doxygen/addon/doxysearch/doxyindexer.cpp File Reference
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <string>
#include <algorithm>
#include <sstream>
#include <fstream>
#include <iterator>
#include <regex>
#include <sys/stat.h>
#include <xapian.h>
#include `version.h`
#include `xml.h`
Classes
class XMLContentHandler
Macros
#define MAX_TERM_LENGTH 245
Functions
static void safeAddTerm (const std::string &term, Xapian::Document &doc, int wfd)
static std::string trim (const std::string &str, const std::string &whitespace=` \t`)
static std::string reduce (const std::string &str, const std::string &fill=` `, const std::string &whitespace=` \t`)
static void addWords (const std::string &s, Xapian::Document &doc, int wfd)
static void addIdentifiers (const std::string &s, Xapian::Document &doc, int wfd)
static void replace_all (std::string &str, const std::string &old, const std::string &repl)
static std::string unescapeXmlEntities (const std::string &s)
static void usage (const char *name, int exitVal=1)
std::string fileToString (const std::string &fileName)
bool dirExists (const char *path)
int main (int argc, const char **argv)
Variables
static char pathSep = '/'
Macro Definition Documentation
MAX_TERM_LENGTH
#define MAX_TERM_LENGTH 245
Definition at line 35 of file doxyindexer.cpp.
Function Documentation
addIdentifiers()
static void addIdentifiers (const std::string & s, Xapian::Document & doc, int wfd) [static]
Adds all identifiers in s to document doc with weight wfd
Definition at line 107 of file doxyindexer.cpp.
{
  std::regex id_re("[A-Z_a-z][A-Z_a-z0-9]*");
  auto id_begin = std::sregex_iterator(s.begin(), s.end(), id_re);
  auto id_end = std::sregex_iterator();
  for (auto i = id_begin; i!=id_end; ++i)
  {
    std::smatch match = *i;
    safeAddTerm(match.str(),doc,wfd);
  }
}
References reg::match(), s, and safeAddTerm().
Referenced by XMLContentHandler::endElement().
addWords()
static void addWords (const std::string & s, Xapian::Document & doc, int wfd) [static]
Adds all words in s to document doc with weight wfd
Definition at line 89 of file doxyindexer.cpp.
{
  std::istringstream iss(s);
  std::istream_iterator<std::string> begin(iss),end,it;
  for (it=begin;it!=end;++it)
  {
    std::string word = *it;
    std::string lword = word;
    std::transform(lword.begin(), lword.end(), lword.begin(), ::tolower);
    safeAddTerm(word,doc,wfd);
    if (lword!=word)
    {
      safeAddTerm(lword,doc,wfd);
    }
  }
}
References ghc::filesystem::begin(), ghc::filesystem::end(), s, safeAddTerm(), string, caseconvert::tolower, and word.
Referenced by XMLContentHandler::endElement().
dirExists()
bool dirExists (const char * path)
Definition at line 304 of file doxyindexer.cpp.
{
  struct stat info = {};
  return stat(path,&info)==0 && (info.st_mode&S_IFDIR);
}
Referenced by main().
fileToString()
std::string fileToString (const std::string & fileName) [inline]
Definition at line 292 of file doxyindexer.cpp.
{
  std::ifstream t(fileName);
  std::string result;
  t.seekg(0, std::ios::end);
  result.reserve(t.tellg());
  t.seekg(0, std::ios::beg);
  result.assign(std::istreambuf_iterator<char>(t),
                std::istreambuf_iterator<char>());
  return result;
}
References ghc::filesystem::end(), and string.
Referenced by createDVIFile(), DoxygenContext::Private::createMathJaxCodeFile(), extractBoundingBox(), findXRefSymbols(), getConvertLatexMacro(), HtmlGenerator::init(), LatexGenerator::init(), main(), LayoutDocManager::parse(), parseCode(), FileDefImpl::parseSource(), parseTagFile(), DocParser::readTextFileByName(), runPlantumlContent(), FileDefImpl::writeSourceBody(), HtmlGenerator::writeStyleInfo(), and writeXMLCodeBlock().
main()
int main (int argc, const char ** argv)
main function to index data
Definition at line 311 of file doxyindexer.cpp.
{
  if (argc<2)
  {
    usage(argv[0]);
  }
  std::string outputDir;
  for (int i=1;i<argc;i++)
  {
    if (std::string(argv[i])=="-o")
    {
      if (i>=argc-1)
      {
        std::cerr << "Error: missing parameter for -o option" << std::endl;
        usage(argv[0]);
      }
      else
      {
        i++;
        outputDir=argv[i];
        if (!dirExists(outputDir.c_str()))
        {
          std::cerr << "Error: specified output directory does not exist!" << std::endl;
          usage(argv[0]);
        }
      }
    }
    else if (std::string(argv[i])=="-h" || std::string(argv[i])=="--help")
    {
      usage(argv[0],0);
    }
    else if (std::string(argv[i])=="-v" || std::string(argv[i])=="--version")
    {
      std::cerr << argv[0] << " version: " << getFullVersion() << std::endl;
      exit(0);
    }
  }
  try
  {
    if (!outputDir.empty() && outputDir.at(outputDir.length()-1)!=pathSep)
    {
      outputDir+=pathSep;
    }
    XMLContentHandler contentHandler(outputDir);
    XMLHandlers handlers;
    handlers.startElement = [&contentHandler](const std::string &name,const XMLHandlers::Attributes &attrs) { contentHandler.startElement(name,attrs); };
    handlers.endElement = [&contentHandler](const std::string &name) { contentHandler.endElement(name); };
    handlers.characters = [&contentHandler](const std::string &chars) { contentHandler.characters(chars); };
    handlers.error = [&contentHandler](const std::string &fileName,int lineNr,const std::string &msg) { contentHandler.error(fileName,lineNr,msg); };
    for (int i=1;i<argc;i++)
    {
      if (std::string(argv[i])=="-o")
      {
        i++;
      }
      else
      {
        std::cout << "Processing " << argv[i] << "..." << std::endl;
        std::string inputStr = fileToString(argv[i]);
        XMLParser parser(handlers);
        parser.parse(argv[i],inputStr.c_str(),false);
      }
    }
  }
  catch(const Xapian::Error &e)
  {
    std::cerr << "Caught exception: " << e.get_description() << std::endl;
  }
  catch(...)
  {
    std::cerr << "Caught an unknown exception" << std::endl;
  }
  return 0;
}
References XMLContentHandler::characters(), XMLHandlers::characters, dirExists(), e, XMLContentHandler::endElement(), XMLHandlers::endElement, XMLContentHandler::error(), XMLHandlers::error, fileToString(), getFullVersion(), msg(), setup::name, XMLParser::parse(), pathSep, XMLContentHandler::startElement(), XMLHandlers::startElement, string, and usage().
reduce()
static std::string reduce (const std::string & str, const std::string & fill = ` `, const std::string & whitespace = ` \t`) [static]
trims whitespace from start and end and replace occurrences of whitespace with fill.
Definition at line 65 of file doxyindexer.cpp.
{
  // trim first
  std::string result = trim(str, whitespace);
  // replace sub ranges
  size_t beginSpace = result.find_first_of(whitespace);
  while (beginSpace != std::string::npos)
  {
    size_t endSpace = result.find_first_not_of(whitespace, beginSpace);
    size_t range = endSpace - beginSpace;
    result.replace(beginSpace, range, fill);
    size_t newStart = beginSpace + fill.length();
    beginSpace = result.find_first_of(whitespace, newStart);
  }
  return result;
}
References translator::fill(), string, and trim().
Referenced by XMLContentHandler::endElement().
replace_all()
static void replace_all (std::string & str, const std::string & old, const std::string & repl) [static]
Replaces all occurrences of old with repl in string str
Definition at line 121 of file doxyindexer.cpp.
{
  size_t pos = 0;
  while ((pos = str.find(old, pos)) != std::string::npos)
  {
    str.replace(pos, old.length(), repl);
    pos += repl.length();
  }
}
Referenced by unescapeXmlEntities().
safeAddTerm()
static void safeAddTerm (const std::string & term, Xapian::Document & doc, int wfd) [static]
Definition at line 43 of file doxyindexer.cpp.
{
  if (term.length()<=MAX_TERM_LENGTH) doc.add_term(term,wfd);
}
References MAX_TERM_LENGTH, and term().
Referenced by addIdentifiers(), addWords(), and XMLContentHandler::endElement().
trim()
static std::string trim (const std::string & str, const std::string & whitespace = ` \t`) [static]
trims whitespace characters from the start and end of string str.
Definition at line 49 of file doxyindexer.cpp.
{
  size_t strBegin = str.find_first_not_of(whitespace);
  if (strBegin == std::string::npos)
    return ""; // no content
  size_t strEnd = str.find_last_not_of(whitespace);
  size_t strRange = strEnd - strBegin + 1;
  return str.substr(strBegin, strRange);
}
Referenced by reduce().
unescapeXmlEntities()
static std::string unescapeXmlEntities (const std::string & s) [static]
Replaces all XML entities in s with their unescaped representation
Definition at line 132 of file doxyindexer.cpp.
{
  std::string result=s;
  replace_all(result,"&gt;",">");
  replace_all(result,"&lt;","<");
  replace_all(result,"&apos;","'");
  replace_all(result,"&quot;","\"");
  replace_all(result,"&amp;","&");
  return result;
}
References replace_all(), s, and string.
Referenced by XMLContentHandler::endElement().
usage()
static void usage (const char * name, int exitVal = 1) [static]
Definition at line 285 of file doxyindexer.cpp.
{
  std::cerr << "Usage: " << name << " [-o output_dir] searchdata.xml [searchdata2.xml ...]" << std::endl;
  exit(exitVal);
}
References setup::name.
Referenced by main().
Variable Documentation
pathSep
char pathSep = '/' [static]
Definition at line 40 of file doxyindexer.cpp.
Referenced by ExistsOnPath(), and main().