doxygen/addon/doxywizard/wizard.cpp File Reference
#include `wizard.h`
#include `input.h`
#include `doxywizard.h`
#include <math.h>
#include <QGridLayout>
#include <QImage>
#include <QLabel>
#include <QHBoxLayout>
#include <QPushButton>
#include <QPixmap>
#include <QPainter>
#include <QMouseEvent>
#include <QLineEdit>
#include <QCheckBox>
#include <QFileInfo>
#include <QFileDialog>
#include <QButtonGroup>
#include <QGroupBox>
#include <QRadioButton>
#include <QTreeWidget>
#include <QStackedWidget>
#include <qdrawutil.h>
Macros
#define STR_PROJECT_NAME QString::fromLatin1(`PROJECT_NAME`)
#define STR_PROJECT_LOGO QString::fromLatin1(`PROJECT_LOGO`)
#define STR_PROJECT_BRIEF QString::fromLatin1(`PROJECT_BRIEF`)
#define STR_INPUT QString::fromLatin1(`INPUT`)
#define STR_OUTPUT_DIRECTORY QString::fromLatin1(`OUTPUT_DIRECTORY`)
#define STR_PROJECT_NUMBER QString::fromLatin1(`PROJECT_NUMBER`)
#define STR_RECURSIVE QString::fromLatin1(`RECURSIVE`)
#define STR_OPTIMIZE_OUTPUT_FOR_C QString::fromLatin1(`OPTIMIZE_OUTPUT_FOR_C`)
#define STR_OPTIMIZE_OUTPUT_JAVA QString::fromLatin1(`OPTIMIZE_OUTPUT_JAVA`)
#define STR_OPTIMIZE_FOR_FORTRAN QString::fromLatin1(`OPTIMIZE_FOR_FORTRAN`)
#define STR_OPTIMIZE_OUTPUT_VHDL QString::fromLatin1(`OPTIMIZE_OUTPUT_VHDL`)
#define STR_OPTIMIZE_OUTPUT_SLICE QString::fromLatin1(`OPTIMIZE_OUTPUT_SLICE`)
#define STR_CPP_CLI_SUPPORT QString::fromLatin1(`CPP_CLI_SUPPORT`)
#define STR_HIDE_SCOPE_NAMES QString::fromLatin1(`HIDE_SCOPE_NAMES`)
#define STR_EXTRACT_ALL QString::fromLatin1(`EXTRACT_ALL`)
#define STR_SOURCE_BROWSER QString::fromLatin1(`SOURCE_BROWSER`)
#define STR_GENERATE_HTML QString::fromLatin1(`GENERATE_HTML`)
#define STR_GENERATE_LATEX QString::fromLatin1(`GENERATE_LATEX`)
#define STR_GENERATE_MAN QString::fromLatin1(`GENERATE_MAN`)
#define STR_GENERATE_RTF QString::fromLatin1(`GENERATE_RTF`)
#define STR_GENERATE_XML QString::fromLatin1(`GENERATE_XML`)
#define STR_GENERATE_DOCBOOK QString::fromLatin1(`GENERATE_DOCBOOK`)
#define STR_GENERATE_HTMLHELP QString::fromLatin1(`GENERATE_HTMLHELP`)
#define STR_GENERATE_TREEVIEW QString::fromLatin1(`GENERATE_TREEVIEW`)
#define STR_USE_PDFLATEX QString::fromLatin1(`USE_PDFLATEX`)
#define STR_PDF_HYPERLINKS QString::fromLatin1(`PDF_HYPERLINKS`)
#define STR_SEARCHENGINE QString::fromLatin1(`SEARCHENGINE`)
#define STR_HAVE_DOT QString::fromLatin1(`HAVE_DOT`)
#define STR_CLASS_GRAPH QString::fromLatin1(`CLASS_GRAPH`)
#define STR_COLLABORATION_GRAPH QString::fromLatin1(`COLLABORATION_GRAPH`)
#define STR_GRAPHICAL_HIERARCHY QString::fromLatin1(`GRAPHICAL_HIERARCHY`)
#define STR_INCLUDE_GRAPH QString::fromLatin1(`INCLUDE_GRAPH`)
#define STR_INCLUDED_BY_GRAPH QString::fromLatin1(`INCLUDED_BY_GRAPH`)
#define STR_CALL_GRAPH QString::fromLatin1(`CALL_GRAPH`)
#define STR_CALLER_GRAPH QString::fromLatin1(`CALLER_GRAPH`)
#define STR_HTML_COLORSTYLE_HUE QString::fromLatin1(`HTML_COLORSTYLE_HUE`)
#define STR_HTML_COLORSTYLE_SAT QString::fromLatin1(`HTML_COLORSTYLE_SAT`)
#define STR_HTML_COLORSTYLE_GAMMA QString::fromLatin1(`HTML_COLORSTYLE_GAMMA`)
Functions
static bool stringVariantToBool (const QVariant &v)
static bool getBoolOption (const QHash< QString, Input * > &model, const QString &name)
static int getIntOption (const QHash< QString, Input * > &model, const QString &name)
static QString getStringOption (const QHash< QString, Input * > &model, const QString &name)
static void updateBoolOption (const QHash< QString, Input * > &model, const QString &name, bool bNew)
static void updateIntOption (const QHash< QString, Input * > &model, const QString &name, int iNew)
static void updateStringOption (const QHash< QString, Input * > &model, const QString &name, const QString &s)
void hsl2rgb (double h, double s, double l, double *pRed, double *pGreen, double *pBlue)
Variables
static bool g_optimizeMapping [7][7]
static QString g_optimizeOptionNames [7]
Macro Definition Documentation
STR_CALL_GRAPH
#define STR_CALL_GRAPH QString::fromLatin1(`CALL_GRAPH`)
Definition at line 73 of file wizard.cpp.
STR_CALLER_GRAPH
#define STR_CALLER_GRAPH QString::fromLatin1(`CALLER_GRAPH`)
Definition at line 74 of file wizard.cpp.
STR_CLASS_GRAPH
#define STR_CLASS_GRAPH QString::fromLatin1(`CLASS_GRAPH`)
Definition at line 68 of file wizard.cpp.
STR_COLLABORATION_GRAPH
#define STR_COLLABORATION_GRAPH QString::fromLatin1(`COLLABORATION_GRAPH`)
Definition at line 69 of file wizard.cpp.
STR_CPP_CLI_SUPPORT
#define STR_CPP_CLI_SUPPORT QString::fromLatin1(`CPP_CLI_SUPPORT`)
Definition at line 52 of file wizard.cpp.
STR_EXTRACT_ALL
#define STR_EXTRACT_ALL QString::fromLatin1(`EXTRACT_ALL`)
Definition at line 54 of file wizard.cpp.
STR_GENERATE_DOCBOOK
#define STR_GENERATE_DOCBOOK QString::fromLatin1(`GENERATE_DOCBOOK`)
Definition at line 61 of file wizard.cpp.
STR_GENERATE_HTML
#define STR_GENERATE_HTML QString::fromLatin1(`GENERATE_HTML`)
Definition at line 56 of file wizard.cpp.
STR_GENERATE_HTMLHELP
#define STR_GENERATE_HTMLHELP QString::fromLatin1(`GENERATE_HTMLHELP`)
Definition at line 62 of file wizard.cpp.
STR_GENERATE_LATEX
#define STR_GENERATE_LATEX QString::fromLatin1(`GENERATE_LATEX`)
Definition at line 57 of file wizard.cpp.
STR_GENERATE_MAN
#define STR_GENERATE_MAN QString::fromLatin1(`GENERATE_MAN`)
Definition at line 58 of file wizard.cpp.
STR_GENERATE_RTF
#define STR_GENERATE_RTF QString::fromLatin1(`GENERATE_RTF`)
Definition at line 59 of file wizard.cpp.
STR_GENERATE_TREEVIEW
#define STR_GENERATE_TREEVIEW QString::fromLatin1(`GENERATE_TREEVIEW`)
Definition at line 63 of file wizard.cpp.
STR_GENERATE_XML
#define STR_GENERATE_XML QString::fromLatin1(`GENERATE_XML`)
Definition at line 60 of file wizard.cpp.
STR_GRAPHICAL_HIERARCHY
#define STR_GRAPHICAL_HIERARCHY QString::fromLatin1(`GRAPHICAL_HIERARCHY`)
Definition at line 70 of file wizard.cpp.
STR_HAVE_DOT
#define STR_HAVE_DOT QString::fromLatin1(`HAVE_DOT`)
Definition at line 67 of file wizard.cpp.
STR_HIDE_SCOPE_NAMES
#define STR_HIDE_SCOPE_NAMES QString::fromLatin1(`HIDE_SCOPE_NAMES`)
Definition at line 53 of file wizard.cpp.
STR_HTML_COLORSTYLE_GAMMA
#define STR_HTML_COLORSTYLE_GAMMA QString::fromLatin1(`HTML_COLORSTYLE_GAMMA`)
Definition at line 77 of file wizard.cpp.
STR_HTML_COLORSTYLE_HUE
#define STR_HTML_COLORSTYLE_HUE QString::fromLatin1(`HTML_COLORSTYLE_HUE`)
Definition at line 75 of file wizard.cpp.
STR_HTML_COLORSTYLE_SAT
#define STR_HTML_COLORSTYLE_SAT QString::fromLatin1(`HTML_COLORSTYLE_SAT`)
Definition at line 76 of file wizard.cpp.
STR_INCLUDE_GRAPH
#define STR_INCLUDE_GRAPH QString::fromLatin1(`INCLUDE_GRAPH`)
Definition at line 71 of file wizard.cpp.
STR_INCLUDED_BY_GRAPH
#define STR_INCLUDED_BY_GRAPH QString::fromLatin1(`INCLUDED_BY_GRAPH`)
Definition at line 72 of file wizard.cpp.
STR_INPUT
#define STR_INPUT QString::fromLatin1(`INPUT`)
Definition at line 43 of file wizard.cpp.
STR_OPTIMIZE_FOR_FORTRAN
#define STR_OPTIMIZE_FOR_FORTRAN QString::fromLatin1(`OPTIMIZE_FOR_FORTRAN`)
Definition at line 49 of file wizard.cpp.
STR_OPTIMIZE_OUTPUT_FOR_C
#define STR_OPTIMIZE_OUTPUT_FOR_C QString::fromLatin1(`OPTIMIZE_OUTPUT_FOR_C`)
Definition at line 47 of file wizard.cpp.
STR_OPTIMIZE_OUTPUT_JAVA
#define STR_OPTIMIZE_OUTPUT_JAVA QString::fromLatin1(`OPTIMIZE_OUTPUT_JAVA`)
Definition at line 48 of file wizard.cpp.
STR_OPTIMIZE_OUTPUT_SLICE
#define STR_OPTIMIZE_OUTPUT_SLICE QString::fromLatin1(`OPTIMIZE_OUTPUT_SLICE`)
Definition at line 51 of file wizard.cpp.
STR_OPTIMIZE_OUTPUT_VHDL
#define STR_OPTIMIZE_OUTPUT_VHDL QString::fromLatin1(`OPTIMIZE_OUTPUT_VHDL`)
Definition at line 50 of file wizard.cpp.
STR_OUTPUT_DIRECTORY
#define STR_OUTPUT_DIRECTORY QString::fromLatin1(`OUTPUT_DIRECTORY`)
Definition at line 44 of file wizard.cpp.
STR_PDF_HYPERLINKS
#define STR_PDF_HYPERLINKS QString::fromLatin1(`PDF_HYPERLINKS`)
Definition at line 65 of file wizard.cpp.
STR_PROJECT_BRIEF
#define STR_PROJECT_BRIEF QString::fromLatin1(`PROJECT_BRIEF`)
Definition at line 42 of file wizard.cpp.
STR_PROJECT_LOGO
#define STR_PROJECT_LOGO QString::fromLatin1(`PROJECT_LOGO`)
Definition at line 41 of file wizard.cpp.
STR_PROJECT_NAME
#define STR_PROJECT_NAME QString::fromLatin1(`PROJECT_NAME`)
Definition at line 40 of file wizard.cpp.
STR_PROJECT_NUMBER
#define STR_PROJECT_NUMBER QString::fromLatin1(`PROJECT_NUMBER`)
Definition at line 45 of file wizard.cpp.
STR_RECURSIVE
#define STR_RECURSIVE QString::fromLatin1(`RECURSIVE`)
Definition at line 46 of file wizard.cpp.
STR_SEARCHENGINE
#define STR_SEARCHENGINE QString::fromLatin1(`SEARCHENGINE`)
Definition at line 66 of file wizard.cpp.
STR_SOURCE_BROWSER
#define STR_SOURCE_BROWSER QString::fromLatin1(`SOURCE_BROWSER`)
Definition at line 55 of file wizard.cpp.
STR_USE_PDFLATEX
#define STR_USE_PDFLATEX QString::fromLatin1(`USE_PDFLATEX`)
Definition at line 64 of file wizard.cpp.
Function Documentation
getBoolOption()
static bool getBoolOption (const QHash< QString, Input * > & model, const QString & name) [static]
Definition at line 117 of file wizard.cpp.
{
  Input *option = model[name];
  Q_ASSERT(option!=0);
  return stringVariantToBool(option->value());
}
References setup::name, stringVariantToBool(), and Input::value().
Referenced by Step1::init(), Step2::init(), Step3::init(), and Step4::init().
getIntOption()
static int getIntOption (const QHash< QString, Input * > & model, const QString & name) [static]
Definition at line 125 of file wizard.cpp.
{
  Input *option = model[name];
  Q_ASSERT(option!=0);
  return option->value().toInt();
}
References setup::name, and Input::value().
Referenced by Step3::tuneColorDialog().
getStringOption()
static QString getStringOption (const QHash< QString, Input * > & model, const QString & name) [static]
Definition at line 133 of file wizard.cpp.
{
  Input *option = model[name];
  Q_ASSERT(option!=0);
  return option->value().toString();
}
References setup::name, and Input::value().
Referenced by Step1::init(), Step4::init(), and Step4::setClassGraphEnabled().
hsl2rgb()
void hsl2rgb (double h, double s, double l, double * pRed, double * pGreen, double * pBlue)
Definition at line 228 of file wizard.cpp.
{
  double v;
  double r,g,b;
  r = l; // default to gray
  g = l;
  b = l;
  v = (l <= 0.5) ? (l * (1.0 + s)) : (l + s - l * s);
  if (v > 0)
  {
    double m;
    double sv;
    int sextant;
    double fract, vsf, mid1, mid2;
    m = l + l - v;
    sv = (v - m) / v;
    h *= 6.0;
    sextant = (int)h;
    fract = h - sextant;
    vsf = v * sv * fract;
    mid1 = m + vsf;
    mid2 = v - vsf;
    switch (sextant)
    {
      case 0:
        r = v;
        g = mid1;
        b = m;
        break;
      case 1:
        r = mid2;
        g = v;
        b = m;
        break;
      case 2:
        r = m;
        g = v;
        b = mid1;
        break;
      case 3:
        r = m;
        g = mid2;
        b = v;
        break;
      case 4:
        r = mid1;
        g = m;
        b = v;
        break;
      case 5:
        r = v;
        g = m;
        b = mid2;
        break;
    }
  }
  *pRed = r;
  *pGreen = g;
  *pBlue = b;
}
References b, g, h, r, and s.
Referenced by TuneColorDialog::updateImage().
stringVariantToBool()
static bool stringVariantToBool (const QVariant & v) [static]
Definition at line 111 of file wizard.cpp.
{
  QString s = v.toString().toLower();
  return s==QString::fromLatin1("yes") || s==QString::fromLatin1("true") || s==QString::fromLatin1("1");
}
References s.
Referenced by getBoolOption(), and updateBoolOption().
updateBoolOption()
static void updateBoolOption (const QHash< QString, Input * > & model, const QString & name, bool bNew) [static]
Definition at line 141 of file wizard.cpp.
{
  Input *option = model[name];
  Q_ASSERT(option!=0);
  bool bOld = stringVariantToBool(option->value());
  if (bOld!=bNew)
  {
    option->value()=QString::fromLatin1(bNew ? "true" : "false");
    option->update();
  }
}
References setup::name, stringVariantToBool(), Input::update(), and Input::value().
Referenced by Step2::changeCrossRefState(), Step4::diagramModeChanged(), Step2::extractMode(), Step2::optimizeFor(), Step4::setCallerGraphEnabled(), Step4::setCallGraphEnabled(), Step4::setCollaborationGraphEnabled(), Step3::setDocbookEnabled(), Step4::setGraphicalHierarchyEnabled(), Step3::setHtmlEnabled(), Step3::setHtmlOptions(), Step4::setIncludedByGraphEnabled(), Step4::setIncludeGraphEnabled(), Step3::setLatexEnabled(), Step3::setLatexOptions(), Step3::setManEnabled(), Step1::setRecursiveScan(), Step3::setRtfEnabled(), Step3::setSearchEnabled(), and Step3::setXmlEnabled().
updateIntOption()
static void updateIntOption (const QHash< QString, Input * > & model, const QString & name, int iNew) [static]
Definition at line 154 of file wizard.cpp.
{
  Input *option = model[name];
  Q_ASSERT(option!=0);
  int iOld = option->value().toInt();
  if (iOld!=iNew)
  {
    option->value()=QString::fromLatin1("%1").arg(iNew);
    option->update();
  }
}
References setup::name, Input::update(), and Input::value().
Referenced by Step3::tuneColorDialog().
updateStringOption()
static void updateStringOption (const QHash< QString, Input * > & model, const QString & name, const QString & s) [static]
Definition at line 168 of file wizard.cpp.
{
  Input *option = model[name];
  Q_ASSERT(option!=0);
  if (option->value().toString()!=s)
  {
    option->value() = s;
    option->update();
  }
}
References setup::name, s, Input::update(), and Input::value().
Referenced by Step4::diagramModeChanged(), Step1::selectProjectIcon(), Step4::setClassGraphEnabled(), Step1::setDestinationDir(), Step1::setProjectBrief(), Step1::setProjectName(), and Step1::setProjectNumber().
Variable Documentation
g_optimizeMapping
bool g_optimizeMapping[7][7] [static]
Initial value:
=
{
  
  
  
  
  
  
  
  
  { false,false,false,false,false,false,false },
  { false,false,false,false,true, false,false },
  { false,true, false,false,false,false,false },
  { true, false,false,false,false,true, false },
  { false,false,true, false,false,false,false },
  { false,false,false,true, false,false,false },
  { false,false,false,false,false,false,true },
}
Definition at line 79 of file wizard.cpp.
Referenced by Step2::optimizeFor().
g_optimizeOptionNames
QString g_optimizeOptionNames[7] [static]
Initial value:
=
{
  STR_OPTIMIZE_OUTPUT_FOR_C,
  STR_OPTIMIZE_OUTPUT_JAVA,
  STR_OPTIMIZE_FOR_FORTRAN,
  STR_OPTIMIZE_OUTPUT_VHDL,
  STR_CPP_CLI_SUPPORT,
  STR_HIDE_SCOPE_NAMES,
  STR_OPTIMIZE_OUTPUT_SLICE
}
Definition at line 98 of file wizard.cpp.
Referenced by Step2::optimizeFor().