doxygen/addon/doxyapp/doxyapp.cpp File Reference
Example of how to use doxygen as part of another GPL applications.
#include <stdlib.h>
#include `dir.h`
#include `doxygen.h`
#include `outputgen.h`
#include `parserintf.h`
#include `classdef.h`
#include `namespacedef.h`
#include `filedef.h`
#include `util.h`
#include `classlist.h`
#include `config.h`
#include `filename.h`
#include `version.h`
Classes
class XRefDummyCodeGenerator
Functions
static void findXRefSymbols (FileDef *fd)
static void listSymbol (Definition *d)
static void listSymbols ()
static void lookupSymbol (const Definition *d)
static void lookupSymbols (const QCString &sym)
int main (int argc, char **argv)
Detailed Description
Example of how to use doxygen as part of another GPL applications.
This example shows how to configure and run doxygen programmatically from within an application without generating the usual output. The example should work on any Unix like OS (including Linux and Mac OS X).
This example shows how to use to code parser to get cross-references information and it also shows how to look up symbols in a program parsed by doxygen and show some information about them.
Definition in file doxyapp.cpp.
Function Documentation
findXRefSymbols()
static void findXRefSymbols (FileDef * fd) [static]
Definition at line 109 of file doxyapp.cpp.
{
  // get the interface to a parser that matches the file extension
  auto intf=Doxygen::parserManager->getCodeParser(fd->getDefFileExtension());
  // get the programming language from the file name
  SrcLangExt lang = getLanguageFromFileName(fd->name());
  // reset the parsers state
  intf->resetCodeParserState();
  // create a new backend object
  XRefDummyCodeGenerator *xrefGen = new XRefDummyCodeGenerator(fd);
  // parse the source code
  intf->parseCode(*xrefGen,
                0,
                fileToString(fd->absFilePath()),
                lang,
                FALSE,
                0,
                fd);
  // dismiss the object.
  delete xrefGen;
}
References FileDef::absFilePath(), FALSE, fileToString(), ParserManager::getCodeParser(), Definition::getDefFileExtension(), getLanguageFromFileName(), FileDef::name(), and Doxygen::parserManager.
Referenced by main().
listSymbol()
static void listSymbol (Definition * d) [static]
Definition at line 136 of file doxyapp.cpp.
{
  if (d!=Doxygen::globalScope && // skip the global namespace symbol
      d->name().at(0)!='@' // skip anonymous stuff
     )
  {
    printf("%s\n",
        d->name().data());
  }
}
References QCString::at(), QCString::data(), Doxygen::globalScope, and Definition::name().
Referenced by listSymbols().
listSymbols()
static void listSymbols () [static]
Definition at line 147 of file doxyapp.cpp.
{
  for (const auto &kv : *Doxygen::symbolMap)
  {
    for (const auto &def : kv.second)
    {
      listSymbol(def);
    }
  }
}
References listSymbol(), and Doxygen::symbolMap.
Referenced by main().
lookupSymbol()
static void lookupSymbol (const Definition * d) [static]
Definition at line 158 of file doxyapp.cpp.
{
  if (d!=Doxygen::globalScope && // skip the global namespace symbol
      d->name().at(0)!='@' // skip anonymous stuff
     )
  {
    printf("Symbol info\n");
    printf("-----------\n");
    printf("Name: %s\n",d->name().data());
    printf("File: %s\n",d->getDefFileName().data());
    printf("Line: %d\n",d->getDefLine());
    // depending on the definition type we can case to the appropriate
    // derived to get additional information
    switch (d->definitionType())
    {
      case Definition::TypeClass:
        {
          const ClassDef *cd = dynamic_cast<const ClassDef*>(d);
          printf("Kind: %s\n",cd->compoundTypeString().data());
        }
        break;
      case Definition::TypeFile:
        {
          const FileDef *fd = dynamic_cast<const FileDef*>(d);
          printf("Kind: File: #includes %zu other files\n",
              fd->includeFileList().size());
        }
        break;
      case Definition::TypeNamespace:
        {
          const NamespaceDef *nd = dynamic_cast<const NamespaceDef*>(d);
          printf("Kind: Namespace: contains %zu classes and %zu namespaces\n",
              nd->getClasses().size(),
              nd->getNamespaces().size());
        }
        break;
      case Definition::TypeMember:
        {
          const MemberDef *md = dynamic_cast<const MemberDef*>(d);
          printf("Kind: %s\n",md->memberTypeName().data());
        }
        break;
      default:
        // ignore groups/pages/packages/dirs for now
        break;
    }
  }
}
References QCString::at(), ClassDef::compoundTypeString(), QCString::data(), Definition::definitionType(), NamespaceDef::getClasses(), Definition::getDefFileName(), Definition::getDefLine(), NamespaceDef::getNamespaces(), Doxygen::globalScope, FileDef::includeFileList(), MemberDef::memberTypeName(), Definition::name(), LinkedRefMap< T, Hash, KeyEqual, Map >::size(), Definition::TypeClass, Definition::TypeFile, Definition::TypeMember, and Definition::TypeNamespace.
Referenced by lookupSymbols().
lookupSymbols()
static void lookupSymbols (const QCString & sym) [static]
Definition at line 207 of file doxyapp.cpp.
{
  if (!sym.isEmpty())
  {
    auto range = Doxygen::symbolMap->find(sym);
    bool found=false;
    for (const Definition *def : range)
    {
      lookupSymbol(def);
      found=true;
    }
    if (!found)
    {
      printf("Unknown symbol\n");
    }
  }
}
References SymbolMap< T >::find(), found, QCString::isEmpty(), lookupSymbol(), and Doxygen::symbolMap.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 225 of file doxyapp.cpp.
{
  char cmd[256];
  int locArgc = argc;
  if (locArgc == 2)
  {
    if (!strcmp(argv[1],"--help"))
    {
      printf("Usage: %s [source_file | source_dir]\n",argv[0]);
      exit(0);
    }
    else if (!strcmp(argv[1],"--version"))
    {
      printf("%s version: %s\n",argv[0],getFullVersion());
      exit(0);
    }
  }
  if (locArgc!=2)
  {
    printf("Usage: %s [source_file | source_dir]\n",argv[0]);
    exit(1);
  }
  // initialize data structures
  initDoxygen();
  // setup the non-default configuration options
  checkConfiguration();
  adjustConfiguration();
  // we need a place to put intermediate files
  Config_updateString(OUTPUT_DIRECTORY,"/tmp/doxygen");
  // disable html output
  Config_updateBool(GENERATE_HTML,FALSE);
  // disable latex output
  Config_updateBool(GENERATE_LATEX,FALSE);
  // be quiet
  Config_updateBool(QUIET,TRUE);
  // turn off warnings
  Config_updateBool(WARNINGS,FALSE);
  Config_updateBool(WARN_IF_UNDOCUMENTED,FALSE);
  Config_updateBool(WARN_IF_DOC_ERROR,FALSE);
  // Extract as much as possible
  Config_updateBool(EXTRACT_ALL,TRUE);
  Config_updateBool(EXTRACT_STATIC,TRUE);
  Config_updateBool(EXTRACT_PRIVATE,TRUE);
  Config_updateBool(EXTRACT_LOCAL_METHODS,TRUE);
  // Extract source browse information, needed
  // to make doxygen gather the cross reference info
  Config_updateBool(SOURCE_BROWSER,TRUE);
  // In case of a directory take all files on directory and its subdirectories
  Config_updateBool(RECURSIVE,TRUE);
  // set the input
  StringVector inputList;
  inputList.push_back(argv[1]);
  Config_updateList(INPUT,inputList);
  // parse the files
  parseInput();
  // iterate over the input files
  for (const auto &fn : *Doxygen::inputNameLinkedMap)
  {
    for (const auto &fd : *fn)
    {
      // get the references (linked and unlinked) found in this file
      findXRefSymbols(fd.get());
    }
  }
  // clean up after us
  Dir().rmdir("/tmp/doxygen");
  while (1)
  {
    printf("> Type a symbol name or\n> .list for a list of symbols or\n> .quit to exit\n> ");
    fgets(cmd,256,stdin);
    QCString s(cmd);
    if (s.at(s.length()-1)=='\n') s=s.left(s.length()-1); // strip trailing \n
    if (s==".list")
      listSymbols();
    else if (s==".quit")
      exit(0);
    else
      lookupSymbols(s);
  }
}
References adjustConfiguration(), checkConfiguration(), Config_updateBool, Config_updateList, Config_updateString, FALSE, findXRefSymbols(), getFullVersion(), initDoxygen(), Doxygen::inputNameLinkedMap, listSymbols(), lookupSymbols(), parseInput(), Dir::rmdir(), s, strcmp(), and TRUE.