doxygen/addon/doxywizard/config_msg.cpp File Reference
#include <QString>
#include `config_msg.h`
#include `doxywizard.h`
Functions
void config_err (const char *fmt,...)
void config_term (const char *fmt,...)
void config_warn (const char *fmt,...)
void config_open ()
void config_finish ()
Variables
static QString warning_str = QString::fromLatin1(`warning: `)
static QString error_str = QString::fromLatin1(`error: `)
Function Documentation
config_err()
void config_err (const char * fmt, ...)
Definition at line 8 of file config_msg.cpp.
{
  QString msg = error_str;
  msg.append(QString::fromLatin1(fmt));
  va_list args;
  va_start(args, fmt);
  char debugOut[1000]; // this size should be sufficient
  vsnprintf(debugOut, 1000,qPrintable(msg), args);
  MainWindow::instance().outputLogText(QString::fromLatin1(debugOut));
  va_end(args);
}
References error_str, fmt, MainWindow::instance(), msg(), and MainWindow::outputLogText().
Referenced by readIncludeFile(), and tryPath().
config_finish()
void config_finish ()
Definition at line 53 of file config_msg.cpp.
{
  MainWindow::instance().outputLogFinish();
}
References MainWindow::instance(), and MainWindow::outputLogFinish().
Referenced by parseConfig().
config_open()
void config_open ()
Definition at line 48 of file config_msg.cpp.
{
  MainWindow::instance().outputLogStart();
}
References MainWindow::instance(), and MainWindow::outputLogStart().
Referenced by parseConfig().
config_term()
void config_term (const char * fmt, ...)
Definition at line 21 of file config_msg.cpp.
{
  QString msg = error_str;
  msg.append(QString::fromLatin1(fmt));
  va_list args;
  va_start(args, fmt);
  char debugOut[1000]; // this size should be sufficient
  vsnprintf(debugOut, 1000,qPrintable(msg), args);
  MainWindow::instance().outputLogText(QString::fromLatin1(debugOut));
  va_end(args);
  exit(1);
}
References error_str, fmt, MainWindow::instance(), msg(), and MainWindow::outputLogText().
config_warn()
void config_warn (const char * fmt, ...)
Definition at line 35 of file config_msg.cpp.
{
  QString msg = warning_str;
  msg.append(QString::fromLatin1(fmt));
  va_list args;
  va_start(args, fmt);
  char debugOut[1000];
  vsnprintf(debugOut, 1000,qPrintable(msg), args);
  MainWindow::instance().outputLogText(QString::fromLatin1(debugOut));
  va_end(args);
}
References fmt, MainWindow::instance(), msg(), MainWindow::outputLogText(), and warning_str.
Referenced by InputString::checkEnumVal(), processList(), processString(), InputInt::setValue(), InputBool::update(), InputInt::update(), and upgradeConfig().
Variable Documentation
error_str
QString error_str = QString::fromLatin1(`error: `) [static]
Definition at line 6 of file config_msg.cpp.
Referenced by config_err(), and config_term().
warning_str
QString warning_str = QString::fromLatin1(`warning: `) [static]
Definition at line 5 of file config_msg.cpp.
Referenced by config_warn().