doxygen/build/doxygen/src/stlsupport.cpp File Reference
#include `stlsupport.h`
#include `entry.h`
#include `config.h`
Classes
struct STLInfo
Functions
static void addSTLMember (const std::shared_ptr< Entry > &root, const char *type, const char *name)
static void addSTLIterator (const std::shared_ptr< Entry > &classEntry, const QCString &name)
static void addSTLClass (const std::shared_ptr< Entry > &root, const STLInfo *info)
static void addSTLClasses (const std::shared_ptr< Entry > &root)
void addSTLSupport (std::shared_ptr< Entry > &root)
Variables
static STLInfo g_stlinfo []
Function Documentation
addSTLClass()
static void addSTLClass (const std::shared_ptr< Entry > & root, const STLInfo * info) [static]
Definition at line 165 of file stlsupport.cpp.
{
  //printf("Adding STL class %s\n",info->className);
  QCString fullName = info->className;
  fullName.prepend("std::");
  // add fake Entry for the class
  std::shared_ptr<Entry> classEntry = std::make_shared<Entry>();
  classEntry->fileName = "[STL]";
  classEntry->startLine = 1;
  classEntry->name = fullName;
  classEntry->section = Entry::CLASS_SEC;
  classEntry->brief = "STL class";
  classEntry->hidden = FALSE;
  classEntry->artificial= TRUE;
  // add template arguments to class
  if (info->templType1)
  {
    ArgumentList al;
    Argument a;
    a.type="typename";
    a.name=info->templType1;
    al.push_back(a);
    if (info->templType2) // another template argument
    {
      a.type="typename";
      a.name=info->templType2;
      al.push_back(a);
    }
    classEntry->tArgLists.push_back(al);
  }
  // add member variables
  if (info->templName1)
  {
    addSTLMember(classEntry,info->templType1,info->templName1);
  }
  if (info->templName2)
  {
    addSTLMember(classEntry,info->templType2,info->templName2);
  }
  if (fullName=="std::auto_ptr" ||
      fullName=="std::smart_ptr" ||
      fullName=="std::shared_ptr" ||
      fullName=="std::weak_ptr" ||
      fullName=="std::unique_ptr")
  {
    std::shared_ptr<Entry> memEntry = std::make_shared<Entry>();
    memEntry->name = "operator->";
    memEntry->args = "()";
    memEntry->type = "T*";
    memEntry->protection = Public;
    memEntry->section = Entry::FUNCTION_SEC;
    memEntry->brief = "STL member";
    memEntry->hidden = FALSE;
    memEntry->artificial = FALSE;
    classEntry->moveToSubEntryAndKeep(memEntry);
  }
  if (info->baseClass1)
  {
    classEntry->extends.push_back(BaseInfo(info->baseClass1,Public,info->virtualInheritance?Virtual:Normal));
  }
  if (info->baseClass2)
  {
    classEntry->extends.push_back(BaseInfo(info->baseClass2,Public,info->virtualInheritance?Virtual:Normal));
  }
  if (info->iterators)
  {
    // add iterator class
    addSTLIterator(classEntry,fullName+"::iterator");
    addSTLIterator(classEntry,fullName+"::const_iterator");
    addSTLIterator(classEntry,fullName+"::reverse_iterator");
    addSTLIterator(classEntry,fullName+"::const_reverse_iterator");
  }
  root->moveToSubEntryAndKeep(classEntry);
}
References a, addSTLIterator(), addSTLMember(), STLInfo::baseClass1, STLInfo::baseClass2, Entry::CLASS_SEC, STLInfo::className, FALSE, Entry::FUNCTION_SEC, STLInfo::iterators, Normal, QCString::prepend(), Public, ArgumentList::push_back(), STLInfo::templName1, STLInfo::templName2, STLInfo::templType1, STLInfo::templType2, TRUE, Virtual, and STLInfo::virtualInheritance.
Referenced by addSTLClasses().
addSTLClasses()
static void addSTLClasses (const std::shared_ptr< Entry > & root) [static]
Definition at line 243 of file stlsupport.cpp.
{
  std::shared_ptr<Entry> namespaceEntry = std::make_shared<Entry>();
  namespaceEntry->fileName = "[STL]";
  namespaceEntry->startLine = 1;
  namespaceEntry->name = "std";
  namespaceEntry->section = Entry::NAMESPACE_SEC;
  namespaceEntry->brief = "STL namespace";
  namespaceEntry->hidden = FALSE;
  namespaceEntry->artificial= TRUE;
  STLInfo *info = g_stlinfo;
  while (info->className)
  {
    addSTLClass(namespaceEntry,info);
    info++;
  }
  root->moveToSubEntryAndKeep(namespaceEntry);
}
References addSTLClass(), STLInfo::className, FALSE, g_stlinfo, Entry::NAMESPACE_SEC, and TRUE.
Referenced by addSTLSupport().
addSTLIterator()
static void addSTLIterator (const std::shared_ptr< Entry > & classEntry, const QCString & name) [static]
Definition at line 152 of file stlsupport.cpp.
{
  std::shared_ptr<Entry> iteratorClassEntry = std::make_shared<Entry>();
  iteratorClassEntry->fileName = "[STL]";
  iteratorClassEntry->startLine = 1;
  iteratorClassEntry->name = name;
  iteratorClassEntry->section = Entry::CLASS_SEC;
  iteratorClassEntry->brief = "STL iterator class";
  iteratorClassEntry->hidden = FALSE;
  iteratorClassEntry->artificial= TRUE;
  classEntry->moveToSubEntryAndKeep(iteratorClassEntry);
}
References Entry::CLASS_SEC, FALSE, setup::name, and TRUE.
Referenced by addSTLClass().
addSTLMember()
static void addSTLMember (const std::shared_ptr< Entry > & root, const char * type, const char * name) [static]
Definition at line 139 of file stlsupport.cpp.
{
  std::shared_ptr<Entry> memEntry = std::make_shared<Entry>();
  memEntry->name = name;
  memEntry->type = type;
  memEntry->protection = Public;
  memEntry->section = Entry::VARIABLE_SEC;
  memEntry->brief = "STL member";
  memEntry->hidden = FALSE;
  memEntry->artificial = TRUE;
  root->moveToSubEntryAndKeep(memEntry);
}
References FALSE, setup::name, Public, TRUE, and Entry::VARIABLE_SEC.
Referenced by addSTLClass().
addSTLSupport()
void addSTLSupport (std::shared_ptr< Entry > & root)
Add stub entries for the most used classes in the standard template library
Parameters
root Root of the entry tree to add the entries to.
Definition at line 264 of file stlsupport.cpp.
{
  if (Config_getBool(BUILTIN_STL_SUPPORT))
  {
    addSTLClasses(root);
  }
}
References addSTLClasses(), and Config_getBool.
Referenced by parseInput().
Variable Documentation
g_stlinfo
STLInfo g_stlinfo[] [static]
Definition at line 34 of file stlsupport.cpp.
Referenced by addSTLClasses().