doxygen/build/doxygen/libversion/fullversion.cpp File Reference
#include <string.h>
#include <version.h>
Macros
#define BUF_SIZE 100
Functions
const char * getFullVersion (void)
Macro Definition Documentation
BUF_SIZE
#define BUF_SIZE 100
Function Documentation
getFullVersion()
const char * getFullVersion (void)
Definition at line 4 of file fullversion.cpp.
{
#define BUF_SIZE 100
  static char fullVersionString[BUF_SIZE];
  static bool init = false;
  if (!init)
  {
    strncpy(fullVersionString,getDoxygenVersion(),BUF_SIZE-1);
    if (strlen(getGitVersion())>0)
    {
      strncat(fullVersionString," (",BUF_SIZE-1);
      strncat(fullVersionString,getGitVersion(),BUF_SIZE-1);
      strncat(fullVersionString,")",BUF_SIZE-1);
    }
    fullVersionString[BUF_SIZE-1]='\0';
    init = true;
  }
  return fullVersionString;
}
References BUF_SIZE, getDoxygenVersion(), getGitVersion(), and Config::init().
Referenced by ConfigImpl::compareDoxyfile(), main(), parseInput(), readConfiguration(), and version().