doxygen/build/doxygen/libmscgen/mscgen_api.c File Reference
#include `mscgen_api.h`
#include `mscgen_config.h`
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <limits.h>
#include <unistd.h>
#include <errno.h>
#include <ctype.h>
#include <assert.h>
#include `mscgen_lexer.h`
#include `mscgen_adraw.h`
#include `mscgen_msc.h`
#include `mscgen_safe.h`
Classes
struct GlobalOptionsTag
struct RowInfo
struct ContextTag
Macros
#define M_Max(a, b) (((a) > (b)) ? (a) : (b))
#define M_Min(a, b) (((a) < (b)) ? (a) : (b))
Typedefs
typedef struct GlobalOptionsTag GlobalOptions
typedef struct ContextTag Context
Functions
static unsigned int countLines (const char *l)
static Boolean isBoxArc (const MscArcType a)
static int getArcGradient (Context *ctx, Msc m, const RowInfo *rowInfo, unsigned int row)
static Boolean isBroadcastArc (const char *entity)
static void freeLabelLines (unsigned int n, char **lines)
static char * splitStringToWidth (Context *ctx, char *l, unsigned int width)
static unsigned int computeLabelLines (Context *ctx, Msc m, const MscArcType arcType, char ***lines, const char *label, int startCol, int endCol)
static RowInfo * computeCanvasSize (Context *ctx, Msc m, unsigned int *w, unsigned int *h)
static void ismapRect (FILE *ismap, const char *url, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
static char * getLine (const char *string, unsigned int line, char *const out, const unsigned int outLen)
static void entityText (Context *ctx, FILE *ismap, unsigned int x, unsigned int y, const char *entLabel, const char *entUrl, const char *entId, const char *entIdUrl, const char *entColour, const char *entBgColour)
static void entityLines (Context *ctx, Msc m, const unsigned int ymin, const unsigned int ymax, Boolean dotted, const ADrawColour *colourRefs)
static void arrowR (Context *ctx, unsigned int x, unsigned int y, MscArcType type)
static void arrowL (Context *ctx, unsigned int x, unsigned int y, MscArcType type)
static void arcBox (Context *ctx, unsigned int ymin, unsigned int ymax, unsigned int boxStart, unsigned int boxEnd, MscArcType boxType, const char *lineColour, const char *bgColour)
static void arcText (Context *ctx, Msc m, FILE *ismap, unsigned int outwidth, unsigned int ymid, int ygradient, unsigned int startCol, unsigned int endCol, const unsigned int arcLabelLineCount, char **arcLabelLines, const char *arcUrl, const char *arcId, const char *arcIdUrl, const char *arcTextColour, const char *arcTextBgColour, const MscArcType arcType)
static void arcLine (Context *ctx, Msc m, unsigned int y, unsigned int ygradient, unsigned int startCol, unsigned int endCol, const char *arcLineCol, Boolean hasArrows, const int hasBiArrows, const MscArcType arcType)
static Boolean checkMsc (Msc m)
int mscgen_generate (const char *inputFile, const char *outputFile, mscgen_format_t format)
const char * mscgen_error2str (int code)
Variables
static const GlobalOptions gDefaultOpts
Macro Definition Documentation
M_Max
#define M_Max(a, b) (((a) > (b)) ? (a) : (b))
Definition at line 24 of file mscgen_api.c.
M_Min
#define M_Min(a, b) (((a) < (b)) ? (a) : (b))
Definition at line 25 of file mscgen_api.c.
Typedef Documentation
Context
typedef struct ContextTag Context
GlobalOptions
typedef struct GlobalOptionsTag GlobalOptions
Structure for holding global options. This structure groups all the options that affect the text output into one structure.
Function Documentation
arcBox()
static void arcBox (Context * ctx, unsigned int ymin, unsigned int ymax, unsigned int boxStart, unsigned int boxEnd, MscArcType boxType, const char * lineColour, const char * bgColour) [static]
Draw vertical lines and boxes stemming from entities.
Parameters
ymin Top of the row.
ymax Bottom of the row.
boxStart Column in which the box starts.
boxEnd Column in which the box ends.
boxType The type of box to draw, MSC_ARC_BOX, MSC_ARC_RBOX etc.
lineColour Colour of the lines to use for rendering the box.
bgColour Background colour for rendering the box.
Definition at line 904 of file mscgen_api.c.
{
    unsigned int t;
    /* Ensure the start is less than or equal to the end */
    if(boxStart > boxEnd)
    {
        t = boxEnd;
        boxEnd = boxStart;
        boxStart = t;
    }
    /* Now draw the box */
    unsigned int x1 = (ctx->opts.entitySpacing * boxStart) + ctx->opts.boxSpacing;
    unsigned int x2 = ctx->opts.entitySpacing * (boxEnd + 1) - ctx->opts.boxSpacing;
    unsigned int ymid = (ymin + ymax) / 2;
    /* Set colour for the background area */
    if(bgColour != NULL)
    {
        ctx->drw.setPen(&ctx->drw, ADrawGetColour(bgColour));
    }
    else
    {
        ctx->drw.setPen(&ctx->drw, ADRAW_COL_WHITE);
    }
    /* Draw the background to overwrite the entity lines */
    switch(boxType)
    {
        case MSC_ARC_BOX:
            ctx->drw.filledRectangle(&ctx->drw, x1, ymin, x2, ymax);
            break;
        case MSC_ARC_RBOX:
            ctx->drw.filledRectangle(&ctx->drw, x1 + ctx->opts.rboxArc, ymin, x2 - ctx->opts.rboxArc, ymax);
            ctx->drw.filledRectangle(&ctx->drw, x1, ymin + ctx->opts.rboxArc, x2, ymax - ctx->opts.rboxArc);
            ctx->drw.filledCircle(&ctx->drw, x1 + ctx->opts.rboxArc, ymin + ctx->opts.rboxArc, ctx->opts.rboxArc);
            ctx->drw.filledCircle(&ctx->drw, x2 - ctx->opts.rboxArc, ymin + ctx->opts.rboxArc, ctx->opts.rboxArc);
            ctx->drw.filledCircle(&ctx->drw, x1 + ctx->opts.rboxArc, ymax - ctx->opts.rboxArc, ctx->opts.rboxArc);
            ctx->drw.filledCircle(&ctx->drw, x2 - ctx->opts.rboxArc, ymax - ctx->opts.rboxArc, ctx->opts.rboxArc);
            break;
        case MSC_ARC_NOTE:
            ctx->drw.filledRectangle(&ctx->drw, x1, ymin, x2 - ctx->opts.noteCorner, ymax);
            ctx->drw.filledRectangle(&ctx->drw, x1, ymin + ctx->opts.noteCorner, x2, ymax);
            ctx->drw.filledTriangle(&ctx->drw, x2 - ctx->opts.noteCorner, ymin,
                                     x2, ymin + ctx->opts.noteCorner,
                                     x2 - ctx->opts.noteCorner, ymin + ctx->opts.noteCorner);
            break;
        case MSC_ARC_ABOX:
            ctx->drw.filledRectangle(&ctx->drw, x1 + ctx->opts.aboxSlope, ymin, x2 - ctx->opts.aboxSlope, ymax);
            ctx->drw.filledTriangle(&ctx->drw, x1 + ctx->opts.aboxSlope, ymin,
                                     x1 + ctx->opts.aboxSlope, ymax,
                                     x1, ymid);
            ctx->drw.filledTriangle(&ctx->drw, x2 - ctx->opts.aboxSlope, ymin,
                                     x2 - ctx->opts.aboxSlope, ymax,
                                     x2, ymid);
            break;
        default:
            assert(0);
    }
    /* Setup the colour for rendering the boxes */
    if(lineColour)
    {
        ctx->drw.setPen(&ctx->drw, ADrawGetColour(lineColour));
    }
    else
    {
        ctx->drw.setPen(&ctx->drw, ADRAW_COL_BLACK);
    }
    /* Draw the outline */
    switch(boxType)
    {
        case MSC_ARC_BOX:
            ctx->drw.line(&ctx->drw, x1, ymin, x2, ymin);
            ctx->drw.line(&ctx->drw, x1, ymax, x2, ymax);
            ctx->drw.line(&ctx->drw, x1, ymin, x1, ymax);
            ctx->drw.line(&ctx->drw, x2, ymin, x2, ymax);
            break;
        case MSC_ARC_NOTE:
            ctx->drw.line(&ctx->drw, x1, ymin, x2 - ctx->opts.noteCorner, ymin);
            ctx->drw.line(&ctx->drw, x1, ymax, x2, ymax);
            ctx->drw.line(&ctx->drw, x1, ymin, x1, ymax);
            ctx->drw.line(&ctx->drw, x2, ymin + ctx->opts.noteCorner, x2, ymax);
            ctx->drw.line(&ctx->drw, x2 - ctx->opts.noteCorner, ymin,
                           x2, ymin + ctx->opts.noteCorner);
            ctx->drw.line(&ctx->drw, x2 - ctx->opts.noteCorner, ymin,
                           x2 - ctx->opts.noteCorner, ymin + ctx->opts.noteCorner);
            ctx->drw.line(&ctx->drw, x2, ymin + ctx->opts.noteCorner,
                           x2 - ctx->opts.noteCorner, ymin + ctx->opts.noteCorner);
            break;
        case MSC_ARC_RBOX:
            ctx->drw.line(&ctx->drw, x1 + ctx->opts.rboxArc, ymin, x2 - ctx->opts.rboxArc, ymin);
            ctx->drw.line(&ctx->drw, x1 + ctx->opts.rboxArc, ymax, x2 - ctx->opts.rboxArc, ymax);
            ctx->drw.line(&ctx->drw, x1, ymin + ctx->opts.rboxArc, x1, ymax - ctx->opts.rboxArc);
            ctx->drw.line(&ctx->drw, x2, ymin + ctx->opts.rboxArc, x2, ymax - ctx->opts.rboxArc);
            ctx->drw.arc(&ctx->drw, x1 + ctx->opts.rboxArc,
                    ymin + ctx->opts.rboxArc, ctx->opts.rboxArc * 2, ctx->opts.rboxArc * 2,
                    180, 270);
            ctx->drw.arc(&ctx->drw, x2 - ctx->opts.rboxArc,
                    ymin + ctx->opts.rboxArc, ctx->opts.rboxArc * 2, ctx->opts.rboxArc * 2,
                    270, 0);
            ctx->drw.arc(&ctx->drw, x2 - ctx->opts.rboxArc,
                    ymax - ctx->opts.rboxArc, ctx->opts.rboxArc * 2, ctx->opts.rboxArc * 2,
                    0, 90);
            ctx->drw.arc(&ctx->drw, x1 + ctx->opts.rboxArc,
                    ymax - ctx->opts.rboxArc, ctx->opts.rboxArc * 2, ctx->opts.rboxArc * 2,
                    90, 180);
            break;
        case MSC_ARC_ABOX:
            ctx->drw.line(&ctx->drw, x1 + ctx->opts.aboxSlope, ymin, x2 - ctx->opts.aboxSlope, ymin);
            ctx->drw.line(&ctx->drw, x1 + ctx->opts.aboxSlope, ymax, x2 - ctx->opts.aboxSlope, ymax);
            ctx->drw.line(&ctx->drw, x1 + ctx->opts.aboxSlope, ymin, x1, ymid);
            ctx->drw.line(&ctx->drw, x1, ymid, x1 + ctx->opts.aboxSlope, ymax);
            ctx->drw.line(&ctx->drw, x2 - ctx->opts.aboxSlope, ymin, x2, ymid);
            ctx->drw.line(&ctx->drw, x2, ymid, x2 - ctx->opts.aboxSlope, ymax);
            break;
        default:
            assert(0);
    }
    /* Restore the pen colour if needed */
    if(lineColour)
    {
        ctx->drw.setPen(&ctx->drw, ADRAW_COL_BLACK);
    }
}
References GlobalOptionsTag::aboxSlope, ADRAW_COL_BLACK, ADRAW_COL_WHITE, ADrawGetColour(), ADrawTag::arc, GlobalOptionsTag::boxSpacing, ContextTag::drw, GlobalOptionsTag::entitySpacing, ADrawTag::filledCircle, ADrawTag::filledRectangle, ADrawTag::filledTriangle, ADrawTag::line, MSC_ARC_ABOX, MSC_ARC_BOX, MSC_ARC_NOTE, MSC_ARC_RBOX, GlobalOptionsTag::noteCorner, ContextTag::opts, GlobalOptionsTag::rboxArc, ADrawTag::setPen, x1, and x2.
Referenced by mscgen_generate().
arcLine()
static void arcLine (Context * ctx, Msc m, unsigned int y, unsigned int ygradient, unsigned int startCol, unsigned int endCol, const char * arcLineCol, Boolean hasArrows, const int hasBiArrows, const MscArcType arcType) [static]
Render the line and arrow head for some arc. This will draw the arc line and arrow head between two columns, noting that if the start and end column are the same, an arc is rendered.
Parameters
m The Msc for which the text is being rendered.
ymin Top of row.
ymax Bottom of row.
ygradient The gradient of the arc which alters the y position a the ending column.
startCol Starting column for the arc.
endCol Column at which the arc terminates.
hasArrows If true, draw arc arrows, otherwise omit them.
hasBiArrows If true, has arrows in both directions.
arcType The type of the arc, which dictates its rendered style.
Definition at line 1216 of file mscgen_api.c.
{
    const unsigned int sx = (startCol * ctx->opts.entitySpacing) +
                             (ctx->opts.entitySpacing / 2);
    const unsigned int dx = (endCol * ctx->opts.entitySpacing) +
                             (ctx->opts.entitySpacing / 2);
    /* Check if an explicit line colour is requested */
    if(arcLineCol != NULL)
    {
        ctx->drw.setPen(&ctx->drw, ADrawGetColour(arcLineCol));
    }
    if(startCol != endCol)
    {
        /* Draw the line */
        if(arcType == MSC_ARC_RETVAL)
        {
            ctx->drw.dottedLine(&ctx->drw, sx, y, dx, y + ygradient);
        }
        else if(arcType == MSC_ARC_DOUBLE)
        {
            ctx->drw.line(&ctx->drw, sx, y - 1, dx, y - 1 + ygradient);
            ctx->drw.line(&ctx->drw, sx, y + 1, dx, y + 1 + ygradient);
        }
        else if(arcType == MSC_ARC_LOSS)
        {
            signed int span = dx - sx;
            unsigned int mx = sx + (span / 4) * 3;
            ctx->drw.line(&ctx->drw, sx, y, mx, y + ygradient);
            hasArrows = 0;
            ctx->drw.line(&ctx->drw, mx - 4, y + ygradient - 4, mx + 4, y + ygradient + 4);
            ctx->drw.line(&ctx->drw, mx + 4, y + ygradient - 4, mx - 4, y + ygradient + 4);
        }
        else
        {
            ctx->drw.line(&ctx->drw, sx, y, dx, y + ygradient);
        }
        /* Now the arrow heads */
        if(hasArrows)
        {
            if(startCol < endCol)
            {
                arrowR(ctx, dx, y + ygradient, arcType);
            }
            else
            {
                arrowL(ctx, dx, y + ygradient, arcType);
            }
            if(hasBiArrows)
            {
                if(startCol < endCol)
                {
                    arrowL(ctx, sx, y + ygradient, arcType);
                }
                else
                {
                    arrowR(ctx, sx, y + ygradient, arcType);
                }
            }
        }
    }
    else if(startCol < (MscGetNumEntities(m) / 2))
    {
        /* Arc looping to the left */
        if(arcType == MSC_ARC_RETVAL)
        {
            ctx->drw.dottedArc(&ctx->drw,
                          sx, y,
                          ctx->opts.entitySpacing,
                          ctx->opts.loopArcHeight,
                          90,
                          270);
        }
        else if(arcType == MSC_ARC_DOUBLE)
        {
            ctx->drw.arc(&ctx->drw,
                    sx, y - 1,
                    ctx->opts.entitySpacing,
                    ctx->opts.loopArcHeight,
                    90,
                    270);
            ctx->drw.arc(&ctx->drw,
                    sx, y + 1,
                    ctx->opts.entitySpacing,
                    ctx->opts.loopArcHeight,
                    90,
                    270);
        }
        else if(arcType == MSC_ARC_LOSS)
        {
            unsigned int px, py;
            ctx->drw.arc(&ctx->drw,
                    sx, y - 1,
                    ctx->opts.entitySpacing - 8,
                    ctx->opts.loopArcHeight,
                    180 - 45,
                    270);
            hasArrows = FALSE;
            /* Get co-ordinates of the arc end-point */
            ADrawComputeArcPoint((float)sx, (float)(y - 1), (float)(ctx->opts.entitySpacing - 8),
                                 (float)ctx->opts.loopArcHeight, 180.0f - 45.0f,
                                 &px, &py);
            /* Draw a cross */
            ctx->drw.line(&ctx->drw, px - 4, py - 4, px + 4, py + 4);
            ctx->drw.line(&ctx->drw, px + 4, py - 4, px - 4, py + 4);
        }
        else
        {
            ctx->drw.arc(&ctx->drw,
                    sx, y,
                    ctx->opts.entitySpacing - 4,
                    ctx->opts.loopArcHeight,
                    90,
                    270);
        }
        if(hasArrows)
        {
            arrowR(ctx, dx, y + (ctx->opts.loopArcHeight / 2), arcType);
        }
    }
    else
    {
        /* Arc looping to right */
        if(arcType == MSC_ARC_RETVAL)
        {
            ctx->drw.dottedArc(&ctx->drw,
                          sx, y,
                          ctx->opts.entitySpacing,
                          ctx->opts.loopArcHeight,
                          270,
                          90);
        }
        else if(arcType == MSC_ARC_DOUBLE)
        {
            ctx->drw.arc(&ctx->drw,
                    sx, y - 1,
                    ctx->opts.entitySpacing,
                    ctx->opts.loopArcHeight,
                    270,
                    90);
            ctx->drw.arc(&ctx->drw,
                    sx, y + 1,
                    ctx->opts.entitySpacing,
                    ctx->opts.loopArcHeight,
                    270,
                    90);
        }
        else if(arcType == MSC_ARC_LOSS)
        {
            unsigned int px, py;
            ctx->drw.arc(&ctx->drw,
                    sx, y - 1,
                    ctx->opts.entitySpacing - 8,
                    ctx->opts.loopArcHeight,
                    270,
                    45);
            hasArrows = FALSE;
            /* Get co-ordinates of the arc end-point */
            ADrawComputeArcPoint((float)sx, (float)(y - 1),
                                 (float)(ctx->opts.entitySpacing - 8),
                                 (float)ctx->opts.loopArcHeight, 45.0f,
                                 &px, &py);
            /* Draw a cross */
            ctx->drw.line(&ctx->drw, px - 4, py - 4, px + 4, py + 4);
            ctx->drw.line(&ctx->drw, px + 4, py - 4, px - 4, py + 4);
        }
        else
        {
            ctx->drw.arc(&ctx->drw,
                    sx, y,
                    ctx->opts.entitySpacing,
                    ctx->opts.loopArcHeight,
                    270,
                    90);
        }
        if(hasArrows)
        {
            arrowL(ctx, dx, y + (ctx->opts.loopArcHeight / 2), arcType);
        }
    }
    /* Restore pen if needed */
    if(arcLineCol != NULL)
    {
        ctx->drw.setPen(&ctx->drw, ADRAW_COL_BLACK);
    }
}
References ADRAW_COL_BLACK, ADrawComputeArcPoint(), ADrawGetColour(), ADrawTag::arc, arrowL(), arrowR(), ADrawTag::dottedArc, ADrawTag::dottedLine, ContextTag::drw, GlobalOptionsTag::entitySpacing, FALSE, ADrawTag::line, GlobalOptionsTag::loopArcHeight, MSC_ARC_DOUBLE, MSC_ARC_LOSS, MSC_ARC_RETVAL, MscGetNumEntities(), ContextTag::opts, ADrawTag::setPen, and y.
Referenced by mscgen_generate().
arcText()
static void arcText (Context * ctx, Msc m, FILE * ismap, unsigned int outwidth, unsigned int ymid, int ygradient, unsigned int startCol, unsigned int endCol, const unsigned int arcLabelLineCount, char ** arcLabelLines, const char * arcUrl, const char * arcId, const char * arcIdUrl, const char * arcTextColour, const char * arcTextBgColour, const MscArcType arcType) [static]
Render text on an arc. Draw the text on some arc.
Parameters
m The Msc for which the text is being rendered.
ismap If not NULL, write an ismap description here.
outwidth Width of the output image.
ymid Co-ordinate of the row on which the text should be aligned.
startCol The column at which the arc being labelled starts.
endCol The column at which the arc being labelled ends.
arcLabelLineCount Count of lines of text in arcLabelLines.
arcLabelLines Array of lines of text from 0 to arcLabelLineCount - 1.
arcUrl The URL for rendering the label as a hyperlink. This maybe NULL if not required.
arcId The text identifier for the arc.
arcIdUrl The URL for rendering the test identifier as a hyperlink. This maybe NULL if not required.
arcTextColour Colour for the arc text, or NULL to use default.
arcTextColour Colour for the arc text background, or NULL to use default.
arcType The type of arc, used to control output semantics.
Definition at line 1069 of file mscgen_api.c.
{
    unsigned int l;
    unsigned int y;
    /* A single line of normal text is above the midline */
    if(arcLabelLineCount == 1 && !isBoxArc(arcType) &&
       arcType != MSC_ARC_DISCO && arcType != MSC_ARC_DIVIDER &&
       arcType != MSC_ARC_SPACE)
    {
        y = ymid + (ygradient / 2) - ctx->drw.textHeight(&ctx->drw);
    }
    else /* Text is vertically centered on the midline */
    {
        int yoff = ygradient - (ctx->drw.textHeight(&ctx->drw) * arcLabelLineCount);
        y = ymid + (yoff / 2);
    }
    for (l = 0; l < arcLabelLineCount; l++)
    {
        const char *lineLabel = arcLabelLines[l];
        unsigned int width = ctx->drw.textWidth(&ctx->drw, lineLabel);
        int x = ((startCol + endCol + 1) * ctx->opts.entitySpacing) / 2;
        y += ctx->drw.textHeight(&ctx->drw);
        if(startCol != endCol || isBoxArc(arcType))
        {
            /* Produce central aligned text */
            x -= width / 2;
        }
        else if(startCol < (MscGetNumEntities(m) / 2))
        {
            /* Form text to the right */
            x += ctx->opts.textHGapPre;
        }
        else
        {
            /* Form text to the left */
            x -= width + ctx->opts.textHGapPost;
        }
        /* Clip against edges of image */
        if(x + width > outwidth)
        {
            x = outwidth - width;
        }
        if(x < 0)
        {
            x = 0;
        }
        /* Check if a URL is associated */
        if(arcUrl)
        {
            /* Default to blue */
            ctx->drw.setPen(&ctx->drw, ADRAW_COL_BLUE);
            /* Image map output */
            ismapRect(ismap,
                      arcUrl,
                      x, y - ctx->drw.textHeight(&ctx->drw),
                      x + width, y);
        }
        /* Set to the explicit colours if directed */
        if(arcTextColour != NULL)
        {
            ctx->drw.setPen(&ctx->drw, ADrawGetColour(arcTextColour));
        }
        if(arcTextBgColour != NULL)
        {
            ctx->drw.setBgPen(&ctx->drw, ADrawGetColour(arcTextBgColour));
        }
        /* Render text and restore pen */
        ctx->drw.textR (&ctx->drw, x, y, lineLabel);
        ctx->drw.setPen(&ctx->drw, ADRAW_COL_BLACK);
        ctx->drw.setBgPen(&ctx->drw, ADRAW_COL_WHITE);
        /* Render the Id of the arc, if specified and for the first line*/
        if(arcId && l == 0)
        {
            unsigned int idwidth;
            int idx, idy;
            idy = y - ctx->drw.textHeight(&ctx->drw);
            idx = x + width;
            ctx->drw.setFontSize(&ctx->drw, ADRAW_FONT_TINY);
            idwidth = ctx->drw.textWidth(&ctx->drw, arcId);
            idy += (ctx->drw.textHeight(&ctx->drw) + 1) / 2;
            if(arcIdUrl)
            {
                ctx->drw.setPen(&ctx->drw, ADRAW_COL_BLUE);
                /* Image map output */
                ismapRect(ismap,
                          arcIdUrl,
                          idx, idy - ctx->drw.textHeight(&ctx->drw),
                          idx + idwidth, idy);
            }
            /* Render text and restore pen and font */
            ctx->drw.textR (&ctx->drw, idx, idy, arcId);
            ctx->drw.setPen(&ctx->drw, ADRAW_COL_BLACK);
            ctx->drw.setFontSize(&ctx->drw, ADRAW_FONT_SMALL);
        }
    }
}
References ADRAW_COL_BLACK, ADRAW_COL_BLUE, ADRAW_COL_WHITE, ADRAW_FONT_SMALL, ADRAW_FONT_TINY, ADrawGetColour(), ContextTag::drw, GlobalOptionsTag::entitySpacing, isBoxArc(), ismapRect(), MSC_ARC_DISCO, MSC_ARC_DIVIDER, MSC_ARC_SPACE, MscGetNumEntities(), ContextTag::opts, ADrawTag::setBgPen, ADrawTag::setFontSize, ADrawTag::setPen, ADrawTag::textHeight, GlobalOptionsTag::textHGapPost, GlobalOptionsTag::textHGapPre, ADrawTag::textR, ADrawTag::textWidth, x, and y.
Referenced by mscgen_generate().
arrowL()
static void arrowL (Context * ctx, unsigned int x, unsigned int y, MscArcType type) [static]
Draw an arrow pointing to the left.
Parameters
x The x co-ordinate for the end point for the arrow head.
y The y co-ordinate for the end point for the arrow head.
type The arc type, which controls the format of the arrow head.
Definition at line 858 of file mscgen_api.c.
{
    switch(type)
    {
        case MSC_ARC_SIGNAL: /* Unfilled half */
            ctx->drw.line(&ctx->drw,
                     x, y,
                     x + ctx->opts.arrowWidth, y + ctx->opts.arrowHeight);
            break;
        case MSC_ARC_DOUBLE:
        case MSC_ARC_METHOD: /* Filled */
        case MSC_ARC_RETVAL: /* Filled, dotted arc (not rendered here) */
            ctx->drw.filledTriangle(&ctx->drw,
                               x, y,
                               x + ctx->opts.arrowWidth, y + ctx->opts.arrowHeight,
                               x + ctx->opts.arrowWidth, y - ctx->opts.arrowHeight);
            break;
        case MSC_ARC_CALLBACK: /* Non-filled */
            ctx->drw.line(&ctx->drw,
                     x, y,
                     x + ctx->opts.arrowWidth, y + ctx->opts.arrowHeight);
            ctx->drw.line(&ctx->drw,
                     x, y,
                     x + ctx->opts.arrowWidth, y - ctx->opts.arrowHeight);
            break;
        default:
            assert(0);
            break;
    }
}
References GlobalOptionsTag::arrowHeight, GlobalOptionsTag::arrowWidth, ContextTag::drw, ADrawTag::filledTriangle, ADrawTag::line, MSC_ARC_CALLBACK, MSC_ARC_DOUBLE, MSC_ARC_METHOD, MSC_ARC_RETVAL, MSC_ARC_SIGNAL, ContextTag::opts, x, and y.
Referenced by arcLine().
arrowR()
static void arrowR (Context * ctx, unsigned int x, unsigned int y, MscArcType type) [static]
Draw an arrow pointing to the right.
Parameters
x The x co-ordinate for the end point for the arrow head.
y The y co-ordinate for the end point for the arrow head.
type The arc type, which controls the format of the arrow head.
Definition at line 815 of file mscgen_api.c.
{
    switch(type)
    {
        case MSC_ARC_SIGNAL: /* Unfilled half */
            ctx->drw.line(&ctx->drw,
                     x, y,
                     x - ctx->opts.arrowWidth, y + ctx->opts.arrowHeight);
            break;
        case MSC_ARC_DOUBLE:
        case MSC_ARC_METHOD: /* Filled */
        case MSC_ARC_RETVAL: /* Filled, dotted arc (not rendered here) */
            ctx->drw.filledTriangle(&ctx->drw,
                               x, y,
                               x - ctx->opts.arrowWidth, y + ctx->opts.arrowHeight,
                               x - ctx->opts.arrowWidth, y - ctx->opts.arrowHeight);
            break;
        case MSC_ARC_CALLBACK: /* Non-filled */
            ctx->drw.line(&ctx->drw,
                     x, y,
                     x - ctx->opts.arrowWidth, y + ctx->opts.arrowHeight);
            ctx->drw.line(&ctx->drw,
                     x - ctx->opts.arrowWidth, y - ctx->opts.arrowHeight,
                     x, y);
            break;
        default:
            assert(0);
            break;
    }
}
References GlobalOptionsTag::arrowHeight, GlobalOptionsTag::arrowWidth, ContextTag::drw, ADrawTag::filledTriangle, ADrawTag::line, MSC_ARC_CALLBACK, MSC_ARC_DOUBLE, MSC_ARC_METHOD, MSC_ARC_RETVAL, MSC_ARC_SIGNAL, ContextTag::opts, x, and y.
Referenced by arcLine().
checkMsc()
static Boolean checkMsc (Msc m) [static]
Definition at line 1434 of file mscgen_api.c.
{
    /* Check all arc entities are known */
    MscResetArcIterator(m);
    do
    {
        const MscArcType arcType = MscGetCurrentArcType(m);
        if (arcType != MSC_ARC_PARALLEL && arcType != MSC_ARC_DISCO &&
            arcType != MSC_ARC_DIVIDER && arcType != MSC_ARC_SPACE)
        {
            const char *src = MscGetCurrentArcSource(m);
            const char *dst = MscGetCurrentArcDest(m);
            const int startCol = MscGetEntityIndex(m, src);
            const int endCol = MscGetEntityIndex(m, dst);
            /* Check the start column is valid */
            if (startCol == -1)
            {
                fprintf(stderr, "Error detected at line %u: Unknown source entity '%s'.\n",
                        MscGetCurrentArcInputLine(m), src);
                return FALSE;
            }
            if (endCol == -1 && !isBroadcastArc(dst))
            {
                fprintf(stderr, "Error detected at line %u: Unknown destination entity '%s'.\n",
                        MscGetCurrentArcInputLine(m), dst);
                return FALSE;
            }
        }
    }
    while (MscNextArc(m));
    return TRUE;
}
References dst, FALSE, isBroadcastArc(), MSC_ARC_DISCO, MSC_ARC_DIVIDER, MSC_ARC_PARALLEL, MSC_ARC_SPACE, MscGetCurrentArcDest(), MscGetCurrentArcInputLine(), MscGetCurrentArcSource(), MscGetCurrentArcType(), MscGetEntityIndex(), MscNextArc(), MscResetArcIterator(), src, and TRUE.
Referenced by mscgen_generate().
computeCanvasSize()
static RowInfo * computeCanvasSize (Context * ctx, Msc m, unsigned int * w, unsigned int * h) [static]
Compute the output canvas size required for some MSC. This computes the dimensions for the canvas as well as the height for each row.
Parameters
 in m The MSC to analyse.
 in,out w Pointer to be filled with the output width.
 in,out h Pointer to be filled with the output height.
Returns
An array giving the height of each row.
Definition at line 443 of file mscgen_api.c.
{
    const unsigned int rowCount = MscGetNumArcs(m) - MscGetNumParallelArcs(m);
    const unsigned int textHeight = ctx->drw.textHeight(&ctx->drw);
    RowInfo *rowHeight;
    unsigned int nextYmin, ymin, ymax, yskipmax, row;
    /* Allocate storage for the height of each row */
    rowHeight = zalloc_s(sizeof(RowInfo) * rowCount);
    row = 0;
    nextYmin = ymin = ctx->opts.entityHeadGap;
    yskipmax = 0;
    ymax = 0;
    MscResetArcIterator(m);
    do
    {
        const MscArcType arcType = MscGetCurrentArcType(m);
        const int arcGradient = isBoxArc(arcType) ? 0 : getArcGradient(ctx, m, NULL, 0);
        char **arcLabelLines = NULL;
        unsigned int arcLabelLineCount = 0;
        int startCol = -1, endCol = -1;
        if (arcType == MSC_ARC_PARALLEL)
        {
            assert(row > 0);
            row--;
            ymin = rowHeight[row].ymin;
            nextYmin = rowHeight[row].ymax;
        }
        else
        {
            /* Get the entity indices */
            if (arcType != MSC_ARC_DISCO && arcType != MSC_ARC_DIVIDER && arcType != MSC_ARC_SPACE)
            {
                startCol = MscGetEntityIndex(m, MscGetCurrentArcSource(m));
                endCol = MscGetEntityIndex(m, MscGetCurrentArcDest(m));
            }
            else
            {
                /* Discontinuity or parallel arc spans whole chart */
                startCol = 0;
                endCol = MscGetNumEntities(m) - 1;
            }
            /* Work out how the label fits the gap between entities */
            arcLabelLineCount = computeLabelLines(ctx, m, arcType, &arcLabelLines,
                                                  MscGetCurrentArcAttrib(m, MSC_ATTR_LABEL),
                                                  startCol, endCol);
            assert(row < rowCount);
            /* Update the max line count for the row */
            if (arcLabelLineCount > rowHeight[row].maxTextLines)
            {
                rowHeight[row].maxTextLines = arcLabelLineCount;
            }
            freeLabelLines(arcLabelLineCount, arcLabelLines);
            /* Compute the height of this arc */
            if (arcType != MSC_ARC_DISCO && arcType != MSC_ARC_DIVIDER && arcType != MSC_ARC_SPACE)
            {
                ymax = ymin + ctx->opts.arcSpacing;
                ymax += (M_Max(rowHeight[row].maxTextLines, 2) * textHeight);
            }
            else
            {
                ymax = ymin + ctx->opts.arcSpacing;
                ymax += (M_Max(rowHeight[row].maxTextLines, 1) * textHeight);
            }
            /* Update next potential row start */
            if (ymax > nextYmin)
            {
                nextYmin = ymax;
            }
            /* Compute the dimensions for the completed row */
            rowHeight[row].ymin = ymin;
            rowHeight[row].ymax = nextYmin - ctx->opts.arcSpacing;
            rowHeight[row].arcliney = rowHeight[row].ymin + (rowHeight[row].ymax - rowHeight[row].ymin) / 2;
            row++;
            /* Start new row */
            ymin = nextYmin;
        }
        /* Keep a track of where the gradient may cause the graph to end */
        if (ymax + arcGradient > ymax)
        {
            yskipmax = ymax + arcGradient;
        }
    }
    while (MscNextArc(m));
    if (ymax < yskipmax)
        ymax = yskipmax;
    /* Set the return values */
    *w = MscGetNumEntities(m) * ctx->opts.entitySpacing;
    *h = ymax;
    return rowHeight;
}
References RowInfo::arcliney, GlobalOptionsTag::arcSpacing, computeLabelLines(), ContextTag::drw, GlobalOptionsTag::entityHeadGap, GlobalOptionsTag::entitySpacing, freeLabelLines(), getArcGradient(), h, isBoxArc(), M_Max, RowInfo::maxTextLines, MSC_ARC_DISCO, MSC_ARC_DIVIDER, MSC_ARC_PARALLEL, MSC_ARC_SPACE, MSC_ATTR_LABEL, MscGetCurrentArcAttrib(), MscGetCurrentArcDest(), MscGetCurrentArcSource(), MscGetCurrentArcType(), MscGetEntityIndex(), MscGetNumArcs(), MscGetNumEntities(), MscGetNumParallelArcs(), MscNextArc(), MscResetArcIterator(), ContextTag::opts, ADrawTag::textHeight, w, RowInfo::ymax, RowInfo::ymin, and zalloc_s().
Referenced by mscgen_generate().
computeLabelLines()
static unsigned int computeLabelLines (Context * ctx, Msc m, const MscArcType arcType, char *** lines, const char * label, int startCol, int endCol) [static]
Split an input arc label into lines, word-wrapping if needed. This takes the literal label supplied from the input and splits it into an array of char * text lines. Splitting is first done according to literal '
' character sequences added by the user, then according to word wrapping to fit available space, if appropriate.
Parameters
 in m The MSC for which the lines are to be split.
 in arcType The type of the arc being labelled.
 in,out lines Pointer to be filled with output line array.
 in label Original arc label from input file.
 in startCol Column in which the arc starts.
 in endCol Column in which the arc ends, or -1 for broadcast arcs.
Note
The returned strings and array must be free()'d. freeLabelLines() can be used for this purpose.
Definition at line 337 of file mscgen_api.c.
{
    unsigned int width;
    unsigned int nAllocLines = 8;
    char **retLines = malloc_s(sizeof(char *) * nAllocLines);
    unsigned int c = 0;
    assert(startCol >= 0 && startCol < (signed)MscGetNumEntities(m));
    assert(startCol >= -1 && startCol < (signed)MscGetNumEntities(m));
    /* Compute available width for text */
    if (isBoxArc(arcType) || ctx->opts.wordWrapArcLabels)
    {
        if (endCol == -1)
        {
            /* This is a special case for a broadcast arc */
            width = ctx->opts.entitySpacing * MscGetNumEntities(m);
        }
        else if (startCol < endCol)
        {
            width = ctx->opts.entitySpacing * (1 + (endCol - startCol));
        }
        else
        {
            width = ctx->opts.entitySpacing * (1 + (startCol - endCol));
        }
        /* Reduce the width due to the box borders */
        if (isBoxArc(arcType))
        {
            width -= (ctx->opts.boxSpacing + ctx->opts.boxInternalBorder) * 2;
        }
        if (arcType == MSC_ARC_NOTE)
        {
            width -= ctx->opts.noteCorner;
        }
    }
    else
    {
        width = UINT_MAX;
    }
    /* Split the input label into lines */
    while (label != NULL)
    {
        /* First split around user specified lines with literal '\n' */
        char *nextLine = strstr(label, "\\n");
        if (nextLine)
        {
            const int lineLen = (int)(nextLine - label);
            /* Allocate storage and duplicate the line */
            retLines[c] = malloc_s(lineLen + 1);
            memcpy(retLines[c], label, lineLen);
            retLines[c][lineLen] = '\0';
            /* Advance the label */
            label = nextLine + 2;
        }
        else
        {
            /* Duplicate the final line */
            retLines[c] = strdup_s(label);
            label = NULL;
        }
        /* Now split the line as required to wrap into the space available */
        do
        {
            /* Check if more storage maybe needed */
            if (c + 2 >= nAllocLines)
            {
                nAllocLines += 8;
                retLines = realloc_s(retLines, sizeof(char *) * nAllocLines);
            }
            retLines[c + 1] = splitStringToWidth(ctx, retLines[c], width);
            c++;
        }
        while (retLines[c] != NULL);
    }
    /* Return the array of lines and the count */
    *lines = retLines;
    return c;
}
References GlobalOptionsTag::boxInternalBorder, GlobalOptionsTag::boxSpacing, c, GlobalOptionsTag::entitySpacing, isBoxArc(), malloc_s(), MSC_ARC_NOTE, MscGetNumEntities(), GlobalOptionsTag::noteCorner, ContextTag::opts, realloc_s(), splitStringToWidth(), strdup_s(), and GlobalOptionsTag::wordWrapArcLabels.
Referenced by computeCanvasSize(), and mscgen_generate().
countLines()
static unsigned int countLines (const char * l) [static]
Count the number of lines in some string. This counts line breaks that are written as a literal '
' in the line to determine how many lines of output are needed.
Parameters
 in l Pointer to the input string to inspect.
Returns
The count of '
' characters appearing in the input string + 1.
Definition at line 160 of file mscgen_api.c.
{
    unsigned int c = 1;
    do
    {
        c++;
        l = strstr(l, "\\n");
        if (l) l += 2;
    } while (l != NULL);
    return c;
}
References c.
Referenced by entityText(), and mscgen_generate().
entityLines()
static void entityLines (Context * ctx, Msc m, const unsigned int ymin, const unsigned int ymax, Boolean dotted, const ADrawColour * colourRefs) [static]
Draw vertical lines stemming from entities. This function will draw a single segment of the vertical line that drops from an entity.
Parameters
m The Msc for which the lines are drawn
ymin Top of the row.
ymax Bottom of the row.
dotted If TRUE, produce a dotted line, otherwise solid.
colourRefs Colour references for each entity.
Definition at line 781 of file mscgen_api.c.
{
    unsigned int t;
    for (t = 0; t < MscGetNumEntities(m); t++)
    {
        unsigned int x = (ctx->opts.entitySpacing / 2) + (ctx->opts.entitySpacing * t);
        ctx->drw.setPen(&ctx->drw, colourRefs[t]);
        if(dotted)
        {
            ctx->drw.dottedLine(&ctx->drw, x, ymin, x, ymax);
        }
        else
        {
            ctx->drw.line(&ctx->drw, x, ymin, x, ymax);
        }
    }
    ctx->drw.setPen(&ctx->drw, ADRAW_COL_BLACK);
}
References ADRAW_COL_BLACK, ADrawTag::dottedLine, ContextTag::drw, GlobalOptionsTag::entitySpacing, ADrawTag::line, MscGetNumEntities(), ContextTag::opts, ADrawTag::setPen, and x.
Referenced by mscgen_generate().
entityText()
static void entityText (Context * ctx, FILE * ismap, unsigned int x, unsigned int y, const char * entLabel, const char * entUrl, const char * entId, const char * entIdUrl, const char * entColour, const char * entBgColour) [static]
Render some entity text. Draw the text for some entity.
Parameters
ismap If not NULL, write an ismap description here.
x The x position at which the entity text should be centered.
y The y position where the text should be placed.
entLabel The label to render, which maybe NULL in which case no output is produced.
entUrl The URL for rendering the label as a hyperlink. This maybe NULL if not required.
entId The text identifier for the arc.
entIdUrl The URL for rendering the test identifier as a hyperlink. This maybe NULL if not required.
entColour The text colour name or specification for the entity text. If NULL, use default colouring scheme.
entBgColour The text background colour name or specification for the entity text. If NULL, use default colouring scheme.
Definition at line 677 of file mscgen_api.c.
{
    if(entLabel)
    {
        const unsigned int lines = countLines(entLabel);
        unsigned int l;
        char lineBuffer[1024];
        /* Adjust y to be above the writing line */
        y -= ctx->drw.textHeight(&ctx->drw) * (lines - 1);
        for (l = 0; l < lines - 1; l++)
        {
            char *lineLabel = getLine(entLabel, l, lineBuffer, sizeof(lineBuffer));
            unsigned int width = ctx->drw.textWidth(&ctx->drw, lineLabel);
            /* Push text down one line */
            y += ctx->drw.textHeight(&ctx->drw);
            /* Check if a URL is associated */
            if(entUrl)
            {
                /* If no explicit colour has been set, make URLS blue */
                ctx->drw.setPen(&ctx->drw, ADRAW_COL_BLUE);
                /* Image map output */
                ismapRect(ismap,
                          entUrl,
                          x - (width / 2), y - ctx->drw.textHeight(&ctx->drw),
                          x + (width / 2), y);
            }
            /* Set to the explicit colours if directed */
            if(entColour != NULL)
            {
                ctx->drw.setPen(&ctx->drw, ADrawGetColour(entColour));
            }
            if(entBgColour != NULL)
            {
                ctx->drw.setBgPen(&ctx->drw, ADrawGetColour(entBgColour));
            }
            /* Render text and restore pen */
            ctx->drw.textC (&ctx->drw, x, y, lineLabel);
            ctx->drw.setPen(&ctx->drw, ADRAW_COL_BLACK);
            ctx->drw.setBgPen(&ctx->drw, ADRAW_COL_WHITE);
            /* Render the Id of the title, if specified and for first line only */
            if(entId && l == 0)
            {
                unsigned int idwidth;
                int idx, idy;
                idy = y - ctx->drw.textHeight(&ctx->drw);
                idx = x + (width / 2);
                ctx->drw.setFontSize(&ctx->drw, ADRAW_FONT_TINY);
                idwidth = ctx->drw.textWidth(&ctx->drw, entId);
                idy += (ctx->drw.textHeight(&ctx->drw) + 1) / 2;
                if(entIdUrl)
                {
                    ctx->drw.setPen(&ctx->drw, ADRAW_COL_BLUE);
                    ctx->drw.textR (&ctx->drw, idx, idy, entId);
                    ctx->drw.setPen(&ctx->drw, ADRAW_COL_BLACK);
                    /* Image map output */
                    ismapRect(ismap,
                              entIdUrl,
                              idx, idy - ctx->drw.textHeight(&ctx->drw),
                              idx + idwidth, idy);
                }
                else
                {
                    ctx->drw.textR(&ctx->drw, idx, idy, entId);
                }
                ctx->drw.setFontSize(&ctx->drw, ADRAW_FONT_SMALL);
            }
        }
    }
}
References ADRAW_COL_BLACK, ADRAW_COL_BLUE, ADRAW_COL_WHITE, ADRAW_FONT_SMALL, ADRAW_FONT_TINY, ADrawGetColour(), countLines(), ContextTag::drw, getLine(), ismapRect(), ADrawTag::setBgPen, ADrawTag::setFontSize, ADrawTag::setPen, ADrawTag::textC, ADrawTag::textHeight, ADrawTag::textR, ADrawTag::textWidth, x, and y.
Referenced by mscgen_generate().
freeLabelLines()
static void freeLabelLines (unsigned int n, char ** lines) [static]
Free memory allocated for the label lines.
Definition at line 221 of file mscgen_api.c.
{
    while (n > 0)
    {
        n--;
        free(lines[n]);
    }
    free(lines);
}
References n.
Referenced by computeCanvasSize(), and mscgen_generate().
getArcGradient()
static int getArcGradient (Context * ctx, Msc m, const RowInfo * rowInfo, unsigned int row) [static]
Get the skip value in pixels for some the current arc in the Msc.
Definition at line 185 of file mscgen_api.c.
{
    const char *s = MscGetCurrentArcAttrib(m, MSC_ATTR_ARC_SKIP);
    unsigned int v = ctx->opts.arcGradient;
    if (s != NULL && rowInfo != NULL)
    {
        const unsigned int rowCount = MscGetNumArcs(m) - MscGetNumParallelArcs(m);
        unsigned int skip;
        if (sscanf(s, "%u", &skip) == 1)
        {
            unsigned int ystart = rowInfo[row].arcliney;
            unsigned int yend = rowInfo[M_Min(rowCount - 1, row + skip)].arcliney;
            v += yend - ystart;
        }
        else
        {
            fprintf(stderr, "Warning: Non-integer arcskip value: %s\n", s);
        }
    }
    return v;
}
References GlobalOptionsTag::arcGradient, RowInfo::arcliney, M_Min, MSC_ATTR_ARC_SKIP, MscGetCurrentArcAttrib(), MscGetNumArcs(), MscGetNumParallelArcs(), ContextTag::opts, and s.
Referenced by computeCanvasSize(), and mscgen_generate().
getLine()
static char * getLine (const char * string, unsigned int line, char *const out, const unsigned int outLen) [static]
Get some line from a string containing '
' delimiters. Given a string that contains literal '
' delimiters, return a subset in a passed buffer that gives the nth line.
Parameters
 in string The string to parse.
 in line The line number to return from the string, which should count from 0.
 in out Pointer to a buffer to fill with line data.
 in outLen The length of the buffer pointed to by out, in bytes.
Returns
A pointer to out.
Definition at line 603 of file mscgen_api.c.
{
    const char *lineStart, *lineEnd;
    unsigned int lineLen;
    /* Setup for the loop */
    lineEnd = NULL;
    line++;
    do
    {
        /* Check if this is the first or a repeat iteration */
        if(lineEnd)
        {
            lineStart = lineEnd + 2;
        }
        else
        {
            lineStart = string;
        }
        /* Search for next delimited */
        lineEnd = strstr(lineStart, "\\n");
        line--;
    }
    while (line > 0 && lineEnd != NULL);
    /* Determine the length of the line */
    if(lineEnd != NULL)
    {
        lineLen = (unsigned int)(lineEnd - lineStart);
    }
    else
    {
        lineLen = (unsigned int)(strlen(string) - (lineStart - string));
    }
    /* Clamp the length to the buffer */
    if(lineLen > outLen - 1)
    {
        lineLen = outLen - 1;
    }
    /* Copy desired characters */
    memcpy(out, lineStart, lineLen);
    /* NULL terminate */
    out[lineLen] = '\0';
    return out;
}
References out, and string.
Referenced by vhdl::parser::VhdlParser::alias_declaration(), vhdl::parser::VhdlParser::architecture_body(), vhdl::parser::VhdlParser::attribute_declaration(), vhdl::parser::VhdlParser::attribute_specification(), vhdl::parser::VhdlParser::component_declaration(), vhdl::parser::VhdlParser::component_instantiation_statement(), vhdl::parser::VhdlParser::configuration_declaration(), vhdl::parser::VhdlParser::constant_declaration(), vhdl::parser::VhdlParser::context_declaration(), vhdl::parser::VhdlParser::element_declaration(), vhdl::parser::VhdlParser::entity_declaration(), entityText(), vhdl::parser::VhdlParser::file_declaration(), vhdl::parser::VhdlParser::full_type_declaration(), vhdl::parser::VhdlParser::interface_declaration(), vhdl::parser::VhdlParser::interface_file_declaration(), vhdl::parser::VhdlParser::interface_variable_declaration(), vhdl::parser::VhdlParser::library_clause(), vhdl::parser::VhdlParser::package_body(), vhdl::parser::VhdlParser::package_declaration(), vhdl::parser::VhdlParser::package_instantiation_declaration(), vhdl::parser::VhdlParser::signal_declaration(), vhdl::parser::VhdlParser::subprogram_instantiation_declaration(), vhdl::parser::VhdlParser::subtype_declaration(), vhdl::parser::VhdlParser::use_clause(), and vhdl::parser::VhdlParser::variable_declaration().
isBoxArc()
static Boolean isBoxArc (const MscArcType a) [static]
Check if some arc type indicates a box.
Definition at line 177 of file mscgen_api.c.
{
    return a == MSC_ARC_BOX || a == MSC_ARC_RBOX ||
           a == MSC_ARC_ABOX || a== MSC_ARC_NOTE;
}
References a, MSC_ARC_ABOX, MSC_ARC_BOX, MSC_ARC_NOTE, and MSC_ARC_RBOX.
Referenced by arcText(), computeCanvasSize(), computeLabelLines(), and mscgen_generate().
isBroadcastArc()
static Boolean isBroadcastArc (const char * entity) [static]
Check if some arc name indicates a broadcast entity.
Definition at line 214 of file mscgen_api.c.
{
    return entity != NULL && (strcmp(entity, "*") == 0);
}
References strcmp().
Referenced by checkMsc(), and mscgen_generate().
ismapRect()
static void ismapRect (FILE * ismap, const char * url, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2) [static]
Add a point to the output imagemap. If ismap and url are non-NULL, this function will add a rectangle to the imagemap according to the parameters passed.
Parameters
ismap The file to which the imagemap should be rendered.
url The URL to which the imagemap area should link.
x1 The x coordinate for the upper left point.
y2 The y coordinate for the upper left point.
x2 The x coordinate for the lower right point.
y2 The y coordinate for the lower right point.
Definition at line 567 of file mscgen_api.c.
{
    if(ismap && url)
    {
        assert(x1 <= x2); assert(y1 <= y2);
        fprintf(ismap,
                "rect %s %d,%d %d,%d\n",
                url,
                x1, y1,
                x2, y2);
    }
#if 0
    /* For debug render a cross onto the output */
    drw.line(&drw, x1, y1, x2, y2);
    drw.line(&drw, x2, y1, x1, y2);
#endif
}
References setup::url, x1, x2, y1, and y2.
Referenced by arcText(), and entityText().
mscgen_error2str()
const char * mscgen_error2str (int code)
Translates the error code returned by mscgen_generate into a string
Definition at line 1865 of file mscgen_api.c.
{
  switch (code)
  {
    case MSCGEN_OK: return "OK";
    case MSCGEN_FILE_ERROR: return "FILE ERROR";
    case MSCGEN_INPUT_FORMAT_ERROR: return "INPUT FORMAT ERROR";
    case MSCGEN_OUTPUT_CONTEXT_ERROR: return "OUTPUT CONTEXT ERROR";
    default: return "UNKNOWN_ERROR";
  }
}
References MSCGEN_FILE_ERROR, MSCGEN_INPUT_FORMAT_ERROR, MSCGEN_OK, and MSCGEN_OUTPUT_CONTEXT_ERROR.
Referenced by getMscImageMapFromFile(), and writeMscGraphFromFile().
mscgen_generate()
int mscgen_generate (const char * inputFile, const char * outputFile, mscgen_format_t format)
generate an image file for a given .msc file.
Parameters
inputFile the name of the MSC file to process.
outputFile the name of the image file to generate.
format the format of the image file to generate.
Returns
0 on success, a non zero error code on failure.
Definition at line 1472 of file mscgen_api.c.
{
  //printf("mscgen_generate(in=%s,out=%s,format=%d)\n",inputFile,outputFile,format);
  ADrawOutputType outType;
  ADrawColour *entColourRef = NULL;
  const char *outImage = outputFile;
  Msc m;
  float f;
  unsigned int w, h, row, col;
  RowInfo *rowInfo = NULL;
  Boolean addLines;
  FILE *ismap = NULL;
#if defined(_WIN32) && !defined(__CYGWIN__)
  const char *nullFile = "nul";
#else
  const char *nullFile = "/dev/null";
#endif
  Context ctx;
  ctx.opts = gDefaultOpts;
  switch (format)
  {
    case mscgen_format_png:
      outType = ADRAW_FMT_PNG;
      break;
    case mscgen_format_eps:
      outType = ADRAW_FMT_EPS;
      break;
    case mscgen_format_svg:
      outType = ADRAW_FMT_SVG;
      break;
    case mscgen_format_pngmap:
      outType = ADRAW_FMT_PNG;
      outImage = nullFile;
      break;
    case mscgen_format_svgmap:
      outType = ADRAW_FMT_SVG;
      outImage = nullFile;
      break;
  }
  /* open file */
  FILE *in = fopen(inputFile, "r");
  if (!in)
  {
    fprintf(stderr, "Failed to open input file '%s'\n", inputFile);
    return MSCGEN_FILE_ERROR;
  }
  /* parse file */
  m = MscParse(in);
  fclose(in);
  if (!m || !checkMsc(m))
  {
    fprintf(stderr, "Input format error for '%s'\n", inputFile);
    return MSCGEN_INPUT_FORMAT_ERROR;
  }
  /* Check if an ismap file should also be generated */
  if (format==mscgen_format_pngmap || format==mscgen_format_svgmap)
  {
      ismap = fopen(outputFile, "w");
      if (!ismap)
      {
        fprintf(stderr, "Failed to open output file '%s': %s\n", outputFile, strerror(errno));
        MscFree(m);
        return MSCGEN_FILE_ERROR;
      }
  }
  /* Open the drawing context with dummy dimensions */
  if (!ADrawOpen(10, 10, nullFile, "", outType, &ctx.drw))
  {
    if (ismap)
    {
      fclose(ismap);
    }
    MscFree(m);
    fprintf(stderr, "Failed to open temporary drawing context\n");
    return MSCGEN_OUTPUT_CONTEXT_ERROR;
  }
  /* Now compute ideal canvas size, which may use text metrics */
  if (MscGetOptAsFloat(m, MSC_OPT_WIDTH, &f))
  {
     ctx.opts.idealCanvasWidth = (unsigned int)f;
  }
  else if (MscGetOptAsFloat(m, MSC_OPT_HSCALE, &f))
  {
     ctx.opts.idealCanvasWidth *= (unsigned int)f;
  }
  /* Set the arc gradient if needed */
  if (MscGetOptAsFloat(m, MSC_OPT_ARCGRADIENT, &f))
  {
     ctx.opts.arcGradient = (int)f;
     ctx.opts.arcSpacing += ctx.opts.arcGradient;
  }
  /* Check if word wrapping on arcs other than boxes should be used */
  MscGetOptAsBoolean(m, MSC_OPT_WORDWRAPARCS, &ctx.opts.wordWrapArcLabels);
  /* Work out the entitySpacing */
  if (ctx.opts.idealCanvasWidth / MscGetNumEntities(m) > ctx.opts.entitySpacing)
  {
    ctx.opts.entitySpacing = ctx.opts.idealCanvasWidth / MscGetNumEntities(m);
  }
  /* Work out the entityHeadGap */
  MscResetEntityIterator(m);
  for (col = 0; col < MscGetNumEntities(m); col++)
  {
    unsigned int lines = countLines(MscGetCurrentEntAttrib(m, MSC_ATTR_LABEL));
    unsigned int gap;
    /* Get the required gap */
    gap = lines * ctx.drw.textHeight(&ctx.drw);
    if (gap > ctx.opts.entityHeadGap)
    {
      ctx.opts.entityHeadGap = gap;
    }
    MscNextEntity(m);
  }
  //printf("opts: idealCanvasWidth=%d entitySpacing=%d entityHeadGap=%d "
  // "arcSpacing=%d arcGradient=%d boxSpacing=%d boxInternalBorder=%d "
  // "rboxArc=%d noteCorner=%d aboxSlope=%d wordWrapArcLabels=%d arrowWidth=%d "
  // "arrowHeight=%d loopArcHeight=%d textHGapPre=%d textHGapPost=%d\n",
  // ctx.opts.idealCanvasWidth,ctx.opts.entitySpacing,ctx.opts.entityHeadGap,
  // ctx.opts.arcSpacing,ctx.opts.arcGradient,ctx.opts.boxSpacing,ctx.opts.boxInternalBorder,
  // ctx.opts.rboxArc,ctx.opts.noteCorner,ctx.opts.aboxSlope,ctx.opts.wordWrapArcLabels,ctx.opts.arrowWidth,
  // ctx.opts.arrowHeight,ctx.opts.loopArcHeight,ctx.opts.textHGapPre,ctx.opts.textHGapPost);
  /* Work out the width and height of the canvas */
  rowInfo = computeCanvasSize(&ctx, m, &w , &h);
  /* Close the temporary output file */
  ctx.drw.close(&ctx.drw);
  //printf("opening canvas %d x %d for %s type=%d\n",w,h,outImage,outType);
  /* Open the output */
  if (!ADrawOpen(w, h, outImage, "", outType, &ctx.drw))
  {
    free(rowInfo);
    if (ismap)
    {
      fclose(ismap);
    }
    MscFree(m);
    return MSCGEN_OUTPUT_CONTEXT_ERROR;
  }
  /* Allocate storage for entity heading colours */
  entColourRef = malloc_s(MscGetNumEntities(m) * sizeof(ADrawColour));
  /* Draw the entity headings */
  MscResetEntityIterator(m);
  for (col = 0; col < MscGetNumEntities(m); col++)
  {
    unsigned int x = (ctx.opts.entitySpacing / 2) + (ctx.opts.entitySpacing * col);
    const char *line;
    /* Titles */
    entityText(&ctx, ismap,
        x,
        ctx.opts.entityHeadGap - (ctx.drw.textHeight(&ctx.drw) / 2),
        MscGetCurrentEntAttrib(m, MSC_ATTR_LABEL),
        MscGetCurrentEntAttrib(m, MSC_ATTR_URL),
        MscGetCurrentEntAttrib(m, MSC_ATTR_ID),
        MscGetCurrentEntAttrib(m, MSC_ATTR_IDURL),
        MscGetCurrentEntAttrib(m, MSC_ATTR_TEXT_COLOUR),
        MscGetCurrentEntAttrib(m, MSC_ATTR_TEXT_BGCOLOUR));
    /* Get the colours */
    line = MscGetCurrentEntAttrib(m, MSC_ATTR_LINE_COLOUR);
    if (line != NULL)
    {
      entColourRef[col] = ADrawGetColour(line);
    }
    else
    {
      entColourRef[col] = ADRAW_COL_BLACK;
    }
    MscNextEntity(m);
  }
  /* Draw the arcs */
  addLines = TRUE;
  row = 0;
  MscResetArcIterator(m);
  do
  {
    const MscArcType arcType = MscGetCurrentArcType(m);
    const char *arcUrl = MscGetCurrentArcAttrib(m, MSC_ATTR_URL);
    const char *arcId = MscGetCurrentArcAttrib(m, MSC_ATTR_ID);
    const char *arcIdUrl = MscGetCurrentArcAttrib(m, MSC_ATTR_IDURL);
    const char *arcTextColour = MscGetCurrentArcAttrib(m, MSC_ATTR_TEXT_COLOUR);
    const char *arcTextBgColour = MscGetCurrentArcAttrib(m, MSC_ATTR_TEXT_BGCOLOUR);
    const char *arcLineColour = MscGetCurrentArcAttrib(m, MSC_ATTR_LINE_COLOUR);
    const int arcGradient = isBoxArc(arcType) ? 0 : getArcGradient(&ctx, m, rowInfo, row);
    const int arcHasArrows = MscGetCurrentArcAttrib(m, MSC_ATTR_NO_ARROWS) == NULL;
    const int arcHasBiArrows = MscGetCurrentArcAttrib(m, MSC_ATTR_BI_ARROWS) != NULL;
    char **arcLabelLines = NULL;
    unsigned int arcLabelLineCount = 0;
    int startCol = -1, endCol = -1;
    if (arcType == MSC_ARC_PARALLEL)
    {
      addLines = FALSE;
      /* Rewind the row */
      assert(row > 0);
      row--;
    }
    else
    {
      const unsigned int ymin = rowInfo[row].ymin;
      const unsigned int ymid = rowInfo[row].arcliney;
      const unsigned int ymax = rowInfo[row].ymax;
#if 0
      /* For debug, mark the row spacing */
      ctx.drw.line(&ctx.drw, 0, ymin, 10, ymin);
      ctx.drw.line(&ctx.drw, 0, ymid, 5, ymid);
      ctx.drw.line(&ctx.drw, 0, ymax, 10, ymax);
#endif
      /* Get the entity indices */
      if (arcType != MSC_ARC_DISCO && arcType != MSC_ARC_DIVIDER && arcType != MSC_ARC_SPACE)
      {
        startCol = MscGetEntityIndex(m, MscGetCurrentArcSource(m));
        endCol = MscGetEntityIndex(m, MscGetCurrentArcDest(m));
        /* Check that the start column is known and the end column is
         * known, or that it's a broadcast arc
         */
        assert(startCol != -1);
        assert(endCol != -1 || isBroadcastArc(MscGetCurrentArcDest(m)));
        /* Check for entity colouring if not set explicitly on the arc */
        if (arcTextColour == NULL)
        {
          arcTextColour = MscGetEntAttrib(m, startCol, MSC_ATTR_ARC_TEXT_COLOUR);
        }
        if (arcTextBgColour == NULL)
        {
          arcTextBgColour = MscGetEntAttrib(m, startCol, MSC_ATTR_ARC_TEXT_BGCOLOUR);
        }
        if (arcLineColour == NULL)
        {
          arcLineColour = MscGetEntAttrib(m, startCol, MSC_ATTR_ARC_LINE_COLOUR);
        }
      }
      else
      {
        /* Discontinuity or parallel arc spans whole chart */
        startCol = 0;
        endCol = MscGetNumEntities(m) - 1;
      }
      /* Work out how the label fits the gap between entities */
      arcLabelLineCount = computeLabelLines(&ctx, m, arcType, &arcLabelLines,
          MscGetCurrentArcAttrib(m, MSC_ATTR_LABEL),
          startCol, endCol);
      /* Check if this is a broadcast message */
      if (isBroadcastArc(MscGetCurrentArcDest(m)))
      {
        unsigned int t;
        /* Add in the entity lines */
        if (addLines)
        {
          entityLines(&ctx, m, ymin, ymax + ctx.opts.arcSpacing, FALSE, entColourRef);
        }
        /* Draw arcs to each entity */
        for (t = 0; t < MscGetNumEntities(m); t++)
        {
          if ((signed)t != startCol)
          {
            arcLine(&ctx, m, ymid, arcGradient, startCol,
                t, arcLineColour, arcHasArrows,
                arcHasBiArrows, arcType);
          }
        }
        /* Fix up the start/end columns to span chart */
        startCol = 0;
        endCol = MscGetNumEntities(m) - 1;
      }
      else
      {
        /* Check if it is a box, discontinuity arc etc... */
        if (isBoxArc(arcType))
        {
          if (addLines)
          {
            entityLines(&ctx, m, ymin, ymax + ctx.opts.arcSpacing, FALSE, entColourRef);
          }
          arcBox(&ctx, ymin, ymax, startCol, endCol, arcType, arcLineColour, arcTextBgColour);
        }
        else if (arcType == MSC_ARC_DISCO)
        {
          if (addLines)
          {
            entityLines(&ctx, m, ymin, ymax + ctx.opts.arcSpacing, TRUE /* dotted */, entColourRef);
          }
        }
        else if (arcType == MSC_ARC_DIVIDER || arcType == MSC_ARC_SPACE)
        {
          if (addLines)
          {
            entityLines(&ctx, m, ymin, ymax + ctx.opts.arcSpacing, FALSE, entColourRef);
          }
          /* Dividers also have a horizontal line at the middle */
          if (arcType == MSC_ARC_DIVIDER)
          {
            const unsigned int margin = ctx.opts.entitySpacing / 4;
            if (arcLineColour != NULL)
            {
              ctx.drw.setPen(&ctx.drw, ADrawGetColour(arcLineColour));
            }
            /* Draw line through middle of text */
            ctx.drw.dottedLine(&ctx.drw,
                margin, ymid,
                (MscGetNumEntities(m) * ctx.opts.entitySpacing) - margin, ymid);
            if (arcLineColour != NULL)
            {
              ctx.drw.setPen(&ctx.drw, ADRAW_COL_BLACK);
            }
          }
        }
        else
        {
          if (addLines)
          {
            entityLines(&ctx, m, ymin, ymax + ctx.opts.arcSpacing, FALSE, entColourRef);
          }
          arcLine(&ctx, m, ymid, arcGradient, startCol, endCol, arcLineColour,
              arcHasArrows, arcHasBiArrows, arcType);
        }
      }
      /* All may have text */
      if (arcLabelLineCount > 0)
      {
        arcText(&ctx, m, ismap, w, ymid, arcGradient,
            startCol, endCol,
            arcLabelLineCount, arcLabelLines,
            arcUrl, arcId, arcIdUrl,
            arcTextColour, arcTextBgColour, arcType);
      }
      freeLabelLines(arcLabelLineCount, arcLabelLines);
      /* Advance the row */
      row++;
      addLines = TRUE;
    }
  } while (MscNextArc(m));
  /* Skip arcs may require the entity lines to be extended */
  entityLines(&ctx, m,
      rowInfo[(MscGetNumArcs(m) - MscGetNumParallelArcs(m)) - 1].ymax,
      h, FALSE, entColourRef);
  if (ismap)
  {
    fclose(ismap);
  }
  free(entColourRef);
  free(rowInfo);
  MscFree(m);
  /* Close the context */
  ctx.drw.close(&ctx.drw);
  return MSCGEN_OK;
}
References ADRAW_COL_BLACK, ADRAW_FMT_EPS, ADRAW_FMT_PNG, ADRAW_FMT_SVG, ADrawGetColour(), ADrawOpen(), arcBox(), GlobalOptionsTag::arcGradient, arcLine(), RowInfo::arcliney, GlobalOptionsTag::arcSpacing, arcText(), checkMsc(), ADrawTag::close, computeCanvasSize(), computeLabelLines(), countLines(), ADrawTag::dottedLine, ContextTag::drw, GlobalOptionsTag::entityHeadGap, entityLines(), GlobalOptionsTag::entitySpacing, entityText(), errno, f, FALSE, Portable::fclose(), Portable::fopen(), freeLabelLines(), gDefaultOpts, getArcGradient(), h, GlobalOptionsTag::idealCanvasWidth, isBoxArc(), isBroadcastArc(), ADrawTag::line, malloc_s(), MSC_ARC_DISCO, MSC_ARC_DIVIDER, MSC_ARC_PARALLEL, MSC_ARC_SPACE, MSC_ATTR_ARC_LINE_COLOUR, MSC_ATTR_ARC_TEXT_BGCOLOUR, MSC_ATTR_ARC_TEXT_COLOUR, MSC_ATTR_BI_ARROWS, MSC_ATTR_ID, MSC_ATTR_IDURL, MSC_ATTR_LABEL, MSC_ATTR_LINE_COLOUR, MSC_ATTR_NO_ARROWS, MSC_ATTR_TEXT_BGCOLOUR, MSC_ATTR_TEXT_COLOUR, MSC_ATTR_URL, MSC_OPT_ARCGRADIENT, MSC_OPT_HSCALE, MSC_OPT_WIDTH, MSC_OPT_WORDWRAPARCS, MscFree(), MSCGEN_FILE_ERROR, mscgen_format_eps, mscgen_format_png, mscgen_format_pngmap, mscgen_format_svg, mscgen_format_svgmap, MSCGEN_INPUT_FORMAT_ERROR, MSCGEN_OK, MSCGEN_OUTPUT_CONTEXT_ERROR, MscGetCurrentArcAttrib(), MscGetCurrentArcDest(), MscGetCurrentArcSource(), MscGetCurrentArcType(), MscGetCurrentEntAttrib(), MscGetEntAttrib(), MscGetEntityIndex(), MscGetNumArcs(), MscGetNumEntities(), MscGetNumParallelArcs(), MscGetOptAsBoolean(), MscGetOptAsFloat(), MscNextArc(), MscNextEntity(), MscParse(), MscResetArcIterator(), MscResetEntityIterator(), ContextTag::opts, ADrawTag::setPen, ADrawTag::textHeight, TRUE, w, GlobalOptionsTag::wordWrapArcLabels, x, RowInfo::ymax, and RowInfo::ymin.
Referenced by getMscImageMapFromFile(), and writeMscGraphFromFile().
splitStringToWidth()
static char * splitStringToWidth (Context * ctx, char * l, unsigned int width) [static]
Word wrap a line of text until the first line is less than width wide. This removes words from the input line and builds them into a 2nd new string until the input line is shorter than the supplied width. The input string is directly truncated, while the remaining characters are returned in a new memory allocation. On return, the input line of text will be shorter than width, while the newly returned string will contain all the remaining characters.
If the input line is already shorter than width, the function returns NULL and does not modify the input line of text.
Parameters
 in,out l Input line of text which maybe modified if needed.
 in width Maximum allowable text line width.
Returns
NULL if l was already less then width long, otherwise a new string giving the remained of the string.
Definition at line 249 of file mscgen_api.c.
{
    char *p = l + strlen(l);
    char *orig = NULL;
    int m, n;
    if (ctx->drw.textWidth(&ctx->drw, l) > width)
    {
        /* Duplicate the original string */
        orig = strdup_s(l);
        /* Now remove words from the line until it fits the available width */
        do
        {
            /* Skip back 1 word */
            while (!isspace(*p) && p > l)
            {
                p--;
            }
            if (p > l)
            {
                *p = '\0';
            }
        }
        while (ctx->drw.textWidth(&ctx->drw, l) > width && p > l);
        /* Check if the first word is bigger than the available space;
         * we need to hyphenate in this case.
         */
        if (p == l)
        {
            const unsigned int hyphenWidth = ctx->drw.textWidth(&ctx->drw, "-");
            /* Find the end of the first word */
            while (!isspace(*p) && *p != '\0')
            {
                p++;
            }
            /* Start removing characters from the word */
            do
            {
                *p = '\0';
                p--;
            }
            while (ctx->drw.textWidth(&ctx->drw, l) + hyphenWidth > width && p > l);
            /* Add a hyphen */
            *p = '-';
        }
        /* Copy the remaining line to the start of the string */
        m = 0;
        n = (int)(p - l);
        while (isspace(orig[n]) && orig[n] != '\0')
        {
            n++;
        }
        do
        {
            orig[m++] = orig[n++];
        }
        while (orig[m - 1] != '\0');
    }
    return orig;
}
References ContextTag::drw, reg::isspace(), n, p, strdup_s(), and ADrawTag::textWidth.
Referenced by computeLabelLines().
Variable Documentation
gDefaultOpts
const GlobalOptions gDefaultOpts [static]
Initial value:
=
{
    600,
    80,
    20,
    6,
    0,
    8,
    4,
    6,
    12,
    6,
    FALSE,
    
    10, 6,
    
    12,
    
    2, 2
}
Definition at line 123 of file mscgen_api.c.
Referenced by mscgen_generate().