doxygen/build/doxygen/examples/restypedef.cpp File Reference
Classes
struct CoordStruct
Typedefs
typedef CoordStruct Coord
Functions
Coord add (Coord c1, Coord c2)
Detailed Description
An example of resolving typedefs.
Definition in file restypedef.cpp.
Typedef Documentation
Coord
typedef CoordStruct Coord
Creates a type name for CoordStruct
Definition at line 17 of file restypedef.cpp.
Function Documentation
add()
Coord add (Coord c1, Coord c2)
This function returns the addition of c1 and c2, i.e: (c1.x+c2.x,c1.y+c2.y)
Definition at line 23 of file restypedef.cpp.
{
}
Referenced by addClassToContext(), addConceptToContext(), ClassDefImpl::addTypeConstraint(), buildNamespaceList(), buildScopeFromQualifiedName(), createTagLessInstance(), findClassRelation(), findUsedClassesForClass(), findUsingDeclarations(), findUsingDirectives(), and ClassDefImpl::insertTemplateInstance().