doxygen/build/doxygen/addon/doxywizard/doxywizard.cpp File Reference
#include `doxywizard.h`
#include `version.h`
#include `expert.h`
#include `wizard.h`
#include <QMenu>
#include <QMenuBar>
#include <QPushButton>
#include <QMessageBox>
#include <QVBoxLayout>
#include <QLineEdit>
#include <QLabel>
#include <QCheckBox>
#include <QTextBrowser>
#include <QStatusBar>
#include <QProcess>
#include <QTimer>
#include <QCloseEvent>
#include <QApplication>
#include <QDir>
#include <QFileDialog>
#include <QDesktopServices>
#include <QUrl>
#include <QTextStream>
#include <QRegularExpression>
#include <QDebug>
#include <QDate>
Macros
#define MAX_RECENT_FILES 10
#define APPQT(x) QString::fromLatin1(`<qt><pre>`) + x + QString::fromLatin1(`</pre></qt>`)
Functions
int main (int argc, char **argv)
Variables
const int messageTimeout = 5000
status bar message timeout in milliseconds.
static QString text1 = QString::fromLatin1(``)
Macro Definition Documentation
APPQT
#define APPQT(x) QString::fromLatin1(`<qt><pre>`) + x + QString::fromLatin1(`</pre></qt>`)
Definition at line 52 of file doxywizard.cpp.
MAX_RECENT_FILES
#define MAX_RECENT_FILES 10
Definition at line 45 of file doxywizard.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 780 of file doxywizard.cpp.
{
  QApplication a(argc,argv);
  int locArgc = argc;
  if (locArgc == 2)
  {
    if (!qstrcmp(argv[1],"--help"))
    {
      QMessageBox msgBox;
      msgBox.setText(QString::fromLatin1("Usage: %1 [config file]").arg(QString::fromLatin1(argv[0])));
      msgBox.exec();
      exit(0);
    }
    else if (!qstrcmp(argv[1],"--version"))
    {
      QMessageBox msgBox;
      if (!qstrcmp(qVersion(),QT_VERSION_STR))
      {
        msgBox.setText(QString::fromLatin1("Doxywizard version: %1, Qt version: %2").arg(QString::fromLatin1(getFullVersion()),QString::fromLatin1(QT_VERSION_STR)));
      }
      else
      {
        msgBox.setText(QString::fromLatin1("Doxywizard version: %1, Qt version: created with %2, running with %3").arg(QString::fromLatin1(getFullVersion()),QString::fromLatin1(QT_VERSION_STR),QString::fromLatin1(qVersion())));
      }
      msgBox.exec();
      exit(0);
    }
  }
  if (!qstrcmp(argv[1],"--debug") && ((locArgc == 2) || (locArgc == 3)))
  {
    DoxygenWizard::debugFlag = true;
    locArgc--;
  }
  if (locArgc > 2)
  {
    QMessageBox msgBox;
    msgBox.setText(QString::fromLatin1("Too many arguments specified\n\nUsage: %1 [config file]").arg(QString::fromLatin1(argv[0])));
    msgBox.exec();
    exit(1);
  }
  else
  {
    MainWindow &main = MainWindow::instance();
    if (locArgc==2 && argv[argc-1][0]!='-') // name of config file as an argument
    {
      main.loadConfigFromFile(QString::fromLocal8Bit(argv[argc-1]));
    }
    main.show();
    return a.exec();
  }
}
References a, DoxygenWizard::debugFlag, getFullVersion(), MainWindow::instance(), main(), and qstrcmp().
Variable Documentation
messageTimeout
const int messageTimeout = 5000
status bar message timeout in milliseconds.
Definition at line 50 of file doxywizard.cpp.
text1
QString text1 = QString::fromLatin1(``) [static]
Definition at line 54 of file doxywizard.cpp.