doxygen/build/doxygen/src/docbookgen.cpp File Reference
#include <stdlib.h>
#include `docbookgen.h`
#include `doxygen.h`
#include `message.h`
#include `config.h`
#include `classlist.h`
#include `classdef.h`
#include `diagram.h`
#include `util.h`
#include `defargs.h`
#include `outputgen.h`
#include `dot.h`
#include `dotcallgraph.h`
#include `dotclassgraph.h`
#include `dotdirdeps.h`
#include `dotgroupcollaboration.h`
#include `dotincldepgraph.h`
#include `pagedef.h`
#include `filename.h`
#include `version.h`
#include `docbookvisitor.h`
#include `docparser.h`
#include `language.h`
#include `parserintf.h`
#include `arguments.h`
#include `memberlist.h`
#include `groupdef.h`
#include `memberdef.h`
#include `namespacedef.h`
#include `membername.h`
#include `membergroup.h`
#include `dirdef.h`
#include `section.h`
#include `dir.h`
Macros
#define Docbook_DB(x) do {} while(0)
#define DB_GEN_C
#define DB_GEN_C1(x)
#define DB_GEN_C2(y)
#define DB_GEN_C2a(x, y)
Functions
void writeDocbookString (TextStream &t, const QCString &s)
void writeDocbookCodeString (TextStream &t, const QCString &str, int &col)
static void addIndexTerm (TextStream &t, QCString prim, QCString sec=``)
void writeDocbookLink (TextStream &t, const QCString &, const QCString &compoundId, const QCString &anchorId, const QCString &text, const QCString &)
Macro Definition Documentation
DB_GEN_C
#define DB_GEN_C
Definition at line 67 of file docbookgen.cpp.
DB_GEN_C1
#define DB_GEN_C1(x)
Definition at line 68 of file docbookgen.cpp.
DB_GEN_C2
#define DB_GEN_C2(y)
Definition at line 69 of file docbookgen.cpp.
DB_GEN_C2a
#define DB_GEN_C2a(x, y)
Definition at line 70 of file docbookgen.cpp.
Docbook_DB
#define Docbook_DB(x) do {} while(0)
Definition at line 55 of file docbookgen.cpp.
Function Documentation
addIndexTerm()
static void addIndexTerm (TextStream & t, QCString prim, QCString sec = ``) [static]
Definition at line 122 of file docbookgen.cpp.
{
  t << "<indexterm><primary>";
  t << convertToDocBook(prim);
  t << "</primary>";
  if (!sec.isEmpty())
  {
    t << "<secondary>";
    t << convertToDocBook(sec);
    t << "</secondary>";
  }
  t << "</indexterm>\n";
}
References convertToDocBook().
Referenced by DocbookGenerator::addIndexItem(), DocbookGenerator::endTitleHead(), and DocbookGenerator::startMemberDoc().
writeDocbookCodeString()
void writeDocbookCodeString (TextStream & t, const QCString & str, int & col) [inline]
Definition at line 80 of file docbookgen.cpp.
{
  if (str.isEmpty()) return;
  const char *s = str.data();
  char c;
  while ((c=*s++))
  {
    switch(c)
    {
      case '\t':
        {
          int tabSize = Config_getInt(TAB_SIZE);
          int spacesToNextTabStop = tabSize - (col%tabSize);
          col+=spacesToNextTabStop;
          while (spacesToNextTabStop--) t << "&#32;";
          break;
        }
      case ' ': t << "&#32;"; col++; break;
      case '<': t << "&lt;"; col++; break;
      case '>': t << "&gt;"; col++; break;
      case '&': t << "&amp;"; col++; break;
      case '\'': t << "&apos;"; col++; break;
      case '"': t << "&quot;"; col++; break;
      default:
        {
          uchar uc = static_cast<uchar>(c);
          static const char *hex="0123456789ABCDEF";
          if (uc<32)
          {
            t << "&#x24" << hex[uc>>4] << hex[uc&0xF] << ";";
          }
          else
          {
            t << c;
          }
          col++;
        }
        break;
    }
  }
}
References c, Config_getInt, QCString::data(), hex, QCString::isEmpty(), and s.
Referenced by DocbookCodeGenerator::codify().
writeDocbookLink()
void writeDocbookLink (TextStream & t, const QCString & , const QCString & compoundId, const QCString & anchorId, const QCString & text, const QCString &)
Definition at line 135 of file docbookgen.cpp.
{
  t << "<link linkend=\"_" << stripPath(compoundId);
  if (!anchorId.isEmpty()) t << "_1" << anchorId;
  t << "\"";
  t << ">";
  writeDocbookString(t,text);
  t << "</link>";
}
References QCString::isEmpty(), stripPath(), and writeDocbookString().
Referenced by DocbookCodeGenerator::writeCodeLink().
writeDocbookString()
void writeDocbookString (TextStream & t, const QCString & s) [inline]
Definition at line 75 of file docbookgen.cpp.
{
  t << convertToDocBook(s);
}
References convertToDocBook(), and s.
Referenced by DocbookCodeGenerator::writeCodeLinkLine(), and writeDocbookLink().