doxygen/build/doxygen/libmscgen/mscgen_null_out.c File Reference
#include <stdio.h>
#include <assert.h>
#include `mscgen_adraw_int.h`
Functions
static unsigned int NullTextWidth (struct ADrawTag *ctx UNUSED, const char *string UNUSED)
static int NullTextHeight (struct ADrawTag *ctx UNUSED)
static void NullLine (struct ADrawTag *ctx UNUSED, unsigned int x1 UNUSED, unsigned int y1 UNUSED, unsigned int x2 UNUSED, unsigned int y2 UNUSED)
static void NullDottedLine (struct ADrawTag *ctx UNUSED, unsigned int x1 UNUSED, unsigned int y1 UNUSED, unsigned int x2 UNUSED, unsigned int y2 UNUSED)
static void NullTextR (struct ADrawTag *ctx UNUSED, unsigned int x UNUSED, unsigned int y UNUSED, const char *string UNUSED)
static void NullTextL (struct ADrawTag *ctx UNUSED, unsigned int x UNUSED, unsigned int y UNUSED, const char *string UNUSED)
static void NullTextC (struct ADrawTag *ctx UNUSED, unsigned int x UNUSED, unsigned int y UNUSED, const char *string UNUSED)
static void NullFilledRectangle (struct ADrawTag *ctx UNUSED, unsigned int x1 UNUSED, unsigned int y1 UNUSED, unsigned int x2 UNUSED, unsigned int y2 UNUSED)
static void NullFilledTriangle (struct ADrawTag *ctx UNUSED, unsigned int x1 UNUSED, unsigned int y1 UNUSED, unsigned int x2 UNUSED, unsigned int y2 UNUSED, unsigned int x3 UNUSED, unsigned int y3 UNUSED)
static void NullArc (struct ADrawTag *ctx UNUSED, unsigned int cx UNUSED, unsigned int cy UNUSED, unsigned int w UNUSED, unsigned int h UNUSED, unsigned int s UNUSED, unsigned int e UNUSED)
static void NullDottedArc (struct ADrawTag *ctx UNUSED, unsigned int cx UNUSED, unsigned int cy UNUSED, unsigned int w UNUSED, unsigned int h UNUSED, unsigned int s UNUSED, unsigned int e UNUSED)
static void NullSetPen (struct ADrawTag *ctx UNUSED, ADrawColour col UNUSED)
static void NullSetFontSize (struct ADrawTag *ctx UNUSED, ADrawFontSize size UNUSED)
static Boolean NullClose (struct ADrawTag *ctx UNUSED)
Boolean NullInit (struct ADrawTag *outContext)
Function Documentation
NullArc()
static void NullArc (struct ADrawTag *ctx UNUSED, unsigned int cx UNUSED, unsigned int cy UNUSED, unsigned int w UNUSED, unsigned int h UNUSED, unsigned int s UNUSED, unsigned int e UNUSED) [static]
Definition at line 108 of file mscgen_null_out.c.
{
}
Referenced by NullInit().
NullClose()
static Boolean NullClose (struct ADrawTag *ctx UNUSED) [static]
Definition at line 142 of file mscgen_null_out.c.
{
    return TRUE;
}
References TRUE.
Referenced by NullInit().
NullDottedArc()
static void NullDottedArc (struct ADrawTag *ctx UNUSED, unsigned int cx UNUSED, unsigned int cy UNUSED, unsigned int w UNUSED, unsigned int h UNUSED, unsigned int s UNUSED, unsigned int e UNUSED) [static]
Definition at line 119 of file mscgen_null_out.c.
{
}
Referenced by NullInit().
NullDottedLine()
static void NullDottedLine (struct ADrawTag *ctx UNUSED, unsigned int x1 UNUSED, unsigned int y1 UNUSED, unsigned int x2 UNUSED, unsigned int y2 UNUSED) [static]
Definition at line 55 of file mscgen_null_out.c.
{
}
Referenced by NullInit().
NullFilledRectangle()
static void NullFilledRectangle (struct ADrawTag *ctx UNUSED, unsigned int x1 UNUSED, unsigned int y1 UNUSED, unsigned int x2 UNUSED, unsigned int y2 UNUSED) [static]
Definition at line 88 of file mscgen_null_out.c.
{
}
Referenced by NullInit().
NullFilledTriangle()
static void NullFilledTriangle (struct ADrawTag *ctx UNUSED, unsigned int x1 UNUSED, unsigned int y1 UNUSED, unsigned int x2 UNUSED, unsigned int y2 UNUSED, unsigned int x3 UNUSED, unsigned int y3 UNUSED) [static]
Definition at line 97 of file mscgen_null_out.c.
{
}
Referenced by NullInit().
NullInit()
Boolean NullInit (struct ADrawTag * outContext)
Definition at line 148 of file mscgen_null_out.c.
{
    /* Fill in the function pointers */
    outContext->line = NullLine;
    outContext->dottedLine = NullDottedLine;
    outContext->textL = NullTextL;
    outContext->textC = NullTextC;
    outContext->textR = NullTextR;
    outContext->textWidth = NullTextWidth;
    outContext->textHeight = NullTextHeight;
    outContext->filledRectangle = NullFilledRectangle;
    outContext->filledTriangle = NullFilledTriangle;
    outContext->arc = NullArc;
    outContext->dottedArc = NullDottedArc;
    outContext->setPen = NullSetPen;
    outContext->setBgPen = NullSetPen;
    outContext->setFontSize = NullSetFontSize;
    outContext->close = NullClose;
    return TRUE;
}
NullLine()
static void NullLine (struct ADrawTag *ctx UNUSED, unsigned int x1 UNUSED, unsigned int y1 UNUSED, unsigned int x2 UNUSED, unsigned int y2 UNUSED) [static]
Definition at line 46 of file mscgen_null_out.c.
{
}
Referenced by NullInit().
NullSetFontSize()
static void NullSetFontSize (struct ADrawTag *ctx UNUSED, ADrawFontSize size UNUSED) [static]
Definition at line 136 of file mscgen_null_out.c.
{
}
Referenced by NullInit().
NullSetPen()
static void NullSetPen (struct ADrawTag *ctx UNUSED, ADrawColour col UNUSED) [static]
Definition at line 130 of file mscgen_null_out.c.
{
}
Referenced by NullInit().
NullTextC()
static void NullTextC (struct ADrawTag *ctx UNUSED, unsigned int x UNUSED, unsigned int y UNUSED, const char *string UNUSED) [static]
Definition at line 80 of file mscgen_null_out.c.
{
}
Referenced by NullInit().
NullTextHeight()
static int NullTextHeight (struct ADrawTag *ctx UNUSED) [static]
Definition at line 40 of file mscgen_null_out.c.
{
    return 0;
}
Referenced by NullInit().
NullTextL()
static void NullTextL (struct ADrawTag *ctx UNUSED, unsigned int x UNUSED, unsigned int y UNUSED, const char *string UNUSED) [static]
Definition at line 72 of file mscgen_null_out.c.
{
}
Referenced by NullInit().
NullTextR()
static void NullTextR (struct ADrawTag *ctx UNUSED, unsigned int x UNUSED, unsigned int y UNUSED, const char *string UNUSED) [static]
Definition at line 64 of file mscgen_null_out.c.
{
}
Referenced by NullInit().
NullTextWidth()
static unsigned int NullTextWidth (struct ADrawTag *ctx UNUSED, const char *string UNUSED) [static]
Definition at line 33 of file mscgen_null_out.c.
{
    return 0;
}
Referenced by NullInit().