doxygen/build/doxygen/libmscgen/mscgen_gd_out.c File Reference
#include `mscgen_config.h`
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <limits.h>
#include `gd.h`
#include `gdfontt.h`
#include `gdfonts.h`
#include `mscgen_adraw_int.h`
#include `mscgen_safe.h`
Classes
struct GdoContextTag
Macros
#define MAX_COLOURS 128
Typedefs
typedef struct GdoContextTag GdoContext
Functions
static void swap (unsigned int *a, unsigned int *b)
static GdoContext * getGdoCtx (struct ADrawTag *ctx)
static gdImagePtr getGdoImg (struct ADrawTag *ctx)
static int getGdoPen (struct ADrawTag *ctx)
static int getColourRef (GdoContext *context, ADrawColour col)
static void setStyle (struct ADrawTag *ctx)
unsigned int gdoTextWidth (struct ADrawTag *ctx, const char *string)
int gdoTextHeight (struct ADrawTag *ctx)
void gdoLine (struct ADrawTag *ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
void gdoDottedLine (struct ADrawTag *ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
void gdoTextR (struct ADrawTag *ctx, unsigned int x, unsigned int y, const char *string)
void gdoTextL (struct ADrawTag *ctx, unsigned int x, unsigned int y, const char *string)
void gdoTextC (struct ADrawTag *ctx, unsigned int x, unsigned int y, const char *string)
void gdoFilledRectangle (struct ADrawTag *ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
void gdoFilledTriangle (struct ADrawTag *ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2, unsigned int x3, unsigned int y3)
void gdoFilledCircle (struct ADrawTag *ctx, unsigned int x, unsigned int y, unsigned int r)
void gdoArc (struct ADrawTag *ctx, unsigned int cx, unsigned int cy, unsigned int w, unsigned int h, unsigned int s, unsigned int e)
void gdoDottedArc (struct ADrawTag *ctx, unsigned int cx, unsigned int cy, unsigned int w, unsigned int h, unsigned int s, unsigned int e)
void gdoSetPen (struct ADrawTag *ctx, ADrawColour col)
void gdoSetBgPen (struct ADrawTag *ctx, ADrawColour col)
void gdoSetFontSize (struct ADrawTag *ctx, ADrawFontSize size)
Boolean gdoClose (struct ADrawTag *ctx)
Boolean GdoInit (unsigned int w, unsigned int h, const char *file, const char *fontName UNUSED, struct ADrawTag *outContext)
Macro Definition Documentation
MAX_COLOURS
#define MAX_COLOURS 128
Definition at line 45 of file mscgen_gd_out.c.
Typedef Documentation
GdoContext
typedef struct GdoContextTag GdoContext
Function Documentation
gdoArc()
void gdoArc (struct ADrawTag * ctx, unsigned int cx, unsigned int cy, unsigned int w, unsigned int h, unsigned int s, unsigned int e)
Definition at line 415 of file mscgen_gd_out.c.
{
    /* Range check since gdImageArc takes signed values */
    if(cx <= INT_MAX && cy <= INT_MAX)
    {
        gdImageArc(getGdoImg(ctx), cx, cy, w, h, s, e, getGdoPen(ctx));
    }
}
References cx, cy, e, getGdoImg(), getGdoPen(), h, s, and w.
Referenced by GdoInit().
gdoClose()
Boolean gdoClose (struct ADrawTag * ctx)
Definition at line 495 of file mscgen_gd_out.c.
{
    GdoContext *context = getGdoCtx(ctx);
    /* Output the image to the disk file in PNG format. */
    gdImagePng(getGdoImg(ctx), context->outFile);
    if(context->outFile != stdout)
    {
        fclose(context->outFile);
    }
    /* Destroy the image in memory */
    gdImageDestroy(context->img);
    /* Free and destroy context */
    free(context);
    ctx->internal = NULL;
    return TRUE;
}
References Portable::fclose(), getGdoCtx(), getGdoImg(), GdoContextTag::img, ADrawTag::internal, GdoContextTag::outFile, and TRUE.
Referenced by GdoInit().
gdoDottedArc()
void gdoDottedArc (struct ADrawTag * ctx, unsigned int cx, unsigned int cy, unsigned int w, unsigned int h, unsigned int s, unsigned int e)
Definition at line 432 of file mscgen_gd_out.c.
{
    /* Range check since gdImageArc takes signed values */
    if(cx <= INT_MAX && cy <= INT_MAX)
    {
        setStyle(ctx);
        gdImageArc(getGdoImg(ctx), cx, cy, w, h, s, e, gdStyled);
    }
}
References cx, cy, e, gdStyled, getGdoImg(), h, s, setStyle(), and w.
Referenced by GdoInit().
gdoDottedLine()
void gdoDottedLine (struct ADrawTag * ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
Definition at line 269 of file mscgen_gd_out.c.
{
    setStyle(ctx);
    /* Range check since gdImageLine() takes signed values */
    if(x1 <= INT_MAX && y1 <= INT_MAX && x2 <= INT_MAX && y2 <= INT_MAX)
    {
        gdImageLine(getGdoImg(ctx), x1, y1, x2, y2, gdStyled);
    }
}
References gdStyled, getGdoImg(), setStyle(), x1, x2, y1, and y2.
Referenced by GdoInit().
gdoFilledCircle()
void gdoFilledCircle (struct ADrawTag * ctx, unsigned int x, unsigned int y, unsigned int r)
Definition at line 405 of file mscgen_gd_out.c.
{
    gdImageSetAntiAliased(getGdoImg(ctx), getGdoPen(ctx));
    gdImageFilledEllipse(getGdoImg(ctx), x, y, r * 2, r * 2, gdAntiAliased);
}
References gdAntiAliased, getGdoImg(), getGdoPen(), r, x, and y.
Referenced by GdoInit().
gdoFilledRectangle()
void gdoFilledRectangle (struct ADrawTag * ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
Definition at line 359 of file mscgen_gd_out.c.
{
    gdPoint p[4];
    /* Range check since gdPoint contains signed values */
    if(x1 <= INT_MAX && y1 <= INT_MAX && x2 <= INT_MAX && y2 <= INT_MAX)
    {
        p[0].x = x1; p[0].y = y1;
        p[1].x = x2; p[1].y = y1;
        p[2].x = x2; p[2].y = y2;
        p[3].x = x1; p[3].y = y2;
        gdImageFilledPolygon(getGdoImg(ctx), p, 4, getGdoPen(ctx));
    }
}
References getGdoImg(), getGdoPen(), p, gdPoint::x, x1, x2, gdPoint::y, y1, and y2.
Referenced by GdoInit().
gdoFilledTriangle()
void gdoFilledTriangle (struct ADrawTag * ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2, unsigned int x3, unsigned int y3)
Definition at line 380 of file mscgen_gd_out.c.
{
    gdPoint p[3];
    /* Range check since gdPoint contains signed values */
    if(x1 <= INT_MAX && y1 <= INT_MAX &&
       x2 <= INT_MAX && y2 <= INT_MAX &&
       x3 <= INT_MAX && y3 <= INT_MAX)
    {
        p[0].x = x1; p[0].y = y1;
        p[1].x = x2; p[1].y = y2;
        p[2].x = x3; p[2].y = y3;
        gdImageSetAntiAliased(getGdoImg(ctx), getGdoPen(ctx));
        gdImageFilledPolygon(getGdoImg(ctx), p, 3, gdAntiAliased);
    }
}
References gdAntiAliased, getGdoImg(), getGdoPen(), p, gdPoint::x, x1, x2, gdPoint::y, y1, and y2.
Referenced by GdoInit().
GdoInit()
Boolean GdoInit (unsigned int w, unsigned int h, const char * file, const char *fontName UNUSED, struct ADrawTag * outContext)
Definition at line 518 of file mscgen_gd_out.c.
{
    GdoContext *context;
    /* Range check the size */
    if(w > INT_MAX || h > INT_MAX)
    {
        fprintf(stderr, "Warning: The output image size larger than can be supported for png; output\n"
                        " will be clipped.\n");
    }
    /* Clip image size to limits */
    if(w > INT_MAX) w = INT_MAX;
    if(h > INT_MAX) h = INT_MAX;
    /* Create context */
    context = outContext->internal = zalloc_s(sizeof(GdoContext));
    if(context == NULL)
    {
        return FALSE;
    }
    /* Open the output file */
    if(strcmp(file, "-") == 0)
    {
        context->outFile = stdout;
    }
    else
    {
        context->outFile = fopen(file, "wb");
        if(!context->outFile)
        {
            fprintf(stderr, "GdoInit: Failed to open output file '%s': %s\n", file, strerror(errno));
            return FALSE;
        }
    }
#ifdef USE_FREETYPE
    /* Request that we use font config strings and store font name */
    gdFTUseFontConfig(1);
    context->fontName = fontName;
    assert(fontName != NULL);
#endif
    /* Allocate the image */
    context->img = gdImageCreateTrueColor(w, h);
    /* Allocate first colour and clear background */
    gdImageFilledRectangle(context->img,
                           0, 0,
                           w, h,
                           getColourRef(context, ADRAW_COL_WHITE));
    /* Set pen colour to black and background to white */
    context->pen = getColourRef(context, ADRAW_COL_BLACK);
    context->bgpen = getColourRef(context, ADRAW_COL_WHITE);
    /* Get the default font size */
    gdoSetFontSize(outContext, ADRAW_FONT_SMALL);
    /* Now fill in the function pointers */
    outContext->line = gdoLine;
    outContext->dottedLine = gdoDottedLine;
    outContext->textL = gdoTextL;
    outContext->textC = gdoTextC;
    outContext->textR = gdoTextR;
    outContext->textWidth = gdoTextWidth;
    outContext->textHeight = gdoTextHeight;
    outContext->filledRectangle = gdoFilledRectangle;
    outContext->filledTriangle = gdoFilledTriangle;
    outContext->filledCircle = gdoFilledCircle;
    outContext->arc = gdoArc;
    outContext->dottedArc = gdoDottedArc;
    outContext->setPen = gdoSetPen;
    outContext->setBgPen = gdoSetBgPen;
    outContext->setFontSize = gdoSetFontSize;
    outContext->close = gdoClose;
    return TRUE;
}
References ADRAW_COL_BLACK, ADRAW_COL_WHITE, ADRAW_FONT_SMALL, ADrawTag::arc, GdoContextTag::bgpen, ADrawTag::close, ADrawTag::dottedArc, ADrawTag::dottedLine, errno, FALSE, caseconvert::file, ADrawTag::filledCircle, ADrawTag::filledRectangle, ADrawTag::filledTriangle, Portable::fopen(), gdoArc(), gdoClose(), gdoDottedArc(), gdoDottedLine(), gdoFilledCircle(), gdoFilledRectangle(), gdoFilledTriangle(), gdoLine(), gdoSetBgPen(), gdoSetFontSize(), gdoSetPen(), gdoTextC(), gdoTextHeight(), gdoTextL(), gdoTextR(), gdoTextWidth(), getColourRef(), h, GdoContextTag::img, ADrawTag::internal, ADrawTag::line, GdoContextTag::outFile, GdoContextTag::pen, ADrawTag::setBgPen, ADrawTag::setFontSize, ADrawTag::setPen, strcmp(), ADrawTag::textC, ADrawTag::textHeight, ADrawTag::textL, ADrawTag::textR, ADrawTag::textWidth, TRUE, w, and zalloc_s().
gdoLine()
void gdoLine (struct ADrawTag * ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
Definition at line 246 of file mscgen_gd_out.c.
{
    /* Range check since gdImageLine() takes signed values */
    if(x1 <= INT_MAX && y1 <= INT_MAX && x2 <= INT_MAX && y2 <= INT_MAX)
    {
        /* Anti-aliasing fails if drawing 'backwards' for some octants */
        if(x1 > x2 && abs((int)x1 - (int)x2) > abs((int)y1 - (int)y2))
        {
            swap(&x1, &x2);
            swap(&y1, &y2);
        }
        gdImageSetAntiAliased(getGdoImg(ctx), getGdoPen(ctx));
        gdImageLine(getGdoImg(ctx),
                    x1, y1, x2, y2, gdAntiAliased);
    }
}
References gdAntiAliased, getGdoImg(), getGdoPen(), swap(), x1, x2, y1, and y2.
Referenced by GdoInit().
gdoSetBgPen()
void gdoSetBgPen (struct ADrawTag * ctx, ADrawColour col)
Definition at line 458 of file mscgen_gd_out.c.
{
    GdoContext *context = getGdoCtx(ctx);;
    context->bgpen = getColourRef(context, col);
}
References GdoContextTag::bgpen, getColourRef(), and getGdoCtx().
Referenced by GdoInit().
gdoSetFontSize()
void gdoSetFontSize (struct ADrawTag * ctx, ADrawFontSize size)
Definition at line 467 of file mscgen_gd_out.c.
{
    switch(size)
    {
#ifdef USE_FREETYPE
        case ADRAW_FONT_TINY:
            getGdoCtx(ctx)->fontPoints = 9.0;
            break;
        case ADRAW_FONT_SMALL:
            getGdoCtx(ctx)->fontPoints = 11.0;
            break;
#else
        case ADRAW_FONT_TINY:
            getGdoCtx(ctx)->font = gdFontGetTiny();
            break;
        case ADRAW_FONT_SMALL:
            getGdoCtx(ctx)->font = gdFontGetSmall();
            break;
#endif
        default:
            assert(0);
    }
}
References ADRAW_FONT_SMALL, ADRAW_FONT_TINY, GdoContextTag::font, gdFontGetSmall(), gdFontGetTiny(), getGdoCtx(), and size.
Referenced by GdoInit().
gdoSetPen()
void gdoSetPen (struct ADrawTag * ctx, ADrawColour col)
Definition at line 449 of file mscgen_gd_out.c.
{
    GdoContext *context = getGdoCtx(ctx);;
    context->pen = getColourRef(context, col);
}
References getColourRef(), getGdoCtx(), and GdoContextTag::pen.
Referenced by GdoInit().
gdoTextC()
void gdoTextC (struct ADrawTag * ctx, unsigned int x, unsigned int y, const char * string)
Definition at line 351 of file mscgen_gd_out.c.
{
    gdoTextR(ctx, x - (gdoTextWidth(ctx, string) / 2), y, string);
}
References gdoTextR(), gdoTextWidth(), x, and y.
Referenced by GdoInit().
gdoTextHeight()
int gdoTextHeight (struct ADrawTag * ctx)
Definition at line 218 of file mscgen_gd_out.c.
{
#ifndef USE_FREETYPE
    return getGdoCtx(ctx)->font->h;
#else
    GdoContext *context = getGdoCtx(ctx);
    int rect[8] = { 0, 0, 0, 0, 0, 0, 0, 0 };
    const char *r;
    r = gdImageStringFT(NULL,
                        rect,
                        context->pen,
                        (char *)context->fontName,
                        context->fontPoints,
                        0,
                        0, 0,
                        "gHELLOWt");
    if(r)
    {
        fprintf(stderr, "Error: gdoTextHeight: %s (GDFONTPATH=%s)\n", r, mscgen_getenv_s("GDFONTPATH"));
        exit(EXIT_FAILURE);
    }
    return (-rect[5]) + 1;
#endif
}
References GdoContextTag::font, getGdoCtx(), gdFont::h, mscgen_getenv_s(), GdoContextTag::pen, and r.
Referenced by GdoInit(), and gdoTextR().
gdoTextL()
void gdoTextL (struct ADrawTag * ctx, unsigned int x, unsigned int y, const char * string)
Definition at line 337 of file mscgen_gd_out.c.
{
    x -= gdoTextWidth(ctx, string);
    /* Range check since gdImageFilledRectangle() takes signed values */
    if(x <= INT_MAX && y <= INT_MAX)
    {
        gdoTextR(ctx, x, y, string);
    }
}
References gdoTextR(), gdoTextWidth(), x, and y.
Referenced by GdoInit().
gdoTextR()
void gdoTextR (struct ADrawTag * ctx, unsigned int x, unsigned int y, const char * string)
Definition at line 285 of file mscgen_gd_out.c.
{
    GdoContext *context = getGdoCtx(ctx);
#ifdef USE_FREETYPE
    int rect[8] = { 0, 0, 0, 0, 0, 0, 0, 0 };
    const char *r;
#endif
    int textWidth;
    textWidth = gdoTextWidth(ctx, string);
    /* Range check since gdImageFilledRectangle() takes signed values */
    if(x + textWidth <= INT_MAX && y <= INT_MAX)
    {
        gdImageFilledRectangle(getGdoImg(ctx),
                              x,
                              y - (gdoTextHeight(ctx) - 2),
                              x + textWidth,
                              y - 2,
                              context->bgpen);
#ifdef USE_FREETYPE
        r = gdImageStringFT(getGdoImg(ctx),
                            rect,
                            context->pen,
                            (char *)context->fontName,
                            context->fontPoints,
                            0,
                            x, y - 2,
                            (char *)string);
        if(r)
        {
            fprintf(stderr, "Error: gdoTextR: %s (GDFONTPATH=%s)\n", r, mscgen_getenv_s("GDFONTPATH"));
            exit(EXIT_FAILURE);
        }
#else
        gdImageString(getGdoImg(ctx),
                      getGdoCtx(ctx)->font,
                      x,
                      y - gdoTextHeight(ctx),
                      (unsigned char *)string,
                      getGdoPen(ctx));
#endif
    }
}
References GdoContextTag::bgpen, gdoTextHeight(), gdoTextWidth(), getGdoCtx(), getGdoImg(), getGdoPen(), mscgen_getenv_s(), GdoContextTag::pen, r, x, and y.
Referenced by GdoInit(), gdoTextC(), and gdoTextL().
gdoTextWidth()
unsigned int gdoTextWidth (struct ADrawTag * ctx, const char * string)
Definition at line 179 of file mscgen_gd_out.c.
{
#ifndef USE_FREETYPE
    const unsigned int l = (unsigned int)strlen(string);
    /* Remove 1 pixel since there is usually an uneven gap at
     * the right of the last character for the fixed width
     * font.
     */
    return l == 0 ? 0 : (getGdoCtx(ctx)->font->w * l) - 1;
#else
    GdoContext *context = getGdoCtx(ctx);
    int rect[8] = { 0, 0, 0, 0, 0, 0, 0, 0 };
    const char *r;
    r = gdImageStringFT(NULL,
                        rect,
                        context->pen,
                        (char *)context->fontName,
                        context->fontPoints,
                        0,
                        0, 0,
                        (char *)string);
    if(r)
    {
        fprintf(stderr, "Error: gdoTextWidth: %s (GDFONTPATH=%s)\n", r, mscgen_getenv_s("GDFONTPATH"));
        exit(EXIT_FAILURE);
    }
    /* Remove 1 pixel since there is usually an uneven gap at
     * the right of the last character for the fixed width
     * font.
     */
    return rect[2] - 1;
#endif
}
References GdoContextTag::font, getGdoCtx(), mscgen_getenv_s(), GdoContextTag::pen, r, and gdFont::w.
Referenced by GdoInit(), gdoTextC(), gdoTextL(), and gdoTextR().
getColourRef()
static int getColourRef (GdoContext * context, ADrawColour col) [static]
Given a colour value, convert to a gd colour reference. This searches the current palette of colours for the passed colour and returns an existing reference if possible. Otherwise a new colour reference is allocated and returned.
Definition at line 126 of file mscgen_gd_out.c.
{
    int t;
    /* Check if the colour is already allocated */
    for(t = 0; t < context->colourCount; t++)
    {
        if(context->colour[t].col == col)
        {
            return context->colour[t].ref;
        }
    }
    /* Allocate a new colour if there is space */
    if(t < MAX_COLOURS)
    {
        /* Store the colour and allocate a reference */
        context->colour[t].col = col;
        context->colour[t].ref = gdImageColorAllocate(context->img,
                                                      (col & 0xff0000) >> 16,
                                                      (col & 0x00ff00) >> 8,
                                                      (col & 0x0000ff) >> 0);
        context->colourCount++;
        /* Return the new colour reference */
        return context->colour[t].ref;
    }
    else
    {
        /* Cannot allocate more colours, so return black by default */
        return getColourRef(context, ADRAW_COL_BLACK);
    }
}
References ADRAW_COL_BLACK, GdoContextTag::col, GdoContextTag::colour, GdoContextTag::colourCount, getColourRef(), GdoContextTag::img, MAX_COLOURS, and GdoContextTag::ref.
Referenced by GdoInit(), gdoSetBgPen(), gdoSetPen(), getColourRef(), and setStyle().
getGdoCtx()
static GdoContext * getGdoCtx (struct ADrawTag * ctx) [static]
Get the context pointer from an ADraw structure.
Definition at line 100 of file mscgen_gd_out.c.
{
    return (GdoContext *)ctx->internal;
}
References ADrawTag::internal.
Referenced by gdoClose(), gdoSetBgPen(), gdoSetFontSize(), gdoSetPen(), gdoTextHeight(), gdoTextR(), gdoTextWidth(), getGdoImg(), getGdoPen(), and setStyle().
getGdoImg()
static gdImagePtr getGdoImg (struct ADrawTag * ctx) [static]
Get the GD image pointer from an ADraw structure.
Definition at line 108 of file mscgen_gd_out.c.
{
    return getGdoCtx(ctx)->img;
}
References getGdoCtx(), and GdoContextTag::img.
Referenced by gdoArc(), gdoClose(), gdoDottedArc(), gdoDottedLine(), gdoFilledCircle(), gdoFilledRectangle(), gdoFilledTriangle(), gdoLine(), and gdoTextR().
getGdoPen()
static int getGdoPen (struct ADrawTag * ctx) [static]
Get the current GD pen index from an ADraw structure.
Definition at line 115 of file mscgen_gd_out.c.
{
    return getGdoCtx(ctx)->pen;
}
References getGdoCtx(), and GdoContextTag::pen.
Referenced by gdoArc(), gdoFilledCircle(), gdoFilledRectangle(), gdoFilledTriangle(), gdoLine(), and gdoTextR().
setStyle()
static void setStyle (struct ADrawTag * ctx) [static]
Set the dashed style.
Definition at line 163 of file mscgen_gd_out.c.
{
    GdoContext *context = getGdoCtx(ctx);
    int style[4];
    /* Create dash pattern */
    style[0] = style[1] = context->pen;
    style[2] = style[3] = getColourRef(context, ADRAW_COL_WHITE);
    gdImageSetStyle(context->img, style, 4);
}
References ADRAW_COL_WHITE, getColourRef(), getGdoCtx(), GdoContextTag::img, GdoContextTag::pen, and style.
Referenced by gdoDottedArc(), and gdoDottedLine().
swap()
static void swap (unsigned int * a, unsigned int * b) [static]
Swap a pair of values inplace.
Definition at line 88 of file mscgen_gd_out.c.
{
    unsigned int x;
    x = *a;
    *a = *b;
    *b = x;
}
References a, b, and x.
Referenced by gdoLine().