doxygen/build/doxygen/src/pagedef.cpp File Reference
#include `pagedef.h`
#include `groupdef.h`
#include `docparser.h`
#include `config.h`
#include `util.h`
#include `outputlist.h`
#include `doxygen.h`
#include `language.h`
#include `namespacedef.h`
#include `reflist.h`
#include `definitionimpl.h`
Classes
class PageDefImpl
Functions
PageDef * createPageDef (const QCString &f, int l, const QCString &n, const QCString &d, const QCString &t)
PageDef * toPageDef (Definition *d)
const PageDef * toPageDef (const Definition *d)
Function Documentation
createPageDef()
PageDef * createPageDef (const QCString & f, int l, const QCString & n, const QCString & d, const QCString & t)
Definition at line 76 of file pagedef.cpp.
{
  return new PageDefImpl(f,l,n,d,t);
}
References f, and n.
Referenced by addRelatedPage(), buildExampleList(), findMainPage(), and generateOutputViaTemplate().
toPageDef() [1/2]
const PageDef * toPageDef (const Definition * d)
Definition at line 421 of file pagedef.cpp.
{
  if (d==0) return 0;
  if (d && typeid(*d)==typeid(PageDefImpl))
  {
    return static_cast<const PageDef*>(d);
  }
  else
  {
    return 0;
  }
}
toPageDef() [2/2]
PageDef * toPageDef (Definition * d)
Definition at line 408 of file pagedef.cpp.
{
  if (d==0) return 0;
  if (d && typeid(*d)==typeid(PageDefImpl))
  {
    return static_cast<PageDef*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by PageDefImpl::addInnerCompound(), NestingNodeContext::Private::addPages(), NestingNodeContext::Private::createPage(), DefinitionImpl::navigationPathAsString(), DefinitionImpl::pathFragment(), searchName(), SearchIndex::setCurrentDoc(), NavPathElemContext::Private::text(), and validatingParseDoc().