doxygen/build/doxygen/examples/structcmd.h File Reference
A Documented file.
Macros
#define MAX(a, b) (((a)>(b))?(a):(b))
A macro that returns the maximum of a and b.
Typedefs
typedef unsigned int UINT32
A type definition for a .
Functions
int open (const char *, int)
Opens a file descriptor.
int close (int)
Closes the file descriptor fd.
size_t write (int, const char *, size_t)
Writes count bytes from buf to the filedescriptor fd.
int read (int, char *, size_t)
Read bytes from a file descriptor.
Variables
int errno
Contains the last error code.
Detailed Description
A Documented file.
Details.
Definition in file structcmd.h.
Macro Definition Documentation
MAX
#define MAX(a, b) (((a)>(b))?(a):(b))
A macro that returns the maximum of a and b.
Details.
Definition at line 51 of file structcmd.h.
Typedef Documentation
UINT32
typedef unsigned int UINT32
A type definition for a .
Details.
Definition at line 52 of file structcmd.h.
Function Documentation
close()
int close (int fd)
Closes the file descriptor fd.
Parameters
fd The descriptor to close.
Referenced by ghc::filesystem::copy_file(), and writeExceptionListImpl().
open()
int open (const char * pathname, int flags)
Opens a file descriptor.
Parameters
pathname The name of the descriptor.
flags Opening flags.
Referenced by res2cc_cmd.File::__init__(), ghc::filesystem::copy_file(), generateDS_post::main(), post_lex::main(), pre_lex::main(), res2cc_cmd::main(), scan_states::main(), vhdl_adj::main(), ghc::filesystem::basic_filebuf< charT, traits >::open(), ghc::filesystem::basic_ifstream< charT, traits >::open(), ghc::filesystem::basic_fstream< charT, traits >::open(), ghc::filesystem::basic_ofstream< charT, traits >::open(), res2cc_cmd.LumaFile::writeDirEntry(), runtests::xopen(), and translator::xopen().
read()
int read (int fd, char * buf, size_t count)
Read bytes from a file descriptor.
Parameters
fd The descriptor to read from.
buf The buffer to read into.
count The number of bytes to read.
Referenced by ghc::filesystem::copy_file(), runtests.Tester::perform_test(), res2cc_cmd.VerbatimFile::writeContents(), res2cc_cmd.CSSFile::writeContents(), res2cc_cmd.SVGFile::writeContents(), and runtests::xpopen().
write()
size_t write (int fd, const char * buf, size_t count)
Writes count bytes from buf to the filedescriptor fd.
Parameters
fd The descriptor to write to.
buf The data buffer to write.
count The number of bytes to write.
Referenced by ghc::filesystem::copy_file().
Variable Documentation
errno
int errno
Contains the last error code.
Warning
Not thread safe!
Definition at line 53 of file structcmd.h.
Referenced by adjustConfiguration(), configStringRecode(), ghc::filesystem::equivalent(), GdoInit(), ghc::filesystem::directory_iterator::impl::impl(), ghc::filesystem::directory_iterator::impl::increment(), ghc::filesystem::detail::make_system_error(), mscgen_generate(), PsInit(), ghc::filesystem::remove(), SvgInit(), Portable::system(), ghc::filesystem::detail::systemErrorText(), and transcodeCharacterBuffer().