doxygen/build/doxygen/src/dirdef.cpp File Reference
#include <algorithm>
#include `dirdef.h`
#include `md5.h`
#include `filename.h`
#include `doxygen.h`
#include `util.h`
#include `outputlist.h`
#include `language.h`
#include `message.h`
#include `dot.h`
#include `dotdirdeps.h`
#include `layout.h`
#include `config.h`
#include `docparser.h`
#include `definitionimpl.h`
#include `filedef.h`
Classes
class DirDefImpl
Functions
DirDef * createDirDef (const QCString &path)
static QCString encodeDirName (const QCString &anchor)
static void writePartialDirPath (OutputList &ol, const DirDef *root, const DirDef *target)
static void writePartialFilePath (OutputList &ol, const DirDef *root, const FileDef *fd)
static void computeCommonDirPrefix ()
void buildDirectories ()
void computeDirDependencies ()
void generateDirDocs (OutputList &ol)
bool compareDirDefs (const DirDef *item1, const DirDef *item2)
DirDef * toDirDef (Definition *d)
const DirDef * toDirDef (const Definition *d)
Function Documentation
buildDirectories()
void buildDirectories ()
Definition at line 1015 of file dirdef.cpp.
{
  // for each input file
  for (const auto &fn : *Doxygen::inputNameLinkedMap)
  {
    for (const auto &fd : *fn)
    {
      if (fd->getReference().isEmpty())
      {
        DirDef *dir;
        if ((dir=Doxygen::dirLinkedMap->find(fd->getPath()))==0) // new directory
        {
          dir = DirDefImpl::mergeDirectoryInTree(fd->getPath());
        }
        if (dir && !fd->isDocumentationFile()) dir->addFile(fd.get());
      }
      else
      {
        // do something for file imported via tag files.
      }
    }
  }
  // compute relations between directories => introduce container dirs.
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    QCString name = dir->name();
    int i=name.findRev('/',name.length()-2);
    if (i>0)
    {
      DirDef *parent = Doxygen::dirLinkedMap->find(name.left(i+1));
      //if (parent==0) parent=root;
      if (parent)
      {
        parent->addSubDir(dir.get());
        //printf("DirDefImpl::addSubdir(): Adding subdir\n%s to\n%s\n",
        // qPrint(dir->displayName()), qPrint(parent->displayName()));
      }
    }
  }
  // sort the directory contents
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    dir->sort();
  }
  // short the directories themselves
  std::sort(Doxygen::dirLinkedMap->begin(),
            Doxygen::dirLinkedMap->end(),
            [](const auto &d1,const auto &d2)
            {
              QCString s1 = d1->shortName(), s2 = d2->shortName();
              int i = qstricmp(s1,s2);
              if (i==0) // if sort name are equal, sort on full path
              {
                QCString n1 = d1->name(), n2 = d2->name();
                int n = qstricmp(n1,n2);
                return n < 0;
              }
              return i < 0;
            });
  // set the directory count identifier
  int dirCount=0;
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    dir->setDirCount(dirCount++);
  }
  computeCommonDirPrefix();
}
References DirDef::addFile(), ghc::filesystem::begin(), computeCommonDirPrefix(), Doxygen::dirLinkedMap, ghc::filesystem::end(), LinkedMap< T, Hash, KeyEqual, Map >::find(), Doxygen::inputNameLinkedMap, DirDefImpl::mergeDirectoryInTree(), n, setup::name, parent(), and qstricmp().
Referenced by parseInput().
compareDirDefs()
bool compareDirDefs (const DirDef * item1, const DirDef * item2)
Definition at line 1125 of file dirdef.cpp.
{
  return qstricmp(item1->shortName(),item2->shortName()) < 0;
}
References qstricmp(), and DirDef::shortName().
Referenced by DirDefImpl::sort(), and GroupDefImpl::sortMemberLists().
computeCommonDirPrefix()
static void computeCommonDirPrefix () [static]
In order to create stable, but unique directory names, we compute the common part of the path shared by all directories.
Definition at line 940 of file dirdef.cpp.
{
  QCString path;
  auto it = Doxygen::dirLinkedMap->begin();
  if (!Doxygen::dirLinkedMap->empty()) // we have at least one dir
  {
    // start will full path of first dir
    path=(*it)->name();
    int i=path.findRev('/',path.length()-2);
    path=path.left(i+1);
    bool done=FALSE;
    if (i==-1)
    {
      path="";
    }
    else
    {
      while (!done)
      {
        uint l = path.length();
        size_t count=0;
        for (const auto &dir : *Doxygen::dirLinkedMap)
        {
          QCString dirName = dir->name();
          if (dirName.length()>path.length())
          {
            if (dirName.left(l)!=path) // dirName does not start with path
            {
              i=path.findRev('/',l-2);
              if (i==-1) // no unique prefix -> stop
              {
                path="";
                done=TRUE;
              }
              else // restart with shorter path
              {
                path=path.left(i+1);
                break;
              }
            }
          }
          else // dir is shorter than path -> take path of dir as new start
          {
            path=dir->name();
            l=path.length();
            i=path.findRev('/',l-2);
            if (i==-1) // no unique prefix -> stop
            {
              path="";
              done=TRUE;
            }
            else // restart with shorter path
            {
              path=path.left(i+1);
            }
            break;
          }
          count++;
        }
        if (count==Doxygen::dirLinkedMap->size())
          // path matches for all directories -> found the common prefix
        {
          done=TRUE;
        }
      }
    }
  }
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    QCString diskName = dir->name().right(dir->name().length()-path.length());
    dir->setDiskName(diskName);
    //printf("set disk name: %s -> %s\n",qPrint(dir->name()),qPrint(diskName));
  }
}
References LinkedMap< T, Hash, KeyEqual, Map >::begin(), Doxygen::dirLinkedMap, FALSE, QCString::findRev(), QCString::left(), QCString::length(), QCString::right(), size, and TRUE.
Referenced by buildDirectories().
computeDirDependencies()
void computeDirDependencies ()
Definition at line 1088 of file dirdef.cpp.
{
  // compute nesting level for each directory
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    dir->setLevel();
  }
  // compute uses dependencies between directories
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    //printf("computeDependencies for %s: #dirs=%d\n",qPrint(dir->name()),Doxygen::directories.count());
    dir->computeDependencies();
  }
}
References Doxygen::dirLinkedMap.
Referenced by parseInput().
createDirDef()
DirDef * createDirDef (const QCString & path)
Definition at line 102 of file dirdef.cpp.
{
  return new DirDefImpl(path);
}
Referenced by DirDefImpl::createNewDir().
encodeDirName()
static QCString encodeDirName (const QCString & anchor) [static]
Definition at line 181 of file dirdef.cpp.
{
  // convert to md5 hash
  uchar md5_sig[16];
  char sigStr[33];
  MD5Buffer(anchor.data(),anchor.length(),md5_sig);
  MD5SigToString(md5_sig,sigStr);
  return sigStr;
  // old algorithm
// QCString result;
// int l = anchor.length(),i;
// for (i=0;i<l;i++)
// {
// char c = anchor.at(i);
// if ((c>='a' && c<='z') || (c>='A' && c<='Z') || (c>='0' && c<='9'))
// {
// result+=c;
// }
// else
// {
// static char hexStr[]="0123456789ABCDEF";
// char escChar[]={ '_', 0, 0, 0 };
// escChar[1]=hexStr[c>>4];
// escChar[2]=hexStr[c&0xf];
// result+=escChar;
// }
// }
// return result;
}
References QCString::data(), QCString::length(), MD5Buffer(), and MD5SigToString().
Referenced by DirDefImpl::getOutputFileBase().
generateDirDocs()
void generateDirDocs (OutputList & ol)
Definition at line 1104 of file dirdef.cpp.
{
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    ol.pushGeneratorState();
    if (!dir->hasDocumentation())
    {
      ol.disableAllBut(OutputGenerator::Html);
    }
    dir->writeDocumentation(ol);
    ol.popGeneratorState();
  }
  if (Config_getBool(DIRECTORY_GRAPH))
  {
    for (const auto &dr : Doxygen::dirRelations)
    {
      dr->writeDocumentation(ol);
    }
  }
}
References Config_getBool, Doxygen::dirLinkedMap, Doxygen::dirRelations, OutputList::disableAllBut(), OutputGenerator::Html, OutputList::popGeneratorState(), and OutputList::pushGeneratorState().
Referenced by generateOutput().
toDirDef() [1/2]
const DirDef * toDirDef (const Definition * d)
Definition at line 1145 of file dirdef.cpp.
{
  if (d==0) return 0;
  if (d && typeid(*d)==typeid(DirDefImpl))
  {
    return static_cast<const DirDef*>(d);
  }
  else
  {
    return 0;
  }
}
toDirDef() [2/2]
DirDef * toDirDef (Definition * d)
Definition at line 1132 of file dirdef.cpp.
{
  if (d==0) return 0;
  if (d && typeid(*d)==typeid(DirDefImpl))
  {
    return static_cast<DirDef*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by NestingNodeContext::Private::addDirFiles(), and NestingNodeContext::Private::createDir().
writePartialDirPath()
static void writePartialDirPath (OutputList & ol, const DirDef * root, const DirDef * target) [static]
Definition at line 853 of file dirdef.cpp.
{
  if (target->parent()!=root)
  {
    writePartialDirPath(ol,root,target->parent());
    ol.writeString("&#160;/&#160;");
  }
  ol.writeObjectLink(target->getReference(),target->getOutputFileBase(),QCString(),target->shortName());
}
References DirDef::getOutputFileBase(), Definition::getReference(), DirDef::parent(), DirDef::shortName(), OutputList::writeObjectLink(), writePartialDirPath(), and OutputList::writeString().
Referenced by writePartialDirPath(), and writePartialFilePath().
writePartialFilePath()
static void writePartialFilePath (OutputList & ol, const DirDef * root, const FileDef * fd) [static]
Definition at line 863 of file dirdef.cpp.
{
  if (fd->getDirDef() && fd->getDirDef()!=root)
  {
    writePartialDirPath(ol,root,fd->getDirDef());
    ol.writeString("&#160;/&#160;");
  }
  if (fd->isLinkable())
  {
    ol.writeObjectLink(fd->getReference(),fd->getOutputFileBase(),QCString(),fd->name());
  }
  else
  {
    ol.startBold();
    ol.docify(fd->name());
    ol.endBold();
  }
}
References OutputList::docify(), OutputList::endBold(), FileDef::getDirDef(), FileDef::getOutputFileBase(), Definition::getReference(), FileDef::isLinkable(), FileDef::name(), OutputList::startBold(), OutputList::writeObjectLink(), writePartialDirPath(), and OutputList::writeString().
Referenced by DirRelation::writeDocumentation().