doxygen/build/doxygen/src/filedef.cpp File Reference
#include <unordered_set>
#include `memberlist.h`
#include `classlist.h`
#include `filedef.h`
#include `doxygen.h`
#include `memberdef.h`
#include `classdef.h`
#include `namespacedef.h`
#include `util.h`
#include `language.h`
#include `outputlist.h`
#include `dot.h`
#include `dotincldepgraph.h`
#include `message.h`
#include `docparser.h`
#include `searchindex.h`
#include `htags.h`
#include `parserintf.h`
#include `portable.h`
#include `vhdldocgen.h`
#include `debug.h`
#include `layout.h`
#include `entry.h`
#include `groupdef.h`
#include `filename.h`
#include `membergroup.h`
#include `dirdef.h`
#include `config.h`
#include `clangparser.h`
#include `settings.h`
#include `definitionimpl.h`
#include `conceptdef.h`
Classes
class FileDefImpl
class DevNullCodeDocInterface
Typedefs
using DefinitionLineMap = std::unordered_map< int, const Definition * >
using MemberDefLineMap = std::unordered_map< int, const MemberDef * >
using IncludeInfoMap = std::unordered_map< std::string, const IncludeInfo * >
Functions
FileDef * createFileDef (const QCString &p, const QCString &n, const QCString &ref, const QCString &dn)
static void getAllIncludeFilesRecursively (StringUnorderedSet &filesVisited, const FileDef *fd, StringVector &incFiles)
bool compareFileDefs (const FileDef *fd1, const FileDef *fd2)
FileDef * toFileDef (Definition *d)
const FileDef * toFileDef (const Definition *d)
Typedef Documentation
DefinitionLineMap
using DefinitionLineMap = std::unordered_map<int,const Definition *>
Definition at line 54 of file filedef.cpp.
IncludeInfoMap
using IncludeInfoMap = std::unordered_map<std::string, const IncludeInfo *>
Definition at line 56 of file filedef.cpp.
MemberDefLineMap
using MemberDefLineMap = std::unordered_map<int,const MemberDef *>
Definition at line 55 of file filedef.cpp.
Function Documentation
compareFileDefs()
bool compareFileDefs (const FileDef * fd1, const FileDef * fd2)
Definition at line 1750 of file filedef.cpp.
{
  return qstricmp(fd1->name(),fd2->name()) < 0;
}
References FileDef::name(), and qstricmp().
Referenced by DirDefImpl::sort(), and writeFileIndex().
createFileDef()
FileDef * createFileDef (const QCString & p, const QCString & n, const QCString & ref, const QCString & dn)
Definition at line 192 of file filedef.cpp.
{
  return new FileDefImpl(p,n,ref,dn);
}
References n, and p.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), CCodeParser::parseCode(), FortranCodeParser::parseCode(), PythonCodeParser::parseCode(), VHDLCodeParser::parseCode(), LexCodeParser::parseCode(), SQLCodeParser::parseCode(), XMLCodeParser::parseCode(), readDir(), readFileOrDirectory(), and writeGraphInfo().
getAllIncludeFilesRecursively()
static void getAllIncludeFilesRecursively (StringUnorderedSet & filesVisited, const FileDef * fd, StringVector & incFiles) [static]
Definition at line 1680 of file filedef.cpp.
{
  for (const auto &ii : fd->includeFileList())
  {
    if (ii.fileDef && !ii.fileDef->isReference() &&
        filesVisited.find(ii.fileDef->absFilePath().str())==filesVisited.end())
    {
      //printf("FileDefImpl::addIncludeDependency(%s)\n",qPrint(ii->fileDef->absFilePath()));
      incFiles.push_back(ii.fileDef->absFilePath().str());
      filesVisited.insert(ii.fileDef->absFilePath().str());
      getAllIncludeFilesRecursively(filesVisited,ii.fileDef,incFiles);
    }
  }
}
References getAllIncludeFilesRecursively(), and FileDef::includeFileList().
Referenced by getAllIncludeFilesRecursively().
toFileDef() [1/2]
const FileDef * toFileDef (const Definition * d)
Definition at line 1770 of file filedef.cpp.
{
  if (d==0) return 0;
  if (d && typeid(*d)==typeid(FileDefImpl))
  {
    return static_cast<const FileDef*>(d);
  }
  else
  {
    return 0;
  }
}
toFileDef() [2/2]
FileDef * toFileDef (Definition * d)
Definition at line 1757 of file filedef.cpp.
{
  if (d==0) return 0;
  if (d && typeid(*d)==typeid(FileDefImpl))
  {
    return static_cast<FileDef*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by DocSets::addIndexItem(), NestingNodeContext::Private::addMembers(), NestingNodeContext::Private::createFile(), DefinitionContext< T >::createNavigationPath(), DocLink::DocLink(), DocRef::DocRef(), DefinitionContext< T >::fillPath(), SymbolResolver::Private::followPath(), generateJSTree(), FTVHelp::Private::generateTree(), DocParser::handleLinkedWord(), NamespaceDefImpl::insertMember(), MemberDefImpl::moveTo(), DefinitionImpl::navigationPathAsString(), node2URL(), SearchIndex::setCurrentDoc(), and SearchIndexExternal::setCurrentDoc().