doxygen/build/doxygen/src/docbookvisitor.cpp File Reference
#include <fstream>
#include `docbookvisitor.h`
#include `docparser.h`
#include `language.h`
#include `doxygen.h`
#include `outputgen.h`
#include `docbookgen.h`
#include `dot.h`
#include `message.h`
#include `util.h`
#include `parserintf.h`
#include `filename.h`
#include `config.h`
#include `filedef.h`
#include `msc.h`
#include `dia.h`
#include `htmlentity.h`
#include `emoji.h`
#include `plantuml.h`
#include `growbuf.h`
#include `fileinfo.h`
Macros
#define DB_VIS_C
#define DB_VIS_C1(x)
#define DB_VIS_C2(y)
#define DB_VIS_C2a(x, y)
Functions
static QCString filterId (const QCString &s)
static bool supportedHtmlAttribute (const QCString &name)
Macro Definition Documentation
DB_VIS_C
#define DB_VIS_C
Definition at line 45 of file docbookvisitor.cpp.
DB_VIS_C1
#define DB_VIS_C1(x)
Definition at line 46 of file docbookvisitor.cpp.
DB_VIS_C2
#define DB_VIS_C2(y)
Definition at line 47 of file docbookvisitor.cpp.
DB_VIS_C2a
#define DB_VIS_C2a(x, y)
Definition at line 48 of file docbookvisitor.cpp.
Function Documentation
filterId()
static QCString filterId (const QCString & s) [static]
Definition at line 51 of file docbookvisitor.cpp.
{
  if (s.isEmpty()) return s;
  GrowBuf growBuf;
  growBuf.clear();
  const char *p=s.data();
  char c;
  while ((c=*p++))
  {
    switch (c)
    {
      case ':': growBuf.addStr("_1"); break;
      default: growBuf.addChar(c); break;
    }
  }
  growBuf.addChar(0);
  return growBuf.get();
}
References GrowBuf::addChar(), GrowBuf::addStr(), c, GrowBuf::clear(), gdFont::data, GrowBuf::get(), p, and s.
Referenced by DocbookDocVisitor::operator()().
supportedHtmlAttribute()
static bool supportedHtmlAttribute (const QCString & name) [static]
Definition at line 70 of file docbookvisitor.cpp.
{
  return (name=="align" ||
          name=="bgcolor" ||
          name=="border" ||
          name=="cellpadding" ||
          name=="cellspacing" ||
          name=="class" ||
          name=="frame" ||
          name=="label" ||
          name=="style" ||
          name=="width" ||
          name=="tabstyle" ||
          name=="title");
}
References setup::name.
Referenced by DocbookDocVisitor::operator()().