doxygen/build/doxygen/src/docparser_p.h File Reference
Private header shared between docparser.cpp and docnode.cpp.
#include <cassert>
#include <stack>
#include <iterator>
#include <vector>
#include <deque>
#include `containers.h`
#include `docparser.h`
#include `docnode.h`
#include `doctokenizer.h`
#include `searchindex.h`
Classes
class IterableStack< T, Container >
struct DocParserContext
class DocParser
class AutoNodeStack
Typedefs
using DefinitionStack = std::vector< const Definition * >
using DocNodeStack = std::stack< DocNodeVariant * >
using DocStyleChangeStack = IterableStack< const DocNodeVariant * >
Functions
bool isPreformatted (const DocNodeVariant *n)
bool insidePRE (const DocNodeVariant *n)
bool insideLI (const DocNodeVariant *n)
bool insideUL (const DocNodeVariant *n)
bool insideOL (const DocNodeVariant *n)
bool insideTable (const DocNodeVariant *n)
bool insideDetails (const DocNodeVariant *n)
Detailed Description
Private header shared between docparser.cpp and docnode.cpp.
Definition in file docparser_p.h.
Typedef Documentation
DefinitionStack
using DefinitionStack = std::vector<const Definition *>
Definition at line 35 of file docparser_p.h.
DocNodeStack
using DocNodeStack = std::stack<DocNodeVariant *>
Definition at line 36 of file docparser_p.h.
DocStyleChangeStack
using DocStyleChangeStack = IterableStack<const DocNodeVariant *>
Definition at line 52 of file docparser_p.h.
Function Documentation
insideDetails()
bool insideDetails (const DocNodeVariant * n) [inline]
Definition at line 239 of file docparser_p.h.
{
  while (n)
  {
    if (std::holds_alternative<DocHtmlDetails>(*n)) return TRUE;
    n=parent(n);
  }
  return FALSE;
}
References FALSE, n, parent(), and TRUE.
Referenced by DocPara::handleHtmlStartTag().
insideLI()
bool insideLI (const DocNodeVariant * n) [inline]
Returns TRUE iff node n is a child of a html list item node
Definition at line 181 of file docparser_p.h.
{
  while (n)
  {
    if (std::holds_alternative<DocHtmlListItem>(*n)) return TRUE;
    n=parent(n);
  }
  return FALSE;
}
References FALSE, n, parent(), and TRUE.
Referenced by DocPara::handleHtmlEndTag(), and DocParser::handleStyleArgument().
insideOL()
bool insideOL (const DocNodeVariant * n) [inline]
Returns TRUE iff node n is a child of a ordered html list node
Definition at line 211 of file docparser_p.h.
{
  while (n)
  {
    if (std::holds_alternative<DocHtmlList>(*n) &&
        std::get<DocHtmlList>(*n).type()==DocHtmlList::Ordered)
    {
      return TRUE;
    }
    n=parent(n);
  }
  return FALSE;
}
References FALSE, n, DocHtmlList::Ordered, parent(), and TRUE.
Referenced by DocPara::handleHtmlEndTag(), and DocPara::handleHtmlStartTag().
insidePRE()
bool insidePRE (const DocNodeVariant * n) [inline]
Returns TRUE iff node n is a child of a preformatted node
Definition at line 170 of file docparser_p.h.
{
  while (n)
  {
    if (isPreformatted(n)) return TRUE;
    n=parent(n);
  }
  return FALSE;
}
References FALSE, isPreformatted(), n, parent(), and TRUE.
Referenced by DocParser::defaultHandleToken(), and DocPara::parse().
insideTable()
bool insideTable (const DocNodeVariant * n) [inline]
Definition at line 227 of file docparser_p.h.
{
  while (n)
  {
    if (std::holds_alternative<DocHtmlTable>(*n)) return TRUE;
    n=parent(n);
  }
  return FALSE;
}
References FALSE, n, parent(), and TRUE.
Referenced by filterLatexString(), and DocPara::handleHtmlStartTag().
insideUL()
bool insideUL (const DocNodeVariant * n) [inline]
Returns TRUE iff node n is a child of a unordered html list node
Definition at line 194 of file docparser_p.h.
{
  while (n)
  {
    if (std::holds_alternative<DocHtmlList>(*n) &&
        std::get<DocHtmlList>(*n).type()==DocHtmlList::Unordered)
    {
      return TRUE;
    }
    n=parent(n);
  }
  return FALSE;
}
References FALSE, n, parent(), TRUE, and DocHtmlList::Unordered.
Referenced by DocPara::handleHtmlEndTag(), and DocPara::handleHtmlStartTag().
isPreformatted()
bool isPreformatted (const DocNodeVariant * n) [inline]
Definition at line 164 of file docparser_p.h.
{
  return std::visit([](auto &&x)->decltype(auto) { return x.isPreformatted(); }, *n);
}
References n, and x.
Referenced by insidePRE().