doxygen/build/doxygen/src/portable.h File Reference
Portable versions of functions that are platform dependent.
#include <stdio.h>
#include <sys/types.h>
#include <stdint.h>
#include `qcstring.h`
Namespaces
namespace Portable
Typedefs
typedef off_t portable_off_t
Functions
int Portable::system (const QCString &command, const QCString &args, bool commandHasConsole=true)
unsigned int Portable::pid ()
QCString Portable::getenv (const QCString &variable)
void Portable::setenv (const QCString &variable, const QCString &value)
void Portable::unsetenv (const QCString &variable)
portable_off_t Portable::fseek (FILE *f, portable_off_t offset, int whence)
portable_off_t Portable::ftell (FILE *f)
FILE * Portable::fopen (const QCString &fileName, const QCString &mode)
int Portable::fclose (FILE *f)
void Portable::unlink (const QCString &fileName)
QCString Portable::pathSeparator ()
QCString Portable::pathListSeparator ()
const char * Portable::ghostScriptCommand ()
const char * Portable::commandExtension ()
bool Portable::fileSystemIsCaseSensitive ()
FILE * Portable::popen (const QCString &name, const QCString &type)
int Portable::pclose (FILE *stream)
void Portable::sysTimerStart ()
void Portable::sysTimerStop ()
double Portable::getSysElapsedTime ()
void Portable::sleep (int ms)
bool Portable::isAbsolutePath (const QCString &fileName)
void Portable::correct_path ()
void Portable::setShortDir ()
const char * Portable::strnstr (const char *haystack, const char *needle, size_t haystack_len)
const char * Portable::devNull ()
bool Portable::checkForExecutable (const QCString &fileName)
size_t Portable::recodeUtf8StringToW (const QCString &inputStr, uint16_t **buf)
void * portable_iconv_open (const char *tocode, const char *fromcode)
size_t portable_iconv (void *cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft)
int portable_iconv_close (void *cd)
Detailed Description
Portable versions of functions that are platform dependent.
Definition in file portable.h.
Typedef Documentation
portable_off_t
typedef off_t portable_off_t
Definition at line 15 of file portable.h.
Function Documentation
portable_iconv()
size_t portable_iconv (void * cd, const char ** inbuf, size_t * inbytesleft, char ** outbuf, size_t * outbytesleft)
Definition at line 24 of file portable_c.c.
{
  return iconv((iconv_t)cd,(char**)inbuf,inbytesleft,outbuf,outbytesleft);
}
References iconv.
Referenced by configStringRecode(), encodeForOutput(), HtmlHelpRecoder::recode(), TemplateContextImpl::recode(), Portable::recodeUtf8StringToW(), transcodeCharacterBuffer(), and transcodeCharacterStringToUTF8().
portable_iconv_close()
int portable_iconv_close (void * cd)
Definition at line 30 of file portable_c.c.
{
  return iconv_close((iconv_t)cd);
}
References iconv_close.
Referenced by adjustConfiguration(), configStringRecode(), encodeForOutput(), HtmlHelpRecoder::finalize(), Portable::recodeUtf8StringToW(), TemplateContextImpl::setEncoding(), transcodeCharacterBuffer(), and transcodeCharacterStringToUTF8().
portable_iconv_open()
void * portable_iconv_open (const char * tocode, const char * fromcode)
Definition at line 19 of file portable_c.c.
{
  return iconv_open(tocode,fromcode);
}
References iconv_open.
Referenced by adjustConfiguration(), configStringRecode(), encodeForOutput(), HtmlHelpRecoder::initialize(), Portable::recodeUtf8StringToW(), TemplateContextImpl::setEncoding(), transcodeCharacterBuffer(), and transcodeCharacterStringToUTF8().