doxygen/build/doxygen/libmscgen/gdhelpers.c File Reference
#include `gd.h`
#include `gdhelpers.h`
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <ctype.h>
Macros
#define SEP_TEST (separators[*((unsigned char *) s)])
Functions
char * gd_strtok_r (char *s, char *sep, char **state)
void * gdCalloc (size_t nmemb, size_t size)
void * gdMalloc (size_t size)
void * gdRealloc (void *ptr, size_t size)
void * gdReallocEx (void *ptr, size_t size)
BGD_DECLARE (void)
Macro Definition Documentation
SEP_TEST
#define SEP_TEST (separators[*((unsigned char *) s)])
Definition at line 15 of file gdhelpers.c.
Function Documentation
BGD_DECLARE()
BGD_DECLARE (void)
Definition at line 113 of file gdhelpers.c.
{
    free (ptr);
}
gd_strtok_r()
char * gd_strtok_r (char * s, char * sep, char ** state)
Definition at line 18 of file gdhelpers.c.
{
    char separators[256];
    char *result = 0;
    memset (separators, 0, sizeof (separators));
    while (*sep) {
        separators[*((unsigned char *) sep)] = 1;
        sep++;
    }
    if (!s) {
        /* Pick up where we left off */
        s = *state;
    }
    /* 1. EOS */
    if (!(*s)) {
        *state = s;
        return 0;
    }
    /* 2. Leading separators, if any */
    if (SEP_TEST) {
        do {
            s++;
        } while (SEP_TEST);
        /* 2a. EOS after separators only */
        if (!(*s)) {
            *state = s;
            return 0;
        }
    }
    /* 3. A token */
    result = s;
    do {
        /* 3a. Token at end of string */
        if (!(*s)) {
            *state = s;
            return result;
        }
        s++;
    } while (!SEP_TEST);
    /* 4. Terminate token and skip trailing separators */
    *s = '\0';
    do {
        s++;
    } while (SEP_TEST);
    /* 5. Return token */
    *state = s;
    return result;
}
References s, and SEP_TEST.
gdCalloc()
void * gdCalloc (size_t nmemb, size_t size)
Definition at line 67 of file gdhelpers.c.
{
    return calloc (nmemb, size);
}
References size.
Referenced by _gdImageFillTiled(), and BGD_DECLARE().
gdMalloc()
void * gdMalloc (size_t size)
Definition at line 73 of file gdhelpers.c.
{
    return malloc (size);
}
References size.
Referenced by _gdImageFillTiled(), and BGD_DECLARE().
gdRealloc()
void * gdRealloc (void * ptr, size_t size)
Definition at line 79 of file gdhelpers.c.
{
    return realloc (ptr, size);
}
References size.
Referenced by gdReallocEx().
gdReallocEx()
void * gdReallocEx (void * ptr, size_t size)
Definition at line 85 of file gdhelpers.c.
{
    void *newPtr = gdRealloc (ptr, size);
    if (!newPtr && ptr)
        gdFree(ptr);
    return newPtr;
}
References gdRealloc(), and size.