doxygen/build/doxygen/addon/doxywizard/config.h File Reference
#include <QHash>
#include <QString>
#include `adapter.h`
Enumerations
enum { MAX_OPTION_LENGTH = 23
 }
Functions
bool parseConfig (const QString &fileName, const QHash< QString, Input * > &options)
void writeStringValue (QTextStream &t, TextCodecAdapter *codec, const QString &s)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAX_OPTION_LENGTH Maximum length of an option in the config file. Used for alignment purposes.
Definition at line 32 of file config.h.
{
  MAX_OPTION_LENGTH = 23
};
Function Documentation
parseConfig()
bool parseConfig (const QString & fileName, const QHash< QString, Input * > & options)
Definition at line 735 of file config_doxyw.l.
{
  yylineno = 1;
  config_open();
  QHashIterator<QString, Input*> i(options);
  g_file = fopen(fileName.toLocal8Bit(),"r");
  if (g_file==NULL) return false;
  // reset all values
  i.toFront();
  while (i.hasNext())
  {
    i.next();
    if (i.value())
    {
      i.value()->reset();
    }
  }
  // parse config file
  g_options = &options;
  g_yyFileName = fileName;
  g_includeStack.clear();
  g_includeDepth = 0;
  config_doxywYYrestart(config_doxywYYin);
  BEGIN(Start);
  config_doxywYYlex();
  upgradeConfig(options);
  // update the values in the UI
  i.toFront();
  while (i.hasNext())
  {
    i.next();
    if (i.value())
    {
      //printf("Updating: %s\n",qPrintable(i.key()));
      i.value()->update();
    }
    else
    {
      printf("Invalid option: %s\n",qPrintable(i.key()));
    }
  }
  fclose(g_file);
  config_finish();
  return true;
}
References config_finish(), config_open(), Portable::fclose(), Portable::fopen(), g_file, g_includeDepth, g_includeStack, g_options, g_yyFileName, and upgradeConfig().
writeStringValue()
void writeStringValue (QTextStream & t, TextCodecAdapter * codec, const QString & s)
Definition at line 788 of file config_doxyw.l.
{
  QChar c;
  bool needsEscaping=false;
  bool needsHashEscaping=false;
  // convert the string back to it original encoding
  codec->applyToStream(t);
  const QChar *p=s.data();
  if (!s.isEmpty() && !p->isNull())
  {
    if (*p != QChar::fromLatin1('"'))
    {
      while (!(c=*p++).isNull() && !needsEscaping)
      {
        needsEscaping = (c==QChar::fromLatin1(' ') ||
                     c==QChar::fromLatin1(',') ||
                     c==QChar::fromLatin1('\n') ||
                 c==QChar::fromLatin1('\t') ||
                 c==QChar::fromLatin1('"'));
      }
      p=s.data();
      while (!(c=*p++).isNull() && !needsHashEscaping)
      {
        needsHashEscaping = (c==QChar::fromLatin1('#'));
      }
    }
    if (needsHashEscaping || needsEscaping)
    {
      t << "\"";
    }
    if (needsEscaping)
    {
      p=s.data();
      while (!p->isNull())
      {
    if (*p ==QChar::fromLatin1(' ') &&
       *(p+1)==QChar::fromLatin1('\0')) break; // skip inserted space at the end
    if (*p ==QChar::fromLatin1('"')) t << "\\"; // escape quotes
    t << *p++;
      }
    }
    else
    {
      t << s;
    }
    if (needsHashEscaping || needsEscaping)
    {
      t << "\"";
    }
  }
}
References TextCodecAdapter::applyToStream(), c, gdFont::data, p, and s.