doxygen/build/doxygen/libmscgen/mscgen_safe.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include `mscgen_config.h`
#include `mscgen_safe.h`
Macros
#define FILE_NAME SAFE
Functions
static void checkNotNull (void *p, const char *message)
void * realloc_s (void *ptr, size_t size)
void * malloc_s (size_t size)
void * zalloc_s (size_t size)
char * strdup_s (const char *s)
const char * mscgen_getenv_s (const char *name)
Macro Definition Documentation
FILE_NAME
#define FILE_NAME SAFE
Definition at line 23 of file mscgen_safe.c.
Function Documentation
checkNotNull()
static void checkNotNull (void * p, const char * message) [static]
Definition at line 55 of file mscgen_safe.c.
{
    if(!p)
    {
        fprintf(stderr, "Fatal error: %s\n", message);
        exit(EXIT_FAILURE);
    }
}
References p.
Referenced by malloc_s(), realloc_s(), strdup_s(), and zalloc_s().
malloc_s()
void * malloc_s (size_t size)
Definition at line 77 of file mscgen_safe.c.
{
    void *r = malloc(size);
    checkNotNull(r, "malloc() failed");
    return r;
}
References checkNotNull(), r, and size.
Referenced by computeLabelLines(), MscAlloc(), MscAllocArc(), MscAllocAttrib(), MscAllocEntity(), MscAllocOpt(), mscgen_generate(), PsInit(), and SvgInit().
mscgen_getenv_s()
const char * mscgen_getenv_s (const char * name)
Definition at line 105 of file mscgen_safe.c.
{
    char *r = getenv(name);
    if(r == NULL) r = "";
    return r;
}
References Portable::getenv(), setup::name, and r.
Referenced by gdoTextHeight(), gdoTextR(), and gdoTextWidth().
realloc_s()
void * realloc_s (void * ptr, size_t size)
Definition at line 68 of file mscgen_safe.c.
{
    void *r = realloc(ptr, size);
    checkNotNull(r, "realloc() failed");
    return r;
}
References checkNotNull(), r, and size.
Referenced by computeLabelLines().
strdup_s()
char * strdup_s (const char * s)
Definition at line 96 of file mscgen_safe.c.
{
    char *r = strdup(s);
    checkNotNull(r, "strdup() failed");
    return r;
}
References checkNotNull(), r, and s.
Referenced by computeLabelLines(), and splitStringToWidth().
zalloc_s()
void * zalloc_s (size_t size)
Definition at line 86 of file mscgen_safe.c.
{
    void *r = malloc(size);
    checkNotNull(r, "malloc() failed");
    memset(r, 0, size);
    return r;
}
References checkNotNull(), r, and size.
Referenced by computeCanvasSize(), GdoInit(), MscLinkArc(), and MscLinkEntity().