doxygen/build/doxygen/addon/doxyparse/doxyparse.cpp File Reference
Code parse based on doxyapp by Dimitri van Heesch.
#include <stdlib.h>
#include <unistd.h>
#include `version.h`
#include `doxygen.h`
#include `outputgen.h`
#include `parserintf.h`
#include `classlist.h`
#include `config.h`
#include `filedef.h`
#include `util.h`
#include `filename.h`
#include `arguments.h`
#include `memberlist.h`
#include `types.h`
#include <string>
#include <cstdlib>
#include <sstream>
#include <map>
#include `qcstring.h`
#include `namespacedef.h`
#include `portable.h`
#include `dir.h`
Classes
class Doxyparse
Functions
static void findXRefSymbols (FileDef *fd)
static bool ignoreStaticExternalCall (const MemberDef *context, const MemberDef *md)
static void startYamlDocument ()
static void printFile (std::string file)
static void printModule (std::string module)
static void printClassInformation (std::string information)
static void printInherits ()
static void printInheritance (std::string base_class)
static void printDefines ()
static void printDefinition (std::string type, std::string signature, int line)
static void printProtection (std::string protection)
static void printPrototypeYes ()
static void printNumberOfLines (int lines)
static void printNumberOfArguments (size_t arguments)
static void printUses ()
static void printReferenceTo (std::string type, std::string signature, std::string defined_in)
static void printNumberOfConditionalPaths (const MemberDef *md)
static int isPartOfCStruct (const MemberDef *md)
std::string sanitizeString (std::string data)
std::string argumentData (const Argument &argument)
std::string functionSignature (const MemberDef *md)
static void referenceTo (const MemberDef *md)
void protectionInformation (Protection protection)
void cModule (const ClassDef *cd)
static bool checkOverrideArg (const ArgumentList &argList, const MemberDef *md)
void functionInformation (const MemberDef *md)
void prototypeInformation (const MemberDef *md)
static void lookupSymbol (const Definition *d)
void listMembers (const MemberList *ml)
void listAllMembers (const ClassDef *cd)
static void classInformation (const ClassDef *cd)
static bool checkLanguage (std::string &filename, std::string extension)
static void detectProgrammingLanguage (FileNameLinkedMap &fnli)
static void listSymbols ()
int main (int argc, char **argv)
Variables
static bool is_c_code = true
Detailed Description
Code parse based on doxyapp by Dimitri van Heesch.
Definition in file doxyparse.cpp.
Function Documentation
argumentData()
std::string argumentData (const Argument & argument)
Definition at line 188 of file doxyparse.cpp.
                                                 {
  std::string data = "";
  if (argument.type.size() > 1)
    data = sanitizeString(argument.type.data());
  else if (!argument.name.isEmpty())
    data = sanitizeString(argument.name.data());
  return data;
}
References data, QCString::data(), QCString::isEmpty(), Argument::name, sanitizeString(), QCString::size(), string, and Argument::type.
checkLanguage()
static bool checkLanguage (std::string & filename, std::string extension) [static]
Definition at line 367 of file doxyparse.cpp.
                                                                    {
  if (filename.find(extension, filename.size() - extension.size()) != std::string::npos) {
    return true;
  } else {
    return false;
  }
}
References filename.
Referenced by detectProgrammingLanguage().
checkOverrideArg()
static bool checkOverrideArg (const ArgumentList & argList, const MemberDef * md) [static]
Definition at line 268 of file doxyparse.cpp.
                                                                               {
  if(!md->isFunction() || argList.empty()){
    return false;
  }
  for (const Argument &argument : argList) {
    if(md->name() == argument.name) {
      return true;
    }
  }
  return false;
}
References ArgumentList::empty(), MemberDef::isFunction(), and Definition::name().
Referenced by functionInformation().
classInformation()
static void classInformation (const ClassDef * cd) [static]
Definition at line 348 of file doxyparse.cpp.
                                                 {
  if (is_c_code) {
    cModule(cd);
  } else {
    printModule(cd->name().data());
    if (!cd->baseClasses().empty()) {
      printInherits();
      for (const auto &bcd : cd->baseClasses()) {
        printInheritance(sanitizeString(bcd.classDef->name().data()));
      }
    }
    if(cd->isAbstract()) {
      printClassInformation("abstract class");
    }
    printDefines();
    listAllMembers(cd);
  }
}
References ClassDef::baseClasses(), cModule(), QCString::data(), is_c_code, ClassDef::isAbstract(), listAllMembers(), Definition::name(), printClassInformation(), printDefines(), printInheritance(), printInherits(), printModule(), and sanitizeString().
Referenced by listSymbols().
cModule()
void cModule (const ClassDef * cd)
Definition at line 252 of file doxyparse.cpp.
                                 {
  const MemberList* ml = cd->getMemberList(MemberListType_variableMembers);
  if (ml) {
    const FileDef *fd = cd->getFileDef();
    const MemberList *fd_ml = fd->getMemberList(MemberListType_allMembersList);
    if (!fd_ml || fd_ml->size() == 0) {
      printModule(fd->getOutputFileBase().data());
      printDefines();
    }
    for (const auto &md : *ml) {
      printDefinition("variable", cd->name().data() + std::string("::") + md->name().data(), md->getDefLine());
      protectionInformation(md->protection());
    }
  }
}
References QCString::data(), ClassDef::getFileDef(), ClassDef::getMemberList(), FileDef::getMemberList(), FileDef::getOutputFileBase(), MemberListType_allMembersList, MemberListType_variableMembers, Definition::name(), printDefines(), printDefinition(), printModule(), protectionInformation(), MemberVector::size(), and string.
detectProgrammingLanguage()
static void detectProgrammingLanguage (FileNameLinkedMap & fnli) [static]
Definition at line 377 of file doxyparse.cpp.
                                                               {
  for (const auto &fn : fnli) {
    std::string filename = fn->fileName().str();
    if (
        checkLanguage(filename, ".cc") ||
        checkLanguage(filename, ".cxx") ||
        checkLanguage(filename, ".cpp") ||
        checkLanguage(filename, ".java") ||
        checkLanguage(filename, ".py") ||
        checkLanguage(filename, ".pyw") ||
        checkLanguage(filename, ".cs")
       ) {
      is_c_code = false;
    }
  }
}
References checkLanguage(), filename, is_c_code, and string.
Referenced by listSymbols().
findXRefSymbols()
static void findXRefSymbols (FileDef * fd) [static]
Definition at line 88 of file doxyparse.cpp.
{
  // get the interface to a parser that matches the file extension
  auto intf=Doxygen::parserManager->getCodeParser(fd->getDefFileExtension());
  // get the programming language from the file name
  SrcLangExt lang = getLanguageFromFileName(fd->name());
  // reset the parsers state
  intf->resetCodeParserState();
  // create a new backend object
  Doxyparse *parse = new Doxyparse(fd);
  // parse the source code
  intf->parseCode(*parse, 0, fileToString(fd->absFilePath()), lang, FALSE, 0, fd);
  // dismiss the object.
  delete parse;
}
References FileDef::absFilePath(), FALSE, fileToString(), ParserManager::getCodeParser(), Definition::getDefFileExtension(), getLanguageFromFileName(), FileDef::name(), doxmlparser.compound::parse(), and Doxygen::parserManager.
Referenced by main().
functionInformation()
void functionInformation (const MemberDef * md)
Definition at line 282 of file doxyparse.cpp.
                                              {
  std::string temp = "";
  int size = md->getEndBodyLine() - md->getStartBodyLine() + 1;
  printNumberOfLines(size);
  const ArgumentList &argList = md->argumentList();
  if (!argList.empty())
  {
    temp = argumentData(argList.front());
// TODO: This is a workaround; better not include "void" in argList, in the first place.
    if (temp!="void")
    {
      printNumberOfArguments(argList.size());
    }
  }
  printNumberOfConditionalPaths(md);
  auto refList = md->getReferencesMembers();
  if (!refList.empty()) {
    printUses();
    for (const auto &rmd : refList) {
      if (rmd->definitionType() == Definition::TypeMember && !ignoreStaticExternalCall(md, rmd) && !checkOverrideArg(argList, rmd)) {
        referenceTo(rmd);
      }
    }
  }
}
References argumentData(), MemberDef::argumentList(), checkOverrideArg(), ArgumentList::empty(), ArgumentList::front(), Definition::getEndBodyLine(), Definition::getReferencesMembers(), Definition::getStartBodyLine(), ignoreStaticExternalCall(), printNumberOfArguments(), printNumberOfConditionalPaths(), printNumberOfLines(), printUses(), referenceTo(), size, ArgumentList::size(), string, and Definition::TypeMember.
functionSignature()
std::string functionSignature (const MemberDef * md)
Definition at line 197 of file doxyparse.cpp.
                                                 {
  std::string signature = sanitizeString(md->name().data());
  if(md->isFunction()){
    const ArgumentList &argList = md->argumentList();
    signature += "(";
    auto it = argList.begin();
    if(it!=argList.end()) {
      signature += argumentData(*it);
      for(++it; it!=argList.end(); ++it) {
        signature += std::string(",") + argumentData(*it);
      }
    }
    signature += ")";
  }
  return signature;
}
References argumentData(), MemberDef::argumentList(), ArgumentList::begin(), QCString::data(), ArgumentList::end(), MemberDef::isFunction(), Definition::name(), sanitizeString(), and string.
ignoreStaticExternalCall()
static bool ignoreStaticExternalCall (const MemberDef * context, const MemberDef * md) [static]
Definition at line 109 of file doxyparse.cpp.
                                                                                    {
  if (md->isStatic()) {
    if(md->getFileDef() && context->getFileDef()) {
      if(md->getFileDef()->getOutputFileBase() == context->getFileDef()->getOutputFileBase())
        // TODO ignore prefix of file
        return false;
      else
        return true;
    }
    else {
      return false;
    }
  }
  else {
    return false;
  }
}
References MemberDef::getFileDef(), FileDef::getOutputFileBase(), and MemberDef::isStatic().
Referenced by functionInformation().
isPartOfCStruct()
static int isPartOfCStruct (const MemberDef * md) [static]
Definition at line 177 of file doxyparse.cpp.
                                                 {
  return is_c_code && md->getClassDef() != NULL;
}
References MemberDef::getClassDef(), and is_c_code.
Referenced by referenceTo().
listAllMembers()
void listAllMembers (const ClassDef * cd)
Definition at line 339 of file doxyparse.cpp.
                                        {
  // methods
  listMembers(cd->getMemberList(MemberListType_functionMembers));
  // constructors
  listMembers(cd->getMemberList(MemberListType_constructors));
  // attributes
  listMembers(cd->getMemberList(MemberListType_variableMembers));
}
References ClassDef::getMemberList(), listMembers(), MemberListType_constructors, MemberListType_functionMembers, and MemberListType_variableMembers.
listMembers()
void listMembers (const MemberList * ml)
Definition at line 331 of file doxyparse.cpp.
                                       {
  if (ml) {
    for (const auto &md : *ml) {
      lookupSymbol((Definition*) md);
    }
  }
}
References lookupSymbol().
listSymbols()
static void listSymbols () [static]
Definition at line 394 of file doxyparse.cpp.
                          {
  detectProgrammingLanguage(*Doxygen::inputNameLinkedMap);
  // iterate over the input files
  for (const auto &fn : *Doxygen::inputNameLinkedMap) {
    for (const auto &fd : *fn) {
      printFile(fd->absFilePath().data());
      MemberList *ml = fd->getMemberList(MemberListType_allMembersList);
      if (ml && ml->size() > 0) {
        printModule(fd->getOutputFileBase().data());
        printDefines();
        listMembers(ml);
      }
      ClassDefSet visitedClasses;
      for (const auto &cd : fd->getClasses()) {
        if (visitedClasses.find(cd)==visitedClasses.end()) {
          classInformation(cd);
          visitedClasses.insert(cd);
        }
      }
    }
  }
  // TODO print external symbols referenced
}
References classInformation(), detectProgrammingLanguage(), Doxygen::inputNameLinkedMap, listMembers(), MemberListType_allMembersList, printDefines(), printFile(), printModule(), and MemberVector::size().
Referenced by main().
lookupSymbol()
static void lookupSymbol (const Definition * d) [static]
Definition at line 315 of file doxyparse.cpp.
                                              {
  if (d->definitionType() == Definition::TypeMember) {
    const MemberDef *md = dynamic_cast<const MemberDef*>(d);
    std::string type = md->memberTypeName().data();
    std::string signature = functionSignature(md);
    printDefinition(type, signature, md->getDefLine());
    protectionInformation(md->protection());
    if (md->isFunction() && md->isPrototype()) {
      prototypeInformation(md);
    }
    else if (md->isFunction()) {
      functionInformation(md);
    }
  }
}
References QCString::data(), Definition::definitionType(), functionInformation(), functionSignature(), Definition::getDefLine(), MemberDef::isFunction(), MemberDef::isPrototype(), MemberDef::memberTypeName(), printDefinition(), MemberDef::protection(), protectionInformation(), prototypeInformation(), string, and Definition::TypeMember.
Referenced by listMembers().
main()
int main (int argc, char ** argv)
Definition at line 420 of file doxyparse.cpp.
                               {
  int locArgc = argc;
  if (locArgc == 2)
  {
    if (!strcmp(argv[1],"--help"))
    {
      printf("Usage: %s [source_file | source_dir]\n",argv[0]);
      exit(0);
    }
    else if (!strcmp(argv[1],"--version"))
    {
      printf("%s version: %s\n",argv[0],getFullVersion());
      exit(0);
    }
  }
  if (locArgc!=2)
  {
    printf("Usage: %s [source_file | source_dir]\n",argv[0]);
    exit(1);
  }
  // initialize data structures
  initDoxygen();
  // check and finalize the configuration
  checkConfiguration();
  adjustConfiguration();
  // setup the non-default configuration options
  // we need a place to put intermediate files
  std::ostringstream tmpdir;
  unsigned int pid = Portable::pid();
  if (!Portable::getenv("TMP").isEmpty())
    tmpdir << Portable::getenv("TMP") << "/doxyparse-" << pid;
  else if (!Portable::getenv("TEMP").isEmpty())
    tmpdir << Portable::getenv("TEMP") << "/doxyparse-" << pid;
  else
    tmpdir << "doxyparse-" << pid;
  Config_updateString(OUTPUT_DIRECTORY,tmpdir.str().c_str());
  // enable HTML (fake) output to omit warning about missing output format
  Config_updateBool(GENERATE_HTML,TRUE);
  // disable latex output
  Config_updateBool(GENERATE_LATEX,FALSE);
  // be quiet
  Config_updateBool(QUIET,TRUE);
  // turn off warnings
  Config_updateBool(WARNINGS,FALSE);
  Config_updateBool(WARN_IF_UNDOCUMENTED,FALSE);
  Config_updateBool(WARN_IF_DOC_ERROR,FALSE);
  // Extract as much as possible
  Config_updateBool(EXTRACT_ALL,TRUE);
  Config_updateBool(EXTRACT_STATIC,TRUE);
  Config_updateBool(EXTRACT_PRIVATE,TRUE);
  Config_updateBool(EXTRACT_LOCAL_METHODS,TRUE);
  Config_updateBool(EXTRACT_PACKAGE,TRUE);
  // Extract source browse information, needed
  // to make doxygen gather the cross reference info
  Config_updateBool(SOURCE_BROWSER,TRUE);
  // find functions call between modules
  Config_updateBool(CALL_GRAPH,TRUE);
  // loop recursive over input files
  Config_updateBool(RECURSIVE,TRUE);
  // add file extensions
  Config_updateList(FILE_PATTERNS, { "*.cc", "*.cxx", "*.cpp", "*.java",
                                     "*.py", "*.pyw", "*.cs", "*.c", "*.h", "*.hh", "*.hpp"});
  // set the input
  StringVector inputList;
  for (int i = 1; i < argc; i++) {
    if (strcmp(argv[i], "-") == 0) {
      char filename[1024];
      while (1) {
        scanf("%s[^\n]", filename);
        if (feof(stdin)) {
          break;
        }
        inputList.push_back(filename);
      }
    } else {
      inputList.push_back(argv[i]);
    }
  }
  Config_updateList(INPUT,inputList);
  if (inputList.empty()) {
    exit(0);
  }
  // parse the files
  parseInput();
  // iterate over the input files
  for (const auto &fn : *Doxygen::inputNameLinkedMap) {
    for (const auto &fd : *fn) {
      // get the references (linked and unlinked) found in this file
      findXRefSymbols(fd.get());
    }
  }
  Dir thisDir;
  // remove temporary files
  if (!Doxygen::filterDBFileName.isEmpty()) thisDir.remove(Doxygen::filterDBFileName.str());
  // clean up after us
  thisDir.rmdir(Config_getString(OUTPUT_DIRECTORY).str());
  startYamlDocument();
  listSymbols();
  std::string cleanup_command = "rm -rf ";
  cleanup_command += tmpdir.str();
  system(cleanup_command.c_str());
  exit(0);
}
References adjustConfiguration(), checkConfiguration(), Config_getString, Config_updateBool, Config_updateList, Config_updateString, FALSE, filename, Doxygen::filterDBFileName, findXRefSymbols(), Portable::getenv(), getFullVersion(), initDoxygen(), Doxygen::inputNameLinkedMap, listSymbols(), parseInput(), Portable::pid(), Dir::remove(), Dir::rmdir(), startYamlDocument(), strcmp(), string, Portable::system(), and TRUE.
printClassInformation()
static void printClassInformation (std::string information) [static]
Definition at line 136 of file doxyparse.cpp.
                                                         {
  printf(" information: %s\n", information.c_str());
}
Referenced by classInformation().
printDefines()
static void printDefines () [static]
Definition at line 145 of file doxyparse.cpp.
                           {
  printf(" defines:\n");
}
Referenced by classInformation(), cModule(), and listSymbols().
printDefinition()
static void printDefinition (std::string type, std::string signature, int line) [static]
Definition at line 148 of file doxyparse.cpp.
                                                                           {
  printf(" - \"%s\":\n", signature.substr(0, 1022).c_str());
  printf(" type: %s\n", type.c_str());
  printf(" line: %d\n", line);
}
Referenced by cModule(), and lookupSymbol().
printFile()
static void printFile (std::string file) [static]
Definition at line 130 of file doxyparse.cpp.
                                      {
  printf("%s:\n", file.c_str());
}
References caseconvert::file.
Referenced by listSymbols().
printInheritance()
static void printInheritance (std::string base_class) [static]
Definition at line 142 of file doxyparse.cpp.
                                                   {
  printf(" - \"%s\"\n", base_class.c_str());
}
Referenced by classInformation().
printInherits()
static void printInherits () [static]
Definition at line 139 of file doxyparse.cpp.
                            {
  printf(" inherits:\n");
}
Referenced by classInformation().
printModule()
static void printModule (std::string module) [static]
Definition at line 133 of file doxyparse.cpp.
                                          {
  printf(" \"%s\":\n", unescapeCharsInString(module.c_str()).data());
}
References QCString::data(), and unescapeCharsInString().
Referenced by classInformation(), cModule(), and listSymbols().
printNumberOfArguments()
static void printNumberOfArguments (size_t arguments) [static]
Definition at line 162 of file doxyparse.cpp.
                                                     {
  printf(" parameters: %zu\n", arguments);
}
Referenced by functionInformation(), and prototypeInformation().
printNumberOfConditionalPaths()
static void printNumberOfConditionalPaths (const MemberDef * md) [static]
Definition at line 173 of file doxyparse.cpp.
                                                               {
  printf(" conditional_paths: %d\n", md->numberOfFlowKeyWords());
}
References MemberDef::numberOfFlowKeyWords().
Referenced by functionInformation().
printNumberOfLines()
static void printNumberOfLines (int lines) [static]
Definition at line 159 of file doxyparse.cpp.
                                          {
  printf(" lines_of_code: %d\n", lines);
}
Referenced by functionInformation().
printProtection()
static void printProtection (std::string protection) [static]
Definition at line 153 of file doxyparse.cpp.
                                                  {
  printf(" protection: %s\n", protection.c_str());
}
Referenced by protectionInformation().
printPrototypeYes()
static void printPrototypeYes () [static]
Definition at line 156 of file doxyparse.cpp.
                                {
  printf(" prototype: yes\n");
}
Referenced by prototypeInformation().
printReferenceTo()
static void printReferenceTo (std::string type, std::string signature, std::string defined_in) [static]
Definition at line 168 of file doxyparse.cpp.
                                                                                        {
  printf(" - \"%s\":\n", signature.substr(0, 1022).c_str());
  printf(" type: %s\n", type.c_str());
  printf(" defined_in: \"%s\"\n", unescapeCharsInString(defined_in.c_str()).data());
}
References QCString::data(), and unescapeCharsInString().
Referenced by referenceTo().
printUses()
static void printUses () [static]
Definition at line 165 of file doxyparse.cpp.
                        {
  printf(" uses:\n");
}
Referenced by functionInformation().
protectionInformation()
void protectionInformation (Protection protection)
Definition at line 237 of file doxyparse.cpp.
                                                  {
  if (protection == Public) {
    printProtection("public");
  }
  else if (protection == Protected) {
    printProtection("protected");
  }
  else if (protection == Private) {
    printProtection("private");
  }
  else if (protection == Package) {
    printProtection("package");
  }
}
References Package, printProtection(), Private, Protected, and Public.
prototypeInformation()
void prototypeInformation (const MemberDef * md)
Definition at line 309 of file doxyparse.cpp.
                                               {
  printPrototypeYes();
  const ArgumentList &argList = md->argumentList();
  printNumberOfArguments(argList.size());
}
References MemberDef::argumentList(), printNumberOfArguments(), printPrototypeYes(), and ArgumentList::size().
referenceTo()
static void referenceTo (const MemberDef * md) [static]
Definition at line 214 of file doxyparse.cpp.
                                             {
  std::string type = md->memberTypeName().data();
  std::string defined_in = "";
  std::string signature = "";
  if (isPartOfCStruct(md)) {
    signature = md->getClassDef()->name().data() + std::string("::") + functionSignature(md);
    defined_in = md->getClassDef()->getFileDef()->getOutputFileBase().data();
  }
  else {
    signature = functionSignature(md);
    if (md->getClassDef()) {
      defined_in = md->getClassDef()->name().data();
    }
    else if (md->getFileDef()) {
      defined_in = md->getFileDef()->getOutputFileBase().data();
    }
    else if (md->getNamespaceDef()) {
      defined_in = md->getNamespaceDef()->name().data();
    }
  }
  printReferenceTo(type, signature, defined_in);
}
References QCString::data(), functionSignature(), MemberDef::getClassDef(), ClassDef::getFileDef(), MemberDef::getFileDef(), MemberDef::getNamespaceDef(), FileDef::getOutputFileBase(), isPartOfCStruct(), MemberDef::memberTypeName(), Definition::name(), printReferenceTo(), and string.
Referenced by functionInformation().
sanitizeString()
std::string sanitizeString (std::string data)
Definition at line 181 of file doxyparse.cpp.
                                         {
  QCString new_data = QCString(data.c_str());
  new_data = substitute(new_data,"\"", "");
  new_data = substitute(new_data,"\'", ""); // https://github.com/analizo/analizo/issues/138
  return !new_data.isEmpty() ? new_data.data() : "";
}
References data, QCString::data(), QCString::isEmpty(), and substitute().
startYamlDocument()
static void startYamlDocument () [static]
Definition at line 127 of file doxyparse.cpp.
                                {
  printf("---\n");
}
Referenced by main().
Variable Documentation
is_c_code
bool is_c_code = true [static]
Definition at line 86 of file doxyparse.cpp.
Referenced by classInformation(), detectProgrammingLanguage(), and isPartOfCStruct().