doxygen/build/doxygen/src/tooltip.cpp File Reference
#include <map>
#include <memory>
#include <unordered_map>
#include <string>
#include <mutex>
#include `tooltip.h`
#include `definition.h`
#include `outputgen.h`
#include `util.h`
#include `filedef.h`
#include `doxygen.h`
#include `config.h`
Classes
class TooltipManager::Private
Functions
static QCString escapeId (const QCString &s)
Variables
static std::mutex g_tooltipsMutex
static std::unordered_map< int, std::set< std::string > > g_tooltipsWrittenPerFile
Function Documentation
escapeId()
static QCString escapeId (const QCString & s) [static]
Definition at line 47 of file tooltip.cpp.
{
  QCString res=s;
  for (uint i=0;i<res.length();i++) if (!isId(res[i])) res[i]='_';
  return res;
}
References isId(), QCString::length(), and s.
Referenced by TooltipManager::addTooltip().
Variable Documentation
g_tooltipsMutex
std::mutex g_tooltipsMutex [static]
Definition at line 30 of file tooltip.cpp.
Referenced by TooltipManager::writeTooltips().
g_tooltipsWrittenPerFile
std::unordered_map<int, std::set<std::string> > g_tooltipsWrittenPerFile [static]
Definition at line 31 of file tooltip.cpp.
Referenced by TooltipManager::writeTooltips().