doxygen/build/doxygen/libmscgen/mscgen_msc.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include `mscgen_config.h`
#include `mscgen_safe.h`
#include `mscgen_msc.h`
Classes
struct MscEntityTag
struct MscEntityListTag
struct MscArcTag
struct MscArcListTag
struct MscAttribTag
struct MscOptTag
struct MscTag
Functions
static const char * findAttrib (const struct MscAttribTag *attr, MscAttribType a)
static void freeAttribList (struct MscAttribTag *attr)
struct MscOptTag * MscAllocOpt (MscOptType type, char *value)
struct MscOptTag * MscLinkOpt (struct MscOptTag *head, struct MscOptTag *newHead)
const char * MscPrettyOptType (MscOptType t)
struct MscOptTag * MscFindOpt (struct MscOptTag *list, MscOptType type)
void MscPrintOptList (struct MscOptTag *list)
struct MscEntityTag * MscAllocEntity (char *entityName)
struct MscEntityListTag * MscLinkEntity (struct MscEntityListTag *list, struct MscEntityTag *elem)
void MscPrintEntityList (struct MscEntityListTag *list)
struct MscArcTag * MscAllocArc (char *srcEntity, char *dstEntity, MscArcType type, unsigned int inputLine)
struct MscArcListTag * MscLinkArc (struct MscArcListTag *list, struct MscArcTag *elem)
void MscPrintArcList (struct MscArcListTag *list)
struct MscAttribTag * MscAllocAttrib (MscAttribType type, char *value)
struct MscAttribTag * MscLinkAttrib (struct MscAttribTag *head, struct MscAttribTag *newHead)
void MscArcLinkAttrib (struct MscArcTag *arc, struct MscAttribTag *att)
void MscEntityLinkAttrib (struct MscEntityTag *ent, struct MscAttribTag *att)
void MscPrintAttrib (const struct MscAttribTag *att)
const char * MscPrettyAttribType (MscAttribType t)
struct MscTag * MscAlloc (struct MscOptTag *optList, struct MscEntityListTag *entityList, struct MscArcListTag *arcList)
void MscFree (struct MscTag *m)
void MscPrint (struct MscTag *m)
unsigned int MscGetNumEntities (struct MscTag *m)
unsigned int MscGetNumArcs (Msc m)
unsigned int MscGetNumParallelArcs (Msc m)
unsigned int MscGetNumOpts (Msc m)
int MscGetEntityIndex (struct MscTag *m, const char *label)
void MscResetEntityIterator (struct MscTag *m)
Boolean MscNextEntity (struct MscTag *m)
const char * MscGetCurrentEntAttrib (struct MscTag *m, MscAttribType a)
const char * MscGetEntAttrib (Msc m, unsigned int entIdx, MscAttribType a)
void MscResetArcIterator (struct MscTag *m)
Boolean MscNextArc (struct MscTag *m)
const char * MscGetCurrentArcSource (struct MscTag *m)
const char * MscGetCurrentArcDest (struct MscTag *m)
MscArcType MscGetCurrentArcType (struct MscTag *m)
const char * MscGetCurrentArcAttrib (struct MscTag *m, MscAttribType a)
Boolean MscGetOptAsFloat (struct MscTag *m, MscOptType type, float *const f)
unsigned int MscGetCurrentArcInputLine (struct MscTag *m)
Boolean MscGetOptAsBoolean (struct MscTag *m, MscOptType type, Boolean *const b)
Function Documentation
findAttrib()
static const char * findAttrib (const struct MscAttribTag * attr, MscAttribType a) [static]
Find come attribute in an attribute list.
Parameters
 in attr Head of the linked list to search.
 in a The attribute type to find.
Return values
NULL If the attribute was not found or the passed list was NULL.
Definition at line 100 of file mscgen_msc.c.
{
    while(attr != NULL && attr->type != a)
    {
        attr = attr->next;
    }
    if(attr != NULL)
    {
        return attr->value;
    }
    else
    {
        return NULL;
    }
}
References a, MscEntityTag::attr, MscAttribTag::next, MscAttribTag::type, and MscAttribTag::value.
Referenced by MscGetCurrentEntAttrib(), and MscGetEntAttrib().
freeAttribList()
static void freeAttribList (struct MscAttribTag * attr) [static]
Free the memory underlying a list of attributes.
Definition at line 120 of file mscgen_msc.c.
{
    while(attr)
    {
        struct MscAttribTag *next = attr->next;
        free(attr->value);
        free(attr);
        attr = next;
    }
}
References MscEntityTag::attr, MscAttribTag::next, and MscAttribTag::value.
Referenced by MscFree().
MscAlloc()
struct MscTag * MscAlloc (struct MscOptTag * optList, struct MscEntityListTag * entityList, struct MscArcListTag * arcList)
Definition at line 482 of file mscgen_msc.c.
{
    struct MscTag *m = malloc_s(sizeof(struct MscTag));
    /* Copy the lists */
    m->optList = optList;
    m->entityList = entityList;
    m->arcList = arcList;
    /* Reset the iterators */
    MscResetEntityIterator(m);
    MscResetArcIterator(m);
    return m;
}
References MscTag::arcList, MscTag::entityList, malloc_s(), MscResetArcIterator(), MscResetEntityIterator(), and MscTag::optList.
MscAllocArc()
struct MscArcTag * MscAllocArc (char * srcEntity, char * dstEntity, MscArcType type, unsigned int inputLine)
Definition at line 282 of file mscgen_msc.c.
{
    struct MscArcTag *a = malloc_s(sizeof(struct MscArcTag));
    /* A discontinuity arcs are not between entities */
    if(type == MSC_ARC_DISCO)
    {
        assert(srcEntity == NULL && dstEntity == NULL);
    }
    a->inputLine = inputLine;
    a->src = srcEntity;
    a->dst = dstEntity;
    a->type = type;
    a->next = NULL;
    a->attr = NULL;
    return a;
}
References a, MscArcTag::inputLine, malloc_s(), MSC_ARC_DISCO, and MscArcTag::type.
MscAllocAttrib()
struct MscAttribTag * MscAllocAttrib (MscAttribType type, char * value)
Definition at line 369 of file mscgen_msc.c.
{
    struct MscAttribTag *a = malloc_s(sizeof(struct MscAttribTag));
    a->type = type;
    a->value = value;
    a->next = NULL;
    return a;
}
References a, malloc_s(), MscAttribTag::type, and MscAttribTag::value.
MscAllocEntity()
struct MscEntityTag * MscAllocEntity (char * entityName)
Definition at line 220 of file mscgen_msc.c.
{
    struct MscEntityTag *e = malloc_s(sizeof(struct MscEntityListTag));
    e->label = entityName;
    e->attr = NULL;
    e->next = NULL;
    return e;
}
References e, and malloc_s().
MscAllocOpt()
struct MscOptTag * MscAllocOpt (MscOptType type, char * value)
Definition at line 137 of file mscgen_msc.c.
{
    struct MscOptTag *a = malloc_s(sizeof(struct MscOptTag));
    a->type = type;
    a->value = value;
    a->next = NULL;
    return a;
}
References a, malloc_s(), MscOptTag::type, and MscOptTag::value.
MscArcLinkAttrib()
void MscArcLinkAttrib (struct MscArcTag * arc, struct MscAttribTag * att)
Definition at line 407 of file mscgen_msc.c.
{
    if(arc->attr)
    {
        arc->attr = MscLinkAttrib(arc->attr, att);
    }
    else
    {
        arc->attr = att;
    }
}
References MscArcTag::attr, and MscLinkAttrib().
MscEntityLinkAttrib()
void MscEntityLinkAttrib (struct MscEntityTag * ent, struct MscAttribTag * att)
Definition at line 424 of file mscgen_msc.c.
{
    if(ent->attr)
    {
        ent->attr = MscLinkAttrib(ent->attr, att);
    }
    else
    {
        ent->attr = att;
    }
}
References MscEntityTag::attr, and MscLinkAttrib().
MscFindOpt()
struct MscOptTag * MscFindOpt (struct MscOptTag * list, MscOptType type)
Definition at line 184 of file mscgen_msc.c.
{
    struct MscOptTag *elem = list;
    while(elem && elem->type != type)
    {
        elem = elem->next;
    }
    if(elem && elem->type == type)
    {
        return elem;
    }
    return NULL;
}
References MscOptTag::next, and MscOptTag::type.
Referenced by MscGetOptAsBoolean(), and MscGetOptAsFloat().
MscFree()
void MscFree (struct MscTag * m)
Definition at line 500 of file mscgen_msc.c.
{
    struct MscOptTag *opt = m->optList;
    struct MscEntityTag *entity = m->entityList->head;
    struct MscArcTag *arc = m->arcList->head;
    while(opt)
    {
        struct MscOptTag *next = opt->next;
        free(opt->value);
        free(opt);
        opt = next;
    }
    while(entity)
    {
        struct MscEntityTag *next = entity->next;
        freeAttribList(entity->attr);
        free(entity->label);
        free(entity);
        entity = next;
    }
    while(arc)
    {
        struct MscArcTag *next = arc->next;
        freeAttribList(arc->attr);
        free(arc->dst);
        free(arc->src);
        free(arc);
        arc = next;
    }
    free(m->entityList);
    free(m->arcList);
    free(m);
}
References MscTag::arcList, MscEntityTag::attr, MscArcTag::attr, MscArcTag::dst, MscTag::entityList, freeAttribList(), MscEntityListTag::head, MscArcListTag::head, MscEntityTag::label, MscEntityTag::next, MscArcTag::next, MscOptTag::next, MscTag::optList, MscArcTag::src, and MscOptTag::value.
Referenced by mscgen_generate().
MscGetCurrentArcAttrib()
const char * MscGetCurrentArcAttrib (struct MscTag * m, MscAttribType a)
Definition at line 720 of file mscgen_msc.c.
{
    struct MscAttribTag *attr;
    if(!m->nextArc)
    {
       return NULL;
    }
    attr = m->nextArc->attr;
    while(attr != NULL && attr->type != a)
    {
        attr = attr->next;
    }
    if(attr != NULL)
    {
        return attr->value;
    }
    else
    {
        return NULL;
    }
}
References a, MscArcTag::attr, MscAttribTag::next, MscTag::nextArc, MscAttribTag::type, and MscAttribTag::value.
Referenced by computeCanvasSize(), getArcGradient(), and mscgen_generate().
MscGetCurrentArcDest()
const char * MscGetCurrentArcDest (struct MscTag * m)
Definition at line 710 of file mscgen_msc.c.
{
    return m->nextArc ? m->nextArc->dst : NULL;
}
References MscArcTag::dst, and MscTag::nextArc.
Referenced by checkMsc(), computeCanvasSize(), and mscgen_generate().
MscGetCurrentArcInputLine()
unsigned int MscGetCurrentArcInputLine (struct MscTag * m)
Definition at line 760 of file mscgen_msc.c.
{
    if(m->nextArc)
    {
       return m->nextArc->inputLine;
    }
    else
    {
        return 0;
    }
}
References MscArcTag::inputLine, and MscTag::nextArc.
Referenced by checkMsc().
MscGetCurrentArcSource()
const char * MscGetCurrentArcSource (struct MscTag * m)
Definition at line 705 of file mscgen_msc.c.
{
    return m->nextArc ? m->nextArc->src : NULL;
}
References MscTag::nextArc, and MscArcTag::src.
Referenced by checkMsc(), computeCanvasSize(), and mscgen_generate().
MscGetCurrentEntAttrib()
const char * MscGetCurrentEntAttrib (struct MscTag * m, MscAttribType a)
Definition at line 628 of file mscgen_msc.c.
{
    const char *r;
    if(!m->nextEntity)
    {
       return NULL;
    }
    r = findAttrib(m->nextEntity->attr, a);
    /* If the entity label was sought but not found, return entity name */
    if(r == NULL && a == MSC_ATTR_LABEL)
    {
        return m->nextEntity->label;
    }
    else
    {
        return r;
    }
}
References a, MscEntityTag::attr, findAttrib(), MscEntityTag::label, MSC_ATTR_LABEL, MscTag::nextEntity, and r.
Referenced by mscgen_generate().
MscGetEntityIndex()
int MscGetEntityIndex (struct MscTag * m, const char * label)
Get the index of some entity. This returns the column index for the entity identified by the passed label.
Parameters
m The MSC to analyse.
label The label to find.
Return values
-1 If the label was not found, otherwise the column index.
Definition at line 586 of file mscgen_msc.c.
{
    struct MscEntityTag *entity = m->entityList->head;
    int c = 0;
    assert(label);
    while(entity != NULL && strcmp(entity->label, label) != 0)
    {
        entity = entity->next;
        c++;
    }
    if(entity == NULL)
    {
        return -1;
    }
    else
    {
        return c;
    }
}
References c, MscTag::entityList, MscEntityListTag::head, MscEntityTag::label, MscEntityTag::next, and strcmp().
Referenced by checkMsc(), computeCanvasSize(), and mscgen_generate().
MscGetNumArcs()
unsigned int MscGetNumArcs (Msc m)
Definition at line 562 of file mscgen_msc.c.
{
    return m->arcList->elements;
}
References MscTag::arcList, and MscArcListTag::elements.
Referenced by computeCanvasSize(), getArcGradient(), mscgen_generate(), and MscPrint().
MscGetNumEntities()
unsigned int MscGetNumEntities (struct MscTag * m)
Definition at line 557 of file mscgen_msc.c.
{
    return m->entityList->elements;
}
References MscEntityListTag::elements, and MscTag::entityList.
Referenced by arcLine(), arcText(), computeCanvasSize(), computeLabelLines(), entityLines(), mscgen_generate(), and MscPrint().
MscGetNumOpts()
unsigned int MscGetNumOpts (Msc m)
Definition at line 572 of file mscgen_msc.c.
{
    struct MscOptTag *elem = m->optList;
    unsigned int count = 0;
    while(elem)
    {
        count++;
        elem = elem->next;
    }
    return count;
}
References MscOptTag::next, and MscTag::optList.
Referenced by MscPrint().
MscGetNumParallelArcs()
unsigned int MscGetNumParallelArcs (Msc m)
Definition at line 567 of file mscgen_msc.c.
{
    return m->arcList->parElements;
}
References MscTag::arcList, and MscArcListTag::parElements.
Referenced by computeCanvasSize(), getArcGradient(), mscgen_generate(), and MscPrint().
MscGetOptAsBoolean()
Boolean MscGetOptAsBoolean (struct MscTag * m, MscOptType type, Boolean *const b)
Get an MSC option, returning the value as a Boolean.
Parameters
 in m The MSC to analyse.
 in type The option type to retrieve.
 in,out b Pointer to be filled with parsed value.
Return values
TRUE If the option was found and parsed successfully, otherwise FALSE in which case *b is unmodified.
Definition at line 772 of file mscgen_msc.c.
{
    struct MscOptTag *opt = MscFindOpt(m->optList, type);
    if(opt != NULL)
    {
        const char *v = opt->value;
        if(strcasecmp(v, "true") == 0 || strcasecmp(v, "yes") == 0 ||
           strcasecmp(v, "on") == 0 || strcasecmp(v, "1") == 0)
        {
            *b = TRUE;
            return TRUE;
        }
        else if(strcasecmp(v, "false") == 0 || strcasecmp(v, "no") == 0 ||
                strcasecmp(v, "off") == 0 || strcasecmp(v, "0") == 0)
        {
            *b = FALSE;
            return TRUE;
        }
        else
        {
            fprintf(stderr, "Warning: Unrecognised boolean option value '%s'. Valid values are 'true',\n"
                            " 'false', 'yes', 'no', 'on', 'off', '1' and '0'.\n",
                            v);
            return FALSE;
        }
    }
    return FALSE;
}
References b, FALSE, MscFindOpt(), MscTag::optList, TRUE, MscOptTag::type, and MscOptTag::value.
Referenced by mscgen_generate().
MscGetOptAsFloat()
Boolean MscGetOptAsFloat (struct MscTag * m, MscOptType type, float *const f)
Get an MSC option, returning the value as a float.
Parameters
 in m The MSC to analyse.
 in type The option type to retrieve.
 in,out f Pointer to be filled with parsed value.
Return values
TRUE If the option was found and parsed successfully.
Definition at line 747 of file mscgen_msc.c.
{
    struct MscOptTag *opt = MscFindOpt(m->optList, type);
    if(opt != NULL)
    {
        *f = (float)atof(opt->value);
        return *f != 0.0f;
    }
    return FALSE;
}
References f, FALSE, MscFindOpt(), MscTag::optList, MscOptTag::type, and MscOptTag::value.
Referenced by mscgen_generate().
MscLinkArc()
struct MscArcListTag * MscLinkArc (struct MscArcListTag * list, struct MscArcTag * elem)
Definition at line 309 of file mscgen_msc.c.
{
    /* Check if the list has been allocated or not */
    if(list == NULL)
    {
        list = zalloc_s(sizeof(struct MscArcListTag));
    }
    /* Check for an empty list */
    if(list->head == NULL)
    {
        list->head = list->tail = elem;
    }
    else
    {
        /* Add to tail */
        list->tail->next = elem;
        list->tail = elem;
    }
    /* Increment count of elements */
    list->elements++;
    if(elem->type == MSC_ARC_PARALLEL)
    {
        /* A parallel arc is a place holder, and indicates the next arc
         * is on the same line. It also needs to account itself, so subtract
         * two here.
         */
        list->parElements += 2;
    }
    return list;
}
References MscArcListTag::elements, MscArcListTag::head, MSC_ARC_PARALLEL, MscArcTag::next, MscArcListTag::parElements, MscArcListTag::tail, MscArcTag::type, and zalloc_s().
MscLinkAttrib()
struct MscAttribTag * MscLinkAttrib (struct MscAttribTag * head, struct MscAttribTag * newHead)
Definition at line 386 of file mscgen_msc.c.
{
    struct MscAttribTag *tail = newHead;
    assert(newHead);
    /* Find the end of the list */
    while(tail->next)
    {
        tail = tail->next;
    }
    tail->next = head;
    return newHead;
}
References MscAttribTag::next.
Referenced by MscArcLinkAttrib(), and MscEntityLinkAttrib().
MscLinkEntity()
struct MscEntityListTag * MscLinkEntity (struct MscEntityListTag * list, struct MscEntityTag * elem)
Definition at line 235 of file mscgen_msc.c.
{
    /* Check if the list has been allocated or not */
    if(list == NULL)
    {
        list = zalloc_s(sizeof(struct MscEntityListTag));
    }
    /* Check for an empty list */
    if(list->head == NULL)
    {
        list->head = list->tail = elem;
    }
    else
    {
        /* Add to tail */
        list->tail->next = elem;
        list->tail = elem;
    }
    /* Increment count of elements */
    list->elements++;
    return list;
}
References MscEntityListTag::elements, MscEntityListTag::head, MscEntityTag::next, MscEntityListTag::tail, and zalloc_s().
MscLinkOpt()
struct MscOptTag * MscLinkOpt (struct MscOptTag * head, struct MscOptTag * newHead)
Definition at line 151 of file mscgen_msc.c.
{
    struct MscOptTag *tail = newHead;
    assert(newHead);
    /* Find the end of the list */
    while(tail->next)
    {
        tail = tail->next;
    }
    tail->next = head;
    return newHead;
}
References MscOptTag::next.
MscPrettyAttribType()
const char * MscPrettyAttribType (MscAttribType t)
Definition at line 456 of file mscgen_msc.c.
{
    switch(t)
    {
        case MSC_ATTR_LABEL: return "label";
        case MSC_ATTR_URL: return "url";
        case MSC_ATTR_ID: return "id";
        case MSC_ATTR_IDURL: return "idurl";
        case MSC_ATTR_LINE_COLOUR: return "linecolour";
        case MSC_ATTR_TEXT_COLOUR: return "textcolour";
        case MSC_ATTR_TEXT_BGCOLOUR: return "textbgcolour";
        case MSC_ATTR_ARC_LINE_COLOUR: return "arclinecolour";
        case MSC_ATTR_ARC_TEXT_COLOUR: return "arctextcolour";
        case MSC_ATTR_ARC_TEXT_BGCOLOUR: return "arctextbgcolour";
        case MSC_ATTR_NO_ARROWS: return "noarrows";
        case MSC_ATTR_BI_ARROWS : return "biarrows";
        default:
            return "<unknown>";
    }
}
References MSC_ATTR_ARC_LINE_COLOUR, MSC_ATTR_ARC_TEXT_BGCOLOUR, MSC_ATTR_ARC_TEXT_COLOUR, MSC_ATTR_BI_ARROWS, MSC_ATTR_ID, MSC_ATTR_IDURL, MSC_ATTR_LABEL, MSC_ATTR_LINE_COLOUR, MSC_ATTR_NO_ARROWS, MSC_ATTR_TEXT_BGCOLOUR, MSC_ATTR_TEXT_COLOUR, and MSC_ATTR_URL.
Referenced by MscPrintAttrib().
MscPrettyOptType()
const char * MscPrettyOptType (MscOptType t)
Definition at line 172 of file mscgen_msc.c.
{
    switch(t)
    {
        case MSC_OPT_HSCALE: return "hscale";
        case MSC_OPT_WIDTH: return "width";
        case MSC_OPT_ARCGRADIENT: return "arcgradient";
        default:
            return "unknown";
    }
}
References MSC_OPT_ARCGRADIENT, MSC_OPT_HSCALE, and MSC_OPT_WIDTH.
Referenced by MscPrintOptList().
MscPrint()
void MscPrint (struct MscTag * m)
Definition at line 544 of file mscgen_msc.c.
{
    printf("Option list (%d options)\n", MscGetNumOpts(m));
    MscPrintOptList(m->optList);
    printf("Entity list (%d entities, %d parallel)\n",
           MscGetNumEntities(m), MscGetNumParallelArcs(m));
    MscPrintEntityList(m->entityList);
    printf("\nArc list (%d arcs)\n", MscGetNumArcs(m));
    MscPrintArcList(m->arcList);
}
References MscTag::arcList, MscTag::entityList, MscGetNumArcs(), MscGetNumEntities(), MscGetNumOpts(), MscGetNumParallelArcs(), MscPrintArcList(), MscPrintEntityList(), MscPrintOptList(), and MscTag::optList.
MscPrintArcList()
void MscPrintArcList (struct MscArcListTag * list)
Definition at line 348 of file mscgen_msc.c.
{
    struct MscArcTag *elem = list->head;
    while(elem)
    {
        printf("%p: '%s' -> '%s'\n", elem, elem->src, elem->dst);
        MscPrintAttrib(elem->attr);
        elem = elem->next;
    }
}
References MscArcTag::attr, MscArcTag::dst, MscArcListTag::head, MscPrintAttrib(), MscArcTag::next, and MscArcTag::src.
Referenced by MscPrint().
MscPrintAttrib()
void MscPrintAttrib (const struct MscAttribTag * att)
Definition at line 441 of file mscgen_msc.c.
{
    while(att)
    {
        printf(" %s = %s\n", MscPrettyAttribType(att->type), att->value);
        att = att->next;
    }
}
References MscPrettyAttribType(), MscAttribTag::next, MscAttribTag::type, and MscAttribTag::value.
Referenced by MscPrintArcList(), and MscPrintEntityList().
MscPrintEntityList()
void MscPrintEntityList (struct MscEntityListTag * list)
Definition at line 263 of file mscgen_msc.c.
{
    struct MscEntityTag *elem = list->head;
    while(elem)
    {
        printf("%p: %s\n", elem, elem->label);
        MscPrintAttrib(elem->attr);
        elem = elem->next;
    }
}
References MscEntityTag::attr, MscEntityListTag::head, MscEntityTag::label, MscPrintAttrib(), and MscEntityTag::next.
Referenced by MscPrint().
MscPrintOptList()
void MscPrintOptList (struct MscOptTag * list)
Definition at line 202 of file mscgen_msc.c.
{
    struct MscOptTag *elem = list;
    while(elem)
    {
        printf("%p: %s=%s\n", elem, MscPrettyOptType(elem->type), elem->value);
        elem = elem->next;
    }
}
References MscPrettyOptType(), MscOptTag::next, MscOptTag::type, and MscOptTag::value.
Referenced by MscPrint().
MscResetArcIterator()
void MscResetArcIterator (struct MscTag * m)
Definition at line 687 of file mscgen_msc.c.
{
    m->nextArc = m->arcList->head;
}
References MscTag::arcList, MscArcListTag::head, and MscTag::nextArc.
Referenced by checkMsc(), computeCanvasSize(), MscAlloc(), and mscgen_generate().
MscResetEntityIterator()
void MscResetEntityIterator (struct MscTag * m)
Definition at line 609 of file mscgen_msc.c.
{
    m->nextEntity = m->entityList->head;
}
References MscTag::entityList, MscEntityListTag::head, and MscTag::nextEntity.
Referenced by MscAlloc(), and mscgen_generate().