doxygen/build/doxygen/libmscgen/gd_security.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include `gd.h`
#include `gd_errors.h`
Functions
int overflow2 (int a, int b)
Function Documentation
overflow2()
int overflow2 (int a, int b)
Definition at line 21 of file gd_security.c.
{
    if(a <= 0 || b <= 0) {
        gd_error_ex(GD_WARNING, "one parameter to a memory allocation multiplication is negative or zero, failing operation gracefully\n");
        return 1;
    }
    if(a > INT_MAX / b) {
        gd_error_ex(GD_WARNING, "product of memory allocation multiplication would exceed INT_MAX, failing operation gracefully\n");
        return 1;
    }
    return 0;
}
References a, b, gd_error_ex(), and GD_WARNING.
Referenced by _gdImageFillTiled(), and BGD_DECLARE().