doxygen/build/doxygen/libmscgen/mscgen_svg_out.c File Reference
#include `mscgen_config.h`
#include <math.h>
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include `mscgen_adraw_int.h`
#include `mscgen_safe.h`
#include `mscgen_utf8.h`
Classes
struct SvgContextTag
struct SvgCharMetric
Typedefs
typedef struct SvgContextTag SvgContext
Functions
static SvgContext * getSvgCtx (struct ADrawTag *ctx)
static FILE * getSvgFile (struct ADrawTag *ctx)
static const char * getSvgPen (struct ADrawTag *ctx)
static const char * getSvgBgPen (struct ADrawTag *ctx)
static int getSpace (struct ADrawTag *ctx, long thousanths)
static void arcPoint (float cx, float cy, float w, float h, float a, unsigned int *x, unsigned int *y)
static void writeEscaped (struct ADrawTag *ctx, const char *string)
static void svgRect (struct ADrawTag *ctx, const char *colour, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
static const char * svgColour (ADrawColour col)
unsigned int SvgTextWidth (struct ADrawTag *ctx, const char *string)
int SvgTextHeight (struct ADrawTag *ctx)
void SvgLine (struct ADrawTag *ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
void SvgDottedLine (struct ADrawTag *ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
void SvgTextR (struct ADrawTag *ctx, unsigned int x, unsigned int y, const char *string)
void SvgTextL (struct ADrawTag *ctx, unsigned int x, unsigned int y, const char *string)
void SvgTextC (struct ADrawTag *ctx, unsigned int x, unsigned int y, const char *string)
void SvgFilledTriangle (struct ADrawTag *ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2, unsigned int x3, unsigned int y3)
void SvgFilledCircle (struct ADrawTag *ctx, unsigned int x, unsigned int y, unsigned int r)
void SvgFilledRectangle (struct ADrawTag *ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
void SvgArc (struct ADrawTag *ctx, unsigned int cx, unsigned int cy, unsigned int w, unsigned int h, unsigned int s, unsigned int e)
void SvgDottedArc (struct ADrawTag *ctx, unsigned int cx, unsigned int cy, unsigned int w, unsigned int h, unsigned int s, unsigned int e)
void SvgSetPen (struct ADrawTag *ctx, ADrawColour col)
void SvgSetBgPen (struct ADrawTag *ctx, ADrawColour col)
void SvgSetFontSize (struct ADrawTag *ctx, ADrawFontSize size)
Boolean SvgClose (struct ADrawTag *ctx)
Boolean SvgInit (unsigned int w, unsigned int h, const char *file, struct ADrawTag *outContext)
Variables
static const SvgCharMetric SvgHelvetica
Typedef Documentation
SvgContext
typedef struct SvgContextTag SvgContext
Function Documentation
arcPoint()
static void arcPoint (float cx, float cy, float w, float h, float a, unsigned int * x, unsigned int * y) [static]
Compute a point on an ellipse. This computes the point on an ellipse.
Parameters
 in cx,cy Center of the ellipse.
 in w,h Ellipse width and height.
 in a Angle in degrees.
 in,out x,y Pointer to be populated with result co-ordinates.
Definition at line 151 of file mscgen_svg_out.c.
{
    float rad = (float)((a * M_PI) / 180.0f);
    /* Compute point, noting this is for SVG co-ordinate system */
    *x = (unsigned int)round(cx + ((w / 2.0f) * cos(rad)));
    *y = (unsigned int)round(cy + ((h / 2.0f) * sin(rad)));
}
References a, cx, cy, h, M_PI, w, x, and y.
Referenced by SvgArc(), and SvgDottedArc().
getSpace()
static int getSpace (struct ADrawTag * ctx, long thousanths) [static]
Given a font metric measurement, return device dependent units. Font metric data is stored as 1/1000th of a point, and therefore needs to be multiplied by the font point size and divided by 1000 to give a value in device dependent units.
Definition at line 137 of file mscgen_svg_out.c.
{
    return ((thousanths * getSvgCtx(ctx)->fontPoints) + 500) / 1000;
}
References getSvgCtx().
Referenced by SvgTextC(), SvgTextHeight(), SvgTextL(), SvgTextR(), and SvgTextWidth().
getSvgBgPen()
static const char * getSvgBgPen (struct ADrawTag * ctx) [static]
Definition at line 127 of file mscgen_svg_out.c.
{
    return getSvgCtx(ctx)->penBgColName;
}
References getSvgCtx(), and SvgContextTag::penBgColName.
Referenced by SvgTextC(), SvgTextL(), and SvgTextR().
getSvgCtx()
static SvgContext * getSvgCtx (struct ADrawTag * ctx) [static]
Get the context pointer from an ADraw structure.
Definition at line 110 of file mscgen_svg_out.c.
{
    return (SvgContext *)ctx->internal;
}
References ADrawTag::internal.
Referenced by getSpace(), getSvgBgPen(), getSvgFile(), getSvgPen(), SvgClose(), SvgSetBgPen(), SvgSetFontSize(), SvgSetPen(), SvgTextC(), SvgTextL(), and SvgTextR().
getSvgFile()
static FILE * getSvgFile (struct ADrawTag * ctx) [static]
Get the context pointer from an ADraw structure.
Definition at line 117 of file mscgen_svg_out.c.
{
    return getSvgCtx(ctx)->of;
}
References getSvgCtx(), and SvgContextTag::of.
Referenced by SvgArc(), SvgDottedArc(), SvgDottedLine(), SvgFilledCircle(), SvgFilledTriangle(), SvgLine(), svgRect(), SvgTextC(), SvgTextL(), SvgTextR(), and writeEscaped().
getSvgPen()
static const char * getSvgPen (struct ADrawTag * ctx) [static]
Definition at line 122 of file mscgen_svg_out.c.
{
    return getSvgCtx(ctx)->penColName;
}
References getSvgCtx(), and SvgContextTag::penColName.
Referenced by SvgArc(), SvgDottedArc(), SvgDottedLine(), SvgFilledCircle(), SvgFilledRectangle(), SvgFilledTriangle(), and SvgLine().
SvgArc()
void SvgArc (struct ADrawTag * ctx, unsigned int cx, unsigned int cy, unsigned int w, unsigned int h, unsigned int s, unsigned int e)
Definition at line 399 of file mscgen_svg_out.c.
{
    unsigned int sx, sy, ex, ey;
    /* Get start and end x,y */
    arcPoint((float)cx, (float)cy, (float)w, (float)h, (float)s, &sx, &sy);
    arcPoint((float)cx, (float)cy, (float)w, (float)h, (float)e, &ex, &ey);
    fprintf(getSvgFile(ctx),
            "<path d=\"M %u %u A%u,%u 0 0,1 %u,%u\" stroke=\"%s\" fill=\"none\"/>",
            sx, sy, w / 2, h / 2, ex, ey, getSvgPen(ctx));
}
References arcPoint(), cx, cy, e, getSvgFile(), getSvgPen(), h, s, sy, and w.
Referenced by SvgInit().
SvgClose()
Boolean SvgClose (struct ADrawTag * ctx)
Definition at line 496 of file mscgen_svg_out.c.
{
    SvgContext *context = getSvgCtx(ctx);
    /* Close the SVG */
    fprintf(context->of, "</svg>\n");
    /* Close the output file */
    if(context->of != stdout)
    {
        fclose(context->of);
    }
    /* Free and destroy context */
    free(context);
    ctx->internal = NULL;
    return TRUE;
}
References Portable::fclose(), getSvgCtx(), ADrawTag::internal, SvgContextTag::of, and TRUE.
Referenced by SvgInit().
svgColour()
static const char * svgColour (ADrawColour col) [static]
Definition at line 219 of file mscgen_svg_out.c.
{
    switch(col)
    {
        case ADRAW_COL_WHITE:
            return "white";
        case ADRAW_COL_BLACK:
            return "black";
        case ADRAW_COL_BLUE:
            return "blue";
        case ADRAW_COL_RED:
            return "red";
        case ADRAW_COL_GREEN:
            return "green";
        default:
            return NULL;
    }
}
References ADRAW_COL_BLACK, ADRAW_COL_BLUE, ADRAW_COL_GREEN, ADRAW_COL_RED, and ADRAW_COL_WHITE.
Referenced by SvgSetBgPen(), and SvgSetPen().
SvgDottedArc()
void SvgDottedArc (struct ADrawTag * ctx, unsigned int cx, unsigned int cy, unsigned int w, unsigned int h, unsigned int s, unsigned int e)
Definition at line 419 of file mscgen_svg_out.c.
{
    unsigned int sx, sy, ex, ey;
    /* Get start and end x,y */
    arcPoint((float)cx, (float)cy, (float)w, (float)h, (float)s, &sx, &sy);
    arcPoint((float)cx, (float)cy, (float)w, (float)h, (float)e, &ex, &ey);
    fprintf(getSvgFile(ctx),
            "<path d=\"M %u %u A%u,%u 0 0,1 %u,%u\" stroke=\"%s\" fill=\"none\" stroke-dasharray=\"2,2\"/>",
            sx, sy, w / 2, h / 2, ex, ey, getSvgPen(ctx));
}
References arcPoint(), cx, cy, e, getSvgFile(), getSvgPen(), h, s, sy, and w.
Referenced by SvgInit().
SvgDottedLine()
void SvgDottedLine (struct ADrawTag * ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
Definition at line 287 of file mscgen_svg_out.c.
{
    fprintf(getSvgFile(ctx),
            "<line x1=\"%u\" y1=\"%u\" x2=\"%u\" y2=\"%u\" stroke=\"%s\" stroke-dasharray=\"2,2\"/>\n",
            x1, y1, x2, y2, getSvgPen(ctx));
}
References getSvgFile(), getSvgPen(), x1, x2, y1, and y2.
Referenced by SvgInit().
SvgFilledCircle()
void SvgFilledCircle (struct ADrawTag * ctx, unsigned int x, unsigned int y, unsigned int r)
Definition at line 377 of file mscgen_svg_out.c.
{
    fprintf(getSvgFile(ctx),
            "<circle fill=\"%s\" cx=\"%u\" cy=\"%u\" r=\"%u\"/>\n",
            getSvgPen(ctx),
            x, y, r);
}
References getSvgFile(), getSvgPen(), r, x, and y.
Referenced by SvgInit().
SvgFilledRectangle()
void SvgFilledRectangle (struct ADrawTag * ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
Definition at line 389 of file mscgen_svg_out.c.
{
    svgRect(ctx, getSvgPen(ctx), x1, y1, x2, y2);
}
References getSvgPen(), svgRect(), x1, x2, y1, and y2.
Referenced by SvgInit().
SvgFilledTriangle()
void SvgFilledTriangle (struct ADrawTag * ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2, unsigned int x3, unsigned int y3)
Definition at line 359 of file mscgen_svg_out.c.
{
    fprintf(getSvgFile(ctx),
            "<polygon fill=\"%s\" points=\"%u,%u %u,%u %u,%u\"/>\n",
            getSvgPen(ctx),
            x1, y1,
            x2, y2,
            x3, y3);
}
References getSvgFile(), getSvgPen(), x1, x2, y1, and y2.
Referenced by SvgInit().
SvgInit()
Boolean SvgInit (unsigned int w, unsigned int h, const char * file, struct ADrawTag * outContext)
Definition at line 518 of file mscgen_svg_out.c.
{
    SvgContext *context;
    /* Create context */
    context = outContext->internal = malloc_s(sizeof(SvgContext));
    if(context == NULL)
    {
        return FALSE;
    }
    /* Open the output file */
    if(strcmp(file, "-") == 0)
    {
        context->of = stdout;
    }
    else
    {
        context->of = fopen(file, "wb");
        if(!context->of)
        {
            fprintf(stderr, "SvgInit: Failed to open output file '%s': %s\n", file, strerror(errno));
            return FALSE;
        }
    }
    /* Set the initial pen state */
    SvgSetPen(outContext, ADRAW_COL_BLACK);
    SvgSetBgPen(outContext, ADRAW_COL_WHITE);
    /* Default to small font */
    SvgSetFontSize(outContext, ADRAW_FONT_SMALL);
    fprintf(context->of, "<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n"
                         " \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n");
    fprintf(context->of, "<svg version=\"1.1\"\n"
                         " width=\"%upx\" height=\"%upx\"\n"
                         " viewBox=\"0 0 %u %u\"\n"
                         " xmlns=\"http://www.w3.org/2000/svg\" shape-rendering=\"crispEdges\"\n"
                         " stroke-width=\"1\" text-rendering=\"geometricPrecision\">\n",
                         w, h, w, h);
    /* Now fill in the function pointers */
    outContext->line = SvgLine;
    outContext->dottedLine = SvgDottedLine;
    outContext->textL = SvgTextL;
    outContext->textC = SvgTextC;
    outContext->textR = SvgTextR;
    outContext->textWidth = SvgTextWidth;
    outContext->textHeight = SvgTextHeight;
    outContext->filledRectangle = SvgFilledRectangle;
    outContext->filledTriangle = SvgFilledTriangle;
    outContext->filledCircle = SvgFilledCircle;
    outContext->arc = SvgArc;
    outContext->dottedArc = SvgDottedArc;
    outContext->setPen = SvgSetPen;
    outContext->setBgPen = SvgSetBgPen;
    outContext->setFontSize = SvgSetFontSize;
    outContext->close = SvgClose;
    return TRUE;
}
SvgLine()
void SvgLine (struct ADrawTag * ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
Definition at line 274 of file mscgen_svg_out.c.
{
    fprintf(getSvgFile(ctx),
            "<line x1=\"%u\" y1=\"%u\" x2=\"%u\" y2=\"%u\" stroke=\"%s\"/>\n",
            x1, y1, x2, y2, getSvgPen(ctx));
}
References getSvgFile(), getSvgPen(), x1, x2, y1, and y2.
Referenced by SvgInit().
svgRect()
static void svgRect (struct ADrawTag * ctx, const char * colour, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2) [static]
Definition at line 203 of file mscgen_svg_out.c.
{
    fprintf(getSvgFile(ctx),
            "<polygon fill=\"%s\" points=\"%u,%u %u,%u %u,%u %u,%u\"/>\n",
            colour,
            x1, y1,
            x2, y1,
            x2, y2,
            x1, y2);
}
References getSvgFile(), x1, x2, y1, and y2.
Referenced by SvgFilledRectangle(), SvgTextC(), SvgTextL(), and SvgTextR().
SvgSetBgPen()
void SvgSetBgPen (struct ADrawTag * ctx, ADrawColour col)
Definition at line 457 of file mscgen_svg_out.c.
{
    static char colCmd[10];
    getSvgCtx(ctx)->penBgColName = svgColour(col);
    if(getSvgCtx(ctx)->penBgColName == NULL)
    {
        /* Print the RGB value into the local storage */
        sprintf(colCmd, "#%06X", col);
        /* Now set the colour name to the local store */
        getSvgCtx(ctx)->penBgColName = colCmd;
    }
}
References getSvgCtx(), SvgContextTag::penBgColName, and svgColour().
Referenced by SvgInit().
SvgSetFontSize()
void SvgSetFontSize (struct ADrawTag * ctx, ADrawFontSize size)
Definition at line 474 of file mscgen_svg_out.c.
{
    SvgContext *context = getSvgCtx(ctx);
    switch(size)
    {
        case ADRAW_FONT_TINY:
            context->fontPoints = 8;
            break;
        case ADRAW_FONT_SMALL:
            context->fontPoints = 12;
            break;
        default:
            assert(0);
    }
}
References ADRAW_FONT_SMALL, ADRAW_FONT_TINY, SvgContextTag::fontPoints, getSvgCtx(), and size.
Referenced by SvgInit().
SvgSetPen()
void SvgSetPen (struct ADrawTag * ctx, ADrawColour col)
Definition at line 440 of file mscgen_svg_out.c.
{
    static char colCmd[10];
    getSvgCtx(ctx)->penColName = svgColour(col);
    if(getSvgCtx(ctx)->penColName == NULL)
    {
        /* Print the RGB value into the local storage */
        sprintf(colCmd, "#%06X", col);
        /* Now set the colour name to the local store */
        getSvgCtx(ctx)->penColName = colCmd;
    }
}
References getSvgCtx(), SvgContextTag::penColName, and svgColour().
Referenced by SvgInit().
SvgTextC()
void SvgTextC (struct ADrawTag * ctx, unsigned int x, unsigned int y, const char * string)
Definition at line 339 of file mscgen_svg_out.c.
{
    SvgContext *context = getSvgCtx(ctx);
    unsigned int hw = SvgTextWidth(ctx, string) / 2;
    svgRect(ctx, getSvgBgPen(ctx), x - (hw + 2), y - SvgTextHeight(ctx) + 1, x + hw, y - 1);
    y += getSpace(ctx, SvgHelvetica.descender);
    fprintf(getSvgFile(ctx),
            "<text x=\"%u\" y=\"%u\" textLength=\"%u\" font-family=\"Helvetica\" font-size=\"%u\" fill=\"%s\" text-anchor=\"middle\">\n\n",
            x, y, SvgTextWidth(ctx, string), context->fontPoints, context->penColName);
    writeEscaped(ctx, string);
    fprintf(getSvgFile(ctx), "\n</text>\n");
}
References SvgCharMetric::descender, SvgContextTag::fontPoints, getSpace(), getSvgBgPen(), getSvgCtx(), getSvgFile(), SvgContextTag::penColName, SvgHelvetica, svgRect(), SvgTextHeight(), SvgTextWidth(), writeEscaped(), x, and y.
Referenced by SvgInit().
SvgTextHeight()
int SvgTextHeight (struct ADrawTag * ctx)
Definition at line 268 of file mscgen_svg_out.c.
{
    return getSpace(ctx, SvgHelvetica.ascender - SvgHelvetica.descender);
}
References SvgCharMetric::ascender, SvgCharMetric::descender, getSpace(), and SvgHelvetica.
Referenced by SvgInit(), SvgTextC(), SvgTextL(), and SvgTextR().
SvgTextL()
void SvgTextL (struct ADrawTag * ctx, unsigned int x, unsigned int y, const char * string)
Definition at line 318 of file mscgen_svg_out.c.
{
    SvgContext *context = getSvgCtx(ctx);
    svgRect(ctx, getSvgBgPen(ctx), x - (SvgTextWidth(ctx, string) + 2), y - SvgTextHeight(ctx) + 1, x, y - 1);
    y += getSpace(ctx, SvgHelvetica.descender);
    fprintf(getSvgFile(ctx),
            "<text x=\"%u\" y=\"%u\" textLength=\"%u\" font-family=\"Helvetica\" font-size=\"%u\" fill=\"%s\" text-anchor=\"end\">\n",
            x, y, SvgTextWidth(ctx, string), context->fontPoints, context->penColName);
    writeEscaped(ctx, string);
    fprintf(getSvgFile(ctx), "\n</text>\n");
}
References SvgCharMetric::descender, SvgContextTag::fontPoints, getSpace(), getSvgBgPen(), getSvgCtx(), getSvgFile(), SvgContextTag::penColName, SvgHelvetica, svgRect(), SvgTextHeight(), SvgTextWidth(), writeEscaped(), x, and y.
Referenced by SvgInit().
SvgTextR()
void SvgTextR (struct ADrawTag * ctx, unsigned int x, unsigned int y, const char * string)
Definition at line 299 of file mscgen_svg_out.c.
{
    SvgContext *context = getSvgCtx(ctx);
    svgRect(ctx, getSvgBgPen(ctx), x - 2, y - SvgTextHeight(ctx) + 1, x + SvgTextWidth(ctx, string), y - 1);
    y += getSpace(ctx, SvgHelvetica.descender);
    fprintf(getSvgFile(ctx),
            "<text x=\"%u\" y=\"%u\" textLength=\"%u\" font-family=\"Helvetica\" font-size=\"%u\" fill=\"%s\">\n",
            x - 1, y, SvgTextWidth(ctx, string), context->fontPoints, context->penColName);
    writeEscaped(ctx, string);
    fprintf(getSvgFile(ctx), "\n</text>\n");
}
References SvgCharMetric::descender, SvgContextTag::fontPoints, getSpace(), getSvgBgPen(), getSvgCtx(), getSvgFile(), SvgContextTag::penColName, SvgHelvetica, svgRect(), SvgTextHeight(), SvgTextWidth(), writeEscaped(), x, and y.
Referenced by SvgInit().
SvgTextWidth()
unsigned int SvgTextWidth (struct ADrawTag * ctx, const char * string)
Definition at line 248 of file mscgen_svg_out.c.
{
    unsigned long width = 0;
    while(*string != '\0')
    {
        int i = *string & 0xff;
        unsigned long w = SvgHelvetica.widths[i];
        /* Ignore undefined characters */
        width += w > 0 ? w : 0;
        string++;
    }
    return getSpace(ctx, width);
}
References getSpace(), SvgHelvetica, w, and SvgCharMetric::widths.
Referenced by SvgInit(), SvgTextC(), SvgTextL(), and SvgTextR().
writeEscaped()
static void writeEscaped (struct ADrawTag * ctx, const char * string) [static]
Write out a line of text, escaping special characters.
Definition at line 169 of file mscgen_svg_out.c.
{
    FILE *f = getSvgFile(ctx);
    while(*string != '\0')
    {
        unsigned int code, bytes;
        switch(*string)
        {
            case '<': fprintf(f, "&lt;"); break;
            case '>': fprintf(f, "&gt;"); break;
            case '"': fprintf(f, "&quot;"); break;
            case '&': fprintf(f, "&amp;"); break;
            default:
                if(Utf8Decode(string, &code, &bytes))
                {
                    fprintf(f, "&#x%x;", code);
                    string += bytes - 1;
                }
                else
                {
                    fputc(*string, f);
                }
                break;
        }
        string++;
    }
}
References f, getSvgFile(), and Utf8Decode().
Referenced by SvgTextC(), SvgTextL(), and SvgTextR().
Variable Documentation
SvgHelvetica
const SvgCharMetric SvgHelvetica [static]
Helvetica character widths. This gives the width of each character is 1/1000ths of a point. The values are taken from the Adobe Font Metric file for Hevletica.
Definition at line 64 of file mscgen_svg_out.c.
Referenced by SvgTextC(), SvgTextHeight(), SvgTextL(), SvgTextR(), and SvgTextWidth().