doxygen/build/doxygen/libmscgen/mscgen_adraw.c File Reference
#include `mscgen_config.h`
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include `mscgen_adraw_int.h`
Functions
Boolean ADrawOpen (unsigned int w, unsigned int h, const char *file, const char *fontName, ADrawOutputType type, struct ADrawTag *outContext)
ADrawColour ADrawGetColour (const char *colour)
void ADrawComputeArcPoint (float cx, float cy, float w, float h, float degrees, unsigned int *x, unsigned int *y)
Function Documentation
ADrawComputeArcPoint()
void ADrawComputeArcPoint (float cx, float cy, float w, float h, float degrees, unsigned int * x, unsigned int * y)
Compute the position of a point on an arc. This allows co-ordinates on arc drawn using arc() or dottedArc() to be computed. The centre and bounding box for the arc are supplied as well as an angular offset.
Parameters
 in cx Center of the arc.
 in cy Center of the arc.
 in w Arc x-diameter (width).
 in h Arc y-diameter (height).
 in degrees Position on the arc to be returned.
 in,out x Pointer to fill with x coordinate.
 in,out y Pointer to fill with y coordinate.
Definition at line 131 of file mscgen_adraw.c.
{
    float rad = (float)((degrees * M_PI) / 180.0f);
    *x = (unsigned int)round(cx + ((w / 2.0f) * cos(rad)));
    *y = (unsigned int)round(cy + ((h / 2.0f) * sin(rad)));
}
References cx, cy, h, M_PI, w, x, and y.
Referenced by arcLine().
ADrawGetColour()
ADrawColour ADrawGetColour (const char * colour)
Given a string name for a colour, return the corresponding ADrawColour.
Parameters
 in colour The string representation of the colour that is sought.
Definition at line 71 of file mscgen_adraw.c.
{
    assert(colour != NULL);
    /* Check if an RGB value has been specified */
    if(*colour == '#')
    {
        unsigned int c = ADRAW_COL_BLACK;
        if(sscanf(&colour[1], "%x", &c) == 1)
        {
            return (ADrawColour)c;
        }
    }
    else /* Check for name matches */
    {
        static const struct
        {
            char *name;
            ADrawColour col;
        }
        colourMap[] =
        {
            { "WHITE", ADRAW_COL_WHITE },
            { "BLACK", ADRAW_COL_BLACK },
            { "RED", ADRAW_COL_RED },
            { "ORANGE", ADRAW_COL_ORANGE },
            { "YELLOW", ADRAW_COL_YELLOW },
            { "GREEN", ADRAW_COL_GREEN },
            { "BLUE", ADRAW_COL_BLUE },
            { "INDIGO", ADRAW_COL_INDIGO },
            { "VIOLET", ADRAW_COL_VIOLET },
            { "SILVER", ADRAW_COL_SILVER },
            { "LIME", ADRAW_COL_LIME },
            { "GRAY", ADRAW_COL_GRAY },
            { "OLIVE", ADRAW_COL_OLIVE },
            { "MAROON", ADRAW_COL_MAROON },
            { "NAVY", ADRAW_COL_NAVY },
            { "PURPLE", ADRAW_COL_PURPLE },
            { "TEAL", ADRAW_COL_TEAL },
            { "FUCHSIA", ADRAW_COL_FUCHSIA },
            { "AQUA", ADRAW_COL_AQUA }
        };
        unsigned int t;
        for(t = 0; t < sizeof(colourMap) / sizeof(colourMap[0]); t++)
        {
            if(strcasecmp(colour, colourMap[t].name) == 0)
            {
                return colourMap[t].col;
            }
        }
    }
    /* Default to black if all else failed */
    return ADRAW_COL_BLACK;
}
References ADRAW_COL_AQUA, ADRAW_COL_BLACK, ADRAW_COL_BLUE, ADRAW_COL_FUCHSIA, ADRAW_COL_GRAY, ADRAW_COL_GREEN, ADRAW_COL_INDIGO, ADRAW_COL_LIME, ADRAW_COL_MAROON, ADRAW_COL_NAVY, ADRAW_COL_OLIVE, ADRAW_COL_ORANGE, ADRAW_COL_PURPLE, ADRAW_COL_RED, ADRAW_COL_SILVER, ADRAW_COL_TEAL, ADRAW_COL_VIOLET, ADRAW_COL_WHITE, ADRAW_COL_YELLOW, c, and setup::name.
Referenced by arcBox(), arcLine(), arcText(), entityText(), and mscgen_generate().
ADrawOpen()
Boolean ADrawOpen (unsigned int w, unsigned int h, const char * file, const char * fontName, ADrawOutputType type, struct ADrawTag * outContext)
Create a new drawing context. This will create a drawing context with some dimensions, and some format. After this has been called, the function pointers in the returned structure can be called together with a pointer to the structure itself to cause image functions to be executed.
Parameters
 in w The width of the output image.
 in h The height of the output image.
 in file The file to which the image should be written.
 in fontName The name of the font to use for rendering.
 in type The output type to generate.
 in,out *outContext Pointer to an ADraw structure to populate with values.
Return values
Boolean On error, FALSE will be returned.
Definition at line 38 of file mscgen_adraw.c.
{
    assert(outContext);
    switch(type)
    {
        case ADRAW_FMT_NULL:
            return NullInit(outContext);
        case ADRAW_FMT_PNG:
#if !defined(REMOVE_PNG_OUTPUT)
            return GdoInit(w, h, file, fontName, outContext);
#else
            fprintf(stderr, "Built with REMOVE_PNG_OUTPUT; PNG output is not supported\n");
            return FALSE;
#endif
        case ADRAW_FMT_EPS:
            return PsInit(w, h, file, outContext);
        case ADRAW_FMT_SVG:
            return SvgInit(w, h, file, outContext);
        default:
            return FALSE;
    }
}
References ADRAW_FMT_EPS, ADRAW_FMT_NULL, ADRAW_FMT_PNG, ADRAW_FMT_SVG, FALSE, caseconvert::file, GdoInit(), h, NullInit(), PsInit(), SvgInit(), and w.
Referenced by mscgen_generate().