doxygen/build/doxygen/testing/094_old_style_fortran_routines.f90 File Reference
Functions/Subroutines
subroutine use_tst2
subroutine use_tst
subroutine use_tst1 (routine_interface)
subroutine a (i)
subroutine b (i)
program tst
Function/Subroutine Documentation
a()
subroutine a (integer i)
Definition at line 21 of file 094_old_style_fortran_routines.f90.
  integer i
    write(*,*) "I'm A"
b()
subroutine b (integer i)
Definition at line 26 of file 094_old_style_fortran_routines.f90.
  integer i
    write(*,*) "I'm B"
tst()
program tst
Definition at line 31 of file 094_old_style_fortran_routines.f90.
References use_tst(), use_tst1(), and use_tst2().
use_tst()
subroutine use_tst
Definition at line 11 of file 094_old_style_fortran_routines.f90.
  write(*,*) "I'm use_tst"
  call inner
use_tst1()
subroutine use_tst1 (external routine_interface)
Definition at line 16 of file 094_old_style_fortran_routines.f90.
  external routine_interface
  call routine_interface(7)
Referenced by tst().
use_tst2()
subroutine use_tst2
Definition at line 6 of file 094_old_style_fortran_routines.f90.
  write(*,*) "I'm use_tst2"
  call inner2
Referenced by tst().