FileDefImpl Class Reference
Public Member Functions
FileDefImpl (const QCString &p, const QCString &n, const QCString &ref=QCString(), const QCString &dn=QCString())
virtual ~FileDefImpl ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString name () const
virtual QCString displayName (bool=TRUE) const
virtual QCString fileName () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual QCString getSourceFileBase () const
virtual QCString includeName () const
virtual QCString includeDependencyGraphFileName () const
virtual QCString includedByDependencyGraphFileName () const
virtual QCString absFilePath () const
virtual const QCString & docName () const
virtual bool isSource () const
virtual bool isDocumentationFile () const
virtual const Definition * getSourceDefinition (int lineNr) const
virtual const MemberDef * getSourceMember (int lineNr) const
virtual QCString getPath () const
virtual QCString getVersion () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool isIncluded (const QCString &name) const
virtual PackageDef * packageDef () const
virtual DirDef * getDirDef () const
virtual const LinkedRefMap< const NamespaceDef > & getUsedNamespaces () const
virtual const LinkedRefMap< const ClassDef > & getUsedClasses () const
virtual const IncludeInfoList & includeFileList () const
virtual const IncludeInfoList & includedByFileList () const
virtual void getAllIncludeFilesRecursively (StringVector &incFiles) const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberGroupList & getMemberGroups () const
virtual const NamespaceLinkedRefMap & getNamespaces () const
virtual const ConceptLinkedRefMap & getConcepts () const
virtual const ClassLinkedRefMap & getClasses () const
virtual QCString title () const
virtual bool hasDetailedDescription () const
virtual QCString fileVersion () const
virtual bool subGrouping () const
virtual void countMembers ()
virtual int numDocMembers () const
virtual int numDecMembers () const
virtual void addSourceRef (int line, const Definition *d, const MemberDef *md)
virtual void writeDocumentation (OutputList &ol)
virtual void writeMemberPages (OutputList &ol)
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const
virtual void writeSummaryLinks (OutputList &ol) const
virtual void writeTagFile (TextStream &t)
virtual void writeSourceHeader (OutputList &ol)
virtual void writeSourceBody (OutputList &ol, ClangTUParser *clangParser)
virtual void writeSourceFooter (OutputList &ol)
virtual void parseSource (ClangTUParser *clangParser)
virtual void setDiskName (const QCString &name)
virtual void insertMember (MemberDef *md)
virtual void insertClass (const ClassDef *cd)
virtual void insertConcept (const ConceptDef *cd)
virtual void insertNamespace (const NamespaceDef *nd)
virtual void computeAnchors ()
virtual void setPackageDef (PackageDef *pd)
virtual void setDirDef (DirDef *dd)
virtual void addUsingDirective (const NamespaceDef *nd)
virtual void addUsingDeclaration (const ClassDef *cd)
virtual void combineUsingRelations ()
virtual bool generateSourceFile () const
virtual void sortMemberLists ()
virtual void addIncludeDependency (const FileDef *fd, const QCString &incName, bool local, bool imported)
virtual void addIncludedByDependency (const FileDef *fd, const QCString &incName, bool local, bool imported)
virtual void addMembersToMemberGroup ()
virtual void distributeMemberGroupDocumentation ()
virtual void findSectionsInDocumentation ()
virtual void addIncludedUsingDirectives (FileDefSet &visitedFiles)
virtual void addListReferences ()
FileDefImpl (const QCString &p, const QCString &n, const QCString &ref=QCString(), const QCString &dn=QCString())
virtual ~FileDefImpl ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString name () const
virtual QCString displayName (bool=TRUE) const
virtual QCString fileName () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual QCString getSourceFileBase () const
virtual QCString includeName () const
virtual QCString includeDependencyGraphFileName () const
virtual QCString includedByDependencyGraphFileName () const
virtual QCString absFilePath () const
virtual const QCString & docName () const
virtual bool isSource () const
virtual bool isDocumentationFile () const
virtual const Definition * getSourceDefinition (int lineNr) const
virtual const MemberDef * getSourceMember (int lineNr) const
virtual QCString getPath () const
virtual QCString getVersion () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool isIncluded (const QCString &name) const
virtual PackageDef * packageDef () const
virtual DirDef * getDirDef () const
virtual const LinkedRefMap< const NamespaceDef > & getUsedNamespaces () const
virtual const LinkedRefMap< const ClassDef > & getUsedClasses () const
virtual const IncludeInfoList & includeFileList () const
virtual const IncludeInfoList & includedByFileList () const
virtual void getAllIncludeFilesRecursively (StringVector &incFiles) const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberGroupList & getMemberGroups () const
virtual const NamespaceLinkedRefMap & getNamespaces () const
virtual const ConceptLinkedRefMap & getConcepts () const
virtual const ClassLinkedRefMap & getClasses () const
virtual QCString title () const
virtual bool hasDetailedDescription () const
virtual QCString fileVersion () const
virtual bool subGrouping () const
virtual void countMembers ()
virtual int numDocMembers () const
virtual int numDecMembers () const
virtual void addSourceRef (int line, const Definition *d, const MemberDef *md)
virtual void writeDocumentation (OutputList &ol)
virtual void writeMemberPages (OutputList &ol)
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const
virtual void writeSummaryLinks (OutputList &ol) const
virtual void writeTagFile (TextStream &t)
virtual void writeSourceHeader (OutputList &ol)
virtual void writeSourceBody (OutputList &ol, ClangTUParser *clangParser)
virtual void writeSourceFooter (OutputList &ol)
virtual void parseSource (ClangTUParser *clangParser)
virtual void setDiskName (const QCString &name)
virtual void insertMember (MemberDef *md)
virtual void insertClass (const ClassDef *cd)
virtual void insertConcept (const ConceptDef *cd)
virtual void insertNamespace (const NamespaceDef *nd)
virtual void computeAnchors ()
virtual void setPackageDef (PackageDef *pd)
virtual void setDirDef (DirDef *dd)
virtual void addUsingDirective (const NamespaceDef *nd)
virtual void addUsingDeclaration (const ClassDef *cd)
virtual void combineUsingRelations ()
virtual bool generateSourceFile () const
virtual void sortMemberLists ()
virtual void addIncludeDependency (const FileDef *fd, const QCString &incName, bool local, bool imported)
virtual void addIncludedByDependency (const FileDef *fd, const QCString &incName, bool local, bool imported)
virtual void addMembersToMemberGroup ()
virtual void distributeMemberGroupDocumentation ()
virtual void findSectionsInDocumentation ()
virtual void addIncludedUsingDirectives (FileDefSet &visitedFiles)
virtual void addListReferences ()
Private Member Functions
void acquireFileVersion ()
void addMemberToList (MemberListType lt, MemberDef *md)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void writeIncludeFiles (OutputList &ol)
void writeIncludeGraph (OutputList &ol)
void writeIncludedByGraph (OutputList &ol)
void writeMemberGroups (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void writeSourceLink (OutputList &ol)
void writeNamespaceDeclarations (OutputList &ol, const QCString &title, bool isConstantGroup)
void writeClassDeclarations (OutputList &ol, const QCString &title, const ClassLinkedRefMap &list)
void writeConcepts (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void writeClassesToTagFile (TextStream &t, const ClassLinkedRefMap &list)
void acquireFileVersion ()
void addMemberToList (MemberListType lt, MemberDef *md)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void writeIncludeFiles (OutputList &ol)
void writeIncludeGraph (OutputList &ol)
void writeIncludedByGraph (OutputList &ol)
void writeMemberGroups (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void writeSourceLink (OutputList &ol)
void writeNamespaceDeclarations (OutputList &ol, const QCString &title, bool isConstantGroup)
void writeClassDeclarations (OutputList &ol, const QCString &title, const ClassLinkedRefMap &list)
void writeConcepts (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void writeClassesToTagFile (TextStream &t, const ClassLinkedRefMap &list)
Private Attributes
IncludeInfoMap m_includeMap
IncludeInfoList m_includeList
IncludeInfoMap m_includedByMap
IncludeInfoList m_includedByList
LinkedRefMap< const NamespaceDef > m_usingDirList
LinkedRefMap< const ClassDef > m_usingDeclList
QCString m_path
QCString m_filePath
QCString m_inclDepFileName
QCString m_inclByDepFileName
QCString m_outputDiskName
QCString m_fileName
QCString m_docname
DefinitionLineMap m_srcDefMap
MemberDefLineMap m_srcMemberMap
bool m_isSource
QCString m_fileVersion
PackageDef * m_package
DirDef * m_dir
MemberLists m_memberLists
MemberGroupList m_memberGroups
NamespaceLinkedRefMap m_namespaces
ClassLinkedRefMap m_classes
ClassLinkedRefMap m_interfaces
ClassLinkedRefMap m_structs
ClassLinkedRefMap m_exceptions
ConceptLinkedRefMap m_concepts
bool m_subGrouping
Additional Inherited Members
Detailed Description
Definition at line 58 of file filedef.cpp.
Constructor & Destructor Documentation
FileDefImpl() [1/2]
FileDefImpl::FileDefImpl (const QCString & p, const QCString & nm, const QCString & lref = QCString(), const QCString & dn = QCString())
create a new file definition, where p is the file path, nm the file name, and lref is an HTML anchor name if the file was read from a tag file or 0 otherwise
Definition at line 231 of file filedef.cpp.
   : DefinitionMixin(QCString(p)+nm,1,1,nm,0,0,!p.isEmpty())
{
  m_path=p;
  m_filePath=m_path+nm;
  m_fileName=nm;
  setReference(lref);
  setDiskName(!dn.isEmpty() ? dn : nm);
  m_package = 0;
  m_isSource = guessSection(nm)==Entry::SOURCE_SEC;
  m_docname = nm;
  m_dir = 0;
  if (Config_getBool(FULL_PATH_NAMES))
  {
    m_docname.prepend(stripFromPath(m_path));
  }
  setLanguage(getLanguageFromFileName(name()));
  acquireFileVersion();
  m_subGrouping=Config_getBool(SUBGROUPING);
}
References acquireFileVersion(), Config_getBool, getLanguageFromFileName(), guessSection(), QCString::isEmpty(), m_dir, m_docname, m_fileName, m_filePath, m_isSource, m_package, m_path, m_subGrouping, name(), p, QCString::prepend(), setDiskName(), DefinitionMixin< FileDef >::setLanguage(), DefinitionMixin< FileDef >::setReference(), Entry::SOURCE_SEC, and stripFromPath().
 FileDefImpl() [1/2]
FileDefImpl::~FileDefImpl () [virtual]
destroy the file definition
Definition at line 254 of file filedef.cpp.
{
}
FileDefImpl() [2/2]
FileDefImpl::FileDefImpl (const QCString & p, const QCString & n, const QCString & ref = QCString(), const QCString & dn = QCString())
 FileDefImpl() [2/2]
virtual FileDefImpl::~FileDefImpl () [virtual]
Member Function Documentation
absFilePath() [1/2]
virtual QCString FileDefImpl::absFilePath () const [inline], [virtual]
Returns the absolute path including the file name.
Implements FileDef.
Definition at line 76 of file filedef.cpp.
{ return m_filePath; }
References m_filePath.
Referenced by parseSource(), and writeSourceBody().
absFilePath() [2/2]
virtual QCString FileDefImpl::absFilePath () const [inline], [virtual]
Returns the absolute path including the file name.
Implements FileDef.
Definition at line 76 of file filedef.cpp.
{ return m_filePath; }
References m_filePath.
acquireFileVersion() [1/2]
void FileDefImpl::acquireFileVersion () [private]
Definition at line 1523 of file filedef.cpp.
{
  QCString vercmd = Config_getString(FILE_VERSION_FILTER);
  if (!vercmd.isEmpty() && !m_filePath.isEmpty() &&
      m_filePath!="generated" && m_filePath!="graph_legend.dox")
  {
    msg("Version of %s : ",qPrint(m_filePath));
    QCString cmd = vercmd+" \""+m_filePath+"\"";
    Debug::print(Debug::ExtCmd,0,"Executing popen(`%s`)\n",qPrint(cmd));
    FILE *f=Portable::popen(cmd,"r");
    if (!f)
    {
      err("could not execute %s\n",qPrint(vercmd));
      return;
    }
    const int bufSize=1024;
    char buf[bufSize];
    int numRead = static_cast<int>(fread(buf,1,bufSize-1,f));
    Portable::pclose(f);
    if (numRead>0 && numRead<bufSize)
    {
      buf[numRead]='\0';
      m_fileVersion=QCString(buf,numRead).stripWhiteSpace();
      if (!m_fileVersion.isEmpty())
      {
        msg("%s\n",qPrint(m_fileVersion));
        return;
      }
    }
    msg("no version available\n");
  }
}
References Config_getString, err(), Debug::ExtCmd, f, QCString::isEmpty(), m_filePath, m_fileVersion, msg(), Portable::pclose(), Portable::popen(), Debug::print(), qPrint(), and QCString::stripWhiteSpace().
Referenced by FileDefImpl().
acquireFileVersion() [2/2]
void FileDefImpl::acquireFileVersion () [private]
addIncludedByDependency() [1/2]
void FileDefImpl::addIncludedByDependency (const FileDef * fd, const QCString & incName, bool local, bool imported) [virtual]
Implements FileDef.
Definition at line 1428 of file filedef.cpp.
{
  //printf("FileDefImpl::addIncludedByDependency(%p,%s,%d)\n",fd,incName,local);
  QCString iName = fd ? fd->absFilePath() : incName;
  if (!iName.isEmpty() && m_includedByMap.find(iName.str())==m_includedByMap.end())
  {
    m_includedByList.emplace_back(fd,incName,local,imported);
    m_includedByMap.insert(std::make_pair(iName.str(),&m_includedByList.back()));
  }
}
References FileDef::absFilePath(), QCString::isEmpty(), m_includedByList, m_includedByMap, and QCString::str().
addIncludedByDependency() [2/2]
virtual void FileDefImpl::addIncludedByDependency (const FileDef * fd, const QCString & incName, bool local, bool imported) [virtual]
Implements FileDef.
addIncludeDependency() [1/2]
void FileDefImpl::addIncludeDependency (const FileDef * fd, const QCString & incName, bool local, bool imported) [virtual]
Implements FileDef.
Definition at line 1369 of file filedef.cpp.
{
  //printf("FileDefImpl::addIncludeDependency(%p,%s,%d)\n",fd,incName,local);
  QCString iName = fd ? fd->absFilePath() : incName;
  if (!iName.isEmpty() && m_includeMap.find(iName.str())==m_includeMap.end())
  {
    m_includeList.emplace_back(fd,incName,local,imported);
    m_includeMap.insert(std::make_pair(iName.str(),&m_includeList.back()));
  }
}
References FileDef::absFilePath(), QCString::isEmpty(), m_includeList, m_includeMap, and QCString::str().
addIncludeDependency() [2/2]
virtual void FileDefImpl::addIncludeDependency (const FileDef * fd, const QCString & incName, bool local, bool imported) [virtual]
Implements FileDef.
addIncludedUsingDirectives() [1/2]
void FileDefImpl::addIncludedUsingDirectives (FileDefSet & visitedFiles) [virtual]
Implements FileDef.
Definition at line 1380 of file filedef.cpp.
{
  if (visitedFiles.find(this)!=visitedFiles.end()) return; // file already processed
  visitedFiles.insert(this);
  //printf("(FileDefImpl::addIncludedUsingDirectives for file %s\n",qPrint(name()));
  if (!m_includeList.empty()) // file contains #includes
  {
    {
      for (const auto &ii : m_includeList) // foreach #include...
      {
        if (ii.fileDef) // ...that is a known file
        {
          // recurse into this file
          const_cast<FileDef*>(ii.fileDef)->addIncludedUsingDirectives(visitedFiles);
        }
      }
    }
    {
      // iterate through list from last to first
      for (auto ii_it = m_includeList.rbegin(); ii_it!=m_includeList.rend(); ++ii_it)
      {
        const auto &ii = *ii_it;
        if (ii.fileDef && ii.fileDef!=this)
        {
          // add using directives
          auto unl = ii.fileDef->getUsedNamespaces();
          for (auto it = unl.rbegin(); it!=unl.rend(); ++it)
          {
            const auto *nd = *it;
            //printf(" adding using directive for %s\n",qPrint(nd->qualifiedName()));
            m_usingDirList.prepend(nd->qualifiedName(),nd);
          }
          // add using declarations
          auto udl = ii.fileDef->getUsedClasses();
          for (auto it = udl.rbegin(); it!=udl.rend(); ++it)
          {
            const auto *cd = *it;
            m_usingDeclList.prepend(cd->qualifiedName(),cd);
          }
        }
      }
    }
  }
  //printf(") end FileDefImpl::addIncludedUsingDirectives for file %s\n",qPrint(name()));
}
References addIncludedUsingDirectives(), m_includeList, m_usingDeclList, m_usingDirList, and LinkedRefMap< T, Hash, KeyEqual, Map >::prepend().
Referenced by addIncludedUsingDirectives().
addIncludedUsingDirectives() [2/2]
virtual void FileDefImpl::addIncludedUsingDirectives (FileDefSet & visitedFiles) [virtual]
Implements FileDef.
addListReferences() [1/2]
void FileDefImpl::addListReferences () [virtual]
Implements FileDef.
Definition at line 1458 of file filedef.cpp.
{
  {
    const RefItemVector &xrefItems = xrefListItems();
    addRefItem(xrefItems,
               getOutputFileBase(),
               theTranslator->trFile(TRUE,TRUE),
               getOutputFileBase(),name(),
               QCString(),
               0
              );
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->addListReferences(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_documentationLists)
    {
      ml->addListReferences(this);
    }
  }
}
References addRefItem(), getOutputFileBase(), m_memberGroups, m_memberLists, MemberListType_documentationLists, name(), theTranslator, Translator::trFile(), TRUE, and DefinitionMixin< FileDef >::xrefListItems().
addListReferences() [2/2]
virtual void FileDefImpl::addListReferences () [virtual]
Implements FileDef.
addMembersToMemberGroup() [1/2]
void FileDefImpl::addMembersToMemberGroup () [virtual]
Implements FileDef.
Definition at line 1195 of file filedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_declarationLists)
    {
      ::addMembersToMemberGroup(ml.get(),&m_memberGroups,this);
    }
  }
  // add members inside sections to their groups
  for (const auto &mg : m_memberGroups)
  {
    if (mg->allMembersInSameSection() && m_subGrouping)
    {
      //printf("----> addToDeclarationSection(%s)\n",qPrint(mg->header()));
      mg->addToDeclarationSection();
    }
  }
}
References addMembersToMemberGroup(), m_memberGroups, m_memberLists, m_subGrouping, and MemberListType_declarationLists.
Referenced by addMembersToMemberGroup().
addMembersToMemberGroup() [2/2]
virtual void FileDefImpl::addMembersToMemberGroup () [virtual]
Implements FileDef.
addMemberToList() [1/2]
void FileDefImpl::addMemberToList (MemberListType lt, MemberDef * md) [private]
Definition at line 1580 of file filedef.cpp.
{
  bool sortBriefDocs = Config_getBool(SORT_BRIEF_DOCS);
  bool sortMemberDocs = Config_getBool(SORT_MEMBER_DOCS);
  const auto &ml = m_memberLists.get(lt,MemberListContainer::File);
  ml->setNeedsSorting(
       ((ml->listType()&MemberListType_declarationLists) && sortBriefDocs) ||
       ((ml->listType()&MemberListType_documentationLists) && sortMemberDocs));
  ml->push_back(md);
  if (ml->listType()&MemberListType_declarationLists)
  {
    MemberDefMutable *mdm = toMemberDefMutable(md);
    if (mdm)
    {
      mdm->setSectionList(this,ml.get());
    }
  }
}
References Config_getBool, File, MemberLists::get(), m_memberLists, MemberListType_declarationLists, MemberListType_documentationLists, MemberDefMutable::setSectionList(), and toMemberDefMutable().
Referenced by insertMember().
addMemberToList() [2/2]
void FileDefImpl::addMemberToList (MemberListType lt, MemberDef * md) [private]
addSourceRef() [1/2]
void FileDefImpl::addSourceRef (int line, const Definition * d, const MemberDef * md) [virtual]
Implements FileDef.
Definition at line 1325 of file filedef.cpp.
{
  //printf("FileDefImpl::addSourceDef(%d,%p,%p)\n",line,d,md);
  if (d)
  {
    m_srcDefMap.insert(std::make_pair(line,d));
    if (md) m_srcMemberMap.insert(std::make_pair(line,md));
    //printf("Adding member %s with anchor %s at line %d to file %s\n",
    // md?qPrint(md->name()):"<none>",md?qPrint(md->anchor()):"<none>",line,qPrint(name()));
  }
}
References m_srcDefMap, and m_srcMemberMap.
addSourceRef() [2/2]
virtual void FileDefImpl::addSourceRef (int line, const Definition * d, const MemberDef * md) [virtual]
Implements FileDef.
addUsingDeclaration() [1/2]
void FileDefImpl::addUsingDeclaration (const ClassDef * cd) [virtual]
Implements FileDef.
Definition at line 1364 of file filedef.cpp.
{
  m_usingDeclList.add(cd->qualifiedName(),cd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), m_usingDeclList, and Definition::qualifiedName().
Referenced by combineUsingRelations().
addUsingDeclaration() [2/2]
virtual void FileDefImpl::addUsingDeclaration (const ClassDef * cd) [virtual]
Implements FileDef.
addUsingDirective() [1/2]
void FileDefImpl::addUsingDirective (const NamespaceDef * nd) [virtual]
Implements FileDef.
Definition at line 1352 of file filedef.cpp.
{
  m_usingDirList.add(nd->qualifiedName(),nd);
  //printf("%p: FileDefImpl::addUsingDirective: %s:%d\n",this,qPrint(name()),usingDirList->count());
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), m_usingDirList, and Definition::qualifiedName().
Referenced by combineUsingRelations().
addUsingDirective() [2/2]
virtual void FileDefImpl::addUsingDirective (const NamespaceDef * nd) [virtual]
Implements FileDef.
anchor() [1/2]
virtual QCString FileDefImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements FileDef.
Definition at line 71 of file filedef.cpp.
{ return QCString(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString FileDefImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements FileDef.
Definition at line 71 of file filedef.cpp.
{ return QCString(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
codeSymbolType() [1/2]
virtual CodeSymbolType FileDefImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 65 of file filedef.cpp.
{ return CodeSymbolType::Default; }
References Default.
codeSymbolType() [2/2]
virtual CodeSymbolType FileDefImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 65 of file filedef.cpp.
{ return CodeSymbolType::Default; }
References Default.
combineUsingRelations() [1/2]
void FileDefImpl::combineUsingRelations () [virtual]
Implements FileDef.
Definition at line 1485 of file filedef.cpp.
{
  LinkedRefMap<const NamespaceDef> usingDirList = m_usingDirList;
  NamespaceDefSet visitedNamespaces;
  for (auto &nd : usingDirList)
  {
    NamespaceDefMutable *ndm = toNamespaceDefMutable(nd);
    if (ndm)
    {
      ndm->combineUsingRelations(visitedNamespaces);
    }
  }
  for (auto &nd : usingDirList)
  {
    // add used namespaces of namespace nd to this namespace
    for (const auto &und : nd->getUsedNamespaces())
    {
      addUsingDirective(und);
    }
    // add used classes of namespace nd to this namespace
    for (const auto &ucd : nd->getUsedClasses())
    {
      addUsingDeclaration(ucd);
    }
  }
}
References addUsingDeclaration(), addUsingDirective(), NamespaceDefMutable::combineUsingRelations(), m_usingDirList, and toNamespaceDefMutable().
combineUsingRelations() [2/2]
virtual void FileDefImpl::combineUsingRelations () [virtual]
Implements FileDef.
computeAnchors() [1/2]
void FileDefImpl::computeAnchors () [virtual]
Compute the HTML anchor names for all members in the class
Implements FileDef.
Definition at line 275 of file filedef.cpp.
{
  MemberList *ml = getMemberList(MemberListType_allMembersList);
  if (ml) ml->setAnchors();
}
References getMemberList(), MemberListType_allMembersList, and MemberList::setAnchors().
computeAnchors() [2/2]
virtual void FileDefImpl::computeAnchors () [virtual]
Implements FileDef.
countMembers() [1/2]
void FileDefImpl::countMembers () [virtual]
Implements FileDef.
Definition at line 1722 of file filedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    ml->countDecMembers();
    ml->countDocMembers();
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->countDecMembers();
    mg->countDocMembers();
  }
}
References m_memberGroups, and m_memberLists.
countMembers() [2/2]
virtual void FileDefImpl::countMembers () [virtual]
Implements FileDef.
definitionType() [1/2]
virtual DefType FileDefImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements FileDef.
Definition at line 64 of file filedef.cpp.
{ return TypeFile; }
References Definition::TypeFile.
definitionType() [2/2]
virtual DefType FileDefImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements FileDef.
Definition at line 64 of file filedef.cpp.
{ return TypeFile; }
References Definition::TypeFile.
displayName() [1/2]
virtual QCString FileDefImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements FileDef.
Definition at line 68 of file filedef.cpp.
{ return name(); }
References name().
displayName() [2/2]
virtual QCString FileDefImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements FileDef.
Definition at line 68 of file filedef.cpp.
{ return name(); }
References name().
distributeMemberGroupDocumentation() [1/2]
void FileDefImpl::distributeMemberGroupDocumentation () [virtual]
Implements FileDef.
Definition at line 281 of file filedef.cpp.
{
  //printf("FileDefImpl::distributeMemberGroupDocumentation()\n");
  for (const auto &mg : m_memberGroups)
  {
    mg->distributeMemberGroupDocumentation();
  }
}
References m_memberGroups.
distributeMemberGroupDocumentation() [2/2]
virtual void FileDefImpl::distributeMemberGroupDocumentation () [virtual]
Implements FileDef.
docName() [1/2]
virtual const QCString & FileDefImpl::docName () const [inline], [virtual]
Returns the name as it is used in the documentation
Implements FileDef.
Definition at line 77 of file filedef.cpp.
{ return m_docname; }
References m_docname.
docName() [2/2]
virtual const QCString & FileDefImpl::docName () const [inline], [virtual]
Returns the name as it is used in the documentation
Implements FileDef.
Definition at line 77 of file filedef.cpp.
{ return m_docname; }
References m_docname.
endMemberDeclarations() [1/2]
void FileDefImpl::endMemberDeclarations (OutputList & ol) [private]
Definition at line 699 of file filedef.cpp.
{
  ol.endMemberSections();
}
References OutputList::endMemberSections().
Referenced by writeDocumentation().
endMemberDeclarations() [2/2]
void FileDefImpl::endMemberDeclarations (OutputList & ol) [private]
endMemberDocumentation() [1/2]
void FileDefImpl::endMemberDocumentation (OutputList & ol) [private]
Definition at line 713 of file filedef.cpp.
{
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.enable(OutputGenerator::Html);
    Doxygen::suppressDocWarnings = FALSE;
  }
}
References Config_getBool, OutputList::enable(), FALSE, OutputGenerator::Html, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
endMemberDocumentation() [2/2]
void FileDefImpl::endMemberDocumentation (OutputList & ol) [private]
fileName() [1/2]
virtual QCString FileDefImpl::fileName () const [inline], [virtual]
Implements FileDef.
Definition at line 69 of file filedef.cpp.
{ return m_fileName; }
References m_fileName.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
virtual QCString FileDefImpl::fileName () const [inline], [virtual]
Implements FileDef.
Definition at line 69 of file filedef.cpp.
{ return m_fileName; }
References m_fileName.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileVersion() [1/2]
QCString FileDefImpl::fileVersion () const [virtual]
Implements FileDef.
Definition at line 1707 of file filedef.cpp.
{
  return m_fileVersion;
}
References m_fileVersion.
fileVersion() [2/2]
virtual QCString FileDefImpl::fileVersion () const [virtual]
Implements FileDef.
findSectionsInDocumentation() [1/2]
void FileDefImpl::findSectionsInDocumentation () [virtual]
Implements FileDef.
Definition at line 290 of file filedef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
  for (const auto &mg : m_memberGroups)
  {
    mg->findSectionsInDocumentation(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_declarationLists)
    {
      ml->findSectionsInDocumentation(this);
    }
  }
}
References DefinitionMixin< FileDef >::briefDescription(), DefinitionMixin< FileDef >::docFile(), docFindSections(), DefinitionMixin< FileDef >::documentation(), m_memberGroups, m_memberLists, and MemberListType_declarationLists.
findSectionsInDocumentation() [2/2]
virtual void FileDefImpl::findSectionsInDocumentation () [virtual]
Implements FileDef.
generateSourceFile() [1/2]
bool FileDefImpl::generateSourceFile () const [virtual]
Implements FileDef.
Definition at line 1446 of file filedef.cpp.
{
  bool sourceBrowser = Config_getBool(SOURCE_BROWSER);
  bool verbatimHeaders = Config_getBool(VERBATIM_HEADERS);
  return !isReference() &&
         (sourceBrowser ||
           (verbatimHeaders && guessSection(name())==Entry::HEADER_SEC)
         ) &&
         !isDocumentationFile();
}
References Config_getBool, guessSection(), Entry::HEADER_SEC, isDocumentationFile(), DefinitionMixin< FileDef >::isReference(), and name().
Referenced by writeSourceHeader(), and writeSourceLink().
generateSourceFile() [2/2]
virtual bool FileDefImpl::generateSourceFile () const [virtual]
Implements FileDef.
getAllIncludeFilesRecursively() [1/2]
void FileDefImpl::getAllIncludeFilesRecursively (StringVector & incFiles) const [virtual]
Implements FileDef.
Definition at line 1696 of file filedef.cpp.
{
  StringUnorderedSet includes;
  ::getAllIncludeFilesRecursively(includes,this,incFiles);
}
References getAllIncludeFilesRecursively().
Referenced by getAllIncludeFilesRecursively().
getAllIncludeFilesRecursively() [2/2]
virtual void FileDefImpl::getAllIncludeFilesRecursively (StringVector & incFiles) const [virtual]
Implements FileDef.
getClasses() [1/2]
virtual const ClassLinkedRefMap & FileDefImpl::getClasses () const [inline], [virtual]
Implements FileDef.
Definition at line 99 of file filedef.cpp.
{ return m_classes; }
References m_classes.
getClasses() [2/2]
virtual const ClassLinkedRefMap & FileDefImpl::getClasses () const [inline], [virtual]
Implements FileDef.
Definition at line 99 of file filedef.cpp.
{ return m_classes; }
References m_classes.
getConcepts() [1/2]
virtual const ConceptLinkedRefMap & FileDefImpl::getConcepts () const [inline], [virtual]
Implements FileDef.
Definition at line 98 of file filedef.cpp.
{ return m_concepts; }
References m_concepts.
getConcepts() [2/2]
virtual const ConceptLinkedRefMap & FileDefImpl::getConcepts () const [inline], [virtual]
Implements FileDef.
Definition at line 98 of file filedef.cpp.
{ return m_concepts; }
References m_concepts.
getDirDef() [1/2]
virtual DirDef * FileDefImpl::getDirDef () const [inline], [virtual]
Implements FileDef.
Definition at line 88 of file filedef.cpp.
{ return m_dir; }
References m_dir.
Referenced by writeDocumentation(), and writeSourceHeader().
getDirDef() [2/2]
virtual DirDef * FileDefImpl::getDirDef () const [inline], [virtual]
Implements FileDef.
Definition at line 88 of file filedef.cpp.
{ return m_dir; }
References m_dir.
getMemberGroups() [1/2]
virtual const MemberGroupList & FileDefImpl::getMemberGroups () const [inline], [virtual]
Implements FileDef.
Definition at line 96 of file filedef.cpp.
{ return m_memberGroups; }
References m_memberGroups.
getMemberGroups() [2/2]
virtual const MemberGroupList & FileDefImpl::getMemberGroups () const [inline], [virtual]
Implements FileDef.
Definition at line 96 of file filedef.cpp.
{ return m_memberGroups; }
References m_memberGroups.
getMemberList() [1/2]
MemberList * FileDefImpl::getMemberList (MemberListType lt) const [virtual]
Implements FileDef.
Definition at line 1638 of file filedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()==lt)
    {
      return ml.get();
    }
  }
  return 0;
}
References m_memberLists.
Referenced by computeAnchors(), insertMember(), numDecMembers(), numDocMembers(), writeDocumentation(), writeMemberDeclarations(), writeMemberDocumentation(), writeQuickMemberLinks(), writeSummaryLinks(), and writeTagFile().
getMemberList() [2/2]
virtual MemberList * FileDefImpl::getMemberList (MemberListType lt) const [virtual]
Implements FileDef.
getMemberLists() [1/2]
virtual const MemberLists & FileDefImpl::getMemberLists () const [inline], [virtual]
Implements FileDef.
Definition at line 95 of file filedef.cpp.
{ return m_memberLists; }
References m_memberLists.
getMemberLists() [2/2]
virtual const MemberLists & FileDefImpl::getMemberLists () const [inline], [virtual]
Implements FileDef.
Definition at line 95 of file filedef.cpp.
{ return m_memberLists; }
References m_memberLists.
getNamespaces() [1/2]
virtual const NamespaceLinkedRefMap & FileDefImpl::getNamespaces () const [inline], [virtual]
Implements FileDef.
Definition at line 97 of file filedef.cpp.
{ return m_namespaces; }
References m_namespaces.
getNamespaces() [2/2]
virtual const NamespaceLinkedRefMap & FileDefImpl::getNamespaces () const [inline], [virtual]
Implements FileDef.
Definition at line 97 of file filedef.cpp.
{ return m_namespaces; }
References m_namespaces.
getOutputFileBase() [1/2]
QCString FileDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements FileDef.
Definition at line 1569 of file filedef.cpp.
{
  return m_outputDiskName;
}
References m_outputDiskName.
Referenced by addListReferences(), writeDocumentation(), writeSourceHeader(), and writeTagFile().
getOutputFileBase() [2/2]
virtual QCString FileDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements FileDef.
getPath() [1/2]
virtual QCString FileDefImpl::getPath () const [inline], [virtual]
Returns the absolute path of this file.
Implements FileDef.
Definition at line 82 of file filedef.cpp.
{ return m_path; }
References m_path.
Referenced by writeTagFile().
getPath() [2/2]
virtual QCString FileDefImpl::getPath () const [inline], [virtual]
Returns the absolute path of this file.
Implements FileDef.
Definition at line 82 of file filedef.cpp.
{ return m_path; }
References m_path.
getSourceDefinition() [1/2]
const Definition * FileDefImpl::getSourceDefinition (int lineNr) const [virtual]
Implements FileDef.
Definition at line 1337 of file filedef.cpp.
{
  auto it = m_srcDefMap.find(lineNr);
  //printf("%s::getSourceDefinition(%d)=%s\n",qPrint(name()),lineNr,it!=m_srcDefMap.end()?qPrint(it->second->name()):"none");
  return it!=m_srcDefMap.end() ? it->second : 0;
}
References m_srcDefMap.
getSourceDefinition() [2/2]
virtual const Definition * FileDefImpl::getSourceDefinition (int lineNr) const [virtual]
Implements FileDef.
getSourceFileBase() [1/2]
QCString FileDefImpl::getSourceFileBase () const [virtual]
Returns the name of the source listing of this definition.
Reimplemented from DefinitionMixin< FileDef >.
Definition at line 1557 of file filedef.cpp.
{
  if (Htags::useHtags)
  {
    return Htags::path2URL(m_filePath);
  }
  else
  {
    return m_outputDiskName+"_source";
  }
}
References m_filePath, m_outputDiskName, Htags::path2URL(), and Htags::useHtags.
Referenced by includeName(), writeDetailedDescription(), and writeSourceHeader().
getSourceFileBase() [2/2]
virtual QCString FileDefImpl::getSourceFileBase () const [virtual]
Returns the name of the source listing of this definition.
Reimplemented from DefinitionMixin< FileDef >.
getSourceMember() [1/2]
const MemberDef * FileDefImpl::getSourceMember (int lineNr) const [virtual]
Implements FileDef.
Definition at line 1344 of file filedef.cpp.
{
  auto it = m_srcMemberMap.find(lineNr);
  //printf("%s::getSourceMember(%d)=%s\n",qPrint(name()),lineNr,it!=m_srcMemberMap.end()?qPrint(it->second->name()):"none");
  return it!=m_srcMemberMap.end() ? it->second : 0;
}
References m_srcMemberMap.
getSourceMember() [2/2]
virtual const MemberDef * FileDefImpl::getSourceMember (int lineNr) const [virtual]
Implements FileDef.
getUsedClasses() [1/2]
virtual const LinkedRefMap< const ClassDef > & FileDefImpl::getUsedClasses () const [inline], [virtual]
Implements FileDef.
Definition at line 90 of file filedef.cpp.
{ return m_usingDeclList; }
References m_usingDeclList.
getUsedClasses() [2/2]
virtual const LinkedRefMap< const ClassDef > & FileDefImpl::getUsedClasses () const [inline], [virtual]
Implements FileDef.
Definition at line 90 of file filedef.cpp.
{ return m_usingDeclList; }
References m_usingDeclList.
getUsedNamespaces() [1/2]
const LinkedRefMap< const NamespaceDef > & FileDefImpl::getUsedNamespaces () const [virtual]
Implements FileDef.
Definition at line 1358 of file filedef.cpp.
{
  //printf("%p: FileDefImpl::getUsedNamespace: %s:%d\n",this,qPrint(name()),usingDirList?usingDirList->count():0);
  return m_usingDirList;
}
References m_usingDirList.
getUsedNamespaces() [2/2]
virtual const LinkedRefMap< const NamespaceDef > & FileDefImpl::getUsedNamespaces () const [virtual]
Implements FileDef.
getVersion() [1/2]
virtual QCString FileDefImpl::getVersion () const [inline], [virtual]
Returns version of this file.
Implements FileDef.
Definition at line 83 of file filedef.cpp.
{ return m_fileVersion; }
References m_fileVersion.
getVersion() [2/2]
virtual QCString FileDefImpl::getVersion () const [inline], [virtual]
Returns version of this file.
Implements FileDef.
Definition at line 83 of file filedef.cpp.
{ return m_fileVersion; }
References m_fileVersion.
hasDetailedDescription() [1/2]
bool FileDefImpl::hasDetailedDescription () const [virtual]
Implements FileDef.
Definition at line 308 of file filedef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  bool sourceBrowser = Config_getBool(SOURCE_BROWSER);
  return ((!briefDescription().isEmpty() && repeatBrief) ||
          !documentation().stripWhiteSpace().isEmpty() || // avail empty section
          (sourceBrowser && getStartBodyLine()!=-1 && getBodyDef())
         );
}
References DefinitionMixin< FileDef >::briefDescription(), Config_getBool, DefinitionMixin< FileDef >::documentation(), DefinitionMixin< FileDef >::getBodyDef(), and DefinitionMixin< FileDef >::getStartBodyLine().
Referenced by writeDetailedDescription().
hasDetailedDescription() [2/2]
virtual bool FileDefImpl::hasDetailedDescription () const [virtual]
Implements FileDef.
includedByDependencyGraphFileName() [1/2]
QCString FileDefImpl::includedByDependencyGraphFileName () const [virtual]
Implements FileDef.
Definition at line 1717 of file filedef.cpp.
{
  return m_inclByDepFileName;
}
References m_inclByDepFileName.
includedByDependencyGraphFileName() [2/2]
virtual QCString FileDefImpl::includedByDependencyGraphFileName () const [virtual]
Implements FileDef.
includedByFileList() [1/2]
virtual const IncludeInfoList & FileDefImpl::includedByFileList () const [inline], [virtual]
Implements FileDef.
Definition at line 92 of file filedef.cpp.
{ return m_includedByList; }
References m_includedByList.
includedByFileList() [2/2]
virtual const IncludeInfoList & FileDefImpl::includedByFileList () const [inline], [virtual]
Implements FileDef.
Definition at line 92 of file filedef.cpp.
{ return m_includedByList; }
References m_includedByList.
includeDependencyGraphFileName() [1/2]
QCString FileDefImpl::includeDependencyGraphFileName () const [virtual]
Implements FileDef.
Definition at line 1712 of file filedef.cpp.
{
  return m_inclDepFileName;
}
References m_inclDepFileName.
includeDependencyGraphFileName() [2/2]
virtual QCString FileDefImpl::includeDependencyGraphFileName () const [virtual]
Implements FileDef.
includeFileList() [1/2]
virtual const IncludeInfoList & FileDefImpl::includeFileList () const [inline], [virtual]
Implements FileDef.
Definition at line 91 of file filedef.cpp.
{ return m_includeList; }
References m_includeList.
includeFileList() [2/2]
virtual const IncludeInfoList & FileDefImpl::includeFileList () const [inline], [virtual]
Implements FileDef.
Definition at line 91 of file filedef.cpp.
{ return m_includeList; }
References m_includeList.
includeName() [1/2]
QCString FileDefImpl::includeName () const [virtual]
Returns the name of the verbatim copy of this file (if any).
Implements FileDef.
Definition at line 1575 of file filedef.cpp.
{
  return getSourceFileBase();
}
References getSourceFileBase().
Referenced by writeSourceLink().
includeName() [2/2]
virtual QCString FileDefImpl::includeName () const [virtual]
Returns the name of the verbatim copy of this file (if any).
Implements FileDef.
insertClass() [1/2]
void FileDefImpl::insertClass (const ClassDef * cd) [virtual]
Adds compound definition cd to the list of all compounds of this file
Implements FileDef.
Definition at line 1279 of file filedef.cpp.
{
  if (cd->isHidden()) return;
  ClassLinkedRefMap &list = m_classes;
  if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
  {
    if (cd->compoundType()==ClassDef::Interface)
    {
      list = m_interfaces;
    }
    else if (cd->compoundType()==ClassDef::Struct)
    {
      list = m_structs;
    }
    else if (cd->compoundType()==ClassDef::Exception)
    {
      list = m_exceptions;
    }
  }
  list.add(cd->name(),cd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), ClassDef::compoundType(), Config_getBool, ClassDef::Exception, ClassDef::Interface, Definition::isHidden(), m_classes, m_exceptions, m_interfaces, m_structs, Definition::name(), and ClassDef::Struct.
insertClass() [2/2]
virtual void FileDefImpl::insertClass (const ClassDef * cd) [virtual]
Implements FileDef.
insertConcept() [1/2]
void FileDefImpl::insertConcept (const ConceptDef * cd) [virtual]
Implements FileDef.
Definition at line 1304 of file filedef.cpp.
{
  if (cd->isHidden()) return;
  m_concepts.add(cd->name(),cd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::isHidden(), m_concepts, and Definition::name().
insertConcept() [2/2]
virtual void FileDefImpl::insertConcept (const ConceptDef * cd) [virtual]
Implements FileDef.
insertMember() [1/2]
void FileDefImpl::insertMember (MemberDef * md) [virtual]
Adds member definition md to the list of all members of this file
Implements FileDef.
Definition at line 1217 of file filedef.cpp.
{
  if (md->isHidden()) return;
  //printf("%s:FileDefImpl::insertMember(%s (=%p) list has %d elements)\n",
  // qPrint(name()),qPrint(md->name()),md,allMemberList.count());
  MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
  if (allMemberList && allMemberList->contains(md))
  {
    return;
  }
  if (allMemberList==0)
  {
    m_memberLists.emplace_back(std::make_unique<MemberList>(MemberListType_allMembersList,MemberListContainer::File));
    allMemberList = m_memberLists.back().get();
  }
  allMemberList->push_back(md);
  //::addFileMemberNameToIndex(md);
  switch (md->memberType())
  {
    case MemberType_Variable:
    case MemberType_Property:
      addMemberToList(MemberListType_decVarMembers,md);
      addMemberToList(MemberListType_docVarMembers,md);
      break;
    case MemberType_Function:
      addMemberToList(MemberListType_decFuncMembers,md);
      addMemberToList(MemberListType_docFuncMembers,md);
      break;
    case MemberType_Typedef:
      addMemberToList(MemberListType_decTypedefMembers,md);
      addMemberToList(MemberListType_docTypedefMembers,md);
      break;
    case MemberType_Sequence:
      addMemberToList(MemberListType_decSequenceMembers,md);
      addMemberToList(MemberListType_docSequenceMembers,md);
      break;
    case MemberType_Dictionary:
      addMemberToList(MemberListType_decDictionaryMembers,md);
      addMemberToList(MemberListType_docDictionaryMembers,md);
      break;
    case MemberType_Enumeration:
      addMemberToList(MemberListType_decEnumMembers,md);
      addMemberToList(MemberListType_docEnumMembers,md);
      break;
    case MemberType_EnumValue: // enum values are shown inside their enums
      break;
    case MemberType_Define:
      addMemberToList(MemberListType_decDefineMembers,md);
      addMemberToList(MemberListType_docDefineMembers,md);
      break;
    default:
       err("FileDefImpl::insertMembers(): "
           "member '%s' with class scope '%s' inserted in file scope '%s'!\n",
           qPrint(md->name()),
           md->getClassDef() ? qPrint(md->getClassDef()->name()) : "<global>",
           qPrint(name()));
  }
  //addMemberToGroup(md,groupId);
}
References addMemberToList(), MemberVector::contains(), err(), File, MemberLists::get(), MemberDef::getClassDef(), getMemberList(), Definition::isHidden(), m_memberLists, MemberListType_allMembersList, MemberListType_decDefineMembers, MemberListType_decDictionaryMembers, MemberListType_decEnumMembers, MemberListType_decFuncMembers, MemberListType_decSequenceMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docDictionaryMembers, MemberListType_docEnumMembers, MemberListType_docFuncMembers, MemberListType_docSequenceMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberDef::memberType(), MemberType_Define, MemberType_Dictionary, MemberType_Enumeration, MemberType_EnumValue, MemberType_Function, MemberType_Property, MemberType_Sequence, MemberType_Typedef, MemberType_Variable, name(), Definition::name(), MemberVector::push_back(), and qPrint().
insertMember() [2/2]
virtual void FileDefImpl::insertMember (MemberDef * md) [virtual]
Implements FileDef.
insertNamespace() [1/2]
void FileDefImpl::insertNamespace (const NamespaceDef * nd) [virtual]
Adds namespace definition nd to the list of all compounds of this file
Implements FileDef.
Definition at line 1311 of file filedef.cpp.
{
  if (nd->isHidden()) return;
  m_namespaces.add(nd->name(),nd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::isHidden(), m_namespaces, and Definition::name().
insertNamespace() [2/2]
virtual void FileDefImpl::insertNamespace (const NamespaceDef * nd) [virtual]
Implements FileDef.
isDocumentationFile() [1/2]
bool FileDefImpl::isDocumentationFile () const [virtual]
Implements FileDef.
Definition at line 1513 of file filedef.cpp.
{
  static const std::unordered_set<std::string> docExtensions =
  { "doc", "txt", "dox", "md", "markdown" };
  int lastDot = name().findRev('.');
  return (lastDot!=-1 && docExtensions.find(name().mid(lastDot+1).str())!=docExtensions.end()) ||
         getLanguageFromFileName(getFileNameExtension(name())) == SrcLangExt_Markdown;
}
References QCString::findRev(), getFileNameExtension(), getLanguageFromFileName(), name(), and SrcLangExt_Markdown.
Referenced by generateSourceFile(), and writeSourceHeader().
isDocumentationFile() [2/2]
virtual bool FileDefImpl::isDocumentationFile () const [virtual]
Implements FileDef.
isIncluded() [1/2]
bool FileDefImpl::isIncluded (const QCString & name) const [virtual]
Implements FileDef.
Definition at line 1440 of file filedef.cpp.
{
  if (name.isEmpty()) return FALSE;
  return m_includeMap.find(name.str())!=m_includeMap.end();
}
References FALSE, QCString::isEmpty(), m_includeMap, name(), and QCString::str().
isIncluded() [2/2]
virtual bool FileDefImpl::isIncluded (const QCString & name) const [virtual]
Implements FileDef.
isLinkable() [1/2]
virtual bool FileDefImpl::isLinkable () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements FileDef.
Definition at line 85 of file filedef.cpp.
{ return isLinkableInProject() || isReference(); }
References isLinkableInProject(), and DefinitionMixin< FileDef >::isReference().
Referenced by writeSourceHeader().
isLinkable() [2/2]
virtual bool FileDefImpl::isLinkable () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements FileDef.
Definition at line 85 of file filedef.cpp.
{ return isLinkableInProject() || isReference(); }
References isLinkableInProject(), and DefinitionMixin< FileDef >::isReference().
isLinkableInProject() [1/2]
bool FileDefImpl::isLinkableInProject () const [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements FileDef.
Definition at line 1674 of file filedef.cpp.
{
  bool showFiles = Config_getBool(SHOW_FILES);
  return hasDocumentation() && !isReference() && (showFiles || isLinkableViaGroup());
}
References Config_getBool, DefinitionMixin< FileDef >::hasDocumentation(), DefinitionMixin< FileDef >::isLinkableViaGroup(), and DefinitionMixin< FileDef >::isReference().
Referenced by isLinkable().
isLinkableInProject() [2/2]
virtual bool FileDefImpl::isLinkableInProject () const [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements FileDef.
isSource() [1/2]
virtual bool FileDefImpl::isSource () const [inline], [virtual]
Returns TRUE if this file is a source file.
Implements FileDef.
Definition at line 78 of file filedef.cpp.
{ return m_isSource; }
References m_isSource.
isSource() [2/2]
virtual bool FileDefImpl::isSource () const [inline], [virtual]
Returns TRUE if this file is a source file.
Implements FileDef.
Definition at line 78 of file filedef.cpp.
{ return m_isSource; }
References m_isSource.
name() [1/2]
QCString FileDefImpl::name () const [virtual]
Returns the unique file name (this may include part of the path).
Reimplemented from DefinitionMixin< FileDef >.
Definition at line 1317 of file filedef.cpp.
{
  if (Config_getBool(FULL_PATH_NAMES))
    return m_fileName;
  else
    return DefinitionMixin::name();
}
References Config_getBool, m_fileName, and DefinitionMixin< Base >::name().
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), addListReferences(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), displayName(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), FileDefImpl(), search.Finder::function(), generateSourceFile(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), insertMember(), isDocumentationFile(), isIncluded(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), setDiskName(), search.Finder::struct(), search.Finder::subClasses(), title(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), search.Finder::variable(), writeDetailedDescription(), writeDocumentation(), writeIncludedByGraph(), writeIncludeGraph(), writeMemberDocumentation(), writeMemberPages(), writeSourceHeader(), and writeTagFile().
name() [2/2]
virtual QCString FileDefImpl::name () const [virtual]
Returns the unique file name (this may include part of the path).
Reimplemented from DefinitionMixin< FileDef >.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
numDecMembers() [1/2]
int FileDefImpl::numDecMembers () const [virtual]
Implements FileDef.
Definition at line 1742 of file filedef.cpp.
{
  MemberList *ml = getMemberList(MemberListType_allMembersList);
  return ml ? ml->numDecMembers() : 0;
}
References getMemberList(), MemberListType_allMembersList, and MemberList::numDecMembers().
numDecMembers() [2/2]
virtual int FileDefImpl::numDecMembers () const [virtual]
Implements FileDef.
numDocMembers() [1/2]
int FileDefImpl::numDocMembers () const [virtual]
Implements FileDef.
Definition at line 1736 of file filedef.cpp.
{
  MemberList *ml = getMemberList(MemberListType_allMembersList);
  return ml ? ml->numDocMembers() : 0;
}
References getMemberList(), MemberListType_allMembersList, and MemberList::numDocMembers().
numDocMembers() [2/2]
virtual int FileDefImpl::numDocMembers () const [virtual]
Implements FileDef.
packageDef() [1/2]
virtual PackageDef * FileDefImpl::packageDef () const [inline], [virtual]
Implements FileDef.
Definition at line 87 of file filedef.cpp.
{ return m_package; }
References m_package.
packageDef() [2/2]
virtual PackageDef * FileDefImpl::packageDef () const [inline], [virtual]
Implements FileDef.
Definition at line 87 of file filedef.cpp.
{ return m_package; }
References m_package.
parseSource() [1/2]
void FileDefImpl::parseSource (ClangTUParser * clangParser) [virtual]
Implements FileDef.
Definition at line 1170 of file filedef.cpp.
{
  bool filterSourceFiles = Config_getBool(FILTER_SOURCE_FILES);
  DevNullCodeDocInterface devNullIntf;
#if USE_LIBCLANG
  if (Doxygen::clangAssistedParsing && clangParser &&
      (getLanguage()==SrcLangExt_Cpp || getLanguage()==SrcLangExt_ObjC))
  {
    clangParser->switchToFile(this);
    clangParser->writeSources(devNullIntf,this);
  }
  else
#endif
  {
    auto intf = Doxygen::parserManager->getCodeParser(getDefFileExtension());
    intf->resetCodeParserState();
    intf->parseCode(
            devNullIntf,QCString(),
            fileToString(absFilePath(),filterSourceFiles,TRUE),
            getLanguage(),
            FALSE,QCString(),this
           );
  }
}
References absFilePath(), Doxygen::clangAssistedParsing, Config_getBool, FALSE, fileToString(), ParserManager::getCodeParser(), DefinitionMixin< FileDef >::getDefFileExtension(), DefinitionMixin< FileDef >::getLanguage(), Doxygen::parserManager, SrcLangExt_Cpp, SrcLangExt_ObjC, ClangTUParser::switchToFile(), TRUE, and ClangTUParser::writeSources().
parseSource() [2/2]
virtual void FileDefImpl::parseSource (ClangTUParser * clangParser) [virtual]
Implements FileDef.
setDirDef() [1/2]
virtual void FileDefImpl::setDirDef (DirDef * dd) [inline], [virtual]
Implements FileDef.
Definition at line 124 of file filedef.cpp.
{ m_dir=dd; }
References m_dir.
setDirDef() [2/2]
virtual void FileDefImpl::setDirDef (DirDef * dd) [inline], [virtual]
Implements FileDef.
Definition at line 124 of file filedef.cpp.
{ m_dir=dd; }
References m_dir.
setDiskName() [1/2]
void FileDefImpl::setDiskName (const QCString & name) [virtual]
Implements FileDef.
Definition at line 258 of file filedef.cpp.
{
  if (isReference())
  {
    m_outputDiskName = name;
    m_inclDepFileName = name+"_incl";
    m_inclByDepFileName = name+"_dep_incl";
  }
  else
  {
    m_outputDiskName = convertNameToFile(name);
    m_inclDepFileName = convertNameToFile(name+"_incl");
    m_inclByDepFileName = convertNameToFile(name+"_dep_incl");
  }
}
References convertNameToFile(), DefinitionMixin< FileDef >::isReference(), m_inclByDepFileName, m_inclDepFileName, m_outputDiskName, and name().
Referenced by FileDefImpl().
setDiskName() [2/2]
virtual void FileDefImpl::setDiskName (const QCString & name) [virtual]
Implements FileDef.
setPackageDef() [1/2]
virtual void FileDefImpl::setPackageDef (PackageDef * pd) [inline], [virtual]
Implements FileDef.
Definition at line 123 of file filedef.cpp.
{ m_package=pd; }
References m_package.
setPackageDef() [2/2]
virtual void FileDefImpl::setPackageDef (PackageDef * pd) [inline], [virtual]
Implements FileDef.
Definition at line 123 of file filedef.cpp.
{ m_package=pd; }
References m_package.
sortMemberLists() [1/2]
void FileDefImpl::sortMemberLists () [virtual]
Implements FileDef.
Definition at line 1599 of file filedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->needsSorting()) { ml->sort(); ml->setNeedsSorting(FALSE); }
  }
  for (const auto &mg : m_memberGroups)
  {
    MemberList &mlg = const_cast<MemberList&>(mg->members());
    if (mlg.needsSorting()) { mlg.sort(); mlg.setNeedsSorting(FALSE); }
  }
  std::sort(m_includedByList.begin(),m_includedByList.end(),
      [](const auto &fi1,const auto &fi2) { return fi1.includeName < fi2.includeName; });
  if (Config_getBool(SORT_BRIEF_DOCS))
  {
    auto classComp = [](const ClassLinkedRefMap::Ptr &c1,const ClassLinkedRefMap::Ptr &c2)
    {
      return Config_getBool(SORT_BY_SCOPE_NAME) ?
        qstricmp(c1->name(), c2->name())<0 :
        qstricmp(c1->className(), c2->className())<0;
    };
    std::sort(m_classes.begin(), m_classes.end(), classComp);
    std::sort(m_interfaces.begin(),m_interfaces.end(),classComp);
    std::sort(m_structs.begin(), m_structs.end(), classComp);
    std::sort(m_exceptions.begin(),m_exceptions.end(),classComp);
    auto namespaceComp = [](const NamespaceLinkedRefMap::Ptr &n1,const NamespaceLinkedRefMap::Ptr &n2)
    {
      return qstricmp(n1->name(),n2->name())<0;
    };
    std::sort(m_namespaces.begin(),m_namespaces.end(),namespaceComp);
  }
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::begin(), ClassDef::className(), Config_getBool, LinkedRefMap< T, Hash, KeyEqual, Map >::end(), FALSE, m_classes, m_exceptions, m_includedByList, m_interfaces, m_memberGroups, m_memberLists, m_namespaces, m_structs, Definition::name(), MemberList::needsSorting(), qstricmp(), MemberList::setNeedsSorting(), and MemberVector::sort().
sortMemberLists() [2/2]
virtual void FileDefImpl::sortMemberLists () [virtual]
Implements FileDef.
startMemberDeclarations() [1/2]
void FileDefImpl::startMemberDeclarations (OutputList & ol) [private]
Definition at line 694 of file filedef.cpp.
{
  ol.startMemberSections();
}
References OutputList::startMemberSections().
Referenced by writeDocumentation().
startMemberDeclarations() [2/2]
void FileDefImpl::startMemberDeclarations (OutputList & ol) [private]
startMemberDocumentation() [1/2]
void FileDefImpl::startMemberDocumentation (OutputList & ol) [private]
Definition at line 704 of file filedef.cpp.
{
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.disable(OutputGenerator::Html);
    Doxygen::suppressDocWarnings = TRUE;
  }
}
References Config_getBool, OutputList::disable(), OutputGenerator::Html, Doxygen::suppressDocWarnings, and TRUE.
Referenced by writeDocumentation().
startMemberDocumentation() [2/2]
void FileDefImpl::startMemberDocumentation (OutputList & ol) [private]
subGrouping() [1/2]
virtual bool FileDefImpl::subGrouping () const [inline], [virtual]
Implements FileDef.
Definition at line 103 of file filedef.cpp.
{ return m_subGrouping; }
References m_subGrouping.
subGrouping() [2/2]
virtual bool FileDefImpl::subGrouping () const [inline], [virtual]
Implements FileDef.
Definition at line 103 of file filedef.cpp.
{ return m_subGrouping; }
References m_subGrouping.
title() [1/2]
QCString FileDefImpl::title () const [virtual]
Implements FileDef.
Definition at line 1702 of file filedef.cpp.
{
  return theTranslator->trFileReference(name());
}
References name(), theTranslator, and Translator::trFileReference().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), writeClassDeclarations(), writeConcepts(), writeDetailedDescription(), writeDocumentation(), writeMemberDeclarations(), writeMemberDocumentation(), writeNamespaceDeclarations(), and writeSourceHeader().
title() [2/2]
virtual QCString FileDefImpl::title () const [virtual]
Implements FileDef.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
writeAuthorSection() [1/2]
void FileDefImpl::writeAuthorSection (OutputList & ol) [private]
Definition at line 734 of file filedef.cpp.
{
  // write Author section (Man only)
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Man);
  ol.startGroupHeader();
  ol.parseText(theTranslator->trAuthor(TRUE,TRUE));
  ol.endGroupHeader();
  ol.parseText(theTranslator->trGeneratedAutomatically(Config_getString(PROJECT_NAME)));
  ol.popGeneratorState();
}
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), and TRUE.
Referenced by writeDocumentation().
writeAuthorSection() [2/2]
void FileDefImpl::writeAuthorSection (OutputList & ol) [private]
writeBriefDescription() [1/2]
void FileDefImpl::writeBriefDescription (OutputList & ol) [private]
Definition at line 482 of file filedef.cpp.
{
  if (hasBriefDescription())
  {
    auto parser { createDocParser() };
    auto ast { validatingParseDoc(*parser.get(),
                                     briefFile(),briefLine(),this,0,
                                     briefDescription(),TRUE,FALSE,
                                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startParagraph();
      ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Man);
      ol.writeString(" - ");
      ol.popGeneratorState();
      ol.writeDoc(ast.get(),this,0);
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::RTF);
      ol.writeString(" \n");
      ol.enable(OutputGenerator::RTF);
      if (Config_getBool(REPEAT_BRIEF) ||
          !documentation().isEmpty()
         )
      {
        ol.disableAllBut(OutputGenerator::Html);
        ol.startTextLink(QCString(),"details");
        ol.parseText(theTranslator->trMore());
        ol.endTextLink();
      }
      ol.popGeneratorState();
      ol.endParagraph();
    }
  }
  ol.writeSynopsis();
}
References DefinitionMixin< FileDef >::briefDescription(), DefinitionMixin< FileDef >::briefFile(), DefinitionMixin< FileDef >::briefLine(), Config_getBool, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< FileDef >::documentation(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), FALSE, DefinitionMixin< FileDef >::hasBriefDescription(), OutputGenerator::Html, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, Translator::trMore(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeBriefDescription() [2/2]
void FileDefImpl::writeBriefDescription (OutputList & ol) [private]
writeClassDeclarations() [1/2]
void FileDefImpl::writeClassDeclarations (OutputList & ol, const QCString & title, const ClassLinkedRefMap & list) [private]
Definition at line 669 of file filedef.cpp.
{
  // write list of classes
  list.writeDeclaration(ol,0,title,FALSE);
}
References FALSE, title(), and ClassLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeClassDeclarations() [2/2]
void FileDefImpl::writeClassDeclarations (OutputList & ol, const QCString & title, const ClassLinkedRefMap & list) [private]
writeClassesToTagFile() [1/2]
void FileDefImpl::writeClassesToTagFile (TextStream & t, const ClassLinkedRefMap & list) [private]
Definition at line 520 of file filedef.cpp.
{
  for (const auto &cd : list)
  {
    if (cd->isLinkableInProject())
    {
      tagFile << " <class kind=\"" << cd->compoundTypeString() <<
        "\">" << convertToXML(cd->name()) << "</class>\n";
    }
  }
}
References convertToXML().
Referenced by writeTagFile().
writeClassesToTagFile() [2/2]
void FileDefImpl::writeClassesToTagFile (TextStream & t, const ClassLinkedRefMap & list) [private]
writeConcepts() [1/2]
void FileDefImpl::writeConcepts (OutputList & ol, const QCString & title) [private]
Definition at line 675 of file filedef.cpp.
{
  // write list of classes
  m_concepts.writeDeclaration(ol,title,FALSE);
}
References FALSE, m_concepts, title(), and ConceptLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeConcepts() [2/2]
void FileDefImpl::writeConcepts (OutputList & ol, const QCString & title) [private]
writeDetailedDescription() [1/2]
void FileDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) [private]
Definition at line 419 of file filedef.cpp.
{
  if (hasDetailedDescription())
  {
    ol.pushGeneratorState();
      ol.disable(OutputGenerator::Html);
      ol.writeRuler();
    ol.popGeneratorState();
    ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Html);
      ol.writeAnchor(QCString(),"details");
    ol.popGeneratorState();
    ol.startGroupHeader();
    ol.parseText(title);
    ol.endGroupHeader();
    ol.startTextBlock();
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF))
    {
      ol.generateDoc(briefFile(),briefLine(),this,0,briefDescription(),FALSE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF) &&
        !documentation().isEmpty())
    {
      ol.pushGeneratorState();
        ol.disable(OutputGenerator::Man);
        ol.disable(OutputGenerator::RTF);
        // ol.newParagraph(); // FIXME:PARA
        ol.enableAll();
        ol.disableAllBut(OutputGenerator::Man);
        ol.enable(OutputGenerator::Latex);
        ol.writeString("\n\n");
      ol.popGeneratorState();
    }
    if (!documentation().isEmpty())
    {
      ol.generateDoc(docFile(),docLine(),this,0,documentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    //printf("Writing source ref for file %s\n",qPrint(name()));
    if (Config_getBool(SOURCE_BROWSER))
    {
      ol.startParagraph("definition");
      QCString refText = theTranslator->trDefinedInSourceFile();
      int fileMarkerPos = refText.find("@0");
      if (fileMarkerPos!=-1) // should always pass this.
      {
        ol.parseText(refText.left(fileMarkerPos)); //text left from marker 1
        ol.writeObjectLink(QCString(),getSourceFileBase(),QCString(),name());
        ol.parseText(refText.right(
              refText.length()-fileMarkerPos-2)); // text right from marker 2
      }
      else
      {
        err("translation error: invalid marker in trDefinedInSourceFile()\n");
      }
      ol.endParagraph();
    }
    ol.endTextBlock();
  }
}
References DefinitionMixin< FileDef >::briefDescription(), DefinitionMixin< FileDef >::briefFile(), DefinitionMixin< FileDef >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< FileDef >::docFile(), DefinitionMixin< FileDef >::docLine(), DefinitionMixin< FileDef >::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endGroupHeader(), OutputList::endParagraph(), OutputList::endTextBlock(), err(), FALSE, QCString::find(), OutputList::generateDoc(), getSourceFileBase(), hasDetailedDescription(), OutputGenerator::Html, OutputGenerator::Latex, QCString::left(), QCString::length(), OutputGenerator::Man, name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), QCString::right(), OutputGenerator::RTF, OutputList::startGroupHeader(), OutputList::startParagraph(), OutputList::startTextBlock(), theTranslator, title(), Translator::trDefinedInSourceFile(), TRUE, OutputList::writeAnchor(), OutputList::writeObjectLink(), OutputList::writeRuler(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDetailedDescription() [2/2]
void FileDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) [private]
writeDocumentation() [1/2]
void FileDefImpl::writeDocumentation (OutputList & ol) [virtual]
Write the documentation page for this file to the file of output generators ol.
Implements FileDef.
Definition at line 815 of file filedef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  //funcList->countDecMembers();
  //QCString fn = name();
  //if (Config_getBool(FULL_PATH_NAMES))
  //{
  // fn.prepend(stripFromPath(getPath()));
  //}
  //printf("WriteDocumentation diskname=%s\n",qPrint(diskname));
  QCString versionTitle;
  if (!m_fileVersion.isEmpty())
  {
    versionTitle=("("+m_fileVersion+")");
  }
  QCString title = m_docname+versionTitle;
  QCString pageTitle=theTranslator->trFileReference(m_docname);
  if (getDirDef())
  {
    startFile(ol,getOutputFileBase(),name(),pageTitle,HLI_FileVisible,!generateTreeView);
    if (!generateTreeView)
    {
      getDirDef()->writeNavigationPath(ol);
      ol.endQuickIndices();
    }
    QCString pageTitleShort=theTranslator->trFileReference(name());
    startTitle(ol,getOutputFileBase(),this);
    ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Html);
      ol.parseText(pageTitleShort); // Html only
      ol.enableAll();
      ol.disable(OutputGenerator::Html);
      ol.parseText(pageTitle); // other output formats
    ol.popGeneratorState();
    addGroupListToTitle(ol,this);
    endTitle(ol,getOutputFileBase(),title);
  }
  else
  {
    startFile(ol,getOutputFileBase(),name(),pageTitle,HLI_FileVisible,!generateTreeView);
    if (!generateTreeView)
    {
      ol.endQuickIndices();
    }
    startTitle(ol,getOutputFileBase(),this);
    ol.parseText(pageTitle);
    addGroupListToTitle(ol,this);
    endTitle(ol,getOutputFileBase(),title);
  }
  ol.startContents();
  if (!m_fileVersion.isEmpty())
  {
    ol.disableAllBut(OutputGenerator::Html);
    ol.startProjectNumber();
    ol.docify(versionTitle);
    ol.endProjectNumber();
    ol.enableAll();
  }
  //---------------------------------------- start flexible part -------------------------------
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::File))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
        startMemberDeclarations(ol);
        break;
      case LayoutDocEntry::FileIncludes:
        writeIncludeFiles(ol);
        break;
      case LayoutDocEntry::FileIncludeGraph:
        writeIncludeGraph(ol);
        break;
      case LayoutDocEntry::FileIncludedByGraph:
        writeIncludedByGraph(ol);
        break;
      case LayoutDocEntry::FileSourceLink:
        writeSourceLink(ol);
        break;
      case LayoutDocEntry::FileClasses:
        if (ls) writeClassDeclarations(ol,ls->title(lang),m_classes);
        break;
      case LayoutDocEntry::FileInterfaces:
        if (ls) writeClassDeclarations(ol,ls->title(lang),m_interfaces);
        break;
      case LayoutDocEntry::FileStructs:
        if (ls) writeClassDeclarations(ol,ls->title(lang),m_structs);
        break;
      case LayoutDocEntry::FileExceptions:
        if (ls) writeClassDeclarations(ol,ls->title(lang),m_exceptions);
        break;
      case LayoutDocEntry::FileConcepts:
        if (ls) writeConcepts(ol,ls->title(lang));
        break;
      case LayoutDocEntry::FileNamespaces:
        if (ls) writeNamespaceDeclarations(ol,ls->title(lang),false);
        break;
      case LayoutDocEntry::FileConstantGroups:
        if (ls) writeNamespaceDeclarations(ol,ls->title(lang),true);
        break;
      case LayoutDocEntry::MemberGroups:
        writeMemberGroups(ol);
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd) writeMemberDeclarations(ol,lmd->type,lmd->title(lang));
        }
        break;
      case LayoutDocEntry::MemberDeclEnd:
        endMemberDeclarations(ol);
        break;
      case LayoutDocEntry::DetailedDesc:
        if (ls) writeDetailedDescription(ol,ls->title(lang));
        break;
      case LayoutDocEntry::MemberDefStart:
        startMemberDocumentation(ol);
        break;
      case LayoutDocEntry::FileInlineClasses:
        writeInlineClasses(ol);
        break;
      case LayoutDocEntry::MemberDef:
        {
          const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
          if (lmd) writeMemberDocumentation(ol,lmd->type,lmd->title(lang));
        }
        break;
      case LayoutDocEntry::MemberDefEnd:
        endMemberDocumentation(ol);
        break;
      case LayoutDocEntry::AuthorSection:
        writeAuthorSection(ol);
        break;
      case LayoutDocEntry::ClassIncludes:
      case LayoutDocEntry::ClassInheritanceGraph:
      case LayoutDocEntry::ClassNestedClasses:
      case LayoutDocEntry::ClassCollaborationGraph:
      case LayoutDocEntry::ClassAllMembersLink:
      case LayoutDocEntry::ClassUsedFiles:
      case LayoutDocEntry::ClassInlineClasses:
      case LayoutDocEntry::NamespaceNestedNamespaces:
      case LayoutDocEntry::NamespaceNestedConstantGroups:
      case LayoutDocEntry::NamespaceClasses:
      case LayoutDocEntry::NamespaceConcepts:
      case LayoutDocEntry::NamespaceInterfaces:
      case LayoutDocEntry::NamespaceStructs:
      case LayoutDocEntry::NamespaceExceptions:
      case LayoutDocEntry::NamespaceInlineClasses:
      case LayoutDocEntry::ConceptDefinition:
      case LayoutDocEntry::GroupClasses:
      case LayoutDocEntry::GroupConcepts:
      case LayoutDocEntry::GroupInlineClasses:
      case LayoutDocEntry::GroupNamespaces:
      case LayoutDocEntry::GroupDirs:
      case LayoutDocEntry::GroupNestedGroups:
      case LayoutDocEntry::GroupFiles:
      case LayoutDocEntry::GroupGraph:
      case LayoutDocEntry::GroupPageDocs:
      case LayoutDocEntry::DirSubDirs:
      case LayoutDocEntry::DirFiles:
      case LayoutDocEntry::DirGraph:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::File entry list\n",lde->kind());
        break;
    }
  }
  //---------------------------------------- end flexible part -------------------------------
  ol.endContents();
  endFileWithNavPath(this,ol);
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    MemberList *ml = getMemberList(MemberListType_allMembersList);
    if (ml) ml->sort();
    writeMemberPages(ol);
  }
}
References addGroupListToTitle(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, LayoutDocEntry::ConceptDefinition, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enableAll(), OutputList::endContents(), endFileWithNavPath(), endMemberDeclarations(), endMemberDocumentation(), OutputList::endProjectNumber(), OutputList::endQuickIndices(), endTitle(), err(), LayoutDocManager::File, LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, LayoutDocEntry::FileStructs, getDirDef(), DefinitionMixin< FileDef >::getLanguage(), getMemberList(), getOutputFileBase(), LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, HLI_FileVisible, OutputGenerator::Html, LayoutDocManager::instance(), QCString::isEmpty(), m_classes, m_docname, m_exceptions, m_fileVersion, m_interfaces, m_structs, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, MemberListType_allMembersList, name(), LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, LayoutDocEntry::NamespaceStructs, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), MemberVector::sort(), OutputList::startContents(), startFile(), startMemberDeclarations(), startMemberDocumentation(), OutputList::startProjectNumber(), startTitle(), theTranslator, title(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), Translator::trFileReference(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeClassDeclarations(), writeConcepts(), writeDetailedDescription(), writeIncludedByGraph(), writeIncludeFiles(), writeIncludeGraph(), writeInlineClasses(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), writeMemberPages(), writeNamespaceDeclarations(), DefinitionMutable::writeNavigationPath(), and writeSourceLink().
writeDocumentation() [2/2]
virtual void FileDefImpl::writeDocumentation (OutputList & ol) [virtual]
Implements FileDef.
writeIncludedByGraph() [1/2]
void FileDefImpl::writeIncludedByGraph (OutputList & ol) [private]
Definition at line 621 of file filedef.cpp.
{
  if (Config_getBool(HAVE_DOT) /*&& Config_getBool(INCLUDED_BY_GRAPH)*/)
  {
    //printf("Graph for file %s\n",qPrint(name()));
    DotInclDepGraph incDepGraph(this,TRUE);
    if (incDepGraph.isTooBig())
    {
       warn_uncond("Included by graph for '%s' not generated, too many nodes (%d), threshold is %d. Consider increasing DOT_GRAPH_MAX_NODES.\n",
           qPrint(name()), incDepGraph.numNodes(), Config_getInt(DOT_GRAPH_MAX_NODES));
    }
    else if (!incDepGraph.isTrivial())
    {
      ol.startTextBlock();
      ol.disable(OutputGenerator::Man);
      ol.startInclDepGraph();
      ol.parseText(theTranslator->trInclByDepGraph());
      ol.endInclDepGraph(incDepGraph);
      ol.enableAll();
      ol.endTextBlock(TRUE);
    }
    //incDepGraph.writeGraph(Config_getString(HTML_OUTPUT),fd->getOutputFileBase());
  }
}
References Config_getBool, Config_getInt, OutputList::disable(), OutputList::enableAll(), OutputList::endInclDepGraph(), OutputList::endTextBlock(), DotInclDepGraph::isTooBig(), DotInclDepGraph::isTrivial(), OutputGenerator::Man, name(), DotInclDepGraph::numNodes(), OutputList::parseText(), qPrint(), OutputList::startInclDepGraph(), OutputList::startTextBlock(), theTranslator, Translator::trInclByDepGraph(), TRUE, and warn_uncond().
Referenced by writeDocumentation().
writeIncludedByGraph() [2/2]
void FileDefImpl::writeIncludedByGraph (OutputList & ol) [private]
writeIncludeFiles() [1/2]
void FileDefImpl::writeIncludeFiles (OutputList & ol) [private]
Definition at line 532 of file filedef.cpp.
{
  if (!m_includeList.empty())
  {
    ol.startTextBlock(TRUE);
    for (const auto &ii : m_includeList)
    {
      const FileDef *fd=ii.fileDef;
      bool isIDLorJava = FALSE;
      if (fd)
      {
        SrcLangExt lang = fd->getLanguage();
        isIDLorJava = lang==SrcLangExt_IDL || lang==SrcLangExt_Java;
      }
      ol.startTypewriter();
      if (isIDLorJava) // IDL/Java include
      {
        ol.docify("import ");
      }
      else if (ii.imported) // Objective-C include
      {
        ol.docify("#import ");
      }
      else // C/C++ include
      {
        ol.docify("#include ");
      }
      if (ii.local || isIDLorJava)
        ol.docify("\"");
      else
        ol.docify("<");
      ol.disable(OutputGenerator::Html);
      ol.docify(ii.includeName);
      ol.enableAll();
      ol.disableAllBut(OutputGenerator::Html);
      // Here we use the include file name as it appears in the file.
      // we could also we the name as it is used within doxygen,
      // then we should have used fd->docName() instead of ii->includeName
      if (fd && fd->isLinkable())
      {
        ol.writeObjectLink(fd->getReference(),
            fd->generateSourceFile() ? fd->includeName() : fd->getOutputFileBase(),
            QCString(),ii.includeName);
      }
      else
      {
        ol.docify(ii.includeName);
      }
      ol.enableAll();
      if (ii.local || isIDLorJava)
        ol.docify("\"");
      else
        ol.docify(">");
      if (isIDLorJava)
        ol.docify(";");
      ol.endTypewriter();
      ol.lineBreak();
    }
    ol.endTextBlock();
  }
}
References OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enableAll(), OutputList::endTextBlock(), OutputList::endTypewriter(), FALSE, FileDef::generateSourceFile(), Definition::getLanguage(), FileDef::getOutputFileBase(), Definition::getReference(), OutputGenerator::Html, FileDef::includeName(), FileDef::isLinkable(), OutputList::lineBreak(), m_includeList, SrcLangExt_IDL, SrcLangExt_Java, OutputList::startTextBlock(), OutputList::startTypewriter(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeIncludeFiles() [2/2]
void FileDefImpl::writeIncludeFiles (OutputList & ol) [private]
writeIncludeGraph() [1/2]
void FileDefImpl::writeIncludeGraph (OutputList & ol) [private]
Definition at line 596 of file filedef.cpp.
{
  if (Config_getBool(HAVE_DOT) /*&& Config_getBool(INCLUDE_GRAPH)*/)
  {
    //printf("Graph for file %s\n",qPrint(name()));
    DotInclDepGraph incDepGraph(this,FALSE);
    if (incDepGraph.isTooBig())
    {
       warn_uncond("Include graph for '%s' not generated, too many nodes (%d), threshold is %d. Consider increasing DOT_GRAPH_MAX_NODES.\n",
           qPrint(name()), incDepGraph.numNodes(), Config_getInt(DOT_GRAPH_MAX_NODES));
    }
    else if (!incDepGraph.isTrivial())
    {
      ol.startTextBlock();
      ol.disable(OutputGenerator::Man);
      ol.startInclDepGraph();
      ol.parseText(theTranslator->trInclDepGraph(name()));
      ol.endInclDepGraph(incDepGraph);
      ol.enableAll();
      ol.endTextBlock(TRUE);
    }
    //incDepGraph.writeGraph(Config_getString(HTML_OUTPUT),fd->getOutputFileBase());
  }
}
References Config_getBool, Config_getInt, OutputList::disable(), OutputList::enableAll(), OutputList::endInclDepGraph(), OutputList::endTextBlock(), FALSE, DotInclDepGraph::isTooBig(), DotInclDepGraph::isTrivial(), OutputGenerator::Man, name(), DotInclDepGraph::numNodes(), OutputList::parseText(), qPrint(), OutputList::startInclDepGraph(), OutputList::startTextBlock(), theTranslator, Translator::trInclDepGraph(), TRUE, and warn_uncond().
Referenced by writeDocumentation().
writeIncludeGraph() [2/2]
void FileDefImpl::writeIncludeGraph (OutputList & ol) [private]
writeInlineClasses() [1/2]
void FileDefImpl::writeInlineClasses (OutputList & ol) [private]
Definition at line 681 of file filedef.cpp.
{
  // temporarily undo the disabling could be done by startMemberDocumentation()
  // as a result of setting SEPARATE_MEMBER_PAGES to YES; see bug730512
  bool isEnabled = ol.isEnabled(OutputGenerator::Html);
  ol.enable(OutputGenerator::Html);
  m_classes.writeDocumentation(ol,this);
  // restore the initial state if needed
  if (!isEnabled) ol.disable(OutputGenerator::Html);
}
References OutputList::disable(), OutputList::enable(), OutputGenerator::Html, OutputList::isEnabled(), m_classes, and ClassLinkedRefMap::writeDocumentation().
Referenced by writeDocumentation().
writeInlineClasses() [2/2]
void FileDefImpl::writeInlineClasses (OutputList & ol) [private]
writeMemberDeclarations() [1/2]
void FileDefImpl::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title) [private]
Definition at line 1650 of file filedef.cpp.
{
  bool optVhdl = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  MemberList * ml = getMemberList(lt);
  if (ml)
  {
    if (optVhdl) // use specific declarations function
    {
      VhdlDocGen::writeVhdlDeclarations(ml,ol,0,0,this,0);
    }
    else
    {
      ml->writeDeclarations(ol,0,0,this,0,title,QCString());
    }
  }
}
References Config_getBool, getMemberList(), title(), MemberList::writeDeclarations(), and VhdlDocGen::writeVhdlDeclarations().
Referenced by writeDocumentation().
writeMemberDeclarations() [2/2]
void FileDefImpl::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title) [private]
writeMemberDocumentation() [1/2]
void FileDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title) [private]
Definition at line 1668 of file filedef.cpp.
{
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeDocumentation(ol,name(),this,title);
}
References getMemberList(), name(), title(), and MemberList::writeDocumentation().
Referenced by writeDocumentation().
writeMemberDocumentation() [2/2]
void FileDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title) [private]
writeMemberGroups() [1/2]
void FileDefImpl::writeMemberGroups (OutputList & ol) [private]
Definition at line 722 of file filedef.cpp.
{
  /* write user defined member groups */
  for (const auto &mg : m_memberGroups)
  {
    if (!mg->allMembersInSameSection() || !m_subGrouping)
    {
      mg->writeDeclarations(ol,0,0,this,0);
    }
  }
}
References m_memberGroups, and m_subGrouping.
Referenced by writeDocumentation().
writeMemberGroups() [2/2]
void FileDefImpl::writeMemberGroups (OutputList & ol) [private]
writeMemberPages() [1/2]
void FileDefImpl::writeMemberPages (OutputList & ol) [virtual]
Implements FileDef.
Definition at line 1008 of file filedef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  for (const auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_documentationLists)
    {
      ml->writeDocumentationPage(ol,name(),this);
    }
  }
  ol.popGeneratorState();
}
References OutputList::disableAllBut(), OutputGenerator::Html, m_memberLists, MemberListType_documentationLists, name(), OutputList::popGeneratorState(), and OutputList::pushGeneratorState().
Referenced by writeDocumentation().
writeMemberPages() [2/2]
virtual void FileDefImpl::writeMemberPages (OutputList & ol) [virtual]
Implements FileDef.
writeNamespaceDeclarations() [1/2]
void FileDefImpl::writeNamespaceDeclarations (OutputList & ol, const QCString & title, bool isConstantGroup) [private]
Definition at line 662 of file filedef.cpp.
{
  // write list of namespaces
  m_namespaces.writeDeclaration(ol,title,isConstantGroup);
}
References m_namespaces, title(), and NamespaceLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeNamespaceDeclarations() [2/2]
void FileDefImpl::writeNamespaceDeclarations (OutputList & ol, const QCString & title, bool isConstantGroup) [private]
writeQuickMemberLinks() [1/2]
void FileDefImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const [virtual]
Reimplemented from DefinitionMixin< FileDef >.
Definition at line 1024 of file filedef.cpp.
{
  bool createSubDirs=Config_getBool(CREATE_SUBDIRS);
  ol.writeString(" <div class=\"navtab\">\n");
  ol.writeString(" <table>\n");
  MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
  if (allMemberList)
  {
    for (const auto &md : *allMemberList)
    {
      if (md->getFileDef()==this && md->getNamespaceDef()==0 && md->isLinkable() && !md->isEnumValue())
      {
        if (md->isLinkableInProject())
        {
          if (md==currentMd) // selected item => highlight
          {
            ol.writeString(" <tr><td class=\"navtabHL\">");
          }
          else
          {
            ol.writeString(" <tr><td class=\"navtab\">");
          }
          ol.writeString("<a class=\"navtab\" ");
          ol.writeString("href=\"");
          if (createSubDirs) ol.writeString("../../");
          ol.writeString(addHtmlExtensionIfMissing(md->getOutputFileBase())+"#"+md->anchor());
          ol.writeString("\">");
          ol.writeString(convertToHtml(md->localName()));
          ol.writeString("</a>");
          ol.writeString("</td></tr>\n");
        }
      }
    }
  }
  ol.writeString(" </table>\n");
  ol.writeString(" </div>\n");
}
References addHtmlExtensionIfMissing(), Config_getBool, convertToHtml(), createSubDirs(), getMemberList(), MemberListType_allMembersList, and OutputList::writeString().
writeQuickMemberLinks() [2/2]
virtual void FileDefImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const [virtual]
Reimplemented from DefinitionMixin< FileDef >.
writeSourceBody() [1/2]
void FileDefImpl::writeSourceBody (OutputList & ol, ClangTUParser * clangParser) [virtual]
Implements FileDef.
Definition at line 1112 of file filedef.cpp.
{
  bool filterSourceFiles = Config_getBool(FILTER_SOURCE_FILES);
  DevNullCodeDocInterface devNullIntf;
#if USE_LIBCLANG
  if (Doxygen::clangAssistedParsing && clangParser &&
      (getLanguage()==SrcLangExt_Cpp || getLanguage()==SrcLangExt_ObjC))
  {
    ol.startCodeFragment("DoxyCode");
    clangParser->switchToFile(this);
    clangParser->writeSources(ol,this);
    ol.endCodeFragment("DoxyCode");
  }
  else
#endif
  {
    auto intf = Doxygen::parserManager->getCodeParser(getDefFileExtension());
    intf->resetCodeParserState();
    ol.startCodeFragment("DoxyCode");
    bool needs2PassParsing =
        Doxygen::parseSourcesNeeded && // we need to parse (filtered) sources for cross-references
        !filterSourceFiles && // but user wants to show sources as-is
        !getFileFilter(absFilePath(),TRUE).isEmpty(); // and there is a filter used while parsing
    if (needs2PassParsing)
    {
      // parse code for cross-references only (see bug707641)
      intf->parseCode(devNullIntf,QCString(),
                       fileToString(absFilePath(),TRUE,TRUE),
                       getLanguage(),
                       FALSE,QCString(),this
                      );
    }
    intf->parseCode(ol,QCString(),
        fileToString(absFilePath(),filterSourceFiles,TRUE),
        getLanguage(), // lang
        FALSE, // isExampleBlock
        QCString(), // exampleName
        this, // fileDef
        -1, // startLine
        -1, // endLine
        FALSE, // inlineFragment
        0, // memberDef
        TRUE, // showLineNumbers
        0, // searchCtx
        !needs2PassParsing // collectXRefs
        );
    ol.endCodeFragment("DoxyCode");
  }
}
References absFilePath(), Doxygen::clangAssistedParsing, Config_getBool, OutputList::endCodeFragment(), FALSE, fileToString(), ParserManager::getCodeParser(), DefinitionMixin< FileDef >::getDefFileExtension(), getFileFilter(), DefinitionMixin< FileDef >::getLanguage(), QCString::isEmpty(), Doxygen::parserManager, Doxygen::parseSourcesNeeded, SrcLangExt_Cpp, SrcLangExt_ObjC, OutputList::startCodeFragment(), ClangTUParser::switchToFile(), TRUE, and ClangTUParser::writeSources().
writeSourceBody() [2/2]
virtual void FileDefImpl::writeSourceBody (OutputList & ol, ClangTUParser * clangParser) [virtual]
Implements FileDef.
writeSourceFooter() [1/2]
void FileDefImpl::writeSourceFooter (OutputList & ol) [virtual]
Implements FileDef.
Definition at line 1163 of file filedef.cpp.
{
  ol.endContents();
  endFileWithNavPath(this,ol);
  ol.enableAll();
}
References OutputList::enableAll(), OutputList::endContents(), and endFileWithNavPath().
writeSourceFooter() [2/2]
virtual void FileDefImpl::writeSourceFooter (OutputList & ol) [virtual]
Implements FileDef.
writeSourceHeader() [1/2]
void FileDefImpl::writeSourceHeader (OutputList & ol) [virtual]
Write a source listing of this file to the output
Implements FileDef.
Definition at line 1066 of file filedef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  QCString title = m_docname;
  if (!m_fileVersion.isEmpty())
  {
    title+=(" ("+m_fileVersion+")");
  }
  QCString pageTitle = theTranslator->trSourceFile(title);
  ol.disable(OutputGenerator::Man);
  bool isDocFile = isDocumentationFile();
  bool genSourceFile = !isDocFile && generateSourceFile();
  if (getDirDef())
  {
    startFile(ol,getSourceFileBase(),QCString(),pageTitle,HLI_FileVisible,
        !generateTreeView,
        !isDocFile && genSourceFile ? QCString() : getOutputFileBase());
    if (!generateTreeView)
    {
      getDirDef()->writeNavigationPath(ol);
      ol.endQuickIndices();
    }
    startTitle(ol,getSourceFileBase());
    ol.parseText(name());
    endTitle(ol,getSourceFileBase(),title);
  }
  else
  {
    startFile(ol,getSourceFileBase(),QCString(),pageTitle,HLI_FileVisible,FALSE,
        !isDocFile && genSourceFile ? QCString() : getOutputFileBase());
    startTitle(ol,getSourceFileBase());
    ol.parseText(title);
    endTitle(ol,getSourceFileBase(),QCString());
  }
  ol.startContents();
  if (isLinkable())
  {
    ol.startTextLink(getOutputFileBase(),QCString());
    ol.parseText(theTranslator->trGotoDocumentation());
    ol.endTextLink();
  }
}
References Config_getBool, OutputList::disable(), OutputList::endQuickIndices(), OutputList::endTextLink(), endTitle(), FALSE, generateSourceFile(), getDirDef(), getOutputFileBase(), getSourceFileBase(), HLI_FileVisible, isDocumentationFile(), QCString::isEmpty(), isLinkable(), m_docname, m_fileVersion, OutputGenerator::Man, name(), OutputList::parseText(), OutputList::startContents(), startFile(), OutputList::startTextLink(), startTitle(), theTranslator, title(), Translator::trGotoDocumentation(), Translator::trSourceFile(), and DefinitionMutable::writeNavigationPath().
writeSourceHeader() [2/2]
virtual void FileDefImpl::writeSourceHeader (OutputList & ol) [virtual]
Implements FileDef.
writeSourceLink() [1/2]
void FileDefImpl::writeSourceLink (OutputList & ol) [private]
Definition at line 647 of file filedef.cpp.
{
  //printf("%s: generateSourceFile()=%d\n",qPrint(name()),generateSourceFile());
  if (generateSourceFile())
  {
    ol.disableAllBut(OutputGenerator::Html);
    ol.startParagraph();
    ol.startTextLink(includeName(),QCString());
    ol.parseText(theTranslator->trGotoSourceCode());
    ol.endTextLink();
    ol.endParagraph();
    ol.enableAll();
  }
}
References OutputList::disableAllBut(), OutputList::enableAll(), OutputList::endParagraph(), OutputList::endTextLink(), generateSourceFile(), OutputGenerator::Html, includeName(), OutputList::parseText(), OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, and Translator::trGotoSourceCode().
Referenced by writeDocumentation().
writeSourceLink() [2/2]
void FileDefImpl::writeSourceLink (OutputList & ol) [private]
writeSummaryLinks() [1/2]
void FileDefImpl::writeSummaryLinks (OutputList & ol) const [virtual]
Reimplemented from DefinitionMixin< FileDef >.
Definition at line 746 of file filedef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  bool first=TRUE;
  SrcLangExt lang=getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::File))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    if (lde->kind()==LayoutDocEntry::FileClasses && m_classes.declVisible() && ls)
    {
      QCString label = "nested-classes";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::FileInterfaces && m_interfaces.declVisible() && ls)
    {
      QCString label = "interfaces";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::FileStructs && m_structs.declVisible() && ls)
    {
      QCString label = "structs";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::FileExceptions && m_exceptions.declVisible() && ls)
    {
      QCString label = "exceptions";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::FileNamespaces && m_namespaces.declVisible(false) && ls)
    {
      QCString label = "namespaces";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::FileConcepts && m_concepts.declVisible() && ls)
    {
      QCString label = "concepts";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd)
      {
        MemberList * ml = getMemberList(lmd->type);
        if (ml && ml->declVisible())
        {
          ol.writeSummaryLink(QCString(),MemberList::listTypeAsString(ml->listType()),lmd->title(lang),first);
          first=FALSE;
        }
      }
    }
  }
  if (!first)
  {
    ol.writeString(" </div>\n");
  }
  ol.popGeneratorState();
}
References ConceptLinkedRefMap::declVisible(), MemberList::declVisible(), NamespaceLinkedRefMap::declVisible(), ClassLinkedRefMap::declVisible(), OutputList::disableAllBut(), FALSE, LayoutDocManager::File, LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileStructs, DefinitionMixin< FileDef >::getLanguage(), getMemberList(), OutputGenerator::Html, LayoutDocManager::instance(), MemberList::listType(), MemberList::listTypeAsString(), m_classes, m_concepts, m_exceptions, m_interfaces, m_namespaces, m_structs, LayoutDocEntry::MemberDecl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), TRUE, LayoutDocEntryMemberDecl::type, OutputList::writeString(), and OutputList::writeSummaryLink().
writeSummaryLinks() [2/2]
virtual void FileDefImpl::writeSummaryLinks (OutputList & ol) const [virtual]
Reimplemented from DefinitionMixin< FileDef >.
writeTagFile() [1/2]
void FileDefImpl::writeTagFile (TextStream & t) [virtual]
Implements FileDef.
Definition at line 318 of file filedef.cpp.
{
  tagFile << " <compound kind=\"file\">\n";
  tagFile << " <name>" << convertToXML(name()) << "</name>\n";
  tagFile << " <path>" << convertToXML(stripFromPath(getPath())) << "</path>\n";
  tagFile << " <filename>" << addHtmlExtensionIfMissing(getOutputFileBase()) << "</filename>\n";
  for (const auto &ii : m_includeList)
  {
    const FileDef *fd=ii.fileDef;
    if (fd && fd->isLinkable() && !fd->isReference())
    {
      bool isIDLorJava = FALSE;
      SrcLangExt lang = fd->getLanguage();
      isIDLorJava = lang==SrcLangExt_IDL || lang==SrcLangExt_Java;
      const char *locStr = (ii.local || isIDLorJava) ? "yes" : "no";
      const char *impStr = (ii.imported || isIDLorJava) ? "yes" : "no";
      tagFile << " <includes id=\""
        << convertToXML(fd->getOutputFileBase()) << "\" "
        << "name=\"" << convertToXML(fd->name()) << "\" "
        << "local=\"" << locStr << "\" "
        << "imported=\"" << impStr << "\">"
        << convertToXML(ii.includeName)
        << "</includes>\n";
    }
  }
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::File))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::FileClasses:
        {
          writeClassesToTagFile(tagFile, m_classes);
        }
        break;
      case LayoutDocEntry::FileInterfaces:
        {
          writeClassesToTagFile(tagFile, m_interfaces);
        }
        break;
      case LayoutDocEntry::FileStructs:
        {
          writeClassesToTagFile(tagFile, m_structs);
        }
        break;
      case LayoutDocEntry::FileExceptions:
        {
          writeClassesToTagFile(tagFile, m_exceptions);
        }
        break;
      case LayoutDocEntry::FileConcepts:
        {
          for (const auto *nd : m_concepts)
          {
            if (nd->isLinkableInProject())
            {
              tagFile << " <concept>" << convertToXML(nd->name()) << "</concept>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::FileNamespaces:
        {
          for (const auto *nd : m_namespaces)
          {
            if (nd->isLinkableInProject())
            {
              tagFile << " <namespace>" << convertToXML(nd->name()) << "</namespace>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            MemberList * ml = getMemberList(lmd->type);
            if (ml)
            {
              ml->writeTagFile(tagFile);
            }
          }
        }
        break;
      case LayoutDocEntry::MemberGroups:
        {
          for (const auto &mg : m_memberGroups)
          {
            mg->writeTagFile(tagFile);
          }
        }
        break;
      default:
        break;
    }
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << " </compound>\n";
}
References addHtmlExtensionIfMissing(), convertToXML(), FALSE, LayoutDocManager::File, LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileStructs, Definition::getLanguage(), getMemberList(), getOutputFileBase(), FileDef::getOutputFileBase(), getPath(), LayoutDocManager::instance(), FileDef::isLinkable(), Definition::isReference(), m_classes, m_concepts, m_exceptions, m_includeList, m_interfaces, m_memberGroups, m_namespaces, m_structs, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberGroups, name(), FileDef::name(), SrcLangExt_IDL, SrcLangExt_Java, stripFromPath(), LayoutDocEntryMemberDecl::type, writeClassesToTagFile(), DefinitionMixin< FileDef >::writeDocAnchorsToTagFile(), and MemberList::writeTagFile().
writeTagFile() [2/2]
virtual void FileDefImpl::writeTagFile (TextStream & t) [virtual]
Implements FileDef.
Member Data Documentation
m_classes
ClassLinkedRefMap FileDefImpl::m_classes [private]
Definition at line 184 of file filedef.cpp.
Referenced by getClasses(), insertClass(), sortMemberLists(), writeDocumentation(), writeInlineClasses(), writeSummaryLinks(), and writeTagFile().
m_concepts
ConceptLinkedRefMap FileDefImpl::m_concepts [private]
Definition at line 188 of file filedef.cpp.
Referenced by getConcepts(), insertConcept(), writeConcepts(), writeSummaryLinks(), and writeTagFile().
m_dir
DirDef * FileDefImpl::m_dir [private]
Definition at line 180 of file filedef.cpp.
Referenced by FileDefImpl(), getDirDef(), and setDirDef().
m_docname
QCString FileDefImpl::m_docname [private]
Definition at line 174 of file filedef.cpp.
Referenced by docName(), FileDefImpl(), writeDocumentation(), and writeSourceHeader().
m_exceptions
ClassLinkedRefMap FileDefImpl::m_exceptions [private]
Definition at line 187 of file filedef.cpp.
Referenced by insertClass(), sortMemberLists(), writeDocumentation(), writeSummaryLinks(), and writeTagFile().
m_fileName
QCString FileDefImpl::m_fileName [private]
Definition at line 173 of file filedef.cpp.
Referenced by FileDefImpl(), fileName(), and name().
m_filePath
QCString FileDefImpl::m_filePath [private]
Definition at line 169 of file filedef.cpp.
Referenced by absFilePath(), acquireFileVersion(), FileDefImpl(), and getSourceFileBase().
m_fileVersion
QCString FileDefImpl::m_fileVersion [private]
Definition at line 178 of file filedef.cpp.
Referenced by acquireFileVersion(), fileVersion(), getVersion(), writeDocumentation(), and writeSourceHeader().
m_inclByDepFileName
QCString FileDefImpl::m_inclByDepFileName [private]
Definition at line 171 of file filedef.cpp.
Referenced by includedByDependencyGraphFileName(), and setDiskName().
m_inclDepFileName
QCString FileDefImpl::m_inclDepFileName [private]
Definition at line 170 of file filedef.cpp.
Referenced by includeDependencyGraphFileName(), and setDiskName().
m_includedByList
IncludeInfoList FileDefImpl::m_includedByList [private]
Definition at line 165 of file filedef.cpp.
Referenced by addIncludedByDependency(), includedByFileList(), and sortMemberLists().
m_includedByMap
IncludeInfoMap FileDefImpl::m_includedByMap [private]
Definition at line 164 of file filedef.cpp.
Referenced by addIncludedByDependency().
m_includeList
IncludeInfoList FileDefImpl::m_includeList [private]
Definition at line 163 of file filedef.cpp.
Referenced by addIncludeDependency(), addIncludedUsingDirectives(), includeFileList(), writeIncludeFiles(), and writeTagFile().
m_includeMap
IncludeInfoMap FileDefImpl::m_includeMap [private]
Definition at line 162 of file filedef.cpp.
Referenced by addIncludeDependency(), and isIncluded().
m_interfaces
ClassLinkedRefMap FileDefImpl::m_interfaces [private]
Definition at line 185 of file filedef.cpp.
Referenced by insertClass(), sortMemberLists(), writeDocumentation(), writeSummaryLinks(), and writeTagFile().
m_isSource
bool FileDefImpl::m_isSource [private]
Definition at line 177 of file filedef.cpp.
Referenced by FileDefImpl(), and isSource().
m_memberGroups
MemberGroupList FileDefImpl::m_memberGroups [private]
Definition at line 182 of file filedef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), countMembers(), distributeMemberGroupDocumentation(), findSectionsInDocumentation(), getMemberGroups(), sortMemberLists(), writeMemberGroups(), and writeTagFile().
m_memberLists
MemberLists FileDefImpl::m_memberLists [private]
Definition at line 181 of file filedef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), addMemberToList(), countMembers(), findSectionsInDocumentation(), getMemberList(), getMemberLists(), insertMember(), sortMemberLists(), and writeMemberPages().
m_namespaces
NamespaceLinkedRefMap FileDefImpl::m_namespaces [private]
Definition at line 183 of file filedef.cpp.
Referenced by getNamespaces(), insertNamespace(), sortMemberLists(), writeNamespaceDeclarations(), writeSummaryLinks(), and writeTagFile().
m_outputDiskName
QCString FileDefImpl::m_outputDiskName [private]
Definition at line 172 of file filedef.cpp.
Referenced by getOutputFileBase(), getSourceFileBase(), and setDiskName().
m_package
PackageDef * FileDefImpl::m_package [private]
Definition at line 179 of file filedef.cpp.
Referenced by FileDefImpl(), packageDef(), and setPackageDef().
m_path
QCString FileDefImpl::m_path [private]
Definition at line 168 of file filedef.cpp.
Referenced by FileDefImpl(), and getPath().
m_srcDefMap
DefinitionLineMap FileDefImpl::m_srcDefMap [private]
Definition at line 175 of file filedef.cpp.
Referenced by addSourceRef(), and getSourceDefinition().
m_srcMemberMap
MemberDefLineMap FileDefImpl::m_srcMemberMap [private]
Definition at line 176 of file filedef.cpp.
Referenced by addSourceRef(), and getSourceMember().
m_structs
ClassLinkedRefMap FileDefImpl::m_structs [private]
Definition at line 186 of file filedef.cpp.
Referenced by insertClass(), sortMemberLists(), writeDocumentation(), writeSummaryLinks(), and writeTagFile().
m_subGrouping
bool FileDefImpl::m_subGrouping [private]
Definition at line 189 of file filedef.cpp.
Referenced by addMembersToMemberGroup(), FileDefImpl(), subGrouping(), and writeMemberGroups().
m_usingDeclList
LinkedRefMap< const ClassDef > FileDefImpl::m_usingDeclList [private]
Definition at line 167 of file filedef.cpp.
Referenced by addIncludedUsingDirectives(), addUsingDeclaration(), and getUsedClasses().
m_usingDirList
LinkedRefMap< const NamespaceDef > FileDefImpl::m_usingDirList [private]
Definition at line 166 of file filedef.cpp.
Referenced by addIncludedUsingDirectives(), addUsingDirective(), combineUsingRelations(), and getUsedNamespaces().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/filedef.cpp
doxygen/src/filedef.cpp