GroupDefImpl Class Reference
Public Member Functions
GroupDefImpl (const QCString &fileName, int line, const QCString &name, const QCString &title, const QCString &refFileName=QCString())
virtual ~GroupDefImpl ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual QCString displayName (bool=TRUE) const
virtual QCString groupTitle () const
virtual void setGroupTitle (const QCString &newtitle)
virtual bool hasGroupTitle () const
virtual void addFile (const FileDef *def)
virtual bool addClass (const ClassDef *def)
virtual bool addConcept (const ConceptDef *def)
virtual bool addNamespace (const NamespaceDef *def)
virtual void addGroup (const GroupDef *def)
virtual void addPage (const PageDef *def)
virtual void addExample (const PageDef *def)
virtual void addDir (DirDef *dd)
virtual bool insertMember (const MemberDef *def, bool docOnly=FALSE)
virtual void removeMember (MemberDef *md)
virtual bool findGroup (const GroupDef *def) const
virtual void writeDocumentation (OutputList &ol)
virtual void writeMemberPages (OutputList &ol)
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const
virtual void writeTagFile (TextStream &)
virtual size_t numDocMembers () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool isASubGroup () const
virtual void computeAnchors ()
virtual void countMembers ()
virtual void addMembersToMemberGroup ()
virtual void distributeMemberGroupDocumentation ()
virtual void findSectionsInDocumentation ()
virtual void addListReferences ()
virtual void sortMemberLists ()
virtual bool subGrouping () const
virtual void setGroupScope (Definition *d)
virtual Definition * getGroupScope () const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberGroupList & getMemberGroups () const
virtual const FileList & getFiles () const
virtual const ClassLinkedRefMap & getClasses () const
virtual const ConceptLinkedRefMap & getConcepts () const
virtual const NamespaceLinkedRefMap & getNamespaces () const
virtual const GroupList & getSubGroups () const
virtual const PageLinkedRefMap & getPages () const
virtual const DirList & getDirs () const
virtual const PageLinkedRefMap & getExamples () const
virtual bool hasDetailedDescription () const
virtual void sortSubGroups ()
GroupDefImpl (const QCString &fileName, int line, const QCString &name, const QCString &title, const QCString &refFileName=QCString())
virtual ~GroupDefImpl ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual QCString displayName (bool=TRUE) const
virtual QCString groupTitle () const
virtual void setGroupTitle (const QCString &newtitle)
virtual bool hasGroupTitle () const
virtual void addFile (const FileDef *def)
virtual bool addClass (const ClassDef *def)
virtual bool addConcept (const ConceptDef *def)
virtual bool addNamespace (const NamespaceDef *def)
virtual void addGroup (const GroupDef *def)
virtual void addPage (const PageDef *def)
virtual void addExample (const PageDef *def)
virtual void addDir (DirDef *dd)
virtual bool insertMember (const MemberDef *def, bool docOnly=FALSE)
virtual void removeMember (MemberDef *md)
virtual bool findGroup (const GroupDef *def) const
virtual void writeDocumentation (OutputList &ol)
virtual void writeMemberPages (OutputList &ol)
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const
virtual void writeTagFile (TextStream &)
virtual size_t numDocMembers () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool isASubGroup () const
virtual void computeAnchors ()
virtual void countMembers ()
virtual void addMembersToMemberGroup ()
virtual void distributeMemberGroupDocumentation ()
virtual void findSectionsInDocumentation ()
virtual void addListReferences ()
virtual void sortMemberLists ()
virtual bool subGrouping () const
virtual void setGroupScope (Definition *d)
virtual Definition * getGroupScope () const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberGroupList & getMemberGroups () const
virtual const FileList & getFiles () const
virtual const ClassLinkedRefMap & getClasses () const
virtual const ConceptLinkedRefMap & getConcepts () const
virtual const NamespaceLinkedRefMap & getNamespaces () const
virtual const GroupList & getSubGroups () const
virtual const PageLinkedRefMap & getPages () const
virtual const DirList & getDirs () const
virtual const PageLinkedRefMap & getExamples () const
virtual bool hasDetailedDescription () const
virtual void sortSubGroups ()
Private Member Functions
void addMemberListToGroup (MemberList *, bool(MemberDef::*)() const)
void addMemberToList (MemberListType lt, const MemberDef *md)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void removeMemberFromList (MemberListType lt, MemberDef *md)
void writeGroupGraph (OutputList &ol)
void writeFiles (OutputList &ol, const QCString &title)
void writeNamespaces (OutputList &ol, const QCString &title)
void writeNestedGroups (OutputList &ol, const QCString &title)
void writeDirs (OutputList &ol, const QCString &title)
void writeClasses (OutputList &ol, const QCString &title)
void writeConcepts (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void writePageDocumentation (OutputList &ol)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void writeMemberGroups (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void writeSummaryLinks (OutputList &ol) const
void updateLanguage (const Definition *)
void addMemberListToGroup (MemberList *, bool(MemberDef::*)() const)
void addMemberToList (MemberListType lt, const MemberDef *md)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void removeMemberFromList (MemberListType lt, MemberDef *md)
void writeGroupGraph (OutputList &ol)
void writeFiles (OutputList &ol, const QCString &title)
void writeNamespaces (OutputList &ol, const QCString &title)
void writeNestedGroups (OutputList &ol, const QCString &title)
void writeDirs (OutputList &ol, const QCString &title)
void writeClasses (OutputList &ol, const QCString &title)
void writeConcepts (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void writePageDocumentation (OutputList &ol)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void writeMemberGroups (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void writeSummaryLinks (OutputList &ol) const
void updateLanguage (const Definition *)
Private Attributes
QCString m_title
bool m_titleSet
QCString m_fileName
FileList m_fileList
ClassLinkedRefMap m_classes
ConceptLinkedRefMap m_concepts
NamespaceLinkedRefMap m_namespaces
GroupList m_groups
PageLinkedRefMap m_pages
PageLinkedRefMap m_examples
DirList m_dirList
MemberList m_allMemberList
MemberNameInfoLinkedMap m_allMemberNameInfoLinkedMap
Definition * m_groupScope
MemberLists m_memberLists
MemberGroupList m_memberGroups
bool m_subGrouping
Additional Inherited Members
Detailed Description
Definition at line 52 of file groupdef.cpp.
Constructor & Destructor Documentation
GroupDefImpl() [1/2]
GroupDefImpl::GroupDefImpl (const QCString & fileName, int line, const QCString & name, const QCString & title, const QCString & refFileName = QCString())
Definition at line 171 of file groupdef.cpp.
                                                : DefinitionMixin(df,dl,1,na),
                    m_allMemberList(MemberListType_allMembersList,MemberListContainer::Group)
{
  if (!refFileName.isEmpty())
  {
    m_fileName=stripExtension(refFileName);
  }
  else
  {
    m_fileName = convertNameToFile(QCString("group_")+na);
  }
  setGroupTitle(t);
  //visited = 0;
  m_groupScope = 0;
  m_subGrouping=Config_getBool(SUBGROUPING);
}
References Config_getBool, convertNameToFile(), Group, QCString::isEmpty(), m_fileName, m_groupScope, m_subGrouping, setGroupTitle(), and stripExtension().
 GroupDefImpl() [1/2]
GroupDefImpl::~GroupDefImpl () [virtual]
Definition at line 190 of file groupdef.cpp.
{
}
GroupDefImpl() [2/2]
GroupDefImpl::GroupDefImpl (const QCString & fileName, int line, const QCString & name, const QCString & title, const QCString & refFileName = QCString())
 GroupDefImpl() [2/2]
virtual GroupDefImpl::~GroupDefImpl () [virtual]
Member Function Documentation
addClass() [1/2]
bool GroupDefImpl::addClass (const ClassDef * def) [virtual]
Implements GroupDef.
Definition at line 251 of file groupdef.cpp.
{
  if (cd->isHidden()) return FALSE;
  updateLanguage(cd);
  QCString qn = cd->name();
  if (m_classes.find(qn)==0)
  {
    m_classes.add(qn,cd);
    return TRUE;
  }
  return FALSE;
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), FALSE, LinkedRefMap< T, Hash, KeyEqual, Map >::find(), Definition::isHidden(), m_classes, Definition::name(), TRUE, and updateLanguage().
addClass() [2/2]
virtual bool GroupDefImpl::addClass (const ClassDef * def) [virtual]
Implements GroupDef.
addConcept() [1/2]
bool GroupDefImpl::addConcept (const ConceptDef * def) [virtual]
Implements GroupDef.
Definition at line 264 of file groupdef.cpp.
{
  if (cd->isHidden()) return FALSE;
  QCString qn = cd->name();
  if (m_concepts.find(qn)==0)
  {
    m_concepts.add(qn,cd);
    return TRUE;
  }
  return FALSE;
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), FALSE, LinkedRefMap< T, Hash, KeyEqual, Map >::find(), Definition::isHidden(), m_concepts, Definition::name(), and TRUE.
addConcept() [2/2]
virtual bool GroupDefImpl::addConcept (const ConceptDef * def) [virtual]
Implements GroupDef.
addDir() [1/2]
void GroupDefImpl::addDir (DirDef * dd) [virtual]
Implements GroupDef.
Definition at line 289 of file groupdef.cpp.
{
  if (def->isHidden()) return;
  m_dirList.push_back(def);
}
References Definition::isHidden(), and m_dirList.
addDir() [2/2]
virtual void GroupDefImpl::addDir (DirDef * dd) [virtual]
Implements GroupDef.
addExample() [1/2]
void GroupDefImpl::addExample (const PageDef * def) [virtual]
Implements GroupDef.
Definition at line 303 of file groupdef.cpp.
{
  if (def->isHidden()) return;
  m_examples.add(def->name(),def);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::isHidden(), m_examples, and Definition::name().
addExample() [2/2]
virtual void GroupDefImpl::addExample (const PageDef * def) [virtual]
Implements GroupDef.
addFile() [1/2]
void GroupDefImpl::addFile (const FileDef * def) [virtual]
Implements GroupDef.
Definition at line 237 of file groupdef.cpp.
{
  bool sortBriefDocs = Config_getBool(SORT_BRIEF_DOCS);
  if (def->isHidden()) return;
  updateLanguage(def);
  if (sortBriefDocs)
    m_fileList.insert(std::upper_bound(m_fileList.begin(), m_fileList.end(), def,
                                         [](const auto &fd1, const auto &fd2)
                                         { return qstricmp(fd1->name(),fd2->name())<0; }),
                       def);
  else
    m_fileList.push_back(def);
}
References Config_getBool, Definition::isHidden(), m_fileList, and updateLanguage().
addFile() [2/2]
virtual void GroupDefImpl::addFile (const FileDef * def) [virtual]
Implements GroupDef.
addGroup() [1/2]
void GroupDefImpl::addGroup (const GroupDef * def) [virtual]
Implements GroupDef.
Definition at line 565 of file groupdef.cpp.
{
  //printf("adding group '%s' to group '%s'\n",qPrint(def->name()),qPrint(name()));
  //if (Config_getBool(SORT_MEMBER_DOCS))
  // groupList->inSort(def);
  //else
  m_groups.push_back(def);
}
References m_groups.
addGroup() [2/2]
virtual void GroupDefImpl::addGroup (const GroupDef * def) [virtual]
Implements GroupDef.
addListReferences() [1/2]
void GroupDefImpl::addListReferences () [virtual]
Implements GroupDef.
Definition at line 1552 of file groupdef.cpp.
{
  {
    const RefItemVector &xrefItems = xrefListItems();
    addRefItem(xrefItems,
             getOutputFileBase(),
             theTranslator->trGroup(TRUE,TRUE),
             getOutputFileBase(),name(),
             QCString(),
             0
            );
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->addListReferences(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_documentationLists)
    {
      ml->addListReferences(this);
    }
  }
}
References addRefItem(), getOutputFileBase(), m_memberGroups, m_memberLists, MemberListType_documentationLists, DefinitionMixin< GroupDef >::name(), theTranslator, Translator::trGroup(), TRUE, and DefinitionMixin< GroupDef >::xrefListItems().
addListReferences() [2/2]
virtual void GroupDefImpl::addListReferences () [virtual]
Implements GroupDef.
addMemberListToGroup() [1/2]
void GroupDefImpl::addMemberListToGroup (MemberList * , bool(MemberDef::*)() const) [private]
addMemberListToGroup() [2/2]
void GroupDefImpl::addMemberListToGroup (MemberList * , bool(MemberDef::*)() const) [private]
addMembersToMemberGroup() [1/2]
void GroupDefImpl::addMembersToMemberGroup () [virtual]
Implements GroupDef.
Definition at line 310 of file groupdef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_declarationLists)
    {
      ::addMembersToMemberGroup(ml.get(),&m_memberGroups,this);
    }
  }
}
References addMembersToMemberGroup(), m_memberGroups, m_memberLists, and MemberListType_declarationLists.
Referenced by addMembersToMemberGroup().
addMembersToMemberGroup() [2/2]
virtual void GroupDefImpl::addMembersToMemberGroup () [virtual]
Implements GroupDef.
addMemberToList() [1/2]
void GroupDefImpl::addMemberToList (MemberListType lt, const MemberDef * md) [private]
Definition at line 1577 of file groupdef.cpp.
{
  bool sortBriefDocs = Config_getBool(SORT_BRIEF_DOCS);
  bool sortMemberDocs = Config_getBool(SORT_MEMBER_DOCS);
  const auto &ml = m_memberLists.get(lt,MemberListContainer::Group);
  ml->setNeedsSorting(
      ((ml->listType()&MemberListType_declarationLists) && sortBriefDocs) ||
      ((ml->listType()&MemberListType_documentationLists) && sortMemberDocs));
  ml->push_back(md);
}
References Config_getBool, MemberLists::get(), Group, m_memberLists, MemberListType_declarationLists, and MemberListType_documentationLists.
Referenced by insertMember().
addMemberToList() [2/2]
void GroupDefImpl::addMemberToList (MemberListType lt, const MemberDef * md) [private]
addNamespace() [1/2]
bool GroupDefImpl::addNamespace (const NamespaceDef * def) [virtual]
Implements GroupDef.
Definition at line 276 of file groupdef.cpp.
{
  //printf("adding namespace hidden=%d\n",def->isHidden());
  if (def->isHidden()) return false;
  if (m_namespaces.find(def->name())==0)
  {
    updateLanguage(def);
    m_namespaces.add(def->name(),def);
    return true;
  }
  return false;
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), LinkedRefMap< T, Hash, KeyEqual, Map >::find(), Definition::isHidden(), m_namespaces, Definition::name(), and updateLanguage().
addNamespace() [2/2]
virtual bool GroupDefImpl::addNamespace (const NamespaceDef * def) [virtual]
Implements GroupDef.
addPage() [1/2]
void GroupDefImpl::addPage (const PageDef * def) [virtual]
Implements GroupDef.
Definition at line 295 of file groupdef.cpp.
{
  if (def->isHidden()) return;
  //printf("Making page %s part of a group\n",qPrint(def->name));
  m_pages.add(def->name(),def);
  const_cast<PageDef*>(def)->makePartOfGroup(this);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::isHidden(), m_pages, DefinitionMixin< GroupDef >::makePartOfGroup(), and Definition::name().
addPage() [2/2]
virtual void GroupDefImpl::addPage (const PageDef * def) [virtual]
Implements GroupDef.
anchor() [1/2]
virtual QCString GroupDefImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements GroupDef.
Definition at line 61 of file groupdef.cpp.
{ return QCString(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString GroupDefImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements GroupDef.
Definition at line 61 of file groupdef.cpp.
{ return QCString(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
codeSymbolType() [1/2]
virtual CodeSymbolType GroupDefImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 59 of file groupdef.cpp.
{ return CodeSymbolType::Default; }
References Default.
codeSymbolType() [2/2]
virtual CodeSymbolType GroupDefImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 59 of file groupdef.cpp.
{ return CodeSymbolType::Default; }
References Default.
computeAnchors() [1/2]
void GroupDefImpl::computeAnchors () [virtual]
Compute the HTML anchor names for all members in the group
Implements GroupDef.
Definition at line 605 of file groupdef.cpp.
{
  //printf("GroupDefImpl::computeAnchors()\n");
  m_allMemberList.setAnchors();
}
References m_allMemberList, and MemberList::setAnchors().
computeAnchors() [2/2]
virtual void GroupDefImpl::computeAnchors () [virtual]
Implements GroupDef.
countMembers() [1/2]
void GroupDefImpl::countMembers () [virtual]
Implements GroupDef.
Definition at line 579 of file groupdef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    ml->countDecMembers();
    ml->countDocMembers();
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->countDecMembers();
    mg->countDocMembers();
  }
}
References m_memberGroups, and m_memberLists.
countMembers() [2/2]
virtual void GroupDefImpl::countMembers () [virtual]
Implements GroupDef.
definitionType() [1/2]
virtual DefType GroupDefImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements GroupDef.
Definition at line 58 of file groupdef.cpp.
{ return TypeGroup; }
References Definition::TypeGroup.
definitionType() [2/2]
virtual DefType GroupDefImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements GroupDef.
Definition at line 58 of file groupdef.cpp.
{ return TypeGroup; }
References Definition::TypeGroup.
displayName() [1/2]
virtual QCString GroupDefImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements GroupDef.
Definition at line 62 of file groupdef.cpp.
{ return hasGroupTitle() ? m_title : DefinitionMixin::name(); }
References hasGroupTitle(), m_title, and DefinitionMixin< Base >::name().
displayName() [2/2]
virtual QCString GroupDefImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements GroupDef.
Definition at line 62 of file groupdef.cpp.
{ return hasGroupTitle() ? m_title : DefinitionMixin::name(); }
References hasGroupTitle(), m_title, and DefinitionMixin< Base >::name().
distributeMemberGroupDocumentation() [1/2]
void GroupDefImpl::distributeMemberGroupDocumentation () [virtual]
Implements GroupDef.
Definition at line 210 of file groupdef.cpp.
{
  for (const auto &mg : m_memberGroups)
  {
    mg->distributeMemberGroupDocumentation();
  }
}
References m_memberGroups.
distributeMemberGroupDocumentation() [2/2]
virtual void GroupDefImpl::distributeMemberGroupDocumentation () [virtual]
Implements GroupDef.
endMemberDeclarations() [1/2]
void GroupDefImpl::endMemberDeclarations (OutputList & ol) [private]
Definition at line 1013 of file groupdef.cpp.
{
  ol.endMemberSections();
}
References OutputList::endMemberSections().
Referenced by writeDocumentation().
endMemberDeclarations() [2/2]
void GroupDefImpl::endMemberDeclarations (OutputList & ol) [private]
endMemberDocumentation() [1/2]
void GroupDefImpl::endMemberDocumentation (OutputList & ol) [private]
Definition at line 1029 of file groupdef.cpp.
{
  //printf("** GroupDefImpl::endMemberDocumentation()\n");
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.popGeneratorState();
    Doxygen::suppressDocWarnings = FALSE;
  }
}
References Config_getBool, FALSE, OutputList::popGeneratorState(), and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
endMemberDocumentation() [2/2]
void GroupDefImpl::endMemberDocumentation (OutputList & ol) [private]
findGroup() [1/2]
bool GroupDefImpl::findGroup (const GroupDef * def) const [virtual]
Implements GroupDef.
Definition at line 549 of file groupdef.cpp.
{
  if (this==def)
  {
    return TRUE;
  }
  for (const auto &gd : m_groups)
  {
    if (gd->findGroup(def))
    {
      return TRUE;
    }
  }
  return FALSE;
}
References FALSE, m_groups, and TRUE.
findGroup() [2/2]
virtual bool GroupDefImpl::findGroup (const GroupDef * def) const [virtual]
Implements GroupDef.
findSectionsInDocumentation() [1/2]
void GroupDefImpl::findSectionsInDocumentation () [virtual]
Implements GroupDef.
Definition at line 218 of file groupdef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
  for (const auto &mg : m_memberGroups)
  {
    mg->findSectionsInDocumentation(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_declarationLists)
    {
      ml->findSectionsInDocumentation(this);
    }
  }
}
References DefinitionMixin< GroupDef >::briefDescription(), DefinitionMixin< GroupDef >::docFile(), docFindSections(), DefinitionMixin< GroupDef >::documentation(), m_memberGroups, m_memberLists, and MemberListType_declarationLists.
findSectionsInDocumentation() [2/2]
virtual void GroupDefImpl::findSectionsInDocumentation () [virtual]
Implements GroupDef.
getClasses() [1/2]
virtual const ClassLinkedRefMap & GroupDefImpl::getClasses () const [inline], [virtual]
Implements GroupDef.
Definition at line 106 of file groupdef.cpp.
{ return m_classes; }
References m_classes.
getClasses() [2/2]
virtual const ClassLinkedRefMap & GroupDefImpl::getClasses () const [inline], [virtual]
Implements GroupDef.
Definition at line 106 of file groupdef.cpp.
{ return m_classes; }
References m_classes.
getConcepts() [1/2]
virtual const ConceptLinkedRefMap & GroupDefImpl::getConcepts () const [inline], [virtual]
Implements GroupDef.
Definition at line 107 of file groupdef.cpp.
{ return m_concepts; }
References m_concepts.
getConcepts() [2/2]
virtual const ConceptLinkedRefMap & GroupDefImpl::getConcepts () const [inline], [virtual]
Implements GroupDef.
Definition at line 107 of file groupdef.cpp.
{ return m_concepts; }
References m_concepts.
getDirs() [1/2]
virtual const DirList & GroupDefImpl::getDirs () const [inline], [virtual]
Implements GroupDef.
Definition at line 111 of file groupdef.cpp.
{ return m_dirList; }
References m_dirList.
getDirs() [2/2]
virtual const DirList & GroupDefImpl::getDirs () const [inline], [virtual]
Implements GroupDef.
Definition at line 111 of file groupdef.cpp.
{ return m_dirList; }
References m_dirList.
getExamples() [1/2]
virtual const PageLinkedRefMap & GroupDefImpl::getExamples () const [inline], [virtual]
Implements GroupDef.
Definition at line 112 of file groupdef.cpp.
{ return m_examples; }
References m_examples.
getExamples() [2/2]
virtual const PageLinkedRefMap & GroupDefImpl::getExamples () const [inline], [virtual]
Implements GroupDef.
Definition at line 112 of file groupdef.cpp.
{ return m_examples; }
References m_examples.
getFiles() [1/2]
virtual const FileList & GroupDefImpl::getFiles () const [inline], [virtual]
Implements GroupDef.
Definition at line 105 of file groupdef.cpp.
{ return m_fileList; }
References m_fileList.
getFiles() [2/2]
virtual const FileList & GroupDefImpl::getFiles () const [inline], [virtual]
Implements GroupDef.
Definition at line 105 of file groupdef.cpp.
{ return m_fileList; }
References m_fileList.
getGroupScope() [1/2]
virtual Definition * GroupDefImpl::getGroupScope () const [inline], [virtual]
Implements GroupDef.
Definition at line 97 of file groupdef.cpp.
{ return m_groupScope; }
References m_groupScope.
getGroupScope() [2/2]
virtual Definition * GroupDefImpl::getGroupScope () const [inline], [virtual]
Implements GroupDef.
Definition at line 97 of file groupdef.cpp.
{ return m_groupScope; }
References m_groupScope.
getMemberGroups() [1/2]
virtual const MemberGroupList & GroupDefImpl::getMemberGroups () const [inline], [virtual]
Implements GroupDef.
Definition at line 103 of file groupdef.cpp.
{ return m_memberGroups; }
References m_memberGroups.
getMemberGroups() [2/2]
virtual const MemberGroupList & GroupDefImpl::getMemberGroups () const [inline], [virtual]
Implements GroupDef.
Definition at line 103 of file groupdef.cpp.
{ return m_memberGroups; }
References m_memberGroups.
getMemberList() [1/2]
MemberList * GroupDefImpl::getMemberList (MemberListType lt) const [virtual]
Implements GroupDef.
Definition at line 1680 of file groupdef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()==lt)
    {
      return ml.get();
    }
  }
  return 0;
}
References m_memberLists.
Referenced by removeMemberFromList(), writeMemberDeclarations(), writeMemberDocumentation(), writeSummaryLinks(), and writeTagFile().
getMemberList() [2/2]
virtual MemberList * GroupDefImpl::getMemberList (MemberListType lt) const [virtual]
Implements GroupDef.
getMemberLists() [1/2]
virtual const MemberLists & GroupDefImpl::getMemberLists () const [inline], [virtual]
Implements GroupDef.
Definition at line 100 of file groupdef.cpp.
{ return m_memberLists; }
References m_memberLists.
getMemberLists() [2/2]
virtual const MemberLists & GroupDefImpl::getMemberLists () const [inline], [virtual]
Implements GroupDef.
Definition at line 100 of file groupdef.cpp.
{ return m_memberLists; }
References m_memberLists.
getNamespaces() [1/2]
virtual const NamespaceLinkedRefMap & GroupDefImpl::getNamespaces () const [inline], [virtual]
Implements GroupDef.
Definition at line 108 of file groupdef.cpp.
{ return m_namespaces; }
References m_namespaces.
getNamespaces() [2/2]
virtual const NamespaceLinkedRefMap & GroupDefImpl::getNamespaces () const [inline], [virtual]
Implements GroupDef.
Definition at line 108 of file groupdef.cpp.
{ return m_namespaces; }
References m_namespaces.
getOutputFileBase() [1/2]
QCString GroupDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements GroupDef.
Definition at line 1547 of file groupdef.cpp.
{
  return m_fileName;
}
References m_fileName.
Referenced by addListReferences(), writeDocumentation(), and writeTagFile().
getOutputFileBase() [2/2]
virtual QCString GroupDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements GroupDef.
getPages() [1/2]
virtual const PageLinkedRefMap & GroupDefImpl::getPages () const [inline], [virtual]
Implements GroupDef.
Definition at line 110 of file groupdef.cpp.
{ return m_pages; }
References m_pages.
getPages() [2/2]
virtual const PageLinkedRefMap & GroupDefImpl::getPages () const [inline], [virtual]
Implements GroupDef.
Definition at line 110 of file groupdef.cpp.
{ return m_pages; }
References m_pages.
getSubGroups() [1/2]
virtual const GroupList & GroupDefImpl::getSubGroups () const [inline], [virtual]
Implements GroupDef.
Definition at line 109 of file groupdef.cpp.
{ return m_groups; }
References m_groups.
getSubGroups() [2/2]
virtual const GroupList & GroupDefImpl::getSubGroups () const [inline], [virtual]
Implements GroupDef.
Definition at line 109 of file groupdef.cpp.
{ return m_groups; }
References m_groups.
groupTitle() [1/2]
virtual QCString GroupDefImpl::groupTitle () const [inline], [virtual]
Implements GroupDef.
Definition at line 63 of file groupdef.cpp.
{ return m_title; }
References m_title.
groupTitle() [2/2]
virtual QCString GroupDefImpl::groupTitle () const [inline], [virtual]
Implements GroupDef.
Definition at line 63 of file groupdef.cpp.
{ return m_title; }
References m_title.
hasDetailedDescription() [1/2]
bool GroupDefImpl::hasDetailedDescription () const [virtual]
Implements GroupDef.
Definition at line 1748 of file groupdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  return ((!briefDescription().isEmpty() && repeatBrief) ||
         !documentation().isEmpty() ||
         !inbodyDocumentation().isEmpty()) &&
         (m_pages.size()!=numDocMembers());
}
References DefinitionMixin< GroupDef >::briefDescription(), Config_getBool, DefinitionMixin< GroupDef >::documentation(), DefinitionMixin< GroupDef >::inbodyDocumentation(), m_pages, numDocMembers(), and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
Referenced by writeBriefDescription().
hasDetailedDescription() [2/2]
virtual bool GroupDefImpl::hasDetailedDescription () const [virtual]
Implements GroupDef.
hasGroupTitle() [1/2]
virtual bool GroupDefImpl::hasGroupTitle () const [inline], [virtual]
Implements GroupDef.
Definition at line 65 of file groupdef.cpp.
{ return m_titleSet; }
References m_titleSet.
Referenced by displayName().
hasGroupTitle() [2/2]
virtual bool GroupDefImpl::hasGroupTitle () const [inline], [virtual]
Implements GroupDef.
Definition at line 65 of file groupdef.cpp.
{ return m_titleSet; }
References m_titleSet.
insertMember() [1/2]
bool GroupDefImpl::insertMember (const MemberDef * def, bool docOnly = FALSE) [virtual]
Implements GroupDef.
Definition at line 322 of file groupdef.cpp.
{
  if (md->isHidden()) return FALSE;
  updateLanguage(md);
  //printf("GroupDef(%s)::insertMember(%s)\n", qPrint(title), qPrint(md->name()));
  MemberNameInfo *mni = m_allMemberNameInfoLinkedMap.add(md->name());
  for (auto &srcMi : *mni)
  {
    const MemberDef *srcMd = srcMi->memberDef();
    if (srcMd==md) return FALSE; // already added before!
    bool sameScope = srcMd->getOuterScope()==md->getOuterScope() || // same class or namespace
        // both inside a file => definition and declaration do not have to be in the same file
         (srcMd->getOuterScope()->definitionType()==Definition::TypeFile &&
             md->getOuterScope()->definitionType()==Definition::TypeFile);
    const ArgumentList &srcMdAl = srcMd->argumentList();
    const ArgumentList &mdAl = md->argumentList();
    const ArgumentList &tSrcMdAl = srcMd->templateArguments();
    const ArgumentList &tMdAl = md->templateArguments();
    if (srcMd->isFunction() && md->isFunction() && // both are a function
        (tSrcMdAl.size()==tMdAl.size()) && // same number of template arguments
        matchArguments2(srcMd->getOuterScope(),srcMd->getFileDef(),&srcMdAl,
                        md->getOuterScope(),md->getFileDef(),&mdAl,
                        TRUE,srcMd->getLanguage()
                       ) && // matching parameters
        sameScope // both are found in the same scope
       )
    {
      MemberDefMutable *mdm = toMemberDefMutable(md);
      if (mdm && srcMd->getGroupAlias()==0)
      {
        mdm->setGroupAlias(srcMd);
      }
      else if (mdm && md!=srcMd->getGroupAlias())
      {
        mdm->setGroupAlias(srcMd->getGroupAlias());
      }
      return FALSE; // member is the same as one that is already added
    }
  }
  mni->push_back(std::make_unique<MemberInfo>(md,md->protection(),md->virtualness(),FALSE));
  //printf("Added member!\n");
  m_allMemberList.push_back(md);
  switch(md->memberType())
  {
    case MemberType_Variable:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decVarMembers,md);
      }
      addMemberToList(MemberListType_docVarMembers,md);
      break;
    case MemberType_Function:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decFuncMembers,md);
      }
      addMemberToList(MemberListType_docFuncMembers,md);
      break;
    case MemberType_Typedef:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decTypedefMembers,md);
      }
      addMemberToList(MemberListType_docTypedefMembers,md);
      break;
    case MemberType_Enumeration:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decEnumMembers,md);
      }
      addMemberToList(MemberListType_docEnumMembers,md);
      break;
    case MemberType_EnumValue:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decEnumValMembers,md);
      }
      addMemberToList(MemberListType_docEnumValMembers,md);
      break;
    case MemberType_Define:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decDefineMembers,md);
      }
      addMemberToList(MemberListType_docDefineMembers,md);
      break;
    case MemberType_Signal:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decSignalMembers,md);
      }
      addMemberToList(MemberListType_docSignalMembers,md);
      break;
    case MemberType_Slot:
      if (md->protection()==Public)
      {
        if (!docOnly)
        {
          addMemberToList(MemberListType_decPubSlotMembers,md);
        }
        addMemberToList(MemberListType_docPubSlotMembers,md);
      }
      else if (md->protection()==Protected)
      {
        if (!docOnly)
        {
          addMemberToList(MemberListType_decProSlotMembers,md);
        }
        addMemberToList(MemberListType_docProSlotMembers,md);
      }
      else
      {
        if (!docOnly)
        {
          addMemberToList(MemberListType_decPriSlotMembers,md);
        }
        addMemberToList(MemberListType_docPriSlotMembers,md);
      }
      break;
    case MemberType_Event:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decEventMembers,md);
      }
      addMemberToList(MemberListType_docEventMembers,md);
      break;
    case MemberType_Property:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decPropMembers,md);
      }
      addMemberToList(MemberListType_docPropMembers,md);
      break;
    case MemberType_Friend:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decFriendMembers,md);
      }
      addMemberToList(MemberListType_docFriendMembers,md);
      break;
    default:
      err("GroupDefImpl::insertMembers(): "
           "member '%s' (typeid=%d) with scope '%s' inserted in group scope '%s'!\n",
           qPrint(md->name()),md->memberType(),
           md->getClassDef() ? qPrint(md->getClassDef()->name()) : "",
           qPrint(name()));
  }
  return TRUE;
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), addMemberToList(), MemberDef::argumentList(), Definition::definitionType(), err(), FALSE, MemberDef::getClassDef(), MemberDef::getFileDef(), MemberDef::getGroupAlias(), Definition::getLanguage(), Definition::getOuterScope(), MemberDef::isFunction(), Definition::isHidden(), m_allMemberList, m_allMemberNameInfoLinkedMap, matchArguments2(), MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decEnumValMembers, MemberListType_decEventMembers, MemberListType_decFriendMembers, MemberListType_decFuncMembers, MemberListType_decPriSlotMembers, MemberListType_decPropMembers, MemberListType_decProSlotMembers, MemberListType_decPubSlotMembers, MemberListType_decSignalMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docEnumMembers, MemberListType_docEnumValMembers, MemberListType_docEventMembers, MemberListType_docFriendMembers, MemberListType_docFuncMembers, MemberListType_docPriSlotMembers, MemberListType_docPropMembers, MemberListType_docProSlotMembers, MemberListType_docPubSlotMembers, MemberListType_docSignalMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberDef::memberType(), MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Property, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, DefinitionMixin< GroupDef >::name(), Definition::name(), Protected, MemberDef::protection(), Public, MemberVector::push_back(), MemberNameInfo::push_back(), qPrint(), MemberDefMutable::setGroupAlias(), ArgumentList::size(), MemberDef::templateArguments(), toMemberDefMutable(), TRUE, Definition::TypeFile, updateLanguage(), and MemberDef::virtualness().
insertMember() [2/2]
virtual bool GroupDefImpl::insertMember (const MemberDef * def, bool docOnly = FALSE) [virtual]
Implements GroupDef.
isASubGroup() [1/2]
bool GroupDefImpl::isASubGroup () const [virtual]
Implements GroupDef.
Definition at line 574 of file groupdef.cpp.
{
  return !partOfGroups().empty();
}
References DefinitionMixin< GroupDef >::partOfGroups().
isASubGroup() [2/2]
virtual bool GroupDefImpl::isASubGroup () const [virtual]
Implements GroupDef.
isLinkable() [1/2]
bool GroupDefImpl::isLinkable () const [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements GroupDef.
Definition at line 1733 of file groupdef.cpp.
{
  return hasUserDocumentation();
}
References DefinitionMixin< GroupDef >::hasUserDocumentation().
Referenced by isLinkableInProject().
isLinkable() [2/2]
virtual bool GroupDefImpl::isLinkable () const [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements GroupDef.
isLinkableInProject() [1/2]
bool GroupDefImpl::isLinkableInProject () const [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements GroupDef.
Definition at line 1728 of file groupdef.cpp.
{
  return !isReference() && isLinkable();
}
References isLinkable(), and DefinitionMixin< GroupDef >::isReference().
isLinkableInProject() [2/2]
virtual bool GroupDefImpl::isLinkableInProject () const [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements GroupDef.
numDocMembers() [1/2]
size_t GroupDefImpl::numDocMembers () const [virtual]
Implements GroupDef.
Definition at line 593 of file groupdef.cpp.
{
  return m_fileList.size()+
         m_classes.size()+
         m_namespaces.size()+
         m_groups.size()+
         m_allMemberList.size()+
         m_pages.size()+
         m_examples.size();
}
References m_allMemberList, m_classes, m_examples, m_fileList, m_groups, m_namespaces, m_pages, LinkedRefMap< T, Hash, KeyEqual, Map >::size(), and MemberVector::size().
Referenced by hasDetailedDescription(), and writeDetailedDescription().
numDocMembers() [2/2]
virtual size_t GroupDefImpl::numDocMembers () const [virtual]
Implements GroupDef.
removeMember() [1/2]
void GroupDefImpl::removeMember (MemberDef * md) [virtual]
Implements GroupDef.
Definition at line 475 of file groupdef.cpp.
{
  // fprintf(stderr, "GroupDef(%s)::removeMember(%s)\n", qPrint(title), qPrint(md->name()));
  MemberNameInfo *mni = m_allMemberNameInfoLinkedMap.find(md->name());
  if (mni)
  {
    m_allMemberNameInfoLinkedMap.del(md->name());
    removeMemberFromList(MemberListType_allMembersList,md);
    switch(md->memberType())
    {
      case MemberType_Variable:
    removeMemberFromList(MemberListType_decVarMembers,md);
        removeMemberFromList(MemberListType_docVarMembers,md);
        break;
      case MemberType_Function:
        removeMemberFromList(MemberListType_decFuncMembers,md);
        removeMemberFromList(MemberListType_docFuncMembers,md);
        break;
      case MemberType_Typedef:
        removeMemberFromList(MemberListType_decTypedefMembers,md);
        removeMemberFromList(MemberListType_docTypedefMembers,md);
        break;
      case MemberType_Enumeration:
        removeMemberFromList(MemberListType_decEnumMembers,md);
        removeMemberFromList(MemberListType_docEnumMembers,md);
        break;
      case MemberType_EnumValue:
        removeMemberFromList(MemberListType_decEnumValMembers,md);
        removeMemberFromList(MemberListType_docEnumValMembers,md);
        break;
      case MemberType_Define:
        removeMemberFromList(MemberListType_decDefineMembers,md);
        removeMemberFromList(MemberListType_docDefineMembers,md);
        break;
      case MemberType_Signal:
        removeMemberFromList(MemberListType_decSignalMembers,md);
        removeMemberFromList(MemberListType_docSignalMembers,md);
        break;
      case MemberType_Slot:
        if (md->protection()==Public)
        {
          removeMemberFromList(MemberListType_decPubSlotMembers,md);
          removeMemberFromList(MemberListType_docPubSlotMembers,md);
        }
        else if (md->protection()==Protected)
        {
          removeMemberFromList(MemberListType_decProSlotMembers,md);
          removeMemberFromList(MemberListType_docProSlotMembers,md);
        }
        else
        {
          removeMemberFromList(MemberListType_decPriSlotMembers,md);
          removeMemberFromList(MemberListType_docPriSlotMembers,md);
        }
        break;
      case MemberType_Event:
        removeMemberFromList(MemberListType_decEventMembers,md);
        removeMemberFromList(MemberListType_docEventMembers,md);
        break;
      case MemberType_Property:
        removeMemberFromList(MemberListType_decPropMembers,md);
        removeMemberFromList(MemberListType_docPropMembers,md);
        break;
      case MemberType_Friend:
        removeMemberFromList(MemberListType_decFriendMembers,md);
        removeMemberFromList(MemberListType_docFriendMembers,md);
        break;
      default:
        err("GroupDefImpl::removeMember(): unexpected member remove in file!\n");
    }
  }
}
References LinkedMap< T, Hash, KeyEqual, Map >::del(), err(), LinkedMap< T, Hash, KeyEqual, Map >::find(), m_allMemberNameInfoLinkedMap, MemberListType_allMembersList, MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decEnumValMembers, MemberListType_decEventMembers, MemberListType_decFriendMembers, MemberListType_decFuncMembers, MemberListType_decPriSlotMembers, MemberListType_decPropMembers, MemberListType_decProSlotMembers, MemberListType_decPubSlotMembers, MemberListType_decSignalMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docEnumMembers, MemberListType_docEnumValMembers, MemberListType_docEventMembers, MemberListType_docFriendMembers, MemberListType_docFuncMembers, MemberListType_docPriSlotMembers, MemberListType_docPropMembers, MemberListType_docProSlotMembers, MemberListType_docPubSlotMembers, MemberListType_docSignalMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberDef::memberType(), MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Property, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, Definition::name(), Protected, MemberDef::protection(), Public, and removeMemberFromList().
removeMember() [2/2]
virtual void GroupDefImpl::removeMember (MemberDef * md) [virtual]
Implements GroupDef.
removeMemberFromList() [1/2]
void GroupDefImpl::removeMemberFromList (MemberListType lt, MemberDef * md) [private]
Definition at line 1714 of file groupdef.cpp.
{
  MemberList *ml = getMemberList(lt);
  if (ml) ml->remove(md);
}
References getMemberList(), and MemberVector::remove().
Referenced by removeMember().
removeMemberFromList() [2/2]
void GroupDefImpl::removeMemberFromList (MemberListType lt, MemberDef * md) [private]
setGroupScope() [1/2]
virtual void GroupDefImpl::setGroupScope (Definition * d) [inline], [virtual]
Implements GroupDef.
Definition at line 96 of file groupdef.cpp.
{ m_groupScope = d; }
References m_groupScope.
setGroupScope() [2/2]
virtual void GroupDefImpl::setGroupScope (Definition * d) [inline], [virtual]
Implements GroupDef.
Definition at line 96 of file groupdef.cpp.
{ m_groupScope = d; }
References m_groupScope.
setGroupTitle() [1/2]
void GroupDefImpl::setGroupTitle (const QCString & newtitle) [virtual]
Implements GroupDef.
Definition at line 194 of file groupdef.cpp.
{
  if (!t.isEmpty())
  {
    m_title = t;
    m_titleSet = TRUE;
  }
  else
  {
    m_title = name();
    m_title[0]=static_cast<char>(toupper(m_title[0]));
    m_titleSet = FALSE;
  }
}
References FALSE, QCString::isEmpty(), m_title, m_titleSet, DefinitionMixin< GroupDef >::name(), caseconvert::toupper, and TRUE.
Referenced by GroupDefImpl().
setGroupTitle() [2/2]
virtual void GroupDefImpl::setGroupTitle (const QCString & newtitle) [virtual]
Implements GroupDef.
sortMemberLists() [1/2]
void GroupDefImpl::sortMemberLists () [virtual]
Implements GroupDef.
Definition at line 1648 of file groupdef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->needsSorting()) { ml->sort(); ml->setNeedsSorting(FALSE); }
  }
  if (Config_getBool(SORT_BRIEF_DOCS))
  {
    std::sort(m_dirList.begin(), m_dirList.end(), compareDirDefs);
    auto classComp = [](const ClassLinkedRefMap::Ptr &c1,const ClassLinkedRefMap::Ptr &c2)
    {
      return Config_getBool(SORT_BY_SCOPE_NAME) ?
        qstricmp(c1->name(), c2->name())<0 :
        qstricmp(c1->className(), c2->className())<0;
    };
    std::sort(m_classes.begin(), m_classes.end(), classComp);
    auto namespaceComp = [](const NamespaceLinkedRefMap::Ptr &n1,const NamespaceLinkedRefMap::Ptr &n2)
    {
      return qstricmp(n1->name(),n2->name())<0;
    };
    std::sort(m_namespaces.begin(),m_namespaces.end(),namespaceComp);
  }
  else
  {
    groupClassesWithSameScope(m_classes);
    groupClassesWithSameScope(m_namespaces);
  }
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::begin(), ClassDef::className(), compareDirDefs(), Config_getBool, LinkedRefMap< T, Hash, KeyEqual, Map >::end(), FALSE, groupClassesWithSameScope(), m_classes, m_dirList, m_memberLists, m_namespaces, Definition::name(), and qstricmp().
sortMemberLists() [2/2]
virtual void GroupDefImpl::sortMemberLists () [virtual]
Implements GroupDef.
sortSubGroups() [1/2]
void GroupDefImpl::sortSubGroups () [virtual]
Implements GroupDef.
Definition at line 1720 of file groupdef.cpp.
{
  std::sort(m_groups.begin(),
            m_groups.end(),
            [](const auto &g1,const auto &g2)
            { return g1->groupTitle() < g2->groupTitle(); });
}
References m_groups.
sortSubGroups() [2/2]
virtual void GroupDefImpl::sortSubGroups () [virtual]
Implements GroupDef.
startMemberDeclarations() [1/2]
void GroupDefImpl::startMemberDeclarations (OutputList & ol) [private]
Definition at line 1008 of file groupdef.cpp.
{
  ol.startMemberSections();
}
References OutputList::startMemberSections().
Referenced by writeDocumentation().
startMemberDeclarations() [2/2]
void GroupDefImpl::startMemberDeclarations (OutputList & ol) [private]
startMemberDocumentation() [1/2]
void GroupDefImpl::startMemberDocumentation (OutputList & ol) [private]
Definition at line 1018 of file groupdef.cpp.
{
  //printf("** GroupDefImpl::startMemberDocumentation()\n");
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.pushGeneratorState();
    ol.disable(OutputGenerator::Html);
    Doxygen::suppressDocWarnings = TRUE;
  }
}
References Config_getBool, OutputList::disable(), OutputGenerator::Html, OutputList::pushGeneratorState(), Doxygen::suppressDocWarnings, and TRUE.
Referenced by writeDocumentation().
startMemberDocumentation() [2/2]
void GroupDefImpl::startMemberDocumentation (OutputList & ol) [private]
subGrouping() [1/2]
virtual bool GroupDefImpl::subGrouping () const [inline], [virtual]
Implements GroupDef.
Definition at line 94 of file groupdef.cpp.
{ return m_subGrouping; }
References m_subGrouping.
subGrouping() [2/2]
virtual bool GroupDefImpl::subGrouping () const [inline], [virtual]
Implements GroupDef.
Definition at line 94 of file groupdef.cpp.
{ return m_subGrouping; }
References m_subGrouping.
updateLanguage() [1/2]
void GroupDefImpl::updateLanguage (const Definition * d) [private]
Definition at line 1740 of file groupdef.cpp.
{
  if (getLanguage()==SrcLangExt_Unknown && d->getLanguage()!=SrcLangExt_Unknown)
  {
    setLanguage(d->getLanguage());
  }
}
References DefinitionMixin< GroupDef >::getLanguage(), Definition::getLanguage(), DefinitionMixin< GroupDef >::setLanguage(), and SrcLangExt_Unknown.
Referenced by addClass(), addFile(), addNamespace(), and insertMember().
updateLanguage() [2/2]
void GroupDefImpl::updateLanguage (const Definition *) [private]
writeAuthorSection() [1/2]
void GroupDefImpl::writeAuthorSection (OutputList & ol) [private]
Definition at line 1039 of file groupdef.cpp.
{
  // write Author section (Man only)
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Man);
  ol.startGroupHeader();
  ol.parseText(theTranslator->trAuthor(TRUE,TRUE));
  ol.endGroupHeader();
  ol.parseText(theTranslator->trGeneratedAutomatically(Config_getString(PROJECT_NAME)));
  ol.popGeneratorState();
}
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), and TRUE.
Referenced by writeDocumentation().
writeAuthorSection() [2/2]
void GroupDefImpl::writeAuthorSection (OutputList & ol) [private]
writeBriefDescription() [1/2]
void GroupDefImpl::writeBriefDescription (OutputList & ol) [private]
Definition at line 795 of file groupdef.cpp.
{
  if (hasBriefDescription())
  {
    auto parser { createDocParser() };
    auto ast { validatingParseDoc(*parser.get(),
                                     briefFile(),briefLine(),this,0,
                                     briefDescription(),TRUE,FALSE,
                                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startParagraph();
      ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Man);
      ol.writeString(" - ");
      ol.popGeneratorState();
      ol.writeDoc(ast.get(),this,0);
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::RTF);
      ol.writeString(" \n");
      ol.enable(OutputGenerator::RTF);
      if (hasDetailedDescription())
      {
        ol.disableAllBut(OutputGenerator::Html);
        ol.startTextLink(QCString(),"details");
        ol.parseText(theTranslator->trMore());
        ol.endTextLink();
      }
      ol.popGeneratorState();
      ol.endParagraph();
    }
  }
  ol.writeSynopsis();
}
References DefinitionMixin< GroupDef >::briefDescription(), DefinitionMixin< GroupDef >::briefFile(), DefinitionMixin< GroupDef >::briefLine(), Config_getBool, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), FALSE, DefinitionMixin< GroupDef >::hasBriefDescription(), hasDetailedDescription(), OutputGenerator::Html, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, Translator::trMore(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeBriefDescription() [2/2]
void GroupDefImpl::writeBriefDescription (OutputList & ol) [private]
writeClasses() [1/2]
void GroupDefImpl::writeClasses (OutputList & ol, const QCString & title) [private]
Definition at line 960 of file groupdef.cpp.
{
  // write list of classes
  m_classes.writeDeclaration(ol,0,title,FALSE);
}
References FALSE, m_classes, and ClassLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeClasses() [2/2]
void GroupDefImpl::writeClasses (OutputList & ol, const QCString & title) [private]
writeConcepts() [1/2]
void GroupDefImpl::writeConcepts (OutputList & ol, const QCString & title) [private]
Definition at line 966 of file groupdef.cpp.
{
  // write list of concepts
  m_concepts.writeDeclaration(ol,title,FALSE);
}
References FALSE, m_concepts, and ConceptLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeConcepts() [2/2]
void GroupDefImpl::writeConcepts (OutputList & ol, const QCString & title) [private]
writeDetailedDescription() [1/2]
void GroupDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) [private]
Definition at line 731 of file groupdef.cpp.
{
  if ((!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF))
      || !documentation().isEmpty() || !inbodyDocumentation().isEmpty()
     )
  {
    ol.pushGeneratorState();
    if (m_pages.size()!=numDocMembers()) // not only pages -> classical layout
    {
      ol.pushGeneratorState();
        ol.disable(OutputGenerator::Html);
        ol.writeRuler();
      ol.popGeneratorState();
      ol.pushGeneratorState();
        ol.disableAllBut(OutputGenerator::Html);
        ol.writeAnchor(QCString(),"details");
      ol.popGeneratorState();
    }
    else
    {
      ol.disableAllBut(OutputGenerator::Man); // always print title for man page
    }
    ol.startGroupHeader();
    ol.parseText(title);
    ol.endGroupHeader();
    ol.popGeneratorState();
    // repeat brief description
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF))
    {
      ol.generateDoc(briefFile(),briefLine(),this,0,briefDescription(),FALSE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    // write separator between brief and details
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF) &&
        !documentation().isEmpty())
    {
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::Man);
      ol.disable(OutputGenerator::RTF);
      // ol.newParagraph(); // FIXME:PARA
      ol.enableAll();
      ol.disableAllBut(OutputGenerator::Man);
      ol.enable(OutputGenerator::Latex);
      ol.writeString("\n\n");
      ol.popGeneratorState();
    }
    // write detailed documentation
    if (!documentation().isEmpty())
    {
      ol.generateDoc(docFile(),docLine(),this,0,documentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    // write inbody documentation
    if (!inbodyDocumentation().isEmpty())
    {
      ol.generateDoc(inbodyFile(),inbodyLine(),this,0,inbodyDocumentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
  }
}
References DefinitionMixin< GroupDef >::briefDescription(), DefinitionMixin< GroupDef >::briefFile(), DefinitionMixin< GroupDef >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< GroupDef >::docFile(), DefinitionMixin< GroupDef >::docLine(), DefinitionMixin< GroupDef >::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endGroupHeader(), FALSE, OutputList::generateDoc(), OutputGenerator::Html, DefinitionMixin< GroupDef >::inbodyDocumentation(), DefinitionMixin< GroupDef >::inbodyFile(), DefinitionMixin< GroupDef >::inbodyLine(), OutputGenerator::Latex, m_pages, OutputGenerator::Man, numDocMembers(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, LinkedRefMap< T, Hash, KeyEqual, Map >::size(), OutputList::startGroupHeader(), TRUE, OutputList::writeAnchor(), OutputList::writeRuler(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDetailedDescription() [2/2]
void GroupDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) [private]
writeDirs() [1/2]
void GroupDefImpl::writeDirs (OutputList & ol, const QCString & title) [private]
Definition at line 928 of file groupdef.cpp.
{
  // write list of directories
  if (!m_dirList.empty())
  {
    ol.startMemberHeader("dirs");
    ol.parseText(title);
    ol.endMemberHeader();
    ol.startMemberList();
    for(const auto dd : m_dirList)
    {
      if (!dd->hasDocumentation()) continue;
      ol.startMemberDeclaration();
      ol.startMemberItem(dd->getOutputFileBase(),0);
      ol.parseText(theTranslator->trDir(FALSE,TRUE));
      ol.insertMemberAlign();
      ol.writeObjectLink(dd->getReference(),dd->getOutputFileBase(),QCString(),dd->shortName());
      ol.endMemberItem();
      if (!dd->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
      {
        ol.startMemberDescription(dd->getOutputFileBase());
        ol.generateDoc(briefFile(),briefLine(),dd,0,dd->briefDescription(),FALSE,FALSE,
                       QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
        ol.endMemberDescription();
      }
      ol.endMemberDeclaration(QCString(),QCString());
    }
    ol.endMemberList();
  }
}
References DefinitionMixin< GroupDef >::briefFile(), DefinitionMixin< GroupDef >::briefLine(), Config_getBool, OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), FALSE, OutputList::generateDoc(), OutputList::insertMemberAlign(), m_dirList, OutputList::parseText(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trDir(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeDirs() [2/2]
void GroupDefImpl::writeDirs (OutputList & ol, const QCString & title) [private]
writeDocumentation() [1/2]
void GroupDefImpl::writeDocumentation (OutputList & ol) [virtual]
Implements GroupDef.
Definition at line 1101 of file groupdef.cpp.
{
  //bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  ol.pushGeneratorState();
  startFile(ol,getOutputFileBase(),name(),m_title,HLI_Modules);
  ol.startHeaderSection();
  writeSummaryLinks(ol);
  ol.startTitleHead(getOutputFileBase());
  ol.pushGeneratorState();
  ol.disable(OutputGenerator::Man);
  ol.parseText(m_title);
  ol.popGeneratorState();
  addGroupListToTitle(ol,this);
  ol.pushGeneratorState();
  ol.disable(OutputGenerator::Man);
  ol.endTitleHead(getOutputFileBase(),m_title);
  ol.popGeneratorState();
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Man);
  ol.endTitleHead(getOutputFileBase(),name());
  if (!m_title.isEmpty())
  {
    ol.writeString(" - ");
    ol.parseText(m_title);
  }
  ol.popGeneratorState();
  ol.endHeaderSection();
  ol.startContents();
  //---------------------------------------- start flexible part -------------------------------
  SrcLangExt lang=getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Group))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
        startMemberDeclarations(ol);
        break;
      case LayoutDocEntry::GroupClasses:
        if (ls) writeClasses(ol,ls->title(lang));
        break;
      case LayoutDocEntry::GroupConcepts:
        if (ls) writeConcepts(ol,ls->title(lang));
        break;
      case LayoutDocEntry::GroupInlineClasses:
        writeInlineClasses(ol);
        break;
      case LayoutDocEntry::GroupNamespaces:
        if (ls) writeNamespaces(ol,ls->title(lang));
        break;
      case LayoutDocEntry::MemberGroups:
        writeMemberGroups(ol);
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            writeMemberDeclarations(ol,lmd->type,lmd->title(lang));
          }
        }
        break;
      case LayoutDocEntry::MemberDeclEnd:
        endMemberDeclarations(ol);
        break;
      case LayoutDocEntry::DetailedDesc:
        if (ls) writeDetailedDescription(ol,ls->title(lang));
        break;
      case LayoutDocEntry::MemberDefStart:
        startMemberDocumentation(ol);
        break;
      case LayoutDocEntry::MemberDef:
        {
          const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
          if (lmd)
          {
            writeMemberDocumentation(ol,lmd->type,lmd->title(lang));
          }
        }
        break;
      case LayoutDocEntry::MemberDefEnd:
        endMemberDocumentation(ol);
        break;
      case LayoutDocEntry::GroupNestedGroups:
        if (ls) writeNestedGroups(ol,ls->title(lang));
        break;
      case LayoutDocEntry::GroupPageDocs:
        writePageDocumentation(ol);
        break;
      case LayoutDocEntry::GroupDirs:
        if (ls) writeDirs(ol,ls->title(lang));
        break;
      case LayoutDocEntry::GroupFiles:
        if (ls) writeFiles(ol,ls->title(lang));
        break;
      case LayoutDocEntry::GroupGraph:
        writeGroupGraph(ol);
        break;
      case LayoutDocEntry::AuthorSection:
        writeAuthorSection(ol);
        break;
      case LayoutDocEntry::ClassIncludes:
      case LayoutDocEntry::ClassInheritanceGraph:
      case LayoutDocEntry::ClassNestedClasses:
      case LayoutDocEntry::ClassCollaborationGraph:
      case LayoutDocEntry::ClassAllMembersLink:
      case LayoutDocEntry::ClassUsedFiles:
      case LayoutDocEntry::ClassInlineClasses:
      case LayoutDocEntry::NamespaceNestedNamespaces:
      case LayoutDocEntry::NamespaceNestedConstantGroups:
      case LayoutDocEntry::NamespaceClasses:
      case LayoutDocEntry::NamespaceConcepts:
      case LayoutDocEntry::NamespaceInterfaces:
      case LayoutDocEntry::NamespaceStructs:
      case LayoutDocEntry::NamespaceExceptions:
      case LayoutDocEntry::NamespaceInlineClasses:
      case LayoutDocEntry::ConceptDefinition:
      case LayoutDocEntry::FileClasses:
      case LayoutDocEntry::FileConcepts:
      case LayoutDocEntry::FileInterfaces:
      case LayoutDocEntry::FileStructs:
      case LayoutDocEntry::FileExceptions:
      case LayoutDocEntry::FileNamespaces:
      case LayoutDocEntry::FileConstantGroups:
      case LayoutDocEntry::FileIncludes:
      case LayoutDocEntry::FileIncludeGraph:
      case LayoutDocEntry::FileIncludedByGraph:
      case LayoutDocEntry::FileSourceLink:
      case LayoutDocEntry::FileInlineClasses:
      case LayoutDocEntry::DirSubDirs:
      case LayoutDocEntry::DirFiles:
      case LayoutDocEntry::DirGraph:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::Group entry list\n",lde->kind());
        break;
    }
  }
  //---------------------------------------- end flexible part -------------------------------
  endFile(ol);
  ol.popGeneratorState();
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    m_allMemberList.sort();
    writeMemberPages(ol);
  }
}
References addGroupListToTitle(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, LayoutDocEntry::ConceptDefinition, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, OutputList::disable(), OutputList::disableAllBut(), endFile(), OutputList::endHeaderSection(), endMemberDeclarations(), endMemberDocumentation(), OutputList::endTitleHead(), err(), LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, LayoutDocEntry::FileStructs, DefinitionMixin< GroupDef >::getLanguage(), getOutputFileBase(), LayoutDocManager::Group, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, HLI_Modules, LayoutDocManager::instance(), QCString::isEmpty(), m_allMemberList, m_title, OutputGenerator::Man, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, DefinitionMixin< GroupDef >::name(), LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, LayoutDocEntry::NamespaceStructs, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), MemberVector::sort(), OutputList::startContents(), startFile(), OutputList::startHeaderSection(), startMemberDeclarations(), startMemberDocumentation(), OutputList::startTitleHead(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeClasses(), writeConcepts(), writeDetailedDescription(), writeDirs(), writeFiles(), writeGroupGraph(), writeInlineClasses(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), writeMemberPages(), writeNamespaces(), writeNestedGroups(), writePageDocumentation(), OutputList::writeString(), and writeSummaryLinks().
writeDocumentation() [2/2]
virtual void GroupDefImpl::writeDocumentation (OutputList & ol) [virtual]
Implements GroupDef.
writeFiles() [1/2]
void GroupDefImpl::writeFiles (OutputList & ol, const QCString & title) [private]
Definition at line 851 of file groupdef.cpp.
{
  // write list of files
  if (!m_fileList.empty())
  {
    ol.startMemberHeader("files");
    ol.parseText(title);
    ol.endMemberHeader();
    ol.startMemberList();
    for (const auto &fd : m_fileList)
    {
      if (!fd->hasDocumentation()) continue;
      ol.startMemberDeclaration();
      ol.startMemberItem(fd->getOutputFileBase(),0);
      ol.docify(theTranslator->trFile(FALSE,TRUE)+" ");
      ol.insertMemberAlign();
      ol.writeObjectLink(fd->getReference(),fd->getOutputFileBase(),QCString(),fd->name());
      ol.endMemberItem();
      if (!fd->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
      {
        ol.startMemberDescription(fd->getOutputFileBase());
        ol.generateDoc(briefFile(),briefLine(),fd,0,fd->briefDescription(),FALSE,FALSE,
                       QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
        ol.endMemberDescription();
      }
      ol.endMemberDeclaration(QCString(),QCString());
    }
    ol.endMemberList();
  }
}
References DefinitionMixin< GroupDef >::briefFile(), DefinitionMixin< GroupDef >::briefLine(), Config_getBool, OutputList::docify(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), FALSE, OutputList::generateDoc(), OutputList::insertMemberAlign(), m_fileList, OutputList::parseText(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trFile(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeFiles() [2/2]
void GroupDefImpl::writeFiles (OutputList & ol, const QCString & title) [private]
writeGroupGraph() [1/2]
void GroupDefImpl::writeGroupGraph (OutputList & ol) [private]
Definition at line 831 of file groupdef.cpp.
{
  if (Config_getBool(HAVE_DOT) /*&& Config_getBool(GROUP_GRAPHS)*/)
  {
    DotGroupCollaboration graph(this);
    if (!graph.isTrivial())
    {
      msg("Generating dependency graph for group %s\n",qPrint(qualifiedName()));
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::Man);
      //ol.startParagraph();
      ol.startGroupCollaboration();
      ol.parseText(theTranslator->trCollaborationDiagram(m_title));
      ol.endGroupCollaboration(graph);
      //ol.endParagraph();
      ol.popGeneratorState();
    }
  }
}
References Config_getBool, OutputList::disable(), OutputList::endGroupCollaboration(), DotGroupCollaboration::isTrivial(), m_title, OutputGenerator::Man, msg(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), qPrint(), DefinitionMixin< GroupDef >::qualifiedName(), OutputList::startGroupCollaboration(), theTranslator, and Translator::trCollaborationDiagram().
Referenced by writeDocumentation().
writeGroupGraph() [2/2]
void GroupDefImpl::writeGroupGraph (OutputList & ol) [private]
writeInlineClasses() [1/2]
void GroupDefImpl::writeInlineClasses (OutputList & ol) [private]
Definition at line 972 of file groupdef.cpp.
{
  m_classes.writeDocumentation(ol);
}
References m_classes, and ClassLinkedRefMap::writeDocumentation().
Referenced by writeDocumentation().
writeInlineClasses() [2/2]
void GroupDefImpl::writeInlineClasses (OutputList & ol) [private]
writeMemberDeclarations() [1/2]
void GroupDefImpl::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title) [private]
Definition at line 1692 of file groupdef.cpp.
{
  bool optimizeVhdl = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  MemberList * ml = getMemberList(lt);
  if (optimizeVhdl && ml)
  {
    VhdlDocGen::writeVhdlDeclarations(ml,ol,this,0,0,0);
    return;
  }
  if (ml)
  {
    ml->writeDeclarations(ol,0,0,0,this,title,QCString());
  }
}
References Config_getBool, getMemberList(), MemberList::writeDeclarations(), and VhdlDocGen::writeVhdlDeclarations().
Referenced by writeDocumentation().
writeMemberDeclarations() [2/2]
void GroupDefImpl::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title) [private]
writeMemberDocumentation() [1/2]
void GroupDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title) [private]
Definition at line 1708 of file groupdef.cpp.
{
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeDocumentation(ol,name(),this,title);
}
References getMemberList(), DefinitionMixin< GroupDef >::name(), and MemberList::writeDocumentation().
Referenced by writeDocumentation().
writeMemberDocumentation() [2/2]
void GroupDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title) [private]
writeMemberGroups() [1/2]
void GroupDefImpl::writeMemberGroups (OutputList & ol) [private]
Definition at line 999 of file groupdef.cpp.
{
  /* write user defined member groups */
  for (const auto &mg : m_memberGroups)
  {
    mg->writeDeclarations(ol,0,0,0,this);
  }
}
References m_memberGroups.
Referenced by writeDocumentation().
writeMemberGroups() [2/2]
void GroupDefImpl::writeMemberGroups (OutputList & ol) [private]
writeMemberPages() [1/2]
void GroupDefImpl::writeMemberPages (OutputList & ol) [virtual]
Implements GroupDef.
Definition at line 1259 of file groupdef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  for (const auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_documentationLists)
    {
       ml->writeDocumentationPage(ol,name(),this);
    }
  }
  ol.popGeneratorState();
}
References OutputList::disableAllBut(), OutputGenerator::Html, m_memberLists, MemberListType_documentationLists, DefinitionMixin< GroupDef >::name(), OutputList::popGeneratorState(), and OutputList::pushGeneratorState().
Referenced by writeDocumentation().
writeMemberPages() [2/2]
virtual void GroupDefImpl::writeMemberPages (OutputList & ol) [virtual]
Implements GroupDef.
writeNamespaces() [1/2]
void GroupDefImpl::writeNamespaces (OutputList & ol, const QCString & title) [private]
Definition at line 882 of file groupdef.cpp.
{
  // write list of namespaces
  m_namespaces.writeDeclaration(ol,title);
}
References m_namespaces, and NamespaceLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeNamespaces() [2/2]
void GroupDefImpl::writeNamespaces (OutputList & ol, const QCString & title) [private]
writeNestedGroups() [1/2]
void GroupDefImpl::writeNestedGroups (OutputList & ol, const QCString & title) [private]
Definition at line 888 of file groupdef.cpp.
{
  // write list of groups
  int count=0;
  for (const auto &gd : m_groups)
  {
    if (gd->isVisible()) count++;
  }
  if (count>0)
  {
    ol.startMemberHeader("groups");
    ol.parseText(title);
    ol.endMemberHeader();
    ol.startMemberList();
    for (const auto &gd : m_groups)
    {
      if (gd->isVisible())
      {
        if (!gd->hasDocumentation()) continue;
        ol.startMemberDeclaration();
        ol.startMemberItem(gd->getOutputFileBase(),0);
        //ol.docify(theTranslator->trGroup(FALSE,TRUE));
        //ol.docify(" ");
        ol.insertMemberAlign();
        ol.writeObjectLink(gd->getReference(),gd->getOutputFileBase(),QCString(),gd->groupTitle());
        ol.endMemberItem();
        if (!gd->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
        {
          ol.startMemberDescription(gd->getOutputFileBase());
          ol.generateDoc(briefFile(),briefLine(),gd,0,gd->briefDescription(),FALSE,FALSE,
                         QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
          ol.endMemberDescription();
        }
        ol.endMemberDeclaration(QCString(),QCString());
      }
    }
    ol.endMemberList();
  }
}
References DefinitionMixin< GroupDef >::briefFile(), DefinitionMixin< GroupDef >::briefLine(), Config_getBool, OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), FALSE, OutputList::generateDoc(), OutputList::insertMemberAlign(), m_groups, OutputList::parseText(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeNestedGroups() [2/2]
void GroupDefImpl::writeNestedGroups (OutputList & ol, const QCString & title) [private]
writePageDocumentation() [1/2]
void GroupDefImpl::writePageDocumentation (OutputList & ol) [private]
Definition at line 977 of file groupdef.cpp.
{
  for (const auto *pd : m_pages)
  {
    if (!pd->isReference())
    {
      const SectionInfo *si=0;
      if (pd->hasTitle() && !pd->name().isEmpty() &&
          (si=SectionManager::instance().find(pd->name()))!=0)
      {
        ol.startSection(si->label(),si->title(),SectionType::Subsection);
        ol.docify(si->title());
        ol.endSection(si->label(),SectionType::Subsection);
      }
      ol.startTextBlock();
      ol.generateDoc(pd->docFile(),pd->docLine(),pd,0,(pd->documentation()+pd->inbodyDocumentation()),TRUE,FALSE,
                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
      ol.endTextBlock();
    }
  }
}
References Config_getBool, OutputList::docify(), OutputList::endSection(), OutputList::endTextBlock(), FALSE, LinkedMap< T, Hash, KeyEqual, Map >::find(), OutputList::generateDoc(), SectionManager::instance(), SectionInfo::label(), m_pages, OutputList::startSection(), OutputList::startTextBlock(), Subsection, SectionInfo::title(), and TRUE.
Referenced by writeDocumentation().
writePageDocumentation() [2/2]
void GroupDefImpl::writePageDocumentation (OutputList & ol) [private]
writeQuickMemberLinks() [1/2]
void GroupDefImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const [virtual]
Reimplemented from DefinitionMixin< GroupDef >.
Definition at line 1275 of file groupdef.cpp.
{
  bool createSubDirs=Config_getBool(CREATE_SUBDIRS);
  ol.writeString(" <div class=\"navtab\">\n");
  ol.writeString(" <table>\n");
  for (const auto *md : m_allMemberList)
  {
    if (md->getGroupDef()==this && md->isLinkable() && !md->isEnumValue())
    {
      if (md->isLinkableInProject())
      {
        if (md==currentMd) // selected item => highlight
        {
          ol.writeString(" <tr><td class=\"navtabHL\">");
        }
        else
        {
          ol.writeString(" <tr><td class=\"navtab\">");
        }
        ol.writeString("<a class=\"navtab\" ");
        ol.writeString("href=\"");
        if (createSubDirs) ol.writeString("../../");
        ol.writeString(addHtmlExtensionIfMissing(md->getOutputFileBase())+"#"+md->anchor());
        ol.writeString("\">");
        ol.writeString(convertToHtml(md->localName()));
        ol.writeString("</a>");
        ol.writeString("</td></tr>\n");
      }
    }
  }
  ol.writeString(" </table>\n");
  ol.writeString(" </div>\n");
}
References addHtmlExtensionIfMissing(), Config_getBool, convertToHtml(), createSubDirs(), m_allMemberList, and OutputList::writeString().
writeQuickMemberLinks() [2/2]
virtual void GroupDefImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const [virtual]
Reimplemented from DefinitionMixin< GroupDef >.
writeSummaryLinks() [1/2]
void GroupDefImpl::writeSummaryLinks (OutputList & ol) const [private], [virtual]
Reimplemented from DefinitionMixin< GroupDef >.
Definition at line 1051 of file groupdef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  bool first=TRUE;
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Group))
  {
    if ((lde->kind()==LayoutDocEntry::GroupClasses && m_classes.declVisible()) ||
        (lde->kind()==LayoutDocEntry::GroupConcepts && m_concepts.declVisible()) ||
        (lde->kind()==LayoutDocEntry::GroupNamespaces && m_namespaces.declVisible(false)) ||
        (lde->kind()==LayoutDocEntry::GroupFiles && !m_fileList.empty()) ||
        (lde->kind()==LayoutDocEntry::GroupNestedGroups && !m_groups.empty()) ||
        (lde->kind()==LayoutDocEntry::GroupDirs && !m_dirList.empty())
       )
    {
      const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
      if (ls)
      {
        QCString label = lde->kind()==LayoutDocEntry::GroupClasses ? "nested-classes" :
                         lde->kind()==LayoutDocEntry::GroupConcepts ? "concepts" :
                         lde->kind()==LayoutDocEntry::GroupNamespaces ? "namespaces" :
                         lde->kind()==LayoutDocEntry::GroupFiles ? "files" :
                         lde->kind()==LayoutDocEntry::GroupNestedGroups ? "groups" :
                         "dirs";
        ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
        first=FALSE;
      }
    }
    else if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd)
      {
        MemberList * ml = getMemberList(lmd->type);
        if (ml && ml->declVisible())
        {
          ol.writeSummaryLink(QCString(),MemberList::listTypeAsString(ml->listType()),lmd->title(lang),first);
          first=FALSE;
        }
      }
    }
  }
  if (!first)
  {
    ol.writeString(" </div>\n");
  }
  ol.popGeneratorState();
}
References ConceptLinkedRefMap::declVisible(), MemberList::declVisible(), NamespaceLinkedRefMap::declVisible(), ClassLinkedRefMap::declVisible(), OutputList::disableAllBut(), FALSE, DefinitionMixin< GroupDef >::getLanguage(), getMemberList(), LayoutDocManager::Group, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, OutputGenerator::Html, LayoutDocManager::instance(), MemberList::listType(), MemberList::listTypeAsString(), m_classes, m_concepts, m_dirList, m_fileList, m_groups, m_namespaces, LayoutDocEntry::MemberDecl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), TRUE, LayoutDocEntryMemberDecl::type, OutputList::writeString(), and OutputList::writeSummaryLink().
Referenced by writeDocumentation().
writeSummaryLinks() [2/2]
void GroupDefImpl::writeSummaryLinks (OutputList & ol) const [private], [virtual]
Reimplemented from DefinitionMixin< GroupDef >.
writeTagFile() [1/2]
void GroupDefImpl::writeTagFile (TextStream & tagFile) [virtual]
Implements GroupDef.
Definition at line 611 of file groupdef.cpp.
{
  tagFile << " <compound kind=\"group\">\n";
  tagFile << " <name>" << convertToXML(name()) << "</name>\n";
  tagFile << " <title>" << convertToXML(m_title) << "</title>\n";
  tagFile << " <filename>" << addHtmlExtensionIfMissing(getOutputFileBase()) << "</filename>\n";
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Group))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::GroupClasses:
        {
          for (const auto &cd : m_classes)
          {
            if (cd->isLinkableInProject())
            {
              tagFile << " <class kind=\"" << cd->compoundTypeString()
                      << "\">" << convertToXML(cd->name()) << "</class>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::GroupConcepts:
        {
          for (const auto &cd : m_concepts)
          {
            if (cd->isLinkableInProject())
            {
              tagFile << " <concept>" << convertToXML(cd->name())
                      << "</concept>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::GroupNamespaces:
        {
          for (const auto &nd : m_namespaces)
          {
            if (nd->isLinkableInProject())
            {
              tagFile << " <namespace>" << convertToXML(nd->name())
                      << "</namespace>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::GroupFiles:
        {
          for (const auto &fd : m_fileList)
          {
            if (fd->isLinkableInProject())
            {
              tagFile << " <file>" << convertToXML(fd->name()) << "</file>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::GroupPageDocs:
        {
          for (const auto &pd : m_pages)
          {
            QCString pageName = pd->getOutputFileBase();
            if (pd->isLinkableInProject())
            {
              tagFile << " <page>" << convertToXML(pageName) << "</page>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::GroupDirs:
        {
          for (const auto &dd : m_dirList)
          {
            if (dd->isLinkableInProject())
            {
              tagFile << " <dir>" << convertToXML(dd->displayName()) << "</dir>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::GroupNestedGroups:
        {
          for (const auto &gd : m_groups)
          {
            if (gd->isVisible())
            {
              tagFile << " <subgroup>" << convertToXML(gd->name()) << "</subgroup>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            MemberList * ml = getMemberList(lmd->type);
            if (ml)
            {
              ml->writeTagFile(tagFile,true);
            }
          }
        }
        break;
      case LayoutDocEntry::MemberGroups:
        {
          for (const auto &mg : m_memberGroups)
          {
            mg->writeTagFile(tagFile,true);
          }
        }
        break;
      default:
        break;
    }
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << " </compound>\n";
}
References addHtmlExtensionIfMissing(), convertToXML(), getMemberList(), getOutputFileBase(), LayoutDocManager::Group, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, LayoutDocManager::instance(), m_classes, m_concepts, m_dirList, m_fileList, m_groups, m_memberGroups, m_namespaces, m_pages, m_title, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberGroups, DefinitionMixin< GroupDef >::name(), LayoutDocEntryMemberDecl::type, DefinitionMixin< GroupDef >::writeDocAnchorsToTagFile(), and MemberList::writeTagFile().
writeTagFile() [2/2]
virtual void GroupDefImpl::writeTagFile (TextStream &) [virtual]
Implements GroupDef.
Member Data Documentation
m_allMemberList
MemberList GroupDefImpl::m_allMemberList [private]
Definition at line 153 of file groupdef.cpp.
Referenced by computeAnchors(), insertMember(), numDocMembers(), writeDocumentation(), and writeQuickMemberLinks().
m_allMemberNameInfoLinkedMap
MemberNameInfoLinkedMap GroupDefImpl::m_allMemberNameInfoLinkedMap [private]
Definition at line 154 of file groupdef.cpp.
Referenced by insertMember(), and removeMember().
m_classes
ClassLinkedRefMap GroupDefImpl::m_classes [private]
Definition at line 146 of file groupdef.cpp.
Referenced by addClass(), getClasses(), numDocMembers(), sortMemberLists(), writeClasses(), writeInlineClasses(), writeSummaryLinks(), and writeTagFile().
m_concepts
ConceptLinkedRefMap GroupDefImpl::m_concepts [private]
Definition at line 147 of file groupdef.cpp.
Referenced by addConcept(), getConcepts(), writeConcepts(), writeSummaryLinks(), and writeTagFile().
m_dirList
DirList GroupDefImpl::m_dirList [private]
Definition at line 152 of file groupdef.cpp.
Referenced by addDir(), getDirs(), sortMemberLists(), writeDirs(), writeSummaryLinks(), and writeTagFile().
m_examples
PageLinkedRefMap GroupDefImpl::m_examples [private]
Definition at line 151 of file groupdef.cpp.
Referenced by addExample(), getExamples(), and numDocMembers().
m_fileList
FileList GroupDefImpl::m_fileList [private]
Definition at line 145 of file groupdef.cpp.
Referenced by addFile(), getFiles(), numDocMembers(), writeFiles(), writeSummaryLinks(), and writeTagFile().
m_fileName
QCString GroupDefImpl::m_fileName [private]
Definition at line 144 of file groupdef.cpp.
Referenced by getOutputFileBase(), and GroupDefImpl().
m_groups
GroupList GroupDefImpl::m_groups [private]
Definition at line 149 of file groupdef.cpp.
Referenced by addGroup(), findGroup(), getSubGroups(), numDocMembers(), sortSubGroups(), writeNestedGroups(), writeSummaryLinks(), and writeTagFile().
m_groupScope
Definition * GroupDefImpl::m_groupScope [private]
Definition at line 155 of file groupdef.cpp.
Referenced by getGroupScope(), GroupDefImpl(), and setGroupScope().
m_memberGroups
MemberGroupList GroupDefImpl::m_memberGroups [private]
Definition at line 157 of file groupdef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), countMembers(), distributeMemberGroupDocumentation(), findSectionsInDocumentation(), getMemberGroups(), writeMemberGroups(), and writeTagFile().
m_memberLists
MemberLists GroupDefImpl::m_memberLists [private]
Definition at line 156 of file groupdef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), addMemberToList(), countMembers(), findSectionsInDocumentation(), getMemberList(), getMemberLists(), sortMemberLists(), and writeMemberPages().
m_namespaces
NamespaceLinkedRefMap GroupDefImpl::m_namespaces [private]
Definition at line 148 of file groupdef.cpp.
Referenced by addNamespace(), getNamespaces(), numDocMembers(), sortMemberLists(), writeNamespaces(), writeSummaryLinks(), and writeTagFile().
m_pages
PageLinkedRefMap GroupDefImpl::m_pages [private]
Definition at line 150 of file groupdef.cpp.
Referenced by addPage(), getPages(), hasDetailedDescription(), numDocMembers(), writeDetailedDescription(), writePageDocumentation(), and writeTagFile().
m_subGrouping
bool GroupDefImpl::m_subGrouping [private]
Definition at line 158 of file groupdef.cpp.
Referenced by GroupDefImpl(), and subGrouping().
m_title
QCString GroupDefImpl::m_title [private]
Definition at line 142 of file groupdef.cpp.
Referenced by displayName(), groupTitle(), setGroupTitle(), writeDocumentation(), writeGroupGraph(), and writeTagFile().
m_titleSet
bool GroupDefImpl::m_titleSet [private]
Definition at line 143 of file groupdef.cpp.
Referenced by hasGroupTitle(), and setGroupTitle().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/groupdef.cpp
doxygen/src/groupdef.cpp