FilterStripPath Class Reference
The implementation of the `default` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `default` filter.
Definition at line 1382 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterStripPath::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1385 of file template.cpp.
    {
      if (!v.isValid() || !v.isString())
      {
        return v;
      }
      QCString result = v.toString();
      int i=result.findRev('/');
      if (i!=-1)
      {
        result=result.mid(i+1);
      }
      i=result.findRev('\\');
      if (i!=-1)
      {
        result=result.mid(i+1);
      }
      return result;
    }
References QCString::findRev(), TemplateVariant::isString(), TemplateVariant::isValid(), QCString::mid(), and TemplateVariant::toString().
apply() [2/2]
static TemplateVariant FilterStripPath::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1385 of file template.cpp.
    {
      if (!v.isValid() || !v.isString())
      {
        return v;
      }
      QCString result = v.toString();
      int i=result.findRev('/');
      if (i!=-1)
      {
        result=result.mid(i+1);
      }
      i=result.findRev('\\');
      if (i!=-1)
      {
        result=result.mid(i+1);
      }
      return result;
    }
References QCString::findRev(), TemplateVariant::isString(), TemplateVariant::isValid(), QCString::mid(), and TemplateVariant::toString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp