ClassHierarchyContext::Private Class Reference
Public Member Functions
Private ()
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private ()
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant tree () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant diagrams () const
TemplateVariant maxDepth () const
TemplateVariant preferredDepth () const
TemplateVariant title () const
int createMaxDepth () const
int createPreferredDepth () const
TemplateVariant createDiagrams () const
TemplateVariant tree () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant diagrams () const
TemplateVariant maxDepth () const
TemplateVariant preferredDepth () const
TemplateVariant title () const
int createMaxDepth () const
int createPreferredDepth () const
TemplateVariant createDiagrams () const
Private Attributes
TemplateListIntfPtr m_classTree
CachedItem< int, Private, &Private::createMaxDepth > m_maxDepth
CachedItem< int, Private, &Private::createPreferredDepth > m_preferredDepth
CachedItem< TemplateVariant, Private, &Private::createDiagrams > m_diagrams
Static Private Attributes
static const PropertyMap< ClassHierarchyContext::Private > s_inst
Detailed Description
Definition at line 5195 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
ClassHierarchyContext::Private::Private () [inline]
Definition at line 5198 of file context.cpp.
    {
      m_classTree = NestingContext::alloc(0,ContextTreeType::ClassInheritance,0);
      auto ctx = std::dynamic_pointer_cast<NestingContext>(m_classTree);
      ClassDefSet visitedClasses;
      ctx->addClassHierarchy(*Doxygen::classLinkedMap,visitedClasses);
      ctx->addClassHierarchy(*Doxygen::hiddenClassLinkedMap,visitedClasses);
    }
References NestingContext::alloc(), ClassInheritance, Doxygen::classLinkedMap, Doxygen::hiddenClassLinkedMap, and m_classTree.
Private() [2/2]
ClassHierarchyContext::Private::Private () [inline]
Definition at line 5198 of file context.cpp.
    {
      m_classTree = NestingContext::alloc(0,ContextTreeType::ClassInheritance,0);
      auto ctx = std::dynamic_pointer_cast<NestingContext>(m_classTree);
      ClassDefSet visitedClasses;
      ctx->addClassHierarchy(*Doxygen::classLinkedMap,visitedClasses);
      ctx->addClassHierarchy(*Doxygen::hiddenClassLinkedMap,visitedClasses);
    }
References NestingContext::alloc(), ClassInheritance, Doxygen::classLinkedMap, and Doxygen::hiddenClassLinkedMap.
Member Function Documentation
createDiagrams() [1/2]
TemplateVariant ClassHierarchyContext::Private::createDiagrams () const [inline], [private]
Definition at line 5235 of file context.cpp.
    {
      TemplateVariantList diagrams;
      DotGfxHierarchyTablePtr hierarchy = std::make_shared<DotGfxHierarchyTable>();
      diagrams.reserve(hierarchy->subGraphs().size());
      int id=0;
      for (auto n : hierarchy->subGraphs())
      {
        diagrams.push_back(InheritanceGraphContext::alloc(hierarchy,n,id++));
      }
      return TemplateImmutableList::alloc(diagrams);
    }
References InheritanceGraphContext::alloc(), TemplateImmutableList::alloc(), diagrams(), and n.
createDiagrams() [2/2]
TemplateVariant ClassHierarchyContext::Private::createDiagrams () const [inline], [private]
Definition at line 5235 of file context.cpp.
    {
      TemplateVariantList diagrams;
      DotGfxHierarchyTablePtr hierarchy = std::make_shared<DotGfxHierarchyTable>();
      diagrams.reserve(hierarchy->subGraphs().size());
      int id=0;
      for (auto n : hierarchy->subGraphs())
      {
        diagrams.push_back(InheritanceGraphContext::alloc(hierarchy,n,id++));
      }
      return TemplateImmutableList::alloc(diagrams);
    }
References InheritanceGraphContext::alloc(), TemplateImmutableList::alloc(), and n.
createMaxDepth() [1/2]
int ClassHierarchyContext::Private::createMaxDepth () const [inline], [private]
Definition at line 5227 of file context.cpp.
    {
      return computeMaxDepth(m_classTree);
    }
References computeMaxDepth(), and m_classTree.
createMaxDepth() [2/2]
int ClassHierarchyContext::Private::createMaxDepth () const [inline], [private]
Definition at line 5227 of file context.cpp.
    {
      return computeMaxDepth(m_classTree);
    }
References computeMaxDepth().
createPreferredDepth() [1/2]
int ClassHierarchyContext::Private::createPreferredDepth () const [inline], [private]
Definition at line 5231 of file context.cpp.
    {
      return computePreferredDepth(m_classTree,m_maxDepth.get(this));
    }
References computePreferredDepth(), m_classTree, and m_maxDepth.
createPreferredDepth() [2/2]
int ClassHierarchyContext::Private::createPreferredDepth () const [inline], [private]
Definition at line 5231 of file context.cpp.
    {
      return computePreferredDepth(m_classTree,m_maxDepth.get(this));
    }
References computePreferredDepth().
diagrams() [1/2]
TemplateVariant ClassHierarchyContext::Private::diagrams () const [inline], [private]
Definition at line 5218 of file context.cpp.
{ return m_diagrams.get(this); }
References m_diagrams.
Referenced by createDiagrams().
diagrams() [2/2]
TemplateVariant ClassHierarchyContext::Private::diagrams () const [inline], [private]
Definition at line 5218 of file context.cpp.
{ return m_diagrams.get(this); }
fields() [1/2]
StringVector ClassHierarchyContext::Private::fields () const [inline]
Definition at line 5209 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector ClassHierarchyContext::Private::fields () const [inline]
Definition at line 5209 of file context.cpp.
{ return s_inst.fields(); }
fileName() [1/2]
TemplateVariant ClassHierarchyContext::Private::fileName () const [inline], [private]
Definition at line 5214 of file context.cpp.
{ return "hierarchy"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
TemplateVariant ClassHierarchyContext::Private::fileName () const [inline], [private]
Definition at line 5214 of file context.cpp.
{ return "hierarchy"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
get() [1/2]
TemplateVariant ClassHierarchyContext::Private::get (const QCString & n) const [inline]
Definition at line 5208 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant ClassHierarchyContext::Private::get (const QCString & n) const [inline]
Definition at line 5208 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
highlight() [1/2]
TemplateVariant ClassHierarchyContext::Private::highlight () const [inline], [private]
Definition at line 5216 of file context.cpp.
{ return "classes"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant ClassHierarchyContext::Private::highlight () const [inline], [private]
Definition at line 5216 of file context.cpp.
{ return "classes"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
maxDepth() [1/2]
TemplateVariant ClassHierarchyContext::Private::maxDepth () const [inline], [private]
Definition at line 5219 of file context.cpp.
{ return m_maxDepth.get(this); }
References m_maxDepth.
maxDepth() [2/2]
TemplateVariant ClassHierarchyContext::Private::maxDepth () const [inline], [private]
Definition at line 5219 of file context.cpp.
{ return m_maxDepth.get(this); }
preferredDepth() [1/2]
TemplateVariant ClassHierarchyContext::Private::preferredDepth () const [inline], [private]
Definition at line 5220 of file context.cpp.
{ return m_preferredDepth.get(this); }
References m_preferredDepth.
preferredDepth() [2/2]
TemplateVariant ClassHierarchyContext::Private::preferredDepth () const [inline], [private]
Definition at line 5220 of file context.cpp.
{ return m_preferredDepth.get(this); }
relPath() [1/2]
TemplateVariant ClassHierarchyContext::Private::relPath () const [inline], [private]
Definition at line 5215 of file context.cpp.
{ return ""; }
relPath() [2/2]
TemplateVariant ClassHierarchyContext::Private::relPath () const [inline], [private]
Definition at line 5215 of file context.cpp.
{ return ""; }
subhighlight() [1/2]
TemplateVariant ClassHierarchyContext::Private::subhighlight () const [inline], [private]
Definition at line 5217 of file context.cpp.
{ return "classhierarchy"; }
subhighlight() [2/2]
TemplateVariant ClassHierarchyContext::Private::subhighlight () const [inline], [private]
Definition at line 5217 of file context.cpp.
{ return "classhierarchy"; }
title() [1/2]
TemplateVariant ClassHierarchyContext::Private::title () const [inline], [private]
Definition at line 5221 of file context.cpp.
    {
      return Config_getBool(OPTIMIZE_OUTPUT_VHDL) ? theTranslator->trDesignUnitHierarchy() :
                                                    theTranslator->trClassHierarchy();
    }
References Config_getBool, theTranslator, Translator::trClassHierarchy(), and Translator::trDesignUnitHierarchy().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant ClassHierarchyContext::Private::title () const [inline], [private]
Definition at line 5221 of file context.cpp.
    {
      return Config_getBool(OPTIMIZE_OUTPUT_VHDL) ? theTranslator->trDesignUnitHierarchy() :
                                                    theTranslator->trClassHierarchy();
    }
References Config_getBool, theTranslator, Translator::trClassHierarchy(), and Translator::trDesignUnitHierarchy().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
tree() [1/2]
TemplateVariant ClassHierarchyContext::Private::tree () const [inline], [private]
Definition at line 5213 of file context.cpp.
{ return TemplateVariant(m_classTree); }
References m_classTree.
tree() [2/2]
TemplateVariant ClassHierarchyContext::Private::tree () const [inline], [private]
Definition at line 5213 of file context.cpp.
{ return TemplateVariant(m_classTree); }
Member Data Documentation
m_classTree
TemplateListIntfPtr ClassHierarchyContext::Private::m_classTree [private]
Definition at line 5248 of file context.cpp.
Referenced by createMaxDepth(), createPreferredDepth(), Private(), and tree().
m_diagrams
CachedItem< TemplateVariant, Private, &Private::createDiagrams > ClassHierarchyContext::Private::m_diagrams [private]
Definition at line 5251 of file context.cpp.
Referenced by diagrams().
m_maxDepth
CachedItem< int, Private, &Private::createMaxDepth > ClassHierarchyContext::Private::m_maxDepth [private]
Definition at line 5249 of file context.cpp.
Referenced by createPreferredDepth(), and maxDepth().
m_preferredDepth
CachedItem< int, Private, &Private::createPreferredDepth > ClassHierarchyContext::Private::m_preferredDepth [private]
Definition at line 5250 of file context.cpp.
Referenced by preferredDepth().
s_inst
const PropertyMap< ClassHierarchyContext::Private > ClassHierarchyContext::Private::s_inst [static], [private]
Initial value:
{
  { "tree", &Private::tree },
  { "fileName", &Private::fileName },
  { "relPath", &Private::relPath },
  { "highlight", &Private::highlight },
  { "subhighlight", &Private::subhighlight },
  { "diagrams", &Private::diagrams },
  { "maxDepth", &Private::maxDepth },
  { "preferredDepth", &Private::preferredDepth },
  { "title", &Private::title },
}
Definition at line 5252 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp