XmlDocVisitor Class Reference
Concrete visitor implementation for XML output.
#include <xmldocvisitor.h>
Public Member Functions
XmlDocVisitor (TextStream &t, CodeOutputInterface &ci, const QCString &langExt)
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &)
void operator() (const DocHtmlList &)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocHtmlCaption &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &)
void operator() (const DocRef &)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
XmlDocVisitor (TextStream &t, CodeOutputInterface &ci, const QCString &langExt)
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &)
void operator() (const DocHtmlList &)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocHtmlCaption &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &)
void operator() (const DocRef &)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
Private Member Functions
template<class T >
void visitChildren (const T &t)
void filter (const QCString &str)
void startLink (const QCString &ref, const QCString &file, const QCString &anchor)
void endLink ()
template<class T >
void visitChildren (const T &t)
void filter (const QCString &str)
void startLink (const QCString &ref, const QCString &file, const QCString &anchor)
void endLink ()
Private Attributes
TextStream & m_t
CodeOutputInterface & m_ci
bool m_insidePre
bool m_hide
QCString m_langExt
Detailed Description
Concrete visitor implementation for XML output.
Definition at line 33 of file xmldocvisitor.h.
Constructor & Destructor Documentation
XmlDocVisitor() [1/2]
XmlDocVisitor::XmlDocVisitor (TextStream & t, CodeOutputInterface & ci, const QCString & langExt)
Definition at line 147 of file xmldocvisitor.cpp.
  : m_t(t), m_ci(ci), m_insidePre(FALSE), m_hide(FALSE),
    m_langExt(langExt)
{
}
XmlDocVisitor() [2/2]
XmlDocVisitor::XmlDocVisitor (TextStream & t, CodeOutputInterface & ci, const QCString & langExt)
Member Function Documentation
endLink() [1/2]
void XmlDocVisitor::endLink () [private]
Definition at line 1160 of file xmldocvisitor.cpp.
{
  m_t << "</ref>";
}
References m_t.
Referenced by operator()().
endLink() [2/2]
void XmlDocVisitor::endLink () [private]
filter() [1/2]
void XmlDocVisitor::filter (const QCString & str) [private]
Definition at line 1143 of file xmldocvisitor.cpp.
{
  m_t << convertToXML(str);
}
References convertToXML(), and m_t.
Referenced by operator()().
filter() [2/2]
void XmlDocVisitor::filter (const QCString & str) [private]
operator()() [1/114]
void XmlDocVisitor::operator() (const DocAnchor & anc)
Definition at line 389 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<anchor id=\"" << anc.file() << "_1" << anc.anchor() << "\"/>";
}
References DocAnchor::anchor(), DocAnchor::file(), m_hide, and m_t.
operator()() [2/114]
void XmlDocVisitor::operator() (const DocAnchor &)
operator()() [3/114]
void XmlDocVisitor::operator() (const DocAutoList & l)
Definition at line 614 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  if (l.isEnumList())
  {
    m_t << "<orderedlist>\n";
  }
  else
  {
    m_t << "<itemizedlist>\n";
  }
  visitChildren(l);
  if (l.isEnumList())
  {
    m_t << "</orderedlist>\n";
  }
  else
  {
    m_t << "</itemizedlist>\n";
  }
}
References DocAutoList::isEnumList(), m_hide, m_t, and visitChildren().
operator()() [4/114]
void XmlDocVisitor::operator() (const DocAutoList &)
operator()() [5/114]
void XmlDocVisitor::operator() (const DocAutoListItem & li)
Definition at line 636 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<listitem>";
  visitChildren(li);
  m_t << "</listitem>";
}
References m_hide, m_t, and visitChildren().
operator()() [6/114]
void XmlDocVisitor::operator() (const DocAutoListItem &)
operator()() [7/114]
void XmlDocVisitor::operator() (const DocCite & cite)
Definition at line 602 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  if (!cite.file().isEmpty()) startLink(cite.ref(),cite.file(),cite.anchor());
  filter(cite.text());
  if (!cite.file().isEmpty()) endLink();
}
References DocCite::anchor(), endLink(), DocCite::file(), filter(), QCString::isEmpty(), m_hide, DocCite::ref(), startLink(), and DocCite::text().
operator()() [8/114]
void XmlDocVisitor::operator() (const DocCite &)
operator()() [9/114]
void XmlDocVisitor::operator() (const DocDiaFile & df)
Definition at line 967 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  copyFile(df.file(),Config_getString(XML_OUTPUT)+"/"+stripPath(df.file()));
  visitPreStart(m_t, "diafile", FALSE, *this, df.children(), stripPath(df.file()), FALSE, DocImage::Html, df.width(), df.height());
  visitChildren(df);
  visitPostEnd(m_t, "diafile");
}
References DocCompoundNode::children(), Config_getString, copyFile(), FALSE, DocDiagramFileBase::file(), DocDiagramFileBase::height(), DocImage::Html, m_hide, m_t, stripPath(), visitChildren(), visitPostEnd(), visitPreStart(), and DocDiagramFileBase::width().
operator()() [10/114]
void XmlDocVisitor::operator() (const DocDiaFile &)
operator()() [11/114]
void XmlDocVisitor::operator() (const DocDotFile & df)
Definition at line 949 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  copyFile(df.file(),Config_getString(XML_OUTPUT)+"/"+stripPath(df.file()));
  visitPreStart(m_t, "dotfile", FALSE, *this, df.children(), stripPath(df.file()), FALSE, DocImage::Html, df.width(), df.height());
  visitChildren(df);
  visitPostEnd(m_t, "dotfile");
}
References DocCompoundNode::children(), Config_getString, copyFile(), FALSE, DocDiagramFileBase::file(), DocDiagramFileBase::height(), DocImage::Html, m_hide, m_t, stripPath(), visitChildren(), visitPostEnd(), visitPreStart(), and DocDiagramFileBase::width().
operator()() [12/114]
void XmlDocVisitor::operator() (const DocDotFile &)
operator()() [13/114]
void XmlDocVisitor::operator() (const DocEmoji & s)
Definition at line 198 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  const char *res = EmojiEntityMapper::instance()->name(s.index());
  if (res)
  {
    QCString name=res;
    name = name.mid(1,name.length()-2);
    m_t << "<emoji name=\"" << name << "\" unicode=\"";
    filter(EmojiEntityMapper::instance()->unicode(s.index()));
    m_t << "\"/>";
  }
  else
  {
    m_t << s.name();
  }
}
References filter(), EmojiEntityMapper::instance(), m_hide, m_t, setup::name, EmojiEntityMapper::name(), and s.
operator()() [14/114]
void XmlDocVisitor::operator() (const DocEmoji &)
operator()() [15/114]
void XmlDocVisitor::operator() (const DocFormula & f)
Definition at line 573 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<formula id=\"" << f.id() << "\">";
  filter(f.text());
  m_t << "</formula>";
}
References f, filter(), m_hide, and m_t.
operator()() [16/114]
void XmlDocVisitor::operator() (const DocFormula &)
operator()() [17/114]
void XmlDocVisitor::operator() (const DocHorRuler &)
Definition at line 233 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<hruler/>\n";
}
References m_hide, and m_t.
operator()() [18/114]
void XmlDocVisitor::operator() (const DocHorRuler &)
operator()() [19/114]
void XmlDocVisitor::operator() (const DocHRef & href)
Definition at line 879 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<ulink url=\"" << convertToXML(href.url(), TRUE) << "\">";
  visitChildren(href);
  m_t << "</ulink>";
}
References convertToXML(), m_hide, m_t, TRUE, DocHRef::url(), and visitChildren().
operator()() [20/114]
void XmlDocVisitor::operator() (const DocHRef &)
operator()() [21/114]
void XmlDocVisitor::operator() (const DocHtmlBlockQuote & q)
Definition at line 1122 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<blockquote>";
  visitChildren(q);
  m_t << "</blockquote>";
}
References m_hide, m_t, and visitChildren().
operator()() [22/114]
void XmlDocVisitor::operator() (const DocHtmlBlockQuote &)
operator()() [23/114]
void XmlDocVisitor::operator() (const DocHtmlCaption & c)
Definition at line 858 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<caption";
  if (!c.file().isEmpty())
  {
    m_t << " id=\"" << stripPath(c.file()) << "_1" << c.anchor() << "\"";
  }
  m_t << ">";
  visitChildren(c);
  m_t << "</caption>\n";
}
References c, m_hide, m_t, stripPath(), and visitChildren().
operator()() [24/114]
void XmlDocVisitor::operator() (const DocHtmlCaption &)
operator()() [25/114]
void XmlDocVisitor::operator() (const DocHtmlCell & c)
Definition at line 805 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  if (c.isHeading()) m_t << "<entry thead=\"yes\""; else m_t << "<entry thead=\"no\"";
  for (const auto &opt : c.attribs())
  {
    if (opt.name=="colspan" || opt.name=="rowspan")
    {
      m_t << " " << opt.name << "=\"" << opt.value.toInt() << "\"";
    }
    else if (opt.name=="align" &&
             (opt.value=="right" || opt.value=="left" || opt.value=="center"))
    {
      m_t << " align=\"" << opt.value << "\"";
    }
    else if (opt.name=="valign" &&
      (opt.value == "bottom" || opt.value == "top" || opt.value == "middle"))
    {
      m_t << " valign=\"" << opt.value << "\"";
    }
    else if (opt.name=="width")
    {
      m_t << " width=\"" << opt.value << "\"";
    }
    else if (opt.name=="class") // handle markdown generated attributes
    {
      if (opt.value.startsWith("markdownTable")) // handle markdown generated attributes
      {
        if (opt.value.endsWith("Right"))
        {
          m_t << " align='right'";
        }
        else if (opt.value.endsWith("Left"))
        {
          m_t << " align='left'";
        }
        else if (opt.value.endsWith("Center"))
        {
          m_t << " align='center'";
        }
        // skip 'markdownTable*' value ending with "None"
      }
      else if (!opt.value.isEmpty())
      {
        m_t << " class=\"" << convertToXML(opt.value) << "\"";
      }
    }
  }
  m_t << ">";
  visitChildren(c);
  m_t << "</entry>";
}
References c, convertToXML(), m_hide, m_t, and visitChildren().
operator()() [26/114]
void XmlDocVisitor::operator() (const DocHtmlCell &)
operator()() [27/114]
void XmlDocVisitor::operator() (const DocHtmlDescData & dd)
Definition at line 768 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<listitem>";
  visitChildren(dd);
  m_t << "</listitem>\n";
}
References m_hide, m_t, and visitChildren().
operator()() [28/114]
void XmlDocVisitor::operator() (const DocHtmlDescData &)
operator()() [29/114]
void XmlDocVisitor::operator() (const DocHtmlDescList & dl)
Definition at line 752 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<variablelist>\n";
  visitChildren(dl);
  m_t << "</variablelist>\n";
}
References m_hide, m_t, and visitChildren().
operator()() [30/114]
void XmlDocVisitor::operator() (const DocHtmlDescList &)
operator()() [31/114]
void XmlDocVisitor::operator() (const DocHtmlDescTitle & dt)
Definition at line 760 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<varlistentry><term>";
  visitChildren(dt);
  m_t << "</term></varlistentry>\n";
}
References m_hide, m_t, and visitChildren().
operator()() [32/114]
void XmlDocVisitor::operator() (const DocHtmlDescTitle &)
operator()() [33/114]
void XmlDocVisitor::operator() (const DocHtmlDetails & d)
Definition at line 895 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<details>";
  auto summary = d.summary();
  if (summary)
  {
    std::visit(*this,*summary);
  }
  visitChildren(d);
  m_t << "</details>";
}
References m_hide, m_t, DocHtmlDetails::summary(), and visitChildren().
operator()() [34/114]
void XmlDocVisitor::operator() (const DocHtmlDetails &)
operator()() [35/114]
void XmlDocVisitor::operator() (const DocHtmlHeader & header)
Definition at line 908 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<heading level=\"" << header.level() << "\">";
  visitChildren(header);
  m_t << "</heading>\n";
}
References DocHtmlHeader::level(), m_hide, m_t, and visitChildren().
operator()() [36/114]
void XmlDocVisitor::operator() (const DocHtmlHeader &)
operator()() [37/114]
void XmlDocVisitor::operator() (const DocHtmlList & s)
Definition at line 709 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  if (s.type()==DocHtmlList::Ordered)
  {
    m_t << "<orderedlist";
    for (const auto &opt : s.attribs())
    {
      m_t << " " << opt.name << "=\"" << opt.value << "\"";
    }
    m_t << ">\n";
  }
  else
  {
    m_t << "<itemizedlist>\n";
  }
  visitChildren(s);
  if (s.type()==DocHtmlList::Ordered)
  {
    m_t << "</orderedlist>\n";
  }
  else
  {
    m_t << "</itemizedlist>\n";
  }
}
References m_hide, m_t, DocHtmlList::Ordered, s, and visitChildren().
operator()() [38/114]
void XmlDocVisitor::operator() (const DocHtmlList &)
operator()() [39/114]
void XmlDocVisitor::operator() (const DocHtmlListItem & l)
Definition at line 736 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<listitem";
  for (const auto &opt : l.attribs())
  {
    if (opt.name=="value")
    {
      m_t << " " << opt.name << "=\"" << opt.value << "\"";
    }
  }
  m_t << ">\n";
  visitChildren(l);
  m_t << "</listitem>\n";
}
References DocHtmlListItem::attribs(), m_hide, m_t, and visitChildren().
operator()() [40/114]
void XmlDocVisitor::operator() (const DocHtmlListItem &)
operator()() [41/114]
void XmlDocVisitor::operator() (const DocHtmlRow & r)
Definition at line 797 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<row>\n";
  visitChildren(r);
  m_t << "</row>\n";
}
References m_hide, m_t, r, and visitChildren().
operator()() [42/114]
void XmlDocVisitor::operator() (const DocHtmlRow &)
operator()() [43/114]
void XmlDocVisitor::operator() (const DocHtmlSummary & s)
Definition at line 887 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<summary>";
  visitChildren(s);
  m_t << "</summary>";
}
References m_hide, m_t, s, and visitChildren().
operator()() [44/114]
void XmlDocVisitor::operator() (const DocHtmlSummary &)
operator()() [45/114]
void XmlDocVisitor::operator() (const DocHtmlTable & t)
Definition at line 776 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<table rows=\"" << t.numRows()
      << "\" cols=\"" << t.numColumns() << "\"" ;
  for (const auto &opt : t.attribs())
  {
    if (opt.name=="width")
    {
      m_t << " " << opt.name << "=\"" << opt.value << "\"";
    }
  }
  m_t << ">";
  if (t.caption())
  {
    std::visit(*this,*t.caption());
  }
  visitChildren(t);
  m_t << "</table>\n";
}
References DocHtmlTable::attribs(), DocHtmlTable::caption(), m_hide, m_t, DocHtmlTable::numColumns(), DocHtmlTable::numRows(), and visitChildren().
operator()() [46/114]
void XmlDocVisitor::operator() (const DocHtmlTable &)
operator()() [47/114]
void XmlDocVisitor::operator() (const DocImage & img)
Definition at line 916 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  QCString url = img.url();
  QCString baseName;
  if (url.isEmpty())
  {
    baseName = img.relPath()+img.name();
  }
  else
  {
    baseName = correctURL(url,img.relPath());
  }
  HtmlAttribList attribs = img.attribs();
  auto it = std::find_if(attribs.begin(),attribs.end(),
                         [](const auto &att) { return att.name=="alt"; });
  QCString altValue = it!=attribs.end() ? it->value : "";
  visitPreStart(m_t, "image", FALSE, *this, img.children(), baseName, TRUE,
                img.type(), img.width(), img.height(), QCString(),
                altValue, img.isInlineImage());
  // copy the image to the output dir
  FileDef *fd = 0;
  bool ambig;
  if (url.isEmpty() && (fd=findFileDef(Doxygen::imageNameLinkedMap,img.name(),ambig)))
  {
    copyFile(fd->absFilePath(),Config_getString(XML_OUTPUT)+"/"+baseName);
  }
  visitChildren(img);
  visitPostEnd(m_t, "image");
}
References FileDef::absFilePath(), DocImage::attribs(), DocCompoundNode::children(), Config_getString, copyFile(), correctURL(), FALSE, findFileDef(), DocImage::height(), Doxygen::imageNameLinkedMap, DocImage::isInlineImage(), m_hide, m_t, DocImage::name(), DocImage::relPath(), TRUE, DocImage::type(), setup::url, DocImage::url(), visitChildren(), visitPostEnd(), visitPreStart(), and DocImage::width().
operator()() [48/114]
void XmlDocVisitor::operator() (const DocImage &)
operator()() [49/114]
void XmlDocVisitor::operator() (const DocInclude & inc)
Definition at line 395 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  SrcLangExt langExt = getLanguageFromFileName(inc.extension());
  switch(inc.type())
  {
    case DocInclude::IncWithLines:
      {
         m_t << "<programlisting filename=\"" << inc.file() << "\">";
         FileInfo cfi(inc.file().str());
         std::unique_ptr<FileDef> fd { createFileDef(cfi.dirPath(), cfi.fileName()) };
         getCodeParser(inc.extension()).parseCode(m_ci,inc.context(),
                                           inc.text(),
                                           langExt,
                                           inc.isExample(),
                                           inc.exampleFile(),
                                           fd.get(), // fileDef,
                                           -1, // start line
                                           -1, // end line
                                           FALSE, // inline fragment
                                           0, // memberDef
                                           TRUE // show line numbers
                       );
         m_t << "</programlisting>";
      }
      break;
    case DocInclude::Include:
      m_t << "<programlisting filename=\"" << inc.file() << "\">";
      getCodeParser(inc.extension()).parseCode(m_ci,inc.context(),
                                        inc.text(),
                                        langExt,
                                        inc.isExample(),
                                        inc.exampleFile(),
                                        0, // fileDef
                                        -1, // startLine
                                        -1, // endLine
                                        TRUE, // inlineFragment
                                        0, // memberDef
                                        FALSE // show line numbers
                       );
      m_t << "</programlisting>";
      break;
    case DocInclude::DontInclude:
    case DocInclude::DontIncWithLines:
      break;
    case DocInclude::HtmlInclude:
      if (inc.isBlock())
      {
        m_t << "<htmlonly block=\"yes\">";
      }
      else
      {
        m_t << "<htmlonly>";
      }
      filter(inc.text());
      m_t << "</htmlonly>";
      break;
    case DocInclude::LatexInclude:
      m_t << "<latexonly>";
      filter(inc.text());
      m_t << "</latexonly>";
      break;
    case DocInclude::RtfInclude:
      m_t << "<rtfonly>";
      filter(inc.text());
      m_t << "</rtfonly>";
      break;
    case DocInclude::ManInclude:
      m_t << "<manonly>";
      filter(inc.text());
      m_t << "</manonly>";
      break;
    case DocInclude::XmlInclude:
      filter(inc.text());
      break;
    case DocInclude::DocbookInclude:
      m_t << "<docbookonly>";
      filter(inc.text());
      m_t << "</docbookonly>";
      break;
    case DocInclude::VerbInclude:
      m_t << "<verbatim>";
      filter(inc.text());
      m_t << "</verbatim>";
      break;
    case DocInclude::Snippet:
      m_t << "<programlisting filename=\"" << inc.file() << "\">";
      getCodeParser(inc.extension()).parseCode(m_ci,
                                        inc.context(),
                                        extractBlock(inc.text(),inc.blockId()),
                                        langExt,
                                        inc.isExample(),
                                        inc.exampleFile()
                                       );
      m_t << "</programlisting>";
      break;
    case DocInclude::SnipWithLines:
      {
         m_t << "<programlisting filename=\"" << inc.file() << "\">";
         FileInfo cfi(inc.file().str());
         std::unique_ptr<FileDef> fd { createFileDef(cfi.dirPath(), cfi.fileName()) };
         getCodeParser(inc.extension()).parseCode(m_ci,
                                           inc.context(),
                                           extractBlock(inc.text(),inc.blockId()),
                                           langExt,
                                           inc.isExample(),
                                           inc.exampleFile(),
                                           fd.get(),
                                           lineBlock(inc.text(),inc.blockId()),
                                           -1, // endLine
                                           FALSE, // inlineFragment
                                           0, // memberDef
                                           TRUE // show line number
                                          );
         m_t << "</programlisting>";
      }
      break;
    case DocInclude::SnippetDoc:
    case DocInclude::IncludeDoc:
      err("Internal inconsistency: found switch SnippetDoc / IncludeDoc in file: %s"
          "Please create a bug report\n",__FILE__);
      break;
  }
}
References DocInclude::blockId(), DocInclude::context(), createFileDef(), FileInfo::dirPath(), DocInclude::DocbookInclude, DocInclude::DontInclude, DocInclude::DontIncWithLines, err(), DocInclude::exampleFile(), DocInclude::extension(), extractBlock(), FALSE, DocInclude::file(), FileInfo::fileName(), filter(), DocVisitor::getCodeParser(), getLanguageFromFileName(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isBlock(), DocInclude::isExample(), DocInclude::LatexInclude, lineBlock(), m_ci, m_hide, m_t, DocInclude::ManInclude, CodeParserInterface::parseCode(), DocInclude::RtfInclude, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, QCString::str(), DocInclude::text(), TRUE, DocInclude::type(), DocInclude::VerbInclude, and DocInclude::XmlInclude.
operator()() [50/114]
void XmlDocVisitor::operator() (const DocInclude &)
operator()() [51/114]
void XmlDocVisitor::operator() (const DocIncOperator & op)
Definition at line 520 of file xmldocvisitor.cpp.
{
  //printf("DocIncOperator: type=%d first=%d, last=%d text='%s'\n",
  // op.type(),op.isFirst(),op.isLast(),qPrint(op.text()));
  if (op.isFirst())
  {
    if (!m_hide)
    {
      m_t << "<programlisting filename=\"" << op.includeFileName() << "\">";
    }
    pushHidden(m_hide);
    m_hide = TRUE;
  }
  QCString locLangExt = getFileNameExtension(op.includeFileName());
  if (locLangExt.isEmpty()) locLangExt = m_langExt;
  SrcLangExt langExt = getLanguageFromFileName(locLangExt);
  if (op.type()!=DocIncOperator::Skip)
  {
    m_hide = popHidden();
    if (!m_hide)
    {
      std::unique_ptr<FileDef> fd;
      if (!op.includeFileName().isEmpty())
      {
        FileInfo cfi(op.includeFileName().str());
        fd.reset(createFileDef(cfi.dirPath(), cfi.fileName()));
      }
      getCodeParser(locLangExt).parseCode(m_ci,op.context(),
                                          op.text(),langExt,op.isExample(),
                                          op.exampleFile(),
                                          fd.get(), // fileDef
                                          op.line(), // startLine
                                          -1, // endLine
                                          FALSE, // inline fragment
                                          0, // memberDef
                                          op.showLineNo() // show line numbers
                                         );
    }
    pushHidden(m_hide);
    m_hide=TRUE;
  }
  if (op.isLast())
  {
    m_hide = popHidden();
    if (!m_hide) m_t << "</programlisting>";
  }
  else
  {
    if (!m_hide) m_t << "\n";
  }
}
References DocIncOperator::context(), createFileDef(), FileInfo::dirPath(), DocIncOperator::exampleFile(), FALSE, FileInfo::fileName(), DocVisitor::getCodeParser(), getFileNameExtension(), getLanguageFromFileName(), DocIncOperator::includeFileName(), QCString::isEmpty(), DocIncOperator::isExample(), DocIncOperator::isFirst(), DocIncOperator::isLast(), DocIncOperator::line(), m_ci, m_hide, m_langExt, m_t, CodeParserInterface::parseCode(), DocVisitor::popHidden(), DocVisitor::pushHidden(), DocIncOperator::showLineNo(), DocIncOperator::Skip, QCString::str(), DocIncOperator::text(), TRUE, and DocIncOperator::type().
operator()() [52/114]
void XmlDocVisitor::operator() (const DocIncOperator &)
operator()() [53/114]
void XmlDocVisitor::operator() (const DocIndexEntry & ie)
Definition at line 581 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<indexentry>"
           "<primaryie>";
  filter(ie.entry());
  m_t << "</primaryie>"
           "<secondaryie></secondaryie>"
         "</indexentry>";
}
References DocIndexEntry::entry(), filter(), m_hide, and m_t.
operator()() [54/114]
void XmlDocVisitor::operator() (const DocIndexEntry &)
operator()() [55/114]
void XmlDocVisitor::operator() (const DocInternal & i)
Definition at line 871 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<internal>";
  visitChildren(i);
  m_t << "</internal>\n";
}
References m_hide, m_t, and visitChildren().
operator()() [56/114]
void XmlDocVisitor::operator() (const DocInternal &)
operator()() [57/114]
void XmlDocVisitor::operator() (const DocInternalRef & ref)
Definition at line 1108 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  startLink(QCString(),ref.file(),ref.anchor());
  visitChildren(ref);
  endLink();
  m_t << " ";
}
References DocInternalRef::anchor(), endLink(), DocInternalRef::file(), m_hide, m_t, startLink(), and visitChildren().
operator()() [58/114]
void XmlDocVisitor::operator() (const DocInternalRef &)
operator()() [59/114]
void XmlDocVisitor::operator() (const DocLineBreak &)
Definition at line 227 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<linebreak/>\n";
}
References m_hide, and m_t.
operator()() [60/114]
void XmlDocVisitor::operator() (const DocLineBreak &)
operator()() [61/114]
void XmlDocVisitor::operator() (const DocLink & lnk)
Definition at line 976 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  startLink(lnk.ref(),lnk.file(),lnk.anchor());
  visitChildren(lnk);
  endLink();
}
References DocLink::anchor(), endLink(), DocLink::file(), m_hide, DocLink::ref(), startLink(), and visitChildren().
operator()() [62/114]
void XmlDocVisitor::operator() (const DocLink &)
operator()() [63/114]
void XmlDocVisitor::operator() (const DocLinkedWord & w)
Definition at line 163 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  startLink(w.ref(),w.file(),w.anchor());
  filter(w.word());
  endLink();
}
References endLink(), filter(), m_hide, startLink(), and w.
operator()() [64/114]
void XmlDocVisitor::operator() (const DocLinkedWord &)
operator()() [65/114]
void XmlDocVisitor::operator() (const DocMscFile & df)
Definition at line 958 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  copyFile(df.file(),Config_getString(XML_OUTPUT)+"/"+stripPath(df.file()));
  visitPreStart(m_t, "mscfile", FALSE, *this, df.children(), stripPath(df.file()), FALSE, DocImage::Html, df.width(), df.height());
  visitChildren(df);
  visitPostEnd(m_t, "mscfile");
}
References DocCompoundNode::children(), Config_getString, copyFile(), FALSE, DocDiagramFileBase::file(), DocDiagramFileBase::height(), DocImage::Html, m_hide, m_t, stripPath(), visitChildren(), visitPostEnd(), visitPreStart(), and DocDiagramFileBase::width().
operator()() [66/114]
void XmlDocVisitor::operator() (const DocMscFile &)
operator()() [67/114]
void XmlDocVisitor::operator() (const DocPara & p)
Definition at line 644 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<para>";
  visitChildren(p);
  m_t << "</para>\n";
}
References m_hide, m_t, p, and visitChildren().
operator()() [68/114]
void XmlDocVisitor::operator() (const DocPara &)
operator()() [69/114]
void XmlDocVisitor::operator() (const DocParamList & pl)
Definition at line 1043 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<parameteritem>\n";
  m_t << "<parameternamelist>\n";
  for (const auto &param : pl.parameters())
  {
    if (!pl.paramTypes().empty())
    {
      m_t << "<parametertype>";
      for (const auto &type : pl.paramTypes())
      {
        std::visit(*this,type);
      }
      m_t << "</parametertype>\n";
    }
    m_t << "<parametername";
    if (pl.direction()!=DocParamSect::Unspecified)
    {
      m_t << " direction=\"";
      if (pl.direction()==DocParamSect::In)
      {
        m_t << "in";
      }
      else if (pl.direction()==DocParamSect::Out)
      {
        m_t << "out";
      }
      else if (pl.direction()==DocParamSect::InOut)
      {
        m_t << "inout";
      }
      m_t << "\"";
    }
    m_t << ">";
    std::visit(*this,param);
    m_t << "</parametername>\n";
  }
  m_t << "</parameternamelist>\n";
  m_t << "<parameterdescription>\n";
  for (const auto &par : pl.paragraphs())
  {
    std::visit(*this,par);
  }
  m_t << "</parameterdescription>\n";
  m_t << "</parameteritem>\n";
}
References DocParamList::direction(), GrowVector< T >::empty(), DocParamSect::In, DocParamSect::InOut, m_hide, m_t, DocParamSect::Out, DocParamList::paragraphs(), DocParamList::parameters(), DocParamList::paramTypes(), and DocParamSect::Unspecified.
operator()() [70/114]
void XmlDocVisitor::operator() (const DocParamList &)
operator()() [71/114]
void XmlDocVisitor::operator() (const DocParamSect & s)
Definition at line 1015 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<parameterlist kind=\"";
  switch(s.type())
  {
    case DocParamSect::Param:
      m_t << "param"; break;
    case DocParamSect::RetVal:
      m_t << "retval"; break;
    case DocParamSect::Exception:
      m_t << "exception"; break;
    case DocParamSect::TemplateParam:
      m_t << "templateparam"; break;
    default:
      ASSERT(0);
  }
  m_t << "\">";
  visitChildren(s);
  m_t << "</parameterlist>\n";
}
References ASSERT, DocParamSect::Exception, m_hide, m_t, DocParamSect::Param, DocParamSect::RetVal, s, DocParamSect::TemplateParam, and visitChildren().
operator()() [72/114]
void XmlDocVisitor::operator() (const DocParamSect &)
operator()() [73/114]
void XmlDocVisitor::operator() (const DocParBlock & pb)
Definition at line 1134 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<parblock>";
  visitChildren(pb);
  m_t << "</parblock>";
}
References m_hide, m_t, and visitChildren().
operator()() [74/114]
void XmlDocVisitor::operator() (const DocParBlock &)
operator()() [75/114]
void XmlDocVisitor::operator() (const DocRef & ref)
Definition at line 984 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  if (!ref.file().isEmpty())
  {
    startLink(ref.ref(),ref.file(),ref.isSubPage() ? QCString() : ref.anchor());
  }
  if (!ref.hasLinkText()) filter(ref.targetTitle());
  visitChildren(ref);
  if (!ref.file().isEmpty()) endLink();
}
References DocRef::anchor(), endLink(), DocRef::file(), filter(), DocRef::hasLinkText(), QCString::isEmpty(), DocRef::isSubPage(), m_hide, DocRef::ref(), startLink(), DocRef::targetTitle(), and visitChildren().
operator()() [76/114]
void XmlDocVisitor::operator() (const DocRef &)
operator()() [77/114]
void XmlDocVisitor::operator() (const DocRoot & r)
Definition at line 652 of file xmldocvisitor.cpp.
{
  visitChildren(r);
}
References r, and visitChildren().
operator()() [78/114]
void XmlDocVisitor::operator() (const DocRoot &)
operator()() [79/114]
void XmlDocVisitor::operator() (const DocSecRefItem & ref)
Definition at line 996 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<tocitem id=\"" << ref.file();
  if (!ref.anchor().isEmpty()) m_t << "_1" << ref.anchor();
  m_t << "\"";
  m_t << ">";
  visitChildren(ref);
  m_t << "</tocitem>\n";
}
References DocSecRefItem::anchor(), DocSecRefItem::file(), QCString::isEmpty(), m_hide, m_t, and visitChildren().
operator()() [80/114]
void XmlDocVisitor::operator() (const DocSecRefItem &)
operator()() [81/114]
void XmlDocVisitor::operator() (const DocSecRefList & l)
Definition at line 1007 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<toclist>\n";
  visitChildren(l);
  m_t << "</toclist>\n";
}
References m_hide, m_t, and visitChildren().
operator()() [82/114]
void XmlDocVisitor::operator() (const DocSecRefList &)
operator()() [83/114]
void XmlDocVisitor::operator() (const DocSection & s)
Definition at line 696 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<sect" << s.level() << " id=\"" << s.file();
  if (!s.anchor().isEmpty()) m_t << "_1" << s.anchor();
  m_t << "\">\n";
  m_t << "<title>";
  filter(convertCharEntitiesToUTF8(s.title()));
  m_t << "</title>\n";
  visitChildren(s);
  m_t << "</sect" << s.level() << ">\n";
}
References convertCharEntitiesToUTF8(), filter(), m_hide, m_t, s, and visitChildren().
operator()() [84/114]
void XmlDocVisitor::operator() (const DocSection &)
operator()() [85/114]
void XmlDocVisitor::operator() (const DocSeparator &)
Definition at line 1037 of file xmldocvisitor.cpp.
{
  m_t << "</parametertype>\n";
  m_t << "<parametertype>";
}
References m_t.
operator()() [86/114]
void XmlDocVisitor::operator() (const DocSeparator &)
operator()() [87/114]
void XmlDocVisitor::operator() (const DocSimpleList & l)
Definition at line 677 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<itemizedlist>\n";
  visitChildren(l);
  m_t << "</itemizedlist>\n";
}
References m_hide, m_t, and visitChildren().
operator()() [88/114]
void XmlDocVisitor::operator() (const DocSimpleList &)
operator()() [89/114]
void XmlDocVisitor::operator() (const DocSimpleListItem & li)
Definition at line 685 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<listitem>";
  if (li.paragraph())
  {
    std::visit(*this,*li.paragraph());
  }
  m_t << "</listitem>\n";
}
References m_hide, m_t, and DocSimpleListItem::paragraph().
operator()() [90/114]
void XmlDocVisitor::operator() (const DocSimpleListItem &)
operator()() [91/114]
void XmlDocVisitor::operator() (const DocSimpleSect & s)
Definition at line 657 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  startSimpleSect(m_t,s);
  if (s.title())
  {
    std::visit(*this,*s.title());
  }
  visitChildren(s);
  endSimpleSect(m_t,s);
}
References endSimpleSect(), m_hide, m_t, s, startSimpleSect(), and visitChildren().
operator()() [92/114]
void XmlDocVisitor::operator() (const DocSimpleSect &)
operator()() [93/114]
void XmlDocVisitor::operator() (const DocSimpleSectSep & sep)
Definition at line 592 of file xmldocvisitor.cpp.
{
  const DocSimpleSect *sect = std::get_if<DocSimpleSect>(sep.parent());
  if (sect)
  {
    endSimpleSect(m_t,*sect);
    startSimpleSect(m_t,*sect);
  }
}
References endSimpleSect(), m_t, DocNode::parent(), and startSimpleSect().
operator()() [94/114]
void XmlDocVisitor::operator() (const DocSimpleSectSep &)
operator()() [95/114]
void XmlDocVisitor::operator() (const DocStyleChange & s)
Definition at line 239 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  switch (s.style())
  {
    case DocStyleChange::Bold:
      if (s.enable()) m_t << "<bold>"; else m_t << "</bold>";
      break;
    case DocStyleChange::S:
      if (s.enable()) m_t << "<s>"; else m_t << "</s>";
      break;
    case DocStyleChange::Strike:
      if (s.enable()) m_t << "<strike>"; else m_t << "</strike>";
      break;
    case DocStyleChange::Del:
      if (s.enable()) m_t << "<del>"; else m_t << "</del>";
      break;
    case DocStyleChange::Underline:
      if (s.enable()) m_t << "<underline>"; else m_t << "</underline>";
      break;
    case DocStyleChange::Ins:
      if (s.enable()) m_t << "<ins>"; else m_t << "</ins>";
      break;
    case DocStyleChange::Italic:
      if (s.enable()) m_t << "<emphasis>"; else m_t << "</emphasis>";
      break;
    case DocStyleChange::Code:
      if (s.enable()) m_t << "<computeroutput>"; else m_t << "</computeroutput>";
      break;
    case DocStyleChange::Subscript:
      if (s.enable()) m_t << "<subscript>"; else m_t << "</subscript>";
      break;
    case DocStyleChange::Superscript:
      if (s.enable()) m_t << "<superscript>"; else m_t << "</superscript>";
      break;
    case DocStyleChange::Center:
      if (s.enable()) m_t << "<center>"; else m_t << "</center>";
      break;
    case DocStyleChange::Small:
      if (s.enable()) m_t << "<small>"; else m_t << "</small>";
      break;
    case DocStyleChange::Cite:
      if (s.enable()) m_t << "<cite>"; else m_t << "</cite>";
      break;
    case DocStyleChange::Preformatted:
      if (s.enable())
      {
        m_t << "<preformatted>";
        m_insidePre=TRUE;
      }
      else
      {
        m_t << "</preformatted>";
        m_insidePre=FALSE;
      }
      break;
    case DocStyleChange::Div: /* HTML only */ break;
    case DocStyleChange::Span: /* HTML only */ break;
  }
}
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Cite, DocStyleChange::Code, DocStyleChange::Del, DocStyleChange::Div, FALSE, DocStyleChange::Ins, DocStyleChange::Italic, m_hide, m_insidePre, m_t, DocStyleChange::Preformatted, s, DocStyleChange::S, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::Strike, DocStyleChange::Subscript, DocStyleChange::Superscript, TRUE, and DocStyleChange::Underline.
operator()() [96/114]
void XmlDocVisitor::operator() (const DocStyleChange &)
operator()() [97/114]
void XmlDocVisitor::operator() (const DocSymbol & s)
Definition at line 184 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  const char *res = HtmlEntityMapper::instance()->xml(s.symbol());
  if (res)
  {
    m_t << res;
  }
  else
  {
    err("XML: non supported HTML-entity found: %s\n",HtmlEntityMapper::instance()->html(s.symbol(),TRUE));
  }
}
References err(), HtmlEntityMapper::instance(), m_hide, m_t, s, TRUE, and HtmlEntityMapper::xml().
operator()() [98/114]
void XmlDocVisitor::operator() (const DocSymbol &)
operator()() [99/114]
void XmlDocVisitor::operator() (const DocText & t)
Definition at line 1117 of file xmldocvisitor.cpp.
{
  visitChildren(t);
}
References visitChildren().
operator()() [100/114]
void XmlDocVisitor::operator() (const DocText &)
operator()() [101/114]
void XmlDocVisitor::operator() (const DocTitle & t)
Definition at line 669 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<title>";
  visitChildren(t);
  m_t << "</title>";
}
References m_hide, m_t, and visitChildren().
operator()() [102/114]
void XmlDocVisitor::operator() (const DocTitle &)
operator()() [103/114]
void XmlDocVisitor::operator() (const DocURL & u)
Definition at line 216 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<ulink url=\"";
  if (u.isEmail()) m_t << "mailto:";
  filter(u.url());
  m_t << "\">";
  filter(u.url());
  m_t << "</ulink>";
}
References filter(), DocURL::isEmail(), m_hide, m_t, and DocURL::url().
operator()() [104/114]
void XmlDocVisitor::operator() (const DocURL &)
operator()() [105/114]
void XmlDocVisitor::operator() (const DocVerbatim & s)
Definition at line 300 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  QCString lang = m_langExt;
  if (!s.language().isEmpty()) // explicit language setting
  {
    lang = s.language();
  }
  SrcLangExt langExt = getLanguageFromCodeLang(lang);
  switch(s.type())
  {
    case DocVerbatim::Code:
      m_t << "<programlisting";
      if (!s.language().isEmpty())
          m_t << " filename=\"" << lang << "\">";
      else
          m_t << ">";
      getCodeParser(lang).parseCode(m_ci,s.context(),s.text(),langExt,
                                    s.isExample(),s.exampleFile());
      m_t << "</programlisting>";
      break;
    case DocVerbatim::JavaDocLiteral:
      m_t << "<javadocliteral>";
      filter(s.text());
      m_t << "</javadocliteral>";
      break;
    case DocVerbatim::JavaDocCode:
      m_t << "<javadoccode>";
      filter(s.text());
      m_t << "</javadoccode>";
      break;
    case DocVerbatim::Verbatim:
      m_t << "<verbatim>";
      filter(s.text());
      m_t << "</verbatim>";
      break;
    case DocVerbatim::HtmlOnly:
      if (s.isBlock())
      {
        m_t << "<htmlonly block=\"yes\">";
      }
      else
      {
        m_t << "<htmlonly>";
      }
      filter(s.text());
      m_t << "</htmlonly>";
      break;
    case DocVerbatim::RtfOnly:
      m_t << "<rtfonly>";
      filter(s.text());
      m_t << "</rtfonly>";
      break;
    case DocVerbatim::ManOnly:
      m_t << "<manonly>";
      filter(s.text());
      m_t << "</manonly>";
      break;
    case DocVerbatim::LatexOnly:
      m_t << "<latexonly>";
      filter(s.text());
      m_t << "</latexonly>";
      break;
    case DocVerbatim::DocbookOnly:
      m_t << "<docbookonly>";
      filter(s.text());
      m_t << "</docbookonly>";
      break;
    case DocVerbatim::XmlOnly:
      m_t << s.text();
      break;
    case DocVerbatim::Dot:
      visitPreStart(m_t, "dot", s.hasCaption(), *this, s.children(), QCString(""), FALSE, DocImage::Html, s.width(), s.height());
      filter(s.text());
      visitPostEnd(m_t, "dot");
      break;
    case DocVerbatim::Msc:
      visitPreStart(m_t, "msc", s.hasCaption(), *this, s.children(), QCString(""), FALSE, DocImage::Html, s.width(), s.height());
      filter(s.text());
      visitPostEnd(m_t, "msc");
      break;
    case DocVerbatim::PlantUML:
      visitPreStart(m_t, "plantuml", s.hasCaption(), *this, s.children(), QCString(""), FALSE, DocImage::Html, s.width(), s.height(), s.engine());
      filter(s.text());
      visitPostEnd(m_t, "plantuml");
      break;
  }
}
References DocVerbatim::Code, DocVerbatim::DocbookOnly, DocVerbatim::Dot, FALSE, filter(), DocVisitor::getCodeParser(), getLanguageFromCodeLang(), DocImage::Html, DocVerbatim::HtmlOnly, DocVerbatim::JavaDocCode, DocVerbatim::JavaDocLiteral, DocVerbatim::LatexOnly, m_ci, m_hide, m_langExt, m_t, DocVerbatim::ManOnly, DocVerbatim::Msc, CodeParserInterface::parseCode(), DocVerbatim::PlantUML, DocVerbatim::RtfOnly, s, DocVerbatim::Verbatim, visitPostEnd(), visitPreStart(), and DocVerbatim::XmlOnly.
operator()() [106/114]
void XmlDocVisitor::operator() (const DocVerbatim &)
operator()() [107/114]
void XmlDocVisitor::operator() (const DocVhdlFlow &)
Definition at line 1130 of file xmldocvisitor.cpp.
{
}
operator()() [108/114]
void XmlDocVisitor::operator() (const DocVhdlFlow &)
operator()() [109/114]
void XmlDocVisitor::operator() (const DocWhiteSpace & w)
Definition at line 171 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  if (m_insidePre)
  {
    m_t << w.chars();
  }
  else
  {
    m_t << " ";
  }
}
References m_hide, m_insidePre, m_t, and w.
operator()() [110/114]
void XmlDocVisitor::operator() (const DocWhiteSpace &)
operator()() [111/114]
void XmlDocVisitor::operator() (const DocWord & w)
Definition at line 157 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  filter(w.word());
}
References filter(), m_hide, and w.
operator()() [112/114]
void XmlDocVisitor::operator() (const DocWord &)
operator()() [113/114]
void XmlDocVisitor::operator() (const DocXRefItem & x)
Definition at line 1091 of file xmldocvisitor.cpp.
{
  if (m_hide) return;
  if (x.title().isEmpty()) return;
  m_t << "<xrefsect id=\"";
  m_t << x.file() << "_1" << x.anchor();
  m_t << "\">";
  m_t << "<xreftitle>";
  filter(x.title());
  m_t << "</xreftitle>";
  m_t << "<xrefdescription>";
  visitChildren(x);
  if (x.title().isEmpty()) return;
  m_t << "</xrefdescription>";
  m_t << "</xrefsect>";
}
References filter(), m_hide, m_t, visitChildren(), and x.
operator()() [114/114]
void XmlDocVisitor::operator() (const DocXRefItem &)
startLink() [1/2]
void XmlDocVisitor::startLink (const QCString & ref, const QCString & file, const QCString & anchor) [private]
Definition at line 1148 of file xmldocvisitor.cpp.
{
  //printf("XmlDocVisitor: file=%s anchor=%s\n",qPrint(file),qPrint(anchor));
  m_t << "<ref refid=\"" << file;
  if (!anchor.isEmpty()) m_t << "_1" << anchor;
  m_t << "\" kindref=\"";
  if (!anchor.isEmpty()) m_t << "member"; else m_t << "compound";
  m_t << "\"";
  if (!ref.isEmpty()) m_t << " external=\"" << ref << "\"";
  m_t << ">";
}
References caseconvert::file, QCString::isEmpty(), and m_t.
Referenced by operator()().
startLink() [2/2]
void XmlDocVisitor::startLink (const QCString & ref, const QCString & file, const QCString & anchor) [private]
visitChildren() [1/2]
template<class T >
void XmlDocVisitor::visitChildren (const T & t) [inline], [private]
Definition at line 107 of file xmldocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
Referenced by operator()().
visitChildren() [2/2]
template<class T >
void XmlDocVisitor::visitChildren (const T & t) [inline], [private]
Definition at line 107 of file xmldocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
Member Data Documentation
m_ci
CodeOutputInterface & XmlDocVisitor::m_ci [private]
Definition at line 129 of file xmldocvisitor.h.
Referenced by operator()().
m_hide
bool XmlDocVisitor::m_hide [private]
Definition at line 131 of file xmldocvisitor.h.
Referenced by operator()().
m_insidePre
bool XmlDocVisitor::m_insidePre [private]
Definition at line 130 of file xmldocvisitor.h.
Referenced by operator()().
m_langExt
QCString XmlDocVisitor::m_langExt [private]
Definition at line 132 of file xmldocvisitor.h.
Referenced by operator()().
m_t
TextStream & XmlDocVisitor::m_t [private]
Definition at line 128 of file xmldocvisitor.h.
Referenced by endLink(), filter(), operator()(), and startLink().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/xmldocvisitor.h
doxygen/src/xmldocvisitor.h
doxygen/build/doxygen/src/xmldocvisitor.cpp
doxygen/src/xmldocvisitor.cpp