DotWorkerThread Class Reference
#include <dotrunner.h>
Public Member Functions
DotWorkerThread (DotRunnerQueue *queue)
~DotWorkerThread ()
void run ()
void start ()
bool isRunning () const
void wait ()
DotWorkerThread (DotRunnerQueue *queue)
~DotWorkerThread ()
void run ()
void start ()
bool isRunning () const
void wait ()
Private Attributes
std::unique_ptr< std::thread > m_thread
DotRunnerQueue * m_queue
Detailed Description
Worker thread to execute a dot run
Definition at line 86 of file dotrunner.h.
Constructor & Destructor Documentation
DotWorkerThread() [1/2]
DotWorkerThread::DotWorkerThread (DotRunnerQueue * queue)
Definition at line 290 of file dotrunner.cpp.
  : m_queue(queue)
{
}
 DotWorkerThread() [1/2]
DotWorkerThread::~DotWorkerThread ()
Definition at line 295 of file dotrunner.cpp.
{
  if (isRunning())
  {
    wait();
  }
}
References isRunning(), and wait().
DotWorkerThread() [2/2]
DotWorkerThread::DotWorkerThread (DotRunnerQueue * queue)
 DotWorkerThread() [2/2]
DotWorkerThread::~DotWorkerThread ()
Member Function Documentation
isRunning() [1/2]
bool DotWorkerThread::isRunning () const [inline]
Definition at line 93 of file dotrunner.h.
{ return m_thread && m_thread->joinable(); }
References m_thread.
Referenced by ~DotWorkerThread().
isRunning() [2/2]
bool DotWorkerThread::isRunning () const [inline]
Definition at line 93 of file dotrunner.h.
{ return m_thread && m_thread->joinable(); }
References m_thread.
run() [1/2]
void DotWorkerThread::run ()
Definition at line 303 of file dotrunner.cpp.
{
  DotRunner *runner;
  while ((runner=m_queue->dequeue()))
  {
    runner->run();
  }
}
References DotRunnerQueue::dequeue(), m_queue, and DotRunner::run().
Referenced by start().
run() [2/2]
void DotWorkerThread::run ()
start() [1/2]
void DotWorkerThread::start ()
Definition at line 312 of file dotrunner.cpp.
{
  assert(!m_thread);
  m_thread = std::make_unique<std::thread>(&DotWorkerThread::run, this);
}
References m_thread, and run().
Referenced by doxmlparser.compound.docListType::__init__(), doxmlparser.compound.docListType::buildAttributes(), doxmlparser.compound.docListType::exportAttributes(), doxmlparser.compound.docListType::get_start(), and doxmlparser.compound.docListType::set_start().
start() [2/2]
void DotWorkerThread::start ()
Referenced by doxmlparser.compound.docListType::__init__(), doxmlparser.compound.docListType::buildAttributes(), doxmlparser.compound.docListType::exportAttributes(), doxmlparser.compound.docListType::get_start(), and doxmlparser.compound.docListType::set_start().
wait() [1/2]
void DotWorkerThread::wait () [inline]
Definition at line 94 of file dotrunner.h.
{ m_thread->join(); }
References m_thread.
Referenced by ~DotWorkerThread().
wait() [2/2]
void DotWorkerThread::wait () [inline]
Definition at line 94 of file dotrunner.h.
{ m_thread->join(); }
References m_thread.
Member Data Documentation
m_queue
DotRunnerQueue * DotWorkerThread::m_queue [private]
Definition at line 97 of file dotrunner.h.
Referenced by run().
m_thread
std::unique_ptr< std::thread > DotWorkerThread::m_thread [private]
Definition at line 96 of file dotrunner.h.
Referenced by isRunning(), start(), and wait().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dotrunner.h
doxygen/src/dotrunner.h
doxygen/build/doxygen/src/dotrunner.cpp
doxygen/src/dotrunner.cpp