DocVerbatim Class Reference
#include <docnode.h>
Classes
struct Private
Public Types
enum Type {
Code
, HtmlOnly
, ManOnly
, LatexOnly
,
RtfOnly
, XmlOnly
, Verbatim
, Dot
,
Msc
, DocbookOnly
, PlantUML
, JavaDocCode
,
JavaDocLiteral
, Code
, HtmlOnly
, ManOnly
,
LatexOnly
, RtfOnly
, XmlOnly
, Verbatim
,
Dot
, Msc
, DocbookOnly
, PlantUML
,
JavaDocCode
, JavaDocLiteral
 }
enum Type {
Code
, HtmlOnly
, ManOnly
, LatexOnly
,
RtfOnly
, XmlOnly
, Verbatim
, Dot
,
Msc
, DocbookOnly
, PlantUML
, JavaDocCode
,
JavaDocLiteral
, Code
, HtmlOnly
, ManOnly
,
LatexOnly
, RtfOnly
, XmlOnly
, Verbatim
,
Dot
, Msc
, DocbookOnly
, PlantUML
,
JavaDocCode
, JavaDocLiteral
 }
Public Member Functions
DocVerbatim (DocParser *parser, DocNodeVariant *parent, const QCString &context, const QCString &text, Type t, bool isExample, const QCString &exampleFile, bool isBlock=FALSE, const QCString &lang=QCString())
Type type () const
QCString text () const
QCString context () const
bool isExample () const
QCString exampleFile () const
QCString relPath () const
QCString language () const
bool isBlock () const
bool hasCaption () const
QCString width () const
QCString height () const
QCString engine () const
bool useBitmap () const
const DocNodeList & children () const
DocNodeList & children ()
QCString srcFile () const
int srcLine () const
void setText (const QCString &t)
void setWidth (const QCString &w)
void setHeight (const QCString &h)
void setEngine (const QCString &e)
void setUseBitmap (const bool &u)
void setLocation (const QCString &file, int line)
DocVerbatim (DocParser *parser, DocNodeVariant *parent, const QCString &context, const QCString &text, Type t, bool isExample, const QCString &exampleFile, bool isBlock=FALSE, const QCString &lang=QCString())
Type type () const
QCString text () const
QCString context () const
bool isExample () const
QCString exampleFile () const
QCString relPath () const
QCString language () const
bool isBlock () const
bool hasCaption () const
QCString width () const
QCString height () const
QCString engine () const
bool useBitmap () const
const DocNodeList & children () const
DocNodeList & children ()
QCString srcFile () const
int srcLine () const
void setText (const QCString &t)
void setWidth (const QCString &w)
void setHeight (const QCString &h)
void setEngine (const QCString &e)
void setUseBitmap (const bool &u)
void setLocation (const QCString &file, int line)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Node representing a verbatim, unparsed text fragment
Definition at line 349 of file docnode.h.
Member Enumeration Documentation
Type [1/2]
enum DocVerbatim::Type
Enumerator
Code
HtmlOnly
ManOnly
LatexOnly
RtfOnly
XmlOnly
Verbatim
Dot
Msc
DocbookOnly
PlantUML
JavaDocCode
JavaDocLiteral
Code
HtmlOnly
ManOnly
LatexOnly
RtfOnly
XmlOnly
Verbatim
Dot
Msc
DocbookOnly
PlantUML
JavaDocCode
JavaDocLiteral
Definition at line 352 of file docnode.h.
{ Code, HtmlOnly, ManOnly, LatexOnly, RtfOnly, XmlOnly, Verbatim, Dot, Msc, DocbookOnly, PlantUML, JavaDocCode, JavaDocLiteral };
Type [2/2]
enum DocVerbatim::Type
Enumerator
Code
HtmlOnly
ManOnly
LatexOnly
RtfOnly
XmlOnly
Verbatim
Dot
Msc
DocbookOnly
PlantUML
JavaDocCode
JavaDocLiteral
Code
HtmlOnly
ManOnly
LatexOnly
RtfOnly
XmlOnly
Verbatim
Dot
Msc
DocbookOnly
PlantUML
JavaDocCode
JavaDocLiteral
Definition at line 352 of file docnode.h.
{ Code, HtmlOnly, ManOnly, LatexOnly, RtfOnly, XmlOnly, Verbatim, Dot, Msc, DocbookOnly, PlantUML, JavaDocCode, JavaDocLiteral };
Constructor & Destructor Documentation
DocVerbatim() [1/2]
DocVerbatim::DocVerbatim (DocParser * parser, DocNodeVariant * parent, const QCString & context, const QCString & text, Type t, bool isExample, const QCString & exampleFile, bool isBlock = FALSE, const QCString & lang = QCString())
Definition at line 252 of file docnode.cpp.
  : DocNode(parser,parent), p(std::make_unique<Private>(context, text, t, isExample, exampleFile, parser->context.relPath, lang, isBlock))
{
}
DocVerbatim() [2/2]
DocVerbatim::DocVerbatim (DocParser * parser, DocNodeVariant * parent, const QCString & context, const QCString & text, Type t, bool isExample, const QCString & exampleFile, bool isBlock = FALSE, const QCString & lang = QCString())
Member Function Documentation
children() [1/4]
DocNodeList & DocVerbatim::children () [inline]
Definition at line 370 of file docnode.h.
{ return p->children; }
References p.
children() [2/4]
DocNodeList & DocVerbatim::children () [inline]
Definition at line 370 of file docnode.h.
{ return p->children; }
References p.
children() [3/4]
const DocNodeList & DocVerbatim::children () const [inline]
Definition at line 369 of file docnode.h.
{ return p->children; }
References p.
children() [4/4]
const DocNodeList & DocVerbatim::children () const [inline]
Definition at line 369 of file docnode.h.
{ return p->children; }
References p.
context() [1/2]
QCString DocVerbatim::context () const [inline]
Definition at line 358 of file docnode.h.
{ return p->context; }
References p.
context() [2/2]
QCString DocVerbatim::context () const [inline]
Definition at line 358 of file docnode.h.
{ return p->context; }
References p.
engine() [1/2]
QCString DocVerbatim::engine () const [inline]
Definition at line 367 of file docnode.h.
{ return p->engine; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docPlantumlType::get_engine(), and doxmlparser.compound.docPlantumlType::set_engine().
engine() [2/2]
QCString DocVerbatim::engine () const [inline]
Definition at line 367 of file docnode.h.
{ return p->engine; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docPlantumlType::get_engine(), and doxmlparser.compound.docPlantumlType::set_engine().
exampleFile() [1/2]
QCString DocVerbatim::exampleFile () const [inline]
Definition at line 360 of file docnode.h.
{ return p->exampleFile; }
References p.
exampleFile() [2/2]
QCString DocVerbatim::exampleFile () const [inline]
Definition at line 360 of file docnode.h.
{ return p->exampleFile; }
References p.
hasCaption() [1/2]
bool DocVerbatim::hasCaption () const [inline]
Definition at line 364 of file docnode.h.
{ return !p->children.empty(); }
References p.
hasCaption() [2/2]
bool DocVerbatim::hasCaption () const [inline]
Definition at line 364 of file docnode.h.
{ return !p->children.empty(); }
References p.
height() [1/2]
QCString DocVerbatim::height () const [inline]
Definition at line 366 of file docnode.h.
{ return p->height; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docImageType::get_height(), doxmlparser.compound.docDotMscType::get_height(), doxmlparser.compound.docImageFileType::get_height(), doxmlparser.compound.docPlantumlType::get_height(), doxmlparser.compound.docImageType::set_height(), doxmlparser.compound.docDotMscType::set_height(), doxmlparser.compound.docImageFileType::set_height(), and doxmlparser.compound.docPlantumlType::set_height().
height() [2/2]
QCString DocVerbatim::height () const [inline]
Definition at line 366 of file docnode.h.
{ return p->height; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docImageType::get_height(), doxmlparser.compound.docDotMscType::get_height(), doxmlparser.compound.docImageFileType::get_height(), doxmlparser.compound.docPlantumlType::get_height(), doxmlparser.compound.docImageType::set_height(), doxmlparser.compound.docDotMscType::set_height(), doxmlparser.compound.docImageFileType::set_height(), and doxmlparser.compound.docPlantumlType::set_height().
isBlock() [1/2]
bool DocVerbatim::isBlock () const [inline]
Definition at line 363 of file docnode.h.
{ return p->isBlock; }
References p.
Referenced by mustBeOutsideParagraph().
isBlock() [2/2]
bool DocVerbatim::isBlock () const [inline]
Definition at line 363 of file docnode.h.
{ return p->isBlock; }
References p.
isExample() [1/2]
bool DocVerbatim::isExample () const [inline]
Definition at line 359 of file docnode.h.
{ return p->isExample; }
References p.
isExample() [2/2]
bool DocVerbatim::isExample () const [inline]
Definition at line 359 of file docnode.h.
{ return p->isExample; }
References p.
language() [1/2]
QCString DocVerbatim::language () const [inline]
Definition at line 362 of file docnode.h.
{ return p->lang; }
References p.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_language(), doxmlparser.compound.docMarkupType::add_language(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.compounddefType::get_language(), doxmlparser.compound.docParaType::get_language(), doxmlparser.compound.docMarkupType::get_language(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docParaType::insert_language_at(), doxmlparser.compound.docMarkupType::insert_language_at(), doxmlparser.compound.docParaType::replace_language_at(), doxmlparser.compound.docMarkupType::replace_language_at(), doxmlparser.compound.compounddefType::set_language(), doxmlparser.compound.docParaType::set_language(), and doxmlparser.compound.docMarkupType::set_language().
language() [2/2]
QCString DocVerbatim::language () const [inline]
Definition at line 362 of file docnode.h.
{ return p->lang; }
References p.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_language(), doxmlparser.compound.docMarkupType::add_language(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.compounddefType::get_language(), doxmlparser.compound.docParaType::get_language(), doxmlparser.compound.docMarkupType::get_language(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docParaType::insert_language_at(), doxmlparser.compound.docMarkupType::insert_language_at(), doxmlparser.compound.docParaType::replace_language_at(), doxmlparser.compound.docMarkupType::replace_language_at(), doxmlparser.compound.compounddefType::set_language(), doxmlparser.compound.docParaType::set_language(), and doxmlparser.compound.docMarkupType::set_language().
relPath() [1/2]
QCString DocVerbatim::relPath () const [inline]
Definition at line 361 of file docnode.h.
{ return p->relPath; }
References p.
relPath() [2/2]
QCString DocVerbatim::relPath () const [inline]
Definition at line 361 of file docnode.h.
{ return p->relPath; }
References p.
setEngine() [1/2]
void DocVerbatim::setEngine (const QCString & e) [inline]
Definition at line 376 of file docnode.h.
{ p->engine=e; }
References e, and p.
Referenced by DocPara::handleCommand().
setEngine() [2/2]
void DocVerbatim::setEngine (const QCString & e) [inline]
Definition at line 376 of file docnode.h.
{ p->engine=e; }
References e, and p.
setHeight() [1/2]
void DocVerbatim::setHeight (const QCString & h) [inline]
Definition at line 375 of file docnode.h.
{ p->height=h; }
References h, and p.
setHeight() [2/2]
void DocVerbatim::setHeight (const QCString & h) [inline]
Definition at line 375 of file docnode.h.
{ p->height=h; }
References h, and p.
setLocation() [1/2]
void DocVerbatim::setLocation (const QCString & file, int line) [inline]
Definition at line 378 of file docnode.h.
{ p->srcFile=file; p->srcLine=line; }
References caseconvert::file, and p.
setLocation() [2/2]
void DocVerbatim::setLocation (const QCString & file, int line) [inline]
Definition at line 378 of file docnode.h.
{ p->srcFile=file; p->srcLine=line; }
References caseconvert::file, and p.
setText() [1/2]
void DocVerbatim::setText (const QCString & t) [inline]
Definition at line 373 of file docnode.h.
{ p->text=t; }
References p.
setText() [2/2]
void DocVerbatim::setText (const QCString & t) [inline]
Definition at line 373 of file docnode.h.
{ p->text=t; }
References p.
setUseBitmap() [1/2]
void DocVerbatim::setUseBitmap (const bool & u) [inline]
Definition at line 377 of file docnode.h.
{ p->useBitmap=u; }
References p.
setUseBitmap() [2/2]
void DocVerbatim::setUseBitmap (const bool & u) [inline]
Definition at line 377 of file docnode.h.
{ p->useBitmap=u; }
References p.
setWidth() [1/2]
void DocVerbatim::setWidth (const QCString & w) [inline]
Definition at line 374 of file docnode.h.
{ p->width=w; }
References p, and w.
setWidth() [2/2]
void DocVerbatim::setWidth (const QCString & w) [inline]
Definition at line 374 of file docnode.h.
{ p->width=w; }
References p, and w.
srcFile() [1/2]
QCString DocVerbatim::srcFile () const [inline]
Definition at line 371 of file docnode.h.
{ return p->srcFile; }
References p.
srcFile() [2/2]
QCString DocVerbatim::srcFile () const [inline]
Definition at line 371 of file docnode.h.
{ return p->srcFile; }
References p.
srcLine() [1/2]
int DocVerbatim::srcLine () const [inline]
Definition at line 372 of file docnode.h.
{ return p->srcLine; }
References p.
srcLine() [2/2]
int DocVerbatim::srcLine () const [inline]
Definition at line 372 of file docnode.h.
{ return p->srcLine; }
References p.
text() [1/2]
QCString DocVerbatim::text () const [inline]
Definition at line 357 of file docnode.h.
{ return p->text; }
References p.
text() [2/2]
QCString DocVerbatim::text () const [inline]
Definition at line 357 of file docnode.h.
{ return p->text; }
References p.
type() [1/2]
Type DocVerbatim::type () const [inline]
Definition at line 356 of file docnode.h.
{ return p->type; }
References p.
Referenced by mustBeOutsideParagraph().
type() [2/2]
Type DocVerbatim::type () const [inline]
Definition at line 356 of file docnode.h.
{ return p->type; }
References p.
useBitmap() [1/2]
bool DocVerbatim::useBitmap () const [inline]
Definition at line 368 of file docnode.h.
{ return p->useBitmap; }
References p.
useBitmap() [2/2]
bool DocVerbatim::useBitmap () const [inline]
Definition at line 368 of file docnode.h.
{ return p->useBitmap; }
References p.
width() [1/2]
QCString DocVerbatim::width () const [inline]
Definition at line 365 of file docnode.h.
{ return p->width; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docEntryType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docTableType::buildAttributes(), doxmlparser.compound.docEntryType::buildAttributes(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEntryType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docTableType::exportAttributes(), doxmlparser.compound.docTableType::get_width(), doxmlparser.compound.docEntryType::get_width(), doxmlparser.compound.docImageType::get_width(), doxmlparser.compound.docDotMscType::get_width(), doxmlparser.compound.docImageFileType::get_width(), doxmlparser.compound.docPlantumlType::get_width(), doxmlparser.compound.docTableType::set_width(), doxmlparser.compound.docEntryType::set_width(), doxmlparser.compound.docImageType::set_width(), doxmlparser.compound.docDotMscType::set_width(), doxmlparser.compound.docImageFileType::set_width(), and doxmlparser.compound.docPlantumlType::set_width().
width() [2/2]
QCString DocVerbatim::width () const [inline]
Definition at line 365 of file docnode.h.
{ return p->width; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docEntryType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docTableType::buildAttributes(), doxmlparser.compound.docEntryType::buildAttributes(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEntryType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docTableType::exportAttributes(), doxmlparser.compound.docTableType::get_width(), doxmlparser.compound.docEntryType::get_width(), doxmlparser.compound.docImageType::get_width(), doxmlparser.compound.docDotMscType::get_width(), doxmlparser.compound.docImageFileType::get_width(), doxmlparser.compound.docPlantumlType::get_width(), doxmlparser.compound.docTableType::set_width(), doxmlparser.compound.docEntryType::set_width(), doxmlparser.compound.docImageType::set_width(), doxmlparser.compound.docDotMscType::set_width(), doxmlparser.compound.docImageFileType::set_width(), and doxmlparser.compound.docPlantumlType::set_width().
Member Data Documentation
p
std::unique_ptr< Private > DocVerbatim::p [private]
Definition at line 403 of file docnode.h.
Referenced by children(), context(), engine(), exampleFile(), hasCaption(), height(), isBlock(), isExample(), language(), relPath(), setEngine(), setHeight(), setLocation(), setText(), setUseBitmap(), setWidth(), srcFile(), srcLine(), text(), type(), useBitmap(), and width().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp