TemplateFilterFactory Class Reference
Factory singleton for registering and creating filters.
Classes
class AutoRegister
Helper class for registering a filter function.
Public Types
typedef TemplateVariant() FilterFunction(const TemplateVariant &v, const TemplateVariant &arg)
typedef TemplateVariant() FilterFunction(const TemplateVariant &v, const TemplateVariant &arg)
Public Member Functions
TemplateVariant apply (const QCString &name, const TemplateVariant &v, const TemplateVariant &arg, bool &ok)
void registerFilter (const QCString &name, FilterFunction *func)
TemplateVariant apply (const QCString &name, const TemplateVariant &v, const TemplateVariant &arg, bool &ok)
void registerFilter (const QCString &name, FilterFunction *func)
Static Public Member Functions
static TemplateFilterFactory & instance ()
static TemplateFilterFactory & instance ()
Private Attributes
std::unordered_map< std::string, FilterFunction * > m_registry
Detailed Description
Factory singleton for registering and creating filters.
Definition at line 1582 of file template.cpp.
Member Typedef Documentation
FilterFunction [1/2]
typedef TemplateVariant() TemplateFilterFactory::FilterFunction(const TemplateVariant &v, const TemplateVariant &arg)
Definition at line 1585 of file template.cpp.
FilterFunction [2/2]
typedef TemplateVariant() TemplateFilterFactory::FilterFunction(const TemplateVariant &v, const TemplateVariant &arg)
Definition at line 1585 of file template.cpp.
Member Function Documentation
apply() [1/2]
TemplateVariant TemplateFilterFactory::apply (const QCString & name, const TemplateVariant & v, const TemplateVariant & arg, bool & ok) [inline]
Definition at line 1594 of file template.cpp.
    {
      auto it = m_registry.find(name.str());
      if (it!=m_registry.end())
      {
        ok=TRUE;
        return it->second(v,arg);
      }
      else
      {
        ok=FALSE;
        return v;
      }
    }
References FALSE, m_registry, setup::name, and TRUE.
Referenced by ExprAstFilter::apply().
apply() [2/2]
TemplateVariant TemplateFilterFactory::apply (const QCString & name, const TemplateVariant & v, const TemplateVariant & arg, bool & ok) [inline]
Definition at line 1594 of file template.cpp.
    {
      auto it = m_registry.find(name.str());
      if (it!=m_registry.end())
      {
        ok=TRUE;
        return it->second(v,arg);
      }
      else
      {
        ok=FALSE;
        return v;
      }
    }
References FALSE, setup::name, and TRUE.
instance() [1/2]
static TemplateFilterFactory & TemplateFilterFactory::instance () [inline], [static]
Definition at line 1587 of file template.cpp.
    {
      static std::unique_ptr<TemplateFilterFactory> instance;
      if (instance==0) instance = std::make_unique<TemplateFilterFactory>();
      return *instance;
    }
References instance().
Referenced by ExprAstFilter::apply(), and instance().
instance() [2/2]
static TemplateFilterFactory & TemplateFilterFactory::instance () [inline], [static]
Definition at line 1587 of file template.cpp.
    {
      static std::unique_ptr<TemplateFilterFactory> instance;
      if (instance==0) instance = std::make_unique<TemplateFilterFactory>();
      return *instance;
    }
registerFilter() [1/2]
void TemplateFilterFactory::registerFilter (const QCString & name, FilterFunction * func) [inline]
Definition at line 1609 of file template.cpp.
    {
      m_registry.insert(std::make_pair(name.str(),func));
    }
References docstring::func(), m_registry, and setup::name.
registerFilter() [2/2]
void TemplateFilterFactory::registerFilter (const QCString & name, FilterFunction * func) [inline]
Definition at line 1609 of file template.cpp.
    {
      m_registry.insert(std::make_pair(name.str(),func));
    }
References docstring::func(), and setup::name.
Member Data Documentation
m_registry
std::unordered_map< std::string, FilterFunction * > TemplateFilterFactory::m_registry [private]
Definition at line 1625 of file template.cpp.
Referenced by apply(), and registerFilter().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp