MemberDefAliasImpl Class Reference
Public Member Functions
MemberDefAliasImpl (const Definition *newScope, const MemberDef *md)
virtual ~MemberDefAliasImpl ()
virtual DefType definitionType () const
const MemberDef * getMdAlias () const
virtual MemberDef * resolveAlias ()
virtual const MemberDef * resolveAlias () const
virtual MemberDef * deepCopy () const
virtual void moveTo (Definition *)
virtual QCString name () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString getReference () const
virtual QCString anchor () const
virtual QCString declaration () const
virtual QCString definition () const
virtual QCString typeString () const
virtual QCString argsString () const
virtual QCString excpString () const
virtual QCString bitfieldString () const
virtual QCString extraTypeChars () const
virtual const QCString & initializer () const
virtual int initializerLines () const
virtual uint64 getMemberSpecifiers () const
virtual const MemberList * getSectionList (const Definition *container) const
virtual QCString displayDefinition () const
virtual const ClassDef * getClassDef () const
virtual const FileDef * getFileDef () const
virtual const NamespaceDef * getNamespaceDef () const
virtual const ClassDef * accessorClass () const
virtual QCString getReadAccessor () const
virtual QCString getWriteAccessor () const
virtual const GroupDef * getGroupDef () const
virtual Grouping::GroupPri_t getGroupPri () const
virtual QCString getGroupFileName () const
virtual int getGroupStartLine () const
virtual bool getGroupHasDocs () const
virtual QCString qualifiedName () const
virtual QCString objCMethodName (bool localLink, bool showStatic) const
virtual Protection protection () const
virtual Specifier virtualness (int count) const
virtual MemberType memberType () const
virtual QCString memberTypeName () const
virtual bool isSignal () const
virtual bool isSlot () const
virtual bool isVariable () const
virtual bool isEnumerate () const
virtual bool isEnumValue () const
virtual bool isTypedef () const
virtual bool isSequence () const
virtual bool isDictionary () const
virtual bool isFunction () const
virtual bool isFunctionPtr () const
virtual bool isDefine () const
virtual bool isFriend () const
virtual bool isDCOP () const
virtual bool isProperty () const
virtual bool isEvent () const
virtual bool isRelated () const
virtual bool isForeign () const
virtual bool isStatic () const
virtual bool isInline () const
virtual bool isExplicit () const
virtual bool isMutable () const
virtual bool isGettable () const
virtual bool isPrivateGettable () const
virtual bool isProtectedGettable () const
virtual bool isSettable () const
virtual bool isPrivateSettable () const
virtual bool isProtectedSettable () const
virtual bool isReadable () const
virtual bool isWritable () const
virtual bool isAddable () const
virtual bool isRemovable () const
virtual bool isRaisable () const
virtual bool isFinal () const
virtual bool isAbstract () const
virtual bool isOverride () const
virtual bool isInitonly () const
virtual bool isOptional () const
virtual bool isRequired () const
virtual bool isNonAtomic () const
virtual bool isCopy () const
virtual bool isAssign () const
virtual bool isRetain () const
virtual bool isWeak () const
virtual bool isStrong () const
virtual bool isEnumStruct () const
virtual bool isUnretained () const
virtual bool isNew () const
virtual bool isSealed () const
virtual bool isImplementation () const
virtual bool isExternal () const
virtual bool isTypeAlias () const
virtual bool isDefault () const
virtual bool isDelete () const
virtual bool isNoExcept () const
virtual bool isAttribute () const
virtual bool isUNOProperty () const
virtual bool isReadonly () const
virtual bool isBound () const
virtual bool isConstrained () const
virtual bool isTransient () const
virtual bool isMaybeVoid () const
virtual bool isMaybeDefault () const
virtual bool isMaybeAmbiguous () const
virtual bool isPublished () const
virtual bool isTemplateSpecialization () const
virtual bool isObjCMethod () const
virtual bool isObjCProperty () const
virtual bool isCSharpProperty () const
virtual bool isConstructor () const
virtual bool isDestructor () const
virtual bool hasOneLineInitializer () const
virtual bool hasMultiLineInitializer () const
virtual bool showInCallGraph () const
virtual bool isStrongEnumValue () const
virtual bool livesInsideEnum () const
virtual bool isSliceLocal () const
virtual bool isConstExpr () const
virtual int numberOfFlowKeyWords () const
virtual bool isFriendToHide () const
virtual bool isNotFriend () const
virtual bool isFunctionOrSignalSlot () const
virtual bool isRelatedOrFriend () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool hasDocumentation () const
virtual bool isDeleted () const
virtual bool isBriefSectionVisible () const
virtual bool isDetailedSectionVisible (MemberListContainer container) const
virtual bool hasDetailedDescription () const
virtual bool isFriendClass () const
virtual bool isDocumentedFriendClass () const
virtual const MemberDef * reimplements () const
virtual const MemberVector & reimplementedBy () const
virtual bool isReimplementedBy (const ClassDef *cd) const
virtual ClassDef * relatedAlso () const
virtual bool hasDocumentedEnumValues () const
virtual const MemberDef * getAnonymousEnumType () const
virtual bool isDocsForDefinition () const
virtual const MemberDef * getEnumScope () const
virtual const MemberVector & enumFieldList () const
virtual QCString enumBaseType () const
virtual bool hasExamples () const
virtual const ExampleList & getExamples () const
virtual bool isPrototype () const
virtual const ArgumentList & argumentList () const
virtual const ArgumentList & declArgumentList () const
virtual const ArgumentList & templateArguments () const
virtual const ArgumentLists & definitionTemplateParameterLists () const
virtual int getMemberGroupId () const
virtual MemberGroup * getMemberGroup () const
virtual bool fromAnonymousScope () const
virtual bool anonymousDeclShown () const
virtual MemberDef * fromAnonymousMember () const
virtual bool hasCallGraph () const
virtual bool hasCallerGraph () const
virtual bool hasReferencesRelation () const
virtual bool hasReferencedByRelation () const
virtual const MemberDef * templateMaster () const
virtual QCString getScopeString () const
virtual ClassDef * getClassDefOfAnonymousType () const
virtual bool isTypedefValCached () const
virtual const ClassDef * getCachedTypedefVal () const
virtual QCString getCachedTypedefTemplSpec () const
virtual QCString getCachedResolvedTypedef () const
virtual MemberDef * memberDefinition () const
virtual MemberDef * memberDeclaration () const
virtual const MemberDef * inheritsDocsFrom () const
virtual const MemberDef * getGroupAlias () const
virtual ClassDef * category () const
virtual const MemberDef * categoryRelation () const
virtual QCString displayName (bool b=TRUE) const
virtual QCString getDeclType () const
virtual StringVector getLabels (const Definition *container) const
virtual const ArgumentList & typeConstraints () const
virtual QCString documentation () const
virtual QCString briefDescription (bool abbr=FALSE) const
virtual QCString fieldType () const
virtual bool isReference () const
virtual QCString getDeclFileName () const
virtual int getDeclLine () const
virtual int getDeclColumn () const
virtual QCString requiresClause () const
virtual bool visibleInIndex () const
virtual void warnIfUndocumented () const
virtual void warnIfUndocumentedParams () const
virtual void detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const
virtual void setMemberGroup (MemberGroup *grp)
virtual MemberDefMutable * createTemplateInstanceMember (const ArgumentList &formalArgs, const std::unique_ptr< ArgumentList > &actualArgs) const
virtual void writeDeclaration (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool inGroup, int indentLevel, const ClassDef *inheritFrom=0, const QCString &inheritId=QCString()) const
virtual void writeEnumDeclaration (OutputList &typeDecl, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd) const
MemberDefAliasImpl (const Definition *newScope, const MemberDef *md)
virtual ~MemberDefAliasImpl ()
virtual DefType definitionType () const
const MemberDef * getMdAlias () const
virtual MemberDef * resolveAlias ()
virtual const MemberDef * resolveAlias () const
virtual MemberDef * deepCopy () const
virtual void moveTo (Definition *)
virtual QCString name () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString getReference () const
virtual QCString anchor () const
virtual QCString declaration () const
virtual QCString definition () const
virtual QCString typeString () const
virtual QCString argsString () const
virtual QCString excpString () const
virtual QCString bitfieldString () const
virtual QCString extraTypeChars () const
virtual const QCString & initializer () const
virtual int initializerLines () const
virtual uint64 getMemberSpecifiers () const
virtual const MemberList * getSectionList (const Definition *container) const
virtual QCString displayDefinition () const
virtual const ClassDef * getClassDef () const
virtual const FileDef * getFileDef () const
virtual const NamespaceDef * getNamespaceDef () const
virtual const ClassDef * accessorClass () const
virtual QCString getReadAccessor () const
virtual QCString getWriteAccessor () const
virtual const GroupDef * getGroupDef () const
virtual Grouping::GroupPri_t getGroupPri () const
virtual QCString getGroupFileName () const
virtual int getGroupStartLine () const
virtual bool getGroupHasDocs () const
virtual QCString qualifiedName () const
virtual QCString objCMethodName (bool localLink, bool showStatic) const
virtual Protection protection () const
virtual Specifier virtualness (int count) const
virtual MemberType memberType () const
virtual QCString memberTypeName () const
virtual bool isSignal () const
virtual bool isSlot () const
virtual bool isVariable () const
virtual bool isEnumerate () const
virtual bool isEnumValue () const
virtual bool isTypedef () const
virtual bool isSequence () const
virtual bool isDictionary () const
virtual bool isFunction () const
virtual bool isFunctionPtr () const
virtual bool isDefine () const
virtual bool isFriend () const
virtual bool isDCOP () const
virtual bool isProperty () const
virtual bool isEvent () const
virtual bool isRelated () const
virtual bool isForeign () const
virtual bool isStatic () const
virtual bool isInline () const
virtual bool isExplicit () const
virtual bool isMutable () const
virtual bool isGettable () const
virtual bool isPrivateGettable () const
virtual bool isProtectedGettable () const
virtual bool isSettable () const
virtual bool isPrivateSettable () const
virtual bool isProtectedSettable () const
virtual bool isReadable () const
virtual bool isWritable () const
virtual bool isAddable () const
virtual bool isRemovable () const
virtual bool isRaisable () const
virtual bool isFinal () const
virtual bool isAbstract () const
virtual bool isOverride () const
virtual bool isInitonly () const
virtual bool isOptional () const
virtual bool isRequired () const
virtual bool isNonAtomic () const
virtual bool isCopy () const
virtual bool isAssign () const
virtual bool isRetain () const
virtual bool isWeak () const
virtual bool isStrong () const
virtual bool isEnumStruct () const
virtual bool isUnretained () const
virtual bool isNew () const
virtual bool isSealed () const
virtual bool isImplementation () const
virtual bool isExternal () const
virtual bool isTypeAlias () const
virtual bool isDefault () const
virtual bool isDelete () const
virtual bool isNoExcept () const
virtual bool isAttribute () const
virtual bool isUNOProperty () const
virtual bool isReadonly () const
virtual bool isBound () const
virtual bool isConstrained () const
virtual bool isTransient () const
virtual bool isMaybeVoid () const
virtual bool isMaybeDefault () const
virtual bool isMaybeAmbiguous () const
virtual bool isPublished () const
virtual bool isTemplateSpecialization () const
virtual bool isObjCMethod () const
virtual bool isObjCProperty () const
virtual bool isCSharpProperty () const
virtual bool isConstructor () const
virtual bool isDestructor () const
virtual bool hasOneLineInitializer () const
virtual bool hasMultiLineInitializer () const
virtual bool showInCallGraph () const
virtual bool isStrongEnumValue () const
virtual bool livesInsideEnum () const
virtual bool isSliceLocal () const
virtual bool isConstExpr () const
virtual int numberOfFlowKeyWords () const
virtual bool isFriendToHide () const
virtual bool isNotFriend () const
virtual bool isFunctionOrSignalSlot () const
virtual bool isRelatedOrFriend () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool hasDocumentation () const
virtual bool isDeleted () const
virtual bool isBriefSectionVisible () const
virtual bool isDetailedSectionVisible (MemberListContainer container) const
virtual bool hasDetailedDescription () const
virtual bool isFriendClass () const
virtual bool isDocumentedFriendClass () const
virtual const MemberDef * reimplements () const
virtual const MemberVector & reimplementedBy () const
virtual bool isReimplementedBy (const ClassDef *cd) const
virtual ClassDef * relatedAlso () const
virtual bool hasDocumentedEnumValues () const
virtual const MemberDef * getAnonymousEnumType () const
virtual bool isDocsForDefinition () const
virtual const MemberDef * getEnumScope () const
virtual const MemberVector & enumFieldList () const
virtual QCString enumBaseType () const
virtual bool hasExamples () const
virtual const ExampleList & getExamples () const
virtual bool isPrototype () const
virtual const ArgumentList & argumentList () const
virtual const ArgumentList & declArgumentList () const
virtual const ArgumentList & templateArguments () const
virtual const ArgumentLists & definitionTemplateParameterLists () const
virtual int getMemberGroupId () const
virtual MemberGroup * getMemberGroup () const
virtual bool fromAnonymousScope () const
virtual bool anonymousDeclShown () const
virtual MemberDef * fromAnonymousMember () const
virtual bool hasCallGraph () const
virtual bool hasCallerGraph () const
virtual bool hasReferencesRelation () const
virtual bool hasReferencedByRelation () const
virtual const MemberDef * templateMaster () const
virtual QCString getScopeString () const
virtual ClassDef * getClassDefOfAnonymousType () const
virtual bool isTypedefValCached () const
virtual const ClassDef * getCachedTypedefVal () const
virtual QCString getCachedTypedefTemplSpec () const
virtual QCString getCachedResolvedTypedef () const
virtual MemberDef * memberDefinition () const
virtual MemberDef * memberDeclaration () const
virtual const MemberDef * inheritsDocsFrom () const
virtual const MemberDef * getGroupAlias () const
virtual ClassDef * category () const
virtual const MemberDef * categoryRelation () const
virtual QCString displayName (bool b=TRUE) const
virtual QCString getDeclType () const
virtual StringVector getLabels (const Definition *container) const
virtual const ArgumentList & typeConstraints () const
virtual QCString documentation () const
virtual QCString briefDescription (bool abbr=FALSE) const
virtual QCString fieldType () const
virtual bool isReference () const
virtual QCString getDeclFileName () const
virtual int getDeclLine () const
virtual int getDeclColumn () const
virtual QCString requiresClause () const
virtual bool visibleInIndex () const
virtual void warnIfUndocumented () const
virtual void warnIfUndocumentedParams () const
virtual void detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const
virtual void setMemberGroup (MemberGroup *grp)
virtual MemberDefMutable * createTemplateInstanceMember (const ArgumentList &formalArgs, const std::unique_ptr< ArgumentList > &actualArgs) const
virtual void writeDeclaration (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool inGroup, int indentLevel, const ClassDef *inheritFrom=0, const QCString &inheritId=QCString()) const
virtual void writeEnumDeclaration (OutputList &typeDecl, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd) const
Private Attributes
MemberGroup * m_memberGroup
Additional Inherited Members
Detailed Description
Definition at line 385 of file memberdef.cpp.
Constructor & Destructor Documentation
MemberDefAliasImpl() [1/2]
MemberDefAliasImpl::MemberDefAliasImpl (const Definition * newScope, const MemberDef * md) [inline]
Definition at line 388 of file memberdef.cpp.
    : DefinitionAliasMixin(newScope,md), m_memberGroup(0) { init(); }
References DefinitionAliasMixin< MemberDef >::init().
 MemberDefAliasImpl() [1/2]
virtual MemberDefAliasImpl::~MemberDefAliasImpl () [inline], [virtual]
Definition at line 390 of file memberdef.cpp.
{ deinit(); }
References DefinitionAliasMixin< MemberDef >::deinit().
MemberDefAliasImpl() [2/2]
MemberDefAliasImpl::MemberDefAliasImpl (const Definition * newScope, const MemberDef * md) [inline]
Definition at line 388 of file memberdef.cpp.
    : DefinitionAliasMixin(newScope,md), m_memberGroup(0) { init(); }
References DefinitionAliasMixin< MemberDef >::init().
 MemberDefAliasImpl() [2/2]
virtual MemberDefAliasImpl::~MemberDefAliasImpl () [inline], [virtual]
Definition at line 390 of file memberdef.cpp.
{ deinit(); }
References DefinitionAliasMixin< MemberDef >::deinit().
Member Function Documentation
accessorClass() [1/2]
virtual const ClassDef * MemberDefAliasImpl::accessorClass () const [inline], [virtual]
Implements MemberDef.
Definition at line 442 of file memberdef.cpp.
    { return getMdAlias()->accessorClass(); }
References MemberDef::accessorClass(), and getMdAlias().
accessorClass() [2/2]
virtual const ClassDef * MemberDefAliasImpl::accessorClass () const [inline], [virtual]
Implements MemberDef.
Definition at line 442 of file memberdef.cpp.
    { return getMdAlias()->accessorClass(); }
References MemberDef::accessorClass(), and getMdAlias().
anchor() [1/2]
virtual QCString MemberDefAliasImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements MemberDef.
Definition at line 410 of file memberdef.cpp.
    { return getMdAlias()->anchor(); }
References MemberDef::anchor(), and getMdAlias().
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString MemberDefAliasImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements MemberDef.
Definition at line 410 of file memberdef.cpp.
    { return getMdAlias()->anchor(); }
References MemberDef::anchor(), and getMdAlias().
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anonymousDeclShown() [1/2]
virtual bool MemberDefAliasImpl::anonymousDeclShown () const [inline], [virtual]
Implements MemberDef.
Definition at line 692 of file memberdef.cpp.
    { return getMdAlias()->anonymousDeclShown(); }
References MemberDef::anonymousDeclShown(), and getMdAlias().
anonymousDeclShown() [2/2]
virtual bool MemberDefAliasImpl::anonymousDeclShown () const [inline], [virtual]
Implements MemberDef.
Definition at line 692 of file memberdef.cpp.
    { return getMdAlias()->anonymousDeclShown(); }
References MemberDef::anonymousDeclShown(), and getMdAlias().
argsString() [1/2]
virtual QCString MemberDefAliasImpl::argsString () const [inline], [virtual]
Implements MemberDef.
Definition at line 418 of file memberdef.cpp.
    { return getMdAlias()->argsString(); }
References MemberDef::argsString(), and getMdAlias().
argsString() [2/2]
virtual QCString MemberDefAliasImpl::argsString () const [inline], [virtual]
Implements MemberDef.
Definition at line 418 of file memberdef.cpp.
    { return getMdAlias()->argsString(); }
References MemberDef::argsString(), and getMdAlias().
argumentList() [1/2]
virtual const ArgumentList & MemberDefAliasImpl::argumentList () const [inline], [virtual]
Implements MemberDef.
Definition at line 678 of file memberdef.cpp.
    { return getMdAlias()->argumentList(); }
References MemberDef::argumentList(), and getMdAlias().
argumentList() [2/2]
virtual const ArgumentList & MemberDefAliasImpl::argumentList () const [inline], [virtual]
Implements MemberDef.
Definition at line 678 of file memberdef.cpp.
    { return getMdAlias()->argumentList(); }
References MemberDef::argumentList(), and getMdAlias().
bitfieldString() [1/2]
virtual QCString MemberDefAliasImpl::bitfieldString () const [inline], [virtual]
Implements MemberDef.
Definition at line 422 of file memberdef.cpp.
    { return getMdAlias()->bitfieldString(); }
References MemberDef::bitfieldString(), and getMdAlias().
bitfieldString() [2/2]
virtual QCString MemberDefAliasImpl::bitfieldString () const [inline], [virtual]
Implements MemberDef.
Definition at line 422 of file memberdef.cpp.
    { return getMdAlias()->bitfieldString(); }
References MemberDef::bitfieldString(), and getMdAlias().
briefDescription() [1/2]
virtual QCString MemberDefAliasImpl::briefDescription (bool abbreviate = FALSE) const [inline], [virtual]
Returns the brief description of this definition. This can include commands.
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 740 of file memberdef.cpp.
    { return getMdAlias()->briefDescription(); }
References MemberDef::briefDescription(), and getMdAlias().
briefDescription() [2/2]
virtual QCString MemberDefAliasImpl::briefDescription (bool abbreviate = FALSE) const [inline], [virtual]
Returns the brief description of this definition. This can include commands.
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 740 of file memberdef.cpp.
    { return getMdAlias()->briefDescription(); }
References MemberDef::briefDescription(), and getMdAlias().
category() [1/2]
virtual ClassDef * MemberDefAliasImpl::category () const [inline], [virtual]
Implements MemberDef.
Definition at line 726 of file memberdef.cpp.
    { return getMdAlias()->category(); }
References MemberDef::category(), and getMdAlias().
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::getCategory(), doxmlparser.index.MixedContainer::getCategory(), doxmlparser.compound.MixedContainer::to_etree(), and doxmlparser.index.MixedContainer::to_etree().
category() [2/2]
virtual ClassDef * MemberDefAliasImpl::category () const [inline], [virtual]
Implements MemberDef.
Definition at line 726 of file memberdef.cpp.
    { return getMdAlias()->category(); }
References MemberDef::category(), and getMdAlias().
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::getCategory(), doxmlparser.index.MixedContainer::getCategory(), doxmlparser.compound.MixedContainer::to_etree(), and doxmlparser.index.MixedContainer::to_etree().
categoryRelation() [1/2]
virtual const MemberDef * MemberDefAliasImpl::categoryRelation () const [inline], [virtual]
Implements MemberDef.
Definition at line 728 of file memberdef.cpp.
    { return getMdAlias()->categoryRelation(); }
References MemberDef::categoryRelation(), and getMdAlias().
categoryRelation() [2/2]
virtual const MemberDef * MemberDefAliasImpl::categoryRelation () const [inline], [virtual]
Implements MemberDef.
Definition at line 728 of file memberdef.cpp.
    { return getMdAlias()->categoryRelation(); }
References MemberDef::categoryRelation(), and getMdAlias().
codeSymbolType() [1/2]
virtual CodeSymbolType MemberDefAliasImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 404 of file memberdef.cpp.
    { return getMdAlias()->codeSymbolType(); }
References Definition::codeSymbolType(), and getMdAlias().
codeSymbolType() [2/2]
virtual CodeSymbolType MemberDefAliasImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 404 of file memberdef.cpp.
    { return getMdAlias()->codeSymbolType(); }
References Definition::codeSymbolType(), and getMdAlias().
createTemplateInstanceMember() [1/2]
virtual MemberDefMutable * MemberDefAliasImpl::createTemplateInstanceMember (const ArgumentList & formalArgs, const std::unique_ptr< ArgumentList > & actualArgs) const [inline], [virtual]
Implements MemberDef.
Definition at line 761 of file memberdef.cpp.
    { return getMdAlias()->createTemplateInstanceMember(formalArgs,actualArgs); }
References MemberDef::createTemplateInstanceMember(), and getMdAlias().
createTemplateInstanceMember() [2/2]
virtual MemberDefMutable * MemberDefAliasImpl::createTemplateInstanceMember (const ArgumentList & formalArgs, const std::unique_ptr< ArgumentList > & actualArgs) const [inline], [virtual]
Implements MemberDef.
Definition at line 761 of file memberdef.cpp.
    { return getMdAlias()->createTemplateInstanceMember(formalArgs,actualArgs); }
References MemberDef::createTemplateInstanceMember(), and getMdAlias().
declaration() [1/2]
virtual QCString MemberDefAliasImpl::declaration () const [inline], [virtual]
Implements MemberDef.
Definition at line 412 of file memberdef.cpp.
    { return getMdAlias()->declaration(); }
References MemberDef::declaration(), and getMdAlias().
declaration() [2/2]
virtual QCString MemberDefAliasImpl::declaration () const [inline], [virtual]
Implements MemberDef.
Definition at line 412 of file memberdef.cpp.
    { return getMdAlias()->declaration(); }
References MemberDef::declaration(), and getMdAlias().
declArgumentList() [1/2]
virtual const ArgumentList & MemberDefAliasImpl::declArgumentList () const [inline], [virtual]
Implements MemberDef.
Definition at line 680 of file memberdef.cpp.
    { return getMdAlias()->declArgumentList(); }
References MemberDef::declArgumentList(), and getMdAlias().
declArgumentList() [2/2]
virtual const ArgumentList & MemberDefAliasImpl::declArgumentList () const [inline], [virtual]
Implements MemberDef.
Definition at line 680 of file memberdef.cpp.
    { return getMdAlias()->declArgumentList(); }
References MemberDef::declArgumentList(), and getMdAlias().
deepCopy() [1/2]
virtual MemberDef * MemberDefAliasImpl::deepCopy () const [inline], [virtual]
Implements MemberDef.
Definition at line 397 of file memberdef.cpp.
                                         {
      return createMemberDefAlias(getScope(),getMdAlias());
    }
References createMemberDefAlias(), getMdAlias(), and DefinitionAliasMixin< MemberDef >::getScope().
deepCopy() [2/2]
virtual MemberDef * MemberDefAliasImpl::deepCopy () const [inline], [virtual]
Implements MemberDef.
Definition at line 397 of file memberdef.cpp.
                                         {
      return createMemberDefAlias(getScope(),getMdAlias());
    }
References createMemberDefAlias(), getMdAlias(), and DefinitionAliasMixin< MemberDef >::getScope().
definition() [1/2]
virtual QCString MemberDefAliasImpl::definition () const [inline], [virtual]
Implements MemberDef.
Definition at line 414 of file memberdef.cpp.
    { return getMdAlias()->definition(); }
References MemberDef::definition(), and getMdAlias().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_definition(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_definition().
definition() [2/2]
virtual QCString MemberDefAliasImpl::definition () const [inline], [virtual]
Implements MemberDef.
Definition at line 414 of file memberdef.cpp.
    { return getMdAlias()->definition(); }
References MemberDef::definition(), and getMdAlias().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_definition(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_definition().
definitionTemplateParameterLists() [1/2]
virtual const ArgumentLists & MemberDefAliasImpl::definitionTemplateParameterLists () const [inline], [virtual]
Implements MemberDef.
Definition at line 684 of file memberdef.cpp.
    { return getMdAlias()->definitionTemplateParameterLists(); }
References MemberDef::definitionTemplateParameterLists(), and getMdAlias().
definitionTemplateParameterLists() [2/2]
virtual const ArgumentLists & MemberDefAliasImpl::definitionTemplateParameterLists () const [inline], [virtual]
Implements MemberDef.
Definition at line 684 of file memberdef.cpp.
    { return getMdAlias()->definitionTemplateParameterLists(); }
References MemberDef::definitionTemplateParameterLists(), and getMdAlias().
definitionType() [1/2]
virtual DefType MemberDefAliasImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements MemberDef.
Definition at line 391 of file memberdef.cpp.
{ return TypeMember; }
References Definition::TypeMember.
definitionType() [2/2]
virtual DefType MemberDefAliasImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements MemberDef.
Definition at line 391 of file memberdef.cpp.
{ return TypeMember; }
References Definition::TypeMember.
detectUndocumentedParams() [1/2]
virtual void MemberDefAliasImpl::detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const [inline], [virtual]
Implements MemberDef.
Definition at line 759 of file memberdef.cpp.
{}
detectUndocumentedParams() [2/2]
virtual void MemberDefAliasImpl::detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const [inline], [virtual]
Implements MemberDef.
Definition at line 759 of file memberdef.cpp.
{}
displayDefinition() [1/2]
virtual QCString MemberDefAliasImpl::displayDefinition () const [inline], [virtual]
Implements MemberDef.
Definition at line 434 of file memberdef.cpp.
    { return getMdAlias()->displayDefinition(); }
References MemberDef::displayDefinition(), and getMdAlias().
displayDefinition() [2/2]
virtual QCString MemberDefAliasImpl::displayDefinition () const [inline], [virtual]
Implements MemberDef.
Definition at line 434 of file memberdef.cpp.
    { return getMdAlias()->displayDefinition(); }
References MemberDef::displayDefinition(), and getMdAlias().
displayName() [1/2]
virtual QCString MemberDefAliasImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements MemberDef.
Definition at line 730 of file memberdef.cpp.
    { return getMdAlias()->displayName(b); }
References b, MemberDef::displayName(), and getMdAlias().
displayName() [2/2]
virtual QCString MemberDefAliasImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements MemberDef.
Definition at line 730 of file memberdef.cpp.
    { return getMdAlias()->displayName(b); }
References b, MemberDef::displayName(), and getMdAlias().
documentation() [1/2]
virtual QCString MemberDefAliasImpl::documentation () const [inline], [virtual]
Returns the detailed description of this definition
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 738 of file memberdef.cpp.
    { return getMdAlias()->documentation(); }
References MemberDef::documentation(), and getMdAlias().
documentation() [2/2]
virtual QCString MemberDefAliasImpl::documentation () const [inline], [virtual]
Returns the detailed description of this definition
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 738 of file memberdef.cpp.
    { return getMdAlias()->documentation(); }
References MemberDef::documentation(), and getMdAlias().
enumBaseType() [1/2]
virtual QCString MemberDefAliasImpl::enumBaseType () const [inline], [virtual]
Implements MemberDef.
Definition at line 670 of file memberdef.cpp.
    { return getMdAlias()->enumBaseType(); }
References MemberDef::enumBaseType(), and getMdAlias().
enumBaseType() [2/2]
virtual QCString MemberDefAliasImpl::enumBaseType () const [inline], [virtual]
Implements MemberDef.
Definition at line 670 of file memberdef.cpp.
    { return getMdAlias()->enumBaseType(); }
References MemberDef::enumBaseType(), and getMdAlias().
enumFieldList() [1/2]
virtual const MemberVector & MemberDefAliasImpl::enumFieldList () const [inline], [virtual]
Implements MemberDef.
Definition at line 668 of file memberdef.cpp.
    { return getMdAlias()->enumFieldList(); }
References MemberDef::enumFieldList(), and getMdAlias().
enumFieldList() [2/2]
virtual const MemberVector & MemberDefAliasImpl::enumFieldList () const [inline], [virtual]
Implements MemberDef.
Definition at line 668 of file memberdef.cpp.
    { return getMdAlias()->enumFieldList(); }
References MemberDef::enumFieldList(), and getMdAlias().
excpString() [1/2]
virtual QCString MemberDefAliasImpl::excpString () const [inline], [virtual]
Implements MemberDef.
Definition at line 420 of file memberdef.cpp.
    { return getMdAlias()->excpString(); }
References MemberDef::excpString(), and getMdAlias().
excpString() [2/2]
virtual QCString MemberDefAliasImpl::excpString () const [inline], [virtual]
Implements MemberDef.
Definition at line 420 of file memberdef.cpp.
    { return getMdAlias()->excpString(); }
References MemberDef::excpString(), and getMdAlias().
extraTypeChars() [1/2]
virtual QCString MemberDefAliasImpl::extraTypeChars () const [inline], [virtual]
Implements MemberDef.
Definition at line 424 of file memberdef.cpp.
    { return getMdAlias()->extraTypeChars(); }
References MemberDef::extraTypeChars(), and getMdAlias().
extraTypeChars() [2/2]
virtual QCString MemberDefAliasImpl::extraTypeChars () const [inline], [virtual]
Implements MemberDef.
Definition at line 424 of file memberdef.cpp.
    { return getMdAlias()->extraTypeChars(); }
References MemberDef::extraTypeChars(), and getMdAlias().
fieldType() [1/2]
virtual QCString MemberDefAliasImpl::fieldType () const [inline], [virtual]
Implements MemberDef.
Definition at line 742 of file memberdef.cpp.
    { return getMdAlias()->fieldType(); }
References MemberDef::fieldType(), and getMdAlias().
fieldType() [2/2]
virtual QCString MemberDefAliasImpl::fieldType () const [inline], [virtual]
Implements MemberDef.
Definition at line 742 of file memberdef.cpp.
    { return getMdAlias()->fieldType(); }
References MemberDef::fieldType(), and getMdAlias().
fromAnonymousMember() [1/2]
virtual MemberDef * MemberDefAliasImpl::fromAnonymousMember () const [inline], [virtual]
Implements MemberDef.
Definition at line 694 of file memberdef.cpp.
    { return getMdAlias()->fromAnonymousMember(); }
References MemberDef::fromAnonymousMember(), and getMdAlias().
fromAnonymousMember() [2/2]
virtual MemberDef * MemberDefAliasImpl::fromAnonymousMember () const [inline], [virtual]
Implements MemberDef.
Definition at line 694 of file memberdef.cpp.
    { return getMdAlias()->fromAnonymousMember(); }
References MemberDef::fromAnonymousMember(), and getMdAlias().
fromAnonymousScope() [1/2]
virtual bool MemberDefAliasImpl::fromAnonymousScope () const [inline], [virtual]
Implements MemberDef.
Definition at line 690 of file memberdef.cpp.
    { return getMdAlias()->fromAnonymousScope(); }
References MemberDef::fromAnonymousScope(), and getMdAlias().
fromAnonymousScope() [2/2]
virtual bool MemberDefAliasImpl::fromAnonymousScope () const [inline], [virtual]
Implements MemberDef.
Definition at line 690 of file memberdef.cpp.
    { return getMdAlias()->fromAnonymousScope(); }
References MemberDef::fromAnonymousScope(), and getMdAlias().
getAnonymousEnumType() [1/2]
virtual const MemberDef * MemberDefAliasImpl::getAnonymousEnumType () const [inline], [virtual]
Implements MemberDef.
Definition at line 662 of file memberdef.cpp.
    { return getMdAlias()->getAnonymousEnumType(); }
References MemberDef::getAnonymousEnumType(), and getMdAlias().
getAnonymousEnumType() [2/2]
virtual const MemberDef * MemberDefAliasImpl::getAnonymousEnumType () const [inline], [virtual]
Implements MemberDef.
Definition at line 662 of file memberdef.cpp.
    { return getMdAlias()->getAnonymousEnumType(); }
References MemberDef::getAnonymousEnumType(), and getMdAlias().
getCachedResolvedTypedef() [1/2]
virtual QCString MemberDefAliasImpl::getCachedResolvedTypedef () const [inline], [virtual]
Implements MemberDef.
Definition at line 716 of file memberdef.cpp.
    { return getMdAlias()->getCachedResolvedTypedef(); }
References MemberDef::getCachedResolvedTypedef(), and getMdAlias().
getCachedResolvedTypedef() [2/2]
virtual QCString MemberDefAliasImpl::getCachedResolvedTypedef () const [inline], [virtual]
Implements MemberDef.
Definition at line 716 of file memberdef.cpp.
    { return getMdAlias()->getCachedResolvedTypedef(); }
References MemberDef::getCachedResolvedTypedef(), and getMdAlias().
getCachedTypedefTemplSpec() [1/2]
virtual QCString MemberDefAliasImpl::getCachedTypedefTemplSpec () const [inline], [virtual]
Implements MemberDef.
Definition at line 714 of file memberdef.cpp.
    { return getMdAlias()->getCachedTypedefTemplSpec(); }
References MemberDef::getCachedTypedefTemplSpec(), and getMdAlias().
getCachedTypedefTemplSpec() [2/2]
virtual QCString MemberDefAliasImpl::getCachedTypedefTemplSpec () const [inline], [virtual]
Implements MemberDef.
Definition at line 714 of file memberdef.cpp.
    { return getMdAlias()->getCachedTypedefTemplSpec(); }
References MemberDef::getCachedTypedefTemplSpec(), and getMdAlias().
getCachedTypedefVal() [1/2]
virtual const ClassDef * MemberDefAliasImpl::getCachedTypedefVal () const [inline], [virtual]
Implements MemberDef.
Definition at line 712 of file memberdef.cpp.
    { return getMdAlias()->getCachedTypedefVal(); }
References MemberDef::getCachedTypedefVal(), and getMdAlias().
getCachedTypedefVal() [2/2]
virtual const ClassDef * MemberDefAliasImpl::getCachedTypedefVal () const [inline], [virtual]
Implements MemberDef.
Definition at line 712 of file memberdef.cpp.
    { return getMdAlias()->getCachedTypedefVal(); }
References MemberDef::getCachedTypedefVal(), and getMdAlias().
getClassDef() [1/2]
virtual const ClassDef * MemberDefAliasImpl::getClassDef () const [inline], [virtual]
Implements MemberDef.
Definition at line 436 of file memberdef.cpp.
    { return getMdAlias()->getClassDef(); }
References MemberDef::getClassDef(), and getMdAlias().
getClassDef() [2/2]
virtual const ClassDef * MemberDefAliasImpl::getClassDef () const [inline], [virtual]
Implements MemberDef.
Definition at line 436 of file memberdef.cpp.
    { return getMdAlias()->getClassDef(); }
References MemberDef::getClassDef(), and getMdAlias().
getClassDefOfAnonymousType() [1/2]
virtual ClassDef * MemberDefAliasImpl::getClassDefOfAnonymousType () const [inline], [virtual]
Implements MemberDef.
Definition at line 708 of file memberdef.cpp.
    { return getMdAlias()->getClassDefOfAnonymousType(); }
References MemberDef::getClassDefOfAnonymousType(), and getMdAlias().
getClassDefOfAnonymousType() [2/2]
virtual ClassDef * MemberDefAliasImpl::getClassDefOfAnonymousType () const [inline], [virtual]
Implements MemberDef.
Definition at line 708 of file memberdef.cpp.
    { return getMdAlias()->getClassDefOfAnonymousType(); }
References MemberDef::getClassDefOfAnonymousType(), and getMdAlias().
getDeclColumn() [1/2]
virtual int MemberDefAliasImpl::getDeclColumn () const [inline], [virtual]
Implements MemberDef.
Definition at line 750 of file memberdef.cpp.
    { return getMdAlias()->getDeclColumn(); }
References MemberDef::getDeclColumn(), and getMdAlias().
getDeclColumn() [2/2]
virtual int MemberDefAliasImpl::getDeclColumn () const [inline], [virtual]
Implements MemberDef.
Definition at line 750 of file memberdef.cpp.
    { return getMdAlias()->getDeclColumn(); }
References MemberDef::getDeclColumn(), and getMdAlias().
getDeclFileName() [1/2]
virtual QCString MemberDefAliasImpl::getDeclFileName () const [inline], [virtual]
Implements MemberDef.
Definition at line 746 of file memberdef.cpp.
    { return getMdAlias()->getDeclFileName(); }
References MemberDef::getDeclFileName(), and getMdAlias().
getDeclFileName() [2/2]
virtual QCString MemberDefAliasImpl::getDeclFileName () const [inline], [virtual]
Implements MemberDef.
Definition at line 746 of file memberdef.cpp.
    { return getMdAlias()->getDeclFileName(); }
References MemberDef::getDeclFileName(), and getMdAlias().
getDeclLine() [1/2]
virtual int MemberDefAliasImpl::getDeclLine () const [inline], [virtual]
Implements MemberDef.
Definition at line 748 of file memberdef.cpp.
    { return getMdAlias()->getDeclLine(); }
References MemberDef::getDeclLine(), and getMdAlias().
getDeclLine() [2/2]
virtual int MemberDefAliasImpl::getDeclLine () const [inline], [virtual]
Implements MemberDef.
Definition at line 748 of file memberdef.cpp.
    { return getMdAlias()->getDeclLine(); }
References MemberDef::getDeclLine(), and getMdAlias().
getDeclType() [1/2]
virtual QCString MemberDefAliasImpl::getDeclType () const [inline], [virtual]
Implements MemberDef.
Definition at line 732 of file memberdef.cpp.
    { return getMdAlias()->getDeclType(); }
References MemberDef::getDeclType(), and getMdAlias().
getDeclType() [2/2]
virtual QCString MemberDefAliasImpl::getDeclType () const [inline], [virtual]
Implements MemberDef.
Definition at line 732 of file memberdef.cpp.
    { return getMdAlias()->getDeclType(); }
References MemberDef::getDeclType(), and getMdAlias().
getEnumScope() [1/2]
virtual const MemberDef * MemberDefAliasImpl::getEnumScope () const [inline], [virtual]
Implements MemberDef.
Definition at line 666 of file memberdef.cpp.
    { return getMdAlias()->getEnumScope(); }
References MemberDef::getEnumScope(), and getMdAlias().
getEnumScope() [2/2]
virtual const MemberDef * MemberDefAliasImpl::getEnumScope () const [inline], [virtual]
Implements MemberDef.
Definition at line 666 of file memberdef.cpp.
    { return getMdAlias()->getEnumScope(); }
References MemberDef::getEnumScope(), and getMdAlias().
getExamples() [1/2]
virtual const ExampleList & MemberDefAliasImpl::getExamples () const [inline], [virtual]
Implements MemberDef.
Definition at line 674 of file memberdef.cpp.
    { return getMdAlias()->getExamples(); }
References MemberDef::getExamples(), and getMdAlias().
getExamples() [2/2]
virtual const ExampleList & MemberDefAliasImpl::getExamples () const [inline], [virtual]
Implements MemberDef.
Definition at line 674 of file memberdef.cpp.
    { return getMdAlias()->getExamples(); }
References MemberDef::getExamples(), and getMdAlias().
getFileDef() [1/2]
virtual const FileDef * MemberDefAliasImpl::getFileDef () const [inline], [virtual]
Implements MemberDef.
Definition at line 438 of file memberdef.cpp.
    { return getMdAlias()->getFileDef(); }
References MemberDef::getFileDef(), and getMdAlias().
getFileDef() [2/2]
virtual const FileDef * MemberDefAliasImpl::getFileDef () const [inline], [virtual]
Implements MemberDef.
Definition at line 438 of file memberdef.cpp.
    { return getMdAlias()->getFileDef(); }
References MemberDef::getFileDef(), and getMdAlias().
getGroupAlias() [1/2]
virtual const MemberDef * MemberDefAliasImpl::getGroupAlias () const [inline], [virtual]
Implements MemberDef.
Definition at line 724 of file memberdef.cpp.
    { return getMdAlias()->getGroupAlias(); }
References MemberDef::getGroupAlias(), and getMdAlias().
getGroupAlias() [2/2]
virtual const MemberDef * MemberDefAliasImpl::getGroupAlias () const [inline], [virtual]
Implements MemberDef.
Definition at line 724 of file memberdef.cpp.
    { return getMdAlias()->getGroupAlias(); }
References MemberDef::getGroupAlias(), and getMdAlias().
getGroupDef() [1/2]
virtual const GroupDef * MemberDefAliasImpl::getGroupDef () const [inline], [virtual]
Implements MemberDef.
Definition at line 448 of file memberdef.cpp.
    { return getMdAlias()->getGroupDef(); }
References MemberDef::getGroupDef(), and getMdAlias().
getGroupDef() [2/2]
virtual const GroupDef * MemberDefAliasImpl::getGroupDef () const [inline], [virtual]
Implements MemberDef.
Definition at line 448 of file memberdef.cpp.
    { return getMdAlias()->getGroupDef(); }
References MemberDef::getGroupDef(), and getMdAlias().
getGroupFileName() [1/2]
virtual QCString MemberDefAliasImpl::getGroupFileName () const [inline], [virtual]
Implements MemberDef.
Definition at line 452 of file memberdef.cpp.
    { return getMdAlias()->getGroupFileName(); }
References MemberDef::getGroupFileName(), and getMdAlias().
getGroupFileName() [2/2]
virtual QCString MemberDefAliasImpl::getGroupFileName () const [inline], [virtual]
Implements MemberDef.
Definition at line 452 of file memberdef.cpp.
    { return getMdAlias()->getGroupFileName(); }
References MemberDef::getGroupFileName(), and getMdAlias().
getGroupHasDocs() [1/2]
virtual bool MemberDefAliasImpl::getGroupHasDocs () const [inline], [virtual]
Implements MemberDef.
Definition at line 456 of file memberdef.cpp.
    { return getMdAlias()->getGroupHasDocs(); }
References MemberDef::getGroupHasDocs(), and getMdAlias().
getGroupHasDocs() [2/2]
virtual bool MemberDefAliasImpl::getGroupHasDocs () const [inline], [virtual]
Implements MemberDef.
Definition at line 456 of file memberdef.cpp.
    { return getMdAlias()->getGroupHasDocs(); }
References MemberDef::getGroupHasDocs(), and getMdAlias().
getGroupPri() [1/2]
virtual Grouping::GroupPri_t MemberDefAliasImpl::getGroupPri () const [inline], [virtual]
Implements MemberDef.
Definition at line 450 of file memberdef.cpp.
    { return getMdAlias()->getGroupPri(); }
References MemberDef::getGroupPri(), and getMdAlias().
getGroupPri() [2/2]
virtual Grouping::GroupPri_t MemberDefAliasImpl::getGroupPri () const [inline], [virtual]
Implements MemberDef.
Definition at line 450 of file memberdef.cpp.
    { return getMdAlias()->getGroupPri(); }
References MemberDef::getGroupPri(), and getMdAlias().
getGroupStartLine() [1/2]
virtual int MemberDefAliasImpl::getGroupStartLine () const [inline], [virtual]
Implements MemberDef.
Definition at line 454 of file memberdef.cpp.
    { return getMdAlias()->getGroupStartLine(); }
References MemberDef::getGroupStartLine(), and getMdAlias().
getGroupStartLine() [2/2]
virtual int MemberDefAliasImpl::getGroupStartLine () const [inline], [virtual]
Implements MemberDef.
Definition at line 454 of file memberdef.cpp.
    { return getMdAlias()->getGroupStartLine(); }
References MemberDef::getGroupStartLine(), and getMdAlias().
getLabels() [1/2]
virtual StringVector MemberDefAliasImpl::getLabels (const Definition * container) const [inline], [virtual]
Implements MemberDef.
Definition at line 734 of file memberdef.cpp.
    { return getMdAlias()->getLabels(container); }
References MemberDef::getLabels(), and getMdAlias().
getLabels() [2/2]
virtual StringVector MemberDefAliasImpl::getLabels (const Definition * container) const [inline], [virtual]
Implements MemberDef.
Definition at line 734 of file memberdef.cpp.
    { return getMdAlias()->getLabels(container); }
References MemberDef::getLabels(), and getMdAlias().
getMdAlias() [1/2]
const MemberDef * MemberDefAliasImpl::getMdAlias () const [inline]
Definition at line 393 of file memberdef.cpp.
{ return toMemberDef(getAlias()); }
References DefinitionAliasMixin< MemberDef >::getAlias(), and toMemberDef().
Referenced by accessorClass(), anchor(), anonymousDeclShown(), argsString(), argumentList(), bitfieldString(), briefDescription(), category(), categoryRelation(), codeSymbolType(), createTemplateInstanceMember(), declaration(), declArgumentList(), deepCopy(), definition(), definitionTemplateParameterLists(), displayDefinition(), displayName(), documentation(), enumBaseType(), enumFieldList(), excpString(), extraTypeChars(), fieldType(), fromAnonymousMember(), fromAnonymousScope(), getAnonymousEnumType(), getCachedResolvedTypedef(), getCachedTypedefTemplSpec(), getCachedTypedefVal(), getClassDef(), getClassDefOfAnonymousType(), getDeclColumn(), getDeclFileName(), getDeclLine(), getDeclType(), getEnumScope(), getExamples(), getFileDef(), getGroupAlias(), getGroupDef(), getGroupFileName(), getGroupHasDocs(), getGroupPri(), getGroupStartLine(), getLabels(), getMemberGroupId(), getMemberSpecifiers(), getNamespaceDef(), getOutputFileBase(), getReadAccessor(), getReference(), getScopeString(), getSectionList(), getWriteAccessor(), hasCallerGraph(), hasCallGraph(), hasDetailedDescription(), hasDocumentation(), hasDocumentedEnumValues(), hasExamples(), hasMultiLineInitializer(), hasOneLineInitializer(), hasReferencedByRelation(), hasReferencesRelation(), inheritsDocsFrom(), initializer(), initializerLines(), isAbstract(), isAddable(), isAssign(), isAttribute(), isBound(), isBriefSectionVisible(), isConstExpr(), isConstrained(), isConstructor(), isCopy(), isCSharpProperty(), isDCOP(), isDefault(), isDefine(), isDelete(), isDeleted(), isDestructor(), isDetailedSectionVisible(), isDictionary(), isDocsForDefinition(), isDocumentedFriendClass(), isEnumerate(), isEnumStruct(), isEnumValue(), isEvent(), isExplicit(), isExternal(), isFinal(), isForeign(), isFriend(), isFriendClass(), isFriendToHide(), isFunction(), isFunctionOrSignalSlot(), isFunctionPtr(), isGettable(), isImplementation(), isInitonly(), isInline(), isLinkable(), isLinkableInProject(), isMaybeAmbiguous(), isMaybeDefault(), isMaybeVoid(), isMutable(), isNew(), isNoExcept(), isNonAtomic(), isNotFriend(), isObjCMethod(), isObjCProperty(), isOptional(), isOverride(), isPrivateGettable(), isPrivateSettable(), isProperty(), isProtectedGettable(), isProtectedSettable(), isPrototype(), isPublished(), isRaisable(), isReadable(), isReadonly(), isReference(), isReimplementedBy(), isRelated(), isRelatedOrFriend(), isRemovable(), isRequired(), isRetain(), isSealed(), isSequence(), isSettable(), isSignal(), isSliceLocal(), isSlot(), isStatic(), isStrong(), isStrongEnumValue(), isTemplateSpecialization(), isTransient(), isTypeAlias(), isTypedef(), isTypedefValCached(), isUNOProperty(), isUnretained(), isVariable(), isWeak(), isWritable(), livesInsideEnum(), memberDeclaration(), memberDefinition(), memberType(), memberTypeName(), name(), numberOfFlowKeyWords(), objCMethodName(), protection(), qualifiedName(), reimplementedBy(), reimplements(), relatedAlso(), requiresClause(), resolveAlias(), showInCallGraph(), templateArguments(), templateMaster(), typeConstraints(), typeString(), virtualness(), visibleInIndex(), writeDeclaration(), and writeEnumDeclaration().
getMdAlias() [2/2]
const MemberDef * MemberDefAliasImpl::getMdAlias () const [inline]
Definition at line 393 of file memberdef.cpp.
{ return toMemberDef(getAlias()); }
References DefinitionAliasMixin< MemberDef >::getAlias(), and toMemberDef().
getMemberGroup() [1/2]
virtual MemberGroup * MemberDefAliasImpl::getMemberGroup () const [inline], [virtual]
Implements MemberDef.
Definition at line 688 of file memberdef.cpp.
    { return m_memberGroup; }
References m_memberGroup.
getMemberGroup() [2/2]
virtual MemberGroup * MemberDefAliasImpl::getMemberGroup () const [inline], [virtual]
Implements MemberDef.
Definition at line 688 of file memberdef.cpp.
    { return m_memberGroup; }
References m_memberGroup.
getMemberGroupId() [1/2]
virtual int MemberDefAliasImpl::getMemberGroupId () const [inline], [virtual]
Implements MemberDef.
Definition at line 686 of file memberdef.cpp.
    { return getMdAlias()->getMemberGroupId(); }
References getMdAlias(), and MemberDef::getMemberGroupId().
getMemberGroupId() [2/2]
virtual int MemberDefAliasImpl::getMemberGroupId () const [inline], [virtual]
Implements MemberDef.
Definition at line 686 of file memberdef.cpp.
    { return getMdAlias()->getMemberGroupId(); }
References getMdAlias(), and MemberDef::getMemberGroupId().
getMemberSpecifiers() [1/2]
virtual uint64 MemberDefAliasImpl::getMemberSpecifiers () const [inline], [virtual]
Implements MemberDef.
Definition at line 430 of file memberdef.cpp.
    { return getMdAlias()->getMemberSpecifiers(); }
References getMdAlias(), and MemberDef::getMemberSpecifiers().
getMemberSpecifiers() [2/2]
virtual uint64 MemberDefAliasImpl::getMemberSpecifiers () const [inline], [virtual]
Implements MemberDef.
Definition at line 430 of file memberdef.cpp.
    { return getMdAlias()->getMemberSpecifiers(); }
References getMdAlias(), and MemberDef::getMemberSpecifiers().
getNamespaceDef() [1/2]
virtual const NamespaceDef * MemberDefAliasImpl::getNamespaceDef () const [inline], [virtual]
Implements MemberDef.
Definition at line 440 of file memberdef.cpp.
    { return getMdAlias()->getNamespaceDef(); }
References getMdAlias(), and MemberDef::getNamespaceDef().
getNamespaceDef() [2/2]
virtual const NamespaceDef * MemberDefAliasImpl::getNamespaceDef () const [inline], [virtual]
Implements MemberDef.
Definition at line 440 of file memberdef.cpp.
    { return getMdAlias()->getNamespaceDef(); }
References getMdAlias(), and MemberDef::getNamespaceDef().
getOutputFileBase() [1/2]
virtual QCString MemberDefAliasImpl::getOutputFileBase () const [inline], [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements MemberDef.
Definition at line 406 of file memberdef.cpp.
    { return getMdAlias()->getOutputFileBase(); }
References getMdAlias(), and MemberDef::getOutputFileBase().
getOutputFileBase() [2/2]
virtual QCString MemberDefAliasImpl::getOutputFileBase () const [inline], [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements MemberDef.
Definition at line 406 of file memberdef.cpp.
    { return getMdAlias()->getOutputFileBase(); }
References getMdAlias(), and MemberDef::getOutputFileBase().
getReadAccessor() [1/2]
virtual QCString MemberDefAliasImpl::getReadAccessor () const [inline], [virtual]
Implements MemberDef.
Definition at line 444 of file memberdef.cpp.
    { return getMdAlias()->getReadAccessor(); }
References getMdAlias(), and MemberDef::getReadAccessor().
getReadAccessor() [2/2]
virtual QCString MemberDefAliasImpl::getReadAccessor () const [inline], [virtual]
Implements MemberDef.
Definition at line 444 of file memberdef.cpp.
    { return getMdAlias()->getReadAccessor(); }
References getMdAlias(), and MemberDef::getReadAccessor().
getReference() [1/2]
virtual QCString MemberDefAliasImpl::getReference () const [inline], [virtual]
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 408 of file memberdef.cpp.
    { return getMdAlias()->getReference(); }
References getMdAlias(), and MemberDef::getReference().
getReference() [2/2]
virtual QCString MemberDefAliasImpl::getReference () const [inline], [virtual]
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 408 of file memberdef.cpp.
    { return getMdAlias()->getReference(); }
References getMdAlias(), and MemberDef::getReference().
getScopeString() [1/2]
virtual QCString MemberDefAliasImpl::getScopeString () const [inline], [virtual]
Implements MemberDef.
Definition at line 706 of file memberdef.cpp.
    { return getMdAlias()->getScopeString(); }
References getMdAlias(), and MemberDef::getScopeString().
getScopeString() [2/2]
virtual QCString MemberDefAliasImpl::getScopeString () const [inline], [virtual]
Implements MemberDef.
Definition at line 706 of file memberdef.cpp.
    { return getMdAlias()->getScopeString(); }
References getMdAlias(), and MemberDef::getScopeString().
getSectionList() [1/2]
virtual const MemberList * MemberDefAliasImpl::getSectionList (const Definition * container) const [inline], [virtual]
Implements MemberDef.
Definition at line 432 of file memberdef.cpp.
    { return getMdAlias()->getSectionList(container); }
References getMdAlias(), and MemberDef::getSectionList().
getSectionList() [2/2]
virtual const MemberList * MemberDefAliasImpl::getSectionList (const Definition * container) const [inline], [virtual]
Implements MemberDef.
Definition at line 432 of file memberdef.cpp.
    { return getMdAlias()->getSectionList(container); }
References getMdAlias(), and MemberDef::getSectionList().
getWriteAccessor() [1/2]
virtual QCString MemberDefAliasImpl::getWriteAccessor () const [inline], [virtual]
Implements MemberDef.
Definition at line 446 of file memberdef.cpp.
    { return getMdAlias()->getWriteAccessor(); }
References getMdAlias(), and MemberDef::getWriteAccessor().
getWriteAccessor() [2/2]
virtual QCString MemberDefAliasImpl::getWriteAccessor () const [inline], [virtual]
Implements MemberDef.
Definition at line 446 of file memberdef.cpp.
    { return getMdAlias()->getWriteAccessor(); }
References getMdAlias(), and MemberDef::getWriteAccessor().
hasCallerGraph() [1/2]
virtual bool MemberDefAliasImpl::hasCallerGraph () const [inline], [virtual]
Implements MemberDef.
Definition at line 698 of file memberdef.cpp.
    { return getMdAlias()->hasCallerGraph(); }
References getMdAlias(), and MemberDef::hasCallerGraph().
hasCallerGraph() [2/2]
virtual bool MemberDefAliasImpl::hasCallerGraph () const [inline], [virtual]
Implements MemberDef.
Definition at line 698 of file memberdef.cpp.
    { return getMdAlias()->hasCallerGraph(); }
References getMdAlias(), and MemberDef::hasCallerGraph().
hasCallGraph() [1/2]
virtual bool MemberDefAliasImpl::hasCallGraph () const [inline], [virtual]
Implements MemberDef.
Definition at line 696 of file memberdef.cpp.
    { return getMdAlias()->hasCallGraph(); }
References getMdAlias(), and MemberDef::hasCallGraph().
hasCallGraph() [2/2]
virtual bool MemberDefAliasImpl::hasCallGraph () const [inline], [virtual]
Implements MemberDef.
Definition at line 696 of file memberdef.cpp.
    { return getMdAlias()->hasCallGraph(); }
References getMdAlias(), and MemberDef::hasCallGraph().
hasDetailedDescription() [1/2]
virtual bool MemberDefAliasImpl::hasDetailedDescription () const [inline], [virtual]
Implements MemberDef.
Definition at line 646 of file memberdef.cpp.
    { return getMdAlias()->hasDetailedDescription(); }
References getMdAlias(), and MemberDef::hasDetailedDescription().
hasDetailedDescription() [2/2]
virtual bool MemberDefAliasImpl::hasDetailedDescription () const [inline], [virtual]
Implements MemberDef.
Definition at line 646 of file memberdef.cpp.
    { return getMdAlias()->hasDetailedDescription(); }
References getMdAlias(), and MemberDef::hasDetailedDescription().
hasDocumentation() [1/2]
virtual bool MemberDefAliasImpl::hasDocumentation () const [inline], [virtual]
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 638 of file memberdef.cpp.
    { return getMdAlias()->hasDocumentation(); }
References getMdAlias(), and MemberDef::hasDocumentation().
hasDocumentation() [2/2]
virtual bool MemberDefAliasImpl::hasDocumentation () const [inline], [virtual]
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 638 of file memberdef.cpp.
    { return getMdAlias()->hasDocumentation(); }
References getMdAlias(), and MemberDef::hasDocumentation().
hasDocumentedEnumValues() [1/2]
virtual bool MemberDefAliasImpl::hasDocumentedEnumValues () const [inline], [virtual]
Implements MemberDef.
Definition at line 660 of file memberdef.cpp.
    { return getMdAlias()->hasDocumentedEnumValues(); }
References getMdAlias(), and MemberDef::hasDocumentedEnumValues().
hasDocumentedEnumValues() [2/2]
virtual bool MemberDefAliasImpl::hasDocumentedEnumValues () const [inline], [virtual]
Implements MemberDef.
Definition at line 660 of file memberdef.cpp.
    { return getMdAlias()->hasDocumentedEnumValues(); }
References getMdAlias(), and MemberDef::hasDocumentedEnumValues().
hasExamples() [1/2]
virtual bool MemberDefAliasImpl::hasExamples () const [inline], [virtual]
Implements MemberDef.
Definition at line 672 of file memberdef.cpp.
    { return getMdAlias()->hasExamples(); }
References getMdAlias(), and MemberDef::hasExamples().
hasExamples() [2/2]
virtual bool MemberDefAliasImpl::hasExamples () const [inline], [virtual]
Implements MemberDef.
Definition at line 672 of file memberdef.cpp.
    { return getMdAlias()->hasExamples(); }
References getMdAlias(), and MemberDef::hasExamples().
hasMultiLineInitializer() [1/2]
virtual bool MemberDefAliasImpl::hasMultiLineInitializer () const [inline], [virtual]
Implements MemberDef.
Definition at line 612 of file memberdef.cpp.
    { return getMdAlias()->hasMultiLineInitializer(); }
References getMdAlias(), and MemberDef::hasMultiLineInitializer().
hasMultiLineInitializer() [2/2]
virtual bool MemberDefAliasImpl::hasMultiLineInitializer () const [inline], [virtual]
Implements MemberDef.
Definition at line 612 of file memberdef.cpp.
    { return getMdAlias()->hasMultiLineInitializer(); }
References getMdAlias(), and MemberDef::hasMultiLineInitializer().
hasOneLineInitializer() [1/2]
virtual bool MemberDefAliasImpl::hasOneLineInitializer () const [inline], [virtual]
Implements MemberDef.
Definition at line 610 of file memberdef.cpp.
    { return getMdAlias()->hasOneLineInitializer(); }
References getMdAlias(), and MemberDef::hasOneLineInitializer().
hasOneLineInitializer() [2/2]
virtual bool MemberDefAliasImpl::hasOneLineInitializer () const [inline], [virtual]
Implements MemberDef.
Definition at line 610 of file memberdef.cpp.
    { return getMdAlias()->hasOneLineInitializer(); }
References getMdAlias(), and MemberDef::hasOneLineInitializer().
hasReferencedByRelation() [1/2]
virtual bool MemberDefAliasImpl::hasReferencedByRelation () const [inline], [virtual]
Implements MemberDef.
Definition at line 702 of file memberdef.cpp.
    { return getMdAlias()->hasReferencedByRelation(); }
References getMdAlias(), and MemberDef::hasReferencedByRelation().
hasReferencedByRelation() [2/2]
virtual bool MemberDefAliasImpl::hasReferencedByRelation () const [inline], [virtual]
Implements MemberDef.
Definition at line 702 of file memberdef.cpp.
    { return getMdAlias()->hasReferencedByRelation(); }
References getMdAlias(), and MemberDef::hasReferencedByRelation().
hasReferencesRelation() [1/2]
virtual bool MemberDefAliasImpl::hasReferencesRelation () const [inline], [virtual]
Implements MemberDef.
Definition at line 700 of file memberdef.cpp.
    { return getMdAlias()->hasReferencesRelation(); }
References getMdAlias(), and MemberDef::hasReferencesRelation().
hasReferencesRelation() [2/2]
virtual bool MemberDefAliasImpl::hasReferencesRelation () const [inline], [virtual]
Implements MemberDef.
Definition at line 700 of file memberdef.cpp.
    { return getMdAlias()->hasReferencesRelation(); }
References getMdAlias(), and MemberDef::hasReferencesRelation().
inheritsDocsFrom() [1/2]
virtual const MemberDef * MemberDefAliasImpl::inheritsDocsFrom () const [inline], [virtual]
Implements MemberDef.
Definition at line 722 of file memberdef.cpp.
    { return getMdAlias()->inheritsDocsFrom(); }
References getMdAlias(), and MemberDef::inheritsDocsFrom().
inheritsDocsFrom() [2/2]
virtual const MemberDef * MemberDefAliasImpl::inheritsDocsFrom () const [inline], [virtual]
Implements MemberDef.
Definition at line 722 of file memberdef.cpp.
    { return getMdAlias()->inheritsDocsFrom(); }
References getMdAlias(), and MemberDef::inheritsDocsFrom().
initializer() [1/2]
virtual const QCString & MemberDefAliasImpl::initializer () const [inline], [virtual]
Implements MemberDef.
Definition at line 426 of file memberdef.cpp.
    { return getMdAlias()->initializer(); }
References getMdAlias(), and MemberDef::initializer().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
initializer() [2/2]
virtual const QCString & MemberDefAliasImpl::initializer () const [inline], [virtual]
Implements MemberDef.
Definition at line 426 of file memberdef.cpp.
    { return getMdAlias()->initializer(); }
References getMdAlias(), and MemberDef::initializer().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
initializerLines() [1/2]
virtual int MemberDefAliasImpl::initializerLines () const [inline], [virtual]
Implements MemberDef.
Definition at line 428 of file memberdef.cpp.
    { return getMdAlias()->initializerLines(); }
References getMdAlias(), and MemberDef::initializerLines().
initializerLines() [2/2]
virtual int MemberDefAliasImpl::initializerLines () const [inline], [virtual]
Implements MemberDef.
Definition at line 428 of file memberdef.cpp.
    { return getMdAlias()->initializerLines(); }
References getMdAlias(), and MemberDef::initializerLines().
isAbstract() [1/2]
virtual bool MemberDefAliasImpl::isAbstract () const [inline], [virtual]
Implements MemberDef.
Definition at line 536 of file memberdef.cpp.
    { return getMdAlias()->isAbstract(); }
References getMdAlias(), and MemberDef::isAbstract().
isAbstract() [2/2]
virtual bool MemberDefAliasImpl::isAbstract () const [inline], [virtual]
Implements MemberDef.
Definition at line 536 of file memberdef.cpp.
    { return getMdAlias()->isAbstract(); }
References getMdAlias(), and MemberDef::isAbstract().
isAddable() [1/2]
virtual bool MemberDefAliasImpl::isAddable () const [inline], [virtual]
Implements MemberDef.
Definition at line 528 of file memberdef.cpp.
    { return getMdAlias()->isAddable(); }
References getMdAlias(), and MemberDef::isAddable().
isAddable() [2/2]
virtual bool MemberDefAliasImpl::isAddable () const [inline], [virtual]
Implements MemberDef.
Definition at line 528 of file memberdef.cpp.
    { return getMdAlias()->isAddable(); }
References getMdAlias(), and MemberDef::isAddable().
isAssign() [1/2]
virtual bool MemberDefAliasImpl::isAssign () const [inline], [virtual]
Implements MemberDef.
Definition at line 550 of file memberdef.cpp.
    { return getMdAlias()->isAssign(); }
References getMdAlias(), and MemberDef::isAssign().
isAssign() [2/2]
virtual bool MemberDefAliasImpl::isAssign () const [inline], [virtual]
Implements MemberDef.
Definition at line 550 of file memberdef.cpp.
    { return getMdAlias()->isAssign(); }
References getMdAlias(), and MemberDef::isAssign().
isAttribute() [1/2]
virtual bool MemberDefAliasImpl::isAttribute () const [inline], [virtual]
Implements MemberDef.
Definition at line 578 of file memberdef.cpp.
    { return getMdAlias()->isAttribute(); }
References getMdAlias(), and MemberDef::isAttribute().
isAttribute() [2/2]
virtual bool MemberDefAliasImpl::isAttribute () const [inline], [virtual]
Implements MemberDef.
Definition at line 578 of file memberdef.cpp.
    { return getMdAlias()->isAttribute(); }
References getMdAlias(), and MemberDef::isAttribute().
isBound() [1/2]
virtual bool MemberDefAliasImpl::isBound () const [inline], [virtual]
Implements MemberDef.
Definition at line 584 of file memberdef.cpp.
    { return getMdAlias()->isBound(); }
References getMdAlias(), and MemberDef::isBound().
isBound() [2/2]
virtual bool MemberDefAliasImpl::isBound () const [inline], [virtual]
Implements MemberDef.
Definition at line 584 of file memberdef.cpp.
    { return getMdAlias()->isBound(); }
References getMdAlias(), and MemberDef::isBound().
isBriefSectionVisible() [1/2]
virtual bool MemberDefAliasImpl::isBriefSectionVisible () const [inline], [virtual]
Implements MemberDef.
Definition at line 642 of file memberdef.cpp.
    { return getMdAlias()->isBriefSectionVisible(); }
References getMdAlias(), and MemberDef::isBriefSectionVisible().
isBriefSectionVisible() [2/2]
virtual bool MemberDefAliasImpl::isBriefSectionVisible () const [inline], [virtual]
Implements MemberDef.
Definition at line 642 of file memberdef.cpp.
    { return getMdAlias()->isBriefSectionVisible(); }
References getMdAlias(), and MemberDef::isBriefSectionVisible().
isConstExpr() [1/2]
virtual bool MemberDefAliasImpl::isConstExpr () const [inline], [virtual]
Implements MemberDef.
Definition at line 622 of file memberdef.cpp.
    { return getMdAlias()->isConstExpr(); }
References getMdAlias(), and MemberDef::isConstExpr().
isConstExpr() [2/2]
virtual bool MemberDefAliasImpl::isConstExpr () const [inline], [virtual]
Implements MemberDef.
Definition at line 622 of file memberdef.cpp.
    { return getMdAlias()->isConstExpr(); }
References getMdAlias(), and MemberDef::isConstExpr().
isConstrained() [1/2]
virtual bool MemberDefAliasImpl::isConstrained () const [inline], [virtual]
Implements MemberDef.
Definition at line 586 of file memberdef.cpp.
    { return getMdAlias()->isConstrained(); }
References getMdAlias(), and MemberDef::isConstrained().
isConstrained() [2/2]
virtual bool MemberDefAliasImpl::isConstrained () const [inline], [virtual]
Implements MemberDef.
Definition at line 586 of file memberdef.cpp.
    { return getMdAlias()->isConstrained(); }
References getMdAlias(), and MemberDef::isConstrained().
isConstructor() [1/2]
virtual bool MemberDefAliasImpl::isConstructor () const [inline], [virtual]
Implements MemberDef.
Definition at line 606 of file memberdef.cpp.
    { return getMdAlias()->isConstructor(); }
References getMdAlias(), and MemberDef::isConstructor().
isConstructor() [2/2]
virtual bool MemberDefAliasImpl::isConstructor () const [inline], [virtual]
Implements MemberDef.
Definition at line 606 of file memberdef.cpp.
    { return getMdAlias()->isConstructor(); }
References getMdAlias(), and MemberDef::isConstructor().
isCopy() [1/2]
virtual bool MemberDefAliasImpl::isCopy () const [inline], [virtual]
Implements MemberDef.
Definition at line 548 of file memberdef.cpp.
    { return getMdAlias()->isCopy(); }
References getMdAlias(), and MemberDef::isCopy().
isCopy() [2/2]
virtual bool MemberDefAliasImpl::isCopy () const [inline], [virtual]
Implements MemberDef.
Definition at line 548 of file memberdef.cpp.
    { return getMdAlias()->isCopy(); }
References getMdAlias(), and MemberDef::isCopy().
isCSharpProperty() [1/2]
virtual bool MemberDefAliasImpl::isCSharpProperty () const [inline], [virtual]
Implements MemberDef.
Definition at line 604 of file memberdef.cpp.
    { return getMdAlias()->isCSharpProperty(); }
References getMdAlias(), and MemberDef::isCSharpProperty().
isCSharpProperty() [2/2]
virtual bool MemberDefAliasImpl::isCSharpProperty () const [inline], [virtual]
Implements MemberDef.
Definition at line 604 of file memberdef.cpp.
    { return getMdAlias()->isCSharpProperty(); }
References getMdAlias(), and MemberDef::isCSharpProperty().
isDCOP() [1/2]
virtual bool MemberDefAliasImpl::isDCOP () const [inline], [virtual]
Implements MemberDef.
Definition at line 494 of file memberdef.cpp.
    { return getMdAlias()->isDCOP(); }
References getMdAlias(), and MemberDef::isDCOP().
isDCOP() [2/2]
virtual bool MemberDefAliasImpl::isDCOP () const [inline], [virtual]
Implements MemberDef.
Definition at line 494 of file memberdef.cpp.
    { return getMdAlias()->isDCOP(); }
References getMdAlias(), and MemberDef::isDCOP().
isDefault() [1/2]
virtual bool MemberDefAliasImpl::isDefault () const [inline], [virtual]
Implements MemberDef.
Definition at line 572 of file memberdef.cpp.
    { return getMdAlias()->isDefault(); }
References getMdAlias(), and MemberDef::isDefault().
isDefault() [2/2]
virtual bool MemberDefAliasImpl::isDefault () const [inline], [virtual]
Implements MemberDef.
Definition at line 572 of file memberdef.cpp.
    { return getMdAlias()->isDefault(); }
References getMdAlias(), and MemberDef::isDefault().
isDefine() [1/2]
virtual bool MemberDefAliasImpl::isDefine () const [inline], [virtual]
Implements MemberDef.
Definition at line 490 of file memberdef.cpp.
    { return getMdAlias()->isDefine(); }
References getMdAlias(), and MemberDef::isDefine().
isDefine() [2/2]
virtual bool MemberDefAliasImpl::isDefine () const [inline], [virtual]
Implements MemberDef.
Definition at line 490 of file memberdef.cpp.
    { return getMdAlias()->isDefine(); }
References getMdAlias(), and MemberDef::isDefine().
isDelete() [1/2]
virtual bool MemberDefAliasImpl::isDelete () const [inline], [virtual]
Implements MemberDef.
Definition at line 574 of file memberdef.cpp.
    { return getMdAlias()->isDelete(); }
References getMdAlias(), and MemberDef::isDelete().
isDelete() [2/2]
virtual bool MemberDefAliasImpl::isDelete () const [inline], [virtual]
Implements MemberDef.
Definition at line 574 of file memberdef.cpp.
    { return getMdAlias()->isDelete(); }
References getMdAlias(), and MemberDef::isDelete().
isDeleted() [1/2]
virtual bool MemberDefAliasImpl::isDeleted () const [inline], [virtual]
Implements MemberDef.
Definition at line 640 of file memberdef.cpp.
    { return getMdAlias()->isDeleted(); }
References getMdAlias(), and MemberDef::isDeleted().
isDeleted() [2/2]
virtual bool MemberDefAliasImpl::isDeleted () const [inline], [virtual]
Implements MemberDef.
Definition at line 640 of file memberdef.cpp.
    { return getMdAlias()->isDeleted(); }
References getMdAlias(), and MemberDef::isDeleted().
isDestructor() [1/2]
virtual bool MemberDefAliasImpl::isDestructor () const [inline], [virtual]
Implements MemberDef.
Definition at line 608 of file memberdef.cpp.
    { return getMdAlias()->isDestructor(); }
References getMdAlias(), and MemberDef::isDestructor().
isDestructor() [2/2]
virtual bool MemberDefAliasImpl::isDestructor () const [inline], [virtual]
Implements MemberDef.
Definition at line 608 of file memberdef.cpp.
    { return getMdAlias()->isDestructor(); }
References getMdAlias(), and MemberDef::isDestructor().
isDetailedSectionVisible() [1/2]
virtual bool MemberDefAliasImpl::isDetailedSectionVisible (MemberListContainer container) const [inline], [virtual]
Implements MemberDef.
Definition at line 644 of file memberdef.cpp.
    { return getMdAlias()->isDetailedSectionVisible(container); }
References getMdAlias(), and MemberDef::isDetailedSectionVisible().
isDetailedSectionVisible() [2/2]
virtual bool MemberDefAliasImpl::isDetailedSectionVisible (MemberListContainer container) const [inline], [virtual]
Implements MemberDef.
Definition at line 644 of file memberdef.cpp.
    { return getMdAlias()->isDetailedSectionVisible(container); }
References getMdAlias(), and MemberDef::isDetailedSectionVisible().
isDictionary() [1/2]
virtual bool MemberDefAliasImpl::isDictionary () const [inline], [virtual]
Implements MemberDef.
Definition at line 484 of file memberdef.cpp.
    { return getMdAlias()->isDictionary(); }
References getMdAlias(), and MemberDef::isDictionary().
isDictionary() [2/2]
virtual bool MemberDefAliasImpl::isDictionary () const [inline], [virtual]
Implements MemberDef.
Definition at line 484 of file memberdef.cpp.
    { return getMdAlias()->isDictionary(); }
References getMdAlias(), and MemberDef::isDictionary().
isDocsForDefinition() [1/2]
virtual bool MemberDefAliasImpl::isDocsForDefinition () const [inline], [virtual]
Implements MemberDef.
Definition at line 664 of file memberdef.cpp.
    { return getMdAlias()->isDocsForDefinition(); }
References getMdAlias(), and MemberDef::isDocsForDefinition().
isDocsForDefinition() [2/2]
virtual bool MemberDefAliasImpl::isDocsForDefinition () const [inline], [virtual]
Implements MemberDef.
Definition at line 664 of file memberdef.cpp.
    { return getMdAlias()->isDocsForDefinition(); }
References getMdAlias(), and MemberDef::isDocsForDefinition().
isDocumentedFriendClass() [1/2]
virtual bool MemberDefAliasImpl::isDocumentedFriendClass () const [inline], [virtual]
Implements MemberDef.
Definition at line 650 of file memberdef.cpp.
    { return getMdAlias()->isDocumentedFriendClass(); }
References getMdAlias(), and MemberDef::isDocumentedFriendClass().
isDocumentedFriendClass() [2/2]
virtual bool MemberDefAliasImpl::isDocumentedFriendClass () const [inline], [virtual]
Implements MemberDef.
Definition at line 650 of file memberdef.cpp.
    { return getMdAlias()->isDocumentedFriendClass(); }
References getMdAlias(), and MemberDef::isDocumentedFriendClass().
isEnumerate() [1/2]
virtual bool MemberDefAliasImpl::isEnumerate () const [inline], [virtual]
Implements MemberDef.
Definition at line 476 of file memberdef.cpp.
    { return getMdAlias()->isEnumerate(); }
References getMdAlias(), and MemberDef::isEnumerate().
isEnumerate() [2/2]
virtual bool MemberDefAliasImpl::isEnumerate () const [inline], [virtual]
Implements MemberDef.
Definition at line 476 of file memberdef.cpp.
    { return getMdAlias()->isEnumerate(); }
References getMdAlias(), and MemberDef::isEnumerate().
isEnumStruct() [1/2]
virtual bool MemberDefAliasImpl::isEnumStruct () const [inline], [virtual]
Implements MemberDef.
Definition at line 558 of file memberdef.cpp.
    { return getMdAlias()->isEnumStruct(); }
References getMdAlias(), and MemberDef::isEnumStruct().
isEnumStruct() [2/2]
virtual bool MemberDefAliasImpl::isEnumStruct () const [inline], [virtual]
Implements MemberDef.
Definition at line 558 of file memberdef.cpp.
    { return getMdAlias()->isEnumStruct(); }
References getMdAlias(), and MemberDef::isEnumStruct().
isEnumValue() [1/2]
virtual bool MemberDefAliasImpl::isEnumValue () const [inline], [virtual]
Implements MemberDef.
Definition at line 478 of file memberdef.cpp.
    { return getMdAlias()->isEnumValue(); }
References getMdAlias(), and MemberDef::isEnumValue().
isEnumValue() [2/2]
virtual bool MemberDefAliasImpl::isEnumValue () const [inline], [virtual]
Implements MemberDef.
Definition at line 478 of file memberdef.cpp.
    { return getMdAlias()->isEnumValue(); }
References getMdAlias(), and MemberDef::isEnumValue().
isEvent() [1/2]
virtual bool MemberDefAliasImpl::isEvent () const [inline], [virtual]
Implements MemberDef.
Definition at line 498 of file memberdef.cpp.
    { return getMdAlias()->isEvent(); }
References getMdAlias(), and MemberDef::isEvent().
isEvent() [2/2]
virtual bool MemberDefAliasImpl::isEvent () const [inline], [virtual]
Implements MemberDef.
Definition at line 498 of file memberdef.cpp.
    { return getMdAlias()->isEvent(); }
References getMdAlias(), and MemberDef::isEvent().
isExplicit() [1/2]
virtual bool MemberDefAliasImpl::isExplicit () const [inline], [virtual]
Implements MemberDef.
Definition at line 508 of file memberdef.cpp.
    { return getMdAlias()->isExplicit(); }
References getMdAlias(), and MemberDef::isExplicit().
isExplicit() [2/2]
virtual bool MemberDefAliasImpl::isExplicit () const [inline], [virtual]
Implements MemberDef.
Definition at line 508 of file memberdef.cpp.
    { return getMdAlias()->isExplicit(); }
References getMdAlias(), and MemberDef::isExplicit().
isExternal() [1/2]
virtual bool MemberDefAliasImpl::isExternal () const [inline], [virtual]
Implements MemberDef.
Definition at line 568 of file memberdef.cpp.
    { return getMdAlias()->isExternal(); }
References getMdAlias(), and MemberDef::isExternal().
isExternal() [2/2]
virtual bool MemberDefAliasImpl::isExternal () const [inline], [virtual]
Implements MemberDef.
Definition at line 568 of file memberdef.cpp.
    { return getMdAlias()->isExternal(); }
References getMdAlias(), and MemberDef::isExternal().
isFinal() [1/2]
virtual bool MemberDefAliasImpl::isFinal () const [inline], [virtual]
Implements MemberDef.
Definition at line 534 of file memberdef.cpp.
    { return getMdAlias()->isFinal(); }
References getMdAlias(), and MemberDef::isFinal().
isFinal() [2/2]
virtual bool MemberDefAliasImpl::isFinal () const [inline], [virtual]
Implements MemberDef.
Definition at line 534 of file memberdef.cpp.
    { return getMdAlias()->isFinal(); }
References getMdAlias(), and MemberDef::isFinal().
isForeign() [1/2]
virtual bool MemberDefAliasImpl::isForeign () const [inline], [virtual]
Implements MemberDef.
Definition at line 502 of file memberdef.cpp.
    { return getMdAlias()->isForeign(); }
References getMdAlias(), and MemberDef::isForeign().
isForeign() [2/2]
virtual bool MemberDefAliasImpl::isForeign () const [inline], [virtual]
Implements MemberDef.
Definition at line 502 of file memberdef.cpp.
    { return getMdAlias()->isForeign(); }
References getMdAlias(), and MemberDef::isForeign().
isFriend() [1/2]
virtual bool MemberDefAliasImpl::isFriend () const [inline], [virtual]
Implements MemberDef.
Definition at line 492 of file memberdef.cpp.
    { return getMdAlias()->isFriend(); }
References getMdAlias(), and MemberDef::isFriend().
isFriend() [2/2]
virtual bool MemberDefAliasImpl::isFriend () const [inline], [virtual]
Implements MemberDef.
Definition at line 492 of file memberdef.cpp.
    { return getMdAlias()->isFriend(); }
References getMdAlias(), and MemberDef::isFriend().
isFriendClass() [1/2]
virtual bool MemberDefAliasImpl::isFriendClass () const [inline], [virtual]
Implements MemberDef.
Definition at line 648 of file memberdef.cpp.
    { return getMdAlias()->isFriendClass(); }
References getMdAlias(), and MemberDef::isFriendClass().
isFriendClass() [2/2]
virtual bool MemberDefAliasImpl::isFriendClass () const [inline], [virtual]
Implements MemberDef.
Definition at line 648 of file memberdef.cpp.
    { return getMdAlias()->isFriendClass(); }
References getMdAlias(), and MemberDef::isFriendClass().
isFriendToHide() [1/2]
virtual bool MemberDefAliasImpl::isFriendToHide () const [inline], [virtual]
Implements MemberDef.
Definition at line 626 of file memberdef.cpp.
    { return getMdAlias()->isFriendToHide(); }
References getMdAlias(), and MemberDef::isFriendToHide().
isFriendToHide() [2/2]
virtual bool MemberDefAliasImpl::isFriendToHide () const [inline], [virtual]
Implements MemberDef.
Definition at line 626 of file memberdef.cpp.
    { return getMdAlias()->isFriendToHide(); }
References getMdAlias(), and MemberDef::isFriendToHide().
isFunction() [1/2]
virtual bool MemberDefAliasImpl::isFunction () const [inline], [virtual]
Implements MemberDef.
Definition at line 486 of file memberdef.cpp.
    { return getMdAlias()->isFunction(); }
References getMdAlias(), and MemberDef::isFunction().
isFunction() [2/2]
virtual bool MemberDefAliasImpl::isFunction () const [inline], [virtual]
Implements MemberDef.
Definition at line 486 of file memberdef.cpp.
    { return getMdAlias()->isFunction(); }
References getMdAlias(), and MemberDef::isFunction().
isFunctionOrSignalSlot() [1/2]
virtual bool MemberDefAliasImpl::isFunctionOrSignalSlot () const [inline], [virtual]
Implements MemberDef.
Definition at line 630 of file memberdef.cpp.
    { return getMdAlias()->isFunctionOrSignalSlot(); }
References getMdAlias(), and MemberDef::isFunctionOrSignalSlot().
isFunctionOrSignalSlot() [2/2]
virtual bool MemberDefAliasImpl::isFunctionOrSignalSlot () const [inline], [virtual]
Implements MemberDef.
Definition at line 630 of file memberdef.cpp.
    { return getMdAlias()->isFunctionOrSignalSlot(); }
References getMdAlias(), and MemberDef::isFunctionOrSignalSlot().
isFunctionPtr() [1/2]
virtual bool MemberDefAliasImpl::isFunctionPtr () const [inline], [virtual]
Implements MemberDef.
Definition at line 488 of file memberdef.cpp.
    { return getMdAlias()->isFunctionPtr(); }
References getMdAlias(), and MemberDef::isFunctionPtr().
isFunctionPtr() [2/2]
virtual bool MemberDefAliasImpl::isFunctionPtr () const [inline], [virtual]
Implements MemberDef.
Definition at line 488 of file memberdef.cpp.
    { return getMdAlias()->isFunctionPtr(); }
References getMdAlias(), and MemberDef::isFunctionPtr().
isGettable() [1/2]
virtual bool MemberDefAliasImpl::isGettable () const [inline], [virtual]
Implements MemberDef.
Definition at line 512 of file memberdef.cpp.
    { return getMdAlias()->isGettable(); }
References getMdAlias(), and MemberDef::isGettable().
isGettable() [2/2]
virtual bool MemberDefAliasImpl::isGettable () const [inline], [virtual]
Implements MemberDef.
Definition at line 512 of file memberdef.cpp.
    { return getMdAlias()->isGettable(); }
References getMdAlias(), and MemberDef::isGettable().
isImplementation() [1/2]
virtual bool MemberDefAliasImpl::isImplementation () const [inline], [virtual]
Implements MemberDef.
Definition at line 566 of file memberdef.cpp.
    { return getMdAlias()->isImplementation(); }
References getMdAlias(), and MemberDef::isImplementation().
isImplementation() [2/2]
virtual bool MemberDefAliasImpl::isImplementation () const [inline], [virtual]
Implements MemberDef.
Definition at line 566 of file memberdef.cpp.
    { return getMdAlias()->isImplementation(); }
References getMdAlias(), and MemberDef::isImplementation().
isInitonly() [1/2]
virtual bool MemberDefAliasImpl::isInitonly () const [inline], [virtual]
Implements MemberDef.
Definition at line 540 of file memberdef.cpp.
    { return getMdAlias()->isInitonly(); }
References getMdAlias(), and MemberDef::isInitonly().
isInitonly() [2/2]
virtual bool MemberDefAliasImpl::isInitonly () const [inline], [virtual]
Implements MemberDef.
Definition at line 540 of file memberdef.cpp.
    { return getMdAlias()->isInitonly(); }
References getMdAlias(), and MemberDef::isInitonly().
isInline() [1/2]
virtual bool MemberDefAliasImpl::isInline () const [inline], [virtual]
Implements MemberDef.
Definition at line 506 of file memberdef.cpp.
    { return getMdAlias()->isInline(); }
References getMdAlias(), and MemberDef::isInline().
isInline() [2/2]
virtual bool MemberDefAliasImpl::isInline () const [inline], [virtual]
Implements MemberDef.
Definition at line 506 of file memberdef.cpp.
    { return getMdAlias()->isInline(); }
References getMdAlias(), and MemberDef::isInline().
isLinkable() [1/2]
virtual bool MemberDefAliasImpl::isLinkable () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements MemberDef.
Definition at line 636 of file memberdef.cpp.
    { return getMdAlias()->isLinkable(); }
References getMdAlias(), and MemberDef::isLinkable().
isLinkable() [2/2]
virtual bool MemberDefAliasImpl::isLinkable () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements MemberDef.
Definition at line 636 of file memberdef.cpp.
    { return getMdAlias()->isLinkable(); }
References getMdAlias(), and MemberDef::isLinkable().
isLinkableInProject() [1/2]
virtual bool MemberDefAliasImpl::isLinkableInProject () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements MemberDef.
Definition at line 634 of file memberdef.cpp.
    { return getMdAlias()->isLinkableInProject(); }
References getMdAlias(), and MemberDef::isLinkableInProject().
isLinkableInProject() [2/2]
virtual bool MemberDefAliasImpl::isLinkableInProject () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements MemberDef.
Definition at line 634 of file memberdef.cpp.
    { return getMdAlias()->isLinkableInProject(); }
References getMdAlias(), and MemberDef::isLinkableInProject().
isMaybeAmbiguous() [1/2]
virtual bool MemberDefAliasImpl::isMaybeAmbiguous () const [inline], [virtual]
Implements MemberDef.
Definition at line 594 of file memberdef.cpp.
    { return getMdAlias()->isMaybeAmbiguous(); }
References getMdAlias(), and MemberDef::isMaybeAmbiguous().
isMaybeAmbiguous() [2/2]
virtual bool MemberDefAliasImpl::isMaybeAmbiguous () const [inline], [virtual]
Implements MemberDef.
Definition at line 594 of file memberdef.cpp.
    { return getMdAlias()->isMaybeAmbiguous(); }
References getMdAlias(), and MemberDef::isMaybeAmbiguous().
isMaybeDefault() [1/2]
virtual bool MemberDefAliasImpl::isMaybeDefault () const [inline], [virtual]
Implements MemberDef.
Definition at line 592 of file memberdef.cpp.
    { return getMdAlias()->isMaybeDefault(); }
References getMdAlias(), and MemberDef::isMaybeDefault().
isMaybeDefault() [2/2]
virtual bool MemberDefAliasImpl::isMaybeDefault () const [inline], [virtual]
Implements MemberDef.
Definition at line 592 of file memberdef.cpp.
    { return getMdAlias()->isMaybeDefault(); }
References getMdAlias(), and MemberDef::isMaybeDefault().
isMaybeVoid() [1/2]
virtual bool MemberDefAliasImpl::isMaybeVoid () const [inline], [virtual]
Implements MemberDef.
Definition at line 590 of file memberdef.cpp.
    { return getMdAlias()->isMaybeVoid(); }
References getMdAlias(), and MemberDef::isMaybeVoid().
isMaybeVoid() [2/2]
virtual bool MemberDefAliasImpl::isMaybeVoid () const [inline], [virtual]
Implements MemberDef.
Definition at line 590 of file memberdef.cpp.
    { return getMdAlias()->isMaybeVoid(); }
References getMdAlias(), and MemberDef::isMaybeVoid().
isMutable() [1/2]
virtual bool MemberDefAliasImpl::isMutable () const [inline], [virtual]
Implements MemberDef.
Definition at line 510 of file memberdef.cpp.
    { return getMdAlias()->isMutable(); }
References getMdAlias(), and MemberDef::isMutable().
isMutable() [2/2]
virtual bool MemberDefAliasImpl::isMutable () const [inline], [virtual]
Implements MemberDef.
Definition at line 510 of file memberdef.cpp.
    { return getMdAlias()->isMutable(); }
References getMdAlias(), and MemberDef::isMutable().
isNew() [1/2]
virtual bool MemberDefAliasImpl::isNew () const [inline], [virtual]
Implements MemberDef.
Definition at line 562 of file memberdef.cpp.
    { return getMdAlias()->isNew(); }
References getMdAlias(), and MemberDef::isNew().
isNew() [2/2]
virtual bool MemberDefAliasImpl::isNew () const [inline], [virtual]
Implements MemberDef.
Definition at line 562 of file memberdef.cpp.
    { return getMdAlias()->isNew(); }
References getMdAlias(), and MemberDef::isNew().
isNoExcept() [1/2]
virtual bool MemberDefAliasImpl::isNoExcept () const [inline], [virtual]
Implements MemberDef.
Definition at line 576 of file memberdef.cpp.
    { return getMdAlias()->isNoExcept(); }
References getMdAlias(), and MemberDef::isNoExcept().
isNoExcept() [2/2]
virtual bool MemberDefAliasImpl::isNoExcept () const [inline], [virtual]
Implements MemberDef.
Definition at line 576 of file memberdef.cpp.
    { return getMdAlias()->isNoExcept(); }
References getMdAlias(), and MemberDef::isNoExcept().
isNonAtomic() [1/2]
virtual bool MemberDefAliasImpl::isNonAtomic () const [inline], [virtual]
Implements MemberDef.
Definition at line 546 of file memberdef.cpp.
    { return getMdAlias()->isNonAtomic(); }
References getMdAlias(), and MemberDef::isNonAtomic().
isNonAtomic() [2/2]
virtual bool MemberDefAliasImpl::isNonAtomic () const [inline], [virtual]
Implements MemberDef.
Definition at line 546 of file memberdef.cpp.
    { return getMdAlias()->isNonAtomic(); }
References getMdAlias(), and MemberDef::isNonAtomic().
isNotFriend() [1/2]
virtual bool MemberDefAliasImpl::isNotFriend () const [inline], [virtual]
Implements MemberDef.
Definition at line 628 of file memberdef.cpp.
    { return getMdAlias()->isNotFriend(); }
References getMdAlias(), and MemberDef::isNotFriend().
isNotFriend() [2/2]
virtual bool MemberDefAliasImpl::isNotFriend () const [inline], [virtual]
Implements MemberDef.
Definition at line 628 of file memberdef.cpp.
    { return getMdAlias()->isNotFriend(); }
References getMdAlias(), and MemberDef::isNotFriend().
isObjCMethod() [1/2]
virtual bool MemberDefAliasImpl::isObjCMethod () const [inline], [virtual]
Implements MemberDef.
Definition at line 600 of file memberdef.cpp.
    { return getMdAlias()->isObjCMethod(); }
References getMdAlias(), and MemberDef::isObjCMethod().
isObjCMethod() [2/2]
virtual bool MemberDefAliasImpl::isObjCMethod () const [inline], [virtual]
Implements MemberDef.
Definition at line 600 of file memberdef.cpp.
    { return getMdAlias()->isObjCMethod(); }
References getMdAlias(), and MemberDef::isObjCMethod().
isObjCProperty() [1/2]
virtual bool MemberDefAliasImpl::isObjCProperty () const [inline], [virtual]
Implements MemberDef.
Definition at line 602 of file memberdef.cpp.
    { return getMdAlias()->isObjCProperty(); }
References getMdAlias(), and MemberDef::isObjCProperty().
isObjCProperty() [2/2]
virtual bool MemberDefAliasImpl::isObjCProperty () const [inline], [virtual]
Implements MemberDef.
Definition at line 602 of file memberdef.cpp.
    { return getMdAlias()->isObjCProperty(); }
References getMdAlias(), and MemberDef::isObjCProperty().
isOptional() [1/2]
virtual bool MemberDefAliasImpl::isOptional () const [inline], [virtual]
Implements MemberDef.
Definition at line 542 of file memberdef.cpp.
    { return getMdAlias()->isOptional(); }
References getMdAlias(), and MemberDef::isOptional().
isOptional() [2/2]
virtual bool MemberDefAliasImpl::isOptional () const [inline], [virtual]
Implements MemberDef.
Definition at line 542 of file memberdef.cpp.
    { return getMdAlias()->isOptional(); }
References getMdAlias(), and MemberDef::isOptional().
isOverride() [1/2]
virtual bool MemberDefAliasImpl::isOverride () const [inline], [virtual]
Implements MemberDef.
Definition at line 538 of file memberdef.cpp.
    { return getMdAlias()->isOverride(); }
References getMdAlias(), and MemberDef::isOverride().
isOverride() [2/2]
virtual bool MemberDefAliasImpl::isOverride () const [inline], [virtual]
Implements MemberDef.
Definition at line 538 of file memberdef.cpp.
    { return getMdAlias()->isOverride(); }
References getMdAlias(), and MemberDef::isOverride().
isPrivateGettable() [1/2]
virtual bool MemberDefAliasImpl::isPrivateGettable () const [inline], [virtual]
Implements MemberDef.
Definition at line 514 of file memberdef.cpp.
    { return getMdAlias()->isPrivateGettable(); }
References getMdAlias(), and MemberDef::isPrivateGettable().
isPrivateGettable() [2/2]
virtual bool MemberDefAliasImpl::isPrivateGettable () const [inline], [virtual]
Implements MemberDef.
Definition at line 514 of file memberdef.cpp.
    { return getMdAlias()->isPrivateGettable(); }
References getMdAlias(), and MemberDef::isPrivateGettable().
isPrivateSettable() [1/2]
virtual bool MemberDefAliasImpl::isPrivateSettable () const [inline], [virtual]
Implements MemberDef.
Definition at line 520 of file memberdef.cpp.
    { return getMdAlias()->isPrivateSettable(); }
References getMdAlias(), and MemberDef::isPrivateSettable().
isPrivateSettable() [2/2]
virtual bool MemberDefAliasImpl::isPrivateSettable () const [inline], [virtual]
Implements MemberDef.
Definition at line 520 of file memberdef.cpp.
    { return getMdAlias()->isPrivateSettable(); }
References getMdAlias(), and MemberDef::isPrivateSettable().
isProperty() [1/2]
virtual bool MemberDefAliasImpl::isProperty () const [inline], [virtual]
Implements MemberDef.
Definition at line 496 of file memberdef.cpp.
    { return getMdAlias()->isProperty(); }
References getMdAlias(), and MemberDef::isProperty().
isProperty() [2/2]
virtual bool MemberDefAliasImpl::isProperty () const [inline], [virtual]
Implements MemberDef.
Definition at line 496 of file memberdef.cpp.
    { return getMdAlias()->isProperty(); }
References getMdAlias(), and MemberDef::isProperty().
isProtectedGettable() [1/2]
virtual bool MemberDefAliasImpl::isProtectedGettable () const [inline], [virtual]
Implements MemberDef.
Definition at line 516 of file memberdef.cpp.
    { return getMdAlias()->isProtectedGettable(); }
References getMdAlias(), and MemberDef::isProtectedGettable().
isProtectedGettable() [2/2]
virtual bool MemberDefAliasImpl::isProtectedGettable () const [inline], [virtual]
Implements MemberDef.
Definition at line 516 of file memberdef.cpp.
    { return getMdAlias()->isProtectedGettable(); }
References getMdAlias(), and MemberDef::isProtectedGettable().
isProtectedSettable() [1/2]
virtual bool MemberDefAliasImpl::isProtectedSettable () const [inline], [virtual]
Implements MemberDef.
Definition at line 522 of file memberdef.cpp.
    { return getMdAlias()->isProtectedSettable(); }
References getMdAlias(), and MemberDef::isProtectedSettable().
isProtectedSettable() [2/2]
virtual bool MemberDefAliasImpl::isProtectedSettable () const [inline], [virtual]
Implements MemberDef.
Definition at line 522 of file memberdef.cpp.
    { return getMdAlias()->isProtectedSettable(); }
References getMdAlias(), and MemberDef::isProtectedSettable().
isPrototype() [1/2]
virtual bool MemberDefAliasImpl::isPrototype () const [inline], [virtual]
Implements MemberDef.
Definition at line 676 of file memberdef.cpp.
    { return getMdAlias()->isPrototype(); }
References getMdAlias(), and MemberDef::isPrototype().
isPrototype() [2/2]
virtual bool MemberDefAliasImpl::isPrototype () const [inline], [virtual]
Implements MemberDef.
Definition at line 676 of file memberdef.cpp.
    { return getMdAlias()->isPrototype(); }
References getMdAlias(), and MemberDef::isPrototype().
isPublished() [1/2]
virtual bool MemberDefAliasImpl::isPublished () const [inline], [virtual]
Implements MemberDef.
Definition at line 596 of file memberdef.cpp.
    { return getMdAlias()->isPublished(); }
References getMdAlias(), and MemberDef::isPublished().
isPublished() [2/2]
virtual bool MemberDefAliasImpl::isPublished () const [inline], [virtual]
Implements MemberDef.
Definition at line 596 of file memberdef.cpp.
    { return getMdAlias()->isPublished(); }
References getMdAlias(), and MemberDef::isPublished().
isRaisable() [1/2]
virtual bool MemberDefAliasImpl::isRaisable () const [inline], [virtual]
Implements MemberDef.
Definition at line 532 of file memberdef.cpp.
    { return getMdAlias()->isRaisable(); }
References getMdAlias(), and MemberDef::isRaisable().
isRaisable() [2/2]
virtual bool MemberDefAliasImpl::isRaisable () const [inline], [virtual]
Implements MemberDef.
Definition at line 532 of file memberdef.cpp.
    { return getMdAlias()->isRaisable(); }
References getMdAlias(), and MemberDef::isRaisable().
isReadable() [1/2]
virtual bool MemberDefAliasImpl::isReadable () const [inline], [virtual]
Implements MemberDef.
Definition at line 524 of file memberdef.cpp.
    { return getMdAlias()->isReadable(); }
References getMdAlias(), and MemberDef::isReadable().
isReadable() [2/2]
virtual bool MemberDefAliasImpl::isReadable () const [inline], [virtual]
Implements MemberDef.
Definition at line 524 of file memberdef.cpp.
    { return getMdAlias()->isReadable(); }
References getMdAlias(), and MemberDef::isReadable().
isReadonly() [1/2]
virtual bool MemberDefAliasImpl::isReadonly () const [inline], [virtual]
Implements MemberDef.
Definition at line 582 of file memberdef.cpp.
    { return getMdAlias()->isReadable(); }
References getMdAlias(), and MemberDef::isReadable().
isReadonly() [2/2]
virtual bool MemberDefAliasImpl::isReadonly () const [inline], [virtual]
Implements MemberDef.
Definition at line 582 of file memberdef.cpp.
    { return getMdAlias()->isReadable(); }
References getMdAlias(), and MemberDef::isReadable().
isReference() [1/2]
virtual bool MemberDefAliasImpl::isReference () const [inline], [virtual]
Returns TRUE if this definition is imported via a tag file.
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 744 of file memberdef.cpp.
    { return getMdAlias()->isReference(); }
References getMdAlias(), and MemberDef::isReference().
isReference() [2/2]
virtual bool MemberDefAliasImpl::isReference () const [inline], [virtual]
Returns TRUE if this definition is imported via a tag file.
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 744 of file memberdef.cpp.
    { return getMdAlias()->isReference(); }
References getMdAlias(), and MemberDef::isReference().
isReimplementedBy() [1/2]
virtual bool MemberDefAliasImpl::isReimplementedBy (const ClassDef * cd) const [inline], [virtual]
Implements MemberDef.
Definition at line 656 of file memberdef.cpp.
    { return getMdAlias()->isReimplementedBy(cd); }
References getMdAlias(), and MemberDef::isReimplementedBy().
isReimplementedBy() [2/2]
virtual bool MemberDefAliasImpl::isReimplementedBy (const ClassDef * cd) const [inline], [virtual]
Implements MemberDef.
Definition at line 656 of file memberdef.cpp.
    { return getMdAlias()->isReimplementedBy(cd); }
References getMdAlias(), and MemberDef::isReimplementedBy().
isRelated() [1/2]
virtual bool MemberDefAliasImpl::isRelated () const [inline], [virtual]
Implements MemberDef.
Definition at line 500 of file memberdef.cpp.
    { return getMdAlias()->isRelated(); }
References getMdAlias(), and MemberDef::isRelated().
isRelated() [2/2]
virtual bool MemberDefAliasImpl::isRelated () const [inline], [virtual]
Implements MemberDef.
Definition at line 500 of file memberdef.cpp.
    { return getMdAlias()->isRelated(); }
References getMdAlias(), and MemberDef::isRelated().
isRelatedOrFriend() [1/2]
virtual bool MemberDefAliasImpl::isRelatedOrFriend () const [inline], [virtual]
Implements MemberDef.
Definition at line 632 of file memberdef.cpp.
    { return getMdAlias()->isRelatedOrFriend(); }
References getMdAlias(), and MemberDef::isRelatedOrFriend().
isRelatedOrFriend() [2/2]
virtual bool MemberDefAliasImpl::isRelatedOrFriend () const [inline], [virtual]
Implements MemberDef.
Definition at line 632 of file memberdef.cpp.
    { return getMdAlias()->isRelatedOrFriend(); }
References getMdAlias(), and MemberDef::isRelatedOrFriend().
isRemovable() [1/2]
virtual bool MemberDefAliasImpl::isRemovable () const [inline], [virtual]
Implements MemberDef.
Definition at line 530 of file memberdef.cpp.
    { return getMdAlias()->isRemovable(); }
References getMdAlias(), and MemberDef::isRemovable().
isRemovable() [2/2]
virtual bool MemberDefAliasImpl::isRemovable () const [inline], [virtual]
Implements MemberDef.
Definition at line 530 of file memberdef.cpp.
    { return getMdAlias()->isRemovable(); }
References getMdAlias(), and MemberDef::isRemovable().
isRequired() [1/2]
virtual bool MemberDefAliasImpl::isRequired () const [inline], [virtual]
Implements MemberDef.
Definition at line 544 of file memberdef.cpp.
    { return getMdAlias()->isRequired(); }
References getMdAlias(), and MemberDef::isRequired().
isRequired() [2/2]
virtual bool MemberDefAliasImpl::isRequired () const [inline], [virtual]
Implements MemberDef.
Definition at line 544 of file memberdef.cpp.
    { return getMdAlias()->isRequired(); }
References getMdAlias(), and MemberDef::isRequired().
isRetain() [1/2]
virtual bool MemberDefAliasImpl::isRetain () const [inline], [virtual]
Implements MemberDef.
Definition at line 552 of file memberdef.cpp.
    { return getMdAlias()->isRetain(); }
References getMdAlias(), and MemberDef::isRetain().
isRetain() [2/2]
virtual bool MemberDefAliasImpl::isRetain () const [inline], [virtual]
Implements MemberDef.
Definition at line 552 of file memberdef.cpp.
    { return getMdAlias()->isRetain(); }
References getMdAlias(), and MemberDef::isRetain().
isSealed() [1/2]
virtual bool MemberDefAliasImpl::isSealed () const [inline], [virtual]
Implements MemberDef.
Definition at line 564 of file memberdef.cpp.
    { return getMdAlias()->isSealed(); }
References getMdAlias(), and MemberDef::isSealed().
isSealed() [2/2]
virtual bool MemberDefAliasImpl::isSealed () const [inline], [virtual]
Implements MemberDef.
Definition at line 564 of file memberdef.cpp.
    { return getMdAlias()->isSealed(); }
References getMdAlias(), and MemberDef::isSealed().
isSequence() [1/2]
virtual bool MemberDefAliasImpl::isSequence () const [inline], [virtual]
Implements MemberDef.
Definition at line 482 of file memberdef.cpp.
    { return getMdAlias()->isSequence(); }
References getMdAlias(), and MemberDef::isSequence().
isSequence() [2/2]
virtual bool MemberDefAliasImpl::isSequence () const [inline], [virtual]
Implements MemberDef.
Definition at line 482 of file memberdef.cpp.
    { return getMdAlias()->isSequence(); }
References getMdAlias(), and MemberDef::isSequence().
isSettable() [1/2]
virtual bool MemberDefAliasImpl::isSettable () const [inline], [virtual]
Implements MemberDef.
Definition at line 518 of file memberdef.cpp.
    { return getMdAlias()->isSettable(); }
References getMdAlias(), and MemberDef::isSettable().
isSettable() [2/2]
virtual bool MemberDefAliasImpl::isSettable () const [inline], [virtual]
Implements MemberDef.
Definition at line 518 of file memberdef.cpp.
    { return getMdAlias()->isSettable(); }
References getMdAlias(), and MemberDef::isSettable().
isSignal() [1/2]
virtual bool MemberDefAliasImpl::isSignal () const [inline], [virtual]
Implements MemberDef.
Definition at line 470 of file memberdef.cpp.
    { return getMdAlias()->isSignal(); }
References getMdAlias(), and MemberDef::isSignal().
isSignal() [2/2]
virtual bool MemberDefAliasImpl::isSignal () const [inline], [virtual]
Implements MemberDef.
Definition at line 470 of file memberdef.cpp.
    { return getMdAlias()->isSignal(); }
References getMdAlias(), and MemberDef::isSignal().
isSliceLocal() [1/2]
virtual bool MemberDefAliasImpl::isSliceLocal () const [inline], [virtual]
Implements MemberDef.
Definition at line 620 of file memberdef.cpp.
    { return getMdAlias()->isSliceLocal(); }
References getMdAlias(), and MemberDef::isSliceLocal().
isSliceLocal() [2/2]
virtual bool MemberDefAliasImpl::isSliceLocal () const [inline], [virtual]
Implements MemberDef.
Definition at line 620 of file memberdef.cpp.
    { return getMdAlias()->isSliceLocal(); }
References getMdAlias(), and MemberDef::isSliceLocal().
isSlot() [1/2]
virtual bool MemberDefAliasImpl::isSlot () const [inline], [virtual]
Implements MemberDef.
Definition at line 472 of file memberdef.cpp.
    { return getMdAlias()->isSlot(); }
References getMdAlias(), and MemberDef::isSlot().
isSlot() [2/2]
virtual bool MemberDefAliasImpl::isSlot () const [inline], [virtual]
Implements MemberDef.
Definition at line 472 of file memberdef.cpp.
    { return getMdAlias()->isSlot(); }
References getMdAlias(), and MemberDef::isSlot().
isStatic() [1/2]
virtual bool MemberDefAliasImpl::isStatic () const [inline], [virtual]
Implements MemberDef.
Definition at line 504 of file memberdef.cpp.
    { return getMdAlias()->isStatic(); }
References getMdAlias(), and MemberDef::isStatic().
isStatic() [2/2]
virtual bool MemberDefAliasImpl::isStatic () const [inline], [virtual]
Implements MemberDef.
Definition at line 504 of file memberdef.cpp.
    { return getMdAlias()->isStatic(); }
References getMdAlias(), and MemberDef::isStatic().
isStrong() [1/2]
virtual bool MemberDefAliasImpl::isStrong () const [inline], [virtual]
Implements MemberDef.
Definition at line 556 of file memberdef.cpp.
    { return getMdAlias()->isStrong(); }
References getMdAlias(), and MemberDef::isStrong().
isStrong() [2/2]
virtual bool MemberDefAliasImpl::isStrong () const [inline], [virtual]
Implements MemberDef.
Definition at line 556 of file memberdef.cpp.
    { return getMdAlias()->isStrong(); }
References getMdAlias(), and MemberDef::isStrong().
isStrongEnumValue() [1/2]
virtual bool MemberDefAliasImpl::isStrongEnumValue () const [inline], [virtual]
Implements MemberDef.
Definition at line 616 of file memberdef.cpp.
    { return getMdAlias()->isStrongEnumValue(); }
References getMdAlias(), and MemberDef::isStrongEnumValue().
isStrongEnumValue() [2/2]
virtual bool MemberDefAliasImpl::isStrongEnumValue () const [inline], [virtual]
Implements MemberDef.
Definition at line 616 of file memberdef.cpp.
    { return getMdAlias()->isStrongEnumValue(); }
References getMdAlias(), and MemberDef::isStrongEnumValue().
isTemplateSpecialization() [1/2]
virtual bool MemberDefAliasImpl::isTemplateSpecialization () const [inline], [virtual]
Implements MemberDef.
Definition at line 598 of file memberdef.cpp.
    { return getMdAlias()->isTemplateSpecialization(); }
References getMdAlias(), and MemberDef::isTemplateSpecialization().
isTemplateSpecialization() [2/2]
virtual bool MemberDefAliasImpl::isTemplateSpecialization () const [inline], [virtual]
Implements MemberDef.
Definition at line 598 of file memberdef.cpp.
    { return getMdAlias()->isTemplateSpecialization(); }
References getMdAlias(), and MemberDef::isTemplateSpecialization().
isTransient() [1/2]
virtual bool MemberDefAliasImpl::isTransient () const [inline], [virtual]
Implements MemberDef.
Definition at line 588 of file memberdef.cpp.
    { return getMdAlias()->isTransient(); }
References getMdAlias(), and MemberDef::isTransient().
isTransient() [2/2]
virtual bool MemberDefAliasImpl::isTransient () const [inline], [virtual]
Implements MemberDef.
Definition at line 588 of file memberdef.cpp.
    { return getMdAlias()->isTransient(); }
References getMdAlias(), and MemberDef::isTransient().
isTypeAlias() [1/2]
virtual bool MemberDefAliasImpl::isTypeAlias () const [inline], [virtual]
Implements MemberDef.
Definition at line 570 of file memberdef.cpp.
    { return getMdAlias()->isTypeAlias(); }
References getMdAlias(), and MemberDef::isTypeAlias().
isTypeAlias() [2/2]
virtual bool MemberDefAliasImpl::isTypeAlias () const [inline], [virtual]
Implements MemberDef.
Definition at line 570 of file memberdef.cpp.
    { return getMdAlias()->isTypeAlias(); }
References getMdAlias(), and MemberDef::isTypeAlias().
isTypedef() [1/2]
virtual bool MemberDefAliasImpl::isTypedef () const [inline], [virtual]
Implements MemberDef.
Definition at line 480 of file memberdef.cpp.
    { return getMdAlias()->isTypedef(); }
References getMdAlias(), and MemberDef::isTypedef().
isTypedef() [2/2]
virtual bool MemberDefAliasImpl::isTypedef () const [inline], [virtual]
Implements MemberDef.
Definition at line 480 of file memberdef.cpp.
    { return getMdAlias()->isTypedef(); }
References getMdAlias(), and MemberDef::isTypedef().
isTypedefValCached() [1/2]
virtual bool MemberDefAliasImpl::isTypedefValCached () const [inline], [virtual]
Implements MemberDef.
Definition at line 710 of file memberdef.cpp.
    { return getMdAlias()->isTypedefValCached(); }
References getMdAlias(), and MemberDef::isTypedefValCached().
isTypedefValCached() [2/2]
virtual bool MemberDefAliasImpl::isTypedefValCached () const [inline], [virtual]
Implements MemberDef.
Definition at line 710 of file memberdef.cpp.
    { return getMdAlias()->isTypedefValCached(); }
References getMdAlias(), and MemberDef::isTypedefValCached().
isUNOProperty() [1/2]
virtual bool MemberDefAliasImpl::isUNOProperty () const [inline], [virtual]
Implements MemberDef.
Definition at line 580 of file memberdef.cpp.
    { return getMdAlias()->isUNOProperty(); }
References getMdAlias(), and MemberDef::isUNOProperty().
isUNOProperty() [2/2]
virtual bool MemberDefAliasImpl::isUNOProperty () const [inline], [virtual]
Implements MemberDef.
Definition at line 580 of file memberdef.cpp.
    { return getMdAlias()->isUNOProperty(); }
References getMdAlias(), and MemberDef::isUNOProperty().
isUnretained() [1/2]
virtual bool MemberDefAliasImpl::isUnretained () const [inline], [virtual]
Implements MemberDef.
Definition at line 560 of file memberdef.cpp.
    { return getMdAlias()->isUnretained(); }
References getMdAlias(), and MemberDef::isUnretained().
isUnretained() [2/2]
virtual bool MemberDefAliasImpl::isUnretained () const [inline], [virtual]
Implements MemberDef.
Definition at line 560 of file memberdef.cpp.
    { return getMdAlias()->isUnretained(); }
References getMdAlias(), and MemberDef::isUnretained().
isVariable() [1/2]
virtual bool MemberDefAliasImpl::isVariable () const [inline], [virtual]
Implements MemberDef.
Definition at line 474 of file memberdef.cpp.
    { return getMdAlias()->isVariable(); }
References getMdAlias(), and MemberDef::isVariable().
isVariable() [2/2]
virtual bool MemberDefAliasImpl::isVariable () const [inline], [virtual]
Implements MemberDef.
Definition at line 474 of file memberdef.cpp.
    { return getMdAlias()->isVariable(); }
References getMdAlias(), and MemberDef::isVariable().
isWeak() [1/2]
virtual bool MemberDefAliasImpl::isWeak () const [inline], [virtual]
Implements MemberDef.
Definition at line 554 of file memberdef.cpp.
    { return getMdAlias()->isWeak(); }
References getMdAlias(), and MemberDef::isWeak().
isWeak() [2/2]
virtual bool MemberDefAliasImpl::isWeak () const [inline], [virtual]
Implements MemberDef.
Definition at line 554 of file memberdef.cpp.
    { return getMdAlias()->isWeak(); }
References getMdAlias(), and MemberDef::isWeak().
isWritable() [1/2]
virtual bool MemberDefAliasImpl::isWritable () const [inline], [virtual]
Implements MemberDef.
Definition at line 526 of file memberdef.cpp.
    { return getMdAlias()->isWritable(); }
References getMdAlias(), and MemberDef::isWritable().
isWritable() [2/2]
virtual bool MemberDefAliasImpl::isWritable () const [inline], [virtual]
Implements MemberDef.
Definition at line 526 of file memberdef.cpp.
    { return getMdAlias()->isWritable(); }
References getMdAlias(), and MemberDef::isWritable().
livesInsideEnum() [1/2]
virtual bool MemberDefAliasImpl::livesInsideEnum () const [inline], [virtual]
Implements MemberDef.
Definition at line 618 of file memberdef.cpp.
    { return getMdAlias()->livesInsideEnum(); }
References getMdAlias(), and MemberDef::livesInsideEnum().
livesInsideEnum() [2/2]
virtual bool MemberDefAliasImpl::livesInsideEnum () const [inline], [virtual]
Implements MemberDef.
Definition at line 618 of file memberdef.cpp.
    { return getMdAlias()->livesInsideEnum(); }
References getMdAlias(), and MemberDef::livesInsideEnum().
memberDeclaration() [1/2]
virtual MemberDef * MemberDefAliasImpl::memberDeclaration () const [inline], [virtual]
Implements MemberDef.
Definition at line 720 of file memberdef.cpp.
    { return getMdAlias()->memberDeclaration(); }
References getMdAlias(), and MemberDef::memberDeclaration().
memberDeclaration() [2/2]
virtual MemberDef * MemberDefAliasImpl::memberDeclaration () const [inline], [virtual]
Implements MemberDef.
Definition at line 720 of file memberdef.cpp.
    { return getMdAlias()->memberDeclaration(); }
References getMdAlias(), and MemberDef::memberDeclaration().
memberDefinition() [1/2]
virtual MemberDef * MemberDefAliasImpl::memberDefinition () const [inline], [virtual]
Implements MemberDef.
Definition at line 718 of file memberdef.cpp.
    { return getMdAlias()->memberDefinition(); }
References getMdAlias(), and MemberDef::memberDefinition().
memberDefinition() [2/2]
virtual MemberDef * MemberDefAliasImpl::memberDefinition () const [inline], [virtual]
Implements MemberDef.
Definition at line 718 of file memberdef.cpp.
    { return getMdAlias()->memberDefinition(); }
References getMdAlias(), and MemberDef::memberDefinition().
memberType() [1/2]
virtual MemberType MemberDefAliasImpl::memberType () const [inline], [virtual]
Implements MemberDef.
Definition at line 466 of file memberdef.cpp.
    { return getMdAlias()->memberType(); }
References getMdAlias(), and MemberDef::memberType().
memberType() [2/2]
virtual MemberType MemberDefAliasImpl::memberType () const [inline], [virtual]
Implements MemberDef.
Definition at line 466 of file memberdef.cpp.
    { return getMdAlias()->memberType(); }
References getMdAlias(), and MemberDef::memberType().
memberTypeName() [1/2]
virtual QCString MemberDefAliasImpl::memberTypeName () const [inline], [virtual]
Implements MemberDef.
Definition at line 468 of file memberdef.cpp.
    { return getMdAlias()->memberTypeName(); }
References getMdAlias(), and MemberDef::memberTypeName().
memberTypeName() [2/2]
virtual QCString MemberDefAliasImpl::memberTypeName () const [inline], [virtual]
Implements MemberDef.
Definition at line 468 of file memberdef.cpp.
    { return getMdAlias()->memberTypeName(); }
References getMdAlias(), and MemberDef::memberTypeName().
moveTo() [1/2]
virtual void MemberDefAliasImpl::moveTo (Definition *) [inline], [virtual]
Implements MemberDef.
Definition at line 400 of file memberdef.cpp.
{}
moveTo() [2/2]
virtual void MemberDefAliasImpl::moveTo (Definition *) [inline], [virtual]
Implements MemberDef.
Definition at line 400 of file memberdef.cpp.
{}
name() [1/2]
virtual QCString MemberDefAliasImpl::name () const [inline], [virtual]
Returns the name of the definition
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 402 of file memberdef.cpp.
    { return getMdAlias()->name(); }
References getMdAlias(), and Definition::name().
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
virtual QCString MemberDefAliasImpl::name () const [inline], [virtual]
Returns the name of the definition
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 402 of file memberdef.cpp.
    { return getMdAlias()->name(); }
References getMdAlias(), and Definition::name().
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
numberOfFlowKeyWords() [1/2]
virtual int MemberDefAliasImpl::numberOfFlowKeyWords () const [inline], [virtual]
Implements MemberDef.
Definition at line 624 of file memberdef.cpp.
    { return getMdAlias()->numberOfFlowKeyWords(); }
References getMdAlias(), and MemberDef::numberOfFlowKeyWords().
numberOfFlowKeyWords() [2/2]
virtual int MemberDefAliasImpl::numberOfFlowKeyWords () const [inline], [virtual]
Implements MemberDef.
Definition at line 624 of file memberdef.cpp.
    { return getMdAlias()->numberOfFlowKeyWords(); }
References getMdAlias(), and MemberDef::numberOfFlowKeyWords().
objCMethodName() [1/2]
virtual QCString MemberDefAliasImpl::objCMethodName (bool localLink, bool showStatic) const [inline], [virtual]
Implements MemberDef.
Definition at line 460 of file memberdef.cpp.
    { return getMdAlias()->objCMethodName(localLink,showStatic); }
References getMdAlias(), and MemberDef::objCMethodName().
objCMethodName() [2/2]
virtual QCString MemberDefAliasImpl::objCMethodName (bool localLink, bool showStatic) const [inline], [virtual]
Implements MemberDef.
Definition at line 460 of file memberdef.cpp.
    { return getMdAlias()->objCMethodName(localLink,showStatic); }
References getMdAlias(), and MemberDef::objCMethodName().
protection() [1/2]
virtual Protection MemberDefAliasImpl::protection () const [inline], [virtual]
Implements MemberDef.
Definition at line 462 of file memberdef.cpp.
    { return getMdAlias()->protection(); }
References getMdAlias(), and MemberDef::protection().
protection() [2/2]
virtual Protection MemberDefAliasImpl::protection () const [inline], [virtual]
Implements MemberDef.
Definition at line 462 of file memberdef.cpp.
    { return getMdAlias()->protection(); }
References getMdAlias(), and MemberDef::protection().
qualifiedName() [1/2]
virtual QCString MemberDefAliasImpl::qualifiedName () const [inline], [virtual]
Returns the fully qualified name of this definition
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 458 of file memberdef.cpp.
    { return getMdAlias()->qualifiedName(); }
References getMdAlias(), and MemberDef::qualifiedName().
qualifiedName() [2/2]
virtual QCString MemberDefAliasImpl::qualifiedName () const [inline], [virtual]
Returns the fully qualified name of this definition
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 458 of file memberdef.cpp.
    { return getMdAlias()->qualifiedName(); }
References getMdAlias(), and MemberDef::qualifiedName().
reimplementedBy() [1/2]
virtual const MemberVector & MemberDefAliasImpl::reimplementedBy () const [inline], [virtual]
Implements MemberDef.
Definition at line 654 of file memberdef.cpp.
    { return getMdAlias()->reimplementedBy(); }
References getMdAlias(), and MemberDef::reimplementedBy().
reimplementedBy() [2/2]
virtual const MemberVector & MemberDefAliasImpl::reimplementedBy () const [inline], [virtual]
Implements MemberDef.
Definition at line 654 of file memberdef.cpp.
    { return getMdAlias()->reimplementedBy(); }
References getMdAlias(), and MemberDef::reimplementedBy().
reimplements() [1/2]
virtual const MemberDef * MemberDefAliasImpl::reimplements () const [inline], [virtual]
Implements MemberDef.
Definition at line 652 of file memberdef.cpp.
    { return getMdAlias()->reimplements(); }
References getMdAlias(), and MemberDef::reimplements().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::add_reimplements(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_reimplements(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.memberdefType::insert_reimplements_at(), doxmlparser.compound.memberdefType::replace_reimplements_at(), and doxmlparser.compound.memberdefType::set_reimplements().
reimplements() [2/2]
virtual const MemberDef * MemberDefAliasImpl::reimplements () const [inline], [virtual]
Implements MemberDef.
Definition at line 652 of file memberdef.cpp.
    { return getMdAlias()->reimplements(); }
References getMdAlias(), and MemberDef::reimplements().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::add_reimplements(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_reimplements(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.memberdefType::insert_reimplements_at(), doxmlparser.compound.memberdefType::replace_reimplements_at(), and doxmlparser.compound.memberdefType::set_reimplements().
relatedAlso() [1/2]
virtual ClassDef * MemberDefAliasImpl::relatedAlso () const [inline], [virtual]
Implements MemberDef.
Definition at line 658 of file memberdef.cpp.
    { return getMdAlias()->relatedAlso(); }
References getMdAlias(), and MemberDef::relatedAlso().
relatedAlso() [2/2]
virtual ClassDef * MemberDefAliasImpl::relatedAlso () const [inline], [virtual]
Implements MemberDef.
Definition at line 658 of file memberdef.cpp.
    { return getMdAlias()->relatedAlso(); }
References getMdAlias(), and MemberDef::relatedAlso().
requiresClause() [1/2]
virtual QCString MemberDefAliasImpl::requiresClause () const [inline], [virtual]
Implements MemberDef.
Definition at line 752 of file memberdef.cpp.
    { return getMdAlias()->requiresClause(); }
References getMdAlias(), and MemberDef::requiresClause().
requiresClause() [2/2]
virtual QCString MemberDefAliasImpl::requiresClause () const [inline], [virtual]
Implements MemberDef.
Definition at line 752 of file memberdef.cpp.
    { return getMdAlias()->requiresClause(); }
References getMdAlias(), and MemberDef::requiresClause().
resolveAlias() [1/4]
virtual MemberDef * MemberDefAliasImpl::resolveAlias () [inline], [virtual]
Implements MemberDef.
Definition at line 394 of file memberdef.cpp.
{ return const_cast<MemberDef*>(getMdAlias()); }
References getMdAlias().
resolveAlias() [2/4]
virtual MemberDef * MemberDefAliasImpl::resolveAlias () [inline], [virtual]
Implements MemberDef.
Definition at line 394 of file memberdef.cpp.
{ return const_cast<MemberDef*>(getMdAlias()); }
References getMdAlias().
resolveAlias() [3/4]
virtual const MemberDef * MemberDefAliasImpl::resolveAlias () const [inline], [virtual]
Implements MemberDef.
Definition at line 395 of file memberdef.cpp.
{ return getMdAlias(); }
References getMdAlias().
resolveAlias() [4/4]
virtual const MemberDef * MemberDefAliasImpl::resolveAlias () const [inline], [virtual]
Implements MemberDef.
Definition at line 395 of file memberdef.cpp.
{ return getMdAlias(); }
References getMdAlias().
setMemberGroup() [1/2]
virtual void MemberDefAliasImpl::setMemberGroup (MemberGroup * grp) [inline], [virtual]
Implements MemberDef.
Definition at line 760 of file memberdef.cpp.
{ m_memberGroup = grp; }
References m_memberGroup.
setMemberGroup() [2/2]
virtual void MemberDefAliasImpl::setMemberGroup (MemberGroup * grp) [inline], [virtual]
Implements MemberDef.
Definition at line 760 of file memberdef.cpp.
{ m_memberGroup = grp; }
References m_memberGroup.
showInCallGraph() [1/2]
virtual bool MemberDefAliasImpl::showInCallGraph () const [inline], [virtual]
Implements MemberDef.
Definition at line 614 of file memberdef.cpp.
    { return getMdAlias()->showInCallGraph(); }
References getMdAlias(), and MemberDef::showInCallGraph().
showInCallGraph() [2/2]
virtual bool MemberDefAliasImpl::showInCallGraph () const [inline], [virtual]
Implements MemberDef.
Definition at line 614 of file memberdef.cpp.
    { return getMdAlias()->showInCallGraph(); }
References getMdAlias(), and MemberDef::showInCallGraph().
templateArguments() [1/2]
virtual const ArgumentList & MemberDefAliasImpl::templateArguments () const [inline], [virtual]
Implements MemberDef.
Definition at line 682 of file memberdef.cpp.
    { return getMdAlias()->templateArguments(); }
References getMdAlias(), and MemberDef::templateArguments().
templateArguments() [2/2]
virtual const ArgumentList & MemberDefAliasImpl::templateArguments () const [inline], [virtual]
Implements MemberDef.
Definition at line 682 of file memberdef.cpp.
    { return getMdAlias()->templateArguments(); }
References getMdAlias(), and MemberDef::templateArguments().
templateMaster() [1/2]
virtual const MemberDef * MemberDefAliasImpl::templateMaster () const [inline], [virtual]
Implements MemberDef.
Definition at line 704 of file memberdef.cpp.
    { return getMdAlias()->templateMaster(); }
References getMdAlias(), and MemberDef::templateMaster().
templateMaster() [2/2]
virtual const MemberDef * MemberDefAliasImpl::templateMaster () const [inline], [virtual]
Implements MemberDef.
Definition at line 704 of file memberdef.cpp.
    { return getMdAlias()->templateMaster(); }
References getMdAlias(), and MemberDef::templateMaster().
typeConstraints() [1/2]
virtual const ArgumentList & MemberDefAliasImpl::typeConstraints () const [inline], [virtual]
Implements MemberDef.
Definition at line 736 of file memberdef.cpp.
    { return getMdAlias()->typeConstraints(); }
References getMdAlias(), and MemberDef::typeConstraints().
typeConstraints() [2/2]
virtual const ArgumentList & MemberDefAliasImpl::typeConstraints () const [inline], [virtual]
Implements MemberDef.
Definition at line 736 of file memberdef.cpp.
    { return getMdAlias()->typeConstraints(); }
References getMdAlias(), and MemberDef::typeConstraints().
typeString() [1/2]
virtual QCString MemberDefAliasImpl::typeString () const [inline], [virtual]
Implements MemberDef.
Definition at line 416 of file memberdef.cpp.
    { return getMdAlias()->typeString(); }
References getMdAlias(), and MemberDef::typeString().
typeString() [2/2]
virtual QCString MemberDefAliasImpl::typeString () const [inline], [virtual]
Implements MemberDef.
Definition at line 416 of file memberdef.cpp.
    { return getMdAlias()->typeString(); }
References getMdAlias(), and MemberDef::typeString().
virtualness() [1/2]
virtual Specifier MemberDefAliasImpl::virtualness (int count) const [inline], [virtual]
Implements MemberDef.
Definition at line 464 of file memberdef.cpp.
    { return getMdAlias()->virtualness(); }
References getMdAlias(), and MemberDef::virtualness().
virtualness() [2/2]
virtual Specifier MemberDefAliasImpl::virtualness (int count) const [inline], [virtual]
Implements MemberDef.
Definition at line 464 of file memberdef.cpp.
    { return getMdAlias()->virtualness(); }
References getMdAlias(), and MemberDef::virtualness().
visibleInIndex() [1/2]
virtual bool MemberDefAliasImpl::visibleInIndex () const [inline], [virtual]
Implements MemberDef.
Definition at line 754 of file memberdef.cpp.
    { return getMdAlias()->visibleInIndex(); }
References getMdAlias(), and MemberDef::visibleInIndex().
visibleInIndex() [2/2]
virtual bool MemberDefAliasImpl::visibleInIndex () const [inline], [virtual]
Implements MemberDef.
Definition at line 754 of file memberdef.cpp.
    { return getMdAlias()->visibleInIndex(); }
References getMdAlias(), and MemberDef::visibleInIndex().
warnIfUndocumented() [1/2]
virtual void MemberDefAliasImpl::warnIfUndocumented () const [inline], [virtual]
Implements MemberDef.
Definition at line 757 of file memberdef.cpp.
{}
warnIfUndocumented() [2/2]
virtual void MemberDefAliasImpl::warnIfUndocumented () const [inline], [virtual]
Implements MemberDef.
Definition at line 757 of file memberdef.cpp.
{}
warnIfUndocumentedParams() [1/2]
virtual void MemberDefAliasImpl::warnIfUndocumentedParams () const [inline], [virtual]
Implements MemberDef.
Definition at line 758 of file memberdef.cpp.
{}
warnIfUndocumentedParams() [2/2]
virtual void MemberDefAliasImpl::warnIfUndocumentedParams () const [inline], [virtual]
Implements MemberDef.
Definition at line 758 of file memberdef.cpp.
{}
writeDeclaration() [1/2]
virtual void MemberDefAliasImpl::writeDeclaration (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool inGroup, int indentLevel, const ClassDef * inheritFrom = 0, const QCString & inheritId = QCString()) const [inline], [virtual]
Implements MemberDef.
Definition at line 765 of file memberdef.cpp.
    {
      getMdAlias()->writeDeclaration(ol,cd,nd,fd,gd,inGroup,indentLevel,inheritFrom,inheritId);
    }
References getMdAlias(), and MemberDef::writeDeclaration().
writeDeclaration() [2/2]
virtual void MemberDefAliasImpl::writeDeclaration (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool inGroup, int indentLevel, const ClassDef * inheritFrom = 0, const QCString & inheritId = QCString()) const [inline], [virtual]
Implements MemberDef.
Definition at line 765 of file memberdef.cpp.
    {
      getMdAlias()->writeDeclaration(ol,cd,nd,fd,gd,inGroup,indentLevel,inheritFrom,inheritId);
    }
References getMdAlias(), and MemberDef::writeDeclaration().
writeEnumDeclaration() [1/2]
virtual void MemberDefAliasImpl::writeEnumDeclaration (OutputList & typeDecl, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd) const [inline], [virtual]
Implements MemberDef.
Definition at line 771 of file memberdef.cpp.
    {
      getMdAlias()->writeEnumDeclaration(typeDecl,cd,nd,fd,gd);
    }
References getMdAlias(), and MemberDef::writeEnumDeclaration().
writeEnumDeclaration() [2/2]
virtual void MemberDefAliasImpl::writeEnumDeclaration (OutputList & typeDecl, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd) const [inline], [virtual]
Implements MemberDef.
Definition at line 771 of file memberdef.cpp.
    {
      getMdAlias()->writeEnumDeclaration(typeDecl,cd,nd,fd,gd);
    }
References getMdAlias(), and MemberDef::writeEnumDeclaration().
Member Data Documentation
m_memberGroup
MemberGroup * MemberDefAliasImpl::m_memberGroup [private]
Definition at line 777 of file memberdef.cpp.
Referenced by getMemberGroup(), and setMemberGroup().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/memberdef.cpp
doxygen/src/memberdef.cpp