Step1 Class Reference
#include <wizard.h>
Public Member Functions
Step1 (Wizard *parent, const QHash< QString, Input * > &modelData)
void init ()
Step1 (Wizard *parent, const QHash< QString, Input * > &modelData)
void init ()
Private Slots
void selectSourceDir ()
void selectDestinationDir ()
void selectProjectIcon ()
void setProjectName (const QString &name)
void setProjectBrief (const QString &desc)
void setProjectNumber (const QString &num)
void setSourceDir (const QString &dir)
void setDestinationDir (const QString &dir)
void setRecursiveScan (int)
void selectSourceDir ()
void selectDestinationDir ()
void selectProjectIcon ()
void setProjectName (const QString &name)
void setProjectBrief (const QString &desc)
void setProjectNumber (const QString &num)
void setSourceDir (const QString &dir)
void setDestinationDir (const QString &dir)
void setRecursiveScan (int)
Private Attributes
QLineEdit * m_projName = 0
QLineEdit * m_projBrief = 0
QLineEdit * m_projNumber = 0
QLineEdit * m_sourceDir = 0
QLineEdit * m_destDir = 0
QLabel * m_projIconLab = 0
QCheckBox * m_recursive = 0
QPushButton * m_srcSelectDir = 0
QPushButton * m_dstSelectDir = 0
Wizard * m_wizard = 0
const QHash< QString, Input * > & m_modelData
Detailed Description
Definition at line 96 of file wizard.h.
Constructor & Destructor Documentation
Step1() [1/2]
Step1::Step1 (Wizard * parent, const QHash< QString, Input * > & modelData)
Definition at line 479 of file wizard.cpp.
                                                                  : m_wizard(wizard), m_modelData(modelData)
{
  QVBoxLayout *layout = new QVBoxLayout(this);
  layout->setContentsMargins(4,4,4,4);
  layout->setSpacing(8);
  QLabel *l = new QLabel(this);
  l->setText(tr("Provide some information "
              "about the project you are documenting"));
  layout->addWidget(l);
  QWidget *w = new QWidget(this);
  QGridLayout *grid = new QGridLayout(w);
  grid->setSpacing(10);
  // project name
  QLabel *projName = new QLabel(this);
  projName->setText(tr("Project name:"));
  projName->setAlignment(Qt::AlignRight|Qt::AlignVCenter);
  // project brief
  QLabel *projBrief = new QLabel(this);
  projBrief->setText(tr("Project synopsis:"));
  projBrief->setAlignment(Qt::AlignRight|Qt::AlignVCenter);
  // project version
  QLabel *projVersion = new QLabel(this);
  projVersion->setText(tr("Project version or id:"));
  projVersion->setAlignment(Qt::AlignRight|Qt::AlignVCenter);
  // project icon
  QLabel *projLogo = new QLabel(this);
  projLogo->setMinimumSize(1,55);
  projLogo->setText(tr("Project logo:"));
  projLogo->setAlignment(Qt::AlignRight|Qt::AlignVCenter);
  grid->addWidget(projName,0,0);
  grid->addWidget(projBrief,1,0);
  grid->addWidget(projVersion,2,0);
  grid->addWidget(projLogo,3,0);
  m_projName = new QLineEdit;
  m_projBrief = new QLineEdit;
  m_projNumber = new QLineEdit;
  QPushButton *projIconSel = new QPushButton(this);
  projIconSel->setText(tr("Select..."));
  m_projIconLab = new QLabel;
  grid->addWidget(m_projName,0,1,1,2);
  grid->addWidget(m_projBrief,1,1,1,2);
  grid->addWidget(m_projNumber,2,1,1,2);
  grid->addWidget(projIconSel,3,1);
  grid->addWidget(m_projIconLab,3,2);
  grid->setColumnStretch(2,1);
  w->setLayout(grid);
  layout->addWidget(w);
  //---------------------------------------------------
  QFrame *f = new QFrame(this);
  f->setFrameStyle(QFrame::HLine | QFrame::Sunken);
  layout->addWidget(f);
  l = new QLabel(this);
  l->setText(tr("Specify the directory to scan for source code"));
  layout->addWidget(l);
  QWidget *row = new QWidget;
  QHBoxLayout *rowLayout = new QHBoxLayout(row);
  rowLayout->setSpacing(10);
  l = new QLabel(this);
  l->setText(tr("Source code directory:"));
  rowLayout->addWidget(l);
  m_sourceDir = new QLineEdit;
  m_srcSelectDir = new QPushButton(this);
  m_srcSelectDir->setText(tr("Select..."));
  rowLayout->addWidget(m_sourceDir);
  rowLayout->addWidget(m_srcSelectDir);
  layout->addWidget(row);
  m_recursive = new QCheckBox(this);
  m_recursive->setText(tr("Scan recursively"));
  m_recursive->setChecked(true);
  layout->addWidget(m_recursive);
  //---------------------------------------------------
  f = new QFrame(this);
  f->setFrameStyle(QFrame::HLine | QFrame::Sunken);
  layout->addWidget(f);
  l = new QLabel(this);
  l->setText(tr("Specify the directory where doxygen should "
              "put the generated documentation"));
  layout->addWidget(l);
  row = new QWidget;
  rowLayout = new QHBoxLayout(row);
  rowLayout->setSpacing(10);
  l = new QLabel(this);
  l->setText(tr("Destination directory:"));
  rowLayout->addWidget(l);
  m_destDir = new QLineEdit;
  m_dstSelectDir = new QPushButton(this);
  m_dstSelectDir->setText(tr("Select..."));
  rowLayout->addWidget(m_destDir);
  rowLayout->addWidget(m_dstSelectDir);
  layout->addWidget(row);
  layout->addStretch(1);
  setLayout(layout);
  connect(projIconSel,SIGNAL(clicked()),
          this,SLOT(selectProjectIcon()));
  connect(m_srcSelectDir,SIGNAL(clicked()),
          this,SLOT(selectSourceDir()));
  connect(m_dstSelectDir,SIGNAL(clicked()),
          this,SLOT(selectDestinationDir()));
  connect(m_projName,SIGNAL(textChanged(const QString &)),SLOT(setProjectName(const QString &)));
  connect(m_projBrief,SIGNAL(textChanged(const QString &)),SLOT(setProjectBrief(const QString &)));
  connect(m_projNumber,SIGNAL(textChanged(const QString &)),SLOT(setProjectNumber(const QString &)));
  connect(m_sourceDir,SIGNAL(textChanged(const QString &)),SLOT(setSourceDir(const QString &)));
  connect(m_recursive,SIGNAL(stateChanged(int)),SLOT(setRecursiveScan(int)));
  connect(m_destDir,SIGNAL(textChanged(const QString &)),SLOT(setDestinationDir(const QString &)));
}
References AlignRight, f, m_destDir, m_dstSelectDir, m_projBrief, m_projIconLab, m_projName, m_projNumber, m_recursive, m_sourceDir, m_srcSelectDir, selectDestinationDir(), selectProjectIcon(), selectSourceDir(), setDestinationDir(), setProjectBrief(), setProjectName(), setProjectNumber(), setRecursiveScan(), setSourceDir(), and w.
Step1() [2/2]
Step1::Step1 (Wizard * parent, const QHash< QString, Input * > & modelData)
Member Function Documentation
init() [1/2]
void Step1::init ()
Definition at line 709 of file wizard.cpp.
{
  Input *option;
  m_projName->setText(getStringOption(m_modelData,STR_PROJECT_NAME));
  m_projBrief->setText(getStringOption(m_modelData,STR_PROJECT_BRIEF));
  m_projNumber->setText(getStringOption(m_modelData,STR_PROJECT_NUMBER));
  QString iconName = getStringOption(m_modelData,STR_PROJECT_LOGO);
  if (!iconName.isEmpty())
  {
    QFile Fout(iconName);
    if(!Fout.exists())
    {
      m_projIconLab->setText(tr("Sorry, cannot find file(")+iconName+QString::fromLatin1(");"));
    }
    else
    {
      QPixmap pm(iconName);
      if (!pm.isNull())
      {
        m_projIconLab->setPixmap(pm.scaledToHeight(55,Qt::SmoothTransformation));
      }
      else
      {
        m_projIconLab->setText(tr("Sorry, no preview available (")+iconName+QString::fromLatin1(");"));
      }
    }
  }
  else
  {
    m_projIconLab->setText(tr("No Project logo selected."));
  }
  option = m_modelData[STR_INPUT];
  if (option->value().toStringList().count()>0)
  {
    m_sourceDir->setText(option->value().toStringList().first());
  }
  m_recursive->setChecked(
      getBoolOption(m_modelData,STR_RECURSIVE) ? Qt::Checked : Qt::Unchecked);
  m_destDir->setText(getStringOption(m_modelData,STR_OUTPUT_DIRECTORY));
}
References getBoolOption(), getStringOption(), m_destDir, m_modelData, m_projBrief, m_projIconLab, m_projName, m_projNumber, m_recursive, m_sourceDir, STR_INPUT, STR_OUTPUT_DIRECTORY, STR_PROJECT_BRIEF, STR_PROJECT_LOGO, STR_PROJECT_NAME, STR_PROJECT_NUMBER, STR_RECURSIVE, and Input::value().
Referenced by Wizard::refresh().
init() [2/2]
void Step1::init ()
selectDestinationDir [1/2]
void Step1::selectDestinationDir () [private], [slot]
Definition at line 647 of file wizard.cpp.
{
  QString path = QFileInfo(MainWindow::instance().configFileName()).path();
  QString dirName = QFileDialog::getExistingDirectory(this,
        tr("Select destination directory"),path);
  QDir dir(path);
  if (!MainWindow::instance().configFileName().isEmpty() && dir.exists())
  {
    dirName = dir.relativeFilePath(dirName);
  }
  if (dirName.isEmpty())
  {
    dirName=QString::fromLatin1(".");
  }
  m_destDir->setText(dirName);
}
References MainWindow::instance(), and m_destDir.
Referenced by Step1().
selectDestinationDir [2/2]
void Step1::selectDestinationDir () [private], [slot]
selectProjectIcon [1/2]
void Step1::selectProjectIcon () [private], [slot]
Definition at line 598 of file wizard.cpp.
{
  QString path = QFileInfo(MainWindow::instance().configFileName()).path();
  QString iconName = QFileDialog::getOpenFileName(this,
                                    tr("Select project icon/image"),path);
  if (iconName.isEmpty())
  {
    m_projIconLab->setText(tr("No Project logo selected."));
  }
  else
  {
    QFile Fout(iconName);
    if(!Fout.exists())
    {
      m_projIconLab->setText(tr("Sorry, cannot find file(")+iconName+QString::fromLatin1(");"));
    }
    else
    {
      QPixmap pm(iconName);
      if (!pm.isNull())
      {
        m_projIconLab->setPixmap(pm.scaledToHeight(55,Qt::SmoothTransformation));
      }
      else
      {
        m_projIconLab->setText(tr("Sorry, no preview available (")+iconName+QString::fromLatin1(");"));
      }
    }
  }
  updateStringOption(m_modelData,STR_PROJECT_LOGO,iconName);
}
References MainWindow::instance(), m_modelData, m_projIconLab, STR_PROJECT_LOGO, and updateStringOption().
Referenced by Step1().
selectProjectIcon [2/2]
void Step1::selectProjectIcon () [private], [slot]
selectSourceDir [1/2]
void Step1::selectSourceDir () [private], [slot]
Definition at line 630 of file wizard.cpp.
{
  QString path = QFileInfo(MainWindow::instance().configFileName()).path();
  QString dirName = QFileDialog::getExistingDirectory(this,
        tr("Select source directory"),path);
  QDir dir(path);
  if (!MainWindow::instance().configFileName().isEmpty() && dir.exists())
  {
    dirName = dir.relativeFilePath(dirName);
  }
  if (dirName.isEmpty())
  {
    dirName=QString::fromLatin1(".");
  }
  m_sourceDir->setText(dirName);
}
References MainWindow::instance(), and m_sourceDir.
Referenced by Step1().
selectSourceDir [2/2]
void Step1::selectSourceDir () [private], [slot]
setDestinationDir [1/2]
void Step1::setDestinationDir (const QString & dir) [private], [slot]
Definition at line 699 of file wizard.cpp.
{
  updateStringOption(m_modelData,STR_OUTPUT_DIRECTORY,dir);
}
References m_modelData, STR_OUTPUT_DIRECTORY, and updateStringOption().
Referenced by Step1().
setDestinationDir [2/2]
void Step1::setDestinationDir (const QString & dir) [private], [slot]
setProjectBrief [1/2]
void Step1::setProjectBrief (const QString & desc) [private], [slot]
Definition at line 669 of file wizard.cpp.
{
  updateStringOption(m_modelData,STR_PROJECT_BRIEF,desc);
}
References m_modelData, STR_PROJECT_BRIEF, and updateStringOption().
Referenced by Step1().
setProjectBrief [2/2]
void Step1::setProjectBrief (const QString & desc) [private], [slot]
setProjectName [1/2]
void Step1::setProjectName (const QString & name) [private], [slot]
Definition at line 664 of file wizard.cpp.
{
  updateStringOption(m_modelData,STR_PROJECT_NAME,name);
}
References m_modelData, setup::name, STR_PROJECT_NAME, and updateStringOption().
Referenced by Step1().
setProjectName [2/2]
void Step1::setProjectName (const QString & name) [private], [slot]
setProjectNumber [1/2]
void Step1::setProjectNumber (const QString & num) [private], [slot]
Definition at line 674 of file wizard.cpp.
{
  updateStringOption(m_modelData,STR_PROJECT_NUMBER,num);
}
References m_modelData, STR_PROJECT_NUMBER, and updateStringOption().
Referenced by Step1().
setProjectNumber [2/2]
void Step1::setProjectNumber (const QString & num) [private], [slot]
setRecursiveScan [1/2]
void Step1::setRecursiveScan (int s) [private], [slot]
Definition at line 704 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_RECURSIVE,s==Qt::Checked);
}
References m_modelData, s, STR_RECURSIVE, and updateBoolOption().
Referenced by Step1().
setRecursiveScan [2/2]
void Step1::setRecursiveScan (int) [private], [slot]
setSourceDir [1/2]
void Step1::setSourceDir (const QString & dir) [private], [slot]
Definition at line 679 of file wizard.cpp.
{
  Input *option = m_modelData[STR_INPUT];
  if (option->value().toStringList().count()>0)
  {
    QStringList sl = option->value().toStringList();
    if (sl[0]!=dir)
    {
      sl[0] = dir;
      option->value() = sl;
      option->update();
    }
  }
  else
  {
    option->value() = QStringList() << dir;
    option->update();
  }
}
References m_modelData, caseconvert::sl, STR_INPUT, Input::update(), and Input::value().
Referenced by Step1().
setSourceDir [2/2]
void Step1::setSourceDir (const QString & dir) [private], [slot]
Member Data Documentation
m_destDir
QLineEdit * Step1::m_destDir = 0 [private]
Definition at line 120 of file wizard.h.
Referenced by init(), selectDestinationDir(), and Step1().
m_dstSelectDir
QPushButton * Step1::m_dstSelectDir = 0 [private]
Definition at line 124 of file wizard.h.
Referenced by Step1().
m_modelData
const QHash< QString, Input * > & Step1::m_modelData [private]
Definition at line 126 of file wizard.h.
Referenced by init(), selectProjectIcon(), setDestinationDir(), setProjectBrief(), setProjectName(), setProjectNumber(), setRecursiveScan(), and setSourceDir().
m_projBrief
QLineEdit * Step1::m_projBrief = 0 [private]
Definition at line 117 of file wizard.h.
Referenced by init(), and Step1().
m_projIconLab
QLabel * Step1::m_projIconLab = 0 [private]
Definition at line 121 of file wizard.h.
Referenced by init(), selectProjectIcon(), and Step1().
m_projName
QLineEdit * Step1::m_projName = 0 [private]
Definition at line 116 of file wizard.h.
Referenced by init(), and Step1().
m_projNumber
QLineEdit * Step1::m_projNumber = 0 [private]
Definition at line 118 of file wizard.h.
Referenced by init(), and Step1().
m_recursive
QCheckBox * Step1::m_recursive = 0 [private]
Definition at line 122 of file wizard.h.
Referenced by init(), and Step1().
m_sourceDir
QLineEdit * Step1::m_sourceDir = 0 [private]
Definition at line 119 of file wizard.h.
Referenced by init(), selectSourceDir(), and Step1().
m_srcSelectDir
QPushButton * Step1::m_srcSelectDir = 0 [private]
Definition at line 123 of file wizard.h.
Referenced by Step1().
m_wizard
Wizard * Step1::m_wizard = 0 [private]
Definition at line 125 of file wizard.h.
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/wizard.h
doxygen/build/doxygen/addon/doxywizard/wizard.h
doxygen/addon/doxywizard/wizard.cpp
doxygen/build/doxygen/addon/doxywizard/wizard.cpp