DotLegendGraph Class Reference
#include <dotlegendgraph.h>
Public Member Functions
void writeGraph (const QCString &path)
void writeGraph (const QCString &path)
Private Member Functions
virtual QCString getBaseName () const
virtual void computeTheGraph ()
virtual QCString getMapLabel () const
virtual QCString getBaseName () const
virtual void computeTheGraph ()
virtual QCString getMapLabel () const
Additional Inherited Members
Detailed Description
Representation of a legend explaining the meaning of boxes, arrows, and colors
Definition at line 22 of file dotlegendgraph.h.
Member Function Documentation
computeTheGraph() [1/2]
void DotLegendGraph::computeTheGraph () [private], [virtual]
Implements DotGraph.
Definition at line 45 of file dotlegendgraph.cpp.
{
  TextStream md5stream;
  writeGraphHeader(md5stream,theTranslator->trLegendTitle());
  DotNode{9, "Inherited", "", "", TRUE}.writeBox(md5stream, CallGraph, GOF_BITMAP, false);
  md5stream << " Node10 -> Node9 [dir=\"back\",color=\"steelblue1\",style=\"solid\"];\n";
  DotNode{10, "PublicBase", "", "url"}.markHasDocumentation().writeBox(md5stream, CallGraph, GOF_BITMAP, false);
  md5stream << " Node11 -> Node10 [dir=\"back\",color=\"steelblue1\",style=\"solid\"];\n";
  DotNode{11, "Truncated", "", "url"}.markAsTruncated().markHasDocumentation().writeBox(md5stream, CallGraph, GOF_BITMAP, true);
  md5stream << " Node13 -> Node9 [dir=\"back\",color=\"darkgreen\",style=\"solid\"];\n";
  md5stream << " Node13 [label=\"ProtectedBase\",color=\"gray40\",fillcolor=\"white\",style=\"filled\"];\n";
  md5stream << " Node14 -> Node9 [dir=\"back\",color=\"firebrick4\",style=\"solid\"];\n";
  md5stream << " Node14 [label=\"PrivateBase\",color=\"gray40\",fillcolor=\"white\",style=\"filled\"];\n";
  md5stream << " Node15 -> Node9 [dir=\"back\",color=\"steelblue1\",style=\"solid\"];\n";
  DotNode{15, "Undocumented", "", ""}.writeBox(md5stream, CallGraph, GOF_BITMAP, false);
  md5stream << " Node16 -> Node9 [dir=\"back\",color=\"steelblue1\",style=\"solid\"];\n";
  md5stream << " Node16 [label=\"Templ\\< int \\>\",color=\"gray40\",fillcolor=\"white\",style=\"filled\"];\n";
  md5stream << " Node17 -> Node16 [dir=\"back\",color=\"orange\",style=\"dashed\",label=\"< int >\",];\n";
  md5stream << " Node17 [label=\"Templ\\< T \\>\",color=\"gray40\",fillcolor=\"white\",style=\"filled\"];\n";
  md5stream << " Node18 -> Node9 [dir=\"back\",color=\"darkorchid3\",style=\"dashed\",label=\"m_usedClass\",];\n";
  md5stream << " Node18 [label=\"Used\",color=\"gray40\",fillcolor=\"white\",style=\"filled\"];\n";
  writeGraphFooter(md5stream);
  m_theGraph = md5stream.str();
}
References CallGraph, GOF_BITMAP, DotGraph::m_theGraph, DotNode::markAsTruncated(), DotNode::markHasDocumentation(), TextStream::str(), theTranslator, Translator::trLegendTitle(), TRUE, DotNode::writeBox(), DotGraph::writeGraphFooter(), and DotGraph::writeGraphHeader().
computeTheGraph() [2/2]
virtual void DotLegendGraph::computeTheGraph () [private], [virtual]
Implements DotGraph.
getBaseName() [1/2]
QCString DotLegendGraph::getBaseName () const [private], [virtual]
Implements DotGraph.
Definition at line 40 of file dotlegendgraph.cpp.
{
  return "graph_legend";
}
getBaseName() [2/2]
virtual QCString DotLegendGraph::getBaseName () const [private], [virtual]
Implements DotGraph.
getMapLabel() [1/2]
QCString DotLegendGraph::getMapLabel () const [private], [virtual]
Implements DotGraph.
Definition at line 71 of file dotlegendgraph.cpp.
{
  return "";
}
getMapLabel() [2/2]
virtual QCString DotLegendGraph::getMapLabel () const [private], [virtual]
Implements DotGraph.
writeGraph() [1/2]
void DotLegendGraph::writeGraph (const QCString & path)
Definition at line 27 of file dotlegendgraph.cpp.
{
  TextStream ts;
  DotGraph::writeGraph(ts, GOF_BITMAP, EOF_Html, path, "", "", FALSE, 0);
  if (getDotImageExtension()=="svg")
  {
    DotManager::instance()->
      createFilePatcher(absBaseName()+Config_getString(HTML_FILE_EXTENSION))->
      addSVGObject("graph_legend", absImgName(),QCString());
  }
}
References DotGraph::absBaseName(), DotGraph::absImgName(), Config_getString, EOF_Html, FALSE, getDotImageExtension(), GOF_BITMAP, DotManager::instance(), and DotGraph::writeGraph().
Referenced by writeGraphInfo().
writeGraph() [2/2]
void DotLegendGraph::writeGraph (const QCString & path)
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dotlegendgraph.h
doxygen/src/dotlegendgraph.h
doxygen/build/doxygen/src/dotlegendgraph.cpp
doxygen/src/dotlegendgraph.cpp