TextGeneratorFactory Class Reference
Public Member Functions
TextGeneratorIntf * create (TextStream &ts, const QCString &relPath)
TextGeneratorIntf * create (TextStream &ts, const QCString &relPath)
Static Public Member Functions
static TextGeneratorFactory * instance ()
static TextGeneratorFactory * instance ()
Private Member Functions
TextGeneratorFactory ()=default
virtual ~TextGeneratorFactory ()=default
TextGeneratorFactory ()=default
virtual ~TextGeneratorFactory ()=default
Detailed Description
Definition at line 3532 of file context.cpp.
Constructor & Destructor Documentation
TextGeneratorFactory() [1/2]
TextGeneratorFactory::TextGeneratorFactory () [private], [default]
Referenced by instance().
 TextGeneratorFactory() [1/2]
virtual TextGeneratorFactory::~TextGeneratorFactory () [private], [virtual], [default]
TextGeneratorFactory() [2/2]
TextGeneratorFactory::TextGeneratorFactory () [private], [default]
 TextGeneratorFactory() [2/2]
virtual TextGeneratorFactory::~TextGeneratorFactory () [private], [virtual], [default]
Member Function Documentation
create() [1/2]
TextGeneratorIntf * TextGeneratorFactory::create (TextStream & ts, const QCString & relPath) [inline]
Definition at line 3540 of file context.cpp.
    {
      switch (g_globals.outputFormat)
      {
        case ContextOutputFormat_Html:
          return new TextGeneratorHtml(ts,relPath);
        case ContextOutputFormat_Latex:
          return new TextGeneratorLatex(ts);
        default:
          break;
      }
      return 0;
    }
References ContextOutputFormat_Html, ContextOutputFormat_Latex, g_globals, and ContextGlobals::outputFormat.
Referenced by createLinkedText().
create() [2/2]
TextGeneratorIntf * TextGeneratorFactory::create (TextStream & ts, const QCString & relPath) [inline]
Definition at line 3540 of file context.cpp.
    {
      switch (g_globals.outputFormat)
      {
        case ContextOutputFormat_Html:
          return new TextGeneratorHtml(ts,relPath);
        case ContextOutputFormat_Latex:
          return new TextGeneratorLatex(ts);
        default:
          break;
      }
      return 0;
    }
References ContextOutputFormat_Html, ContextOutputFormat_Latex, g_globals, and ContextGlobals::outputFormat.
instance() [1/2]
static TextGeneratorFactory * TextGeneratorFactory::instance () [inline], [static]
Definition at line 3535 of file context.cpp.
    {
      static TextGeneratorFactory *instance = new TextGeneratorFactory;
      return instance;
    }
References instance(), and TextGeneratorFactory().
Referenced by createLinkedText(), and instance().
instance() [2/2]
static TextGeneratorFactory * TextGeneratorFactory::instance () [inline], [static]
Definition at line 3535 of file context.cpp.
    {
      static TextGeneratorFactory *instance = new TextGeneratorFactory;
      return instance;
    }
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp