DotGroupCollaboration Class Reference
#include <dotgroupcollaboration.h>
Classes
struct Edge
struct Link
Public Member Functions
DotGroupCollaboration (const GroupDef *gd)
~DotGroupCollaboration ()
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
bool isTrivial () const
DotGroupCollaboration (const GroupDef *gd)
~DotGroupCollaboration ()
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
bool isTrivial () const
Protected Member Functions
virtual QCString getBaseName () const
virtual QCString getMapLabel () const
virtual void computeTheGraph ()
virtual QCString getBaseName () const
virtual QCString getMapLabel () const
virtual void computeTheGraph ()
Private Types
enum EdgeType {
tmember = 0
, tclass
, tnamespace
, tfile
,
tpages
, tdir
, thierarchy
, tmember = 0
,
tclass
, tnamespace
, tfile
, tpages
,
tdir
, thierarchy
 }
enum EdgeType {
tmember = 0
, tclass
, tnamespace
, tfile
,
tpages
, tdir
, thierarchy
, tmember = 0
,
tclass
, tnamespace
, tfile
, tpages
,
tdir
, thierarchy
 }
Private Member Functions
void buildGraph (const GroupDef *gd)
void addCollaborationMember (const Definition *def, QCString &url, EdgeType eType)
void addMemberList (class MemberList *ml)
void writeGraphHeader (TextStream &t, const QCString &title) const
Edge * addEdge (DotNode *_pNStart, DotNode *_pNEnd, EdgeType _eType, const QCString &_label, const QCString &_url)
void buildGraph (const GroupDef *gd)
void addCollaborationMember (const Definition *def, QCString &url, EdgeType eType)
void addMemberList (class MemberList *ml)
void writeGraphHeader (TextStream &t, const QCString &title) const
Edge * addEdge (DotNode *_pNStart, DotNode *_pNEnd, EdgeType _eType, const QCString &_label, const QCString &_url)
Private Attributes
DotNode * m_rootNode
DotNodeMap m_usedNodes
QCString m_diskName
std::vector< std::unique_ptr< Edge > > m_edges
Additional Inherited Members
Detailed Description
Representation of a group collaboration graph
Definition at line 28 of file dotgroupcollaboration.h.
Member Enumeration Documentation
EdgeType [1/2]
enum DotGroupCollaboration::EdgeType [private]
Enumerator
tmember
tclass
tnamespace
tfile
tpages
tdir
thierarchy
tmember
tclass
tnamespace
tfile
tpages
tdir
thierarchy
Definition at line 44 of file dotgroupcollaboration.h.
    {
      tmember = 0,
      tclass,
      tnamespace,
      tfile,
      tpages,
      tdir,
      thierarchy
    };
EdgeType [2/2]
enum DotGroupCollaboration::EdgeType [private]
Enumerator
tmember
tclass
tnamespace
tfile
tpages
tdir
thierarchy
tmember
tclass
tnamespace
tfile
tpages
tdir
thierarchy
Definition at line 44 of file dotgroupcollaboration.h.
    {
      tmember = 0,
      tclass,
      tnamespace,
      tfile,
      tpages,
      tdir,
      thierarchy
    };
Constructor & Destructor Documentation
DotGroupCollaboration() [1/2]
DotGroupCollaboration::DotGroupCollaboration (const GroupDef * gd)
Definition at line 25 of file dotgroupcollaboration.cpp.
{
  QCString tmp_url = gd->getReference()+"$"+gd->getOutputFileBase();
  QCString tooltip = gd->briefDescriptionAsTooltip();
  m_rootNode = new DotNode(getNextNodeNumber(), gd->groupTitle(), tooltip, tmp_url, TRUE);
  m_rootNode->markAsVisible();
  m_usedNodes.insert(std::make_pair(gd->name().str(), m_rootNode));
  m_diskName = gd->getOutputFileBase();
  buildGraph(gd);
}
References Definition::briefDescriptionAsTooltip(), buildGraph(), DotGraph::getNextNodeNumber(), GroupDef::getOutputFileBase(), Definition::getReference(), GroupDef::groupTitle(), m_diskName, m_rootNode, m_usedNodes, DotNode::markAsVisible(), Definition::name(), QCString::str(), and TRUE.
 DotGroupCollaboration() [1/2]
DotGroupCollaboration::~DotGroupCollaboration ()
Definition at line 38 of file dotgroupcollaboration.cpp.
{
  // delete all created Nodes saved in m_usedNodes map
  for (const auto &kv : m_usedNodes)
  {
    delete kv.second;
  }
}
References m_usedNodes.
DotGroupCollaboration() [2/2]
DotGroupCollaboration::DotGroupCollaboration (const GroupDef * gd)
 DotGroupCollaboration() [2/2]
DotGroupCollaboration::~DotGroupCollaboration ()
Member Function Documentation
addCollaborationMember() [1/2]
void DotGroupCollaboration::addCollaborationMember (const Definition * def, QCString & url, EdgeType eType) [private]
Definition at line 179 of file dotgroupcollaboration.cpp.
{
  // Create group nodes
  QCString tmp_str;
  for (const auto &d : def->partOfGroups())
  {
    auto it = m_usedNodes.find(d->name().str());
    DotNode* nnode = it!=m_usedNodes.end() ? it->second : 0;
    if (nnode != m_rootNode)
    {
      if (nnode==0)
      { // add node
        tmp_str = d->getReference()+"$"+d->getOutputFileBase();
        QCString tooltip = d->briefDescriptionAsTooltip();
        nnode = new DotNode(getNextNodeNumber(), d->groupTitle(), tooltip, tmp_str);
        nnode->markAsVisible();
        m_usedNodes.insert(std::make_pair(d->name().str(), nnode));
      }
      tmp_str = def->qualifiedName();
      addEdge(m_rootNode, nnode, eType, tmp_str, url);
    }
  }
}
References addEdge(), DotGraph::getNextNodeNumber(), m_rootNode, m_usedNodes, DotNode::markAsVisible(), Definition::partOfGroups(), Definition::qualifiedName(), and setup::url.
Referenced by addMemberList(), and buildGraph().
addCollaborationMember() [2/2]
void DotGroupCollaboration::addCollaborationMember (const Definition * def, QCString & url, EdgeType eType) [private]
addEdge() [1/2]
DotGroupCollaboration::Edge * DotGroupCollaboration::addEdge (DotNode * _pNStart, DotNode * _pNEnd, EdgeType _eType, const QCString & _label, const QCString & _url) [private]
Definition at line 155 of file dotgroupcollaboration.cpp.
{
  // search a existing link.
  auto it = std::find_if(m_edges.begin(),m_edges.end(),
      [&_pNStart,&_pNEnd,&_eType](const auto &edge)
      { return edge->pNStart==_pNStart && edge->pNEnd==_pNEnd && edge->eType==_eType; });
  if (it==m_edges.end()) // new link
  {
    m_edges.emplace_back(std::make_unique<Edge>(_pNStart,_pNEnd,_eType));
    it = m_edges.end()-1;
  }
  if (!_label.isEmpty()) // add label
  {
    (*it)->links.emplace_back(_label,_url);
  }
  // return found or added edge
  return (*it).get();
}
References QCString::isEmpty(), and m_edges.
Referenced by addCollaborationMember(), and buildGraph().
addEdge() [2/2]
Edge * DotGroupCollaboration::addEdge (DotNode * _pNStart, DotNode * _pNEnd, EdgeType _eType, const QCString & _label, const QCString & _url) [private]
addMemberList() [1/2]
void DotGroupCollaboration::addMemberList (class MemberList * ml) [private]
Definition at line 144 of file dotgroupcollaboration.cpp.
{
  if (ml==0 || ml->empty()) return;
  for (const auto &def : *ml)
  {
    QCString tmp_url = def->getReference()+"$"+addHtmlExtensionIfMissing(def->getOutputFileBase());
      +"#"+def->anchor();
    addCollaborationMember(def, tmp_url, DotGroupCollaboration::tmember);
  }
}
References addCollaborationMember(), addHtmlExtensionIfMissing(), MemberVector::empty(), and tmember.
Referenced by buildGraph().
addMemberList() [2/2]
void DotGroupCollaboration::addMemberList (class MemberList * ml) [private]
buildGraph() [1/2]
void DotGroupCollaboration::buildGraph (const GroupDef * gd) [private]
Definition at line 47 of file dotgroupcollaboration.cpp.
{
  QCString tmp_url;
  //===========================
  // hierarchy.
  // Write parents
  for (const auto &d : gd->partOfGroups())
  {
    DotNode *nnode = 0;
    auto it = m_usedNodes.find(d->name().str());
    if (it==m_usedNodes.end())
    { // add node
      tmp_url = d->getReference()+"$"+d->getOutputFileBase();
      QCString tooltip = d->briefDescriptionAsTooltip();
      nnode = new DotNode(getNextNodeNumber(), d->groupTitle(), tooltip, tmp_url);
      nnode->markAsVisible();
      m_usedNodes.insert(std::make_pair(d->name().str(), nnode));
    }
    else
    {
      nnode = it->second;
    }
    tmp_url = "";
    addEdge(nnode, m_rootNode, DotGroupCollaboration::thierarchy, tmp_url, tmp_url);
  }
  // Add subgroups
  for (const auto &def : gd->getSubGroups())
  {
    DotNode *nnode = 0;
    auto it = m_usedNodes.find(def->name().str());
    if (it==m_usedNodes.end())
    { // add node
      tmp_url = def->getReference()+"$"+def->getOutputFileBase();
      QCString tooltip = def->briefDescriptionAsTooltip();
      nnode = new DotNode(getNextNodeNumber(), def->groupTitle(), tooltip, tmp_url);
      nnode->markAsVisible();
      m_usedNodes.insert(std::make_pair(def->name().str(), nnode));
    }
    else
    {
      nnode = it->second;
    }
    tmp_url = "";
    addEdge(m_rootNode, nnode, DotGroupCollaboration::thierarchy, tmp_url, tmp_url);
  }
  //=======================
  // Write collaboration
  // Add members
  addMemberList(gd->getMemberList(MemberListType_allMembersList));
  // Add classes
  for (const auto &def : gd->getClasses())
  {
    tmp_url = def->getReference()+"$"+addHtmlExtensionIfMissing(def->getOutputFileBase());
    if (!def->anchor().isEmpty())
    {
      tmp_url+="#"+def->anchor();
    }
    addCollaborationMember(def, tmp_url, DotGroupCollaboration::tclass);
  }
  // Add namespaces
  for (const auto &def : gd->getNamespaces())
  {
    tmp_url = def->getReference()+"$"+addHtmlExtensionIfMissing(def->getOutputFileBase());
    addCollaborationMember(def, tmp_url, DotGroupCollaboration::tnamespace);
  }
  // Add files
  for (const auto &def : gd->getFiles())
  {
    tmp_url = def->getReference()+"$"+addHtmlExtensionIfMissing(def->getOutputFileBase());
    addCollaborationMember(def, tmp_url, DotGroupCollaboration::tfile);
  }
  // Add pages
  for (const auto &def : gd->getPages())
  {
    tmp_url = def->getReference()+"$"+addHtmlExtensionIfMissing(def->getOutputFileBase());
    addCollaborationMember(def, tmp_url, DotGroupCollaboration::tpages);
  }
  // Add directories
  if (!gd->getDirs().empty())
  {
    for(const auto def : gd->getDirs())
    {
      tmp_url = def->getReference()+"$"+addHtmlExtensionIfMissing(def->getOutputFileBase());
      addCollaborationMember(def, tmp_url, DotGroupCollaboration::tdir);
    }
  }
}
References addCollaborationMember(), addEdge(), addHtmlExtensionIfMissing(), addMemberList(), GroupDef::getClasses(), GroupDef::getDirs(), GroupDef::getFiles(), GroupDef::getMemberList(), GroupDef::getNamespaces(), DotGraph::getNextNodeNumber(), GroupDef::getPages(), GroupDef::getSubGroups(), m_rootNode, m_usedNodes, DotNode::markAsVisible(), MemberListType_allMembersList, Definition::partOfGroups(), tclass, tdir, tfile, thierarchy, tnamespace, and tpages.
Referenced by DotGroupCollaboration().
buildGraph() [2/2]
void DotGroupCollaboration::buildGraph (const GroupDef * gd) [private]
computeTheGraph() [1/2]
void DotGroupCollaboration::computeTheGraph () [protected], [virtual]
Implements DotGraph.
Definition at line 209 of file dotgroupcollaboration.cpp.
{
  TextStream md5stream;
  writeGraphHeader(md5stream,m_rootNode->label());
  // clean write flags
  for (const auto &kv : m_usedNodes)
  {
    kv.second->clearWriteFlag();
  }
  // write other nodes.
  for (const auto &kv : m_usedNodes)
  {
    kv.second->write(md5stream,Inheritance,m_graphFormat,TRUE,FALSE,FALSE);
  }
  // write edges
  for (const auto &edge : m_edges)
  {
    edge->write(md5stream);
  }
  writeGraphFooter(md5stream);
  m_theGraph = md5stream.str();
}
References FALSE, Inheritance, DotNode::label(), m_edges, DotGraph::m_graphFormat, m_rootNode, DotGraph::m_theGraph, m_usedNodes, TextStream::str(), TRUE, DotGraph::writeGraphFooter(), and writeGraphHeader().
computeTheGraph() [2/2]
virtual void DotGroupCollaboration::computeTheGraph () [protected], [virtual]
Implements DotGraph.
getBaseName() [1/2]
QCString DotGroupCollaboration::getBaseName () const [protected], [virtual]
Implements DotGraph.
Definition at line 204 of file dotgroupcollaboration.cpp.
{
  return m_diskName;
}
References m_diskName.
getBaseName() [2/2]
virtual QCString DotGroupCollaboration::getBaseName () const [protected], [virtual]
Implements DotGraph.
getMapLabel() [1/2]
QCString DotGroupCollaboration::getMapLabel () const [protected], [virtual]
Implements DotGraph.
Definition at line 237 of file dotgroupcollaboration.cpp.
{
  return escapeCharsInString(m_baseName, FALSE);
}
References escapeCharsInString(), FALSE, and DotGraph::m_baseName.
getMapLabel() [2/2]
virtual QCString DotGroupCollaboration::getMapLabel () const [protected], [virtual]
Implements DotGraph.
isTrivial() [1/2]
bool DotGroupCollaboration::isTrivial () const
Definition at line 312 of file dotgroupcollaboration.cpp.
{
  return m_usedNodes.size() <= 1;
}
References m_usedNodes.
Referenced by GroupDefImpl::writeGroupGraph().
isTrivial() [2/2]
bool DotGroupCollaboration::isTrivial () const
writeGraph() [1/2]
QCString DotGroupCollaboration::writeGraph (TextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1)
Definition at line 242 of file dotgroupcollaboration.cpp.
{
  m_doNotAddImageToIndex = textFormat!=EOF_Html;
  return DotGraph::writeGraph(t, graphFormat, textFormat, path, fileName, relPath, generateImageMap, graphId);
}
References EOF_Html, DotGraph::m_doNotAddImageToIndex, and DotGraph::writeGraph().
writeGraph() [2/2]
QCString DotGroupCollaboration::writeGraph (TextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1)
writeGraphHeader() [1/2]
void DotGroupCollaboration::writeGraphHeader (TextStream & t, const QCString & title) const [private]
Definition at line 317 of file dotgroupcollaboration.cpp.
{
  DotGraph::writeGraphHeader(t, title);
  t << " rankdir=LR;\n";
}
References DotGraph::writeGraphHeader().
Referenced by computeTheGraph().
writeGraphHeader() [2/2]
void DotGroupCollaboration::writeGraphHeader (TextStream & t, const QCString & title) const [private]
Member Data Documentation
m_diskName
QCString DotGroupCollaboration::m_diskName [private]
Definition at line 84 of file dotgroupcollaboration.h.
Referenced by DotGroupCollaboration(), and getBaseName().
m_edges
std::vector< std::unique_ptr< Edge > > DotGroupCollaboration::m_edges [private]
Definition at line 85 of file dotgroupcollaboration.h.
Referenced by addEdge(), and computeTheGraph().
m_rootNode
DotNode * DotGroupCollaboration::m_rootNode [private]
Definition at line 82 of file dotgroupcollaboration.h.
Referenced by addCollaborationMember(), buildGraph(), computeTheGraph(), and DotGroupCollaboration().
m_usedNodes
DotNodeMap DotGroupCollaboration::m_usedNodes [private]
Definition at line 83 of file dotgroupcollaboration.h.
Referenced by addCollaborationMember(), buildGraph(), computeTheGraph(), DotGroupCollaboration(), isTrivial(), and ~DotGroupCollaboration().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dotgroupcollaboration.h
doxygen/src/dotgroupcollaboration.h
doxygen/build/doxygen/src/dotgroupcollaboration.cpp
doxygen/src/dotgroupcollaboration.cpp