DocIntf Class Reference
#include <docintf.h>
Public Member Functions
virtual ~DocIntf ()
virtual void setHeader (const char *header)=0
virtual void add (const char *name, const char *docs)=0
virtual ~DocIntf ()
virtual void setHeader (const char *header)=0
virtual void add (const char *name, const char *docs)=0
Detailed Description
Definition at line 16 of file docintf.h.
Constructor & Destructor Documentation
 DocIntf() [1/2]
virtual DocIntf::~DocIntf () [inline], [virtual]
Definition at line 19 of file docintf.h.
{}
 DocIntf() [2/2]
virtual DocIntf::~DocIntf () [inline], [virtual]
Definition at line 19 of file docintf.h.
{}
Member Function Documentation
add() [1/2]
virtual void DocIntf::add (const char * name, const char * docs) [pure virtual]
Implemented in Expert, and Expert.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [2/2]
virtual void DocIntf::add (const char * name, const char * docs) [pure virtual]
Implemented in Expert, and Expert.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
setHeader() [1/2]
virtual void DocIntf::setHeader (const char * header) [pure virtual]
Implemented in Expert, and Expert.
setHeader() [2/2]
virtual void DocIntf::setHeader (const char * header) [pure virtual]
Implemented in Expert, and Expert.
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/docintf.h
doxygen/build/doxygen/addon/doxywizard/docintf.h