TemplateEngine::Private Class Reference
Private data of the template engine.
Classes
class IncludeEntry
Public Member Functions
Private (TemplateEngine *engine)
~Private ()
Template * loadByName (const QCString &fileName, int line)
void unload (Template *)
void enterBlock (const QCString &fileName, const QCString &blockName, int line)
void leaveBlock ()
void printIncludeContext (const QCString &fileName, int line) const
void setOutputExtension (const QCString &extension)
QCString outputExtension () const
void setTemplateDir (const QCString &dirName)
Private (TemplateEngine *engine)
~Private ()
Template * loadByName (const QCString &fileName, int line)
void unload (Template *)
void enterBlock (const QCString &fileName, const QCString &blockName, int line)
void leaveBlock ()
void printIncludeContext (const QCString &fileName, int line) const
void setOutputExtension (const QCString &extension)
QCString outputExtension () const
void setTemplateDir (const QCString &dirName)
Private Attributes
std::unordered_map< std::string, std::unique_ptr< Template > > m_templateCache
TemplateEngine * m_engine = 0
std::vector< IncludeEntry > m_includeStack
QCString m_extension
QCString m_templateDirName
Detailed Description
Private data of the template engine.
Definition at line 5225 of file template.cpp.
Constructor & Destructor Documentation
Private() [1/2]
TemplateEngine::Private::Private (TemplateEngine * engine) [inline]
Definition at line 5245 of file template.cpp.
                                    : m_engine(engine)
    {
      //printf("%p:TemplateEngine::Private::Private()\n",(void*)this);
    }
 Private() [1/2]
TemplateEngine::Private::~Private () [inline]
Definition at line 5249 of file template.cpp.
    {
      //printf("%p:TemplateEngine::Private::~Private()\n",(void*)this);
    }
Private() [2/2]
TemplateEngine::Private::Private (TemplateEngine * engine) [inline]
Definition at line 5245 of file template.cpp.
                                    : m_engine(engine)
    {
      //printf("%p:TemplateEngine::Private::Private()\n",(void*)this);
    }
 Private() [2/2]
TemplateEngine::Private::~Private () [inline]
Definition at line 5249 of file template.cpp.
    {
      //printf("%p:TemplateEngine::Private::~Private()\n",(void*)this);
    }
Member Function Documentation
enterBlock() [1/2]
void TemplateEngine::Private::enterBlock (const QCString & fileName, const QCString & blockName, int line) [inline]
Definition at line 5304 of file template.cpp.
    {
      //for (int i=0;i<m_indent;i++) printf(" ");
      //m_indent++;
      //printf("enterBlock(%s,%s,%d) {\n",qPrint(fileName),qPrint(blockName),line);
      m_includeStack.emplace_back(IncludeEntry::Block,fileName,blockName,line);
    }
References TemplateEngine::Private::IncludeEntry::Block, and m_includeStack.
enterBlock() [2/2]
void TemplateEngine::Private::enterBlock (const QCString & fileName, const QCString & blockName, int line) [inline]
Definition at line 5304 of file template.cpp.
    {
      //for (int i=0;i<m_indent;i++) printf(" ");
      //m_indent++;
      //printf("enterBlock(%s,%s,%d) {\n",qPrint(fileName),qPrint(blockName),line);
      m_includeStack.emplace_back(IncludeEntry::Block,fileName,blockName,line);
    }
References TemplateEngine::Private::IncludeEntry::Block, and m_includeStack.
leaveBlock() [1/2]
void TemplateEngine::Private::leaveBlock () [inline]
Definition at line 5312 of file template.cpp.
    {
      //m_indent--;
      //for (int i=0;i<m_indent;i++) printf(" ");
      //printf("}\n");
      m_includeStack.pop_back();
    }
References m_includeStack.
leaveBlock() [2/2]
void TemplateEngine::Private::leaveBlock () [inline]
Definition at line 5312 of file template.cpp.
    {
      //m_indent--;
      //for (int i=0;i<m_indent;i++) printf(" ");
      //printf("}\n");
      m_includeStack.pop_back();
    }
References m_includeStack.
loadByName() [1/2]
Template * TemplateEngine::Private::loadByName (const QCString & fileName, int line) [inline]
Definition at line 5253 of file template.cpp.
    {
      //for (int i=0;i<m_indent;i++) printf(" ");
      //m_indent++;
      //printf("loadByName(%s,%d) {\n",qPrint(fileName),line);
      m_includeStack.emplace_back(IncludeEntry::Template,fileName,QCString(),line);
      auto kv = m_templateCache.find(fileName.str());
      if (kv==m_templateCache.end()) // first time template is referenced
      {
        QCString filePath = m_templateDirName+"/"+fileName;
        std::ifstream f(filePath.str(),std::ifstream::in | std::ifstream::binary);
        if (f.is_open()) // read template from disk
        {
          FileInfo fi(filePath.str());
          size_t size=fi.size();
          QCString data(size+1);
          f.read(data.rawData(),size);
          if (!f.fail())
          {
            kv = m_templateCache.insert(
                std::make_pair(fileName.str(),
                  std::make_unique<TemplateImpl>(m_engine,filePath,data,m_extension))).first;
          }
        }
        else // fallback to default built-in template
        {
          const QCString data = ResourceMgr::instance().getAsString(fileName);
          if (!data.isEmpty())
          {
            kv = m_templateCache.insert(
                std::make_pair(fileName.str(),
                  std::make_unique<TemplateImpl>(m_engine,fileName,data,m_extension))).first;
          }
          else
          {
            err("Could not open template file %s\n",qPrint(fileName));
          }
        }
      }
      return kv!=m_templateCache.end() ? kv->second.get() : 0;
    }
References data, err(), f, ResourceMgr::getAsString(), ResourceMgr::instance(), m_engine, m_extension, m_includeStack, m_templateCache, m_templateDirName, qPrint(), size, FileInfo::size(), QCString::str(), and TemplateEngine::Private::IncludeEntry::Template.
loadByName() [2/2]
Template * TemplateEngine::Private::loadByName (const QCString & fileName, int line) [inline]
Definition at line 5253 of file template.cpp.
    {
      //for (int i=0;i<m_indent;i++) printf(" ");
      //m_indent++;
      //printf("loadByName(%s,%d) {\n",qPrint(fileName),line);
      m_includeStack.emplace_back(IncludeEntry::Template,fileName,QCString(),line);
      auto kv = m_templateCache.find(fileName.str());
      if (kv==m_templateCache.end()) // first time template is referenced
      {
        QCString filePath = m_templateDirName+"/"+fileName;
        std::ifstream f(filePath.str(),std::ifstream::in | std::ifstream::binary);
        if (f.is_open()) // read template from disk
        {
          FileInfo fi(filePath.str());
          size_t size=fi.size();
          QCString data(size+1);
          f.read(data.rawData(),size);
          if (!f.fail())
          {
            kv = m_templateCache.insert(
                std::make_pair(fileName.str(),
                  std::make_unique<TemplateImpl>(m_engine,filePath,data,m_extension))).first;
          }
        }
        else // fallback to default built-in template
        {
          const QCString data = ResourceMgr::instance().getAsString(fileName);
          if (!data.isEmpty())
          {
            kv = m_templateCache.insert(
                std::make_pair(fileName.str(),
                  std::make_unique<TemplateImpl>(m_engine,fileName,data,m_extension))).first;
          }
          else
          {
            err("Could not open template file %s\n",qPrint(fileName));
          }
        }
      }
      return kv!=m_templateCache.end() ? kv->second.get() : 0;
    }
References data, err(), f, ResourceMgr::getAsString(), ResourceMgr::instance(), m_engine, m_extension, m_includeStack, m_templateCache, m_templateDirName, qPrint(), size, FileInfo::size(), QCString::str(), and TemplateEngine::Private::IncludeEntry::Template.
outputExtension() [1/2]
QCString TemplateEngine::Private::outputExtension () const [inline]
Definition at line 5348 of file template.cpp.
    {
      return m_extension;
    }
References m_extension.
outputExtension() [2/2]
QCString TemplateEngine::Private::outputExtension () const [inline]
Definition at line 5348 of file template.cpp.
    {
      return m_extension;
    }
References m_extension.
printIncludeContext() [1/2]
void TemplateEngine::Private::printIncludeContext (const QCString & fileName, int line) const [inline]
Definition at line 5320 of file template.cpp.
    {
      auto it = m_includeStack.rbegin();
      while (it!=m_includeStack.rend())
      {
        const IncludeEntry &ie = *it;
        ++it;
        const IncludeEntry *next = it!=m_includeStack.rend() ? &(*it) : 0;
        if (ie.type()==IncludeEntry::Template)
        {
          if (next)
          {
            warn(fileName,line," inside template '%s' included from template '%s' at line %d",qPrint(ie.fileName()),qPrint(next->fileName()),ie.line());
          }
        }
        else // ie.type()==IncludeEntry::Block
        {
          warn(fileName,line," included by block '%s' inside template '%s' at line %d",qPrint(ie.blockName()),
              qPrint(ie.fileName()),ie.line());
        }
      }
    }
References TemplateEngine::Private::IncludeEntry::blockName(), TemplateEngine::Private::IncludeEntry::fileName(), TemplateEngine::Private::IncludeEntry::line(), m_includeStack, qPrint(), TemplateEngine::Private::IncludeEntry::Template, TemplateEngine::Private::IncludeEntry::type(), and warn().
printIncludeContext() [2/2]
void TemplateEngine::Private::printIncludeContext (const QCString & fileName, int line) const [inline]
Definition at line 5320 of file template.cpp.
    {
      auto it = m_includeStack.rbegin();
      while (it!=m_includeStack.rend())
      {
        const IncludeEntry &ie = *it;
        ++it;
        const IncludeEntry *next = it!=m_includeStack.rend() ? &(*it) : 0;
        if (ie.type()==IncludeEntry::Template)
        {
          if (next)
          {
            warn(fileName,line," inside template '%s' included from template '%s' at line %d",qPrint(ie.fileName()),qPrint(next->fileName()),ie.line());
          }
        }
        else // ie.type()==IncludeEntry::Block
        {
          warn(fileName,line," included by block '%s' inside template '%s' at line %d",qPrint(ie.blockName()),
              qPrint(ie.fileName()),ie.line());
        }
      }
    }
References m_includeStack, qPrint(), TemplateEngine::Private::IncludeEntry::Template, and warn().
setOutputExtension() [1/2]
void TemplateEngine::Private::setOutputExtension (const QCString & extension) [inline]
Definition at line 5343 of file template.cpp.
    {
      m_extension = extension;
    }
References m_extension.
setOutputExtension() [2/2]
void TemplateEngine::Private::setOutputExtension (const QCString & extension) [inline]
Definition at line 5343 of file template.cpp.
    {
      m_extension = extension;
    }
References m_extension.
setTemplateDir() [1/2]
void TemplateEngine::Private::setTemplateDir (const QCString & dirName) [inline]
Definition at line 5353 of file template.cpp.
    {
      m_templateDirName = dirName;
    }
References m_templateDirName.
setTemplateDir() [2/2]
void TemplateEngine::Private::setTemplateDir (const QCString & dirName) [inline]
Definition at line 5353 of file template.cpp.
    {
      m_templateDirName = dirName;
    }
References m_templateDirName.
unload() [1/2]
void TemplateEngine::Private::unload (Template *) [inline]
Definition at line 5295 of file template.cpp.
    {
      //(void)t;
      //m_indent--;
      //for (int i=0;i<m_indent;i++) printf(" ");
      //printf("}\n");
      m_includeStack.pop_back();
    }
References m_includeStack.
unload() [2/2]
void TemplateEngine::Private::unload (Template *) [inline]
Definition at line 5295 of file template.cpp.
    {
      //(void)t;
      //m_indent--;
      //for (int i=0;i<m_indent;i++) printf(" ");
      //printf("}\n");
      m_includeStack.pop_back();
    }
References m_includeStack.
Member Data Documentation
m_engine
TemplateEngine * TemplateEngine::Private::m_engine = 0 [private]
Definition at line 5361 of file template.cpp.
Referenced by loadByName().
m_extension
QCString TemplateEngine::Private::m_extension [private]
Definition at line 5363 of file template.cpp.
Referenced by loadByName(), outputExtension(), and setOutputExtension().
m_includeStack
std::vector< IncludeEntry > TemplateEngine::Private::m_includeStack [private]
Definition at line 5362 of file template.cpp.
Referenced by enterBlock(), leaveBlock(), loadByName(), printIncludeContext(), and unload().
m_templateCache
std::unordered_map< std::string, std::unique_ptr< Template > > TemplateEngine::Private::m_templateCache [private]
Definition at line 5359 of file template.cpp.
Referenced by loadByName().
m_templateDirName
QCString TemplateEngine::Private::m_templateDirName [private]
Definition at line 5364 of file template.cpp.
Referenced by loadByName(), and setTemplateDir().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp