FilterListSort Class Reference
The implementation of the `listsort` filter.
Classes
struct ListElem
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &args)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &args)
Static Private Member Functions
static QCString determineSortKey (const TemplateStructIntfPtr s, const QCString &arg)
static QCString determineSortKey (const TemplateStructIntfPtr s, const QCString &arg)
Detailed Description
The implementation of the `listsort` filter.
Definition at line 1064 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterListSort::apply (const TemplateVariant & v, const TemplateVariant & args) [inline], [static]
Definition at line 1073 of file template.cpp.
    {
      if (v.isList() && args.isString())
      {
        //printf("FilterListSort::apply: v=%s args=%s\n",qPrint(v.toString()),qPrint(args.toString()));
        TemplateListIntfPtr list = v.toList();
        if (list)
        {
          TemplateListIntf::ConstIteratorPtr it = list->createIterator();
          TemplateVariant item;
          TemplateListPtr result = TemplateList::alloc();
          // create list of items based on v using the data in args as a sort key
          using SortList = std::vector<ListElem>;
          SortList sortList;
          sortList.reserve(v.toList()->count());
          for (it->toFirst();(it->current(item));it->toNext())
          {
            TemplateStructIntfPtr s = item.toStruct();
            if (s)
            {
              QCString sortKey = determineSortKey(s,args.toString());
              sortList.emplace_back(sortKey,item);
              //printf("sortKey=%s\n",qPrint(sortKey));
            }
          }
          // sort the list
          std::sort(sortList.begin(),
              sortList.end(),
              [](const auto &lhs,const auto &rhs) { return lhs.key < rhs.key; });
          // add sorted items to the result list
          for (const auto &elem : sortList)
          {
            result->append(elem.value);
          }
          return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(result));
        }
      }
      return v;
    }
References TemplateList::alloc(), determineSortKey(), TemplateVariant::isList(), TemplateVariant::isString(), s, TemplateVariant::toList(), TemplateVariant::toString(), and TemplateVariant::toStruct().
apply() [2/2]
static TemplateVariant FilterListSort::apply (const TemplateVariant & v, const TemplateVariant & args) [inline], [static]
Definition at line 1073 of file template.cpp.
    {
      if (v.isList() && args.isString())
      {
        //printf("FilterListSort::apply: v=%s args=%s\n",qPrint(v.toString()),qPrint(args.toString()));
        TemplateListIntfPtr list = v.toList();
        if (list)
        {
          TemplateListIntf::ConstIteratorPtr it = list->createIterator();
          TemplateVariant item;
          TemplateListPtr result = TemplateList::alloc();
          // create list of items based on v using the data in args as a sort key
          using SortList = std::vector<ListElem>;
          SortList sortList;
          sortList.reserve(v.toList()->count());
          for (it->toFirst();(it->current(item));it->toNext())
          {
            TemplateStructIntfPtr s = item.toStruct();
            if (s)
            {
              QCString sortKey = determineSortKey(s,args.toString());
              sortList.emplace_back(sortKey,item);
              //printf("sortKey=%s\n",qPrint(sortKey));
            }
          }
          // sort the list
          std::sort(sortList.begin(),
              sortList.end(),
              [](const auto &lhs,const auto &rhs) { return lhs.key < rhs.key; });
          // add sorted items to the result list
          for (const auto &elem : sortList)
          {
            result->append(elem.value);
          }
          return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(result));
        }
      }
      return v;
    }
References TemplateList::alloc(), TemplateVariant::isList(), TemplateVariant::isString(), s, TemplateVariant::toList(), TemplateVariant::toString(), and TemplateVariant::toStruct().
determineSortKey() [1/2]
static QCString FilterListSort::determineSortKey (const TemplateStructIntfPtr s, const QCString & arg) [inline], [static], [private]
Definition at line 1118 of file template.cpp.
    {
      int i,p=0;
      QCString result;
      while ((i=arg.find("{{",p))!=-1)
      {
        result+=arg.mid(p,i-p);
        int j=arg.find("}}",i+2);
        if (j!=-1)
        {
          QCString var = arg.mid(i+2,j-i-2);
          TemplateVariant val=s->get(var);
          //printf("found argument %s value=%s\n",qPrint(var),qPrint(val.toString()));
          result+=val.toString();
          p=j+2;
        }
        else
        {
          p=i+1;
        }
      }
      result+=arg.right(arg.length()-p);
      return result;
    }
References QCString::find(), QCString::length(), QCString::mid(), p, QCString::right(), s, testsqlite3::val, and var.
Referenced by apply().
determineSortKey() [2/2]
static QCString FilterListSort::determineSortKey (const TemplateStructIntfPtr s, const QCString & arg) [inline], [static], [private]
Definition at line 1118 of file template.cpp.
    {
      int i,p=0;
      QCString result;
      while ((i=arg.find("{{",p))!=-1)
      {
        result+=arg.mid(p,i-p);
        int j=arg.find("}}",i+2);
        if (j!=-1)
        {
          QCString var = arg.mid(i+2,j-i-2);
          TemplateVariant val=s->get(var);
          //printf("found argument %s value=%s\n",qPrint(var),qPrint(val.toString()));
          result+=val.toString();
          p=j+2;
        }
        else
        {
          p=i+1;
        }
      }
      result+=arg.right(arg.length()-p);
      return result;
    }
References QCString::find(), QCString::length(), QCString::mid(), TemplateImmutableList::p, QCString::right(), s, testsqlite3::val, and var.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp