DocHtmlCell Class Reference
#include <docnode.h>
Public Types
enum Alignment {
Left
, Right
, Center
, Left
,
Right
, Center
 }
enum Valignment {
Top
, Middle
, Bottom
, Top
,
Middle
, Bottom
 }
enum Alignment {
Left
, Right
, Center
, Left
,
Right
, Center
 }
enum Valignment {
Top
, Middle
, Bottom
, Top
,
Middle
, Bottom
 }
Public Member Functions
DocHtmlCell (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, bool isHeading)
bool isHeading () const
bool isFirst () const
bool isLast () const
void markFirst (bool v=TRUE)
void markLast (bool v=TRUE)
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
int parseXml (DocNodeVariant *)
uint rowIndex () const
uint columnIndex () const
uint rowSpan () const
uint colSpan () const
Alignment alignment () const
Valignment valignment () const
DocHtmlCell (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, bool isHeading)
bool isHeading () const
bool isFirst () const
bool isLast () const
void markFirst (bool v=TRUE)
void markLast (bool v=TRUE)
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
int parseXml (DocNodeVariant *)
uint rowIndex () const
uint columnIndex () const
uint rowSpan () const
uint colSpan () const
Alignment alignment () const
Valignment valignment () const
Private Member Functions
void setRowIndex (uint idx)
void setColumnIndex (uint idx)
void setRowIndex (uint idx)
void setColumnIndex (uint idx)
Private Attributes
bool m_isHeading = false
bool m_isFirst = false
bool m_isLast = false
HtmlAttribList m_attribs
uint m_rowIdx = static_cast<uint>(-1)
uint m_colIdx = static_cast<uint>(-1)
Friends
class DocHtmlTable
Additional Inherited Members
Detailed Description
Node representing a HTML table cell
Definition at line 1145 of file docnode.h.
Member Enumeration Documentation
Alignment [1/2]
enum DocHtmlCell::Alignment
Enumerator
Left
Right
Center
Left
Right
Center
Definition at line 1149 of file docnode.h.
{ Left, Right, Center };
Alignment [2/2]
enum DocHtmlCell::Alignment
Enumerator
Left
Right
Center
Left
Right
Center
Definition at line 1149 of file docnode.h.
{ Left, Right, Center };
Valignment [1/2]
enum DocHtmlCell::Valignment
Enumerator
Top
Middle
Bottom
Top
Middle
Bottom
Definition at line 1150 of file docnode.h.
{Top, Middle, Bottom};
Valignment [2/2]
enum DocHtmlCell::Valignment
Enumerator
Top
Middle
Bottom
Top
Middle
Bottom
Definition at line 1150 of file docnode.h.
{Top, Middle, Bottom};
Constructor & Destructor Documentation
DocHtmlCell() [1/2]
DocHtmlCell::DocHtmlCell (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, bool isHeading) [inline]
Definition at line 1151 of file docnode.h.
                                                                                                       :
       DocCompoundNode(parser,parent), m_isHeading(isHeading), m_attribs(attribs) {}
DocHtmlCell() [2/2]
DocHtmlCell::DocHtmlCell (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, bool isHeading) [inline]
Definition at line 1151 of file docnode.h.
                                                                                                       :
       DocCompoundNode(parser,parent), m_isHeading(isHeading), m_attribs(attribs) {}
Member Function Documentation
alignment() [1/2]
DocHtmlCell::Alignment DocHtmlCell::alignment () const
Definition at line 1721 of file docnode.cpp.
{
  for (const auto &attr : attribs())
  {
    QCString attrName = attr.name.lower();
    QCString attrValue = attr.value.lower();
    if (attrName=="align")
    {
      if (attrValue=="center")
        return Center;
      else if (attrValue=="right")
        return Right;
      else return Left;
    }
    else if (attrName=="class" && attrValue.startsWith("markdowntable"))
    {
      if (attrValue=="markdowntableheadcenter")
        return Center;
      else if (attrValue=="markdowntableheadright")
        return Right;
      else if (attrValue=="markdowntableheadleft")
        return Left;
      else if (attrValue=="markdowntableheadnone")
        return Center;
      else if (attrValue=="markdowntablebodycenter")
        return Center;
      else if (attrValue=="markdowntablebodyright")
        return Right;
      else if (attrValue=="markdowntablebodyleft")
        return Left;
      else if (attrValue=="markdowntablebodynone")
        return Left;
      else return Left;
    }
  }
  return Left;
}
References attribs(), Center, Left, QCString::lower(), Right, and QCString::startsWith().
alignment() [2/2]
Alignment DocHtmlCell::alignment () const
attribs() [1/2]
const HtmlAttribList & DocHtmlCell::attribs () const [inline]
Definition at line 1158 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by align(), alignment(), colSpan(), rowSpan(), and valignment().
attribs() [2/2]
const HtmlAttribList & DocHtmlCell::attribs () const [inline]
Definition at line 1158 of file docnode.h.
{ return m_attribs; }
References m_attribs.
colSpan() [1/2]
uint DocHtmlCell::colSpan () const
Definition at line 1709 of file docnode.cpp.
{
  for (const auto &attr : attribs())
  {
    if (attr.name.lower()=="colspan")
    {
      return std::max(1u,attr.value.toUInt());
    }
  }
  return 1;
}
References attribs().
Referenced by DocHtmlTable::computeTableGrid().
colSpan() [2/2]
uint DocHtmlCell::colSpan () const
columnIndex() [1/2]
uint DocHtmlCell::columnIndex () const [inline]
Definition at line 1162 of file docnode.h.
{ return m_colIdx; }
References m_colIdx.
columnIndex() [2/2]
uint DocHtmlCell::columnIndex () const [inline]
Definition at line 1162 of file docnode.h.
{ return m_colIdx; }
References m_colIdx.
isFirst() [1/2]
bool DocHtmlCell::isFirst () const [inline]
Definition at line 1154 of file docnode.h.
{ return m_isFirst; }
References m_isFirst.
Referenced by parse(), and parseXml().
isFirst() [2/2]
bool DocHtmlCell::isFirst () const [inline]
Definition at line 1154 of file docnode.h.
{ return m_isFirst; }
References m_isFirst.
isHeading() [1/2]
bool DocHtmlCell::isHeading () const [inline]
Definition at line 1153 of file docnode.h.
{ return m_isHeading; }
References m_isHeading.
Referenced by DocHtmlRow::isHeading().
isHeading() [2/2]
bool DocHtmlCell::isHeading () const [inline]
Definition at line 1153 of file docnode.h.
{ return m_isHeading; }
References m_isHeading.
isLast() [1/2]
bool DocHtmlCell::isLast () const [inline]
Definition at line 1155 of file docnode.h.
{ return m_isLast; }
References m_isLast.
isLast() [2/2]
bool DocHtmlCell::isLast () const [inline]
Definition at line 1155 of file docnode.h.
{ return m_isLast; }
References m_isLast.
markFirst() [1/2]
void DocHtmlCell::markFirst (bool v = TRUE) [inline]
Definition at line 1156 of file docnode.h.
{ m_isFirst=v; }
References m_isFirst.
Referenced by DocHtmlRow::parse(), and DocHtmlRow::parseXml().
markFirst() [2/2]
void DocHtmlCell::markFirst (bool v = TRUE) [inline]
Definition at line 1156 of file docnode.h.
{ m_isFirst=v; }
References m_isFirst.
markLast() [1/2]
void DocHtmlCell::markLast (bool v = TRUE) [inline]
Definition at line 1157 of file docnode.h.
{ m_isLast=v; }
References m_isLast.
Referenced by DocHtmlRow::parse(), and DocHtmlRow::parseXml().
markLast() [2/2]
void DocHtmlCell::markLast (bool v = TRUE) [inline]
Definition at line 1157 of file docnode.h.
{ m_isLast=v; }
References m_isLast.
parse() [1/2]
int DocHtmlCell::parse (DocNodeVariant * thisVariant)
Definition at line 1627 of file docnode.cpp.
{
  int retval=RetVal_OK;
  auto ns = AutoNodeStack(parser(),thisVariant);
  DBG(("DocHtmlCell::parse() start\n"));
  // parse one or more paragraphs
  bool isFirst=TRUE;
  DocPara *par=0;
  do
  {
    auto vDocPara = children().append<DocPara>(parser(),thisVariant);
    par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse(vDocPara);
    if (retval==TK_HTMLTAG)
    {
      int tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
      if (tagId==HTML_TD && parser()->context.token->endTag) // found </td> tag
      {
        retval=TK_NEWPARA; // ignore the tag
      }
      else if (tagId==HTML_TH && parser()->context.token->endTag) // found </th> tag
      {
        retval=TK_NEWPARA; // ignore the tag
      }
    }
  }
  while ((retval==TK_NEWPARA) || (retval==RetVal_EndParBlock));
  if (par) par->markLast();
  DBG(("DocHtmlCell::parse() end\n"));
  return retval;
}
References DocNodeList::append(), DocCompoundNode::children(), DocParser::context, DBG, TokenInfo::endTag, FALSE, DocNodeList::get_last(), HTML_TD, HTML_TH, Mappers::htmlTagMapper, isFirst(), Mapper::map(), DocPara::markFirst(), DocPara::markLast(), TokenInfo::name, DocPara::parse(), DocNode::parser(), RetVal_EndParBlock, RetVal_OK, TK_HTMLTAG, TK_NEWPARA, DocParserContext::token, and TRUE.
Referenced by DocHtmlRow::parse().
parse() [2/2]
int DocHtmlCell::parse (DocNodeVariant *)
parseXml() [1/2]
int DocHtmlCell::parseXml (DocNodeVariant * thisVariant)
Definition at line 1662 of file docnode.cpp.
{
  int retval=RetVal_OK;
  auto ns = AutoNodeStack(parser(),thisVariant);
  DBG(("DocHtmlCell::parseXml() start\n"));
  // parse one or more paragraphs
  bool isFirst=TRUE;
  DocPara *par=0;
  do
  {
    auto vDocPara = children().append<DocPara>(parser(),thisVariant);
    par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse(vDocPara);
    if (retval==TK_HTMLTAG)
    {
      int tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
      if (tagId==XML_ITEM && parser()->context.token->endTag) // found </item> tag
      {
        retval=TK_NEWPARA; // ignore the tag
      }
      else if (tagId==XML_DESCRIPTION && parser()->context.token->endTag) // found </description> tag
      {
        retval=TK_NEWPARA; // ignore the tag
      }
    }
  }
  while (retval==TK_NEWPARA);
  if (par) par->markLast();
  DBG(("DocHtmlCell::parseXml() end\n"));
  return retval;
}
References DocNodeList::append(), DocCompoundNode::children(), DocParser::context, DBG, TokenInfo::endTag, FALSE, DocNodeList::get_last(), Mappers::htmlTagMapper, isFirst(), Mapper::map(), DocPara::markFirst(), DocPara::markLast(), TokenInfo::name, DocPara::parse(), DocNode::parser(), RetVal_OK, TK_HTMLTAG, TK_NEWPARA, DocParserContext::token, TRUE, XML_DESCRIPTION, and XML_ITEM.
Referenced by DocHtmlRow::parseXml().
parseXml() [2/2]
int DocHtmlCell::parseXml (DocNodeVariant *)
rowIndex() [1/2]
uint DocHtmlCell::rowIndex () const [inline]
Definition at line 1161 of file docnode.h.
{ return m_rowIdx; }
References m_rowIdx.
rowIndex() [2/2]
uint DocHtmlCell::rowIndex () const [inline]
Definition at line 1161 of file docnode.h.
{ return m_rowIdx; }
References m_rowIdx.
rowSpan() [1/2]
uint DocHtmlCell::rowSpan () const
Definition at line 1697 of file docnode.cpp.
{
  for (const auto &attr : attribs())
  {
    if (attr.name.lower()=="rowspan")
    {
      return attr.value.toUInt();
    }
  }
  return 0;
}
References attribs().
Referenced by DocHtmlTable::computeTableGrid().
rowSpan() [2/2]
uint DocHtmlCell::rowSpan () const
setColumnIndex() [1/2]
void DocHtmlCell::setColumnIndex (uint idx) [inline], [private]
Definition at line 1170 of file docnode.h.
{ m_colIdx = idx; }
References m_colIdx.
Referenced by DocHtmlTable::computeTableGrid().
setColumnIndex() [2/2]
void DocHtmlCell::setColumnIndex (uint idx) [inline], [private]
Definition at line 1170 of file docnode.h.
{ m_colIdx = idx; }
References m_colIdx.
setRowIndex() [1/2]
void DocHtmlCell::setRowIndex (uint idx) [inline], [private]
Definition at line 1169 of file docnode.h.
{ m_rowIdx = idx; }
References m_rowIdx.
Referenced by DocHtmlTable::computeTableGrid().
setRowIndex() [2/2]
void DocHtmlCell::setRowIndex (uint idx) [inline], [private]
Definition at line 1169 of file docnode.h.
{ m_rowIdx = idx; }
References m_rowIdx.
valignment() [1/2]
DocHtmlCell::Valignment DocHtmlCell::valignment () const
Definition at line 1759 of file docnode.cpp.
{
  for (const auto &attr : attribs())
  {
    QCString attrName = attr.name.lower();
    QCString attrValue = attr.value.lower();
    if (attrName=="valign")
    {
      if (attrValue=="top")
        return Top;
      else if (attrValue=="bottom")
        return Bottom;
      else if (attrValue=="middle")
        return Middle;
      else return Middle;
    }
  }
  return Middle;
}
References attribs(), Bottom, QCString::lower(), Middle, and Top.
valignment() [2/2]
Valignment DocHtmlCell::valignment () const
Friends And Related Function Documentation
DocHtmlTable
DocHtmlTable [friend]
Definition at line 1147 of file docnode.h.
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlCell::m_attribs [private]
Definition at line 1174 of file docnode.h.
Referenced by attribs().
m_colIdx
uint DocHtmlCell::m_colIdx = static_cast<uint>(-1) [private]
Definition at line 1176 of file docnode.h.
Referenced by columnIndex(), and setColumnIndex().
m_isFirst
bool DocHtmlCell::m_isFirst = false [private]
Definition at line 1172 of file docnode.h.
Referenced by isFirst(), and markFirst().
m_isHeading
bool DocHtmlCell::m_isHeading = false [private]
Definition at line 1171 of file docnode.h.
Referenced by isHeading().
m_isLast
bool DocHtmlCell::m_isLast = false [private]
Definition at line 1173 of file docnode.h.
Referenced by isLast(), and markLast().
m_rowIdx
uint DocHtmlCell::m_rowIdx = static_cast<uint>(-1) [private]
Definition at line 1175 of file docnode.h.
Referenced by rowIndex(), and setRowIndex().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp