CodeOutputInterface Class Reference
#include <outputgen.h>
Public Member Functions
virtual ~CodeOutputInterface ()=default
CodeOutputInterface ()
CodeOutputInterface (const CodeOutputInterface &)=delete
CodeOutputInterface & operator= (const CodeOutputInterface &)=delete
virtual int id () const
virtual void codify (const QCString &s)=0
virtual void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)=0
virtual void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)=0
virtual void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)=0
virtual void startCodeLine (bool hasLineNumbers)=0
virtual void endCodeLine ()=0
virtual void startFontClass (const QCString &clsName)=0
virtual void endFontClass ()=0
virtual void writeCodeAnchor (const QCString &name)=0
virtual void setCurrentDoc (const Definition *context, const QCString &anchor, bool isSourceFile)
virtual void addWord (const QCString &word, bool hiPriority)
virtual void startCodeFragment (const QCString &style)=0
virtual void endCodeFragment (const QCString &style)=0
virtual ~CodeOutputInterface ()=default
CodeOutputInterface ()
CodeOutputInterface (const CodeOutputInterface &)=delete
CodeOutputInterface & operator= (const CodeOutputInterface &)=delete
virtual int id () const
virtual void codify (const QCString &s)=0
virtual void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)=0
virtual void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)=0
virtual void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)=0
virtual void startCodeLine (bool hasLineNumbers)=0
virtual void endCodeLine ()=0
virtual void startFontClass (const QCString &clsName)=0
virtual void endFontClass ()=0
virtual void writeCodeAnchor (const QCString &name)=0
virtual void setCurrentDoc (const Definition *context, const QCString &anchor, bool isSourceFile)
virtual void addWord (const QCString &word, bool hiPriority)
virtual void startCodeFragment (const QCString &style)=0
virtual void endCodeFragment (const QCString &style)=0
Detailed Description
Output interface for code parser.
Definition at line 59 of file outputgen.h.
Constructor & Destructor Documentation
 CodeOutputInterface() [1/2]
virtual CodeOutputInterface::~CodeOutputInterface () [virtual], [default]
CodeOutputInterface() [1/4]
CodeOutputInterface::CodeOutputInterface () [inline]
Definition at line 63 of file outputgen.h.
{}
CodeOutputInterface() [2/4]
CodeOutputInterface::CodeOutputInterface (const CodeOutputInterface &) [delete]
 CodeOutputInterface() [2/2]
virtual CodeOutputInterface::~CodeOutputInterface () [virtual], [default]
CodeOutputInterface() [3/4]
CodeOutputInterface::CodeOutputInterface () [inline]
Definition at line 63 of file outputgen.h.
{}
CodeOutputInterface() [4/4]
CodeOutputInterface::CodeOutputInterface (const CodeOutputInterface &) [delete]
Member Function Documentation
addWord() [1/2]
virtual void CodeOutputInterface::addWord (const QCString & word, bool hiPriority) [inline], [virtual]
Reimplemented in DocbookGenerator, LatexGenerator, DocbookGenerator, LatexGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, DevNullCodeDocInterface, OutputList, and OutputList.
Definition at line 138 of file outputgen.h.
{}
addWord() [2/2]
virtual void CodeOutputInterface::addWord (const QCString & word, bool hiPriority) [inline], [virtual]
Reimplemented in DocbookGenerator, LatexGenerator, DocbookGenerator, LatexGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, DevNullCodeDocInterface, OutputList, and OutputList.
Definition at line 138 of file outputgen.h.
{}
codify() [1/2]
virtual void CodeOutputInterface::codify (const QCString & s) [pure virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implemented in XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, DevNullCodeDocInterface, OutputList, OutputList, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, LatexCodeGenerator, XMLCodeGenerator, LatexCodeGenerator, and XMLCodeGenerator.
Referenced by OutputList::codify(), and FileCodeParser::parseCode().
codify() [2/2]
virtual void CodeOutputInterface::codify (const QCString & s) [pure virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implemented in XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, DevNullCodeDocInterface, OutputList, OutputList, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, LatexCodeGenerator, XMLCodeGenerator, LatexCodeGenerator, and XMLCodeGenerator.
endCodeFragment() [1/2]
virtual void CodeOutputInterface::endCodeFragment (const QCString & style) [pure virtual]
Ends a block of code
Implemented in HtmlCodeGenerator, ManGenerator, HtmlCodeGenerator, ManGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, XMLCodeGenerator, DevNullCodeDocInterface, XMLCodeGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, LatexCodeGenerator, and LatexCodeGenerator.
Referenced by OutputList::endCodeFragment(), and HtmlDocVisitor::operator()().
endCodeFragment() [2/2]
virtual void CodeOutputInterface::endCodeFragment (const QCString & style) [pure virtual]
Ends a block of code
Implemented in HtmlCodeGenerator, ManGenerator, HtmlCodeGenerator, ManGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, XMLCodeGenerator, DevNullCodeDocInterface, XMLCodeGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, LatexCodeGenerator, and LatexCodeGenerator.
endCodeLine() [1/2]
virtual void CodeOutputInterface::endCodeLine () [pure virtual]
Ends a line of code started with startCodeLine()
Implemented in DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, and XMLCodeGenerator.
Referenced by OutputList::endCodeLine(), and FileCodeParser::parseCode().
endCodeLine() [2/2]
virtual void CodeOutputInterface::endCodeLine () [pure virtual]
Ends a line of code started with startCodeLine()
Implemented in DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, and XMLCodeGenerator.
endFontClass() [1/2]
virtual void CodeOutputInterface::endFontClass () [pure virtual]
Ends a block started with startFontClass()
Implemented in DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, and XMLCodeGenerator.
Referenced by OutputList::endFontClass().
endFontClass() [2/2]
virtual void CodeOutputInterface::endFontClass () [pure virtual]
Ends a block started with startFontClass()
Implemented in DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, and XMLCodeGenerator.
id() [1/2]
virtual int CodeOutputInterface::id () const [inline], [virtual]
Identifier for the output file
Reimplemented in HtmlCodeGenerator, OutputList, HtmlCodeGenerator, and OutputList.
Definition at line 68 of file outputgen.h.
{ return 0; }
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), doxmlparser.compound.docXRefSectType::set_id(), and TooltipManager::writeTooltips().
id() [2/2]
virtual int CodeOutputInterface::id () const [inline], [virtual]
Identifier for the output file
Reimplemented in HtmlCodeGenerator, OutputList, HtmlCodeGenerator, and OutputList.
Definition at line 68 of file outputgen.h.
{ return 0; }
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
operator=() [1/2]
CodeOutputInterface & CodeOutputInterface::operator= (const CodeOutputInterface &) [delete]
operator=() [2/2]
CodeOutputInterface & CodeOutputInterface::operator= (const CodeOutputInterface &) [delete]
setCurrentDoc() [1/2]
virtual void CodeOutputInterface::setCurrentDoc (const Definition * context, const QCString & anchor, bool isSourceFile) [inline], [virtual]
Reimplemented in DocbookGenerator, LatexGenerator, DocbookGenerator, LatexGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, DevNullCodeDocInterface, OutputList, and OutputList.
Definition at line 137 of file outputgen.h.
{}
setCurrentDoc() [2/2]
virtual void CodeOutputInterface::setCurrentDoc (const Definition * context, const QCString & anchor, bool isSourceFile) [inline], [virtual]
Reimplemented in DocbookGenerator, LatexGenerator, DocbookGenerator, LatexGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, DevNullCodeDocInterface, OutputList, and OutputList.
Definition at line 137 of file outputgen.h.
{}
startCodeFragment() [1/2]
virtual void CodeOutputInterface::startCodeFragment (const QCString & style) [pure virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implemented in ManGenerator, ManGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, XMLCodeGenerator, DevNullCodeDocInterface, XMLCodeGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, LatexCodeGenerator, and LatexCodeGenerator.
Referenced by HtmlDocVisitor::operator()(), and OutputList::startCodeFragment().
startCodeFragment() [2/2]
virtual void CodeOutputInterface::startCodeFragment (const QCString & style) [pure virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implemented in ManGenerator, ManGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, XMLCodeGenerator, DevNullCodeDocInterface, XMLCodeGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, LatexCodeGenerator, and LatexCodeGenerator.
startCodeLine() [1/2]
virtual void CodeOutputInterface::startCodeLine (bool hasLineNumbers) [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, OutputList, DocbookGenerator, HtmlGenerator, LatexGenerator, OutputList, DocbookCodeGenerator, HtmlCodeGenerator, ManGenerator, RTFGenerator, DocbookCodeGenerator, HtmlCodeGenerator, ManGenerator, RTFGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, and XMLCodeGenerator.
Referenced by FileCodeParser::parseCode(), and OutputList::startCodeLine().
startCodeLine() [2/2]
virtual void CodeOutputInterface::startCodeLine (bool hasLineNumbers) [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, OutputList, DocbookGenerator, HtmlGenerator, LatexGenerator, OutputList, DocbookCodeGenerator, HtmlCodeGenerator, ManGenerator, RTFGenerator, DocbookCodeGenerator, HtmlCodeGenerator, ManGenerator, RTFGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, and XMLCodeGenerator.
startFontClass() [1/2]
virtual void CodeOutputInterface::startFontClass (const QCString & clsName) [pure virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implemented in ManGenerator, RTFGenerator, ManGenerator, RTFGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, OutputList, OutputList, DocbookCodeGenerator, DocbookCodeGenerator, XMLCodeGenerator, XMLCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, and LatexGenerator.
Referenced by OutputList::startFontClass().
startFontClass() [2/2]
virtual void CodeOutputInterface::startFontClass (const QCString & clsName) [pure virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implemented in ManGenerator, RTFGenerator, ManGenerator, RTFGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, OutputList, OutputList, DocbookCodeGenerator, DocbookCodeGenerator, XMLCodeGenerator, XMLCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, and LatexGenerator.
writeCodeAnchor() [1/2]
virtual void CodeOutputInterface::writeCodeAnchor (const QCString & name) [pure virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implemented in DocbookCodeGenerator, ManGenerator, RTFGenerator, DocbookCodeGenerator, ManGenerator, RTFGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, OutputList, and OutputList.
Referenced by generateClassMemberLink(), generateClassOrGlobalLink(), getLinkInScope(), and OutputList::writeCodeAnchor().
writeCodeAnchor() [2/2]
virtual void CodeOutputInterface::writeCodeAnchor (const QCString & name) [pure virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implemented in DocbookCodeGenerator, ManGenerator, RTFGenerator, DocbookCodeGenerator, ManGenerator, RTFGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, OutputList, and OutputList.
writeCodeLink() [1/2]
virtual void CodeOutputInterface::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [pure virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implemented in DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, LatexCodeGenerator, XMLCodeGenerator, LatexCodeGenerator, XMLCodeGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, and DevNullCodeDocInterface.
Referenced by OutputList::writeCodeLink(), and writeMultiLineCodeLink().
writeCodeLink() [2/2]
virtual void CodeOutputInterface::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [pure virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implemented in DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, LatexCodeGenerator, XMLCodeGenerator, LatexCodeGenerator, XMLCodeGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, and DevNullCodeDocInterface.
writeLineNumber() [1/2]
virtual void CodeOutputInterface::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [pure virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implemented in ManGenerator, RTFGenerator, ManGenerator, RTFGenerator, HtmlCodeGenerator, HtmlCodeGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, DocbookCodeGenerator, DocbookCodeGenerator, XMLCodeGenerator, XMLCodeGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, OutputList, DocbookGenerator, HtmlGenerator, LatexGenerator, and OutputList.
Referenced by FileCodeParser::parseCode(), and OutputList::writeLineNumber().
writeLineNumber() [2/2]
virtual void CodeOutputInterface::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [pure virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implemented in ManGenerator, RTFGenerator, ManGenerator, RTFGenerator, HtmlCodeGenerator, HtmlCodeGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, DocbookCodeGenerator, DocbookCodeGenerator, XMLCodeGenerator, XMLCodeGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, OutputList, DocbookGenerator, HtmlGenerator, LatexGenerator, and OutputList.
writeTooltip() [1/2]
virtual void CodeOutputInterface::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [pure virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implemented in DocbookCodeGenerator, ManGenerator, RTFGenerator, DocbookCodeGenerator, ManGenerator, RTFGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, OutputList, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, and OutputList.
Referenced by OutputList::writeTooltip(), and TooltipManager::writeTooltips().
writeTooltip() [2/2]
virtual void CodeOutputInterface::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [pure virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implemented in DocbookCodeGenerator, ManGenerator, RTFGenerator, DocbookCodeGenerator, ManGenerator, RTFGenerator, XRefDummyCodeGenerator, Doxyparse, XRefDummyCodeGenerator, Doxyparse, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DevNullCodeDocInterface, LatexCodeGenerator, XMLCodeGenerator, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, OutputList, DocbookGenerator, HtmlCodeGenerator, HtmlGenerator, LatexGenerator, and OutputList.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/outputgen.h
doxygen/src/outputgen.h