ConceptListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
ConceptListContext ()
virtual ~ConceptListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
ConceptListContext ()
virtual ~ConceptListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc ()
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 586 of file context.h.
Constructor & Destructor Documentation
ConceptListContext() [1/2]
ConceptListContext::ConceptListContext ()
Definition at line 6184 of file context.cpp.
                                       : p(std::make_unique<Private>())
{
  p->addConcepts(*Doxygen::conceptLinkedMap);
}
References Doxygen::conceptLinkedMap, and p.
 ConceptListContext() [1/2]
ConceptListContext::~ConceptListContext () [virtual]
Definition at line 6189 of file context.cpp.
{
}
ConceptListContext() [2/2]
ConceptListContext::ConceptListContext ()
 ConceptListContext() [2/2]
virtual ConceptListContext::~ConceptListContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr ConceptListContext::alloc () [inline], [static]
Definition at line 589 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ConceptListContext>()); }
Referenced by generateOutputViaTemplate().
alloc() [2/2]
static TemplateListIntfPtr ConceptListContext::alloc () [inline], [static]
Definition at line 589 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ConceptListContext>()); }
at() [1/2]
TemplateVariant ConceptListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 6199 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant ConceptListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t ConceptListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 6194 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t ConceptListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr ConceptListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 6204 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr ConceptListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > ConceptListContext::p [private]
Definition at line 602 of file context.h.
Referenced by at(), ConceptListContext(), count(), and createIterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp