Step2 Class Reference
#include <wizard.h>
Public Member Functions
Step2 (Wizard *parent, const QHash< QString, Input * > &modelData)
void init ()
Step2 (Wizard *parent, const QHash< QString, Input * > &modelData)
void init ()
Private Slots
void optimizeFor (int choice)
void extractMode (int choice)
void changeCrossRefState (int choice)
void optimizeFor (int choice)
void extractMode (int choice)
void changeCrossRefState (int choice)
Private Attributes
QGroupBox * m_extractMode = 0
QGroupBox * m_optimizeLang = 0
QButtonGroup * m_extractModeGroup = 0
QButtonGroup * m_optimizeLangGroup = 0
QCheckBox * m_crossRef = 0
Wizard * m_wizard = 0
const QHash< QString, Input * > & m_modelData
Detailed Description
Definition at line 129 of file wizard.h.
Constructor & Destructor Documentation
Step2() [1/2]
Step2::Step2 (Wizard * parent, const QHash< QString, Input * > & modelData)
Definition at line 753 of file wizard.cpp.
  : m_wizard(wizard), m_modelData(modelData)
{
  QRadioButton *r;
  QVBoxLayout *layout = new QVBoxLayout(this);
  //---------------------------------------------------
  m_extractModeGroup = new QButtonGroup(this);
  m_extractMode = new QGroupBox(this);
  m_extractMode->setTitle(tr("Select the desired extraction mode:"));
  QGridLayout *gbox = new QGridLayout(m_extractMode);
  r = new QRadioButton(tr("Documented entities only"));
  r->setChecked(true);
  m_extractModeGroup->addButton(r, 0);
  gbox->addWidget(r,1,0);
  // 1 -> EXTRACT_ALL = NO
  r = new QRadioButton(tr("All Entities"));
  m_extractModeGroup->addButton(r, 1);
  gbox->addWidget(r,2,0);
  // 2 -> EXTRACT_ALL = YES
  m_crossRef = new QCheckBox(m_extractMode);
  m_crossRef->setText(tr("Include cross-referenced source code in the output"));
  // m_crossRef -> SOURCE_BROWSER = YES/NO
  gbox->addWidget(m_crossRef,3,0);
  layout->addWidget(m_extractMode);
  //---------------------------------------------------
  QFrame *f = new QFrame(this);
  f->setFrameStyle(QFrame::HLine | QFrame::Sunken);
  layout->addWidget(f);
  m_optimizeLangGroup = new QButtonGroup(this);
  m_optimizeLang = new QGroupBox(this);
  m_optimizeLang->setTitle(tr("Select programming language to optimize the results for"));
  gbox = new QGridLayout(m_optimizeLang);
  r = new QRadioButton(m_optimizeLang);
  r->setText(tr("Optimize for C++ output"));
  r->setChecked(true);
  m_optimizeLangGroup->addButton(r, 0);
  // 0 -> OPTIMIZE_OUTPUT_FOR_C = NO
  // OPTIMIZE_OUTPUT_JAVA = NO
  // OPTIMIZE_FOR_FORTRAN = NO
  // OPTIMIZE_OUTPUT_VHDL = NO
  // CPP_CLI_SUPPORT = NO
  // HIDE_SCOPE_NAMES = NO
  // OPTIMIZE_OUTPUT_SLICE = NO
  gbox->addWidget(r,0,0);
  r = new QRadioButton(tr("Optimize for C++/CLI output"));
  gbox->addWidget(r,1,0);
  m_optimizeLangGroup->addButton(r, 1);
  // 1 -> OPTIMIZE_OUTPUT_FOR_C = NO
  // OPTIMIZE_OUTPUT_JAVA = NO
  // OPTIMIZE_FOR_FORTRAN = NO
  // OPTIMIZE_OUTPUT_VHDL = NO
  // CPP_CLI_SUPPORT = YES
  // HIDE_SCOPE_NAMES = NO
  // OPTIMIZE_OUTPUT_SLICE = NO
  r = new QRadioButton(tr("Optimize for Java or C# output"));
  m_optimizeLangGroup->addButton(r, 2);
  // 2 -> OPTIMIZE_OUTPUT_FOR_C = NO
  // OPTIMIZE_OUTPUT_JAVA = YES
  // OPTIMIZE_FOR_FORTRAN = NO
  // OPTIMIZE_OUTPUT_VHDL = NO
  // CPP_CLI_SUPPORT = NO
  // HIDE_SCOPE_NAMES = NO
  // OPTIMIZE_OUTPUT_SLICE = NO
  gbox->addWidget(r,2,0);
  r = new QRadioButton(tr("Optimize for C or PHP output"));
  m_optimizeLangGroup->addButton(r, 3);
  // 3 -> OPTIMIZE_OUTPUT_FOR_C = YES
  // OPTIMIZE_OUTPUT_JAVA = NO
  // OPTIMIZE_FOR_FORTRAN = NO
  // OPTIMIZE_OUTPUT_VHDL = NO
  // CPP_CLI_SUPPORT = NO
  // HIDE_SCOPE_NAMES = YES
  // OPTIMIZE_OUTPUT_SLICE = NO
  gbox->addWidget(r,3,0);
  r = new QRadioButton(tr("Optimize for Fortran output"));
  m_optimizeLangGroup->addButton(r, 4);
  // 4 -> OPTIMIZE_OUTPUT_FOR_C = NO
  // OPTIMIZE_OUTPUT_JAVA = NO
  // OPTIMIZE_FOR_FORTRAN = YES
  // OPTIMIZE_OUTPUT_VHDL = NO
  // CPP_CLI_SUPPORT = NO
  // HIDE_SCOPE_NAMES = NO
  // OPTIMIZE_OUTPUT_SLICE = NO
  gbox->addWidget(r,4,0);
  r = new QRadioButton(tr("Optimize for VHDL output"));
  m_optimizeLangGroup->addButton(r, 5);
  // 5 -> OPTIMIZE_OUTPUT_FOR_C = NO
  // OPTIMIZE_OUTPUT_JAVA = NO
  // OPTIMIZE_FOR_FORTRAN = NO
  // OPTIMIZE_OUTPUT_VHDL = YES
  // CPP_CLI_SUPPORT = NO
  // HIDE_SCOPE_NAMES = NO
  // OPTIMIZE_OUTPUT_SLICE = NO
  gbox->addWidget(r,5,0);
  r = new QRadioButton(tr("Optimize for SLICE output"));
  m_optimizeLangGroup->addButton(r, 6);
  // 5 -> OPTIMIZE_OUTPUT_FOR_C = NO
  // OPTIMIZE_OUTPUT_JAVA = NO
  // OPTIMIZE_FOR_FORTRAN = NO
  // OPTIMIZE_OUTPUT_VHDL = NO
  // CPP_CLI_SUPPORT = NO
  // HIDE_SCOPE_NAMES = NO
  // OPTIMIZE_OUTPUT_SLICE = YES
  gbox->addWidget(r,6,0);
  layout->addWidget(m_optimizeLang);
  layout->addStretch(1);
  connect(m_crossRef,SIGNAL(stateChanged(int)),
          SLOT(changeCrossRefState(int)));
#if QT_VERSION < QT_VERSION_CHECK(5, 15, 0)
  connect(m_optimizeLangGroup,SIGNAL(buttonClicked(int)),
          SLOT(optimizeFor(int)));
  connect(m_extractModeGroup,SIGNAL(buttonClicked(int)),
          SLOT(extractMode(int)));
#else
  connect(m_optimizeLangGroup,SIGNAL(idClicked(int)),
          SLOT(optimizeFor(int)));
  connect(m_extractModeGroup,SIGNAL(idClicked(int)),
          SLOT(extractMode(int)));
#endif
}
References changeCrossRefState(), extractMode(), f, m_crossRef, m_extractMode, m_extractModeGroup, m_optimizeLang, m_optimizeLangGroup, optimizeFor(), and r.
Step2() [2/2]
Step2::Step2 (Wizard * parent, const QHash< QString, Input * > & modelData)
Member Function Documentation
changeCrossRefState [1/2]
void Step2::changeCrossRefState (int choice) [private], [slot]
Definition at line 896 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_SOURCE_BROWSER,choice==Qt::Checked);
}
References m_modelData, STR_SOURCE_BROWSER, and updateBoolOption().
Referenced by Step2().
changeCrossRefState [2/2]
void Step2::changeCrossRefState (int choice) [private], [slot]
extractMode [1/2]
void Step2::extractMode (int choice) [private], [slot]
Definition at line 891 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_EXTRACT_ALL,choice==1);
}
References m_modelData, STR_EXTRACT_ALL, and updateBoolOption().
Referenced by Step2().
extractMode [2/2]
void Step2::extractMode (int choice) [private], [slot]
init() [1/2]
void Step2::init ()
Definition at line 901 of file wizard.cpp.
{
  m_extractModeGroup->button(
      getBoolOption(m_modelData,STR_EXTRACT_ALL) ? 1 : 0)->setChecked(true);
  m_crossRef->setChecked(getBoolOption(m_modelData,STR_SOURCE_BROWSER));
  int x=0;
  if (getBoolOption(m_modelData,STR_CPP_CLI_SUPPORT)) x=1;
  else if (getBoolOption(m_modelData,STR_OPTIMIZE_OUTPUT_JAVA)) x=2;
  else if (getBoolOption(m_modelData,STR_OPTIMIZE_OUTPUT_FOR_C)) x=3;
  else if (getBoolOption(m_modelData,STR_OPTIMIZE_FOR_FORTRAN)) x=4;
  else if (getBoolOption(m_modelData,STR_OPTIMIZE_OUTPUT_VHDL)) x=5;
  else if (getBoolOption(m_modelData,STR_OPTIMIZE_OUTPUT_SLICE)) x=6;
  m_optimizeLangGroup->button(x)->setChecked(true);
}
References getBoolOption(), m_crossRef, m_extractModeGroup, m_modelData, m_optimizeLangGroup, STR_CPP_CLI_SUPPORT, STR_EXTRACT_ALL, STR_OPTIMIZE_FOR_FORTRAN, STR_OPTIMIZE_OUTPUT_FOR_C, STR_OPTIMIZE_OUTPUT_JAVA, STR_OPTIMIZE_OUTPUT_SLICE, STR_OPTIMIZE_OUTPUT_VHDL, STR_SOURCE_BROWSER, and x.
Referenced by Wizard::refresh().
init() [2/2]
void Step2::init ()
optimizeFor [1/2]
void Step2::optimizeFor (int choice) [private], [slot]
Definition at line 881 of file wizard.cpp.
{
  for (int i=0;i<7;i++)
  {
    updateBoolOption(m_modelData,
                     g_optimizeOptionNames[i],
                     g_optimizeMapping[choice][i]);
  }
}
References g_optimizeMapping, g_optimizeOptionNames, m_modelData, and updateBoolOption().
Referenced by Step2().
optimizeFor [2/2]
void Step2::optimizeFor (int choice) [private], [slot]
Member Data Documentation
m_crossRef
QCheckBox * Step2::m_crossRef = 0 [private]
Definition at line 146 of file wizard.h.
Referenced by init(), and Step2().
m_extractMode
QGroupBox * Step2::m_extractMode = 0 [private]
Definition at line 142 of file wizard.h.
Referenced by Step2().
m_extractModeGroup
QButtonGroup * Step2::m_extractModeGroup = 0 [private]
Definition at line 144 of file wizard.h.
Referenced by init(), and Step2().
m_modelData
const QHash< QString, Input * > & Step2::m_modelData [private]
Definition at line 148 of file wizard.h.
Referenced by changeCrossRefState(), extractMode(), init(), and optimizeFor().
m_optimizeLang
QGroupBox * Step2::m_optimizeLang = 0 [private]
Definition at line 143 of file wizard.h.
Referenced by Step2().
m_optimizeLangGroup
QButtonGroup * Step2::m_optimizeLangGroup = 0 [private]
Definition at line 145 of file wizard.h.
Referenced by init(), and Step2().
m_wizard
Wizard * Step2::m_wizard = 0 [private]
Definition at line 147 of file wizard.h.
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/wizard.h
doxygen/build/doxygen/addon/doxywizard/wizard.h
doxygen/addon/doxywizard/wizard.cpp
doxygen/build/doxygen/addon/doxywizard/wizard.cpp