ConceptDefImpl Class Reference
Public Member Functions
ConceptDefImpl (const QCString &fileName, int startLine, int startColumn, const QCString &name, const QCString &tagRef=QCString(), const QCString &tagFile=QCString())
~ConceptDefImpl ()
virtual ConceptDef * resolveAlias ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual bool hasDetailedDescription () const
virtual QCString displayName (bool includeScope=true) const
virtual const IncludeInfo * includeInfo () const
virtual ArgumentList getTemplateParameterList () const
virtual QCString anchor () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual QCString initializer () const
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const
virtual const NamespaceDef * getNamespaceDef () const
virtual const FileDef * getFileDef () const
virtual QCString title () const
virtual int groupId () const
virtual void setIncludeFile (FileDef *fd, const QCString &incName, bool local, bool force)
virtual void setTemplateArguments (const ArgumentList &al)
virtual void setNamespace (NamespaceDef *nd)
virtual void setFileDef (FileDef *fd)
virtual void writeTagFile (TextStream &)
virtual void writeDocumentation (OutputList &)
virtual void setInitializer (const QCString &init)
virtual void findSectionsInDocumentation ()
virtual void setGroupId (int id)
void writeBriefDescription (OutputList &) const
void writeAuthorSection (OutputList &ol) const
void writeIncludeFiles (OutputList &ol) const
void writeDetailedDescription (OutputList &ol, const QCString &title) const
void writeDefinition (OutputList &ol, const QCString &title) const
ConceptDefImpl (const QCString &fileName, int startLine, int startColumn, const QCString &name, const QCString &tagRef=QCString(), const QCString &tagFile=QCString())
~ConceptDefImpl ()
virtual ConceptDef * resolveAlias ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual bool hasDetailedDescription () const
virtual QCString displayName (bool includeScope=true) const
virtual const IncludeInfo * includeInfo () const
virtual ArgumentList getTemplateParameterList () const
virtual QCString anchor () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual QCString initializer () const
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const
virtual const NamespaceDef * getNamespaceDef () const
virtual const FileDef * getFileDef () const
virtual QCString title () const
virtual int groupId () const
virtual void setIncludeFile (FileDef *fd, const QCString &incName, bool local, bool force)
virtual void setTemplateArguments (const ArgumentList &al)
virtual void setNamespace (NamespaceDef *nd)
virtual void setFileDef (FileDef *fd)
virtual void writeTagFile (TextStream &)
virtual void writeDocumentation (OutputList &)
virtual void setInitializer (const QCString &init)
virtual void findSectionsInDocumentation ()
virtual void setGroupId (int id)
void writeBriefDescription (OutputList &) const
void writeAuthorSection (OutputList &ol) const
void writeIncludeFiles (OutputList &ol) const
void writeDetailedDescription (OutputList &ol, const QCString &title) const
void writeDefinition (OutputList &ol, const QCString &title) const
Private Attributes
QCString m_fileName
std::unique_ptr< IncludeInfo > m_incInfo
NamespaceDef * m_nspace = 0
FileDef * m_fileDef = 0
ArgumentList m_tArgList
QCString m_initializer
int m_groupId = -1
Additional Inherited Members
Detailed Description
Definition at line 31 of file conceptdef.cpp.
Constructor & Destructor Documentation
ConceptDefImpl() [1/2]
ConceptDefImpl::ConceptDefImpl (const QCString & fileName, int startLine, int startColumn, const QCString & name, const QCString & tagRef = QCString(), const QCString & tagFile = QCString())
Definition at line 152 of file conceptdef.cpp.
                                                                         : DefinitionMixin(fileName,startLine,startColumn,name)
{
  if (!tagFile.isEmpty())
  {
    if (!tagRef.isEmpty())
    {
      m_fileName = stripExtension(tagFile);
    }
    else
    {
      m_fileName = convertNameToFile(stripExtension(tagFile));
    }
  }
  else
  {
    m_fileName = convertNameToFile(QCString("concept")+name);
  }
  setReference(tagRef);
}
References convertNameToFile(), QCString::isEmpty(), m_fileName, DefinitionMixin< ConceptDefMutable >::name(), DefinitionMixin< ConceptDefMutable >::setReference(), and stripExtension().
 ConceptDefImpl() [1/2]
ConceptDefImpl::~ConceptDefImpl ()
Definition at line 173 of file conceptdef.cpp.
{
}
ConceptDefImpl() [2/2]
ConceptDefImpl::ConceptDefImpl (const QCString & fileName, int startLine, int startColumn, const QCString & name, const QCString & tagRef = QCString(), const QCString & tagFile = QCString())
 ConceptDefImpl() [2/2]
ConceptDefImpl::~ConceptDefImpl ()
Member Function Documentation
anchor() [1/2]
QCString ConceptDefImpl::anchor () const [virtual]
Returns the anchor within a page where this item can be found
Implements ConceptDef.
Definition at line 196 of file conceptdef.cpp.
{
  return "";
}
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), doxmlparser.compound.docTocItemType::set_anchor(), and writeDeclarationLink().
anchor() [2/2]
virtual QCString ConceptDefImpl::anchor () const [virtual]
Returns the anchor within a page where this item can be found
Implements ConceptDef.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
codeSymbolType() [1/2]
virtual CodeSymbolType ConceptDefImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 42 of file conceptdef.cpp.
{ return CodeSymbolType::Concept; }
References Concept.
codeSymbolType() [2/2]
virtual CodeSymbolType ConceptDefImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 42 of file conceptdef.cpp.
{ return CodeSymbolType::Concept; }
References Concept.
definitionType() [1/2]
Definition::DefType ConceptDefImpl::definitionType () const [virtual]
Use this for dynamic inspection of the type of the derived class
Implements ConceptDef.
Definition at line 177 of file conceptdef.cpp.
{
  return TypeConcept;
}
References Definition::TypeConcept.
definitionType() [2/2]
virtual DefType ConceptDefImpl::definitionType () const [virtual]
Use this for dynamic inspection of the type of the derived class
Implements ConceptDef.
displayName() [1/2]
QCString ConceptDefImpl::displayName (bool includeScope = true) const [virtual]
Returns the name of the definition as it appears in the output
Implements ConceptDef.
Definition at line 201 of file conceptdef.cpp.
{
  return includeScope ? name() : localName();
}
References DefinitionMixin< ConceptDefMutable >::localName(), and DefinitionMixin< ConceptDefMutable >::name().
Referenced by title(), writeDeclarationLink(), and writeDocumentation().
displayName() [2/2]
virtual QCString ConceptDefImpl::displayName (bool includeScope = true) const [virtual]
Returns the name of the definition as it appears in the output
Implements ConceptDef.
findSectionsInDocumentation() [1/2]
void ConceptDefImpl::findSectionsInDocumentation () [virtual]
Implements ConceptDefMutable.
Definition at line 650 of file conceptdef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
}
References DefinitionMixin< ConceptDefMutable >::briefDescription(), DefinitionMixin< ConceptDefMutable >::docFile(), docFindSections(), and DefinitionMixin< ConceptDefMutable >::documentation().
findSectionsInDocumentation() [2/2]
virtual void ConceptDefImpl::findSectionsInDocumentation () [virtual]
Implements ConceptDefMutable.
getFileDef() [1/2]
const FileDef * ConceptDefImpl::getFileDef () const [virtual]
Implements ConceptDef.
Definition at line 264 of file conceptdef.cpp.
{
  return m_fileDef;
}
References m_fileDef.
getFileDef() [2/2]
virtual const FileDef * ConceptDefImpl::getFileDef () const [virtual]
Implements ConceptDef.
getNamespaceDef() [1/2]
const NamespaceDef * ConceptDefImpl::getNamespaceDef () const [virtual]
Implements ConceptDef.
Definition at line 254 of file conceptdef.cpp.
{
  return m_nspace;
}
References m_nspace.
getNamespaceDef() [2/2]
virtual const NamespaceDef * ConceptDefImpl::getNamespaceDef () const [virtual]
Implements ConceptDef.
getOutputFileBase() [1/2]
QCString ConceptDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements ConceptDef.
Definition at line 182 of file conceptdef.cpp.
{
  return m_fileName;
}
References m_fileName.
Referenced by writeBriefDescription(), writeDeclarationLink(), writeDocumentation(), and writeTagFile().
getOutputFileBase() [2/2]
virtual QCString ConceptDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements ConceptDef.
getTemplateParameterList() [1/2]
ArgumentList ConceptDefImpl::getTemplateParameterList () const [virtual]
Implements ConceptDef.
Definition at line 211 of file conceptdef.cpp.
{
  return m_tArgList;
}
References m_tArgList.
getTemplateParameterList() [2/2]
virtual ArgumentList ConceptDefImpl::getTemplateParameterList () const [virtual]
Implements ConceptDef.
groupId() [1/2]
int ConceptDefImpl::groupId () const [virtual]
Implements ConceptDef.
Definition at line 274 of file conceptdef.cpp.
{
  return m_groupId;
}
References m_groupId.
groupId() [2/2]
virtual int ConceptDefImpl::groupId () const [virtual]
Implements ConceptDef.
hasDetailedDescription() [1/2]
bool ConceptDefImpl::hasDetailedDescription () const [virtual]
Implements ConceptDef.
Definition at line 187 of file conceptdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  bool sourceBrowser = Config_getBool(SOURCE_BROWSER);
  return ((!briefDescription().isEmpty() && repeatBrief) ||
          !documentation().isEmpty() ||
          (sourceBrowser && getStartBodyLine()!=-1 && getBodyDef()));
}
References DefinitionMixin< ConceptDefMutable >::briefDescription(), Config_getBool, DefinitionMixin< ConceptDefMutable >::documentation(), DefinitionMixin< ConceptDefMutable >::getBodyDef(), and DefinitionMixin< ConceptDefMutable >::getStartBodyLine().
Referenced by writeBriefDescription(), and writeDetailedDescription().
hasDetailedDescription() [2/2]
virtual bool ConceptDefImpl::hasDetailedDescription () const [virtual]
Implements ConceptDef.
includeInfo() [1/2]
const IncludeInfo * ConceptDefImpl::includeInfo () const [virtual]
Implements ConceptDef.
Definition at line 206 of file conceptdef.cpp.
{
  return m_incInfo.get();
}
References m_incInfo.
includeInfo() [2/2]
virtual const IncludeInfo * ConceptDefImpl::includeInfo () const [virtual]
Implements ConceptDef.
initializer() [1/2]
QCString ConceptDefImpl::initializer () const [virtual]
Implements ConceptDef.
Definition at line 404 of file conceptdef.cpp.
{
  return m_initializer;
}
References m_initializer.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
initializer() [2/2]
virtual QCString ConceptDefImpl::initializer () const [virtual]
Implements ConceptDef.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
isLinkable() [1/2]
bool ConceptDefImpl::isLinkable () const [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements ConceptDef.
Definition at line 221 of file conceptdef.cpp.
{
  return isLinkableInProject() || isReference();
}
References isLinkableInProject(), and DefinitionMixin< ConceptDefMutable >::isReference().
Referenced by writeDeclarationLink().
isLinkable() [2/2]
virtual bool ConceptDefImpl::isLinkable () const [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements ConceptDef.
isLinkableInProject() [1/2]
bool ConceptDefImpl::isLinkableInProject () const [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements ConceptDef.
Definition at line 216 of file conceptdef.cpp.
{
  return hasDocumentation() && !isReference() && !isHidden();
}
References DefinitionMixin< ConceptDefMutable >::hasDocumentation(), DefinitionMixin< ConceptDefMutable >::isHidden(), and DefinitionMixin< ConceptDefMutable >::isReference().
Referenced by isLinkable().
isLinkableInProject() [2/2]
virtual bool ConceptDefImpl::isLinkableInProject () const [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements ConceptDef.
resolveAlias() [1/2]
virtual ConceptDef * ConceptDefImpl::resolveAlias () [inline], [virtual]
Definition at line 38 of file conceptdef.cpp.
{ return this; }
resolveAlias() [2/2]
virtual ConceptDef * ConceptDefImpl::resolveAlias () [inline], [virtual]
Definition at line 38 of file conceptdef.cpp.
{ return this; }
setFileDef() [1/2]
void ConceptDefImpl::setFileDef (FileDef * fd) [virtual]
Implements ConceptDefMutable.
Definition at line 259 of file conceptdef.cpp.
{
  m_fileDef=fd;
}
References m_fileDef.
setFileDef() [2/2]
virtual void ConceptDefImpl::setFileDef (FileDef * fd) [virtual]
Implements ConceptDefMutable.
setGroupId() [1/2]
void ConceptDefImpl::setGroupId (int id) [virtual]
Implements ConceptDefMutable.
Definition at line 279 of file conceptdef.cpp.
{
  m_groupId = id;
}
References DefinitionMixin< ConceptDefMutable >::id(), and m_groupId.
setGroupId() [2/2]
virtual void ConceptDefImpl::setGroupId (int id) [virtual]
Implements ConceptDefMutable.
setIncludeFile() [1/2]
void ConceptDefImpl::setIncludeFile (FileDef * fd, const QCString & incName, bool local, bool force) [virtual]
Implements ConceptDefMutable.
Definition at line 226 of file conceptdef.cpp.
{
  if (!m_incInfo) m_incInfo = std::make_unique<IncludeInfo>();
  if ((!incName.isEmpty() && m_incInfo->includeName.isEmpty()) ||
      (fd!=0 && m_incInfo->fileDef==0)
     )
  {
    m_incInfo->fileDef = fd;
    m_incInfo->includeName = incName;
    m_incInfo->local = local;
  }
  if (force && !incName.isEmpty())
  {
    m_incInfo->includeName = incName;
    m_incInfo->local = local;
  }
}
References QCString::isEmpty(), and m_incInfo.
setIncludeFile() [2/2]
virtual void ConceptDefImpl::setIncludeFile (FileDef * fd, const QCString & incName, bool local, bool force) [virtual]
Implements ConceptDefMutable.
setInitializer() [1/2]
void ConceptDefImpl::setInitializer (const QCString & init) [virtual]
Implements ConceptDefMutable.
Definition at line 399 of file conceptdef.cpp.
{
  m_initializer = templateSpec(m_tArgList)+"\nconcept "+name()+" = "+init;
}
References Config::init(), m_initializer, m_tArgList, DefinitionMixin< ConceptDefMutable >::name(), and templateSpec().
setInitializer() [2/2]
virtual void ConceptDefImpl::setInitializer (const QCString & init) [virtual]
Implements ConceptDefMutable.
setNamespace() [1/2]
void ConceptDefImpl::setNamespace (NamespaceDef * nd) [virtual]
Implements ConceptDefMutable.
Definition at line 249 of file conceptdef.cpp.
{
  m_nspace = nd;
}
References m_nspace.
setNamespace() [2/2]
virtual void ConceptDefImpl::setNamespace (NamespaceDef * nd) [virtual]
Implements ConceptDefMutable.
setTemplateArguments() [1/2]
void ConceptDefImpl::setTemplateArguments (const ArgumentList & al) [virtual]
Implements ConceptDefMutable.
Definition at line 244 of file conceptdef.cpp.
{
  m_tArgList = al;
}
References m_tArgList.
setTemplateArguments() [2/2]
virtual void ConceptDefImpl::setTemplateArguments (const ArgumentList & al) [virtual]
Implements ConceptDefMutable.
title() [1/2]
QCString ConceptDefImpl::title () const [virtual]
Implements ConceptDef.
Definition at line 269 of file conceptdef.cpp.
{
  return theTranslator->trConceptReference(displayName());
}
References displayName(), theTranslator, and Translator::trConceptReference().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), writeDefinition(), and writeDetailedDescription().
title() [2/2]
virtual QCString ConceptDefImpl::title () const [virtual]
Implements ConceptDef.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
writeAuthorSection() [1/2]
void ConceptDefImpl::writeAuthorSection (OutputList & ol) const
Definition at line 474 of file conceptdef.cpp.
{
  // write Author section (Man only)
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Man);
  ol.startGroupHeader();
  ol.parseText(theTranslator->trAuthor(TRUE,TRUE));
  ol.endGroupHeader();
  ol.parseText(theTranslator->trGeneratedAutomatically(Config_getString(PROJECT_NAME)));
  ol.popGeneratorState();
}
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), and TRUE.
Referenced by writeDocumentation().
writeAuthorSection() [2/2]
void ConceptDefImpl::writeAuthorSection (OutputList & ol) const
writeBriefDescription() [1/2]
void ConceptDefImpl::writeBriefDescription (OutputList & ol) const
Definition at line 298 of file conceptdef.cpp.
{
  if (hasBriefDescription())
  {
    auto parser { createDocParser() };
    auto ast { validatingParseDoc(
                        *parser.get(),briefFile(),briefLine(),this,0,
                        briefDescription(),TRUE,FALSE,
                        QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startParagraph();
      ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Man);
      ol.writeString(" - ");
      ol.popGeneratorState();
      ol.writeDoc(ast.get(),this,0);
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::RTF);
      ol.writeString(" \n");
      ol.enable(OutputGenerator::RTF);
      if (hasDetailedDescription())
      {
        ol.disableAllBut(OutputGenerator::Html);
        ol.startTextLink(getOutputFileBase(),"details");
        ol.parseText(theTranslator->trMore());
        ol.endTextLink();
      }
      ol.popGeneratorState();
      ol.endParagraph();
    }
  }
  ol.writeSynopsis();
}
References DefinitionMixin< ConceptDefMutable >::briefDescription(), DefinitionMixin< ConceptDefMutable >::briefFile(), DefinitionMixin< ConceptDefMutable >::briefLine(), Config_getBool, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), FALSE, getOutputFileBase(), DefinitionMixin< ConceptDefMutable >::hasBriefDescription(), hasDetailedDescription(), OutputGenerator::Html, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, Translator::trMore(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeBriefDescription() [2/2]
void ConceptDefImpl::writeBriefDescription (OutputList &) const
writeDeclarationLink() [1/2]
void ConceptDefImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const [virtual]
Implements ConceptDef.
Definition at line 592 of file conceptdef.cpp.
{
  if (isLinkable())
  {
    if (!found) // first concept
    {
      ol.startMemberHeader("concepts");
      if (!header.isEmpty())
      {
        ol.parseText(header);
      }
      else
      {
        theTranslator->trConcept(true,false);
      }
      ol.endMemberHeader();
      ol.startMemberList();
      found=TRUE;
    }
    ol.startMemberDeclaration();
    ol.startMemberItem(anchor(),FALSE);
    ol.writeString("concept ");
    QCString cname = displayName(!localNames);
    ol.insertMemberAlign();
    if (isLinkable())
    {
      ol.writeObjectLink(getReference(),
          getOutputFileBase(),
          anchor(),
          cname
          );
    }
    else
    {
      ol.startBold();
      ol.docify(cname);
      ol.endBold();
    }
    ol.endMemberItem();
    // add the brief description if available
    if (!briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
    {
      auto parser { createDocParser() };
      auto ast { validatingParseDoc(
                                *parser.get(),briefFile(),briefLine(),this,0,
                                briefDescription(),FALSE,FALSE,
                                QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
      if (!ast->isEmpty())
      {
        ol.startMemberDescription(anchor());
        ol.writeDoc(ast.get(),this,0);
        ol.endMemberDescription();
      }
    }
    ol.endMemberDeclaration(anchor(),QCString());
  }
}
References anchor(), DefinitionMixin< ConceptDefMutable >::briefDescription(), DefinitionMixin< ConceptDefMutable >::briefFile(), DefinitionMixin< ConceptDefMutable >::briefLine(), Config_getBool, createDocParser(), displayName(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), FALSE, found, getOutputFileBase(), DefinitionMixin< ConceptDefMutable >::getReference(), OutputList::insertMemberAlign(), QCString::isEmpty(), isLinkable(), OutputList::parseText(), OutputList::startBold(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trConcept(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeObjectLink(), and OutputList::writeString().
writeDeclarationLink() [2/2]
virtual void ConceptDefImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const [virtual]
Implements ConceptDef.
writeDefinition() [1/2]
void ConceptDefImpl::writeDefinition (OutputList & ol, const QCString & title) const
Definition at line 409 of file conceptdef.cpp.
{
    ol.startGroupHeader();
      ol.parseText(title);
    ol.endGroupHeader();
    auto intf = Doxygen::parserManager->getCodeParser(".cpp");
    intf->resetCodeParserState();
    ol.startCodeFragment("DoxyCode");
    QCString scopeName;
    if (getOuterScope()!=Doxygen::globalScope) scopeName=getOuterScope()->name();
    TextStream conceptDef;
    conceptDef << m_initializer;
    intf->parseCode(ol,scopeName,conceptDef.str(),SrcLangExt_Cpp,false,QCString(),
                    m_fileDef, -1,-1,true,0,false,this);
    ol.endCodeFragment("DoxyCode");
}
References OutputList::endCodeFragment(), OutputList::endGroupHeader(), ParserManager::getCodeParser(), DefinitionMixin< ConceptDefMutable >::getOuterScope(), Doxygen::globalScope, m_fileDef, m_initializer, Definition::name(), Doxygen::parserManager, OutputList::parseText(), SrcLangExt_Cpp, OutputList::startCodeFragment(), OutputList::startGroupHeader(), TextStream::str(), and title().
Referenced by writeDocumentation().
writeDefinition() [2/2]
void ConceptDefImpl::writeDefinition (OutputList & ol, const QCString & title) const
writeDetailedDescription() [1/2]
void ConceptDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) const
Definition at line 427 of file conceptdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  if (hasDetailedDescription())
  {
    ol.pushGeneratorState();
      ol.disable(OutputGenerator::Html);
      ol.writeRuler();
    ol.popGeneratorState();
    ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Html);
      ol.writeAnchor(QCString(),"details");
    ol.popGeneratorState();
    ol.startGroupHeader();
      ol.parseText(title);
    ol.endGroupHeader();
    ol.startTextBlock();
    // repeat brief description
    if (!briefDescription().isEmpty() && repeatBrief)
    {
      ol.generateDoc(briefFile(),briefLine(),this,0,briefDescription(),FALSE,FALSE,
          QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    if (!briefDescription().isEmpty() && repeatBrief &&
        !documentation().isEmpty())
    {
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::Html);
      ol.writeString("\n\n");
      ol.popGeneratorState();
    }
    // write documentation
    if (!documentation().isEmpty())
    {
      ol.generateDoc(docFile(),docLine(),this,0,documentation(),TRUE,FALSE,
          QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    writeSourceDef(ol,name());
    ol.endTextBlock();
  }
}
References DefinitionMixin< ConceptDefMutable >::briefDescription(), DefinitionMixin< ConceptDefMutable >::briefFile(), DefinitionMixin< ConceptDefMutable >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< ConceptDefMutable >::docFile(), DefinitionMixin< ConceptDefMutable >::docLine(), DefinitionMixin< ConceptDefMutable >::documentation(), OutputList::endGroupHeader(), OutputList::endTextBlock(), FALSE, OutputList::generateDoc(), hasDetailedDescription(), OutputGenerator::Html, DefinitionMixin< ConceptDefMutable >::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), OutputList::startTextBlock(), title(), TRUE, OutputList::writeAnchor(), OutputList::writeRuler(), DefinitionMixin< ConceptDefMutable >::writeSourceDef(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDetailedDescription() [2/2]
void ConceptDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) const
writeDocumentation() [1/2]
void ConceptDefImpl::writeDocumentation (OutputList & ol) [virtual]
Implements ConceptDefMutable.
Definition at line 486 of file conceptdef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  QCString pageTitle = theTranslator->trConceptReference(displayName());
  startFile(ol,getOutputFileBase(),name(),pageTitle,HLI_ConceptVisible,!generateTreeView);
  // ---- navigation part
  if (!generateTreeView)
  {
    if (getOuterScope()!=Doxygen::globalScope)
    {
      writeNavigationPath(ol);
    }
    ol.endQuickIndices();
  }
  // ---- title part
  startTitle(ol,getOutputFileBase(),this);
  ol.parseText(pageTitle);
  addGroupListToTitle(ol,this);
  endTitle(ol,getOutputFileBase(),displayName());
  // ---- contents part
  ol.startContents();
  //---------------------------------------- start flexible part -------------------------------
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Concept))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol);
        break;
      case LayoutDocEntry::ConceptDefinition:
        if (ls) writeDefinition(ol,ls->title(getLanguage()));
        break;
      case LayoutDocEntry::DetailedDesc:
        if (ls) writeDetailedDescription(ol,ls->title(getLanguage()));
        break;
      case LayoutDocEntry::AuthorSection:
        writeAuthorSection(ol);
        break;
      case LayoutDocEntry::ClassIncludes:
        writeIncludeFiles(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
      case LayoutDocEntry::NamespaceClasses:
      case LayoutDocEntry::NamespaceInterfaces:
      case LayoutDocEntry::NamespaceStructs:
      case LayoutDocEntry::NamespaceExceptions:
      case LayoutDocEntry::NamespaceConcepts:
      case LayoutDocEntry::NamespaceNestedNamespaces:
      case LayoutDocEntry::NamespaceNestedConstantGroups:
      case LayoutDocEntry::MemberGroups:
      case LayoutDocEntry::MemberDecl:
      case LayoutDocEntry::MemberDeclEnd:
      case LayoutDocEntry::MemberDefStart:
      case LayoutDocEntry::NamespaceInlineClasses:
      case LayoutDocEntry::MemberDef:
      case LayoutDocEntry::MemberDefEnd:
      case LayoutDocEntry::ClassInheritanceGraph:
      case LayoutDocEntry::ClassNestedClasses:
      case LayoutDocEntry::ClassCollaborationGraph:
      case LayoutDocEntry::ClassAllMembersLink:
      case LayoutDocEntry::ClassUsedFiles:
      case LayoutDocEntry::ClassInlineClasses:
      case LayoutDocEntry::FileClasses:
      case LayoutDocEntry::FileConcepts:
      case LayoutDocEntry::FileInterfaces:
      case LayoutDocEntry::FileStructs:
      case LayoutDocEntry::FileExceptions:
      case LayoutDocEntry::FileNamespaces:
      case LayoutDocEntry::FileConstantGroups:
      case LayoutDocEntry::FileIncludes:
      case LayoutDocEntry::FileIncludeGraph:
      case LayoutDocEntry::FileIncludedByGraph:
      case LayoutDocEntry::FileInlineClasses:
      case LayoutDocEntry::FileSourceLink:
      case LayoutDocEntry::GroupClasses:
      case LayoutDocEntry::GroupConcepts:
      case LayoutDocEntry::GroupInlineClasses:
      case LayoutDocEntry::GroupNamespaces:
      case LayoutDocEntry::GroupDirs:
      case LayoutDocEntry::GroupNestedGroups:
      case LayoutDocEntry::GroupFiles:
      case LayoutDocEntry::GroupGraph:
      case LayoutDocEntry::GroupPageDocs:
      case LayoutDocEntry::DirSubDirs:
      case LayoutDocEntry::DirFiles:
      case LayoutDocEntry::DirGraph:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::Namespace entry list\n",lde->kind());
        break;
    }
  }
  //---------------------------------------- end flexible part -------------------------------
  ol.endContents();
  endFileWithNavPath(this,ol);
}
References addGroupListToTitle(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, LayoutDocManager::Concept, LayoutDocEntry::ConceptDefinition, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, displayName(), OutputList::endContents(), endFileWithNavPath(), OutputList::endQuickIndices(), endTitle(), err(), LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, LayoutDocEntry::FileStructs, DefinitionMixin< ConceptDefMutable >::getLanguage(), DefinitionMixin< ConceptDefMutable >::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, HLI_ConceptVisible, LayoutDocManager::instance(), LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, DefinitionMixin< ConceptDefMutable >::name(), LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, LayoutDocEntry::NamespaceStructs, OutputList::parseText(), OutputList::startContents(), startFile(), startTitle(), theTranslator, LayoutDocEntrySection::title(), Translator::trConceptReference(), writeAuthorSection(), writeBriefDescription(), writeDefinition(), writeDetailedDescription(), writeIncludeFiles(), and DefinitionMixin< ConceptDefMutable >::writeNavigationPath().
writeDocumentation() [2/2]
virtual void ConceptDefImpl::writeDocumentation (OutputList &) [virtual]
Implements ConceptDefMutable.
writeIncludeFiles() [1/2]
void ConceptDefImpl::writeIncludeFiles (OutputList & ol) const
Definition at line 334 of file conceptdef.cpp.
{
  if (m_incInfo)
  {
    QCString nm=m_incInfo->includeName.isEmpty() ?
      (m_incInfo->fileDef ?
       m_incInfo->fileDef->docName() : QCString()
      ) :
      m_incInfo->includeName;
    if (!nm.isEmpty())
    {
      ol.startParagraph();
      ol.startTypewriter();
      ol.docify("#include ");
      if (m_incInfo->local)
        ol.docify("\"");
      else
        ol.docify("<");
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::Html);
      ol.docify(nm);
      ol.disableAllBut(OutputGenerator::Html);
      ol.enable(OutputGenerator::Html);
      if (m_incInfo->fileDef)
      {
        ol.writeObjectLink(QCString(),m_incInfo->fileDef->includeName(),QCString(),nm);
      }
      else
      {
        ol.docify(nm);
      }
      ol.popGeneratorState();
      if (m_incInfo->local)
        ol.docify("\"");
      else
        ol.docify(">");
      ol.endTypewriter();
      ol.endParagraph();
    }
  }
}
References OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTypewriter(), OutputGenerator::Html, if(), QCString::isEmpty(), m_incInfo, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startParagraph(), OutputList::startTypewriter(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeIncludeFiles() [2/2]
void ConceptDefImpl::writeIncludeFiles (OutputList & ol) const
writeTagFile() [1/2]
void ConceptDefImpl::writeTagFile (TextStream & tagFile) [virtual]
Implements ConceptDefMutable.
Definition at line 284 of file conceptdef.cpp.
{
  tagFile << " <compound kind=\"concept\">\n";
  tagFile << " <name>" << convertToXML(name()) << "</name>\n";
  tagFile << " <filename>" << convertToXML(addHtmlExtensionIfMissing(getOutputFileBase())) << "</filename>\n";
  QCString idStr = id();
  if (!idStr.isEmpty())
  {
    tagFile << " <clangid>" << convertToXML(idStr) << "</clangid>\n";
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << " </compound>\n";
}
References addHtmlExtensionIfMissing(), convertToXML(), getOutputFileBase(), DefinitionMixin< ConceptDefMutable >::id(), QCString::isEmpty(), DefinitionMixin< ConceptDefMutable >::name(), and DefinitionMixin< ConceptDefMutable >::writeDocAnchorsToTagFile().
writeTagFile() [2/2]
virtual void ConceptDefImpl::writeTagFile (TextStream &) [virtual]
Implements ConceptDefMutable.
Member Data Documentation
m_fileDef
FileDef * ConceptDefImpl::m_fileDef = 0 [private]
Definition at line 81 of file conceptdef.cpp.
Referenced by getFileDef(), setFileDef(), and writeDefinition().
m_fileName
QCString ConceptDefImpl::m_fileName [private]
Definition at line 78 of file conceptdef.cpp.
Referenced by ConceptDefImpl(), and getOutputFileBase().
m_groupId
int ConceptDefImpl::m_groupId = -1 [private]
Definition at line 84 of file conceptdef.cpp.
Referenced by groupId(), and setGroupId().
m_incInfo
std::unique_ptr< IncludeInfo > ConceptDefImpl::m_incInfo [private]
Definition at line 79 of file conceptdef.cpp.
Referenced by includeInfo(), setIncludeFile(), and writeIncludeFiles().
m_initializer
QCString ConceptDefImpl::m_initializer [private]
Definition at line 83 of file conceptdef.cpp.
Referenced by initializer(), setInitializer(), and writeDefinition().
m_nspace
NamespaceDef * ConceptDefImpl::m_nspace = 0 [private]
Definition at line 80 of file conceptdef.cpp.
Referenced by getNamespaceDef(), and setNamespace().
m_tArgList
ArgumentList ConceptDefImpl::m_tArgList [private]
Definition at line 82 of file conceptdef.cpp.
Referenced by getTemplateParameterList(), setInitializer(), and setTemplateArguments().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/conceptdef.cpp
doxygen/src/conceptdef.cpp