TemplateBlockContext Class Reference
Class holding stacks of blocks available in the context.
Public Types
using NodeBlockList = std::deque< TemplateNodeBlock * >
using NodeBlockList = std::deque< TemplateNodeBlock * >
Public Member Functions
TemplateBlockContext ()
TemplateNodeBlock * get (const QCString &name) const
TemplateNodeBlock * pop (const QCString &name)
void add (TemplateNodeBlock *block)
void add (TemplateBlockContext *ctx)
void push (TemplateNodeBlock *block)
void clear ()
TemplateBlockContext ()
TemplateNodeBlock * get (const QCString &name) const
TemplateNodeBlock * pop (const QCString &name)
void add (TemplateNodeBlock *block)
void add (TemplateBlockContext *ctx)
void push (TemplateNodeBlock *block)
void clear ()
Private Attributes
std::map< std::string, NodeBlockList > m_blocks
Detailed Description
Class holding stacks of blocks available in the context.
Definition at line 613 of file template.cpp.
Member Typedef Documentation
NodeBlockList [1/2]
using TemplateBlockContext::NodeBlockList = std::deque<TemplateNodeBlock*>
Definition at line 623 of file template.cpp.
NodeBlockList [2/2]
using TemplateBlockContext::NodeBlockList = std::deque<TemplateNodeBlock*>
Definition at line 623 of file template.cpp.
Constructor & Destructor Documentation
TemplateBlockContext() [1/2]
TemplateBlockContext::TemplateBlockContext ()
Definition at line 4732 of file template.cpp.
{
}
TemplateBlockContext() [2/2]
TemplateBlockContext::TemplateBlockContext ()
Member Function Documentation
add() [1/4]
void TemplateBlockContext::add (TemplateBlockContext * ctx)
Definition at line 4774 of file template.cpp.
{
  for (auto &kv : ctx->m_blocks)
  {
    for (auto &nb : kv.second)
    {
      add(nb);
    }
  }
}
References add(), and m_blocks.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [2/4]
void TemplateBlockContext::add (TemplateBlockContext * ctx)
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [3/4]
void TemplateBlockContext::add (TemplateNodeBlock * block)
Definition at line 4764 of file template.cpp.
{
  auto it = m_blocks.find(block->name().str());
  if (it==m_blocks.end())
  {
    it = m_blocks.insert(std::make_pair(block->name().str(),NodeBlockList())).first;
  }
  it->second.push_front(block);
}
References m_blocks.
Referenced by doxmlparser.compound.memberdefType::__init__(), add(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), TemplateImpl::render(), TemplateNodeExtend::render(), and doxmlparser.compound.memberdefType::set_add().
add() [4/4]
void TemplateBlockContext::add (TemplateNodeBlock * block)
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
clear() [1/2]
void TemplateBlockContext::clear ()
Definition at line 4785 of file template.cpp.
{
  m_blocks.clear();
}
References m_blocks.
Referenced by TemplateNodeExtend::render().
clear() [2/2]
void TemplateBlockContext::clear ()
get() [1/2]
TemplateNodeBlock * TemplateBlockContext::get (const QCString & name) const
Definition at line 4736 of file template.cpp.
{
  auto it = m_blocks.find(name.str());
  if (it==m_blocks.end() || it->second.empty())
  {
    return 0;
  }
  else
  {
    return it->second.back();
  }
}
References m_blocks, and setup::name.
Referenced by TemplateNodeBlock::render().
get() [2/2]
TemplateNodeBlock * TemplateBlockContext::get (const QCString & name) const
pop() [1/2]
TemplateNodeBlock * TemplateBlockContext::pop (const QCString & name)
Definition at line 4749 of file template.cpp.
{
  auto it = m_blocks.find(name.str());
  if (it==m_blocks.end() || it->second.empty())
  {
    return 0;
  }
  else
  {
    TemplateNodeBlock *bld = it->second.back();
    it->second.pop_back();
    return bld;
  }
}
References m_blocks, and setup::name.
Referenced by TemplateNodeBlock::render().
pop() [2/2]
TemplateNodeBlock * TemplateBlockContext::pop (const QCString & name)
push() [1/2]
void TemplateBlockContext::push (TemplateNodeBlock * block)
Definition at line 4790 of file template.cpp.
{
  auto it = m_blocks.find(block->name().str());
  if (it==m_blocks.end())
  {
    it = m_blocks.insert(std::make_pair(block->name().str(),NodeBlockList())).first;
  }
  it->second.push_back(block);
}
References m_blocks.
Referenced by TemplateNodeBlock::render().
push() [2/2]
void TemplateBlockContext::push (TemplateNodeBlock * block)
Member Data Documentation
m_blocks
std::map< std::string, NodeBlockList > TemplateBlockContext::m_blocks [private]
Definition at line 625 of file template.cpp.
Referenced by add(), clear(), get(), pop(), and push().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp