TranslatorGreek Class Reference
#include <translator_gr.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString latexCommandName ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString getLanguageString ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString latexCommandName ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString getLanguageString ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 51 of file translator_gr.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorGreek::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 1199 of file translator_gr.h.
    {
      return "0x408 Greece";
    }
getLanguageString() [2/2]
virtual QCString TranslatorGreek::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 1199 of file translator_gr.h.
    {
      return "0x408 Greece";
    }
idLanguage() [1/2]
virtual QCString TranslatorGreek::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 63 of file translator_gr.h.
    { return "greek"; }
idLanguage() [2/2]
virtual QCString TranslatorGreek::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 63 of file translator_gr.h.
    { return "greek"; }
latexCommandName() [1/2]
virtual QCString TranslatorGreek::latexCommandName () [inline], [virtual]
Set the name to be used as latex command.
Reimplemented from Translator.
Definition at line 1176 of file translator_gr.h.
    {
      QCString latex_command = Config_getString(LATEX_CMD_NAME);
      if (latex_command.isEmpty()) latex_command = "latex";
      if (Config_getBool(USE_PDFLATEX))
      {
        if (latex_command == "latex") latex_command = "xelatex";
      }
      return latex_command;
    }
References Config_getBool, Config_getString, and QCString::isEmpty().
latexCommandName() [2/2]
virtual QCString TranslatorGreek::latexCommandName () [inline], [virtual]
Set the name to be used as latex command.
Reimplemented from Translator.
Definition at line 1176 of file translator_gr.h.
    {
      QCString latex_command = Config_getString(LATEX_CMD_NAME);
      if (latex_command.isEmpty()) latex_command = "latex";
      if (Config_getBool(USE_PDFLATEX))
      {
        if (latex_command == "latex") latex_command = "xelatex";
      }
      return latex_command;
    }
References Config_getBool, Config_getString, and QCString::isEmpty().
latexFont() [1/2]
virtual QCString TranslatorGreek::latexFont () [inline], [virtual]
Reimplemented from Translator.
Definition at line 81 of file translator_gr.h.
    {
      return "\\setmainfont{Libertinus Sans}\n"
             "\\setmonofont{Courier New}\n";
    }
latexFont() [2/2]
virtual QCString TranslatorGreek::latexFont () [inline], [virtual]
Reimplemented from Translator.
Definition at line 81 of file translator_gr.h.
    {
      return "\\setmainfont{Libertinus Sans}\n"
             "\\setmonofont{Courier New}\n";
    }
latexFontenc() [1/2]
virtual QCString TranslatorGreek::latexFontenc () [inline], [virtual]
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 77 of file translator_gr.h.
    {
      return "";
    }
latexFontenc() [2/2]
virtual QCString TranslatorGreek::latexFontenc () [inline], [virtual]
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 77 of file translator_gr.h.
    {
      return "";
    }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorGreek::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 66 of file translator_gr.h.
    {
      return "\\usepackage{fontspec}\n"
             "\\usepackage[greek]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorGreek::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 66 of file translator_gr.h.
    {
      return "\\usepackage{fontspec}\n"
             "\\usepackage[greek]{babel}\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorGreek::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1904 of file translator_gr.h.
    { return " "; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorGreek::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1904 of file translator_gr.h.
    { return " "; }
trAll() [1/2]
virtual QCString TranslatorGreek::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1417 of file translator_gr.h.
    {
      return "";
    }
trAll() [2/2]
virtual QCString TranslatorGreek::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1417 of file translator_gr.h.
    {
      return "";
    }
trAndMore() [1/2]
virtual QCString TranslatorGreek::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1882 of file translator_gr.h.
    { return " "+number+" ..."; }
trAndMore() [2/2]
virtual QCString TranslatorGreek::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1882 of file translator_gr.h.
    { return " "+number+" ..."; }
trAttention() [1/2]
virtual QCString TranslatorGreek::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_gr.h.
    {
      return "";
    }
trAttention() [2/2]
virtual QCString TranslatorGreek::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_gr.h.
    {
      return "";
    }
trAuthor() [1/2]
virtual QCString TranslatorGreek::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1288 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorGreek::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1288 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorGreek::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1132 of file translator_gr.h.
    {
      return "";
    }
trBug() [2/2]
virtual QCString TranslatorGreek::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1132 of file translator_gr.h.
    {
      return "";
    }
trBugList() [1/2]
virtual QCString TranslatorGreek::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1137 of file translator_gr.h.
    {
      return " ";
    }
trBugList() [2/2]
virtual QCString TranslatorGreek::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1137 of file translator_gr.h.
    {
      return " ";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorGreek::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1538 of file translator_gr.h.
    {
      return " :";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorGreek::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1538 of file translator_gr.h.
    {
      return " :";
    }
trCallGraph() [1/2]
virtual QCString TranslatorGreek::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1422 of file translator_gr.h.
    {
      return " :";
    }
trCallGraph() [2/2]
virtual QCString TranslatorGreek::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1422 of file translator_gr.h.
    {
      return " :";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorGreek::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1857 of file translator_gr.h.
    { return " "; }
trCiteReferences() [2/2]
virtual QCString TranslatorGreek::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1857 of file translator_gr.h.
    { return " "; }
trClass() [1/2]
virtual QCString TranslatorGreek::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1208 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorGreek::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1208 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorGreek::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 517 of file translator_gr.h.
    {
      return " "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorGreek::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 517 of file translator_gr.h.
    {
      return " "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorGreek::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 392 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return " ";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorGreek::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 392 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return " ";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorGreek::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1095 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorGreek::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1095 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorGreek::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 177 of file translator_gr.h.
    { return " "; }
trClassHierarchy() [2/2]
virtual QCString TranslatorGreek::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 177 of file translator_gr.h.
    { return " "; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorGreek::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 236 of file translator_gr.h.
    { return " :"; }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorGreek::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 236 of file translator_gr.h.
    { return " :"; }
trClassMethods() [1/2]
virtual QCString TranslatorGreek::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1942 of file translator_gr.h.
    {
      return " ";
    }
trClassMethods() [2/2]
virtual QCString TranslatorGreek::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1942 of file translator_gr.h.
    {
      return " ";
    }
trCode() [1/2]
virtual QCString TranslatorGreek::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 864 of file translator_gr.h.
    {
      return "";
    }
trCode() [2/2]
virtual QCString TranslatorGreek::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 864 of file translator_gr.h.
    {
      return "";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorGreek::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 819 of file translator_gr.h.
    {
      return " "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorGreek::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 819 of file translator_gr.h.
    {
      return " "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorGreek::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 365 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorGreek::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 365 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorGreek::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1593 of file translator_gr.h.
    { return " "; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorGreek::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1593 of file translator_gr.h.
    { return " "; }
trCompoundList() [1/2]
virtual QCString TranslatorGreek::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 181 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorGreek::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 181 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorGreek::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 249 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " :";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return " :";
      }
      else
      {
        return " , , "
               " :";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorGreek::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 249 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " :";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return " :";
      }
      else
      {
        return " , , "
               " :";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorGreek::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1566 of file translator_gr.h.
    { return " :"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorGreek::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1566 of file translator_gr.h.
    { return " :"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorGreek::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1558 of file translator_gr.h.
    { return " "; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorGreek::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1558 of file translator_gr.h.
    { return " "; }
trCompoundMembers() [1/2]
virtual QCString TranslatorGreek::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 198 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorGreek::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 198 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorGreek::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 268 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" ";
      }
      else
      {
        result+="";
      }
      result+=" ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" / :";
        }
        else
        {
          result+=" :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" / :";
        }
        else
        {
          result+=" :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorGreek::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 268 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" ";
      }
      else
      {
        result+="";
      }
      result+=" ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" / :";
        }
        else
        {
          result+=" :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" / :";
        }
        else
        {
          result+=" :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorGreek::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1570 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ";
      result+=" ";
      if (!extractAll)
      {
         result+=" ";
      }
      else
      {
         result+=" :";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorGreek::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1570 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ";
      result+=" ";
      if (!extractAll)
      {
         result+=" ";
      }
      else
      {
         result+=" :";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorGreek::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1562 of file translator_gr.h.
    { return " "; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorGreek::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1562 of file translator_gr.h.
    { return " "; }
trCompoundReference() [1/2]
virtual QCString TranslatorGreek::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 592 of file translator_gr.h.
    {
      QCString result="";
      if (isTemplate) result+=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorGreek::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 592 of file translator_gr.h.
    {
      QCString result="";
      if (isTemplate) result+=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorGreek::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1634 of file translator_gr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorGreek::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1634 of file translator_gr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorGreek::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2231 of file translator_gr.h.
    {
      QCString result=" ";
      if (isLocal)
        result+=compType == ClassDef::Protocol ? " " : " ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorGreek::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2231 of file translator_gr.h.
    {
      QCString result=" ";
      if (isLocal)
        result+=compType == ClassDef::Protocol ? " " : " ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorGreek::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 493 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorGreek::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 493 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trConcept() [1/2]
virtual QCString TranslatorGreek::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2280 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=singular ? "" : "";
      return result;
    }
trConcept() [2/2]
virtual QCString TranslatorGreek::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2280 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=singular ? "" : "";
      return result;
    }
trConceptDefinition() [1/2]
virtual QCString TranslatorGreek::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2316 of file translator_gr.h.
    {
      return " ";
    }
trConceptDefinition() [2/2]
virtual QCString TranslatorGreek::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2316 of file translator_gr.h.
    {
      return " ";
    }
trConceptDocumentation() [1/2]
virtual QCString TranslatorGreek::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2303 of file translator_gr.h.
    { return " "; }
trConceptDocumentation() [2/2]
virtual QCString TranslatorGreek::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2303 of file translator_gr.h.
    { return " "; }
trConceptIndex() [1/2]
virtual QCString TranslatorGreek::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2299 of file translator_gr.h.
    { return " "; }
trConceptIndex() [2/2]
virtual QCString TranslatorGreek::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2299 of file translator_gr.h.
    { return " "; }
trConceptList() [1/2]
virtual QCString TranslatorGreek::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2295 of file translator_gr.h.
    { return " "; }
trConceptList() [2/2]
virtual QCString TranslatorGreek::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2295 of file translator_gr.h.
    { return " "; }
trConceptListDescription() [1/2]
virtual QCString TranslatorGreek::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2307 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trConceptListDescription() [2/2]
virtual QCString TranslatorGreek::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2307 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trConceptReference() [1/2]
virtual QCString TranslatorGreek::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2287 of file translator_gr.h.
    {
      QCString result(" ");
      result+=conceptName;
      return result;
    }
trConceptReference() [2/2]
virtual QCString TranslatorGreek::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2287 of file translator_gr.h.
    {
      QCString result(" ");
      result+=conceptName;
      return result;
    }
trConstantDocumentation() [1/2]
virtual QCString TranslatorGreek::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2139 of file translator_gr.h.
    {
        return " ";
    }
trConstantDocumentation() [2/2]
virtual QCString TranslatorGreek::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2139 of file translator_gr.h.
    {
        return " ";
    }
trConstantGroupReference() [1/2]
virtual QCString TranslatorGreek::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1979 of file translator_gr.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorGreek::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1979 of file translator_gr.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorGreek::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1975 of file translator_gr.h.
    { return " "; }
trConstantGroups() [2/2]
virtual QCString TranslatorGreek::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1975 of file translator_gr.h.
    { return " "; }
trConstants() [1/2]
virtual QCString TranslatorGreek::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2135 of file translator_gr.h.
    {
        return "";
    }
trConstants() [2/2]
virtual QCString TranslatorGreek::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2135 of file translator_gr.h.
    {
        return "";
    }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorGreek::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 829 of file translator_gr.h.
    {
      return " Constructor & Destructor";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorGreek::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 829 of file translator_gr.h.
    {
      return " Constructor & Destructor";
    }
trCopyright() [1/2]
virtual QCString TranslatorGreek::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1861 of file translator_gr.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorGreek::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1861 of file translator_gr.h.
    { return "Copyright"; }
trCustomReference() [1/2]
virtual QCString TranslatorGreek::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2131 of file translator_gr.h.
    { return QCString(" ")+name; }
References setup::name.
trCustomReference() [2/2]
virtual QCString TranslatorGreek::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2131 of file translator_gr.h.
    { return QCString(" ")+name; }
References setup::name.
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorGreek::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2262 of file translator_gr.h.
    {
        return " ";
    }
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorGreek::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2262 of file translator_gr.h.
    {
        return " ";
    }
trDataMembers() [1/2]
virtual QCString TranslatorGreek::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2258 of file translator_gr.h.
    {
        return " ";
    }
trDataMembers() [2/2]
virtual QCString TranslatorGreek::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2258 of file translator_gr.h.
    {
        return " ";
    }
trDataTypes() [1/2]
virtual QCString TranslatorGreek::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1617 of file translator_gr.h.
    { return " "; }
trDataTypes() [2/2]
virtual QCString TranslatorGreek::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1617 of file translator_gr.h.
    { return " "; }
trDate() [1/2]
virtual QCString TranslatorGreek::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 531 of file translator_gr.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorGreek::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 531 of file translator_gr.h.
    { return ""; }
trDateTime() [1/2]
virtual QCString TranslatorGreek::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1816 of file translator_gr.h.
    {
      static const char *days[] = { "","","","","","","" };
      static const char *months[] = { "","","","","","","","","","","","" };
      QCString sdate;
      sdate.sprintf("%s %.2d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorGreek::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1816 of file translator_gr.h.
    {
      static const char *days[] = { "","","","","","","" };
      static const char *months[] = { "","","","","","","","","","","","" };
      QCString sdate;
      sdate.sprintf("%s %.2d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorGreek::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1832 of file translator_gr.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorGreek::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1832 of file translator_gr.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorGreek::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1846 of file translator_gr.h.
    {
      static const char *dayPeriod[] = { "..", ".." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorGreek::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1846 of file translator_gr.h.
    {
      static const char *dayPeriod[] = { "..", ".." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorGreek::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 796 of file translator_gr.h.
    {
      return " @0 @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorGreek::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 796 of file translator_gr.h.
    {
      return " @0 @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorGreek::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 165 of file translator_gr.h.
    { return " "; }
trDefinedIn() [2/2]
virtual QCString TranslatorGreek::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 165 of file translator_gr.h.
    { return " "; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorGreek::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 800 of file translator_gr.h.
    {
      return " @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorGreek::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 800 of file translator_gr.h.
    {
      return " @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorGreek::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 463 of file translator_gr.h.
    { return " "; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorGreek::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 463 of file translator_gr.h.
    { return " "; }
trDefines() [1/2]
virtual QCString TranslatorGreek::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 427 of file translator_gr.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorGreek::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 427 of file translator_gr.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorGreek::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1122 of file translator_gr.h.
    {
      return ":";
    }
trDefineValue() [2/2]
virtual QCString TranslatorGreek::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1122 of file translator_gr.h.
    {
      return ":";
    }
trDeprecated() [1/2]
virtual QCString TranslatorGreek::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 809 of file translator_gr.h.
    {
      return "";
    }
trDeprecated() [2/2]
virtual QCString TranslatorGreek::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 809 of file translator_gr.h.
    {
      return "";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorGreek::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1345 of file translator_gr.h.
    {
      return " ";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorGreek::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1345 of file translator_gr.h.
    {
      return " ";
    }
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorGreek::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2272 of file translator_gr.h.
    { return " "; }
Referenced by trClassDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorGreek::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2272 of file translator_gr.h.
    { return " "; }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorGreek::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2023 of file translator_gr.h.
    { return " "; }
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorGreek::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2023 of file translator_gr.h.
    { return " "; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorGreek::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2037 of file translator_gr.h.
    { return " "; }
trDesignUnitIndex() [2/2]
virtual QCString TranslatorGreek::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2037 of file translator_gr.h.
    { return " "; }
trDesignUnitList() [1/2]
virtual QCString TranslatorGreek::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2026 of file translator_gr.h.
    { return " "; }
trDesignUnitList() [2/2]
virtual QCString TranslatorGreek::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2026 of file translator_gr.h.
    { return " "; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorGreek::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2032 of file translator_gr.h.
    {
        return " :";
    }
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorGreek::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2032 of file translator_gr.h.
    {
        return " :";
    }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorGreek::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2029 of file translator_gr.h.
    { return " "; }
trDesignUnitMembers() [2/2]
virtual QCString TranslatorGreek::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2029 of file translator_gr.h.
    { return " "; }
trDesignUnits() [1/2]
virtual QCString TranslatorGreek::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2040 of file translator_gr.h.
    { return " "; }
trDesignUnits() [2/2]
virtual QCString TranslatorGreek::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2040 of file translator_gr.h.
    { return " "; }
trDetailedDescription() [1/2]
virtual QCString TranslatorGreek::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 98 of file translator_gr.h.
    { return " "; }
trDetailedDescription() [2/2]
virtual QCString TranslatorGreek::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 98 of file translator_gr.h.
    { return " "; }
trDetailLevel() [1/2]
virtual QCString TranslatorGreek::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1874 of file translator_gr.h.
    { return " "; }
trDetailLevel() [2/2]
virtual QCString TranslatorGreek::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1874 of file translator_gr.h.
    { return " "; }
trDictionaries() [1/2]
virtual QCString TranslatorGreek::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2151 of file translator_gr.h.
    {
        return "";
    }
trDictionaries() [2/2]
virtual QCString TranslatorGreek::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2151 of file translator_gr.h.
    {
        return "";
    }
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorGreek::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2155 of file translator_gr.h.
    {
        return " ";
    }
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorGreek::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2155 of file translator_gr.h.
    {
        return " ";
    }
trDir() [1/2]
virtual QCString TranslatorGreek::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1512 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorGreek::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1512 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorGreek::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1865 of file translator_gr.h.
    { return QCString(" ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorGreek::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1865 of file translator_gr.h.
    { return QCString(" ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorGreek::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1494 of file translator_gr.h.
    { return " "; }
trDirDocumentation() [2/2]
virtual QCString TranslatorGreek::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1494 of file translator_gr.h.
    { return " "; }
trDirectories() [1/2]
virtual QCString TranslatorGreek::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1500 of file translator_gr.h.
    { return ""; }
trDirectories() [2/2]
virtual QCString TranslatorGreek::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1500 of file translator_gr.h.
    { return ""; }
trDirIndex() [1/2]
virtual QCString TranslatorGreek::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1488 of file translator_gr.h.
    { return " "; }
trDirIndex() [2/2]
virtual QCString TranslatorGreek::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1488 of file translator_gr.h.
    { return " "; }
trDirReference() [1/2]
virtual QCString TranslatorGreek::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1506 of file translator_gr.h.
    { QCString result=QCString(" ") + dirName; return result; }
trDirReference() [2/2]
virtual QCString TranslatorGreek::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1506 of file translator_gr.h.
    { QCString result=QCString(" ") + dirName; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorGreek::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1755 of file translator_gr.h.
    {
      return " "+QCString(name);
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorGreek::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1755 of file translator_gr.h.
    {
      return " "+QCString(name);
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorGreek::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 347 of file translator_gr.h.
    { return ""; }
trDocumentation() [2/2]
virtual QCString TranslatorGreek::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 347 of file translator_gr.h.
    { return ""; }
trEnumerations() [1/2]
virtual QCString TranslatorGreek::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 439 of file translator_gr.h.
    { return ""; }
trEnumerations() [2/2]
virtual QCString TranslatorGreek::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 439 of file translator_gr.h.
    { return ""; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorGreek::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 475 of file translator_gr.h.
    { return " "; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorGreek::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 475 of file translator_gr.h.
    { return " "; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorGreek::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1546 of file translator_gr.h.
    { return " "; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorGreek::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1546 of file translator_gr.h.
    { return " "; }
trEnumerationValues() [1/2]
virtual QCString TranslatorGreek::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 457 of file translator_gr.h.
    { return " "; }
trEnumerationValues() [2/2]
virtual QCString TranslatorGreek::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 457 of file translator_gr.h.
    { return " "; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorGreek::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1886 of file translator_gr.h.
    { QCString result = " ";
      if (single) result += "o o"; else result += " ";
      result+=":";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorGreek::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1886 of file translator_gr.h.
    { QCString result = " ";
      if (single) result += "o o"; else result += " ";
      result+=":";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorGreek::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 157 of file translator_gr.h.
    { return " "; }
trEnumName() [2/2]
virtual QCString TranslatorGreek::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 157 of file translator_gr.h.
    { return " "; }
trEnumReference() [1/2]
virtual QCString TranslatorGreek::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1894 of file translator_gr.h.
    { return QCString(" ") + name; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorGreek::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1894 of file translator_gr.h.
    { return QCString(" ") + name; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorGreek::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 161 of file translator_gr.h.
    { return " "; }
trEnumValue() [2/2]
virtual QCString TranslatorGreek::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 161 of file translator_gr.h.
    { return " "; }
trEventDocumentation() [1/2]
virtual QCString TranslatorGreek::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1362 of file translator_gr.h.
    {
      return " ";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorGreek::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1362 of file translator_gr.h.
    {
      return " ";
    }
trEvents() [1/2]
virtual QCString TranslatorGreek::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1357 of file translator_gr.h.
    {
      return "";
    }
trEvents() [2/2]
virtual QCString TranslatorGreek::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1357 of file translator_gr.h.
    {
      return "";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorGreek::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 417 of file translator_gr.h.
    { return " "; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorGreek::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 417 of file translator_gr.h.
    { return " "; }
trExamples() [1/2]
virtual QCString TranslatorGreek::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 228 of file translator_gr.h.
    { return ""; }
trExamples() [2/2]
virtual QCString TranslatorGreek::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 228 of file translator_gr.h.
    { return ""; }
trExamplesDescription() [1/2]
virtual QCString TranslatorGreek::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 332 of file translator_gr.h.
    { return " :"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorGreek::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 332 of file translator_gr.h.
    { return " :"; }
trExceptionDocumentation() [1/2]
virtual QCString TranslatorGreek::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2227 of file translator_gr.h.
    {
        return " ";
    }
trExceptionDocumentation() [2/2]
virtual QCString TranslatorGreek::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2227 of file translator_gr.h.
    {
        return " ";
    }
trExceptionHierarchy() [1/2]
virtual QCString TranslatorGreek::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2219 of file translator_gr.h.
    {
        return " ";
    }
trExceptionHierarchy() [2/2]
virtual QCString TranslatorGreek::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2219 of file translator_gr.h.
    {
        return " ";
    }
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorGreek::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2223 of file translator_gr.h.
    {
        return " :";
    }
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorGreek::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2223 of file translator_gr.h.
    {
        return " :";
    }
trExceptionIndex() [1/2]
virtual QCString TranslatorGreek::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2207 of file translator_gr.h.
    {
        return " ";
    }
trExceptionIndex() [2/2]
virtual QCString TranslatorGreek::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2207 of file translator_gr.h.
    {
        return " ";
    }
trExceptionList() [1/2]
virtual QCString TranslatorGreek::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2211 of file translator_gr.h.
    {
        return " ";
    }
trExceptionList() [2/2]
virtual QCString TranslatorGreek::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2211 of file translator_gr.h.
    {
        return " ";
    }
trExceptionListDescription() [1/2]
virtual QCString TranslatorGreek::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2215 of file translator_gr.h.
    {
        return " :";
    }
trExceptionListDescription() [2/2]
virtual QCString TranslatorGreek::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2215 of file translator_gr.h.
    {
        return " :";
    }
trExceptions() [1/2]
virtual QCString TranslatorGreek::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 547 of file translator_gr.h.
    { return ""; }
trExceptions() [2/2]
virtual QCString TranslatorGreek::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 547 of file translator_gr.h.
    { return ""; }
trExtendsClass() [1/2]
virtual QCString TranslatorGreek::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1934 of file translator_gr.h.
    {
      return " @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorGreek::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1934 of file translator_gr.h.
    {
      return " @0.";
    }
trFile() [1/2]
virtual QCString TranslatorGreek::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1219 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorGreek::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1219 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorGreek::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 411 of file translator_gr.h.
    { return " "; }
trFileDocumentation() [2/2]
virtual QCString TranslatorGreek::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 411 of file translator_gr.h.
    { return " "; }
trFileIn() [1/2]
virtual QCString TranslatorGreek::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1792 of file translator_gr.h.
    {
      return " "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorGreek::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1792 of file translator_gr.h.
    {
      return " "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorGreek::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 380 of file translator_gr.h.
    { return " "; }
trFileIndex() [2/2]
virtual QCString TranslatorGreek::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 380 of file translator_gr.h.
    { return " "; }
trFileList() [1/2]
virtual QCString TranslatorGreek::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 194 of file translator_gr.h.
    { return " "; }
trFileList() [2/2]
virtual QCString TranslatorGreek::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 194 of file translator_gr.h.
    { return " "; }
trFileListDescription() [1/2]
virtual QCString TranslatorGreek::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 240 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorGreek::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 240 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorGreek::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 211 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorGreek::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 211 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorGreek::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 310 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , , , ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (extractAll)
        result+=" :";
      else
        result+=" :";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorGreek::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 310 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , , , ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (extractAll)
        result+=" :";
      else
        result+=" :";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorGreek::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 614 of file translator_gr.h.
    {
      QCString result=" ";
      result+=fileName;
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorGreek::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 614 of file translator_gr.h.
    {
      QCString result=" ";
      result+=fileName;
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorGreek::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 574 of file translator_gr.h.
    { return ""; }
trFriends() [2/2]
virtual QCString TranslatorGreek::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 574 of file translator_gr.h.
    { return ""; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorGreek::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2043 of file translator_gr.h.
    { return "//"; }
trFunctionAndProc() [2/2]
virtual QCString TranslatorGreek::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2043 of file translator_gr.h.
    { return "//"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorGreek::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 481 of file translator_gr.h.
    { return " "; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorGreek::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 481 of file translator_gr.h.
    { return " "; }
trFunctions() [1/2]
virtual QCString TranslatorGreek::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 445 of file translator_gr.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorGreek::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 445 of file translator_gr.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorGreek::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 508 of file translator_gr.h.
    {
      QCString result=" "+date;
      if (!projName.isEmpty()) result+=" "+projName;
      result+=" ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorGreek::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 508 of file translator_gr.h.
    {
      QCString result=" "+date;
      if (!projName.isEmpty()) result+=" "+projName;
      result+=" ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorGreek::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 149 of file translator_gr.h.
    { QCString result=" Doxygen";
      if (!s.isEmpty()) result+=" "+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorGreek::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 149 of file translator_gr.h.
    { QCString result=" Doxygen";
      if (!s.isEmpty()) result+=" "+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorGreek::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 551 of file translator_gr.h.
    { return " "; }
trGeneratedBy() [2/2]
virtual QCString TranslatorGreek::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 551 of file translator_gr.h.
    { return " "; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorGreek::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 752 of file translator_gr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorGreek::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 752 of file translator_gr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorGreek::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1702 of file translator_gr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorGreek::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1702 of file translator_gr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorGreek::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1275 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorGreek::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1275 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorGreek::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1767 of file translator_gr.h.
    {
      return " ";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorGreek::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1767 of file translator_gr.h.
    {
      return " ";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorGreek::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 839 of file translator_gr.h.
    {
      return " .";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorGreek::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 839 of file translator_gr.h.
    {
      return " .";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorGreek::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 872 of file translator_gr.h.
    {
      return " ";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorGreek::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 872 of file translator_gr.h.
    {
      return " ";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorGreek::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 834 of file translator_gr.h.
    {
      return " .";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorGreek::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 834 of file translator_gr.h.
    {
      return " .";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorGreek::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_gr.h.
    {
      return " ";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorGreek::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_gr.h.
    {
      return " ";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorGreek::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 868 of file translator_gr.h.
    {
      return " ";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorGreek::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 868 of file translator_gr.h.
    {
      return " ";
    }
trGroup() [1/2]
virtual QCString TranslatorGreek::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1242 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorGreek::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1242 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorGreek::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 359 of file translator_gr.h.
    { return " "; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorGreek::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 359 of file translator_gr.h.
    { return " "; }
trImplementedFromList() [1/2]
virtual QCString TranslatorGreek::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1313 of file translator_gr.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorGreek::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1313 of file translator_gr.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorGreek::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1321 of file translator_gr.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorGreek::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1321 of file translator_gr.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorGreek::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 968 of file translator_gr.h.
    {
      return " "
             " :";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorGreek::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 968 of file translator_gr.h.
    {
      return " "
             " :";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorGreek::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 824 of file translator_gr.h.
    {
      return " "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorGreek::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 824 of file translator_gr.h.
    {
      return " "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorGreek::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1801 of file translator_gr.h.
    {
      return " "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorGreek::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1801 of file translator_gr.h.
    {
      return " "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorGreek::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 143 of file translator_gr.h.
    { return ", ."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorGreek::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 143 of file translator_gr.h.
    { return ", ."; }
trInheritedByList() [1/2]
virtual QCString TranslatorGreek::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 686 of file translator_gr.h.
    {
      return QCString(" ")+(numEntries==1?" ":" ")+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorGreek::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 686 of file translator_gr.h.
    {
      return QCString(" ")+(numEntries==1?" ":" ")+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorGreek::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1898 of file translator_gr.h.
    { return QCString(members)+" "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorGreek::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1898 of file translator_gr.h.
    { return QCString(members)+" "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorGreek::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 678 of file translator_gr.h.
    {
      return QCString(" ")+(numEntries==1?" ":" ")+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorGreek::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 678 of file translator_gr.h.
    {
      return QCString(" ")+(numEntries==1?" ":" ")+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorGreek::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 859 of file translator_gr.h.
    {
      return " :";
    }
trInitialValue() [2/2]
virtual QCString TranslatorGreek::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 859 of file translator_gr.h.
    {
      return " :";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorGreek::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1950 of file translator_gr.h.
    {
      return " ";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorGreek::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1950 of file translator_gr.h.
    {
      return " ";
    }
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorGreek::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2183 of file translator_gr.h.
    {
        return " ";
    }
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorGreek::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2183 of file translator_gr.h.
    {
        return " ";
    }
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorGreek::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2175 of file translator_gr.h.
    {
        return " ";
    }
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorGreek::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2175 of file translator_gr.h.
    {
        return " ";
    }
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorGreek::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2179 of file translator_gr.h.
    {
        return " :";
    }
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorGreek::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2179 of file translator_gr.h.
    {
        return " :";
    }
trInterfaceIndex() [1/2]
virtual QCString TranslatorGreek::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2163 of file translator_gr.h.
    {
        return " ";
    }
trInterfaceIndex() [2/2]
virtual QCString TranslatorGreek::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2163 of file translator_gr.h.
    {
        return " ";
    }
trInterfaceList() [1/2]
virtual QCString TranslatorGreek::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2167 of file translator_gr.h.
    {
        return " ";
    }
trInterfaceList() [2/2]
virtual QCString TranslatorGreek::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2167 of file translator_gr.h.
    {
        return " ";
    }
trInterfaceListDescription() [1/2]
virtual QCString TranslatorGreek::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2171 of file translator_gr.h.
    {
        return " :";
    }
trInterfaceListDescription() [2/2]
virtual QCString TranslatorGreek::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2171 of file translator_gr.h.
    {
        return " :";
    }
trInterfaces() [1/2]
virtual QCString TranslatorGreek::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1967 of file translator_gr.h.
    { return " "; }
trInterfaces() [2/2]
virtual QCString TranslatorGreek::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1967 of file translator_gr.h.
    { return " "; }
trInvariant() [1/2]
virtual QCString TranslatorGreek::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 854 of file translator_gr.h.
    {
      return "";
    }
trInvariant() [2/2]
virtual QCString TranslatorGreek::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 854 of file translator_gr.h.
    {
      return "";
    }
trISOLang() [1/2]
virtual QCString TranslatorGreek::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 72 of file translator_gr.h.
    {
      return "el";
    }
trISOLang() [2/2]
virtual QCString TranslatorGreek::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 72 of file translator_gr.h.
    {
      return "el";
    }
trLegend() [1/2]
virtual QCString TranslatorGreek::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1055 of file translator_gr.h.
    {
      return "";
    }
trLegend() [2/2]
virtual QCString TranslatorGreek::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1055 of file translator_gr.h.
    {
      return "";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorGreek::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 990 of file translator_gr.h.
    {
      return
        " "
        " doxygen.<p>\n"
        " :"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " :"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        " :\n"
        "</p>\n"
        "<ul>\n"
        "<li> "
        " .\n"
        "<li> .\n"
        "<li> .\n"
        "<li> "
        " . % "
        " ."
        "</ul>\n"
        "<p>\n"
        " :\n"
        "</p>\n"
        "<ul>\n"
        "<li> "
        " .</li>\n"
        "<li> .</li>\n"
        "<li> .</li>\n"
        "<li> "
        " . () "
        " .</li>\n"
        "<li> "
        " . "
        " .</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorGreek::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 990 of file translator_gr.h.
    {
      return
        " "
        " doxygen.<p>\n"
        " :"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " :"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        " :\n"
        "</p>\n"
        "<ul>\n"
        "<li> "
        " .\n"
        "<li> .\n"
        "<li> .\n"
        "<li> "
        " . % "
        " ."
        "</ul>\n"
        "<p>\n"
        " :\n"
        "</p>\n"
        "<ul>\n"
        "<li> "
        " .</li>\n"
        "<li> .</li>\n"
        "<li> .</li>\n"
        "<li> "
        " . () "
        " .</li>\n"
        "<li> "
        " . "
        " .</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorGreek::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 983 of file translator_gr.h.
    {
      return " ";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorGreek::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 983 of file translator_gr.h.
    {
      return " ";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorGreek::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 131 of file translator_gr.h.
    { return " "; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorGreek::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 131 of file translator_gr.h.
    { return " "; }
trLoading() [1/2]
virtual QCString TranslatorGreek::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1761 of file translator_gr.h.
    {
      return "...";
    }
trLoading() [2/2]
virtual QCString TranslatorGreek::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1761 of file translator_gr.h.
    {
      return "...";
    }
trMainPage() [1/2]
virtual QCString TranslatorGreek::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 783 of file translator_gr.h.
    { return " "; }
trMainPage() [2/2]
virtual QCString TranslatorGreek::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 783 of file translator_gr.h.
    { return " "; }
trMember() [1/2]
virtual QCString TranslatorGreek::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1264 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorGreek::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1264 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorGreek::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 114 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorGreek::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 114 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorGreek::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 106 of file translator_gr.h.
    { return " "; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorGreek::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 106 of file translator_gr.h.
    { return " "; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorGreek::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 110 of file translator_gr.h.
    { return " "; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorGreek::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 110 of file translator_gr.h.
    { return " "; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorGreek::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1554 of file translator_gr.h.
    { return " / "; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorGreek::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1554 of file translator_gr.h.
    { return " / "; }
trMemberList() [1/2]
virtual QCString TranslatorGreek::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 135 of file translator_gr.h.
    { return " "; }
trMemberList() [2/2]
virtual QCString TranslatorGreek::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 135 of file translator_gr.h.
    { return " "; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorGreek::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 102 of file translator_gr.h.
    { return " "; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorGreek::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 102 of file translator_gr.h.
    { return " "; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorGreek::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1957 of file translator_gr.h.
    {
      return " ";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorGreek::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1957 of file translator_gr.h.
    {
      return " ";
    }
trModule() [1/2]
virtual QCString TranslatorGreek::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1693 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorGreek::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1693 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorGreek::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 386 of file translator_gr.h.
    { return " "; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorGreek::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 386 of file translator_gr.h.
    { return " "; }
trModuleIndex() [1/2]
virtual QCString TranslatorGreek::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 353 of file translator_gr.h.
    { return " "; }
trModuleIndex() [2/2]
virtual QCString TranslatorGreek::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 353 of file translator_gr.h.
    { return " "; }
trModuleReference() [1/2]
virtual QCString TranslatorGreek::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1655 of file translator_gr.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorGreek::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1655 of file translator_gr.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorGreek::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 173 of file translator_gr.h.
    { return ""; }
trModules() [2/2]
virtual QCString TranslatorGreek::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 173 of file translator_gr.h.
    { return ""; }
trModulesDescription() [1/2]
virtual QCString TranslatorGreek::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 340 of file translator_gr.h.
    { return " :"; }
trModulesDescription() [2/2]
virtual QCString TranslatorGreek::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 340 of file translator_gr.h.
    { return " :"; }
trModulesIndex() [1/2]
virtual QCString TranslatorGreek::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1686 of file translator_gr.h.
    { return " "; }
trModulesIndex() [2/2]
virtual QCString TranslatorGreek::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1686 of file translator_gr.h.
    { return " "; }
trModulesList() [1/2]
virtual QCString TranslatorGreek::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1621 of file translator_gr.h.
    { return " "; }
trModulesList() [2/2]
virtual QCString TranslatorGreek::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1621 of file translator_gr.h.
    { return " "; }
trModulesListDescription() [1/2]
virtual QCString TranslatorGreek::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1625 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorGreek::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1625 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorGreek::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1667 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
      {
        result+=" :";
      }
      else
      {
        result+=" :";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorGreek::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1667 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
      {
        result+=" :";
      }
      else
      {
        result+=" :";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorGreek::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1663 of file translator_gr.h.
    { return " "; }
trModulesMembers() [2/2]
virtual QCString TranslatorGreek::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1663 of file translator_gr.h.
    { return " "; }
trMonth() [1/2]
virtual QCString TranslatorGreek::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1839 of file translator_gr.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorGreek::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1839 of file translator_gr.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
virtual QCString TranslatorGreek::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 127 of file translator_gr.h.
    { return "..."; }
trMore() [2/2]
virtual QCString TranslatorGreek::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 127 of file translator_gr.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorGreek::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1230 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      result+=" ";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorGreek::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1230 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      result+=" ";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorGreek::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 732 of file translator_gr.h.
    { return " "; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorGreek::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 732 of file translator_gr.h.
    { return " "; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorGreek::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 726 of file translator_gr.h.
    { return " "; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorGreek::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 726 of file translator_gr.h.
    { return " "; }
trNamespaceList() [1/2]
virtual QCString TranslatorGreek::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 559 of file translator_gr.h.
    { return " "; }
trNamespaceList() [2/2]
virtual QCString TranslatorGreek::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 559 of file translator_gr.h.
    { return " "; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorGreek::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 563 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorGreek::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 563 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorGreek::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 712 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
        result+=" :";
      else
        result+=" :";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorGreek::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 712 of file translator_gr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
        result+=" :";
      else
        result+=" :";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorGreek::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 708 of file translator_gr.h.
    { return " "; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorGreek::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 708 of file translator_gr.h.
    { return " "; }
trNamespaceReference() [1/2]
virtual QCString TranslatorGreek::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 622 of file translator_gr.h.
    {
      QCString result=" ";
      result+=namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorGreek::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 622 of file translator_gr.h.
    {
      QCString result=" ";
      result+=namespaceName;
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorGreek::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 742 of file translator_gr.h.
    { return " "; }
trNamespaces() [2/2]
virtual QCString TranslatorGreek::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 742 of file translator_gr.h.
    { return " "; }
trNoMatches() [1/2]
virtual QCString TranslatorGreek::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1779 of file translator_gr.h.
    {
      return " ";
    }
trNoMatches() [2/2]
virtual QCString TranslatorGreek::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1779 of file translator_gr.h.
    {
      return " ";
    }
trNote() [1/2]
virtual QCString TranslatorGreek::trNote () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_gr.h.
    {
      return "";
    }
trNote() [2/2]
virtual QCString TranslatorGreek::trNote () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_gr.h.
    {
      return "";
    }
trOperationDocumentation() [1/2]
virtual QCString TranslatorGreek::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2254 of file translator_gr.h.
    {
        return " ";
    }
trOperationDocumentation() [2/2]
virtual QCString TranslatorGreek::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2254 of file translator_gr.h.
    {
        return " ";
    }
trOperations() [1/2]
virtual QCString TranslatorGreek::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2250 of file translator_gr.h.
    {
        return "";
    }
trOperations() [2/2]
virtual QCString TranslatorGreek::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2250 of file translator_gr.h.
    {
        return "";
    }
trOverloadText() [1/2]
virtual QCString TranslatorGreek::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1526 of file translator_gr.h.
    {
       return " -, "
              " . "
              " .";
    }
trOverloadText() [2/2]
virtual QCString TranslatorGreek::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1526 of file translator_gr.h.
    {
       return " -, "
              " . "
              " .";
    }
trPackage() [1/2]
virtual QCString TranslatorGreek::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1107 of file translator_gr.h.
    {
      return " "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorGreek::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1107 of file translator_gr.h.
    {
      return " "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorGreek::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1398 of file translator_gr.h.
    {
      return " ";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorGreek::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1398 of file translator_gr.h.
    {
      return " ";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorGreek::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1380 of file translator_gr.h.
    {
      return " ";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorGreek::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1380 of file translator_gr.h.
    {
      return " ";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorGreek::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1112 of file translator_gr.h.
    {
      return " ():";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorGreek::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1112 of file translator_gr.h.
    {
      return " ():";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorGreek::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1384 of file translator_gr.h.
    {
      return " ";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorGreek::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1384 of file translator_gr.h.
    {
      return " ";
    }
trPackages() [1/2]
virtual QCString TranslatorGreek::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1117 of file translator_gr.h.
    {
      return "";
    }
trPackages() [2/2]
virtual QCString TranslatorGreek::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1117 of file translator_gr.h.
    {
      return "";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorGreek::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1373 of file translator_gr.h.
    {
      return " ";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorGreek::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1373 of file translator_gr.h.
    {
      return " ";
    }
trPage() [1/2]
virtual QCString TranslatorGreek::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1253 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorGreek::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1253 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorGreek::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 789 of file translator_gr.h.
    { return "."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorGreek::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 789 of file translator_gr.h.
    { return "."; }
trPageIndex() [1/2]
virtual QCString TranslatorGreek::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 880 of file translator_gr.h.
    {
      return " ";
    }
trPageIndex() [2/2]
virtual QCString TranslatorGreek::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 880 of file translator_gr.h.
    {
      return " ";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorGreek::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1915 of file translator_gr.h.
    {
      QCString opt = enable ? "" : "";
      return " "+opt+" ";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorGreek::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1915 of file translator_gr.h.
    {
      QCString opt = enable ? "" : "";
      return " "+opt+" ";
    }
trParameters() [1/2]
virtual QCString TranslatorGreek::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 543 of file translator_gr.h.
    { return ""; }
trParameters() [2/2]
virtual QCString TranslatorGreek::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 543 of file translator_gr.h.
    { return ""; }
trPostcondition() [1/2]
virtual QCString TranslatorGreek::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 849 of file translator_gr.h.
    {
      return "";
    }
trPostcondition() [2/2]
virtual QCString TranslatorGreek::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 849 of file translator_gr.h.
    {
      return "";
    }
trPrecondition() [1/2]
virtual QCString TranslatorGreek::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 844 of file translator_gr.h.
    {
      return "";
    }
trPrecondition() [2/2]
virtual QCString TranslatorGreek::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 844 of file translator_gr.h.
    {
      return "";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorGreek::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_gr.h.
    {
      return " ";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorGreek::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_gr.h.
    {
      return " ";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorGreek::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 643 of file translator_gr.h.
    { return " "; }
trPrivateMembers() [2/2]
virtual QCString TranslatorGreek::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 643 of file translator_gr.h.
    { return " "; }
trPrivateSlots() [1/2]
virtual QCString TranslatorGreek::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_gr.h.
    { return " "; }
trPrivateSlots() [2/2]
virtual QCString TranslatorGreek::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_gr.h.
    { return " "; }
trPrivateTypes() [1/2]
virtual QCString TranslatorGreek::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_gr.h.
    {
      return " ";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorGreek::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_gr.h.
    {
      return " ";
    }
trProperties() [1/2]
virtual QCString TranslatorGreek::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1080 of file translator_gr.h.
    {
      return "";
    }
trProperties() [2/2]
virtual QCString TranslatorGreek::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1080 of file translator_gr.h.
    {
      return "";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorGreek::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1085 of file translator_gr.h.
    {
      return " ";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorGreek::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1085 of file translator_gr.h.
    {
      return " ";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorGreek::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_gr.h.
    {
      return " ";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorGreek::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_gr.h.
    {
      return " ";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorGreek::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 637 of file translator_gr.h.
    { return " "; }
trProtectedMembers() [2/2]
virtual QCString TranslatorGreek::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 637 of file translator_gr.h.
    { return " "; }
trProtectedSlots() [1/2]
virtual QCString TranslatorGreek::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 639 of file translator_gr.h.
    { return " "; }
trProtectedSlots() [2/2]
virtual QCString TranslatorGreek::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 639 of file translator_gr.h.
    { return " "; }
trProtectedTypes() [1/2]
virtual QCString TranslatorGreek::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_gr.h.
    {
      return " ";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorGreek::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_gr.h.
    {
      return " ";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorGreek::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1925 of file translator_gr.h.
    {
      return " @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorGreek::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1925 of file translator_gr.h.
    {
      return " @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorGreek::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorGreek::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_gr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorGreek::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 629 of file translator_gr.h.
    { return " "; }
trPublicMembers() [2/2]
virtual QCString TranslatorGreek::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 629 of file translator_gr.h.
    { return " "; }
trPublicSlots() [1/2]
virtual QCString TranslatorGreek::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 631 of file translator_gr.h.
    { return " "; }
trPublicSlots() [2/2]
virtual QCString TranslatorGreek::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 631 of file translator_gr.h.
    { return " "; }
trPublicTypes() [1/2]
virtual QCString TranslatorGreek::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_gr.h.
    {
      return " ";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorGreek::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_gr.h.
    {
      return " ";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorGreek::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 956 of file translator_gr.h.
    {
      return " ";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorGreek::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 956 of file translator_gr.h.
    {
      return " ";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorGreek::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 421 of file translator_gr.h.
    { return " "; }
trReferenceManual() [2/2]
virtual QCString TranslatorGreek::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 421 of file translator_gr.h.
    { return " "; }
trReferences() [1/2]
virtual QCString TranslatorGreek::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1301 of file translator_gr.h.
    {
      return "";
    }
trReferences() [2/2]
virtual QCString TranslatorGreek::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1301 of file translator_gr.h.
    {
      return "";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorGreek::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 694 of file translator_gr.h.
    {
      return QCString(" ")+(numEntries==1?" ":" ")+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorGreek::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 694 of file translator_gr.h.
    {
      return QCString(" ")+(numEntries==1?" ":" ")+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorGreek::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 702 of file translator_gr.h.
    {
      return QCString(" ")+(numEntries==1?" ":" ")+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorGreek::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 702 of file translator_gr.h.
    {
      return QCString(" ")+(numEntries==1?" ":" ")+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorGreek::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 584 of file translator_gr.h.
    { return " "; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorGreek::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 584 of file translator_gr.h.
    { return " "; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorGreek::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 90 of file translator_gr.h.
    { return " "; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorGreek::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 90 of file translator_gr.h.
    { return " "; }
trRelatedPages() [1/2]
virtual QCString TranslatorGreek::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 224 of file translator_gr.h.
    { return " "; }
trRelatedPages() [2/2]
virtual QCString TranslatorGreek::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 224 of file translator_gr.h.
    { return " "; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorGreek::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 336 of file translator_gr.h.
    { return " :"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorGreek::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 336 of file translator_gr.h.
    { return " :"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorGreek::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 94 of file translator_gr.h.
    { return "(.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorGreek::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 94 of file translator_gr.h.
    { return "(.)"; }
trRemarks() [1/2]
virtual QCString TranslatorGreek::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 960 of file translator_gr.h.
    {
      return "";
    }
trRemarks() [2/2]
virtual QCString TranslatorGreek::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 960 of file translator_gr.h.
    {
      return "";
    }
trReturns() [1/2]
virtual QCString TranslatorGreek::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 535 of file translator_gr.h.
    { return ""; }
trReturns() [2/2]
virtual QCString TranslatorGreek::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 535 of file translator_gr.h.
    { return ""; }
trReturnValues() [1/2]
virtual QCString TranslatorGreek::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 778 of file translator_gr.h.
    { return " "; }
trReturnValues() [2/2]
virtual QCString TranslatorGreek::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 778 of file translator_gr.h.
    { return " "; }
trRTFansicp() [1/2]
virtual QCString TranslatorGreek::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1171 of file translator_gr.h.
    {
      return "1253";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorGreek::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1171 of file translator_gr.h.
    {
      return "1253";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorGreek::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1189 of file translator_gr.h.
    {
      return "161";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorGreek::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1189 of file translator_gr.h.
    {
      return "161";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorGreek::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1195 of file translator_gr.h.
    {
      return "";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorGreek::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1195 of file translator_gr.h.
    {
      return "";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorGreek::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1333 of file translator_gr.h.
    {
      return " ";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorGreek::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1333 of file translator_gr.h.
    {
      return " ";
    }
trSearch() [1/2]
virtual QCString TranslatorGreek::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 232 of file translator_gr.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorGreek::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 232 of file translator_gr.h.
    { return ""; }
trSearching() [1/2]
virtual QCString TranslatorGreek::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1773 of file translator_gr.h.
    {
      return "...";
    }
trSearching() [2/2]
virtual QCString TranslatorGreek::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1773 of file translator_gr.h.
    {
      return "...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorGreek::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1465 of file translator_gr.h.
    {
      return ":";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorGreek::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1465 of file translator_gr.h.
    {
      return ":";
    }
trSearchResults() [1/2]
virtual QCString TranslatorGreek::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1446 of file translator_gr.h.
    {
      if (numDocuments==0)
      {
        return ", .";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> .";
      }
      else
      {
        return " <b>$num</b> . "
               " .";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorGreek::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1446 of file translator_gr.h.
    {
      if (numDocuments==0)
      {
        return ", .";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> .";
      }
      else
      {
        return " <b>$num</b> . "
               " .";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorGreek::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1434 of file translator_gr.h.
    {
      return " ";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorGreek::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1434 of file translator_gr.h.
    {
      return " ";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorGreek::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 539 of file translator_gr.h.
    { return " "; }
trSeeAlso() [2/2]
virtual QCString TranslatorGreek::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 539 of file translator_gr.h.
    { return " "; }
trSequenceDocumentation() [1/2]
virtual QCString TranslatorGreek::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2147 of file translator_gr.h.
    {
        return " ";
    }
trSequenceDocumentation() [2/2]
virtual QCString TranslatorGreek::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2147 of file translator_gr.h.
    {
        return " ";
    }
trSequences() [1/2]
virtual QCString TranslatorGreek::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2143 of file translator_gr.h.
    {
        return "";
    }
trSequences() [2/2]
virtual QCString TranslatorGreek::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2143 of file translator_gr.h.
    {
        return "";
    }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorGreek::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2000 of file translator_gr.h.
    {
      // single is true implies a single file
      QCString result=" "
                                " ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorGreek::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2000 of file translator_gr.h.
    {
      // single is true implies a single file
      QCString result=" "
                                " ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorGreek::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1986 of file translator_gr.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorGreek::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1986 of file translator_gr.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorGreek::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1971 of file translator_gr.h.
    { return " "; }
trServices() [2/2]
virtual QCString TranslatorGreek::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1971 of file translator_gr.h.
    { return " "; }
trSignals() [1/2]
virtual QCString TranslatorGreek::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 633 of file translator_gr.h.
    { return ""; }
trSignals() [2/2]
virtual QCString TranslatorGreek::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 633 of file translator_gr.h.
    { return ""; }
trSince() [1/2]
virtual QCString TranslatorGreek::trSince () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_gr.h.
    {
      return "";
    }
trSince() [2/2]
virtual QCString TranslatorGreek::trSince () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_gr.h.
    {
      return "";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorGreek::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2009 of file translator_gr.h.
    {
      // single is true implies a single file
      QCString result=" "
                                " ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorGreek::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2009 of file translator_gr.h.
    {
      // single is true implies a single file
      QCString result=" "
                                " ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorGreek::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1993 of file translator_gr.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorGreek::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1993 of file translator_gr.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trSliceInterfaces() [1/2]
virtual QCString TranslatorGreek::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2159 of file translator_gr.h.
    {
        return "";
    }
trSliceInterfaces() [2/2]
virtual QCString TranslatorGreek::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2159 of file translator_gr.h.
    {
        return "";
    }
trSourceFile() [1/2]
virtual QCString TranslatorGreek::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1476 of file translator_gr.h.
    {
      return " " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorGreek::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1476 of file translator_gr.h.
    {
      return " " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorGreek::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1405 of file translator_gr.h.
    {
      return " ";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorGreek::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1405 of file translator_gr.h.
    {
      return " ";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorGreek::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1391 of file translator_gr.h.
    {
      return " ";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorGreek::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1391 of file translator_gr.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorGreek::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 932 of file translator_gr.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorGreek::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 932 of file translator_gr.h.
    {
      return " ";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorGreek::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 647 of file translator_gr.h.
    { return " "; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorGreek::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 647 of file translator_gr.h.
    { return " "; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorGreek::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 920 of file translator_gr.h.
    {
      return " ";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorGreek::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 920 of file translator_gr.h.
    {
      return " ";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorGreek::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 641 of file translator_gr.h.
    { return " "; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorGreek::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 641 of file translator_gr.h.
    { return " "; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorGreek::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_gr.h.
    {
      return " ";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorGreek::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_gr.h.
    {
      return " ";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorGreek::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 635 of file translator_gr.h.
    { return " "; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorGreek::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 635 of file translator_gr.h.
    { return " "; }
trStructDocumentation() [1/2]
virtual QCString TranslatorGreek::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2203 of file translator_gr.h.
    {
        return " ";
    }
trStructDocumentation() [2/2]
virtual QCString TranslatorGreek::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2203 of file translator_gr.h.
    {
        return " ";
    }
trStructIndex() [1/2]
virtual QCString TranslatorGreek::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2191 of file translator_gr.h.
    {
        return " ";
    }
trStructIndex() [2/2]
virtual QCString TranslatorGreek::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2191 of file translator_gr.h.
    {
        return " ";
    }
trStructList() [1/2]
virtual QCString TranslatorGreek::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2195 of file translator_gr.h.
    {
        return " ";
    }
trStructList() [2/2]
virtual QCString TranslatorGreek::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2195 of file translator_gr.h.
    {
        return " ";
    }
trStructListDescription() [1/2]
virtual QCString TranslatorGreek::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2199 of file translator_gr.h.
    {
        return " :";
    }
trStructListDescription() [2/2]
virtual QCString TranslatorGreek::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2199 of file translator_gr.h.
    {
        return " :";
    }
trStructs() [1/2]
virtual QCString TranslatorGreek::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2187 of file translator_gr.h.
    {
        return "";
    }
trStructs() [2/2]
virtual QCString TranslatorGreek::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2187 of file translator_gr.h.
    {
        return "";
    }
trSubprogram() [1/2]
virtual QCString TranslatorGreek::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1737 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorGreek::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1737 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorGreek::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1611 of file translator_gr.h.
    { return " /"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorGreek::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1611 of file translator_gr.h.
    { return " /"; }
trSubprograms() [1/2]
virtual QCString TranslatorGreek::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1605 of file translator_gr.h.
    { return "/"; }
trSubprograms() [2/2]
virtual QCString TranslatorGreek::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1605 of file translator_gr.h.
    { return "/"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorGreek::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1878 of file translator_gr.h.
    { return " "; }
trTemplateParameters() [2/2]
virtual QCString TranslatorGreek::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1878 of file translator_gr.h.
    { return " "; }
trTest() [1/2]
virtual QCString TranslatorGreek::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1065 of file translator_gr.h.
    {
      return "";
    }
trTest() [2/2]
virtual QCString TranslatorGreek::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1065 of file translator_gr.h.
    {
      return "";
    }
trTestList() [1/2]
virtual QCString TranslatorGreek::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1070 of file translator_gr.h.
    {
      return " ";
    }
trTestList() [2/2]
virtual QCString TranslatorGreek::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1070 of file translator_gr.h.
    {
      return " ";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorGreek::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 139 of file translator_gr.h.
    { return " "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorGreek::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 139 of file translator_gr.h.
    { return " "; }
trTodo() [1/2]
virtual QCString TranslatorGreek::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 942 of file translator_gr.h.
    {
      return " ";
    }
trTodo() [2/2]
virtual QCString TranslatorGreek::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 942 of file translator_gr.h.
    {
      return " ";
    }
trTodoList() [1/2]
virtual QCString TranslatorGreek::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 947 of file translator_gr.h.
    {
      return " ";
    }
trTodoList() [2/2]
virtual QCString TranslatorGreek::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 947 of file translator_gr.h.
    {
      return " ";
    }
trType() [1/2]
virtual QCString TranslatorGreek::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1726 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      result+= first_capital ? " " : " ";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorGreek::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1726 of file translator_gr.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      result+= first_capital ? " " : " ";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorGreek::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1745 of file translator_gr.h.
    {
      return " ";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorGreek::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1745 of file translator_gr.h.
    {
      return " ";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorGreek::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 469 of file translator_gr.h.
    { return " "; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorGreek::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 469 of file translator_gr.h.
    { return " "; }
trTypedefs() [1/2]
virtual QCString TranslatorGreek::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 433 of file translator_gr.h.
    { return " "; }
trTypedefs() [2/2]
virtual QCString TranslatorGreek::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 433 of file translator_gr.h.
    { return " "; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorGreek::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1599 of file translator_gr.h.
    { return " "; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorGreek::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1599 of file translator_gr.h.
    { return " "; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorGreek::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 487 of file translator_gr.h.
    { return " "; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorGreek::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 487 of file translator_gr.h.
    { return " "; }
trVariables() [1/2]
virtual QCString TranslatorGreek::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 451 of file translator_gr.h.
    { return ""; }
trVariables() [2/2]
virtual QCString TranslatorGreek::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 451 of file translator_gr.h.
    { return ""; }
trVersion() [1/2]
virtual QCString TranslatorGreek::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 527 of file translator_gr.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorGreek::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 527 of file translator_gr.h.
    { return ""; }
trVhdlType() [1/2]
virtual QCString TranslatorGreek::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2046 of file translator_gr.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "";
          else return "";
        case VhdlDocGen::PACKAGE:
          if (single) return "";
          else return "";
        case VhdlDocGen::SIGNAL:
          if (single) return "";
          else return "";
        case VhdlDocGen::COMPONENT:
          if (single) return "";
          else return "";
        case VhdlDocGen::CONSTANT:
          if (single) return "";
          else return "";
        case VhdlDocGen::ENTITY:
          if (single) return "";
          else return "";
        case VhdlDocGen::TYPE:
          if (single) return "";
          else return "";
        case VhdlDocGen::SUBTYPE:
          if (single) return "";
          else return "";
        case VhdlDocGen::FUNCTION:
          if (single) return "";
          else return "";
        case VhdlDocGen::RECORD:
          if (single) return "";
          else return "";
        case VhdlDocGen::PROCEDURE:
          if (single) return "";
          else return "";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "";
          else return "";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "";
          else return "";
        case VhdlDocGen::PROCESS:
          if (single) return "";
          else return "";
        case VhdlDocGen::PORT:
          if (single) return "";
          else return "";
        case VhdlDocGen::USE:
          if (single) return " ";
          else return " ";
        case VhdlDocGen::GENERIC:
          if (single) return "";
          else return "";
        case VhdlDocGen::PACKAGE_BODY:
          return " ";
        case VhdlDocGen::UNITS:
          return "";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return " ";
          else return " ";
        case VhdlDocGen::VFILE:
          if (single) return "";
          else return "";
        case VhdlDocGen::GROUP:
          if (single) return "";
          else return "";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "";
          else return "";
        case VhdlDocGen::ALIAS:
          if (single) return "";
          else return "";
        case VhdlDocGen::CONFIG:
          if (single) return "";
          else return "";
        case VhdlDocGen::MISCELLANEOUS:
          return "";
        case VhdlDocGen::UCF_CONST:
          return "";
        default:
          return "";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trVhdlType() [2/2]
virtual QCString TranslatorGreek::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2046 of file translator_gr.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "";
          else return "";
        case VhdlDocGen::PACKAGE:
          if (single) return "";
          else return "";
        case VhdlDocGen::SIGNAL:
          if (single) return "";
          else return "";
        case VhdlDocGen::COMPONENT:
          if (single) return "";
          else return "";
        case VhdlDocGen::CONSTANT:
          if (single) return "";
          else return "";
        case VhdlDocGen::ENTITY:
          if (single) return "";
          else return "";
        case VhdlDocGen::TYPE:
          if (single) return "";
          else return "";
        case VhdlDocGen::SUBTYPE:
          if (single) return "";
          else return "";
        case VhdlDocGen::FUNCTION:
          if (single) return "";
          else return "";
        case VhdlDocGen::RECORD:
          if (single) return "";
          else return "";
        case VhdlDocGen::PROCEDURE:
          if (single) return "";
          else return "";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "";
          else return "";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "";
          else return "";
        case VhdlDocGen::PROCESS:
          if (single) return "";
          else return "";
        case VhdlDocGen::PORT:
          if (single) return "";
          else return "";
        case VhdlDocGen::USE:
          if (single) return " ";
          else return " ";
        case VhdlDocGen::GENERIC:
          if (single) return "";
          else return "";
        case VhdlDocGen::PACKAGE_BODY:
          return " ";
        case VhdlDocGen::UNITS:
          return "";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return " ";
          else return " ";
        case VhdlDocGen::VFILE:
          if (single) return "";
          else return "";
        case VhdlDocGen::GROUP:
          if (single) return "";
          else return "";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "";
          else return "";
        case VhdlDocGen::ALIAS:
          if (single) return "";
          else return "";
        case VhdlDocGen::CONFIG:
          if (single) return "";
          else return "";
        case VhdlDocGen::MISCELLANEOUS:
          return "";
        case VhdlDocGen::UCF_CONST:
          return "";
        default:
          return "";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
virtual QCString TranslatorGreek::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 523 of file translator_gr.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorGreek::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 523 of file translator_gr.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorGreek::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 653 of file translator_gr.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorGreek::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 653 of file translator_gr.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_gr.h
doxygen/src/translator_gr.h