SymbolGroupListContext::Private Class Reference
Public Member Functions
Private (const SearchIndexList &sil)
Private (const SearchIndexList &sil)
Additional Inherited Members
Detailed Description
Definition at line 8605 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
SymbolGroupListContext::Private::Private (const SearchIndexList & sil) [inline]
Definition at line 8608 of file context.cpp.
    {
      QCString lastName;
      auto it = sil.begin();
      auto it_begin = it;
      while (it!=sil.end())
      {
        QCString name = searchName(*it);
        if (name!=lastName)
        {
          if (it!=it_begin)
          {
            append(SymbolGroupContext::alloc(it_begin,it));
          }
          it_begin = it;
          lastName = name;
        }
        ++it;
      }
      if (it_begin!=sil.end())
      {
        append(SymbolGroupContext::alloc(it_begin,sil.end()));
      }
    }
References SymbolGroupContext::alloc(), GenericNodeListContext::append(), setup::name, and searchName().
Private() [2/2]
SymbolGroupListContext::Private::Private (const SearchIndexList & sil) [inline]
Definition at line 8608 of file context.cpp.
    {
      QCString lastName;
      auto it = sil.begin();
      auto it_begin = it;
      while (it!=sil.end())
      {
        QCString name = searchName(*it);
        if (name!=lastName)
        {
          if (it!=it_begin)
          {
            append(SymbolGroupContext::alloc(it_begin,it));
          }
          it_begin = it;
          lastName = name;
        }
        ++it;
      }
      if (it_begin!=sil.end())
      {
        append(SymbolGroupContext::alloc(it_begin,sil.end()));
      }
    }
References SymbolGroupContext::alloc(), setup::name, and searchName().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp