FileContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
FileContext (const FileDef *)
virtual ~FileContext ()
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
FileContext (const FileDef *)
virtual ~FileContext ()
Static Public Member Functions
static TemplateStructIntfPtr alloc (const FileDef *fd)
static TemplateStructIntfPtr alloc (const FileDef *fd)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 257 of file context.h.
Constructor & Destructor Documentation
FileContext() [1/2]
FileContext::FileContext (const FileDef * fd)
Definition at line 3094 of file context.cpp.
                                          : p(std::make_unique<Private>(fd))
{
}
 FileContext() [1/2]
FileContext::~FileContext () [virtual]
Definition at line 3098 of file context.cpp.
{
}
FileContext() [2/2]
FileContext::FileContext (const FileDef *)
 FileContext() [2/2]
virtual FileContext::~FileContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateStructIntfPtr FileContext::alloc (const FileDef * fd) [inline], [static]
Definition at line 260 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<FileContext>(fd)); }
Referenced by UsedFilesContext::Private::addFile(), FileListContext::Private::addFiles(), NestingNodeContext::Private::createFile(), IncludeInfoContext::Private::createFileContext(), MemberContext::Private::createFileDef(), DirContext::Private::createFiles(), and ModuleContext::Private::createFiles().
alloc() [2/2]
static TemplateStructIntfPtr FileContext::alloc (const FileDef * fd) [inline], [static]
Definition at line 260 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<FileContext>(fd)); }
fields() [1/2]
StringVector FileContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 3107 of file context.cpp.
{
  return p->fields();
}
References p.
fields() [2/2]
virtual StringVector FileContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant FileContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 3102 of file context.cpp.
{
  return p->get(n);
}
References n, and p.
get() [2/2]
virtual TemplateVariant FileContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Member Data Documentation
p
std::unique_ptr< Private > FileContext::p [private]
Definition at line 272 of file context.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp