FormulaManager Class Reference
#include <formula.h>
Classes
struct Private
Public Member Functions
 repository functions
void initFromRepository (const QCString &dir)
void checkRepositories ()
void initFromRepository (const QCString &dir)
void checkRepositories ()
 formula functions
void clear ()
int addFormula (const std::string &formulaText, int width=-1, int height=-1)
const Formula * findFormula (int formulaId) const
bool hasFormulas () const
void clear ()
int addFormula (const std::string &formulaText, int width=-1, int height=-1)
const Formula * findFormula (int formulaId) const
bool hasFormulas () const
Static Public Member Functions
static FormulaManager & instance ()
static FormulaManager & instance ()
Private Types
enum class Mode { Dark
, Light
, Dark
, Light
 }
enum class Mode { Dark
, Light
, Dark
, Light
 }
Private Member Functions
void createFormulasTexFile (Dir &d, Format format, HighDPI hd, Mode mode)
void createLatexFile (const QCString &fileName, Format format, Mode mode, IntVector &formulasToGenerate)
double updateFormulaSize (int pageNum, int x1, int y1, int x2, int y2)
FormulaManager ()
void createFormulasTexFile (Dir &d, Format format, HighDPI hd, Mode mode)
void createLatexFile (const QCString &fileName, Format format, Mode mode, IntVector &formulasToGenerate)
double updateFormulaSize (int pageNum, int x1, int y1, int x2, int y2)
FormulaManager ()
Private Attributes
std::unique_ptr< Private > p
generator functions
enum class Format { Bitmap
, Vector
, Bitmap
, Vector
 }
enum class HighDPI { On
, Off
, On
, Off
 }
enum class Format { Bitmap
, Vector
, Bitmap
, Vector
 }
enum class HighDPI { On
, Off
, On
, Off
 }
void generateImages (const QCString &outputDir, Format format, HighDPI hd=HighDPI::Off)
void generateImages (const QCString &outputDir, Format format, HighDPI hd=HighDPI::Off)
Detailed Description
Manager class to handle formulas
Definition at line 58 of file formula.h.
Member Enumeration Documentation
Format [1/2]
enum class FormulaManager::Format [strong]
Enumerator
Bitmap
Vector
Bitmap
Vector
Definition at line 79 of file formula.h.
{ Bitmap, Vector };
Format [2/2]
enum class FormulaManager::Format [strong]
Enumerator
Bitmap
Vector
Bitmap
Vector
Definition at line 79 of file formula.h.
{ Bitmap, Vector };
HighDPI [1/2]
enum class FormulaManager::HighDPI [strong]
Enumerator
On
Off
On
Off
Definition at line 80 of file formula.h.
{ On, Off };
HighDPI [2/2]
enum class FormulaManager::HighDPI [strong]
Enumerator
On
Off
On
Off
Definition at line 80 of file formula.h.
{ On, Off };
Mode [1/2]
enum class FormulaManager::Mode [strong], [private]
Enumerator
Dark
Light
Dark
Light
Definition at line 85 of file formula.h.
{ Dark, Light };
Mode [2/2]
enum class FormulaManager::Mode [strong], [private]
Enumerator
Dark
Light
Dark
Light
Definition at line 85 of file formula.h.
{ Dark, Light };
Constructor & Destructor Documentation
FormulaManager() [1/2]
FormulaManager::FormulaManager () [private]
Definition at line 51 of file formula.cpp.
                               : p(std::make_unique<Private>())
{
}
FormulaManager() [2/2]
FormulaManager::FormulaManager () [private]
Member Function Documentation
addFormula() [1/2]
int FormulaManager::addFormula (const std::string & formulaText, int width = -1, int height = -1)
Definition at line 653 of file formula.cpp.
{
  Formula *formula = p->formulas.find(formulaText);
  if (formula) // same formula already stored
  {
    return formula->id();
  }
  // add new formula
  int id = static_cast<int>(p->formulas.size());
  formula = p->formulas.add(formulaText.c_str(),id,width,height);
  p->formulaIdMap.insert(std::make_pair(id,formula));
  return id;
}
References id, Formula::id(), and p.
Referenced by addFormula().
addFormula() [2/2]
int FormulaManager::addFormula (const std::string & formulaText, int width = -1, int height = -1)
checkRepositories() [1/2]
void FormulaManager::checkRepositories ()
Definition at line 175 of file formula.cpp.
{
  //printf("checkRepositories valid=%d\n",p->repositoriesValid);
  if (!p->repositoriesValid)
  {
    clear(); // clear cached formulas, so the corresponding images and repository files
             // are regenerated
    p->repositoriesValid = true;
  }
}
References clear(), and p.
Referenced by parseInput().
checkRepositories() [2/2]
void FormulaManager::checkRepositories ()
clear() [1/2]
void FormulaManager::clear ()
Definition at line 647 of file formula.cpp.
{
  p->formulas.clear();
  p->formulaIdMap.clear();
}
References p.
Referenced by checkRepositories(), cleanUpDoxygen(), and clearAll().
clear() [2/2]
void FormulaManager::clear ()
createFormulasTexFile() [1/2]
void FormulaManager::createFormulasTexFile (Dir & d, Format format, HighDPI hd, Mode mode) [private]
Definition at line 494 of file formula.cpp.
{
  IntVector formulasToGenerate;
  QCString formulaFileName = mode==Mode::Light ? "_formulas" : "_formulas_dark";
  createLatexFile(formulaFileName,format,mode,formulasToGenerate);
  if (!formulasToGenerate.empty()) // there are new formulas
  {
    if (!createDVIFile(formulaFileName)) return;
    //printf("Running dvips...\n");
    int pageIndex=1;
    for (int pageNum : formulasToGenerate)
    {
      QCString outputFile;
      outputFile.sprintf("form_%d%s.%s",pageNum, mode==Mode::Light?"":"_dark", format==Format::Vector?"svg":"png");
      msg("Generating image %s for formula\n",qPrint(outputFile));
      QCString formBase;
      formBase.sprintf("_form%d%s",pageNum,mode==Mode::Light?"":"_dark");
      if (!createPostscriptFile(formulaFileName,formBase,pageIndex)) break;
      int x1=0,y1=0,x2=0,y2=0;
      double x1hi=0.0,y1hi=0.0,x2hi=0.0,y2hi=0.0;
      if (mode==Mode::Light)
      {
        if (!createEPSbboxFile(formBase)) break;
        // extract the bounding box info from the generated .epsi file
        if (!extractBoundingBox(formBase,&x1,&y1,&x2,&y2,&x1hi,&y1hi,&x2hi,&y2hi)) break;
      }
      else // for dark images the bounding box is wrong (includes the black) so
           // use the bounding box of the light image instead.
      {
        QCString formBaseLight;
        formBaseLight.sprintf("_form%d",pageNum);
        if (!extractBoundingBox(formBaseLight,&x1,&y1,&x2,&y2,&x1hi,&y1hi,&x2hi,&y2hi)) break;
      }
      // convert the corrected EPS to a bitmap
      double scaleFactor = updateFormulaSize(pageNum,x1,y1,x2,y2);
      if (format==Format::Vector)
      {
        if (!createCroppedPDF(formBase,x1,y1,x2,y2)) break;
        // if we have pdf2svg available use it to create a SVG image
        if (Portable::checkForExecutable("pdf2svg"))
        {
          createSVGFromPDF(formBase,outputFile);
        }
        else if (Portable::checkForExecutable("inkscape")) // alternative is to use inkscape
        {
          createSVGFromPDFviaInkscape(thisDir,formBase,outputFile);
        }
        else
        {
          err("Neither 'pdf2svg' nor 'inkscape' present for conversion of formula to 'svg'\n");
          return;
        }
        p->tempFiles.push_back(formBase.str()+"_tmp.pdf");
      }
      else // format==Format::Bitmap
      {
        if (!createCroppedEPS(formBase)) break;
        if (!updateEPSBoundingBox(formBase,x1,y1,x2,y2,x1hi,y1hi,x2hi,y2hi)) break;
        if (hd==HighDPI::On) // for high DPI display it looks much better if the
                             // image resolution is higher than the display resolution
        {
          scaleFactor*=2;
        }
        if (!createPNG(formBase,outputFile,scaleFactor)) break;
        p->tempFiles.push_back(formBase.str()+"_tmp.eps");
        p->tempFiles.push_back(formBase.str()+"_tmp_corr.eps");
      }
      // remove intermediate image files
      p->tempFiles.push_back(formBase.str()+"_tmp.ps");
      if (mode==Mode::Light)
      {
        p->tempFiles.push_back(formBase.str()+"_tmp.epsi");
      }
      pageIndex++;
    }
    // remove intermediate files produced by latex
    p->tempFiles.push_back(formulaFileName.str()+".dvi");
    p->tempFiles.push_back(formulaFileName.str()+".log");
    p->tempFiles.push_back(formulaFileName.str()+".aux");
  }
  // remove the latex file itself
  p->tempFiles.push_back(formulaFileName.str()+".tex");
  // write/update the formula repository so we know what text the
  // generated images represent (we use this next time to avoid regeneration
  // of the images, and to avoid forcing the user to delete all images in order
  // to let a browser refresh the images).
  std::ofstream f;
  f.open("formula.repository",std::ofstream::out | std::ofstream::binary);
  if (f.is_open())
  {
    TextStream t(&f);
    for (const auto &formula : p->formulas)
    {
      t << "\\_form#" << formula->id();
      if (formula->width()!=-1 && formula->height()!=-1)
      {
        t << "=" << formula->width() << "x" << formula->height();
      }
      t << ":" << formula->text() << "\n";
    }
  }
}
References Portable::checkForExecutable(), createCroppedEPS(), createCroppedPDF(), createDVIFile(), createEPSbboxFile(), createLatexFile(), createPNG(), createPostscriptFile(), createSVGFromPDF(), createSVGFromPDFviaInkscape(), err(), extractBoundingBox(), f, Light, mode, msg(), On, out, p, qPrint(), QCString::sprintf(), QCString::str(), updateEPSBoundingBox(), updateFormulaSize(), Vector, x1, x2, y1, and y2.
Referenced by generateImages().
createFormulasTexFile() [2/2]
void FormulaManager::createFormulasTexFile (Dir & d, Format format, HighDPI hd, Mode mode) [private]
createLatexFile() [1/2]
void FormulaManager::createLatexFile (const QCString & fileName, Format format, Mode mode, IntVector & formulasToGenerate) [private]
Definition at line 186 of file formula.cpp.
{
  QCString macroFile = Config_getString(FORMULA_MACROFILE);
  QCString stripMacroFile;
  if (!macroFile.isEmpty())
  {
    FileInfo fi(macroFile.str());
    macroFile=fi.absFilePath();
    stripMacroFile = fi.fileName();
  }
  // generate a latex file containing one formula per page.
  QCString texName=fileName+".tex";
  std::ofstream f(texName.str(),std::ofstream::out | std::ofstream::binary);
  if (f.is_open())
  {
    TextStream t(&f);
    t << "\\documentclass{article}\n";
    t << "\\usepackage{ifthen}\n";
    t << "\\usepackage{epsfig}\n"; // for those who want to include images
    t << "\\usepackage[utf8]{inputenc}\n"; // looks like some older distributions with newunicode package 1.1 need this option.
    t << "\\usepackage{xcolor}\n";
    if (mode==Mode::Dark) // invert page and text colors
    {
      t << "\\color{white}\n";
      t << "\\pagecolor{black}\n";
    }
    writeExtraLatexPackages(t);
    writeLatexSpecialFormulaChars(t);
    if (!macroFile.isEmpty())
    {
      copyFile(macroFile,stripMacroFile);
      t << "\\input{" << stripMacroFile << "}\n";
    }
    t << "\\pagestyle{empty}\n";
    t << "\\begin{document}\n";
    for (const auto &formula : p->formulas)
    {
      int id = formula->id();
      // only formulas for which no image is cached are generated
      //printf("check formula %d: cached=%d cachedDark=%d\n",formula->id(),formula->isCached(),formula->isCachedDark());
      if ((mode==Mode::Light && !formula->isCached()) ||
          (mode==Mode::Dark && !formula->isCachedDark())
         )
      {
        // we force a pagebreak after each formula
        t << formula->text() << "\n\\pagebreak\n\n";
        formulasToGenerate.push_back(id);
      }
      QCString resultName;
      resultName.sprintf("form_%d%s.%s",id, mode==Mode::Light?"":"_dark", format==Format::Vector?"svg":"png");
      Doxygen::indexList->addImageFile(resultName);
    }
    t << "\\end{document}\n";
    t.flush();
    f.close();
  }
}
References FileInfo::absFilePath(), IndexList::addImageFile(), Config_getString, copyFile(), Dark, f, FileInfo::fileName(), TextStream::flush(), Doxygen::indexList, QCString::isEmpty(), Light, mode, out, p, QCString::sprintf(), QCString::str(), Vector, writeExtraLatexPackages(), and writeLatexSpecialFormulaChars().
Referenced by createFormulasTexFile().
createLatexFile() [2/2]
void FormulaManager::createLatexFile (const QCString & fileName, Format format, Mode mode, IntVector & formulasToGenerate) [private]
findFormula() [1/2]
const Formula * FormulaManager::findFormula (int formulaId) const
Definition at line 667 of file formula.cpp.
{
  auto it = p->formulaIdMap.find(formulaId);
  return it != p->formulaIdMap.end() ? it->second : nullptr;
}
References p.
Referenced by DocFormula::DocFormula(), and HtmlDocVisitor::operator()().
findFormula() [2/2]
const Formula * FormulaManager::findFormula (int formulaId) const
generateImages() [1/2]
void FormulaManager::generateImages (const QCString & outputDir, Format format, HighDPI hd = HighDPI::Off)
Definition at line 612 of file formula.cpp.
{
  Dir d(path.str());
  // store the original directory
  if (!d.exists())
  {
    term("Output directory '%s' does not exist!\n",qPrint(path));
  }
  std::string oldDir = Dir::currentDirPath();
  // go to the html output directory (i.e. path)
  Dir::setCurrent(d.absPath());
  Dir thisDir;
  createFormulasTexFile(thisDir,format,hd,Mode::Light);
  if (Config_getEnum(HTML_COLORSTYLE)!=HTML_COLORSTYLE_t::LIGHT) // all modes other than light need a dark version
  {
    // note that the dark version reuses the bounding box of the light version so it needs to be
    // created after the light version.
    createFormulasTexFile(thisDir,format,hd,Mode::Dark);
  }
  // clean up temporary files
  if (RM_TMP_FILES)
  {
    for (const auto &file : p->tempFiles)
    {
      thisDir.remove(file);
    }
  }
  // reset the directory to the original location.
  Dir::setCurrent(oldDir);
}
References Dir::absPath(), Config_getEnum, createFormulasTexFile(), Dir::currentDirPath(), Dark, Dir::exists(), caseconvert::file, Light, p, qPrint(), Dir::remove(), RM_TMP_FILES, Dir::setCurrent(), QCString::str(), string, and term().
Referenced by generateOutput().
generateImages() [2/2]
void FormulaManager::generateImages (const QCString & outputDir, Format format, HighDPI hd = HighDPI::Off)
hasFormulas() [1/2]
bool FormulaManager::hasFormulas () const
Definition at line 682 of file formula.cpp.
{
  return !p->formulas.empty();
}
References p.
Referenced by generateOutput().
hasFormulas() [2/2]
bool FormulaManager::hasFormulas () const
initFromRepository() [1/2]
void FormulaManager::initFromRepository (const QCString & dir)
Definition at line 61 of file formula.cpp.
{
  std::ifstream f(dir.str()+"/formula.repository",std::ifstream::in);
  if (f.is_open())
  {
    uint formulaCount=0;
    msg("Reading formula repository...\n");
    std::string readLine;
    std::string line;
    std::string prefix("\\_form#");
    int lineNr;
    int nextLineNr=1;
    bool hasNextLine = !getline(f,readLine).fail();
    while (hasNextLine)
    {
      line = readLine;
      lineNr = nextLineNr;
      // look ahead a bit because a formula can be spread over several lines
      while ((hasNextLine = !getline(f,readLine).fail()))
      {
        nextLineNr+=1;
        if (!readLine.compare(0, prefix.size(), prefix)) break;
        line += "\n" + readLine;
      }
      // new format: \_form#<digits>=<digits>x<digits>:formula
      static const reg::Ex re_new(R"(\\_form#(\d+)=(\d+)x(\d+):)");
      // old format: \_form#<digits>:formula
      static const reg::Ex re_old(R"(\\_form#(\d+):)");
      reg::Match match;
      int id = -1;
      int width = -1;
      int height = -1;
      std::string text;
      if (reg::search(line,match,re_new)) // try new format first
      {
        id = std::stoi(match[1].str());
        width = std::stoi(match[2].str());
        height = std::stoi(match[3].str());
        text = line.substr(match.position()+match.length());
        //printf("new format found id=%d width=%d height=%d text=%s\n",id,width,height,text.c_str());
      }
      else if (reg::search(line,match,re_old)) // check for old format
      {
        //id = std::stoi(match[1].str());
        //text = line.substr(match.position()+match.length());
        //printf("old format found id=%d text=%s\n",id,text.c_str());
        msg("old formula.repository format detected; forcing upgrade.\n");
        p->repositoriesValid = false;
        break;
      }
      else // unexpected content
      {
        warn_uncond("%s/formula.repository contains invalid content at line %d: found: '%s'\n",qPrint(dir),lineNr,line.c_str());
        p->repositoriesValid = false;
        break;
      }
      auto it = p->formulaIdMap.find(id);
      Formula *formula=0;
      if (it!=p->formulaIdMap.end()) // formula already found in a repository for another output format
      {
        formula = it->second;
        if (formula->text().str()!=text) // inconsistency between repositories detected
        {
          msg("differences detected between formula.repository files; forcing upgrade.\n");
          p->repositoriesValid = false;
          break;
        }
        formulaCount++;
      }
      else // create new formula from cache
      {
        //printf("formula not found adding it under id=%d\n",id);
        formula = p->formulas.add(text.c_str(),id,width,height);
        p->formulaIdMap.insert(std::make_pair(id,formula));
      }
      if (formula) // if an entry in the repository exists also check if there is a generated image
      {
        QCString formImgName;
        formImgName.sprintf("form_%d",formula->id());
        FileInfo fiPng((dir+"/"+formImgName+".png").str());
        FileInfo fiSvg((dir+"/"+formImgName+".svg").str());
        // mark formula as cached, so we do not need to regenerate the images
        bool isCached = fiPng.exists() || fiSvg.exists();
        formula->setCached(isCached);
        //printf("formula %d: cached=%d\n",formula->id(),isCached);
        FileInfo fiPngDark((dir+"/"+formImgName+"_dark.png").str());
        FileInfo fiSvgDark((dir+"/"+formImgName+"_dark.svg").str());
        bool isCachedDark = fiPngDark.exists() || fiSvgDark.exists();
        formula->setCachedDark(isCachedDark);
        //printf("formula %d: cachedDark=%d\n",formula->id(),isCachedDark);
      }
    }
    // For the first repository all formulas should be new (e.g. formulaCount==0).
    // For the other repositories the same number of formulas should be found
    // (and number of formulas should be the same for all repositories, content is already check above)
    if (formulaCount>0 && formulaCount!=p->formulas.size()) // inconsistency between repositories
    {
      msg("differences detected between formula.repository files; forcing upgrade.\n");
      p->repositoriesValid = false;
    }
  }
  else // no repository found for an output format
  {
    p->repositoriesValid = false;
  }
}
References FileInfo::exists(), f, Formula::id(), reg::match(), msg(), p, qPrint(), reg::search(), Formula::setCached(), Formula::setCachedDark(), QCString::sprintf(), QCString::str(), string, Formula::text(), and warn_uncond().
Referenced by parseInput().
initFromRepository() [2/2]
void FormulaManager::initFromRepository (const QCString & dir)
instance() [1/2]
FormulaManager & FormulaManager::instance () [static]
Definition at line 55 of file formula.cpp.
{
  static FormulaManager fm;
  return fm;
}
Referenced by addFormula(), cleanUpDoxygen(), clearAll(), DocFormula::DocFormula(), generateOutput(), HtmlDocVisitor::operator()(), and parseInput().
instance() [2/2]
static FormulaManager & FormulaManager::instance () [static]
updateFormulaSize() [1/2]
double FormulaManager::updateFormulaSize (int pageNum, int x1, int y1, int x2, int y2) [private]
Definition at line 344 of file formula.cpp.
{
  double scaleFactor = 1.25;
  int zoomFactor = Config_getInt(FORMULA_FONTSIZE);
  if (zoomFactor<8 || zoomFactor>50) zoomFactor=10;
  scaleFactor *= zoomFactor/10.0;
  auto it = p->formulaIdMap.find(pageNum);
  if (it!=p->formulaIdMap.end())
  {
    Formula *formula = it->second;
    formula->setWidth(static_cast<int>((x2-x1)*scaleFactor+0.5));
    formula->setHeight(static_cast<int>((y2-y1)*scaleFactor+0.5));
  }
  return scaleFactor;
}
References Config_getInt, p, Formula::setHeight(), Formula::setWidth(), x1, x2, y1, and y2.
Referenced by createFormulasTexFile().
updateFormulaSize() [2/2]
double FormulaManager::updateFormulaSize (int pageNum, int x1, int y1, int x2, int y2) [private]
Member Data Documentation
p
std::unique_ptr< Private > FormulaManager::p [private]
Definition at line 91 of file formula.h.
Referenced by addFormula(), checkRepositories(), clear(), createFormulasTexFile(), createLatexFile(), findFormula(), generateImages(), hasFormulas(), initFromRepository(), and updateFormulaSize().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/formula.h
doxygen/src/formula.h
doxygen/build/doxygen/src/formula.cpp
doxygen/src/formula.cpp