FilterNoWrap Class Reference
The implementation of the `default` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `default` filter.
Definition at line 1409 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterNoWrap::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1412 of file template.cpp.
    {
      if (!v.isValid() || !v.isString())
      {
        return v;
      }
      QCString s = v.toString();
      return substitute(s," ","&#160;");
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), s, substitute(), and TemplateVariant::toString().
apply() [2/2]
static TemplateVariant FilterNoWrap::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1412 of file template.cpp.
    {
      if (!v.isValid() || !v.isString())
      {
        return v;
      }
      QCString s = v.toString();
      return substitute(s," ","&#160;");
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), s, substitute(), and TemplateVariant::toString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp