DocParamList Class Reference
#include <docnode.h>
Public Member Functions
DocParamList (DocParser *parser, DocNodeVariant *parent, DocParamSect::Type t, DocParamSect::Direction d)
const DocNodeList & parameters () const
const DocNodeList & paramTypes () const
const DocNodeList & paragraphs () const
DocParamSect::Type type () const
DocParamSect::Direction direction () const
void markFirst (bool b=TRUE)
void markLast (bool b=TRUE)
bool isFirst () const
bool isLast () const
int parse (DocNodeVariant *, const QCString &cmdName)
int parseXml (DocNodeVariant *, const QCString &paramName)
DocParamList (DocParser *parser, DocNodeVariant *parent, DocParamSect::Type t, DocParamSect::Direction d)
const DocNodeList & parameters () const
const DocNodeList & paramTypes () const
const DocNodeList & paragraphs () const
DocParamSect::Type type () const
DocParamSect::Direction direction () const
void markFirst (bool b=TRUE)
void markLast (bool b=TRUE)
bool isFirst () const
bool isLast () const
int parse (DocNodeVariant *, const QCString &cmdName)
int parseXml (DocNodeVariant *, const QCString &paramName)
Private Attributes
DocNodeList m_paragraphs
DocNodeList m_params
DocNodeList m_paramTypes
DocParamSect::Type m_type = DocParamSect::Unknown
DocParamSect::Direction m_dir = DocParamSect::Unspecified
bool m_isFirst = false
bool m_isLast = false
Additional Inherited Members
Detailed Description
Node representing a parameter list.
Definition at line 1077 of file docnode.h.
Constructor & Destructor Documentation
DocParamList() [1/2]
DocParamList::DocParamList (DocParser * parser, DocNodeVariant * parent, DocParamSect::Type t, DocParamSect::Direction d) [inline]
Definition at line 1080 of file docnode.h.
      : DocNode(parser,parent), m_type(t), m_dir(d) {}
DocParamList() [2/2]
DocParamList::DocParamList (DocParser * parser, DocNodeVariant * parent, DocParamSect::Type t, DocParamSect::Direction d) [inline]
Definition at line 1080 of file docnode.h.
      : DocNode(parser,parent), m_type(t), m_dir(d) {}
Member Function Documentation
direction() [1/2]
DocParamSect::Direction DocParamList::direction () const [inline]
Definition at line 1086 of file docnode.h.
{ return m_dir; }
References m_dir.
Referenced by doxmlparser.compound.docParamName::__init__(), doxmlparser.compound.docParamName::buildAttributes(), doxmlparser.compound.docParamName::exportAttributes(), doxmlparser.compound.docParamName::get_direction(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and doxmlparser.compound.docParamName::set_direction().
direction() [2/2]
DocParamSect::Direction DocParamList::direction () const [inline]
Definition at line 1086 of file docnode.h.
{ return m_dir; }
References m_dir.
Referenced by doxmlparser.compound.docParamName::__init__(), doxmlparser.compound.docParamName::buildAttributes(), doxmlparser.compound.docParamName::exportAttributes(), doxmlparser.compound.docParamName::get_direction(), and doxmlparser.compound.docParamName::set_direction().
isFirst() [1/2]
bool DocParamList::isFirst () const [inline]
Definition at line 1089 of file docnode.h.
{ return m_isFirst; }
References m_isFirst.
isFirst() [2/2]
bool DocParamList::isFirst () const [inline]
Definition at line 1089 of file docnode.h.
{ return m_isFirst; }
References m_isFirst.
isLast() [1/2]
bool DocParamList::isLast () const [inline]
Definition at line 1090 of file docnode.h.
{ return m_isLast; }
References m_isLast.
Referenced by ManDocVisitor::operator()().
isLast() [2/2]
bool DocParamList::isLast () const [inline]
Definition at line 1090 of file docnode.h.
{ return m_isLast; }
References m_isLast.
markFirst() [1/2]
void DocParamList::markFirst (bool b = TRUE) [inline]
Definition at line 1087 of file docnode.h.
{ m_isFirst=b; }
References b, and m_isFirst.
Referenced by DocParamSect::parse(), and parseXml().
markFirst() [2/2]
void DocParamList::markFirst (bool b = TRUE) [inline]
Definition at line 1087 of file docnode.h.
{ m_isFirst=b; }
References b, and m_isFirst.
markLast() [1/2]
void DocParamList::markLast (bool b = TRUE) [inline]
Definition at line 1088 of file docnode.h.
{ m_isLast=b; }
References b, and m_isLast.
Referenced by DocParamSect::parse(), and parseXml().
markLast() [2/2]
void DocParamList::markLast (bool b = TRUE) [inline]
Definition at line 1088 of file docnode.h.
{ m_isLast=b; }
References b, and m_isLast.
paragraphs() [1/2]
const DocNodeList & DocParamList::paragraphs () const [inline]
Definition at line 1084 of file docnode.h.
{ return m_paragraphs; }
References m_paragraphs.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
paragraphs() [2/2]
const DocNodeList & DocParamList::paragraphs () const [inline]
Definition at line 1084 of file docnode.h.
{ return m_paragraphs; }
References m_paragraphs.
parameters() [1/2]
const DocNodeList & DocParamList::parameters () const [inline]
Definition at line 1082 of file docnode.h.
{ return m_params; }
References m_params.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
parameters() [2/2]
const DocNodeList & DocParamList::parameters () const [inline]
Definition at line 1082 of file docnode.h.
{ return m_params; }
References m_params.
paramTypes() [1/2]
const DocNodeList & DocParamList::paramTypes () const [inline]
Definition at line 1083 of file docnode.h.
{ return m_paramTypes; }
References m_paramTypes.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
paramTypes() [2/2]
const DocNodeList & DocParamList::paramTypes () const [inline]
Definition at line 1083 of file docnode.h.
{ return m_paramTypes; }
References m_paramTypes.
parse() [1/2]
int DocParamList::parse (DocNodeVariant * thisVariant, const QCString & cmdName)
Definition at line 2905 of file docnode.cpp.
{
  int retval=RetVal_OK;
  DBG(("DocParamList::parse() start\n"));
  auto ns = AutoNodeStack(parser(),thisVariant);
  DocNodeVariant *vDocPara = 0;
  DocPara *par=0;
  QCString saveCmdName = cmdName;
  int tok=parser()->tokenizer.lex();
  if (tok!=TK_WHITESPACE)
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected whitespace after \\%s command",
        qPrint(saveCmdName));
    retval=RetVal_EndParBlock;
    goto endparamlist;
  }
  parser()->tokenizer.setStateParam();
  tok=parser()->tokenizer.lex();
  while (tok==TK_WORD) /* there is a parameter name */
  {
    if (m_type==DocParamSect::Param)
    {
      int typeSeparator = parser()->context.token->name.find('#'); // explicit type position
      if (typeSeparator!=-1)
      {
        parser()->handleParameterType(thisVariant,m_paramTypes,parser()->context.token->name.left(typeSeparator));
        parser()->context.token->name = parser()->context.token->name.mid(typeSeparator+1);
        parser()->context.hasParamCommand=TRUE;
        parser()->checkArgumentName();
        if (parent() && std::holds_alternative<DocParamSect>(*parent()))
        {
          std::get<DocParamSect>(*parent()).m_hasTypeSpecifier=true;
        }
      }
      else
      {
        parser()->context.hasParamCommand=TRUE;
        parser()->checkArgumentName();
      }
    }
    else if (m_type==DocParamSect::RetVal)
    {
      parser()->context.hasReturnCommand=TRUE;
      parser()->checkRetvalName();
    }
    //m_params.append(parser()->context.token->name);
    parser()->handleLinkedWord(thisVariant,m_params);
    tok=parser()->tokenizer.lex();
  }
  parser()->tokenizer.setStatePara();
  if (tok==0) /* premature end of comment block */
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected end of comment block while parsing the "
        "argument of command %s",qPrint(saveCmdName));
    retval=RetVal_EndParBlock;
    goto endparamlist;
  }
  if (tok!=TK_WHITESPACE) /* premature end of comment block */
  {
    if (tok!=TK_NEWPARA) /* empty param description */
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected token %s in comment block while parsing the "
          "argument of command %s",DocTokenizer::tokToString(tok),qPrint(saveCmdName));
    }
    retval=RetVal_EndParBlock;
    goto endparamlist;
  }
  vDocPara = m_paragraphs.append<DocPara>(parser(),thisVariant);
  par = m_paragraphs.get_last<DocPara>();
  retval = par->parse(vDocPara);
  par->markFirst();
  par->markLast();
endparamlist:
  DBG(("DocParamList::parse() end retval=%d\n",retval));
  return retval;
}
References DocNodeList::append(), DocParser::checkArgumentName(), DocParser::checkRetvalName(), DocParser::context, DBG, QCString::find(), DocNodeList::get_last(), DocParser::handleLinkedWord(), DocParser::handleParameterType(), DocParserContext::hasParamCommand, DocParserContext::hasReturnCommand, DocTokenizer::lex(), m_paragraphs, m_params, m_paramTypes, m_type, DocPara::markFirst(), DocPara::markLast(), QCString::mid(), TokenInfo::name, DocParamSect::Param, DocNode::parent(), DocPara::parse(), DocNode::parser(), qPrint(), DocParamSect::RetVal, RetVal_EndParBlock, RetVal_OK, DocTokenizer::setStatePara(), DocTokenizer::setStateParam(), TK_NEWPARA, TK_WHITESPACE, TK_WORD, DocParserContext::token, DocParser::tokenizer, DocTokenizer::tokToString(), TRUE, and warn_doc_error().
parse() [2/2]
int DocParamList::parse (DocNodeVariant * , const QCString & cmdName)
parseXml() [1/2]
int DocParamList::parseXml (DocNodeVariant * thisVariant, const QCString & paramName)
Definition at line 2985 of file docnode.cpp.
{
  int retval=RetVal_OK;
  DBG(("DocParamList::parseXml() start\n"));
  auto ns = AutoNodeStack(parser(),thisVariant);
  parser()->context.token->name = paramName;
  if (m_type==DocParamSect::Param)
  {
    parser()->context.hasParamCommand=TRUE;
    parser()->checkArgumentName();
  }
  else if (m_type==DocParamSect::RetVal)
  {
    parser()->context.hasReturnCommand=TRUE;
    parser()->checkRetvalName();
  }
  parser()->handleLinkedWord(thisVariant,m_params);
  do
  {
    auto vDocPara = m_paragraphs.append<DocPara>(parser(),thisVariant);
    DocPara *par = m_paragraphs.get_last<DocPara>();
    retval = par->parse(vDocPara);
    if (par->isEmpty()) // avoid adding an empty paragraph for the whitespace
                        // after </para> and before </param>
    {
      m_paragraphs.pop_back();
      break;
    }
    else // append the paragraph to the list
    {
      if (!m_paragraphs.empty())
      {
        m_paragraphs.get_last<DocPara>()->markLast(FALSE);
      }
      bool markFirst = m_paragraphs.empty();
      par = &std::get<DocPara>(m_paragraphs.back());
      if (markFirst)
      {
        par->markFirst();
      }
      par->markLast();
    }
    if (retval == 0) break;
  } while (retval==RetVal_CloseXml &&
           Mappers::htmlTagMapper->map(parser()->context.token->name)!=XML_PARAM &&
           Mappers::htmlTagMapper->map(parser()->context.token->name)!=XML_TYPEPARAM &&
           Mappers::htmlTagMapper->map(parser()->context.token->name)!=XML_EXCEPTION);
  if (retval==0) /* premature end of comment block */
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unterminated param or exception tag");
  }
  else
  {
    retval=RetVal_OK;
  }
  DBG(("DocParamList::parse() end retval=%d\n",retval));
  return retval;
}
References DocNodeList::append(), GrowVector< T >::back(), DocParser::checkArgumentName(), DocParser::checkRetvalName(), DocParser::context, DBG, GrowVector< T >::empty(), FALSE, DocNodeList::get_last(), DocParser::handleLinkedWord(), DocParserContext::hasParamCommand, DocParserContext::hasReturnCommand, Mappers::htmlTagMapper, m_paragraphs, m_params, m_type, Mapper::map(), markFirst(), markLast(), TokenInfo::name, DocParamSect::Param, DocPara::parse(), DocNode::parser(), GrowVector< T >::pop_back(), DocParamSect::RetVal, RetVal_CloseXml, RetVal_OK, DocParserContext::token, TRUE, warn_doc_error(), XML_EXCEPTION, XML_PARAM, and XML_TYPEPARAM.
parseXml() [2/2]
int DocParamList::parseXml (DocNodeVariant * , const QCString & paramName)
type() [1/2]
DocParamSect::Type DocParamList::type () const [inline]
Definition at line 1085 of file docnode.h.
{ return m_type; }
References m_type.
type() [2/2]
DocParamSect::Type DocParamList::type () const [inline]
Definition at line 1085 of file docnode.h.
{ return m_type; }
References m_type.
Member Data Documentation
m_dir
DocParamSect::Direction DocParamList::m_dir = DocParamSect::Unspecified [private]
Definition at line 1099 of file docnode.h.
Referenced by direction().
m_isFirst
bool DocParamList::m_isFirst = false [private]
Definition at line 1100 of file docnode.h.
Referenced by isFirst(), and markFirst().
m_isLast
bool DocParamList::m_isLast = false [private]
Definition at line 1101 of file docnode.h.
Referenced by isLast(), and markLast().
m_paragraphs
DocNodeList DocParamList::m_paragraphs [private]
Definition at line 1095 of file docnode.h.
Referenced by paragraphs(), parse(), and parseXml().
m_params
DocNodeList DocParamList::m_params [private]
Definition at line 1096 of file docnode.h.
Referenced by parameters(), parse(), and parseXml().
m_paramTypes
DocNodeList DocParamList::m_paramTypes [private]
Definition at line 1097 of file docnode.h.
Referenced by paramTypes(), and parse().
m_type
DocParamSect::Type DocParamList::m_type = DocParamSect::Unknown [private]
Definition at line 1098 of file docnode.h.
Referenced by parse(), parseXml(), and type().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp