DocLinkedWord Class Reference
#include <docnode.h>
Public Member Functions
DocLinkedWord (DocParser *parser, DocNodeVariant *parent, const QCString &word, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &tooltip)
QCString word () const
QCString file () const
QCString relPath () const
QCString ref () const
QCString anchor () const
QCString tooltip () const
DocLinkedWord (DocParser *parser, DocNodeVariant *parent, const QCString &word, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &tooltip)
QCString word () const
QCString file () const
QCString relPath () const
QCString ref () const
QCString anchor () const
QCString tooltip () const
Private Attributes
QCString m_word
QCString m_ref
QCString m_file
QCString m_relPath
QCString m_anchor
QCString m_tooltip
Additional Inherited Members
Detailed Description
Node representing a word that can be linked to something
Definition at line 157 of file docnode.h.
Constructor & Destructor Documentation
DocLinkedWord() [1/2]
DocLinkedWord::DocLinkedWord (DocParser * parser, DocNodeVariant * parent, const QCString & word, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & tooltip)
Definition at line 186 of file docnode.cpp.
                                                                  :
      DocNode(parser,parent), m_word(word), m_ref(ref),
      m_file(file), m_relPath(parser->context.relPath), m_anchor(anchor),
      m_tooltip(tooltip)
{
  //printf("DocLinkedWord: new word %s url=%s tooltip='%s'\n",
  // qPrint(word),qPrint(parser->context.searchUrl),qPrint(tooltip));
  if (Doxygen::searchIndex && !parser->context.searchUrl.isEmpty())
  {
    parser->searchData.addWord(word,false);
  }
}
References SIDataCollection::addWord(), DocParser::context, QCString::isEmpty(), DocNode::parser(), DocParser::searchData, Doxygen::searchIndex, DocParserContext::searchUrl, and word().
DocLinkedWord() [2/2]
DocLinkedWord::DocLinkedWord (DocParser * parser, DocNodeVariant * parent, const QCString & word, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & tooltip)
Member Function Documentation
anchor() [1/2]
QCString DocLinkedWord::anchor () const [inline]
Definition at line 167 of file docnode.h.
{ return m_anchor; }
References m_anchor.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
QCString DocLinkedWord::anchor () const [inline]
Definition at line 167 of file docnode.h.
{ return m_anchor; }
References m_anchor.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
file() [1/2]
QCString DocLinkedWord::file () const [inline]
Definition at line 164 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), and doxmlparser.compound.locationType::set_file().
file() [2/2]
QCString DocLinkedWord::file () const [inline]
Definition at line 164 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), and doxmlparser.compound.locationType::set_file().
ref() [1/2]
QCString DocLinkedWord::ref () const [inline]
Definition at line 166 of file docnode.h.
{ return m_ref; }
References m_ref.
Referenced by doxmlparser.compound.highlightType::__init__(), doxmlparser.compound.docParamName::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.linkedTextType::__init__(), doxmlparser.compound.docParamType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.linkedTextType::add_ref(), doxmlparser.compound.highlightType::add_ref(), doxmlparser.compound.docTitleType::add_ref(), doxmlparser.compound.docSummaryType::add_ref(), doxmlparser.compound.docParaType::add_ref(), doxmlparser.compound.docMarkupType::add_ref(), doxmlparser.compound.docURLLink::add_ref(), doxmlparser.compound.docRefTextType::add_ref(), doxmlparser.compound.docCaptionType::add_ref(), doxmlparser.compound.docHeadingType::add_ref(), doxmlparser.compound.docImageType::add_ref(), doxmlparser.compound.docDotMscType::add_ref(), doxmlparser.compound.docImageFileType::add_ref(), doxmlparser.compound.docPlantumlType::add_ref(), doxmlparser.compound.docTocItemType::add_ref(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docParamName::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.highlightType::exportChildren(), doxmlparser.compound.linkedTextType::get_ref(), doxmlparser.compound.highlightType::get_ref(), doxmlparser.compound.docTitleType::get_ref(), doxmlparser.compound.docSummaryType::get_ref(), doxmlparser.compound.docParaType::get_ref(), doxmlparser.compound.docMarkupType::get_ref(), doxmlparser.compound.docURLLink::get_ref(), doxmlparser.compound.docRefTextType::get_ref(), doxmlparser.compound.docCaptionType::get_ref(), doxmlparser.compound.docHeadingType::get_ref(), doxmlparser.compound.docImageType::get_ref(), doxmlparser.compound.docDotMscType::get_ref(), doxmlparser.compound.docImageFileType::get_ref(), doxmlparser.compound.docPlantumlType::get_ref(), doxmlparser.compound.docTocItemType::get_ref(), doxmlparser.compound.docParamType::get_ref(), doxmlparser.compound.docParamName::get_ref(), doxmlparser.compound.linkedTextType::hasContent_(), doxmlparser.compound.highlightType::hasContent_(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docParamType::hasContent_(), doxmlparser.compound.docParamName::hasContent_(), doxmlparser.compound.linkedTextType::insert_ref_at(), doxmlparser.compound.highlightType::insert_ref_at(), doxmlparser.compound.docTitleType::insert_ref_at(), doxmlparser.compound.docSummaryType::insert_ref_at(), doxmlparser.compound.docParaType::insert_ref_at(), doxmlparser.compound.docMarkupType::insert_ref_at(), doxmlparser.compound.docURLLink::insert_ref_at(), doxmlparser.compound.docRefTextType::insert_ref_at(), doxmlparser.compound.docCaptionType::insert_ref_at(), doxmlparser.compound.docHeadingType::insert_ref_at(), doxmlparser.compound.docImageType::insert_ref_at(), doxmlparser.compound.docDotMscType::insert_ref_at(), doxmlparser.compound.docImageFileType::insert_ref_at(), doxmlparser.compound.docPlantumlType::insert_ref_at(), doxmlparser.compound.docTocItemType::insert_ref_at(), doxmlparser.compound.linkedTextType::replace_ref_at(), doxmlparser.compound.highlightType::replace_ref_at(), doxmlparser.compound.docTitleType::replace_ref_at(), doxmlparser.compound.docSummaryType::replace_ref_at(), doxmlparser.compound.docParaType::replace_ref_at(), doxmlparser.compound.docMarkupType::replace_ref_at(), doxmlparser.compound.docURLLink::replace_ref_at(), doxmlparser.compound.docRefTextType::replace_ref_at(), doxmlparser.compound.docCaptionType::replace_ref_at(), doxmlparser.compound.docHeadingType::replace_ref_at(), doxmlparser.compound.docImageType::replace_ref_at(), doxmlparser.compound.docDotMscType::replace_ref_at(), doxmlparser.compound.docImageFileType::replace_ref_at(), doxmlparser.compound.docPlantumlType::replace_ref_at(), doxmlparser.compound.docTocItemType::replace_ref_at(), doxmlparser.compound.linkedTextType::set_ref(), doxmlparser.compound.highlightType::set_ref(), doxmlparser.compound.docTitleType::set_ref(), doxmlparser.compound.docSummaryType::set_ref(), doxmlparser.compound.docParaType::set_ref(), doxmlparser.compound.docMarkupType::set_ref(), doxmlparser.compound.docURLLink::set_ref(), doxmlparser.compound.docRefTextType::set_ref(), doxmlparser.compound.docCaptionType::set_ref(), doxmlparser.compound.docHeadingType::set_ref(), doxmlparser.compound.docImageType::set_ref(), doxmlparser.compound.docDotMscType::set_ref(), doxmlparser.compound.docImageFileType::set_ref(), doxmlparser.compound.docPlantumlType::set_ref(), doxmlparser.compound.docTocItemType::set_ref(), doxmlparser.compound.docParamType::set_ref(), and doxmlparser.compound.docParamName::set_ref().
ref() [2/2]
QCString DocLinkedWord::ref () const [inline]
Definition at line 166 of file docnode.h.
{ return m_ref; }
References m_ref.
Referenced by doxmlparser.compound.highlightType::__init__(), doxmlparser.compound.docParamName::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.linkedTextType::__init__(), doxmlparser.compound.docParamType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.linkedTextType::add_ref(), doxmlparser.compound.highlightType::add_ref(), doxmlparser.compound.docTitleType::add_ref(), doxmlparser.compound.docSummaryType::add_ref(), doxmlparser.compound.docParaType::add_ref(), doxmlparser.compound.docMarkupType::add_ref(), doxmlparser.compound.docURLLink::add_ref(), doxmlparser.compound.docRefTextType::add_ref(), doxmlparser.compound.docCaptionType::add_ref(), doxmlparser.compound.docHeadingType::add_ref(), doxmlparser.compound.docImageType::add_ref(), doxmlparser.compound.docDotMscType::add_ref(), doxmlparser.compound.docImageFileType::add_ref(), doxmlparser.compound.docPlantumlType::add_ref(), doxmlparser.compound.docTocItemType::add_ref(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docParamName::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.highlightType::exportChildren(), doxmlparser.compound.linkedTextType::get_ref(), doxmlparser.compound.highlightType::get_ref(), doxmlparser.compound.docTitleType::get_ref(), doxmlparser.compound.docSummaryType::get_ref(), doxmlparser.compound.docParaType::get_ref(), doxmlparser.compound.docMarkupType::get_ref(), doxmlparser.compound.docURLLink::get_ref(), doxmlparser.compound.docRefTextType::get_ref(), doxmlparser.compound.docCaptionType::get_ref(), doxmlparser.compound.docHeadingType::get_ref(), doxmlparser.compound.docImageType::get_ref(), doxmlparser.compound.docDotMscType::get_ref(), doxmlparser.compound.docImageFileType::get_ref(), doxmlparser.compound.docPlantumlType::get_ref(), doxmlparser.compound.docTocItemType::get_ref(), doxmlparser.compound.docParamType::get_ref(), doxmlparser.compound.docParamName::get_ref(), doxmlparser.compound.linkedTextType::hasContent_(), doxmlparser.compound.highlightType::hasContent_(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docParamType::hasContent_(), doxmlparser.compound.docParamName::hasContent_(), doxmlparser.compound.linkedTextType::insert_ref_at(), doxmlparser.compound.highlightType::insert_ref_at(), doxmlparser.compound.docTitleType::insert_ref_at(), doxmlparser.compound.docSummaryType::insert_ref_at(), doxmlparser.compound.docParaType::insert_ref_at(), doxmlparser.compound.docMarkupType::insert_ref_at(), doxmlparser.compound.docURLLink::insert_ref_at(), doxmlparser.compound.docRefTextType::insert_ref_at(), doxmlparser.compound.docCaptionType::insert_ref_at(), doxmlparser.compound.docHeadingType::insert_ref_at(), doxmlparser.compound.docImageType::insert_ref_at(), doxmlparser.compound.docDotMscType::insert_ref_at(), doxmlparser.compound.docImageFileType::insert_ref_at(), doxmlparser.compound.docPlantumlType::insert_ref_at(), doxmlparser.compound.docTocItemType::insert_ref_at(), doxmlparser.compound.linkedTextType::replace_ref_at(), doxmlparser.compound.highlightType::replace_ref_at(), doxmlparser.compound.docTitleType::replace_ref_at(), doxmlparser.compound.docSummaryType::replace_ref_at(), doxmlparser.compound.docParaType::replace_ref_at(), doxmlparser.compound.docMarkupType::replace_ref_at(), doxmlparser.compound.docURLLink::replace_ref_at(), doxmlparser.compound.docRefTextType::replace_ref_at(), doxmlparser.compound.docCaptionType::replace_ref_at(), doxmlparser.compound.docHeadingType::replace_ref_at(), doxmlparser.compound.docImageType::replace_ref_at(), doxmlparser.compound.docDotMscType::replace_ref_at(), doxmlparser.compound.docImageFileType::replace_ref_at(), doxmlparser.compound.docPlantumlType::replace_ref_at(), doxmlparser.compound.docTocItemType::replace_ref_at(), doxmlparser.compound.linkedTextType::set_ref(), doxmlparser.compound.highlightType::set_ref(), doxmlparser.compound.docTitleType::set_ref(), doxmlparser.compound.docSummaryType::set_ref(), doxmlparser.compound.docParaType::set_ref(), doxmlparser.compound.docMarkupType::set_ref(), doxmlparser.compound.docURLLink::set_ref(), doxmlparser.compound.docRefTextType::set_ref(), doxmlparser.compound.docCaptionType::set_ref(), doxmlparser.compound.docHeadingType::set_ref(), doxmlparser.compound.docImageType::set_ref(), doxmlparser.compound.docDotMscType::set_ref(), doxmlparser.compound.docImageFileType::set_ref(), doxmlparser.compound.docPlantumlType::set_ref(), doxmlparser.compound.docTocItemType::set_ref(), doxmlparser.compound.docParamType::set_ref(), and doxmlparser.compound.docParamName::set_ref().
relPath() [1/2]
QCString DocLinkedWord::relPath () const [inline]
Definition at line 165 of file docnode.h.
{ return m_relPath; }
References m_relPath.
relPath() [2/2]
QCString DocLinkedWord::relPath () const [inline]
Definition at line 165 of file docnode.h.
{ return m_relPath; }
References m_relPath.
tooltip() [1/2]
QCString DocLinkedWord::tooltip () const [inline]
Definition at line 168 of file docnode.h.
{ return m_tooltip; }
References m_tooltip.
Referenced by doxmlparser.compound.refTextType::__init__(), doxmlparser.compound.refTextType::buildAttributes(), doxmlparser.compound.refTextType::exportAttributes(), doxmlparser.compound.refTextType::get_tooltip(), and doxmlparser.compound.refTextType::set_tooltip().
tooltip() [2/2]
QCString DocLinkedWord::tooltip () const [inline]
Definition at line 168 of file docnode.h.
{ return m_tooltip; }
References m_tooltip.
Referenced by doxmlparser.compound.refTextType::__init__(), doxmlparser.compound.refTextType::buildAttributes(), doxmlparser.compound.refTextType::exportAttributes(), doxmlparser.compound.refTextType::get_tooltip(), and doxmlparser.compound.refTextType::set_tooltip().
word() [1/2]
QCString DocLinkedWord::word () const [inline]
Definition at line 163 of file docnode.h.
{ return m_word; }
References m_word.
Referenced by DocLinkedWord(), and PerlModDocVisitor::operator()().
word() [2/2]
QCString DocLinkedWord::word () const [inline]
Definition at line 163 of file docnode.h.
{ return m_word; }
References m_word.
Member Data Documentation
m_anchor
QCString DocLinkedWord::m_anchor [private]
Definition at line 175 of file docnode.h.
Referenced by anchor().
m_file
QCString DocLinkedWord::m_file [private]
Definition at line 173 of file docnode.h.
Referenced by file().
m_ref
QCString DocLinkedWord::m_ref [private]
Definition at line 172 of file docnode.h.
Referenced by ref().
m_relPath
QCString DocLinkedWord::m_relPath [private]
Definition at line 174 of file docnode.h.
Referenced by relPath().
m_tooltip
QCString DocLinkedWord::m_tooltip [private]
Definition at line 176 of file docnode.h.
Referenced by tooltip().
m_word
QCString DocLinkedWord::m_word [private]
Definition at line 171 of file docnode.h.
Referenced by word().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp