SectionManager Class Reference
singleton class that owns the list of all sections
#include <section.h>
Public Member Functions
SectionInfo * add (const SectionInfo &si)
SectionInfo * add (const QCString &label, const QCString &fileName, int lineNr, const QCString &title, SectionType type, int level, const QCString &ref=QCString())
SectionInfo * replace (const QCString &label, const QCString &fileName, int lineNr, const QCString &title, SectionType type, int level, const QCString &ref=QCString())
SectionInfo * add (const SectionInfo &si)
SectionInfo * add (const QCString &label, const QCString &fileName, int lineNr, const QCString &title, SectionType type, int level, const QCString &ref=QCString())
SectionInfo * replace (const QCString &label, const QCString &fileName, int lineNr, const QCString &title, SectionType type, int level, const QCString &ref=QCString())
Static Public Member Functions
static SectionManager & instance ()
returns a reference to the singleton
static SectionManager & instance ()
returns a reference to the singleton
Private Member Functions
SectionManager ()
SectionManager (const SectionManager &other)=delete
SectionManager & operator= (const SectionManager &other)=delete
SectionManager ()
SectionManager (const SectionManager &other)=delete
SectionManager & operator= (const SectionManager &other)=delete
Additional Inherited Members
Detailed Description
singleton class that owns the list of all sections
Definition at line 130 of file section.h.
Constructor & Destructor Documentation
SectionManager() [1/4]
SectionManager::SectionManager () [inline], [private]
Definition at line 179 of file section.h.
{}
SectionManager() [2/4]
SectionManager::SectionManager (const SectionManager & other) [private], [delete]
SectionManager() [3/4]
SectionManager::SectionManager () [inline], [private]
Definition at line 179 of file section.h.
{}
SectionManager() [4/4]
SectionManager::SectionManager (const SectionManager & other) [private], [delete]
Member Function Documentation
add() [1/4]
SectionInfo * SectionManager::add (const QCString & label, const QCString & fileName, int lineNr, const QCString & title, SectionType type, int level, const QCString & ref = QCString()) [inline]
Add a new section Return a non-owning pointer to the newly added section
Definition at line 143 of file section.h.
    {
      return LinkedMap<SectionInfo>::add(label.data(),fileName,lineNr,title,type,level,ref);
    }
References LinkedMap< T, Hash, KeyEqual, Map >::add(), QCString::data(), and level.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [2/4]
SectionInfo * SectionManager::add (const QCString & label, const QCString & fileName, int lineNr, const QCString & title, SectionType type, int level, const QCString & ref = QCString()) [inline]
Add a new section Return a non-owning pointer to the newly added section
Definition at line 143 of file section.h.
    {
      return LinkedMap<SectionInfo>::add(label.data(),fileName,lineNr,title,type,level,ref);
    }
References LinkedMap< T, Hash, KeyEqual, Map >::add(), QCString::data(), and level.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [3/4]
SectionInfo * SectionManager::add (const SectionInfo & si) [inline]
Add a new section given the data of an existing section. Returns a non-owning pointer to the newly added section.
Definition at line 135 of file section.h.
    {
      return LinkedMap<SectionInfo>::add(si.label(),si.fileName(),
                      si.lineNr(),si.title(),si.type(),si.level(),si.ref());
    }
References LinkedMap< T, Hash, KeyEqual, Map >::add(), SectionInfo::fileName(), SectionInfo::label(), SectionInfo::level(), SectionInfo::lineNr(), SectionInfo::ref(), SectionInfo::title(), and SectionInfo::type().
Referenced by doxmlparser.compound.memberdefType::__init__(), addAnchor(), anonymous_namespace{tagreader.cpp}::TagFileParser::addDocAnchors(), addRelatedPage(), addSection(), DefinitionImpl::addSectionsToDefinition(), addXRefItem(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), findMainPage(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [4/4]
SectionInfo * SectionManager::add (const SectionInfo & si) [inline]
Add a new section given the data of an existing section. Returns a non-owning pointer to the newly added section.
Definition at line 135 of file section.h.
    {
      return LinkedMap<SectionInfo>::add(si.label(),si.fileName(),
                      si.lineNr(),si.title(),si.type(),si.level(),si.ref());
    }
References LinkedMap< T, Hash, KeyEqual, Map >::add(), SectionInfo::fileName(), SectionInfo::label(), SectionInfo::level(), SectionInfo::lineNr(), SectionInfo::ref(), SectionInfo::title(), and SectionInfo::type().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
instance() [1/2]
static SectionManager & SectionManager::instance () [inline], [static]
returns a reference to the singleton
Definition at line 172 of file section.h.
    {
      static SectionManager sm;
      return sm;
    }
Referenced by addAnchor(), anonymous_namespace{tagreader.cpp}::TagFileParser::addDocAnchors(), addRelatedPage(), addSection(), DefinitionImpl::addSectionsToDefinition(), addXRefItem(), cleanUpDoxygen(), clearAll(), DocAnchor::DocAnchor(), DocHtmlCaption::DocHtmlCaption(), DocRef::DocRef(), findMainPage(), PerlModGenerator::generatePerlModForPage(), generateXMLForPage(), DocSection::parse(), DocSecRefItem::parse(), DocRoot::parse(), processSection(), resolveLink(), resolveUserReferences(), PageDefImpl::writeDocumentation(), writeGroupTreeNode(), GroupDefImpl::writePageDocumentation(), and PageDefImpl::writePageDocumentation().
instance() [2/2]
static SectionManager & SectionManager::instance () [inline], [static]
returns a reference to the singleton
Definition at line 172 of file section.h.
    {
      static SectionManager sm;
      return sm;
    }
operator=() [1/2]
SectionManager & SectionManager::operator= (const SectionManager & other) [private], [delete]
operator=() [2/2]
SectionManager & SectionManager::operator= (const SectionManager & other) [private], [delete]
replace() [1/2]
SectionInfo * SectionManager::replace (const QCString & label, const QCString & fileName, int lineNr, const QCString & title, SectionType type, int level, const QCString & ref = QCString()) [inline]
Replace an existing section with a new one Return a non-owning pointer to the newly added section
Definition at line 151 of file section.h.
    {
      SectionInfo *si = LinkedMap<SectionInfo>::find(label.data());
      if (si)
      {
        si->setFileName(fileName);
        si->setLineNr(lineNr);
        si->setTitle(title);
        si->setType(type);
        si->setLevel(level);
        si->setReference(ref);
        return si;
      }
      else
      {
        return LinkedMap<SectionInfo>::add(label.data(),fileName,lineNr,title,type,level,ref);
      }
    }
References LinkedMap< T, Hash, KeyEqual, Map >::add(), QCString::data(), LinkedMap< T, Hash, KeyEqual, Map >::find(), level, SectionInfo::setFileName(), SectionInfo::setLevel(), SectionInfo::setLineNr(), SectionInfo::setReference(), SectionInfo::setTitle(), and SectionInfo::setType().
Referenced by addAnchor(), addRelatedPage(), addSection(), addXRefItem(), and findMainPage().
replace() [2/2]
SectionInfo * SectionManager::replace (const QCString & label, const QCString & fileName, int lineNr, const QCString & title, SectionType type, int level, const QCString & ref = QCString()) [inline]
Replace an existing section with a new one Return a non-owning pointer to the newly added section
Definition at line 151 of file section.h.
    {
      SectionInfo *si = LinkedMap<SectionInfo>::find(label.data());
      if (si)
      {
        si->setFileName(fileName);
        si->setLineNr(lineNr);
        si->setTitle(title);
        si->setType(type);
        si->setLevel(level);
        si->setReference(ref);
        return si;
      }
      else
      {
        return LinkedMap<SectionInfo>::add(label.data(),fileName,lineNr,title,type,level,ref);
      }
    }
References LinkedMap< T, Hash, KeyEqual, Map >::add(), QCString::data(), LinkedMap< T, Hash, KeyEqual, Map >::find(), level, SectionInfo::setFileName(), SectionInfo::setLevel(), SectionInfo::setLineNr(), SectionInfo::setReference(), SectionInfo::setTitle(), and SectionInfo::setType().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/section.h
doxygen/src/section.h