SymbolIndicesContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
SymbolIndicesContext (const SearchIndexInfo &info)
virtual ~SymbolIndicesContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
SymbolIndicesContext (const SearchIndexInfo &info)
virtual ~SymbolIndicesContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc (const SearchIndexInfo &info)
static TemplateListIntfPtr alloc (const SearchIndexInfo &info)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 1334 of file context.h.
Constructor & Destructor Documentation
SymbolIndicesContext() [1/2]
SymbolIndicesContext::SymbolIndicesContext (const SearchIndexInfo & info)
Definition at line 8731 of file context.cpp.
                                                                      : p(std::make_unique<Private>(info))
{
}
 SymbolIndicesContext() [1/2]
SymbolIndicesContext::~SymbolIndicesContext () [virtual]
Definition at line 8735 of file context.cpp.
{
}
SymbolIndicesContext() [2/2]
SymbolIndicesContext::SymbolIndicesContext (const SearchIndexInfo & info)
 SymbolIndicesContext() [2/2]
virtual SymbolIndicesContext::~SymbolIndicesContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr SymbolIndicesContext::alloc (const SearchIndexInfo & info) [inline], [static]
Definition at line 1337 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<SymbolIndicesContext>(info)); }
Referenced by SearchIndexContext::Private::createSymbolIndices().
alloc() [2/2]
static TemplateListIntfPtr SymbolIndicesContext::alloc (const SearchIndexInfo & info) [inline], [static]
Definition at line 1337 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<SymbolIndicesContext>(info)); }
at() [1/2]
TemplateVariant SymbolIndicesContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 8745 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant SymbolIndicesContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t SymbolIndicesContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 8740 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t SymbolIndicesContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr SymbolIndicesContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 8750 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr SymbolIndicesContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > SymbolIndicesContext::p [private]
Definition at line 1350 of file context.h.
Referenced by at(), count(), and createIterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp