BaseOutputDocInterface Class Reference
#include <outputgen.h>
Public Types
enum ParamListTypes {
Param
, RetVal
, Exception
, Param
,
RetVal
, Exception
 }
enum SectionTypes { EnumValues
, Examples
, EnumValues
, Examples
 }
enum ParamListTypes {
Param
, RetVal
, Exception
, Param
,
RetVal
, Exception
 }
enum SectionTypes { EnumValues
, Examples
, EnumValues
, Examples
 }
Public Member Functions
virtual void parseText (const QCString &)
virtual void startItemList ()=0
virtual void startItemListItem ()=0
virtual void endItemListItem ()=0
virtual void endItemList ()=0
virtual void docify (const QCString &s)=0
virtual void writeChar (char c)=0
virtual void writeString (const QCString &text)=0
virtual void startParagraph (const QCString &classDef)=0
virtual void endParagraph ()=0
virtual void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)=0
virtual void startHtmlLink (const QCString &url)=0
virtual void endHtmlLink ()=0
virtual void startBold ()=0
virtual void endBold ()=0
virtual void startTypewriter ()=0
virtual void endTypewriter ()=0
virtual void startEmphasis ()=0
virtual void endEmphasis ()=0
virtual void writeRuler ()=0
virtual void startDescription ()=0
virtual void endDescription ()=0
virtual void startDescItem ()=0
virtual void startDescForItem ()=0
virtual void endDescForItem ()=0
virtual void endDescItem ()=0
virtual void startCenter ()=0
virtual void endCenter ()=0
virtual void startSmall ()=0
virtual void endSmall ()=0
virtual void startExamples ()=0
virtual void endExamples ()=0
virtual void startParamList (ParamListTypes t, const QCString &title)=0
virtual void endParamList ()=0
virtual void startTitle ()=0
virtual void endTitle ()=0
virtual void writeAnchor (const QCString &fileName, const QCString &name)=0
virtual void startSection (const QCString &, const QCString &, SectionType)=0
virtual void endSection (const QCString &, SectionType)=0
virtual void lineBreak (const QCString &style)=0
virtual void addIndexItem (const QCString &s1, const QCString &s2)=0
virtual void writeNonBreakableSpace (int)=0
virtual void startDescTable (const QCString &title)=0
virtual void endDescTable ()=0
virtual void startDescTableRow ()=0
virtual void endDescTableRow ()=0
virtual void startDescTableTitle ()=0
virtual void endDescTableTitle ()=0
virtual void startDescTableData ()=0
virtual void endDescTableData ()=0
virtual void startTextLink (const QCString &file, const QCString &anchor)=0
virtual void endTextLink ()=0
virtual void startPageRef ()=0
virtual void endPageRef (const QCString &, const QCString &)=0
virtual void startSubsection ()=0
virtual void endSubsection ()=0
virtual void startSubsubsection ()=0
virtual void endSubsubsection ()=0
virtual void parseText (const QCString &)
virtual void startItemList ()=0
virtual void startItemListItem ()=0
virtual void endItemListItem ()=0
virtual void endItemList ()=0
virtual void docify (const QCString &s)=0
virtual void writeChar (char c)=0
virtual void writeString (const QCString &text)=0
virtual void startParagraph (const QCString &classDef)=0
virtual void endParagraph ()=0
virtual void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)=0
virtual void startHtmlLink (const QCString &url)=0
virtual void endHtmlLink ()=0
virtual void startBold ()=0
virtual void endBold ()=0
virtual void startTypewriter ()=0
virtual void endTypewriter ()=0
virtual void startEmphasis ()=0
virtual void endEmphasis ()=0
virtual void writeRuler ()=0
virtual void startDescription ()=0
virtual void endDescription ()=0
virtual void startDescItem ()=0
virtual void startDescForItem ()=0
virtual void endDescForItem ()=0
virtual void endDescItem ()=0
virtual void startCenter ()=0
virtual void endCenter ()=0
virtual void startSmall ()=0
virtual void endSmall ()=0
virtual void startExamples ()=0
virtual void endExamples ()=0
virtual void startParamList (ParamListTypes t, const QCString &title)=0
virtual void endParamList ()=0
virtual void startTitle ()=0
virtual void endTitle ()=0
virtual void writeAnchor (const QCString &fileName, const QCString &name)=0
virtual void startSection (const QCString &, const QCString &, SectionType)=0
virtual void endSection (const QCString &, SectionType)=0
virtual void lineBreak (const QCString &style)=0
virtual void addIndexItem (const QCString &s1, const QCString &s2)=0
virtual void writeNonBreakableSpace (int)=0
virtual void startDescTable (const QCString &title)=0
virtual void endDescTable ()=0
virtual void startDescTableRow ()=0
virtual void endDescTableRow ()=0
virtual void startDescTableTitle ()=0
virtual void endDescTableTitle ()=0
virtual void startDescTableData ()=0
virtual void endDescTableData ()=0
virtual void startTextLink (const QCString &file, const QCString &anchor)=0
virtual void endTextLink ()=0
virtual void startPageRef ()=0
virtual void endPageRef (const QCString &, const QCString &)=0
virtual void startSubsection ()=0
virtual void endSubsection ()=0
virtual void startSubsubsection ()=0
virtual void endSubsubsection ()=0
Detailed Description
Base Interface used for generating output outside of the comment blocks.
This abstract class is used by output generation functions to generate the output for a specific format, or a list of formats (see OutputList). This interface contains functions that generate fragments of the output.
Definition at line 159 of file outputgen.h.
Member Enumeration Documentation
ParamListTypes [1/2]
enum BaseOutputDocInterface::ParamListTypes
Enumerator
Param
RetVal
Exception
Param
RetVal
Exception
Definition at line 162 of file outputgen.h.
{ Param, RetVal, Exception };
ParamListTypes [2/2]
enum BaseOutputDocInterface::ParamListTypes
Enumerator
Param
RetVal
Exception
Param
RetVal
Exception
Definition at line 162 of file outputgen.h.
{ Param, RetVal, Exception };
SectionTypes [1/2]
enum BaseOutputDocInterface::SectionTypes
Enumerator
EnumValues
Examples
EnumValues
Examples
Definition at line 163 of file outputgen.h.
                      { /*See, Return, Author, Version,
                        Since, Date, Bug, Note,
                        Warning, Par, Deprecated, Pre,
                        Post, Invar, Remark, Attention,
                        Todo, Test, RCS, */
                    EnumValues,
                        Examples
                      };
SectionTypes [2/2]
enum BaseOutputDocInterface::SectionTypes
Enumerator
EnumValues
Examples
EnumValues
Examples
Definition at line 163 of file outputgen.h.
                      { /*See, Return, Author, Version,
                        Since, Date, Bug, Note,
                        Warning, Par, Deprecated, Pre,
                        Post, Invar, Remark, Attention,
                        Todo, Test, RCS, */
                    EnumValues,
                        Examples
                      };
Member Function Documentation
addIndexItem() [1/2]
virtual void BaseOutputDocInterface::addIndexItem (const QCString & s1, const QCString & s2) [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, OutputList, and OutputList.
Referenced by OutputList::addIndexItem().
addIndexItem() [2/2]
virtual void BaseOutputDocInterface::addIndexItem (const QCString & s1, const QCString & s2) [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, OutputList, and OutputList.
docify() [1/2]
virtual void BaseOutputDocInterface::docify (const QCString & s) [pure virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implemented in OutputList, OutputList, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::docify(), and TextGeneratorOLImpl::writeString().
docify() [2/2]
virtual void BaseOutputDocInterface::docify (const QCString & s) [pure virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implemented in OutputList, OutputList, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
endBold() [1/2]
virtual void BaseOutputDocInterface::endBold () [pure virtual]
End a section of text displayed in bold face.
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endBold().
endBold() [2/2]
virtual void BaseOutputDocInterface::endBold () [pure virtual]
End a section of text displayed in bold face.
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endCenter() [1/2]
virtual void BaseOutputDocInterface::endCenter () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endCenter().
endCenter() [2/2]
virtual void BaseOutputDocInterface::endCenter () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endDescForItem() [1/2]
virtual void BaseOutputDocInterface::endDescForItem () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endDescForItem().
endDescForItem() [2/2]
virtual void BaseOutputDocInterface::endDescForItem () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endDescItem() [1/2]
virtual void BaseOutputDocInterface::endDescItem () [pure virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endDescItem().
endDescItem() [2/2]
virtual void BaseOutputDocInterface::endDescItem () [pure virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endDescription() [1/2]
virtual void BaseOutputDocInterface::endDescription () [pure virtual]
Ends a description list: e.g. </dl> in HTML
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endDescription().
endDescription() [2/2]
virtual void BaseOutputDocInterface::endDescription () [pure virtual]
Ends a description list: e.g. </dl> in HTML
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endDescTable() [1/2]
virtual void BaseOutputDocInterface::endDescTable () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endDescTable().
endDescTable() [2/2]
virtual void BaseOutputDocInterface::endDescTable () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endDescTableData() [1/2]
virtual void BaseOutputDocInterface::endDescTableData () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endDescTableData().
endDescTableData() [2/2]
virtual void BaseOutputDocInterface::endDescTableData () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endDescTableRow() [1/2]
virtual void BaseOutputDocInterface::endDescTableRow () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endDescTableRow().
endDescTableRow() [2/2]
virtual void BaseOutputDocInterface::endDescTableRow () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endDescTableTitle() [1/2]
virtual void BaseOutputDocInterface::endDescTableTitle () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endDescTableTitle().
endDescTableTitle() [2/2]
virtual void BaseOutputDocInterface::endDescTableTitle () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endEmphasis() [1/2]
virtual void BaseOutputDocInterface::endEmphasis () [pure virtual]
Ends a section of text displayed in italic.
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endEmphasis().
endEmphasis() [2/2]
virtual void BaseOutputDocInterface::endEmphasis () [pure virtual]
Ends a section of text displayed in italic.
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endExamples() [1/2]
virtual void BaseOutputDocInterface::endExamples () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endExamples().
endExamples() [2/2]
virtual void BaseOutputDocInterface::endExamples () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endHtmlLink() [1/2]
virtual void BaseOutputDocInterface::endHtmlLink () [pure virtual]
Ends a link started by startHtmlLink().
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endHtmlLink().
endHtmlLink() [2/2]
virtual void BaseOutputDocInterface::endHtmlLink () [pure virtual]
Ends a link started by startHtmlLink().
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endItemList() [1/2]
virtual void BaseOutputDocInterface::endItemList () [pure virtual]
Ends a bullet list: e.g. </ul> in html
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endItemList().
endItemList() [2/2]
virtual void BaseOutputDocInterface::endItemList () [pure virtual]
Ends a bullet list: e.g. </ul> in html
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endItemListItem() [1/2]
virtual void BaseOutputDocInterface::endItemListItem () [pure virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endItemListItem().
endItemListItem() [2/2]
virtual void BaseOutputDocInterface::endItemListItem () [pure virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endPageRef() [1/2]
virtual void BaseOutputDocInterface::endPageRef (const QCString & , const QCString &) [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, OutputList, and OutputList.
Referenced by OutputList::endPageRef().
endPageRef() [2/2]
virtual void BaseOutputDocInterface::endPageRef (const QCString & , const QCString &) [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, OutputList, and OutputList.
endParagraph() [1/2]
virtual void BaseOutputDocInterface::endParagraph () [pure virtual]
Ends a paragraph
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endParagraph().
endParagraph() [2/2]
virtual void BaseOutputDocInterface::endParagraph () [pure virtual]
Ends a paragraph
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endParamList() [1/2]
virtual void BaseOutputDocInterface::endParamList () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endParamList().
endParamList() [2/2]
virtual void BaseOutputDocInterface::endParamList () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endSection() [1/2]
virtual void BaseOutputDocInterface::endSection (const QCString & , SectionType) [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, OutputList, and OutputList.
Referenced by OutputList::endSection().
endSection() [2/2]
virtual void BaseOutputDocInterface::endSection (const QCString & , SectionType) [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, OutputList, and OutputList.
endSmall() [1/2]
virtual void BaseOutputDocInterface::endSmall () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endSmall().
endSmall() [2/2]
virtual void BaseOutputDocInterface::endSmall () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endSubsection() [1/2]
virtual void BaseOutputDocInterface::endSubsection () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endSubsection().
endSubsection() [2/2]
virtual void BaseOutputDocInterface::endSubsection () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endSubsubsection() [1/2]
virtual void BaseOutputDocInterface::endSubsubsection () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endSubsubsection().
endSubsubsection() [2/2]
virtual void BaseOutputDocInterface::endSubsubsection () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endTextLink() [1/2]
virtual void BaseOutputDocInterface::endTextLink () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endTextLink().
endTextLink() [2/2]
virtual void BaseOutputDocInterface::endTextLink () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endTitle() [1/2]
virtual void BaseOutputDocInterface::endTitle () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endTitle().
endTitle() [2/2]
virtual void BaseOutputDocInterface::endTitle () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
endTypewriter() [1/2]
virtual void BaseOutputDocInterface::endTypewriter () [pure virtual]
End a section of text displayed in typewriter style.
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::endTypewriter().
endTypewriter() [2/2]
virtual void BaseOutputDocInterface::endTypewriter () [pure virtual]
End a section of text displayed in typewriter style.
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
lineBreak() [1/2]
virtual void BaseOutputDocInterface::lineBreak (const QCString & style) [pure virtual]
Implemented in DocbookGenerator, ManGenerator, DocbookGenerator, ManGenerator, HtmlGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, LatexGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::lineBreak(), and TextGeneratorOLImpl::writeBreak().
lineBreak() [2/2]
virtual void BaseOutputDocInterface::lineBreak (const QCString & style) [pure virtual]
Implemented in DocbookGenerator, ManGenerator, DocbookGenerator, ManGenerator, HtmlGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, LatexGenerator, OutputList, and RTFGenerator.
parseText() [1/2]
virtual void BaseOutputDocInterface::parseText (const QCString &) [inline], [virtual]
Reimplemented in OutputList, and OutputList.
Definition at line 172 of file outputgen.h.
{}
parseText() [2/2]
virtual void BaseOutputDocInterface::parseText (const QCString &) [inline], [virtual]
Reimplemented in OutputList, and OutputList.
Definition at line 172 of file outputgen.h.
{}
startBold() [1/2]
virtual void BaseOutputDocInterface::startBold () [pure virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startBold().
startBold() [2/2]
virtual void BaseOutputDocInterface::startBold () [pure virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startCenter() [1/2]
virtual void BaseOutputDocInterface::startCenter () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startCenter().
startCenter() [2/2]
virtual void BaseOutputDocInterface::startCenter () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startDescForItem() [1/2]
virtual void BaseOutputDocInterface::startDescForItem () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startDescForItem().
startDescForItem() [2/2]
virtual void BaseOutputDocInterface::startDescForItem () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startDescItem() [1/2]
virtual void BaseOutputDocInterface::startDescItem () [pure virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startDescItem().
startDescItem() [2/2]
virtual void BaseOutputDocInterface::startDescItem () [pure virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startDescription() [1/2]
virtual void BaseOutputDocInterface::startDescription () [pure virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startDescription().
startDescription() [2/2]
virtual void BaseOutputDocInterface::startDescription () [pure virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startDescTable() [1/2]
virtual void BaseOutputDocInterface::startDescTable (const QCString & title) [pure virtual]
Implemented in DocbookGenerator, DocbookGenerator, ManGenerator, ManGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, HtmlGenerator, LatexGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startDescTable().
startDescTable() [2/2]
virtual void BaseOutputDocInterface::startDescTable (const QCString & title) [pure virtual]
Implemented in DocbookGenerator, DocbookGenerator, ManGenerator, ManGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, HtmlGenerator, LatexGenerator, OutputList, and RTFGenerator.
startDescTableData() [1/2]
virtual void BaseOutputDocInterface::startDescTableData () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startDescTableData().
startDescTableData() [2/2]
virtual void BaseOutputDocInterface::startDescTableData () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startDescTableRow() [1/2]
virtual void BaseOutputDocInterface::startDescTableRow () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startDescTableRow().
startDescTableRow() [2/2]
virtual void BaseOutputDocInterface::startDescTableRow () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startDescTableTitle() [1/2]
virtual void BaseOutputDocInterface::startDescTableTitle () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startDescTableTitle().
startDescTableTitle() [2/2]
virtual void BaseOutputDocInterface::startDescTableTitle () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startEmphasis() [1/2]
virtual void BaseOutputDocInterface::startEmphasis () [pure virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startEmphasis().
startEmphasis() [2/2]
virtual void BaseOutputDocInterface::startEmphasis () [pure virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startExamples() [1/2]
virtual void BaseOutputDocInterface::startExamples () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startExamples().
startExamples() [2/2]
virtual void BaseOutputDocInterface::startExamples () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startHtmlLink() [1/2]
virtual void BaseOutputDocInterface::startHtmlLink (const QCString & url) [pure virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implemented in DocbookGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startHtmlLink().
startHtmlLink() [2/2]
virtual void BaseOutputDocInterface::startHtmlLink (const QCString & url) [pure virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implemented in DocbookGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startItemList() [1/2]
virtual void BaseOutputDocInterface::startItemList () [pure virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startItemList().
startItemList() [2/2]
virtual void BaseOutputDocInterface::startItemList () [pure virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startItemListItem() [1/2]
virtual void BaseOutputDocInterface::startItemListItem () [pure virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startItemListItem().
startItemListItem() [2/2]
virtual void BaseOutputDocInterface::startItemListItem () [pure virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startPageRef() [1/2]
virtual void BaseOutputDocInterface::startPageRef () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startPageRef().
startPageRef() [2/2]
virtual void BaseOutputDocInterface::startPageRef () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startParagraph() [1/2]
virtual void BaseOutputDocInterface::startParagraph (const QCString & classDef) [pure virtual]
Starts a new paragraph
Starts a new paragraph
Implemented in DocbookGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, OutputList, and OutputList.
Referenced by OutputList::startParagraph().
startParagraph() [2/2]
virtual void BaseOutputDocInterface::startParagraph (const QCString & classDef) [pure virtual]
Starts a new paragraph
Starts a new paragraph
Implemented in DocbookGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, OutputList, and OutputList.
startParamList() [1/2]
virtual void BaseOutputDocInterface::startParamList (ParamListTypes t, const QCString & title) [pure virtual]
Implemented in DocbookGenerator, DocbookGenerator, OutputList, OutputList, HtmlGenerator, RTFGenerator, HtmlGenerator, RTFGenerator, LatexGenerator, ManGenerator, LatexGenerator, and ManGenerator.
Referenced by OutputList::startParamList().
startParamList() [2/2]
virtual void BaseOutputDocInterface::startParamList (ParamListTypes t, const QCString & title) [pure virtual]
Implemented in DocbookGenerator, DocbookGenerator, OutputList, OutputList, HtmlGenerator, RTFGenerator, HtmlGenerator, RTFGenerator, LatexGenerator, ManGenerator, LatexGenerator, and ManGenerator.
startSection() [1/2]
virtual void BaseOutputDocInterface::startSection (const QCString & , const QCString & , SectionType) [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, OutputList, and OutputList.
Referenced by OutputList::startSection().
startSection() [2/2]
virtual void BaseOutputDocInterface::startSection (const QCString & , const QCString & , SectionType) [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, RTFGenerator, OutputList, and OutputList.
startSmall() [1/2]
virtual void BaseOutputDocInterface::startSmall () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startSmall().
startSmall() [2/2]
virtual void BaseOutputDocInterface::startSmall () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startSubsection() [1/2]
virtual void BaseOutputDocInterface::startSubsection () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startSubsection().
startSubsection() [2/2]
virtual void BaseOutputDocInterface::startSubsection () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startSubsubsection() [1/2]
virtual void BaseOutputDocInterface::startSubsubsection () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startSubsubsection().
startSubsubsection() [2/2]
virtual void BaseOutputDocInterface::startSubsubsection () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startTextLink() [1/2]
virtual void BaseOutputDocInterface::startTextLink (const QCString & file, const QCString & anchor) [pure virtual]
Implemented in DocbookGenerator, LatexGenerator, ManGenerator, DocbookGenerator, LatexGenerator, ManGenerator, RTFGenerator, RTFGenerator, HtmlGenerator, OutputList, HtmlGenerator, and OutputList.
Referenced by OutputList::startTextLink().
startTextLink() [2/2]
virtual void BaseOutputDocInterface::startTextLink (const QCString & file, const QCString & anchor) [pure virtual]
Implemented in DocbookGenerator, LatexGenerator, ManGenerator, DocbookGenerator, LatexGenerator, ManGenerator, RTFGenerator, RTFGenerator, HtmlGenerator, OutputList, HtmlGenerator, and OutputList.
startTitle() [1/2]
virtual void BaseOutputDocInterface::startTitle () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startTitle().
startTitle() [2/2]
virtual void BaseOutputDocInterface::startTitle () [pure virtual]
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
startTypewriter() [1/2]
virtual void BaseOutputDocInterface::startTypewriter () [pure virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::startTypewriter().
startTypewriter() [2/2]
virtual void BaseOutputDocInterface::startTypewriter () [pure virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
writeAnchor() [1/2]
virtual void BaseOutputDocInterface::writeAnchor (const QCString & fileName, const QCString & name) [pure virtual]
Implemented in DocbookGenerator, ManGenerator, DocbookGenerator, ManGenerator, HtmlGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, LatexGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::writeAnchor().
writeAnchor() [2/2]
virtual void BaseOutputDocInterface::writeAnchor (const QCString & fileName, const QCString & name) [pure virtual]
Implemented in DocbookGenerator, ManGenerator, DocbookGenerator, ManGenerator, HtmlGenerator, HtmlGenerator, LatexGenerator, OutputList, RTFGenerator, LatexGenerator, OutputList, and RTFGenerator.
writeChar() [1/2]
virtual void BaseOutputDocInterface::writeChar (char c) [pure virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implemented in HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, and DocbookGenerator.
Referenced by OutputList::writeChar().
writeChar() [2/2]
virtual void BaseOutputDocInterface::writeChar (char c) [pure virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implemented in HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, and DocbookGenerator.
writeNonBreakableSpace() [1/2]
virtual void BaseOutputDocInterface::writeNonBreakableSpace (int) [pure virtual]
Implemented in ManGenerator, ManGenerator, OutputList, OutputList, DocbookGenerator, HtmlGenerator, LatexGenerator, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, and RTFGenerator.
Referenced by TextGeneratorOLImpl::writeBreak(), OutputList::writeNonBreakableSpace(), and TextGeneratorOLImpl::writeString().
writeNonBreakableSpace() [2/2]
virtual void BaseOutputDocInterface::writeNonBreakableSpace (int) [pure virtual]
Implemented in ManGenerator, ManGenerator, OutputList, OutputList, DocbookGenerator, HtmlGenerator, LatexGenerator, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, and RTFGenerator.
writeObjectLink() [1/2]
virtual void BaseOutputDocInterface::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [pure virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implemented in DocbookGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by TextGeneratorOLImpl::writeLink(), and OutputList::writeObjectLink().
writeObjectLink() [2/2]
virtual void BaseOutputDocInterface::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [pure virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implemented in DocbookGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
writeRuler() [1/2]
virtual void BaseOutputDocInterface::writeRuler () [pure virtual]
Writes a horizontal ruler to the output
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::writeRuler().
writeRuler() [2/2]
virtual void BaseOutputDocInterface::writeRuler () [pure virtual]
Writes a horizontal ruler to the output
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
writeString() [1/2]
virtual void BaseOutputDocInterface::writeString (const QCString & text) [pure virtual]
Writes an ASCII string to the output, without converting special characters.
Implemented in DocbookGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
Referenced by OutputList::writeString().
writeString() [2/2]
virtual void BaseOutputDocInterface::writeString (const QCString & text) [pure virtual]
Writes an ASCII string to the output, without converting special characters.
Implemented in DocbookGenerator, DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, RTFGenerator, HtmlGenerator, LatexGenerator, ManGenerator, OutputList, and RTFGenerator.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/outputgen.h
doxygen/src/outputgen.h