ConceptLinkedRefMap Class Reference
#include <conceptdef.h>
Public Member Functions
bool declVisible () const
void writeDeclaration (OutputList &ol, const QCString &header, bool localNames) const
void writeDocumentation (OutputList &ol, const Definition *container=0) const
bool declVisible () const
void writeDeclaration (OutputList &ol, const QCString &header, bool localNames) const
void writeDocumentation (OutputList &ol, const Definition *container=0) const
Additional Inherited Members
Detailed Description
Definition at line 69 of file conceptdef.h.
Member Function Documentation
declVisible() [1/2]
bool ConceptLinkedRefMap::declVisible () const
Definition at line 658 of file conceptdef.cpp.
{
  bool hideUndocClasses = Config_getBool(HIDE_UNDOC_CLASSES);
  for (const auto &cd : *this)
  {
    bool isLink = cd->isLinkable();
    if (isLink || !hideUndocClasses)
    {
      return true;
    }
  }
  return false;
}
References Config_getBool.
Referenced by FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), and NamespaceDefImpl::writeSummaryLinks().
declVisible() [2/2]
bool ConceptLinkedRefMap::declVisible () const
writeDeclaration() [1/2]
void ConceptLinkedRefMap::writeDeclaration (OutputList & ol, const QCString & header, bool localNames) const
Definition at line 672 of file conceptdef.cpp.
{
  bool found=FALSE;
  for (const auto &cd : *this)
  {
    cd->writeDeclarationLink(ol,found,header,localNames);
  }
  if (found) ol.endMemberList();
}
References OutputList::endMemberList(), FALSE, and found.
Referenced by FileDefImpl::writeConcepts(), GroupDefImpl::writeConcepts(), and NamespaceDefImpl::writeConcepts().
writeDeclaration() [2/2]
void ConceptLinkedRefMap::writeDeclaration (OutputList & ol, const QCString & header, bool localNames) const
writeDocumentation() [1/2]
void ConceptLinkedRefMap::writeDocumentation (OutputList & ol, const Definition * container = 0) const
writeDocumentation() [2/2]
void ConceptLinkedRefMap::writeDocumentation (OutputList & ol, const Definition * container = 0) const
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/conceptdef.h
doxygen/src/conceptdef.h
doxygen/build/doxygen/src/conceptdef.cpp
doxygen/src/conceptdef.cpp