RefList Class Reference
#include <reflist.h>
Public Member Functions
RefList (const QCString &listName, const QCString &pageTitle, const QCString &secTitle)
bool isEnabled () const
RefItem * add ()
RefItem * find (int itemId)
QCString listName () const
QCString fileName () const
QCString pageTitle () const
QCString sectionTitle () const
void generatePage ()
RefList (const QCString &listName, const QCString &pageTitle, const QCString &secTitle)
bool isEnabled () const
RefItem * add ()
RefItem * find (int itemId)
QCString listName () const
QCString fileName () const
QCString pageTitle () const
QCString sectionTitle () const
void generatePage ()
Private Attributes
int m_id = 0
QCString m_listName
QCString m_fileName
QCString m_pageTitle
QCString m_secTitle
std::vector< std::unique_ptr< RefItem > > m_entries
std::unordered_map< int, RefItem * > m_lookup
Detailed Description
List of cross-referenced items
This class represents a list of items that are put at a certain point in the documentation by some special command and are collected in a list. The items cross-reference the documentation and the list.
Examples are the todo list, the test list and the bug list, introduced by the \todo, \test, and \bug commands respectively.
Definition at line 78 of file reflist.h.
Constructor & Destructor Documentation
RefList() [1/2]
RefList::RefList (const QCString & listName, const QCString & pageTitle, const QCString & secTitle)
Create a list of items that are cross referenced with documentation blocks
Parameters
listName String representing the name of the list.
pageTitle String representing the title of the list page.
secTitle String representing the title of the section.
Definition at line 24 of file reflist.cpp.
                                                                                              :
       m_listName(listName), m_fileName(convertNameToFile(listName,FALSE,TRUE)),
       m_pageTitle(pageTitle), m_secTitle(secTitle)
{
}
RefList() [2/2]
RefList::RefList (const QCString & listName, const QCString & pageTitle, const QCString & secTitle)
Create a list of items that are cross referenced with documentation blocks
Parameters
listName String representing the name of the list.
pageTitle String representing the title of the list page.
secTitle String representing the title of the section.
Member Function Documentation
add() [1/2]
RefItem * RefList::add ()
Adds a new item to the list.
Returns
A unique id for this item.
Definition at line 30 of file reflist.cpp.
{
  m_id++;
  std::unique_ptr<RefItem> item = std::make_unique<RefItem>(m_id,this);
  RefItem *result = item.get();
  m_entries.push_back(std::move(item));
  m_lookup.insert({m_id,result});
  return result;
}
References m_entries, m_id, and m_lookup.
Referenced by doxmlparser.compound.memberdefType::__init__(), addXRefItem(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [2/2]
RefItem * RefList::add ()
Adds a new item to the list.
Returns
A unique id for this item.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
fileName() [1/2]
QCString RefList::fileName () const [inline]
Definition at line 101 of file reflist.h.
{ return m_fileName; }
References m_fileName.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), DocXRefItem::parse(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
QCString RefList::fileName () const [inline]
Definition at line 101 of file reflist.h.
{ return m_fileName; }
References m_fileName.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
find() [1/2]
RefItem * RefList::find (int itemId)
Returns an item given it's id that is obtained with addRefItem()
Parameters
itemId item's identifier.
Returns
A pointer to the todo item's structure.
Definition at line 40 of file reflist.cpp.
{
  auto it = m_lookup.find(itemId);
  return it!=m_lookup.end() ? it->second : nullptr;
}
References m_lookup.
Referenced by DocXRefItem::parse().
find() [2/2]
RefItem * RefList::find (int itemId)
Returns an item given it's id that is obtained with addRefItem()
Parameters
itemId item's identifier.
Returns
A pointer to the todo item's structure.
generatePage() [1/2]
void RefList::generatePage ()
Definition at line 55 of file reflist.cpp.
{
  if (!isEnabled()) return;
  std::sort(m_entries.begin(),m_entries.end(),
            [](std::unique_ptr<RefItem> &left,std::unique_ptr<RefItem> &right)
            { return qstricmp(left->title(),right->title()) < 0; });
  //RefItem *item;
  QCString doc;
  int cnt = 0;
  doc += "<dl class=\"reflist\">";
  QCString lastGroup;
  bool first=true;
  for (const std::unique_ptr<RefItem> &item : m_entries)
  {
    if (item->name().isEmpty()) continue;
    cnt++;
    bool startNewGroup = item->group()!=lastGroup;
    if (startNewGroup)
    {
      if (!first)
      {
        doc += "</dd>";
      }
      doc += " <dt>";
      doc += "\n";
      if (item->scope())
      {
        if (item->scope()->name() != "<globalScope>")
        {
          doc += "\\_setscope ";
          doc += item->scope()->name();
          doc += " ";
        }
      }
      doc += item->prefix();
      doc += " \\_internalref ";
      doc += item->name();
      // escape \'s in title, see issue #5901
      QCString escapedTitle = substitute(item->title(),"\\","\\\\");
      doc += " \""+escapedTitle+"\" ";
      // write declaration in case a function with arguments
      if (!item->args().isEmpty())
      {
        // escape @'s in argument list, needed for Java annotations (see issue #6208)
        // escape \'s in argument list (see issue #6533)
        doc += substitute(substitute(item->args(),"@","@@"),"\\","\\\\");
      }
      doc += "</dt><dd>";
    }
    else
    {
      doc += "<p>";
    }
    doc += " \\anchor ";
    doc += item->anchor();
    doc += " ";
    doc += item->text();
    lastGroup = item->group();
    first = false;
  }
  if (!first)
  {
    doc += "</dd>";
  }
  doc += "</dl>\n";
  //printf("generatePage('%s')\n",doc.data());
  if (cnt>0)
  {
    addRelatedPage(m_listName,m_pageTitle,doc,m_fileName,1,1,RefItemVector(),0,0,TRUE);
  }
}
References addRelatedPage(), isEnabled(), m_entries, m_fileName, m_listName, m_pageTitle, substitute(), and TRUE.
generatePage() [2/2]
void RefList::generatePage ()
isEnabled() [1/2]
bool RefList::isEnabled () const
Definition at line 46 of file reflist.cpp.
{
  if (m_listName=="todo" && !Config_getBool(GENERATE_TODOLIST)) return false;
  else if (m_listName=="test" && !Config_getBool(GENERATE_TESTLIST)) return false;
  else if (m_listName=="bug" && !Config_getBool(GENERATE_BUGLIST)) return false;
  else if (m_listName=="deprecated" && !Config_getBool(GENERATE_DEPRECATEDLIST)) return false;
  return true;
}
References Config_getBool, and m_listName.
Referenced by generatePage(), and DocXRefItem::parse().
isEnabled() [2/2]
bool RefList::isEnabled () const
listName() [1/2]
QCString RefList::listName () const [inline]
Definition at line 100 of file reflist.h.
{ return m_listName; }
References m_listName.
Referenced by DefinitionImpl::_getXRefListId(), and addXRefItem().
listName() [2/2]
QCString RefList::listName () const [inline]
Definition at line 100 of file reflist.h.
{ return m_listName; }
References m_listName.
pageTitle() [1/2]
QCString RefList::pageTitle () const [inline]
Definition at line 102 of file reflist.h.
{ return m_pageTitle; }
References m_pageTitle.
pageTitle() [2/2]
QCString RefList::pageTitle () const [inline]
Definition at line 102 of file reflist.h.
{ return m_pageTitle; }
References m_pageTitle.
sectionTitle() [1/2]
QCString RefList::sectionTitle () const [inline]
Definition at line 103 of file reflist.h.
{ return m_secTitle; }
References m_secTitle.
Referenced by DocXRefItem::parse().
sectionTitle() [2/2]
QCString RefList::sectionTitle () const [inline]
Definition at line 103 of file reflist.h.
{ return m_secTitle; }
References m_secTitle.
Member Data Documentation
m_entries
std::vector< std::unique_ptr< RefItem > > RefList::m_entries [private]
Definition at line 113 of file reflist.h.
Referenced by add(), and generatePage().
m_fileName
QCString RefList::m_fileName [private]
Definition at line 110 of file reflist.h.
Referenced by fileName(), and generatePage().
m_id
int RefList::m_id = 0 [private]
Definition at line 108 of file reflist.h.
Referenced by add().
m_listName
QCString RefList::m_listName [private]
Definition at line 109 of file reflist.h.
Referenced by generatePage(), isEnabled(), and listName().
m_lookup
std::unordered_map< int, RefItem * > RefList::m_lookup [private]
Definition at line 114 of file reflist.h.
Referenced by add(), and find().
m_pageTitle
QCString RefList::m_pageTitle [private]
Definition at line 111 of file reflist.h.
Referenced by generatePage(), and pageTitle().
m_secTitle
QCString RefList::m_secTitle [private]
Definition at line 112 of file reflist.h.
Referenced by sectionTitle().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/reflist.h
doxygen/src/reflist.h
doxygen/build/doxygen/src/reflist.cpp
doxygen/src/reflist.cpp