ManGenerator Class Reference
#include <mangen.h>
Public Member Functions
ManGenerator ()
ManGenerator (const ManGenerator &g)
ManGenerator & operator= (const ManGenerator &g)
virtual ~ManGenerator ()
virtual std::unique_ptr< OutputGenerator > clone () const
OutputType type () const
void writeDoc (const IDocNodeAST *ast, const Definition *, const MemberDef *, int)
void cleanup ()
void startFile (const QCString &name, const QCString &manName, const QCString &title, int)
void writeSearchInfo ()
void writeFooter (const QCString &)
void endFile ()
void clearBuffer ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const QCString &, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int)
void startTitleHead (const QCString &)
void endTitleHead (const QCString &, const QCString &)
void startTitle ()
void endTitle ()
void newParagraph ()
void startParagraph (const QCString &classDef)
void endParagraph ()
void writeString (const QCString &text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const QCString &, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const QCString &ref, const QCString &file)
void endIndexItem (const QCString &ref, const QCString &file)
void docify (const QCString &text)
void codify (const QCString &text)
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &)
void startTextLink (const QCString &, const QCString &)
void endTextLink ()
void startHtmlLink (const QCString &url)
void endHtmlLink ()
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int)
void endGroupHeader (int)
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const QCString &, int)
void endMemberHeader ()
void insertMemberAlign (bool)
void insertMemberAlignLeft (int, bool)
void startMemberSubtitle ()
void endMemberSubtitle ()
void startItemListItem ()
void endItemListItem ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const QCString &, int, const QCString &)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const QCString &, const QCString &)
void startCompoundTemplateParams ()
void endCompoundTemplateParams ()
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void writeRuler ()
void writeAnchor (const QCString &, const QCString &)
void startCodeFragment (const QCString &)
void endCodeFragment (const QCString &)
void writeLineNumber (const QCString &, const QCString &, const QCString &, int l, bool)
void startCodeLine (bool)
void endCodeLine ()
void startEmphasis ()
void endEmphasis ()
void startBold ()
void endBold ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void lineBreak (const QCString &)
void writeChar (char c)
void startMemberDoc (const QCString &, const QCString &, const QCString &, const QCString &, int, int, bool)
void endMemberDoc (bool)
void startDoxyAnchor (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void endDoxyAnchor (const QCString &, const QCString &)
void writeLatexSpacing ()
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name)
void writeEndAnnoItem (const QCString &)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startMemberDescription (const QCString &, const QCString &, bool)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const QCString &, const QCString &)
void writeInheritedSectionTitle (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void startDescList (SectionTypes)
void endDescList ()
void startExamples ()
void endExamples ()
void startParamList (ParamListTypes, const QCString &title)
void endParamList ()
void startDescForItem ()
void endDescForItem ()
void startSection (const QCString &, const QCString &, SectionType)
void endSection (const QCString &, SectionType)
void addIndexItem (const QCString &, const QCString &)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const QCString &, const QCString &)
void startPageRef ()
void endPageRef (const QCString &, const QCString &)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const QCString &)
void writeNavigationPath (const QCString &)
void writeLogo ()
void writeQuickLinks (bool, HighlightedItem, const QCString &)
void writeSummaryLink (const QCString &, const QCString &, const QCString &, bool)
void startContents ()
void endContents ()
void writeNonBreakableSpace (int n)
void startDescTable (const QCString &t)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startDotGraph ()
void endDotGraph (DotClassGraph &)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &)
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &)
void startCallGraph ()
void endCallGraph (DotCallGraph &)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &)
void writeGraphicalHierarchy (DotGfxHierarchyTable &)
void startTextBlock (bool)
void endTextBlock (bool)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool, const QCString &)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool, bool, bool)
void startParameterList (bool)
void endParameterList ()
void exceptionEntry (const QCString &, bool)
void startFontClass (const QCString &)
void endFontClass ()
void startConstraintList (const QCString &)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const QCString &l, bool isLast)
void endLabels ()
void writeCodeAnchor (const QCString &)
ManGenerator ()
ManGenerator (const ManGenerator &g)
ManGenerator & operator= (const ManGenerator &g)
virtual ~ManGenerator ()
virtual std::unique_ptr< OutputGenerator > clone () const
OutputType type () const
void writeDoc (const IDocNodeAST *ast, const Definition *, const MemberDef *, int)
void cleanup ()
void startFile (const QCString &name, const QCString &manName, const QCString &title, int)
void writeSearchInfo ()
void writeFooter (const QCString &)
void endFile ()
void clearBuffer ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const QCString &, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int)
void startTitleHead (const QCString &)
void endTitleHead (const QCString &, const QCString &)
void startTitle ()
void endTitle ()
void newParagraph ()
void startParagraph (const QCString &classDef)
void endParagraph ()
void writeString (const QCString &text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const QCString &, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const QCString &ref, const QCString &file)
void endIndexItem (const QCString &ref, const QCString &file)
void docify (const QCString &text)
void codify (const QCString &text)
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &)
void startTextLink (const QCString &, const QCString &)
void endTextLink ()
void startHtmlLink (const QCString &url)
void endHtmlLink ()
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int)
void endGroupHeader (int)
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const QCString &, int)
void endMemberHeader ()
void insertMemberAlign (bool)
void insertMemberAlignLeft (int, bool)
void startMemberSubtitle ()
void endMemberSubtitle ()
void startItemListItem ()
void endItemListItem ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const QCString &, int, const QCString &)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const QCString &, const QCString &)
void startCompoundTemplateParams ()
void endCompoundTemplateParams ()
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void writeRuler ()
void writeAnchor (const QCString &, const QCString &)
void startCodeFragment (const QCString &)
void endCodeFragment (const QCString &)
void writeLineNumber (const QCString &, const QCString &, const QCString &, int l, bool)
void startCodeLine (bool)
void endCodeLine ()
void startEmphasis ()
void endEmphasis ()
void startBold ()
void endBold ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void lineBreak (const QCString &)
void writeChar (char c)
void startMemberDoc (const QCString &, const QCString &, const QCString &, const QCString &, int, int, bool)
void endMemberDoc (bool)
void startDoxyAnchor (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void endDoxyAnchor (const QCString &, const QCString &)
void writeLatexSpacing ()
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name)
void writeEndAnnoItem (const QCString &)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startMemberDescription (const QCString &, const QCString &, bool)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const QCString &, const QCString &)
void writeInheritedSectionTitle (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void startDescList (SectionTypes)
void endDescList ()
void startExamples ()
void endExamples ()
void startParamList (ParamListTypes, const QCString &title)
void endParamList ()
void startDescForItem ()
void endDescForItem ()
void startSection (const QCString &, const QCString &, SectionType)
void endSection (const QCString &, SectionType)
void addIndexItem (const QCString &, const QCString &)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const QCString &, const QCString &)
void startPageRef ()
void endPageRef (const QCString &, const QCString &)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const QCString &)
void writeNavigationPath (const QCString &)
void writeLogo ()
void writeQuickLinks (bool, HighlightedItem, const QCString &)
void writeSummaryLink (const QCString &, const QCString &, const QCString &, bool)
void startContents ()
void endContents ()
void writeNonBreakableSpace (int n)
void startDescTable (const QCString &t)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startDotGraph ()
void endDotGraph (DotClassGraph &)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &)
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &)
void startCallGraph ()
void endCallGraph (DotCallGraph &)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &)
void writeGraphicalHierarchy (DotGfxHierarchyTable &)
void startTextBlock (bool)
void endTextBlock (bool)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool, const QCString &)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool, bool, bool)
void startParameterList (bool)
void endParameterList ()
void exceptionEntry (const QCString &, bool)
void startFontClass (const QCString &)
void endFontClass ()
void startConstraintList (const QCString &)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const QCString &l, bool isLast)
void endLabels ()
void writeCodeAnchor (const QCString &)
Static Public Member Functions
static void init ()
static void init ()
Private Attributes
bool m_firstCol = true
bool m_paragraph = true
int m_col = 0
bool m_upperCase = false
bool m_insideTabbing = false
bool m_inHeader = false
Additional Inherited Members
Detailed Description
Generator for Man page output.
Definition at line 24 of file mangen.h.
Constructor & Destructor Documentation
ManGenerator() [1/4]
ManGenerator::ManGenerator ()
Definition at line 78 of file mangen.cpp.
                           : OutputGenerator(Config_getString(MAN_OUTPUT)+"/"+getSubdir())
{
}
ManGenerator() [2/4]
ManGenerator::ManGenerator (const ManGenerator & g)
Definition at line 82 of file mangen.cpp.
                                                 : OutputGenerator(og)
{
}
 ManGenerator() [1/2]
ManGenerator::~ManGenerator () [virtual]
Definition at line 97 of file mangen.cpp.
{
}
ManGenerator() [3/4]
ManGenerator::ManGenerator ()
ManGenerator() [4/4]
ManGenerator::ManGenerator (const ManGenerator & g)
 ManGenerator() [2/2]
virtual ManGenerator::~ManGenerator () [virtual]
Member Function Documentation
addIndexItem() [1/2]
void ManGenerator::addIndexItem (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 174 of file mangen.h.
{}
addIndexItem() [2/2]
void ManGenerator::addIndexItem (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 174 of file mangen.h.
{}
cleanup() [1/2]
void ManGenerator::cleanup () [virtual]
Implements OutputGenerator.
Definition at line 118 of file mangen.cpp.
{
  QCString dname = Config_getString(MAN_OUTPUT);
  Dir d(dname.str());
  clearSubDirs(d);
}
References clearSubDirs(), Config_getString, and QCString::str().
cleanup() [2/2]
void ManGenerator::cleanup () [virtual]
Implements OutputGenerator.
clearBuffer() [1/2]
void ManGenerator::clearBuffer ()
clearBuffer() [2/2]
void ManGenerator::clearBuffer ()
clone() [1/2]
std::unique_ptr< OutputGenerator > ManGenerator::clone () const [virtual]
Implements OutputGenerator.
Definition at line 92 of file mangen.cpp.
{
  return std::make_unique<ManGenerator>(*this);
}
clone() [2/2]
virtual std::unique_ptr< OutputGenerator > ManGenerator::clone () const [virtual]
Implements OutputGenerator.
codify() [1/2]
void ManGenerator::codify (const QCString & s) [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 317 of file mangen.cpp.
{
  //static char spaces[]=" ";
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    int spacesToNextTabStop;
    while (*p)
    {
      c=*p++;
      switch(c)
      {
        case '.': m_t << "\\&."; break; // see bug652277
        case '\t': spacesToNextTabStop =
                          Config_getInt(TAB_SIZE) - (m_col%Config_getInt(TAB_SIZE));
                    m_t << Doxygen::spaces.left(spacesToNextTabStop);
                    m_col+=spacesToNextTabStop;
                    break;
        case '\n': m_t << "\n"; m_firstCol=TRUE; m_col=0; break;
        case '\\': m_t << "\\"; m_col++; break;
        case '\"': // no break!
        default: p=writeUTF8Char(m_t,p-1); m_firstCol=FALSE; m_col++; break;
      }
    }
    //printf("%s",str);fflush(stdout);
  }
  m_paragraph=FALSE;
}
References c, Config_getInt, QCString::data(), FALSE, QCString::isEmpty(), QCString::left(), m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, p, Doxygen::spaces, TRUE, and writeUTF8Char().
Referenced by endCodeLine().
codify() [2/2]
void ManGenerator::codify (const QCString & s) [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
docify() [1/2]
void ManGenerator::docify (const QCString & s) [virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
Definition at line 293 of file mangen.cpp.
{
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c=0;
    while ((c=*p++))
    {
      switch(c)
      {
        case '-': m_t << "\\-"; break; // see bug747780
        case '.': m_t << "\\&."; break; // see bug652277
        case '\\': m_t << "\\\\"; m_col++; break;
        case '\n': m_t << "\n"; m_col=0; break;
        case '\"': c = '\''; // no break!
        default: m_t << c; m_col++; break;
      }
    }
    m_firstCol=(c=='\n');
    //printf("%s",str);fflush(stdout);
  }
  m_paragraph=FALSE;
}
References c, QCString::data(), FALSE, QCString::isEmpty(), m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, and p.
Referenced by startConstraintList(), startDescTable(), startExamples(), startMemberDocSimple(), startParamList(), writeCodeLink(), writeObjectLink(), and writeString().
docify() [2/2]
void ManGenerator::docify (const QCString & s) [virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
endAnonTypeScope() [1/2]
void ManGenerator::endAnonTypeScope (int indentLevel) [virtual]
Implements OutputGenerator.
Definition at line 530 of file mangen.cpp.
{
  if (indentLevel==0)
  {
    m_insideTabbing=FALSE;
  }
}
References FALSE, and m_insideTabbing.
endAnonTypeScope() [2/2]
void ManGenerator::endAnonTypeScope (int) [virtual]
Implements OutputGenerator.
endBold() [1/2]
void ManGenerator::endBold () [inline], [virtual]
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 135 of file mangen.h.
{ m_t << "\\fP"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
Referenced by endDescTableTitle(), startConstraintList(), startDescTable(), startExamples(), startParamList(), and writeObjectLink().
endBold() [2/2]
void ManGenerator::endBold () [inline], [virtual]
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 135 of file mangen.h.
{ m_t << "\\fP"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
endCallGraph() [1/2]
void ManGenerator::endCallGraph (DotCallGraph &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 209 of file mangen.h.
{}
endCallGraph() [2/2]
void ManGenerator::endCallGraph (DotCallGraph &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 209 of file mangen.h.
{}
endCenter() [1/2]
void ManGenerator::endCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 155 of file mangen.h.
{}
endCenter() [2/2]
void ManGenerator::endCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 155 of file mangen.h.
{}
endClassDiagram() [1/2]
void ManGenerator::endClassDiagram (const ClassDiagram & , const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 179 of file mangen.h.
{}
endClassDiagram() [2/2]
void ManGenerator::endClassDiagram (const ClassDiagram & , const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 179 of file mangen.h.
{}
endCodeFragment() [1/2]
void ManGenerator::endCodeFragment (const QCString & style) [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 406 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".fi\n";
  m_firstCol=TRUE;
  m_paragraph=FALSE;
  m_col=0;
}
References FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
endCodeFragment() [2/2]
void ManGenerator::endCodeFragment (const QCString & style) [virtual]
Ends a block of code
Implements CodeOutputInterface.
endCodeLine() [1/2]
void ManGenerator::endCodeLine () [inline], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 131 of file mangen.h.
{ codify("\n"); m_col=0; }
References codify(), and m_col.
endCodeLine() [2/2]
void ManGenerator::endCodeLine () [inline], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 131 of file mangen.h.
{ codify("\n"); m_col=0; }
References codify(), and m_col.
endCompoundTemplateParams() [1/2]
void ManGenerator::endCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 116 of file mangen.h.
{ endSubsubsection(); }
References endSubsubsection().
endCompoundTemplateParams() [2/2]
void ManGenerator::endCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 116 of file mangen.h.
{ endSubsubsection(); }
References endSubsubsection().
endConstraintDocs() [1/2]
void ManGenerator::endConstraintDocs () [virtual]
Implements OutputGenerator.
Definition at line 746 of file mangen.cpp.
{
  m_t << "\n"; m_firstCol=TRUE;
}
References m_firstCol, OutputGenerator::m_t, and TRUE.
endConstraintDocs() [2/2]
void ManGenerator::endConstraintDocs () [virtual]
Implements OutputGenerator.
endConstraintList() [1/2]
void ManGenerator::endConstraintList () [virtual]
Implements OutputGenerator.
Definition at line 751 of file mangen.cpp.
{
}
endConstraintList() [2/2]
void ManGenerator::endConstraintList () [virtual]
Implements OutputGenerator.
endConstraintParam() [1/2]
void ManGenerator::endConstraintParam () [virtual]
Implements OutputGenerator.
Definition at line 725 of file mangen.cpp.
{
  endEmphasis();
  endItemListItem();
  m_t << " : ";
}
References endEmphasis(), endItemListItem(), and OutputGenerator::m_t.
endConstraintParam() [2/2]
void ManGenerator::endConstraintParam () [virtual]
Implements OutputGenerator.
endConstraintType() [1/2]
void ManGenerator::endConstraintType () [virtual]
Implements OutputGenerator.
Definition at line 737 of file mangen.cpp.
{
  endEmphasis();
}
References endEmphasis().
endConstraintType() [2/2]
void ManGenerator::endConstraintType () [virtual]
Implements OutputGenerator.
endContents() [1/2]
void ManGenerator::endContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 190 of file mangen.h.
{}
endContents() [2/2]
void ManGenerator::endContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 190 of file mangen.h.
{}
endDescForItem() [1/2]
void ManGenerator::endDescForItem () [virtual]
Implements BaseOutputDocInterface.
Definition at line 512 of file mangen.cpp.
{
}
Referenced by endDescTable().
endDescForItem() [2/2]
void ManGenerator::endDescForItem () [virtual]
Implements BaseOutputDocInterface.
endDescItem() [1/2]
void ManGenerator::endDescItem () [virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 516 of file mangen.cpp.
{
  m_t << "\" 1c\n";
  m_firstCol=TRUE;
}
References m_firstCol, OutputGenerator::m_t, and TRUE.
endDescItem() [2/2]
void ManGenerator::endDescItem () [virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
endDescList() [1/2]
void ManGenerator::endDescList () [inline]
Definition at line 165 of file mangen.h.
{}
endDescList() [2/2]
void ManGenerator::endDescList () [inline]
Definition at line 165 of file mangen.h.
{}
endDescription() [1/2]
void ManGenerator::endDescription () [inline], [virtual]
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 137 of file mangen.h.
{}
endDescription() [2/2]
void ManGenerator::endDescription () [inline], [virtual]
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 137 of file mangen.h.
{}
endDescTable() [1/2]
void ManGenerator::endDescTable () [virtual]
Implements BaseOutputDocInterface.
Definition at line 670 of file mangen.cpp.
{
  endDescForItem();
}
References endDescForItem().
endDescTable() [2/2]
void ManGenerator::endDescTable () [virtual]
Implements BaseOutputDocInterface.
endDescTableData() [1/2]
void ManGenerator::endDescTableData () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 200 of file mangen.h.
{}
endDescTableData() [2/2]
void ManGenerator::endDescTableData () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 200 of file mangen.h.
{}
endDescTableRow() [1/2]
void ManGenerator::endDescTableRow () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 196 of file mangen.h.
{}
endDescTableRow() [2/2]
void ManGenerator::endDescTableRow () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 196 of file mangen.h.
{}
endDescTableTitle() [1/2]
void ManGenerator::endDescTableTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 198 of file mangen.h.
{ endEmphasis(); endBold(); }
References endBold(), and endEmphasis().
endDescTableTitle() [2/2]
void ManGenerator::endDescTableTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 198 of file mangen.h.
{ endEmphasis(); endBold(); }
References endBold(), and endEmphasis().
endDirDepGraph() [1/2]
void ManGenerator::endDirDepGraph (DotDirDeps &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 211 of file mangen.h.
{}
endDirDepGraph() [2/2]
void ManGenerator::endDirDepGraph (DotDirDeps &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 211 of file mangen.h.
{}
endDotGraph() [1/2]
void ManGenerator::endDotGraph (DotClassGraph &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 203 of file mangen.h.
{}
endDotGraph() [2/2]
void ManGenerator::endDotGraph (DotClassGraph &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 203 of file mangen.h.
{}
endDoxyAnchor() [1/2]
void ManGenerator::endDoxyAnchor (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 145 of file mangen.h.
{}
endDoxyAnchor() [2/2]
void ManGenerator::endDoxyAnchor (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 145 of file mangen.h.
{}
endEmphasis() [1/2]
void ManGenerator::endEmphasis () [inline], [virtual]
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 133 of file mangen.h.
{ m_t << "\\fP"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
Referenced by endConstraintParam(), endConstraintType(), and endDescTableTitle().
endEmphasis() [2/2]
void ManGenerator::endEmphasis () [inline], [virtual]
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 133 of file mangen.h.
{ m_t << "\\fP"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
endExamples() [1/2]
void ManGenerator::endExamples () [virtual]
Implements BaseOutputDocInterface.
Definition at line 651 of file mangen.cpp.
{
}
endExamples() [2/2]
void ManGenerator::endExamples () [virtual]
Implements BaseOutputDocInterface.
endFile() [1/2]
void ManGenerator::endFile () [virtual]
Implements OutputGenerator.
Definition at line 172 of file mangen.cpp.
{
  m_t << "\n";
  endPlainFile();
}
References OutputGenerator::endPlainFile(), and OutputGenerator::m_t.
endFile() [2/2]
void ManGenerator::endFile () [virtual]
Implements OutputGenerator.
endFontClass() [1/2]
void ManGenerator::endFontClass () [inline], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 231 of file mangen.h.
{}
endFontClass() [2/2]
void ManGenerator::endFontClass () [inline], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 231 of file mangen.h.
{}
endGroupCollaboration() [1/2]
void ManGenerator::endGroupCollaboration (DotGroupCollaboration &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 207 of file mangen.h.
{}
endGroupCollaboration() [2/2]
void ManGenerator::endGroupCollaboration (DotGroupCollaboration &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 207 of file mangen.h.
{}
endGroupHeader() [1/2]
void ManGenerator::endGroupHeader (int) [virtual]
Implements OutputGenerator.
Definition at line 272 of file mangen.cpp.
{
  m_t << "\"\n.PP \n";
  m_firstCol=TRUE;
  m_paragraph=TRUE;
  m_upperCase=FALSE;
}
References FALSE, m_firstCol, m_paragraph, OutputGenerator::m_t, m_upperCase, and TRUE.
Referenced by endSection().
endGroupHeader() [2/2]
void ManGenerator::endGroupHeader (int) [virtual]
Implements OutputGenerator.
endHeaderSection() [1/2]
void ManGenerator::endHeaderSection () [virtual]
Implements OutputGenerator.
Definition at line 843 of file mangen.cpp.
{
}
endHeaderSection() [2/2]
void ManGenerator::endHeaderSection () [virtual]
Implements OutputGenerator.
endHtmlLink() [1/2]
void ManGenerator::endHtmlLink () [virtual]
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
Definition at line 260 of file mangen.cpp.
{
}
endHtmlLink() [2/2]
void ManGenerator::endHtmlLink () [virtual]
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
endInclDepGraph() [1/2]
void ManGenerator::endInclDepGraph (DotInclDepGraph &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 205 of file mangen.h.
{}
endInclDepGraph() [2/2]
void ManGenerator::endInclDepGraph (DotInclDepGraph &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 205 of file mangen.h.
{}
endIndent() [1/2]
void ManGenerator::endIndent () [inline], [virtual]
Implements OutputGenerator.
Definition at line 176 of file mangen.h.
{}
endIndent() [2/2]
void ManGenerator::endIndent () [inline], [virtual]
Implements OutputGenerator.
Definition at line 176 of file mangen.h.
{}
endIndexItem() [1/2]
void ManGenerator::endIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
Definition at line 233 of file mangen.cpp.
{
}
endIndexItem() [2/2]
void ManGenerator::endIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
endIndexKey() [1/2]
void ManGenerator::endIndexKey () [inline], [virtual]
Implements OutputGenerator.
Definition at line 65 of file mangen.h.
{}
endIndexKey() [2/2]
void ManGenerator::endIndexKey () [inline], [virtual]
Implements OutputGenerator.
Definition at line 65 of file mangen.h.
{}
endIndexList() [1/2]
void ManGenerator::endIndexList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 63 of file mangen.h.
{ newParagraph(); }
References newParagraph().
endIndexList() [2/2]
void ManGenerator::endIndexList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 63 of file mangen.h.
{ newParagraph(); }
References newParagraph().
endIndexListItem() [1/2]
void ManGenerator::endIndexListItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 61 of file mangen.h.
{}
endIndexListItem() [2/2]
void ManGenerator::endIndexListItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 61 of file mangen.h.
{}
endIndexSection() [1/2]
void ManGenerator::endIndexSection (IndexSections) [inline], [virtual]
Implements OutputGenerator.
Definition at line 46 of file mangen.h.
{}
endIndexSection() [2/2]
void ManGenerator::endIndexSection (IndexSections) [inline], [virtual]
Implements OutputGenerator.
Definition at line 46 of file mangen.h.
{}
endIndexValue() [1/2]
void ManGenerator::endIndexValue (const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 67 of file mangen.h.
{}
endIndexValue() [2/2]
void ManGenerator::endIndexValue (const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 67 of file mangen.h.
{}
endInlineHeader() [1/2]
void ManGenerator::endInlineHeader () [virtual]
Implements OutputGenerator.
Definition at line 765 of file mangen.cpp.
{
  m_t << "\\fP\"\n" << ".in +1c\n";
  m_firstCol = FALSE;
}
References FALSE, m_firstCol, and OutputGenerator::m_t.
endInlineHeader() [2/2]
void ManGenerator::endInlineHeader () [virtual]
Implements OutputGenerator.
endInlineMemberDoc() [1/2]
void ManGenerator::endInlineMemberDoc () [virtual]
Implements OutputGenerator.
Definition at line 821 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".br\n";
  m_t << ".PP\n";
  m_firstCol=TRUE;
}
References m_firstCol, OutputGenerator::m_t, and TRUE.
endInlineMemberDoc() [2/2]
void ManGenerator::endInlineMemberDoc () [virtual]
Implements OutputGenerator.
endInlineMemberName() [1/2]
void ManGenerator::endInlineMemberName () [virtual]
Implements OutputGenerator.
Definition at line 812 of file mangen.cpp.
{
  m_t << "\\fP ";
}
References OutputGenerator::m_t.
endInlineMemberName() [2/2]
void ManGenerator::endInlineMemberName () [virtual]
Implements OutputGenerator.
endInlineMemberType() [1/2]
void ManGenerator::endInlineMemberType () [virtual]
Implements OutputGenerator.
Definition at line 802 of file mangen.cpp.
{
  m_t << " ";
}
References OutputGenerator::m_t.
endInlineMemberType() [2/2]
void ManGenerator::endInlineMemberType () [virtual]
Implements OutputGenerator.
endItemList() [1/2]
void ManGenerator::endItemList () [inline], [virtual]
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 69 of file mangen.h.
{ newParagraph(); }
References newParagraph().
endItemList() [2/2]
void ManGenerator::endItemList () [inline], [virtual]
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 69 of file mangen.h.
{ newParagraph(); }
References newParagraph().
endItemListItem() [1/2]
void ManGenerator::endItemListItem () [virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 394 of file mangen.cpp.
{
}
Referenced by endConstraintParam(), and startDescTableTitle().
endItemListItem() [2/2]
void ManGenerator::endItemListItem () [virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
endLabels() [1/2]
void ManGenerator::endLabels () [virtual]
Implements OutputGenerator.
Definition at line 839 of file mangen.cpp.
{
}
endLabels() [2/2]
void ManGenerator::endLabels () [virtual]
Implements OutputGenerator.
endMemberDeclaration() [1/2]
void ManGenerator::endMemberDeclaration (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 161 of file mangen.h.
{}
endMemberDeclaration() [2/2]
void ManGenerator::endMemberDeclaration (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 161 of file mangen.h.
{}
endMemberDescription() [1/2]
void ManGenerator::endMemberDescription () [inline], [virtual]
Implements OutputGenerator.
Definition at line 159 of file mangen.h.
{ m_t << "\""; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
endMemberDescription() [2/2]
void ManGenerator::endMemberDescription () [inline], [virtual]
Implements OutputGenerator.
Definition at line 159 of file mangen.h.
{ m_t << "\""; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
endMemberDoc() [1/2]
void ManGenerator::endMemberDoc (bool) [virtual]
Implements OutputGenerator.
Definition at line 455 of file mangen.cpp.
{
    m_t << "\"\n";
}
References OutputGenerator::m_t.
endMemberDoc() [2/2]
void ManGenerator::endMemberDoc (bool) [virtual]
Implements OutputGenerator.
endMemberDocList() [1/2]
void ManGenerator::endMemberDocList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 104 of file mangen.h.
{}
endMemberDocList() [2/2]
void ManGenerator::endMemberDocList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 104 of file mangen.h.
{}
endMemberDocName() [1/2]
void ManGenerator::endMemberDocName () [inline], [virtual]
Implements OutputGenerator.
Definition at line 221 of file mangen.h.
{}
endMemberDocName() [2/2]
void ManGenerator::endMemberDocName () [inline], [virtual]
Implements OutputGenerator.
Definition at line 221 of file mangen.h.
{}
endMemberDocPrefixItem() [1/2]
void ManGenerator::endMemberDocPrefixItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 219 of file mangen.h.
{}
endMemberDocPrefixItem() [2/2]
void ManGenerator::endMemberDocPrefixItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 219 of file mangen.h.
{}
endMemberDocSimple() [1/2]
void ManGenerator::endMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
Definition at line 790 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".RE\n";
  m_t << ".PP\n";
  m_firstCol=TRUE;
}
References m_firstCol, OutputGenerator::m_t, and TRUE.
endMemberDocSimple() [2/2]
void ManGenerator::endMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
endMemberGroup() [1/2]
void ManGenerator::endMemberGroup (bool) [virtual]
Implements OutputGenerator.
Definition at line 592 of file mangen.cpp.
{
  m_t << "\n.in -1c";
  m_firstCol=FALSE;
}
References FALSE, m_firstCol, and OutputGenerator::m_t.
endMemberGroup() [2/2]
void ManGenerator::endMemberGroup (bool) [virtual]
Implements OutputGenerator.
endMemberGroupDocs() [1/2]
void ManGenerator::endMemberGroupDocs () [virtual]
Implements OutputGenerator.
Definition at line 582 of file mangen.cpp.
{
  m_t << "\n.PP";
}
References OutputGenerator::m_t.
endMemberGroupDocs() [2/2]
void ManGenerator::endMemberGroupDocs () [virtual]
Implements OutputGenerator.
endMemberGroupHeader() [1/2]
void ManGenerator::endMemberGroupHeader () [virtual]
Implements OutputGenerator.
Definition at line 572 of file mangen.cpp.
{
  m_t << "\\fP\"\n.br\n";
  m_firstCol=TRUE;
}
References m_firstCol, OutputGenerator::m_t, and TRUE.
endMemberGroupHeader() [2/2]
void ManGenerator::endMemberGroupHeader () [virtual]
Implements OutputGenerator.
endMemberHeader() [1/2]
void ManGenerator::endMemberHeader () [virtual]
Implements OutputGenerator.
Definition at line 286 of file mangen.cpp.
{
  m_t << "\"\n";
  m_firstCol=TRUE;
  m_paragraph=FALSE;
}
References FALSE, m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
Referenced by endSection().
endMemberHeader() [2/2]
void ManGenerator::endMemberHeader () [virtual]
Implements OutputGenerator.
endMemberItem() [1/2]
void ManGenerator::endMemberItem () [virtual]
Implements OutputGenerator.
Definition at line 546 of file mangen.cpp.
{
  m_t << "\"\n.br";
}
References OutputGenerator::m_t.
endMemberItem() [2/2]
void ManGenerator::endMemberItem () [virtual]
Implements OutputGenerator.
endMemberList() [1/2]
void ManGenerator::endMemberList () [virtual]
Implements OutputGenerator.
Definition at line 559 of file mangen.cpp.
{
  if (!m_insideTabbing)
  {
    m_t << "\n.in -1c"; m_firstCol=FALSE;
  }
}
References FALSE, m_firstCol, m_insideTabbing, and OutputGenerator::m_t.
endMemberList() [2/2]
void ManGenerator::endMemberList () [virtual]
Implements OutputGenerator.
endMemberSections() [1/2]
void ManGenerator::endMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 92 of file mangen.h.
{}
endMemberSections() [2/2]
void ManGenerator::endMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 92 of file mangen.h.
{}
endMemberSubtitle() [1/2]
void ManGenerator::endMemberSubtitle () [inline], [virtual]
Implements OutputGenerator.
Definition at line 100 of file mangen.h.
{}
endMemberSubtitle() [2/2]
void ManGenerator::endMemberSubtitle () [inline], [virtual]
Implements OutputGenerator.
Definition at line 100 of file mangen.h.
{}
endMemberTemplateParams() [1/2]
void ManGenerator::endMemberTemplateParams (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 114 of file mangen.h.
{}
endMemberTemplateParams() [2/2]
void ManGenerator::endMemberTemplateParams (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 114 of file mangen.h.
{}
endPageRef() [1/2]
void ManGenerator::endPageRef (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 181 of file mangen.h.
{}
endPageRef() [2/2]
void ManGenerator::endPageRef (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 181 of file mangen.h.
{}
endParagraph() [1/2]
void ManGenerator::endParagraph () [virtual]
Ends a paragraph
Implements BaseOutputDocInterface.
Definition at line 220 of file mangen.cpp.
{
}
endParagraph() [2/2]
void ManGenerator::endParagraph () [virtual]
Ends a paragraph
Implements BaseOutputDocInterface.
endParameterList() [1/2]
void ManGenerator::endParameterList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 227 of file mangen.h.
{}
endParameterList() [2/2]
void ManGenerator::endParameterList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 227 of file mangen.h.
{}
endParameterName() [1/2]
void ManGenerator::endParameterName (bool , bool , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 225 of file mangen.h.
{}
endParameterName() [2/2]
void ManGenerator::endParameterName (bool , bool , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 225 of file mangen.h.
{}
endParameterType() [1/2]
void ManGenerator::endParameterType () [inline], [virtual]
Implements OutputGenerator.
Definition at line 223 of file mangen.h.
{}
endParameterType() [2/2]
void ManGenerator::endParameterType () [inline], [virtual]
Implements OutputGenerator.
Definition at line 223 of file mangen.h.
{}
endParamList() [1/2]
void ManGenerator::endParamList () [virtual]
Implements BaseOutputDocInterface.
Definition at line 689 of file mangen.cpp.
{
}
endParamList() [2/2]
void ManGenerator::endParamList () [virtual]
Implements BaseOutputDocInterface.
endProjectNumber() [1/2]
void ManGenerator::endProjectNumber () [inline], [virtual]
Implements OutputGenerator.
Definition at line 49 of file mangen.h.
{}
endProjectNumber() [2/2]
void ManGenerator::endProjectNumber () [inline], [virtual]
Implements OutputGenerator.
Definition at line 49 of file mangen.h.
{}
endQuickIndices() [1/2]
void ManGenerator::endQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 183 of file mangen.h.
{}
endQuickIndices() [2/2]
void ManGenerator::endQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 183 of file mangen.h.
{}
endSection() [1/2]
void ManGenerator::endSection (const QCString & , SectionType type) [virtual]
Implements BaseOutputDocInterface.
Definition at line 614 of file mangen.cpp.
{
  if(!m_inHeader)
  {
    switch(type)
    {
      case SectionType::Page: endGroupHeader(0); break;
      case SectionType::Section: endGroupHeader(0); break;
      case SectionType::Subsection: endMemberHeader(); break;
      case SectionType::Subsubsection: endMemberHeader(); break;
      case SectionType::Paragraph: endMemberHeader(); break;
      default: ASSERT(0); break;
    }
  }
  else
  {
    m_t << "\n.PP\n";
    m_firstCol=TRUE;
    m_paragraph=FALSE;
    m_inHeader=FALSE;
  }
}
References ASSERT, endGroupHeader(), endMemberHeader(), FALSE, m_firstCol, m_inHeader, m_paragraph, OutputGenerator::m_t, Page, Paragraph, Section, Subsection, Subsubsection, TRUE, and type().
endSection() [2/2]
void ManGenerator::endSection (const QCString & , SectionType) [virtual]
Implements BaseOutputDocInterface.
endSmall() [1/2]
void ManGenerator::endSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 157 of file mangen.h.
{}
endSmall() [2/2]
void ManGenerator::endSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 157 of file mangen.h.
{}
endSubsection() [1/2]
void ManGenerator::endSubsection () [virtual]
Implements BaseOutputDocInterface.
Definition at line 468 of file mangen.cpp.
{
  m_t << "\"";
}
References OutputGenerator::m_t.
endSubsection() [2/2]
void ManGenerator::endSubsection () [virtual]
Implements BaseOutputDocInterface.
endSubsubsection() [1/2]
void ManGenerator::endSubsubsection () [virtual]
Implements BaseOutputDocInterface.
Definition at line 482 of file mangen.cpp.
{
  m_t << "\"";
}
References OutputGenerator::m_t.
Referenced by endCompoundTemplateParams().
endSubsubsection() [2/2]
void ManGenerator::endSubsubsection () [virtual]
Implements BaseOutputDocInterface.
endTextBlock() [1/2]
void ManGenerator::endTextBlock (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 215 of file mangen.h.
{}
endTextBlock() [2/2]
void ManGenerator::endTextBlock (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 215 of file mangen.h.
{}
endTextLink() [1/2]
void ManGenerator::endTextLink () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 84 of file mangen.h.
{}
endTextLink() [2/2]
void ManGenerator::endTextLink () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 84 of file mangen.h.
{}
endTitle() [1/2]
void ManGenerator::endTitle () [virtual]
Implements BaseOutputDocInterface.
Definition at line 380 of file mangen.cpp.
{
    m_t << "\"";
}
References OutputGenerator::m_t.
endTitle() [2/2]
void ManGenerator::endTitle () [virtual]
Implements BaseOutputDocInterface.
endTitleHead() [1/2]
void ManGenerator::endTitleHead (const QCString & , const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 178 of file mangen.cpp.
{
  m_t << ".TH \"" << name << "\" " << getExtension() << " \""
    << dateToString(FALSE) << "\" \"";
  if (!Config_getString(PROJECT_NUMBER).isEmpty())
    m_t << "Version " << Config_getString(PROJECT_NUMBER) << "\" \"";
  if (Config_getString(PROJECT_NAME).isEmpty())
    m_t << "Doxygen";
  else
    m_t << Config_getString(PROJECT_NAME);
  m_t << "\" \\\" -*- nroff -*-\n";
  m_t << ".ad l\n";
  m_t << ".nh\n";
  m_t << ".SH NAME\n";
  m_t << name;
  m_firstCol=FALSE;
  m_paragraph=TRUE;
  m_inHeader=TRUE;
}
References Config_getString, dateToString(), FALSE, getExtension(), m_firstCol, m_inHeader, m_paragraph, OutputGenerator::m_t, setup::name, and TRUE.
endTitleHead() [2/2]
void ManGenerator::endTitleHead (const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
endTypewriter() [1/2]
void ManGenerator::endTypewriter () [inline], [virtual]
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 88 of file mangen.h.
{ m_t << "\\fP"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
endTypewriter() [2/2]
void ManGenerator::endTypewriter () [inline], [virtual]
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 88 of file mangen.h.
{ m_t << "\\fP"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
exceptionEntry() [1/2]
void ManGenerator::exceptionEntry (const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 228 of file mangen.h.
{}
exceptionEntry() [2/2]
void ManGenerator::exceptionEntry (const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 228 of file mangen.h.
{}
init() [1/2]
void ManGenerator::init () [static]
Definition at line 101 of file mangen.cpp.
{
  QCString manOutput = Config_getString(MAN_OUTPUT);
  Dir d(manOutput.str());
  if (!d.exists() && !d.mkdir(manOutput.str()))
  {
    term("Could not create output directory %s\n",qPrint(manOutput));
  }
  std::string manDir = manOutput.str()+"/"+getSubdir().str();
  if (!d.exists(manDir) && !d.mkdir(manDir))
  {
    term("Could not create output directory %s/%s\n",qPrint(manOutput), qPrint(getSubdir()));
  }
  createSubDirs(d);
}
References Config_getString, createSubDirs(), Dir::exists(), getSubdir(), Dir::mkdir(), qPrint(), QCString::str(), string, and term().
Referenced by generateOutput().
init() [2/2]
static void ManGenerator::init () [static]
insertMemberAlign() [1/2]
void ManGenerator::insertMemberAlign (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 97 of file mangen.h.
{}
insertMemberAlign() [2/2]
void ManGenerator::insertMemberAlign (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 97 of file mangen.h.
{}
insertMemberAlignLeft() [1/2]
void ManGenerator::insertMemberAlignLeft (int , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 98 of file mangen.h.
{}
insertMemberAlignLeft() [2/2]
void ManGenerator::insertMemberAlignLeft (int , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 98 of file mangen.h.
{}
lastIndexPage() [1/2]
void ManGenerator::lastIndexPage () [inline], [virtual]
Implements OutputGenerator.
Definition at line 216 of file mangen.h.
{}
lastIndexPage() [2/2]
void ManGenerator::lastIndexPage () [inline], [virtual]
Implements OutputGenerator.
Definition at line 216 of file mangen.h.
{}
lineBreak() [1/2]
void ManGenerator::lineBreak (const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 140 of file mangen.h.
{ m_t << "\n.br\n"; }
References OutputGenerator::m_t.
lineBreak() [2/2]
void ManGenerator::lineBreak (const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 140 of file mangen.h.
{ m_t << "\n.br\n"; }
References OutputGenerator::m_t.
newParagraph() [1/2]
void ManGenerator::newParagraph ()
Definition at line 198 of file mangen.cpp.
{
  if (!m_paragraph)
  {
    if (!m_firstCol) m_t << "\n";
    m_t << ".PP\n";
    m_firstCol=TRUE;
  }
  m_paragraph=TRUE;
}
References m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
Referenced by endIndexList(), endItemList(), and startCodeFragment().
newParagraph() [2/2]
void ManGenerator::newParagraph ()
operator=() [1/2]
ManGenerator & ManGenerator::operator= (const ManGenerator & g)
Definition at line 86 of file mangen.cpp.
{
  OutputGenerator::operator=(og);
  return *this;
}
References OutputGenerator::operator=().
operator=() [2/2]
ManGenerator & ManGenerator::operator= (const ManGenerator & g)
startAnonTypeScope() [1/2]
void ManGenerator::startAnonTypeScope (int indentLevel) [virtual]
Implements OutputGenerator.
Definition at line 522 of file mangen.cpp.
{
  if (indentLevel==0)
  {
    m_insideTabbing=TRUE;
  }
}
References m_insideTabbing, and TRUE.
startAnonTypeScope() [2/2]
void ManGenerator::startAnonTypeScope (int) [virtual]
Implements OutputGenerator.
startBold() [1/2]
void ManGenerator::startBold () [inline], [virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 134 of file mangen.h.
{ m_t << "\\fB"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
Referenced by startConstraintList(), startDescList(), startDescTable(), startDescTableTitle(), startExamples(), startParamList(), and writeObjectLink().
startBold() [2/2]
void ManGenerator::startBold () [inline], [virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 134 of file mangen.h.
{ m_t << "\\fB"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
startCallGraph() [1/2]
void ManGenerator::startCallGraph () [inline], [virtual]
Implements OutputGenerator.
Definition at line 208 of file mangen.h.
{}
startCallGraph() [2/2]
void ManGenerator::startCallGraph () [inline], [virtual]
Implements OutputGenerator.
Definition at line 208 of file mangen.h.
{}
startCenter() [1/2]
void ManGenerator::startCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 154 of file mangen.h.
{}
startCenter() [2/2]
void ManGenerator::startCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 154 of file mangen.h.
{}
startClassDiagram() [1/2]
void ManGenerator::startClassDiagram () [inline], [virtual]
Implements OutputGenerator.
Definition at line 178 of file mangen.h.
{}
startClassDiagram() [2/2]
void ManGenerator::startClassDiagram () [inline], [virtual]
Implements OutputGenerator.
Definition at line 178 of file mangen.h.
{}
startCodeFragment() [1/2]
void ManGenerator::startCodeFragment (const QCString & style) [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 398 of file mangen.cpp.
{
  newParagraph();
  m_t << ".nf\n";
  m_firstCol=TRUE;
  m_paragraph=FALSE;
}
References FALSE, m_firstCol, m_paragraph, OutputGenerator::m_t, newParagraph(), and TRUE.
startCodeFragment() [2/2]
void ManGenerator::startCodeFragment (const QCString & style) [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
startCodeLine() [1/2]
void ManGenerator::startCodeLine (bool) [inline], [virtual]
Implements CodeOutputInterface.
Definition at line 130 of file mangen.h.
{}
startCodeLine() [2/2]
void ManGenerator::startCodeLine (bool) [inline], [virtual]
Implements CodeOutputInterface.
Definition at line 130 of file mangen.h.
{}
startCompoundTemplateParams() [1/2]
void ManGenerator::startCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 115 of file mangen.h.
{ startSubsubsection(); }
References startSubsubsection().
startCompoundTemplateParams() [2/2]
void ManGenerator::startCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 115 of file mangen.h.
{ startSubsubsection(); }
References startSubsubsection().
startConstraintDocs() [1/2]
void ManGenerator::startConstraintDocs () [virtual]
Implements OutputGenerator.
Definition at line 742 of file mangen.cpp.
{
}
startConstraintDocs() [2/2]
void ManGenerator::startConstraintDocs () [virtual]
Implements OutputGenerator.
startConstraintList() [1/2]
void ManGenerator::startConstraintList (const QCString & header) [virtual]
Implements OutputGenerator.
Definition at line 705 of file mangen.cpp.
{
  if (!m_firstCol)
  { m_t << "\n.PP\n";
    m_firstCol=TRUE; m_paragraph=TRUE;
    m_col=0;
  }
  m_paragraph=FALSE;
  startBold();
  docify(header);
  endBold();
  m_paragraph=TRUE;
}
References docify(), endBold(), FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, startBold(), and TRUE.
startConstraintList() [2/2]
void ManGenerator::startConstraintList (const QCString &) [virtual]
Implements OutputGenerator.
startConstraintParam() [1/2]
void ManGenerator::startConstraintParam () [virtual]
Implements OutputGenerator.
Definition at line 719 of file mangen.cpp.
{
  startItemListItem();
  startEmphasis();
}
References startEmphasis(), and startItemListItem().
startConstraintParam() [2/2]
void ManGenerator::startConstraintParam () [virtual]
Implements OutputGenerator.
startConstraintType() [1/2]
void ManGenerator::startConstraintType () [virtual]
Implements OutputGenerator.
Definition at line 732 of file mangen.cpp.
{
  startEmphasis();
}
References startEmphasis().
startConstraintType() [2/2]
void ManGenerator::startConstraintType () [virtual]
Implements OutputGenerator.
startContents() [1/2]
void ManGenerator::startContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 189 of file mangen.h.
{}
startContents() [2/2]
void ManGenerator::startContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 189 of file mangen.h.
{}
startDescForItem() [1/2]
void ManGenerator::startDescForItem () [virtual]
Implements BaseOutputDocInterface.
Definition at line 502 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  if (!m_paragraph) m_t << ".in -1c\n";
  m_t << ".in +1c\n";
  m_firstCol=TRUE;
  m_paragraph=FALSE;
  m_col=0;
}
References FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
Referenced by startDescTable().
startDescForItem() [2/2]
void ManGenerator::startDescForItem () [virtual]
Implements BaseOutputDocInterface.
startDescItem() [1/2]
void ManGenerator::startDescItem () [virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 495 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".IP \"";
  m_firstCol=FALSE;
}
References FALSE, m_firstCol, and OutputGenerator::m_t.
startDescItem() [2/2]
void ManGenerator::startDescItem () [virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
startDescList() [1/2]
void ManGenerator::startDescList (SectionTypes)
Definition at line 361 of file mangen.cpp.
{
  if (!m_firstCol)
  { m_t << "\n" << ".PP\n";
    m_firstCol=TRUE; m_paragraph=TRUE;
    m_col=0;
  }
  m_paragraph=FALSE;
  startBold();
}
References FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, startBold(), and TRUE.
startDescList() [2/2]
void ManGenerator::startDescList (SectionTypes)
startDescription() [1/2]
void ManGenerator::startDescription () [inline], [virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 136 of file mangen.h.
{}
startDescription() [2/2]
void ManGenerator::startDescription () [inline], [virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 136 of file mangen.h.
{}
startDescTable() [1/2]
void ManGenerator::startDescTable (const QCString & t) [virtual]
Implements BaseOutputDocInterface.
Definition at line 655 of file mangen.cpp.
{
  if (!m_firstCol)
  { m_t << "\n.PP\n";
    m_firstCol=TRUE; m_paragraph=TRUE;
    m_col=0;
  }
  m_paragraph=FALSE;
  startBold();
  docify(title);
  endBold();
  m_paragraph=TRUE;
  startDescForItem();
}
References docify(), endBold(), FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, startBold(), startDescForItem(), and TRUE.
startDescTable() [2/2]
void ManGenerator::startDescTable (const QCString & t) [virtual]
Implements BaseOutputDocInterface.
startDescTableData() [1/2]
void ManGenerator::startDescTableData () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 199 of file mangen.h.
{ m_t << "\n"; m_firstCol=TRUE; }
References m_firstCol, OutputGenerator::m_t, and TRUE.
startDescTableData() [2/2]
void ManGenerator::startDescTableData () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 199 of file mangen.h.
{ m_t << "\n"; m_firstCol=TRUE; }
References m_firstCol, OutputGenerator::m_t, and TRUE.
startDescTableRow() [1/2]
void ManGenerator::startDescTableRow () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 195 of file mangen.h.
{}
startDescTableRow() [2/2]
void ManGenerator::startDescTableRow () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 195 of file mangen.h.
{}
startDescTableTitle() [1/2]
void ManGenerator::startDescTableTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 197 of file mangen.h.
{ startItemListItem(); startBold(); startEmphasis(); endItemListItem(); }
References endItemListItem(), startBold(), startEmphasis(), and startItemListItem().
startDescTableTitle() [2/2]
void ManGenerator::startDescTableTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 197 of file mangen.h.
{ startItemListItem(); startBold(); startEmphasis(); endItemListItem(); }
References endItemListItem(), startBold(), startEmphasis(), and startItemListItem().
startDirDepGraph() [1/2]
void ManGenerator::startDirDepGraph () [inline], [virtual]
Implements OutputGenerator.
Definition at line 210 of file mangen.h.
{}
startDirDepGraph() [2/2]
void ManGenerator::startDirDepGraph () [inline], [virtual]
Implements OutputGenerator.
Definition at line 210 of file mangen.h.
{}
startDotGraph() [1/2]
void ManGenerator::startDotGraph () [inline], [virtual]
Implements OutputGenerator.
Definition at line 202 of file mangen.h.
{}
startDotGraph() [2/2]
void ManGenerator::startDotGraph () [inline], [virtual]
Implements OutputGenerator.
Definition at line 202 of file mangen.h.
{}
startDoxyAnchor() [1/2]
void ManGenerator::startDoxyAnchor (const QCString & , const QCString & manName, const QCString & , const QCString & name, const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 423 of file mangen.cpp.
{
    // something to be done?
    if(!Config_getBool(MAN_LINKS))
    {
    return; // no
    }
    // the name of the link file is derived from the name of the anchor:
    // - truncate after an (optional) ::
    QCString baseName = name;
    int i=baseName.findRev("::");
    if (i!=-1) baseName=baseName.right(baseName.length()-i-2);
    //printf("Converting man link '%s'->'%s'->'%s'\n",
    // name,qPrint(baseName),qPrint(buildFileName(baseName)));
    // - remove dangerous characters and append suffix, then add dir prefix
    QCString fileName=dir()+"/"+buildFileName(baseName);
    FileInfo fi(fileName.str());
    if (!fi.exists())
    {
      std::ofstream linkStream(fileName.str(),std::ofstream::out | std::ofstream::binary);
      if (linkStream.is_open())
      {
        linkStream << ".so " << getSubdir() << "/" << buildFileName(manName) << "\n";
      }
    }
}
References buildFileName(), Config_getBool, OutputGenerator::dir(), FileInfo::exists(), OutputGenerator::fileName(), QCString::findRev(), getSubdir(), QCString::length(), setup::name, out, QCString::right(), and QCString::str().
startDoxyAnchor() [2/2]
void ManGenerator::startDoxyAnchor (const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
startEmphasis() [1/2]
void ManGenerator::startEmphasis () [inline], [virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 132 of file mangen.h.
{ m_t << "\\fI"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
Referenced by startConstraintParam(), startConstraintType(), and startDescTableTitle().
startEmphasis() [2/2]
void ManGenerator::startEmphasis () [inline], [virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 132 of file mangen.h.
{ m_t << "\\fI"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
startExamples() [1/2]
void ManGenerator::startExamples () [virtual]
Implements BaseOutputDocInterface.
Definition at line 637 of file mangen.cpp.
{
  if (!m_firstCol)
  { m_t << "\n" << ".PP\n";
    m_firstCol=TRUE; m_paragraph=TRUE;
    m_col=0;
  }
  m_paragraph=FALSE;
  startBold();
  docify(theTranslator->trExamples());
  endBold();
  m_paragraph=TRUE;
}
References docify(), endBold(), FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, startBold(), theTranslator, Translator::trExamples(), and TRUE.
startExamples() [2/2]
void ManGenerator::startExamples () [virtual]
Implements BaseOutputDocInterface.
startFile() [1/2]
void ManGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int) [virtual]
Implements OutputGenerator.
Definition at line 166 of file mangen.cpp.
{
  startPlainFile(buildFileName(manName));
  m_firstCol=TRUE;
}
References buildFileName(), m_firstCol, OutputGenerator::startPlainFile(), and TRUE.
startFile() [2/2]
void ManGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int) [virtual]
Implements OutputGenerator.
startFontClass() [1/2]
void ManGenerator::startFontClass (const QCString & clsName) [inline], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 230 of file mangen.h.
{}
startFontClass() [2/2]
void ManGenerator::startFontClass (const QCString & clsName) [inline], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 230 of file mangen.h.
{}
startGroupCollaboration() [1/2]
void ManGenerator::startGroupCollaboration () [inline], [virtual]
Implements OutputGenerator.
Definition at line 206 of file mangen.h.
{}
startGroupCollaboration() [2/2]
void ManGenerator::startGroupCollaboration () [inline], [virtual]
Implements OutputGenerator.
Definition at line 206 of file mangen.h.
{}
startGroupHeader() [1/2]
void ManGenerator::startGroupHeader (int) [virtual]
Implements OutputGenerator.
Definition at line 264 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".SH \"";
  m_upperCase=TRUE;
  m_firstCol=FALSE;
}
References FALSE, m_firstCol, OutputGenerator::m_t, m_upperCase, and TRUE.
Referenced by startSection().
startGroupHeader() [2/2]
void ManGenerator::startGroupHeader (int) [virtual]
Implements OutputGenerator.
startHeaderSection() [1/2]
void ManGenerator::startHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 93 of file mangen.h.
{}
startHeaderSection() [2/2]
void ManGenerator::startHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 93 of file mangen.h.
{}
startHtmlLink() [1/2]
void ManGenerator::startHtmlLink (const QCString & url) [virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
Definition at line 256 of file mangen.cpp.
{
}
startHtmlLink() [2/2]
void ManGenerator::startHtmlLink (const QCString & url) [virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
startInclDepGraph() [1/2]
void ManGenerator::startInclDepGraph () [inline], [virtual]
Implements OutputGenerator.
Definition at line 204 of file mangen.h.
{}
startInclDepGraph() [2/2]
void ManGenerator::startInclDepGraph () [inline], [virtual]
Implements OutputGenerator.
Definition at line 204 of file mangen.h.
{}
startIndent() [1/2]
void ManGenerator::startIndent () [inline], [virtual]
Implements OutputGenerator.
Definition at line 175 of file mangen.h.
{}
startIndent() [2/2]
void ManGenerator::startIndent () [inline], [virtual]
Implements OutputGenerator.
Definition at line 175 of file mangen.h.
{}
startIndexItem() [1/2]
void ManGenerator::startIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
Definition at line 229 of file mangen.cpp.
{
}
startIndexItem() [2/2]
void ManGenerator::startIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
startIndexKey() [1/2]
void ManGenerator::startIndexKey () [inline], [virtual]
Implements OutputGenerator.
Definition at line 64 of file mangen.h.
{}
startIndexKey() [2/2]
void ManGenerator::startIndexKey () [inline], [virtual]
Implements OutputGenerator.
Definition at line 64 of file mangen.h.
{}
startIndexList() [1/2]
void ManGenerator::startIndexList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 62 of file mangen.h.
{}
startIndexList() [2/2]
void ManGenerator::startIndexList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 62 of file mangen.h.
{}
startIndexListItem() [1/2]
void ManGenerator::startIndexListItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 60 of file mangen.h.
{}
startIndexListItem() [2/2]
void ManGenerator::startIndexListItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 60 of file mangen.h.
{}
startIndexSection() [1/2]
void ManGenerator::startIndexSection (IndexSections) [inline], [virtual]
Implements OutputGenerator.
Definition at line 45 of file mangen.h.
{}
startIndexSection() [2/2]
void ManGenerator::startIndexSection (IndexSections) [inline], [virtual]
Implements OutputGenerator.
Definition at line 45 of file mangen.h.
{}
startIndexValue() [1/2]
void ManGenerator::startIndexValue (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 66 of file mangen.h.
{}
startIndexValue() [2/2]
void ManGenerator::startIndexValue (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 66 of file mangen.h.
{}
startInlineHeader() [1/2]
void ManGenerator::startInlineHeader () [virtual]
Implements OutputGenerator.
Definition at line 756 of file mangen.cpp.
{
  if (!m_firstCol)
  {
    m_t << "\n.PP\n" << ".in -1c\n";
  }
  m_t << ".RI \"\\fB";
}
References m_firstCol, and OutputGenerator::m_t.
startInlineHeader() [2/2]
void ManGenerator::startInlineHeader () [virtual]
Implements OutputGenerator.
startInlineMemberDoc() [1/2]
void ManGenerator::startInlineMemberDoc () [virtual]
Implements OutputGenerator.
Definition at line 817 of file mangen.cpp.
{
}
startInlineMemberDoc() [2/2]
void ManGenerator::startInlineMemberDoc () [virtual]
Implements OutputGenerator.
startInlineMemberName() [1/2]
void ManGenerator::startInlineMemberName () [virtual]
Implements OutputGenerator.
Definition at line 807 of file mangen.cpp.
{
  m_t << "\\fI";
}
References OutputGenerator::m_t.
startInlineMemberName() [2/2]
void ManGenerator::startInlineMemberName () [virtual]
Implements OutputGenerator.
startInlineMemberType() [1/2]
void ManGenerator::startInlineMemberType () [virtual]
Implements OutputGenerator.
Definition at line 798 of file mangen.cpp.
{
}
startInlineMemberType() [2/2]
void ManGenerator::startInlineMemberType () [virtual]
Implements OutputGenerator.
startItemList() [1/2]
void ManGenerator::startItemList () [inline], [virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 68 of file mangen.h.
{}
startItemList() [2/2]
void ManGenerator::startItemList () [inline], [virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 68 of file mangen.h.
{}
startItemListItem() [1/2]
void ManGenerator::startItemListItem () [virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
Definition at line 385 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".TP\n";
  m_firstCol=TRUE;
  m_paragraph=FALSE;
  m_col=0;
}
References FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
Referenced by startConstraintParam(), and startDescTableTitle().
startItemListItem() [2/2]
void ManGenerator::startItemListItem () [virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
startLabels() [1/2]
void ManGenerator::startLabels () [virtual]
Implements OutputGenerator.
Definition at line 829 of file mangen.cpp.
{
}
startLabels() [2/2]
void ManGenerator::startLabels () [virtual]
Implements OutputGenerator.
startMemberDeclaration() [1/2]
void ManGenerator::startMemberDeclaration () [inline], [virtual]
Implements OutputGenerator.
Definition at line 160 of file mangen.h.
{}
startMemberDeclaration() [2/2]
void ManGenerator::startMemberDeclaration () [inline], [virtual]
Implements OutputGenerator.
Definition at line 160 of file mangen.h.
{}
startMemberDescription() [1/2]
void ManGenerator::startMemberDescription (const QCString & , const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 158 of file mangen.h.
{ m_t << "\n.RI \""; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
startMemberDescription() [2/2]
void ManGenerator::startMemberDescription (const QCString & , const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 158 of file mangen.h.
{ m_t << "\n.RI \""; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
startMemberDoc() [1/2]
void ManGenerator::startMemberDoc (const QCString & , const QCString & , const QCString & , const QCString & , int , int , bool) [virtual]
Implements OutputGenerator.
Definition at line 415 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".SS \"";
  m_firstCol=FALSE;
  m_paragraph=FALSE;
}
References FALSE, m_firstCol, m_paragraph, and OutputGenerator::m_t.
startMemberDoc() [2/2]
void ManGenerator::startMemberDoc (const QCString & , const QCString & , const QCString & , const QCString & , int , int , bool) [virtual]
Implements OutputGenerator.
startMemberDocList() [1/2]
void ManGenerator::startMemberDocList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 103 of file mangen.h.
{}
startMemberDocList() [2/2]
void ManGenerator::startMemberDocList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 103 of file mangen.h.
{}
startMemberDocName() [1/2]
void ManGenerator::startMemberDocName (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 220 of file mangen.h.
{}
startMemberDocName() [2/2]
void ManGenerator::startMemberDocName (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 220 of file mangen.h.
{}
startMemberDocPrefixItem() [1/2]
void ManGenerator::startMemberDocPrefixItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 218 of file mangen.h.
{}
startMemberDocPrefixItem() [2/2]
void ManGenerator::startMemberDocPrefixItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 218 of file mangen.h.
{}
startMemberDocSimple() [1/2]
void ManGenerator::startMemberDocSimple (bool isEnum) [virtual]
Implements OutputGenerator.
Definition at line 771 of file mangen.cpp.
{
  if (!m_firstCol)
  {
    m_t << "\n.PP\n";
  }
  m_t << "\\fB";
  if (isEnum)
  {
    docify(theTranslator->trEnumerationValues());
  }
  else
  {
    docify(theTranslator->trCompoundMembers());
  }
  m_t << ":\\fP\n";
  m_t << ".RS 4\n";
}
References docify(), m_firstCol, OutputGenerator::m_t, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberDocSimple() [2/2]
void ManGenerator::startMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
startMemberGroup() [1/2]
void ManGenerator::startMemberGroup () [virtual]
Implements OutputGenerator.
Definition at line 587 of file mangen.cpp.
{
  m_t << "\n.in +1c";
}
References OutputGenerator::m_t.
startMemberGroup() [2/2]
void ManGenerator::startMemberGroup () [virtual]
Implements OutputGenerator.
startMemberGroupDocs() [1/2]
void ManGenerator::startMemberGroupDocs () [virtual]
Implements OutputGenerator.
Definition at line 578 of file mangen.cpp.
{
}
startMemberGroupDocs() [2/2]
void ManGenerator::startMemberGroupDocs () [virtual]
Implements OutputGenerator.
startMemberGroupHeader() [1/2]
void ManGenerator::startMemberGroupHeader (bool) [virtual]
Implements OutputGenerator.
Definition at line 567 of file mangen.cpp.
{
  m_t << "\n.PP\n.RI \"\\fB";
}
References OutputGenerator::m_t.
startMemberGroupHeader() [2/2]
void ManGenerator::startMemberGroupHeader (bool) [virtual]
Implements OutputGenerator.
startMemberHeader() [1/2]
void ManGenerator::startMemberHeader (const QCString & , int) [virtual]
Implements OutputGenerator.
Definition at line 280 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".SS \"";
}
References m_firstCol, and OutputGenerator::m_t.
Referenced by startSection().
startMemberHeader() [2/2]
void ManGenerator::startMemberHeader (const QCString & , int) [virtual]
Implements OutputGenerator.
startMemberItem() [1/2]
void ManGenerator::startMemberItem (const QCString & , int , const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 539 of file mangen.cpp.
{
  if (m_firstCol && !m_insideTabbing) m_t << ".in +1c\n";
  m_t << "\n.ti -1c\n.RI \"";
  m_firstCol=FALSE;
}
References FALSE, m_firstCol, m_insideTabbing, and OutputGenerator::m_t.
startMemberItem() [2/2]
void ManGenerator::startMemberItem (const QCString & , int , const QCString &) [virtual]
Implements OutputGenerator.
startMemberList() [1/2]
void ManGenerator::startMemberList () [virtual]
Implements OutputGenerator.
Definition at line 551 of file mangen.cpp.
{
  if (!m_insideTabbing)
  {
    m_t << "\n.in +1c"; m_firstCol=FALSE;
  }
}
References FALSE, m_firstCol, m_insideTabbing, and OutputGenerator::m_t.
startMemberList() [2/2]
void ManGenerator::startMemberList () [virtual]
Implements OutputGenerator.
startMemberSections() [1/2]
void ManGenerator::startMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 91 of file mangen.h.
{}
startMemberSections() [2/2]
void ManGenerator::startMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 91 of file mangen.h.
{}
startMemberSubtitle() [1/2]
void ManGenerator::startMemberSubtitle () [inline], [virtual]
Implements OutputGenerator.
Definition at line 99 of file mangen.h.
{}
startMemberSubtitle() [2/2]
void ManGenerator::startMemberSubtitle () [inline], [virtual]
Implements OutputGenerator.
Definition at line 99 of file mangen.h.
{}
startMemberTemplateParams() [1/2]
void ManGenerator::startMemberTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 113 of file mangen.h.
{}
startMemberTemplateParams() [2/2]
void ManGenerator::startMemberTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 113 of file mangen.h.
{}
startPageRef() [1/2]
void ManGenerator::startPageRef () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 180 of file mangen.h.
{}
startPageRef() [2/2]
void ManGenerator::startPageRef () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 180 of file mangen.h.
{}
startParagraph() [1/2]
void ManGenerator::startParagraph (const QCString & classDef) [virtual]
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
Definition at line 209 of file mangen.cpp.
{
  if (!m_paragraph)
  {
    if (!m_firstCol) m_t << "\n";
    m_t << ".PP\n";
    m_firstCol=TRUE;
  }
  m_paragraph=TRUE;
}
References m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
startParagraph() [2/2]
void ManGenerator::startParagraph (const QCString & classDef) [virtual]
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
startParameterList() [1/2]
void ManGenerator::startParameterList (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 226 of file mangen.h.
{}
startParameterList() [2/2]
void ManGenerator::startParameterList (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 226 of file mangen.h.
{}
startParameterName() [1/2]
void ManGenerator::startParameterName (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 224 of file mangen.h.
{}
startParameterName() [2/2]
void ManGenerator::startParameterName (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 224 of file mangen.h.
{}
startParameterType() [1/2]
void ManGenerator::startParameterType (bool , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 222 of file mangen.h.
{}
startParameterType() [2/2]
void ManGenerator::startParameterType (bool , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 222 of file mangen.h.
{}
startParamList() [1/2]
void ManGenerator::startParamList (ParamListTypes , const QCString & title) [virtual]
Implements BaseOutputDocInterface.
Definition at line 675 of file mangen.cpp.
{
  if (!m_firstCol)
  { m_t << "\n.PP\n";
    m_firstCol=TRUE; m_paragraph=TRUE;
    m_col=0;
  }
  m_paragraph=FALSE;
  startBold();
  docify(title);
  endBold();
  m_paragraph=TRUE;
}
References docify(), endBold(), FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, startBold(), and TRUE.
startParamList() [2/2]
void ManGenerator::startParamList (ParamListTypes , const QCString & title) [virtual]
Implements BaseOutputDocInterface.
startProjectNumber() [1/2]
void ManGenerator::startProjectNumber () [inline], [virtual]
Implements OutputGenerator.
Definition at line 48 of file mangen.h.
{}
startProjectNumber() [2/2]
void ManGenerator::startProjectNumber () [inline], [virtual]
Implements OutputGenerator.
Definition at line 48 of file mangen.h.
{}
startQuickIndices() [1/2]
void ManGenerator::startQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 182 of file mangen.h.
{}
startQuickIndices() [2/2]
void ManGenerator::startQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 182 of file mangen.h.
{}
startSection() [1/2]
void ManGenerator::startSection (const QCString & , const QCString & , SectionType type) [virtual]
Implements BaseOutputDocInterface.
Definition at line 598 of file mangen.cpp.
{
  if(!m_inHeader)
  {
    switch(type)
    {
      case SectionType::Page: startGroupHeader(FALSE); break;
      case SectionType::Section: startGroupHeader(FALSE); break;
      case SectionType::Subsection: startMemberHeader(QCString(), -1); break;
      case SectionType::Subsubsection: startMemberHeader(QCString(), -1); break;
      case SectionType::Paragraph: startMemberHeader(QCString(), -1); break;
      default: ASSERT(0); break;
    }
  }
}
References ASSERT, FALSE, m_inHeader, Page, Paragraph, Section, startGroupHeader(), startMemberHeader(), Subsection, Subsubsection, and type().
startSection() [2/2]
void ManGenerator::startSection (const QCString & , const QCString & , SectionType) [virtual]
Implements BaseOutputDocInterface.
startSmall() [1/2]
void ManGenerator::startSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 156 of file mangen.h.
{}
startSmall() [2/2]
void ManGenerator::startSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 156 of file mangen.h.
{}
startSubsection() [1/2]
void ManGenerator::startSubsection () [virtual]
Implements BaseOutputDocInterface.
Definition at line 460 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".SS \"";
  m_firstCol=FALSE;
  m_paragraph=FALSE;
}
References FALSE, m_firstCol, m_paragraph, and OutputGenerator::m_t.
startSubsection() [2/2]
void ManGenerator::startSubsection () [virtual]
Implements BaseOutputDocInterface.
startSubsubsection() [1/2]
void ManGenerator::startSubsubsection () [virtual]
Implements BaseOutputDocInterface.
Definition at line 474 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << "\n.SS \"";
  m_firstCol=FALSE;
  m_paragraph=FALSE;
}
References FALSE, m_firstCol, m_paragraph, and OutputGenerator::m_t.
Referenced by startCompoundTemplateParams().
startSubsubsection() [2/2]
void ManGenerator::startSubsubsection () [virtual]
Implements BaseOutputDocInterface.
startTextBlock() [1/2]
void ManGenerator::startTextBlock (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 214 of file mangen.h.
{}
startTextBlock() [2/2]
void ManGenerator::startTextBlock (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 214 of file mangen.h.
{}
startTextLink() [1/2]
void ManGenerator::startTextLink (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 83 of file mangen.h.
{}
startTextLink() [2/2]
void ManGenerator::startTextLink (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 83 of file mangen.h.
{}
startTitle() [1/2]
void ManGenerator::startTitle () [virtual]
Implements BaseOutputDocInterface.
Definition at line 372 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".SH \"";
  m_firstCol=FALSE;
  m_paragraph=FALSE;
}
References FALSE, m_firstCol, m_paragraph, and OutputGenerator::m_t.
startTitle() [2/2]
void ManGenerator::startTitle () [virtual]
Implements BaseOutputDocInterface.
startTitleHead() [1/2]
void ManGenerator::startTitleHead (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 51 of file mangen.h.
{}
startTitleHead() [2/2]
void ManGenerator::startTitleHead (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 51 of file mangen.h.
{}
startTypewriter() [1/2]
void ManGenerator::startTypewriter () [inline], [virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 87 of file mangen.h.
{ m_t << "\\fC"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
startTypewriter() [2/2]
void ManGenerator::startTypewriter () [inline], [virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 87 of file mangen.h.
{ m_t << "\\fC"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
type() [1/2]
OutputType ManGenerator::type () const [inline], [virtual]
Implements OutputGenerator.
Definition at line 33 of file mangen.h.
{ return Man; }
References OutputGenerator::Man.
Referenced by endSection(), and startSection().
type() [2/2]
OutputType ManGenerator::type () const [inline], [virtual]
Implements OutputGenerator.
Definition at line 33 of file mangen.h.
{ return Man; }
References OutputGenerator::Man.
writeAnchor() [1/2]
void ManGenerator::writeAnchor (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 126 of file mangen.h.
{}
writeAnchor() [2/2]
void ManGenerator::writeAnchor (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 126 of file mangen.h.
{}
writeChar() [1/2]
void ManGenerator::writeChar (char c) [virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
Definition at line 347 of file mangen.cpp.
{
  m_firstCol=(c=='\n');
  if (m_firstCol) m_col=0; else m_col++;
  switch (c)
  {
    case '\\': m_t << "\\\\"; break;
  case '\"': c = '\''; // no break!
    default: m_t << c; break;
  }
  //printf("%c",c);fflush(stdout);
  m_paragraph=FALSE;
}
References c, FALSE, m_col, m_firstCol, m_paragraph, and OutputGenerator::m_t.
writeChar() [2/2]
void ManGenerator::writeChar (char c) [virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
writeCodeAnchor() [1/2]
void ManGenerator::writeCodeAnchor (const QCString & name) [inline], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 255 of file mangen.h.
{}
writeCodeAnchor() [2/2]
void ManGenerator::writeCodeAnchor (const QCString & name) [inline], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 255 of file mangen.h.
{}
writeCodeLink() [1/2]
void ManGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 248 of file mangen.cpp.
{
  docify(name);
}
References docify(), and setup::name.
writeCodeLink() [2/2]
void ManGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
writeDoc() [1/2]
void ManGenerator::writeDoc (const IDocNodeAST * ast, const Definition * ctx, const MemberDef * , int) [virtual]
Implements OutputGenerator.
Definition at line 693 of file mangen.cpp.
{
  const DocNodeAST *astImpl = dynamic_cast<const DocNodeAST *>(ast);
  if (astImpl)
  {
    auto visitor { ManDocVisitor(m_t,*this,ctx?ctx->getDefFileExtension():QCString("")) };
    std::visit(visitor,astImpl->root);
  }
  m_firstCol=FALSE;
  m_paragraph = FALSE;
}
References FALSE, Definition::getDefFileExtension(), m_firstCol, m_paragraph, OutputGenerator::m_t, and DocNodeAST::root.
writeDoc() [2/2]
void ManGenerator::writeDoc (const IDocNodeAST * ast, const Definition * , const MemberDef * , int) [virtual]
Implements OutputGenerator.
writeEndAnnoItem() [1/2]
void ManGenerator::writeEndAnnoItem (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 149 of file mangen.h.
{ m_t << "\n"; m_firstCol=TRUE; }
References m_firstCol, OutputGenerator::m_t, and TRUE.
writeEndAnnoItem() [2/2]
void ManGenerator::writeEndAnnoItem (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 149 of file mangen.h.
{ m_t << "\n"; m_firstCol=TRUE; }
References m_firstCol, OutputGenerator::m_t, and TRUE.
writeFooter() [1/2]
void ManGenerator::writeFooter (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 41 of file mangen.h.
{}
writeFooter() [2/2]
void ManGenerator::writeFooter (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 41 of file mangen.h.
{}
writeGraphicalHierarchy() [1/2]
void ManGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 212 of file mangen.h.
{}
writeGraphicalHierarchy() [2/2]
void ManGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 212 of file mangen.h.
{}
writeInheritedSectionTitle() [1/2]
void ManGenerator::writeInheritedSectionTitle (const QCString & , const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 162 of file mangen.h.
                                                                          {}
writeInheritedSectionTitle() [2/2]
void ManGenerator::writeInheritedSectionTitle (const QCString & , const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 162 of file mangen.h.
                                                                          {}
writeLabel() [1/2]
void ManGenerator::writeLabel (const QCString & l, bool isLast) [virtual]
Implements OutputGenerator.
Definition at line 833 of file mangen.cpp.
{
  m_t << "\\fC [" << l << "]\\fP";
  if (!isLast) m_t << ", ";
}
References OutputGenerator::m_t.
writeLabel() [2/2]
void ManGenerator::writeLabel (const QCString & l, bool isLast) [virtual]
Implements OutputGenerator.
writeLatexSpacing() [1/2]
void ManGenerator::writeLatexSpacing () [inline], [virtual]
Implements OutputGenerator.
Definition at line 146 of file mangen.h.
{}
writeLatexSpacing() [2/2]
void ManGenerator::writeLatexSpacing () [inline], [virtual]
Implements OutputGenerator.
Definition at line 146 of file mangen.h.
{}
writeLineNumber() [1/2]
void ManGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [inline], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 129 of file mangen.h.
{ m_t << l << " "; m_col=0; }
References m_col, and OutputGenerator::m_t.
writeLineNumber() [2/2]
void ManGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [inline], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 129 of file mangen.h.
{ m_t << l << " "; m_col=0; }
References m_col, and OutputGenerator::m_t.
writeLogo() [1/2]
void ManGenerator::writeLogo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 186 of file mangen.h.
{}
writeLogo() [2/2]
void ManGenerator::writeLogo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 186 of file mangen.h.
{}
writeNavigationPath() [1/2]
void ManGenerator::writeNavigationPath (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 185 of file mangen.h.
{}
writeNavigationPath() [2/2]
void ManGenerator::writeNavigationPath (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 185 of file mangen.h.
{}
writeNonBreakableSpace() [1/2]
void ManGenerator::writeNonBreakableSpace (int n) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 191 of file mangen.h.
{ int i; for (i=0;i<n;i++) m_t << " "; }
References OutputGenerator::m_t, and n.
writeNonBreakableSpace() [2/2]
void ManGenerator::writeNonBreakableSpace (int n) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 191 of file mangen.h.
{ int i; for (i=0;i<n;i++) m_t << " "; }
References OutputGenerator::m_t, and n.
writeObjectLink() [1/2]
void ManGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
Definition at line 242 of file mangen.cpp.
{
  startBold(); docify(name); endBold();
}
References docify(), endBold(), setup::name, and startBold().
writeObjectLink() [2/2]
void ManGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
writePageLink() [1/2]
void ManGenerator::writePageLink (const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 47 of file mangen.h.
{}
writePageLink() [2/2]
void ManGenerator::writePageLink (const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 47 of file mangen.h.
{}
writeQuickLinks() [1/2]
void ManGenerator::writeQuickLinks (bool , HighlightedItem , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 187 of file mangen.h.
{}
writeQuickLinks() [2/2]
void ManGenerator::writeQuickLinks (bool , HighlightedItem , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 187 of file mangen.h.
{}
writeRuler() [1/2]
void ManGenerator::writeRuler () [inline], [virtual]
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 125 of file mangen.h.
{}
writeRuler() [2/2]
void ManGenerator::writeRuler () [inline], [virtual]
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 125 of file mangen.h.
{}
writeSearchInfo() [1/2]
void ManGenerator::writeSearchInfo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 40 of file mangen.h.
{}
writeSearchInfo() [2/2]
void ManGenerator::writeSearchInfo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 40 of file mangen.h.
{}
writeSplitBar() [1/2]
void ManGenerator::writeSplitBar (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 184 of file mangen.h.
{}
writeSplitBar() [2/2]
void ManGenerator::writeSplitBar (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 184 of file mangen.h.
{}
writeStartAnnoItem() [1/2]
void ManGenerator::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 237 of file mangen.cpp.
{
}
writeStartAnnoItem() [2/2]
void ManGenerator::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) [virtual]
Implements OutputGenerator.
writeString() [1/2]
void ManGenerator::writeString (const QCString & text) [virtual]
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
Definition at line 224 of file mangen.cpp.
{
  docify(text);
}
References docify().
writeString() [2/2]
void ManGenerator::writeString (const QCString & text) [virtual]
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
writeStyleInfo() [1/2]
void ManGenerator::writeStyleInfo (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 50 of file mangen.h.
{}
writeStyleInfo() [2/2]
void ManGenerator::writeStyleInfo (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 50 of file mangen.h.
{}
writeSummaryLink() [1/2]
void ManGenerator::writeSummaryLink (const QCString & , const QCString & , const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 188 of file mangen.h.
{}
writeSummaryLink() [2/2]
void ManGenerator::writeSummaryLink (const QCString & , const QCString & , const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 188 of file mangen.h.
{}
writeSynopsis() [1/2]
void ManGenerator::writeSynopsis () [virtual]
Implements OutputGenerator.
Definition at line 487 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".SH SYNOPSIS\n.br\n.PP\n";
  m_firstCol=TRUE;
  m_paragraph=FALSE;
}
References FALSE, m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
writeSynopsis() [2/2]
void ManGenerator::writeSynopsis () [virtual]
Implements OutputGenerator.
writeTooltip() [1/2]
void ManGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 80 of file mangen.h.
                       {}
writeTooltip() [2/2]
void ManGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 80 of file mangen.h.
                       {}
Member Data Documentation
m_col
int ManGenerator::m_col = 0 [private]
Definition at line 260 of file mangen.h.
Referenced by codify(), docify(), endCodeFragment(), endCodeLine(), startConstraintList(), startDescForItem(), startDescList(), startDescTable(), startExamples(), startItemListItem(), startParamList(), writeChar(), and writeLineNumber().
m_firstCol
bool ManGenerator::m_firstCol = true [private]
Definition at line 258 of file mangen.h.
Referenced by codify(), docify(), endBold(), endCodeFragment(), endConstraintDocs(), endDescItem(), endEmphasis(), endGroupHeader(), endInlineHeader(), endInlineMemberDoc(), endMemberDescription(), endMemberDocSimple(), endMemberGroup(), endMemberGroupHeader(), endMemberHeader(), endMemberList(), endSection(), endTitleHead(), endTypewriter(), newParagraph(), startBold(), startCodeFragment(), startConstraintList(), startDescForItem(), startDescItem(), startDescList(), startDescTable(), startDescTableData(), startEmphasis(), startExamples(), startFile(), startGroupHeader(), startInlineHeader(), startItemListItem(), startMemberDescription(), startMemberDoc(), startMemberDocSimple(), startMemberHeader(), startMemberItem(), startMemberList(), startParagraph(), startParamList(), startSubsection(), startSubsubsection(), startTitle(), startTypewriter(), writeChar(), writeDoc(), writeEndAnnoItem(), and writeSynopsis().
m_inHeader
bool ManGenerator::m_inHeader = false [private]
Definition at line 263 of file mangen.h.
Referenced by endSection(), endTitleHead(), and startSection().
m_insideTabbing
bool ManGenerator::m_insideTabbing = false [private]
Definition at line 262 of file mangen.h.
Referenced by endAnonTypeScope(), endMemberList(), startAnonTypeScope(), startMemberItem(), and startMemberList().
m_paragraph
bool ManGenerator::m_paragraph = true [private]
Definition at line 259 of file mangen.h.
Referenced by codify(), docify(), endCodeFragment(), endGroupHeader(), endMemberHeader(), endSection(), endTitleHead(), newParagraph(), startCodeFragment(), startConstraintList(), startDescForItem(), startDescList(), startDescTable(), startExamples(), startItemListItem(), startMemberDoc(), startParagraph(), startParamList(), startSubsection(), startSubsubsection(), startTitle(), writeChar(), writeDoc(), and writeSynopsis().
m_upperCase
bool ManGenerator::m_upperCase = false [private]
Definition at line 261 of file mangen.h.
Referenced by endGroupHeader(), and startGroupHeader().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/mangen.h
doxygen/src/mangen.h
doxygen/build/doxygen/src/mangen.cpp
doxygen/src/mangen.cpp