TemplateNodeRepeat Class Reference
Class representing a 'for' tag in a template.
Public Member Functions
TemplateNodeRepeat (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
TemplateNodeRepeat (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
Private Attributes
TemplateNodeList m_repeatNodes
ExprAstPtr m_expr
Additional Inherited Members
Detailed Description
Class representing a 'for' tag in a template.
Definition at line 3195 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeRepeat() [1/2]
TemplateNodeRepeat::TemplateNodeRepeat (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3198 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeRepeat>(parser,parent,line)
    {
      TRACE(("{TemplateNodeRepeat(%s)\n",qPrint(data)));
      ExpressionParser expParser(parser,line);
      m_expr = expParser.parse(data);
      StringVector stopAt = { "endrepeat" };
      parser->parse(this,line,stopAt,m_repeatNodes);
      parser->removeNextToken(); // skip over endrepeat
      TRACE(("}TemplateNodeRepeat(%s)\n",qPrint(data)));
    }
References data, m_expr, m_repeatNodes, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), and TRACE.
TemplateNodeRepeat() [2/2]
TemplateNodeRepeat::TemplateNodeRepeat (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3198 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeRepeat>(parser,parent,line)
    {
      TRACE(("{TemplateNodeRepeat(%s)\n",qPrint(data)));
      ExpressionParser expParser(parser,line);
      m_expr = expParser.parse(data);
      StringVector stopAt = { "endrepeat" };
      parser->parse(this,line,stopAt,m_repeatNodes);
      parser->removeNextToken(); // skip over endrepeat
      TRACE(("}TemplateNodeRepeat(%s)\n",qPrint(data)));
    }
References data, m_expr, m_repeatNodes, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), and TRACE.
Member Function Documentation
render() [1/2]
void TemplateNodeRepeat::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3209 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      TemplateVariant v;
      if (m_expr && (v=m_expr->resolve(c)).isInt())
      {
        int i, n = v.toInt();
        for (i=0;i<n;i++)
        {
          TemplateStructPtr s = TemplateStruct::alloc();
          s->set("counter0", i);
          s->set("counter", i+1);
          s->set("revcounter", n-i);
          s->set("revcounter0", n-i-1);
          s->set("first",i==0);
          s->set("last", i==n-1);
          c->set("repeatloop",std::static_pointer_cast<TemplateStructIntf>(s));
          // render all items for this iteration of the loop
          m_repeatNodes.render(ts,c);
        }
      }
      else // simple type...
      {
        ci->warn(m_templateName,m_line,"for requires a variable of list type!");
      }
    }
References TemplateStruct::alloc(), c, m_expr, TemplateNodeCreator< TemplateNodeRepeat >::m_line, m_repeatNodes, TemplateNodeCreator< TemplateNodeRepeat >::m_templateName, n, TemplateNodeList::render(), s, TemplateContextImpl::setLocation(), TemplateVariant::toInt(), and TemplateContextImpl::warn().
render() [2/2]
void TemplateNodeRepeat::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3209 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      TemplateVariant v;
      if (m_expr && (v=m_expr->resolve(c)).isInt())
      {
        int i, n = v.toInt();
        for (i=0;i<n;i++)
        {
          TemplateStructPtr s = TemplateStruct::alloc();
          s->set("counter0", i);
          s->set("counter", i+1);
          s->set("revcounter", n-i);
          s->set("revcounter0", n-i-1);
          s->set("first",i==0);
          s->set("last", i==n-1);
          c->set("repeatloop",std::static_pointer_cast<TemplateStructIntf>(s));
          // render all items for this iteration of the loop
          m_repeatNodes.render(ts,c);
        }
      }
      else // simple type...
      {
        ci->warn(m_templateName,m_line,"for requires a variable of list type!");
      }
    }
References TemplateStruct::alloc(), c, m_expr, TemplateNodeCreator< TemplateNodeRepeat >::m_line, m_repeatNodes, TemplateNodeCreator< TemplateNodeRepeat >::m_templateName, n, TemplateNodeList::render(), s, TemplateContextImpl::setLocation(), TemplateVariant::toInt(), and TemplateContextImpl::warn().
Member Data Documentation
m_expr
ExprAstPtr TemplateNodeRepeat::m_expr [private]
Definition at line 3239 of file template.cpp.
Referenced by render(), and TemplateNodeRepeat().
m_repeatNodes
TemplateNodeList TemplateNodeRepeat::m_repeatNodes [private]
Definition at line 3238 of file template.cpp.
Referenced by render(), and TemplateNodeRepeat().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp