DefinitionImpl Class Reference
#include <definitionimpl.h>
Classes
class IMPL
Public Member Functions
DefinitionImpl (Definition *def, const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~DefinitionImpl ()
QCString name () const
bool isAnonymous () const
QCString localName () const
QCString qualifiedName () const
QCString symbolName () const
QCString getSourceFileBase () const
QCString getSourceAnchor () const
QCString documentation () const
int docLine () const
QCString docFile () const
QCString briefDescription (bool abbreviate=FALSE) const
QCString briefDescriptionAsTooltip () const
int briefLine () const
QCString inbodyDocumentation () const
QCString inbodyFile () const
int inbodyLine () const
QCString briefFile () const
QCString getDefFileName () const
QCString getDefFileExtension () const
int getDefLine () const
int getDefColumn () const
bool hasDocumentation () const
bool hasUserDocumentation () const
bool isVisibleInProject () const
bool isVisible () const
bool isHidden () const
bool isArtificial () const
QCString getReference () const
bool isReference () const
QCString externalReference (const QCString &relPath) const
int getStartDefLine () const
int getStartBodyLine () const
int getEndBodyLine () const
const FileDef * getBodyDef () const
SrcLangExt getLanguage () const
const GroupList & partOfGroups () const
bool isLinkableViaGroup () const
const RefItemVector & xrefListItems () const
const Definition * findInnerCompound (const QCString &name) const
Definition * getOuterScope () const
const MemberVector & getReferencesMembers () const
const MemberVector & getReferencedByMembers () const
bool hasSections () const
bool hasSources () const
bool hasBriefDescription () const
QCString id () const
const SectionRefs & getSectionRefs () const
void setName (const QCString &name)
void setId (const QCString &name)
void setDefFile (const QCString &df, int defLine, int defColumn)
void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)
void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)
void setInbodyDocumentation (const QCString &d, const QCString &docFile, int docLine)
void setReference (const QCString &r)
void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)
void setBodySegment (int defLine, int bls, int ble)
void setBodyDef (const FileDef *fd)
void addSourceReferencedBy (const MemberDef *d)
void addSourceReferences (const MemberDef *d)
void setRefItems (const RefItemVector &sli)
void mergeRefItems (Definition *d)
void mergeReferences (const Definition *other)
void mergeReferencedBy (const Definition *other)
void addInnerCompound (const Definition *d)
void setOuterScope (Definition *d)
void setHidden (bool b)
void setArtificial (bool b)
void setLanguage (SrcLangExt lang)
void writeSourceDef (OutputList &ol, const QCString &scopeName) const
void writeInlineCode (OutputList &ol, const QCString &scopeName) const
bool hasSourceRefs () const
bool hasSourceReffedBy () const
void writeSourceRefs (OutputList &ol, const QCString &scopeName) const
void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const
void makePartOfGroup (const GroupDef *gd)
void writeNavigationPath (OutputList &ol) const
QCString navigationPathAsString () const
void writeQuickMemberLinks (OutputList &, const MemberDef *) const
void writeSummaryLinks (OutputList &) const
QCString pathFragment () const
void writeDocAnchorsToTagFile (TextStream &) const
void setLocalName (const QCString &name)
void addSectionsToIndex ()
void writeToc (OutputList &ol, const LocalToc &lt) const
void computeTooltip ()
void _setSymbolName (const QCString &name)
QCString _symbolName () const
DefinitionImpl (const DefinitionImpl &d)
DefinitionImpl (Definition *def, const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~DefinitionImpl ()
QCString name () const
bool isAnonymous () const
QCString localName () const
QCString qualifiedName () const
QCString symbolName () const
QCString getSourceFileBase () const
QCString getSourceAnchor () const
QCString documentation () const
int docLine () const
QCString docFile () const
QCString briefDescription (bool abbreviate=FALSE) const
QCString briefDescriptionAsTooltip () const
int briefLine () const
QCString inbodyDocumentation () const
QCString inbodyFile () const
int inbodyLine () const
QCString briefFile () const
QCString getDefFileName () const
QCString getDefFileExtension () const
int getDefLine () const
int getDefColumn () const
bool hasDocumentation () const
bool hasUserDocumentation () const
bool isVisibleInProject () const
bool isVisible () const
bool isHidden () const
bool isArtificial () const
QCString getReference () const
bool isReference () const
QCString externalReference (const QCString &relPath) const
int getStartDefLine () const
int getStartBodyLine () const
int getEndBodyLine () const
const FileDef * getBodyDef () const
SrcLangExt getLanguage () const
const GroupList & partOfGroups () const
bool isLinkableViaGroup () const
const RefItemVector & xrefListItems () const
const Definition * findInnerCompound (const QCString &name) const
Definition * getOuterScope () const
const MemberVector & getReferencesMembers () const
const MemberVector & getReferencedByMembers () const
bool hasSections () const
bool hasSources () const
bool hasBriefDescription () const
QCString id () const
const SectionRefs & getSectionRefs () const
void setName (const QCString &name)
void setId (const QCString &name)
void setDefFile (const QCString &df, int defLine, int defColumn)
void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)
void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)
void setInbodyDocumentation (const QCString &d, const QCString &docFile, int docLine)
void setReference (const QCString &r)
void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)
void setBodySegment (int defLine, int bls, int ble)
void setBodyDef (const FileDef *fd)
void addSourceReferencedBy (const MemberDef *d)
void addSourceReferences (const MemberDef *d)
void setRefItems (const RefItemVector &sli)
void mergeRefItems (Definition *d)
void mergeReferences (const Definition *other)
void mergeReferencedBy (const Definition *other)
void addInnerCompound (const Definition *d)
void setOuterScope (Definition *d)
void setHidden (bool b)
void setArtificial (bool b)
void setLanguage (SrcLangExt lang)
void writeSourceDef (OutputList &ol, const QCString &scopeName) const
void writeInlineCode (OutputList &ol, const QCString &scopeName) const
bool hasSourceRefs () const
bool hasSourceReffedBy () const
void writeSourceRefs (OutputList &ol, const QCString &scopeName) const
void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const
void makePartOfGroup (const GroupDef *gd)
void writeNavigationPath (OutputList &ol) const
QCString navigationPathAsString () const
void writeQuickMemberLinks (OutputList &, const MemberDef *) const
void writeSummaryLinks (OutputList &) const
QCString pathFragment () const
void writeDocAnchorsToTagFile (TextStream &) const
void setLocalName (const QCString &name)
void addSectionsToIndex ()
void writeToc (OutputList &ol, const LocalToc &lt) const
void computeTooltip ()
void _setSymbolName (const QCString &name)
QCString _symbolName () const
DefinitionImpl (const DefinitionImpl &d)
Private Member Functions
int _getXRefListId (const QCString &listName) const
void _writeSourceRefList (OutputList &ol, const QCString &scopeName, const QCString &text, const std::unordered_map< std::string, const MemberDef * > &members, bool) const
void _setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)
void _setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace, bool atTop)
void _setInbodyDocumentation (const QCString &d, const QCString &docFile, int docLine)
bool _docsAlreadyAdded (const QCString &doc, QCString &sigList)
int _getXRefListId (const QCString &listName) const
void _writeSourceRefList (OutputList &ol, const QCString &scopeName, const QCString &text, const std::unordered_map< std::string, const MemberDef * > &members, bool) const
void _setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)
void _setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace, bool atTop)
void _setInbodyDocumentation (const QCString &d, const QCString &docFile, int docLine)
bool _docsAlreadyAdded (const QCString &doc, QCString &sigList)
Private Attributes
IMPL * m_impl
Detailed Description
Definition at line 26 of file definitionimpl.h.
Constructor & Destructor Documentation
DefinitionImpl() [1/4]
DefinitionImpl::DefinitionImpl (Definition * def, const QCString & defFileName, int defLine, int defColumn, const QCString & name, const char * b = 0, const char * d = 0, bool isSymbol = TRUE)
Definition at line 225 of file definition.cpp.
{
  m_impl = new DefinitionImpl::IMPL;
  setName(name);
  m_impl->def = def;
  m_impl->defLine = dl;
  m_impl->defColumn = dc;
  m_impl->init(df,name);
  m_impl->isSymbol = isSymbol;
  if (isSymbol) addToMap(name,def);
  _setBriefDescription(b,df,dl);
  _setDocumentation(d,df,dl,TRUE,FALSE);
  if (matchExcludedSymbols(name))
  {
    m_impl->hidden = TRUE;
  }
}
References _setBriefDescription(), _setDocumentation(), addToMap(), b, DefinitionImpl::IMPL::def, DefinitionImpl::IMPL::defColumn, DefinitionImpl::IMPL::defLine, FALSE, DefinitionImpl::IMPL::hidden, DefinitionImpl::IMPL::init(), DefinitionImpl::IMPL::isSymbol, m_impl, matchExcludedSymbols(), name(), setName(), and TRUE.
 DefinitionImpl() [1/2]
DefinitionImpl::~DefinitionImpl () [virtual]
Definition at line 274 of file definition.cpp.
{
  if (m_impl->isSymbol)
  {
    removeFromMap(m_impl->symbolName,m_impl->def);
  }
  delete m_impl;
  m_impl=0;
}
References DefinitionImpl::IMPL::def, DefinitionImpl::IMPL::isSymbol, m_impl, removeFromMap(), and DefinitionImpl::IMPL::symbolName.
DefinitionImpl() [2/4]
DefinitionImpl::DefinitionImpl (const DefinitionImpl & d)
Definition at line 246 of file definition.cpp.
{
  m_impl = new DefinitionImpl::IMPL;
  *m_impl = *d.m_impl;
  m_impl->brief = 0;
  m_impl->details = 0;
  m_impl->body = 0;
  m_impl->inbodyDocs = 0;
  if (d.m_impl->brief)
  {
    m_impl->brief = new BriefInfo(*d.m_impl->brief);
  }
  if (d.m_impl->details)
  {
    m_impl->details = new DocInfo(*d.m_impl->details);
  }
  if (d.m_impl->body)
  {
    m_impl->body = new BodyInfo(*d.m_impl->body);
  }
  if (d.m_impl->inbodyDocs)
  {
    m_impl->inbodyDocs = new DocInfo(*d.m_impl->inbodyDocs);
  }
  if (m_impl->isSymbol) addToMap(m_impl->name,m_impl->def);
}
References addToMap(), DefinitionImpl::IMPL::body, DefinitionImpl::IMPL::brief, DefinitionImpl::IMPL::def, DefinitionImpl::IMPL::details, DefinitionImpl::IMPL::inbodyDocs, DefinitionImpl::IMPL::isSymbol, m_impl, and DefinitionImpl::IMPL::name.
DefinitionImpl() [3/4]
DefinitionImpl::DefinitionImpl (Definition * def, const QCString & defFileName, int defLine, int defColumn, const QCString & name, const char * b = 0, const char * d = 0, bool isSymbol = TRUE)
 DefinitionImpl() [2/2]
virtual DefinitionImpl::~DefinitionImpl () [virtual]
DefinitionImpl() [4/4]
DefinitionImpl::DefinitionImpl (const DefinitionImpl & d)
Member Function Documentation
_docsAlreadyAdded() [1/2]
bool DefinitionImpl::_docsAlreadyAdded (const QCString & doc, QCString & sigList) [private]
Definition at line 418 of file definition.cpp.
{
  uchar md5_sig[16];
  char sigStr[33];
  // to avoid mismatches due to differences in indenting, we first remove
  // double whitespaces...
  QCString docStr = doc.simplifyWhiteSpace();
  MD5Buffer(docStr.data(),docStr.length(),md5_sig);
  MD5SigToString(md5_sig,sigStr);
  //printf("%s:_docsAlreadyAdded doc='%s' sig='%s' docSigs='%s'\n",
  // qPrint(name()),qPrint(doc),qPrint(sigStr),qPrint(sigList));
  if (sigList.find(sigStr)==-1) // new docs, add signature to prevent re-adding it
  {
    sigList+=QCString(":")+sigStr;
    return FALSE;
  }
  else
  {
    return TRUE;
  }
}
References QCString::data(), FALSE, QCString::find(), QCString::length(), MD5Buffer(), MD5SigToString(), QCString::simplifyWhiteSpace(), and TRUE.
Referenced by _setBriefDescription(), and _setDocumentation().
_docsAlreadyAdded() [2/2]
bool DefinitionImpl::_docsAlreadyAdded (const QCString & doc, QCString & sigList) [private]
_getXRefListId() [1/2]
int DefinitionImpl::_getXRefListId (const QCString & listName) const [private]
Definition at line 1284 of file definition.cpp.
{
  for (const RefItem *item : m_impl->xrefListItems)
  {
    if (item->list()->listName()==listName)
    {
      return item->id();
    }
  }
  return -1;
}
References RefItem::id(), RefItem::list(), RefList::listName(), m_impl, and DefinitionImpl::IMPL::xrefListItems.
_getXRefListId() [2/2]
int DefinitionImpl::_getXRefListId (const QCString & listName) const [private]
_setBriefDescription() [1/2]
void DefinitionImpl::_setBriefDescription (const QCString & b, const QCString & briefFile, int briefLine) [private]
Definition at line 492 of file definition.cpp.
{
  QCString brief = b;
  brief = brief.stripWhiteSpace();
  brief = stripLeadingAndTrailingEmptyLines(brief,briefLine);
  brief = brief.stripWhiteSpace();
  if (brief.isEmpty()) return;
  uint bl = brief.length();
  if (bl>0)
  {
    if (!theTranslator || theTranslator->needsPunctuation()) // add punctuation if needed
    {
      int c = brief.at(bl-1);
      switch(c)
      {
        case '.': case '!': case '?': case '>': case ':': case ')': break;
        default:
          if (isUTF8CharUpperCase(brief.str(),0) && !lastUTF8CharIsMultibyte(brief.str())) brief+='.';
          break;
      }
    }
  }
  if (!_docsAlreadyAdded(brief,m_impl->briefSignatures))
  {
    if (m_impl->brief && !m_impl->brief->doc.isEmpty())
    {
       //printf("adding to details\n");
       _setDocumentation(brief,briefFile,briefLine,FALSE,TRUE);
    }
    else
    {
      //fprintf(stderr,"DefinitionImpl::setBriefDescription(%s,%s,%d)\n",b,briefFile,briefLine);
      if (m_impl->brief==0)
      {
        m_impl->brief = new BriefInfo;
      }
      m_impl->brief->doc=brief;
      if (briefLine!=-1)
      {
        m_impl->brief->file = briefFile;
        m_impl->brief->line = briefLine;
      }
      else
      {
        m_impl->brief->file = briefFile;
        m_impl->brief->line = 1;
      }
    }
  }
  else
  {
    //printf("do nothing!\n");
  }
}
References _docsAlreadyAdded(), _setDocumentation(), QCString::at(), b, DefinitionImpl::IMPL::brief, briefFile(), briefLine(), DefinitionImpl::IMPL::briefSignatures, c, BriefInfo::doc, FALSE, BriefInfo::file, QCString::isEmpty(), isUTF8CharUpperCase(), lastUTF8CharIsMultibyte(), QCString::length(), BriefInfo::line, m_impl, Translator::needsPunctuation(), QCString::str(), stripLeadingAndTrailingEmptyLines(), QCString::stripWhiteSpace(), theTranslator, and TRUE.
Referenced by DefinitionImpl(), and setBriefDescription().
_setBriefDescription() [2/2]
void DefinitionImpl::_setBriefDescription (const QCString & b, const QCString & briefFile, int briefLine) [private]
_setDocumentation() [1/2]
void DefinitionImpl::_setDocumentation (const QCString & d, const QCString & docFile, int docLine, bool stripWhiteSpace, bool atTop) [private]
Definition at line 440 of file definition.cpp.
{
  //printf("%s::setDocumentation(%s,%s,%d,%d)\n",qPrint(name()),d,docFile,docLine,stripWhiteSpace);
  if (d.isEmpty()) return;
  QCString doc = d;
  if (stripWhiteSpace)
  {
    doc = stripLeadingAndTrailingEmptyLines(doc,docLine);
  }
  else // don't strip whitespace
  {
    doc=d;
  }
  if (!_docsAlreadyAdded(doc,m_impl->docSignatures))
  {
    //printf("setting docs for %s: '%s'\n",qPrint(name()),qPrint(m_doc));
    if (m_impl->details==0)
    {
      m_impl->details = new DocInfo;
    }
    if (m_impl->details->doc.isEmpty()) // fresh detailed description
    {
      m_impl->details->doc = doc;
    }
    else if (atTop) // another detailed description, append it to the start
    {
      m_impl->details->doc = doc+"\n\n"+m_impl->details->doc;
    }
    else // another detailed description, append it to the end
    {
      m_impl->details->doc += "\n\n"+doc;
    }
    if (docLine!=-1) // store location if valid
    {
      m_impl->details->file = docFile;
      m_impl->details->line = docLine;
    }
    else
    {
      m_impl->details->file = docFile;
      m_impl->details->line = 1;
    }
  }
}
References _docsAlreadyAdded(), DefinitionImpl::IMPL::details, DocInfo::doc, docFile(), docLine(), DefinitionImpl::IMPL::docSignatures, DocInfo::file, QCString::isEmpty(), DocInfo::line, m_impl, and stripLeadingAndTrailingEmptyLines().
Referenced by _setBriefDescription(), DefinitionImpl(), and setDocumentation().
_setDocumentation() [2/2]
void DefinitionImpl::_setDocumentation (const QCString & d, const QCString & docFile, int docLine, bool stripWhiteSpace, bool atTop) [private]
_setInbodyDocumentation() [1/2]
void DefinitionImpl::_setInbodyDocumentation (const QCString & d, const QCString & docFile, int docLine) [private]
Definition at line 554 of file definition.cpp.
{
  if (m_impl->inbodyDocs==0)
  {
    m_impl->inbodyDocs = new DocInfo;
  }
  if (m_impl->inbodyDocs->doc.isEmpty()) // fresh inbody docs
  {
    m_impl->inbodyDocs->doc = doc;
    m_impl->inbodyDocs->file = inbodyFile;
    m_impl->inbodyDocs->line = inbodyLine;
  }
  else // another inbody documentation fragment, append this to the end
  {
    m_impl->inbodyDocs->doc += QCString("\n\n")+doc;
  }
}
References DocInfo::doc, DocInfo::file, DefinitionImpl::IMPL::inbodyDocs, inbodyFile(), inbodyLine(), QCString::isEmpty(), DocInfo::line, and m_impl.
Referenced by setInbodyDocumentation().
_setInbodyDocumentation() [2/2]
void DefinitionImpl::_setInbodyDocumentation (const QCString & d, const QCString & docFile, int docLine) [private]
_setSymbolName() [1/2]
void DefinitionImpl::_setSymbolName (const QCString & name)
Definition at line 1842 of file definition.cpp.
{
  m_impl->symbolName=name;
}
References m_impl, name(), and DefinitionImpl::IMPL::symbolName.
Referenced by DefinitionMixin< Base >::_setSymbolName().
_setSymbolName() [2/2]
void DefinitionImpl::_setSymbolName (const QCString & name)
_symbolName() [1/2]
QCString DefinitionImpl::_symbolName () const
Definition at line 1847 of file definition.cpp.
{
  return m_impl->symbolName;
}
References m_impl, and DefinitionImpl::IMPL::symbolName.
Referenced by DefinitionMixin< Base >::_symbolName().
_symbolName() [2/2]
QCString DefinitionImpl::_symbolName () const
_writeSourceRefList() [1/2]
void DefinitionImpl::_writeSourceRefList (OutputList & ol, const QCString & scopeName, const QCString & text, const std::unordered_map< std::string, const MemberDef * > & membersMap, bool) const [private]
Write a reference to the source code fragments in which this definition is used.
Definition at line 1029 of file definition.cpp.
{
  if (!membersMap.empty())
  {
    auto members = refMapToVector(membersMap);
    auto replaceFunc = [this,&members,scopeName,&ol](size_t entryIndex)
    {
      bool sourceBrowser = Config_getBool(SOURCE_BROWSER);
      bool refLinkSource = Config_getBool(REFERENCES_LINK_SOURCE);
      const MemberDef *md=members[entryIndex];
      if (md)
      {
        QCString scope=md->getScopeString();
        QCString name=md->name();
        //printf("class=%p scope=%s scopeName=%s\n",md->getClassDef(),qPrint(scope),scopeName);
        if (!scope.isEmpty() && scope!=scopeName)
        {
          name.prepend(scope+getLanguageSpecificSeparator(m_impl->lang));
        }
        if (!md->isObjCMethod() &&
            (md->isFunction() || md->isSlot() ||
             md->isPrototype() || md->isSignal()
            )
           )
        {
          name+="()";
        }
        if (sourceBrowser &&
            !(md->isLinkable() && !refLinkSource) &&
            md->getStartBodyLine()!=-1 &&
            md->getBodyDef()
           )
        {
          const int maxLineNrStr = 10;
          char anchorStr[maxLineNrStr];
          qsnprintf(anchorStr,maxLineNrStr,"l%05d",md->getStartBodyLine());
          //printf("Write object link to %s\n",qPrint(md->getBodyDef()->getSourceFileBase()));
          ol.writeObjectLink(QCString(),md->getBodyDef()->getSourceFileBase(),anchorStr,name);
        }
        else if (md->isLinkable())
        {
          ol.writeObjectLink(md->getReference(),
              md->getOutputFileBase(),
              md->anchor(),name);
        }
        else
        {
          ol.docify(name);
        }
      }
    };
    ol.startParagraph("reference");
    ol.parseText(text);
    ol.docify(" ");
    writeMarkerList(ol,
                    theTranslator->trWriteList(static_cast<int>(members.size())).str(),
                    members.size(),
                    replaceFunc);
    ol.writeString(".");
    ol.endParagraph();
  }
}
References MemberDef::anchor(), Config_getBool, OutputList::docify(), OutputList::endParagraph(), Definition::getBodyDef(), getLanguageSpecificSeparator(), MemberDef::getOutputFileBase(), MemberDef::getReference(), MemberDef::getScopeString(), FileDef::getSourceFileBase(), Definition::getStartBodyLine(), QCString::isEmpty(), MemberDef::isFunction(), MemberDef::isLinkable(), MemberDef::isObjCMethod(), MemberDef::isPrototype(), MemberDef::isSignal(), MemberDef::isSlot(), DefinitionImpl::IMPL::lang, m_impl, name(), Definition::name(), OutputList::parseText(), QCString::prepend(), qsnprintf, refMapToVector(), OutputList::startParagraph(), QCString::str(), theTranslator, Translator::trWriteList(), writeMarkerList(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by writeSourceReffedBy(), and writeSourceRefs().
_writeSourceRefList() [2/2]
void DefinitionImpl::_writeSourceRefList (OutputList & ol, const QCString & scopeName, const QCString & text, const std::unordered_map< std::string, const MemberDef * > & members, bool) const [private]
addInnerCompound() [1/2]
void DefinitionImpl::addInnerCompound (const Definition * d)
Definition at line 1179 of file definition.cpp.
{
  err("DefinitionImpl::addInnerCompound() called\n");
}
References err().
Referenced by DefinitionMixin< Base >::addInnerCompound().
addInnerCompound() [2/2]
void DefinitionImpl::addInnerCompound (const Definition * d)
addSectionsToDefinition() [1/2]
void DefinitionImpl::addSectionsToDefinition (const std::vector< const SectionInfo * > & anchorList)
Definition at line 309 of file definition.cpp.
{
  //printf("%s: addSectionsToDefinition(%d)\n",qPrint(name()),anchorList->count());
  for (const SectionInfo *si : anchorList)
  {
    //printf("Add section '%s' to definition '%s'\n",
    // qPrint(si->label()),qPrint(name()));
    SectionManager &sm = SectionManager::instance();
    SectionInfo *gsi=sm.find(si->label());
    //printf("===== label=%s gsi=%p\n",qPrint(si->label),gsi);
    if (gsi==0)
    {
      gsi = sm.add(*si);
    }
    if (m_impl->sectionRefs.find(gsi->label())==0)
    {
      m_impl->sectionRefs.add(gsi);
      gsi->setDefinition(m_impl->def);
    }
  }
}
References SectionManager::add(), SectionRefs::add(), DefinitionImpl::IMPL::def, SectionRefs::find(), LinkedMap< T, Hash, KeyEqual, Map >::find(), SectionManager::instance(), SectionInfo::label(), m_impl, DefinitionImpl::IMPL::sectionRefs, and SectionInfo::setDefinition().
Referenced by DefinitionMixin< Base >::addSectionsToDefinition().
addSectionsToDefinition() [2/2]
void DefinitionImpl::addSectionsToDefinition (const std::vector< const SectionInfo * > & anchorList)
addSectionsToIndex() [1/2]
void DefinitionImpl::addSectionsToIndex ()
Definition at line 346 of file definition.cpp.
{
  if (m_impl->sectionRefs.empty()) return;
  //printf("DefinitionImpl::addSectionsToIndex()\n");
  int level=1;
  for (auto it = m_impl->sectionRefs.begin(); it!=m_impl->sectionRefs.end(); ++it)
  {
    const SectionInfo *si = *it;
    SectionType type = si->type();
    if (isSection(type))
    {
      //printf(" level=%d title=%s\n",level,qPrint(si->title));
      int nextLevel = static_cast<int>(type);
      int i;
      if (nextLevel>level)
      {
        for (i=level;i<nextLevel;i++)
        {
          Doxygen::indexList->incContentsDepth();
        }
      }
      else if (nextLevel<level)
      {
        for (i=nextLevel;i<level;i++)
        {
          Doxygen::indexList->decContentsDepth();
        }
      }
      QCString title = si->title();
      if (title.isEmpty()) title = si->label();
      // determine if there is a next level inside this item, but be aware of the anchor and table section references.
      auto it_next = std::next(it);
      bool isDir = (it_next!=m_impl->sectionRefs.end()) ?
                       (isSection((*it_next)->type()) && static_cast<int>((*it_next)->type()) > nextLevel) : FALSE;
      Doxygen::indexList->addContentsItem(isDir,title,
                                         getReference(),
                                         m_impl->def->getOutputFileBase(),
                                         si->label(),
                                         FALSE,
                                         TRUE);
      level = nextLevel;
    }
  }
  while (level>1)
  {
    Doxygen::indexList->decContentsDepth();
    level--;
  }
}
References IndexList::addContentsItem(), SectionRefs::begin(), IndexList::decContentsDepth(), DefinitionImpl::IMPL::def, SectionRefs::empty(), SectionRefs::end(), FALSE, Definition::getOutputFileBase(), getReference(), IndexList::incContentsDepth(), Doxygen::indexList, QCString::isEmpty(), isSection(), SectionInfo::label(), level, m_impl, DefinitionImpl::IMPL::sectionRefs, SectionInfo::title(), TRUE, and SectionInfo::type().
Referenced by DefinitionMixin< Base >::addSectionsToIndex().
addSectionsToIndex() [2/2]
void DefinitionImpl::addSectionsToIndex ()
addSourceReferencedBy() [1/2]
void DefinitionImpl::addSourceReferencedBy (const MemberDef * d)
Definition at line 1142 of file definition.cpp.
{
  if (md)
  {
    QCString name = md->name();
    QCString scope = md->getScopeString();
    if (!scope.isEmpty())
    {
      name.prepend(scope+"::");
    }
    m_impl->sourceRefByDict.insert({name.str(),md});
  }
}
References MemberDef::getScopeString(), QCString::isEmpty(), m_impl, name(), Definition::name(), QCString::prepend(), DefinitionImpl::IMPL::sourceRefByDict, and QCString::str().
Referenced by DefinitionMixin< Base >::addSourceReferencedBy().
addSourceReferencedBy() [2/2]
void DefinitionImpl::addSourceReferencedBy (const MemberDef * d)
addSourceReferences() [1/2]
void DefinitionImpl::addSourceReferences (const MemberDef * d)
Definition at line 1158 of file definition.cpp.
{
  if (md)
  {
    QCString name = md->name();
    QCString scope = md->getScopeString();
    if (!scope.isEmpty())
    {
      name.prepend(scope+"::");
    }
    m_impl->sourceRefsDict.insert({name.str(),md});
  }
}
References MemberDef::getScopeString(), QCString::isEmpty(), m_impl, name(), Definition::name(), QCString::prepend(), DefinitionImpl::IMPL::sourceRefsDict, and QCString::str().
Referenced by DefinitionMixin< Base >::addSourceReferences().
addSourceReferences() [2/2]
void DefinitionImpl::addSourceReferences (const MemberDef * d)
briefDescription() [1/2]
QCString DefinitionImpl::briefDescription (bool abbreviate = FALSE) const
Definition at line 1627 of file definition.cpp.
{
  //printf("%s::briefDescription(%d)='%s'\n",qPrint(name()),abbr,m_impl->brief?qPrint(m_impl->brief->doc):"<none>");
  return m_impl->brief ?
         (abbr ? abbreviate(m_impl->brief->doc,m_impl->def->displayName()) : m_impl->brief->doc) :
         QCString("");
}
References abbreviate(), DefinitionImpl::IMPL::brief, DefinitionImpl::IMPL::def, Definition::displayName(), BriefInfo::doc, and m_impl.
Referenced by DefinitionMixin< Base >::briefDescription(), and hasBriefDescription().
briefDescription() [2/2]
QCString DefinitionImpl::briefDescription (bool abbreviate = FALSE) const
briefDescriptionAsTooltip() [1/2]
QCString DefinitionImpl::briefDescriptionAsTooltip () const
Definition at line 1646 of file definition.cpp.
{
  return m_impl->brief ? m_impl->brief->tooltip : QCString();
}
References DefinitionImpl::IMPL::brief, m_impl, and BriefInfo::tooltip.
Referenced by DefinitionMixin< Base >::briefDescriptionAsTooltip().
briefDescriptionAsTooltip() [2/2]
QCString DefinitionImpl::briefDescriptionAsTooltip () const
briefFile() [1/2]
QCString DefinitionImpl::briefFile () const
Definition at line 1656 of file definition.cpp.
{
  return m_impl->brief ? m_impl->brief->file : QCString("<"+m_impl->name+">");
}
References DefinitionImpl::IMPL::brief, BriefInfo::file, m_impl, and DefinitionImpl::IMPL::name.
Referenced by _setBriefDescription(), DefinitionMixin< Base >::briefFile(), and setBriefDescription().
briefFile() [2/2]
QCString DefinitionImpl::briefFile () const
briefLine() [1/2]
int DefinitionImpl::briefLine () const
Definition at line 1651 of file definition.cpp.
{
  return m_impl->brief ? m_impl->brief->line : 1;
}
References DefinitionImpl::IMPL::brief, BriefInfo::line, and m_impl.
Referenced by _setBriefDescription(), DefinitionMixin< Base >::briefLine(), and setBriefDescription().
briefLine() [2/2]
int DefinitionImpl::briefLine () const
computeTooltip() [1/2]
void DefinitionImpl::computeTooltip ()
Definition at line 1635 of file definition.cpp.
{
  if (m_impl->brief && m_impl->brief->tooltip.isEmpty() && !m_impl->brief->doc.isEmpty())
  {
    const MemberDef *md = m_impl->def->definitionType()==Definition::TypeMember ? toMemberDef(m_impl->def) : 0;
    const Definition *scope = m_impl->def->definitionType()==Definition::TypeMember ? m_impl->def->getOuterScope() : m_impl->def;
    m_impl->brief->tooltip = parseCommentAsText(scope,md,
                                m_impl->brief->doc, m_impl->brief->file, m_impl->brief->line);
  }
}
References DefinitionImpl::IMPL::brief, DefinitionImpl::IMPL::def, Definition::definitionType(), BriefInfo::doc, BriefInfo::file, Definition::getOuterScope(), QCString::isEmpty(), BriefInfo::line, m_impl, parseCommentAsText(), toMemberDef(), BriefInfo::tooltip, and Definition::TypeMember.
Referenced by DefinitionMixin< Base >::computeTooltip().
computeTooltip() [2/2]
void DefinitionImpl::computeTooltip ()
docFile() [1/2]
QCString DefinitionImpl::docFile () const
Definition at line 1574 of file definition.cpp.
{
  return m_impl->details ? m_impl->details->file : m_impl->brief ? m_impl->brief->file : QCString("<"+m_impl->name+">");
}
References DefinitionImpl::IMPL::brief, DefinitionImpl::IMPL::details, DocInfo::file, BriefInfo::file, m_impl, and DefinitionImpl::IMPL::name.
Referenced by _setDocumentation(), DefinitionMixin< Base >::docFile(), and setDocumentation().
docFile() [2/2]
QCString DefinitionImpl::docFile () const
docLine() [1/2]
int DefinitionImpl::docLine () const
Definition at line 1569 of file definition.cpp.
{
  return m_impl->details ? m_impl->details->line : m_impl->brief ? m_impl->brief->line : 1;
}
References DefinitionImpl::IMPL::brief, DefinitionImpl::IMPL::details, DocInfo::line, BriefInfo::line, and m_impl.
Referenced by _setDocumentation(), DefinitionMixin< Base >::docLine(), and setDocumentation().
docLine() [2/2]
int DefinitionImpl::docLine () const
documentation() [1/2]
QCString DefinitionImpl::documentation () const
Definition at line 1564 of file definition.cpp.
{
  return m_impl->details ? m_impl->details->doc : QCString("");
}
References DefinitionImpl::IMPL::details, DocInfo::doc, and m_impl.
Referenced by DefinitionMixin< Base >::documentation().
documentation() [2/2]
QCString DefinitionImpl::documentation () const
externalReference() [1/2]
QCString DefinitionImpl::externalReference (const QCString & relPath) const
Definition at line 1858 of file definition.cpp.
{
  QCString ref = getReference();
  if (!ref.isEmpty())
  {
    auto it = Doxygen::tagDestinationMap.find(ref.str());
    if (it!=Doxygen::tagDestinationMap.end())
    {
      QCString result(it->second);
      uint l = result.length();
      if (!relPath.isEmpty() && l>0 && result.at(0)=='.')
      { // relative path -> prepend relPath.
        result.prepend(relPath);
        l+=relPath.length();
      }
      if (l>0 && result.at(l-1)!='/') result+='/';
      return result;
    }
  }
  return relPath;
}
References QCString::at(), ghc::filesystem::end(), getReference(), QCString::isEmpty(), QCString::length(), QCString::prepend(), QCString::str(), and Doxygen::tagDestinationMap.
Referenced by DefinitionMixin< Base >::externalReference().
externalReference() [2/2]
QCString DefinitionImpl::externalReference (const QCString & relPath) const
findInnerCompound() [1/2]
const Definition * DefinitionImpl::findInnerCompound (const QCString & name) const
Definition at line 1174 of file definition.cpp.
{
  return 0;
}
Referenced by DefinitionMixin< Base >::findInnerCompound().
findInnerCompound() [2/2]
const Definition * DefinitionImpl::findInnerCompound (const QCString & name) const
getBodyDef() [1/2]
const FileDef * DefinitionImpl::getBodyDef () const
Definition at line 1736 of file definition.cpp.
{
  return m_impl->body ? m_impl->body->fileDef : 0;
}
References DefinitionImpl::IMPL::body, BodyInfo::fileDef, and m_impl.
Referenced by DefinitionMixin< Base >::getBodyDef().
getBodyDef() [2/2]
const FileDef * DefinitionImpl::getBodyDef () const
getDefColumn() [1/2]
int DefinitionImpl::getDefColumn () const
Definition at line 1895 of file definition.cpp.
{
  return m_impl->defColumn;
}
References DefinitionImpl::IMPL::defColumn, and m_impl.
Referenced by DefinitionMixin< Base >::getDefColumn().
getDefColumn() [2/2]
int DefinitionImpl::getDefColumn () const
getDefFileExtension() [1/2]
QCString DefinitionImpl::getDefFileExtension () const
Definition at line 1686 of file definition.cpp.
{
  return m_impl->defFileExt;
}
References DefinitionImpl::IMPL::defFileExt, and m_impl.
Referenced by DefinitionMixin< Base >::getDefFileExtension().
getDefFileExtension() [2/2]
QCString DefinitionImpl::getDefFileExtension () const
getDefFileName() [1/2]
QCString DefinitionImpl::getDefFileName () const
Definition at line 1681 of file definition.cpp.
{
  return m_impl->defFileName;
}
References DefinitionImpl::IMPL::defFileName, and m_impl.
Referenced by DefinitionMixin< Base >::getDefFileName().
getDefFileName() [2/2]
QCString DefinitionImpl::getDefFileName () const
getDefLine() [1/2]
int DefinitionImpl::getDefLine () const
Definition at line 1890 of file definition.cpp.
{
  return m_impl->defLine;
}
References DefinitionImpl::IMPL::defLine, and m_impl.
Referenced by DefinitionMixin< Base >::getDefLine().
getDefLine() [2/2]
int DefinitionImpl::getDefLine () const
getEndBodyLine() [1/2]
int DefinitionImpl::getEndBodyLine () const
Definition at line 1731 of file definition.cpp.
{
  return m_impl->body ? m_impl->body->endLine : -1;
}
References DefinitionImpl::IMPL::body, BodyInfo::endLine, and m_impl.
Referenced by DefinitionMixin< Base >::getEndBodyLine().
getEndBodyLine() [2/2]
int DefinitionImpl::getEndBodyLine () const
getLanguage() [1/2]
SrcLangExt DefinitionImpl::getLanguage () const
Definition at line 1816 of file definition.cpp.
{
  return m_impl->lang;
}
References DefinitionImpl::IMPL::lang, and m_impl.
Referenced by DefinitionMixin< Base >::getLanguage(), and qualifiedName().
getLanguage() [2/2]
SrcLangExt DefinitionImpl::getLanguage () const
getOuterScope() [1/2]
Definition * DefinitionImpl::getOuterScope () const
Definition at line 1755 of file definition.cpp.
{
  return m_impl->outerScope;
}
References m_impl, and DefinitionImpl::IMPL::outerScope.
Referenced by DefinitionMixin< Base >::getOuterScope(), and navigationPathAsString().
getOuterScope() [2/2]
Definition * DefinitionImpl::getOuterScope () const
getReference() [1/2]
QCString DefinitionImpl::getReference () const
Definition at line 1711 of file definition.cpp.
{
  return m_impl->ref;
}
References m_impl, and DefinitionImpl::IMPL::ref.
Referenced by addSectionsToIndex(), externalReference(), and DefinitionMixin< Base >::getReference().
getReference() [2/2]
QCString DefinitionImpl::getReference () const
getReferencedByMembers() [1/2]
const MemberVector & DefinitionImpl::getReferencedByMembers () const
Definition at line 1769 of file definition.cpp.
{
  if (m_impl->referencedByMembers.empty() && !m_impl->sourceRefByDict.empty())
  {
    m_impl->referencedByMembers = refMapToVector(m_impl->sourceRefByDict);
  }
  return m_impl->referencedByMembers;
}
References MemberVector::empty(), m_impl, DefinitionImpl::IMPL::referencedByMembers, refMapToVector(), and DefinitionImpl::IMPL::sourceRefByDict.
Referenced by DefinitionMixin< Base >::getReferencedByMembers().
getReferencedByMembers() [2/2]
const MemberVector & DefinitionImpl::getReferencedByMembers () const
getReferencesMembers() [1/2]
const MemberVector & DefinitionImpl::getReferencesMembers () const
Definition at line 1760 of file definition.cpp.
{
  if (m_impl->referencesMembers.empty() && !m_impl->sourceRefsDict.empty())
  {
    m_impl->referencesMembers = refMapToVector(m_impl->sourceRefsDict);
  }
  return m_impl->referencesMembers;
}
References MemberVector::empty(), m_impl, DefinitionImpl::IMPL::referencesMembers, refMapToVector(), and DefinitionImpl::IMPL::sourceRefsDict.
Referenced by DefinitionMixin< Base >::getReferencesMembers().
getReferencesMembers() [2/2]
const MemberVector & DefinitionImpl::getReferencesMembers () const
getSectionRefs() [1/2]
const SectionRefs & DefinitionImpl::getSectionRefs () const
Definition at line 1552 of file definition.cpp.
{
  return m_impl->sectionRefs;
}
References m_impl, and DefinitionImpl::IMPL::sectionRefs.
Referenced by DefinitionMixin< Base >::getSectionRefs().
getSectionRefs() [2/2]
const SectionRefs & DefinitionImpl::getSectionRefs () const
getSourceAnchor() [1/2]
QCString DefinitionImpl::getSourceAnchor () const
Definition at line 874 of file definition.cpp.
{
  const int maxAnchorStrLen = 20;
  char anchorStr[maxAnchorStrLen];
  anchorStr[0]='\0';
  if (m_impl->body && m_impl->body->startLine!=-1)
  {
    if (Htags::useHtags)
    {
      qsnprintf(anchorStr,maxAnchorStrLen,"L%d",m_impl->body->defLine);
    }
    else
    {
      qsnprintf(anchorStr,maxAnchorStrLen,"l%05d",m_impl->body->defLine);
    }
  }
  return anchorStr;
}
References DefinitionImpl::IMPL::body, BodyInfo::defLine, m_impl, qsnprintf, BodyInfo::startLine, and Htags::useHtags.
Referenced by DefinitionMixin< Base >::getSourceAnchor(), and writeSourceDef().
getSourceAnchor() [2/2]
QCString DefinitionImpl::getSourceAnchor () const
getSourceFileBase() [1/2]
QCString DefinitionImpl::getSourceFileBase () const
Definition at line 861 of file definition.cpp.
{
  ASSERT(m_impl->def->definitionType()!=Definition::TypeFile); // file overloads this method
  QCString fn;
  bool sourceBrowser = Config_getBool(SOURCE_BROWSER);
  if (sourceBrowser &&
      m_impl->body && m_impl->body->startLine!=-1 && m_impl->body->fileDef)
  {
    fn = m_impl->body->fileDef->getSourceFileBase();
  }
  return fn;
}
References ASSERT, DefinitionImpl::IMPL::body, Config_getBool, DefinitionImpl::IMPL::def, Definition::definitionType(), BodyInfo::fileDef, FileDef::getSourceFileBase(), m_impl, BodyInfo::startLine, and Definition::TypeFile.
Referenced by DefinitionMixin< Base >::getSourceFileBase(), and writeSourceDef().
getSourceFileBase() [2/2]
QCString DefinitionImpl::getSourceFileBase () const
getStartBodyLine() [1/2]
int DefinitionImpl::getStartBodyLine () const
Definition at line 1726 of file definition.cpp.
{
  return m_impl->body ? m_impl->body->startLine : -1;
}
References DefinitionImpl::IMPL::body, m_impl, and BodyInfo::startLine.
Referenced by DefinitionMixin< Base >::getStartBodyLine().
getStartBodyLine() [2/2]
int DefinitionImpl::getStartBodyLine () const
getStartDefLine() [1/2]
int DefinitionImpl::getStartDefLine () const
Definition at line 1721 of file definition.cpp.
{
  return m_impl->body ? m_impl->body->defLine : -1;
}
References DefinitionImpl::IMPL::body, BodyInfo::defLine, and m_impl.
Referenced by DefinitionMixin< Base >::getStartDefLine().
getStartDefLine() [2/2]
int DefinitionImpl::getStartDefLine () const
hasBriefDescription() [1/2]
bool DefinitionImpl::hasBriefDescription () const
Definition at line 1852 of file definition.cpp.
{
  bool briefMemberDesc = Config_getBool(BRIEF_MEMBER_DESC);
  return !briefDescription().isEmpty() && briefMemberDesc;
}
References briefDescription(), Config_getBool, and QCString::isEmpty().
Referenced by DefinitionMixin< Base >::hasBriefDescription().
hasBriefDescription() [2/2]
bool DefinitionImpl::hasBriefDescription () const
hasDocumentation() [1/2]
bool DefinitionImpl::hasDocumentation () const
Definition at line 1117 of file definition.cpp.
{
  bool extractAll = Config_getBool(EXTRACT_ALL);
  //bool sourceBrowser = Config_getBool(SOURCE_BROWSER);
  bool hasDocs =
         (m_impl->details && !m_impl->details->doc.isEmpty()) || // has detailed docs
         (m_impl->brief && !m_impl->brief->doc.isEmpty()) || // has brief description
         (m_impl->inbodyDocs && !m_impl->inbodyDocs->doc.isEmpty()) || // has inbody docs
         extractAll //|| // extract everything
  // (sourceBrowser && m_impl->body &&
  // m_impl->body->startLine!=-1 && m_impl->body->fileDef)
         ; // link to definition
  return hasDocs;
}
References DefinitionImpl::IMPL::brief, Config_getBool, DefinitionImpl::IMPL::details, DocInfo::doc, BriefInfo::doc, DefinitionImpl::IMPL::inbodyDocs, QCString::isEmpty(), and m_impl.
Referenced by DefinitionMixin< Base >::hasDocumentation().
hasDocumentation() [2/2]
bool DefinitionImpl::hasDocumentation () const
hasSections() [1/2]
bool DefinitionImpl::hasSections () const
Definition at line 331 of file definition.cpp.
{
  //printf("DefinitionImpl::hasSections(%s) #sections=%d\n",qPrint(name()),
  // m_impl->sectionRefs.size());
  if (m_impl->sectionRefs.empty()) return FALSE;
  for (const SectionInfo *si : m_impl->sectionRefs)
  {
    if (isSection(si->type()))
    {
      return TRUE;
    }
  }
  return FALSE;
}
References SectionRefs::empty(), FALSE, isSection(), m_impl, DefinitionImpl::IMPL::sectionRefs, TRUE, and SectionInfo::type().
Referenced by DefinitionMixin< Base >::hasSections().
hasSections() [2/2]
bool DefinitionImpl::hasSections () const
hasSourceReffedBy() [1/2]
bool DefinitionImpl::hasSourceReffedBy () const
Definition at line 1107 of file definition.cpp.
{
  return !m_impl->sourceRefByDict.empty();
}
References m_impl, and DefinitionImpl::IMPL::sourceRefByDict.
Referenced by DefinitionMixin< Base >::hasSourceReffedBy().
hasSourceReffedBy() [2/2]
bool DefinitionImpl::hasSourceReffedBy () const
hasSourceRefs() [1/2]
bool DefinitionImpl::hasSourceRefs () const
Definition at line 1112 of file definition.cpp.
{
  return !m_impl->sourceRefsDict.empty();
}
References m_impl, and DefinitionImpl::IMPL::sourceRefsDict.
Referenced by DefinitionMixin< Base >::hasSourceRefs().
hasSourceRefs() [2/2]
bool DefinitionImpl::hasSourceRefs () const
hasSources() [1/2]
bool DefinitionImpl::hasSources () const
Definition at line 958 of file definition.cpp.
{
  return m_impl->body && m_impl->body->startLine!=-1 &&
         m_impl->body->endLine>=m_impl->body->startLine &&
         m_impl->body->fileDef;
}
References DefinitionImpl::IMPL::body, BodyInfo::endLine, BodyInfo::fileDef, m_impl, and BodyInfo::startLine.
Referenced by DefinitionMixin< Base >::hasSources(), and writeInlineCode().
hasSources() [2/2]
bool DefinitionImpl::hasSources () const
hasUserDocumentation() [1/2]
bool DefinitionImpl::hasUserDocumentation () const
Definition at line 1132 of file definition.cpp.
{
  bool hasDocs =
         (m_impl->details && !m_impl->details->doc.isEmpty()) ||
         (m_impl->brief && !m_impl->brief->doc.isEmpty()) ||
         (m_impl->inbodyDocs && !m_impl->inbodyDocs->doc.isEmpty());
  return hasDocs;
}
References DefinitionImpl::IMPL::brief, DefinitionImpl::IMPL::details, DocInfo::doc, BriefInfo::doc, DefinitionImpl::IMPL::inbodyDocs, QCString::isEmpty(), and m_impl.
Referenced by DefinitionMixin< Base >::hasUserDocumentation().
hasUserDocumentation() [2/2]
bool DefinitionImpl::hasUserDocumentation () const
id() [1/2]
QCString DefinitionImpl::id () const
Definition at line 304 of file definition.cpp.
{
  return m_impl->id;
}
References DefinitionImpl::IMPL::id, and m_impl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), DefinitionMixin< Base >::id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), doxmlparser.compound.docXRefSectType::set_id(), and setId().
id() [2/2]
QCString DefinitionImpl::id () const
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
inbodyDocumentation() [1/2]
QCString DefinitionImpl::inbodyDocumentation () const
Definition at line 1663 of file definition.cpp.
{
  return m_impl->inbodyDocs ? m_impl->inbodyDocs->doc : QCString("");
}
References DocInfo::doc, DefinitionImpl::IMPL::inbodyDocs, and m_impl.
Referenced by DefinitionMixin< Base >::inbodyDocumentation().
inbodyDocumentation() [2/2]
QCString DefinitionImpl::inbodyDocumentation () const
inbodyFile() [1/2]
QCString DefinitionImpl::inbodyFile () const
Definition at line 1673 of file definition.cpp.
{
  return m_impl->inbodyDocs ? m_impl->inbodyDocs->file : QCString("<"+m_impl->name+">");
}
References DocInfo::file, DefinitionImpl::IMPL::inbodyDocs, m_impl, and DefinitionImpl::IMPL::name.
Referenced by _setInbodyDocumentation(), DefinitionMixin< Base >::inbodyFile(), and setInbodyDocumentation().
inbodyFile() [2/2]
QCString DefinitionImpl::inbodyFile () const
inbodyLine() [1/2]
int DefinitionImpl::inbodyLine () const
Definition at line 1668 of file definition.cpp.
{
  return m_impl->inbodyDocs ? m_impl->inbodyDocs->line : 1;
}
References DefinitionImpl::IMPL::inbodyDocs, DocInfo::line, and m_impl.
Referenced by _setInbodyDocumentation(), DefinitionMixin< Base >::inbodyLine(), and setInbodyDocumentation().
inbodyLine() [2/2]
int DefinitionImpl::inbodyLine () const
isAnonymous() [1/2]
bool DefinitionImpl::isAnonymous () const
Definition at line 1885 of file definition.cpp.
{
  return m_impl->isAnonymous;
}
References DefinitionImpl::IMPL::isAnonymous, and m_impl.
Referenced by DefinitionMixin< Base >::isAnonymous().
isAnonymous() [2/2]
bool DefinitionImpl::isAnonymous () const
isArtificial() [1/2]
bool DefinitionImpl::isArtificial () const
Definition at line 1706 of file definition.cpp.
{
  return m_impl->isArtificial;
}
References DefinitionImpl::IMPL::isArtificial, and m_impl.
Referenced by DefinitionImpl::IMPL::init(), and DefinitionMixin< Base >::isArtificial().
isArtificial() [2/2]
bool DefinitionImpl::isArtificial () const
isHidden() [1/2]
bool DefinitionImpl::isHidden () const
Definition at line 1691 of file definition.cpp.
{
  return m_impl->hidden;
}
References DefinitionImpl::IMPL::hidden, and m_impl.
Referenced by DefinitionMixin< Base >::isHidden().
isHidden() [2/2]
bool DefinitionImpl::isHidden () const
isLinkableViaGroup() [1/2]
bool DefinitionImpl::isLinkableViaGroup () const
Definition at line 1746 of file definition.cpp.
{
  for (const auto &gd : partOfGroups())
  {
    if (gd->isLinkable()) return true;
  }
  return false;
}
References partOfGroups().
Referenced by DefinitionMixin< Base >::isLinkableViaGroup().
isLinkableViaGroup() [2/2]
bool DefinitionImpl::isLinkableViaGroup () const
isReference() [1/2]
bool DefinitionImpl::isReference () const
Definition at line 1716 of file definition.cpp.
{
  return !m_impl->ref.isEmpty();
}
References QCString::isEmpty(), m_impl, and DefinitionImpl::IMPL::ref.
Referenced by DefinitionMixin< Base >::isReference().
isReference() [2/2]
bool DefinitionImpl::isReference () const
isVisible() [1/2]
bool DefinitionImpl::isVisible () const
Definition at line 1701 of file definition.cpp.
{
  return m_impl->def->isLinkable() && !m_impl->hidden;
}
References DefinitionImpl::IMPL::def, DefinitionImpl::IMPL::hidden, Definition::isLinkable(), and m_impl.
Referenced by DefinitionMixin< Base >::isVisible().
isVisible() [2/2]
bool DefinitionImpl::isVisible () const
isVisibleInProject() [1/2]
bool DefinitionImpl::isVisibleInProject () const
Definition at line 1696 of file definition.cpp.
{
  return m_impl->def->isLinkableInProject() && !m_impl->hidden;
}
References DefinitionImpl::IMPL::def, DefinitionImpl::IMPL::hidden, Definition::isLinkableInProject(), and m_impl.
Referenced by DefinitionMixin< Base >::isVisibleInProject().
isVisibleInProject() [2/2]
bool DefinitionImpl::isVisibleInProject () const
localName() [1/2]
QCString DefinitionImpl::localName () const
Definition at line 1243 of file definition.cpp.
{
  return m_impl->localName;
}
References DefinitionImpl::IMPL::localName, and m_impl.
Referenced by DefinitionImpl::IMPL::init(), DefinitionMixin< Base >::localName(), and navigationPathAsString().
localName() [2/2]
QCString DefinitionImpl::localName () const
makePartOfGroup() [1/2]
void DefinitionImpl::makePartOfGroup (const GroupDef * gd)
Definition at line 1248 of file definition.cpp.
{
  m_impl->partOfGroups.push_back(gd);
}
References m_impl, and DefinitionImpl::IMPL::partOfGroups.
Referenced by DefinitionMixin< Base >::makePartOfGroup().
makePartOfGroup() [2/2]
void DefinitionImpl::makePartOfGroup (const GroupDef * gd)
mergeReferencedBy() [1/2]
void DefinitionImpl::mergeReferencedBy (const Definition * other)
Definition at line 1794 of file definition.cpp.
{
  const DefinitionImpl *defImpl = other->toDefinitionImpl_();
  if (defImpl)
  {
    for (const auto &kv : defImpl->m_impl->sourceRefByDict)
    {
      auto it = m_impl->sourceRefByDict.find(kv.first);
      if (it != m_impl->sourceRefByDict.end())
      {
        m_impl->sourceRefByDict.insert({kv.first,kv.second});
      }
    }
  }
}
References m_impl, DefinitionImpl::IMPL::sourceRefByDict, and Definition::toDefinitionImpl_().
Referenced by DefinitionMixin< Base >::mergeReferencedBy().
mergeReferencedBy() [2/2]
void DefinitionImpl::mergeReferencedBy (const Definition * other)
mergeReferences() [1/2]
void DefinitionImpl::mergeReferences (const Definition * other)
Definition at line 1778 of file definition.cpp.
{
  const DefinitionImpl *defImpl = other->toDefinitionImpl_();
  if (defImpl)
  {
    for (const auto &kv : defImpl->m_impl->sourceRefsDict)
    {
      auto it = m_impl->sourceRefsDict.find(kv.first);
      if (it != m_impl->sourceRefsDict.end())
      {
        m_impl->sourceRefsDict.insert(kv);
      }
    }
  }
}
References m_impl, DefinitionImpl::IMPL::sourceRefsDict, and Definition::toDefinitionImpl_().
Referenced by DefinitionMixin< Base >::mergeReferences().
mergeReferences() [2/2]
void DefinitionImpl::mergeReferences (const Definition * other)
mergeRefItems() [1/2]
void DefinitionImpl::mergeRefItems (Definition * d)
Definition at line 1258 of file definition.cpp.
{
  auto otherXrefList = d->xrefListItems();
  // append vectors
  m_impl->xrefListItems.reserve(m_impl->xrefListItems.size()+otherXrefList.size());
  m_impl->xrefListItems.insert (m_impl->xrefListItems.end(),
                                otherXrefList.begin(),otherXrefList.end());
  // sort results on itemId
  std::sort(m_impl->xrefListItems.begin(),m_impl->xrefListItems.end(),
            [](RefItem *left,RefItem *right)
            { return left->id() <right->id() ||
                     (left->id()==right->id() &&
                      left->list()->listName() < right->list()->listName());
            });
  // filter out duplicates
  auto last = std::unique(m_impl->xrefListItems.begin(),m_impl->xrefListItems.end(),
            [](const RefItem *left,const RefItem *right)
            { return left->id()==right->id() &&
                     left->list()->listName()==right->list()->listName();
            });
  m_impl->xrefListItems.erase(last, m_impl->xrefListItems.end());
}
References m_impl, DefinitionImpl::IMPL::xrefListItems, and Definition::xrefListItems().
Referenced by DefinitionMixin< Base >::mergeRefItems().
mergeRefItems() [2/2]
void DefinitionImpl::mergeRefItems (Definition * d)
name() [1/2]
QCString DefinitionImpl::name () const
Definition at line 1880 of file definition.cpp.
{
  return m_impl->name;
}
References m_impl, and DefinitionImpl::IMPL::name.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), _setSymbolName(), _writeSourceRefList(), abbreviate(), addSourceReferencedBy(), addSourceReferences(), addToMap(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), DefinitionImpl(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), matchExcludedSymbols(), search.Finder::members(), DefinitionMixin< Base >::name(), navigationPathAsString(), search.Finder::params(), search.Finder::references(), removeFromMap(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), setLocalName(), setName(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
QCString DefinitionImpl::name () const
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
navigationPathAsString() [1/2]
QCString DefinitionImpl::navigationPathAsString () const
Returns the string used in the footer for $navpath when GENERATE_TREEVIEW is enabled
Definition at line 1339 of file definition.cpp.
{
  QCString result;
  Definition *outerScope = getOuterScope();
  QCString locName = localName();
  if (outerScope && outerScope!=Doxygen::globalScope)
  {
    result+=outerScope->navigationPathAsString();
  }
  else if (m_impl->def->definitionType()==Definition::TypeFile &&
           toFileDef(m_impl->def)->getDirDef())
  {
    result+=(toFileDef(m_impl->def))->getDirDef()->navigationPathAsString();
  }
  result+="<li class=\"navelem\">";
  if (m_impl->def->isLinkable())
  {
    if (m_impl->def->definitionType()==Definition::TypeGroup &&
        !toGroupDef(m_impl->def)->groupTitle().isEmpty())
    {
      result+="<a class=\"el\" href=\"$relpath^"+addHtmlExtensionIfMissing(m_impl->def->getOutputFileBase())+"\">"+
              convertToHtml(toGroupDef(m_impl->def)->groupTitle())+"</a>";
    }
    else if (m_impl->def->definitionType()==Definition::TypePage &&
             toPageDef(m_impl->def)->hasTitle())
    {
      result+="<a class=\"el\" href=\"$relpath^"+addHtmlExtensionIfMissing(m_impl->def->getOutputFileBase())+"\">"+
            convertToHtml((toPageDef(m_impl->def))->title())+"</a>";
    }
    else if (m_impl->def->definitionType()==Definition::TypeClass)
    {
      QCString name = locName;
      if (name.endsWith("-p"))
      {
        name = name.left(name.length()-2);
      }
      result+="<a class=\"el\" href=\"$relpath^"+addHtmlExtensionIfMissing(m_impl->def->getOutputFileBase());
      if (!m_impl->def->anchor().isEmpty()) result+="#"+m_impl->def->anchor();
      result+="\">"+convertToHtml(name)+"</a>";
    }
    else
    {
      result+="<a class=\"el\" href=\"$relpath^"+addHtmlExtensionIfMissing(m_impl->def->getOutputFileBase())+"\">"+
              convertToHtml(locName)+"</a>";
    }
  }
  else
  {
    result+="<b>"+convertToHtml(locName)+"</b>";
  }
  result+="</li>";
  return result;
}
References addHtmlExtensionIfMissing(), Definition::anchor(), convertToHtml(), DefinitionImpl::IMPL::def, Definition::definitionType(), QCString::endsWith(), FileDef::getDirDef(), getOuterScope(), Definition::getOutputFileBase(), Doxygen::globalScope, GroupDef::groupTitle(), PageDef::hasTitle(), QCString::isEmpty(), Definition::isLinkable(), QCString::left(), QCString::length(), localName(), m_impl, name(), Definition::navigationPathAsString(), toFileDef(), toGroupDef(), toPageDef(), Definition::TypeClass, Definition::TypeFile, Definition::TypeGroup, and Definition::TypePage.
Referenced by DefinitionMixin< Base >::navigationPathAsString(), and writeNavigationPath().
navigationPathAsString() [2/2]
QCString DefinitionImpl::navigationPathAsString () const
partOfGroups() [1/2]
const GroupList & DefinitionImpl::partOfGroups () const
Definition at line 1741 of file definition.cpp.
{
  return m_impl->partOfGroups;
}
References m_impl, and DefinitionImpl::IMPL::partOfGroups.
Referenced by isLinkableViaGroup(), and DefinitionMixin< Base >::partOfGroups().
partOfGroups() [2/2]
const GroupList & DefinitionImpl::partOfGroups () const
pathFragment() [1/2]
QCString DefinitionImpl::pathFragment () const
Definition at line 1301 of file definition.cpp.
{
  QCString result;
  if (m_impl->outerScope && m_impl->outerScope!=Doxygen::globalScope)
  {
    result = m_impl->outerScope->pathFragment();
  }
  if (m_impl->def->isLinkable())
  {
    if (!result.isEmpty()) result+="/";
    if (m_impl->def->definitionType()==Definition::TypeGroup &&
        !toGroupDef(m_impl->def)->groupTitle().isEmpty())
    {
      result+=toGroupDef(m_impl->def)->groupTitle();
    }
    else if (m_impl->def->definitionType()==Definition::TypePage &&
        toPageDef(m_impl->def)->hasTitle())
    {
      result+=toPageDef(m_impl->def)->title();
    }
    else
    {
      result+=m_impl->localName;
    }
  }
  else
  {
    result+=m_impl->localName;
  }
  return result;
}
References DefinitionImpl::IMPL::def, Definition::definitionType(), Doxygen::globalScope, GroupDef::groupTitle(), PageDef::hasTitle(), QCString::isEmpty(), Definition::isLinkable(), DefinitionImpl::IMPL::localName, m_impl, DefinitionImpl::IMPL::outerScope, Definition::pathFragment(), PageDef::title(), toGroupDef(), toPageDef(), Definition::TypeGroup, and Definition::TypePage.
Referenced by DefinitionMixin< Base >::pathFragment().
pathFragment() [2/2]
QCString DefinitionImpl::pathFragment () const
qualifiedName() [1/2]
QCString DefinitionImpl::qualifiedName () const
Definition at line 1184 of file definition.cpp.
{
  //static int count=0;
  //count++;
  if (!m_impl->qualifiedName.isEmpty())
  {
    //count--;
    return m_impl->qualifiedName;
  }
  //printf("start %s::qualifiedName() localName=%s\n",qPrint(name()),qPrint(m_impl->localName));
  if (m_impl->outerScope==0)
  {
    if (m_impl->localName=="<globalScope>")
    {
      //count--;
      return "";
    }
    else
    {
      //count--;
      return m_impl->localName;
    }
  }
  if (m_impl->outerScope->name()=="<globalScope>")
  {
    m_impl->qualifiedName = m_impl->localName;
  }
  else
  {
    m_impl->qualifiedName = m_impl->outerScope->qualifiedName()+
           getLanguageSpecificSeparator(getLanguage())+
           m_impl->localName;
  }
  //printf("end %s::qualifiedName()=%s\n",qPrint(name()),qPrint(m_impl->qualifiedName));
  //count--;
  return m_impl->qualifiedName;
}
References getLanguage(), getLanguageSpecificSeparator(), QCString::isEmpty(), DefinitionImpl::IMPL::localName, m_impl, Definition::name(), DefinitionImpl::IMPL::outerScope, DefinitionImpl::IMPL::qualifiedName, and Definition::qualifiedName().
Referenced by DefinitionMixin< Base >::qualifiedName().
qualifiedName() [2/2]
QCString DefinitionImpl::qualifiedName () const
setArtificial() [1/2]
void DefinitionImpl::setArtificial (bool b)
Definition at line 1826 of file definition.cpp.
{
  m_impl->isArtificial = b;
}
References b, DefinitionImpl::IMPL::isArtificial, and m_impl.
Referenced by DefinitionMixin< Base >::setArtificial().
setArtificial() [2/2]
void DefinitionImpl::setArtificial (bool b)
setBodyDef() [1/2]
void DefinitionImpl::setBodyDef (const FileDef * fd)
Definition at line 952 of file definition.cpp.
{
  if (m_impl->body==0) m_impl->body = new BodyInfo;
  m_impl->body->fileDef=fd;
}
References DefinitionImpl::IMPL::body, BodyInfo::fileDef, and m_impl.
Referenced by DefinitionMixin< Base >::setBodyDef().
setBodyDef() [2/2]
void DefinitionImpl::setBodyDef (const FileDef * fd)
setBodySegment() [1/2]
void DefinitionImpl::setBodySegment (int defLine, int bls, int ble)
Definition at line 943 of file definition.cpp.
{
  //printf("setBodySegment(%d,%d) for %s\n",bls,ble,qPrint(name()));
  if (m_impl->body==0) m_impl->body = new BodyInfo;
  m_impl->body->defLine = defLine;
  m_impl->body->startLine = bls;
  m_impl->body->endLine = ble;
}
References DefinitionImpl::IMPL::body, BodyInfo::defLine, BodyInfo::endLine, m_impl, and BodyInfo::startLine.
Referenced by DefinitionMixin< Base >::setBodySegment().
setBodySegment() [2/2]
void DefinitionImpl::setBodySegment (int defLine, int bls, int ble)
setBriefDescription() [1/2]
void DefinitionImpl::setBriefDescription (const QCString & b, const QCString & briefFile, int briefLine)
Definition at line 548 of file definition.cpp.
{
  if (b.isEmpty()) return;
  _setBriefDescription(b,briefFile,briefLine);
}
References _setBriefDescription(), b, briefFile(), and briefLine().
Referenced by DefinitionMixin< Base >::setBriefDescription().
setBriefDescription() [2/2]
void DefinitionImpl::setBriefDescription (const QCString & b, const QCString & briefFile, int briefLine)
setDefFile() [1/2]
void DefinitionImpl::setDefFile (const QCString & df, int defLine, int defColumn)
Definition at line 141 of file definition.cpp.
{
  m_impl->setDefFileName(df);
  m_impl->defLine = defLine;
  m_impl->defColumn = defCol;
}
References DefinitionImpl::IMPL::defColumn, DefinitionImpl::IMPL::defLine, m_impl, and DefinitionImpl::IMPL::setDefFileName().
Referenced by DefinitionMixin< Base >::setDefFile().
setDefFile() [2/2]
void DefinitionImpl::setDefFile (const QCString & df, int defLine, int defColumn)
setDocumentation() [1/2]
void DefinitionImpl::setDocumentation (const QCString & d, const QCString & docFile, int docLine, bool stripWhiteSpace = TRUE)
Definition at line 486 of file definition.cpp.
{
  if (d.isEmpty()) return;
  _setDocumentation(d,docFile,docLine,stripWhiteSpace,FALSE);
}
References _setDocumentation(), docFile(), docLine(), FALSE, and QCString::isEmpty().
Referenced by DefinitionMixin< Base >::setDocumentation().
setDocumentation() [2/2]
void DefinitionImpl::setDocumentation (const QCString & d, const QCString & docFile, int docLine, bool stripWhiteSpace = TRUE)
setHidden() [1/2]
void DefinitionImpl::setHidden (bool b)
Definition at line 1821 of file definition.cpp.
{
  m_impl->hidden = m_impl->hidden || b;
}
References b, DefinitionImpl::IMPL::hidden, and m_impl.
Referenced by DefinitionMixin< Base >::setHidden().
setHidden() [2/2]
void DefinitionImpl::setHidden (bool b)
setId() [1/2]
void DefinitionImpl::setId (const QCString & name)
Definition at line 293 of file definition.cpp.
{
  if (id.isEmpty()) return;
  m_impl->id = id;
  if (Doxygen::clangUsrMap)
  {
    //printf("DefinitionImpl::setId '%s'->'%s'\n",id,qPrint(m_impl->name));
    Doxygen::clangUsrMap->insert(std::make_pair(id.str(),m_impl->def));
  }
}
References DefinitionImpl::IMPL::id, id(), and m_impl.
Referenced by DefinitionMixin< Base >::setId().
setId() [2/2]
void DefinitionImpl::setId (const QCString & name)
setInbodyDocumentation() [1/2]
void DefinitionImpl::setInbodyDocumentation (const QCString & d, const QCString & docFile, int docLine)
Definition at line 572 of file definition.cpp.
{
  if (d.isEmpty()) return;
  _setInbodyDocumentation(d,inbodyFile,inbodyLine);
}
References _setInbodyDocumentation(), inbodyFile(), inbodyLine(), and QCString::isEmpty().
Referenced by DefinitionMixin< Base >::setInbodyDocumentation().
setInbodyDocumentation() [2/2]
void DefinitionImpl::setInbodyDocumentation (const QCString & d, const QCString & docFile, int docLine)
setLanguage() [1/2]
void DefinitionImpl::setLanguage (SrcLangExt lang)
Definition at line 1836 of file definition.cpp.
{
  m_impl->lang=lang;
}
References DefinitionImpl::IMPL::lang, and m_impl.
Referenced by DefinitionMixin< Base >::setLanguage().
setLanguage() [2/2]
void DefinitionImpl::setLanguage (SrcLangExt lang)
setLocalName() [1/2]
void DefinitionImpl::setLocalName (const QCString & name)
Definition at line 1831 of file definition.cpp.
{
  m_impl->localName=name;
}
References DefinitionImpl::IMPL::localName, m_impl, and name().
Referenced by DefinitionMixin< Base >::setLocalName().
setLocalName() [2/2]
void DefinitionImpl::setLocalName (const QCString & name)
setName() [1/2]
void DefinitionImpl::setName (const QCString & name)
Definition at line 284 of file definition.cpp.
{
  if (name.isEmpty()) return;
  m_impl->name = name;
  m_impl->isAnonymous = m_impl->name.isEmpty() ||
                        m_impl->name.at(0)=='@' ||
                        m_impl->name.find("::@")!=-1;
}
References QCString::at(), QCString::find(), DefinitionImpl::IMPL::isAnonymous, QCString::isEmpty(), m_impl, DefinitionImpl::IMPL::name, and name().
Referenced by DefinitionImpl(), and DefinitionMixin< Base >::setName().
setName() [2/2]
void DefinitionImpl::setName (const QCString & name)
setOuterScope() [1/2]
void DefinitionImpl::setOuterScope (Definition * d)
Definition at line 1224 of file definition.cpp.
{
  //printf("%s::setOuterScope(%s)\n",qPrint(name()),d?qPrint(d->name()):"<none>");
  Definition *p = m_impl->outerScope;
  bool found=false;
  // make sure that we are not creating a recursive scope relation.
  while (p && !found)
  {
    found = (p==d);
    p = p->getOuterScope();
  }
  if (!found)
  {
    m_impl->qualifiedName.resize(0); // flush cached scope name
    m_impl->outerScope = d;
  }
  m_impl->hidden = m_impl->hidden || d->isHidden();
}
References found, DefinitionImpl::IMPL::hidden, Definition::isHidden(), m_impl, DefinitionImpl::IMPL::outerScope, p, DefinitionImpl::IMPL::qualifiedName, and QCString::resize().
Referenced by DefinitionMixin< Base >::setOuterScope().
setOuterScope() [2/2]
void DefinitionImpl::setOuterScope (Definition * d)
setReference() [1/2]
void DefinitionImpl::setReference (const QCString & r)
Definition at line 1811 of file definition.cpp.
{
  m_impl->ref=r;
}
References m_impl, r, and DefinitionImpl::IMPL::ref.
Referenced by DefinitionMixin< Base >::setReference().
setReference() [2/2]
void DefinitionImpl::setReference (const QCString & r)
setRefItems() [1/2]
void DefinitionImpl::setRefItems (const RefItemVector & sli)
Definition at line 1253 of file definition.cpp.
{
  m_impl->xrefListItems.insert(m_impl->xrefListItems.end(), sli.cbegin(), sli.cend());
}
References m_impl, and DefinitionImpl::IMPL::xrefListItems.
Referenced by DefinitionMixin< Base >::setRefItems().
setRefItems() [2/2]
void DefinitionImpl::setRefItems (const RefItemVector & sli)
symbolName() [1/2]
QCString DefinitionImpl::symbolName () const
Definition at line 1557 of file definition.cpp.
{
  return m_impl->symbolName;
}
References m_impl, and DefinitionImpl::IMPL::symbolName.
Referenced by addToMap(), and DefinitionMixin< Base >::symbolName().
symbolName() [2/2]
QCString DefinitionImpl::symbolName () const
writeDocAnchorsToTagFile() [1/2]
void DefinitionImpl::writeDocAnchorsToTagFile (TextStream & tagFile) const
Definition at line 396 of file definition.cpp.
{
  if (!m_impl->sectionRefs.empty())
  {
    //printf("%s: writeDocAnchorsToTagFile(%d)\n",qPrint(name()),m_impl->sectionRef.size());
    for (const SectionInfo *si : m_impl->sectionRefs)
    {
      if (!si->generated() && si->ref().isEmpty() && !si->label().startsWith("autotoc_md"))
      {
        //printf("write an entry!\n");
        if (m_impl->def->definitionType()==Definition::TypeMember) tagFile << " ";
        tagFile << " <docanchor file=\"" << addHtmlExtensionIfMissing(si->fileName()) << "\"";
        if (!si->title().isEmpty())
        {
          tagFile << " title=\"" << convertToXML(si->title()) << "\"";
        }
        tagFile << ">" << si->label() << "</docanchor>\n";
      }
    }
  }
}
References addHtmlExtensionIfMissing(), convertToXML(), DefinitionImpl::IMPL::def, Definition::definitionType(), SectionRefs::empty(), SectionInfo::fileName(), SectionInfo::generated(), QCString::isEmpty(), SectionInfo::label(), m_impl, SectionInfo::ref(), DefinitionImpl::IMPL::sectionRefs, QCString::startsWith(), SectionInfo::title(), and Definition::TypeMember.
Referenced by DefinitionMixin< Base >::writeDocAnchorsToTagFile().
writeDocAnchorsToTagFile() [2/2]
void DefinitionImpl::writeDocAnchorsToTagFile (TextStream &) const
writeInlineCode() [1/2]
void DefinitionImpl::writeInlineCode (OutputList & ol, const QCString & scopeName) const
Write code of this definition into the documentation
Definition at line 966 of file definition.cpp.
{
  bool inlineSources = Config_getBool(INLINE_SOURCES);
  ol.pushGeneratorState();
  //printf("Source Fragment %s: %d-%d bodyDef=%p\n",qPrint(name()),
  // m_startBodyLine,m_endBodyLine,m_bodyDef);
  if (inlineSources && hasSources())
  {
    QCString codeFragment;
    int actualStart=m_impl->body->startLine,actualEnd=m_impl->body->endLine;
    if (readCodeFragment(m_impl->body->fileDef->absFilePath(),
          actualStart,actualEnd,codeFragment)
       )
    {
      //printf("Adding code fragment '%s' ext='%s'\n",
      // qPrint(codeFragment),qPrint(m_impl->defFileExt));
      auto intf = Doxygen::parserManager->getCodeParser(m_impl->defFileExt);
      intf->resetCodeParserState();
      //printf("Read:\n'%s'\n\n",qPrint(codeFragment));
      const MemberDef *thisMd = 0;
      if (m_impl->def->definitionType()==Definition::TypeMember)
      {
        thisMd = toMemberDef(m_impl->def);
      }
      ol.startCodeFragment("DoxyCode");
      intf->parseCode(ol, // codeOutIntf
                      scopeName, // scope
                      codeFragment, // input
                      m_impl->lang, // lang
                      FALSE, // isExample
                      QCString(), // exampleName
                      m_impl->body->fileDef, // fileDef
                      actualStart, // startLine
                      actualEnd, // endLine
                      TRUE, // inlineFragment
                      thisMd, // memberDef
                      TRUE // show line numbers
                     );
      ol.endCodeFragment("DoxyCode");
    }
  }
  ol.popGeneratorState();
}
References FileDef::absFilePath(), DefinitionImpl::IMPL::body, Config_getBool, DefinitionImpl::IMPL::def, DefinitionImpl::IMPL::defFileExt, Definition::definitionType(), OutputList::endCodeFragment(), BodyInfo::endLine, FALSE, BodyInfo::fileDef, ParserManager::getCodeParser(), hasSources(), DefinitionImpl::IMPL::lang, m_impl, Doxygen::parserManager, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), readCodeFragment(), OutputList::startCodeFragment(), BodyInfo::startLine, toMemberDef(), TRUE, and Definition::TypeMember.
Referenced by DefinitionMixin< Base >::writeInlineCode().
writeInlineCode() [2/2]
void DefinitionImpl::writeInlineCode (OutputList & ol, const QCString & scopeName) const
writeNavigationPath() [1/2]
void DefinitionImpl::writeNavigationPath (OutputList & ol) const
Definition at line 1394 of file definition.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  QCString navPath;
  navPath += "<div id=\"nav-path\" class=\"navpath\">\n"
             " <ul>\n";
  navPath += navigationPathAsString();
  navPath += " </ul>\n"
             "</div>\n";
  ol.writeNavigationPath(navPath);
  ol.popGeneratorState();
}
References OutputList::disableAllBut(), OutputGenerator::Html, navigationPathAsString(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), and OutputList::writeNavigationPath().
Referenced by DefinitionMixin< Base >::writeNavigationPath().
writeNavigationPath() [2/2]
void DefinitionImpl::writeNavigationPath (OutputList & ol) const
writeQuickMemberLinks() [1/2]
void DefinitionImpl::writeQuickMemberLinks (OutputList & , const MemberDef *) const
Definition at line 1900 of file definition.cpp.
{
}
Referenced by DefinitionMixin< Base >::writeQuickMemberLinks().
writeQuickMemberLinks() [2/2]
void DefinitionImpl::writeQuickMemberLinks (OutputList & , const MemberDef *) const
writeSourceDef() [1/2]
void DefinitionImpl::writeSourceDef (OutputList & ol, const QCString & scopeName) const
Write a reference to the source code defining this definition
Definition at line 894 of file definition.cpp.
{
  //printf("DefinitionImpl::writeSourceRef %d %p\n",bodyLine,bodyDef);
  QCString fn = getSourceFileBase();
  if (!fn.isEmpty())
  {
    QCString refText = theTranslator->trDefinedAtLineInSourceFile();
    int lineMarkerPos = refText.find("@0");
    int fileMarkerPos = refText.find("@1");
    if (lineMarkerPos!=-1 && fileMarkerPos!=-1) // should always pass this.
    {
      QCString lineStr;
      lineStr.sprintf("%d",m_impl->body->defLine);
      QCString anchorStr = getSourceAnchor();
      ol.startParagraph("definition");
      if (lineMarkerPos<fileMarkerPos) // line marker before file marker
      {
        // write text left from linePos marker
        ol.parseText(refText.left(lineMarkerPos));
        ol.writeObjectLink(QCString(),fn,anchorStr,lineStr);
        // write text between markers
        ol.parseText(refText.mid(lineMarkerPos+2,fileMarkerPos-lineMarkerPos-2));
        // write file link
        ol.writeObjectLink(QCString(),fn,QCString(),m_impl->body->fileDef->name());
        // write text right from file marker
        ol.parseText(refText.right(refText.length()-static_cast<size_t>(fileMarkerPos)-2));
      }
      else // file marker before line marker
      {
        // write text left from file marker
        ol.parseText(refText.left(fileMarkerPos));
        // write file link
        ol.writeObjectLink(QCString(),fn,QCString(),m_impl->body->fileDef->name());
        // write text between markers
        ol.parseText(refText.mid(fileMarkerPos+2,lineMarkerPos-fileMarkerPos-2));
        // write line link
        ol.writeObjectLink(QCString(),fn,anchorStr,lineStr);
        // write text right from linePos marker
        ol.parseText(refText.right(refText.length()-static_cast<size_t>(lineMarkerPos)-2));
      }
      ol.endParagraph();
    }
    else
    {
      err("translation error: invalid markers in trDefinedAtLineInSourceFile()\n");
    }
  }
}
References DefinitionImpl::IMPL::body, BodyInfo::defLine, OutputList::endParagraph(), err(), BodyInfo::fileDef, QCString::find(), getSourceAnchor(), getSourceFileBase(), QCString::isEmpty(), QCString::left(), QCString::length(), m_impl, QCString::mid(), FileDef::name(), OutputList::parseText(), QCString::right(), QCString::sprintf(), OutputList::startParagraph(), theTranslator, Translator::trDefinedAtLineInSourceFile(), and OutputList::writeObjectLink().
Referenced by DefinitionMixin< Base >::writeSourceDef().
writeSourceDef() [2/2]
void DefinitionImpl::writeSourceDef (OutputList & ol, const QCString & scopeName) const
writeSourceReffedBy() [1/2]
void DefinitionImpl::writeSourceReffedBy (OutputList & ol, const QCString & scopeName) const
Definition at line 1097 of file definition.cpp.
{
  _writeSourceRefList(ol,scopeName,theTranslator->trReferencedBy(),m_impl->sourceRefByDict,FALSE);
}
References _writeSourceRefList(), FALSE, m_impl, DefinitionImpl::IMPL::sourceRefByDict, theTranslator, and Translator::trReferencedBy().
Referenced by DefinitionMixin< Base >::writeSourceReffedBy().
writeSourceReffedBy() [2/2]
void DefinitionImpl::writeSourceReffedBy (OutputList & ol, const QCString & scopeName) const
writeSourceRefs() [1/2]
void DefinitionImpl::writeSourceRefs (OutputList & ol, const QCString & scopeName) const
Definition at line 1102 of file definition.cpp.
{
  _writeSourceRefList(ol,scopeName,theTranslator->trReferences(),m_impl->sourceRefsDict,TRUE);
}
References _writeSourceRefList(), m_impl, DefinitionImpl::IMPL::sourceRefsDict, theTranslator, Translator::trReferences(), and TRUE.
Referenced by DefinitionMixin< Base >::writeSourceRefs().
writeSourceRefs() [2/2]
void DefinitionImpl::writeSourceRefs (OutputList & ol, const QCString & scopeName) const
writeSummaryLinks() [1/2]
void DefinitionImpl::writeSummaryLinks (OutputList &) const
Definition at line 1904 of file definition.cpp.
{
}
Referenced by DefinitionMixin< Base >::writeSummaryLinks().
writeSummaryLinks() [2/2]
void DefinitionImpl::writeSummaryLinks (OutputList &) const
writeToc() [1/2]
void DefinitionImpl::writeToc (OutputList & ol, const LocalToc & lt) const
Definition at line 1411 of file definition.cpp.
{
  if (m_impl->sectionRefs.empty()) return;
  if (localToc.isHtmlEnabled())
  {
    int maxLevel = localToc.htmlLevel();
    ol.pushGeneratorState();
    ol.disableAllBut(OutputGenerator::Html);
    ol.writeString("<div class=\"toc\">");
    ol.writeString("<h3>");
    ol.writeString(theTranslator->trRTFTableOfContents());
    ol.writeString("</h3>\n");
    ol.writeString("<ul>");
    int level=1,l;
    char cs[2];
    cs[1]='\0';
    BoolVector inLi(maxLevel+1,false);
    for (const SectionInfo *si : m_impl->sectionRefs)
    {
      SectionType type = si->type();
      if (isSection(type))
      {
        //printf(" level=%d title=%s\n",level,qPrint(si->title));
        int nextLevel = static_cast<int>(type);
        if (nextLevel>level)
        {
          for (l=level;l<nextLevel;l++)
          {
            if (l < maxLevel) ol.writeString("<ul>");
          }
        }
        else if (nextLevel<level)
        {
          for (l=level;l>nextLevel;l--)
          {
            if (l <= maxLevel && inLi[l]) ol.writeString("</li>\n");
            inLi[l]=false;
            if (l <= maxLevel) ol.writeString("</ul>\n");
          }
        }
        cs[0]=static_cast<char>('0'+nextLevel);
        if (nextLevel <= maxLevel && inLi[nextLevel])
        {
          ol.writeString("</li>\n");
        }
        QCString titleDoc = convertToHtml(si->title());
        if (nextLevel <= maxLevel)
        {
          ol.writeString("<li class=\"level"+QCString(cs)+"\">"
                         "<a href=\"#"+si->label()+"\">"+
                         (si->title().isEmpty()?si->label():titleDoc)+"</a>");
        }
        inLi[nextLevel]=true;
        level = nextLevel;
      }
    }
    if (level > maxLevel) level = maxLevel;
    while (level>1 && level <= maxLevel)
    {
      if (inLi[level])
      {
        ol.writeString("</li>\n");
      }
      inLi[level]=FALSE;
      ol.writeString("</ul>\n");
      level--;
    }
    if (level <= maxLevel && inLi[level]) ol.writeString("</li>\n");
    ol.writeString("</ul>\n");
    ol.writeString("</div>\n");
    ol.popGeneratorState();
  }
  if (localToc.isDocbookEnabled())
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputGenerator::Docbook);
    ol.writeString(" <toc>\n");
    ol.writeString(" <title>" + theTranslator->trRTFTableOfContents() + "</title>\n");
    int level=1,l;
    int maxLevel = localToc.docbookLevel();
    BoolVector inLi(maxLevel+1,false);
    for (const SectionInfo *si : m_impl->sectionRefs)
    {
      SectionType type = si->type();
      if (isSection(type))
      {
        //printf(" level=%d title=%s\n",level,qPrint(si->title));
        int nextLevel = static_cast<int>(type);
        if (nextLevel>level)
        {
          for (l=level;l<nextLevel;l++)
          {
            if (l < maxLevel) ol.writeString(" <tocdiv>\n");
          }
        }
        else if (nextLevel<level)
        {
          for (l=level;l>nextLevel;l--)
          {
            inLi[l]=FALSE;
            if (l <= maxLevel) ol.writeString(" </tocdiv>\n");
          }
        }
        if (nextLevel <= maxLevel)
        {
          QCString titleDoc = convertToDocBook(si->title());
          ol.writeString(" <tocentry>" +
              (si->title().isEmpty()?si->label():titleDoc) +
              "</tocentry>\n");
        }
        inLi[nextLevel]=TRUE;
        level = nextLevel;
      }
    }
    if (level > maxLevel) level = maxLevel;
    while (level>1 && level <= maxLevel)
    {
      inLi[level]=FALSE;
      ol.writeString("</tocdiv>\n");
      level--;
    }
    ol.writeString(" </toc>\n");
    ol.popGeneratorState();
  }
  if (localToc.isLatexEnabled())
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputGenerator::Latex);
    int maxLevel = localToc.latexLevel();
    ol.writeString("\\etocsetnexttocdepth{"+QCString().setNum(maxLevel)+"}\n");
    ol.writeString("\\localtableofcontents\n");
    ol.popGeneratorState();
  }
}
References convertToDocBook(), convertToHtml(), cs, OutputList::disableAllBut(), OutputGenerator::Docbook, LocalToc::docbookLevel(), SectionRefs::empty(), FALSE, OutputGenerator::Html, LocalToc::htmlLevel(), LocalToc::isDocbookEnabled(), QCString::isEmpty(), LocalToc::isHtmlEnabled(), LocalToc::isLatexEnabled(), isSection(), SectionInfo::label(), OutputGenerator::Latex, LocalToc::latexLevel(), level, m_impl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), DefinitionImpl::IMPL::sectionRefs, theTranslator, SectionInfo::title(), Translator::trRTFTableOfContents(), TRUE, SectionInfo::type(), and OutputList::writeString().
Referenced by DefinitionMixin< Base >::writeToc().
writeToc() [2/2]
void DefinitionImpl::writeToc (OutputList & ol, const LocalToc & lt) const
xrefListItems() [1/2]
const RefItemVector & DefinitionImpl::xrefListItems () const
Definition at line 1296 of file definition.cpp.
{
  return m_impl->xrefListItems;
}
References m_impl, and DefinitionImpl::IMPL::xrefListItems.
Referenced by DefinitionMixin< Base >::xrefListItems().
xrefListItems() [2/2]
const RefItemVector & DefinitionImpl::xrefListItems () const
Member Data Documentation
m_impl
IMPL * DefinitionImpl::m_impl [private]
Definition at line 138 of file definitionimpl.h.
Referenced by _getXRefListId(), _setBriefDescription(), _setDocumentation(), _setInbodyDocumentation(), _setSymbolName(), _symbolName(), _writeSourceRefList(), addSectionsToDefinition(), addSectionsToIndex(), addSourceReferencedBy(), addSourceReferences(), briefDescription(), briefDescriptionAsTooltip(), briefFile(), briefLine(), computeTooltip(), DefinitionImpl(), docFile(), docLine(), documentation(), getBodyDef(), getDefColumn(), getDefFileExtension(), getDefFileName(), getDefLine(), getEndBodyLine(), getLanguage(), getOuterScope(), getReference(), getReferencedByMembers(), getReferencesMembers(), getSectionRefs(), getSourceAnchor(), getSourceFileBase(), getStartBodyLine(), getStartDefLine(), hasDocumentation(), hasSections(), hasSourceReffedBy(), hasSourceRefs(), hasSources(), hasUserDocumentation(), id(), inbodyDocumentation(), inbodyFile(), inbodyLine(), isAnonymous(), isArtificial(), isHidden(), isReference(), isVisible(), isVisibleInProject(), localName(), makePartOfGroup(), mergeReferencedBy(), mergeReferences(), mergeRefItems(), name(), navigationPathAsString(), partOfGroups(), pathFragment(), qualifiedName(), setArtificial(), setBodyDef(), setBodySegment(), setDefFile(), setHidden(), setId(), setLanguage(), setLocalName(), setName(), setOuterScope(), setReference(), setRefItems(), symbolName(), toDefinitionMutable(), writeDocAnchorsToTagFile(), writeInlineCode(), writeSourceDef(), writeSourceReffedBy(), writeSourceRefs(), writeToc(), xrefListItems(), and ~DefinitionImpl().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/definitionimpl.h
doxygen/src/definitionimpl.h
doxygen/build/doxygen/src/definition.cpp
doxygen/src/definition.cpp