TranslatorSlovak Class Reference
#include <translator_sk.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
Additional Inherited Members
Detailed Description
Definition at line 35 of file translator_sk.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorSlovak::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 56 of file translator_sk.h.
    {
      return "0x41B Slovak";
    }
getLanguageString() [2/2]
virtual QCString TranslatorSlovak::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 56 of file translator_sk.h.
    {
      return "0x41B Slovak";
    }
idLanguage() [1/2]
virtual QCString TranslatorSlovak::idLanguage () [inline], [virtual]
Implements Translator.
Definition at line 40 of file translator_sk.h.
    { return "slovak"; }
idLanguage() [2/2]
virtual QCString TranslatorSlovak::idLanguage () [inline], [virtual]
Implements Translator.
Definition at line 40 of file translator_sk.h.
    { return "slovak"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorSlovak::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 43 of file translator_sk.h.
    { return "\\usepackage[slovak]{babel}\n"
             "\\usepackage{regexpatch}\n"
             "\\makeatletter\n"
             "% Change the `-` delimiter to an active character\n"
             "\\xpatchparametertext\\@@@cmidrule{-}{\\cA-}{}{}\n"
             "\\xpatchparametertext\\@cline{-}{\\cA-}{}{}\n"
             "\\makeatother\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorSlovak::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 43 of file translator_sk.h.
    { return "\\usepackage[slovak]{babel}\n"
             "\\usepackage{regexpatch}\n"
             "\\makeatletter\n"
             "% Change the `-` delimiter to an active character\n"
             "\\xpatchparametertext\\@@@cmidrule{-}{\\cA-}{}{}\n"
             "\\xpatchparametertext\\@cline{-}{\\cA-}{}{}\n"
             "\\makeatother\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorSlovak::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1861 of file translator_sk.h.
    { return "aie zdeden leny"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorSlovak::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1861 of file translator_sk.h.
    { return "aie zdeden leny"; }
trAll() [1/2]
virtual QCString TranslatorSlovak::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1358 of file translator_sk.h.
    {
      return "Vetko";
    }
trAll() [2/2]
virtual QCString TranslatorSlovak::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1358 of file translator_sk.h.
    {
      return "Vetko";
    }
trAndMore() [1/2]
virtual QCString TranslatorSlovak::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1832 of file translator_sk.h.
    {
        QCString result("a " + number + " a");
        if (number.toInt() >= 5)
            result += "ch";
        return result + "...";
    }
References QCString::toInt().
trAndMore() [2/2]
virtual QCString TranslatorSlovak::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1832 of file translator_sk.h.
    {
        QCString result("a " + number + " a");
        if (number.toInt() >= 5)
            result += "ch";
        return result + "...";
    }
References QCString::toInt().
trAttention() [1/2]
virtual QCString TranslatorSlovak::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_sk.h.
    {
      return "Upozornenie";
    }
trAttention() [2/2]
virtual QCString TranslatorSlovak::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_sk.h.
    {
      return "Upozornenie";
    }
trAuthor() [1/2]
virtual QCString TranslatorSlovak::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1229 of file translator_sk.h.
    {
      QCString result((first_capital ? "Auto" : "auto"));
      result += (singular) ? "r" : "ri";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorSlovak::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1229 of file translator_sk.h.
    {
      QCString result((first_capital ? "Auto" : "auto"));
      result += (singular) ? "r" : "ri";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorSlovak::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1113 of file translator_sk.h.
    {
      return "Chyba";
    }
trBug() [2/2]
virtual QCString TranslatorSlovak::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1113 of file translator_sk.h.
    {
      return "Chyba";
    }
trBugList() [1/2]
virtual QCString TranslatorSlovak::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1118 of file translator_sk.h.
    {
      return "Zoznam chb";
    }
trBugList() [2/2]
virtual QCString TranslatorSlovak::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1118 of file translator_sk.h.
    {
      return "Zoznam chb";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorSlovak::trCallerGraph () [inline], [virtual]
Implements Translator.
Definition at line 1485 of file translator_sk.h.
    { return "Tto funkciu volaj..."; }
trCallerGraph() [2/2]
virtual QCString TranslatorSlovak::trCallerGraph () [inline], [virtual]
Implements Translator.
Definition at line 1485 of file translator_sk.h.
    { return "Tto funkciu volaj..."; }
trCallGraph() [1/2]
virtual QCString TranslatorSlovak::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1363 of file translator_sk.h.
    {
      return "Tto funkcia vol...";
    }
trCallGraph() [2/2]
virtual QCString TranslatorSlovak::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1363 of file translator_sk.h.
    {
      return "Tto funkcia vol...";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorSlovak::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1808 of file translator_sk.h.
    { return "Odkazy na literatru"; }
trCiteReferences() [2/2]
virtual QCString TranslatorSlovak::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1808 of file translator_sk.h.
    { return "Odkazy na literatru"; }
trClass() [1/2]
virtual QCString TranslatorSlovak::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1149 of file translator_sk.h.
    {
      QCString result((first_capital ? "Tried" : "tried"));
      result+=(singular ? "a" : "y");
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorSlovak::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1149 of file translator_sk.h.
    {
      QCString result((first_capital ? "Tried" : "tried"));
      result+=(singular ? "a" : "y");
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorSlovak::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 488 of file translator_sk.h.
    {
      return "Diagram dedinosti pre triedu "+clName;
    }
trClassDiagram() [2/2]
virtual QCString TranslatorSlovak::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 488 of file translator_sk.h.
    {
      return "Diagram dedinosti pre triedu "+clName;
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorSlovak::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 376 of file translator_sk.h.
    { return "Dokumentcia tried"; }
trClassDocumentation() [2/2]
virtual QCString TranslatorSlovak::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 376 of file translator_sk.h.
    { return "Dokumentcia tried"; }
trClasses() [1/2]
virtual QCString TranslatorSlovak::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1082 of file translator_sk.h.
    {
      return "Triedy";
    }
trClasses() [2/2]
virtual QCString TranslatorSlovak::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1082 of file translator_sk.h.
    {
      return "Triedy";
    }
trClassHierarchy() [1/2]
virtual QCString TranslatorSlovak::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 152 of file translator_sk.h.
    { return "Hierarchia tried"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorSlovak::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 152 of file translator_sk.h.
    { return "Hierarchia tried"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorSlovak::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 211 of file translator_sk.h.
    { return "Tu njdete zoznam, vyjadrujci vzah dedinosti tried. "
             "Je zoraden pribline (ale nie plne) poda abecedy:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorSlovak::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 211 of file translator_sk.h.
    { return "Tu njdete zoznam, vyjadrujci vzah dedinosti tried. "
             "Je zoraden pribline (ale nie plne) poda abecedy:";
    }
trClassMethods() [1/2]
virtual QCString TranslatorSlovak::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1899 of file translator_sk.h.
    {
      return "Metdy triedy";
    }
trClassMethods() [2/2]
virtual QCString TranslatorSlovak::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1899 of file translator_sk.h.
    {
      return "Metdy triedy";
    }
trCode() [1/2]
virtual QCString TranslatorSlovak::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 849 of file translator_sk.h.
    {
      return "zdrojov text";
    }
trCode() [2/2]
virtual QCString TranslatorSlovak::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 849 of file translator_sk.h.
    {
      return "zdrojov text";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorSlovak::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 803 of file translator_sk.h.
    {
      return "Diagram tried pre "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorSlovak::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 803 of file translator_sk.h.
    {
      return "Diagram tried pre "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorSlovak::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 349 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Register dtovch truktr";
      }
      else
      {
        return "Register tried";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorSlovak::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 349 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Register dtovch truktr";
      }
      else
      {
        return "Register tried";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorSlovak::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1541 of file translator_sk.h.
    { return "Register dtovch typov"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorSlovak::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1541 of file translator_sk.h.
    { return "Register dtovch typov"; }
trCompoundList() [1/2]
virtual QCString TranslatorSlovak::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 156 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dtov truktry";
      }
      else
      {
        return "Zoznam tried";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorSlovak::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 156 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dtov truktry";
      }
      else
      {
        return "Zoznam tried";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorSlovak::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 226 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Nasledujci zoznam obsahuje identifikciu dtovch "
               "truktr a ich strun popisy:";
      }
      else
      {
        return "Nasledujci zoznam obsahuje predovetkm identifikciu "
               "tried, ale nachdzaj sa tu i alie netrivilne prvky, "
               "ako s truktry (struct), uniony (union) a rozhrania "
               "(interface). V zozname s uveden ich strun "
               "popisy:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorSlovak::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 226 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Nasledujci zoznam obsahuje identifikciu dtovch "
               "truktr a ich strun popisy:";
      }
      else
      {
        return "Nasledujci zoznam obsahuje predovetkm identifikciu "
               "tried, ale nachdzaj sa tu i alie netrivilne prvky, "
               "ako s truktry (struct), uniony (union) a rozhrania "
               "(interface). V zozname s uveden ich strun "
               "popisy:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorSlovak::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1513 of file translator_sk.h.
    { return "Dtov typy so strunmi popismi:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorSlovak::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1513 of file translator_sk.h.
    { return "Dtov typy so strunmi popismi:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorSlovak::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1505 of file translator_sk.h.
    { return "Zoznam dtovch typov"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorSlovak::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1505 of file translator_sk.h.
    { return "Zoznam dtovch typov"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorSlovak::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 173 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dtov poloky";
      }
      else
      {
        return "Zoznam lenov tried";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorSlovak::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 173 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dtov poloky";
      }
      else
      {
        return "Zoznam lenov tried";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorSlovak::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 244 of file translator_sk.h.
    {
      QCString result= "Tu njdete zoznam vetkch ";
      if (!extractAll)
      {
        result += "dokumentovanch ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result += "poloiek truktr (struct) a unionov (union) ";
      }
      else
      {
        result += "lenov tried ";
      }
      result += "s odkazmi na ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result += "dokumentciu truktr/unionov, ku ktorm prislchaj:";
        }
        else
        {
          result += "dokumentciu tried, ku ktorm prislchaj:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="truktry/uniony, ku ktorm prislchaj:";
        }
        else
        {
          result+="triedy, ku ktorm prislchaj:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorSlovak::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 244 of file translator_sk.h.
    {
      QCString result= "Tu njdete zoznam vetkch ";
      if (!extractAll)
      {
        result += "dokumentovanch ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result += "poloiek truktr (struct) a unionov (union) ";
      }
      else
      {
        result += "lenov tried ";
      }
      result += "s odkazmi na ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result += "dokumentciu truktr/unionov, ku ktorm prislchaj:";
        }
        else
        {
          result += "dokumentciu tried, ku ktorm prislchaj:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="truktry/uniony, ku ktorm prislchaj:";
        }
        else
        {
          result+="triedy, ku ktorm prislchaj:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorSlovak::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1517 of file translator_sk.h.
    {
      QCString result="Nasleduje zoznam vetkch ";
      if (!extractAll)
      {
        result+="dokumentovanch ";
      }
      result+="zloiek dtovch typov";
      result+=" s odkazmi na ";
      if (!extractAll)
      {
         result+="dokumentciu dtovej truktry pre kad zloku:";
      }
      else
      {
          result+="pslun dtov typy:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorSlovak::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1517 of file translator_sk.h.
    {
      QCString result="Nasleduje zoznam vetkch ";
      if (!extractAll)
      {
        result+="dokumentovanch ";
      }
      result+="zloiek dtovch typov";
      result+=" s odkazmi na ";
      if (!extractAll)
      {
         result+="dokumentciu dtovej truktry pre kad zloku:";
      }
      else
      {
          result+="pslun dtov typy:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorSlovak::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1509 of file translator_sk.h.
    { return "Dtov polia"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorSlovak::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1509 of file translator_sk.h.
    { return "Dtov polia"; }
trCompoundReference() [1/2]
virtual QCString TranslatorSlovak::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 561 of file translator_sk.h.
    {
      QCString result("Dokumentcia ");
      if (isTemplate) result+="ablny ";
      switch(compType)
      {
        case ClassDef::Class: result+="triedy "; break;
        case ClassDef::Struct: result+="truktry "; break;
        case ClassDef::Union: result+="unionu "; break;
        case ClassDef::Interface: result+="rozhrania "; break;
        case ClassDef::Protocol: result+="protokol "; break;
        case ClassDef::Category: result+="kategria "; break;
        case ClassDef::Exception: result+="vnimky "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorSlovak::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 561 of file translator_sk.h.
    {
      QCString result("Dokumentcia ");
      if (isTemplate) result+="ablny ";
      switch(compType)
      {
        case ClassDef::Class: result+="triedy "; break;
        case ClassDef::Struct: result+="truktry "; break;
        case ClassDef::Union: result+="unionu "; break;
        case ClassDef::Interface: result+="rozhrania "; break;
        case ClassDef::Protocol: result+="protokol "; break;
        case ClassDef::Category: result+="kategria "; break;
        case ClassDef::Exception: result+="vnimky "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorSlovak::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1582 of file translator_sk.h.
    {
      QCString result("Dokumentcia ");
      if (isTemplate) result += "ablny ";
      switch(compType)
      {
        case ClassDef::Class: result += "triedy "; break;
        case ClassDef::Struct: result += "typu "; break;
        case ClassDef::Union: result += "nie "; break;
        case ClassDef::Interface: result += "rozhrania "; break;
        case ClassDef::Protocol: result += "protokolu "; break;
        case ClassDef::Category: result += "kategrie "; break;
        case ClassDef::Exception: result += "vnimky "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorSlovak::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1582 of file translator_sk.h.
    {
      QCString result("Dokumentcia ");
      if (isTemplate) result += "ablny ";
      switch(compType)
      {
        case ClassDef::Class: result += "triedy "; break;
        case ClassDef::Struct: result += "typu "; break;
        case ClassDef::Union: result += "nie "; break;
        case ClassDef::Interface: result += "rozhrania "; break;
        case ClassDef::Protocol: result += "protokolu "; break;
        case ClassDef::Category: result += "kategrie "; break;
        case ClassDef::Exception: result += "vnimky "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorSlovak::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 464 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dtov truktry";
      }
      else
      {
        return "Triedy";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorSlovak::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 464 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dtov truktry";
      }
      else
      {
        return "Triedy";
      }
    }
References Config_getBool.
trConstantGroupReference() [1/2]
virtual QCString TranslatorSlovak::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1936 of file translator_sk.h.
    {
      QCString result="Kontantn skupiny z ";
      result += namespaceName;
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorSlovak::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1936 of file translator_sk.h.
    {
      QCString result="Kontantn skupiny z ";
      result += namespaceName;
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorSlovak::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1932 of file translator_sk.h.
    { return "Kontantn skupiny"; }
trConstantGroups() [2/2]
virtual QCString TranslatorSlovak::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1932 of file translator_sk.h.
    { return "Kontantn skupiny"; }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorSlovak::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 814 of file translator_sk.h.
    {
      return "Dokumentcia kontruktoru a detruktoru";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorSlovak::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 814 of file translator_sk.h.
    {
      return "Dokumentcia kontruktoru a detruktoru";
    }
trCopyright() [1/2]
virtual QCString TranslatorSlovak::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1812 of file translator_sk.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorSlovak::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1812 of file translator_sk.h.
    { return "Copyright"; }
trDataTypes() [1/2]
virtual QCString TranslatorSlovak::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1565 of file translator_sk.h.
    { return "Dtov typy"; }
trDataTypes() [2/2]
virtual QCString TranslatorSlovak::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1565 of file translator_sk.h.
    { return "Dtov typy"; }
trDate() [1/2]
virtual QCString TranslatorSlovak::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 502 of file translator_sk.h.
    { return "Dtum"; }
trDate() [2/2]
virtual QCString TranslatorSlovak::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 502 of file translator_sk.h.
    { return "Dtum"; }
trDateTime() [1/2]
virtual QCString TranslatorSlovak::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1765 of file translator_sk.h.
    {
      static const char *days[] = { "po","ut","st","t","pi","so","ne" };
      static const char *months[] = { "jan","feb","mar","apr","mj","jn","jl","aug","sep","okt","nov","dec" };
      QCString sdate;
      sdate.sprintf("%s %d. %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d.%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorSlovak::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1765 of file translator_sk.h.
    {
      static const char *days[] = { "po","ut","st","t","pi","so","ne" };
      static const char *months[] = { "jan","feb","mar","apr","mj","jn","jl","aug","sep","okt","nov","dec" };
      QCString sdate;
      sdate.sprintf("%s %d. %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d.%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorSlovak::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1781 of file translator_sk.h.
    {
      static const char *days_short[] = { "po", "ut", "st", "t", "pi", "so", "ne" };
      static const char *days_full[] = { "pondelok", "utorok", "streda", "tvrtok", "piatok", "sobota", "nedea" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorSlovak::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1781 of file translator_sk.h.
    {
      static const char *days_short[] = { "po", "ut", "st", "t", "pi", "so", "ne" };
      static const char *days_full[] = { "pondelok", "utorok", "streda", "tvrtok", "piatok", "sobota", "nedea" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorSlovak::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1797 of file translator_sk.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorSlovak::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1797 of file translator_sk.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorSlovak::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 780 of file translator_sk.h.
    {
      return "Defincia je uveden na riadku @0 v sbore @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorSlovak::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 780 of file translator_sk.h.
    {
      return "Defincia je uveden na riadku @0 v sbore @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorSlovak::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 140 of file translator_sk.h.
    { return "definovan v"; }
trDefinedIn() [2/2]
virtual QCString TranslatorSlovak::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 140 of file translator_sk.h.
    { return "definovan v"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorSlovak::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 784 of file translator_sk.h.
    {
      return "Defincia v sbore @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorSlovak::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 784 of file translator_sk.h.
    {
      return "Defincia v sbore @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorSlovak::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 434 of file translator_sk.h.
    { return "Dokumentcia k defincim makier"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorSlovak::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 434 of file translator_sk.h.
    { return "Dokumentcia k defincim makier"; }
trDefines() [1/2]
virtual QCString TranslatorSlovak::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 398 of file translator_sk.h.
    { return "Defincia makier"; }
trDefines() [2/2]
virtual QCString TranslatorSlovak::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 398 of file translator_sk.h.
    { return "Defincia makier"; }
trDefineValue() [1/2]
virtual QCString TranslatorSlovak::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1103 of file translator_sk.h.
    {
      return "Hodnota:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorSlovak::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1103 of file translator_sk.h.
    {
      return "Hodnota:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorSlovak::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 793 of file translator_sk.h.
    {
      return "Zastaral";
    }
trDeprecated() [2/2]
virtual QCString TranslatorSlovak::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 793 of file translator_sk.h.
    {
      return "Zastaral";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorSlovak::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1286 of file translator_sk.h.
    {
      return "Zastaran metdy";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorSlovak::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1286 of file translator_sk.h.
    {
      return "Zastaran metdy";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorSlovak::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 71 of file translator_sk.h.
    { return "Detailn popis"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorSlovak::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 71 of file translator_sk.h.
    { return "Detailn popis"; }
trDetailLevel() [1/2]
virtual QCString TranslatorSlovak::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1824 of file translator_sk.h.
    { return "rove detailov"; }
trDetailLevel() [2/2]
virtual QCString TranslatorSlovak::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1824 of file translator_sk.h.
    { return "rove detailov"; }
trDir() [1/2]
virtual QCString TranslatorSlovak::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1459 of file translator_sk.h.
    {
        QCString result((first_capital ? "Adresr" : "adresr"));
        if (! singular)
            result += "e";
        return result;
    }
trDir() [2/2]
virtual QCString TranslatorSlovak::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1459 of file translator_sk.h.
    {
        QCString result((first_capital ? "Adresr" : "adresr"));
        if (! singular)
            result += "e";
        return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorSlovak::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1816 of file translator_sk.h.
    { return QCString("Graf zvislosti na prieinkoch pre ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorSlovak::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1816 of file translator_sk.h.
    { return QCString("Graf zvislosti na prieinkoch pre ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorSlovak::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1437 of file translator_sk.h.
    { return "Dokumentcia k adresrom"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorSlovak::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1437 of file translator_sk.h.
    { return "Dokumentcia k adresrom"; }
trDirectories() [1/2]
virtual QCString TranslatorSlovak::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1443 of file translator_sk.h.
    { return "Adresre"; }
trDirectories() [2/2]
virtual QCString TranslatorSlovak::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1443 of file translator_sk.h.
    { return "Adresre"; }
trDirIndex() [1/2]
virtual QCString TranslatorSlovak::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1431 of file translator_sk.h.
    { return "Hierarchia adresrov"; }
trDirIndex() [2/2]
virtual QCString TranslatorSlovak::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1431 of file translator_sk.h.
    { return "Hierarchia adresrov"; }
trDirReference() [1/2]
virtual QCString TranslatorSlovak::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1449 of file translator_sk.h.
    {
        QCString result = "Referencia k adresru ";
        result += dirName;
        return result;
    }
trDirReference() [2/2]
virtual QCString TranslatorSlovak::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1449 of file translator_sk.h.
    {
        QCString result = "Referencia k adresru ";
        result += dirName;
        return result;
    }
trDirRelation() [1/2]
virtual QCString TranslatorSlovak::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1704 of file translator_sk.h.
    {
      return "Relcia " + QCString(name);
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorSlovak::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1704 of file translator_sk.h.
    {
      return "Relcia " + QCString(name);
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorSlovak::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 331 of file translator_sk.h.
    { return "Dokumentcia"; }
trDocumentation() [2/2]
virtual QCString TranslatorSlovak::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 331 of file translator_sk.h.
    { return "Dokumentcia"; }
trEnumerations() [1/2]
virtual QCString TranslatorSlovak::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 410 of file translator_sk.h.
    { return "Enumercie"; }
trEnumerations() [2/2]
virtual QCString TranslatorSlovak::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 410 of file translator_sk.h.
    { return "Enumercie"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorSlovak::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 446 of file translator_sk.h.
    { return "Dokumentcia enumeranch typov"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorSlovak::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 446 of file translator_sk.h.
    { return "Dokumentcia enumeranch typov"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorSlovak::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1492 of file translator_sk.h.
    { return "Dokumentcia enumeranch hodnt"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorSlovak::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1492 of file translator_sk.h.
    { return "Dokumentcia enumeranch hodnt"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorSlovak::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 428 of file translator_sk.h.
    { return "Hodnoty enumerci"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorSlovak::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 428 of file translator_sk.h.
    { return "Hodnoty enumerci"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorSlovak::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1841 of file translator_sk.h.
    { QCString result = "Dokumentcia pre tuto enumerciu bola generovan z ";
      if (single)
          result += "nasledujceho sboru:";
      else
          result += "nasledujcich sborov:";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorSlovak::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1841 of file translator_sk.h.
    { QCString result = "Dokumentcia pre tuto enumerciu bola generovan z ";
      if (single)
          result += "nasledujceho sboru:";
      else
          result += "nasledujcich sborov:";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorSlovak::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 132 of file translator_sk.h.
    { return "meno enumercie"; }
trEnumName() [2/2]
virtual QCString TranslatorSlovak::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 132 of file translator_sk.h.
    { return "meno enumercie"; }
trEnumReference() [1/2]
virtual QCString TranslatorSlovak::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1851 of file translator_sk.h.
    { return "Referencia k enumercii "+QCString(name); }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorSlovak::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1851 of file translator_sk.h.
    { return "Referencia k enumercii "+QCString(name); }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorSlovak::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 136 of file translator_sk.h.
    { return "hodnota enumercie"; }
trEnumValue() [2/2]
virtual QCString TranslatorSlovak::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 136 of file translator_sk.h.
    { return "hodnota enumercie"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorSlovak::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1303 of file translator_sk.h.
    {
      return "Dokumentcia udalost";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorSlovak::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1303 of file translator_sk.h.
    {
      return "Dokumentcia udalost";
    }
trEvents() [1/2]
virtual QCString TranslatorSlovak::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1298 of file translator_sk.h.
    {
      return "Udalosti";
    }
trEvents() [2/2]
virtual QCString TranslatorSlovak::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1298 of file translator_sk.h.
    {
      return "Udalosti";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorSlovak::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 388 of file translator_sk.h.
    { return "Dokumentcia prkladov"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorSlovak::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 388 of file translator_sk.h.
    { return "Dokumentcia prkladov"; }
trExamples() [1/2]
virtual QCString TranslatorSlovak::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 203 of file translator_sk.h.
    { return "Prklady"; }
trExamples() [2/2]
virtual QCString TranslatorSlovak::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 203 of file translator_sk.h.
    { return "Prklady"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorSlovak::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 315 of file translator_sk.h.
    { return "Tu njdete zoznam vetkch prkladov:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorSlovak::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 315 of file translator_sk.h.
    { return "Tu njdete zoznam vetkch prkladov:"; }
trExceptions() [1/2]
virtual QCString TranslatorSlovak::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 518 of file translator_sk.h.
    { return "Vnimky"; }
trExceptions() [2/2]
virtual QCString TranslatorSlovak::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 518 of file translator_sk.h.
    { return "Vnimky"; }
trExtendsClass() [1/2]
virtual QCString TranslatorSlovak::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1891 of file translator_sk.h.
    {
      return "Roziruje triedu @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorSlovak::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1891 of file translator_sk.h.
    {
      return "Roziruje triedu @0.";
    }
trFile() [1/2]
virtual QCString TranslatorSlovak::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1160 of file translator_sk.h.
    {
      QCString result((first_capital ? "Sbor" : "sbor"));
      if (!singular) result+="y";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorSlovak::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1160 of file translator_sk.h.
    {
      QCString result((first_capital ? "Sbor" : "sbor"));
      if (!singular) result+="y";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorSlovak::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 382 of file translator_sk.h.
    { return "Dokumentcia sborov"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorSlovak::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 382 of file translator_sk.h.
    { return "Dokumentcia sborov"; }
trFileIn() [1/2]
virtual QCString TranslatorSlovak::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1741 of file translator_sk.h.
    {
      return "Sbor v "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorSlovak::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1741 of file translator_sk.h.
    {
      return "Sbor v "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorSlovak::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 364 of file translator_sk.h.
    { return "Register sborov"; }
trFileIndex() [2/2]
virtual QCString TranslatorSlovak::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 364 of file translator_sk.h.
    { return "Register sborov"; }
trFileList() [1/2]
virtual QCString TranslatorSlovak::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 169 of file translator_sk.h.
    { return "Zoznam sborov"; }
trFileList() [2/2]
virtual QCString TranslatorSlovak::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 169 of file translator_sk.h.
    { return "Zoznam sborov"; }
trFileListDescription() [1/2]
virtual QCString TranslatorSlovak::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 217 of file translator_sk.h.
    {
        QCString result("Tu njdete zoznam vetkch ");
        if (!extractAll) result+="dokumentovanch ";
        result+="sborov so strunmi popismi:";
        return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorSlovak::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 217 of file translator_sk.h.
    {
        QCString result("Tu njdete zoznam vetkch ");
        if (!extractAll) result+="dokumentovanch ";
        result+="sborov so strunmi popismi:";
        return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorSlovak::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 186 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globlne symboly";
      }
      else
      {
        return "Symboly v sboroch";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorSlovak::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 186 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globlne symboly";
      }
      else
      {
        return "Symboly v sboroch";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorSlovak::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 290 of file translator_sk.h.
    {
      QCString result="Tu njdete zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkci, premennch, makier, enumerci a definci typov (typedef) "
                "s odkazmi na ";
      }
      else
      {
        result+="symbolov, ktor s definovan na rovni svojich sborov. "
                "Pre kad symbol je uveden odkaz na ";
      }
      if (extractAll)
        result+="sbory, ku ktorm prislchaj:";
      else
        result+="dokumentciu:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorSlovak::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 290 of file translator_sk.h.
    {
      QCString result="Tu njdete zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkci, premennch, makier, enumerci a definci typov (typedef) "
                "s odkazmi na ";
      }
      else
      {
        result+="symbolov, ktor s definovan na rovni svojich sborov. "
                "Pre kad symbol je uveden odkaz na ";
      }
      if (extractAll)
        result+="sbory, ku ktorm prislchaj:";
      else
        result+="dokumentciu:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorSlovak::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 583 of file translator_sk.h.
    {
      QCString result("Dokumentcia sboru ");
      result+=fileName;
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorSlovak::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 583 of file translator_sk.h.
    {
      QCString result("Dokumentcia sboru ");
      result+=fileName;
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorSlovak::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 543 of file translator_sk.h.
    { return "Priatelia (friends)"; }
trFriends() [2/2]
virtual QCString TranslatorSlovak::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 543 of file translator_sk.h.
    { return "Priatelia (friends)"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorSlovak::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 452 of file translator_sk.h.
    { return "Dokumentcia funkci"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorSlovak::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 452 of file translator_sk.h.
    { return "Dokumentcia funkci"; }
trFunctions() [1/2]
virtual QCString TranslatorSlovak::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 416 of file translator_sk.h.
    { return "Funkcie"; }
trFunctions() [2/2]
virtual QCString TranslatorSlovak::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 416 of file translator_sk.h.
    { return "Funkcie"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorSlovak::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 479 of file translator_sk.h.
    {
      QCString result="Generovan "+date;
      if (!projName.isEmpty()) result+=" pre projekt "+projName;
      result+=" programom";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorSlovak::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 479 of file translator_sk.h.
    {
      QCString result="Generovan "+date;
      if (!projName.isEmpty()) result+=" pre projekt "+projName;
      result+=" programom";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorSlovak::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 122 of file translator_sk.h.
    { QCString result("Generovan automaticky programom Doxygen "
                      "zo zdrojovch textov");
      if (!s.isEmpty())
          result+=" projektu "+s;
      result+=".";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorSlovak::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 122 of file translator_sk.h.
    { QCString result("Generovan automaticky programom Doxygen "
                      "zo zdrojovch textov");
      if (!s.isEmpty())
          result+=" projektu "+s;
      result+=".";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorSlovak::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 522 of file translator_sk.h.
    { return "Generovan programom"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorSlovak::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 522 of file translator_sk.h.
    { return "Generovan programom"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorSlovak::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 735 of file translator_sk.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentcia pre ";
      switch(compType)
      {
        case ClassDef::Class: result+="tto triedu"; break;
        case ClassDef::Struct: result+="tto truktru (struct)"; break;
        case ClassDef::Union: result+="tento union"; break;
        case ClassDef::Interface: result+="toto rozhranie"; break;
        case ClassDef::Protocol: result+="protokol"; break;
        case ClassDef::Category: result+="kategria"; break;
        case ClassDef::Exception: result+="tto vnimku"; break;
        default: break;
      }
      result+=" bola generovan z ";
      if (single) result+="nasledujceho sboru:";
      else result+="nasledujcich sborov:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorSlovak::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 735 of file translator_sk.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentcia pre ";
      switch(compType)
      {
        case ClassDef::Class: result+="tto triedu"; break;
        case ClassDef::Struct: result+="tto truktru (struct)"; break;
        case ClassDef::Union: result+="tento union"; break;
        case ClassDef::Interface: result+="toto rozhranie"; break;
        case ClassDef::Protocol: result+="protokol"; break;
        case ClassDef::Category: result+="kategria"; break;
        case ClassDef::Exception: result+="tto vnimku"; break;
        default: break;
      }
      result+=" bola generovan z ";
      if (single) result+="nasledujceho sboru:";
      else result+="nasledujcich sborov:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorSlovak::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1651 of file translator_sk.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentcia ";
      switch(compType)
      {
        case ClassDef::Class: result+="k tomuto modulu"; break;
        case ClassDef::Struct: result+="k tomuto typu"; break;
        case ClassDef::Union: result+="k tejto nii"; break;
        case ClassDef::Interface: result+="k tomuto rozhraniu"; break;
        case ClassDef::Protocol: result+="k tomuto protokolu"; break;
        case ClassDef::Category: result+="k tejto kategrii"; break;
        case ClassDef::Exception: result+="k tejto vnimke"; break;
        default: break;
      }
      result+=" bola vygenerovan z ";
      if (single) result+="nasledujceho sboru:";
      else result+="nasledujcich sborov:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorSlovak::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1651 of file translator_sk.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentcia ";
      switch(compType)
      {
        case ClassDef::Class: result+="k tomuto modulu"; break;
        case ClassDef::Struct: result+="k tomuto typu"; break;
        case ClassDef::Union: result+="k tejto nii"; break;
        case ClassDef::Interface: result+="k tomuto rozhraniu"; break;
        case ClassDef::Protocol: result+="k tomuto protokolu"; break;
        case ClassDef::Category: result+="k tejto kategrii"; break;
        case ClassDef::Exception: result+="k tejto vnimke"; break;
        default: break;
      }
      result+=" bola vygenerovan z ";
      if (single) result+="nasledujceho sboru:";
      else result+="nasledujcich sborov:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorSlovak::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1216 of file translator_sk.h.
    {
      QCString result((first_capital ? "Globln" : "globln"));
      result+=(singular ? "y" : "e");
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorSlovak::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1216 of file translator_sk.h.
    {
      QCString result((first_capital ? "Globln" : "globln"));
      result+=(singular ? "y" : "e");
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorSlovak::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1716 of file translator_sk.h.
    {
      return "Globlny priestor mien";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorSlovak::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1716 of file translator_sk.h.
    {
      return "Globlny priestor mien";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorSlovak::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 824 of file translator_sk.h.
    {
      return "Zobrazi dokumentciu tohoto sboru.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorSlovak::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 824 of file translator_sk.h.
    {
      return "Zobrazi dokumentciu tohoto sboru.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorSlovak::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 857 of file translator_sk.h.
    {
      return "Zobrazi grafick podobu hierarchie tried";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorSlovak::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 857 of file translator_sk.h.
    {
      return "Zobrazi grafick podobu hierarchie tried";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorSlovak::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 819 of file translator_sk.h.
    {
      return "Zobrazi zdrojov text tohoto sboru.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorSlovak::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 819 of file translator_sk.h.
    {
      return "Zobrazi zdrojov text tohoto sboru.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorSlovak::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 861 of file translator_sk.h.
    {
      return "Zobrazi textov podobu hierarchie tried";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorSlovak::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 861 of file translator_sk.h.
    {
      return "Zobrazi textov podobu hierarchie tried";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorSlovak::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 853 of file translator_sk.h.
    {
      return "Grafick zobrazenie hierarchie tried";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorSlovak::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 853 of file translator_sk.h.
    {
      return "Grafick zobrazenie hierarchie tried";
    }
trGroup() [1/2]
virtual QCString TranslatorSlovak::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1183 of file translator_sk.h.
    {
      QCString result((first_capital ? "Skupin" : "skupin"));
      result+=(singular ? "a" : "y");
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorSlovak::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1183 of file translator_sk.h.
    {
      QCString result((first_capital ? "Skupin" : "skupin"));
      result+=(singular ? "a" : "y");
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorSlovak::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 343 of file translator_sk.h.
    { return "Register hierarchie tried"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorSlovak::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 343 of file translator_sk.h.
    { return "Register hierarchie tried"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorSlovak::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1254 of file translator_sk.h.
    {
      return "Implementuje " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorSlovak::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1254 of file translator_sk.h.
    {
      return "Implementuje " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorSlovak::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this member.
Implements Translator.
Definition at line 1262 of file translator_sk.h.
    {
      return "Implementovan v " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorSlovak::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this member.
Implements Translator.
Definition at line 1262 of file translator_sk.h.
    {
      return "Implementovan v " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorSlovak::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 953 of file translator_sk.h.
    {
      return "Nasledujci graf ukazuje, ktor sbory priamo alebo "
             "nepriamo vkladaj tento sbor:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorSlovak::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 953 of file translator_sk.h.
    {
      return "Nasledujci graf ukazuje, ktor sbory priamo alebo "
             "nepriamo vkladaj tento sbor:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorSlovak::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 808 of file translator_sk.h.
    {
      return "Graf zvislost na vkladanch sboroch "
                    "pre "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorSlovak::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 808 of file translator_sk.h.
    {
      return "Graf zvislost na vkladanch sboroch "
                    "pre "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorSlovak::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1750 of file translator_sk.h.
    {
      return "Vklad (include) sbor z "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorSlovak::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1750 of file translator_sk.h.
    {
      return "Vklad (include) sbor z "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorSlovak::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 116 of file translator_sk.h.
    { return ", vrtane vetkch zdedench lenov."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorSlovak::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 116 of file translator_sk.h.
    { return ", vrtane vetkch zdedench lenov."; }
trInheritedByList() [1/2]
virtual QCString TranslatorSlovak::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 659 of file translator_sk.h.
    {
      QCString result("Zdeden ");
      result += (numEntries == 1) ? "triedou " : "triedami ";
      result += trWriteList(numEntries)+".";
      return result;
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorSlovak::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 659 of file translator_sk.h.
    {
      QCString result("Zdeden ");
      result += (numEntries == 1) ? "triedou " : "triedami ";
      result += trWriteList(numEntries)+".";
      return result;
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorSlovak::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1855 of file translator_sk.h.
    { return QCString(members)+" ded sa z "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorSlovak::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1855 of file translator_sk.h.
    { return QCString(members)+" ded sa z "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorSlovak::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 648 of file translator_sk.h.
    {
      QCString result("Ded od ");
      result += (numEntries == 1) ? "bzovej triedy " : "bzovch tried ";
      result += trWriteList(numEntries)+".";
      return result;
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorSlovak::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 648 of file translator_sk.h.
    {
      QCString result("Ded od ");
      result += (numEntries == 1) ? "bzovej triedy " : "bzovch tried ";
      result += trWriteList(numEntries)+".";
      return result;
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorSlovak::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 844 of file translator_sk.h.
    {
      return "Inicializtor:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorSlovak::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 844 of file translator_sk.h.
    {
      return "Inicializtor:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorSlovak::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1907 of file translator_sk.h.
    {
      return "Metdy intancie";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorSlovak::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1907 of file translator_sk.h.
    {
      return "Metdy intancie";
    }
trInterfaces() [1/2]
virtual QCString TranslatorSlovak::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1924 of file translator_sk.h.
    { return "Exportovan rozhrania"; }
trInterfaces() [2/2]
virtual QCString TranslatorSlovak::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1924 of file translator_sk.h.
    { return "Exportovan rozhrania"; }
trInvariant() [1/2]
virtual QCString TranslatorSlovak::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 839 of file translator_sk.h.
    {
      return "Invariant";
    }
trInvariant() [2/2]
virtual QCString TranslatorSlovak::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 839 of file translator_sk.h.
    {
      return "Invariant";
    }
trISOLang() [1/2]
virtual QCString TranslatorSlovak::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 52 of file translator_sk.h.
    {
      return "sk";
    }
trISOLang() [2/2]
virtual QCString TranslatorSlovak::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 52 of file translator_sk.h.
    {
      return "sk";
    }
trLegend() [1/2]
virtual QCString TranslatorSlovak::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1042 of file translator_sk.h.
    {
      return "vysvetlivky";
    }
trLegend() [2/2]
virtual QCString TranslatorSlovak::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1042 of file translator_sk.h.
    {
      return "vysvetlivky";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorSlovak::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 973 of file translator_sk.h.
    {
      return
        "Tu njdete vysvetlenie, ako maj by interpretovan grafy, "
        "ktor boli generovan programom doxygen.<p>\n"
        "Uvaujte nasledujci prklad:\n"
        "\\code\n"
        "/*! Neviditeln trieda, ktor sa v grafe nezobrazuje, pretoe "
        "dolo k orezaniu grafu. */\n"
        "class Invisible { };\n\n"
        "/*! Trieda, u ktorej dolo k orezaniu grafu. Vzah dedinosti "
        "je skryt. */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Trieda, ktor nieje dokumentovan komentrmi programu doxygen. */\n"
        "class Undocumented { };\n\n"
        "/*! Odvoden trieda s verejnm (public) dedenm bzovej triedy. */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! ablna triedy. */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Odvoden trieda s chrnenm (protected) dedenm bzovej triedy. */\n"
        "class ProtectedBase { };\n\n"
        "/*! Odvoden trieda s privtnym dedenm bzovej triedy. */\n"
        "class PrivateBase { };\n\n"
        "/*! Trieda, ktor je vyuvan triedou Inherited. */\n"
        "class Used { };\n\n"
        "/*! Odvoden trieda, ktor rznym spsobom ded od viacerch bzovch "
        "tried. */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "K vyie uvedenmu bude vygenerovan nasledujci graf:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Bloky (tj. uzly) v uvedenom grafe maj nasledujci vznam:\n"
        "<ul>\n"
        "<li>ierne vyplnen obdnik reprezentuje truktru alebo triedu, "
            "pre ktor bol graf generovan.\n"
        "<li>Obdnik s iernym obrysom oznauje dokumentovan "
            "truktru alebo triedu.\n"
        "<li>Obdnik so edm obrysom oznauje nedokumentovan "
            "truktru alebo triedu.\n"
        "<li>Obdnik s ervenm obrysom oznauje dokumentovan "
            "truktru alebo triedu, pre ktor\n"
            "nies zobrazen vetky vzahy dedinosti alebo obsiahnutia. "
            "Graf je orezan v prpade, kedy ho\n"
            "nieje mon umiestni do vymedzench hranc.\n"
        "</ul>\n"
        "pky (tj. hrany grafu) maj nasledujc vznam:\n"
        "<ul>\n"
        "<li>Tmavo modr pka sa pouva pre oznaenie vzahu verejnej "
            "dedinosti medzi dvoma triedami.\n"
        "<li>Tmavo zelen pka oznauje vzah chrnenej dedinosti "
            "(protected).\n"
        "<li>Tmavo erven pka oznauje vzah privtnej dedinosti.\n"
        "<li>Purpurov pka kreslen iarkovane sa pouva v prpade, "
            "ak je trieda obsiahnut v inej triede,\n"
            "alebo ak je pouvan inou triedou. Je oznaen identifiktorom "
            "jednej alebo viacerch premennch (objektov), cez ktor\n"
            "je trieda alebo truktra zprstupnena.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorSlovak::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 973 of file translator_sk.h.
    {
      return
        "Tu njdete vysvetlenie, ako maj by interpretovan grafy, "
        "ktor boli generovan programom doxygen.<p>\n"
        "Uvaujte nasledujci prklad:\n"
        "\\code\n"
        "/*! Neviditeln trieda, ktor sa v grafe nezobrazuje, pretoe "
        "dolo k orezaniu grafu. */\n"
        "class Invisible { };\n\n"
        "/*! Trieda, u ktorej dolo k orezaniu grafu. Vzah dedinosti "
        "je skryt. */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Trieda, ktor nieje dokumentovan komentrmi programu doxygen. */\n"
        "class Undocumented { };\n\n"
        "/*! Odvoden trieda s verejnm (public) dedenm bzovej triedy. */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! ablna triedy. */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Odvoden trieda s chrnenm (protected) dedenm bzovej triedy. */\n"
        "class ProtectedBase { };\n\n"
        "/*! Odvoden trieda s privtnym dedenm bzovej triedy. */\n"
        "class PrivateBase { };\n\n"
        "/*! Trieda, ktor je vyuvan triedou Inherited. */\n"
        "class Used { };\n\n"
        "/*! Odvoden trieda, ktor rznym spsobom ded od viacerch bzovch "
        "tried. */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "K vyie uvedenmu bude vygenerovan nasledujci graf:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Bloky (tj. uzly) v uvedenom grafe maj nasledujci vznam:\n"
        "<ul>\n"
        "<li>ierne vyplnen obdnik reprezentuje truktru alebo triedu, "
            "pre ktor bol graf generovan.\n"
        "<li>Obdnik s iernym obrysom oznauje dokumentovan "
            "truktru alebo triedu.\n"
        "<li>Obdnik so edm obrysom oznauje nedokumentovan "
            "truktru alebo triedu.\n"
        "<li>Obdnik s ervenm obrysom oznauje dokumentovan "
            "truktru alebo triedu, pre ktor\n"
            "nies zobrazen vetky vzahy dedinosti alebo obsiahnutia. "
            "Graf je orezan v prpade, kedy ho\n"
            "nieje mon umiestni do vymedzench hranc.\n"
        "</ul>\n"
        "pky (tj. hrany grafu) maj nasledujc vznam:\n"
        "<ul>\n"
        "<li>Tmavo modr pka sa pouva pre oznaenie vzahu verejnej "
            "dedinosti medzi dvoma triedami.\n"
        "<li>Tmavo zelen pka oznauje vzah chrnenej dedinosti "
            "(protected).\n"
        "<li>Tmavo erven pka oznauje vzah privtnej dedinosti.\n"
        "<li>Purpurov pka kreslen iarkovane sa pouva v prpade, "
            "ak je trieda obsiahnut v inej triede,\n"
            "alebo ak je pouvan inou triedou. Je oznaen identifiktorom "
            "jednej alebo viacerch premennch (objektov), cez ktor\n"
            "je trieda alebo truktra zprstupnena.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorSlovak::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 968 of file translator_sk.h.
    {
      return "Vysvetlivky ku grafu";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorSlovak::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 968 of file translator_sk.h.
    {
      return "Vysvetlivky ku grafu";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorSlovak::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 104 of file translator_sk.h.
    { return "Zoznam vetkch lenov"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorSlovak::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 104 of file translator_sk.h.
    { return "Zoznam vetkch lenov"; }
trLoading() [1/2]
virtual QCString TranslatorSlovak::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1710 of file translator_sk.h.
    {
      return "Natam...";
    }
trLoading() [2/2]
virtual QCString TranslatorSlovak::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1710 of file translator_sk.h.
    {
      return "Natam...";
    }
trMainPage() [1/2]
virtual QCString TranslatorSlovak::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 767 of file translator_sk.h.
    { return "Hlavn strnka"; }
trMainPage() [2/2]
virtual QCString TranslatorSlovak::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 767 of file translator_sk.h.
    { return "Hlavn strnka"; }
trMember() [1/2]
virtual QCString TranslatorSlovak::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1205 of file translator_sk.h.
    {
      QCString result((first_capital ? "len" : "len"));
      if (!singular) result+="y";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorSlovak::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1205 of file translator_sk.h.
    {
      QCString result((first_capital ? "len" : "len"));
      if (!singular) result+="y";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorSlovak::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 87 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentcia k polokm";
      }
      else
      {
        return "Dokumentcia k dtovm lenom";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorSlovak::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 87 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentcia k polokm";
      }
      else
      {
        return "Dokumentcia k dtovm lenom";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorSlovak::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 79 of file translator_sk.h.
    { return "Dokumentcia k lenskm enumercim"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorSlovak::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 79 of file translator_sk.h.
    { return "Dokumentcia k lenskm enumercim"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorSlovak::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 83 of file translator_sk.h.
    { return "Dokumentcia k metdam"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorSlovak::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 83 of file translator_sk.h.
    { return "Dokumentcia k metdam"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorSlovak::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1501 of file translator_sk.h.
    { return "Dokumentcia lenskch funkci/podprogramov"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorSlovak::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1501 of file translator_sk.h.
    { return "Dokumentcia lenskch funkci/podprogramov"; }
trMemberList() [1/2]
virtual QCString TranslatorSlovak::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 108 of file translator_sk.h.
    { return "Zoznam lenov triedy"; }
trMemberList() [2/2]
virtual QCString TranslatorSlovak::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 108 of file translator_sk.h.
    { return "Zoznam lenov triedy"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorSlovak::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 75 of file translator_sk.h.
    { return "Dokumentcia k lenskm typom"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorSlovak::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 75 of file translator_sk.h.
    { return "Dokumentcia k lenskm typom"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorSlovak::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1914 of file translator_sk.h.
    {
      return "Dokumentcia metdy";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorSlovak::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1914 of file translator_sk.h.
    {
      return "Dokumentcia metdy";
    }
trModule() [1/2]
virtual QCString TranslatorSlovak::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1642 of file translator_sk.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="y";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorSlovak::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1642 of file translator_sk.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="y";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorSlovak::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 370 of file translator_sk.h.
    { return "Dokumentcia modulov"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorSlovak::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 370 of file translator_sk.h.
    { return "Dokumentcia modulov"; }
trModuleIndex() [1/2]
virtual QCString TranslatorSlovak::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 337 of file translator_sk.h.
    { return "Register modulov"; }
trModuleIndex() [2/2]
virtual QCString TranslatorSlovak::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 337 of file translator_sk.h.
    { return "Register modulov"; }
trModuleReference() [1/2]
virtual QCString TranslatorSlovak::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1604 of file translator_sk.h.
    {
      QCString result="Dokumentcia modulu ";
      result += namespaceName;
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorSlovak::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1604 of file translator_sk.h.
    {
      QCString result="Dokumentcia modulu ";
      result += namespaceName;
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorSlovak::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 148 of file translator_sk.h.
    { return "Moduly"; }
trModules() [2/2]
virtual QCString TranslatorSlovak::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 148 of file translator_sk.h.
    { return "Moduly"; }
trModulesDescription() [1/2]
virtual QCString TranslatorSlovak::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 325 of file translator_sk.h.
    { return "Tu njdete zoznam vetkch modulov:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorSlovak::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 325 of file translator_sk.h.
    { return "Tu njdete zoznam vetkch modulov:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorSlovak::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1635 of file translator_sk.h.
    { return "Register modulov"; }
trModulesIndex() [2/2]
virtual QCString TranslatorSlovak::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1635 of file translator_sk.h.
    { return "Register modulov"; }
trModulesList() [1/2]
virtual QCString TranslatorSlovak::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1569 of file translator_sk.h.
    { return "Zoznam modulov"; }
trModulesList() [2/2]
virtual QCString TranslatorSlovak::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1569 of file translator_sk.h.
    { return "Zoznam modulov"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorSlovak::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1573 of file translator_sk.h.
    {
      QCString result="Nasleduje zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      result+="modulov so strunmi popismi:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorSlovak::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1573 of file translator_sk.h.
    {
      QCString result="Nasleduje zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      result+="modulov so strunmi popismi:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorSlovak::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1616 of file translator_sk.h.
    {
      QCString result="Nasleduje zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      result+="ast modulov s odkazmi ";
      if (extractAll)
      {
        result+="na dokumentciu modulov pre dan as:";
      }
      else
      {
        result+="na moduly, ku ktorm as patr:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorSlovak::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1616 of file translator_sk.h.
    {
      QCString result="Nasleduje zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      result+="ast modulov s odkazmi ";
      if (extractAll)
      {
        result+="na dokumentciu modulov pre dan as:";
      }
      else
      {
        result+="na moduly, ku ktorm as patr:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorSlovak::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1612 of file translator_sk.h.
    { return "asti modulu"; }
trModulesMembers() [2/2]
virtual QCString TranslatorSlovak::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1612 of file translator_sk.h.
    { return "asti modulu"; }
trMonth() [1/2]
virtual QCString TranslatorSlovak::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1789 of file translator_sk.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "mj", "jn", "jl", "aug", "sep", "okt", "nov", "dec" };
      static const char *months_full[] = { "janur", "februr", "marec", "aprl", "mj", "jn", "jl", "august", "september", "oktber", "november", "december" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorSlovak::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1789 of file translator_sk.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "mj", "jn", "jl", "aug", "sep", "okt", "nov", "dec" };
      static const char *months_full[] = { "janur", "februr", "marec", "aprl", "mj", "jn", "jl", "august", "september", "oktber", "november", "december" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorSlovak::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 100 of file translator_sk.h.
    { return "..."; }
trMore() [2/2]
virtual QCString TranslatorSlovak::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 100 of file translator_sk.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorSlovak::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1171 of file translator_sk.h.
    {
      QCString result((first_capital ? "Priestor" : "priestor"));
      if (!singular) result+="y";
      result+=" mien";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorSlovak::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1171 of file translator_sk.h.
    {
      QCString result((first_capital ? "Priestor" : "priestor"));
      if (!singular) result+="y";
      result+=" mien";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorSlovak::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 715 of file translator_sk.h.
    { return "Dokumentcia priestorov mien"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorSlovak::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 715 of file translator_sk.h.
    { return "Dokumentcia priestorov mien"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorSlovak::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 709 of file translator_sk.h.
    { return "Register priestorov mien"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorSlovak::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 709 of file translator_sk.h.
    { return "Register priestorov mien"; }
trNamespaceList() [1/2]
virtual QCString TranslatorSlovak::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 528 of file translator_sk.h.
    { return "Zoznam priestorov mien"; }
trNamespaceList() [2/2]
virtual QCString TranslatorSlovak::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 528 of file translator_sk.h.
    { return "Zoznam priestorov mien"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorSlovak::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 532 of file translator_sk.h.
    {
      QCString result="Tu njdete zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      result+="priestorov mien so strunm popisom:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorSlovak::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 532 of file translator_sk.h.
    {
      QCString result="Tu njdete zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      result+="priestorov mien so strunm popisom:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorSlovak::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 694 of file translator_sk.h.
    {
      QCString result="Tu njdete zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      result+="symbolov, ktor s definovan vo svojich priestoroch mien. "
              "U kadho je uveden odkaz na ";
      if (extractAll)
        result+="dokumentciu prslunho priestoru mien:";
      else
        result+="prslun priestor mien:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorSlovak::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 694 of file translator_sk.h.
    {
      QCString result="Tu njdete zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      result+="symbolov, ktor s definovan vo svojich priestoroch mien. "
              "U kadho je uveden odkaz na ";
      if (extractAll)
        result+="dokumentciu prslunho priestoru mien:";
      else
        result+="prslun priestor mien:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorSlovak::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 690 of file translator_sk.h.
    { return "Symboly v priestoroch mien"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorSlovak::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 690 of file translator_sk.h.
    { return "Symboly v priestoroch mien"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorSlovak::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 591 of file translator_sk.h.
    {
      QCString result("Dokumentcia priestoru mien ");
      result+=namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorSlovak::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 591 of file translator_sk.h.
    {
      QCString result("Dokumentcia priestoru mien ");
      result+=namespaceName;
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorSlovak::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 725 of file translator_sk.h.
    { return "Priestory mien"; }
trNamespaces() [2/2]
virtual QCString TranslatorSlovak::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 725 of file translator_sk.h.
    { return "Priestory mien"; }
trNoMatches() [1/2]
virtual QCString TranslatorSlovak::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1728 of file translator_sk.h.
    {
      return "Ni sa nenalo";
    }
trNoMatches() [2/2]
virtual QCString TranslatorSlovak::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1728 of file translator_sk.h.
    {
      return "Ni sa nenalo";
    }
trNote() [1/2]
virtual QCString TranslatorSlovak::trNote () [inline], [virtual]
Implements Translator.
Definition at line 874 of file translator_sk.h.
    {
      return "Poznmka";
    }
trNote() [2/2]
virtual QCString TranslatorSlovak::trNote () [inline], [virtual]
Implements Translator.
Definition at line 874 of file translator_sk.h.
    {
      return "Poznmka";
    }
trOverloadText() [1/2]
virtual QCString TranslatorSlovak::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1474 of file translator_sk.h.
    {
       return "Ide o preaen (overloaded) metdu, "
              "ktor m uahi pouvanie. Od vyie uvedenej metdy sa odliuje "
              "iba inak zadvanmi argumentami.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorSlovak::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1474 of file translator_sk.h.
    {
       return "Ide o preaen (overloaded) metdu, "
              "ktor m uahi pouvanie. Od vyie uvedenej metdy sa odliuje "
              "iba inak zadvanmi argumentami.";
    }
trPackage() [1/2]
virtual QCString TranslatorSlovak::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1087 of file translator_sk.h.
    {
      return "Balk "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorSlovak::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1087 of file translator_sk.h.
    {
      return "Balk "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorSlovak::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1339 of file translator_sk.h.
    {
      return "Atribty balku";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorSlovak::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1339 of file translator_sk.h.
    {
      return "Atribty balku";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorSlovak::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1321 of file translator_sk.h.
    {
      return "Funkcie v balku";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorSlovak::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1321 of file translator_sk.h.
    {
      return "Funkcie v balku";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorSlovak::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1092 of file translator_sk.h.
    {
      return "Tu njdete zoznam balkov so strunm popisom "
             "(pokia bol uveden):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorSlovak::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1092 of file translator_sk.h.
    {
      return "Tu njdete zoznam balkov so strunm popisom "
             "(pokia bol uveden):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorSlovak::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1325 of file translator_sk.h.
    {
      return "leny v balku";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorSlovak::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1325 of file translator_sk.h.
    {
      return "leny v balku";
    }
trPackages() [1/2]
virtual QCString TranslatorSlovak::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1098 of file translator_sk.h.
    {
      return "Balky";
    }
trPackages() [2/2]
virtual QCString TranslatorSlovak::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1098 of file translator_sk.h.
    {
      return "Balky";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorSlovak::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1314 of file translator_sk.h.
    {
      return "Typy v balku";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorSlovak::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1314 of file translator_sk.h.
    {
      return "Typy v balku";
    }
trPage() [1/2]
virtual QCString TranslatorSlovak::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1194 of file translator_sk.h.
    {
      QCString result((first_capital ? "Strnk" : "strnk"));
      result+=(singular ? "a" : "y");
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorSlovak::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1194 of file translator_sk.h.
    {
      QCString result((first_capital ? "Strnk" : "strnk"));
      result+=(singular ? "a" : "y");
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorSlovak::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 773 of file translator_sk.h.
    { return "s."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorSlovak::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 773 of file translator_sk.h.
    { return "s."; }
trPageIndex() [1/2]
virtual QCString TranslatorSlovak::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 865 of file translator_sk.h.
    {
      return "Register strnok";
    }
trPageIndex() [2/2]
virtual QCString TranslatorSlovak::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 865 of file translator_sk.h.
    {
      return "Register strnok";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorSlovak::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1872 of file translator_sk.h.
    {
      QCString opt = enable ? "povoli" : "zakza";
      return opt + " synchronizciu panelov";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorSlovak::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1872 of file translator_sk.h.
    {
      QCString opt = enable ? "povoli" : "zakza";
      return opt + " synchronizciu panelov";
    }
trParameters() [1/2]
virtual QCString TranslatorSlovak::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 514 of file translator_sk.h.
    { return "Parametre"; }
trParameters() [2/2]
virtual QCString TranslatorSlovak::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 514 of file translator_sk.h.
    { return "Parametre"; }
trPostcondition() [1/2]
virtual QCString TranslatorSlovak::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 834 of file translator_sk.h.
    {
      return "Postpodmienka";
    }
trPostcondition() [2/2]
virtual QCString TranslatorSlovak::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 834 of file translator_sk.h.
    {
      return "Postpodmienka";
    }
trPrecondition() [1/2]
virtual QCString TranslatorSlovak::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 829 of file translator_sk.h.
    {
      return "Prepodmienka";
    }
trPrecondition() [2/2]
virtual QCString TranslatorSlovak::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 829 of file translator_sk.h.
    {
      return "Prepodmienka";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorSlovak::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 913 of file translator_sk.h.
    {
      return "Privtne atribty";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorSlovak::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 913 of file translator_sk.h.
    {
      return "Privtne atribty";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorSlovak::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 613 of file translator_sk.h.
    { return "Privtne metdy"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorSlovak::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 613 of file translator_sk.h.
    { return "Privtne metdy"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorSlovak::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 615 of file translator_sk.h.
    { return "Privtne sloty"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorSlovak::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 615 of file translator_sk.h.
    { return "Privtne sloty"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorSlovak::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 909 of file translator_sk.h.
    {
      return "Privtne typy";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorSlovak::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 909 of file translator_sk.h.
    {
      return "Privtne typy";
    }
trProperties() [1/2]
virtual QCString TranslatorSlovak::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1068 of file translator_sk.h.
    {
      return "Vlastnosti";
    }
trProperties() [2/2]
virtual QCString TranslatorSlovak::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1068 of file translator_sk.h.
    {
      return "Vlastnosti";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorSlovak::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1073 of file translator_sk.h.
    {
      return "Dokumentcia k vlastnosti";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorSlovak::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1073 of file translator_sk.h.
    {
      return "Dokumentcia k vlastnosti";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorSlovak::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 901 of file translator_sk.h.
    {
      return "Chrnen atribty";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorSlovak::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 901 of file translator_sk.h.
    {
      return "Chrnen atribty";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorSlovak::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 607 of file translator_sk.h.
    { return "Chrnen metdy"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorSlovak::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 607 of file translator_sk.h.
    { return "Chrnen metdy"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorSlovak::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 609 of file translator_sk.h.
    { return "Chrnen sloty"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorSlovak::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 609 of file translator_sk.h.
    { return "Chrnen sloty"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorSlovak::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_sk.h.
    {
      return "Chrnen typy";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorSlovak::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_sk.h.
    {
      return "Chrnen typy";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorSlovak::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1882 of file translator_sk.h.
    {
      return "Deklarovan v kategrii @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorSlovak::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1882 of file translator_sk.h.
    {
      return "Deklarovan v kategrii @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorSlovak::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 882 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dtov poloky";
      }
      else
      {
        return "Verejn atribty";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorSlovak::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 882 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dtov poloky";
      }
      else
      {
        return "Verejn atribty";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorSlovak::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 599 of file translator_sk.h.
    { return "Verejn metdy"; }
trPublicMembers() [2/2]
virtual QCString TranslatorSlovak::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 599 of file translator_sk.h.
    { return "Verejn metdy"; }
trPublicSlots() [1/2]
virtual QCString TranslatorSlovak::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 601 of file translator_sk.h.
    { return "Verejn sloty"; }
trPublicSlots() [2/2]
virtual QCString TranslatorSlovak::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 601 of file translator_sk.h.
    { return "Verejn sloty"; }
trPublicTypes() [1/2]
virtual QCString TranslatorSlovak::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 878 of file translator_sk.h.
    {
      return "Verejn typy";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorSlovak::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 878 of file translator_sk.h.
    {
      return "Verejn typy";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorSlovak::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 941 of file translator_sk.h.
    {
      return "Pouva sa v";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorSlovak::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 941 of file translator_sk.h.
    {
      return "Pouva sa v";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorSlovak::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 392 of file translator_sk.h.
    { return "Referenn prruka"; }
trReferenceManual() [2/2]
virtual QCString TranslatorSlovak::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 392 of file translator_sk.h.
    { return "Referenn prruka"; }
trReferences() [1/2]
virtual QCString TranslatorSlovak::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1242 of file translator_sk.h.
    {
      return "Odkazuje sa na";
    }
trReferences() [2/2]
virtual QCString TranslatorSlovak::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1242 of file translator_sk.h.
    {
      return "Odkazuje sa na";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorSlovak::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 670 of file translator_sk.h.
    {
      QCString result("Reimplementuje ");
      result += (numEntries == 1) ? "metdu triedy " : "metdy tried ";
      result += trWriteList(numEntries)+".";
      return result;
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorSlovak::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 670 of file translator_sk.h.
    {
      QCString result("Reimplementuje ");
      result += (numEntries == 1) ? "metdu triedy " : "metdy tried ";
      result += trWriteList(numEntries)+".";
      return result;
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorSlovak::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 681 of file translator_sk.h.
    {
      QCString result("Reimplementovan ");
      result += (numEntries == 1) ? "triedou " : "triedami ";
      result += trWriteList(numEntries)+".";
      return result;
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorSlovak::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 681 of file translator_sk.h.
    {
      QCString result("Reimplementovan ");
      result += (numEntries == 1) ? "triedou " : "triedami ";
      result += trWriteList(numEntries)+".";
      return result;
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorSlovak::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 553 of file translator_sk.h.
    { return "Dokumentcia k priateom (friends)"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorSlovak::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 553 of file translator_sk.h.
    { return "Dokumentcia k priateom (friends)"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorSlovak::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 63 of file translator_sk.h.
    { return "Svisiace funkcie"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorSlovak::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 63 of file translator_sk.h.
    { return "Svisiace funkcie"; }
trRelatedPages() [1/2]
virtual QCString TranslatorSlovak::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 199 of file translator_sk.h.
    { return "Ostatn strnky"; }
trRelatedPages() [2/2]
virtual QCString TranslatorSlovak::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 199 of file translator_sk.h.
    { return "Ostatn strnky"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorSlovak::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 319 of file translator_sk.h.
    { return "Nasledujci zoznam odkazuje na alie strnky projektu, "
             "ktor maj charakter usporiadanch zoznamov informci, "
             "pozbieranch z rznych miest v zdrojovch sboroch:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorSlovak::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 319 of file translator_sk.h.
    { return "Nasledujci zoznam odkazuje na alie strnky projektu, "
             "ktor maj charakter usporiadanch zoznamov informci, "
             "pozbieranch z rznych miest v zdrojovch sboroch:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorSlovak::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 67 of file translator_sk.h.
    { return "(Uveden funkcie nies lenskmi funkciami.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorSlovak::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 67 of file translator_sk.h.
    { return "(Uveden funkcie nies lenskmi funkciami.)"; }
trRemarks() [1/2]
virtual QCString TranslatorSlovak::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 945 of file translator_sk.h.
    {
      return "Poznmky";
    }
trRemarks() [2/2]
virtual QCString TranslatorSlovak::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 945 of file translator_sk.h.
    {
      return "Poznmky";
    }
trReturns() [1/2]
virtual QCString TranslatorSlovak::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 506 of file translator_sk.h.
    { return "Nvratov hodnota"; }
trReturns() [2/2]
virtual QCString TranslatorSlovak::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 506 of file translator_sk.h.
    { return "Nvratov hodnota"; }
trReturnValues() [1/2]
virtual QCString TranslatorSlovak::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 762 of file translator_sk.h.
    { return "Nvratov hodnoty"; }
trReturnValues() [2/2]
virtual QCString TranslatorSlovak::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 762 of file translator_sk.h.
    { return "Nvratov hodnoty"; }
trRTFansicp() [1/2]
virtual QCString TranslatorSlovak::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1128 of file translator_sk.h.
    {
      return "1250";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorSlovak::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1128 of file translator_sk.h.
    {
      return "1250";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorSlovak::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1134 of file translator_sk.h.
    {
      return "238";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorSlovak::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1134 of file translator_sk.h.
    {
      return "238";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorSlovak::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1140 of file translator_sk.h.
    {
      return "Index";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorSlovak::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1140 of file translator_sk.h.
    {
      return "Index";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorSlovak::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1274 of file translator_sk.h.
    {
      return "Obsah";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorSlovak::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1274 of file translator_sk.h.
    {
      return "Obsah";
    }
trSearch() [1/2]
virtual QCString TranslatorSlovak::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 207 of file translator_sk.h.
    { return "Hada"; }
trSearch() [2/2]
virtual QCString TranslatorSlovak::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 207 of file translator_sk.h.
    { return "Hada"; }
trSearching() [1/2]
virtual QCString TranslatorSlovak::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1722 of file translator_sk.h.
    {
      return "Vyhadvam...";
    }
trSearching() [2/2]
virtual QCString TranslatorSlovak::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1722 of file translator_sk.h.
    {
      return "Vyhadvam...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorSlovak::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1406 of file translator_sk.h.
    {
      return "Njden slov:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorSlovak::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1406 of file translator_sk.h.
    {
      return "Njden slov:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorSlovak::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1387 of file translator_sk.h.
    {
      if (numDocuments==0)
      {
        return "utujem. Vmu dotazu neodpoved iadny dokument.";
      }
      else if (numDocuments==1)
      {
        return "Bol njden jedin dokument, ktor vyhovuje vmu dotazu.";
      }
      else
      {
        return "Bolo njdench <b>$num</b> dokumentov, ktor vyhovuj vmu "
                      "dotazu. Najviac odpovedajce dokumenty s ako prv.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorSlovak::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1387 of file translator_sk.h.
    {
      if (numDocuments==0)
      {
        return "utujem. Vmu dotazu neodpoved iadny dokument.";
      }
      else if (numDocuments==1)
      {
        return "Bol njden jedin dokument, ktor vyhovuje vmu dotazu.";
      }
      else
      {
        return "Bolo njdench <b>$num</b> dokumentov, ktor vyhovuj vmu "
                      "dotazu. Najviac odpovedajce dokumenty s ako prv.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorSlovak::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1375 of file translator_sk.h.
    {
      return "Vsledky vyhadvania";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorSlovak::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1375 of file translator_sk.h.
    {
      return "Vsledky vyhadvania";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorSlovak::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 510 of file translator_sk.h.
    { return "Viz tie"; }
trSeeAlso() [2/2]
virtual QCString TranslatorSlovak::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 510 of file translator_sk.h.
    { return "Viz tie"; }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorSlovak::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1957 of file translator_sk.h.
    {
      // single is true implies a single file
      QCString result="Dokumentcia k tejto slube bola vygenerovan ";
      if (single) result+="z nasledujceho sboru:";
      else result+="z nasledujcich sborov:";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorSlovak::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1957 of file translator_sk.h.
    {
      // single is true implies a single file
      QCString result="Dokumentcia k tejto slube bola vygenerovan ";
      if (single) result+="z nasledujceho sboru:";
      else result+="z nasledujcich sborov:";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorSlovak::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1943 of file translator_sk.h.
    {
      QCString result="Popis sluby ";
      result += sName;
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorSlovak::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1943 of file translator_sk.h.
    {
      QCString result="Popis sluby ";
      result += sName;
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorSlovak::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1928 of file translator_sk.h.
    { return "Zalenen sluby"; }
trServices() [2/2]
virtual QCString TranslatorSlovak::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1928 of file translator_sk.h.
    { return "Zalenen sluby"; }
trSignals() [1/2]
virtual QCString TranslatorSlovak::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 603 of file translator_sk.h.
    { return "Signly"; }
trSignals() [2/2]
virtual QCString TranslatorSlovak::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 603 of file translator_sk.h.
    { return "Signly"; }
trSince() [1/2]
virtual QCString TranslatorSlovak::trSince () [inline], [virtual]
Implements Translator.
Definition at line 958 of file translator_sk.h.
    {
      return "Od";
    }
trSince() [2/2]
virtual QCString TranslatorSlovak::trSince () [inline], [virtual]
Implements Translator.
Definition at line 958 of file translator_sk.h.
    {
      return "Od";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorSlovak::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1966 of file translator_sk.h.
    {
      // single is true implies a single file
      QCString result="Dokumentcia k tomuto singletonu bola vygenerovan ";
      if (single) result+="z nasledujceho sboru:";
      else result+="z nasledujcich sborov:";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorSlovak::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1966 of file translator_sk.h.
    {
      // single is true implies a single file
      QCString result="Dokumentcia k tomuto singletonu bola vygenerovan ";
      if (single) result+="z nasledujceho sboru:";
      else result+="z nasledujcich sborov:";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorSlovak::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1950 of file translator_sk.h.
    {
      QCString result="Popis singletonu ";
      result += sName;
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorSlovak::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1950 of file translator_sk.h.
    {
      QCString result="Popis singletonu ";
      result += sName;
      return result;
    }
trSourceFile() [1/2]
virtual QCString TranslatorSlovak::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1417 of file translator_sk.h.
    {
      return QCString("Zdrojov sbor ") + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorSlovak::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1417 of file translator_sk.h.
    {
      return QCString("Zdrojov sbor ") + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorSlovak::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1346 of file translator_sk.h.
    {
      return "Statick atribty balku";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorSlovak::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1346 of file translator_sk.h.
    {
      return "Statick atribty balku";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorSlovak::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1332 of file translator_sk.h.
    {
      return "Statick funkcie v balku";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorSlovak::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1332 of file translator_sk.h.
    {
      return "Statick funkcie v balku";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorSlovak::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 917 of file translator_sk.h.
    {
      return "Statick privtne atribty";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorSlovak::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 917 of file translator_sk.h.
    {
      return "Statick privtne atribty";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorSlovak::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 617 of file translator_sk.h.
    { return "Statick privtne metdy"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorSlovak::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 617 of file translator_sk.h.
    { return "Statick privtne metdy"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorSlovak::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 905 of file translator_sk.h.
    {
      return "Statick chrnen atribty";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorSlovak::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 905 of file translator_sk.h.
    {
      return "Statick chrnen atribty";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorSlovak::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 611 of file translator_sk.h.
    { return "Statick chrnen metdy"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorSlovak::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 611 of file translator_sk.h.
    { return "Statick chrnen metdy"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorSlovak::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_sk.h.
    {
      return "Statick verejn atribty";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorSlovak::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_sk.h.
    {
      return "Statick verejn atribty";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorSlovak::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 605 of file translator_sk.h.
    { return "Statick verejn metdy"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorSlovak::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 605 of file translator_sk.h.
    { return "Statick verejn metdy"; }
trSubprogram() [1/2]
virtual QCString TranslatorSlovak::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1686 of file translator_sk.h.
    {
      QCString result((first_capital ? "Podprogram" : "podprogram"));
      if (!singular) result+="y";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorSlovak::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1686 of file translator_sk.h.
    {
      QCString result((first_capital ? "Podprogram" : "podprogram"));
      if (!singular) result+="y";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorSlovak::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1559 of file translator_sk.h.
    { return "Dokumentcia funkcie/podprogramu"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorSlovak::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1559 of file translator_sk.h.
    { return "Dokumentcia funkcie/podprogramu"; }
trSubprograms() [1/2]
virtual QCString TranslatorSlovak::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1553 of file translator_sk.h.
    { return "Funkcie/podprogramy"; }
trSubprograms() [2/2]
virtual QCString TranslatorSlovak::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1553 of file translator_sk.h.
    { return "Funkcie/podprogramy"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorSlovak::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1828 of file translator_sk.h.
    { return "Parametry abln"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorSlovak::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1828 of file translator_sk.h.
    { return "Parametry abln"; }
trTest() [1/2]
virtual QCString TranslatorSlovak::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1052 of file translator_sk.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorSlovak::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1052 of file translator_sk.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorSlovak::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1058 of file translator_sk.h.
    {
      return "Zoznam testov";
    }
trTestList() [2/2]
virtual QCString TranslatorSlovak::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1058 of file translator_sk.h.
    {
      return "Zoznam testov";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorSlovak::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 112 of file translator_sk.h.
    { return "Tu njdete pln zoznam lenov triedy "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorSlovak::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 112 of file translator_sk.h.
    { return "Tu njdete pln zoznam lenov triedy "; }
trTodo() [1/2]
virtual QCString TranslatorSlovak::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 927 of file translator_sk.h.
    {
      return "Plnovan pravy";
    }
trTodo() [2/2]
virtual QCString TranslatorSlovak::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 927 of file translator_sk.h.
    {
      return "Plnovan pravy";
    }
trTodoList() [1/2]
virtual QCString TranslatorSlovak::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 932 of file translator_sk.h.
    {
      return "Zoznam plnovanch prav";
    }
trTodoList() [2/2]
virtual QCString TranslatorSlovak::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 932 of file translator_sk.h.
    {
      return "Zoznam plnovanch prav";
    }
trType() [1/2]
virtual QCString TranslatorSlovak::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1676 of file translator_sk.h.
    {
      QCString result((first_capital ? "Typ" : "typ"));
      if (!singular) result+="y";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorSlovak::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1676 of file translator_sk.h.
    {
      QCString result((first_capital ? "Typ" : "typ"));
      if (!singular) result+="y";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorSlovak::trTypeConstraints () [inline], [virtual]
C# Type Contraint list
Implements Translator.
Definition at line 1694 of file translator_sk.h.
    {
      return "Obmedzenie typov (Type Constraints)";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorSlovak::trTypeConstraints () [inline], [virtual]
C# Type Contraint list
Implements Translator.
Definition at line 1694 of file translator_sk.h.
    {
      return "Obmedzenie typov (Type Constraints)";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorSlovak::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 440 of file translator_sk.h.
    { return "Dokumentcia definci typov"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorSlovak::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 440 of file translator_sk.h.
    { return "Dokumentcia definci typov"; }
trTypedefs() [1/2]
virtual QCString TranslatorSlovak::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 404 of file translator_sk.h.
    { return "Defincia typov"; }
trTypedefs() [2/2]
virtual QCString TranslatorSlovak::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 404 of file translator_sk.h.
    { return "Defincia typov"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorSlovak::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1547 of file translator_sk.h.
    { return "Dokumentcia k dtovm typom"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorSlovak::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1547 of file translator_sk.h.
    { return "Dokumentcia k dtovm typom"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorSlovak::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 458 of file translator_sk.h.
    { return "Dokumentcia premennch"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorSlovak::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 458 of file translator_sk.h.
    { return "Dokumentcia premennch"; }
trVariables() [1/2]
virtual QCString TranslatorSlovak::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 422 of file translator_sk.h.
    { return "Premenn"; }
trVariables() [2/2]
virtual QCString TranslatorSlovak::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 422 of file translator_sk.h.
    { return "Premenn"; }
trVersion() [1/2]
virtual QCString TranslatorSlovak::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 498 of file translator_sk.h.
    { return "Verzia"; }
trVersion() [2/2]
virtual QCString TranslatorSlovak::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 498 of file translator_sk.h.
    { return "Verzia"; }
trWarning() [1/2]
virtual QCString TranslatorSlovak::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 494 of file translator_sk.h.
    { return "Pozor"; }
trWarning() [2/2]
virtual QCString TranslatorSlovak::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 494 of file translator_sk.h.
    { return "Pozor"; }
trWriteList() [1/2]
virtual QCString TranslatorSlovak::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 623 of file translator_sk.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" a ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorSlovak::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 623 of file translator_sk.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" a ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_sk.h
doxygen/src/translator_sk.h