XRefDummyCodeGenerator Class Reference
Public Member Functions
XRefDummyCodeGenerator (FileDef *fd)
~XRefDummyCodeGenerator ()
void codify (const QCString &) override
void writeCodeLink (CodeSymbolType, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &) override
void writeLineNumber (const QCString &, const QCString &, const QCString &, int, bool) override
virtual void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &) override
void startCodeLine (bool) override
void endCodeLine () override
void startFontClass (const QCString &) override
void endFontClass () override
void writeCodeAnchor (const QCString &) override
void setCurrentDoc (const Definition *, const QCString &, bool) override
void addWord (const QCString &, bool) override
void startCodeFragment (const QCString &) override
void endCodeFragment (const QCString &) override
void linkableSymbol (int l, const char *sym, Definition *symDef, Definition *context)
XRefDummyCodeGenerator (FileDef *fd)
~XRefDummyCodeGenerator ()
void codify (const QCString &) override
void writeCodeLink (CodeSymbolType, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &) override
void writeLineNumber (const QCString &, const QCString &, const QCString &, int, bool) override
virtual void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &) override
void startCodeLine (bool) override
void endCodeLine () override
void startFontClass (const QCString &) override
void endFontClass () override
void writeCodeAnchor (const QCString &) override
void setCurrentDoc (const Definition *, const QCString &, bool) override
void addWord (const QCString &, bool) override
void startCodeFragment (const QCString &) override
void endCodeFragment (const QCString &) override
void linkableSymbol (int l, const char *sym, Definition *symDef, Definition *context)
Private Attributes
FileDef * m_fd
Detailed Description
Definition at line 42 of file doxyapp.cpp.
Constructor & Destructor Documentation
XRefDummyCodeGenerator() [1/2]
XRefDummyCodeGenerator::XRefDummyCodeGenerator (FileDef * fd) [inline]
Definition at line 45 of file doxyapp.cpp.
: m_fd(fd) {}
 XRefDummyCodeGenerator() [1/2]
XRefDummyCodeGenerator::~XRefDummyCodeGenerator () [inline]
Definition at line 46 of file doxyapp.cpp.
{}
XRefDummyCodeGenerator() [2/2]
XRefDummyCodeGenerator::XRefDummyCodeGenerator (FileDef * fd) [inline]
Definition at line 45 of file doxyapp.cpp.
: m_fd(fd) {}
 XRefDummyCodeGenerator() [2/2]
XRefDummyCodeGenerator::~XRefDummyCodeGenerator () [inline]
Definition at line 46 of file doxyapp.cpp.
{}
Member Function Documentation
addWord() [1/2]
void XRefDummyCodeGenerator::addWord (const QCString & , bool) [inline], [override], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 62 of file doxyapp.cpp.
{}
addWord() [2/2]
void XRefDummyCodeGenerator::addWord (const QCString & , bool) [inline], [override], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 62 of file doxyapp.cpp.
{}
codify() [1/2]
void XRefDummyCodeGenerator::codify (const QCString & s) [inline], [override], [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 50 of file doxyapp.cpp.
{}
codify() [2/2]
void XRefDummyCodeGenerator::codify (const QCString & s) [inline], [override], [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 50 of file doxyapp.cpp.
{}
endCodeFragment() [1/2]
void XRefDummyCodeGenerator::endCodeFragment (const QCString & style) [inline], [override], [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 64 of file doxyapp.cpp.
{}
endCodeFragment() [2/2]
void XRefDummyCodeGenerator::endCodeFragment (const QCString & style) [inline], [override], [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 64 of file doxyapp.cpp.
{}
endCodeLine() [1/2]
void XRefDummyCodeGenerator::endCodeLine () [inline], [override], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 57 of file doxyapp.cpp.
{}
endCodeLine() [2/2]
void XRefDummyCodeGenerator::endCodeLine () [inline], [override], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 57 of file doxyapp.cpp.
{}
endFontClass() [1/2]
void XRefDummyCodeGenerator::endFontClass () [inline], [override], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 59 of file doxyapp.cpp.
{}
endFontClass() [2/2]
void XRefDummyCodeGenerator::endFontClass () [inline], [override], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 59 of file doxyapp.cpp.
{}
linkableSymbol() [1/2]
void XRefDummyCodeGenerator::linkableSymbol (int l, const char * sym, Definition * symDef, Definition * context) [inline]
Definition at line 67 of file doxyapp.cpp.
    {
      QCString ctx;
      if (context) // the context of the symbol is known
      {
        if (context->definitionType()==Definition::TypeMember) // it is inside a member
        {
          Definition *parentContext = context->getOuterScope();
          if (parentContext && parentContext->definitionType()==Definition::TypeClass)
             // it is inside a member of a class
          {
            ctx.sprintf("inside %s %s of %s %s",
              (dynamic_cast<MemberDef*>(context))->memberTypeName().data(),
              context->name().data(),
              (dynamic_cast<ClassDef*>(parentContext))->compoundTypeString().data(),
              parentContext->name().data());
          }
          else if (parentContext==Doxygen::globalScope) // it is inside a global member
          {
            ctx.sprintf("inside %s %s",
              (dynamic_cast<MemberDef*>(context))->memberTypeName().data(),
              context->name().data());
          }
        }
        if (ctx.isEmpty()) // it is something else (class, or namespace member, ...)
        {
          ctx.sprintf("in %s",context->name().data());
        }
      }
      printf("Found symbol %s at line %d of %s %s\n",
          sym,l,m_fd->getDefFileName().data(),ctx.data());
      if (symDef && context) // in this case the definition of the symbol is
        // known to doxygen.
      {
        printf("-> defined at line %d of %s\n",
            symDef->getDefLine(),symDef->getDefFileName().data());
      }
    }
References data, QCString::data(), Definition::definitionType(), Definition::getDefFileName(), Definition::getDefLine(), Definition::getOuterScope(), Doxygen::globalScope, QCString::isEmpty(), m_fd, Definition::name(), QCString::sprintf(), Definition::TypeClass, and Definition::TypeMember.
linkableSymbol() [2/2]
void XRefDummyCodeGenerator::linkableSymbol (int l, const char * sym, Definition * symDef, Definition * context) [inline]
Definition at line 67 of file doxyapp.cpp.
    {
      QCString ctx;
      if (context) // the context of the symbol is known
      {
        if (context->definitionType()==Definition::TypeMember) // it is inside a member
        {
          Definition *parentContext = context->getOuterScope();
          if (parentContext && parentContext->definitionType()==Definition::TypeClass)
             // it is inside a member of a class
          {
            ctx.sprintf("inside %s %s of %s %s",
              (dynamic_cast<MemberDef*>(context))->memberTypeName().data(),
              context->name().data(),
              (dynamic_cast<ClassDef*>(parentContext))->compoundTypeString().data(),
              parentContext->name().data());
          }
          else if (parentContext==Doxygen::globalScope) // it is inside a global member
          {
            ctx.sprintf("inside %s %s",
              (dynamic_cast<MemberDef*>(context))->memberTypeName().data(),
              context->name().data());
          }
        }
        if (ctx.isEmpty()) // it is something else (class, or namespace member, ...)
        {
          ctx.sprintf("in %s",context->name().data());
        }
      }
      printf("Found symbol %s at line %d of %s %s\n",
          sym,l,m_fd->getDefFileName().data(),ctx.data());
      if (symDef && context) // in this case the definition of the symbol is
        // known to doxygen.
      {
        printf("-> defined at line %d of %s\n",
            symDef->getDefLine(),symDef->getDefFileName().data());
      }
    }
References data, QCString::data(), Definition::definitionType(), Definition::getDefFileName(), Definition::getDefLine(), Definition::getOuterScope(), Doxygen::globalScope, QCString::isEmpty(), m_fd, Definition::name(), QCString::sprintf(), Definition::TypeClass, and Definition::TypeMember.
setCurrentDoc() [1/2]
void XRefDummyCodeGenerator::setCurrentDoc (const Definition * , const QCString & , bool) [inline], [override], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 61 of file doxyapp.cpp.
{}
setCurrentDoc() [2/2]
void XRefDummyCodeGenerator::setCurrentDoc (const Definition * , const QCString & , bool) [inline], [override], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 61 of file doxyapp.cpp.
{}
startCodeFragment() [1/2]
void XRefDummyCodeGenerator::startCodeFragment (const QCString & style) [inline], [override], [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 63 of file doxyapp.cpp.
{}
startCodeFragment() [2/2]
void XRefDummyCodeGenerator::startCodeFragment (const QCString & style) [inline], [override], [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 63 of file doxyapp.cpp.
{}
startCodeLine() [1/2]
void XRefDummyCodeGenerator::startCodeLine (bool) [inline], [override], [virtual]
Implements CodeOutputInterface.
Definition at line 56 of file doxyapp.cpp.
{}
startCodeLine() [2/2]
void XRefDummyCodeGenerator::startCodeLine (bool) [inline], [override], [virtual]
Implements CodeOutputInterface.
Definition at line 56 of file doxyapp.cpp.
{}
startFontClass() [1/2]
void XRefDummyCodeGenerator::startFontClass (const QCString & clsName) [inline], [override], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 58 of file doxyapp.cpp.
{}
startFontClass() [2/2]
void XRefDummyCodeGenerator::startFontClass (const QCString & clsName) [inline], [override], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 58 of file doxyapp.cpp.
{}
writeCodeAnchor() [1/2]
void XRefDummyCodeGenerator::writeCodeAnchor (const QCString & name) [inline], [override], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 60 of file doxyapp.cpp.
{}
writeCodeAnchor() [2/2]
void XRefDummyCodeGenerator::writeCodeAnchor (const QCString & name) [inline], [override], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 60 of file doxyapp.cpp.
{}
writeCodeLink() [1/2]
void XRefDummyCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [inline], [override], [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 51 of file doxyapp.cpp.
{}
writeCodeLink() [2/2]
void XRefDummyCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [inline], [override], [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 51 of file doxyapp.cpp.
{}
writeLineNumber() [1/2]
void XRefDummyCodeGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [inline], [override], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 52 of file doxyapp.cpp.
{}
writeLineNumber() [2/2]
void XRefDummyCodeGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [inline], [override], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 52 of file doxyapp.cpp.
{}
writeTooltip() [1/2]
virtual void XRefDummyCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [override], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 53 of file doxyapp.cpp.
                                                               {}
writeTooltip() [2/2]
virtual void XRefDummyCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [override], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 53 of file doxyapp.cpp.
                                                               {}
Member Data Documentation
m_fd
FileDef * XRefDummyCodeGenerator::m_fd [private]
Definition at line 106 of file doxyapp.cpp.
Referenced by linkableSymbol().
The documentation for this class was generated from the following files:
doxygen/addon/doxyapp/doxyapp.cpp
doxygen/build/doxygen/addon/doxyapp/doxyapp.cpp