TranslatorAdapter_1_8_2 Class Reference
#include <translator_adapter.h>
Public Member Functions
virtual QCString updateNeededMessage ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString updateNeededMessage ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
Additional Inherited Members
Detailed Description
Definition at line 253 of file translator_adapter.h.
Member Function Documentation
trClassMethods() [1/2]
virtual QCString TranslatorAdapter_1_8_2::trClassMethods () [inline], [virtual]
Implements Translator.
Definition at line 268 of file translator_adapter.h.
    { return english.trClassMethods(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trClassMethods().
trClassMethods() [2/2]
virtual QCString TranslatorAdapter_1_8_2::trClassMethods () [inline], [virtual]
Implements Translator.
Definition at line 268 of file translator_adapter.h.
    { return english.trClassMethods(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trClassMethods().
trExtendsClass() [1/2]
virtual QCString TranslatorAdapter_1_8_2::trExtendsClass () [inline], [virtual]
Implements Translator.
Definition at line 265 of file translator_adapter.h.
    { return english.trExtendsClass(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExtendsClass().
trExtendsClass() [2/2]
virtual QCString TranslatorAdapter_1_8_2::trExtendsClass () [inline], [virtual]
Implements Translator.
Definition at line 265 of file translator_adapter.h.
    { return english.trExtendsClass(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExtendsClass().
trInstanceMethods() [1/2]
virtual QCString TranslatorAdapter_1_8_2::trInstanceMethods () [inline], [virtual]
Implements Translator.
Definition at line 271 of file translator_adapter.h.
    { return english.trInstanceMethods(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInstanceMethods().
trInstanceMethods() [2/2]
virtual QCString TranslatorAdapter_1_8_2::trInstanceMethods () [inline], [virtual]
Implements Translator.
Definition at line 271 of file translator_adapter.h.
    { return english.trInstanceMethods(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInstanceMethods().
trMethodDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_8_2::trMethodDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 274 of file translator_adapter.h.
    { return english.trMethodDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trMethodDocumentation().
trMethodDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_8_2::trMethodDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 274 of file translator_adapter.h.
    { return english.trMethodDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trMethodDocumentation().
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorAdapter_1_8_2::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Implements Translator.
Definition at line 259 of file translator_adapter.h.
    { return english.trPanelSynchronisationTooltip(enable); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trPanelSynchronisationTooltip().
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorAdapter_1_8_2::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Implements Translator.
Definition at line 259 of file translator_adapter.h.
    { return english.trPanelSynchronisationTooltip(enable); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trPanelSynchronisationTooltip().
trProvidedByCategory() [1/2]
virtual QCString TranslatorAdapter_1_8_2::trProvidedByCategory () [inline], [virtual]
Implements Translator.
Definition at line 262 of file translator_adapter.h.
    { return english.trProvidedByCategory(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trProvidedByCategory().
trProvidedByCategory() [2/2]
virtual QCString TranslatorAdapter_1_8_2::trProvidedByCategory () [inline], [virtual]
Implements Translator.
Definition at line 262 of file translator_adapter.h.
    { return english.trProvidedByCategory(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trProvidedByCategory().
updateNeededMessage() [1/2]
virtual QCString TranslatorAdapter_1_8_2::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_8_4.
Reimplemented in TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 256 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.8.2"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
updateNeededMessage() [2/2]
virtual QCString TranslatorAdapter_1_8_2::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_8_4.
Reimplemented in TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 256 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.8.2"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_adapter.h
doxygen/src/translator_adapter.h