PageDefImpl Class Reference
Public Member Functions
PageDefImpl (const QCString &f, int l, const QCString &n, const QCString &d, const QCString &t)
virtual ~PageDefImpl ()
virtual void setFileName (const QCString &name)
virtual void setLocalToc (const LocalToc &tl)
virtual void setShowLineNo (bool)
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual void findSectionsInDocumentation ()
virtual QCString title () const
virtual const GroupDef * getGroupDef () const
virtual const PageLinkedRefMap & getSubPages () const
virtual void addInnerCompound (const Definition *d)
virtual bool visibleInIndex () const
virtual bool documentedPage () const
virtual bool hasSubPages () const
virtual bool hasParentPage () const
virtual bool hasTitle () const
virtual LocalToc localToc () const
virtual void setPageScope (Definition *d)
virtual Definition * getPageScope () const
virtual QCString displayName (bool=TRUE) const
virtual bool showLineNo () const
virtual void setTitle (const QCString &title)
virtual void writeDocumentation (OutputList &ol)
virtual void writeTagFile (TextStream &)
virtual void setNestingLevel (int l)
virtual void writePageDocumentation (OutputList &ol) const
PageDefImpl (const QCString &f, int l, const QCString &n, const QCString &d, const QCString &t)
virtual ~PageDefImpl ()
virtual void setFileName (const QCString &name)
virtual void setLocalToc (const LocalToc &tl)
virtual void setShowLineNo (bool)
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual void findSectionsInDocumentation ()
virtual QCString title () const
virtual const GroupDef * getGroupDef () const
virtual const PageLinkedRefMap & getSubPages () const
virtual void addInnerCompound (const Definition *d)
virtual bool visibleInIndex () const
virtual bool documentedPage () const
virtual bool hasSubPages () const
virtual bool hasParentPage () const
virtual bool hasTitle () const
virtual LocalToc localToc () const
virtual void setPageScope (Definition *d)
virtual Definition * getPageScope () const
virtual QCString displayName (bool=TRUE) const
virtual bool showLineNo () const
virtual void setTitle (const QCString &title)
virtual void writeDocumentation (OutputList &ol)
virtual void writeTagFile (TextStream &)
virtual void setNestingLevel (int l)
virtual void writePageDocumentation (OutputList &ol) const
Private Attributes
QCString m_fileName
QCString m_title
PageLinkedRefMap m_subPages
Definition * m_pageScope
int m_nestingLevel
LocalToc m_localToc
bool m_showLineNo
Additional Inherited Members
Detailed Description
Definition at line 30 of file pagedef.cpp.
Constructor & Destructor Documentation
PageDefImpl() [1/2]
PageDefImpl::PageDefImpl (const QCString & f, int l, const QCString & n, const QCString & d, const QCString & t)
Definition at line 83 of file pagedef.cpp.
 : DefinitionMixin(f,l,1,n), m_title(!t.isEmpty() ? t : n)
{
  setDocumentation(d,f,l);
  m_pageScope = 0;
  m_nestingLevel = 0;
  m_fileName = ::convertNameToFile(n,FALSE,TRUE);
  m_showLineNo = FALSE;
}
References convertNameToFile(), f, FALSE, m_fileName, m_nestingLevel, m_pageScope, m_showLineNo, n, DefinitionMixin< PageDef >::setDocumentation(), and TRUE.
 PageDefImpl() [1/2]
PageDefImpl::~PageDefImpl () [virtual]
Definition at line 94 of file pagedef.cpp.
{
}
PageDefImpl() [2/2]
PageDefImpl::PageDefImpl (const QCString & f, int l, const QCString & n, const QCString & d, const QCString & t)
 PageDefImpl() [2/2]
virtual PageDefImpl::~PageDefImpl () [virtual]
Member Function Documentation
addInnerCompound() [1/2]
void PageDefImpl::addInnerCompound (const Definition * d) [virtual]
Reimplemented from DefinitionMixin< PageDef >.
Definition at line 122 of file pagedef.cpp.
{
  if (def->definitionType()==Definition::TypePage)
  {
    PageDef *pd = const_cast<PageDef*>(toPageDef(def));
    if (pd)
    {
      m_subPages.add(pd->name(),pd);
      pd->setOuterScope(this);
      if (this==Doxygen::mainPage.get())
      {
        pd->setNestingLevel(m_nestingLevel);
      }
      else
      {
        pd->setNestingLevel(m_nestingLevel+1);
      }
    }
  }
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::definitionType(), m_nestingLevel, m_subPages, Doxygen::mainPage, Definition::name(), PageDef::setNestingLevel(), DefinitionMutable::setOuterScope(), toPageDef(), and Definition::TypePage.
addInnerCompound() [2/2]
virtual void PageDefImpl::addInnerCompound (const Definition * d) [virtual]
Reimplemented from DefinitionMixin< PageDef >.
anchor() [1/2]
virtual QCString PageDefImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements PageDef.
Definition at line 44 of file pagedef.cpp.
{ return QCString(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString PageDefImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements PageDef.
Definition at line 44 of file pagedef.cpp.
{ return QCString(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
codeSymbolType() [1/2]
virtual CodeSymbolType PageDefImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 40 of file pagedef.cpp.
{ return CodeSymbolType::Default; }
References Default.
codeSymbolType() [2/2]
virtual CodeSymbolType PageDefImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 40 of file pagedef.cpp.
{ return CodeSymbolType::Default; }
References Default.
definitionType() [1/2]
virtual DefType PageDefImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements PageDef.
Definition at line 39 of file pagedef.cpp.
{ return TypePage; }
References Definition::TypePage.
definitionType() [2/2]
virtual DefType PageDefImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements PageDef.
Definition at line 39 of file pagedef.cpp.
{ return TypePage; }
References Definition::TypePage.
displayName() [1/2]
virtual QCString PageDefImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements PageDef.
Definition at line 58 of file pagedef.cpp.
{ return hasTitle() ? m_title : DefinitionMixin::name(); }
References hasTitle(), m_title, and DefinitionMixin< Base >::name().
displayName() [2/2]
virtual QCString PageDefImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements PageDef.
Definition at line 58 of file pagedef.cpp.
{ return hasTitle() ? m_title : DefinitionMixin::name(); }
References hasTitle(), m_title, and DefinitionMixin< Base >::name().
documentedPage() [1/2]
bool PageDefImpl::documentedPage () const [virtual]
Implements PageDef.
Definition at line 363 of file pagedef.cpp.
{
   return // not part of a group
          !getGroupDef() &&
          // not an externally defined page
          !isReference();
}
References getGroupDef(), and DefinitionMixin< PageDef >::isReference().
documentedPage() [2/2]
virtual bool PageDefImpl::documentedPage () const [virtual]
Implements PageDef.
findSectionsInDocumentation() [1/2]
void PageDefImpl::findSectionsInDocumentation () [virtual]
Implements PageDef.
Definition at line 98 of file pagedef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
}
References DefinitionMixin< PageDef >::briefDescription(), DefinitionMixin< PageDef >::docFile(), docFindSections(), and DefinitionMixin< PageDef >::documentation().
findSectionsInDocumentation() [2/2]
virtual void PageDefImpl::findSectionsInDocumentation () [virtual]
Implements PageDef.
getGroupDef() [1/2]
const GroupDef * PageDefImpl::getGroupDef () const [virtual]
Implements PageDef.
Definition at line 104 of file pagedef.cpp.
{
  return !partOfGroups().empty() ? partOfGroups().front() : 0;
}
References DefinitionMixin< PageDef >::partOfGroups().
Referenced by documentedPage(), getOutputFileBase(), and visibleInIndex().
getGroupDef() [2/2]
virtual const GroupDef * PageDefImpl::getGroupDef () const [virtual]
Implements PageDef.
getOutputFileBase() [1/2]
QCString PageDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements PageDef.
Definition at line 109 of file pagedef.cpp.
{
  if (getGroupDef())
    return getGroupDef()->getOutputFileBase();
  else
    return m_fileName;
}
References getGroupDef(), GroupDef::getOutputFileBase(), and m_fileName.
Referenced by writeDocumentation(), and writeTagFile().
getOutputFileBase() [2/2]
virtual QCString PageDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements PageDef.
getPageScope() [1/2]
virtual Definition * PageDefImpl::getPageScope () const [inline], [virtual]
Implements PageDef.
Definition at line 57 of file pagedef.cpp.
{ return m_pageScope; }
References m_pageScope.
getPageScope() [2/2]
virtual Definition * PageDefImpl::getPageScope () const [inline], [virtual]
Implements PageDef.
Definition at line 57 of file pagedef.cpp.
{ return m_pageScope; }
References m_pageScope.
getSubPages() [1/2]
virtual const PageLinkedRefMap & PageDefImpl::getSubPages () const [inline], [virtual]
Implements PageDef.
Definition at line 48 of file pagedef.cpp.
{ return m_subPages; }
References m_subPages.
getSubPages() [2/2]
virtual const PageLinkedRefMap & PageDefImpl::getSubPages () const [inline], [virtual]
Implements PageDef.
Definition at line 48 of file pagedef.cpp.
{ return m_subPages; }
References m_subPages.
hasParentPage() [1/2]
bool PageDefImpl::hasParentPage () const [virtual]
Implements PageDef.
Definition at line 143 of file pagedef.cpp.
{
  return getOuterScope() &&
         getOuterScope()->definitionType()==Definition::TypePage;
}
References Definition::definitionType(), DefinitionMixin< PageDef >::getOuterScope(), and Definition::TypePage.
hasParentPage() [2/2]
virtual bool PageDefImpl::hasParentPage () const [virtual]
Implements PageDef.
hasSubPages() [1/2]
bool PageDefImpl::hasSubPages () const [virtual]
Implements PageDef.
Definition at line 371 of file pagedef.cpp.
{
  return !m_subPages.empty();
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::empty(), and m_subPages.
Referenced by writePageDocumentation().
hasSubPages() [2/2]
virtual bool PageDefImpl::hasSubPages () const [virtual]
Implements PageDef.
hasTitle() [1/2]
bool PageDefImpl::hasTitle () const [virtual]
Implements PageDef.
Definition at line 396 of file pagedef.cpp.
{
  return !m_title.isEmpty() && m_title.lower()!="notitle";
}
References QCString::isEmpty(), QCString::lower(), and m_title.
Referenced by displayName(), and writeDocumentation().
hasTitle() [2/2]
virtual bool PageDefImpl::hasTitle () const [virtual]
Implements PageDef.
isLinkable() [1/2]
virtual bool PageDefImpl::isLinkable () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements PageDef.
Definition at line 42 of file pagedef.cpp.
{ return isLinkableInProject() || isReference(); }
References isLinkableInProject(), and DefinitionMixin< PageDef >::isReference().
isLinkable() [2/2]
virtual bool PageDefImpl::isLinkable () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements PageDef.
Definition at line 42 of file pagedef.cpp.
{ return isLinkableInProject() || isReference(); }
References isLinkableInProject(), and DefinitionMixin< PageDef >::isReference().
isLinkableInProject() [1/2]
virtual bool PageDefImpl::isLinkableInProject () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements PageDef.
Definition at line 41 of file pagedef.cpp.
{ return /*hasDocumentation() &&*/ !isReference(); }
References DefinitionMixin< PageDef >::isReference().
Referenced by isLinkable().
isLinkableInProject() [2/2]
virtual bool PageDefImpl::isLinkableInProject () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements PageDef.
Definition at line 41 of file pagedef.cpp.
{ return /*hasDocumentation() &&*/ !isReference(); }
References DefinitionMixin< PageDef >::isReference().
localToc() [1/2]
virtual LocalToc PageDefImpl::localToc () const [inline], [virtual]
Implements PageDef.
Definition at line 55 of file pagedef.cpp.
{ return m_localToc; }
References m_localToc.
localToc() [2/2]
virtual LocalToc PageDefImpl::localToc () const [inline], [virtual]
Implements PageDef.
Definition at line 55 of file pagedef.cpp.
{ return m_localToc; }
References m_localToc.
setFileName() [1/2]
void PageDefImpl::setFileName (const QCString & name) [virtual]
Implements PageDef.
Definition at line 117 of file pagedef.cpp.
{
  m_fileName = name;
}
References m_fileName, and DefinitionMixin< PageDef >::name().
setFileName() [2/2]
virtual void PageDefImpl::setFileName (const QCString & name) [virtual]
Implements PageDef.
setLocalToc() [1/2]
void PageDefImpl::setLocalToc (const LocalToc & tl) [virtual]
Implements PageDef.
Definition at line 381 of file pagedef.cpp.
{
  m_localToc = lt;
}
References m_localToc.
setLocalToc() [2/2]
virtual void PageDefImpl::setLocalToc (const LocalToc & tl) [virtual]
Implements PageDef.
setNestingLevel() [1/2]
void PageDefImpl::setNestingLevel (int l) [virtual]
Implements PageDef.
Definition at line 376 of file pagedef.cpp.
{
  m_nestingLevel = l;
}
References m_nestingLevel.
setNestingLevel() [2/2]
virtual void PageDefImpl::setNestingLevel (int l) [virtual]
Implements PageDef.
setPageScope() [1/2]
virtual void PageDefImpl::setPageScope (Definition * d) [inline], [virtual]
Implements PageDef.
Definition at line 56 of file pagedef.cpp.
{ m_pageScope = d; }
References m_pageScope.
setPageScope() [2/2]
virtual void PageDefImpl::setPageScope (Definition * d) [inline], [virtual]
Implements PageDef.
Definition at line 56 of file pagedef.cpp.
{ m_pageScope = d; }
References m_pageScope.
setShowLineNo() [1/2]
void PageDefImpl::setShowLineNo (bool b) [virtual]
Implements PageDef.
Definition at line 386 of file pagedef.cpp.
{
  m_showLineNo = b;
}
References b, and m_showLineNo.
setShowLineNo() [2/2]
virtual void PageDefImpl::setShowLineNo (bool) [virtual]
Implements PageDef.
setTitle() [1/2]
void PageDefImpl::setTitle (const QCString & title) [virtual]
Implements PageDef.
Definition at line 401 of file pagedef.cpp.
{
  m_title = title;
}
References m_title, and title().
setTitle() [2/2]
virtual void PageDefImpl::setTitle (const QCString & title) [virtual]
Implements PageDef.
showLineNo() [1/2]
bool PageDefImpl::showLineNo () const [virtual]
Implements PageDef.
Definition at line 391 of file pagedef.cpp.
{
  return m_showLineNo;
}
References m_showLineNo.
showLineNo() [2/2]
virtual bool PageDefImpl::showLineNo () const [virtual]
Implements PageDef.
title() [1/2]
virtual QCString PageDefImpl::title () const [inline], [virtual]
Implements PageDef.
Definition at line 46 of file pagedef.cpp.
{ return m_title; }
References m_title.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), setTitle(), writeDocumentation(), writePageDocumentation(), and writeTagFile().
title() [2/2]
virtual QCString PageDefImpl::title () const [inline], [virtual]
Implements PageDef.
Definition at line 46 of file pagedef.cpp.
{ return m_title; }
References m_title.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
visibleInIndex() [1/2]
bool PageDefImpl::visibleInIndex () const [virtual]
Implements PageDef.
Definition at line 353 of file pagedef.cpp.
{
  bool externalPages = Config_getBool(EXTERNAL_PAGES);
  return // not part of a group
         !getGroupDef() &&
         // not an externally defined page
         (!isReference() || externalPages)
         ;
}
References Config_getBool, getGroupDef(), and DefinitionMixin< PageDef >::isReference().
visibleInIndex() [2/2]
virtual bool PageDefImpl::visibleInIndex () const [virtual]
Implements PageDef.
writeDocumentation() [1/2]
void PageDefImpl::writeDocumentation (OutputList & ol) [virtual]
Implements PageDef.
Definition at line 171 of file pagedef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  //outputList->disable(OutputGenerator::Man);
  QCString pageName,manPageName;
  pageName = escapeCharsInString(name(),FALSE,TRUE);
  manPageName = escapeCharsInString(name(),TRUE,TRUE);
  //printf("PageDefImpl::writeDocumentation: %s\n",getOutputFileBase().data());
  ol.pushGeneratorState();
  //1.{
  if (m_nestingLevel>0
      //&& // a sub page
      //(Doxygen::mainPage==0 || getOuterScope()!=Doxygen::mainPage) // and not a subpage of the mainpage
     )
  {
    // do not generate sub page output for RTF and LaTeX, as these are
    // part of their parent page
    ol.disableAll();
    ol.enable(OutputGenerator::Man);
    ol.enable(OutputGenerator::Html);
  }
  ol.pushGeneratorState();
  //2.{
  ol.disableAllBut(OutputGenerator::Man);
  startFile(ol,getOutputFileBase(),manPageName,title(),HLI_Pages,!generateTreeView);
  ol.enableAll();
  ol.disable(OutputGenerator::Man);
  startFile(ol,getOutputFileBase(),pageName,title(),HLI_Pages,!generateTreeView);
  ol.popGeneratorState();
  //2.}
  if (!generateTreeView)
  {
    if (getOuterScope()!=Doxygen::globalScope && !Config_getBool(DISABLE_INDEX))
    {
      DefinitionMutable *outerScope = toDefinitionMutable(getOuterScope());
      if (outerScope)
      {
        outerScope->writeNavigationPath(ol);
      }
    }
    ol.endQuickIndices();
  }
  const SectionInfo *si=SectionManager::instance().find(name());
  // save old generator state and write title only to Man generator
  ol.pushGeneratorState();
  //2.{
  ol.disableAllBut(OutputGenerator::Man);
  ol.startTitleHead(manPageName);
  ol.endTitleHead(manPageName, manPageName);
  if (si)
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputGenerator::Man);
    ol.writeString(" - ");
    ol.popGeneratorState();
    if (si->title() != manPageName)
    {
      ol.generateDoc(docFile(),getStartBodyLine(),this,0,si->title(),TRUE,FALSE,
                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
      ol.endSection(si->label(),si->type());
    }
  }
  ol.popGeneratorState();
  //2.}
  // for Latex the section is already generated as a chapter in the index!
  ol.pushGeneratorState();
  //2.{
  ol.disable(OutputGenerator::Latex);
  ol.disable(OutputGenerator::Docbook);
  ol.disable(OutputGenerator::RTF);
  ol.disable(OutputGenerator::Man);
  if (hasTitle() && !name().isEmpty() && si!=0)
  {
    ol.startPageDoc(si->title());
    //ol.startSection(si->label,si->title,si->type);
    startTitle(ol,getOutputFileBase(),this);
    ol.generateDoc(docFile(),getStartBodyLine(),this,0,si->title(),TRUE,FALSE,
                   QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    //stringToSearchIndex(getOutputFileBase(),
    // theTranslator->trPage(TRUE,TRUE)+" "+si->title,
    // si->title);
    //ol.endSection(si->label,si->type);
    endTitle(ol,getOutputFileBase(),name());
  }
  else
    ol.startPageDoc("");
  ol.startContents();
  ol.popGeneratorState();
  //2.}
  if ((m_localToc.isHtmlEnabled() || m_localToc.isLatexEnabled() || m_localToc.isDocbookEnabled()) && hasSections())
  {
    writeToc(ol, m_localToc);
  }
  writePageDocumentation(ol);
  ol.endContents();
  ol.endPageDoc();
  if (generateTreeView && getOuterScope()!=Doxygen::globalScope && !Config_getBool(DISABLE_INDEX))
  {
    endFileWithNavPath(getOuterScope(),ol);
  }
  else
  {
    endFile(ol,FALSE,TRUE);
  }
  ol.popGeneratorState();
  //1.}
}
References Config_getBool, OutputList::disable(), OutputList::disableAll(), OutputList::disableAllBut(), OutputGenerator::Docbook, DefinitionMixin< PageDef >::docFile(), OutputList::enable(), OutputList::enableAll(), OutputList::endContents(), endFile(), endFileWithNavPath(), OutputList::endPageDoc(), OutputList::endQuickIndices(), OutputList::endSection(), endTitle(), OutputList::endTitleHead(), escapeCharsInString(), FALSE, LinkedMap< T, Hash, KeyEqual, Map >::find(), OutputList::generateDoc(), DefinitionMixin< PageDef >::getOuterScope(), getOutputFileBase(), DefinitionMixin< PageDef >::getStartBodyLine(), Doxygen::globalScope, DefinitionMixin< PageDef >::hasSections(), hasTitle(), HLI_Pages, OutputGenerator::Html, SectionManager::instance(), LocalToc::isDocbookEnabled(), LocalToc::isHtmlEnabled(), LocalToc::isLatexEnabled(), SectionInfo::label(), OutputGenerator::Latex, m_localToc, m_nestingLevel, OutputGenerator::Man, DefinitionMixin< PageDef >::name(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startContents(), startFile(), OutputList::startPageDoc(), startTitle(), OutputList::startTitleHead(), title(), SectionInfo::title(), Definition::toDefinitionMutable, TRUE, SectionInfo::type(), DefinitionMutable::writeNavigationPath(), writePageDocumentation(), OutputList::writeString(), and DefinitionMixin< PageDef >::writeToc().
writeDocumentation() [2/2]
virtual void PageDefImpl::writeDocumentation (OutputList & ol) [virtual]
Implements PageDef.
writePageDocumentation() [1/2]
void PageDefImpl::writePageDocumentation (OutputList & ol) const [virtual]
Implements PageDef.
Definition at line 292 of file pagedef.cpp.
{
  ol.startTextBlock();
  QCString docStr = (briefDescription().isEmpty()?"":briefDescription()+"\n\n")+documentation()+inbodyDocumentation();
  if (hasBriefDescription() && !SectionManager::instance().find(name()))
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputGenerator::Man);
    ol.writeString(" - ");
    ol.popGeneratorState();
  }
  ol.generateDoc(
      docFile(), // fileName
      docLine(), // startLine
      this, // context
      0, // memberdef
      docStr, // docStr
      TRUE, // index words
      FALSE, // not an example
      QCString(), // exampleName
      FALSE, // singleLine
      FALSE, // linkFromIndex
      TRUE // markdown support
      );
  ol.endTextBlock();
  if (hasSubPages())
  {
    // for printed documentation we write subpages as section's of the
    // parent page.
    ol.pushGeneratorState();
    ol.disableAll();
    ol.enable(OutputGenerator::Latex);
    ol.enable(OutputGenerator::Docbook);
    ol.enable(OutputGenerator::RTF);
    for (const auto &subPage : m_subPages)
    {
      SectionType sectionType = SectionType::Paragraph;
      switch (m_nestingLevel)
      {
        case 0: sectionType = SectionType::Page; break;
        case 1: sectionType = SectionType::Section; break;
        case 2: sectionType = SectionType::Subsection; break;
        case 3: sectionType = SectionType::Subsubsection; break;
        default: sectionType = SectionType::Paragraph; break;
      }
      QCString title = subPage->title();
      if (title.isEmpty()) title = subPage->name();
      ol.startSection(subPage->name(),title,sectionType);
      ol.parseText(title);
      ol.endSection(subPage->name(),sectionType);
      Doxygen::subpageNestingLevel++;
      subPage->writePageDocumentation(ol);
      Doxygen::subpageNestingLevel--;
    }
    ol.popGeneratorState();
  }
}
References DefinitionMixin< PageDef >::briefDescription(), OutputList::disableAll(), OutputList::disableAllBut(), OutputGenerator::Docbook, DefinitionMixin< PageDef >::docFile(), DefinitionMixin< PageDef >::docLine(), DefinitionMixin< PageDef >::documentation(), OutputList::enable(), OutputList::endSection(), OutputList::endTextBlock(), FALSE, OutputList::generateDoc(), DefinitionMixin< PageDef >::hasBriefDescription(), hasSubPages(), DefinitionMixin< PageDef >::inbodyDocumentation(), SectionManager::instance(), QCString::isEmpty(), OutputGenerator::Latex, m_nestingLevel, m_subPages, OutputGenerator::Man, DefinitionMixin< PageDef >::name(), Page, Paragraph, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, Section, OutputList::startSection(), OutputList::startTextBlock(), Doxygen::subpageNestingLevel, Subsection, Subsubsection, title(), TRUE, and OutputList::writeString().
Referenced by writeDocumentation().
writePageDocumentation() [2/2]
virtual void PageDefImpl::writePageDocumentation (OutputList & ol) const [virtual]
Implements PageDef.
writeTagFile() [1/2]
void PageDefImpl::writeTagFile (TextStream & tagFile) [virtual]
Implements PageDef.
Definition at line 149 of file pagedef.cpp.
{
  bool found = name()=="citelist";
  for (RefListManager::Ptr &rl : RefListManager::instance())
  {
    if (rl->listName()==name())
    {
      found=TRUE;
      break;
    }
  }
  if (!found) // not one of the generated related pages
  {
    tagFile << " <compound kind=\"page\">\n";
    tagFile << " <name>" << name() << "</name>\n";
    tagFile << " <title>" << convertToXML(title()) << "</title>\n";
    tagFile << " <filename>" << addHtmlExtensionIfMissing(getOutputFileBase()) << "</filename>\n";
    writeDocAnchorsToTagFile(tagFile);
    tagFile << " </compound>\n";
  }
}
References addHtmlExtensionIfMissing(), convertToXML(), found, getOutputFileBase(), RefListManager::instance(), DefinitionMixin< PageDef >::name(), title(), TRUE, and DefinitionMixin< PageDef >::writeDocAnchorsToTagFile().
writeTagFile() [2/2]
virtual void PageDefImpl::writeTagFile (TextStream &) [virtual]
Implements PageDef.
Member Data Documentation
m_fileName
QCString PageDefImpl::m_fileName [private]
Definition at line 67 of file pagedef.cpp.
Referenced by getOutputFileBase(), PageDefImpl(), and setFileName().
m_localToc
LocalToc PageDefImpl::m_localToc [private]
Definition at line 72 of file pagedef.cpp.
Referenced by localToc(), setLocalToc(), and writeDocumentation().
m_nestingLevel
int PageDefImpl::m_nestingLevel [private]
Definition at line 71 of file pagedef.cpp.
Referenced by addInnerCompound(), PageDefImpl(), setNestingLevel(), writeDocumentation(), and writePageDocumentation().
m_pageScope
Definition * PageDefImpl::m_pageScope [private]
Definition at line 70 of file pagedef.cpp.
Referenced by getPageScope(), PageDefImpl(), and setPageScope().
m_showLineNo
bool PageDefImpl::m_showLineNo [private]
Definition at line 73 of file pagedef.cpp.
Referenced by PageDefImpl(), setShowLineNo(), and showLineNo().
m_subPages
PageLinkedRefMap PageDefImpl::m_subPages [private]
Definition at line 69 of file pagedef.cpp.
Referenced by addInnerCompound(), getSubPages(), hasSubPages(), and writePageDocumentation().
m_title
QCString PageDefImpl::m_title [private]
Definition at line 68 of file pagedef.cpp.
Referenced by displayName(), hasTitle(), setTitle(), and title().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/pagedef.cpp
doxygen/src/pagedef.cpp