Timer Class Reference
Public Member Functions
void start ()
double elapsedTimeS ()
void start ()
double elapsedTimeS ()
Private Attributes
std::chrono::time_point< std::chrono::steady_clock > m_startTime
Detailed Description
Definition at line 115 of file debug.cpp.
Member Function Documentation
elapsedTimeS() [1/2]
double Timer::elapsedTimeS () [inline]
Definition at line 122 of file debug.cpp.
    {
      return static_cast<double>(
              std::chrono::duration_cast<
                  std::chrono::microseconds>(
                  std::chrono::steady_clock::now() - m_startTime).count()) / 1000000.0;
    }
References m_startTime.
Referenced by Debug::elapsedTime().
elapsedTimeS() [2/2]
double Timer::elapsedTimeS () [inline]
Definition at line 122 of file debug.cpp.
    {
      return static_cast<double>(
              std::chrono::duration_cast<
                  std::chrono::microseconds>(
                  std::chrono::steady_clock::now() - m_startTime).count()) / 1000000.0;
    }
References m_startTime.
start() [1/2]
void Timer::start () [inline]
Definition at line 118 of file debug.cpp.
    {
      m_startTime = std::chrono::steady_clock::now();
    }
References m_startTime.
Referenced by doxmlparser.compound.docListType::__init__(), doxmlparser.compound.docListType::buildAttributes(), doxmlparser.compound.docListType::exportAttributes(), doxmlparser.compound.docListType::get_start(), doxmlparser.compound.docListType::set_start(), and Debug::startTimer().
start() [2/2]
void Timer::start () [inline]
Definition at line 118 of file debug.cpp.
    {
      m_startTime = std::chrono::steady_clock::now();
    }
References m_startTime.
Referenced by doxmlparser.compound.docListType::__init__(), doxmlparser.compound.docListType::buildAttributes(), doxmlparser.compound.docListType::exportAttributes(), doxmlparser.compound.docListType::get_start(), and doxmlparser.compound.docListType::set_start().
Member Data Documentation
m_startTime
std::chrono::time_point< std::chrono::steady_clock > Timer::m_startTime [private]
Definition at line 130 of file debug.cpp.
Referenced by elapsedTimeS(), and start().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/debug.cpp
doxygen/src/debug.cpp