PageDef Class Reference
A model of a page symbol.
#include <pagedef.h>
Public Member Functions
virtual void setFileName (const QCString &name)=0
virtual void setLocalToc (const LocalToc &tl)=0
virtual void setShowLineNo (bool)=0
virtual void setTitle (const QCString &title)=0
virtual DefType definitionType () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual void findSectionsInDocumentation ()=0
virtual QCString title () const =0
virtual const GroupDef * getGroupDef () const =0
virtual const PageLinkedRefMap & getSubPages () const =0
virtual void addInnerCompound (const Definition *)=0
virtual bool visibleInIndex () const =0
virtual bool documentedPage () const =0
virtual bool hasSubPages () const =0
virtual bool hasParentPage () const =0
virtual bool hasTitle () const =0
virtual LocalToc localToc () const =0
virtual void setPageScope (Definition *)=0
virtual Definition * getPageScope () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual bool showLineNo () const =0
virtual void writeDocumentation (OutputList &)=0
virtual void writeTagFile (TextStream &)=0
virtual void setNestingLevel (int)=0
virtual void writePageDocumentation (OutputList &) const =0
virtual void setFileName (const QCString &name)=0
virtual void setLocalToc (const LocalToc &tl)=0
virtual void setShowLineNo (bool)=0
virtual void setTitle (const QCString &title)=0
virtual DefType definitionType () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual void findSectionsInDocumentation ()=0
virtual QCString title () const =0
virtual const GroupDef * getGroupDef () const =0
virtual const PageLinkedRefMap & getSubPages () const =0
virtual void addInnerCompound (const Definition *)=0
virtual bool visibleInIndex () const =0
virtual bool documentedPage () const =0
virtual bool hasSubPages () const =0
virtual bool hasParentPage () const =0
virtual bool hasTitle () const =0
virtual LocalToc localToc () const =0
virtual void setPageScope (Definition *)=0
virtual Definition * getPageScope () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual bool showLineNo () const =0
virtual void writeDocumentation (OutputList &)=0
virtual void writeTagFile (TextStream &)=0
virtual void setNestingLevel (int)=0
virtual void writePageDocumentation (OutputList &) const =0
Additional Inherited Members
Detailed Description
A model of a page symbol.
Definition at line 25 of file pagedef.h.
Member Function Documentation
addInnerCompound() [1/2]
virtual void PageDef::addInnerCompound (const Definition *) [pure virtual]
Implements DefinitionMutable.
Implemented in PageDefImpl, PageDefImpl, DefinitionMixin< PageDef >, and DefinitionMixin< PageDef >.
Referenced by computePageRelations().
addInnerCompound() [2/2]
virtual void PageDef::addInnerCompound (const Definition *) [pure virtual]
Implements DefinitionMutable.
Implemented in PageDefImpl, PageDefImpl, DefinitionMixin< PageDef >, and DefinitionMixin< PageDef >.
anchor() [1/2]
virtual QCString PageDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in PageDefImpl, and PageDefImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString PageDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in PageDefImpl, and PageDefImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
definitionType() [1/2]
virtual DefType PageDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in PageDefImpl, and PageDefImpl.
definitionType() [2/2]
virtual DefType PageDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in PageDefImpl, and PageDefImpl.
displayName() [1/2]
virtual QCString PageDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in PageDefImpl, and PageDefImpl.
displayName() [2/2]
virtual QCString PageDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in PageDefImpl, and PageDefImpl.
documentedPage() [1/2]
virtual bool PageDef::documentedPage () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
documentedPage() [2/2]
virtual bool PageDef::documentedPage () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
findSectionsInDocumentation() [1/2]
virtual void PageDef::findSectionsInDocumentation () [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
findSectionsInDocumentation() [2/2]
virtual void PageDef::findSectionsInDocumentation () [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
getGroupDef() [1/2]
virtual const GroupDef * PageDef::getGroupDef () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by generateXMLForPage(), resolveLink(), and resolveUserReferences().
getGroupDef() [2/2]
virtual const GroupDef * PageDef::getGroupDef () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
getOutputFileBase() [1/2]
virtual QCString PageDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in PageDefImpl, and PageDefImpl.
Referenced by addRelatedPage(), generateXMLForPage(), and writePages().
getOutputFileBase() [2/2]
virtual QCString PageDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in PageDefImpl, and PageDefImpl.
getPageScope() [1/2]
virtual Definition * PageDef::getPageScope () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
getPageScope() [2/2]
virtual Definition * PageDef::getPageScope () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
getSubPages() [1/2]
virtual const PageLinkedRefMap & PageDef::getSubPages () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by NestingNodeContext::Private::addPages(), generateXMLForPage(), and writePages().
getSubPages() [2/2]
virtual const PageLinkedRefMap & PageDef::getSubPages () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
hasParentPage() [1/2]
virtual bool PageDef::hasParentPage () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by DocRef::DocRef(), and DocSecRefItem::parse().
hasParentPage() [2/2]
virtual bool PageDef::hasParentPage () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
hasSubPages() [1/2]
virtual bool PageDef::hasSubPages () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by writePages().
hasSubPages() [2/2]
virtual bool PageDef::hasSubPages () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
hasTitle() [1/2]
virtual bool PageDef::hasTitle () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by addRelatedPage(), DefinitionImpl::navigationPathAsString(), DefinitionImpl::pathFragment(), and SearchIndex::setCurrentDoc().
hasTitle() [2/2]
virtual bool PageDef::hasTitle () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
isLinkable() [1/2]
virtual bool PageDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in PageDefImpl, and PageDefImpl.
isLinkable() [2/2]
virtual bool PageDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in PageDefImpl, and PageDefImpl.
isLinkableInProject() [1/2]
virtual bool PageDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in PageDefImpl, and PageDefImpl.
isLinkableInProject() [2/2]
virtual bool PageDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in PageDefImpl, and PageDefImpl.
localToc() [1/2]
virtual LocalToc PageDef::localToc () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by generateXMLForPage().
localToc() [2/2]
virtual LocalToc PageDef::localToc () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
setFileName() [1/2]
virtual void PageDef::setFileName (const QCString & name) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by addRelatedPage(), and buildExampleList().
setFileName() [2/2]
virtual void PageDef::setFileName (const QCString & name) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
setLocalToc() [1/2]
virtual void PageDef::setLocalToc (const LocalToc & tl) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by addRelatedPage().
setLocalToc() [2/2]
virtual void PageDef::setLocalToc (const LocalToc & tl) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
setNestingLevel() [1/2]
virtual void PageDef::setNestingLevel (int) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by PageDefImpl::addInnerCompound(), and addRelatedPage().
setNestingLevel() [2/2]
virtual void PageDef::setNestingLevel (int) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
setPageScope() [1/2]
virtual void PageDef::setPageScope (Definition *) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by addPageToContext(), and addRelatedPage().
setPageScope() [2/2]
virtual void PageDef::setPageScope (Definition *) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
setShowLineNo() [1/2]
virtual void PageDef::setShowLineNo (bool) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by addRelatedPage(), and buildExampleList().
setShowLineNo() [2/2]
virtual void PageDef::setShowLineNo (bool) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
setTitle() [1/2]
virtual void PageDef::setTitle (const QCString & title) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by addRelatedPage().
setTitle() [2/2]
virtual void PageDef::setTitle (const QCString & title) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
showLineNo() [1/2]
virtual bool PageDef::showLineNo () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
showLineNo() [2/2]
virtual bool PageDef::showLineNo () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
title() [1/2]
virtual QCString PageDef::title () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), addRelatedPage(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), DefinitionImpl::pathFragment(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), searchName(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), SearchIndex::setCurrentDoc(), PageContext::Private::title(), and writePages().
title() [2/2]
virtual QCString PageDef::title () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
visibleInIndex() [1/2]
virtual bool PageDef::visibleInIndex () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
Referenced by writePages().
visibleInIndex() [2/2]
virtual bool PageDef::visibleInIndex () const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
writeDocumentation() [1/2]
virtual void PageDef::writeDocumentation (OutputList &) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
writeDocumentation() [2/2]
virtual void PageDef::writeDocumentation (OutputList &) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
writePageDocumentation() [1/2]
virtual void PageDef::writePageDocumentation (OutputList &) const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
writePageDocumentation() [2/2]
virtual void PageDef::writePageDocumentation (OutputList &) const [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
writeTagFile() [1/2]
virtual void PageDef::writeTagFile (TextStream &) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
writeTagFile() [2/2]
virtual void PageDef::writeTagFile (TextStream &) [pure virtual]
Implemented in PageDefImpl, and PageDefImpl.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/pagedef.h
doxygen/src/pagedef.h