HtmlHelpIndex Class Reference
Public Member Functions
HtmlHelpIndex (HtmlHelpRecoder &recoder)
~HtmlHelpIndex ()
void addItem (const QCString &first, const QCString &second, const QCString &url, const QCString &anchor, bool hasLink, bool reversed)
void writeFields (std::ostream &t)
size_t size () const
HtmlHelpIndex (HtmlHelpRecoder &recoder)
~HtmlHelpIndex ()
void addItem (const QCString &first, const QCString &second, const QCString &url, const QCString &anchor, bool hasLink, bool reversed)
void writeFields (std::ostream &t)
size_t size () const
Private Attributes
LinkedMap< IndexField > m_map
HtmlHelpRecoder & m_recoder
Detailed Description
A helper class for HtmlHelp that manages a two level index in alphabetical order.
Definition at line 114 of file htmlhelp.cpp.
Constructor & Destructor Documentation
HtmlHelpIndex() [1/2]
HtmlHelpIndex::HtmlHelpIndex (HtmlHelpRecoder & recoder)
Constructs a new HtmlHelp index
Definition at line 130 of file htmlhelp.cpp.
                                                     : m_recoder(recoder)
{
}
 HtmlHelpIndex() [1/2]
HtmlHelpIndex::~HtmlHelpIndex ()
Destroys the HtmlHelp index
Definition at line 135 of file htmlhelp.cpp.
{
}
HtmlHelpIndex() [2/2]
HtmlHelpIndex::HtmlHelpIndex (HtmlHelpRecoder & recoder)
 HtmlHelpIndex() [2/2]
HtmlHelpIndex::~HtmlHelpIndex ()
Member Function Documentation
addItem() [1/2]
void HtmlHelpIndex::addItem (const QCString & level1, const QCString & level2, const QCString & url, const QCString & anchor, bool hasLink, bool reversed)
Stores an item in the index if it is not already present. Items are stored in alphabetical order, by sorting on the concatenation of level1 and level2 (if present).
Parameters
level1 the string at level 1 in the index.
level2 the string at level 2 in the index (or 0 if not applicable).
url the url of the documentation (without .html extension).
anchor the anchor of the documentation within the page.
hasLink if true, the url (without anchor) can be used in the level1 item, when writing the header of a list of level2 items.
reversed TRUE if level1 is the member name and level2 the compound name.
Definition at line 152 of file htmlhelp.cpp.
{
  static const reg::Ex re(R"(@\d+)");
  std::string key = level1.str();
  if (!level2.isEmpty()) key+= std::string("?") + level2.str();
  if (reg::search(key,re)) // skip anonymous stuff
  {
    return;
  }
  std::string key_anchor;
  if (!anchor.isEmpty())
  {
    key_anchor = key+anchor.str();
  }
  else
  {
    key_anchor = key;
  }
  m_map.add(key_anchor.c_str(),key.c_str(),url,anchor,hasLink,reversed);
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), QCString::isEmpty(), m_map, reg::search(), QCString::str(), string, and setup::url.
addItem() [2/2]
void HtmlHelpIndex::addItem (const QCString & first, const QCString & second, const QCString & url, const QCString & anchor, bool hasLink, bool reversed)
size() [1/2]
size_t HtmlHelpIndex::size () const [inline]
Definition at line 123 of file htmlhelp.cpp.
{ return m_map.size(); }
References m_map, and LinkedMap< T, Hash, KeyEqual, Map >::size().
Referenced by HtmlHelp::Private::createProjectFile().
size() [2/2]
size_t HtmlHelpIndex::size () const [inline]
Definition at line 123 of file htmlhelp.cpp.
{ return m_map.size(); }
References m_map, and LinkedMap< T, Hash, KeyEqual, Map >::size().
writeFields() [1/2]
void HtmlHelpIndex::writeFields (std::ostream & t)
Writes the sorted list of index items into a html like list.
An list of calls with name = level1,level2 as follows:
  a1,b1
  a1,b2
  a2,b1
  a2,b2
  a3
  a4,b1
Will result in the following list:
  a1 -> link to url if hasLink==TRUE
    b1 -> link to url::anchor
    b2 -> link to url::anchor
  a2 -> link to url if hasLink==TRUE
    b1 -> link to url::anchor
    b2 -> link to url::anchor
  a3 -> link to url if hasLink==TRUE
  a4 -> link to url if hasLink==TRUE
    b1 -> link to url::anchor
Definition at line 212 of file htmlhelp.cpp.
{
  std::sort(std::begin(m_map),
            std::end(m_map),
            [](const auto &e1,const auto &e2) { return e1->name < e2->name; }
           );
  QCString prevLevel1;
  bool level2Started=FALSE;
  for (auto it = std::begin(m_map); it!=std::end(m_map); ++it)
  {
    auto &f = *it;
    QCString level1,level2;
    int i;
    if ((i=f->name.find('?'))!=-1)
    {
      level1 = f->name.left(i);
      level2 = f->name.right(f->name.length()-i-1);
    }
    else
    {
      level1 = f->name;
    }
    { // finish old list at level 2
      if (level2Started) t << " </UL>\n";
      level2Started=FALSE;
      // <Antony>
      // Added this code so that an item with only one subitem is written
      // without any subitem.
      // For example:
      // a1, b1 -> will create only a1, not separate subitem for b1
      // a2, b2
      // a2, b3
      QCString nextLevel1;
      auto it_next = std::next(it);
      if (it_next!=std::end(m_map))
      {
        auto &fnext = *it_next;
        int j = fnext->name.find('?');
        if (j<0) j=0;
        nextLevel1 = fnext->name.left(j);
      }
      if (!(level1 == prevLevel1 || level1 == nextLevel1))
      {
        level2 = "";
      }
      prevLevel1 = level1;
      // </Antony>
      if (level2.isEmpty())
      {
        t << " <LI><OBJECT type=\"text/sitemap\">";
        t << "<param name=\"Local\" value=\"" << field2URL(f.get(),FALSE);
        t << "\">";
        t << "<param name=\"Name\" value=\"" << convertToHtml(m_recoder.recode(level1),TRUE) << "\">"
           "</OBJECT>\n";
      }
      else
      {
        if (f->link)
        {
          t << " <LI><OBJECT type=\"text/sitemap\">";
          t << "<param name=\"Local\" value=\"" << field2URL(f.get(),TRUE);
          t << "\">";
          t << "<param name=\"Name\" value=\"" << convertToHtml(m_recoder.recode(level1),TRUE) << "\">"
               "</OBJECT>\n";
        }
        else
        {
          t << " <LI><OBJECT type=\"text/sitemap\">";
          t << "<param name=\"See Also\" value=\"" << convertToHtml(m_recoder.recode(level1),TRUE) << "\">";
          t << "<param name=\"Name\" value=\"" << convertToHtml(m_recoder.recode(level1),TRUE) << "\">"
               "</OBJECT>\n";
        }
      }
    }
    if (!level2Started && !level2.isEmpty())
    { // start new list at level 2
      t << " <UL>\n";
      level2Started=TRUE;
    }
    else if (level2Started && level2.isEmpty())
    { // end list at level 2
      t << " </UL>\n";
      level2Started=FALSE;
    }
    if (level2Started)
    {
      t << " <LI><OBJECT type=\"text/sitemap\">";
      t << "<param name=\"Local\" value=\"" << field2URL(f.get(),FALSE);
      t << "\">";
      t << "<param name=\"Name\" value=\"" << convertToHtml(m_recoder.recode(level2),TRUE) << "\">"
         "</OBJECT>\n";
    }
  }
  if (level2Started) t << " </UL>\n";
}
References ghc::filesystem::begin(), convertToHtml(), ghc::filesystem::end(), f, FALSE, field2URL(), QCString::isEmpty(), QCString::left(), m_map, m_recoder, HtmlHelpRecoder::recode(), and TRUE.
writeFields() [2/2]
void HtmlHelpIndex::writeFields (std::ostream & t)
Member Data Documentation
m_map
LinkedMap< IndexField > HtmlHelpIndex::m_map [private]
Definition at line 125 of file htmlhelp.cpp.
Referenced by addItem(), size(), and writeFields().
m_recoder
HtmlHelpRecoder & HtmlHelpIndex::m_recoder [private]
Definition at line 126 of file htmlhelp.cpp.
Referenced by writeFields().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/htmlhelp.cpp
doxygen/src/htmlhelp.cpp