FilterDivisibleBy Class Reference
The implementation of the `divisibleby` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &n)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &n)
Detailed Description
The implementation of the `divisibleby` filter.
Definition at line 1426 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterDivisibleBy::apply (const TemplateVariant & v, const TemplateVariant & n) [inline], [static]
Definition at line 1429 of file template.cpp.
    {
      if (!v.isValid() || !n.isValid())
      {
        return TemplateVariant();
      }
      if (v.isInt() && n.isInt())
      {
        int ni = n.toInt();
        if (ni>0)
        {
          return TemplateVariant((v.toInt()%ni)==0);
        }
        else
        {
          return TemplateVariant(FALSE);
        }
      }
      else
      {
        return TemplateVariant();
      }
    }
References FALSE, TemplateVariant::isInt(), TemplateVariant::isValid(), n, and TemplateVariant::toInt().
apply() [2/2]
static TemplateVariant FilterDivisibleBy::apply (const TemplateVariant & v, const TemplateVariant & n) [inline], [static]
Definition at line 1429 of file template.cpp.
    {
      if (!v.isValid() || !n.isValid())
      {
        return TemplateVariant();
      }
      if (v.isInt() && n.isInt())
      {
        int ni = n.toInt();
        if (ni>0)
        {
          return TemplateVariant((v.toInt()%ni)==0);
        }
        else
        {
          return TemplateVariant(FALSE);
        }
      }
      else
      {
        return TemplateVariant();
      }
    }
References FALSE, TemplateVariant::isInt(), TemplateVariant::isValid(), n, and TemplateVariant::toInt().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp