TextGeneratorOLImpl Class Reference
#include <util.h>
Public Member Functions
TextGeneratorOLImpl (BaseOutputDocInterface &od)
void writeString (const QCString &s, bool keepSpaces) const
void writeBreak (int indent) const
void writeLink (const QCString &extRef, const QCString &file, const QCString &anchor, const QCString &text) const
TextGeneratorOLImpl (BaseOutputDocInterface &od)
void writeString (const QCString &s, bool keepSpaces) const
void writeBreak (int indent) const
void writeLink (const QCString &extRef, const QCString &file, const QCString &anchor, const QCString &text) const
Private Attributes
BaseOutputDocInterface & m_od
Detailed Description
Implements TextGeneratorIntf for an OutputDocInterface stream.
Definition at line 72 of file util.h.
Constructor & Destructor Documentation
TextGeneratorOLImpl() [1/2]
TextGeneratorOLImpl::TextGeneratorOLImpl (BaseOutputDocInterface & od)
Definition at line 101 of file util.cpp.
                                                                   : m_od(od)
{
}
TextGeneratorOLImpl() [2/2]
TextGeneratorOLImpl::TextGeneratorOLImpl (BaseOutputDocInterface & od)
Member Function Documentation
writeBreak() [1/2]
void TextGeneratorOLImpl::writeBreak (int indent) const [virtual]
Implements TextGeneratorIntf.
Definition at line 130 of file util.cpp.
{
  m_od.lineBreak("typebreak");
  int i;
  for (i=0;i<indent;i++)
  {
    m_od.writeNonBreakableSpace(3);
  }
}
References BaseOutputDocInterface::lineBreak(), m_od, and BaseOutputDocInterface::writeNonBreakableSpace().
writeBreak() [2/2]
void TextGeneratorOLImpl::writeBreak (int indent) const [virtual]
Implements TextGeneratorIntf.
writeLink() [1/2]
void TextGeneratorOLImpl::writeLink (const QCString & extRef, const QCString & file, const QCString & anchor, const QCString & text) const [virtual]
Implements TextGeneratorIntf.
Definition at line 140 of file util.cpp.
{
  //printf("TextGeneratorOlImpl::writeLink('%s')\n",text);
  m_od.writeObjectLink(extRef,file,anchor,text);
}
References caseconvert::file, m_od, and BaseOutputDocInterface::writeObjectLink().
writeLink() [2/2]
void TextGeneratorOLImpl::writeLink (const QCString & extRef, const QCString & file, const QCString & anchor, const QCString & text) const [virtual]
Implements TextGeneratorIntf.
writeString() [1/2]
void TextGeneratorOLImpl::writeString (const QCString & s, bool keepSpaces) const [virtual]
Implements TextGeneratorIntf.
Definition at line 105 of file util.cpp.
{
  if (s.isEmpty()) return;
  //printf("TextGeneratorOlImpl::writeString('%s',%d)\n",s,keepSpaces);
  if (keepSpaces)
  {
    const char *p=s.data();
    if (p)
    {
      char cs[2];
      char c;
      cs[1]='\0';
      while ((c=*p++))
      {
        if (c==' ') m_od.writeNonBreakableSpace(1);
        else cs[0]=c,m_od.docify(cs);
      }
    }
  }
  else
  {
    m_od.docify(s);
  }
}
References c, cs, gdFont::data, BaseOutputDocInterface::docify(), m_od, p, s, and BaseOutputDocInterface::writeNonBreakableSpace().
writeString() [2/2]
void TextGeneratorOLImpl::writeString (const QCString & s, bool keepSpaces) const [virtual]
Implements TextGeneratorIntf.
Member Data Documentation
m_od
BaseOutputDocInterface & TextGeneratorOLImpl::m_od [private]
Definition at line 82 of file util.h.
Referenced by writeBreak(), writeLink(), and writeString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/util.h
doxygen/src/util.h
doxygen/build/doxygen/src/util.cpp
doxygen/src/util.cpp