AlphaIndexTableCell Class Reference
Public Member Functions
AlphaIndexTableCell (int row, int col, const std::string &letter, const ClassDef *cd)
const ClassDef * classDef () const
std::string letter () const
int row () const
int column () const
AlphaIndexTableCell (int row, int col, const std::string &letter, const ClassDef *cd)
const ClassDef * classDef () const
std::string letter () const
int row () const
int column () const
Private Attributes
std::string m_letter
const ClassDef * m_class
int m_row
int m_col
Detailed Description
Class representing a cell in the alphabetical class index.
Definition at line 2056 of file index.cpp.
Constructor & Destructor Documentation
AlphaIndexTableCell() [1/2]
AlphaIndexTableCell::AlphaIndexTableCell (int row, int col, const std::string & letter, const ClassDef * cd) [inline]
Definition at line 2059 of file index.cpp.
                                                                                    :
      m_letter(letter), m_class(cd), m_row(row), m_col(col)
    {
    }
AlphaIndexTableCell() [2/2]
AlphaIndexTableCell::AlphaIndexTableCell (int row, int col, const std::string & letter, const ClassDef * cd) [inline]
Definition at line 2059 of file index.cpp.
                                                                                    :
      m_letter(letter), m_class(cd), m_row(row), m_col(col)
    {
    }
Member Function Documentation
classDef() [1/2]
const ClassDef * AlphaIndexTableCell::classDef () const [inline]
Definition at line 2064 of file index.cpp.
{ return m_class; }
References m_class.
classDef() [2/2]
const ClassDef * AlphaIndexTableCell::classDef () const [inline]
Definition at line 2064 of file index.cpp.
{ return m_class; }
References m_class.
column() [1/2]
int AlphaIndexTableCell::column () const [inline]
Definition at line 2067 of file index.cpp.
{ return m_col; }
References m_col.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_column(), and doxmlparser.compound.locationType::set_column().
column() [2/2]
int AlphaIndexTableCell::column () const [inline]
Definition at line 2067 of file index.cpp.
{ return m_col; }
References m_col.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_column(), and doxmlparser.compound.locationType::set_column().
letter() [1/2]
std::string AlphaIndexTableCell::letter () const [inline]
Definition at line 2065 of file index.cpp.
{ return m_letter; }
References m_letter.
letter() [2/2]
std::string AlphaIndexTableCell::letter () const [inline]
Definition at line 2065 of file index.cpp.
{ return m_letter; }
References m_letter.
row() [1/2]
int AlphaIndexTableCell::row () const [inline]
Definition at line 2066 of file index.cpp.
{ return m_row; }
References m_row.
Referenced by doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docTableType::add_row(), doxmlparser.compound.docTableType::buildChildren(), doxmlparser.compound.docTableType::exportChildren(), doxmlparser.compound.docTableType::get_row(), doxmlparser.compound.docTableType::hasContent_(), doxmlparser.compound.docTableType::insert_row_at(), doxmlparser.compound.docTableType::replace_row_at(), and doxmlparser.compound.docTableType::set_row().
row() [2/2]
int AlphaIndexTableCell::row () const [inline]
Definition at line 2066 of file index.cpp.
{ return m_row; }
References m_row.
Referenced by doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docTableType::add_row(), doxmlparser.compound.docTableType::buildChildren(), doxmlparser.compound.docTableType::exportChildren(), doxmlparser.compound.docTableType::get_row(), doxmlparser.compound.docTableType::hasContent_(), doxmlparser.compound.docTableType::insert_row_at(), doxmlparser.compound.docTableType::replace_row_at(), and doxmlparser.compound.docTableType::set_row().
Member Data Documentation
m_class
const ClassDef * AlphaIndexTableCell::m_class [private]
Definition at line 2071 of file index.cpp.
Referenced by classDef().
m_col
int AlphaIndexTableCell::m_col [private]
Definition at line 2073 of file index.cpp.
Referenced by column().
m_letter
std::string AlphaIndexTableCell::m_letter [private]
Definition at line 2070 of file index.cpp.
Referenced by letter().
m_row
int AlphaIndexTableCell::m_row [private]
Definition at line 2072 of file index.cpp.
Referenced by row().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/index.cpp
doxygen/src/index.cpp