DiagramItem Class Reference
Public Member Functions
DiagramItem (DiagramItem *p, uint number, const ClassDef *cd, Protection prot, Specifier virt, const QCString &ts)
QCString label () const
QCString fileName () const
DiagramItem * parentItem ()
DiagramItemList getChildren ()
void move (int dx, int dy)
uint xPos () const
uint yPos () const
float xfPos () const
float yfPos () const
uint avgChildPos () const
uint numChildren () const
void addChild (DiagramItem *di)
uint number () const
Protection protection () const
Specifier virtualness () const
void putInList ()
bool isInList () const
const ClassDef * getClassDef () const
DiagramItem (DiagramItem *p, uint number, const ClassDef *cd, Protection prot, Specifier virt, const QCString &ts)
QCString label () const
QCString fileName () const
DiagramItem * parentItem ()
DiagramItemList getChildren ()
void move (int dx, int dy)
uint xPos () const
uint yPos () const
float xfPos () const
float yfPos () const
uint avgChildPos () const
uint numChildren () const
void addChild (DiagramItem *di)
uint number () const
Protection protection () const
Specifier virtualness () const
void putInList ()
bool isInList () const
const ClassDef * getClassDef () const
Private Attributes
DiagramItemList m_children
DiagramItem * m_parent
uint m_x = 0
uint m_y = 0
uint m_num
Protection m_prot
Specifier m_virt
QCString m_templSpec
bool m_inList = false
const ClassDef * m_classDef
Detailed Description
Class representing a single node in the built-in class diagram
Definition at line 40 of file diagram.cpp.
Constructor & Destructor Documentation
DiagramItem() [1/2]
DiagramItem::DiagramItem (DiagramItem * p, uint number, const ClassDef * cd, Protection prot, Specifier virt, const QCString & ts)
Definition at line 278 of file diagram.cpp.
  : m_parent(p), m_num(number), m_prot(pr), m_virt(vi), m_templSpec(ts), m_classDef(cd)
{
}
DiagramItem() [2/2]
DiagramItem::DiagramItem (DiagramItem * p, uint number, const ClassDef * cd, Protection prot, Specifier virt, const QCString & ts)
Member Function Documentation
addChild() [1/2]
void DiagramItem::addChild (DiagramItem * di)
Definition at line 330 of file diagram.cpp.
{
  m_children.push_back(di);
}
References m_children.
addChild() [2/2]
void DiagramItem::addChild (DiagramItem * di)
avgChildPos() [1/2]
uint DiagramItem::avgChildPos () const
Definition at line 311 of file diagram.cpp.
{
  DiagramItem *di;
  size_t c=m_children.size();
  if (c==0) // no children -> don't move
    return xPos();
  if ((di=m_children.front())->isInList()) // children should be in a list
    return di->xPos();
  if (c&1) // odd number of children -> get pos of middle child
    return m_children.at(c/2)->xPos();
  else // even number of children -> get middle of most middle children
    return (m_children.at(c/2-1)->xPos()+m_children.at(c/2)->xPos())/2;
}
References c, m_children, and xPos().
Referenced by TreeDiagram::layoutTree().
avgChildPos() [2/2]
uint DiagramItem::avgChildPos () const
fileName() [1/2]
QCString DiagramItem::fileName () const
Definition at line 306 of file diagram.cpp.
{
  return m_classDef->getOutputFileBase();
}
References ClassDef::getOutputFileBase(), and m_classDef.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
QCString DiagramItem::fileName () const
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
getChildren() [1/2]
DiagramItemList DiagramItem::getChildren () [inline]
Definition at line 48 of file diagram.cpp.
{ return m_children; }
References m_children.
Referenced by TreeDiagram::drawConnectors(), TreeDiagram::layoutTree(), and TreeDiagram::moveChildren().
getChildren() [2/2]
DiagramItemList DiagramItem::getChildren () [inline]
Definition at line 48 of file diagram.cpp.
{ return m_children; }
References m_children.
getClassDef() [1/2]
const ClassDef * DiagramItem::getClassDef () const [inline]
Definition at line 62 of file diagram.cpp.
{ return m_classDef; }
References m_classDef.
Referenced by TreeDiagram::drawBoxes().
getClassDef() [2/2]
const ClassDef * DiagramItem::getClassDef () const [inline]
Definition at line 62 of file diagram.cpp.
{ return m_classDef; }
References m_classDef.
isInList() [1/2]
bool DiagramItem::isInList () const [inline]
Definition at line 61 of file diagram.cpp.
{ return m_inList; }
References m_inList.
Referenced by TreeDiagram::drawBoxes(), and TreeDiagram::drawConnectors().
isInList() [2/2]
bool DiagramItem::isInList () const [inline]
Definition at line 61 of file diagram.cpp.
{ return m_inList; }
References m_inList.
label() [1/2]
QCString DiagramItem::label () const
Definition at line 284 of file diagram.cpp.
{
  QCString result;
  if (!m_templSpec.isEmpty())
  {
    // we use classDef->name() here and not displayName() in order
    // to get the name used in the inheritance relation.
    QCString n = m_classDef->name();
    if (n.endsWith("-p"))
    {
      n = n.left(n.length()-2);
    }
    result=insertTemplateSpecifierInScope(n,m_templSpec);
  }
  else
  {
    result=m_classDef->displayName();
  }
  if (Config_getBool(HIDE_SCOPE_NAMES)) result=stripScope(result);
  return result;
}
References Config_getBool, ClassDef::displayName(), insertTemplateSpecifierInScope(), QCString::isEmpty(), m_classDef, m_templSpec, n, Definition::name(), and stripScope().
Referenced by doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.nodeType::buildChildren(), doxmlparser.compound.nodeType::exportChildren(), doxmlparser.compound.nodeType::get_label(), doxmlparser.compound.nodeType::hasContent_(), doxmlparser.compound.nodeType::set_label(), writeBitmapBox(), and writeVectorBox().
label() [2/2]
QCString DiagramItem::label () const
Referenced by doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.nodeType::buildChildren(), doxmlparser.compound.nodeType::exportChildren(), doxmlparser.compound.nodeType::get_label(), doxmlparser.compound.nodeType::hasContent_(), and doxmlparser.compound.nodeType::set_label().
move() [1/2]
void DiagramItem::move (int dx, int dy) [inline]
Definition at line 49 of file diagram.cpp.
{ m_x=static_cast<uint>(m_x+dx); m_y=static_cast<uint>(m_y+dy); }
References m_x, and m_y.
Referenced by ClassDiagram::ClassDiagram(), TreeDiagram::computeLayout(), and TreeDiagram::layoutTree().
move() [2/2]
void DiagramItem::move (int dx, int dy) [inline]
Definition at line 49 of file diagram.cpp.
{ m_x=static_cast<uint>(m_x+dx); m_y=static_cast<uint>(m_y+dy); }
References m_x, and m_y.
number() [1/2]
uint DiagramItem::number () const [inline]
Definition at line 57 of file diagram.cpp.
{ return m_num; }
References m_num.
Referenced by TreeDiagram::layoutTree().
number() [2/2]
uint DiagramItem::number () const [inline]
Definition at line 57 of file diagram.cpp.
{ return m_num; }
References m_num.
numChildren() [1/2]
uint DiagramItem::numChildren () const
Definition at line 325 of file diagram.cpp.
{
  return static_cast<uint>(m_children.size());
}
References m_children.
Referenced by TreeDiagram::computeLayout(), TreeDiagram::drawBoxes(), and TreeDiagram::layoutTree().
numChildren() [2/2]
uint DiagramItem::numChildren () const
parentItem() [1/2]
DiagramItem * DiagramItem::parentItem () [inline]
Definition at line 47 of file diagram.cpp.
{ return m_parent; }
References m_parent.
Referenced by TreeDiagram::computeLayout(), TreeDiagram::computeRows(), TreeDiagram::drawBoxes(), and TreeDiagram::drawConnectors().
parentItem() [2/2]
DiagramItem * DiagramItem::parentItem () [inline]
Definition at line 47 of file diagram.cpp.
{ return m_parent; }
References m_parent.
protection() [1/2]
Protection DiagramItem::protection () const [inline]
Definition at line 58 of file diagram.cpp.
{ return m_prot; }
References m_prot.
Referenced by TreeDiagram::drawConnectors().
protection() [2/2]
Protection DiagramItem::protection () const [inline]
Definition at line 58 of file diagram.cpp.
{ return m_prot; }
References m_prot.
putInList() [1/2]
void DiagramItem::putInList () [inline]
Definition at line 60 of file diagram.cpp.
{ m_inList=TRUE; }
References m_inList, and TRUE.
putInList() [2/2]
void DiagramItem::putInList () [inline]
Definition at line 60 of file diagram.cpp.
{ m_inList=TRUE; }
References m_inList, and TRUE.
virtualness() [1/2]
Specifier DiagramItem::virtualness () const [inline]
Definition at line 59 of file diagram.cpp.
{ return m_virt; }
References m_virt.
Referenced by writeBitmapBox(), and writeVectorBox().
virtualness() [2/2]
Specifier DiagramItem::virtualness () const [inline]
Definition at line 59 of file diagram.cpp.
{ return m_virt; }
References m_virt.
xfPos() [1/2]
float DiagramItem::xfPos () const [inline]
Definition at line 52 of file diagram.cpp.
{ return static_cast<float>(m_x); }
References m_x.
Referenced by TreeDiagram::drawBoxes(), and TreeDiagram::drawConnectors().
xfPos() [2/2]
float DiagramItem::xfPos () const [inline]
Definition at line 52 of file diagram.cpp.
{ return static_cast<float>(m_x); }
References m_x.
xPos() [1/2]
uint DiagramItem::xPos () const [inline]
Definition at line 50 of file diagram.cpp.
{ return m_x; }
References m_x.
Referenced by avgChildPos(), ClassDiagram::ClassDiagram(), TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), and TreeDiagram::layoutTree().
xPos() [2/2]
uint DiagramItem::xPos () const [inline]
Definition at line 50 of file diagram.cpp.
{ return m_x; }
References m_x.
yfPos() [1/2]
float DiagramItem::yfPos () const [inline]
Definition at line 53 of file diagram.cpp.
{ return static_cast<float>(m_y); }
References m_y.
Referenced by TreeDiagram::drawBoxes(), and TreeDiagram::drawConnectors().
yfPos() [2/2]
float DiagramItem::yfPos () const [inline]
Definition at line 53 of file diagram.cpp.
{ return static_cast<float>(m_y); }
References m_y.
yPos() [1/2]
uint DiagramItem::yPos () const [inline]
Definition at line 51 of file diagram.cpp.
{ return m_y; }
References m_y.
Referenced by TreeDiagram::drawBoxes(), and TreeDiagram::drawConnectors().
yPos() [2/2]
uint DiagramItem::yPos () const [inline]
Definition at line 51 of file diagram.cpp.
{ return m_y; }
References m_y.
Member Data Documentation
m_children
DiagramItemList DiagramItem::m_children [private]
Definition at line 64 of file diagram.cpp.
Referenced by addChild(), avgChildPos(), getChildren(), and numChildren().
m_classDef
const ClassDef * DiagramItem::m_classDef [private]
Definition at line 73 of file diagram.cpp.
Referenced by fileName(), getClassDef(), and label().
m_inList
bool DiagramItem::m_inList = false [private]
Definition at line 72 of file diagram.cpp.
Referenced by isInList(), and putInList().
m_num
uint DiagramItem::m_num [private]
Definition at line 68 of file diagram.cpp.
Referenced by number().
m_parent
DiagramItem * DiagramItem::m_parent [private]
Definition at line 65 of file diagram.cpp.
Referenced by parentItem().
m_prot
Protection DiagramItem::m_prot [private]
Definition at line 69 of file diagram.cpp.
Referenced by protection().
m_templSpec
QCString DiagramItem::m_templSpec [private]
Definition at line 71 of file diagram.cpp.
Referenced by label().
m_virt
Specifier DiagramItem::m_virt [private]
Definition at line 70 of file diagram.cpp.
Referenced by virtualness().
m_x
uint DiagramItem::m_x = 0 [private]
Definition at line 66 of file diagram.cpp.
Referenced by move(), xfPos(), and xPos().
m_y
uint DiagramItem::m_y = 0 [private]
Definition at line 67 of file diagram.cpp.
Referenced by move(), yfPos(), and yPos().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/diagram.cpp
doxygen/src/diagram.cpp