TranslateContext::Private Class Reference
Public Member Functions
Private ()
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private ()
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant handleGeneratedAt (const TemplateVariantList &args) const
TemplateVariant handleInheritanceDiagramFor (const TemplateVariantList &args) const
TemplateVariant handleCollaborationDiagramFor (const TemplateVariantList &args) const
TemplateVariant handleDirDependencyGraphFor (const TemplateVariantList &args) const
TemplateVariant handleInheritsList (const TemplateVariantList &args) const
TemplateVariant handleInheritedByList (const TemplateVariantList &args) const
TemplateVariant handleWriteList (const TemplateVariantList &args) const
TemplateVariant handleImplementedBy (const TemplateVariantList &args) const
TemplateVariant handleReimplementedBy (const TemplateVariantList &args) const
TemplateVariant handleSourceRefs (const TemplateVariantList &args) const
TemplateVariant handleSourceRefBys (const TemplateVariantList &args) const
TemplateVariant handleIncludeDependencyGraph (const TemplateVariantList &args) const
TemplateVariant generatedBy () const
TemplateVariant generatedAt () const
TemplateVariant inheritanceDiagramFor () const
TemplateVariant collaborationDiagramFor () const
TemplateVariant dirDependencyGraphFor () const
TemplateVariant search () const
TemplateVariant mainPage () const
TemplateVariant classes () const
TemplateVariant concepts () const
TemplateVariant conceptDefinition () const
TemplateVariant classList () const
TemplateVariant classListDescription () const
TemplateVariant classIndex () const
TemplateVariant namespaceIndex () const
TemplateVariant classHierarchy () const
TemplateVariant classMembers () const
TemplateVariant modules () const
TemplateVariant moduleIndex () const
TemplateVariant namespaces () const
TemplateVariant files () const
TemplateVariant fileIndex () const
TemplateVariant pages () const
TemplateVariant examples () const
TemplateVariant namespaceList () const
TemplateVariant namespaceMembers () const
TemplateVariant moduleDocumentation () const
TemplateVariant fileDocumentation () const
TemplateVariant fileList () const
TemplateVariant fileMembers () const
TemplateVariant fileMembersDescription () const
TemplateVariant namespaceMembersDescription () const
TemplateVariant classHierarchyDescription () const
TemplateVariant gotoGraphicalHierarchy () const
TemplateVariant gotoTextualHierarchy () const
TemplateVariant classMembersDescription () const
TemplateVariant relatedPagesDesc () const
TemplateVariant more () const
TemplateVariant detailedDesc () const
TemplateVariant inheritsList () const
TemplateVariant inheritedByList () const
TemplateVariant definedAtLineInSourceFile () const
TemplateVariant typeConstraints () const
TemplateVariant exampleList () const
TemplateVariant listOfAllMembers () const
TemplateVariant memberList () const
TemplateVariant theListOfAllMembers () const
TemplateVariant incInheritedMembers () const
TemplateVariant defineValue () const
TemplateVariant initialValue () const
TemplateVariant enumerationValues () const
TemplateVariant implements () const
TemplateVariant reimplements () const
TemplateVariant implementedBy () const
TemplateVariant reimplementedBy () const
TemplateVariant sourceRefs () const
TemplateVariant sourceRefBys () const
TemplateVariant callGraph () const
TemplateVariant callerGraph () const
TemplateVariant referencedByRelation () const
TemplateVariant referencesRelation () const
TemplateVariant inheritedFrom () const
TemplateVariant additionalInheritedMembers () const
TemplateVariant includeDependencyGraph () const
TemplateVariant includedByDependencyGraph () const
TemplateVariant gotoSourceCode () const
TemplateVariant gotoDocumentation () const
TemplateVariant constantgroups () const
TemplateVariant classDocumentation () const
TemplateVariant namespaceDocumentation () const
TemplateVariant compoundMembers () const
TemplateVariant detailLevel () const
TemplateVariant fileListDescription () const
TemplateVariant modulesDescription () const
TemplateVariant namespaceListDescription () const
TemplateVariant conceptListDescription () const
TemplateVariant directories () const
TemplateVariant all () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant related () const
TemplateVariant macros () const
TemplateVariant loading () const
TemplateVariant searching () const
TemplateVariant noMatches () const
TemplateVariant enumName () const
TemplateVariant enumValue () const
TemplateVariant referenceManual () const
TemplateVariant index () const
TemplateVariant panelSyncOn () const
TemplateVariant panelSyncOff () const
TemplateVariant providedByCategory () const
TemplateVariant extendsClass () const
TemplateVariant examplesDescription () const
TemplateVariant langString () const
TemplateVariant code () const
TemplateVariant handleGeneratedAt (const TemplateVariantList &args) const
TemplateVariant handleInheritanceDiagramFor (const TemplateVariantList &args) const
TemplateVariant handleCollaborationDiagramFor (const TemplateVariantList &args) const
TemplateVariant handleDirDependencyGraphFor (const TemplateVariantList &args) const
TemplateVariant handleInheritsList (const TemplateVariantList &args) const
TemplateVariant handleInheritedByList (const TemplateVariantList &args) const
TemplateVariant handleWriteList (const TemplateVariantList &args) const
TemplateVariant handleImplementedBy (const TemplateVariantList &args) const
TemplateVariant handleReimplementedBy (const TemplateVariantList &args) const
TemplateVariant handleSourceRefs (const TemplateVariantList &args) const
TemplateVariant handleSourceRefBys (const TemplateVariantList &args) const
TemplateVariant handleIncludeDependencyGraph (const TemplateVariantList &args) const
TemplateVariant generatedBy () const
TemplateVariant generatedAt () const
TemplateVariant inheritanceDiagramFor () const
TemplateVariant collaborationDiagramFor () const
TemplateVariant dirDependencyGraphFor () const
TemplateVariant search () const
TemplateVariant mainPage () const
TemplateVariant classes () const
TemplateVariant concepts () const
TemplateVariant conceptDefinition () const
TemplateVariant classList () const
TemplateVariant classListDescription () const
TemplateVariant classIndex () const
TemplateVariant namespaceIndex () const
TemplateVariant classHierarchy () const
TemplateVariant classMembers () const
TemplateVariant modules () const
TemplateVariant moduleIndex () const
TemplateVariant namespaces () const
TemplateVariant files () const
TemplateVariant fileIndex () const
TemplateVariant pages () const
TemplateVariant examples () const
TemplateVariant namespaceList () const
TemplateVariant namespaceMembers () const
TemplateVariant moduleDocumentation () const
TemplateVariant fileDocumentation () const
TemplateVariant fileList () const
TemplateVariant fileMembers () const
TemplateVariant fileMembersDescription () const
TemplateVariant namespaceMembersDescription () const
TemplateVariant classHierarchyDescription () const
TemplateVariant gotoGraphicalHierarchy () const
TemplateVariant gotoTextualHierarchy () const
TemplateVariant classMembersDescription () const
TemplateVariant relatedPagesDesc () const
TemplateVariant more () const
TemplateVariant detailedDesc () const
TemplateVariant inheritsList () const
TemplateVariant inheritedByList () const
TemplateVariant definedAtLineInSourceFile () const
TemplateVariant typeConstraints () const
TemplateVariant exampleList () const
TemplateVariant listOfAllMembers () const
TemplateVariant memberList () const
TemplateVariant theListOfAllMembers () const
TemplateVariant incInheritedMembers () const
TemplateVariant defineValue () const
TemplateVariant initialValue () const
TemplateVariant enumerationValues () const
TemplateVariant implements () const
TemplateVariant reimplements () const
TemplateVariant implementedBy () const
TemplateVariant reimplementedBy () const
TemplateVariant sourceRefs () const
TemplateVariant sourceRefBys () const
TemplateVariant callGraph () const
TemplateVariant callerGraph () const
TemplateVariant referencedByRelation () const
TemplateVariant referencesRelation () const
TemplateVariant inheritedFrom () const
TemplateVariant additionalInheritedMembers () const
TemplateVariant includeDependencyGraph () const
TemplateVariant includedByDependencyGraph () const
TemplateVariant gotoSourceCode () const
TemplateVariant gotoDocumentation () const
TemplateVariant constantgroups () const
TemplateVariant classDocumentation () const
TemplateVariant namespaceDocumentation () const
TemplateVariant compoundMembers () const
TemplateVariant detailLevel () const
TemplateVariant fileListDescription () const
TemplateVariant modulesDescription () const
TemplateVariant namespaceListDescription () const
TemplateVariant conceptListDescription () const
TemplateVariant directories () const
TemplateVariant all () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant related () const
TemplateVariant macros () const
TemplateVariant loading () const
TemplateVariant searching () const
TemplateVariant noMatches () const
TemplateVariant enumName () const
TemplateVariant enumValue () const
TemplateVariant referenceManual () const
TemplateVariant index () const
TemplateVariant panelSyncOn () const
TemplateVariant panelSyncOff () const
TemplateVariant providedByCategory () const
TemplateVariant extendsClass () const
TemplateVariant examplesDescription () const
TemplateVariant langString () const
TemplateVariant code () const
Private Attributes
bool m_javaOpt
bool m_fortranOpt
bool m_vhdlOpt
bool m_sliceOpt
Static Private Attributes
static const PropertyMap< TranslateContext::Private > s_inst
Detailed Description
Definition at line 391 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
TranslateContext::Private::Private () [inline]
Definition at line 395 of file context.cpp.
    {
      m_javaOpt = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
      m_fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
      m_vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      m_sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
    }
References Config_getBool, m_fortranOpt, m_javaOpt, m_sliceOpt, and m_vhdlOpt.
Private() [2/2]
TranslateContext::Private::Private () [inline]
Definition at line 395 of file context.cpp.
    {
      m_javaOpt = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
      m_fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
      m_vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      m_sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
    }
References Config_getBool.
Member Function Documentation
additionalInheritedMembers() [1/2]
TemplateVariant TranslateContext::Private::additionalInheritedMembers () const [inline], [private]
Definition at line 845 of file context.cpp.
    {
      return theTranslator->trAdditionalInheritedMembers();
    }
References theTranslator, and Translator::trAdditionalInheritedMembers().
additionalInheritedMembers() [2/2]
TemplateVariant TranslateContext::Private::additionalInheritedMembers () const [inline], [private]
Definition at line 845 of file context.cpp.
    {
      return theTranslator->trAdditionalInheritedMembers();
    }
References theTranslator, and Translator::trAdditionalInheritedMembers().
all() [1/2]
TemplateVariant TranslateContext::Private::all () const [inline], [private]
Definition at line 909 of file context.cpp.
    {
      return theTranslator->trAll();
    }
References theTranslator, and Translator::trAll().
all() [2/2]
TemplateVariant TranslateContext::Private::all () const [inline], [private]
Definition at line 909 of file context.cpp.
    {
      return theTranslator->trAll();
    }
References theTranslator, and Translator::trAll().
callerGraph() [1/2]
TemplateVariant TranslateContext::Private::callerGraph () const [inline], [private]
Definition at line 829 of file context.cpp.
    {
      return theTranslator->trCallerGraph();
    }
References theTranslator, and Translator::trCallerGraph().
callerGraph() [2/2]
TemplateVariant TranslateContext::Private::callerGraph () const [inline], [private]
Definition at line 829 of file context.cpp.
    {
      return theTranslator->trCallerGraph();
    }
References theTranslator, and Translator::trCallerGraph().
callGraph() [1/2]
TemplateVariant TranslateContext::Private::callGraph () const [inline], [private]
Definition at line 825 of file context.cpp.
    {
      return theTranslator->trCallGraph();
    }
References theTranslator, and Translator::trCallGraph().
callGraph() [2/2]
TemplateVariant TranslateContext::Private::callGraph () const [inline], [private]
Definition at line 825 of file context.cpp.
    {
      return theTranslator->trCallGraph();
    }
References theTranslator, and Translator::trCallGraph().
classDocumentation() [1/2]
TemplateVariant TranslateContext::Private::classDocumentation () const [inline], [private]
Definition at line 869 of file context.cpp.
    {
      return theTranslator->trClassDocumentation();
    }
References theTranslator, and Translator::trClassDocumentation().
classDocumentation() [2/2]
TemplateVariant TranslateContext::Private::classDocumentation () const [inline], [private]
Definition at line 869 of file context.cpp.
    {
      return theTranslator->trClassDocumentation();
    }
References theTranslator, and Translator::trClassDocumentation().
classes() [1/2]
TemplateVariant TranslateContext::Private::classes () const [inline], [private]
Definition at line 583 of file context.cpp.
    {
      return theTranslator->trClasses();
      // TODO: VHDL: theTranslator->trVhdlType(VhdlDocGen::ENTITY,FALSE)
      // TODO: Fortran: trDataTypes()
    }
References theTranslator, and Translator::trClasses().
classes() [2/2]
TemplateVariant TranslateContext::Private::classes () const [inline], [private]
Definition at line 583 of file context.cpp.
    {
      return theTranslator->trClasses();
      // TODO: VHDL: theTranslator->trVhdlType(VhdlDocGen::ENTITY,FALSE)
      // TODO: Fortran: trDataTypes()
    }
References theTranslator, and Translator::trClasses().
classHierarchy() [1/2]
TemplateVariant TranslateContext::Private::classHierarchy () const [inline], [private]
Definition at line 613 of file context.cpp.
    {
      return theTranslator->trClassHierarchy();
    }
References theTranslator, and Translator::trClassHierarchy().
classHierarchy() [2/2]
TemplateVariant TranslateContext::Private::classHierarchy () const [inline], [private]
Definition at line 613 of file context.cpp.
    {
      return theTranslator->trClassHierarchy();
    }
References theTranslator, and Translator::trClassHierarchy().
classHierarchyDescription() [1/2]
TemplateVariant TranslateContext::Private::classHierarchyDescription () const [inline], [private]
Definition at line 716 of file context.cpp.
    {
      return theTranslator->trClassHierarchyDescription();
    }
References theTranslator, and Translator::trClassHierarchyDescription().
classHierarchyDescription() [2/2]
TemplateVariant TranslateContext::Private::classHierarchyDescription () const [inline], [private]
Definition at line 716 of file context.cpp.
    {
      return theTranslator->trClassHierarchyDescription();
    }
References theTranslator, and Translator::trClassHierarchyDescription().
classIndex() [1/2]
TemplateVariant TranslateContext::Private::classIndex () const [inline], [private]
Definition at line 605 of file context.cpp.
    {
      return theTranslator->trCompoundIndex();
    }
References theTranslator, and Translator::trCompoundIndex().
classIndex() [2/2]
TemplateVariant TranslateContext::Private::classIndex () const [inline], [private]
Definition at line 605 of file context.cpp.
    {
      return theTranslator->trCompoundIndex();
    }
References theTranslator, and Translator::trCompoundIndex().
classList() [1/2]
TemplateVariant TranslateContext::Private::classList () const [inline], [private]
Definition at line 597 of file context.cpp.
    {
      return theTranslator->trCompoundList();
    }
References theTranslator, and Translator::trCompoundList().
classList() [2/2]
TemplateVariant TranslateContext::Private::classList () const [inline], [private]
Definition at line 597 of file context.cpp.
    {
      return theTranslator->trCompoundList();
    }
References theTranslator, and Translator::trCompoundList().
classListDescription() [1/2]
TemplateVariant TranslateContext::Private::classListDescription () const [inline], [private]
Definition at line 601 of file context.cpp.
    {
      return theTranslator->trCompoundListDescription();
    }
References theTranslator, and Translator::trCompoundListDescription().
classListDescription() [2/2]
TemplateVariant TranslateContext::Private::classListDescription () const [inline], [private]
Definition at line 601 of file context.cpp.
    {
      return theTranslator->trCompoundListDescription();
    }
References theTranslator, and Translator::trCompoundListDescription().
classMembers() [1/2]
TemplateVariant TranslateContext::Private::classMembers () const [inline], [private]
Definition at line 617 of file context.cpp.
    {
      return theTranslator->trCompoundMembers();
    }
References theTranslator, and Translator::trCompoundMembers().
classMembers() [2/2]
TemplateVariant TranslateContext::Private::classMembers () const [inline], [private]
Definition at line 617 of file context.cpp.
    {
      return theTranslator->trCompoundMembers();
    }
References theTranslator, and Translator::trCompoundMembers().
classMembersDescription() [1/2]
TemplateVariant TranslateContext::Private::classMembersDescription () const [inline], [private]
Definition at line 728 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
      if (fortranOpt)
      {
        return theTranslator->trCompoundMembersDescriptionFortran(extractAll);
      }
      else
      {
        return theTranslator->trCompoundMembersDescription(extractAll);
      }
    }
References Config_getBool, theTranslator, Translator::trCompoundMembersDescription(), and Translator::trCompoundMembersDescriptionFortran().
classMembersDescription() [2/2]
TemplateVariant TranslateContext::Private::classMembersDescription () const [inline], [private]
Definition at line 728 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
      if (fortranOpt)
      {
        return theTranslator->trCompoundMembersDescriptionFortran(extractAll);
      }
      else
      {
        return theTranslator->trCompoundMembersDescription(extractAll);
      }
    }
References Config_getBool, theTranslator, Translator::trCompoundMembersDescription(), and Translator::trCompoundMembersDescriptionFortran().
code() [1/2]
TemplateVariant TranslateContext::Private::code () const [inline], [private]
Definition at line 1002 of file context.cpp.
    {
      return theTranslator->trCode();
    }
References theTranslator, and Translator::trCode().
code() [2/2]
TemplateVariant TranslateContext::Private::code () const [inline], [private]
Definition at line 1002 of file context.cpp.
    {
      return theTranslator->trCode();
    }
References theTranslator, and Translator::trCode().
collaborationDiagramFor() [1/2]
TemplateVariant TranslateContext::Private::collaborationDiagramFor () const [inline], [private]
Definition at line 567 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleCollaborationDiagramFor,this,std::placeholders::_1));
    }
References handleCollaborationDiagramFor().
collaborationDiagramFor() [2/2]
TemplateVariant TranslateContext::Private::collaborationDiagramFor () const [inline], [private]
Definition at line 567 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleCollaborationDiagramFor,this,std::placeholders::_1));
    }
compoundMembers() [1/2]
TemplateVariant TranslateContext::Private::compoundMembers () const [inline], [private]
Definition at line 877 of file context.cpp.
    {
      return theTranslator->trCompoundMembers();
    }
References theTranslator, and Translator::trCompoundMembers().
compoundMembers() [2/2]
TemplateVariant TranslateContext::Private::compoundMembers () const [inline], [private]
Definition at line 877 of file context.cpp.
    {
      return theTranslator->trCompoundMembers();
    }
References theTranslator, and Translator::trCompoundMembers().
conceptDefinition() [1/2]
TemplateVariant TranslateContext::Private::conceptDefinition () const [inline], [private]
Definition at line 593 of file context.cpp.
    {
      return theTranslator->trConceptDefinition();
    }
References theTranslator, and Translator::trConceptDefinition().
conceptDefinition() [2/2]
TemplateVariant TranslateContext::Private::conceptDefinition () const [inline], [private]
Definition at line 593 of file context.cpp.
    {
      return theTranslator->trConceptDefinition();
    }
References theTranslator, and Translator::trConceptDefinition().
conceptListDescription() [1/2]
TemplateVariant TranslateContext::Private::conceptListDescription () const [inline], [private]
Definition at line 900 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      return theTranslator->trConceptListDescription(extractAll);
    }
References Config_getBool, theTranslator, and Translator::trConceptListDescription().
conceptListDescription() [2/2]
TemplateVariant TranslateContext::Private::conceptListDescription () const [inline], [private]
Definition at line 900 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      return theTranslator->trConceptListDescription(extractAll);
    }
References Config_getBool, theTranslator, and Translator::trConceptListDescription().
concepts() [1/2]
TemplateVariant TranslateContext::Private::concepts () const [inline], [private]
Definition at line 589 of file context.cpp.
    {
      return theTranslator->trConcept(true,false);
    }
References theTranslator, and Translator::trConcept().
concepts() [2/2]
TemplateVariant TranslateContext::Private::concepts () const [inline], [private]
Definition at line 589 of file context.cpp.
    {
      return theTranslator->trConcept(true,false);
    }
References theTranslator, and Translator::trConcept().
constantgroups() [1/2]
TemplateVariant TranslateContext::Private::constantgroups () const [inline], [private]
Definition at line 865 of file context.cpp.
    {
      return theTranslator->trConstantGroups();
    }
References theTranslator, and Translator::trConstantGroups().
constantgroups() [2/2]
TemplateVariant TranslateContext::Private::constantgroups () const [inline], [private]
Definition at line 865 of file context.cpp.
    {
      return theTranslator->trConstantGroups();
    }
References theTranslator, and Translator::trConstantGroups().
definedAtLineInSourceFile() [1/2]
TemplateVariant TranslateContext::Private::definedAtLineInSourceFile () const [inline], [private]
Definition at line 761 of file context.cpp.
    {
      return theTranslator->trDefinedAtLineInSourceFile();
    }
References theTranslator, and Translator::trDefinedAtLineInSourceFile().
definedAtLineInSourceFile() [2/2]
TemplateVariant TranslateContext::Private::definedAtLineInSourceFile () const [inline], [private]
Definition at line 761 of file context.cpp.
    {
      return theTranslator->trDefinedAtLineInSourceFile();
    }
References theTranslator, and Translator::trDefinedAtLineInSourceFile().
defineValue() [1/2]
TemplateVariant TranslateContext::Private::defineValue () const [inline], [private]
Definition at line 789 of file context.cpp.
    {
      return theTranslator->trDefineValue();
    }
References theTranslator, and Translator::trDefineValue().
defineValue() [2/2]
TemplateVariant TranslateContext::Private::defineValue () const [inline], [private]
Definition at line 789 of file context.cpp.
    {
      return theTranslator->trDefineValue();
    }
References theTranslator, and Translator::trDefineValue().
detailedDesc() [1/2]
TemplateVariant TranslateContext::Private::detailedDesc () const [inline], [private]
Definition at line 749 of file context.cpp.
    {
      return theTranslator->trDetailedDescription();
    }
References theTranslator, and Translator::trDetailedDescription().
detailedDesc() [2/2]
TemplateVariant TranslateContext::Private::detailedDesc () const [inline], [private]
Definition at line 749 of file context.cpp.
    {
      return theTranslator->trDetailedDescription();
    }
References theTranslator, and Translator::trDetailedDescription().
detailLevel() [1/2]
TemplateVariant TranslateContext::Private::detailLevel () const [inline], [private]
Definition at line 881 of file context.cpp.
    {
      return theTranslator->trDetailLevel();
    }
References theTranslator, and Translator::trDetailLevel().
detailLevel() [2/2]
TemplateVariant TranslateContext::Private::detailLevel () const [inline], [private]
Definition at line 881 of file context.cpp.
    {
      return theTranslator->trDetailLevel();
    }
References theTranslator, and Translator::trDetailLevel().
dirDependencyGraphFor() [1/2]
TemplateVariant TranslateContext::Private::dirDependencyGraphFor () const [inline], [private]
Definition at line 571 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleDirDependencyGraphFor,this,std::placeholders::_1));
    }
References handleDirDependencyGraphFor().
dirDependencyGraphFor() [2/2]
TemplateVariant TranslateContext::Private::dirDependencyGraphFor () const [inline], [private]
Definition at line 571 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleDirDependencyGraphFor,this,std::placeholders::_1));
    }
directories() [1/2]
TemplateVariant TranslateContext::Private::directories () const [inline], [private]
Definition at line 905 of file context.cpp.
    {
      return theTranslator->trDirectories();
    }
References theTranslator, and Translator::trDirectories().
directories() [2/2]
TemplateVariant TranslateContext::Private::directories () const [inline], [private]
Definition at line 905 of file context.cpp.
    {
      return theTranslator->trDirectories();
    }
References theTranslator, and Translator::trDirectories().
enumerationValues() [1/2]
TemplateVariant TranslateContext::Private::enumerationValues () const [inline], [private]
Definition at line 797 of file context.cpp.
    {
      return theTranslator->trEnumerationValues();
    }
References theTranslator, and Translator::trEnumerationValues().
enumerationValues() [2/2]
TemplateVariant TranslateContext::Private::enumerationValues () const [inline], [private]
Definition at line 797 of file context.cpp.
    {
      return theTranslator->trEnumerationValues();
    }
References theTranslator, and Translator::trEnumerationValues().
enumName() [1/2]
TemplateVariant TranslateContext::Private::enumName () const [inline], [private]
Definition at line 962 of file context.cpp.
    {
      return theTranslator->trEnumName();
    }
References theTranslator, and Translator::trEnumName().
enumName() [2/2]
TemplateVariant TranslateContext::Private::enumName () const [inline], [private]
Definition at line 962 of file context.cpp.
    {
      return theTranslator->trEnumName();
    }
References theTranslator, and Translator::trEnumName().
enums() [1/2]
TemplateVariant TranslateContext::Private::enums () const [inline], [private]
Definition at line 930 of file context.cpp.
    {
      return theTranslator->trEnumerations();
    }
References theTranslator, and Translator::trEnumerations().
enums() [2/2]
TemplateVariant TranslateContext::Private::enums () const [inline], [private]
Definition at line 930 of file context.cpp.
    {
      return theTranslator->trEnumerations();
    }
References theTranslator, and Translator::trEnumerations().
enumValue() [1/2]
TemplateVariant TranslateContext::Private::enumValue () const [inline], [private]
Definition at line 966 of file context.cpp.
    {
      return theTranslator->trEnumValue();
    }
References theTranslator, and Translator::trEnumValue().
enumValue() [2/2]
TemplateVariant TranslateContext::Private::enumValue () const [inline], [private]
Definition at line 966 of file context.cpp.
    {
      return theTranslator->trEnumValue();
    }
References theTranslator, and Translator::trEnumValue().
events() [1/2]
TemplateVariant TranslateContext::Private::events () const [inline], [private]
Definition at line 938 of file context.cpp.
    {
      return theTranslator->trEvents();
    }
References theTranslator, and Translator::trEvents().
events() [2/2]
TemplateVariant TranslateContext::Private::events () const [inline], [private]
Definition at line 938 of file context.cpp.
    {
      return theTranslator->trEvents();
    }
References theTranslator, and Translator::trEvents().
exampleList() [1/2]
TemplateVariant TranslateContext::Private::exampleList () const [inline], [private]
Definition at line 769 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleWriteList,this,std::placeholders::_1));
    }
References handleWriteList().
exampleList() [2/2]
TemplateVariant TranslateContext::Private::exampleList () const [inline], [private]
Definition at line 769 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleWriteList,this,std::placeholders::_1));
    }
examples() [1/2]
TemplateVariant TranslateContext::Private::examples () const [inline], [private]
Definition at line 656 of file context.cpp.
    {
      return theTranslator->trExamples();
    }
References theTranslator, and Translator::trExamples().
examples() [2/2]
TemplateVariant TranslateContext::Private::examples () const [inline], [private]
Definition at line 656 of file context.cpp.
    {
      return theTranslator->trExamples();
    }
References theTranslator, and Translator::trExamples().
examplesDescription() [1/2]
TemplateVariant TranslateContext::Private::examplesDescription () const [inline], [private]
Definition at line 994 of file context.cpp.
    {
      return theTranslator->trExamplesDescription();
    }
References theTranslator, and Translator::trExamplesDescription().
examplesDescription() [2/2]
TemplateVariant TranslateContext::Private::examplesDescription () const [inline], [private]
Definition at line 994 of file context.cpp.
    {
      return theTranslator->trExamplesDescription();
    }
References theTranslator, and Translator::trExamplesDescription().
extendsClass() [1/2]
TemplateVariant TranslateContext::Private::extendsClass () const [inline], [private]
Definition at line 990 of file context.cpp.
    {
      return theTranslator->trExtendsClass();
    }
References theTranslator, and Translator::trExtendsClass().
extendsClass() [2/2]
TemplateVariant TranslateContext::Private::extendsClass () const [inline], [private]
Definition at line 990 of file context.cpp.
    {
      return theTranslator->trExtendsClass();
    }
References theTranslator, and Translator::trExtendsClass().
fields() [1/2]
StringVector TranslateContext::Private::fields () const [inline]
Definition at line 405 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector TranslateContext::Private::fields () const [inline]
Definition at line 405 of file context.cpp.
{ return s_inst.fields(); }
fileDocumentation() [1/2]
TemplateVariant TranslateContext::Private::fileDocumentation () const [inline], [private]
Definition at line 694 of file context.cpp.
    {
      return theTranslator->trFileDocumentation();
    }
References theTranslator, and Translator::trFileDocumentation().
fileDocumentation() [2/2]
TemplateVariant TranslateContext::Private::fileDocumentation () const [inline], [private]
Definition at line 694 of file context.cpp.
    {
      return theTranslator->trFileDocumentation();
    }
References theTranslator, and Translator::trFileDocumentation().
fileIndex() [1/2]
TemplateVariant TranslateContext::Private::fileIndex () const [inline], [private]
Definition at line 648 of file context.cpp.
    {
      return theTranslator->trFileIndex();
    }
References theTranslator, and Translator::trFileIndex().
fileIndex() [2/2]
TemplateVariant TranslateContext::Private::fileIndex () const [inline], [private]
Definition at line 648 of file context.cpp.
    {
      return theTranslator->trFileIndex();
    }
References theTranslator, and Translator::trFileIndex().
fileList() [1/2]
TemplateVariant TranslateContext::Private::fileList () const [inline], [private]
Definition at line 698 of file context.cpp.
    {
      return theTranslator->trFileList();
    }
References theTranslator, and Translator::trFileList().
fileList() [2/2]
TemplateVariant TranslateContext::Private::fileList () const [inline], [private]
Definition at line 698 of file context.cpp.
    {
      return theTranslator->trFileList();
    }
References theTranslator, and Translator::trFileList().
fileListDescription() [1/2]
TemplateVariant TranslateContext::Private::fileListDescription () const [inline], [private]
Definition at line 885 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      return theTranslator->trFileListDescription(extractAll);
    }
References Config_getBool, theTranslator, and Translator::trFileListDescription().
fileListDescription() [2/2]
TemplateVariant TranslateContext::Private::fileListDescription () const [inline], [private]
Definition at line 885 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      return theTranslator->trFileListDescription(extractAll);
    }
References Config_getBool, theTranslator, and Translator::trFileListDescription().
fileMembers() [1/2]
TemplateVariant TranslateContext::Private::fileMembers () const [inline], [private]
Definition at line 702 of file context.cpp.
    {
      return theTranslator->trFileMembers();
    }
References theTranslator, and Translator::trFileMembers().
fileMembers() [2/2]
TemplateVariant TranslateContext::Private::fileMembers () const [inline], [private]
Definition at line 702 of file context.cpp.
    {
      return theTranslator->trFileMembers();
    }
References theTranslator, and Translator::trFileMembers().
fileMembersDescription() [1/2]
TemplateVariant TranslateContext::Private::fileMembersDescription () const [inline], [private]
Definition at line 706 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      return theTranslator->trFileMembersDescription(extractAll);
    }
References Config_getBool, theTranslator, and Translator::trFileMembersDescription().
fileMembersDescription() [2/2]
TemplateVariant TranslateContext::Private::fileMembersDescription () const [inline], [private]
Definition at line 706 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      return theTranslator->trFileMembersDescription(extractAll);
    }
References Config_getBool, theTranslator, and Translator::trFileMembersDescription().
files() [1/2]
TemplateVariant TranslateContext::Private::files () const [inline], [private]
Definition at line 644 of file context.cpp.
    {
      return theTranslator->trFile(TRUE,FALSE);
    }
References FALSE, theTranslator, Translator::trFile(), and TRUE.
files() [2/2]
TemplateVariant TranslateContext::Private::files () const [inline], [private]
Definition at line 644 of file context.cpp.
    {
      return theTranslator->trFile(TRUE,FALSE);
    }
References FALSE, theTranslator, Translator::trFile(), and TRUE.
functions() [1/2]
TemplateVariant TranslateContext::Private::functions () const [inline], [private]
Definition at line 913 of file context.cpp.
    {
      bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      return fortranOpt ? theTranslator->trSubprograms() :
             vhdlOpt ? theTranslator->trFunctionAndProc() :
                          theTranslator->trFunctions();
    }
References Config_getBool, theTranslator, Translator::trFunctionAndProc(), Translator::trFunctions(), and Translator::trSubprograms().
functions() [2/2]
TemplateVariant TranslateContext::Private::functions () const [inline], [private]
Definition at line 913 of file context.cpp.
    {
      bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      return fortranOpt ? theTranslator->trSubprograms() :
             vhdlOpt ? theTranslator->trFunctionAndProc() :
                          theTranslator->trFunctions();
    }
References Config_getBool, theTranslator, Translator::trFunctionAndProc(), Translator::trFunctions(), and Translator::trSubprograms().
generatedAt() [1/2]
TemplateVariant TranslateContext::Private::generatedAt () const [inline], [private]
Definition at line 559 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleGeneratedAt,this,std::placeholders::_1));
    }
References handleGeneratedAt().
generatedAt() [2/2]
TemplateVariant TranslateContext::Private::generatedAt () const [inline], [private]
Definition at line 559 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleGeneratedAt,this,std::placeholders::_1));
    }
generatedBy() [1/2]
TemplateVariant TranslateContext::Private::generatedBy () const [inline], [private]
Definition at line 555 of file context.cpp.
    {
      return theTranslator->trGeneratedBy();
    }
References theTranslator, and Translator::trGeneratedBy().
generatedBy() [2/2]
TemplateVariant TranslateContext::Private::generatedBy () const [inline], [private]
Definition at line 555 of file context.cpp.
    {
      return theTranslator->trGeneratedBy();
    }
References theTranslator, and Translator::trGeneratedBy().
get() [1/2]
TemplateVariant TranslateContext::Private::get (const QCString & n) const [inline]
Definition at line 404 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant TranslateContext::Private::get (const QCString & n) const [inline]
Definition at line 404 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
gotoDocumentation() [1/2]
TemplateVariant TranslateContext::Private::gotoDocumentation () const [inline], [private]
Definition at line 861 of file context.cpp.
    {
      return theTranslator->trGotoDocumentation();
    }
References theTranslator, and Translator::trGotoDocumentation().
gotoDocumentation() [2/2]
TemplateVariant TranslateContext::Private::gotoDocumentation () const [inline], [private]
Definition at line 861 of file context.cpp.
    {
      return theTranslator->trGotoDocumentation();
    }
References theTranslator, and Translator::trGotoDocumentation().
gotoGraphicalHierarchy() [1/2]
TemplateVariant TranslateContext::Private::gotoGraphicalHierarchy () const [inline], [private]
Definition at line 720 of file context.cpp.
    {
      return theTranslator->trGotoGraphicalHierarchy();
    }
References theTranslator, and Translator::trGotoGraphicalHierarchy().
gotoGraphicalHierarchy() [2/2]
TemplateVariant TranslateContext::Private::gotoGraphicalHierarchy () const [inline], [private]
Definition at line 720 of file context.cpp.
    {
      return theTranslator->trGotoGraphicalHierarchy();
    }
References theTranslator, and Translator::trGotoGraphicalHierarchy().
gotoSourceCode() [1/2]
TemplateVariant TranslateContext::Private::gotoSourceCode () const [inline], [private]
Definition at line 857 of file context.cpp.
    {
      return theTranslator->trGotoSourceCode();
    }
References theTranslator, and Translator::trGotoSourceCode().
gotoSourceCode() [2/2]
TemplateVariant TranslateContext::Private::gotoSourceCode () const [inline], [private]
Definition at line 857 of file context.cpp.
    {
      return theTranslator->trGotoSourceCode();
    }
References theTranslator, and Translator::trGotoSourceCode().
gotoTextualHierarchy() [1/2]
TemplateVariant TranslateContext::Private::gotoTextualHierarchy () const [inline], [private]
Definition at line 724 of file context.cpp.
    {
      return theTranslator->trGotoTextualHierarchy();
    }
References theTranslator, and Translator::trGotoTextualHierarchy().
gotoTextualHierarchy() [2/2]
TemplateVariant TranslateContext::Private::gotoTextualHierarchy () const [inline], [private]
Definition at line 724 of file context.cpp.
    {
      return theTranslator->trGotoTextualHierarchy();
    }
References theTranslator, and Translator::trGotoTextualHierarchy().
handleCollaborationDiagramFor() [1/2]
TemplateVariant TranslateContext::Private::handleCollaborationDiagramFor (const TemplateVariantList & args) const [inline], [private]
Definition at line 433 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trCollaborationDiagram(args[0].toString());
      }
      else
      {
        err("tr.collaborationDiagramFor should take one argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trCollaborationDiagram().
Referenced by collaborationDiagramFor().
handleCollaborationDiagramFor() [2/2]
TemplateVariant TranslateContext::Private::handleCollaborationDiagramFor (const TemplateVariantList & args) const [inline], [private]
Definition at line 433 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trCollaborationDiagram(args[0].toString());
      }
      else
      {
        err("tr.collaborationDiagramFor should take one argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trCollaborationDiagram().
handleDirDependencyGraphFor() [1/2]
TemplateVariant TranslateContext::Private::handleDirDependencyGraphFor (const TemplateVariantList & args) const [inline], [private]
Definition at line 445 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trDirDepGraph(args[0].toString());
      }
      else
      {
        err("tr.dirDependencyGraphFor should take one argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trDirDepGraph().
Referenced by dirDependencyGraphFor().
handleDirDependencyGraphFor() [2/2]
TemplateVariant TranslateContext::Private::handleDirDependencyGraphFor (const TemplateVariantList & args) const [inline], [private]
Definition at line 445 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trDirDepGraph(args[0].toString());
      }
      else
      {
        err("tr.dirDependencyGraphFor should take one argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trDirDepGraph().
handleGeneratedAt() [1/2]
TemplateVariant TranslateContext::Private::handleGeneratedAt (const TemplateVariantList & args) const [inline], [private]
Definition at line 409 of file context.cpp.
    {
      if (args.size()==2)
      {
        return theTranslator->trGeneratedAt(args[0].toString(),args[1].toString());
      }
      else
      {
        err("tr.generateAt should take two arguments, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trGeneratedAt().
Referenced by generatedAt().
handleGeneratedAt() [2/2]
TemplateVariant TranslateContext::Private::handleGeneratedAt (const TemplateVariantList & args) const [inline], [private]
Definition at line 409 of file context.cpp.
    {
      if (args.size()==2)
      {
        return theTranslator->trGeneratedAt(args[0].toString(),args[1].toString());
      }
      else
      {
        err("tr.generateAt should take two arguments, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trGeneratedAt().
handleImplementedBy() [1/2]
TemplateVariant TranslateContext::Private::handleImplementedBy (const TemplateVariantList & args) const [inline], [private]
Definition at line 493 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trImplementedInList(args[0].toInt());
      }
      else
      {
        err("tr.implementedBy should take one integer argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trImplementedInList().
Referenced by implementedBy().
handleImplementedBy() [2/2]
TemplateVariant TranslateContext::Private::handleImplementedBy (const TemplateVariantList & args) const [inline], [private]
Definition at line 493 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trImplementedInList(args[0].toInt());
      }
      else
      {
        err("tr.implementedBy should take one integer argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trImplementedInList().
handleIncludeDependencyGraph() [1/2]
TemplateVariant TranslateContext::Private::handleIncludeDependencyGraph (const TemplateVariantList & args) const [inline], [private]
Definition at line 541 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trInclDepGraph(args[0].toString());
      }
      else
      {
        err("tr.includeDependencyGraph should take one string argument, got %zu\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trInclDepGraph().
Referenced by includeDependencyGraph().
handleIncludeDependencyGraph() [2/2]
TemplateVariant TranslateContext::Private::handleIncludeDependencyGraph (const TemplateVariantList & args) const [inline], [private]
Definition at line 541 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trInclDepGraph(args[0].toString());
      }
      else
      {
        err("tr.includeDependencyGraph should take one string argument, got %zu\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trInclDepGraph().
handleInheritanceDiagramFor() [1/2]
TemplateVariant TranslateContext::Private::handleInheritanceDiagramFor (const TemplateVariantList & args) const [inline], [private]
Definition at line 421 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trClassDiagram(args[0].toString());
      }
      else
      {
        err("tr.inheritanceDiagramFor should take one argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trClassDiagram().
Referenced by inheritanceDiagramFor().
handleInheritanceDiagramFor() [2/2]
TemplateVariant TranslateContext::Private::handleInheritanceDiagramFor (const TemplateVariantList & args) const [inline], [private]
Definition at line 421 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trClassDiagram(args[0].toString());
      }
      else
      {
        err("tr.inheritanceDiagramFor should take one argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trClassDiagram().
handleInheritedByList() [1/2]
TemplateVariant TranslateContext::Private::handleInheritedByList (const TemplateVariantList & args) const [inline], [private]
Definition at line 469 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trInheritedByList(args[0].toInt());
      }
      else
      {
        err("tr.inheritedByList should take one integer argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trInheritedByList().
Referenced by inheritedByList().
handleInheritedByList() [2/2]
TemplateVariant TranslateContext::Private::handleInheritedByList (const TemplateVariantList & args) const [inline], [private]
Definition at line 469 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trInheritedByList(args[0].toInt());
      }
      else
      {
        err("tr.inheritedByList should take one integer argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trInheritedByList().
handleInheritsList() [1/2]
TemplateVariant TranslateContext::Private::handleInheritsList (const TemplateVariantList & args) const [inline], [private]
Definition at line 457 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trInheritsList(args[0].toInt());
      }
      else
      {
        err("tr.inheritsList should take one integer argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trInheritsList().
Referenced by inheritsList().
handleInheritsList() [2/2]
TemplateVariant TranslateContext::Private::handleInheritsList (const TemplateVariantList & args) const [inline], [private]
Definition at line 457 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trInheritsList(args[0].toInt());
      }
      else
      {
        err("tr.inheritsList should take one integer argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trInheritsList().
handleReimplementedBy() [1/2]
TemplateVariant TranslateContext::Private::handleReimplementedBy (const TemplateVariantList & args) const [inline], [private]
Definition at line 505 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trReimplementedInList(args[0].toInt());
      }
      else
      {
        err("tr.reimplementedBy should take one integer argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trReimplementedInList().
Referenced by reimplementedBy().
handleReimplementedBy() [2/2]
TemplateVariant TranslateContext::Private::handleReimplementedBy (const TemplateVariantList & args) const [inline], [private]
Definition at line 505 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trReimplementedInList(args[0].toInt());
      }
      else
      {
        err("tr.reimplementedBy should take one integer argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trReimplementedInList().
handleSourceRefBys() [1/2]
TemplateVariant TranslateContext::Private::handleSourceRefBys (const TemplateVariantList & args) const [inline], [private]
Definition at line 529 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trReferencedBy()+" "+theTranslator->trWriteList(args[0].toInt())+".";
      }
      else
      {
        err("tr.sourceRefBys should take one integer argument, got %zu\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, Translator::trReferencedBy(), and Translator::trWriteList().
Referenced by sourceRefBys().
handleSourceRefBys() [2/2]
TemplateVariant TranslateContext::Private::handleSourceRefBys (const TemplateVariantList & args) const [inline], [private]
Definition at line 529 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trReferencedBy()+" "+theTranslator->trWriteList(args[0].toInt())+".";
      }
      else
      {
        err("tr.sourceRefBys should take one integer argument, got %zu\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, Translator::trReferencedBy(), and Translator::trWriteList().
handleSourceRefs() [1/2]
TemplateVariant TranslateContext::Private::handleSourceRefs (const TemplateVariantList & args) const [inline], [private]
Definition at line 517 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trReferences()+" "+theTranslator->trWriteList(args[0].toInt())+".";
      }
      else
      {
        err("tr.sourceRefs should take one integer argument, got %zu\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, Translator::trReferences(), and Translator::trWriteList().
Referenced by sourceRefs().
handleSourceRefs() [2/2]
TemplateVariant TranslateContext::Private::handleSourceRefs (const TemplateVariantList & args) const [inline], [private]
Definition at line 517 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trReferences()+" "+theTranslator->trWriteList(args[0].toInt())+".";
      }
      else
      {
        err("tr.sourceRefs should take one integer argument, got %zu\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, Translator::trReferences(), and Translator::trWriteList().
handleWriteList() [1/2]
TemplateVariant TranslateContext::Private::handleWriteList (const TemplateVariantList & args) const [inline], [private]
Definition at line 481 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trWriteList(args[0].toInt());
      }
      else
      {
        err("tr.*List should take one integer argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trWriteList().
Referenced by exampleList().
handleWriteList() [2/2]
TemplateVariant TranslateContext::Private::handleWriteList (const TemplateVariantList & args) const [inline], [private]
Definition at line 481 of file context.cpp.
    {
      if (args.size()==1)
      {
        return theTranslator->trWriteList(args[0].toInt());
      }
      else
      {
        err("tr.*List should take one integer argument, got %zu!\n",args.size());
      }
      return TemplateVariant();
    }
References err(), theTranslator, and Translator::trWriteList().
implementedBy() [1/2]
TemplateVariant TranslateContext::Private::implementedBy () const [inline], [private]
Definition at line 809 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleImplementedBy,this,std::placeholders::_1));
    }
References handleImplementedBy().
implementedBy() [2/2]
TemplateVariant TranslateContext::Private::implementedBy () const [inline], [private]
Definition at line 809 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleImplementedBy,this,std::placeholders::_1));
    }
implements() [1/2]
TemplateVariant TranslateContext::Private::implements () const [inline], [private]
Definition at line 801 of file context.cpp.
    {
      return theTranslator->trImplementedFromList(1);
    }
References theTranslator, and Translator::trImplementedFromList().
implements() [2/2]
TemplateVariant TranslateContext::Private::implements () const [inline], [private]
Definition at line 801 of file context.cpp.
    {
      return theTranslator->trImplementedFromList(1);
    }
References theTranslator, and Translator::trImplementedFromList().
incInheritedMembers() [1/2]
TemplateVariant TranslateContext::Private::incInheritedMembers () const [inline], [private]
Definition at line 785 of file context.cpp.
    {
      return theTranslator->trIncludingInheritedMembers();
    }
References theTranslator, and Translator::trIncludingInheritedMembers().
incInheritedMembers() [2/2]
TemplateVariant TranslateContext::Private::incInheritedMembers () const [inline], [private]
Definition at line 785 of file context.cpp.
    {
      return theTranslator->trIncludingInheritedMembers();
    }
References theTranslator, and Translator::trIncludingInheritedMembers().
includedByDependencyGraph() [1/2]
TemplateVariant TranslateContext::Private::includedByDependencyGraph () const [inline], [private]
Definition at line 853 of file context.cpp.
    {
      return theTranslator->trInclByDepGraph();
    }
References theTranslator, and Translator::trInclByDepGraph().
includedByDependencyGraph() [2/2]
TemplateVariant TranslateContext::Private::includedByDependencyGraph () const [inline], [private]
Definition at line 853 of file context.cpp.
    {
      return theTranslator->trInclByDepGraph();
    }
References theTranslator, and Translator::trInclByDepGraph().
includeDependencyGraph() [1/2]
TemplateVariant TranslateContext::Private::includeDependencyGraph () const [inline], [private]
Definition at line 849 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleIncludeDependencyGraph,this,std::placeholders::_1));
    }
References handleIncludeDependencyGraph().
includeDependencyGraph() [2/2]
TemplateVariant TranslateContext::Private::includeDependencyGraph () const [inline], [private]
Definition at line 849 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleIncludeDependencyGraph,this,std::placeholders::_1));
    }
index() [1/2]
TemplateVariant TranslateContext::Private::index () const [inline], [private]
Definition at line 974 of file context.cpp.
    {
      return theTranslator->trRTFGeneralIndex();
    }
References theTranslator, and Translator::trRTFGeneralIndex().
index() [2/2]
TemplateVariant TranslateContext::Private::index () const [inline], [private]
Definition at line 974 of file context.cpp.
    {
      return theTranslator->trRTFGeneralIndex();
    }
References theTranslator, and Translator::trRTFGeneralIndex().
inheritanceDiagramFor() [1/2]
TemplateVariant TranslateContext::Private::inheritanceDiagramFor () const [inline], [private]
Definition at line 563 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleInheritanceDiagramFor,this,std::placeholders::_1));
    }
References handleInheritanceDiagramFor().
inheritanceDiagramFor() [2/2]
TemplateVariant TranslateContext::Private::inheritanceDiagramFor () const [inline], [private]
Definition at line 563 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleInheritanceDiagramFor,this,std::placeholders::_1));
    }
inheritedByList() [1/2]
TemplateVariant TranslateContext::Private::inheritedByList () const [inline], [private]
Definition at line 757 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleInheritedByList,this,std::placeholders::_1));
    }
References handleInheritedByList().
inheritedByList() [2/2]
TemplateVariant TranslateContext::Private::inheritedByList () const [inline], [private]
Definition at line 757 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleInheritedByList,this,std::placeholders::_1));
    }
inheritedFrom() [1/2]
TemplateVariant TranslateContext::Private::inheritedFrom () const [inline], [private]
Definition at line 841 of file context.cpp.
    {
      return theTranslator->trInheritedFrom("@0","@1");
    }
References theTranslator, and Translator::trInheritedFrom().
inheritedFrom() [2/2]
TemplateVariant TranslateContext::Private::inheritedFrom () const [inline], [private]
Definition at line 841 of file context.cpp.
    {
      return theTranslator->trInheritedFrom("@0","@1");
    }
References theTranslator, and Translator::trInheritedFrom().
inheritsList() [1/2]
TemplateVariant TranslateContext::Private::inheritsList () const [inline], [private]
Definition at line 753 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleInheritsList,this,std::placeholders::_1));
    }
References handleInheritsList().
inheritsList() [2/2]
TemplateVariant TranslateContext::Private::inheritsList () const [inline], [private]
Definition at line 753 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleInheritsList,this,std::placeholders::_1));
    }
initialValue() [1/2]
TemplateVariant TranslateContext::Private::initialValue () const [inline], [private]
Definition at line 793 of file context.cpp.
    {
      return theTranslator->trInitialValue();
    }
References theTranslator, and Translator::trInitialValue().
initialValue() [2/2]
TemplateVariant TranslateContext::Private::initialValue () const [inline], [private]
Definition at line 793 of file context.cpp.
    {
      return theTranslator->trInitialValue();
    }
References theTranslator, and Translator::trInitialValue().
langString() [1/2]
TemplateVariant TranslateContext::Private::langString () const [inline], [private]
Definition at line 998 of file context.cpp.
    {
      return theTranslator->getLanguageString();
    }
References Translator::getLanguageString(), and theTranslator.
langString() [2/2]
TemplateVariant TranslateContext::Private::langString () const [inline], [private]
Definition at line 998 of file context.cpp.
    {
      return theTranslator->getLanguageString();
    }
References Translator::getLanguageString(), and theTranslator.
listOfAllMembers() [1/2]
TemplateVariant TranslateContext::Private::listOfAllMembers () const [inline], [private]
Definition at line 773 of file context.cpp.
    {
      return theTranslator->trListOfAllMembers();
    }
References theTranslator, and Translator::trListOfAllMembers().
listOfAllMembers() [2/2]
TemplateVariant TranslateContext::Private::listOfAllMembers () const [inline], [private]
Definition at line 773 of file context.cpp.
    {
      return theTranslator->trListOfAllMembers();
    }
References theTranslator, and Translator::trListOfAllMembers().
loading() [1/2]
TemplateVariant TranslateContext::Private::loading () const [inline], [private]
Definition at line 950 of file context.cpp.
    {
      return theTranslator->trLoading();
    }
References theTranslator, and Translator::trLoading().
loading() [2/2]
TemplateVariant TranslateContext::Private::loading () const [inline], [private]
Definition at line 950 of file context.cpp.
    {
      return theTranslator->trLoading();
    }
References theTranslator, and Translator::trLoading().
macros() [1/2]
TemplateVariant TranslateContext::Private::macros () const [inline], [private]
Definition at line 946 of file context.cpp.
    {
      return theTranslator->trDefines();
    }
References theTranslator, and Translator::trDefines().
macros() [2/2]
TemplateVariant TranslateContext::Private::macros () const [inline], [private]
Definition at line 946 of file context.cpp.
    {
      return theTranslator->trDefines();
    }
References theTranslator, and Translator::trDefines().
mainPage() [1/2]
TemplateVariant TranslateContext::Private::mainPage () const [inline], [private]
Definition at line 579 of file context.cpp.
    {
      return theTranslator->trMainPage();
    }
References theTranslator, and Translator::trMainPage().
mainPage() [2/2]
TemplateVariant TranslateContext::Private::mainPage () const [inline], [private]
Definition at line 579 of file context.cpp.
    {
      return theTranslator->trMainPage();
    }
References theTranslator, and Translator::trMainPage().
memberList() [1/2]
TemplateVariant TranslateContext::Private::memberList () const [inline], [private]
Definition at line 777 of file context.cpp.
    {
      return theTranslator->trMemberList();
    }
References theTranslator, and Translator::trMemberList().
memberList() [2/2]
TemplateVariant TranslateContext::Private::memberList () const [inline], [private]
Definition at line 777 of file context.cpp.
    {
      return theTranslator->trMemberList();
    }
References theTranslator, and Translator::trMemberList().
moduleDocumentation() [1/2]
TemplateVariant TranslateContext::Private::moduleDocumentation () const [inline], [private]
Definition at line 690 of file context.cpp.
    {
      return theTranslator->trModuleDocumentation();
    }
References theTranslator, and Translator::trModuleDocumentation().
moduleDocumentation() [2/2]
TemplateVariant TranslateContext::Private::moduleDocumentation () const [inline], [private]
Definition at line 690 of file context.cpp.
    {
      return theTranslator->trModuleDocumentation();
    }
References theTranslator, and Translator::trModuleDocumentation().
moduleIndex() [1/2]
TemplateVariant TranslateContext::Private::moduleIndex () const [inline], [private]
Definition at line 625 of file context.cpp.
    {
      return theTranslator->trModuleIndex();
    }
References theTranslator, and Translator::trModuleIndex().
moduleIndex() [2/2]
TemplateVariant TranslateContext::Private::moduleIndex () const [inline], [private]
Definition at line 625 of file context.cpp.
    {
      return theTranslator->trModuleIndex();
    }
References theTranslator, and Translator::trModuleIndex().
modules() [1/2]
TemplateVariant TranslateContext::Private::modules () const [inline], [private]
Definition at line 621 of file context.cpp.
    {
      return theTranslator->trModules();
    }
References theTranslator, and Translator::trModules().
modules() [2/2]
TemplateVariant TranslateContext::Private::modules () const [inline], [private]
Definition at line 621 of file context.cpp.
    {
      return theTranslator->trModules();
    }
References theTranslator, and Translator::trModules().
modulesDescription() [1/2]
TemplateVariant TranslateContext::Private::modulesDescription () const [inline], [private]
Definition at line 890 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      return theTranslator->trModulesListDescription(extractAll);
    }
References Config_getBool, theTranslator, and Translator::trModulesListDescription().
modulesDescription() [2/2]
TemplateVariant TranslateContext::Private::modulesDescription () const [inline], [private]
Definition at line 890 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      return theTranslator->trModulesListDescription(extractAll);
    }
References Config_getBool, theTranslator, and Translator::trModulesListDescription().
more() [1/2]
TemplateVariant TranslateContext::Private::more () const [inline], [private]
Definition at line 745 of file context.cpp.
    {
      return theTranslator->trMore();
    }
References theTranslator, and Translator::trMore().
more() [2/2]
TemplateVariant TranslateContext::Private::more () const [inline], [private]
Definition at line 745 of file context.cpp.
    {
      return theTranslator->trMore();
    }
References theTranslator, and Translator::trMore().
namespaceDocumentation() [1/2]
TemplateVariant TranslateContext::Private::namespaceDocumentation () const [inline], [private]
Definition at line 873 of file context.cpp.
    {
      return theTranslator->trNamespaceDocumentation();
    }
References theTranslator, and Translator::trNamespaceDocumentation().
namespaceDocumentation() [2/2]
TemplateVariant TranslateContext::Private::namespaceDocumentation () const [inline], [private]
Definition at line 873 of file context.cpp.
    {
      return theTranslator->trNamespaceDocumentation();
    }
References theTranslator, and Translator::trNamespaceDocumentation().
namespaceIndex() [1/2]
TemplateVariant TranslateContext::Private::namespaceIndex () const [inline], [private]
Definition at line 609 of file context.cpp.
    {
      return theTranslator->trNamespaceIndex();
    }
References theTranslator, and Translator::trNamespaceIndex().
namespaceIndex() [2/2]
TemplateVariant TranslateContext::Private::namespaceIndex () const [inline], [private]
Definition at line 609 of file context.cpp.
    {
      return theTranslator->trNamespaceIndex();
    }
References theTranslator, and Translator::trNamespaceIndex().
namespaceList() [1/2]
TemplateVariant TranslateContext::Private::namespaceList () const [inline], [private]
Definition at line 660 of file context.cpp.
    {
      if (m_javaOpt || m_vhdlOpt)
      {
        return theTranslator->trPackageList();
      }
      else if (m_fortranOpt || m_sliceOpt)
      {
        return theTranslator->trModulesList();
      }
      else
      {
        return theTranslator->trNamespaceList();
      }
    }
References m_fortranOpt, m_javaOpt, m_sliceOpt, m_vhdlOpt, theTranslator, Translator::trModulesList(), Translator::trNamespaceList(), and Translator::trPackageList().
namespaceList() [2/2]
TemplateVariant TranslateContext::Private::namespaceList () const [inline], [private]
Definition at line 660 of file context.cpp.
    {
      if (m_javaOpt || m_vhdlOpt)
      {
        return theTranslator->trPackageList();
      }
      else if (m_fortranOpt || m_sliceOpt)
      {
        return theTranslator->trModulesList();
      }
      else
      {
        return theTranslator->trNamespaceList();
      }
    }
References theTranslator, Translator::trModulesList(), Translator::trNamespaceList(), and Translator::trPackageList().
namespaceListDescription() [1/2]
TemplateVariant TranslateContext::Private::namespaceListDescription () const [inline], [private]
Definition at line 895 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      return theTranslator->trNamespaceListDescription(extractAll);
    }
References Config_getBool, theTranslator, and Translator::trNamespaceListDescription().
namespaceListDescription() [2/2]
TemplateVariant TranslateContext::Private::namespaceListDescription () const [inline], [private]
Definition at line 895 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      return theTranslator->trNamespaceListDescription(extractAll);
    }
References Config_getBool, theTranslator, and Translator::trNamespaceListDescription().
namespaceMembers() [1/2]
TemplateVariant TranslateContext::Private::namespaceMembers () const [inline], [private]
Definition at line 675 of file context.cpp.
    {
      if (m_javaOpt || m_vhdlOpt)
      {
        return theTranslator->trPackageFunctions();
      }
      else if (m_fortranOpt || m_sliceOpt)
      {
        return theTranslator->trModulesMembers();
      }
      else
      {
        return theTranslator->trNamespaceMembers();
      }
    }
References m_fortranOpt, m_javaOpt, m_sliceOpt, m_vhdlOpt, theTranslator, Translator::trModulesMembers(), Translator::trNamespaceMembers(), and Translator::trPackageFunctions().
namespaceMembers() [2/2]
TemplateVariant TranslateContext::Private::namespaceMembers () const [inline], [private]
Definition at line 675 of file context.cpp.
    {
      if (m_javaOpt || m_vhdlOpt)
      {
        return theTranslator->trPackageFunctions();
      }
      else if (m_fortranOpt || m_sliceOpt)
      {
        return theTranslator->trModulesMembers();
      }
      else
      {
        return theTranslator->trNamespaceMembers();
      }
    }
References theTranslator, Translator::trModulesMembers(), Translator::trNamespaceMembers(), and Translator::trPackageFunctions().
namespaceMembersDescription() [1/2]
TemplateVariant TranslateContext::Private::namespaceMembersDescription () const [inline], [private]
Definition at line 711 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      return theTranslator->trNamespaceMemberDescription(extractAll);
    }
References Config_getBool, theTranslator, and Translator::trNamespaceMemberDescription().
namespaceMembersDescription() [2/2]
TemplateVariant TranslateContext::Private::namespaceMembersDescription () const [inline], [private]
Definition at line 711 of file context.cpp.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      return theTranslator->trNamespaceMemberDescription(extractAll);
    }
References Config_getBool, theTranslator, and Translator::trNamespaceMemberDescription().
namespaces() [1/2]
TemplateVariant TranslateContext::Private::namespaces () const [inline], [private]
Definition at line 629 of file context.cpp.
    {
      if (m_javaOpt || m_vhdlOpt)
      {
        return theTranslator->trPackages();
      }
      else if (m_fortranOpt || m_sliceOpt)
      {
        return theTranslator->trModules();
      }
      else
      {
        return theTranslator->trNamespaces();
      }
    }
References m_fortranOpt, m_javaOpt, m_sliceOpt, m_vhdlOpt, theTranslator, Translator::trModules(), Translator::trNamespaces(), and Translator::trPackages().
namespaces() [2/2]
TemplateVariant TranslateContext::Private::namespaces () const [inline], [private]
Definition at line 629 of file context.cpp.
    {
      if (m_javaOpt || m_vhdlOpt)
      {
        return theTranslator->trPackages();
      }
      else if (m_fortranOpt || m_sliceOpt)
      {
        return theTranslator->trModules();
      }
      else
      {
        return theTranslator->trNamespaces();
      }
    }
References theTranslator, Translator::trModules(), Translator::trNamespaces(), and Translator::trPackages().
noMatches() [1/2]
TemplateVariant TranslateContext::Private::noMatches () const [inline], [private]
Definition at line 958 of file context.cpp.
    {
      return theTranslator->trNoMatches();
    }
References theTranslator, and Translator::trNoMatches().
noMatches() [2/2]
TemplateVariant TranslateContext::Private::noMatches () const [inline], [private]
Definition at line 958 of file context.cpp.
    {
      return theTranslator->trNoMatches();
    }
References theTranslator, and Translator::trNoMatches().
pages() [1/2]
TemplateVariant TranslateContext::Private::pages () const [inline], [private]
Definition at line 652 of file context.cpp.
    {
      return theTranslator->trRelatedPages();
    }
References theTranslator, and Translator::trRelatedPages().
pages() [2/2]
TemplateVariant TranslateContext::Private::pages () const [inline], [private]
Definition at line 652 of file context.cpp.
    {
      return theTranslator->trRelatedPages();
    }
References theTranslator, and Translator::trRelatedPages().
panelSyncOff() [1/2]
TemplateVariant TranslateContext::Private::panelSyncOff () const [inline], [private]
Definition at line 982 of file context.cpp.
    {
      return theTranslator->trPanelSynchronisationTooltip(TRUE);
    }
References theTranslator, Translator::trPanelSynchronisationTooltip(), and TRUE.
panelSyncOff() [2/2]
TemplateVariant TranslateContext::Private::panelSyncOff () const [inline], [private]
Definition at line 982 of file context.cpp.
    {
      return theTranslator->trPanelSynchronisationTooltip(TRUE);
    }
References theTranslator, Translator::trPanelSynchronisationTooltip(), and TRUE.
panelSyncOn() [1/2]
TemplateVariant TranslateContext::Private::panelSyncOn () const [inline], [private]
Definition at line 978 of file context.cpp.
    {
      return theTranslator->trPanelSynchronisationTooltip(FALSE);
    }
References FALSE, theTranslator, and Translator::trPanelSynchronisationTooltip().
panelSyncOn() [2/2]
TemplateVariant TranslateContext::Private::panelSyncOn () const [inline], [private]
Definition at line 978 of file context.cpp.
    {
      return theTranslator->trPanelSynchronisationTooltip(FALSE);
    }
References FALSE, theTranslator, and Translator::trPanelSynchronisationTooltip().
properties() [1/2]
TemplateVariant TranslateContext::Private::properties () const [inline], [private]
Definition at line 934 of file context.cpp.
    {
      return theTranslator->trProperties();
    }
References theTranslator, and Translator::trProperties().
properties() [2/2]
TemplateVariant TranslateContext::Private::properties () const [inline], [private]
Definition at line 934 of file context.cpp.
    {
      return theTranslator->trProperties();
    }
References theTranslator, and Translator::trProperties().
providedByCategory() [1/2]
TemplateVariant TranslateContext::Private::providedByCategory () const [inline], [private]
Definition at line 986 of file context.cpp.
    {
      return theTranslator->trProvidedByCategory();
    }
References theTranslator, and Translator::trProvidedByCategory().
providedByCategory() [2/2]
TemplateVariant TranslateContext::Private::providedByCategory () const [inline], [private]
Definition at line 986 of file context.cpp.
    {
      return theTranslator->trProvidedByCategory();
    }
References theTranslator, and Translator::trProvidedByCategory().
referencedByRelation() [1/2]
TemplateVariant TranslateContext::Private::referencedByRelation () const [inline], [private]
Definition at line 833 of file context.cpp.
    {
      return theTranslator->trReferencedBy();
    }
References theTranslator, and Translator::trReferencedBy().
referencedByRelation() [2/2]
TemplateVariant TranslateContext::Private::referencedByRelation () const [inline], [private]
Definition at line 833 of file context.cpp.
    {
      return theTranslator->trReferencedBy();
    }
References theTranslator, and Translator::trReferencedBy().
referenceManual() [1/2]
TemplateVariant TranslateContext::Private::referenceManual () const [inline], [private]
Definition at line 970 of file context.cpp.
    {
      return theTranslator->trReferenceManual();
    }
References theTranslator, and Translator::trReferenceManual().
referenceManual() [2/2]
TemplateVariant TranslateContext::Private::referenceManual () const [inline], [private]
Definition at line 970 of file context.cpp.
    {
      return theTranslator->trReferenceManual();
    }
References theTranslator, and Translator::trReferenceManual().
referencesRelation() [1/2]
TemplateVariant TranslateContext::Private::referencesRelation () const [inline], [private]
Definition at line 837 of file context.cpp.
    {
      return theTranslator->trReferences();
    }
References theTranslator, and Translator::trReferences().
referencesRelation() [2/2]
TemplateVariant TranslateContext::Private::referencesRelation () const [inline], [private]
Definition at line 837 of file context.cpp.
    {
      return theTranslator->trReferences();
    }
References theTranslator, and Translator::trReferences().
reimplementedBy() [1/2]
TemplateVariant TranslateContext::Private::reimplementedBy () const [inline], [private]
Definition at line 813 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleReimplementedBy,this,std::placeholders::_1));
    }
References handleReimplementedBy().
reimplementedBy() [2/2]
TemplateVariant TranslateContext::Private::reimplementedBy () const [inline], [private]
Definition at line 813 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleReimplementedBy,this,std::placeholders::_1));
    }
reimplements() [1/2]
TemplateVariant TranslateContext::Private::reimplements () const [inline], [private]
Definition at line 805 of file context.cpp.
    {
      return theTranslator->trReimplementedFromList(1);
    }
References theTranslator, and Translator::trReimplementedFromList().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::add_reimplements(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_reimplements(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.memberdefType::insert_reimplements_at(), doxmlparser.compound.memberdefType::replace_reimplements_at(), and doxmlparser.compound.memberdefType::set_reimplements().
reimplements() [2/2]
TemplateVariant TranslateContext::Private::reimplements () const [inline], [private]
Definition at line 805 of file context.cpp.
    {
      return theTranslator->trReimplementedFromList(1);
    }
References theTranslator, and Translator::trReimplementedFromList().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::add_reimplements(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_reimplements(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.memberdefType::insert_reimplements_at(), doxmlparser.compound.memberdefType::replace_reimplements_at(), and doxmlparser.compound.memberdefType::set_reimplements().
related() [1/2]
TemplateVariant TranslateContext::Private::related () const [inline], [private]
Definition at line 942 of file context.cpp.
    {
      return theTranslator->trRelatedFunctions();
    }
References theTranslator, and Translator::trRelatedFunctions().
related() [2/2]
TemplateVariant TranslateContext::Private::related () const [inline], [private]
Definition at line 942 of file context.cpp.
    {
      return theTranslator->trRelatedFunctions();
    }
References theTranslator, and Translator::trRelatedFunctions().
relatedPagesDesc() [1/2]
TemplateVariant TranslateContext::Private::relatedPagesDesc () const [inline], [private]
Definition at line 741 of file context.cpp.
    {
      return theTranslator->trRelatedPagesDescription();
    }
References theTranslator, and Translator::trRelatedPagesDescription().
relatedPagesDesc() [2/2]
TemplateVariant TranslateContext::Private::relatedPagesDesc () const [inline], [private]
Definition at line 741 of file context.cpp.
    {
      return theTranslator->trRelatedPagesDescription();
    }
References theTranslator, and Translator::trRelatedPagesDescription().
search() [1/2]
TemplateVariant TranslateContext::Private::search () const [inline], [private]
Definition at line 575 of file context.cpp.
    {
      return theTranslator->trSearch();
    }
References theTranslator, and Translator::trSearch().
search() [2/2]
TemplateVariant TranslateContext::Private::search () const [inline], [private]
Definition at line 575 of file context.cpp.
    {
      return theTranslator->trSearch();
    }
References theTranslator, and Translator::trSearch().
searching() [1/2]
TemplateVariant TranslateContext::Private::searching () const [inline], [private]
Definition at line 954 of file context.cpp.
    {
      return theTranslator->trSearching();
    }
References theTranslator, and Translator::trSearching().
searching() [2/2]
TemplateVariant TranslateContext::Private::searching () const [inline], [private]
Definition at line 954 of file context.cpp.
    {
      return theTranslator->trSearching();
    }
References theTranslator, and Translator::trSearching().
sourceRefBys() [1/2]
TemplateVariant TranslateContext::Private::sourceRefBys () const [inline], [private]
Definition at line 821 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleSourceRefBys,this,std::placeholders::_1));
    }
References handleSourceRefBys().
sourceRefBys() [2/2]
TemplateVariant TranslateContext::Private::sourceRefBys () const [inline], [private]
Definition at line 821 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleSourceRefBys,this,std::placeholders::_1));
    }
sourceRefs() [1/2]
TemplateVariant TranslateContext::Private::sourceRefs () const [inline], [private]
Definition at line 817 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleSourceRefs,this,std::placeholders::_1));
    }
References handleSourceRefs().
sourceRefs() [2/2]
TemplateVariant TranslateContext::Private::sourceRefs () const [inline], [private]
Definition at line 817 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleSourceRefs,this,std::placeholders::_1));
    }
theListOfAllMembers() [1/2]
TemplateVariant TranslateContext::Private::theListOfAllMembers () const [inline], [private]
Definition at line 781 of file context.cpp.
    {
      return theTranslator->trThisIsTheListOfAllMembers();
    }
References theTranslator, and Translator::trThisIsTheListOfAllMembers().
theListOfAllMembers() [2/2]
TemplateVariant TranslateContext::Private::theListOfAllMembers () const [inline], [private]
Definition at line 781 of file context.cpp.
    {
      return theTranslator->trThisIsTheListOfAllMembers();
    }
References theTranslator, and Translator::trThisIsTheListOfAllMembers().
typeConstraints() [1/2]
TemplateVariant TranslateContext::Private::typeConstraints () const [inline], [private]
Definition at line 765 of file context.cpp.
    {
      return theTranslator->trTypeConstraints();
    }
References theTranslator, and Translator::trTypeConstraints().
typeConstraints() [2/2]
TemplateVariant TranslateContext::Private::typeConstraints () const [inline], [private]
Definition at line 765 of file context.cpp.
    {
      return theTranslator->trTypeConstraints();
    }
References theTranslator, and Translator::trTypeConstraints().
typedefs() [1/2]
TemplateVariant TranslateContext::Private::typedefs () const [inline], [private]
Definition at line 926 of file context.cpp.
    {
      return theTranslator->trTypedefs();
    }
References theTranslator, and Translator::trTypedefs().
typedefs() [2/2]
TemplateVariant TranslateContext::Private::typedefs () const [inline], [private]
Definition at line 926 of file context.cpp.
    {
      return theTranslator->trTypedefs();
    }
References theTranslator, and Translator::trTypedefs().
variables() [1/2]
TemplateVariant TranslateContext::Private::variables () const [inline], [private]
Definition at line 921 of file context.cpp.
    {
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      return sliceOpt ? theTranslator->trConstants() : theTranslator->trVariables();
    }
References Config_getBool, theTranslator, Translator::trConstants(), and Translator::trVariables().
variables() [2/2]
TemplateVariant TranslateContext::Private::variables () const [inline], [private]
Definition at line 921 of file context.cpp.
    {
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      return sliceOpt ? theTranslator->trConstants() : theTranslator->trVariables();
    }
References Config_getBool, theTranslator, Translator::trConstants(), and Translator::trVariables().
Member Data Documentation
m_fortranOpt
bool TranslateContext::Private::m_fortranOpt [private]
Definition at line 1009 of file context.cpp.
Referenced by namespaceList(), namespaceMembers(), namespaces(), and Private().
m_javaOpt
bool TranslateContext::Private::m_javaOpt [private]
Definition at line 1008 of file context.cpp.
Referenced by namespaceList(), namespaceMembers(), namespaces(), and Private().
m_sliceOpt
bool TranslateContext::Private::m_sliceOpt [private]
Definition at line 1011 of file context.cpp.
Referenced by namespaceList(), namespaceMembers(), namespaces(), and Private().
m_vhdlOpt
bool TranslateContext::Private::m_vhdlOpt [private]
Definition at line 1010 of file context.cpp.
Referenced by namespaceList(), namespaceMembers(), namespaces(), and Private().
s_inst
const PropertyMap< TranslateContext::Private > TranslateContext::Private::s_inst [static], [private]
Definition at line 1012 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp