TranslatorAdapter_1_8_4 Class Reference
#include <translator_adapter.h>
Public Member Functions
virtual QCString updateNeededMessage ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString updateNeededMessage ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
Additional Inherited Members
Detailed Description
Definition at line 222 of file translator_adapter.h.
Member Function Documentation
trConstantGroupReference() [1/2]
virtual QCString TranslatorAdapter_1_8_4::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
Implements Translator.
Definition at line 237 of file translator_adapter.h.
    { return english.trConstantGroupReference(namespaceName); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConstantGroupReference().
trConstantGroupReference() [2/2]
virtual QCString TranslatorAdapter_1_8_4::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
Implements Translator.
Definition at line 237 of file translator_adapter.h.
    { return english.trConstantGroupReference(namespaceName); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConstantGroupReference().
trConstantGroups() [1/2]
virtual QCString TranslatorAdapter_1_8_4::trConstantGroups () [inline], [virtual]
Implements Translator.
Definition at line 234 of file translator_adapter.h.
    { return english.trConstantGroups(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConstantGroups().
trConstantGroups() [2/2]
virtual QCString TranslatorAdapter_1_8_4::trConstantGroups () [inline], [virtual]
Implements Translator.
Definition at line 234 of file translator_adapter.h.
    { return english.trConstantGroups(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConstantGroups().
trInterfaces() [1/2]
virtual QCString TranslatorAdapter_1_8_4::trInterfaces () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorArabic, TranslatorNorwegian, TranslatorPolish, TranslatorSerbian, TranslatorArabic, TranslatorNorwegian, TranslatorPolish, and TranslatorSerbian.
Definition at line 228 of file translator_adapter.h.
    { return english.trInterfaces(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaces().
trInterfaces() [2/2]
virtual QCString TranslatorAdapter_1_8_4::trInterfaces () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorArabic, TranslatorNorwegian, TranslatorPolish, TranslatorSerbian, TranslatorArabic, TranslatorNorwegian, TranslatorPolish, and TranslatorSerbian.
Definition at line 228 of file translator_adapter.h.
    { return english.trInterfaces(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaces().
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorAdapter_1_8_4::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
Implements Translator.
Definition at line 246 of file translator_adapter.h.
    { return english.trServiceGeneratedFromFiles(single); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trServiceGeneratedFromFiles().
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorAdapter_1_8_4::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
Implements Translator.
Definition at line 246 of file translator_adapter.h.
    { return english.trServiceGeneratedFromFiles(single); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trServiceGeneratedFromFiles().
trServiceReference() [1/2]
virtual QCString TranslatorAdapter_1_8_4::trServiceReference (const QCString & sName) [inline], [virtual]
Implements Translator.
Definition at line 240 of file translator_adapter.h.
    { return english.trServiceReference(sName); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trServiceReference().
trServiceReference() [2/2]
virtual QCString TranslatorAdapter_1_8_4::trServiceReference (const QCString & sName) [inline], [virtual]
Implements Translator.
Definition at line 240 of file translator_adapter.h.
    { return english.trServiceReference(sName); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trServiceReference().
trServices() [1/2]
virtual QCString TranslatorAdapter_1_8_4::trServices () [inline], [virtual]
Implements Translator.
Definition at line 231 of file translator_adapter.h.
    { return english.trServices(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trServices().
trServices() [2/2]
virtual QCString TranslatorAdapter_1_8_4::trServices () [inline], [virtual]
Implements Translator.
Definition at line 231 of file translator_adapter.h.
    { return english.trServices(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trServices().
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorAdapter_1_8_4::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
Implements Translator.
Definition at line 249 of file translator_adapter.h.
    { return english.trSingletonGeneratedFromFiles(single); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSingletonGeneratedFromFiles().
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorAdapter_1_8_4::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
Implements Translator.
Definition at line 249 of file translator_adapter.h.
    { return english.trSingletonGeneratedFromFiles(single); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSingletonGeneratedFromFiles().
trSingletonReference() [1/2]
virtual QCString TranslatorAdapter_1_8_4::trSingletonReference (const QCString & sName) [inline], [virtual]
Implements Translator.
Definition at line 243 of file translator_adapter.h.
    { return english.trSingletonReference(sName); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSingletonReference().
trSingletonReference() [2/2]
virtual QCString TranslatorAdapter_1_8_4::trSingletonReference (const QCString & sName) [inline], [virtual]
Implements Translator.
Definition at line 243 of file translator_adapter.h.
    { return english.trSingletonReference(sName); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSingletonReference().
updateNeededMessage() [1/2]
virtual QCString TranslatorAdapter_1_8_4::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_8_15.
Reimplemented in TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 225 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.8.4"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
updateNeededMessage() [2/2]
virtual QCString TranslatorAdapter_1_8_4::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_8_15.
Reimplemented in TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 225 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.8.4"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_adapter.h
doxygen/src/translator_adapter.h