NamespaceDefMutable Class Reference
#include <namespacedef.h>
Public Member Functions
virtual void setMetaData (const QCString &m)=0
virtual void insertUsedFile (FileDef *fd)=0
virtual void writeDocumentation (OutputList &ol)=0
virtual void writeMemberPages (OutputList &ol)=0
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const =0
virtual void writeTagFile (TextStream &)=0
virtual void insertClass (const ClassDef *cd)=0
virtual void insertConcept (const ConceptDef *cd)=0
virtual void insertNamespace (const NamespaceDef *nd)=0
virtual void insertMember (MemberDef *md)=0
virtual void computeAnchors ()=0
virtual void countMembers ()=0
virtual void addMembersToMemberGroup ()=0
virtual void distributeMemberGroupDocumentation ()=0
virtual void findSectionsInDocumentation ()=0
virtual void sortMemberLists ()=0
virtual void addInnerCompound (const Definition *d)=0
virtual void addListReferences ()=0
virtual void setFileName (const QCString &fn)=0
virtual void combineUsingRelations (NamespaceDefSet &visitedNamespace)=0
virtual void addUsingDirective (const NamespaceDef *nd)=0
virtual void addUsingDeclaration (const ClassDef *cd)=0
virtual void setInline (bool isInline)=0
virtual void setMetaData (const QCString &m)=0
virtual void insertUsedFile (FileDef *fd)=0
virtual void writeDocumentation (OutputList &ol)=0
virtual void writeMemberPages (OutputList &ol)=0
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const =0
virtual void writeTagFile (TextStream &)=0
virtual void insertClass (const ClassDef *cd)=0
virtual void insertConcept (const ConceptDef *cd)=0
virtual void insertNamespace (const NamespaceDef *nd)=0
virtual void insertMember (MemberDef *md)=0
virtual void computeAnchors ()=0
virtual void countMembers ()=0
virtual void addMembersToMemberGroup ()=0
virtual void distributeMemberGroupDocumentation ()=0
virtual void findSectionsInDocumentation ()=0
virtual void sortMemberLists ()=0
virtual void addInnerCompound (const Definition *d)=0
virtual void addListReferences ()=0
virtual void setFileName (const QCString &fn)=0
virtual void combineUsingRelations (NamespaceDefSet &visitedNamespace)=0
virtual void addUsingDirective (const NamespaceDef *nd)=0
virtual void addUsingDeclaration (const ClassDef *cd)=0
virtual void setInline (bool isInline)=0
Additional Inherited Members
Detailed Description
Definition at line 105 of file namespacedef.h.
Member Function Documentation
addInnerCompound() [1/2]
virtual void NamespaceDefMutable::addInnerCompound (const Definition * d) [pure virtual]
Implements DefinitionMutable.
Implemented in NamespaceDefImpl, NamespaceDefImpl, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< NamespaceDefMutable >.
addInnerCompound() [2/2]
virtual void NamespaceDefMutable::addInnerCompound (const Definition * d) [pure virtual]
Implements DefinitionMutable.
Implemented in NamespaceDefImpl, NamespaceDefImpl, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< NamespaceDefMutable >.
addListReferences() [1/2]
virtual void NamespaceDefMutable::addListReferences () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by addListReferences().
addListReferences() [2/2]
virtual void NamespaceDefMutable::addListReferences () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
addMembersToMemberGroup() [1/2]
virtual void NamespaceDefMutable::addMembersToMemberGroup () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by addMembersToMemberGroup().
addMembersToMemberGroup() [2/2]
virtual void NamespaceDefMutable::addMembersToMemberGroup () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
addUsingDeclaration() [1/2]
virtual void NamespaceDefMutable::addUsingDeclaration (const ClassDef * cd) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by findUsingDeclarations().
addUsingDeclaration() [2/2]
virtual void NamespaceDefMutable::addUsingDeclaration (const ClassDef * cd) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
addUsingDirective() [1/2]
virtual void NamespaceDefMutable::addUsingDirective (const NamespaceDef * nd) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by findUsingDirectives().
addUsingDirective() [2/2]
virtual void NamespaceDefMutable::addUsingDirective (const NamespaceDef * nd) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
combineUsingRelations() [1/2]
virtual void NamespaceDefMutable::combineUsingRelations (NamespaceDefSet & visitedNamespace) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by combineUsingRelations(), FileDefImpl::combineUsingRelations(), and NamespaceDefImpl::combineUsingRelations().
combineUsingRelations() [2/2]
virtual void NamespaceDefMutable::combineUsingRelations (NamespaceDefSet & visitedNamespace) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
computeAnchors() [1/2]
virtual void NamespaceDefMutable::computeAnchors () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by computeMemberReferences().
computeAnchors() [2/2]
virtual void NamespaceDefMutable::computeAnchors () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
countMembers() [1/2]
virtual void NamespaceDefMutable::countMembers () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by countMembers().
countMembers() [2/2]
virtual void NamespaceDefMutable::countMembers () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
distributeMemberGroupDocumentation() [1/2]
virtual void NamespaceDefMutable::distributeMemberGroupDocumentation () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by distributeMemberGroupDocumentation().
distributeMemberGroupDocumentation() [2/2]
virtual void NamespaceDefMutable::distributeMemberGroupDocumentation () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
findSectionsInDocumentation() [1/2]
virtual void NamespaceDefMutable::findSectionsInDocumentation () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by findSectionsInDocumentation().
findSectionsInDocumentation() [2/2]
virtual void NamespaceDefMutable::findSectionsInDocumentation () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
insertClass() [1/2]
virtual void NamespaceDefMutable::insertClass (const ClassDef * cd) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
insertClass() [2/2]
virtual void NamespaceDefMutable::insertClass (const ClassDef * cd) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
insertConcept() [1/2]
virtual void NamespaceDefMutable::insertConcept (const ConceptDef * cd) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
insertConcept() [2/2]
virtual void NamespaceDefMutable::insertConcept (const ConceptDef * cd) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
insertMember() [1/2]
virtual void NamespaceDefMutable::insertMember (MemberDef * md) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by addVariableToFile(), findEnums(), and NamespaceDefImpl::insertMember().
insertMember() [2/2]
virtual void NamespaceDefMutable::insertMember (MemberDef * md) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
insertNamespace() [1/2]
virtual void NamespaceDefMutable::insertNamespace (const NamespaceDef * nd) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
insertNamespace() [2/2]
virtual void NamespaceDefMutable::insertNamespace (const NamespaceDef * nd) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
insertUsedFile() [1/2]
virtual void NamespaceDefMutable::insertUsedFile (FileDef * fd) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by buildNamespaceList(), and findUsingDirectives().
insertUsedFile() [2/2]
virtual void NamespaceDefMutable::insertUsedFile (FileDef * fd) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
setFileName() [1/2]
virtual void NamespaceDefMutable::setFileName (const QCString & fn) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by buildNamespaceList().
setFileName() [2/2]
virtual void NamespaceDefMutable::setFileName (const QCString & fn) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
setInline() [1/2]
virtual void NamespaceDefMutable::setInline (bool isInline) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by buildNamespaceList(), and findUsingDirectives().
setInline() [2/2]
virtual void NamespaceDefMutable::setInline (bool isInline) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
setMetaData() [1/2]
virtual void NamespaceDefMutable::setMetaData (const QCString & m) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by buildNamespaceList(), and findUsingDirectives().
setMetaData() [2/2]
virtual void NamespaceDefMutable::setMetaData (const QCString & m) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
sortMemberLists() [1/2]
virtual void NamespaceDefMutable::sortMemberLists () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by sortMemberLists().
sortMemberLists() [2/2]
virtual void NamespaceDefMutable::sortMemberLists () [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
writeDocumentation() [1/2]
virtual void NamespaceDefMutable::writeDocumentation (OutputList & ol) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by generateNamespaceDocs().
writeDocumentation() [2/2]
virtual void NamespaceDefMutable::writeDocumentation (OutputList & ol) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
writeMemberPages() [1/2]
virtual void NamespaceDefMutable::writeMemberPages (OutputList & ol) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
writeMemberPages() [2/2]
virtual void NamespaceDefMutable::writeMemberPages (OutputList & ol) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
writeQuickMemberLinks() [1/2]
virtual void NamespaceDefMutable::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const [pure virtual]
Implements DefinitionMutable.
Implemented in NamespaceDefImpl, NamespaceDefImpl, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< NamespaceDefMutable >.
writeQuickMemberLinks() [2/2]
virtual void NamespaceDefMutable::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const [pure virtual]
Implements DefinitionMutable.
Implemented in NamespaceDefImpl, NamespaceDefImpl, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< NamespaceDefMutable >.
writeTagFile() [1/2]
virtual void NamespaceDefMutable::writeTagFile (TextStream &) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
Referenced by writeTagFile().
writeTagFile() [2/2]
virtual void NamespaceDefMutable::writeTagFile (TextStream &) [pure virtual]
Implemented in NamespaceDefImpl, and NamespaceDefImpl.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/namespacedef.h
doxygen/src/namespacedef.h