ConfigContext::Private Class Reference
Public Member Functions
StringVector fields () const
TemplateVariant get (const QCString &name) const
StringVector fields () const
TemplateVariant get (const QCString &name) const
Private Types
using ConfigData = std::map< std::string, TemplateVariant >
using ConfigData = std::map< std::string, TemplateVariant >
Private Member Functions
ConfigData createConfigData () const
StringVector createFields () const
ConfigData createConfigData () const
StringVector createFields () const
Private Attributes
CachedItem< StringVector, Private, &Private::createFields > m_fields
CachedItem< ConfigData, Private, &Private::createConfigData > m_configData
Detailed Description
Definition at line 235 of file context.cpp.
Member Typedef Documentation
ConfigData [1/2]
using ConfigContext::Private::ConfigData = std::map<std::string,TemplateVariant> [private]
Definition at line 250 of file context.cpp.
ConfigData [2/2]
using ConfigContext::Private::ConfigData = std::map<std::string,TemplateVariant> [private]
Definition at line 250 of file context.cpp.
Member Function Documentation
createConfigData() [1/2]
ConfigData ConfigContext::Private::createConfigData () const [inline], [private]
Definition at line 252 of file context.cpp.
    {
      std::map<std::string,TemplateVariant> map;
      for (auto name : ConfigValues::instance().fields())
      {
        const ConfigValues::Info *option = ConfigValues::instance().get(QCString(name));
        if (option)
        {
          switch (option->type)
          {
            case ConfigValues::Info::Bool:
              {
                bool b = ConfigValues::instance().*(option->value.b);
                map.insert(std::make_pair(name,TemplateVariant(b)));
              }
              break;
            case ConfigValues::Info::Int:
              {
                int i = ConfigValues::instance().*(option->value.i);
                map.insert(std::make_pair(name,TemplateVariant(i)));
              }
              break;
            case ConfigValues::Info::String:
              {
                QCString s = ConfigValues::instance().*(option->value.s);
                map.insert(std::make_pair(name,TemplateVariant(s)));
              }
              break;
            case ConfigValues::Info::List:
              {
                auto fetchList = [](const StringVector &list) -> TemplateVariant
                {
                  TemplateVariantList elements;
                  elements.reserve(list.size());
                  for (const auto &s : list)
                  {
                    elements.push_back(TemplateVariant(s));
                  }
                  return TemplateImmutableList::alloc(elements);
                };
                const StringVector &l = ConfigValues::instance().*(option->value.l);
                map.insert(std::make_pair(name,fetchList(l)));
              }
              break;
            default:
              break;
          }
        }
      }
      return map;
    }
References TemplateImmutableList::alloc(), b, fields(), setup::name, and s.
createConfigData() [2/2]
ConfigData ConfigContext::Private::createConfigData () const [inline], [private]
Definition at line 252 of file context.cpp.
    {
      std::map<std::string,TemplateVariant> map;
      for (auto name : ConfigValues::instance().fields())
      {
        const ConfigValues::Info *option = ConfigValues::instance().get(QCString(name));
        if (option)
        {
          switch (option->type)
          {
            case ConfigValues::Info::Bool:
              {
                bool b = ConfigValues::instance().*(option->value.b);
                map.insert(std::make_pair(name,TemplateVariant(b)));
              }
              break;
            case ConfigValues::Info::Int:
              {
                int i = ConfigValues::instance().*(option->value.i);
                map.insert(std::make_pair(name,TemplateVariant(i)));
              }
              break;
            case ConfigValues::Info::String:
              {
                QCString s = ConfigValues::instance().*(option->value.s);
                map.insert(std::make_pair(name,TemplateVariant(s)));
              }
              break;
            case ConfigValues::Info::List:
              {
                auto fetchList = [](const StringVector &list) -> TemplateVariant
                {
                  TemplateVariantList elements;
                  elements.reserve(list.size());
                  for (const auto &s : list)
                  {
                    elements.push_back(TemplateVariant(s));
                  }
                  return TemplateImmutableList::alloc(elements);
                };
                const StringVector &l = ConfigValues::instance().*(option->value.l);
                map.insert(std::make_pair(name,fetchList(l)));
              }
              break;
            default:
              break;
          }
        }
      }
      return map;
    }
References TemplateImmutableList::alloc(), b, fields(), setup::name, and s.
createFields() [1/2]
StringVector ConfigContext::Private::createFields () const [inline], [private]
Definition at line 304 of file context.cpp.
    {
      return ConfigValues::instance().fields();
    }
createFields() [2/2]
StringVector ConfigContext::Private::createFields () const [inline], [private]
Definition at line 304 of file context.cpp.
    {
      return ConfigValues::instance().fields();
    }
fields() [1/2]
StringVector ConfigContext::Private::fields () const [inline]
Definition at line 239 of file context.cpp.
    {
      return m_fields.get(this);
    }
References m_fields.
Referenced by createConfigData().
fields() [2/2]
StringVector ConfigContext::Private::fields () const [inline]
Definition at line 239 of file context.cpp.
    {
      return m_fields.get(this);
    }
References m_fields.
get() [1/2]
TemplateVariant ConfigContext::Private::get (const QCString & name) const [inline]
Definition at line 243 of file context.cpp.
    {
      auto &data = m_configData.get(this);
      auto it = data.find(name.str());
      return (it!=data.end()) ? it->second : TemplateVariant();
    }
References data, m_configData, and setup::name.
get() [2/2]
TemplateVariant ConfigContext::Private::get (const QCString & name) const [inline]
Definition at line 243 of file context.cpp.
    {
      auto &data = m_configData.get(this);
      auto it = data.find(name.str());
      return (it!=data.end()) ? it->second : TemplateVariant();
    }
References data, m_configData, and setup::name.
Member Data Documentation
m_configData
CachedItem< ConfigData, Private, &Private::createConfigData > ConfigContext::Private::m_configData [private]
Definition at line 310 of file context.cpp.
Referenced by get().
m_fields
CachedItem< StringVector, Private, &Private::createFields > ConfigContext::Private::m_fields [private]
Definition at line 309 of file context.cpp.
Referenced by fields().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp