Afterdoc_Test Class Reference
#include <afterdoc.h>
Public Types
enum EnumType { EVal1
, EVal2
, EVal1
, EVal2
 }
enum EnumType { EVal1
, EVal2
, EVal1
, EVal2
 }
Public Member Functions
void member ()
a member function.
void member ()
a member function.
Protected Attributes
int value
Detailed Description
A test class
Definition at line 3 of file afterdoc.h.
Member Enumeration Documentation
EnumType [1/2]
enum Afterdoc_Test::EnumType
An enum type. The documentation block cannot be put after the enum!
Enumerator
EVal1 enum value 1
EVal2 enum value 2
EVal1 enum value 1
EVal2 enum value 2
Definition at line 9 of file afterdoc.h.
    {
      int EVal1,
      int EVal2
    };
EnumType [2/2]
enum Afterdoc_Test::EnumType
An enum type. The documentation block cannot be put after the enum!
Enumerator
EVal1 enum value 1
EVal2 enum value 2
EVal1 enum value 1
EVal2 enum value 2
Definition at line 9 of file afterdoc.h.
    {
      int EVal1,
      int EVal2
    };
Member Function Documentation
member() [1/2]
void Afterdoc_Test::member ()
a member function.
Referenced by doxmlparser.compound.listofallmembersType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.listofallmembersType::add_member(), doxmlparser.index.CompoundType::add_member(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.listofallmembersType::get_member(), doxmlparser.index.CompoundType::get_member(), doxmlparser.compound.listofallmembersType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.compound.listofallmembersType::insert_member_at(), doxmlparser.index.CompoundType::insert_member_at(), doxmlparser.compound.listofallmembersType::replace_member_at(), doxmlparser.index.CompoundType::replace_member_at(), doxmlparser.compound.listofallmembersType::set_member(), and doxmlparser.index.CompoundType::set_member().
member() [2/2]
void Afterdoc_Test::member ()
a member function.
Referenced by doxmlparser.compound.listofallmembersType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.listofallmembersType::add_member(), doxmlparser.index.CompoundType::add_member(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.listofallmembersType::get_member(), doxmlparser.index.CompoundType::get_member(), doxmlparser.compound.listofallmembersType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.compound.listofallmembersType::insert_member_at(), doxmlparser.index.CompoundType::insert_member_at(), doxmlparser.compound.listofallmembersType::replace_member_at(), doxmlparser.index.CompoundType::replace_member_at(), doxmlparser.compound.listofallmembersType::set_member(), and doxmlparser.index.CompoundType::set_member().
Member Data Documentation
value
int Afterdoc_Test::value [protected]
an integer value
Definition at line 17 of file afterdoc.h.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), and doxmlparser.index.MixedContainer::to_etree_simple().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/examples/afterdoc.h
doxygen/examples/afterdoc.h