TranslatorRussian Class Reference
#include <translator_ru.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
Additional Inherited Members
Detailed Description
Definition at line 29 of file translator_ru.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorRussian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 42 of file translator_ru.h.
    {
      return "0x419 Russian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorRussian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 42 of file translator_ru.h.
    {
      return "0x419 Russian";
    }
idLanguage() [1/2]
virtual QCString TranslatorRussian::idLanguage () [inline], [virtual]
Used for identification of the language.
Implements Translator.
Definition at line 33 of file translator_ru.h.
    { return "russian"; }
idLanguage() [2/2]
virtual QCString TranslatorRussian::idLanguage () [inline], [virtual]
Used for identification of the language.
Implements Translator.
Definition at line 33 of file translator_ru.h.
    { return "russian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorRussian::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 37 of file translator_ru.h.
    { return "\\usepackage[T2A]{fontenc}\n\\usepackage[russian]{babel}\n"; }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorRussian::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 37 of file translator_ru.h.
    { return "\\usepackage[T2A]{fontenc}\n\\usepackage[russian]{babel}\n"; }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorRussian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1864 of file translator_ru.h.
    { return " "; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorRussian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1864 of file translator_ru.h.
    { return " "; }
trAll() [1/2]
virtual QCString TranslatorRussian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1364 of file translator_ru.h.
    {
      return "";
    }
trAll() [2/2]
virtual QCString TranslatorRussian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1364 of file translator_ru.h.
    {
      return "";
    }
trAndMore() [1/2]
virtual QCString TranslatorRussian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1842 of file translator_ru.h.
    { return " "+number+" ..."; }
trAndMore() [2/2]
virtual QCString TranslatorRussian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1842 of file translator_ru.h.
    { return " "+number+" ..."; }
trAttention() [1/2]
virtual QCString TranslatorRussian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 951 of file translator_ru.h.
    {
      return "";
    }
trAttention() [2/2]
virtual QCString TranslatorRussian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 951 of file translator_ru.h.
    {
      return "";
    }
trAuthor() [1/2]
virtual QCString TranslatorRussian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1235 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorRussian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1235 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorRussian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1115 of file translator_ru.h.
    {
      return "";
    }
trBug() [2/2]
virtual QCString TranslatorRussian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1115 of file translator_ru.h.
    {
      return "";
    }
trBugList() [1/2]
virtual QCString TranslatorRussian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1120 of file translator_ru.h.
    {
      return "";
    }
trBugList() [2/2]
virtual QCString TranslatorRussian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1120 of file translator_ru.h.
    {
      return "";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorRussian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1485 of file translator_ru.h.
    {
      return " :";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorRussian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1485 of file translator_ru.h.
    {
      return " :";
    }
trCallGraph() [1/2]
virtual QCString TranslatorRussian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1369 of file translator_ru.h.
    {
      return " :";
    }
trCallGraph() [2/2]
virtual QCString TranslatorRussian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1369 of file translator_ru.h.
    {
      return " :";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorRussian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1818 of file translator_ru.h.
    { return " "; }
trCiteReferences() [2/2]
virtual QCString TranslatorRussian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1818 of file translator_ru.h.
    { return " "; }
trClass() [1/2]
virtual QCString TranslatorRussian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1148 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        QCString result((first_capital ? " " : " "));
        return result;
      }
      else
      {
        QCString result((first_capital ? "" : ""));
        if(!singular) result+="";
        return result;
      }
    }
References Config_getBool.
trClass() [2/2]
virtual QCString TranslatorRussian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1148 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        QCString result((first_capital ? " " : " "));
        return result;
      }
      else
      {
        QCString result((first_capital ? "" : ""));
        if(!singular) result+="";
        return result;
      }
    }
References Config_getBool.
trClassDiagram() [1/2]
virtual QCString TranslatorRussian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 470 of file translator_ru.h.
    {
      return QCString(" :")+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorRussian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 470 of file translator_ru.h.
    {
      return QCString(" :")+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorRussian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 340 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorRussian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 340 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorRussian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1078 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorRussian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1078 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorRussian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 145 of file translator_ru.h.
    { return " "; }
trClassHierarchy() [2/2]
virtual QCString TranslatorRussian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 145 of file translator_ru.h.
    { return " "; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorRussian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 200 of file translator_ru.h.
    { return " ."; }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorRussian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 200 of file translator_ru.h.
    { return " ."; }
trClassMethods() [1/2]
virtual QCString TranslatorRussian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1902 of file translator_ru.h.
    {
      return " ";
    }
trClassMethods() [2/2]
virtual QCString TranslatorRussian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1902 of file translator_ru.h.
    {
      return " ";
    }
trCode() [1/2]
virtual QCString TranslatorRussian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 848 of file translator_ru.h.
    {
      return " ";
    }
trCode() [2/2]
virtual QCString TranslatorRussian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 848 of file translator_ru.h.
    {
      return " ";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorRussian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 803 of file translator_ru.h.
    {
      return " "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorRussian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 803 of file translator_ru.h.
    {
      return " "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorRussian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 313 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorRussian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 313 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorRussian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1542 of file translator_ru.h.
    { return " "; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorRussian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1542 of file translator_ru.h.
    { return " "; }
trCompoundList() [1/2]
virtual QCString TranslatorRussian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 149 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorRussian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 149 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorRussian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 213 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " .";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return " .";
      }
      else
      {
        return " .";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorRussian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 213 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " .";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return " .";
      }
      else
      {
        return " .";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorRussian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1516 of file translator_ru.h.
    { return " :"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorRussian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1516 of file translator_ru.h.
    { return " :"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorRussian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1508 of file translator_ru.h.
    { return " "; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorRussian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1508 of file translator_ru.h.
    { return " "; }
trCompoundMembers() [1/2]
virtual QCString TranslatorRussian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 166 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorRussian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 166 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorRussian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 230 of file translator_ru.h.
    {
        QCString result=" ";
        if(!extractAll) result+=" ";
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result+=" ";
        else
          result+=" ";
        if(!extractAll)
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result+=" .";
          else
            result+=" .";
        }
        else
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result += "";
          else
            result += "";
          result+=", .";
        }
        return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorRussian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 230 of file translator_ru.h.
    {
        QCString result=" ";
        if(!extractAll) result+=" ";
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result+=" ";
        else
          result+=" ";
        if(!extractAll)
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result+=" .";
          else
            result+=" .";
        }
        else
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result += "";
          else
            result += "";
          result+=", .";
        }
        return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorRussian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1520 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ";
      if (!extractAll)
      {
    result+=" :";
      }
      else
      {
         result+=" :";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorRussian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1520 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ";
      if (!extractAll)
      {
    result+=" :";
      }
      else
      {
         result+=" :";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorRussian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1512 of file translator_ru.h.
    { return " "; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorRussian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1512 of file translator_ru.h.
    { return " "; }
trCompoundReference() [1/2]
virtual QCString TranslatorRussian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 546 of file translator_ru.h.
    {
      QCString result;
      if (isTemplate)
      {
        result=" ";
        switch(compType)
        {
          case ClassDef::Class: result+=""; break;
          case ClassDef::Struct: result+=""; break;
          case ClassDef::Union: result+=""; break;
          case ClassDef::Interface: result+=""; break;
          case ClassDef::Protocol: result+=""; break;
          case ClassDef::Category: result+=""; break;
          case ClassDef::Exception: result+=""; break;
          default: break;
        }
      }
      else
      {
        switch(compType)
        {
          case ClassDef::Class: result+=""; break;
          case ClassDef::Struct: result+=""; break;
          case ClassDef::Union: result+=""; break;
          case ClassDef::Interface: result+=""; break;
          case ClassDef::Protocol: result+=""; break;
          case ClassDef::Category: result+=""; break;
          case ClassDef::Exception: result+=""; break;
          default: break;
        }
      }
      result+=" ";
      return result+clName;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorRussian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 546 of file translator_ru.h.
    {
      QCString result;
      if (isTemplate)
      {
        result=" ";
        switch(compType)
        {
          case ClassDef::Class: result+=""; break;
          case ClassDef::Struct: result+=""; break;
          case ClassDef::Union: result+=""; break;
          case ClassDef::Interface: result+=""; break;
          case ClassDef::Protocol: result+=""; break;
          case ClassDef::Category: result+=""; break;
          case ClassDef::Exception: result+=""; break;
          default: break;
        }
      }
      else
      {
        switch(compType)
        {
          case ClassDef::Class: result+=""; break;
          case ClassDef::Struct: result+=""; break;
          case ClassDef::Union: result+=""; break;
          case ClassDef::Interface: result+=""; break;
          case ClassDef::Protocol: result+=""; break;
          case ClassDef::Category: result+=""; break;
          case ClassDef::Exception: result+=""; break;
          default: break;
        }
      }
      result+=" ";
      return result+clName;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorRussian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1583 of file translator_ru.h.
    {
      QCString result=clName;
      if (isTemplate)
      {
    switch(compType)
    {
      case ClassDef::Class: result+=" "; break;
      case ClassDef::Struct: result+=" "; break;
      case ClassDef::Union: result+=" "; break;
      case ClassDef::Interface: result+=" "; break;
      case ClassDef::Protocol: result+=" "; break;
      case ClassDef::Category: result+=" "; break;
      case ClassDef::Exception: result+=" "; break;
          default: break;
    }
      }
      else
      {
    result+=" ";
    switch(compType)
    {
      case ClassDef::Class: result+=""; break;
      case ClassDef::Struct: result+=""; break;
      case ClassDef::Union: result+=""; break;
      case ClassDef::Interface: result+=""; break;
      case ClassDef::Protocol: result+=""; break;
      case ClassDef::Category: result+=""; break;
      case ClassDef::Exception: result+=""; break;
          default: break;
    }
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorRussian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1583 of file translator_ru.h.
    {
      QCString result=clName;
      if (isTemplate)
      {
    switch(compType)
    {
      case ClassDef::Class: result+=" "; break;
      case ClassDef::Struct: result+=" "; break;
      case ClassDef::Union: result+=" "; break;
      case ClassDef::Interface: result+=" "; break;
      case ClassDef::Protocol: result+=" "; break;
      case ClassDef::Category: result+=" "; break;
      case ClassDef::Exception: result+=" "; break;
          default: break;
    }
      }
      else
      {
    result+=" ";
    switch(compType)
    {
      case ClassDef::Class: result+=""; break;
      case ClassDef::Struct: result+=""; break;
      case ClassDef::Union: result+=""; break;
      case ClassDef::Interface: result+=""; break;
      case ClassDef::Protocol: result+=""; break;
      case ClassDef::Category: result+=""; break;
      case ClassDef::Exception: result+=""; break;
          default: break;
    }
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorRussian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 441 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorRussian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 441 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trConstantGroupReference() [1/2]
virtual QCString TranslatorRussian::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1939 of file translator_ru.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorRussian::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1939 of file translator_ru.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorRussian::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1935 of file translator_ru.h.
    { return " "; }
trConstantGroups() [2/2]
virtual QCString TranslatorRussian::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1935 of file translator_ru.h.
    { return " "; }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorRussian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 813 of file translator_ru.h.
    {
      return "()";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorRussian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 813 of file translator_ru.h.
    {
      return "()";
    }
trCopyright() [1/2]
virtual QCString TranslatorRussian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1822 of file translator_ru.h.
    { return ""; }
trCopyright() [2/2]
virtual QCString TranslatorRussian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1822 of file translator_ru.h.
    { return ""; }
trDataTypes() [1/2]
virtual QCString TranslatorRussian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1566 of file translator_ru.h.
    { return " "; }
trDataTypes() [2/2]
virtual QCString TranslatorRussian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1566 of file translator_ru.h.
    { return " "; }
trDate() [1/2]
virtual QCString TranslatorRussian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 484 of file translator_ru.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorRussian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 484 of file translator_ru.h.
    { return ""; }
trDateTime() [1/2]
virtual QCString TranslatorRussian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1777 of file translator_ru.h.
    {
      static const char *days[] = { "","","","","","","" };
      static const char *months[] = { "","","","","","","","","","","","" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorRussian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1777 of file translator_ru.h.
    {
      static const char *days[] = { "","","","","","","" };
      static const char *months[] = { "","","","","","","","","","","","" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorRussian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1793 of file translator_ru.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorRussian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1793 of file translator_ru.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorRussian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1807 of file translator_ru.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorRussian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1807 of file translator_ru.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorRussian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 780 of file translator_ru.h.
    {
      return ". @1 @0";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorRussian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 780 of file translator_ru.h.
    {
      return ". @1 @0";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorRussian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 133 of file translator_ru.h.
    { return " "; }
trDefinedIn() [2/2]
virtual QCString TranslatorRussian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 133 of file translator_ru.h.
    { return " "; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorRussian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 784 of file translator_ru.h.
    {
      return ". @0";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorRussian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 784 of file translator_ru.h.
    {
      return ". @0";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorRussian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 411 of file translator_ru.h.
    { return ""; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorRussian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 411 of file translator_ru.h.
    { return ""; }
trDefines() [1/2]
virtual QCString TranslatorRussian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 375 of file translator_ru.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorRussian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 375 of file translator_ru.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorRussian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1105 of file translator_ru.h.
    {
      return ":";
    }
trDefineValue() [2/2]
virtual QCString TranslatorRussian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1105 of file translator_ru.h.
    {
      return ":";
    }
trDeprecated() [1/2]
virtual QCString TranslatorRussian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 793 of file translator_ru.h.
    {
      return ".";
    }
trDeprecated() [2/2]
virtual QCString TranslatorRussian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 793 of file translator_ru.h.
    {
      return ".";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorRussian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1292 of file translator_ru.h.
    {
      return " ";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorRussian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1292 of file translator_ru.h.
    {
      return " ";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorRussian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 58 of file translator_ru.h.
    { return " "; }
trDetailedDescription() [2/2]
virtual QCString TranslatorRussian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 58 of file translator_ru.h.
    { return " "; }
trDetailLevel() [1/2]
virtual QCString TranslatorRussian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1834 of file translator_ru.h.
    { return " "; }
trDetailLevel() [2/2]
virtual QCString TranslatorRussian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1834 of file translator_ru.h.
    { return " "; }
trDir() [1/2]
virtual QCString TranslatorRussian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1459 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorRussian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1459 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorRussian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1826 of file translator_ru.h.
    { return QCString(" ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorRussian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1826 of file translator_ru.h.
    { return QCString(" ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorRussian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1441 of file translator_ru.h.
    { return ""; }
trDirDocumentation() [2/2]
virtual QCString TranslatorRussian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1441 of file translator_ru.h.
    { return ""; }
trDirectories() [1/2]
virtual QCString TranslatorRussian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1447 of file translator_ru.h.
    { return " "; }
trDirectories() [2/2]
virtual QCString TranslatorRussian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1447 of file translator_ru.h.
    { return " "; }
trDirIndex() [1/2]
virtual QCString TranslatorRussian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1435 of file translator_ru.h.
    { return " "; }
trDirIndex() [2/2]
virtual QCString TranslatorRussian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1435 of file translator_ru.h.
    { return " "; }
trDirReference() [1/2]
virtual QCString TranslatorRussian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1453 of file translator_ru.h.
    { QCString result=QCString(" ")+ dirName; return result; }
trDirReference() [2/2]
virtual QCString TranslatorRussian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1453 of file translator_ru.h.
    { QCString result=QCString(" ")+ dirName; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorRussian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1716 of file translator_ru.h.
    {
      return QCString(name)+" ";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorRussian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1716 of file translator_ru.h.
    {
      return QCString(name)+" ";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorRussian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 295 of file translator_ru.h.
    { return ""; }
trDocumentation() [2/2]
virtual QCString TranslatorRussian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 295 of file translator_ru.h.
    { return ""; }
trEnumerations() [1/2]
virtual QCString TranslatorRussian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 387 of file translator_ru.h.
    { return ""; }
trEnumerations() [2/2]
virtual QCString TranslatorRussian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 387 of file translator_ru.h.
    { return ""; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorRussian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 423 of file translator_ru.h.
    { return ""; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorRussian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 423 of file translator_ru.h.
    { return ""; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorRussian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1493 of file translator_ru.h.
    { return " "; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorRussian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1493 of file translator_ru.h.
    { return " "; }
trEnumerationValues() [1/2]
virtual QCString TranslatorRussian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 405 of file translator_ru.h.
    { return " "; }
trEnumerationValues() [2/2]
virtual QCString TranslatorRussian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 405 of file translator_ru.h.
    { return " "; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorRussian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1846 of file translator_ru.h.
    { QCString result = " ";
      if (!single) result += "";
      result+=":";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorRussian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1846 of file translator_ru.h.
    { QCString result = " ";
      if (!single) result += "";
      result+=":";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorRussian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 125 of file translator_ru.h.
    { return ""; }
trEnumName() [2/2]
virtual QCString TranslatorRussian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 125 of file translator_ru.h.
    { return ""; }
trEnumReference() [1/2]
virtual QCString TranslatorRussian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1854 of file translator_ru.h.
    { return QCString(name)+" "; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorRussian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1854 of file translator_ru.h.
    { return QCString(name)+" "; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorRussian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 129 of file translator_ru.h.
    { return " "; }
trEnumValue() [2/2]
virtual QCString TranslatorRussian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 129 of file translator_ru.h.
    { return " "; }
trEventDocumentation() [1/2]
virtual QCString TranslatorRussian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1309 of file translator_ru.h.
    {
      return "C";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorRussian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1309 of file translator_ru.h.
    {
      return "C";
    }
trEvents() [1/2]
virtual QCString TranslatorRussian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1304 of file translator_ru.h.
    {
      return "";
    }
trEvents() [2/2]
virtual QCString TranslatorRussian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1304 of file translator_ru.h.
    {
      return "";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorRussian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 365 of file translator_ru.h.
    { return ""; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorRussian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 365 of file translator_ru.h.
    { return ""; }
trExamples() [1/2]
virtual QCString TranslatorRussian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 192 of file translator_ru.h.
    { return ""; }
trExamples() [2/2]
virtual QCString TranslatorRussian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 192 of file translator_ru.h.
    { return ""; }
trExamplesDescription() [1/2]
virtual QCString TranslatorRussian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 280 of file translator_ru.h.
    { return " ."; }
trExamplesDescription() [2/2]
virtual QCString TranslatorRussian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 280 of file translator_ru.h.
    { return " ."; }
trExceptions() [1/2]
virtual QCString TranslatorRussian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 500 of file translator_ru.h.
    { return ""; }
trExceptions() [2/2]
virtual QCString TranslatorRussian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 500 of file translator_ru.h.
    { return ""; }
trExtendsClass() [1/2]
virtual QCString TranslatorRussian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1894 of file translator_ru.h.
    {
      return " @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorRussian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1894 of file translator_ru.h.
    {
      return " @0.";
    }
trFile() [1/2]
virtual QCString TranslatorRussian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1167 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorRussian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1167 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorRussian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 359 of file translator_ru.h.
    { return ""; }
trFileDocumentation() [2/2]
virtual QCString TranslatorRussian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 359 of file translator_ru.h.
    { return ""; }
trFileIn() [1/2]
virtual QCString TranslatorRussian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1753 of file translator_ru.h.
    {
      return " "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorRussian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1753 of file translator_ru.h.
    {
      return " "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorRussian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 328 of file translator_ru.h.
    { return " "; }
trFileIndex() [2/2]
virtual QCString TranslatorRussian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 328 of file translator_ru.h.
    { return " "; }
trFileList() [1/2]
virtual QCString TranslatorRussian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 162 of file translator_ru.h.
    { return ""; }
trFileList() [2/2]
virtual QCString TranslatorRussian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 162 of file translator_ru.h.
    { return ""; }
trFileListDescription() [1/2]
virtual QCString TranslatorRussian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 204 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=".";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorRussian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 204 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=".";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorRussian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 180 of file translator_ru.h.
    {
      return " ";
    }
trFileMembers() [2/2]
virtual QCString TranslatorRussian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 180 of file translator_ru.h.
    {
      return " ";
    }
trFileMembersDescription() [1/2]
virtual QCString TranslatorRussian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 257 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , , "
                " ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (extractAll)
        result+=", .";
      else
        result+=".";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorRussian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 257 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , , "
                " ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (extractAll)
        result+=", .";
      else
        result+=".";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorRussian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 585 of file translator_ru.h.
    {
      return QCString(" ")+fileName;
    }
trFileReference() [2/2]
virtual QCString TranslatorRussian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 585 of file translator_ru.h.
    {
      return QCString(" ")+fileName;
    }
trFriends() [1/2]
virtual QCString TranslatorRussian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 527 of file translator_ru.h.
    { return ""; }
trFriends() [2/2]
virtual QCString TranslatorRussian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 527 of file translator_ru.h.
    { return ""; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorRussian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 429 of file translator_ru.h.
    { return ""; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorRussian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 429 of file translator_ru.h.
    { return ""; }
trFunctions() [1/2]
virtual QCString TranslatorRussian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 393 of file translator_ru.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorRussian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 393 of file translator_ru.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorRussian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the documentation of a group before the list of links to documented files
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 460 of file translator_ru.h.
    {
      QCString result=" ";
      if (!projName.isEmpty()) result+=QCString(" ")+projName;
      result+=QCString(". : ")+date;
      result+=". ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorRussian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the documentation of a group before the list of links to documented files
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 460 of file translator_ru.h.
    {
      QCString result=" ";
      if (!projName.isEmpty()) result+=QCString(" ")+projName;
      result+=QCString(". : ")+date;
      result+=". ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorRussian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 117 of file translator_ru.h.
    { QCString result=" Doxygen";
      if (!s.isEmpty()) result+=QCString(" ")+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorRussian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 117 of file translator_ru.h.
    { QCString result=" Doxygen";
      if (!s.isEmpty()) result+=QCString(" ")+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorRussian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 504 of file translator_ru.h.
    { return " "; }
trGeneratedBy() [2/2]
virtual QCString TranslatorRussian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 504 of file translator_ru.h.
    { return " "; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorRussian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 721 of file translator_ru.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=QCString(" ");
      switch(compType)
      {
        case ClassDef::Class: result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Struct: result+="";
          if (single) result+="";
          break;
        case ClassDef::Union: result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Interface: result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Protocol: result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Category: result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Exception: result+="";
          if (single) result+=""; else result+="";
          break;
        default:
          break;
      }
      result+=" ";
      if (single) result+=":"; else result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorRussian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 721 of file translator_ru.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=QCString(" ");
      switch(compType)
      {
        case ClassDef::Class: result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Struct: result+="";
          if (single) result+="";
          break;
        case ClassDef::Union: result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Interface: result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Protocol: result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Category: result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Exception: result+="";
          if (single) result+=""; else result+="";
          break;
        default:
          break;
      }
      result+=" ";
      if (single) result+=":"; else result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorRussian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1665 of file translator_ru.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorRussian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1665 of file translator_ru.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorRussian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1222 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorRussian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1222 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorRussian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1728 of file translator_ru.h.
    {
      return " ";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorRussian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1728 of file translator_ru.h.
    {
      return " ";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorRussian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 823 of file translator_ru.h.
    {
      return ". .";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorRussian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 823 of file translator_ru.h.
    {
      return ". .";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorRussian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 856 of file translator_ru.h.
    {
      return ". .";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorRussian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 856 of file translator_ru.h.
    {
      return ". .";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorRussian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 818 of file translator_ru.h.
    {
      return ". .";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorRussian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 818 of file translator_ru.h.
    {
      return ". .";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorRussian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 860 of file translator_ru.h.
    {
      return ". .";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorRussian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 860 of file translator_ru.h.
    {
      return ". .";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorRussian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 852 of file translator_ru.h.
    {
      return " . .";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorRussian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 852 of file translator_ru.h.
    {
      return " . .";
    }
trGroup() [1/2]
virtual QCString TranslatorRussian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1189 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorRussian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1189 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorRussian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 307 of file translator_ru.h.
    { return " "; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorRussian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 307 of file translator_ru.h.
    { return " "; }
trImplementedFromList() [1/2]
virtual QCString TranslatorRussian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1260 of file translator_ru.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorRussian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1260 of file translator_ru.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorRussian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1268 of file translator_ru.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorRussian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1268 of file translator_ru.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorRussian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 955 of file translator_ru.h.
    {
      return " , :";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorRussian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 955 of file translator_ru.h.
    {
      return " , :";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorRussian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 808 of file translator_ru.h.
    {
      return " "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorRussian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 808 of file translator_ru.h.
    {
      return " "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorRussian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1762 of file translator_ru.h.
    {
      return " "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorRussian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1762 of file translator_ru.h.
    {
      return " "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorRussian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 111 of file translator_ru.h.
    { return ", "; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorRussian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 111 of file translator_ru.h.
    { return ", "; }
trInheritedByList() [1/2]
virtual QCString TranslatorRussian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 653 of file translator_ru.h.
    {
      return " :"+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorRussian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 653 of file translator_ru.h.
    {
      return " :"+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorRussian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1858 of file translator_ru.h.
    { return QCString(members)+" "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorRussian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1858 of file translator_ru.h.
    { return QCString(members)+" "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorRussian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 645 of file translator_ru.h.
    {
      return " :"+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorRussian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 645 of file translator_ru.h.
    {
      return " :"+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorRussian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 843 of file translator_ru.h.
    {
      return "";
    }
trInitialValue() [2/2]
virtual QCString TranslatorRussian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 843 of file translator_ru.h.
    {
      return "";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorRussian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1910 of file translator_ru.h.
    {
      return " ";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorRussian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1910 of file translator_ru.h.
    {
      return " ";
    }
trInterfaces() [1/2]
virtual QCString TranslatorRussian::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1927 of file translator_ru.h.
    { return " "; }
trInterfaces() [2/2]
virtual QCString TranslatorRussian::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1927 of file translator_ru.h.
    { return " "; }
trInvariant() [1/2]
virtual QCString TranslatorRussian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 838 of file translator_ru.h.
    {
      return "";
    }
trInvariant() [2/2]
virtual QCString TranslatorRussian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 838 of file translator_ru.h.
    {
      return "";
    }
trISOLang() [1/2]
virtual QCString TranslatorRussian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 40 of file translator_ru.h.
    { return "ru"; }
trISOLang() [2/2]
virtual QCString TranslatorRussian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 40 of file translator_ru.h.
    { return "ru"; }
trLegend() [1/2]
virtual QCString TranslatorRussian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1038 of file translator_ru.h.
    {
      return ". ";
    }
trLegend() [2/2]
virtual QCString TranslatorRussian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1038 of file translator_ru.h.
    {
      return ". ";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorRussian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 975 of file translator_ru.h.
    {
      return
        ", .<p>\n"
        " :\n"
        "\\code\n"
        "/*! - */\n"
        "class Invisible { };\n\n"
        "/*! , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* */\n"
        "class Undocumented { };\n\n"
        "/*! */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ {};\n\n"
        "/*! */\n"
        "class ProtectedBase { };\n\n"
        "/*! */\n"
        "class PrivateBase { };\n\n"
        "/*! , Inherited */\n"
        "class Used { };\n\n"
        "/*! , */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " \\c MAX_DOT_GRAPH_HEIGHT "
        " 240, :"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        " :\n"
        "<ul>\n"
        "<li> , "
        " .\n"
        "<li> .\n"
        "<li> .\n"
        "<li> , \n"
        " / . , "
        " .\n"
        "</ul>\n"
        " :\n"
        "<ul>\n"
        "<li>- "
        " .\n"
        "<li>- .\n"
        "<li>- .\n"
        "<li> , "
        " ."
        " , "
        " . \n"
        "<li> "
        ", . "
        " .\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorRussian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 975 of file translator_ru.h.
    {
      return
        ", .<p>\n"
        " :\n"
        "\\code\n"
        "/*! - */\n"
        "class Invisible { };\n\n"
        "/*! , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* */\n"
        "class Undocumented { };\n\n"
        "/*! */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ {};\n\n"
        "/*! */\n"
        "class ProtectedBase { };\n\n"
        "/*! */\n"
        "class PrivateBase { };\n\n"
        "/*! , Inherited */\n"
        "class Used { };\n\n"
        "/*! , */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " \\c MAX_DOT_GRAPH_HEIGHT "
        " 240, :"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        " :\n"
        "<ul>\n"
        "<li> , "
        " .\n"
        "<li> .\n"
        "<li> .\n"
        "<li> , \n"
        " / . , "
        " .\n"
        "</ul>\n"
        " :\n"
        "<ul>\n"
        "<li>- "
        " .\n"
        "<li>- .\n"
        "<li>- .\n"
        "<li> , "
        " ."
        " , "
        " . \n"
        "<li> "
        ", . "
        " .\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorRussian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 970 of file translator_ru.h.
    {
      return "";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorRussian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 970 of file translator_ru.h.
    {
      return "";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorRussian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 92 of file translator_ru.h.
    {
      return " ";
    }
trListOfAllMembers() [2/2]
virtual QCString TranslatorRussian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 92 of file translator_ru.h.
    {
      return " ";
    }
trLoading() [1/2]
virtual QCString TranslatorRussian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1722 of file translator_ru.h.
    {
      return "...";
    }
trLoading() [2/2]
virtual QCString TranslatorRussian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1722 of file translator_ru.h.
    {
      return "...";
    }
trMainPage() [1/2]
virtual QCString TranslatorRussian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 767 of file translator_ru.h.
    { return " "; }
trMainPage() [2/2]
virtual QCString TranslatorRussian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 767 of file translator_ru.h.
    { return " "; }
trMember() [1/2]
virtual QCString TranslatorRussian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1211 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorRussian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1211 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorRussian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 74 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorRussian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 74 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorRussian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 66 of file translator_ru.h.
    { return ""; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorRussian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 66 of file translator_ru.h.
    { return ""; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorRussian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 70 of file translator_ru.h.
    { return ""; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorRussian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 70 of file translator_ru.h.
    { return ""; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorRussian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1504 of file translator_ru.h.
    { return "/"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorRussian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1504 of file translator_ru.h.
    { return "/"; }
trMemberList() [1/2]
virtual QCString TranslatorRussian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 99 of file translator_ru.h.
    {
      return "C ";
    }
trMemberList() [2/2]
virtual QCString TranslatorRussian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 99 of file translator_ru.h.
    {
      return "C ";
    }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorRussian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 62 of file translator_ru.h.
    { return " "; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorRussian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 62 of file translator_ru.h.
    { return " "; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorRussian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1917 of file translator_ru.h.
    {
      return " ";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorRussian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1917 of file translator_ru.h.
    {
      return " ";
    }
trModule() [1/2]
virtual QCString TranslatorRussian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1656 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorRussian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1656 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorRussian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 334 of file translator_ru.h.
    { return ""; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorRussian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 334 of file translator_ru.h.
    { return ""; }
trModuleIndex() [1/2]
virtual QCString TranslatorRussian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 301 of file translator_ru.h.
    { return " "; }
trModuleIndex() [2/2]
virtual QCString TranslatorRussian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 301 of file translator_ru.h.
    { return " "; }
trModuleReference() [1/2]
virtual QCString TranslatorRussian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1620 of file translator_ru.h.
    {
      return QCString(" ") + namespaceName;
    }
trModuleReference() [2/2]
virtual QCString TranslatorRussian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1620 of file translator_ru.h.
    {
      return QCString(" ") + namespaceName;
    }
trModules() [1/2]
virtual QCString TranslatorRussian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 141 of file translator_ru.h.
    { return ""; }
trModules() [2/2]
virtual QCString TranslatorRussian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 141 of file translator_ru.h.
    { return ""; }
trModulesDescription() [1/2]
virtual QCString TranslatorRussian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 288 of file translator_ru.h.
    { return " ."; }
trModulesDescription() [2/2]
virtual QCString TranslatorRussian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 288 of file translator_ru.h.
    { return " ."; }
trModulesIndex() [1/2]
virtual QCString TranslatorRussian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1649 of file translator_ru.h.
    { return " "; }
trModulesIndex() [2/2]
virtual QCString TranslatorRussian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1649 of file translator_ru.h.
    { return " "; }
trModulesList() [1/2]
virtual QCString TranslatorRussian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1570 of file translator_ru.h.
    { return " "; }
trModulesList() [2/2]
virtual QCString TranslatorRussian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1570 of file translator_ru.h.
    { return " "; }
trModulesListDescription() [1/2]
virtual QCString TranslatorRussian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1574 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=":";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorRussian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1574 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=":";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorRussian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1630 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
      {
        result+=" :";
      }
      else
      {
        result+=" , :";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorRussian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1630 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
      {
        result+=" :";
      }
      else
      {
        result+=" , :";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorRussian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1626 of file translator_ru.h.
    { return " "; }
trModulesMembers() [2/2]
virtual QCString TranslatorRussian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1626 of file translator_ru.h.
    { return " "; }
trMonth() [1/2]
virtual QCString TranslatorRussian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1800 of file translator_ru.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorRussian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1800 of file translator_ru.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
virtual QCString TranslatorRussian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 87 of file translator_ru.h.
    { return "..."; }
trMore() [2/2]
virtual QCString TranslatorRussian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 87 of file translator_ru.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorRussian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1178 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular?" ":" ");
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorRussian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1178 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular?" ":" ");
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorRussian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 701 of file translator_ru.h.
    { return " "; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorRussian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 701 of file translator_ru.h.
    { return " "; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorRussian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 695 of file translator_ru.h.
    { return " "; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorRussian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 695 of file translator_ru.h.
    { return " "; }
trNamespaceList() [1/2]
virtual QCString TranslatorRussian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 512 of file translator_ru.h.
    { return " "; }
trNamespaceList() [2/2]
virtual QCString TranslatorRussian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 512 of file translator_ru.h.
    { return " "; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorRussian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 516 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" .";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorRussian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 516 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" .";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorRussian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 684 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" .";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorRussian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 684 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" .";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorRussian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 680 of file translator_ru.h.
    { return " "; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorRussian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 680 of file translator_ru.h.
    { return " "; }
trNamespaceReference() [1/2]
virtual QCString TranslatorRussian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 591 of file translator_ru.h.
    {
      return QCString(" ")+namespaceName;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorRussian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 591 of file translator_ru.h.
    {
      return QCString(" ")+namespaceName;
    }
trNamespaces() [1/2]
virtual QCString TranslatorRussian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 711 of file translator_ru.h.
    { return " "; }
trNamespaces() [2/2]
virtual QCString TranslatorRussian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 711 of file translator_ru.h.
    { return " "; }
trNoMatches() [1/2]
virtual QCString TranslatorRussian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1740 of file translator_ru.h.
    {
      return " ";
    }
trNoMatches() [2/2]
virtual QCString TranslatorRussian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1740 of file translator_ru.h.
    {
      return " ";
    }
trNote() [1/2]
virtual QCString TranslatorRussian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 873 of file translator_ru.h.
    {
      return "";
    }
trNote() [2/2]
virtual QCString TranslatorRussian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 873 of file translator_ru.h.
    {
      return "";
    }
trOverloadText() [1/2]
virtual QCString TranslatorRussian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1473 of file translator_ru.h.
    {
       return " "
              " . "
              " .";
    }
trOverloadText() [2/2]
virtual QCString TranslatorRussian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1473 of file translator_ru.h.
    {
       return " "
              " . "
              " .";
    }
trPackage() [1/2]
virtual QCString TranslatorRussian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1090 of file translator_ru.h.
    {
      return QCString(" ")+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorRussian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1090 of file translator_ru.h.
    {
      return QCString(" ")+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorRussian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1345 of file translator_ru.h.
    {
      return " ";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorRussian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1345 of file translator_ru.h.
    {
      return " ";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorRussian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1327 of file translator_ru.h.
    {
      return " ";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorRussian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1327 of file translator_ru.h.
    {
      return " ";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorRussian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1095 of file translator_ru.h.
    {
      return " .";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorRussian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1095 of file translator_ru.h.
    {
      return " .";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorRussian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1331 of file translator_ru.h.
    {
      return " ";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorRussian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1331 of file translator_ru.h.
    {
      return " ";
    }
trPackages() [1/2]
virtual QCString TranslatorRussian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1100 of file translator_ru.h.
    {
      return "";
    }
trPackages() [2/2]
virtual QCString TranslatorRussian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1100 of file translator_ru.h.
    {
      return "";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorRussian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1320 of file translator_ru.h.
    {
      return " ";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorRussian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1320 of file translator_ru.h.
    {
      return " ";
    }
trPage() [1/2]
virtual QCString TranslatorRussian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1200 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorRussian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1200 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorRussian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 773 of file translator_ru.h.
    { return "."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorRussian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 773 of file translator_ru.h.
    { return "."; }
trPageIndex() [1/2]
virtual QCString TranslatorRussian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 864 of file translator_ru.h.
    {
      return " ";
    }
trPageIndex() [2/2]
virtual QCString TranslatorRussian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 864 of file translator_ru.h.
    {
      return " ";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorRussian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1875 of file translator_ru.h.
    {
      QCString opt = enable ? "" : "";
      return " "+opt+" ";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorRussian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1875 of file translator_ru.h.
    {
      QCString opt = enable ? "" : "";
      return " "+opt+" ";
    }
trParameters() [1/2]
virtual QCString TranslatorRussian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 496 of file translator_ru.h.
    { return ""; }
trParameters() [2/2]
virtual QCString TranslatorRussian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 496 of file translator_ru.h.
    { return ""; }
trPostcondition() [1/2]
virtual QCString TranslatorRussian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 833 of file translator_ru.h.
    {
      return "";
    }
trPostcondition() [2/2]
virtual QCString TranslatorRussian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 833 of file translator_ru.h.
    {
      return "";
    }
trPrecondition() [1/2]
virtual QCString TranslatorRussian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 828 of file translator_ru.h.
    {
      return "";
    }
trPrecondition() [2/2]
virtual QCString TranslatorRussian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 828 of file translator_ru.h.
    {
      return "";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorRussian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_ru.h.
    {
      return " ";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorRussian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_ru.h.
    {
      return " ";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorRussian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 610 of file translator_ru.h.
    { return " "; }
trPrivateMembers() [2/2]
virtual QCString TranslatorRussian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 610 of file translator_ru.h.
    { return " "; }
trPrivateSlots() [1/2]
virtual QCString TranslatorRussian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 612 of file translator_ru.h.
    { return " "; }
trPrivateSlots() [2/2]
virtual QCString TranslatorRussian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 612 of file translator_ru.h.
    { return " "; }
trPrivateTypes() [1/2]
virtual QCString TranslatorRussian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_ru.h.
    {
      return " ";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorRussian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_ru.h.
    {
      return " ";
    }
trProperties() [1/2]
virtual QCString TranslatorRussian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1063 of file translator_ru.h.
    {
      return "";
    }
trProperties() [2/2]
virtual QCString TranslatorRussian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1063 of file translator_ru.h.
    {
      return "";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorRussian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1068 of file translator_ru.h.
    {
      return " ";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorRussian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1068 of file translator_ru.h.
    {
      return " ";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorRussian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 900 of file translator_ru.h.
    {
      return " ";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorRussian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 900 of file translator_ru.h.
    {
      return " ";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorRussian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 604 of file translator_ru.h.
    { return " "; }
trProtectedMembers() [2/2]
virtual QCString TranslatorRussian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 604 of file translator_ru.h.
    { return " "; }
trProtectedSlots() [1/2]
virtual QCString TranslatorRussian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 606 of file translator_ru.h.
    { return " "; }
trProtectedSlots() [2/2]
virtual QCString TranslatorRussian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 606 of file translator_ru.h.
    { return " "; }
trProtectedTypes() [1/2]
virtual QCString TranslatorRussian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 896 of file translator_ru.h.
    {
      return " ";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorRussian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 896 of file translator_ru.h.
    {
      return " ";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorRussian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1885 of file translator_ru.h.
    {
      return " @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorRussian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1885 of file translator_ru.h.
    {
      return " @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorRussian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorRussian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorRussian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 596 of file translator_ru.h.
    { return " "; }
trPublicMembers() [2/2]
virtual QCString TranslatorRussian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 596 of file translator_ru.h.
    { return " "; }
trPublicSlots() [1/2]
virtual QCString TranslatorRussian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 598 of file translator_ru.h.
    { return " "; }
trPublicSlots() [2/2]
virtual QCString TranslatorRussian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 598 of file translator_ru.h.
    { return " "; }
trPublicTypes() [1/2]
virtual QCString TranslatorRussian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_ru.h.
    {
      return " ";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorRussian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_ru.h.
    {
      return " ";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorRussian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_ru.h.
    {
      return " ";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorRussian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_ru.h.
    {
      return " ";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorRussian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 369 of file translator_ru.h.
    { return ""; }
trReferenceManual() [2/2]
virtual QCString TranslatorRussian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 369 of file translator_ru.h.
    { return ""; }
trReferences() [1/2]
virtual QCString TranslatorRussian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1248 of file translator_ru.h.
    {
      return " ";
    }
trReferences() [2/2]
virtual QCString TranslatorRussian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1248 of file translator_ru.h.
    {
      return " ";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorRussian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 661 of file translator_ru.h.
    {
      QCString result=" ";
      if(numEntries>1)
    result+=" ";
      else
    result+=" ";
      return result+" "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorRussian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 661 of file translator_ru.h.
    {
      QCString result=" ";
      if(numEntries>1)
    result+=" ";
      else
    result+=" ";
      return result+" "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorRussian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 674 of file translator_ru.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorRussian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 674 of file translator_ru.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorRussian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 537 of file translator_ru.h.
    { return " , "
        " "; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorRussian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 537 of file translator_ru.h.
    { return " , "
        " "; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorRussian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 50 of file translator_ru.h.
    { return " "; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorRussian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 50 of file translator_ru.h.
    { return " "; }
trRelatedPages() [1/2]
virtual QCString TranslatorRussian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 186 of file translator_ru.h.
    { return ""; }
trRelatedPages() [2/2]
virtual QCString TranslatorRussian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 186 of file translator_ru.h.
    { return ""; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorRussian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 284 of file translator_ru.h.
    { return " ."; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorRussian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 284 of file translator_ru.h.
    { return " ."; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorRussian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 54 of file translator_ru.h.
    { return "()"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorRussian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 54 of file translator_ru.h.
    { return "()"; }
trRemarks() [1/2]
virtual QCString TranslatorRussian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_ru.h.
    {
      return ".";
    }
trRemarks() [2/2]
virtual QCString TranslatorRussian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_ru.h.
    {
      return ".";
    }
trReturns() [1/2]
virtual QCString TranslatorRussian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 488 of file translator_ru.h.
    { return ""; }
trReturns() [2/2]
virtual QCString TranslatorRussian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 488 of file translator_ru.h.
    { return ""; }
trReturnValues() [1/2]
virtual QCString TranslatorRussian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 762 of file translator_ru.h.
    { return " "; }
trReturnValues() [2/2]
virtual QCString TranslatorRussian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 762 of file translator_ru.h.
    { return " "; }
trRTFansicp() [1/2]
virtual QCString TranslatorRussian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1129 of file translator_ru.h.
    {
      return "1251";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorRussian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1129 of file translator_ru.h.
    {
      return "1251";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorRussian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1134 of file translator_ru.h.
    {
      return "204";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorRussian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1134 of file translator_ru.h.
    {
      return "204";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorRussian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1139 of file translator_ru.h.
    {
      return " ";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorRussian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1139 of file translator_ru.h.
    {
      return " ";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorRussian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1280 of file translator_ru.h.
    {
      return "";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorRussian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1280 of file translator_ru.h.
    {
      return "";
    }
trSearch() [1/2]
virtual QCString TranslatorRussian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 196 of file translator_ru.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorRussian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 196 of file translator_ru.h.
    { return ""; }
trSearching() [1/2]
virtual QCString TranslatorRussian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1734 of file translator_ru.h.
    {
      return "...";
    }
trSearching() [2/2]
virtual QCString TranslatorRussian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1734 of file translator_ru.h.
    {
      return "...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorRussian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1412 of file translator_ru.h.
    {
      return ":";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorRussian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1412 of file translator_ru.h.
    {
      return ":";
    }
trSearchResults() [1/2]
virtual QCString TranslatorRussian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1393 of file translator_ru.h.
    {
      if (numDocuments==0)
      {
        return " , .";
      }
      else if(numDocuments == 1)
      {
        return " 1 .";
      }
      else
      {
        return "() <b>$num</b> (). "
          " .";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorRussian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1393 of file translator_ru.h.
    {
      if (numDocuments==0)
      {
        return " , .";
      }
      else if(numDocuments == 1)
      {
        return " 1 .";
      }
      else
      {
        return "() <b>$num</b> (). "
          " .";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorRussian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1381 of file translator_ru.h.
    {
      return " ";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorRussian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1381 of file translator_ru.h.
    {
      return " ";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorRussian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 492 of file translator_ru.h.
    { return ". "; }
trSeeAlso() [2/2]
virtual QCString TranslatorRussian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 492 of file translator_ru.h.
    { return ". "; }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorRussian::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1960 of file translator_ru.h.
    {
      // single is true implies a single file
      QCString result=" "
                                " ";
      if (single) result+=":"; else result+=":";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorRussian::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1960 of file translator_ru.h.
    {
      // single is true implies a single file
      QCString result=" "
                                " ";
      if (single) result+=":"; else result+=":";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorRussian::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1946 of file translator_ru.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorRussian::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1946 of file translator_ru.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorRussian::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1931 of file translator_ru.h.
    { return " "; }
trServices() [2/2]
virtual QCString TranslatorRussian::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1931 of file translator_ru.h.
    { return " "; }
trSignals() [1/2]
virtual QCString TranslatorRussian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 600 of file translator_ru.h.
    { return ""; }
trSignals() [2/2]
virtual QCString TranslatorRussian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 600 of file translator_ru.h.
    { return ""; }
trSince() [1/2]
virtual QCString TranslatorRussian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 959 of file translator_ru.h.
    {
      return " ";
    }
trSince() [2/2]
virtual QCString TranslatorRussian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 959 of file translator_ru.h.
    {
      return " ";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorRussian::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1969 of file translator_ru.h.
    {
      // single is true implies a single file
      QCString result=" "
                                " ";
      if (single) result+=":"; else result+=":";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorRussian::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1969 of file translator_ru.h.
    {
      // single is true implies a single file
      QCString result=" "
                                " ";
      if (single) result+=":"; else result+=":";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorRussian::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1953 of file translator_ru.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorRussian::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1953 of file translator_ru.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trSourceFile() [1/2]
virtual QCString TranslatorRussian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1423 of file translator_ru.h.
    {
      return " " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorRussian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1423 of file translator_ru.h.
    {
      return " " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorRussian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1352 of file translator_ru.h.
    {
      return " ";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorRussian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1352 of file translator_ru.h.
    {
      return " ";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorRussian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1338 of file translator_ru.h.
    {
      return " ";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorRussian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1338 of file translator_ru.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorRussian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_ru.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorRussian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_ru.h.
    {
      return " ";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorRussian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 614 of file translator_ru.h.
    { return " "; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorRussian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 614 of file translator_ru.h.
    { return " "; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorRussian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_ru.h.
    {
      return " ";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorRussian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_ru.h.
    {
      return " ";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorRussian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 608 of file translator_ru.h.
    { return " "; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorRussian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 608 of file translator_ru.h.
    { return " "; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorRussian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 892 of file translator_ru.h.
    {
      return " ";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorRussian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 892 of file translator_ru.h.
    {
      return " ";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorRussian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 602 of file translator_ru.h.
    { return " "; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorRussian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 602 of file translator_ru.h.
    { return " "; }
trSubprogram() [1/2]
virtual QCString TranslatorRussian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1699 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorRussian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1699 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorRussian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1560 of file translator_ru.h.
    { return "/"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorRussian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1560 of file translator_ru.h.
    { return "/"; }
trSubprograms() [1/2]
virtual QCString TranslatorRussian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1554 of file translator_ru.h.
    { return "/"; }
trSubprograms() [2/2]
virtual QCString TranslatorRussian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1554 of file translator_ru.h.
    { return "/"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorRussian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1838 of file translator_ru.h.
    { return " "; }
trTemplateParameters() [2/2]
virtual QCString TranslatorRussian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1838 of file translator_ru.h.
    { return " "; }
trTest() [1/2]
virtual QCString TranslatorRussian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1048 of file translator_ru.h.
    {
      return "";
    }
trTest() [2/2]
virtual QCString TranslatorRussian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1048 of file translator_ru.h.
    {
      return "";
    }
trTestList() [1/2]
virtual QCString TranslatorRussian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1053 of file translator_ru.h.
    {
      return " ";
    }
trTestList() [2/2]
virtual QCString TranslatorRussian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1053 of file translator_ru.h.
    {
      return " ";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorRussian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 106 of file translator_ru.h.
    { return " "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorRussian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 106 of file translator_ru.h.
    { return " "; }
trTodo() [1/2]
virtual QCString TranslatorRussian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 927 of file translator_ru.h.
    {
      return " ";
    }
trTodo() [2/2]
virtual QCString TranslatorRussian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 927 of file translator_ru.h.
    {
      return " ";
    }
trTodoList() [1/2]
virtual QCString TranslatorRussian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 933 of file translator_ru.h.
    {
      return " ";
    }
trTodoList() [2/2]
virtual QCString TranslatorRussian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 933 of file translator_ru.h.
    {
      return " ";
    }
trType() [1/2]
virtual QCString TranslatorRussian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1689 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorRussian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1689 of file translator_ru.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorRussian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1707 of file translator_ru.h.
    {
      return " ";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorRussian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1707 of file translator_ru.h.
    {
      return " ";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorRussian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 417 of file translator_ru.h.
    { return ""; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorRussian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 417 of file translator_ru.h.
    { return ""; }
trTypedefs() [1/2]
virtual QCString TranslatorRussian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 381 of file translator_ru.h.
    { return " "; }
trTypedefs() [2/2]
virtual QCString TranslatorRussian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 381 of file translator_ru.h.
    { return " "; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorRussian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1548 of file translator_ru.h.
    { return " "; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorRussian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1548 of file translator_ru.h.
    { return " "; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorRussian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 435 of file translator_ru.h.
    { return ""; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorRussian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 435 of file translator_ru.h.
    { return ""; }
trVariables() [1/2]
virtual QCString TranslatorRussian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 399 of file translator_ru.h.
    { return ""; }
trVariables() [2/2]
virtual QCString TranslatorRussian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 399 of file translator_ru.h.
    { return ""; }
trVersion() [1/2]
virtual QCString TranslatorRussian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 480 of file translator_ru.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorRussian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 480 of file translator_ru.h.
    { return ""; }
trWarning() [1/2]
virtual QCString TranslatorRussian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 476 of file translator_ru.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorRussian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 476 of file translator_ru.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorRussian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 620 of file translator_ru.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorRussian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 620 of file translator_ru.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_ru.h
doxygen/src/translator_ru.h