TranslatorIndonesian Class Reference
#include <translator_id.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
Additional Inherited Members
Detailed Description
Definition at line 27 of file translator_id.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorIndonesian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 65 of file translator_id.h.
    {
      return "0x421 Indonesian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorIndonesian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 65 of file translator_id.h.
    {
      return "0x421 Indonesian";
    }
idLanguage() [1/2]
virtual QCString TranslatorIndonesian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 39 of file translator_id.h.
    { return "indonesian"; }
idLanguage() [2/2]
virtual QCString TranslatorIndonesian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 39 of file translator_id.h.
    { return "indonesian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorIndonesian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 56 of file translator_id.h.
    {
      return "\\usepackage[bahasa]{babel}";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorIndonesian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 56 of file translator_id.h.
    {
      return "\\usepackage[bahasa]{babel}";
    }
trAll() [1/2]
virtual QCString TranslatorIndonesian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1383 of file translator_id.h.
    {
      return "Semua";
    }
trAll() [2/2]
virtual QCString TranslatorIndonesian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1383 of file translator_id.h.
    {
      return "Semua";
    }
trAttention() [1/2]
virtual QCString TranslatorIndonesian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 948 of file translator_id.h.
    {
      return "Perhatian";
    }
trAttention() [2/2]
virtual QCString TranslatorIndonesian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 948 of file translator_id.h.
    {
      return "Perhatian";
    }
trAuthor() [1/2]
virtual QCString TranslatorIndonesian::trAuthor (bool first_capital, bool) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1254 of file translator_id.h.
    {
      QCString result((first_capital ? "Penulis" : "penulis"));
      //if (!singular) result+="s";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorIndonesian::trAuthor (bool first_capital, bool) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1254 of file translator_id.h.
    {
      QCString result((first_capital ? "Penulis" : "penulis"));
      //if (!singular) result+="s";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorIndonesian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1112 of file translator_id.h.
    {
      return "Bug";
    }
trBug() [2/2]
virtual QCString TranslatorIndonesian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1112 of file translator_id.h.
    {
      return "Bug";
    }
trBugList() [1/2]
virtual QCString TranslatorIndonesian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1117 of file translator_id.h.
    {
      return "Daftar Bug";
    }
trBugList() [2/2]
virtual QCString TranslatorIndonesian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1117 of file translator_id.h.
    {
      return "Daftar Bug";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorIndonesian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1504 of file translator_id.h.
    {
      return "Berikut ini bagan fungsi-pemanggil untuk fungsi ini:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorIndonesian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1504 of file translator_id.h.
    {
      return "Berikut ini bagan fungsi-pemanggil untuk fungsi ini:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorIndonesian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1388 of file translator_id.h.
    {
      return "Berikut ini bagan fungsi-terpanggil untuk fungsi ini:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorIndonesian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1388 of file translator_id.h.
    {
      return "Berikut ini bagan fungsi-terpanggil untuk fungsi ini:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorIndonesian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1820 of file translator_id.h.
    { return "Daftar Pustaka"; }
trCiteReferences() [2/2]
virtual QCString TranslatorIndonesian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1820 of file translator_id.h.
    { return "Daftar Pustaka"; }
trClass() [1/2]
virtual QCString TranslatorIndonesian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1175 of file translator_id.h.
    {
      QCString result((first_capital ? "Kelas" : "kelas"));
      if (!singular) result+="-kelas";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorIndonesian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1175 of file translator_id.h.
    {
      QCString result((first_capital ? "Kelas" : "kelas"));
      if (!singular) result+="-kelas";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorIndonesian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 500 of file translator_id.h.
    {
      return "Diagram hierarki kelas untuk "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorIndonesian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 500 of file translator_id.h.
    {
      return "Diagram hierarki kelas untuk "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 375 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentasi Struktur Data";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentasi Kelas";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 375 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentasi Struktur Data";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentasi Kelas";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorIndonesian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1075 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktur Data";
      }
      else
      {
        return "Daftar Kelas";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorIndonesian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1075 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktur Data";
      }
      else
      {
        return "Daftar Kelas";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorIndonesian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 160 of file translator_id.h.
    { return "Hierarki Kelas"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorIndonesian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 160 of file translator_id.h.
    { return "Hierarki Kelas"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorIndonesian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 219 of file translator_id.h.
    { return "Hierarki kelas ini diurutkan kurang-lebih"
    " berdasarkan abjad:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorIndonesian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 219 of file translator_id.h.
    { return "Hierarki kelas ini diurutkan kurang-lebih"
    " berdasarkan abjad:";
    }
trCode() [1/2]
virtual QCString TranslatorIndonesian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 848 of file translator_id.h.
    {
      return "kode";
    }
trCode() [2/2]
virtual QCString TranslatorIndonesian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 848 of file translator_id.h.
    {
      return "kode";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorIndonesian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 803 of file translator_id.h.
    {
      return "Diagram kolaborasi untuk "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorIndonesian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 803 of file translator_id.h.
    {
      return "Diagram kolaborasi untuk "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorIndonesian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 348 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Indeks Struktur Data";
      }
      else
      {
        return "Indeks Kelas";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorIndonesian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 348 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Indeks Struktur Data";
      }
      else
      {
        return "Indeks Kelas";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorIndonesian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1558 of file translator_id.h.
    { return "Indeks Tipe Data"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorIndonesian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1558 of file translator_id.h.
    { return "Indeks Tipe Data"; }
trCompoundList() [1/2]
virtual QCString TranslatorIndonesian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 164 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktur Data";
      }
      else
      {
        return "Daftar Kelas";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorIndonesian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 164 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktur Data";
      }
      else
      {
        return "Daftar Kelas";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorIndonesian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 234 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Berikut ini daftar struktur data, dengan penjelasan singkat:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Berikut ini daftar kelas, dengan penjelasan singkat:";
      }
      else
      {
        return "Berikut ini daftar kelas, struct, union, dan interface, dengan penjelasan singkat:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorIndonesian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 234 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Berikut ini daftar struktur data, dengan penjelasan singkat:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Berikut ini daftar kelas, dengan penjelasan singkat:";
      }
      else
      {
        return "Berikut ini daftar kelas, struct, union, dan interface, dengan penjelasan singkat:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorIndonesian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1532 of file translator_id.h.
    { return "Berikut daftar tipe data, dengan penjelasan singkat:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorIndonesian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1532 of file translator_id.h.
    { return "Berikut daftar tipe data, dengan penjelasan singkat:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorIndonesian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1524 of file translator_id.h.
    { return "Daftar Tipe Data"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorIndonesian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1524 of file translator_id.h.
    { return "Daftar Tipe Data"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorIndonesian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 181 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Variabel Data";
      }
      else
      {
        return "Daftar Anggota Kelas";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorIndonesian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 181 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Variabel Data";
      }
      else
      {
        return "Daftar Anggota Kelas";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorIndonesian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 252 of file translator_id.h.
    {
      QCString result="Berikut ini daftar seluruh ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="variabel anggota struct dan union";
      }
      else
      {
        result+="kelas";
      }
      if (!extractAll)
      {
        result+=" yang didokumentasikan";
      }
      result+=", dengan tautan ke ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="dokumentasi struct/union untuk setiap variabel:";
        }
        else
        {
          result+="dokumentasi kelas untuk setiap anggota:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struct/union yang memuatnya:";
        }
        else
        {
          result+="kelas yang memuatnya:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorIndonesian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 252 of file translator_id.h.
    {
      QCString result="Berikut ini daftar seluruh ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="variabel anggota struct dan union";
      }
      else
      {
        result+="kelas";
      }
      if (!extractAll)
      {
        result+=" yang didokumentasikan";
      }
      result+=", dengan tautan ke ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="dokumentasi struct/union untuk setiap variabel:";
        }
        else
        {
          result+="dokumentasi kelas untuk setiap anggota:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struct/union yang memuatnya:";
        }
        else
        {
          result+="kelas yang memuatnya:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorIndonesian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1536 of file translator_id.h.
    {
      QCString result="Berikut daftar semua anggota tipe data ";
      if (!extractAll)
      {
        result+="terdokumentasi ";
      }
      result+=" dengan tautan ke ";
      if (!extractAll)
      {
         result+="dokumentasi struktur data untuk setiap anggota:";
      }
      else
      {
         result+="tipe data yang memuatnya:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorIndonesian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1536 of file translator_id.h.
    {
      QCString result="Berikut daftar semua anggota tipe data ";
      if (!extractAll)
      {
        result+="terdokumentasi ";
      }
      result+=" dengan tautan ke ";
      if (!extractAll)
      {
         result+="dokumentasi struktur data untuk setiap anggota:";
      }
      else
      {
         result+="tipe data yang memuatnya:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorIndonesian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1528 of file translator_id.h.
    { return "Variabel Data"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorIndonesian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1528 of file translator_id.h.
    { return "Variabel Data"; }
trCompoundReference() [1/2]
virtual QCString TranslatorIndonesian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 575 of file translator_id.h.
    {
      QCString result="Referensi";
      switch(compType)
      {
        case ClassDef::Class: result+=" Kelas "; break;
        case ClassDef::Struct: result+=" Struct "; break;
        case ClassDef::Union: result+=" Union "; break;
        case ClassDef::Interface: result+=" Interface "; break;
        case ClassDef::Protocol: result+=" Protokol "; break;
        case ClassDef::Category: result+=" Kategori "; break;
        case ClassDef::Exception: result+=" Eksepsi "; break;
        default: break;
      }
      if (isTemplate) result+=" Template ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorIndonesian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 575 of file translator_id.h.
    {
      QCString result="Referensi";
      switch(compType)
      {
        case ClassDef::Class: result+=" Kelas "; break;
        case ClassDef::Struct: result+=" Struct "; break;
        case ClassDef::Union: result+=" Union "; break;
        case ClassDef::Interface: result+=" Interface "; break;
        case ClassDef::Protocol: result+=" Protokol "; break;
        case ClassDef::Category: result+=" Kategori "; break;
        case ClassDef::Exception: result+=" Eksepsi "; break;
        default: break;
      }
      if (isTemplate) result+=" Template ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorIndonesian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1599 of file translator_id.h.
    {
      QCString result="Referensi ";
      if (isTemplate) result+="Template ";
      switch(compType)
      {
        case ClassDef::Class: result+="Modul "; break;
        case ClassDef::Struct: result+="Tipe "; break;
        case ClassDef::Union: result+="Union "; break;
        case ClassDef::Interface: result+="Antarmuka "; break;
        case ClassDef::Protocol: result+="Protokol "; break;
        case ClassDef::Category: result+="Kategori "; break;
        case ClassDef::Exception: result+="Eksepsi "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorIndonesian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1599 of file translator_id.h.
    {
      QCString result="Referensi ";
      if (isTemplate) result+="Template ";
      switch(compType)
      {
        case ClassDef::Class: result+="Modul "; break;
        case ClassDef::Struct: result+="Tipe "; break;
        case ClassDef::Union: result+="Union "; break;
        case ClassDef::Interface: result+="Antarmuka "; break;
        case ClassDef::Protocol: result+="Protokol "; break;
        case ClassDef::Category: result+="Kategori "; break;
        case ClassDef::Exception: result+="Eksepsi "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorIndonesian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 476 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktur Data";
      }
      else
      {
        return "Kelas";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorIndonesian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 476 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktur Data";
      }
      else
      {
        return "Kelas";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 813 of file translator_id.h.
    {
      return "Dokumentasi Konstruktor & Destruktor";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 813 of file translator_id.h.
    {
      return "Dokumentasi Konstruktor & Destruktor";
    }
trCopyright() [1/2]
virtual QCString TranslatorIndonesian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1824 of file translator_id.h.
    { return "Hak Cipta"; }
trCopyright() [2/2]
virtual QCString TranslatorIndonesian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1824 of file translator_id.h.
    { return "Hak Cipta"; }
trDataTypes() [1/2]
virtual QCString TranslatorIndonesian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1582 of file translator_id.h.
    { return "Tipe Data"; }
trDataTypes() [2/2]
virtual QCString TranslatorIndonesian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1582 of file translator_id.h.
    { return "Tipe Data"; }
trDate() [1/2]
virtual QCString TranslatorIndonesian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 514 of file translator_id.h.
    { return "Tanggal"; }
trDate() [2/2]
virtual QCString TranslatorIndonesian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 514 of file translator_id.h.
    { return "Tanggal"; }
trDateTime() [1/2]
virtual QCString TranslatorIndonesian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1781 of file translator_id.h.
    {
      static const char *days[] = { "Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu" };
      static const char *months[] = { "Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorIndonesian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1781 of file translator_id.h.
    {
      static const char *days[] = { "Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu" };
      static const char *months[] = { "Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorIndonesian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1797 of file translator_id.h.
    {
      static const char *days_short[] = { "Sen", "Sel", "Rab", "Kam", "Jum", "Sab", "Min" };
      static const char *days_full[] = { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorIndonesian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1797 of file translator_id.h.
    {
      static const char *days_short[] = { "Sen", "Sel", "Rab", "Kam", "Jum", "Sab", "Min" };
      static const char *days_full[] = { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayPeriod() [1/2]
virtual QCString TranslatorIndonesian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1809 of file translator_id.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorIndonesian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1809 of file translator_id.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorIndonesian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 780 of file translator_id.h.
    {
      return "Definisi pada baris @0 dalam file @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorIndonesian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 780 of file translator_id.h.
    {
      return "Definisi pada baris @0 dalam file @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorIndonesian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 148 of file translator_id.h.
    { return "didefinisikan di"; }
trDefinedIn() [2/2]
virtual QCString TranslatorIndonesian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 148 of file translator_id.h.
    { return "didefinisikan di"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorIndonesian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 784 of file translator_id.h.
    {
      return "Definisi dalam file @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorIndonesian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 784 of file translator_id.h.
    {
      return "Definisi dalam file @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 446 of file translator_id.h.
    { return "Dokumentasi Makro Definisi"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 446 of file translator_id.h.
    { return "Dokumentasi Makro Definisi"; }
trDefines() [1/2]
virtual QCString TranslatorIndonesian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 410 of file translator_id.h.
    { return "Makro Definisi"; }
trDefines() [2/2]
virtual QCString TranslatorIndonesian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 410 of file translator_id.h.
    { return "Makro Definisi"; }
trDefineValue() [1/2]
virtual QCString TranslatorIndonesian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1102 of file translator_id.h.
    {
      return "Nilai:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorIndonesian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1102 of file translator_id.h.
    {
      return "Nilai:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorIndonesian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 793 of file translator_id.h.
    {
      return "Kadaluarsa";
    }
trDeprecated() [2/2]
virtual QCString TranslatorIndonesian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 793 of file translator_id.h.
    {
      return "Kadaluarsa";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorIndonesian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1311 of file translator_id.h.
    {
      return "Daftar Kadaluarsa";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorIndonesian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1311 of file translator_id.h.
    {
      return "Daftar Kadaluarsa";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorIndonesian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 81 of file translator_id.h.
    { return "Keterangan Lengkap"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorIndonesian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 81 of file translator_id.h.
    { return "Keterangan Lengkap"; }
trDir() [1/2]
virtual QCString TranslatorIndonesian::trDir (bool first_capital, bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1478 of file translator_id.h.
    {
      QCString result((first_capital ? "Direktori" : "direktori"));
      //if (singular) result+="y"; else result+="ies";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorIndonesian::trDir (bool first_capital, bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1478 of file translator_id.h.
    {
      QCString result((first_capital ? "Direktori" : "direktori"));
      //if (singular) result+="y"; else result+="ies";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorIndonesian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1828 of file translator_id.h.
    { return QCString("Bagan dependensi directori untuk ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorIndonesian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1828 of file translator_id.h.
    { return QCString("Bagan dependensi directori untuk ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1460 of file translator_id.h.
    { return "Dokumentasi Direktori"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1460 of file translator_id.h.
    { return "Dokumentasi Direktori"; }
trDirectories() [1/2]
virtual QCString TranslatorIndonesian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1466 of file translator_id.h.
    { return "Daftar Direktori"; }
trDirectories() [2/2]
virtual QCString TranslatorIndonesian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1466 of file translator_id.h.
    { return "Daftar Direktori"; }
trDirIndex() [1/2]
virtual QCString TranslatorIndonesian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1454 of file translator_id.h.
    { return "Hierarki Direktori"; }
trDirIndex() [2/2]
virtual QCString TranslatorIndonesian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1454 of file translator_id.h.
    { return "Hierarki Direktori"; }
trDirReference() [1/2]
virtual QCString TranslatorIndonesian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1472 of file translator_id.h.
    { QCString result="Referensi Direktori "; result+=dirName; return result; }
trDirReference() [2/2]
virtual QCString TranslatorIndonesian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1472 of file translator_id.h.
    { QCString result="Referensi Direktori "; result+=dirName; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorIndonesian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1720 of file translator_id.h.
    {
      return "Relasi "+QCString(name);
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorIndonesian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1720 of file translator_id.h.
    {
      return "Relasi "+QCString(name);
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 330 of file translator_id.h.
    { return "Dokumentasi"; }
trDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 330 of file translator_id.h.
    { return "Dokumentasi"; }
trEnumerations() [1/2]
virtual QCString TranslatorIndonesian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 422 of file translator_id.h.
    { return "Enumerasi"; }
trEnumerations() [2/2]
virtual QCString TranslatorIndonesian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 422 of file translator_id.h.
    { return "Enumerasi"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 458 of file translator_id.h.
    { return "Dokumentasi Tipe Enumerasi"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 458 of file translator_id.h.
    { return "Dokumentasi Tipe Enumerasi"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1512 of file translator_id.h.
    { return "Dokumentasi Nilai Enumerasi"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1512 of file translator_id.h.
    { return "Dokumentasi Nilai Enumerasi"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorIndonesian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 440 of file translator_id.h.
    { return "Nilai enumerasi"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorIndonesian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 440 of file translator_id.h.
    { return "Nilai enumerasi"; }
trEnumName() [1/2]
virtual QCString TranslatorIndonesian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 140 of file translator_id.h.
    { return "nama enumerasi"; }
trEnumName() [2/2]
virtual QCString TranslatorIndonesian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 140 of file translator_id.h.
    { return "nama enumerasi"; }
trEnumValue() [1/2]
virtual QCString TranslatorIndonesian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 144 of file translator_id.h.
    { return "nilai enumerasi"; }
trEnumValue() [2/2]
virtual QCString TranslatorIndonesian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 144 of file translator_id.h.
    { return "nilai enumerasi"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1328 of file translator_id.h.
    {
      return "Dokumentasi Event";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1328 of file translator_id.h.
    {
      return "Dokumentasi Event";
    }
trEvents() [1/2]
virtual QCString TranslatorIndonesian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1323 of file translator_id.h.
    {
      return "Event";
    }
trEvents() [2/2]
virtual QCString TranslatorIndonesian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1323 of file translator_id.h.
    {
      return "Event";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 400 of file translator_id.h.
    { return "Dokumentasi Contoh"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 400 of file translator_id.h.
    { return "Dokumentasi Contoh"; }
trExamples() [1/2]
virtual QCString TranslatorIndonesian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 211 of file translator_id.h.
    { return "Contoh"; }
trExamples() [2/2]
virtual QCString TranslatorIndonesian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 211 of file translator_id.h.
    { return "Contoh"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorIndonesian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 316 of file translator_id.h.
    { return "Berikut ini daftar semua contoh:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorIndonesian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 316 of file translator_id.h.
    { return "Berikut ini daftar semua contoh:"; }
trExceptions() [1/2]
virtual QCString TranslatorIndonesian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 530 of file translator_id.h.
    { return "Eksepsi"; }
trExceptions() [2/2]
virtual QCString TranslatorIndonesian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 530 of file translator_id.h.
    { return "Eksepsi"; }
trFile() [1/2]
virtual QCString TranslatorIndonesian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1186 of file translator_id.h.
    {
      QCString result((first_capital ? "File" : "file"));
      if (!singular) result+="-file";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorIndonesian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1186 of file translator_id.h.
    {
      QCString result((first_capital ? "File" : "file"));
      if (!singular) result+="-file";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 394 of file translator_id.h.
    { return "Dokumentasi File"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 394 of file translator_id.h.
    { return "Dokumentasi File"; }
trFileIn() [1/2]
virtual QCString TranslatorIndonesian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1757 of file translator_id.h.
    {
      return "File dimuat dalam "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorIndonesian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1757 of file translator_id.h.
    {
      return "File dimuat dalam "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorIndonesian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 363 of file translator_id.h.
    { return "Indeks File"; }
trFileIndex() [2/2]
virtual QCString TranslatorIndonesian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 363 of file translator_id.h.
    { return "Indeks File"; }
trFileList() [1/2]
virtual QCString TranslatorIndonesian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 177 of file translator_id.h.
    { return "Daftar File"; }
trFileList() [2/2]
virtual QCString TranslatorIndonesian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 177 of file translator_id.h.
    { return "Daftar File"; }
trFileListDescription() [1/2]
virtual QCString TranslatorIndonesian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 225 of file translator_id.h.
    {
      QCString result="Berikut ini daftar seluruh file";
      if (!extractAll) result+=" yang didokumentasikan";
      result += ", dengan penjelasan singkat:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorIndonesian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 225 of file translator_id.h.
    {
      QCString result="Berikut ini daftar seluruh file";
      if (!extractAll) result+=" yang didokumentasikan";
      result += ", dengan penjelasan singkat:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorIndonesian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 194 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Daftar Definisi Global";
      }
      else
      {
        return "Daftar Anggota File";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorIndonesian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 194 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Daftar Definisi Global";
      }
      else
      {
        return "Daftar Anggota File";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorIndonesian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 294 of file translator_id.h.
    {
      QCString result="Berikut ini daftar ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="fungsi, variabel, makro definisi, enumerasi, dan tipe";
      }
      else
      {
        result+="file";
      }
      if (!extractAll) result+=" yang didokumentasikan";
      result+=", dengan tautan ke ";
      if (extractAll)
        result+="file yang memuatnya:";
      else
        result+="dokumentasinya:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorIndonesian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 294 of file translator_id.h.
    {
      QCString result="Berikut ini daftar ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="fungsi, variabel, makro definisi, enumerasi, dan tipe";
      }
      else
      {
        result+="file";
      }
      if (!extractAll) result+=" yang didokumentasikan";
      result+=", dengan tautan ke ";
      if (extractAll)
        result+="file yang memuatnya:";
      else
        result+="dokumentasinya:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorIndonesian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 597 of file translator_id.h.
    {
      QCString result="Referensi File ";
      result+=fileName;
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorIndonesian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 597 of file translator_id.h.
    {
      QCString result="Referensi File ";
      result+=fileName;
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorIndonesian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 557 of file translator_id.h.
    { return "Friend"; }
trFriends() [2/2]
virtual QCString TranslatorIndonesian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 557 of file translator_id.h.
    { return "Friend"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 464 of file translator_id.h.
    { return "Dokumentasi Fungsi"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 464 of file translator_id.h.
    { return "Dokumentasi Fungsi"; }
trFunctions() [1/2]
virtual QCString TranslatorIndonesian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 428 of file translator_id.h.
    { return "Fungsi"; }
trFunctions() [2/2]
virtual QCString TranslatorIndonesian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 428 of file translator_id.h.
    { return "Fungsi"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorIndonesian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 491 of file translator_id.h.
    {
      QCString result="Dibangkitkan pada tanggal "+date;
      if (!projName.isEmpty()) result+=" untuk "+projName;
      result+=" oleh";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorIndonesian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 491 of file translator_id.h.
    {
      QCString result="Dibangkitkan pada tanggal "+date;
      if (!projName.isEmpty()) result+=" untuk "+projName;
      result+=" oleh";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorIndonesian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 132 of file translator_id.h.
    { QCString result="Dibangkitkan secara otomatis oleh Doxygen";
      if (!s.isEmpty()) result+=" untuk "+s;
      result+=" dari kode sumber.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorIndonesian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 132 of file translator_id.h.
    { QCString result="Dibangkitkan secara otomatis oleh Doxygen";
      if (!s.isEmpty()) result+=" untuk "+s;
      result+=" dari kode sumber.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorIndonesian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 534 of file translator_id.h.
    { return "Dibangkitkan oleh"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorIndonesian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 534 of file translator_id.h.
    { return "Dibangkitkan oleh"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorIndonesian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 735 of file translator_id.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentasi untuk ";
      switch(compType)
      {
        case ClassDef::Class: result+="kelas"; break;
        case ClassDef::Struct: result+="struct"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protokol"; break;
        case ClassDef::Category: result+="kategori"; break;
        case ClassDef::Exception: result+="eksepsi"; break;
        default: break;
      }
      result+=" ini dibangkitkan dari file";
      result+=single ? "" : "-file";
      result+=" berikut:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorIndonesian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 735 of file translator_id.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentasi untuk ";
      switch(compType)
      {
        case ClassDef::Class: result+="kelas"; break;
        case ClassDef::Struct: result+="struct"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protokol"; break;
        case ClassDef::Category: result+="kategori"; break;
        case ClassDef::Exception: result+="eksepsi"; break;
        default: break;
      }
      result+=" ini dibangkitkan dari file";
      result+=single ? "" : "-file";
      result+=" berikut:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorIndonesian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1667 of file translator_id.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentasi untuk ";
      switch(compType)
      {
        case ClassDef::Class: result+="module"; break;
        case ClassDef::Struct: result+="type"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" ini dibangkitkan dari file";
      if (!single) result+="-file ";
      result+="berikut:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorIndonesian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1667 of file translator_id.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentasi untuk ";
      switch(compType)
      {
        case ClassDef::Class: result+="module"; break;
        case ClassDef::Struct: result+="type"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" ini dibangkitkan dari file";
      if (!single) result+="-file ";
      result+="berikut:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorIndonesian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1240 of file translator_id.h.
    {
      QCString result((first_capital ? "Definisi" : "definisi"));
      if (!singular) result+="-definisi";
      result += " global";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorIndonesian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1240 of file translator_id.h.
    {
      QCString result((first_capital ? "Definisi" : "definisi"));
      if (!singular) result+="-definisi";
      result += " global";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorIndonesian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1732 of file translator_id.h.
    {
      return "Namespace Global";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorIndonesian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1732 of file translator_id.h.
    {
      return "Namespace Global";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 823 of file translator_id.h.
    {
      return "Ke dokumentasi file ini.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 823 of file translator_id.h.
    {
      return "Ke dokumentasi file ini.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorIndonesian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 856 of file translator_id.h.
    {
      return "Ke bagan grafis hierarki kelas";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorIndonesian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 856 of file translator_id.h.
    {
      return "Ke bagan grafis hierarki kelas";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorIndonesian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 818 of file translator_id.h.
    {
      return "Ke kode sumber file ini.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorIndonesian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 818 of file translator_id.h.
    {
      return "Ke kode sumber file ini.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorIndonesian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 860 of file translator_id.h.
    {
      return "Ke bagan tekstual hierarki kelas";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorIndonesian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 860 of file translator_id.h.
    {
      return "Ke bagan tekstual hierarki kelas";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorIndonesian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 852 of file translator_id.h.
    {
      return "Hierarki Kelas Secara Grafis";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorIndonesian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 852 of file translator_id.h.
    {
      return "Hierarki Kelas Secara Grafis";
    }
trGroup() [1/2]
virtual QCString TranslatorIndonesian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1207 of file translator_id.h.
    {
      QCString result((first_capital ? "Kelompok" : "kelompok"));
      if (!singular) result+="-kelompok";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorIndonesian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1207 of file translator_id.h.
    {
      QCString result((first_capital ? "Kelompok" : "kelompok"));
      if (!singular) result+="-kelompok";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorIndonesian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 342 of file translator_id.h.
    { return "Indeks Hierarki Kelas"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorIndonesian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 342 of file translator_id.h.
    { return "Indeks Hierarki Kelas"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorIndonesian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1279 of file translator_id.h.
    {
      return "Mengimplementasikan "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorIndonesian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1279 of file translator_id.h.
    {
      return "Mengimplementasikan "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorIndonesian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1287 of file translator_id.h.
    {
      return "Diimplementasikan di "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorIndonesian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1287 of file translator_id.h.
    {
      return "Diimplementasikan di "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorIndonesian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_id.h.
    {
      return "Bagan ini menunjukkan file-file yang memuat"
    " atau menggunakan file ini baik secara langsung maupun"
    " tidak langsung:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorIndonesian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_id.h.
    {
      return "Bagan ini menunjukkan file-file yang memuat"
    " atau menggunakan file ini baik secara langsung maupun"
    " tidak langsung:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorIndonesian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 808 of file translator_id.h.
    {
      return "Bagan kebergantungan pemuatan untuk "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorIndonesian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 808 of file translator_id.h.
    {
      return "Bagan kebergantungan pemuatan untuk "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorIndonesian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1766 of file translator_id.h.
    {
      return "Memuat file dalam "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorIndonesian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1766 of file translator_id.h.
    {
      return "Memuat file dalam "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorIndonesian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 126 of file translator_id.h.
    { return ", termasuk semua anggota yang diwariskan."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorIndonesian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 126 of file translator_id.h.
    { return ", termasuk semua anggota yang diwariskan."; }
trInheritedByList() [1/2]
virtual QCString TranslatorIndonesian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 669 of file translator_id.h.
    {
      return "Diwariskan ke "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorIndonesian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 669 of file translator_id.h.
    {
      return "Diwariskan ke "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorIndonesian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 661 of file translator_id.h.
    {
      return "Mewarisi "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorIndonesian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 661 of file translator_id.h.
    {
      return "Mewarisi "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorIndonesian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 843 of file translator_id.h.
    {
      return "Nilai awal:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorIndonesian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 843 of file translator_id.h.
    {
      return "Nilai awal:";
    }
trInvariant() [1/2]
virtual QCString TranslatorIndonesian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 838 of file translator_id.h.
    {
      return "Invarian";
    }
trInvariant() [2/2]
virtual QCString TranslatorIndonesian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 838 of file translator_id.h.
    {
      return "Invarian";
    }
trISOLang() [1/2]
virtual QCString TranslatorIndonesian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 61 of file translator_id.h.
    {
      return "id";
    }
trISOLang() [2/2]
virtual QCString TranslatorIndonesian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 61 of file translator_id.h.
    {
      return "id";
    }
trLegend() [1/2]
virtual QCString TranslatorIndonesian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1035 of file translator_id.h.
    {
      return "keterangan";
    }
trLegend() [2/2]
virtual QCString TranslatorIndonesian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1035 of file translator_id.h.
    {
      return "keterangan";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorIndonesian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 975 of file translator_id.h.
    {
      return
        "Halaman ini berisi keterangan cara membaca bagan yang dibangkitkan "
        "oleh doxygen.<p>\n"
        "Contoh:\n"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Apabila tag \\c MAX_DOT_GRAPH_HEIGHT di file konfigurasi "
        "diset ke 240 kode di atas akan menghasilkan bagan berikut:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Kotak-kotak pada bagan di atas mempunyai arti sebagai berikut:\n"
        "<ul>\n"
        "<li>%Kotak hitam merupakan struct atau kelas yang bersangkutan.\n"
        "<li>%Kotak berbingkai hitam adalah struct atau kelas yang mempunyai dokumentasi.\n"
        "<li>%Kotak dengan bingkai abu-abu adalah struct atau kelas tanpa dokumentasi.\n"
        "<li>%Kotak dengan bingkai merah merupakan struct atau kelas yang didokumentasikan tetapi"
        "tidak semua relasinya ditampilkan. %Sebuah bagan "
        "akan terpotong apabila lebih besar daripada ukuran yang ditentukan.\n"
        "</ul>\n"
        "Arti dari tanda-tanda panah adalah sebagai berikut:\n"
        "<ul>\n"
        "<li>%Panah biru tua menandakan pewarisan publik.\n"
        "<li>%Panah hijau tua untuk pewarisan diproteksi.\n"
        "<li>%Panah merah tua untuk pewarisan privat.\n"
        "<li>%Panah ungu putus-putus menandakan kelas tersebut berhubungan dengan kelas lain. "
        "Panah tersebut diberi judul sesuai dengan kelas atau struct tujuan.\n"
        "<li>%Panah kuning putus-putus menandakan hubungan antara sebuah template kelas dan "
        "instance dari template tersebut. Panah tersebut diberi judul sesuai dengan "
        "parameter template yang digunakan.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorIndonesian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 975 of file translator_id.h.
    {
      return
        "Halaman ini berisi keterangan cara membaca bagan yang dibangkitkan "
        "oleh doxygen.<p>\n"
        "Contoh:\n"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Apabila tag \\c MAX_DOT_GRAPH_HEIGHT di file konfigurasi "
        "diset ke 240 kode di atas akan menghasilkan bagan berikut:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Kotak-kotak pada bagan di atas mempunyai arti sebagai berikut:\n"
        "<ul>\n"
        "<li>%Kotak hitam merupakan struct atau kelas yang bersangkutan.\n"
        "<li>%Kotak berbingkai hitam adalah struct atau kelas yang mempunyai dokumentasi.\n"
        "<li>%Kotak dengan bingkai abu-abu adalah struct atau kelas tanpa dokumentasi.\n"
        "<li>%Kotak dengan bingkai merah merupakan struct atau kelas yang didokumentasikan tetapi"
        "tidak semua relasinya ditampilkan. %Sebuah bagan "
        "akan terpotong apabila lebih besar daripada ukuran yang ditentukan.\n"
        "</ul>\n"
        "Arti dari tanda-tanda panah adalah sebagai berikut:\n"
        "<ul>\n"
        "<li>%Panah biru tua menandakan pewarisan publik.\n"
        "<li>%Panah hijau tua untuk pewarisan diproteksi.\n"
        "<li>%Panah merah tua untuk pewarisan privat.\n"
        "<li>%Panah ungu putus-putus menandakan kelas tersebut berhubungan dengan kelas lain. "
        "Panah tersebut diberi judul sesuai dengan kelas atau struct tujuan.\n"
        "<li>%Panah kuning putus-putus menandakan hubungan antara sebuah template kelas dan "
        "instance dari template tersebut. Panah tersebut diberi judul sesuai dengan "
        "parameter template yang digunakan.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorIndonesian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 968 of file translator_id.h.
    {
      return "Keterangan Bagan";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorIndonesian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 968 of file translator_id.h.
    {
      return "Keterangan Bagan";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorIndonesian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 114 of file translator_id.h.
    { return "Daftar semua anggota"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorIndonesian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 114 of file translator_id.h.
    { return "Daftar semua anggota"; }
trLoading() [1/2]
virtual QCString TranslatorIndonesian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1726 of file translator_id.h.
    {
      return "Memuat...";
    }
trLoading() [2/2]
virtual QCString TranslatorIndonesian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1726 of file translator_id.h.
    {
      return "Memuat...";
    }
trMainPage() [1/2]
virtual QCString TranslatorIndonesian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 767 of file translator_id.h.
    { return "Halaman Utama"; }
trMainPage() [2/2]
virtual QCString TranslatorIndonesian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 767 of file translator_id.h.
    { return "Halaman Utama"; }
trMember() [1/2]
virtual QCString TranslatorIndonesian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1229 of file translator_id.h.
    {
      QCString result((first_capital ? "Anggota" : "anggota"));
      if (!singular) result+="-anggota";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorIndonesian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1229 of file translator_id.h.
    {
      QCString result((first_capital ? "Anggota" : "anggota"));
      if (!singular) result+="-anggota";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 97 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentasi Variabel";
      }
      else
      {
        return "Dokumentasi Anggota: Data";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 97 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentasi Variabel";
      }
      else
      {
        return "Dokumentasi Anggota: Data";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 89 of file translator_id.h.
    { return "Dokumentasi Anggota: Enumerasi"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 89 of file translator_id.h.
    { return "Dokumentasi Anggota: Enumerasi"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 93 of file translator_id.h.
    { return "Dokumentasi Anggota: Fungsi"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 93 of file translator_id.h.
    { return "Dokumentasi Anggota: Fungsi"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorIndonesian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1520 of file translator_id.h.
    { return "Dokumentasi Fungsi/Subrutin Anggota"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorIndonesian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1520 of file translator_id.h.
    { return "Dokumentasi Fungsi/Subrutin Anggota"; }
trMemberList() [1/2]
virtual QCString TranslatorIndonesian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 118 of file translator_id.h.
    { return "Daftar anggota"; }
trMemberList() [2/2]
virtual QCString TranslatorIndonesian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 118 of file translator_id.h.
    { return "Daftar anggota"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 85 of file translator_id.h.
    { return "Dokumentasi Anggota: Tipe"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 85 of file translator_id.h.
    { return "Dokumentasi Anggota: Tipe"; }
trModule() [1/2]
virtual QCString TranslatorIndonesian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1658 of file translator_id.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="-modul";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorIndonesian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1658 of file translator_id.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="-modul";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 369 of file translator_id.h.
    { return "Dokumentasi Modul"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 369 of file translator_id.h.
    { return "Dokumentasi Modul"; }
trModuleIndex() [1/2]
virtual QCString TranslatorIndonesian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 336 of file translator_id.h.
    { return "Indeks Modul"; }
trModuleIndex() [2/2]
virtual QCString TranslatorIndonesian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 336 of file translator_id.h.
    { return "Indeks Modul"; }
trModuleReference() [1/2]
virtual QCString TranslatorIndonesian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1620 of file translator_id.h.
    {
      QCString result="Referensi Modul ";
      result+=namespaceName;
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorIndonesian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1620 of file translator_id.h.
    {
      QCString result="Referensi Modul ";
      result+=namespaceName;
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorIndonesian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 156 of file translator_id.h.
    { return "Modul"; }
trModules() [2/2]
virtual QCString TranslatorIndonesian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 156 of file translator_id.h.
    { return "Modul"; }
trModulesDescription() [1/2]
virtual QCString TranslatorIndonesian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 324 of file translator_id.h.
    { return "Berikut ini daftar semua modul:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorIndonesian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 324 of file translator_id.h.
    { return "Berikut ini daftar semua modul:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorIndonesian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1651 of file translator_id.h.
    { return "Indeks Modul"; }
trModulesIndex() [2/2]
virtual QCString TranslatorIndonesian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1651 of file translator_id.h.
    { return "Indeks Modul"; }
trModulesList() [1/2]
virtual QCString TranslatorIndonesian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1586 of file translator_id.h.
    { return "Modules List"; }
trModulesList() [2/2]
virtual QCString TranslatorIndonesian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1586 of file translator_id.h.
    { return "Modules List"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorIndonesian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1590 of file translator_id.h.
    {
      QCString result="Berikut daftar semua modul";
      if (!extractAll) result+=" terdokumentasi";
      result+=", dengan penjelasan singkat:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorIndonesian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1590 of file translator_id.h.
    {
      QCString result="Berikut daftar semua modul";
      if (!extractAll) result+=" terdokumentasi";
      result+=", dengan penjelasan singkat:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorIndonesian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1632 of file translator_id.h.
    {
      QCString result="Berikut daftar semua anggota modul ";
      if (!extractAll) result+="terdokumentasi ";
      result+="dengan tautan ke ";
      if (extractAll)
      {
        result+="dokumentasi modul untuk setiap anggota:";
      }
      else
      {
        result+="modul yang memuatnya:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorIndonesian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1632 of file translator_id.h.
    {
      QCString result="Berikut daftar semua anggota modul ";
      if (!extractAll) result+="terdokumentasi ";
      result+="dengan tautan ke ";
      if (extractAll)
      {
        result+="dokumentasi modul untuk setiap anggota:";
      }
      else
      {
        result+="modul yang memuatnya:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorIndonesian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1628 of file translator_id.h.
    { return "Anggota Modul"; }
trModulesMembers() [2/2]
virtual QCString TranslatorIndonesian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1628 of file translator_id.h.
    { return "Anggota Modul"; }
trMonth() [1/2]
virtual QCString TranslatorIndonesian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1803 of file translator_id.h.
    {
      static const char *months_short[] = { "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des" };
      static const char *months_full[] = { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMonth() [2/2]
virtual QCString TranslatorIndonesian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1803 of file translator_id.h.
    {
      static const char *months_short[] = { "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des" };
      static const char *months_full[] = { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMore() [1/2]
virtual QCString TranslatorIndonesian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 110 of file translator_id.h.
    { return "Selengkapnya..."; }
trMore() [2/2]
virtual QCString TranslatorIndonesian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 110 of file translator_id.h.
    { return "Selengkapnya..."; }
trNamespace() [1/2]
virtual QCString TranslatorIndonesian::trNamespace (bool first_capital, bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1197 of file translator_id.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorIndonesian::trNamespace (bool first_capital, bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1197 of file translator_id.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 715 of file translator_id.h.
    { return "Dokumentasi Namespace"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 715 of file translator_id.h.
    { return "Dokumentasi Namespace"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorIndonesian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 709 of file translator_id.h.
    { return "Indeks Namespace"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorIndonesian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 709 of file translator_id.h.
    { return "Indeks Namespace"; }
trNamespaceList() [1/2]
virtual QCString TranslatorIndonesian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 542 of file translator_id.h.
    { return "Daftar Namespace"; }
trNamespaceList() [2/2]
virtual QCString TranslatorIndonesian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 542 of file translator_id.h.
    { return "Daftar Namespace"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorIndonesian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 546 of file translator_id.h.
    {
      QCString result="Berikut ini daftar namespace";
      if (!extractAll) result+=" yang didokumentasikan";
      result+=", dengan keterangan singkat:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorIndonesian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 546 of file translator_id.h.
    {
      QCString result="Berikut ini daftar namespace";
      if (!extractAll) result+=" yang didokumentasikan";
      result+=", dengan keterangan singkat:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorIndonesian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 695 of file translator_id.h.
    {
      QCString result="Berikut ini daftar anggota namespace";
      if (!extractAll) result+=" yang didokumentasikan";
      result+=", dengan tautan ke ";
      if (extractAll)
        result+="dokumentasi namespace untuk setiap anggota:";
      else
        result+="namespace yang memuatnya:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorIndonesian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 695 of file translator_id.h.
    {
      QCString result="Berikut ini daftar anggota namespace";
      if (!extractAll) result+=" yang didokumentasikan";
      result+=", dengan tautan ke ";
      if (extractAll)
        result+="dokumentasi namespace untuk setiap anggota:";
      else
        result+="namespace yang memuatnya:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorIndonesian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 691 of file translator_id.h.
    { return "Anggota Namespace"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorIndonesian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 691 of file translator_id.h.
    { return "Anggota Namespace"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorIndonesian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 605 of file translator_id.h.
    {
      QCString result="Referensi Namespace ";
      result+=namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorIndonesian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 605 of file translator_id.h.
    {
      QCString result="Referensi Namespace ";
      result+=namespaceName;
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorIndonesian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 725 of file translator_id.h.
    { return "Daftar Namespace"; }
trNamespaces() [2/2]
virtual QCString TranslatorIndonesian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 725 of file translator_id.h.
    { return "Daftar Namespace"; }
trNoMatches() [1/2]
virtual QCString TranslatorIndonesian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1744 of file translator_id.h.
    {
      return "Tidak Ditemukan";
    }
trNoMatches() [2/2]
virtual QCString TranslatorIndonesian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1744 of file translator_id.h.
    {
      return "Tidak Ditemukan";
    }
trNote() [1/2]
virtual QCString TranslatorIndonesian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 873 of file translator_id.h.
    {
      return "Catatan";
    }
trNote() [2/2]
virtual QCString TranslatorIndonesian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 873 of file translator_id.h.
    {
      return "Catatan";
    }
trOverloadText() [1/2]
virtual QCString TranslatorIndonesian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1492 of file translator_id.h.
    {
      return "Ini adalah fungsi anggota yang di-overload"
    " untuk kemudahan. Perbedaannya dengan fungsi di atas"
    " hanya pada parameter-parameter yang diterima.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorIndonesian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1492 of file translator_id.h.
    {
      return "Ini adalah fungsi anggota yang di-overload"
    " untuk kemudahan. Perbedaannya dengan fungsi di atas"
    " hanya pada parameter-parameter yang diterima.";
    }
trPackage() [1/2]
virtual QCString TranslatorIndonesian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1087 of file translator_id.h.
    {
      return "Paket "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorIndonesian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1087 of file translator_id.h.
    {
      return "Paket "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorIndonesian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1364 of file translator_id.h.
    {
      return "Daftar Atribut Paket";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorIndonesian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1364 of file translator_id.h.
    {
      return "Daftar Atribut Paket";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorIndonesian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1346 of file translator_id.h.
    {
      return "Daftar Fungsi Paket";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorIndonesian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1346 of file translator_id.h.
    {
      return "Daftar Fungsi Paket";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorIndonesian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1092 of file translator_id.h.
    {
      return "Berikut ini daftar paket, dengan keterangan singkat (apabila tersedia):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorIndonesian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1092 of file translator_id.h.
    {
      return "Berikut ini daftar paket, dengan keterangan singkat (apabila tersedia):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorIndonesian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1350 of file translator_id.h.
    {
      return "Anggota-anggota Paket";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorIndonesian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1350 of file translator_id.h.
    {
      return "Anggota-anggota Paket";
    }
trPackages() [1/2]
virtual QCString TranslatorIndonesian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1097 of file translator_id.h.
    {
      return "Daftar Paket";
    }
trPackages() [2/2]
virtual QCString TranslatorIndonesian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1097 of file translator_id.h.
    {
      return "Daftar Paket";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorIndonesian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1339 of file translator_id.h.
    {
      return "Jenis Paket";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorIndonesian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1339 of file translator_id.h.
    {
      return "Jenis Paket";
    }
trPage() [1/2]
virtual QCString TranslatorIndonesian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1218 of file translator_id.h.
    {
      QCString result((first_capital ? "Halaman" : "halaman"));
      if (!singular) result+="-halaman";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorIndonesian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1218 of file translator_id.h.
    {
      QCString result((first_capital ? "Halaman" : "halaman"));
      if (!singular) result+="-halaman";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorIndonesian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 773 of file translator_id.h.
    { return "hal."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorIndonesian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 773 of file translator_id.h.
    { return "hal."; }
trPageIndex() [1/2]
virtual QCString TranslatorIndonesian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 864 of file translator_id.h.
    {
      return "Indeks Halaman";
    }
trPageIndex() [2/2]
virtual QCString TranslatorIndonesian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 864 of file translator_id.h.
    {
      return "Indeks Halaman";
    }
trParameters() [1/2]
virtual QCString TranslatorIndonesian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 526 of file translator_id.h.
    { return "Parameter"; }
trParameters() [2/2]
virtual QCString TranslatorIndonesian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 526 of file translator_id.h.
    { return "Parameter"; }
trPostcondition() [1/2]
virtual QCString TranslatorIndonesian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 833 of file translator_id.h.
    {
      return "Kondisi Akhir";
    }
trPostcondition() [2/2]
virtual QCString TranslatorIndonesian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 833 of file translator_id.h.
    {
      return "Kondisi Akhir";
    }
trPrecondition() [1/2]
virtual QCString TranslatorIndonesian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 828 of file translator_id.h.
    {
      return "Kondisi Awal";
    }
trPrecondition() [2/2]
virtual QCString TranslatorIndonesian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 828 of file translator_id.h.
    {
      return "Kondisi Awal";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorIndonesian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_id.h.
    {
      return "Atribut Privat";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorIndonesian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_id.h.
    {
      return "Atribut Privat";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorIndonesian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 626 of file translator_id.h.
    { return "Fungsi Anggota Privat"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorIndonesian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 626 of file translator_id.h.
    { return "Fungsi Anggota Privat"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorIndonesian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 628 of file translator_id.h.
    { return "Slot Privat"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorIndonesian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 628 of file translator_id.h.
    { return "Slot Privat"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorIndonesian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_id.h.
    {
      return "Tipe Privat";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorIndonesian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_id.h.
    {
      return "Tipe Privat";
    }
trProperties() [1/2]
virtual QCString TranslatorIndonesian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1060 of file translator_id.h.
    {
      return "Daftar Property";
    }
trProperties() [2/2]
virtual QCString TranslatorIndonesian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1060 of file translator_id.h.
    {
      return "Daftar Property";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1065 of file translator_id.h.
    {
      return "Dokumentasi Property";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1065 of file translator_id.h.
    {
      return "Dokumentasi Property";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorIndonesian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 900 of file translator_id.h.
    {
      return "Atribut Diproteksi";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorIndonesian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 900 of file translator_id.h.
    {
      return "Atribut Diproteksi";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorIndonesian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 620 of file translator_id.h.
    { return "Fungsi Anggota Diproteksi"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorIndonesian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 620 of file translator_id.h.
    { return "Fungsi Anggota Diproteksi"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorIndonesian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 622 of file translator_id.h.
    { return "Slot Diproteksi"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorIndonesian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 622 of file translator_id.h.
    { return "Slot Diproteksi"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorIndonesian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 896 of file translator_id.h.
    {
      return "Tipe Diproteksi";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorIndonesian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 896 of file translator_id.h.
    {
      return "Tipe Diproteksi";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorIndonesian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Variabel Data";
      }
      else
      {
        return "Atribut Publik";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorIndonesian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Variabel Data";
      }
      else
      {
        return "Atribut Publik";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorIndonesian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 612 of file translator_id.h.
    { return "Fungsi Anggota Publik"; }
trPublicMembers() [2/2]
virtual QCString TranslatorIndonesian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 612 of file translator_id.h.
    { return "Fungsi Anggota Publik"; }
trPublicSlots() [1/2]
virtual QCString TranslatorIndonesian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 614 of file translator_id.h.
    { return "Slot Publik"; }
trPublicSlots() [2/2]
virtual QCString TranslatorIndonesian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 614 of file translator_id.h.
    { return "Slot Publik"; }
trPublicTypes() [1/2]
virtual QCString TranslatorIndonesian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_id.h.
    {
      return "Tipe Publik";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorIndonesian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_id.h.
    {
      return "Tipe Publik";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorIndonesian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 940 of file translator_id.h.
    {
      return "Direferensikan oleh";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorIndonesian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 940 of file translator_id.h.
    {
      return "Direferensikan oleh";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorIndonesian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 404 of file translator_id.h.
    { return "Dokumen Referensi"; }
trReferenceManual() [2/2]
virtual QCString TranslatorIndonesian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 404 of file translator_id.h.
    { return "Dokumen Referensi"; }
trReferences() [1/2]
virtual QCString TranslatorIndonesian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1267 of file translator_id.h.
    {
      return "Referensi";
    }
trReferences() [2/2]
virtual QCString TranslatorIndonesian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1267 of file translator_id.h.
    {
      return "Referensi";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorIndonesian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 677 of file translator_id.h.
    {
      return "Di-reimplementasikan dari "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorIndonesian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 677 of file translator_id.h.
    {
      return "Di-reimplementasikan dari "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorIndonesian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 685 of file translator_id.h.
    {
      return "Diimplementasikan ulang di "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorIndonesian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 685 of file translator_id.h.
    {
      return "Diimplementasikan ulang di "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 567 of file translator_id.h.
    { return "Dokumentasi Friend Dan Fungsi Terkait"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 567 of file translator_id.h.
    { return "Dokumentasi Friend Dan Fungsi Terkait"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorIndonesian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 73 of file translator_id.h.
    { return "Fungsi-fungsi Terkait"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorIndonesian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 73 of file translator_id.h.
    { return "Fungsi-fungsi Terkait"; }
trRelatedPages() [1/2]
virtual QCString TranslatorIndonesian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 207 of file translator_id.h.
    { return "Halaman Terkait"; }
trRelatedPages() [2/2]
virtual QCString TranslatorIndonesian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 207 of file translator_id.h.
    { return "Halaman Terkait"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorIndonesian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 320 of file translator_id.h.
    { return "Berikut ini daftar semua halaman dokumentasi yang terkait:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorIndonesian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 320 of file translator_id.h.
    { return "Berikut ini daftar semua halaman dokumentasi yang terkait:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorIndonesian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 77 of file translator_id.h.
    { return "(Perhatikan bahwa fungsi-fungsi tersebut bukan fungsi anggota.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorIndonesian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 77 of file translator_id.h.
    { return "(Perhatikan bahwa fungsi-fungsi tersebut bukan fungsi anggota.)"; }
trRemarks() [1/2]
virtual QCString TranslatorIndonesian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 944 of file translator_id.h.
    {
      return "Keterangan";
    }
trRemarks() [2/2]
virtual QCString TranslatorIndonesian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 944 of file translator_id.h.
    {
      return "Keterangan";
    }
trReturns() [1/2]
virtual QCString TranslatorIndonesian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 518 of file translator_id.h.
    { return "Mengembalikan"; }
trReturns() [2/2]
virtual QCString TranslatorIndonesian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 518 of file translator_id.h.
    { return "Mengembalikan"; }
trReturnValues() [1/2]
virtual QCString TranslatorIndonesian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 762 of file translator_id.h.
    { return "Nilai kembali"; }
trReturnValues() [2/2]
virtual QCString TranslatorIndonesian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 762 of file translator_id.h.
    { return "Nilai kembali"; }
trRTFansicp() [1/2]
virtual QCString TranslatorIndonesian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1151 of file translator_id.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorIndonesian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1151 of file translator_id.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorIndonesian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1160 of file translator_id.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorIndonesian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1160 of file translator_id.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorIndonesian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1166 of file translator_id.h.
    {
      return "Indeks";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorIndonesian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1166 of file translator_id.h.
    {
      return "Indeks";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorIndonesian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1299 of file translator_id.h.
    {
      return "Daftar Isi";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorIndonesian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1299 of file translator_id.h.
    {
      return "Daftar Isi";
    }
trSearch() [1/2]
virtual QCString TranslatorIndonesian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 215 of file translator_id.h.
    { return "Cari"; }
trSearch() [2/2]
virtual QCString TranslatorIndonesian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 215 of file translator_id.h.
    { return "Cari"; }
trSearching() [1/2]
virtual QCString TranslatorIndonesian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1738 of file translator_id.h.
    {
      return "Mencari...";
    }
trSearching() [2/2]
virtual QCString TranslatorIndonesian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1738 of file translator_id.h.
    {
      return "Mencari...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorIndonesian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1431 of file translator_id.h.
    {
      return "Kecocokan:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorIndonesian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1431 of file translator_id.h.
    {
      return "Kecocokan:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorIndonesian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1412 of file translator_id.h.
    {
      if (numDocuments==0)
      {
        return "Maaf, tidak ada dokumen yang cocok.";
      }
      else if (numDocuments==1)
      {
        return "Ditemukan <b>1</b> dokumen yang cocok.";
      }
      else
      {
        return "Ditemukan <b>$num</b> documents yang cocok. "
               "Menampilkan hasil terbaik lebih awal.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorIndonesian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1412 of file translator_id.h.
    {
      if (numDocuments==0)
      {
        return "Maaf, tidak ada dokumen yang cocok.";
      }
      else if (numDocuments==1)
      {
        return "Ditemukan <b>1</b> dokumen yang cocok.";
      }
      else
      {
        return "Ditemukan <b>$num</b> documents yang cocok. "
               "Menampilkan hasil terbaik lebih awal.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorIndonesian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1400 of file translator_id.h.
    {
      return "Hasil Pencarian";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorIndonesian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1400 of file translator_id.h.
    {
      return "Hasil Pencarian";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorIndonesian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 522 of file translator_id.h.
    { return "Lihat juga"; }
trSeeAlso() [2/2]
virtual QCString TranslatorIndonesian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 522 of file translator_id.h.
    { return "Lihat juga"; }
trSignals() [1/2]
virtual QCString TranslatorIndonesian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 616 of file translator_id.h.
    { return "Signal"; }
trSignals() [2/2]
virtual QCString TranslatorIndonesian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 616 of file translator_id.h.
    { return "Signal"; }
trSince() [1/2]
virtual QCString TranslatorIndonesian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 958 of file translator_id.h.
    {
      return "Sejak";
    }
trSince() [2/2]
virtual QCString TranslatorIndonesian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 958 of file translator_id.h.
    {
      return "Sejak";
    }
trSourceFile() [1/2]
virtual QCString TranslatorIndonesian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1442 of file translator_id.h.
    {
      return "Kode Sumber:" + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorIndonesian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1442 of file translator_id.h.
    {
      return "Kode Sumber:" + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorIndonesian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1371 of file translator_id.h.
    {
      return "Daftar Atribut Statis Paket";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorIndonesian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1371 of file translator_id.h.
    {
      return "Daftar Atribut Statis Paket";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorIndonesian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1357 of file translator_id.h.
    {
      return "Daftar Fungsi Statis Paket";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorIndonesian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1357 of file translator_id.h.
    {
      return "Daftar Fungsi Statis Paket";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorIndonesian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_id.h.
    {
      return "Atribut Privat Statis";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorIndonesian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_id.h.
    {
      return "Atribut Privat Statis";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorIndonesian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 630 of file translator_id.h.
    { return "Fungsi Anggota Privat Statis"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorIndonesian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 630 of file translator_id.h.
    { return "Fungsi Anggota Privat Statis"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorIndonesian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_id.h.
    {
      return "Atribut Diproteksi Statis";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorIndonesian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_id.h.
    {
      return "Atribut Diproteksi Statis";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorIndonesian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 624 of file translator_id.h.
    { return "Fungsi Anggota Diproteksi Statis"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorIndonesian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 624 of file translator_id.h.
    { return "Fungsi Anggota Diproteksi Statis"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorIndonesian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 892 of file translator_id.h.
    {
      return "Atribut Publik Statis";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorIndonesian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 892 of file translator_id.h.
    {
      return "Atribut Publik Statis";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorIndonesian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 618 of file translator_id.h.
    { return "Fungsi Anggota Publik Statis"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorIndonesian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 618 of file translator_id.h.
    { return "Fungsi Anggota Publik Statis"; }
trSubprogram() [1/2]
virtual QCString TranslatorIndonesian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1702 of file translator_id.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram"));
      if (!singular) result+="-subprogram";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorIndonesian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1702 of file translator_id.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram"));
      if (!singular) result+="-subprogram";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1576 of file translator_id.h.
    { return "Dokumentasi Fungsi/Subrutin"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1576 of file translator_id.h.
    { return "Dokumentasi Fungsi/Subrutin"; }
trSubprograms() [1/2]
virtual QCString TranslatorIndonesian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1570 of file translator_id.h.
    { return "Fungsi/Subrutin"; }
trSubprograms() [2/2]
virtual QCString TranslatorIndonesian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1570 of file translator_id.h.
    { return "Fungsi/Subrutin"; }
trTest() [1/2]
virtual QCString TranslatorIndonesian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1045 of file translator_id.h.
    {
      return "Tes";
    }
trTest() [2/2]
virtual QCString TranslatorIndonesian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1045 of file translator_id.h.
    {
      return "Tes";
    }
trTestList() [1/2]
virtual QCString TranslatorIndonesian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1050 of file translator_id.h.
    {
      return "Daftar Tes";
    }
trTestList() [2/2]
virtual QCString TranslatorIndonesian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1050 of file translator_id.h.
    {
      return "Daftar Tes";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorIndonesian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 122 of file translator_id.h.
    { return "Berikut ini daftar lengkap anggota untuk "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorIndonesian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 122 of file translator_id.h.
    { return "Berikut ini daftar lengkap anggota untuk "; }
trTodo() [1/2]
virtual QCString TranslatorIndonesian::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 926 of file translator_id.h.
    {
      return "Tugas";
    }
trTodo() [2/2]
virtual QCString TranslatorIndonesian::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 926 of file translator_id.h.
    {
      return "Tugas";
    }
trTodoList() [1/2]
virtual QCString TranslatorIndonesian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 931 of file translator_id.h.
    {
      return "Daftar Tugas";
    }
trTodoList() [2/2]
virtual QCString TranslatorIndonesian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 931 of file translator_id.h.
    {
      return "Daftar Tugas";
    }
trType() [1/2]
virtual QCString TranslatorIndonesian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1692 of file translator_id.h.
    {
      QCString result((first_capital ? "Tipe" : "tipe"));
      if (!singular) result+="-tipe";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorIndonesian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1692 of file translator_id.h.
    {
      QCString result((first_capital ? "Tipe" : "tipe"));
      if (!singular) result+="-tipe";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorIndonesian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1710 of file translator_id.h.
    {
      return "Batasan Tipe";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorIndonesian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1710 of file translator_id.h.
    {
      return "Batasan Tipe";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 452 of file translator_id.h.
    { return "Dokumentasi Definisi Tipe"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 452 of file translator_id.h.
    { return "Dokumentasi Definisi Tipe"; }
trTypedefs() [1/2]
virtual QCString TranslatorIndonesian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 416 of file translator_id.h.
    { return "Definisi Tipe"; }
trTypedefs() [2/2]
virtual QCString TranslatorIndonesian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 416 of file translator_id.h.
    { return "Definisi Tipe"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1564 of file translator_id.h.
    { return "Dokumentasi Tipe Data"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1564 of file translator_id.h.
    { return "Dokumentasi Tipe Data"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorIndonesian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 470 of file translator_id.h.
    { return "Dokumentasi Variabel"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorIndonesian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 470 of file translator_id.h.
    { return "Dokumentasi Variabel"; }
trVariables() [1/2]
virtual QCString TranslatorIndonesian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 434 of file translator_id.h.
    { return "Variabel"; }
trVariables() [2/2]
virtual QCString TranslatorIndonesian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 434 of file translator_id.h.
    { return "Variabel"; }
trVersion() [1/2]
virtual QCString TranslatorIndonesian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 510 of file translator_id.h.
    { return "Versi"; }
trVersion() [2/2]
virtual QCString TranslatorIndonesian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 510 of file translator_id.h.
    { return "Versi"; }
trWarning() [1/2]
virtual QCString TranslatorIndonesian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 506 of file translator_id.h.
    { return "Peringatan"; }
trWarning() [2/2]
virtual QCString TranslatorIndonesian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 506 of file translator_id.h.
    { return "Peringatan"; }
trWriteList() [1/2]
virtual QCString TranslatorIndonesian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 636 of file translator_id.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
        // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", dan ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorIndonesian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 636 of file translator_id.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
        // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", dan ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_id.h
doxygen/src/translator_id.h