TextStream Class Reference
Text streaming class that buffers data.
#include <textstream.h>
Public Member Functions
TextStream ()
TextStream (std::ostream *s)
TextStream (const std::string &s)
~TextStream ()
TextStream (const TextStream &)=delete
TextStream & operator= (const TextStream &)=delete
void setStream (std::ostream *s)
void setFile (FILE *f)
std::ostream * stream () const
FILE * file () const
TextStream & operator<< (char c)
TextStream & operator<< (unsigned char c)
TextStream & operator<< (unsigned char *s)
TextStream & operator<< (const char *s)
TextStream & operator<< (const QCString &s)
TextStream & operator<< (const std::string &s)
TextStream & operator<< (signed short i)
TextStream & operator<< (unsigned short i)
TextStream & operator<< (signed int i)
TextStream & operator<< (unsigned int i)
template<typename T , typename std::enable_if< std::is_same< T, size_t >::value, T >::type * = nullptr>
TextStream & operator<< (T i)
TextStream & operator<< (float f)
TextStream & operator<< (double d)
void write (const char *buf, size_t len)
void flush ()
void clear ()
std::string str () const
void str (const std::string &s)
void str (const char *s)
bool empty () const
TextStream ()
TextStream (std::ostream *s)
TextStream (const std::string &s)
~TextStream ()
TextStream (const TextStream &)=delete
TextStream & operator= (const TextStream &)=delete
void setStream (std::ostream *s)
void setFile (FILE *f)
std::ostream * stream () const
FILE * file () const
TextStream & operator<< (char c)
TextStream & operator<< (unsigned char c)
TextStream & operator<< (unsigned char *s)
TextStream & operator<< (const char *s)
TextStream & operator<< (const QCString &s)
TextStream & operator<< (const std::string &s)
TextStream & operator<< (signed short i)
TextStream & operator<< (unsigned short i)
TextStream & operator<< (signed int i)
TextStream & operator<< (unsigned int i)
template<typename T , typename std::enable_if< std::is_same< T, size_t >::value, T >::type * = nullptr>
TextStream & operator<< (T i)
TextStream & operator<< (float f)
TextStream & operator<< (double d)
void write (const char *buf, size_t len)
void flush ()
void clear ()
std::string str () const
void str (const std::string &s)
void str (const char *s)
bool empty () const
Private Member Functions
void output_int32 (uint32_t n, bool neg)
void output_double (double d)
void output_int32 (uint32_t n, bool neg)
void output_double (double d)
Private Attributes
std::string m_buffer
std::ostream * m_s = nullptr
FILE * m_f = nullptr
Static Private Attributes
static const int INITIAL_CAPACITY = 4096
Detailed Description
Text streaming class that buffers data.
Simpler version of std::ostringstream that has much better performance.
Definition at line 34 of file textstream.h.
Constructor & Destructor Documentation
TextStream() [1/8]
TextStream::TextStream () [inline]
Creates an empty stream object.
Definition at line 40 of file textstream.h.
    {
      m_buffer.reserve(INITIAL_CAPACITY);
    }
References INITIAL_CAPACITY, and m_buffer.
TextStream() [2/8]
TextStream::TextStream (std::ostream * s) [inline]
Create a text stream object for writing to a std::ostream.
Note
data is buffered until flush() is called or the object is destroyed.
Definition at line 47 of file textstream.h.
                              : m_s(s)
    {
      m_buffer.reserve(INITIAL_CAPACITY);
    }
References INITIAL_CAPACITY, and m_buffer.
TextStream() [3/8]
TextStream::TextStream (const std::string & s) [inline]
Create a text stream, initializing the buffer with string s
Definition at line 53 of file textstream.h.
                                   : m_buffer(s)
    {
      m_buffer.reserve(s.length()+INITIAL_CAPACITY);
    }
References INITIAL_CAPACITY, m_buffer, and s.
 TextStream() [1/2]
TextStream::~TextStream () [inline]
Writes any data that is buffered to the attached std::ostream
Definition at line 59 of file textstream.h.
{ flush(); }
References flush().
TextStream() [4/8]
TextStream::TextStream (const TextStream &) [delete]
TextStream() [5/8]
TextStream::TextStream () [inline]
Creates an empty stream object.
Definition at line 40 of file textstream.h.
    {
      m_buffer.reserve(INITIAL_CAPACITY);
    }
References INITIAL_CAPACITY, and m_buffer.
TextStream() [6/8]
TextStream::TextStream (std::ostream * s) [inline]
Create a text stream object for writing to a std::ostream.
Note
data is buffered until flush() is called or the object is destroyed.
Definition at line 47 of file textstream.h.
                              : m_s(s)
    {
      m_buffer.reserve(INITIAL_CAPACITY);
    }
References INITIAL_CAPACITY, and m_buffer.
TextStream() [7/8]
TextStream::TextStream (const std::string & s) [inline]
Create a text stream, initializing the buffer with string s
Definition at line 53 of file textstream.h.
                                   : m_buffer(s)
    {
      m_buffer.reserve(s.length()+INITIAL_CAPACITY);
    }
References INITIAL_CAPACITY, m_buffer, and s.
 TextStream() [2/2]
TextStream::~TextStream () [inline]
Writes any data that is buffered to the attached std::ostream
Definition at line 59 of file textstream.h.
{ flush(); }
References flush().
TextStream() [8/8]
TextStream::TextStream (const TextStream &) [delete]
Member Function Documentation
clear() [1/2]
void TextStream::clear () [inline]
Clears any buffered data
Definition at line 223 of file textstream.h.
    {
      m_buffer.clear();
    }
References m_buffer.
clear() [2/2]
void TextStream::clear () [inline]
Clears any buffered data
Definition at line 223 of file textstream.h.
    {
      m_buffer.clear();
    }
References m_buffer.
empty() [1/2]
bool TextStream::empty () const [inline]
Returns true iff the buffer is empty
Definition at line 253 of file textstream.h.
    {
      return m_buffer.empty();
    }
References m_buffer.
Referenced by HtmlGenerator::endClassDiagram(), ClassContext::Private::inheritanceDiagram(), insertMapFile(), DotFilePatcher::run(), and writeDotImageMapFromFile().
empty() [2/2]
bool TextStream::empty () const [inline]
Returns true iff the buffer is empty
Definition at line 253 of file textstream.h.
    {
      return m_buffer.empty();
    }
References m_buffer.
file() [1/2]
FILE * TextStream::file () const [inline]
Definition at line 89 of file textstream.h.
    {
      return m_f;
    }
References m_f.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), and doxmlparser.compound.locationType::set_file().
file() [2/2]
FILE * TextStream::file () const [inline]
Definition at line 89 of file textstream.h.
    {
      return m_f;
    }
References m_f.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), and doxmlparser.compound.locationType::set_file().
flush() [1/2]
void TextStream::flush () [inline]
Flushes the buffer. If a std::ostream is attached, the buffer's contents will be written to the stream.
Definition at line 209 of file textstream.h.
    {
      if (m_s)
      {
        m_s->write(m_buffer.c_str(),m_buffer.length());
      }
      else if (m_f)
      {
        fwrite(m_buffer.c_str(),1,m_buffer.length(),m_f);
      }
      m_buffer.clear();
    }
References m_buffer, m_f, and m_s.
Referenced by FormulaManager::createLatexFile(), OutputGenerator::endPlainFile(), RTFGenerator::preProcessFileInplace(), TemplateNodeMsg::render(), DotFilePatcher::run(), setFile(), setStream(), str(), FlowChart::writeFlowChart(), VhdlDocGen::writeOverview(), and ~TextStream().
flush() [2/2]
void TextStream::flush () [inline]
Flushes the buffer. If a std::ostream is attached, the buffer's contents will be written to the stream.
Definition at line 209 of file textstream.h.
    {
      if (m_s)
      {
        m_s->write(m_buffer.c_str(),m_buffer.length());
      }
      else if (m_f)
      {
        fwrite(m_buffer.c_str(),1,m_buffer.length(),m_f);
      }
      m_buffer.clear();
    }
References m_buffer, m_f, and m_s.
operator<<() [1/26]
TextStream & TextStream::operator<< (char c) [inline]
Adds a character to the stream
Definition at line 95 of file textstream.h.
    {
      m_buffer+=c;
      return static_cast<TextStream&>(*this);
    }
References c, and m_buffer.
operator<<() [2/26]
TextStream & TextStream::operator<< (char c) [inline]
Adds a character to the stream
Definition at line 95 of file textstream.h.
    {
      m_buffer+=c;
      return static_cast<TextStream&>(*this);
    }
References c, and m_buffer.
operator<<() [3/26]
TextStream & TextStream::operator<< (const char * s) [inline]
Adds a C-style string to the stream
Definition at line 123 of file textstream.h.
    {
      if (s) m_buffer+=s;
      return static_cast<TextStream&>(*this);
    }
References m_buffer, and s.
operator<<() [4/26]
TextStream & TextStream::operator<< (const char * s) [inline]
Adds a C-style string to the stream
Definition at line 123 of file textstream.h.
    {
      if (s) m_buffer+=s;
      return static_cast<TextStream&>(*this);
    }
References m_buffer, and s.
operator<<() [5/26]
TextStream & TextStream::operator<< (const QCString & s) [inline]
Adds a QCString to the stream
Definition at line 130 of file textstream.h.
    {
      m_buffer+=s.str();
      return static_cast<TextStream&>(*this);
    }
References m_buffer, and s.
operator<<() [6/26]
TextStream & TextStream::operator<< (const QCString & s) [inline]
Adds a QCString to the stream
Definition at line 130 of file textstream.h.
    {
      m_buffer+=s.str();
      return static_cast<TextStream&>(*this);
    }
References m_buffer, and s.
operator<<() [7/26]
TextStream & TextStream::operator<< (const std::string & s) [inline]
Adds a std::string to the stream
Definition at line 137 of file textstream.h.
    {
      m_buffer+=s;
      return static_cast<TextStream&>(*this);
    }
References m_buffer, and s.
operator<<() [8/26]
TextStream & TextStream::operator<< (const std::string & s) [inline]
Adds a std::string to the stream
Definition at line 137 of file textstream.h.
    {
      m_buffer+=s;
      return static_cast<TextStream&>(*this);
    }
References m_buffer, and s.
operator<<() [9/26]
TextStream & TextStream::operator<< (double d) [inline]
Adds a double to the stream
Definition at line 191 of file textstream.h.
    {
      output_double(d);
      return static_cast<TextStream&>(*this);
    }
References output_double().
operator<<() [10/26]
TextStream & TextStream::operator<< (double d) [inline]
Adds a double to the stream
Definition at line 191 of file textstream.h.
    {
      output_double(d);
      return static_cast<TextStream&>(*this);
    }
References output_double().
operator<<() [11/26]
TextStream & TextStream::operator<< (float f) [inline]
Adds a float to the stream
Definition at line 184 of file textstream.h.
    {
      output_double(static_cast<double>(f));
      return static_cast<TextStream&>(*this);
    }
References f, and output_double().
operator<<() [12/26]
TextStream & TextStream::operator<< (float f) [inline]
Adds a float to the stream
Definition at line 184 of file textstream.h.
    {
      output_double(static_cast<double>(f));
      return static_cast<TextStream&>(*this);
    }
References f, and output_double().
operator<<() [13/26]
TextStream & TextStream::operator<< (signed int i) [inline]
Adds a signed integer to the stream
Definition at line 158 of file textstream.h.
    {
      output_int32(i,i<0);
      return static_cast<TextStream&>(*this);
    }
References output_int32().
operator<<() [14/26]
TextStream & TextStream::operator<< (signed int i) [inline]
Adds a signed integer to the stream
Definition at line 158 of file textstream.h.
    {
      output_int32(i,i<0);
      return static_cast<TextStream&>(*this);
    }
References output_int32().
operator<<() [15/26]
TextStream & TextStream::operator<< (signed short i) [inline]
Adds a signed short integer to the stream
Definition at line 144 of file textstream.h.
    {
      output_int32(i,i<0);
      return static_cast<TextStream&>(*this);
    }
References output_int32().
operator<<() [16/26]
TextStream & TextStream::operator<< (signed short i) [inline]
Adds a signed short integer to the stream
Definition at line 144 of file textstream.h.
    {
      output_int32(i,i<0);
      return static_cast<TextStream&>(*this);
    }
References output_int32().
operator<<() [17/26]
template<typename T , typename std::enable_if< std::is_same< T, size_t >::value, T >::type * = nullptr>
TextStream & TextStream::operator<< (T i) [inline]
Adds a size_t integer to the stream. We use SFINAE to avoid a compiler error in case size_t already matches the 'unsigned int' overload.
Definition at line 177 of file textstream.h.
    {
      output_int32(static_cast<uint>(i),false);
      return static_cast<TextStream&>(*this);
    }
References output_int32().
operator<<() [18/26]
template<typename T , typename std::enable_if< std::is_same< T, size_t >::value, T >::type * = nullptr>
TextStream & TextStream::operator<< (T i) [inline]
Adds a size_t integer to the stream. We use SFINAE to avoid a compiler error in case size_t already matches the 'unsigned int' overload.
Definition at line 177 of file textstream.h.
    {
      output_int32(static_cast<uint>(i),false);
      return static_cast<TextStream&>(*this);
    }
References output_int32().
operator<<() [19/26]
TextStream & TextStream::operator<< (unsigned char * s) [inline]
Adds an unsigned character string to the stream
Definition at line 108 of file textstream.h.
    {
      if (s)
      {
        unsigned char *p = s;
        while(*p)
        {
          m_buffer+=*p;
          p++;
        }
      }
      return static_cast<TextStream&>(*this);
    }
References m_buffer, p, and s.
operator<<() [20/26]
TextStream & TextStream::operator<< (unsigned char * s) [inline]
Adds an unsigned character string to the stream
Definition at line 108 of file textstream.h.
    {
      if (s)
      {
        unsigned char *p = s;
        while(*p)
        {
          m_buffer+=*p;
          p++;
        }
      }
      return static_cast<TextStream&>(*this);
    }
References m_buffer, p, and s.
operator<<() [21/26]
TextStream & TextStream::operator<< (unsigned char c) [inline]
Adds an unsigned character to the stream
Definition at line 101 of file textstream.h.
    {
      m_buffer+=c;
      return static_cast<TextStream&>(*this);
    }
References c, and m_buffer.
operator<<() [22/26]
TextStream & TextStream::operator<< (unsigned char c) [inline]
Adds an unsigned character to the stream
Definition at line 101 of file textstream.h.
    {
      m_buffer+=c;
      return static_cast<TextStream&>(*this);
    }
References c, and m_buffer.
operator<<() [23/26]
TextStream & TextStream::operator<< (unsigned int i) [inline]
Adds a unsigned integer to the stream
Definition at line 165 of file textstream.h.
    {
      output_int32(i,false);
      return static_cast<TextStream&>(*this);
    }
References output_int32().
operator<<() [24/26]
TextStream & TextStream::operator<< (unsigned int i) [inline]
Adds a unsigned integer to the stream
Definition at line 165 of file textstream.h.
    {
      output_int32(i,false);
      return static_cast<TextStream&>(*this);
    }
References output_int32().
operator<<() [25/26]
TextStream & TextStream::operator<< (unsigned short i) [inline]
Adds a unsigned short integer to the stream
Definition at line 151 of file textstream.h.
    {
      output_int32(i,false);
      return static_cast<TextStream&>(*this);
    }
References output_int32().
operator<<() [26/26]
TextStream & TextStream::operator<< (unsigned short i) [inline]
Adds a unsigned short integer to the stream
Definition at line 151 of file textstream.h.
    {
      output_int32(i,false);
      return static_cast<TextStream&>(*this);
    }
References output_int32().
operator=() [1/2]
TextStream & TextStream::operator= (const TextStream &) [delete]
operator=() [2/2]
TextStream & TextStream::operator= (const TextStream &) [delete]
output_double() [1/2]
void TextStream::output_double (double d) [inline], [private]
Definition at line 276 of file textstream.h.
    {
      char buf[64];
      snprintf(buf,64,"%f",d);
      m_buffer+=buf;
    }
References m_buffer.
Referenced by operator<<().
output_double() [2/2]
void TextStream::output_double (double d) [inline], [private]
Definition at line 276 of file textstream.h.
    {
      char buf[64];
      snprintf(buf,64,"%f",d);
      m_buffer+=buf;
    }
References m_buffer.
output_int32() [1/2]
void TextStream::output_int32 (uint32_t n, bool neg) [inline], [private]
Writes a string representation of an integer to the buffer
Parameters
n the absolute value of the integer
neg indicates if the integer is negative
Definition at line 263 of file textstream.h.
    {
      char buf[20];
      char *p = &buf[19];
      *p = '\0';
      if (neg)
      {
    n = static_cast<uint32_t>(-static_cast<int32_t>(n));
      }
      do { *--p = (static_cast<char>(n%10)) + '0'; n /= 10; } while (n);
      if (neg) *--p = '-';
      m_buffer+=p;
    }
References m_buffer, n, and p.
Referenced by operator<<().
output_int32() [2/2]
void TextStream::output_int32 (uint32_t n, bool neg) [inline], [private]
Writes a string representation of an integer to the buffer
Parameters
n the absolute value of the integer
neg indicates if the integer is negative
Definition at line 263 of file textstream.h.
    {
      char buf[20];
      char *p = &buf[19];
      *p = '\0';
      if (neg)
      {
    n = static_cast<uint32_t>(-static_cast<int32_t>(n));
      }
      do { *--p = (static_cast<char>(n%10)) + '0'; n /= 10; } while (n);
      if (neg) *--p = '-';
      m_buffer+=p;
    }
References m_buffer, n, and p.
setFile() [1/2]
void TextStream::setFile (FILE * f) [inline]
Definition at line 74 of file textstream.h.
    {
      flush();
      m_s = nullptr;
      m_f = f;
    }
References f, flush(), m_f, and m_s.
Referenced by OutputGenerator::startPlainFile().
setFile() [2/2]
void TextStream::setFile (FILE * f) [inline]
Definition at line 74 of file textstream.h.
    {
      flush();
      m_s = nullptr;
      m_f = f;
    }
References f, flush(), m_f, and m_s.
setStream() [1/2]
void TextStream::setStream (std::ostream * s) [inline]
Sets or changes the std::ostream to write to.
Note
Any data already buffered will be flushed.
Definition at line 67 of file textstream.h.
    {
      flush();
      m_s = s;
      m_f = nullptr;
    }
References flush(), m_f, m_s, and s.
Referenced by OutputGenerator::endPlainFile(), and DotFilePatcher::run().
setStream() [2/2]
void TextStream::setStream (std::ostream * s) [inline]
Sets or changes the std::ostream to write to.
Note
Any data already buffered will be flushed.
Definition at line 67 of file textstream.h.
    {
      flush();
      m_s = s;
      m_f = nullptr;
    }
References flush(), m_f, m_s, and s.
str() [1/6]
std::string TextStream::str () const [inline]
Return the contents of the buffer as a std::string object
Definition at line 229 of file textstream.h.
    {
      return m_buffer;
    }
References m_buffer.
Referenced by addConceptToContext(), addMemberDocs(), addVariableToClass(), addVariableToFile(), MemberContext::Private::callerGraph(), MemberContext::Private::callGraph(), ClassContext::Private::collaborationDiagram(), DotGraph::computeGraph(), DotDirDeps::computeTheGraph(), DotGfxHierarchyTable::computeTheGraph(), DotGroupCollaboration::computeTheGraph(), DotLegendGraph::computeTheGraph(), convertToLaTeX(), InheritanceGraphContext::Private::createGraph(), createLinkedText(), DirContext::Private::dirGraph(), HtmlGenerator::endClassDiagram(), Entry::Entry(), escapeCommas(), getMscImageMapFromFile(), getSearchBox(), ModuleContext::Private::groupGraph(), FileContext::Private::includedByGraph(), FileContext::Private::includeGraph(), ClassContext::Private::inheritanceDiagram(), insertMapFile(), latexEscapeIndexChars(), latexEscapeLabelName(), latexEscapePDFString(), latexFilterURL(), HtmlDocVisitor::operator()(), parseCode(), parseCommentAsText(), parseDoc(), LatexSpaceless::remove(), HtmlSpaceless::remove(), TemplateNodeCreate::render(), TemplateNodeBlock::render(), TemplateNodeTree::renderChildren(), Entry::reset(), DotFilePatcher::run(), searchId(), stripIndentation(), substituteLatexKeywords(), templateSpec(), writeAnnotatedIndexGeneric(), writeConceptIndex(), ConceptDefImpl::writeDefinition(), writeDotImageMapFromFile(), writeFileIndex(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeNamespaceIndex(), and writePageIndex().
str() [2/6]
std::string TextStream::str () const [inline]
Return the contents of the buffer as a std::string object
Definition at line 229 of file textstream.h.
    {
      return m_buffer;
    }
References m_buffer.
str() [3/6]
void TextStream::str (const char * s) [inline]
Sets the buffer's contents to string s Any data already in the buffer will be flushed.
Definition at line 246 of file textstream.h.
    {
      flush();
      if (s) m_buffer=s;
    }
References flush(), m_buffer, and s.
str() [4/6]
void TextStream::str (const char * s) [inline]
Sets the buffer's contents to string s Any data already in the buffer will be flushed.
Definition at line 246 of file textstream.h.
    {
      flush();
      if (s) m_buffer=s;
    }
References flush(), m_buffer, and s.
str() [5/6]
void TextStream::str (const std::string & s) [inline]
Sets the buffer's contents to string s. Any data already in the buffer will be flushed.
Definition at line 237 of file textstream.h.
    {
      flush();
      m_buffer=s;
    }
References flush(), m_buffer, and s.
str() [6/6]
void TextStream::str (const std::string & s) [inline]
Sets the buffer's contents to string s. Any data already in the buffer will be flushed.
Definition at line 237 of file textstream.h.
    {
      flush();
      m_buffer=s;
    }
References flush(), m_buffer, and s.
stream() [1/2]
std::ostream * TextStream::stream () const [inline]
Returns the attached std::ostream object.
See also
setStream()
Definition at line 84 of file textstream.h.
    {
      return m_s;
    }
References m_s.
Referenced by OutputGenerator::operator=(), and OutputGenerator::OutputGenerator().
stream() [2/2]
std::ostream * TextStream::stream () const [inline]
Returns the attached std::ostream object.
See also
setStream()
Definition at line 84 of file textstream.h.
    {
      return m_s;
    }
References m_s.
write() [1/2]
void TextStream::write (const char * buf, size_t len) [inline]
Adds a array of character to the stream
Parameters
buf the character buffer
len the number of characters in the buffer to write
Definition at line 201 of file textstream.h.
    {
      m_buffer.append(buf,len);
    }
References len, and m_buffer.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), DotGfxHierarchyTable::computeTheGraph(), doxmlparser.compound.memberdefType::exportChildren(), generateXML(), doxmlparser.compound.memberdefType::get_write(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.memberdefType::set_write(), and writeUTF8Char().
write() [2/2]
void TextStream::write (const char * buf, size_t len) [inline]
Adds a array of character to the stream
Parameters
buf the character buffer
len the number of characters in the buffer to write
Definition at line 201 of file textstream.h.
    {
      m_buffer.append(buf,len);
    }
References len, and m_buffer.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_write(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_write().
Member Data Documentation
INITIAL_CAPACITY
static const int TextStream::INITIAL_CAPACITY = 4096 [static], [private]
Definition at line 36 of file textstream.h.
Referenced by TextStream().
m_buffer
std::string TextStream::m_buffer [private]
Definition at line 282 of file textstream.h.
Referenced by clear(), empty(), flush(), operator<<(), output_double(), output_int32(), str(), TextStream(), and write().
m_f
FILE * TextStream::m_f = nullptr [private]
Definition at line 284 of file textstream.h.
Referenced by file(), flush(), setFile(), and setStream().
m_s
std::ostream * TextStream::m_s = nullptr [private]
Definition at line 283 of file textstream.h.
Referenced by flush(), setFile(), setStream(), and stream().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/textstream.h
doxygen/src/textstream.h