vhdl::parser::VhdlParserTokenManager Class Reference
#include <VhdlParserTokenManager.h>
Public Member Functions
void setDebugStream (FILE *ds)
int jjStopAtPos (int pos, int kind)
int jjMoveStringLiteralDfa0_0 ()
int jjMoveStringLiteralDfa1_0 (unsigned long long active0, unsigned long long active1, unsigned long long active2)
int jjMoveStringLiteralDfa2_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1, unsigned long long old2, unsigned long long active2)
int jjMoveStringLiteralDfa3_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1, unsigned long long old2, unsigned long long active2)
int jjMoveStringLiteralDfa4_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa5_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa6_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa7_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa8_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa9_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa10_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa11_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa12_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa13_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa14_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa15_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa16_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa17_0 (unsigned long long old1, unsigned long long active1)
int jjMoveNfa_0 (int startState, int curPos)
bool jjCanMove_0 (int hiByte, int i1, int i2, unsigned long long l1, unsigned long long l2)
bool jjCanMove_1 (int hiByte, int i1, int i2, unsigned long long l1, unsigned long long l2)
Token * jjFillToken ()
Token * getNextToken ()
void SkipLexicalActions (Token *matchedToken)
void TokenLexicalActions (Token *matchedToken)
VhdlParserTokenManager (JAVACC_CHARSTREAM *stream, int lexState=0)
virtual ~VhdlParserTokenManager ()
void ReInit (JAVACC_CHARSTREAM *stream, int lexState=0)
void SwitchTo (int lexState)
void clear ()
const JJSimpleString jjKindsForBitVector (int i, unsigned long long vec)
const JJSimpleString jjKindsForStateVector (int lexState, int vec[], int start, int end)
void setErrorHandler (TokenManagerErrorHandler *eh)
void setDebugStream (FILE *ds)
int jjStopAtPos (int pos, int kind)
int jjMoveStringLiteralDfa0_0 ()
int jjMoveStringLiteralDfa1_0 (unsigned long long active0, unsigned long long active1, unsigned long long active2)
int jjMoveStringLiteralDfa2_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1, unsigned long long old2, unsigned long long active2)
int jjMoveStringLiteralDfa3_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1, unsigned long long old2, unsigned long long active2)
int jjMoveStringLiteralDfa4_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa5_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa6_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa7_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa8_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa9_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa10_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa11_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa12_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa13_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa14_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa15_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa16_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
int jjMoveStringLiteralDfa17_0 (unsigned long long old1, unsigned long long active1)
int jjMoveNfa_0 (int startState, int curPos)
bool jjCanMove_0 (int hiByte, int i1, int i2, unsigned long long l1, unsigned long long l2)
bool jjCanMove_1 (int hiByte, int i1, int i2, unsigned long long l1, unsigned long long l2)
Token * jjFillToken ()
Token * getNextToken ()
void SkipLexicalActions (Token *matchedToken)
void TokenLexicalActions (Token *matchedToken)
VhdlParserTokenManager (JAVACC_CHARSTREAM *stream, int lexState=0)
virtual ~VhdlParserTokenManager ()
void ReInit (JAVACC_CHARSTREAM *stream, int lexState=0)
void SwitchTo (int lexState)
void clear ()
const JJSimpleString jjKindsForBitVector (int i, unsigned long long vec)
const JJSimpleString jjKindsForStateVector (int lexState, int vec[], int start, int end)
void setErrorHandler (TokenManagerErrorHandler *eh)
Public Attributes
FILE * debugStream
int curLexState = 0
int jjnewStateCnt = 0
int jjround = 0
int jjmatchedPos = 0
int jjmatchedKind = 0
JAVACC_CHARSTREAM * input_stream
int jjrounds [87]
int jjstateSet [2 *87]
JJString jjimage
JJString image
int jjimageLen
int lengthOfMatch
JJChar curChar
TokenManagerErrorHandler * errorHandler = nullptr
Private Member Functions
void ReInitRounds ()
void ReInitRounds ()
Detailed Description
Token Manager.
Definition at line 18 of file VhdlParserTokenManager.h.
Constructor & Destructor Documentation
VhdlParserTokenManager() [1/2]
vhdl::parser::VhdlParserTokenManager::VhdlParserTokenManager (JAVACC_CHARSTREAM * stream, int lexState = 0)
Constructor.
Definition at line 3706 of file VhdlParserTokenManager.cc.
  : TokenParser()
  {
    input_stream = nullptr;
    ReInit(stream, lexState);
  }
References input_stream, and ReInit().
 VhdlParserTokenManager() [1/2]
vhdl::parser::VhdlParserTokenManager::~VhdlParserTokenManager () [virtual]
Definition at line 3714 of file VhdlParserTokenManager.cc.
                                                   {
    clear();
  }
References clear().
VhdlParserTokenManager() [2/2]
vhdl::parser::VhdlParserTokenManager::VhdlParserTokenManager (JAVACC_CHARSTREAM * stream, int lexState = 0)
 VhdlParserTokenManager() [2/2]
virtual vhdl::parser::VhdlParserTokenManager::~VhdlParserTokenManager () [virtual]
Member Function Documentation
clear() [1/2]
void vhdl::parser::VhdlParserTokenManager::clear ()
Definition at line 3719 of file VhdlParserTokenManager.cc.
                                     {
    //Since input_stream was generated outside of TokenManager
    //TokenManager should not take care of deleting it
    //if (input_stream) delete input_stream;
    if (errorHandler) delete errorHandler, errorHandler = nullptr;
  }
References errorHandler.
Referenced by ReInit(), and ~VhdlParserTokenManager().
clear() [2/2]
void vhdl::parser::VhdlParserTokenManager::clear ()
getNextToken() [1/2]
Token * vhdl::parser::VhdlParserTokenManager::getNextToken () [virtual]
Get the next Token.
Implements vhdl::parser::TokenManager.
Definition at line 3426 of file VhdlParserTokenManager.cc.
                                            {
  Token *matchedToken = nullptr;
  int curPos = 0;
  for (;;)
  {
   EOFLoop:
   if (input_stream->endOfInput())
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   curChar = input_stream->BeginToken();
   image = jjimage;
   image.clear();
   jjimageLen = 0;
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream->backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1ULL << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         TokenLexicalActions(matchedToken);
         return matchedToken;
      }
      else
      {
         SkipLexicalActions(nullptr);
         goto EOFLoop;
      }
   }
   int error_line = input_stream->getEndLine();
   int error_column = input_stream->getEndColumn();
   JJString error_after;
   bool EOFSeen = false;
   if (input_stream->endOfInput()) {
      EOFSeen = true;
      error_after = curPos <= 1 ? EMPTY : input_stream->GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      error_after = curPos <= 1 ? EMPTY : input_stream->GetImage();
   }
   errorHandler->lexicalError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, this);
  }
}
References curChar, curLexState, EMPTY, errorHandler, image, input_stream, jjFillToken(), jjimage, jjimageLen, jjmatchedKind, jjmatchedPos, jjMoveStringLiteralDfa0_0(), vhdl::parser::jjtoToken, vhdl::parser::TokenManagerErrorHandler::lexicalError(), SkipLexicalActions(), and TokenLexicalActions().
getNextToken() [2/2]
Token * vhdl::parser::VhdlParserTokenManager::getNextToken () [virtual]
This gets the next token from the input stream. A token of kind 0 (<EOF>) should be returned on EOF.
Implements vhdl::parser::TokenManager.
jjCanMove_0() [1/2]
bool vhdl::parser::VhdlParserTokenManager::jjCanMove_0 (int hiByte, int i1, int i2, unsigned long long l1, unsigned long long l2)
Definition at line 3371 of file VhdlParserTokenManager.cc.
                                                                                                                {
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
References vhdl::parser::jjbitVec0, and vhdl::parser::jjbitVec2.
Referenced by jjMoveNfa_0().
jjCanMove_0() [2/2]
bool vhdl::parser::VhdlParserTokenManager::jjCanMove_0 (int hiByte, int i1, int i2, unsigned long long l1, unsigned long long l2)
jjCanMove_1() [1/2]
bool vhdl::parser::VhdlParserTokenManager::jjCanMove_1 (int hiByte, int i1, int i2, unsigned long long l1, unsigned long long l2)
Definition at line 3383 of file VhdlParserTokenManager.cc.
                                                                                                                {
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec3[i2] & l2) != 0L);
      default :
         return false;
   }
}
References vhdl::parser::jjbitVec3.
Referenced by jjMoveNfa_0().
jjCanMove_1() [2/2]
bool vhdl::parser::VhdlParserTokenManager::jjCanMove_1 (int hiByte, int i1, int i2, unsigned long long l1, unsigned long long l2)
jjFillToken() [1/2]
Token * vhdl::parser::VhdlParserTokenManager::jjFillToken ()
Token literal values.
Definition at line 3395 of file VhdlParserTokenManager.cc.
                                           {
   Token *t;
   JJString curTokenImage;
   int beginLine = -1;
   int endLine = -1;
   int beginColumn = -1;
   int endColumn = -1;
   JJString im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im.length() == 0) ? input_stream->GetImage() : im;
   if (input_stream->getTrackLineColumn()) {
     beginLine = input_stream->getBeginLine();
     beginColumn = input_stream->getBeginColumn();
     endLine = input_stream->getEndLine();
     endColumn = input_stream->getEndColumn();
   }
   t = Token::newToken(jjmatchedKind, curTokenImage);
   t->specialToken = nullptr;
   t->next = nullptr;
   if (input_stream->getTrackLineColumn()) {
   t->beginLine = beginLine;
   t->endLine = endLine;
   t->beginColumn = beginColumn;
   t->endColumn = endColumn;
   }
   return t;
}
References vhdl::parser::Token::beginColumn, vhdl::parser::Token::beginLine, vhdl::parser::Token::endColumn, vhdl::parser::Token::endLine, input_stream, jjmatchedKind, vhdl::parser::jjstrLiteralImages, vhdl::parser::Token::newToken(), vhdl::parser::Token::next, and vhdl::parser::Token::specialToken.
Referenced by getNextToken().
jjFillToken() [2/2]
Token * vhdl::parser::VhdlParserTokenManager::jjFillToken ()
jjKindsForBitVector() [1/2]
const JJSimpleString vhdl::parser::VhdlParserTokenManager::jjKindsForBitVector (int i, unsigned long long vec)
jjKindsForBitVector() [2/2]
const JJSimpleString vhdl::parser::VhdlParserTokenManager::jjKindsForBitVector (int i, unsigned long long vec)
jjKindsForStateVector() [1/2]
const JJSimpleString vhdl::parser::VhdlParserTokenManager::jjKindsForStateVector (int lexState, int vec[], int start, int end)
jjKindsForStateVector() [2/2]
const JJSimpleString vhdl::parser::VhdlParserTokenManager::jjKindsForStateVector (int lexState, int vec[], int start, int end)
jjMoveNfa_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveNfa_0 (int startState, int curPos)
Definition at line 2684 of file VhdlParserTokenManager.cc.
                                                                 {
   int strKind = jjmatchedKind;
   int strPos = jjmatchedPos;
   int seenUpto;
   input_stream->backup(seenUpto = curPos + 1);
   assert(!input_stream->endOfInput());
   curChar = input_stream->readChar();
   curPos = 0;
   int startsAt = 0;
   jjnewStateCnt = 87;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         unsigned long long l = 1ULL << curChar;
         (void)l;
         do
         {
            switch(jjstateSet[--i])
            {
               case 11:
                  if ((0x3ff000000000000ULL & l) != 0L)
                  {
                     if (kind > 165)
                        kind = 165;
                     { jjCheckNAddStates(0, 12); }
                  }
                  else if ((0x100000200ULL & l) != 0L)
                     { jjCheckNAddTwoStates(0, 3); }
                  else if (curChar == 39)
                     { jjAddStates(13, 14); }
                  else if (curChar == 47)
                     { jjAddStates(15, 16); }
                  else if (curChar == 45)
                     { jjCheckNAddStates(17, 19); }
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(9, 10); }
                  if ((0x3ff000000000000ULL & l) != 0L)
                  {
                     if (kind > 171)
                        kind = 171;
                     { jjCheckNAdd(17); }
                  }
                  break;
               case 0:
                  if ((0x100000200ULL & l) != 0L)
                     { jjCheckNAddTwoStates(0, 3); }
                  break;
               case 1:
                  if (curChar != 33)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAddStates(20, 24); }
                  break;
               case 2:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 45)
                     { jjCheckNAdd(2); }
                  break;
               case 4:
                  if ((0xffffffffffffdbffULL & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAddStates(20, 24); }
                  break;
               case 5:
                  if ((0x2400ULL & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAddTwoStates(0, 3); }
                  break;
               case 6:
                  if (curChar != 10)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAddTwoStates(0, 3); }
                  break;
               case 7:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(9, 10); }
                  break;
               case 9:
                  if ((0xfffffffb00000200ULL & l) != 0L)
                     { jjCheckNAddTwoStates(9, 10); }
                  break;
               case 10:
                  if (curChar != 34)
                     break;
                  if (kind > 166)
                     kind = 166;
                  jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 13:
                  if ((0x3ff000000000000ULL & l) == 0L)
                     break;
                  if (kind > 167)
                     kind = 167;
                  { jjAddStates(25, 26); }
                  break;
               case 15:
                  if ((0xfffffffb00000200ULL & l) != 0L)
                     { jjAddStates(27, 28); }
                  break;
               case 17:
                  if ((0x3ff000000000000ULL & l) == 0L)
                     break;
                  if (kind > 171)
                     kind = 171;
                  { jjCheckNAdd(17); }
                  break;
               case 20:
                  if (curChar == 34)
                     { jjCheckNAdd(21); }
                  break;
               case 21:
                  if ((0x3ff200000000000ULL & l) != 0L)
                     { jjCheckNAddStates(29, 31); }
                  break;
               case 23:
                  if (curChar == 34 && kind > 180)
                     kind = 180;
                  break;
               case 25:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(26, 27); }
                  break;
               case 26:
                  if ((0xfffffffb00000200ULL & l) != 0L)
                     { jjCheckNAddTwoStates(26, 27); }
                  break;
               case 27:
                  if (curChar != 34)
                     break;
                  if (kind > 189)
                     kind = 189;
                  { jjCheckNAddTwoStates(25, 28); }
                  break;
               case 28:
                  if ((0xfffffffb00000200ULL & l) == 0L)
                     break;
                  if (kind > 189)
                     kind = 189;
                  { jjCheckNAddTwoStates(25, 28); }
                  break;
               case 29:
                  if (curChar == 45)
                     { jjCheckNAddStates(17, 19); }
                  break;
               case 30:
                  if (curChar != 35)
                     break;
                  if (kind > 7)
                     kind = 7;
                  { jjCheckNAddStates(32, 34); }
                  break;
               case 31:
                  if ((0xffffffffffffdbffULL & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  { jjCheckNAddStates(32, 34); }
                  break;
               case 32:
                  if ((0x2400ULL & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 33:
                  if (curChar == 10 && kind > 7)
                     kind = 7;
                  break;
               case 34:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 36:
                  if (curChar != 45)
                     break;
                  if (kind > 8)
                     kind = 8;
                  { jjCheckNAddStates(35, 37); }
                  break;
               case 37:
                  if ((0xffffffffffffdbffULL & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  { jjCheckNAddStates(35, 37); }
                  break;
               case 38:
                  if ((0x2400ULL & l) != 0L && kind > 8)
                     kind = 8;
                  break;
               case 39:
                  if (curChar == 10 && kind > 8)
                     kind = 8;
                  break;
               case 40:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if (curChar == 47)
                     { jjAddStates(15, 16); }
                  break;
               case 42:
                  if (curChar == 33)
                     { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 43:
                  if ((0xfffffbffffffffffULL & l) != 0L)
                     { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 44:
                  if (curChar == 42)
                     { jjCheckNAddStates(38, 40); }
                  break;
               case 45:
                  if ((0xffff7bffffffffffULL & l) != 0L)
                     { jjCheckNAddTwoStates(46, 44); }
                  break;
               case 46:
                  if ((0xfffffbffffffffffULL & l) != 0L)
                     { jjCheckNAddTwoStates(46, 44); }
                  break;
               case 47:
                  if (curChar == 47 && kind > 9)
                     kind = 9;
                  break;
               case 48:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 49:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(50, 51); }
                  break;
               case 50:
                  if ((0xfffffbffffffffffULL & l) != 0L)
                     { jjCheckNAddTwoStates(50, 51); }
                  break;
               case 51:
                  if (curChar == 42)
                     { jjCheckNAddStates(41, 43); }
                  break;
               case 52:
                  if ((0xffff7bffffffffffULL & l) != 0L)
                     { jjCheckNAddTwoStates(53, 51); }
                  break;
               case 53:
                  if ((0xfffffbffffffffffULL & l) != 0L)
                     { jjCheckNAddTwoStates(53, 51); }
                  break;
               case 54:
                  if (curChar == 47 && kind > 10)
                     kind = 10;
                  break;
               case 55:
                  if ((0x3ff000000000000ULL & l) == 0L)
                     break;
                  if (kind > 165)
                     kind = 165;
                  { jjCheckNAddStates(0, 12); }
                  break;
               case 57:
                  if ((0x3ff000000000000ULL & l) == 0L)
                     break;
                  if (kind > 165)
                     kind = 165;
                  { jjCheckNAddTwoStates(56, 57); }
                  break;
               case 59:
                  if ((0x3ff000000000000ULL & l) == 0L)
                     break;
                  if (kind > 170)
                     kind = 170;
                  { jjCheckNAddStates(44, 47); }
                  break;
               case 60:
                  if (curChar == 46)
                     { jjCheckNAdd(61); }
                  break;
               case 61:
                  if ((0x3ff000000000000ULL & l) == 0L)
                     break;
                  if (kind > 170)
                     kind = 170;
                  { jjCheckNAddStates(48, 50); }
                  break;
               case 64:
                  if ((0x280000000000ULL & l) != 0L)
                     { jjCheckNAdd(65); }
                  break;
               case 65:
                  if ((0x3ff000000000000ULL & l) == 0L)
                     break;
                  if (kind > 170)
                     kind = 170;
                  { jjCheckNAddTwoStates(66, 65); }
                  break;
               case 68:
                  if ((0x3ff000000000000ULL & l) != 0L)
                     { jjCheckNAddStates(51, 53); }
                  break;
               case 69:
                  if (curChar == 35)
                     { jjCheckNAdd(70); }
                  break;
               case 70:
                  if ((0x3ff000000000000ULL & l) != 0L)
                     { jjCheckNAddStates(54, 56); }
                  break;
               case 71:
                  if (curChar == 46)
                     { jjCheckNAdd(72); }
                  break;
               case 72:
                  if ((0x3ff000000000000ULL & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 73:
                  if (curChar != 35)
                     break;
                  if (kind > 172)
                     kind = 172;
                  jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 75:
                  if ((0x280000000000ULL & l) != 0L)
                     { jjCheckNAdd(76); }
                  break;
               case 76:
                  if ((0x3ff000000000000ULL & l) == 0L)
                     break;
                  if (kind > 172)
                     kind = 172;
                  { jjCheckNAddTwoStates(77, 76); }
                  break;
               case 78:
                  if ((0x3ff000000000000ULL & l) != 0L)
                     { jjCheckNAddStates(57, 59); }
                  break;
               case 79:
                  if ((0x3ff000000000000ULL & l) != 0L)
                     { jjCheckNAddStates(60, 63); }
                  break;
               case 80:
                  if (curChar == 39)
                     { jjAddStates(13, 14); }
                  break;
               case 81:
                  if ((0xffffffff00000200ULL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 82:
                  if (curChar == 39 && kind > 169)
                     kind = 169;
                  break;
               case 83:
                  if (curChar == 40)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 84:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if ((0xfffffffb00000200ULL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 86:
                  if (curChar == 39 && kind > 190)
                     kind = 190;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         unsigned long long l = 1ULL << (curChar & 077);
         (void)l;
         do
         {
            switch(jjstateSet[--i])
            {
               case 11:
                  if ((0x7fffffe07fffffeULL & l) != 0L)
                  {
                     if (kind > 171)
                        kind = 171;
                     { jjCheckNAdd(17); }
                  }
                  else if (curChar == 96)
                     { jjCheckNAddTwoStates(25, 28); }
                  else if (curChar == 92)
                     { jjCheckNAddTwoStates(15, 16); }
                  if ((0x7fffffe07fffffeULL & l) != 0L)
                  {
                     if (kind > 167)
                        kind = 167;
                     { jjCheckNAddTwoStates(12, 13); }
                  }
                  if ((0x100801401008014ULL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 20;
                  else if ((0x280000ULL & l) != 0L)
                     { jjCheckNAddTwoStates(18, 19); }
                  break;
               case 4:
                  if (kind > 6)
                     kind = 6;
                  { jjAddStates(20, 24); }
                  break;
               case 9:
                  if ((0x7fffffffffffffffULL & l) != 0L)
                     { jjAddStates(64, 65); }
                  break;
               case 12:
                  if (curChar == 95)
                     { jjCheckNAddTwoStates(12, 13); }
                  break;
               case 13:
                  if ((0x7fffffe07fffffeULL & l) == 0L)
                     break;
                  if (kind > 167)
                     kind = 167;
                  { jjCheckNAddTwoStates(12, 13); }
                  break;
               case 14:
                  if (curChar == 92)
                     { jjCheckNAddTwoStates(15, 16); }
                  break;
               case 15:
                  if ((0x7fffffffffffffffULL & l) != 0L)
                     { jjCheckNAddTwoStates(15, 16); }
                  break;
               case 16:
                  if (curChar == 92 && kind > 168)
                     kind = 168;
                  break;
               case 17:
                  if ((0x7fffffe07fffffeULL & l) == 0L)
                     break;
                  if (kind > 171)
                     kind = 171;
                  { jjCheckNAdd(17); }
                  break;
               case 18:
                  if ((0x280000ULL & l) != 0L)
                     { jjCheckNAddTwoStates(18, 19); }
                  break;
               case 19:
                  if ((0x100801401008014ULL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 21:
                  if ((0x7fffffe07fffffeULL & l) != 0L)
                     { jjCheckNAddStates(29, 31); }
                  break;
               case 22:
                  if (curChar == 95)
                     { jjCheckNAddTwoStates(22, 21); }
                  break;
               case 24:
                  if (curChar == 96)
                     { jjCheckNAddTwoStates(25, 28); }
                  break;
               case 26:
                  if ((0x7fffffffffffffffULL & l) != 0L)
                     { jjAddStates(66, 67); }
                  break;
               case 28:
                  if ((0x7fffffffffffffffULL & l) == 0L)
                     break;
                  if (kind > 189)
                     kind = 189;
                  { jjCheckNAddTwoStates(25, 28); }
                  break;
               case 31:
                  if (kind > 7)
                     kind = 7;
                  { jjAddStates(32, 34); }
                  break;
               case 37:
                  if (kind > 8)
                     kind = 8;
                  { jjAddStates(35, 37); }
                  break;
               case 43:
                  { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 45:
               case 46:
                  { jjCheckNAddTwoStates(46, 44); }
                  break;
               case 50:
                  { jjCheckNAddTwoStates(50, 51); }
                  break;
               case 52:
               case 53:
                  { jjCheckNAddTwoStates(53, 51); }
                  break;
               case 56:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 58:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 62:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if ((0x2000000020ULL & l) != 0L)
                     { jjCheckNAddTwoStates(64, 65); }
                  break;
               case 66:
                  if (curChar == 95)
                     { jjCheckNAdd(65); }
                  break;
               case 67:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if ((0x7fffffe07fffffeULL & l) != 0L)
                     { jjCheckNAddStates(54, 56); }
                  break;
               case 72:
                  if ((0x7fffffe07fffffeULL & l) != 0L)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 74:
                  if ((0x2000000020ULL & l) != 0L)
                     { jjCheckNAddTwoStates(75, 76); }
                  break;
               case 77:
                  if (curChar == 95)
                     { jjCheckNAdd(76); }
                  break;
               case 81:
                  if ((0x7fffffffffffffffULL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 85:
                  if ((0x7fffffffffffffffULL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         unsigned long long l1 = 1ULL << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         unsigned long long l2 = 1ULL << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 4:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjAddStates(20, 24); }
                  break;
               case 9:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     { jjAddStates(64, 65); }
                  break;
               case 15:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     { jjAddStates(27, 28); }
                  break;
               case 26:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     { jjAddStates(66, 67); }
                  break;
               case 28:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 189)
                     kind = 189;
                  { jjAddStates(68, 69); }
                  break;
               case 31:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 7)
                     kind = 7;
                  { jjAddStates(32, 34); }
                  break;
               case 37:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 8)
                     kind = 8;
                  { jjAddStates(35, 37); }
                  break;
               case 43:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 45:
               case 46:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(46, 44); }
                  break;
               case 50:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(50, 51); }
                  break;
               case 52:
               case 53:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(53, 51); }
                  break;
               case 81:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 85:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 || l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt), (jjnewStateCnt = startsAt), (i == (startsAt = 87 - startsAt)))
         break;
      if (input_stream->endOfInput()) { break; }
      curChar = input_stream->readChar();
   }
   if (jjmatchedPos > strPos)
      return curPos;
   int toRet = MAX(curPos, seenUpto);
   if (curPos < toRet)
      for (i = toRet - MIN(curPos, seenUpto); i-- > 0;)
        { assert(!input_stream->endOfInput());
           curChar = input_stream->readChar(); }
   if (jjmatchedPos < strPos)
   {
      jjmatchedKind = strKind;
      jjmatchedPos = strPos;
   }
   else if (jjmatchedPos == strPos && jjmatchedKind > strKind)
      jjmatchedKind = strKind;
   return toRet;
}
References curChar, input_stream, jjAddStates, jjCanMove_0(), jjCanMove_1(), jjCheckNAdd, jjCheckNAddStates, jjCheckNAddTwoStates, jjmatchedKind, jjmatchedPos, jjnewStateCnt, jjround, jjstateSet, MAX, MIN, and ReInitRounds().
Referenced by jjMoveStringLiteralDfa0_0(), jjMoveStringLiteralDfa10_0(), jjMoveStringLiteralDfa11_0(), jjMoveStringLiteralDfa12_0(), jjMoveStringLiteralDfa13_0(), jjMoveStringLiteralDfa14_0(), jjMoveStringLiteralDfa15_0(), jjMoveStringLiteralDfa16_0(), jjMoveStringLiteralDfa17_0(), jjMoveStringLiteralDfa1_0(), jjMoveStringLiteralDfa2_0(), jjMoveStringLiteralDfa3_0(), jjMoveStringLiteralDfa4_0(), jjMoveStringLiteralDfa5_0(), jjMoveStringLiteralDfa6_0(), jjMoveStringLiteralDfa7_0(), jjMoveStringLiteralDfa8_0(), and jjMoveStringLiteralDfa9_0().
jjMoveNfa_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveNfa_0 (int startState, int curPos)
jjMoveStringLiteralDfa0_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa0_0 ()
Definition at line 458 of file VhdlParserTokenManager.cc.
                                                       {
   switch(curChar)
   {
      case 9:
         jjmatchedKind = 2;
         return jjMoveNfa_0(11, 0);
      case 10:
         jjmatchedKind = 3;
         return jjMoveNfa_0(11, 0);
      case 13:
         jjmatchedKind = 4;
         return jjMoveNfa_0(11, 0);
      case 32:
         jjmatchedKind = 1;
         return jjMoveNfa_0(11, 0);
      case 38:
         jjmatchedKind = 126;
         return jjMoveNfa_0(11, 0);
      case 39:
         jjmatchedKind = 127;
         return jjMoveNfa_0(11, 0);
      case 40:
         jjmatchedKind = 128;
         return jjMoveNfa_0(11, 0);
      case 41:
         jjmatchedKind = 129;
         return jjMoveNfa_0(11, 0);
      case 42:
         jjmatchedKind = 131;
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x0ULL, 0x4ULL);
      case 43:
         jjmatchedKind = 132;
         return jjMoveNfa_0(11, 0);
      case 44:
         jjmatchedKind = 134;
         return jjMoveNfa_0(11, 0);
      case 45:
         jjmatchedKind = 133;
         return jjMoveNfa_0(11, 0);
      case 46:
         jjmatchedKind = 157;
         return jjMoveNfa_0(11, 0);
      case 47:
         jjmatchedKind = 158;
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x0ULL, 0x8000ULL);
      case 58:
         jjmatchedKind = 136;
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x0ULL, 0x80ULL);
      case 59:
         jjmatchedKind = 137;
         return jjMoveNfa_0(11, 0);
      case 60:
         jjmatchedKind = 140;
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x0ULL, 0x60400ULL);
      case 61:
         jjmatchedKind = 142;
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x0ULL, 0x10000ULL);
      case 62:
         jjmatchedKind = 141;
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x0ULL, 0x80800ULL);
      case 63:
         jjmatchedKind = 155;
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x0ULL, 0x7f00000ULL);
      case 64:
         jjmatchedKind = 159;
         return jjMoveNfa_0(11, 0);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x7ff800ULL, 0x0ULL, 0x0ULL);
      case 66:
         return jjMoveStringLiteralDfa1_0(0xf800000ULL, 0x0ULL, 0x0ULL);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x3f0000000ULL, 0x0ULL, 0x0ULL);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x1c00000000ULL, 0x0ULL, 0x0ULL);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x3e000000000ULL, 0x0ULL, 0x0ULL);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x7c0000000000ULL, 0x0ULL, 0x0ULL);
      case 71:
         return jjMoveStringLiteralDfa1_0(0x7800000000000ULL, 0x0ULL, 0x0ULL);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x1f8000000000000ULL, 0x0ULL, 0x0ULL);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x3e00000000000000ULL, 0x0ULL, 0x0ULL);
      case 77:
         return jjMoveStringLiteralDfa1_0(0xc000000000000000ULL, 0x0ULL, 0x0ULL);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x3fULL, 0x0ULL);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0xfc0ULL, 0x0ULL);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x1ff000ULL, 0x0ULL);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x1ffe00000ULL, 0x0ULL);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0xffe00000000ULL, 0x0ULL);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0xf00000000000ULL, 0x0ULL);
      case 85:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0xf000000000000ULL, 0x0ULL);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0xf0000000000000ULL, 0x0ULL);
      case 87:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0xf00000000000000ULL, 0x0ULL);
      case 88:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x3000000000000000ULL, 0x0ULL);
      case 91:
         jjmatchedKind = 161;
         return jjMoveNfa_0(11, 0);
      case 93:
         jjmatchedKind = 162;
         return jjMoveNfa_0(11, 0);
      case 94:
         jjmatchedKind = 160;
         return jjMoveNfa_0(11, 0);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x7ff800ULL, 0x0ULL, 0x0ULL);
      case 98:
         return jjMoveStringLiteralDfa1_0(0xf800000ULL, 0x0ULL, 0x0ULL);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x3f0000000ULL, 0x0ULL, 0x0ULL);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x1c00000000ULL, 0x0ULL, 0x0ULL);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x3e000000000ULL, 0x0ULL, 0x0ULL);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x7c0000000000ULL, 0x0ULL, 0x0ULL);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x7800000000000ULL, 0x0ULL, 0x0ULL);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1f8000000000000ULL, 0x0ULL, 0x0ULL);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x3e00000000000000ULL, 0x0ULL, 0x0ULL);
      case 109:
         return jjMoveStringLiteralDfa1_0(0xc000000000000000ULL, 0x0ULL, 0x0ULL);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x3fULL, 0x0ULL);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0xfc0ULL, 0x0ULL);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x1ff000ULL, 0x0ULL);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x1ffe00000ULL, 0x0ULL);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0xffe00000000ULL, 0x0ULL);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0xf00000000000ULL, 0x0ULL);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0xf000000000000ULL, 0x0ULL);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0xf0000000000000ULL, 0x0ULL);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0xf00000000000000ULL, 0x0ULL);
      case 120:
         return jjMoveStringLiteralDfa1_0(0x0ULL, 0x3000000000000000ULL, 0x0ULL);
      case 123:
         jjmatchedKind = 163;
         return jjMoveNfa_0(11, 0);
      case 124:
         jjmatchedKind = 156;
         return jjMoveNfa_0(11, 0);
      case 125:
         jjmatchedKind = 164;
         return jjMoveNfa_0(11, 0);
      default :
         return jjMoveNfa_0(11, 0);
   }
}
References curChar, jjmatchedKind, jjMoveNfa_0(), and jjMoveStringLiteralDfa1_0().
Referenced by getNextToken().
jjMoveStringLiteralDfa0_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa0_0 ()
jjMoveStringLiteralDfa10_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa10_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 2460 of file VhdlParserTokenManager.cc.
                                                                                                                                                                {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 9);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 9);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa11_0(active0, 0x40000000ULL, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa11_0(active0, 0x220000ULL, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x8000000ULL);
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x40000000ULL, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa11_0(active0, 0x220000ULL, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x8000000ULL);
      default :
         break;
   }
   return jjMoveNfa_0(11, 10);
}
References curChar, input_stream, jjMoveNfa_0(), and jjMoveStringLiteralDfa11_0().
Referenced by jjMoveStringLiteralDfa9_0().
jjMoveStringLiteralDfa10_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa10_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa11_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa11_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 2487 of file VhdlParserTokenManager.cc.
                                                                                                                                                                {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 10);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 10);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000ULL, active1, 0x8000000ULL);
      case 69:
         if ((active0 & 0x20000ULL) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 11;
         }
         break;
      case 79:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000000ULL, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000ULL, active1, 0x8000000ULL);
      case 101:
         if ((active0 & 0x20000ULL) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 11;
         }
         break;
      case 111:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000000ULL, active1, 0L);
      default :
         break;
   }
   return jjMoveNfa_0(11, 11);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, jjMoveNfa_0(), and jjMoveStringLiteralDfa12_0().
Referenced by jjMoveStringLiteralDfa10_0().
jjMoveStringLiteralDfa11_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa11_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa12_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa12_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 2524 of file VhdlParserTokenManager.cc.
                                                                                                                                                                {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 11);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 11);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x40000000ULL) != 0L)
         {
            jjmatchedKind = 30;
            jjmatchedPos = 12;
         }
         return jjMoveStringLiteralDfa13_0(active0, 0x200000ULL, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa13_0(active0, 0L, active1, 0x8000000ULL);
      case 110:
         if ((active0 & 0x40000000ULL) != 0L)
         {
            jjmatchedKind = 30;
            jjmatchedPos = 12;
         }
         return jjMoveStringLiteralDfa13_0(active0, 0x200000ULL, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa13_0(active0, 0L, active1, 0x8000000ULL);
      default :
         break;
   }
   return jjMoveNfa_0(11, 12);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, jjMoveNfa_0(), and jjMoveStringLiteralDfa13_0().
Referenced by jjMoveStringLiteralDfa11_0().
jjMoveStringLiteralDfa12_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa12_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa13_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa13_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 2557 of file VhdlParserTokenManager.cc.
                                                                                                                                                                {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 12);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 12);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa14_0(active0, 0L, active1, 0x8000000ULL);
      case 84:
         return jjMoveStringLiteralDfa14_0(active0, 0x200000ULL, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa14_0(active0, 0L, active1, 0x8000000ULL);
      case 116:
         return jjMoveStringLiteralDfa14_0(active0, 0x200000ULL, active1, 0L);
      default :
         break;
   }
   return jjMoveNfa_0(11, 13);
}
References curChar, input_stream, jjMoveNfa_0(), and jjMoveStringLiteralDfa14_0().
Referenced by jjMoveStringLiteralDfa12_0().
jjMoveStringLiteralDfa13_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa13_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa14_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa14_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 2580 of file VhdlParserTokenManager.cc.
                                                                                                                                                                {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 13);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 13);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa15_0(active0, 0x200000ULL, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa15_0(active0, 0L, active1, 0x8000000ULL);
      case 101:
         return jjMoveStringLiteralDfa15_0(active0, 0x200000ULL, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa15_0(active0, 0L, active1, 0x8000000ULL);
      default :
         break;
   }
   return jjMoveNfa_0(11, 14);
}
References curChar, input_stream, jjMoveNfa_0(), and jjMoveStringLiteralDfa15_0().
Referenced by jjMoveStringLiteralDfa13_0().
jjMoveStringLiteralDfa14_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa14_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa15_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa15_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 2603 of file VhdlParserTokenManager.cc.
                                                                                                                                                                {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 14);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 14);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x200000ULL) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 15;
         }
         break;
      case 84:
         return jjMoveStringLiteralDfa16_0(active0, 0L, active1, 0x8000000ULL);
      case 101:
         if ((active0 & 0x200000ULL) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 15;
         }
         break;
      case 116:
         return jjMoveStringLiteralDfa16_0(active0, 0L, active1, 0x8000000ULL);
      default :
         break;
   }
   return jjMoveNfa_0(11, 15);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, jjMoveNfa_0(), and jjMoveStringLiteralDfa16_0().
Referenced by jjMoveStringLiteralDfa14_0().
jjMoveStringLiteralDfa15_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa15_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa16_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa16_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 2636 of file VhdlParserTokenManager.cc.
                                                                                                                                                                {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 15);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 15);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa17_0(active1, 0x8000000ULL);
      case 101:
         return jjMoveStringLiteralDfa17_0(active1, 0x8000000ULL);
      default :
         break;
   }
   return jjMoveNfa_0(11, 16);
}
References curChar, input_stream, jjMoveNfa_0(), and jjMoveStringLiteralDfa17_0().
Referenced by jjMoveStringLiteralDfa15_0().
jjMoveStringLiteralDfa16_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa16_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa17_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa17_0 (unsigned long long old1, unsigned long long active1)
Definition at line 2655 of file VhdlParserTokenManager.cc.
                                                                                                           {
   if (((active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 16);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 16);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 69:
         if ((active1 & 0x8000000ULL) != 0L)
         {
            jjmatchedKind = 91;
            jjmatchedPos = 17;
         }
         break;
      case 101:
         if ((active1 & 0x8000000ULL) != 0L)
         {
            jjmatchedKind = 91;
            jjmatchedPos = 17;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(11, 17);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, and jjMoveNfa_0().
Referenced by jjMoveStringLiteralDfa16_0().
jjMoveStringLiteralDfa17_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa17_0 (unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa1_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa1_0 (unsigned long long active0, unsigned long long active1, unsigned long long active2)
Definition at line 627 of file VhdlParserTokenManager.cc.
                                                                                                                                         {
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 0);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 42:
         if ((active2 & 0x4ULL) != 0L)
         {
            jjmatchedKind = 130;
            jjmatchedPos = 1;
         }
         break;
      case 47:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x4000000ULL);
      case 60:
         if ((active2 & 0x40000ULL) != 0L)
         {
            jjmatchedKind = 146;
            jjmatchedPos = 1;
         }
         else if ((active2 & 0x1000000ULL) != 0L)
         {
            jjmatchedKind = 152;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x400000ULL);
      case 61:
         if ((active2 & 0x80ULL) != 0L)
         {
            jjmatchedKind = 135;
            jjmatchedPos = 1;
         }
         else if ((active2 & 0x400ULL) != 0L)
         {
            jjmatchedKind = 138;
            jjmatchedPos = 1;
         }
         else if ((active2 & 0x800ULL) != 0L)
         {
            jjmatchedKind = 139;
            jjmatchedPos = 1;
         }
         else if ((active2 & 0x8000ULL) != 0L)
         {
            jjmatchedKind = 143;
            jjmatchedPos = 1;
         }
         else if ((active2 & 0x2000000ULL) != 0L)
         {
            jjmatchedKind = 153;
            jjmatchedPos = 1;
         }
         break;
      case 62:
         if ((active2 & 0x10000ULL) != 0L)
         {
            jjmatchedKind = 144;
            jjmatchedPos = 1;
         }
         else if ((active2 & 0x20000ULL) != 0L)
         {
            jjmatchedKind = 145;
            jjmatchedPos = 1;
         }
         else if ((active2 & 0x80000ULL) != 0L)
         {
            jjmatchedKind = 147;
            jjmatchedPos = 1;
         }
         else if ((active2 & 0x800000ULL) != 0L)
         {
            jjmatchedKind = 151;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x200000ULL);
      case 63:
         if ((active2 & 0x100000ULL) != 0L)
         {
            jjmatchedKind = 148;
            jjmatchedPos = 1;
         }
         break;
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x4200040020000000ULL, active1, 0x110000000203001ULL, active2, 0L);
      case 66:
         return jjMoveStringLiteralDfa2_0(active0, 0x800ULL, active1, 0L, active2, 0L);
      case 67:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000ULL, active1, 0L, active2, 0L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x1800400800000ULL, active1, 0xf3fc00006ULL, active2, 0L);
      case 70:
         if ((active0 & 0x8000000000000ULL) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x40ULL) != 0L)
         {
            jjmatchedKind = 70;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000ULL, active1, 0L, active2, 0L);
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x600102000000000ULL, active2, 0L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x1c00080800000000ULL, active1, 0x800001000000000ULL, active2, 0L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x600100c000ULL, active1, 0xc000000000ULL, active2, 0L);
      case 77:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000000000ULL, active1, 0x20000000000000ULL, active2, 0L);
      case 78:
         if ((active0 & 0x20000000000000ULL) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x80ULL) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0xc0018000010000ULL, active1, 0x2007000000000000ULL, active2, 0L);
      case 79:
         if ((active1 & 0x200000000000ULL) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0xa0003013d2000000ULL, active1, 0x10000000c000c018ULL, active2, 0L);
      case 80:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40000000000100ULL, active2, 0L);
      case 82:
         if ((active1 & 0x200ULL) != 0L)
         {
            jjmatchedKind = 73;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000060000ULL, active1, 0x4300000f0000ULL, active2, 0L);
      case 83:
         if ((active0 & 0x100000000000000ULL) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x380000ULL, active1, 0x8000000000000ULL, active2, 0L);
      case 84:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000ULL, active1, 0x40000000400ULL, active2, 0L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x440000c000000ULL, active1, 0x80080000100820ULL, active2, 0L);
      case 88:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000ULL, active1, 0L, active2, 0L);
      case 89:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800000000000ULL, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x4200040020000000ULL, active1, 0x110000000203001ULL, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x800ULL, active1, 0L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000ULL, active1, 0L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x1800400800000ULL, active1, 0xf3fc00006ULL, active2, 0L);
      case 102:
         if ((active0 & 0x8000000000000ULL) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x40ULL) != 0L)
         {
            jjmatchedKind = 70;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000ULL, active1, 0L, active2, 0L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x600102000000000ULL, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x1c00080800000000ULL, active1, 0x800001000000000ULL, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x600100c000ULL, active1, 0xc000000000ULL, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000000000ULL, active1, 0x20000000000000ULL, active2, 0L);
      case 110:
         if ((active0 & 0x20000000000000ULL) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x80ULL) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0xc0018000010000ULL, active1, 0x2007000000000000ULL, active2, 0L);
      case 111:
         if ((active1 & 0x200000000000ULL) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0xa0003013d2000000ULL, active1, 0x10000000c000c018ULL, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40000000000100ULL, active2, 0L);
      case 114:
         if ((active1 & 0x200ULL) != 0L)
         {
            jjmatchedKind = 73;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000060000ULL, active1, 0x4300000f0000ULL, active2, 0L);
      case 115:
         if ((active0 & 0x100000000000000ULL) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x380000ULL, active1, 0x8000000000000ULL, active2, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000ULL, active1, 0x40000000400ULL, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x440000c000000ULL, active1, 0x80080000100820ULL, active2, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000ULL, active1, 0L, active2, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800000000000ULL, active2, 0L);
      default :
         break;
   }
   return jjMoveNfa_0(11, 1);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, jjMoveNfa_0(), and jjMoveStringLiteralDfa2_0().
Referenced by jjMoveStringLiteralDfa0_0().
jjMoveStringLiteralDfa1_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa1_0 (unsigned long long active0, unsigned long long active1, unsigned long long active2)
jjMoveStringLiteralDfa2_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa2_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1, unsigned long long old2, unsigned long long active2)
Definition at line 859 of file VhdlParserTokenManager.cc.
                                                                                                                                                                                                                    {
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjMoveNfa_0(11, 1);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 1);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 61:
         if ((active2 & 0x200000ULL) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 2;
         }
         else if ((active2 & 0x400000ULL) != 0L)
         {
            jjmatchedKind = 150;
            jjmatchedPos = 2;
         }
         else if ((active2 & 0x4000000ULL) != 0L)
         {
            jjmatchedKind = 154;
            jjmatchedPos = 2;
         }
         break;
      case 65:
         if ((active1 & 0x4000000000ULL) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x10000000000ULL) != 0L)
         {
            jjmatchedKind = 104;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000ULL, active1, 0x1402000000000ULL, active2, 0L);
      case 66:
         return jjMoveStringLiteralDfa3_0(active0, 0x600000000000000ULL, active1, 0x80000000000ULL, active2, 0L);
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x21000ULL, active1, 0x401000ULL, active2, 0L);
      case 68:
         if ((active0 & 0x10000ULL) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x8000000000ULL) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x8000000000000000ULL) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000ULL, active1, 0L, active2, 0L);
      case 69:
         if ((active1 & 0x8000000000000ULL) != 0L)
         {
            jjmatchedKind = 115;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000000ULL, active1, 0x200100000000100ULL, active2, 0L);
      case 70:
         return jjMoveStringLiteralDfa3_0(active0, 0x404000000ULL, active1, 0L, active2, 0L);
      case 71:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000ULL, active1, 0x1000800000ULL, active2, 0L);
      case 72:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x400ULL, active2, 0L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x60000004000ULL, active1, 0x502000000000000ULL, active2, 0L);
      case 74:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x1000000ULL, active2, 0L);
      case 76:
         if ((active0 & 0x8000ULL) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x40000000ULL) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x8000000000ULL) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x20000000000ULL) != 0L)
         {
            jjmatchedKind = 105;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000ULL, active1, 0x202000020ULL, active2, 0L);
      case 77:
         if ((active1 & 0x10000000ULL) != 0L)
         {
            jjmatchedKind = 92;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000ULL, active1, 0L, active2, 0L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x801c001c0000000ULL, active1, 0x80000000200001ULL, active2, 0L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x2082000001000000ULL, active1, 0x20200000000f0000ULL, active2, 0L);
      case 80:
         if ((active0 & 0x4000000000000000ULL) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000000ULL, active1, 0x800020000000ULL, active2, 0L);
      case 81:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x400000000ULL, active2, 0L);
      case 82:
         if ((active0 & 0x100000000000ULL) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x8ULL) != 0L)
         {
            jjmatchedKind = 67;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x80000000ULL) != 0L)
         {
            jjmatchedKind = 95;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x1000000000000000ULL) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x200000040000ULL, active1, 0x50040000106000ULL, active2, 0L);
      case 83:
         if ((active0 & 0x800ULL) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x8000000ULL) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x6820380000ULL, active1, 0xc008000ULL, active2, 0L);
      case 84:
         if ((active1 & 0x10ULL) != 0L)
         {
            jjmatchedKind = 68;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x800ULL) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x1000010000402000ULL, active1, 0x804000100000000ULL, active2, 0L);
      case 86:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000ULL, active1, 0x800000000ULL, active2, 0L);
      case 87:
         if ((active1 & 0x2ULL) != 0L)
         {
            jjmatchedKind = 65;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000ULL, active1, 0L, active2, 0L);
      case 88:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4ULL, active2, 0L);
      case 97:
         if ((active1 & 0x4000000000ULL) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x10000000000ULL) != 0L)
         {
            jjmatchedKind = 104;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000ULL, active1, 0x1402000000000ULL, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x600000000000000ULL, active1, 0x80000000000ULL, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x21000ULL, active1, 0x401000ULL, active2, 0L);
      case 100:
         if ((active0 & 0x10000ULL) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x8000000000ULL) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x8000000000000000ULL) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000ULL, active1, 0L, active2, 0L);
      case 101:
         if ((active1 & 0x8000000000000ULL) != 0L)
         {
            jjmatchedKind = 115;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000000ULL, active1, 0x200100000000100ULL, active2, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x404000000ULL, active1, 0L, active2, 0L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000ULL, active1, 0x1000800000ULL, active2, 0L);
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x400ULL, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x60000004000ULL, active1, 0x502000000000000ULL, active2, 0L);
      case 106:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x1000000ULL, active2, 0L);
      case 108:
         if ((active0 & 0x8000ULL) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x40000000ULL) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x8000000000ULL) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x20000000000ULL) != 0L)
         {
            jjmatchedKind = 105;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000ULL, active1, 0x202000020ULL, active2, 0L);
      case 109:
         if ((active1 & 0x10000000ULL) != 0L)
         {
            jjmatchedKind = 92;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000ULL, active1, 0L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x801c001c0000000ULL, active1, 0x80000000200001ULL, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x2082000001000000ULL, active1, 0x20200000000f0000ULL, active2, 0L);
      case 112:
         if ((active0 & 0x4000000000000000ULL) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000000ULL, active1, 0x800020000000ULL, active2, 0L);
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x400000000ULL, active2, 0L);
      case 114:
         if ((active0 & 0x100000000000ULL) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x8ULL) != 0L)
         {
            jjmatchedKind = 67;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x80000000ULL) != 0L)
         {
            jjmatchedKind = 95;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x1000000000000000ULL) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x200000040000ULL, active1, 0x50040000106000ULL, active2, 0L);
      case 115:
         if ((active0 & 0x800ULL) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x8000000ULL) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x6820380000ULL, active1, 0xc008000ULL, active2, 0L);
      case 116:
         if ((active1 & 0x10ULL) != 0L)
         {
            jjmatchedKind = 68;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x800ULL) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x1000010000402000ULL, active1, 0x804000100000000ULL, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000ULL, active1, 0x800000000ULL, active2, 0L);
      case 119:
         if ((active1 & 0x2ULL) != 0L)
         {
            jjmatchedKind = 65;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000ULL, active1, 0L, active2, 0L);
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4ULL, active2, 0L);
      default :
         break;
   }
   return jjMoveNfa_0(11, 2);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, jjMoveNfa_0(), and jjMoveStringLiteralDfa3_0().
Referenced by jjMoveStringLiteralDfa1_0().
jjMoveStringLiteralDfa2_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa2_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1, unsigned long long old2, unsigned long long active2)
jjMoveStringLiteralDfa3_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa3_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1, unsigned long long old2, unsigned long long active2)
Definition at line 1189 of file VhdlParserTokenManager.cc.
                                                                                                                                                                                                                    {
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjMoveNfa_0(11, 2);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 2);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x400044000ULL, active1, 0x2000ULL);
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0x600801000000ULL, active1, 0x30000ULL);
      case 68:
         if ((active1 & 0x1ULL) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x20000000000000ULL);
      case 69:
         if ((active0 & 0x20000000ULL) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x2000000000ULL) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x80000000000ULL) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x100000ULL) != 0L)
         {
            jjmatchedKind = 84;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x800000000000ULL) != 0L)
         {
            jjmatchedKind = 111;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x1201800200083000ULL, active1, 0xa03000400ULL);
      case 70:
         return jjMoveStringLiteralDfa4_0(active0, 0x44000000ULL, active1, 0x1000000000000ULL);
      case 71:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x200000ULL);
      case 72:
         if ((active1 & 0x800000000000000ULL) != 0L)
         {
            jjmatchedKind = 123;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x20000ULL, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x14000800000ULL, active1, 0x94000000800000ULL);
      case 75:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000000ULL, active1, 0x1000ULL);
      case 76:
         if ((active1 & 0x20ULL) != 0L)
         {
            jjmatchedKind = 69;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x400000000000000ULL);
      case 78:
         if ((active1 & 0x100ULL) != 0L)
         {
            jjmatchedKind = 72;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x100000000000ULL) != 0L)
         {
            jjmatchedKind = 108;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x200000000000000ULL) != 0L)
         {
            jjmatchedKind = 121;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000ULL, active1, 0x401000000000ULL);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x40040020400000ULL);
      case 80:
         if ((active0 & 0x2000000000000000ULL) != 0L)
         {
            jjmatchedKind = 61;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000ULL, active1, 0x40000ULL);
      case 82:
         if ((active1 & 0x2000000000000000ULL) != 0L)
         {
            jjmatchedKind = 125;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x444040000400000ULL, active1, 0x2000000000ULL);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000ULL, active1, 0L);
      case 84:
         if ((active0 & 0x20000000000ULL) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x4ULL) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x4000ULL) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x100000000000000ULL) != 0L)
         {
            jjmatchedKind = 120;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000ULL, active1, 0x208000c088000ULL);
      case 85:
         return jjMoveStringLiteralDfa4_0(active0, 0x92000000300000ULL, active1, 0x500000000ULL);
      case 89:
         if ((active0 & 0x2000000ULL) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 3;
         }
         break;
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x400044000ULL, active1, 0x2000ULL);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x600801000000ULL, active1, 0x30000ULL);
      case 100:
         if ((active1 & 0x1ULL) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x20000000000000ULL);
      case 101:
         if ((active0 & 0x20000000ULL) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x2000000000ULL) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x80000000000ULL) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x100000ULL) != 0L)
         {
            jjmatchedKind = 84;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x800000000000ULL) != 0L)
         {
            jjmatchedKind = 111;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x1201800200083000ULL, active1, 0xa03000400ULL);
      case 102:
         return jjMoveStringLiteralDfa4_0(active0, 0x44000000ULL, active1, 0x1000000000000ULL);
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x200000ULL);
      case 104:
         if ((active1 & 0x800000000000000ULL) != 0L)
         {
            jjmatchedKind = 123;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x20000ULL, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x14000800000ULL, active1, 0x94000000800000ULL);
      case 107:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000000ULL, active1, 0x1000ULL);
      case 108:
         if ((active1 & 0x20ULL) != 0L)
         {
            jjmatchedKind = 69;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x400000000000000ULL);
      case 110:
         if ((active1 & 0x100ULL) != 0L)
         {
            jjmatchedKind = 72;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x100000000000ULL) != 0L)
         {
            jjmatchedKind = 108;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x200000000000000ULL) != 0L)
         {
            jjmatchedKind = 121;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000ULL, active1, 0x401000000000ULL);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x40040020400000ULL);
      case 112:
         if ((active0 & 0x2000000000000000ULL) != 0L)
         {
            jjmatchedKind = 61;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000ULL, active1, 0x40000ULL);
      case 114:
         if ((active1 & 0x2000000000000000ULL) != 0L)
         {
            jjmatchedKind = 125;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x444040000400000ULL, active1, 0x2000000000ULL);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000ULL, active1, 0L);
      case 116:
         if ((active0 & 0x20000000000ULL) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x4ULL) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x4000ULL) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x100000000000000ULL) != 0L)
         {
            jjmatchedKind = 120;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000ULL, active1, 0x208000c088000ULL);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x92000000300000ULL, active1, 0x500000000ULL);
      case 121:
         if ((active0 & 0x2000000ULL) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 3;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(11, 3);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, jjMoveNfa_0(), and jjMoveStringLiteralDfa4_0().
Referenced by jjMoveStringLiteralDfa2_0().
jjMoveStringLiteralDfa3_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa3_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1, unsigned long long old2, unsigned long long active2)
jjMoveStringLiteralDfa4_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa4_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 1456 of file VhdlParserTokenManager.cc.
                                                                                                                                                               {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 3);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 3);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0xc00000000000000ULL, active1, 0x10001002001000ULL);
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x201000000ULL);
      case 68:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000ULL, active1, 0L);
      case 69:
         if ((active0 & 0x200000000000ULL) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x200000ULL) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x20000000000000ULL) != 0L)
         {
            jjmatchedKind = 117;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x400000000000000ULL) != 0L)
         {
            jjmatchedKind = 122;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x104000000ULL, active1, 0x24000f0000ULL);
      case 70:
         if ((active0 & 0x4000000000ULL) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x1000000000000ULL);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x40420000ULL, active1, 0L);
      case 75:
         if ((active0 & 0x1000000ULL) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 4;
         }
         break;
      case 76:
         if ((active0 & 0x200000000000000ULL) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x4000000000000ULL) != 0L)
         {
            jjmatchedKind = 114;
            jjmatchedPos = 4;
         }
         break;
      case 77:
         return jjMoveStringLiteralDfa5_0(active0, 0x300000ULL, active1, 0x2000ULL);
      case 78:
         if ((active0 & 0x800000ULL) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000ULL, active1, 0x40000000000ULL);
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0x810000000ULL, active1, 0L);
      case 80:
         if ((active0 & 0x2000000000000ULL) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x40000000000000ULL) != 0L)
         {
            jjmatchedKind = 118;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x8000ULL);
      case 82:
         if ((active0 & 0x2000ULL) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x200000000ULL) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x1011800000080000ULL, active1, 0x92c400400ULL);
      case 83:
         if ((active0 & 0x4000ULL) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x2000000000000ULL) != 0L)
         {
            jjmatchedKind = 113;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x1000ULL, active1, 0x400000800000ULL);
      case 84:
         if ((active0 & 0x80000000000000ULL) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x80000000000000ULL) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x40411080000000ULL, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000ULL, active1, 0L);
      case 89:
         if ((active0 & 0x40000ULL) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x80000000000ULL);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0xc00000000000000ULL, active1, 0x10001002001000ULL);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x201000000ULL);
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000ULL, active1, 0L);
      case 101:
         if ((active0 & 0x200000000000ULL) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x200000ULL) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x20000000000000ULL) != 0L)
         {
            jjmatchedKind = 117;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x400000000000000ULL) != 0L)
         {
            jjmatchedKind = 122;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x104000000ULL, active1, 0x24000f0000ULL);
      case 102:
         if ((active0 & 0x4000000000ULL) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x1000000000000ULL);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x40420000ULL, active1, 0L);
      case 107:
         if ((active0 & 0x1000000ULL) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 4;
         }
         break;
      case 108:
         if ((active0 & 0x200000000000000ULL) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x4000000000000ULL) != 0L)
         {
            jjmatchedKind = 114;
            jjmatchedPos = 4;
         }
         break;
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x300000ULL, active1, 0x2000ULL);
      case 110:
         if ((active0 & 0x800000ULL) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000ULL, active1, 0x40000000000ULL);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x810000000ULL, active1, 0L);
      case 112:
         if ((active0 & 0x2000000000000ULL) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x40000000000000ULL) != 0L)
         {
            jjmatchedKind = 118;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x8000ULL);
      case 114:
         if ((active0 & 0x2000ULL) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x200000000ULL) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x1011800000080000ULL, active1, 0x92c400400ULL);
      case 115:
         if ((active0 & 0x4000ULL) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x2000000000000ULL) != 0L)
         {
            jjmatchedKind = 113;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x1000ULL, active1, 0x400000800000ULL);
      case 116:
         if ((active0 & 0x80000000000000ULL) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x80000000000000ULL) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x40411080000000ULL, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000ULL, active1, 0L);
      case 121:
         if ((active0 & 0x40000ULL) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x80000000000ULL);
      default :
         break;
   }
   return jjMoveNfa_0(11, 4);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, jjMoveNfa_0(), and jjMoveStringLiteralDfa5_0().
Referenced by jjMoveStringLiteralDfa3_0().
jjMoveStringLiteralDfa4_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa4_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa5_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa5_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 1719 of file VhdlParserTokenManager.cc.
                                                                                                                                                               {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 4);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 4);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000800080000000ULL, active1, 0L);
      case 66:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000ULL, active1, 0x10000000000000ULL);
      case 67:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x80000ULL);
      case 68:
         if ((active1 & 0x400000ULL) != 0L)
         {
            jjmatchedKind = 86;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x2000000000ULL) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x10000ULL);
      case 69:
         if ((active0 & 0x100000ULL) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x10000000000000ULL) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x4040000200000ULL, active1, 0x1000000002000ULL);
      case 71:
         if ((active1 & 0x40000000000ULL) != 0L)
         {
            jjmatchedKind = 106;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x800000040000000ULL, active1, 0x1000ULL);
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x41400000000000ULL, active1, 0x80c000000ULL);
      case 76:
         if ((active1 & 0x1000000000ULL) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000ULL, active1, 0L);
      case 78:
         if ((active1 & 0x100000000ULL) != 0L)
         {
            jjmatchedKind = 96;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x810000000ULL, active1, 0x400000000ULL);
      case 79:
         if ((active0 & 0x1000000000ULL) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x8000ULL);
      case 80:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x480000000000ULL);
      case 82:
         if ((active0 & 0x4000000ULL) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000000ULL, active1, 0x40000ULL);
      case 83:
         if ((active0 & 0x1000ULL) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x400ULL) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x2020000ULL);
      case 84:
         if ((active0 & 0x80000ULL) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x1000000ULL) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x20000000ULL) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x200000000ULL) != 0L)
         {
            jjmatchedKind = 97;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x20000ULL, active1, 0x800000ULL);
      case 88:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000ULL, active1, 0L);
      case 89:
         if ((active0 & 0x10000000000ULL) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 5;
         }
         break;
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000800080000000ULL, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000ULL, active1, 0x10000000000000ULL);
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x80000ULL);
      case 100:
         if ((active1 & 0x400000ULL) != 0L)
         {
            jjmatchedKind = 86;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x2000000000ULL) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x10000ULL);
      case 101:
         if ((active0 & 0x100000ULL) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x10000000000000ULL) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x4040000200000ULL, active1, 0x1000000002000ULL);
      case 103:
         if ((active1 & 0x40000000000ULL) != 0L)
         {
            jjmatchedKind = 106;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x800000040000000ULL, active1, 0x1000ULL);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x41400000000000ULL, active1, 0x80c000000ULL);
      case 108:
         if ((active1 & 0x1000000000ULL) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000ULL, active1, 0L);
      case 110:
         if ((active1 & 0x100000000ULL) != 0L)
         {
            jjmatchedKind = 96;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x810000000ULL, active1, 0x400000000ULL);
      case 111:
         if ((active0 & 0x1000000000ULL) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x8000ULL);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x480000000000ULL);
      case 114:
         if ((active0 & 0x4000000ULL) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000000ULL, active1, 0x40000ULL);
      case 115:
         if ((active0 & 0x1000ULL) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x400ULL) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x2020000ULL);
      case 116:
         if ((active0 & 0x80000ULL) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x1000000ULL) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x20000000ULL) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x200000000ULL) != 0L)
         {
            jjmatchedKind = 97;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x20000ULL, active1, 0x800000ULL);
      case 120:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000ULL, active1, 0L);
      case 121:
         if ((active0 & 0x10000000000ULL) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 5;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(11, 5);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, jjMoveNfa_0(), and jjMoveStringLiteralDfa6_0().
Referenced by jjMoveStringLiteralDfa4_0().
jjMoveStringLiteralDfa5_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa5_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa6_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa6_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 1958 of file VhdlParserTokenManager.cc.
                                                                                                                                                               {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 5);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 5);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000000000ULL, active1, 0L);
      case 67:
         if ((active0 & 0x1000000000000ULL) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x100040c000000ULL);
      case 68:
         if ((active0 & 0x4000000000000ULL) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 6;
         }
         break;
      case 69:
         if ((active0 & 0x800000000000000ULL) != 0L)
         {
            jjmatchedKind = 59;
            jjmatchedPos = 6;
         }
         else if ((active1 & 0x1000ULL) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 6;
         }
         else if ((active1 & 0x2000000ULL) != 0L)
         {
            jjmatchedKind = 89;
            jjmatchedPos = 6;
         }
         else if ((active1 & 0x80000000000ULL) != 0L)
         {
            jjmatchedKind = 107;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x10020000ULL, active1, 0x800000ULL);
      case 76:
         if ((active0 & 0x1000000000000000ULL) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x10000000000000ULL);
      case 78:
         return jjMoveStringLiteralDfa7_0(active0, 0x880000000ULL, active1, 0x8000ULL);
      case 79:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000ULL, active1, 0x400000000000ULL);
      case 83:
         if ((active1 & 0x20000ULL) != 0L)
         {
            jjmatchedKind = 81;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000000ULL, active1, 0L);
      case 84:
         if ((active0 & 0x100000000ULL) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x400000000ULL) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000000ULL, active1, 0x8000c2000ULL);
      case 85:
         return jjMoveStringLiteralDfa7_0(active0, 0x40400000ULL, active1, 0x10000ULL);
      case 89:
         if ((active0 & 0x400000000000000ULL) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 6;
         }
         break;
      case 95:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000ULL, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000000000ULL, active1, 0L);
      case 99:
         if ((active0 & 0x1000000000000ULL) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x100040c000000ULL);
      case 100:
         if ((active0 & 0x4000000000000ULL) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 6;
         }
         break;
      case 101:
         if ((active0 & 0x800000000000000ULL) != 0L)
         {
            jjmatchedKind = 59;
            jjmatchedPos = 6;
         }
         else if ((active1 & 0x1000ULL) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 6;
         }
         else if ((active1 & 0x2000000ULL) != 0L)
         {
            jjmatchedKind = 89;
            jjmatchedPos = 6;
         }
         else if ((active1 & 0x80000000000ULL) != 0L)
         {
            jjmatchedKind = 107;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x10020000ULL, active1, 0x800000ULL);
      case 108:
         if ((active0 & 0x1000000000000000ULL) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x10000000000000ULL);
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x880000000ULL, active1, 0x8000ULL);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000ULL, active1, 0x400000000000ULL);
      case 115:
         if ((active1 & 0x20000ULL) != 0L)
         {
            jjmatchedKind = 81;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000000ULL, active1, 0L);
      case 116:
         if ((active0 & 0x100000000ULL) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x400000000ULL) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000000ULL, active1, 0x8000c2000ULL);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x40400000ULL, active1, 0x10000ULL);
      case 121:
         if ((active0 & 0x400000000000000ULL) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 6;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(11, 6);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, jjMoveNfa_0(), and jjMoveStringLiteralDfa7_0().
Referenced by jjMoveStringLiteralDfa5_0().
jjMoveStringLiteralDfa6_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa6_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa7_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa7_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 2129 of file VhdlParserTokenManager.cc.
                                                                                                                                                               {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 6);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 6);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000ULL, active1, 0L);
      case 69:
         if ((active0 & 0x800000000000ULL) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 7;
         }
         else if ((active1 & 0x400000000ULL) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 7;
         }
         else if ((active1 & 0x10000000000000ULL) != 0L)
         {
            jjmatchedKind = 116;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000ULL, active1, 0x8a000ULL);
      case 71:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000ULL, active1, 0L);
      case 76:
         if ((active0 & 0x40000000000000ULL) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 7;
         }
         break;
      case 78:
         if ((active0 & 0x400000000000ULL) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000ULL, active1, 0L);
      case 82:
         if ((active1 & 0x800000ULL) != 0L)
         {
            jjmatchedKind = 87;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000ULL, active1, 0x400000010000ULL);
      case 83:
         if ((active0 & 0x40000000000ULL) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 7;
         }
         break;
      case 84:
         if ((active0 & 0x80000000ULL) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 7;
         }
         else if ((active1 & 0x4000000ULL) != 0L)
         {
            jjmatchedKind = 90;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x400000ULL, active1, 0x1000008000000ULL);
      case 89:
         if ((active1 & 0x40000ULL) != 0L)
         {
            jjmatchedKind = 82;
            jjmatchedPos = 7;
         }
         else if ((active1 & 0x800000000ULL) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 7;
         }
         break;
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000ULL, active1, 0L);
      case 101:
         if ((active0 & 0x800000000000ULL) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 7;
         }
         else if ((active1 & 0x400000000ULL) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 7;
         }
         else if ((active1 & 0x10000000000000ULL) != 0L)
         {
            jjmatchedKind = 116;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000ULL, active1, 0x8a000ULL);
      case 103:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000ULL, active1, 0L);
      case 108:
         if ((active0 & 0x40000000000000ULL) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 7;
         }
         break;
      case 110:
         if ((active0 & 0x400000000000ULL) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000ULL, active1, 0L);
      case 114:
         if ((active1 & 0x800000ULL) != 0L)
         {
            jjmatchedKind = 87;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000ULL, active1, 0x400000010000ULL);
      case 115:
         if ((active0 & 0x40000000000ULL) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 7;
         }
         break;
      case 116:
         if ((active0 & 0x80000000ULL) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 7;
         }
         else if ((active1 & 0x4000000ULL) != 0L)
         {
            jjmatchedKind = 90;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x400000ULL, active1, 0x1000008000000ULL);
      case 121:
         if ((active1 & 0x40000ULL) != 0L)
         {
            jjmatchedKind = 82;
            jjmatchedPos = 7;
         }
         else if ((active1 & 0x800000000ULL) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 7;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(11, 7);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, jjMoveNfa_0(), and jjMoveStringLiteralDfa8_0().
Referenced by jjMoveStringLiteralDfa6_0().
jjMoveStringLiteralDfa7_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa7_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa8_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa8_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 2290 of file VhdlParserTokenManager.cc.
                                                                                                                                                               {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 7);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 7);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000ULL, active1, 0L);
      case 67:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000ULL, active1, 0L);
      case 68:
         if ((active1 & 0x8000ULL) != 0L)
         {
            jjmatchedKind = 79;
            jjmatchedPos = 8;
         }
         else if ((active1 & 0x80000ULL) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 8;
         }
         break;
      case 69:
         if ((active0 & 0x400000ULL) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 8;
         }
         else if ((active1 & 0x10000ULL) != 0L)
         {
            jjmatchedKind = 80;
            jjmatchedPos = 8;
         }
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x1000000000000ULL);
      case 82:
         if ((active1 & 0x2000ULL) != 0L)
         {
            jjmatchedKind = 77;
            jjmatchedPos = 8;
         }
         break;
      case 84:
         if ((active0 & 0x10000000ULL) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 8;
         }
         else if ((active1 & 0x400000000000ULL) != 0L)
         {
            jjmatchedKind = 110;
            jjmatchedPos = 8;
         }
         return jjMoveStringLiteralDfa9_0(active0, 0x20000ULL, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa9_0(active0, 0x200000ULL, active1, 0L);
      case 95:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x8000000ULL);
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000ULL, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000ULL, active1, 0L);
      case 100:
         if ((active1 & 0x8000ULL) != 0L)
         {
            jjmatchedKind = 79;
            jjmatchedPos = 8;
         }
         else if ((active1 & 0x80000ULL) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 8;
         }
         break;
      case 101:
         if ((active0 & 0x400000ULL) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 8;
         }
         else if ((active1 & 0x10000ULL) != 0L)
         {
            jjmatchedKind = 80;
            jjmatchedPos = 8;
         }
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x1000000000000ULL);
      case 114:
         if ((active1 & 0x2000ULL) != 0L)
         {
            jjmatchedKind = 77;
            jjmatchedPos = 8;
         }
         break;
      case 116:
         if ((active0 & 0x10000000ULL) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 8;
         }
         else if ((active1 & 0x400000000000ULL) != 0L)
         {
            jjmatchedKind = 110;
            jjmatchedPos = 8;
         }
         return jjMoveStringLiteralDfa9_0(active0, 0x20000ULL, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa9_0(active0, 0x200000ULL, active1, 0L);
      default :
         break;
   }
   return jjMoveNfa_0(11, 8);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, jjMoveNfa_0(), and jjMoveStringLiteralDfa9_0().
Referenced by jjMoveStringLiteralDfa7_0().
jjMoveStringLiteralDfa8_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa8_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjMoveStringLiteralDfa9_0() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa9_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
Definition at line 2405 of file VhdlParserTokenManager.cc.
                                                                                                                                                               {
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(11, 8);
   if (input_stream->endOfInput()) {
   return jjMoveNfa_0(11, 8);
   }
   curChar = input_stream->readChar();
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa10_0(active0, 0x200000ULL, active1, 0L);
      case 68:
         if ((active1 & 0x1000000000000ULL) != 0L)
         {
            jjmatchedKind = 112;
            jjmatchedPos = 9;
         }
         break;
      case 71:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x8000000ULL);
      case 84:
         if ((active0 & 0x800000000ULL) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0x40000000ULL, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000ULL, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x200000ULL, active1, 0L);
      case 100:
         if ((active1 & 0x1000000000000ULL) != 0L)
         {
            jjmatchedKind = 112;
            jjmatchedPos = 9;
         }
         break;
      case 103:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x8000000ULL);
      case 116:
         if ((active0 & 0x800000000ULL) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0x40000000ULL, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000ULL, active1, 0L);
      default :
         break;
   }
   return jjMoveNfa_0(11, 9);
}
References curChar, input_stream, jjmatchedKind, jjmatchedPos, jjMoveNfa_0(), and jjMoveStringLiteralDfa10_0().
Referenced by jjMoveStringLiteralDfa8_0().
jjMoveStringLiteralDfa9_0() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjMoveStringLiteralDfa9_0 (unsigned long long old0, unsigned long long active0, unsigned long long old1, unsigned long long active1)
jjStopAtPos() [1/2]
int vhdl::parser::VhdlParserTokenManager::jjStopAtPos (int pos, int kind)
Definition at line 452 of file VhdlParserTokenManager.cc.
                                                          {
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
References jjmatchedKind, and jjmatchedPos.
jjStopAtPos() [2/2]
int vhdl::parser::VhdlParserTokenManager::jjStopAtPos (int pos, int kind)
ReInit() [1/2]
void vhdl::parser::VhdlParserTokenManager::ReInit (JAVACC_CHARSTREAM * stream, int lexState = 0)
Reinitialise parser.
Definition at line 3671 of file VhdlParserTokenManager.cc.
                                                                             {
    clear();
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = lexState;
    input_stream = stream;
    ReInitRounds();
    debugStream = stdout; // init
    SwitchTo(lexState);
    errorHandler = new TokenManagerErrorHandler();
  }
References clear(), curLexState, debugStream, errorHandler, input_stream, jjmatchedPos, jjnewStateCnt, ReInitRounds(), and SwitchTo().
Referenced by VHDLOutlineParser::Private::parseVhdlfile(), and VhdlParserTokenManager().
ReInit() [2/2]
void vhdl::parser::VhdlParserTokenManager::ReInit (JAVACC_CHARSTREAM * stream, int lexState = 0)
ReInitRounds() [1/2]
void vhdl::parser::VhdlParserTokenManager::ReInitRounds () [private]
Definition at line 3682 of file VhdlParserTokenManager.cc.
                                            {
    int i;
    jjround = 0x80000001;
    for (i = 87; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }
References jjround, and jjrounds.
Referenced by jjMoveNfa_0(), and ReInit().
ReInitRounds() [2/2]
void vhdl::parser::VhdlParserTokenManager::ReInitRounds () [private]
setDebugStream() [1/2]
void vhdl::parser::VhdlParserTokenManager::setDebugStream (FILE * ds)
Definition at line 450 of file VhdlParserTokenManager.cc.
{ debugStream = ds; }
References debugStream.
setDebugStream() [2/2]
void vhdl::parser::VhdlParserTokenManager::setDebugStream (FILE * ds)
setErrorHandler() [1/2]
void vhdl::parser::VhdlParserTokenManager::setErrorHandler (TokenManagerErrorHandler * eh) [inline]
Definition at line 111 of file VhdlParserTokenManager.h.
                                                     {
      if (errorHandler) delete errorHandler, errorHandler = nullptr;
      errorHandler = eh;
    }
References errorHandler.
Referenced by VHDLOutlineParser::Private::parseVhdlfile().
setErrorHandler() [2/2]
void vhdl::parser::VhdlParserTokenManager::setErrorHandler (TokenManagerErrorHandler * eh) [inline]
Definition at line 111 of file VhdlParserTokenManager.h.
                                                     {
      if (errorHandler) delete errorHandler, errorHandler = nullptr;
      errorHandler = eh;
    }
References errorHandler.
SkipLexicalActions() [1/2]
void vhdl::parser::VhdlParserTokenManager::SkipLexicalActions (Token * matchedToken)
Definition at line 3486 of file VhdlParserTokenManager.cc.
                                                                   {
   switch(jjmatchedKind)
   {
      case 3 : {
         image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        parser->outlineParser()->lineCount();
         break;
       }
      case 6 : {
         image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
    {
    QCString doc(image.data());
     int count=doc.contains("--!");
     parser->outlineParser()->setMultCommentLine();
    parser->outlineParser()->lineCount(image.data());
    if (count == 1)
      parser->outlineParser()->oneLineComment(doc);
    else
      parser->outlineParser()->handleCommentBlock(QCString(image),FALSE); ;
    }
         break;
       }
      case 7 : {
         image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                               parser->outlineParser()->handleFlowComment(image.data());
         break;
       }
      case 8 : {
         image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
    parser->outlineParser()->lineCount(image.data());
         break;
       }
      case 9 : {
         image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
   {
     QCString q = filter2008VhdlComment(image.data());
     parser->outlineParser()->lineCount(image.data());
     parser->outlineParser()->handleCommentBlock(QCString(q),TRUE);image.clear();
   }
         break;
       }
      case 10 : {
         image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
      parser->outlineParser()->lineCount(image.data());image.clear();
         break;
       }
      default :
         break;
   }
}
References QCString::contains(), FALSE, filter2008VhdlComment(), VHDLOutlineParser::handleCommentBlock(), VHDLOutlineParser::handleFlowComment(), image, input_stream, jjimageLen, jjmatchedKind, jjmatchedPos, lengthOfMatch, VHDLOutlineParser::lineCount(), VHDLOutlineParser::oneLineComment(), vhdl::parser::VhdlParser::outlineParser(), vhdl::parser::TokenParser::parser, VHDLOutlineParser::setMultCommentLine(), and TRUE.
Referenced by getNextToken().
SkipLexicalActions() [2/2]
void vhdl::parser::VhdlParserTokenManager::SkipLexicalActions (Token * matchedToken)
SwitchTo() [1/2]
void vhdl::parser::VhdlParserTokenManager::SwitchTo (int lexState)
Switch to specified lex state.
Definition at line 3690 of file VhdlParserTokenManager.cc.
                                                    {
    if (lexState >= 1 || lexState < 0) {
      JJString message;
#ifdef WIDE_CHAR
      message += L"Error: Ignoring invalid lexical state : ";
      message += lexState; message += L". State unchanged.";
#else
      message += "Error: Ignoring invalid lexical state : ";
      message += lexState; message += ". State unchanged.";
#endif
      throw new TokenMgrError(message, INVALID_LEXICAL_STATE);
    } else
      curLexState = lexState;
  }
References curLexState, and vhdl::parser::INVALID_LEXICAL_STATE.
Referenced by ReInit().
SwitchTo() [2/2]
void vhdl::parser::VhdlParserTokenManager::SwitchTo (int lexState)
TokenLexicalActions() [1/2]
void vhdl::parser::VhdlParserTokenManager::TokenLexicalActions (Token * matchedToken)
Definition at line 3537 of file VhdlParserTokenManager.cc.
                                                                    {
   switch(jjmatchedKind)
   {
      case 14 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      parser->outlineParser()->setLineParsed(ALIAS_T);
         break;
       }
      case 17 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                    parser->outlineParser()->setLineParsed(ARCHITECTURE_T);
         break;
       }
      case 18 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      parser->outlineParser()->setLineParsed(ARRAY_T);
         break;
       }
      case 22 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              parser->outlineParser()->setLineParsed(ATTRIBUTE_T);
         break;
       }
      case 25 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                    parser->outlineParser()->setLineParsed(BODY_T);
         break;
       }
      case 28 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              parser->outlineParser()->setLineParsed(COMPONENT_T);
         break;
       }
      case 30 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                      parser->outlineParser()->setLineParsed(CONFIGURATION_T);
         break;
       }
      case 31 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                             parser->outlineParser()->setLineParsed(CONSTANT_T);
         break;
       }
      case 32 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          parser->outlineParser()->setLineParsed(CONTEXT_T);
         break;
       }
      case 39 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                  parser->outlineParser()->setLineParsed(END_T);
         break;
       }
      case 40 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                        parser->outlineParser()->setLineParsed(ENTITY_T);
         break;
       }
      case 43 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                    parser->outlineParser()->setLineParsed(FILE_T);
         break;
       }
      case 46 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                             parser->outlineParser()->setLineParsed(FUNCTION_T);
         break;
       }
      case 49 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      parser->outlineParser()->setLineParsed(GROUP_T);
         break;
       }
      case 58 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          parser->outlineParser()->setLineParsed(LIBRARY_T);
         break;
       }
      case 76 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          parser->outlineParser()->setLineParsed(PACKAGE_T);
         break;
       }
      case 78 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                    parser->outlineParser()->setLineParsed(PORT_T);
         break;
       }
      case 80 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              parser->outlineParser()->setLineParsed(PROCEDURE_T);
         break;
       }
      case 81 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          parser->outlineParser()->setLineParsed(PROCESS_T);
         break;
       }
      case 86 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                        parser->outlineParser()->setLineParsed(RECORD_T);
         break;
       }
      case 100 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                        parser->outlineParser()->setLineParsed(SIGNAL_T);
         break;
       }
      case 107 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          parser->outlineParser()->setLineParsed(SUBTYPE_T);
         break;
       }
      case 111 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                    parser->outlineParser()->setLineParsed(TYPE_T);
         break;
       }
      case 113 : {
        image.append(input_stream->GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      parser->outlineParser()->setLineParsed(UNITS_T);
         break;
       }
      case 137 : {
        image.append(jjstrLiteralImages[137]);
        lengthOfMatch = jjstrLiteralImages[137].length();
                  parser->outlineParser()->setLineParsed(SEMI_T);
         break;
       }
      default :
         break;
   }
}
References vhdl::parser::ALIAS_T, vhdl::parser::ARCHITECTURE_T, vhdl::parser::ARRAY_T, vhdl::parser::ATTRIBUTE_T, vhdl::parser::BODY_T, vhdl::parser::COMPONENT_T, vhdl::parser::CONFIGURATION_T, vhdl::parser::CONSTANT_T, vhdl::parser::CONTEXT_T, vhdl::parser::END_T, vhdl::parser::ENTITY_T, vhdl::parser::FILE_T, vhdl::parser::FUNCTION_T, vhdl::parser::GROUP_T, image, input_stream, jjimageLen, jjmatchedKind, jjmatchedPos, vhdl::parser::jjstrLiteralImages, lengthOfMatch, vhdl::parser::LIBRARY_T, vhdl::parser::VhdlParser::outlineParser(), vhdl::parser::PACKAGE_T, vhdl::parser::TokenParser::parser, vhdl::parser::PORT_T, vhdl::parser::PROCEDURE_T, vhdl::parser::PROCESS_T, vhdl::parser::RECORD_T, vhdl::parser::SEMI_T, VHDLOutlineParser::setLineParsed(), vhdl::parser::SIGNAL_T, vhdl::parser::SUBTYPE_T, vhdl::parser::TYPE_T, and vhdl::parser::UNITS_T.
Referenced by getNextToken().
TokenLexicalActions() [2/2]
void vhdl::parser::VhdlParserTokenManager::TokenLexicalActions (Token * matchedToken)
Member Data Documentation
curChar
JJChar vhdl::parser::VhdlParserTokenManager::curChar
Definition at line 107 of file VhdlParserTokenManager.h.
Referenced by getNextToken(), jjMoveNfa_0(), jjMoveStringLiteralDfa0_0(), jjMoveStringLiteralDfa10_0(), jjMoveStringLiteralDfa11_0(), jjMoveStringLiteralDfa12_0(), jjMoveStringLiteralDfa13_0(), jjMoveStringLiteralDfa14_0(), jjMoveStringLiteralDfa15_0(), jjMoveStringLiteralDfa16_0(), jjMoveStringLiteralDfa17_0(), jjMoveStringLiteralDfa1_0(), jjMoveStringLiteralDfa2_0(), jjMoveStringLiteralDfa3_0(), jjMoveStringLiteralDfa4_0(), jjMoveStringLiteralDfa5_0(), jjMoveStringLiteralDfa6_0(), jjMoveStringLiteralDfa7_0(), jjMoveStringLiteralDfa8_0(), and jjMoveStringLiteralDfa9_0().
curLexState
int vhdl::parser::VhdlParserTokenManager::curLexState = 0
Definition at line 48 of file VhdlParserTokenManager.h.
Referenced by getNextToken(), ReInit(), and SwitchTo().
debugStream
FILE * vhdl::parser::VhdlParserTokenManager::debugStream
Definition at line 21 of file VhdlParserTokenManager.h.
Referenced by ReInit(), and setDebugStream().
errorHandler
TokenManagerErrorHandler * vhdl::parser::VhdlParserTokenManager::errorHandler = nullptr
Definition at line 108 of file VhdlParserTokenManager.h.
Referenced by clear(), getNextToken(), ReInit(), and setErrorHandler().
image
JJString vhdl::parser::VhdlParserTokenManager::image
Definition at line 104 of file VhdlParserTokenManager.h.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_image(), doxmlparser.compound.docSummaryType::add_image(), doxmlparser.compound.docParaType::add_image(), doxmlparser.compound.docMarkupType::add_image(), doxmlparser.compound.docURLLink::add_image(), doxmlparser.compound.docRefTextType::add_image(), doxmlparser.compound.docCaptionType::add_image(), doxmlparser.compound.docHeadingType::add_image(), doxmlparser.compound.docImageType::add_image(), doxmlparser.compound.docDotMscType::add_image(), doxmlparser.compound.docImageFileType::add_image(), doxmlparser.compound.docPlantumlType::add_image(), doxmlparser.compound.docTocItemType::add_image(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_image(), doxmlparser.compound.docSummaryType::get_image(), doxmlparser.compound.docParaType::get_image(), doxmlparser.compound.docMarkupType::get_image(), doxmlparser.compound.docURLLink::get_image(), doxmlparser.compound.docRefTextType::get_image(), doxmlparser.compound.docCaptionType::get_image(), doxmlparser.compound.docHeadingType::get_image(), doxmlparser.compound.docImageType::get_image(), doxmlparser.compound.docDotMscType::get_image(), doxmlparser.compound.docImageFileType::get_image(), doxmlparser.compound.docPlantumlType::get_image(), doxmlparser.compound.docTocItemType::get_image(), getNextToken(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_image_at(), doxmlparser.compound.docSummaryType::insert_image_at(), doxmlparser.compound.docParaType::insert_image_at(), doxmlparser.compound.docMarkupType::insert_image_at(), doxmlparser.compound.docURLLink::insert_image_at(), doxmlparser.compound.docRefTextType::insert_image_at(), doxmlparser.compound.docCaptionType::insert_image_at(), doxmlparser.compound.docHeadingType::insert_image_at(), doxmlparser.compound.docImageType::insert_image_at(), doxmlparser.compound.docDotMscType::insert_image_at(), doxmlparser.compound.docImageFileType::insert_image_at(), doxmlparser.compound.docPlantumlType::insert_image_at(), doxmlparser.compound.docTocItemType::insert_image_at(), doxmlparser.compound.docTitleType::replace_image_at(), doxmlparser.compound.docSummaryType::replace_image_at(), doxmlparser.compound.docParaType::replace_image_at(), doxmlparser.compound.docMarkupType::replace_image_at(), doxmlparser.compound.docURLLink::replace_image_at(), doxmlparser.compound.docRefTextType::replace_image_at(), doxmlparser.compound.docCaptionType::replace_image_at(), doxmlparser.compound.docHeadingType::replace_image_at(), doxmlparser.compound.docImageType::replace_image_at(), doxmlparser.compound.docDotMscType::replace_image_at(), doxmlparser.compound.docImageFileType::replace_image_at(), doxmlparser.compound.docPlantumlType::replace_image_at(), doxmlparser.compound.docTocItemType::replace_image_at(), doxmlparser.compound.docTitleType::set_image(), doxmlparser.compound.docSummaryType::set_image(), doxmlparser.compound.docParaType::set_image(), doxmlparser.compound.docMarkupType::set_image(), doxmlparser.compound.docURLLink::set_image(), doxmlparser.compound.docRefTextType::set_image(), doxmlparser.compound.docCaptionType::set_image(), doxmlparser.compound.docHeadingType::set_image(), doxmlparser.compound.docImageType::set_image(), doxmlparser.compound.docDotMscType::set_image(), doxmlparser.compound.docImageFileType::set_image(), doxmlparser.compound.docPlantumlType::set_image(), doxmlparser.compound.docTocItemType::set_image(), SkipLexicalActions(), and TokenLexicalActions().
input_stream
JAVACC_CHARSTREAM * vhdl::parser::VhdlParserTokenManager::input_stream
Definition at line 100 of file VhdlParserTokenManager.h.
Referenced by getNextToken(), jjFillToken(), jjMoveNfa_0(), jjMoveStringLiteralDfa10_0(), jjMoveStringLiteralDfa11_0(), jjMoveStringLiteralDfa12_0(), jjMoveStringLiteralDfa13_0(), jjMoveStringLiteralDfa14_0(), jjMoveStringLiteralDfa15_0(), jjMoveStringLiteralDfa16_0(), jjMoveStringLiteralDfa17_0(), jjMoveStringLiteralDfa1_0(), jjMoveStringLiteralDfa2_0(), jjMoveStringLiteralDfa3_0(), jjMoveStringLiteralDfa4_0(), jjMoveStringLiteralDfa5_0(), jjMoveStringLiteralDfa6_0(), jjMoveStringLiteralDfa7_0(), jjMoveStringLiteralDfa8_0(), jjMoveStringLiteralDfa9_0(), ReInit(), SkipLexicalActions(), TokenLexicalActions(), and VhdlParserTokenManager().
jjimage
JJString vhdl::parser::VhdlParserTokenManager::jjimage
Definition at line 103 of file VhdlParserTokenManager.h.
Referenced by getNextToken().
jjimageLen
int vhdl::parser::VhdlParserTokenManager::jjimageLen
Definition at line 105 of file VhdlParserTokenManager.h.
Referenced by getNextToken(), SkipLexicalActions(), and TokenLexicalActions().
jjmatchedKind
int vhdl::parser::VhdlParserTokenManager::jjmatchedKind = 0
Definition at line 52 of file VhdlParserTokenManager.h.
Referenced by getNextToken(), jjFillToken(), jjMoveNfa_0(), jjMoveStringLiteralDfa0_0(), jjMoveStringLiteralDfa11_0(), jjMoveStringLiteralDfa12_0(), jjMoveStringLiteralDfa15_0(), jjMoveStringLiteralDfa17_0(), jjMoveStringLiteralDfa1_0(), jjMoveStringLiteralDfa2_0(), jjMoveStringLiteralDfa3_0(), jjMoveStringLiteralDfa4_0(), jjMoveStringLiteralDfa5_0(), jjMoveStringLiteralDfa6_0(), jjMoveStringLiteralDfa7_0(), jjMoveStringLiteralDfa8_0(), jjMoveStringLiteralDfa9_0(), jjStopAtPos(), SkipLexicalActions(), and TokenLexicalActions().
jjmatchedPos
int vhdl::parser::VhdlParserTokenManager::jjmatchedPos = 0
Definition at line 51 of file VhdlParserTokenManager.h.
Referenced by getNextToken(), jjMoveNfa_0(), jjMoveStringLiteralDfa11_0(), jjMoveStringLiteralDfa12_0(), jjMoveStringLiteralDfa15_0(), jjMoveStringLiteralDfa17_0(), jjMoveStringLiteralDfa1_0(), jjMoveStringLiteralDfa2_0(), jjMoveStringLiteralDfa3_0(), jjMoveStringLiteralDfa4_0(), jjMoveStringLiteralDfa5_0(), jjMoveStringLiteralDfa6_0(), jjMoveStringLiteralDfa7_0(), jjMoveStringLiteralDfa8_0(), jjMoveStringLiteralDfa9_0(), jjStopAtPos(), ReInit(), SkipLexicalActions(), and TokenLexicalActions().
jjnewStateCnt
int vhdl::parser::VhdlParserTokenManager::jjnewStateCnt = 0
Definition at line 49 of file VhdlParserTokenManager.h.
Referenced by jjMoveNfa_0(), and ReInit().
jjround
int vhdl::parser::VhdlParserTokenManager::jjround = 0
Definition at line 50 of file VhdlParserTokenManager.h.
Referenced by jjMoveNfa_0(), and ReInitRounds().
jjrounds
int vhdl::parser::VhdlParserTokenManager::jjrounds
Definition at line 101 of file VhdlParserTokenManager.h.
Referenced by ReInitRounds().
jjstateSet
int vhdl::parser::VhdlParserTokenManager::jjstateSet
Definition at line 102 of file VhdlParserTokenManager.h.
Referenced by jjMoveNfa_0().
lengthOfMatch
int vhdl::parser::VhdlParserTokenManager::lengthOfMatch
Definition at line 106 of file VhdlParserTokenManager.h.
Referenced by SkipLexicalActions(), and TokenLexicalActions().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/vhdlparser/VhdlParserTokenManager.h
doxygen/vhdlparser/VhdlParserTokenManager.h
doxygen/build/doxygen/vhdlparser/VhdlParserTokenManager.cc
doxygen/vhdlparser/VhdlParserTokenManager.cc