TemplateNodeTree Class Reference
Class representing an 'tree' tag in a template.
Classes
struct TreeContext
Public Member Functions
TemplateNodeTree (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
QCString renderChildren (const TreeContext *ctx)
void render (TextStream &ts, TemplateContext *c)
TemplateNodeTree (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
QCString renderChildren (const TreeContext *ctx)
void render (TextStream &ts, TemplateContext *c)
Private Attributes
ExprAstPtr m_treeExpr
TemplateNodeList m_treeNodes
Additional Inherited Members
Detailed Description
Class representing an 'tree' tag in a template.
Definition at line 3934 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeTree() [1/2]
TemplateNodeTree::TemplateNodeTree (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3945 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeTree>(parser,parent,line)
    {
      TRACE(("{TemplateNodeTree(%s)\n",qPrint(data)));
      ExpressionParser ep(parser,line);
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"recursetree tag is missing data argument");
      }
      m_treeExpr = ep.parse(data);
      StringVector stopAt = { "endrecursetree" };
      parser->parse(this,line,stopAt,m_treeNodes);
      parser->removeNextToken(); // skip over endrecursetree
      TRACE(("}TemplateNodeTree(%s)\n",qPrint(data)));
    }
References data, TemplateNodeCreator< TemplateNodeTree >::m_templateName, m_treeExpr, m_treeNodes, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), TRACE, and TemplateParser::warn().
TemplateNodeTree() [2/2]
TemplateNodeTree::TemplateNodeTree (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3945 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeTree>(parser,parent,line)
    {
      TRACE(("{TemplateNodeTree(%s)\n",qPrint(data)));
      ExpressionParser ep(parser,line);
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"recursetree tag is missing data argument");
      }
      m_treeExpr = ep.parse(data);
      StringVector stopAt = { "endrecursetree" };
      parser->parse(this,line,stopAt,m_treeNodes);
      parser->removeNextToken(); // skip over endrecursetree
      TRACE(("}TemplateNodeTree(%s)\n",qPrint(data)));
    }
References data, TemplateNodeCreator< TemplateNodeTree >::m_templateName, m_treeExpr, m_treeNodes, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), TRACE, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeTree::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4013 of file template.cpp.
    {
      //printf("TemplateNodeTree::render()\n");
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      TemplateVariant v = m_treeExpr->resolve(c);
      const TemplateListIntfPtr list = v.toList();
      if (list)
      {
        TreeContext ctx(this,list,c);
        ts << renderChildren(&ctx);
      }
      else
      {
        ci->warn(m_templateName,m_line,"recursetree's argument should be a list type");
      }
    }
References c, TemplateNodeCreator< TemplateNodeTree >::m_line, TemplateNodeCreator< TemplateNodeTree >::m_templateName, m_treeExpr, renderChildren(), TemplateContextImpl::setLocation(), TemplateVariant::toList(), and TemplateContextImpl::warn().
render() [2/2]
void TemplateNodeTree::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4013 of file template.cpp.
    {
      //printf("TemplateNodeTree::render()\n");
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      TemplateVariant v = m_treeExpr->resolve(c);
      const TemplateListIntfPtr list = v.toList();
      if (list)
      {
        TreeContext ctx(this,list,c);
        ts << renderChildren(&ctx);
      }
      else
      {
        ci->warn(m_templateName,m_line,"recursetree's argument should be a list type");
      }
    }
References c, TemplateNodeCreator< TemplateNodeTree >::m_line, TemplateNodeCreator< TemplateNodeTree >::m_templateName, m_treeExpr, renderChildren(), TemplateContextImpl::setLocation(), TemplateVariant::toList(), and TemplateContextImpl::warn().
renderChildren() [1/2]
QCString TemplateNodeTree::renderChildren (const TreeContext * ctx) [inline]
Definition at line 3960 of file template.cpp.
    {
      //printf("TemplateNodeTree::renderChildren(%d)\n",ctx->list->count());
      // render all children of node to a string and return it
      TemplateContext *c = ctx->templateCtx;
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return QCString(); // should not happen
      TextStream ss;
      c->push();
      TemplateVariant node;
      TemplateListIntf::ConstIteratorPtr it = ctx->list->createIterator();
      for (it->toFirst();(it->current(node));it->toNext())
      {
        c->set("node",node);
        bool hasChildren=FALSE;
        const TemplateStructIntfPtr ns = node.toStruct();
        if (ns) // node is a struct
        {
          TemplateVariant v = ns->get("children");
          if (v.isValid()) // with a field 'children'
          {
            const TemplateListIntfPtr list = v.toList();
            if (list && list->count()>0) // non-empty list
            {
              TreeContext childCtx(this,list,ctx->templateCtx);
              TemplateVariant children(
                    [childCtx](const TemplateVariantList &) {
                       return TemplateVariant(childCtx.object->renderChildren(&childCtx),TRUE);
                    });
              children.setRaw(TRUE);
              c->set("children",children);
              m_treeNodes.render(ss,c);
              hasChildren=TRUE;
            }
            else if (list==0)
            {
              ci->warn(m_templateName,m_line,"recursetree: children attribute has type '%s' instead of list\n",qPrint(v.typeAsString()));
            }
          }
          //else
          //{
          // ci->warn(m_templateName,m_line,"recursetree: children attribute is not valid");
          //}
        }
        if (!hasChildren)
        {
          c->set("children",TemplateVariant("")); // provide default
          m_treeNodes.render(ss,c);
        }
      }
      c->pop();
      return ss.str();
    }
References c, FALSE, TemplateVariant::isValid(), TemplateNodeTree::TreeContext::list, TemplateNodeCreator< TemplateNodeTree >::m_line, TemplateNodeCreator< TemplateNodeTree >::m_templateName, m_treeNodes, TemplateNodeTree::TreeContext::object, qPrint(), TemplateNodeList::render(), renderChildren(), TemplateVariant::setRaw(), TextStream::str(), TemplateNodeTree::TreeContext::templateCtx, TemplateVariant::toList(), TemplateVariant::toStruct(), TRUE, TemplateVariant::typeAsString(), and TemplateContextImpl::warn().
Referenced by render(), and renderChildren().
renderChildren() [2/2]
QCString TemplateNodeTree::renderChildren (const TreeContext * ctx) [inline]
Definition at line 3960 of file template.cpp.
    {
      //printf("TemplateNodeTree::renderChildren(%d)\n",ctx->list->count());
      // render all children of node to a string and return it
      TemplateContext *c = ctx->templateCtx;
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return QCString(); // should not happen
      TextStream ss;
      c->push();
      TemplateVariant node;
      TemplateListIntf::ConstIteratorPtr it = ctx->list->createIterator();
      for (it->toFirst();(it->current(node));it->toNext())
      {
        c->set("node",node);
        bool hasChildren=FALSE;
        const TemplateStructIntfPtr ns = node.toStruct();
        if (ns) // node is a struct
        {
          TemplateVariant v = ns->get("children");
          if (v.isValid()) // with a field 'children'
          {
            const TemplateListIntfPtr list = v.toList();
            if (list && list->count()>0) // non-empty list
            {
              TreeContext childCtx(this,list,ctx->templateCtx);
              TemplateVariant children(
                    [childCtx](const TemplateVariantList &) {
                       return TemplateVariant(childCtx.object->renderChildren(&childCtx),TRUE);
                    });
              children.setRaw(TRUE);
              c->set("children",children);
              m_treeNodes.render(ss,c);
              hasChildren=TRUE;
            }
            else if (list==0)
            {
              ci->warn(m_templateName,m_line,"recursetree: children attribute has type '%s' instead of list\n",qPrint(v.typeAsString()));
            }
          }
          //else
          //{
          // ci->warn(m_templateName,m_line,"recursetree: children attribute is not valid");
          //}
        }
        if (!hasChildren)
        {
          c->set("children",TemplateVariant("")); // provide default
          m_treeNodes.render(ss,c);
        }
      }
      c->pop();
      return ss.str();
    }
References c, FALSE, TemplateVariant::isValid(), TemplateNodeCreator< TemplateNodeTree >::m_line, TemplateNodeCreator< TemplateNodeTree >::m_templateName, m_treeNodes, qPrint(), TemplateNodeList::render(), TemplateVariant::setRaw(), TextStream::str(), TemplateVariant::toList(), TemplateVariant::toStruct(), TRUE, TemplateVariant::typeAsString(), and TemplateContextImpl::warn().
Member Data Documentation
m_treeExpr
ExprAstPtr TemplateNodeTree::m_treeExpr [private]
Definition at line 4033 of file template.cpp.
Referenced by render(), and TemplateNodeTree().
m_treeNodes
TemplateNodeList TemplateNodeTree::m_treeNodes [private]
Definition at line 4034 of file template.cpp.
Referenced by renderChildren(), and TemplateNodeTree().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp