ClassListContext::Private Class Reference
Public Member Functions
void addClasses (const ClassLinkedMap &classLinkedMap)
void addClasses (const ClassLinkedMap &classLinkedMap)
Additional Inherited Members
Detailed Description
Definition at line 4993 of file context.cpp.
Member Function Documentation
addClasses() [1/2]
void ClassListContext::Private::addClasses (const ClassLinkedMap & classLinkedMap) [inline]
Definition at line 4996 of file context.cpp.
    {
      for (const auto &cd : classLinkedMap)
      {
        if (cd->getLanguage()==SrcLangExt_VHDL &&
            (VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKAGECLASS ||
             VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKBODYCLASS)
           ) // no architecture
        {
          continue;
        }
        if (cd->isLinkableInProject() && cd->templateMaster()==0 &&
            !cd->isHidden() && !cd->isEmbeddedInOuterScope())
        {
          append(ClassContext::alloc(cd.get()));
        }
      }
    }
References ClassContext::alloc(), GenericNodeListContext::append(), VhdlDocGen::convert(), VhdlDocGen::PACKAGECLASS, VhdlDocGen::PACKBODYCLASS, and SrcLangExt_VHDL.
addClasses() [2/2]
void ClassListContext::Private::addClasses (const ClassLinkedMap & classLinkedMap) [inline]
Definition at line 4996 of file context.cpp.
    {
      for (const auto &cd : classLinkedMap)
      {
        if (cd->getLanguage()==SrcLangExt_VHDL &&
            (VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKAGECLASS ||
             VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKBODYCLASS)
           ) // no architecture
        {
          continue;
        }
        if (cd->isLinkableInProject() && cd->templateMaster()==0 &&
            !cd->isHidden() && !cd->isEmbeddedInOuterScope())
        {
          append(ClassContext::alloc(cd.get()));
        }
      }
    }
References ClassContext::alloc(), VhdlDocGen::convert(), VhdlDocGen::PACKAGECLASS, VhdlDocGen::PACKBODYCLASS, and SrcLangExt_VHDL.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp