Fn_Test Class Reference
Fn_Test class.
#include <func.h>
Public Member Functions
const char * member (char, int) throw (std::out_of_range)
A member function.
const char * member (char, int) throw (std::out_of_range)
Detailed Description
Fn_Test class.
Details about Fn_Test.
Definition at line 1 of file func.h.
Member Function Documentation
member() [1/2]
const char * Fn_Test::member (char c, int n) throw (std::out_of_range)
A member function.
Parameters
c a character.
n an integer.
Exceptions
std::out_of_range parameter is out of range.
Returns
a character pointer.
Definition at line 7 of file func.h.
{}
Referenced by doxmlparser.compound.listofallmembersType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.listofallmembersType::add_member(), doxmlparser.index.CompoundType::add_member(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.listofallmembersType::get_member(), doxmlparser.index.CompoundType::get_member(), doxmlparser.compound.listofallmembersType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.compound.listofallmembersType::insert_member_at(), doxmlparser.index.CompoundType::insert_member_at(), doxmlparser.compound.listofallmembersType::replace_member_at(), doxmlparser.index.CompoundType::replace_member_at(), doxmlparser.compound.listofallmembersType::set_member(), and doxmlparser.index.CompoundType::set_member().
member() [2/2]
const char * Fn_Test::member (char , int) throw (std::out_of_range)
Referenced by doxmlparser.compound.listofallmembersType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.listofallmembersType::add_member(), doxmlparser.index.CompoundType::add_member(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.listofallmembersType::get_member(), doxmlparser.index.CompoundType::get_member(), doxmlparser.compound.listofallmembersType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.compound.listofallmembersType::insert_member_at(), doxmlparser.index.CompoundType::insert_member_at(), doxmlparser.compound.listofallmembersType::replace_member_at(), doxmlparser.index.CompoundType::replace_member_at(), doxmlparser.compound.listofallmembersType::set_member(), and doxmlparser.index.CompoundType::set_member().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/examples/func.h
doxygen/examples/func.h