ConfigBool Class Reference
#include <configimpl.h>
Public Member Functions
ConfigBool (const char *name, const char *doc, bool defVal)
QCString * valueStringRef ()
bool * valueRef ()
void convertStrToVal (Config::CompareMode compareMode)
void substEnvVars ()
void setValueString (const QCString &v)
void writeTemplate (TextStream &t, bool sl, bool upd)
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)
void writeXMLDoxyfile (TextStream &t)
void init ()
bool isDefault ()
ConfigBool (const char *name, const char *doc, bool defVal)
QCString * valueStringRef ()
bool * valueRef ()
void convertStrToVal (Config::CompareMode compareMode)
void substEnvVars ()
void setValueString (const QCString &v)
void writeTemplate (TextStream &t, bool sl, bool upd)
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)
void writeXMLDoxyfile (TextStream &t)
void init ()
bool isDefault ()
Private Attributes
bool m_value
bool m_defValue
QCString m_valueString
Additional Inherited Members
Detailed Description
Class representing a Boolean type option.
Definition at line 251 of file configimpl.h.
Constructor & Destructor Documentation
ConfigBool() [1/2]
ConfigBool::ConfigBool (const char * name, const char * doc, bool defVal) [inline]
Definition at line 254 of file configimpl.h.
      : ConfigOption(O_Bool)
    {
      m_name = name;
      m_doc = doc;
      m_value = defVal;
      m_defValue = defVal;
    }
References m_defValue, ConfigOption::m_doc, ConfigOption::m_name, m_value, and ConfigOption::name().
ConfigBool() [2/2]
ConfigBool::ConfigBool (const char * name, const char * doc, bool defVal) [inline]
Definition at line 254 of file configimpl.h.
      : ConfigOption(O_Bool)
    {
      m_name = name;
      m_doc = doc;
      m_value = defVal;
      m_defValue = defVal;
    }
References m_defValue, ConfigOption::m_doc, ConfigOption::m_name, m_value, and ConfigOption::name().
Member Function Documentation
compareDoxyfile() [1/2]
void ConfigBool::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) [virtual]
Implements ConfigOption.
Definition at line 589 of file configimpl.l.
{
  if (!isDefault() || ((compareMode == Config::CompareMode::CompressedNoEnv) && containsEnvVar(m_valueString))) writeTemplate(t,TRUE,TRUE);
}
References Config::CompressedNoEnv, containsEnvVar(), isDefault(), m_valueString, TRUE, and writeTemplate().
compareDoxyfile() [2/2]
void ConfigBool::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) [virtual]
Implements ConfigOption.
convertStrToVal() [1/2]
void ConfigBool::convertStrToVal (Config::CompareMode compareMode) [virtual]
Reimplemented from ConfigOption.
Definition at line 249 of file configimpl.l.
{
  if (!m_valueString.stripWhiteSpace().isEmpty())
  {
    if (compareMode == Config::CompareMode::CompressedNoEnv)
    {
       if (containsEnvVar(m_valueString)) return;
    }
    bool isValid=false;
    bool b = convertStringToBool(m_valueString,isValid);
    if (isValid)
    {
      m_value=b;
    }
    else
    {
      config_warn("argument '%s' for option %s is not a valid boolean value\n"
          "Using the default: %s!\n",qPrint(m_valueString),qPrint(m_name),m_value?"YES":"NO");
    }
  }
}
References b, Config::CompressedNoEnv, config_warn(), containsEnvVar(), convertStringToBool(), QCString::isEmpty(), ConfigOption::m_name, m_value, m_valueString, qPrint(), and QCString::stripWhiteSpace().
convertStrToVal() [2/2]
void ConfigBool::convertStrToVal (Config::CompareMode compareMode) [virtual]
Reimplemented from ConfigOption.
init() [1/2]
void ConfigBool::init () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 270 of file configimpl.h.
{ m_value = m_defValue; }
References m_defValue, and m_value.
init() [2/2]
void ConfigBool::init () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 270 of file configimpl.h.
{ m_value = m_defValue; }
References m_defValue, and m_value.
isDefault() [1/2]
bool ConfigBool::isDefault () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 271 of file configimpl.h.
{ return m_value == m_defValue; }
References m_defValue, and m_value.
Referenced by compareDoxyfile(), and writeXMLDoxyfile().
isDefault() [2/2]
bool ConfigBool::isDefault () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 271 of file configimpl.h.
{ return m_value == m_defValue; }
References m_defValue, and m_value.
setValueString() [1/2]
void ConfigBool::setValueString (const QCString & v) [inline]
Definition at line 266 of file configimpl.h.
{ m_valueString = v; }
References m_valueString.
setValueString() [2/2]
void ConfigBool::setValueString (const QCString & v) [inline]
Definition at line 266 of file configimpl.h.
{ m_valueString = v; }
References m_valueString.
substEnvVars() [1/2]
void ConfigBool::substEnvVars () [virtual]
Implements ConfigOption.
Definition at line 1484 of file configimpl.l.
{
  substEnvVarsInString(m_valueString);
}
References m_valueString, and substEnvVarsInString().
substEnvVars() [2/2]
void ConfigBool::substEnvVars () [virtual]
Implements ConfigOption.
valueRef() [1/2]
bool * ConfigBool::valueRef () [inline]
Definition at line 263 of file configimpl.h.
{ return &m_value; }
References m_value.
valueRef() [2/2]
bool * ConfigBool::valueRef () [inline]
Definition at line 263 of file configimpl.h.
{ return &m_value; }
References m_value.
valueStringRef() [1/2]
QCString * ConfigBool::valueStringRef () [inline]
Definition at line 262 of file configimpl.h.
{ return &m_valueString; }
References m_valueString.
Referenced by Config::updateObsolete().
valueStringRef() [2/2]
QCString * ConfigBool::valueStringRef () [inline]
Definition at line 262 of file configimpl.h.
{ return &m_valueString; }
References m_valueString.
writeTemplate() [1/2]
void ConfigBool::writeTemplate (TextStream & t, bool sl, bool upd) [virtual]
Implements ConfigOption.
Definition at line 564 of file configimpl.l.
{
  if (!sl)
  {
    t << "\n";
    t << convertToComment(m_doc, m_userComment);
    t << "\n";
  }
  else if (!m_userComment.isEmpty())
  {
    t << convertToComment("", m_userComment);
  }
  QCString spaces = m_spaces.left(MAX_OPTION_LENGTH-m_name.length());
  t << m_name << spaces << "=";
  if (upd && !m_valueString.isEmpty())
  {
    writeStringValue(t,m_valueString);
  }
  else
  {
    writeBoolValue(t,m_value);
  }
  t << "\n";
}
References convertToComment(), QCString::isEmpty(), QCString::left(), QCString::length(), ConfigOption::m_doc, ConfigOption::m_name, ConfigOption::m_spaces, ConfigOption::m_userComment, m_value, m_valueString, ConfigOption::MAX_OPTION_LENGTH, caseconvert::sl, ConfigOption::writeBoolValue(), and ConfigOption::writeStringValue().
Referenced by compareDoxyfile().
writeTemplate() [2/2]
void ConfigBool::writeTemplate (TextStream & t, bool sl, bool upd) [virtual]
Implements ConfigOption.
writeXMLDoxyfile() [1/2]
void ConfigBool::writeXMLDoxyfile (TextStream & t) [virtual]
Implements ConfigOption.
Definition at line 594 of file configimpl.l.
{
  t << " <option id='" << m_name << "'";
  t << " default='" << (isDefault() ? "yes" : "no") << "'";
  t << " type='bool'";
  t << ">";
  t << "<value>";
  writeBoolValue(t,m_value,false);
  t << "</value>";
  t << "</option>\n";
}
References isDefault(), ConfigOption::m_name, m_value, and ConfigOption::writeBoolValue().
writeXMLDoxyfile() [2/2]
void ConfigBool::writeXMLDoxyfile (TextStream & t) [virtual]
Implements ConfigOption.
Member Data Documentation
m_defValue
bool ConfigBool::m_defValue [private]
Definition at line 274 of file configimpl.h.
Referenced by ConfigBool(), init(), and isDefault().
m_value
bool ConfigBool::m_value [private]
Definition at line 273 of file configimpl.h.
Referenced by ConfigBool(), convertStrToVal(), init(), isDefault(), valueRef(), writeTemplate(), and writeXMLDoxyfile().
m_valueString
QCString ConfigBool::m_valueString [private]
Definition at line 275 of file configimpl.h.
Referenced by compareDoxyfile(), convertStrToVal(), setValueString(), substEnvVars(), valueStringRef(), and writeTemplate().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/configimpl.h
doxygen/src/configimpl.h
doxygen/build/doxygen/src/configimpl.l
doxygen/src/configimpl.l