TemplateNodeVariable Class Reference
Class representing a variable in a template.
Public Member Functions
TemplateNodeVariable (TemplateParser *parser, TemplateNode *parent, int line, const QCString &var)
~TemplateNodeVariable ()
void render (TextStream &ts, TemplateContext *c)
TemplateNodeVariable (TemplateParser *parser, TemplateNode *parent, int line, const QCString &var)
~TemplateNodeVariable ()
void render (TextStream &ts, TemplateContext *c)
Private Attributes
QCString m_templateName
int m_line = 0
ExprAstPtr m_var
Detailed Description
Class representing a variable in a template.
Definition at line 2970 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeVariable() [1/2]
TemplateNodeVariable::TemplateNodeVariable (TemplateParser * parser, TemplateNode * parent, int line, const QCString & var) [inline]
Definition at line 2973 of file template.cpp.
      : TemplateNode(parent), m_templateName(parser->templateName()), m_line(line)
    {
      TRACE(("TemplateNodeVariable(%s)\n",qPrint(var)));
      ExpressionParser expParser(parser,line);
      m_var = expParser.parse(var);
      if (m_var==0)
      {
        parser->warn(m_templateName,line,"invalid expression '%s' for variable",qPrint(var));
      }
    }
References m_templateName, m_var, ExpressionParser::parse(), qPrint(), TRACE, var, and TemplateParser::warn().
 TemplateNodeVariable() [1/2]
TemplateNodeVariable::~TemplateNodeVariable () [inline]
Definition at line 2984 of file template.cpp.
    {
    }
TemplateNodeVariable() [2/2]
TemplateNodeVariable::TemplateNodeVariable (TemplateParser * parser, TemplateNode * parent, int line, const QCString & var) [inline]
Definition at line 2973 of file template.cpp.
      : TemplateNode(parent), m_templateName(parser->templateName()), m_line(line)
    {
      TRACE(("TemplateNodeVariable(%s)\n",qPrint(var)));
      ExpressionParser expParser(parser,line);
      m_var = expParser.parse(var);
      if (m_var==0)
      {
        parser->warn(m_templateName,line,"invalid expression '%s' for variable",qPrint(var));
      }
    }
References m_templateName, m_var, ExpressionParser::parse(), qPrint(), TRACE, var, and TemplateParser::warn().
 TemplateNodeVariable() [2/2]
TemplateNodeVariable::~TemplateNodeVariable () [inline]
Definition at line 2984 of file template.cpp.
    {
    }
Member Function Documentation
render() [1/2]
void TemplateNodeVariable::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 2988 of file template.cpp.
    {
      TRACE(("{TemplateNodeVariable::render\n"));
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_var)
      {
        TemplateVariant v = m_var->resolve(c);
        if (v.isFunction())
        {
          v = v.call();
        }
        if (ci->escapeIntf() && !v.raw())
        {
          if (ci->needsRecoding())
          {
            ts << ci->recode(ci->escapeIntf()->escape(v.toString()));
          }
          else
          {
            ts << ci->escapeIntf()->escape(v.toString());
          }
        }
        else
        {
          if (ci->needsRecoding())
          {
            ts << ci->recode(v.toString());
          }
          else
          {
            ts << v.toString();
          }
        }
      }
      TRACE(("}TemplateNodeVariable::render\n"));
    }
References c, TemplateVariant::call(), TemplateEscapeIntf::escape(), TemplateContextImpl::escapeIntf(), TemplateVariant::isFunction(), m_line, m_templateName, m_var, TemplateContextImpl::needsRecoding(), TemplateVariant::raw(), TemplateContextImpl::recode(), TemplateContextImpl::setLocation(), TemplateVariant::toString(), and TRACE.
render() [2/2]
void TemplateNodeVariable::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 2988 of file template.cpp.
    {
      TRACE(("{TemplateNodeVariable::render\n"));
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_var)
      {
        TemplateVariant v = m_var->resolve(c);
        if (v.isFunction())
        {
          v = v.call();
        }
        if (ci->escapeIntf() && !v.raw())
        {
          if (ci->needsRecoding())
          {
            ts << ci->recode(ci->escapeIntf()->escape(v.toString()));
          }
          else
          {
            ts << ci->escapeIntf()->escape(v.toString());
          }
        }
        else
        {
          if (ci->needsRecoding())
          {
            ts << ci->recode(v.toString());
          }
          else
          {
            ts << v.toString();
          }
        }
      }
      TRACE(("}TemplateNodeVariable::render\n"));
    }
References c, TemplateVariant::call(), TemplateEscapeIntf::escape(), TemplateContextImpl::escapeIntf(), TemplateVariant::isFunction(), m_line, m_templateName, m_var, TemplateContextImpl::needsRecoding(), TemplateVariant::raw(), TemplateContextImpl::recode(), TemplateContextImpl::setLocation(), TemplateVariant::toString(), and TRACE.
Member Data Documentation
m_line
int TemplateNodeVariable::m_line = 0 [private]
Definition at line 3029 of file template.cpp.
Referenced by render().
m_templateName
QCString TemplateNodeVariable::m_templateName [private]
Definition at line 3028 of file template.cpp.
Referenced by render(), and TemplateNodeVariable().
m_var
ExprAstPtr TemplateNodeVariable::m_var [private]
Definition at line 3030 of file template.cpp.
Referenced by render(), and TemplateNodeVariable().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp