FileContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (const FileDef *fd)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant versionInfo () const
TemplateVariant includeList () const
TemplateVariant hasDetails () const
TemplateVariant hasSourceFile () const
TemplateVariant sources () const
TemplateVariant version () const
TemplateVariant classes () const
TemplateVariant namespaces () const
TemplateVariant constantgroups () const
TemplateVariant macros () const
TemplateVariant typedefs () const
TemplateVariant sequences () const
TemplateVariant dictionaries () const
TemplateVariant enums () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant memberGroups () const
TemplateVariant detailedMacros () const
TemplateVariant detailedTypedefs () const
TemplateVariant detailedSequences () const
TemplateVariant detailedDictionaries () const
TemplateVariant detailedEnums () const
TemplateVariant detailedFunctions () const
TemplateVariant detailedVariables () const
TemplateVariant inlineClasses () const
TemplateVariant compoundType () const
DotInclDepGraphPtr getIncludeGraph () const
DotInclDepGraphPtr getIncludedByGraph () const
TemplateVariant hasIncludeGraph () const
TemplateVariant includeGraph () const
TemplateVariant hasIncludedByGraph () const
TemplateVariant includedByGraph () const
Private (const FileDef *fd)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant versionInfo () const
TemplateVariant includeList () const
TemplateVariant hasDetails () const
TemplateVariant hasSourceFile () const
TemplateVariant sources () const
TemplateVariant version () const
TemplateVariant classes () const
TemplateVariant namespaces () const
TemplateVariant constantgroups () const
TemplateVariant macros () const
TemplateVariant typedefs () const
TemplateVariant sequences () const
TemplateVariant dictionaries () const
TemplateVariant enums () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant memberGroups () const
TemplateVariant detailedMacros () const
TemplateVariant detailedTypedefs () const
TemplateVariant detailedSequences () const
TemplateVariant detailedDictionaries () const
TemplateVariant detailedEnums () const
TemplateVariant detailedFunctions () const
TemplateVariant detailedVariables () const
TemplateVariant inlineClasses () const
TemplateVariant compoundType () const
DotInclDepGraphPtr getIncludeGraph () const
DotInclDepGraphPtr getIncludedByGraph () const
TemplateVariant hasIncludeGraph () const
TemplateVariant includeGraph () const
TemplateVariant hasIncludedByGraph () const
TemplateVariant includedByGraph () const
Private Member Functions
TemplateVariant createIncludeList () const
DotInclDepGraphPtr createIncludeGraph () const
DotInclDepGraphPtr createIncludedByGraph () const
TemplateVariant createSources () const
TemplateVariant createClasses () const
TemplateVariant createNamespaces () const
TemplateVariant createConstantgroups () const
TemplateVariant createMemberList (MemberListType type, const QCString &title) const
TemplateVariant createMacros () const
TemplateVariant createTypedefs () const
TemplateVariant createSequences () const
TemplateVariant createDictionaries () const
TemplateVariant createEnums () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createDetailedMacros () const
TemplateVariant createDetailedTypedefs () const
TemplateVariant createDetailedSequences () const
TemplateVariant createDetailedDictionaries () const
TemplateVariant createDetailedEnums () const
TemplateVariant createDetailedFunctions () const
TemplateVariant createDetailedVariables () const
TemplateVariant createMemberGroups () const
TemplateVariant createInlineClasses () const
TemplateVariant createIncludeList () const
DotInclDepGraphPtr createIncludeGraph () const
DotInclDepGraphPtr createIncludedByGraph () const
TemplateVariant createSources () const
TemplateVariant createClasses () const
TemplateVariant createNamespaces () const
TemplateVariant createConstantgroups () const
TemplateVariant createMemberList (MemberListType type, const QCString &title) const
TemplateVariant createMacros () const
TemplateVariant createTypedefs () const
TemplateVariant createSequences () const
TemplateVariant createDictionaries () const
TemplateVariant createEnums () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createDetailedMacros () const
TemplateVariant createDetailedTypedefs () const
TemplateVariant createDetailedSequences () const
TemplateVariant createDetailedDictionaries () const
TemplateVariant createDetailedEnums () const
TemplateVariant createDetailedFunctions () const
TemplateVariant createDetailedVariables () const
TemplateVariant createMemberGroups () const
TemplateVariant createInlineClasses () const
Private Attributes
const FileDef * m_fileDef
Cachable m_cachable
Static Private Attributes
static const PropertyMap< FileContext::Private > s_inst
Additional Inherited Members
Detailed Description
Definition at line 2738 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
FileContext::Private::Private (const FileDef * fd) [inline]
Definition at line 2741 of file context.cpp.
                               : DefinitionContext<FileContext::Private>(fd) , m_fileDef(fd)
    {
      if (fd==0) abort();
    }
Private() [2/2]
FileContext::Private::Private (const FileDef * fd) [inline]
Definition at line 2741 of file context.cpp.
                               : DefinitionContext<FileContext::Private>(fd) , m_fileDef(fd)
    {
      if (fd==0) abort();
    }
Member Function Documentation
classes() [1/2]
TemplateVariant FileContext::Private::classes () const [inline]
Definition at line 2760 of file context.cpp.
{ return m_cachable.classes.get(this); }
References FileContext::Private::Cachable::classes, and m_cachable.
classes() [2/2]
TemplateVariant FileContext::Private::classes () const [inline]
Definition at line 2760 of file context.cpp.
{ return m_cachable.classes.get(this); }
compoundType() [1/2]
TemplateVariant FileContext::Private::compoundType () const [inline]
Definition at line 2779 of file context.cpp.
{ return theTranslator->trFile(FALSE,TRUE); }
References FALSE, theTranslator, Translator::trFile(), and TRUE.
compoundType() [2/2]
TemplateVariant FileContext::Private::compoundType () const [inline]
Definition at line 2779 of file context.cpp.
{ return theTranslator->trFile(FALSE,TRUE); }
References FALSE, theTranslator, Translator::trFile(), and TRUE.
constantgroups() [1/2]
TemplateVariant FileContext::Private::constantgroups () const [inline]
Definition at line 2762 of file context.cpp.
{ return m_cachable.constantgroups.get(this); }
References FileContext::Private::Cachable::constantgroups, and m_cachable.
constantgroups() [2/2]
TemplateVariant FileContext::Private::constantgroups () const [inline]
Definition at line 2762 of file context.cpp.
{ return m_cachable.constantgroups.get(this); }
createClasses() [1/2]
TemplateVariant FileContext::Private::createClasses () const [inline], [private]
Definition at line 2890 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_fileDef->getClasses().size());
      for (const auto &cd : m_fileDef->getClasses())
      {
        if (cd->visibleInParentsDeclList())
        {
          list.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ClassContext::alloc(), TemplateImmutableList::alloc(), FileDef::getClasses(), m_fileDef, and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
createClasses() [2/2]
TemplateVariant FileContext::Private::createClasses () const [inline], [private]
Definition at line 2890 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_fileDef->getClasses().size());
      for (const auto &cd : m_fileDef->getClasses())
      {
        if (cd->visibleInParentsDeclList())
        {
          list.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ClassContext::alloc(), and TemplateImmutableList::alloc().
createConstantgroups() [1/2]
TemplateVariant FileContext::Private::createConstantgroups () const [inline], [private]
Definition at line 2916 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_fileDef->getNamespaces().size());
      for (const auto &nd : m_fileDef->getNamespaces())
      {
        if (nd->isLinkable() && nd->isConstantGroup())
        {
          list.push_back(NamespaceContext::alloc(nd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References NamespaceContext::alloc(), TemplateImmutableList::alloc(), FileDef::getNamespaces(), m_fileDef, and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
createConstantgroups() [2/2]
TemplateVariant FileContext::Private::createConstantgroups () const [inline], [private]
Definition at line 2916 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_fileDef->getNamespaces().size());
      for (const auto &nd : m_fileDef->getNamespaces())
      {
        if (nd->isLinkable() && nd->isConstantGroup())
        {
          list.push_back(NamespaceContext::alloc(nd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References NamespaceContext::alloc(), and TemplateImmutableList::alloc().
createDetailedDictionaries() [1/2]
TemplateVariant FileContext::Private::createDetailedDictionaries () const [inline], [private]
Definition at line 2980 of file context.cpp.
    {
      return createMemberList(MemberListType_docDictionaryMembers,theTranslator->trDictionaryDocumentation());
    }
References createMemberList(), MemberListType_docDictionaryMembers, theTranslator, and Translator::trDictionaryDocumentation().
createDetailedDictionaries() [2/2]
TemplateVariant FileContext::Private::createDetailedDictionaries () const [inline], [private]
Definition at line 2980 of file context.cpp.
    {
      return createMemberList(MemberListType_docDictionaryMembers,theTranslator->trDictionaryDocumentation());
    }
References MemberListType_docDictionaryMembers, theTranslator, and Translator::trDictionaryDocumentation().
createDetailedEnums() [1/2]
TemplateVariant FileContext::Private::createDetailedEnums () const [inline], [private]
Definition at line 2984 of file context.cpp.
    {
      return createMemberList(MemberListType_docEnumMembers,theTranslator->trEnumerationTypeDocumentation());
    }
References createMemberList(), MemberListType_docEnumMembers, theTranslator, and Translator::trEnumerationTypeDocumentation().
createDetailedEnums() [2/2]
TemplateVariant FileContext::Private::createDetailedEnums () const [inline], [private]
Definition at line 2984 of file context.cpp.
    {
      return createMemberList(MemberListType_docEnumMembers,theTranslator->trEnumerationTypeDocumentation());
    }
References MemberListType_docEnumMembers, theTranslator, and Translator::trEnumerationTypeDocumentation().
createDetailedFunctions() [1/2]
TemplateVariant FileContext::Private::createDetailedFunctions () const [inline], [private]
Definition at line 2988 of file context.cpp.
    {
      SrcLangExt lang = m_fileDef->getLanguage();
      return createMemberList(MemberListType_docFuncMembers, lang==SrcLangExt_Fortran ? theTranslator->trSubprogramDocumentation() :
                                                                                        theTranslator->trFunctionDocumentation());
    }
References createMemberList(), Definition::getLanguage(), m_fileDef, MemberListType_docFuncMembers, SrcLangExt_Fortran, theTranslator, Translator::trFunctionDocumentation(), and Translator::trSubprogramDocumentation().
createDetailedFunctions() [2/2]
TemplateVariant FileContext::Private::createDetailedFunctions () const [inline], [private]
Definition at line 2988 of file context.cpp.
    {
      SrcLangExt lang = m_fileDef->getLanguage();
      return createMemberList(MemberListType_docFuncMembers, lang==SrcLangExt_Fortran ? theTranslator->trSubprogramDocumentation() :
                                                                                        theTranslator->trFunctionDocumentation());
    }
References MemberListType_docFuncMembers, SrcLangExt_Fortran, theTranslator, Translator::trFunctionDocumentation(), and Translator::trSubprogramDocumentation().
createDetailedMacros() [1/2]
TemplateVariant FileContext::Private::createDetailedMacros () const [inline], [private]
Definition at line 2968 of file context.cpp.
    {
      return createMemberList(MemberListType_docDefineMembers,theTranslator->trDefineDocumentation());
    }
References createMemberList(), MemberListType_docDefineMembers, theTranslator, and Translator::trDefineDocumentation().
createDetailedMacros() [2/2]
TemplateVariant FileContext::Private::createDetailedMacros () const [inline], [private]
Definition at line 2968 of file context.cpp.
    {
      return createMemberList(MemberListType_docDefineMembers,theTranslator->trDefineDocumentation());
    }
References MemberListType_docDefineMembers, theTranslator, and Translator::trDefineDocumentation().
createDetailedSequences() [1/2]
TemplateVariant FileContext::Private::createDetailedSequences () const [inline], [private]
Definition at line 2976 of file context.cpp.
    {
      return createMemberList(MemberListType_docSequenceMembers,theTranslator->trSequenceDocumentation());
    }
References createMemberList(), MemberListType_docSequenceMembers, theTranslator, and Translator::trSequenceDocumentation().
createDetailedSequences() [2/2]
TemplateVariant FileContext::Private::createDetailedSequences () const [inline], [private]
Definition at line 2976 of file context.cpp.
    {
      return createMemberList(MemberListType_docSequenceMembers,theTranslator->trSequenceDocumentation());
    }
References MemberListType_docSequenceMembers, theTranslator, and Translator::trSequenceDocumentation().
createDetailedTypedefs() [1/2]
TemplateVariant FileContext::Private::createDetailedTypedefs () const [inline], [private]
Definition at line 2972 of file context.cpp.
    {
      return createMemberList(MemberListType_docTypedefMembers,theTranslator->trTypedefDocumentation());
    }
References createMemberList(), MemberListType_docTypedefMembers, theTranslator, and Translator::trTypedefDocumentation().
createDetailedTypedefs() [2/2]
TemplateVariant FileContext::Private::createDetailedTypedefs () const [inline], [private]
Definition at line 2972 of file context.cpp.
    {
      return createMemberList(MemberListType_docTypedefMembers,theTranslator->trTypedefDocumentation());
    }
References MemberListType_docTypedefMembers, theTranslator, and Translator::trTypedefDocumentation().
createDetailedVariables() [1/2]
TemplateVariant FileContext::Private::createDetailedVariables () const [inline], [private]
Definition at line 2994 of file context.cpp.
    {
      return createMemberList(MemberListType_docVarMembers,theTranslator->trVariableDocumentation());
    }
References createMemberList(), MemberListType_docVarMembers, theTranslator, and Translator::trVariableDocumentation().
createDetailedVariables() [2/2]
TemplateVariant FileContext::Private::createDetailedVariables () const [inline], [private]
Definition at line 2994 of file context.cpp.
    {
      return createMemberList(MemberListType_docVarMembers,theTranslator->trVariableDocumentation());
    }
References MemberListType_docVarMembers, theTranslator, and Translator::trVariableDocumentation().
createDictionaries() [1/2]
TemplateVariant FileContext::Private::createDictionaries () const [inline], [private]
Definition at line 2947 of file context.cpp.
    {
      return createMemberList(MemberListType_decDictionaryMembers,theTranslator->trDictionaries());
    }
References createMemberList(), MemberListType_decDictionaryMembers, theTranslator, and Translator::trDictionaries().
createDictionaries() [2/2]
TemplateVariant FileContext::Private::createDictionaries () const [inline], [private]
Definition at line 2947 of file context.cpp.
    {
      return createMemberList(MemberListType_decDictionaryMembers,theTranslator->trDictionaries());
    }
References MemberListType_decDictionaryMembers, theTranslator, and Translator::trDictionaries().
createEnums() [1/2]
TemplateVariant FileContext::Private::createEnums () const [inline], [private]
Definition at line 2951 of file context.cpp.
    {
      return createMemberList(MemberListType_decEnumMembers,theTranslator->trEnumerations());
    }
References createMemberList(), MemberListType_decEnumMembers, theTranslator, and Translator::trEnumerations().
createEnums() [2/2]
TemplateVariant FileContext::Private::createEnums () const [inline], [private]
Definition at line 2951 of file context.cpp.
    {
      return createMemberList(MemberListType_decEnumMembers,theTranslator->trEnumerations());
    }
References MemberListType_decEnumMembers, theTranslator, and Translator::trEnumerations().
createFunctions() [1/2]
TemplateVariant FileContext::Private::createFunctions () const [inline], [private]
Definition at line 2955 of file context.cpp.
    {
      SrcLangExt lang = m_fileDef->getLanguage();
      return createMemberList(MemberListType_decFuncMembers, lang==SrcLangExt_Fortran ? theTranslator->trSubprograms() :
                                                             lang==SrcLangExt_VHDL ? theTranslator->trFunctionAndProc() :
                                                                                        theTranslator->trFunctions());
    }
References createMemberList(), Definition::getLanguage(), m_fileDef, MemberListType_decFuncMembers, SrcLangExt_Fortran, SrcLangExt_VHDL, theTranslator, Translator::trFunctionAndProc(), Translator::trFunctions(), and Translator::trSubprograms().
createFunctions() [2/2]
TemplateVariant FileContext::Private::createFunctions () const [inline], [private]
Definition at line 2955 of file context.cpp.
    {
      SrcLangExt lang = m_fileDef->getLanguage();
      return createMemberList(MemberListType_decFuncMembers, lang==SrcLangExt_Fortran ? theTranslator->trSubprograms() :
                                                             lang==SrcLangExt_VHDL ? theTranslator->trFunctionAndProc() :
                                                                                        theTranslator->trFunctions());
    }
References MemberListType_decFuncMembers, SrcLangExt_Fortran, SrcLangExt_VHDL, theTranslator, Translator::trFunctionAndProc(), Translator::trFunctions(), and Translator::trSubprograms().
createIncludedByGraph() [1/2]
DotInclDepGraphPtr FileContext::Private::createIncludedByGraph () const [inline], [private]
Definition at line 2880 of file context.cpp.
    {
      return std::make_shared<DotInclDepGraph>(m_fileDef,TRUE);
    }
References m_fileDef, and TRUE.
createIncludedByGraph() [2/2]
DotInclDepGraphPtr FileContext::Private::createIncludedByGraph () const [inline], [private]
Definition at line 2880 of file context.cpp.
    {
      return std::make_shared<DotInclDepGraph>(m_fileDef,TRUE);
    }
References TRUE.
createIncludeGraph() [1/2]
DotInclDepGraphPtr FileContext::Private::createIncludeGraph () const [inline], [private]
Definition at line 2876 of file context.cpp.
    {
      return std::make_shared<DotInclDepGraph>(m_fileDef,FALSE);
    }
References FALSE, and m_fileDef.
createIncludeGraph() [2/2]
DotInclDepGraphPtr FileContext::Private::createIncludeGraph () const [inline], [private]
Definition at line 2876 of file context.cpp.
    {
      return std::make_shared<DotInclDepGraph>(m_fileDef,FALSE);
    }
References FALSE.
createIncludeList() [1/2]
TemplateVariant FileContext::Private::createIncludeList () const [inline], [private]
Definition at line 2870 of file context.cpp.
    {
      return !m_fileDef->includeFileList().empty() ?
        TemplateVariant(IncludeInfoListContext::alloc(m_fileDef->includeFileList(),m_fileDef->getLanguage())) :
        TemplateVariant(false);
    }
References IncludeInfoListContext::alloc(), Definition::getLanguage(), FileDef::includeFileList(), and m_fileDef.
createIncludeList() [2/2]
TemplateVariant FileContext::Private::createIncludeList () const [inline], [private]
Definition at line 2870 of file context.cpp.
    {
      return !m_fileDef->includeFileList().empty() ?
        TemplateVariant(IncludeInfoListContext::alloc(m_fileDef->includeFileList(),m_fileDef->getLanguage())) :
        TemplateVariant(false);
    }
References IncludeInfoListContext::alloc().
createInlineClasses() [1/2]
TemplateVariant FileContext::Private::createInlineClasses () const [inline], [private]
Definition at line 3004 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_fileDef->getClasses().size());
      for (const auto &cd : m_fileDef->getClasses())
      {
        if (!cd->isAnonymous() &&
            cd->isLinkableInProject() &&
            cd->isEmbeddedInOuterScope() &&
            cd->partOfGroups().empty())
        {
          list.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ClassContext::alloc(), TemplateImmutableList::alloc(), FileDef::getClasses(), m_fileDef, and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
createInlineClasses() [2/2]
TemplateVariant FileContext::Private::createInlineClasses () const [inline], [private]
Definition at line 3004 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_fileDef->getClasses().size());
      for (const auto &cd : m_fileDef->getClasses())
      {
        if (!cd->isAnonymous() &&
            cd->isLinkableInProject() &&
            cd->isEmbeddedInOuterScope() &&
            cd->partOfGroups().empty())
        {
          list.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ClassContext::alloc(), and TemplateImmutableList::alloc().
createMacros() [1/2]
TemplateVariant FileContext::Private::createMacros () const [inline], [private]
Definition at line 2935 of file context.cpp.
    {
      return createMemberList(MemberListType_decDefineMembers,theTranslator->trDefines());
    }
References createMemberList(), MemberListType_decDefineMembers, theTranslator, and Translator::trDefines().
createMacros() [2/2]
TemplateVariant FileContext::Private::createMacros () const [inline], [private]
Definition at line 2935 of file context.cpp.
    {
      return createMemberList(MemberListType_decDefineMembers,theTranslator->trDefines());
    }
References MemberListType_decDefineMembers, theTranslator, and Translator::trDefines().
createMemberGroups() [1/2]
TemplateVariant FileContext::Private::createMemberGroups () const [inline], [private]
Definition at line 2998 of file context.cpp.
    {
      return !m_fileDef->getMemberGroups().empty() ?
          MemberGroupListContext::alloc(m_fileDef,relPathAsString(),m_fileDef->getMemberGroups(),m_fileDef->subGrouping()) :
          MemberGroupListContext::alloc();
    }
References MemberGroupListContext::alloc(), FileDef::getMemberGroups(), m_fileDef, DefinitionContext< FileContext::Private >::relPathAsString(), and FileDef::subGrouping().
createMemberGroups() [2/2]
TemplateVariant FileContext::Private::createMemberGroups () const [inline], [private]
Definition at line 2998 of file context.cpp.
    {
      return !m_fileDef->getMemberGroups().empty() ?
          MemberGroupListContext::alloc(m_fileDef,relPathAsString(),m_fileDef->getMemberGroups(),m_fileDef->subGrouping()) :
          MemberGroupListContext::alloc();
    }
References MemberGroupListContext::alloc().
createMemberList() [1/2]
TemplateVariant FileContext::Private::createMemberList (MemberListType type, const QCString & title) const [inline], [private]
Definition at line 2929 of file context.cpp.
    {
      const MemberList *ml = m_fileDef->getMemberList(type);
      return ml ? TemplateVariant(MemberListInfoContext::alloc(m_fileDef,relPathAsString(),ml,title,""))
                : TemplateVariant(false);
    }
References MemberListInfoContext::alloc(), FileDef::getMemberList(), m_fileDef, DefinitionContext< FileContext::Private >::relPathAsString(), and title().
Referenced by createDetailedDictionaries(), createDetailedEnums(), createDetailedFunctions(), createDetailedMacros(), createDetailedSequences(), createDetailedTypedefs(), createDetailedVariables(), createDictionaries(), createEnums(), createFunctions(), createMacros(), createSequences(), createTypedefs(), and createVariables().
createMemberList() [2/2]
TemplateVariant FileContext::Private::createMemberList (MemberListType type, const QCString & title) const [inline], [private]
Definition at line 2929 of file context.cpp.
    {
      const MemberList *ml = m_fileDef->getMemberList(type);
      return ml ? TemplateVariant(MemberListInfoContext::alloc(m_fileDef,relPathAsString(),ml,title,""))
                : TemplateVariant(false);
    }
References MemberListInfoContext::alloc().
createNamespaces() [1/2]
TemplateVariant FileContext::Private::createNamespaces () const [inline], [private]
Definition at line 2903 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_fileDef->getNamespaces().size());
      for (const auto &nd : m_fileDef->getNamespaces())
      {
        if (nd->isLinkable() && !nd->isConstantGroup())
        {
          list.push_back(NamespaceContext::alloc(nd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References NamespaceContext::alloc(), TemplateImmutableList::alloc(), FileDef::getNamespaces(), m_fileDef, and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
createNamespaces() [2/2]
TemplateVariant FileContext::Private::createNamespaces () const [inline], [private]
Definition at line 2903 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_fileDef->getNamespaces().size());
      for (const auto &nd : m_fileDef->getNamespaces())
      {
        if (nd->isLinkable() && !nd->isConstantGroup())
        {
          list.push_back(NamespaceContext::alloc(nd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References NamespaceContext::alloc(), and TemplateImmutableList::alloc().
createSequences() [1/2]
TemplateVariant FileContext::Private::createSequences () const [inline], [private]
Definition at line 2943 of file context.cpp.
    {
      return createMemberList(MemberListType_decSequenceMembers,theTranslator->trSequences());
    }
References createMemberList(), MemberListType_decSequenceMembers, theTranslator, and Translator::trSequences().
createSequences() [2/2]
TemplateVariant FileContext::Private::createSequences () const [inline], [private]
Definition at line 2943 of file context.cpp.
    {
      return createMemberList(MemberListType_decSequenceMembers,theTranslator->trSequences());
    }
References MemberListType_decSequenceMembers, theTranslator, and Translator::trSequences().
createSources() [1/2]
TemplateVariant FileContext::Private::createSources () const [inline], [private]
Definition at line 2884 of file context.cpp.
    {
      return m_fileDef->generateSourceFile() ?
          TemplateVariant(parseCode(m_fileDef,relPathAsString())) :
          TemplateVariant("");
    }
References FileDef::generateSourceFile(), m_fileDef, parseCode(), and DefinitionContext< FileContext::Private >::relPathAsString().
createSources() [2/2]
TemplateVariant FileContext::Private::createSources () const [inline], [private]
Definition at line 2884 of file context.cpp.
    {
      return m_fileDef->generateSourceFile() ?
          TemplateVariant(parseCode(m_fileDef,relPathAsString())) :
          TemplateVariant("");
    }
References parseCode().
createTypedefs() [1/2]
TemplateVariant FileContext::Private::createTypedefs () const [inline], [private]
Definition at line 2939 of file context.cpp.
    {
      return createMemberList(MemberListType_decTypedefMembers,theTranslator->trTypedefs());
    }
References createMemberList(), MemberListType_decTypedefMembers, theTranslator, and Translator::trTypedefs().
createTypedefs() [2/2]
TemplateVariant FileContext::Private::createTypedefs () const [inline], [private]
Definition at line 2939 of file context.cpp.
    {
      return createMemberList(MemberListType_decTypedefMembers,theTranslator->trTypedefs());
    }
References MemberListType_decTypedefMembers, theTranslator, and Translator::trTypedefs().
createVariables() [1/2]
TemplateVariant FileContext::Private::createVariables () const [inline], [private]
Definition at line 2962 of file context.cpp.
    {
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      return createMemberList(MemberListType_decVarMembers, sliceOpt ? theTranslator->trConstants() :
                                                                       theTranslator->trVariables());
    }
References Config_getBool, createMemberList(), MemberListType_decVarMembers, theTranslator, Translator::trConstants(), and Translator::trVariables().
createVariables() [2/2]
TemplateVariant FileContext::Private::createVariables () const [inline], [private]
Definition at line 2962 of file context.cpp.
    {
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      return createMemberList(MemberListType_decVarMembers, sliceOpt ? theTranslator->trConstants() :
                                                                       theTranslator->trVariables());
    }
References Config_getBool, MemberListType_decVarMembers, theTranslator, Translator::trConstants(), and Translator::trVariables().
detailedDictionaries() [1/2]
TemplateVariant FileContext::Private::detailedDictionaries () const [inline]
Definition at line 2774 of file context.cpp.
{ return m_cachable.detailedDictionaries.get(this); }
References FileContext::Private::Cachable::detailedDictionaries, and m_cachable.
detailedDictionaries() [2/2]
TemplateVariant FileContext::Private::detailedDictionaries () const [inline]
Definition at line 2774 of file context.cpp.
{ return m_cachable.detailedDictionaries.get(this); }
detailedEnums() [1/2]
TemplateVariant FileContext::Private::detailedEnums () const [inline]
Definition at line 2775 of file context.cpp.
{ return m_cachable.detailedEnums.get(this); }
References FileContext::Private::Cachable::detailedEnums, and m_cachable.
detailedEnums() [2/2]
TemplateVariant FileContext::Private::detailedEnums () const [inline]
Definition at line 2775 of file context.cpp.
{ return m_cachable.detailedEnums.get(this); }
detailedFunctions() [1/2]
TemplateVariant FileContext::Private::detailedFunctions () const [inline]
Definition at line 2776 of file context.cpp.
{ return m_cachable.detailedFunctions.get(this); }
References FileContext::Private::Cachable::detailedFunctions, and m_cachable.
detailedFunctions() [2/2]
TemplateVariant FileContext::Private::detailedFunctions () const [inline]
Definition at line 2776 of file context.cpp.
{ return m_cachable.detailedFunctions.get(this); }
detailedMacros() [1/2]
TemplateVariant FileContext::Private::detailedMacros () const [inline]
Definition at line 2771 of file context.cpp.
{ return m_cachable.detailedMacros.get(this); }
References FileContext::Private::Cachable::detailedMacros, and m_cachable.
detailedMacros() [2/2]
TemplateVariant FileContext::Private::detailedMacros () const [inline]
Definition at line 2771 of file context.cpp.
{ return m_cachable.detailedMacros.get(this); }
detailedSequences() [1/2]
TemplateVariant FileContext::Private::detailedSequences () const [inline]
Definition at line 2773 of file context.cpp.
{ return m_cachable.detailedSequences.get(this); }
References FileContext::Private::Cachable::detailedSequences, and m_cachable.
detailedSequences() [2/2]
TemplateVariant FileContext::Private::detailedSequences () const [inline]
Definition at line 2773 of file context.cpp.
{ return m_cachable.detailedSequences.get(this); }
detailedTypedefs() [1/2]
TemplateVariant FileContext::Private::detailedTypedefs () const [inline]
Definition at line 2772 of file context.cpp.
{ return m_cachable.detailedTypedefs.get(this); }
References FileContext::Private::Cachable::detailedTypedefs, and m_cachable.
detailedTypedefs() [2/2]
TemplateVariant FileContext::Private::detailedTypedefs () const [inline]
Definition at line 2772 of file context.cpp.
{ return m_cachable.detailedTypedefs.get(this); }
detailedVariables() [1/2]
TemplateVariant FileContext::Private::detailedVariables () const [inline]
Definition at line 2777 of file context.cpp.
{ return m_cachable.detailedVariables.get(this); }
References FileContext::Private::Cachable::detailedVariables, and m_cachable.
detailedVariables() [2/2]
TemplateVariant FileContext::Private::detailedVariables () const [inline]
Definition at line 2777 of file context.cpp.
{ return m_cachable.detailedVariables.get(this); }
dictionaries() [1/2]
TemplateVariant FileContext::Private::dictionaries () const [inline]
Definition at line 2766 of file context.cpp.
{ return m_cachable.dictionaries.get(this); }
References FileContext::Private::Cachable::dictionaries, and m_cachable.
dictionaries() [2/2]
TemplateVariant FileContext::Private::dictionaries () const [inline]
Definition at line 2766 of file context.cpp.
{ return m_cachable.dictionaries.get(this); }
enums() [1/2]
TemplateVariant FileContext::Private::enums () const [inline]
Definition at line 2767 of file context.cpp.
{ return m_cachable.enums.get(this); }
References FileContext::Private::Cachable::enums, and m_cachable.
enums() [2/2]
TemplateVariant FileContext::Private::enums () const [inline]
Definition at line 2767 of file context.cpp.
{ return m_cachable.enums.get(this); }
fields() [1/2]
StringVector FileContext::Private::fields () const [inline]
Definition at line 2748 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector FileContext::Private::fields () const [inline]
Definition at line 2748 of file context.cpp.
{ return s_inst.fields(); }
functions() [1/2]
TemplateVariant FileContext::Private::functions () const [inline]
Definition at line 2768 of file context.cpp.
{ return m_cachable.functions.get(this); }
References FileContext::Private::Cachable::functions, and m_cachable.
functions() [2/2]
TemplateVariant FileContext::Private::functions () const [inline]
Definition at line 2768 of file context.cpp.
{ return m_cachable.functions.get(this); }
get() [1/2]
TemplateVariant FileContext::Private::get (const QCString & n) const [inline]
Definition at line 2747 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant FileContext::Private::get (const QCString & n) const [inline]
Definition at line 2747 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
getIncludedByGraph() [1/2]
DotInclDepGraphPtr FileContext::Private::getIncludedByGraph () const [inline]
Definition at line 2781 of file context.cpp.
{ return m_cachable.includedByGraph.get(this); }
References FileContext::Private::Cachable::includedByGraph, and m_cachable.
Referenced by hasIncludedByGraph(), and includedByGraph().
getIncludedByGraph() [2/2]
DotInclDepGraphPtr FileContext::Private::getIncludedByGraph () const [inline]
Definition at line 2781 of file context.cpp.
{ return m_cachable.includedByGraph.get(this); }
getIncludeGraph() [1/2]
DotInclDepGraphPtr FileContext::Private::getIncludeGraph () const [inline]
Definition at line 2780 of file context.cpp.
{ return m_cachable.includeGraph.get(this); }
References FileContext::Private::Cachable::includeGraph, and m_cachable.
Referenced by hasIncludeGraph(), and includeGraph().
getIncludeGraph() [2/2]
DotInclDepGraphPtr FileContext::Private::getIncludeGraph () const [inline]
Definition at line 2780 of file context.cpp.
{ return m_cachable.includeGraph.get(this); }
hasDetails() [1/2]
TemplateVariant FileContext::Private::hasDetails () const [inline]
Definition at line 2756 of file context.cpp.
{ return m_fileDef->hasDetailedDescription(); }
References FileDef::hasDetailedDescription(), and m_fileDef.
hasDetails() [2/2]
TemplateVariant FileContext::Private::hasDetails () const [inline]
Definition at line 2756 of file context.cpp.
{ return m_fileDef->hasDetailedDescription(); }
hasIncludedByGraph() [1/2]
TemplateVariant FileContext::Private::hasIncludedByGraph () const [inline]
Definition at line 2825 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      DotInclDepGraphPtr incGraph = getIncludedByGraph();
      return (haveDot && !incGraph->isTooBig() && !incGraph->isTrivial());
    }
References Config_getBool, and getIncludedByGraph().
hasIncludedByGraph() [2/2]
TemplateVariant FileContext::Private::hasIncludedByGraph () const [inline]
Definition at line 2825 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      DotInclDepGraphPtr incGraph = getIncludedByGraph();
      return (haveDot && !incGraph->isTooBig() && !incGraph->isTrivial());
    }
References Config_getBool.
hasIncludeGraph() [1/2]
TemplateVariant FileContext::Private::hasIncludeGraph () const [inline]
Definition at line 2783 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      DotInclDepGraphPtr incGraph = getIncludeGraph();
      return (haveDot && !incGraph->isTooBig() && !incGraph->isTrivial());
    }
References Config_getBool, and getIncludeGraph().
hasIncludeGraph() [2/2]
TemplateVariant FileContext::Private::hasIncludeGraph () const [inline]
Definition at line 2783 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      DotInclDepGraphPtr incGraph = getIncludeGraph();
      return (haveDot && !incGraph->isTooBig() && !incGraph->isTrivial());
    }
References Config_getBool.
hasSourceFile() [1/2]
TemplateVariant FileContext::Private::hasSourceFile () const [inline]
Definition at line 2757 of file context.cpp.
{ return m_fileDef->generateSourceFile(); }
References FileDef::generateSourceFile(), and m_fileDef.
hasSourceFile() [2/2]
TemplateVariant FileContext::Private::hasSourceFile () const [inline]
Definition at line 2757 of file context.cpp.
{ return m_fileDef->generateSourceFile(); }
highlight() [1/2]
TemplateVariant FileContext::Private::highlight () const [inline]
Definition at line 2752 of file context.cpp.
{ return TemplateVariant("files"); }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant FileContext::Private::highlight () const [inline]
Definition at line 2752 of file context.cpp.
{ return TemplateVariant("files"); }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
includedByGraph() [1/2]
TemplateVariant FileContext::Private::includedByGraph () const [inline]
Definition at line 2831 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      TextStream t;
      if (haveDot)
      {
        DotInclDepGraphPtr cg = getIncludedByGraph();
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              cg->writeGraph(t,GOF_BITMAP,EOF_Html,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_fileDef->getOutputFileBase()),
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
          case ContextOutputFormat_Latex:
            {
              cg->writeGraph(t,GOF_EPS,EOF_LaTeX,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+m_fileDef->getOutputFileBase()+".tex",
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References addHtmlExtensionIfMissing(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, getIncludedByGraph(), FileDef::getOutputFileBase(), GOF_BITMAP, GOF_EPS, m_fileDef, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), DefinitionContext< FileContext::Private >::relPathAsString(), TextStream::str(), and TRUE.
includedByGraph() [2/2]
TemplateVariant FileContext::Private::includedByGraph () const [inline]
Definition at line 2831 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      TextStream t;
      if (haveDot)
      {
        DotInclDepGraphPtr cg = getIncludedByGraph();
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              cg->writeGraph(t,GOF_BITMAP,EOF_Html,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_fileDef->getOutputFileBase()),
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
          case ContextOutputFormat_Latex:
            {
              cg->writeGraph(t,GOF_EPS,EOF_LaTeX,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+m_fileDef->getOutputFileBase()+".tex",
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References addHtmlExtensionIfMissing(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, GOF_BITMAP, GOF_EPS, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), TextStream::str(), and TRUE.
includeGraph() [1/2]
TemplateVariant FileContext::Private::includeGraph () const [inline]
Definition at line 2789 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      TextStream t;
      if (haveDot)
      {
        DotInclDepGraphPtr cg = getIncludeGraph();
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              cg->writeGraph(t,GOF_BITMAP,EOF_Html,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_fileDef->getOutputFileBase()),
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
          case ContextOutputFormat_Latex:
            {
              cg->writeGraph(t,GOF_EPS,EOF_LaTeX,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+m_fileDef->getOutputFileBase()+".tex",
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References addHtmlExtensionIfMissing(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, getIncludeGraph(), FileDef::getOutputFileBase(), GOF_BITMAP, GOF_EPS, m_fileDef, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), DefinitionContext< FileContext::Private >::relPathAsString(), TextStream::str(), and TRUE.
includeGraph() [2/2]
TemplateVariant FileContext::Private::includeGraph () const [inline]
Definition at line 2789 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      TextStream t;
      if (haveDot)
      {
        DotInclDepGraphPtr cg = getIncludeGraph();
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              cg->writeGraph(t,GOF_BITMAP,EOF_Html,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_fileDef->getOutputFileBase()),
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
          case ContextOutputFormat_Latex:
            {
              cg->writeGraph(t,GOF_EPS,EOF_LaTeX,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+m_fileDef->getOutputFileBase()+".tex",
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References addHtmlExtensionIfMissing(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, GOF_BITMAP, GOF_EPS, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), TextStream::str(), and TRUE.
includeList() [1/2]
TemplateVariant FileContext::Private::includeList () const [inline]
Definition at line 2755 of file context.cpp.
{ return m_cachable.includeList.get(this); }
References FileContext::Private::Cachable::includeList, and m_cachable.
includeList() [2/2]
TemplateVariant FileContext::Private::includeList () const [inline]
Definition at line 2755 of file context.cpp.
{ return m_cachable.includeList.get(this); }
inlineClasses() [1/2]
TemplateVariant FileContext::Private::inlineClasses () const [inline]
Definition at line 2778 of file context.cpp.
{ return m_cachable.inlineClasses.get(this); }
References FileContext::Private::Cachable::inlineClasses, and m_cachable.
inlineClasses() [2/2]
TemplateVariant FileContext::Private::inlineClasses () const [inline]
Definition at line 2778 of file context.cpp.
{ return m_cachable.inlineClasses.get(this); }
macros() [1/2]
TemplateVariant FileContext::Private::macros () const [inline]
Definition at line 2763 of file context.cpp.
{ return m_cachable.macros.get(this); }
References m_cachable, and FileContext::Private::Cachable::macros.
macros() [2/2]
TemplateVariant FileContext::Private::macros () const [inline]
Definition at line 2763 of file context.cpp.
{ return m_cachable.macros.get(this); }
memberGroups() [1/2]
TemplateVariant FileContext::Private::memberGroups () const [inline]
Definition at line 2770 of file context.cpp.
{ return m_cachable.memberGroups.get(this); }
References m_cachable, and FileContext::Private::Cachable::memberGroups.
memberGroups() [2/2]
TemplateVariant FileContext::Private::memberGroups () const [inline]
Definition at line 2770 of file context.cpp.
{ return m_cachable.memberGroups.get(this); }
namespaces() [1/2]
TemplateVariant FileContext::Private::namespaces () const [inline]
Definition at line 2761 of file context.cpp.
{ return m_cachable.namespaces.get(this); }
References m_cachable, and FileContext::Private::Cachable::namespaces.
namespaces() [2/2]
TemplateVariant FileContext::Private::namespaces () const [inline]
Definition at line 2761 of file context.cpp.
{ return m_cachable.namespaces.get(this); }
sequences() [1/2]
TemplateVariant FileContext::Private::sequences () const [inline]
Definition at line 2765 of file context.cpp.
{ return m_cachable.sequences.get(this); }
References m_cachable, and FileContext::Private::Cachable::sequences.
sequences() [2/2]
TemplateVariant FileContext::Private::sequences () const [inline]
Definition at line 2765 of file context.cpp.
{ return m_cachable.sequences.get(this); }
sources() [1/2]
TemplateVariant FileContext::Private::sources () const [inline]
Definition at line 2758 of file context.cpp.
{ return m_cachable.sources.get(this); }
References m_cachable, and FileContext::Private::Cachable::sources.
sources() [2/2]
TemplateVariant FileContext::Private::sources () const [inline]
Definition at line 2758 of file context.cpp.
{ return m_cachable.sources.get(this); }
subHighlight() [1/2]
TemplateVariant FileContext::Private::subHighlight () const [inline]
Definition at line 2753 of file context.cpp.
{ return TemplateVariant(""); }
subHighlight() [2/2]
TemplateVariant FileContext::Private::subHighlight () const [inline]
Definition at line 2753 of file context.cpp.
{ return TemplateVariant(""); }
title() [1/2]
TemplateVariant FileContext::Private::title () const [inline]
Definition at line 2751 of file context.cpp.
{ return m_fileDef->title(); }
References m_fileDef, and FileDef::title().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), createMemberList(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant FileContext::Private::title () const [inline]
Definition at line 2751 of file context.cpp.
{ return m_fileDef->title(); }
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
typedefs() [1/2]
TemplateVariant FileContext::Private::typedefs () const [inline]
Definition at line 2764 of file context.cpp.
{ return m_cachable.typedefs.get(this); }
References m_cachable, and FileContext::Private::Cachable::typedefs.
typedefs() [2/2]
TemplateVariant FileContext::Private::typedefs () const [inline]
Definition at line 2764 of file context.cpp.
{ return m_cachable.typedefs.get(this); }
variables() [1/2]
TemplateVariant FileContext::Private::variables () const [inline]
Definition at line 2769 of file context.cpp.
{ return m_cachable.variables.get(this); }
References m_cachable, and FileContext::Private::Cachable::variables.
variables() [2/2]
TemplateVariant FileContext::Private::variables () const [inline]
Definition at line 2769 of file context.cpp.
{ return m_cachable.variables.get(this); }
version() [1/2]
TemplateVariant FileContext::Private::version () const [inline]
Definition at line 2759 of file context.cpp.
{ return m_fileDef->fileVersion(); }
References FileDef::fileVersion(), and m_fileDef.
Referenced by doxmlparser.index.DoxygenType::__init__(), doxmlparser.compound.DoxygenType::__init__(), doxmlparser.compound.DoxygenType::buildAttributes(), doxmlparser.index.DoxygenType::buildAttributes(), doxmlparser.compound.DoxygenType::exportAttributes(), doxmlparser.index.DoxygenType::exportAttributes(), doxmlparser.compound.DoxygenType::get_version(), doxmlparser.index.DoxygenType::get_version(), doxmlparser.compound.DoxygenType::set_version(), and doxmlparser.index.DoxygenType::set_version().
version() [2/2]
TemplateVariant FileContext::Private::version () const [inline]
Definition at line 2759 of file context.cpp.
{ return m_fileDef->fileVersion(); }
Referenced by doxmlparser.index.DoxygenType::__init__(), doxmlparser.compound.DoxygenType::__init__(), doxmlparser.compound.DoxygenType::buildAttributes(), doxmlparser.index.DoxygenType::buildAttributes(), doxmlparser.compound.DoxygenType::exportAttributes(), doxmlparser.index.DoxygenType::exportAttributes(), doxmlparser.compound.DoxygenType::get_version(), doxmlparser.index.DoxygenType::get_version(), doxmlparser.compound.DoxygenType::set_version(), and doxmlparser.index.DoxygenType::set_version().
versionInfo() [1/2]
TemplateVariant FileContext::Private::versionInfo () const [inline]
Definition at line 2754 of file context.cpp.
{ return m_fileDef->getVersion(); }
References FileDef::getVersion(), and m_fileDef.
versionInfo() [2/2]
TemplateVariant FileContext::Private::versionInfo () const [inline]
Definition at line 2754 of file context.cpp.
{ return m_fileDef->getVersion(); }
Member Data Documentation
m_cachable
Cachable FileContext::Private::m_cachable [private]
Definition at line 3048 of file context.cpp.
Referenced by classes(), constantgroups(), detailedDictionaries(), detailedEnums(), detailedFunctions(), detailedMacros(), detailedSequences(), detailedTypedefs(), detailedVariables(), dictionaries(), enums(), functions(), getIncludedByGraph(), getIncludeGraph(), includeList(), inlineClasses(), macros(), memberGroups(), namespaces(), sequences(), sources(), typedefs(), and variables().
m_fileDef
const FileDef * FileContext::Private::m_fileDef [private]
Definition at line 3021 of file context.cpp.
Referenced by createClasses(), createConstantgroups(), createDetailedFunctions(), createFunctions(), createIncludedByGraph(), createIncludeGraph(), createIncludeList(), createInlineClasses(), createMemberGroups(), createMemberList(), createNamespaces(), createSources(), hasDetails(), hasSourceFile(), includedByGraph(), includeGraph(), title(), version(), and versionInfo().
s_inst
const PropertyMap< FileContext::Private > FileContext::Private::s_inst [static], [private]
Definition at line 3049 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp