TranslatorPortuguese Class Reference
#include <translator_pt.h>
Public Member Functions
QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const QCString &s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const QCString &date, const QCString &projName)
QCString trClassDiagram (const QCString &clName)
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString trPackageList ()
virtual QCString trFlowchart ()
QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const QCString &s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const QCString &date, const QCString &projName)
QCString trClassDiagram (const QCString &clName)
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString trPackageList ()
virtual QCString trFlowchart ()
Detailed Description
Definition at line 72 of file translator_pt.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorPortuguese::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 111 of file translator_pt.h.
    {
      return "0x816 Portuguese(Portugal)";
    }
getLanguageString() [2/2]
virtual QCString TranslatorPortuguese::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 111 of file translator_pt.h.
    {
      return "0x816 Portuguese(Portugal)";
    }
idLanguage() [1/2]
QCString TranslatorPortuguese::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 84 of file translator_pt.h.
    { return "portuguese"; }
idLanguage() [2/2]
QCString TranslatorPortuguese::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 84 of file translator_pt.h.
    { return "portuguese"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorPortuguese::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 101 of file translator_pt.h.
    {
      return
        "\\usepackage[portuges]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorPortuguese::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 101 of file translator_pt.h.
    {
      return
        "\\usepackage[portuges]{babel}\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorPortuguese::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1940 of file translator_pt.h.
    { return "Outros membros herdados"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorPortuguese::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1940 of file translator_pt.h.
    { return "Outros membros herdados"; }
trAll() [1/2]
virtual QCString TranslatorPortuguese::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1434 of file translator_pt.h.
    {
      return "Tudo";
    }
trAll() [2/2]
virtual QCString TranslatorPortuguese::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1434 of file translator_pt.h.
    {
      return "Tudo";
    }
trAndMore() [1/2]
virtual QCString TranslatorPortuguese::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1912 of file translator_pt.h.
    { return "e "+number+" mais..."; }
trAndMore() [2/2]
virtual QCString TranslatorPortuguese::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1912 of file translator_pt.h.
    { return "e "+number+" mais..."; }
trAttention() [1/2]
virtual QCString TranslatorPortuguese::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1005 of file translator_pt.h.
    {
      return "Ateno";
    }
trAttention() [2/2]
virtual QCString TranslatorPortuguese::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1005 of file translator_pt.h.
    {
      return "Ateno";
    }
trAuthor() [1/2]
virtual QCString TranslatorPortuguese::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1305 of file translator_pt.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      if (!singular) result+="es";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorPortuguese::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1305 of file translator_pt.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      if (!singular) result+="es";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorPortuguese::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1163 of file translator_pt.h.
    {
      return "Bug";
    }
trBug() [2/2]
virtual QCString TranslatorPortuguese::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1163 of file translator_pt.h.
    {
      return "Bug";
    }
trBugList() [1/2]
virtual QCString TranslatorPortuguese::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1168 of file translator_pt.h.
    {
      return "Lista de Bugs";
    }
trBugList() [2/2]
virtual QCString TranslatorPortuguese::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1168 of file translator_pt.h.
    {
      return "Lista de Bugs";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorPortuguese::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1558 of file translator_pt.h.
    {
      return "Este o diagrama das funes que utilizam esta funo:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorPortuguese::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1558 of file translator_pt.h.
    {
      return "Este o diagrama das funes que utilizam esta funo:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorPortuguese::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1439 of file translator_pt.h.
    {
      return "Grafo de chamadas desta funo:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorPortuguese::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1439 of file translator_pt.h.
    {
      return "Grafo de chamadas desta funo:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorPortuguese::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1884 of file translator_pt.h.
    { return "Referncias Bibliogrficas"; }
trCiteReferences() [2/2]
virtual QCString TranslatorPortuguese::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1884 of file translator_pt.h.
    { return "Referncias Bibliogrficas"; }
trClass() [1/2]
virtual QCString TranslatorPortuguese::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1226 of file translator_pt.h.
    {
      QCString result((first_capital ? "Classe" : "classe"));
      if (!singular) result+="s";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorPortuguese::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1226 of file translator_pt.h.
    {
      QCString result((first_capital ? "Classe" : "classe"));
      if (!singular) result+="s";
      return result;
    }
trClassDiagram() [1/2]
QCString TranslatorPortuguese::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 553 of file translator_pt.h.
    {
      return "Diagrama de heranas da classe "+clName;
    }
trClassDiagram() [2/2]
QCString TranslatorPortuguese::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 553 of file translator_pt.h.
    {
      return "Diagrama de heranas da classe "+clName;
    }
trClassDocumentation() [1/2]
QCString TranslatorPortuguese::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 428 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentao da estruturas de dados";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentao da classe";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClassDocumentation() [2/2]
QCString TranslatorPortuguese::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 428 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentao da estruturas de dados";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentao da classe";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorPortuguese::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1126 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de dados";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorPortuguese::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1126 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de dados";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
QCString TranslatorPortuguese::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 215 of file translator_pt.h.
    { return "Hierarquia de classes"; }
trClassHierarchy() [2/2]
QCString TranslatorPortuguese::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 215 of file translator_pt.h.
    { return "Hierarquia de classes"; }
trClassHierarchyDescription() [1/2]
QCString TranslatorPortuguese::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 274 of file translator_pt.h.
    { return "Esta lista de heranas est organizada, dentro do possvel, por ordem alfabtica:"; }
trClassHierarchyDescription() [2/2]
QCString TranslatorPortuguese::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 274 of file translator_pt.h.
    { return "Esta lista de heranas est organizada, dentro do possvel, por ordem alfabtica:"; }
trClassMethods() [1/2]
virtual QCString TranslatorPortuguese::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1978 of file translator_pt.h.
    {
      return "Mtodos de classe";
    }
trClassMethods() [2/2]
virtual QCString TranslatorPortuguese::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1978 of file translator_pt.h.
    {
      return "Mtodos de classe";
    }
trCode() [1/2]
virtual QCString TranslatorPortuguese::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 905 of file translator_pt.h.
    {
      return "cdigo";
    }
trCode() [2/2]
virtual QCString TranslatorPortuguese::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 905 of file translator_pt.h.
    {
      return "cdigo";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorPortuguese::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 860 of file translator_pt.h.
    {
      return "Diagrama de colaborao para "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorPortuguese::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 860 of file translator_pt.h.
    {
      return "Diagrama de colaborao para "+clName+":";
    }
trCompoundIndex() [1/2]
QCString TranslatorPortuguese::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 401 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "ndice das estruturas de dados";
      }
      else
      {
        return "ndice dos componentes";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
QCString TranslatorPortuguese::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 401 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "ndice das estruturas de dados";
      }
      else
      {
        return "ndice dos componentes";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorPortuguese::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1610 of file translator_pt.h.
    { return "ndice de Tipos de Dados"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorPortuguese::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1610 of file translator_pt.h.
    { return "ndice de Tipos de Dados"; }
trCompoundList() [1/2]
QCString TranslatorPortuguese::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 219 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de dados";
      }
      else
      {
        return "Lista de componentes";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
QCString TranslatorPortuguese::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 219 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de dados";
      }
      else
      {
        return "Lista de componentes";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
QCString TranslatorPortuguese::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 287 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lista das estruturas de dados com uma breve descrio:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Lista de classes com uma breve descrio:";
      }
      else
      {
        return "Lista de classes, estruturas, unies e interfaces com uma breve descrio:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
QCString TranslatorPortuguese::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 287 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lista das estruturas de dados com uma breve descrio:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Lista de classes com uma breve descrio:";
      }
      else
      {
        return "Lista de classes, estruturas, unies e interfaces com uma breve descrio:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorPortuguese::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1587 of file translator_pt.h.
    { return "Aqui esto os tipos de dados com descries resumidas:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorPortuguese::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1587 of file translator_pt.h.
    { return "Aqui esto os tipos de dados com descries resumidas:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorPortuguese::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1579 of file translator_pt.h.
    { return "Lista de Tipos de Dados"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorPortuguese::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1579 of file translator_pt.h.
    { return "Lista de Tipos de Dados"; }
trCompoundMembers() [1/2]
QCString TranslatorPortuguese::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 236 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de dados";
      }
      else
      {
        return "Componentes membro";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
QCString TranslatorPortuguese::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 236 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de dados";
      }
      else
      {
        return "Componentes membro";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
QCString TranslatorPortuguese::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 304 of file translator_pt.h.
    {
      QCString result="Lista de todas as";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" estruturas e campos de unies";
      }
      else
      {
        result+=" classes membro";
      }
      if (!extractAll)
      {
        result+=" documentadas";
      }
      result+=" com referncia para ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a respectiva documentao:";
        }
        else
        {
          result+="a documentao de cada membro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="as estruturas/unies a que pertencem:";
        }
        else
        {
          result+="as classes a que pertencem:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
QCString TranslatorPortuguese::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 304 of file translator_pt.h.
    {
      QCString result="Lista de todas as";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" estruturas e campos de unies";
      }
      else
      {
        result+=" classes membro";
      }
      if (!extractAll)
      {
        result+=" documentadas";
      }
      result+=" com referncia para ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a respectiva documentao:";
        }
        else
        {
          result+="a documentao de cada membro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="as estruturas/unies a que pertencem:";
        }
        else
        {
          result+="as classes a que pertencem:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorPortuguese::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1591 of file translator_pt.h.
    {
      QCString result="Esta a lista de todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="dos tipos de dados com links para ";
      if (extractAll)
      {
        result+="a documentao dos tipos de dados para cada membro:";
      }
      else
      {
        result+="os tipos de dados a que pertencem:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorPortuguese::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1591 of file translator_pt.h.
    {
      QCString result="Esta a lista de todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="dos tipos de dados com links para ";
      if (extractAll)
      {
        result+="a documentao dos tipos de dados para cada membro:";
      }
      else
      {
        result+="os tipos de dados a que pertencem:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorPortuguese::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1583 of file translator_pt.h.
    { return "Campos de Dados"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorPortuguese::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1583 of file translator_pt.h.
    { return "Campos de Dados"; }
trCompoundReference() [1/2]
virtual QCString TranslatorPortuguese::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 628 of file translator_pt.h.
    {
      QCString result="Referncia ";
      switch(compType)
      {
        case ClassDef::Class: result+=" classe "; break;
        case ClassDef::Struct: result+=" estrutura "; break;
        case ClassDef::Union: result+=" unio "; break;
        case ClassDef::Interface: result+="ao interface "; break;
        case ClassDef::Protocol: result+="ao protocolo "; break;
        case ClassDef::Category: result+=" categoria "; break;
        case ClassDef::Exception: result+=" excepo "; break;
        default: break;
      }
      if (isTemplate) result+="Template ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorPortuguese::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 628 of file translator_pt.h.
    {
      QCString result="Referncia ";
      switch(compType)
      {
        case ClassDef::Class: result+=" classe "; break;
        case ClassDef::Struct: result+=" estrutura "; break;
        case ClassDef::Union: result+=" unio "; break;
        case ClassDef::Interface: result+="ao interface "; break;
        case ClassDef::Protocol: result+="ao protocolo "; break;
        case ClassDef::Category: result+=" categoria "; break;
        case ClassDef::Exception: result+=" excepo "; break;
        default: break;
      }
      if (isTemplate) result+="Template ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorPortuguese::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1651 of file translator_pt.h.
    {
      QCString result = "Referncia ";
      if (isTemplate) result+="da Template ";
      switch(compType)
      {
        case ClassDef::Class: result+="do Modulo "; break;
        case ClassDef::Struct: result+="do Tipo "; break;
        case ClassDef::Union: result+="da Unio "; break;
        case ClassDef::Interface: result+="da Interface "; break;
        case ClassDef::Protocol: result+="do Protocolo "; break;
        case ClassDef::Category: result+="da Categoria "; break;
        case ClassDef::Exception: result+="da Exceo "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorPortuguese::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1651 of file translator_pt.h.
    {
      QCString result = "Referncia ";
      if (isTemplate) result+="da Template ";
      switch(compType)
      {
        case ClassDef::Class: result+="do Modulo "; break;
        case ClassDef::Struct: result+="do Tipo "; break;
        case ClassDef::Union: result+="da Unio "; break;
        case ClassDef::Interface: result+="da Interface "; break;
        case ClassDef::Protocol: result+="do Protocolo "; break;
        case ClassDef::Category: result+="da Categoria "; break;
        case ClassDef::Exception: result+="da Exceo "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorPortuguese::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2281 of file translator_pt.h.
    {
      QCString result="Referncia ";
      switch(compType)
      {
        case ClassDef::Class: result+="da Classe "; break;
        case ClassDef::Struct: result+="da Estrutura "; break;
        case ClassDef::Union: result+="da Unio "; break;
        case ClassDef::Interface: result+="da Interface "; break;
        case ClassDef::Protocol: result+="do Protocolo "; break;
        case ClassDef::Category: result+="da Categoria "; break;
        case ClassDef::Exception: result+="da Exceo "; break;
        default: break;
      }
      if (isLocal) result+="Local ";
      result+= clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorPortuguese::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2281 of file translator_pt.h.
    {
      QCString result="Referncia ";
      switch(compType)
      {
        case ClassDef::Class: result+="da Classe "; break;
        case ClassDef::Struct: result+="da Estrutura "; break;
        case ClassDef::Union: result+="da Unio "; break;
        case ClassDef::Interface: result+="da Interface "; break;
        case ClassDef::Protocol: result+="do Protocolo "; break;
        case ClassDef::Category: result+="da Categoria "; break;
        case ClassDef::Exception: result+="da Exceo "; break;
        default: break;
      }
      if (isLocal) result+="Local ";
      result+= clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
QCString TranslatorPortuguese::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 529 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de Dados";
      }
      else
      {
        return "Componentes";
      }
    }
References Config_getBool.
trCompounds() [2/2]
QCString TranslatorPortuguese::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 529 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de Dados";
      }
      else
      {
        return "Componentes";
      }
    }
References Config_getBool.
trConcept() [1/2]
virtual QCString TranslatorPortuguese::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2331 of file translator_pt.h.
    {
        QCString result((first_capital ? "Conceito" : "conceito"));
        if (!singular) result+="s";
        return result;
    }
trConcept() [2/2]
virtual QCString TranslatorPortuguese::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2331 of file translator_pt.h.
    {
        QCString result((first_capital ? "Conceito" : "conceito"));
        if (!singular) result+="s";
        return result;
    }
trConceptDefinition() [1/2]
virtual QCString TranslatorPortuguese::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2367 of file translator_pt.h.
    {
        return "Definio de conceito";
    }
trConceptDefinition() [2/2]
virtual QCString TranslatorPortuguese::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2367 of file translator_pt.h.
    {
        return "Definio de conceito";
    }
trConceptDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2354 of file translator_pt.h.
    { return "Documentao do Conceito"; }
trConceptDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2354 of file translator_pt.h.
    { return "Documentao do Conceito"; }
trConceptIndex() [1/2]
virtual QCString TranslatorPortuguese::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2350 of file translator_pt.h.
    { return "ndice de Conceitos"; }
trConceptIndex() [2/2]
virtual QCString TranslatorPortuguese::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2350 of file translator_pt.h.
    { return "ndice de Conceitos"; }
trConceptList() [1/2]
virtual QCString TranslatorPortuguese::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2346 of file translator_pt.h.
    { return "Lista de Conceitos"; }
trConceptList() [2/2]
virtual QCString TranslatorPortuguese::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2346 of file translator_pt.h.
    { return "Lista de Conceitos"; }
trConceptListDescription() [1/2]
virtual QCString TranslatorPortuguese::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2358 of file translator_pt.h.
    {
        QCString result="Esta a lista de todos os conceitos ";
        if (!extractAll) result+="documentados ";
        result+="com suas respectivas descries:";
        return result;
    }
trConceptListDescription() [2/2]
virtual QCString TranslatorPortuguese::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2358 of file translator_pt.h.
    {
        QCString result="Esta a lista de todos os conceitos ";
        if (!extractAll) result+="documentados ";
        result+="com suas respectivas descries:";
        return result;
    }
trConceptReference() [1/2]
virtual QCString TranslatorPortuguese::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2338 of file translator_pt.h.
    {
        QCString result= "Referncia do Conceito ";
        result+=conceptName;
        return result;
    }
trConceptReference() [2/2]
virtual QCString TranslatorPortuguese::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2338 of file translator_pt.h.
    {
        QCString result= "Referncia do Conceito ";
        result+=conceptName;
        return result;
    }
trConstantDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2189 of file translator_pt.h.
    {
        return "Constantes";
    }
trConstantDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2189 of file translator_pt.h.
    {
        return "Constantes";
    }
trConstantGroupReference() [1/2]
virtual QCString TranslatorPortuguese::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2015 of file translator_pt.h.
    {
      QCString result = "Referncia do grupo de constantes ";
      result += namespaceName;
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorPortuguese::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2015 of file translator_pt.h.
    {
      QCString result = "Referncia do grupo de constantes ";
      result += namespaceName;
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorPortuguese::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2011 of file translator_pt.h.
    { return "Grupos de Constantes"; }
trConstantGroups() [2/2]
virtual QCString TranslatorPortuguese::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2011 of file translator_pt.h.
    { return "Grupos de Constantes"; }
trConstants() [1/2]
virtual QCString TranslatorPortuguese::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2185 of file translator_pt.h.
    {
        return "Constantes";
    }
trConstants() [2/2]
virtual QCString TranslatorPortuguese::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2185 of file translator_pt.h.
    {
        return "Constantes";
    }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 870 of file translator_pt.h.
    {
      return "Documentao dos Construtores & Destrutor";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 870 of file translator_pt.h.
    {
      return "Documentao dos Construtores & Destrutor";
    }
trCopyright() [1/2]
virtual QCString TranslatorPortuguese::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1888 of file translator_pt.h.
    {
      // Note: I will left it as is because "Direitos de autor" may not fit
      // in the text.
      return "Copyright";
    }
trCopyright() [2/2]
virtual QCString TranslatorPortuguese::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1888 of file translator_pt.h.
    {
      // Note: I will left it as is because "Direitos de autor" may not fit
      // in the text.
      return "Copyright";
    }
trCustomReference() [1/2]
virtual QCString TranslatorPortuguese::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2181 of file translator_pt.h.
    { return "Referncia de " + QCString(name); }
References setup::name.
trCustomReference() [2/2]
virtual QCString TranslatorPortuguese::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2181 of file translator_pt.h.
    { return "Referncia de " + QCString(name); }
References setup::name.
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2311 of file translator_pt.h.
    {
        return "Dados Membros";
    }
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2311 of file translator_pt.h.
    {
        return "Dados Membros";
    }
trDataMembers() [1/2]
virtual QCString TranslatorPortuguese::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2307 of file translator_pt.h.
    {
        return "Dados Membros";
    }
trDataMembers() [2/2]
virtual QCString TranslatorPortuguese::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2307 of file translator_pt.h.
    {
        return "Dados Membros";
    }
trDataTypes() [1/2]
virtual QCString TranslatorPortuguese::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1634 of file translator_pt.h.
    { return "Tipos de Dados"; }
trDataTypes() [2/2]
virtual QCString TranslatorPortuguese::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1634 of file translator_pt.h.
    { return "Tipos de Dados"; }
trDate() [1/2]
QCString TranslatorPortuguese::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 567 of file translator_pt.h.
    { return "Data"; }
trDate() [2/2]
QCString TranslatorPortuguese::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 567 of file translator_pt.h.
    { return "Data"; }
trDateTime() [1/2]
virtual QCString TranslatorPortuguese::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1841 of file translator_pt.h.
    {
      static const char *days[] = { "Segunda","Tera","Quarta","Quinta","Sexta","Sbado","Domingo" };
      static const char *months[] = { "Janeiro","Fevereiro","Maro","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro" };
      QCString sdate;
      sdate.sprintf("%s, %d de %s de %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorPortuguese::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1841 of file translator_pt.h.
    {
      static const char *days[] = { "Segunda","Tera","Quarta","Quinta","Sexta","Sbado","Domingo" };
      static const char *months[] = { "Janeiro","Fevereiro","Maro","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro" };
      QCString sdate;
      sdate.sprintf("%s, %d de %s de %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorPortuguese::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1857 of file translator_pt.h.
    {
      static const char *days_short[] = { "seg", "ter", "qua", "qui", "sex", "sb", "dom" };
      static const char *days_full[] = { "segunda-feira", "tera-feira", "quarta-feira", "quinta-feira", "sexta-feira", "sbado", "domingo" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorPortuguese::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1857 of file translator_pt.h.
    {
      static const char *days_short[] = { "seg", "ter", "qua", "qui", "sex", "sb", "dom" };
      static const char *days_full[] = { "segunda-feira", "tera-feira", "quarta-feira", "quinta-feira", "sexta-feira", "sbado", "domingo" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorPortuguese::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1873 of file translator_pt.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorPortuguese::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1873 of file translator_pt.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorPortuguese::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 837 of file translator_pt.h.
    {
      return "Definido na linha @0 do ficheiro @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorPortuguese::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 837 of file translator_pt.h.
    {
      return "Definido na linha @0 do ficheiro @1.";
    }
trDefinedIn() [1/2]
QCString TranslatorPortuguese::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 203 of file translator_pt.h.
    { return "definido em"; }
trDefinedIn() [2/2]
QCString TranslatorPortuguese::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 203 of file translator_pt.h.
    { return "definido em"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorPortuguese::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 841 of file translator_pt.h.
    {
      return "Definido no ficheiro @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorPortuguese::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 841 of file translator_pt.h.
    {
      return "Definido no ficheiro @0.";
    }
trDefineDocumentation() [1/2]
QCString TranslatorPortuguese::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 499 of file translator_pt.h.
    { return "Documentao das macros"; }
trDefineDocumentation() [2/2]
QCString TranslatorPortuguese::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 499 of file translator_pt.h.
    { return "Documentao das macros"; }
trDefines() [1/2]
QCString TranslatorPortuguese::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 463 of file translator_pt.h.
    { return "Macros"; }
trDefines() [2/2]
QCString TranslatorPortuguese::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 463 of file translator_pt.h.
    { return "Macros"; }
trDefineValue() [1/2]
virtual QCString TranslatorPortuguese::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1153 of file translator_pt.h.
    {
      return "Valor:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorPortuguese::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1153 of file translator_pt.h.
    {
      return "Valor:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorPortuguese::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 850 of file translator_pt.h.
    {
      return "Desaprovado";
    }
trDeprecated() [2/2]
virtual QCString TranslatorPortuguese::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 850 of file translator_pt.h.
    {
      return "Desaprovado";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorPortuguese::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1362 of file translator_pt.h.
    {
      return "Lista de Deprecados";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorPortuguese::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1362 of file translator_pt.h.
    {
      return "Lista de Deprecados";
    }
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2321 of file translator_pt.h.
    {
        return "Documentao da Unidade de Projeto";
    }
Referenced by trClassDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2321 of file translator_pt.h.
    {
        return "Documentao da Unidade de Projeto";
    }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorPortuguese::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2072 of file translator_pt.h.
    { return "Hierarquia da Unidade de Design"; }
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorPortuguese::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2072 of file translator_pt.h.
    { return "Hierarquia da Unidade de Design"; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorPortuguese::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2087 of file translator_pt.h.
    { return "ndice de Unidades de Design"; }
trDesignUnitIndex() [2/2]
virtual QCString TranslatorPortuguese::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2087 of file translator_pt.h.
    { return "ndice de Unidades de Design"; }
trDesignUnitList() [1/2]
virtual QCString TranslatorPortuguese::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2075 of file translator_pt.h.
    { return "Lista de Unidades de Design"; }
trDesignUnitList() [2/2]
virtual QCString TranslatorPortuguese::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2075 of file translator_pt.h.
    { return "Lista de Unidades de Design"; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorPortuguese::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2081 of file translator_pt.h.
    {
        return "Esta uma lista de todos os membros de unidades de design "
                "com ligaes para as entidades s quais pertencem:";
    }
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorPortuguese::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2081 of file translator_pt.h.
    {
        return "Esta uma lista de todos os membros de unidades de design "
                "com ligaes para as entidades s quais pertencem:";
    }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorPortuguese::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2078 of file translator_pt.h.
    { return "Membros da Unidade de Design"; }
trDesignUnitMembers() [2/2]
virtual QCString TranslatorPortuguese::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2078 of file translator_pt.h.
    { return "Membros da Unidade de Design"; }
trDesignUnits() [1/2]
virtual QCString TranslatorPortuguese::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2090 of file translator_pt.h.
    { return "Unidades de Design"; }
trDesignUnits() [2/2]
virtual QCString TranslatorPortuguese::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2090 of file translator_pt.h.
    { return "Unidades de Design"; }
trDetailedDescription() [1/2]
QCString TranslatorPortuguese::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 127 of file translator_pt.h.
    { return "Descrio detalhada"; }
trDetailedDescription() [2/2]
QCString TranslatorPortuguese::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 127 of file translator_pt.h.
    { return "Descrio detalhada"; }
trDetailLevel() [1/2]
virtual QCString TranslatorPortuguese::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1904 of file translator_pt.h.
    { return "nvel de detalhes"; }
trDetailLevel() [2/2]
virtual QCString TranslatorPortuguese::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1904 of file translator_pt.h.
    { return "nvel de detalhes"; }
trDictionaries() [1/2]
virtual QCString TranslatorPortuguese::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2201 of file translator_pt.h.
    {
        return "Dicionrios";
    }
trDictionaries() [2/2]
virtual QCString TranslatorPortuguese::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2201 of file translator_pt.h.
    {
        return "Dicionrios";
    }
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2205 of file translator_pt.h.
    {
        return "Dicionrios";
    }
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2205 of file translator_pt.h.
    {
        return "Dicionrios";
    }
trDir() [1/2]
virtual QCString TranslatorPortuguese::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1533 of file translator_pt.h.
    {
      QCString result((first_capital ? "Diretrio" : "diretrio"));
      if (!singular) result+="s";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorPortuguese::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1533 of file translator_pt.h.
    {
      QCString result((first_capital ? "Diretrio" : "diretrio"));
      if (!singular) result+="s";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorPortuguese::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1896 of file translator_pt.h.
    { return QCString("Grafo de dependncias do directrio ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorPortuguese::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1896 of file translator_pt.h.
    { return QCString("Grafo de dependncias do directrio ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1511 of file translator_pt.h.
    { return "Documentao do Directrio"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1511 of file translator_pt.h.
    { return "Documentao do Directrio"; }
trDirectories() [1/2]
virtual QCString TranslatorPortuguese::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1517 of file translator_pt.h.
    { return "Diretrios"; }
trDirectories() [2/2]
virtual QCString TranslatorPortuguese::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1517 of file translator_pt.h.
    { return "Diretrios"; }
trDirIndex() [1/2]
virtual QCString TranslatorPortuguese::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1505 of file translator_pt.h.
    { return "Hierarquia de Diretrios"; }
trDirIndex() [2/2]
virtual QCString TranslatorPortuguese::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1505 of file translator_pt.h.
    { return "Hierarquia de Diretrios"; }
trDirReference() [1/2]
virtual QCString TranslatorPortuguese::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1523 of file translator_pt.h.
    {
        QCString result = "Referncia do diretrio ";
        result += dirName;
        return result;
    }
trDirReference() [2/2]
virtual QCString TranslatorPortuguese::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1523 of file translator_pt.h.
    {
        QCString result = "Referncia do diretrio ";
        result += dirName;
        return result;
    }
trDirRelation() [1/2]
virtual QCString TranslatorPortuguese::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1780 of file translator_pt.h.
    {
      return "Relao " + QCString(name);
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorPortuguese::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1780 of file translator_pt.h.
    {
      return "Relao " + QCString(name);
    }
References setup::name.
trDocumentation() [1/2]
QCString TranslatorPortuguese::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 383 of file translator_pt.h.
    { return "Documentao"; }
trDocumentation() [2/2]
QCString TranslatorPortuguese::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 383 of file translator_pt.h.
    { return "Documentao"; }
trEnumerations() [1/2]
QCString TranslatorPortuguese::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 475 of file translator_pt.h.
    { return "Enumeraes"; }
trEnumerations() [2/2]
QCString TranslatorPortuguese::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 475 of file translator_pt.h.
    { return "Enumeraes"; }
trEnumerationTypeDocumentation() [1/2]
QCString TranslatorPortuguese::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 511 of file translator_pt.h.
    { return "Documentao dos valores da enumerao"; }
trEnumerationTypeDocumentation() [2/2]
QCString TranslatorPortuguese::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 511 of file translator_pt.h.
    { return "Documentao dos valores da enumerao"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1566 of file translator_pt.h.
    { return "Documentao da enumerao"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1566 of file translator_pt.h.
    { return "Documentao da enumerao"; }
trEnumerationValues() [1/2]
QCString TranslatorPortuguese::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 493 of file translator_pt.h.
    { return "Valores de enumeraes"; }
trEnumerationValues() [2/2]
QCString TranslatorPortuguese::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 493 of file translator_pt.h.
    { return "Valores de enumeraes"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorPortuguese::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1916 of file translator_pt.h.
    { QCString result = "A documentao para esta enumerao foi gerada a partir";
      if (single) {
        result += "do seguinte ficheiro:";
      } else {
        result += "dos seguintes ficheiros:";
      }
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorPortuguese::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1916 of file translator_pt.h.
    { QCString result = "A documentao para esta enumerao foi gerada a partir";
      if (single) {
        result += "do seguinte ficheiro:";
      } else {
        result += "dos seguintes ficheiros:";
      }
      return result;
    }
trEnumName() [1/2]
QCString TranslatorPortuguese::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 195 of file translator_pt.h.
    { return "enumerao"; }
trEnumName() [2/2]
QCString TranslatorPortuguese::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 195 of file translator_pt.h.
    { return "enumerao"; }
trEnumReference() [1/2]
virtual QCString TranslatorPortuguese::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1927 of file translator_pt.h.
    {
      QCString result = "Referncia da enumerao ";
      return result + name;
    }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorPortuguese::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1927 of file translator_pt.h.
    {
      QCString result = "Referncia da enumerao ";
      return result + name;
    }
References setup::name.
trEnumValue() [1/2]
QCString TranslatorPortuguese::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 199 of file translator_pt.h.
    { return "valor enumerado"; }
trEnumValue() [2/2]
QCString TranslatorPortuguese::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 199 of file translator_pt.h.
    { return "valor enumerado"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1379 of file translator_pt.h.
    {
      return "Documentao dos eventos";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1379 of file translator_pt.h.
    {
      return "Documentao dos eventos";
    }
trEvents() [1/2]
virtual QCString TranslatorPortuguese::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1374 of file translator_pt.h.
    {
      return "Eventos";
    }
trEvents() [2/2]
virtual QCString TranslatorPortuguese::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1374 of file translator_pt.h.
    {
      return "Eventos";
    }
trExampleDocumentation() [1/2]
QCString TranslatorPortuguese::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 453 of file translator_pt.h.
    { return "Documentao do exemplo"; }
trExampleDocumentation() [2/2]
QCString TranslatorPortuguese::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 453 of file translator_pt.h.
    { return "Documentao do exemplo"; }
trExamples() [1/2]
QCString TranslatorPortuguese::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 266 of file translator_pt.h.
    { return "Exemplos"; }
trExamples() [2/2]
QCString TranslatorPortuguese::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 266 of file translator_pt.h.
    { return "Exemplos"; }
trExamplesDescription() [1/2]
QCString TranslatorPortuguese::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 368 of file translator_pt.h.
    { return "Lista de todos os exemplos:"; }
trExamplesDescription() [2/2]
QCString TranslatorPortuguese::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 368 of file translator_pt.h.
    { return "Lista de todos os exemplos:"; }
trExceptionDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2277 of file translator_pt.h.
    {
        return "Excees";
    }
trExceptionDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2277 of file translator_pt.h.
    {
        return "Excees";
    }
trExceptionHierarchy() [1/2]
virtual QCString TranslatorPortuguese::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2269 of file translator_pt.h.
    {
        return "Hierarquia de Excees";
    }
trExceptionHierarchy() [2/2]
virtual QCString TranslatorPortuguese::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2269 of file translator_pt.h.
    {
        return "Hierarquia de Excees";
    }
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorPortuguese::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2273 of file translator_pt.h.
    {
        return "Esta a lista parcialmente ordenadas de heranas:";
    }
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorPortuguese::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2273 of file translator_pt.h.
    {
        return "Esta a lista parcialmente ordenadas de heranas:";
    }
trExceptionIndex() [1/2]
virtual QCString TranslatorPortuguese::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2257 of file translator_pt.h.
    {
        return "ndice the Excees";
    }
trExceptionIndex() [2/2]
virtual QCString TranslatorPortuguese::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2257 of file translator_pt.h.
    {
        return "ndice the Excees";
    }
trExceptionList() [1/2]
virtual QCString TranslatorPortuguese::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2261 of file translator_pt.h.
    {
        return "Lista de Excees";
    }
trExceptionList() [2/2]
virtual QCString TranslatorPortuguese::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2261 of file translator_pt.h.
    {
        return "Lista de Excees";
    }
trExceptionListDescription() [1/2]
virtual QCString TranslatorPortuguese::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2265 of file translator_pt.h.
    {
        return "Estas so as excees com suas respectivas descries:";
    }
trExceptionListDescription() [2/2]
virtual QCString TranslatorPortuguese::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2265 of file translator_pt.h.
    {
        return "Estas so as excees com suas respectivas descries:";
    }
trExceptions() [1/2]
QCString TranslatorPortuguese::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 583 of file translator_pt.h.
    { return "Excepes"; }
trExceptions() [2/2]
QCString TranslatorPortuguese::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 583 of file translator_pt.h.
    { return "Excepes"; }
trExtendsClass() [1/2]
virtual QCString TranslatorPortuguese::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1970 of file translator_pt.h.
    {
      return "estende a classe @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorPortuguese::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1970 of file translator_pt.h.
    {
      return "estende a classe @0.";
    }
trFile() [1/2]
virtual QCString TranslatorPortuguese::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1237 of file translator_pt.h.
    {
      QCString result((first_capital ? "Ficheiro" : "ficheiro"));
      if (!singular) result+="s";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorPortuguese::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1237 of file translator_pt.h.
    {
      QCString result((first_capital ? "Ficheiro" : "ficheiro"));
      if (!singular) result+="s";
      return result;
    }
trFileDocumentation() [1/2]
QCString TranslatorPortuguese::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 447 of file translator_pt.h.
    { return "Documentao do ficheiro"; }
trFileDocumentation() [2/2]
QCString TranslatorPortuguese::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 447 of file translator_pt.h.
    { return "Documentao do ficheiro"; }
trFileIn() [1/2]
virtual QCString TranslatorPortuguese::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1817 of file translator_pt.h.
    {
      return "Ficheiro em "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorPortuguese::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1817 of file translator_pt.h.
    {
      return "Ficheiro em "+name;
    }
References setup::name.
trFileIndex() [1/2]
QCString TranslatorPortuguese::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 416 of file translator_pt.h.
    { return "ndice dos ficheiros"; }
trFileIndex() [2/2]
QCString TranslatorPortuguese::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 416 of file translator_pt.h.
    { return "ndice dos ficheiros"; }
trFileList() [1/2]
QCString TranslatorPortuguese::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 232 of file translator_pt.h.
    { return "Lista de ficheiros"; }
trFileList() [2/2]
QCString TranslatorPortuguese::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 232 of file translator_pt.h.
    { return "Lista de ficheiros"; }
trFileListDescription() [1/2]
QCString TranslatorPortuguese::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 278 of file translator_pt.h.
    {
      QCString result="Lista de todos os ficheiros ";
      if (!extractAll) result+="documentados ";
      result+="com uma breve descrio:";
      return result;
    }
trFileListDescription() [2/2]
QCString TranslatorPortuguese::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 278 of file translator_pt.h.
    {
      QCString result="Lista de todos os ficheiros ";
      if (!extractAll) result+="documentados ";
      result+="com uma breve descrio:";
      return result;
    }
trFileMembers() [1/2]
QCString TranslatorPortuguese::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 249 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globais";
      }
      else
      {
        return "Membros dos Ficheiros";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
QCString TranslatorPortuguese::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 249 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globais";
      }
      else
      {
        return "Membros dos Ficheiros";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
QCString TranslatorPortuguese::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 346 of file translator_pt.h.
    {
      QCString result="Lista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="todas as funes, variveis, definies, enumeraes e definies de tipo ";
        if (!extractAll) result+="documentadas ";
      }
      else
      {
        result+="todos os ficheiros membro ";
        if (!extractAll) result+="documentados ";
      }
      result+="com referncia para ";
      if (extractAll)
        result+="o ficheiro a que pertecem:";
      else
        result+="a respectiva documentao:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
QCString TranslatorPortuguese::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 346 of file translator_pt.h.
    {
      QCString result="Lista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="todas as funes, variveis, definies, enumeraes e definies de tipo ";
        if (!extractAll) result+="documentadas ";
      }
      else
      {
        result+="todos os ficheiros membro ";
        if (!extractAll) result+="documentados ";
      }
      result+="com referncia para ";
      if (extractAll)
        result+="o ficheiro a que pertecem:";
      else
        result+="a respectiva documentao:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorPortuguese::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 650 of file translator_pt.h.
    {
      QCString result= "Referncia ao ficheiro ";
      result += fileName;
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorPortuguese::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 650 of file translator_pt.h.
    {
      QCString result= "Referncia ao ficheiro ";
      result += fileName;
      return result;
    }
trFlowchart() [1/2]
virtual QCString TranslatorPortuguese::trFlowchart () [inline], [virtual]
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2385 of file translator_pt.h.
    {
        return "Fluxograma: ";
    }
trFlowchart() [2/2]
virtual QCString TranslatorPortuguese::trFlowchart () [inline], [virtual]
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2385 of file translator_pt.h.
    {
        return "Fluxograma: ";
    }
trFriends() [1/2]
virtual QCString TranslatorPortuguese::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 610 of file translator_pt.h.
    { return "Amigos"; }
trFriends() [2/2]
virtual QCString TranslatorPortuguese::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 610 of file translator_pt.h.
    { return "Amigos"; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorPortuguese::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2093 of file translator_pt.h.
    { return "Funes/Procedimentos/Processos"; }
trFunctionAndProc() [2/2]
virtual QCString TranslatorPortuguese::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2093 of file translator_pt.h.
    { return "Funes/Procedimentos/Processos"; }
trFunctionDocumentation() [1/2]
QCString TranslatorPortuguese::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 517 of file translator_pt.h.
    { return "Documentao das funes"; }
trFunctionDocumentation() [2/2]
QCString TranslatorPortuguese::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 517 of file translator_pt.h.
    { return "Documentao das funes"; }
trFunctions() [1/2]
QCString TranslatorPortuguese::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 481 of file translator_pt.h.
    { return "Funes"; }
trFunctions() [2/2]
QCString TranslatorPortuguese::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 481 of file translator_pt.h.
    { return "Funes"; }
trGeneratedAt() [1/2]
QCString TranslatorPortuguese::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 544 of file translator_pt.h.
    {
      QCString result="Gerado em "+date;
      if (!projName.isEmpty()) result+=" para "+projName;
      result+=" por";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
QCString TranslatorPortuguese::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 544 of file translator_pt.h.
    {
      QCString result="Gerado em "+date;
      if (!projName.isEmpty()) result+=" para "+projName;
      result+=" por";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
QCString TranslatorPortuguese::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 187 of file translator_pt.h.
    { QCString result="Gerado automaticamente por Doxygen";
      if (!s.isEmpty()) result+=" para "+s;
      result+=" a partir do cdigo fonte.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
QCString TranslatorPortuguese::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 187 of file translator_pt.h.
    { QCString result="Gerado automaticamente por Doxygen";
      if (!s.isEmpty()) result+=" para "+s;
      result+=" a partir do cdigo fonte.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
QCString TranslatorPortuguese::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 587 of file translator_pt.h.
    { return "Gerado por"; }
trGeneratedBy() [2/2]
QCString TranslatorPortuguese::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 587 of file translator_pt.h.
    { return "Gerado por"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorPortuguese::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 791 of file translator_pt.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="A documentao para ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?"esta Unidade de Design":"esta classe"; break;
        case ClassDef::Struct: result+="esta estrutura"; break;
        case ClassDef::Union: result+="esta unio"; break;
        case ClassDef::Interface: result+="este interface"; break;
        case ClassDef::Protocol: result+="este protocolo"; break;
        case ClassDef::Category: result+="esta categoria"; break;
        case ClassDef::Exception: result+="esta excepo"; break;
        default: break;
      }
      result+=" foi gerada a partir ";
      if (single) result+=" do seguinte ficheiro:";
      else result+="dos seguintes ficheiros:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorPortuguese::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 791 of file translator_pt.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="A documentao para ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?"esta Unidade de Design":"esta classe"; break;
        case ClassDef::Struct: result+="esta estrutura"; break;
        case ClassDef::Union: result+="esta unio"; break;
        case ClassDef::Interface: result+="este interface"; break;
        case ClassDef::Protocol: result+="este protocolo"; break;
        case ClassDef::Category: result+="esta categoria"; break;
        case ClassDef::Exception: result+="esta excepo"; break;
        default: break;
      }
      result+=" foi gerada a partir ";
      if (single) result+=" do seguinte ficheiro:";
      else result+="dos seguintes ficheiros:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorPortuguese::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1722 of file translator_pt.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="A documentao para ";
      switch(compType)
      {
        case ClassDef::Class: result+="este modulo "; break;
        case ClassDef::Struct: result+="este tipo "; break;
        case ClassDef::Union: result+="esta unio "; break;
        case ClassDef::Interface: result+="esta interface "; break;
        case ClassDef::Protocol: result+="esto protocolo "; break;
        case ClassDef::Category: result+="esta categoria "; break;
        case ClassDef::Exception: result+="esta exceo "; break;
        default: break;
      }
      result+=" foi gerada a partir do";
      if (single)
        result+=" seguinte ficheiro:";
      else
        result+="s seguintes ficheiros:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorPortuguese::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1722 of file translator_pt.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="A documentao para ";
      switch(compType)
      {
        case ClassDef::Class: result+="este modulo "; break;
        case ClassDef::Struct: result+="este tipo "; break;
        case ClassDef::Union: result+="esta unio "; break;
        case ClassDef::Interface: result+="esta interface "; break;
        case ClassDef::Protocol: result+="esto protocolo "; break;
        case ClassDef::Category: result+="esta categoria "; break;
        case ClassDef::Exception: result+="esta exceo "; break;
        default: break;
      }
      result+=" foi gerada a partir do";
      if (single)
        result+=" seguinte ficheiro:";
      else
        result+="s seguintes ficheiros:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorPortuguese::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1292 of file translator_pt.h.
    {
      QCString result((first_capital ? "Globa" : "globa"));
      result+= singular? "l" : "ais";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorPortuguese::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1292 of file translator_pt.h.
    {
      QCString result((first_capital ? "Globa" : "globa"));
      result+= singular? "l" : "ais";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorPortuguese::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1792 of file translator_pt.h.
    {
      return "Namespace global";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorPortuguese::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1792 of file translator_pt.h.
    {
      return "Namespace global";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 880 of file translator_pt.h.
    {
      return "Ir para a documentao deste ficheiro.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 880 of file translator_pt.h.
    {
      return "Ir para a documentao deste ficheiro.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorPortuguese::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 913 of file translator_pt.h.
    {
      return "Ir para a representao grfica da hierarquia da classe";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorPortuguese::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 913 of file translator_pt.h.
    {
      return "Ir para a representao grfica da hierarquia da classe";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorPortuguese::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 875 of file translator_pt.h.
    {
      return "Ir para o cdigo fonte deste ficheiro.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorPortuguese::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 875 of file translator_pt.h.
    {
      return "Ir para o cdigo fonte deste ficheiro.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorPortuguese::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 917 of file translator_pt.h.
    {
      return "Ir para a representao textual da hierarquia da classe";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorPortuguese::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 917 of file translator_pt.h.
    {
      return "Ir para a representao textual da hierarquia da classe";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorPortuguese::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 909 of file translator_pt.h.
    {
      return "Representao grfica da hiearquia da classe";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorPortuguese::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 909 of file translator_pt.h.
    {
      return "Representao grfica da hiearquia da classe";
    }
trGroup() [1/2]
virtual QCString TranslatorPortuguese::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1259 of file translator_pt.h.
    {
      QCString result((first_capital ? "Grupo" : "grupo"));
      if (!singular) result+="s";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorPortuguese::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1259 of file translator_pt.h.
    {
      QCString result((first_capital ? "Grupo" : "grupo"));
      if (!singular) result+="s";
      return result;
    }
trHierarchicalIndex() [1/2]
QCString TranslatorPortuguese::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 395 of file translator_pt.h.
    { return "ndice da hierarquia"; }
trHierarchicalIndex() [2/2]
QCString TranslatorPortuguese::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 395 of file translator_pt.h.
    { return "ndice da hierarquia"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorPortuguese::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1330 of file translator_pt.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorPortuguese::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1330 of file translator_pt.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorPortuguese::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1338 of file translator_pt.h.
    {
      return "Implementado em "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorPortuguese::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1338 of file translator_pt.h.
    {
      return "Implementado em "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorPortuguese::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1009 of file translator_pt.h.
    {
      return "Este grafo mostra quais so os ficheiros que incluem directamente ou indirectamente este ficheiro:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorPortuguese::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1009 of file translator_pt.h.
    {
      return "Este grafo mostra quais so os ficheiros que incluem directamente ou indirectamente este ficheiro:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorPortuguese::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 865 of file translator_pt.h.
    {
      return "Diagrama de dependncias de incluso para "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorPortuguese::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 865 of file translator_pt.h.
    {
      return "Diagrama de dependncias de incluso para "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorPortuguese::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1826 of file translator_pt.h.
    {
      return "Inclui ficheiro em "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorPortuguese::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1826 of file translator_pt.h.
    {
      return "Inclui ficheiro em "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
QCString TranslatorPortuguese::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 181 of file translator_pt.h.
    { return ", incluindo todos os membros herdados."; }
trIncludingInheritedMembers() [2/2]
QCString TranslatorPortuguese::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 181 of file translator_pt.h.
    { return ", incluindo todos os membros herdados."; }
trInheritedByList() [1/2]
virtual QCString TranslatorPortuguese::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 723 of file translator_pt.h.
    {
      return "Herdado por "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorPortuguese::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 723 of file translator_pt.h.
    {
      return "Herdado por "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorPortuguese::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1934 of file translator_pt.h.
    { return QCString(members)+" herdados de "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorPortuguese::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1934 of file translator_pt.h.
    { return QCString(members)+" herdados de "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorPortuguese::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 715 of file translator_pt.h.
    {
      return "Derivada de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorPortuguese::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 715 of file translator_pt.h.
    {
      return "Derivada de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorPortuguese::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 900 of file translator_pt.h.
    {
      return "Valor inicial:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorPortuguese::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 900 of file translator_pt.h.
    {
      return "Valor inicial:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorPortuguese::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1986 of file translator_pt.h.
    {
      return "Mtodos de instncia";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorPortuguese::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1986 of file translator_pt.h.
    {
      return "Mtodos de instncia";
    }
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2233 of file translator_pt.h.
    {
        return "Interfaces";
    }
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2233 of file translator_pt.h.
    {
        return "Interfaces";
    }
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorPortuguese::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2225 of file translator_pt.h.
    {
        return "Hierarquia de Interfaces";
    }
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorPortuguese::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2225 of file translator_pt.h.
    {
        return "Hierarquia de Interfaces";
    }
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorPortuguese::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2229 of file translator_pt.h.
    {
        return "Esta a lista parcialmente ordenadas de heranas:";
    }
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorPortuguese::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2229 of file translator_pt.h.
    {
        return "Esta a lista parcialmente ordenadas de heranas:";
    }
trInterfaceIndex() [1/2]
virtual QCString TranslatorPortuguese::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2213 of file translator_pt.h.
    {
        return "ndice de Interfaces";
    }
trInterfaceIndex() [2/2]
virtual QCString TranslatorPortuguese::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2213 of file translator_pt.h.
    {
        return "ndice de Interfaces";
    }
trInterfaceList() [1/2]
virtual QCString TranslatorPortuguese::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2217 of file translator_pt.h.
    {
        return "Lista de Interfaces";
    }
trInterfaceList() [2/2]
virtual QCString TranslatorPortuguese::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2217 of file translator_pt.h.
    {
        return "Lista de Interfaces";
    }
trInterfaceListDescription() [1/2]
virtual QCString TranslatorPortuguese::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2221 of file translator_pt.h.
    {
        return "Estas so as interfaces com suas respectivas descries:";
    }
trInterfaceListDescription() [2/2]
virtual QCString TranslatorPortuguese::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2221 of file translator_pt.h.
    {
        return "Estas so as interfaces com suas respectivas descries:";
    }
trInterfaces() [1/2]
virtual QCString TranslatorPortuguese::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2003 of file translator_pt.h.
    { return "Interfaces Exportadas"; }
trInterfaces() [2/2]
virtual QCString TranslatorPortuguese::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2003 of file translator_pt.h.
    { return "Interfaces Exportadas"; }
trInvariant() [1/2]
virtual QCString TranslatorPortuguese::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 895 of file translator_pt.h.
    {
      return "Invariante";
    }
trInvariant() [2/2]
virtual QCString TranslatorPortuguese::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 895 of file translator_pt.h.
    {
      return "Invariante";
    }
trISOLang() [1/2]
virtual QCString TranslatorPortuguese::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 107 of file translator_pt.h.
    {
      return "pt";
    }
trISOLang() [2/2]
virtual QCString TranslatorPortuguese::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 107 of file translator_pt.h.
    {
      return "pt";
    }
trLegend() [1/2]
virtual QCString TranslatorPortuguese::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1086 of file translator_pt.h.
    {
      return "legenda";
    }
trLegend() [2/2]
virtual QCString TranslatorPortuguese::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1086 of file translator_pt.h.
    {
      return "legenda";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorPortuguese::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 1028 of file translator_pt.h.
    {
      return
        "Esta pgina explica como interpretar os grafos gerados pelo doxygen.<p>\n"
        "Considere o seguinte exemplo:\n"
        "\\code\n"
        "/*! Esta classe vai estar escondida devido truncao */\n"
        "class Invisible { };\n\n"
        "/*! Esta classe tem a relao de herana escondida */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Classe no documentada por comentrios doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Classe derivada usando derivao pblica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe derivada usando derivao protegida */\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe derivada usando derivao privada */\n"
        "class PrivateBase { };\n\n"
        "/*! Classe usada pela classe Inherited */\n"
        "class Used { };\n\n"
        "/*! Super classe que deriva de vrias classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Isto ir gerar o seguinte grfo:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "As caixas no grafo anterior tm as seguintes interpretaes:\n"
        "<ul>\n"
        "<li>Uma caixa inteiramente preta representa a estrutura ou a classe para "
        "a qual o grafo foi gerado.\n"
        "<li>Uma caixa com borda preta representa uma estrutura ou classe documentada.\n"
        "<li>Uma caixa com borda cinzenta representa uma estrutura ou classe no documentada.\n"
        "<li>Uma caixa com borda vermelha representa uma estrutura ou classe documentada onde "
        "nem todas as relaes de herana/encapsulamento so exibidas. Um grafo truncado "
        "quando no cabe na sua rea predefinida.\n"
        "</ul>\n"
        "As setas tm a seguinte interpretao:\n"
        "<ul>\n"
        "<li>Uma seta azul escura representa uma relao de herana pblica entre duas classes.\n"
        "<li>Uma seta verde escura representa uma relao de herana protegida.\n"
        "<li>Uma seta vermelha escura representa uma relao de herana privada.\n"
        "<li>Uma seta rocha em tracejado representa uma relao de encapsulamento ou uso por "
        "parte de outra classe. A legenda da seta contm o nome da varivel ou variveis da "
        "relao. A seta aponta da classe que estabelece a relao para a classe ou estrutura que "
        " acessvel.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorPortuguese::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 1028 of file translator_pt.h.
    {
      return
        "Esta pgina explica como interpretar os grafos gerados pelo doxygen.<p>\n"
        "Considere o seguinte exemplo:\n"
        "\\code\n"
        "/*! Esta classe vai estar escondida devido truncao */\n"
        "class Invisible { };\n\n"
        "/*! Esta classe tem a relao de herana escondida */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Classe no documentada por comentrios doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Classe derivada usando derivao pblica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe derivada usando derivao protegida */\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe derivada usando derivao privada */\n"
        "class PrivateBase { };\n\n"
        "/*! Classe usada pela classe Inherited */\n"
        "class Used { };\n\n"
        "/*! Super classe que deriva de vrias classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Isto ir gerar o seguinte grfo:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "As caixas no grafo anterior tm as seguintes interpretaes:\n"
        "<ul>\n"
        "<li>Uma caixa inteiramente preta representa a estrutura ou a classe para "
        "a qual o grafo foi gerado.\n"
        "<li>Uma caixa com borda preta representa uma estrutura ou classe documentada.\n"
        "<li>Uma caixa com borda cinzenta representa uma estrutura ou classe no documentada.\n"
        "<li>Uma caixa com borda vermelha representa uma estrutura ou classe documentada onde "
        "nem todas as relaes de herana/encapsulamento so exibidas. Um grafo truncado "
        "quando no cabe na sua rea predefinida.\n"
        "</ul>\n"
        "As setas tm a seguinte interpretao:\n"
        "<ul>\n"
        "<li>Uma seta azul escura representa uma relao de herana pblica entre duas classes.\n"
        "<li>Uma seta verde escura representa uma relao de herana protegida.\n"
        "<li>Uma seta vermelha escura representa uma relao de herana privada.\n"
        "<li>Uma seta rocha em tracejado representa uma relao de encapsulamento ou uso por "
        "parte de outra classe. A legenda da seta contm o nome da varivel ou variveis da "
        "relao. A seta aponta da classe que estabelece a relao para a classe ou estrutura que "
        " acessvel.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorPortuguese::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1023 of file translator_pt.h.
    {
      return "Legenda do grafo";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorPortuguese::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1023 of file translator_pt.h.
    {
      return "Legenda do grafo";
    }
trListOfAllMembers() [1/2]
QCString TranslatorPortuguese::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 169 of file translator_pt.h.
    { return "Mostrar lista completa dos membros"; }
trListOfAllMembers() [2/2]
QCString TranslatorPortuguese::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 169 of file translator_pt.h.
    { return "Mostrar lista completa dos membros"; }
trLoading() [1/2]
virtual QCString TranslatorPortuguese::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1786 of file translator_pt.h.
    {
      return "Carregando...";
    }
trLoading() [2/2]
virtual QCString TranslatorPortuguese::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1786 of file translator_pt.h.
    {
      return "Carregando...";
    }
trMainPage() [1/2]
virtual QCString TranslatorPortuguese::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 824 of file translator_pt.h.
    { return "Pgina principal"; }
trMainPage() [2/2]
virtual QCString TranslatorPortuguese::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 824 of file translator_pt.h.
    { return "Pgina principal"; }
trMember() [1/2]
virtual QCString TranslatorPortuguese::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1281 of file translator_pt.h.
    {
      QCString result((first_capital ? "Membro" : "membro"));
      if (!singular) result+="s";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorPortuguese::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1281 of file translator_pt.h.
    {
      QCString result((first_capital ? "Membro" : "membro"));
      if (!singular) result+="s";
      return result;
    }
trMemberDataDocumentation() [1/2]
QCString TranslatorPortuguese::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 152 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentao dos campos e atributos";
      }
      else
      {
        return "Documentao dos dados membro";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
QCString TranslatorPortuguese::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 152 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentao dos campos e atributos";
      }
      else
      {
        return "Documentao dos dados membro";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
QCString TranslatorPortuguese::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 135 of file translator_pt.h.
    { return "Documentao das enumeraes"; }
trMemberEnumerationDocumentation() [2/2]
QCString TranslatorPortuguese::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 135 of file translator_pt.h.
    { return "Documentao das enumeraes"; }
trMemberFunctionDocumentation() [1/2]
QCString TranslatorPortuguese::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 139 of file translator_pt.h.
    {
        if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
        {
          return "Documentao das funes, procedimentos e processos";
        }
        else
        {
            return "Documentao das funes";
        }
    }
References Config_getBool.
trMemberFunctionDocumentation() [2/2]
QCString TranslatorPortuguese::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 139 of file translator_pt.h.
    {
        if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
        {
          return "Documentao das funes, procedimentos e processos";
        }
        else
        {
            return "Documentao das funes";
        }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorPortuguese::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1575 of file translator_pt.h.
    { return "Documentao de Funo Membro/Subrotina"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorPortuguese::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1575 of file translator_pt.h.
    { return "Documentao de Funo Membro/Subrotina"; }
trMemberList() [1/2]
QCString TranslatorPortuguese::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 173 of file translator_pt.h.
    { return "Lista dos membros"; }
trMemberList() [2/2]
QCString TranslatorPortuguese::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 173 of file translator_pt.h.
    { return "Lista dos membros"; }
trMemberTypedefDocumentation() [1/2]
QCString TranslatorPortuguese::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 131 of file translator_pt.h.
    { return "Documentao das definies de tipo"; }
trMemberTypedefDocumentation() [2/2]
QCString TranslatorPortuguese::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 131 of file translator_pt.h.
    { return "Documentao das definies de tipo"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1993 of file translator_pt.h.
    {
      return "Documentao do mtodo";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1993 of file translator_pt.h.
    {
      return "Documentao do mtodo";
    }
trModule() [1/2]
virtual QCString TranslatorPortuguese::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1713 of file translator_pt.h.
    {
      QCString result((first_capital ? "Modulo" : "modulo"));
      if (!singular) result+="s";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorPortuguese::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1713 of file translator_pt.h.
    {
      QCString result((first_capital ? "Modulo" : "modulo"));
      if (!singular) result+="s";
      return result;
    }
trModuleDocumentation() [1/2]
QCString TranslatorPortuguese::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 422 of file translator_pt.h.
    { return "Documentao do mdulo"; }
trModuleDocumentation() [2/2]
QCString TranslatorPortuguese::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 422 of file translator_pt.h.
    { return "Documentao do mdulo"; }
trModuleIndex() [1/2]
QCString TranslatorPortuguese::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 389 of file translator_pt.h.
    { return "ndice dos mdulos"; }
trModuleIndex() [2/2]
QCString TranslatorPortuguese::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 389 of file translator_pt.h.
    { return "ndice dos mdulos"; }
trModuleReference() [1/2]
virtual QCString TranslatorPortuguese::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1675 of file translator_pt.h.
    {
      QCString result = "Referncia do Mdulo ";
      result += namespaceName;
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorPortuguese::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1675 of file translator_pt.h.
    {
      QCString result = "Referncia do Mdulo ";
      result += namespaceName;
      return result;
    }
trModules() [1/2]
QCString TranslatorPortuguese::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 211 of file translator_pt.h.
    { return "Mdulos"; }
trModules() [2/2]
QCString TranslatorPortuguese::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 211 of file translator_pt.h.
    { return "Mdulos"; }
trModulesDescription() [1/2]
QCString TranslatorPortuguese::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 376 of file translator_pt.h.
    { return "Lista de todos os mdulos:"; }
trModulesDescription() [2/2]
QCString TranslatorPortuguese::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 376 of file translator_pt.h.
    { return "Lista de todos os mdulos:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorPortuguese::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1706 of file translator_pt.h.
    { return "ndice dos Mdulos"; }
trModulesIndex() [2/2]
virtual QCString TranslatorPortuguese::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1706 of file translator_pt.h.
    { return "ndice dos Mdulos"; }
trModulesList() [1/2]
virtual QCString TranslatorPortuguese::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1638 of file translator_pt.h.
    { return "Lista de Mdulos"; }
trModulesList() [2/2]
virtual QCString TranslatorPortuguese::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1638 of file translator_pt.h.
    { return "Lista de Mdulos"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorPortuguese::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1642 of file translator_pt.h.
    {
      QCString result="Esta a lista de todos os mdulos ";
      if (!extractAll) result+="documentados ";
      result+="com descries resumidas:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorPortuguese::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1642 of file translator_pt.h.
    {
      QCString result="Esta a lista de todos os mdulos ";
      if (!extractAll) result+="documentados ";
      result+="com descries resumidas:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorPortuguese::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1687 of file translator_pt.h.
    {
      QCString result="Esta a lista de todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="dos mdulos com links para ";
      if (extractAll)
      {
        result+="a documentao dos mdulos para cada membro:";
      }
      else
      {
        result+="os mdulos a que pertencem:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorPortuguese::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1687 of file translator_pt.h.
    {
      QCString result="Esta a lista de todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="dos mdulos com links para ";
      if (extractAll)
      {
        result+="a documentao dos mdulos para cada membro:";
      }
      else
      {
        result+="os mdulos a que pertencem:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorPortuguese::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1683 of file translator_pt.h.
    { return "Membros do Mdulo"; }
trModulesMembers() [2/2]
virtual QCString TranslatorPortuguese::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1683 of file translator_pt.h.
    { return "Membros do Mdulo"; }
trMonth() [1/2]
virtual QCString TranslatorPortuguese::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1865 of file translator_pt.h.
    {
      static const char *months_short[] = { "jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez" };
      static const char *months_full[] = { "janeiro", "fevereiro", "maro", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorPortuguese::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1865 of file translator_pt.h.
    {
      static const char *months_short[] = { "jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez" };
      static const char *months_full[] = { "janeiro", "fevereiro", "maro", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
QCString TranslatorPortuguese::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 165 of file translator_pt.h.
    { return "Mais..."; }
trMore() [2/2]
QCString TranslatorPortuguese::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 165 of file translator_pt.h.
    { return "Mais..."; }
trNamespace() [1/2]
virtual QCString TranslatorPortuguese::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1248 of file translator_pt.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorPortuguese::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1248 of file translator_pt.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 771 of file translator_pt.h.
    { return "Documentao dos namespaces"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 771 of file translator_pt.h.
    { return "Documentao dos namespaces"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorPortuguese::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 765 of file translator_pt.h.
    { return "ndice dos namespaces"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorPortuguese::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 765 of file translator_pt.h.
    { return "ndice dos namespaces"; }
trNamespaceList() [1/2]
virtual QCString TranslatorPortuguese::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 595 of file translator_pt.h.
    { return "Lista de namespaces"; }
trNamespaceList() [2/2]
virtual QCString TranslatorPortuguese::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 595 of file translator_pt.h.
    { return "Lista de namespaces"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorPortuguese::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 599 of file translator_pt.h.
    {
      QCString result="Lista ";
      if (!extractAll) result+="de toda a documentao ";
      result+="dos namespaces com uma breve descrio:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorPortuguese::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 599 of file translator_pt.h.
    {
      QCString result="Lista ";
      if (!extractAll) result+="de toda a documentao ";
      result+="dos namespaces com uma breve descrio:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorPortuguese::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 749 of file translator_pt.h.
    {
      QCString result="Lista ";
      if (extractAll) result+="de todos os ";
      else result+="de toda a documentao dos ";
      result+="membros do namespace com referncia para ";
      if (extractAll)
        result+="a documentao de cada membro:";
      else
        result+="o namespace correspondente:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorPortuguese::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 749 of file translator_pt.h.
    {
      QCString result="Lista ";
      if (extractAll) result+="de todos os ";
      else result+="de toda a documentao dos ";
      result+="membros do namespace com referncia para ";
      if (extractAll)
        result+="a documentao de cada membro:";
      else
        result+="o namespace correspondente:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorPortuguese::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 745 of file translator_pt.h.
    { return "Membros do namespace"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorPortuguese::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 745 of file translator_pt.h.
    { return "Membros do namespace"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorPortuguese::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 658 of file translator_pt.h.
    {
      QCString result= "Referncia ao namespace ";
      result += namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorPortuguese::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 658 of file translator_pt.h.
    {
      QCString result= "Referncia ao namespace ";
      result += namespaceName;
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorPortuguese::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 781 of file translator_pt.h.
    { return "Namespaces"; }
trNamespaces() [2/2]
virtual QCString TranslatorPortuguese::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 781 of file translator_pt.h.
    { return "Namespaces"; }
trNoMatches() [1/2]
virtual QCString TranslatorPortuguese::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1804 of file translator_pt.h.
    {
      return "Nenhuma entrada encontrada";
    }
trNoMatches() [2/2]
virtual QCString TranslatorPortuguese::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1804 of file translator_pt.h.
    {
      return "Nenhuma entrada encontrada";
    }
trNote() [1/2]
virtual QCString TranslatorPortuguese::trNote () [inline], [virtual]
Implements Translator.
Definition at line 930 of file translator_pt.h.
    {
      return "Nota";
    }
trNote() [2/2]
virtual QCString TranslatorPortuguese::trNote () [inline], [virtual]
Implements Translator.
Definition at line 930 of file translator_pt.h.
    {
      return "Nota";
    }
trOperationDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2303 of file translator_pt.h.
    {
        return "Operaes";
    }
trOperationDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2303 of file translator_pt.h.
    {
        return "Operaes";
    }
trOperations() [1/2]
virtual QCString TranslatorPortuguese::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2299 of file translator_pt.h.
    {
        return "Operaes";
    }
trOperations() [2/2]
virtual QCString TranslatorPortuguese::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2299 of file translator_pt.h.
    {
        return "Operaes";
    }
trOverloadText() [1/2]
virtual QCString TranslatorPortuguese::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1546 of file translator_pt.h.
    {
       return "Este um mtodo provido por convenincia. "
            "Ele difere do mtodo acima apenas na lista de "
            "argumentos que devem ser utilizados.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorPortuguese::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1546 of file translator_pt.h.
    {
       return "Este um mtodo provido por convenincia. "
            "Ele difere do mtodo acima apenas na lista de "
            "argumentos que devem ser utilizados.";
    }
trPackage() [1/2]
virtual QCString TranslatorPortuguese::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1138 of file translator_pt.h.
    {
      return "Pacote "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorPortuguese::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1138 of file translator_pt.h.
    {
      return "Pacote "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorPortuguese::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1415 of file translator_pt.h.
    {
      return "Atributos do Pacote";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorPortuguese::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1415 of file translator_pt.h.
    {
      return "Atributos do Pacote";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorPortuguese::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1397 of file translator_pt.h.
    {
      return "Funes do Pacote";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorPortuguese::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1397 of file translator_pt.h.
    {
      return "Funes do Pacote";
    }
trPackageList() [1/2]
virtual QCString TranslatorPortuguese::trPackageList () [inline], [virtual]
Implements Translator.
Definition at line 2375 of file translator_pt.h.
    { return "Lista de pacotes"; }
trPackageList() [2/2]
virtual QCString TranslatorPortuguese::trPackageList () [inline], [virtual]
Implements Translator.
Definition at line 2375 of file translator_pt.h.
    { return "Lista de pacotes"; }
trPackageListDescription() [1/2]
virtual QCString TranslatorPortuguese::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1143 of file translator_pt.h.
    {
      return "Lista de pacotes com uma breve descrio (se disponvel):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorPortuguese::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1143 of file translator_pt.h.
    {
      return "Lista de pacotes com uma breve descrio (se disponvel):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorPortuguese::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1401 of file translator_pt.h.
    {
      return "Membros do Pacote";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorPortuguese::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1401 of file translator_pt.h.
    {
      return "Membros do Pacote";
    }
trPackages() [1/2]
virtual QCString TranslatorPortuguese::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1148 of file translator_pt.h.
    {
      return "Pacotes";
    }
trPackages() [2/2]
virtual QCString TranslatorPortuguese::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1148 of file translator_pt.h.
    {
      return "Pacotes";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorPortuguese::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1390 of file translator_pt.h.
    {
      return "Tipos do Pacote";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorPortuguese::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1390 of file translator_pt.h.
    {
      return "Tipos do Pacote";
    }
trPage() [1/2]
virtual QCString TranslatorPortuguese::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1270 of file translator_pt.h.
    {
      QCString result((first_capital ? "Pgina" : "pgina"));
      if (!singular) result+="s";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorPortuguese::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1270 of file translator_pt.h.
    {
      QCString result((first_capital ? "Pgina" : "pgina"));
      if (!singular) result+="s";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorPortuguese::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 830 of file translator_pt.h.
    { return "p. "; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorPortuguese::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 830 of file translator_pt.h.
    { return "p. "; }
trPageIndex() [1/2]
virtual QCString TranslatorPortuguese::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 921 of file translator_pt.h.
    {
      return "ndice da pgina";
    }
trPageIndex() [2/2]
virtual QCString TranslatorPortuguese::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 921 of file translator_pt.h.
    {
      return "ndice da pgina";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorPortuguese::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1951 of file translator_pt.h.
    {
      QCString opt = enable ? "ativar" : "desativar";
      return "clique para "+opt+" a sincronizao do painel";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorPortuguese::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1951 of file translator_pt.h.
    {
      QCString opt = enable ? "ativar" : "desativar";
      return "clique para "+opt+" a sincronizao do painel";
    }
trParameters() [1/2]
QCString TranslatorPortuguese::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 579 of file translator_pt.h.
    { return "Parmetros"; }
trParameters() [2/2]
QCString TranslatorPortuguese::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 579 of file translator_pt.h.
    { return "Parmetros"; }
trPostcondition() [1/2]
virtual QCString TranslatorPortuguese::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 890 of file translator_pt.h.
    {
      return "Poscondio";
    }
trPostcondition() [2/2]
virtual QCString TranslatorPortuguese::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 890 of file translator_pt.h.
    {
      return "Poscondio";
    }
trPrecondition() [1/2]
virtual QCString TranslatorPortuguese::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 885 of file translator_pt.h.
    {
      return "Precondio";
    }
trPrecondition() [2/2]
virtual QCString TranslatorPortuguese::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 885 of file translator_pt.h.
    {
      return "Precondio";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorPortuguese::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 969 of file translator_pt.h.
    {
      return "Atributos Privados";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorPortuguese::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 969 of file translator_pt.h.
    {
      return "Atributos Privados";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorPortuguese::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 680 of file translator_pt.h.
    { return "Membros privados"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorPortuguese::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 680 of file translator_pt.h.
    { return "Membros privados"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorPortuguese::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 682 of file translator_pt.h.
    { return "Slots privados"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorPortuguese::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 682 of file translator_pt.h.
    { return "Slots privados"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorPortuguese::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 965 of file translator_pt.h.
    {
      return "Tipos Privados";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorPortuguese::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 965 of file translator_pt.h.
    {
      return "Tipos Privados";
    }
trProperties() [1/2]
virtual QCString TranslatorPortuguese::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1111 of file translator_pt.h.
    {
      return "Propriedades";
    }
trProperties() [2/2]
virtual QCString TranslatorPortuguese::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1111 of file translator_pt.h.
    {
      return "Propriedades";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1116 of file translator_pt.h.
    {
      return "Documentao das propriedades";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1116 of file translator_pt.h.
    {
      return "Documentao das propriedades";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorPortuguese::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 957 of file translator_pt.h.
    {
      return "Atributos Protegidos";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorPortuguese::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 957 of file translator_pt.h.
    {
      return "Atributos Protegidos";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorPortuguese::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 674 of file translator_pt.h.
    { return "Membros protegidos"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorPortuguese::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 674 of file translator_pt.h.
    { return "Membros protegidos"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorPortuguese::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 676 of file translator_pt.h.
    { return "Slots protegidos"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorPortuguese::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 676 of file translator_pt.h.
    { return "Slots protegidos"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorPortuguese::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 953 of file translator_pt.h.
    {
      return "Tipos Protegidos";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorPortuguese::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 953 of file translator_pt.h.
    {
      return "Tipos Protegidos";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorPortuguese::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1961 of file translator_pt.h.
    {
      return "Provido pela categoria @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorPortuguese::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1961 of file translator_pt.h.
    {
      return "Provido pela categoria @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorPortuguese::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 938 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de Dados";
      }
      else
      {
        return "Atributos Pblicos";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorPortuguese::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 938 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de Dados";
      }
      else
      {
        return "Atributos Pblicos";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorPortuguese::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 666 of file translator_pt.h.
    { return "Membros pblicos"; }
trPublicMembers() [2/2]
virtual QCString TranslatorPortuguese::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 666 of file translator_pt.h.
    { return "Membros pblicos"; }
trPublicSlots() [1/2]
virtual QCString TranslatorPortuguese::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 668 of file translator_pt.h.
    { return "Slots pblicos"; }
trPublicSlots() [2/2]
virtual QCString TranslatorPortuguese::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 668 of file translator_pt.h.
    { return "Slots pblicos"; }
trPublicTypes() [1/2]
virtual QCString TranslatorPortuguese::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 934 of file translator_pt.h.
    {
      return "Tipos Pblicos";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorPortuguese::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 934 of file translator_pt.h.
    {
      return "Tipos Pblicos";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorPortuguese::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 997 of file translator_pt.h.
    {
      return "Referenciado por";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorPortuguese::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 997 of file translator_pt.h.
    {
      return "Referenciado por";
    }
trReferenceManual() [1/2]
QCString TranslatorPortuguese::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 457 of file translator_pt.h.
    { return "Manual de referncia"; }
trReferenceManual() [2/2]
QCString TranslatorPortuguese::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 457 of file translator_pt.h.
    { return "Manual de referncia"; }
trReferences() [1/2]
virtual QCString TranslatorPortuguese::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1318 of file translator_pt.h.
    {
      return "Referncias";
    }
trReferences() [2/2]
virtual QCString TranslatorPortuguese::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1318 of file translator_pt.h.
    {
      return "Referncias";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorPortuguese::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 731 of file translator_pt.h.
    {
      return "Reimplementado de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorPortuguese::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 731 of file translator_pt.h.
    {
      return "Reimplementado de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorPortuguese::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 739 of file translator_pt.h.
    {
      return "Reimplementado em "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorPortuguese::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 739 of file translator_pt.h.
    {
      return "Reimplementado em "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 620 of file translator_pt.h.
    { return "Documentao das classes amigas e funes relacionadas"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 620 of file translator_pt.h.
    { return "Documentao das classes amigas e funes relacionadas"; }
trRelatedFunctions() [1/2]
QCString TranslatorPortuguese::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 119 of file translator_pt.h.
    { return "Funes associadas"; }
trRelatedFunctions() [2/2]
QCString TranslatorPortuguese::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 119 of file translator_pt.h.
    { return "Funes associadas"; }
trRelatedPages() [1/2]
QCString TranslatorPortuguese::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 262 of file translator_pt.h.
    { return "Pginas relacionadas"; }
trRelatedPages() [2/2]
QCString TranslatorPortuguese::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 262 of file translator_pt.h.
    { return "Pginas relacionadas"; }
trRelatedPagesDescription() [1/2]
QCString TranslatorPortuguese::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 372 of file translator_pt.h.
    { return "Lista de documentao relacionada:"; }
trRelatedPagesDescription() [2/2]
QCString TranslatorPortuguese::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 372 of file translator_pt.h.
    { return "Lista de documentao relacionada:"; }
trRelatedSubscript() [1/2]
QCString TranslatorPortuguese::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 123 of file translator_pt.h.
    { return "(Note que no so funes membro)"; }
trRelatedSubscript() [2/2]
QCString TranslatorPortuguese::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 123 of file translator_pt.h.
    { return "(Note que no so funes membro)"; }
trRemarks() [1/2]
virtual QCString TranslatorPortuguese::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1001 of file translator_pt.h.
    {
      return "Observaes";
    }
trRemarks() [2/2]
virtual QCString TranslatorPortuguese::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1001 of file translator_pt.h.
    {
      return "Observaes";
    }
trReturns() [1/2]
QCString TranslatorPortuguese::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 571 of file translator_pt.h.
    { return "Retorna"; }
trReturns() [2/2]
QCString TranslatorPortuguese::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 571 of file translator_pt.h.
    { return "Retorna"; }
trReturnValues() [1/2]
virtual QCString TranslatorPortuguese::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 819 of file translator_pt.h.
    { return "Valores retornados"; }
trReturnValues() [2/2]
virtual QCString TranslatorPortuguese::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 819 of file translator_pt.h.
    { return "Valores retornados"; }
trRTFansicp() [1/2]
virtual QCString TranslatorPortuguese::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1202 of file translator_pt.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorPortuguese::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1202 of file translator_pt.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorPortuguese::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1211 of file translator_pt.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorPortuguese::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1211 of file translator_pt.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorPortuguese::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1217 of file translator_pt.h.
    {
      return "ndice";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorPortuguese::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1217 of file translator_pt.h.
    {
      return "ndice";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorPortuguese::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1350 of file translator_pt.h.
    {
      return "ndice";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorPortuguese::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1350 of file translator_pt.h.
    {
      return "ndice";
    }
trSearch() [1/2]
QCString TranslatorPortuguese::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 270 of file translator_pt.h.
    { return "Localizar"; }
trSearch() [2/2]
QCString TranslatorPortuguese::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 270 of file translator_pt.h.
    { return "Localizar"; }
trSearching() [1/2]
virtual QCString TranslatorPortuguese::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1798 of file translator_pt.h.
    {
      return "Procurando...";
    }
trSearching() [2/2]
virtual QCString TranslatorPortuguese::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1798 of file translator_pt.h.
    {
      return "Procurando...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorPortuguese::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1482 of file translator_pt.h.
    {
      return "Resultados:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorPortuguese::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1482 of file translator_pt.h.
    {
      return "Resultados:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorPortuguese::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1463 of file translator_pt.h.
    {
      if (numDocuments==0)
      {
        return "Nenhum documento foi encontrado.";
      }
      else if (numDocuments==1)
      {
        return "Apenas <b>1</b> documento foi encontrado.";
      }
      else
      {
        return "<b>$num</b> documentos encontrados. "
               "Os melhores resultados vem primeiro.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorPortuguese::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1463 of file translator_pt.h.
    {
      if (numDocuments==0)
      {
        return "Nenhum documento foi encontrado.";
      }
      else if (numDocuments==1)
      {
        return "Apenas <b>1</b> documento foi encontrado.";
      }
      else
      {
        return "<b>$num</b> documentos encontrados. "
               "Os melhores resultados vem primeiro.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorPortuguese::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1451 of file translator_pt.h.
    {
      return "Resultado da Busca";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorPortuguese::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1451 of file translator_pt.h.
    {
      return "Resultado da Busca";
    }
trSeeAlso() [1/2]
QCString TranslatorPortuguese::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 575 of file translator_pt.h.
    { return "Veja tambm"; }
trSeeAlso() [2/2]
QCString TranslatorPortuguese::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 575 of file translator_pt.h.
    { return "Veja tambm"; }
trSequenceDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2197 of file translator_pt.h.
    {
        return "Sequncias";
    }
trSequenceDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2197 of file translator_pt.h.
    {
        return "Sequncias";
    }
trSequences() [1/2]
virtual QCString TranslatorPortuguese::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2193 of file translator_pt.h.
    {
        return "Sequncias";
    }
trSequences() [2/2]
virtual QCString TranslatorPortuguese::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2193 of file translator_pt.h.
    {
        return "Sequncias";
    }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorPortuguese::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2039 of file translator_pt.h.
    {
      // single is true implies a single file
      QCString result="A documentao para este servio "
                                "foi gerada a partir ";
      if (single) {
        result+="do seguinte ficheiro:";
      } else {
        result+="dos: seguintes ficheiros:";
      }
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorPortuguese::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2039 of file translator_pt.h.
    {
      // single is true implies a single file
      QCString result="A documentao para este servio "
                                "foi gerada a partir ";
      if (single) {
        result+="do seguinte ficheiro:";
      } else {
        result+="dos: seguintes ficheiros:";
      }
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorPortuguese::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2023 of file translator_pt.h.
    {
      QCString result = "Referncia do servio ";
      result += sName;
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorPortuguese::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2023 of file translator_pt.h.
    {
      QCString result = "Referncia do servio ";
      result += sName;
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorPortuguese::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2007 of file translator_pt.h.
    { return "Servios Includos"; }
trServices() [2/2]
virtual QCString TranslatorPortuguese::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2007 of file translator_pt.h.
    { return "Servios Includos"; }
trSignals() [1/2]
virtual QCString TranslatorPortuguese::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 670 of file translator_pt.h.
    { return "Sinais"; }
trSignals() [2/2]
virtual QCString TranslatorPortuguese::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 670 of file translator_pt.h.
    { return "Sinais"; }
trSince() [1/2]
virtual QCString TranslatorPortuguese::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1013 of file translator_pt.h.
    {
      return "Desde";
    }
trSince() [2/2]
virtual QCString TranslatorPortuguese::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1013 of file translator_pt.h.
    {
      return "Desde";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorPortuguese::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2053 of file translator_pt.h.
    {
      // single is true implies a single file
      QCString result="A documentao para este singleton "
                                "foi gerada a partir ";
      if (single) {
        result+="do seguinte ficheiro:";
      } else {
        result+="dos: seguintes ficheiros:";
      }
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorPortuguese::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2053 of file translator_pt.h.
    {
      // single is true implies a single file
      QCString result="A documentao para este singleton "
                                "foi gerada a partir ";
      if (single) {
        result+="do seguinte ficheiro:";
      } else {
        result+="dos: seguintes ficheiros:";
      }
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorPortuguese::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2031 of file translator_pt.h.
    {
      QCString result = "Referncia do Singleton ";
      result += sName;
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorPortuguese::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2031 of file translator_pt.h.
    {
      QCString result = "Referncia do Singleton ";
      result += sName;
      return result;
    }
trSliceInterfaces() [1/2]
virtual QCString TranslatorPortuguese::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2209 of file translator_pt.h.
    {
        return "Interfaces";
    }
trSliceInterfaces() [2/2]
virtual QCString TranslatorPortuguese::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2209 of file translator_pt.h.
    {
        return "Interfaces";
    }
trSourceFile() [1/2]
virtual QCString TranslatorPortuguese::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1493 of file translator_pt.h.
    {
      return "Cdigo-Fonte de " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorPortuguese::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1493 of file translator_pt.h.
    {
      return "Cdigo-Fonte de " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorPortuguese::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1422 of file translator_pt.h.
    {
      return "Atributos Estticos do Pacote";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorPortuguese::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1422 of file translator_pt.h.
    {
      return "Atributos Estticos do Pacote";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorPortuguese::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1408 of file translator_pt.h.
    {
      return "Funes Estticas do Pacote";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorPortuguese::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1408 of file translator_pt.h.
    {
      return "Funes Estticas do Pacote";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorPortuguese::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_pt.h.
    {
      return "Atributos Privados Estticos";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorPortuguese::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_pt.h.
    {
      return "Atributos Privados Estticos";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorPortuguese::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 684 of file translator_pt.h.
    { return "Membros privados estticos"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorPortuguese::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 684 of file translator_pt.h.
    { return "Membros privados estticos"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorPortuguese::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 961 of file translator_pt.h.
    {
      return "Atributos Protegidos Estticos";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorPortuguese::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 961 of file translator_pt.h.
    {
      return "Atributos Protegidos Estticos";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorPortuguese::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 678 of file translator_pt.h.
    { return "Membros protegidos estticos"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorPortuguese::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 678 of file translator_pt.h.
    { return "Membros protegidos estticos"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorPortuguese::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_pt.h.
    {
      return "Atributos Pblicos Estticos";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorPortuguese::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_pt.h.
    {
      return "Atributos Pblicos Estticos";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorPortuguese::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 672 of file translator_pt.h.
    { return "Membros pblicos estticos"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorPortuguese::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 672 of file translator_pt.h.
    { return "Membros pblicos estticos"; }
trStructDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2253 of file translator_pt.h.
    {
        return "Estruturas";
    }
trStructDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2253 of file translator_pt.h.
    {
        return "Estruturas";
    }
trStructIndex() [1/2]
virtual QCString TranslatorPortuguese::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2241 of file translator_pt.h.
    {
        return "ndice de Estruturas";
    }
trStructIndex() [2/2]
virtual QCString TranslatorPortuguese::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2241 of file translator_pt.h.
    {
        return "ndice de Estruturas";
    }
trStructList() [1/2]
virtual QCString TranslatorPortuguese::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2245 of file translator_pt.h.
    {
        return "Lista de Estruturas";
    }
trStructList() [2/2]
virtual QCString TranslatorPortuguese::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2245 of file translator_pt.h.
    {
        return "Lista de Estruturas";
    }
trStructListDescription() [1/2]
virtual QCString TranslatorPortuguese::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2249 of file translator_pt.h.
    {
        return "Estas so as estruturas com suas respectivas descries:";
    }
trStructListDescription() [2/2]
virtual QCString TranslatorPortuguese::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2249 of file translator_pt.h.
    {
        return "Estas so as estruturas com suas respectivas descries:";
    }
trStructs() [1/2]
virtual QCString TranslatorPortuguese::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2237 of file translator_pt.h.
    {
        return "Estruturas";
    }
trStructs() [2/2]
virtual QCString TranslatorPortuguese::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2237 of file translator_pt.h.
    {
        return "Estruturas";
    }
trSubprogram() [1/2]
virtual QCString TranslatorPortuguese::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1761 of file translator_pt.h.
    {
      QCString result((first_capital ? "Subprograma" : "subprograma"));
      if (!singular) result+="s";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorPortuguese::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1761 of file translator_pt.h.
    {
      QCString result((first_capital ? "Subprograma" : "subprograma"));
      if (!singular) result+="s";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1628 of file translator_pt.h.
    { return "Documentao da Funo/Subrotina"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1628 of file translator_pt.h.
    { return "Documentao da Funo/Subrotina"; }
trSubprograms() [1/2]
virtual QCString TranslatorPortuguese::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1622 of file translator_pt.h.
    { return "Funes/Subrotinas"; }
trSubprograms() [2/2]
virtual QCString TranslatorPortuguese::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1622 of file translator_pt.h.
    { return "Funes/Subrotinas"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorPortuguese::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1908 of file translator_pt.h.
    { return "Parmetros de template"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorPortuguese::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1908 of file translator_pt.h.
    { return "Parmetros de template"; }
trTest() [1/2]
virtual QCString TranslatorPortuguese::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1096 of file translator_pt.h.
    {
      return "Teste";
    }
trTest() [2/2]
virtual QCString TranslatorPortuguese::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1096 of file translator_pt.h.
    {
      return "Teste";
    }
trTestList() [1/2]
virtual QCString TranslatorPortuguese::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1101 of file translator_pt.h.
    {
      return "Lista de teste";
    }
trTestList() [2/2]
virtual QCString TranslatorPortuguese::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1101 of file translator_pt.h.
    {
      return "Lista de teste";
    }
trThisIsTheListOfAllMembers() [1/2]
QCString TranslatorPortuguese::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 177 of file translator_pt.h.
    { return "Lista completa de todos os membros de "; }
trThisIsTheListOfAllMembers() [2/2]
QCString TranslatorPortuguese::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 177 of file translator_pt.h.
    { return "Lista completa de todos os membros de "; }
trTodo() [1/2]
virtual QCString TranslatorPortuguese::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 983 of file translator_pt.h.
    {
      return "Tarefa";
    }
trTodo() [2/2]
virtual QCString TranslatorPortuguese::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 983 of file translator_pt.h.
    {
      return "Tarefa";
    }
trTodoList() [1/2]
virtual QCString TranslatorPortuguese::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 988 of file translator_pt.h.
    {
      return "Lista de tarefas";
    }
trTodoList() [2/2]
virtual QCString TranslatorPortuguese::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 988 of file translator_pt.h.
    {
      return "Lista de tarefas";
    }
trType() [1/2]
virtual QCString TranslatorPortuguese::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1751 of file translator_pt.h.
    {
      QCString result((first_capital ? "Tipo" : "tipo"));
      if (!singular) result+="s";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorPortuguese::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1751 of file translator_pt.h.
    {
      QCString result((first_capital ? "Tipo" : "tipo"));
      if (!singular) result+="s";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorPortuguese::trTypeConstraints () [inline], [virtual]
C# Type Contraint list
Implements Translator.
Definition at line 1769 of file translator_pt.h.
    {
      return "Restries do Tipo";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorPortuguese::trTypeConstraints () [inline], [virtual]
C# Type Contraint list
Implements Translator.
Definition at line 1769 of file translator_pt.h.
    {
      return "Restries do Tipo";
    }
trTypedefDocumentation() [1/2]
QCString TranslatorPortuguese::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 505 of file translator_pt.h.
    { return "Documentao dos tipos"; }
trTypedefDocumentation() [2/2]
QCString TranslatorPortuguese::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 505 of file translator_pt.h.
    { return "Documentao dos tipos"; }
trTypedefs() [1/2]
QCString TranslatorPortuguese::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 469 of file translator_pt.h.
    { return "Definies de tipos"; }
trTypedefs() [2/2]
QCString TranslatorPortuguese::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 469 of file translator_pt.h.
    { return "Definies de tipos"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorPortuguese::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1616 of file translator_pt.h.
    { return "Documentao dos Tipos de Dados"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorPortuguese::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1616 of file translator_pt.h.
    { return "Documentao dos Tipos de Dados"; }
trVariableDocumentation() [1/2]
QCString TranslatorPortuguese::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 523 of file translator_pt.h.
    { return "Documentao das variveis"; }
trVariableDocumentation() [2/2]
QCString TranslatorPortuguese::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 523 of file translator_pt.h.
    { return "Documentao das variveis"; }
trVariables() [1/2]
QCString TranslatorPortuguese::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 487 of file translator_pt.h.
    { return "Variveis"; }
trVariables() [2/2]
QCString TranslatorPortuguese::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 487 of file translator_pt.h.
    { return "Variveis"; }
trVersion() [1/2]
QCString TranslatorPortuguese::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 563 of file translator_pt.h.
    { return "Verso"; }
trVersion() [2/2]
QCString TranslatorPortuguese::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 563 of file translator_pt.h.
    { return "Verso"; }
trVhdlType() [1/2]
virtual QCString TranslatorPortuguese::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2096 of file translator_pt.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Biblioteca";
          else return "Bibliotecas";
        case VhdlDocGen::PACKAGE:
          if (single) return "Pacote";
          else return "Pacotes";
        case VhdlDocGen::SIGNAL:
          if (single) return "Sinal";
          else return "Sinais";
        case VhdlDocGen::COMPONENT:
          if (single) return "Componente";
          else return "Componentes";
        case VhdlDocGen::CONSTANT:
          if (single) return "Constante";
          else return "Constantes";
        case VhdlDocGen::ENTITY:
          if (single) return "Entidade";
          else return "Entidades";
        case VhdlDocGen::TYPE:
          if (single) return "Tipo";
          else return "Tipos";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Subtipo";
          else return "Subtipos";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funo";
          else return "Funes";
        case VhdlDocGen::RECORD:
          if (single) return "Registro";
          else return "Registros";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedimento";
          else return "Procedimentos";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Arquitetura";
          else return "Arquiteturas";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Atributo";
          else return "Atributos";
        case VhdlDocGen::PROCESS:
          if (single) return "Processo";
          else return "Processos";
        case VhdlDocGen::PORT:
          if (single) return "Porta";
          else return "Portas";
        case VhdlDocGen::USE:
          if (single) return "clusula de uso";
          else return "clusulas de uso";
        case VhdlDocGen::GENERIC:
          if (single) return "Generico";
          else return "Genericos";
        case VhdlDocGen::PACKAGE_BODY:
          return "Corpo do Pacote";
        case VhdlDocGen::UNITS:
          return "Unidades";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Varivel Compartilhada";
          else return "Variveis Compartilhadas";
        case VhdlDocGen::VFILE:
          if (single) return "Ficheiro";
          else return "Ficheiros";
        case VhdlDocGen::GROUP:
          if (single) return "Grupo";
          else return "Grupos";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instncia";
          else return "Instncias";
        case VhdlDocGen::ALIAS:
          if (single) return "Apelido";
          else return "Apelidos";
        case VhdlDocGen::CONFIG:
          if (single) return "Configurao";
          else return "Configuraes";
        case VhdlDocGen::MISCELLANEOUS:
          return "Outros"; // Is this correct for VHDL?
        case VhdlDocGen::UCF_CONST:
          return "Restries";
        default:
          return "Classe";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trVhdlType() [2/2]
virtual QCString TranslatorPortuguese::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2096 of file translator_pt.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Biblioteca";
          else return "Bibliotecas";
        case VhdlDocGen::PACKAGE:
          if (single) return "Pacote";
          else return "Pacotes";
        case VhdlDocGen::SIGNAL:
          if (single) return "Sinal";
          else return "Sinais";
        case VhdlDocGen::COMPONENT:
          if (single) return "Componente";
          else return "Componentes";
        case VhdlDocGen::CONSTANT:
          if (single) return "Constante";
          else return "Constantes";
        case VhdlDocGen::ENTITY:
          if (single) return "Entidade";
          else return "Entidades";
        case VhdlDocGen::TYPE:
          if (single) return "Tipo";
          else return "Tipos";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Subtipo";
          else return "Subtipos";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funo";
          else return "Funes";
        case VhdlDocGen::RECORD:
          if (single) return "Registro";
          else return "Registros";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedimento";
          else return "Procedimentos";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Arquitetura";
          else return "Arquiteturas";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Atributo";
          else return "Atributos";
        case VhdlDocGen::PROCESS:
          if (single) return "Processo";
          else return "Processos";
        case VhdlDocGen::PORT:
          if (single) return "Porta";
          else return "Portas";
        case VhdlDocGen::USE:
          if (single) return "clusula de uso";
          else return "clusulas de uso";
        case VhdlDocGen::GENERIC:
          if (single) return "Generico";
          else return "Genericos";
        case VhdlDocGen::PACKAGE_BODY:
          return "Corpo do Pacote";
        case VhdlDocGen::UNITS:
          return "Unidades";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Varivel Compartilhada";
          else return "Variveis Compartilhadas";
        case VhdlDocGen::VFILE:
          if (single) return "Ficheiro";
          else return "Ficheiros";
        case VhdlDocGen::GROUP:
          if (single) return "Grupo";
          else return "Grupos";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instncia";
          else return "Instncias";
        case VhdlDocGen::ALIAS:
          if (single) return "Apelido";
          else return "Apelidos";
        case VhdlDocGen::CONFIG:
          if (single) return "Configurao";
          else return "Configuraes";
        case VhdlDocGen::MISCELLANEOUS:
          return "Outros"; // Is this correct for VHDL?
        case VhdlDocGen::UCF_CONST:
          return "Restries";
        default:
          return "Classe";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
QCString TranslatorPortuguese::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 559 of file translator_pt.h.
    { return "Aviso"; }
trWarning() [2/2]
QCString TranslatorPortuguese::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 559 of file translator_pt.h.
    { return "Aviso"; }
trWriteList() [1/2]
virtual QCString TranslatorPortuguese::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 690 of file translator_pt.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" e ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorPortuguese::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 690 of file translator_pt.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" e ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_pt.h
doxygen/src/translator_pt.h