TranslatorAdapter_1_6_0 Class Reference
#include <translator_adapter.h>
Public Member Functions
virtual QCString updateNeededMessage ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString updateNeededMessage ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
Additional Inherited Members
Detailed Description
Adapter class for languages that only contain translations up to version 1.6.0.
Definition at line 345 of file translator_adapter.h.
Member Function Documentation
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trCompoundIndexFortran () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 381 of file translator_adapter.h.
    { return english.trCompoundIndexFortran(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundIndexFortran().
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trCompoundIndexFortran () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 381 of file translator_adapter.h.
    { return english.trCompoundIndexFortran(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundIndexFortran().
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trCompoundListDescriptionFortran () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 375 of file translator_adapter.h.
    { return english.trCompoundListDescriptionFortran(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundListDescriptionFortran().
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trCompoundListDescriptionFortran () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 375 of file translator_adapter.h.
    { return english.trCompoundListDescriptionFortran(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundListDescriptionFortran().
trCompoundListFortran() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trCompoundListFortran () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 369 of file translator_adapter.h.
    { return english.trCompoundListFortran(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundListFortran().
trCompoundListFortran() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trCompoundListFortran () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 369 of file translator_adapter.h.
    { return english.trCompoundListFortran(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundListFortran().
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 378 of file translator_adapter.h.
    { return english.trCompoundMembersDescriptionFortran(extractAll); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundMembersDescriptionFortran().
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 378 of file translator_adapter.h.
    { return english.trCompoundMembersDescriptionFortran(extractAll); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundMembersDescriptionFortran().
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trCompoundMembersFortran () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 372 of file translator_adapter.h.
    { return english.trCompoundMembersFortran(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundMembersFortran().
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trCompoundMembersFortran () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 372 of file translator_adapter.h.
    { return english.trCompoundMembersFortran(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundMembersFortran().
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 402 of file translator_adapter.h.
    { return english.trCompoundReferenceFortran(clName,compType,isTemplate); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundReferenceFortran().
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 402 of file translator_adapter.h.
    { return english.trCompoundReferenceFortran(clName,compType,isTemplate); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundReferenceFortran().
trDataTypes() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trDataTypes () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 393 of file translator_adapter.h.
    { return english.trDataTypes(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDataTypes().
trDataTypes() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trDataTypes () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 393 of file translator_adapter.h.
    { return english.trDataTypes(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDataTypes().
trDirRelation() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trDirRelation (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 351 of file translator_adapter.h.
    { return english.trDirRelation(name); }
References TranslatorAdapterBase::english, setup::name, and TranslatorEnglish::trDirRelation().
trDirRelation() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trDirRelation (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 351 of file translator_adapter.h.
    { return english.trDirRelation(name); }
References TranslatorAdapterBase::english, setup::name, and TranslatorEnglish::trDirRelation().
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 422 of file translator_adapter.h.
    { return english.trGeneratedFromFilesFortran(compType,single); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trGeneratedFromFilesFortran().
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 422 of file translator_adapter.h.
    { return english.trGeneratedFromFilesFortran(compType,single); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trGeneratedFromFilesFortran().
trGlobalNamespace() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trGlobalNamespace () [inline], [virtual]
Implements Translator.
Definition at line 357 of file translator_adapter.h.
    { return english.trGlobalNamespace(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trGlobalNamespace().
trGlobalNamespace() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trGlobalNamespace () [inline], [virtual]
Implements Translator.
Definition at line 357 of file translator_adapter.h.
    { return english.trGlobalNamespace(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trGlobalNamespace().
trLoading() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trLoading () [inline], [virtual]
Implements Translator.
Definition at line 354 of file translator_adapter.h.
    { return english.trLoading(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trLoading().
trLoading() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trLoading () [inline], [virtual]
Implements Translator.
Definition at line 354 of file translator_adapter.h.
    { return english.trLoading(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trLoading().
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trMemberFunctionDocumentationFortran () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 366 of file translator_adapter.h.
    { return english.trMemberFunctionDocumentationFortran(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trMemberFunctionDocumentationFortran().
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trMemberFunctionDocumentationFortran () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 366 of file translator_adapter.h.
    { return english.trMemberFunctionDocumentationFortran(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trMemberFunctionDocumentationFortran().
trModule() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trModule (bool first_capital, bool singular) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 419 of file translator_adapter.h.
    { return english.trModule(first_capital,singular); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModule().
trModule() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trModule (bool first_capital, bool singular) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 419 of file translator_adapter.h.
    { return english.trModule(first_capital,singular); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModule().
trModuleReference() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trModuleReference (const QCString & namespaceName) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 407 of file translator_adapter.h.
    { return english.trModuleReference(namespaceName); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModuleReference().
trModuleReference() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trModuleReference (const QCString & namespaceName) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 407 of file translator_adapter.h.
    { return english.trModuleReference(namespaceName); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModuleReference().
trModulesIndex() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trModulesIndex () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 416 of file translator_adapter.h.
    { return english.trModulesIndex(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesIndex().
trModulesIndex() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trModulesIndex () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 416 of file translator_adapter.h.
    { return english.trModulesIndex(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesIndex().
trModulesList() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trModulesList () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 396 of file translator_adapter.h.
    { return english.trModulesList(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesList().
trModulesList() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trModulesList () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 396 of file translator_adapter.h.
    { return english.trModulesList(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesList().
trModulesListDescription() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trModulesListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 399 of file translator_adapter.h.
    { return english.trModulesListDescription(extractAll); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesListDescription().
trModulesListDescription() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trModulesListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 399 of file translator_adapter.h.
    { return english.trModulesListDescription(extractAll); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesListDescription().
trModulesMemberDescription() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trModulesMemberDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 413 of file translator_adapter.h.
    { return english.trModulesMemberDescription(extractAll); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesMemberDescription().
trModulesMemberDescription() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trModulesMemberDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 413 of file translator_adapter.h.
    { return english.trModulesMemberDescription(extractAll); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesMemberDescription().
trModulesMembers() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trModulesMembers () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 410 of file translator_adapter.h.
    { return english.trModulesMembers(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesMembers().
trModulesMembers() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trModulesMembers () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 410 of file translator_adapter.h.
    { return english.trModulesMembers(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesMembers().
trNoMatches() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trNoMatches () [inline], [virtual]
Implements Translator.
Definition at line 363 of file translator_adapter.h.
    { return english.trNoMatches(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trNoMatches().
trNoMatches() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trNoMatches () [inline], [virtual]
Implements Translator.
Definition at line 363 of file translator_adapter.h.
    { return english.trNoMatches(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trNoMatches().
trSearching() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trSearching () [inline], [virtual]
Implements Translator.
Definition at line 360 of file translator_adapter.h.
    { return english.trSearching(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSearching().
trSearching() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trSearching () [inline], [virtual]
Implements Translator.
Definition at line 360 of file translator_adapter.h.
    { return english.trSearching(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSearching().
trSubprogram() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 429 of file translator_adapter.h.
    { return english.trSubprogram(first_capital,singular); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSubprogram().
trSubprogram() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 429 of file translator_adapter.h.
    { return english.trSubprogram(first_capital,singular); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSubprogram().
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trSubprogramDocumentation () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 390 of file translator_adapter.h.
    { return english.trSubprogramDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSubprogramDocumentation().
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trSubprogramDocumentation () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 390 of file translator_adapter.h.
    { return english.trSubprogramDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSubprogramDocumentation().
trSubprograms() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trSubprograms () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 387 of file translator_adapter.h.
    { return english.trSubprograms(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSubprograms().
trSubprograms() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trSubprograms () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 387 of file translator_adapter.h.
    { return english.trSubprograms(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSubprograms().
trType() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trType (bool first_capital, bool singular) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 426 of file translator_adapter.h.
    { return english.trType(first_capital,singular); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trType().
trType() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trType (bool first_capital, bool singular) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 426 of file translator_adapter.h.
    { return english.trType(first_capital,singular); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trType().
trTypeConstraints() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trTypeConstraints () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 432 of file translator_adapter.h.
    { return english.trTypeConstraints(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trTypeConstraints().
trTypeConstraints() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trTypeConstraints () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 432 of file translator_adapter.h.
    { return english.trTypeConstraints(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trTypeConstraints().
trTypeDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_6_0::trTypeDocumentation () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 384 of file translator_adapter.h.
    { return english.trTypeDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trTypeDocumentation().
trTypeDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_6_0::trTypeDocumentation () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, TranslatorAfrikaans, TranslatorFinnish, TranslatorMacedonian, TranslatorSerbianCyrillic, TranslatorSerbian, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 384 of file translator_adapter.h.
    { return english.trTypeDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trTypeDocumentation().
updateNeededMessage() [1/2]
virtual QCString TranslatorAdapter_1_6_0::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_7_5.
Reimplemented in TranslatorAdapter_1_4_6, and TranslatorAdapter_1_4_6.
Definition at line 348 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.6.0"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
updateNeededMessage() [2/2]
virtual QCString TranslatorAdapter_1_6_0::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_7_5.
Reimplemented in TranslatorAdapter_1_4_6, and TranslatorAdapter_1_4_6.
Definition at line 348 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.6.0"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_adapter.h
doxygen/src/translator_adapter.h