DefinitionContext< T > Class Template Reference
Classes
struct Cachable
Public Member Functions
DefinitionContext (const Definition *d)
virtual ~DefinitionContext ()=default
DefinitionContext (const Definition *d)
virtual ~DefinitionContext ()=default
Protected Member Functions
TemplateVariant fileName () const
TemplateVariant anchor () const
TemplateVariant sourceFileName () const
TemplateVariant isLinkable () const
TemplateVariant isLinkableInProject () const
TemplateVariant name () const
TemplateVariant bareName () const
TemplateVariant details () const
TemplateVariant brief () const
TemplateVariant inbodyDocs () const
TemplateVariant dynSectionId () const
TemplateVariant sourceDef () const
TemplateVariant navigationPath () const
TemplateVariant partOfGroups () const
TemplateVariant isReference () const
TemplateVariant externalReference () const
TemplateVariant language () const
TemplateVariant compoundKind () const
QCString relPathAsString () const
virtual TemplateVariant relPath () const
TemplateVariant fileName () const
TemplateVariant anchor () const
TemplateVariant sourceFileName () const
TemplateVariant isLinkable () const
TemplateVariant isLinkableInProject () const
TemplateVariant name () const
TemplateVariant bareName () const
TemplateVariant details () const
TemplateVariant brief () const
TemplateVariant inbodyDocs () const
TemplateVariant dynSectionId () const
TemplateVariant sourceDef () const
TemplateVariant navigationPath () const
TemplateVariant partOfGroups () const
TemplateVariant isReference () const
TemplateVariant externalReference () const
TemplateVariant language () const
TemplateVariant compoundKind () const
QCString relPathAsString () const
virtual TemplateVariant relPath () const
Private Member Functions
TemplateVariant createDetails () const
TemplateVariant createBrief () const
TemplateVariant createInbodyDocs () const
void fillPath (const Definition *def, TemplateVariantList &list) const
TemplateListIntfPtr createNavigationPath () const
TemplateListIntfPtr createPartOfGroups () const
TemplateVariant createDetails () const
TemplateVariant createBrief () const
TemplateVariant createInbodyDocs () const
void fillPath (const Definition *def, TemplateVariantList &list) const
TemplateListIntfPtr createNavigationPath () const
TemplateListIntfPtr createPartOfGroups () const
Private Attributes
Cachable m_cachable
const Definition * m_def
TemplateListIntfPtr m_sourceDef
Static Private Attributes
static const PropertyMap< DefinitionContext< T > > s_baseProperties
Detailed Description
template<typename T>
class DefinitionContext< T >
Definition at line 1369 of file context.cpp.
Constructor & Destructor Documentation
DefinitionContext() [1/2]
template<typename T >
DefinitionContext< T >::DefinitionContext (const Definition * d) [inline]
Definition at line 1372 of file context.cpp.
                                           : m_def(d)
    {
      assert(d!=0);
      if (m_def && !m_def->getSourceFileBase().isEmpty())
      {
        TemplateStructIntfPtr lineLink = TemplateImmutableStruct::alloc(
        {
          { "text", TemplateVariant(m_def->getStartBodyLine()) },
          { "isLinkable", TemplateVariant(TRUE) },
          { "fileName", TemplateVariant(m_def->getSourceFileBase()) },
          { "anchor", TemplateVariant(m_def->getSourceAnchor()) },
          { "isReference", TemplateVariant(FALSE) },
          { "externalReference", TemplateVariant("") }
        });
        QCString text = m_def->definitionType()==Definition::TypeFile ? m_def->name() :
                                                  m_def->getBodyDef() ? m_def->getBodyDef()->name() :
                                                                        m_def->displayName(TRUE);
        TemplateStructIntfPtr fileLink = TemplateImmutableStruct::alloc(
        {
          { "text", TemplateVariant(text) },
          { "isLinkable", TemplateVariant(TRUE) },
          { "fileName", TemplateVariant(m_def->getSourceFileBase()) },
          { "anchor", TemplateVariant("") },
          { "isReference", TemplateVariant(FALSE) },
          { "externalReference", TemplateVariant("") }
        });
        m_sourceDef = TemplateImmutableList::alloc({ lineLink, fileLink });
      }
      else
      {
        m_sourceDef = TemplateImmutableList::alloc({});
      }
    }
References TemplateImmutableStruct::alloc(), TemplateImmutableList::alloc(), Definition::definitionType(), Definition::displayName(), FALSE, Definition::getBodyDef(), Definition::getSourceAnchor(), Definition::getSourceFileBase(), Definition::getStartBodyLine(), QCString::isEmpty(), DefinitionContext< T >::m_def, DefinitionContext< T >::m_sourceDef, Definition::name(), FileDef::name(), TRUE, and Definition::TypeFile.
 DefinitionContext() [1/2]
template<typename T >
virtual DefinitionContext< T >::~DefinitionContext () [virtual], [default]
DefinitionContext() [2/2]
template<typename T >
DefinitionContext< T >::DefinitionContext (const Definition * d) [inline]
Definition at line 1372 of file context.cpp.
                                           : m_def(d)
    {
      assert(d!=0);
      if (m_def && !m_def->getSourceFileBase().isEmpty())
      {
        TemplateStructIntfPtr lineLink = TemplateImmutableStruct::alloc(
        {
          { "text", TemplateVariant(m_def->getStartBodyLine()) },
          { "isLinkable", TemplateVariant(TRUE) },
          { "fileName", TemplateVariant(m_def->getSourceFileBase()) },
          { "anchor", TemplateVariant(m_def->getSourceAnchor()) },
          { "isReference", TemplateVariant(FALSE) },
          { "externalReference", TemplateVariant("") }
        });
        QCString text = m_def->definitionType()==Definition::TypeFile ? m_def->name() :
                                                  m_def->getBodyDef() ? m_def->getBodyDef()->name() :
                                                                        m_def->displayName(TRUE);
        TemplateStructIntfPtr fileLink = TemplateImmutableStruct::alloc(
        {
          { "text", TemplateVariant(text) },
          { "isLinkable", TemplateVariant(TRUE) },
          { "fileName", TemplateVariant(m_def->getSourceFileBase()) },
          { "anchor", TemplateVariant("") },
          { "isReference", TemplateVariant(FALSE) },
          { "externalReference", TemplateVariant("") }
        });
        m_sourceDef = TemplateImmutableList::alloc({ lineLink, fileLink });
      }
      else
      {
        m_sourceDef = TemplateImmutableList::alloc({});
      }
    }
References TemplateImmutableStruct::alloc(), TemplateImmutableList::alloc(), FALSE, TRUE, and Definition::TypeFile.
 DefinitionContext() [2/2]
template<typename T >
virtual DefinitionContext< T >::~DefinitionContext () [virtual], [default]
Member Function Documentation
anchor() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::anchor () const [inline], [protected]
Definition at line 1414 of file context.cpp.
{ return m_def->anchor(); }
References Definition::anchor(), and DefinitionContext< T >::m_def.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::anchor () const [inline], [protected]
Definition at line 1414 of file context.cpp.
{ return m_def->anchor(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
bareName() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::bareName () const [inline], [protected]
Definition at line 1419 of file context.cpp.
{ return m_def->displayName(FALSE); }
References Definition::displayName(), FALSE, and DefinitionContext< T >::m_def.
Referenced by res2cc_cmd.File::__init__(), res2cc_cmd.File::writeBytes(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
bareName() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::bareName () const [inline], [protected]
Definition at line 1419 of file context.cpp.
{ return m_def->displayName(FALSE); }
References FALSE.
Referenced by res2cc_cmd.File::__init__(), res2cc_cmd.File::writeBytes(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
brief() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::brief () const [inline], [protected]
Definition at line 1421 of file context.cpp.
{ return m_cachable.brief.get(this); }
References DefinitionContext< T >::Cachable::brief, and DefinitionContext< T >::m_cachable.
brief() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::brief () const [inline], [protected]
Definition at line 1421 of file context.cpp.
{ return m_cachable.brief.get(this); }
compoundKind() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::compoundKind () const [inline], [protected]
Definition at line 1455 of file context.cpp.
    {
      QCString result = "unspecified";
      switch (m_def->definitionType())
      {
        case Definition::TypeClass: result="class"; break;
        case Definition::TypeFile: result="file"; break;
        case Definition::TypeNamespace: result="namespace"; break;
        case Definition::TypeGroup: result="module"; break;
        case Definition::TypePackage: result="package"; break;
        case Definition::TypePage: result="page"; break;
        case Definition::TypeDir: result="dir"; break;
        case Definition::TypeConcept: result="concept"; break;
        case Definition::TypeMember: break;
      }
      return result;
    }
References Definition::definitionType(), DefinitionContext< T >::m_def, Definition::TypeClass, Definition::TypeConcept, Definition::TypeDir, Definition::TypeFile, Definition::TypeGroup, Definition::TypeMember, Definition::TypeNamespace, Definition::TypePackage, and Definition::TypePage.
compoundKind() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::compoundKind () const [inline], [protected]
Definition at line 1455 of file context.cpp.
    {
      QCString result = "unspecified";
      switch (m_def->definitionType())
      {
        case Definition::TypeClass: result="class"; break;
        case Definition::TypeFile: result="file"; break;
        case Definition::TypeNamespace: result="namespace"; break;
        case Definition::TypeGroup: result="module"; break;
        case Definition::TypePackage: result="package"; break;
        case Definition::TypePage: result="page"; break;
        case Definition::TypeDir: result="dir"; break;
        case Definition::TypeConcept: result="concept"; break;
        case Definition::TypeMember: break;
      }
      return result;
    }
References Definition::TypeClass, Definition::TypeConcept, Definition::TypeDir, Definition::TypeFile, Definition::TypeGroup, Definition::TypeMember, Definition::TypeNamespace, Definition::TypePackage, and Definition::TypePage.
createBrief() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::createBrief () const [inline], [private]
Definition at line 1490 of file context.cpp.
    {
      if (m_def->hasBriefDescription())
      {
        return TemplateVariant(parseDoc(m_def,m_def->briefFile(),m_def->briefLine(),
                               relPathAsString(),m_def->briefDescription(),TRUE));
      }
      else
      {
        return TemplateVariant("");
      }
    }
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Definition::hasBriefDescription(), DefinitionContext< T >::m_def, parseDoc(), DefinitionContext< T >::relPathAsString(), and TRUE.
createBrief() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::createBrief () const [inline], [private]
Definition at line 1490 of file context.cpp.
    {
      if (m_def->hasBriefDescription())
      {
        return TemplateVariant(parseDoc(m_def,m_def->briefFile(),m_def->briefLine(),
                               relPathAsString(),m_def->briefDescription(),TRUE));
      }
      else
      {
        return TemplateVariant("");
      }
    }
References parseDoc(), and TRUE.
createDetails() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::createDetails () const [inline], [private]
Definition at line 1485 of file context.cpp.
    {
      return TemplateVariant(parseDoc(m_def,m_def->docFile(),m_def->docLine(),
                                      relPathAsString(),m_def->documentation(),FALSE));
    }
References Definition::docFile(), Definition::docLine(), Definition::documentation(), FALSE, DefinitionContext< T >::m_def, parseDoc(), and DefinitionContext< T >::relPathAsString().
createDetails() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::createDetails () const [inline], [private]
Definition at line 1485 of file context.cpp.
    {
      return TemplateVariant(parseDoc(m_def,m_def->docFile(),m_def->docLine(),
                                      relPathAsString(),m_def->documentation(),FALSE));
    }
References FALSE, and parseDoc().
createInbodyDocs() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::createInbodyDocs () const [inline], [private]
Definition at line 1502 of file context.cpp.
    {
      if (!m_def->inbodyDocumentation().isEmpty())
      {
        return TemplateVariant(parseDoc(m_def,m_def->inbodyFile(),m_def->inbodyLine(),
                                        relPathAsString(),m_def->inbodyDocumentation(),FALSE));
      }
      else
      {
        return TemplateVariant("");
      }
    }
References FALSE, Definition::inbodyDocumentation(), Definition::inbodyFile(), Definition::inbodyLine(), QCString::isEmpty(), DefinitionContext< T >::m_def, parseDoc(), and DefinitionContext< T >::relPathAsString().
createInbodyDocs() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::createInbodyDocs () const [inline], [private]
Definition at line 1502 of file context.cpp.
    {
      if (!m_def->inbodyDocumentation().isEmpty())
      {
        return TemplateVariant(parseDoc(m_def,m_def->inbodyFile(),m_def->inbodyLine(),
                                        relPathAsString(),m_def->inbodyDocumentation(),FALSE));
      }
      else
      {
        return TemplateVariant("");
      }
    }
References FALSE, and parseDoc().
createNavigationPath() [1/2]
template<typename T >
TemplateListIntfPtr DefinitionContext< T >::createNavigationPath () const [inline], [private]
Definition at line 1528 of file context.cpp.
    {
      TemplateVariantList list;
      if (m_def->getOuterScope() && m_def->getOuterScope()!=Doxygen::globalScope)
      {
        fillPath(m_def,list);
      }
      else if (m_def->definitionType()==Definition::TypeFile && (toFileDef(m_def))->getDirDef())
      {
        fillPath((toFileDef(m_def))->getDirDef(),list);
      }
      return TemplateImmutableList::alloc(list);
    }
References TemplateImmutableList::alloc(), Definition::definitionType(), DefinitionContext< T >::fillPath(), Definition::getOuterScope(), Doxygen::globalScope, DefinitionContext< T >::m_def, toFileDef(), and Definition::TypeFile.
createNavigationPath() [2/2]
template<typename T >
TemplateListIntfPtr DefinitionContext< T >::createNavigationPath () const [inline], [private]
Definition at line 1528 of file context.cpp.
    {
      TemplateVariantList list;
      if (m_def->getOuterScope() && m_def->getOuterScope()!=Doxygen::globalScope)
      {
        fillPath(m_def,list);
      }
      else if (m_def->definitionType()==Definition::TypeFile && (toFileDef(m_def))->getDirDef())
      {
        fillPath((toFileDef(m_def))->getDirDef(),list);
      }
      return TemplateImmutableList::alloc(list);
    }
References TemplateImmutableList::alloc(), Doxygen::globalScope, toFileDef(), and Definition::TypeFile.
createPartOfGroups() [1/2]
template<typename T >
TemplateListIntfPtr DefinitionContext< T >::createPartOfGroups () const [inline], [private]
Definition at line 1541 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_def->partOfGroups().size());
      for (const auto &gd : m_def->partOfGroups())
      {
        list.push_back(ModuleContext::alloc(gd));
      }
      return TemplateImmutableList::alloc(list);
    }
References ModuleContext::alloc(), TemplateImmutableList::alloc(), DefinitionContext< T >::m_def, and Definition::partOfGroups().
createPartOfGroups() [2/2]
template<typename T >
TemplateListIntfPtr DefinitionContext< T >::createPartOfGroups () const [inline], [private]
Definition at line 1541 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_def->partOfGroups().size());
      for (const auto &gd : m_def->partOfGroups())
      {
        list.push_back(ModuleContext::alloc(gd));
      }
      return TemplateImmutableList::alloc(list);
    }
References ModuleContext::alloc(), and TemplateImmutableList::alloc().
details() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::details () const [inline], [protected]
Definition at line 1420 of file context.cpp.
{ return m_cachable.details.get(this); }
References DefinitionContext< T >::Cachable::details, and DefinitionContext< T >::m_cachable.
Referenced by doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_details(), doxmlparser.compound.docMarkupType::add_details(), doxmlparser.compound.docParaType::get_details(), doxmlparser.compound.docMarkupType::get_details(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docParaType::insert_details_at(), doxmlparser.compound.docMarkupType::insert_details_at(), doxmlparser.compound.docParaType::replace_details_at(), doxmlparser.compound.docMarkupType::replace_details_at(), doxmlparser.compound.docParaType::set_details(), and doxmlparser.compound.docMarkupType::set_details().
details() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::details () const [inline], [protected]
Definition at line 1420 of file context.cpp.
{ return m_cachable.details.get(this); }
Referenced by doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_details(), doxmlparser.compound.docMarkupType::add_details(), doxmlparser.compound.docParaType::get_details(), doxmlparser.compound.docMarkupType::get_details(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docParaType::insert_details_at(), doxmlparser.compound.docMarkupType::insert_details_at(), doxmlparser.compound.docParaType::replace_details_at(), doxmlparser.compound.docMarkupType::replace_details_at(), doxmlparser.compound.docParaType::set_details(), and doxmlparser.compound.docMarkupType::set_details().
dynSectionId() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::dynSectionId () const [inline], [protected]
Definition at line 1423 of file context.cpp.
{ return g_globals.dynSectionId; }
References ContextGlobals::dynSectionId, and g_globals.
dynSectionId() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::dynSectionId () const [inline], [protected]
Definition at line 1423 of file context.cpp.
{ return g_globals.dynSectionId; }
References ContextGlobals::dynSectionId, and g_globals.
externalReference() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::externalReference () const [inline], [protected]
Definition at line 1428 of file context.cpp.
{ return m_def->externalReference(relPathAsString()); }
References Definition::externalReference(), DefinitionContext< T >::m_def, and DefinitionContext< T >::relPathAsString().
externalReference() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::externalReference () const [inline], [protected]
Definition at line 1428 of file context.cpp.
{ return m_def->externalReference(relPathAsString()); }
fileName() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::fileName () const [inline], [protected]
Definition at line 1413 of file context.cpp.
{ return m_def->getOutputFileBase(); }
References Definition::getOutputFileBase(), and DefinitionContext< T >::m_def.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::fileName () const [inline], [protected]
Definition at line 1413 of file context.cpp.
{ return m_def->getOutputFileBase(); }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fillPath() [1/2]
template<typename T >
void DefinitionContext< T >::fillPath (const Definition * def, TemplateVariantList & list) const [inline], [private]
Definition at line 1514 of file context.cpp.
    {
      const Definition *outerScope = def->getOuterScope();
      Definition::DefType type = def->definitionType();
      if (outerScope && outerScope!=Doxygen::globalScope)
      {
        fillPath(outerScope,list);
      }
      else if (type==Definition::TypeFile && (toFileDef(def))->getDirDef())
      {
        fillPath((toFileDef(def))->getDirDef(),list);
      }
      list.push_back(NavPathElemContext::alloc(def));
    }
References NavPathElemContext::alloc(), Definition::definitionType(), DefinitionContext< T >::fillPath(), Definition::getOuterScope(), Doxygen::globalScope, toFileDef(), and Definition::TypeFile.
Referenced by DefinitionContext< T >::createNavigationPath(), and DefinitionContext< T >::fillPath().
fillPath() [2/2]
template<typename T >
void DefinitionContext< T >::fillPath (const Definition * def, TemplateVariantList & list) const [inline], [private]
Definition at line 1514 of file context.cpp.
    {
      const Definition *outerScope = def->getOuterScope();
      Definition::DefType type = def->definitionType();
      if (outerScope && outerScope!=Doxygen::globalScope)
      {
        fillPath(outerScope,list);
      }
      else if (type==Definition::TypeFile && (toFileDef(def))->getDirDef())
      {
        fillPath((toFileDef(def))->getDirDef(),list);
      }
      list.push_back(NavPathElemContext::alloc(def));
    }
References NavPathElemContext::alloc(), Definition::definitionType(), Definition::getOuterScope(), Doxygen::globalScope, toFileDef(), and Definition::TypeFile.
inbodyDocs() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::inbodyDocs () const [inline], [protected]
Definition at line 1422 of file context.cpp.
{ return m_cachable.inbodyDocs.get(this); }
References DefinitionContext< T >::Cachable::inbodyDocs, and DefinitionContext< T >::m_cachable.
inbodyDocs() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::inbodyDocs () const [inline], [protected]
Definition at line 1422 of file context.cpp.
{ return m_cachable.inbodyDocs.get(this); }
isLinkable() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::isLinkable () const [inline], [protected]
Definition at line 1416 of file context.cpp.
{ return m_def->isLinkable(); }
References Definition::isLinkable(), and DefinitionContext< T >::m_def.
isLinkable() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::isLinkable () const [inline], [protected]
Definition at line 1416 of file context.cpp.
{ return m_def->isLinkable(); }
isLinkableInProject() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::isLinkableInProject () const [inline], [protected]
Definition at line 1417 of file context.cpp.
{ return m_def->isLinkableInProject(); }
References Definition::isLinkableInProject(), and DefinitionContext< T >::m_def.
isLinkableInProject() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::isLinkableInProject () const [inline], [protected]
Definition at line 1417 of file context.cpp.
{ return m_def->isLinkableInProject(); }
isReference() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::isReference () const [inline], [protected]
Definition at line 1427 of file context.cpp.
{ return m_def->isReference(); }
References Definition::isReference(), and DefinitionContext< T >::m_def.
isReference() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::isReference () const [inline], [protected]
Definition at line 1427 of file context.cpp.
{ return m_def->isReference(); }
language() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::language () const [inline], [protected]
Definition at line 1429 of file context.cpp.
    {
      SrcLangExt lang = m_def->getLanguage();
      QCString result = "unknown";
      switch (lang)
      {
        case SrcLangExt_Unknown: break;
        case SrcLangExt_IDL: result="idl"; break;
        case SrcLangExt_Java: result="java"; break;
        case SrcLangExt_CSharp: result="csharp"; break;
        case SrcLangExt_D: result="d"; break;
        case SrcLangExt_PHP: result="php"; break;
        case SrcLangExt_ObjC: result="objc"; break;
        case SrcLangExt_Cpp: result="cpp"; break;
        case SrcLangExt_JS: result="js"; break;
        case SrcLangExt_Python: result="python"; break;
        case SrcLangExt_Fortran: result="fortran"; break;
        case SrcLangExt_VHDL: result="vhdl"; break;
        case SrcLangExt_XML: result="xml"; break;
        case SrcLangExt_SQL: result="sql"; break;
        case SrcLangExt_Markdown: result="markdown"; break;
        case SrcLangExt_Slice: result="slice"; break;
        case SrcLangExt_Lex: result="lex"; break;
      }
      return result;
    }
References Definition::getLanguage(), DefinitionContext< T >::m_def, SrcLangExt_Cpp, SrcLangExt_CSharp, SrcLangExt_D, SrcLangExt_Fortran, SrcLangExt_IDL, SrcLangExt_Java, SrcLangExt_JS, SrcLangExt_Lex, SrcLangExt_Markdown, SrcLangExt_ObjC, SrcLangExt_PHP, SrcLangExt_Python, SrcLangExt_Slice, SrcLangExt_SQL, SrcLangExt_Unknown, SrcLangExt_VHDL, and SrcLangExt_XML.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_language(), doxmlparser.compound.docMarkupType::add_language(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.compounddefType::get_language(), doxmlparser.compound.docParaType::get_language(), doxmlparser.compound.docMarkupType::get_language(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docParaType::insert_language_at(), doxmlparser.compound.docMarkupType::insert_language_at(), doxmlparser.compound.docParaType::replace_language_at(), doxmlparser.compound.docMarkupType::replace_language_at(), doxmlparser.compound.compounddefType::set_language(), doxmlparser.compound.docParaType::set_language(), and doxmlparser.compound.docMarkupType::set_language().
language() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::language () const [inline], [protected]
Definition at line 1429 of file context.cpp.
    {
      SrcLangExt lang = m_def->getLanguage();
      QCString result = "unknown";
      switch (lang)
      {
        case SrcLangExt_Unknown: break;
        case SrcLangExt_IDL: result="idl"; break;
        case SrcLangExt_Java: result="java"; break;
        case SrcLangExt_CSharp: result="csharp"; break;
        case SrcLangExt_D: result="d"; break;
        case SrcLangExt_PHP: result="php"; break;
        case SrcLangExt_ObjC: result="objc"; break;
        case SrcLangExt_Cpp: result="cpp"; break;
        case SrcLangExt_JS: result="js"; break;
        case SrcLangExt_Python: result="python"; break;
        case SrcLangExt_Fortran: result="fortran"; break;
        case SrcLangExt_VHDL: result="vhdl"; break;
        case SrcLangExt_XML: result="xml"; break;
        case SrcLangExt_SQL: result="sql"; break;
        case SrcLangExt_Markdown: result="markdown"; break;
        case SrcLangExt_Slice: result="slice"; break;
        case SrcLangExt_Lex: result="lex"; break;
      }
      return result;
    }
References SrcLangExt_Cpp, SrcLangExt_CSharp, SrcLangExt_D, SrcLangExt_Fortran, SrcLangExt_IDL, SrcLangExt_Java, SrcLangExt_JS, SrcLangExt_Lex, SrcLangExt_Markdown, SrcLangExt_ObjC, SrcLangExt_PHP, SrcLangExt_Python, SrcLangExt_Slice, SrcLangExt_SQL, SrcLangExt_Unknown, SrcLangExt_VHDL, and SrcLangExt_XML.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_language(), doxmlparser.compound.docMarkupType::add_language(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.compounddefType::get_language(), doxmlparser.compound.docParaType::get_language(), doxmlparser.compound.docMarkupType::get_language(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docParaType::insert_language_at(), doxmlparser.compound.docMarkupType::insert_language_at(), doxmlparser.compound.docParaType::replace_language_at(), doxmlparser.compound.docMarkupType::replace_language_at(), doxmlparser.compound.compounddefType::set_language(), doxmlparser.compound.docParaType::set_language(), and doxmlparser.compound.docMarkupType::set_language().
name() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::name () const [inline], [protected]
Definition at line 1418 of file context.cpp.
{ return m_def->displayName(TRUE); }
References Definition::displayName(), DefinitionContext< T >::m_def, and TRUE.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::name () const [inline], [protected]
Definition at line 1418 of file context.cpp.
{ return m_def->displayName(TRUE); }
References TRUE.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
navigationPath() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::navigationPath () const [inline], [protected]
Definition at line 1425 of file context.cpp.
{ return m_cachable.navPath.get(this); }
References DefinitionContext< T >::m_cachable, and DefinitionContext< T >::Cachable::navPath.
navigationPath() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::navigationPath () const [inline], [protected]
Definition at line 1425 of file context.cpp.
{ return m_cachable.navPath.get(this); }
partOfGroups() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::partOfGroups () const [inline], [protected]
Definition at line 1426 of file context.cpp.
{ return m_cachable.partOfGroups.get(this); }
References DefinitionContext< T >::m_cachable, and DefinitionContext< T >::Cachable::partOfGroups.
partOfGroups() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::partOfGroups () const [inline], [protected]
Definition at line 1426 of file context.cpp.
{ return m_cachable.partOfGroups.get(this); }
relPath() [1/2]
template<typename T >
virtual TemplateVariant DefinitionContext< T >::relPath () const [inline], [protected], [virtual]
Reimplemented in DirContext::Private, PageContext::Private, DirContext::Private, and PageContext::Private.
Definition at line 1480 of file context.cpp.
{ return relPathAsString(); }
References DefinitionContext< T >::relPathAsString().
relPath() [2/2]
template<typename T >
virtual TemplateVariant DefinitionContext< T >::relPath () const [inline], [protected], [virtual]
Reimplemented in DirContext::Private, PageContext::Private, DirContext::Private, and PageContext::Private.
Definition at line 1480 of file context.cpp.
{ return relPathAsString(); }
relPathAsString() [1/2]
template<typename T >
QCString DefinitionContext< T >::relPathAsString () const [inline], [protected]
Definition at line 1475 of file context.cpp.
    {
      bool createSubdirs = Config_getBool(CREATE_SUBDIRS);
      return createSubdirs ? QCString("../../") : QCString("");
    }
References Config_getBool.
Referenced by DefinitionContext< T >::createBrief(), DefinitionContext< T >::createDetails(), DefinitionContext< T >::createInbodyDocs(), DefinitionContext< T >::externalReference(), and DefinitionContext< T >::relPath().
relPathAsString() [2/2]
template<typename T >
QCString DefinitionContext< T >::relPathAsString () const [inline], [protected]
Definition at line 1475 of file context.cpp.
    {
      bool createSubdirs = Config_getBool(CREATE_SUBDIRS);
      return createSubdirs ? QCString("../../") : QCString("");
    }
References Config_getBool.
sourceDef() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::sourceDef () const [inline], [protected]
Definition at line 1424 of file context.cpp.
{ return std::static_pointer_cast<TemplateListIntf>(m_sourceDef); }
References DefinitionContext< T >::m_sourceDef.
sourceDef() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::sourceDef () const [inline], [protected]
Definition at line 1424 of file context.cpp.
{ return std::static_pointer_cast<TemplateListIntf>(m_sourceDef); }
sourceFileName() [1/2]
template<typename T >
TemplateVariant DefinitionContext< T >::sourceFileName () const [inline], [protected]
Definition at line 1415 of file context.cpp.
{ return m_def->getSourceFileBase(); }
References Definition::getSourceFileBase(), and DefinitionContext< T >::m_def.
sourceFileName() [2/2]
template<typename T >
TemplateVariant DefinitionContext< T >::sourceFileName () const [inline], [protected]
Definition at line 1415 of file context.cpp.
{ return m_def->getSourceFileBase(); }
Member Data Documentation
m_cachable
template<typename T >
Cachable DefinitionContext< T >::m_cachable [private]
Definition at line 1564 of file context.cpp.
Referenced by DefinitionContext< T >::brief(), DefinitionContext< T >::details(), DefinitionContext< T >::inbodyDocs(), DefinitionContext< T >::navigationPath(), and DefinitionContext< T >::partOfGroups().
m_def
template<typename T >
const Definition * DefinitionContext< T >::m_def [private]
Definition at line 1565 of file context.cpp.
Referenced by DefinitionContext< T >::anchor(), DefinitionContext< T >::bareName(), DefinitionContext< T >::compoundKind(), DefinitionContext< T >::createBrief(), DefinitionContext< T >::createDetails(), DefinitionContext< T >::createInbodyDocs(), DefinitionContext< T >::createNavigationPath(), DefinitionContext< T >::createPartOfGroups(), DefinitionContext< T >::DefinitionContext(), DefinitionContext< T >::externalReference(), DefinitionContext< T >::fileName(), DefinitionContext< T >::isLinkable(), DefinitionContext< T >::isLinkableInProject(), DefinitionContext< T >::isReference(), DefinitionContext< T >::language(), DefinitionContext< T >::name(), and DefinitionContext< T >::sourceFileName().
m_sourceDef
template<typename T >
TemplateListIntfPtr DefinitionContext< T >::m_sourceDef [private]
Definition at line 1566 of file context.cpp.
Referenced by DefinitionContext< T >::DefinitionContext(), and DefinitionContext< T >::sourceDef().
s_baseProperties
template<typename T >
static const PropertyMap< DefinitionContext< T > > DefinitionContext< T >::s_baseProperties [static], [private]
Definition at line 1567 of file context.cpp.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp