PythonCodeParser Class Reference
#include <pycode.h>
Classes
struct Private
Public Member Functions
PythonCodeParser ()
virtual ~PythonCodeParser ()
void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXrefs=TRUE)
void resetCodeParserState ()
PythonCodeParser ()
virtual ~PythonCodeParser ()
void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXrefs=TRUE)
void resetCodeParserState ()
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 34 of file pycode.h.
Constructor & Destructor Documentation
PythonCodeParser() [1/2]
PythonCodeParser::PythonCodeParser ()
Definition at line 1556 of file pycode.l.
                                   : p(std::make_unique<Private>())
{
  pycodeYYlex_init_extra(&p->state,&p->yyscanner);
#ifdef FLEX_DEBUG
  pycodeYYset_debug(1,p->yyscanner);
#endif
  resetCodeParserState();
}
References p, and resetCodeParserState().
 PythonCodeParser() [1/2]
PythonCodeParser::~PythonCodeParser () [virtual]
Definition at line 1565 of file pycode.l.
{
  pycodeYYlex_destroy(p->yyscanner);
}
References p.
PythonCodeParser() [2/2]
PythonCodeParser::PythonCodeParser ()
 PythonCodeParser() [2/2]
virtual PythonCodeParser::~PythonCodeParser () [virtual]
Member Function Documentation
parseCode() [1/2]
void PythonCodeParser::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
Definition at line 1582 of file pycode.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  //printf("***parseCode()\n");
  if (input.isEmpty()) return;
  printlex(yy_flex_debug, TRUE, __FILE__, fileDef ? qPrint(fileDef->fileName()): NULL);
  yyextra->fileName = fileDef ? fileDef->fileName():"";
  yyextra->code = &codeOutIntf;
  yyextra->inputString = input.data();
  yyextra->inputPosition = 0;
  yyextra->currentFontClass = 0;
  yyextra->insideCodeLine = FALSE;
  yyextra->searchCtx=searchCtx;
  yyextra->collectXRefs=collectXRefs;
  if (startLine!=-1)
    yyextra->yyLineNr = startLine;
  else
    yyextra->yyLineNr = 1;
  if (endLine!=-1)
    yyextra->inputLines = endLine+1;
  else
    yyextra->inputLines = yyextra->yyLineNr + countLines(yyscanner) - 1;
  yyextra->exampleBlock = isExampleBlock;
  yyextra->exampleName = exampleName;
  yyextra->sourceFileDef = fileDef;
  yyextra->symbolResolver.setFileScope(fileDef);
  bool cleanupSourceDef = FALSE;
  if (yyextra->exampleBlock && fileDef==0)
  {
    // create a dummy filedef for the example
    yyextra->sourceFileDef = createFileDef("",(!exampleName.isEmpty()?qPrint(exampleName):"generated"));
    cleanupSourceDef = TRUE;
  }
  if (yyextra->sourceFileDef)
  {
    setCurrentDoc(yyscanner,"l00001");
  }
  yyextra->includeCodeFragment = inlineFragment;
  // Starts line 1 on the output
  startCodeLine(yyscanner);
  pycodeYYrestart(0,yyscanner);
  pycodeYYlex(yyscanner);
  if (!yyextra->indents.empty())
  {
    // printf("Exited pysourceparser in inconsistent state!\n");
  }
  if (yyextra->insideCodeLine)
  {
    endCodeLine(yyscanner);
  }
  if (cleanupSourceDef)
  {
    // delete the temporary file definition used for this example
    delete yyextra->sourceFileDef;
    yyextra->sourceFileDef=0;
  }
  // write the tooltips
  yyextra->tooltipManager.writeTooltips(codeOutIntf);
  printlex(yy_flex_debug, FALSE, __FILE__, fileDef ? qPrint(fileDef->fileName()): NULL);
}
References countLines(), createFileDef(), QCString::data(), endCodeLine(), FALSE, FileDef::fileName(), QCString::isEmpty(), p, printlex(), qPrint(), setCurrentDoc(), startCodeLine(), and TRUE.
parseCode() [2/2]
void PythonCodeParser::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
resetCodeParserState() [1/2]
void PythonCodeParser::resetCodeParserState () [virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Definition at line 1570 of file pycode.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->codeClassMap.clear();
  yyextra->currentDefinition = 0;
  yyextra->currentMemberDef = 0;
  yyextra->doubleStringIsDoc = FALSE;
  yyextra->paramParens = 0;
  while (!yyextra->indents.empty()) yyextra->indents.pop();
  BEGIN(Body);
}
References FALSE, and p.
Referenced by PythonCodeParser().
resetCodeParserState() [2/2]
void PythonCodeParser::resetCodeParserState () [virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Member Data Documentation
p
std::unique_ptr< Private > PythonCodeParser::p [private]
Definition at line 57 of file pycode.h.
Referenced by parseCode(), PythonCodeParser(), resetCodeParserState(), and ~PythonCodeParser().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/pycode.h
doxygen/src/pycode.h
doxygen/build/doxygen/src/pycode.l
doxygen/src/pycode.l