MemberListInfoContext::Private Class Reference
Public Member Functions
Private (const Definition *def, const QCString &relPath, const MemberList *ml, const QCString &title, const QCString &subtitle)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (const Definition *def, const QCString &relPath, const MemberList *ml, const QCString &title, const QCString &subtitle)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant members () const
TemplateVariant title () const
TemplateVariant subtitle () const
TemplateVariant anchor () const
TemplateVariant memberGroups () const
TemplateVariant inherited () const
TemplateVariant createMemberList () const
TemplateVariant createMemberGroups () const
TemplateVariant createInherited () const
TemplateVariant members () const
TemplateVariant title () const
TemplateVariant subtitle () const
TemplateVariant anchor () const
TemplateVariant memberGroups () const
TemplateVariant inherited () const
TemplateVariant createMemberList () const
TemplateVariant createMemberGroups () const
TemplateVariant createInherited () const
Private Attributes
const Definition * m_def
const MemberList * m_memberList
QCString m_relPath
QCString m_title
QCString m_subtitle
CachedItem< TemplateVariant, Private, &Private::createMemberList > m_memberListCtx
CachedItem< TemplateVariant, Private, &Private::createMemberGroups > m_memberGroups
CachedItem< TemplateVariant, Private, &Private::createInherited > m_inherited
Static Private Attributes
static const PropertyMap< MemberListInfoContext::Private > s_inst
Detailed Description
Definition at line 7907 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
MemberListInfoContext::Private::Private (const Definition * def, const QCString & relPath, const MemberList * ml, const QCString & title, const QCString & subtitle) [inline]
Definition at line 7910 of file context.cpp.
      : m_def(def), m_memberList(ml), m_relPath(relPath), m_title(title), m_subtitle(subtitle) {}
Private() [2/2]
MemberListInfoContext::Private::Private (const Definition * def, const QCString & relPath, const MemberList * ml, const QCString & title, const QCString & subtitle) [inline]
Definition at line 7910 of file context.cpp.
      : m_def(def), m_memberList(ml), m_relPath(relPath), m_title(title), m_subtitle(subtitle) {}
Member Function Documentation
anchor() [1/2]
TemplateVariant MemberListInfoContext::Private::anchor () const [inline], [private]
Definition at line 7922 of file context.cpp.
{ return MemberList::listTypeAsString(m_memberList->listType()); }
References MemberList::listType(), MemberList::listTypeAsString(), and m_memberList.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
TemplateVariant MemberListInfoContext::Private::anchor () const [inline], [private]
Definition at line 7922 of file context.cpp.
{ return MemberList::listTypeAsString(m_memberList->listType()); }
References MemberList::listTypeAsString().
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
createInherited() [1/2]
TemplateVariant MemberListInfoContext::Private::createInherited () const [inline], [private]
Definition at line 7936 of file context.cpp.
    {
      if ((m_memberList->listType()&MemberListType_detailedLists)==0 &&
          m_def->definitionType()==Definition::TypeClass)
      {
        TemplateListIntfPtr list = InheritedMemberInfoListContext::alloc();
        auto ctx = std::dynamic_pointer_cast<InheritedMemberInfoListContext>(list);
        ctx->addMemberList(toClassDef(m_def),m_memberList->listType(),m_title,FALSE);
        return list;
      }
      else
      {
        return TemplateVariant(false);
      }
    }
References InheritedMemberInfoListContext::alloc(), Definition::definitionType(), FALSE, MemberList::listType(), m_def, m_memberList, m_title, MemberListType_detailedLists, toClassDef(), and Definition::TypeClass.
createInherited() [2/2]
TemplateVariant MemberListInfoContext::Private::createInherited () const [inline], [private]
Definition at line 7936 of file context.cpp.
    {
      if ((m_memberList->listType()&MemberListType_detailedLists)==0 &&
          m_def->definitionType()==Definition::TypeClass)
      {
        TemplateListIntfPtr list = InheritedMemberInfoListContext::alloc();
        auto ctx = std::dynamic_pointer_cast<InheritedMemberInfoListContext>(list);
        ctx->addMemberList(toClassDef(m_def),m_memberList->listType(),m_title,FALSE);
        return list;
      }
      else
      {
        return TemplateVariant(false);
      }
    }
References InheritedMemberInfoListContext::alloc(), FALSE, MemberListType_detailedLists, toClassDef(), and Definition::TypeClass.
createMemberGroups() [1/2]
TemplateVariant MemberListInfoContext::Private::createMemberGroups () const [inline], [private]
Definition at line 7932 of file context.cpp.
    {
      return MemberGroupListContext::alloc(m_def,m_relPath,m_memberList->getMemberGroupList());
    }
References MemberGroupListContext::alloc(), MemberList::getMemberGroupList(), m_def, m_memberList, and m_relPath.
createMemberGroups() [2/2]
TemplateVariant MemberListInfoContext::Private::createMemberGroups () const [inline], [private]
Definition at line 7932 of file context.cpp.
    {
      return MemberGroupListContext::alloc(m_def,m_relPath,m_memberList->getMemberGroupList());
    }
References MemberGroupListContext::alloc().
createMemberList() [1/2]
TemplateVariant MemberListInfoContext::Private::createMemberList () const [inline], [private]
Definition at line 7928 of file context.cpp.
    {
      return MemberListContext::alloc(m_memberList);
    }
References MemberListContext::alloc(), and m_memberList.
createMemberList() [2/2]
TemplateVariant MemberListInfoContext::Private::createMemberList () const [inline], [private]
Definition at line 7928 of file context.cpp.
    {
      return MemberListContext::alloc(m_memberList);
    }
References MemberListContext::alloc().
fields() [1/2]
StringVector MemberListInfoContext::Private::fields () const [inline]
Definition at line 7915 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector MemberListInfoContext::Private::fields () const [inline]
Definition at line 7915 of file context.cpp.
{ return s_inst.fields(); }
get() [1/2]
TemplateVariant MemberListInfoContext::Private::get (const QCString & n) const [inline]
Definition at line 7914 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant MemberListInfoContext::Private::get (const QCString & n) const [inline]
Definition at line 7914 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
inherited() [1/2]
TemplateVariant MemberListInfoContext::Private::inherited () const [inline], [private]
Definition at line 7924 of file context.cpp.
{ return m_inherited.get(this); }
References m_inherited.
inherited() [2/2]
TemplateVariant MemberListInfoContext::Private::inherited () const [inline], [private]
Definition at line 7924 of file context.cpp.
{ return m_inherited.get(this); }
memberGroups() [1/2]
TemplateVariant MemberListInfoContext::Private::memberGroups () const [inline], [private]
Definition at line 7923 of file context.cpp.
{ return m_memberGroups.get(this); }
References m_memberGroups.
memberGroups() [2/2]
TemplateVariant MemberListInfoContext::Private::memberGroups () const [inline], [private]
Definition at line 7923 of file context.cpp.
{ return m_memberGroups.get(this); }
members() [1/2]
TemplateVariant MemberListInfoContext::Private::members () const [inline], [private]
Definition at line 7919 of file context.cpp.
{ return m_memberListCtx.get(this); }
References m_memberListCtx.
members() [2/2]
TemplateVariant MemberListInfoContext::Private::members () const [inline], [private]
Definition at line 7919 of file context.cpp.
{ return m_memberListCtx.get(this); }
subtitle() [1/2]
TemplateVariant MemberListInfoContext::Private::subtitle () const [inline], [private]
Definition at line 7921 of file context.cpp.
{ return m_subtitle; }
References m_subtitle.
subtitle() [2/2]
TemplateVariant MemberListInfoContext::Private::subtitle () const [inline], [private]
Definition at line 7921 of file context.cpp.
{ return m_subtitle; }
title() [1/2]
TemplateVariant MemberListInfoContext::Private::title () const [inline], [private]
Definition at line 7920 of file context.cpp.
{ return m_title; }
References m_title.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant MemberListInfoContext::Private::title () const [inline], [private]
Definition at line 7920 of file context.cpp.
{ return m_title; }
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
Member Data Documentation
m_def
const Definition * MemberListInfoContext::Private::m_def [private]
Definition at line 7951 of file context.cpp.
Referenced by createInherited(), and createMemberGroups().
m_inherited
CachedItem< TemplateVariant, Private, &Private::createInherited > MemberListInfoContext::Private::m_inherited [private]
Definition at line 7958 of file context.cpp.
Referenced by inherited().
m_memberGroups
CachedItem< TemplateVariant, Private, &Private::createMemberGroups > MemberListInfoContext::Private::m_memberGroups [private]
Definition at line 7957 of file context.cpp.
Referenced by memberGroups().
m_memberList
const MemberList * MemberListInfoContext::Private::m_memberList [private]
Definition at line 7952 of file context.cpp.
Referenced by anchor(), createInherited(), createMemberGroups(), and createMemberList().
m_memberListCtx
CachedItem< TemplateVariant, Private, &Private::createMemberList > MemberListInfoContext::Private::m_memberListCtx [private]
Definition at line 7956 of file context.cpp.
Referenced by members().
m_relPath
QCString MemberListInfoContext::Private::m_relPath [private]
Definition at line 7953 of file context.cpp.
Referenced by createMemberGroups().
m_subtitle
QCString MemberListInfoContext::Private::m_subtitle [private]
Definition at line 7955 of file context.cpp.
Referenced by subtitle().
m_title
QCString MemberListInfoContext::Private::m_title [private]
Definition at line 7954 of file context.cpp.
Referenced by createInherited(), and title().
s_inst
const PropertyMap< MemberListInfoContext::Private > MemberListInfoContext::Private::s_inst [static], [private]
Initial value:
{
  { "members", &Private::members },
  { "title", &Private::title },
  { "subtitle", &Private::subtitle },
  { "anchor", &Private::anchor },
  { "memberGroups", &Private::memberGroups },
  { "inherited", &Private::inherited }
}
Definition at line 7959 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp