SectionInfo Class Reference
class that provide information about a section.
#include <section.h>
Public Member Functions
SectionInfo (const QCString &label, const QCString &fileName, int lineNr, const QCString &title, SectionType type, int level, const QCString &ref)
~SectionInfo ()
QCString label () const
QCString title () const
SectionType type () const
QCString ref () const
int lineNr () const
QCString fileName () const
bool generated () const
int level () const
Definition * definition () const
void setFileName (const QCString &fn)
void setType (SectionType t)
void setGenerated (bool b)
void setDefinition (Definition *d)
void setTitle (const QCString &t)
void setLevel (int l)
void setReference (const QCString &r)
void setLineNr (int l)
SectionInfo (const QCString &label, const QCString &fileName, int lineNr, const QCString &title, SectionType type, int level, const QCString &ref)
~SectionInfo ()
QCString label () const
QCString title () const
SectionType type () const
QCString ref () const
int lineNr () const
QCString fileName () const
bool generated () const
int level () const
Definition * definition () const
void setFileName (const QCString &fn)
void setType (SectionType t)
void setGenerated (bool b)
void setDefinition (Definition *d)
void setTitle (const QCString &t)
void setLevel (int l)
void setReference (const QCString &r)
void setLineNr (int l)
Private Attributes
QCString m_label
QCString m_title
SectionType m_type
QCString m_ref
int m_lineNr
QCString m_fileName
bool m_generated = false
int m_level
Definition * m_definition = 0
Detailed Description
class that provide information about a section.
Definition at line 49 of file section.h.
Constructor & Destructor Documentation
SectionInfo() [1/2]
SectionInfo::SectionInfo (const QCString & label, const QCString & fileName, int lineNr, const QCString & title, SectionType type, int level, const QCString & ref) [inline]
Definition at line 52 of file section.h.
                                                                                        :
        m_label(label), m_title(title), m_type(type), m_ref(ref),
        m_lineNr(lineNr), m_fileName(fileName), m_level(level)
    {
      //printf("SectionInfo(%p)\n",this);
    }
 SectionInfo() [1/2]
SectionInfo::~SectionInfo () [inline]
Definition at line 59 of file section.h.
    {
      //printf("~SectionInfo(%p)\n",this);
    }
SectionInfo() [2/2]
SectionInfo::SectionInfo (const QCString & label, const QCString & fileName, int lineNr, const QCString & title, SectionType type, int level, const QCString & ref) [inline]
Definition at line 52 of file section.h.
                                                                                        :
        m_label(label), m_title(title), m_type(type), m_ref(ref),
        m_lineNr(lineNr), m_fileName(fileName), m_level(level)
    {
      //printf("SectionInfo(%p)\n",this);
    }
 SectionInfo() [2/2]
SectionInfo::~SectionInfo () [inline]
Definition at line 59 of file section.h.
    {
      //printf("~SectionInfo(%p)\n",this);
    }
Member Function Documentation
definition() [1/2]
Definition * SectionInfo::definition () const [inline]
Definition at line 73 of file section.h.
{ return m_definition; }
References m_definition.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_definition(), doxmlparser.compound.memberdefType::hasContent_(), resolveLink(), and doxmlparser.compound.memberdefType::set_definition().
definition() [2/2]
Definition * SectionInfo::definition () const [inline]
Definition at line 73 of file section.h.
{ return m_definition; }
References m_definition.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_definition(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_definition().
fileName() [1/2]
QCString SectionInfo::fileName () const [inline]
Definition at line 70 of file section.h.
{ return m_fileName; }
References m_fileName.
Referenced by res2cc_cmd.File::__init__(), SectionManager::add(), addAnchor(), addRelatedPage(), addSection(), addXRefItem(), DocAnchor::DocAnchor(), DocHtmlCaption::DocHtmlCaption(), DocRef::DocRef(), findMainPage(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), DocSection::parse(), DocSecRefItem::parse(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), res2cc_cmd.LumaFile::writeDirEntry(), and DefinitionImpl::writeDocAnchorsToTagFile().
fileName() [2/2]
QCString SectionInfo::fileName () const [inline]
Definition at line 70 of file section.h.
{ return m_fileName; }
References m_fileName.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
generated() [1/2]
bool SectionInfo::generated () const [inline]
Definition at line 71 of file section.h.
{ return m_generated; }
References m_generated.
Referenced by DefinitionImpl::writeDocAnchorsToTagFile().
generated() [2/2]
bool SectionInfo::generated () const [inline]
Definition at line 71 of file section.h.
{ return m_generated; }
References m_generated.
label() [1/2]
QCString SectionInfo::label () const [inline]
Definition at line 65 of file section.h.
{ return m_label; }
References m_label.
Referenced by doxmlparser.compound.nodeType::__init__(), SectionManager::add(), SectionRefs::add(), DefinitionImpl::addSectionsToDefinition(), DefinitionImpl::addSectionsToIndex(), doxmlparser.compound.nodeType::buildChildren(), DocAnchor::DocAnchor(), DocHtmlCaption::DocHtmlCaption(), DocRef::DocRef(), doxmlparser.compound.nodeType::exportChildren(), doxmlparser.compound.nodeType::get_label(), doxmlparser.compound.nodeType::hasContent_(), DocSection::parse(), DocSecRefItem::parse(), resolveLink(), doxmlparser.compound.nodeType::set_label(), DefinitionImpl::writeDocAnchorsToTagFile(), PageDefImpl::writeDocumentation(), writeGroupTreeNode(), GroupDefImpl::writePageDocumentation(), and DefinitionImpl::writeToc().
label() [2/2]
QCString SectionInfo::label () const [inline]
Definition at line 65 of file section.h.
{ return m_label; }
References m_label.
Referenced by doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.nodeType::buildChildren(), doxmlparser.compound.nodeType::exportChildren(), doxmlparser.compound.nodeType::get_label(), doxmlparser.compound.nodeType::hasContent_(), and doxmlparser.compound.nodeType::set_label().
level() [1/2]
int SectionInfo::level () const [inline]
Definition at line 72 of file section.h.
{ return m_level; }
References m_level.
Referenced by doxmlparser.compound.docHeadingType::__init__(), SectionManager::add(), doxmlparser.compound.docHeadingType::buildAttributes(), doxmlparser.compound.docHeadingType::exportAttributes(), doxmlparser.compound.docHeadingType::get_level(), and doxmlparser.compound.docHeadingType::set_level().
level() [2/2]
int SectionInfo::level () const [inline]
Definition at line 72 of file section.h.
{ return m_level; }
References m_level.
Referenced by doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docHeadingType::buildAttributes(), doxmlparser.compound.docHeadingType::exportAttributes(), doxmlparser.compound.docHeadingType::get_level(), and doxmlparser.compound.docHeadingType::set_level().
lineNr() [1/2]
int SectionInfo::lineNr () const [inline]
Definition at line 69 of file section.h.
{ return m_lineNr; }
References m_lineNr.
Referenced by SectionManager::add(), addAnchor(), addRelatedPage(), addSection(), addXRefItem(), and findMainPage().
lineNr() [2/2]
int SectionInfo::lineNr () const [inline]
Definition at line 69 of file section.h.
{ return m_lineNr; }
References m_lineNr.
ref() [1/2]
QCString SectionInfo::ref () const [inline]
Definition at line 68 of file section.h.
{ return m_ref; }
References m_ref.
Referenced by doxmlparser.compound.highlightType::__init__(), doxmlparser.compound.docParamName::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.linkedTextType::__init__(), doxmlparser.compound.docParamType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), SectionManager::add(), doxmlparser.compound.linkedTextType::add_ref(), doxmlparser.compound.highlightType::add_ref(), doxmlparser.compound.docTitleType::add_ref(), doxmlparser.compound.docSummaryType::add_ref(), doxmlparser.compound.docParaType::add_ref(), doxmlparser.compound.docMarkupType::add_ref(), doxmlparser.compound.docURLLink::add_ref(), doxmlparser.compound.docRefTextType::add_ref(), doxmlparser.compound.docCaptionType::add_ref(), doxmlparser.compound.docHeadingType::add_ref(), doxmlparser.compound.docImageType::add_ref(), doxmlparser.compound.docDotMscType::add_ref(), doxmlparser.compound.docImageFileType::add_ref(), doxmlparser.compound.docPlantumlType::add_ref(), doxmlparser.compound.docTocItemType::add_ref(), addAnchor(), addRelatedPage(), addSection(), addXRefItem(), DocRef::DocRef(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docParamName::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.highlightType::exportChildren(), findMainPage(), doxmlparser.compound.linkedTextType::get_ref(), doxmlparser.compound.highlightType::get_ref(), doxmlparser.compound.docTitleType::get_ref(), doxmlparser.compound.docSummaryType::get_ref(), doxmlparser.compound.docParaType::get_ref(), doxmlparser.compound.docMarkupType::get_ref(), doxmlparser.compound.docURLLink::get_ref(), doxmlparser.compound.docRefTextType::get_ref(), doxmlparser.compound.docCaptionType::get_ref(), doxmlparser.compound.docHeadingType::get_ref(), doxmlparser.compound.docImageType::get_ref(), doxmlparser.compound.docDotMscType::get_ref(), doxmlparser.compound.docImageFileType::get_ref(), doxmlparser.compound.docPlantumlType::get_ref(), doxmlparser.compound.docTocItemType::get_ref(), doxmlparser.compound.docParamType::get_ref(), doxmlparser.compound.docParamName::get_ref(), doxmlparser.compound.linkedTextType::hasContent_(), doxmlparser.compound.highlightType::hasContent_(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docParamType::hasContent_(), doxmlparser.compound.docParamName::hasContent_(), doxmlparser.compound.linkedTextType::insert_ref_at(), doxmlparser.compound.highlightType::insert_ref_at(), doxmlparser.compound.docTitleType::insert_ref_at(), doxmlparser.compound.docSummaryType::insert_ref_at(), doxmlparser.compound.docParaType::insert_ref_at(), doxmlparser.compound.docMarkupType::insert_ref_at(), doxmlparser.compound.docURLLink::insert_ref_at(), doxmlparser.compound.docRefTextType::insert_ref_at(), doxmlparser.compound.docCaptionType::insert_ref_at(), doxmlparser.compound.docHeadingType::insert_ref_at(), doxmlparser.compound.docImageType::insert_ref_at(), doxmlparser.compound.docDotMscType::insert_ref_at(), doxmlparser.compound.docImageFileType::insert_ref_at(), doxmlparser.compound.docPlantumlType::insert_ref_at(), doxmlparser.compound.docTocItemType::insert_ref_at(), DocSecRefItem::parse(), doxmlparser.compound.linkedTextType::replace_ref_at(), doxmlparser.compound.highlightType::replace_ref_at(), doxmlparser.compound.docTitleType::replace_ref_at(), doxmlparser.compound.docSummaryType::replace_ref_at(), doxmlparser.compound.docParaType::replace_ref_at(), doxmlparser.compound.docMarkupType::replace_ref_at(), doxmlparser.compound.docURLLink::replace_ref_at(), doxmlparser.compound.docRefTextType::replace_ref_at(), doxmlparser.compound.docCaptionType::replace_ref_at(), doxmlparser.compound.docHeadingType::replace_ref_at(), doxmlparser.compound.docImageType::replace_ref_at(), doxmlparser.compound.docDotMscType::replace_ref_at(), doxmlparser.compound.docImageFileType::replace_ref_at(), doxmlparser.compound.docPlantumlType::replace_ref_at(), doxmlparser.compound.docTocItemType::replace_ref_at(), doxmlparser.compound.linkedTextType::set_ref(), doxmlparser.compound.highlightType::set_ref(), doxmlparser.compound.docTitleType::set_ref(), doxmlparser.compound.docSummaryType::set_ref(), doxmlparser.compound.docParaType::set_ref(), doxmlparser.compound.docMarkupType::set_ref(), doxmlparser.compound.docURLLink::set_ref(), doxmlparser.compound.docRefTextType::set_ref(), doxmlparser.compound.docCaptionType::set_ref(), doxmlparser.compound.docHeadingType::set_ref(), doxmlparser.compound.docImageType::set_ref(), doxmlparser.compound.docDotMscType::set_ref(), doxmlparser.compound.docImageFileType::set_ref(), doxmlparser.compound.docPlantumlType::set_ref(), doxmlparser.compound.docTocItemType::set_ref(), doxmlparser.compound.docParamType::set_ref(), doxmlparser.compound.docParamName::set_ref(), and DefinitionImpl::writeDocAnchorsToTagFile().
ref() [2/2]
QCString SectionInfo::ref () const [inline]
Definition at line 68 of file section.h.
{ return m_ref; }
References m_ref.
Referenced by doxmlparser.compound.highlightType::__init__(), doxmlparser.compound.docParamName::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.linkedTextType::__init__(), doxmlparser.compound.docParamType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.linkedTextType::add_ref(), doxmlparser.compound.highlightType::add_ref(), doxmlparser.compound.docTitleType::add_ref(), doxmlparser.compound.docSummaryType::add_ref(), doxmlparser.compound.docParaType::add_ref(), doxmlparser.compound.docMarkupType::add_ref(), doxmlparser.compound.docURLLink::add_ref(), doxmlparser.compound.docRefTextType::add_ref(), doxmlparser.compound.docCaptionType::add_ref(), doxmlparser.compound.docHeadingType::add_ref(), doxmlparser.compound.docImageType::add_ref(), doxmlparser.compound.docDotMscType::add_ref(), doxmlparser.compound.docImageFileType::add_ref(), doxmlparser.compound.docPlantumlType::add_ref(), doxmlparser.compound.docTocItemType::add_ref(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docParamName::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.highlightType::exportChildren(), doxmlparser.compound.linkedTextType::get_ref(), doxmlparser.compound.highlightType::get_ref(), doxmlparser.compound.docTitleType::get_ref(), doxmlparser.compound.docSummaryType::get_ref(), doxmlparser.compound.docParaType::get_ref(), doxmlparser.compound.docMarkupType::get_ref(), doxmlparser.compound.docURLLink::get_ref(), doxmlparser.compound.docRefTextType::get_ref(), doxmlparser.compound.docCaptionType::get_ref(), doxmlparser.compound.docHeadingType::get_ref(), doxmlparser.compound.docImageType::get_ref(), doxmlparser.compound.docDotMscType::get_ref(), doxmlparser.compound.docImageFileType::get_ref(), doxmlparser.compound.docPlantumlType::get_ref(), doxmlparser.compound.docTocItemType::get_ref(), doxmlparser.compound.docParamType::get_ref(), doxmlparser.compound.docParamName::get_ref(), doxmlparser.compound.linkedTextType::hasContent_(), doxmlparser.compound.highlightType::hasContent_(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docParamType::hasContent_(), doxmlparser.compound.docParamName::hasContent_(), doxmlparser.compound.linkedTextType::insert_ref_at(), doxmlparser.compound.highlightType::insert_ref_at(), doxmlparser.compound.docTitleType::insert_ref_at(), doxmlparser.compound.docSummaryType::insert_ref_at(), doxmlparser.compound.docParaType::insert_ref_at(), doxmlparser.compound.docMarkupType::insert_ref_at(), doxmlparser.compound.docURLLink::insert_ref_at(), doxmlparser.compound.docRefTextType::insert_ref_at(), doxmlparser.compound.docCaptionType::insert_ref_at(), doxmlparser.compound.docHeadingType::insert_ref_at(), doxmlparser.compound.docImageType::insert_ref_at(), doxmlparser.compound.docDotMscType::insert_ref_at(), doxmlparser.compound.docImageFileType::insert_ref_at(), doxmlparser.compound.docPlantumlType::insert_ref_at(), doxmlparser.compound.docTocItemType::insert_ref_at(), doxmlparser.compound.linkedTextType::replace_ref_at(), doxmlparser.compound.highlightType::replace_ref_at(), doxmlparser.compound.docTitleType::replace_ref_at(), doxmlparser.compound.docSummaryType::replace_ref_at(), doxmlparser.compound.docParaType::replace_ref_at(), doxmlparser.compound.docMarkupType::replace_ref_at(), doxmlparser.compound.docURLLink::replace_ref_at(), doxmlparser.compound.docRefTextType::replace_ref_at(), doxmlparser.compound.docCaptionType::replace_ref_at(), doxmlparser.compound.docHeadingType::replace_ref_at(), doxmlparser.compound.docImageType::replace_ref_at(), doxmlparser.compound.docDotMscType::replace_ref_at(), doxmlparser.compound.docImageFileType::replace_ref_at(), doxmlparser.compound.docPlantumlType::replace_ref_at(), doxmlparser.compound.docTocItemType::replace_ref_at(), doxmlparser.compound.linkedTextType::set_ref(), doxmlparser.compound.highlightType::set_ref(), doxmlparser.compound.docTitleType::set_ref(), doxmlparser.compound.docSummaryType::set_ref(), doxmlparser.compound.docParaType::set_ref(), doxmlparser.compound.docMarkupType::set_ref(), doxmlparser.compound.docURLLink::set_ref(), doxmlparser.compound.docRefTextType::set_ref(), doxmlparser.compound.docCaptionType::set_ref(), doxmlparser.compound.docHeadingType::set_ref(), doxmlparser.compound.docImageType::set_ref(), doxmlparser.compound.docDotMscType::set_ref(), doxmlparser.compound.docImageFileType::set_ref(), doxmlparser.compound.docPlantumlType::set_ref(), doxmlparser.compound.docTocItemType::set_ref(), doxmlparser.compound.docParamType::set_ref(), and doxmlparser.compound.docParamName::set_ref().
setDefinition() [1/2]
void SectionInfo::setDefinition (Definition * d) [inline]
Definition at line 79 of file section.h.
{ m_definition = d; }
References m_definition.
Referenced by DefinitionImpl::addSectionsToDefinition().
setDefinition() [2/2]
void SectionInfo::setDefinition (Definition * d) [inline]
Definition at line 79 of file section.h.
{ m_definition = d; }
References m_definition.
setFileName() [1/2]
void SectionInfo::setFileName (const QCString & fn) [inline]
Definition at line 76 of file section.h.
{ m_fileName = fn; }
References m_fileName.
Referenced by processSection(), and SectionManager::replace().
setFileName() [2/2]
void SectionInfo::setFileName (const QCString & fn) [inline]
Definition at line 76 of file section.h.
{ m_fileName = fn; }
References m_fileName.
setGenerated() [1/2]
void SectionInfo::setGenerated (bool b) [inline]
Definition at line 78 of file section.h.
{ m_generated = b; }
References b, and m_generated.
setGenerated() [2/2]
void SectionInfo::setGenerated (bool b) [inline]
Definition at line 78 of file section.h.
{ m_generated = b; }
References b, and m_generated.
setLevel() [1/2]
void SectionInfo::setLevel (int l) [inline]
Definition at line 81 of file section.h.
{ m_level = l; }
References m_level.
Referenced by SectionManager::replace().
setLevel() [2/2]
void SectionInfo::setLevel (int l) [inline]
Definition at line 81 of file section.h.
{ m_level = l; }
References m_level.
setLineNr() [1/2]
void SectionInfo::setLineNr (int l) [inline]
Definition at line 83 of file section.h.
{ m_lineNr = l; }
References m_lineNr.
Referenced by SectionManager::replace().
setLineNr() [2/2]
void SectionInfo::setLineNr (int l) [inline]
Definition at line 83 of file section.h.
{ m_lineNr = l; }
References m_lineNr.
setReference() [1/2]
void SectionInfo::setReference (const QCString & r) [inline]
Definition at line 82 of file section.h.
{ m_ref = r; }
References m_ref, and r.
Referenced by SectionManager::replace().
setReference() [2/2]
void SectionInfo::setReference (const QCString & r) [inline]
Definition at line 82 of file section.h.
{ m_ref = r; }
References m_ref, and r.
setTitle() [1/2]
void SectionInfo::setTitle (const QCString & t) [inline]
Definition at line 80 of file section.h.
{ m_title = t; }
References m_title.
Referenced by addRelatedPage(), and SectionManager::replace().
setTitle() [2/2]
void SectionInfo::setTitle (const QCString & t) [inline]
Definition at line 80 of file section.h.
{ m_title = t; }
References m_title.
setType() [1/2]
void SectionInfo::setType (SectionType t) [inline]
Definition at line 77 of file section.h.
{ m_type = t; }
References m_type.
Referenced by processSection(), and SectionManager::replace().
setType() [2/2]
void SectionInfo::setType (SectionType t) [inline]
Definition at line 77 of file section.h.
{ m_type = t; }
References m_type.
title() [1/2]
QCString SectionInfo::title () const [inline]
Definition at line 66 of file section.h.
{ return m_title; }
References m_title.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), SectionManager::add(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), DefinitionImpl::addSectionsToIndex(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), DocRef::DocRef(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), PerlModGenerator::generatePerlModForPage(), generateXMLForPage(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), DocSection::parse(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), DefinitionImpl::writeDocAnchorsToTagFile(), PageDefImpl::writeDocumentation(), GroupDefImpl::writePageDocumentation(), and DefinitionImpl::writeToc().
title() [2/2]
QCString SectionInfo::title () const [inline]
Definition at line 66 of file section.h.
{ return m_title; }
References m_title.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
type() [1/2]
SectionType SectionInfo::type () const [inline]
Definition at line 67 of file section.h.
{ return m_type; }
References m_type.
Referenced by SectionManager::add(), DefinitionImpl::addSectionsToIndex(), DocRef::DocRef(), DefinitionImpl::hasSections(), DocSecRefItem::parse(), PageDefImpl::writeDocumentation(), and DefinitionImpl::writeToc().
type() [2/2]
SectionType SectionInfo::type () const [inline]
Definition at line 67 of file section.h.
{ return m_type; }
References m_type.
Member Data Documentation
m_definition
Definition * SectionInfo::m_definition = 0 [private]
Definition at line 94 of file section.h.
Referenced by definition(), and setDefinition().
m_fileName
QCString SectionInfo::m_fileName [private]
Definition at line 91 of file section.h.
Referenced by fileName(), and setFileName().
m_generated
bool SectionInfo::m_generated = false [private]
Definition at line 92 of file section.h.
Referenced by generated(), and setGenerated().
m_label
QCString SectionInfo::m_label [private]
Definition at line 86 of file section.h.
Referenced by label().
m_level
int SectionInfo::m_level [private]
Definition at line 93 of file section.h.
Referenced by level(), and setLevel().
m_lineNr
int SectionInfo::m_lineNr [private]
Definition at line 90 of file section.h.
Referenced by lineNr(), and setLineNr().
m_ref
QCString SectionInfo::m_ref [private]
Definition at line 89 of file section.h.
Referenced by ref(), and setReference().
m_title
QCString SectionInfo::m_title [private]
Definition at line 87 of file section.h.
Referenced by setTitle(), and title().
m_type
SectionType SectionInfo::m_type [private]
Definition at line 88 of file section.h.
Referenced by setType(), and type().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/section.h
doxygen/src/section.h