LatexDocVisitor Class Reference
Concrete visitor implementation for LaTeX output.
#include <latexdocvisitor.h>
Classes
struct ActiveRowSpan
struct LatexListItemInfo
struct TableState
Public Member Functions
LatexDocVisitor (TextStream &t, LatexCodeGenerator &ci, const QCString &langExt, bool insideTabbing)
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &s)
void operator() (const DocHtmlList &s)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &t)
void operator() (const DocHtmlCaption &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &lnk)
void operator() (const DocRef &ref)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
LatexDocVisitor (TextStream &t, LatexCodeGenerator &ci, const QCString &langExt, bool insideTabbing)
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &s)
void operator() (const DocHtmlList &s)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &t)
void operator() (const DocHtmlCaption &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &lnk)
void operator() (const DocRef &ref)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
Private Types
typedef std::vector< ActiveRowSpan > RowSpanList
typedef std::vector< ActiveRowSpan > RowSpanList
Private Member Functions
template<class T >
void visitChildren (const T &t)
void filter (const QCString &str, const bool retainNewLine=false)
void startLink (const QCString &ref, const QCString &file, const QCString &anchor, bool refToTable=FALSE)
void endLink (const QCString &ref, const QCString &file, const QCString &anchor, bool refToTable=FALSE)
QCString escapeMakeIndexChars (const char *s)
void startDotFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption, const QCString &srcFile, int srcLine)
void endDotFile (bool hasCaption)
void startMscFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption, const QCString &srcFile, int srcLine)
void endMscFile (bool hasCaption)
void writeMscFile (const QCString &fileName, const DocVerbatim &s)
void startDiaFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption, const QCString &srcFile, int srcLine)
void endDiaFile (bool hasCaption)
void writeDiaFile (const QCString &fileName, const DocVerbatim &s)
void writePlantUMLFile (const QCString &fileName, const DocVerbatim &s)
void visitCaption (const DocNodeList &children)
void incIndentLevel ()
void decIndentLevel ()
int indentLevel () const
void pushTableState ()
void popTableState ()
size_t currentColumn () const
void setCurrentColumn (size_t col)
size_t numCols () const
void setNumCols (size_t num)
bool inRowSpan () const
void setInRowSpan (bool b)
bool inColSpan () const
void setInColSpan (bool b)
bool firstRow () const
void setFirstRow (bool b)
RowSpanList & rowSpans ()
void addRowSpan (ActiveRowSpan &&span)
bool insideTable () const
template<class T >
void visitChildren (const T &t)
void filter (const QCString &str, const bool retainNewLine=false)
void startLink (const QCString &ref, const QCString &file, const QCString &anchor, bool refToTable=FALSE)
void endLink (const QCString &ref, const QCString &file, const QCString &anchor, bool refToTable=FALSE)
QCString escapeMakeIndexChars (const char *s)
void startDotFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption, const QCString &srcFile, int srcLine)
void endDotFile (bool hasCaption)
void startMscFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption, const QCString &srcFile, int srcLine)
void endMscFile (bool hasCaption)
void writeMscFile (const QCString &fileName, const DocVerbatim &s)
void startDiaFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption, const QCString &srcFile, int srcLine)
void endDiaFile (bool hasCaption)
void writeDiaFile (const QCString &fileName, const DocVerbatim &s)
void writePlantUMLFile (const QCString &fileName, const DocVerbatim &s)
void visitCaption (const DocNodeList &children)
void incIndentLevel ()
void decIndentLevel ()
int indentLevel () const
void pushTableState ()
void popTableState ()
size_t currentColumn () const
void setCurrentColumn (size_t col)
size_t numCols () const
void setNumCols (size_t num)
bool inRowSpan () const
void setInRowSpan (bool b)
bool inColSpan () const
void setInColSpan (bool b)
bool firstRow () const
void setFirstRow (bool b)
RowSpanList & rowSpans ()
void addRowSpan (ActiveRowSpan &&span)
bool insideTable () const
Private Attributes
TextStream & m_t
LatexCodeGenerator & m_ci
bool m_insidePre
bool m_insideItem
bool m_hide
bool m_insideTabbing
QCString m_langExt
std::stack< TableState > m_tableStateStack
RowSpanList m_emptyRowSpanList
int m_indentLevel = 0
LatexListItemInfo m_listItemInfo [maxIndentLevels]
Static Private Attributes
static const int maxIndentLevels = 13
Detailed Description
Concrete visitor implementation for LaTeX output.
Definition at line 30 of file latexdocvisitor.h.
Member Typedef Documentation
RowSpanList [1/2]
typedef std::vector<ActiveRowSpan> LatexDocVisitor::RowSpanList [private]
Definition at line 123 of file latexdocvisitor.h.
RowSpanList [2/2]
typedef std::vector<ActiveRowSpan> LatexDocVisitor::RowSpanList [private]
Definition at line 123 of file latexdocvisitor.h.
Constructor & Destructor Documentation
LatexDocVisitor() [1/2]
LatexDocVisitor::LatexDocVisitor (TextStream & t, LatexCodeGenerator & ci, const QCString & langExt, bool insideTabbing)
Definition at line 204 of file latexdocvisitor.cpp.
  : m_t(t), m_ci(ci), m_insidePre(FALSE),
    m_insideItem(FALSE), m_hide(FALSE),
    m_insideTabbing(insideTabbing), m_langExt(langExt)
{
}
LatexDocVisitor() [2/2]
LatexDocVisitor::LatexDocVisitor (TextStream & t, LatexCodeGenerator & ci, const QCString & langExt, bool insideTabbing)
Member Function Documentation
addRowSpan() [1/2]
void LatexDocVisitor::addRowSpan (ActiveRowSpan && span) [inline], [private]
Definition at line 244 of file latexdocvisitor.h.
    {
      if (!m_tableStateStack.empty()) m_tableStateStack.top().rowSpans.push_back(std::move(span));
    }
References m_tableStateStack.
Referenced by operator()().
addRowSpan() [2/2]
void LatexDocVisitor::addRowSpan (ActiveRowSpan && span) [inline], [private]
Definition at line 244 of file latexdocvisitor.h.
    {
      if (!m_tableStateStack.empty()) m_tableStateStack.top().rowSpans.push_back(std::move(span));
    }
References m_tableStateStack.
currentColumn() [1/2]
size_t LatexDocVisitor::currentColumn () const [inline], [private]
Definition at line 200 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty() ? m_tableStateStack.top().currentColumn : 0;
    }
References m_tableStateStack.
Referenced by operator()().
currentColumn() [2/2]
size_t LatexDocVisitor::currentColumn () const [inline], [private]
Definition at line 200 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty() ? m_tableStateStack.top().currentColumn : 0;
    }
References m_tableStateStack.
decIndentLevel() [1/2]
void LatexDocVisitor::decIndentLevel () [private]
Definition at line 2000 of file latexdocvisitor.cpp.
{
  if (m_indentLevel>0)
  {
    m_indentLevel--;
  }
}
References m_indentLevel.
Referenced by operator()().
decIndentLevel() [2/2]
void LatexDocVisitor::decIndentLevel () [private]
endDiaFile() [1/2]
void LatexDocVisitor::endDiaFile (bool hasCaption) [private]
Definition at line 1944 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  visitPostEnd(m_t,hasCaption);
}
References m_hide, m_t, and visitPostEnd().
Referenced by operator()().
endDiaFile() [2/2]
void LatexDocVisitor::endDiaFile (bool hasCaption) [private]
endDotFile() [1/2]
void LatexDocVisitor::endDotFile (bool hasCaption) [private]
Definition at line 1865 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  visitPostEnd(m_t,hasCaption);
}
References m_hide, m_t, and visitPostEnd().
Referenced by operator()().
endDotFile() [2/2]
void LatexDocVisitor::endDotFile (bool hasCaption) [private]
endLink() [1/2]
void LatexDocVisitor::endLink (const QCString & ref, const QCString & file, const QCString & anchor, bool refToTable = FALSE) [private]
Definition at line 1819 of file latexdocvisitor.cpp.
{
  m_t << "}";
  bool pdfHyperLinks = Config_getBool(PDF_HYPERLINKS);
  if (ref.isEmpty() && !pdfHyperLinks)
  {
    m_t << "{";
    filter(theTranslator->trPageAbbreviation());
    m_t << "}{" << file;
    if (!file.isEmpty() && !anchor.isEmpty()) m_t << "_";
    m_t << anchor << "}";
  }
  if (ref.isEmpty() && pdfHyperLinks) // internal PDF link
  {
    if (!refToTable)
    {
      m_t << "}";
    }
  }
}
References Config_getBool, caseconvert::file, filter(), QCString::isEmpty(), m_t, theTranslator, and Translator::trPageAbbreviation().
Referenced by operator()().
endLink() [2/2]
void LatexDocVisitor::endLink (const QCString & ref, const QCString & file, const QCString & anchor, bool refToTable = FALSE) [private]
endMscFile() [1/2]
void LatexDocVisitor::endMscFile (bool hasCaption) [private]
Definition at line 1896 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  visitPostEnd(m_t,hasCaption);
}
References m_hide, m_t, and visitPostEnd().
Referenced by operator()().
endMscFile() [2/2]
void LatexDocVisitor::endMscFile (bool hasCaption) [private]
escapeMakeIndexChars() [1/2]
QCString LatexDocVisitor::escapeMakeIndexChars (const char * s) [private]
Definition at line 176 of file latexdocvisitor.cpp.
{
  QCString result;
  const char *p=s;
  char str[2]; str[1]=0;
  char c;
  if (p)
  {
    while ((c=*p++))
    {
      switch (c)
      {
        case '!': m_t << "\"!"; break;
        case '"': m_t << "\"\""; break;
        case '@': m_t << "\"@"; break;
        case '|': m_t << "\\texttt{\"|}"; break;
        case '[': m_t << "["; break;
        case ']': m_t << "]"; break;
        case '{': m_t << "\\lcurly{}"; break;
        case '}': m_t << "\\rcurly{}"; break;
        default: str[0]=c; filter(str); break;
      }
    }
  }
  return result;
}
References c, filter(), m_t, p, and s.
escapeMakeIndexChars() [2/2]
QCString LatexDocVisitor::escapeMakeIndexChars (const char * s) [private]
filter() [1/2]
void LatexDocVisitor::filter (const QCString & str, const bool retainNewLine = false) [private]
Definition at line 1775 of file latexdocvisitor.cpp.
{
  filterLatexString(m_t,str,
                    m_insideTabbing,
                    m_insidePre,
                    m_insideItem,
                    m_ci.usedTableLevel()>0, // insideTable
                    false, // keepSpaces
                    retainNewLine
                   );
}
References filterLatexString(), m_ci, m_insideItem, m_insidePre, m_insideTabbing, m_t, and LatexCodeGenerator::usedTableLevel().
Referenced by endLink(), escapeMakeIndexChars(), and operator()().
filter() [2/2]
void LatexDocVisitor::filter (const QCString & str, const bool retainNewLine = false) [private]
firstRow() [1/2]
bool LatexDocVisitor::firstRow () const [inline], [private]
Definition at line 232 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty() ? m_tableStateStack.top().firstRow : FALSE;
    }
References FALSE, and m_tableStateStack.
Referenced by operator()().
firstRow() [2/2]
bool LatexDocVisitor::firstRow () const [inline], [private]
Definition at line 232 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty() ? m_tableStateStack.top().firstRow : FALSE;
    }
References FALSE, and m_tableStateStack.
incIndentLevel() [1/2]
void LatexDocVisitor::incIndentLevel () [private]
Definition at line 1991 of file latexdocvisitor.cpp.
{
  m_indentLevel++;
  if (m_indentLevel>=maxIndentLevels)
  {
    err("Maximum indent level (%d) exceeded while generating LaTeX output!\n",maxIndentLevels-1);
  }
}
References err(), m_indentLevel, and maxIndentLevels.
Referenced by operator()().
incIndentLevel() [2/2]
void LatexDocVisitor::incIndentLevel () [private]
inColSpan() [1/2]
bool LatexDocVisitor::inColSpan () const [inline], [private]
Definition at line 224 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty() ? m_tableStateStack.top().inColSpan : FALSE;
    }
References FALSE, and m_tableStateStack.
Referenced by operator()().
inColSpan() [2/2]
bool LatexDocVisitor::inColSpan () const [inline], [private]
Definition at line 224 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty() ? m_tableStateStack.top().inColSpan : FALSE;
    }
References FALSE, and m_tableStateStack.
indentLevel() [1/2]
int LatexDocVisitor::indentLevel () const [private]
Definition at line 1986 of file latexdocvisitor.cpp.
{
  return std::min(m_indentLevel,maxIndentLevels-1);
}
References m_indentLevel, and maxIndentLevels.
Referenced by operator()().
indentLevel() [2/2]
int LatexDocVisitor::indentLevel () const [private]
inRowSpan() [1/2]
bool LatexDocVisitor::inRowSpan () const [inline], [private]
Definition at line 216 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty() ? m_tableStateStack.top().inRowSpan : FALSE;
    }
References FALSE, and m_tableStateStack.
Referenced by operator()().
inRowSpan() [2/2]
bool LatexDocVisitor::inRowSpan () const [inline], [private]
Definition at line 216 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty() ? m_tableStateStack.top().inRowSpan : FALSE;
    }
References FALSE, and m_tableStateStack.
insideTable() [1/2]
bool LatexDocVisitor::insideTable () const [inline], [private]
Definition at line 248 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty();
    }
References m_tableStateStack.
Referenced by operator()().
insideTable() [2/2]
bool LatexDocVisitor::insideTable () const [inline], [private]
Definition at line 248 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty();
    }
References m_tableStateStack.
numCols() [1/2]
size_t LatexDocVisitor::numCols () const [inline], [private]
Definition at line 208 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty() ? m_tableStateStack.top().numCols : 0;
    }
References m_tableStateStack.
Referenced by operator()().
numCols() [2/2]
size_t LatexDocVisitor::numCols () const [inline], [private]
Definition at line 208 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty() ? m_tableStateStack.top().numCols : 0;
    }
References m_tableStateStack.
operator()() [1/114]
void LatexDocVisitor::operator() (const DocAnchor & anc)
Definition at line 497 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\label{" << stripPath(anc.file()) << "_" << anc.anchor() << "}%\n";
  if (!anc.file().isEmpty() && Config_getBool(PDF_HYPERLINKS))
  {
    m_t << "\\Hypertarget{" << stripPath(anc.file()) << "_" << anc.anchor()
      << "}%\n";
  }
}
References DocAnchor::anchor(), Config_getBool, DocAnchor::file(), QCString::isEmpty(), m_hide, m_t, and stripPath().
operator()() [2/114]
void LatexDocVisitor::operator() (const DocAnchor &)
operator()() [3/114]
void LatexDocVisitor::operator() (const DocAutoList & l)
Definition at line 716 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  if (m_indentLevel>=maxIndentLevels-1) return;
  if (l.isEnumList())
  {
    m_t << "\n\\begin{DoxyEnumerate}";
    m_listItemInfo[indentLevel()].isEnum = true;
  }
  else
  {
    m_listItemInfo[indentLevel()].isEnum = false;
    m_t << "\n\\begin{DoxyItemize}";
  }
  visitChildren(l);
  if (l.isEnumList())
  {
    m_t << "\n\\end{DoxyEnumerate}";
  }
  else
  {
    m_t << "\n\\end{DoxyItemize}";
  }
}
References indentLevel(), LatexDocVisitor::LatexListItemInfo::isEnum, DocAutoList::isEnumList(), m_hide, m_indentLevel, m_listItemInfo, m_t, maxIndentLevels, and visitChildren().
operator()() [4/114]
void LatexDocVisitor::operator() (const DocAutoList &)
operator()() [5/114]
void LatexDocVisitor::operator() (const DocAutoListItem & li)
Definition at line 741 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\n\\item ";
  incIndentLevel();
  visitChildren(li);
  decIndentLevel();
}
References decIndentLevel(), incIndentLevel(), m_hide, m_t, and visitChildren().
operator()() [6/114]
void LatexDocVisitor::operator() (const DocAutoListItem &)
operator()() [7/114]
void LatexDocVisitor::operator() (const DocCite & cite)
Definition at line 693 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  if (!cite.file().isEmpty())
  {
    //startLink(cite.ref(),cite.file(),cite.anchor());
    QCString anchor = cite.anchor();
    QCString anchorPrefix = CitationManager::instance().anchorPrefix();
    anchor = anchor.mid(anchorPrefix.length()); // strip prefix
    m_t << "\\cite{" << anchor << "}";
  }
  else
  {
    m_t << "{\\bfseries [";
    filter(cite.text());
    m_t << "]}";
  }
}
References DocCite::anchor(), CitationManager::anchorPrefix(), DocCite::file(), filter(), CitationManager::instance(), QCString::isEmpty(), QCString::length(), m_hide, m_t, QCString::mid(), and DocCite::text().
operator()() [8/114]
void LatexDocVisitor::operator() (const DocCite &)
operator()() [9/114]
void LatexDocVisitor::operator() (const DocDiaFile & df)
Definition at line 1484 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  if (!Config_getBool(DOT_CLEANUP)) copyFile(df.file(),Config_getString(LATEX_OUTPUT)+"/"+stripPath(df.file()));
  startDiaFile(df.file(),df.width(),df.height(),df.hasCaption(),df.srcFile(),df.srcLine());
  visitChildren(df);
  endDiaFile(df.hasCaption());
}
References Config_getBool, Config_getString, copyFile(), endDiaFile(), DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), DocDiagramFileBase::height(), m_hide, DocDiagramFileBase::srcFile(), DocDiagramFileBase::srcLine(), startDiaFile(), stripPath(), visitChildren(), and DocDiagramFileBase::width().
operator()() [10/114]
void LatexDocVisitor::operator() (const DocDiaFile &)
operator()() [11/114]
void LatexDocVisitor::operator() (const DocDotFile & df)
Definition at line 1466 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  if (!Config_getBool(DOT_CLEANUP)) copyFile(df.file(),Config_getString(LATEX_OUTPUT)+"/"+stripPath(df.file()));
  startDotFile(df.file(),df.width(),df.height(),df.hasCaption(),df.srcFile(),df.srcLine());
  visitChildren(df);
  endDotFile(df.hasCaption());
}
References Config_getBool, Config_getString, copyFile(), endDotFile(), DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), DocDiagramFileBase::height(), m_hide, DocDiagramFileBase::srcFile(), DocDiagramFileBase::srcLine(), startDotFile(), stripPath(), visitChildren(), and DocDiagramFileBase::width().
operator()() [12/114]
void LatexDocVisitor::operator() (const DocDotFile &)
operator()() [13/114]
void LatexDocVisitor::operator() (const DocEmoji & s)
Definition at line 283 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  QCString emojiName = EmojiEntityMapper::instance()->name(s.index());
  if (!emojiName.isEmpty())
  {
    QCString imageName=emojiName.mid(1,emojiName.length()-2); // strip : at start and end
    m_t << "\\doxygenemoji{";
    filter(emojiName);
    m_t << "}{" << imageName << "}";
  }
  else
  {
    m_t << s.name();
  }
}
References filter(), EmojiEntityMapper::instance(), QCString::isEmpty(), QCString::length(), m_hide, m_t, QCString::mid(), EmojiEntityMapper::name(), and s.
operator()() [14/114]
void LatexDocVisitor::operator() (const DocEmoji &)
operator()() [15/114]
void LatexDocVisitor::operator() (const DocFormula & f)
Definition at line 660 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  QCString s = f.text();
  const char *p = s.data();
  char c;
  if (p)
  {
    while ((c=*p++))
    {
      switch (c)
      {
        case '\'': m_t << "\\textnormal{\\textquotesingle}"; break;
        default: m_t << c; break;
      }
    }
  }
}
References c, gdFont::data, f, m_hide, m_t, p, and s.
operator()() [16/114]
void LatexDocVisitor::operator() (const DocFormula &)
operator()() [17/114]
void LatexDocVisitor::operator() (const DocHorRuler &)
Definition at line 320 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  if (insideTable())
    m_t << "\\DoxyHorRuler{1}\n";
  else
    m_t << "\\DoxyHorRuler{0}\n";
}
References insideTable(), m_hide, and m_t.
operator()() [18/114]
void LatexDocVisitor::operator() (const DocHorRuler &)
operator()() [19/114]
void LatexDocVisitor::operator() (const DocHRef & href)
Definition at line 1395 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  if (Config_getBool(PDF_HYPERLINKS))
  {
    m_t << "\\href{";
    m_t << latexFilterURL(href.url());
    m_t << "}";
  }
  m_t << "{\\texttt{ ";
  visitChildren(href);
  m_t << "}}";
}
References Config_getBool, latexFilterURL(), m_hide, m_t, DocHRef::url(), and visitChildren().
operator()() [20/114]
void LatexDocVisitor::operator() (const DocHRef &)
operator()() [21/114]
void LatexDocVisitor::operator() (const DocHtmlBlockQuote & q)
Definition at line 1755 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\begin{quote}\n";
  incIndentLevel();
  visitChildren(q);
  m_t << "\\end{quote}\n";
  decIndentLevel();
}
References decIndentLevel(), incIndentLevel(), m_hide, m_t, and visitChildren().
operator()() [22/114]
void LatexDocVisitor::operator() (const DocHtmlBlockQuote &)
operator()() [23/114]
void LatexDocVisitor::operator() (const DocHtmlCaption & c)
Definition at line 1190 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(c);
}
References c, m_hide, and visitChildren().
operator()() [24/114]
void LatexDocVisitor::operator() (const DocHtmlCaption &)
operator()() [25/114]
void LatexDocVisitor::operator() (const DocHtmlCell & c)
Definition at line 1274 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  const DocHtmlRow *row = std::get_if<DocHtmlRow>(c.parent());
  setCurrentColumn(currentColumn()+1);
  //Skip columns that span from above.
  for (const auto &span : rowSpans())
  {
    if (span.rowSpan>0 && span.column==currentColumn())
    {
      if (row && span.colSpan>1)
      {
        m_t << "\\multicolumn{" << span.colSpan << "}{";
        if (currentColumn() /*c.columnIndex()*/==1) // add extra | for first column
        {
          m_t << "|";
        }
        m_t << "l|}{" << (c.isHeading()? "\\columncolor{\\tableheadbgcolor}" : "") << "}"; // alignment not relevant, empty column
        setCurrentColumn(currentColumn()+span.colSpan);
      }
      else
      {
        setCurrentColumn(currentColumn()+1);
      }
      m_t << "&";
    }
  }
  int cs = c.colSpan();
  int a = c.alignment();
  if (cs>1 && row)
  {
    setInColSpan(TRUE);
    m_t << "\\multicolumn{" << cs << "}{";
    if (c.columnIndex()==1) // add extra | for first column
    {
      m_t << "|";
    }
    switch (a)
    {
      case DocHtmlCell::Right:
        m_t << "r|}{";
        break;
      case DocHtmlCell::Center:
        m_t << "c|}{";
        break;
      default:
        m_t << "l|}{";
        break;
    }
  }
  int rs = c.rowSpan();
  int va = c.valignment();
  if (rs>0)
  {
    setInRowSpan(TRUE);
    m_t << "\\multirow";
    switch(va)
    {
      case DocHtmlCell::Top:
        m_t << "[t]";
        break;
      case DocHtmlCell::Bottom:
        m_t << "[b]";
        break;
      case DocHtmlCell::Middle:
        break; // No alignment option needed
      default:
        break;
    }
    //printf("adding row span: cell={r=%d c=%d rs=%d cs=%d} curCol=%d\n",
    // c.rowIndex(),c.columnIndex(),c.rowSpan(),c.colSpan(),
    // currentColumn());
    addRowSpan(ActiveRowSpan(c,rs,cs,currentColumn()));
    m_t << "{" << rs << "}{*}{";
  }
  if (a==DocHtmlCell::Center)
  {
    m_t << "\\PBS\\centering ";
  }
  else if (a==DocHtmlCell::Right)
  {
    m_t << "\\PBS\\raggedleft ";
  }
  if (c.isHeading())
  {
    m_t << "\\cellcolor{\\tableheadbgcolor}\\textbf{ ";
  }
  if (cs>1)
  {
    setCurrentColumn(currentColumn()+cs-1);
  }
  visitChildren(c);
  if (c.isHeading())
  {
    m_t << "}";
  }
  if (inRowSpan())
  {
    setInRowSpan(FALSE);
    m_t << "}";
  }
  if (inColSpan())
  {
    setInColSpan(FALSE);
    m_t << "}";
  }
  if (!c.isLast()) m_t << "&";
}
References a, addRowSpan(), DocHtmlCell::Bottom, c, DocHtmlCell::Center, cs, currentColumn(), FALSE, inColSpan(), inRowSpan(), m_hide, m_t, DocHtmlCell::Middle, DocHtmlCell::Right, rowSpans(), setCurrentColumn(), setInColSpan(), setInRowSpan(), DocHtmlCell::Top, TRUE, and visitChildren().
operator()() [26/114]
void LatexDocVisitor::operator() (const DocHtmlCell &)
operator()() [27/114]
void LatexDocVisitor::operator() (const DocHtmlDescData & dd)
Definition at line 1098 of file latexdocvisitor.cpp.
{
  incIndentLevel();
  visitChildren(dd);
  decIndentLevel();
}
References decIndentLevel(), incIndentLevel(), and visitChildren().
operator()() [28/114]
void LatexDocVisitor::operator() (const DocHtmlDescData &)
operator()() [29/114]
void LatexDocVisitor::operator() (const DocHtmlDescList & dl)
Definition at line 1064 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  bool eq = classEqualsReflist(dl);
  if (eq)
  {
    m_t << "\n\\begin{DoxyRefList}";
  }
  else
  {
    if (listIsNested(dl)) m_t << "\n\\hfill";
    m_t << "\n\\begin{DoxyDescription}";
  }
  visitChildren(dl);
  if (eq)
  {
    m_t << "\n\\end{DoxyRefList}";
  }
  else
  {
    m_t << "\n\\end{DoxyDescription}";
  }
}
References classEqualsReflist(), listIsNested(), m_hide, m_t, and visitChildren().
operator()() [30/114]
void LatexDocVisitor::operator() (const DocHtmlDescList &)
operator()() [31/114]
void LatexDocVisitor::operator() (const DocHtmlDescTitle & dt)
Definition at line 1088 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\n\\item[";
  m_insideItem=TRUE;
  visitChildren(dt);
  m_insideItem=FALSE;
  m_t << "]";
}
References FALSE, m_hide, m_insideItem, m_t, TRUE, and visitChildren().
operator()() [32/114]
void LatexDocVisitor::operator() (const DocHtmlDescTitle &)
operator()() [33/114]
void LatexDocVisitor::operator() (const DocHtmlDetails & d)
Definition at line 1417 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\n\n";
  auto summary = d.summary();
  if (summary)
  {
    std::visit(*this,*summary);
    m_t << "\\begin{adjustwidth}{1em}{0em}\n";
  }
  visitChildren(d);
  if (summary)
  {
    m_t << "\\end{adjustwidth}\n";
  }
  else
  {
    m_t << "\n\n";
  }
}
References m_hide, m_t, DocHtmlDetails::summary(), and visitChildren().
operator()() [34/114]
void LatexDocVisitor::operator() (const DocHtmlDetails &)
operator()() [35/114]
void LatexDocVisitor::operator() (const DocHtmlHeader & header)
Definition at line 1438 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\" << getSectionName(header.level()) << "*{";
  visitChildren(header);
  m_t << "}";
}
References getSectionName(), DocHtmlHeader::level(), m_hide, m_t, and visitChildren().
operator()() [36/114]
void LatexDocVisitor::operator() (const DocHtmlHeader &)
operator()() [37/114]
void LatexDocVisitor::operator() (const DocHtmlList & s)
Definition at line 948 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  if (m_indentLevel>=maxIndentLevels-1) return;
  m_listItemInfo[indentLevel()].isEnum = s.type()==DocHtmlList::Ordered;
  if (s.type()==DocHtmlList::Ordered)
  {
    bool first = true;
    m_t << "\n\\begin{DoxyEnumerate}";
    for (const auto &opt : s.attribs())
    {
      if (opt.name=="type")
      {
        if (opt.value=="1")
        {
          m_t << (first ? "[": ",");
          m_t << "label=\\arabic*";
          first = false;
        }
        else if (opt.value=="a")
        {
          m_t << (first ? "[": ",");
          m_t << "label=\\enumalphalphcnt*";
          first = false;
        }
        else if (opt.value=="A")
        {
          m_t << (first ? "[": ",");
          m_t << "label=\\enumAlphAlphcnt*";
          first = false;
        }
        else if (opt.value=="i")
        {
          m_t << (first ? "[": ",");
          m_t << "label=\\roman*";
          first = false;
        }
        else if (opt.value=="I")
        {
          m_t << (first ? "[": ",");
          m_t << "label=\\Roman*";
          first = false;
        }
      }
      else if (opt.name=="start")
      {
        m_t << (first ? "[": ",");
        bool ok;
        int val = opt.value.toInt(&ok);
        if (ok) m_t << "start=" << val;
        first = false;
      }
    }
    if (!first) m_t << "]\n";
  }
  else
  {
    m_t << "\n\\begin{DoxyItemize}";
  }
  visitChildren(s);
  if (m_indentLevel>=maxIndentLevels-1) return;
  if (s.type()==DocHtmlList::Ordered)
    m_t << "\n\\end{DoxyEnumerate}";
  else
    m_t << "\n\\end{DoxyItemize}";
}
References indentLevel(), LatexDocVisitor::LatexListItemInfo::isEnum, m_hide, m_indentLevel, m_listItemInfo, m_t, maxIndentLevels, DocHtmlList::Ordered, s, testsqlite3::val, and visitChildren().
operator()() [38/114]
void LatexDocVisitor::operator() (const DocHtmlList & s)
operator()() [39/114]
void LatexDocVisitor::operator() (const DocHtmlListItem & l)
Definition at line 1015 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  if (m_listItemInfo[indentLevel()].isEnum)
  {
    for (const auto &opt : l.attribs())
    {
      if (opt.name=="value")
      {
        bool ok;
        int val = opt.value.toInt(&ok);
        if (ok)
        {
          m_t << "\n\\setcounter{DoxyEnumerate" << integerToRoman(indentLevel()+1,false) << "}{" << (val - 1) << "}";
        }
      }
    }
  }
  m_t << "\n\\item ";
  incIndentLevel();
  visitChildren(l);
  decIndentLevel();
}
References DocHtmlListItem::attribs(), decIndentLevel(), incIndentLevel(), indentLevel(), integerToRoman(), m_hide, m_listItemInfo, m_t, testsqlite3::val, and visitChildren().
operator()() [40/114]
void LatexDocVisitor::operator() (const DocHtmlListItem &)
operator()() [41/114]
void LatexDocVisitor::operator() (const DocHtmlRow & row)
Definition at line 1196 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  setCurrentColumn(0);
  visitChildren(row);
  size_t c=currentColumn();
  while (c<=numCols()) // end of row while inside a row span?
  {
    for (const auto &span : rowSpans())
    {
      //printf(" found row span: column=%d rs=%d cs=%d rowIdx=%d cell->rowIdx=%d i=%d c=%d\n",
      // span->column, span->rowSpan,span->colSpan,row.rowIndex(),span->cell->rowIndex(),i,c);
      if (span.rowSpan>0 && span.column==c && // we are at a cell in a row span
          row.rowIndex()>span.cell.rowIndex() // but not the row that started the span
         )
      {
        m_t << "&";
        if (span.colSpan>1) // row span is also part of a column span
        {
          m_t << "\\multicolumn{" << span.colSpan << "}{";
          m_t << "}|}{}";
        }
        else // solitary row span
        {
          m_t << "\\multicolumn{1}{c|}{}";
        }
      }
    }
    c++;
  }
  m_t << "\\\\";
  size_t col = 1;
  for (auto &span : rowSpans())
  {
    if (span.rowSpan>0) span.rowSpan--;
    if (span.rowSpan<=0)
    {
      // inactive span
    }
    else if (span.column>col)
    {
      m_t << "\\cline{" << col << "-" << (span.column-1) << "}";
      col = span.column+span.colSpan;
    }
    else
    {
      col = span.column+span.colSpan;
    }
  }
  if (col <= numCols())
  {
    m_t << "\\cline{" << col << "-" << numCols() << "}";
  }
  m_t << "\n";
  const DocNodeVariant *n = ::parent(row.parent());
  if (row.isHeading() && row.rowIndex()==1 && !tableIsNested(n))
  {
    if (firstRow())
    {
      m_t << "\\endfirsthead\n";
      m_t << "\\hline\n";
      m_t << "\\endfoot\n";
      m_t << "\\hline\n";
    }
    else
    {
      m_t << "\\endhead\n";
    }
  }
}
References c, currentColumn(), firstRow(), DocHtmlRow::isHeading(), m_hide, m_t, n, numCols(), DocNode::parent(), parent(), DocHtmlRow::rowIndex(), rowSpans(), setCurrentColumn(), tableIsNested(), and visitChildren().
operator()() [42/114]
void LatexDocVisitor::operator() (const DocHtmlRow &)
operator()() [43/114]
void LatexDocVisitor::operator() (const DocHtmlSummary & d)
Definition at line 1409 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "{\\bfseries{";
  visitChildren(d);
  m_t << "}}";
}
References m_hide, m_t, and visitChildren().
operator()() [44/114]
void LatexDocVisitor::operator() (const DocHtmlSummary &)
operator()() [45/114]
void LatexDocVisitor::operator() (const DocHtmlTable & t)
Definition at line 1142 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  pushTableState();
  const DocHtmlCaption *c = t.caption() ? &std::get<DocHtmlCaption>(*t.caption()) : nullptr;
  if (c)
  {
    bool pdfHyperLinks = Config_getBool(PDF_HYPERLINKS);
    if (!c->file().isEmpty() && pdfHyperLinks)
    {
      m_t << "\\hypertarget{" << stripPath(c->file()) << "_" << c->anchor()
        << "}{}";
    }
    m_t << "\n";
  }
  writeStartTableCommand(m_t,t.parent(),t.numColumns());
  if (c)
  {
    m_t << "\\caption{";
    std::visit(*this, *t.caption());
    m_t << "}";
    m_t << "\\label{" << stripPath(c->file()) << "_" << c->anchor() << "}";
    m_t << "\\\\\n";
  }
  setNumCols(t.numColumns());
  m_t << "\\hline\n";
  // check if first row is a heading and then render the row already here
  // and end it with \endfirsthead (triggered via m_firstRow==TRUE)
  // then repeat the row as normal and end it with \endhead (m_firstRow==FALSE)
  const DocHtmlRow *firstRow = std::get_if<DocHtmlRow>(t.firstRow());
  if (firstRow && firstRow->isHeading())
  {
    setFirstRow(TRUE);
    if (!tableIsNested(t.parent()))
    {
      std::visit(*this,*t.firstRow());
    }
    setFirstRow(FALSE);
  }
  visitChildren(t);
  writeEndTableCommand(m_t,t.parent());
  popTableState();
}
References c, DocHtmlTable::caption(), Config_getBool, FALSE, DocHtmlTable::firstRow(), firstRow(), m_hide, m_t, DocHtmlTable::numColumns(), DocNode::parent(), popTableState(), pushTableState(), setFirstRow(), setNumCols(), stripPath(), tableIsNested(), TRUE, visitChildren(), writeEndTableCommand(), and writeStartTableCommand().
operator()() [46/114]
void LatexDocVisitor::operator() (const DocHtmlTable & t)
operator()() [47/114]
void LatexDocVisitor::operator() (const DocImage & img)
Definition at line 1446 of file latexdocvisitor.cpp.
{
  if (img.type()==DocImage::Latex)
  {
    if (m_hide) return;
    QCString gfxName = img.name();
    if (gfxName.endsWith(".eps") || gfxName.endsWith(".pdf"))
    {
      gfxName=gfxName.left(gfxName.length()-4);
    }
    visitPreStart(m_t,img.hasCaption(), gfxName, img.width(), img.height(), img.isInlineImage());
    visitChildren(img);
    visitPostEnd(m_t,img.hasCaption(), img.isInlineImage());
  }
  else // other format -> skip
  {
  }
}
References QCString::endsWith(), DocImage::hasCaption(), DocImage::height(), DocImage::isInlineImage(), DocImage::Latex, QCString::left(), QCString::length(), m_hide, m_t, DocImage::name(), DocImage::type(), visitChildren(), visitPostEnd(), visitPreStart(), and DocImage::width().
operator()() [48/114]
void LatexDocVisitor::operator() (const DocImage &)
operator()() [49/114]
void LatexDocVisitor::operator() (const DocInclude & inc)
Definition at line 508 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  SrcLangExt langExt = getLanguageFromFileName(inc.extension());
  switch(inc.type())
  {
    case DocInclude::IncWithLines:
      {
        m_ci.startCodeFragment("DoxyCodeInclude");
        FileInfo cfi(inc.file().str());
        FileDef *fd = createFileDef(cfi.dirPath(), cfi.fileName());
        getCodeParser(inc.extension()).parseCode(m_ci,inc.context(),
                                                  inc.text(),
                                                  langExt,
                                                  inc.isExample(),
                                                  inc.exampleFile(),
                                                  fd, // fileDef,
                                                  -1, // start line
                                                  -1, // end line
                                                  FALSE, // inline fragment
                                                  0, // memberDef
                                                  TRUE // show line numbers
                                     );
        delete fd;
        m_ci.endCodeFragment("DoxyCodeInclude");
      }
      break;
    case DocInclude::Include:
      {
        m_ci.startCodeFragment("DoxyCodeInclude");
        getCodeParser(inc.extension()).parseCode(m_ci,inc.context(),
                                                  inc.text(),langExt,inc.isExample(),
                                                  inc.exampleFile(),
                                                  0, // fileDef
                                                  -1, // startLine
                                                  -1, // endLine
                                                  TRUE, // inlineFragment
                                                  0, // memberDef
                                                  FALSE
                                                 );
        m_ci.endCodeFragment("DoxyCodeInclude");
      }
      break;
    case DocInclude::DontInclude:
    case DocInclude::DontIncWithLines:
    case DocInclude::HtmlInclude:
    case DocInclude::RtfInclude:
    case DocInclude::ManInclude:
    case DocInclude::XmlInclude:
    case DocInclude::DocbookInclude:
      break;
    case DocInclude::LatexInclude:
      m_t << inc.text();
      break;
    case DocInclude::VerbInclude:
      m_t << "\n\\begin{DoxyVerbInclude}\n";
      m_t << inc.text();
      m_t << "\\end{DoxyVerbInclude}\n";
      break;
    case DocInclude::Snippet:
      {
        m_ci.startCodeFragment("DoxyCodeInclude");
        getCodeParser(inc.extension()).parseCode(m_ci,
                                                  inc.context(),
                                                  extractBlock(inc.text(),inc.blockId()),
                                                  langExt,
                                                  inc.isExample(),
                                                  inc.exampleFile()
                                                 );
        m_ci.endCodeFragment("DoxyCodeInclude");
      }
      break;
    case DocInclude::SnipWithLines:
      {
        FileInfo cfi(inc.file().str());
        FileDef *fd = createFileDef(cfi.dirPath(), cfi.fileName());
        m_ci.startCodeFragment("DoxyCodeInclude");
        getCodeParser(inc.extension()).parseCode(m_ci,
                                                  inc.context(),
                                                  extractBlock(inc.text(),inc.blockId()),
                                                  langExt,
                                                  inc.isExample(),
                                                  inc.exampleFile(),
                                                  fd,
                                                  lineBlock(inc.text(),inc.blockId()),
                                                  -1, // endLine
                                                  FALSE, // inlineFragment
                                                  0, // memberDef
                                                  TRUE // show line number
                                                 );
        delete fd;
        m_ci.endCodeFragment("DoxyCodeInclude");
      }
      break;
    case DocInclude::SnippetDoc:
    case DocInclude::IncludeDoc:
      err("Internal inconsistency: found switch SnippetDoc / IncludeDoc in file: %s"
          "Please create a bug report\n",__FILE__);
      break;
  }
}
References DocInclude::blockId(), DocInclude::context(), createFileDef(), FileInfo::dirPath(), DocInclude::DocbookInclude, DocInclude::DontInclude, DocInclude::DontIncWithLines, LatexCodeGenerator::endCodeFragment(), err(), DocInclude::exampleFile(), DocInclude::extension(), extractBlock(), FALSE, DocInclude::file(), FileInfo::fileName(), DocVisitor::getCodeParser(), getLanguageFromFileName(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isExample(), DocInclude::LatexInclude, lineBlock(), m_ci, m_hide, m_t, DocInclude::ManInclude, CodeParserInterface::parseCode(), DocInclude::RtfInclude, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, LatexCodeGenerator::startCodeFragment(), QCString::str(), DocInclude::text(), TRUE, DocInclude::type(), DocInclude::VerbInclude, and DocInclude::XmlInclude.
operator()() [50/114]
void LatexDocVisitor::operator() (const DocInclude &)
operator()() [51/114]
void LatexDocVisitor::operator() (const DocIncOperator & op)
Definition at line 610 of file latexdocvisitor.cpp.
{
  //printf("DocIncOperator: type=%d first=%d, last=%d text='%s'\n",
  // op.type(),op.isFirst(),op.isLast(),qPrint(op.text()));
  if (op.isFirst())
  {
    if (!m_hide) m_ci.startCodeFragment("DoxyCodeInclude");
    pushHidden(m_hide);
    m_hide = TRUE;
  }
  QCString locLangExt = getFileNameExtension(op.includeFileName());
  if (locLangExt.isEmpty()) locLangExt = m_langExt;
  SrcLangExt langExt = getLanguageFromFileName(locLangExt);
  if (op.type()!=DocIncOperator::Skip)
  {
    m_hide = popHidden();
    if (!m_hide)
    {
      FileDef *fd = 0;
      if (!op.includeFileName().isEmpty())
      {
        FileInfo cfi(op.includeFileName().str());
        fd = createFileDef(cfi.dirPath(), cfi.fileName());
      }
      getCodeParser(locLangExt).parseCode(m_ci,op.context(),op.text(),langExt,
                                          op.isExample(),op.exampleFile(),
                                          fd, // fileDef
                                          op.line(), // startLine
                                          -1, // endLine
                                          FALSE, // inline fragment
                                          0, // memberDef
                                          op.showLineNo() // show line numbers
                                         );
      if (fd) delete fd;
    }
    pushHidden(m_hide);
    m_hide=TRUE;
  }
  if (op.isLast())
  {
    m_hide=popHidden();
    if (!m_hide) m_ci.endCodeFragment("DoxyCodeInclude");
  }
  else
  {
    if (!m_hide) m_t << "\n";
  }
}
References DocIncOperator::context(), createFileDef(), FileInfo::dirPath(), LatexCodeGenerator::endCodeFragment(), DocIncOperator::exampleFile(), FALSE, FileInfo::fileName(), DocVisitor::getCodeParser(), getFileNameExtension(), getLanguageFromFileName(), DocIncOperator::includeFileName(), QCString::isEmpty(), DocIncOperator::isExample(), DocIncOperator::isFirst(), DocIncOperator::isLast(), DocIncOperator::line(), m_ci, m_hide, m_langExt, m_t, CodeParserInterface::parseCode(), DocVisitor::popHidden(), DocVisitor::pushHidden(), DocIncOperator::showLineNo(), DocIncOperator::Skip, LatexCodeGenerator::startCodeFragment(), QCString::str(), DocIncOperator::text(), TRUE, and DocIncOperator::type().
operator()() [52/114]
void LatexDocVisitor::operator() (const DocIncOperator &)
operator()() [53/114]
void LatexDocVisitor::operator() (const DocIndexEntry & i)
Definition at line 679 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\index{";
  m_t << latexEscapeLabelName(i.entry());
  m_t << "@{";
  m_t << latexEscapeIndexChars(i.entry());
  m_t << "}}";
}
References DocIndexEntry::entry(), latexEscapeIndexChars(), latexEscapeLabelName(), m_hide, and m_t.
operator()() [54/114]
void LatexDocVisitor::operator() (const DocIndexEntry &)
operator()() [55/114]
void LatexDocVisitor::operator() (const DocInternal & i)
Definition at line 1389 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(i);
}
References m_hide, and visitChildren().
operator()() [56/114]
void LatexDocVisitor::operator() (const DocInternal &)
operator()() [57/114]
void LatexDocVisitor::operator() (const DocInternalRef & ref)
Definition at line 1741 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  startLink(QCString(),ref.file(),ref.anchor());
  visitChildren(ref);
  endLink(QCString(),ref.file(),ref.anchor());
}
References DocInternalRef::anchor(), endLink(), DocInternalRef::file(), m_hide, startLink(), and visitChildren().
operator()() [58/114]
void LatexDocVisitor::operator() (const DocInternalRef &)
operator()() [59/114]
void LatexDocVisitor::operator() (const DocLineBreak &)
Definition at line 314 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "~\\newline\n";
}
References m_hide, and m_t.
operator()() [60/114]
void LatexDocVisitor::operator() (const DocLineBreak &)
operator()() [61/114]
void LatexDocVisitor::operator() (const DocLink & lnk)
Definition at line 1493 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  startLink(lnk.ref(),lnk.file(),lnk.anchor());
  visitChildren(lnk);
  endLink(lnk.ref(),lnk.file(),lnk.anchor());
}
References DocLink::anchor(), endLink(), DocLink::file(), m_hide, DocLink::ref(), startLink(), and visitChildren().
operator()() [62/114]
void LatexDocVisitor::operator() (const DocLink & lnk)
operator()() [63/114]
void LatexDocVisitor::operator() (const DocLinkedWord & w)
Definition at line 222 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  startLink(w.ref(),w.file(),w.anchor());
  filter(w.word());
  endLink(w.ref(),w.file(),w.anchor());
}
References endLink(), filter(), m_hide, startLink(), and w.
operator()() [64/114]
void LatexDocVisitor::operator() (const DocLinkedWord &)
operator()() [65/114]
void LatexDocVisitor::operator() (const DocMscFile & df)
Definition at line 1475 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  if (!Config_getBool(DOT_CLEANUP)) copyFile(df.file(),Config_getString(LATEX_OUTPUT)+"/"+stripPath(df.file()));
  startMscFile(df.file(),df.width(),df.height(),df.hasCaption(),df.srcFile(),df.srcLine());
  visitChildren(df);
  endMscFile(df.hasCaption());
}
References Config_getBool, Config_getString, copyFile(), endMscFile(), DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), DocDiagramFileBase::height(), m_hide, DocDiagramFileBase::srcFile(), DocDiagramFileBase::srcLine(), startMscFile(), stripPath(), visitChildren(), and DocDiagramFileBase::width().
operator()() [66/114]
void LatexDocVisitor::operator() (const DocMscFile &)
operator()() [67/114]
void LatexDocVisitor::operator() (const DocPara & p)
Definition at line 750 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(p);
  if (!p.isLast() && // omit <p> for last paragraph
      !(p.parent() && // and for parameter sections
        std::get_if<DocParamSect>(p.parent())
       )
     ) m_t << "\n\n";
}
References m_hide, m_t, p, and visitChildren().
operator()() [68/114]
void LatexDocVisitor::operator() (const DocPara &)
operator()() [69/114]
void LatexDocVisitor::operator() (const DocParamList & pl)
Definition at line 1633 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  DocParamSect::Type parentType = DocParamSect::Unknown;
  const DocParamSect *sect = std::get_if<DocParamSect>(pl.parent());
  if (sect)
  {
    parentType = sect->type();
  }
  bool useTable = parentType==DocParamSect::Param ||
                  parentType==DocParamSect::RetVal ||
                  parentType==DocParamSect::Exception ||
                  parentType==DocParamSect::TemplateParam;
  if (!useTable)
  {
    m_t << "\\item[";
  }
  if (sect && sect->hasInOutSpecifier())
  {
    if (pl.direction()!=DocParamSect::Unspecified)
    {
      m_t << "\\mbox{\\texttt{ ";
      if (pl.direction()==DocParamSect::In)
      {
        m_t << "in";
      }
      else if (pl.direction()==DocParamSect::Out)
      {
        m_t << "out";
      }
      else if (pl.direction()==DocParamSect::InOut)
      {
        m_t << "in,out";
      }
      m_t << "}} ";
    }
    if (useTable) m_t << " & ";
  }
  if (sect && sect->hasTypeSpecifier())
  {
    for (const auto &type : pl.paramTypes())
    {
      std::visit(*this,type);
    }
    if (useTable) m_t << " & ";
  }
  m_t << "{\\em ";
  bool first=TRUE;
  for (const auto &param : pl.parameters())
  {
    if (!first) m_t << ","; else first=FALSE;
    m_insideItem=TRUE;
    std::visit(*this,param);
    m_insideItem=FALSE;
  }
  m_t << "}";
  if (useTable)
  {
    m_t << " & ";
  }
  else
  {
    m_t << "]";
  }
  for (const auto &par : pl.paragraphs())
  {
    std::visit(*this,par);
  }
  if (useTable)
  {
    m_t << "\\\\\n"
        << "\\hline\n";
  }
}
References DocParamList::direction(), DocParamSect::Exception, FALSE, DocParamSect::hasInOutSpecifier(), DocParamSect::hasTypeSpecifier(), DocParamSect::In, DocParamSect::InOut, m_hide, m_insideItem, m_t, DocParamSect::Out, DocParamList::paragraphs(), DocParamSect::Param, DocParamList::parameters(), DocParamList::paramTypes(), DocNode::parent(), DocParamSect::RetVal, DocParamSect::TemplateParam, TRUE, DocParamSect::type(), DocParamSect::Unknown, and DocParamSect::Unspecified.
operator()() [70/114]
void LatexDocVisitor::operator() (const DocParamList &)
operator()() [71/114]
void LatexDocVisitor::operator() (const DocParamSect & s)
Definition at line 1574 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  bool hasInOutSpecs = s.hasInOutSpecifier();
  bool hasTypeSpecs = s.hasTypeSpecifier();
  m_ci.incUsedTableLevel();
  switch(s.type())
  {
    case DocParamSect::Param:
      m_t << "\n\\begin{DoxyParams}";
      if (hasInOutSpecs && hasTypeSpecs) m_t << "[2]"; // 2 extra cols
      else if (hasInOutSpecs || hasTypeSpecs) m_t << "[1]"; // 1 extra col
      m_t << "{";
      filter(theTranslator->trParameters());
      break;
    case DocParamSect::RetVal:
      m_t << "\n\\begin{DoxyRetVals}{";
      filter(theTranslator->trReturnValues());
      break;
    case DocParamSect::Exception:
      m_t << "\n\\begin{DoxyExceptions}{";
      filter(theTranslator->trExceptions());
      break;
    case DocParamSect::TemplateParam:
      m_t << "\n\\begin{DoxyTemplParams}{";
      filter(theTranslator->trTemplateParameters());
      break;
    default:
      ASSERT(0);
      incIndentLevel();
  }
  m_t << "}\n";
  visitChildren(s);
  m_ci.decUsedTableLevel();
  switch(s.type())
  {
    case DocParamSect::Param:
      m_t << "\\end{DoxyParams}\n";
      break;
    case DocParamSect::RetVal:
      m_t << "\\end{DoxyRetVals}\n";
      break;
    case DocParamSect::Exception:
      m_t << "\\end{DoxyExceptions}\n";
      break;
    case DocParamSect::TemplateParam:
      m_t << "\\end{DoxyTemplParams}\n";
      break;
    default:
      ASSERT(0);
      decIndentLevel();
  }
}
References ASSERT, decIndentLevel(), LatexCodeGenerator::decUsedTableLevel(), DocParamSect::Exception, filter(), incIndentLevel(), LatexCodeGenerator::incUsedTableLevel(), m_ci, m_hide, m_t, DocParamSect::Param, DocParamSect::RetVal, s, DocParamSect::TemplateParam, theTranslator, Translator::trExceptions(), Translator::trParameters(), Translator::trReturnValues(), Translator::trTemplateParameters(), and visitChildren().
operator()() [72/114]
void LatexDocVisitor::operator() (const DocParamSect &)
operator()() [73/114]
void LatexDocVisitor::operator() (const DocParBlock & pb)
Definition at line 1769 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(pb);
}
References m_hide, and visitChildren().
operator()() [74/114]
void LatexDocVisitor::operator() (const DocParBlock &)
operator()() [75/114]
void LatexDocVisitor::operator() (const DocRef & ref)
Definition at line 1501 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  // when ref.isSubPage()==TRUE we use ref.file() for HTML and
  // ref.anchor() for LaTeX/RTF
  if (ref.isSubPage())
  {
    startLink(ref.ref(),QCString(),ref.anchor());
  }
  else
  {
    if (!ref.file().isEmpty()) startLink(ref.ref(),ref.file(),ref.anchor(),ref.refToTable());
  }
  if (!ref.hasLinkText())
  {
    filter(ref.targetTitle());
  }
  visitChildren(ref);
  if (ref.isSubPage())
  {
    endLink(ref.ref(),QCString(),ref.anchor());
  }
  else
  {
    if (!ref.file().isEmpty()) endLink(ref.ref(),ref.file(),ref.anchor(),ref.refToTable());
  }
}
References DocRef::anchor(), endLink(), DocRef::file(), filter(), DocRef::hasLinkText(), QCString::isEmpty(), DocRef::isSubPage(), m_hide, DocRef::ref(), DocRef::refToTable(), startLink(), DocRef::targetTitle(), and visitChildren().
operator()() [76/114]
void LatexDocVisitor::operator() (const DocRef & ref)
operator()() [77/114]
void LatexDocVisitor::operator() (const DocRoot & r)
Definition at line 761 of file latexdocvisitor.cpp.
{
  visitChildren(r);
}
References r, and visitChildren().
operator()() [78/114]
void LatexDocVisitor::operator() (const DocRoot &)
operator()() [79/114]
void LatexDocVisitor::operator() (const DocSecRefItem & ref)
Definition at line 1529 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\item \\contentsline{section}{";
  if (ref.isSubPage())
  {
    startLink(ref.ref(),QCString(),ref.anchor());
  }
  else
  {
    if (!ref.file().isEmpty())
    {
      startLink(ref.ref(),ref.file(),ref.anchor(),ref.refToTable());
    }
  }
  visitChildren(ref);
  if (ref.isSubPage())
  {
    endLink(ref.ref(),QCString(),ref.anchor());
  }
  else
  {
    if (!ref.file().isEmpty()) endLink(ref.ref(),ref.file(),ref.anchor(),ref.refToTable());
  }
  m_t << "}{\\ref{";
  if (!ref.file().isEmpty()) m_t << stripPath(ref.file());
  if (!ref.file().isEmpty() && !ref.anchor().isEmpty()) m_t << "_";
  if (!ref.anchor().isEmpty()) m_t << ref.anchor();
  m_t << "}}{}\n";
}
References DocSecRefItem::anchor(), endLink(), DocSecRefItem::file(), QCString::isEmpty(), DocSecRefItem::isSubPage(), m_hide, m_t, DocSecRefItem::ref(), DocSecRefItem::refToTable(), startLink(), stripPath(), and visitChildren().
operator()() [80/114]
void LatexDocVisitor::operator() (const DocSecRefItem &)
operator()() [81/114]
void LatexDocVisitor::operator() (const DocSecRefList & l)
Definition at line 1560 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\footnotesize\n";
  m_t << "\\begin{multicols}{2}\n";
  m_t << "\\begin{DoxyCompactList}\n";
  incIndentLevel();
  visitChildren(l);
  decIndentLevel();
  m_t << "\\end{DoxyCompactList}\n";
  m_t << "\\end{multicols}\n";
  m_t << "\\normalsize\n";
}
References decIndentLevel(), incIndentLevel(), m_hide, m_t, and visitChildren().
operator()() [82/114]
void LatexDocVisitor::operator() (const DocSecRefList &)
operator()() [83/114]
void LatexDocVisitor::operator() (const DocSection & s)
Definition at line 935 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  if (Config_getBool(PDF_HYPERLINKS))
  {
    m_t << "\\hypertarget{" << stripPath(s.file()) << "_" << s.anchor() << "}{}";
  }
  m_t << "\\" << getSectionName(s.level()) << "{";
  filter(convertCharEntitiesToUTF8(s.title()));
  m_t << "}\\label{" << stripPath(s.file()) << "_" << s.anchor() << "}\n";
  visitChildren(s);
}
References Config_getBool, convertCharEntitiesToUTF8(), filter(), getSectionName(), m_hide, m_t, s, stripPath(), and visitChildren().
operator()() [84/114]
void LatexDocVisitor::operator() (const DocSection & s)
operator()() [85/114]
void LatexDocVisitor::operator() (const DocSeparator & sep)
Definition at line 1628 of file latexdocvisitor.cpp.
{
  m_t << " " << sep.chars() << " ";
}
References DocSeparator::chars(), and m_t.
operator()() [86/114]
void LatexDocVisitor::operator() (const DocSeparator &)
operator()() [87/114]
void LatexDocVisitor::operator() (const DocSimpleList & l)
Definition at line 914 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\begin{DoxyItemize}\n";
  m_listItemInfo[indentLevel()].isEnum = false;
  visitChildren(l);
  m_t << "\\end{DoxyItemize}\n";
}
References indentLevel(), LatexDocVisitor::LatexListItemInfo::isEnum, m_hide, m_listItemInfo, m_t, and visitChildren().
operator()() [88/114]
void LatexDocVisitor::operator() (const DocSimpleList &)
operator()() [89/114]
void LatexDocVisitor::operator() (const DocSimpleListItem & li)
Definition at line 923 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\item ";
  incIndentLevel();
  if (li.paragraph())
  {
    visit(*this,*li.paragraph());
  }
  decIndentLevel();
}
References decIndentLevel(), incIndentLevel(), m_hide, m_t, and DocSimpleListItem::paragraph().
operator()() [90/114]
void LatexDocVisitor::operator() (const DocSimpleListItem &)
operator()() [91/114]
void LatexDocVisitor::operator() (const DocSimpleSect & s)
Definition at line 766 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  switch(s.type())
  {
    case DocSimpleSect::See:
      m_t << "\\begin{DoxySeeAlso}{";
      filter(theTranslator->trSeeAlso());
      break;
    case DocSimpleSect::Return:
      m_t << "\\begin{DoxyReturn}{";
      filter(theTranslator->trReturns());
      break;
    case DocSimpleSect::Author:
      m_t << "\\begin{DoxyAuthor}{";
      filter(theTranslator->trAuthor(TRUE,TRUE));
      break;
    case DocSimpleSect::Authors:
      m_t << "\\begin{DoxyAuthor}{";
      filter(theTranslator->trAuthor(TRUE,FALSE));
      break;
    case DocSimpleSect::Version:
      m_t << "\\begin{DoxyVersion}{";
      filter(theTranslator->trVersion());
      break;
    case DocSimpleSect::Since:
      m_t << "\\begin{DoxySince}{";
      filter(theTranslator->trSince());
      break;
    case DocSimpleSect::Date:
      m_t << "\\begin{DoxyDate}{";
      filter(theTranslator->trDate());
      break;
    case DocSimpleSect::Note:
      m_t << "\\begin{DoxyNote}{";
      filter(theTranslator->trNote());
      break;
    case DocSimpleSect::Warning:
      m_t << "\\begin{DoxyWarning}{";
      filter(theTranslator->trWarning());
      break;
    case DocSimpleSect::Pre:
      m_t << "\\begin{DoxyPrecond}{";
      filter(theTranslator->trPrecondition());
      break;
    case DocSimpleSect::Post:
      m_t << "\\begin{DoxyPostcond}{";
      filter(theTranslator->trPostcondition());
      break;
    case DocSimpleSect::Copyright:
      m_t << "\\begin{DoxyCopyright}{";
      filter(theTranslator->trCopyright());
      break;
    case DocSimpleSect::Invar:
      m_t << "\\begin{DoxyInvariant}{";
      filter(theTranslator->trInvariant());
      break;
    case DocSimpleSect::Remark:
      m_t << "\\begin{DoxyRemark}{";
      filter(theTranslator->trRemarks());
      break;
    case DocSimpleSect::Attention:
      m_t << "\\begin{DoxyAttention}{";
      filter(theTranslator->trAttention());
      break;
    case DocSimpleSect::User:
      m_t << "\\begin{DoxyParagraph}{";
      break;
    case DocSimpleSect::Rcs:
      m_t << "\\begin{DoxyParagraph}{";
      break;
    case DocSimpleSect::Unknown: break;
  }
  if (s.title())
  {
    m_insideItem=TRUE;
    std::visit(*this,*s.title());
    m_insideItem=FALSE;
  }
  m_t << "}\n";
  incIndentLevel();
  visitChildren(s);
  switch(s.type())
  {
    case DocSimpleSect::See:
      m_t << "\n\\end{DoxySeeAlso}\n";
      break;
    case DocSimpleSect::Return:
      m_t << "\n\\end{DoxyReturn}\n";
      break;
    case DocSimpleSect::Author:
      m_t << "\n\\end{DoxyAuthor}\n";
      break;
    case DocSimpleSect::Authors:
      m_t << "\n\\end{DoxyAuthor}\n";
      break;
    case DocSimpleSect::Version:
      m_t << "\n\\end{DoxyVersion}\n";
      break;
    case DocSimpleSect::Since:
      m_t << "\n\\end{DoxySince}\n";
      break;
    case DocSimpleSect::Date:
      m_t << "\n\\end{DoxyDate}\n";
      break;
    case DocSimpleSect::Note:
      m_t << "\n\\end{DoxyNote}\n";
      break;
    case DocSimpleSect::Warning:
      m_t << "\n\\end{DoxyWarning}\n";
      break;
    case DocSimpleSect::Pre:
      m_t << "\n\\end{DoxyPrecond}\n";
      break;
    case DocSimpleSect::Post:
      m_t << "\n\\end{DoxyPostcond}\n";
      break;
    case DocSimpleSect::Copyright:
      m_t << "\n\\end{DoxyCopyright}\n";
      break;
    case DocSimpleSect::Invar:
      m_t << "\n\\end{DoxyInvariant}\n";
      break;
    case DocSimpleSect::Remark:
      m_t << "\n\\end{DoxyRemark}\n";
      break;
    case DocSimpleSect::Attention:
      m_t << "\n\\end{DoxyAttention}\n";
      break;
    case DocSimpleSect::User:
      m_t << "\n\\end{DoxyParagraph}\n";
      break;
    case DocSimpleSect::Rcs:
      m_t << "\n\\end{DoxyParagraph}\n";
      break;
    default:
      break;
  }
  decIndentLevel();
}
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, decIndentLevel(), FALSE, filter(), incIndentLevel(), DocSimpleSect::Invar, m_hide, m_insideItem, m_t, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, s, DocSimpleSect::See, DocSimpleSect::Since, theTranslator, Translator::trAttention(), Translator::trAuthor(), Translator::trCopyright(), Translator::trDate(), Translator::trInvariant(), Translator::trNote(), Translator::trPostcondition(), Translator::trPrecondition(), Translator::trRemarks(), Translator::trReturns(), Translator::trSeeAlso(), Translator::trSince(), TRUE, Translator::trVersion(), Translator::trWarning(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, visitChildren(), and DocSimpleSect::Warning.
operator()() [92/114]
void LatexDocVisitor::operator() (const DocSimpleSect &)
operator()() [93/114]
void LatexDocVisitor::operator() (const DocSimpleSectSep &)
Definition at line 689 of file latexdocvisitor.cpp.
{
}
operator()() [94/114]
void LatexDocVisitor::operator() (const DocSimpleSectSep &)
operator()() [95/114]
void LatexDocVisitor::operator() (const DocStyleChange & s)
Definition at line 329 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  switch (s.style())
  {
    case DocStyleChange::Bold:
      if (s.enable()) m_t << "{\\bfseries{"; else m_t << "}}";
      break;
    case DocStyleChange::S:
    case DocStyleChange::Strike:
    case DocStyleChange::Del:
      if (s.enable()) m_t << "\\sout{"; else m_t << "}";
      break;
    case DocStyleChange::Underline:
    case DocStyleChange::Ins:
      if (s.enable()) m_t << "\\uline{"; else m_t << "}";
      break;
    case DocStyleChange::Italic:
      if (s.enable()) m_t << "{\\itshape "; else m_t << "}";
      break;
    case DocStyleChange::Code:
      if (s.enable()) m_t << "{\\ttfamily "; else m_t << "}";
      break;
    case DocStyleChange::Subscript:
      if (s.enable()) m_t << "\\textsubscript{"; else m_t << "}";
      break;
    case DocStyleChange::Superscript:
      if (s.enable()) m_t << "\\textsuperscript{"; else m_t << "}";
      break;
    case DocStyleChange::Center:
      if (s.enable()) m_t << "\\begin{center}"; else m_t << "\\end{center} ";
      break;
    case DocStyleChange::Small:
      if (s.enable()) m_t << "\n\\footnotesize "; else m_t << "\n\\normalsize ";
      break;
    case DocStyleChange::Cite:
      if (s.enable()) m_t << "{\\itshape "; else m_t << "}";
      break;
    case DocStyleChange::Preformatted:
      if (s.enable())
      {
        m_t << "\n\\begin{DoxyPre}";
        m_insidePre=TRUE;
      }
      else
      {
        m_insidePre=FALSE;
        m_t << "\\end{DoxyPre}\n";
      }
      break;
    case DocStyleChange::Div: /* HTML only */ break;
    case DocStyleChange::Span: /* HTML only */ break;
  }
}
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Cite, DocStyleChange::Code, DocStyleChange::Del, DocStyleChange::Div, FALSE, DocStyleChange::Ins, DocStyleChange::Italic, m_hide, m_insidePre, m_t, DocStyleChange::Preformatted, s, DocStyleChange::S, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::Strike, DocStyleChange::Subscript, DocStyleChange::Superscript, TRUE, and DocStyleChange::Underline.
operator()() [96/114]
void LatexDocVisitor::operator() (const DocStyleChange &)
operator()() [97/114]
void LatexDocVisitor::operator() (const DocSymbol & s)
Definition at line 243 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  const char *res = HtmlEntityMapper::instance()->latex(s.symbol());
  if (res)
  {
    if (((s.symbol() == HtmlEntityMapper::Sym_lt) || (s.symbol() == HtmlEntityMapper::Sym_Less))&& (!m_insidePre))
    {
      if (pdfHyperlinks)
      {
        m_t << "\\texorpdfstring{$<$}{<}";
      }
      else
      {
        m_t << "$<$";
      }
    }
    else if (((s.symbol() == HtmlEntityMapper::Sym_gt) || (s.symbol() == HtmlEntityMapper::Sym_Greater)) && (!m_insidePre))
    {
      if (pdfHyperlinks)
      {
        m_t << "\\texorpdfstring{$>$}{>}";
      }
      else
      {
        m_t << "$>$";
      }
    }
    else
    {
      m_t << res;
    }
  }
  else
  {
    err("LaTeX: non supported HTML-entity found: %s\n",HtmlEntityMapper::instance()->html(s.symbol(),TRUE));
  }
}
References Config_getBool, err(), HtmlEntityMapper::instance(), HtmlEntityMapper::latex(), m_hide, m_insidePre, m_t, s, HtmlEntityMapper::Sym_Greater, HtmlEntityMapper::Sym_gt, HtmlEntityMapper::Sym_Less, HtmlEntityMapper::Sym_lt, and TRUE.
operator()() [98/114]
void LatexDocVisitor::operator() (const DocSymbol &)
operator()() [99/114]
void LatexDocVisitor::operator() (const DocText & t)
Definition at line 1749 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(t);
}
References m_hide, and visitChildren().
operator()() [100/114]
void LatexDocVisitor::operator() (const DocText &)
operator()() [101/114]
void LatexDocVisitor::operator() (const DocTitle & t)
Definition at line 908 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(t);
}
References m_hide, and visitChildren().
operator()() [102/114]
void LatexDocVisitor::operator() (const DocTitle &)
operator()() [103/114]
void LatexDocVisitor::operator() (const DocURL & u)
Definition at line 300 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  if (Config_getBool(PDF_HYPERLINKS))
  {
    m_t << "\\href{";
    if (u.isEmail()) m_t << "mailto:";
    m_t << latexFilterURL(u.url()) << "}";
  }
  m_t << "{\\texttt{ ";
  filter(u.url());
  m_t << "}}";
}
References Config_getBool, filter(), DocURL::isEmail(), latexFilterURL(), m_hide, m_t, and DocURL::url().
operator()() [104/114]
void LatexDocVisitor::operator() (const DocURL &)
operator()() [105/114]
void LatexDocVisitor::operator() (const DocVerbatim & s)
Definition at line 384 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  QCString lang = m_langExt;
  if (!s.language().isEmpty()) // explicit language setting
  {
    lang = s.language();
  }
  SrcLangExt langExt = getLanguageFromCodeLang(lang);
  switch(s.type())
  {
    case DocVerbatim::Code:
      {
        m_ci.startCodeFragment("DoxyCode");
        getCodeParser(lang).parseCode(m_ci,s.context(),s.text(),langExt,
                                      s.isExample(),s.exampleFile());
        m_ci.endCodeFragment("DoxyCode");
      }
      break;
    case DocVerbatim::JavaDocLiteral:
      filter(s.text(), true);
      break;
    case DocVerbatim::JavaDocCode:
      m_t << "{\\ttfamily ";
      filter(s.text(), true);
      m_t << "}";
      break;
    case DocVerbatim::Verbatim:
      m_t << "\\begin{DoxyVerb}";
      m_t << s.text();
      m_t << "\\end{DoxyVerb}\n";
      break;
    case DocVerbatim::HtmlOnly:
    case DocVerbatim::XmlOnly:
    case DocVerbatim::ManOnly:
    case DocVerbatim::RtfOnly:
    case DocVerbatim::DocbookOnly:
      /* nothing */
      break;
    case DocVerbatim::LatexOnly:
      m_t << s.text();
      break;
    case DocVerbatim::Dot:
      {
        static int dotindex = 1;
        QCString fileName(4096);
        fileName.sprintf("%s%d%s",
            qPrint(Config_getString(LATEX_OUTPUT)+"/inline_dotgraph_"),
            dotindex++,
            ".dot"
           );
        std::ofstream file(fileName.str(),std::ofstream::out | std::ofstream::binary);
        if (!file.is_open())
        {
          err("Could not open file %s for writing\n",qPrint(fileName));
        }
        else
        {
          file.write(s.text().data(), s.text().length());
          file.close();
          startDotFile(fileName,s.width(),s.height(),s.hasCaption(),s.srcFile(),s.srcLine());
          visitChildren(s);
          endDotFile(s.hasCaption());
          if (Config_getBool(DOT_CLEANUP)) Dir().remove(fileName.str());
        }
      }
      break;
    case DocVerbatim::Msc:
      {
        static int mscindex = 1;
        QCString baseName(4096);
        baseName.sprintf("%s%d",
            qPrint(Config_getString(LATEX_OUTPUT)+"/inline_mscgraph_"),
            mscindex++
           );
        std::string fileName = baseName.str()+".msc";
        std::ofstream file(fileName,std::ofstream::out | std::ofstream::binary);
        if (!file.is_open())
        {
          err("Could not open file %s for writing\n",fileName.c_str());
        }
        else
        {
          QCString text = "msc {";
          text+=s.text();
          text+="}";
          file.write(text.data(), text.length());
          file.close();
          writeMscFile(baseName, s);
          if (Config_getBool(DOT_CLEANUP)) Dir().remove(fileName);
        }
      }
      break;
    case DocVerbatim::PlantUML:
      {
        QCString latexOutput = Config_getString(LATEX_OUTPUT);
        QCString baseName = PlantumlManager::instance().writePlantUMLSource(
                              latexOutput,s.exampleFile(),s.text(),
                              s.useBitmap() ? PlantumlManager::PUML_BITMAP : PlantumlManager::PUML_EPS,
                              s.engine(),s.srcFile(),s.srcLine());
        writePlantUMLFile(baseName, s);
      }
      break;
  }
}
References DocVerbatim::Code, Config_getBool, Config_getString, gdFont::data, QCString::data(), DocVerbatim::DocbookOnly, DocVerbatim::Dot, LatexCodeGenerator::endCodeFragment(), endDotFile(), err(), caseconvert::file, filter(), DocVisitor::getCodeParser(), getLanguageFromCodeLang(), DocVerbatim::HtmlOnly, PlantumlManager::instance(), DocVerbatim::JavaDocCode, DocVerbatim::JavaDocLiteral, DocVerbatim::LatexOnly, QCString::length(), m_ci, m_hide, m_langExt, m_t, DocVerbatim::ManOnly, DocVerbatim::Msc, out, CodeParserInterface::parseCode(), DocVerbatim::PlantUML, PlantumlManager::PUML_BITMAP, PlantumlManager::PUML_EPS, qPrint(), Dir::remove(), DocVerbatim::RtfOnly, s, QCString::sprintf(), LatexCodeGenerator::startCodeFragment(), startDotFile(), QCString::str(), string, DocVerbatim::Verbatim, visitChildren(), writeMscFile(), writePlantUMLFile(), PlantumlManager::writePlantUMLSource(), and DocVerbatim::XmlOnly.
operator()() [106/114]
void LatexDocVisitor::operator() (const DocVerbatim &)
operator()() [107/114]
void LatexDocVisitor::operator() (const DocVhdlFlow &)
Definition at line 1765 of file latexdocvisitor.cpp.
{
}
operator()() [108/114]
void LatexDocVisitor::operator() (const DocVhdlFlow &)
operator()() [109/114]
void LatexDocVisitor::operator() (const DocWhiteSpace & w)
Definition at line 230 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  if (m_insidePre)
  {
    m_t << w.chars();
  }
  else
  {
    m_t << " ";
  }
}
References m_hide, m_insidePre, m_t, and w.
operator()() [110/114]
void LatexDocVisitor::operator() (const DocWhiteSpace &)
operator()() [111/114]
void LatexDocVisitor::operator() (const DocWord & w)
Definition at line 216 of file latexdocvisitor.cpp.
{
  if (m_hide) return;
  filter(w.word());
}
References filter(), m_hide, and w.
operator()() [112/114]
void LatexDocVisitor::operator() (const DocWord &)
operator()() [113/114]
void LatexDocVisitor::operator() (const DocXRefItem & x)
Definition at line 1708 of file latexdocvisitor.cpp.
{
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  if (m_hide) return;
  if (x.title().isEmpty()) return;
  incIndentLevel();
  m_t << "\\begin{DoxyRefDesc}{";
  filter(x.title());
  m_t << "}\n";
  bool anonymousEnum = x.file()=="@";
  m_t << "\\item[";
  if (pdfHyperlinks && !anonymousEnum)
  {
    m_t << "\\mbox{\\hyperlink{" << stripPath(x.file()) << "_" << x.anchor() << "}{";
  }
  else
  {
    m_t << "\\textbf{ ";
  }
  m_insideItem=TRUE;
  filter(x.title());
  m_insideItem=FALSE;
  if (pdfHyperlinks && !anonymousEnum)
  {
    m_t << "}";
  }
  m_t << "}]";
  visitChildren(x);
  if (x.title().isEmpty()) return;
  decIndentLevel();
  m_t << "\\end{DoxyRefDesc}\n";
}
References Config_getBool, decIndentLevel(), FALSE, filter(), incIndentLevel(), m_hide, m_insideItem, m_t, stripPath(), TRUE, visitChildren(), and x.
operator()() [114/114]
void LatexDocVisitor::operator() (const DocXRefItem &)
popTableState() [1/2]
void LatexDocVisitor::popTableState () [inline], [private]
Definition at line 196 of file latexdocvisitor.h.
    {
      m_tableStateStack.pop();
    }
References m_tableStateStack.
Referenced by operator()().
popTableState() [2/2]
void LatexDocVisitor::popTableState () [inline], [private]
Definition at line 196 of file latexdocvisitor.h.
    {
      m_tableStateStack.pop();
    }
References m_tableStateStack.
pushTableState() [1/2]
void LatexDocVisitor::pushTableState () [inline], [private]
Definition at line 192 of file latexdocvisitor.h.
    {
      m_tableStateStack.push(TableState());
    }
References m_tableStateStack.
Referenced by operator()().
pushTableState() [2/2]
void LatexDocVisitor::pushTableState () [inline], [private]
Definition at line 192 of file latexdocvisitor.h.
    {
      m_tableStateStack.push(TableState());
    }
References m_tableStateStack.
rowSpans() [1/2]
RowSpanList & LatexDocVisitor::rowSpans () [inline], [private]
Definition at line 240 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty() ? m_tableStateStack.top().rowSpans : m_emptyRowSpanList;
    }
References m_emptyRowSpanList, and m_tableStateStack.
Referenced by operator()().
rowSpans() [2/2]
RowSpanList & LatexDocVisitor::rowSpans () [inline], [private]
Definition at line 240 of file latexdocvisitor.h.
    {
      return !m_tableStateStack.empty() ? m_tableStateStack.top().rowSpans : m_emptyRowSpanList;
    }
References m_emptyRowSpanList, and m_tableStateStack.
setCurrentColumn() [1/2]
void LatexDocVisitor::setCurrentColumn (size_t col) [inline], [private]
Definition at line 204 of file latexdocvisitor.h.
    {
      if (!m_tableStateStack.empty()) m_tableStateStack.top().currentColumn = col;
    }
References m_tableStateStack.
Referenced by operator()().
setCurrentColumn() [2/2]
void LatexDocVisitor::setCurrentColumn (size_t col) [inline], [private]
Definition at line 204 of file latexdocvisitor.h.
    {
      if (!m_tableStateStack.empty()) m_tableStateStack.top().currentColumn = col;
    }
References m_tableStateStack.
setFirstRow() [1/2]
void LatexDocVisitor::setFirstRow (bool b) [inline], [private]
Definition at line 236 of file latexdocvisitor.h.
    {
      if (!m_tableStateStack.empty()) m_tableStateStack.top().firstRow = b;
    }
References b, and m_tableStateStack.
Referenced by operator()().
setFirstRow() [2/2]
void LatexDocVisitor::setFirstRow (bool b) [inline], [private]
Definition at line 236 of file latexdocvisitor.h.
    {
      if (!m_tableStateStack.empty()) m_tableStateStack.top().firstRow = b;
    }
References b, and m_tableStateStack.
setInColSpan() [1/2]
void LatexDocVisitor::setInColSpan (bool b) [inline], [private]
Definition at line 228 of file latexdocvisitor.h.
    {
      if (!m_tableStateStack.empty()) m_tableStateStack.top().inColSpan = b;
    }
References b, and m_tableStateStack.
Referenced by operator()().
setInColSpan() [2/2]
void LatexDocVisitor::setInColSpan (bool b) [inline], [private]
Definition at line 228 of file latexdocvisitor.h.
    {
      if (!m_tableStateStack.empty()) m_tableStateStack.top().inColSpan = b;
    }
References b, and m_tableStateStack.
setInRowSpan() [1/2]
void LatexDocVisitor::setInRowSpan (bool b) [inline], [private]
Definition at line 220 of file latexdocvisitor.h.
    {
      if (!m_tableStateStack.empty()) m_tableStateStack.top().inRowSpan = b;
    }
References b, and m_tableStateStack.
Referenced by operator()().
setInRowSpan() [2/2]
void LatexDocVisitor::setInRowSpan (bool b) [inline], [private]
Definition at line 220 of file latexdocvisitor.h.
    {
      if (!m_tableStateStack.empty()) m_tableStateStack.top().inRowSpan = b;
    }
References b, and m_tableStateStack.
setNumCols() [1/2]
void LatexDocVisitor::setNumCols (size_t num) [inline], [private]
Definition at line 212 of file latexdocvisitor.h.
    {
      if (!m_tableStateStack.empty()) m_tableStateStack.top().numCols = num;
    }
References m_tableStateStack.
Referenced by operator()().
setNumCols() [2/2]
void LatexDocVisitor::setNumCols (size_t num) [inline], [private]
Definition at line 212 of file latexdocvisitor.h.
    {
      if (!m_tableStateStack.empty()) m_tableStateStack.top().numCols = num;
    }
References m_tableStateStack.
startDiaFile() [1/2]
void LatexDocVisitor::startDiaFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption, const QCString & srcFile, int srcLine) [private]
Definition at line 1919 of file latexdocvisitor.cpp.
{
  QCString baseName=fileName;
  int i;
  if ((i=baseName.findRev('/'))!=-1)
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  if ((i=baseName.find('.'))!=-1)
  {
    baseName=baseName.left(i);
  }
  baseName.prepend("dia_");
  QCString outDir = Config_getString(LATEX_OUTPUT);
  writeDiaGraphFromFile(fileName,outDir,baseName,DIA_EPS,srcFile,srcLine);
  visitPreStart(m_t,hasCaption, baseName, width, height);
}
References Config_getString, DIA_EPS, QCString::find(), QCString::findRev(), QCString::left(), QCString::length(), m_t, QCString::prepend(), QCString::right(), visitPreStart(), and writeDiaGraphFromFile().
Referenced by operator()().
startDiaFile() [2/2]
void LatexDocVisitor::startDiaFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption, const QCString & srcFile, int srcLine) [private]
startDotFile() [1/2]
void LatexDocVisitor::startDotFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption, const QCString & srcFile, int srcLine) [private]
Definition at line 1840 of file latexdocvisitor.cpp.
{
  QCString baseName=fileName;
  int i;
  if ((i=baseName.findRev('/'))!=-1)
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  if ((i=baseName.find('.'))!=-1)
  {
    baseName=baseName.left(i);
  }
  baseName.prepend("dot_");
  QCString outDir = Config_getString(LATEX_OUTPUT);
  QCString name = fileName;
  writeDotGraphFromFile(name,outDir,baseName,GOF_EPS,srcFile,srcLine);
  visitPreStart(m_t,hasCaption, baseName, width, height);
}
References Config_getString, QCString::find(), QCString::findRev(), GOF_EPS, QCString::left(), QCString::length(), m_t, setup::name, QCString::prepend(), QCString::right(), visitPreStart(), and writeDotGraphFromFile().
Referenced by operator()().
startDotFile() [2/2]
void LatexDocVisitor::startDotFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption, const QCString & srcFile, int srcLine) [private]
startLink() [1/2]
void LatexDocVisitor::startLink (const QCString & ref, const QCString & file, const QCString & anchor, bool refToTable = FALSE) [private]
Definition at line 1787 of file latexdocvisitor.cpp.
{
  bool pdfHyperLinks = Config_getBool(PDF_HYPERLINKS);
  if (ref.isEmpty() && pdfHyperLinks) // internal PDF link
  {
    if (refToTable)
    {
      m_t << "\\doxytablelink{";
    }
    else
    {
      m_t << "\\mbox{\\hyperlink{";
    }
    if (!file.isEmpty()) m_t << stripPath(file);
    if (!file.isEmpty() && !anchor.isEmpty()) m_t << "_";
    if (!anchor.isEmpty()) m_t << anchor;
    m_t << "}{";
  }
  else if (ref.isEmpty() && refToTable)
  {
    m_t << "\\doxytableref{";
  }
  else if (ref.isEmpty()) // internal non-PDF link
  {
    m_t << "\\doxyref{";
  }
  else // external link
  {
    m_t << "\\textbf{ ";
  }
}
References Config_getBool, caseconvert::file, QCString::isEmpty(), m_t, and stripPath().
Referenced by operator()().
startLink() [2/2]
void LatexDocVisitor::startLink (const QCString & ref, const QCString & file, const QCString & anchor, bool refToTable = FALSE) [private]
startMscFile() [1/2]
void LatexDocVisitor::startMscFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption, const QCString & srcFile, int srcLine) [private]
Definition at line 1871 of file latexdocvisitor.cpp.
{
  QCString baseName=fileName;
  int i;
  if ((i=baseName.findRev('/'))!=-1)
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  if ((i=baseName.find('.'))!=-1)
  {
    baseName=baseName.left(i);
  }
  baseName.prepend("msc_");
  QCString outDir = Config_getString(LATEX_OUTPUT);
  writeMscGraphFromFile(fileName,outDir,baseName,MSC_EPS,srcFile,srcLine);
  visitPreStart(m_t,hasCaption, baseName, width, height);
}
References Config_getString, QCString::find(), QCString::findRev(), QCString::left(), QCString::length(), m_t, MSC_EPS, QCString::prepend(), QCString::right(), visitPreStart(), and writeMscGraphFromFile().
Referenced by operator()().
startMscFile() [2/2]
void LatexDocVisitor::startMscFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption, const QCString & srcFile, int srcLine) [private]
visitCaption() [1/2]
void LatexDocVisitor::visitCaption (const DocNodeList & children) [private]
Definition at line 168 of file latexdocvisitor.cpp.
{
  for (const auto &n : children)
  {
    std::visit(*this,n);
  }
}
References n.
Referenced by writeDiaFile(), writeMscFile(), and writePlantUMLFile().
visitCaption() [2/2]
void LatexDocVisitor::visitCaption (const DocNodeList & children) [private]
visitChildren() [1/2]
template<class T >
void LatexDocVisitor::visitChildren (const T & t) [inline], [private]
Definition at line 105 of file latexdocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
Referenced by operator()().
visitChildren() [2/2]
template<class T >
void LatexDocVisitor::visitChildren (const T & t) [inline], [private]
Definition at line 105 of file latexdocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
writeDiaFile() [1/2]
void LatexDocVisitor::writeDiaFile (const QCString & fileName, const DocVerbatim & s) [private]
Definition at line 1951 of file latexdocvisitor.cpp.
{
  QCString shortName = baseName;
  int i;
  if ((i=shortName.findRev('/'))!=-1)
  {
    shortName=shortName.right(shortName.length()-i-1);
  }
  QCString outDir = Config_getString(LATEX_OUTPUT);
  writeDiaGraphFromFile(baseName+".dia",outDir,shortName,DIA_EPS,s.srcFile(),s.srcLine());
  visitPreStart(m_t, s.hasCaption(), shortName, s.width(), s.height());
  visitCaption(s.children());
  visitPostEnd(m_t, s.hasCaption());
}
References Config_getString, DIA_EPS, QCString::findRev(), QCString::length(), m_t, QCString::right(), s, visitCaption(), visitPostEnd(), visitPreStart(), and writeDiaGraphFromFile().
writeDiaFile() [2/2]
void LatexDocVisitor::writeDiaFile (const QCString & fileName, const DocVerbatim & s) [private]
writeMscFile() [1/2]
void LatexDocVisitor::writeMscFile (const QCString & fileName, const DocVerbatim & s) [private]
Definition at line 1903 of file latexdocvisitor.cpp.
{
  QCString shortName = baseName;
  int i;
  if ((i=shortName.findRev('/'))!=-1)
  {
    shortName=shortName.right(shortName.length()-i-1);
  }
  QCString outDir = Config_getString(LATEX_OUTPUT);
  writeMscGraphFromFile(baseName+".msc",outDir,shortName,MSC_EPS,s.srcFile(),s.srcLine());
  visitPreStart(m_t, s.hasCaption(), shortName, s.width(),s.height());
  visitCaption(s.children());
  visitPostEnd(m_t, s.hasCaption());
}
References Config_getString, QCString::findRev(), QCString::length(), m_t, MSC_EPS, QCString::right(), s, visitCaption(), visitPostEnd(), visitPreStart(), and writeMscGraphFromFile().
Referenced by operator()().
writeMscFile() [2/2]
void LatexDocVisitor::writeMscFile (const QCString & fileName, const DocVerbatim & s) [private]
writePlantUMLFile() [1/2]
void LatexDocVisitor::writePlantUMLFile (const QCString & fileName, const DocVerbatim & s) [private]
Definition at line 1966 of file latexdocvisitor.cpp.
{
  QCString shortName = baseName;
  int i;
  if ((i=shortName.findRev('/'))!=-1)
  {
    shortName=shortName.right(shortName.length()-i-1);
  }
  if (s.useBitmap())
  {
    if (shortName.find('.')==-1) shortName += ".png";
  }
  QCString outDir = Config_getString(LATEX_OUTPUT);
  PlantumlManager::instance().generatePlantUMLOutput(baseName,outDir,
                              s.useBitmap() ? PlantumlManager::PUML_BITMAP : PlantumlManager::PUML_EPS);
  visitPreStart(m_t, s.hasCaption(), shortName, s.width(), s.height());
  visitCaption(s.children());
  visitPostEnd(m_t, s.hasCaption());
}
References Config_getString, QCString::find(), QCString::findRev(), PlantumlManager::generatePlantUMLOutput(), PlantumlManager::instance(), QCString::length(), m_t, PlantumlManager::PUML_BITMAP, PlantumlManager::PUML_EPS, QCString::right(), s, visitCaption(), visitPostEnd(), and visitPreStart().
Referenced by operator()().
writePlantUMLFile() [2/2]
void LatexDocVisitor::writePlantUMLFile (const QCString & fileName, const DocVerbatim & s) [private]
Member Data Documentation
m_ci
LatexCodeGenerator & LatexDocVisitor::m_ci [private]
Definition at line 163 of file latexdocvisitor.h.
Referenced by filter(), and operator()().
m_emptyRowSpanList
RowSpanList LatexDocVisitor::m_emptyRowSpanList [private]
Definition at line 180 of file latexdocvisitor.h.
Referenced by rowSpans().
m_hide
bool LatexDocVisitor::m_hide [private]
Definition at line 166 of file latexdocvisitor.h.
Referenced by endDiaFile(), endDotFile(), endMscFile(), and operator()().
m_indentLevel
int LatexDocVisitor::m_indentLevel = 0 [private]
Definition at line 183 of file latexdocvisitor.h.
Referenced by decIndentLevel(), incIndentLevel(), indentLevel(), and operator()().
m_insideItem
bool LatexDocVisitor::m_insideItem [private]
Definition at line 165 of file latexdocvisitor.h.
Referenced by filter(), and operator()().
m_insidePre
bool LatexDocVisitor::m_insidePre [private]
Definition at line 164 of file latexdocvisitor.h.
Referenced by filter(), and operator()().
m_insideTabbing
bool LatexDocVisitor::m_insideTabbing [private]
Definition at line 167 of file latexdocvisitor.h.
Referenced by filter().
m_langExt
QCString LatexDocVisitor::m_langExt [private]
Definition at line 168 of file latexdocvisitor.h.
Referenced by operator()().
m_listItemInfo
LatexListItemInfo LatexDocVisitor::m_listItemInfo [private]
Definition at line 190 of file latexdocvisitor.h.
Referenced by operator()().
m_t
TextStream & LatexDocVisitor::m_t [private]
Definition at line 162 of file latexdocvisitor.h.
Referenced by endDiaFile(), endDotFile(), endLink(), endMscFile(), escapeMakeIndexChars(), filter(), operator()(), startDiaFile(), startDotFile(), startLink(), startMscFile(), writeDiaFile(), writeMscFile(), and writePlantUMLFile().
m_tableStateStack
std::stack< TableState > LatexDocVisitor::m_tableStateStack [private]
Definition at line 179 of file latexdocvisitor.h.
Referenced by addRowSpan(), currentColumn(), firstRow(), inColSpan(), inRowSpan(), insideTable(), numCols(), popTableState(), pushTableState(), rowSpans(), setCurrentColumn(), setFirstRow(), setInColSpan(), setInRowSpan(), and setNumCols().
maxIndentLevels
static const int LatexDocVisitor::maxIndentLevels = 13 [static], [private]
Definition at line 182 of file latexdocvisitor.h.
Referenced by incIndentLevel(), indentLevel(), and operator()().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/latexdocvisitor.h
doxygen/src/latexdocvisitor.h
doxygen/build/doxygen/src/latexdocvisitor.cpp
doxygen/src/latexdocvisitor.cpp