Statistics Class Reference
Classes
struct stat
Public Member Functions
Statistics ()
void begin (const char *name)
void end ()
void print ()
Statistics ()
void begin (const char *name)
void end ()
void print ()
Private Attributes
std::vector< stat > stats
std::chrono::steady_clock::time_point startTime
Detailed Description
Definition at line 211 of file doxygen.cpp.
Constructor & Destructor Documentation
Statistics() [1/2]
Statistics::Statistics () [inline]
Definition at line 214 of file doxygen.cpp.
{}
Statistics() [2/2]
Statistics::Statistics () [inline]
Definition at line 214 of file doxygen.cpp.
{}
Member Function Documentation
begin() [1/2]
void Statistics::begin (const char * name) [inline]
Definition at line 215 of file doxygen.cpp.
    {
      msg("%s", name);
      stats.emplace_back(name,0);
      startTime = std::chrono::steady_clock::now();
    }
References msg(), setup::name, startTime, and stats.
Referenced by generateOutput(), parseInput(), and searchInputFiles().
begin() [2/2]
void Statistics::begin (const char * name) [inline]
Definition at line 215 of file doxygen.cpp.
    {
      msg("%s", name);
      stats.emplace_back(name,0);
      startTime = std::chrono::steady_clock::now();
    }
References msg(), setup::name, startTime, and stats.
end() [1/2]
void Statistics::end () [inline]
Definition at line 221 of file doxygen.cpp.
    {
      std::chrono::steady_clock::time_point endTime = std::chrono::steady_clock::now();
      stats.back().elapsed = static_cast<double>(std::chrono::duration_cast<
                                std::chrono::microseconds>(endTime - startTime).count())/1000000.0;
    }
References startTime, and stats.
Referenced by generateOutput(), parseInput(), and searchInputFiles().
end() [2/2]
void Statistics::end () [inline]
Definition at line 221 of file doxygen.cpp.
    {
      std::chrono::steady_clock::time_point endTime = std::chrono::steady_clock::now();
      stats.back().elapsed = static_cast<double>(std::chrono::duration_cast<
                                std::chrono::microseconds>(endTime - startTime).count())/1000000.0;
    }
References startTime, and stats.
print() [1/2]
void Statistics::print () [inline]
Definition at line 227 of file doxygen.cpp.
    {
      bool restore=FALSE;
      if (Debug::isFlagSet(Debug::Time))
      {
        Debug::clearFlag("time");
        restore=TRUE;
      }
      msg("----------------------\n");
      for (const auto &s : stats)
      {
        msg("Spent %.6f seconds in %s",s.elapsed,s.name);
      }
      if (restore) Debug::setFlag("time");
    }
References Debug::clearFlag(), FALSE, Debug::isFlagSet(), msg(), s, Debug::setFlag(), stats, Debug::Time, and TRUE.
Referenced by generateOutput().
print() [2/2]
void Statistics::print () [inline]
Definition at line 227 of file doxygen.cpp.
    {
      bool restore=FALSE;
      if (Debug::isFlagSet(Debug::Time))
      {
        Debug::clearFlag("time");
        restore=TRUE;
      }
      msg("----------------------\n");
      for (const auto &s : stats)
      {
        msg("Spent %.6f seconds in %s",s.elapsed,s.name);
      }
      if (restore) Debug::setFlag("time");
    }
References Debug::clearFlag(), FALSE, Debug::isFlagSet(), msg(), s, Debug::setFlag(), stats, Debug::Time, and TRUE.
Member Data Documentation
startTime
std::chrono::steady_clock::time_point Statistics::startTime [private]
Definition at line 251 of file doxygen.cpp.
Referenced by begin(), and end().
stats
std::vector< stat > Statistics::stats [private]
Definition at line 250 of file doxygen.cpp.
Referenced by begin(), end(), and print().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/doxygen.cpp
doxygen/src/doxygen.cpp