MemberGroupInfoContext::Private Class Reference
Public Member Functions
Private (const Definition *def, const QCString &relPath, const MemberGroup *mg)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (const Definition *def, const QCString &relPath, const MemberGroup *mg)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant members () const
TemplateVariant groupTitle () const
TemplateVariant groupSubtitle () const
TemplateVariant memberGroups () const
TemplateVariant docs () const
TemplateVariant inherited () const
TemplateVariant createMembers () const
TemplateVariant createMemberGroups () const
TemplateVariant createDocs () const
TemplateVariant members () const
TemplateVariant groupTitle () const
TemplateVariant groupSubtitle () const
TemplateVariant memberGroups () const
TemplateVariant docs () const
TemplateVariant inherited () const
TemplateVariant createMembers () const
TemplateVariant createMemberGroups () const
TemplateVariant createDocs () const
Private Attributes
const Definition * m_def
QCString m_relPath
const MemberGroup * m_memberGroup
CachedItem< TemplateVariant, Private,&Private::createDocs > m_docs
CachedItem< TemplateVariant, Private,&Private::createMembers > m_members
CachedItem< TemplateVariant, Private,&Private::createMemberGroups > m_memberGroups
Static Private Attributes
static const PropertyMap< MemberGroupInfoContext::Private > s_inst
Detailed Description
Definition at line 7773 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
MemberGroupInfoContext::Private::Private (const Definition * def, const QCString & relPath, const MemberGroup * mg) [inline]
Definition at line 7776 of file context.cpp.
      : m_def(def), m_relPath(relPath), m_memberGroup(mg) {}
Private() [2/2]
MemberGroupInfoContext::Private::Private (const Definition * def, const QCString & relPath, const MemberGroup * mg) [inline]
Definition at line 7776 of file context.cpp.
      : m_def(def), m_relPath(relPath), m_memberGroup(mg) {}
Member Function Documentation
createDocs() [1/2]
TemplateVariant MemberGroupInfoContext::Private::createDocs () const [inline], [private]
Definition at line 7801 of file context.cpp.
    {
      return !m_memberGroup->documentation().isEmpty() ?
          TemplateVariant(parseDoc(m_def,"[@name docs]",-1, // TODO store file & line
                                   m_relPath,
                                   m_memberGroup->documentation(),FALSE)) :
          TemplateVariant("");
    }
References MemberGroup::documentation(), FALSE, QCString::isEmpty(), m_def, m_memberGroup, m_relPath, and parseDoc().
createDocs() [2/2]
TemplateVariant MemberGroupInfoContext::Private::createDocs () const [inline], [private]
Definition at line 7801 of file context.cpp.
    {
      return !m_memberGroup->documentation().isEmpty() ?
          TemplateVariant(parseDoc(m_def,"[@name docs]",-1, // TODO store file & line
                                   m_relPath,
                                   m_memberGroup->documentation(),FALSE)) :
          TemplateVariant("");
    }
References FALSE, and parseDoc().
createMemberGroups() [1/2]
TemplateVariant MemberGroupInfoContext::Private::createMemberGroups () const [inline], [private]
Definition at line 7797 of file context.cpp.
    {
      return MemberGroupListContext::alloc();
    }
References MemberGroupListContext::alloc().
createMemberGroups() [2/2]
TemplateVariant MemberGroupInfoContext::Private::createMemberGroups () const [inline], [private]
Definition at line 7797 of file context.cpp.
    {
      return MemberGroupListContext::alloc();
    }
References MemberGroupListContext::alloc().
createMembers() [1/2]
TemplateVariant MemberGroupInfoContext::Private::createMembers () const [inline], [private]
Definition at line 7793 of file context.cpp.
    {
      return MemberListContext::alloc(&m_memberGroup->members());
    }
References MemberListContext::alloc(), m_memberGroup, and MemberGroup::members().
createMembers() [2/2]
TemplateVariant MemberGroupInfoContext::Private::createMembers () const [inline], [private]
Definition at line 7793 of file context.cpp.
    {
      return MemberListContext::alloc(&m_memberGroup->members());
    }
References MemberListContext::alloc().
docs() [1/2]
TemplateVariant MemberGroupInfoContext::Private::docs () const [inline], [private]
Definition at line 7789 of file context.cpp.
{ return m_docs.get(this); }
References m_docs.
docs() [2/2]
TemplateVariant MemberGroupInfoContext::Private::docs () const [inline], [private]
Definition at line 7789 of file context.cpp.
{ return m_docs.get(this); }
fields() [1/2]
StringVector MemberGroupInfoContext::Private::fields () const [inline]
Definition at line 7781 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector MemberGroupInfoContext::Private::fields () const [inline]
Definition at line 7781 of file context.cpp.
{ return s_inst.fields(); }
get() [1/2]
TemplateVariant MemberGroupInfoContext::Private::get (const QCString & n) const [inline]
Definition at line 7780 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant MemberGroupInfoContext::Private::get (const QCString & n) const [inline]
Definition at line 7780 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
groupSubtitle() [1/2]
TemplateVariant MemberGroupInfoContext::Private::groupSubtitle () const [inline], [private]
Definition at line 7787 of file context.cpp.
{ return ""; }
groupSubtitle() [2/2]
TemplateVariant MemberGroupInfoContext::Private::groupSubtitle () const [inline], [private]
Definition at line 7787 of file context.cpp.
{ return ""; }
groupTitle() [1/2]
TemplateVariant MemberGroupInfoContext::Private::groupTitle () const [inline], [private]
Definition at line 7786 of file context.cpp.
{ return m_memberGroup->header(); }
References MemberGroup::header(), and m_memberGroup.
groupTitle() [2/2]
TemplateVariant MemberGroupInfoContext::Private::groupTitle () const [inline], [private]
Definition at line 7786 of file context.cpp.
{ return m_memberGroup->header(); }
inherited() [1/2]
TemplateVariant MemberGroupInfoContext::Private::inherited () const [inline], [private]
Definition at line 7790 of file context.cpp.
{ return FALSE; }
References FALSE.
inherited() [2/2]
TemplateVariant MemberGroupInfoContext::Private::inherited () const [inline], [private]
Definition at line 7790 of file context.cpp.
{ return FALSE; }
References FALSE.
memberGroups() [1/2]
TemplateVariant MemberGroupInfoContext::Private::memberGroups () const [inline], [private]
Definition at line 7788 of file context.cpp.
{ return m_memberGroups.get(this); }
References m_memberGroups.
memberGroups() [2/2]
TemplateVariant MemberGroupInfoContext::Private::memberGroups () const [inline], [private]
Definition at line 7788 of file context.cpp.
{ return m_memberGroups.get(this); }
members() [1/2]
TemplateVariant MemberGroupInfoContext::Private::members () const [inline], [private]
Definition at line 7785 of file context.cpp.
{ return m_members.get(this); }
References m_members.
members() [2/2]
TemplateVariant MemberGroupInfoContext::Private::members () const [inline], [private]
Definition at line 7785 of file context.cpp.
{ return m_members.get(this); }
Member Data Documentation
m_def
const Definition * MemberGroupInfoContext::Private::m_def [private]
Definition at line 7809 of file context.cpp.
Referenced by createDocs().
m_docs
CachedItem< TemplateVariant, Private,&Private::createDocs > MemberGroupInfoContext::Private::m_docs [private]
Definition at line 7812 of file context.cpp.
Referenced by docs().
m_memberGroup
const MemberGroup * MemberGroupInfoContext::Private::m_memberGroup [private]
Definition at line 7811 of file context.cpp.
Referenced by createDocs(), createMembers(), and groupTitle().
m_memberGroups
CachedItem< TemplateVariant, Private,&Private::createMemberGroups > MemberGroupInfoContext::Private::m_memberGroups [private]
Definition at line 7814 of file context.cpp.
Referenced by memberGroups().
m_members
CachedItem< TemplateVariant, Private,&Private::createMembers > MemberGroupInfoContext::Private::m_members [private]
Definition at line 7813 of file context.cpp.
Referenced by members().
m_relPath
QCString MemberGroupInfoContext::Private::m_relPath [private]
Definition at line 7810 of file context.cpp.
Referenced by createDocs().
s_inst
const PropertyMap< MemberGroupInfoContext::Private > MemberGroupInfoContext::Private::s_inst [static], [private]
Initial value:
{
  { "members", &Private::members },
  { "title", &Private::groupTitle },
  { "subtitle", &Private::groupSubtitle },
  { "memberGroups", &Private::memberGroups },
  { "docs", &Private::docs },
  { "inherited", &Private::inherited }
}
Definition at line 7815 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp