ClassContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
ClassContext (const ClassDef *)
virtual ~ClassContext ()
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
ClassContext (const ClassDef *)
virtual ~ClassContext ()
Static Public Member Functions
static TemplateStructIntfPtr alloc (const ClassDef *cd)
static TemplateStructIntfPtr alloc (const ClassDef *cd)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 196 of file context.h.
Constructor & Destructor Documentation
ClassContext() [1/2]
ClassContext::ClassContext (const ClassDef * cd)
Definition at line 2472 of file context.cpp.
                                             : p(std::make_unique<Private>(cd))
{
}
 ClassContext() [1/2]
ClassContext::~ClassContext () [virtual]
Definition at line 2476 of file context.cpp.
{
}
ClassContext() [2/2]
ClassContext::ClassContext (const ClassDef *)
 ClassContext() [2/2]
virtual ClassContext::~ClassContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateStructIntfPtr ClassContext::alloc (const ClassDef * cd) [inline], [static]
Definition at line 199 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<ClassContext>(cd)); }
Referenced by ClassListContext::Private::addClasses(), MemberContext::Private::createAnonymousType(), MemberContext::Private::createCategory(), ClassContext::Private::createCategoryOf(), NestingNodeContext::Private::createClass(), InheritanceNodeContext::Private::createClass(), InheritedMemberInfoContext::Private::createClass(), MemberContext::Private::createClassDef(), ClassContext::Private::createClasses(), NamespaceContext::Private::createClasses(), FileContext::Private::createClasses(), ModuleContext::Private::createClasses(), ClassIndexContext::Private::createClasses(), NamespaceContext::Private::createInlineClasses(), FileContext::Private::createInlineClasses(), ModuleContext::Private::createInlineClasses(), and ClassContext::Private::createInnerClasses().
alloc() [2/2]
static TemplateStructIntfPtr ClassContext::alloc (const ClassDef * cd) [inline], [static]
Definition at line 199 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<ClassContext>(cd)); }
fields() [1/2]
StringVector ClassContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 2485 of file context.cpp.
{
  return p->fields();
}
References p.
fields() [2/2]
virtual StringVector ClassContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant ClassContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 2480 of file context.cpp.
{
  return p->get(n);
}
References n, and p.
get() [2/2]
virtual TemplateVariant ClassContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Member Data Documentation
p
std::unique_ptr< Private > ClassContext::p [private]
Definition at line 211 of file context.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp