NamespaceDefImpl Class Reference
Public Member Functions
NamespaceDefImpl (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const QCString &ref=QCString(), const QCString &refFile=QCString(), const QCString &type=QCString(), bool isPublished=false)
virtual ~NamespaceDefImpl ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual void insertUsedFile (FileDef *fd)
virtual void writeDocumentation (OutputList &ol)
virtual void writeMemberPages (OutputList &ol)
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const
virtual void writeTagFile (TextStream &)
virtual void insertClass (const ClassDef *cd)
virtual void insertConcept (const ConceptDef *cd)
virtual void insertNamespace (const NamespaceDef *nd)
virtual void insertMember (MemberDef *md)
virtual void computeAnchors ()
virtual void countMembers ()
virtual int numDocMembers () const
virtual void addUsingDirective (const NamespaceDef *nd)
virtual const LinkedRefMap< const NamespaceDef > & getUsedNamespaces () const
virtual void addUsingDeclaration (const ClassDef *cd)
virtual const LinkedRefMap< const ClassDef > & getUsedClasses () const
virtual void combineUsingRelations (NamespaceDefSet &visitedNamespace)
virtual QCString displayName (bool=TRUE) const
virtual QCString localName () const
virtual void setInline (bool isInline)
virtual bool isConstantGroup () const
virtual bool isModule () const
virtual bool isLibrary () const
virtual bool isInline () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool hasDetailedDescription () const
virtual void addMembersToMemberGroup ()
virtual void distributeMemberGroupDocumentation ()
virtual void findSectionsInDocumentation ()
virtual void sortMemberLists ()
virtual const Definition * findInnerCompound (const QCString &name) const
virtual void addInnerCompound (const Definition *d)
virtual void addListReferences ()
virtual void setFileName (const QCString &fn)
virtual bool subGrouping () const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberDef * getMemberByName (const QCString &) const
virtual const MemberGroupList & getMemberGroups () const
virtual ClassLinkedRefMap getClasses () const
virtual ClassLinkedRefMap getInterfaces () const
virtual ClassLinkedRefMap getStructs () const
virtual ClassLinkedRefMap getExceptions () const
virtual NamespaceLinkedRefMap getNamespaces () const
virtual ConceptLinkedRefMap getConcepts () const
virtual QCString title () const
virtual QCString compoundTypeString () const
virtual void setMetaData (const QCString &m)
NamespaceDefImpl (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const QCString &ref=QCString(), const QCString &refFile=QCString(), const QCString &type=QCString(), bool isPublished=false)
virtual ~NamespaceDefImpl ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual void insertUsedFile (FileDef *fd)
virtual void writeDocumentation (OutputList &ol)
virtual void writeMemberPages (OutputList &ol)
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const
virtual void writeTagFile (TextStream &)
virtual void insertClass (const ClassDef *cd)
virtual void insertConcept (const ConceptDef *cd)
virtual void insertNamespace (const NamespaceDef *nd)
virtual void insertMember (MemberDef *md)
virtual void computeAnchors ()
virtual void countMembers ()
virtual int numDocMembers () const
virtual void addUsingDirective (const NamespaceDef *nd)
virtual const LinkedRefMap< const NamespaceDef > & getUsedNamespaces () const
virtual void addUsingDeclaration (const ClassDef *cd)
virtual const LinkedRefMap< const ClassDef > & getUsedClasses () const
virtual void combineUsingRelations (NamespaceDefSet &visitedNamespace)
virtual QCString displayName (bool=TRUE) const
virtual QCString localName () const
virtual void setInline (bool isInline)
virtual bool isConstantGroup () const
virtual bool isModule () const
virtual bool isLibrary () const
virtual bool isInline () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool hasDetailedDescription () const
virtual void addMembersToMemberGroup ()
virtual void distributeMemberGroupDocumentation ()
virtual void findSectionsInDocumentation ()
virtual void sortMemberLists ()
virtual const Definition * findInnerCompound (const QCString &name) const
virtual void addInnerCompound (const Definition *d)
virtual void addListReferences ()
virtual void setFileName (const QCString &fn)
virtual bool subGrouping () const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberDef * getMemberByName (const QCString &) const
virtual const MemberGroupList & getMemberGroups () const
virtual ClassLinkedRefMap getClasses () const
virtual ClassLinkedRefMap getInterfaces () const
virtual ClassLinkedRefMap getStructs () const
virtual ClassLinkedRefMap getExceptions () const
virtual NamespaceLinkedRefMap getNamespaces () const
virtual ConceptLinkedRefMap getConcepts () const
virtual QCString title () const
virtual QCString compoundTypeString () const
virtual void setMetaData (const QCString &m)
Private Types
enum { NAMESPACE
, MODULE
, CONSTANT_GROUP
, LIBRARY
 }
enum { NAMESPACE
, MODULE
, CONSTANT_GROUP
, LIBRARY
 }
Private Member Functions
void addMemberToList (MemberListType lt, MemberDef *md)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void writeClassDeclarations (OutputList &ol, const QCString &title, const ClassLinkedRefMap &d)
void writeConcepts (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void writeMemberGroups (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeSummaryLinks (OutputList &ol) const
void addNamespaceAttributes (OutputList &ol)
void writeClassesToTagFile (TextStream &, const ClassLinkedRefMap &d)
void writeConceptsToTagFile (TextStream &)
void writeNamespaceDeclarations (OutputList &ol, const QCString &title, bool isConstantGroup=false)
void addMemberToList (MemberListType lt, MemberDef *md)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void writeClassDeclarations (OutputList &ol, const QCString &title, const ClassLinkedRefMap &d)
void writeConcepts (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void writeMemberGroups (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeSummaryLinks (OutputList &ol) const
void addNamespaceAttributes (OutputList &ol)
void writeClassesToTagFile (TextStream &, const ClassLinkedRefMap &d)
void writeConceptsToTagFile (TextStream &)
void writeNamespaceDeclarations (OutputList &ol, const QCString &title, bool isConstantGroup=false)
Private Attributes
QCString fileName
FileList files
LinkedRefMap< const NamespaceDef > m_usingDirList
LinkedRefMap< const ClassDef > m_usingDeclList
LinkedRefMap< const Definition > m_innerCompounds
MemberLinkedRefMap m_allMembers
MemberLists m_memberLists
MemberGroupList m_memberGroups
ClassLinkedRefMap classes
ClassLinkedRefMap interfaces
ClassLinkedRefMap structs
ClassLinkedRefMap exceptions
ConceptLinkedRefMap m_concepts
NamespaceLinkedRefMap namespaces
bool m_subGrouping = false
enum NamespaceDefImpl:: { ... } m_type
bool m_isPublished = false
QCString metaData
bool m_inline = false
enum NamespaceDefImpl:: { ... } m_type
Additional Inherited Members
Detailed Description
Definition at line 52 of file namespacedef.cpp.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
NAMESPACE
MODULE
CONSTANT_GROUP
LIBRARY
Definition at line 157 of file namespacedef.cpp.
{ NAMESPACE, MODULE, CONSTANT_GROUP, LIBRARY } m_type;
anonymous enum
anonymous enum [private]
Enumerator
NAMESPACE
MODULE
CONSTANT_GROUP
LIBRARY
Definition at line 157 of file namespacedef.cpp.
{ NAMESPACE, MODULE, CONSTANT_GROUP, LIBRARY } m_type;
Constructor & Destructor Documentation
NamespaceDefImpl() [1/2]
NamespaceDefImpl::NamespaceDefImpl (const QCString & defFileName, int defLine, int defColumn, const QCString & name, const QCString & ref = QCString(), const QCString & refFile = QCString(), const QCString & type = QCString(), bool isPublished = false)
Definition at line 256 of file namespacedef.cpp.
                                             :
   DefinitionMixin(df,dl,dc,name)
  ,m_isPublished(isPublished)
{
  if (!fName.isEmpty())
  {
    if (!lref.isEmpty())
    {
      fileName = stripExtension(fName);
    }
    else
    {
      fileName = convertNameToFile(stripExtension(fName));
    }
  }
  else
  {
    setFileName(name);
  }
  setReference(lref);
  m_inline=FALSE;
  m_subGrouping=Config_getBool(SUBGROUPING);
  if (type=="module")
  {
    m_type = MODULE;
  }
  else if (type=="constants")
  {
    m_type = CONSTANT_GROUP;
  }
  else if (type=="library")
  {
    m_type = LIBRARY;
  }
  else
  {
    m_type = NAMESPACE;
  }
}
References Config_getBool, CONSTANT_GROUP, convertNameToFile(), FALSE, fileName, QCString::isEmpty(), LIBRARY, m_inline, m_subGrouping, m_type, MODULE, DefinitionMixin< NamespaceDefMutable >::name(), NAMESPACE, setFileName(), DefinitionMixin< NamespaceDefMutable >::setReference(), and stripExtension().
 NamespaceDefImpl() [1/2]
NamespaceDefImpl::~NamespaceDefImpl () [virtual]
Definition at line 299 of file namespacedef.cpp.
{
}
NamespaceDefImpl() [2/2]
NamespaceDefImpl::NamespaceDefImpl (const QCString & defFileName, int defLine, int defColumn, const QCString & name, const QCString & ref = QCString(), const QCString & refFile = QCString(), const QCString & type = QCString(), bool isPublished = false)
 NamespaceDefImpl() [2/2]
virtual NamespaceDefImpl::~NamespaceDefImpl () [virtual]
Member Function Documentation
addInnerCompound() [1/2]
void NamespaceDefImpl::addInnerCompound (const Definition * d) [virtual]
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
Definition at line 350 of file namespacedef.cpp.
{
  m_innerCompounds.add(d->localName(),d);
  if (d->definitionType()==Definition::TypeNamespace)
  {
    insertNamespace(toNamespaceDef(d));
  }
  else if (d->definitionType()==Definition::TypeClass)
  {
    insertClass(toClassDef(d));
  }
  else if (d->definitionType()==Definition::TypeConcept)
  {
    insertConcept(toConceptDef(d));
  }
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::definitionType(), insertClass(), insertConcept(), insertNamespace(), Definition::localName(), m_innerCompounds, toClassDef(), toConceptDef(), toNamespaceDef(), Definition::TypeClass, Definition::TypeConcept, and Definition::TypeNamespace.
addInnerCompound() [2/2]
virtual void NamespaceDefImpl::addInnerCompound (const Definition * d) [virtual]
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
addListReferences() [1/2]
void NamespaceDefImpl::addListReferences () [virtual]
Implements NamespaceDefMutable.
Definition at line 1201 of file namespacedef.cpp.
{
  //bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  {
    const RefItemVector &xrefItems = xrefListItems();
    addRefItem(xrefItems,
        qualifiedName(),
        getLanguage()==SrcLangExt_Fortran ?
          theTranslator->trModule(TRUE,TRUE) :
          theTranslator->trNamespace(TRUE,TRUE),
        getOutputFileBase(),displayName(),
        QCString(),
        this
        );
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->addListReferences(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_documentationLists)
    {
      ml->addListReferences(this);
    }
  }
}
References addRefItem(), displayName(), DefinitionMixin< NamespaceDefMutable >::getLanguage(), getOutputFileBase(), m_memberGroups, m_memberLists, MemberListType_documentationLists, DefinitionMixin< NamespaceDefMutable >::qualifiedName(), SrcLangExt_Fortran, theTranslator, Translator::trModule(), Translator::trNamespace(), TRUE, and DefinitionMixin< NamespaceDefMutable >::xrefListItems().
addListReferences() [2/2]
virtual void NamespaceDefImpl::addListReferences () [virtual]
Implements NamespaceDefMutable.
addMembersToMemberGroup() [1/2]
void NamespaceDefImpl::addMembersToMemberGroup () [virtual]
Implements NamespaceDefMutable.
Definition at line 401 of file namespacedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_declarationLists)
    {
      ::addMembersToMemberGroup(ml.get(),&m_memberGroups,this);
    }
  }
  // add members inside sections to their groups
  for (const auto &mg : m_memberGroups)
  {
    if (mg->allMembersInSameSection() && m_subGrouping)
    {
      //printf("----> addToDeclarationSection(%s)\n",qPrint(mg->header()));
      mg->addToDeclarationSection();
    }
  }
}
References addMembersToMemberGroup(), m_memberGroups, m_memberLists, m_subGrouping, and MemberListType_declarationLists.
Referenced by addMembersToMemberGroup().
addMembersToMemberGroup() [2/2]
virtual void NamespaceDefImpl::addMembersToMemberGroup () [virtual]
Implements NamespaceDefMutable.
addMemberToList() [1/2]
void NamespaceDefImpl::addMemberToList (MemberListType lt, MemberDef * md) [private]
Definition at line 1364 of file namespacedef.cpp.
{
  bool sortBriefDocs = Config_getBool(SORT_BRIEF_DOCS);
  bool sortMemberDocs = Config_getBool(SORT_MEMBER_DOCS);
  const auto &ml = m_memberLists.get(lt,MemberListContainer::Namespace);
  ml->setNeedsSorting(
      ((ml->listType()&MemberListType_declarationLists) && sortBriefDocs) ||
      ((ml->listType()&MemberListType_documentationLists) && sortMemberDocs));
  ml->push_back(md);
  if (ml->listType()&MemberListType_declarationLists)
  {
    MemberDefMutable *mdm = toMemberDefMutable(md);
    if (mdm)
    {
      mdm->setSectionList(this,ml.get());
    }
  }
}
References Config_getBool, MemberLists::get(), m_memberLists, MemberListType_declarationLists, MemberListType_documentationLists, Namespace, MemberDefMutable::setSectionList(), and toMemberDefMutable().
Referenced by insertMember().
addMemberToList() [2/2]
void NamespaceDefImpl::addMemberToList (MemberListType lt, MemberDef * md) [private]
addNamespaceAttributes() [1/2]
void NamespaceDefImpl::addNamespaceAttributes (OutputList & ol) [private]
Definition at line 886 of file namespacedef.cpp.
{
  // UNO IDL constant groups may be published
  if (getLanguage()==SrcLangExt_IDL && isConstantGroup() && m_isPublished)
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputGenerator::Html);
    ol.startLabels();
    ol.writeLabel("published",false);
    ol.endLabels();
    ol.popGeneratorState();
  }
}
References OutputList::disableAllBut(), OutputList::endLabels(), DefinitionMixin< NamespaceDefMutable >::getLanguage(), OutputGenerator::Html, isConstantGroup(), m_isPublished, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), SrcLangExt_IDL, OutputList::startLabels(), and OutputList::writeLabel().
Referenced by writeDocumentation().
addNamespaceAttributes() [2/2]
void NamespaceDefImpl::addNamespaceAttributes (OutputList & ol) [private]
addUsingDeclaration() [1/2]
void NamespaceDefImpl::addUsingDeclaration (const ClassDef * cd) [virtual]
Implements NamespaceDefMutable.
Definition at line 1173 of file namespacedef.cpp.
{
  m_usingDeclList.add(cd->qualifiedName(),cd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), m_usingDeclList, and Definition::qualifiedName().
Referenced by combineUsingRelations().
addUsingDeclaration() [2/2]
virtual void NamespaceDefImpl::addUsingDeclaration (const ClassDef * cd) [virtual]
Implements NamespaceDefMutable.
addUsingDirective() [1/2]
void NamespaceDefImpl::addUsingDirective (const NamespaceDef * nd) [virtual]
Implements NamespaceDefMutable.
Definition at line 1167 of file namespacedef.cpp.
{
  m_usingDirList.add(nd->qualifiedName(),nd);
  //printf("%s: NamespaceDefImpl::addUsingDirective: %s:%zu\n",qPrint(name()),qPrint(nd->qualifiedName()),m_usingDirList.size());
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), m_usingDirList, and Definition::qualifiedName().
Referenced by combineUsingRelations().
addUsingDirective() [2/2]
virtual void NamespaceDefImpl::addUsingDirective (const NamespaceDef * nd) [virtual]
Implements NamespaceDefMutable.
anchor() [1/2]
virtual QCString NamespaceDefImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements NamespaceDef.
Definition at line 64 of file namespacedef.cpp.
{ return QCString(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString NamespaceDefImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements NamespaceDef.
Definition at line 64 of file namespacedef.cpp.
{ return QCString(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
codeSymbolType() [1/2]
virtual CodeSymbolType NamespaceDefImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 61 of file namespacedef.cpp.
    { return getLanguage()==SrcLangExt_Java ? CodeSymbolType::Package : CodeSymbolType::Namespace; }
References DefinitionMixin< NamespaceDefMutable >::getLanguage(), Namespace, Package, and SrcLangExt_Java.
codeSymbolType() [2/2]
virtual CodeSymbolType NamespaceDefImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 61 of file namespacedef.cpp.
    { return getLanguage()==SrcLangExt_Java ? CodeSymbolType::Package : CodeSymbolType::Namespace; }
References DefinitionMixin< NamespaceDefMutable >::getLanguage(), Namespace, Package, and SrcLangExt_Java.
combineUsingRelations() [1/2]
void NamespaceDefImpl::combineUsingRelations (NamespaceDefSet & visitedNamespace) [virtual]
Implements NamespaceDefMutable.
Definition at line 1245 of file namespacedef.cpp.
{
  if (visitedNamespaces.find(this)!=visitedNamespaces.end()) return; // already processed
  visitedNamespaces.insert(this);
  LinkedRefMap<const NamespaceDef> usingDirList = m_usingDirList;
  for (auto &nd : usingDirList)
  {
    NamespaceDefMutable *ndm = toNamespaceDefMutable(nd);
    if (ndm)
    {
      ndm->combineUsingRelations(visitedNamespaces);
    }
  }
  for (auto &nd : usingDirList)
  {
    // add used namespaces of namespace nd to this namespace
    for (const auto &und : nd->getUsedNamespaces())
    {
      addUsingDirective(und);
    }
    // add used classes of namespace nd to this namespace
    for (const auto &ucd : nd->getUsedClasses())
    {
      addUsingDeclaration(ucd);
    }
  }
}
References addUsingDeclaration(), addUsingDirective(), NamespaceDefMutable::combineUsingRelations(), m_usingDirList, and toNamespaceDefMutable().
combineUsingRelations() [2/2]
virtual void NamespaceDefImpl::combineUsingRelations (NamespaceDefSet & visitedNamespace) [virtual]
Implements NamespaceDefMutable.
compoundTypeString() [1/2]
QCString NamespaceDefImpl::compoundTypeString () const [virtual]
Implements NamespaceDef.
Definition at line 1490 of file namespacedef.cpp.
{
  SrcLangExt lang = getLanguage();
  if (lang==SrcLangExt_Java)
  {
    return "package";
  }
  else if(lang==SrcLangExt_CSharp)
  {
    return "namespace";
  }
  else if (lang==SrcLangExt_Fortran)
  {
    return "module";
  }
  else if (lang==SrcLangExt_IDL)
  {
    if (isModule())
    {
      return "module";
    }
    else if (isConstantGroup())
    {
      return "constants";
    }
    else if (isLibrary())
    {
      return "library";
    }
    else
    {
      err_full(getDefFileName(),getDefLine(),"Internal inconsistency: namespace in IDL not module, library or constant group");
    }
  }
  return "namespace";
}
References err_full(), DefinitionMixin< NamespaceDefMutable >::getDefFileName(), DefinitionMixin< NamespaceDefMutable >::getDefLine(), DefinitionMixin< NamespaceDefMutable >::getLanguage(), isConstantGroup(), isLibrary(), isModule(), SrcLangExt_CSharp, SrcLangExt_Fortran, SrcLangExt_IDL, and SrcLangExt_Java.
compoundTypeString() [2/2]
virtual QCString NamespaceDefImpl::compoundTypeString () const [virtual]
Implements NamespaceDef.
computeAnchors() [1/2]
void NamespaceDefImpl::computeAnchors () [virtual]
Implements NamespaceDefMutable.
Definition at line 545 of file namespacedef.cpp.
{
  MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
  if (allMemberList) allMemberList->setAnchors();
}
References getMemberList(), MemberListType_allMembersList, and MemberList::setAnchors().
computeAnchors() [2/2]
virtual void NamespaceDefImpl::computeAnchors () [virtual]
Implements NamespaceDefMutable.
countMembers() [1/2]
void NamespaceDefImpl::countMembers () [virtual]
Implements NamespaceDefMutable.
Definition at line 1147 of file namespacedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    ml->countDecMembers();
    ml->countDocMembers();
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->countDecMembers();
    mg->countDocMembers();
  }
}
References m_memberGroups, and m_memberLists.
countMembers() [2/2]
virtual void NamespaceDefImpl::countMembers () [virtual]
Implements NamespaceDefMutable.
definitionType() [1/2]
virtual DefType NamespaceDefImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements NamespaceDef.
Definition at line 60 of file namespacedef.cpp.
{ return TypeNamespace; }
References Definition::TypeNamespace.
definitionType() [2/2]
virtual DefType NamespaceDefImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements NamespaceDef.
Definition at line 60 of file namespacedef.cpp.
{ return TypeNamespace; }
References Definition::TypeNamespace.
displayName() [1/2]
QCString NamespaceDefImpl::displayName (bool includeScope = TRUE) const [virtual]
Returns the name of the definition as it appears in the output
Implements NamespaceDef.
Definition at line 1229 of file namespacedef.cpp.
{
  return makeDisplayName(this,includeScope);
}
References makeDisplayName().
Referenced by addListReferences(), title(), writeDocumentation(), writeMemberDocumentation(), and writeMemberPages().
displayName() [2/2]
virtual QCString NamespaceDefImpl::displayName (bool includeScope = TRUE) const [virtual]
Returns the name of the definition as it appears in the output
Implements NamespaceDef.
distributeMemberGroupDocumentation() [1/2]
void NamespaceDefImpl::distributeMemberGroupDocumentation () [virtual]
Implements NamespaceDefMutable.
Definition at line 315 of file namespacedef.cpp.
{
  for (const auto &mg : m_memberGroups)
  {
    mg->distributeMemberGroupDocumentation();
  }
}
References m_memberGroups.
distributeMemberGroupDocumentation() [2/2]
virtual void NamespaceDefImpl::distributeMemberGroupDocumentation () [virtual]
Implements NamespaceDefMutable.
endMemberDeclarations() [1/2]
void NamespaceDefImpl::endMemberDeclarations (OutputList & ol) [private]
Definition at line 746 of file namespacedef.cpp.
{
  ol.endMemberSections();
}
References OutputList::endMemberSections().
Referenced by writeDocumentation().
endMemberDeclarations() [2/2]
void NamespaceDefImpl::endMemberDeclarations (OutputList & ol) [private]
endMemberDocumentation() [1/2]
void NamespaceDefImpl::endMemberDocumentation (OutputList & ol) [private]
Definition at line 760 of file namespacedef.cpp.
{
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.enable(OutputGenerator::Html);
    Doxygen::suppressDocWarnings = FALSE;
  }
}
References Config_getBool, OutputList::enable(), FALSE, OutputGenerator::Html, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
endMemberDocumentation() [2/2]
void NamespaceDefImpl::endMemberDocumentation (OutputList & ol) [private]
findInnerCompound() [1/2]
const Definition * NamespaceDefImpl::findInnerCompound (const QCString & name) const [virtual]
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
Definition at line 1183 of file namespacedef.cpp.
{
  if (n==0) return 0;
  const Definition *d = m_innerCompounds.find(n);
  if (d==0)
  {
    if (!m_usingDirList.empty())
    {
      d = m_usingDirList.find(n);
    }
    if (d==0 && !m_usingDeclList.empty())
    {
      d = m_usingDeclList.find(n);
    }
  }
  return d;
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::empty(), LinkedRefMap< T, Hash, KeyEqual, Map >::find(), m_innerCompounds, m_usingDeclList, m_usingDirList, and n.
findInnerCompound() [2/2]
virtual const Definition * NamespaceDefImpl::findInnerCompound (const QCString & name) const [virtual]
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
findSectionsInDocumentation() [1/2]
void NamespaceDefImpl::findSectionsInDocumentation () [virtual]
Implements NamespaceDefMutable.
Definition at line 323 of file namespacedef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
  for (const auto &mg : m_memberGroups)
  {
    mg->findSectionsInDocumentation(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_declarationLists)
    {
      ml->findSectionsInDocumentation(this);
    }
  }
}
References DefinitionMixin< NamespaceDefMutable >::briefDescription(), DefinitionMixin< NamespaceDefMutable >::docFile(), docFindSections(), DefinitionMixin< NamespaceDefMutable >::documentation(), m_memberGroups, m_memberLists, and MemberListType_declarationLists.
findSectionsInDocumentation() [2/2]
virtual void NamespaceDefImpl::findSectionsInDocumentation () [virtual]
Implements NamespaceDefMutable.
getClasses() [1/2]
virtual ClassLinkedRefMap NamespaceDefImpl::getClasses () const [inline], [virtual]
Returns the classes contained in this namespace
Implements NamespaceDef.
Definition at line 105 of file namespacedef.cpp.
{ return classes; }
References classes.
getClasses() [2/2]
virtual ClassLinkedRefMap NamespaceDefImpl::getClasses () const [inline], [virtual]
Returns the classes contained in this namespace
Implements NamespaceDef.
Definition at line 105 of file namespacedef.cpp.
{ return classes; }
References classes.
getConcepts() [1/2]
virtual ConceptLinkedRefMap NamespaceDefImpl::getConcepts () const [inline], [virtual]
Returns the concepts contained in this namespace
Implements NamespaceDef.
Definition at line 110 of file namespacedef.cpp.
{ return m_concepts; }
References m_concepts.
getConcepts() [2/2]
virtual ConceptLinkedRefMap NamespaceDefImpl::getConcepts () const [inline], [virtual]
Returns the concepts contained in this namespace
Implements NamespaceDef.
Definition at line 110 of file namespacedef.cpp.
{ return m_concepts; }
References m_concepts.
getExceptions() [1/2]
virtual ClassLinkedRefMap NamespaceDefImpl::getExceptions () const [inline], [virtual]
Returns the Slice exceptions contained in this namespace
Implements NamespaceDef.
Definition at line 108 of file namespacedef.cpp.
{ return exceptions; }
References exceptions.
getExceptions() [2/2]
virtual ClassLinkedRefMap NamespaceDefImpl::getExceptions () const [inline], [virtual]
Returns the Slice exceptions contained in this namespace
Implements NamespaceDef.
Definition at line 108 of file namespacedef.cpp.
{ return exceptions; }
References exceptions.
getInterfaces() [1/2]
virtual ClassLinkedRefMap NamespaceDefImpl::getInterfaces () const [inline], [virtual]
Returns the Slice interfaces contained in this namespace
Implements NamespaceDef.
Definition at line 106 of file namespacedef.cpp.
{ return interfaces; }
References interfaces.
getInterfaces() [2/2]
virtual ClassLinkedRefMap NamespaceDefImpl::getInterfaces () const [inline], [virtual]
Returns the Slice interfaces contained in this namespace
Implements NamespaceDef.
Definition at line 106 of file namespacedef.cpp.
{ return interfaces; }
References interfaces.
getMemberByName() [1/2]
const MemberDef * NamespaceDefImpl::getMemberByName (const QCString & n) const [virtual]
Implements NamespaceDef.
Definition at line 1460 of file namespacedef.cpp.
{
  return m_allMembers.find(n);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), m_allMembers, and n.
getMemberByName() [2/2]
virtual const MemberDef * NamespaceDefImpl::getMemberByName (const QCString &) const [virtual]
Implements NamespaceDef.
getMemberGroups() [1/2]
virtual const MemberGroupList & NamespaceDefImpl::getMemberGroups () const [inline], [virtual]
Returns the user defined member groups
Implements NamespaceDef.
Definition at line 104 of file namespacedef.cpp.
{ return m_memberGroups; }
References m_memberGroups.
getMemberGroups() [2/2]
virtual const MemberGroupList & NamespaceDefImpl::getMemberGroups () const [inline], [virtual]
Returns the user defined member groups
Implements NamespaceDef.
Definition at line 104 of file namespacedef.cpp.
{ return m_memberGroups; }
References m_memberGroups.
getMemberList() [1/2]
MemberList * NamespaceDefImpl::getMemberList (MemberListType lt) const [virtual]
Implements NamespaceDef.
Definition at line 1412 of file namespacedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()==lt)
    {
      return ml.get();
    }
  }
  return 0;
}
References m_memberLists.
Referenced by computeAnchors(), insertMember(), numDocMembers(), writeDocumentation(), writeMemberDeclarations(), writeMemberDocumentation(), writeQuickMemberLinks(), writeSummaryLinks(), and writeTagFile().
getMemberList() [2/2]
virtual MemberList * NamespaceDefImpl::getMemberList (MemberListType lt) const [virtual]
Implements NamespaceDef.
getMemberLists() [1/2]
virtual const MemberLists & NamespaceDefImpl::getMemberLists () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 102 of file namespacedef.cpp.
{ return m_memberLists; }
References m_memberLists.
getMemberLists() [2/2]
virtual const MemberLists & NamespaceDefImpl::getMemberLists () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 102 of file namespacedef.cpp.
{ return m_memberLists; }
References m_memberLists.
getNamespaces() [1/2]
virtual NamespaceLinkedRefMap NamespaceDefImpl::getNamespaces () const [inline], [virtual]
Returns the namespaces contained in this namespace
Implements NamespaceDef.
Definition at line 109 of file namespacedef.cpp.
{ return namespaces; }
References namespaces.
getNamespaces() [2/2]
virtual NamespaceLinkedRefMap NamespaceDefImpl::getNamespaces () const [inline], [virtual]
Returns the namespaces contained in this namespace
Implements NamespaceDef.
Definition at line 109 of file namespacedef.cpp.
{ return namespaces; }
References namespaces.
getOutputFileBase() [1/2]
QCString NamespaceDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements NamespaceDef.
Definition at line 1178 of file namespacedef.cpp.
{
  return fileName;
}
References fileName.
Referenced by addListReferences(), writeBriefDescription(), writeDocumentation(), and writeTagFile().
getOutputFileBase() [2/2]
virtual QCString NamespaceDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements NamespaceDef.
getStructs() [1/2]
virtual ClassLinkedRefMap NamespaceDefImpl::getStructs () const [inline], [virtual]
Returns the Slice structs contained in this namespace
Implements NamespaceDef.
Definition at line 107 of file namespacedef.cpp.
{ return structs; }
References structs.
getStructs() [2/2]
virtual ClassLinkedRefMap NamespaceDefImpl::getStructs () const [inline], [virtual]
Returns the Slice structs contained in this namespace
Implements NamespaceDef.
Definition at line 107 of file namespacedef.cpp.
{ return structs; }
References structs.
getUsedClasses() [1/2]
virtual const LinkedRefMap< const ClassDef > & NamespaceDefImpl::getUsedClasses () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 80 of file namespacedef.cpp.
{ return m_usingDeclList; }
References m_usingDeclList.
getUsedClasses() [2/2]
virtual const LinkedRefMap< const ClassDef > & NamespaceDefImpl::getUsedClasses () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 80 of file namespacedef.cpp.
{ return m_usingDeclList; }
References m_usingDeclList.
getUsedNamespaces() [1/2]
virtual const LinkedRefMap< const NamespaceDef > & NamespaceDefImpl::getUsedNamespaces () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 78 of file namespacedef.cpp.
{ return m_usingDirList; }
References m_usingDirList.
getUsedNamespaces() [2/2]
virtual const LinkedRefMap< const NamespaceDef > & NamespaceDefImpl::getUsedNamespaces () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 78 of file namespacedef.cpp.
{ return m_usingDirList; }
References m_usingDirList.
hasDetailedDescription() [1/2]
bool NamespaceDefImpl::hasDetailedDescription () const [virtual]
Implements NamespaceDef.
Definition at line 551 of file namespacedef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  return ((!briefDescription().isEmpty() && repeatBrief) ||
          !documentation().isEmpty());
}
References DefinitionMixin< NamespaceDefMutable >::briefDescription(), Config_getBool, and DefinitionMixin< NamespaceDefMutable >::documentation().
Referenced by writeBriefDescription(), and writeDetailedDescription().
hasDetailedDescription() [2/2]
virtual bool NamespaceDefImpl::hasDetailedDescription () const [virtual]
Implements NamespaceDef.
insertClass() [1/2]
void NamespaceDefImpl::insertClass (const ClassDef * cd) [virtual]
Implements NamespaceDefMutable.
Definition at line 367 of file namespacedef.cpp.
{
  ClassLinkedRefMap &d = classes;
  if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
  {
    if (cd->compoundType()==ClassDef::Interface)
    {
      d = interfaces;
    }
    else if (cd->compoundType()==ClassDef::Struct)
    {
      d = structs;
    }
    else if (cd->compoundType()==ClassDef::Exception)
    {
      d = exceptions;
    }
  }
  d.add(cd->name(),cd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), classes, ClassDef::compoundType(), Config_getBool, ClassDef::Exception, exceptions, ClassDef::Interface, interfaces, Definition::name(), ClassDef::Struct, and structs.
Referenced by addInnerCompound().
insertClass() [2/2]
virtual void NamespaceDefImpl::insertClass (const ClassDef * cd) [virtual]
Implements NamespaceDefMutable.
insertConcept() [1/2]
void NamespaceDefImpl::insertConcept (const ConceptDef * cd) [virtual]
Implements NamespaceDefMutable.
Definition at line 390 of file namespacedef.cpp.
{
  m_concepts.add(cd->name(),cd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), m_concepts, and Definition::name().
Referenced by addInnerCompound().
insertConcept() [2/2]
virtual void NamespaceDefImpl::insertConcept (const ConceptDef * cd) [virtual]
Implements NamespaceDefMutable.
insertMember() [1/2]
void NamespaceDefImpl::insertMember (MemberDef * md) [virtual]
Implements NamespaceDefMutable.
Definition at line 422 of file namespacedef.cpp.
{
  //printf("%s::insertMember(%s) isInline=%d hasDocs=%d\n",qPrint(name()),qPrint(md->name()),
  // isInline(),hasDocumentation());
  if (md->isHidden()) return;
  MemberDefMutable *mdm = toMemberDefMutable(md);
  // if this is an inline namespace that is not documented, then insert the
  // member in the parent scope instead
  if (isInline() && !hasDocumentation())
  {
    Definition *outerScope = getOuterScope();
    if (outerScope)
    {
      if (outerScope->definitionType()==Definition::TypeNamespace)
      {
        NamespaceDefMutable *nd = toNamespaceDefMutable(outerScope);
        if (nd)
        {
          nd->insertMember(md);
          if (mdm)
          {
            mdm->setNamespace(nd);
          }
        }
      }
      else if (outerScope->definitionType()==Definition::TypeFile)
      {
        FileDef *fd = toFileDef(outerScope);
        fd->insertMember(md);
        if (mdm)
        {
          mdm->setFileDef(fd);
          mdm->setOuterScope(fd);
        }
      }
    }
  }
  else // member is a non-inline namespace or a documented inline namespace
  {
    MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
    if (allMemberList==0)
    {
      m_memberLists.emplace_back(std::make_unique<MemberList>(MemberListType_allMembersList,MemberListContainer::Namespace));
      allMemberList = m_memberLists.back().get();
    }
    allMemberList->push_back(md);
    //printf("%s::m_allMembersDict->append(%s)\n",qPrint(name()),qPrint(md->localName()));
    m_allMembers.add(md->localName(),md);
    //::addNamespaceMemberNameToIndex(md);
    //bool sortBriefDocs=Config_getBool(SORT_BRIEF_DOCS);
    switch(md->memberType())
    {
      case MemberType_Variable:
        addMemberToList(MemberListType_decVarMembers,md);
        addMemberToList(MemberListType_docVarMembers,md);
        break;
      case MemberType_Function:
        addMemberToList(MemberListType_decFuncMembers,md);
        addMemberToList(MemberListType_docFuncMembers,md);
        break;
      case MemberType_Typedef:
        addMemberToList(MemberListType_decTypedefMembers,md);
        addMemberToList(MemberListType_docTypedefMembers,md);
        break;
      case MemberType_Sequence:
        addMemberToList(MemberListType_decSequenceMembers,md);
        addMemberToList(MemberListType_docSequenceMembers,md);
        break;
      case MemberType_Dictionary:
        addMemberToList(MemberListType_decDictionaryMembers,md);
        addMemberToList(MemberListType_docDictionaryMembers,md);
        break;
      case MemberType_Enumeration:
        addMemberToList(MemberListType_decEnumMembers,md);
        addMemberToList(MemberListType_docEnumMembers,md);
        break;
      case MemberType_EnumValue:
        break;
      case MemberType_Define:
        addMemberToList(MemberListType_decDefineMembers,md);
        addMemberToList(MemberListType_docDefineMembers,md);
        break;
      default:
        err("NamespaceDefImpl::insertMembers(): "
            "member '%s' with class scope '%s' inserted in namespace scope '%s'!\n",
            qPrint(md->name()),
            md->getClassDef() ? qPrint(md->getClassDef()->name()) : "",
            qPrint(name()));
    }
    // if this is an inline namespace, then insert an alias of this member in the outer scope.
    if (isInline())
    {
      Definition *outerScope = getOuterScope();
      if (outerScope)
      {
        std::unique_ptr<MemberDef> aliasMd;
        if (outerScope->definitionType()==Definition::TypeNamespace)
        {
          aliasMd.reset(createMemberDefAlias(outerScope,md));
          NamespaceDefMutable *ndm = toNamespaceDefMutable(outerScope);
          if (ndm)
          {
            ndm->insertMember(aliasMd.get());
          }
        }
        else if (outerScope->definitionType()==Definition::TypeFile)
        {
          aliasMd.reset(createMemberDefAlias(outerScope,md));
          toFileDef(outerScope)->insertMember(aliasMd.get());
        }
        if (aliasMd)
        {
          MemberName *mn;
          QCString name = md->name();
          mn = Doxygen::functionNameLinkedMap->add(name);
          mn->push_back(std::move(aliasMd));
        }
      }
    }
  }
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), LinkedRefMap< T, Hash, KeyEqual, Map >::add(), addMemberToList(), createMemberDefAlias(), Definition::definitionType(), err(), Doxygen::functionNameLinkedMap, MemberLists::get(), MemberDef::getClassDef(), getMemberList(), DefinitionMixin< NamespaceDefMutable >::getOuterScope(), DefinitionMixin< NamespaceDefMutable >::hasDocumentation(), FileDef::insertMember(), NamespaceDefMutable::insertMember(), Definition::isHidden(), isInline(), Definition::localName(), m_allMembers, m_memberLists, MemberListType_allMembersList, MemberListType_decDefineMembers, MemberListType_decDictionaryMembers, MemberListType_decEnumMembers, MemberListType_decFuncMembers, MemberListType_decSequenceMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docDictionaryMembers, MemberListType_docEnumMembers, MemberListType_docFuncMembers, MemberListType_docSequenceMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberDef::memberType(), MemberType_Define, MemberType_Dictionary, MemberType_Enumeration, MemberType_EnumValue, MemberType_Function, MemberType_Sequence, MemberType_Typedef, MemberType_Variable, DefinitionMixin< NamespaceDefMutable >::name(), Definition::name(), Namespace, MemberVector::push_back(), MemberName::push_back(), qPrint(), MemberDefMutable::setFileDef(), MemberDefMutable::setNamespace(), DefinitionMutable::setOuterScope(), toFileDef(), toMemberDefMutable(), toNamespaceDefMutable(), Definition::TypeFile, and Definition::TypeNamespace.
insertMember() [2/2]
virtual void NamespaceDefImpl::insertMember (MemberDef * md) [virtual]
Implements NamespaceDefMutable.
insertNamespace() [1/2]
void NamespaceDefImpl::insertNamespace (const NamespaceDef * nd) [virtual]
Implements NamespaceDefMutable.
Definition at line 395 of file namespacedef.cpp.
{
  namespaces.add(nd->name(),nd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::name(), and namespaces.
Referenced by addInnerCompound().
insertNamespace() [2/2]
virtual void NamespaceDefImpl::insertNamespace (const NamespaceDef * nd) [virtual]
Implements NamespaceDefMutable.
insertUsedFile() [1/2]
void NamespaceDefImpl::insertUsedFile (FileDef * fd) [virtual]
Implements NamespaceDefMutable.
Definition at line 340 of file namespacedef.cpp.
{
  if (fd==0) return;
  auto it = std::find(files.begin(),files.end(),fd);
  if (it==files.end())
  {
    files.push_back(fd);
  }
}
References files.
insertUsedFile() [2/2]
virtual void NamespaceDefImpl::insertUsedFile (FileDef * fd) [virtual]
Implements NamespaceDefMutable.
isConstantGroup() [1/2]
virtual bool NamespaceDefImpl::isConstantGroup () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 85 of file namespacedef.cpp.
{ return CONSTANT_GROUP == m_type; }
References CONSTANT_GROUP, and m_type.
Referenced by addNamespaceAttributes(), compoundTypeString(), title(), and writeNamespaceDeclarations().
isConstantGroup() [2/2]
virtual bool NamespaceDefImpl::isConstantGroup () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 85 of file namespacedef.cpp.
{ return CONSTANT_GROUP == m_type; }
References CONSTANT_GROUP, and m_type.
isInline() [1/2]
virtual bool NamespaceDefImpl::isInline () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 88 of file namespacedef.cpp.
{ return m_inline; }
References m_inline.
Referenced by insertMember(), and setInline().
isInline() [2/2]
virtual bool NamespaceDefImpl::isInline () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 88 of file namespacedef.cpp.
{ return m_inline; }
References m_inline.
isLibrary() [1/2]
virtual bool NamespaceDefImpl::isLibrary () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 87 of file namespacedef.cpp.
{ return LIBRARY == m_type; }
References LIBRARY, and m_type.
Referenced by compoundTypeString().
isLibrary() [2/2]
virtual bool NamespaceDefImpl::isLibrary () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 87 of file namespacedef.cpp.
{ return LIBRARY == m_type; }
References LIBRARY, and m_type.
isLinkable() [1/2]
bool NamespaceDefImpl::isLinkable () const [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements NamespaceDef.
Definition at line 1455 of file namespacedef.cpp.
{
  return isLinkableInProject() || isReference();
}
References isLinkableInProject(), and DefinitionMixin< NamespaceDefMutable >::isReference().
isLinkable() [2/2]
virtual bool NamespaceDefImpl::isLinkable () const [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements NamespaceDef.
isLinkableInProject() [1/2]
bool NamespaceDefImpl::isLinkableInProject () const [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements NamespaceDef.
Definition at line 1437 of file namespacedef.cpp.
{
  int i = name().findRev("::");
  if (i==-1) i=0; else i+=2;
  bool extractAnonNs = Config_getBool(EXTRACT_ANON_NSPACES);
  if (extractAnonNs && // extract anonymous ns
      name().mid(i,20)=="anonymous_namespace{" // correct prefix
     ) // not disabled by config
  {
    return TRUE;
  }
  return !name().isEmpty() && name().at(i)!='@' && // not anonymous
    (hasDocumentation() || getLanguage()==SrcLangExt_CSharp) && // documented
    !isReference() && // not an external reference
    !isHidden() && // not hidden
    !isArtificial(); // or artificial
}
References QCString::at(), Config_getBool, QCString::findRev(), DefinitionMixin< NamespaceDefMutable >::getLanguage(), DefinitionMixin< NamespaceDefMutable >::hasDocumentation(), DefinitionMixin< NamespaceDefMutable >::isArtificial(), QCString::isEmpty(), DefinitionMixin< NamespaceDefMutable >::isHidden(), DefinitionMixin< NamespaceDefMutable >::isReference(), DefinitionMixin< NamespaceDefMutable >::name(), SrcLangExt_CSharp, and TRUE.
Referenced by isLinkable().
isLinkableInProject() [2/2]
virtual bool NamespaceDefImpl::isLinkableInProject () const [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements NamespaceDef.
isModule() [1/2]
virtual bool NamespaceDefImpl::isModule () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 86 of file namespacedef.cpp.
{ return NAMESPACE == m_type || MODULE == m_type; }
References m_type, MODULE, and NAMESPACE.
Referenced by compoundTypeString().
isModule() [2/2]
virtual bool NamespaceDefImpl::isModule () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 86 of file namespacedef.cpp.
{ return NAMESPACE == m_type || MODULE == m_type; }
References m_type, MODULE, and NAMESPACE.
localName() [1/2]
QCString NamespaceDefImpl::localName () const [virtual]
Returns the local name without any scope qualifiers.
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
Definition at line 1234 of file namespacedef.cpp.
{
  QCString result=name();
  int i=result.findRev("::");
  if (i!=-1)
  {
    result=result.mid(i+2);
  }
  return result;
}
References QCString::findRev(), QCString::mid(), and DefinitionMixin< NamespaceDefMutable >::name().
localName() [2/2]
virtual QCString NamespaceDefImpl::localName () const [virtual]
Returns the local name without any scope qualifiers.
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
numDocMembers() [1/2]
int NamespaceDefImpl::numDocMembers () const [virtual]
Implements NamespaceDef.
Definition at line 1161 of file namespacedef.cpp.
{
  MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
  return (allMemberList ? allMemberList->numDocMembers() : 0) + static_cast<int>(m_innerCompounds.size());
}
References getMemberList(), m_innerCompounds, MemberListType_allMembersList, MemberList::numDocMembers(), and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
numDocMembers() [2/2]
virtual int NamespaceDefImpl::numDocMembers () const [virtual]
Implements NamespaceDef.
setFileName() [1/2]
void NamespaceDefImpl::setFileName (const QCString & fn) [virtual]
Implements NamespaceDefMutable.
Definition at line 303 of file namespacedef.cpp.
{
  if (isReference())
  {
    fileName = "namespace"+fn;
  }
  else
  {
    fileName = convertNameToFile("namespace"+fn);
  }
}
References convertNameToFile(), fileName, and DefinitionMixin< NamespaceDefMutable >::isReference().
Referenced by NamespaceDefImpl().
setFileName() [2/2]
virtual void NamespaceDefImpl::setFileName (const QCString & fn) [virtual]
Implements NamespaceDefMutable.
setInline() [1/2]
virtual void NamespaceDefImpl::setInline (bool isInline) [inline], [virtual]
Implements NamespaceDefMutable.
Definition at line 84 of file namespacedef.cpp.
{ m_inline = isInline; }
References isInline(), and m_inline.
setInline() [2/2]
virtual void NamespaceDefImpl::setInline (bool isInline) [inline], [virtual]
Implements NamespaceDefMutable.
Definition at line 84 of file namespacedef.cpp.
{ m_inline = isInline; }
References isInline(), and m_inline.
setMetaData() [1/2]
void NamespaceDefImpl::setMetaData (const QCString & m) [virtual]
Implements NamespaceDefMutable.
Definition at line 1527 of file namespacedef.cpp.
{
  metaData = m;
}
References metaData.
setMetaData() [2/2]
virtual void NamespaceDefImpl::setMetaData (const QCString & m) [virtual]
Implements NamespaceDefMutable.
sortMemberLists() [1/2]
void NamespaceDefImpl::sortMemberLists () [virtual]
Implements NamespaceDefMutable.
Definition at line 1384 of file namespacedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->needsSorting()) { ml->sort(); ml->setNeedsSorting(FALSE); }
  }
  auto classComp = [](const ClassLinkedRefMap::Ptr &c1,const ClassLinkedRefMap::Ptr &c2)
  {
    return Config_getBool(SORT_BY_SCOPE_NAME) ?
      qstricmp(c1->name(), c2->name())<0 :
      qstricmp(c1->className(), c2->className())<0;
  };
  std::sort(classes.begin(), classes.end(), classComp);
  std::sort(interfaces.begin(),interfaces.end(),classComp);
  std::sort(structs.begin(), structs.end(), classComp);
  std::sort(exceptions.begin(),exceptions.end(),classComp);
  auto namespaceComp = [](const NamespaceLinkedRefMap::Ptr &n1,const NamespaceLinkedRefMap::Ptr &n2)
  {
    return qstricmp(n1->name(),n2->name())<0;
  };
  std::sort(namespaces.begin(),namespaces.end(),namespaceComp);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::begin(), classes, ClassDef::className(), Config_getBool, LinkedRefMap< T, Hash, KeyEqual, Map >::end(), exceptions, FALSE, interfaces, m_memberLists, Definition::name(), namespaces, qstricmp(), and structs.
sortMemberLists() [2/2]
virtual void NamespaceDefImpl::sortMemberLists () [virtual]
Implements NamespaceDefMutable.
startMemberDeclarations() [1/2]
void NamespaceDefImpl::startMemberDeclarations (OutputList & ol) [private]
Definition at line 741 of file namespacedef.cpp.
{
  ol.startMemberSections();
}
References OutputList::startMemberSections().
Referenced by writeDocumentation().
startMemberDeclarations() [2/2]
void NamespaceDefImpl::startMemberDeclarations (OutputList & ol) [private]
startMemberDocumentation() [1/2]
void NamespaceDefImpl::startMemberDocumentation (OutputList & ol) [private]
Definition at line 751 of file namespacedef.cpp.
{
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.disable(OutputGenerator::Html);
    Doxygen::suppressDocWarnings = TRUE;
  }
}
References Config_getBool, OutputList::disable(), OutputGenerator::Html, Doxygen::suppressDocWarnings, and TRUE.
Referenced by writeDocumentation().
startMemberDocumentation() [2/2]
void NamespaceDefImpl::startMemberDocumentation (OutputList & ol) [private]
subGrouping() [1/2]
virtual bool NamespaceDefImpl::subGrouping () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 100 of file namespacedef.cpp.
{ return m_subGrouping; }
References m_subGrouping.
subGrouping() [2/2]
virtual bool NamespaceDefImpl::subGrouping () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 100 of file namespacedef.cpp.
{ return m_subGrouping; }
References m_subGrouping.
title() [1/2]
QCString NamespaceDefImpl::title () const [virtual]
Implements NamespaceDef.
Definition at line 1465 of file namespacedef.cpp.
{
  SrcLangExt lang = getLanguage();
  QCString pageTitle;
  if (lang==SrcLangExt_Java)
  {
    pageTitle = theTranslator->trPackage(displayName());
  }
  else if (lang==SrcLangExt_Fortran || lang==SrcLangExt_Slice)
  {
    pageTitle = theTranslator->trModuleReference(displayName());
  }
  else if (lang==SrcLangExt_IDL)
  {
    pageTitle = isConstantGroup()
        ? theTranslator->trConstantGroupReference(displayName())
        : theTranslator->trModuleReference(displayName());
  }
  else
  {
    pageTitle = theTranslator->trNamespaceReference(displayName());
  }
  return pageTitle;
}
References displayName(), DefinitionMixin< NamespaceDefMutable >::getLanguage(), isConstantGroup(), SrcLangExt_Fortran, SrcLangExt_IDL, SrcLangExt_Java, SrcLangExt_Slice, theTranslator, Translator::trConstantGroupReference(), Translator::trModuleReference(), Translator::trNamespaceReference(), and Translator::trPackage().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), writeClassDeclarations(), writeConcepts(), writeDetailedDescription(), writeDocumentation(), writeMemberDeclarations(), writeMemberDocumentation(), and writeNamespaceDeclarations().
title() [2/2]
virtual QCString NamespaceDefImpl::title () const [virtual]
Implements NamespaceDef.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
writeAuthorSection() [1/2]
void NamespaceDefImpl::writeAuthorSection (OutputList & ol) [private]
Definition at line 802 of file namespacedef.cpp.
{
  // write Author section (Man only)
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Man);
  ol.startGroupHeader();
  ol.parseText(theTranslator->trAuthor(TRUE,TRUE));
  ol.endGroupHeader();
  ol.parseText(theTranslator->trGeneratedAutomatically(Config_getString(PROJECT_NAME)));
  ol.popGeneratorState();
}
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), and TRUE.
Referenced by writeDocumentation().
writeAuthorSection() [2/2]
void NamespaceDefImpl::writeAuthorSection (OutputList & ol) [private]
writeBriefDescription() [1/2]
void NamespaceDefImpl::writeBriefDescription (OutputList & ol) [private]
Definition at line 681 of file namespacedef.cpp.
{
  if (hasBriefDescription())
  {
    auto parser { createDocParser() };
    auto ast { validatingParseDoc(*parser.get(),
                                     briefFile(),briefLine(),this,0,
                                     briefDescription(),TRUE,FALSE,
                                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startParagraph();
      ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Man);
      ol.writeString(" - ");
      ol.popGeneratorState();
      ol.writeDoc(ast.get(),this,0);
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::RTF);
      ol.writeString(" \n");
      ol.enable(OutputGenerator::RTF);
      if (hasDetailedDescription())
      {
        ol.disableAllBut(OutputGenerator::Html);
        ol.startTextLink(getOutputFileBase(),"details");
        ol.parseText(theTranslator->trMore());
        ol.endTextLink();
      }
      ol.popGeneratorState();
      ol.endParagraph();
    }
    // FIXME:PARA
    //ol.pushGeneratorState();
    //ol.disable(OutputGenerator::RTF);
    //ol.newParagraph();
    //ol.popGeneratorState();
  }
  // Write a summary of the Slice definition including metadata.
  if (getLanguage() == SrcLangExt_Slice)
  {
    ol.startParagraph();
    ol.startTypewriter();
    if (!metaData.isEmpty())
    {
      ol.docify(metaData);
      ol.lineBreak();
    }
    ol.docify("module ");
    ol.docify(stripScope(name()));
    ol.docify(" { ... }");
    ol.endTypewriter();
    ol.endParagraph();
  }
  ol.writeSynopsis();
}
References DefinitionMixin< NamespaceDefMutable >::briefDescription(), DefinitionMixin< NamespaceDefMutable >::briefFile(), DefinitionMixin< NamespaceDefMutable >::briefLine(), Config_getBool, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), OutputList::endTypewriter(), FALSE, DefinitionMixin< NamespaceDefMutable >::getLanguage(), getOutputFileBase(), DefinitionMixin< NamespaceDefMutable >::hasBriefDescription(), hasDetailedDescription(), OutputGenerator::Html, QCString::isEmpty(), OutputList::lineBreak(), OutputGenerator::Man, metaData, DefinitionMixin< NamespaceDefMutable >::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, SrcLangExt_Slice, OutputList::startParagraph(), OutputList::startTextLink(), OutputList::startTypewriter(), stripScope(), theTranslator, Translator::trMore(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeBriefDescription() [2/2]
void NamespaceDefImpl::writeBriefDescription (OutputList & ol) [private]
writeClassDeclarations() [1/2]
void NamespaceDefImpl::writeClassDeclarations (OutputList & ol, const QCString & title, const ClassLinkedRefMap & d) [private]
Definition at line 769 of file namespacedef.cpp.
{
  d.writeDeclaration(ol,0,title,TRUE);
}
References title(), TRUE, and ClassLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeClassDeclarations() [2/2]
void NamespaceDefImpl::writeClassDeclarations (OutputList & ol, const QCString & title, const ClassLinkedRefMap & d) [private]
writeClassesToTagFile() [1/2]
void NamespaceDefImpl::writeClassesToTagFile (TextStream & tagFile, const ClassLinkedRefMap & d) [private]
Definition at line 900 of file namespacedef.cpp.
{
  for (const auto &cd : list)
  {
    if (cd->isLinkableInProject())
    {
      tagFile << " <class kind=\"" << cd->compoundTypeString()
              << "\">" << convertToXML(cd->name()) << "</class>\n";
    }
  }
}
References convertToXML().
Referenced by writeTagFile().
writeClassesToTagFile() [2/2]
void NamespaceDefImpl::writeClassesToTagFile (TextStream & , const ClassLinkedRefMap & d) [private]
writeConcepts() [1/2]
void NamespaceDefImpl::writeConcepts (OutputList & ol, const QCString & title) [private]
Definition at line 774 of file namespacedef.cpp.
{
  m_concepts.writeDeclaration(ol,title,TRUE);
}
References m_concepts, title(), TRUE, and ConceptLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeConcepts() [2/2]
void NamespaceDefImpl::writeConcepts (OutputList & ol, const QCString & title) [private]
writeConceptsToTagFile() [1/2]
void NamespaceDefImpl::writeConceptsToTagFile (TextStream & tagFile) [private]
Definition at line 912 of file namespacedef.cpp.
{
  for (const auto &cd : m_concepts)
  {
    if (cd->isLinkableInProject())
    {
      tagFile << " <concept>" << convertToXML(cd->name()) << "</concept>\n";
    }
  }
}
References convertToXML(), and m_concepts.
Referenced by writeTagFile().
writeConceptsToTagFile() [2/2]
void NamespaceDefImpl::writeConceptsToTagFile (TextStream &) [private]
writeDetailedDescription() [1/2]
void NamespaceDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) [private]
Definition at line 637 of file namespacedef.cpp.
{
  if (hasDetailedDescription())
  {
    ol.pushGeneratorState();
      ol.disable(OutputGenerator::Html);
      ol.writeRuler();
    ol.popGeneratorState();
    ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Html);
      ol.writeAnchor(QCString(),"details");
    ol.popGeneratorState();
    ol.startGroupHeader();
    ol.parseText(title);
    ol.endGroupHeader();
    ol.startTextBlock();
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF))
    {
      ol.generateDoc(briefFile(),briefLine(),this,0,briefDescription(),FALSE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF) &&
        !documentation().isEmpty())
    {
      ol.pushGeneratorState();
        ol.disable(OutputGenerator::Man);
        ol.disable(OutputGenerator::RTF);
        //ol.newParagraph(); // FIXME:PARA
        ol.enableAll();
        ol.disableAllBut(OutputGenerator::Man);
        ol.enable(OutputGenerator::Latex);
        ol.writeString("\n\n");
      ol.popGeneratorState();
    }
    if (!documentation().isEmpty())
    {
      ol.generateDoc(docFile(),docLine(),this,0,documentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    ol.endTextBlock();
  }
}
References DefinitionMixin< NamespaceDefMutable >::briefDescription(), DefinitionMixin< NamespaceDefMutable >::briefFile(), DefinitionMixin< NamespaceDefMutable >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< NamespaceDefMutable >::docFile(), DefinitionMixin< NamespaceDefMutable >::docLine(), DefinitionMixin< NamespaceDefMutable >::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endGroupHeader(), OutputList::endTextBlock(), FALSE, OutputList::generateDoc(), hasDetailedDescription(), OutputGenerator::Html, OutputGenerator::Latex, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startGroupHeader(), OutputList::startTextBlock(), title(), TRUE, OutputList::writeAnchor(), OutputList::writeRuler(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDetailedDescription() [2/2]
void NamespaceDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) [private]
writeDocumentation() [1/2]
void NamespaceDefImpl::writeDocumentation (OutputList & ol) [virtual]
Implements NamespaceDefMutable.
Definition at line 923 of file namespacedef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  //bool outputJava = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
  //bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  QCString pageTitle = title();
  startFile(ol,getOutputFileBase(),name(),pageTitle,HLI_NamespaceVisible,!generateTreeView);
  if (!generateTreeView)
  {
    if (getOuterScope()!=Doxygen::globalScope)
    {
      writeNavigationPath(ol);
    }
    ol.endQuickIndices();
  }
  startTitle(ol,getOutputFileBase(),this);
  ol.parseText(pageTitle);
  addGroupListToTitle(ol,this);
  addNamespaceAttributes(ol);
  endTitle(ol,getOutputFileBase(),displayName());
  ol.startContents();
  //if (Doxygen::searchIndex)
  //{
  // Doxygen::searchIndex->setCurrentDoc(this,anchor(),FALSE);
  // Doxygen::searchIndex->addWord(localName(),TRUE);
  //}
  //Doxygen::indexList->addIndexItem(this,0);
  //---------------------------------------- start flexible part -------------------------------
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Namespace))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
        startMemberDeclarations(ol);
        break;
      case LayoutDocEntry::NamespaceClasses:
        {
          if (ls) writeClassDeclarations(ol,ls->title(lang),classes);
        }
        break;
      case LayoutDocEntry::NamespaceInterfaces:
        {
          if (ls) writeClassDeclarations(ol,ls->title(lang),interfaces);
        }
        break;
      case LayoutDocEntry::NamespaceStructs:
        {
          if (ls) writeClassDeclarations(ol,ls->title(lang),structs);
        }
        break;
      case LayoutDocEntry::NamespaceExceptions:
        {
          if (ls) writeClassDeclarations(ol,ls->title(lang),exceptions);
        }
        break;
      case LayoutDocEntry::NamespaceConcepts:
        {
          if (ls) writeConcepts(ol,ls->title(lang));
        }
        break;
      case LayoutDocEntry::NamespaceNestedNamespaces:
        {
          if (ls) writeNamespaceDeclarations(ol,ls->title(lang),false);
        }
        break;
      case LayoutDocEntry::NamespaceNestedConstantGroups:
        {
          if (ls) writeNamespaceDeclarations(ol,ls->title(lang),true);
        }
        break;
      case LayoutDocEntry::MemberGroups:
        writeMemberGroups(ol);
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd) writeMemberDeclarations(ol,lmd->type,lmd->title(lang));
        }
        break;
      case LayoutDocEntry::MemberDeclEnd:
        endMemberDeclarations(ol);
        break;
      case LayoutDocEntry::DetailedDesc:
        {
          if (ls) writeDetailedDescription(ol,ls->title(lang));
        }
        break;
      case LayoutDocEntry::MemberDefStart:
        startMemberDocumentation(ol);
        break;
      case LayoutDocEntry::NamespaceInlineClasses:
        writeInlineClasses(ol);
        break;
      case LayoutDocEntry::MemberDef:
        {
          const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
          if (lmd) writeMemberDocumentation(ol,lmd->type,lmd->title(lang));
        }
        break;
      case LayoutDocEntry::MemberDefEnd:
        endMemberDocumentation(ol);
        break;
      case LayoutDocEntry::AuthorSection:
        writeAuthorSection(ol);
        break;
      case LayoutDocEntry::ClassIncludes:
      case LayoutDocEntry::ClassInheritanceGraph:
      case LayoutDocEntry::ClassNestedClasses:
      case LayoutDocEntry::ClassCollaborationGraph:
      case LayoutDocEntry::ClassAllMembersLink:
      case LayoutDocEntry::ClassUsedFiles:
      case LayoutDocEntry::ClassInlineClasses:
      case LayoutDocEntry::ConceptDefinition:
      case LayoutDocEntry::FileClasses:
      case LayoutDocEntry::FileConcepts:
      case LayoutDocEntry::FileInterfaces:
      case LayoutDocEntry::FileStructs:
      case LayoutDocEntry::FileExceptions:
      case LayoutDocEntry::FileNamespaces:
      case LayoutDocEntry::FileConstantGroups:
      case LayoutDocEntry::FileIncludes:
      case LayoutDocEntry::FileIncludeGraph:
      case LayoutDocEntry::FileIncludedByGraph:
      case LayoutDocEntry::FileSourceLink:
      case LayoutDocEntry::FileInlineClasses:
      case LayoutDocEntry::GroupClasses:
      case LayoutDocEntry::GroupConcepts:
      case LayoutDocEntry::GroupInlineClasses:
      case LayoutDocEntry::GroupNamespaces:
      case LayoutDocEntry::GroupDirs:
      case LayoutDocEntry::GroupNestedGroups:
      case LayoutDocEntry::GroupFiles:
      case LayoutDocEntry::GroupGraph:
      case LayoutDocEntry::GroupPageDocs:
      case LayoutDocEntry::DirSubDirs:
      case LayoutDocEntry::DirFiles:
      case LayoutDocEntry::DirGraph:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::Namespace entry list\n",lde->kind());
        break;
    }
  }
  //---------------------------------------- end flexible part -------------------------------
  ol.endContents();
  endFileWithNavPath(this,ol);
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
    if (allMemberList) allMemberList->sort();
    writeMemberPages(ol);
  }
}
References addGroupListToTitle(), addNamespaceAttributes(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, classes, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, LayoutDocEntry::ConceptDefinition, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, displayName(), OutputList::endContents(), endFileWithNavPath(), endMemberDeclarations(), endMemberDocumentation(), OutputList::endQuickIndices(), endTitle(), err(), exceptions, LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, LayoutDocEntry::FileStructs, DefinitionMixin< NamespaceDefMutable >::getLanguage(), getMemberList(), DefinitionMixin< NamespaceDefMutable >::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, HLI_NamespaceVisible, LayoutDocManager::instance(), interfaces, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, MemberListType_allMembersList, DefinitionMixin< NamespaceDefMutable >::name(), LayoutDocManager::Namespace, LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, LayoutDocEntry::NamespaceStructs, OutputList::parseText(), MemberVector::sort(), OutputList::startContents(), startFile(), startMemberDeclarations(), startMemberDocumentation(), startTitle(), structs, title(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeClassDeclarations(), writeConcepts(), writeDetailedDescription(), writeInlineClasses(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), writeMemberPages(), writeNamespaceDeclarations(), and DefinitionMixin< NamespaceDefMutable >::writeNavigationPath().
writeDocumentation() [2/2]
virtual void NamespaceDefImpl::writeDocumentation (OutputList & ol) [virtual]
Implements NamespaceDefMutable.
writeInlineClasses() [1/2]
void NamespaceDefImpl::writeInlineClasses (OutputList & ol) [private]
Definition at line 779 of file namespacedef.cpp.
{
  classes.writeDocumentation(ol,this);
}
References classes, and ClassLinkedRefMap::writeDocumentation().
Referenced by writeDocumentation().
writeInlineClasses() [2/2]
void NamespaceDefImpl::writeInlineClasses (OutputList & ol) [private]
writeMemberDeclarations() [1/2]
void NamespaceDefImpl::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title) [private]
Definition at line 1424 of file namespacedef.cpp.
{
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeDeclarations(ol,0,this,0,0,title,QCString());
}
References getMemberList(), title(), and MemberList::writeDeclarations().
Referenced by writeDocumentation().
writeMemberDeclarations() [2/2]
void NamespaceDefImpl::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title) [private]
writeMemberDocumentation() [1/2]
void NamespaceDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title) [private]
Definition at line 1430 of file namespacedef.cpp.
{
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeDocumentation(ol,displayName(),this,title);
}
References displayName(), getMemberList(), title(), and MemberList::writeDocumentation().
Referenced by writeDocumentation().
writeMemberDocumentation() [2/2]
void NamespaceDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title) [private]
writeMemberGroups() [1/2]
void NamespaceDefImpl::writeMemberGroups (OutputList & ol) [private]
Definition at line 790 of file namespacedef.cpp.
{
  /* write user defined member groups */
  for (const auto &mg : m_memberGroups)
  {
    if (!mg->allMembersInSameSection() || !m_subGrouping)
    {
      mg->writeDeclarations(ol,0,this,0,0);
    }
  }
}
References m_memberGroups, and m_subGrouping.
Referenced by writeDocumentation().
writeMemberGroups() [2/2]
void NamespaceDefImpl::writeMemberGroups (OutputList & ol) [private]
writeMemberPages() [1/2]
void NamespaceDefImpl::writeMemberPages (OutputList & ol) [virtual]
Implements NamespaceDefMutable.
Definition at line 1091 of file namespacedef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  for (const auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_documentationLists)
    {
      ml->writeDocumentationPage(ol,displayName(),this);
    }
  }
  ol.popGeneratorState();
}
References OutputList::disableAllBut(), displayName(), OutputGenerator::Html, m_memberLists, MemberListType_documentationLists, OutputList::popGeneratorState(), and OutputList::pushGeneratorState().
Referenced by writeDocumentation().
writeMemberPages() [2/2]
virtual void NamespaceDefImpl::writeMemberPages (OutputList & ol) [virtual]
Implements NamespaceDefMutable.
writeNamespaceDeclarations() [1/2]
void NamespaceDefImpl::writeNamespaceDeclarations (OutputList & ol, const QCString & title, bool isConstantGroup = false) [private]
Definition at line 784 of file namespacedef.cpp.
{
  namespaces.writeDeclaration(ol,title,isConstantGroup,TRUE);
}
References isConstantGroup(), namespaces, title(), TRUE, and NamespaceLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeNamespaceDeclarations() [2/2]
void NamespaceDefImpl::writeNamespaceDeclarations (OutputList & ol, const QCString & title, bool isConstantGroup = false) [private]
writeQuickMemberLinks() [1/2]
void NamespaceDefImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const [virtual]
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
Definition at line 1106 of file namespacedef.cpp.
{
  bool createSubDirs=Config_getBool(CREATE_SUBDIRS);
  ol.writeString(" <div class=\"navtab\">\n");
  ol.writeString(" <table>\n");
  MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
  if (allMemberList)
  {
    for (const auto &md : *allMemberList)
    {
      if (md->getNamespaceDef()==this && md->isLinkable() && !md->isEnumValue())
      {
        if (md->isLinkableInProject())
        {
          if (md==currentMd) // selected item => highlight
          {
            ol.writeString(" <tr><td class=\"navtabHL\">");
          }
          else
          {
            ol.writeString(" <tr><td class=\"navtab\">");
          }
          ol.writeString("<a class=\"navtab\" ");
          ol.writeString("href=\"");
          if (createSubDirs) ol.writeString("../../");
          ol.writeString(addHtmlExtensionIfMissing(md->getOutputFileBase())+"#"+md->anchor());
          ol.writeString("\">");
          ol.writeString(convertToHtml(md->localName()));
          ol.writeString("</a>");
          ol.writeString("</td></tr>\n");
        }
      }
    }
  }
  ol.writeString(" </table>\n");
  ol.writeString(" </div>\n");
}
References addHtmlExtensionIfMissing(), Config_getBool, convertToHtml(), createSubDirs(), getMemberList(), MemberListType_allMembersList, and OutputList::writeString().
writeQuickMemberLinks() [2/2]
virtual void NamespaceDefImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const [virtual]
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
writeSummaryLinks() [1/2]
void NamespaceDefImpl::writeSummaryLinks (OutputList & ol) const [private], [virtual]
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
Definition at line 814 of file namespacedef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  bool first=TRUE;
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Namespace))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    if (lde->kind()==LayoutDocEntry::NamespaceClasses && classes.declVisible() && ls)
    {
      QCString label = "nested-classes";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::NamespaceInterfaces && interfaces.declVisible() && ls)
    {
      QCString label = "interfaces";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::NamespaceStructs && structs.declVisible() && ls)
    {
      QCString label = "structs";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::NamespaceExceptions && exceptions.declVisible() && ls)
    {
      QCString label = "exceptions";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::NamespaceNestedNamespaces && namespaces.declVisible(false) && ls)
    {
      QCString label = "namespaces";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::NamespaceNestedConstantGroups && namespaces.declVisible(true) && ls)
    {
      QCString label = "constantgroups";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::NamespaceConcepts && m_concepts.declVisible() && ls)
    {
      QCString label = "concepts";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()== LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd)
      {
        MemberList * ml = getMemberList(lmd->type);
        if (ml && ml->declVisible())
        {
          ol.writeSummaryLink(QCString(),MemberList::listTypeAsString(ml->listType()),lmd->title(lang),first);
          first=FALSE;
        }
      }
    }
  }
  if (!first)
  {
    ol.writeString(" </div>\n");
  }
  ol.popGeneratorState();
}
References classes, ConceptLinkedRefMap::declVisible(), MemberList::declVisible(), NamespaceLinkedRefMap::declVisible(), ClassLinkedRefMap::declVisible(), OutputList::disableAllBut(), exceptions, FALSE, DefinitionMixin< NamespaceDefMutable >::getLanguage(), getMemberList(), OutputGenerator::Html, LayoutDocManager::instance(), interfaces, MemberList::listType(), MemberList::listTypeAsString(), m_concepts, LayoutDocEntry::MemberDecl, LayoutDocManager::Namespace, LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, namespaces, LayoutDocEntry::NamespaceStructs, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), structs, LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), TRUE, LayoutDocEntryMemberDecl::type, OutputList::writeString(), and OutputList::writeSummaryLink().
writeSummaryLinks() [2/2]
void NamespaceDefImpl::writeSummaryLinks (OutputList & ol) const [private], [virtual]
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
writeTagFile() [1/2]
void NamespaceDefImpl::writeTagFile (TextStream & tagFile) [virtual]
Implements NamespaceDefMutable.
Definition at line 558 of file namespacedef.cpp.
{
  tagFile << " <compound kind=\"namespace\">\n";
  tagFile << " <name>" << convertToXML(name()) << "</name>\n";
  tagFile << " <filename>" << addHtmlExtensionIfMissing(getOutputFileBase()) << "</filename>\n";
  QCString idStr = id();
  if (!idStr.isEmpty())
  {
    tagFile << " <clangid>" << convertToXML(idStr) << "</clangid>\n";
  }
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Namespace))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::NamespaceNestedNamespaces:
        {
          for (const auto &nd : namespaces)
          {
            if (nd->isLinkableInProject())
            {
              tagFile << " <namespace>" << convertToXML(nd->name()) << "</namespace>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::NamespaceClasses:
        {
          writeClassesToTagFile(tagFile, classes);
        }
        break;
      case LayoutDocEntry::NamespaceInterfaces:
        {
          writeClassesToTagFile(tagFile, interfaces);
        }
        break;
      case LayoutDocEntry::NamespaceStructs:
        {
          writeClassesToTagFile(tagFile, structs);
        }
        break;
      case LayoutDocEntry::NamespaceExceptions:
        {
          writeClassesToTagFile(tagFile, exceptions);
        }
        break;
      case LayoutDocEntry::NamespaceConcepts:
        {
          writeConceptsToTagFile(tagFile);
        }
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            MemberList * ml = getMemberList(lmd->type);
            if (ml)
            {
              ml->writeTagFile(tagFile);
            }
          }
        }
        break;
      case LayoutDocEntry::MemberGroups:
        {
          for (const auto &mg : m_memberGroups)
          {
            mg->writeTagFile(tagFile);
          }
        }
        break;
      default:
        break;
    }
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << " </compound>\n";
}
References addHtmlExtensionIfMissing(), classes, convertToXML(), exceptions, getMemberList(), getOutputFileBase(), DefinitionMixin< NamespaceDefMutable >::id(), LayoutDocManager::instance(), interfaces, QCString::isEmpty(), m_memberGroups, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberGroups, DefinitionMixin< NamespaceDefMutable >::name(), LayoutDocManager::Namespace, LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedNamespaces, namespaces, LayoutDocEntry::NamespaceStructs, structs, LayoutDocEntryMemberDecl::type, writeClassesToTagFile(), writeConceptsToTagFile(), DefinitionMixin< NamespaceDefMutable >::writeDocAnchorsToTagFile(), and MemberList::writeTagFile().
writeTagFile() [2/2]
virtual void NamespaceDefImpl::writeTagFile (TextStream &) [virtual]
Implements NamespaceDefMutable.
Member Data Documentation
classes
ClassLinkedRefMap NamespaceDefImpl::classes [private]
Definition at line 150 of file namespacedef.cpp.
Referenced by getClasses(), insertClass(), sortMemberLists(), writeDocumentation(), writeInlineClasses(), writeSummaryLinks(), and writeTagFile().
exceptions
ClassLinkedRefMap NamespaceDefImpl::exceptions [private]
Definition at line 153 of file namespacedef.cpp.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_exceptions(), getExceptions(), doxmlparser.compound.memberdefType::hasContent_(), insertClass(), doxmlparser.compound.memberdefType::set_exceptions(), sortMemberLists(), writeDocumentation(), writeSummaryLinks(), and writeTagFile().
fileName
QCString NamespaceDefImpl::fileName [private]
Definition at line 140 of file namespacedef.cpp.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), getOutputFileBase(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), NamespaceDefImpl(), setFileName(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
files
FileList NamespaceDefImpl::files [private]
Definition at line 141 of file namespacedef.cpp.
Referenced by insertUsedFile().
interfaces
ClassLinkedRefMap NamespaceDefImpl::interfaces [private]
Definition at line 151 of file namespacedef.cpp.
Referenced by getInterfaces(), insertClass(), sortMemberLists(), writeDocumentation(), writeSummaryLinks(), and writeTagFile().
m_allMembers
MemberLinkedRefMap NamespaceDefImpl::m_allMembers [private]
Definition at line 147 of file namespacedef.cpp.
Referenced by getMemberByName(), and insertMember().
m_concepts
ConceptLinkedRefMap NamespaceDefImpl::m_concepts [private]
Definition at line 154 of file namespacedef.cpp.
Referenced by getConcepts(), insertConcept(), writeConcepts(), writeConceptsToTagFile(), and writeSummaryLinks().
m_inline
bool NamespaceDefImpl::m_inline = false [private]
Definition at line 160 of file namespacedef.cpp.
Referenced by isInline(), NamespaceDefImpl(), and setInline().
m_innerCompounds
LinkedRefMap< const Definition > NamespaceDefImpl::m_innerCompounds [private]
Definition at line 145 of file namespacedef.cpp.
Referenced by addInnerCompound(), findInnerCompound(), and numDocMembers().
m_isPublished
bool NamespaceDefImpl::m_isPublished = false [private]
Definition at line 158 of file namespacedef.cpp.
Referenced by addNamespaceAttributes().
m_memberGroups
MemberGroupList NamespaceDefImpl::m_memberGroups [private]
Definition at line 149 of file namespacedef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), countMembers(), distributeMemberGroupDocumentation(), findSectionsInDocumentation(), getMemberGroups(), writeMemberGroups(), and writeTagFile().
m_memberLists
MemberLists NamespaceDefImpl::m_memberLists [private]
Definition at line 148 of file namespacedef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), addMemberToList(), countMembers(), findSectionsInDocumentation(), getMemberList(), getMemberLists(), insertMember(), sortMemberLists(), and writeMemberPages().
m_subGrouping
bool NamespaceDefImpl::m_subGrouping = false [private]
Definition at line 156 of file namespacedef.cpp.
Referenced by addMembersToMemberGroup(), NamespaceDefImpl(), subGrouping(), and writeMemberGroups().
 [1/2]
enum { ... } NamespaceDefImpl::m_type [private]
Referenced by isConstantGroup(), isLibrary(), isModule(), and NamespaceDefImpl().
 [2/2]
enum { ... } NamespaceDefImpl::m_type [private]
m_usingDeclList
LinkedRefMap< const ClassDef > NamespaceDefImpl::m_usingDeclList [private]
Definition at line 144 of file namespacedef.cpp.
Referenced by addUsingDeclaration(), findInnerCompound(), and getUsedClasses().
m_usingDirList
LinkedRefMap< const NamespaceDef > NamespaceDefImpl::m_usingDirList [private]
Definition at line 143 of file namespacedef.cpp.
Referenced by addUsingDirective(), combineUsingRelations(), findInnerCompound(), and getUsedNamespaces().
metaData
QCString NamespaceDefImpl::metaData [private]
Definition at line 159 of file namespacedef.cpp.
Referenced by setMetaData(), and writeBriefDescription().
namespaces
NamespaceLinkedRefMap NamespaceDefImpl::namespaces [private]
Definition at line 155 of file namespacedef.cpp.
Referenced by getNamespaces(), insertNamespace(), sortMemberLists(), writeNamespaceDeclarations(), writeSummaryLinks(), and writeTagFile().
structs
ClassLinkedRefMap NamespaceDefImpl::structs [private]
Definition at line 152 of file namespacedef.cpp.
Referenced by getStructs(), insertClass(), sortMemberLists(), writeDocumentation(), writeSummaryLinks(), and writeTagFile().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/namespacedef.cpp
doxygen/src/namespacedef.cpp