TranslatorAdapter_1_8_19 Class Reference
#include <translator_adapter.h>
Public Member Functions
virtual QCString updateNeededMessage ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString updateNeededMessage ()
virtual QCString trDesignUnitDocumentation ()
Additional Inherited Members
Detailed Description
Definition at line 91 of file translator_adapter.h.
Member Function Documentation
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_8_19::trDesignUnitDocumentation () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 97 of file translator_adapter.h.
    { return english.trDesignUnitDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnitDocumentation().
Referenced by TranslatorArmenian::trClassDocumentation(), TranslatorArabic::trClassDocumentation(), TranslatorCatalan::trClassDocumentation(), TranslatorDanish::trClassDocumentation(), TranslatorEsperanto::trClassDocumentation(), TranslatorSpanish::trClassDocumentation(), TranslatorPersian::trClassDocumentation(), TranslatorFinnish::trClassDocumentation(), TranslatorCroatian::trClassDocumentation(), TranslatorHungarian::trClassDocumentation(), TranslatorIndonesian::trClassDocumentation(), TranslatorJapanese::trClassDocumentation(), TranslatorKorean::trClassDocumentation(), TranslatorLithuanian::trClassDocumentation(), TranslatorLatvian::trClassDocumentation(), TranslatorMacedonian::trClassDocumentation(), TranslatorNorwegian::trClassDocumentation(), TranslatorPolish::trClassDocumentation(), TranslatorRomanian::trClassDocumentation(), TranslatorRussian::trClassDocumentation(), TranslatorSerbianCyrillic::trClassDocumentation(), TranslatorSerbian::trClassDocumentation(), TranslatorTurkish::trClassDocumentation(), TranslatorChinesetraditional::trClassDocumentation(), TranslatorUkrainian::trClassDocumentation(), TranslatorVietnamese::trClassDocumentation(), and TranslatorAfrikaans::trClassDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_8_19::trDesignUnitDocumentation () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 97 of file translator_adapter.h.
    { return english.trDesignUnitDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnitDocumentation().
updateNeededMessage() [1/2]
virtual QCString TranslatorAdapter_1_8_19::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_9_2.
Reimplemented in TranslatorAdapter_1_8_15, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_8_15, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 94 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.8.19"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
updateNeededMessage() [2/2]
virtual QCString TranslatorAdapter_1_8_19::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_9_2.
Reimplemented in TranslatorAdapter_1_8_15, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_8_15, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 94 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.8.19"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_adapter.h
doxygen/src/translator_adapter.h