TemplateNodeRange Class Reference
Class representing a 'range' tag in a template.
Public Member Functions
TemplateNodeRange (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
TemplateNodeRange (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
Private Attributes
bool m_down = false
ExprAstPtr m_startExpr
ExprAstPtr m_endExpr
QCString m_var
TemplateNodeList m_loopNodes
Additional Inherited Members
Detailed Description
Class representing a 'range' tag in a template.
Definition at line 3245 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeRange() [1/2]
TemplateNodeRange::TemplateNodeRange (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3248 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeRange>(parser,parent,line), m_down(FALSE)
    {
      TRACE(("{TemplateNodeRange(%s)\n",qPrint(data)));
      QCString start,end;
      int i1 = data.find(" from ");
      int i2 = data.find(" to ");
      int i3 = data.find(" downto ");
      if (i1==-1)
      {
        if (data.endsWith(" from"))
        {
          parser->warn(m_templateName,line,"range missing after 'from' keyword");
        }
        else if (data=="from")
        {
          parser->warn(m_templateName,line,"range needs an iterator variable and a range");
        }
        else
        {
          parser->warn(m_templateName,line,"range is missing 'from' keyword");
        }
      }
      else if (i2==-1 && i3==-1)
      {
        if (data.endsWith(" to"))
        {
          parser->warn(m_templateName,line,"range is missing end value after 'to' keyword");
        }
        else if (data.endsWith(" downto"))
        {
          parser->warn(m_templateName,line,"range is missing end value after 'downto' keyword");
        }
        else
        {
          parser->warn(m_templateName,line,"range is missing 'to' or 'downto' keyword");
        }
      }
      else
      {
        m_var = data.left(i1).stripWhiteSpace();
        if (m_var.isEmpty())
        {
          parser->warn(m_templateName,line,"range needs an iterator variable");
        }
        start = data.mid(i1+6,i2-i1-6).stripWhiteSpace();
        if (i2!=-1)
        {
          end = data.right(data.length()-i2-4).stripWhiteSpace();
          m_down = FALSE;
        }
        else if (i3!=-1)
        {
          end = data.right(data.length()-i3-8).stripWhiteSpace();
          m_down = TRUE;
        }
      }
      ExpressionParser expParser(parser,line);
      m_startExpr = expParser.parse(start);
      m_endExpr = expParser.parse(end);
      StringVector stopAt = { "endrange" };
      parser->parse(this,line,stopAt,m_loopNodes);
      parser->removeNextToken(); // skip over endrange
      TRACE(("}TemplateNodeRange(%s)\n",qPrint(data)));
    }
References data, ghc::filesystem::end(), FALSE, QCString::isEmpty(), m_down, m_endExpr, m_loopNodes, m_startExpr, TemplateNodeCreator< TemplateNodeRange >::m_templateName, m_var, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), TRACE, TRUE, and TemplateParser::warn().
TemplateNodeRange() [2/2]
TemplateNodeRange::TemplateNodeRange (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3248 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeRange>(parser,parent,line), m_down(FALSE)
    {
      TRACE(("{TemplateNodeRange(%s)\n",qPrint(data)));
      QCString start,end;
      int i1 = data.find(" from ");
      int i2 = data.find(" to ");
      int i3 = data.find(" downto ");
      if (i1==-1)
      {
        if (data.endsWith(" from"))
        {
          parser->warn(m_templateName,line,"range missing after 'from' keyword");
        }
        else if (data=="from")
        {
          parser->warn(m_templateName,line,"range needs an iterator variable and a range");
        }
        else
        {
          parser->warn(m_templateName,line,"range is missing 'from' keyword");
        }
      }
      else if (i2==-1 && i3==-1)
      {
        if (data.endsWith(" to"))
        {
          parser->warn(m_templateName,line,"range is missing end value after 'to' keyword");
        }
        else if (data.endsWith(" downto"))
        {
          parser->warn(m_templateName,line,"range is missing end value after 'downto' keyword");
        }
        else
        {
          parser->warn(m_templateName,line,"range is missing 'to' or 'downto' keyword");
        }
      }
      else
      {
        m_var = data.left(i1).stripWhiteSpace();
        if (m_var.isEmpty())
        {
          parser->warn(m_templateName,line,"range needs an iterator variable");
        }
        start = data.mid(i1+6,i2-i1-6).stripWhiteSpace();
        if (i2!=-1)
        {
          end = data.right(data.length()-i2-4).stripWhiteSpace();
          m_down = FALSE;
        }
        else if (i3!=-1)
        {
          end = data.right(data.length()-i3-8).stripWhiteSpace();
          m_down = TRUE;
        }
      }
      ExpressionParser expParser(parser,line);
      m_startExpr = expParser.parse(start);
      m_endExpr = expParser.parse(end);
      StringVector stopAt = { "endrange" };
      parser->parse(this,line,stopAt,m_loopNodes);
      parser->removeNextToken(); // skip over endrange
      TRACE(("}TemplateNodeRange(%s)\n",qPrint(data)));
    }
References data, ghc::filesystem::end(), FALSE, QCString::isEmpty(), m_down, m_endExpr, m_loopNodes, m_startExpr, TemplateNodeCreator< TemplateNodeRange >::m_templateName, m_var, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), TRACE, TRUE, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeRange::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3315 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      //printf("TemplateNodeRange::render #loopNodes=%d\n",
      // m_loopNodes.count());
      if (m_startExpr && m_endExpr)
      {
        TemplateVariant vs = m_startExpr->resolve(c);
        TemplateVariant ve = m_endExpr->resolve(c);
        if (vs.isInt() && ve.isInt())
        {
          size_t s = vs.toInt();
          size_t e = ve.toInt();
          size_t l = m_down ? s-e+1 : e-s+1;
          if (l>0)
          {
            c->push();
            //int index = m_reversed ? list.count() : 0;
            const TemplateVariant *parentLoop = c->getRef("forloop");
            size_t index = 0;
            size_t i = m_down ? e : s;
            bool done=false;
            while (!done)
            {
              // set the forloop meta-data variable
              TemplateStructPtr ls = TemplateStruct::alloc();
              ls->set("counter0", index);
              ls->set("counter", (index+1));
              ls->set("revcounter", (l-index));
              ls->set("revcounter0", (l-index-1));
              ls->set("first", index==0);
              ls->set("last", index==l-1);
              ls->set("parentloop",parentLoop ? *parentLoop : TemplateVariant());
              c->set("forloop",std::static_pointer_cast<TemplateStructIntf>(ls));
              // set the iterator variable
              c->set(m_var,i);
              // render all items for this iteration of the loop
              m_loopNodes.render(ts,c);
              index++;
              if (m_down)
              {
                i--;
                done = i<e;
              }
              else
              {
                i++;
                done = i>e;
              }
            }
            c->pop();
          }
          else
          {
            ci->warn(m_templateName,m_line,"range %d %s %d is empty!",
                s,m_down?"downto":"to",e);
          }
        }
        else if (!vs.isInt())
        {
          ci->warn(m_templateName,m_line,"range requires a start value of integer type!");
        }
        else if (!ve.isInt())
        {
          ci->warn(m_templateName,m_line,"range requires an end value of integer type!");
        }
      }
      else if (!m_startExpr)
      {
        ci->warn(m_templateName,m_line,"range has empty start value");
      }
      else if (!m_endExpr)
      {
        ci->warn(m_templateName,m_line,"range has empty end value");
      }
    }
References TemplateStruct::alloc(), c, e, TemplateVariant::isInt(), m_down, m_endExpr, TemplateNodeCreator< TemplateNodeRange >::m_line, m_loopNodes, m_startExpr, TemplateNodeCreator< TemplateNodeRange >::m_templateName, m_var, TemplateNodeList::render(), s, TemplateContextImpl::setLocation(), TemplateVariant::toInt(), and TemplateContextImpl::warn().
render() [2/2]
void TemplateNodeRange::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3315 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      //printf("TemplateNodeRange::render #loopNodes=%d\n",
      // m_loopNodes.count());
      if (m_startExpr && m_endExpr)
      {
        TemplateVariant vs = m_startExpr->resolve(c);
        TemplateVariant ve = m_endExpr->resolve(c);
        if (vs.isInt() && ve.isInt())
        {
          size_t s = vs.toInt();
          size_t e = ve.toInt();
          size_t l = m_down ? s-e+1 : e-s+1;
          if (l>0)
          {
            c->push();
            //int index = m_reversed ? list.count() : 0;
            const TemplateVariant *parentLoop = c->getRef("forloop");
            size_t index = 0;
            size_t i = m_down ? e : s;
            bool done=false;
            while (!done)
            {
              // set the forloop meta-data variable
              TemplateStructPtr ls = TemplateStruct::alloc();
              ls->set("counter0", index);
              ls->set("counter", (index+1));
              ls->set("revcounter", (l-index));
              ls->set("revcounter0", (l-index-1));
              ls->set("first", index==0);
              ls->set("last", index==l-1);
              ls->set("parentloop",parentLoop ? *parentLoop : TemplateVariant());
              c->set("forloop",std::static_pointer_cast<TemplateStructIntf>(ls));
              // set the iterator variable
              c->set(m_var,i);
              // render all items for this iteration of the loop
              m_loopNodes.render(ts,c);
              index++;
              if (m_down)
              {
                i--;
                done = i<e;
              }
              else
              {
                i++;
                done = i>e;
              }
            }
            c->pop();
          }
          else
          {
            ci->warn(m_templateName,m_line,"range %d %s %d is empty!",
                s,m_down?"downto":"to",e);
          }
        }
        else if (!vs.isInt())
        {
          ci->warn(m_templateName,m_line,"range requires a start value of integer type!");
        }
        else if (!ve.isInt())
        {
          ci->warn(m_templateName,m_line,"range requires an end value of integer type!");
        }
      }
      else if (!m_startExpr)
      {
        ci->warn(m_templateName,m_line,"range has empty start value");
      }
      else if (!m_endExpr)
      {
        ci->warn(m_templateName,m_line,"range has empty end value");
      }
    }
References TemplateStruct::alloc(), c, e, TemplateVariant::isInt(), m_down, m_endExpr, TemplateNodeCreator< TemplateNodeRange >::m_line, m_loopNodes, m_startExpr, TemplateNodeCreator< TemplateNodeRange >::m_templateName, m_var, TemplateNodeList::render(), s, TemplateContextImpl::setLocation(), TemplateVariant::toInt(), and TemplateContextImpl::warn().
Member Data Documentation
m_down
bool TemplateNodeRange::m_down = false [private]
Definition at line 3398 of file template.cpp.
Referenced by render(), and TemplateNodeRange().
m_endExpr
ExprAstPtr TemplateNodeRange::m_endExpr [private]
Definition at line 3400 of file template.cpp.
Referenced by render(), and TemplateNodeRange().
m_loopNodes
TemplateNodeList TemplateNodeRange::m_loopNodes [private]
Definition at line 3402 of file template.cpp.
Referenced by render(), and TemplateNodeRange().
m_startExpr
ExprAstPtr TemplateNodeRange::m_startExpr [private]
Definition at line 3399 of file template.cpp.
Referenced by render(), and TemplateNodeRange().
m_var
QCString TemplateNodeRange::m_var [private]
Definition at line 3401 of file template.cpp.
Referenced by render(), and TemplateNodeRange().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp