ArgumentListContext::Private Class Reference
Public Member Functions
void addArgument (const Argument &arg, const Definition *def, const QCString &relPath)
void addArgument (const Argument &arg, const Definition *def, const QCString &relPath)
Additional Inherited Members
Detailed Description
Definition at line 8296 of file context.cpp.
Member Function Documentation
addArgument() [1/2]
void ArgumentListContext::Private::addArgument (const Argument & arg, const Definition * def, const QCString & relPath) [inline]
Definition at line 8299 of file context.cpp.
    {
      append(ArgumentContext::alloc(arg,def,relPath));
    }
References ArgumentContext::alloc(), and GenericNodeListContext::append().
addArgument() [2/2]
void ArgumentListContext::Private::addArgument (const Argument & arg, const Definition * def, const QCString & relPath) [inline]
Definition at line 8299 of file context.cpp.
    {
      append(ArgumentContext::alloc(arg,def,relPath));
    }
References ArgumentContext::alloc().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp