HtmlCodeGenerator Class Reference
#include <htmlgen.h>
Public Member Functions
HtmlCodeGenerator (TextStream &t, const QCString &relPath)
HtmlCodeGenerator (TextStream &t)
int id () const
void setId (int id)
void setRelativePath (const QCString &path)
void codify (const QCString &text)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void writeLineNumber (const QCString &, const QCString &, const QCString &, int, bool)
void startCodeLine (bool)
void endCodeLine ()
void startFontClass (const QCString &s)
void endFontClass ()
void writeCodeAnchor (const QCString &anchor)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &)
HtmlCodeGenerator (TextStream &t, const QCString &relPath)
HtmlCodeGenerator (TextStream &t)
int id () const
void setId (int id)
void setRelativePath (const QCString &path)
void codify (const QCString &text)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void writeLineNumber (const QCString &, const QCString &, const QCString &, int, bool)
void startCodeLine (bool)
void endCodeLine ()
void startFontClass (const QCString &s)
void endFontClass ()
void writeCodeAnchor (const QCString &anchor)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &)
Private Member Functions
void _writeCodeLink (const QCString &className, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void docify (const QCString &str)
void _writeCodeLink (const QCString &className, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void docify (const QCString &str)
Private Attributes
TextStream & m_t
int m_col = 0
QCString m_relPath
bool m_lineOpen = false
int m_id = 0
Detailed Description
Definition at line 21 of file htmlgen.h.
Constructor & Destructor Documentation
HtmlCodeGenerator() [1/4]
HtmlCodeGenerator::HtmlCodeGenerator (TextStream & t, const QCString & relPath)
Definition at line 690 of file htmlgen.cpp.
  : m_t(t), m_relPath(relPath)
{
}
HtmlCodeGenerator() [2/4]
HtmlCodeGenerator::HtmlCodeGenerator (TextStream & t)
Definition at line 686 of file htmlgen.cpp.
                                                  : m_t(t)
{
}
HtmlCodeGenerator() [3/4]
HtmlCodeGenerator::HtmlCodeGenerator (TextStream & t, const QCString & relPath)
HtmlCodeGenerator() [4/4]
HtmlCodeGenerator::HtmlCodeGenerator (TextStream & t)
Member Function Documentation
_writeCodeLink() [1/2]
void HtmlCodeGenerator::_writeCodeLink (const QCString & className, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [private]
Definition at line 855 of file htmlgen.cpp.
{
  if (!ref.isEmpty())
  {
    m_t << "<a class=\"" << className << "Ref\" ";
    m_t << externalLinkTarget();
  }
  else
  {
    m_t << "<a class=\"" << className << "\" ";
  }
  m_t << "href=\"";
  m_t << externalRef(m_relPath,ref,TRUE);
  if (!f.isEmpty()) m_t << addHtmlExtensionIfMissing(f);
  if (!anchor.isEmpty()) m_t << "#" << anchor;
  m_t << "\"";
  if (!tooltip.isEmpty()) m_t << " title=\"" << convertToHtml(tooltip) << "\"";
  m_t << ">";
  docify(name);
  m_t << "</a>";
  m_col+=name.length();
}
References addHtmlExtensionIfMissing(), convertToHtml(), docify(), externalLinkTarget(), externalRef(), f, QCString::isEmpty(), m_col, m_relPath, m_t, setup::name, and TRUE.
Referenced by writeCodeLink(), and writeLineNumber().
_writeCodeLink() [2/2]
void HtmlCodeGenerator::_writeCodeLink (const QCString & className, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [private]
codify() [1/2]
void HtmlCodeGenerator::codify (const QCString & s) [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 700 of file htmlgen.cpp.
{
  int tabSize = Config_getInt(TAB_SIZE);
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    int spacesToNextTabStop;
    while (*p)
    {
      c=*p++;
      switch(c)
      {
        case '\t': spacesToNextTabStop =
                         tabSize - (m_col%tabSize);
                   m_t << Doxygen::spaces.left(spacesToNextTabStop);
                   m_col+=spacesToNextTabStop;
                   break;
        case '\n': m_t << "\n"; m_col=0;
                   break;
        case '\r': break;
        case '<': m_t << "&lt;"; m_col++;
                   break;
        case '>': m_t << "&gt;"; m_col++;
                   break;
        case '&': m_t << "&amp;"; m_col++;
                   break;
        case '\'': m_t << "&#39;"; m_col++; // &apos; is not valid XHTML
                   break;
        case '"': m_t << "&quot;"; m_col++;
                   break;
        case '\\':
                   if (*p=='<')
                     { m_t << "&lt;"; p++; }
                   else if (*p=='>')
                     { m_t << "&gt;"; p++; }
           else if (*p=='(')
                     { m_t << "\\&zwj;("; m_col++;p++; }
                   else if (*p==')')
                     { m_t << "\\&zwj;)"; m_col++;p++; }
                   else
                     m_t << "\\";
                   m_col++;
                   break;
        default:
          {
            uchar uc = static_cast<uchar>(c);
            if (uc<32)
            {
              m_t << "&#x24" << hex[uc>>4] << hex[uc&0xF] << ";";
              m_col++;
            }
            else
            {
              p=writeUTF8Char(m_t,p-1);
              m_col++;
            }
          }
          break;
      }
    }
  }
}
References c, Config_getInt, QCString::data(), hex, QCString::isEmpty(), QCString::left(), m_col, m_t, p, Doxygen::spaces, and writeUTF8Char().
Referenced by HtmlGenerator::codify(), and writeLineNumber().
codify() [2/2]
void HtmlCodeGenerator::codify (const QCString & s) [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
docify() [1/2]
void HtmlCodeGenerator::docify (const QCString & str) [private]
Definition at line 764 of file htmlgen.cpp.
{
  //m_t << getHtmlDirEmbeddingChar(getTextDirByConfig(str));
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    while (*p)
    {
      c=*p++;
      switch(c)
      {
        case '<': m_t << "&lt;"; break;
        case '>': m_t << "&gt;"; break;
        case '&': m_t << "&amp;"; break;
        case '"': m_t << "&quot;"; break;
        case '\\':
          if (*p=='<')
            { m_t << "&lt;"; p++; }
          else if (*p=='>')
            { m_t << "&gt;"; p++; }
      else if (*p=='(')
            { m_t << "\\&zwj;("; p++; }
          else if (*p==')')
            { m_t << "\\&zwj;)"; p++; }
          else
            m_t << "\\";
          break;
        default:
          {
            uchar uc = static_cast<uchar>(c);
            if (uc<32 && !isspace(c))
            {
              m_t << "&#x24" << hex[uc>>4] << hex[uc&0xF] << ";";
            }
            else
            {
              m_t << c;
            }
          }
          break;
      }
    }
  }
}
References c, QCString::data(), hex, QCString::isEmpty(), reg::isspace(), m_t, and p.
Referenced by _writeCodeLink(), and writeTooltip().
docify() [2/2]
void HtmlCodeGenerator::docify (const QCString & str) [private]
endCodeFragment() [1/2]
void HtmlCodeGenerator::endCodeFragment (const QCString & style) [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 1007 of file htmlgen.cpp.
{
  //endCodeLine checks is there is still an open code line, if so closes it.
  endCodeLine();
  m_t << "</div><!-- fragment -->";
}
References endCodeLine(), and m_t.
Referenced by HtmlGenerator::endCodeFragment().
endCodeFragment() [2/2]
void HtmlCodeGenerator::endCodeFragment (const QCString & style) [virtual]
Ends a block of code
Implements CodeOutputInterface.
endCodeLine() [1/2]
void HtmlCodeGenerator::endCodeLine () [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 973 of file htmlgen.cpp.
{
  if (m_col == 0)
  {
    m_t << " ";
    m_col++;
  }
  if (m_lineOpen)
  {
    m_t << "</div>\n";
    m_lineOpen = FALSE;
  }
}
References FALSE, m_col, m_lineOpen, and m_t.
Referenced by endCodeFragment(), and HtmlGenerator::endCodeLine().
endCodeLine() [2/2]
void HtmlCodeGenerator::endCodeLine () [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
endFontClass() [1/2]
void HtmlCodeGenerator::endFontClass () [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 992 of file htmlgen.cpp.
{
  m_t << "</span>";
}
References m_t.
Referenced by HtmlGenerator::endFontClass().
endFontClass() [2/2]
void HtmlCodeGenerator::endFontClass () [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
id() [1/2]
int HtmlCodeGenerator::id () const [inline], [virtual]
Identifier for the output file
Reimplemented from CodeOutputInterface.
Definition at line 26 of file htmlgen.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), doxmlparser.compound.docXRefSectType::set_id(), and setId().
id() [2/2]
int HtmlCodeGenerator::id () const [inline], [virtual]
Identifier for the output file
Reimplemented from CodeOutputInterface.
Definition at line 26 of file htmlgen.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
setId() [1/2]
void HtmlCodeGenerator::setId (int id) [inline]
Definition at line 27 of file htmlgen.h.
{ m_id = id; }
References id(), and m_id.
Referenced by HtmlGenerator::startFile(), and HtmlGenerator::writeDoc().
setId() [2/2]
void HtmlCodeGenerator::setId (int id) [inline]
Definition at line 27 of file htmlgen.h.
{ m_id = id; }
References id(), and m_id.
setRelativePath() [1/2]
void HtmlCodeGenerator::setRelativePath (const QCString & path)
Definition at line 695 of file htmlgen.cpp.
{
  m_relPath = path;
}
References m_relPath.
Referenced by HtmlGenerator::startFile().
setRelativePath() [2/2]
void HtmlCodeGenerator::setRelativePath (const QCString & path)
startCodeFragment() [1/2]
void HtmlCodeGenerator::startCodeFragment (const QCString & style) [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 1002 of file htmlgen.cpp.
{
  m_t << "<div class=\"fragment\">";
}
References m_t.
Referenced by HtmlGenerator::startCodeFragment().
startCodeFragment() [2/2]
void HtmlCodeGenerator::startCodeFragment (const QCString & style) [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
startCodeLine() [1/2]
void HtmlCodeGenerator::startCodeLine (bool) [virtual]
Implements CodeOutputInterface.
Definition at line 963 of file htmlgen.cpp.
{
  m_col=0;
  if (!m_lineOpen)
  {
    m_t << "<div class=\"line\">";
    m_lineOpen = TRUE;
  }
}
References m_col, m_lineOpen, m_t, and TRUE.
Referenced by HtmlGenerator::startCodeLine().
startCodeLine() [2/2]
void HtmlCodeGenerator::startCodeLine (bool) [virtual]
Implements CodeOutputInterface.
startFontClass() [1/2]
void HtmlCodeGenerator::startFontClass (const QCString & clsName) [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 987 of file htmlgen.cpp.
{
  m_t << "<span class=\"" << s << "\">";
}
References m_t, and s.
Referenced by HtmlGenerator::startFontClass().
startFontClass() [2/2]
void HtmlCodeGenerator::startFontClass (const QCString & clsName) [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
writeCodeAnchor() [1/2]
void HtmlCodeGenerator::writeCodeAnchor (const QCString & name) [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 997 of file htmlgen.cpp.
{
  m_t << "<a id=\"" << anchor << "\" name=\"" << anchor << "\"></a>";
}
References m_t.
Referenced by HtmlGenerator::writeCodeAnchor().
writeCodeAnchor() [2/2]
void HtmlCodeGenerator::writeCodeAnchor (const QCString & name) [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
writeCodeLink() [1/2]
void HtmlCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 840 of file htmlgen.cpp.
{
  const char *hl = codeSymbolType2Str(type);
  QCString hlClass = "code";
  if (hl)
  {
    hlClass+=" hl_";
    hlClass+=hl;
  }
  _writeCodeLink(hlClass,ref,f,anchor,name,tooltip);
}
References _writeCodeLink(), codeSymbolType2Str(), f, and setup::name.
Referenced by HtmlGenerator::writeCodeLink().
writeCodeLink() [2/2]
void HtmlCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
writeLineNumber() [1/2]
void HtmlCodeGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 811 of file htmlgen.cpp.
{
  const int maxLineNrStr = 10;
  char lineNumber[maxLineNrStr];
  char lineAnchor[maxLineNrStr];
  qsnprintf(lineNumber,maxLineNrStr,"%5d",l);
  qsnprintf(lineAnchor,maxLineNrStr,"l%05d",l);
  if (!m_lineOpen)
  {
    m_t << "<div class=\"line\">";
    m_lineOpen = TRUE;
  }
  if (writeLineAnchor) m_t << "<a id=\"" << lineAnchor << "\" name=\"" << lineAnchor << "\"></a>";
  m_t << "<span class=\"lineno\">";
  if (!filename.isEmpty())
  {
    _writeCodeLink("line",ref,filename,anchor,lineNumber,QCString());
  }
  else
  {
    codify(lineNumber);
  }
  m_t << "</span>";
  m_col=0;
}
References _writeCodeLink(), codify(), filename, m_col, m_lineOpen, m_t, qsnprintf, and TRUE.
Referenced by HtmlGenerator::writeLineNumber().
writeLineNumber() [2/2]
void HtmlCodeGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
writeTooltip() [1/2]
void HtmlCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 881 of file htmlgen.cpp.
{
  m_t << "<div class=\"ttc\" id=\"" << id << "\">";
  m_t << "<div class=\"ttname\">";
  if (!docInfo.url.isEmpty())
  {
    m_t << "<a href=\"";
    m_t << externalRef(m_relPath,docInfo.ref,TRUE);
    m_t << addHtmlExtensionIfMissing(docInfo.url);
    if (!docInfo.anchor.isEmpty())
    {
      m_t << "#" << docInfo.anchor;
    }
    m_t << "\">";
  }
  docify(docInfo.name);
  if (!docInfo.url.isEmpty())
  {
    m_t << "</a>";
  }
  m_t << "</div>";
  if (!decl.isEmpty())
  {
    m_t << "<div class=\"ttdeci\">";
    docify(decl);
    m_t << "</div>";
  }
  if (!desc.isEmpty())
  {
    m_t << "<div class=\"ttdoc\">";
    docify(desc);
    m_t << "</div>";
  }
  if (!defInfo.file.isEmpty())
  {
    m_t << "<div class=\"ttdef\"><b>Definition:</b> ";
    if (!defInfo.url.isEmpty())
    {
      m_t << "<a href=\"";
      m_t << externalRef(m_relPath,defInfo.ref,TRUE);
      m_t << addHtmlExtensionIfMissing(defInfo.url);
      if (!defInfo.anchor.isEmpty())
      {
        m_t << "#" << defInfo.anchor;
      }
      m_t << "\">";
    }
    m_t << defInfo.file << ":" << defInfo.line;
    if (!defInfo.url.isEmpty())
    {
      m_t << "</a>";
    }
    m_t << "</div>";
  }
  if (!declInfo.file.isEmpty())
  {
    m_t << "<div class=\"ttdecl\"><b>Declaration:</b> ";
    if (!declInfo.url.isEmpty())
    {
      m_t << "<a href=\"";
      m_t << externalRef(m_relPath,declInfo.ref,TRUE);
      m_t << addHtmlExtensionIfMissing(declInfo.url);
      if (!declInfo.anchor.isEmpty())
      {
        m_t << "#" << declInfo.anchor;
      }
      m_t << "\">";
    }
    m_t << declInfo.file << ":" << declInfo.line;
    if (!declInfo.url.isEmpty())
    {
      m_t << "</a>";
    }
    m_t << "</div>";
  }
  m_t << "</div>\n";
}
References addHtmlExtensionIfMissing(), DocLinkInfo::anchor, SourceLinkInfo::anchor, docify(), externalRef(), SourceLinkInfo::file, QCString::isEmpty(), SourceLinkInfo::line, m_relPath, m_t, DocLinkInfo::name, DocLinkInfo::ref, SourceLinkInfo::ref, TRUE, DocLinkInfo::url, and SourceLinkInfo::url.
Referenced by HtmlGenerator::writeTooltip().
writeTooltip() [2/2]
void HtmlCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Member Data Documentation
m_col
int HtmlCodeGenerator::m_col = 0 [private]
Definition at line 57 of file htmlgen.h.
Referenced by _writeCodeLink(), codify(), endCodeLine(), startCodeLine(), and writeLineNumber().
m_id
int HtmlCodeGenerator::m_id = 0 [private]
Definition at line 60 of file htmlgen.h.
Referenced by id(), and setId().
m_lineOpen
bool HtmlCodeGenerator::m_lineOpen = false [private]
Definition at line 59 of file htmlgen.h.
Referenced by endCodeLine(), startCodeLine(), and writeLineNumber().
m_relPath
QCString HtmlCodeGenerator::m_relPath [private]
Definition at line 58 of file htmlgen.h.
Referenced by _writeCodeLink(), setRelativePath(), and writeTooltip().
m_t
TextStream & HtmlCodeGenerator::m_t [private]
Definition at line 56 of file htmlgen.h.
Referenced by _writeCodeLink(), codify(), docify(), endCodeFragment(), endCodeLine(), endFontClass(), startCodeFragment(), startCodeLine(), startFontClass(), writeCodeAnchor(), writeLineNumber(), and writeTooltip().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/htmlgen.h
doxygen/src/htmlgen.h
doxygen/build/doxygen/src/htmlgen.cpp
doxygen/src/htmlgen.cpp