FilterRaw Class Reference
The implementation of the `raw` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `raw` filter.
Definition at line 798 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterRaw::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 801 of file template.cpp.
    {
      if (v.isValid() && (v.isString() || v.isInt()))
      {
        return TemplateVariant(v.toString(),TRUE);
      }
      else
      {
        return v;
      }
    }
References TemplateVariant::isInt(), TemplateVariant::isString(), TemplateVariant::isValid(), TemplateVariant::toString(), and TRUE.
apply() [2/2]
static TemplateVariant FilterRaw::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 801 of file template.cpp.
    {
      if (v.isValid() && (v.isString() || v.isInt()))
      {
        return TemplateVariant(v.toString(),TRUE);
      }
      else
      {
        return v;
      }
    }
References TemplateVariant::isInt(), TemplateVariant::isString(), TemplateVariant::isValid(), TemplateVariant::toString(), and TRUE.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp