ghc::filesystem::filesystem_error Class Reference
#include <filesystem.hpp>
Public Member Functions
filesystem_error (const std::string &what_arg, std::error_code ec)
filesystem_error (const std::string &what_arg, const path &p1, std::error_code ec)
filesystem_error (const std::string &what_arg, const path &p1, const path &p2, std::error_code ec)
const path & path1 () const noexcept
const path & path2 () const noexcept
const char * what () const noexcept override
filesystem_error (const std::string &what_arg, std::error_code ec)
filesystem_error (const std::string &what_arg, const path &p1, std::error_code ec)
filesystem_error (const std::string &what_arg, const path &p1, const path &p2, std::error_code ec)
const path & path1 () const noexcept
const path & path2 () const noexcept
const char * what () const noexcept override
Private Attributes
std::string _what_arg
std::error_code _ec
path _p1
path _p2
Detailed Description
Definition at line 651 of file filesystem.hpp.
Constructor & Destructor Documentation
filesystem_error() [1/6]
GHC_INLINE ghc::filesystem::filesystem_error::filesystem_error (const std::string & what_arg, std::error_code ec)
Definition at line 3480 of file filesystem.hpp.
    : std::system_error(ec, what_arg)
    , _what_arg(what_arg)
    , _ec(ec)
{
}
filesystem_error() [2/6]
GHC_INLINE ghc::filesystem::filesystem_error::filesystem_error (const std::string & what_arg, const path & p1, std::error_code ec)
Definition at line 3487 of file filesystem.hpp.
    : std::system_error(ec, what_arg)
    , _what_arg(what_arg)
    , _ec(ec)
    , _p1(p1)
{
    if (!_p1.empty()) {
        _what_arg += ": '" + _p1.string() + "'";
    }
}
References _p1, _what_arg, ghc::filesystem::path::empty(), and ghc::filesystem::path::string().
filesystem_error() [3/6]
GHC_INLINE ghc::filesystem::filesystem_error::filesystem_error (const std::string & what_arg, const path & p1, const path & p2, std::error_code ec)
Definition at line 3498 of file filesystem.hpp.
    : std::system_error(ec, what_arg)
    , _what_arg(what_arg)
    , _ec(ec)
    , _p1(p1)
    , _p2(p2)
{
    if (!_p1.empty()) {
        _what_arg += ": '" + _p1.string() + "'";
    }
    if (!_p2.empty()) {
        _what_arg += ", '" + _p2.string() + "'";
    }
}
References _p1, _p2, _what_arg, ghc::filesystem::path::empty(), and ghc::filesystem::path::string().
filesystem_error() [4/6]
ghc::filesystem::filesystem_error::filesystem_error (const std::string & what_arg, std::error_code ec)
filesystem_error() [5/6]
ghc::filesystem::filesystem_error::filesystem_error (const std::string & what_arg, const path & p1, std::error_code ec)
filesystem_error() [6/6]
ghc::filesystem::filesystem_error::filesystem_error (const std::string & what_arg, const path & p1, const path & p2, std::error_code ec)
Member Function Documentation
path1() [1/2]
GHC_INLINE const path & ghc::filesystem::filesystem_error::path1 () const [noexcept]
Definition at line 3513 of file filesystem.hpp.
{
    return _p1;
}
References _p1.
path1() [2/2]
const path & ghc::filesystem::filesystem_error::path1 () const [noexcept]
path2() [1/2]
GHC_INLINE const path & ghc::filesystem::filesystem_error::path2 () const [noexcept]
Definition at line 3518 of file filesystem.hpp.
{
    return _p2;
}
References _p2.
path2() [2/2]
const path & ghc::filesystem::filesystem_error::path2 () const [noexcept]
what() [1/2]
GHC_INLINE const char * ghc::filesystem::filesystem_error::what () const [override], [noexcept]
Definition at line 3523 of file filesystem.hpp.
{
    return _what_arg.c_str();
}
References _what_arg.
what() [2/2]
const char * ghc::filesystem::filesystem_error::what () const [override], [noexcept]
Member Data Documentation
_ec
std::error_code ghc::filesystem::filesystem_error::_ec [private]
Definition at line 663 of file filesystem.hpp.
_p1
path ghc::filesystem::filesystem_error::_p1 [private]
Definition at line 664 of file filesystem.hpp.
Referenced by filesystem_error(), and path1().
_p2
path ghc::filesystem::filesystem_error::_p2 [private]
Definition at line 664 of file filesystem.hpp.
Referenced by filesystem_error(), and path2().
_what_arg
std::string ghc::filesystem::filesystem_error::_what_arg [private]
Definition at line 662 of file filesystem.hpp.
Referenced by filesystem_error(), and what().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/filesystem/filesystem.hpp
doxygen/filesystem/filesystem.hpp