FilterIsRelativeURL Class Reference
The implementation of the `isRelativeURL` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `isRelativeURL` filter.
Definition at line 1457 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterIsRelativeURL::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1460 of file template.cpp.
    {
      if (v.isValid() && v.isString())
      {
        QCString s = v.toString();
        if (!s.isEmpty() && s.at(0)=='!') return TRUE;
      }
      return FALSE;
    }
References FALSE, TemplateVariant::isString(), TemplateVariant::isValid(), s, TemplateVariant::toString(), and TRUE.
apply() [2/2]
static TemplateVariant FilterIsRelativeURL::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1460 of file template.cpp.
    {
      if (v.isValid() && v.isString())
      {
        QCString s = v.toString();
        if (!s.isEmpty() && s.at(0)=='!') return TRUE;
      }
      return FALSE;
    }
References FALSE, TemplateVariant::isString(), TemplateVariant::isValid(), s, TemplateVariant::toString(), and TRUE.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp