PrintDocVisitor Class Reference
#include <printdocvisitor.h>
Public Member Functions
PrintDocVisitor ()
void operator() (const DocWord &w)
void operator() (const DocLinkedWord &w)
void operator() (const DocWhiteSpace &w)
void operator() (const DocSymbol &s)
void operator() (const DocEmoji &s)
void operator() (const DocURL &u)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &s)
void operator() (const DocVerbatim &s)
void operator() (const DocAnchor &a)
void operator() (const DocInclude &inc)
void operator() (const DocIncOperator &op)
void operator() (const DocFormula &f)
void operator() (const DocIndexEntry &i)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &cite)
void operator() (const DocSeparator &)
template<class T >
void visitChildren (const T &t)
void operator() (const DocAutoList &l)
void operator() (const DocAutoListItem &li)
void operator() (const DocPara &p)
void operator() (const DocRoot &r)
void operator() (const DocSimpleSect &s)
void operator() (const DocTitle &t)
void operator() (const DocSimpleList &l)
void operator() (const DocSimpleListItem &li)
void operator() (const DocSection &s)
void operator() (const DocHtmlList &s)
void operator() (const DocHtmlListItem &li)
void operator() (const DocHtmlDescList &l)
void operator() (const DocHtmlDescTitle &dt)
void operator() (const DocHtmlDescData &dd)
void operator() (const DocHtmlTable &t)
void operator() (const DocHtmlRow &tr)
void operator() (const DocHtmlCell &c)
void operator() (const DocHtmlCaption &c)
void operator() (const DocInternal &i)
void operator() (const DocHRef &href)
void operator() (const DocHtmlSummary &summary)
void operator() (const DocHtmlDetails &details)
void operator() (const DocHtmlHeader &header)
void operator() (const DocImage &img)
void operator() (const DocDotFile &df)
void operator() (const DocMscFile &df)
void operator() (const DocDiaFile &df)
void operator() (const DocLink &lnk)
void operator() (const DocRef &ref)
void operator() (const DocSecRefItem &ref)
void operator() (const DocSecRefList &rl)
void operator() (const DocParamList &pl)
void operator() (const DocParamSect &ps)
void operator() (const DocXRefItem &x)
void operator() (const DocInternalRef &r)
void operator() (const DocText &t)
void operator() (const DocHtmlBlockQuote &q)
void operator() (const DocVhdlFlow &vf)
void operator() (const DocParBlock &pb)
PrintDocVisitor ()
void operator() (const DocWord &w)
void operator() (const DocLinkedWord &w)
void operator() (const DocWhiteSpace &w)
void operator() (const DocSymbol &s)
void operator() (const DocEmoji &s)
void operator() (const DocURL &u)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &s)
void operator() (const DocVerbatim &s)
void operator() (const DocAnchor &a)
void operator() (const DocInclude &inc)
void operator() (const DocIncOperator &op)
void operator() (const DocFormula &f)
void operator() (const DocIndexEntry &i)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &cite)
void operator() (const DocSeparator &)
template<class T >
void visitChildren (const T &t)
void operator() (const DocAutoList &l)
void operator() (const DocAutoListItem &li)
void operator() (const DocPara &p)
void operator() (const DocRoot &r)
void operator() (const DocSimpleSect &s)
void operator() (const DocTitle &t)
void operator() (const DocSimpleList &l)
void operator() (const DocSimpleListItem &li)
void operator() (const DocSection &s)
void operator() (const DocHtmlList &s)
void operator() (const DocHtmlListItem &li)
void operator() (const DocHtmlDescList &l)
void operator() (const DocHtmlDescTitle &dt)
void operator() (const DocHtmlDescData &dd)
void operator() (const DocHtmlTable &t)
void operator() (const DocHtmlRow &tr)
void operator() (const DocHtmlCell &c)
void operator() (const DocHtmlCaption &c)
void operator() (const DocInternal &i)
void operator() (const DocHRef &href)
void operator() (const DocHtmlSummary &summary)
void operator() (const DocHtmlDetails &details)
void operator() (const DocHtmlHeader &header)
void operator() (const DocImage &img)
void operator() (const DocDotFile &df)
void operator() (const DocMscFile &df)
void operator() (const DocDiaFile &df)
void operator() (const DocLink &lnk)
void operator() (const DocRef &ref)
void operator() (const DocSecRefItem &ref)
void operator() (const DocSecRefList &rl)
void operator() (const DocParamList &pl)
void operator() (const DocParamSect &ps)
void operator() (const DocXRefItem &x)
void operator() (const DocInternalRef &r)
void operator() (const DocText &t)
void operator() (const DocHtmlBlockQuote &q)
void operator() (const DocVhdlFlow &vf)
void operator() (const DocParBlock &pb)
Private Member Functions
void indent ()
void indent_leaf ()
void indent_pre ()
void indent_post ()
void indent ()
void indent_leaf ()
void indent_pre ()
void indent_post ()
Private Attributes
int m_indent
bool m_needsEnter
bool m_insidePre
Detailed Description
Visitor implementation for pretty printing
Definition at line 27 of file printdocvisitor.h.
Constructor & Destructor Documentation
PrintDocVisitor() [1/2]
PrintDocVisitor::PrintDocVisitor () [inline]
Definition at line 30 of file printdocvisitor.h.
: m_indent(0), m_needsEnter(FALSE), m_insidePre(FALSE) {}
PrintDocVisitor() [2/2]
PrintDocVisitor::PrintDocVisitor () [inline]
Definition at line 30 of file printdocvisitor.h.
: m_indent(0), m_needsEnter(FALSE), m_insidePre(FALSE) {}
Member Function Documentation
indent() [1/2]
void PrintDocVisitor::indent () [inline], [private]
Definition at line 714 of file printdocvisitor.h.
    {
      if (m_needsEnter) printf("\n");
      for (int i=0;i<m_indent;i++) printf(".");
      m_needsEnter=FALSE;
    }
References FALSE, m_indent, and m_needsEnter.
Referenced by indent_leaf(), indent_post(), and indent_pre().
indent() [2/2]
void PrintDocVisitor::indent () [inline], [private]
Definition at line 714 of file printdocvisitor.h.
    {
      if (m_needsEnter) printf("\n");
      for (int i=0;i<m_indent;i++) printf(".");
      m_needsEnter=FALSE;
    }
References FALSE, m_indent, and m_needsEnter.
indent_leaf() [1/2]
void PrintDocVisitor::indent_leaf () [inline], [private]
Definition at line 720 of file printdocvisitor.h.
    {
      if (!m_needsEnter) indent();
      m_needsEnter=TRUE;
    }
References indent(), m_needsEnter, and TRUE.
Referenced by operator()().
indent_leaf() [2/2]
void PrintDocVisitor::indent_leaf () [inline], [private]
Definition at line 720 of file printdocvisitor.h.
    {
      if (!m_needsEnter) indent();
      m_needsEnter=TRUE;
    }
References indent(), m_needsEnter, and TRUE.
indent_post() [1/2]
void PrintDocVisitor::indent_post () [inline], [private]
Definition at line 730 of file printdocvisitor.h.
    {
      m_indent--;
      indent();
    }
References indent(), and m_indent.
Referenced by operator()().
indent_post() [2/2]
void PrintDocVisitor::indent_post () [inline], [private]
Definition at line 730 of file printdocvisitor.h.
    {
      m_indent--;
      indent();
    }
References indent(), and m_indent.
indent_pre() [1/2]
void PrintDocVisitor::indent_pre () [inline], [private]
Definition at line 725 of file printdocvisitor.h.
    {
      indent();
      m_indent++;
    }
References indent(), and m_indent.
Referenced by operator()().
indent_pre() [2/2]
void PrintDocVisitor::indent_pre () [inline], [private]
Definition at line 725 of file printdocvisitor.h.
    {
      indent();
      m_indent++;
    }
References indent(), and m_indent.
operator()() [1/114]
void PrintDocVisitor::operator() (const DocAnchor & a) [inline]
Definition at line 189 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<anchor name=\"%s\"/>",qPrint(a.anchor()));
    }
References a, indent_leaf(), and qPrint().
operator()() [2/114]
void PrintDocVisitor::operator() (const DocAnchor & a) [inline]
Definition at line 189 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<anchor name=\"%s\"/>",qPrint(a.anchor()));
    }
References a, indent_leaf(), and qPrint().
operator()() [3/114]
void PrintDocVisitor::operator() (const DocAutoList & l) [inline]
Definition at line 277 of file printdocvisitor.h.
    {
      indent_pre();
      if (l.isEnumList())
      {
        printf("<ol>\n");
      }
      else
      {
        printf("<ul>\n");
      }
      visitChildren(l);
      indent_post();
      if (l.isEnumList())
      {
        printf("</ol>\n");
      }
      else
      {
        printf("</ul>\n");
      }
    }
References indent_post(), indent_pre(), DocAutoList::isEnumList(), and visitChildren().
operator()() [4/114]
void PrintDocVisitor::operator() (const DocAutoList & l) [inline]
Definition at line 277 of file printdocvisitor.h.
    {
      indent_pre();
      if (l.isEnumList())
      {
        printf("<ol>\n");
      }
      else
      {
        printf("<ul>\n");
      }
      visitChildren(l);
      indent_post();
      if (l.isEnumList())
      {
        printf("</ol>\n");
      }
      else
      {
        printf("</ul>\n");
      }
    }
References indent_post(), indent_pre(), DocAutoList::isEnumList(), and visitChildren().
operator()() [5/114]
void PrintDocVisitor::operator() (const DocAutoListItem & li) [inline]
Definition at line 299 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<li>\n");
      visitChildren(li);
      indent_post();
      printf("</li>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [6/114]
void PrintDocVisitor::operator() (const DocAutoListItem & li) [inline]
Definition at line 299 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<li>\n");
      visitChildren(li);
      indent_post();
      printf("</li>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [7/114]
void PrintDocVisitor::operator() (const DocCite & cite) [inline]
Definition at line 252 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<cite ref=\"%s\" file=\"%s\" "
             "anchor=\"%s\" text=\"%s\""
             "/>\n",
             qPrint(cite.ref()),qPrint(cite.file()),qPrint(cite.anchor()),
             qPrint(cite.text()));
    }
References DocCite::anchor(), DocCite::file(), indent_leaf(), qPrint(), DocCite::ref(), and DocCite::text().
operator()() [8/114]
void PrintDocVisitor::operator() (const DocCite & cite) [inline]
Definition at line 252 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<cite ref=\"%s\" file=\"%s\" "
             "anchor=\"%s\" text=\"%s\""
             "/>\n",
             qPrint(cite.ref()),qPrint(cite.file()),qPrint(cite.anchor()),
             qPrint(cite.text()));
    }
References DocCite::anchor(), DocCite::file(), indent_leaf(), qPrint(), DocCite::ref(), and DocCite::text().
operator()() [9/114]
void PrintDocVisitor::operator() (const DocDiaFile & df) [inline]
Definition at line 581 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<diafile src=\"%s\">\n",qPrint(df.name()));
      visitChildren(df);
      indent_post();
      printf("</diafile>\n");
    }
References indent_post(), indent_pre(), DocDiagramFileBase::name(), qPrint(), and visitChildren().
operator()() [10/114]
void PrintDocVisitor::operator() (const DocDiaFile & df) [inline]
Definition at line 581 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<diafile src=\"%s\">\n",qPrint(df.name()));
      visitChildren(df);
      indent_post();
      printf("</diafile>\n");
    }
References indent_post(), indent_pre(), DocDiagramFileBase::name(), qPrint(), and visitChildren().
operator()() [11/114]
void PrintDocVisitor::operator() (const DocDotFile & df) [inline]
Definition at line 565 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<dotfile src=\"%s\">\n",qPrint(df.name()));
      visitChildren(df);
      indent_post();
      printf("</dotfile>\n");
    }
References indent_post(), indent_pre(), DocDiagramFileBase::name(), qPrint(), and visitChildren().
operator()() [12/114]
void PrintDocVisitor::operator() (const DocDotFile & df) [inline]
Definition at line 565 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<dotfile src=\"%s\">\n",qPrint(df.name()));
      visitChildren(df);
      indent_post();
      printf("</dotfile>\n");
    }
References indent_post(), indent_pre(), DocDiagramFileBase::name(), qPrint(), and visitChildren().
operator()() [13/114]
void PrintDocVisitor::operator() (const DocEmoji & s) [inline]
Definition at line 69 of file printdocvisitor.h.
    {
      indent_leaf();
      const char *res = EmojiEntityMapper::instance()->name(s.index());
      if (res)
      {
        printf("%s",res);
      }
      else
      {
        printf("print: non supported emoji found: %s\n",qPrint(s.name()));
      }
    }
References indent_leaf(), EmojiEntityMapper::instance(), EmojiEntityMapper::name(), qPrint(), and s.
operator()() [14/114]
void PrintDocVisitor::operator() (const DocEmoji & s) [inline]
Definition at line 69 of file printdocvisitor.h.
    {
      indent_leaf();
      const char *res = EmojiEntityMapper::instance()->name(s.index());
      if (res)
      {
        printf("%s",res);
      }
      else
      {
        printf("print: non supported emoji found: %s\n",qPrint(s.name()));
      }
    }
References indent_leaf(), EmojiEntityMapper::instance(), EmojiEntityMapper::name(), qPrint(), and s.
operator()() [15/114]
void PrintDocVisitor::operator() (const DocFormula & f) [inline]
Definition at line 237 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<formula name=%s text=%s/>",qPrint(f.name()),qPrint(f.text()));
    }
References f, indent_leaf(), and qPrint().
operator()() [16/114]
void PrintDocVisitor::operator() (const DocFormula & f) [inline]
Definition at line 237 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<formula name=%s text=%s/>",qPrint(f.name()),qPrint(f.text()));
    }
References f, indent_leaf(), and qPrint().
operator()() [17/114]
void PrintDocVisitor::operator() (const DocHorRuler &) [inline]
Definition at line 92 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<hr>");
    }
References indent_leaf().
operator()() [18/114]
void PrintDocVisitor::operator() (const DocHorRuler &) [inline]
Definition at line 92 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<hr>");
    }
References indent_leaf().
operator()() [19/114]
void PrintDocVisitor::operator() (const DocHRef & href) [inline]
Definition at line 501 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<a url=\"%s\">\n",qPrint(href.url()));
      visitChildren(href);
      indent_post();
      printf("</a>\n");
    }
References indent_post(), indent_pre(), qPrint(), DocHRef::url(), and visitChildren().
operator()() [20/114]
void PrintDocVisitor::operator() (const DocHRef & href) [inline]
Definition at line 501 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<a url=\"%s\">\n",qPrint(href.url()));
      visitChildren(href);
      indent_post();
      printf("</a>\n");
    }
References indent_post(), indent_pre(), qPrint(), DocHRef::url(), and visitChildren().
operator()() [21/114]
void PrintDocVisitor::operator() (const DocHtmlBlockQuote & q) [inline]
Definition at line 687 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<blockquote>\n");
      visitChildren(q);
      indent_post();
      printf("</blockquote>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [22/114]
void PrintDocVisitor::operator() (const DocHtmlBlockQuote & q) [inline]
Definition at line 687 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<blockquote>\n");
      visitChildren(q);
      indent_post();
      printf("</blockquote>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [23/114]
void PrintDocVisitor::operator() (const DocHtmlCaption & c) [inline]
Definition at line 485 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<caption>\n");
      visitChildren(c);
      indent_post();
      printf("</caption>\n");
    }
References c, indent_post(), indent_pre(), and visitChildren().
operator()() [24/114]
void PrintDocVisitor::operator() (const DocHtmlCaption & c) [inline]
Definition at line 485 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<caption>\n");
      visitChildren(c);
      indent_post();
      printf("</caption>\n");
    }
References c, indent_post(), indent_pre(), and visitChildren().
operator()() [25/114]
void PrintDocVisitor::operator() (const DocHtmlCell & c) [inline]
Definition at line 477 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<t%c>\n",c.isHeading()?'h':'d');
      visitChildren(c);
      indent_post();
      printf("</t%c>\n",c.isHeading()?'h':'d');
    }
References c, indent_post(), indent_pre(), and visitChildren().
operator()() [26/114]
void PrintDocVisitor::operator() (const DocHtmlCell & c) [inline]
Definition at line 477 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<t%c>\n",c.isHeading()?'h':'d');
      visitChildren(c);
      indent_post();
      printf("</t%c>\n",c.isHeading()?'h':'d');
    }
References c, indent_post(), indent_pre(), and visitChildren().
operator()() [27/114]
void PrintDocVisitor::operator() (const DocHtmlDescData & dd) [inline]
Definition at line 448 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<dd>\n");
      visitChildren(dd);
      indent_post();
      printf("</dd>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [28/114]
void PrintDocVisitor::operator() (const DocHtmlDescData & dd) [inline]
Definition at line 448 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<dd>\n");
      visitChildren(dd);
      indent_post();
      printf("</dd>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [29/114]
void PrintDocVisitor::operator() (const DocHtmlDescList & l) [inline]
Definition at line 432 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<dl>\n");
      visitChildren(l);
      indent_post();
      printf("</dl>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [30/114]
void PrintDocVisitor::operator() (const DocHtmlDescList & l) [inline]
Definition at line 432 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<dl>\n");
      visitChildren(l);
      indent_post();
      printf("</dl>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [31/114]
void PrintDocVisitor::operator() (const DocHtmlDescTitle & dt) [inline]
Definition at line 440 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<dt>\n");
      visitChildren(dt);
      indent_post();
      printf("</dt>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [32/114]
void PrintDocVisitor::operator() (const DocHtmlDescTitle & dt) [inline]
Definition at line 440 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<dt>\n");
      visitChildren(dt);
      indent_post();
      printf("</dt>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [33/114]
void PrintDocVisitor::operator() (const DocHtmlDetails & details) [inline]
Definition at line 522 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<details");
      for (const auto &opt : details.attribs())
      {
        printf(" %s=\"%s\"",qPrint(opt.name),qPrint(opt.value));
      }
      printf(">\n");
      auto summary = details.summary();
      if (summary)
      {
        std::visit(*this,*summary);
      }
      visitChildren(details);
      indent_post();
      printf("</details>\n");
    }
References indent_post(), indent_pre(), qPrint(), and visitChildren().
operator()() [34/114]
void PrintDocVisitor::operator() (const DocHtmlDetails & details) [inline]
Definition at line 522 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<details");
      for (const auto &opt : details.attribs())
      {
        printf(" %s=\"%s\"",qPrint(opt.name),qPrint(opt.value));
      }
      printf(">\n");
      auto summary = details.summary();
      if (summary)
      {
        std::visit(*this,*summary);
      }
      visitChildren(details);
      indent_post();
      printf("</details>\n");
    }
References indent_post(), indent_pre(), qPrint(), and visitChildren().
operator()() [35/114]
void PrintDocVisitor::operator() (const DocHtmlHeader & header) [inline]
Definition at line 540 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<h%d>\n",header.level());
      visitChildren(header);
      indent_post();
      printf("</h%d>\n",header.level());
    }
References indent_post(), indent_pre(), DocHtmlHeader::level(), and visitChildren().
operator()() [36/114]
void PrintDocVisitor::operator() (const DocHtmlHeader & header) [inline]
Definition at line 540 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<h%d>\n",header.level());
      visitChildren(header);
      indent_post();
      printf("</h%d>\n",header.level());
    }
References indent_post(), indent_pre(), DocHtmlHeader::level(), and visitChildren().
operator()() [37/114]
void PrintDocVisitor::operator() (const DocHtmlList & s) [inline]
Definition at line 392 of file printdocvisitor.h.
    {
      indent_pre();
      if (s.type()==DocHtmlList::Ordered)
      {
        printf("<ol");
        for (const auto &opt : s.attribs())
        {
          printf(" %s=\"%s\"",qPrint(opt.name),qPrint(opt.value));
        }
        printf(">\n");
      }
      else
      {
        printf("<ul>\n");
      }
      visitChildren(s);
      indent_post();
      if (s.type()==DocHtmlList::Ordered)
      {
        printf("</ol>\n");
      }
      else
      {
        printf("</ul>\n");
      }
    }
References indent_post(), indent_pre(), DocHtmlList::Ordered, qPrint(), s, and visitChildren().
operator()() [38/114]
void PrintDocVisitor::operator() (const DocHtmlList & s) [inline]
Definition at line 392 of file printdocvisitor.h.
    {
      indent_pre();
      if (s.type()==DocHtmlList::Ordered)
      {
        printf("<ol");
        for (const auto &opt : s.attribs())
        {
          printf(" %s=\"%s\"",qPrint(opt.name),qPrint(opt.value));
        }
        printf(">\n");
      }
      else
      {
        printf("<ul>\n");
      }
      visitChildren(s);
      indent_post();
      if (s.type()==DocHtmlList::Ordered)
      {
        printf("</ol>\n");
      }
      else
      {
        printf("</ul>\n");
      }
    }
References indent_post(), indent_pre(), DocHtmlList::Ordered, qPrint(), s, and visitChildren().
operator()() [39/114]
void PrintDocVisitor::operator() (const DocHtmlListItem & li) [inline]
Definition at line 419 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<li");
      for (const auto &opt : li.attribs())
      {
        printf(" %s=\"%s\"",qPrint(opt.name),qPrint(opt.value));
      }
      printf(">\n");
      visitChildren(li);
      indent_post();
      printf("</li>\n");
    }
References DocHtmlListItem::attribs(), indent_post(), indent_pre(), qPrint(), and visitChildren().
operator()() [40/114]
void PrintDocVisitor::operator() (const DocHtmlListItem & li) [inline]
Definition at line 419 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<li");
      for (const auto &opt : li.attribs())
      {
        printf(" %s=\"%s\"",qPrint(opt.name),qPrint(opt.value));
      }
      printf(">\n");
      visitChildren(li);
      indent_post();
      printf("</li>\n");
    }
References DocHtmlListItem::attribs(), indent_post(), indent_pre(), qPrint(), and visitChildren().
operator()() [41/114]
void PrintDocVisitor::operator() (const DocHtmlRow & tr) [inline]
Definition at line 469 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<tr>\n");
      visitChildren(tr);
      indent_post();
      printf("</tr>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [42/114]
void PrintDocVisitor::operator() (const DocHtmlRow & tr) [inline]
Definition at line 469 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<tr>\n");
      visitChildren(tr);
      indent_post();
      printf("</tr>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [43/114]
void PrintDocVisitor::operator() (const DocHtmlSummary & summary) [inline]
Definition at line 509 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<summary");
      for (const auto &opt : summary.attribs())
      {
        printf(" %s=\"%s\"",qPrint(opt.name),qPrint(opt.value));
      }
      printf(">\n");
      visitChildren(summary);
      indent_post();
      printf("</summary>\n");
    }
References DocHtmlSummary::attribs(), indent_post(), indent_pre(), qPrint(), and visitChildren().
operator()() [44/114]
void PrintDocVisitor::operator() (const DocHtmlSummary & summary) [inline]
Definition at line 509 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<summary");
      for (const auto &opt : summary.attribs())
      {
        printf(" %s=\"%s\"",qPrint(opt.name),qPrint(opt.value));
      }
      printf(">\n");
      visitChildren(summary);
      indent_post();
      printf("</summary>\n");
    }
References DocHtmlSummary::attribs(), indent_post(), indent_pre(), qPrint(), and visitChildren().
operator()() [45/114]
void PrintDocVisitor::operator() (const DocHtmlTable & t) [inline]
Definition at line 456 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<table rows=\"%zu\" cols=\"%zu\">\n",
          t.numRows(),t.numColumns());
      visitChildren(t);
      if (t.caption())
      {
        std::visit(*this, *t.caption());
      }
      indent_post();
      printf("</table>\n");
    }
References DocHtmlTable::caption(), indent_post(), indent_pre(), DocHtmlTable::numColumns(), DocHtmlTable::numRows(), and visitChildren().
operator()() [46/114]
void PrintDocVisitor::operator() (const DocHtmlTable & t) [inline]
Definition at line 456 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<table rows=\"%zu\" cols=\"%zu\">\n",
          t.numRows(),t.numColumns());
      visitChildren(t);
      if (t.caption())
      {
        std::visit(*this, *t.caption());
      }
      indent_post();
      printf("</table>\n");
    }
References DocHtmlTable::caption(), indent_post(), indent_pre(), DocHtmlTable::numColumns(), DocHtmlTable::numRows(), and visitChildren().
operator()() [47/114]
void PrintDocVisitor::operator() (const DocImage & img) [inline]
Definition at line 548 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<image src=\"%s\" type=\"",qPrint(img.name()));
      switch(img.type())
      {
        case DocImage::Html: printf("html"); break;
        case DocImage::Latex: printf("latex"); break;
        case DocImage::Rtf: printf("rtf"); break;
        case DocImage::DocBook: printf("docbook"); break;
        case DocImage::Xml: printf("xml"); break;
      }
      printf("\" %s %s inline=\"%s\">\n",qPrint(img.width()),qPrint(img.height()),img.isInlineImage() ? "yes" : "no");
      visitChildren(img);
      indent_post();
      printf("</image>\n");
    }
References DocImage::DocBook, DocImage::height(), DocImage::Html, indent_post(), indent_pre(), DocImage::isInlineImage(), DocImage::Latex, DocImage::name(), qPrint(), DocImage::Rtf, DocImage::type(), visitChildren(), DocImage::width(), and DocImage::Xml.
operator()() [48/114]
void PrintDocVisitor::operator() (const DocImage & img) [inline]
Definition at line 548 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<image src=\"%s\" type=\"",qPrint(img.name()));
      switch(img.type())
      {
        case DocImage::Html: printf("html"); break;
        case DocImage::Latex: printf("latex"); break;
        case DocImage::Rtf: printf("rtf"); break;
        case DocImage::DocBook: printf("docbook"); break;
        case DocImage::Xml: printf("xml"); break;
      }
      printf("\" %s %s inline=\"%s\">\n",qPrint(img.width()),qPrint(img.height()),img.isInlineImage() ? "yes" : "no");
      visitChildren(img);
      indent_post();
      printf("</image>\n");
    }
References DocImage::DocBook, DocImage::height(), DocImage::Html, indent_post(), indent_pre(), DocImage::isInlineImage(), DocImage::Latex, DocImage::name(), qPrint(), DocImage::Rtf, DocImage::type(), visitChildren(), DocImage::width(), and DocImage::Xml.
operator()() [49/114]
void PrintDocVisitor::operator() (const DocInclude & inc) [inline]
Definition at line 194 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<include file=\"%s\" type=\"",qPrint(inc.file()));
      switch(inc.type())
      {
        case DocInclude::Include: printf("include"); break;
        case DocInclude::IncWithLines: printf("incwithlines"); break;
        case DocInclude::DontInclude: printf("dontinclude"); break;
        case DocInclude::DontIncWithLines: printf("dontinwithlines"); break;
        case DocInclude::HtmlInclude:
               printf("htmlinclude");
               if (inc.isBlock()) printf(" block=\"yes\"");
               break;
        case DocInclude::LatexInclude: printf("latexinclude"); break;
        case DocInclude::RtfInclude: printf("rtfinclude"); break;
        case DocInclude::DocbookInclude: printf("docbookinclude"); break;
        case DocInclude::ManInclude: printf("maninclude"); break;
        case DocInclude::XmlInclude: printf("xmlinclude"); break;
        case DocInclude::VerbInclude: printf("verbinclude"); break;
        case DocInclude::Snippet: printf("snippet"); break;
        case DocInclude::SnipWithLines: printf("snipwithlines"); break;
        case DocInclude::SnippetDoc:
        case DocInclude::IncludeDoc:
          err("Internal inconsistency: found switch SnippetDoc / IncludeDoc in file: %s"
              "Please create a bug report\n",__FILE__);
          break;
      }
      printf("\"/>");
    }
References DocInclude::DocbookInclude, DocInclude::DontInclude, DocInclude::DontIncWithLines, err(), DocInclude::file(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, indent_leaf(), DocInclude::isBlock(), DocInclude::LatexInclude, DocInclude::ManInclude, qPrint(), DocInclude::RtfInclude, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, DocInclude::type(), DocInclude::VerbInclude, and DocInclude::XmlInclude.
operator()() [50/114]
void PrintDocVisitor::operator() (const DocInclude & inc) [inline]
Definition at line 194 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<include file=\"%s\" type=\"",qPrint(inc.file()));
      switch(inc.type())
      {
        case DocInclude::Include: printf("include"); break;
        case DocInclude::IncWithLines: printf("incwithlines"); break;
        case DocInclude::DontInclude: printf("dontinclude"); break;
        case DocInclude::DontIncWithLines: printf("dontinwithlines"); break;
        case DocInclude::HtmlInclude:
               printf("htmlinclude");
               if (inc.isBlock()) printf(" block=\"yes\"");
               break;
        case DocInclude::LatexInclude: printf("latexinclude"); break;
        case DocInclude::RtfInclude: printf("rtfinclude"); break;
        case DocInclude::DocbookInclude: printf("docbookinclude"); break;
        case DocInclude::ManInclude: printf("maninclude"); break;
        case DocInclude::XmlInclude: printf("xmlinclude"); break;
        case DocInclude::VerbInclude: printf("verbinclude"); break;
        case DocInclude::Snippet: printf("snippet"); break;
        case DocInclude::SnipWithLines: printf("snipwithlines"); break;
        case DocInclude::SnippetDoc:
        case DocInclude::IncludeDoc:
          err("Internal inconsistency: found switch SnippetDoc / IncludeDoc in file: %s"
              "Please create a bug report\n",__FILE__);
          break;
      }
      printf("\"/>");
    }
References DocInclude::DocbookInclude, DocInclude::DontInclude, DocInclude::DontIncWithLines, err(), DocInclude::file(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, indent_leaf(), DocInclude::isBlock(), DocInclude::LatexInclude, DocInclude::ManInclude, qPrint(), DocInclude::RtfInclude, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, DocInclude::type(), DocInclude::VerbInclude, and DocInclude::XmlInclude.
operator()() [51/114]
void PrintDocVisitor::operator() (const DocIncOperator & op) [inline]
Definition at line 224 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<incoperator pattern=\"%s\" type=\"",qPrint(op.pattern()));
      switch(op.type())
      {
        case DocIncOperator::Line: printf("line"); break;
        case DocIncOperator::Skip: printf("skip"); break;
        case DocIncOperator::SkipLine: printf("skipline"); break;
        case DocIncOperator::Until: printf("until"); break;
      }
      printf("\"/>");
    }
References indent_leaf(), DocIncOperator::Line, DocIncOperator::pattern(), qPrint(), DocIncOperator::Skip, DocIncOperator::SkipLine, DocIncOperator::type(), and DocIncOperator::Until.
operator()() [52/114]
void PrintDocVisitor::operator() (const DocIncOperator & op) [inline]
Definition at line 224 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<incoperator pattern=\"%s\" type=\"",qPrint(op.pattern()));
      switch(op.type())
      {
        case DocIncOperator::Line: printf("line"); break;
        case DocIncOperator::Skip: printf("skip"); break;
        case DocIncOperator::SkipLine: printf("skipline"); break;
        case DocIncOperator::Until: printf("until"); break;
      }
      printf("\"/>");
    }
References indent_leaf(), DocIncOperator::Line, DocIncOperator::pattern(), qPrint(), DocIncOperator::Skip, DocIncOperator::SkipLine, DocIncOperator::type(), and DocIncOperator::Until.
operator()() [53/114]
void PrintDocVisitor::operator() (const DocIndexEntry & i) [inline]
Definition at line 242 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<indexentry>%s</indexentry\n",qPrint(i.entry()));
    }
References DocIndexEntry::entry(), indent_leaf(), and qPrint().
operator()() [54/114]
void PrintDocVisitor::operator() (const DocIndexEntry & i) [inline]
Definition at line 242 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<indexentry>%s</indexentry\n",qPrint(i.entry()));
    }
References DocIndexEntry::entry(), indent_leaf(), and qPrint().
operator()() [55/114]
void PrintDocVisitor::operator() (const DocInternal & i) [inline]
Definition at line 493 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<internal>\n");
      visitChildren(i);
      indent_post();
      printf("</internal>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [56/114]
void PrintDocVisitor::operator() (const DocInternal & i) [inline]
Definition at line 493 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<internal>\n");
      visitChildren(i);
      indent_post();
      printf("</internal>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [57/114]
void PrintDocVisitor::operator() (const DocInternalRef & r) [inline]
Definition at line 671 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<internalref file=%s anchor=%s>\n",qPrint(r.file()),qPrint(r.anchor()));
      visitChildren(r);
      indent_post();
      printf("</internalref>\n");
    }
References indent_post(), indent_pre(), qPrint(), r, and visitChildren().
operator()() [58/114]
void PrintDocVisitor::operator() (const DocInternalRef & r) [inline]
Definition at line 671 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<internalref file=%s anchor=%s>\n",qPrint(r.file()),qPrint(r.anchor()));
      visitChildren(r);
      indent_post();
      printf("</internalref>\n");
    }
References indent_post(), indent_pre(), qPrint(), r, and visitChildren().
operator()() [59/114]
void PrintDocVisitor::operator() (const DocLineBreak &) [inline]
Definition at line 87 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<br/>");
    }
References indent_leaf().
operator()() [60/114]
void PrintDocVisitor::operator() (const DocLineBreak &) [inline]
Definition at line 87 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<br/>");
    }
References indent_leaf().
operator()() [61/114]
void PrintDocVisitor::operator() (const DocLink & lnk) [inline]
Definition at line 589 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<link ref=\"%s\" file=\"%s\" anchor=\"%s\">\n",
          qPrint(lnk.ref()),qPrint(lnk.file()),qPrint(lnk.anchor()));
      visitChildren(lnk);
      indent_post();
      printf("</link>\n");
    }
References DocLink::anchor(), DocLink::file(), indent_post(), indent_pre(), qPrint(), DocLink::ref(), and visitChildren().
operator()() [62/114]
void PrintDocVisitor::operator() (const DocLink & lnk) [inline]
Definition at line 589 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<link ref=\"%s\" file=\"%s\" anchor=\"%s\">\n",
          qPrint(lnk.ref()),qPrint(lnk.file()),qPrint(lnk.anchor()));
      visitChildren(lnk);
      indent_post();
      printf("</link>\n");
    }
References DocLink::anchor(), DocLink::file(), indent_post(), indent_pre(), qPrint(), DocLink::ref(), and visitChildren().
operator()() [63/114]
void PrintDocVisitor::operator() (const DocLinkedWord & w) [inline]
Definition at line 39 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("%s",qPrint(w.word()));
    }
References indent_leaf(), qPrint(), and w.
operator()() [64/114]
void PrintDocVisitor::operator() (const DocLinkedWord & w) [inline]
Definition at line 39 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("%s",qPrint(w.word()));
    }
References indent_leaf(), qPrint(), and w.
operator()() [65/114]
void PrintDocVisitor::operator() (const DocMscFile & df) [inline]
Definition at line 573 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<mscfile src=\"%s\">\n",qPrint(df.name()));
      visitChildren(df);
      indent_post();
      printf("</mscfile>\n");
    }
References indent_post(), indent_pre(), DocDiagramFileBase::name(), qPrint(), and visitChildren().
operator()() [66/114]
void PrintDocVisitor::operator() (const DocMscFile & df) [inline]
Definition at line 573 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<mscfile src=\"%s\">\n",qPrint(df.name()));
      visitChildren(df);
      indent_post();
      printf("</mscfile>\n");
    }
References indent_post(), indent_pre(), DocDiagramFileBase::name(), qPrint(), and visitChildren().
operator()() [67/114]
void PrintDocVisitor::operator() (const DocPara & p) [inline]
Definition at line 307 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<para>\n");
      visitChildren(p);
      indent_post();
      printf("</para>\n");
    }
References indent_post(), indent_pre(), p, and visitChildren().
operator()() [68/114]
void PrintDocVisitor::operator() (const DocPara & p) [inline]
Definition at line 307 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<para>\n");
      visitChildren(p);
      indent_post();
      printf("</para>\n");
    }
References indent_post(), indent_pre(), p, and visitChildren().
operator()() [69/114]
void PrintDocVisitor::operator() (const DocParamList & pl) [inline]
Definition at line 628 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<parameters>");
      if (!pl.parameters().empty())
      {
        printf("<param>");
        for (const auto &param : pl.parameters())
        {
          std::visit(*this,param);
        }
        printf("</param>");
      }
      printf("\n");
      indent_post();
      printf("</parameters>\n");
    }
References GrowVector< T >::empty(), indent_post(), indent_pre(), and DocParamList::parameters().
operator()() [70/114]
void PrintDocVisitor::operator() (const DocParamList & pl) [inline]
Definition at line 628 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<parameters>");
      if (!pl.parameters().empty())
      {
        printf("<param>");
        for (const auto &param : pl.parameters())
        {
          std::visit(*this,param);
        }
        printf("</param>");
      }
      printf("\n");
      indent_post();
      printf("</parameters>\n");
    }
References GrowVector< T >::empty(), indent_post(), indent_pre(), and DocParamList::parameters().
operator()() [71/114]
void PrintDocVisitor::operator() (const DocParamSect & ps) [inline]
Definition at line 645 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<paramsect type=");
      switch (ps.type())
      {
    case DocParamSect::Param: printf("param"); break;
    case DocParamSect::RetVal: printf("retval"); break;
    case DocParamSect::Exception: printf("exception"); break;
    case DocParamSect::TemplateParam: printf("templateparam"); break;
    case DocParamSect::Unknown: printf("unknown"); break;
      }
      printf(">\n");
      visitChildren(ps);
      indent_post();
      printf("</paramsect>\n");
    }
References DocParamSect::Exception, indent_post(), indent_pre(), DocParamSect::Param, DocParamSect::RetVal, DocParamSect::TemplateParam, DocParamSect::type(), DocParamSect::Unknown, and visitChildren().
operator()() [72/114]
void PrintDocVisitor::operator() (const DocParamSect & ps) [inline]
Definition at line 645 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<paramsect type=");
      switch (ps.type())
      {
    case DocParamSect::Param: printf("param"); break;
    case DocParamSect::RetVal: printf("retval"); break;
    case DocParamSect::Exception: printf("exception"); break;
    case DocParamSect::TemplateParam: printf("templateparam"); break;
    case DocParamSect::Unknown: printf("unknown"); break;
      }
      printf(">\n");
      visitChildren(ps);
      indent_post();
      printf("</paramsect>\n");
    }
References DocParamSect::Exception, indent_post(), indent_pre(), DocParamSect::Param, DocParamSect::RetVal, DocParamSect::TemplateParam, DocParamSect::type(), DocParamSect::Unknown, and visitChildren().
operator()() [73/114]
void PrintDocVisitor::operator() (const DocParBlock & pb) [inline]
Definition at line 703 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<parblock>\n");
      visitChildren(pb);
      indent_post();
      printf("</parblock>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [74/114]
void PrintDocVisitor::operator() (const DocParBlock & pb) [inline]
Definition at line 703 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<parblock>\n");
      visitChildren(pb);
      indent_post();
      printf("</parblock>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [75/114]
void PrintDocVisitor::operator() (const DocRef & ref) [inline]
Definition at line 598 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<ref ref=\"%s\" file=\"%s\" "
             "anchor=\"%s\" targetTitle=\"%s\""
             " hasLinkText=\"%s\" refToAnchor=\"%s\" refToSection=\"%s\" refToTable=\"%s\">\n",
             qPrint(ref.ref()),qPrint(ref.file()),qPrint(ref.anchor()),
             qPrint(ref.targetTitle()),ref.hasLinkText()?"yes":"no",
             ref.refToAnchor()?"yes":"no", ref.refToSection()?"yes":"no",
             ref.refToTable()?"yes":"no");
      visitChildren(ref);
      indent_post();
      printf("</ref>\n");
    }
References DocRef::anchor(), DocRef::file(), DocRef::hasLinkText(), indent_post(), indent_pre(), qPrint(), DocRef::ref(), DocRef::refToAnchor(), DocRef::refToSection(), DocRef::refToTable(), DocRef::targetTitle(), and visitChildren().
operator()() [76/114]
void PrintDocVisitor::operator() (const DocRef & ref) [inline]
Definition at line 598 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<ref ref=\"%s\" file=\"%s\" "
             "anchor=\"%s\" targetTitle=\"%s\""
             " hasLinkText=\"%s\" refToAnchor=\"%s\" refToSection=\"%s\" refToTable=\"%s\">\n",
             qPrint(ref.ref()),qPrint(ref.file()),qPrint(ref.anchor()),
             qPrint(ref.targetTitle()),ref.hasLinkText()?"yes":"no",
             ref.refToAnchor()?"yes":"no", ref.refToSection()?"yes":"no",
             ref.refToTable()?"yes":"no");
      visitChildren(ref);
      indent_post();
      printf("</ref>\n");
    }
References DocRef::anchor(), DocRef::file(), DocRef::hasLinkText(), indent_post(), indent_pre(), qPrint(), DocRef::ref(), DocRef::refToAnchor(), DocRef::refToSection(), DocRef::refToTable(), DocRef::targetTitle(), and visitChildren().
operator()() [77/114]
void PrintDocVisitor::operator() (const DocRoot & r) [inline]
Definition at line 315 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<root>\n");
      visitChildren(r);
      indent_post();
      printf("</root>\n");
    }
References indent_post(), indent_pre(), r, and visitChildren().
operator()() [78/114]
void PrintDocVisitor::operator() (const DocRoot & r) [inline]
Definition at line 315 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<root>\n");
      visitChildren(r);
      indent_post();
      printf("</root>\n");
    }
References indent_post(), indent_pre(), r, and visitChildren().
operator()() [79/114]
void PrintDocVisitor::operator() (const DocSecRefItem & ref) [inline]
Definition at line 612 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<secrefitem target=\"%s\">\n",qPrint(ref.target()));
      visitChildren(ref);
      indent_post();
      printf("</secrefitem>\n");
    }
References indent_post(), indent_pre(), qPrint(), DocSecRefItem::target(), and visitChildren().
operator()() [80/114]
void PrintDocVisitor::operator() (const DocSecRefItem & ref) [inline]
Definition at line 612 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<secrefitem target=\"%s\">\n",qPrint(ref.target()));
      visitChildren(ref);
      indent_post();
      printf("</secrefitem>\n");
    }
References indent_post(), indent_pre(), qPrint(), DocSecRefItem::target(), and visitChildren().
operator()() [81/114]
void PrintDocVisitor::operator() (const DocSecRefList & rl) [inline]
Definition at line 620 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<secreflist>\n");
      visitChildren(rl);
      indent_post();
      printf("</secreflist>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [82/114]
void PrintDocVisitor::operator() (const DocSecRefList & rl) [inline]
Definition at line 620 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<secreflist>\n");
      visitChildren(rl);
      indent_post();
      printf("</secreflist>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [83/114]
void PrintDocVisitor::operator() (const DocSection & s) [inline]
Definition at line 384 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<sect%d>\n",s.level());
      visitChildren(s);
      indent_post();
      printf("</sect%d>\n",s.level());
    }
References indent_post(), indent_pre(), s, and visitChildren().
operator()() [84/114]
void PrintDocVisitor::operator() (const DocSection & s) [inline]
Definition at line 384 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<sect%d>\n",s.level());
      visitChildren(s);
      indent_post();
      printf("</sect%d>\n",s.level());
    }
References indent_post(), indent_pre(), s, and visitChildren().
operator()() [85/114]
void PrintDocVisitor::operator() (const DocSeparator &) [inline]
Definition at line 261 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<sep/>");
    }
References indent_leaf().
operator()() [86/114]
void PrintDocVisitor::operator() (const DocSeparator &) [inline]
Definition at line 261 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<sep/>");
    }
References indent_leaf().
operator()() [87/114]
void PrintDocVisitor::operator() (const DocSimpleList & l) [inline]
Definition at line 365 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<ul>\n");
      visitChildren(l);
      indent_post();
      printf("</ul>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [88/114]
void PrintDocVisitor::operator() (const DocSimpleList & l) [inline]
Definition at line 365 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<ul>\n");
      visitChildren(l);
      indent_post();
      printf("</ul>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [89/114]
void PrintDocVisitor::operator() (const DocSimpleListItem & li) [inline]
Definition at line 373 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<li>\n");
      if (li.paragraph())
      {
        visit(*this,*li.paragraph());
      }
      indent_post();
      printf("</li>\n");
    }
References indent_post(), indent_pre(), and DocSimpleListItem::paragraph().
operator()() [90/114]
void PrintDocVisitor::operator() (const DocSimpleListItem & li) [inline]
Definition at line 373 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<li>\n");
      if (li.paragraph())
      {
        visit(*this,*li.paragraph());
      }
      indent_post();
      printf("</li>\n");
    }
References indent_post(), indent_pre(), and DocSimpleListItem::paragraph().
operator()() [91/114]
void PrintDocVisitor::operator() (const DocSimpleSect & s) [inline]
Definition at line 323 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<simplesect type=");
      switch(s.type())
      {
    case DocSimpleSect::See: printf("see"); break;
    case DocSimpleSect::Return: printf("return"); break;
    case DocSimpleSect::Author: printf("author"); break;
    case DocSimpleSect::Authors: printf("authors"); break;
    case DocSimpleSect::Version: printf("version"); break;
    case DocSimpleSect::Since: printf("since"); break;
    case DocSimpleSect::Date: printf("date"); break;
    case DocSimpleSect::Note: printf("note"); break;
    case DocSimpleSect::Warning: printf("warning"); break;
    case DocSimpleSect::Pre: printf("pre"); break;
    case DocSimpleSect::Post: printf("post"); break;
    case DocSimpleSect::Copyright: printf("copyright"); break;
    case DocSimpleSect::Invar: printf("invar"); break;
    case DocSimpleSect::Remark: printf("remark"); break;
    case DocSimpleSect::Attention: printf("attention"); break;
    case DocSimpleSect::User: printf("user"); break;
    case DocSimpleSect::Rcs: printf("rcs"); break;
    case DocSimpleSect::Unknown: printf("unknown"); break;
      }
      printf(">\n");
      if (s.title())
      {
        std::visit(*this, *s.title());
      }
      visitChildren(s);
      indent_post();
      printf("</simplesect>\n");
    }
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, indent_post(), indent_pre(), DocSimpleSect::Invar, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, s, DocSimpleSect::See, DocSimpleSect::Since, DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, visitChildren(), and DocSimpleSect::Warning.
operator()() [92/114]
void PrintDocVisitor::operator() (const DocSimpleSect & s) [inline]
Definition at line 323 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<simplesect type=");
      switch(s.type())
      {
    case DocSimpleSect::See: printf("see"); break;
    case DocSimpleSect::Return: printf("return"); break;
    case DocSimpleSect::Author: printf("author"); break;
    case DocSimpleSect::Authors: printf("authors"); break;
    case DocSimpleSect::Version: printf("version"); break;
    case DocSimpleSect::Since: printf("since"); break;
    case DocSimpleSect::Date: printf("date"); break;
    case DocSimpleSect::Note: printf("note"); break;
    case DocSimpleSect::Warning: printf("warning"); break;
    case DocSimpleSect::Pre: printf("pre"); break;
    case DocSimpleSect::Post: printf("post"); break;
    case DocSimpleSect::Copyright: printf("copyright"); break;
    case DocSimpleSect::Invar: printf("invar"); break;
    case DocSimpleSect::Remark: printf("remark"); break;
    case DocSimpleSect::Attention: printf("attention"); break;
    case DocSimpleSect::User: printf("user"); break;
    case DocSimpleSect::Rcs: printf("rcs"); break;
    case DocSimpleSect::Unknown: printf("unknown"); break;
      }
      printf(">\n");
      if (s.title())
      {
        std::visit(*this, *s.title());
      }
      visitChildren(s);
      indent_post();
      printf("</simplesect>\n");
    }
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, indent_post(), indent_pre(), DocSimpleSect::Invar, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, s, DocSimpleSect::See, DocSimpleSect::Since, DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, visitChildren(), and DocSimpleSect::Warning.
operator()() [93/114]
void PrintDocVisitor::operator() (const DocSimpleSectSep &) [inline]
Definition at line 247 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<simplesectsep/>");
    }
References indent_leaf().
operator()() [94/114]
void PrintDocVisitor::operator() (const DocSimpleSectSep &) [inline]
Definition at line 247 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("<simplesectsep/>");
    }
References indent_leaf().
operator()() [95/114]
void PrintDocVisitor::operator() (const DocStyleChange & s) [inline]
Definition at line 97 of file printdocvisitor.h.
    {
      indent_leaf();
      switch (s.style())
      {
        case DocStyleChange::Bold:
          if (s.enable()) printf("<bold>"); else printf("</bold>");
          break;
        case DocStyleChange::S:
          if (s.enable()) printf("<s>"); else printf("</s>");
          break;
        case DocStyleChange::Strike:
          if (s.enable()) printf("<strike>"); else printf("</strike>");
          break;
        case DocStyleChange::Del:
          if (s.enable()) printf("<del>"); else printf("</del>");
          break;
        case DocStyleChange::Underline:
          if (s.enable()) printf("<underline>"); else printf("</underline>");
          break;
        case DocStyleChange::Ins:
          if (s.enable()) printf("<ins>"); else printf("</ins>");
          break;
        case DocStyleChange::Italic:
          if (s.enable()) printf("<italic>"); else printf("</italic>");
          break;
        case DocStyleChange::Code:
          if (s.enable()) printf("<code>"); else printf("</code>");
          break;
        case DocStyleChange::Subscript:
          if (s.enable()) printf("<sub>"); else printf("</sub>");
          break;
        case DocStyleChange::Superscript:
          if (s.enable()) printf("<sup>"); else printf("</sup>");
          break;
        case DocStyleChange::Center:
          if (s.enable()) printf("<center>"); else printf("</center>");
          break;
        case DocStyleChange::Small:
          if (s.enable()) printf("<small>"); else printf("</small>");
          break;
        case DocStyleChange::Cite:
          if (s.enable()) printf("<cite>"); else printf("</cite>");
          break;
        case DocStyleChange::Preformatted:
          if (s.enable()) printf("<pre>"); else printf("</pre>");
          break;
        case DocStyleChange::Div:
          if (s.enable()) printf("<div>"); else printf("</div>");
          break;
        case DocStyleChange::Span:
          if (s.enable()) printf("<span>"); else printf("</span>");
          break;
      }
    }
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Cite, DocStyleChange::Code, DocStyleChange::Del, DocStyleChange::Div, indent_leaf(), DocStyleChange::Ins, DocStyleChange::Italic, DocStyleChange::Preformatted, s, DocStyleChange::S, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::Strike, DocStyleChange::Subscript, DocStyleChange::Superscript, and DocStyleChange::Underline.
operator()() [96/114]
void PrintDocVisitor::operator() (const DocStyleChange & s) [inline]
Definition at line 97 of file printdocvisitor.h.
    {
      indent_leaf();
      switch (s.style())
      {
        case DocStyleChange::Bold:
          if (s.enable()) printf("<bold>"); else printf("</bold>");
          break;
        case DocStyleChange::S:
          if (s.enable()) printf("<s>"); else printf("</s>");
          break;
        case DocStyleChange::Strike:
          if (s.enable()) printf("<strike>"); else printf("</strike>");
          break;
        case DocStyleChange::Del:
          if (s.enable()) printf("<del>"); else printf("</del>");
          break;
        case DocStyleChange::Underline:
          if (s.enable()) printf("<underline>"); else printf("</underline>");
          break;
        case DocStyleChange::Ins:
          if (s.enable()) printf("<ins>"); else printf("</ins>");
          break;
        case DocStyleChange::Italic:
          if (s.enable()) printf("<italic>"); else printf("</italic>");
          break;
        case DocStyleChange::Code:
          if (s.enable()) printf("<code>"); else printf("</code>");
          break;
        case DocStyleChange::Subscript:
          if (s.enable()) printf("<sub>"); else printf("</sub>");
          break;
        case DocStyleChange::Superscript:
          if (s.enable()) printf("<sup>"); else printf("</sup>");
          break;
        case DocStyleChange::Center:
          if (s.enable()) printf("<center>"); else printf("</center>");
          break;
        case DocStyleChange::Small:
          if (s.enable()) printf("<small>"); else printf("</small>");
          break;
        case DocStyleChange::Cite:
          if (s.enable()) printf("<cite>"); else printf("</cite>");
          break;
        case DocStyleChange::Preformatted:
          if (s.enable()) printf("<pre>"); else printf("</pre>");
          break;
        case DocStyleChange::Div:
          if (s.enable()) printf("<div>"); else printf("</div>");
          break;
        case DocStyleChange::Span:
          if (s.enable()) printf("<span>"); else printf("</span>");
          break;
      }
    }
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Cite, DocStyleChange::Code, DocStyleChange::Del, DocStyleChange::Div, indent_leaf(), DocStyleChange::Ins, DocStyleChange::Italic, DocStyleChange::Preformatted, s, DocStyleChange::S, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::Strike, DocStyleChange::Subscript, DocStyleChange::Superscript, and DocStyleChange::Underline.
operator()() [97/114]
void PrintDocVisitor::operator() (const DocSymbol & s) [inline]
Definition at line 56 of file printdocvisitor.h.
    {
      indent_leaf();
      const char *res = HtmlEntityMapper::instance()->utf8(s.symbol(),TRUE);
      if (res)
      {
        printf("%s",res);
      }
      else
      {
        printf("print: non supported HTML-entity found: %s\n",HtmlEntityMapper::instance()->html(s.symbol(),TRUE));
      }
    }
References indent_leaf(), HtmlEntityMapper::instance(), s, TRUE, and HtmlEntityMapper::utf8().
operator()() [98/114]
void PrintDocVisitor::operator() (const DocSymbol & s) [inline]
Definition at line 56 of file printdocvisitor.h.
    {
      indent_leaf();
      const char *res = HtmlEntityMapper::instance()->utf8(s.symbol(),TRUE);
      if (res)
      {
        printf("%s",res);
      }
      else
      {
        printf("print: non supported HTML-entity found: %s\n",HtmlEntityMapper::instance()->html(s.symbol(),TRUE));
      }
    }
References indent_leaf(), HtmlEntityMapper::instance(), s, TRUE, and HtmlEntityMapper::utf8().
operator()() [99/114]
void PrintDocVisitor::operator() (const DocText & t) [inline]
Definition at line 679 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<text>\n");
      visitChildren(t);
      indent_post();
      printf("</text>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [100/114]
void PrintDocVisitor::operator() (const DocText & t) [inline]
Definition at line 679 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<text>\n");
      visitChildren(t);
      indent_post();
      printf("</text>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [101/114]
void PrintDocVisitor::operator() (const DocTitle & t) [inline]
Definition at line 357 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<title>\n");
      visitChildren(t);
      indent_post();
      printf("</title>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [102/114]
void PrintDocVisitor::operator() (const DocTitle & t) [inline]
Definition at line 357 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<title>\n");
      visitChildren(t);
      indent_post();
      printf("</title>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [103/114]
void PrintDocVisitor::operator() (const DocURL & u) [inline]
Definition at line 82 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("%s",qPrint(u.url()));
    }
References indent_leaf(), qPrint(), and DocURL::url().
operator()() [104/114]
void PrintDocVisitor::operator() (const DocURL & u) [inline]
Definition at line 82 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("%s",qPrint(u.url()));
    }
References indent_leaf(), qPrint(), and DocURL::url().
operator()() [105/114]
void PrintDocVisitor::operator() (const DocVerbatim & s) [inline]
Definition at line 152 of file printdocvisitor.h.
    {
      indent_leaf();
      switch(s.type())
      {
        case DocVerbatim::Code: printf("<code>"); break;
        case DocVerbatim::Verbatim: printf("<verbatim>"); break;
        case DocVerbatim::JavaDocLiteral: printf("<javadocliteral>"); break;
        case DocVerbatim::JavaDocCode: printf("<javadoccode>"); break;
        case DocVerbatim::HtmlOnly: printf("<htmlonly>"); break;
        case DocVerbatim::RtfOnly: printf("<rtfonly>"); break;
        case DocVerbatim::ManOnly: printf("<manonly>"); break;
        case DocVerbatim::LatexOnly: printf("<latexonly>"); break;
        case DocVerbatim::XmlOnly: printf("<xmlonly>"); break;
        case DocVerbatim::DocbookOnly: printf("<docbookonly>"); break;
        case DocVerbatim::Dot: printf("<dot>"); break;
        case DocVerbatim::Msc: printf("<msc>"); break;
        case DocVerbatim::PlantUML: printf("<plantuml>"); break;
      }
      printf("%s",qPrint(s.text()));
      switch(s.type())
      {
        case DocVerbatim::Code: printf("</code>"); break;
        case DocVerbatim::Verbatim: printf("</verbatim>"); break;
        case DocVerbatim::JavaDocLiteral: printf("</javadocliteral>"); break;
        case DocVerbatim::JavaDocCode: printf("</javadoccode>"); break;
        case DocVerbatim::HtmlOnly: printf("</htmlonly>"); break;
        case DocVerbatim::RtfOnly: printf("</rtfonly>"); break;
        case DocVerbatim::ManOnly: printf("</manonly>"); break;
        case DocVerbatim::LatexOnly: printf("</latexonly>"); break;
        case DocVerbatim::XmlOnly: printf("</xmlonly>"); break;
        case DocVerbatim::DocbookOnly: printf("</docbookonly>"); break;
        case DocVerbatim::Dot: printf("</dot>"); break;
        case DocVerbatim::Msc: printf("</msc>"); break;
        case DocVerbatim::PlantUML: printf("</plantuml>"); break;
      }
    }
References DocVerbatim::Code, DocVerbatim::DocbookOnly, DocVerbatim::Dot, DocVerbatim::HtmlOnly, indent_leaf(), DocVerbatim::JavaDocCode, DocVerbatim::JavaDocLiteral, DocVerbatim::LatexOnly, DocVerbatim::ManOnly, DocVerbatim::Msc, DocVerbatim::PlantUML, qPrint(), DocVerbatim::RtfOnly, s, DocVerbatim::Verbatim, and DocVerbatim::XmlOnly.
operator()() [106/114]
void PrintDocVisitor::operator() (const DocVerbatim & s) [inline]
Definition at line 152 of file printdocvisitor.h.
    {
      indent_leaf();
      switch(s.type())
      {
        case DocVerbatim::Code: printf("<code>"); break;
        case DocVerbatim::Verbatim: printf("<verbatim>"); break;
        case DocVerbatim::JavaDocLiteral: printf("<javadocliteral>"); break;
        case DocVerbatim::JavaDocCode: printf("<javadoccode>"); break;
        case DocVerbatim::HtmlOnly: printf("<htmlonly>"); break;
        case DocVerbatim::RtfOnly: printf("<rtfonly>"); break;
        case DocVerbatim::ManOnly: printf("<manonly>"); break;
        case DocVerbatim::LatexOnly: printf("<latexonly>"); break;
        case DocVerbatim::XmlOnly: printf("<xmlonly>"); break;
        case DocVerbatim::DocbookOnly: printf("<docbookonly>"); break;
        case DocVerbatim::Dot: printf("<dot>"); break;
        case DocVerbatim::Msc: printf("<msc>"); break;
        case DocVerbatim::PlantUML: printf("<plantuml>"); break;
      }
      printf("%s",qPrint(s.text()));
      switch(s.type())
      {
        case DocVerbatim::Code: printf("</code>"); break;
        case DocVerbatim::Verbatim: printf("</verbatim>"); break;
        case DocVerbatim::JavaDocLiteral: printf("</javadocliteral>"); break;
        case DocVerbatim::JavaDocCode: printf("</javadoccode>"); break;
        case DocVerbatim::HtmlOnly: printf("</htmlonly>"); break;
        case DocVerbatim::RtfOnly: printf("</rtfonly>"); break;
        case DocVerbatim::ManOnly: printf("</manonly>"); break;
        case DocVerbatim::LatexOnly: printf("</latexonly>"); break;
        case DocVerbatim::XmlOnly: printf("</xmlonly>"); break;
        case DocVerbatim::DocbookOnly: printf("</docbookonly>"); break;
        case DocVerbatim::Dot: printf("</dot>"); break;
        case DocVerbatim::Msc: printf("</msc>"); break;
        case DocVerbatim::PlantUML: printf("</plantuml>"); break;
      }
    }
References DocVerbatim::Code, DocVerbatim::DocbookOnly, DocVerbatim::Dot, DocVerbatim::HtmlOnly, indent_leaf(), DocVerbatim::JavaDocCode, DocVerbatim::JavaDocLiteral, DocVerbatim::LatexOnly, DocVerbatim::ManOnly, DocVerbatim::Msc, DocVerbatim::PlantUML, qPrint(), DocVerbatim::RtfOnly, s, DocVerbatim::Verbatim, and DocVerbatim::XmlOnly.
operator()() [107/114]
void PrintDocVisitor::operator() (const DocVhdlFlow & vf) [inline]
Definition at line 695 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<vhdlflow>\n");
      visitChildren(vf);
      indent_post();
      printf("</vhdlflow>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [108/114]
void PrintDocVisitor::operator() (const DocVhdlFlow & vf) [inline]
Definition at line 695 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<vhdlflow>\n");
      visitChildren(vf);
      indent_post();
      printf("</vhdlflow>\n");
    }
References indent_post(), indent_pre(), and visitChildren().
operator()() [109/114]
void PrintDocVisitor::operator() (const DocWhiteSpace & w) [inline]
Definition at line 44 of file printdocvisitor.h.
    {
      indent_leaf();
      if (m_insidePre)
      {
        printf("%s",qPrint(w.chars()));
      }
      else
      {
        printf(" ");
      }
    }
References indent_leaf(), m_insidePre, qPrint(), and w.
operator()() [110/114]
void PrintDocVisitor::operator() (const DocWhiteSpace & w) [inline]
Definition at line 44 of file printdocvisitor.h.
    {
      indent_leaf();
      if (m_insidePre)
      {
        printf("%s",qPrint(w.chars()));
      }
      else
      {
        printf(" ");
      }
    }
References indent_leaf(), m_insidePre, qPrint(), and w.
operator()() [111/114]
void PrintDocVisitor::operator() (const DocWord & w) [inline]
Definition at line 34 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("%s",qPrint(w.word()));
    }
References indent_leaf(), qPrint(), and w.
operator()() [112/114]
void PrintDocVisitor::operator() (const DocWord & w) [inline]
Definition at line 34 of file printdocvisitor.h.
    {
      indent_leaf();
      printf("%s",qPrint(w.word()));
    }
References indent_leaf(), qPrint(), and w.
operator()() [113/114]
void PrintDocVisitor::operator() (const DocXRefItem & x) [inline]
Definition at line 662 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<xrefitem file=\"%s\" anchor=\"%s\" title=\"%s\">\n",
          qPrint(x.file()),qPrint(x.anchor()),qPrint(x.title()));
      visitChildren(x);
      indent_post();
      printf("</xrefitem>\n");
    }
References indent_post(), indent_pre(), qPrint(), visitChildren(), and x.
operator()() [114/114]
void PrintDocVisitor::operator() (const DocXRefItem & x) [inline]
Definition at line 662 of file printdocvisitor.h.
    {
      indent_pre();
      printf("<xrefitem file=\"%s\" anchor=\"%s\" title=\"%s\">\n",
          qPrint(x.file()),qPrint(x.anchor()),qPrint(x.title()));
      visitChildren(x);
      indent_post();
      printf("</xrefitem>\n");
    }
References indent_post(), indent_pre(), qPrint(), visitChildren(), and x.
visitChildren() [1/2]
template<class T >
void PrintDocVisitor::visitChildren (const T & t) [inline]
Definition at line 269 of file printdocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
Referenced by operator()().
visitChildren() [2/2]
template<class T >
void PrintDocVisitor::visitChildren (const T & t) [inline]
Definition at line 269 of file printdocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
Member Data Documentation
m_indent
int PrintDocVisitor::m_indent [private]
Definition at line 737 of file printdocvisitor.h.
Referenced by indent(), indent_post(), and indent_pre().
m_insidePre
bool PrintDocVisitor::m_insidePre [private]
Definition at line 739 of file printdocvisitor.h.
Referenced by operator()().
m_needsEnter
bool PrintDocVisitor::m_needsEnter [private]
Definition at line 738 of file printdocvisitor.h.
Referenced by indent(), and indent_leaf().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/printdocvisitor.h
doxygen/src/printdocvisitor.h