DocbookDocVisitor Class Reference
Concrete visitor implementation for Docbook output.
#include <docbookvisitor.h>
Public Member Functions
DocbookDocVisitor (TextStream &t, CodeOutputInterface &ci, const QCString &langExt)
~DocbookDocVisitor ()
template<class T >
void visitChildren (const T &t)
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &)
void operator() (const DocHtmlList &)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocHtmlCaption &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &)
void operator() (const DocRef &)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
DocbookDocVisitor (TextStream &t, CodeOutputInterface &ci, const QCString &langExt)
~DocbookDocVisitor ()
template<class T >
void visitChildren (const T &t)
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &)
void operator() (const DocHtmlList &)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocHtmlCaption &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &)
void operator() (const DocRef &)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
Private Member Functions
void filter (const QCString &str, const bool retainNewLine=false)
void startLink (const QCString &file, const QCString &anchor)
void endLink ()
void startMscFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption, const DocNodeList &children, const QCString &srcFile, int srcLine)
void endMscFile (bool hasCaption)
void writeMscFile (const QCString &fileName, const DocVerbatim &s)
void startDiaFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption, const DocNodeList &children, const QCString &srcFile, int srcLine)
void endDiaFile (bool hasCaption)
void writeDiaFile (const QCString &fileName, const DocVerbatim &s)
void startDotFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption, const DocNodeList &children, const QCString &srcFile, int srcLine)
void endDotFile (bool hasCaption)
void writeDotFile (const QCString &fileName, const DocVerbatim &s)
void writePlantUMLFile (const QCString &fileName, const DocVerbatim &s)
void visitPreStart (TextStream &t, const DocNodeList &children, bool hasCaption, const QCString &name, const QCString &width, const QCString &height, bool inlineImage=FALSE)
void visitPostEnd (TextStream &t, bool hasCaption, bool inlineImage=FALSE)
void visitCaption (const DocNodeList &children)
void filter (const QCString &str, const bool retainNewLine=false)
void startLink (const QCString &file, const QCString &anchor)
void endLink ()
void startMscFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption, const DocNodeList &children, const QCString &srcFile, int srcLine)
void endMscFile (bool hasCaption)
void writeMscFile (const QCString &fileName, const DocVerbatim &s)
void startDiaFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption, const DocNodeList &children, const QCString &srcFile, int srcLine)
void endDiaFile (bool hasCaption)
void writeDiaFile (const QCString &fileName, const DocVerbatim &s)
void startDotFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption, const DocNodeList &children, const QCString &srcFile, int srcLine)
void endDotFile (bool hasCaption)
void writeDotFile (const QCString &fileName, const DocVerbatim &s)
void writePlantUMLFile (const QCString &fileName, const DocVerbatim &s)
void visitPreStart (TextStream &t, const DocNodeList &children, bool hasCaption, const QCString &name, const QCString &width, const QCString &height, bool inlineImage=FALSE)
void visitPostEnd (TextStream &t, bool hasCaption, bool inlineImage=FALSE)
void visitCaption (const DocNodeList &children)
Private Attributes
TextStream & m_t
CodeOutputInterface & m_ci
bool m_insidePre = false
bool m_hide = false
BoolStack m_enabled
QCString m_langExt
int m_colCnt = 0
BoolStack m_bodySet
Detailed Description
Concrete visitor implementation for Docbook output.
Definition at line 31 of file docbookvisitor.h.
Constructor & Destructor Documentation
DocbookDocVisitor() [1/2]
DocbookDocVisitor::DocbookDocVisitor (TextStream & t, CodeOutputInterface & ci, const QCString & langExt)
Definition at line 156 of file docbookvisitor.cpp.
  : m_t(t), m_ci(ci),m_langExt(langExt)
{
DB_VIS_C
  // m_t << "<section>\n";
}
References DB_VIS_C.
 DocbookDocVisitor() [1/2]
DocbookDocVisitor::~DocbookDocVisitor ()
Definition at line 162 of file docbookvisitor.cpp.
{
DB_VIS_C
  // m_t << "</section>\n";
}
References DB_VIS_C.
DocbookDocVisitor() [2/2]
DocbookDocVisitor::DocbookDocVisitor (TextStream & t, CodeOutputInterface & ci, const QCString & langExt)
 DocbookDocVisitor() [2/2]
DocbookDocVisitor::~DocbookDocVisitor ()
Member Function Documentation
endDiaFile() [1/2]
void DocbookDocVisitor::endDiaFile (bool hasCaption) [private]
Definition at line 1618 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  visitPostEnd(m_t, hasCaption);
  m_t << "</para>\n";
}
References DB_VIS_C, m_hide, m_t, and visitPostEnd().
Referenced by operator()().
endDiaFile() [2/2]
void DocbookDocVisitor::endDiaFile (bool hasCaption) [private]
endDotFile() [1/2]
void DocbookDocVisitor::endDotFile (bool hasCaption) [private]
Definition at line 1670 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "\n";
  visitPostEnd(m_t, hasCaption);
  m_t << "</para>\n";
}
References DB_VIS_C, m_hide, m_t, and visitPostEnd().
Referenced by operator()().
endDotFile() [2/2]
void DocbookDocVisitor::endDotFile (bool hasCaption) [private]
endLink() [1/2]
void DocbookDocVisitor::endLink () [private]
Definition at line 1502 of file docbookvisitor.cpp.
{
DB_VIS_C
  m_t << "</link>";
}
References DB_VIS_C, and m_t.
Referenced by operator()().
endLink() [2/2]
void DocbookDocVisitor::endLink () [private]
endMscFile() [1/2]
void DocbookDocVisitor::endMscFile (bool hasCaption) [private]
Definition at line 1567 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  visitPostEnd(m_t, hasCaption);
  m_t << "</para>\n";
}
References DB_VIS_C, m_hide, m_t, and visitPostEnd().
Referenced by operator()().
endMscFile() [2/2]
void DocbookDocVisitor::endMscFile (bool hasCaption) [private]
filter() [1/2]
void DocbookDocVisitor::filter (const QCString & str, const bool retainNewLine = false) [private]
Definition at line 1484 of file docbookvisitor.cpp.
{
DB_VIS_C
  m_t << convertToDocBook(str, retainNewLine);
}
References convertToDocBook(), DB_VIS_C, and m_t.
Referenced by operator()().
filter() [2/2]
void DocbookDocVisitor::filter (const QCString & str, const bool retainNewLine = false) [private]
operator()() [1/114]
void DocbookDocVisitor::operator() (const DocAnchor & anc)
Definition at line 432 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<anchor xml:id=\"_" << stripPath(anc.file()) << "_1" << filterId(anc.anchor()) << "\"/>";
}
References DocAnchor::anchor(), DB_VIS_C, DocAnchor::file(), filterId(), m_hide, m_t, and stripPath().
operator()() [2/114]
void DocbookDocVisitor::operator() (const DocAnchor &)
operator()() [3/114]
void DocbookDocVisitor::operator() (const DocAutoList & l)
Definition at line 622 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  if (l.isEnumList())
  {
    m_t << "<orderedlist>\n";
  }
  else
  {
    m_t << "<itemizedlist>\n";
  }
  visitChildren(l);
  if (l.isEnumList())
  {
    m_t << "</orderedlist>\n";
  }
  else
  {
    m_t << "</itemizedlist>\n";
  }
}
References DB_VIS_C, DocAutoList::isEnumList(), m_hide, m_t, and visitChildren().
operator()() [4/114]
void DocbookDocVisitor::operator() (const DocAutoList &)
operator()() [5/114]
void DocbookDocVisitor::operator() (const DocAutoListItem & li)
Definition at line 645 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<listitem>";
  visitChildren(li);
  m_t << "</listitem>";
}
References DB_VIS_C, m_hide, m_t, and visitChildren().
operator()() [6/114]
void DocbookDocVisitor::operator() (const DocAutoListItem &)
operator()() [7/114]
void DocbookDocVisitor::operator() (const DocCite & cite)
Definition at line 609 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  if (!cite.file().isEmpty()) startLink(cite.file(),filterId(cite.anchor()));
  filter(cite.text());
  if (!cite.file().isEmpty()) endLink();
}
References DocCite::anchor(), DB_VIS_C, endLink(), DocCite::file(), filter(), filterId(), QCString::isEmpty(), m_hide, startLink(), and DocCite::text().
operator()() [8/114]
void DocbookDocVisitor::operator() (const DocCite &)
operator()() [9/114]
void DocbookDocVisitor::operator() (const DocDiaFile & df)
Definition at line 1256 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  if (!Config_getBool(DOT_CLEANUP)) copyFile(df.file(),Config_getString(DOCBOOK_OUTPUT)+"/"+stripPath(df.file()));
  startDiaFile(df.file(),df.width(),df.height(),df.hasCaption(),df.children(),df.srcFile(),df.srcLine());
  visitChildren(df);
  endDiaFile(df.hasCaption());
}
References DocCompoundNode::children(), Config_getBool, Config_getString, copyFile(), DB_VIS_C, endDiaFile(), DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), DocDiagramFileBase::height(), m_hide, DocDiagramFileBase::srcFile(), DocDiagramFileBase::srcLine(), startDiaFile(), stripPath(), visitChildren(), and DocDiagramFileBase::width().
operator()() [10/114]
void DocbookDocVisitor::operator() (const DocDiaFile &)
operator()() [11/114]
void DocbookDocVisitor::operator() (const DocDotFile & df)
Definition at line 1236 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  if (!Config_getBool(DOT_CLEANUP)) copyFile(df.file(),Config_getString(DOCBOOK_OUTPUT)+"/"+stripPath(df.file()));
  startDotFile(df.file(),df.width(),df.height(),df.hasCaption(),df.children(),df.srcFile(),df.srcLine());
  visitChildren(df);
  endDotFile(df.hasCaption());
}
References DocCompoundNode::children(), Config_getBool, Config_getString, copyFile(), DB_VIS_C, endDotFile(), DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), DocDiagramFileBase::height(), m_hide, DocDiagramFileBase::srcFile(), DocDiagramFileBase::srcLine(), startDotFile(), stripPath(), visitChildren(), and DocDiagramFileBase::width().
operator()() [12/114]
void DocbookDocVisitor::operator() (const DocDotFile &)
operator()() [13/114]
void DocbookDocVisitor::operator() (const DocEmoji & s)
Definition at line 217 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  const char *res = EmojiEntityMapper::instance()->unicode(s.index());
  if (res)
  {
    m_t << res;
  }
  else
  {
    m_t << s.name();
  }
}
References DB_VIS_C, EmojiEntityMapper::instance(), m_hide, m_t, s, and EmojiEntityMapper::unicode().
operator()() [14/114]
void DocbookDocVisitor::operator() (const DocEmoji &)
operator()() [15/114]
void DocbookDocVisitor::operator() (const DocFormula & f)
Definition at line 579 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  if (f.isInline()) m_t << "<inlinemediaobject>\n";
  else m_t << " <mediaobject>\n";
  m_t << " <imageobject>\n";
  m_t << " <imagedata ";
  m_t << "align=\"center\" valign=\"middle\" scalefit=\"0\" fileref=\"" << f.relPath() << f.name() << ".png\"/>\n";
  m_t << " </imageobject>\n";
  if (f.isInline()) m_t << "</inlinemediaobject>\n";
  else m_t << " </mediaobject>\n";
}
References DB_VIS_C, f, m_hide, and m_t.
operator()() [16/114]
void DocbookDocVisitor::operator() (const DocFormula &)
operator()() [17/114]
void DocbookDocVisitor::operator() (const DocHorRuler &)
Definition at line 253 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<informaltable frame='bottom'><tgroup cols='1'><colspec align='center'/><tbody><row><entry align='center'>\n";
  m_t << "</entry></row></tbody></tgroup></informaltable>\n";
}
References DB_VIS_C, m_hide, and m_t.
operator()() [18/114]
void DocbookDocVisitor::operator() (const DocHorRuler &)
operator()() [19/114]
void DocbookDocVisitor::operator() (const DocHRef & href)
Definition at line 1156 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  if (href.url().at(0) != '#')
  {
    m_t << "<link xlink:href=\"" << convertToDocBook(href.url()) << "\">";
  }
  else
  {
    startLink(href.file(),filterId(href.url().mid(1)));
  }
  visitChildren(href);
  m_t << "</link>";
}
References QCString::at(), convertToDocBook(), DB_VIS_C, DocHRef::file(), filterId(), m_hide, m_t, QCString::mid(), startLink(), DocHRef::url(), and visitChildren().
operator()() [20/114]
void DocbookDocVisitor::operator() (const DocHRef &)
operator()() [21/114]
void DocbookDocVisitor::operator() (const DocHtmlBlockQuote & q)
Definition at line 1461 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<blockquote>";
  visitChildren(q);
  m_t << "</blockquote>";
}
References DB_VIS_C, m_hide, m_t, and visitChildren().
operator()() [22/114]
void DocbookDocVisitor::operator() (const DocHtmlBlockQuote &)
operator()() [23/114]
void DocbookDocVisitor::operator() (const DocHtmlCaption & c)
Definition at line 1136 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<caption>";
  if (!c.file().isEmpty())
  {
    m_t << "<anchor xml:id=\"_" << stripPath(c.file()) << "_1" << filterId(c.anchor()) << "\"/>";
  }
  visitChildren(c);
  m_t << "</caption>\n";
}
References c, DB_VIS_C, filterId(), m_hide, m_t, stripPath(), and visitChildren().
operator()() [24/114]
void DocbookDocVisitor::operator() (const DocHtmlCaption &)
operator()() [25/114]
void DocbookDocVisitor::operator() (const DocHtmlCell & c)
Definition at line 1081 of file docbookvisitor.cpp.
{
DB_VIS_C
  m_colCnt++;
  if (m_hide) return;
  m_t << "<entry";
  for (const auto &opt : c.attribs())
  {
    if (opt.name=="colspan")
    {
      m_t << " namest='c" << m_colCnt << "'";
      int cols = opt.value.toInt();
      m_colCnt += (cols - 1);
      m_t << " nameend='c" << m_colCnt << "'";
    }
    else if (opt.name=="rowspan")
    {
      int extraRows = opt.value.toInt() - 1;
      m_t << " morerows='" << extraRows << "'";
    }
    else if (opt.name=="class")
    {
      if (opt.value.startsWith("markdownTable")) // handle markdown generated attributes
      {
        if (opt.value.endsWith("Right"))
        {
          m_t << " align='right'";
        }
        else if (opt.value.endsWith("Left"))
        {
          m_t << " align='left'";
        }
        else if (opt.value.endsWith("Center"))
        {
          m_t << " align='center'";
        }
        // skip 'markdownTable*' value ending with "None"
      }
      else
      {
        m_t << " class='" << convertToDocBook(opt.value) << "'";
      }
    }
    else if (supportedHtmlAttribute(opt.name))
    {
      // process supported attributes only
      m_t << " " << opt.name << "='" << convertToDocBook(opt.value) << "'";
    }
  }
  m_t << ">";
  visitChildren(c);
  m_t << "</entry>";
}
References c, convertToDocBook(), DB_VIS_C, m_colCnt, m_hide, m_t, supportedHtmlAttribute(), and visitChildren().
operator()() [26/114]
void DocbookDocVisitor::operator() (const DocHtmlCell &)
operator()() [27/114]
void DocbookDocVisitor::operator() (const DocHtmlDescData & dd)
Definition at line 1011 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<listitem>";
  visitChildren(dd);
  m_t << "</listitem></varlistentry>\n";
}
References DB_VIS_C, m_hide, m_t, and visitChildren().
operator()() [28/114]
void DocbookDocVisitor::operator() (const DocHtmlDescData &)
operator()() [29/114]
void DocbookDocVisitor::operator() (const DocHtmlDescList & l)
Definition at line 993 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<variablelist>\n";
  visitChildren(l);
  m_t << "</variablelist>\n";
}
References DB_VIS_C, m_hide, m_t, and visitChildren().
operator()() [30/114]
void DocbookDocVisitor::operator() (const DocHtmlDescList &)
operator()() [31/114]
void DocbookDocVisitor::operator() (const DocHtmlDescTitle & dt)
Definition at line 1002 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<varlistentry><term>";
  visitChildren(dt);
  m_t << "</term>\n";
}
References DB_VIS_C, m_hide, m_t, and visitChildren().
operator()() [32/114]
void DocbookDocVisitor::operator() (const DocHtmlDescTitle &)
operator()() [33/114]
void DocbookDocVisitor::operator() (const DocHtmlDetails & d)
Definition at line 1181 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "\n";
  auto summary = d.summary();
  if (summary)
  {
    std::visit(*this,*summary);
  }
  m_t << "<para>";
  visitChildren(d);
  m_t << "</para>";
  m_t << "\n";
}
References DB_VIS_C, m_hide, m_t, DocHtmlDetails::summary(), and visitChildren().
operator()() [34/114]
void DocbookDocVisitor::operator() (const DocHtmlDetails &)
operator()() [35/114]
void DocbookDocVisitor::operator() (const DocHtmlHeader & h)
Definition at line 1197 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<formalpara><title>";
  visitChildren(h);
  m_t << "</title></formalpara>\n";
}
References DB_VIS_C, h, m_hide, m_t, and visitChildren().
operator()() [36/114]
void DocbookDocVisitor::operator() (const DocHtmlHeader &)
operator()() [37/114]
void DocbookDocVisitor::operator() (const DocHtmlList & s)
Definition at line 913 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  if (s.children().empty()) return;
  // opening tag will be handled in DocHtmlListItem
  visitChildren(s);
  if (s.type()==DocHtmlList::Ordered)
    m_t << "</orderedlist>\n";
  else
    m_t << "</itemizedlist>\n";
}
References DB_VIS_C, m_hide, m_t, DocHtmlList::Ordered, s, and visitChildren().
operator()() [38/114]
void DocbookDocVisitor::operator() (const DocHtmlList &)
operator()() [39/114]
void DocbookDocVisitor::operator() (const DocHtmlListItem & s)
Definition at line 926 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  const DocHtmlList *l = std::get_if<DocHtmlList>(s.parent());
  if (l->type()==DocHtmlList::Ordered)
  {
    bool isFirst = &std::get<DocHtmlListItem>(l->children().front())==&s;
    int value = 0;
    QCString type;
    for (const auto &opt : s.attribs())
    {
      if (opt.name=="value")
      {
        bool ok;
        int val = opt.value.toInt(&ok);
        if (ok) value = val;
      }
    }
    if (value>0 || isFirst)
    {
      for (const auto &opt : l->attribs())
      {
        if (opt.name=="type")
        {
          if (opt.value=="1")
            type = " numeration=\"arabic\"";
          else if (opt.value=="a")
            type = " numeration=\"loweralpha\"";
            else if (opt.value=="A")
            type = " numeration=\"upperalpha\"";
          else if (opt.value=="i")
            type = " numeration=\"lowerroman\"";
          else if (opt.value=="I")
            type = " numeration=\"upperroman\"";
        }
        else if (value==0 && opt.name=="start")
        {
          bool ok;
          int val = opt.value.toInt(&ok);
          if (ok) value = val;
        }
      }
    }
    if (value>0 && !isFirst)
    {
      m_t << "</orderedlist>\n";
    }
    if (value>0 || isFirst)
    {
      m_t << "<orderedlist";
      if (!type.isEmpty()) m_t << type.data();
      if (value>0) m_t << " startingnumber=\"" << value << "\"";
      m_t << ">\n";
    }
  }
  else
  {
    m_t << "<itemizedlist>\n";
  }
  m_t << "<listitem>\n";
  visitChildren(s);
  m_t << "</listitem>\n";
}
References DocHtmlList::attribs(), DocCompoundNode::children(), QCString::data(), DB_VIS_C, GrowVector< T >::front(), QCString::isEmpty(), m_hide, m_t, DocHtmlList::Ordered, s, DocHtmlList::type(), testsqlite3::val, and visitChildren().
operator()() [40/114]
void DocbookDocVisitor::operator() (const DocHtmlListItem &)
operator()() [41/114]
void DocbookDocVisitor::operator() (const DocHtmlRow & tr)
Definition at line 1043 of file docbookvisitor.cpp.
{
DB_VIS_C
  m_colCnt = 0;
  if (m_hide) return;
  if (tr.isHeading())
  {
    if (m_bodySet.top()) m_t << "</tbody>\n";
    m_bodySet.top() = false;
    m_t << "<thead>\n";
  }
  else if (!m_bodySet.top())
  {
    m_bodySet.top() = true;
    m_t << "<tbody>\n";
  }
  m_t << " <row ";
  for (const auto &opt : tr.attribs())
  {
    if (supportedHtmlAttribute(opt.name))
    {
      // process supported attributes only
      m_t << " " << opt.name << "='" << convertToDocBook(opt.value) << "'";
    }
  }
  m_t << ">\n";
  visitChildren(tr);
  m_t << "</row>\n";
  if (tr.isHeading())
  {
    m_t << "</thead><tbody>\n";
    m_bodySet.top() = true;
  }
}
References DocHtmlRow::attribs(), convertToDocBook(), DB_VIS_C, DocHtmlRow::isHeading(), m_bodySet, m_colCnt, m_hide, m_t, supportedHtmlAttribute(), and visitChildren().
operator()() [42/114]
void DocbookDocVisitor::operator() (const DocHtmlRow &)
operator()() [43/114]
void DocbookDocVisitor::operator() (const DocHtmlSummary & s)
Definition at line 1172 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<para><emphasis role=\"bold\">";
  visitChildren(s);
  m_t << "</emphasis></para>";
}
References DB_VIS_C, m_hide, m_t, s, and visitChildren().
operator()() [44/114]
void DocbookDocVisitor::operator() (const DocHtmlSummary &)
operator()() [45/114]
void DocbookDocVisitor::operator() (const DocHtmlTable & t)
Definition at line 1020 of file docbookvisitor.cpp.
{
DB_VIS_C
  m_bodySet.push(false);
  if (m_hide) return;
  m_t << "<informaltable frame=\"all\">\n";
  m_t << " <tgroup cols=\"" << t.numColumns() << "\" align=\"left\" colsep=\"1\" rowsep=\"1\">\n";
  for (uint i = 0; i <t.numColumns(); i++)
  {
    // do something with colwidth based of cell width specification (be aware of possible colspan in the header)?
    m_t << " <colspec colname='c" << i+1 << "'/>\n";
  }
  if (t.caption())
  {
    std::visit(*this,*t.caption());
  }
  visitChildren(t);
  if (m_bodySet.top()) m_t << " </tbody>\n";
  m_bodySet.pop();
  m_t << " </tgroup>\n";
  m_t << "</informaltable>\n";
}
References DocHtmlTable::caption(), DB_VIS_C, m_bodySet, m_hide, m_t, DocHtmlTable::numColumns(), and visitChildren().
operator()() [46/114]
void DocbookDocVisitor::operator() (const DocHtmlTable &)
operator()() [47/114]
void DocbookDocVisitor::operator() (const DocImage & img)
Definition at line 1206 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (img.type()==DocImage::DocBook)
  {
    if (m_hide) return;
    m_t << "\n";
    QCString baseName=img.name();
    int i;
    if ((i=baseName.findRev('/'))!=-1 || (i=baseName.findRev('\\'))!=-1)
    {
      baseName=baseName.right(baseName.length()-i-1);
    }
    visitPreStart(m_t, img.children(), img.hasCaption(), img.relPath() + baseName, img.width(), img.height(), img.isInlineImage());
    visitChildren(img);
    visitPostEnd(m_t, img.hasCaption(),img.isInlineImage());
    QCString file;
    bool ambig;
    FileDef *fd=findFileDef(Doxygen::imageNameLinkedMap, baseName, ambig);
    if (fd)
    {
      file=fd->absFilePath();
    }
    copyFile(file,Config_getString(DOCBOOK_OUTPUT)+"/"+baseName);
  }
  else // skip other formats
  {
  }
}
References FileDef::absFilePath(), DocCompoundNode::children(), Config_getString, copyFile(), DB_VIS_C, DocImage::DocBook, caseconvert::file, findFileDef(), QCString::findRev(), DocImage::hasCaption(), DocImage::height(), Doxygen::imageNameLinkedMap, DocImage::isInlineImage(), QCString::length(), m_hide, m_t, DocImage::name(), DocImage::relPath(), QCString::right(), DocImage::type(), visitChildren(), visitPostEnd(), visitPreStart(), and DocImage::width().
operator()() [48/114]
void DocbookDocVisitor::operator() (const DocImage &)
operator()() [49/114]
void DocbookDocVisitor::operator() (const DocInclude & inc)
Definition at line 439 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  SrcLangExt langExt = getLanguageFromFileName(inc.extension());
  switch(inc.type())
  {
    case DocInclude::IncWithLines:
      {
        m_t << "<literallayout><computeroutput>";
        FileInfo cfi(inc.file().str());
        FileDef *fd = createFileDef(cfi.dirPath(), cfi.fileName());
        getCodeParser(inc.extension()).parseCode(m_ci,inc.context(),
                                                  inc.text(),
                                                  langExt,
                                                  inc.isExample(),
                                                  inc.exampleFile(), fd);
        delete fd;
        m_t << "</computeroutput></literallayout>";
      }
      break;
    case DocInclude::Include:
      m_t << "<literallayout><computeroutput>";
      getCodeParser(inc.extension()).parseCode(m_ci,inc.context(),
                                                inc.text(),
                                                langExt,
                                                inc.isExample(),
                                                inc.exampleFile());
      m_t << "</computeroutput></literallayout>";
      break;
    case DocInclude::DontInclude:
    case DocInclude::DontIncWithLines:
    case DocInclude::HtmlInclude:
    case DocInclude::LatexInclude:
    case DocInclude::RtfInclude:
    case DocInclude::ManInclude:
    case DocInclude::XmlInclude:
      break;
    case DocInclude::DocbookInclude:
      m_t << inc.text();
      break;
    case DocInclude::VerbInclude:
      m_t << "<literallayout>";
      filter(inc.text());
      m_t << "</literallayout>";
      break;
    case DocInclude::Snippet:
      m_t << "<literallayout><computeroutput>";
      getCodeParser(inc.extension()).parseCode(m_ci,
                                                inc.context(),
                                                extractBlock(inc.text(),inc.blockId()),
                                                langExt,
                                                inc.isExample(),
                                                inc.exampleFile()
                                               );
      m_t << "</computeroutput></literallayout>";
      break;
    case DocInclude::SnipWithLines:
      {
         FileInfo cfi(inc.file().str());
         FileDef *fd = createFileDef(cfi.dirPath(), cfi.fileName());
         m_t << "<literallayout><computeroutput>";
         getCodeParser(inc.extension()).parseCode(m_ci,
                                           inc.context(),
                                           extractBlock(inc.text(),inc.blockId()),
                                           langExt,
                                           inc.isExample(),
                                           inc.exampleFile(),
                                           fd,
                                           lineBlock(inc.text(),inc.blockId()),
                                           -1, // endLine
                                           FALSE, // inlineFragment
                                           0, // memberDef
                                           TRUE // show line number
                                          );
         delete fd;
         m_t << "</computeroutput></literallayout>";
      }
      break;
    case DocInclude::SnippetDoc:
    case DocInclude::IncludeDoc:
      err("Internal inconsistency: found switch SnippetDoc / IncludeDoc in file: %s"
          "Please create a bug report\n",__FILE__);
      break;
  }
}
References DocInclude::blockId(), DocInclude::context(), createFileDef(), DB_VIS_C, FileInfo::dirPath(), DocInclude::DocbookInclude, DocInclude::DontInclude, DocInclude::DontIncWithLines, err(), DocInclude::exampleFile(), DocInclude::extension(), extractBlock(), FALSE, DocInclude::file(), FileInfo::fileName(), filter(), DocVisitor::getCodeParser(), getLanguageFromFileName(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isExample(), DocInclude::LatexInclude, lineBlock(), m_ci, m_hide, m_t, DocInclude::ManInclude, CodeParserInterface::parseCode(), DocInclude::RtfInclude, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, QCString::str(), DocInclude::text(), TRUE, DocInclude::type(), DocInclude::VerbInclude, and DocInclude::XmlInclude.
operator()() [50/114]
void DocbookDocVisitor::operator() (const DocInclude &)
operator()() [51/114]
void DocbookDocVisitor::operator() (const DocIncOperator & op)
Definition at line 526 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (op.isFirst())
  {
    if (!m_hide)
    {
      m_t << "<programlisting linenumbering=\"unnumbered\">";
    }
    pushHidden(m_hide);
    m_hide = TRUE;
  }
  QCString locLangExt = getFileNameExtension(op.includeFileName());
  if (locLangExt.isEmpty()) locLangExt = m_langExt;
  SrcLangExt langExt = getLanguageFromFileName(locLangExt);
  if (op.type()!=DocIncOperator::Skip)
  {
    m_hide = popHidden();
    if (!m_hide)
    {
      FileDef *fd = 0;
      if (!op.includeFileName().isEmpty())
      {
        FileInfo cfi(op.includeFileName().str());
        fd = createFileDef(cfi.dirPath(), cfi.fileName());
      }
      getCodeParser(locLangExt).parseCode(m_ci,op.context(),
                                        op.text(),langExt,op.isExample(),
                                        op.exampleFile(),
                                        fd, // fileDef
                                        op.line(), // startLine
                                        -1, // endLine
                                        FALSE, // inline fragment
                                        0, // memberDef
                                        op.showLineNo() // show line numbers
                                       );
      if (fd) delete fd;
    }
    pushHidden(m_hide);
    m_hide=TRUE;
  }
  if (op.isLast())
  {
    m_hide = popHidden();
    if (!m_hide) m_t << "</programlisting>";
  }
  else
  {
    if (!m_hide) m_t << "\n";
  }
}
References DocIncOperator::context(), createFileDef(), DB_VIS_C, FileInfo::dirPath(), DocIncOperator::exampleFile(), FALSE, FileInfo::fileName(), DocVisitor::getCodeParser(), getFileNameExtension(), getLanguageFromFileName(), DocIncOperator::includeFileName(), QCString::isEmpty(), DocIncOperator::isExample(), DocIncOperator::isFirst(), DocIncOperator::isLast(), DocIncOperator::line(), m_ci, m_hide, m_langExt, m_t, CodeParserInterface::parseCode(), DocVisitor::popHidden(), DocVisitor::pushHidden(), DocIncOperator::showLineNo(), DocIncOperator::Skip, QCString::str(), DocIncOperator::text(), TRUE, and DocIncOperator::type().
operator()() [52/114]
void DocbookDocVisitor::operator() (const DocIncOperator &)
operator()() [53/114]
void DocbookDocVisitor::operator() (const DocIndexEntry & ie)
Definition at line 594 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<indexterm><primary>";
  filter(ie.entry());
  m_t << "</primary></indexterm>\n";
}
References DB_VIS_C, DocIndexEntry::entry(), filter(), m_hide, and m_t.
operator()() [54/114]
void DocbookDocVisitor::operator() (const DocIndexEntry &)
operator()() [55/114]
void DocbookDocVisitor::operator() (const DocInternal & i)
Definition at line 1149 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  visitChildren(i);
}
References DB_VIS_C, m_hide, and visitChildren().
operator()() [56/114]
void DocbookDocVisitor::operator() (const DocInternal &)
operator()() [57/114]
void DocbookDocVisitor::operator() (const DocInternalRef & ref)
Definition at line 1444 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  startLink(ref.file(),ref.anchor());
  visitChildren(ref);
  endLink();
  m_t << " ";
}
References DocInternalRef::anchor(), DB_VIS_C, endLink(), DocInternalRef::file(), m_hide, m_t, startLink(), and visitChildren().
operator()() [58/114]
void DocbookDocVisitor::operator() (const DocInternalRef &)
operator()() [59/114]
void DocbookDocVisitor::operator() (const DocLineBreak &)
Definition at line 244 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<?linebreak?>";
  // gives nicer results but gives problems as it is not allowed in <pare> and also problems with dblatex
  // m_t << "\n" << "<sbr/>\n";
}
References DB_VIS_C, m_hide, and m_t.
operator()() [60/114]
void DocbookDocVisitor::operator() (const DocLineBreak &)
operator()() [61/114]
void DocbookDocVisitor::operator() (const DocLink & lnk)
Definition at line 1266 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  startLink(lnk.file(),lnk.anchor());
  visitChildren(lnk);
  endLink();
}
References DocLink::anchor(), DB_VIS_C, endLink(), DocLink::file(), m_hide, startLink(), and visitChildren().
operator()() [62/114]
void DocbookDocVisitor::operator() (const DocLink &)
operator()() [63/114]
void DocbookDocVisitor::operator() (const DocLinkedWord & w)
Definition at line 179 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  startLink(w.file(),w.anchor());
  filter(w.word());
  endLink();
}
References DB_VIS_C, endLink(), filter(), m_hide, startLink(), and w.
operator()() [64/114]
void DocbookDocVisitor::operator() (const DocLinkedWord &)
operator()() [65/114]
void DocbookDocVisitor::operator() (const DocMscFile & df)
Definition at line 1246 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  if (!Config_getBool(DOT_CLEANUP)) copyFile(df.file(),Config_getString(DOCBOOK_OUTPUT)+"/"+stripPath(df.file()));
  startMscFile(df.file(),df.width(),df.height(),df.hasCaption(),df.children(),df.srcFile(),df.srcLine());
  visitChildren(df);
  endMscFile(df.hasCaption());
}
References DocCompoundNode::children(), Config_getBool, Config_getString, copyFile(), DB_VIS_C, endMscFile(), DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), DocDiagramFileBase::height(), m_hide, DocDiagramFileBase::srcFile(), DocDiagramFileBase::srcLine(), startMscFile(), stripPath(), visitChildren(), and DocDiagramFileBase::width().
operator()() [66/114]
void DocbookDocVisitor::operator() (const DocMscFile &)
operator()() [67/114]
void DocbookDocVisitor::operator() (const DocPara & p)
Definition at line 654 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "\n";
  m_t << "<para>";
  visitChildren(p);
  m_t << "</para>";
  m_t << "\n";
}
References DB_VIS_C, m_hide, m_t, p, and visitChildren().
operator()() [68/114]
void DocbookDocVisitor::operator() (const DocPara &)
operator()() [69/114]
void DocbookDocVisitor::operator() (const DocParamList & pl)
Definition at line 1362 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << " <row>\n";
  const DocParamSect *sect = std::get_if<DocParamSect>(pl.parent());
  if (sect && sect->hasInOutSpecifier())
  {
    m_t << "<entry>";
    if (pl.direction()!=DocParamSect::Unspecified)
    {
      if (pl.direction()==DocParamSect::In)
      {
        m_t << "in";
      }
      else if (pl.direction()==DocParamSect::Out)
      {
        m_t << "out";
      }
      else if (pl.direction()==DocParamSect::InOut)
      {
        m_t << "in,out";
      }
    }
    m_t << "</entry>";
  }
  if (sect && sect->hasTypeSpecifier())
  {
    m_t << "<entry>";
    for (const auto &type : pl.paramTypes())
    {
      std::visit(*this,type);
    }
    m_t << "</entry>";
  }
  if (pl.parameters().empty())
  {
    m_t << "<entry></entry>\n";
  }
  else
  {
    m_t << "<entry>";
    int cnt = 0;
    for (const auto &param : pl.parameters())
    {
      if (cnt)
      {
        m_t << ", ";
      }
      std::visit(*this,param);
      cnt++;
    }
    m_t << "</entry>";
  }
  m_t << "<entry>";
  for (const auto &par : pl.paragraphs())
  {
    std::visit(*this,par);
  }
  m_t << "</entry>\n";
  m_t << " </row>\n";
}
References DB_VIS_C, DocParamList::direction(), GrowVector< T >::empty(), DocParamSect::hasInOutSpecifier(), DocParamSect::hasTypeSpecifier(), DocParamSect::In, DocParamSect::InOut, m_hide, m_t, DocParamSect::Out, DocParamList::paragraphs(), DocParamList::parameters(), DocParamList::paramTypes(), DocNode::parent(), and DocParamSect::Unspecified.
operator()() [70/114]
void DocbookDocVisitor::operator() (const DocParamList &)
operator()() [71/114]
void DocbookDocVisitor::operator() (const DocParamSect & s)
Definition at line 1312 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "\n";
  m_t << " <formalpara>\n";
  m_t << " <title>\n";
  switch(s.type())
  {
    case DocParamSect::Param: m_t << theTranslator->trParameters(); break;
    case DocParamSect::RetVal: m_t << theTranslator->trReturnValues(); break;
    case DocParamSect::Exception: m_t << theTranslator->trExceptions(); break;
    case DocParamSect::TemplateParam: m_t << theTranslator->trTemplateParameters(); break;
    default:
      ASSERT(0);
  }
  m_t << "</title>\n";
  m_t << " <para>\n";
  m_t << " <table frame=\"all\">\n";
  int ncols = 2;
  if (s.type() == DocParamSect::Param)
  {
    bool hasInOutSpecs = s.hasInOutSpecifier();
    bool hasTypeSpecs = s.hasTypeSpecifier();
    if (hasInOutSpecs && hasTypeSpecs) ncols += 2;
    else if (hasInOutSpecs || hasTypeSpecs) ncols += 1;
  }
  m_t << " <tgroup cols=\"" << ncols << "\" align=\"left\" colsep=\"1\" rowsep=\"1\">\n";
  for (int i = 1; i <= ncols; i++)
  {
    if (i == ncols) m_t << " <colspec colwidth=\"4*\"/>\n";
    else m_t << " <colspec colwidth=\"1*\"/>\n";
  }
  m_t << " <tbody>\n";
  visitChildren(s);
  m_t << " </tbody>\n";
  m_t << " </tgroup>\n";
  m_t << " </table>\n";
  m_t << " </para>\n";
  m_t << " </formalpara>\n";
  m_t << " ";
}
References ASSERT, DB_VIS_C, DocParamSect::Exception, m_hide, m_t, DocParamSect::Param, DocParamSect::RetVal, s, DocParamSect::TemplateParam, theTranslator, Translator::trExceptions(), Translator::trParameters(), Translator::trReturnValues(), Translator::trTemplateParameters(), and visitChildren().
operator()() [72/114]
void DocbookDocVisitor::operator() (const DocParamSect &)
operator()() [73/114]
void DocbookDocVisitor::operator() (const DocParBlock & b)
Definition at line 1476 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  visitChildren(b);
}
References b, DB_VIS_C, m_hide, and visitChildren().
operator()() [74/114]
void DocbookDocVisitor::operator() (const DocParBlock &)
operator()() [75/114]
void DocbookDocVisitor::operator() (const DocRef & ref)
Definition at line 1275 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  if (ref.isSubPage())
  {
    startLink(QCString(),ref.anchor());
  }
  else
  {
    if (!ref.file().isEmpty()) startLink(ref.file(),ref.anchor());
  }
  if (!ref.hasLinkText()) filter(ref.targetTitle());
  visitChildren(ref);
  if (!ref.file().isEmpty()) endLink();
}
References DocRef::anchor(), DB_VIS_C, endLink(), DocRef::file(), filter(), DocRef::hasLinkText(), QCString::isEmpty(), DocRef::isSubPage(), m_hide, startLink(), DocRef::targetTitle(), and visitChildren().
operator()() [76/114]
void DocbookDocVisitor::operator() (const DocRef &)
operator()() [77/114]
void DocbookDocVisitor::operator() (const DocRoot & r)
Definition at line 665 of file docbookvisitor.cpp.
{
DB_VIS_C
  visitChildren(r);
}
References DB_VIS_C, r, and visitChildren().
operator()() [78/114]
void DocbookDocVisitor::operator() (const DocRoot &)
operator()() [79/114]
void DocbookDocVisitor::operator() (const DocSecRefItem & ref)
Definition at line 1293 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  //m_t << "<tocentry xml:idref=\"_" << stripPath(ref->file()) << "_1" << ref->anchor() << "\">";
  m_t << "<tocentry>";
  visitChildren(ref);
  m_t << "</tocentry>\n";
}
References DB_VIS_C, m_hide, m_t, and visitChildren().
operator()() [80/114]
void DocbookDocVisitor::operator() (const DocSecRefItem &)
operator()() [81/114]
void DocbookDocVisitor::operator() (const DocSecRefList & l)
Definition at line 1303 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<toc>\n";
  visitChildren(l);
  m_t << "</toc>\n";
}
References DB_VIS_C, m_hide, m_t, and visitChildren().
operator()() [82/114]
void DocbookDocVisitor::operator() (const DocSecRefList &)
operator()() [83/114]
void DocbookDocVisitor::operator() (const DocSection & s)
Definition at line 899 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<section xml:id=\"_" << stripPath(s.file());
  if (!s.anchor().isEmpty()) m_t << "_1" << s.anchor();
  m_t << "\">\n";
  m_t << "<title>";
  filter(s.title());
  m_t << "</title>\n";
  visitChildren(s);
  m_t << "</section>\n";
}
References DB_VIS_C, filter(), m_hide, m_t, s, stripPath(), and visitChildren().
operator()() [84/114]
void DocbookDocVisitor::operator() (const DocSection &)
operator()() [85/114]
void DocbookDocVisitor::operator() (const DocSeparator & sep)
Definition at line 1355 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << " " << sep.chars() << " ";
}
References DocSeparator::chars(), DB_VIS_C, m_hide, and m_t.
operator()() [86/114]
void DocbookDocVisitor::operator() (const DocSeparator &)
operator()() [87/114]
void DocbookDocVisitor::operator() (const DocSimpleList & l)
Definition at line 878 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<itemizedlist>\n";
  visitChildren(l);
  m_t << "</itemizedlist>\n";
}
References DB_VIS_C, m_hide, m_t, and visitChildren().
operator()() [88/114]
void DocbookDocVisitor::operator() (const DocSimpleList &)
operator()() [89/114]
void DocbookDocVisitor::operator() (const DocSimpleListItem & li)
Definition at line 887 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<listitem>";
  if (li.paragraph())
  {
    visit(*this,*li.paragraph());
  }
  m_t << "</listitem>\n";
}
References DB_VIS_C, m_hide, m_t, and DocSimpleListItem::paragraph().
operator()() [90/114]
void DocbookDocVisitor::operator() (const DocSimpleListItem &)
operator()() [91/114]
void DocbookDocVisitor::operator() (const DocSimpleSect & s)
Definition at line 671 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  switch(s.type())
  {
    case DocSimpleSect::See:
      if (m_insidePre)
      {
        m_t << "<formalpara><title>" << theTranslator->trSeeAlso() << "</title>\n";
      }
      else
      {
        m_t << "<formalpara><title>" << convertToDocBook(theTranslator->trSeeAlso()) << "</title>\n";
      }
      break;
    case DocSimpleSect::Return:
      if (m_insidePre)
      {
        m_t << "<formalpara><title>" << theTranslator->trReturns()<< "</title>\n";
      }
      else
      {
        m_t << "<formalpara><title>" << convertToDocBook(theTranslator->trReturns()) << "</title>\n";
      }
      break;
    case DocSimpleSect::Author:
      if (m_insidePre)
      {
        m_t << "<formalpara><title>" << theTranslator->trAuthor(TRUE, TRUE) << "</title>\n";
      }
      else
      {
        m_t << "<formalpara><title>" << convertToDocBook(theTranslator->trAuthor(TRUE, TRUE)) << "</title>\n";
      }
      break;
    case DocSimpleSect::Authors:
      if (m_insidePre)
      {
        m_t << "<formalpara><title>" << theTranslator->trAuthor(TRUE, FALSE) << "</title>\n";
      }
      else
      {
        m_t << "<formalpara><title>" << convertToDocBook(theTranslator->trAuthor(TRUE, FALSE)) << "</title>\n";
      }
      break;
    case DocSimpleSect::Version:
      if (m_insidePre)
      {
        m_t << "<formalpara><title>" << theTranslator->trVersion() << "</title>\n";
      }
      else
      {
        m_t << "<formalpara><title>" << convertToDocBook(theTranslator->trVersion()) << "</title>\n";
      }
      break;
    case DocSimpleSect::Since:
      if (m_insidePre)
      {
        m_t << "<formalpara><title>" << theTranslator->trSince() << "</title>\n";
      }
      else
      {
        m_t << "<formalpara><title>" << convertToDocBook(theTranslator->trSince()) << "</title>\n";
      }
      break;
    case DocSimpleSect::Date:
      if (m_insidePre)
      {
        m_t << "<formalpara><title>" << theTranslator->trDate() << "</title>\n";
      }
      else
      {
        m_t << "<formalpara><title>" << convertToDocBook(theTranslator->trDate()) << "</title>\n";
      }
      break;
    case DocSimpleSect::Note:
      if (m_insidePre)
      {
        m_t << "<note><title>" << theTranslator->trNote() << "</title>\n";
      }
      else
      {
        m_t << "<note><title>" << convertToDocBook(theTranslator->trNote()) << "</title>\n";
      }
      break;
    case DocSimpleSect::Warning:
      if (m_insidePre)
      {
        m_t << "<warning><title>" << theTranslator->trWarning() << "</title>\n";
      }
      else
      {
        m_t << "<warning><title>" << convertToDocBook(theTranslator->trWarning()) << "</title>\n";
      }
      break;
    case DocSimpleSect::Pre:
      if (m_insidePre)
      {
        m_t << "<formalpara><title>" << theTranslator->trPrecondition() << "</title>\n";
      }
      else
      {
        m_t << "<formalpara><title>" << convertToDocBook(theTranslator->trPrecondition()) << "</title>\n";
      }
      break;
    case DocSimpleSect::Post:
      if (m_insidePre)
      {
        m_t << "<formalpara><title>" << theTranslator->trPostcondition() << "</title>\n";
      }
      else
      {
        m_t << "<formalpara><title>" << convertToDocBook(theTranslator->trPostcondition()) << "</title>\n";
      }
      break;
    case DocSimpleSect::Copyright:
      if (m_insidePre)
      {
        m_t << "<formalpara><title>" << theTranslator->trCopyright() << "</title>\n";
      }
      else
      {
        m_t << "<formalpara><title>" << convertToDocBook(theTranslator->trCopyright()) << "</title>\n";
      }
      break;
    case DocSimpleSect::Invar:
      if (m_insidePre)
      {
        m_t << "<formalpara><title>" << theTranslator->trInvariant() << "</title>\n";
      }
      else
      {
        m_t << "<formalpara><title>" << convertToDocBook(theTranslator->trInvariant()) << "</title>\n";
      }
      break;
    case DocSimpleSect::Remark:
      // <remark> is miising the <title> possibility
      if (m_insidePre)
      {
        m_t << "<formalpara><title>" << theTranslator->trRemarks() << "</title>\n";
      }
      else
      {
        m_t << "<formalpara><title>" << convertToDocBook(theTranslator->trRemarks()) << "</title>\n";
      }
      break;
    case DocSimpleSect::Attention:
      if (m_insidePre)
      {
        m_t << "<caution><title>" << theTranslator->trAttention() << "</title>\n";
      }
      else
      {
        m_t << "<caution><title>" << convertToDocBook(theTranslator->trAttention()) << "</title>\n";
      }
      break;
    case DocSimpleSect::User:
    case DocSimpleSect::Rcs:
    case DocSimpleSect::Unknown:
      if (s.hasTitle())
        m_t << "<formalpara>\n";
      else
        m_t << "<para>\n";
      break;
  }
  if (s.title())
  {
    std::visit(*this,*s.title());
  }
  visitChildren(s);
  switch(s.type())
  {
    case DocSimpleSect::User:
    case DocSimpleSect::Rcs:
    case DocSimpleSect::Unknown:
      if (s.hasTitle())
        m_t << "</formalpara>\n";
      else
        m_t << "</para>\n";
      break;
    case DocSimpleSect::Note:
      m_t << "</note>\n";
      break;
    case DocSimpleSect::Attention:
      m_t << "</caution>\n";
      break;
    case DocSimpleSect::Warning:
      m_t << "</warning>\n";
      break;
    default:
      m_t << "</formalpara>\n";
      break;
  }
}
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, convertToDocBook(), DocSimpleSect::Copyright, DocSimpleSect::Date, DB_VIS_C, FALSE, DocSimpleSect::Invar, m_hide, m_insidePre, m_t, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, s, DocSimpleSect::See, DocSimpleSect::Since, theTranslator, Translator::trAttention(), Translator::trAuthor(), Translator::trCopyright(), Translator::trDate(), Translator::trInvariant(), Translator::trNote(), Translator::trPostcondition(), Translator::trPrecondition(), Translator::trRemarks(), Translator::trReturns(), Translator::trSeeAlso(), Translator::trSince(), TRUE, Translator::trVersion(), Translator::trWarning(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, visitChildren(), and DocSimpleSect::Warning.
operator()() [92/114]
void DocbookDocVisitor::operator() (const DocSimpleSect &)
operator()() [93/114]
void DocbookDocVisitor::operator() (const DocSimpleSectSep &)
Definition at line 603 of file docbookvisitor.cpp.
{
DB_VIS_C
  // m_t << "<simplesect/>";
}
References DB_VIS_C.
operator()() [94/114]
void DocbookDocVisitor::operator() (const DocSimpleSectSep &)
operator()() [95/114]
void DocbookDocVisitor::operator() (const DocStyleChange & s)
Definition at line 261 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  switch (s.style())
  {
    case DocStyleChange::Bold:
      if (s.enable()) m_t << "<emphasis role=\"bold\">"; else m_t << "</emphasis>";
      break;
    case DocStyleChange::Italic:
      if (s.enable()) m_t << "<emphasis>"; else m_t << "</emphasis>";
      break;
    case DocStyleChange::Code:
      if (s.enable()) m_t << "<computeroutput>"; else m_t << "</computeroutput>";
      break;
    case DocStyleChange::Subscript:
      if (s.enable()) m_t << "<subscript>"; else m_t << "</subscript>";
      break;
    case DocStyleChange::Superscript:
      if (s.enable()) m_t << "<superscript>"; else m_t << "</superscript>";
      break;
    case DocStyleChange::Center:
      if (s.enable()) m_t << "<informaltable frame='none'><tgroup cols='1'><colspec align='center'/><tbody><row><entry align='center'>";
      else m_t << "</entry></row></tbody></tgroup></informaltable>";
      break;
    case DocStyleChange::Preformatted:
      if (s.enable())
      {
        m_t << "<literallayout>";
        m_insidePre=TRUE;
      }
      else
      {
        m_t << "</literallayout>";
        m_insidePre=FALSE;
      }
      break;
      /* There is no equivalent Docbook tag for rendering Small text */
    case DocStyleChange::Small: /* XSLT Stylesheets can be used */ break;
                                                                   /* HTML only */
    case DocStyleChange::Cite: break;
    case DocStyleChange::S: break;
    case DocStyleChange::Strike: break;
    case DocStyleChange::Del: break;
    case DocStyleChange::Underline: break;
    case DocStyleChange::Ins: break;
    case DocStyleChange::Div: /* HTML only */ break;
    case DocStyleChange::Span: /* HTML only */ break;
  }
}
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Cite, DocStyleChange::Code, DB_VIS_C, DocStyleChange::Del, DocStyleChange::Div, FALSE, DocStyleChange::Ins, DocStyleChange::Italic, m_hide, m_insidePre, m_t, DocStyleChange::Preformatted, s, DocStyleChange::S, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::Strike, DocStyleChange::Subscript, DocStyleChange::Superscript, TRUE, and DocStyleChange::Underline.
operator()() [96/114]
void DocbookDocVisitor::operator() (const DocStyleChange &)
operator()() [97/114]
void DocbookDocVisitor::operator() (const DocSymbol & s)
Definition at line 202 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  const char *res = HtmlEntityMapper::instance()->docbook(s.symbol());
  if (res)
  {
    m_t << res;
  }
  else
  {
    err("DocBook: non supported HTML-entity found: %s\n",HtmlEntityMapper::instance()->html(s.symbol(),TRUE));
  }
}
References DB_VIS_C, HtmlEntityMapper::docbook(), err(), HtmlEntityMapper::instance(), m_hide, m_t, s, and TRUE.
operator()() [98/114]
void DocbookDocVisitor::operator() (const DocSymbol &)
operator()() [99/114]
void DocbookDocVisitor::operator() (const DocText & t)
Definition at line 1454 of file docbookvisitor.cpp.
{
DB_VIS_C
  visitChildren(t);
}
References DB_VIS_C, and visitChildren().
operator()() [100/114]
void DocbookDocVisitor::operator() (const DocText &)
operator()() [101/114]
void DocbookDocVisitor::operator() (const DocTitle & t)
Definition at line 869 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  if (t.hasTitle()) m_t << "<title>";
  visitChildren(t);
  if (t.hasTitle()) m_t << "</title>";
}
References DB_VIS_C, DocTitle::hasTitle(), m_hide, m_t, and visitChildren().
operator()() [102/114]
void DocbookDocVisitor::operator() (const DocTitle &)
operator()() [103/114]
void DocbookDocVisitor::operator() (const DocURL & u)
Definition at line 232 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  m_t << "<link xlink:href=\"";
  if (u.isEmail()) m_t << "mailto:";
  filter(u.url());
  m_t << "\">";
  filter(u.url());
  m_t << "</link>";
}
References DB_VIS_C, filter(), DocURL::isEmail(), m_hide, m_t, and DocURL::url().
operator()() [104/114]
void DocbookDocVisitor::operator() (const DocURL &)
operator()() [105/114]
void DocbookDocVisitor::operator() (const DocVerbatim & s)
Definition at line 312 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  QCString lang = m_langExt;
  if (!s.language().isEmpty()) // explicit language setting
  {
    lang = s.language();
  }
  SrcLangExt langExt = getLanguageFromCodeLang(lang);
  switch(s.type())
  {
    case DocVerbatim::Code:
      m_t << "<literallayout><computeroutput>";
      getCodeParser(m_langExt).parseCode(m_ci,s.context(),
                                         s.text(),
                                         langExt,
                                         s.isExample(),
                                         s.exampleFile());
      m_t << "</computeroutput></literallayout>";
      break;
    case DocVerbatim::Verbatim:
      m_t << "<literallayout><computeroutput>";
      filter(s.text());
      m_t << "</computeroutput></literallayout>";
      break;
    case DocVerbatim::JavaDocLiteral:
      filter(s.text(), true);
      break;
    case DocVerbatim::JavaDocCode:
      m_t << "<computeroutput>";
      filter(s.text(), true);
      m_t << "</computeroutput>";
      break;
    case DocVerbatim::HtmlOnly:
      break;
    case DocVerbatim::RtfOnly:
      break;
    case DocVerbatim::ManOnly:
      break;
    case DocVerbatim::LatexOnly:
      break;
    case DocVerbatim::XmlOnly:
      break;
    case DocVerbatim::DocbookOnly:
      m_t << s.text();
      break;
    case DocVerbatim::Dot:
      {
        static int dotindex = 1;
        QCString baseName(4096);
        QCString name;
        QCString stext = s.text();
        m_t << "<para>\n";
        name.sprintf("%s%d", "dot_inline_dotgraph_", dotindex);
        baseName.sprintf("%s%d",
            qPrint(Config_getString(DOCBOOK_OUTPUT)+"/inline_dotgraph_"),
            dotindex++
            );
        std::string fileName = baseName.str()+".dot";
        std::ofstream file(fileName,std::ofstream::out | std::ofstream::binary);
        if (!file.is_open())
        {
          err("Could not open file %s for writing\n",fileName.c_str());
        }
        file.write(stext.data(), stext.length());
        file.close();
        writeDotFile(baseName, s);
        m_t << "</para>\n";
        if (Config_getBool(DOT_CLEANUP)) Dir().remove(fileName);
      }
      break;
    case DocVerbatim::Msc:
      {
        static int mscindex = 1;
        QCString baseName(4096);
        QCString name;
        QCString stext = s.text();
        m_t << "<para>\n";
        name.sprintf("%s%d", "msc_inline_mscgraph_", mscindex);
        baseName.sprintf("%s%d",
            (Config_getString(DOCBOOK_OUTPUT)+"/inline_mscgraph_").data(),
            mscindex++
            );
        std::string fileName = baseName.str()+".msc";
        std::ofstream file(fileName,std::ofstream::out | std::ofstream::binary);
        if (!file.is_open())
        {
          err("Could not open file %s for writing\n",fileName.c_str());
        }
        QCString text = "msc {";
        text+=stext;
        text+="}";
        file.write(text.data(), text.length());
        file.close();
        writeMscFile(baseName,s);
        m_t << "</para>\n";
        if (Config_getBool(DOT_CLEANUP)) Dir().remove(fileName);
      }
      break;
    case DocVerbatim::PlantUML:
      {
        QCString docbookOutput = Config_getString(DOCBOOK_OUTPUT);
        QCString baseName = PlantumlManager::instance().writePlantUMLSource(docbookOutput,
            s.exampleFile(),s.text(),PlantumlManager::PUML_BITMAP,
            s.engine(),s.srcFile(),s.srcLine());
        QCString shortName = baseName;
        int i;
        if ((i=shortName.findRev('/'))!=-1)
        {
          shortName=shortName.right(shortName.length()-i-1);
        }
        m_t << "<para>\n";
        writePlantUMLFile(baseName,s);
        m_t << "</para>\n";
      }
      break;
  }
}
References DocVerbatim::Code, Config_getBool, Config_getString, data, QCString::data(), DB_VIS_C, DocVerbatim::DocbookOnly, DocVerbatim::Dot, err(), caseconvert::file, filter(), QCString::findRev(), DocVisitor::getCodeParser(), getLanguageFromCodeLang(), DocVerbatim::HtmlOnly, PlantumlManager::instance(), DocVerbatim::JavaDocCode, DocVerbatim::JavaDocLiteral, DocVerbatim::LatexOnly, QCString::length(), m_ci, m_hide, m_langExt, m_t, DocVerbatim::ManOnly, DocVerbatim::Msc, setup::name, out, CodeParserInterface::parseCode(), DocVerbatim::PlantUML, PlantumlManager::PUML_BITMAP, qPrint(), Dir::remove(), QCString::right(), DocVerbatim::RtfOnly, s, QCString::sprintf(), QCString::str(), string, DocVerbatim::Verbatim, writeDotFile(), writeMscFile(), writePlantUMLFile(), PlantumlManager::writePlantUMLSource(), and DocVerbatim::XmlOnly.
operator()() [106/114]
void DocbookDocVisitor::operator() (const DocVerbatim &)
operator()() [107/114]
void DocbookDocVisitor::operator() (const DocVhdlFlow &)
Definition at line 1470 of file docbookvisitor.cpp.
{
DB_VIS_C
  // TODO: to be implemented
}
References DB_VIS_C.
operator()() [108/114]
void DocbookDocVisitor::operator() (const DocVhdlFlow &)
operator()() [109/114]
void DocbookDocVisitor::operator() (const DocWhiteSpace & w)
Definition at line 188 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  if (m_insidePre)
  {
    m_t << w.chars();
  }
  else
  {
    m_t << " ";
  }
}
References DB_VIS_C, m_hide, m_insidePre, m_t, and w.
operator()() [110/114]
void DocbookDocVisitor::operator() (const DocWhiteSpace &)
operator()() [111/114]
void DocbookDocVisitor::operator() (const DocWord & w)
Definition at line 172 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  filter(w.word());
}
References DB_VIS_C, filter(), m_hide, and w.
operator()() [112/114]
void DocbookDocVisitor::operator() (const DocWord &)
operator()() [113/114]
void DocbookDocVisitor::operator() (const DocXRefItem & x)
Definition at line 1428 of file docbookvisitor.cpp.
{
DB_VIS_C
  if (m_hide) return;
  if (x.title().isEmpty()) return;
  m_t << "<para><link linkend=\"_";
  m_t << stripPath(x.file()) << "_1" << x.anchor();
  m_t << "\">";
  filter(x.title());
  m_t << "</link>";
  m_t << " ";
  visitChildren(x);
  if (x.title().isEmpty()) return;
  m_t << "</para>";
}
References DB_VIS_C, filter(), m_hide, m_t, stripPath(), visitChildren(), and x.
operator()() [114/114]
void DocbookDocVisitor::operator() (const DocXRefItem &)
startDiaFile() [1/2]
void DocbookDocVisitor::startDiaFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption, const DocNodeList & children, const QCString & srcFile, int srcLine) [private]
Definition at line 1591 of file docbookvisitor.cpp.
{
DB_VIS_C
  QCString baseName=fileName;
  int i;
  if ((i=baseName.findRev('/'))!=-1)
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  if ((i=baseName.find('.'))!=-1)
  {
    baseName=baseName.left(i);
  }
  baseName.prepend("dia_");
  QCString outDir = Config_getString(DOCBOOK_OUTPUT);
  writeDiaGraphFromFile(fileName,outDir,baseName,DIA_BITMAP,srcFile,srcLine);
  m_t << "<para>\n";
  visitPreStart(m_t, children, hasCaption, baseName + ".png", width, height);
}
References Config_getString, DB_VIS_C, DIA_BITMAP, QCString::left(), m_t, QCString::prepend(), QCString::right(), visitPreStart(), and writeDiaGraphFromFile().
Referenced by operator()().
startDiaFile() [2/2]
void DocbookDocVisitor::startDiaFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption, const DocNodeList & children, const QCString & srcFile, int srcLine) [private]
startDotFile() [1/2]
void DocbookDocVisitor::startDotFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption, const DocNodeList & children, const QCString & srcFile, int srcLine) [private]
Definition at line 1642 of file docbookvisitor.cpp.
{
DB_VIS_C
  QCString baseName=fileName;
  int i;
  if ((i=baseName.findRev('/'))!=-1)
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  if ((i=baseName.find('.'))!=-1)
  {
    baseName=baseName.left(i);
  }
  baseName.prepend("dot_");
  QCString outDir = Config_getString(DOCBOOK_OUTPUT);
  QCString imgExt = getDotImageExtension();
  writeDotGraphFromFile(fileName,outDir,baseName,GOF_BITMAP,srcFile,srcLine);
  m_t << "<para>\n";
  visitPreStart(m_t, children, hasCaption, baseName + "." + imgExt, width, height);
}
References Config_getString, DB_VIS_C, getDotImageExtension(), GOF_BITMAP, QCString::left(), m_t, QCString::prepend(), QCString::right(), visitPreStart(), and writeDotGraphFromFile().
Referenced by operator()().
startDotFile() [2/2]
void DocbookDocVisitor::startDotFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption, const DocNodeList & children, const QCString & srcFile, int srcLine) [private]
startLink() [1/2]
void DocbookDocVisitor::startLink (const QCString & file, const QCString & anchor) [private]
Definition at line 1490 of file docbookvisitor.cpp.
{
DB_VIS_C
  m_t << "<link linkend=\"_" << stripPath(file);
  if (!anchor.isEmpty())
  {
    if (!file.isEmpty()) m_t << "_1";
    m_t << anchor;
  }
  m_t << "\">";
}
References DB_VIS_C, caseconvert::file, QCString::isEmpty(), m_t, and stripPath().
Referenced by operator()().
startLink() [2/2]
void DocbookDocVisitor::startLink (const QCString & file, const QCString & anchor) [private]
startMscFile() [1/2]
void DocbookDocVisitor::startMscFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption, const DocNodeList & children, const QCString & srcFile, int srcLine) [private]
Definition at line 1540 of file docbookvisitor.cpp.
{
DB_VIS_C
  QCString baseName=fileName;
  int i;
  if ((i=baseName.findRev('/'))!=-1)
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  if ((i=baseName.find('.'))!=-1)
  {
    baseName=baseName.left(i);
  }
  baseName.prepend("msc_");
  QCString outDir = Config_getString(DOCBOOK_OUTPUT);
  writeMscGraphFromFile(fileName,outDir,baseName,MSC_BITMAP,srcFile,srcLine);
  m_t << "<para>\n";
  visitPreStart(m_t, children, hasCaption, baseName + ".png", width, height);
}
References Config_getString, DB_VIS_C, QCString::left(), m_t, MSC_BITMAP, QCString::prepend(), QCString::right(), visitPreStart(), and writeMscGraphFromFile().
Referenced by operator()().
startMscFile() [2/2]
void DocbookDocVisitor::startMscFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption, const DocNodeList & children, const QCString & srcFile, int srcLine) [private]
visitCaption() [1/2]
void DocbookDocVisitor::visitCaption (const DocNodeList & children) [private]
Definition at line 87 of file docbookvisitor.cpp.
{
  for (const auto &n : children)
  {
    std::visit(*this,n);
  }
}
References n.
Referenced by visitPreStart(), writeDiaFile(), writeDotFile(), writeMscFile(), and writePlantUMLFile().
visitCaption() [2/2]
void DocbookDocVisitor::visitCaption (const DocNodeList & children) [private]
visitChildren() [1/2]
template<class T >
void DocbookDocVisitor::visitChildren (const T & t) [inline]
Definition at line 38 of file docbookvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
Referenced by operator()().
visitChildren() [2/2]
template<class T >
void DocbookDocVisitor::visitChildren (const T & t) [inline]
Definition at line 38 of file docbookvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
visitPostEnd() [1/2]
void DocbookDocVisitor::visitPostEnd (TextStream & t, bool hasCaption, bool inlineImage = FALSE) [private]
Definition at line 138 of file docbookvisitor.cpp.
{
  t << "\n";
  if (hasCaption && !inlineImage)
  {
    t << " -->\n"; // Needed for general formatting with title for other formats
  }
  t << " </mediaobject>\n";
  if (hasCaption && !inlineImage)
  {
    t << " </figure>\n";
  }
  else
  {
    t << " </informalfigure>\n";
  }
}
Referenced by endDiaFile(), endDotFile(), endMscFile(), operator()(), writeDiaFile(), writeDotFile(), writeMscFile(), and writePlantUMLFile().
visitPostEnd() [2/2]
void DocbookDocVisitor::visitPostEnd (TextStream & t, bool hasCaption, bool inlineImage = FALSE) [private]
visitPreStart() [1/2]
void DocbookDocVisitor::visitPreStart (TextStream & t, const DocNodeList & children, bool hasCaption, const QCString & name, const QCString & width, const QCString & height, bool inlineImage = FALSE) [private]
Definition at line 95 of file docbookvisitor.cpp.
{
  if (hasCaption && !inlineImage)
  {
    t << " <figure>\n";
    t << " <title>\n";
    visitCaption(children);
    t << " </title>\n";
  }
  else
  {
    t << " <informalfigure>\n";
  }
  t << " <mediaobject>\n";
  t << " <imageobject>\n";
  t << " <imagedata";
  if (!width.isEmpty())
  {
    t << " width=\"" << convertToDocBook(width) << "\"";
  }
  else
  {
    if (!height.isEmpty() && !inlineImage) t << " width=\"50%\"";
  }
  if (!height.isEmpty())
  {
    t << " depth=\"" << convertToDocBook(height) << "\"";
  }
  t << " align=\"center\" valign=\"middle\" scalefit=\"0\" fileref=\"" << name << "\">";
  t << "</imagedata>\n";
  t << " </imageobject>\n";
  if (hasCaption && !inlineImage)
  {
    t << " <!--\n"; // Needed for general formatting with title for other formats
  }
}
References convertToDocBook(), QCString::isEmpty(), setup::name, and visitCaption().
Referenced by operator()(), startDiaFile(), startDotFile(), startMscFile(), writeDiaFile(), writeDotFile(), writeMscFile(), and writePlantUMLFile().
visitPreStart() [2/2]
void DocbookDocVisitor::visitPreStart (TextStream & t, const DocNodeList & children, bool hasCaption, const QCString & name, const QCString & width, const QCString & height, bool inlineImage = FALSE) [private]
writeDiaFile() [1/2]
void DocbookDocVisitor::writeDiaFile (const QCString & fileName, const DocVerbatim & s) [private]
Definition at line 1575 of file docbookvisitor.cpp.
{
DB_VIS_C
  QCString shortName = baseName;
  int i;
  if ((i=shortName.findRev('/'))!=-1)
  {
    shortName=shortName.right(shortName.length()-i-1);
  }
  QCString outDir = Config_getString(DOCBOOK_OUTPUT);
  writeDiaGraphFromFile(baseName+".dia",outDir,shortName,DIA_BITMAP,s.srcFile(),s.srcLine());
  visitPreStart(m_t, s.children(), s.hasCaption(), shortName, s.width(),s.height());
  visitCaption(s.children());
  visitPostEnd(m_t, s.hasCaption());
}
References Config_getString, DB_VIS_C, DIA_BITMAP, m_t, QCString::right(), s, visitCaption(), visitPostEnd(), visitPreStart(), and writeDiaGraphFromFile().
writeDiaFile() [2/2]
void DocbookDocVisitor::writeDiaFile (const QCString & fileName, const DocVerbatim & s) [private]
writeDotFile() [1/2]
void DocbookDocVisitor::writeDotFile (const QCString & fileName, const DocVerbatim & s) [private]
Definition at line 1626 of file docbookvisitor.cpp.
{
DB_VIS_C
  QCString shortName = baseName;
  int i;
  if ((i=shortName.findRev('/'))!=-1)
  {
    shortName=shortName.right(shortName.length()-i-1);
  }
  QCString outDir = Config_getString(DOCBOOK_OUTPUT);
  writeDotGraphFromFile(baseName+".dot",outDir,shortName,GOF_BITMAP,s.srcFile(),s.srcLine());
  visitPreStart(m_t, s.children(), s.hasCaption(), s.relPath() + shortName + "." + getDotImageExtension(), s.width(),s.height());
  visitCaption(s.children());
  visitPostEnd(m_t, s.hasCaption());
}
References Config_getString, DB_VIS_C, getDotImageExtension(), GOF_BITMAP, m_t, QCString::right(), s, visitCaption(), visitPostEnd(), visitPreStart(), and writeDotGraphFromFile().
Referenced by operator()().
writeDotFile() [2/2]
void DocbookDocVisitor::writeDotFile (const QCString & fileName, const DocVerbatim & s) [private]
writeMscFile() [1/2]
void DocbookDocVisitor::writeMscFile (const QCString & fileName, const DocVerbatim & s) [private]
Definition at line 1508 of file docbookvisitor.cpp.
{
DB_VIS_C
  QCString shortName = baseName;
  int i;
  if ((i=shortName.findRev('/'))!=-1)
  {
    shortName=shortName.right(shortName.length()-i-1);
  }
  QCString outDir = Config_getString(DOCBOOK_OUTPUT);
  writeMscGraphFromFile(baseName+".msc",outDir,shortName,MSC_BITMAP,s.srcFile(),s.srcLine());
  visitPreStart(m_t, s.children(), s.hasCaption(), s.relPath() + shortName + ".png", s.width(), s.height());
  visitCaption(s.children());
  visitPostEnd(m_t, s.hasCaption());
}
References Config_getString, DB_VIS_C, m_t, MSC_BITMAP, QCString::right(), s, visitCaption(), visitPostEnd(), visitPreStart(), and writeMscGraphFromFile().
Referenced by operator()().
writeMscFile() [2/2]
void DocbookDocVisitor::writeMscFile (const QCString & fileName, const DocVerbatim & s) [private]
writePlantUMLFile() [1/2]
void DocbookDocVisitor::writePlantUMLFile (const QCString & fileName, const DocVerbatim & s) [private]
Definition at line 1524 of file docbookvisitor.cpp.
{
DB_VIS_C
  QCString shortName = baseName;
  int i;
  if ((i=shortName.findRev('/'))!=-1)
  {
    shortName=shortName.right(shortName.length()-i-1);
  }
  QCString outDir = Config_getString(DOCBOOK_OUTPUT);
  PlantumlManager::instance().generatePlantUMLOutput(baseName,outDir,PlantumlManager::PUML_BITMAP);
  visitPreStart(m_t, s.children(), s.hasCaption(), s.relPath() + shortName + ".png", s.width(),s.height());
  visitCaption(s.children());
  visitPostEnd(m_t, s.hasCaption());
}
References Config_getString, DB_VIS_C, PlantumlManager::generatePlantUMLOutput(), PlantumlManager::instance(), m_t, PlantumlManager::PUML_BITMAP, QCString::right(), s, visitCaption(), visitPostEnd(), and visitPreStart().
Referenced by operator()().
writePlantUMLFile() [2/2]
void DocbookDocVisitor::writePlantUMLFile (const QCString & fileName, const DocVerbatim & s) [private]
Member Data Documentation
m_bodySet
BoolStack DocbookDocVisitor::m_bodySet [private]
Definition at line 152 of file docbookvisitor.h.
Referenced by operator()().
m_ci
CodeOutputInterface & DocbookDocVisitor::m_ci [private]
Definition at line 146 of file docbookvisitor.h.
Referenced by operator()().
m_colCnt
int DocbookDocVisitor::m_colCnt = 0 [private]
Definition at line 151 of file docbookvisitor.h.
Referenced by operator()().
m_enabled
BoolStack DocbookDocVisitor::m_enabled [private]
Definition at line 149 of file docbookvisitor.h.
m_hide
bool DocbookDocVisitor::m_hide = false [private]
Definition at line 148 of file docbookvisitor.h.
Referenced by endDiaFile(), endDotFile(), endMscFile(), and operator()().
m_insidePre
bool DocbookDocVisitor::m_insidePre = false [private]
Definition at line 147 of file docbookvisitor.h.
Referenced by operator()().
m_langExt
QCString DocbookDocVisitor::m_langExt [private]
Definition at line 150 of file docbookvisitor.h.
Referenced by operator()().
m_t
TextStream & DocbookDocVisitor::m_t [private]
Definition at line 145 of file docbookvisitor.h.
Referenced by endDiaFile(), endDotFile(), endLink(), endMscFile(), filter(), operator()(), startDiaFile(), startDotFile(), startLink(), startMscFile(), writeDiaFile(), writeDotFile(), writeMscFile(), and writePlantUMLFile().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docbookvisitor.h
doxygen/src/docbookvisitor.h
doxygen/build/doxygen/src/docbookvisitor.cpp
doxygen/src/docbookvisitor.cpp