UsedFilesContext::Private Class Reference
Public Member Functions
void addFile (const FileDef *fd)
void addFile (const FileDef *fd)
Additional Inherited Members
Detailed Description
Definition at line 6428 of file context.cpp.
Member Function Documentation
addFile() [1/2]
void UsedFilesContext::Private::addFile (const FileDef * fd) [inline]
Definition at line 6431 of file context.cpp.
    {
      append(FileContext::alloc(fd));
    }
References FileContext::alloc(), and GenericNodeListContext::append().
addFile() [2/2]
void UsedFilesContext::Private::addFile (const FileDef * fd) [inline]
Definition at line 6431 of file context.cpp.
    {
      append(FileContext::alloc(fd));
    }
References FileContext::alloc().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp