TemplateNodeFor Class Reference
Class representing a 'for' tag in a template.
Public Member Functions
TemplateNodeFor (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
TemplateNodeFor (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
Private Attributes
bool m_reversed = false
ExprAstPtr m_expr
std::vector< QCString > m_vars
TemplateNodeList m_loopNodes
TemplateNodeList m_emptyNodes
Additional Inherited Members
Detailed Description
Class representing a 'for' tag in a template.
Definition at line 3408 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeFor() [1/2]
TemplateNodeFor::TemplateNodeFor (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3411 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeFor>(parser,parent,line), m_reversed(FALSE)
    {
      TRACE(("{TemplateNodeFor(%s)\n",qPrint(data)));
      QCString exprStr;
      int i = data.find(" in ");
      if (i==-1)
      {
        if (data.endsWith(" in"))
        {
          parser->warn(m_templateName,line,"for is missing container after 'in' keyword");
        }
        else if (data=="in")
        {
          parser->warn(m_templateName,line,"for needs at least one iterator variable");
        }
        else
        {
          parser->warn(m_templateName,line,"for is missing 'in' keyword");
        }
      }
      else
      {
        m_vars = split(data.left(i),",");
        if (m_vars.size()==0)
        {
          parser->warn(m_templateName,line,"for needs at least one iterator variable");
        }
        int j = data.find(" reversed",i);
        m_reversed = (j!=-1);
        if (j==-1) j=data.length();
        if (j>i+4)
        {
          exprStr = data.mid(i+4,j-i-4); // skip over " in " part
        }
        if (exprStr.isEmpty())
        {
          parser->warn(m_templateName,line,"for is missing container after 'in' keyword");
        }
      }
      ExpressionParser expParser(parser,line);
      m_expr = expParser.parse(exprStr);
      StringVector stopAt = { "endfor", "empty" };
      parser->parse(this,line,stopAt,m_loopNodes);
      auto tok = parser->takeNextToken();
      if (tok && tok->data=="empty")
      {
        stopAt.pop_back();
        parser->parse(this,line,stopAt,m_emptyNodes);
        parser->removeNextToken(); // skip over endfor
      }
      TRACE(("}TemplateNodeFor(%s)\n",qPrint(data)));
    }
References data, QCString::isEmpty(), m_emptyNodes, m_expr, m_loopNodes, m_reversed, TemplateNodeCreator< TemplateNodeFor >::m_templateName, m_vars, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), split(), TemplateParser::takeNextToken(), TRACE, and TemplateParser::warn().
TemplateNodeFor() [2/2]
TemplateNodeFor::TemplateNodeFor (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3411 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeFor>(parser,parent,line), m_reversed(FALSE)
    {
      TRACE(("{TemplateNodeFor(%s)\n",qPrint(data)));
      QCString exprStr;
      int i = data.find(" in ");
      if (i==-1)
      {
        if (data.endsWith(" in"))
        {
          parser->warn(m_templateName,line,"for is missing container after 'in' keyword");
        }
        else if (data=="in")
        {
          parser->warn(m_templateName,line,"for needs at least one iterator variable");
        }
        else
        {
          parser->warn(m_templateName,line,"for is missing 'in' keyword");
        }
      }
      else
      {
        m_vars = split(data.left(i),",");
        if (m_vars.size()==0)
        {
          parser->warn(m_templateName,line,"for needs at least one iterator variable");
        }
        int j = data.find(" reversed",i);
        m_reversed = (j!=-1);
        if (j==-1) j=data.length();
        if (j>i+4)
        {
          exprStr = data.mid(i+4,j-i-4); // skip over " in " part
        }
        if (exprStr.isEmpty())
        {
          parser->warn(m_templateName,line,"for is missing container after 'in' keyword");
        }
      }
      ExpressionParser expParser(parser,line);
      m_expr = expParser.parse(exprStr);
      StringVector stopAt = { "endfor", "empty" };
      parser->parse(this,line,stopAt,m_loopNodes);
      auto tok = parser->takeNextToken();
      if (tok && tok->data=="empty")
      {
        stopAt.pop_back();
        parser->parse(this,line,stopAt,m_emptyNodes);
        parser->removeNextToken(); // skip over endfor
      }
      TRACE(("}TemplateNodeFor(%s)\n",qPrint(data)));
    }
References data, QCString::isEmpty(), m_emptyNodes, m_expr, m_loopNodes, m_reversed, TemplateNodeCreator< TemplateNodeFor >::m_templateName, m_vars, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), split(), TemplateParser::takeNextToken(), TRACE, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeFor::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3468 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      //printf("TemplateNodeFor::render #loopNodes=%d #emptyNodes=%d\n",
      // m_loopNodes.count(),m_emptyNodes.count());
      if (m_expr)
      {
        TemplateVariant v = m_expr->resolve(c);
        if (v.isFunction())
        {
          v = v.call();
        }
        const TemplateListIntfPtr list = v.toList();
        if (list)
        {
          size_t listSize = list->count();
          if (listSize==0) // empty for loop
          {
            m_emptyNodes.render(ts,c);
            return;
          }
          c->push();
          //int index = m_reversed ? list.count() : 0;
          //TemplateVariant v;
          const TemplateVariant *parentLoop = c->getRef("forloop");
          size_t index = m_reversed ? listSize-1 : 0;
          TemplateListIntf::ConstIteratorPtr it = list->createIterator();
          TemplateVariant ve;
          for (m_reversed ? it->toLast() : it->toFirst();
              (it->current(ve));
              m_reversed ? it->toPrev() : it->toNext())
          {
            TemplateStructPtr s = TemplateStruct::alloc();
            s->set("counter0", index);
            s->set("counter", index+1);
            s->set("revcounter", listSize-index);
            s->set("revcounter0", listSize-index-1);
            s->set("first", index==0);
            s->set("last", index==listSize-1);
            s->set("parentloop",parentLoop ? *parentLoop : TemplateVariant());
            c->set("forloop",std::static_pointer_cast<TemplateStructIntf>(s));
            // add variables for this loop to the context
            //obj->addVariableToContext(index,m_vars,c);
            uint vi=0;
            if (m_vars.size()==1) // loop variable represents an item
            {
              c->set(m_vars[vi++],ve);
            }
            else if (m_vars.size()>1 && (ve.isStruct() || ve.isWeakStruct()))
              // loop variables represent elements in a list item
            {
              TemplateStructIntfPtr vs = ve.toStruct();
              if (vs)
              {
                for (uint i=0;i<m_vars.size();i++,vi++)
                {
                  c->set(m_vars[vi],vs->get(m_vars[vi]));
                }
              }
            }
            for (;vi<m_vars.size();vi++)
            {
              c->set(m_vars[vi],TemplateVariant());
            }
            // render all items for this iteration of the loop
            m_loopNodes.render(ts,c);
            if (m_reversed) index--; else index++;
          }
          c->pop();
        }
        else // simple type...
        {
          ci->warn(m_templateName,m_line,"for requires a variable of list type, got type '%s'!",qPrint(v.typeAsString()));
        }
      }
    }
References TemplateStruct::alloc(), c, TemplateVariant::call(), TemplateVariant::isFunction(), TemplateVariant::isStruct(), TemplateVariant::isWeakStruct(), m_emptyNodes, m_expr, TemplateNodeCreator< TemplateNodeFor >::m_line, m_loopNodes, m_reversed, TemplateNodeCreator< TemplateNodeFor >::m_templateName, m_vars, qPrint(), TemplateNodeList::render(), s, TemplateContextImpl::setLocation(), TemplateVariant::toList(), TemplateVariant::toStruct(), TemplateVariant::typeAsString(), and TemplateContextImpl::warn().
render() [2/2]
void TemplateNodeFor::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3468 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      //printf("TemplateNodeFor::render #loopNodes=%d #emptyNodes=%d\n",
      // m_loopNodes.count(),m_emptyNodes.count());
      if (m_expr)
      {
        TemplateVariant v = m_expr->resolve(c);
        if (v.isFunction())
        {
          v = v.call();
        }
        const TemplateListIntfPtr list = v.toList();
        if (list)
        {
          size_t listSize = list->count();
          if (listSize==0) // empty for loop
          {
            m_emptyNodes.render(ts,c);
            return;
          }
          c->push();
          //int index = m_reversed ? list.count() : 0;
          //TemplateVariant v;
          const TemplateVariant *parentLoop = c->getRef("forloop");
          size_t index = m_reversed ? listSize-1 : 0;
          TemplateListIntf::ConstIteratorPtr it = list->createIterator();
          TemplateVariant ve;
          for (m_reversed ? it->toLast() : it->toFirst();
              (it->current(ve));
              m_reversed ? it->toPrev() : it->toNext())
          {
            TemplateStructPtr s = TemplateStruct::alloc();
            s->set("counter0", index);
            s->set("counter", index+1);
            s->set("revcounter", listSize-index);
            s->set("revcounter0", listSize-index-1);
            s->set("first", index==0);
            s->set("last", index==listSize-1);
            s->set("parentloop",parentLoop ? *parentLoop : TemplateVariant());
            c->set("forloop",std::static_pointer_cast<TemplateStructIntf>(s));
            // add variables for this loop to the context
            //obj->addVariableToContext(index,m_vars,c);
            uint vi=0;
            if (m_vars.size()==1) // loop variable represents an item
            {
              c->set(m_vars[vi++],ve);
            }
            else if (m_vars.size()>1 && (ve.isStruct() || ve.isWeakStruct()))
              // loop variables represent elements in a list item
            {
              TemplateStructIntfPtr vs = ve.toStruct();
              if (vs)
              {
                for (uint i=0;i<m_vars.size();i++,vi++)
                {
                  c->set(m_vars[vi],vs->get(m_vars[vi]));
                }
              }
            }
            for (;vi<m_vars.size();vi++)
            {
              c->set(m_vars[vi],TemplateVariant());
            }
            // render all items for this iteration of the loop
            m_loopNodes.render(ts,c);
            if (m_reversed) index--; else index++;
          }
          c->pop();
        }
        else // simple type...
        {
          ci->warn(m_templateName,m_line,"for requires a variable of list type, got type '%s'!",qPrint(v.typeAsString()));
        }
      }
    }
References TemplateStruct::alloc(), c, TemplateVariant::call(), TemplateVariant::isFunction(), TemplateVariant::isStruct(), TemplateVariant::isWeakStruct(), m_emptyNodes, m_expr, TemplateNodeCreator< TemplateNodeFor >::m_line, m_loopNodes, m_reversed, TemplateNodeCreator< TemplateNodeFor >::m_templateName, m_vars, qPrint(), TemplateNodeList::render(), s, TemplateContextImpl::setLocation(), TemplateVariant::toList(), TemplateVariant::toStruct(), TemplateVariant::typeAsString(), and TemplateContextImpl::warn().
Member Data Documentation
m_emptyNodes
TemplateNodeList TemplateNodeFor::m_emptyNodes [private]
Definition at line 3555 of file template.cpp.
Referenced by render(), and TemplateNodeFor().
m_expr
ExprAstPtr TemplateNodeFor::m_expr [private]
Definition at line 3552 of file template.cpp.
Referenced by render(), and TemplateNodeFor().
m_loopNodes
TemplateNodeList TemplateNodeFor::m_loopNodes [private]
Definition at line 3554 of file template.cpp.
Referenced by render(), and TemplateNodeFor().
m_reversed
bool TemplateNodeFor::m_reversed = false [private]
Definition at line 3551 of file template.cpp.
Referenced by render(), and TemplateNodeFor().
m_vars
std::vector< QCString > TemplateNodeFor::m_vars [private]
Definition at line 3553 of file template.cpp.
Referenced by render(), and TemplateNodeFor().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp