IterableStack< T, Container > Class Template Reference
#include <docparser_p.h>
Public Member Functions
auto begin ()
auto end ()
auto begin () const
auto end () const
auto begin ()
auto end ()
auto begin () const
auto end () const
Detailed Description
template<typename T, typename Container = std::deque<T>>
class IterableStack< T, Container >
Definition at line 39 of file docparser_p.h.
Member Function Documentation
begin() [1/4]
template<typename T , typename Container = std::deque<T>>
auto IterableStack< T, Container >::begin () [inline]
Definition at line 46 of file docparser_p.h.
{ return std::begin(c); }
References ghc::filesystem::begin(), and c.
begin() [2/4]
template<typename T , typename Container = std::deque<T>>
auto IterableStack< T, Container >::begin () [inline]
Definition at line 46 of file docparser_p.h.
{ return std::begin(c); }
References ghc::filesystem::begin(), and c.
begin() [3/4]
template<typename T , typename Container = std::deque<T>>
auto IterableStack< T, Container >::begin () const [inline]
Definition at line 49 of file docparser_p.h.
{ return std::begin(c); }
References ghc::filesystem::begin(), and c.
begin() [4/4]
template<typename T , typename Container = std::deque<T>>
auto IterableStack< T, Container >::begin () const [inline]
Definition at line 49 of file docparser_p.h.
{ return std::begin(c); }
References ghc::filesystem::begin(), and c.
end() [1/4]
template<typename T , typename Container = std::deque<T>>
auto IterableStack< T, Container >::end () [inline]
Definition at line 47 of file docparser_p.h.
{ return std::end(c); }
References c, and ghc::filesystem::end().
end() [2/4]
template<typename T , typename Container = std::deque<T>>
auto IterableStack< T, Container >::end () [inline]
Definition at line 47 of file docparser_p.h.
{ return std::end(c); }
References c, and ghc::filesystem::end().
end() [3/4]
template<typename T , typename Container = std::deque<T>>
auto IterableStack< T, Container >::end () const [inline]
Definition at line 50 of file docparser_p.h.
{ return std::end(c); }
References c, and ghc::filesystem::end().
end() [4/4]
template<typename T , typename Container = std::deque<T>>
auto IterableStack< T, Container >::end () const [inline]
Definition at line 50 of file docparser_p.h.
{ return std::end(c); }
References c, and ghc::filesystem::end().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docparser_p.h
doxygen/src/docparser_p.h