SymbolGroupContext::Private Class Reference
Public Member Functions
Private (const SearchIndexList::const_iterator &start, const SearchIndexList::const_iterator &end)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (const SearchIndexList::const_iterator &start, const SearchIndexList::const_iterator &end)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant id () const
TemplateVariant name () const
TemplateVariant symbolList () const
TemplateVariant createSymbolList () const
TemplateVariant id () const
TemplateVariant name () const
TemplateVariant symbolList () const
TemplateVariant createSymbolList () const
Private Attributes
SearchIndexList::const_iterator m_start
SearchIndexList::const_iterator m_end
CachedItem< TemplateVariant, Private,&Private::createSymbolList > m_symbolList
Static Private Attributes
static const PropertyMap< SymbolGroupContext::Private > s_inst
Detailed Description
Definition at line 8545 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
SymbolGroupContext::Private::Private (const SearchIndexList::const_iterator & start, const SearchIndexList::const_iterator & end) [inline]
Definition at line 8548 of file context.cpp.
      : m_start(start), m_end(end) {}
Private() [2/2]
SymbolGroupContext::Private::Private (const SearchIndexList::const_iterator & start, const SearchIndexList::const_iterator & end) [inline]
Definition at line 8548 of file context.cpp.
      : m_start(start), m_end(end) {}
Member Function Documentation
createSymbolList() [1/2]
TemplateVariant SymbolGroupContext::Private::createSymbolList () const [inline], [private]
Definition at line 8563 of file context.cpp.
    {
      return SymbolListContext::alloc(m_start,m_end);
    }
References SymbolListContext::alloc(), m_end, and m_start.
createSymbolList() [2/2]
TemplateVariant SymbolGroupContext::Private::createSymbolList () const [inline], [private]
Definition at line 8563 of file context.cpp.
    {
      return SymbolListContext::alloc(m_start,m_end);
    }
References SymbolListContext::alloc().
fields() [1/2]
StringVector SymbolGroupContext::Private::fields () const [inline]
Definition at line 8553 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector SymbolGroupContext::Private::fields () const [inline]
Definition at line 8553 of file context.cpp.
{ return s_inst.fields(); }
get() [1/2]
TemplateVariant SymbolGroupContext::Private::get (const QCString & n) const [inline]
Definition at line 8552 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant SymbolGroupContext::Private::get (const QCString & n) const [inline]
Definition at line 8552 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
id() [1/2]
TemplateVariant SymbolGroupContext::Private::id () const [inline], [private]
Definition at line 8557 of file context.cpp.
{ return searchId(*m_start); }
References m_start, and searchId().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
TemplateVariant SymbolGroupContext::Private::id () const [inline], [private]
Definition at line 8557 of file context.cpp.
{ return searchId(*m_start); }
References searchId().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
name() [1/2]
TemplateVariant SymbolGroupContext::Private::name () const [inline], [private]
Definition at line 8558 of file context.cpp.
{ return searchName(*m_start); }
References m_start, and searchName().
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
TemplateVariant SymbolGroupContext::Private::name () const [inline], [private]
Definition at line 8558 of file context.cpp.
{ return searchName(*m_start); }
References searchName().
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
symbolList() [1/2]
TemplateVariant SymbolGroupContext::Private::symbolList () const [inline], [private]
Definition at line 8559 of file context.cpp.
{ return m_symbolList.get(this); }
References m_symbolList.
symbolList() [2/2]
TemplateVariant SymbolGroupContext::Private::symbolList () const [inline], [private]
Definition at line 8559 of file context.cpp.
{ return m_symbolList.get(this); }
Member Data Documentation
m_end
SearchIndexList::const_iterator SymbolGroupContext::Private::m_end [private]
Definition at line 8569 of file context.cpp.
Referenced by createSymbolList().
m_start
SearchIndexList::const_iterator SymbolGroupContext::Private::m_start [private]
Definition at line 8568 of file context.cpp.
Referenced by createSymbolList(), id(), and name().
m_symbolList
CachedItem< TemplateVariant, Private,&Private::createSymbolList > SymbolGroupContext::Private::m_symbolList [private]
Definition at line 8570 of file context.cpp.
Referenced by symbolList().
s_inst
const PropertyMap< SymbolGroupContext::Private > SymbolGroupContext::Private::s_inst [static], [private]
Initial value:
{
  { "id", &Private::id },
  { "name", &Private::name },
  { "symbols",&Private::symbolList }
}
Definition at line 8571 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp