FortranCodeParser Class Reference
#include <fortrancode.h>
Classes
struct Private
Public Member Functions
FortranCodeParser (FortranFormat format=FortranFormat_Unknown)
virtual ~FortranCodeParser ()
void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXRefs=TRUE)
void resetCodeParserState ()
FortranCodeParser (FortranFormat format=FortranFormat_Unknown)
virtual ~FortranCodeParser ()
void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXRefs=TRUE)
void resetCodeParserState ()
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 29 of file fortrancode.h.
Constructor & Destructor Documentation
FortranCodeParser() [1/2]
FortranCodeParser::FortranCodeParser (FortranFormat format = FortranFormat_Unknown)
Definition at line 1422 of file fortrancode.l.
                                                         : p(std::make_unique<Private>())
{
  p->format = format;
  fortrancodeYYlex_init_extra(&p->state,&p->yyscanner);
#ifdef FLEX_DEBUG
  fortrancodeYYset_debug(1,p->yyscanner);
#endif
  resetCodeParserState();
}
References p, and resetCodeParserState().
 FortranCodeParser() [1/2]
FortranCodeParser::~FortranCodeParser () [virtual]
Definition at line 1432 of file fortrancode.l.
{
  fortrancodeYYlex_destroy(p->yyscanner);
}
References p.
FortranCodeParser() [2/2]
FortranCodeParser::FortranCodeParser (FortranFormat format = FortranFormat_Unknown)
 FortranCodeParser() [2/2]
virtual FortranCodeParser::~FortranCodeParser () [virtual]
Member Function Documentation
parseCode() [1/2]
void FortranCodeParser::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
Definition at line 1447 of file fortrancode.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  //::parseFortranCode(codeOutIntf,scopeName,input,isExampleBlock,exampleName,
  // fileDef,startLine,endLine,inlineFragment,memberDef,
  // showLineNumbers,searchCtx,collectXRefs,m_format);
  // parseFortranCode(CodeOutputInterface &od,const char *,const QCString &s,
  // bool exBlock, const char *exName,FileDef *fd,
  // int startLine,int endLine,bool inlineFragment,
  // const MemberDef *,bool,const Definition *searchCtx,
  // bool collectXRefs, FortranFormat format)
  if (input.isEmpty()) return;
  printlex(yy_flex_debug, TRUE, __FILE__, fileDef ? qPrint(fileDef->fileName()): NULL);
  yyextra->code = &codeOutIntf;
  yyextra->inputString = input.data();
  yyextra->inputPosition = 0;
  yyextra->fileName = fileDef ? fileDef->fileName():"";
  yyextra->isFixedForm = recognizeFixedForm(input,p->format);
  yyextra->contLineNr = 1;
  yyextra->hasContLine = NULL;
  if (yyextra->isFixedForm)
  {
    checkContLines(yyscanner,yyextra->inputString);
    yyextra->fixedCommentAfter = Config_getInt(FORTRAN_COMMENT_AFTER);
  }
  yyextra->currentFontClass = 0;
  yyextra->insideCodeLine = FALSE;
  yyextra->searchCtx = searchCtx;
  yyextra->collectXRefs = collectXRefs;
  if (startLine!=-1)
    yyextra->yyLineNr = startLine;
  else
    yyextra->yyLineNr = 1;
  if (endLine!=-1)
    yyextra->inputLines = endLine+1;
  else
    yyextra->inputLines = yyextra->yyLineNr + countLines(yyscanner) - 1;
  yyextra->exampleBlock = isExampleBlock;
  yyextra->exampleName = exampleName;
  yyextra->sourceFileDef = fileDef;
  if (isExampleBlock && fileDef==0)
  {
    // create a dummy filedef for the example
    yyextra->sourceFileDef = createFileDef(QCString(),exampleName);
  }
  if (yyextra->sourceFileDef)
  {
    setCurrentDoc(yyscanner,QCString("l00001"));
  }
  yyextra->currentDefinition = 0;
  yyextra->currentMemberDef = 0;
  if (!yyextra->exampleName.isEmpty())
  {
    yyextra->exampleFile = convertNameToFile(yyextra->exampleName+"-example");
  }
  yyextra->includeCodeFragment = inlineFragment;
  startCodeLine(yyscanner);
  fortrancodeYYrestart(0, yyscanner);
  BEGIN(Start);
  fortrancodeYYlex(yyscanner);
  if (yyextra->insideCodeLine)
  {
    endCodeLine(yyscanner);
  }
  if (!fileDef && isExampleBlock && yyextra->sourceFileDef)
  {
    // delete the temporary file definition used for this example
    delete yyextra->sourceFileDef;
    yyextra->sourceFileDef=0;
  }
  if (yyextra->hasContLine) free(yyextra->hasContLine);
  yyextra->hasContLine = NULL;
  // write the tooltips
  yyextra->tooltipManager.writeTooltips(codeOutIntf);
  printlex(yy_flex_debug, FALSE, __FILE__, fileDef ? qPrint(fileDef->fileName()): NULL);
}
References checkContLines(), Config_getInt, convertNameToFile(), countLines(), createFileDef(), QCString::data(), endCodeLine(), FALSE, FileDef::fileName(), if(), QCString::isEmpty(), p, printlex(), qPrint(), recognizeFixedForm(), setCurrentDoc(), startCodeLine(), and TRUE.
parseCode() [2/2]
void FortranCodeParser::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
resetCodeParserState() [1/2]
void FortranCodeParser::resetCodeParserState () [virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Definition at line 1437 of file fortrancode.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->currentDefinition = 0;
  yyextra->currentMemberDef = 0;
  yyextra->currentFontClass = 0;
  yyextra->insideCodeLine = FALSE;
  BEGIN(Start);
}
References FALSE, and p.
Referenced by FortranCodeParser().
resetCodeParserState() [2/2]
void FortranCodeParser::resetCodeParserState () [virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Member Data Documentation
p
std::unique_ptr< Private > FortranCodeParser::p [private]
Definition at line 53 of file fortrancode.h.
Referenced by FortranCodeParser(), parseCode(), resetCodeParserState(), and ~FortranCodeParser().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/fortrancode.h
doxygen/src/fortrancode.h
doxygen/build/doxygen/src/fortrancode.l
doxygen/src/fortrancode.l