RTFDocVisitor Class Reference
Concrete visitor implementation for RTF output.
#include <rtfdocvisitor.h>
Classes
struct RTFListItemInfo
Public Member Functions
RTFDocVisitor (TextStream &t, CodeOutputInterface &ci, const QCString &langExt)
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &s)
void operator() (const DocHtmlList &s)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &t)
void operator() (const DocHtmlCaption &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &)
void operator() (const DocRef &ref)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
RTFDocVisitor (TextStream &t, CodeOutputInterface &ci, const QCString &langExt)
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &s)
void operator() (const DocHtmlList &s)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &t)
void operator() (const DocHtmlCaption &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &)
void operator() (const DocRef &ref)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
Private Member Functions
template<class T >
void visitChildren (const T &t)
void filter (const QCString &str, bool verbatim=FALSE)
void startLink (const QCString &ref, const QCString &file, const QCString &anchor)
void endLink (const QCString &ref)
QCString getStyle (const QCString &name)
int indentLevel () const
void incIndentLevel ()
void decIndentLevel ()
void includePicturePreRTF (const QCString &name, bool isTypeRTF, bool hasCaption, bool inlineImage=FALSE)
void includePicturePostRTF (bool isTypeRTF, bool hasCaption, bool inlineImage=FALSE)
void writeDotFile (const QCString &fileName, bool hasCaption, const QCString &srcFile, int srcLine)
void writeDotFile (const DocDotFile &)
void writeMscFile (const QCString &fileName, bool hasCaption, const QCString &srcFile, int srcLine)
void writeMscFile (const DocMscFile &)
void writeDiaFile (const DocDiaFile &)
void writePlantUMLFile (const QCString &fileName, bool hasCaption)
template<class T >
void visitChildren (const T &t)
void filter (const QCString &str, bool verbatim=FALSE)
void startLink (const QCString &ref, const QCString &file, const QCString &anchor)
void endLink (const QCString &ref)
QCString getStyle (const QCString &name)
int indentLevel () const
void incIndentLevel ()
void decIndentLevel ()
void includePicturePreRTF (const QCString &name, bool isTypeRTF, bool hasCaption, bool inlineImage=FALSE)
void includePicturePostRTF (bool isTypeRTF, bool hasCaption, bool inlineImage=FALSE)
void writeDotFile (const QCString &fileName, bool hasCaption, const QCString &srcFile, int srcLine)
void writeDotFile (const DocDotFile &)
void writeMscFile (const QCString &fileName, bool hasCaption, const QCString &srcFile, int srcLine)
void writeMscFile (const DocMscFile &)
void writeDiaFile (const DocDiaFile &)
void writePlantUMLFile (const QCString &fileName, bool hasCaption)
Private Attributes
TextStream & m_t
CodeOutputInterface & m_ci
bool m_insidePre = false
bool m_hide = false
bool m_lastIsPara = false
QCString m_langExt
int m_indentLevel = 0
RTFListItemInfo m_listItemInfo [maxIndentLevels]
Static Private Attributes
static const int maxIndentLevels = 13
Detailed Description
Concrete visitor implementation for RTF output.
Definition at line 31 of file rtfdocvisitor.h.
Constructor & Destructor Documentation
RTFDocVisitor() [1/2]
RTFDocVisitor::RTFDocVisitor (TextStream & t, CodeOutputInterface & ci, const QCString & langExt)
Definition at line 58 of file rtfdocvisitor.cpp.
  : m_t(t), m_ci(ci), m_langExt(langExt)
{
}
RTFDocVisitor() [2/2]
RTFDocVisitor::RTFDocVisitor (TextStream & t, CodeOutputInterface & ci, const QCString & langExt)
Member Function Documentation
decIndentLevel() [1/2]
void RTFDocVisitor::decIndentLevel () [private]
Definition at line 85 of file rtfdocvisitor.cpp.
{
  if (m_indentLevel>0) m_indentLevel--;
}
References m_indentLevel.
Referenced by operator()().
decIndentLevel() [2/2]
void RTFDocVisitor::decIndentLevel () [private]
endLink() [1/2]
void RTFDocVisitor::endLink (const QCString & ref) [private]
Definition at line 1684 of file rtfdocvisitor.cpp.
{
  if (ref.isEmpty() && Config_getBool(RTF_HYPERLINKS))
  {
    m_t << "}}}";
  }
  else
  {
    m_t << "}";
  }
  m_lastIsPara=FALSE;
}
References Config_getBool, FALSE, QCString::isEmpty(), m_lastIsPara, and m_t.
Referenced by operator()().
endLink() [2/2]
void RTFDocVisitor::endLink (const QCString & ref) [private]
filter() [1/2]
void RTFDocVisitor::filter (const QCString & str, bool verbatim = FALSE) [private]
Definition at line 1625 of file rtfdocvisitor.cpp.
{
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    while (*p)
    {
      c=*p++;
      switch (c)
      {
        case '{': m_t << "\\{"; break;
        case '}': m_t << "\\}"; break;
        case '\\': m_t << "\\\\"; break;
        case '\n': if (verbatim)
                   {
                     m_t << "\\par\n";
                   }
                   else
                   {
                     m_t << '\n';
                   }
                   break;
        default: m_t << c;
      }
    }
  }
}
References c, QCString::data(), QCString::isEmpty(), m_t, and p.
Referenced by operator()().
filter() [2/2]
void RTFDocVisitor::filter (const QCString & str, bool verbatim = FALSE) [private]
getStyle() [1/2]
QCString RTFDocVisitor::getStyle (const QCString & name) [private]
Definition at line 64 of file rtfdocvisitor.cpp.
{
  QCString n = name + QCString().setNum(indentLevel());
  StyleData &sd = rtf_Style[n.str()];
  return sd.reference();
}
References indentLevel(), n, setup::name, StyleData::reference(), rtf_Style, and QCString::setNum().
Referenced by operator()().
getStyle() [2/2]
QCString RTFDocVisitor::getStyle (const QCString & name) [private]
incIndentLevel() [1/2]
void RTFDocVisitor::incIndentLevel () [private]
Definition at line 76 of file rtfdocvisitor.cpp.
{
  m_indentLevel++;
  if (m_indentLevel>=maxIndentLevels)
  {
    err("Maximum indent level (%d) exceeded while generating RTF output!\n",maxIndentLevels-1);
  }
}
References err(), m_indentLevel, and maxIndentLevels.
Referenced by operator()().
incIndentLevel() [2/2]
void RTFDocVisitor::incIndentLevel () [private]
includePicturePostRTF() [1/2]
void RTFDocVisitor::includePicturePostRTF (bool isTypeRTF, bool hasCaption, bool inlineImage = FALSE) [private]
Definition at line 1220 of file rtfdocvisitor.cpp.
{
  if (isTypeRTF)
  {
    if (m_hide) return;
    if (inlineImage)
    {
      if (hasCaption) m_t << " }";
    }
    else
    {
      if (hasCaption)
      {
        m_t << "}\n";
        m_t << "\\par}\n";
      }
      else
      {
        m_t << "}\n";
      }
    }
  }
  else
  {
    m_hide = popHidden();
  }
}
References m_hide, m_t, and DocVisitor::popHidden().
Referenced by operator()().
includePicturePostRTF() [2/2]
void RTFDocVisitor::includePicturePostRTF (bool isTypeRTF, bool hasCaption, bool inlineImage = FALSE) [private]
includePicturePreRTF() [1/2]
void RTFDocVisitor::includePicturePreRTF (const QCString & name, bool isTypeRTF, bool hasCaption, bool inlineImage = FALSE) [private]
Definition at line 1183 of file rtfdocvisitor.cpp.
{
  if (isTypeRTF)
  {
    if (!inlineImage)
    {
      m_t << "\\par\n";
      m_t << "{\n";
      m_t << rtf_Style_Reset << "\n";
      if (hasCaption || m_lastIsPara) m_t << "\\par\n";
      m_t << "\\pard \\qc ";
    }
    m_t << "{ \\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"";
    m_t << name;
    m_t << "\" \\\\d \\\\*MERGEFORMAT}{\\fldrslt Image}}\n";
    if (!inlineImage)
    {
      m_t << "\\par\n";
      if (hasCaption)
      {
         m_t << "\\pard \\qc \\b";
         m_t << "{Image \\field\\flddirty{\\*\\fldinst { SEQ Image \\\\*Arabic }}{\\fldrslt {\\noproof 1}} ";
      }
      m_lastIsPara=TRUE;
    }
    else
    {
      if (hasCaption) m_t << "{\\comment "; // to prevent caption to be shown
    }
  }
  else // other format -> skip
  {
    pushHidden(m_hide);
    m_hide=TRUE;
  }
}
References m_hide, m_lastIsPara, m_t, setup::name, DocVisitor::pushHidden(), rtf_Style_Reset, and TRUE.
Referenced by operator()(), writeDiaFile(), writeDotFile(), writeMscFile(), and writePlantUMLFile().
includePicturePreRTF() [2/2]
void RTFDocVisitor::includePicturePreRTF (const QCString & name, bool isTypeRTF, bool hasCaption, bool inlineImage = FALSE) [private]
indentLevel() [1/2]
int RTFDocVisitor::indentLevel () const [private]
Definition at line 71 of file rtfdocvisitor.cpp.
{
  return std::min(m_indentLevel,maxIndentLevels-1);
}
References m_indentLevel, and maxIndentLevels.
Referenced by getStyle(), and operator()().
indentLevel() [2/2]
int RTFDocVisitor::indentLevel () const [private]
operator()() [1/114]
void RTFDocVisitor::operator() (const DocAnchor & anc)
Definition at line 414 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocAnchor)}\n");
  QCString anchor;
  if (!anc.file().isEmpty())
  {
    anchor+=stripPath(anc.file());
  }
  if (!anc.file().isEmpty() && !anc.anchor().isEmpty())
  {
    anchor+="_";
  }
  if (!anc.anchor().isEmpty())
  {
    anchor+=anc.anchor();
  }
  m_t << "{\\bkmkstart " << rtfFormatBmkStr(anchor) << "}\n";
  m_t << "{\\bkmkend " << rtfFormatBmkStr(anchor) << "}\n";
  m_lastIsPara=FALSE;
}
References DocAnchor::anchor(), DBG_RTF, FALSE, DocAnchor::file(), QCString::isEmpty(), m_hide, m_lastIsPara, m_t, rtfFormatBmkStr(), and stripPath().
operator()() [2/114]
void RTFDocVisitor::operator() (const DocAnchor &)
operator()() [3/114]
void RTFDocVisitor::operator() (const DocAutoList & l)
Definition at line 672 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocAutoList &)}\n");
  m_t << "{\n";
  int level = indentLevel();
  m_listItemInfo[level].isEnum = l.isEnumList();
  m_listItemInfo[level].type = '1';
  m_listItemInfo[level].number = 1;
  m_lastIsPara=FALSE;
  visitChildren(l);
  if (!m_lastIsPara) m_t << "\\par";
  m_t << "}\n";
  m_lastIsPara=TRUE;
  if (indentLevel()==0) m_t << "\\par\n";
}
References DBG_RTF, FALSE, indentLevel(), RTFDocVisitor::RTFListItemInfo::isEnum, DocAutoList::isEnumList(), level, m_hide, m_lastIsPara, m_listItemInfo, m_t, RTFDocVisitor::RTFListItemInfo::number, TRUE, RTFDocVisitor::RTFListItemInfo::type, and visitChildren().
operator()() [4/114]
void RTFDocVisitor::operator() (const DocAutoList &)
operator()() [5/114]
void RTFDocVisitor::operator() (const DocAutoListItem & li)
Definition at line 689 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocAutoListItem &)}\n");
  if (!m_lastIsPara) m_t << "\\par\n";
  m_t << rtf_Style_Reset;
  int level = indentLevel();
  if (m_listItemInfo[level].isEnum)
  {
    m_t << getStyle("ListEnum") << "\n";
    m_t << m_listItemInfo[level].number << ".\\tab ";
    m_listItemInfo[level].number++;
  }
  else
  {
    m_t << getStyle("ListBullet") << "\n";
  }
  incIndentLevel();
  m_lastIsPara=FALSE;
  visitChildren(li);
  decIndentLevel();
}
References DBG_RTF, decIndentLevel(), FALSE, getStyle(), incIndentLevel(), indentLevel(), level, m_hide, m_lastIsPara, m_listItemInfo, m_t, RTFDocVisitor::RTFListItemInfo::number, rtf_Style_Reset, and visitChildren().
operator()() [6/114]
void RTFDocVisitor::operator() (const DocAutoListItem &)
operator()() [7/114]
void RTFDocVisitor::operator() (const DocCite & cite)
Definition at line 644 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocCite &)}\n");
  if (!cite.file().isEmpty())
  {
    startLink(cite.ref(),cite.file(),cite.anchor());
  }
  else
  {
    m_t << "{\\b ";
  }
  filter(cite.text());
  if (!cite.file().isEmpty())
  {
    endLink(cite.ref());
  }
  else
  {
    m_t << "}";
  }
}
References DocCite::anchor(), DBG_RTF, endLink(), DocCite::file(), filter(), QCString::isEmpty(), m_hide, m_t, DocCite::ref(), startLink(), and DocCite::text().
operator()() [8/114]
void RTFDocVisitor::operator() (const DocCite &)
operator()() [9/114]
void RTFDocVisitor::operator() (const DocDiaFile & df)
Definition at line 1274 of file rtfdocvisitor.cpp.
{
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocDiaFile &)}\n");
  if (!Config_getBool(DOT_CLEANUP)) copyFile(df.file(),Config_getString(RTF_OUTPUT)+"/"+stripPath(df.file()));
  writeDiaFile(df);
  visitChildren(df);
  includePicturePostRTF(true, df.hasCaption());
}
References Config_getBool, Config_getString, copyFile(), DBG_RTF, DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), includePicturePostRTF(), stripPath(), visitChildren(), and writeDiaFile().
operator()() [10/114]
void RTFDocVisitor::operator() (const DocDiaFile &)
operator()() [11/114]
void RTFDocVisitor::operator() (const DocDotFile & df)
Definition at line 1257 of file rtfdocvisitor.cpp.
{
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocDotFile &)}\n");
  if (!Config_getBool(DOT_CLEANUP)) copyFile(df.file(),Config_getString(RTF_OUTPUT)+"/"+stripPath(df.file()));
  writeDotFile(df);
  visitChildren(df);
  includePicturePostRTF(true, df.hasCaption());
}
References Config_getBool, Config_getString, copyFile(), DBG_RTF, DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), includePicturePostRTF(), stripPath(), visitChildren(), and writeDotFile().
operator()() [12/114]
void RTFDocVisitor::operator() (const DocDotFile &)
operator()() [13/114]
void RTFDocVisitor::operator() (const DocEmoji & s)
Definition at line 143 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocEmoji)}\n");
  const char *res = EmojiEntityMapper::instance()->unicode(s.index());
  if (res)
  {
    const char *p = res;
    int val = 0;
    int val1 = 0;
    while (*p)
    {
      switch(*p)
      {
        case '&': case '#': case 'x':
          break;
        case ';':
      val1 = val;
      val = 0xd800 + ((val1 - 0x10000) & 0xffc00) / 0x400 - 0x10000;
          m_t << "\\u" << val << "?";
          val = 0xdC00 + ((val1 - 0x10000) & 0x3ff) - 0x10000 ;
          m_t << "\\u" << val << "?";
          val = 0;
          break;
        case '0': case '1': case '2': case '3': case '4':
        case '5': case '6': case '7': case '8': case '9':
          val = val * 16 + *p - '0';
          break;
        case 'a': case 'b': case 'c': case 'd': case 'e': case 'f':
          val = val * 16 + *p - 'a' + 10;
          break;
      }
      p++;
    }
  }
  else
  {
    m_t << s.name();
  }
  m_lastIsPara=FALSE;
}
References DBG_RTF, FALSE, EmojiEntityMapper::instance(), m_hide, m_lastIsPara, m_t, p, s, EmojiEntityMapper::unicode(), and testsqlite3::val.
operator()() [14/114]
void RTFDocVisitor::operator() (const DocEmoji &)
operator()() [15/114]
void RTFDocVisitor::operator() (const DocFormula & f)
Definition at line 611 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocFormula)}\n");
  bool bDisplay = !f.isInline();
  if (bDisplay)
  {
    m_t << "\\par";
    m_t << "{";
    m_t << "\\pard\\plain";
    m_t << "\\pard";
    m_t << "\\qc";
  }
  m_t << "{ \\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"" << f.relPath() << f.name() << ".png\" \\\\d \\\\*MERGEFORMAT}{\\fldrslt Image}}";
  if (bDisplay)
  {
    m_t << "\\par}";
  }
  m_lastIsPara=FALSE;
}
References DBG_RTF, f, FALSE, m_hide, m_lastIsPara, and m_t.
operator()() [16/114]
void RTFDocVisitor::operator() (const DocFormula &)
operator()() [17/114]
void RTFDocVisitor::operator() (const DocHorRuler &)
Definition at line 223 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocHorRuler)}\n");
  m_t << "{\\pard\\widctlpar\\brdrb\\brdrs\\brdrw5\\brsp20 \\adjustright \\par}\n";
  m_lastIsPara=TRUE;
}
References DBG_RTF, m_hide, m_lastIsPara, m_t, and TRUE.
operator()() [18/114]
void RTFDocVisitor::operator() (const DocHorRuler &)
operator()() [19/114]
void RTFDocVisitor::operator() (const DocHRef & href)
Definition at line 1082 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHRef &)}\n");
  if (Config_getBool(RTF_HYPERLINKS))
  {
    if (href.url().startsWith("#"))
    {
      // when starting with # so a local link
      QCString cite;
      cite = href.file() + "_" + href.url().right(href.url().length()-1);
      m_t << "{\\field "
               "{\\*\\fldinst "
                 "{ HYPERLINK \\\\l \"" << rtfFormatBmkStr(cite) << "\" "
                 "}{}"
               "}"
               "{\\fldrslt "
                 "{\\cs37\\ul\\cf2 ";
    }
    else
    {
      m_t << "{\\field "
                 "{\\*\\fldinst "
                 "{ HYPERLINK \"" << href.url() << "\" "
                 "}{}"
               "}"
               "{\\fldrslt "
                 "{\\cs37\\ul\\cf2 ";
    }
  }
  else
  {
    m_t << "{\\f2 ";
  }
  m_lastIsPara=FALSE;
  visitChildren(href);
  if (Config_getBool(RTF_HYPERLINKS))
  {
    m_t << "}"
             "}"
           "}";
  }
  else
  {
    m_t << "}";
  }
  m_lastIsPara=FALSE;
}
References Config_getBool, DBG_RTF, FALSE, DocHRef::file(), QCString::length(), m_hide, m_lastIsPara, m_t, QCString::right(), rtfFormatBmkStr(), QCString::startsWith(), DocHRef::url(), and visitChildren().
operator()() [20/114]
void RTFDocVisitor::operator() (const DocHRef &)
operator()() [21/114]
void RTFDocVisitor::operator() (const DocHtmlBlockQuote & q)
Definition at line 1592 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHtmlBlockQuote &)}\n");
  if (!m_lastIsPara) m_t << "\\par\n";
  m_t << "{"; // start desc
  incIndentLevel();
  m_t << rtf_Style_Reset << getStyle("DescContinue");
  visitChildren(q);
  if (!m_lastIsPara) m_t << "\\par\n";
  decIndentLevel();
  m_t << "}"; // end desc
  m_lastIsPara=TRUE;
}
References DBG_RTF, decIndentLevel(), getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, rtf_Style_Reset, TRUE, and visitChildren().
operator()() [22/114]
void RTFDocVisitor::operator() (const DocHtmlBlockQuote &)
operator()() [23/114]
void RTFDocVisitor::operator() (const DocHtmlCaption & c)
Definition at line 1024 of file rtfdocvisitor.cpp.
{
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHtmlCaption &)}\n");
  visitChildren(c);
  m_t << "}\n\\par\n";
}
References c, DBG_RTF, m_t, and visitChildren().
operator()() [24/114]
void RTFDocVisitor::operator() (const DocHtmlCaption &)
operator()() [25/114]
void RTFDocVisitor::operator() (const DocHtmlCell & c)
Definition at line 1065 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHtmlCell &)}\n");
  m_t << "{" << align(c);
  m_lastIsPara=FALSE;
  visitChildren(c);
  m_t << "\\cell }";
  m_lastIsPara=FALSE;
}
References align(), c, DBG_RTF, FALSE, m_hide, m_lastIsPara, m_t, and visitChildren().
operator()() [26/114]
void RTFDocVisitor::operator() (const DocHtmlCell &)
operator()() [27/114]
void RTFDocVisitor::operator() (const DocHtmlDescData & dd)
Definition at line 987 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHtmlDescData &)}\n");
  incIndentLevel();
  m_t << "{" << rtf_Style_Reset << getStyle("DescContinue");
  visitChildren(dd);
  m_t << "\\par";
  m_t << "}\n";
  decIndentLevel();
  m_lastIsPara=TRUE;
}
References DBG_RTF, decIndentLevel(), getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, rtf_Style_Reset, TRUE, and visitChildren().
operator()() [28/114]
void RTFDocVisitor::operator() (const DocHtmlDescData &)
operator()() [29/114]
void RTFDocVisitor::operator() (const DocHtmlDescList & dl)
Definition at line 960 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHtmlDescList &)}\n");
  //m_t << "{\n";
  //m_t << rtf_Style_Reset << getStyle("ListContinue");
  //m_lastIsPara=FALSE;
  visitChildren(dl);
  //m_t << "}\n";
  //m_t << "\\par\n";
  //m_lastIsPara=TRUE;
}
References DBG_RTF, m_hide, and visitChildren().
operator()() [30/114]
void RTFDocVisitor::operator() (const DocHtmlDescList &)
operator()() [31/114]
void RTFDocVisitor::operator() (const DocHtmlDescTitle & dt)
Definition at line 973 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHtmlDescTitle &)}\n");
  //m_t << "\\par\n";
  //m_t << "{\\b ";
  m_t << "{" << rtf_Style["Heading5"].reference() << "\n";
  m_lastIsPara=FALSE;
  visitChildren(dt);
  m_t << "\\par\n";
  m_t << "}\n";
  m_lastIsPara=TRUE;
}
References DBG_RTF, FALSE, m_hide, m_lastIsPara, m_t, rtf_Style, TRUE, and visitChildren().
operator()() [32/114]
void RTFDocVisitor::operator() (const DocHtmlDescTitle &)
operator()() [33/114]
void RTFDocVisitor::operator() (const DocHtmlDetails & d)
Definition at line 1139 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHtmlDetails &)}\n");
  if (!m_lastIsPara) m_t << "\\par\n";
  auto summary = d.summary();
  if (summary)
  {
    std::visit(*this,*summary);
    m_t << "{"; // start desc
    incIndentLevel();
    m_t << rtf_Style_Reset << getStyle("DescContinue");
  }
  visitChildren(d);
  if (!m_lastIsPara) m_t << "\\par\n";
  if (summary)
  {
    decIndentLevel();
    m_t << "}"; // end desc
  }
  m_lastIsPara=TRUE;
}
References DBG_RTF, decIndentLevel(), getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, rtf_Style_Reset, DocHtmlDetails::summary(), TRUE, and visitChildren().
operator()() [34/114]
void RTFDocVisitor::operator() (const DocHtmlDetails &)
operator()() [35/114]
void RTFDocVisitor::operator() (const DocHtmlHeader & header)
Definition at line 1162 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHtmlHeader &)}\n");
  m_t << "{" // start section
      << rtf_Style_Reset;
  QCString heading;
  int level = std::min(header.level(),5);
  heading.sprintf("Heading%d",level);
  // set style
  m_t << rtf_Style[heading.str()].reference();
  // make open table of contents entry that will be closed in visitPost method
  m_t << "{\\tc\\tcl" << level << " ";
  m_lastIsPara=FALSE;
  visitChildren(header);
  // close open table of contents entry
  m_t << "} \\par";
  m_t << "}\n"; // end section
  m_lastIsPara=TRUE;
}
References DBG_RTF, FALSE, level, DocHtmlHeader::level(), m_hide, m_lastIsPara, m_t, rtf_Style, rtf_Style_Reset, QCString::sprintf(), QCString::str(), TRUE, and visitChildren().
operator()() [36/114]
void RTFDocVisitor::operator() (const DocHtmlHeader &)
operator()() [37/114]
void RTFDocVisitor::operator() (const DocHtmlList & s)
Definition at line 878 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHtmlList &)}\n");
  m_t << "{\n";
  int level = indentLevel();
  m_listItemInfo[level].isEnum = l.type()==DocHtmlList::Ordered;
  m_listItemInfo[level].number = 1;
  m_listItemInfo[level].type = '1';
  for (const auto &opt : l.attribs())
  {
    if (opt.name=="type")
    {
      m_listItemInfo[level].type = opt.value[0];
    }
    if (opt.name=="start")
    {
      bool ok;
      int val = opt.value.toInt(&ok);
      if (ok) m_listItemInfo[level].number = val;
    }
  }
  m_lastIsPara=FALSE;
  visitChildren(l);
  m_t << "\\par" << "}\n";
  m_lastIsPara=TRUE;
}
References DocHtmlList::attribs(), DBG_RTF, FALSE, indentLevel(), RTFDocVisitor::RTFListItemInfo::isEnum, level, m_hide, m_lastIsPara, m_listItemInfo, m_t, RTFDocVisitor::RTFListItemInfo::number, DocHtmlList::Ordered, TRUE, DocHtmlList::type(), RTFDocVisitor::RTFListItemInfo::type, testsqlite3::val, and visitChildren().
operator()() [38/114]
void RTFDocVisitor::operator() (const DocHtmlList & s)
operator()() [39/114]
void RTFDocVisitor::operator() (const DocHtmlListItem & l)
Definition at line 906 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHtmlListItem &)}\n");
  m_t << "\\par\n";
  m_t << rtf_Style_Reset;
  int level = indentLevel();
  if (m_listItemInfo[level].isEnum)
  {
    for (const auto &opt : l.attribs())
    {
      if (opt.name=="value")
      {
        bool ok;
        int val = opt.value.toInt(&ok);
        if (ok) m_listItemInfo[level].number = val;
      }
    }
    m_t << getStyle("ListEnum") << "\n";
    switch (m_listItemInfo[level].type)
    {
      case '1':
        m_t << m_listItemInfo[level].number;
        break;
      case 'a':
        m_t << integerToAlpha(m_listItemInfo[level].number,false);
        break;
      case 'A':
        m_t << integerToAlpha(m_listItemInfo[level].number);
        break;
      case 'i':
        m_t << integerToRoman(m_listItemInfo[level].number,false);
        break;
      case 'I':
        m_t << integerToRoman(m_listItemInfo[level].number);
        break;
      default:
        m_t << m_listItemInfo[level].number;
        break;
    }
    m_t << ".\\tab ";
    m_listItemInfo[level].number++;
  }
  else
  {
    m_t << getStyle("ListBullet") << "\n";
  }
  incIndentLevel();
  m_lastIsPara=FALSE;
  visitChildren(l);
  decIndentLevel();
  DBG_RTF("{\\comment RTFDocVisitor::visitPost(DocHtmlListItem)}\n");
}
References DocHtmlListItem::attribs(), DBG_RTF, decIndentLevel(), FALSE, getStyle(), incIndentLevel(), indentLevel(), integerToAlpha(), integerToRoman(), level, m_hide, m_lastIsPara, m_listItemInfo, m_t, RTFDocVisitor::RTFListItemInfo::number, rtf_Style_Reset, testsqlite3::val, and visitChildren().
operator()() [40/114]
void RTFDocVisitor::operator() (const DocHtmlListItem &)
operator()() [41/114]
void RTFDocVisitor::operator() (const DocHtmlRow & r)
Definition at line 1031 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHtmlRow &)}\n");
  size_t i,columnWidth=r.numCells()>0 ? rtf_pageWidth/r.numCells() : 10;
  m_t << "\\trowd \\trgaph108\\trleft-108"
         "\\trbrdrt\\brdrs\\brdrw10 "
         "\\trbrdrl\\brdrs\\brdrw10 "
         "\\trbrdrb\\brdrs\\brdrw10 "
         "\\trbrdrr\\brdrs\\brdrw10 "
         "\\trbrdrh\\brdrs\\brdrw10 "
         "\\trbrdrv\\brdrs\\brdrw10 \n";
  for (i=0;i<r.numCells();i++)
  {
    if (r.isHeading())
    {
      m_t << "\\clcbpat16"; // set cell shading to light grey (color 16 in the clut)
    }
    m_t << "\\clvertalt\\clbrdrt\\brdrs\\brdrw10 "
           "\\clbrdrl\\brdrs\\brdrw10 "
           "\\clbrdrb\\brdrs\\brdrw10 "
           "\\clbrdrr \\brdrs\\brdrw10 "
           "\\cltxlrtb "
           "\\cellx" << ((i+1)*columnWidth) << "\n";
  }
  m_t << "\\pard \\widctlpar\\intbl\\adjustright\n";
  m_lastIsPara=FALSE;
  visitChildren(r);
  m_t << "\n";
  m_t << "\\pard \\widctlpar\\intbl\\adjustright\n";
  m_t << "{\\row }\n";
  m_lastIsPara=FALSE;
}
References DBG_RTF, FALSE, m_hide, m_lastIsPara, m_t, r, rtf_pageWidth, and visitChildren().
operator()() [42/114]
void RTFDocVisitor::operator() (const DocHtmlRow &)
operator()() [43/114]
void RTFDocVisitor::operator() (const DocHtmlSummary & s)
Definition at line 1131 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "{\\b ";
  visitChildren(s);
  m_t << "}\\par ";
}
References m_hide, m_t, s, and visitChildren().
operator()() [44/114]
void RTFDocVisitor::operator() (const DocHtmlSummary &)
operator()() [45/114]
void RTFDocVisitor::operator() (const DocHtmlTable & t)
Definition at line 1000 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocHtmlTable &)}\n");
  if (!m_lastIsPara) m_t << "\\par\n";
  m_lastIsPara=TRUE;
  if (t.caption())
  {
    const DocHtmlCaption &c = std::get<DocHtmlCaption>(*t.caption());
    m_t << "\\pard \\qc \\b";
    if (!c.file().isEmpty())
    {
      m_t << "{\\bkmkstart " << rtfFormatBmkStr(stripPath(c.file())+"_"+c.anchor()) << "}\n";
      m_t << "{\\bkmkend " << rtfFormatBmkStr(stripPath(c.file())+"_"+c.anchor()) << "}\n";
    }
    m_t << "{Table \\field\\flddirty{\\*\\fldinst { SEQ Table \\\\*Arabic }}{\\fldrslt {\\noproof 1}} ";
    std::visit(*this,*t.caption());
  }
  visitChildren(t);
  m_t << "\\pard\\plain\n";
  m_t << "\\par\n";
  m_lastIsPara=TRUE;
}
References c, DocHtmlTable::caption(), DBG_RTF, m_hide, m_lastIsPara, m_t, rtfFormatBmkStr(), stripPath(), TRUE, and visitChildren().
operator()() [46/114]
void RTFDocVisitor::operator() (const DocHtmlTable & t)
operator()() [47/114]
void RTFDocVisitor::operator() (const DocImage & img)
Definition at line 1248 of file rtfdocvisitor.cpp.
{
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocImage &)}\n");
  includePicturePreRTF(img.name(), img.type()==DocImage::Rtf, img.hasCaption(), img.isInlineImage());
  visitChildren(img);
  includePicturePostRTF(img.type()==DocImage::Rtf, img.hasCaption(), img.isInlineImage());
}
References DBG_RTF, DocImage::hasCaption(), includePicturePostRTF(), includePicturePreRTF(), DocImage::isInlineImage(), DocImage::name(), DocImage::Rtf, DocImage::type(), and visitChildren().
operator()() [48/114]
void RTFDocVisitor::operator() (const DocImage &)
operator()() [49/114]
void RTFDocVisitor::operator() (const DocInclude & inc)
Definition at line 436 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  SrcLangExt langExt = getLanguageFromFileName(inc.extension());
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocInclude)}\n");
  switch(inc.type())
  {
     case DocInclude::IncWithLines:
      {
         m_t << "{\n";
         m_t << "\\par\n";
         m_t << rtf_Style_Reset << getStyle("CodeExample");
         FileInfo cfi(inc.file().str());
         FileDef *fd = createFileDef(cfi.dirPath(), cfi.fileName());
         getCodeParser(inc.extension()).parseCode(m_ci,inc.context(),
                                           inc.text(),
                                           langExt,
                                           inc.isExample(),
                                           inc.exampleFile(),
                                           fd, // fileDef,
                                           -1, // start line
                                           -1, // end line
                                           FALSE, // inline fragment
                                           0, // memberDef
                                           TRUE // show line numbers
                       );
         delete fd;
         m_t << "\\par";
         m_t << "}\n";
      }
      break;
    case DocInclude::Include:
      m_t << "{\n";
      m_t << "\\par\n";
      m_t << rtf_Style_Reset << getStyle("CodeExample");
      getCodeParser(inc.extension()).parseCode(m_ci,inc.context(),
                                        inc.text(),langExt,inc.isExample(),
                                        inc.exampleFile(),
                                        0, // fileDef
                                        -1, // startLine
                                        -1, // endLine
                                        TRUE, // inlineFragment
                                        0, // memberDef
                                        FALSE // show line numbers
                       );
      m_t << "\\par";
      m_t << "}\n";
      break;
    case DocInclude::DontInclude:
    case DocInclude::DontIncWithLines:
    case DocInclude::HtmlInclude:
    case DocInclude::LatexInclude:
    case DocInclude::ManInclude:
    case DocInclude::XmlInclude:
    case DocInclude::DocbookInclude:
      break;
    case DocInclude::RtfInclude:
      m_t << inc.text();
      break;
    case DocInclude::VerbInclude:
      m_t << "{\n";
      m_t << "\\par\n";
      m_t << rtf_Style_Reset << getStyle("CodeExample");
      filter(inc.text());
      m_t << "\\par";
      m_t << "}\n";
      break;
    case DocInclude::Snippet:
      m_t << "{\n";
      if (!m_lastIsPara) m_t << "\\par\n";
      m_t << rtf_Style_Reset << getStyle("CodeExample");
      getCodeParser(inc.extension()).parseCode(m_ci,
                                        inc.context(),
                                        extractBlock(inc.text(),inc.blockId()),
                                        langExt,
                                        inc.isExample(),
                                        inc.exampleFile()
                                       );
      m_t << "}";
      break;
    case DocInclude::SnipWithLines:
      {
         FileInfo cfi(inc.file().str());
         FileDef *fd = createFileDef(cfi.dirPath(), cfi.fileName());
         m_t << "{\n";
         if (!m_lastIsPara) m_t << "\\par\n";
         m_t << rtf_Style_Reset << getStyle("CodeExample");
         getCodeParser(inc.extension()).parseCode(m_ci,
                                           inc.context(),
                                           extractBlock(inc.text(),inc.blockId()),
                                           langExt,
                                           inc.isExample(),
                                           inc.exampleFile(),
                                           fd,
                                           lineBlock(inc.text(),inc.blockId()),
                                           -1, // endLine
                                           FALSE, // inlineFragment
                                           0, // memberDef
                                           TRUE // show line number
                                          );
         delete fd;
         m_t << "}";
      }
      break;
    case DocInclude::SnippetDoc:
    case DocInclude::IncludeDoc:
      err("Internal inconsistency: found switch SnippetDoc / IncludeDoc in file: %s"
          "Please create a bug report\n",__FILE__);
      break;
  }
  m_lastIsPara=TRUE;
}
References DocInclude::blockId(), DocInclude::context(), createFileDef(), DBG_RTF, FileInfo::dirPath(), DocInclude::DocbookInclude, DocInclude::DontInclude, DocInclude::DontIncWithLines, err(), DocInclude::exampleFile(), DocInclude::extension(), extractBlock(), FALSE, DocInclude::file(), FileInfo::fileName(), filter(), DocVisitor::getCodeParser(), getLanguageFromFileName(), getStyle(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isExample(), DocInclude::LatexInclude, lineBlock(), m_ci, m_hide, m_lastIsPara, m_t, DocInclude::ManInclude, CodeParserInterface::parseCode(), rtf_Style_Reset, DocInclude::RtfInclude, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, QCString::str(), DocInclude::text(), TRUE, DocInclude::type(), DocInclude::VerbInclude, and DocInclude::XmlInclude.
operator()() [50/114]
void RTFDocVisitor::operator() (const DocInclude &)
operator()() [51/114]
void RTFDocVisitor::operator() (const DocIncOperator & op)
Definition at line 549 of file rtfdocvisitor.cpp.
{
  //printf("DocIncOperator: type=%d first=%d, last=%d text='%s'\n",
  // op.type(),op.isFirst(),op.isLast(),qPrint(op.text()));
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocIncOperator)}\n");
  QCString locLangExt = getFileNameExtension(op.includeFileName());
  if (locLangExt.isEmpty()) locLangExt = m_langExt;
  SrcLangExt langExt = getLanguageFromFileName(locLangExt);
  if (op.isFirst())
  {
    if (!m_hide)
    {
      m_t << "{\n";
      m_t << "\\par\n";
      m_t << rtf_Style_Reset << getStyle("CodeExample");
    }
    pushHidden(m_hide);
    m_hide = TRUE;
  }
  if (op.type()!=DocIncOperator::Skip)
  {
    m_hide = popHidden();
    if (!m_hide)
    {
      FileDef *fd = 0;
      if (!op.includeFileName().isEmpty())
      {
        FileInfo cfi(op.includeFileName().str());
        fd = createFileDef(cfi.dirPath(), cfi.fileName());
      }
      getCodeParser(locLangExt).parseCode(m_ci,op.context(),op.text(),langExt,
                                        op.isExample(),op.exampleFile(),
                                        fd, // fileDef
                                        op.line(), // startLine
                                        -1, // endLine
                                        FALSE, // inline fragment
                                        0, // memberDef
                                        op.showLineNo() // show line numbers
                                       );
      if (fd) delete fd;
    }
    pushHidden(m_hide);
    m_hide=TRUE;
  }
  if (op.isLast())
  {
    m_hide = popHidden();
    if (!m_hide)
    {
      m_t << "\\par";
      m_t << "}\n";
    }
    m_lastIsPara=TRUE;
  }
  else
  {
    if (!m_hide) m_t << "\n";
    m_lastIsPara=FALSE;
  }
}
References DocIncOperator::context(), createFileDef(), DBG_RTF, FileInfo::dirPath(), DocIncOperator::exampleFile(), FALSE, FileInfo::fileName(), DocVisitor::getCodeParser(), getFileNameExtension(), getLanguageFromFileName(), getStyle(), DocIncOperator::includeFileName(), QCString::isEmpty(), DocIncOperator::isExample(), DocIncOperator::isFirst(), DocIncOperator::isLast(), DocIncOperator::line(), m_ci, m_hide, m_langExt, m_lastIsPara, m_t, CodeParserInterface::parseCode(), DocVisitor::popHidden(), DocVisitor::pushHidden(), rtf_Style_Reset, DocIncOperator::showLineNo(), DocIncOperator::Skip, QCString::str(), DocIncOperator::text(), TRUE, and DocIncOperator::type().
operator()() [52/114]
void RTFDocVisitor::operator() (const DocIncOperator &)
operator()() [53/114]
void RTFDocVisitor::operator() (const DocIndexEntry & i)
Definition at line 632 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocIndexEntry)}\n");
  m_t << "{\\xe \\v " << i.entry() << "}\n";
  m_lastIsPara=FALSE;
}
References DBG_RTF, DocIndexEntry::entry(), FALSE, m_hide, m_lastIsPara, and m_t.
operator()() [54/114]
void RTFDocVisitor::operator() (const DocIndexEntry &)
operator()() [55/114]
void RTFDocVisitor::operator() (const DocInternal & i)
Definition at line 1076 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(i);
}
References m_hide, and visitChildren().
operator()() [56/114]
void RTFDocVisitor::operator() (const DocInternal &)
operator()() [57/114]
void RTFDocVisitor::operator() (const DocInternalRef & ref)
Definition at line 1575 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocInternalRef &)}\n");
  startLink("",ref.file(),ref.anchor());
  visitChildren(ref);
  endLink("");
  m_t << " ";
}
References DocInternalRef::anchor(), DBG_RTF, endLink(), DocInternalRef::file(), m_hide, m_t, startLink(), and visitChildren().
operator()() [58/114]
void RTFDocVisitor::operator() (const DocInternalRef &)
operator()() [59/114]
void RTFDocVisitor::operator() (const DocLineBreak &)
Definition at line 215 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocLineBreak)}\n");
  m_t << "\\par\n";
  m_lastIsPara=TRUE;
}
References DBG_RTF, m_hide, m_lastIsPara, m_t, and TRUE.
operator()() [60/114]
void RTFDocVisitor::operator() (const DocLineBreak &)
operator()() [61/114]
void RTFDocVisitor::operator() (const DocLink & lnk)
Definition at line 1283 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocLink &)}\n");
  startLink(lnk.ref(),lnk.file(),lnk.anchor());
  visitChildren(lnk);
  endLink(lnk.ref());
}
References DocLink::anchor(), DBG_RTF, endLink(), DocLink::file(), m_hide, DocLink::ref(), startLink(), and visitChildren().
operator()() [62/114]
void RTFDocVisitor::operator() (const DocLink &)
operator()() [63/114]
void RTFDocVisitor::operator() (const DocLinkedWord & w)
Definition at line 102 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocLinkedWord)}\n");
  startLink(w.ref(),w.file(),w.anchor());
  filter(w.word());
  endLink(w.ref());
  m_lastIsPara=FALSE;
}
References DBG_RTF, endLink(), FALSE, filter(), m_hide, m_lastIsPara, startLink(), and w.
operator()() [64/114]
void RTFDocVisitor::operator() (const DocLinkedWord &)
operator()() [65/114]
void RTFDocVisitor::operator() (const DocMscFile & df)
Definition at line 1265 of file rtfdocvisitor.cpp.
{
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocMscFile &)}\n");
  if (!Config_getBool(DOT_CLEANUP)) copyFile(df.file(),Config_getString(RTF_OUTPUT)+"/"+stripPath(df.file()));
  writeMscFile(df);
  visitChildren(df);
  includePicturePostRTF(true, df.hasCaption());
}
References Config_getBool, Config_getString, copyFile(), DBG_RTF, DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), includePicturePostRTF(), stripPath(), visitChildren(), and writeMscFile().
operator()() [66/114]
void RTFDocVisitor::operator() (const DocMscFile &)
operator()() [67/114]
void RTFDocVisitor::operator() (const DocPara & p)
Definition at line 712 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocPara &)}\n");
  visitChildren(p);
  if (!m_lastIsPara &&
      !p.isLast() && // omit <p> for last paragraph
      !(p.parent() && // and for parameters & sections
        std::get_if<DocParamSect>(p.parent())
       )
     )
  {
    m_t << "\\par\n";
    m_lastIsPara=TRUE;
  }
}
References DBG_RTF, m_hide, m_lastIsPara, m_t, p, TRUE, and visitChildren().
operator()() [68/114]
void RTFDocVisitor::operator() (const DocPara &)
operator()() [69/114]
void RTFDocVisitor::operator() (const DocParamList & pl)
Definition at line 1382 of file rtfdocvisitor.cpp.
{
  static int columnPos[4][5] =
  { { 2, 25, 100, 100, 100 }, // no inout, no type
    { 3, 14, 35, 100, 100 }, // inout, no type
    { 3, 25, 50, 100, 100 }, // no inout, type
    { 4, 14, 35, 55, 100 }, // inout, type
  };
  int config=0;
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocParamList &)}\n");
  DocParamSect::Type parentType = DocParamSect::Unknown;
  const DocParamSect *sect = std::get_if<DocParamSect>(pl.parent());
  if (sect)
  {
    parentType = sect->type();
  }
  bool useTable = parentType==DocParamSect::Param ||
                  parentType==DocParamSect::RetVal ||
                  parentType==DocParamSect::Exception ||
                  parentType==DocParamSect::TemplateParam;
  if (sect && sect->hasInOutSpecifier()) config+=1;
  if (sect && sect->hasTypeSpecifier()) config+=2;
  if (useTable)
  {
    int i;
    m_t << "\\trowd \\trgaph108\\trleft426\\tblind426"
         "\\trbrdrt\\brdrs\\brdrw10\\brdrcf15 "
         "\\trbrdrl\\brdrs\\brdrw10\\brdrcf15 "
         "\\trbrdrb\\brdrs\\brdrw10\\brdrcf15 "
         "\\trbrdrr\\brdrs\\brdrw10\\brdrcf15 "
         "\\trbrdrh\\brdrs\\brdrw10\\brdrcf15 "
         "\\trbrdrv\\brdrs\\brdrw10\\brdrcf15 "<< "\n";
    for (i=0;i<columnPos[config][0];i++)
    {
      m_t << "\\clvertalt\\clbrdrt\\brdrs\\brdrw10\\brdrcf15 "
           "\\clbrdrl\\brdrs\\brdrw10\\brdrcf15 "
           "\\clbrdrb\\brdrs\\brdrw10\\brdrcf15 "
           "\\clbrdrr \\brdrs\\brdrw10\\brdrcf15 "
           "\\cltxlrtb "
           "\\cellx" << (rtf_pageWidth*columnPos[config][i+1]/100) << "\n";
    }
    m_t << "\\pard \\widctlpar\\intbl\\adjustright\n";
  }
  if (sect && sect->hasInOutSpecifier())
  {
    if (useTable)
    {
      m_t << "{";
    }
    // Put in the direction: in/out/in,out if specified.
    if (pl.direction()!=DocParamSect::Unspecified)
    {
      if (pl.direction()==DocParamSect::In)
      {
        m_t << "in";
      }
      else if (pl.direction()==DocParamSect::Out)
      {
        m_t << "out";
      }
      else if (pl.direction()==DocParamSect::InOut)
      {
        m_t << "in,out";
      }
    }
    if (useTable)
    {
      m_t << "\\cell }";
    }
  }
  if (sect && sect->hasTypeSpecifier())
  {
    if (useTable)
    {
      m_t << "{";
    }
    for (const auto &type : pl.paramTypes())
    {
      std::visit(*this,type);
    }
    if (useTable)
    {
      m_t << "\\cell }";
    }
  }
  if (useTable)
  {
    m_t << "{";
  }
  m_t << "{\\i ";
  bool first=TRUE;
  for (const auto &param : pl.parameters())
  {
    if (!first) m_t << ","; else first=FALSE;
    std::visit(*this,param);
  }
  m_t << "} ";
  if (useTable)
  {
    m_t << "\\cell }{";
  }
  m_lastIsPara=TRUE;
  for (const auto &par : pl.paragraphs())
  {
    std::visit(*this,par);
  }
  if (useTable)
  {
    m_t << "\\cell }\n";
    //m_t << "\\pard \\widctlpar\\intbl\\adjustright\n";
    m_t << "{\\row }\n";
  }
  else
  {
    m_t << "\\par\n";
  }
  m_lastIsPara=TRUE;
}
References DBG_RTF, DocParamList::direction(), DocParamSect::Exception, FALSE, DocParamSect::hasInOutSpecifier(), DocParamSect::hasTypeSpecifier(), DocParamSect::In, DocParamSect::InOut, m_hide, m_lastIsPara, m_t, DocParamSect::Out, DocParamList::paragraphs(), DocParamSect::Param, DocParamList::parameters(), DocParamList::paramTypes(), DocNode::parent(), DocParamSect::RetVal, rtf_pageWidth, DocParamSect::TemplateParam, TRUE, DocParamSect::type(), DocParamSect::Unknown, and DocParamSect::Unspecified.
operator()() [70/114]
void RTFDocVisitor::operator() (const DocParamList &)
operator()() [71/114]
void RTFDocVisitor::operator() (const DocParamSect & s)
Definition at line 1335 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocParamSect &)}\n");
  m_t << "{"; // start param list
  if (!m_lastIsPara) m_t << "\\par\n";
  //m_t << "{\\b "; // start bold
  m_t << "{" << rtf_Style["Heading5"].reference() << "\n";
  switch(s.type())
  {
    case DocParamSect::Param:
      m_t << theTranslator->trParameters(); break;
    case DocParamSect::RetVal:
      m_t << theTranslator->trReturnValues(); break;
    case DocParamSect::Exception:
      m_t << theTranslator->trExceptions(); break;
    case DocParamSect::TemplateParam:
      m_t << theTranslator->trTemplateParameters(); break;
    default:
      ASSERT(0);
  }
  m_t << "\\par";
  m_t << "}\n";
  bool useTable = s.type()==DocParamSect::Param ||
                  s.type()==DocParamSect::RetVal ||
                  s.type()==DocParamSect::Exception ||
                  s.type()==DocParamSect::TemplateParam;
  if (!useTable)
  {
    incIndentLevel();
  }
  m_t << rtf_Style_Reset << getStyle("DescContinue");
  m_lastIsPara=TRUE;
  visitChildren(s);
  //m_t << "\\par\n";
  if (!useTable)
  {
    decIndentLevel();
  }
  m_t << "}\n";
}
References ASSERT, DBG_RTF, decIndentLevel(), DocParamSect::Exception, getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, DocParamSect::Param, DocParamSect::RetVal, rtf_Style, rtf_Style_Reset, s, DocParamSect::TemplateParam, theTranslator, Translator::trExceptions(), Translator::trParameters(), Translator::trReturnValues(), Translator::trTemplateParameters(), TRUE, and visitChildren().
operator()() [72/114]
void RTFDocVisitor::operator() (const DocParamSect &)
operator()() [73/114]
void RTFDocVisitor::operator() (const DocParBlock & pb)
Definition at line 1611 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(pb);
}
References m_hide, and visitChildren().
operator()() [74/114]
void RTFDocVisitor::operator() (const DocParBlock &)
operator()() [75/114]
void RTFDocVisitor::operator() (const DocRef & ref)
Definition at line 1292 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocRef &)}\n");
  // when ref.isSubPage()==TRUE we use ref.file() for HTML and
  // ref.anchor() for LaTeX/RTF
  if (ref.isSubPage())
  {
    startLink(ref.ref(),QCString(),ref.anchor());
  }
  else
  {
    if (!ref.file().isEmpty()) startLink(ref.ref(),ref.file(),ref.anchor());
  }
  if (!ref.hasLinkText()) filter(ref.targetTitle());
  visitChildren(ref);
  if (!ref.file().isEmpty()) endLink(ref.ref());
  //m_t << " ";
}
References DocRef::anchor(), DBG_RTF, endLink(), DocRef::file(), filter(), DocRef::hasLinkText(), QCString::isEmpty(), DocRef::isSubPage(), m_hide, DocRef::ref(), startLink(), DocRef::targetTitle(), and visitChildren().
operator()() [76/114]
void RTFDocVisitor::operator() (const DocRef & ref)
operator()() [77/114]
void RTFDocVisitor::operator() (const DocRoot & r)
Definition at line 729 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocRoot &)}\n");
  if (r.indent()) incIndentLevel();
  m_t << "{" << rtf_Style["BodyText"].reference() << "\n";
  visitChildren(r);
  if (!m_lastIsPara && !r.singleLine()) m_t << "\\par\n";
  m_t << "}";
  m_lastIsPara=TRUE;
  if (r.indent()) decIndentLevel();
}
References DBG_RTF, decIndentLevel(), incIndentLevel(), m_hide, m_lastIsPara, m_t, r, rtf_Style, TRUE, and visitChildren().
operator()() [78/114]
void RTFDocVisitor::operator() (const DocRoot &)
operator()() [79/114]
void RTFDocVisitor::operator() (const DocSecRefItem & ref)
Definition at line 1313 of file rtfdocvisitor.cpp.
{
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocSecRefItem &)}\n");
  visitChildren(ref);
}
References DBG_RTF, and visitChildren().
operator()() [80/114]
void RTFDocVisitor::operator() (const DocSecRefItem &)
operator()() [81/114]
void RTFDocVisitor::operator() (const DocSecRefList & l)
Definition at line 1319 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocSecRefList &)}\n");
  m_t << "{\n";
  incIndentLevel();
  m_t << rtf_Style_Reset << getStyle("LatexTOC") << "\n";
  m_t << "\\par\n";
  m_lastIsPara=TRUE;
  visitChildren(l);
  decIndentLevel();
  m_t << "\\par";
  m_t << "}\n";
  m_lastIsPara=TRUE;
}
References DBG_RTF, decIndentLevel(), getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, rtf_Style_Reset, TRUE, and visitChildren().
operator()() [82/114]
void RTFDocVisitor::operator() (const DocSecRefList &)
operator()() [83/114]
void RTFDocVisitor::operator() (const DocSection & s)
Definition at line 852 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocSection &)}\n");
  if (!m_lastIsPara) m_t << "\\par\n";
  m_t << "{\\bkmkstart " << rtfFormatBmkStr(stripPath(s.file())+"_"+s.anchor()) << "}\n";
  m_t << "{\\bkmkend " << rtfFormatBmkStr(stripPath(s.file())+"_"+s.anchor()) << "}\n";
  m_t << "{{" // start section
      << rtf_Style_Reset;
  QCString heading;
  int level = std::min(s.level()+1,4);
  heading.sprintf("Heading%d",level);
  // set style
  m_t << rtf_Style[heading.str()].reference() << "\n";
  // make table of contents entry
  filter(s.title());
  m_t << "\n\\par" << "}\n";
  m_t << "{\\tc\\tcl" << level << " \\v ";
  filter(s.title());
  m_t << "}\n";
  m_lastIsPara=TRUE;
  visitChildren(s);
  m_t << "\\par}\n"; // end section
  m_lastIsPara=TRUE;
}
References DBG_RTF, filter(), level, m_hide, m_lastIsPara, m_t, rtf_Style, rtf_Style_Reset, rtfFormatBmkStr(), s, QCString::sprintf(), QCString::str(), stripPath(), TRUE, and visitChildren().
operator()() [84/114]
void RTFDocVisitor::operator() (const DocSection & s)
operator()() [85/114]
void RTFDocVisitor::operator() (const DocSeparator & sep)
Definition at line 1377 of file rtfdocvisitor.cpp.
{
  m_t << " " << sep.chars() << " ";
}
References DocSeparator::chars(), and m_t.
operator()() [86/114]
void RTFDocVisitor::operator() (const DocSeparator &)
operator()() [87/114]
void RTFDocVisitor::operator() (const DocSimpleList & l)
Definition at line 824 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocSimpleSect &)}\n");
  m_t << "{\n";
  m_listItemInfo[indentLevel()].isEnum = FALSE;
  m_lastIsPara=FALSE;
  visitChildren(l);
  if (!m_lastIsPara) m_t << "\\par\n";
  m_t << "}\n";
  m_lastIsPara=TRUE;
}
References DBG_RTF, FALSE, indentLevel(), RTFDocVisitor::RTFListItemInfo::isEnum, m_hide, m_lastIsPara, m_listItemInfo, m_t, TRUE, and visitChildren().
operator()() [88/114]
void RTFDocVisitor::operator() (const DocSimpleList &)
operator()() [89/114]
void RTFDocVisitor::operator() (const DocSimpleListItem & li)
Definition at line 837 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocSimpleListItem &)}\n");
  m_t << "\\par" << rtf_Style_Reset << getStyle("ListBullet") << "\n";
  m_lastIsPara=FALSE;
  incIndentLevel();
  if (li.paragraph())
  {
    std::visit(*this,*li.paragraph());
  }
  decIndentLevel();
  DBG_RTF("{\\comment RTFDocVisitor::visitPost(DocSimpleListItem)}\n");
}
References DBG_RTF, decIndentLevel(), FALSE, getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, DocSimpleListItem::paragraph(), and rtf_Style_Reset.
operator()() [90/114]
void RTFDocVisitor::operator() (const DocSimpleListItem &)
operator()() [91/114]
void RTFDocVisitor::operator() (const DocSimpleSect & s)
Definition at line 742 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocSimpleSect &)}\n");
  if (!m_lastIsPara) m_t << "\\par\n";
  m_t << "{"; // start desc
  //m_t << "{\\b "; // start bold
  m_t << "{" << rtf_Style["Heading5"].reference() << "\n";
  switch(s.type())
  {
    case DocSimpleSect::See:
      m_t << theTranslator->trSeeAlso(); break;
    case DocSimpleSect::Return:
      m_t << theTranslator->trReturns(); break;
    case DocSimpleSect::Author:
      m_t << theTranslator->trAuthor(TRUE,TRUE); break;
    case DocSimpleSect::Authors:
      m_t << theTranslator->trAuthor(TRUE,FALSE); break;
    case DocSimpleSect::Version:
      m_t << theTranslator->trVersion(); break;
    case DocSimpleSect::Since:
      m_t << theTranslator->trSince(); break;
    case DocSimpleSect::Date:
      m_t << theTranslator->trDate(); break;
    case DocSimpleSect::Note:
      m_t << theTranslator->trNote(); break;
    case DocSimpleSect::Warning:
      m_t << theTranslator->trWarning(); break;
    case DocSimpleSect::Pre:
      m_t << theTranslator->trPrecondition(); break;
    case DocSimpleSect::Post:
      m_t << theTranslator->trPostcondition(); break;
    case DocSimpleSect::Copyright:
      m_t << theTranslator->trCopyright(); break;
    case DocSimpleSect::Invar:
      m_t << theTranslator->trInvariant(); break;
    case DocSimpleSect::Remark:
      m_t << theTranslator->trRemarks(); break;
    case DocSimpleSect::Attention:
      m_t << theTranslator->trAttention(); break;
    case DocSimpleSect::User: break;
    case DocSimpleSect::Rcs: break;
    case DocSimpleSect::Unknown: break;
  }
  incIndentLevel();
  if (s.type()!=DocSimpleSect::User && s.type()!=DocSimpleSect::Rcs)
  {
    m_t << "\\par";
    m_t << "}"; // end bold
    m_t << rtf_Style_Reset << getStyle("DescContinue");
    m_t << "{\\s17 \\sa60 \\sb30\n";
  }
  else
  {
    if (s.title())
    {
      std::visit(*this,*s.title());
    }
    m_t << "\\par\n";
    m_t << "}"; // end bold
    m_t << rtf_Style_Reset << getStyle("DescContinue");
  }
  m_lastIsPara=FALSE;
  visitChildren(s);
  if (!m_lastIsPara) m_t << "\\par\n";
  decIndentLevel();
  if (s.type()!=DocSimpleSect::User && s.type()!=DocSimpleSect::Rcs)
  {
    m_t << "}"; // end DescContinue
  }
  m_t << "}"; // end desc
  m_lastIsPara=TRUE;
}
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, DBG_RTF, decIndentLevel(), FALSE, getStyle(), incIndentLevel(), DocSimpleSect::Invar, m_hide, m_lastIsPara, m_t, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, rtf_Style, rtf_Style_Reset, s, DocSimpleSect::See, DocSimpleSect::Since, theTranslator, Translator::trAttention(), Translator::trAuthor(), Translator::trCopyright(), Translator::trDate(), Translator::trInvariant(), Translator::trNote(), Translator::trPostcondition(), Translator::trPrecondition(), Translator::trRemarks(), Translator::trReturns(), Translator::trSeeAlso(), Translator::trSince(), TRUE, Translator::trVersion(), Translator::trWarning(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, visitChildren(), and DocSimpleSect::Warning.
operator()() [92/114]
void RTFDocVisitor::operator() (const DocSimpleSect &)
operator()() [93/114]
void RTFDocVisitor::operator() (const DocSimpleSectSep &)
Definition at line 640 of file rtfdocvisitor.cpp.
{
}
operator()() [94/114]
void RTFDocVisitor::operator() (const DocSimpleSectSep &)
operator()() [95/114]
void RTFDocVisitor::operator() (const DocStyleChange & s)
Definition at line 231 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  m_lastIsPara=FALSE;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocStyleChange)}\n");
  switch (s.style())
  {
    case DocStyleChange::Bold:
      if (s.enable()) m_t << "{\\b "; else m_t << "} ";
      break;
    case DocStyleChange::S:
    case DocStyleChange::Strike:
    case DocStyleChange::Del:
      if (s.enable()) m_t << "{\\strike "; else m_t << "} ";
      break;
    case DocStyleChange::Underline:
    case DocStyleChange::Ins:
      if (s.enable()) m_t << "{\\ul "; else m_t << "} ";
      break;
    case DocStyleChange::Italic:
      if (s.enable()) m_t << "{\\i "; else m_t << "} ";
      break;
    case DocStyleChange::Code:
      if (s.enable()) m_t << "{\\f2 "; else m_t << "} ";
      break;
    case DocStyleChange::Subscript:
      if (s.enable()) m_t << "{\\sub "; else m_t << "} ";
      break;
    case DocStyleChange::Superscript:
      if (s.enable()) m_t << "{\\super "; else m_t << "} ";
      break;
    case DocStyleChange::Center:
      if (s.enable()) m_t << "{\\qc "; else m_t << "} ";
      break;
    case DocStyleChange::Small:
      if (s.enable()) m_t << "{\\sub "; else m_t << "} ";
      break;
    case DocStyleChange::Cite:
      if (s.enable()) m_t << "{\\i "; else m_t << "} ";
      break;
    case DocStyleChange::Preformatted:
      if (s.enable())
      {
        m_t << "{\n";
        m_t << "\\par\n";
        m_t << rtf_Style_Reset << getStyle("CodeExample");
        m_insidePre=TRUE;
      }
      else
      {
        m_insidePre=FALSE;
        m_t << "\\par";
        m_t << "}\n";
      }
      m_lastIsPara=TRUE;
      break;
    case DocStyleChange::Div: /* HTML only */ break;
    case DocStyleChange::Span: /* HTML only */ break;
  }
}
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Cite, DocStyleChange::Code, DBG_RTF, DocStyleChange::Del, DocStyleChange::Div, FALSE, getStyle(), DocStyleChange::Ins, DocStyleChange::Italic, m_hide, m_insidePre, m_lastIsPara, m_t, DocStyleChange::Preformatted, rtf_Style_Reset, s, DocStyleChange::S, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::Strike, DocStyleChange::Subscript, DocStyleChange::Superscript, TRUE, and DocStyleChange::Underline.
operator()() [96/114]
void RTFDocVisitor::operator() (const DocStyleChange &)
operator()() [97/114]
void RTFDocVisitor::operator() (const DocSymbol & s)
Definition at line 127 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocSymbol)}\n");
  const char *res = HtmlEntityMapper::instance()->rtf(s.symbol());
  if (res)
  {
    m_t << res;
  }
  else
  {
    err("RTF: non supported HTML-entity found: %s\n",HtmlEntityMapper::instance()->html(s.symbol(),TRUE));
  }
  m_lastIsPara=FALSE;
}
References DBG_RTF, err(), FALSE, HtmlEntityMapper::instance(), m_hide, m_lastIsPara, m_t, HtmlEntityMapper::rtf(), s, and TRUE.
operator()() [98/114]
void RTFDocVisitor::operator() (const DocSymbol &)
operator()() [99/114]
void RTFDocVisitor::operator() (const DocText & t)
Definition at line 1585 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocText &)}\n");
  visitChildren(t);
}
References DBG_RTF, m_hide, and visitChildren().
operator()() [100/114]
void RTFDocVisitor::operator() (const DocText &)
operator()() [101/114]
void RTFDocVisitor::operator() (const DocTitle & t)
Definition at line 817 of file rtfdocvisitor.cpp.
{
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocTitle &)}\n");
  if (m_hide) return;
  visitChildren(t);
}
References DBG_RTF, m_hide, and visitChildren().
operator()() [102/114]
void RTFDocVisitor::operator() (const DocTitle &)
operator()() [103/114]
void RTFDocVisitor::operator() (const DocURL & u)
Definition at line 185 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocURL)}\n");
  if (Config_getBool(RTF_HYPERLINKS))
  {
    m_t << "{\\field "
             "{\\*\\fldinst "
               "{ HYPERLINK \"";
    if (u.isEmail()) m_t << "mailto:";
    m_t << u.url();
    m_t << "\" }"
               "{}";
    m_t << "}"
             "{\\fldrslt "
               "{\\cs37\\ul\\cf2 ";
    filter(u.url());
    m_t << "}"
             "}"
           "}\n";
  }
  else
  {
    m_t << "{\\f2 ";
    filter(u.url());
    m_t << "}";
  }
  m_lastIsPara=FALSE;
}
References Config_getBool, DBG_RTF, FALSE, filter(), DocURL::isEmail(), m_hide, m_lastIsPara, m_t, and DocURL::url().
operator()() [104/114]
void RTFDocVisitor::operator() (const DocURL &)
operator()() [105/114]
void RTFDocVisitor::operator() (const DocVerbatim & s)
Definition at line 292 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocVerbatim)}\n");
  QCString lang = m_langExt;
  if (!s.language().isEmpty()) // explicit language setting
  {
    lang = s.language();
  }
  SrcLangExt langExt = getLanguageFromCodeLang(lang);
  switch(s.type())
  {
    case DocVerbatim::Code:
      m_t << "{\n";
      m_t << "\\par\n";
      m_t << rtf_Style_Reset << getStyle("CodeExample");
      getCodeParser(lang).parseCode(m_ci,s.context(),s.text(),langExt,
                                    s.isExample(),s.exampleFile());
      //m_t << "\\par\n";
      m_t << "}\n";
      break;
    case DocVerbatim::JavaDocLiteral:
      filter(s.text(),TRUE);
      break;
    case DocVerbatim::JavaDocCode:
      m_t << "{\n";
      m_t << "{\\f2 ";
      filter(s.text(),TRUE);
      m_t << "}";
      m_t << "}\n";
      break;
    case DocVerbatim::Verbatim:
      m_t << "{\n";
      m_t << "\\par\n";
      m_t << rtf_Style_Reset << getStyle("CodeExample");
      filter(s.text(),TRUE);
      //m_t << "\\par\n";
      m_t << "}\n";
      break;
    case DocVerbatim::RtfOnly:
      m_t << s.text();
      break;
    case DocVerbatim::HtmlOnly:
    case DocVerbatim::LatexOnly:
    case DocVerbatim::XmlOnly:
    case DocVerbatim::ManOnly:
    case DocVerbatim::DocbookOnly:
      /* nothing */
      break;
    case DocVerbatim::Dot:
      {
        static int dotindex = 1;
        QCString fileName(4096);
        fileName.sprintf("%s%d%s",
            qPrint(Config_getString(RTF_OUTPUT)+"/inline_dotgraph_"),
            dotindex++,
            ".dot"
           );
        std::ofstream file(fileName.str(),std::ofstream::out | std::ofstream::binary);
        if (!file.is_open())
        {
          err("Could not open file %s for writing\n",qPrint(fileName));
        }
        else
        {
          QCString stext = s.text();
          file.write(stext.data(), stext.length());
          file.close();
        }
        writeDotFile(fileName, s.hasCaption(), s.srcFile(), s.srcLine());
        visitChildren(s);
        includePicturePostRTF(true, s.hasCaption());
        if (Config_getBool(DOT_CLEANUP)) Dir().remove(fileName.str());
      }
      break;
    case DocVerbatim::Msc:
      {
        static int mscindex = 1;
        QCString baseName(4096);
        baseName.sprintf("%s%d%s",
            qPrint(Config_getString(RTF_OUTPUT)+"/inline_mscgraph_"),
            mscindex++,
            ".msc"
           );
        std::ofstream file(baseName.str(),std::ofstream::out | std::ofstream::binary);
        if (!file.is_open())
        {
          err("Could not open file %s for writing\n",qPrint(baseName));
        }
        QCString text = "msc {";
        text+=s.text();
        text+="}";
        file.write(text.data(), text.length());
        file.close();
        writeMscFile(baseName, s.hasCaption(), s.srcFile(), s.srcLine());
        visitChildren(s);
        includePicturePostRTF(true, s.hasCaption());
        if (Config_getBool(DOT_CLEANUP)) Dir().remove(baseName.str());
      }
      break;
    case DocVerbatim::PlantUML:
      {
        QCString rtfOutput = Config_getString(RTF_OUTPUT);
        QCString baseName = PlantumlManager::instance().writePlantUMLSource(
                       rtfOutput,s.exampleFile(),s.text(),PlantumlManager::PUML_BITMAP,
                       s.engine(),s.srcFile(),s.srcLine());
        writePlantUMLFile(baseName, s.hasCaption());
        visitChildren(s);
        includePicturePostRTF(true, s.hasCaption());
      }
      break;
  }
  m_lastIsPara=FALSE;
}
References DocVerbatim::Code, Config_getBool, Config_getString, QCString::data(), DBG_RTF, DocVerbatim::DocbookOnly, DocVerbatim::Dot, err(), FALSE, caseconvert::file, filter(), DocVisitor::getCodeParser(), getLanguageFromCodeLang(), getStyle(), DocVerbatim::HtmlOnly, includePicturePostRTF(), PlantumlManager::instance(), DocVerbatim::JavaDocCode, DocVerbatim::JavaDocLiteral, DocVerbatim::LatexOnly, QCString::length(), m_ci, m_hide, m_langExt, m_lastIsPara, m_t, DocVerbatim::ManOnly, DocVerbatim::Msc, out, CodeParserInterface::parseCode(), DocVerbatim::PlantUML, PlantumlManager::PUML_BITMAP, qPrint(), Dir::remove(), rtf_Style_Reset, DocVerbatim::RtfOnly, s, QCString::sprintf(), QCString::str(), TRUE, DocVerbatim::Verbatim, visitChildren(), writeDotFile(), writeMscFile(), writePlantUMLFile(), PlantumlManager::writePlantUMLSource(), and DocVerbatim::XmlOnly.
operator()() [106/114]
void RTFDocVisitor::operator() (const DocVerbatim &)
operator()() [107/114]
void RTFDocVisitor::operator() (const DocVhdlFlow &)
Definition at line 1607 of file rtfdocvisitor.cpp.
{
}
operator()() [108/114]
void RTFDocVisitor::operator() (const DocVhdlFlow &)
operator()() [109/114]
void RTFDocVisitor::operator() (const DocWhiteSpace & w)
Definition at line 112 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocWhiteSpace)}\n");
  if (m_insidePre)
  {
    m_t << w.chars();
  }
  else
  {
    m_t << " ";
  }
  m_lastIsPara=FALSE;
}
References DBG_RTF, FALSE, m_hide, m_insidePre, m_lastIsPara, m_t, and w.
operator()() [110/114]
void RTFDocVisitor::operator() (const DocWhiteSpace &)
operator()() [111/114]
void RTFDocVisitor::operator() (const DocWord & w)
Definition at line 94 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  DBG_RTF("{\\comment RTFDocVisitor::visit(DocWord)}\n");
  filter(w.word());
  m_lastIsPara=FALSE;
}
References DBG_RTF, FALSE, filter(), m_hide, m_lastIsPara, and w.
operator()() [112/114]
void RTFDocVisitor::operator() (const DocWord &)
operator()() [113/114]
void RTFDocVisitor::operator() (const DocXRefItem & x)
Definition at line 1514 of file rtfdocvisitor.cpp.
{
  if (m_hide) return;
  if (x.title().isEmpty()) return;
  bool anonymousEnum = x.file()=="@";
  DBG_RTF("{\\comment RTFDocVisitor::operator()(const DocXRefItem &)}\n");
  if (!m_lastIsPara)
  {
    m_t << "\\par\n";
    m_lastIsPara=TRUE;
  }
  m_t << "{"; // start param list
  //m_t << "{\\b "; // start bold
  m_t << "{" << rtf_Style["Heading5"].reference() << "\n";
  if (Config_getBool(RTF_HYPERLINKS) && !anonymousEnum)
  {
    QCString refName;
    if (!x.file().isEmpty())
    {
      refName+=stripPath(x.file());
    }
    if (!x.file().isEmpty() && !x.anchor().isEmpty())
    {
      refName+="_";
    }
    if (!x.anchor().isEmpty())
    {
      refName+=x.anchor();
    }
    m_t << "{\\field "
             "{\\*\\fldinst "
               "{ HYPERLINK \\\\l \"" << rtfFormatBmkStr(refName) << "\" "
               "}{}"
             "}"
             "{\\fldrslt "
               "{\\cs37\\ul\\cf2 ";
    filter(x.title());
    m_t << "}"
             "}"
           "}";
  }
  else
  {
    filter(x.title());
  }
  m_t << ":";
  m_t << "\\par";
  m_t << "}"; // end bold
  incIndentLevel();
  m_t << rtf_Style_Reset << getStyle("DescContinue");
  m_lastIsPara=FALSE;
  visitChildren(x);
  if (x.title().isEmpty()) return;
  DBG_RTF("{\\comment RTFDocVisitor::visitPost(DocXRefItem)}\n");
  m_t << "\\par\n";
  decIndentLevel();
  m_t << "}\n"; // end xref item
  m_lastIsPara=TRUE;
}
References Config_getBool, DBG_RTF, decIndentLevel(), FALSE, filter(), getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, rtf_Style, rtf_Style_Reset, rtfFormatBmkStr(), stripPath(), TRUE, visitChildren(), and x.
operator()() [114/114]
void RTFDocVisitor::operator() (const DocXRefItem &)
startLink() [1/2]
void RTFDocVisitor::startLink (const QCString & ref, const QCString & file, const QCString & anchor) [private]
Definition at line 1654 of file rtfdocvisitor.cpp.
{
  if (ref.isEmpty() && Config_getBool(RTF_HYPERLINKS))
  {
    QCString refName;
    if (!file.isEmpty())
    {
      refName+=stripPath(file);
    }
    if (!file.isEmpty() && !anchor.isEmpty())
    {
      refName+='_';
    }
    if (!anchor.isEmpty())
    {
      refName+=anchor;
    }
    m_t << "{\\field {\\*\\fldinst { HYPERLINK \\\\l \"";
    m_t << rtfFormatBmkStr(refName);
    m_t << "\" }{}";
    m_t << "}{\\fldrslt {\\cs37\\ul\\cf2 ";
  }
  else
  {
    m_t << "{\\b ";
  }
  m_lastIsPara=FALSE;
}
References Config_getBool, FALSE, caseconvert::file, QCString::isEmpty(), m_lastIsPara, m_t, rtfFormatBmkStr(), and stripPath().
Referenced by operator()().
startLink() [2/2]
void RTFDocVisitor::startLink (const QCString & ref, const QCString & file, const QCString & anchor) [private]
visitChildren() [1/2]
template<class T >
void RTFDocVisitor::visitChildren (const T & t) [inline], [private]
Definition at line 105 of file rtfdocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
Referenced by operator()().
visitChildren() [2/2]
template<class T >
void RTFDocVisitor::visitChildren (const T & t) [inline], [private]
Definition at line 105 of file rtfdocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
writeDiaFile() [1/2]
void RTFDocVisitor::writeDiaFile (const DocDiaFile & df) [private]
Definition at line 1734 of file rtfdocvisitor.cpp.
{
  QCString baseName=df.file();
  int i;
  if ((i=baseName.findRev('/'))!=-1)
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  QCString outDir = Config_getString(RTF_OUTPUT);
  writeDiaGraphFromFile(df.file(),outDir,baseName,DIA_BITMAP,df.srcFile(),df.srcLine());
  includePicturePreRTF(baseName + ".png", true, df.hasCaption());
}
References Config_getString, DIA_BITMAP, DocDiagramFileBase::file(), QCString::findRev(), DocDiagramFileBase::hasCaption(), includePicturePreRTF(), QCString::length(), QCString::right(), DocDiagramFileBase::srcFile(), DocDiagramFileBase::srcLine(), and writeDiaGraphFromFile().
Referenced by operator()().
writeDiaFile() [2/2]
void RTFDocVisitor::writeDiaFile (const DocDiaFile &) [private]
writeDotFile() [1/4]
void RTFDocVisitor::writeDotFile (const DocDotFile & df) [private]
Definition at line 1697 of file rtfdocvisitor.cpp.
{
  writeDotFile(df.file(), df.hasCaption(), df.srcFile(), df.srcLine());
}
References DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), DocDiagramFileBase::srcFile(), DocDiagramFileBase::srcLine(), and writeDotFile().
writeDotFile() [2/4]
void RTFDocVisitor::writeDotFile (const DocDotFile &) [private]
writeDotFile() [3/4]
void RTFDocVisitor::writeDotFile (const QCString & fileName, bool hasCaption, const QCString & srcFile, int srcLine) [private]
Definition at line 1701 of file rtfdocvisitor.cpp.
{
  QCString baseName=filename;
  int i;
  if ((i=baseName.findRev('/'))!=-1)
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  QCString outDir = Config_getString(RTF_OUTPUT);
  writeDotGraphFromFile(filename,outDir,baseName,GOF_BITMAP,srcFile,srcLine);
  QCString imgExt = getDotImageExtension();
  includePicturePreRTF(baseName + "." + imgExt, true, hasCaption);
}
References Config_getString, filename, QCString::findRev(), getDotImageExtension(), GOF_BITMAP, includePicturePreRTF(), QCString::length(), QCString::right(), and writeDotGraphFromFile().
Referenced by operator()(), and writeDotFile().
writeDotFile() [4/4]
void RTFDocVisitor::writeDotFile (const QCString & fileName, bool hasCaption, const QCString & srcFile, int srcLine) [private]
writeMscFile() [1/4]
void RTFDocVisitor::writeMscFile (const DocMscFile & df) [private]
Definition at line 1716 of file rtfdocvisitor.cpp.
{
  writeMscFile(df.file(), df.hasCaption(), df.srcFile(), df.srcLine());
}
References DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), DocDiagramFileBase::srcFile(), DocDiagramFileBase::srcLine(), and writeMscFile().
writeMscFile() [2/4]
void RTFDocVisitor::writeMscFile (const DocMscFile &) [private]
writeMscFile() [3/4]
void RTFDocVisitor::writeMscFile (const QCString & fileName, bool hasCaption, const QCString & srcFile, int srcLine) [private]
Definition at line 1720 of file rtfdocvisitor.cpp.
{
  QCString baseName=fileName;
  int i;
  if ((i=baseName.findRev('/'))!=-1)
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  QCString outDir = Config_getString(RTF_OUTPUT);
  writeMscGraphFromFile(fileName,outDir,baseName,MSC_BITMAP,srcFile,srcLine);
  includePicturePreRTF(baseName + ".png", true, hasCaption);
}
References Config_getString, QCString::findRev(), includePicturePreRTF(), QCString::length(), MSC_BITMAP, QCString::right(), and writeMscGraphFromFile().
Referenced by operator()(), and writeMscFile().
writeMscFile() [4/4]
void RTFDocVisitor::writeMscFile (const QCString & fileName, bool hasCaption, const QCString & srcFile, int srcLine) [private]
writePlantUMLFile() [1/2]
void RTFDocVisitor::writePlantUMLFile (const QCString & fileName, bool hasCaption) [private]
Definition at line 1747 of file rtfdocvisitor.cpp.
{
  QCString baseName=fileName;
  int i;
  if ((i=baseName.findRev('/'))!=-1)
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  QCString outDir = Config_getString(RTF_OUTPUT);
  PlantumlManager::instance().generatePlantUMLOutput(fileName,outDir,PlantumlManager::PUML_BITMAP);
  includePicturePreRTF(baseName + ".png", true, hasCaption);
}
References Config_getString, QCString::findRev(), PlantumlManager::generatePlantUMLOutput(), includePicturePreRTF(), PlantumlManager::instance(), QCString::length(), PlantumlManager::PUML_BITMAP, and QCString::right().
Referenced by operator()().
writePlantUMLFile() [2/2]
void RTFDocVisitor::writePlantUMLFile (const QCString & fileName, bool hasCaption) [private]
Member Data Documentation
m_ci
CodeOutputInterface & RTFDocVisitor::m_ci [private]
Definition at line 141 of file rtfdocvisitor.h.
Referenced by operator()().
m_hide
bool RTFDocVisitor::m_hide = false [private]
Definition at line 143 of file rtfdocvisitor.h.
Referenced by includePicturePostRTF(), includePicturePreRTF(), and operator()().
m_indentLevel
int RTFDocVisitor::m_indentLevel = 0 [private]
Definition at line 148 of file rtfdocvisitor.h.
Referenced by decIndentLevel(), incIndentLevel(), and indentLevel().
m_insidePre
bool RTFDocVisitor::m_insidePre = false [private]
Definition at line 142 of file rtfdocvisitor.h.
Referenced by operator()().
m_langExt
QCString RTFDocVisitor::m_langExt [private]
Definition at line 145 of file rtfdocvisitor.h.
Referenced by operator()().
m_lastIsPara
bool RTFDocVisitor::m_lastIsPara = false [private]
Definition at line 144 of file rtfdocvisitor.h.
Referenced by endLink(), includePicturePreRTF(), operator()(), and startLink().
m_listItemInfo
RTFListItemInfo RTFDocVisitor::m_listItemInfo [private]
Definition at line 155 of file rtfdocvisitor.h.
Referenced by operator()().
m_t
TextStream & RTFDocVisitor::m_t [private]
Definition at line 140 of file rtfdocvisitor.h.
Referenced by endLink(), filter(), includePicturePostRTF(), includePicturePreRTF(), operator()(), and startLink().
maxIndentLevels
static const int RTFDocVisitor::maxIndentLevels = 13 [static], [private]
Definition at line 147 of file rtfdocvisitor.h.
Referenced by incIndentLevel(), and indentLevel().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/rtfdocvisitor.h
doxygen/src/rtfdocvisitor.h
doxygen/build/doxygen/src/rtfdocvisitor.cpp
doxygen/src/rtfdocvisitor.cpp