reg::Ex Class Reference
#include <regex.h>
Classes
class Private
Public Types
enum class Mode { RegEx
, Wildcard
, RegEx
, Wildcard
 }
enum class Mode { RegEx
, Wildcard
, RegEx
, Wildcard
 }
Public Member Functions
Ex (const std::string &pattern, Mode mode=Mode::RegEx)
~Ex ()
bool match (const std::string &str, Match &match, size_t pos=0) const
bool isValid () const
Ex (const std::string &pattern, Mode mode=Mode::RegEx)
~Ex ()
bool match (const std::string &str, Match &match, size_t pos=0) const
bool isValid () const
Private Member Functions
Ex (const Ex &)=delete
Ex & operator= (const Ex &e)=delete
Ex (const Ex &)=delete
Ex & operator= (const Ex &e)=delete
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Class representing a regular expression.
It has a similar API as std::regex, but is much faster (and also somewhat more limited).
Definition at line 35 of file regex.h.
Member Enumeration Documentation
Mode [1/2]
enum class reg::Ex::Mode [strong]
Matching algorithm
Enumerator
RegEx full regular expression.
Wildcard simple globbing pattern.
RegEx full regular expression.
Wildcard simple globbing pattern.
Definition at line 39 of file regex.h.
    {
      RegEx,
      Wildcard
    };
Mode [2/2]
enum class reg::Ex::Mode [strong]
Matching algorithm
Enumerator
RegEx full regular expression.
Wildcard simple globbing pattern.
RegEx full regular expression.
Wildcard simple globbing pattern.
Definition at line 39 of file regex.h.
    {
      RegEx,
      Wildcard
    };
Constructor & Destructor Documentation
Ex() [1/4]
reg::Ex::Ex (const std::string & pattern, Mode mode = Mode::RegEx)
Creates a regular expression object given the pattern as a string. Two modes of matching are supported: RegEx and Wildcard
The following special characters are supported in Mode::RegEx mode.
c matches character c
. matches any character
^ matches the start of the input
$ matches the end of the input
\< matches the start of a word
\> matches the end of a word
[] matches a set of characters
x* matches a sequence of zero or more x's
x+ matches a sequence of one or more x's
x? matches an optional x
(matches the start of a capture range
) matches the ends a capture range
\c to escape a special character, such as +, [, *, (, etc.
\t matches a tab character
\n matches a newline character
\r matches a return character
\s matches any whitespace as defined by std::isspace()
\d matches any digit as defined by std::digit()
\a matches any alphabetical characters, same as [a-z_A-Z\x80-\xFF]
\w matches any alpha numerical character, same as [a-z_A-Z0-9\x80-\xFF]
\xHH matches a hexadecimal character, e.g. \xA0 matches character code 160.
A character range can be used to match a character that falls inside a range (or set of ranges). Within the opening [ and closing ] brackets of a character ranges the following is supported:
^ if at the start of the range, a character matches if it is not in the range, e.g. [^\d] matches any character not a digit
- when placed between 2 characters it defines a range from the first character to the second. any character that falls in the range will match, e.g. [0-9] matches the digit from 0 to 9.
\s, \d, \a, and \w as explained above.
Note
that special characters ., *, ?, $, +, [ do not have a special meaning in a character range. ^ only has a special meaning as the first character.
that capture ranges cannot be nested, and *, +, and ? do not work on capture ranges. e.g. (abd)? is not valid. If multiple capture ranges are specified then some character has to be in between them, e.g. this does not work (.*)(a.*), but this does (.*)a(.*).
In Wildcard mode * is used to match any sequence of zero or more characters. The character ? can be used to match an optional character. Character ranges are also supported, but other characters like $ and + are just treated as literal characters.
Definition at line 693 of file regex.cpp.
  : p(std::make_unique<Private>(mode==Mode::RegEx ? pattern : wildcard2regex(pattern)))
{
  p->compile();
#if ENABLE_DEBUG
  p->dump();
  assert(!p->error);
#endif
}
References p.
 Ex() [1/2]
reg::Ex::~Ex ()
Destroys the regular expression object. Frees resources.
Definition at line 703 of file regex.cpp.
{
}
Ex() [2/4]
reg::Ex::Ex (const Ex &) [private], [delete]
Ex() [3/4]
reg::Ex::Ex (const std::string & pattern, Mode mode = Mode::RegEx)
Creates a regular expression object given the pattern as a string. Two modes of matching are supported: RegEx and Wildcard
The following special characters are supported in Mode::RegEx mode.
c matches character c
. matches any character
^ matches the start of the input
$ matches the end of the input
\< matches the start of a word
\> matches the end of a word
[] matches a set of characters
x* matches a sequence of zero or more x's
x+ matches a sequence of one or more x's
x? matches an optional x
(matches the start of a capture range
) matches the ends a capture range
\c to escape a special character, such as +, [, *, (, etc.
\t matches a tab character
\n matches a newline character
\r matches a return character
\s matches any whitespace as defined by std::isspace()
\d matches any digit as defined by std::digit()
\a matches any alphabetical characters, same as [a-z_A-Z\x80-\xFF]
\w matches any alpha numerical character, same as [a-z_A-Z0-9\x80-\xFF]
\xHH matches a hexadecimal character, e.g. \xA0 matches character code 160.
A character range can be used to match a character that falls inside a range (or set of ranges). Within the opening [ and closing ] brackets of a character ranges the following is supported:
^ if at the start of the range, a character matches if it is not in the range, e.g. [^\d] matches any character not a digit
- when placed between 2 characters it defines a range from the first character to the second. any character that falls in the range will match, e.g. [0-9] matches the digit from 0 to 9.
\s, \d, \a, and \w as explained above.
Note
that special characters ., *, ?, $, +, [ do not have a special meaning in a character range. ^ only has a special meaning as the first character.
that capture ranges cannot be nested, and *, +, and ? do not work on capture ranges. e.g. (abd)? is not valid. If multiple capture ranges are specified then some character has to be in between them, e.g. this does not work (.*)(a.*), but this does (.*)a(.*).
In Wildcard mode * is used to match any sequence of zero or more characters. The character ? can be used to match an optional character. Character ranges are also supported, but other characters like $ and + are just treated as literal characters.
 Ex() [2/2]
reg::Ex::~Ex ()
Destroys the regular expression object. Frees resources.
Ex() [4/4]
reg::Ex::Ex (const Ex &) [private], [delete]
Member Function Documentation
isValid() [1/2]
bool reg::Ex::isValid () const
Definition at line 742 of file regex.cpp.
{
  return !p->pattern.empty() && !p->error;
}
References p.
Referenced by genericPatternMatch(), and getFilterFromList().
isValid() [2/2]
bool reg::Ex::isValid () const
match() [1/2]
bool reg::Ex::match (const std::string & str, Match & match, size_t pos = 0) const
Check if a given string matches this regular expression.
Parameters
str The input string to match against.
match The match object to hold the matching results.
pos The position in the string at which to start the match.
Returns
true iff a match is found. Details are stored in the match object.
Definition at line 707 of file regex.cpp.
{
  bool found=false;
  if (p->data.size()==0 || p->error) return found;
  match.init(&str);
  PToken tok = p->data[0];
  if (tok.kind()==PToken::Kind::BeginOfLine) // only test match at the given position
  {
    found = p->matchAt(0,p->data.size(),str,match,pos,0);
  }
  else
  {
    if (tok.kind()==PToken::Kind::Character) // search for the start character
    {
      size_t index = str.find(tok.asciiValue(),pos);
      if (index==std::string::npos)
      {
        DBG("Ex::match(str='%s',pos=%zu)=false (no start char '%c')\n",str.c_str(),pos,tok.asciiValue());
        return false;
      }
      DBG("pos=%zu str='%s' char='%c' index=%zu\n",index,str.c_str(),tok.asciiValue(),index);
      pos=index;
    }
    while (pos<str.length()) // search for a match starting at pos
    {
      found = p->matchAt(0,p->data.size(),str,match,pos,0);
      if (found) break;
      pos++;
    }
  }
  DBG("Ex::match(str='%s',pos=%zu)=%d\n",str.c_str(),pos,found);
  return found;
}
References reg::PToken::asciiValue(), reg::PToken::BeginOfLine, reg::PToken::Character, DBG, found, reg::PToken::kind(), match(), and p.
Referenced by search.Finder::baseClasses(), search.Finder::file(), search.Finder::fileId(), reg::Iterator::findNext(), search.Finder::function(), search.Finder::macro(), reg::match(), match(), reg::Ex::Private::matchAt(), search.Finder::members(), search.Finder::params(), search.Finder::references(), reg::replace(), reg::search(), search.Finder::struct(), search.Finder::subClasses(), search.Finder::typedef(), and search.Finder::variable().
match() [2/2]
bool reg::Ex::match (const std::string & str, Match & match, size_t pos = 0) const
Check if a given string matches this regular expression.
Parameters
str The input string to match against.
match The match object to hold the matching results.
pos The position in the string at which to start the match.
Returns
true iff a match is found. Details are stored in the match object.
Referenced by search.Finder::baseClasses(), search.Finder::file(), search.Finder::fileId(), search.Finder::function(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), search.Finder::struct(), search.Finder::subClasses(), search.Finder::typedef(), and search.Finder::variable().
operator=() [1/2]
Ex & reg::Ex::operator= (const Ex & e) [private], [delete]
operator=() [2/2]
Ex & reg::Ex::operator= (const Ex & e) [private], [delete]
Member Data Documentation
p
std::unique_ptr< Private > reg::Ex::p [private]
Definition at line 112 of file regex.h.
Referenced by Ex(), isValid(), match(), and reg::wildcard2regex().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/regex.h
doxygen/src/regex.h
doxygen/build/doxygen/src/regex.cpp
doxygen/src/regex.cpp