ghc::filesystem::path Class Reference
#include <filesystem.hpp>
Classes
struct _is_basic_string
struct _is_basic_string< std::basic_string< CharT, std::char_traits< CharT >, std::allocator< CharT > > >
struct _is_basic_string< std::basic_string< CharT, Traits, Alloc > >
class input_iterator_range
Public Types
enum format {
generic_format
, native_format
, auto_format
, generic_format
,
native_format
, auto_format
 }
The path format in which the constructor argument is given.
enum format {
generic_format
, native_format
, auto_format
, generic_format
,
native_format
, auto_format
 }
The path format in which the constructor argument is given.
using string_type = std::basic_string< value_type >
template<typename T1 , typename T2 = void>
using path_type = typename std::enable_if<!std::is_same< path, T1 >::value, path >::type
template<typename T >
using path_from_string = typename std::enable_if< _is_basic_string< T >::value||std::is_same< char const *, typename std::decay< T >::type >::value||std::is_same< char *, typename std::decay< T >::type >::value||std::is_same< char16_t const *, typename std::decay< T >::type >::value||std::is_same< char16_t *, typename std::decay< T >::type >::value||std::is_same< char32_t const *, typename std::decay< T >::type >::value||std::is_same< char32_t *, typename std::decay< T >::type >::value||std::is_same< wchar_t const *, typename std::decay< T >::type >::value||std::is_same< wchar_t *, typename std::decay< T >::type >::value, path >::type
template<typename T >
using path_type_EcharT = typename std::enable_if< std::is_same< T, char >::value||std::is_same< T, char16_t >::value||std::is_same< T, char32_t >::value||std::is_same< T, wchar_t >::value, path >::type
using const_iterator = iterator
using value_type = const path
using difference_type = std::ptrdiff_t
using pointer = const path *
using reference = const path &
using iterator_category = std::bidirectional_iterator_tag
using string_type = std::basic_string< value_type >
template<typename T1 , typename T2 = void>
using path_type = typename std::enable_if<!std::is_same< path, T1 >::value, path >::type
template<typename T >
using path_from_string = typename std::enable_if< _is_basic_string< T >::value||std::is_same< char const *, typename std::decay< T >::type >::value||std::is_same< char *, typename std::decay< T >::type >::value||std::is_same< char16_t const *, typename std::decay< T >::type >::value||std::is_same< char16_t *, typename std::decay< T >::type >::value||std::is_same< char32_t const *, typename std::decay< T >::type >::value||std::is_same< char32_t *, typename std::decay< T >::type >::value||std::is_same< wchar_t const *, typename std::decay< T >::type >::value||std::is_same< wchar_t *, typename std::decay< T >::type >::value, path >::type
template<typename T >
using path_type_EcharT = typename std::enable_if< std::is_same< T, char >::value||std::is_same< T, char16_t >::value||std::is_same< T, char32_t >::value||std::is_same< T, wchar_t >::value, path >::type
using const_iterator = iterator
using value_type = const path
using difference_type = std::ptrdiff_t
using pointer = const path *
using reference = const path &
using iterator_category = std::bidirectional_iterator_tag
Public Member Functions
path () noexcept
path (const path &p)
path (path &&p) noexcept
path (string_type &&source, format fmt=auto_format)
template<class Source , typename = path_from_string<Source>>
path (const Source &source, format fmt=auto_format)
template<class InputIterator >
path (InputIterator first, InputIterator last, format fmt=auto_format)
~path ()
path & operator= (const path &p)
path & operator= (path &&p) noexcept
path & operator= (string_type &&source)
path & assign (string_type &&source)
template<class Source >
path & operator= (const Source &source)
template<class Source >
path & assign (const Source &source)
template<class InputIterator >
path & assign (InputIterator first, InputIterator last)
path & operator/= (const path &p)
template<class Source >
path & operator/= (const Source &source)
template<class Source >
path & append (const Source &source)
template<class InputIterator >
path & append (InputIterator first, InputIterator last)
path & operator+= (const path &x)
path & operator+= (const string_type &x)
path & operator+= (const value_type *x)
path & operator+= (value_type x)
template<class Source >
path_from_string< Source > & operator+= (const Source &x)
template<class EcharT >
path_type_EcharT< EcharT > & operator+= (EcharT x)
template<class Source >
path & concat (const Source &x)
template<class InputIterator >
path & concat (InputIterator first, InputIterator last)
void clear () noexcept
path & make_preferred ()
path & remove_filename ()
path & replace_filename (const path &replacement)
path & replace_extension (const path &replacement=path())
void swap (path &rhs) noexcept
const string_type & native () const noexcept
const value_type * c_str () const noexcept
operator string_type () const
template<class EcharT , class traits = std::char_traits<EcharT>, class Allocator = std::allocator<EcharT>>
std::basic_string< EcharT, traits, Allocator > string (const Allocator &a=Allocator()) const
std::string string () const
std::wstring wstring () const
std::string u8string () const
std::u16string u16string () const
std::u32string u32string () const
template<class EcharT , class traits = std::char_traits<EcharT>, class Allocator = std::allocator<EcharT>>
std::basic_string< EcharT, traits, Allocator > generic_string (const Allocator &a=Allocator()) const
std::string generic_string () const
std::wstring generic_wstring () const
std::string generic_u8string () const
std::u16string generic_u16string () const
std::u32string generic_u32string () const
int compare (const path &p) const noexcept
int compare (const string_type &s) const
int compare (const value_type *s) const
path root_name () const
path root_directory () const
path root_path () const
path relative_path () const
path parent_path () const
path filename () const
path stem () const
path extension () const
bool empty () const noexcept
bool has_root_name () const
bool has_root_directory () const
bool has_root_path () const
bool has_relative_path () const
bool has_parent_path () const
bool has_filename () const
bool has_stem () const
bool has_extension () const
bool is_absolute () const
bool is_relative () const
path lexically_normal () const
path lexically_relative (const path &base) const
path lexically_proximate (const path &base) const
iterator begin () const
iterator end () const
iterator ()
iterator (const path &p, const impl_string_type::const_iterator &pos)
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
bool operator== (const iterator &other) const
bool operator!= (const iterator &other) const
reference operator* () const
pointer operator-> () const
path () noexcept
path (const path &p)
path (path &&p) noexcept
path (string_type &&source, format fmt=auto_format)
template<class Source , typename = path_from_string<Source>>
path (const Source &source, format fmt=auto_format)
template<class InputIterator >
path (InputIterator first, InputIterator last, format fmt=auto_format)
~path ()
path & operator= (const path &p)
path & operator= (path &&p) noexcept
path & operator= (string_type &&source)
path & assign (string_type &&source)
template<class Source >
path & operator= (const Source &source)
template<class Source >
path & assign (const Source &source)
template<class InputIterator >
path & assign (InputIterator first, InputIterator last)
path & operator/= (const path &p)
template<class Source >
path & operator/= (const Source &source)
template<class Source >
path & append (const Source &source)
template<class InputIterator >
path & append (InputIterator first, InputIterator last)
path & operator+= (const path &x)
path & operator+= (const string_type &x)
path & operator+= (const value_type *x)
path & operator+= (value_type x)
template<class Source >
path_from_string< Source > & operator+= (const Source &x)
template<class EcharT >
path_type_EcharT< EcharT > & operator+= (EcharT x)
template<class Source >
path & concat (const Source &x)
template<class InputIterator >
path & concat (InputIterator first, InputIterator last)
void clear () noexcept
path & make_preferred ()
path & remove_filename ()
path & replace_filename (const path &replacement)
path & replace_extension (const path &replacement=path())
void swap (path &rhs) noexcept
const string_type & native () const noexcept
const value_type * c_str () const noexcept
operator string_type () const
template<class EcharT , class traits = std::char_traits<EcharT>, class Allocator = std::allocator<EcharT>>
std::basic_string< EcharT, traits, Allocator > string (const Allocator &a=Allocator()) const
std::string string () const
std::wstring wstring () const
std::string u8string () const
std::u16string u16string () const
std::u32string u32string () const
template<class EcharT , class traits = std::char_traits<EcharT>, class Allocator = std::allocator<EcharT>>
std::basic_string< EcharT, traits, Allocator > generic_string (const Allocator &a=Allocator()) const
std::string generic_string () const
std::wstring generic_wstring () const
std::string generic_u8string () const
std::u16string generic_u16string () const
std::u32string generic_u32string () const
int compare (const path &p) const noexcept
int compare (const string_type &s) const
int compare (const value_type *s) const
path root_name () const
path root_directory () const
path root_path () const
path relative_path () const
path parent_path () const
path filename () const
path stem () const
path extension () const
bool empty () const noexcept
bool has_root_name () const
bool has_root_directory () const
bool has_root_path () const
bool has_relative_path () const
bool has_parent_path () const
bool has_filename () const
bool has_stem () const
bool has_extension () const
bool is_absolute () const
bool is_relative () const
path lexically_normal () const
path lexically_relative (const path &base) const
path lexically_proximate (const path &base) const
iterator begin () const
iterator end () const
iterator ()
iterator (const path &p, const impl_string_type::const_iterator &pos)
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
bool operator== (const iterator &other) const
bool operator!= (const iterator &other) const
reference operator* () const
pointer operator-> () const
template<> path & assign (const path &source)
template<> path & append (const path &p)
template<> path & assign (const path &source)
template<> path & append (const path &p)
Private Types
using impl_value_type = value_type
using impl_string_type = std::basic_string< impl_value_type >
using impl_value_type = value_type
using impl_string_type = std::basic_string< impl_value_type >
Private Member Functions
void append_name (const value_type *name)
string_type::size_type root_name_length () const noexcept
void postprocess_path_with_format (format fmt)
void check_long_path ()
impl_string_type::const_iterator increment (const impl_string_type::const_iterator &pos) const
impl_string_type::const_iterator decrement (const impl_string_type::const_iterator &pos) const
void updateCurrent ()
void append_name (const value_type *name)
string_type::size_type root_name_length () const noexcept
void postprocess_path_with_format (format fmt)
void check_long_path ()
impl_string_type::const_iterator increment (const impl_string_type::const_iterator &pos) const
impl_string_type::const_iterator decrement (const impl_string_type::const_iterator &pos) const
void updateCurrent ()
Private Attributes
impl_string_type _path
impl_string_type::const_iterator _first
impl_string_type::const_iterator _last
impl_string_type::const_iterator _prefix
impl_string_type::const_iterator _root
impl_string_type::const_iterator _iter
path _current
Static Private Attributes
static constexpr impl_value_type generic_separator = '/'
static const string_type::size_type _prefixLength {0}
Friends
class directory_iterator
class path
void swap (path &lhs, path &rhs) noexcept
size_t hash_value (const path &p) noexcept
path canonical (const path &p, std::error_code &ec)
void swap (path &lhs, path &rhs) noexcept
size_t hash_value (const path &p) noexcept
path canonical (const path &p, std::error_code &ec)
Detailed Description
Definition at line 364 of file filesystem.hpp.
Member Typedef Documentation
const_iterator [1/2]
using ghc::filesystem::path::const_iterator = iterator
Definition at line 567 of file filesystem.hpp.
const_iterator [2/2]
using ghc::filesystem::path::const_iterator = iterator
Definition at line 567 of file filesystem.hpp.
difference_type [1/2]
using ghc::filesystem::path::difference_type = std::ptrdiff_t
Definition at line 671 of file filesystem.hpp.
difference_type [2/2]
using ghc::filesystem::path::difference_type = std::ptrdiff_t
Definition at line 671 of file filesystem.hpp.
impl_string_type [1/2]
using ghc::filesystem::path::impl_string_type = std::basic_string<impl_value_type> [private]
Definition at line 573 of file filesystem.hpp.
impl_string_type [2/2]
using ghc::filesystem::path::impl_string_type = std::basic_string<impl_value_type> [private]
Definition at line 573 of file filesystem.hpp.
impl_value_type [1/2]
using ghc::filesystem::path::impl_value_type = value_type [private]
Definition at line 572 of file filesystem.hpp.
impl_value_type [2/2]
using ghc::filesystem::path::impl_value_type = value_type [private]
Definition at line 572 of file filesystem.hpp.
iterator_category [1/2]
using ghc::filesystem::path::iterator_category = std::bidirectional_iterator_tag
Definition at line 674 of file filesystem.hpp.
iterator_category [2/2]
using ghc::filesystem::path::iterator_category = std::bidirectional_iterator_tag
Definition at line 674 of file filesystem.hpp.
path_from_string [1/2]
template<typename T >
using ghc::filesystem::path::path_from_string = typename std::enable_if<_is_basic_string<T>::value || std::is_same<char const*, typename std::decay<T>::type>::value || std::is_same<char*, typename std::decay<T>::type>::value || std::is_same<char16_t const*, typename std::decay<T>::type>::value || std::is_same<char16_t*, typename std::decay<T>::type>::value || std::is_same<char32_t const*, typename std::decay<T>::type>::value || std::is_same<char32_t*, typename std::decay<T>::type>::value || std::is_same<wchar_t const*, typename std::decay<T>::type>::value || std::is_same<wchar_t*, typename std::decay<T>::type>::value, path>::type
Definition at line 430 of file filesystem.hpp.
path_from_string [2/2]
template<typename T >
using ghc::filesystem::path::path_from_string = typename std::enable_if<_is_basic_string<T>::value || std::is_same<char const*, typename std::decay<T>::type>::value || std::is_same<char*, typename std::decay<T>::type>::value || std::is_same<char16_t const*, typename std::decay<T>::type>::value || std::is_same<char16_t*, typename std::decay<T>::type>::value || std::is_same<char32_t const*, typename std::decay<T>::type>::value || std::is_same<char32_t*, typename std::decay<T>::type>::value || std::is_same<wchar_t const*, typename std::decay<T>::type>::value || std::is_same<wchar_t*, typename std::decay<T>::type>::value, path>::type
Definition at line 430 of file filesystem.hpp.
path_type [1/2]
template<typename T1 , typename T2 = void>
using ghc::filesystem::path::path_type = typename std::enable_if<!std::is_same<path, T1>::value, path>::type
Definition at line 418 of file filesystem.hpp.
path_type [2/2]
template<typename T1 , typename T2 = void>
using ghc::filesystem::path::path_type = typename std::enable_if<!std::is_same<path, T1>::value, path>::type
Definition at line 418 of file filesystem.hpp.
path_type_EcharT [1/2]
template<typename T >
using ghc::filesystem::path::path_type_EcharT = typename std::enable_if<std::is_same<T, char>::value || std::is_same<T, char16_t>::value || std::is_same<T, char32_t>::value || std::is_same<T, wchar_t>::value, path>::type
Definition at line 435 of file filesystem.hpp.
path_type_EcharT [2/2]
template<typename T >
using ghc::filesystem::path::path_type_EcharT = typename std::enable_if<std::is_same<T, char>::value || std::is_same<T, char16_t>::value || std::is_same<T, char32_t>::value || std::is_same<T, wchar_t>::value, path>::type
Definition at line 435 of file filesystem.hpp.
pointer [1/2]
using ghc::filesystem::path::pointer = const path*
Definition at line 672 of file filesystem.hpp.
pointer [2/2]
using ghc::filesystem::path::pointer = const path*
Definition at line 672 of file filesystem.hpp.
reference [1/2]
using ghc::filesystem::path::reference = const path&
Definition at line 673 of file filesystem.hpp.
reference [2/2]
using ghc::filesystem::path::reference = const path&
Definition at line 673 of file filesystem.hpp.
string_type [1/2]
using ghc::filesystem::path::string_type = std::basic_string<value_type>
Definition at line 381 of file filesystem.hpp.
string_type [2/2]
using ghc::filesystem::path::string_type = std::basic_string<value_type>
Definition at line 381 of file filesystem.hpp.
value_type [1/2]
using ghc::filesystem::path::value_type = const path
Definition at line 670 of file filesystem.hpp.
value_type [2/2]
using ghc::filesystem::path::value_type = const path
Definition at line 670 of file filesystem.hpp.
Member Enumeration Documentation
format [1/2]
enum ghc::filesystem::path::format
The path format in which the constructor argument is given.
Enumerator
generic_format The generic format, internally used by ghc::filesystem::path with slashes
native_format The format native to the current platform this code is build for
auto_format Try to auto-detect the format, fallback to native.
generic_format The generic format, internally used by ghc::filesystem::path with slashes
native_format The format native to the current platform this code is build for
auto_format Try to auto-detect the format, fallback to native.
Definition at line 386 of file filesystem.hpp.
                {
        generic_format,
        native_format,
        auto_format,
    };
format [2/2]
enum ghc::filesystem::path::format
The path format in which the constructor argument is given.
Enumerator
generic_format The generic format, internally used by ghc::filesystem::path with slashes
native_format The format native to the current platform this code is build for
auto_format Try to auto-detect the format, fallback to native.
generic_format The generic format, internally used by ghc::filesystem::path with slashes
native_format The format native to the current platform this code is build for
auto_format Try to auto-detect the format, fallback to native.
Definition at line 386 of file filesystem.hpp.
                {
        generic_format,
        native_format,
        auto_format,
    };
Constructor & Destructor Documentation
path() [1/12]
ghc::filesystem::path::path () [noexcept]
path() [2/12]
GHC_INLINE ghc::filesystem::path::path (const path & p)
Definition at line 2366 of file filesystem.hpp.
    : _path(p._path)
#if defined(GHC_OS_WINDOWS) && defined(GHC_WIN_AUTO_PREFIX_LONG_PATH)
    , _prefixLength(p._prefixLength)
#endif
{
}
path() [3/12]
GHC_INLINE ghc::filesystem::path::path (path && p) [noexcept]
Definition at line 2374 of file filesystem.hpp.
    : _path(std::move(p._path))
#if defined(GHC_OS_WINDOWS) && defined(GHC_WIN_AUTO_PREFIX_LONG_PATH)
    , _prefixLength(p._prefixLength)
#endif
{
}
path() [4/12]
GHC_INLINE ghc::filesystem::path::path (string_type && source, format fmt = auto_format)
Definition at line 2382 of file filesystem.hpp.
    : _path(std::move(source))
{
    postprocess_path_with_format(fmt);
}
References fmt, and postprocess_path_with_format().
path() [5/12]
template<class Source , typename >
ghc::filesystem::path::path (const Source & source, format fmt = auto_format) [inline]
Definition at line 1780 of file filesystem.hpp.
    : _path(detail::toWChar(source))
#else
    : _path(detail::toUtf8(source))
#endif
{
    postprocess_path_with_format(fmt);
}
References fmt.
path() [6/12]
template<class InputIterator >
ghc::filesystem::path::path (InputIterator first, InputIterator last, format fmt = auto_format) [inline]
Definition at line 1802 of file filesystem.hpp.
    : path(std::basic_string<typename std::iterator_traits<InputIterator>::value_type>(first, last), fmt)
{
    // delegated
}
 path() [1/2]
GHC_INLINE ghc::filesystem::path::~path ()
Definition at line 2414 of file filesystem.hpp.
{}
path() [7/12]
ghc::filesystem::path::path () [noexcept]
path() [8/12]
ghc::filesystem::path::path (const path & p)
path() [9/12]
ghc::filesystem::path::path (path && p) [noexcept]
path() [10/12]
ghc::filesystem::path::path (string_type && source, format fmt = auto_format)
path() [11/12]
template<class Source , typename = path_from_string<Source>>
ghc::filesystem::path::path (const Source & source, format fmt = auto_format)
path() [12/12]
template<class InputIterator >
ghc::filesystem::path::path (InputIterator first, InputIterator last, format fmt = auto_format)
 path() [2/2]
ghc::filesystem::path::~path ()
Member Function Documentation
append() [1/6]
template<>
path & ghc::filesystem::path::append (const path & p) [inline]
Definition at line 2556 of file filesystem.hpp.
{
    return this->operator/=(p);
}
References operator/=().
append() [2/6]
template<>
path & ghc::filesystem::path::append (const path & p) [inline]
Definition at line 2556 of file filesystem.hpp.
{
    return this->operator/=(p);
}
References operator/=().
append() [3/6]
template<class Source >
path & ghc::filesystem::path::append (const Source & source) [inline]
Definition at line 2550 of file filesystem.hpp.
{
    return this->operator/=(path(source));
}
References operator/=(), and path.
Referenced by append(), operator/=(), and replace_filename().
append() [4/6]
template<class Source >
path & ghc::filesystem::path::append (const Source & source)
append() [5/6]
template<class InputIterator >
path & ghc::filesystem::path::append (InputIterator first, InputIterator last) [inline]
Definition at line 2562 of file filesystem.hpp.
{
    std::basic_string<typename std::iterator_traits<InputIterator>::value_type> part(first, last);
    return append(part);
}
References append().
append() [6/6]
template<class InputIterator >
path & ghc::filesystem::path::append (InputIterator first, InputIterator last)
append_name() [1/2]
GHC_INLINE void ghc::filesystem::path::append_name (const value_type * name) [private]
Definition at line 2527 of file filesystem.hpp.
{
    if (_path.empty()) {
        this->operator/=(path(name));
    }
    else {
        if (_path.back() != path::preferred_separator) {
            _path.push_back(path::preferred_separator);
        }
        _path += name;
        check_long_path();
    }
}
References _path, check_long_path(), setup::name, operator/=(), path, and ghc::filesystem::path_helper_base< std::string::value_type >::preferred_separator.
Referenced by ghc::filesystem::directory_iterator::impl::increment().
append_name() [2/2]
void ghc::filesystem::path::append_name (const value_type * name) [private]
assign() [1/8]
template<>
path & ghc::filesystem::path::assign (const path & source) [inline]
Definition at line 2470 of file filesystem.hpp.
{
    _path = source._path;
#if defined(GHC_OS_WINDOWS) && defined(GHC_WIN_AUTO_PREFIX_LONG_PATH)
    _prefixLength = source._prefixLength;
#endif
    return *this;
}
References _path, and _prefixLength.
assign() [2/8]
template<>
path & ghc::filesystem::path::assign (const path & source) [inline]
Definition at line 2470 of file filesystem.hpp.
{
    _path = source._path;
#if defined(GHC_OS_WINDOWS) && defined(GHC_WIN_AUTO_PREFIX_LONG_PATH)
    _prefixLength = source._prefixLength;
#endif
    return *this;
}
References _path, and _prefixLength.
assign() [3/8]
template<class Source >
path & ghc::filesystem::path::assign (const Source & source) [inline]
Definition at line 2458 of file filesystem.hpp.
{
#ifdef GHC_USE_WCHAR_T
    _path.assign(detail::toWChar(source));
#else
    _path.assign(detail::toUtf8(source));
#endif
    postprocess_path_with_format(native_format);
    return *this;
}
References _path, native_format, postprocess_path_with_format(), and ghc::filesystem::detail::toUtf8().
assign() [4/8]
template<class Source >
path & ghc::filesystem::path::assign (const Source & source)
assign() [5/8]
template<class InputIterator >
path & ghc::filesystem::path::assign (InputIterator first, InputIterator last) [inline]
Definition at line 2480 of file filesystem.hpp.
{
    _path.assign(first, last);
    postprocess_path_with_format(native_format);
    return *this;
}
References _path, native_format, and postprocess_path_with_format().
assign() [6/8]
template<class InputIterator >
path & ghc::filesystem::path::assign (InputIterator first, InputIterator last)
assign() [7/8]
GHC_INLINE path & ghc::filesystem::path::assign (path::string_type && source)
Definition at line 2442 of file filesystem.hpp.
{
    _path = std::move(source);
    postprocess_path_with_format(native_format);
    return *this;
}
References _path, native_format, and postprocess_path_with_format().
Referenced by operator/=(), and operator=().
assign() [8/8]
path & ghc::filesystem::path::assign (string_type && source)
begin() [1/2]
GHC_INLINE path::iterator ghc::filesystem::path::begin () const
Definition at line 3353 of file filesystem.hpp.
{
    return iterator(*this, _path.begin());
}
References _path, and iterator().
Referenced by lexically_relative().
begin() [2/2]
iterator ghc::filesystem::path::begin () const
c_str() [1/2]
GHC_INLINE const path::value_type * ghc::filesystem::path::c_str () const [noexcept]
Definition at line 2709 of file filesystem.hpp.
{
    return native().c_str();
}
References native().
Referenced by ghc::filesystem::detail::create_hardlink(), and ghc::filesystem::detail::create_symlink().
c_str() [2/2]
const value_type * ghc::filesystem::path::c_str () const [noexcept]
check_long_path() [1/2]
GHC_INLINE void ghc::filesystem::path::check_long_path () [private]
Definition at line 1724 of file filesystem.hpp.
{
#if defined(GHC_OS_WINDOWS) && defined(GHC_WIN_AUTO_PREFIX_LONG_PATH)
    if (is_absolute() && _path.length() >= MAX_PATH - 12 && !detail::startsWith(_path, impl_string_type(GHC_PLATFORM_LITERAL("\\\\?\\")))) {
        postprocess_path_with_format(native_format);
    }
#endif
}
References _path, GHC_PLATFORM_LITERAL, is_absolute(), native_format, postprocess_path_with_format(), and ghc::filesystem::detail::startsWith().
Referenced by append_name(), operator+=(), and operator/=().
check_long_path() [2/2]
void ghc::filesystem::path::check_long_path () [private]
clear() [1/2]
GHC_INLINE void ghc::filesystem::path::clear () [noexcept]
Definition at line 2654 of file filesystem.hpp.
{
    _path.clear();
#if defined(GHC_OS_WINDOWS) && defined(GHC_WIN_AUTO_PREFIX_LONG_PATH)
    _prefixLength = 0;
#endif
}
References _path, and _prefixLength.
Referenced by ghc::filesystem::absolute(), ghc::filesystem::create_directories(), ghc::filesystem::current_path(), ghc::filesystem::directory_iterator::impl::increment(), ghc::filesystem::temp_directory_path(), and ghc::filesystem::weakly_canonical().
clear() [2/2]
void ghc::filesystem::path::clear () [noexcept]
compare() [1/6]
GHC_INLINE int ghc::filesystem::path::compare (const path & p) const [noexcept]
Definition at line 2867 of file filesystem.hpp.
{
#ifdef LWG_2936_BEHAVIOUR
    auto rnl1 = root_name_length();
    auto rnl2 = p.root_name_length();
#ifdef GHC_OS_WINDOWS
    auto rnc = detail::compare_simple_insensitive(_path.c_str(), rnl1, p._path.c_str(), rnl2);
#else
    auto rnc = _path.compare(0, rnl1, p._path, 0, (std::min(rnl1, rnl2)));
#endif
    if (rnc) {
        return rnc;
    }
    bool hrd1 = has_root_directory(), hrd2 = p.has_root_directory();
    if (hrd1 != hrd2) {
        return hrd1 ? 1 : -1;
    }
    if (hrd1) {
        ++rnl1;
        ++rnl2;
    }
    auto iter1 = _path.begin() + static_cast<int>(rnl1);
    auto iter2 = p._path.begin() + static_cast<int>(rnl2);
    while (iter1 != _path.end() && iter2 != p._path.end() && *iter1 == *iter2) {
        ++iter1;
        ++iter2;
    }
    if (iter1 == _path.end()) {
        return iter2 == p._path.end() ? 0 : -1;
    }
    if (iter2 == p._path.end()) {
        return 1;
    }
    if (*iter1 == preferred_separator) {
        return -1;
    }
    if (*iter2 == preferred_separator) {
        return 1;
    }
    return *iter1 < *iter2 ? -1 : 1;
#else // LWG_2936_BEHAVIOUR
#ifdef GHC_OS_WINDOWS
    auto rnl1 = root_name_length();
    auto rnl2 = p.root_name_length();
    auto rnc = detail::compare_simple_insensitive(_path.c_str(), rnl1, p._path.c_str(), rnl2);
    if (rnc) {
        return rnc;
    }
    return _path.compare(rnl1, std::string::npos, p._path, rnl2, std::string::npos);
#else
    return _path.compare(p._path);
#endif
#endif
}
References ghc::filesystem::detail::compare_simple_insensitive(), and p.
Referenced by compare().
compare() [2/6]
int ghc::filesystem::path::compare (const path & p) const [noexcept]
compare() [3/6]
GHC_INLINE int ghc::filesystem::path::compare (const string_type & s) const
Definition at line 2922 of file filesystem.hpp.
{
    return compare(path(s));
}
References compare(), path, and s.
compare() [4/6]
int ghc::filesystem::path::compare (const string_type & s) const
compare() [5/6]
GHC_INLINE int ghc::filesystem::path::compare (const value_type * s) const
Definition at line 2934 of file filesystem.hpp.
{
    return compare(path(s));
}
References compare(), path, and s.
compare() [6/6]
int ghc::filesystem::path::compare (const value_type * s) const
concat() [1/4]
template<class Source >
path & ghc::filesystem::path::concat (const Source & x) [inline]
Definition at line 2635 of file filesystem.hpp.
{
    path p(x);
    _path += p._path;
    postprocess_path_with_format(native_format);
    return *this;
}
References _path, native_format, p, postprocess_path_with_format(), and x.
Referenced by operator+=(), and replace_extension().
concat() [2/4]
template<class Source >
path & ghc::filesystem::path::concat (const Source & x)
concat() [3/4]
template<class InputIterator >
path & ghc::filesystem::path::concat (InputIterator first, InputIterator last) [inline]
Definition at line 2643 of file filesystem.hpp.
{
    _path.append(first, last);
    postprocess_path_with_format(native_format);
    return *this;
}
References _path, native_format, and postprocess_path_with_format().
concat() [4/4]
template<class InputIterator >
path & ghc::filesystem::path::concat (InputIterator first, InputIterator last)
decrement() [1/2]
impl_string_type::const_iterator ghc::filesystem::path::decrement (const impl_string_type::const_iterator & pos) const [private]
decrement() [2/2]
impl_string_type::const_iterator ghc::filesystem::path::decrement (const impl_string_type::const_iterator & pos) const [private]
empty() [1/2]
GHC_INLINE bool ghc::filesystem::path::empty () const [noexcept]
Definition at line 3073 of file filesystem.hpp.
{
    return _path.empty();
}
References _path.
Referenced by ghc::filesystem::filesystem_error::filesystem_error(), has_extension(), has_filename(), has_parent_path(), has_stem(), ghc::filesystem::directory_iterator::impl::impl(), lexically_normal(), lexically_proximate(), parent_path(), replace_extension(), ghc::filesystem::detail::status_ex(), and ghc::filesystem::weakly_canonical().
empty() [2/2]
bool ghc::filesystem::path::empty () const [noexcept]
end() [1/2]
GHC_INLINE path::iterator ghc::filesystem::path::end () const
Definition at line 3358 of file filesystem.hpp.
{
    return iterator(*this, _path.end());
}
References _path, and iterator().
Referenced by extension(), filename(), lexically_normal(), lexically_relative(), and parent_path().
end() [2/2]
iterator ghc::filesystem::path::end () const
extension() [1/2]
GHC_INLINE path ghc::filesystem::path::extension () const
Definition at line 3037 of file filesystem.hpp.
{
    if (has_relative_path()) {
        auto iter = end();
        const auto& fn = *--iter;
        impl_string_type::size_type pos = fn._path.rfind('.');
        if (pos != std::string::npos && pos > 0) {
            return path(fn._path.substr(pos), native_format);
        }
    }
    return path();
}
References end(), has_relative_path(), native_format, and path.
Referenced by has_extension(), and replace_extension().
extension() [2/2]
path ghc::filesystem::path::extension () const
filename() [1/2]
GHC_INLINE path ghc::filesystem::path::filename () const
Definition at line 3020 of file filesystem.hpp.
{
    return !has_relative_path() ? path() : path(*--end());
}
References end(), has_relative_path(), and path.
Referenced by doxmlparser.compound.listingType::__init__(), doxmlparser.compound.listingType::buildAttributes(), doxmlparser.compound.listingType::exportAttributes(), FileInfo::fileName(), doxmlparser.compound.listingType::get_filename(), has_filename(), remove_filename(), doxmlparser.compound.listingType::set_filename(), and stem().
filename() [2/2]
path ghc::filesystem::path::filename () const
Referenced by doxmlparser.compound.listingType::__init__(), doxmlparser.compound.listingType::buildAttributes(), doxmlparser.compound.listingType::exportAttributes(), doxmlparser.compound.listingType::get_filename(), and doxmlparser.compound.listingType::set_filename().
generic_string() [1/4]
GHC_INLINE std::string ghc::filesystem::path::generic_string () const
Definition at line 2809 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    return generic_string<std::string::value_type, std::string::traits_type, std::string::allocator_type>();
#else
    return _path;
#endif
}
References _path.
generic_string() [2/4]
std::string ghc::filesystem::path::generic_string () const
generic_string() [3/4]
template<class EcharT , class traits , class Allocator >
std::basic_string< EcharT, traits, Allocator > ghc::filesystem::path::generic_string (const Allocator & a = Allocator()) const [inline]
Definition at line 2788 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
#ifdef GHC_USE_WCHAR_T
    auto result = detail::fromWChar<std::basic_string<EcharT, traits, Allocator>, path::string_type>(_path, a);
#else
    auto result = detail::fromUtf8<std::basic_string<EcharT, traits, Allocator>>(_path, a);
#endif
    for (auto& c : result) {
        if (c == preferred_separator) {
            c = generic_separator;
        }
    }
    return result;
#else
    return detail::fromUtf8<std::basic_string<EcharT, traits, Allocator>>(_path, a);
#endif
}
References _path, a, c, generic_separator, and ghc::filesystem::path_helper_base< std::string::value_type >::preferred_separator.
generic_string() [4/4]
template<class EcharT , class traits = std::char_traits<EcharT>, class Allocator = std::allocator<EcharT>>
std::basic_string< EcharT, traits, Allocator > ghc::filesystem::path::generic_string (const Allocator & a = Allocator()) const
generic_u16string() [1/2]
GHC_INLINE std::u16string ghc::filesystem::path::generic_u16string () const
Definition at line 2847 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    return generic_string<std::u16string::value_type, std::u16string::traits_type, std::u16string::allocator_type>();
#else
    return detail::fromUtf8<std::u16string>(_path);
#endif
}
References _path.
generic_u16string() [2/2]
std::u16string ghc::filesystem::path::generic_u16string () const
generic_u32string() [1/2]
GHC_INLINE std::u32string ghc::filesystem::path::generic_u32string () const
Definition at line 2856 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    return generic_string<std::u32string::value_type, std::u32string::traits_type, std::u32string::allocator_type>();
#else
    return detail::fromUtf8<std::u32string>(_path);
#endif
}
References _path.
generic_u32string() [2/2]
std::u32string ghc::filesystem::path::generic_u32string () const
generic_u8string() [1/2]
GHC_INLINE std::string ghc::filesystem::path::generic_u8string () const
Definition at line 2837 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    return generic_string<std::string::value_type, std::string::traits_type, std::string::allocator_type>();
#else
    return _path;
#endif
}
References _path.
generic_u8string() [2/2]
std::string ghc::filesystem::path::generic_u8string () const
generic_wstring() [1/2]
GHC_INLINE std::wstring ghc::filesystem::path::generic_wstring () const
Definition at line 2818 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    return generic_string<std::wstring::value_type, std::wstring::traits_type, std::wstring::allocator_type>();
#else
    return detail::fromUtf8<std::wstring>(_path);
#endif
} // namespace filesystem
References _path.
generic_wstring() [2/2]
std::wstring ghc::filesystem::path::generic_wstring () const
has_extension() [1/2]
GHC_INLINE bool ghc::filesystem::path::has_extension () const
Definition at line 3115 of file filesystem.hpp.
{
    return !extension().empty();
}
References empty(), and extension().
Referenced by replace_extension().
has_extension() [2/2]
bool ghc::filesystem::path::has_extension () const
has_filename() [1/2]
GHC_INLINE bool ghc::filesystem::path::has_filename () const
Definition at line 3105 of file filesystem.hpp.
{
    return has_relative_path() && !filename().empty();
}
References empty(), filename(), and has_relative_path().
Referenced by operator/=(), and remove_filename().
has_filename() [2/2]
bool ghc::filesystem::path::has_filename () const
has_parent_path() [1/2]
GHC_INLINE bool ghc::filesystem::path::has_parent_path () const
Definition at line 3100 of file filesystem.hpp.
{
    return !parent_path().empty();
}
References empty(), and parent_path().
has_parent_path() [2/2]
bool ghc::filesystem::path::has_parent_path () const
has_relative_path() [1/2]
GHC_INLINE bool ghc::filesystem::path::has_relative_path () const
Definition at line 3094 of file filesystem.hpp.
{
    auto rootPathLen = _prefixLength + root_name_length() + (has_root_directory() ? 1 : 0);
    return rootPathLen < _path.length();
}
References _path, _prefixLength, has_root_directory(), and root_name_length().
Referenced by extension(), filename(), and has_filename().
has_relative_path() [2/2]
bool ghc::filesystem::path::has_relative_path () const
has_root_directory() [1/2]
GHC_INLINE bool ghc::filesystem::path::has_root_directory () const
Definition at line 3083 of file filesystem.hpp.
{
    auto rootLen = _prefixLength + root_name_length();
    return (_path.length() > rootLen && _path[rootLen] == preferred_separator);
}
References _path, _prefixLength, ghc::filesystem::path_helper_base< std::string::value_type >::preferred_separator, and root_name_length().
Referenced by has_relative_path(), has_root_path(), is_absolute(), lexically_relative(), operator/=(), parent_path(), relative_path(), and root_directory().
has_root_directory() [2/2]
bool ghc::filesystem::path::has_root_directory () const
has_root_name() [1/2]
GHC_INLINE bool ghc::filesystem::path::has_root_name () const
Definition at line 3078 of file filesystem.hpp.
{
    return root_name_length() > 0;
}
References root_name_length().
Referenced by has_root_path(), and is_absolute().
has_root_name() [2/2]
bool ghc::filesystem::path::has_root_name () const
has_root_path() [1/2]
GHC_INLINE bool ghc::filesystem::path::has_root_path () const
Definition at line 3089 of file filesystem.hpp.
{
    return has_root_name() || has_root_directory();
}
References has_root_directory(), and has_root_name().
has_root_path() [2/2]
bool ghc::filesystem::path::has_root_path () const
has_stem() [1/2]
GHC_INLINE bool ghc::filesystem::path::has_stem () const
Definition at line 3110 of file filesystem.hpp.
{
    return !stem().empty();
}
References empty(), and stem().
has_stem() [2/2]
bool ghc::filesystem::path::has_stem () const
increment() [1/2]
impl_string_type::const_iterator ghc::filesystem::path::increment (const impl_string_type::const_iterator & pos) const [private]
increment() [2/2]
impl_string_type::const_iterator ghc::filesystem::path::increment (const impl_string_type::const_iterator & pos) const [private]
is_absolute() [1/2]
GHC_INLINE bool ghc::filesystem::path::is_absolute () const
Definition at line 3120 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    return has_root_name() && has_root_directory();
#else
    return has_root_directory();
#endif
}
References has_root_directory(), and has_root_name().
Referenced by check_long_path(), is_relative(), lexically_relative(), operator/=(), and postprocess_path_with_format().
is_absolute() [2/2]
bool ghc::filesystem::path::is_absolute () const
is_relative() [1/2]
GHC_INLINE bool ghc::filesystem::path::is_relative () const
Definition at line 3129 of file filesystem.hpp.
{
    return !is_absolute();
}
References is_absolute().
Referenced by FileInfo::absFilePath(), FileInfo::isRelative(), and Dir::isRelativePath().
is_relative() [2/2]
bool ghc::filesystem::path::is_relative () const
iterator() [1/4]
ghc::filesystem::path::iterator ()
Referenced by begin(), and end().
iterator() [2/4]
ghc::filesystem::path::iterator ()
iterator() [3/4]
ghc::filesystem::path::iterator (const path & p, const impl_string_type::const_iterator & pos)
iterator() [4/4]
ghc::filesystem::path::iterator (const path & p, const impl_string_type::const_iterator & pos)
lexically_normal() [1/2]
GHC_INLINE path ghc::filesystem::path::lexically_normal () const
Definition at line 3136 of file filesystem.hpp.
{
    path dest;
    bool lastDotDot = false;
    for (string_type s : *this) {
        if (s == ".") {
            dest /= "";
            continue;
        }
        else if (s == ".." && !dest.empty()) {
            auto root = root_path();
            if (dest == root) {
                continue;
            }
            else if (*(--dest.end()) != "..") {
                if (dest._path.back() == preferred_separator) {
                    dest._path.pop_back();
                }
                dest.remove_filename();
                continue;
            }
        }
        if (!(s.empty() && lastDotDot)) {
            dest /= s;
        }
        lastDotDot = s == "..";
    }
    if (dest.empty()) {
        dest = ".";
    }
    return dest;
}
References _path, empty(), end(), ghc::filesystem::path_helper_base< std::string::value_type >::preferred_separator, remove_filename(), root_path(), and s.
Referenced by FileInfo::absFilePath(), Dir::cleanDirPath(), and ghc::filesystem::weakly_canonical().
lexically_normal() [2/2]
path ghc::filesystem::path::lexically_normal () const
lexically_proximate() [1/2]
GHC_INLINE path ghc::filesystem::path::lexically_proximate (const path & base) const
Definition at line 3204 of file filesystem.hpp.
{
    path result = lexically_relative(base);
    return result.empty() ? *this : result;
}
References empty(), and lexically_relative().
Referenced by ghc::filesystem::proximate().
lexically_proximate() [2/2]
path ghc::filesystem::path::lexically_proximate (const path & base) const
lexically_relative() [1/2]
GHC_INLINE path ghc::filesystem::path::lexically_relative (const path & base) const
Definition at line 3169 of file filesystem.hpp.
{
    if (root_name() != base.root_name() || is_absolute() != base.is_absolute() || (!has_root_directory() && base.has_root_directory())) {
        return path();
    }
    const_iterator a = begin(), b = base.begin();
    while (a != end() && b != base.end() && *a == *b) {
        ++a;
        ++b;
    }
    if (a == end() && b == base.end()) {
        return path(".");
    }
    int count = 0;
    for (const auto& element : input_iterator_range<const_iterator>(b, base.end())) {
        if (element != "." && element != "" && element != "..") {
            ++count;
        }
        else if (element == "..") {
            --count;
        }
    }
    if (count < 0) {
        return path();
    }
    path result;
    for (int i = 0; i < count; ++i) {
        result /= "..";
    }
    for (const auto& element : input_iterator_range<const_iterator>(a, end())) {
        result /= element;
    }
    return result;
}
References a, b, begin(), end(), has_root_directory(), is_absolute(), path, and root_name().
Referenced by lexically_proximate(), and ghc::filesystem::relative().
lexically_relative() [2/2]
path ghc::filesystem::path::lexically_relative (const path & base) const
make_preferred() [1/2]
GHC_INLINE path & ghc::filesystem::path::make_preferred ()
Definition at line 2662 of file filesystem.hpp.
{
    // as this filesystem implementation only uses generic_format
    // internally, this must be a no-op
    return *this;
}
make_preferred() [2/2]
path & ghc::filesystem::path::make_preferred ()
native() [1/2]
GHC_INLINE const path::string_type & ghc::filesystem::path::native () const [noexcept]
Definition at line 2704 of file filesystem.hpp.
{
    return _path;
}
References _path.
Referenced by c_str(), ghc::filesystem::directory_iterator::impl::impl(), operator string_type(), operator/=(), stem(), string(), u8string(), and wstring().
native() [2/2]
const string_type & ghc::filesystem::path::native () const [noexcept]
operator string_type() [1/2]
GHC_INLINE ghc::filesystem::path::operator path::string_type () const
Definition at line 2714 of file filesystem.hpp.
{
    return native();
}
References native().
operator string_type() [2/2]
ghc::filesystem::path::operator string_type () const
operator!=() [1/2]
bool ghc::filesystem::path::operator!= (const iterator & other) const
operator!=() [2/2]
bool ghc::filesystem::path::operator!= (const iterator & other) const
operator*() [1/2]
reference ghc::filesystem::path::operator* () const
operator*() [2/2]
reference ghc::filesystem::path::operator* () const
operator++() [1/4]
iterator & ghc::filesystem::path::operator++ ()
operator++() [2/4]
iterator & ghc::filesystem::path::operator++ ()
operator++() [3/4]
iterator ghc::filesystem::path::operator++ (int)
operator++() [4/4]
iterator ghc::filesystem::path::operator++ (int)
operator+=() [1/12]
GHC_INLINE path & ghc::filesystem::path::operator+= (const path & x)
Definition at line 2573 of file filesystem.hpp.
{
    return concat(x._path);
}
References concat(), and x.
operator+=() [2/12]
path & ghc::filesystem::path::operator+= (const path & x)
operator+=() [3/12]
template<class Source >
path::path_from_string< Source > & ghc::filesystem::path::operator+= (const Source & x) [inline]
Definition at line 2617 of file filesystem.hpp.
{
    return concat(x);
}
References concat(), and x.
operator+=() [4/12]
template<class Source >
path_from_string< Source > & ghc::filesystem::path::operator+= (const Source & x)
operator+=() [5/12]
GHC_INLINE path & ghc::filesystem::path::operator+= (const string_type & x)
Definition at line 2578 of file filesystem.hpp.
{
    return concat(x);
}
References concat(), and x.
operator+=() [6/12]
path & ghc::filesystem::path::operator+= (const string_type & x)
operator+=() [7/12]
GHC_INLINE path & ghc::filesystem::path::operator+= (const value_type * x)
Definition at line 2590 of file filesystem.hpp.
{
#ifdef GHC_WITH_STRING_VIEW
    basic_string_view<value_type> part(x);
#else
    string_type part(x);
#endif
    return concat(part);
}
References concat(), and x.
operator+=() [8/12]
path & ghc::filesystem::path::operator+= (const value_type * x)
operator+=() [9/12]
template<class EcharT >
path::path_type_EcharT< EcharT > & ghc::filesystem::path::operator+= (EcharT x) [inline]
Definition at line 2623 of file filesystem.hpp.
{
#ifdef GHC_WITH_STRING_VIEW
    basic_string_view<EcharT> part(&x, 1);
#else
    std::basic_string<EcharT> part(1, x);
#endif
    concat(part);
    return *this;
}
References concat(), and x.
operator+=() [10/12]
template<class EcharT >
path_type_EcharT< EcharT > & ghc::filesystem::path::operator+= (EcharT x)
operator+=() [11/12]
GHC_INLINE path & ghc::filesystem::path::operator+= (value_type x)
Definition at line 2600 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    if (x == generic_separator) {
        x = preferred_separator;
    }
#endif
    if (_path.empty() || _path.back() != preferred_separator) {
        _path += x;
    }
    check_long_path();
    return *this;
}
References _path, check_long_path(), generic_separator, ghc::filesystem::path_helper_base< std::string::value_type >::preferred_separator, and x.
operator+=() [12/12]
path & ghc::filesystem::path::operator+= (value_type x)
operator--() [1/4]
iterator & ghc::filesystem::path::operator-- ()
operator--() [2/4]
iterator & ghc::filesystem::path::operator-- ()
operator--() [3/4]
iterator ghc::filesystem::path::operator-- (int)
operator--() [4/4]
iterator ghc::filesystem::path::operator-- (int)
operator->() [1/2]
pointer ghc::filesystem::path::operator-> () const
operator->() [2/2]
pointer ghc::filesystem::path::operator-> () const
operator/=() [1/4]
GHC_INLINE path & ghc::filesystem::path::operator/= (const path & p)
Definition at line 2492 of file filesystem.hpp.
{
    if (p.empty()) {
        // was: if ((!has_root_directory() && is_absolute()) || has_filename())
        if (!_path.empty() && _path[_path.length() - 1] != preferred_separator && _path[_path.length() - 1] != ':') {
            _path += preferred_separator;
        }
        return *this;
    }
    if ((p.is_absolute() && (_path != root_name()._path || p._path != "/")) || (p.has_root_name() && p.root_name() != root_name())) {
        assign(p);
        return *this;
    }
    if (p.has_root_directory()) {
        assign(root_name());
    }
    else if ((!has_root_directory() && is_absolute()) || has_filename()) {
        _path += preferred_separator;
    }
    auto iter = p.begin();
    bool first = true;
    if (p.has_root_name()) {
        ++iter;
    }
    while (iter != p.end()) {
        if (!first && !(!_path.empty() && _path[_path.length() - 1] == preferred_separator)) {
            _path += preferred_separator;
        }
        first = false;
        _path += (*iter++).native();
    }
    check_long_path();
    return *this;
}
References _path, assign(), check_long_path(), has_filename(), has_root_directory(), is_absolute(), native(), p, ghc::filesystem::path_helper_base< std::string::value_type >::preferred_separator, and root_name().
Referenced by append(), and append_name().
operator/=() [2/4]
path & ghc::filesystem::path::operator/= (const path & p)
operator/=() [3/4]
template<class Source >
path & ghc::filesystem::path::operator/= (const Source & source) [inline]
Definition at line 2544 of file filesystem.hpp.
{
    return append(source);
}
References append().
operator/=() [4/4]
template<class Source >
path & ghc::filesystem::path::operator/= (const Source & source)
operator=() [1/8]
GHC_INLINE path & ghc::filesystem::path::operator= (const path & p)
Definition at line 2419 of file filesystem.hpp.
{
    _path = p._path;
#if defined(GHC_OS_WINDOWS) && defined(GHC_WIN_AUTO_PREFIX_LONG_PATH)
    _prefixLength = p._prefixLength;
#endif
    return *this;
}
References _path, _prefixLength, and p.
operator=() [2/8]
path & ghc::filesystem::path::operator= (const path & p)
operator=() [3/8]
template<class Source >
path & ghc::filesystem::path::operator= (const Source & source) [inline]
Definition at line 2452 of file filesystem.hpp.
{
    return assign(source);
}
References assign().
operator=() [4/8]
template<class Source >
path & ghc::filesystem::path::operator= (const Source & source)
operator=() [5/8]
GHC_INLINE path & ghc::filesystem::path::operator= (path && p) [noexcept]
Definition at line 2428 of file filesystem.hpp.
{
    _path = std::move(p._path);
#if defined(GHC_OS_WINDOWS) && defined(GHC_WIN_AUTO_PREFIX_LONG_PATH)
    _prefixLength = p._prefixLength;
#endif
    return *this;
}
References p.
operator=() [6/8]
path & ghc::filesystem::path::operator= (path && p) [noexcept]
operator=() [7/8]
GHC_INLINE path & ghc::filesystem::path::operator= (path::string_type && source)
Definition at line 2437 of file filesystem.hpp.
{
    return assign(source);
}
References assign().
operator=() [8/8]
path & ghc::filesystem::path::operator= (string_type && source)
operator==() [1/2]
bool ghc::filesystem::path::operator== (const iterator & other) const
operator==() [2/2]
bool ghc::filesystem::path::operator== (const iterator & other) const
parent_path() [1/2]
GHC_INLINE path ghc::filesystem::path::parent_path () const
Definition at line 2999 of file filesystem.hpp.
{
    auto rootPathLen = _prefixLength + root_name_length() + (has_root_directory() ? 1 : 0);
    if (rootPathLen < _path.length()) {
        if (empty()) {
            return path();
        }
        else {
            auto piter = end();
            auto iter = piter.decrement(_path.end());
            if (iter > _path.begin() + static_cast<long>(rootPathLen) && *iter != preferred_separator) {
                --iter;
            }
            return path(_path.begin(), iter, native_format);
        }
    }
    else {
        return *this;
    }
}
References _path, _prefixLength, empty(), end(), has_root_directory(), native_format, path, ghc::filesystem::path_helper_base< std::string::value_type >::preferred_separator, and root_name_length().
Referenced by has_parent_path().
parent_path() [2/2]
path ghc::filesystem::path::parent_path () const
postprocess_path_with_format() [1/2]
GHC_INLINE void ghc::filesystem::path::postprocess_path_with_format (path::format fmt) [private]
Definition at line 1733 of file filesystem.hpp.
{
#ifdef GHC_RAISE_UNICODE_ERRORS
    if (!detail::validUtf8(_path)) {
        path t;
        t._path = _path;
        throw filesystem_error("Illegal byte sequence for unicode character.", t, std::make_error_code(std::errc::illegal_byte_sequence));
    }
#endif
    switch (fmt) {
#ifdef GHC_OS_WINDOWS
        case path::native_format:
        case path::auto_format:
        case path::generic_format:
            for (auto& c : _path) {
                if (c == generic_separator) {
                    c = preferred_separator;
                }
            }
#ifdef GHC_WIN_AUTO_PREFIX_LONG_PATH
            if (is_absolute() && _path.length() >= MAX_PATH - 12 && !detail::startsWith(_path, impl_string_type(GHC_PLATFORM_LITERAL("\\\\?\\")))) {
                _path = GHC_PLATFORM_LITERAL("\\\\?\\") + _path;
            }
#endif
            handle_prefixes();
            break;
#else
        case path::auto_format:
        case path::native_format:
        case path::generic_format:
            // nothing to do
            break;
#endif
    }
    if (_path.length() > _prefixLength + 2 && _path[_prefixLength] == preferred_separator && _path[_prefixLength + 1] == preferred_separator && _path[_prefixLength + 2] != preferred_separator) {
        impl_string_type::iterator new_end = std::unique(_path.begin() + static_cast<string_type::difference_type>(_prefixLength) + 2, _path.end(), [](path::value_type lhs, path::value_type rhs) { return lhs == rhs && lhs == preferred_separator; });
        _path.erase(new_end, _path.end());
    }
    else {
        impl_string_type::iterator new_end = std::unique(_path.begin() + static_cast<string_type::difference_type>(_prefixLength), _path.end(), [](path::value_type lhs, path::value_type rhs) { return lhs == rhs && lhs == preferred_separator; });
        _path.erase(new_end, _path.end());
    }
}
References _path, _prefixLength, auto_format, c, fmt, generic_format, generic_separator, GHC_PLATFORM_LITERAL, is_absolute(), ghc::filesystem::detail::make_error_code(), native_format, ghc::filesystem::path_helper_base< std::string::value_type >::preferred_separator, ghc::filesystem::detail::startsWith(), and ghc::filesystem::detail::validUtf8().
Referenced by assign(), check_long_path(), concat(), and path().
postprocess_path_with_format() [2/2]
void ghc::filesystem::path::postprocess_path_with_format (format fmt) [private]
relative_path() [1/2]
GHC_INLINE path ghc::filesystem::path::relative_path () const
Definition at line 2993 of file filesystem.hpp.
{
    auto rootPathLen = _prefixLength + root_name_length() + (has_root_directory() ? 1 : 0);
    return path(_path.substr((std::min)(rootPathLen, _path.length())), generic_format);
}
References _path, _prefixLength, generic_format, has_root_directory(), path, and root_name_length().
Referenced by ghc::filesystem::absolute().
relative_path() [2/2]
path ghc::filesystem::path::relative_path () const
remove_filename() [1/2]
GHC_INLINE path & ghc::filesystem::path::remove_filename ()
Definition at line 2669 of file filesystem.hpp.
{
    if (has_filename()) {
        _path.erase(_path.size() - filename()._path.size());
    }
    return *this;
}
References _path, filename(), and has_filename().
Referenced by lexically_normal(), and replace_filename().
remove_filename() [2/2]
path & ghc::filesystem::path::remove_filename ()
replace_extension() [1/2]
GHC_INLINE path & ghc::filesystem::path::replace_extension (const path & replacement = path())
Definition at line 2683 of file filesystem.hpp.
{
    if (has_extension()) {
        _path.erase(_path.size() - extension()._path.size());
    }
    if (!replacement.empty() && replacement._path[0] != '.') {
        _path += '.';
    }
    return concat(replacement);
}
References _path, concat(), empty(), extension(), and has_extension().
replace_extension() [2/2]
path & ghc::filesystem::path::replace_extension (const path & replacement = path())
replace_filename() [1/2]
GHC_INLINE path & ghc::filesystem::path::replace_filename (const path & replacement)
Definition at line 2677 of file filesystem.hpp.
{
    remove_filename();
    return append(replacement);
}
References append(), and remove_filename().
Referenced by ghc::filesystem::directory_entry::replace_filename().
replace_filename() [2/2]
path & ghc::filesystem::path::replace_filename (const path & replacement)
root_directory() [1/2]
GHC_INLINE path ghc::filesystem::path::root_directory () const
Definition at line 2979 of file filesystem.hpp.
{
    if (has_root_directory()) {
        static const path _root_dir(std::string(1, preferred_separator), native_format);
        return _root_dir;
    }
    return path();
}
References has_root_directory(), native_format, path, ghc::filesystem::path_helper_base< std::string::value_type >::preferred_separator, and string.
Referenced by ghc::filesystem::absolute(), and root_path().
root_directory() [2/2]
path ghc::filesystem::path::root_directory () const
root_name() [1/2]
GHC_INLINE path ghc::filesystem::path::root_name () const
Definition at line 2974 of file filesystem.hpp.
{
    return path(_path.substr(_prefixLength, root_name_length()), native_format);
}
References _path, _prefixLength, native_format, path, and root_name_length().
Referenced by ghc::filesystem::absolute(), lexically_relative(), operator/=(), and root_path().
root_name() [2/2]
path ghc::filesystem::path::root_name () const
root_name_length() [1/2]
GHC_INLINE path::string_type::size_type ghc::filesystem::path::root_name_length () const [private], [noexcept]
Definition at line 2955 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    if (_path.length() >= _prefixLength + 2 && std::toupper(static_cast<unsigned char>(_path[_prefixLength])) >= 'A' && std::toupper(static_cast<unsigned char>(_path[_prefixLength])) <= 'Z' && _path[_prefixLength + 1] == ':') {
        return 2;
    }
#endif
    if (_path.length() > _prefixLength + 2 && _path[_prefixLength] == preferred_separator && _path[_prefixLength + 1] == preferred_separator && _path[_prefixLength + 2] != preferred_separator && std::isprint(_path[_prefixLength + 2])) {
        impl_string_type::size_type pos = _path.find(preferred_separator, _prefixLength + 3);
        if (pos == impl_string_type::npos) {
            return _path.length();
        }
        else {
            return pos;
        }
    }
    return 0;
}
References _path, _prefixLength, ghc::filesystem::path_helper_base< std::string::value_type >::preferred_separator, and caseconvert::toupper.
Referenced by has_relative_path(), has_root_directory(), has_root_name(), parent_path(), relative_path(), and root_name().
root_name_length() [2/2]
string_type::size_type ghc::filesystem::path::root_name_length () const [private], [noexcept]
root_path() [1/2]
GHC_INLINE path ghc::filesystem::path::root_path () const
Definition at line 2988 of file filesystem.hpp.
{
    return path(root_name().string() + root_directory().string(), native_format);
}
References native_format, path, root_directory(), and root_name().
Referenced by lexically_normal().
root_path() [2/2]
path ghc::filesystem::path::root_path () const
stem() [1/2]
GHC_INLINE path ghc::filesystem::path::stem () const
Definition at line 3025 of file filesystem.hpp.
{
    impl_string_type fn = filename().native();
    if (fn != "." && fn != "..") {
        impl_string_type::size_type pos = fn.rfind('.');
        if (pos != impl_string_type::npos && pos > 0) {
            return path{fn.substr(0, pos), native_format};
        }
    }
    return path{fn, native_format};
}
References filename(), native(), and native_format.
Referenced by has_stem().
stem() [2/2]
path ghc::filesystem::path::stem () const
string() [1/4]
GHC_INLINE std::string ghc::filesystem::path::string () const
Definition at line 2733 of file filesystem.hpp.
{
#ifdef GHC_USE_WCHAR_T
    return detail::toUtf8(native());
#else
    return native();
#endif
}
References native(), and ghc::filesystem::detail::toUtf8().
string() [2/4]
std::string ghc::filesystem::path::string () const
string() [3/4]
template<class EcharT , class traits , class Allocator >
std::basic_string< EcharT, traits, Allocator > ghc::filesystem::path::string (const Allocator & a = Allocator()) const [inline]
Definition at line 2722 of file filesystem.hpp.
{
#ifdef GHC_USE_WCHAR_T
    return detail::fromWChar<std::basic_string<EcharT, traits, Allocator>>(_path, a);
#else
    return detail::fromUtf8<std::basic_string<EcharT, traits, Allocator>>(_path, a);
#endif
}
References _path, and a.
Referenced by FileInfo::absFilePath(), Dir::absPath(), Dir::cleanDirPath(), Dir::currentDirPath(), FileInfo::fileName(), ghc::filesystem::filesystem_error::filesystem_error(), and FileInfo::readLink().
string() [4/4]
template<class EcharT , class traits = std::char_traits<EcharT>, class Allocator = std::allocator<EcharT>>
std::basic_string< EcharT, traits, Allocator > ghc::filesystem::path::string (const Allocator & a = Allocator()) const
swap() [1/2]
GHC_INLINE void ghc::filesystem::path::swap (path & rhs) [noexcept]
Definition at line 2694 of file filesystem.hpp.
{
    _path.swap(rhs._path);
#if defined(GHC_OS_WINDOWS) && defined(GHC_WIN_AUTO_PREFIX_LONG_PATH)
    std::swap(_prefixLength, rhs._prefixLength);
#endif
}
References ghc::filesystem::swap().
swap() [2/2]
void ghc::filesystem::path::swap (path & rhs) [noexcept]
u16string() [1/2]
GHC_INLINE std::u16string ghc::filesystem::path::u16string () const
Definition at line 2771 of file filesystem.hpp.
{
    // TODO: optimize
    return detail::fromUtf8<std::u16string>(string());
}
u16string() [2/2]
std::u16string ghc::filesystem::path::u16string () const
u32string() [1/2]
GHC_INLINE std::u32string ghc::filesystem::path::u32string () const
Definition at line 2777 of file filesystem.hpp.
{
    // TODO: optimize
    return detail::fromUtf8<std::u32string>(string());
}
u32string() [2/2]
std::u32string ghc::filesystem::path::u32string () const
u8string() [1/2]
GHC_INLINE std::string ghc::filesystem::path::u8string () const
Definition at line 2761 of file filesystem.hpp.
{
#ifdef GHC_USE_WCHAR_T
    return detail::toUtf8(native());
#else
    return native();
#endif
}
References native(), and ghc::filesystem::detail::toUtf8().
u8string() [2/2]
std::string ghc::filesystem::path::u8string () const
updateCurrent() [1/2]
void ghc::filesystem::path::updateCurrent () [private]
updateCurrent() [2/2]
void ghc::filesystem::path::updateCurrent () [private]
wstring() [1/2]
GHC_INLINE std::wstring ghc::filesystem::path::wstring () const
Definition at line 2742 of file filesystem.hpp.
{
#ifdef GHC_USE_WCHAR_T
    return native();
#else
    return detail::fromUtf8<std::wstring>(native());
#endif
}
References native().
wstring() [2/2]
std::wstring ghc::filesystem::path::wstring () const
Friends And Related Function Documentation
canonical [1/2]
path canonical (const path & p, std::error_code & ec) [friend]
Definition at line 3603 of file filesystem.hpp.
{
    if (p.empty()) {
        ec = detail::make_error_code(detail::portable_error::not_found);
        return path();
    }
    path work = p.is_absolute() ? p : absolute(p, ec);
    path result;
    auto fs = status(work, ec);
    if (ec) {
        return path();
    }
    if (fs.type() == file_type::not_found) {
        ec = detail::make_error_code(detail::portable_error::not_found);
        return path();
    }
    bool redo;
    do {
        auto rootPathLen = work._prefixLength + work.root_name_length() + (work.has_root_directory() ? 1 : 0);
        redo = false;
        result.clear();
        for (auto pe : work) {
            if (pe.empty() || pe == ".") {
                continue;
            }
            else if (pe == "..") {
                result = result.parent_path();
                continue;
            }
            else if ((result / pe).string().length() <= rootPathLen) {
                result /= pe;
                continue;
            }
            auto sls = symlink_status(result / pe, ec);
            if (ec) {
                return path();
            }
            if (is_symlink(sls)) {
                redo = true;
                auto target = read_symlink(result / pe, ec);
                if (ec) {
                    return path();
                }
                if (target.is_absolute()) {
                    result = target;
                    continue;
                }
                else {
                    result /= target;
                    continue;
                }
            }
            else {
                result /= pe;
            }
        }
        work = result;
    } while (redo);
    ec.clear();
    return result;
}
canonical [2/2]
path canonical (const path & p, std::error_code & ec) [friend]
Definition at line 3603 of file filesystem.hpp.
{
    if (p.empty()) {
        ec = detail::make_error_code(detail::portable_error::not_found);
        return path();
    }
    path work = p.is_absolute() ? p : absolute(p, ec);
    path result;
    auto fs = status(work, ec);
    if (ec) {
        return path();
    }
    if (fs.type() == file_type::not_found) {
        ec = detail::make_error_code(detail::portable_error::not_found);
        return path();
    }
    bool redo;
    do {
        auto rootPathLen = work._prefixLength + work.root_name_length() + (work.has_root_directory() ? 1 : 0);
        redo = false;
        result.clear();
        for (auto pe : work) {
            if (pe.empty() || pe == ".") {
                continue;
            }
            else if (pe == "..") {
                result = result.parent_path();
                continue;
            }
            else if ((result / pe).string().length() <= rootPathLen) {
                result /= pe;
                continue;
            }
            auto sls = symlink_status(result / pe, ec);
            if (ec) {
                return path();
            }
            if (is_symlink(sls)) {
                redo = true;
                auto target = read_symlink(result / pe, ec);
                if (ec) {
                    return path();
                }
                if (target.is_absolute()) {
                    result = target;
                    continue;
                }
                else {
                    result /= target;
                    continue;
                }
            }
            else {
                result /= pe;
            }
        }
        work = result;
    } while (redo);
    ec.clear();
    return result;
}
directory_iterator
directory_iterator [friend]
Definition at line 574 of file filesystem.hpp.
hash_value [1/2]
size_t hash_value (const path & p) [friend]
Definition at line 3370 of file filesystem.hpp.
{
    return std::hash<std::string>()(p.generic_string());
}
hash_value [2/2]
size_t hash_value (const path & p) [friend]
Definition at line 3370 of file filesystem.hpp.
{
    return std::hash<std::string>()(p.generic_string());
}
path
GHC_INLINE ghc::filesystem::path::path [friend]
Definition at line 688 of file filesystem.hpp.
Referenced by append(), append_name(), compare(), extension(), filename(), lexically_relative(), parent_path(), relative_path(), root_directory(), root_name(), and root_path().
swap [1/2]
void swap (path & lhs, path & rhs) [friend]
Definition at line 3365 of file filesystem.hpp.
{
    swap(lhs._path, rhs._path);
}
swap [2/2]
void swap (path & lhs, path & rhs) [friend]
Definition at line 3365 of file filesystem.hpp.
{
    swap(lhs._path, rhs._path);
}
Member Data Documentation
_current
path ghc::filesystem::path::_current [private]
Definition at line 697 of file filesystem.hpp.
_first
impl_string_type::const_iterator ghc::filesystem::path::_first [private]
Definition at line 692 of file filesystem.hpp.
_iter
impl_string_type::const_iterator ghc::filesystem::path::_iter [private]
Definition at line 696 of file filesystem.hpp.
_last
impl_string_type::const_iterator ghc::filesystem::path::_last [private]
Definition at line 693 of file filesystem.hpp.
_path
impl_string_type ghc::filesystem::path::_path [private]
Definition at line 604 of file filesystem.hpp.
Referenced by append_name(), assign(), begin(), check_long_path(), clear(), concat(), empty(), end(), generic_string(), generic_u16string(), generic_u32string(), generic_u8string(), generic_wstring(), has_relative_path(), has_root_directory(), lexically_normal(), native(), operator+=(), operator/=(), operator=(), parent_path(), postprocess_path_with_format(), relative_path(), remove_filename(), replace_extension(), root_name(), root_name_length(), and string().
_prefix
impl_string_type::const_iterator ghc::filesystem::path::_prefix [private]
Definition at line 694 of file filesystem.hpp.
_prefixLength
static const string_type::size_type ghc::filesystem::path::_prefixLength {0} [static], [private]
Definition at line 614 of file filesystem.hpp.
Referenced by assign(), clear(), has_relative_path(), has_root_directory(), operator=(), parent_path(), postprocess_path_with_format(), relative_path(), root_name(), and root_name_length().
_root
impl_string_type::const_iterator ghc::filesystem::path::_root [private]
Definition at line 695 of file filesystem.hpp.
generic_separator
static constexpr impl_value_type ghc::filesystem::path::generic_separator = '/' [static], [constexpr], [private]
Definition at line 576 of file filesystem.hpp.
Referenced by generic_string(), operator+=(), and postprocess_path_with_format().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/filesystem/filesystem.hpp
doxygen/filesystem/filesystem.hpp