TranslatorAdapter_1_9_5 Class Reference
#include <translator_adapter.h>
Public Member Functions
virtual QCString updateNeededMessage ()
virtual QCString trFlowchart ()
virtual QCString updateNeededMessage ()
virtual QCString trFlowchart ()
Additional Inherited Members
Detailed Description
Definition at line 43 of file translator_adapter.h.
Member Function Documentation
trFlowchart() [1/2]
virtual QCString TranslatorAdapter_1_9_5::trFlowchart () [inline], [virtual]
Implements Translator.
Definition at line 49 of file translator_adapter.h.
    { return english.trFlowchart(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trFlowchart().
trFlowchart() [2/2]
virtual QCString TranslatorAdapter_1_9_5::trFlowchart () [inline], [virtual]
Implements Translator.
Definition at line 49 of file translator_adapter.h.
    { return english.trFlowchart(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trFlowchart().
updateNeededMessage() [1/2]
virtual QCString TranslatorAdapter_1_9_5::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Implements TranslatorAdapterBase.
Reimplemented in TranslatorAdapter_1_9_4, TranslatorAdapter_1_9_2, TranslatorAdapter_1_8_19, TranslatorAdapter_1_8_15, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_9_4, TranslatorAdapter_1_9_2, TranslatorAdapter_1_8_19, TranslatorAdapter_1_8_15, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 46 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.9.5"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
updateNeededMessage() [2/2]
virtual QCString TranslatorAdapter_1_9_5::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Implements TranslatorAdapterBase.
Reimplemented in TranslatorAdapter_1_9_4, TranslatorAdapter_1_9_2, TranslatorAdapter_1_8_19, TranslatorAdapter_1_8_15, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_9_4, TranslatorAdapter_1_9_2, TranslatorAdapter_1_8_19, TranslatorAdapter_1_8_15, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 46 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.9.5"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_adapter.h
doxygen/src/translator_adapter.h