TemplateNodeCycle Class Reference
Class representing an 'cycle' tag in a template.
Public Member Functions
TemplateNodeCycle (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
TemplateNodeCycle (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
Private Attributes
size_t m_index = 0
ExprAstList m_args
Additional Inherited Members
Detailed Description
Class representing an 'cycle' tag in a template.
Definition at line 4247 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeCycle() [1/2]
TemplateNodeCycle::TemplateNodeCycle (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4250 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeCycle>(parser,parent,line)
    {
      TRACE(("{TemplateNodeCycle(%s)\n",qPrint(data)));
      m_index=0;
      ExpressionParser expParser(parser,line);
      std::vector<QCString> args = split(data," ");
      auto it = args.begin();
      while (it!=args.end())
      {
        ExprAstPtr expr = expParser.parse(*it);
        if (expr)
        {
          m_args.emplace_back(std::move(expr));
        }
        ++it;
      }
      if (m_args.size()<2)
      {
          parser->warn(parser->templateName(),line,"expected at least two arguments for cycle command, got %zu",m_args.size());
      }
      TRACE(("}TemplateNodeCycle(%s)\n",qPrint(data)));
    }
References data, m_args, m_index, ExpressionParser::parse(), qPrint(), split(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
TemplateNodeCycle() [2/2]
TemplateNodeCycle::TemplateNodeCycle (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4250 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeCycle>(parser,parent,line)
    {
      TRACE(("{TemplateNodeCycle(%s)\n",qPrint(data)));
      m_index=0;
      ExpressionParser expParser(parser,line);
      std::vector<QCString> args = split(data," ");
      auto it = args.begin();
      while (it!=args.end())
      {
        ExprAstPtr expr = expParser.parse(*it);
        if (expr)
        {
          m_args.emplace_back(std::move(expr));
        }
        ++it;
      }
      if (m_args.size()<2)
      {
          parser->warn(parser->templateName(),line,"expected at least two arguments for cycle command, got %zu",m_args.size());
      }
      TRACE(("}TemplateNodeCycle(%s)\n",qPrint(data)));
    }
References data, m_args, m_index, ExpressionParser::parse(), qPrint(), split(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeCycle::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4273 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_index<m_args.size())
      {
        TemplateVariant v = m_args[m_index]->resolve(c);
        if (v.isFunction())
        {
          v = v.call();
        }
        if (ci->escapeIntf() && !v.raw())
        {
          if (ci->needsRecoding())
          {
            ts << ci->recode(ci->escapeIntf()->escape(v.toString()));
          }
          else
          {
            ts << ci->escapeIntf()->escape(v.toString());
          }
        }
        else
        {
          if (ci->needsRecoding())
          {
            ts << ci->recode(v.toString());
          }
          else
          {
            ts << v.toString();
          }
        }
      }
      if (++m_index==m_args.size()) // wrap around
      {
        m_index=0;
      }
    }
References c, TemplateVariant::call(), TemplateEscapeIntf::escape(), TemplateContextImpl::escapeIntf(), TemplateVariant::isFunction(), m_args, m_index, TemplateNodeCreator< TemplateNodeCycle >::m_line, TemplateNodeCreator< TemplateNodeCycle >::m_templateName, TemplateContextImpl::needsRecoding(), TemplateVariant::raw(), TemplateContextImpl::recode(), TemplateContextImpl::setLocation(), and TemplateVariant::toString().
render() [2/2]
void TemplateNodeCycle::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4273 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_index<m_args.size())
      {
        TemplateVariant v = m_args[m_index]->resolve(c);
        if (v.isFunction())
        {
          v = v.call();
        }
        if (ci->escapeIntf() && !v.raw())
        {
          if (ci->needsRecoding())
          {
            ts << ci->recode(ci->escapeIntf()->escape(v.toString()));
          }
          else
          {
            ts << ci->escapeIntf()->escape(v.toString());
          }
        }
        else
        {
          if (ci->needsRecoding())
          {
            ts << ci->recode(v.toString());
          }
          else
          {
            ts << v.toString();
          }
        }
      }
      if (++m_index==m_args.size()) // wrap around
      {
        m_index=0;
      }
    }
References c, TemplateVariant::call(), TemplateEscapeIntf::escape(), TemplateContextImpl::escapeIntf(), TemplateVariant::isFunction(), m_args, m_index, TemplateNodeCreator< TemplateNodeCycle >::m_line, TemplateNodeCreator< TemplateNodeCycle >::m_templateName, TemplateContextImpl::needsRecoding(), TemplateVariant::raw(), TemplateContextImpl::recode(), TemplateContextImpl::setLocation(), and TemplateVariant::toString().
Member Data Documentation
m_args
ExprAstList TemplateNodeCycle::m_args [private]
Definition at line 4315 of file template.cpp.
Referenced by render(), and TemplateNodeCycle().
m_index
size_t TemplateNodeCycle::m_index = 0 [private]
Definition at line 4314 of file template.cpp.
Referenced by render(), and TemplateNodeCycle().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp