SearchIndicesContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
SearchIndicesContext ()
virtual ~SearchIndicesContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
SearchIndicesContext ()
virtual ~SearchIndicesContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc ()
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 1375 of file context.h.
Constructor & Destructor Documentation
SearchIndicesContext() [1/2]
SearchIndicesContext::SearchIndicesContext ()
Definition at line 8826 of file context.cpp.
                                           : p(std::make_unique<Private>())
{
}
 SearchIndicesContext() [1/2]
SearchIndicesContext::~SearchIndicesContext () [virtual]
Definition at line 8830 of file context.cpp.
{
}
SearchIndicesContext() [2/2]
SearchIndicesContext::SearchIndicesContext ()
 SearchIndicesContext() [2/2]
virtual SearchIndicesContext::~SearchIndicesContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr SearchIndicesContext::alloc () [inline], [static]
Definition at line 1378 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<SearchIndicesContext>()); }
Referenced by generateOutputViaTemplate().
alloc() [2/2]
static TemplateListIntfPtr SearchIndicesContext::alloc () [inline], [static]
Definition at line 1378 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<SearchIndicesContext>()); }
at() [1/2]
TemplateVariant SearchIndicesContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 8840 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant SearchIndicesContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t SearchIndicesContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 8835 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t SearchIndicesContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr SearchIndicesContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 8845 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr SearchIndicesContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > SearchIndicesContext::p [private]
Definition at line 1391 of file context.h.
Referenced by at(), count(), createIterator(), LatexSpaceless::remove(), and HtmlSpaceless::remove().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp