TemplateNodeText Class Reference
Class representing a piece of plain text in a template.
Public Member Functions
TemplateNodeText (TemplateParser *, TemplateNode *parent, int, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
TemplateNodeText (TemplateParser *, TemplateNode *parent, int, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
Private Attributes
QCString m_data
Detailed Description
Class representing a piece of plain text in a template.
Definition at line 2926 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeText() [1/2]
TemplateNodeText::TemplateNodeText (TemplateParser * , TemplateNode * parent, int , const QCString & data) [inline]
Definition at line 2929 of file template.cpp.
      : TemplateNode(parent), m_data(data)
    {
      TRACE(("TemplateNodeText('%s')\n",replace(data,'\n',' ').data()));
    }
References data, reg::replace(), and TRACE.
TemplateNodeText() [2/2]
TemplateNodeText::TemplateNodeText (TemplateParser * , TemplateNode * parent, int , const QCString & data) [inline]
Definition at line 2929 of file template.cpp.
      : TemplateNode(parent), m_data(data)
    {
      TRACE(("TemplateNodeText('%s')\n",replace(data,'\n',' ').data()));
    }
References data, reg::replace(), and TRACE.
Member Function Documentation
render() [1/2]
void TemplateNodeText::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 2935 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      //printf("TemplateNodeText::render(%s) needsRecoding=%d ci=%p\n",qPrint(m_data),ci->needsRecoding(),ci);
      if (ci->spacelessEnabled())
      {
        if (ci->needsRecoding())
        {
          ts << ci->recode(ci->spacelessIntf()->remove(m_data));
        }
        else
        {
          ts << ci->spacelessIntf()->remove(m_data);
        }
      }
      else
      {
        if (ci->needsRecoding())
        {
          ts << ci->recode(m_data);
        }
        else
        {
          ts << m_data;
        }
      }
    }
References c, m_data, TemplateContextImpl::needsRecoding(), TemplateContextImpl::recode(), TemplateContextImpl::spacelessEnabled(), and TemplateContextImpl::spacelessIntf().
render() [2/2]
void TemplateNodeText::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 2935 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      //printf("TemplateNodeText::render(%s) needsRecoding=%d ci=%p\n",qPrint(m_data),ci->needsRecoding(),ci);
      if (ci->spacelessEnabled())
      {
        if (ci->needsRecoding())
        {
          ts << ci->recode(ci->spacelessIntf()->remove(m_data));
        }
        else
        {
          ts << ci->spacelessIntf()->remove(m_data);
        }
      }
      else
      {
        if (ci->needsRecoding())
        {
          ts << ci->recode(m_data);
        }
        else
        {
          ts << m_data;
        }
      }
    }
References c, m_data, TemplateContextImpl::needsRecoding(), TemplateContextImpl::recode(), TemplateContextImpl::spacelessEnabled(), and TemplateContextImpl::spacelessIntf().
Member Data Documentation
m_data
QCString TemplateNodeText::m_data [private]
Definition at line 2964 of file template.cpp.
Referenced by render().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp