ConfigInt Class Reference
#include <configimpl.h>
Public Member Functions
ConfigInt (const char *name, const char *doc, int minVal, int maxVal, int defVal)
QCString * valueStringRef ()
int * valueRef ()
int minVal () const
int maxVal () const
void convertStrToVal (Config::CompareMode compareMode)
void substEnvVars ()
void writeTemplate (TextStream &t, bool sl, bool upd)
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)
void writeXMLDoxyfile (TextStream &t)
void init ()
bool isDefault ()
ConfigInt (const char *name, const char *doc, int minVal, int maxVal, int defVal)
QCString * valueStringRef ()
int * valueRef ()
int minVal () const
int maxVal () const
void convertStrToVal (Config::CompareMode compareMode)
void substEnvVars ()
void writeTemplate (TextStream &t, bool sl, bool upd)
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)
void writeXMLDoxyfile (TextStream &t)
void init ()
bool isDefault ()
Private Attributes
int m_value
int m_defValue
int m_minVal
int m_maxVal
QCString m_valueString
Additional Inherited Members
Detailed Description
Class representing an integer type option.
Definition at line 217 of file configimpl.h.
Constructor & Destructor Documentation
ConfigInt() [1/2]
ConfigInt::ConfigInt (const char * name, const char * doc, int minVal, int maxVal, int defVal) [inline]
Definition at line 220 of file configimpl.h.
      : ConfigOption(O_Int)
    {
      m_name = name;
      m_doc = doc;
      m_value = defVal;
      m_defValue = defVal;
      m_minVal = minVal;
      m_maxVal = maxVal;
    }
References m_defValue, ConfigOption::m_doc, m_maxVal, m_minVal, ConfigOption::m_name, m_value, maxVal(), minVal(), and ConfigOption::name().
ConfigInt() [2/2]
ConfigInt::ConfigInt (const char * name, const char * doc, int minVal, int maxVal, int defVal) [inline]
Definition at line 220 of file configimpl.h.
      : ConfigOption(O_Int)
    {
      m_name = name;
      m_doc = doc;
      m_value = defVal;
      m_defValue = defVal;
      m_minVal = minVal;
      m_maxVal = maxVal;
    }
References m_defValue, ConfigOption::m_doc, m_maxVal, m_minVal, ConfigOption::m_name, m_value, maxVal(), minVal(), and ConfigOption::name().
Member Function Documentation
compareDoxyfile() [1/2]
void ConfigInt::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) [virtual]
Implements ConfigOption.
Definition at line 547 of file configimpl.l.
{
  if (!isDefault() || ((compareMode == Config::CompareMode::CompressedNoEnv) && containsEnvVar(m_valueString))) writeTemplate(t,TRUE,TRUE);
}
References Config::CompressedNoEnv, containsEnvVar(), isDefault(), m_valueString, TRUE, and writeTemplate().
compareDoxyfile() [2/2]
void ConfigInt::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) [virtual]
Implements ConfigOption.
convertStrToVal() [1/2]
void ConfigInt::convertStrToVal (Config::CompareMode compareMode) [virtual]
Reimplemented from ConfigOption.
Definition at line 207 of file configimpl.l.
{
  if (!m_valueString.isEmpty())
  {
    if (compareMode == Config::CompareMode::CompressedNoEnv)
    {
       if (containsEnvVar(m_valueString)) return;
    }
    bool ok;
    int val = m_valueString.toInt(&ok);
    if (!ok || val<m_minVal || val>m_maxVal)
    {
      config_warn("argument '%s' for option %s is not a valid number in the range [%d..%d]!\n"
                "Using the default: %d!\n",qPrint(m_valueString),qPrint(m_name),m_minVal,m_maxVal,m_value);
    }
    else
    {
      m_value=val;
    }
  }
}
References Config::CompressedNoEnv, config_warn(), containsEnvVar(), QCString::isEmpty(), m_maxVal, m_minVal, ConfigOption::m_name, m_value, m_valueString, qPrint(), QCString::toInt(), and testsqlite3::val.
convertStrToVal() [2/2]
void ConfigInt::convertStrToVal (Config::CompareMode compareMode) [virtual]
Reimplemented from ConfigOption.
init() [1/2]
void ConfigInt::init () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 239 of file configimpl.h.
{ m_value = m_defValue; }
References m_defValue, and m_value.
init() [2/2]
void ConfigInt::init () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 239 of file configimpl.h.
{ m_value = m_defValue; }
References m_defValue, and m_value.
isDefault() [1/2]
bool ConfigInt::isDefault () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 240 of file configimpl.h.
{ return m_value == m_defValue; }
References m_defValue, and m_value.
Referenced by compareDoxyfile(), and writeXMLDoxyfile().
isDefault() [2/2]
bool ConfigInt::isDefault () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 240 of file configimpl.h.
{ return m_value == m_defValue; }
References m_defValue, and m_value.
maxVal() [1/2]
int ConfigInt::maxVal () const [inline]
Definition at line 233 of file configimpl.h.
{ return m_maxVal; }
References m_maxVal.
Referenced by ConfigInt().
maxVal() [2/2]
int ConfigInt::maxVal () const [inline]
Definition at line 233 of file configimpl.h.
{ return m_maxVal; }
References m_maxVal.
minVal() [1/2]
int ConfigInt::minVal () const [inline]
Definition at line 232 of file configimpl.h.
{ return m_minVal; }
References m_minVal.
Referenced by ConfigInt().
minVal() [2/2]
int ConfigInt::minVal () const [inline]
Definition at line 232 of file configimpl.h.
{ return m_minVal; }
References m_minVal.
substEnvVars() [1/2]
void ConfigInt::substEnvVars () [virtual]
Implements ConfigOption.
Definition at line 1489 of file configimpl.l.
{
  substEnvVarsInString(m_valueString);
}
References m_valueString, and substEnvVarsInString().
substEnvVars() [2/2]
void ConfigInt::substEnvVars () [virtual]
Implements ConfigOption.
valueRef() [1/2]
int * ConfigInt::valueRef () [inline]
Definition at line 231 of file configimpl.h.
{ return &m_value; }
References m_value.
valueRef() [2/2]
int * ConfigInt::valueRef () [inline]
Definition at line 231 of file configimpl.h.
{ return &m_value; }
References m_value.
valueStringRef() [1/2]
QCString * ConfigInt::valueStringRef () [inline]
Definition at line 230 of file configimpl.h.
{ return &m_valueString; }
References m_valueString.
valueStringRef() [2/2]
QCString * ConfigInt::valueStringRef () [inline]
Definition at line 230 of file configimpl.h.
{ return &m_valueString; }
References m_valueString.
writeTemplate() [1/2]
void ConfigInt::writeTemplate (TextStream & t, bool sl, bool upd) [virtual]
Implements ConfigOption.
Definition at line 523 of file configimpl.l.
{
  if (!sl)
  {
    t << "\n";
    t << convertToComment(m_doc, m_userComment);
    t << "\n";
  }
  else if (!m_userComment.isEmpty())
  {
    t << convertToComment("", m_userComment);
  }
  t << m_name << m_spaces.left(MAX_OPTION_LENGTH-m_name.length()) << "=";
  if (upd && !m_valueString.isEmpty())
  {
    writeStringValue(t,m_valueString);
  }
  else
  {
    writeIntValue(t,m_value);
  }
  t << "\n";
}
References convertToComment(), QCString::isEmpty(), QCString::left(), QCString::length(), ConfigOption::m_doc, ConfigOption::m_name, ConfigOption::m_spaces, ConfigOption::m_userComment, m_value, m_valueString, ConfigOption::MAX_OPTION_LENGTH, caseconvert::sl, ConfigOption::writeIntValue(), and ConfigOption::writeStringValue().
Referenced by compareDoxyfile().
writeTemplate() [2/2]
void ConfigInt::writeTemplate (TextStream & t, bool sl, bool upd) [virtual]
Implements ConfigOption.
writeXMLDoxyfile() [1/2]
void ConfigInt::writeXMLDoxyfile (TextStream & t) [virtual]
Implements ConfigOption.
Definition at line 552 of file configimpl.l.
{
  t << " <option id='" << m_name << "'";
  t << " default='" << (isDefault() ? "yes" : "no") << "'";
  t << " type='int'";
  t << ">";
  t << "<value>";
  writeIntValue(t,m_value,false);
  t << "</value>";
  t << "</option>\n";
}
References isDefault(), ConfigOption::m_name, m_value, and ConfigOption::writeIntValue().
writeXMLDoxyfile() [2/2]
void ConfigInt::writeXMLDoxyfile (TextStream & t) [virtual]
Implements ConfigOption.
Member Data Documentation
m_defValue
int ConfigInt::m_defValue [private]
Definition at line 243 of file configimpl.h.
Referenced by ConfigInt(), init(), and isDefault().
m_maxVal
int ConfigInt::m_maxVal [private]
Definition at line 245 of file configimpl.h.
Referenced by ConfigInt(), convertStrToVal(), and maxVal().
m_minVal
int ConfigInt::m_minVal [private]
Definition at line 244 of file configimpl.h.
Referenced by ConfigInt(), convertStrToVal(), and minVal().
m_value
int ConfigInt::m_value [private]
Definition at line 242 of file configimpl.h.
Referenced by ConfigInt(), convertStrToVal(), init(), isDefault(), valueRef(), writeTemplate(), and writeXMLDoxyfile().
m_valueString
QCString ConfigInt::m_valueString [private]
Definition at line 246 of file configimpl.h.
Referenced by compareDoxyfile(), convertStrToVal(), substEnvVars(), valueStringRef(), and writeTemplate().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/configimpl.h
doxygen/src/configimpl.h
doxygen/build/doxygen/src/configimpl.l
doxygen/src/configimpl.l