FilterKeep Class Reference
The implementation of the `keep` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &args)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &args)
Detailed Description
The implementation of the `keep` filter.
Definition at line 817 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterKeep::apply (const TemplateVariant & v, const TemplateVariant & args) [inline], [static]
Definition at line 820 of file template.cpp.
    {
      if (v.isValid() && (v.isList()) && args.isString())
      {
        TemplateListIntfPtr list = v.toList();
        if (list)
        {
          //printf("FilterKeep::apply: v=%s args=%s\n",qPrint(v.toString()),qPrint(args.toString()));
          TemplateListIntf::ConstIteratorPtr it = list->createIterator();
          TemplateListPtr result = TemplateList::alloc();
          TemplateVariant item;
          for (it->toFirst();(it->current(item));it->toNext())
          {
            //printf("item type=%s\n",item.typeAsString());
            TemplateStructIntfPtr s = item.toStruct();
            if (s)
            {
              TemplateVariant value = s->get(args.toString());
              //printf("value type=%s\n",value.typeAsString());
              if (value.toBool())
              {
                //printf("keeping it\n");
                result->append(item);
              }
              else
              {
                //printf("Dropping it\n");
              }
            }
          }
          return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(result));
        }
      }
      return v;
    }
References TemplateList::alloc(), TemplateVariant::isList(), TemplateVariant::isString(), TemplateVariant::isValid(), s, TemplateVariant::toBool(), TemplateVariant::toList(), TemplateVariant::toString(), and TemplateVariant::toStruct().
apply() [2/2]
static TemplateVariant FilterKeep::apply (const TemplateVariant & v, const TemplateVariant & args) [inline], [static]
Definition at line 820 of file template.cpp.
    {
      if (v.isValid() && (v.isList()) && args.isString())
      {
        TemplateListIntfPtr list = v.toList();
        if (list)
        {
          //printf("FilterKeep::apply: v=%s args=%s\n",qPrint(v.toString()),qPrint(args.toString()));
          TemplateListIntf::ConstIteratorPtr it = list->createIterator();
          TemplateListPtr result = TemplateList::alloc();
          TemplateVariant item;
          for (it->toFirst();(it->current(item));it->toNext())
          {
            //printf("item type=%s\n",item.typeAsString());
            TemplateStructIntfPtr s = item.toStruct();
            if (s)
            {
              TemplateVariant value = s->get(args.toString());
              //printf("value type=%s\n",value.typeAsString());
              if (value.toBool())
              {
                //printf("keeping it\n");
                result->append(item);
              }
              else
              {
                //printf("Dropping it\n");
              }
            }
          }
          return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(result));
        }
      }
      return v;
    }
References TemplateList::alloc(), TemplateVariant::isList(), TemplateVariant::isString(), TemplateVariant::isValid(), s, TemplateVariant::toBool(), TemplateVariant::toList(), TemplateVariant::toString(), and TemplateVariant::toStruct().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp