TranslatorDanish Class Reference
#include <translator_dk.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
Protected Member Functions
QCString createNoun (bool first_capital, bool singular, const char *base, const char *plurSuffix)
QCString createNoun (bool first_capital, bool singular, const char *base, const char *plurSuffix)
Additional Inherited Members
Detailed Description
Definition at line 90 of file translator_dk.h.
Member Function Documentation
createNoun() [1/2]
QCString TranslatorDanish::createNoun (bool first_capital, bool singular, const char * base, const char * plurSuffix) [inline], [protected]
For easy flexible-noun implementation.
Definition at line 1793 of file translator_dk.h.
    {
      QCString result(base);
      if (first_capital) result[0] = static_cast<char>(toupper(result[0]));
      if (!singular) result+=plurSuffix;
      return result;
    }
References caseconvert::toupper.
Referenced by trAuthor(), trClass(), trDir(), trFile(), trGlobal(), trGroup(), trMember(), trNamespace(), and trPage().
createNoun() [2/2]
QCString TranslatorDanish::createNoun (bool first_capital, bool singular, const char * base, const char * plurSuffix) [inline], [protected]
For easy flexible-noun implementation.
Definition at line 1793 of file translator_dk.h.
    {
      QCString result(base);
      if (first_capital) result[0] = static_cast<char>(toupper(result[0]));
      if (!singular) result+=plurSuffix;
      return result;
    }
References caseconvert::toupper.
getLanguageString() [1/2]
virtual QCString TranslatorDanish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 126 of file translator_dk.h.
    {
      return "0x406 Danish";
    }
getLanguageString() [2/2]
virtual QCString TranslatorDanish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 126 of file translator_dk.h.
    {
      return "0x406 Danish";
    }
idLanguage() [1/2]
virtual QCString TranslatorDanish::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 102 of file translator_dk.h.
    { return "danish"; }
idLanguage() [2/2]
virtual QCString TranslatorDanish::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 102 of file translator_dk.h.
    { return "danish"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorDanish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 116 of file translator_dk.h.
    {
      return
    "\\usepackage[danish]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorDanish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 116 of file translator_dk.h.
    {
      return
    "\\usepackage[danish]{babel}\n";
    }
trAll() [1/2]
virtual QCString TranslatorDanish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1321 of file translator_dk.h.
    {
      return "Alle";
    }
trAll() [2/2]
virtual QCString TranslatorDanish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1321 of file translator_dk.h.
    {
      return "Alle";
    }
trAttention() [1/2]
virtual QCString TranslatorDanish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 942 of file translator_dk.h.
    {
      return "OBS";
    }
trAttention() [2/2]
virtual QCString TranslatorDanish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 942 of file translator_dk.h.
    {
      return "OBS";
    }
trAuthor() [1/2]
virtual QCString TranslatorDanish::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1219 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "forfatter", "e");
    }
References createNoun().
trAuthor() [2/2]
virtual QCString TranslatorDanish::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1219 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "forfatter", "e");
    }
References createNoun().
trBug() [1/2]
virtual QCString TranslatorDanish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1111 of file translator_dk.h.
    {
      return "Kendte fejl";
    }
trBug() [2/2]
virtual QCString TranslatorDanish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1111 of file translator_dk.h.
    {
      return "Kendte fejl";
    }
trBugList() [1/2]
virtual QCString TranslatorDanish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1116 of file translator_dk.h.
    {
      return "Liste over kendte fejl";
    }
trBugList() [2/2]
virtual QCString TranslatorDanish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1116 of file translator_dk.h.
    {
      return "Liste over kendte fejl";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorDanish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1442 of file translator_dk.h.
    {
      return "Her er kalder-grafen for denne funktion:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorDanish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1442 of file translator_dk.h.
    {
      return "Her er kalder-grafen for denne funktion:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorDanish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1327 of file translator_dk.h.
    {
      return "Her er kald-grafen for denne funktion:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorDanish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1327 of file translator_dk.h.
    {
      return "Her er kald-grafen for denne funktion:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorDanish::trCiteReferences () [inline], [virtual]
Implements Translator.
Definition at line 1771 of file translator_dk.h.
    {
      return "Bibliografiske referencer";
    }
trCiteReferences() [2/2]
virtual QCString TranslatorDanish::trCiteReferences () [inline], [virtual]
Implements Translator.
Definition at line 1771 of file translator_dk.h.
    {
      return "Bibliografiske referencer";
    }
trClass() [1/2]
virtual QCString TranslatorDanish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1154 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "klasse", "r");
    }
References createNoun().
trClass() [2/2]
virtual QCString TranslatorDanish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1154 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "klasse", "r");
    }
References createNoun().
trClassDiagram() [1/2]
virtual QCString TranslatorDanish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 531 of file translator_dk.h.
    {
      return "Stamtr for "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorDanish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 531 of file translator_dk.h.
    {
      return "Stamtr for "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorDanish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 403 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastruktur-documentation";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klasse-dokumentation";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorDanish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 403 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastruktur-documentation";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klasse-dokumentation";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorDanish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1075 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Datastrukturer";
      } else {
        return "Klasser";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorDanish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1075 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Datastrukturer";
      } else {
        return "Klasser";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorDanish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 220 of file translator_dk.h.
    { return "Klassehierarki"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorDanish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 220 of file translator_dk.h.
    { return "Klassehierarki"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorDanish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 271 of file translator_dk.h.
    { return "Denne nedarvningsliste er sorteret nsten - "
             "men ikke ndvendigvis helt - alfabetisk:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorDanish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 271 of file translator_dk.h.
    { return "Denne nedarvningsliste er sorteret nsten - "
             "men ikke ndvendigvis helt - alfabetisk:";
    }
trCode() [1/2]
virtual QCString TranslatorDanish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 871 of file translator_dk.h.
    { return "kildekode"; }
trCode() [2/2]
virtual QCString TranslatorDanish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 871 of file translator_dk.h.
    { return "kildekode"; }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorDanish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 833 of file translator_dk.h.
    {
      return "Samarbejdsdiagram for "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorDanish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 833 of file translator_dk.h.
    {
      return "Samarbejdsdiagram for "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorDanish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 379 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Indeks over datastrukturer";
      } else {
        return "Indeks over sammensatte typer";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorDanish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 379 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Indeks over datastrukturer";
      } else {
        return "Indeks over sammensatte typer";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorDanish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1503 of file translator_dk.h.
    { return "Datatype indeks"; } // "Data Type Index"
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorDanish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1503 of file translator_dk.h.
    { return "Datatype indeks"; } // "Data Type Index"
trCompoundList() [1/2]
virtual QCString TranslatorDanish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 224 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Datastrukturer";
      } else {
        return "Oversigt over sammensatte typer";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorDanish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 224 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Datastrukturer";
      } else {
        return "Oversigt over sammensatte typer";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorDanish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 286 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Her er datastrukturerne med korte beskrivelser:";
      } else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE)) {
        return "Her er klasserne med korte beskrivelser:";
      } else {
        return "Her er klasserne, datastrukturerne, "
               "unionerne og grnsefladerne med korte beskrivelser:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorDanish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 286 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Her er datastrukturerne med korte beskrivelser:";
      } else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE)) {
        return "Her er klasserne med korte beskrivelser:";
      } else {
        return "Her er klasserne, datastrukturerne, "
               "unionerne og grnsefladerne med korte beskrivelser:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorDanish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1476 of file translator_dk.h.
    { return "Her er de datatyper med kort beskrivelse:"; } // "Here are the data types with brief descriptions:"
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorDanish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1476 of file translator_dk.h.
    { return "Her er de datatyper med kort beskrivelse:"; } // "Here are the data types with brief descriptions:"
trCompoundListFortran() [1/2]
virtual QCString TranslatorDanish::trCompoundListFortran () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1468 of file translator_dk.h.
    { return "Data Type Liste"; } // "Data Types List"
trCompoundListFortran() [2/2]
virtual QCString TranslatorDanish::trCompoundListFortran () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1468 of file translator_dk.h.
    { return "Data Type Liste"; } // "Data Types List"
trCompoundMembers() [1/2]
virtual QCString TranslatorDanish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 238 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Data-felter";
      } else {
        return "Felter i sammensatte typer";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorDanish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 238 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Data-felter";
      } else {
        return "Felter i sammensatte typer";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorDanish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 300 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) {
        result+="dokumenterede ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result+="felter i datastrukturer og unioner";
      } else {
        result+="klassemedlemmer";
      }
      result+=" med links til ";
      if (!extractAll) {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
          result+="datastruktur/unions-dokumentationen for hvert felt:";
        } else {
          result+="klassedokumentationen for hvert medlem:";
        }
      } else {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
          result+="de datastrukturer/unioner, de hrer til:";
        } else {
          result+="de klasser, de hrer til:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorDanish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 300 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) {
        result+="dokumenterede ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result+="felter i datastrukturer og unioner";
      } else {
        result+="klassemedlemmer";
      }
      result+=" med links til ";
      if (!extractAll) {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
          result+="datastruktur/unions-dokumentationen for hvert felt:";
        } else {
          result+="klassedokumentationen for hvert medlem:";
        }
      } else {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
          result+="de datastrukturer/unioner, de hrer til:";
        } else {
          result+="de klasser, de hrer til:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorDanish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1480 of file translator_dk.h.
    {
      QCString result="Her er en liste af alle "; // "Here is a list of all "
      if (!extractAll)
      {
        result+="dokumenteret "; // "documented "
      }
      result+="datatype medlemmer"; // "data types members"
      result+=" med links til "; // " with links to "
      if (!extractAll)
      {
         result+="data strukturer dokumenteret for hver medlem"; // "the data structure documentation for each member"
      }
      else
      {
         result+="de datatyper som de tilhrer:"; // "the data types they belong to:"
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorDanish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1480 of file translator_dk.h.
    {
      QCString result="Her er en liste af alle "; // "Here is a list of all "
      if (!extractAll)
      {
        result+="dokumenteret "; // "documented "
      }
      result+="datatype medlemmer"; // "data types members"
      result+=" med links til "; // " with links to "
      if (!extractAll)
      {
         result+="data strukturer dokumenteret for hver medlem"; // "the data structure documentation for each member"
      }
      else
      {
         result+="de datatyper som de tilhrer:"; // "the data types they belong to:"
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorDanish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1472 of file translator_dk.h.
    { return "Data felter"; } // "Data Fields"
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorDanish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1472 of file translator_dk.h.
    { return "Data felter"; } // "Data Fields"
trCompoundReference() [1/2]
virtual QCString TranslatorDanish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 606 of file translator_dk.h.
    {
      QCString result=clName+" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" Klasse-"; break;
        case ClassDef::Struct: result+=" Datastruktur-"; break;
        case ClassDef::Union: result+=" Union-"; break;
        case ClassDef::Interface: result+=" Grnseflade-"; break;
        case ClassDef::Protocol: result+=" Protokol-"; break;
        case ClassDef::Category: result+=" Kategori-"; break; // " Category-"
        case ClassDef::Exception: result+=" Undtagelse-"; break; // " Exception"
        default: break;
      }
      if (isTemplate) result+="skabelon-"; // "template-"
      result+="reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorDanish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 606 of file translator_dk.h.
    {
      QCString result=clName+" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" Klasse-"; break;
        case ClassDef::Struct: result+=" Datastruktur-"; break;
        case ClassDef::Union: result+=" Union-"; break;
        case ClassDef::Interface: result+=" Grnseflade-"; break;
        case ClassDef::Protocol: result+=" Protokol-"; break;
        case ClassDef::Category: result+=" Kategori-"; break; // " Category-"
        case ClassDef::Exception: result+=" Undtagelse-"; break; // " Exception"
        default: break;
      }
      if (isTemplate) result+="skabelon-"; // "template-"
      result+="reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorDanish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1544 of file translator_dk.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Modul"; break; // " Module"
        case ClassDef::Struct: result+=" Type"; break; // " Type"
        case ClassDef::Union: result+=" Union"; break; // " Union"
        case ClassDef::Interface: result+=" Grnseflade"; break; // " Interface"
        case ClassDef::Protocol: result+=" Protocol"; break; // " Protocol"
        case ClassDef::Category: result+=" Kategori"; break; // " Category"
        case ClassDef::Exception: result+=" Undtagelse"; break; // " Exception"
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorDanish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1544 of file translator_dk.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Modul"; break; // " Module"
        case ClassDef::Struct: result+=" Type"; break; // " Type"
        case ClassDef::Union: result+=" Union"; break; // " Union"
        case ClassDef::Interface: result+=" Grnseflade"; break; // " Interface"
        case ClassDef::Protocol: result+=" Protocol"; break; // " Protocol"
        case ClassDef::Category: result+=" Kategori"; break; // " Category"
        case ClassDef::Exception: result+=" Undtagelse"; break; // " Exception"
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorDanish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 510 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Datastrukturer";
      } else {
        return "Sammensatte typer";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorDanish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 510 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Datastrukturer";
      } else {
        return "Sammensatte typer";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorDanish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 843 of file translator_dk.h.
    {
      return "Dokumentation af konstruktrer og destruktrer";
      // "Constructor & Destructor dokumentation";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorDanish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 843 of file translator_dk.h.
    {
      return "Dokumentation af konstruktrer og destruktrer";
      // "Constructor & Destructor dokumentation";
    }
trCopyright() [1/2]
virtual QCString TranslatorDanish::trCopyright () [inline], [virtual]
Implements Translator.
Definition at line 1776 of file translator_dk.h.
    {
      return "Copyright";
    }
trCopyright() [2/2]
virtual QCString TranslatorDanish::trCopyright () [inline], [virtual]
Implements Translator.
Definition at line 1776 of file translator_dk.h.
    {
      return "Copyright";
    }
trDataTypes() [1/2]
virtual QCString TranslatorDanish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1527 of file translator_dk.h.
    { return "Datatyper"; } // "Data Types"
trDataTypes() [2/2]
virtual QCString TranslatorDanish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1527 of file translator_dk.h.
    { return "Datatyper"; } // "Data Types"
trDate() [1/2]
virtual QCString TranslatorDanish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 545 of file translator_dk.h.
    { return "Dato"; }
trDate() [2/2]
virtual QCString TranslatorDanish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 545 of file translator_dk.h.
    { return "Dato"; }
trDateTime() [1/2]
virtual QCString TranslatorDanish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1729 of file translator_dk.h.
    {
      static const char *days[] = { "Man","Tir","Ons","Tor","Fre","Lr","Sn" }; // { "Mon","Tue","Wed","Thu","Fri","Sat","Sun" };
      static const char *months[] = { "Jan","Feb","Mar","Apr","Maj","Jun","Jul","Aug","Sep","Okt","Nov","Dec" }; // { "Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorDanish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1729 of file translator_dk.h.
    {
      static const char *days[] = { "Man","Tir","Ons","Tor","Fre","Lr","Sn" }; // { "Mon","Tue","Wed","Thu","Fri","Sat","Sun" };
      static const char *months[] = { "Jan","Feb","Mar","Apr","Maj","Jun","Jul","Aug","Sep","Okt","Nov","Dec" }; // { "Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorDanish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1745 of file translator_dk.h.
    {
      static const char *days_short[] = { "ma", "ti", "on", "to", "fr", "l", "s" };
      static const char *days_full[] = { "mandag", "tirsdag", "onsdag", "torsdag", "fredag", "lrdag", "sndag" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorDanish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1745 of file translator_dk.h.
    {
      static const char *days_short[] = { "ma", "ti", "on", "to", "fr", "l", "s" };
      static const char *days_full[] = { "mandag", "tirsdag", "onsdag", "torsdag", "fredag", "lrdag", "sndag" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorDanish::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1761 of file translator_dk.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorDanish::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1761 of file translator_dk.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorDanish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 808 of file translator_dk.h.
    {
      return "Defineret p linje @0 i filen @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorDanish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 808 of file translator_dk.h.
    {
      return "Defineret p linje @0 i filen @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorDanish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 208 of file translator_dk.h.
    { return "defineret i"; }
trDefinedIn() [2/2]
virtual QCString TranslatorDanish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 208 of file translator_dk.h.
    { return "defineret i"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorDanish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 813 of file translator_dk.h.
    {
      return "Defineret i filen @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorDanish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 813 of file translator_dk.h.
    {
      return "Defineret i filen @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorDanish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 474 of file translator_dk.h.
    { return "#Define-dokumentation"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorDanish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 474 of file translator_dk.h.
    { return "#Define-dokumentation"; }
trDefines() [1/2]
virtual QCString TranslatorDanish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 438 of file translator_dk.h.
    { return "#Defines"; }
trDefines() [2/2]
virtual QCString TranslatorDanish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 438 of file translator_dk.h.
    { return "#Defines"; }
trDefineValue() [1/2]
virtual QCString TranslatorDanish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1101 of file translator_dk.h.
    {
      return "Vrdi:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorDanish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1101 of file translator_dk.h.
    {
      return "Vrdi:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorDanish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 822 of file translator_dk.h.
    {
      return "Frardes - fortidslevn"; // ?? - What is the context?
      // "Ugleset" :)
    }
trDeprecated() [2/2]
virtual QCString TranslatorDanish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 822 of file translator_dk.h.
    {
      return "Frardes - fortidslevn"; // ?? - What is the context?
      // "Ugleset" :)
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorDanish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1274 of file translator_dk.h.
    {
      return "Liste over fortidslevn, hvis brug frardes";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorDanish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1274 of file translator_dk.h.
    {
      return "Liste over fortidslevn, hvis brug frardes";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorDanish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 143 of file translator_dk.h.
    { return "Detaljeret beskrivelse"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorDanish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 143 of file translator_dk.h.
    { return "Detaljeret beskrivelse"; }
trDir() [1/2]
virtual QCString TranslatorDanish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1417 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "katalog", "er");
    }
References createNoun().
trDir() [2/2]
virtual QCString TranslatorDanish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1417 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "katalog", "er");
    }
References createNoun().
trDirDepGraph() [1/2]
virtual QCString TranslatorDanish::trDirDepGraph (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 1781 of file translator_dk.h.
    {
      return QCString("Afhngighedsgraf for katalog ")+name+":";
    }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorDanish::trDirDepGraph (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 1781 of file translator_dk.h.
    {
      return QCString("Afhngighedsgraf for katalog ")+name+":";
    }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorDanish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1399 of file translator_dk.h.
    { return "Katalog-dokumentation"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorDanish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1399 of file translator_dk.h.
    { return "Katalog-dokumentation"; }
trDirectories() [1/2]
virtual QCString TranslatorDanish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1405 of file translator_dk.h.
    { return "Kataloger"; }
trDirectories() [2/2]
virtual QCString TranslatorDanish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1405 of file translator_dk.h.
    { return "Kataloger"; }
trDirIndex() [1/2]
virtual QCString TranslatorDanish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1393 of file translator_dk.h.
    { return "Katalogstruktur"; }
trDirIndex() [2/2]
virtual QCString TranslatorDanish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1393 of file translator_dk.h.
    { return "Katalogstruktur"; }
trDirReference() [1/2]
virtual QCString TranslatorDanish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1411 of file translator_dk.h.
      { QCString result="Indhold af kataloget "; result+=dirName; return result;}
trDirReference() [2/2]
virtual QCString TranslatorDanish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1411 of file translator_dk.h.
      { QCString result="Indhold af kataloget "; result+=dirName; return result;}
trDirRelation() [1/2]
virtual QCString TranslatorDanish::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1668 of file translator_dk.h.
    {
      return QCString(name)+" Relation"; // " Relation"
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorDanish::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1668 of file translator_dk.h.
    {
      return QCString(name)+" Relation"; // " Relation"
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorDanish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 361 of file translator_dk.h.
    { return "Dokumentation"; }
trDocumentation() [2/2]
virtual QCString TranslatorDanish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 361 of file translator_dk.h.
    { return "Dokumentation"; }
trEnumerations() [1/2]
virtual QCString TranslatorDanish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 450 of file translator_dk.h.
    { return "Enumerationer"; }
trEnumerations() [2/2]
virtual QCString TranslatorDanish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 450 of file translator_dk.h.
    { return "Enumerationer"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorDanish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 486 of file translator_dk.h.
    { return "Dokumentation af enumerations-typer"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorDanish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 486 of file translator_dk.h.
    { return "Dokumentation af enumerations-typer"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorDanish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 492 of file translator_dk.h.
    { return "Dokumentation af enumerations-vrdier"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorDanish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 492 of file translator_dk.h.
    { return "Dokumentation af enumerations-vrdier"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorDanish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 468 of file translator_dk.h.
    { return "Enumerationsvrdier"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorDanish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 468 of file translator_dk.h.
    { return "Enumerationsvrdier"; }
trEnumName() [1/2]
virtual QCString TranslatorDanish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 200 of file translator_dk.h.
    { return "enumerationsnavn"; }
trEnumName() [2/2]
virtual QCString TranslatorDanish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 200 of file translator_dk.h.
    { return "enumerationsnavn"; }
trEnumValue() [1/2]
virtual QCString TranslatorDanish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 204 of file translator_dk.h.
    { return "enumerationsvrdi"; }
trEnumValue() [2/2]
virtual QCString TranslatorDanish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 204 of file translator_dk.h.
    { return "enumerationsvrdi"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorDanish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1291 of file translator_dk.h.
    {
      return "Begivenhedsdokumentation";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorDanish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1291 of file translator_dk.h.
    {
      return "Begivenhedsdokumentation";
    }
trEvents() [1/2]
virtual QCString TranslatorDanish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1286 of file translator_dk.h.
    {
      return "Begivenheder";
    }
trEvents() [2/2]
virtual QCString TranslatorDanish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1286 of file translator_dk.h.
    {
      return "Begivenheder";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorDanish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 428 of file translator_dk.h.
    { return "Eksempel-dokumentation"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorDanish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 428 of file translator_dk.h.
    { return "Eksempel-dokumentation"; }
trExamples() [1/2]
virtual QCString TranslatorDanish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 263 of file translator_dk.h.
    { return "Eksempler"; }
trExamples() [2/2]
virtual QCString TranslatorDanish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 263 of file translator_dk.h.
    { return "Eksempler"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorDanish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 349 of file translator_dk.h.
    { return "Her er en liste over alle eksempler:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorDanish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 349 of file translator_dk.h.
    { return "Her er en liste over alle eksempler:"; }
trExceptions() [1/2]
virtual QCString TranslatorDanish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 561 of file translator_dk.h.
    { return "Undtagelser"; } // "Exceptions"
trExceptions() [2/2]
virtual QCString TranslatorDanish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 561 of file translator_dk.h.
    { return "Undtagelser"; } // "Exceptions"
trFile() [1/2]
virtual QCString TranslatorDanish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1163 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "fil", "er");
    }
References createNoun().
trFile() [2/2]
virtual QCString TranslatorDanish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1163 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "fil", "er");
    }
References createNoun().
trFileDocumentation() [1/2]
virtual QCString TranslatorDanish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 422 of file translator_dk.h.
    { return "Fil-dokumentation"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorDanish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 422 of file translator_dk.h.
    { return "Fil-dokumentation"; }
trFileIn() [1/2]
virtual QCString TranslatorDanish::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1705 of file translator_dk.h.
    {
      return "File i "+name; // "File in "
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorDanish::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1705 of file translator_dk.h.
    {
      return "File i "+name; // "File in "
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorDanish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 391 of file translator_dk.h.
    { return "Fil-indeks"; }
trFileIndex() [2/2]
virtual QCString TranslatorDanish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 391 of file translator_dk.h.
    { return "Fil-indeks"; }
trFileList() [1/2]
virtual QCString TranslatorDanish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 234 of file translator_dk.h.
    { return "Filoversigt"; }
trFileList() [2/2]
virtual QCString TranslatorDanish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 234 of file translator_dk.h.
    { return "Filoversigt"; }
trFileListDescription() [1/2]
virtual QCString TranslatorDanish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 277 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterede ";
      result+="filer med korte beskrivelser:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorDanish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 277 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterede ";
      result+="filer med korte beskrivelser:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorDanish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 248 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Globale symboler";
      } else {
    return "Placering i filer"; // Fil-medlemmer"; //TODO
    //"Globale definitioner" ?
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorDanish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 248 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Globale symboler";
      } else {
    return "Placering i filer"; // Fil-medlemmer"; //TODO
    //"Globale definitioner" ?
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorDanish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 329 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterede ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result+="funktioner, variable, #defines, enumerationer "
        "og typedefinitioner";
      } else {
        result+="fil-medlemmer";
      }
      result+=", med links til ";
      if (extractAll)
        result+="de filer, de tilhrer:";
      else
        result+="deres dokumentation:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorDanish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 329 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterede ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result+="funktioner, variable, #defines, enumerationer "
        "og typedefinitioner";
      } else {
        result+="fil-medlemmer";
      }
      result+=", med links til ";
      if (extractAll)
        result+="de filer, de tilhrer:";
      else
        result+="deres dokumentation:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorDanish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 628 of file translator_dk.h.
    {
      QCString result=fileName;
      result+=" filreference";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorDanish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 628 of file translator_dk.h.
    {
      QCString result=fileName;
      result+=" filreference";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorDanish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 588 of file translator_dk.h.
    { return "Friends"; }
trFriends() [2/2]
virtual QCString TranslatorDanish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 588 of file translator_dk.h.
    { return "Friends"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorDanish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 498 of file translator_dk.h.
    { return "Funktions-dokumentation"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorDanish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 498 of file translator_dk.h.
    { return "Funktions-dokumentation"; }
trFunctions() [1/2]
virtual QCString TranslatorDanish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 456 of file translator_dk.h.
    { return "Funktioner"; }
trFunctions() [2/2]
virtual QCString TranslatorDanish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 456 of file translator_dk.h.
    { return "Funktioner"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorDanish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 522 of file translator_dk.h.
    {
      QCString result="Genereret "+date;
      if (!projName.isEmpty()) result+=" for "+projName;
      result+=" af";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorDanish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 522 of file translator_dk.h.
    {
      QCString result="Genereret "+date;
      if (!projName.isEmpty()) result+=" for "+projName;
      result+=" af";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorDanish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 192 of file translator_dk.h.
    { QCString result="Automatisk genereret af Doxygen";
      if (!s.isEmpty()) result+=" for "+s;
      result+=" ud fra kildekoden.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorDanish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 192 of file translator_dk.h.
    { QCString result="Automatisk genereret af Doxygen";
      if (!s.isEmpty()) result+=" for "+s;
      result+=" ud fra kildekoden.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorDanish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 565 of file translator_dk.h.
    { return "Genereret af"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorDanish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 565 of file translator_dk.h.
    { return "Genereret af"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorDanish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 764 of file translator_dk.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentationen for denne ";
      switch(compType)
      {
        case ClassDef::Class: result+="klasse"; break;
        case ClassDef::Struct: result+="datastruktur"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="grnseflade"; break;
        case ClassDef::Protocol: result+="protokol"; break; // "protocol"
        case ClassDef::Category: result+="kategori"; break; // "category"
        case ClassDef::Exception: result+="undtagelse"; break; // "exception"
        default: break;
      }
      result+=" blev genereret ud fra fil";
      if (single) result+="en:"; else result+="erne:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorDanish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 764 of file translator_dk.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentationen for denne ";
      switch(compType)
      {
        case ClassDef::Class: result+="klasse"; break;
        case ClassDef::Struct: result+="datastruktur"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="grnseflade"; break;
        case ClassDef::Protocol: result+="protokol"; break; // "protocol"
        case ClassDef::Category: result+="kategori"; break; // "category"
        case ClassDef::Exception: result+="undtagelse"; break; // "exception"
        default: break;
      }
      result+=" blev genereret ud fra fil";
      if (single) result+="en:"; else result+="erne:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorDanish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1614 of file translator_dk.h.
    {
      // single is true implies a single file
      QCString result="The documentation for this ";
      switch(compType)
      {
        case ClassDef::Class: result+="modul"; break; // "module"
        case ClassDef::Struct: result+="type"; break; // "type"
        case ClassDef::Union: result+="union"; break; // "union"
        case ClassDef::Interface: result+="grnseflade"; break; // "interface"
        case ClassDef::Protocol: result+="protokol"; break; // "protocol"
        case ClassDef::Category: result+="kategori"; break; // "category"
        case ClassDef::Exception: result+="undtagelse"; break; // "exception"
        default: break;
      }
      result+=" var lavet udfra flgende file"; // " was generated from the following file"
      if (single) result+=":"; else result+="r:"; // ":" / "s:"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorDanish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1614 of file translator_dk.h.
    {
      // single is true implies a single file
      QCString result="The documentation for this ";
      switch(compType)
      {
        case ClassDef::Class: result+="modul"; break; // "module"
        case ClassDef::Struct: result+="type"; break; // "type"
        case ClassDef::Union: result+="union"; break; // "union"
        case ClassDef::Interface: result+="grnseflade"; break; // "interface"
        case ClassDef::Protocol: result+="protokol"; break; // "protocol"
        case ClassDef::Category: result+="kategori"; break; // "category"
        case ClassDef::Exception: result+="undtagelse"; break; // "exception"
        default: break;
      }
      result+=" var lavet udfra flgende file"; // " was generated from the following file"
      if (single) result+=":"; else result+="r:"; // ":" / "s:"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorDanish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1208 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "global", "e");
    }
References createNoun().
trGlobal() [2/2]
virtual QCString TranslatorDanish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1208 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "global", "e");
    }
References createNoun().
trGlobalNamespace() [1/2]
virtual QCString TranslatorDanish::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1680 of file translator_dk.h.
    {
      return "Globalt Namespace"; // "Global Namespace"
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorDanish::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1680 of file translator_dk.h.
    {
      return "Globalt Namespace"; // "Global Namespace"
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorDanish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 853 of file translator_dk.h.
    { return "Hop til denne fils dokumentation."; }
trGotoDocumentation() [2/2]
virtual QCString TranslatorDanish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 853 of file translator_dk.h.
    { return "Hop til denne fils dokumentation."; }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorDanish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 875 of file translator_dk.h.
    { return "Hop til det grafiske klassehierarki"; }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorDanish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 875 of file translator_dk.h.
    { return "Hop til det grafiske klassehierarki"; }
trGotoSourceCode() [1/2]
virtual QCString TranslatorDanish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 850 of file translator_dk.h.
    { return "Hop til denne fils kildekode."; }
trGotoSourceCode() [2/2]
virtual QCString TranslatorDanish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 850 of file translator_dk.h.
    { return "Hop til denne fils kildekode."; }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorDanish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_dk.h.
    { return "Hop til det tekstuelle klassehierarki"; }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorDanish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_dk.h.
    { return "Hop til det tekstuelle klassehierarki"; }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorDanish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 873 of file translator_dk.h.
    { return "Grafisk klassehierarki"; }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorDanish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 873 of file translator_dk.h.
    { return "Grafisk klassehierarki"; }
trGroup() [1/2]
virtual QCString TranslatorDanish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1181 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "gruppe", "r");
    }
References createNoun().
trGroup() [2/2]
virtual QCString TranslatorDanish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1181 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "gruppe", "r");
    }
References createNoun().
trHierarchicalIndex() [1/2]
virtual QCString TranslatorDanish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 373 of file translator_dk.h.
    { return "Hierarkisk indeks"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorDanish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 373 of file translator_dk.h.
    { return "Hierarkisk indeks"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorDanish::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1242 of file translator_dk.h.
    {
      return "Implementerer "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorDanish::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1242 of file translator_dk.h.
    {
      return "Implementerer "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorDanish::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1250 of file translator_dk.h.
    {
      return "Implementeret i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorDanish::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1250 of file translator_dk.h.
    {
      return "Implementeret i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorDanish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 946 of file translator_dk.h.
    {
      return
    "Denne graf viser, hvilke filer der direkte eller "
    "indirekte inkluderer denne fil:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorDanish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 946 of file translator_dk.h.
    {
      return
    "Denne graf viser, hvilke filer der direkte eller "
    "indirekte inkluderer denne fil:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorDanish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 838 of file translator_dk.h.
    {
      return "Inklusions-afhngighedsgraf for "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorDanish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 838 of file translator_dk.h.
    {
      return "Inklusions-afhngighedsgraf for "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorDanish::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1714 of file translator_dk.h.
    {
      return "Inkluderer file i "+name; // "Includes file in "
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorDanish::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1714 of file translator_dk.h.
    {
      return "Inkluderer file i "+name; // "Includes file in "
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorDanish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 186 of file translator_dk.h.
    { return ", inklusive alle nedarvede medlemmer."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorDanish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 186 of file translator_dk.h.
    { return ", inklusive alle nedarvede medlemmer."; }
trInheritedByList() [1/2]
virtual QCString TranslatorDanish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 698 of file translator_dk.h.
    {
      return "Nedarvet af "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorDanish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 698 of file translator_dk.h.
    {
      return "Nedarvet af "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorDanish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 690 of file translator_dk.h.
    {
      return "Nedarver "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorDanish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 690 of file translator_dk.h.
    {
      return "Nedarver "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorDanish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 867 of file translator_dk.h.
    { return "Startvrdi:"; }
trInitialValue() [2/2]
virtual QCString TranslatorDanish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 867 of file translator_dk.h.
    { return "Startvrdi:"; }
trInvariant() [1/2]
virtual QCString TranslatorDanish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 863 of file translator_dk.h.
    { return "Invariant"; }
trInvariant() [2/2]
virtual QCString TranslatorDanish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 863 of file translator_dk.h.
    { return "Invariant"; }
trISOLang() [1/2]
virtual QCString TranslatorDanish::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 122 of file translator_dk.h.
    {
      return "da";
    }
trISOLang() [2/2]
virtual QCString TranslatorDanish::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 122 of file translator_dk.h.
    {
      return "da";
    }
trLegend() [1/2]
virtual QCString TranslatorDanish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1035 of file translator_dk.h.
    {
      return "forklaring til graf";
    }
trLegend() [2/2]
virtual QCString TranslatorDanish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1035 of file translator_dk.h.
    {
      return "forklaring til graf";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorDanish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 967 of file translator_dk.h.
    {
      return
        "Denne side forklarer, hvordan man skal fortolke de grafer, "
        "der genereres af doxygen.<p>\n"
        "Tag flgende eksempel:\n"
        "\\code\n"
        "/*! Klasse der er usynlig pg.a. beskring */\n"
        "class Invisible { };\n\n"
        "/*! Beskret klasse: nedarvningsrelation er skjult */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klasse der ikke er dokumenteret med doxygen-kommentarer */\n"
        "class Undocumented { };\n\n"
        "/*! Klasse der nedarves fra offentligt */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! En template-klasse */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasse der nedarves fra beskyttet */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasse der nedarves fra privat */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasse der bruges af Inherited-klassen */\n"
        "class Used { };\n\n"
        "/*! Klasse der nedarver en masse andre klasser */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Hvis \\c MAX_DOT_GRAPH_HEIGHT i konfigurationsfilen "
        "er sat til 240, vil dette resultere i flgende graf:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "De forskellige slags kasser i ovenstende graf har flgende "
        "betydninger:\n"
        "<ul>\n"
        "<li>%En udfyldt sort kasse reprsenterer den datastruktur eller "
        "klasse, grafen er genereret for.\n"
        "<li>%En kasse med sort kant betegner en dokumenteret datastruktur "
        " eller klasse.\n"
        "<li>%En kasse med gr kant betegner en udokumenteret datastruktur "
        " eller klasse.\n"
        "<li>%En kasse med rd kant betegner en dokumenteret datastruktur "
        " eller klasse, for hvilken ikke alle "
        "nedarvnings- og indeholdelses-relationer er vist. "
        "%Grafer beskres, hvis de fylder mere end de specificerede dimensioner.\n "
        "</ul>\n"
        "Pilene har flgende betydninger:\n"
        "<ul>\n"
        "<li>%En mrkebl pil viser en offentlig nedarvningsrelation "
        "mellem to klasser.\n"
        "<li>%En mrkegrn pil viser en beskyttet nedarvningsrelation.\n"
        "<li>%En mrkerd pil viser en privat nedarvningsrelation.\n"
        "<li>%En lilla, stiplet pil bruges, nr en klasse er indeholdt i "
        "eller benyttes af en anden klasse. "
        "Ved pilen str navnet p den eller de variable, gennem hvilke(n) "
        "den klasse, pilen peger p, er tilgngelig.\n"
        "<li>%En gul, stiplet pil viser forholdet mellem en template-instans "
        "og den template-klasse, den er instantieret fra."
        "Ved pilen str template-parametrene brugt ved instantieringen.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorDanish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 967 of file translator_dk.h.
    {
      return
        "Denne side forklarer, hvordan man skal fortolke de grafer, "
        "der genereres af doxygen.<p>\n"
        "Tag flgende eksempel:\n"
        "\\code\n"
        "/*! Klasse der er usynlig pg.a. beskring */\n"
        "class Invisible { };\n\n"
        "/*! Beskret klasse: nedarvningsrelation er skjult */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klasse der ikke er dokumenteret med doxygen-kommentarer */\n"
        "class Undocumented { };\n\n"
        "/*! Klasse der nedarves fra offentligt */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! En template-klasse */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasse der nedarves fra beskyttet */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasse der nedarves fra privat */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasse der bruges af Inherited-klassen */\n"
        "class Used { };\n\n"
        "/*! Klasse der nedarver en masse andre klasser */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Hvis \\c MAX_DOT_GRAPH_HEIGHT i konfigurationsfilen "
        "er sat til 240, vil dette resultere i flgende graf:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "De forskellige slags kasser i ovenstende graf har flgende "
        "betydninger:\n"
        "<ul>\n"
        "<li>%En udfyldt sort kasse reprsenterer den datastruktur eller "
        "klasse, grafen er genereret for.\n"
        "<li>%En kasse med sort kant betegner en dokumenteret datastruktur "
        " eller klasse.\n"
        "<li>%En kasse med gr kant betegner en udokumenteret datastruktur "
        " eller klasse.\n"
        "<li>%En kasse med rd kant betegner en dokumenteret datastruktur "
        " eller klasse, for hvilken ikke alle "
        "nedarvnings- og indeholdelses-relationer er vist. "
        "%Grafer beskres, hvis de fylder mere end de specificerede dimensioner.\n "
        "</ul>\n"
        "Pilene har flgende betydninger:\n"
        "<ul>\n"
        "<li>%En mrkebl pil viser en offentlig nedarvningsrelation "
        "mellem to klasser.\n"
        "<li>%En mrkegrn pil viser en beskyttet nedarvningsrelation.\n"
        "<li>%En mrkerd pil viser en privat nedarvningsrelation.\n"
        "<li>%En lilla, stiplet pil bruges, nr en klasse er indeholdt i "
        "eller benyttes af en anden klasse. "
        "Ved pilen str navnet p den eller de variable, gennem hvilke(n) "
        "den klasse, pilen peger p, er tilgngelig.\n"
        "<li>%En gul, stiplet pil viser forholdet mellem en template-instans "
        "og den template-klasse, den er instantieret fra."
        "Ved pilen str template-parametrene brugt ved instantieringen.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorDanish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 962 of file translator_dk.h.
    {
      return "Graf-forklaring";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorDanish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 962 of file translator_dk.h.
    {
      return "Graf-forklaring";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorDanish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 174 of file translator_dk.h.
    { return "Liste over alle medlemmer"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorDanish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 174 of file translator_dk.h.
    { return "Liste over alle medlemmer"; }
trLoading() [1/2]
virtual QCString TranslatorDanish::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1674 of file translator_dk.h.
    {
      return "Indlser..."; // "Loading..."
    }
trLoading() [2/2]
virtual QCString TranslatorDanish::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1674 of file translator_dk.h.
    {
      return "Indlser..."; // "Loading..."
    }
trMainPage() [1/2]
virtual QCString TranslatorDanish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 795 of file translator_dk.h.
    { return "Hovedside"; }
trMainPage() [2/2]
virtual QCString TranslatorDanish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 795 of file translator_dk.h.
    { return "Hovedside"; }
trMember() [1/2]
virtual QCString TranslatorDanish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1199 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "medlem", "mer");
    }
References createNoun().
trMember() [2/2]
virtual QCString TranslatorDanish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1199 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "medlem", "mer");
    }
References createNoun().
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorDanish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 160 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Felt-dokumentation";
      } else {
    return "Dokumentation af feltvariable";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorDanish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 160 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Felt-dokumentation";
      } else {
    return "Dokumentation af feltvariable";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorDanish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 151 of file translator_dk.h.
    { return "Dokumentation af medlems-enumerationer"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorDanish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 151 of file translator_dk.h.
    { return "Dokumentation af medlems-enumerationer"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorDanish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 156 of file translator_dk.h.
    { return "Dokumentation af medlemsfunktioner"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorDanish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 156 of file translator_dk.h.
    { return "Dokumentation af medlemsfunktioner"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorDanish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1451 of file translator_dk.h.
    { return "Medlem Funktion/Subroutine Dokumentation"; } // "Member Function/Subroutine Documentation"
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorDanish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1451 of file translator_dk.h.
    { return "Medlem Funktion/Subroutine Dokumentation"; } // "Member Function/Subroutine Documentation"
trMemberList() [1/2]
virtual QCString TranslatorDanish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 178 of file translator_dk.h.
    { return "Liste over medlemmer"; }
trMemberList() [2/2]
virtual QCString TranslatorDanish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 178 of file translator_dk.h.
    { return "Liste over medlemmer"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorDanish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 147 of file translator_dk.h.
    { return "Dokumentation af medlems-typedefinitioner"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorDanish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 147 of file translator_dk.h.
    { return "Dokumentation af medlems-typedefinitioner"; }
trModule() [1/2]
virtual QCString TranslatorDanish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1604 of file translator_dk.h.
    {
      QCString result((first_capital ? "Modul" : "modul")); // "Module" : "module"));
      if (!singular) result+="er"; // "s";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorDanish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1604 of file translator_dk.h.
    {
      QCString result((first_capital ? "Modul" : "modul")); // "Module" : "module"));
      if (!singular) result+="er"; // "s";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorDanish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 397 of file translator_dk.h.
    { return "Modul-dokumentation"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorDanish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 397 of file translator_dk.h.
    { return "Modul-dokumentation"; }
trModuleIndex() [1/2]
virtual QCString TranslatorDanish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 367 of file translator_dk.h.
    { return "Modul-indeks"; }
trModuleIndex() [2/2]
virtual QCString TranslatorDanish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 367 of file translator_dk.h.
    { return "Modul-indeks"; }
trModuleReference() [1/2]
virtual QCString TranslatorDanish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1566 of file translator_dk.h.
    {
      QCString result=namespaceName;
      result+=" Modulreference"; // " Module Reference"
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorDanish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1566 of file translator_dk.h.
    {
      QCString result=namespaceName;
      result+=" Modulreference"; // " Module Reference"
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorDanish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 216 of file translator_dk.h.
    { return "Moduler"; }
trModules() [2/2]
virtual QCString TranslatorDanish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 216 of file translator_dk.h.
    { return "Moduler"; }
trModulesDescription() [1/2]
virtual QCString TranslatorDanish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 357 of file translator_dk.h.
    { return "Her er en liste over alle moduler:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorDanish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 357 of file translator_dk.h.
    { return "Her er en liste over alle moduler:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorDanish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1597 of file translator_dk.h.
    { return "Modulindekser"; } // "Modules Index"
trModulesIndex() [2/2]
virtual QCString TranslatorDanish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1597 of file translator_dk.h.
    { return "Modulindekser"; } // "Modules Index"
trModulesList() [1/2]
virtual QCString TranslatorDanish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1531 of file translator_dk.h.
    { return "Modulliste"; } // "Modules List"
trModulesList() [2/2]
virtual QCString TranslatorDanish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1531 of file translator_dk.h.
    { return "Modulliste"; } // "Modules List"
trModulesListDescription() [1/2]
virtual QCString TranslatorDanish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1535 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle "; // "Here is a list of all "
      if (!extractAll) result+="dokumenteret "; // "documented "
      result+="moduler med kort beskrivelse:"; // "modules with brief descriptions:"
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorDanish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1535 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle "; // "Here is a list of all "
      if (!extractAll) result+="dokumenteret "; // "documented "
      result+="moduler med kort beskrivelse:"; // "modules with brief descriptions:"
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorDanish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1578 of file translator_dk.h.
    {
      QCString result="Her er en list over alle "; // "Here is a list of all "
      if (!extractAll) result+="Dokumentet "; // "documented "
      result+="modulmemlemmer med link til "; // "module members with links to "
      if (extractAll)
      {
        result+="dokumentation for hvert model medlem:"; // "the module documentation for each member:"
      }
      else
      {
        result+="moduler de tilhre:"; // "the modules they belong to:"
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorDanish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1578 of file translator_dk.h.
    {
      QCString result="Her er en list over alle "; // "Here is a list of all "
      if (!extractAll) result+="Dokumentet "; // "documented "
      result+="modulmemlemmer med link til "; // "module members with links to "
      if (extractAll)
      {
        result+="dokumentation for hvert model medlem:"; // "the module documentation for each member:"
      }
      else
      {
        result+="moduler de tilhre:"; // "the modules they belong to:"
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorDanish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1574 of file translator_dk.h.
    { return "Modulmedlemmer"; } // "Module Members"
trModulesMembers() [2/2]
virtual QCString TranslatorDanish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1574 of file translator_dk.h.
    { return "Modulmedlemmer"; } // "Module Members"
trMonth() [1/2]
virtual QCString TranslatorDanish::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1753 of file translator_dk.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "aug", "sep", "okt", "nov", "dec" };
      static const char *months_full[] = { "januar", "februar", "marts", "april", "maj", "juni", "juli", "august", "september", "oktober", "november", "december" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorDanish::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1753 of file translator_dk.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "aug", "sep", "okt", "nov", "dec" };
      static const char *months_full[] = { "januar", "februar", "marts", "april", "maj", "juni", "juli", "august", "september", "oktober", "november", "december" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorDanish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 170 of file translator_dk.h.
    { return "Mere..."; }
trMore() [2/2]
virtual QCString TranslatorDanish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 170 of file translator_dk.h.
    { return "Mere..."; }
trNamespace() [1/2]
virtual QCString TranslatorDanish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1172 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "namespace", "s");
    }
References createNoun().
trNamespace() [2/2]
virtual QCString TranslatorDanish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1172 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "namespace", "s");
    }
References createNoun().
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorDanish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 744 of file translator_dk.h.
    { return "Namespace-dokumentation"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorDanish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 744 of file translator_dk.h.
    { return "Namespace-dokumentation"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorDanish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 738 of file translator_dk.h.
    { return "Namespace-indeks"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorDanish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 738 of file translator_dk.h.
    { return "Namespace-indeks"; }
trNamespaceList() [1/2]
virtual QCString TranslatorDanish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 573 of file translator_dk.h.
    { return "Oversigt over namespaces"; }
trNamespaceList() [2/2]
virtual QCString TranslatorDanish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 573 of file translator_dk.h.
    { return "Oversigt over namespaces"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorDanish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 577 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterede ";
      result+="namespaces med korte beskrivelser:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorDanish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 577 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterede ";
      result+="namespaces med korte beskrivelser:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorDanish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 724 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterede ";
      result+="namespace-medlemmer med links til ";
      if (extractAll)
        result+="namespace-dokumentationen for hvert medlem:";
      else
        result+="det namespace, de hrer til:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorDanish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 724 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterede ";
      result+="namespace-medlemmer med links til ";
      if (extractAll)
        result+="namespace-dokumentationen for hvert medlem:";
      else
        result+="det namespace, de hrer til:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorDanish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 720 of file translator_dk.h.
    { return "Namespace-medlemmer"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorDanish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 720 of file translator_dk.h.
    { return "Namespace-medlemmer"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorDanish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 636 of file translator_dk.h.
    {
      QCString result=namespaceName;
      result+=" namespace-reference";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorDanish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 636 of file translator_dk.h.
    {
      QCString result=namespaceName;
      result+=" namespace-reference";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorDanish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 754 of file translator_dk.h.
    { return "Namespaces"; }
trNamespaces() [2/2]
virtual QCString TranslatorDanish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 754 of file translator_dk.h.
    { return "Namespaces"; }
trNoMatches() [1/2]
virtual QCString TranslatorDanish::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1692 of file translator_dk.h.
    {
      return "Ingen fund"; // "No Matches"
    }
trNoMatches() [2/2]
virtual QCString TranslatorDanish::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1692 of file translator_dk.h.
    {
      return "Ingen fund"; // "No Matches"
    }
trNote() [1/2]
virtual QCString TranslatorDanish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 886 of file translator_dk.h.
    { return "Note"; }
trNote() [2/2]
virtual QCString TranslatorDanish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 886 of file translator_dk.h.
    { return "Note"; }
trOverloadText() [1/2]
virtual QCString TranslatorDanish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1429 of file translator_dk.h.
    {
       return "Dette er en overdefineret medlemsfunktion, "
              "defineret af bekvemmelighedshensyn. "
          "Den adskiller sig kun fra den ovenstende funktion i, "
          "hvilke argumenter den tager.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorDanish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1429 of file translator_dk.h.
    {
       return "Dette er en overdefineret medlemsfunktion, "
              "defineret af bekvemmelighedshensyn. "
          "Den adskiller sig kun fra den ovenstende funktion i, "
          "hvilke argumenter den tager.";
    }
trPackage() [1/2]
virtual QCString TranslatorDanish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1084 of file translator_dk.h.
    {
      return "Pakke "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorDanish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1084 of file translator_dk.h.
    {
      return "Pakke "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorDanish::trPackageAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1309 of file translator_dk.h.
    { return "Attributter med pakke-scope"; }
trPackageAttribs() [2/2]
virtual QCString TranslatorDanish::trPackageAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1309 of file translator_dk.h.
    { return "Attributter med pakke-scope"; }
trPackageFunctions() [1/2]
virtual QCString TranslatorDanish::trPackageFunctions () [inline], [virtual]
Implements Translator.
Definition at line 1303 of file translator_dk.h.
    { return "Metoder med pakke-scope"; }
trPackageFunctions() [2/2]
virtual QCString TranslatorDanish::trPackageFunctions () [inline], [virtual]
Implements Translator.
Definition at line 1303 of file translator_dk.h.
    { return "Metoder med pakke-scope"; }
trPackageListDescription() [1/2]
virtual QCString TranslatorDanish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1089 of file translator_dk.h.
    {
      return
    "Her er en liste over pakkerne, med korte beskrivelser "
    "(hvor en sdan findes):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorDanish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1089 of file translator_dk.h.
    {
      return
    "Her er en liste over pakkerne, med korte beskrivelser "
    "(hvor en sdan findes):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorDanish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1305 of file translator_dk.h.
    { return "Medlemmer med pakke-scope"; }
trPackageMembers() [2/2]
virtual QCString TranslatorDanish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1305 of file translator_dk.h.
    { return "Medlemmer med pakke-scope"; }
trPackages() [1/2]
virtual QCString TranslatorDanish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1096 of file translator_dk.h.
    {
      return "Pakker";
    }
trPackages() [2/2]
virtual QCString TranslatorDanish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1096 of file translator_dk.h.
    {
      return "Pakker";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorDanish::trPackageTypes () [inline], [virtual]
Implements Translator.
Definition at line 1301 of file translator_dk.h.
    { return "Typer med pakke-scope"; }
trPackageTypes() [2/2]
virtual QCString TranslatorDanish::trPackageTypes () [inline], [virtual]
Implements Translator.
Definition at line 1301 of file translator_dk.h.
    { return "Typer med pakke-scope"; }
trPage() [1/2]
virtual QCString TranslatorDanish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1190 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "side", "r");
    }
References createNoun().
trPage() [2/2]
virtual QCString TranslatorDanish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1190 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "side", "r");
    }
References createNoun().
trPageAbbreviation() [1/2]
virtual QCString TranslatorDanish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 801 of file translator_dk.h.
    { return "s."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorDanish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 801 of file translator_dk.h.
    { return "s."; }
trPageIndex() [1/2]
virtual QCString TranslatorDanish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 879 of file translator_dk.h.
    { return "Sideindeks"; }
trPageIndex() [2/2]
virtual QCString TranslatorDanish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 879 of file translator_dk.h.
    { return "Sideindeks"; }
trParameters() [1/2]
virtual QCString TranslatorDanish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 557 of file translator_dk.h.
    { return "Parametre"; }
trParameters() [2/2]
virtual QCString TranslatorDanish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 557 of file translator_dk.h.
    { return "Parametre"; }
trPostcondition() [1/2]
virtual QCString TranslatorDanish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 860 of file translator_dk.h.
    { return "Resultat (postcondition)"; }
trPostcondition() [2/2]
virtual QCString TranslatorDanish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 860 of file translator_dk.h.
    { return "Resultat (postcondition)"; }
trPrecondition() [1/2]
virtual QCString TranslatorDanish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 857 of file translator_dk.h.
    { return "Forudstninger (precondition)"; }
trPrecondition() [2/2]
virtual QCString TranslatorDanish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 857 of file translator_dk.h.
    { return "Forudstninger (precondition)"; }
trPrivateAttribs() [1/2]
virtual QCString TranslatorDanish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_dk.h.
    { return "Private attributter"; }
trPrivateAttribs() [2/2]
virtual QCString TranslatorDanish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_dk.h.
    { return "Private attributter"; }
trPrivateMembers() [1/2]
virtual QCString TranslatorDanish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 657 of file translator_dk.h.
    { return "Private metoder"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorDanish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 657 of file translator_dk.h.
    { return "Private metoder"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorDanish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 659 of file translator_dk.h.
    { return "Private slots"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorDanish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 659 of file translator_dk.h.
    { return "Private slots"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorDanish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_dk.h.
    { return "Private typer"; }
trPrivateTypes() [2/2]
virtual QCString TranslatorDanish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_dk.h.
    { return "Private typer"; }
trProperties() [1/2]
virtual QCString TranslatorDanish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1060 of file translator_dk.h.
    {
      return "Egenskaber";
    }
trProperties() [2/2]
virtual QCString TranslatorDanish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1060 of file translator_dk.h.
    {
      return "Egenskaber";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorDanish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1065 of file translator_dk.h.
    {
      return "Egenskabsdokumentation";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorDanish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1065 of file translator_dk.h.
    {
      return "Egenskabsdokumentation";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorDanish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_dk.h.
    { return "Beskyttede attributter"; }
trProtectedAttribs() [2/2]
virtual QCString TranslatorDanish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_dk.h.
    { return "Beskyttede attributter"; }
trProtectedMembers() [1/2]
virtual QCString TranslatorDanish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 651 of file translator_dk.h.
    { return "Beskyttede metoder"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorDanish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 651 of file translator_dk.h.
    { return "Beskyttede metoder"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorDanish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_dk.h.
    { return "Beskyttede slots"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorDanish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_dk.h.
    { return "Beskyttede slots"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorDanish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_dk.h.
    { return "Beskyttede typer"; }
trProtectedTypes() [2/2]
virtual QCString TranslatorDanish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_dk.h.
    { return "Beskyttede typer"; }
trPublicAttribs() [1/2]
virtual QCString TranslatorDanish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 891 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Datafelter";
      } else {
        return "Offentlige attributter";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorDanish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 891 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Datafelter";
      } else {
        return "Offentlige attributter";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorDanish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 643 of file translator_dk.h.
    { return "Offentlige metoder"; }
trPublicMembers() [2/2]
virtual QCString TranslatorDanish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 643 of file translator_dk.h.
    { return "Offentlige metoder"; }
trPublicSlots() [1/2]
virtual QCString TranslatorDanish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_dk.h.
    { return "Offentlige slots"; }
trPublicSlots() [2/2]
virtual QCString TranslatorDanish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_dk.h.
    { return "Offentlige slots"; }
trPublicTypes() [1/2]
virtual QCString TranslatorDanish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 888 of file translator_dk.h.
    { return "Offentlige typer"; }
trPublicTypes() [2/2]
virtual QCString TranslatorDanish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 888 of file translator_dk.h.
    { return "Offentlige typer"; }
trReferencedBy() [1/2]
virtual QCString TranslatorDanish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 934 of file translator_dk.h.
    {
      return "Refereret til af";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorDanish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 934 of file translator_dk.h.
    {
      return "Refereret til af";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorDanish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 432 of file translator_dk.h.
    { return "Referencemanual"; }
trReferenceManual() [2/2]
virtual QCString TranslatorDanish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 432 of file translator_dk.h.
    { return "Referencemanual"; }
trReferences() [1/2]
virtual QCString TranslatorDanish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1230 of file translator_dk.h.
    {
      return "Indeholder referencer til";
    }
trReferences() [2/2]
virtual QCString TranslatorDanish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1230 of file translator_dk.h.
    {
      return "Indeholder referencer til";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorDanish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 706 of file translator_dk.h.
    {
      return "Overskriver metode fra "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorDanish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 706 of file translator_dk.h.
    {
      return "Overskriver metode fra "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorDanish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 714 of file translator_dk.h.
    {
      return "Reimplementeret i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorDanish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 714 of file translator_dk.h.
    {
      return "Reimplementeret i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorDanish::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 598 of file translator_dk.h.
    { return "Dokumentation af friends og af relaterede funktioner"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorDanish::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 598 of file translator_dk.h.
    { return "Dokumentation af friends og af relaterede funktioner"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorDanish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 134 of file translator_dk.h.
    { return "Relaterede funktioner"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorDanish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 134 of file translator_dk.h.
    { return "Relaterede funktioner"; }
trRelatedPages() [1/2]
virtual QCString TranslatorDanish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 259 of file translator_dk.h.
    { return "Relaterede sider"; }
trRelatedPages() [2/2]
virtual QCString TranslatorDanish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 259 of file translator_dk.h.
    { return "Relaterede sider"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorDanish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 353 of file translator_dk.h.
    { return "Her er en liste over alle relaterede dokumentationssider:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorDanish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 353 of file translator_dk.h.
    { return "Her er en liste over alle relaterede dokumentationssider:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorDanish::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 138 of file translator_dk.h.
    { return "(Bemrk at disse ikke er medlems-funktioner.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorDanish::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 138 of file translator_dk.h.
    { return "(Bemrk at disse ikke er medlems-funktioner.)"; }
trRemarks() [1/2]
virtual QCString TranslatorDanish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 938 of file translator_dk.h.
    {
      return "Bemrkninger";
    }
trRemarks() [2/2]
virtual QCString TranslatorDanish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 938 of file translator_dk.h.
    {
      return "Bemrkninger";
    }
trReturns() [1/2]
virtual QCString TranslatorDanish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 549 of file translator_dk.h.
    { return "Returnerer"; }
trReturns() [2/2]
virtual QCString TranslatorDanish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 549 of file translator_dk.h.
    { return "Returnerer"; }
trReturnValues() [1/2]
virtual QCString TranslatorDanish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 790 of file translator_dk.h.
    { return "Returvrdier"; }
trReturnValues() [2/2]
virtual QCString TranslatorDanish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 790 of file translator_dk.h.
    { return "Returvrdier"; }
trRTFansicp() [1/2]
virtual QCString TranslatorDanish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file (used table extract:)
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
ANSI_CHARSET 0 (x00) 1252
Implements Translator.
Definition at line 1133 of file translator_dk.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorDanish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file (used table extract:)
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
ANSI_CHARSET 0 (x00) 1252
Implements Translator.
Definition at line 1133 of file translator_dk.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorDanish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1139 of file translator_dk.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorDanish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1139 of file translator_dk.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorDanish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1145 of file translator_dk.h.
    {
      return "Indeks";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorDanish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1145 of file translator_dk.h.
    {
      return "Indeks";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorDanish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1262 of file translator_dk.h.
    {
      return "Indholdsfortegnelse";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorDanish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1262 of file translator_dk.h.
    {
      return "Indholdsfortegnelse";
    }
trSearch() [1/2]
virtual QCString TranslatorDanish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 267 of file translator_dk.h.
    { return "Sg"; }
trSearch() [2/2]
virtual QCString TranslatorDanish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 267 of file translator_dk.h.
    { return "Sg"; }
trSearching() [1/2]
virtual QCString TranslatorDanish::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1686 of file translator_dk.h.
    {
      return "Sger..."; // "Searching..."
    }
trSearching() [2/2]
virtual QCString TranslatorDanish::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1686 of file translator_dk.h.
    {
      return "Sger..."; // "Searching..."
    }
trSearchMatches() [1/2]
virtual QCString TranslatorDanish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1368 of file translator_dk.h.
    {
      return "Fundne ord:"; //translation?
    }
trSearchMatches() [2/2]
virtual QCString TranslatorDanish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1368 of file translator_dk.h.
    {
      return "Fundne ord:"; //translation?
    }
trSearchResults() [1/2]
virtual QCString TranslatorDanish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1352 of file translator_dk.h.
    {
      if (numDocuments==0) {
        return "Beklager - ingen dokumenter passede til din foresprgsel.";
      } else if (numDocuments==1) {
        return "Fandt <b>1</b> dokument, der passer til din foresprgsel.";
      } else {
        return
      "Fandt <b>$num</b> dokumenter, der passer til din foresprgsel. "
      "De, der passer bedst, vises frst.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorDanish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1352 of file translator_dk.h.
    {
      if (numDocuments==0) {
        return "Beklager - ingen dokumenter passede til din foresprgsel.";
      } else if (numDocuments==1) {
        return "Fandt <b>1</b> dokument, der passer til din foresprgsel.";
      } else {
        return
      "Fandt <b>$num</b> dokumenter, der passer til din foresprgsel. "
      "De, der passer bedst, vises frst.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorDanish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1339 of file translator_dk.h.
    {
      return "Sgeresultater";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorDanish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1339 of file translator_dk.h.
    {
      return "Sgeresultater";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorDanish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 553 of file translator_dk.h.
    { return "Se ogs"; }
trSeeAlso() [2/2]
virtual QCString TranslatorDanish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 553 of file translator_dk.h.
    { return "Se ogs"; }
trSignals() [1/2]
virtual QCString TranslatorDanish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 647 of file translator_dk.h.
    { return "Signaler"; }
trSignals() [2/2]
virtual QCString TranslatorDanish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 647 of file translator_dk.h.
    { return "Signaler"; }
trSince() [1/2]
virtual QCString TranslatorDanish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_dk.h.
    {
      return "Siden";
    }
trSince() [2/2]
virtual QCString TranslatorDanish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_dk.h.
    {
      return "Siden";
    }
trSourceFile() [1/2]
virtual QCString TranslatorDanish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1380 of file translator_dk.h.
    {
      return "Kildefilen " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorDanish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1380 of file translator_dk.h.
    {
      return "Kildefilen " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorDanish::trStaticPackageAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1311 of file translator_dk.h.
    { return "Statiske attributter med pakke-scope"; }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorDanish::trStaticPackageAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1311 of file translator_dk.h.
    { return "Statiske attributter med pakke-scope"; }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorDanish::trStaticPackageFunctions () [inline], [virtual]
Implements Translator.
Definition at line 1307 of file translator_dk.h.
    { return "Statiske metoder med pakke-scope"; }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorDanish::trStaticPackageFunctions () [inline], [virtual]
Implements Translator.
Definition at line 1307 of file translator_dk.h.
    { return "Statiske metoder med pakke-scope"; }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorDanish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_dk.h.
    { return "Statiske, private attributter"; }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorDanish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_dk.h.
    { return "Statiske, private attributter"; }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorDanish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 661 of file translator_dk.h.
    { return "Statiske, private metoder"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorDanish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 661 of file translator_dk.h.
    { return "Statiske, private metoder"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorDanish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 906 of file translator_dk.h.
    { return "Statiske, beskyttede attributter"; }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorDanish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 906 of file translator_dk.h.
    { return "Statiske, beskyttede attributter"; }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorDanish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 655 of file translator_dk.h.
    { return "Statiske, beskyttede metoder"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorDanish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 655 of file translator_dk.h.
    { return "Statiske, beskyttede metoder"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorDanish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 900 of file translator_dk.h.
    { return "Statiske, offentlige attributter"; }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorDanish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 900 of file translator_dk.h.
    { return "Statiske, offentlige attributter"; }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorDanish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 649 of file translator_dk.h.
    { return "Statiske, offentlige metoder"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorDanish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 649 of file translator_dk.h.
    { return "Statiske, offentlige metoder"; }
trSubprogram() [1/2]
virtual QCString TranslatorDanish::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1650 of file translator_dk.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram")); // "Subprogram" : "subprogram"
      if (!singular) result+="er"; // "s"
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorDanish::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1650 of file translator_dk.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram")); // "Subprogram" : "subprogram"
      if (!singular) result+="er"; // "s"
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorDanish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1521 of file translator_dk.h.
    { return "Funktion/Subroutine dokumentation"; } // "Function/Subroutine Documentation"
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorDanish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1521 of file translator_dk.h.
    { return "Funktion/Subroutine dokumentation"; } // "Function/Subroutine Documentation"
trSubprograms() [1/2]
virtual QCString TranslatorDanish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1515 of file translator_dk.h.
    { return "Funktioner/Subroutiner"; } // "Functions/Subroutines"
trSubprograms() [2/2]
virtual QCString TranslatorDanish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1515 of file translator_dk.h.
    { return "Funktioner/Subroutiner"; } // "Functions/Subroutines"
trTest() [1/2]
virtual QCString TranslatorDanish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1045 of file translator_dk.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorDanish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1045 of file translator_dk.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorDanish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1050 of file translator_dk.h.
    {
      return "Testliste";
    }
trTestList() [2/2]
virtual QCString TranslatorDanish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1050 of file translator_dk.h.
    {
      return "Testliste";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorDanish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 182 of file translator_dk.h.
    { return "Dette er den komplette liste over medlemmer i "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorDanish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 182 of file translator_dk.h.
    { return "Dette er den komplette liste over medlemmer i "; }
trTodo() [1/2]
virtual QCString TranslatorDanish::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 920 of file translator_dk.h.
    {
      return "Todo";
    }
trTodo() [2/2]
virtual QCString TranslatorDanish::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 920 of file translator_dk.h.
    {
      return "Todo";
    }
trTodoList() [1/2]
virtual QCString TranslatorDanish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 925 of file translator_dk.h.
    {
      return "Todo-liste";
    }
trTodoList() [2/2]
virtual QCString TranslatorDanish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 925 of file translator_dk.h.
    {
      return "Todo-liste";
    }
trType() [1/2]
virtual QCString TranslatorDanish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1639 of file translator_dk.h.
    {
      QCString result((first_capital ? "Type" : "type")); // "Type" : "type"
      if (!singular) result+="r"; // "s"
      return result;
    }
trType() [2/2]
virtual QCString TranslatorDanish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1639 of file translator_dk.h.
    {
      QCString result((first_capital ? "Type" : "type")); // "Type" : "type"
      if (!singular) result+="r"; // "s"
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorDanish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1658 of file translator_dk.h.
    {
      return "typebegrnsninger"; // "Type Constraints"
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorDanish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1658 of file translator_dk.h.
    {
      return "typebegrnsninger"; // "Type Constraints"
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorDanish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 480 of file translator_dk.h.
    { return "Dokumentation af typedefinitioner"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorDanish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 480 of file translator_dk.h.
    { return "Dokumentation af typedefinitioner"; }
trTypedefs() [1/2]
virtual QCString TranslatorDanish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 444 of file translator_dk.h.
    { return "Typedefinitioner"; }
trTypedefs() [2/2]
virtual QCString TranslatorDanish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 444 of file translator_dk.h.
    { return "Typedefinitioner"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorDanish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1509 of file translator_dk.h.
    { return "Datatype dokumentation"; } // "Data Type Documentation"
trTypeDocumentation() [2/2]
virtual QCString TranslatorDanish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1509 of file translator_dk.h.
    { return "Datatype dokumentation"; } // "Data Type Documentation"
trVariableDocumentation() [1/2]
virtual QCString TranslatorDanish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 504 of file translator_dk.h.
    { return "Variabel-dokumentation"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorDanish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 504 of file translator_dk.h.
    { return "Variabel-dokumentation"; }
trVariables() [1/2]
virtual QCString TranslatorDanish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 462 of file translator_dk.h.
    { return "Variable"; }
trVariables() [2/2]
virtual QCString TranslatorDanish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 462 of file translator_dk.h.
    { return "Variable"; }
trVersion() [1/2]
virtual QCString TranslatorDanish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 541 of file translator_dk.h.
    { return "Version"; }
trVersion() [2/2]
virtual QCString TranslatorDanish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 541 of file translator_dk.h.
    { return "Version"; }
trWarning() [1/2]
virtual QCString TranslatorDanish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 537 of file translator_dk.h.
    { return "Advarsel"; }
trWarning() [2/2]
virtual QCString TranslatorDanish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 537 of file translator_dk.h.
    { return "Advarsel"; }
trWriteList() [1/2]
virtual QCString TranslatorDanish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 667 of file translator_dk.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++) {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) { // not the last entry, so we need a separator
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" og ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorDanish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 667 of file translator_dk.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++) {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) { // not the last entry, so we need a separator
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" og ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_dk.h
doxygen/src/translator_dk.h