FilterLower Class Reference
The implementation of the `lower` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `lower` filter.
Definition at line 1491 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterLower::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1494 of file template.cpp.
    {
      if (v.isValid() && v.isString())
      {
        return v.toString().lower();
      }
      return v;
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), QCString::lower(), and TemplateVariant::toString().
apply() [2/2]
static TemplateVariant FilterLower::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1494 of file template.cpp.
    {
      if (v.isValid() && v.isString())
      {
        return v.toString().lower();
      }
      return v;
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), QCString::lower(), and TemplateVariant::toString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp