XMLLocator Class Reference
#include <xml.h>
Public Member Functions
virtual ~XMLLocator ()
virtual int lineNr () const =0
virtual std::string fileName () const =0
virtual ~XMLLocator ()
virtual int lineNr () const =0
virtual std::string fileName () const =0
Detailed Description
Definition at line 55 of file xml.h.
Constructor & Destructor Documentation
 XMLLocator() [1/2]
virtual XMLLocator::~XMLLocator () [inline], [virtual]
Definition at line 58 of file xml.h.
{}
 XMLLocator() [2/2]
virtual XMLLocator::~XMLLocator () [inline], [virtual]
Definition at line 58 of file xml.h.
{}
Member Function Documentation
fileName() [1/2]
virtual std::string XMLLocator::fileName () const [pure virtual]
Implemented in XMLParser, and XMLParser.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), LayoutParser::startElement(), LayoutParser::startNavEntry(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
virtual std::string XMLLocator::fileName () const [pure virtual]
Implemented in XMLParser, and XMLParser.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
lineNr() [1/2]
virtual int XMLLocator::lineNr () const [pure virtual]
Implemented in XMLParser, and XMLParser.
Referenced by LayoutParser::startElement(), and LayoutParser::startNavEntry().
lineNr() [2/2]
virtual int XMLLocator::lineNr () const [pure virtual]
Implemented in XMLParser, and XMLParser.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/libxml/xml.h
doxygen/libxml/xml.h