TranslatorHungarian Class Reference
#include <translator_hu.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
Private Member Functions
const char * zed (char c)
const char * zed (char c)
Additional Inherited Members
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include `translator.h` or `translator_adapter.h` here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 55 of file translator_hu.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorHungarian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 107 of file translator_hu.h.
    {
      return "0x40E Hungarian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorHungarian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 107 of file translator_hu.h.
    {
      return "0x40E Hungarian";
    }
idLanguage() [1/2]
virtual QCString TranslatorHungarian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 80 of file translator_hu.h.
    { return "hungarian"; }
idLanguage() [2/2]
virtual QCString TranslatorHungarian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 80 of file translator_hu.h.
    { return "hungarian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorHungarian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 97 of file translator_hu.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[magyar]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorHungarian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 97 of file translator_hu.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[magyar]{babel}\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorHungarian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1919 of file translator_hu.h.
    { return "Tovbbi rklt tagok"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorHungarian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1919 of file translator_hu.h.
    { return "Tovbbi rklt tagok"; }
trAll() [1/2]
virtual QCString TranslatorHungarian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1429 of file translator_hu.h.
    {
      return "sszes";
    }
trAll() [2/2]
virtual QCString TranslatorHungarian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1429 of file translator_hu.h.
    {
      return "sszes";
    }
trAndMore() [1/2]
virtual QCString TranslatorHungarian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1897 of file translator_hu.h.
    { return "s "+number+" elemmel tbb..."; }
trAndMore() [2/2]
virtual QCString TranslatorHungarian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1897 of file translator_hu.h.
    { return "s "+number+" elemmel tbb..."; }
trAttention() [1/2]
virtual QCString TranslatorHungarian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 991 of file translator_hu.h.
    {
      return "Figyelem";
    }
trAttention() [2/2]
virtual QCString TranslatorHungarian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 991 of file translator_hu.h.
    {
      return "Figyelem";
    }
trAuthor() [1/2]
virtual QCString TranslatorHungarian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1300 of file translator_hu.h.
    {
      QCString result((first_capital ? "Szerz" : "szerz"));
      if (!singular) result+="k";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorHungarian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1300 of file translator_hu.h.
    {
      QCString result((first_capital ? "Szerz" : "szerz"));
      if (!singular) result+="k";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorHungarian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1157 of file translator_hu.h.
    {
      return "Hiba";
    }
trBug() [2/2]
virtual QCString TranslatorHungarian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1157 of file translator_hu.h.
    {
      return "Hiba";
    }
trBugList() [1/2]
virtual QCString TranslatorHungarian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1162 of file translator_hu.h.
    {
      return "Hiba lista";
    }
trBugList() [2/2]
virtual QCString TranslatorHungarian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1162 of file translator_hu.h.
    {
      return "Hiba lista";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorHungarian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1551 of file translator_hu.h.
    {
      return "A fggvny hv grfja:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorHungarian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1551 of file translator_hu.h.
    {
      return "A fggvny hv grfja:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorHungarian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1434 of file translator_hu.h.
    {
      return "A fggvny hvsi grfja:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorHungarian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1434 of file translator_hu.h.
    {
      return "A fggvny hvsi grfja:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorHungarian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1873 of file translator_hu.h.
    { return "Bibliogrfia"; }
trCiteReferences() [2/2]
virtual QCString TranslatorHungarian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1873 of file translator_hu.h.
    { return "Bibliogrfia"; }
trClass() [1/2]
virtual QCString TranslatorHungarian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1220 of file translator_hu.h.
    {
      QCString result((first_capital ? "Osztly" : "osztly"));
      //if (!singular) result+="ok";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorHungarian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1220 of file translator_hu.h.
    {
      QCString result((first_capital ? "Osztly" : "osztly"));
      //if (!singular) result+="ok";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorHungarian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 544 of file translator_hu.h.
    {
      return QCString("A")+zed(clName[0])+clName+" osztly szrmazsi diagramja:";
    }
References zed().
trClassDiagram() [2/2]
virtual QCString TranslatorHungarian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 544 of file translator_hu.h.
    {
      return QCString("A")+zed(clName[0])+clName+" osztly szrmazsi diagramja:";
    }
References zed().
trClassDocumentation() [1/2]
virtual QCString TranslatorHungarian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 419 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezetek dokumentcija";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Osztlyok dokumentcija";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorHungarian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 419 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezetek dokumentcija";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Osztlyok dokumentcija";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorHungarian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1120 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezetek";
      }
      else
      {
        return "Osztlyok";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorHungarian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1120 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezetek";
      }
      else
      {
        return "Osztlyok";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorHungarian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 202 of file translator_hu.h.
    { return "Osztlyhierarchia"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorHungarian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 202 of file translator_hu.h.
    { return "Osztlyhierarchia"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorHungarian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 261 of file translator_hu.h.
    { return "Majdnem (de nem teljesen) betrendbe szedett "
             "leszrmazsi lista:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorHungarian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 261 of file translator_hu.h.
    { return "Majdnem (de nem teljesen) betrendbe szedett "
             "leszrmazsi lista:";
    }
trClassMethods() [1/2]
virtual QCString TranslatorHungarian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1957 of file translator_hu.h.
    {
      return "Osztly metdusok";
    }
trClassMethods() [2/2]
virtual QCString TranslatorHungarian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1957 of file translator_hu.h.
    {
      return "Osztly metdusok";
    }
trCode() [1/2]
virtual QCString TranslatorHungarian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 891 of file translator_hu.h.
    {
      return "forrskd";
    }
trCode() [2/2]
virtual QCString TranslatorHungarian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 891 of file translator_hu.h.
    {
      return "forrskd";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorHungarian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 846 of file translator_hu.h.
    {
      return QCString("A")+zed(clName[0])+clName+" osztly egyttmkdsi diagramja:";
    }
References zed().
trCollaborationDiagram() [2/2]
virtual QCString TranslatorHungarian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 846 of file translator_hu.h.
    {
      return QCString("A")+zed(clName[0])+clName+" osztly egyttmkdsi diagramja:";
    }
References zed().
trCompoundIndex() [1/2]
virtual QCString TranslatorHungarian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 392 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezet-mutat";
      }
      else
      {
        return "Osztlymutat";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorHungarian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 392 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezet-mutat";
      }
      else
      {
        return "Osztlymutat";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorHungarian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1605 of file translator_hu.h.
    { return "Adattpus index"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorHungarian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1605 of file translator_hu.h.
    { return "Adattpus index"; }
trCompoundList() [1/2]
virtual QCString TranslatorHungarian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 206 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezetek";
      }
      else
      {
        return "Osztlylista";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorHungarian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 206 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezetek";
      }
      else
      {
        return "Osztlylista";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorHungarian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 276 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Az sszes adatszerkezet listja rvid lersokkal:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Az sszes osztly listja rvid lersokkal:";
      }
      else
      {
        return "Az sszes osztly, struktra, uni s interfsz "
               "listja rvid lersokkal:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorHungarian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 276 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Az sszes adatszerkezet listja rvid lersokkal:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Az sszes osztly listja rvid lersokkal:";
      }
      else
      {
        return "Az sszes osztly, struktra, uni s interfsz "
               "listja rvid lersokkal:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorHungarian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1579 of file translator_hu.h.
    { return "Rvid lerssal elltott adattpusok:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorHungarian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1579 of file translator_hu.h.
    { return "Rvid lerssal elltott adattpusok:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorHungarian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1571 of file translator_hu.h.
    { return "Adattpusok listja"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorHungarian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1571 of file translator_hu.h.
    { return "Adattpusok listja"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorHungarian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 223 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatmezk";
      }
      else
      {
        return "Osztlytagok";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorHungarian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 223 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatmezk";
      }
      else
      {
        return "Osztlytagok";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorHungarian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 295 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll)
      {
        result+="dokumentlt ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struktra- s unimez";
      }
      else
      {
        result+="osztlytag";
      }
      result+=" listja, valamint hivatkozs ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a megfelel struktra/uni dokumentcira minden meznl:";
        }
        else
        {
          result+="a megfelel osztlydokumentcira minden tagnl:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a struktrkra/unikra, amikhez tartoznak:";
        }
        else
        {
          result+="az osztlyokra, amikhez tartoznak:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorHungarian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 295 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll)
      {
        result+="dokumentlt ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struktra- s unimez";
      }
      else
      {
        result+="osztlytag";
      }
      result+=" listja, valamint hivatkozs ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a megfelel struktra/uni dokumentcira minden meznl:";
        }
        else
        {
          result+="a megfelel osztlydokumentcira minden tagnl:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a struktrkra/unikra, amikhez tartoznak:";
        }
        else
        {
          result+="az osztlyokra, amikhez tartoznak:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorHungarian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1583 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll)
      {
        result+="dokumentlt ";
      }
      result+="adattpus tagvltoz";
      result+=" hivatkozsokkal elltva ";
      if (!extractAll)
      {
         result+="az egyes adattagok adatszerkezetnek dokumentcijra";
      }
      else
      {
         result+="azokhoz az adattpusokhoz, amelyekhez tartoznak:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorHungarian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1583 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll)
      {
        result+="dokumentlt ";
      }
      result+="adattpus tagvltoz";
      result+=" hivatkozsokkal elltva ";
      if (!extractAll)
      {
         result+="az egyes adattagok adatszerkezetnek dokumentcijra";
      }
      else
      {
         result+="azokhoz az adattpusokhoz, amelyekhez tartoznak:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorHungarian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1575 of file translator_hu.h.
    { return "Adatmezk"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorHungarian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1575 of file translator_hu.h.
    { return "Adatmezk"; }
trCompoundReference() [1/2]
virtual QCString TranslatorHungarian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 619 of file translator_hu.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" osztly"; break;
        case ClassDef::Struct: result+=" struktra"; break;
        case ClassDef::Union: result+=" uni"; break;
        case ClassDef::Interface: result+=" interfsz"; break;
        case ClassDef::Protocol: result+=" protokoll"; break;
        case ClassDef::Category: result+=" kategria"; break;
        case ClassDef::Exception: result+=" kivtel"; break;
        default: break;
      }
      if (isTemplate) result+="sablon-";
      result+="referencia";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorHungarian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 619 of file translator_hu.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" osztly"; break;
        case ClassDef::Struct: result+=" struktra"; break;
        case ClassDef::Union: result+=" uni"; break;
        case ClassDef::Interface: result+=" interfsz"; break;
        case ClassDef::Protocol: result+=" protokoll"; break;
        case ClassDef::Category: result+=" kategria"; break;
        case ClassDef::Exception: result+=" kivtel"; break;
        default: break;
      }
      if (isTemplate) result+="sablon-";
      result+="referencia";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorHungarian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1645 of file translator_hu.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" modul"; break;
        case ClassDef::Struct: result+=" tpus"; break;
        case ClassDef::Union: result+=" uni"; break;
        case ClassDef::Interface: result+=" interfsz"; break;
        case ClassDef::Protocol: result+=" protokoll"; break;
        case ClassDef::Category: result+=" kategria"; break;
        case ClassDef::Exception: result+=" kivtel"; break;
        default: break;
      }
      if (isTemplate) result+=" sablon";
      result+=" hivatkozs";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorHungarian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1645 of file translator_hu.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" modul"; break;
        case ClassDef::Struct: result+=" tpus"; break;
        case ClassDef::Union: result+=" uni"; break;
        case ClassDef::Interface: result+=" interfsz"; break;
        case ClassDef::Protocol: result+=" protokoll"; break;
        case ClassDef::Category: result+=" kategria"; break;
        case ClassDef::Exception: result+=" kivtel"; break;
        default: break;
      }
      if (isTemplate) result+=" sablon";
      result+=" hivatkozs";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorHungarian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 520 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezetek";
      }
      else
      {
        return "Osztlyok";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorHungarian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 520 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezetek";
      }
      else
      {
        return "Osztlyok";
      }
    }
References Config_getBool.
trConstantGroupReference() [1/2]
virtual QCString TranslatorHungarian::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1994 of file translator_hu.h.
    {
      QCString result=namespaceName;
      result+=" konstans csoport referencia";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorHungarian::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1994 of file translator_hu.h.
    {
      QCString result=namespaceName;
      result+=" konstans csoport referencia";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorHungarian::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1990 of file translator_hu.h.
    { return "Konstans csoportok"; }
trConstantGroups() [2/2]
virtual QCString TranslatorHungarian::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1990 of file translator_hu.h.
    { return "Konstans csoportok"; }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorHungarian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 856 of file translator_hu.h.
    {
      return "Konstruktorok s destruktorok dokumentcija";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorHungarian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 856 of file translator_hu.h.
    {
      return "Konstruktorok s destruktorok dokumentcija";
    }
trCopyright() [1/2]
virtual QCString TranslatorHungarian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1877 of file translator_hu.h.
    { return "Szerzi jog"; }
trCopyright() [2/2]
virtual QCString TranslatorHungarian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1877 of file translator_hu.h.
    { return "Szerzi jog"; }
trDataTypes() [1/2]
virtual QCString TranslatorHungarian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1628 of file translator_hu.h.
    { return "Adattpusok"; }
trDataTypes() [2/2]
virtual QCString TranslatorHungarian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1628 of file translator_hu.h.
    { return "Adattpusok"; }
trDate() [1/2]
virtual QCString TranslatorHungarian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 558 of file translator_hu.h.
    { return "Dtum"; }
trDate() [2/2]
virtual QCString TranslatorHungarian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 558 of file translator_hu.h.
    { return "Dtum"; }
trDateTime() [1/2]
virtual QCString TranslatorHungarian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1830 of file translator_hu.h.
    {
      static const char *days[] = { "Htf","Kedd","Szerda","Cstrtk","Pntek","Szombat","Vasrnap" };
      static const char *months[] = { "Janur","Februr","Mrcius","prilis","Mjus","Jnius","Jlius","Augusztus","Szeptember","Oktber","November","December" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorHungarian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1830 of file translator_hu.h.
    {
      static const char *days[] = { "Htf","Kedd","Szerda","Cstrtk","Pntek","Szombat","Vasrnap" };
      static const char *months[] = { "Janur","Februr","Mrcius","prilis","Mjus","Jnius","Jlius","Augusztus","Szeptember","Oktber","November","December" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorHungarian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1846 of file translator_hu.h.
    {
      static const char *days_short[] = { "H", "K", "Sze", "Cs", "P", "Szo", "V" };
      static const char *days_full[] = { "htf", "kedd", "szerda", "cstrtk", "pntek", "szombat", "vasrnap" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorHungarian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1846 of file translator_hu.h.
    {
      static const char *days_short[] = { "H", "K", "Sze", "Cs", "P", "Szo", "V" };
      static const char *days_full[] = { "htf", "kedd", "szerda", "cstrtk", "pntek", "szombat", "vasrnap" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorHungarian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1862 of file translator_hu.h.
    {
      static const char *dayPeriod[] = { "de.", "du." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorHungarian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1862 of file translator_hu.h.
    {
      static const char *dayPeriod[] = { "de.", "du." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorHungarian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 823 of file translator_hu.h.
    {
      return "Definci a(z) @1 fjl @0. sorban.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorHungarian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 823 of file translator_hu.h.
    {
      return "Definci a(z) @1 fjl @0. sorban.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorHungarian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 190 of file translator_hu.h.
    { return "definilja:"; }
trDefinedIn() [2/2]
virtual QCString TranslatorHungarian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 190 of file translator_hu.h.
    { return "definilja:"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorHungarian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 827 of file translator_hu.h.
    {
      return "Definci a(z) @0 fjlban.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorHungarian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 827 of file translator_hu.h.
    {
      return "Definci a(z) @0 fjlban.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorHungarian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 490 of file translator_hu.h.
    { return "Makrdefincik dokumentcija"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorHungarian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 490 of file translator_hu.h.
    { return "Makrdefincik dokumentcija"; }
trDefines() [1/2]
virtual QCString TranslatorHungarian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 454 of file translator_hu.h.
    { return "Makrdefincik"; }
trDefines() [2/2]
virtual QCString TranslatorHungarian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 454 of file translator_hu.h.
    { return "Makrdefincik"; }
trDefineValue() [1/2]
virtual QCString TranslatorHungarian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1147 of file translator_hu.h.
    {
      return "rtk:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorHungarian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1147 of file translator_hu.h.
    {
      return "rtk:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorHungarian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 836 of file translator_hu.h.
    {
      return "Ellenjavallt";
    }
trDeprecated() [2/2]
virtual QCString TranslatorHungarian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 836 of file translator_hu.h.
    {
      return "Ellenjavallt";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorHungarian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1357 of file translator_hu.h.
    {
      return "Ellenjavallt elemek listja";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorHungarian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1357 of file translator_hu.h.
    {
      return "Ellenjavallt elemek listja";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorHungarian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 123 of file translator_hu.h.
    { return "Rszletes lers"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorHungarian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 123 of file translator_hu.h.
    { return "Rszletes lers"; }
trDetailLevel() [1/2]
virtual QCString TranslatorHungarian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1889 of file translator_hu.h.
    { return "rszletessgi szint"; }
trDetailLevel() [2/2]
virtual QCString TranslatorHungarian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1889 of file translator_hu.h.
    { return "rszletessgi szint"; }
trDir() [1/2]
virtual QCString TranslatorHungarian::trDir (bool first_capital, bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1524 of file translator_hu.h.
    {
      QCString result((first_capital ? "Knyvtr" : "knyvtr"));
      //if (singular) result+="y"; else result+="ies";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorHungarian::trDir (bool first_capital, bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1524 of file translator_hu.h.
    {
      QCString result((first_capital ? "Knyvtr" : "knyvtr"));
      //if (singular) result+="y"; else result+="ies";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorHungarian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1881 of file translator_hu.h.
    { return QCString("Knyvtr fggsgi grf a(z) ")+name+"-knyvtrhoz:"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorHungarian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1881 of file translator_hu.h.
    { return QCString("Knyvtr fggsgi grf a(z) ")+name+"-knyvtrhoz:"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorHungarian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1506 of file translator_hu.h.
    { return "Knyvtrak dokumentcija"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorHungarian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1506 of file translator_hu.h.
    { return "Knyvtrak dokumentcija"; }
trDirectories() [1/2]
virtual QCString TranslatorHungarian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1512 of file translator_hu.h.
    { return "Knyvtrak"; }
trDirectories() [2/2]
virtual QCString TranslatorHungarian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1512 of file translator_hu.h.
    { return "Knyvtrak"; }
trDirIndex() [1/2]
virtual QCString TranslatorHungarian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1500 of file translator_hu.h.
    { return "Knyvtrhierarchia"; }
trDirIndex() [2/2]
virtual QCString TranslatorHungarian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1500 of file translator_hu.h.
    { return "Knyvtrhierarchia"; }
trDirReference() [1/2]
virtual QCString TranslatorHungarian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1518 of file translator_hu.h.
    { QCString result=dirName; result+=" knyvtrreferencia"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorHungarian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1518 of file translator_hu.h.
    { QCString result=dirName; result+=" knyvtrreferencia"; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorHungarian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1769 of file translator_hu.h.
    {
      return QCString(name)+" kapcsolat";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorHungarian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1769 of file translator_hu.h.
    {
      return QCString(name)+" kapcsolat";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorHungarian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 374 of file translator_hu.h.
    { return "Dokumentci"; }
trDocumentation() [2/2]
virtual QCString TranslatorHungarian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 374 of file translator_hu.h.
    { return "Dokumentci"; }
trEnumerations() [1/2]
virtual QCString TranslatorHungarian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 466 of file translator_hu.h.
    { return "Enumercik"; }
trEnumerations() [2/2]
virtual QCString TranslatorHungarian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 466 of file translator_hu.h.
    { return "Enumercik"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorHungarian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 502 of file translator_hu.h.
    { return "Enumercik dokumentcija"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorHungarian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 502 of file translator_hu.h.
    { return "Enumercik dokumentcija"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorHungarian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1559 of file translator_hu.h.
    { return "Enumercis-rtk dokumentci"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorHungarian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1559 of file translator_hu.h.
    { return "Enumercis-rtk dokumentci"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorHungarian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 484 of file translator_hu.h.
    { return "Enumerci-rtkek"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorHungarian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 484 of file translator_hu.h.
    { return "Enumerci-rtkek"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorHungarian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1901 of file translator_hu.h.
    { QCString result = "A dokumentci ehhez az enum-hoz a kvetkez fjl";
      if (!single) result+="ok";
      result+=" alapjn kszlt:";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorHungarian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1901 of file translator_hu.h.
    { QCString result = "A dokumentci ehhez az enum-hoz a kvetkez fjl";
      if (!single) result+="ok";
      result+=" alapjn kszlt:";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorHungarian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 182 of file translator_hu.h.
    { return "enum"; }
trEnumName() [2/2]
virtual QCString TranslatorHungarian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 182 of file translator_hu.h.
    { return "enum"; }
trEnumReference() [1/2]
virtual QCString TranslatorHungarian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1909 of file translator_hu.h.
    { return QCString(name)+" felsorol referencia"; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorHungarian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1909 of file translator_hu.h.
    { return QCString(name)+" felsorol referencia"; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorHungarian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 186 of file translator_hu.h.
    { return "enum-rtk"; }
trEnumValue() [2/2]
virtual QCString TranslatorHungarian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 186 of file translator_hu.h.
    { return "enum-rtk"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorHungarian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1374 of file translator_hu.h.
    {
      return "Esemnyek dokumentcija";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorHungarian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1374 of file translator_hu.h.
    {
      return "Esemnyek dokumentcija";
    }
trEvents() [1/2]
virtual QCString TranslatorHungarian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1369 of file translator_hu.h.
    {
      return "Esemnyek";
    }
trEvents() [2/2]
virtual QCString TranslatorHungarian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1369 of file translator_hu.h.
    {
      return "Esemnyek";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorHungarian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 444 of file translator_hu.h.
    { return "Pldk dokumentcija"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorHungarian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 444 of file translator_hu.h.
    { return "Pldk dokumentcija"; }
trExamples() [1/2]
virtual QCString TranslatorHungarian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 253 of file translator_hu.h.
    { return "Pldk"; }
trExamples() [2/2]
virtual QCString TranslatorHungarian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 253 of file translator_hu.h.
    { return "Pldk"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorHungarian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 359 of file translator_hu.h.
    { return "A pldk listja:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorHungarian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 359 of file translator_hu.h.
    { return "A pldk listja:"; }
trExceptions() [1/2]
virtual QCString TranslatorHungarian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 574 of file translator_hu.h.
    { return "Kivtelek"; }
trExceptions() [2/2]
virtual QCString TranslatorHungarian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 574 of file translator_hu.h.
    { return "Kivtelek"; }
trExtendsClass() [1/2]
virtual QCString TranslatorHungarian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1949 of file translator_hu.h.
    {
      return "@0 kiterjesztett osztly.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorHungarian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1949 of file translator_hu.h.
    {
      return "@0 kiterjesztett osztly.";
    }
trFile() [1/2]
virtual QCString TranslatorHungarian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1231 of file translator_hu.h.
    {
      QCString result((first_capital ? "Fjl" : "fjl"));
      if (!singular) result+="ok";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorHungarian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1231 of file translator_hu.h.
    {
      QCString result((first_capital ? "Fjl" : "fjl"));
      if (!singular) result+="ok";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorHungarian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 438 of file translator_hu.h.
    { return "Fjlok dokumentcija"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorHungarian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 438 of file translator_hu.h.
    { return "Fjlok dokumentcija"; }
trFileIn() [1/2]
virtual QCString TranslatorHungarian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1806 of file translator_hu.h.
    {
      return "Fjl a(z) "+name+" knyvtrban";
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorHungarian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1806 of file translator_hu.h.
    {
      return "Fjl a(z) "+name+" knyvtrban";
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorHungarian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 407 of file translator_hu.h.
    { return "Fjlmutat"; }
trFileIndex() [2/2]
virtual QCString TranslatorHungarian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 407 of file translator_hu.h.
    { return "Fjlmutat"; }
trFileList() [1/2]
virtual QCString TranslatorHungarian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 219 of file translator_hu.h.
    { return "Fjllista"; }
trFileList() [2/2]
virtual QCString TranslatorHungarian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 219 of file translator_hu.h.
    { return "Fjllista"; }
trFileListDescription() [1/2]
virtual QCString TranslatorHungarian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 267 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="fjl listja rvid lersokkal:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorHungarian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 267 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="fjl listja rvid lersokkal:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorHungarian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 236 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globlis elemek";
      }
      else
      {
        return "Fjlelemek";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorHungarian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 236 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globlis elemek";
      }
      else
      {
        return "Fjlelemek";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorHungarian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 337 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="fggvny, vltoz, makrdefinci, enumerci s tpusdefinci";
      }
      else
      {
        result+="fjlelem";
      }
      result+=" listja, valamint hivatkozs ";
      if (extractAll)
        result+="a fjlokra, amikhez tartoznak:";
      else
        result+="a dokumentcira:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorHungarian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 337 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="fggvny, vltoz, makrdefinci, enumerci s tpusdefinci";
      }
      else
      {
        result+="fjlelem";
      }
      result+=" listja, valamint hivatkozs ";
      if (extractAll)
        result+="a fjlokra, amikhez tartoznak:";
      else
        result+="a dokumentcira:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorHungarian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 641 of file translator_hu.h.
    {
      QCString result=fileName;
      result+=" fjlreferencia";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorHungarian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 641 of file translator_hu.h.
    {
      QCString result=fileName;
      result+=" fjlreferencia";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorHungarian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 601 of file translator_hu.h.
    { return "Bartok"; }
trFriends() [2/2]
virtual QCString TranslatorHungarian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 601 of file translator_hu.h.
    { return "Bartok"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorHungarian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 508 of file translator_hu.h.
    { return "Fggvnyek dokumentcija"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorHungarian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 508 of file translator_hu.h.
    { return "Fggvnyek dokumentcija"; }
trFunctions() [1/2]
virtual QCString TranslatorHungarian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 472 of file translator_hu.h.
    { return "Fggvnyek"; }
trFunctions() [2/2]
virtual QCString TranslatorHungarian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 472 of file translator_hu.h.
    { return "Fggvnyek"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorHungarian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 535 of file translator_hu.h.
    {
      QCString result="";
      if (!projName.isEmpty()) result+="Projekt: "+projName;
      result+=" Kszlt: "+date+" Ksztette: ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorHungarian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 535 of file translator_hu.h.
    {
      QCString result="";
      if (!projName.isEmpty()) result+="Projekt: "+projName;
      result+=" Kszlt: "+date+" Ksztette: ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorHungarian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 174 of file translator_hu.h.
    { QCString result="Ezt a dokumentcit a Doxygen ksztette ";
      if (!s.isEmpty()) result+=QCString(" a") + zed(s[0])+s+" projekthez";
      result+=" a forrskdbl.";
      return result;
    }
References s, and zed().
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorHungarian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 174 of file translator_hu.h.
    { QCString result="Ezt a dokumentcit a Doxygen ksztette ";
      if (!s.isEmpty()) result+=QCString(" a") + zed(s[0])+s+" projekthez";
      result+=" a forrskdbl.";
      return result;
    }
References s, and zed().
trGeneratedBy() [1/2]
virtual QCString TranslatorHungarian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 578 of file translator_hu.h.
    { return "Ksztette"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorHungarian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 578 of file translator_hu.h.
    { return "Ksztette"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorHungarian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 779 of file translator_hu.h.
    { // single is true implies a single file
      QCString result="Ez a dokumentci ";
      switch(compType)
      {
        case ClassDef::Class: result+="az osztlyrl"; break;
        case ClassDef::Struct: result+="a struktrrl"; break;
        case ClassDef::Union: result+="az unirl"; break;
        case ClassDef::Interface: result+="az interfszrl"; break;
        case ClassDef::Protocol: result+="a protokollrl"; break;
        case ClassDef::Category: result+="a kategrirl"; break;
        case ClassDef::Exception: result+="a kivtelrl"; break;
        default: break;
      }
      result+=" a kvetkez fjl";
      if (!single) result+="ok";
      result+=" alapjn kszlt:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorHungarian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 779 of file translator_hu.h.
    { // single is true implies a single file
      QCString result="Ez a dokumentci ";
      switch(compType)
      {
        case ClassDef::Class: result+="az osztlyrl"; break;
        case ClassDef::Struct: result+="a struktrrl"; break;
        case ClassDef::Union: result+="az unirl"; break;
        case ClassDef::Interface: result+="az interfszrl"; break;
        case ClassDef::Protocol: result+="a protokollrl"; break;
        case ClassDef::Category: result+="a kategrirl"; break;
        case ClassDef::Exception: result+="a kivtelrl"; break;
        default: break;
      }
      result+=" a kvetkez fjl";
      if (!single) result+="ok";
      result+=" alapjn kszlt:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorHungarian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1714 of file translator_hu.h.
    {
      // single is true implies a single file
      QCString result="Ez a dokumentci ";
      switch(compType)
      {
        case ClassDef::Class: result+="a modulrl"; break;
        case ClassDef::Struct: result+="a tpusrl"; break;
        case ClassDef::Union: result+="az unirl"; break;
        case ClassDef::Interface: result+="az interfszrl"; break;
        case ClassDef::Protocol: result+="a protokollrl"; break;
        case ClassDef::Category: result+="a kategrirl"; break;
        case ClassDef::Exception: result+="a kivtelrl"; break;
        default: break;
      }
      result+=" a kvetkez fjl";
      if (!single) result+="ok";
      result+=" alapjn kszlt:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorHungarian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1714 of file translator_hu.h.
    {
      // single is true implies a single file
      QCString result="Ez a dokumentci ";
      switch(compType)
      {
        case ClassDef::Class: result+="a modulrl"; break;
        case ClassDef::Struct: result+="a tpusrl"; break;
        case ClassDef::Union: result+="az unirl"; break;
        case ClassDef::Interface: result+="az interfszrl"; break;
        case ClassDef::Protocol: result+="a protokollrl"; break;
        case ClassDef::Category: result+="a kategrirl"; break;
        case ClassDef::Exception: result+="a kivtelrl"; break;
        default: break;
      }
      result+=" a kvetkez fjl";
      if (!single) result+="ok";
      result+=" alapjn kszlt:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorHungarian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1287 of file translator_hu.h.
    {
      QCString result((first_capital ? "Globlis elem" : "globlis elem"));
      if (!singular) result+="ek";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorHungarian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1287 of file translator_hu.h.
    {
      QCString result((first_capital ? "Globlis elem" : "globlis elem"));
      if (!singular) result+="ek";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorHungarian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1781 of file translator_hu.h.
    {
      return "Globlis nvtr";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorHungarian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1781 of file translator_hu.h.
    {
      return "Globlis nvtr";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorHungarian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 866 of file translator_hu.h.
    {
      return "Ugrs a fjl dokumentcijhoz.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorHungarian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 866 of file translator_hu.h.
    {
      return "Ugrs a fjl dokumentcijhoz.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorHungarian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 899 of file translator_hu.h.
    {
      return "Ugrs az osztlyhierarchia-brhoz";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorHungarian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 899 of file translator_hu.h.
    {
      return "Ugrs az osztlyhierarchia-brhoz";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorHungarian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 861 of file translator_hu.h.
    {
      return "Ugrs a fjl forrskdjhoz.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorHungarian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 861 of file translator_hu.h.
    {
      return "Ugrs a fjl forrskdjhoz.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorHungarian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 903 of file translator_hu.h.
    {
      return "Ugrs az szveges osztlyhierarchihoz";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorHungarian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 903 of file translator_hu.h.
    {
      return "Ugrs az szveges osztlyhierarchihoz";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorHungarian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 895 of file translator_hu.h.
    {
      return "Osztlyhierarchia-bra";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorHungarian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 895 of file translator_hu.h.
    {
      return "Osztlyhierarchia-bra";
    }
trGroup() [1/2]
virtual QCString TranslatorHungarian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1254 of file translator_hu.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="ok";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorHungarian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1254 of file translator_hu.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="ok";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorHungarian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 386 of file translator_hu.h.
    { return "Hierarchikus mutat"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorHungarian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 386 of file translator_hu.h.
    { return "Hierarchikus mutat"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorHungarian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1325 of file translator_hu.h.
    {
      return "Megvalstja a kvetkezket: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorHungarian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1325 of file translator_hu.h.
    {
      return "Megvalstja a kvetkezket: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorHungarian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1333 of file translator_hu.h.
    {
      return "Megvalstjk a kvetkezk: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorHungarian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1333 of file translator_hu.h.
    {
      return "Megvalstjk a kvetkezk: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorHungarian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 995 of file translator_hu.h.
    {
      return "Ez az bra azt mutatja, hogy mely fjlok gyazzk be "
             "kzvetve vagy kzvetlenl ezt a fjlt:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorHungarian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 995 of file translator_hu.h.
    {
      return "Ez az bra azt mutatja, hogy mely fjlok gyazzk be "
             "kzvetve vagy kzvetlenl ezt a fjlt:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorHungarian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 851 of file translator_hu.h.
    {
      return QCString("A")+zed(fName[0])+fName+" defincis fjl fggsi grfja:";
    }
References zed().
trInclDepGraph() [2/2]
virtual QCString TranslatorHungarian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 851 of file translator_hu.h.
    {
      return QCString("A")+zed(fName[0])+fName+" defincis fjl fggsi grfja:";
    }
References zed().
trIncludesFileIn() [1/2]
virtual QCString TranslatorHungarian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1815 of file translator_hu.h.
    {
      return "Tartalmazott fjl a(z) "+name+" knyvtrban";
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorHungarian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1815 of file translator_hu.h.
    {
      return "Tartalmazott fjl a(z) "+name+" knyvtrban";
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorHungarian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 168 of file translator_hu.h.
    { return " osztly tagjainak teljes listja, az rklt tagokkal egytt."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorHungarian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 168 of file translator_hu.h.
    { return " osztly tagjainak teljes listja, az rklt tagokkal egytt."; }
trInheritedByList() [1/2]
virtual QCString TranslatorHungarian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 713 of file translator_hu.h.
    {
      return "Leszrmazottak: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorHungarian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 713 of file translator_hu.h.
    {
      return "Leszrmazottak: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorHungarian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1913 of file translator_hu.h.
    { return QCString(members)+" a(z) "+what+" osztlybl szrmaznak"; }
trInheritedFrom() [2/2]
virtual QCString TranslatorHungarian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1913 of file translator_hu.h.
    { return QCString(members)+" a(z) "+what+" osztlybl szrmaznak"; }
trInheritsList() [1/2]
virtual QCString TranslatorHungarian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 705 of file translator_hu.h.
    {
      return "sk: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorHungarian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 705 of file translator_hu.h.
    {
      return "sk: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorHungarian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 886 of file translator_hu.h.
    {
      return "Kezd rtk:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorHungarian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 886 of file translator_hu.h.
    {
      return "Kezd rtk:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorHungarian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1965 of file translator_hu.h.
    {
      return "Pldny metdusok";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorHungarian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1965 of file translator_hu.h.
    {
      return "Pldny metdusok";
    }
trInterfaces() [1/2]
virtual QCString TranslatorHungarian::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1982 of file translator_hu.h.
    { return "Exportlt interfszek"; }
trInterfaces() [2/2]
virtual QCString TranslatorHungarian::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1982 of file translator_hu.h.
    { return "Exportlt interfszek"; }
trInvariant() [1/2]
virtual QCString TranslatorHungarian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 881 of file translator_hu.h.
    {
      return "Invarins";
    }
trInvariant() [2/2]
virtual QCString TranslatorHungarian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 881 of file translator_hu.h.
    {
      return "Invarins";
    }
trISOLang() [1/2]
virtual QCString TranslatorHungarian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 103 of file translator_hu.h.
    {
      return "hu";
    }
trISOLang() [2/2]
virtual QCString TranslatorHungarian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 103 of file translator_hu.h.
    {
      return "hu";
    }
trLegend() [1/2]
virtual QCString TranslatorHungarian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1080 of file translator_hu.h.
    {
      return "Jelmagyarzat";
    }
trLegend() [2/2]
virtual QCString TranslatorHungarian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1080 of file translator_hu.h.
    {
      return "Jelmagyarzat";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorHungarian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1017 of file translator_hu.h.
    {
      return
        "Ez az oldal elmagyarzza hogyan kell rtelmezni a "
        "doxygen ltal ksztett brkat.<p>\n"
        "Vegyk a kvetkez pldt:\n"
        "\\code\n"
        "/*! Vgs miatt nem lthat osztly */\n"
        "class Invisible { };\n\n"
        "/*! Levgott osztly, szrmazsa rejtett */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Doxygen kommentekkel nem dokumentlt osztly */\n"
        "class Undocumented { };\n\n"
        "/*! Publikus szrmaztatsal levezetett osztly */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Egy sablonosztly */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Vdett szrmaztatsal levezetett osztly */\n"
        "class ProtectedBase { };\n\n"
        "/*! Privt szrmaztatsal levezetett osztly */\n"
        "class PrivateBase { };\n\n"
        "/*! Osztly, melyet a szrmaztatott osztly hasznl */\n"
        "class Used { };\n\n"
        "/*! Osztly, mely tbb msiknak leszrmazottja */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Az eredmny a kvetkez bra lesz:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "A fenti brn lev dobozok jelentse a kvetkez:\n"
        "<ul>\n"
        "<li>Kitlttt fekete doboz jelzi azt az osztlyt vagy struktrt,"
        "amelyrl az bra szl.</li>\n"
        "<li>Fekete keret jelzi a dokumentlt osztlyokat s struktrkat.</li>\n"
        "<li>Szrke keret jelzi a nem dokumentlt osztlyokat s struktrkat.</li>\n"
        "<li>Piros keret jelzi azokat az osztlyokat s struktrkat, amelyeknl vgs miatt nem lthat "
        "az sszes leszrmaztatsi kapcsolat. Egy bra vgsra kerl, ha nem fr bele "
        "a megadott tartomnyba.</li>\n"
        "</ul>\n"
        "<p>\n"
        "A nyilak jelentse a kvetkez:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Sttkk nyl jelzi a publikus szrmaztats "
        "kapcsolatt kt osztly kztt.</li>\n"
        "<li>Sttzld nyl jelzi a vdett szrmaztatst.</li>\n"
        "<li>Sttvrs nyl jelzi a privt szrmaztatst.</li>\n"
        "<li>Lila szaggatott nyl jelzi, ha az osztly egy msikat hasznl vagy tartalmaz. "
        "A nyl felirata jelzi a vltoz(k) nevt, amelyeken keresztl a msik osztly kapcsoldik.</li>\n"
        "<li>Srga szaggatott nyl jelzi a kapcsolatot a sablonpldny s a pldnyostott "
        "osztlysablon kztt. A nyl felirata jelzi a plny sablonparamtereit.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorHungarian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1017 of file translator_hu.h.
    {
      return
        "Ez az oldal elmagyarzza hogyan kell rtelmezni a "
        "doxygen ltal ksztett brkat.<p>\n"
        "Vegyk a kvetkez pldt:\n"
        "\\code\n"
        "/*! Vgs miatt nem lthat osztly */\n"
        "class Invisible { };\n\n"
        "/*! Levgott osztly, szrmazsa rejtett */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Doxygen kommentekkel nem dokumentlt osztly */\n"
        "class Undocumented { };\n\n"
        "/*! Publikus szrmaztatsal levezetett osztly */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Egy sablonosztly */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Vdett szrmaztatsal levezetett osztly */\n"
        "class ProtectedBase { };\n\n"
        "/*! Privt szrmaztatsal levezetett osztly */\n"
        "class PrivateBase { };\n\n"
        "/*! Osztly, melyet a szrmaztatott osztly hasznl */\n"
        "class Used { };\n\n"
        "/*! Osztly, mely tbb msiknak leszrmazottja */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Az eredmny a kvetkez bra lesz:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "A fenti brn lev dobozok jelentse a kvetkez:\n"
        "<ul>\n"
        "<li>Kitlttt fekete doboz jelzi azt az osztlyt vagy struktrt,"
        "amelyrl az bra szl.</li>\n"
        "<li>Fekete keret jelzi a dokumentlt osztlyokat s struktrkat.</li>\n"
        "<li>Szrke keret jelzi a nem dokumentlt osztlyokat s struktrkat.</li>\n"
        "<li>Piros keret jelzi azokat az osztlyokat s struktrkat, amelyeknl vgs miatt nem lthat "
        "az sszes leszrmaztatsi kapcsolat. Egy bra vgsra kerl, ha nem fr bele "
        "a megadott tartomnyba.</li>\n"
        "</ul>\n"
        "<p>\n"
        "A nyilak jelentse a kvetkez:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Sttkk nyl jelzi a publikus szrmaztats "
        "kapcsolatt kt osztly kztt.</li>\n"
        "<li>Sttzld nyl jelzi a vdett szrmaztatst.</li>\n"
        "<li>Sttvrs nyl jelzi a privt szrmaztatst.</li>\n"
        "<li>Lila szaggatott nyl jelzi, ha az osztly egy msikat hasznl vagy tartalmaz. "
        "A nyl felirata jelzi a vltoz(k) nevt, amelyeken keresztl a msik osztly kapcsoldik.</li>\n"
        "<li>Srga szaggatott nyl jelzi a kapcsolatot a sablonpldny s a pldnyostott "
        "osztlysablon kztt. A nyl felirata jelzi a plny sablonparamtereit.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorHungarian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1010 of file translator_hu.h.
    {
      return "Jelmagyarzat";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorHungarian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1010 of file translator_hu.h.
    {
      return "Jelmagyarzat";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorHungarian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 156 of file translator_hu.h.
    { return "A tagok teljes listja"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorHungarian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 156 of file translator_hu.h.
    { return "A tagok teljes listja"; }
trLoading() [1/2]
virtual QCString TranslatorHungarian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1775 of file translator_hu.h.
    {
      return "Betlts...";
    }
trLoading() [2/2]
virtual QCString TranslatorHungarian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1775 of file translator_hu.h.
    {
      return "Betlts...";
    }
trMainPage() [1/2]
virtual QCString TranslatorHungarian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 810 of file translator_hu.h.
    { return "Foldal"; }
trMainPage() [2/2]
virtual QCString TranslatorHungarian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 810 of file translator_hu.h.
    { return "Foldal"; }
trMember() [1/2]
virtual QCString TranslatorHungarian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1276 of file translator_hu.h.
    {
      QCString result((first_capital ? "Tag" : "tag"));
      if (!singular) result+="ok";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorHungarian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1276 of file translator_hu.h.
    {
      QCString result((first_capital ? "Tag" : "tag"));
      if (!singular) result+="ok";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorHungarian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 139 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatmezk dokumentcija";
      }
      else
      {
        return "Adattagok dokumentcija";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorHungarian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 139 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatmezk dokumentcija";
      }
      else
      {
        return "Adattagok dokumentcija";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorHungarian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 131 of file translator_hu.h.
    { return "Enumerci-tagok dokumentcija"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorHungarian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 131 of file translator_hu.h.
    { return "Enumerci-tagok dokumentcija"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorHungarian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 135 of file translator_hu.h.
    { return "Tagfggvnyek dokumentcija"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorHungarian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 135 of file translator_hu.h.
    { return "Tagfggvnyek dokumentcija"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorHungarian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1567 of file translator_hu.h.
    { return "Tagfggvny/Alprogram dokumentci"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorHungarian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1567 of file translator_hu.h.
    { return "Tagfggvny/Alprogram dokumentci"; }
trMemberList() [1/2]
virtual QCString TranslatorHungarian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 160 of file translator_hu.h.
    { return "Taglista"; }
trMemberList() [2/2]
virtual QCString TranslatorHungarian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 160 of file translator_hu.h.
    { return "Taglista"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorHungarian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 127 of file translator_hu.h.
    { return "Tpusdefinci-tagok dokumentcija"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorHungarian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 127 of file translator_hu.h.
    { return "Tpusdefinci-tagok dokumentcija"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorHungarian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1972 of file translator_hu.h.
    {
      return "Metdus dokumentci";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorHungarian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1972 of file translator_hu.h.
    {
      return "Metdus dokumentci";
    }
trModule() [1/2]
virtual QCString TranslatorHungarian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1704 of file translator_hu.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="s";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorHungarian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1704 of file translator_hu.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="s";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorHungarian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 413 of file translator_hu.h.
    { return "Modulok dokumentcija"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorHungarian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 413 of file translator_hu.h.
    { return "Modulok dokumentcija"; }
trModuleIndex() [1/2]
virtual QCString TranslatorHungarian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 380 of file translator_hu.h.
    { return "Modulmutat"; }
trModuleIndex() [2/2]
virtual QCString TranslatorHungarian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 380 of file translator_hu.h.
    { return "Modulmutat"; }
trModuleReference() [1/2]
virtual QCString TranslatorHungarian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1666 of file translator_hu.h.
    {
      QCString result=namespaceName;
      result+=" modul hivatkozs";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorHungarian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1666 of file translator_hu.h.
    {
      QCString result=namespaceName;
      result+=" modul hivatkozs";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorHungarian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 198 of file translator_hu.h.
    { return "Modulok"; }
trModules() [2/2]
virtual QCString TranslatorHungarian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 198 of file translator_hu.h.
    { return "Modulok"; }
trModulesDescription() [1/2]
virtual QCString TranslatorHungarian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 367 of file translator_hu.h.
    { return "A modulok listja:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorHungarian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 367 of file translator_hu.h.
    { return "A modulok listja:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorHungarian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1697 of file translator_hu.h.
    { return "Modulok indexe"; }
trModulesIndex() [2/2]
virtual QCString TranslatorHungarian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1697 of file translator_hu.h.
    { return "Modulok indexe"; }
trModulesList() [1/2]
virtual QCString TranslatorHungarian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1632 of file translator_hu.h.
    { return "Modulok listja"; }
trModulesList() [2/2]
virtual QCString TranslatorHungarian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1632 of file translator_hu.h.
    { return "Modulok listja"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorHungarian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1636 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="rvid lerssal elltott modul:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorHungarian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1636 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="rvid lerssal elltott modul:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorHungarian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1678 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="modul adattagja hivatkozsokkal elltva ";
      if (extractAll)
      {
        result+="az egyes adattagok moduljainak dokumentcijra:";
      }
      else
      {
        result+="azokhoz a modulokhoz, amelyekhez tartoznak:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorHungarian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1678 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="modul adattagja hivatkozsokkal elltva ";
      if (extractAll)
      {
        result+="az egyes adattagok moduljainak dokumentcijra:";
      }
      else
      {
        result+="azokhoz a modulokhoz, amelyekhez tartoznak:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorHungarian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1674 of file translator_hu.h.
    { return "Modul adattagok"; }
trModulesMembers() [2/2]
virtual QCString TranslatorHungarian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1674 of file translator_hu.h.
    { return "Modul adattagok"; }
trMonth() [1/2]
virtual QCString TranslatorHungarian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1854 of file translator_hu.h.
    {
      static const char *months_short[] = { "jan.", "febr.", "mrc.", "pr.", "mj.", "jn.", "jl.", "aug.", "szept.", "okt.", "nov.", "dec." };
      static const char *months_full[] = { "janur", "februr", "mrcius", "prilis", "mjus", "jnius", "jlius", "augusztus", "szeptember", "oktber", "november", "december" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorHungarian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1854 of file translator_hu.h.
    {
      static const char *months_short[] = { "jan.", "febr.", "mrc.", "pr.", "mj.", "jn.", "jl.", "aug.", "szept.", "okt.", "nov.", "dec." };
      static const char *months_full[] = { "janur", "februr", "mrcius", "prilis", "mjus", "jnius", "jlius", "augusztus", "szeptember", "oktber", "november", "december" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorHungarian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 152 of file translator_hu.h.
    { return "Rszletek..."; }
trMore() [2/2]
virtual QCString TranslatorHungarian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 152 of file translator_hu.h.
    { return "Rszletek..."; }
trNamespace() [1/2]
virtual QCString TranslatorHungarian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1242 of file translator_hu.h.
    {
      QCString result("");
      if (!singular) result+=first_capital ? "Nvterek" : "nvterek";
      else result+=first_capital ? "Nvtr" : "nvtr";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorHungarian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1242 of file translator_hu.h.
    {
      QCString result("");
      if (!singular) result+=first_capital ? "Nvterek" : "nvterek";
      else result+=first_capital ? "Nvtr" : "nvtr";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorHungarian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 759 of file translator_hu.h.
    { return "Nvterek dokumentcija"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorHungarian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 759 of file translator_hu.h.
    { return "Nvterek dokumentcija"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorHungarian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 753 of file translator_hu.h.
    { return "Nvtrmutat"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorHungarian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 753 of file translator_hu.h.
    { return "Nvtrmutat"; }
trNamespaceList() [1/2]
virtual QCString TranslatorHungarian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 586 of file translator_hu.h.
    { return "Nvtrlista"; }
trNamespaceList() [2/2]
virtual QCString TranslatorHungarian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 586 of file translator_hu.h.
    { return "Nvtrlista"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorHungarian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 590 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="nvtr listja rvid lersokkal:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorHungarian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 590 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="nvtr listja rvid lersokkal:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorHungarian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 739 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="nvtr tagjainak listja, valamint hivatkozs ";
      if (extractAll)
        result+=" a megfelel nvtr dokumentcira minden tagnl:";
      else
        result+=" a nvterekre, amelynek tagjai:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorHungarian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 739 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="nvtr tagjainak listja, valamint hivatkozs ";
      if (extractAll)
        result+=" a megfelel nvtr dokumentcira minden tagnl:";
      else
        result+=" a nvterekre, amelynek tagjai:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorHungarian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 735 of file translator_hu.h.
    { return "Nvtrtagok"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorHungarian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 735 of file translator_hu.h.
    { return "Nvtrtagok"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorHungarian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 649 of file translator_hu.h.
    {
      QCString result=namespaceName;
      result+=" nvtr-referencia";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorHungarian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 649 of file translator_hu.h.
    {
      QCString result=namespaceName;
      result+=" nvtr-referencia";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorHungarian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 769 of file translator_hu.h.
    { return "Nvterek"; }
trNamespaces() [2/2]
virtual QCString TranslatorHungarian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 769 of file translator_hu.h.
    { return "Nvterek"; }
trNoMatches() [1/2]
virtual QCString TranslatorHungarian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1793 of file translator_hu.h.
    {
      return "Nincs egyezs";
    }
trNoMatches() [2/2]
virtual QCString TranslatorHungarian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1793 of file translator_hu.h.
    {
      return "Nincs egyezs";
    }
trNote() [1/2]
virtual QCString TranslatorHungarian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_hu.h.
    {
      return "Megjegyzs";
    }
trNote() [2/2]
virtual QCString TranslatorHungarian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_hu.h.
    {
      return "Megjegyzs";
    }
trOverloadText() [1/2]
virtual QCString TranslatorHungarian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1538 of file translator_hu.h.
    {
       return "Ez egy tlterhelt tagfggvny, "
              "a knyelem rdekben. A fenti fggvnytl csak abban klnbzik, "
              "hogy milyen argumentumokat fogad el.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorHungarian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1538 of file translator_hu.h.
    {
       return "Ez egy tlterhelt tagfggvny, "
              "a knyelem rdekben. A fenti fggvnytl csak abban klnbzik, "
              "hogy milyen argumentumokat fogad el.";
    }
trPackage() [1/2]
virtual QCString TranslatorHungarian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1132 of file translator_hu.h.
    {
      return name+" csomag";
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorHungarian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1132 of file translator_hu.h.
    {
      return name+" csomag";
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorHungarian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1410 of file translator_hu.h.
    {
      return "Csomag attribtumok";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorHungarian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1410 of file translator_hu.h.
    {
      return "Csomag attribtumok";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorHungarian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1392 of file translator_hu.h.
    {
      return "Csomag fggvnyek";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorHungarian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1392 of file translator_hu.h.
    {
      return "Csomag fggvnyek";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorHungarian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1137 of file translator_hu.h.
    {
      return "A csomagok rvid lersai (ha lteznek):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorHungarian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1137 of file translator_hu.h.
    {
      return "A csomagok rvid lersai (ha lteznek):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorHungarian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1396 of file translator_hu.h.
    {
      return "Csomag tagok";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorHungarian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1396 of file translator_hu.h.
    {
      return "Csomag tagok";
    }
trPackages() [1/2]
virtual QCString TranslatorHungarian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1142 of file translator_hu.h.
    {
      return "Csomagok";
    }
trPackages() [2/2]
virtual QCString TranslatorHungarian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1142 of file translator_hu.h.
    {
      return "Csomagok";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorHungarian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1385 of file translator_hu.h.
    {
      return "Csomag tpusok";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorHungarian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1385 of file translator_hu.h.
    {
      return "Csomag tpusok";
    }
trPage() [1/2]
virtual QCString TranslatorHungarian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1265 of file translator_hu.h.
    {
      QCString result((first_capital ? "Oldal" : "oldal"));
      if (!singular) result+="ak";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorHungarian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1265 of file translator_hu.h.
    {
      QCString result((first_capital ? "Oldal" : "oldal"));
      if (!singular) result+="ak";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorHungarian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 816 of file translator_hu.h.
    { return "o."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorHungarian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 816 of file translator_hu.h.
    { return "o."; }
trPageIndex() [1/2]
virtual QCString TranslatorHungarian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 907 of file translator_hu.h.
    {
      return "Oldalmutat";
    }
trPageIndex() [2/2]
virtual QCString TranslatorHungarian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 907 of file translator_hu.h.
    {
      return "Oldalmutat";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorHungarian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1930 of file translator_hu.h.
    {
      QCString opt = enable ? "engedlyez" : "letilt";
      return "Kattintson a(z) "+opt+" panel synchronisation";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorHungarian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1930 of file translator_hu.h.
    {
      QCString opt = enable ? "engedlyez" : "letilt";
      return "Kattintson a(z) "+opt+" panel synchronisation";
    }
trParameters() [1/2]
virtual QCString TranslatorHungarian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 570 of file translator_hu.h.
    { return "Paramterek"; }
trParameters() [2/2]
virtual QCString TranslatorHungarian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 570 of file translator_hu.h.
    { return "Paramterek"; }
trPostcondition() [1/2]
virtual QCString TranslatorHungarian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 876 of file translator_hu.h.
    {
      return "Utfelttel";
    }
trPostcondition() [2/2]
virtual QCString TranslatorHungarian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 876 of file translator_hu.h.
    {
      return "Utfelttel";
    }
trPrecondition() [1/2]
virtual QCString TranslatorHungarian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 871 of file translator_hu.h.
    {
      return "Elfelttel";
    }
trPrecondition() [2/2]
virtual QCString TranslatorHungarian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 871 of file translator_hu.h.
    {
      return "Elfelttel";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorHungarian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 955 of file translator_hu.h.
    {
      return "Privt attribtumok";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorHungarian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 955 of file translator_hu.h.
    {
      return "Privt attribtumok";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorHungarian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 670 of file translator_hu.h.
    { return "Privt tagfggvnyek"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorHungarian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 670 of file translator_hu.h.
    { return "Privt tagfggvnyek"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorHungarian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 672 of file translator_hu.h.
    { return "Privt rsek"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorHungarian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 672 of file translator_hu.h.
    { return "Privt rsek"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorHungarian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 951 of file translator_hu.h.
    {
      return "Privt tpusok";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorHungarian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 951 of file translator_hu.h.
    {
      return "Privt tpusok";
    }
trProperties() [1/2]
virtual QCString TranslatorHungarian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1105 of file translator_hu.h.
    {
      return "Tulajdonsgok";
    }
trProperties() [2/2]
virtual QCString TranslatorHungarian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1105 of file translator_hu.h.
    {
      return "Tulajdonsgok";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorHungarian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1110 of file translator_hu.h.
    {
      return "Tulajdonsgok dokumentcijka";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorHungarian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1110 of file translator_hu.h.
    {
      return "Tulajdonsgok dokumentcijka";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorHungarian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_hu.h.
    {
      return "Vdett attribtumok";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorHungarian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_hu.h.
    {
      return "Vdett attribtumok";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorHungarian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 664 of file translator_hu.h.
    { return "Vdett tagfggvnyek"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorHungarian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 664 of file translator_hu.h.
    { return "Vdett tagfggvnyek"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorHungarian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 666 of file translator_hu.h.
    { return "Vdett rsek"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorHungarian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 666 of file translator_hu.h.
    { return "Vdett rsek"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorHungarian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 939 of file translator_hu.h.
    {
      return "Vdett tpusok";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorHungarian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 939 of file translator_hu.h.
    {
      return "Vdett tpusok";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorHungarian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1940 of file translator_hu.h.
    {
      return "@0 kategria szerint.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorHungarian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1940 of file translator_hu.h.
    {
      return "@0 kategria szerint.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorHungarian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatmezk";
      }
      else
      {
        return "Publikus attribtumok";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorHungarian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatmezk";
      }
      else
      {
        return "Publikus attribtumok";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorHungarian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 656 of file translator_hu.h.
    { return "Publikus tagfggvnyek"; }
trPublicMembers() [2/2]
virtual QCString TranslatorHungarian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 656 of file translator_hu.h.
    { return "Publikus tagfggvnyek"; }
trPublicSlots() [1/2]
virtual QCString TranslatorHungarian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 658 of file translator_hu.h.
    { return "Publikus rsek"; }
trPublicSlots() [2/2]
virtual QCString TranslatorHungarian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 658 of file translator_hu.h.
    { return "Publikus rsek"; }
trPublicTypes() [1/2]
virtual QCString TranslatorHungarian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 920 of file translator_hu.h.
    {
      return "Publikus tpusok";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorHungarian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 920 of file translator_hu.h.
    {
      return "Publikus tpusok";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorHungarian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 983 of file translator_hu.h.
    {
      return "Hivatkozsok:";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorHungarian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 983 of file translator_hu.h.
    {
      return "Hivatkozsok:";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorHungarian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 448 of file translator_hu.h.
    { return "Referencia kziknyv"; }
trReferenceManual() [2/2]
virtual QCString TranslatorHungarian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 448 of file translator_hu.h.
    { return "Referencia kziknyv"; }
trReferences() [1/2]
virtual QCString TranslatorHungarian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1313 of file translator_hu.h.
    {
      return "Hivatkozsok";
    }
trReferences() [2/2]
virtual QCString TranslatorHungarian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1313 of file translator_hu.h.
    {
      return "Hivatkozsok";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorHungarian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 721 of file translator_hu.h.
    {
      return "jraimplementlt sk: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorHungarian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 721 of file translator_hu.h.
    {
      return "jraimplementlt sk: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorHungarian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 729 of file translator_hu.h.
    {
      return "jraimplementl leszrmazottak: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorHungarian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 729 of file translator_hu.h.
    {
      return "jraimplementl leszrmazottak: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorHungarian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 611 of file translator_hu.h.
    { return "Bart s kapcsold fggvnyek dokumentcija"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorHungarian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 611 of file translator_hu.h.
    { return "Bart s kapcsold fggvnyek dokumentcija"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorHungarian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 115 of file translator_hu.h.
    { return "Kapcsold fggvnyek"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorHungarian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 115 of file translator_hu.h.
    { return "Kapcsold fggvnyek"; }
trRelatedPages() [1/2]
virtual QCString TranslatorHungarian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 249 of file translator_hu.h.
    { return "Kapcsold lapok"; }
trRelatedPages() [2/2]
virtual QCString TranslatorHungarian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 249 of file translator_hu.h.
    { return "Kapcsold lapok"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorHungarian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 363 of file translator_hu.h.
    { return "A kapcsold dokumentcik listja:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorHungarian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 363 of file translator_hu.h.
    { return "A kapcsold dokumentcik listja:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorHungarian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 119 of file translator_hu.h.
    { return "(Figyelem! Ezek a fggvnyek nem tagjai az osztlynak!)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorHungarian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 119 of file translator_hu.h.
    { return "(Figyelem! Ezek a fggvnyek nem tagjai az osztlynak!)"; }
trRemarks() [1/2]
virtual QCString TranslatorHungarian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 987 of file translator_hu.h.
    {
      return "Megjegyzsek";
    }
trRemarks() [2/2]
virtual QCString TranslatorHungarian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 987 of file translator_hu.h.
    {
      return "Megjegyzsek";
    }
trReturns() [1/2]
virtual QCString TranslatorHungarian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 562 of file translator_hu.h.
    { return "Visszatrsi rtk"; }
trReturns() [2/2]
virtual QCString TranslatorHungarian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 562 of file translator_hu.h.
    { return "Visszatrsi rtk"; }
trReturnValues() [1/2]
virtual QCString TranslatorHungarian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 805 of file translator_hu.h.
    { return "Visszatrsi rtkek"; }
trReturnValues() [2/2]
virtual QCString TranslatorHungarian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 805 of file translator_hu.h.
    { return "Visszatrsi rtkek"; }
trRTFansicp() [1/2]
virtual QCString TranslatorHungarian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1196 of file translator_hu.h.
    {
      return "1250";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorHungarian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1196 of file translator_hu.h.
    {
      return "1250";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorHungarian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1205 of file translator_hu.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorHungarian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1205 of file translator_hu.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorHungarian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1211 of file translator_hu.h.
    {
      return "Trgymutat";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorHungarian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1211 of file translator_hu.h.
    {
      return "Trgymutat";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorHungarian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1345 of file translator_hu.h.
    {
      return "Tartalomjegyzk";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorHungarian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1345 of file translator_hu.h.
    {
      return "Tartalomjegyzk";
    }
trSearch() [1/2]
virtual QCString TranslatorHungarian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 257 of file translator_hu.h.
    { return "Keress"; }
trSearch() [2/2]
virtual QCString TranslatorHungarian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 257 of file translator_hu.h.
    { return "Keress"; }
trSearching() [1/2]
virtual QCString TranslatorHungarian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1787 of file translator_hu.h.
    {
      return "Keress...";
    }
trSearching() [2/2]
virtual QCString TranslatorHungarian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1787 of file translator_hu.h.
    {
      return "Keress...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorHungarian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1477 of file translator_hu.h.
    {
      return "Tallatok:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorHungarian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1477 of file translator_hu.h.
    {
      return "Tallatok:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorHungarian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1458 of file translator_hu.h.
    {
      if (numDocuments==0)
      {
        return "Sajnos egy dokumentum sem felelt meg a keressi feltteleknek.";
      }
      else if (numDocuments==1)
      {
        return "<b>1</b> dokumentum felelt meg a keressi feltteleknek.";
      }
      else
      {
        return "<b>$num</b> dokumentum felelt meg a keressi feltteleknek."
               "Elsnek a legjobb tallatok vannak feltntetve.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorHungarian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1458 of file translator_hu.h.
    {
      if (numDocuments==0)
      {
        return "Sajnos egy dokumentum sem felelt meg a keressi feltteleknek.";
      }
      else if (numDocuments==1)
      {
        return "<b>1</b> dokumentum felelt meg a keressi feltteleknek.";
      }
      else
      {
        return "<b>$num</b> dokumentum felelt meg a keressi feltteleknek."
               "Elsnek a legjobb tallatok vannak feltntetve.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorHungarian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1446 of file translator_hu.h.
    {
      return "A keress eredmnye";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorHungarian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1446 of file translator_hu.h.
    {
      return "A keress eredmnye";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorHungarian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 566 of file translator_hu.h.
    { return "Lsd mg"; }
trSeeAlso() [2/2]
virtual QCString TranslatorHungarian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 566 of file translator_hu.h.
    { return "Lsd mg"; }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorHungarian::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2015 of file translator_hu.h.
    {
      // single is true implies a single file
      QCString result="A szolgltats dokumentcija "
                                "a kvetkez fjl";
      if (single) result+="bl"; else result+="okbl";
      result+="lett ltrehozva:";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorHungarian::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2015 of file translator_hu.h.
    {
      // single is true implies a single file
      QCString result="A szolgltats dokumentcija "
                                "a kvetkez fjl";
      if (single) result+="bl"; else result+="okbl";
      result+="lett ltrehozva:";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorHungarian::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2001 of file translator_hu.h.
    {
      QCString result=sName;
      result+=" szolgltats referencia";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorHungarian::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2001 of file translator_hu.h.
    {
      QCString result=sName;
      result+=" szolgltats referencia";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorHungarian::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1986 of file translator_hu.h.
    { return "Mellkelt szolgltatsok"; }
trServices() [2/2]
virtual QCString TranslatorHungarian::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1986 of file translator_hu.h.
    { return "Mellkelt szolgltatsok"; }
trSignals() [1/2]
virtual QCString TranslatorHungarian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 660 of file translator_hu.h.
    { return "Szignlok"; }
trSignals() [2/2]
virtual QCString TranslatorHungarian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 660 of file translator_hu.h.
    { return "Szignlok"; }
trSince() [1/2]
virtual QCString TranslatorHungarian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1000 of file translator_hu.h.
    {
      return "Elszr bevezetve";
    }
trSince() [2/2]
virtual QCString TranslatorHungarian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1000 of file translator_hu.h.
    {
      return "Elszr bevezetve";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorHungarian::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2025 of file translator_hu.h.
    {
      // single is true implies a single file
      QCString result="Az egyke pldny dokomentcija "
                                "a kvetkez fjl";
      if (single) result+="bl"; else result+="okbl";
      result+="lett ltrehozva:";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorHungarian::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2025 of file translator_hu.h.
    {
      // single is true implies a single file
      QCString result="Az egyke pldny dokomentcija "
                                "a kvetkez fjl";
      if (single) result+="bl"; else result+="okbl";
      result+="lett ltrehozva:";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorHungarian::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2008 of file translator_hu.h.
    {
      QCString result=sName;
      result+=" egyke pldny referencia";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorHungarian::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2008 of file translator_hu.h.
    {
      QCString result=sName;
      result+=" egyke pldny referencia";
      return result;
    }
trSourceFile() [1/2]
virtual QCString TranslatorHungarian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1488 of file translator_hu.h.
    {
      return filename + " Forrsfjl";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorHungarian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1488 of file translator_hu.h.
    {
      return filename + " Forrsfjl";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorHungarian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1417 of file translator_hu.h.
    {
      return "Statikus csomag attribtumok";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorHungarian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1417 of file translator_hu.h.
    {
      return "Statikus csomag attribtumok";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorHungarian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1403 of file translator_hu.h.
    {
      return "Statikus csomag fggvnyek";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorHungarian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1403 of file translator_hu.h.
    {
      return "Statikus csomag fggvnyek";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorHungarian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 959 of file translator_hu.h.
    {
      return "Statikus privt attribtumok";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorHungarian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 959 of file translator_hu.h.
    {
      return "Statikus privt attribtumok";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorHungarian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 674 of file translator_hu.h.
    { return "Statikus privt tagfggvnyek"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorHungarian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 674 of file translator_hu.h.
    { return "Statikus privt tagfggvnyek"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorHungarian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_hu.h.
    {
      return "Statikus vdett attribtumok";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorHungarian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_hu.h.
    {
      return "Statikus vdett attribtumok";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorHungarian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 668 of file translator_hu.h.
    { return "Statikus vdett tagfggvnyek"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorHungarian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 668 of file translator_hu.h.
    { return "Statikus vdett tagfggvnyek"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorHungarian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 935 of file translator_hu.h.
    {
      return "Statikus publikus attribtumok";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorHungarian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 935 of file translator_hu.h.
    {
      return "Statikus publikus attribtumok";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorHungarian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 662 of file translator_hu.h.
    { return "Statikus publikus tagfggvnyek"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorHungarian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 662 of file translator_hu.h.
    { return "Statikus publikus tagfggvnyek"; }
trSubprogram() [1/2]
virtual QCString TranslatorHungarian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1751 of file translator_hu.h.
    {
      QCString result((first_capital ? "Alprogram" : "alprogram"));
      if (!singular) result+="ok";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorHungarian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1751 of file translator_hu.h.
    {
      QCString result((first_capital ? "Alprogram" : "alprogram"));
      if (!singular) result+="ok";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorHungarian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1622 of file translator_hu.h.
    { return "Fggvny/Alprogram dokumentci"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorHungarian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1622 of file translator_hu.h.
    { return "Fggvny/Alprogram dokumentci"; }
trSubprograms() [1/2]
virtual QCString TranslatorHungarian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1616 of file translator_hu.h.
    { return "Fggvnyek/Alprogramok"; }
trSubprograms() [2/2]
virtual QCString TranslatorHungarian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1616 of file translator_hu.h.
    { return "Fggvnyek/Alprogramok"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorHungarian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1893 of file translator_hu.h.
    { return "Sablon paramterek"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorHungarian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1893 of file translator_hu.h.
    { return "Sablon paramterek"; }
trTest() [1/2]
virtual QCString TranslatorHungarian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1090 of file translator_hu.h.
    {
      return "Teszt";
    }
trTest() [2/2]
virtual QCString TranslatorHungarian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1090 of file translator_hu.h.
    {
      return "Teszt";
    }
trTestList() [1/2]
virtual QCString TranslatorHungarian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1095 of file translator_hu.h.
    {
      return "Tesztlista";
    }
trTestList() [2/2]
virtual QCString TranslatorHungarian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1095 of file translator_hu.h.
    {
      return "Tesztlista";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorHungarian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 164 of file translator_hu.h.
    { return "A(z) "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorHungarian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 164 of file translator_hu.h.
    { return "A(z) "; }
trTodo() [1/2]
virtual QCString TranslatorHungarian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 969 of file translator_hu.h.
    {
      return "Tennival";
    }
trTodo() [2/2]
virtual QCString TranslatorHungarian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 969 of file translator_hu.h.
    {
      return "Tennival";
    }
trTodoList() [1/2]
virtual QCString TranslatorHungarian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 974 of file translator_hu.h.
    {
      return "Tennivalk listja";
    }
trTodoList() [2/2]
virtual QCString TranslatorHungarian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 974 of file translator_hu.h.
    {
      return "Tennivalk listja";
    }
trType() [1/2]
virtual QCString TranslatorHungarian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1740 of file translator_hu.h.
    {
      QCString result((first_capital ? "Tpus" : "tpus"));
      if (!singular) result+="ok";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorHungarian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1740 of file translator_hu.h.
    {
      QCString result((first_capital ? "Tpus" : "tpus"));
      if (!singular) result+="ok";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorHungarian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1759 of file translator_hu.h.
    {
      return "Tpuskorltozsok";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorHungarian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1759 of file translator_hu.h.
    {
      return "Tpuskorltozsok";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorHungarian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 496 of file translator_hu.h.
    { return "Tpusdefincik dokumentcija"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorHungarian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 496 of file translator_hu.h.
    { return "Tpusdefincik dokumentcija"; }
trTypedefs() [1/2]
virtual QCString TranslatorHungarian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 460 of file translator_hu.h.
    { return "Tpusdefincik"; }
trTypedefs() [2/2]
virtual QCString TranslatorHungarian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 460 of file translator_hu.h.
    { return "Tpusdefincik"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorHungarian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1611 of file translator_hu.h.
    { return "Adattpus dokumentci"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorHungarian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1611 of file translator_hu.h.
    { return "Adattpus dokumentci"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorHungarian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 514 of file translator_hu.h.
    { return "Vltozk dokumentcija"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorHungarian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 514 of file translator_hu.h.
    { return "Vltozk dokumentcija"; }
trVariables() [1/2]
virtual QCString TranslatorHungarian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 478 of file translator_hu.h.
    { return "Vltozk"; }
trVariables() [2/2]
virtual QCString TranslatorHungarian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 478 of file translator_hu.h.
    { return "Vltozk"; }
trVersion() [1/2]
virtual QCString TranslatorHungarian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 554 of file translator_hu.h.
    { return "Verzi"; }
trVersion() [2/2]
virtual QCString TranslatorHungarian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 554 of file translator_hu.h.
    { return "Verzi"; }
trWarning() [1/2]
virtual QCString TranslatorHungarian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 550 of file translator_hu.h.
    { return "Figyelmeztets"; }
trWarning() [2/2]
virtual QCString TranslatorHungarian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 550 of file translator_hu.h.
    { return "Figyelmeztets"; }
trWriteList() [1/2]
virtual QCString TranslatorHungarian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 680 of file translator_hu.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" s ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorHungarian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 680 of file translator_hu.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" s ";
        }
      }
      return result;
    }
References generateMarker().
zed() [1/2]
const char * TranslatorHungarian::zed (char c) [inline], [private]
Definition at line 58 of file translator_hu.h.
    {
        switch (c & ~('a' ^ 'A')) {
            case 'B': case 'C': case 'D': case 'F': case 'G':
            case 'H': case 'J': case 'K': case 'L': case 'M':
            case 'N': case 'P': case 'Q': case 'R': case 'S':
            case 'T': case 'V': case 'W': case 'X': case 'Z':
                return " ";
            default:
                return "z ";
        }
    }
References c.
Referenced by trClassDiagram(), trCollaborationDiagram(), trGeneratedAutomatically(), and trInclDepGraph().
zed() [2/2]
const char * TranslatorHungarian::zed (char c) [inline], [private]
Definition at line 58 of file translator_hu.h.
    {
        switch (c & ~('a' ^ 'A')) {
            case 'B': case 'C': case 'D': case 'F': case 'G':
            case 'H': case 'J': case 'K': case 'L': case 'M':
            case 'N': case 'P': case 'Q': case 'R': case 'S':
            case 'T': case 'V': case 'W': case 'X': case 'Z':
                return " ";
            default:
                return "z ";
        }
    }
References c.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_hu.h
doxygen/src/translator_hu.h