CondParser Class Reference
#include <condparser.h>
Public Member Functions
CondParser ()
bool parse (const QCString &fileName, int lineNr, const QCString &expr)
CondParser ()
bool parse (const QCString &fileName, int lineNr, const QCString &expr)
Private Types
enum TOKENTYPE {
NOTHING = -1
, DELIMITER
, VARIABLE
, UNKNOWN
,
NOTHING = -1
, DELIMITER
, VARIABLE
, UNKNOWN
 }
enum OPERATOR_ID {
UNKNOWN_OP = -1
, AND = 1
, OR
, NOT
,
UNKNOWN_OP = -1
, AND = 1
, OR
, NOT
 }
enum TOKENTYPE {
NOTHING = -1
, DELIMITER
, VARIABLE
, UNKNOWN
,
NOTHING = -1
, DELIMITER
, VARIABLE
, UNKNOWN
 }
enum OPERATOR_ID {
UNKNOWN_OP = -1
, AND = 1
, OR
, NOT
,
UNKNOWN_OP = -1
, AND = 1
, OR
, NOT
 }
Private Member Functions
void getToken ()
bool parseLevel1 ()
bool parseLevel2 ()
bool parseLevel3 ()
bool parseVar ()
bool evalOperator (const int opId, bool lhs, bool rhs)
bool evalVariable (const QCString &varName)
int getOperatorId (const QCString &opName)
void getToken ()
bool parseLevel1 ()
bool parseLevel2 ()
bool parseLevel3 ()
bool parseVar ()
bool evalOperator (const int opId, bool lhs, bool rhs)
bool evalVariable (const QCString &varName)
int getOperatorId (const QCString &opName)
Private Attributes
QCString m_err
error state
QCString m_expr
holds the expression
const char * m_e
points to a character in expr
QCString m_token
holds the token
TOKENTYPE m_tokenType
type of the token
Detailed Description
Copyright (C) 1997-2015 by Dimitri van Heesch.
Permission to use, copy, modify, and distribute this software and its documentation under the terms of the GNU General Public License is hereby granted. No representations are made about the suitability of this software for any purpose. It is provided `as is` without express or implied warranty. See the GNU General Public License for more details.
Documents produced by Doxygen are derivative works derived from the input used in their production; they are not affected by this license.
C++ Expression parser for ENABLED_SECTIONS in Doxygen
Features used: Operators: && AND operator || OR operator ! NOT operator
Definition at line 27 of file condparser.h.
Member Enumeration Documentation
OPERATOR_ID [1/2]
enum CondParser::OPERATOR_ID [private]
Enumerator
UNKNOWN_OP
AND
OR
NOT
UNKNOWN_OP
AND
OR
NOT
Definition at line 43 of file condparser.h.
    {
      UNKNOWN_OP = -1,
      AND = 1,
      OR,
      NOT
    };
OPERATOR_ID [2/2]
enum CondParser::OPERATOR_ID [private]
Enumerator
UNKNOWN_OP
AND
OR
NOT
UNKNOWN_OP
AND
OR
NOT
Definition at line 43 of file condparser.h.
    {
      UNKNOWN_OP = -1,
      AND = 1,
      OR,
      NOT
    };
TOKENTYPE [1/2]
enum CondParser::TOKENTYPE [private]
Enumerator
NOTHING
DELIMITER
VARIABLE
UNKNOWN
NOTHING
DELIMITER
VARIABLE
UNKNOWN
Definition at line 36 of file condparser.h.
    {
      NOTHING = -1,
      DELIMITER,
      VARIABLE,
      UNKNOWN
    };
TOKENTYPE [2/2]
enum CondParser::TOKENTYPE [private]
Enumerator
NOTHING
DELIMITER
VARIABLE
UNKNOWN
NOTHING
DELIMITER
VARIABLE
UNKNOWN
Definition at line 36 of file condparser.h.
    {
      NOTHING = -1,
      DELIMITER,
      VARIABLE,
      UNKNOWN
    };
Constructor & Destructor Documentation
CondParser() [1/2]
CondParser::CondParser () [inline]
Definition at line 31 of file condparser.h.
: m_e(0), m_tokenType(NOTHING) {}
CondParser() [2/2]
CondParser::CondParser () [inline]
Definition at line 31 of file condparser.h.
: m_e(0), m_tokenType(NOTHING) {}
Member Function Documentation
evalOperator() [1/2]
bool CondParser::evalOperator (const int opId, bool lhs, bool rhs) [private]
evaluate an operator for given values
Definition at line 267 of file condparser.cpp.
{
  switch (opId)
  {
    // level 2
    case AND: return lhs && rhs;
    case OR: return lhs || rhs;
  }
  m_err = "Internal error unknown operator: id="+QCString().setNum(opId);
  return FALSE;
}
References AND, FALSE, m_err, OR, and QCString::setNum().
Referenced by parseLevel1().
evalOperator() [2/2]
bool CondParser::evalOperator (const int opId, bool lhs, bool rhs) [private]
evalVariable() [1/2]
bool CondParser::evalVariable (const QCString & varName) [private]
evaluate a variable
Definition at line 283 of file condparser.cpp.
{
  const StringVector &list = Config_getList(ENABLED_SECTIONS);
  return std::find(list.begin(),list.end(),varName.str())!=list.end();
}
References Config_getList, and QCString::str().
Referenced by parseVar().
evalVariable() [2/2]
bool CondParser::evalVariable (const QCString & varName) [private]
getOperatorId() [1/2]
int CondParser::getOperatorId (const QCString & opName) [private]
returns the id of the given operator returns -1 if the operator is not recognized
Definition at line 91 of file condparser.cpp.
{
  // level 2
  if (opName=="&&") { return AND; }
  if (opName=="||") { return OR; }
  // not operator
  if (opName=="!") { return NOT; }
  return UNKNOWN_OP;
}
References AND, NOT, OR, and UNKNOWN_OP.
Referenced by parseLevel1(), and parseLevel2().
getOperatorId() [2/2]
int CondParser::getOperatorId (const QCString & opName) [private]
getToken() [1/2]
void CondParser::getToken () [private]
Get next token in the current string expr. Uses the data in m_expr pointed to by m_e to produce m_tokenType and m_token, set m_err in case of an error
Definition at line 108 of file condparser.cpp.
{
  m_tokenType = NOTHING;
  m_token.resize(0);
  //printf("\tgetToken e:{%c}, ascii=%i, col=%i\n", *e, *e, e-expr);
  // skip over whitespaces
  while (*m_e == ' ' || *m_e == '\t' || *m_e == '\n') // space or tab or newline
  {
    m_e++;
  }
  // check for end of expression
  if (*m_e=='\0')
  {
    // token is still empty
    m_tokenType = DELIMITER;
    return;
  }
  // check for parentheses
  if (*m_e == '(' || *m_e == ')')
  {
    m_tokenType = DELIMITER;
    m_token += *m_e++;
    return;
  }
  // check for operators (delimiters)
  if (isDelimiter(*m_e))
  {
    m_tokenType = DELIMITER;
    while (isDelimiter(*m_e))
    {
      m_token += *m_e++;
    }
    return;
  }
  // check for variables
  if (isAlpha(*m_e))
  {
    m_tokenType = VARIABLE;
    while (isAlphaNumSpec(*m_e))
    {
      m_token += *m_e++;
    }
    return;
  }
  // something unknown is found, wrong characters -> a syntax error
  m_tokenType = UNKNOWN;
  while (*m_e)
  {
    m_token += *m_e++;
  }
  m_err = QCString("Syntax error in part '")+m_token+"'";
  return;
}
References DELIMITER, isAlpha(), isAlphaNumSpec(), isDelimiter(), m_e, m_err, m_token, m_tokenType, NOTHING, QCString::resize(), UNKNOWN, and VARIABLE.
Referenced by parse(), parseLevel1(), parseLevel2(), parseLevel3(), and parseVar().
getToken() [2/2]
void CondParser::getToken () [private]
parse() [1/2]
bool CondParser::parse (const QCString & fileName, int lineNr, const QCString & expr)
Copyright (C) 1997-2015 by Dimitri van Heesch.
Permission to use, copy, modify, and distribute this software and its documentation under the terms of the GNU General Public License is hereby granted. No representations are made about the suitability of this software for any purpose. It is provided `as is` without express or implied warranty. See the GNU General Public License for more details.
Documents produced by Doxygen are derivative works derived from the input used in their production; they are not affected by this license.
C++ Expression parser for ENABLED_SECTIONS in Doxygen
Features used: Operators: && AND operator || OR operator ! NOT operator parses and evaluates the given expression.
Returns
On error, an error message is returned.
On success, the result of the expression is either `1` or `0`.
Definition at line 36 of file condparser.cpp.
{
  if (expr.isEmpty()) return false;
  m_expr = expr;
  m_tokenType = NOTHING;
  // initialize all variables
  m_e = m_expr.data(); // let m_e point to the start of the expression
  bool answer=false;
  getToken();
  if (m_tokenType==DELIMITER && m_token.isEmpty())
  {
    // empty expression: answer==FALSE
  }
  else if (m_err.isEmpty())
  {
    answer = parseLevel1();
  }
  if (!m_err.isEmpty())
  {
    warn(fileName,lineNr,"problem evaluating expression '%s': %s",
        qPrint(expr),qPrint(m_err));
  }
  //printf("expr='%s' answer=%d\n",expr,answer);
  return answer;
}
References QCString::data(), DELIMITER, getToken(), QCString::isEmpty(), m_e, m_err, m_expr, m_token, m_tokenType, NOTHING, parseLevel1(), qPrint(), and warn().
Referenced by handleGuard(), and startCondSection().
parse() [2/2]
bool CondParser::parse (const QCString & fileName, int lineNr, const QCString & expr)
parseLevel1() [1/2]
bool CondParser::parseLevel1 () [private]
conditional operators AND and OR
Definition at line 173 of file condparser.cpp.
{
  bool ans = parseLevel2();
  int opId = getOperatorId(m_token);
  while (opId==AND || opId==OR)
  {
    getToken();
    ans = evalOperator(opId, ans, parseLevel2());
    opId = getOperatorId(m_token);
  }
  return ans;
}
References AND, evalOperator(), getOperatorId(), getToken(), m_token, OR, and parseLevel2().
Referenced by parse(), and parseLevel3().
parseLevel1() [2/2]
bool CondParser::parseLevel1 () [private]
parseLevel2() [1/2]
bool CondParser::parseLevel2 () [private]
NOT
Definition at line 191 of file condparser.cpp.
{
  bool ans;
  int opId = getOperatorId(m_token);
  if (opId == NOT)
  {
    getToken();
    ans = !parseLevel3();
  }
  else
  {
    ans = parseLevel3();
  }
  return ans;
}
References getOperatorId(), getToken(), m_token, NOT, and parseLevel3().
Referenced by parseLevel1().
parseLevel2() [2/2]
bool CondParser::parseLevel2 () [private]
parseLevel3() [1/2]
bool CondParser::parseLevel3 () [private]
parenthesized expression or variable
Definition at line 212 of file condparser.cpp.
{
  // check if it is a parenthesized expression
  if (m_tokenType == DELIMITER)
  {
    if (m_token=="(")
    {
      getToken();
      int ans = parseLevel1();
      if (m_tokenType!=DELIMITER || m_token!=")")
      {
        m_err="Parenthesis) missing";
        return FALSE;
      }
      getToken();
      return ans;
    }
  }
  // if not parenthesized then the expression is a variable
  return parseVar();
}
References DELIMITER, FALSE, getToken(), m_err, m_token, m_tokenType, parseLevel1(), and parseVar().
Referenced by parseLevel2().
parseLevel3() [2/2]
bool CondParser::parseLevel3 () [private]
parseVar() [1/2]
bool CondParser::parseVar () [private]
Definition at line 236 of file condparser.cpp.
{
  bool ans = false;
  switch (m_tokenType)
  {
    case VARIABLE:
      // this is a variable
      ans = evalVariable(m_token);
      getToken();
      break;
    default:
      // syntax error or unexpected end of expression
      if (m_token.isEmpty())
      {
        m_err="Unexpected end of expression";
        return FALSE;
      }
      else
      {
        m_err="Value expected";
        return FALSE;
      }
      break;
  }
  return ans;
}
References evalVariable(), FALSE, getToken(), QCString::isEmpty(), m_err, m_token, m_tokenType, and VARIABLE.
Referenced by parseLevel3().
parseVar() [2/2]
bool CondParser::parseVar () [private]
Member Data Documentation
m_e
const char * CondParser::m_e [private]
points to a character in expr
Definition at line 56 of file condparser.h.
Referenced by getToken(), and parse().
m_err
QCString CondParser::m_err [private]
error state
Definition at line 54 of file condparser.h.
Referenced by evalOperator(), getToken(), parse(), parseLevel3(), and parseVar().
m_expr
QCString CondParser::m_expr [private]
holds the expression
Definition at line 55 of file condparser.h.
Referenced by parse().
m_token
QCString CondParser::m_token [private]
holds the token
Definition at line 58 of file condparser.h.
Referenced by getToken(), parse(), parseLevel1(), parseLevel2(), parseLevel3(), and parseVar().
m_tokenType
TOKENTYPE CondParser::m_tokenType [private]
type of the token
Definition at line 59 of file condparser.h.
Referenced by getToken(), parse(), parseLevel3(), and parseVar().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/condparser.h
doxygen/src/condparser.h
doxygen/build/doxygen/src/condparser.cpp
doxygen/src/condparser.cpp