SymbolGroupListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
SymbolGroupListContext (const SearchIndexList &sil)
virtual ~SymbolGroupListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
SymbolGroupListContext (const SearchIndexList &sil)
virtual ~SymbolGroupListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc (const SearchIndexList &sil)
static TemplateListIntfPtr alloc (const SearchIndexList &sil)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 1292 of file context.h.
Constructor & Destructor Documentation
SymbolGroupListContext() [1/2]
SymbolGroupListContext::SymbolGroupListContext (const SearchIndexList & sil)
Definition at line 8634 of file context.cpp.
                                                                         : p(std::make_unique<Private>(sil))
{
}
 SymbolGroupListContext() [1/2]
SymbolGroupListContext::~SymbolGroupListContext () [virtual]
Definition at line 8638 of file context.cpp.
{
}
SymbolGroupListContext() [2/2]
SymbolGroupListContext::SymbolGroupListContext (const SearchIndexList & sil)
 SymbolGroupListContext() [2/2]
virtual SymbolGroupListContext::~SymbolGroupListContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr SymbolGroupListContext::alloc (const SearchIndexList & sil) [inline], [static]
Definition at line 1295 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<SymbolGroupListContext>(sil)); }
Referenced by SymbolIndexContext::Private::createSymbolGroups().
alloc() [2/2]
static TemplateListIntfPtr SymbolGroupListContext::alloc (const SearchIndexList & sil) [inline], [static]
Definition at line 1295 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<SymbolGroupListContext>(sil)); }
at() [1/2]
TemplateVariant SymbolGroupListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 8648 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant SymbolGroupListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t SymbolGroupListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 8643 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t SymbolGroupListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr SymbolGroupListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 8653 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr SymbolGroupListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > SymbolGroupListContext::p [private]
Definition at line 1308 of file context.h.
Referenced by at(), count(), and createIterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp