HtmlSpaceless Class Reference
Public Member Functions
HtmlSpaceless ()
std::unique_ptr< TemplateSpacelessIntf > clone ()
void reset ()
QCString remove (const QCString &s)
HtmlSpaceless ()
std::unique_ptr< TemplateSpacelessIntf > clone ()
void reset ()
QCString remove (const QCString &s)
Private Attributes
bool m_insideTag
char m_insideString
bool m_removeSpaces
Detailed Description
Definition at line 8902 of file context.cpp.
Constructor & Destructor Documentation
HtmlSpaceless() [1/2]
HtmlSpaceless::HtmlSpaceless () [inline]
Definition at line 8905 of file context.cpp.
{ reset(); }
References reset().
HtmlSpaceless() [2/2]
HtmlSpaceless::HtmlSpaceless () [inline]
Definition at line 8905 of file context.cpp.
{ reset(); }
Member Function Documentation
clone() [1/2]
std::unique_ptr< TemplateSpacelessIntf > HtmlSpaceless::clone () [inline], [virtual]
Create a copy of the spaceless filter
Implements TemplateSpacelessIntf.
Definition at line 8906 of file context.cpp.
    {
      return std::make_unique<HtmlSpaceless>(*this);
    }
clone() [2/2]
std::unique_ptr< TemplateSpacelessIntf > HtmlSpaceless::clone () [inline], [virtual]
Create a copy of the spaceless filter
Implements TemplateSpacelessIntf.
Definition at line 8906 of file context.cpp.
    {
      return std::make_unique<HtmlSpaceless>(*this);
    }
remove() [1/2]
QCString HtmlSpaceless::remove (const QCString & input) [inline], [virtual]
Returns the input after removing redundant whitespace
Implements TemplateSpacelessIntf.
Definition at line 8916 of file context.cpp.
    {
      if (s.isEmpty()) return s;
      TextStream result;
      const char *p = s.data();
      char c;
      while ((c=*p++))
      {
        switch(c)
        {
          case '<': // start of a tag
            if (!m_insideString) m_insideTag=TRUE,m_removeSpaces=FALSE;
            result << c;
            break;
          case '>': // end of a tag
            if (!m_insideString) m_insideTag=FALSE,m_removeSpaces=TRUE;
            result << c;
            break;
          case '\\': // escaped character in a string
            result << c;
            if (m_insideString && *p) result << *p++;
            break;
          case '"': case '\'':
            if (m_insideTag)
            {
              if (m_insideString==c) // end of string
              {
                m_insideString='\0';
              }
              else if (m_insideString=='\0') // start of string
              {
                m_insideString=c;
              }
            }
            result << c;
            break;
          case ' ': case '\t': case '\n': // whitespace
            if (!m_insideTag) // outside tags strip consecutive whitespace
            {
              m_removeSpaces=TRUE;
            }
            else
            {
              result << ' ';
            }
            break;
          default:
            //if (m_removeSpaces) result+=' ';
            result << c;
            m_removeSpaces=FALSE;
            break;
        }
      }
      //printf("HtmlSpaceless::remove({%s})={%s} m_insideTag=%d m_insideString=%c (%d) removeSpaces=%d\n",qPrint(s),qPrint(result),
      // m_insideTag,m_insideString,m_insideString,m_removeSpaces);
      return result.str();
    }
References c, gdFont::data, FALSE, m_insideString, m_insideTag, m_removeSpaces, p, s, TextStream::str(), and TRUE.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
remove() [2/2]
QCString HtmlSpaceless::remove (const QCString & input) [inline], [virtual]
Returns the input after removing redundant whitespace
Implements TemplateSpacelessIntf.
Definition at line 8916 of file context.cpp.
    {
      if (s.isEmpty()) return s;
      TextStream result;
      const char *p = s.data();
      char c;
      while ((c=*p++))
      {
        switch(c)
        {
          case '<': // start of a tag
            if (!m_insideString) m_insideTag=TRUE,m_removeSpaces=FALSE;
            result << c;
            break;
          case '>': // end of a tag
            if (!m_insideString) m_insideTag=FALSE,m_removeSpaces=TRUE;
            result << c;
            break;
          case '\\': // escaped character in a string
            result << c;
            if (m_insideString && *p) result << *p++;
            break;
          case '"': case '\'':
            if (m_insideTag)
            {
              if (m_insideString==c) // end of string
              {
                m_insideString='\0';
              }
              else if (m_insideString=='\0') // start of string
              {
                m_insideString=c;
              }
            }
            result << c;
            break;
          case ' ': case '\t': case '\n': // whitespace
            if (!m_insideTag) // outside tags strip consecutive whitespace
            {
              m_removeSpaces=TRUE;
            }
            else
            {
              result << ' ';
            }
            break;
          default:
            //if (m_removeSpaces) result+=' ';
            result << c;
            m_removeSpaces=FALSE;
            break;
        }
      }
      //printf("HtmlSpaceless::remove({%s})={%s} m_insideTag=%d m_insideString=%c (%d) removeSpaces=%d\n",qPrint(s),qPrint(result),
      // m_insideTag,m_insideString,m_insideString,m_removeSpaces);
      return result.str();
    }
References c, gdFont::data, FALSE, SearchIndicesContext::p, s, TextStream::str(), and TRUE.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
reset() [1/2]
void HtmlSpaceless::reset () [inline], [virtual]
Reset filter state
Implements TemplateSpacelessIntf.
Definition at line 8910 of file context.cpp.
    {
      m_insideTag = FALSE;
      m_insideString = '\0';
      m_removeSpaces = TRUE;
    }
References FALSE, m_insideString, m_insideTag, m_removeSpaces, and TRUE.
Referenced by HtmlSpaceless().
reset() [2/2]
void HtmlSpaceless::reset () [inline], [virtual]
Reset filter state
Implements TemplateSpacelessIntf.
Definition at line 8910 of file context.cpp.
    {
      m_insideTag = FALSE;
      m_insideString = '\0';
      m_removeSpaces = TRUE;
    }
References FALSE, and TRUE.
Member Data Documentation
m_insideString
char HtmlSpaceless::m_insideString [private]
Definition at line 8975 of file context.cpp.
Referenced by remove(), and reset().
m_insideTag
bool HtmlSpaceless::m_insideTag [private]
Definition at line 8974 of file context.cpp.
Referenced by remove(), and reset().
m_removeSpaces
bool HtmlSpaceless::m_removeSpaces [private]
Definition at line 8976 of file context.cpp.
Referenced by remove(), and reset().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp