TemplateStruct Class Reference
Default implementation of a context value of type struct.
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
virtual void set (const QCString &name, const TemplateVariant &v)
virtual void remove (const QCString &name)
TemplateStruct ()=default
virtual ~TemplateStruct ()=default
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
virtual void set (const QCString &name, const TemplateVariant &v)
virtual void remove (const QCString &name)
TemplateStruct ()=default
virtual ~TemplateStruct ()=default
Static Public Member Functions
static TemplateStructPtr alloc ()
static TemplateStructPtr alloc ()
Private Attributes
std::unordered_map< std::string, TemplateVariant > m_fields
Detailed Description
Default implementation of a context value of type struct.
Definition at line 150 of file template.cpp.
Constructor & Destructor Documentation
TemplateStruct() [1/2]
TemplateStruct::TemplateStruct () [default]
Creates a struct
 TemplateStruct() [1/2]
virtual TemplateStruct::~TemplateStruct () [virtual], [default]
Destroys the struct
TemplateStruct() [2/2]
TemplateStruct::TemplateStruct () [default]
Creates a struct
 TemplateStruct() [2/2]
virtual TemplateStruct::~TemplateStruct () [virtual], [default]
Destroys the struct
Member Function Documentation
alloc() [1/2]
TemplateStructPtr TemplateStruct::alloc () [static]
Creates an instance and returns a shared pointer to it
Definition at line 218 of file template.cpp.
{
  return std::make_shared<TemplateStruct>();
}
Referenced by TemplateContextImpl::addIndexEntry(), FilterAlphaIndex::apply(), TemplateNodeRepeat::render(), TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeBlock::render(), and TemplateNodeMarkers::render().
alloc() [2/2]
static TemplateStructPtr TemplateStruct::alloc () [static]
Creates an instance and returns a shared pointer to it
fields() [1/2]
StringVector TemplateStruct::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 207 of file template.cpp.
{
  StringVector result;
  for (const auto &kv : m_fields)
  {
    result.push_back(kv.first);
  }
  std::sort(result.begin(),result.end());
  return result;
}
References m_fields.
fields() [2/2]
virtual StringVector TemplateStruct::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant TemplateStruct::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 201 of file template.cpp.
{
  auto it = m_fields.find(name.str());
  return it!=m_fields.end() ? it->second : TemplateVariant();
}
References m_fields, and setup::name.
get() [2/2]
virtual TemplateVariant TemplateStruct::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
remove() [1/2]
void TemplateStruct::remove (const QCString & name) [virtual]
Removes the field from the struct
Definition at line 192 of file template.cpp.
{
  auto it = m_fields.find(name.str());
  if (it!=m_fields.end())
  {
    m_fields.erase(it);
  }
}
References m_fields, and setup::name.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
remove() [2/2]
virtual void TemplateStruct::remove (const QCString & name) [virtual]
Removes the field from the struct
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
set() [1/2]
void TemplateStruct::set (const QCString & name, const TemplateVariant & v) [virtual]
Sets the value the field of a struct
Parameters
 in name The name of the field.
 in v The value to set.
Definition at line 179 of file template.cpp.
{
  auto it = m_fields.find(name.str());
  if (it!=m_fields.end()) // change existing field
  {
    it->second = v;
  }
  else // insert new field
  {
    m_fields.insert(std::make_pair(name.str(),v));
  }
}
References m_fields, and setup::name.
set() [2/2]
virtual void TemplateStruct::set (const QCString & name, const TemplateVariant & v) [virtual]
Sets the value the field of a struct
Parameters
 in name The name of the field.
 in v The value to set.
Member Data Documentation
m_fields
std::unordered_map< std::string, TemplateVariant > TemplateStruct::m_fields [private]
Definition at line 176 of file template.cpp.
Referenced by fields(), get(), remove(), and set().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp