ghc::filesystem::recursive_directory_iterator Class Reference
#include <filesystem.hpp>
Classes
struct recursive_directory_iterator_impl
Public Types
using iterator_category = std::input_iterator_tag
using value_type = directory_entry
using difference_type = std::ptrdiff_t
using pointer = const directory_entry *
using reference = const directory_entry &
using iterator_category = std::input_iterator_tag
using value_type = directory_entry
using difference_type = std::ptrdiff_t
using pointer = const directory_entry *
using reference = const directory_entry &
Public Member Functions
recursive_directory_iterator () noexcept
recursive_directory_iterator (const path &p, directory_options options, std::error_code &ec) noexcept
recursive_directory_iterator (const path &p, std::error_code &ec) noexcept
recursive_directory_iterator (const recursive_directory_iterator &rhs)
recursive_directory_iterator (recursive_directory_iterator &&rhs) noexcept
~recursive_directory_iterator ()
directory_options options () const
int depth () const
bool recursion_pending () const
const directory_entry & operator* () const
const directory_entry * operator-> () const
recursive_directory_iterator & operator= (const recursive_directory_iterator &rhs)
recursive_directory_iterator & operator= (recursive_directory_iterator &&rhs) noexcept
recursive_directory_iterator & increment (std::error_code &ec) noexcept
void pop (std::error_code &ec)
void disable_recursion_pending ()
bool operator== (const recursive_directory_iterator &rhs) const
bool operator!= (const recursive_directory_iterator &rhs) const
recursive_directory_iterator () noexcept
recursive_directory_iterator (const path &p, directory_options options, std::error_code &ec) noexcept
recursive_directory_iterator (const path &p, std::error_code &ec) noexcept
recursive_directory_iterator (const recursive_directory_iterator &rhs)
recursive_directory_iterator (recursive_directory_iterator &&rhs) noexcept
~recursive_directory_iterator ()
directory_options options () const
int depth () const
bool recursion_pending () const
const directory_entry & operator* () const
const directory_entry * operator-> () const
recursive_directory_iterator & operator= (const recursive_directory_iterator &rhs)
recursive_directory_iterator & operator= (recursive_directory_iterator &&rhs) noexcept
recursive_directory_iterator & increment (std::error_code &ec) noexcept
void pop (std::error_code &ec)
void disable_recursion_pending ()
bool operator== (const recursive_directory_iterator &rhs) const
bool operator!= (const recursive_directory_iterator &rhs) const
Private Attributes
std::shared_ptr< recursive_directory_iterator_impl > _impl
Detailed Description
Definition at line 973 of file filesystem.hpp.
Member Typedef Documentation
difference_type [1/2]
using ghc::filesystem::recursive_directory_iterator::difference_type = std::ptrdiff_t
Definition at line 978 of file filesystem.hpp.
difference_type [2/2]
using ghc::filesystem::recursive_directory_iterator::difference_type = std::ptrdiff_t
Definition at line 978 of file filesystem.hpp.
iterator_category [1/2]
using ghc::filesystem::recursive_directory_iterator::iterator_category = std::input_iterator_tag
Definition at line 976 of file filesystem.hpp.
iterator_category [2/2]
using ghc::filesystem::recursive_directory_iterator::iterator_category = std::input_iterator_tag
Definition at line 976 of file filesystem.hpp.
pointer [1/2]
using ghc::filesystem::recursive_directory_iterator::pointer = const directory_entry*
Definition at line 979 of file filesystem.hpp.
pointer [2/2]
using ghc::filesystem::recursive_directory_iterator::pointer = const directory_entry*
Definition at line 979 of file filesystem.hpp.
reference [1/2]
using ghc::filesystem::recursive_directory_iterator::reference = const directory_entry&
Definition at line 980 of file filesystem.hpp.
reference [2/2]
using ghc::filesystem::recursive_directory_iterator::reference = const directory_entry&
Definition at line 980 of file filesystem.hpp.
value_type [1/2]
using ghc::filesystem::recursive_directory_iterator::value_type = directory_entry
Definition at line 977 of file filesystem.hpp.
value_type [2/2]
using ghc::filesystem::recursive_directory_iterator::value_type = directory_entry
Definition at line 977 of file filesystem.hpp.
Constructor & Destructor Documentation
recursive_directory_iterator() [1/10]
GHC_INLINE ghc::filesystem::recursive_directory_iterator::recursive_directory_iterator () [noexcept]
Definition at line 5762 of file filesystem.hpp.
    : _impl(new recursive_directory_iterator_impl(directory_options::none, true))
{
    _impl->_dir_iter_stack.push(directory_iterator());
}
References _impl.
Referenced by pop().
recursive_directory_iterator() [2/10]
GHC_INLINE ghc::filesystem::recursive_directory_iterator::recursive_directory_iterator (const path & p, directory_options options, std::error_code & ec) [noexcept]
Definition at line 5782 of file filesystem.hpp.
    : _impl(new recursive_directory_iterator_impl(options, true))
{
    _impl->_dir_iter_stack.push(directory_iterator(p, options, ec));
}
References p.
recursive_directory_iterator() [3/10]
GHC_INLINE ghc::filesystem::recursive_directory_iterator::recursive_directory_iterator (const path & p, std::error_code & ec) [noexcept]
Definition at line 5788 of file filesystem.hpp.
    : _impl(new recursive_directory_iterator_impl(directory_options::none, true))
{
    _impl->_dir_iter_stack.push(directory_iterator(p, ec));
}
References p.
recursive_directory_iterator() [4/10]
GHC_INLINE ghc::filesystem::recursive_directory_iterator::recursive_directory_iterator (const recursive_directory_iterator & rhs)
Definition at line 5794 of file filesystem.hpp.
    : _impl(rhs._impl)
{
}
recursive_directory_iterator() [5/10]
GHC_INLINE ghc::filesystem::recursive_directory_iterator::recursive_directory_iterator (recursive_directory_iterator && rhs) [noexcept]
Definition at line 5799 of file filesystem.hpp.
    : _impl(std::move(rhs._impl))
{
}
 recursive_directory_iterator() [1/2]
GHC_INLINE ghc::filesystem::recursive_directory_iterator::~recursive_directory_iterator ()
Definition at line 5804 of file filesystem.hpp.
{}
recursive_directory_iterator() [6/10]
ghc::filesystem::recursive_directory_iterator::recursive_directory_iterator () [noexcept]
recursive_directory_iterator() [7/10]
ghc::filesystem::recursive_directory_iterator::recursive_directory_iterator (const path & p, directory_options options, std::error_code & ec) [noexcept]
recursive_directory_iterator() [8/10]
ghc::filesystem::recursive_directory_iterator::recursive_directory_iterator (const path & p, std::error_code & ec) [noexcept]
recursive_directory_iterator() [9/10]
ghc::filesystem::recursive_directory_iterator::recursive_directory_iterator (const recursive_directory_iterator & rhs)
recursive_directory_iterator() [10/10]
ghc::filesystem::recursive_directory_iterator::recursive_directory_iterator (recursive_directory_iterator && rhs) [noexcept]
 recursive_directory_iterator() [2/2]
ghc::filesystem::recursive_directory_iterator::~recursive_directory_iterator ()
Member Function Documentation
depth() [1/2]
GHC_INLINE int ghc::filesystem::recursive_directory_iterator::depth () const
Definition at line 5812 of file filesystem.hpp.
{
    return static_cast<int>(_impl->_dir_iter_stack.size() - 1);
}
References _impl.
Referenced by pop().
depth() [2/2]
int ghc::filesystem::recursive_directory_iterator::depth () const
disable_recursion_pending() [1/2]
GHC_INLINE void ghc::filesystem::recursive_directory_iterator::disable_recursion_pending ()
Definition at line 5909 of file filesystem.hpp.
{
    _impl->_recursion_pending = false;
}
References _impl.
disable_recursion_pending() [2/2]
void ghc::filesystem::recursive_directory_iterator::disable_recursion_pending ()
increment() [1/2]
GHC_INLINE recursive_directory_iterator & ghc::filesystem::recursive_directory_iterator::increment (std::error_code & ec) [noexcept]
Definition at line 5857 of file filesystem.hpp.
{
    bool isSymLink = (*this)->is_symlink(ec);
    bool isDir = !ec && (*this)->is_directory(ec);
    if(isSymLink && detail::is_not_found_error(ec)) {
        ec.clear();
    }
    if(!ec) {
        if (recursion_pending() && isDir && (!isSymLink || (options() & directory_options::follow_directory_symlink) != directory_options::none)) {
            _impl->_dir_iter_stack.push(directory_iterator((*this)->path(), _impl->_options, ec));
        }
        else {
            _impl->_dir_iter_stack.top().increment(ec);
        }
        if (!ec) {
            while (depth() && _impl->_dir_iter_stack.top() == directory_iterator()) {
                _impl->_dir_iter_stack.pop();
                _impl->_dir_iter_stack.top().increment(ec);
            }
        }
        else if (!_impl->_dir_iter_stack.empty()) {
            _impl->_dir_iter_stack.pop();
        }
        _impl->_recursion_pending = true;
    }
    return *this;
}
References ghc::filesystem::follow_directory_symlink, ghc::filesystem::detail::is_not_found_error(), ghc::filesystem::directory_entry::is_symlink(), and ghc::filesystem::none.
increment() [2/2]
recursive_directory_iterator & ghc::filesystem::recursive_directory_iterator::increment (std::error_code & ec) [noexcept]
operator!=() [1/2]
GHC_INLINE bool ghc::filesystem::recursive_directory_iterator::operator!= (const recursive_directory_iterator & rhs) const
Definition at line 5920 of file filesystem.hpp.
{
    return _impl->_dir_iter_stack.top() != rhs._impl->_dir_iter_stack.top();
}
References _impl.
operator!=() [2/2]
bool ghc::filesystem::recursive_directory_iterator::operator!= (const recursive_directory_iterator & rhs) const
operator*() [1/2]
GHC_INLINE const directory_entry & ghc::filesystem::recursive_directory_iterator::operator* () const
Definition at line 5822 of file filesystem.hpp.
{
    return *(_impl->_dir_iter_stack.top());
}
References _impl.
operator*() [2/2]
const directory_entry & ghc::filesystem::recursive_directory_iterator::operator* () const
operator->() [1/2]
GHC_INLINE const directory_entry * ghc::filesystem::recursive_directory_iterator::operator-> () const
Definition at line 5827 of file filesystem.hpp.
{
    return &(*(_impl->_dir_iter_stack.top()));
}
References _impl.
operator->() [2/2]
const directory_entry * ghc::filesystem::recursive_directory_iterator::operator-> () const
operator=() [1/4]
GHC_INLINE recursive_directory_iterator & ghc::filesystem::recursive_directory_iterator::operator= (const recursive_directory_iterator & rhs)
Definition at line 5833 of file filesystem.hpp.
{
    _impl = rhs._impl;
    return *this;
}
References _impl.
operator=() [2/4]
recursive_directory_iterator & ghc::filesystem::recursive_directory_iterator::operator= (const recursive_directory_iterator & rhs)
operator=() [3/4]
GHC_INLINE recursive_directory_iterator & ghc::filesystem::recursive_directory_iterator::operator= (recursive_directory_iterator && rhs) [noexcept]
Definition at line 5839 of file filesystem.hpp.
{
    _impl = std::move(rhs._impl);
    return *this;
}
operator=() [4/4]
recursive_directory_iterator & ghc::filesystem::recursive_directory_iterator::operator= (recursive_directory_iterator && rhs) [noexcept]
operator==() [1/2]
GHC_INLINE bool ghc::filesystem::recursive_directory_iterator::operator== (const recursive_directory_iterator & rhs) const
Definition at line 5915 of file filesystem.hpp.
{
    return _impl->_dir_iter_stack.top() == rhs._impl->_dir_iter_stack.top();
}
References _impl.
operator==() [2/2]
bool ghc::filesystem::recursive_directory_iterator::operator== (const recursive_directory_iterator & rhs) const
options() [1/2]
GHC_INLINE directory_options ghc::filesystem::recursive_directory_iterator::options () const
Definition at line 5807 of file filesystem.hpp.
{
    return _impl->_options;
}
References _impl.
options() [2/2]
directory_options ghc::filesystem::recursive_directory_iterator::options () const
pop() [1/2]
GHC_INLINE void ghc::filesystem::recursive_directory_iterator::pop (std::error_code & ec)
Definition at line 5896 of file filesystem.hpp.
{
    if (depth() == 0) {
        *this = recursive_directory_iterator();
    }
    else {
        do {
            _impl->_dir_iter_stack.pop();
            _impl->_dir_iter_stack.top().increment(ec);
        } while (depth() && _impl->_dir_iter_stack.top() == directory_iterator());
    }
}
References _impl, depth(), and recursive_directory_iterator().
pop() [2/2]
void ghc::filesystem::recursive_directory_iterator::pop (std::error_code & ec)
recursion_pending() [1/2]
GHC_INLINE bool ghc::filesystem::recursive_directory_iterator::recursion_pending () const
Definition at line 5817 of file filesystem.hpp.
{
    return _impl->_recursion_pending;
}
References _impl.
recursion_pending() [2/2]
bool ghc::filesystem::recursive_directory_iterator::recursion_pending () const
Member Data Documentation
_impl
std::shared_ptr< recursive_directory_iterator_impl > ghc::filesystem::recursive_directory_iterator::_impl [private]
Definition at line 1040 of file filesystem.hpp.
Referenced by depth(), disable_recursion_pending(), operator!=(), operator*(), operator->(), operator=(), operator==(), options(), pop(), recursion_pending(), and recursive_directory_iterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/filesystem/filesystem.hpp
doxygen/filesystem/filesystem.hpp