PageListContext::Private Class Reference
Public Member Functions
void addPages (const PageLinkedMap &pages)
void addPages (const PageLinkedMap &pages)
Additional Inherited Members
Detailed Description
Definition at line 6635 of file context.cpp.
Member Function Documentation
addPages() [1/2]
void PageListContext::Private::addPages (const PageLinkedMap & pages) [inline]
Definition at line 6638 of file context.cpp.
    {
      for (const auto &pd : pages)
      {
        if (!pd->getGroupDef() && !pd->isReference())
        {
          append(PageContext::alloc(pd.get(),FALSE,FALSE));
        }
      }
    }
References PageContext::alloc(), GenericNodeListContext::append(), and FALSE.
addPages() [2/2]
void PageListContext::Private::addPages (const PageLinkedMap & pages) [inline]
Definition at line 6638 of file context.cpp.
    {
      for (const auto &pd : pages)
      {
        if (!pd->getGroupDef() && !pd->isReference())
        {
          append(PageContext::alloc(pd.get(),FALSE,FALSE));
        }
      }
    }
References PageContext::alloc(), and FALSE.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp