TextGeneratorLatex Class Reference
Public Member Functions
TextGeneratorLatex (TextStream &ts)
void writeString (const QCString &s, bool keepSpaces) const
void writeBreak (int indent) const
void writeLink (const QCString &ref, const QCString &f, const QCString &anchor, const QCString &text) const
TextGeneratorLatex (TextStream &ts)
void writeString (const QCString &s, bool keepSpaces) const
void writeBreak (int indent) const
void writeLink (const QCString &ref, const QCString &f, const QCString &anchor, const QCString &text) const
Private Attributes
TextStream & m_ts
Detailed Description
Definition at line 3474 of file context.cpp.
Constructor & Destructor Documentation
TextGeneratorLatex() [1/2]
TextGeneratorLatex::TextGeneratorLatex (TextStream & ts) [inline]
Definition at line 3477 of file context.cpp.
: m_ts(ts) {}
TextGeneratorLatex() [2/2]
TextGeneratorLatex::TextGeneratorLatex (TextStream & ts) [inline]
Definition at line 3477 of file context.cpp.
: m_ts(ts) {}
Member Function Documentation
writeBreak() [1/2]
void TextGeneratorLatex::writeBreak (int indent) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 3483 of file context.cpp.
    {
      m_ts << "\\\\*\n";
      for (int i=0;i<indent;i++)
      {
        m_ts << "~";
      }
    }
References m_ts.
writeBreak() [2/2]
void TextGeneratorLatex::writeBreak (int indent) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 3483 of file context.cpp.
    {
      m_ts << "\\\\*\n";
      for (int i=0;i<indent;i++)
      {
        m_ts << "~";
      }
    }
writeLink() [1/2]
void TextGeneratorLatex::writeLink (const QCString & ref, const QCString & f, const QCString & anchor, const QCString & text) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 3491 of file context.cpp.
    {
      bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
      if (ref.isEmpty() && pdfHyperlinks)
      {
        m_ts << "\\mbox{\\hyperlink{";
        if (!f.isEmpty()) m_ts << stripPath(f);
        if (!f.isEmpty() && !anchor.isEmpty()) m_ts << "_";
        if (!anchor.isEmpty()) m_ts << anchor;
        m_ts << "}{";
        filterLatexString(m_ts,text,
                          false, // insideTabbing
                          false, // insidePre
                          false, // insideItem
                          false, // insideTable
                          false // keepSpaces
                         );
        m_ts << "}}";
      }
      else
      {
        m_ts << "\\textbf{ ";
        filterLatexString(m_ts,text,
                          false, // insideTabbing
                          false, // insidePre
                          false, // insideItem
                          false, // insideTable
                          false // keepSpaces
                         );
        m_ts << "}";
      }
    }
References Config_getBool, f, filterLatexString(), QCString::isEmpty(), m_ts, and stripPath().
writeLink() [2/2]
void TextGeneratorLatex::writeLink (const QCString & ref, const QCString & f, const QCString & anchor, const QCString & text) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 3491 of file context.cpp.
    {
      bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
      if (ref.isEmpty() && pdfHyperlinks)
      {
        m_ts << "\\mbox{\\hyperlink{";
        if (!f.isEmpty()) m_ts << stripPath(f);
        if (!f.isEmpty() && !anchor.isEmpty()) m_ts << "_";
        if (!anchor.isEmpty()) m_ts << anchor;
        m_ts << "}{";
        filterLatexString(m_ts,text,
                          false, // insideTabbing
                          false, // insidePre
                          false, // insideItem
                          false, // insideTable
                          false // keepSpaces
                         );
        m_ts << "}}";
      }
      else
      {
        m_ts << "\\textbf{ ";
        filterLatexString(m_ts,text,
                          false, // insideTabbing
                          false, // insidePre
                          false, // insideItem
                          false, // insideTable
                          false // keepSpaces
                         );
        m_ts << "}";
      }
    }
References Config_getBool, f, filterLatexString(), QCString::isEmpty(), and stripPath().
writeString() [1/2]
void TextGeneratorLatex::writeString (const QCString & s, bool keepSpaces) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 3478 of file context.cpp.
    {
      if (s==0) return;
      m_ts << convertToLaTeX(s,FALSE,keepSpaces);
    }
References convertToLaTeX(), FALSE, m_ts, and s.
writeString() [2/2]
void TextGeneratorLatex::writeString (const QCString & s, bool keepSpaces) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 3478 of file context.cpp.
    {
      if (s==0) return;
      m_ts << convertToLaTeX(s,FALSE,keepSpaces);
    }
References convertToLaTeX(), FALSE, and s.
Member Data Documentation
m_ts
TextStream & TextGeneratorLatex::m_ts [private]
Definition at line 3527 of file context.cpp.
Referenced by writeBreak(), writeLink(), and writeString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp