LatexSpaceless Class Reference
Public Member Functions
LatexSpaceless ()
std::unique_ptr< TemplateSpacelessIntf > clone ()
void reset ()
QCString remove (const QCString &s)
LatexSpaceless ()
std::unique_ptr< TemplateSpacelessIntf > clone ()
void reset ()
QCString remove (const QCString &s)
Detailed Description
Definition at line 8869 of file context.cpp.
Constructor & Destructor Documentation
LatexSpaceless() [1/2]
LatexSpaceless::LatexSpaceless () [inline]
Definition at line 8872 of file context.cpp.
{ reset(); }
References reset().
LatexSpaceless() [2/2]
LatexSpaceless::LatexSpaceless () [inline]
Definition at line 8872 of file context.cpp.
{ reset(); }
Member Function Documentation
clone() [1/2]
std::unique_ptr< TemplateSpacelessIntf > LatexSpaceless::clone () [inline], [virtual]
Create a copy of the spaceless filter
Implements TemplateSpacelessIntf.
Definition at line 8873 of file context.cpp.
    {
      return std::make_unique<LatexSpaceless>(*this);
    }
clone() [2/2]
std::unique_ptr< TemplateSpacelessIntf > LatexSpaceless::clone () [inline], [virtual]
Create a copy of the spaceless filter
Implements TemplateSpacelessIntf.
Definition at line 8873 of file context.cpp.
    {
      return std::make_unique<LatexSpaceless>(*this);
    }
remove() [1/2]
QCString LatexSpaceless::remove (const QCString & input) [inline], [virtual]
Returns the input after removing redundant whitespace
Implements TemplateSpacelessIntf.
Definition at line 8878 of file context.cpp.
    {
      if (s.isEmpty()) return s;
      TextStream result;
      const char *p = s.data();
      char c;
      while ((c=*p++))
      {
        switch(c)
        {
          case '\t': case ' ': case '\n':
            break;
          default:
            result << c;
            break;
        }
      }
      return result.str();
    }
References c, gdFont::data, p, s, and TextStream::str().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
remove() [2/2]
QCString LatexSpaceless::remove (const QCString & input) [inline], [virtual]
Returns the input after removing redundant whitespace
Implements TemplateSpacelessIntf.
Definition at line 8878 of file context.cpp.
    {
      if (s.isEmpty()) return s;
      TextStream result;
      const char *p = s.data();
      char c;
      while ((c=*p++))
      {
        switch(c)
        {
          case '\t': case ' ': case '\n':
            break;
          default:
            result << c;
            break;
        }
      }
      return result.str();
    }
References c, gdFont::data, SearchIndicesContext::p, s, and TextStream::str().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
reset() [1/2]
void LatexSpaceless::reset () [inline], [virtual]
Reset filter state
Implements TemplateSpacelessIntf.
Definition at line 8877 of file context.cpp.
{ }
Referenced by LatexSpaceless().
reset() [2/2]
void LatexSpaceless::reset () [inline], [virtual]
Reset filter state
Implements TemplateSpacelessIntf.
Definition at line 8877 of file context.cpp.
{ }
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp