TranslatorSlovene Class Reference
#include <translator_si.h>
Public Member Functions
QCString idLanguage ()
QCString latexLanguageSupportCommand ()
QCString trISOLang ()
virtual QCString getLanguageString ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const QCString &s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const QCString &date, const QCString &projName)
QCString trClassDiagram (const QCString &clName)
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
QCString trNamespaceList ()
QCString trNamespaceListDescription (bool extractAll)
QCString trFriends ()
QCString trRelatedFunctionDocumentation ()
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool)
QCString trFileReference (const QCString &fileName)
QCString trNamespaceReference (const QCString &namespaceName)
QCString trPublicMembers ()
QCString trPublicSlots ()
QCString trSignals ()
QCString trStaticPublicMembers ()
QCString trProtectedMembers ()
QCString trProtectedSlots ()
QCString trStaticProtectedMembers ()
QCString trPrivateMembers ()
QCString trPrivateSlots ()
QCString trStaticPrivateMembers ()
QCString trWriteList (int numEntries)
QCString trInheritsList (int numEntries)
QCString trInheritedByList (int numEntries)
QCString trReimplementedFromList (int numEntries)
QCString trReimplementedInList (int numEntries)
QCString trNamespaceMembers ()
QCString trNamespaceMemberDescription (bool extractAll)
QCString trNamespaceIndex ()
QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
QCString trReturnValues ()
QCString trMainPage ()
QCString trPageAbbreviation ()
QCString trDefinedAtLineInSourceFile ()
QCString trDefinedInSourceFile ()
QCString trDeprecated ()
QCString trCollaborationDiagram (const QCString &clName)
QCString trInclDepGraph (const QCString &fName)
QCString trConstructorDocumentation ()
QCString trGotoSourceCode ()
QCString trGotoDocumentation ()
QCString trPrecondition ()
QCString trPostcondition ()
QCString trInvariant ()
QCString trInitialValue ()
QCString trCode ()
QCString trGraphicalHierarchy ()
QCString trGotoGraphicalHierarchy ()
QCString trGotoTextualHierarchy ()
QCString trPageIndex ()
QCString trNote ()
QCString trPublicTypes ()
QCString trPublicAttribs ()
QCString trStaticPublicAttribs ()
QCString trProtectedTypes ()
QCString trProtectedAttribs ()
QCString trStaticProtectedAttribs ()
QCString trPrivateTypes ()
QCString trPrivateAttribs ()
QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
QCString idLanguage ()
QCString latexLanguageSupportCommand ()
QCString trISOLang ()
virtual QCString getLanguageString ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const QCString &s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const QCString &date, const QCString &projName)
QCString trClassDiagram (const QCString &clName)
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
QCString trNamespaceList ()
QCString trNamespaceListDescription (bool extractAll)
QCString trFriends ()
QCString trRelatedFunctionDocumentation ()
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool)
QCString trFileReference (const QCString &fileName)
QCString trNamespaceReference (const QCString &namespaceName)
QCString trPublicMembers ()
QCString trPublicSlots ()
QCString trSignals ()
QCString trStaticPublicMembers ()
QCString trProtectedMembers ()
QCString trProtectedSlots ()
QCString trStaticProtectedMembers ()
QCString trPrivateMembers ()
QCString trPrivateSlots ()
QCString trStaticPrivateMembers ()
QCString trWriteList (int numEntries)
QCString trInheritsList (int numEntries)
QCString trInheritedByList (int numEntries)
QCString trReimplementedFromList (int numEntries)
QCString trReimplementedInList (int numEntries)
QCString trNamespaceMembers ()
QCString trNamespaceMemberDescription (bool extractAll)
QCString trNamespaceIndex ()
QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
QCString trReturnValues ()
QCString trMainPage ()
QCString trPageAbbreviation ()
QCString trDefinedAtLineInSourceFile ()
QCString trDefinedInSourceFile ()
QCString trDeprecated ()
QCString trCollaborationDiagram (const QCString &clName)
QCString trInclDepGraph (const QCString &fName)
QCString trConstructorDocumentation ()
QCString trGotoSourceCode ()
QCString trGotoDocumentation ()
QCString trPrecondition ()
QCString trPostcondition ()
QCString trInvariant ()
QCString trInitialValue ()
QCString trCode ()
QCString trGraphicalHierarchy ()
QCString trGotoGraphicalHierarchy ()
QCString trGotoTextualHierarchy ()
QCString trPageIndex ()
QCString trNote ()
QCString trPublicTypes ()
QCString trPublicAttribs ()
QCString trStaticPublicAttribs ()
QCString trProtectedTypes ()
QCString trProtectedAttribs ()
QCString trStaticProtectedAttribs ()
QCString trPrivateTypes ()
QCString trPrivateAttribs ()
QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
Additional Inherited Members
Detailed Description
Definition at line 24 of file translator_si.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorSlovene::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 38 of file translator_si.h.
    {
      return "0x424 Slovenian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorSlovene::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 38 of file translator_si.h.
    {
      return "0x424 Slovenian";
    }
idLanguage() [1/2]
QCString TranslatorSlovene::idLanguage () [inline], [virtual]
Implements Translator.
Definition at line 27 of file translator_si.h.
    { return "slovene"; }
idLanguage() [2/2]
QCString TranslatorSlovene::idLanguage () [inline], [virtual]
Implements Translator.
Definition at line 27 of file translator_si.h.
    { return "slovene"; }
latexLanguageSupportCommand() [1/2]
QCString TranslatorSlovene::latexLanguageSupportCommand () [inline], [virtual]
Used to get the command(s) for the language support. This method was designed for languages which do not prefer babel package. If this methods returns empty string, then the latexBabelPackage() method is used to generate the command for using the babel package.
Implements Translator.
Definition at line 34 of file translator_si.h.
    { return "\\usepackage[slovene]{babel}\n"; }
latexLanguageSupportCommand() [2/2]
QCString TranslatorSlovene::latexLanguageSupportCommand () [inline], [virtual]
Used to get the command(s) for the language support. This method was designed for languages which do not prefer babel package. If this methods returns empty string, then the latexBabelPackage() method is used to generate the command for using the babel package.
Implements Translator.
Definition at line 34 of file translator_si.h.
    { return "\\usepackage[slovene]{babel}\n"; }
trAll() [1/2]
virtual QCString TranslatorSlovene::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1043 of file translator_si.h.
    {
      return "Vse";
    }
trAll() [2/2]
virtual QCString TranslatorSlovene::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1043 of file translator_si.h.
    {
      return "Vse";
    }
trAttention() [1/2]
virtual QCString TranslatorSlovene::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 598 of file translator_si.h.
    {
      return "Pozor";
    }
trAttention() [2/2]
virtual QCString TranslatorSlovene::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 598 of file translator_si.h.
    {
      return "Pozor";
    }
trAuthor() [1/2]
virtual QCString TranslatorSlovene::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 916 of file translator_si.h.
    {
      QCString result((first_capital ? "Avtor" : "avtor"));
      if (!singular) result+="ji";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorSlovene::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 916 of file translator_si.h.
    {
      QCString result((first_capital ? "Avtor" : "avtor"));
      if (!singular) result+="ji";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorSlovene::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 773 of file translator_si.h.
    {
      return "Programska napaka";
    }
trBug() [2/2]
virtual QCString TranslatorSlovene::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 773 of file translator_si.h.
    {
      return "Programska napaka";
    }
trBugList() [1/2]
virtual QCString TranslatorSlovene::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 778 of file translator_si.h.
    {
      return "Seznam programskih napak";
    }
trBugList() [2/2]
virtual QCString TranslatorSlovene::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 778 of file translator_si.h.
    {
      return "Seznam programskih napak";
    }
trCallGraph() [1/2]
virtual QCString TranslatorSlovene::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1048 of file translator_si.h.
    {
      return "Graf klicev tekoe funkcije:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorSlovene::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1048 of file translator_si.h.
    {
      return "Graf klicev tekoe funkcije:";
    }
trClass() [1/2]
virtual QCString TranslatorSlovene::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 836 of file translator_si.h.
    {
      QCString result((first_capital ? "Razred" : "razred"));
      if (!singular) result+="i";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorSlovene::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 836 of file translator_si.h.
    {
      QCString result((first_capital ? "Razred" : "razred"));
      if (!singular) result+="i";
      return result;
    }
trClassDiagram() [1/2]
QCString TranslatorSlovene::trClassDiagram (const QCString & clName) [inline], [virtual]
Implements Translator.
Definition at line 188 of file translator_si.h.
    {
      return "Diagram razredov za "+clName;
    }
trClassDiagram() [2/2]
QCString TranslatorSlovene::trClassDiagram (const QCString & clName) [inline], [virtual]
Implements Translator.
Definition at line 188 of file translator_si.h.
    {
      return "Diagram razredov za "+clName;
    }
trClassDocumentation() [1/2]
QCString TranslatorSlovene::trClassDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 148 of file translator_si.h.
    { return "Opis razreda"; }
trClassDocumentation() [2/2]
QCString TranslatorSlovene::trClassDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 148 of file translator_si.h.
    { return "Opis razreda"; }
trClasses() [1/2]
virtual QCString TranslatorSlovene::trClasses () [inline], [virtual]
Used for Java interfaces in the summary section of Java packages
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 736 of file translator_si.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Podatkovne strukture";
      }
      else
      {
        return "Razredi";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorSlovene::trClasses () [inline], [virtual]
Used for Java interfaces in the summary section of Java packages
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 736 of file translator_si.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Podatkovne strukture";
      }
      else
      {
        return "Razredi";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
QCString TranslatorSlovene::trClassHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 82 of file translator_si.h.
    { return "dedovalna hierarhija"; }
trClassHierarchy() [2/2]
QCString TranslatorSlovene::trClassHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 82 of file translator_si.h.
    { return "dedovalna hierarhija"; }
trClassHierarchyDescription() [1/2]
QCString TranslatorSlovene::trClassHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 98 of file translator_si.h.
      { return "Hierarhino drevo je (okvirno) sortirano po abecedi. ";
    }
trClassHierarchyDescription() [2/2]
QCString TranslatorSlovene::trClassHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 98 of file translator_si.h.
      { return "Hierarhino drevo je (okvirno) sortirano po abecedi. ";
    }
trCode() [1/2]
QCString TranslatorSlovene::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 506 of file translator_si.h.
    {
      return "koda";
    }
trCode() [2/2]
QCString TranslatorSlovene::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 506 of file translator_si.h.
    {
      return "koda";
    }
trCollaborationDiagram() [1/2]
QCString TranslatorSlovene::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 455 of file translator_si.h.
    {
      return "Kolaboracijski diagram razreda "+clName+":";
    }
trCollaborationDiagram() [2/2]
QCString TranslatorSlovene::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 455 of file translator_si.h.
    {
      return "Kolaboracijski diagram razreda "+clName+":";
    }
trCompoundIndex() [1/2]
QCString TranslatorSlovene::trCompoundIndex () [inline], [virtual]
Implements Translator.
Definition at line 142 of file translator_si.h.
    { return "abecedni seznam"; }
trCompoundIndex() [2/2]
QCString TranslatorSlovene::trCompoundIndex () [inline], [virtual]
Implements Translator.
Definition at line 142 of file translator_si.h.
    { return "abecedni seznam"; }
trCompoundList() [1/2]
QCString TranslatorSlovene::trCompoundList () [inline], [virtual]
Implements Translator.
Definition at line 84 of file translator_si.h.
    { return "kratek opis razredov"; }
trCompoundList() [2/2]
QCString TranslatorSlovene::trCompoundList () [inline], [virtual]
Implements Translator.
Definition at line 84 of file translator_si.h.
    { return "kratek opis razredov"; }
trCompoundListDescription() [1/2]
QCString TranslatorSlovene::trCompoundListDescription () [inline], [virtual]
Implements Translator.
Definition at line 108 of file translator_si.h.
    { return "Seznam razredov, mnoic in struktur "
             "s kratkim opisom :";
    }
trCompoundListDescription() [2/2]
QCString TranslatorSlovene::trCompoundListDescription () [inline], [virtual]
Implements Translator.
Definition at line 108 of file translator_si.h.
    { return "Seznam razredov, mnoic in struktur "
             "s kratkim opisom :";
    }
trCompoundMembers() [1/2]
QCString TranslatorSlovene::trCompoundMembers () [inline], [virtual]
Implements Translator.
Definition at line 88 of file translator_si.h.
    { return "metode in atributi"; }
trCompoundMembers() [2/2]
QCString TranslatorSlovene::trCompoundMembers () [inline], [virtual]
Implements Translator.
Definition at line 88 of file translator_si.h.
    { return "metode in atributi"; }
trCompoundMembersDescription() [1/2]
QCString TranslatorSlovene::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 112 of file translator_si.h.
    {
      QCString result="Seznam vseh ";
      if (!extractAll) result+="dokumentiranih ";
      result+="metod in atributov s povezavami na ";
      if (extractAll) result+="opis posamezne metode in/ali atributa:";
      else result+="opis razreda :";
      return result;
    }
trCompoundMembersDescription() [2/2]
QCString TranslatorSlovene::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 112 of file translator_si.h.
    {
      QCString result="Seznam vseh ";
      if (!extractAll) result+="dokumentiranih ";
      result+="metod in atributov s povezavami na ";
      if (extractAll) result+="opis posamezne metode in/ali atributa:";
      else result+="opis razreda :";
      return result;
    }
trCompoundReference() [1/2]
QCString TranslatorSlovene::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool) [inline], [virtual]
Implements Translator.
Definition at line 236 of file translator_si.h.
    {
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=" Razred "; break;
        case ClassDef::Struct: result+=" Struktura "; break;
        case ClassDef::Union: result+=" Mnoica "; break;
        case ClassDef::Interface: result+=" IDL vmesnik "; break;
        case ClassDef::Protocol: result+=" protocol "; break; // translate me!
        case ClassDef::Category: result+=" category "; break; // translate me!
        case ClassDef::Exception: result+=" IDL prekinitev "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
QCString TranslatorSlovene::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool) [inline], [virtual]
Implements Translator.
Definition at line 236 of file translator_si.h.
    {
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=" Razred "; break;
        case ClassDef::Struct: result+=" Struktura "; break;
        case ClassDef::Union: result+=" Mnoica "; break;
        case ClassDef::Interface: result+=" IDL vmesnik "; break;
        case ClassDef::Protocol: result+=" protocol "; break; // translate me!
        case ClassDef::Category: result+=" category "; break; // translate me!
        case ClassDef::Exception: result+=" IDL prekinitev "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
QCString TranslatorSlovene::trCompounds () [inline], [virtual]
Implements Translator.
Definition at line 179 of file translator_si.h.
    { return "Strukture"; }
trCompounds() [2/2]
QCString TranslatorSlovene::trCompounds () [inline], [virtual]
Implements Translator.
Definition at line 179 of file translator_si.h.
    { return "Strukture"; }
trConstructorDocumentation() [1/2]
QCString TranslatorSlovene::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 471 of file translator_si.h.
    {
      return "Opis konstruktorjev in destruktorjev ";
    }
trConstructorDocumentation() [2/2]
QCString TranslatorSlovene::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 471 of file translator_si.h.
    {
      return "Opis konstruktorjev in destruktorjev ";
    }
trDate() [1/2]
QCString TranslatorSlovene::trDate () [inline], [virtual]
Implements Translator.
Definition at line 196 of file translator_si.h.
    { return "Datum"; }
trDate() [2/2]
QCString TranslatorSlovene::trDate () [inline], [virtual]
Implements Translator.
Definition at line 196 of file translator_si.h.
    { return "Datum"; }
trDayOfWeek() [1/2]
virtual QCString TranslatorSlovene::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1166 of file translator_si.h.
    {
      static const char *days_short[] = { "pon.", "tor.", "sre.", "et.", "pet.", "sob.", "ned." };
      static const char *days_full[] = { "ponedeljek", "torek", "sreda", "etrtek", "petek", "sobota", "nedelja" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorSlovene::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1166 of file translator_si.h.
    {
      static const char *days_short[] = { "pon.", "tor.", "sre.", "et.", "pet.", "sob.", "ned." };
      static const char *days_full[] = { "ponedeljek", "torek", "sreda", "etrtek", "petek", "sobota", "nedelja" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorSlovene::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1182 of file translator_si.h.
    {
      static const char *dayPeriod[] = { "dop.", "pop." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorSlovene::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1182 of file translator_si.h.
    {
      static const char *dayPeriod[] = { "dop.", "pop." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
QCString TranslatorSlovene::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 432 of file translator_si.h.
    {
      return "Definirano v @0 vrstici datoteke @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
QCString TranslatorSlovene::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 432 of file translator_si.h.
    {
      return "Definirano v @0 vrstici datoteke @1.";
    }
trDefinedIn() [1/2]
QCString TranslatorSlovene::trDefinedIn () [inline], [virtual]
Implements Translator.
Definition at line 78 of file translator_si.h.
    { return "definirano v"; }
trDefinedIn() [2/2]
QCString TranslatorSlovene::trDefinedIn () [inline], [virtual]
Implements Translator.
Definition at line 78 of file translator_si.h.
    { return "definirano v"; }
trDefinedInSourceFile() [1/2]
QCString TranslatorSlovene::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 436 of file translator_si.h.
    {
      return "Definirano v datoteki @0.";
    }
trDefinedInSourceFile() [2/2]
QCString TranslatorSlovene::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 436 of file translator_si.h.
    {
      return "Definirano v datoteki @0.";
    }
trDefineDocumentation() [1/2]
QCString TranslatorSlovene::trDefineDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 169 of file translator_si.h.
    { return "Opis makro definicije"; }
trDefineDocumentation() [2/2]
QCString TranslatorSlovene::trDefineDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 169 of file translator_si.h.
    { return "Opis makro definicije"; }
trDefines() [1/2]
QCString TranslatorSlovene::trDefines () [inline], [virtual]
Implements Translator.
Definition at line 157 of file translator_si.h.
    { return "Makro deklaracije"; }
trDefines() [2/2]
QCString TranslatorSlovene::trDefines () [inline], [virtual]
Implements Translator.
Definition at line 157 of file translator_si.h.
    { return "Makro deklaracije"; }
trDefineValue() [1/2]
virtual QCString TranslatorSlovene::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 763 of file translator_si.h.
    {
      return "Vrednost:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorSlovene::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 763 of file translator_si.h.
    {
      return "Vrednost:";
    }
trDeprecated() [1/2]
QCString TranslatorSlovene::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 445 of file translator_si.h.
    {
      return "Zastarelo";
    }
trDeprecated() [2/2]
QCString TranslatorSlovene::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 445 of file translator_si.h.
    {
      return "Zastarelo";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorSlovene::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 971 of file translator_si.h.
    {
      return "Seznam opuenih";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorSlovene::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 971 of file translator_si.h.
    {
      return "Seznam opuenih";
    }
trDetailedDescription() [1/2]
QCString TranslatorSlovene::trDetailedDescription () [inline], [virtual]
Implements Translator.
Definition at line 46 of file translator_si.h.
    { return "Podroben opis"; }
trDetailedDescription() [2/2]
QCString TranslatorSlovene::trDetailedDescription () [inline], [virtual]
Implements Translator.
Definition at line 46 of file translator_si.h.
    { return "Podroben opis"; }
trDir() [1/2]
virtual QCString TranslatorSlovene::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1145 of file translator_si.h.
    {
      QCString result((first_capital ? "Imenik" : "imenik"));
      if (singular) result+="i"; else result+="";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorSlovene::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1145 of file translator_si.h.
    {
      QCString result((first_capital ? "Imenik" : "imenik"));
      if (singular) result+="i"; else result+="";
      return result;
    }
trDirDocumentation() [1/2]
virtual QCString TranslatorSlovene::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1124 of file translator_si.h.
    { return "Opisi imenikov"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorSlovene::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1124 of file translator_si.h.
    { return "Opisi imenikov"; }
trDirectories() [1/2]
virtual QCString TranslatorSlovene::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1130 of file translator_si.h.
    { return "Imeniki"; }
trDirectories() [2/2]
virtual QCString TranslatorSlovene::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1130 of file translator_si.h.
    { return "Imeniki"; }
trDirIndex() [1/2]
virtual QCString TranslatorSlovene::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1118 of file translator_si.h.
    { return "Hierarhija imenikov"; }
trDirIndex() [2/2]
virtual QCString TranslatorSlovene::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1118 of file translator_si.h.
    { return "Hierarhija imenikov"; }
trDirReference() [1/2]
virtual QCString TranslatorSlovene::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1136 of file translator_si.h.
    { QCString result=dirName;
      result+=" imenike reference"; /* not sure for context */
      return result;
    }
trDirReference() [2/2]
virtual QCString TranslatorSlovene::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1136 of file translator_si.h.
    { QCString result=dirName;
      result+=" imenike reference"; /* not sure for context */
      return result;
    }
trDocumentation() [1/2]
QCString TranslatorSlovene::trDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 136 of file translator_si.h.
    { return "Dokumentacija"; }
trDocumentation() [2/2]
QCString TranslatorSlovene::trDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 136 of file translator_si.h.
    { return "Dokumentacija"; }
trEnumerations() [1/2]
QCString TranslatorSlovene::trEnumerations () [inline], [virtual]
Implements Translator.
Definition at line 161 of file translator_si.h.
    { return "Natevni tipi"; }
trEnumerations() [2/2]
QCString TranslatorSlovene::trEnumerations () [inline], [virtual]
Implements Translator.
Definition at line 161 of file translator_si.h.
    { return "Natevni tipi"; }
trEnumerationTypeDocumentation() [1/2]
QCString TranslatorSlovene::trEnumerationTypeDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 173 of file translator_si.h.
    { return "Opis natevnega (enum) tipa"; }
trEnumerationTypeDocumentation() [2/2]
QCString TranslatorSlovene::trEnumerationTypeDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 173 of file translator_si.h.
    { return "Opis natevnega (enum) tipa"; }
trEnumerationValues() [1/2]
QCString TranslatorSlovene::trEnumerationValues () [inline], [virtual]
Implements Translator.
Definition at line 167 of file translator_si.h.
    { return "Vrednosti natevnih tipov"; }
trEnumerationValues() [2/2]
QCString TranslatorSlovene::trEnumerationValues () [inline], [virtual]
Implements Translator.
Definition at line 167 of file translator_si.h.
    { return "Vrednosti natevnih tipov"; }
trEnumName() [1/2]
QCString TranslatorSlovene::trEnumName () [inline], [virtual]
Implements Translator.
Definition at line 74 of file translator_si.h.
    { return "natevno ime"; }
trEnumName() [2/2]
QCString TranslatorSlovene::trEnumName () [inline], [virtual]
Implements Translator.
Definition at line 74 of file translator_si.h.
    { return "natevno ime"; }
trEnumValue() [1/2]
QCString TranslatorSlovene::trEnumValue () [inline], [virtual]
Implements Translator.
Definition at line 76 of file translator_si.h.
    { return "natevna vrednost"; }
trEnumValue() [2/2]
QCString TranslatorSlovene::trEnumValue () [inline], [virtual]
Implements Translator.
Definition at line 76 of file translator_si.h.
    { return "natevna vrednost"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorSlovene::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 988 of file translator_si.h.
    {
      return "Opisi dogodkov";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorSlovene::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 988 of file translator_si.h.
    {
      return "Opisi dogodkov";
    }
trEvents() [1/2]
virtual QCString TranslatorSlovene::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 983 of file translator_si.h.
    {
      return "Dogodki";
    }
trEvents() [2/2]
virtual QCString TranslatorSlovene::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 983 of file translator_si.h.
    {
      return "Dogodki";
    }
trExampleDocumentation() [1/2]
QCString TranslatorSlovene::trExampleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 152 of file translator_si.h.
    { return "Opis primera"; }
trExampleDocumentation() [2/2]
QCString TranslatorSlovene::trExampleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 152 of file translator_si.h.
    { return "Opis primera"; }
trExamples() [1/2]
QCString TranslatorSlovene::trExamples () [inline], [virtual]
Implements Translator.
Definition at line 94 of file translator_si.h.
    { return "Primeri"; }
trExamples() [2/2]
QCString TranslatorSlovene::trExamples () [inline], [virtual]
Implements Translator.
Definition at line 94 of file translator_si.h.
    { return "Primeri"; }
trExamplesDescription() [1/2]
QCString TranslatorSlovene::trExamplesDescription () [inline], [virtual]
Implements Translator.
Definition at line 130 of file translator_si.h.
    { return "Seznam primerov :"; }
trExamplesDescription() [2/2]
QCString TranslatorSlovene::trExamplesDescription () [inline], [virtual]
Implements Translator.
Definition at line 130 of file translator_si.h.
    { return "Seznam primerov :"; }
trExceptions() [1/2]
QCString TranslatorSlovene::trExceptions () [inline], [virtual]
Implements Translator.
Definition at line 204 of file translator_si.h.
    { return "Prekinitve"; }
trExceptions() [2/2]
QCString TranslatorSlovene::trExceptions () [inline], [virtual]
Implements Translator.
Definition at line 204 of file translator_si.h.
    { return "Prekinitve"; }
trFile() [1/2]
virtual QCString TranslatorSlovene::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 847 of file translator_si.h.
    {
      QCString result((first_capital ? "Datotek" : "datotek"));
      if (!singular) result+="e";
      else result += "a";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorSlovene::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 847 of file translator_si.h.
    {
      QCString result((first_capital ? "Datotek" : "datotek"));
      if (!singular) result+="e";
      else result += "a";
      return result;
    }
trFileDocumentation() [1/2]
QCString TranslatorSlovene::trFileDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 150 of file translator_si.h.
    { return "Opis datoteke"; }
trFileDocumentation() [2/2]
QCString TranslatorSlovene::trFileDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 150 of file translator_si.h.
    { return "Opis datoteke"; }
trFileIndex() [1/2]
QCString TranslatorSlovene::trFileIndex () [inline], [virtual]
Implements Translator.
Definition at line 144 of file translator_si.h.
    { return "seznam datotek"; }
trFileIndex() [2/2]
QCString TranslatorSlovene::trFileIndex () [inline], [virtual]
Implements Translator.
Definition at line 144 of file translator_si.h.
    { return "seznam datotek"; }
trFileList() [1/2]
QCString TranslatorSlovene::trFileList () [inline], [virtual]
Implements Translator.
Definition at line 86 of file translator_si.h.
    { return "seznam datotek"; }
trFileList() [2/2]
QCString TranslatorSlovene::trFileList () [inline], [virtual]
Implements Translator.
Definition at line 86 of file translator_si.h.
    { return "seznam datotek"; }
trFileListDescription() [1/2]
QCString TranslatorSlovene::trFileListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 101 of file translator_si.h.
    {
      QCString result="Seznam vseh ";
      if (!extractAll) result+="dokumentiranih ";
      result+="datotek s kratkim opisom:";
      return result;
    }
trFileListDescription() [2/2]
QCString TranslatorSlovene::trFileListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 101 of file translator_si.h.
    {
      QCString result="Seznam vseh ";
      if (!extractAll) result+="dokumentiranih ";
      result+="datotek s kratkim opisom:";
      return result;
    }
trFileMembers() [1/2]
QCString TranslatorSlovene::trFileMembers () [inline], [virtual]
Implements Translator.
Definition at line 90 of file translator_si.h.
    { return "komponente v datotekah"; }
trFileMembers() [2/2]
QCString TranslatorSlovene::trFileMembers () [inline], [virtual]
Implements Translator.
Definition at line 90 of file translator_si.h.
    { return "komponente v datotekah"; }
trFileMembersDescription() [1/2]
QCString TranslatorSlovene::trFileMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 121 of file translator_si.h.
    {
      QCString result="Seznam ";
      if (!extractAll) result+="dokumentiranih ";
      result+="entitet v datotekah ";
      if (extractAll) result+="skupaj z opisom datoteke v kateri se nahajajo:";
      else result+="s povezavami na datoteke v katerih se nahajajo:";
      return result;
    }
trFileMembersDescription() [2/2]
QCString TranslatorSlovene::trFileMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 121 of file translator_si.h.
    {
      QCString result="Seznam ";
      if (!extractAll) result+="dokumentiranih ";
      result+="entitet v datotekah ";
      if (extractAll) result+="skupaj z opisom datoteke v kateri se nahajajo:";
      else result+="s povezavami na datoteke v katerih se nahajajo:";
      return result;
    }
trFileReference() [1/2]
QCString TranslatorSlovene::trFileReference (const QCString & fileName) [inline], [virtual]
Implements Translator.
Definition at line 257 of file translator_si.h.
    {
      QCString result="Datoteka ";
      result+=fileName;
      return result;
    }
trFileReference() [2/2]
QCString TranslatorSlovene::trFileReference (const QCString & fileName) [inline], [virtual]
Implements Translator.
Definition at line 257 of file translator_si.h.
    {
      QCString result="Datoteka ";
      result+=fileName;
      return result;
    }
trFriends() [1/2]
QCString TranslatorSlovene::trFriends () [inline], [virtual]
Implements Translator.
Definition at line 222 of file translator_si.h.
    { return "Prijatelji (Friends) "; }
trFriends() [2/2]
QCString TranslatorSlovene::trFriends () [inline], [virtual]
Implements Translator.
Definition at line 222 of file translator_si.h.
    { return "Prijatelji (Friends) "; }
trFunctionDocumentation() [1/2]
QCString TranslatorSlovene::trFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 175 of file translator_si.h.
    { return "Opis funkcije"; }
trFunctionDocumentation() [2/2]
QCString TranslatorSlovene::trFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 175 of file translator_si.h.
    { return "Opis funkcije"; }
trFunctions() [1/2]
QCString TranslatorSlovene::trFunctions () [inline], [virtual]
Implements Translator.
Definition at line 163 of file translator_si.h.
    { return "Funkcije"; }
trFunctions() [2/2]
QCString TranslatorSlovene::trFunctions () [inline], [virtual]
Implements Translator.
Definition at line 163 of file translator_si.h.
    { return "Funkcije"; }
trGeneratedAt() [1/2]
QCString TranslatorSlovene::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
Implements Translator.
Definition at line 181 of file translator_si.h.
    {
      QCString result="Generirano "+date;
      if (!projName.isEmpty()) result+=" projekt: "+projName;
      result+=" generator: ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
QCString TranslatorSlovene::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
Implements Translator.
Definition at line 181 of file translator_si.h.
    {
      QCString result="Generirano "+date;
      if (!projName.isEmpty()) result+=" projekt: "+projName;
      result+=" generator: ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
QCString TranslatorSlovene::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
Implements Translator.
Definition at line 68 of file translator_si.h.
    { QCString result="zgenerirano z Doxygen-om";
      if (!s.isEmpty()) result+=" za "+s;
      result+=" iz izvorne kode.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
QCString TranslatorSlovene::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
Implements Translator.
Definition at line 68 of file translator_si.h.
    { QCString result="zgenerirano z Doxygen-om";
      if (!s.isEmpty()) result+=" za "+s;
      result+=" iz izvorne kode.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
QCString TranslatorSlovene::trGeneratedBy () [inline], [virtual]
Implements Translator.
Definition at line 206 of file translator_si.h.
    { return "Izdelano s pomojo"; }
trGeneratedBy() [2/2]
QCString TranslatorSlovene::trGeneratedBy () [inline], [virtual]
Implements Translator.
Definition at line 206 of file translator_si.h.
    { return "Izdelano s pomojo"; }
trGeneratedFromFiles() [1/2]
QCString TranslatorSlovene::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 386 of file translator_si.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Opis ";
      switch(compType)
      {
        case ClassDef::Class: result+="razreda"; break;
        case ClassDef::Struct: result+="strukture"; break;
        case ClassDef::Union: result+="unije"; break;
        case ClassDef::Interface: result+="vmesnika (interface)"; break;
        case ClassDef::Protocol: result+="protocol"; break; // translate me!
        case ClassDef::Category: result+="category"; break; // translate me!
        case ClassDef::Exception: result+="prekinitve (exception)"; break;
        default: break;
      }
      result+=" je zgrajen na podlagi naslednj";
      if (single) result+="e "; else result+="ih";
      result+=" datotek";
      if (single) result+="e :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
QCString TranslatorSlovene::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 386 of file translator_si.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Opis ";
      switch(compType)
      {
        case ClassDef::Class: result+="razreda"; break;
        case ClassDef::Struct: result+="strukture"; break;
        case ClassDef::Union: result+="unije"; break;
        case ClassDef::Interface: result+="vmesnika (interface)"; break;
        case ClassDef::Protocol: result+="protocol"; break; // translate me!
        case ClassDef::Category: result+="category"; break; // translate me!
        case ClassDef::Exception: result+="prekinitve (exception)"; break;
        default: break;
      }
      result+=" je zgrajen na podlagi naslednj";
      if (single) result+="e "; else result+="ih";
      result+=" datotek";
      if (single) result+="e :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorSlovene::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 903 of file translator_si.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorSlovene::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 903 of file translator_si.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGotoDocumentation() [1/2]
QCString TranslatorSlovene::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 481 of file translator_si.h.
    {
      return "dokumenacija tekoe datoteke.";
    }
trGotoDocumentation() [2/2]
QCString TranslatorSlovene::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 481 of file translator_si.h.
    {
      return "dokumenacija tekoe datoteke.";
    }
trGotoGraphicalHierarchy() [1/2]
QCString TranslatorSlovene::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 514 of file translator_si.h.
    {
      return "Dedovalna hierarhija v grafini obliki";
    }
trGotoGraphicalHierarchy() [2/2]
QCString TranslatorSlovene::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 514 of file translator_si.h.
    {
      return "Dedovalna hierarhija v grafini obliki";
    }
trGotoSourceCode() [1/2]
QCString TranslatorSlovene::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 476 of file translator_si.h.
    {
      return "izvorna koda";
    }
trGotoSourceCode() [2/2]
QCString TranslatorSlovene::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 476 of file translator_si.h.
    {
      return "izvorna koda";
    }
trGotoTextualHierarchy() [1/2]
QCString TranslatorSlovene::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 518 of file translator_si.h.
    {
      return "Dedovalna hierarhija v tekstovni obliki";
    }
trGotoTextualHierarchy() [2/2]
QCString TranslatorSlovene::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 518 of file translator_si.h.
    {
      return "Dedovalna hierarhija v tekstovni obliki";
    }
trGraphicalHierarchy() [1/2]
QCString TranslatorSlovene::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 510 of file translator_si.h.
    {
      return "Hierarhija razredov v grafini obliki";
    }
trGraphicalHierarchy() [2/2]
QCString TranslatorSlovene::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 510 of file translator_si.h.
    {
      return "Hierarhija razredov v grafini obliki";
    }
trGroup() [1/2]
virtual QCString TranslatorSlovene::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 870 of file translator_si.h.
    {
      QCString result((first_capital ? "Skupina" : "skupina"));
      if (!singular) result+="s";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorSlovene::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 870 of file translator_si.h.
    {
      QCString result((first_capital ? "Skupina" : "skupina"));
      if (!singular) result+="s";
      return result;
    }
trHierarchicalIndex() [1/2]
QCString TranslatorSlovene::trHierarchicalIndex () [inline], [virtual]
Implements Translator.
Definition at line 140 of file translator_si.h.
    { return "Hierarhini indeks"; }
trHierarchicalIndex() [2/2]
QCString TranslatorSlovene::trHierarchicalIndex () [inline], [virtual]
Implements Translator.
Definition at line 140 of file translator_si.h.
    { return "Hierarhini indeks"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorSlovene::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 939 of file translator_si.h.
    {
      return "Implementira "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorSlovene::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 939 of file translator_si.h.
    {
      return "Implementira "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorSlovene::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 947 of file translator_si.h.
    {
      return "Implementirano v "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorSlovene::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 947 of file translator_si.h.
    {
      return "Implementirano v "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorSlovene::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 602 of file translator_si.h.
    {
      return "Graf prikazuje datoteke, ki posredno ali neposredno "
             "vkljuujejo tekoo datoteko. Pravokotniki simbolizirajo datoteke, "
             "puice pa relacije med datotekami. Tekoa datoteka je prikazana "
         "kot pravokotnik s rno podlago, ostale pa kot pravokotnik brez podlage. "
         "Smer puice A->B definira relacijo \"A vkljuuje B\". "
         "Vse datoteke, ki torej mejijo na tekoo (t.j. obstaja povezava med rnim in "
         "praznim pravokotnikom), jo direktno vkljuujejo, medtem, ko jo ostale vkljuujejo "
         "le posredno. "
    ;
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorSlovene::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 602 of file translator_si.h.
    {
      return "Graf prikazuje datoteke, ki posredno ali neposredno "
             "vkljuujejo tekoo datoteko. Pravokotniki simbolizirajo datoteke, "
             "puice pa relacije med datotekami. Tekoa datoteka je prikazana "
         "kot pravokotnik s rno podlago, ostale pa kot pravokotnik brez podlage. "
         "Smer puice A->B definira relacijo \"A vkljuuje B\". "
         "Vse datoteke, ki torej mejijo na tekoo (t.j. obstaja povezava med rnim in "
         "praznim pravokotnikom), jo direktno vkljuujejo, medtem, ko jo ostale vkljuujejo "
         "le posredno. "
    ;
    }
trInclDepGraph() [1/2]
QCString TranslatorSlovene::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 460 of file translator_si.h.
    {
      return "Graf prikazuje seznam datotek, "
          "ki jih datoteka \""+fName+"\" "
          "direktno ali indirektno vkljuuje. Pravokotniki ponazarjajo datoteke, puice "
      "predstavljajo relacije med njimi. "
      "rn pravokotnik ponazarja datoteko "+fName+". Puice A->B ponazarjajo "
      "usmerjeno relacijo \"A vkljuuje B\"."
;
    }
trInclDepGraph() [2/2]
QCString TranslatorSlovene::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 460 of file translator_si.h.
    {
      return "Graf prikazuje seznam datotek, "
          "ki jih datoteka \""+fName+"\" "
          "direktno ali indirektno vkljuuje. Pravokotniki ponazarjajo datoteke, puice "
      "predstavljajo relacije med njimi. "
      "rn pravokotnik ponazarja datoteko "+fName+". Puice A->B ponazarjajo "
      "usmerjeno relacijo \"A vkljuuje B\"."
;
    }
trIncludingInheritedMembers() [1/2]
QCString TranslatorSlovene::trIncludingInheritedMembers () [inline], [virtual]
Implements Translator.
Definition at line 66 of file translator_si.h.
    { return ", vkljuujo dedovane metode in atribute."; }
trIncludingInheritedMembers() [2/2]
QCString TranslatorSlovene::trIncludingInheritedMembers () [inline], [virtual]
Implements Translator.
Definition at line 66 of file translator_si.h.
    { return ", vkljuujo dedovane metode in atribute."; }
trInheritedByList() [1/2]
QCString TranslatorSlovene::trInheritedByList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 326 of file translator_si.h.
    {
      return "Naslijeena u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
QCString TranslatorSlovene::trInheritedByList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 326 of file translator_si.h.
    {
      return "Naslijeena u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [1/2]
QCString TranslatorSlovene::trInheritsList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 320 of file translator_si.h.
    {
      return "Deduje od "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
QCString TranslatorSlovene::trInheritsList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 320 of file translator_si.h.
    {
      return "Deduje od "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
QCString TranslatorSlovene::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 501 of file translator_si.h.
    {
      return "Zaetna vrednost / definicija :";
    }
trInitialValue() [2/2]
QCString TranslatorSlovene::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 501 of file translator_si.h.
    {
      return "Zaetna vrednost / definicija :";
    }
trInvariant() [1/2]
QCString TranslatorSlovene::trInvariant () [inline], [virtual]
Text for the
Invariant
command
Implements Translator.
Definition at line 496 of file translator_si.h.
    {
      return "Invarianta";
    }
trInvariant() [2/2]
QCString TranslatorSlovene::trInvariant () [inline], [virtual]
Text for the
Invariant
command
Implements Translator.
Definition at line 496 of file translator_si.h.
    {
      return "Invarianta";
    }
trISOLang() [1/2]
QCString TranslatorSlovene::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 36 of file translator_si.h.
    { return "sl"; }
trISOLang() [2/2]
QCString TranslatorSlovene::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 36 of file translator_si.h.
    { return "sl"; }
trLegend() [1/2]
virtual QCString TranslatorSlovene::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 691 of file translator_si.h.
    {
      return "legenda";
    }
trLegend() [2/2]
virtual QCString TranslatorSlovene::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 691 of file translator_si.h.
    {
      return "legenda";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorSlovene::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 631 of file translator_si.h.
    {
      return
        "Tekoa stran pojasnjuje nain interpretacije grafov, ki jih izrie "
        "doxygen.<p>\n"
        "Poglejmo si naslednji primer:\n"
        "\\code\n"
        "/*! Nevide razred zaradi rezanja */\n"
        "class Invisible { };\n\n"
        "/*! Odrezan razred, dedovalna relacija je skrita */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* razred, ki ni opisan z doxygen komentarji */\n"
        "class Undocumented { };\n\n"
        "/*! Razred, ki ga dedujemo s pomojo javnega dedovanja */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Razred, ki ga dedujemo s pomojo zaitenega dedovanja */\n"
        "class ProtectedBase { };\n\n"
        "/*! Razred, ki ga dedujemo s pomojo skritega dedovanja */\n"
        "class PrivateBase { };\n\n"
        "/*! Razred, ki ga uporablja dedovani razred */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "If the \\c MAX_DOT_GRAPH_HEIGHT tag in the configuration file "
        "is set to 200 this will result in the following graph:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>%A filled black box represents the struct or class for which the "
        "graph is generated.\n"
        "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.\n"
        "<li>%A box with a red border denotes a documented struct or class for\n"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries."
        "</ul>\n"
        "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.\n"
        "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible. \n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorSlovene::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 631 of file translator_si.h.
    {
      return
        "Tekoa stran pojasnjuje nain interpretacije grafov, ki jih izrie "
        "doxygen.<p>\n"
        "Poglejmo si naslednji primer:\n"
        "\\code\n"
        "/*! Nevide razred zaradi rezanja */\n"
        "class Invisible { };\n\n"
        "/*! Odrezan razred, dedovalna relacija je skrita */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* razred, ki ni opisan z doxygen komentarji */\n"
        "class Undocumented { };\n\n"
        "/*! Razred, ki ga dedujemo s pomojo javnega dedovanja */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Razred, ki ga dedujemo s pomojo zaitenega dedovanja */\n"
        "class ProtectedBase { };\n\n"
        "/*! Razred, ki ga dedujemo s pomojo skritega dedovanja */\n"
        "class PrivateBase { };\n\n"
        "/*! Razred, ki ga uporablja dedovani razred */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "If the \\c MAX_DOT_GRAPH_HEIGHT tag in the configuration file "
        "is set to 200 this will result in the following graph:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>%A filled black box represents the struct or class for which the "
        "graph is generated.\n"
        "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.\n"
        "<li>%A box with a red border denotes a documented struct or class for\n"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries."
        "</ul>\n"
        "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.\n"
        "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible. \n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorSlovene::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 624 of file translator_si.h.
    {
      return "Legenda grafa";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorSlovene::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 624 of file translator_si.h.
    {
      return "Legenda grafa";
    }
trListOfAllMembers() [1/2]
QCString TranslatorSlovene::trListOfAllMembers () [inline], [virtual]
Implements Translator.
Definition at line 60 of file translator_si.h.
    { return "Seznam vseh metod / atributov"; }
trListOfAllMembers() [2/2]
QCString TranslatorSlovene::trListOfAllMembers () [inline], [virtual]
Implements Translator.
Definition at line 60 of file translator_si.h.
    { return "Seznam vseh metod / atributov"; }
trMainPage() [1/2]
QCString TranslatorSlovene::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 419 of file translator_si.h.
    { return "prva stran"; }
trMainPage() [2/2]
QCString TranslatorSlovene::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 419 of file translator_si.h.
    { return "prva stran"; }
trMember() [1/2]
virtual QCString TranslatorSlovene::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 892 of file translator_si.h.
    {
      QCString result((first_capital ? "Element" : "element"));
      if (!singular) result+="i";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorSlovene::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 892 of file translator_si.h.
    {
      QCString result((first_capital ? "Element" : "element"));
      if (!singular) result+="i";
      return result;
    }
trMemberDataDocumentation() [1/2]
QCString TranslatorSlovene::trMemberDataDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 56 of file translator_si.h.
    { return "Opis atributov"; }
trMemberDataDocumentation() [2/2]
QCString TranslatorSlovene::trMemberDataDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 56 of file translator_si.h.
    { return "Opis atributov"; }
trMemberEnumerationDocumentation() [1/2]
QCString TranslatorSlovene::trMemberEnumerationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 50 of file translator_si.h.
    { return "Opis komponent natevnih tipov"; }
trMemberEnumerationDocumentation() [2/2]
QCString TranslatorSlovene::trMemberEnumerationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 50 of file translator_si.h.
    { return "Opis komponent natevnih tipov"; }
trMemberFunctionDocumentation() [1/2]
QCString TranslatorSlovene::trMemberFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 54 of file translator_si.h.
    { return "Opis metod"; }
trMemberFunctionDocumentation() [2/2]
QCString TranslatorSlovene::trMemberFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 54 of file translator_si.h.
    { return "Opis metod"; }
trMemberList() [1/2]
QCString TranslatorSlovene::trMemberList () [inline], [virtual]
Implements Translator.
Definition at line 62 of file translator_si.h.
    { return " - seznam metod in atributov."; }
trMemberList() [2/2]
QCString TranslatorSlovene::trMemberList () [inline], [virtual]
Implements Translator.
Definition at line 62 of file translator_si.h.
    { return " - seznam metod in atributov."; }
trMemberTypedefDocumentation() [1/2]
QCString TranslatorSlovene::trMemberTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 48 of file translator_si.h.
    { return "Opis uporabniko definiranih tipov"; }
trMemberTypedefDocumentation() [2/2]
QCString TranslatorSlovene::trMemberTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 48 of file translator_si.h.
    { return "Opis uporabniko definiranih tipov"; }
trModuleDocumentation() [1/2]
QCString TranslatorSlovene::trModuleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 146 of file translator_si.h.
    { return "Dokumentacija modulov"; }
trModuleDocumentation() [2/2]
QCString TranslatorSlovene::trModuleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 146 of file translator_si.h.
    { return "Dokumentacija modulov"; }
trModuleIndex() [1/2]
QCString TranslatorSlovene::trModuleIndex () [inline], [virtual]
Implements Translator.
Definition at line 138 of file translator_si.h.
    { return "seznam modulov"; }
trModuleIndex() [2/2]
QCString TranslatorSlovene::trModuleIndex () [inline], [virtual]
Implements Translator.
Definition at line 138 of file translator_si.h.
    { return "seznam modulov"; }
trModules() [1/2]
QCString TranslatorSlovene::trModules () [inline], [virtual]
Implements Translator.
Definition at line 80 of file translator_si.h.
    { return "moduli"; }
trModules() [2/2]
QCString TranslatorSlovene::trModules () [inline], [virtual]
Implements Translator.
Definition at line 80 of file translator_si.h.
    { return "moduli"; }
trModulesDescription() [1/2]
QCString TranslatorSlovene::trModulesDescription () [inline], [virtual]
Implements Translator.
Definition at line 134 of file translator_si.h.
    { return "Seznam modulov:"; }
trModulesDescription() [2/2]
QCString TranslatorSlovene::trModulesDescription () [inline], [virtual]
Implements Translator.
Definition at line 134 of file translator_si.h.
    { return "Seznam modulov:"; }
trMonth() [1/2]
virtual QCString TranslatorSlovene::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1174 of file translator_si.h.
    {
      static const char *months_short[] = { "jan.", "feb.", "mar.", "apr.", "maj", "jun.", "jul.", "avg.", "sep.", "okt.", "nov.", "dec." };
      static const char *months_full[] = { "januar", "februar", "marec", "april", "maj", "junij", "julij", "avgust", "september", "oktober", "november", "december" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorSlovene::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1174 of file translator_si.h.
    {
      static const char *months_short[] = { "jan.", "feb.", "mar.", "apr.", "maj", "jun.", "jul.", "avg.", "sep.", "okt.", "nov.", "dec." };
      static const char *months_full[] = { "januar", "februar", "marec", "april", "maj", "junij", "julij", "avgust", "september", "oktober", "november", "december" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
QCString TranslatorSlovene::trMore () [inline], [virtual]
Implements Translator.
Definition at line 58 of file translator_si.h.
    { return "..."; }
trMore() [2/2]
QCString TranslatorSlovene::trMore () [inline], [virtual]
Implements Translator.
Definition at line 58 of file translator_si.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorSlovene::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 859 of file translator_si.h.
    {
      QCString result((first_capital ? "Imenski prostor" : "imenski prostor"));
      if (!singular) result+="i";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorSlovene::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 859 of file translator_si.h.
    {
      QCString result((first_capital ? "Imenski prostor" : "imenski prostor"));
      if (!singular) result+="i";
      return result;
    }
trNamespaceDocumentation() [1/2]
QCString TranslatorSlovene::trNamespaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 364 of file translator_si.h.
    { return "Podatki o imenskih prostorih"; }
trNamespaceDocumentation() [2/2]
QCString TranslatorSlovene::trNamespaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 364 of file translator_si.h.
    { return "Podatki o imenskih prostorih"; }
trNamespaceIndex() [1/2]
QCString TranslatorSlovene::trNamespaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 360 of file translator_si.h.
    { return "Indeks imenskih prostorov"; }
trNamespaceIndex() [2/2]
QCString TranslatorSlovene::trNamespaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 360 of file translator_si.h.
    { return "Indeks imenskih prostorov"; }
trNamespaceList() [1/2]
QCString TranslatorSlovene::trNamespaceList () [inline], [virtual]
Implements Translator.
Definition at line 213 of file translator_si.h.
    { return "imenski prostori"; }
trNamespaceList() [2/2]
QCString TranslatorSlovene::trNamespaceList () [inline], [virtual]
Implements Translator.
Definition at line 213 of file translator_si.h.
    { return "imenski prostori"; }
trNamespaceListDescription() [1/2]
QCString TranslatorSlovene::trNamespaceListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 215 of file translator_si.h.
    {
      QCString result="Seznam ";
      if (!extractAll) result+="dokumentiranih ";
      result+="imenskih prostorov z opisom:";
      return result;
    }
trNamespaceListDescription() [2/2]
QCString TranslatorSlovene::trNamespaceListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 215 of file translator_si.h.
    {
      QCString result="Seznam ";
      if (!extractAll) result+="dokumentiranih ";
      result+="imenskih prostorov z opisom:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
QCString TranslatorSlovene::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 348 of file translator_si.h.
    {
      QCString result="Seznam vseh ";
      if (!extractAll) result+="dokumentiranih ";
      result+="elementov imenskega prostora s povezavami na ";
      if (extractAll)
        result+="opis vsakega elementa:";
      else
        result+="imenski prostor, ki mu pripadajo:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
QCString TranslatorSlovene::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 348 of file translator_si.h.
    {
      QCString result="Seznam vseh ";
      if (!extractAll) result+="dokumentiranih ";
      result+="elementov imenskega prostora s povezavami na ";
      if (extractAll)
        result+="opis vsakega elementa:";
      else
        result+="imenski prostor, ki mu pripadajo:";
      return result;
    }
trNamespaceMembers() [1/2]
QCString TranslatorSlovene::trNamespaceMembers () [inline], [virtual]
Implements Translator.
Definition at line 345 of file translator_si.h.
    { return "elementi imenskega prostora"; }
trNamespaceMembers() [2/2]
QCString TranslatorSlovene::trNamespaceMembers () [inline], [virtual]
Implements Translator.
Definition at line 345 of file translator_si.h.
    { return "elementi imenskega prostora"; }
trNamespaceReference() [1/2]
QCString TranslatorSlovene::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
Implements Translator.
Definition at line 264 of file translator_si.h.
    {
      QCString result ="Imenski prostor ";
      result+=namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
QCString TranslatorSlovene::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
Implements Translator.
Definition at line 264 of file translator_si.h.
    {
      QCString result ="Imenski prostor ";
      result+=namespaceName;
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorSlovene::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 375 of file translator_si.h.
    { return "Imenski prostori"; }
trNamespaces() [2/2]
virtual QCString TranslatorSlovene::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 375 of file translator_si.h.
    { return "Imenski prostori"; }
trNote() [1/2]
QCString TranslatorSlovene::trNote () [inline], [virtual]
Implements Translator.
Definition at line 531 of file translator_si.h.
    {
      return "Opomba";
    }
trNote() [2/2]
QCString TranslatorSlovene::trNote () [inline], [virtual]
Implements Translator.
Definition at line 531 of file translator_si.h.
    {
      return "Opomba";
    }
trOverloadText() [1/2]
virtual QCString TranslatorSlovene::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1159 of file translator_si.h.
    {
      return "To je ponovno definirana metoda, " /* don't know Slovene expresion for overloaded */
             "podana je zaradi prironosti. Metoda se od predhodnje razlikuje "
             "samo v tevilu in/ali tipu formalnih argumentov.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorSlovene::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1159 of file translator_si.h.
    {
      return "To je ponovno definirana metoda, " /* don't know Slovene expresion for overloaded */
             "podana je zaradi prironosti. Metoda se od predhodnje razlikuje "
             "samo v tevilu in/ali tipu formalnih argumentov.";
    }
trPackage() [1/2]
virtual QCString TranslatorSlovene::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 748 of file translator_si.h.
    {
      return "JAVA paket "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorSlovene::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 748 of file translator_si.h.
    {
      return "JAVA paket "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorSlovene::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1024 of file translator_si.h.
    {
      return "Atributi paketa";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorSlovene::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1024 of file translator_si.h.
    {
      return "Atributi paketa";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorSlovene::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1006 of file translator_si.h.
    {
      return "Funkcije paketa"; /* don't know the context */
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorSlovene::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1006 of file translator_si.h.
    {
      return "Funkcije paketa"; /* don't know the context */
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorSlovene::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 753 of file translator_si.h.
    {
      return "Seznam JAVA paketov in njihovih kratkih opisov v primeru, da obstajajo:";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorSlovene::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 753 of file translator_si.h.
    {
      return "Seznam JAVA paketov in njihovih kratkih opisov v primeru, da obstajajo:";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorSlovene::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1010 of file translator_si.h.
    {
      return "Elemente paketa"; /* don't know the context */
    }
trPackageMembers() [2/2]
virtual QCString TranslatorSlovene::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1010 of file translator_si.h.
    {
      return "Elemente paketa"; /* don't know the context */
    }
trPackages() [1/2]
virtual QCString TranslatorSlovene::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 758 of file translator_si.h.
    {
      return "JAVA paketi";
    }
trPackages() [2/2]
virtual QCString TranslatorSlovene::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 758 of file translator_si.h.
    {
      return "JAVA paketi";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorSlovene::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 999 of file translator_si.h.
    {
      return "Tipi paketov";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorSlovene::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 999 of file translator_si.h.
    {
      return "Tipi paketov";
    }
trPage() [1/2]
virtual QCString TranslatorSlovene::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 881 of file translator_si.h.
    {
      QCString result((first_capital ? "Stran" : "stran"));
      if (!singular) result+="i";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorSlovene::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 881 of file translator_si.h.
    {
      QCString result((first_capital ? "Stran" : "stran"));
      if (!singular) result+="i";
      return result;
    }
trPageAbbreviation() [1/2]
QCString TranslatorSlovene::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 425 of file translator_si.h.
    { return "str."; }
trPageAbbreviation() [2/2]
QCString TranslatorSlovene::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 425 of file translator_si.h.
    { return "str."; }
trPageIndex() [1/2]
QCString TranslatorSlovene::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 522 of file translator_si.h.
    {
      return "Indeks strani";
    }
trPageIndex() [2/2]
QCString TranslatorSlovene::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 522 of file translator_si.h.
    {
      return "Indeks strani";
    }
trParameters() [1/2]
QCString TranslatorSlovene::trParameters () [inline], [virtual]
Implements Translator.
Definition at line 202 of file translator_si.h.
    { return "Parametri"; }
trParameters() [2/2]
QCString TranslatorSlovene::trParameters () [inline], [virtual]
Implements Translator.
Definition at line 202 of file translator_si.h.
    { return "Parametri"; }
trPostcondition() [1/2]
QCString TranslatorSlovene::trPostcondition () [inline], [virtual]
Text for the
Postcondition
command
Implements Translator.
Definition at line 491 of file translator_si.h.
    {
      return "Naknadni pogoji (posconditions)";
    }
trPostcondition() [2/2]
QCString TranslatorSlovene::trPostcondition () [inline], [virtual]
Text for the
Postcondition
command
Implements Translator.
Definition at line 491 of file translator_si.h.
    {
      return "Naknadni pogoji (posconditions)";
    }
trPrecondition() [1/2]
QCString TranslatorSlovene::trPrecondition () [inline], [virtual]
Text for the
Precondition
command
Implements Translator.
Definition at line 486 of file translator_si.h.
    {
      return "Predpogoji (preconditions)";
    }
trPrecondition() [2/2]
QCString TranslatorSlovene::trPrecondition () [inline], [virtual]
Text for the
Precondition
command
Implements Translator.
Definition at line 486 of file translator_si.h.
    {
      return "Predpogoji (preconditions)";
    }
trPrivateAttribs() [1/2]
QCString TranslatorSlovene::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 563 of file translator_si.h.
    {
      return "Skriti atributi";
    }
trPrivateAttribs() [2/2]
QCString TranslatorSlovene::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 563 of file translator_si.h.
    {
      return "Skriti atributi";
    }
trPrivateMembers() [1/2]
QCString TranslatorSlovene::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 288 of file translator_si.h.
    { return "Skrite metode in atributi"; }
trPrivateMembers() [2/2]
QCString TranslatorSlovene::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 288 of file translator_si.h.
    { return "Skrite metode in atributi"; }
trPrivateSlots() [1/2]
QCString TranslatorSlovene::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 290 of file translator_si.h.
    { return "Skriti slotovi"; }
trPrivateSlots() [2/2]
QCString TranslatorSlovene::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 290 of file translator_si.h.
    { return "Skriti slotovi"; }
trPrivateTypes() [1/2]
QCString TranslatorSlovene::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 559 of file translator_si.h.
    {
      return "Skriti tipi";
    }
trPrivateTypes() [2/2]
QCString TranslatorSlovene::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 559 of file translator_si.h.
    {
      return "Skriti tipi";
    }
trProperties() [1/2]
virtual QCString TranslatorSlovene::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 716 of file translator_si.h.
    {
      return "IDL Lastnosti";
    }
trProperties() [2/2]
virtual QCString TranslatorSlovene::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 716 of file translator_si.h.
    {
      return "IDL Lastnosti";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorSlovene::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 721 of file translator_si.h.
    {
      return "Opis IDL lastnosti";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorSlovene::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 721 of file translator_si.h.
    {
      return "Opis IDL lastnosti";
    }
trProtectedAttribs() [1/2]
QCString TranslatorSlovene::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 551 of file translator_si.h.
    {
      return "Zaiteni atributi";
    }
trProtectedAttribs() [2/2]
QCString TranslatorSlovene::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 551 of file translator_si.h.
    {
      return "Zaiteni atributi";
    }
trProtectedMembers() [1/2]
QCString TranslatorSlovene::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 282 of file translator_si.h.
    { return "Zaitene metode in atributi"; }
trProtectedMembers() [2/2]
QCString TranslatorSlovene::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 282 of file translator_si.h.
    { return "Zaitene metode in atributi"; }
trProtectedSlots() [1/2]
QCString TranslatorSlovene::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 284 of file translator_si.h.
    { return "Zaiteni sloti"; }
trProtectedSlots() [2/2]
QCString TranslatorSlovene::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 284 of file translator_si.h.
    { return "Zaiteni sloti"; }
trProtectedTypes() [1/2]
QCString TranslatorSlovene::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 547 of file translator_si.h.
    {
      return "Zaiteni tipi";
    }
trProtectedTypes() [2/2]
QCString TranslatorSlovene::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 547 of file translator_si.h.
    {
      return "Zaiteni tipi";
    }
trPublicAttribs() [1/2]
QCString TranslatorSlovene::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 539 of file translator_si.h.
    {
      return "Javni atributi";
    }
trPublicAttribs() [2/2]
QCString TranslatorSlovene::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 539 of file translator_si.h.
    {
      return "Javni atributi";
    }
trPublicMembers() [1/2]
QCString TranslatorSlovene::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 274 of file translator_si.h.
    { return "Javne metode"; }
trPublicMembers() [2/2]
QCString TranslatorSlovene::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 274 of file translator_si.h.
    { return "Javne metode"; }
trPublicSlots() [1/2]
QCString TranslatorSlovene::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 276 of file translator_si.h.
    { return "Public slotovi"; }
trPublicSlots() [2/2]
QCString TranslatorSlovene::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 276 of file translator_si.h.
    { return "Public slotovi"; }
trPublicTypes() [1/2]
QCString TranslatorSlovene::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 535 of file translator_si.h.
    {
      return "Javni tipi";
    }
trPublicTypes() [2/2]
QCString TranslatorSlovene::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 535 of file translator_si.h.
    {
      return "Javni tipi";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorSlovene::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 590 of file translator_si.h.
    {
      return "Uporabniki entitete: ";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorSlovene::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 590 of file translator_si.h.
    {
      return "Uporabniki entitete: ";
    }
trReferenceManual() [1/2]
QCString TranslatorSlovene::trReferenceManual () [inline], [virtual]
Implements Translator.
Definition at line 154 of file translator_si.h.
    { return "Prironik"; }
trReferenceManual() [2/2]
QCString TranslatorSlovene::trReferenceManual () [inline], [virtual]
Implements Translator.
Definition at line 154 of file translator_si.h.
    { return "Prironik"; }
trReferences() [1/2]
virtual QCString TranslatorSlovene::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 928 of file translator_si.h.
    {
      return "Reference";
    }
trReferences() [2/2]
virtual QCString TranslatorSlovene::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 928 of file translator_si.h.
    {
      return "Reference";
    }
trReimplementedFromList() [1/2]
QCString TranslatorSlovene::trReimplementedFromList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 332 of file translator_si.h.
    {
      return "Skrije implementacijo iz "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
QCString TranslatorSlovene::trReimplementedFromList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 332 of file translator_si.h.
    {
      return "Skrije implementacijo iz "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
QCString TranslatorSlovene::trReimplementedInList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 338 of file translator_si.h.
    {
      // used in member documentation blocks to produce a list of
      // all member that overwrite the implementation of this member.
      return "Metodo skrijejo implementacije v razredih "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
QCString TranslatorSlovene::trReimplementedInList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 338 of file translator_si.h.
    {
      // used in member documentation blocks to produce a list of
      // all member that overwrite the implementation of this member.
      return "Metodo skrijejo implementacije v razredih "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
QCString TranslatorSlovene::trRelatedFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 229 of file translator_si.h.
    { return "Podatki o poveznih funkcijah"; }
trRelatedFunctionDocumentation() [2/2]
QCString TranslatorSlovene::trRelatedFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 229 of file translator_si.h.
    { return "Podatki o poveznih funkcijah"; }
trRelatedFunctions() [1/2]
QCString TranslatorSlovene::trRelatedFunctions () [inline], [virtual]
Implements Translator.
Definition at line 42 of file translator_si.h.
    { return "Povezane funkcije"; }
trRelatedFunctions() [2/2]
QCString TranslatorSlovene::trRelatedFunctions () [inline], [virtual]
Implements Translator.
Definition at line 42 of file translator_si.h.
    { return "Povezane funkcije"; }
trRelatedPages() [1/2]
QCString TranslatorSlovene::trRelatedPages () [inline], [virtual]
Implements Translator.
Definition at line 92 of file translator_si.h.
    { return "dodatni opisi"; }
trRelatedPages() [2/2]
QCString TranslatorSlovene::trRelatedPages () [inline], [virtual]
Implements Translator.
Definition at line 92 of file translator_si.h.
    { return "dodatni opisi"; }
trRelatedPagesDescription() [1/2]
QCString TranslatorSlovene::trRelatedPagesDescription () [inline], [virtual]
Implements Translator.
Definition at line 132 of file translator_si.h.
    { return "Seznam strani z dodatnimi opisi:"; }
trRelatedPagesDescription() [2/2]
QCString TranslatorSlovene::trRelatedPagesDescription () [inline], [virtual]
Implements Translator.
Definition at line 132 of file translator_si.h.
    { return "Seznam strani z dodatnimi opisi:"; }
trRelatedSubscript() [1/2]
QCString TranslatorSlovene::trRelatedSubscript () [inline], [virtual]
Implements Translator.
Definition at line 44 of file translator_si.h.
    { return "(To niso metode.)"; }
trRelatedSubscript() [2/2]
QCString TranslatorSlovene::trRelatedSubscript () [inline], [virtual]
Implements Translator.
Definition at line 44 of file translator_si.h.
    { return "(To niso metode.)"; }
trRemarks() [1/2]
virtual QCString TranslatorSlovene::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 594 of file translator_si.h.
    {
      return "Opomba";
    }
trRemarks() [2/2]
virtual QCString TranslatorSlovene::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 594 of file translator_si.h.
    {
      return "Opomba";
    }
trReturns() [1/2]
QCString TranslatorSlovene::trReturns () [inline], [virtual]
Implements Translator.
Definition at line 198 of file translator_si.h.
    { return "Rezultat(i)"; }
trReturns() [2/2]
QCString TranslatorSlovene::trReturns () [inline], [virtual]
Implements Translator.
Definition at line 198 of file translator_si.h.
    { return "Rezultat(i)"; }
trReturnValues() [1/2]
QCString TranslatorSlovene::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 414 of file translator_si.h.
    { return "Povratna vrednost"; }
trReturnValues() [2/2]
QCString TranslatorSlovene::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 414 of file translator_si.h.
    { return "Povratna vrednost"; }
trRTFansicp() [1/2]
virtual QCString TranslatorSlovene::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 812 of file translator_si.h.
    {
      return "1250";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorSlovene::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 812 of file translator_si.h.
    {
      return "1250";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorSlovene::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 821 of file translator_si.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorSlovene::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 821 of file translator_si.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorSlovene::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 827 of file translator_si.h.
    {
      return "Indeks";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorSlovene::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 827 of file translator_si.h.
    {
      return "Indeks";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorSlovene::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 959 of file translator_si.h.
    {
      return "Vsebina";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorSlovene::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 959 of file translator_si.h.
    {
      return "Vsebina";
    }
trSearch() [1/2]
QCString TranslatorSlovene::trSearch () [inline], [virtual]
Implements Translator.
Definition at line 96 of file translator_si.h.
    { return "Ii"; }
trSearch() [2/2]
QCString TranslatorSlovene::trSearch () [inline], [virtual]
Implements Translator.
Definition at line 96 of file translator_si.h.
    { return "Ii"; }
trSearchMatches() [1/2]
virtual QCString TranslatorSlovene::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1095 of file translator_si.h.
    {
      return "Zadetki:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorSlovene::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1095 of file translator_si.h.
    {
      return "Zadetki:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorSlovene::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1072 of file translator_si.h.
    {
      if (numDocuments==0)
      {
        return "Oprostite, noben dokument ne ustreza vaemu povpraevanju.";
      }
      else if (numDocuments==1)
      {
        return "Nael sem <b>1</b> dokument, ki ustreza vaemu povpraevanju.";
      }
      else if (numDocuments==2)
      {
        return "Nael sem <b>2</b> dokumenta, ki ustrezata vaemu povpraevanju.";
      }
      else
      {
        return "Nael sem <b>$num</b> dokumentov, ki ustrezajo vaemu povpraevanju. "
               "Dokumenti z najboljo stopnjo ujemanja se nahajajo na zaetku.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorSlovene::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1072 of file translator_si.h.
    {
      if (numDocuments==0)
      {
        return "Oprostite, noben dokument ne ustreza vaemu povpraevanju.";
      }
      else if (numDocuments==1)
      {
        return "Nael sem <b>1</b> dokument, ki ustreza vaemu povpraevanju.";
      }
      else if (numDocuments==2)
      {
        return "Nael sem <b>2</b> dokumenta, ki ustrezata vaemu povpraevanju.";
      }
      else
      {
        return "Nael sem <b>$num</b> dokumentov, ki ustrezajo vaemu povpraevanju. "
               "Dokumenti z najboljo stopnjo ujemanja se nahajajo na zaetku.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorSlovene::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1060 of file translator_si.h.
    {
      return "Rezultat(i) iskanja";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorSlovene::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1060 of file translator_si.h.
    {
      return "Rezultat(i) iskanja";
    }
trSeeAlso() [1/2]
QCString TranslatorSlovene::trSeeAlso () [inline], [virtual]
Implements Translator.
Definition at line 200 of file translator_si.h.
    { return "Glej"; }
trSeeAlso() [2/2]
QCString TranslatorSlovene::trSeeAlso () [inline], [virtual]
Implements Translator.
Definition at line 200 of file translator_si.h.
    { return "Glej"; }
trSignals() [1/2]
QCString TranslatorSlovene::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 278 of file translator_si.h.
    { return "Programske prekinitve"; }
trSignals() [2/2]
QCString TranslatorSlovene::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 278 of file translator_si.h.
    { return "Programske prekinitve"; }
trSince() [1/2]
virtual QCString TranslatorSlovene::trSince () [inline], [virtual]
Implements Translator.
Definition at line 614 of file translator_si.h.
    {
      return "Od";
    }
trSince() [2/2]
virtual QCString TranslatorSlovene::trSince () [inline], [virtual]
Implements Translator.
Definition at line 614 of file translator_si.h.
    {
      return "Od";
    }
trSourceFile() [1/2]
virtual QCString TranslatorSlovene::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1106 of file translator_si.h.
    {
      return filename + " izvorna koda";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorSlovene::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1106 of file translator_si.h.
    {
      return filename + " izvorna koda";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorSlovene::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1031 of file translator_si.h.
    {
      return "Statini atributi paketa";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorSlovene::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1031 of file translator_si.h.
    {
      return "Statini atributi paketa";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorSlovene::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1017 of file translator_si.h.
    {
      return "Statine funkcije paketa";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorSlovene::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1017 of file translator_si.h.
    {
      return "Statine funkcije paketa";
    }
trStaticPrivateAttribs() [1/2]
QCString TranslatorSlovene::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 567 of file translator_si.h.
    {
      return "Statini skriti atributi";
    }
trStaticPrivateAttribs() [2/2]
QCString TranslatorSlovene::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 567 of file translator_si.h.
    {
      return "Statini skriti atributi";
    }
trStaticPrivateMembers() [1/2]
QCString TranslatorSlovene::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 292 of file translator_si.h.
    { return "Statine skrite metode in atributi"; }
trStaticPrivateMembers() [2/2]
QCString TranslatorSlovene::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 292 of file translator_si.h.
    { return "Statine skrite metode in atributi"; }
trStaticProtectedAttribs() [1/2]
QCString TranslatorSlovene::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 555 of file translator_si.h.
    {
      return "Statini zaiteni tipi";
    }
trStaticProtectedAttribs() [2/2]
QCString TranslatorSlovene::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 555 of file translator_si.h.
    {
      return "Statini zaiteni tipi";
    }
trStaticProtectedMembers() [1/2]
QCString TranslatorSlovene::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 286 of file translator_si.h.
    { return "Statine zaitene metode in atributi"; }
trStaticProtectedMembers() [2/2]
QCString TranslatorSlovene::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 286 of file translator_si.h.
    { return "Statine zaitene metode in atributi"; }
trStaticPublicAttribs() [1/2]
QCString TranslatorSlovene::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 543 of file translator_si.h.
    {
      return "Statini javni atributi";
    }
trStaticPublicAttribs() [2/2]
QCString TranslatorSlovene::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 543 of file translator_si.h.
    {
      return "Statini javni atributi";
    }
trStaticPublicMembers() [1/2]
QCString TranslatorSlovene::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 280 of file translator_si.h.
    { return "Statine javne metode in atributi"; }
trStaticPublicMembers() [2/2]
QCString TranslatorSlovene::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 280 of file translator_si.h.
    { return "Statine javne metode in atributi"; }
trTest() [1/2]
virtual QCString TranslatorSlovene::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 701 of file translator_si.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorSlovene::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 701 of file translator_si.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorSlovene::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 706 of file translator_si.h.
    {
      return "Test List";
    }
trTestList() [2/2]
virtual QCString TranslatorSlovene::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 706 of file translator_si.h.
    {
      return "Test List";
    }
trThisIsTheListOfAllMembers() [1/2]
QCString TranslatorSlovene::trThisIsTheListOfAllMembers () [inline], [virtual]
Implements Translator.
Definition at line 64 of file translator_si.h.
    { return "Seznam metod razreda "; }
trThisIsTheListOfAllMembers() [2/2]
QCString TranslatorSlovene::trThisIsTheListOfAllMembers () [inline], [virtual]
Implements Translator.
Definition at line 64 of file translator_si.h.
    { return "Seznam metod razreda "; }
trTodo() [1/2]
virtual QCString TranslatorSlovene::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 576 of file translator_si.h.
    {
      return "TODO";
    }
trTodo() [2/2]
virtual QCString TranslatorSlovene::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 576 of file translator_si.h.
    {
      return "TODO";
    }
trTodoList() [1/2]
virtual QCString TranslatorSlovene::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 581 of file translator_si.h.
    {
      return "Seznam nedokonanih opravil";
    }
trTodoList() [2/2]
virtual QCString TranslatorSlovene::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 581 of file translator_si.h.
    {
      return "Seznam nedokonanih opravil";
    }
trTypedefDocumentation() [1/2]
QCString TranslatorSlovene::trTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 171 of file translator_si.h.
    { return "Opis uporabniko definiranega tipa"; }
trTypedefDocumentation() [2/2]
QCString TranslatorSlovene::trTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 171 of file translator_si.h.
    { return "Opis uporabniko definiranega tipa"; }
trTypedefs() [1/2]
QCString TranslatorSlovene::trTypedefs () [inline], [virtual]
Implements Translator.
Definition at line 159 of file translator_si.h.
    { return "Uporabniko definirani tipi"; }
trTypedefs() [2/2]
QCString TranslatorSlovene::trTypedefs () [inline], [virtual]
Implements Translator.
Definition at line 159 of file translator_si.h.
    { return "Uporabniko definirani tipi"; }
trVariableDocumentation() [1/2]
QCString TranslatorSlovene::trVariableDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 177 of file translator_si.h.
    { return "Opis spremenljivke"; }
trVariableDocumentation() [2/2]
QCString TranslatorSlovene::trVariableDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 177 of file translator_si.h.
    { return "Opis spremenljivke"; }
trVariables() [1/2]
QCString TranslatorSlovene::trVariables () [inline], [virtual]
Implements Translator.
Definition at line 165 of file translator_si.h.
    { return "Spremenljivke"; }
trVariables() [2/2]
QCString TranslatorSlovene::trVariables () [inline], [virtual]
Implements Translator.
Definition at line 165 of file translator_si.h.
    { return "Spremenljivke"; }
trVersion() [1/2]
QCString TranslatorSlovene::trVersion () [inline], [virtual]
Implements Translator.
Definition at line 194 of file translator_si.h.
    { return "Verzija"; }
trVersion() [2/2]
QCString TranslatorSlovene::trVersion () [inline], [virtual]
Implements Translator.
Definition at line 194 of file translator_si.h.
    { return "Verzija"; }
trWarning() [1/2]
QCString TranslatorSlovene::trWarning () [inline], [virtual]
Implements Translator.
Definition at line 192 of file translator_si.h.
    { return "Opozorilo"; }
trWarning() [2/2]
QCString TranslatorSlovene::trWarning () [inline], [virtual]
Implements Translator.
Definition at line 192 of file translator_si.h.
    { return "Opozorilo"; }
trWriteList() [1/2]
QCString TranslatorSlovene::trWriteList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 296 of file translator_si.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" in ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
QCString TranslatorSlovene::trWriteList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 296 of file translator_si.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" in ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_si.h
doxygen/src/translator_si.h