ConceptDefAliasImpl Class Reference
Public Member Functions
ConceptDefAliasImpl (const Definition *newScope, const ConceptDef *cd)
virtual ~ConceptDefAliasImpl ()
const ConceptDef * getCdAlias () const
virtual ConceptDef * resolveAlias ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString getReference () const
virtual bool isReference () const
virtual bool hasDetailedDescription () const
virtual QCString displayName (bool includeScope=true) const
virtual const IncludeInfo * includeInfo () const
virtual ArgumentList getTemplateParameterList () const
virtual QCString anchor () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual QCString initializer () const
virtual const NamespaceDef * getNamespaceDef () const
virtual const FileDef * getFileDef () const
virtual QCString title () const
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const
virtual int groupId () const
ConceptDefAliasImpl (const Definition *newScope, const ConceptDef *cd)
virtual ~ConceptDefAliasImpl ()
const ConceptDef * getCdAlias () const
virtual ConceptDef * resolveAlias ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString getReference () const
virtual bool isReference () const
virtual bool hasDetailedDescription () const
virtual QCString displayName (bool includeScope=true) const
virtual const IncludeInfo * includeInfo () const
virtual ArgumentList getTemplateParameterList () const
virtual QCString anchor () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual QCString initializer () const
virtual const NamespaceDef * getNamespaceDef () const
virtual const FileDef * getFileDef () const
virtual QCString title () const
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const
virtual int groupId () const
Additional Inherited Members
Detailed Description
Definition at line 96 of file conceptdef.cpp.
Constructor & Destructor Documentation
ConceptDefAliasImpl() [1/2]
ConceptDefAliasImpl::ConceptDefAliasImpl (const Definition * newScope, const ConceptDef * cd) [inline]
Definition at line 99 of file conceptdef.cpp.
      : DefinitionAliasMixin(newScope,cd) { init(); }
References DefinitionAliasMixin< ConceptDef >::init().
 ConceptDefAliasImpl() [1/2]
virtual ConceptDefAliasImpl::~ConceptDefAliasImpl () [inline], [virtual]
Definition at line 101 of file conceptdef.cpp.
{ deinit(); }
References DefinitionAliasMixin< ConceptDef >::deinit().
ConceptDefAliasImpl() [2/2]
ConceptDefAliasImpl::ConceptDefAliasImpl (const Definition * newScope, const ConceptDef * cd) [inline]
Definition at line 99 of file conceptdef.cpp.
      : DefinitionAliasMixin(newScope,cd) { init(); }
References DefinitionAliasMixin< ConceptDef >::init().
 ConceptDefAliasImpl() [2/2]
virtual ConceptDefAliasImpl::~ConceptDefAliasImpl () [inline], [virtual]
Definition at line 101 of file conceptdef.cpp.
{ deinit(); }
References DefinitionAliasMixin< ConceptDef >::deinit().
Member Function Documentation
anchor() [1/2]
virtual QCString ConceptDefAliasImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements ConceptDef.
Definition at line 123 of file conceptdef.cpp.
    { return getCdAlias()->anchor(); }
References ConceptDef::anchor(), and getCdAlias().
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString ConceptDefAliasImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements ConceptDef.
Definition at line 123 of file conceptdef.cpp.
    { return getCdAlias()->anchor(); }
References ConceptDef::anchor(), and getCdAlias().
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
codeSymbolType() [1/2]
virtual CodeSymbolType ConceptDefAliasImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 107 of file conceptdef.cpp.
    { return getCdAlias()->codeSymbolType(); }
References Definition::codeSymbolType(), and getCdAlias().
codeSymbolType() [2/2]
virtual CodeSymbolType ConceptDefAliasImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 107 of file conceptdef.cpp.
    { return getCdAlias()->codeSymbolType(); }
References Definition::codeSymbolType(), and getCdAlias().
definitionType() [1/2]
virtual DefType ConceptDefAliasImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements ConceptDef.
Definition at line 106 of file conceptdef.cpp.
{ return TypeConcept; }
References Definition::TypeConcept.
definitionType() [2/2]
virtual DefType ConceptDefAliasImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements ConceptDef.
Definition at line 106 of file conceptdef.cpp.
{ return TypeConcept; }
References Definition::TypeConcept.
displayName() [1/2]
virtual QCString ConceptDefAliasImpl::displayName (bool includeScope = true) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements ConceptDef.
Definition at line 117 of file conceptdef.cpp.
    { return getCdAlias()->displayName(includeScope); }
References ConceptDef::displayName(), and getCdAlias().
displayName() [2/2]
virtual QCString ConceptDefAliasImpl::displayName (bool includeScope = true) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements ConceptDef.
Definition at line 117 of file conceptdef.cpp.
    { return getCdAlias()->displayName(includeScope); }
References ConceptDef::displayName(), and getCdAlias().
getCdAlias() [1/2]
const ConceptDef * ConceptDefAliasImpl::getCdAlias () const [inline]
Definition at line 103 of file conceptdef.cpp.
{ return toConceptDef(getAlias()); }
References DefinitionAliasMixin< ConceptDef >::getAlias(), and toConceptDef().
Referenced by anchor(), codeSymbolType(), displayName(), getFileDef(), getNamespaceDef(), getOutputFileBase(), getReference(), getTemplateParameterList(), groupId(), hasDetailedDescription(), includeInfo(), initializer(), isLinkable(), isLinkableInProject(), isReference(), resolveAlias(), title(), and writeDeclarationLink().
getCdAlias() [2/2]
const ConceptDef * ConceptDefAliasImpl::getCdAlias () const [inline]
Definition at line 103 of file conceptdef.cpp.
{ return toConceptDef(getAlias()); }
References DefinitionAliasMixin< ConceptDef >::getAlias(), and toConceptDef().
getFileDef() [1/2]
virtual const FileDef * ConceptDefAliasImpl::getFileDef () const [inline], [virtual]
Implements ConceptDef.
Definition at line 133 of file conceptdef.cpp.
    { return getCdAlias()->getFileDef(); }
References getCdAlias(), and ConceptDef::getFileDef().
getFileDef() [2/2]
virtual const FileDef * ConceptDefAliasImpl::getFileDef () const [inline], [virtual]
Implements ConceptDef.
Definition at line 133 of file conceptdef.cpp.
    { return getCdAlias()->getFileDef(); }
References getCdAlias(), and ConceptDef::getFileDef().
getNamespaceDef() [1/2]
virtual const NamespaceDef * ConceptDefAliasImpl::getNamespaceDef () const [inline], [virtual]
Implements ConceptDef.
Definition at line 131 of file conceptdef.cpp.
    { return getCdAlias()->getNamespaceDef(); }
References getCdAlias(), and ConceptDef::getNamespaceDef().
getNamespaceDef() [2/2]
virtual const NamespaceDef * ConceptDefAliasImpl::getNamespaceDef () const [inline], [virtual]
Implements ConceptDef.
Definition at line 131 of file conceptdef.cpp.
    { return getCdAlias()->getNamespaceDef(); }
References getCdAlias(), and ConceptDef::getNamespaceDef().
getOutputFileBase() [1/2]
virtual QCString ConceptDefAliasImpl::getOutputFileBase () const [inline], [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements ConceptDef.
Definition at line 109 of file conceptdef.cpp.
    { return getCdAlias()->getOutputFileBase(); }
References getCdAlias(), and ConceptDef::getOutputFileBase().
getOutputFileBase() [2/2]
virtual QCString ConceptDefAliasImpl::getOutputFileBase () const [inline], [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements ConceptDef.
Definition at line 109 of file conceptdef.cpp.
    { return getCdAlias()->getOutputFileBase(); }
References getCdAlias(), and ConceptDef::getOutputFileBase().
getReference() [1/2]
virtual QCString ConceptDefAliasImpl::getReference () const [inline], [virtual]
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Reimplemented from DefinitionAliasMixin< ConceptDef >.
Definition at line 111 of file conceptdef.cpp.
    { return getCdAlias()->getReference(); }
References getCdAlias(), and Definition::getReference().
getReference() [2/2]
virtual QCString ConceptDefAliasImpl::getReference () const [inline], [virtual]
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Reimplemented from DefinitionAliasMixin< ConceptDef >.
Definition at line 111 of file conceptdef.cpp.
    { return getCdAlias()->getReference(); }
References getCdAlias(), and Definition::getReference().
getTemplateParameterList() [1/2]
virtual ArgumentList ConceptDefAliasImpl::getTemplateParameterList () const [inline], [virtual]
Implements ConceptDef.
Definition at line 121 of file conceptdef.cpp.
    { return getCdAlias()->getTemplateParameterList(); }
References getCdAlias(), and ConceptDef::getTemplateParameterList().
getTemplateParameterList() [2/2]
virtual ArgumentList ConceptDefAliasImpl::getTemplateParameterList () const [inline], [virtual]
Implements ConceptDef.
Definition at line 121 of file conceptdef.cpp.
    { return getCdAlias()->getTemplateParameterList(); }
References getCdAlias(), and ConceptDef::getTemplateParameterList().
groupId() [1/2]
virtual int ConceptDefAliasImpl::groupId () const [inline], [virtual]
Implements ConceptDef.
Definition at line 140 of file conceptdef.cpp.
    { return getCdAlias()->groupId(); }
References getCdAlias(), and ConceptDef::groupId().
groupId() [2/2]
virtual int ConceptDefAliasImpl::groupId () const [inline], [virtual]
Implements ConceptDef.
Definition at line 140 of file conceptdef.cpp.
    { return getCdAlias()->groupId(); }
References getCdAlias(), and ConceptDef::groupId().
hasDetailedDescription() [1/2]
virtual bool ConceptDefAliasImpl::hasDetailedDescription () const [inline], [virtual]
Implements ConceptDef.
Definition at line 115 of file conceptdef.cpp.
    { return getCdAlias()->hasDetailedDescription(); }
References getCdAlias(), and ConceptDef::hasDetailedDescription().
hasDetailedDescription() [2/2]
virtual bool ConceptDefAliasImpl::hasDetailedDescription () const [inline], [virtual]
Implements ConceptDef.
Definition at line 115 of file conceptdef.cpp.
    { return getCdAlias()->hasDetailedDescription(); }
References getCdAlias(), and ConceptDef::hasDetailedDescription().
includeInfo() [1/2]
virtual const IncludeInfo * ConceptDefAliasImpl::includeInfo () const [inline], [virtual]
Implements ConceptDef.
Definition at line 119 of file conceptdef.cpp.
    { return getCdAlias()->includeInfo(); }
References getCdAlias(), and ConceptDef::includeInfo().
includeInfo() [2/2]
virtual const IncludeInfo * ConceptDefAliasImpl::includeInfo () const [inline], [virtual]
Implements ConceptDef.
Definition at line 119 of file conceptdef.cpp.
    { return getCdAlias()->includeInfo(); }
References getCdAlias(), and ConceptDef::includeInfo().
initializer() [1/2]
virtual QCString ConceptDefAliasImpl::initializer () const [inline], [virtual]
Implements ConceptDef.
Definition at line 129 of file conceptdef.cpp.
    { return getCdAlias()->initializer(); }
References getCdAlias(), and ConceptDef::initializer().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
initializer() [2/2]
virtual QCString ConceptDefAliasImpl::initializer () const [inline], [virtual]
Implements ConceptDef.
Definition at line 129 of file conceptdef.cpp.
    { return getCdAlias()->initializer(); }
References getCdAlias(), and ConceptDef::initializer().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
isLinkable() [1/2]
virtual bool ConceptDefAliasImpl::isLinkable () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements ConceptDef.
Definition at line 127 of file conceptdef.cpp.
    { return getCdAlias()->isLinkable(); }
References getCdAlias(), and ConceptDef::isLinkable().
isLinkable() [2/2]
virtual bool ConceptDefAliasImpl::isLinkable () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements ConceptDef.
Definition at line 127 of file conceptdef.cpp.
    { return getCdAlias()->isLinkable(); }
References getCdAlias(), and ConceptDef::isLinkable().
isLinkableInProject() [1/2]
virtual bool ConceptDefAliasImpl::isLinkableInProject () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements ConceptDef.
Definition at line 125 of file conceptdef.cpp.
    { return getCdAlias()->isLinkableInProject(); }
References getCdAlias(), and ConceptDef::isLinkableInProject().
isLinkableInProject() [2/2]
virtual bool ConceptDefAliasImpl::isLinkableInProject () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements ConceptDef.
Definition at line 125 of file conceptdef.cpp.
    { return getCdAlias()->isLinkableInProject(); }
References getCdAlias(), and ConceptDef::isLinkableInProject().
isReference() [1/2]
virtual bool ConceptDefAliasImpl::isReference () const [inline], [virtual]
Returns TRUE if this definition is imported via a tag file.
Reimplemented from DefinitionAliasMixin< ConceptDef >.
Definition at line 113 of file conceptdef.cpp.
    { return getCdAlias()->isReference(); }
References getCdAlias(), and Definition::isReference().
isReference() [2/2]
virtual bool ConceptDefAliasImpl::isReference () const [inline], [virtual]
Returns TRUE if this definition is imported via a tag file.
Reimplemented from DefinitionAliasMixin< ConceptDef >.
Definition at line 113 of file conceptdef.cpp.
    { return getCdAlias()->isReference(); }
References getCdAlias(), and Definition::isReference().
resolveAlias() [1/2]
virtual ConceptDef * ConceptDefAliasImpl::resolveAlias () [inline], [virtual]
Definition at line 104 of file conceptdef.cpp.
{ return const_cast<ConceptDef*>(getCdAlias()); }
References getCdAlias().
resolveAlias() [2/2]
virtual ConceptDef * ConceptDefAliasImpl::resolveAlias () [inline], [virtual]
Definition at line 104 of file conceptdef.cpp.
{ return const_cast<ConceptDef*>(getCdAlias()); }
References getCdAlias().
title() [1/2]
virtual QCString ConceptDefAliasImpl::title () const [inline], [virtual]
Implements ConceptDef.
Definition at line 135 of file conceptdef.cpp.
    { return getCdAlias()->title(); }
References getCdAlias(), and ConceptDef::title().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
virtual QCString ConceptDefAliasImpl::title () const [inline], [virtual]
Implements ConceptDef.
Definition at line 135 of file conceptdef.cpp.
    { return getCdAlias()->title(); }
References getCdAlias(), and ConceptDef::title().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
writeDeclarationLink() [1/2]
virtual void ConceptDefAliasImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const [inline], [virtual]
Implements ConceptDef.
Definition at line 137 of file conceptdef.cpp.
    { getCdAlias()->writeDeclarationLink(ol,found,header,localNames); }
References found, getCdAlias(), and ConceptDef::writeDeclarationLink().
writeDeclarationLink() [2/2]
virtual void ConceptDefAliasImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const [inline], [virtual]
Implements ConceptDef.
Definition at line 137 of file conceptdef.cpp.
    { getCdAlias()->writeDeclarationLink(ol,found,header,localNames); }
References found, getCdAlias(), and ConceptDef::writeDeclarationLink().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/conceptdef.cpp
doxygen/src/conceptdef.cpp