translator.TrManager Class Reference
Public Member Functions
def __init__ (self)
def getBgcolorByReadableStatus (self, readableStatus)
def generateTranslatorReport (self)
def generateLanguageDoc (self)
def __init__ (self)
def getBgcolorByReadableStatus (self, readableStatus)
def generateTranslatorReport (self)
def generateLanguageDoc (self)
Public Attributes
script
script_name
script_path
doxy_path
doc_path
src_path
org_src_path
org_doc_path
org_doxy_path
script_argLst
requiredMethodsDic
adaptMethodsDic
lastModificationTime
translatorReportFileName
maintainersFileName
languageTplFileName
languageDocFileName
langLst
supportedLangReadableStr
numLang
doxVersion
upToDateIdLst
EnBasedIdLst
adaptIdLst
Private Member Functions
def __build (self)
def __extractProcessedInfo (self)
def __getNoTrSourceFilesLst (self)
def __removeUsedInFiles (self, fname, dic)
def __checkForNotUsedTrMethods (self)
def __emails (self, classId)
def __loadMaintainers (self)
def __build (self)
def __extractProcessedInfo (self)
def __getNoTrSourceFilesLst (self)
def __removeUsedInFiles (self, fname, dic)
def __checkForNotUsedTrMethods (self)
def __emails (self, classId)
def __loadMaintainers (self)
Private Attributes
__translDic
__maintainersDic
Detailed Description
Collects basic info and builds subordinate Transl objects.
Definition at line 1209 of file translator.py.
Constructor & Destructor Documentation
__init__() [1/2]
def translator.TrManager.__init__ (self)
Determines paths, creates and initializes structures.

The arguments of the script may explicitly say what languages should
be processed. Write the two letter identifications that are used
for composing the source filenames, so...

    python translator.py cz

this will process only translator_cz.h source.
Definition at line 1212 of file translator.py.
    def __init__(self):
        """Determines paths, creates and initializes structures.
 
        The arguments of the script may explicitly say what languages should
        be processed. Write the two letter identifications that are used
        for composing the source filenames, so...
 
            python translator.py cz
 
        this will process only translator_cz.h source.
        """
 
        # Determine the path to the script and its name.
        self.script = os.path.abspath(sys.argv[0])
        self.script_path, self.script_name = os.path.split(self.script)
        self.script_path = os.path.abspath(self.script_path)
 
        # Determine the absolute path to the Doxygen's root subdirectory.
        # If DOXYGEN environment variable is not found, the directory is
        # determined from the path of the script.
        doxy_default = os.path.join(self.script_path, '..')
        self.doxy_path = os.path.abspath(os.getenv('DOXYGEN', doxy_default))
 
        # Build the path names based on the Doxygen's root knowledge.
        self.doc_path = os.path.join(self.doxy_path, 'doc')
        self.src_path = os.path.join(self.doxy_path, 'src')
        # Normally the original sources aren't in the current directory
        # (as we are in the build directory) so we have to specify the
        # original source /documentation / ... directory.
        self.org_src_path = self.src_path
        self.org_doc_path = self.doc_path
        self.org_doxy_path = self.doxy_path
        if (len(sys.argv) > 1 and os.path.isdir(os.path.join(sys.argv[1], 'src'))):
            self.org_src_path = os.path.join(sys.argv[1], 'src')
            self.org_doc_path = os.path.join(sys.argv[1], 'doc')
            self.org_doxy_path = sys.argv[1]
            # Get the explicit arguments of the script.
            self.script_argLst = sys.argv[2:]
        else:
            # Get the explicit arguments of the script.
            self.script_argLst = sys.argv[1:]
 
        # Create the empty dictionary for Transl object identified by the
        # class identifier of the translator.
        self.__translDic = {}
 
        # Create the None dictionary of required methods. The key is the
        # unified prototype, the value is the full prototype. Set inside
        # the self.__build().
        self.requiredMethodsDic = None
 
        # Create the empty dictionary that says what method is implemented
        # by what adapter.
        self.adaptMethodsDic = {}
 
        # The last modification time will capture the modification of this
        # script, of the translator.h, of the translator_adapter.h (see the
        # self.__build() for the last two) of all the translator_xx.h files
        # and of the template for generating the documentation. So, this
        # time can be compared with modification time of the generated
        # documentation to decide, whether the doc should be re-generated.
        self.lastModificationTime = os.path.getmtime(self.script)
 
        # Set the names of the translator report text file, of the template
        # for generating "Internationalization" document, for the generated
        # file itself, and for the maintainers list.
        self.translatorReportFileName = 'translator_report.txt'
        self.maintainersFileName = 'maintainers.txt'
        self.languageTplFileName = 'language.tpl'
        self.languageDocFileName = 'language.doc'
 
        # The information about the maintainers will be stored
        # in the dictionary with the following name.
        self.__maintainersDic = None
 
        # Define the other used structures and variables for information.
        self.langLst = None # including English based
        self.supportedLangReadableStr = None # coupled En-based as a note
        self.numLang = None # excluding coupled En-based
        self.doxVersion = None # Doxygen version
 
        # Build objects where each one is responsible for one translator.
        self.__build()
 
 
__init__() [2/2]
def translator.TrManager.__init__ (self)
Determines paths, creates and initializes structures.

The arguments of the script may explicitly say what languages should
be processed. Write the two letter identifications that are used
for composing the source filenames, so...

    python translator.py cz

this will process only translator_cz.h source.
Definition at line 1212 of file translator.py.
    def __init__(self):
        """Determines paths, creates and initializes structures.
 
        The arguments of the script may explicitly say what languages should
        be processed. Write the two letter identifications that are used
        for composing the source filenames, so...
 
            python translator.py cz
 
        this will process only translator_cz.h source.
        """
 
        # Determine the path to the script and its name.
        self.script = os.path.abspath(sys.argv[0])
        self.script_path, self.script_name = os.path.split(self.script)
        self.script_path = os.path.abspath(self.script_path)
 
        # Determine the absolute path to the Doxygen's root subdirectory.
        # If DOXYGEN environment variable is not found, the directory is
        # determined from the path of the script.
        doxy_default = os.path.join(self.script_path, '..')
        self.doxy_path = os.path.abspath(os.getenv('DOXYGEN', doxy_default))
 
        # Build the path names based on the Doxygen's root knowledge.
        self.doc_path = os.path.join(self.doxy_path, 'doc')
        self.src_path = os.path.join(self.doxy_path, 'src')
        # Normally the original sources aren't in the current directory
        # (as we are in the build directory) so we have to specify the
        # original source /documentation / ... directory.
        self.org_src_path = self.src_path
        self.org_doc_path = self.doc_path
        self.org_doxy_path = self.doxy_path
        if (len(sys.argv) > 1 and os.path.isdir(os.path.join(sys.argv[1], 'src'))):
            self.org_src_path = os.path.join(sys.argv[1], 'src')
            self.org_doc_path = os.path.join(sys.argv[1], 'doc')
            self.org_doxy_path = sys.argv[1]
            # Get the explicit arguments of the script.
            self.script_argLst = sys.argv[2:]
        else:
            # Get the explicit arguments of the script.
            self.script_argLst = sys.argv[1:]
 
        # Create the empty dictionary for Transl object identified by the
        # class identifier of the translator.
        self.__translDic = {}
 
        # Create the None dictionary of required methods. The key is the
        # unified prototype, the value is the full prototype. Set inside
        # the self.__build().
        self.requiredMethodsDic = None
 
        # Create the empty dictionary that says what method is implemented
        # by what adapter.
        self.adaptMethodsDic = {}
 
        # The last modification time will capture the modification of this
        # script, of the translator.h, of the translator_adapter.h (see the
        # self.__build() for the last two) of all the translator_xx.h files
        # and of the template for generating the documentation. So, this
        # time can be compared with modification time of the generated
        # documentation to decide, whether the doc should be re-generated.
        self.lastModificationTime = os.path.getmtime(self.script)
 
        # Set the names of the translator report text file, of the template
        # for generating "Internationalization" document, for the generated
        # file itself, and for the maintainers list.
        self.translatorReportFileName = 'translator_report.txt'
        self.maintainersFileName = 'maintainers.txt'
        self.languageTplFileName = 'language.tpl'
        self.languageDocFileName = 'language.doc'
 
        # The information about the maintainers will be stored
        # in the dictionary with the following name.
        self.__maintainersDic = None
 
        # Define the other used structures and variables for information.
        self.langLst = None # including English based
        self.supportedLangReadableStr = None # coupled En-based as a note
        self.numLang = None # excluding coupled En-based
        self.doxVersion = None # Doxygen version
 
        # Build objects where each one is responsible for one translator.
        self.__build()
 
 
References translator.TrManager.__build(), translator.TrManager.__maintainersDic, translator.TrManager.__translDic, translator.TrManager.adaptMethodsDic, translator.TrManager.doc_path, translator.TrManager.doxVersion, translator.TrManager.doxy_path, translator.TrManager.langLst, translator.TrManager.languageDocFileName, translator.TrManager.languageTplFileName, translator.TrManager.lastModificationTime, len, translator.TrManager.maintainersFileName, translator.TrManager.numLang, translator.TrManager.org_doc_path, translator.TrManager.org_doxy_path, translator.TrManager.org_src_path, translator.TrManager.requiredMethodsDic, translator.TrManager.script, translator.TrManager.script_argLst, translator.TrManager.script_name, translator.TrManager.script_path, translator.TrManager.src_path, translator.TrManager.supportedLangReadableStr, and translator.TrManager.translatorReportFileName.
Member Function Documentation
__build() [1/2]
def translator.TrManager.__build (self) [private]
Find the translator files and build the objects for translators.
Definition at line 1297 of file translator.py.
    def __build(self):
        """Find the translator files and build the objects for translators."""
 
        # The translator.h must exist (the Transl object will check it),
        # create the object for it and let it build the dictionary of
        # required methods.
        tr = Transl(os.path.join(self.org_src_path, 'translator.h'), self)
        self.requiredMethodsDic = tr.collectPureVirtualPrototypes()
        tim = tr.getmtime()
        if tim > self.lastModificationTime:
            self.lastModificationTime = tim
 
        # The translator_adapter.h must exist (the Transl object will check it),
        # create the object for it and store the reference in the dictionary.
        tr = Transl(os.path.join(self.org_src_path, 'translator_adapter.h'), self)
        self.adaptMethodsDic = tr.collectAdapterPrototypes()
        tim = tr.getmtime()
        if tim > self.lastModificationTime:
            self.lastModificationTime = tim
 
        # Create the list of the filenames with language translator sources.
        # If the explicit arguments of the script were typed, process only
        # those files.
        if self.script_argLst:
            lst = ['translator_' + x + '.h' for x in self.script_argLst]
            for fname in lst:
                if not os.path.isfile(os.path.join(self.org_src_path, fname)):
                    sys.stderr.write("\a\nFile '%s' not found!\n" % fname)
                    sys.exit(1)
        else:
            lst = os.listdir(self.org_src_path)
            lst = [x for x in lst if x[:11] == 'translator_'
                                   and x[-2:] == '.h'
                                   and x != 'translator_adapter.h']
 
        # Build the object for the translator_xx.h files, and process the
        # content of the file. Then insert the object to the dictionary
        # accessed via classId.
        for fname in lst:
            fullname = os.path.join(self.org_src_path, fname)
            tr = Transl(fullname, self)
            tr.processing()
            assert(tr.classId != 'Translator')
            self.__translDic[tr.classId] = tr
 
        # Extract the global information of the processed info.
        self.__extractProcessedInfo()
 
 
References translator.TrManager.__extractProcessedInfo(), translator.TrManager.__translDic, translator.TrManager.adaptMethodsDic, translator.TrManager.lastModificationTime, translator.TrManager.org_src_path, translator.TrManager.requiredMethodsDic, and translator.TrManager.script_argLst.
Referenced by translator.TrManager.__init__().
__build() [2/2]
def translator.TrManager.__build (self) [private]
Find the translator files and build the objects for translators.
Definition at line 1297 of file translator.py.
    def __build(self):
        """Find the translator files and build the objects for translators."""
 
        # The translator.h must exist (the Transl object will check it),
        # create the object for it and let it build the dictionary of
        # required methods.
        tr = Transl(os.path.join(self.org_src_path, 'translator.h'), self)
        self.requiredMethodsDic = tr.collectPureVirtualPrototypes()
        tim = tr.getmtime()
        if tim > self.lastModificationTime:
            self.lastModificationTime = tim
 
        # The translator_adapter.h must exist (the Transl object will check it),
        # create the object for it and store the reference in the dictionary.
        tr = Transl(os.path.join(self.org_src_path, 'translator_adapter.h'), self)
        self.adaptMethodsDic = tr.collectAdapterPrototypes()
        tim = tr.getmtime()
        if tim > self.lastModificationTime:
            self.lastModificationTime = tim
 
        # Create the list of the filenames with language translator sources.
        # If the explicit arguments of the script were typed, process only
        # those files.
        if self.script_argLst:
            lst = ['translator_' + x + '.h' for x in self.script_argLst]
            for fname in lst:
                if not os.path.isfile(os.path.join(self.org_src_path, fname)):
                    sys.stderr.write("\a\nFile '%s' not found!\n" % fname)
                    sys.exit(1)
        else:
            lst = os.listdir(self.org_src_path)
            lst = [x for x in lst if x[:11] == 'translator_'
                                   and x[-2:] == '.h'
                                   and x != 'translator_adapter.h']
 
        # Build the object for the translator_xx.h files, and process the
        # content of the file. Then insert the object to the dictionary
        # accessed via classId.
        for fname in lst:
            fullname = os.path.join(self.org_src_path, fname)
            tr = Transl(fullname, self)
            tr.processing()
            assert(tr.classId != 'Translator')
            self.__translDic[tr.classId] = tr
 
        # Extract the global information of the processed info.
        self.__extractProcessedInfo()
 
 
References translator.TrManager.__extractProcessedInfo(), translator.TrManager.__translDic, translator.TrManager.adaptMethodsDic, translator.TrManager.lastModificationTime, translator.TrManager.org_src_path, translator.TrManager.requiredMethodsDic, and translator.TrManager.script_argLst.
Referenced by translator.TrManager.__init__().
__checkForNotUsedTrMethods() [1/2]
def translator.TrManager.__checkForNotUsedTrMethods (self) [private]
Returns the dictionary of not used translator methods.

The method can be called only after self.requiredMethodsDic has been
built. The stripped prototypes are the values, the method identifiers
are the keys.
Definition at line 1476 of file translator.py.
    def __checkForNotUsedTrMethods(self):
        """Returns the dictionary of not used translator methods.
 
        The method can be called only after self.requiredMethodsDic has been
        built. The stripped prototypes are the values, the method identifiers
        are the keys.
        """
        # Build the dictionary of the required method prototypes with
        # method identifiers used as keys.
        trdic = {}
        for prototype in list(self.requiredMethodsDic.keys()):
            ri = prototype.split('(')[0]
            identifier = ri.split()[1].strip()
            trdic[identifier] = prototype
 
        # Build the list of source files where translator method identifiers
        # can be used.
        files = self.__getNoTrSourceFilesLst()
 
        # Loop through the files and reduce the dictionary of id -> proto.
        for fname in files:
            self.__removeUsedInFiles(fname, trdic)
 
        # Return the dictionary of not used translator methods.
        return trdic
 
 
References translator.TrManager.__getNoTrSourceFilesLst(), translator.TrManager.__removeUsedInFiles(), and translator.TrManager.requiredMethodsDic.
Referenced by translator.TrManager.generateTranslatorReport().
__checkForNotUsedTrMethods() [2/2]
def translator.TrManager.__checkForNotUsedTrMethods (self) [private]
Returns the dictionary of not used translator methods.

The method can be called only after self.requiredMethodsDic has been
built. The stripped prototypes are the values, the method identifiers
are the keys.
Definition at line 1476 of file translator.py.
    def __checkForNotUsedTrMethods(self):
        """Returns the dictionary of not used translator methods.
 
        The method can be called only after self.requiredMethodsDic has been
        built. The stripped prototypes are the values, the method identifiers
        are the keys.
        """
        # Build the dictionary of the required method prototypes with
        # method identifiers used as keys.
        trdic = {}
        for prototype in list(self.requiredMethodsDic.keys()):
            ri = prototype.split('(')[0]
            identifier = ri.split()[1].strip()
            trdic[identifier] = prototype
 
        # Build the list of source files where translator method identifiers
        # can be used.
        files = self.__getNoTrSourceFilesLst()
 
        # Loop through the files and reduce the dictionary of id -> proto.
        for fname in files:
            self.__removeUsedInFiles(fname, trdic)
 
        # Return the dictionary of not used translator methods.
        return trdic
 
 
References translator.TrManager.__getNoTrSourceFilesLst(), translator.TrManager.__removeUsedInFiles(), and translator.TrManager.requiredMethodsDic.
Referenced by translator.TrManager.generateTranslatorReport().
__emails() [1/2]
def translator.TrManager.__emails (self, classId) [private]
Returns the list of maintainer emails.

The method returns the list of e-mail addresses for the translator
class, but only the addresses that were not marked as [xxx].
Definition at line 1503 of file translator.py.
    def __emails(self, classId):
        """Returns the list of maintainer emails.
 
        The method returns the list of e-mail addresses for the translator
        class, but only the addresses that were not marked as [xxx]."""
        lst = []
        for m in self.__maintainersDic[classId]:
            if not m[1].startswith('['):
                email = m[1]
                email = email.replace(' at ', '@') # Unmangle the mangled e-mail
                email = email.replace(' dot ', '.')
                lst.append(email)
        return lst
 
 
References translator.TrManager.__maintainersDic.
Referenced by translator.TrManager.generateTranslatorReport().
__emails() [2/2]
def translator.TrManager.__emails (self, classId) [private]
Returns the list of maintainer emails.

The method returns the list of e-mail addresses for the translator
class, but only the addresses that were not marked as [xxx].
Definition at line 1503 of file translator.py.
    def __emails(self, classId):
        """Returns the list of maintainer emails.
 
        The method returns the list of e-mail addresses for the translator
        class, but only the addresses that were not marked as [xxx]."""
        lst = []
        for m in self.__maintainersDic[classId]:
            if not m[1].startswith('['):
                email = m[1]
                email = email.replace(' at ', '@') # Unmangle the mangled e-mail
                email = email.replace(' dot ', '.')
                lst.append(email)
        return lst
 
 
References translator.TrManager.__maintainersDic.
Referenced by translator.TrManager.generateTranslatorReport().
__extractProcessedInfo() [1/2]
def translator.TrManager.__extractProcessedInfo (self) [private]
Build lists and strings of the processed info.
Definition at line 1346 of file translator.py.
    def __extractProcessedInfo(self):
        """Build lists and strings of the processed info."""
 
        # Build the auxiliary list with strings compound of the status,
        # readable form of the language, and classId.
        statLst = []
        for obj in list(self.__translDic.values()):
            assert(obj.classId != 'Translator')
            s = obj.status + '|' + obj.langReadable + '|' + obj.classId
            statLst.append(s)
 
        # Sort the list and extract the object identifiers (classId's) for
        # the up-to-date translators and English-based translators.
        statLst.sort()
        self.upToDateIdLst = [x.split('|')[2] for x in statLst if x[0] == '|']
        self.EnBasedIdLst = [x.split('|')[2] for x in statLst if x[:2] == 'En']
 
        # Reverse the list and extract the TranslatorAdapter based translators.
        statLst.reverse()
        self.adaptIdLst = [x.split('|')[2] for x in statLst if x[0].isdigit()]
 
        # Build the list of tuples that contain (langReadable, obj).
        # Sort it by readable name.
        self.langLst = []
        for obj in list(self.__translDic.values()):
            self.langLst.append((obj.langReadable, obj))
 
        self.langLst.sort(key=lambda x: x[0])
 
        # Create the list with readable language names. If the language has
        # also the English-based version, modify the item by appending
        # the note. Number of the supported languages is equal to the length
        # of the list.
        langReadableLst = []
        for name, obj in self.langLst:
            if obj.status == 'En': continue
 
            # Append the 'En' to the classId to possibly obtain the classId
            # of the English-based object. If the object exists, modify the
            # name for the readable list of supported languages.
            classIdEn = obj.classId + 'En'
            if classIdEn in self.__translDic:
                name += ' (+En)'
 
            # Append the result name of the language, possibly with note.
            langReadableLst.append(name)
 
        # Create the multiline string of readable language names,
        # with punctuation, wrapped to paragraph.
        if len(langReadableLst) == 1:
            s = langReadableLst[0]
        elif len(langReadableLst) == 2:
            s = ' and '.join(langReadableLst)
        else:
            s = ', '.join(langReadableLst[:-1]) + ', and '
            s += langReadableLst[-1]
 
        self.supportedLangReadableStr = fill(s + '.')
 
        # Find the number of the supported languages. The English based
        # languages are not counted if the non-English based also exists.
        self.numLang = len(self.langLst)
        for name, obj in self.langLst:
            if obj.status == 'En':
                classId = obj.classId[:-2]
                if classId in self.__translDic:
                    self.numLang -= 1 # the couple will be counted as one
 
        # Extract the version of Doxygen.
        f = xopen(os.path.join(self.org_doxy_path, 'VERSION'))
        self.doxVersion = f.readline().strip()
        f.close()
 
        # Update the last modification time.
        for tr in list(self.__translDic.values()):
            tim = tr.getmtime()
            if tim > self.lastModificationTime:
                self.lastModificationTime = tim
 
 
References translator.TrManager.__translDic.
Referenced by translator.TrManager.__build().
__extractProcessedInfo() [2/2]
def translator.TrManager.__extractProcessedInfo (self) [private]
Build lists and strings of the processed info.
Definition at line 1346 of file translator.py.
    def __extractProcessedInfo(self):
        """Build lists and strings of the processed info."""
 
        # Build the auxiliary list with strings compound of the status,
        # readable form of the language, and classId.
        statLst = []
        for obj in list(self.__translDic.values()):
            assert(obj.classId != 'Translator')
            s = obj.status + '|' + obj.langReadable + '|' + obj.classId
            statLst.append(s)
 
        # Sort the list and extract the object identifiers (classId's) for
        # the up-to-date translators and English-based translators.
        statLst.sort()
        self.upToDateIdLst = [x.split('|')[2] for x in statLst if x[0] == '|']
        self.EnBasedIdLst = [x.split('|')[2] for x in statLst if x[:2] == 'En']
 
        # Reverse the list and extract the TranslatorAdapter based translators.
        statLst.reverse()
        self.adaptIdLst = [x.split('|')[2] for x in statLst if x[0].isdigit()]
 
        # Build the list of tuples that contain (langReadable, obj).
        # Sort it by readable name.
        self.langLst = []
        for obj in list(self.__translDic.values()):
            self.langLst.append((obj.langReadable, obj))
 
        self.langLst.sort(key=lambda x: x[0])
 
        # Create the list with readable language names. If the language has
        # also the English-based version, modify the item by appending
        # the note. Number of the supported languages is equal to the length
        # of the list.
        langReadableLst = []
        for name, obj in self.langLst:
            if obj.status == 'En': continue
 
            # Append the 'En' to the classId to possibly obtain the classId
            # of the English-based object. If the object exists, modify the
            # name for the readable list of supported languages.
            classIdEn = obj.classId + 'En'
            if classIdEn in self.__translDic:
                name += ' (+En)'
 
            # Append the result name of the language, possibly with note.
            langReadableLst.append(name)
 
        # Create the multiline string of readable language names,
        # with punctuation, wrapped to paragraph.
        if len(langReadableLst) == 1:
            s = langReadableLst[0]
        elif len(langReadableLst) == 2:
            s = ' and '.join(langReadableLst)
        else:
            s = ', '.join(langReadableLst[:-1]) + ', and '
            s += langReadableLst[-1]
 
        self.supportedLangReadableStr = fill(s + '.')
 
        # Find the number of the supported languages. The English based
        # languages are not counted if the non-English based also exists.
        self.numLang = len(self.langLst)
        for name, obj in self.langLst:
            if obj.status == 'En':
                classId = obj.classId[:-2]
                if classId in self.__translDic:
                    self.numLang -= 1 # the couple will be counted as one
 
        # Extract the version of Doxygen.
        f = xopen(os.path.join(self.org_doxy_path, 'VERSION'))
        self.doxVersion = f.readline().strip()
        f.close()
 
        # Update the last modification time.
        for tr in list(self.__translDic.values()):
            tim = tr.getmtime()
            if tim > self.lastModificationTime:
                self.lastModificationTime = tim
 
 
References translator.TrManager.__translDic, translator.TrManager.adaptIdLst, translator.TrManager.doxVersion, translator.TrManager.EnBasedIdLst, translator.fill(), reg.isdigit(), join(), translator.TrManager.langLst, translator.TrManager.lastModificationTime, len, translator.TrManager.numLang, translator.TrManager.org_doxy_path, translator.TrManager.supportedLangReadableStr, translator.TrManager.upToDateIdLst, and translator.xopen().
Referenced by translator.TrManager.__build().
__getNoTrSourceFilesLst() [1/2]
def translator.TrManager.__getNoTrSourceFilesLst (self) [private]
Returns the list of sources to be checked.

All .cpp files and also .h files that do not declare or define
the translator methods are included in the list. The file names
are searched in doxygen/src directory.
Definition at line 1426 of file translator.py.
    def __getNoTrSourceFilesLst(self):
        """Returns the list of sources to be checked.
 
        All .cpp files and also .h files that do not declare or define
        the translator methods are included in the list. The file names
        are searched in doxygen/src directory.
        """
        files = []
        for item in os.listdir(self.org_src_path):
            # Split the bare name to get the extension.
            name, ext = os.path.splitext(item)
            ext = ext.lower()
 
            # Include only .cpp and .h files (case independent) and exclude
            # the files where the checked identifiers are defined.
            if ext == '.cpp' or ext == '.l' or (ext == '.h' and name.find('translator') == -1):
                fname = os.path.join(self.org_src_path, item)
                assert os.path.isfile(fname) # assumes no directory with the ext
                files.append(fname) # full name
        return files
 
 
References translator.TrManager.org_src_path.
Referenced by translator.TrManager.__checkForNotUsedTrMethods().
__getNoTrSourceFilesLst() [2/2]
def translator.TrManager.__getNoTrSourceFilesLst (self) [private]
Returns the list of sources to be checked.

All .cpp files and also .h files that do not declare or define
the translator methods are included in the list. The file names
are searched in doxygen/src directory.
Definition at line 1426 of file translator.py.
    def __getNoTrSourceFilesLst(self):
        """Returns the list of sources to be checked.
 
        All .cpp files and also .h files that do not declare or define
        the translator methods are included in the list. The file names
        are searched in doxygen/src directory.
        """
        files = []
        for item in os.listdir(self.org_src_path):
            # Split the bare name to get the extension.
            name, ext = os.path.splitext(item)
            ext = ext.lower()
 
            # Include only .cpp and .h files (case independent) and exclude
            # the files where the checked identifiers are defined.
            if ext == '.cpp' or ext == '.l' or (ext == '.h' and name.find('translator') == -1):
                fname = os.path.join(self.org_src_path, item)
                assert os.path.isfile(fname) # assumes no directory with the ext
                files.append(fname) # full name
        return files
 
 
References translator.TrManager.org_src_path.
Referenced by translator.TrManager.__checkForNotUsedTrMethods().
__loadMaintainers() [1/2]
def translator.TrManager.__loadMaintainers (self) [private]
Load and process the file with the maintainers.

Fills the dictionary classId -> [(name, e-mail), ...].
Definition at line 1728 of file translator.py.
    def __loadMaintainers(self):
        """Load and process the file with the maintainers.
 
        Fills the dictionary classId -> [(name, e-mail), ...]."""
 
        fname = os.path.join(self.org_doc_path, self.maintainersFileName)
 
        # Include the maintainers file to the group of files checked with
        # respect to the modification time.
        tim = os.path.getmtime(fname)
        if tim > self.lastModificationTime:
            self.lastModificationTime = tim
 
        # Process the content of the maintainers file.
        f = xopen(fname)
        inside = False # inside the record for the language
        lineReady = True
        classId = None
        maintainersLst = None
        self.__maintainersDic = {}
        while lineReady:
            line = f.readline() # next line
            lineReady = line != '' # when eof, then line == ''
 
            line = line.strip() # eof should also behave as separator
            if line != '' and line[0] == '%': # skip the comment line
                continue
 
            if not inside: # if outside of the record
                if line != '': # should be language identifier
                    classId = line
                    maintainersLst = []
                    inside = True
                # Otherwise skip empty line that do not act as separator.
 
            else: # if inside the record
                if line == '': # separator found
                    inside = False
                else:
                    # If it is the first maintainer, create the empty list.
                    if classId not in self.__maintainersDic:
                        self.__maintainersDic[classId] = []
 
                    # Split the information about the maintainer and append
                    # the tuple. The address may be prefixed '[unreachable]'
                    # or whatever '[xxx]'. This will be processed later.
                    lst = line.split(':', 1)
                    assert(len(lst) == 2)
                    t = (lst[0].strip(), lst[1].strip())
                    self.__maintainersDic[classId].append(t)
        f.close()
 
 
References translator.TrManager.__maintainersDic, translator.TrManager.lastModificationTime, len, translator.TrManager.maintainersFileName, translator.TrManager.org_doc_path, and translator.xopen().
Referenced by translator.TrManager.generateLanguageDoc().
__loadMaintainers() [2/2]
def translator.TrManager.__loadMaintainers (self) [private]
Load and process the file with the maintainers.

Fills the dictionary classId -> [(name, e-mail), ...].
Definition at line 1728 of file translator.py.
    def __loadMaintainers(self):
        """Load and process the file with the maintainers.
 
        Fills the dictionary classId -> [(name, e-mail), ...]."""
 
        fname = os.path.join(self.org_doc_path, self.maintainersFileName)
 
        # Include the maintainers file to the group of files checked with
        # respect to the modification time.
        tim = os.path.getmtime(fname)
        if tim > self.lastModificationTime:
            self.lastModificationTime = tim
 
        # Process the content of the maintainers file.
        f = xopen(fname)
        inside = False # inside the record for the language
        lineReady = True
        classId = None
        maintainersLst = None
        self.__maintainersDic = {}
        while lineReady:
            line = f.readline() # next line
            lineReady = line != '' # when eof, then line == ''
 
            line = line.strip() # eof should also behave as separator
            if line != '' and line[0] == '%': # skip the comment line
                continue
 
            if not inside: # if outside of the record
                if line != '': # should be language identifier
                    classId = line
                    maintainersLst = []
                    inside = True
                # Otherwise skip empty line that do not act as separator.
 
            else: # if inside the record
                if line == '': # separator found
                    inside = False
                else:
                    # If it is the first maintainer, create the empty list.
                    if classId not in self.__maintainersDic:
                        self.__maintainersDic[classId] = []
 
                    # Split the information about the maintainer and append
                    # the tuple. The address may be prefixed '[unreachable]'
                    # or whatever '[xxx]'. This will be processed later.
                    lst = line.split(':', 1)
                    assert(len(lst) == 2)
                    t = (lst[0].strip(), lst[1].strip())
                    self.__maintainersDic[classId].append(t)
        f.close()
 
 
References translator.TrManager.__maintainersDic, translator.TrManager.lastModificationTime, len, translator.TrManager.maintainersFileName, translator.TrManager.org_doc_path, and translator.xopen().
Referenced by translator.TrManager.generateLanguageDoc().
__removeUsedInFiles() [1/2]
def translator.TrManager.__removeUsedInFiles (self, fname, dic) [private]
Removes items for method identifiers that are found in fname.

The method reads the content of the file as one string and searches
for all identifiers from dic. The identifiers that were found in
the file are removed from the dictionary.

Note: If more files is to be checked, the files where most items are
probably used should be checked first and the resulting reduced
dictionary should be used for checking the next files (speed up).
Definition at line 1448 of file translator.py.
    def __removeUsedInFiles(self, fname, dic):
        """Removes items for method identifiers that are found in fname.
 
        The method reads the content of the file as one string and searches
        for all identifiers from dic. The identifiers that were found in
        the file are removed from the dictionary.
 
        Note: If more files is to be checked, the files where most items are
        probably used should be checked first and the resulting reduced
        dictionary should be used for checking the next files (speed up).
        """
        lst_in = list(dic.keys()) # identifiers to be searched for
 
        # Read content of the file as one string.
        assert os.path.isfile(fname)
        f = xopen(fname)
        cont = f.read()
        cont = ''.join(cont.split('\n')) # otherwise the 'match' function won't work.
        f.close()
 
        # Remove the items for identifiers that were found in the file.
        while lst_in:
            item = lst_in.pop(0)
            rexItem = re.compile('.*' + item + ' *\(')
            if rexItem.match(cont):
                del dic[item]
 
 
References join(), and translator.xopen().
Referenced by translator.TrManager.__checkForNotUsedTrMethods().
__removeUsedInFiles() [2/2]
def translator.TrManager.__removeUsedInFiles (self, fname, dic) [private]
Removes items for method identifiers that are found in fname.

The method reads the content of the file as one string and searches
for all identifiers from dic. The identifiers that were found in
the file are removed from the dictionary.

Note: If more files is to be checked, the files where most items are
probably used should be checked first and the resulting reduced
dictionary should be used for checking the next files (speed up).
Definition at line 1448 of file translator.py.
    def __removeUsedInFiles(self, fname, dic):
        """Removes items for method identifiers that are found in fname.
 
        The method reads the content of the file as one string and searches
        for all identifiers from dic. The identifiers that were found in
        the file are removed from the dictionary.
 
        Note: If more files is to be checked, the files where most items are
        probably used should be checked first and the resulting reduced
        dictionary should be used for checking the next files (speed up).
        """
        lst_in = list(dic.keys()) # identifiers to be searched for
 
        # Read content of the file as one string.
        assert os.path.isfile(fname)
        f = xopen(fname)
        cont = f.read()
        cont = ''.join(cont.split('\n')) # otherwise the 'match' function won't work.
        f.close()
 
        # Remove the items for identifiers that were found in the file.
        while lst_in:
            item = lst_in.pop(0)
            rexItem = re.compile('.*' + item + ' *\(')
            if rexItem.match(cont):
                del dic[item]
 
 
References join(), and translator.xopen().
Referenced by translator.TrManager.__checkForNotUsedTrMethods().
generateLanguageDoc() [1/2]
def translator.TrManager.generateLanguageDoc (self)
Checks the modtime of files and generates language.doc.
Definition at line 1781 of file translator.py.
    def generateLanguageDoc(self):
        """Checks the modtime of files and generates language.doc."""
        self.__loadMaintainers()
 
        # Check the last modification time of the VERSION file.
        fVerName = os.path.join(self.org_doxy_path, "VERSION")
        tim = os.path.getmtime(fVerName)
        if tim > self.lastModificationTime:
            self.lastModificationTime = tim
 
        # Check the last modification time of the template file. It is the
        # last file from the group that decide whether the documentation
        # should or should not be generated.
        fTplName = os.path.join(self.org_doc_path, self.languageTplFileName)
        tim = os.path.getmtime(fTplName)
        if tim > self.lastModificationTime:
            self.lastModificationTime = tim
 
        # If the generated documentation exists and is newer than any of
        # the source files from the group, do not generate it and quit
        # quietly.
        fDocName = os.path.join(self.doc_path, self.languageDocFileName)
        if os.path.isfile(fDocName):
            if os.path.getmtime(fDocName) > self.lastModificationTime:
                return
 
        # The document or does not exist or is older than some of the
        # sources. It must be generated again.
        #
        # Read the template of the documentation, and remove the first
        # attention lines.
        f = xopen(fTplName)
        doctpl = f.read()
        f.close()
 
        pos = doctpl.find('/***')
        assert pos != -1
        doctpl = doctpl[pos:]
 
        # Fill the tplDic by symbols that will be inserted into the
        # document template.
        tplDic = {}
 
        s = ('Do not edit this file. It was generated by the %s script.\n' +\
             ' * Edit the %s and %s files instead.') % (
             self.script_name, self.languageTplFileName, self.maintainersFileName)
        tplDic['editnote'] = s
 
        tplDic['doxVersion'] = self.doxVersion
        tplDic['supportedLangReadableStr'] = self.supportedLangReadableStr
        tplDic['translatorReportFileName'] = self.translatorReportFileName
 
        ahref = '<a href="' + self.translatorReportFileName
        ahref += '"\n><code>' + self.translatorReportFileName + '</code></a>'
        tplDic['translatorReportLink'] = ahref
        tplDic['numLangStr'] = str(self.numLang)
 
        # Define templates for HTML table parts of the documentation.
        htmlTableTpl = '''
            \\htmlonly
            </p>
            <table align="center" cellspacing="0" cellpadding="0" border="0">
            <tr bgcolor="#000000">
            <td>
              <table cellspacing="1" cellpadding="2" border="0">
              <tr bgcolor="#4040c0">
              <td ><b><font size="+1" color="#ffffff"> Language </font></b></td>
              <td ><b><font size="+1" color="#ffffff"> Maintainer </font></b></td>
              <td ><b><font size="+1" color="#ffffff"> Contact address </font>
                      <font size="-2" color="#ffffff">(replace the at and dot)</font></b></td>
              <td ><b><font size="+1" color="#ffffff"> Status </font></b></td>
              </tr>
              <!-- table content begin -->
            %s
              <!-- table content end -->
              </table>
            </td>
            </tr>
            </table>
            <p>
            \\endhtmlonly
            '''
        htmlTableTpl = textwrap.dedent(htmlTableTpl)
        htmlTrTpl = '\n <tr bgcolor="#ffffff">%s\n </tr>'
        htmlTdTpl = '\n <td>%s</td>'
        htmlTdStatusColorTpl = '\n <td bgcolor="%s">%s</td>'
 
        # Loop through transl objects in the order of sorted readable names
        # and add generate the content of the HTML table.
        trlst = []
        for name, obj in self.langLst:
            # Fill the table data elements for one row. The first element
            # contains the readable name of the language. Only the oldest
            # translator are colour marked in the language column. Less
            # "heavy" color is used (when compared with the Status column).
            if obj.readableStatus.startswith('1.4'):
                bkcolor = self.getBgcolorByReadableStatus('1.4')
            else:
                bkcolor = '#ffffff'
 
            lst = [ htmlTdStatusColorTpl % (bkcolor, obj.langReadable) ]
 
            # The next two elements contain the list of maintainers
            # and the list of their mangled e-mails. For English-based
            # translators that are coupled with the non-English based,
            # insert the 'see' note.
            mm = None # init -- maintainer
            ee = None # init -- e-mail address
            if obj.status == 'En':
                # Check whether there is the coupled non-English.
                classId = obj.classId[:-2]
                if classId in self.__translDic:
                    lang = self.__translDic[classId].langReadable
                    mm = 'see the %s language' % lang
                    ee = '&#160;'
 
            if not mm and obj.classId in self.__maintainersDic:
                # Build a string of names separated by the HTML break element.
                # Special notes used instead of names are highlighted.
                lm = []
                for maintainer in self.__maintainersDic[obj.classId]:
                    name = maintainer[0]
                    if name.startswith('--'):
                        name = '<span style="color: red; background-color: yellow">'\
                               + name + '</span>'
                    lm.append(name)
                mm = '<br/>'.join(lm)
 
                # The marked addresses (they start with the mark '[unreachable]',
                # '[resigned]', whatever '[xxx]') will not be displayed at all.
                # Only the mark will be used instead.
                rexMark = re.compile('(?P<mark>\\[.*?\\])')
                le = []
                for maintainer in self.__maintainersDic[obj.classId]:
                    address = maintainer[1]
                    m = rexMark.search(address)
                    if m is not None:
                        address = '<span style="color: brown">'\
                                  + m.group('mark') + '</span>'
                    le.append(address)
                ee = '<br/>'.join(le)
 
            # Append the maintainer and e-mail elements.
            lst.append(htmlTdTpl % mm)
            lst.append(htmlTdTpl % ee)
 
            # The last element contains the readable form of the status.
            bgcolor = self.getBgcolorByReadableStatus(obj.readableStatus)
            lst.append(htmlTdStatusColorTpl % (bgcolor, obj.readableStatus))
 
            # Join the table data to one table row.
            trlst.append(htmlTrTpl % (''.join(lst)))
 
        # Join the table rows and insert into the template.
        htmlTable = htmlTableTpl % (''.join(trlst))
 
        # Define templates for LaTeX table parts of the documentation.
        latexTableTpl = r'''
            \latexonly
            \footnotesize
            \begin{longtable}{|l|l|l|l|}
              \hline
              {\bf Language} & {\bf Maintainer} & {\bf Contact address} & {\bf Status} \\
              \hline
            %s
              \hline
            \end{longtable}
            \normalsize
            \endlatexonly
            '''
        latexTableTpl = textwrap.dedent(latexTableTpl)
        latexLineTpl = '\n' + r' %s & %s & {\tt\tiny %s} & %s \\'
 
        # Loop through transl objects in the order of sorted readable names
        # and add generate the content of the LaTeX table.
        trlst = []
        for name, obj in self.langLst:
            # For LaTeX, more maintainers for the same language are
            # placed on separate rows in the table. The line separator
            # in the table is placed explicitly above the first
            # maintainer. Prepare the arguments for the LaTeX row template.
            maintainers = []
            if obj.classId in self.__maintainersDic:
                maintainers = self.__maintainersDic[obj.classId]
 
            lang = obj.langReadable
            maintainer = None # init
            email = None # init
            if obj.status == 'En':
                # Check whether there is the coupled non-English.
                classId = obj.classId[:-2]
                if classId in self.__translDic:
                    langNE = self.__translDic[classId].langReadable
                    maintainer = 'see the %s language' % langNE
                    email = '~'
 
            if not maintainer and (obj.classId in self.__maintainersDic):
                lm = [ m[0] for m in self.__maintainersDic[obj.classId] ]
                maintainer = maintainers[0][0]
                email = maintainers[0][1]
 
            status = obj.readableStatus
 
            # Use the template to produce the line of the table and insert
            # the hline plus the constructed line into the table content.
            # The underscore character must be escaped.
            trlst.append('\n \\hline')
            s = latexLineTpl % (lang, maintainer, email, status)
            s = s.replace('_', '\\_')
            trlst.append(s)
 
            # List the other maintainers for the language. Do not set
            # lang and status for them.
            lang = '~'
            status = '~'
            for m in maintainers[1:]:
                maintainer = m[0]
                email = m[1]
                s = latexLineTpl % (lang, maintainer, email, status)
                s = s.replace('_', '\\_')
                trlst.append(s)
 
        # Join the table lines and insert into the template.
        latexTable = latexTableTpl % (''.join(trlst))
 
        # Put the HTML and LaTeX parts together and define the dic item.
        tplDic['informationTable'] = htmlTable + '\n' + latexTable
 
        # Insert the symbols into the document template and write it down.
        f = xopen(fDocName, 'w')
        f.write(doctpl % tplDic)
        f.close()
 
References translator.TrManager.__loadMaintainers(), translator.TrManager.__maintainersDic, translator.TrManager.__translDic, translator.TrManager.doc_path, translator.TrManager.doxVersion, translator.TrManager.getBgcolorByReadableStatus(), join(), translator.TrManager.langLst, translator.TrManager.languageDocFileName, translator.TrManager.languageTplFileName, translator.TrManager.lastModificationTime, translator.TrManager.maintainersFileName, translator.TrManager.numLang, translator.TrManager.org_doc_path, translator.TrManager.org_doxy_path, translator.TrManager.script_name, translator.TrManager.supportedLangReadableStr, translator.TrManager.translatorReportFileName, and translator.xopen().
generateLanguageDoc() [2/2]
def translator.TrManager.generateLanguageDoc (self)
Checks the modtime of files and generates language.doc.
Definition at line 1781 of file translator.py.
    def generateLanguageDoc(self):
        """Checks the modtime of files and generates language.doc."""
        self.__loadMaintainers()
 
        # Check the last modification time of the VERSION file.
        fVerName = os.path.join(self.org_doxy_path, "VERSION")
        tim = os.path.getmtime(fVerName)
        if tim > self.lastModificationTime:
            self.lastModificationTime = tim
 
        # Check the last modification time of the template file. It is the
        # last file from the group that decide whether the documentation
        # should or should not be generated.
        fTplName = os.path.join(self.org_doc_path, self.languageTplFileName)
        tim = os.path.getmtime(fTplName)
        if tim > self.lastModificationTime:
            self.lastModificationTime = tim
 
        # If the generated documentation exists and is newer than any of
        # the source files from the group, do not generate it and quit
        # quietly.
        fDocName = os.path.join(self.doc_path, self.languageDocFileName)
        if os.path.isfile(fDocName):
            if os.path.getmtime(fDocName) > self.lastModificationTime:
                return
 
        # The document or does not exist or is older than some of the
        # sources. It must be generated again.
        #
        # Read the template of the documentation, and remove the first
        # attention lines.
        f = xopen(fTplName)
        doctpl = f.read()
        f.close()
 
        pos = doctpl.find('/***')
        assert pos != -1
        doctpl = doctpl[pos:]
 
        # Fill the tplDic by symbols that will be inserted into the
        # document template.
        tplDic = {}
 
        s = ('Do not edit this file. It was generated by the %s script.\n' +\
             ' * Edit the %s and %s files instead.') % (
             self.script_name, self.languageTplFileName, self.maintainersFileName)
        tplDic['editnote'] = s
 
        tplDic['doxVersion'] = self.doxVersion
        tplDic['supportedLangReadableStr'] = self.supportedLangReadableStr
        tplDic['translatorReportFileName'] = self.translatorReportFileName
 
        ahref = '<a href="' + self.translatorReportFileName
        ahref += '"\n><code>' + self.translatorReportFileName + '</code></a>'
        tplDic['translatorReportLink'] = ahref
        tplDic['numLangStr'] = str(self.numLang)
 
        # Define templates for HTML table parts of the documentation.
        htmlTableTpl = '''
            \\htmlonly
            </p>
            <table align="center" cellspacing="0" cellpadding="0" border="0">
            <tr bgcolor="#000000">
            <td>
              <table cellspacing="1" cellpadding="2" border="0">
              <tr bgcolor="#4040c0">
              <td ><b><font size="+1" color="#ffffff"> Language </font></b></td>
              <td ><b><font size="+1" color="#ffffff"> Maintainer </font></b></td>
              <td ><b><font size="+1" color="#ffffff"> Contact address </font>
                      <font size="-2" color="#ffffff">(replace the at and dot)</font></b></td>
              <td ><b><font size="+1" color="#ffffff"> Status </font></b></td>
              </tr>
              <!-- table content begin -->
            %s
              <!-- table content end -->
              </table>
            </td>
            </tr>
            </table>
            <p>
            \\endhtmlonly
            '''
        htmlTableTpl = textwrap.dedent(htmlTableTpl)
        htmlTrTpl = '\n <tr bgcolor="#ffffff">%s\n </tr>'
        htmlTdTpl = '\n <td>%s</td>'
        htmlTdStatusColorTpl = '\n <td bgcolor="%s">%s</td>'
 
        # Loop through transl objects in the order of sorted readable names
        # and add generate the content of the HTML table.
        trlst = []
        for name, obj in self.langLst:
            # Fill the table data elements for one row. The first element
            # contains the readable name of the language. Only the oldest
            # translator are colour marked in the language column. Less
            # "heavy" color is used (when compared with the Status column).
            if obj.readableStatus.startswith('1.4'):
                bkcolor = self.getBgcolorByReadableStatus('1.4')
            else:
                bkcolor = '#ffffff'
 
            lst = [ htmlTdStatusColorTpl % (bkcolor, obj.langReadable) ]
 
            # The next two elements contain the list of maintainers
            # and the list of their mangled e-mails. For English-based
            # translators that are coupled with the non-English based,
            # insert the 'see' note.
            mm = None # init -- maintainer
            ee = None # init -- e-mail address
            if obj.status == 'En':
                # Check whether there is the coupled non-English.
                classId = obj.classId[:-2]
                if classId in self.__translDic:
                    lang = self.__translDic[classId].langReadable
                    mm = 'see the %s language' % lang
                    ee = '&#160;'
 
            if not mm and obj.classId in self.__maintainersDic:
                # Build a string of names separated by the HTML break element.
                # Special notes used instead of names are highlighted.
                lm = []
                for maintainer in self.__maintainersDic[obj.classId]:
                    name = maintainer[0]
                    if name.startswith('--'):
                        name = '<span style="color: red; background-color: yellow">'\
                               + name + '</span>'
                    lm.append(name)
                mm = '<br/>'.join(lm)
 
                # The marked addresses (they start with the mark '[unreachable]',
                # '[resigned]', whatever '[xxx]') will not be displayed at all.
                # Only the mark will be used instead.
                rexMark = re.compile('(?P<mark>\\[.*?\\])')
                le = []
                for maintainer in self.__maintainersDic[obj.classId]:
                    address = maintainer[1]
                    m = rexMark.search(address)
                    if m is not None:
                        address = '<span style="color: brown">'\
                                  + m.group('mark') + '</span>'
                    le.append(address)
                ee = '<br/>'.join(le)
 
            # Append the maintainer and e-mail elements.
            lst.append(htmlTdTpl % mm)
            lst.append(htmlTdTpl % ee)
 
            # The last element contains the readable form of the status.
            bgcolor = self.getBgcolorByReadableStatus(obj.readableStatus)
            lst.append(htmlTdStatusColorTpl % (bgcolor, obj.readableStatus))
 
            # Join the table data to one table row.
            trlst.append(htmlTrTpl % (''.join(lst)))
 
        # Join the table rows and insert into the template.
        htmlTable = htmlTableTpl % (''.join(trlst))
 
        # Define templates for LaTeX table parts of the documentation.
        latexTableTpl = r'''
            \latexonly
            \footnotesize
            \begin{longtable}{|l|l|l|l|}
              \hline
              {\bf Language} & {\bf Maintainer} & {\bf Contact address} & {\bf Status} \\
              \hline
            %s
              \hline
            \end{longtable}
            \normalsize
            \endlatexonly
            '''
        latexTableTpl = textwrap.dedent(latexTableTpl)
        latexLineTpl = '\n' + r' %s & %s & {\tt\tiny %s} & %s \\'
 
        # Loop through transl objects in the order of sorted readable names
        # and add generate the content of the LaTeX table.
        trlst = []
        for name, obj in self.langLst:
            # For LaTeX, more maintainers for the same language are
            # placed on separate rows in the table. The line separator
            # in the table is placed explicitly above the first
            # maintainer. Prepare the arguments for the LaTeX row template.
            maintainers = []
            if obj.classId in self.__maintainersDic:
                maintainers = self.__maintainersDic[obj.classId]
 
            lang = obj.langReadable
            maintainer = None # init
            email = None # init
            if obj.status == 'En':
                # Check whether there is the coupled non-English.
                classId = obj.classId[:-2]
                if classId in self.__translDic:
                    langNE = self.__translDic[classId].langReadable
                    maintainer = 'see the %s language' % langNE
                    email = '~'
 
            if not maintainer and (obj.classId in self.__maintainersDic):
                lm = [ m[0] for m in self.__maintainersDic[obj.classId] ]
                maintainer = maintainers[0][0]
                email = maintainers[0][1]
 
            status = obj.readableStatus
 
            # Use the template to produce the line of the table and insert
            # the hline plus the constructed line into the table content.
            # The underscore character must be escaped.
            trlst.append('\n \\hline')
            s = latexLineTpl % (lang, maintainer, email, status)
            s = s.replace('_', '\\_')
            trlst.append(s)
 
            # List the other maintainers for the language. Do not set
            # lang and status for them.
            lang = '~'
            status = '~'
            for m in maintainers[1:]:
                maintainer = m[0]
                email = m[1]
                s = latexLineTpl % (lang, maintainer, email, status)
                s = s.replace('_', '\\_')
                trlst.append(s)
 
        # Join the table lines and insert into the template.
        latexTable = latexTableTpl % (''.join(trlst))
 
        # Put the HTML and LaTeX parts together and define the dic item.
        tplDic['informationTable'] = htmlTable + '\n' + latexTable
 
        # Insert the symbols into the document template and write it down.
        f = xopen(fDocName, 'w')
        f.write(doctpl % tplDic)
        f.close()
 
References translator.TrManager.__loadMaintainers(), translator.TrManager.__maintainersDic, translator.TrManager.__translDic, translator.TrManager.doc_path, translator.TrManager.doxVersion, translator.TrManager.getBgcolorByReadableStatus(), join(), translator.TrManager.langLst, translator.TrManager.languageDocFileName, translator.TrManager.languageTplFileName, translator.TrManager.lastModificationTime, translator.TrManager.maintainersFileName, translator.TrManager.numLang, translator.TrManager.org_doc_path, translator.TrManager.org_doxy_path, print(), translator.TrManager.script_name, translator.TrManager.supportedLangReadableStr, translator.TrManager.translatorReportFileName, and translator.xopen().
generateTranslatorReport() [1/2]
def translator.TrManager.generateTranslatorReport (self)
Generates the translator report.
Definition at line 1536 of file translator.py.
    def generateTranslatorReport(self):
        """Generates the translator report."""
 
        output = os.path.join(self.doc_path, self.translatorReportFileName)
 
        # Open the textual report file for the output.
        f = xopen(output, 'w')
 
        # Output the information about the version.
        f.write('(' + self.doxVersion + ')\n\n')
 
        # Output the information about the number of the supported languages
        # and the list of the languages, or only the note about the explicitly
        # given languages to process.
        if self.script_argLst:
            f.write('The report was generated for the following, explicitly')
            f.write(' identified languages:\n\n')
            f.write(self.supportedLangReadableStr + '\n\n')
        else:
            f.write('Doxygen supports the following ')
            f.write(str(self.numLang))
            f.write(' languages (sorted alphabetically):\n\n')
            f.write(self.supportedLangReadableStr + '\n\n')
 
            # Write the summary about the status of language translators (how
            # many translators) are up-to-date, etc.
            s = 'Of them, %d translators are up-to-date, ' % len(self.upToDateIdLst)
            s += '%d translators are based on some adapter class, ' % len(self.adaptIdLst)
            s += 'and %d are English based.' % len(self.EnBasedIdLst)
            f.write(fill(s) + '\n\n')
 
        # The e-mail addresses of the maintainers will be collected to
        # the auxiliary file in the order of translator classes listed
        # in the translator report.
        fmail = xopen(os.path.join(self.doc_path, 'mailto.txt'), 'w')
 
        # Write the list of "up-to-date" translator classes.
        if self.upToDateIdLst:
            s = '''The following translator classes are up-to-date (sorted
                alphabetically). This means that they derive from the
                Translator class, they implement all %d of the required
                methods, and even minor problems were not spotted by the script:'''
            s = s % len(self.requiredMethodsDic)
            f.write('-' * 70 + '\n')
            f.write(fill(s) + '\n\n')
 
            mailtoLst = []
            for x in self.upToDateIdLst:
                obj = self.__translDic[x]
                if obj.note is None:
                    f.write(' ' + obj.classId + '\n')
                    mailtoLst.extend(self.__emails(obj.classId))
 
            fmail.write('up-to-date\n')
            fmail.write('; '.join(mailtoLst))
 
 
            # Write separately the list of "ALMOST up-to-date" translator classes.
            s = '''The following translator classes are ALMOST up-to-date (sorted
                alphabetically). This means that they derive from the
                Translator class, but there still may be some minor problems
                listed for them:'''
            f.write('\n' + ('-' * 70) + '\n')
            f.write(fill(s) + '\n\n')
            mailtoLst = []
            for x in self.upToDateIdLst:
                obj = self.__translDic[x]
                if obj.note is not None:
                    f.write(' ' + obj.classId + '\t-- ' + obj.note + '\n')
                    mailtoLst.extend(self.__emails(obj.classId))
 
            fmail.write('\n\nalmost up-to-date\n')
            fmail.write('; '.join(mailtoLst))
 
        # Write the list of the adapter based classes. The very obsolete
        # translators that derive from TranslatorEnglish are included.
        if self.adaptIdLst:
            s = '''The following translator classes need maintenance
                (the most obsolete at the end). The other info shows the
                estimation of Doxygen version when the class was last
                updated and number of methods that must be implemented to
                become up-to-date:'''
            f.write('\n' + '-' * 70 + '\n')
            f.write(fill(s) + '\n\n')
 
            # Find also whether some adapter classes may be removed.
            adaptMinVersion = '9.9.99'
 
            mailtoLst = []
            numRequired = len(self.requiredMethodsDic)
            for x in self.adaptIdLst:
                obj = self.__translDic[x]
                f.write(' %-30s' % obj.classId)
                f.write(' %-6s' % obj.readableStatus)
                numimpl = len(obj.missingMethods)
                pluralS = ''
                if numimpl > 1: pluralS = 's'
                percent = 100 * numimpl / numRequired
                f.write('\t%2d method%s to implement (%d %%)' % (
                        numimpl, pluralS, percent))
                if obj.note:
                    f.write('\n\tNote: ' + obj.note + '\n')
                f.write('\n')
                mailtoLst.extend(self.__emails(obj.classId)) # to maintainer
 
                # Check the level of required adapter classes.
                if obj.status != '0.0.00' and obj.status < adaptMinVersion:
                    adaptMinVersion = obj.status
 
            fmail.write('\n\ntranslator based\n')
            fmail.write('; '.join(mailtoLst))
 
            # Set the note if some old translator adapters are not needed
            # any more. Do it only when the script is called without arguments,
            # i.e. all languages were checked against the needed translator
            # adapters.
            if not self.script_argLst:
                to_remove = {}
                for version, adaptClassId in list(self.adaptMethodsDic.values()):
                    if version < adaptMinVersion:
                        to_remove[adaptClassId] = True
 
                if to_remove:
                    lst = list(to_remove.keys())
                    lst.sort()
                    plural = len(lst) > 1
                    note = 'Note: The adapter class'
                    if plural: note += 'es'
                    note += ' ' + ', '.join(lst)
                    if not plural:
                        note += ' is'
                    else:
                        note += ' are'
                    note += ' not used and can be removed.'
                    f.write('\n' + fill(note) + '\n')
 
        # Write the list of the English-based classes.
        if self.EnBasedIdLst:
            s = '''The following translator classes derive directly from the
                TranslatorEnglish. The class identifier has the suffix 'En'
                that says that this is intentional. Usually, there is also
                a non-English based version of the translator for
                the language:'''
            f.write('\n' + '-' * 70 + '\n')
            f.write(fill(s) + '\n\n')
 
            for x in self.EnBasedIdLst:
                obj = self.__translDic[x]
                f.write(' ' + obj.classId)
                f.write('\timplements %d methods' % len(obj.implementedMethods))
                if obj.note:
                    f.write(' -- ' + obj.note)
                f.write('\n')
 
        # Check for not used translator methods and generate warning if found.
        # The check is rather time consuming, so it is not done when report
        # is restricted to explicitly given language identifiers.
        if not self.script_argLst:
            dic = self.__checkForNotUsedTrMethods()
            if dic:
                s = '''WARNING: The following translator methods are declared
                    in the Translator class but their identifiers do not appear
                    in source files. The situation should be checked. The .cpp
                    files and .h files excluding the '*translator*' files
                    in doxygen/src directory were simply searched for occurrence
                    of the method identifiers:'''
                f.write('\n' + '=' * 70 + '\n')
                f.write(fill(s) + '\n\n')
 
                keys = list(dic.keys())
                keys.sort()
                for key in keys:
                    f.write(' ' + dic[key] + '\n')
                f.write('\n')
 
        # Write the details for the translators.
        f.write('\n' + '=' * 70)
        f.write('\nDetails for translators (classes sorted alphabetically):\n')
 
        cls = list(self.__translDic.keys())
        cls.sort()
 
        for c in cls:
            obj = self.__translDic[c]
            assert(obj.classId != 'Translator')
            obj.report(f)
 
        # Close the report file and the auxiliary file with e-mails.
        f.close()
        fmail.close()
 
 
References translator.TrManager.__checkForNotUsedTrMethods(), translator.TrManager.__emails(), translator.TrManager.__translDic, translator.TrManager.adaptIdLst, translator.TrManager.adaptMethodsDic, translator.TrManager.doc_path, translator.TrManager.doxVersion, translator.TrManager.EnBasedIdLst, translator.fill(), join(), len, translator.TrManager.numLang, translator.TrManager.requiredMethodsDic, translator.TrManager.script_argLst, DirDefImpl.sort(), UsedDir.sort(), MemberVector.sort(), DirDef.sort(), translator.TrManager.supportedLangReadableStr, translator.TrManager.translatorReportFileName, translator.TrManager.upToDateIdLst, and translator.xopen().
generateTranslatorReport() [2/2]
def translator.TrManager.generateTranslatorReport (self)
Generates the translator report.
Definition at line 1536 of file translator.py.
    def generateTranslatorReport(self):
        """Generates the translator report."""
 
        output = os.path.join(self.doc_path, self.translatorReportFileName)
 
        # Open the textual report file for the output.
        f = xopen(output, 'w')
 
        # Output the information about the version.
        f.write('(' + self.doxVersion + ')\n\n')
 
        # Output the information about the number of the supported languages
        # and the list of the languages, or only the note about the explicitly
        # given languages to process.
        if self.script_argLst:
            f.write('The report was generated for the following, explicitly')
            f.write(' identified languages:\n\n')
            f.write(self.supportedLangReadableStr + '\n\n')
        else:
            f.write('Doxygen supports the following ')
            f.write(str(self.numLang))
            f.write(' languages (sorted alphabetically):\n\n')
            f.write(self.supportedLangReadableStr + '\n\n')
 
            # Write the summary about the status of language translators (how
            # many translators) are up-to-date, etc.
            s = 'Of them, %d translators are up-to-date, ' % len(self.upToDateIdLst)
            s += '%d translators are based on some adapter class, ' % len(self.adaptIdLst)
            s += 'and %d are English based.' % len(self.EnBasedIdLst)
            f.write(fill(s) + '\n\n')
 
        # The e-mail addresses of the maintainers will be collected to
        # the auxiliary file in the order of translator classes listed
        # in the translator report.
        fmail = xopen(os.path.join(self.doc_path, 'mailto.txt'), 'w')
 
        # Write the list of "up-to-date" translator classes.
        if self.upToDateIdLst:
            s = '''The following translator classes are up-to-date (sorted
                alphabetically). This means that they derive from the
                Translator class, they implement all %d of the required
                methods, and even minor problems were not spotted by the script:'''
            s = s % len(self.requiredMethodsDic)
            f.write('-' * 70 + '\n')
            f.write(fill(s) + '\n\n')
 
            mailtoLst = []
            for x in self.upToDateIdLst:
                obj = self.__translDic[x]
                if obj.note is None:
                    f.write(' ' + obj.classId + '\n')
                    mailtoLst.extend(self.__emails(obj.classId))
 
            fmail.write('up-to-date\n')
            fmail.write('; '.join(mailtoLst))
 
 
            # Write separately the list of "ALMOST up-to-date" translator classes.
            s = '''The following translator classes are ALMOST up-to-date (sorted
                alphabetically). This means that they derive from the
                Translator class, but there still may be some minor problems
                listed for them:'''
            f.write('\n' + ('-' * 70) + '\n')
            f.write(fill(s) + '\n\n')
            mailtoLst = []
            for x in self.upToDateIdLst:
                obj = self.__translDic[x]
                if obj.note is not None:
                    f.write(' ' + obj.classId + '\t-- ' + obj.note + '\n')
                    mailtoLst.extend(self.__emails(obj.classId))
 
            fmail.write('\n\nalmost up-to-date\n')
            fmail.write('; '.join(mailtoLst))
 
        # Write the list of the adapter based classes. The very obsolete
        # translators that derive from TranslatorEnglish are included.
        if self.adaptIdLst:
            s = '''The following translator classes need maintenance
                (the most obsolete at the end). The other info shows the
                estimation of Doxygen version when the class was last
                updated and number of methods that must be implemented to
                become up-to-date:'''
            f.write('\n' + '-' * 70 + '\n')
            f.write(fill(s) + '\n\n')
 
            # Find also whether some adapter classes may be removed.
            adaptMinVersion = '9.9.99'
 
            mailtoLst = []
            numRequired = len(self.requiredMethodsDic)
            for x in self.adaptIdLst:
                obj = self.__translDic[x]
                f.write(' %-30s' % obj.classId)
                f.write(' %-6s' % obj.readableStatus)
                numimpl = len(obj.missingMethods)
                pluralS = ''
                if numimpl > 1: pluralS = 's'
                percent = 100 * numimpl / numRequired
                f.write('\t%2d method%s to implement (%d %%)' % (
                        numimpl, pluralS, percent))
                if obj.note:
                    f.write('\n\tNote: ' + obj.note + '\n')
                f.write('\n')
                mailtoLst.extend(self.__emails(obj.classId)) # to maintainer
 
                # Check the level of required adapter classes.
                if obj.status != '0.0.00' and obj.status < adaptMinVersion:
                    adaptMinVersion = obj.status
 
            fmail.write('\n\ntranslator based\n')
            fmail.write('; '.join(mailtoLst))
 
            # Set the note if some old translator adapters are not needed
            # any more. Do it only when the script is called without arguments,
            # i.e. all languages were checked against the needed translator
            # adapters.
            if not self.script_argLst:
                to_remove = {}
                for version, adaptClassId in list(self.adaptMethodsDic.values()):
                    if version < adaptMinVersion:
                        to_remove[adaptClassId] = True
 
                if to_remove:
                    lst = list(to_remove.keys())
                    lst.sort()
                    plural = len(lst) > 1
                    note = 'Note: The adapter class'
                    if plural: note += 'es'
                    note += ' ' + ', '.join(lst)
                    if not plural:
                        note += ' is'
                    else:
                        note += ' are'
                    note += ' not used and can be removed.'
                    f.write('\n' + fill(note) + '\n')
 
        # Write the list of the English-based classes.
        if self.EnBasedIdLst:
            s = '''The following translator classes derive directly from the
                TranslatorEnglish. The class identifier has the suffix 'En'
                that says that this is intentional. Usually, there is also
                a non-English based version of the translator for
                the language:'''
            f.write('\n' + '-' * 70 + '\n')
            f.write(fill(s) + '\n\n')
 
            for x in self.EnBasedIdLst:
                obj = self.__translDic[x]
                f.write(' ' + obj.classId)
                f.write('\timplements %d methods' % len(obj.implementedMethods))
                if obj.note:
                    f.write(' -- ' + obj.note)
                f.write('\n')
 
        # Check for not used translator methods and generate warning if found.
        # The check is rather time consuming, so it is not done when report
        # is restricted to explicitly given language identifiers.
        if not self.script_argLst:
            dic = self.__checkForNotUsedTrMethods()
            if dic:
                s = '''WARNING: The following translator methods are declared
                    in the Translator class but their identifiers do not appear
                    in source files. The situation should be checked. The .cpp
                    files and .h files excluding the '*translator*' files
                    in doxygen/src directory were simply searched for occurrence
                    of the method identifiers:'''
                f.write('\n' + '=' * 70 + '\n')
                f.write(fill(s) + '\n\n')
 
                keys = list(dic.keys())
                keys.sort()
                for key in keys:
                    f.write(' ' + dic[key] + '\n')
                f.write('\n')
 
        # Write the details for the translators.
        f.write('\n' + '=' * 70)
        f.write('\nDetails for translators (classes sorted alphabetically):\n')
 
        cls = list(self.__translDic.keys())
        cls.sort()
 
        for c in cls:
            obj = self.__translDic[c]
            assert(obj.classId != 'Translator')
            obj.report(f)
 
        # Close the report file and the auxiliary file with e-mails.
        f.close()
        fmail.close()
 
 
References translator.TrManager.__checkForNotUsedTrMethods(), translator.TrManager.__emails(), translator.TrManager.__translDic, translator.TrManager.adaptIdLst, translator.TrManager.adaptMethodsDic, translator.TrManager.doc_path, translator.TrManager.doxVersion, translator.TrManager.EnBasedIdLst, translator.fill(), join(), len, translator.TrManager.numLang, translator.TrManager.requiredMethodsDic, translator.TrManager.script_argLst, DirDefImpl.sort(), UsedDir.sort(), MemberVector.sort(), DirDef.sort(), translator.TrManager.supportedLangReadableStr, translator.TrManager.translatorReportFileName, translator.TrManager.upToDateIdLst, and translator.xopen().
getBgcolorByReadableStatus() [1/2]
def translator.TrManager.getBgcolorByReadableStatus (self, readableStatus)
Definition at line 1518 of file translator.py.
    def getBgcolorByReadableStatus(self, readableStatus):
        if readableStatus == 'up-to-date':
            color = '#ccffcc' # green
        elif readableStatus.startswith('almost'):
            color = '#ffffff' # white
        elif readableStatus.startswith('English'):
            color = '#ccffcc' # green
        elif readableStatus.startswith('1.8'):
            color = '#ffffcc' # yellow
        elif readableStatus.startswith('1.7'):
            color = '#ffcccc' # pink
        elif readableStatus.startswith('1.6'):
            color = '#ffcccc' # pink
        else:
            color = '#ff5555' # red
        return color
 
 
Referenced by translator.TrManager.generateLanguageDoc().
getBgcolorByReadableStatus() [2/2]
def translator.TrManager.getBgcolorByReadableStatus (self, readableStatus)
Definition at line 1518 of file translator.py.
    def getBgcolorByReadableStatus(self, readableStatus):
        if readableStatus == 'up-to-date':
            color = '#ccffcc' # green
        elif readableStatus.startswith('almost'):
            color = '#ffffff' # white
        elif readableStatus.startswith('English'):
            color = '#ccffcc' # green
        elif readableStatus.startswith('1.8'):
            color = '#ffffcc' # yellow
        elif readableStatus.startswith('1.7'):
            color = '#ffcccc' # pink
        elif readableStatus.startswith('1.6'):
            color = '#ffcccc' # pink
        else:
            color = '#ff5555' # red
        return color
 
 
Referenced by translator.TrManager.generateLanguageDoc().
Member Data Documentation
__maintainersDic
translator.TrManager.__maintainersDic [private]
Definition at line 1285 of file translator.py.
Referenced by translator.TrManager.__emails(), translator.TrManager.__init__(), translator.TrManager.__loadMaintainers(), and translator.TrManager.generateLanguageDoc().
__translDic
translator.TrManager.__translDic [private]
Definition at line 1256 of file translator.py.
Referenced by translator.TrManager.__build(), translator.TrManager.__extractProcessedInfo(), translator.TrManager.__init__(), translator.TrManager.generateLanguageDoc(), and translator.TrManager.generateTranslatorReport().
adaptIdLst
translator.TrManager.adaptIdLst
Definition at line 1365 of file translator.py.
Referenced by translator.TrManager.__extractProcessedInfo(), and translator.TrManager.generateTranslatorReport().
adaptMethodsDic
translator.TrManager.adaptMethodsDic
Definition at line 1265 of file translator.py.
Referenced by translator.TrManager.__build(), translator.TrManager.__init__(), and translator.TrManager.generateTranslatorReport().
doc_path
translator.TrManager.doc_path
Definition at line 1236 of file translator.py.
Referenced by translator.TrManager.__init__(), translator.TrManager.generateLanguageDoc(), and translator.TrManager.generateTranslatorReport().
doxVersion
translator.TrManager.doxVersion
Definition at line 1291 of file translator.py.
Referenced by translator.TrManager.__extractProcessedInfo(), translator.TrManager.__init__(), translator.TrManager.generateLanguageDoc(), and translator.TrManager.generateTranslatorReport().
doxy_path
translator.TrManager.doxy_path
Definition at line 1233 of file translator.py.
Referenced by translator.TrManager.__init__().
EnBasedIdLst
translator.TrManager.EnBasedIdLst
Definition at line 1361 of file translator.py.
Referenced by translator.TrManager.__extractProcessedInfo(), and translator.TrManager.generateTranslatorReport().
langLst
translator.TrManager.langLst
Definition at line 1288 of file translator.py.
Referenced by translator.TrManager.__extractProcessedInfo(), translator.TrManager.__init__(), and translator.TrManager.generateLanguageDoc().
languageDocFileName
translator.TrManager.languageDocFileName
Definition at line 1281 of file translator.py.
Referenced by translator.TrManager.__init__(), and translator.TrManager.generateLanguageDoc().
languageTplFileName
translator.TrManager.languageTplFileName
Definition at line 1280 of file translator.py.
Referenced by translator.TrManager.__init__(), and translator.TrManager.generateLanguageDoc().
lastModificationTime
translator.TrManager.lastModificationTime
Definition at line 1273 of file translator.py.
Referenced by translator.TrManager.__build(), translator.TrManager.__extractProcessedInfo(), translator.TrManager.__init__(), translator.TrManager.__loadMaintainers(), and translator.TrManager.generateLanguageDoc().
maintainersFileName
translator.TrManager.maintainersFileName
Definition at line 1279 of file translator.py.
Referenced by translator.TrManager.__init__(), translator.TrManager.__loadMaintainers(), and translator.TrManager.generateLanguageDoc().
numLang
translator.TrManager.numLang
Definition at line 1290 of file translator.py.
Referenced by translator.TrManager.__extractProcessedInfo(), translator.TrManager.__init__(), translator.TrManager.generateLanguageDoc(), and translator.TrManager.generateTranslatorReport().
org_doc_path
translator.TrManager.org_doc_path
Definition at line 1242 of file translator.py.
Referenced by translator.TrManager.__init__(), translator.TrManager.__loadMaintainers(), and translator.TrManager.generateLanguageDoc().
org_doxy_path
translator.TrManager.org_doxy_path
Definition at line 1243 of file translator.py.
Referenced by translator.TrManager.__extractProcessedInfo(), translator.TrManager.__init__(), and translator.TrManager.generateLanguageDoc().
org_src_path
translator.TrManager.org_src_path
Definition at line 1241 of file translator.py.
Referenced by translator.TrManager.__build(), translator.TrManager.__getNoTrSourceFilesLst(), and translator.TrManager.__init__().
requiredMethodsDic
translator.TrManager.requiredMethodsDic
Definition at line 1261 of file translator.py.
Referenced by translator.TrManager.__build(), translator.TrManager.__checkForNotUsedTrMethods(), translator.TrManager.__init__(), and translator.TrManager.generateTranslatorReport().
script
translator.TrManager.script
Definition at line 1225 of file translator.py.
Referenced by translator.TrManager.__init__().
script_argLst
translator.TrManager.script_argLst
Definition at line 1249 of file translator.py.
Referenced by translator.TrManager.__build(), translator.TrManager.__init__(), and translator.TrManager.generateTranslatorReport().
script_name
translator.TrManager.script_name
Definition at line 1226 of file translator.py.
Referenced by translator.TrManager.__init__(), and translator.TrManager.generateLanguageDoc().
script_path
translator.TrManager.script_path
Definition at line 1227 of file translator.py.
Referenced by translator.TrManager.__init__().
src_path
translator.TrManager.src_path
Definition at line 1237 of file translator.py.
Referenced by translator.TrManager.__init__().
supportedLangReadableStr
translator.TrManager.supportedLangReadableStr
Definition at line 1289 of file translator.py.
Referenced by translator.TrManager.__extractProcessedInfo(), translator.TrManager.__init__(), translator.TrManager.generateLanguageDoc(), and translator.TrManager.generateTranslatorReport().
translatorReportFileName
translator.TrManager.translatorReportFileName
Definition at line 1278 of file translator.py.
Referenced by translator.TrManager.__init__(), translator.TrManager.generateLanguageDoc(), and translator.TrManager.generateTranslatorReport().
upToDateIdLst
translator.TrManager.upToDateIdLst
Definition at line 1360 of file translator.py.
Referenced by translator.TrManager.__extractProcessedInfo(), and translator.TrManager.generateTranslatorReport().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/doc/translator.py
doxygen/doc/translator.py