TextGeneratorXMLImpl Class Reference
Public Member Functions
TextGeneratorXMLImpl (TextStream &t)
void writeString (const QCString &s, bool) const
void writeBreak (int) const
void writeLink (const QCString &extRef, const QCString &file, const QCString &anchor, const QCString &text) const
TextGeneratorXMLImpl (TextStream &t)
void writeString (const QCString &s, bool) const
void writeBreak (int) const
void writeLink (const QCString &extRef, const QCString &file, const QCString &anchor, const QCString &text) const
Private Attributes
TextStream & m_t
Detailed Description
Implements TextGeneratorIntf for an XML stream.
Definition at line 207 of file xmlgen.cpp.
Constructor & Destructor Documentation
TextGeneratorXMLImpl() [1/2]
TextGeneratorXMLImpl::TextGeneratorXMLImpl (TextStream & t) [inline]
Definition at line 210 of file xmlgen.cpp.
: m_t(t) {}
TextGeneratorXMLImpl() [2/2]
TextGeneratorXMLImpl::TextGeneratorXMLImpl (TextStream & t) [inline]
Definition at line 210 of file xmlgen.cpp.
: m_t(t) {}
Member Function Documentation
writeBreak() [1/2]
void TextGeneratorXMLImpl::writeBreak (int) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 215 of file xmlgen.cpp.
{}
writeBreak() [2/2]
void TextGeneratorXMLImpl::writeBreak (int) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 215 of file xmlgen.cpp.
{}
writeLink() [1/2]
void TextGeneratorXMLImpl::writeLink (const QCString & extRef, const QCString & file, const QCString & anchor, const QCString & text) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 216 of file xmlgen.cpp.
    {
      writeXMLLink(m_t,extRef,file,anchor,text,QCString());
    }
References caseconvert::file, m_t, and writeXMLLink().
writeLink() [2/2]
void TextGeneratorXMLImpl::writeLink (const QCString & extRef, const QCString & file, const QCString & anchor, const QCString & text) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 216 of file xmlgen.cpp.
    {
      writeXMLLink(m_t,extRef,file,anchor,text,QCString());
    }
References caseconvert::file, m_t, and writeXMLLink().
writeString() [1/2]
void TextGeneratorXMLImpl::writeString (const QCString & s, bool) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 211 of file xmlgen.cpp.
    {
      writeXMLString(m_t,s);
    }
References m_t, s, and writeXMLString().
writeString() [2/2]
void TextGeneratorXMLImpl::writeString (const QCString & s, bool) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 211 of file xmlgen.cpp.
    {
      writeXMLString(m_t,s);
    }
References m_t, s, and writeXMLString().
Member Data Documentation
m_t
TextStream & TextGeneratorXMLImpl::m_t [private]
Definition at line 223 of file xmlgen.cpp.
Referenced by writeLink(), and writeString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/xmlgen.cpp
doxygen/src/xmlgen.cpp