SymbolGroupContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
SymbolGroupContext (const SearchIndexList::const_iterator &start, const SearchIndexList::const_iterator &end)
virtual ~SymbolGroupContext ()
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
SymbolGroupContext (const SearchIndexList::const_iterator &start, const SearchIndexList::const_iterator &end)
virtual ~SymbolGroupContext ()
Static Public Member Functions
static TemplateStructIntfPtr alloc (const SearchIndexList::const_iterator &start, const SearchIndexList::const_iterator &end)
static TemplateStructIntfPtr alloc (const SearchIndexList::const_iterator &start, const SearchIndexList::const_iterator &end)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 1270 of file context.h.
Constructor & Destructor Documentation
SymbolGroupContext() [1/2]
SymbolGroupContext::SymbolGroupContext (const SearchIndexList::const_iterator & start, const SearchIndexList::const_iterator & end)
Definition at line 8583 of file context.cpp.
                                                                                 : p(std::make_unique<Private>(start,end))
{
}
 SymbolGroupContext() [1/2]
SymbolGroupContext::~SymbolGroupContext () [virtual]
Definition at line 8588 of file context.cpp.
{
}
SymbolGroupContext() [2/2]
SymbolGroupContext::SymbolGroupContext (const SearchIndexList::const_iterator & start, const SearchIndexList::const_iterator & end)
 SymbolGroupContext() [2/2]
virtual SymbolGroupContext::~SymbolGroupContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateStructIntfPtr SymbolGroupContext::alloc (const SearchIndexList::const_iterator & start, const SearchIndexList::const_iterator & end) [inline], [static]
Definition at line 1273 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<SymbolGroupContext>(start,end)); }
References ghc::filesystem::end().
Referenced by SymbolGroupListContext::Private::Private().
alloc() [2/2]
static TemplateStructIntfPtr SymbolGroupContext::alloc (const SearchIndexList::const_iterator & start, const SearchIndexList::const_iterator & end) [inline], [static]
Definition at line 1273 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<SymbolGroupContext>(start,end)); }
References ghc::filesystem::end().
fields() [1/2]
StringVector SymbolGroupContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 8597 of file context.cpp.
{
  return p->fields();
}
References p.
fields() [2/2]
virtual StringVector SymbolGroupContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant SymbolGroupContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 8592 of file context.cpp.
{
  return p->get(name);
}
References setup::name, and p.
get() [2/2]
virtual TemplateVariant SymbolGroupContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Member Data Documentation
p
std::unique_ptr< Private > SymbolGroupContext::p [private]
Definition at line 1287 of file context.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp