RTFGenerator Class Reference
#include <rtfgen.h>
Classes
struct RTFListItemInfo
Public Member Functions
RTFGenerator ()
RTFGenerator (const RTFGenerator &)
RTFGenerator & operator= (const RTFGenerator &)
virtual ~RTFGenerator ()
virtual std::unique_ptr< OutputGenerator > clone () const
void cleanup ()
OutputType type () const
void setRelativePath (const QCString &path)
void setSourceFileName (const QCString &sourceFileName)
void writeDoc (const IDocNodeAST *ast, const Definition *, const MemberDef *, int)
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id)
void writeSearchInfo ()
void writeFooter (const QCString &)
void endFile ()
void clearBuffer ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const QCString &, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int part)
void startTitleHead (const QCString &)
void startTitle ()
void endTitleHead (const QCString &, const QCString &name)
void endTitle ()
void newParagraph ()
void startParagraph (const QCString &classDef)
void endParagraph ()
void writeString (const QCString &text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const QCString &, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const QCString &ref, const QCString &file)
void endIndexItem (const QCString &ref, const QCString &file)
void docify (const QCString &text)
void codify (const QCString &text)
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &)
void startTextLink (const QCString &f, const QCString &anchor)
void endTextLink ()
void startHtmlLink (const QCString &url)
void endHtmlLink ()
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int)
void endGroupHeader (int)
void startItemListItem ()
void endItemListItem ()
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const QCString &, int)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const QCString &, int, const QCString &)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const QCString &, const QCString &)
void startCompoundTemplateParams ()
void endCompoundTemplateParams ()
void insertMemberAlign (bool)
void insertMemberAlignLeft (int, bool)
void writeRuler ()
void writeAnchor (const QCString &fileName, const QCString &name)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
void writeLineNumber (const QCString &, const QCString &, const QCString &, int l, bool)
void startCodeLine (bool)
void endCodeLine ()
void startEmphasis ()
void endEmphasis ()
void startBold ()
void endBold ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void lineBreak (const QCString &style=QCString())
void startMemberDoc (const QCString &, const QCString &, const QCString &, const QCString &, int, int, bool)
void endMemberDoc (bool)
void startDoxyAnchor (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void endDoxyAnchor (const QCString &, const QCString &)
void writeChar (char c)
void writeLatexSpacing ()
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name)
void writeEndAnnoItem (const QCString &name)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startMemberDescription (const QCString &, const QCString &, bool)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const QCString &, const QCString &)
void writeInheritedSectionTitle (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void startDescList (SectionTypes)
void startExamples ()
void endExamples ()
void startParamList (ParamListTypes, const QCString &)
void endParamList ()
void startDescForItem ()
void endDescForItem ()
void startSection (const QCString &, const QCString &, SectionType)
void endSection (const QCString &, SectionType)
void addIndexItem (const QCString &, const QCString &)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const QCString &filename, const QCString &name)
void startPageRef ()
void endPageRef (const QCString &, const QCString &)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const QCString &)
void writeNavigationPath (const QCString &)
void writeLogo ()
void writeQuickLinks (bool, HighlightedItem, const QCString &)
void writeSummaryLink (const QCString &, const QCString &, const QCString &, bool)
void startContents ()
void endContents ()
void writeNonBreakableSpace (int)
void startDescTable (const QCString &title)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startDotGraph ()
void endDotGraph (DotClassGraph &)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &)
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &g)
void startCallGraph ()
void endCallGraph (DotCallGraph &)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &g)
void writeGraphicalHierarchy (DotGfxHierarchyTable &)
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void startTextBlock (bool dense)
void endTextBlock (bool)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool, const QCString &)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool, bool, bool)
void startParameterList (bool)
void endParameterList ()
void exceptionEntry (const QCString &, bool)
void startConstraintList (const QCString &)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const QCString &l, bool isLast)
void endLabels ()
void startFontClass (const QCString &)
void endFontClass ()
void writeCodeAnchor (const QCString &)
RTFGenerator ()
RTFGenerator (const RTFGenerator &)
RTFGenerator & operator= (const RTFGenerator &)
virtual ~RTFGenerator ()
virtual std::unique_ptr< OutputGenerator > clone () const
void cleanup ()
OutputType type () const
void setRelativePath (const QCString &path)
void setSourceFileName (const QCString &sourceFileName)
void writeDoc (const IDocNodeAST *ast, const Definition *, const MemberDef *, int)
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id)
void writeSearchInfo ()
void writeFooter (const QCString &)
void endFile ()
void clearBuffer ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const QCString &, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int part)
void startTitleHead (const QCString &)
void startTitle ()
void endTitleHead (const QCString &, const QCString &name)
void endTitle ()
void newParagraph ()
void startParagraph (const QCString &classDef)
void endParagraph ()
void writeString (const QCString &text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const QCString &, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const QCString &ref, const QCString &file)
void endIndexItem (const QCString &ref, const QCString &file)
void docify (const QCString &text)
void codify (const QCString &text)
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &)
void startTextLink (const QCString &f, const QCString &anchor)
void endTextLink ()
void startHtmlLink (const QCString &url)
void endHtmlLink ()
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int)
void endGroupHeader (int)
void startItemListItem ()
void endItemListItem ()
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const QCString &, int)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const QCString &, int, const QCString &)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const QCString &, const QCString &)
void startCompoundTemplateParams ()
void endCompoundTemplateParams ()
void insertMemberAlign (bool)
void insertMemberAlignLeft (int, bool)
void writeRuler ()
void writeAnchor (const QCString &fileName, const QCString &name)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
void writeLineNumber (const QCString &, const QCString &, const QCString &, int l, bool)
void startCodeLine (bool)
void endCodeLine ()
void startEmphasis ()
void endEmphasis ()
void startBold ()
void endBold ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void lineBreak (const QCString &style=QCString())
void startMemberDoc (const QCString &, const QCString &, const QCString &, const QCString &, int, int, bool)
void endMemberDoc (bool)
void startDoxyAnchor (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void endDoxyAnchor (const QCString &, const QCString &)
void writeChar (char c)
void writeLatexSpacing ()
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name)
void writeEndAnnoItem (const QCString &name)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startMemberDescription (const QCString &, const QCString &, bool)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const QCString &, const QCString &)
void writeInheritedSectionTitle (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void startDescList (SectionTypes)
void startExamples ()
void endExamples ()
void startParamList (ParamListTypes, const QCString &)
void endParamList ()
void startDescForItem ()
void endDescForItem ()
void startSection (const QCString &, const QCString &, SectionType)
void endSection (const QCString &, SectionType)
void addIndexItem (const QCString &, const QCString &)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const QCString &filename, const QCString &name)
void startPageRef ()
void endPageRef (const QCString &, const QCString &)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const QCString &)
void writeNavigationPath (const QCString &)
void writeLogo ()
void writeQuickLinks (bool, HighlightedItem, const QCString &)
void writeSummaryLink (const QCString &, const QCString &, const QCString &, bool)
void startContents ()
void endContents ()
void writeNonBreakableSpace (int)
void startDescTable (const QCString &title)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startDotGraph ()
void endDotGraph (DotClassGraph &)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &)
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &g)
void startCallGraph ()
void endCallGraph (DotCallGraph &)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &g)
void writeGraphicalHierarchy (DotGfxHierarchyTable &)
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void startTextBlock (bool dense)
void endTextBlock (bool)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool, const QCString &)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool, bool, bool)
void startParameterList (bool)
void endParameterList ()
void exceptionEntry (const QCString &, bool)
void startConstraintList (const QCString &)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const QCString &l, bool isLast)
void endLabels ()
void startFontClass (const QCString &)
void endFontClass ()
void writeCodeAnchor (const QCString &)
Static Public Member Functions
static void init ()
static void writeStyleSheetFile (TextStream &t)
static void writeExtensionsFile (TextStream &t)
static bool preProcessFileInplace (const QCString &path, const QCString &name)
static void init ()
static void writeStyleSheetFile (TextStream &t)
static void writeExtensionsFile (TextStream &t)
static bool preProcessFileInplace (const QCString &path, const QCString &name)
Private Member Functions
QCString rtf_BList_DepthStyle ()
QCString rtf_CList_DepthStyle ()
QCString rtf_EList_DepthStyle ()
QCString rtf_LCList_DepthStyle ()
QCString rtf_DList_DepthStyle ()
QCString rtf_Code_DepthStyle ()
void beginRTFDocument ()
void beginRTFChapter ()
void beginRTFSection ()
void rtfwriteRuler_doubleline ()
void rtfwriteRuler_emboss ()
void rtfwriteRuler_thick ()
void rtfwriteRuler_thin ()
void writeRTFReference (const QCString &label)
int indentLevel () const
void incIndentLevel ()
void decIndentLevel ()
QCString rtf_BList_DepthStyle ()
QCString rtf_CList_DepthStyle ()
QCString rtf_EList_DepthStyle ()
QCString rtf_LCList_DepthStyle ()
QCString rtf_DList_DepthStyle ()
QCString rtf_Code_DepthStyle ()
void beginRTFDocument ()
void beginRTFChapter ()
void beginRTFSection ()
void rtfwriteRuler_doubleline ()
void rtfwriteRuler_emboss ()
void rtfwriteRuler_thick ()
void rtfwriteRuler_thin ()
void writeRTFReference (const QCString &label)
int indentLevel () const
void incIndentLevel ()
void decIndentLevel ()
Private Attributes
QCString m_sourceFileName
int m_col = 0
bool m_bstartedBody = false
bool m_omitParagraph = false
int m_numCols = 0
QCString m_relPath
bool m_doxyCodeLineOpen = false
int m_indentLevel = 0
RTFListItemInfo m_listItemInfo [maxIndentLevels]
Static Private Attributes
static const int maxIndentLevels = 13
Additional Inherited Members
Detailed Description
Generator for RTF output.
Definition at line 25 of file rtfgen.h.
Constructor & Destructor Documentation
RTFGenerator() [1/4]
RTFGenerator::RTFGenerator ()
Definition at line 64 of file rtfgen.cpp.
                           : OutputGenerator(Config_getString(RTF_OUTPUT))
{
}
RTFGenerator() [2/4]
RTFGenerator::RTFGenerator (const RTFGenerator & og)
Definition at line 68 of file rtfgen.cpp.
                                                 : OutputGenerator(og)
{
}
 RTFGenerator() [1/2]
RTFGenerator::~RTFGenerator () [virtual]
Definition at line 83 of file rtfgen.cpp.
{
}
RTFGenerator() [3/4]
RTFGenerator::RTFGenerator ()
RTFGenerator() [4/4]
RTFGenerator::RTFGenerator (const RTFGenerator &)
 RTFGenerator() [2/2]
virtual RTFGenerator::~RTFGenerator () [virtual]
Member Function Documentation
addIndexItem() [1/2]
void RTFGenerator::addIndexItem (const QCString & s1, const QCString & s2) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1454 of file rtfgen.cpp.
{
  if (!s1.isEmpty())
  {
    m_t << "{\\xe \\v ";
    docify(s1);
    if (!s2.isEmpty())
    {
      m_t << "\\:";
      docify(s2);
    }
    m_t << "}\n";
  }
}
References docify(), QCString::isEmpty(), and OutputGenerator::m_t.
Referenced by endTitleHead(), and startMemberDoc().
addIndexItem() [2/2]
void RTFGenerator::addIndexItem (const QCString & , const QCString &) [virtual]
Implements BaseOutputDocInterface.
beginRTFChapter() [1/2]
void RTFGenerator::beginRTFChapter () [private]
Definition at line 326 of file rtfgen.cpp.
{
  m_t << "\n";
  DBG_RTF(m_t << "{\\comment BeginRTFChapter}\n")
  m_t << rtf_Style_Reset;
  // if we are compact, no extra page breaks...
  if (Config_getBool(COMPACT_RTF))
  {
    // m_t << "\\sect\\sectd\\sbknone\n";
    m_t << "\\sect\\sbknone\n";
    rtfwriteRuler_thick();
  }
  else
    m_t << "\\sect\\sbkpage\n";
  //m_t << "\\sect\\sectd\\sbkpage\n";
  m_t << rtf_Style["Heading1"].reference() << "\n";
}
References Config_getBool, DBG_RTF, OutputGenerator::m_t, rtf_Style, rtf_Style_Reset, and rtfwriteRuler_thick().
Referenced by endIndexSection(), startIndexSection(), and startTitle().
beginRTFChapter() [2/2]
void RTFGenerator::beginRTFChapter () [private]
beginRTFDocument() [1/2]
void RTFGenerator::beginRTFDocument () [private]
Definition at line 220 of file rtfgen.cpp.
{
  /* all the included RTF files should begin with the
   * same header
   */
  m_t << "{\\rtf1\\ansi\\ansicpg" << theTranslator->trRTFansicp();
  m_t << "\\uc1 \\deff0\\deflang1033\\deflangfe1033\n";
  DBG_RTF(m_t << "{\\comment Beginning font list}\n")
  m_t << "{\\fonttbl ";
  m_t << "{\\f0\\froman\\fcharset" << theTranslator->trRTFCharSet();
  m_t << "\\fprq2{\\*\\panose 02020603050405020304}Times New Roman;}\n";
  m_t << "{\\f1\\fswiss\\fcharset" << theTranslator->trRTFCharSet();
  m_t << "\\fprq2{\\*\\panose 020b0604020202020204}Arial;}\n";
  m_t << "{\\f2\\fmodern\\fcharset" << theTranslator->trRTFCharSet();
  m_t << "\\fprq1{\\*\\panose 02070309020205020404}Courier New;}\n";
  m_t << "{\\f3\\froman\\fcharset2\\fprq2{\\*\\panose 05050102010706020507}Symbol;}\n";
  m_t << "}\n";
  DBG_RTF(m_t << "{\\comment begin colors}\n")
  m_t << "{\\colortbl;";
  m_t << "\\red0\\green0\\blue0;";
  m_t << "\\red0\\green0\\blue255;";
  m_t << "\\red0\\green255\\blue255;";
  m_t << "\\red0\\green255\\blue0;";
  m_t << "\\red255\\green0\\blue255;";
  m_t << "\\red255\\green0\\blue0;";
  m_t << "\\red255\\green255\\blue0;";
  m_t << "\\red255\\green255\\blue255;";
  m_t << "\\red0\\green0\\blue128;";
  m_t << "\\red0\\green128\\blue128;";
  m_t << "\\red0\\green128\\blue0;";
  m_t << "\\red128\\green0\\blue128;";
  m_t << "\\red128\\green0\\blue0;";
  m_t << "\\red128\\green128\\blue0;";
  m_t << "\\red128\\green128\\blue128;";
  m_t << "\\red192\\green192\\blue192;";
  // code highlighting colors. Note order is important see also RTFGenerator::startFontClass
  m_t << "\\red0\\green128\\blue0;"; // keyword = index 17
  m_t << "\\red96\\green64\\blue32;"; // keywordtype
  m_t << "\\rede0\\green128\\blue0;"; // keywordflow
  m_t << "\\red128\\green0\\blue0;"; // comment
  m_t << "\\red128\\green96\\blue32;"; // preprocessor
  m_t << "\\red0\\green32\\blue128;"; // stringliteral
  m_t << "\\red0\\green128\\blue128;"; // charliteral
  m_t << "\\red255\\green0\\blue255;"; // vhdldigit
  m_t << "\\red0\\green0\\blue0;"; // vhdlchar
  m_t << "\\red112\\green0\\blue112;"; // vhdlkeyword
  m_t << "\\red255\\green0\\blue0;"; // vhdllogic
  m_t << "}\n";
  DBG_RTF(m_t << "{\\comment Beginning style list}\n")
  m_t << "{\\stylesheet\n";
  m_t << "{\\widctlpar\\adjustright \\fs20\\cgrid \\snext0 Normal;}\n";
  // set the paper dimensions according to PAPER_TYPE
  auto paperType = Config_getEnum(PAPER_TYPE);
  m_t << "{";
  switch (paperType)
  {
    // width & height values are inches * 1440
    case PAPER_TYPE_t::a4: m_t << "\\paperw11900\\paperh16840"; break;
    case PAPER_TYPE_t::letter: m_t << "\\paperw12240\\paperh15840"; break;
    case PAPER_TYPE_t::legal: m_t << "\\paperw12240\\paperh20160"; break;
    case PAPER_TYPE_t::executive: m_t << "\\paperw10440\\paperh15120"; break;
  }
  m_t << "\\margl1800\\margr1800\\margt1440\\margb1440\\gutter0\\ltrsect}\n";
  // sort styles ascending by \s-number via an intermediate QArray
  unsigned maxIndex = 0;
  for (const auto &kv : rtf_Style)
  {
    uint index = kv.second.index();
    if (index > maxIndex) maxIndex = index;
  }
  std::vector<const StyleData*> array(maxIndex + 1, 0);
  ASSERT(maxIndex < array.size());
  for (const auto &kv : rtf_Style)
  {
    uint index = kv.second.index();
    if (array[index] != 0)
    {
      msg("Style '%s' redefines \\s%d.\n", kv.first.c_str(), index);
    }
    array[index] = &kv.second;
  }
  // write array elements
  size_t size = array.size();
  for(size_t i = 0; i < size; i++)
  {
    const StyleData *pStyle = array[i];
    if (pStyle)
    {
      m_t << "{" << pStyle->reference() << pStyle->definition() << ";}\n";
    }
  }
  m_t << "}\n";
  // this comment is needed for postprocessing!
  m_t << "{\\comment begin body}\n";
}
References ASSERT, Config_getEnum, DBG_RTF, StyleData::definition(), OutputGenerator::m_t, msg(), StyleData::reference(), rtf_Style, size, theTranslator, Translator::trRTFansicp(), and Translator::trRTFCharSet().
Referenced by startFile().
beginRTFDocument() [2/2]
void RTFGenerator::beginRTFDocument () [private]
beginRTFSection() [1/2]
void RTFGenerator::beginRTFSection () [private]
Definition at line 346 of file rtfgen.cpp.
{
  m_t << "\n";
  DBG_RTF(m_t << "{\\comment BeginRTFSection}\n")
  m_t << rtf_Style_Reset;
  // if we are compact, no extra page breaks...
  if (Config_getBool(COMPACT_RTF))
  {
    m_t << "\\sect\\sbknone\n";
    rtfwriteRuler_emboss();
  }
  else
  {
    m_t << "\\sect\\sbkpage\n";
  }
  m_t << rtf_Style["Heading2"].reference() << "\n";
}
References Config_getBool, DBG_RTF, OutputGenerator::m_t, rtf_Style, rtf_Style_Reset, and rtfwriteRuler_emboss().
Referenced by endIndexSection(), and startTitle().
beginRTFSection() [2/2]
void RTFGenerator::beginRTFSection () [private]
cleanup() [1/2]
void RTFGenerator::cleanup () [virtual]
Implements OutputGenerator.
Definition at line 206 of file rtfgen.cpp.
{
  QCString dname = Config_getString(RTF_OUTPUT);
  Dir d(dname.str());
  clearSubDirs(d);
}
References clearSubDirs(), Config_getString, and QCString::str().
cleanup() [2/2]
void RTFGenerator::cleanup () [virtual]
Implements OutputGenerator.
clearBuffer() [1/2]
void RTFGenerator::clearBuffer ()
clearBuffer() [2/2]
void RTFGenerator::clearBuffer ()
clone() [1/2]
std::unique_ptr< OutputGenerator > RTFGenerator::clone () const [virtual]
Implements OutputGenerator.
Definition at line 78 of file rtfgen.cpp.
{
  return std::make_unique<RTFGenerator>(*this);
}
clone() [2/2]
virtual std::unique_ptr< OutputGenerator > RTFGenerator::clone () const [virtual]
Implements OutputGenerator.
codify() [1/2]
void RTFGenerator::codify (const QCString & s) [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 1611 of file rtfgen.cpp.
{
  // note that RTF does not have a "verbatim", so "\n" means
  // nothing... add a "newParagraph()";
  //static char spaces[]=" ";
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    int spacesToNextTabStop;
    while (*p)
    {
      //static bool MultiByte = FALSE;
      c=*p++;
      switch(c)
      {
        case '\t': spacesToNextTabStop = Config_getInt(TAB_SIZE) - (m_col%Config_getInt(TAB_SIZE));
                    m_t << Doxygen::spaces.left(spacesToNextTabStop);
                    m_col+=spacesToNextTabStop;
                    break;
        case '\n': newParagraph();
                    m_t << '\n'; m_col=0;
                    break;
        case '{': m_t << "\\{"; m_col++; break;
        case '}': m_t << "\\}"; m_col++; break;
        case '\\': m_t << "\\\\"; m_col++; break;
        default: p=writeUTF8Char(m_t,p-1); m_col++; break;
      }
    }
  }
}
References c, Config_getInt, QCString::data(), QCString::isEmpty(), QCString::left(), m_col, OutputGenerator::m_t, newParagraph(), p, Doxygen::spaces, and writeUTF8Char().
Referenced by writeCodeLink().
codify() [2/2]
void RTFGenerator::codify (const QCString & s) [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
decIndentLevel() [1/2]
void RTFGenerator::decIndentLevel () [private]
Definition at line 1842 of file rtfgen.cpp.
{
  m_indentLevel--;
  if (m_indentLevel<0)
  {
    err("Negative indent level while generating RTF output!\n");
    m_indentLevel=0;
  }
}
References err(), and m_indentLevel.
Referenced by endConstraintList(), endExamples(), endIndent(), endIndexList(), endItemList(), endMemberDescription(), endMemberGroup(), and endParamList().
decIndentLevel() [2/2]
void RTFGenerator::decIndentLevel () [private]
docify() [1/2]
void RTFGenerator::docify (const QCString & s) [virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
Definition at line 1586 of file rtfgen.cpp.
{
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    while (*p)
    {
      c=*p++;
      switch (c)
      {
        case '{': m_t << "\\{"; break;
        case '}': m_t << "\\}"; break;
        case '\\': m_t << "\\\\"; break;
        default:
          {
            m_t << c;
          }
      }
      m_omitParagraph = FALSE;
    }
  }
}
References c, QCString::data(), FALSE, QCString::isEmpty(), m_omitParagraph, OutputGenerator::m_t, and p.
Referenced by addIndexItem(), endTitleHead(), startConstraintList(), startDescTable(), startExamples(), startParamList(), startSection(), writeChar(), writeObjectLink(), and writeStartAnnoItem().
docify() [2/2]
void RTFGenerator::docify (const QCString & s) [virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
endAnonTypeScope() [1/2]
void RTFGenerator::endAnonTypeScope (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 115 of file rtfgen.h.
{}
endAnonTypeScope() [2/2]
void RTFGenerator::endAnonTypeScope (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 115 of file rtfgen.h.
{}
endBold() [1/2]
void RTFGenerator::endBold () [inline], [virtual]
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 136 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
Referenced by endInlineHeader(), endMemberDoc(), startConstraintList(), startExamples(), startParamList(), and writeObjectLink().
endBold() [2/2]
void RTFGenerator::endBold () [inline], [virtual]
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 136 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endCallGraph() [1/2]
void RTFGenerator::endCallGraph (DotCallGraph & g) [virtual]
Implements OutputGenerator.
Definition at line 2176 of file rtfgen.cpp.
{
  newParagraph();
  QCString fn = g.writeGraph(m_t,GOF_BITMAP,EOF_Rtf,dir(),fileName(),m_relPath,FALSE);
  // display the file
  m_t << "{\n";
  m_t << rtf_Style_Reset << "\n";
  m_t << "\\par\\pard \\qc {\\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"";
  QCString imgExt = getDotImageExtension();
  m_t << fn << "." << imgExt;
  m_t << "\" \\\\d \\\\*MERGEFORMAT}{\\fldrslt IMAGE}}\\par\n";
  m_t << "}\n";
  DBG_RTF(m_t << "{\\comment (endCallGraph)}\n")
}
References DBG_RTF, OutputGenerator::dir(), EOF_Rtf, FALSE, OutputGenerator::fileName(), g, getDotImageExtension(), GOF_BITMAP, m_relPath, OutputGenerator::m_t, newParagraph(), and rtf_Style_Reset.
endCallGraph() [2/2]
void RTFGenerator::endCallGraph (DotCallGraph &) [virtual]
Implements OutputGenerator.
endCenter() [1/2]
void RTFGenerator::endCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 156 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endCenter() [2/2]
void RTFGenerator::endCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 156 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endClassDiagram() [1/2]
void RTFGenerator::endClassDiagram (const ClassDiagram & d, const QCString & filename, const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 1659 of file rtfgen.cpp.
{
  newParagraph();
  // create a png file
  d.writeImage(m_t,dir(),m_relPath,fileName,FALSE);
  // display the file
  m_t << "{\n";
  m_t << rtf_Style_Reset << "\n";
  m_t << "\\par\\pard \\qc {\\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"";
  m_t << fileName << ".png\"";
  m_t << " \\\\d \\\\*MERGEFORMAT}{\\fldrslt IMAGE}}\\par\n";
  m_t << "}\n";
}
References OutputGenerator::dir(), FALSE, OutputGenerator::fileName(), m_relPath, OutputGenerator::m_t, newParagraph(), rtf_Style_Reset, and ClassDiagram::writeImage().
endClassDiagram() [2/2]
void RTFGenerator::endClassDiagram (const ClassDiagram & , const QCString & filename, const QCString & name) [virtual]
Implements OutputGenerator.
endCodeFragment() [1/2]
void RTFGenerator::endCodeFragment (const QCString & style) [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 1724 of file rtfgen.cpp.
{
  endCodeLine();
  DBG_RTF(m_t << "{\\comment (endCodeFragment) }\n")
  m_t << "}\n";
  m_omitParagraph = TRUE;
}
References DBG_RTF, endCodeLine(), m_omitParagraph, OutputGenerator::m_t, and TRUE.
endCodeFragment() [2/2]
void RTFGenerator::endCodeFragment (const QCString & style) [virtual]
Ends a block of code
Implements CodeOutputInterface.
endCodeLine() [1/2]
void RTFGenerator::endCodeLine () [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 2692 of file rtfgen.cpp.
{
  if (m_doxyCodeLineOpen) lineBreak();
  m_doxyCodeLineOpen = false;
}
References lineBreak(), and m_doxyCodeLineOpen.
Referenced by endCodeFragment().
endCodeLine() [2/2]
void RTFGenerator::endCodeLine () [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
endCompoundTemplateParams() [1/2]
void RTFGenerator::endCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 121 of file rtfgen.h.
{ endSubsubsection(); }
References endSubsubsection().
endCompoundTemplateParams() [2/2]
void RTFGenerator::endCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 121 of file rtfgen.h.
{ endSubsubsection(); }
References endSubsubsection().
endConstraintDocs() [1/2]
void RTFGenerator::endConstraintDocs () [virtual]
Implements OutputGenerator.
Definition at line 2520 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endConstraintDocs)}\n")
  newParagraph();
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
endConstraintDocs() [2/2]
void RTFGenerator::endConstraintDocs () [virtual]
Implements OutputGenerator.
endConstraintList() [1/2]
void RTFGenerator::endConstraintList () [virtual]
Implements OutputGenerator.
Definition at line 2526 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endConstraintList)}\n")
  newParagraph();
  decIndentLevel();
  m_omitParagraph = TRUE;
  m_t << "}";
}
References DBG_RTF, decIndentLevel(), m_omitParagraph, OutputGenerator::m_t, newParagraph(), and TRUE.
endConstraintList() [2/2]
void RTFGenerator::endConstraintList () [virtual]
Implements OutputGenerator.
endConstraintParam() [1/2]
void RTFGenerator::endConstraintParam () [virtual]
Implements OutputGenerator.
Definition at line 2495 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endConstraintParam)}\n")
  endEmphasis();
  m_t << " : ";
}
References DBG_RTF, endEmphasis(), and OutputGenerator::m_t.
endConstraintParam() [2/2]
void RTFGenerator::endConstraintParam () [virtual]
Implements OutputGenerator.
endConstraintType() [1/2]
void RTFGenerator::endConstraintType () [virtual]
Implements OutputGenerator.
Definition at line 2508 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endConstraintType)}\n")
  endEmphasis();
  m_t << " ";
}
References DBG_RTF, endEmphasis(), and OutputGenerator::m_t.
endConstraintType() [2/2]
void RTFGenerator::endConstraintType () [virtual]
Implements OutputGenerator.
endContents() [1/2]
void RTFGenerator::endContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 191 of file rtfgen.h.
{}
endContents() [2/2]
void RTFGenerator::endContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 191 of file rtfgen.h.
{}
endDescForItem() [1/2]
void RTFGenerator::endDescForItem () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1546 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endDescForItem) }\n")
}
References DBG_RTF, and OutputGenerator::m_t.
endDescForItem() [2/2]
void RTFGenerator::endDescForItem () [virtual]
Implements BaseOutputDocInterface.
endDescItem() [1/2]
void RTFGenerator::endDescItem () [virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 1505 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endDescItem)}\n")
  m_t << "}\n";
  newParagraph();
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
endDescItem() [2/2]
void RTFGenerator::endDescItem () [virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
endDescription() [1/2]
void RTFGenerator::endDescription () [virtual]
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 1491 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endDescription)}" << "\n")
  newParagraph();
  m_t << "}";
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
endDescription() [2/2]
void RTFGenerator::endDescription () [virtual]
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
endDescTable() [1/2]
void RTFGenerator::endDescTable () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1788 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endDescTable)}\n")
  m_t << "}\n";
}
References DBG_RTF, and OutputGenerator::m_t.
endDescTable() [2/2]
void RTFGenerator::endDescTable () [virtual]
Implements BaseOutputDocInterface.
endDescTableData() [1/2]
void RTFGenerator::endDescTableData () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1820 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endDescTableData) }\n")
  m_t << "\\cell }{\\row }\n";
}
References DBG_RTF, and OutputGenerator::m_t.
endDescTableData() [2/2]
void RTFGenerator::endDescTableData () [virtual]
Implements BaseOutputDocInterface.
endDescTableRow() [1/2]
void RTFGenerator::endDescTableRow () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1798 of file rtfgen.cpp.
{
}
endDescTableRow() [2/2]
void RTFGenerator::endDescTableRow () [virtual]
Implements BaseOutputDocInterface.
endDescTableTitle() [1/2]
void RTFGenerator::endDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1808 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endDescTableTitle) }\n")
  m_t << "\\cell }";
}
References DBG_RTF, and OutputGenerator::m_t.
endDescTableTitle() [2/2]
void RTFGenerator::endDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
endDirDepGraph() [1/2]
void RTFGenerator::endDirDepGraph (DotDirDeps & g) [virtual]
Implements OutputGenerator.
Definition at line 2198 of file rtfgen.cpp.
{
  newParagraph();
  QCString fn = g.writeGraph(m_t,GOF_BITMAP,EOF_Rtf,dir(),fileName(),m_relPath,FALSE);
  // display the file
  m_t << "{\n";
  m_t << rtf_Style_Reset << "\n";
  m_t << "\\par\\pard \\qc {\\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"";
  QCString imgExt = getDotImageExtension();
  m_t << fn << "." << imgExt;
  m_t << "\" \\\\d \\\\*MERGEFORMAT}{\\fldrslt IMAGE}}\\par\n";
  m_t << "}\n";
  DBG_RTF(m_t << "{\\comment (endDirDepGraph)}\n")
}
References DBG_RTF, OutputGenerator::dir(), EOF_Rtf, FALSE, OutputGenerator::fileName(), g, getDotImageExtension(), GOF_BITMAP, m_relPath, OutputGenerator::m_t, newParagraph(), and rtf_Style_Reset.
endDirDepGraph() [2/2]
void RTFGenerator::endDirDepGraph (DotDirDeps & g) [virtual]
Implements OutputGenerator.
endDotGraph() [1/2]
void RTFGenerator::endDotGraph (DotClassGraph & g) [virtual]
Implements OutputGenerator.
Definition at line 2122 of file rtfgen.cpp.
{
  newParagraph();
  QCString fn =
    g.writeGraph(m_t,GOF_BITMAP,EOF_Rtf,dir(),fileName(),m_relPath,TRUE,FALSE);
  // display the file
  m_t << "{\n";
  m_t << rtf_Style_Reset << "\n";
  m_t << "\\par\\pard \\qc {\\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"";
  QCString imgExt = getDotImageExtension();
  m_t << fn << "." << imgExt;
  m_t << "\" \\\\d \\\\*MERGEFORMAT}{\\fldrslt IMAGE}}\\par\n";
  m_t << "}\n";
  newParagraph();
  DBG_RTF(m_t << "{\\comment (endDotGraph)}\n")
}
References DBG_RTF, OutputGenerator::dir(), EOF_Rtf, FALSE, OutputGenerator::fileName(), g, getDotImageExtension(), GOF_BITMAP, m_relPath, OutputGenerator::m_t, newParagraph(), rtf_Style_Reset, and TRUE.
endDotGraph() [2/2]
void RTFGenerator::endDotGraph (DotClassGraph &) [virtual]
Implements OutputGenerator.
endDoxyAnchor() [1/2]
void RTFGenerator::endDoxyAnchor (const QCString & fName, const QCString & anchor) [virtual]
Implements OutputGenerator.
Definition at line 1432 of file rtfgen.cpp.
{
  QCString ref;
  if (!fName.isEmpty())
  {
    ref+=stripPath(fName);
  }
  if (!anchor.isEmpty())
  {
    ref+='_';
    ref+=anchor;
  }
  DBG_RTF(m_t << "{\\comment endDoxyAnchor}\n")
  m_t << "{\\bkmkstart ";
  m_t << rtfFormatBmkStr(ref);
  m_t << "}\n";
  m_t << "{\\bkmkend ";
  m_t << rtfFormatBmkStr(ref);
  m_t << "}\n";
}
References DBG_RTF, QCString::isEmpty(), OutputGenerator::m_t, rtfFormatBmkStr(), and stripPath().
endDoxyAnchor() [2/2]
void RTFGenerator::endDoxyAnchor (const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
endEmphasis() [1/2]
void RTFGenerator::endEmphasis () [inline], [virtual]
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 134 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
Referenced by endConstraintParam(), endConstraintType(), endMemberDescription(), endMemberGroupDocs(), and endPageRef().
endEmphasis() [2/2]
void RTFGenerator::endEmphasis () [inline], [virtual]
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 134 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endExamples() [1/2]
void RTFGenerator::endExamples () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2376 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endExamples)}\n")
  m_omitParagraph = FALSE;
  newParagraph();
  decIndentLevel();
  m_omitParagraph = TRUE;
  m_t << "}";
}
References DBG_RTF, decIndentLevel(), FALSE, m_omitParagraph, OutputGenerator::m_t, newParagraph(), and TRUE.
endExamples() [2/2]
void RTFGenerator::endExamples () [virtual]
Implements BaseOutputDocInterface.
endFile() [1/2]
void RTFGenerator::endFile () [virtual]
Implements OutputGenerator.
Definition at line 379 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endFile}\n")
  m_t << "}";
  endPlainFile();
  setSourceFileName("");
}
References DBG_RTF, OutputGenerator::endPlainFile(), OutputGenerator::m_t, and setSourceFileName().
endFile() [2/2]
void RTFGenerator::endFile () [virtual]
Implements OutputGenerator.
endFontClass() [1/2]
void RTFGenerator::endFontClass () [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 2730 of file rtfgen.cpp.
{
  m_t << "}";
}
References OutputGenerator::m_t.
endFontClass() [2/2]
void RTFGenerator::endFontClass () [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
endGroupCollaboration() [1/2]
void RTFGenerator::endGroupCollaboration (DotGroupCollaboration & g) [virtual]
Implements OutputGenerator.
Definition at line 2167 of file rtfgen.cpp.
{
}
endGroupCollaboration() [2/2]
void RTFGenerator::endGroupCollaboration (DotGroupCollaboration & g) [virtual]
Implements OutputGenerator.
endGroupHeader() [1/2]
void RTFGenerator::endGroupHeader (int) [virtual]
Implements OutputGenerator.
Definition at line 1384 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endGroupHeader}\n")
  m_t << "\\par\n";
  m_t << rtf_Style_Reset << "\n";
}
References DBG_RTF, OutputGenerator::m_t, and rtf_Style_Reset.
Referenced by endMemberHeader().
endGroupHeader() [2/2]
void RTFGenerator::endGroupHeader (int) [virtual]
Implements OutputGenerator.
endHeaderSection() [1/2]
void RTFGenerator::endHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 103 of file rtfgen.h.
{}
endHeaderSection() [2/2]
void RTFGenerator::endHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 103 of file rtfgen.h.
{}
endHtmlLink() [1/2]
void RTFGenerator::endHtmlLink () [virtual]
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
Definition at line 1089 of file rtfgen.cpp.
{
  if (Config_getBool(RTF_HYPERLINKS))
  {
    m_t << "}}}\n";
  }
  else
  {
    endTypewriter();
  }
}
References Config_getBool, endTypewriter(), and OutputGenerator::m_t.
endHtmlLink() [2/2]
void RTFGenerator::endHtmlLink () [virtual]
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
endInclDepGraph() [1/2]
void RTFGenerator::endInclDepGraph (DotInclDepGraph & g) [virtual]
Implements OutputGenerator.
Definition at line 2146 of file rtfgen.cpp.
{
  newParagraph();
  QCString fn = g.writeGraph(m_t,GOF_BITMAP,EOF_Rtf,dir(),fileName(),m_relPath,FALSE);
  // display the file
  m_t << "{\n";
  m_t << rtf_Style_Reset << "\n";
  m_t << "\\par\\pard \\qc {\\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"";
  QCString imgExt = getDotImageExtension();
  m_t << fn << "." << imgExt;
  m_t << "\" \\\\d \\\\*MERGEFORMAT}{\\fldrslt IMAGE}}\\par\n";
  m_t << "}\n";
  DBG_RTF(m_t << "{\\comment (endInclDepGraph)}\n")
}
References DBG_RTF, OutputGenerator::dir(), EOF_Rtf, FALSE, OutputGenerator::fileName(), g, getDotImageExtension(), GOF_BITMAP, m_relPath, OutputGenerator::m_t, newParagraph(), and rtf_Style_Reset.
endInclDepGraph() [2/2]
void RTFGenerator::endInclDepGraph (DotInclDepGraph &) [virtual]
Implements OutputGenerator.
endIndent() [1/2]
void RTFGenerator::endIndent () [virtual]
Implements OutputGenerator.
Definition at line 1477 of file rtfgen.cpp.
{
  m_t << "}\n";
  decIndentLevel();
}
References decIndentLevel(), and OutputGenerator::m_t.
endIndent() [2/2]
void RTFGenerator::endIndent () [virtual]
Implements OutputGenerator.
endIndexItem() [1/2]
void RTFGenerator::endIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
Definition at line 1057 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endIndexItem)}\n")
  if (ref.isEmpty() && !fn.isEmpty())
  {
    m_t << "\\tab ";
    writeRTFReference(fn);
    m_t << "\n";
  }
  else
  {
    m_t << "\n";
  }
  m_omitParagraph = TRUE;
}
References DBG_RTF, QCString::isEmpty(), m_omitParagraph, OutputGenerator::m_t, TRUE, and writeRTFReference().
endIndexItem() [2/2]
void RTFGenerator::endIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
endIndexKey() [1/2]
void RTFGenerator::endIndexKey () [virtual]
Implements OutputGenerator.
Definition at line 1147 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endIndexKey)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
endIndexKey() [2/2]
void RTFGenerator::endIndexKey () [virtual]
Implements OutputGenerator.
endIndexList() [1/2]
void RTFGenerator::endIndexList () [virtual]
Implements OutputGenerator.
Definition at line 986 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endIndexList)}\n")
  if (!m_omitParagraph)
  {
    m_t << "\\par";
    m_omitParagraph = TRUE;
  }
  m_t << "}";
  decIndentLevel();
}
References DBG_RTF, decIndentLevel(), m_omitParagraph, OutputGenerator::m_t, and TRUE.
endIndexList() [2/2]
void RTFGenerator::endIndexList () [virtual]
Implements OutputGenerator.
endIndexListItem() [1/2]
void RTFGenerator::endIndexListItem () [virtual]
Implements OutputGenerator.
Definition at line 2540 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endIndexListItem)}\n")
  m_t << "\\par\n";
}
References DBG_RTF, and OutputGenerator::m_t.
endIndexListItem() [2/2]
void RTFGenerator::endIndexListItem () [virtual]
Implements OutputGenerator.
endIndexSection() [1/2]
void RTFGenerator::endIndexSection (IndexSections is) [virtual]
Implements OutputGenerator.
Definition at line 578 of file rtfgen.cpp.
{
  bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  QCString projectName = Config_getString(PROJECT_NAME);
  switch (is)
  {
    case isTitlePageStart:
      if (!rtf_title.isEmpty())
        // User has overridden document title in extensions file
        m_t << "}" << rtf_title;
      else
        m_t << "}" << projectName;
      break;
    case isTitlePageAuthor:
      {
        m_t << " doxygen " << getDoxygenVersion() << ".}\n";
        m_t << "{\\creatim " << dateToRTFDateString() << "}\n}";
        DBG_RTF(m_t << "{\\comment end of infoblock}\n");
        // setup for this section
        m_t << rtf_Style_Reset <<"\n";
        m_t << "\\sectd\\pgnlcrm\n";
        m_t << "{\\footer "<<rtf_Style["Footer"].reference() << "{\\chpgn}}\n";
        // the title entry
        DBG_RTF(m_t << "{\\comment begin title page}\n")
        m_t << rtf_Style_Reset << rtf_Style["SubTitle"].reference() << "\n"; // set to title style
        m_t << "\\vertalc\\qc\\par\\par\\par\\par\\par\\par\\par\n";
        if (!rtf_logoFilename.isEmpty())
        {
          m_t << "{\\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"" << rtf_logoFilename;
          m_t << "\" \\\\d \\\\*MERGEFORMAT} {\\fldrslt IMAGE }}\\par\\par\n";
        }
        if (!rtf_company.isEmpty())
        {
          m_t << rtf_company << "\\par\\par\n";
        }
        m_t << rtf_Style_Reset << rtf_Style["Title"].reference() << "\n"; // set to title style
        if (!rtf_title.isEmpty())
        {
          // User has overridden document title in extensions file
          m_t << "{\\field\\fldedit {\\*\\fldinst TITLE \\\\*MERGEFORMAT}{\\fldrslt " << rtf_title << "}}\\par\n";
        }
        else
        {
          auto parser { createDocParser() };
          auto ast { validatingParseText(*parser.get(), projectName) };
          if (ast)
          {
            m_t << "{\\field\\fldedit {\\*\\fldinst TITLE \\\\*MERGEFORMAT}{\\fldrslt ";
            writeDoc(ast.get(),0,0,0);
            m_t << "}}\\par\n";
          }
        }
        m_t << rtf_Style_Reset << rtf_Style["SubTitle"].reference() << "\n"; // set to title style
        m_t << "\\par\n";
        if (!rtf_documentType.isEmpty())
        {
          m_t << rtf_documentType << "\\par\n";
        }
        if (!rtf_documentId.isEmpty())
        {
          m_t << rtf_documentId << "\\par\n";
        }
        m_t << "\\par\\par\\par\\par\\par\\par\\par\\par\\par\\par\\par\\par\n";
        m_t << rtf_Style_Reset << rtf_Style["SubTitle"].reference() << "\n"; // set to subtitle style
        if (!rtf_author.isEmpty())
        {
          m_t << "{\\field\\fldedit {\\*\\fldinst AUTHOR \\\\*MERGEFORMAT}{\\fldrslt "<< rtf_author << " }}\\par\n";
        }
        else
        {
          m_t << "{\\field\\fldedit {\\*\\fldinst AUTHOR \\\\*MERGEFORMAT}{\\fldrslt AUTHOR}}\\par\n";
        }
        m_t << theTranslator->trVersion() << " " << Config_getString(PROJECT_NUMBER) << "\\par";
        m_t << "{\\field\\fldedit {\\*\\fldinst CREATEDATE \\\\*MERGEFORMAT}"
          "{\\fldrslt "<< dateToString(FALSE) << " }}\\par\n";
        m_t << "\\page\\page";
        DBG_RTF(m_t << "{\\comment End title page}\n")
        // table of contents section
        DBG_RTF(m_t << "{\\comment Table of contents}\n")
        m_t << "\\vertalt\n";
        m_t << rtf_Style_Reset << "\n";
        m_t << rtf_Style["Heading1"].reference();
        m_t << theTranslator->trRTFTableOfContents() << "\\par\n";
        m_t << rtf_Style_Reset << "\\par\n";
        m_t << "{\\field\\fldedit {\\*\\fldinst TOC \\\\f \\\\*MERGEFORMAT}{\\fldrslt Table of contents}}\\par\n";
        m_t << rtf_Style_Reset << "\n";
      }
      break;
    case isMainPage:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      if (!mainPageHasTitle())
      {
        m_t << "{\\tc \\v " << theTranslator->trMainPage() << "}\n";
      }
      else
      {
        m_t << "{\\tc \\v " << substitute(Doxygen::mainPage->title(),"%","") << "}\n";
      }
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
      //if (Config_getBool(GENERATE_TREEVIEW)) m_t << "main"; else m_t << "index";
      m_t << "index";
      m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case isModuleIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trModuleIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"modules.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case isDirIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trDirIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"dirs.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case isNamespaceIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      if (fortranOpt)
      {
          m_t << "{\\tc \\v " << theTranslator->trModulesIndex() << "}\n";
      }
      else
      {
          m_t << "{\\tc \\v " << theTranslator->trNamespaceIndex() << "}\n";
      }
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"namespaces.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case isConceptIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trConceptIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"concepts.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case isClassHierarchyIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trHierarchicalIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"hierarchy.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case isCompoundIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      if (fortranOpt)
      {
        m_t << "{\\tc \\v " << theTranslator->trCompoundIndexFortran() << "}\n";
      }
      else if (vhdlOpt)
      {
        m_t << "{\\tc \\v " << theTranslator->trDesignUnitIndex() << "}\n";
      }
      else
      {
        m_t << "{\\tc \\v " << theTranslator->trCompoundIndex() << "}\n";
      }
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"annotated.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case isFileIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trFileIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"files.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case isPageIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trPageIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"pages.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case isModuleDocumentation:
      {
        bool first=true;
        m_t << "{\\tc \\v " << theTranslator->trModuleDocumentation() << "}\n";
        for (const auto &gd : *Doxygen::groupLinkedMap)
        {
          if (!gd->isReference())
          {
            m_t << "\\par " << rtf_Style_Reset << "\n";
            if (!first)
            {
              beginRTFSection();
            }
            first=false;
            m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
            m_t << gd->getOutputFileBase();
            m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
          }
        }
      }
      break;
    case isDirDocumentation:
      {
        bool first=true;
        m_t << "{\\tc \\v " << theTranslator->trDirDocumentation() << "}\n";
        for (const auto &dd : *Doxygen::dirLinkedMap)
        {
          if (dd->isLinkableInProject())
          {
            m_t << "\\par " << rtf_Style_Reset << "\n";
            if (!first)
            {
              beginRTFSection();
            }
            first=false;
            m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
            m_t << dd->getOutputFileBase();
            m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
          }
        }
      }
      break;
    case isNamespaceDocumentation:
      {
        bool first=true;
        for (const auto &nd : *Doxygen::namespaceLinkedMap)
        {
          if (nd->isLinkableInProject() && !nd->isAlias())
          {
            m_t << "\\par " << rtf_Style_Reset << "\n";
            if (!first)
            {
              beginRTFSection();
            }
            first=false;
            m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
            m_t << nd->getOutputFileBase();
            m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
          }
        }
      }
      break;
    case isConceptDocumentation:
      {
        bool first=true;
        for (const auto &cd : *Doxygen::conceptLinkedMap)
        {
          if (cd->isLinkableInProject() && !cd->isAlias())
          {
            m_t << "\\par " << rtf_Style_Reset << "\n";
            if (!first)
            {
              beginRTFSection();
            }
            first=false;
            m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
            m_t << cd->getOutputFileBase();
            m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
          }
        }
      }
      break;
    case isClassDocumentation:
      {
        bool first=true;
        if (fortranOpt)
        {
          m_t << "{\\tc \\v " << theTranslator->trTypeDocumentation() << "}\n";
        }
        else
        {
          m_t << "{\\tc \\v " << theTranslator->trClassDocumentation() << "}\n";
        }
        for (const auto &cd : *Doxygen::classLinkedMap)
        {
          if (cd->isLinkableInProject() &&
              cd->templateMaster()==0 &&
             !cd->isEmbeddedInOuterScope() &&
             !cd->isAlias()
             )
          {
            m_t << "\\par " << rtf_Style_Reset << "\n";
            if (!first)
            {
              beginRTFSection();
            }
            first=false;
            m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
            m_t << cd->getOutputFileBase();
            m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
          }
        }
      }
      break;
    case isFileDocumentation:
      {
        bool isFirst=TRUE;
        m_t << "{\\tc \\v " << theTranslator->trFileDocumentation() << "}\n";
        for (const auto &fn : *Doxygen::inputNameLinkedMap)
        {
          for (const auto &fd : *fn)
          {
            if (fd->isLinkableInProject())
            {
              m_t << "\\par " << rtf_Style_Reset << "\n";
              if (!isFirst)
              {
                beginRTFSection();
              }
              isFirst=FALSE;
              m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
              m_t << fd->getOutputFileBase();
              m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
            }
            if (fd->generateSourceFile())
            {
              m_t << "\\par " << rtf_Style_Reset << "\n";
              if (!isFirst)
              {
                beginRTFSection();
              }
              isFirst=FALSE;
              m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
              m_t << fd->getSourceFileBase();
              m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
            }
          }
        }
      }
      break;
    case isExampleDocumentation:
      {
        //m_t << "}\n";
        bool isFirst=true;
        m_t << "{\\tc \\v " << theTranslator->trExampleDocumentation() << "}\n";
        for (const auto &pd : *Doxygen::exampleLinkedMap)
        {
          m_t << "\\par " << rtf_Style_Reset << "\n";
          if (!isFirst)
          {
            beginRTFSection();
          }
          isFirst=false;
          m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
          m_t << pd->getOutputFileBase();
          m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
        }
      }
      break;
    case isPageDocumentation:
      break;
    case isPageDocumentation2:
      {
        m_t << "}";
        m_t << "\\par " << rtf_Style_Reset << "\n";
      }
      break;
    case isEndIndex:
      beginRTFChapter();
      m_t << rtf_Style["Heading1"].reference();
      m_t << theTranslator->trRTFGeneralIndex() << "\\par \n";
      m_t << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trRTFGeneralIndex() << "}\n";
      m_t << "{\\field\\fldedit {\\*\\fldinst INDEX \\\\c2 \\\\*MERGEFORMAT}{\\fldrslt INDEX}}\n";
      break;
   }
}
References beginRTFChapter(), beginRTFSection(), Doxygen::classLinkedMap, Doxygen::conceptLinkedMap, Config_getBool, Config_getString, createDocParser(), dateToRTFDateString(), dateToString(), DBG_RTF, Doxygen::dirLinkedMap, Doxygen::exampleLinkedMap, FALSE, getDoxygenVersion(), Doxygen::groupLinkedMap, Doxygen::inputNameLinkedMap, isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isConceptDocumentation, isConceptIndex, isDirDocumentation, isDirIndex, QCString::isEmpty(), isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, isTitlePageAuthor, isTitlePageStart, OutputGenerator::m_t, Doxygen::mainPage, mainPageHasTitle(), Doxygen::namespaceLinkedMap, rtf_author, rtf_company, rtf_documentId, rtf_documentType, rtf_logoFilename, rtf_Style, rtf_Style_Reset, rtf_title, substitute(), theTranslator, Translator::trClassDocumentation(), Translator::trCompoundIndex(), Translator::trCompoundIndexFortran(), Translator::trConceptIndex(), Translator::trDesignUnitIndex(), Translator::trDirDocumentation(), Translator::trDirIndex(), Translator::trExampleDocumentation(), Translator::trFileDocumentation(), Translator::trFileIndex(), Translator::trHierarchicalIndex(), Translator::trMainPage(), Translator::trModuleDocumentation(), Translator::trModuleIndex(), Translator::trModulesIndex(), Translator::trNamespaceIndex(), Translator::trPageIndex(), Translator::trRTFGeneralIndex(), Translator::trRTFTableOfContents(), Translator::trTypeDocumentation(), TRUE, Translator::trVersion(), validatingParseText(), and writeDoc().
endIndexSection() [2/2]
void RTFGenerator::endIndexSection (IndexSections) [virtual]
Implements OutputGenerator.
endIndexValue() [1/2]
void RTFGenerator::endIndexValue (const QCString & name, bool hasBrief) [virtual]
Implements OutputGenerator.
Definition at line 1159 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endIndexValue)}\n")
  if (hasBrief) m_t << ")";
  m_t << "} ";
  if (!name.isEmpty())
  {
    m_t << "\\tab ";
    writeRTFReference(name);
    m_t << "\n";
  }
  else
  {
    m_t << "\n";
  }
  m_omitParagraph=FALSE;
  newParagraph();
}
References DBG_RTF, FALSE, m_omitParagraph, OutputGenerator::m_t, setup::name, newParagraph(), and writeRTFReference().
endIndexValue() [2/2]
void RTFGenerator::endIndexValue (const QCString & , bool) [virtual]
Implements OutputGenerator.
endInlineHeader() [1/2]
void RTFGenerator::endInlineHeader () [virtual]
Implements OutputGenerator.
Definition at line 2554 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endInlineHeader)}\n")
  endBold();
  m_t << "\\par";
  m_t << "}\n";
}
References DBG_RTF, endBold(), and OutputGenerator::m_t.
endInlineHeader() [2/2]
void RTFGenerator::endInlineHeader () [virtual]
Implements OutputGenerator.
endInlineMemberDoc() [1/2]
void RTFGenerator::endInlineMemberDoc () [virtual]
Implements OutputGenerator.
Definition at line 2639 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endInlineMemberDoc)}\n")
  m_t << "\\cell }{\\row }\n";
}
References DBG_RTF, and OutputGenerator::m_t.
endInlineMemberDoc() [2/2]
void RTFGenerator::endInlineMemberDoc () [virtual]
Implements OutputGenerator.
endInlineMemberName() [1/2]
void RTFGenerator::endInlineMemberName () [virtual]
Implements OutputGenerator.
Definition at line 2627 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endInlineMemberName)}\n")
  m_t << "\\cell }";
}
References DBG_RTF, and OutputGenerator::m_t.
endInlineMemberName() [2/2]
void RTFGenerator::endInlineMemberName () [virtual]
Implements OutputGenerator.
endInlineMemberType() [1/2]
void RTFGenerator::endInlineMemberType () [virtual]
Implements OutputGenerator.
Definition at line 2615 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endInlineMemberType)}\n")
  m_t << "\\cell }";
}
References DBG_RTF, and OutputGenerator::m_t.
endInlineMemberType() [2/2]
void RTFGenerator::endInlineMemberType () [virtual]
Implements OutputGenerator.
endItemList() [1/2]
void RTFGenerator::endItemList () [virtual]
end bullet list
Implements BaseOutputDocInterface.
Definition at line 1012 of file rtfgen.cpp.
{
  newParagraph();
  DBG_RTF(m_t << "{\\comment (endItemList level=" << indentLevel() << ")}\n")
  m_t << "}";
  decIndentLevel();
  m_omitParagraph = TRUE;
}
References DBG_RTF, decIndentLevel(), indentLevel(), m_omitParagraph, OutputGenerator::m_t, newParagraph(), and TRUE.
endItemList() [2/2]
void RTFGenerator::endItemList () [virtual]
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
endItemListItem() [1/2]
void RTFGenerator::endItemListItem () [virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 1041 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endItemListItem)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
endItemListItem() [2/2]
void RTFGenerator::endItemListItem () [virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
endLabels() [1/2]
void RTFGenerator::endLabels () [virtual]
Implements OutputGenerator.
Definition at line 2708 of file rtfgen.cpp.
{
}
endLabels() [2/2]
void RTFGenerator::endLabels () [virtual]
Implements OutputGenerator.
endMemberDeclaration() [1/2]
void RTFGenerator::endMemberDeclaration (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 163 of file rtfgen.h.
{}
endMemberDeclaration() [2/2]
void RTFGenerator::endMemberDeclaration (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 163 of file rtfgen.h.
{}
endMemberDescription() [1/2]
void RTFGenerator::endMemberDescription () [virtual]
Implements OutputGenerator.
Definition at line 1521 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endMemberDescription)}\n")
  endEmphasis();
  //newParagraph();
  decIndentLevel();
  m_t << "\\par";
  m_t << "}\n";
  m_omitParagraph = TRUE;
}
References DBG_RTF, decIndentLevel(), endEmphasis(), m_omitParagraph, OutputGenerator::m_t, and TRUE.
endMemberDescription() [2/2]
void RTFGenerator::endMemberDescription () [virtual]
Implements OutputGenerator.
endMemberDoc() [1/2]
void RTFGenerator::endMemberDoc (bool) [virtual]
Implements OutputGenerator.
Definition at line 1413 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endMemberDoc}\n")
  //const QCString &style = styleStack.pop();
  //printf("RTFGenerator::endMemberDoc() '%s'\n",style);
  //ASSERT(style==rtf_Style["Heading4"].reference());
  endBold();
  m_t << "}\n";
  newParagraph();
}
References DBG_RTF, endBold(), OutputGenerator::m_t, and newParagraph().
endMemberDoc() [2/2]
void RTFGenerator::endMemberDoc (bool) [virtual]
Implements OutputGenerator.
endMemberDocList() [1/2]
void RTFGenerator::endMemberDocList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 109 of file rtfgen.h.
{}
endMemberDocList() [2/2]
void RTFGenerator::endMemberDocList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 109 of file rtfgen.h.
{}
endMemberDocName() [1/2]
void RTFGenerator::endMemberDocName () [inline], [virtual]
Implements OutputGenerator.
Definition at line 229 of file rtfgen.h.
{}
endMemberDocName() [2/2]
void RTFGenerator::endMemberDocName () [inline], [virtual]
Implements OutputGenerator.
Definition at line 229 of file rtfgen.h.
{}
endMemberDocPrefixItem() [1/2]
void RTFGenerator::endMemberDocPrefixItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 227 of file rtfgen.h.
{}
endMemberDocPrefixItem() [2/2]
void RTFGenerator::endMemberDocPrefixItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 227 of file rtfgen.h.
{}
endMemberDocSimple() [1/2]
void RTFGenerator::endMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
Definition at line 2603 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endMemberDocSimple)}\n")
  m_t << "}\n";
}
References DBG_RTF, and OutputGenerator::m_t.
endMemberDocSimple() [2/2]
void RTFGenerator::endMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
endMemberGroup() [1/2]
void RTFGenerator::endMemberGroup (bool hasHeader) [virtual]
Implements OutputGenerator.
Definition at line 2354 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endMemberGroup}\n")
  if (hasHeader) decIndentLevel();
  m_t << "}";
}
References DBG_RTF, decIndentLevel(), and OutputGenerator::m_t.
endMemberGroup() [2/2]
void RTFGenerator::endMemberGroup (bool) [virtual]
Implements OutputGenerator.
endMemberGroupDocs() [1/2]
void RTFGenerator::endMemberGroupDocs () [virtual]
Implements OutputGenerator.
Definition at line 2341 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endMemberGroupDocs}\n")
  endEmphasis();
  newParagraph();
}
References DBG_RTF, endEmphasis(), OutputGenerator::m_t, and newParagraph().
endMemberGroupDocs() [2/2]
void RTFGenerator::endMemberGroupDocs () [virtual]
Implements OutputGenerator.
endMemberGroupHeader() [1/2]
void RTFGenerator::endMemberGroupHeader () [virtual]
Implements OutputGenerator.
Definition at line 2328 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endMemberGroupHeader}\n")
  newParagraph();
  m_t << rtf_Style_Reset << rtf_CList_DepthStyle();
}
References DBG_RTF, OutputGenerator::m_t, newParagraph(), rtf_CList_DepthStyle(), and rtf_Style_Reset.
endMemberGroupHeader() [2/2]
void RTFGenerator::endMemberGroupHeader () [virtual]
Implements OutputGenerator.
endMemberHeader() [1/2]
void RTFGenerator::endMemberHeader () [inline], [virtual]
Implements OutputGenerator.
Definition at line 105 of file rtfgen.h.
{ endGroupHeader(FALSE); }
References endGroupHeader(), and FALSE.
endMemberHeader() [2/2]
void RTFGenerator::endMemberHeader () [inline], [virtual]
Implements OutputGenerator.
Definition at line 105 of file rtfgen.h.
{ endGroupHeader(FALSE); }
References endGroupHeader(), and FALSE.
endMemberItem() [1/2]
void RTFGenerator::endMemberItem () [virtual]
Implements OutputGenerator.
Definition at line 1682 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endMemberItem }\n")
  newParagraph();
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
endMemberItem() [2/2]
void RTFGenerator::endMemberItem () [virtual]
Implements OutputGenerator.
endMemberList() [1/2]
void RTFGenerator::endMemberList () [virtual]
Implements OutputGenerator.
Definition at line 1750 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endMemberList) }\n")
  m_t << "}\n";
#ifdef DELETEDCODE
  if (!insideTabbing)
    m_t << "\\end{CompactItemize}\n";
#endif
}
References DBG_RTF, and OutputGenerator::m_t.
endMemberList() [2/2]
void RTFGenerator::endMemberList () [virtual]
Implements OutputGenerator.
endMemberSections() [1/2]
void RTFGenerator::endMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 101 of file rtfgen.h.
{}
endMemberSections() [2/2]
void RTFGenerator::endMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 101 of file rtfgen.h.
{}
endMemberSubtitle() [1/2]
void RTFGenerator::endMemberSubtitle () [virtual]
Implements OutputGenerator.
Definition at line 1947 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endMemberSubtitle}\n")
  newParagraph();
  m_t << "}\n";
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
endMemberSubtitle() [2/2]
void RTFGenerator::endMemberSubtitle () [virtual]
Implements OutputGenerator.
endMemberTemplateParams() [1/2]
void RTFGenerator::endMemberTemplateParams (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 119 of file rtfgen.h.
{}
endMemberTemplateParams() [2/2]
void RTFGenerator::endMemberTemplateParams (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 119 of file rtfgen.h.
{}
endPageRef() [1/2]
void RTFGenerator::endPageRef (const QCString & clname, const QCString & anchor) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1277 of file rtfgen.cpp.
{
  QCString ref;
  if (!clname.isEmpty())
  {
    ref+=clname;
  }
  if (!anchor.isEmpty())
  {
    ref+='_';
    ref+=anchor;
  }
  writeRTFReference(ref);
  endEmphasis();
  m_t << ")";
}
References endEmphasis(), QCString::isEmpty(), OutputGenerator::m_t, and writeRTFReference().
endPageRef() [2/2]
void RTFGenerator::endPageRef (const QCString & , const QCString &) [virtual]
Implements BaseOutputDocInterface.
endParagraph() [1/2]
void RTFGenerator::endParagraph () [virtual]
Ends a paragraph
Implements BaseOutputDocInterface.
Definition at line 1933 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endParagraph}\n")
  m_t << "}\\par\n";
  m_omitParagraph = TRUE;
}
References DBG_RTF, m_omitParagraph, OutputGenerator::m_t, and TRUE.
endParagraph() [2/2]
void RTFGenerator::endParagraph () [virtual]
Ends a paragraph
Implements BaseOutputDocInterface.
endParameterList() [1/2]
void RTFGenerator::endParameterList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 235 of file rtfgen.h.
{}
endParameterList() [2/2]
void RTFGenerator::endParameterList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 235 of file rtfgen.h.
{}
endParameterName() [1/2]
void RTFGenerator::endParameterName (bool , bool , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 233 of file rtfgen.h.
{}
endParameterName() [2/2]
void RTFGenerator::endParameterName (bool , bool , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 233 of file rtfgen.h.
{}
endParameterType() [1/2]
void RTFGenerator::endParameterType () [virtual]
Implements OutputGenerator.
Definition at line 2419 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endParameterType)}\n")
  m_t << " ";
}
References DBG_RTF, and OutputGenerator::m_t.
endParameterType() [2/2]
void RTFGenerator::endParameterType () [virtual]
Implements OutputGenerator.
endParamList() [1/2]
void RTFGenerator::endParamList () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2401 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endParamList)}\n")
  newParagraph();
  decIndentLevel();
  m_omitParagraph = TRUE;
  m_t << "}";
}
References DBG_RTF, decIndentLevel(), m_omitParagraph, OutputGenerator::m_t, newParagraph(), and TRUE.
endParamList() [2/2]
void RTFGenerator::endParamList () [virtual]
Implements BaseOutputDocInterface.
endProjectNumber() [1/2]
void RTFGenerator::endProjectNumber () [virtual]
Implements OutputGenerator.
Definition at line 394 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endProjectNumber }\n")
}
References DBG_RTF, and OutputGenerator::m_t.
endProjectNumber() [2/2]
void RTFGenerator::endProjectNumber () [virtual]
Implements OutputGenerator.
endQuickIndices() [1/2]
void RTFGenerator::endQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 184 of file rtfgen.h.
{}
endQuickIndices() [2/2]
void RTFGenerator::endQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 184 of file rtfgen.h.
{}
endSection() [1/2]
void RTFGenerator::endSection (const QCString & lab, SectionType) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1576 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endSection)}\n")
  // make bookmark
  m_omitParagraph=FALSE;
  newParagraph();
  writeAnchor(QCString(),lab);
  m_t << "}";
}
References DBG_RTF, FALSE, m_omitParagraph, OutputGenerator::m_t, newParagraph(), and writeAnchor().
endSection() [2/2]
void RTFGenerator::endSection (const QCString & , SectionType) [virtual]
Implements BaseOutputDocInterface.
endSmall() [1/2]
void RTFGenerator::endSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 158 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endSmall() [2/2]
void RTFGenerator::endSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 158 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endSubsection() [1/2]
void RTFGenerator::endSubsection () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1187 of file rtfgen.cpp.
{
  newParagraph();
  m_t << rtf_Style_Reset << "\n";
}
References OutputGenerator::m_t, newParagraph(), and rtf_Style_Reset.
endSubsection() [2/2]
void RTFGenerator::endSubsection () [virtual]
Implements BaseOutputDocInterface.
endSubsubsection() [1/2]
void RTFGenerator::endSubsubsection () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1202 of file rtfgen.cpp.
{
  newParagraph();
  m_t << "}\n";
}
References OutputGenerator::m_t, and newParagraph().
Referenced by endCompoundTemplateParams().
endSubsubsection() [2/2]
void RTFGenerator::endSubsubsection () [virtual]
Implements BaseOutputDocInterface.
endTextBlock() [1/2]
void RTFGenerator::endTextBlock (bool) [virtual]
Implements OutputGenerator.
Definition at line 1907 of file rtfgen.cpp.
{
  newParagraph();
  DBG_RTF(m_t << "{\\comment endTextBlock}\n")
  m_t << "}\n";
  //m_omitParagraph = TRUE;
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
endTextBlock() [2/2]
void RTFGenerator::endTextBlock (bool) [virtual]
Implements OutputGenerator.
endTextLink() [1/2]
void RTFGenerator::endTextLink () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1230 of file rtfgen.cpp.
{
  if (Config_getBool(RTF_HYPERLINKS))
  {
    m_t << "}}}\n";
  }
}
References Config_getBool, and OutputGenerator::m_t.
endTextLink() [2/2]
void RTFGenerator::endTextLink () [virtual]
Implements BaseOutputDocInterface.
endTitle() [1/2]
void RTFGenerator::endTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 60 of file rtfgen.h.
{}
endTitle() [2/2]
void RTFGenerator::endTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 60 of file rtfgen.h.
{}
endTitleHead() [1/2]
void RTFGenerator::endTitleHead (const QCString & fileName, const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 1335 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endTitleHead}\n")
  m_t << "\\par " << rtf_Style_Reset << "\n";
  if (!name.isEmpty())
  {
    // make table of contents entry
    m_t << "{\\tc\\tcl2 \\v ";
    docify(name);
    m_t << "}\n";
    // make an index entry
    addIndexItem(name,QCString());
  }
  if (!fileName.isEmpty())
  {
    writeAnchor(fileName,QCString());
  }
}
References addIndexItem(), DBG_RTF, docify(), OutputGenerator::fileName(), QCString::isEmpty(), OutputGenerator::m_t, setup::name, rtf_Style_Reset, and writeAnchor().
endTitleHead() [2/2]
void RTFGenerator::endTitleHead (const QCString & , const QCString & name) [virtual]
Implements OutputGenerator.
endTypewriter() [1/2]
void RTFGenerator::endTypewriter () [inline], [virtual]
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 94 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
Referenced by endHtmlLink().
endTypewriter() [2/2]
void RTFGenerator::endTypewriter () [inline], [virtual]
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 94 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
exceptionEntry() [1/2]
void RTFGenerator::exceptionEntry (const QCString & prefix, bool closeBracket) [virtual]
Implements OutputGenerator.
Definition at line 2425 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (exceptionEntry)}\n")
  if (!prefix.isEmpty())
  {
    m_t << " " << prefix << "(";
  }
  else if (closeBracket)
  {
    m_t << ")";
  }
  m_t << " ";
}
References DBG_RTF, QCString::isEmpty(), and OutputGenerator::m_t.
exceptionEntry() [2/2]
void RTFGenerator::exceptionEntry (const QCString & , bool) [virtual]
Implements OutputGenerator.
incIndentLevel() [1/2]
void RTFGenerator::incIndentLevel () [private]
Definition at line 1833 of file rtfgen.cpp.
{
  m_indentLevel++;
  if (m_indentLevel>=maxIndentLevels)
  {
    err("Maximum indent level (%d) exceeded while generating RTF output!\n",maxIndentLevels);
  }
}
References err(), m_indentLevel, and maxIndentLevels.
Referenced by startConstraintList(), startExamples(), startIndent(), startIndexList(), startItemList(), startMemberDescription(), startMemberGroupHeader(), and startParamList().
incIndentLevel() [2/2]
void RTFGenerator::incIndentLevel () [private]
indentLevel() [1/2]
int RTFGenerator::indentLevel () const [private]
Definition at line 1828 of file rtfgen.cpp.
{
  return std::min(m_indentLevel,maxIndentLevels-1);
}
References m_indentLevel, and maxIndentLevels.
Referenced by endItemList(), rtf_BList_DepthStyle(), rtf_CList_DepthStyle(), rtf_Code_DepthStyle(), rtf_DList_DepthStyle(), rtf_EList_DepthStyle(), rtf_LCList_DepthStyle(), startItemList(), and startItemListItem().
indentLevel() [2/2]
int RTFGenerator::indentLevel () const [private]
init() [1/2]
void RTFGenerator::init () [static]
Definition at line 165 of file rtfgen.cpp.
{
  QCString dir=Config_getString(RTF_OUTPUT);
  Dir d(dir.str());
  if (!d.exists() && !d.mkdir(dir.str()))
  {
    term("Could not create output directory %s\n",qPrint(dir));
  }
  // first duplicate strings of rtf_Style_Default
  const struct Rtf_Style_Default* def = rtf_Style_Default;
  while (def->reference)
  {
    if (def->definition == 0)
    {
      err("Internal: rtf_Style_Default[%s] has no definition.\n", def->name);
    }
    else
    {
      rtf_Style.insert(std::make_pair(def->name, StyleData(def->reference, def->definition)));
    }
    def++;
  }
  // overwrite some (or all) definitions from file
  QCString rtfStyleSheetFile = Config_getString(RTF_STYLESHEET_FILE);
  if (!rtfStyleSheetFile.isEmpty())
  {
    loadStylesheet(rtfStyleSheetFile, rtf_Style);
  }
  // If user has defined an extension file, load its contents.
  QCString rtfExtensionsFile = Config_getString(RTF_EXTENSIONS_FILE);
  if (!rtfExtensionsFile.isEmpty())
  {
    loadExtensions(rtfExtensionsFile);
  }
  createSubDirs(d);
}
References Config_getString, createSubDirs(), Rtf_Style_Default::definition, OutputGenerator::dir(), err(), Dir::exists(), QCString::isEmpty(), loadExtensions(), loadStylesheet(), Dir::mkdir(), Rtf_Style_Default::name, qPrint(), Rtf_Style_Default::reference, rtf_Style, rtf_Style_Default, QCString::str(), and term().
Referenced by generateOutput().
init() [2/2]
static void RTFGenerator::init () [static]
insertMemberAlign() [1/2]
void RTFGenerator::insertMemberAlign (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 122 of file rtfgen.h.
{}
insertMemberAlign() [2/2]
void RTFGenerator::insertMemberAlign (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 122 of file rtfgen.h.
{}
insertMemberAlignLeft() [1/2]
void RTFGenerator::insertMemberAlignLeft (int , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 123 of file rtfgen.h.
{}
insertMemberAlignLeft() [2/2]
void RTFGenerator::insertMemberAlignLeft (int , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 123 of file rtfgen.h.
{}
lastIndexPage() [1/2]
void RTFGenerator::lastIndexPage () [virtual]
Implements OutputGenerator.
Definition at line 948 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment Beginning Body of RTF Document}\n")
  // end page and setup for rest of document
  m_t << "\\sect \\sbkpage \\pgndec \\pgnrestart\n";
  m_t << "\\sect \\sectd \\sbknone\n";
  // set new footer with arabic numbers
  m_t << "{\\footer "<< rtf_Style["Footer"].reference() << "{\\chpgn}}\n";
}
References DBG_RTF, OutputGenerator::m_t, and rtf_Style.
lastIndexPage() [2/2]
void RTFGenerator::lastIndexPage () [virtual]
Implements OutputGenerator.
lineBreak() [1/2]
void RTFGenerator::lineBreak (const QCString & style = QCString()) [virtual]
Implements BaseOutputDocInterface.
Definition at line 964 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (lineBreak)}" << "\n")
  m_t << "\\par\n";
  m_omitParagraph = TRUE;
}
References DBG_RTF, m_omitParagraph, OutputGenerator::m_t, and TRUE.
Referenced by endCodeLine().
lineBreak() [2/2]
void RTFGenerator::lineBreak (const QCString & style = QCString()) [virtual]
Implements BaseOutputDocInterface.
newParagraph() [1/2]
void RTFGenerator::newParagraph ()
Definition at line 1915 of file rtfgen.cpp.
{
  if (!m_omitParagraph)
  {
    DBG_RTF(m_t << "{\\comment (newParagraph)}\n")
    m_t << "\\par\n";
  }
  m_omitParagraph = FALSE;
}
References DBG_RTF, FALSE, m_omitParagraph, and OutputGenerator::m_t.
Referenced by codify(), endCallGraph(), endClassDiagram(), endConstraintDocs(), endConstraintList(), endDescItem(), endDescription(), endDirDepGraph(), endDotGraph(), endExamples(), endInclDepGraph(), endIndexValue(), endItemList(), endMemberDoc(), endMemberGroupDocs(), endMemberGroupHeader(), endMemberItem(), endMemberSubtitle(), endParamList(), endSection(), endSubsection(), endSubsubsection(), endTextBlock(), startConstraintList(), startDescItem(), startDescList(), startExamples(), startItemList(), startItemListItem(), startParagraph(), startParamList(), and writeEndAnnoItem().
newParagraph() [2/2]
void RTFGenerator::newParagraph ()
operator=() [1/2]
RTFGenerator & RTFGenerator::operator= (const RTFGenerator & og)
Definition at line 72 of file rtfgen.cpp.
{
  OutputGenerator::operator=(og);
  return *this;
}
References OutputGenerator::operator=().
operator=() [2/2]
RTFGenerator & RTFGenerator::operator= (const RTFGenerator &)
preProcessFileInplace() [1/2]
bool RTFGenerator::preProcessFileInplace (const QCString & path, const QCString & name) [static]
This is an API to a VERY brittle RTF preprocessor that combines nested RTF files. This version replaces the infile with the new file
Definition at line 2263 of file rtfgen.cpp.
{
  static bool rtfDebug = Debug::isFlagSet(Debug::Rtf);
  Dir d(path.str());
  // store the original directory
  if (!d.exists())
  {
    err("Output dir %s does not exist!\n",qPrint(path));
    return FALSE;
  }
  std::string oldDir = Dir::currentDirPath();
  // go to the html output directory (i.e. path)
  Dir::setCurrent(d.absPath());
  Dir thisDir;
  QCString combinedName = path+"/combined.rtf";
  QCString mainRTFName = path+"/"+name;
  std::ofstream f(combinedName.str(),std::ofstream::out | std::ofstream::binary);
  if (!f.is_open())
  {
    err("Failed to open %s for writing!\n",combinedName.data());
    Dir::setCurrent(oldDir);
    return FALSE;
  }
  TextStream outt(&f);
  if (!preProcessFile(thisDir,mainRTFName,outt))
  {
    // it failed, remove the temp file
    outt.flush();
    f.close();
    if (!rtfDebug) thisDir.remove(combinedName.str());
    Dir::setCurrent(oldDir);
    return FALSE;
  }
  // everything worked, move the files
  outt.flush();
  f.close();
  if (!rtfDebug)
  {
    thisDir.remove(mainRTFName.str());
  }
  else
  {
    thisDir.rename(mainRTFName.str(),mainRTFName.str() + ".org");
  }
  thisDir.rename(combinedName.str(),mainRTFName.str());
  testRTFOutput(mainRTFName);
  Dir::setCurrent(oldDir);
  return TRUE;
}
References Dir::absPath(), Dir::currentDirPath(), QCString::data(), err(), Dir::exists(), f, FALSE, TextStream::flush(), Debug::isFlagSet(), setup::name, out, preProcessFile(), qPrint(), Dir::remove(), Dir::rename(), Debug::Rtf, Dir::setCurrent(), QCString::str(), string, testRTFOutput(), and TRUE.
Referenced by generateOutput().
preProcessFileInplace() [2/2]
static bool RTFGenerator::preProcessFileInplace (const QCString & path, const QCString & name) [static]
rtf_BList_DepthStyle() [1/2]
QCString RTFGenerator::rtf_BList_DepthStyle () [private]
Definition at line 1867 of file rtfgen.cpp.
{
  QCString n=makeIndexName("ListBullet",indentLevel());
  return rtf_Style[n.str()].reference();
}
References indentLevel(), makeIndexName(), n, and rtf_Style.
Referenced by startItemListItem(), startMemberGroup(), and startMemberItem().
rtf_BList_DepthStyle() [2/2]
QCString RTFGenerator::rtf_BList_DepthStyle () [private]
rtf_CList_DepthStyle() [1/2]
QCString RTFGenerator::rtf_CList_DepthStyle () [private]
Definition at line 1853 of file rtfgen.cpp.
{
  QCString n=makeIndexName("ListContinue",indentLevel());
  return rtf_Style[n.str()].reference();
}
References indentLevel(), makeIndexName(), n, and rtf_Style.
Referenced by endMemberGroupHeader(), startIndent(), startMemberDescription(), and startMemberSubtitle().
rtf_CList_DepthStyle() [2/2]
QCString RTFGenerator::rtf_CList_DepthStyle () [private]
rtf_Code_DepthStyle() [1/2]
QCString RTFGenerator::rtf_Code_DepthStyle () [private]
Definition at line 1886 of file rtfgen.cpp.
{
  QCString n=makeIndexName("CodeExample",indentLevel());
  return rtf_Style[n.str()].reference();
}
References indentLevel(), makeIndexName(), n, and rtf_Style.
Referenced by startCodeFragment().
rtf_Code_DepthStyle() [2/2]
QCString RTFGenerator::rtf_Code_DepthStyle () [private]
rtf_DList_DepthStyle() [1/2]
QCString RTFGenerator::rtf_DList_DepthStyle () [private]
Definition at line 1880 of file rtfgen.cpp.
{
  QCString n=makeIndexName("DescContinue",indentLevel());
  return rtf_Style[n.str()].reference();
}
References indentLevel(), makeIndexName(), n, and rtf_Style.
Referenced by startConstraintList(), startDescription(), startDescTable(), startExamples(), startMemberDocSimple(), and startParamList().
rtf_DList_DepthStyle() [2/2]
QCString RTFGenerator::rtf_DList_DepthStyle () [private]
rtf_EList_DepthStyle() [1/2]
QCString RTFGenerator::rtf_EList_DepthStyle () [private]
Definition at line 1874 of file rtfgen.cpp.
{
  QCString n=makeIndexName("ListEnum",indentLevel());
  return rtf_Style[n.str()].reference();
}
References indentLevel(), makeIndexName(), n, and rtf_Style.
Referenced by startItemListItem().
rtf_EList_DepthStyle() [2/2]
QCString RTFGenerator::rtf_EList_DepthStyle () [private]
rtf_LCList_DepthStyle() [1/2]
QCString RTFGenerator::rtf_LCList_DepthStyle () [private]
Definition at line 1860 of file rtfgen.cpp.
{
  QCString n=makeIndexName("LatexTOC",indentLevel());
  return rtf_Style[n.str()].reference();
}
References indentLevel(), makeIndexName(), n, and rtf_Style.
Referenced by startIndexList().
rtf_LCList_DepthStyle() [2/2]
QCString RTFGenerator::rtf_LCList_DepthStyle () [private]
rtfwriteRuler_doubleline() [1/2]
void RTFGenerator::rtfwriteRuler_doubleline () [private]
Definition at line 2450 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (rtfwriteRuler_doubleline)}\n")
  m_t << "{\\pard\\widctlpar\\brdrb\\brdrdb\\brdrw15\\brsp20 \\adjustright \\par}\n";
}
References DBG_RTF, and OutputGenerator::m_t.
rtfwriteRuler_doubleline() [2/2]
void RTFGenerator::rtfwriteRuler_doubleline () [private]
rtfwriteRuler_emboss() [1/2]
void RTFGenerator::rtfwriteRuler_emboss () [private]
Definition at line 2456 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (rtfwriteRuler_emboss)}\n")
  m_t << "{\\pard\\widctlpar\\brdrb\\brdremboss\\brdrw15\\brsp20 \\adjustright \\par}\n";
}
References DBG_RTF, and OutputGenerator::m_t.
Referenced by beginRTFSection().
rtfwriteRuler_emboss() [2/2]
void RTFGenerator::rtfwriteRuler_emboss () [private]
rtfwriteRuler_thick() [1/2]
void RTFGenerator::rtfwriteRuler_thick () [private]
Definition at line 2462 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (rtfwriteRuler_thick)}\n")
  m_t << "{\\pard\\widctlpar\\brdrb\\brdrs\\brdrw75\\brsp20 \\adjustright \\par}\n";
}
References DBG_RTF, and OutputGenerator::m_t.
Referenced by beginRTFChapter().
rtfwriteRuler_thick() [2/2]
void RTFGenerator::rtfwriteRuler_thick () [private]
rtfwriteRuler_thin() [1/2]
void RTFGenerator::rtfwriteRuler_thin () [private]
Definition at line 2468 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (rtfwriteRuler_thin)}\n")
  m_t << "{\\pard\\widctlpar\\brdrb\\brdrs\\brdrw5\\brsp20 \\adjustright \\par}\n";
}
References DBG_RTF, and OutputGenerator::m_t.
Referenced by writeRuler().
rtfwriteRuler_thin() [2/2]
void RTFGenerator::rtfwriteRuler_thin () [private]
setRelativePath() [1/2]
void RTFGenerator::setRelativePath (const QCString & path)
Definition at line 87 of file rtfgen.cpp.
{
  m_relPath = path;
}
References m_relPath.
Referenced by startFile().
setRelativePath() [2/2]
void RTFGenerator::setRelativePath (const QCString & path)
setSourceFileName() [1/2]
void RTFGenerator::setSourceFileName (const QCString & sourceFileName)
Definition at line 92 of file rtfgen.cpp.
{
  m_sourceFileName = name;
}
References m_sourceFileName, and setup::name.
Referenced by endFile(), and startFile().
setSourceFileName() [2/2]
void RTFGenerator::setSourceFileName (const QCString & sourceFileName)
startAnonTypeScope() [1/2]
void RTFGenerator::startAnonTypeScope (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 114 of file rtfgen.h.
{}
startAnonTypeScope() [2/2]
void RTFGenerator::startAnonTypeScope (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 114 of file rtfgen.h.
{}
startBold() [1/2]
void RTFGenerator::startBold () [inline], [virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 135 of file rtfgen.h.
{ m_t << "{\\b "; }
References OutputGenerator::m_t.
Referenced by startConstraintList(), startDescList(), startExamples(), startInlineHeader(), startMemberDoc(), startParamList(), and writeObjectLink().
startBold() [2/2]
void RTFGenerator::startBold () [inline], [virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 135 of file rtfgen.h.
{ m_t << "{\\b "; }
References OutputGenerator::m_t.
startCallGraph() [1/2]
void RTFGenerator::startCallGraph () [virtual]
Implements OutputGenerator.
Definition at line 2171 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startCallGraph)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startCallGraph() [2/2]
void RTFGenerator::startCallGraph () [virtual]
Implements OutputGenerator.
startCenter() [1/2]
void RTFGenerator::startCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 155 of file rtfgen.h.
{ m_t << "{\\qc\n"; }
References OutputGenerator::m_t.
startCenter() [2/2]
void RTFGenerator::startCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 155 of file rtfgen.h.
{ m_t << "{\\qc\n"; }
References OutputGenerator::m_t.
startClassDiagram() [1/2]
void RTFGenerator::startClassDiagram () [virtual]
Implements OutputGenerator.
Definition at line 1654 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startClassDiagram }\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startClassDiagram() [2/2]
void RTFGenerator::startClassDiagram () [virtual]
Implements OutputGenerator.
startCodeFragment() [1/2]
void RTFGenerator::startCodeFragment (const QCString & style) [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 1717 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startCodeFragment) }\n")
  m_t << "{\n";
  m_t << rtf_Style_Reset << rtf_Code_DepthStyle();
}
References DBG_RTF, OutputGenerator::m_t, rtf_Code_DepthStyle(), and rtf_Style_Reset.
startCodeFragment() [2/2]
void RTFGenerator::startCodeFragment (const QCString & style) [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
startCodeLine() [1/2]
void RTFGenerator::startCodeLine (bool) [virtual]
Implements CodeOutputInterface.
Definition at line 2687 of file rtfgen.cpp.
{
  m_doxyCodeLineOpen = true;
  m_col=0;
}
References m_col, and m_doxyCodeLineOpen.
startCodeLine() [2/2]
void RTFGenerator::startCodeLine (bool) [virtual]
Implements CodeOutputInterface.
startCompoundTemplateParams() [1/2]
void RTFGenerator::startCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 120 of file rtfgen.h.
{ startSubsubsection(); }
References startSubsubsection().
startCompoundTemplateParams() [2/2]
void RTFGenerator::startCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 120 of file rtfgen.h.
{ startSubsubsection(); }
References startSubsubsection().
startConstraintDocs() [1/2]
void RTFGenerator::startConstraintDocs () [virtual]
Implements OutputGenerator.
Definition at line 2515 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startConstraintDocs)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startConstraintDocs() [2/2]
void RTFGenerator::startConstraintDocs () [virtual]
Implements OutputGenerator.
startConstraintList() [1/2]
void RTFGenerator::startConstraintList (const QCString & header) [virtual]
Implements OutputGenerator.
Definition at line 2474 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startConstraintList)}\n")
  m_t << "{"; // ends at endConstraintList
  m_t << "{";
  startBold();
  newParagraph();
  docify(header);
  endBold();
  m_t << "}";
  newParagraph();
  incIndentLevel();
  m_t << rtf_Style_Reset << rtf_DList_DepthStyle();
}
References DBG_RTF, docify(), endBold(), incIndentLevel(), OutputGenerator::m_t, newParagraph(), rtf_DList_DepthStyle(), rtf_Style_Reset, and startBold().
startConstraintList() [2/2]
void RTFGenerator::startConstraintList (const QCString &) [virtual]
Implements OutputGenerator.
startConstraintParam() [1/2]
void RTFGenerator::startConstraintParam () [virtual]
Implements OutputGenerator.
Definition at line 2489 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startConstraintParam)}\n")
  startEmphasis();
}
References DBG_RTF, OutputGenerator::m_t, and startEmphasis().
startConstraintParam() [2/2]
void RTFGenerator::startConstraintParam () [virtual]
Implements OutputGenerator.
startConstraintType() [1/2]
void RTFGenerator::startConstraintType () [virtual]
Implements OutputGenerator.
Definition at line 2502 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startConstraintType)}\n")
  startEmphasis();
}
References DBG_RTF, OutputGenerator::m_t, and startEmphasis().
startConstraintType() [2/2]
void RTFGenerator::startConstraintType () [virtual]
Implements OutputGenerator.
startContents() [1/2]
void RTFGenerator::startContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 190 of file rtfgen.h.
{}
startContents() [2/2]
void RTFGenerator::startContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 190 of file rtfgen.h.
{}
startDescForItem() [1/2]
void RTFGenerator::startDescForItem () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1541 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDescForItem) }\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startDescForItem() [2/2]
void RTFGenerator::startDescForItem () [virtual]
Implements BaseOutputDocInterface.
startDescItem() [1/2]
void RTFGenerator::startDescItem () [virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 1498 of file rtfgen.cpp.
{
  newParagraph();
  DBG_RTF(m_t << "{\\comment (startDescItem)}\n")
  m_t << "{\\b ";
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
startDescItem() [2/2]
void RTFGenerator::startDescItem () [virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
startDescList() [1/2]
void RTFGenerator::startDescList (SectionTypes)
Definition at line 1532 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDescList)}\n")
  m_t << "{"; // ends at endDescList
  m_t << "{"; // ends at endDescTitle
  startBold();
  newParagraph();
}
References DBG_RTF, OutputGenerator::m_t, newParagraph(), and startBold().
startDescList() [2/2]
void RTFGenerator::startDescList (SectionTypes)
startDescription() [1/2]
void RTFGenerator::startDescription () [virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 1484 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDescription)}" << "\n")
  m_t << "{\n";
  m_t << rtf_Style_Reset << rtf_DList_DepthStyle();
}
References DBG_RTF, OutputGenerator::m_t, rtf_DList_DepthStyle(), and rtf_Style_Reset.
startDescription() [2/2]
void RTFGenerator::startDescription () [virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
startDescTable() [1/2]
void RTFGenerator::startDescTable (const QCString & title) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1760 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDescTable) }\n")
  m_t << "{\\par\n";
  m_t << "{" << rtf_Style["Heading5"].reference() << "\n";
  docify(title);
  m_t << ":\\par}\n";
  m_t << rtf_Style_Reset << rtf_DList_DepthStyle();
  m_t << "\\trowd \\trgaph108\\trleft426\\tblind426"
       "\\trbrdrt\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrl\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrb\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrr\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrh\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrv\\brdrs\\brdrw10\\brdrcf15 \n";
  int i,columnPos[2] = { 25, 100 };
  for (i=0;i<2;i++)
  {
    m_t << "\\clvertalt\\clbrdrt\\brdrs\\brdrw10\\brdrcf15 "
         "\\clbrdrl\\brdrs\\brdrw10\\brdrcf15 "
         "\\clbrdrb\\brdrs\\brdrw10\\brdrcf15 "
         "\\clbrdrr \\brdrs\\brdrw10\\brdrcf15 "
         "\\cltxlrtb "
         "\\cellx" << (rtf_pageWidth*columnPos[i]/100) << "\n";
  }
  m_t << "\\pard \\widctlpar\\intbl\\adjustright\n";
}
References DBG_RTF, docify(), OutputGenerator::m_t, rtf_DList_DepthStyle(), rtf_pageWidth, rtf_Style, and rtf_Style_Reset.
startDescTable() [2/2]
void RTFGenerator::startDescTable (const QCString & title) [virtual]
Implements BaseOutputDocInterface.
startDescTableData() [1/2]
void RTFGenerator::startDescTableData () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1814 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDescTableData) }\n")
  m_t << "{";
}
References DBG_RTF, and OutputGenerator::m_t.
startDescTableData() [2/2]
void RTFGenerator::startDescTableData () [virtual]
Implements BaseOutputDocInterface.
startDescTableRow() [1/2]
void RTFGenerator::startDescTableRow () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1794 of file rtfgen.cpp.
{
}
startDescTableRow() [2/2]
void RTFGenerator::startDescTableRow () [virtual]
Implements BaseOutputDocInterface.
startDescTableTitle() [1/2]
void RTFGenerator::startDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1802 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDescTableTitle) }\n")
  m_t << "{\\qr ";
}
References DBG_RTF, and OutputGenerator::m_t.
startDescTableTitle() [2/2]
void RTFGenerator::startDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
startDirDepGraph() [1/2]
void RTFGenerator::startDirDepGraph () [virtual]
Implements OutputGenerator.
Definition at line 2193 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDirDepGraph)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startDirDepGraph() [2/2]
void RTFGenerator::startDirDepGraph () [virtual]
Implements OutputGenerator.
startDotGraph() [1/2]
void RTFGenerator::startDotGraph () [virtual]
Implements OutputGenerator.
Definition at line 2117 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDotGraph)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startDotGraph() [2/2]
void RTFGenerator::startDotGraph () [virtual]
Implements OutputGenerator.
startDoxyAnchor() [1/2]
void RTFGenerator::startDoxyAnchor (const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 1424 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startDoxyAnchor}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startDoxyAnchor() [2/2]
void RTFGenerator::startDoxyAnchor (const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
startEmphasis() [1/2]
void RTFGenerator::startEmphasis () [inline], [virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 133 of file rtfgen.h.
{ m_t << "{\\i "; }
References OutputGenerator::m_t.
Referenced by startConstraintParam(), startConstraintType(), startMemberDescription(), startMemberGroupDocs(), and startPageRef().
startEmphasis() [2/2]
void RTFGenerator::startEmphasis () [inline], [virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 133 of file rtfgen.h.
{ m_t << "{\\i "; }
References OutputGenerator::m_t.
startExamples() [1/2]
void RTFGenerator::startExamples () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2361 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startExamples)}\n")
  m_t << "{"; // ends at endDescList
  m_t << "{"; // ends at endDescTitle
  startBold();
  newParagraph();
  docify(theTranslator->trExamples());
  endBold();
  m_t << "}";
  newParagraph();
  incIndentLevel();
  m_t << rtf_Style_Reset << rtf_DList_DepthStyle();
}
References DBG_RTF, docify(), endBold(), incIndentLevel(), OutputGenerator::m_t, newParagraph(), rtf_DList_DepthStyle(), rtf_Style_Reset, startBold(), theTranslator, and Translator::trExamples().
startExamples() [2/2]
void RTFGenerator::startExamples () [virtual]
Implements BaseOutputDocInterface.
startFile() [1/2]
void RTFGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id) [virtual]
Implements OutputGenerator.
Definition at line 366 of file rtfgen.cpp.
{
  //setEncoding(QCString().sprintf("CP%s",theTranslator->trRTFansicp()));
  QCString fileName=name;
  m_relPath = relativePathToRoot(fileName);
  if (!fileName.endsWith(".rtf")) fileName+=".rtf";
  startPlainFile(fileName);
  setRelativePath(m_relPath);
  setSourceFileName(stripPath(fileName));
  beginRTFDocument();
}
References beginRTFDocument(), QCString::endsWith(), OutputGenerator::fileName(), m_relPath, setup::name, relativePathToRoot(), setRelativePath(), setSourceFileName(), OutputGenerator::startPlainFile(), and stripPath().
startFile() [2/2]
void RTFGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id) [virtual]
Implements OutputGenerator.
startFontClass() [1/2]
void RTFGenerator::startFontClass (const QCString & clsName) [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 2712 of file rtfgen.cpp.
{
  int cod = 2;
  QCString qname(name);
  if (qname == "keyword") cod = 17;
  else if (qname == "keywordtype") cod = 18;
  else if (qname == "keywordflow") cod = 19;
  else if (qname == "comment") cod = 20;
  else if (qname == "preprocessor") cod = 21;
  else if (qname == "stringliteral") cod = 22;
  else if (qname == "charliteral") cod = 23;
  else if (qname == "vhdldigit") cod = 24;
  else if (qname == "vhdlchar") cod = 25;
  else if (qname == "vhdlkeyword") cod = 26;
  else if (qname == "vhdllogic") cod = 27;
  m_t << "{\\cf" << cod << " ";
}
References OutputGenerator::m_t, and setup::name.
startFontClass() [2/2]
void RTFGenerator::startFontClass (const QCString & clsName) [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
startGroupCollaboration() [1/2]
void RTFGenerator::startGroupCollaboration () [virtual]
Implements OutputGenerator.
Definition at line 2163 of file rtfgen.cpp.
{
}
startGroupCollaboration() [2/2]
void RTFGenerator::startGroupCollaboration () [virtual]
Implements OutputGenerator.
startGroupHeader() [1/2]
void RTFGenerator::startGroupHeader (int extraIndent) [virtual]
Implements OutputGenerator.
Definition at line 1364 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startGroupHeader}\n")
  //newParagraph();
  m_t << rtf_Style_Reset;
  if (extraIndent==2)
  {
    m_t << rtf_Style["Heading5"].reference();
  }
  else if (extraIndent==1)
  {
    m_t << rtf_Style["Heading4"].reference();
  }
  else // extraIndent==0
  {
    m_t << rtf_Style["Heading3"].reference();
  }
  m_t << "\n";
}
References DBG_RTF, OutputGenerator::m_t, rtf_Style, and rtf_Style_Reset.
Referenced by startMemberHeader().
startGroupHeader() [2/2]
void RTFGenerator::startGroupHeader (int) [virtual]
Implements OutputGenerator.
startHeaderSection() [1/2]
void RTFGenerator::startHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 102 of file rtfgen.h.
{}
startHeaderSection() [2/2]
void RTFGenerator::startHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 102 of file rtfgen.h.
{}
startHtmlLink() [1/2]
void RTFGenerator::startHtmlLink (const QCString & url) [virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
Definition at line 1073 of file rtfgen.cpp.
{
  if (Config_getBool(RTF_HYPERLINKS))
  {
    m_t << "{\\field {\\*\\fldinst { HYPERLINK \"";
    m_t << url;
    m_t << "\" }{}";
    m_t << "}{\\fldrslt {\\cs37\\ul\\cf2 ";
  }
  else
  {
    startTypewriter();
  }
}
References Config_getBool, OutputGenerator::m_t, startTypewriter(), and setup::url.
startHtmlLink() [2/2]
void RTFGenerator::startHtmlLink (const QCString & url) [virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
startInclDepGraph() [1/2]
void RTFGenerator::startInclDepGraph () [virtual]
Implements OutputGenerator.
Definition at line 2141 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startInclDepGraph)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startInclDepGraph() [2/2]
void RTFGenerator::startInclDepGraph () [virtual]
Implements OutputGenerator.
startIndent() [1/2]
void RTFGenerator::startIndent () [virtual]
Implements OutputGenerator.
Definition at line 1469 of file rtfgen.cpp.
{
  incIndentLevel();
  DBG_RTF(m_t << "{\\comment (startIndent) }\n")
  m_t << "{\n";
  m_t << rtf_Style_Reset << rtf_CList_DepthStyle() << "\n";
}
References DBG_RTF, incIndentLevel(), OutputGenerator::m_t, rtf_CList_DepthStyle(), and rtf_Style_Reset.
startIndent() [2/2]
void RTFGenerator::startIndent () [virtual]
Implements OutputGenerator.
startIndexItem() [1/2]
void RTFGenerator::startIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
Definition at line 1046 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startIndexItem)}\n")
  if (!m_omitParagraph)
  {
    m_t << "\\par\n";
    m_omitParagraph = TRUE;
  }
}
References DBG_RTF, m_omitParagraph, OutputGenerator::m_t, and TRUE.
startIndexItem() [2/2]
void RTFGenerator::startIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
startIndexKey() [1/2]
void RTFGenerator::startIndexKey () [virtual]
Implements OutputGenerator.
Definition at line 1141 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startIndexKey)}\n")
  m_t << "{\\b ";
}
References DBG_RTF, and OutputGenerator::m_t.
startIndexKey() [2/2]
void RTFGenerator::startIndexKey () [virtual]
Implements OutputGenerator.
startIndexList() [1/2]
void RTFGenerator::startIndexList () [virtual]
Implements OutputGenerator.
Definition at line 976 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startIndexList)}\n")
  m_t << "{\n";
  m_t << "\\par\n";
  incIndentLevel();
  m_t << rtf_Style_Reset << rtf_LCList_DepthStyle() << "\n";
  m_omitParagraph = TRUE;
}
References DBG_RTF, incIndentLevel(), m_omitParagraph, OutputGenerator::m_t, rtf_LCList_DepthStyle(), rtf_Style_Reset, and TRUE.
startIndexList() [2/2]
void RTFGenerator::startIndexList () [virtual]
Implements OutputGenerator.
startIndexListItem() [1/2]
void RTFGenerator::startIndexListItem () [virtual]
Implements OutputGenerator.
Definition at line 2535 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startIndexListItem)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startIndexListItem() [2/2]
void RTFGenerator::startIndexListItem () [virtual]
Implements OutputGenerator.
startIndexSection() [1/2]
void RTFGenerator::startIndexSection (IndexSections is) [virtual]
Implements OutputGenerator.
Definition at line 399 of file rtfgen.cpp.
{
  //QCString paperName;
  //m_indentLevel = 0;
  switch (is)
  {
    case isTitlePageStart:
      // basic RTFstart
      // get readyfor author etc
      m_t << "{\\info \n";
      m_t << "{\\title {\\comment ";
      break;
    case isTitlePageAuthor:
      m_t << "}\n";
      if (!rtf_subject.isEmpty()) m_t << "{\\subject " << rtf_subject << "}\n";
      if (!rtf_comments.isEmpty()) m_t << "{\\comment " << rtf_comments << "}\n";
      if (!rtf_company.isEmpty()) m_t << "{\\company " << rtf_company << "}\n";
      if (!rtf_author.isEmpty()) m_t << "{\\author " << rtf_author << "}\n";
      if (!rtf_manager.isEmpty()) m_t << "{\\manager " << rtf_manager << "}\n";
      if (!rtf_documentType.isEmpty()) m_t << "{\\category " << rtf_documentType << "}\n";
      if (!rtf_keywords.isEmpty()) m_t << "{\\keywords " << rtf_keywords << "}\n";
      m_t << "{\\comment ";
      break;
    case isMainPage:
      //Introduction
      beginRTFChapter();
      break;
    case isModuleIndex:
      //Module Index
      beginRTFChapter();
      break;
    case isDirIndex:
      //Directory Index
      beginRTFChapter();
      break;
    case isNamespaceIndex:
      //Namespace Index
      beginRTFChapter();
      break;
    case isConceptIndex:
      //Concept Index
      beginRTFChapter();
      break;
    case isClassHierarchyIndex:
      //Hierarchical Index
      DBG_RTF(m_t << "{\\comment start classhierarchy}\n")
      beginRTFChapter();
      break;
    case isCompoundIndex:
      //Annotated Compound Index
      beginRTFChapter();
      break;
    case isFileIndex:
      //Annotated File Index
      beginRTFChapter();
      break;
    case isPageIndex:
      //Related Page Index
      beginRTFChapter();
      break;
    case isModuleDocumentation:
      {
        //Module Documentation
        for (const auto &gd : *Doxygen::groupLinkedMap)
        {
          if (!gd->isReference())
          {
            beginRTFChapter();
            break;
          }
        }
      }
      break;
    case isDirDocumentation:
      {
        //Directory Documentation
        for (const auto &dd : *Doxygen::dirLinkedMap)
        {
          if (dd->isLinkableInProject())
          {
            beginRTFChapter();
            break;
          }
        }
      }
      break;
    case isNamespaceDocumentation:
      {
        // Namespace Documentation
        for (const auto &nd : *Doxygen::namespaceLinkedMap)
        {
          if (nd->isLinkableInProject())
          {
            beginRTFChapter();
            break;
          }
        }
      }
      break;
    case isConceptDocumentation:
      {
        // Concept Documentation
        for (const auto &cd : *Doxygen::conceptLinkedMap)
        {
          if (cd->isLinkableInProject())
          {
            beginRTFChapter();
            break;
          }
        }
      }
      break;
    case isClassDocumentation:
      {
        //Compound Documentation
        for (const auto &cd : *Doxygen::classLinkedMap)
        {
          if (cd->isLinkableInProject() &&
              cd->templateMaster()==0 &&
             !cd->isEmbeddedInOuterScope() &&
             !cd->isAlias()
             )
          {
            beginRTFChapter();
            break;
          }
        }
      }
      break;
    case isFileDocumentation:
      {
        //File Documentation
        bool isFirst=TRUE;
        for (const auto &fn : *Doxygen::inputNameLinkedMap)
        {
          for (const auto &fd : *fn)
          {
            if (fd->isLinkableInProject() || fd->generateSourceFile())
            {
              if (isFirst)
              {
                beginRTFChapter();
                isFirst=FALSE;
                break;
              }
            }
          }
          if (!isFirst)
          {
            break;
          }
        }
      }
      break;
    case isExampleDocumentation:
      {
        //Example Documentation
        beginRTFChapter();
      }
      break;
    case isPageDocumentation:
      {
        //Page Documentation
        beginRTFChapter();
      }
      break;
    case isPageDocumentation2:
      {
        m_t << "{\\tc \\v ";
      }
      break;
    case isEndIndex:
      break;
  }
}
References beginRTFChapter(), Doxygen::classLinkedMap, Doxygen::conceptLinkedMap, DBG_RTF, Doxygen::dirLinkedMap, FALSE, Doxygen::groupLinkedMap, Doxygen::inputNameLinkedMap, isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isConceptDocumentation, isConceptIndex, isDirDocumentation, isDirIndex, QCString::isEmpty(), isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, isTitlePageAuthor, isTitlePageStart, OutputGenerator::m_t, Doxygen::namespaceLinkedMap, rtf_author, rtf_comments, rtf_company, rtf_documentType, rtf_keywords, rtf_manager, rtf_subject, and TRUE.
startIndexSection() [2/2]
void RTFGenerator::startIndexSection (IndexSections) [virtual]
Implements OutputGenerator.
startIndexValue() [1/2]
void RTFGenerator::startIndexValue (bool hasBrief) [virtual]
Implements OutputGenerator.
Definition at line 1152 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startIndexValue)}\n")
  m_t << " ";
  if (hasBrief) m_t << "(";
}
References DBG_RTF, and OutputGenerator::m_t.
startIndexValue() [2/2]
void RTFGenerator::startIndexValue (bool) [virtual]
Implements OutputGenerator.
startInlineHeader() [1/2]
void RTFGenerator::startInlineHeader () [virtual]
Implements OutputGenerator.
Definition at line 2546 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startInlineHeader)}\n")
  m_t << "{\n";
  m_t << rtf_Style_Reset << rtf_Style["Heading5"].reference();
  startBold();
}
References DBG_RTF, OutputGenerator::m_t, rtf_Style, rtf_Style_Reset, and startBold().
startInlineHeader() [2/2]
void RTFGenerator::startInlineHeader () [virtual]
Implements OutputGenerator.
startInlineMemberDoc() [1/2]
void RTFGenerator::startInlineMemberDoc () [virtual]
Implements OutputGenerator.
Definition at line 2633 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startInlineMemberDoc)}\n")
  m_t << "{";
}
References DBG_RTF, and OutputGenerator::m_t.
startInlineMemberDoc() [2/2]
void RTFGenerator::startInlineMemberDoc () [virtual]
Implements OutputGenerator.
startInlineMemberName() [1/2]
void RTFGenerator::startInlineMemberName () [virtual]
Implements OutputGenerator.
Definition at line 2621 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startInlineMemberName)}\n")
  m_t << "{";
}
References DBG_RTF, and OutputGenerator::m_t.
startInlineMemberName() [2/2]
void RTFGenerator::startInlineMemberName () [virtual]
Implements OutputGenerator.
startInlineMemberType() [1/2]
void RTFGenerator::startInlineMemberType () [virtual]
Implements OutputGenerator.
Definition at line 2609 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startInlineMemberType)}\n")
  m_t << "{\\qr ";
}
References DBG_RTF, and OutputGenerator::m_t.
startInlineMemberType() [2/2]
void RTFGenerator::startInlineMemberType () [virtual]
Implements OutputGenerator.
startItemList() [1/2]
void RTFGenerator::startItemList () [virtual]
start bullet list
Implements BaseOutputDocInterface.
Definition at line 999 of file rtfgen.cpp.
{
  newParagraph();
  incIndentLevel();
  int level = indentLevel();
  DBG_RTF(m_t << "{\\comment (startItemList level=" << level << ") }\n")
  m_t << "{";
  m_listItemInfo[level].number = 1;
  m_listItemInfo[level].isEnum = false;
  m_listItemInfo[level].type = '1';
}
References DBG_RTF, incIndentLevel(), indentLevel(), RTFGenerator::RTFListItemInfo::isEnum, level, m_listItemInfo, OutputGenerator::m_t, newParagraph(), RTFGenerator::RTFListItemInfo::number, and RTFGenerator::RTFListItemInfo::type.
startItemList() [2/2]
void RTFGenerator::startItemList () [virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
startItemListItem() [1/2]
void RTFGenerator::startItemListItem () [virtual]
write bullet or enum item
Implements BaseOutputDocInterface.
Definition at line 1022 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startItemListItem)}\n")
  newParagraph();
  m_t << rtf_Style_Reset;
  int level = indentLevel();
  if (m_listItemInfo[level].isEnum)
  {
    m_t << rtf_EList_DepthStyle() << "\n";
    m_t << m_listItemInfo[level].number << ".\\tab ";
    m_listItemInfo[level].number++;
  }
  else
  {
    m_t << rtf_BList_DepthStyle() << "\n";
  }
  m_omitParagraph = TRUE;
}
References DBG_RTF, indentLevel(), level, m_listItemInfo, m_omitParagraph, OutputGenerator::m_t, newParagraph(), RTFGenerator::RTFListItemInfo::number, rtf_BList_DepthStyle(), rtf_EList_DepthStyle(), rtf_Style_Reset, and TRUE.
startItemListItem() [2/2]
void RTFGenerator::startItemListItem () [virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
startLabels() [1/2]
void RTFGenerator::startLabels () [virtual]
Implements OutputGenerator.
Definition at line 2698 of file rtfgen.cpp.
{
}
startLabels() [2/2]
void RTFGenerator::startLabels () [virtual]
Implements OutputGenerator.
startMemberDeclaration() [1/2]
void RTFGenerator::startMemberDeclaration () [inline], [virtual]
Implements OutputGenerator.
Definition at line 162 of file rtfgen.h.
{}
startMemberDeclaration() [2/2]
void RTFGenerator::startMemberDeclaration () [inline], [virtual]
Implements OutputGenerator.
Definition at line 162 of file rtfgen.h.
{}
startMemberDescription() [1/2]
void RTFGenerator::startMemberDescription (const QCString & , const QCString & , bool) [virtual]
Implements OutputGenerator.
Definition at line 1512 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startMemberDescription)}\n")
  m_t << "{\n";
  incIndentLevel();
  m_t << rtf_Style_Reset << rtf_CList_DepthStyle();
  startEmphasis();
}
References DBG_RTF, incIndentLevel(), OutputGenerator::m_t, rtf_CList_DepthStyle(), rtf_Style_Reset, and startEmphasis().
startMemberDescription() [2/2]
void RTFGenerator::startMemberDescription (const QCString & , const QCString & , bool) [virtual]
Implements OutputGenerator.
startMemberDoc() [1/2]
void RTFGenerator::startMemberDoc (const QCString & clname, const QCString & memname, const QCString & , const QCString & , int , int , bool showInline) [virtual]
Implements OutputGenerator.
Definition at line 1391 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startMemberDoc}\n")
  if (!memname.isEmpty() && memname[0]!='@')
  {
    addIndexItem(memname,clname);
    addIndexItem(clname,memname);
  }
  m_t << rtf_Style_Reset << rtf_Style[showInline ? "Heading5" : "Heading4"].reference();
  //styleStack.push(rtf_Style_Heading4);
  m_t << "{\n";
  //printf("RTFGenerator::startMemberDoc() '%s'\n",rtf_Style["Heading4"].reference());
  startBold();
  m_t << "\n";
}
References addIndexItem(), DBG_RTF, QCString::isEmpty(), OutputGenerator::m_t, rtf_Style, rtf_Style_Reset, and startBold().
startMemberDoc() [2/2]
void RTFGenerator::startMemberDoc (const QCString & , const QCString & , const QCString & , const QCString & , int , int , bool) [virtual]
Implements OutputGenerator.
startMemberDocList() [1/2]
void RTFGenerator::startMemberDocList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 108 of file rtfgen.h.
{}
startMemberDocList() [2/2]
void RTFGenerator::startMemberDocList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 108 of file rtfgen.h.
{}
startMemberDocName() [1/2]
void RTFGenerator::startMemberDocName (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 228 of file rtfgen.h.
{}
startMemberDocName() [2/2]
void RTFGenerator::startMemberDocName (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 228 of file rtfgen.h.
{}
startMemberDocPrefixItem() [1/2]
void RTFGenerator::startMemberDocPrefixItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 226 of file rtfgen.h.
{}
startMemberDocPrefixItem() [2/2]
void RTFGenerator::startMemberDocPrefixItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 226 of file rtfgen.h.
{}
startMemberDocSimple() [1/2]
void RTFGenerator::startMemberDocSimple (bool isEnum) [virtual]
Implements OutputGenerator.
Definition at line 2562 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startMemberDocSimple)}\n")
  m_t << "{\\par\n";
  m_t << "{" << rtf_Style["Heading5"].reference() << "\n";
  if (isEnum)
  {
    m_t << theTranslator->trEnumerationValues();
  }
  else
  {
    m_t << theTranslator->trCompoundMembers();
  }
  m_t << ":\\par}\n";
  m_t << rtf_Style_Reset << rtf_DList_DepthStyle();
  m_t << "\\trowd \\trgaph108\\trleft426\\tblind426"
       "\\trbrdrt\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrl\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrb\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrr\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrh\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrv\\brdrs\\brdrw10\\brdrcf15 \n";
  int i,n=3,columnPos[3] = { 25, 50, 100 };
  if (isEnum)
  {
    columnPos[0]=30;
    columnPos[1]=100;
    n=2;
  }
  for (i=0;i<n;i++)
  {
    m_t << "\\clvertalt\\clbrdrt\\brdrs\\brdrw10\\brdrcf15 "
         "\\clbrdrl\\brdrs\\brdrw10\\brdrcf15 "
         "\\clbrdrb\\brdrs\\brdrw10\\brdrcf15 "
         "\\clbrdrr \\brdrs\\brdrw10\\brdrcf15 "
         "\\cltxlrtb "
         "\\cellx" << (rtf_pageWidth*columnPos[i]/100) << "\n";
  }
  m_t << "\\pard \\widctlpar\\intbl\\adjustright\n";
}
References DBG_RTF, OutputGenerator::m_t, n, rtf_DList_DepthStyle(), rtf_pageWidth, rtf_Style, rtf_Style_Reset, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberDocSimple() [2/2]
void RTFGenerator::startMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
startMemberGroup() [1/2]
void RTFGenerator::startMemberGroup () [virtual]
Implements OutputGenerator.
Definition at line 2348 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startMemberGroup}\n")
  m_t << rtf_Style_Reset << rtf_BList_DepthStyle() << "\n";
}
References DBG_RTF, OutputGenerator::m_t, rtf_BList_DepthStyle(), and rtf_Style_Reset.
startMemberGroup() [2/2]
void RTFGenerator::startMemberGroup () [virtual]
Implements OutputGenerator.
startMemberGroupDocs() [1/2]
void RTFGenerator::startMemberGroupDocs () [virtual]
Implements OutputGenerator.
Definition at line 2335 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startMemberGroupDocs}\n")
  startEmphasis();
}
References DBG_RTF, OutputGenerator::m_t, and startEmphasis().
startMemberGroupDocs() [2/2]
void RTFGenerator::startMemberGroupDocs () [virtual]
Implements OutputGenerator.
startMemberGroupHeader() [1/2]
void RTFGenerator::startMemberGroupHeader (bool hasHeader) [virtual]
Implements OutputGenerator.
Definition at line 2320 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startMemberGroupHeader}\n")
  m_t << "{\n";
  if (hasHeader) incIndentLevel();
  m_t << rtf_Style_Reset << rtf_Style["GroupHeader"].reference();
}
References DBG_RTF, incIndentLevel(), OutputGenerator::m_t, rtf_Style, and rtf_Style_Reset.
startMemberGroupHeader() [2/2]
void RTFGenerator::startMemberGroupHeader (bool) [virtual]
Implements OutputGenerator.
startMemberHeader() [1/2]
void RTFGenerator::startMemberHeader (const QCString & , int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 104 of file rtfgen.h.
{ startGroupHeader(FALSE); }
References FALSE, and startGroupHeader().
startMemberHeader() [2/2]
void RTFGenerator::startMemberHeader (const QCString & , int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 104 of file rtfgen.h.
{ startGroupHeader(FALSE); }
References FALSE, and startGroupHeader().
startMemberItem() [1/2]
void RTFGenerator::startMemberItem (const QCString & , int , const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 1676 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startMemberItem }\n")
  m_t << rtf_Style_Reset << rtf_BList_DepthStyle() << "\n"; // set style to appropriate depth
}
References DBG_RTF, OutputGenerator::m_t, rtf_BList_DepthStyle(), and rtf_Style_Reset.
startMemberItem() [2/2]
void RTFGenerator::startMemberItem (const QCString & , int , const QCString &) [virtual]
Implements OutputGenerator.
startMemberList() [1/2]
void RTFGenerator::startMemberList () [virtual]
Implements OutputGenerator.
Definition at line 1739 of file rtfgen.cpp.
{
  m_t << "\n";
  DBG_RTF(m_t << "{\\comment (startMemberList) }\n")
  m_t << "{\n";
#ifdef DELETEDCODE
  if (!insideTabbing)
    m_t << "\\begin{CompactItemize}\n";
#endif
}
References DBG_RTF, and OutputGenerator::m_t.
startMemberList() [2/2]
void RTFGenerator::startMemberList () [virtual]
Implements OutputGenerator.
startMemberSections() [1/2]
void RTFGenerator::startMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 100 of file rtfgen.h.
{}
startMemberSections() [2/2]
void RTFGenerator::startMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 100 of file rtfgen.h.
{}
startMemberSubtitle() [1/2]
void RTFGenerator::startMemberSubtitle () [virtual]
Implements OutputGenerator.
Definition at line 1940 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startMemberSubtitle}\n")
  m_t << "{\n";
  m_t << rtf_Style_Reset << rtf_CList_DepthStyle() << "\n";
}
References DBG_RTF, OutputGenerator::m_t, rtf_CList_DepthStyle(), and rtf_Style_Reset.
startMemberSubtitle() [2/2]
void RTFGenerator::startMemberSubtitle () [virtual]
Implements OutputGenerator.
startMemberTemplateParams() [1/2]
void RTFGenerator::startMemberTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 118 of file rtfgen.h.
{}
startMemberTemplateParams() [2/2]
void RTFGenerator::startMemberTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 118 of file rtfgen.h.
{}
startPageRef() [1/2]
void RTFGenerator::startPageRef () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1271 of file rtfgen.cpp.
{
  m_t << " (";
  startEmphasis();
}
References OutputGenerator::m_t, and startEmphasis().
startPageRef() [2/2]
void RTFGenerator::startPageRef () [virtual]
Implements BaseOutputDocInterface.
startParagraph() [1/2]
void RTFGenerator::startParagraph (const QCString & classDef) [virtual]
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
Definition at line 1925 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startParagraph}\n")
  newParagraph();
  m_t << "{\n";
  if (QCString(txt) == "reference") m_t << "\\ql\n";
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
startParagraph() [2/2]
void RTFGenerator::startParagraph (const QCString & classDef) [virtual]
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
startParameterList() [1/2]
void RTFGenerator::startParameterList (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 234 of file rtfgen.h.
{}
startParameterList() [2/2]
void RTFGenerator::startParameterList (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 234 of file rtfgen.h.
{}
startParameterName() [1/2]
void RTFGenerator::startParameterName (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 232 of file rtfgen.h.
{}
startParameterName() [2/2]
void RTFGenerator::startParameterName (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 232 of file rtfgen.h.
{}
startParameterType() [1/2]
void RTFGenerator::startParameterType (bool first, const QCString & key) [virtual]
Implements OutputGenerator.
Definition at line 2410 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startParameterType)}\n")
  if (!first && !key.isEmpty())
  {
    m_t << " " << key << " ";
  }
}
References DBG_RTF, QCString::isEmpty(), and OutputGenerator::m_t.
startParameterType() [2/2]
void RTFGenerator::startParameterType (bool , const QCString &) [virtual]
Implements OutputGenerator.
startParamList() [1/2]
void RTFGenerator::startParamList (ParamListTypes , const QCString & title) [virtual]
Implements BaseOutputDocInterface.
Definition at line 2386 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startParamList)}\n")
  m_t << "{"; // ends at endParamList
  m_t << "{"; // ends at endDescTitle
  startBold();
  newParagraph();
  docify(title);
  endBold();
  m_t << "}";
  newParagraph();
  incIndentLevel();
  m_t << rtf_Style_Reset << rtf_DList_DepthStyle();
}
References DBG_RTF, docify(), endBold(), incIndentLevel(), OutputGenerator::m_t, newParagraph(), rtf_DList_DepthStyle(), rtf_Style_Reset, and startBold().
startParamList() [2/2]
void RTFGenerator::startParamList (ParamListTypes , const QCString &) [virtual]
Implements BaseOutputDocInterface.
startProjectNumber() [1/2]
void RTFGenerator::startProjectNumber () [virtual]
Implements OutputGenerator.
Definition at line 388 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startProjectNumber }\n")
  m_t << " ";
}
References DBG_RTF, and OutputGenerator::m_t.
startProjectNumber() [2/2]
void RTFGenerator::startProjectNumber () [virtual]
Implements OutputGenerator.
startQuickIndices() [1/2]
void RTFGenerator::startQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 183 of file rtfgen.h.
{}
startQuickIndices() [2/2]
void RTFGenerator::startQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 183 of file rtfgen.h.
{}
startSection() [1/2]
void RTFGenerator::startSection (const QCString & , const QCString & title, SectionType type) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1551 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startSection)}\n")
  m_t << "{";
  m_t << rtf_Style_Reset;
  int num=4;
  switch(type)
  {
    case SectionType::Page: num=2; break;
    case SectionType::Section: num=3; break;
    case SectionType::Subsection: num=4; break;
    case SectionType::Subsubsection: num=4; break;
    case SectionType::Paragraph: num=4; break;
    default: ASSERT(0); break;
  }
  QCString heading;
  heading.sprintf("Heading%d",num);
  // set style
  m_t << rtf_Style[heading.str()].reference();
  // make table of contents entry
  m_t << "{\\tc\\tcl" << num << " \\v ";
  docify(title);
  m_t << "}\n";
}
References ASSERT, DBG_RTF, docify(), OutputGenerator::m_t, Page, Paragraph, rtf_Style, rtf_Style_Reset, Section, QCString::sprintf(), QCString::str(), Subsection, Subsubsection, and type().
startSection() [2/2]
void RTFGenerator::startSection (const QCString & , const QCString & , SectionType) [virtual]
Implements BaseOutputDocInterface.
startSmall() [1/2]
void RTFGenerator::startSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 157 of file rtfgen.h.
{ m_t << "{\\sub "; }
References OutputGenerator::m_t.
startSmall() [2/2]
void RTFGenerator::startSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 157 of file rtfgen.h.
{ m_t << "{\\sub "; }
References OutputGenerator::m_t.
startSubsection() [1/2]
void RTFGenerator::startSubsection () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1178 of file rtfgen.cpp.
{
  //beginRTFSubSection();
  m_t << "\n";
  DBG_RTF(m_t << "{\\comment Begin SubSection}\n")
  m_t << rtf_Style_Reset;
  m_t << rtf_Style["Heading3"].reference() << "\n";
}
References DBG_RTF, OutputGenerator::m_t, rtf_Style, and rtf_Style_Reset.
startSubsection() [2/2]
void RTFGenerator::startSubsection () [virtual]
Implements BaseOutputDocInterface.
startSubsubsection() [1/2]
void RTFGenerator::startSubsubsection () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1193 of file rtfgen.cpp.
{
  //beginRTFSubSubSection();
  m_t << "\n";
  DBG_RTF(m_t << "{\\comment Begin SubSubSection}\n")
  m_t << "{\n";
  m_t << rtf_Style_Reset << rtf_Style["Heading4"].reference() << "\n";
}
References DBG_RTF, OutputGenerator::m_t, rtf_Style, and rtf_Style_Reset.
Referenced by startCompoundTemplateParams().
startSubsubsection() [2/2]
void RTFGenerator::startSubsubsection () [virtual]
Implements BaseOutputDocInterface.
startTextBlock() [1/2]
void RTFGenerator::startTextBlock (bool dense) [virtual]
Implements OutputGenerator.
Definition at line 1892 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startTextBlock}\n")
  m_t << "{\n";
  m_t << rtf_Style_Reset;
  if (dense) // no spacing between "paragraphs"
  {
    m_t << rtf_Style["DenseText"].reference();
  }
  else // some spacing
  {
    m_t << rtf_Style["BodyText"].reference();
  }
}
References DBG_RTF, OutputGenerator::m_t, rtf_Style, and rtf_Style_Reset.
startTextBlock() [2/2]
void RTFGenerator::startTextBlock (bool dense) [virtual]
Implements OutputGenerator.
startTextLink() [1/2]
void RTFGenerator::startTextLink (const QCString & f, const QCString & anchor) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1208 of file rtfgen.cpp.
{
  if (Config_getBool(RTF_HYPERLINKS))
  {
    QCString ref;
    if (!f.isEmpty())
    {
      ref+=stripPath(f);
    }
    if (!anchor.isEmpty())
    {
      ref+='_';
      ref+=anchor;
    }
    m_t << "{\\field {\\*\\fldinst { HYPERLINK \\\\l \"";
    m_t << rtfFormatBmkStr(ref);
    m_t << "\" }{}";
    m_t << "}{\\fldrslt {\\cs37\\ul\\cf2 ";
  }
}
References Config_getBool, f, QCString::isEmpty(), OutputGenerator::m_t, rtfFormatBmkStr(), and stripPath().
startTextLink() [2/2]
void RTFGenerator::startTextLink (const QCString & f, const QCString & anchor) [virtual]
Implements BaseOutputDocInterface.
startTitle() [1/2]
void RTFGenerator::startTitle () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1355 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startTitle}\n")
  if (Config_getBool(COMPACT_RTF))
    beginRTFSection();
  else
    beginRTFChapter();
}
References beginRTFChapter(), beginRTFSection(), Config_getBool, DBG_RTF, and OutputGenerator::m_t.
startTitle() [2/2]
void RTFGenerator::startTitle () [virtual]
Implements BaseOutputDocInterface.
startTitleHead() [1/2]
void RTFGenerator::startTitleHead (const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 1327 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startTitleHead}\n")
  // beginRTFSection();
  m_t << rtf_Style_Reset << rtf_Style["Heading2"].reference() << "\n";
}
References DBG_RTF, OutputGenerator::m_t, rtf_Style, and rtf_Style_Reset.
startTitleHead() [2/2]
void RTFGenerator::startTitleHead (const QCString &) [virtual]
Implements OutputGenerator.
startTypewriter() [1/2]
void RTFGenerator::startTypewriter () [inline], [virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 93 of file rtfgen.h.
{ m_t << "{\\f2 "; }
References OutputGenerator::m_t.
Referenced by startHtmlLink().
startTypewriter() [2/2]
void RTFGenerator::startTypewriter () [inline], [virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 93 of file rtfgen.h.
{ m_t << "{\\f2 "; }
References OutputGenerator::m_t.
type() [1/2]
OutputType RTFGenerator::type () const [inline], [virtual]
Implements OutputGenerator.
Definition at line 38 of file rtfgen.h.
{ return RTF; }
References OutputGenerator::RTF.
Referenced by startSection().
type() [2/2]
OutputType RTFGenerator::type () const [inline], [virtual]
Implements OutputGenerator.
Definition at line 38 of file rtfgen.h.
{ return RTF; }
References OutputGenerator::RTF.
writeAnchor() [1/2]
void RTFGenerator::writeAnchor (const QCString & fileName, const QCString & name) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1688 of file rtfgen.cpp.
{
  QCString anchor;
  if (!fileName.isEmpty())
  {
    anchor+=stripPath(fileName);
  }
  if (!fileName.isEmpty() && !name.isEmpty())
  {
    anchor+='_';
  }
  if (!name.isEmpty())
  {
    anchor+=name;
  }
  //printf("writeAnchor(%s->%s)\n",qPrint(anchor),qPrint(rtfFormatBmkStr(anchor)));
  DBG_RTF(m_t << "{\\comment writeAnchor (" << anchor << ")}\n")
  m_t << "{\\bkmkstart " << rtfFormatBmkStr(anchor) << "}\n";
  m_t << "{\\bkmkend " << rtfFormatBmkStr(anchor) << "}\n";
}
References DBG_RTF, OutputGenerator::fileName(), QCString::isEmpty(), OutputGenerator::m_t, setup::name, rtfFormatBmkStr(), and stripPath().
Referenced by endSection(), and endTitleHead().
writeAnchor() [2/2]
void RTFGenerator::writeAnchor (const QCString & fileName, const QCString & name) [virtual]
Implements BaseOutputDocInterface.
writeChar() [1/2]
void RTFGenerator::writeChar (char c) [virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
Definition at line 1646 of file rtfgen.cpp.
{
  char cs[2];
  cs[0]=c;
  cs[1]=0;
  docify(cs);
}
References c, cs, and docify().
writeChar() [2/2]
void RTFGenerator::writeChar (char c) [virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
writeCodeAnchor() [1/2]
void RTFGenerator::writeCodeAnchor (const QCString & name) [inline], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 263 of file rtfgen.h.
{}
writeCodeAnchor() [2/2]
void RTFGenerator::writeCodeAnchor (const QCString & name) [inline], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 263 of file rtfgen.h.
{}
writeCodeLink() [1/2]
void RTFGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 1294 of file rtfgen.cpp.
{
  if (ref.isEmpty() && Config_getBool(RTF_HYPERLINKS))
  {
    QCString refName;
    if (!f.isEmpty())
    {
      refName+=stripPath(f);
    }
    if (!anchor.isEmpty())
    {
      refName+='_';
      refName+=anchor;
    }
    m_t << "{\\field {\\*\\fldinst { HYPERLINK \\\\l \"";
    m_t << rtfFormatBmkStr(refName);
    m_t << "\" }{}";
    m_t << "}{\\fldrslt {\\cs37\\ul\\cf2 ";
    codify(name);
    m_t << "}}}\n";
  }
  else
  {
    codify(name);
  }
}
References codify(), Config_getBool, f, QCString::isEmpty(), OutputGenerator::m_t, setup::name, rtfFormatBmkStr(), and stripPath().
Referenced by writeLineNumber().
writeCodeLink() [2/2]
void RTFGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
writeDoc() [1/2]
void RTFGenerator::writeDoc (const IDocNodeAST * ast, const Definition * ctx, const MemberDef * , int) [virtual]
Implements OutputGenerator.
Definition at line 2439 of file rtfgen.cpp.
{
  auto astImpl = dynamic_cast<const DocNodeAST*>(ast);
  if (astImpl)
  {
    RTFDocVisitor visitor(m_t,*this,ctx?ctx->getDefFileExtension():QCString(""));
    std::visit(visitor,astImpl->root);
  }
  m_omitParagraph = TRUE;
}
References Definition::getDefFileExtension(), m_omitParagraph, OutputGenerator::m_t, and TRUE.
Referenced by endIndexSection().
writeDoc() [2/2]
void RTFGenerator::writeDoc (const IDocNodeAST * ast, const Definition * , const MemberDef * , int) [virtual]
Implements OutputGenerator.
writeEndAnnoItem() [1/2]
void RTFGenerator::writeEndAnnoItem (const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 1125 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (writeEndAnnoItem)}\n")
  if (!name.isEmpty())
  {
    m_t << "\\tab ";
    writeRTFReference(name);
    m_t << "\n";
  }
  else
  {
    m_t << "\n";
  }
  newParagraph();
}
References DBG_RTF, OutputGenerator::m_t, setup::name, newParagraph(), and writeRTFReference().
writeEndAnnoItem() [2/2]
void RTFGenerator::writeEndAnnoItem (const QCString & name) [virtual]
Implements OutputGenerator.
writeExtensionsFile() [1/2]
void RTFGenerator::writeExtensionsFile (TextStream & t) [static]
Definition at line 113 of file rtfgen.cpp.
{
  t << "# Generated by doxygen " << getDoxygenVersion() << "\n\n";
  t << "# This file describes extensions used for generating RTF output.\n";
  t << "# All text after a hash (#) is considered a comment and will be ignored.\n";
  t << "# Remove a hash to activate a line.\n\n";
  t << "# Overrides the project title.\n";
  t << "#Title = \n\n";
  t << "# Name of the company that produced this document.\n";
  t << "#Company = \n\n";
  t << "# Filename of a company or project logo.\n";
  t << "#LogoFilename = \n\n";
  t << "# Author of the document.\n";
  t << "#Author = \n\n";
  t << "# Type of document (e.g. Design Specification, User Manual, etc.).\n";
  t << "#DocumentType = \n\n";
  t << "# Document tracking number.\n";
  t << "#DocumentId = \n\n";
  t << "# Name of the author's manager.\n";
  t << "# This field is not displayed in the document itself, but it is \n";
  t << "# available in the information block of the rtf file. In Microsoft \n";
  t << "# Word, it is available under File:Properties.\n";
  t << "#Manager = \n\n";
  t << "# Subject of the document.\n";
  t << "# This field is not displayed in the document itself, but it is \n";
  t << "# available in the information block of the rtf file. In Microsoft \n";
  t << "# Word, it is available under File:Properties.\n";
  t << "#Subject = \n\n";
  t << "# Comments regarding the document.\n";
  t << "# This field is not displayed in the document itself, but it is \n";
  t << "# available in the information block of the rtf file. In Microsoft \n";
  t << "# Word, it is available under File:Properties.\n";
  t << "#Comments = \n\n";
  t << "# Keywords associated with the document.\n";
  t << "# This field is not displayed in the document itself, but it is \n";
  t << "# available in the information block of the rtf file. In Microsoft \n";
  t << "# Word, it is available under File:Properties.\n";
  t << "#Keywords = \n\n";
}
References getDoxygenVersion().
Referenced by readConfiguration().
writeExtensionsFile() [2/2]
static void RTFGenerator::writeExtensionsFile (TextStream & t) [static]
writeFooter() [1/2]
void RTFGenerator::writeFooter (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 47 of file rtfgen.h.
{}
writeFooter() [2/2]
void RTFGenerator::writeFooter (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 47 of file rtfgen.h.
{}
writeGraphicalHierarchy() [1/2]
void RTFGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 213 of file rtfgen.h.
{}
writeGraphicalHierarchy() [2/2]
void RTFGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 213 of file rtfgen.h.
{}
writeInheritedSectionTitle() [1/2]
void RTFGenerator::writeInheritedSectionTitle (const QCString & , const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 164 of file rtfgen.h.
                                                                          {}
writeInheritedSectionTitle() [2/2]
void RTFGenerator::writeInheritedSectionTitle (const QCString & , const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 164 of file rtfgen.h.
                                                                          {}
writeLabel() [1/2]
void RTFGenerator::writeLabel (const QCString & l, bool isLast) [virtual]
Implements OutputGenerator.
Definition at line 2702 of file rtfgen.cpp.
{
  m_t << "{\\f2 [" << l << "]}";
  if (!isLast) m_t << ", ";
}
References OutputGenerator::m_t.
writeLabel() [2/2]
void RTFGenerator::writeLabel (const QCString & l, bool isLast) [virtual]
Implements OutputGenerator.
writeLatexSpacing() [1/2]
void RTFGenerator::writeLatexSpacing () [inline], [virtual]
Implements OutputGenerator.
Definition at line 147 of file rtfgen.h.
{};//{ m_t << "\\hspace{0.3cm}"; }
writeLatexSpacing() [2/2]
void RTFGenerator::writeLatexSpacing () [inline], [virtual]
Implements OutputGenerator.
Definition at line 147 of file rtfgen.h.
{};//{ m_t << "\\hspace{0.3cm}"; }
writeLineNumber() [1/2]
void RTFGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 2645 of file rtfgen.cpp.
{
  bool rtfHyperlinks = Config_getBool(RTF_HYPERLINKS);
  m_doxyCodeLineOpen = true;
  if (Config_getBool(SOURCE_BROWSER))
  {
    QCString lineNumber;
    lineNumber.sprintf("%05d",l);
    QCString lineAnchor;
    if (!m_sourceFileName.isEmpty())
    {
      lineAnchor.sprintf("_l%05d",l);
      lineAnchor.prepend(stripExtensionGeneral(stripPath(m_sourceFileName), ".rtf"));
    }
    bool showTarget = rtfHyperlinks && !lineAnchor.isEmpty() && writeLineAnchor;
    if (showTarget)
    {
        m_t << "{\\bkmkstart ";
        m_t << rtfFormatBmkStr(lineAnchor);
        m_t << "}";
        m_t << "{\\bkmkend ";
        m_t << rtfFormatBmkStr(lineAnchor);
        m_t << "}\n";
    }
    if (!fileName.isEmpty())
    {
      writeCodeLink(CodeSymbolType::Default,ref,fileName,anchor,lineNumber,QCString());
    }
    else
    {
      m_t << lineNumber;
    }
    m_t << " ";
  }
  else
  {
    m_t << l << " ";
  }
  m_col=0;
}
References Config_getBool, Default, OutputGenerator::fileName(), QCString::isEmpty(), m_col, m_doxyCodeLineOpen, m_sourceFileName, OutputGenerator::m_t, QCString::prepend(), rtfFormatBmkStr(), QCString::sprintf(), stripExtensionGeneral(), stripPath(), and writeCodeLink().
writeLineNumber() [2/2]
void RTFGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
writeLogo() [1/2]
void RTFGenerator::writeLogo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 187 of file rtfgen.h.
{}
writeLogo() [2/2]
void RTFGenerator::writeLogo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 187 of file rtfgen.h.
{}
writeNavigationPath() [1/2]
void RTFGenerator::writeNavigationPath (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 186 of file rtfgen.h.
{}
writeNavigationPath() [2/2]
void RTFGenerator::writeNavigationPath (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 186 of file rtfgen.h.
{}
writeNonBreakableSpace() [1/2]
void RTFGenerator::writeNonBreakableSpace (int) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1733 of file rtfgen.cpp.
{
  m_t << "\\~ ";
}
References OutputGenerator::m_t.
writeNonBreakableSpace() [2/2]
void RTFGenerator::writeNonBreakableSpace (int) [virtual]
Implements BaseOutputDocInterface.
writeObjectLink() [1/2]
void RTFGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
Definition at line 1238 of file rtfgen.cpp.
{
  if (ref.isEmpty() && Config_getBool(RTF_HYPERLINKS))
  {
    QCString refName;
    if (!f.isEmpty())
    {
      refName+=stripPath(f);
    }
    if (!anchor.isEmpty())
    {
      refName+='_';
      refName+=anchor;
    }
    m_t << "{\\field {\\*\\fldinst { HYPERLINK \\\\l \"";
    m_t << rtfFormatBmkStr(refName);
    m_t << "\" }{}";
    m_t << "}{\\fldrslt {\\cs37\\ul\\cf2 ";
    docify(text);
    m_t << "}}}\n";
  }
  else
  {
    startBold();
    docify(text);
    endBold();
  }
}
References Config_getBool, docify(), endBold(), f, QCString::isEmpty(), OutputGenerator::m_t, rtfFormatBmkStr(), startBold(), and stripPath().
writeObjectLink() [2/2]
void RTFGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
writePageLink() [1/2]
void RTFGenerator::writePageLink (const QCString & name, bool first) [virtual]
Implements OutputGenerator.
Definition at line 940 of file rtfgen.cpp.
{
   if (first) m_t << "\\par " << rtf_Style_Reset << "\n";
   m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
   m_t << name;
   m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
}
References OutputGenerator::m_t, setup::name, and rtf_Style_Reset.
writePageLink() [2/2]
void RTFGenerator::writePageLink (const QCString & , bool) [virtual]
Implements OutputGenerator.
writeQuickLinks() [1/2]
void RTFGenerator::writeQuickLinks (bool , HighlightedItem , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 188 of file rtfgen.h.
{}
writeQuickLinks() [2/2]
void RTFGenerator::writeQuickLinks (bool , HighlightedItem , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 188 of file rtfgen.h.
{}
writeRTFReference() [1/2]
void RTFGenerator::writeRTFReference (const QCString & label) [private]
Definition at line 1710 of file rtfgen.cpp.
{
  m_t << "{\\field\\fldedit {\\*\\fldinst PAGEREF ";
  m_t << rtfFormatBmkStr(stripPath(label));
  m_t << " \\\\*MERGEFORMAT}{\\fldrslt pagenum}}";
}
References OutputGenerator::m_t, rtfFormatBmkStr(), and stripPath().
Referenced by endIndexItem(), endIndexValue(), endPageRef(), and writeEndAnnoItem().
writeRTFReference() [2/2]
void RTFGenerator::writeRTFReference (const QCString & label) [private]
writeRuler() [1/2]
void RTFGenerator::writeRuler () [inline], [virtual]
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 125 of file rtfgen.h.
{ rtfwriteRuler_thin(); }
References rtfwriteRuler_thin().
writeRuler() [2/2]
void RTFGenerator::writeRuler () [inline], [virtual]
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 125 of file rtfgen.h.
{ rtfwriteRuler_thin(); }
References rtfwriteRuler_thin().
writeSearchInfo() [1/2]
void RTFGenerator::writeSearchInfo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 46 of file rtfgen.h.
{}
writeSearchInfo() [2/2]
void RTFGenerator::writeSearchInfo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 46 of file rtfgen.h.
{}
writeSplitBar() [1/2]
void RTFGenerator::writeSplitBar (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 185 of file rtfgen.h.
{}
writeSplitBar() [2/2]
void RTFGenerator::writeSplitBar (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 185 of file rtfgen.h.
{}
writeStartAnnoItem() [1/2]
void RTFGenerator::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 1101 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (writeStartAnnoItem)}\n")
  m_t << "{\\b ";
  if (!path.isEmpty()) docify(path);
  if (!f.isEmpty() && Config_getBool(RTF_HYPERLINKS))
  {
    m_t << "{\\field {\\*\\fldinst { HYPERLINK \\\\l \"";
    m_t << rtfFormatBmkStr(stripPath(f));
    m_t << "\" }{}";
    m_t << "}{\\fldrslt {\\cs37\\ul\\cf2 ";
    docify(name);
    m_t << "}}}\n";
  }
  else
  {
    docify(name);
  }
  m_t << "} ";
}
References Config_getBool, DBG_RTF, docify(), f, QCString::isEmpty(), OutputGenerator::m_t, setup::name, rtfFormatBmkStr(), and stripPath().
writeStartAnnoItem() [2/2]
void RTFGenerator::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) [virtual]
Implements OutputGenerator.
writeString() [1/2]
void RTFGenerator::writeString (const QCString & text) [virtual]
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
Definition at line 971 of file rtfgen.cpp.
{
  m_t << text;
}
References OutputGenerator::m_t.
writeString() [2/2]
void RTFGenerator::writeString (const QCString & text) [virtual]
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
writeStyleInfo() [1/2]
void RTFGenerator::writeStyleInfo (int part) [virtual]
Implements OutputGenerator.
Definition at line 960 of file rtfgen.cpp.
{
}
writeStyleInfo() [2/2]
void RTFGenerator::writeStyleInfo (int part) [virtual]
Implements OutputGenerator.
writeStyleSheetFile() [1/2]
void RTFGenerator::writeStyleSheetFile (TextStream & t) [static]
Definition at line 97 of file rtfgen.cpp.
{
  t << "# Generated by doxygen " << getDoxygenVersion() << "\n\n";
  t << "# This file describes styles used for generating RTF output.\n";
  t << "# All text after a hash (#) is considered a comment and will be ignored.\n";
  t << "# Remove a hash to activate a line.\n\n";
  int i;
  for (i=0 ; rtf_Style_Default[i].reference!=0 ; i++)
  {
    t << "# " << rtf_Style_Default[i].name << " = "
              << rtf_Style_Default[i].reference
              << rtf_Style_Default[i].definition << "\n";
  }
}
References Rtf_Style_Default::definition, getDoxygenVersion(), Rtf_Style_Default::name, Rtf_Style_Default::reference, and rtf_Style_Default.
Referenced by readConfiguration().
writeStyleSheetFile() [2/2]
static void RTFGenerator::writeStyleSheetFile (TextStream & t) [static]
writeSummaryLink() [1/2]
void RTFGenerator::writeSummaryLink (const QCString & , const QCString & , const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 189 of file rtfgen.h.
{}
writeSummaryLink() [2/2]
void RTFGenerator::writeSummaryLink (const QCString & , const QCString & , const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 189 of file rtfgen.h.
{}
writeSynopsis() [1/2]
void RTFGenerator::writeSynopsis () [inline], [virtual]
Implements OutputGenerator.
Definition at line 178 of file rtfgen.h.
{}
writeSynopsis() [2/2]
void RTFGenerator::writeSynopsis () [inline], [virtual]
Implements OutputGenerator.
Definition at line 178 of file rtfgen.h.
{}
writeTooltip() [1/2]
void RTFGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 86 of file rtfgen.h.
                       {}
writeTooltip() [2/2]
void RTFGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 86 of file rtfgen.h.
                       {}
Member Data Documentation
m_bstartedBody
bool RTFGenerator::m_bstartedBody = false [private]
Definition at line 289 of file rtfgen.h.
m_col
int RTFGenerator::m_col = 0 [private]
Definition at line 288 of file rtfgen.h.
Referenced by codify(), startCodeLine(), and writeLineNumber().
m_doxyCodeLineOpen
bool RTFGenerator::m_doxyCodeLineOpen = false [private]
Definition at line 293 of file rtfgen.h.
Referenced by endCodeLine(), startCodeLine(), and writeLineNumber().
m_indentLevel
int RTFGenerator::m_indentLevel = 0 [private]
Definition at line 297 of file rtfgen.h.
Referenced by decIndentLevel(), incIndentLevel(), and indentLevel().
m_listItemInfo
RTFListItemInfo RTFGenerator::m_listItemInfo [private]
Definition at line 304 of file rtfgen.h.
Referenced by startItemList(), and startItemListItem().
m_numCols
int RTFGenerator::m_numCols = 0 [private]
Definition at line 291 of file rtfgen.h.
m_omitParagraph
bool RTFGenerator::m_omitParagraph = false [private]
Definition at line 290 of file rtfgen.h.
Referenced by docify(), endCodeFragment(), endConstraintList(), endExamples(), endIndexItem(), endIndexList(), endIndexValue(), endItemList(), endMemberDescription(), endParagraph(), endParamList(), endSection(), lineBreak(), newParagraph(), startIndexItem(), startIndexList(), startItemListItem(), and writeDoc().
m_relPath
QCString RTFGenerator::m_relPath [private]
Definition at line 292 of file rtfgen.h.
Referenced by endCallGraph(), endClassDiagram(), endDirDepGraph(), endDotGraph(), endInclDepGraph(), setRelativePath(), and startFile().
m_sourceFileName
QCString RTFGenerator::m_sourceFileName [private]
Definition at line 287 of file rtfgen.h.
Referenced by setSourceFileName(), and writeLineNumber().
maxIndentLevels
static const int RTFGenerator::maxIndentLevels = 13 [static], [private]
Definition at line 296 of file rtfgen.h.
Referenced by incIndentLevel(), and indentLevel().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/rtfgen.h
doxygen/src/rtfgen.h
doxygen/build/doxygen/src/rtfgen.cpp
doxygen/src/rtfgen.cpp