HtmlGenerator Class Reference
#include <htmlgen.h>
Public Member Functions
HtmlGenerator ()
HtmlGenerator & operator= (const HtmlGenerator &g)
HtmlGenerator (const HtmlGenerator &g)
virtual ~HtmlGenerator ()
virtual std::unique_ptr< OutputGenerator > clone () const
virtual OutputType type () const
void cleanup ()
void codify (const QCString &text)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void startCodeLine (bool hasLineNumbers)
void endCodeLine ()
void startFontClass (const QCString &s)
void endFontClass ()
void writeCodeAnchor (const QCString &anchor)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
void writeDoc (const IDocNodeAST *node, const Definition *, const MemberDef *, int id)
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id)
void writeFooter (const QCString &navPath)
void endFile ()
void clearBuffer ()
void writeSearchInfo ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const QCString &, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int part)
void startTitleHead (const QCString &)
void endTitleHead (const QCString &, const QCString &)
void startTitle ()
void endTitle ()
void startParagraph (const QCString &classDef)
void endParagraph ()
void writeString (const QCString &text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const QCString &, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const QCString &ref, const QCString &file)
void endIndexItem (const QCString &ref, const QCString &file)
void docify (const QCString &text)
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)
void startTextLink (const QCString &file, const QCString &anchor)
void endTextLink ()
void startHtmlLink (const QCString &url)
void endHtmlLink ()
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int)
void endGroupHeader (int)
void startItemListItem ()
void endItemListItem ()
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const QCString &, int)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const QCString &anchor, int, const QCString &inheritId)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const QCString &anchor, const QCString &inheritId)
void startCompoundTemplateParams ()
void endCompoundTemplateParams ()
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void insertMemberAlign (bool)
void insertMemberAlignLeft (int, bool)
void startMemberDescription (const QCString &anchor, const QCString &inheritId, bool typ)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const QCString &anchor, const QCString &inheritId)
void writeInheritedSectionTitle (const QCString &id, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &title, const QCString &name)
void writeRuler ()
void writeAnchor (const QCString &, const QCString &name)
void startEmphasis ()
void endEmphasis ()
void startBold ()
void endBold ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void startDescForItem ()
void endDescForItem ()
void lineBreak (const QCString &style)
void writeChar (char c)
void startMemberDoc (const QCString &clName, const QCString &memName, const QCString &anchor, const QCString &title, int memCount, int memTotal, bool showInline)
void endMemberDoc (bool)
void startDoxyAnchor (const QCString &fName, const QCString &manName, const QCString &anchor, const QCString &name, const QCString &args)
void endDoxyAnchor (const QCString &fName, const QCString &anchor)
void writeLatexSpacing ()
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name)
void writeEndAnnoItem (const QCString &)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startExamples ()
void endExamples ()
void startParamList (ParamListTypes, const QCString &)
void endParamList ()
void startSection (const QCString &, const QCString &, SectionType)
void endSection (const QCString &, SectionType)
void addIndexItem (const QCString &, const QCString &)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const QCString &, const QCString &)
void startPageRef ()
void endPageRef (const QCString &, const QCString &)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const QCString &name)
void writeNavigationPath (const QCString &s)
void writeLogo ()
void writeQuickLinks (bool compact, HighlightedItem hli, const QCString &file)
void writeSummaryLink (const QCString &file, const QCString &anchor, const QCString &title, bool first)
void startContents ()
void endContents ()
void startPageDoc (const QCString &pageTitle)
void endPageDoc ()
void writeNonBreakableSpace (int)
void startDescTable (const QCString &title)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startDotGraph ()
void endDotGraph (DotClassGraph &g)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &g)
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &g)
void startCallGraph ()
void endCallGraph (DotCallGraph &g)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &g)
void writeGraphicalHierarchy (DotGfxHierarchyTable &g)
void startTextBlock (bool)
void endTextBlock (bool)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool first, const QCString &key)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool last, bool emptyList, bool closeBracket)
void startParameterList (bool)
void endParameterList ()
void exceptionEntry (const QCString &, bool)
void startConstraintList (const QCString &)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const QCString &l, bool isLast)
void endLabels ()
HtmlGenerator ()
HtmlGenerator & operator= (const HtmlGenerator &g)
HtmlGenerator (const HtmlGenerator &g)
virtual ~HtmlGenerator ()
virtual std::unique_ptr< OutputGenerator > clone () const
virtual OutputType type () const
void cleanup ()
void codify (const QCString &text)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void startCodeLine (bool hasLineNumbers)
void endCodeLine ()
void startFontClass (const QCString &s)
void endFontClass ()
void writeCodeAnchor (const QCString &anchor)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
void writeDoc (const IDocNodeAST *node, const Definition *, const MemberDef *, int id)
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id)
void writeFooter (const QCString &navPath)
void endFile ()
void clearBuffer ()
void writeSearchInfo ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const QCString &, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int part)
void startTitleHead (const QCString &)
void endTitleHead (const QCString &, const QCString &)
void startTitle ()
void endTitle ()
void startParagraph (const QCString &classDef)
void endParagraph ()
void writeString (const QCString &text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const QCString &, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const QCString &ref, const QCString &file)
void endIndexItem (const QCString &ref, const QCString &file)
void docify (const QCString &text)
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)
void startTextLink (const QCString &file, const QCString &anchor)
void endTextLink ()
void startHtmlLink (const QCString &url)
void endHtmlLink ()
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int)
void endGroupHeader (int)
void startItemListItem ()
void endItemListItem ()
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const QCString &, int)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const QCString &anchor, int, const QCString &inheritId)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const QCString &anchor, const QCString &inheritId)
void startCompoundTemplateParams ()
void endCompoundTemplateParams ()
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void insertMemberAlign (bool)
void insertMemberAlignLeft (int, bool)
void startMemberDescription (const QCString &anchor, const QCString &inheritId, bool typ)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const QCString &anchor, const QCString &inheritId)
void writeInheritedSectionTitle (const QCString &id, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &title, const QCString &name)
void writeRuler ()
void writeAnchor (const QCString &, const QCString &name)
void startEmphasis ()
void endEmphasis ()
void startBold ()
void endBold ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void startDescForItem ()
void endDescForItem ()
void lineBreak (const QCString &style)
void writeChar (char c)
void startMemberDoc (const QCString &clName, const QCString &memName, const QCString &anchor, const QCString &title, int memCount, int memTotal, bool showInline)
void endMemberDoc (bool)
void startDoxyAnchor (const QCString &fName, const QCString &manName, const QCString &anchor, const QCString &name, const QCString &args)
void endDoxyAnchor (const QCString &fName, const QCString &anchor)
void writeLatexSpacing ()
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name)
void writeEndAnnoItem (const QCString &)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startExamples ()
void endExamples ()
void startParamList (ParamListTypes, const QCString &)
void endParamList ()
void startSection (const QCString &, const QCString &, SectionType)
void endSection (const QCString &, SectionType)
void addIndexItem (const QCString &, const QCString &)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const QCString &, const QCString &)
void startPageRef ()
void endPageRef (const QCString &, const QCString &)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const QCString &name)
void writeNavigationPath (const QCString &s)
void writeLogo ()
void writeQuickLinks (bool compact, HighlightedItem hli, const QCString &file)
void writeSummaryLink (const QCString &file, const QCString &anchor, const QCString &title, bool first)
void startContents ()
void endContents ()
void startPageDoc (const QCString &pageTitle)
void endPageDoc ()
void writeNonBreakableSpace (int)
void startDescTable (const QCString &title)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startDotGraph ()
void endDotGraph (DotClassGraph &g)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &g)
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &g)
void startCallGraph ()
void endCallGraph (DotCallGraph &g)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &g)
void writeGraphicalHierarchy (DotGfxHierarchyTable &g)
void startTextBlock (bool)
void endTextBlock (bool)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool first, const QCString &key)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool last, bool emptyList, bool closeBracket)
void startParameterList (bool)
void endParameterList ()
void exceptionEntry (const QCString &, bool)
void startConstraintList (const QCString &)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const QCString &l, bool isLast)
void endLabels ()
Static Public Member Functions
static void init ()
static void writeStyleSheetFile (TextStream &t)
static void writeHeaderFile (TextStream &t, const QCString &cssname)
static void writeFooterFile (TextStream &t)
static void writeTabData ()
Additional initialization after indices have been created.
static void writeSearchInfo (TextStream &t, const QCString &relPath)
static void writeSearchData (const QCString &dir)
static void writeSearchPage ()
static void writeExternalSearchPage ()
static QCString writeLogoAsString (const QCString &path)
static QCString writeSplitBarAsString (const QCString &name, const QCString &relpath)
static QCString getMathJaxMacros ()
static QCString getNavTreeCss ()
static void init ()
static void writeStyleSheetFile (TextStream &t)
static void writeHeaderFile (TextStream &t, const QCString &cssname)
static void writeFooterFile (TextStream &t)
static void writeTabData ()
static void writeSearchInfo (TextStream &t, const QCString &relPath)
static void writeSearchData (const QCString &dir)
static void writeSearchPage ()
static void writeExternalSearchPage ()
static QCString writeLogoAsString (const QCString &path)
static QCString writeSplitBarAsString (const QCString &name, const QCString &relpath)
static QCString getMathJaxMacros ()
static QCString getNavTreeCss ()
Private Member Functions
void docify (const QCString &text, bool inHtmlComment)
void docify (const QCString &text, bool inHtmlComment)
Static Private Member Functions
static void writePageFooter (TextStream &t, const QCString &, const QCString &, const QCString &)
static void writePageFooter (TextStream &t, const QCString &, const QCString &, const QCString &)
Private Attributes
QCString m_lastTitle
QCString m_lastFile
QCString m_relPath
int m_sectionCount = 0
bool m_emptySection = false
HtmlCodeGenerator m_codeGen
Additional Inherited Members
Detailed Description
Generator for HTML output
Definition at line 64 of file htmlgen.h.
Constructor & Destructor Documentation
HtmlGenerator() [1/4]
HtmlGenerator::HtmlGenerator ()
Definition at line 1018 of file htmlgen.cpp.
                             : OutputGenerator(Config_getString(HTML_OUTPUT)), m_codeGen(m_t)
{
}
HtmlGenerator() [2/4]
HtmlGenerator::HtmlGenerator (const HtmlGenerator & g)
Definition at line 1022 of file htmlgen.cpp.
                                                    : OutputGenerator(og), m_codeGen(m_t)
{
}
 HtmlGenerator() [1/2]
HtmlGenerator::~HtmlGenerator () [virtual]
Definition at line 1037 of file htmlgen.cpp.
{
  //printf("HtmlGenerator::~HtmlGenerator()\n");
}
HtmlGenerator() [3/4]
HtmlGenerator::HtmlGenerator ()
HtmlGenerator() [4/4]
HtmlGenerator::HtmlGenerator (const HtmlGenerator & g)
 HtmlGenerator() [2/2]
virtual HtmlGenerator::~HtmlGenerator () [virtual]
Member Function Documentation
addIndexItem() [1/2]
void HtmlGenerator::addIndexItem (const QCString & , const QCString &) [virtual]
Implements BaseOutputDocInterface.
Definition at line 2372 of file htmlgen.cpp.
{
}
addIndexItem() [2/2]
void HtmlGenerator::addIndexItem (const QCString & , const QCString &) [virtual]
Implements BaseOutputDocInterface.
cleanup() [1/2]
void HtmlGenerator::cleanup () [virtual]
Implements OutputGenerator.
Definition at line 1143 of file htmlgen.cpp.
{
  QCString dname = Config_getString(HTML_OUTPUT);
  Dir d(dname.str());
  clearSubDirs(d);
}
References clearSubDirs(), Config_getString, and QCString::str().
cleanup() [2/2]
void HtmlGenerator::cleanup () [virtual]
Implements OutputGenerator.
clearBuffer() [1/2]
void HtmlGenerator::clearBuffer ()
clearBuffer() [2/2]
void HtmlGenerator::clearBuffer ()
clone() [1/2]
std::unique_ptr< OutputGenerator > HtmlGenerator::clone () const [virtual]
Implements OutputGenerator.
Definition at line 1032 of file htmlgen.cpp.
{
  return std::make_unique<HtmlGenerator>(*this);
}
clone() [2/2]
virtual std::unique_ptr< OutputGenerator > HtmlGenerator::clone () const [virtual]
Implements OutputGenerator.
codify() [1/2]
void HtmlGenerator::codify (const QCString & s) [inline], [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 90 of file htmlgen.h.
    { m_codeGen.codify(text); }
References HtmlCodeGenerator::codify(), and m_codeGen.
codify() [2/2]
void HtmlGenerator::codify (const QCString & s) [inline], [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 90 of file htmlgen.h.
    { m_codeGen.codify(text); }
References HtmlCodeGenerator::codify(), and m_codeGen.
docify() [1/4]
void HtmlGenerator::docify (const QCString & s) [virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
Definition at line 1720 of file htmlgen.cpp.
{
  docify(str,FALSE);
}
References docify(), and FALSE.
Referenced by docify(), startExamples(), startMemberDoc(), startParamList(), writeChar(), writeObjectLink(), and writeStartAnnoItem().
docify() [2/4]
void HtmlGenerator::docify (const QCString & s) [virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
docify() [3/4]
void HtmlGenerator::docify (const QCString & text, bool inHtmlComment) [private]
Definition at line 1725 of file htmlgen.cpp.
{
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    while (*p)
    {
      c=*p++;
      switch(c)
      {
        case '<': m_t << "&lt;"; break;
        case '>': m_t << "&gt;"; break;
        case '&': m_t << "&amp;"; break;
        case '"': m_t << "&quot;"; break;
        case '-': if (inHtmlComment) m_t << "&#45;"; else m_t << "-"; break;
        case '\\':
                   if (*p=='<')
                     { m_t << "&lt;"; p++; }
                   else if (*p=='>')
                     { m_t << "&gt;"; p++; }
           else if (*p=='(')
                     { m_t << "\\&zwj;("; p++; }
                   else if (*p==')')
                     { m_t << "\\&zwj;)"; p++; }
                   else
                     m_t << "\\";
                   break;
        default: m_t << c;
      }
    }
  }
}
References c, QCString::data(), QCString::isEmpty(), OutputGenerator::m_t, and p.
docify() [4/4]
void HtmlGenerator::docify (const QCString & text, bool inHtmlComment) [private]
endAnonTypeScope() [1/2]
void HtmlGenerator::endAnonTypeScope (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 184 of file htmlgen.h.
{}
endAnonTypeScope() [2/2]
void HtmlGenerator::endAnonTypeScope (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 184 of file htmlgen.h.
{}
endBold() [1/2]
void HtmlGenerator::endBold () [inline], [virtual]
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 215 of file htmlgen.h.
{ m_t << "</b>"; }
References OutputGenerator::m_t.
endBold() [2/2]
void HtmlGenerator::endBold () [inline], [virtual]
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 215 of file htmlgen.h.
{ m_t << "</b>"; }
References OutputGenerator::m_t.
endCallGraph() [1/2]
void HtmlGenerator::endCallGraph (DotCallGraph & g) [virtual]
Implements OutputGenerator.
Definition at line 2295 of file htmlgen.cpp.
{
  endSectionHeader(m_t);
  startSectionSummary(m_t,m_sectionCount);
  endSectionSummary(m_t);
  startSectionContent(m_t,m_sectionCount);
  g.writeGraph(m_t,GOF_BITMAP,EOF_Html,dir(),fileName(),m_relPath,TRUE,m_sectionCount);
  endSectionContent(m_t);
  m_sectionCount++;
}
References OutputGenerator::dir(), endSectionContent(), endSectionHeader(), endSectionSummary(), EOF_Html, OutputGenerator::fileName(), g, GOF_BITMAP, m_relPath, m_sectionCount, OutputGenerator::m_t, startSectionContent(), startSectionSummary(), and TRUE.
endCallGraph() [2/2]
void HtmlGenerator::endCallGraph (DotCallGraph & g) [virtual]
Implements OutputGenerator.
endCenter() [1/2]
void HtmlGenerator::endCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 241 of file htmlgen.h.
{ m_t << "</center>\n"; }
References OutputGenerator::m_t.
endCenter() [2/2]
void HtmlGenerator::endCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 241 of file htmlgen.h.
{ m_t << "</center>\n"; }
References OutputGenerator::m_t.
endClassDiagram() [1/2]
void HtmlGenerator::endClassDiagram (const ClassDiagram & d, const QCString & fileName, const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 1846 of file htmlgen.cpp.
{
  endSectionHeader(m_t);
  startSectionSummary(m_t,m_sectionCount);
  endSectionSummary(m_t);
  startSectionContent(m_t,m_sectionCount);
  TextStream tt;
  d.writeImage(tt,dir(),m_relPath,fileName);
  if (!tt.empty())
  {
    m_t << " <div class=\"center\">\n";
    m_t << " <img src=\"";
    m_t << m_relPath << fileName << ".png\" usemap=\"#" << convertToId(name);
    m_t << "_map\" alt=\"\"/>\n";
    m_t << " <map id=\"" << convertToId(name);
    m_t << "_map\" name=\"" << convertToId(name);
    m_t << "_map\">\n";
    m_t << tt.str();
    m_t << " </map>\n";
    m_t << "</div>";
  }
  else
  {
    m_t << " <div class=\"center\">\n";
    m_t << " <img src=\"";
    m_t << m_relPath << fileName << ".png\" alt=\"\"/>\n";
    m_t << " </div>";
  }
  endSectionContent(m_t);
  m_sectionCount++;
}
References convertToId(), OutputGenerator::dir(), TextStream::empty(), endSectionContent(), endSectionHeader(), endSectionSummary(), OutputGenerator::fileName(), m_relPath, m_sectionCount, OutputGenerator::m_t, setup::name, startSectionContent(), startSectionSummary(), TextStream::str(), and ClassDiagram::writeImage().
endClassDiagram() [2/2]
void HtmlGenerator::endClassDiagram (const ClassDiagram & , const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
endCodeFragment() [1/2]
void HtmlGenerator::endCodeFragment (const QCString & style) [inline], [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 115 of file htmlgen.h.
    { m_codeGen.endCodeFragment(style); }
References HtmlCodeGenerator::endCodeFragment(), m_codeGen, and style.
endCodeFragment() [2/2]
void HtmlGenerator::endCodeFragment (const QCString & style) [inline], [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 115 of file htmlgen.h.
    { m_codeGen.endCodeFragment(style); }
References HtmlCodeGenerator::endCodeFragment(), m_codeGen, and style.
endCodeLine() [1/2]
void HtmlGenerator::endCodeLine () [inline], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 105 of file htmlgen.h.
    { m_codeGen.endCodeLine(); }
References HtmlCodeGenerator::endCodeLine(), and m_codeGen.
endCodeLine() [2/2]
void HtmlGenerator::endCodeLine () [inline], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 105 of file htmlgen.h.
    { m_codeGen.endCodeLine(); }
References HtmlCodeGenerator::endCodeLine(), and m_codeGen.
endCompoundTemplateParams() [1/2]
void HtmlGenerator::endCompoundTemplateParams () [virtual]
Implements OutputGenerator.
Definition at line 1936 of file htmlgen.cpp.
{
  m_t << "</div>";
}
References OutputGenerator::m_t.
endCompoundTemplateParams() [2/2]
void HtmlGenerator::endCompoundTemplateParams () [virtual]
Implements OutputGenerator.
endConstraintDocs() [1/2]
void HtmlGenerator::endConstraintDocs () [virtual]
Implements OutputGenerator.
Definition at line 3089 of file htmlgen.cpp.
{
  m_t << "</td></tr>\n";
}
References OutputGenerator::m_t.
endConstraintDocs() [2/2]
void HtmlGenerator::endConstraintDocs () [virtual]
Implements OutputGenerator.
endConstraintList() [1/2]
void HtmlGenerator::endConstraintList () [virtual]
Implements OutputGenerator.
Definition at line 3094 of file htmlgen.cpp.
{
  m_t << "</table>\n";
  m_t << "</dd>\n";
  m_t << "</dl>\n";
  m_t << "</div>\n";
}
References OutputGenerator::m_t.
endConstraintList() [2/2]
void HtmlGenerator::endConstraintList () [virtual]
Implements OutputGenerator.
endConstraintParam() [1/2]
void HtmlGenerator::endConstraintParam () [virtual]
Implements OutputGenerator.
Definition at line 3069 of file htmlgen.cpp.
{
  m_t << "</em></td>";
}
References OutputGenerator::m_t.
endConstraintParam() [2/2]
void HtmlGenerator::endConstraintParam () [virtual]
Implements OutputGenerator.
endConstraintType() [1/2]
void HtmlGenerator::endConstraintType () [virtual]
Implements OutputGenerator.
Definition at line 3079 of file htmlgen.cpp.
{
  m_t << "</em></td>";
}
References OutputGenerator::m_t.
endConstraintType() [2/2]
void HtmlGenerator::endConstraintType () [virtual]
Implements OutputGenerator.
endContents() [1/2]
void HtmlGenerator::endContents () [virtual]
Implements OutputGenerator.
Definition at line 2835 of file htmlgen.cpp.
{
  m_t << "</div><!-- contents -->\n";
}
References OutputGenerator::m_t.
endContents() [2/2]
void HtmlGenerator::endContents () [virtual]
Implements OutputGenerator.
endDescForItem() [1/2]
void HtmlGenerator::endDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 221 of file htmlgen.h.
{ m_t << "</dd>\n"; }
References OutputGenerator::m_t.
endDescForItem() [2/2]
void HtmlGenerator::endDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 221 of file htmlgen.h.
{ m_t << "</dd>\n"; }
References OutputGenerator::m_t.
endDescItem() [1/2]
void HtmlGenerator::endDescItem () [inline], [virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 219 of file htmlgen.h.
{ m_t << "</dt>"; }
References OutputGenerator::m_t.
endDescItem() [2/2]
void HtmlGenerator::endDescItem () [inline], [virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 219 of file htmlgen.h.
{ m_t << "</dt>"; }
References OutputGenerator::m_t.
endDescription() [1/2]
void HtmlGenerator::endDescription () [inline], [virtual]
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 217 of file htmlgen.h.
{ m_t << "\n</dl>\n\n"; }
References OutputGenerator::m_t.
endDescription() [2/2]
void HtmlGenerator::endDescription () [inline], [virtual]
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 217 of file htmlgen.h.
{ m_t << "\n</dl>\n\n"; }
References OutputGenerator::m_t.
endDescTable() [1/2]
void HtmlGenerator::endDescTable () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2390 of file htmlgen.cpp.
{
  m_t << "</table>\n";
}
References OutputGenerator::m_t.
endDescTable() [2/2]
void HtmlGenerator::endDescTable () [virtual]
Implements BaseOutputDocInterface.
endDescTableData() [1/2]
void HtmlGenerator::endDescTableData () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2420 of file htmlgen.cpp.
{
  m_t << "</td>";
}
References OutputGenerator::m_t.
endDescTableData() [2/2]
void HtmlGenerator::endDescTableData () [virtual]
Implements BaseOutputDocInterface.
endDescTableRow() [1/2]
void HtmlGenerator::endDescTableRow () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2400 of file htmlgen.cpp.
{
  m_t << "</tr>\n";
}
References OutputGenerator::m_t.
endDescTableRow() [2/2]
void HtmlGenerator::endDescTableRow () [virtual]
Implements BaseOutputDocInterface.
endDescTableTitle() [1/2]
void HtmlGenerator::endDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2410 of file htmlgen.cpp.
{
  m_t << "&#160;</td>";
}
References OutputGenerator::m_t.
endDescTableTitle() [2/2]
void HtmlGenerator::endDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
endDirDepGraph() [1/2]
void HtmlGenerator::endDirDepGraph (DotDirDeps & g) [virtual]
Implements OutputGenerator.
Definition at line 2313 of file htmlgen.cpp.
{
  endSectionHeader(m_t);
  startSectionSummary(m_t,m_sectionCount);
  endSectionSummary(m_t);
  startSectionContent(m_t,m_sectionCount);
  g.writeGraph(m_t,GOF_BITMAP,EOF_Html,dir(),fileName(),m_relPath,TRUE,m_sectionCount);
  endSectionContent(m_t);
  m_sectionCount++;
}
References OutputGenerator::dir(), endSectionContent(), endSectionHeader(), endSectionSummary(), EOF_Html, OutputGenerator::fileName(), g, GOF_BITMAP, m_relPath, m_sectionCount, OutputGenerator::m_t, startSectionContent(), startSectionSummary(), and TRUE.
endDirDepGraph() [2/2]
void HtmlGenerator::endDirDepGraph (DotDirDeps & g) [virtual]
Implements OutputGenerator.
endDotGraph() [1/2]
void HtmlGenerator::endDotGraph (DotClassGraph & g) [virtual]
Implements OutputGenerator.
Definition at line 2231 of file htmlgen.cpp.
{
  bool generateLegend = Config_getBool(GENERATE_LEGEND);
  bool umlLook = Config_getBool(UML_LOOK);
  endSectionHeader(m_t);
  startSectionSummary(m_t,m_sectionCount);
  endSectionSummary(m_t);
  startSectionContent(m_t,m_sectionCount);
  g.writeGraph(m_t,GOF_BITMAP,EOF_Html,dir(),fileName(),m_relPath,TRUE,TRUE,m_sectionCount);
  if (generateLegend && !umlLook)
  {
    m_t << "<center><span class=\"legend\">[";
    startHtmlLink((m_relPath+"graph_legend"+Doxygen::htmlFileExtension));
    m_t << theTranslator->trLegend();
    endHtmlLink();
    m_t << "]</span></center>";
  }
  endSectionContent(m_t);
  m_sectionCount++;
}
References Config_getBool, OutputGenerator::dir(), endHtmlLink(), endSectionContent(), endSectionHeader(), endSectionSummary(), EOF_Html, OutputGenerator::fileName(), g, GOF_BITMAP, Doxygen::htmlFileExtension, m_relPath, m_sectionCount, OutputGenerator::m_t, startHtmlLink(), startSectionContent(), startSectionSummary(), theTranslator, Translator::trLegend(), and TRUE.
endDotGraph() [2/2]
void HtmlGenerator::endDotGraph (DotClassGraph & g) [virtual]
Implements OutputGenerator.
endDoxyAnchor() [1/2]
void HtmlGenerator::endDoxyAnchor (const QCString & fName, const QCString & anchor) [virtual]
Implements OutputGenerator.
Definition at line 1527 of file htmlgen.cpp.
{
}
endDoxyAnchor() [2/2]
void HtmlGenerator::endDoxyAnchor (const QCString & fName, const QCString & anchor) [virtual]
Implements OutputGenerator.
endEmphasis() [1/2]
void HtmlGenerator::endEmphasis () [inline], [virtual]
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 213 of file htmlgen.h.
{ m_t << "</em>"; }
References OutputGenerator::m_t.
endEmphasis() [2/2]
void HtmlGenerator::endEmphasis () [inline], [virtual]
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 213 of file htmlgen.h.
{ m_t << "</em>"; }
References OutputGenerator::m_t.
endExamples() [1/2]
void HtmlGenerator::endExamples () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2432 of file htmlgen.cpp.
{
  m_t << "</dl>\n";
}
References OutputGenerator::m_t.
endExamples() [2/2]
void HtmlGenerator::endExamples () [virtual]
Implements BaseOutputDocInterface.
endFile() [1/2]
void HtmlGenerator::endFile () [virtual]
Implements OutputGenerator.
Definition at line 1435 of file htmlgen.cpp.
{
  endPlainFile();
}
References OutputGenerator::endPlainFile().
endFile() [2/2]
void HtmlGenerator::endFile () [virtual]
Implements OutputGenerator.
endFontClass() [1/2]
void HtmlGenerator::endFontClass () [inline], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 109 of file htmlgen.h.
    { m_codeGen.endFontClass(); }
References HtmlCodeGenerator::endFontClass(), and m_codeGen.
endFontClass() [2/2]
void HtmlGenerator::endFontClass () [inline], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 109 of file htmlgen.h.
    { m_codeGen.endFontClass(); }
References HtmlCodeGenerator::endFontClass(), and m_codeGen.
endGroupCollaboration() [1/2]
void HtmlGenerator::endGroupCollaboration (DotGroupCollaboration & g) [virtual]
Implements OutputGenerator.
Definition at line 2277 of file htmlgen.cpp.
{
  endSectionHeader(m_t);
  startSectionSummary(m_t,m_sectionCount);
  endSectionSummary(m_t);
  startSectionContent(m_t,m_sectionCount);
  g.writeGraph(m_t,GOF_BITMAP,EOF_Html,dir(),fileName(),m_relPath,TRUE,m_sectionCount);
  endSectionContent(m_t);
  m_sectionCount++;
}
References OutputGenerator::dir(), endSectionContent(), endSectionHeader(), endSectionSummary(), EOF_Html, OutputGenerator::fileName(), g, GOF_BITMAP, m_relPath, m_sectionCount, OutputGenerator::m_t, startSectionContent(), startSectionSummary(), and TRUE.
endGroupCollaboration() [2/2]
void HtmlGenerator::endGroupCollaboration (DotGroupCollaboration & g) [virtual]
Implements OutputGenerator.
endGroupHeader() [1/2]
void HtmlGenerator::endGroupHeader (int extraIndentLevel) [virtual]
Implements OutputGenerator.
Definition at line 1677 of file htmlgen.cpp.
{
  if (extraIndentLevel==2)
  {
    m_t << "</h4>\n";
  }
  else if (extraIndentLevel==1)
  {
    m_t << "</h3>\n";
  }
  else
  {
    m_t << "</h2>\n";
  }
}
References OutputGenerator::m_t.
endGroupHeader() [2/2]
void HtmlGenerator::endGroupHeader (int) [virtual]
Implements OutputGenerator.
endHeaderSection() [1/2]
void HtmlGenerator::endHeaderSection () [virtual]
Implements OutputGenerator.
Definition at line 3131 of file htmlgen.cpp.
{
  m_t << "</div><!--header-->\n";
}
References OutputGenerator::m_t.
endHeaderSection() [2/2]
void HtmlGenerator::endHeaderSection () [virtual]
Implements OutputGenerator.
endHtmlLink() [1/2]
void HtmlGenerator::endHtmlLink () [virtual]
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
Definition at line 1656 of file htmlgen.cpp.
{
  m_t << "</a>";
}
References OutputGenerator::m_t.
Referenced by endDotGraph().
endHtmlLink() [2/2]
void HtmlGenerator::endHtmlLink () [virtual]
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
endInclDepGraph() [1/2]
void HtmlGenerator::endInclDepGraph (DotInclDepGraph & g) [virtual]
Implements OutputGenerator.
Definition at line 2259 of file htmlgen.cpp.
{
  endSectionHeader(m_t);
  startSectionSummary(m_t,m_sectionCount);
  endSectionSummary(m_t);
  startSectionContent(m_t,m_sectionCount);
  g.writeGraph(m_t,GOF_BITMAP,EOF_Html,dir(),fileName(),m_relPath,TRUE,m_sectionCount);
  endSectionContent(m_t);
  m_sectionCount++;
}
References OutputGenerator::dir(), endSectionContent(), endSectionHeader(), endSectionSummary(), EOF_Html, OutputGenerator::fileName(), g, GOF_BITMAP, m_relPath, m_sectionCount, OutputGenerator::m_t, startSectionContent(), startSectionSummary(), and TRUE.
endInclDepGraph() [2/2]
void HtmlGenerator::endInclDepGraph (DotInclDepGraph & g) [virtual]
Implements OutputGenerator.
endIndent() [1/2]
void HtmlGenerator::endIndent () [virtual]
Implements OutputGenerator.
Definition at line 2366 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endIndent -->\n";)
  m_t << "\n</div>\n" << "</div>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endIndent() [2/2]
void HtmlGenerator::endIndent () [virtual]
Implements OutputGenerator.
endIndexItem() [1/2]
void HtmlGenerator::endIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
Definition at line 1589 of file htmlgen.cpp.
{
  //printf("HtmlGenerator::endIndexItem(%s,%s,%s)\n",ref,f,name);
  if (!ref.isEmpty() || !f.isEmpty())
  {
    m_t << "</a>";
  }
  else
  {
    m_t << "</b>";
  }
}
References f, QCString::isEmpty(), and OutputGenerator::m_t.
endIndexItem() [2/2]
void HtmlGenerator::endIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
endIndexKey() [1/2]
void HtmlGenerator::endIndexKey () [virtual]
Implements OutputGenerator.
Definition at line 2055 of file htmlgen.cpp.
{
  //m_t << "</td>";
}
endIndexKey() [2/2]
void HtmlGenerator::endIndexKey () [virtual]
Implements OutputGenerator.
endIndexList() [1/2]
void HtmlGenerator::endIndexList () [virtual]
Implements OutputGenerator.
Definition at line 2045 of file htmlgen.cpp.
{
  m_t << "</table>\n";
}
References OutputGenerator::m_t.
endIndexList() [2/2]
void HtmlGenerator::endIndexList () [virtual]
Implements OutputGenerator.
endIndexListItem() [1/2]
void HtmlGenerator::endIndexListItem () [virtual]
Implements OutputGenerator.
Definition at line 1559 of file htmlgen.cpp.
{
  m_t << "</li>\n";
}
References OutputGenerator::m_t.
endIndexListItem() [2/2]
void HtmlGenerator::endIndexListItem () [virtual]
Implements OutputGenerator.
endIndexSection() [1/2]
void HtmlGenerator::endIndexSection (IndexSections) [inline], [virtual]
Implements OutputGenerator.
Definition at line 128 of file htmlgen.h.
{}
endIndexSection() [2/2]
void HtmlGenerator::endIndexSection (IndexSections) [inline], [virtual]
Implements OutputGenerator.
Definition at line 128 of file htmlgen.h.
{}
endIndexValue() [1/2]
void HtmlGenerator::endIndexValue (const QCString & , bool) [virtual]
Implements OutputGenerator.
Definition at line 2065 of file htmlgen.cpp.
{
  //m_t << "</td></tr>\n";
}
endIndexValue() [2/2]
void HtmlGenerator::endIndexValue (const QCString & , bool) [virtual]
Implements OutputGenerator.
endInlineHeader() [1/2]
void HtmlGenerator::endInlineHeader () [virtual]
Implements OutputGenerator.
Definition at line 3146 of file htmlgen.cpp.
{
  m_t << "</h3></td></tr>\n";
}
References OutputGenerator::m_t.
endInlineHeader() [2/2]
void HtmlGenerator::endInlineHeader () [virtual]
Implements OutputGenerator.
endInlineMemberDoc() [1/2]
void HtmlGenerator::endInlineMemberDoc () [virtual]
Implements OutputGenerator.
Definition at line 3196 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endInlineMemberDoc -->\n";)
  m_t << "</td></tr>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endInlineMemberDoc() [2/2]
void HtmlGenerator::endInlineMemberDoc () [virtual]
Implements OutputGenerator.
endInlineMemberName() [1/2]
void HtmlGenerator::endInlineMemberName () [virtual]
Implements OutputGenerator.
Definition at line 3184 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endInlineMemberName -->\n";)
  m_t << "</td>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endInlineMemberName() [2/2]
void HtmlGenerator::endInlineMemberName () [virtual]
Implements OutputGenerator.
endInlineMemberType() [1/2]
void HtmlGenerator::endInlineMemberType () [virtual]
Implements OutputGenerator.
Definition at line 3172 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endInlineMemberType -->\n";)
  m_t << "</td>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endInlineMemberType() [2/2]
void HtmlGenerator::endInlineMemberType () [virtual]
Implements OutputGenerator.
endItemList() [1/2]
void HtmlGenerator::endItemList () [inline], [virtual]
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 150 of file htmlgen.h.
{ m_t << "</ul>\n"; }
References OutputGenerator::m_t.
endItemList() [2/2]
void HtmlGenerator::endItemList () [inline], [virtual]
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 150 of file htmlgen.h.
{ m_t << "</ul>\n"; }
References OutputGenerator::m_t.
endItemListItem() [1/2]
void HtmlGenerator::endItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 167 of file htmlgen.h.
{ m_t << "</li>\n"; }
References OutputGenerator::m_t.
endItemListItem() [2/2]
void HtmlGenerator::endItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 167 of file htmlgen.h.
{ m_t << "</li>\n"; }
References OutputGenerator::m_t.
endLabels() [1/2]
void HtmlGenerator::endLabels () [virtual]
Implements OutputGenerator.
Definition at line 3216 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endLabels -->\n";)
  m_t << "</span>";
}
References DBG_HTML, and OutputGenerator::m_t.
endLabels() [2/2]
void HtmlGenerator::endLabels () [virtual]
Implements OutputGenerator.
endMemberDeclaration() [1/2]
void HtmlGenerator::endMemberDeclaration (const QCString & anchor, const QCString & inheritId) [virtual]
Implements OutputGenerator.
Definition at line 3276 of file htmlgen.cpp.
{
  m_t << "<tr class=\"separator:" << anchor;
  if (!inheritId.isEmpty())
  {
    m_t << " inherit " << inheritId;
  }
  m_t << "\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n";
}
References QCString::isEmpty(), and OutputGenerator::m_t.
endMemberDeclaration() [2/2]
void HtmlGenerator::endMemberDeclaration (const QCString & anchor, const QCString & inheritId) [virtual]
Implements OutputGenerator.
endMemberDescription() [1/2]
void HtmlGenerator::endMemberDescription () [virtual]
Implements OutputGenerator.
Definition at line 1979 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberDescription -->\n")
  m_t << "<br /></td></tr>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberDescription() [2/2]
void HtmlGenerator::endMemberDescription () [virtual]
Implements OutputGenerator.
endMemberDoc() [1/2]
void HtmlGenerator::endMemberDoc (bool hasArgs) [virtual]
Implements OutputGenerator.
Definition at line 2215 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberDoc -->\n";)
  if (!hasArgs)
  {
    m_t << " </tr>\n";
  }
  m_t << " </table>\n";
 // m_t << "</div>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberDoc() [2/2]
void HtmlGenerator::endMemberDoc (bool) [virtual]
Implements OutputGenerator.
endMemberDocList() [1/2]
void HtmlGenerator::endMemberDocList () [virtual]
Implements OutputGenerator.
Definition at line 2075 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberDocList -->\n";)
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberDocList() [2/2]
void HtmlGenerator::endMemberDocList () [virtual]
Implements OutputGenerator.
endMemberDocName() [1/2]
void HtmlGenerator::endMemberDocName () [virtual]
Implements OutputGenerator.
Definition at line 2119 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberDocName -->\n";)
  m_t << "</td>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberDocName() [2/2]
void HtmlGenerator::endMemberDocName () [virtual]
Implements OutputGenerator.
endMemberDocPrefixItem() [1/2]
void HtmlGenerator::endMemberDocPrefixItem () [virtual]
Implements OutputGenerator.
Definition at line 2103 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberDocPrefixItem -->\n";)
  m_t << "</div>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberDocPrefixItem() [2/2]
void HtmlGenerator::endMemberDocPrefixItem () [virtual]
Implements OutputGenerator.
endMemberDocSimple() [1/2]
void HtmlGenerator::endMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
Definition at line 3160 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberDocSimple -->\n";)
  m_t << "</table>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberDocSimple() [2/2]
void HtmlGenerator::endMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
endMemberGroup() [1/2]
void HtmlGenerator::endMemberGroup (bool) [virtual]
Implements OutputGenerator.
Definition at line 2355 of file htmlgen.cpp.
{
}
endMemberGroup() [2/2]
void HtmlGenerator::endMemberGroup (bool) [virtual]
Implements OutputGenerator.
endMemberGroupDocs() [1/2]
void HtmlGenerator::endMemberGroupDocs () [virtual]
Implements OutputGenerator.
Definition at line 2346 of file htmlgen.cpp.
{
  m_t << "</div></td></tr>\n";
}
References OutputGenerator::m_t.
endMemberGroupDocs() [2/2]
void HtmlGenerator::endMemberGroupDocs () [virtual]
Implements OutputGenerator.
endMemberGroupHeader() [1/2]
void HtmlGenerator::endMemberGroupHeader () [virtual]
Implements OutputGenerator.
Definition at line 2336 of file htmlgen.cpp.
{
  m_t << "</div></td></tr>\n";
}
References OutputGenerator::m_t.
endMemberGroupHeader() [2/2]
void HtmlGenerator::endMemberGroupHeader () [virtual]
Implements OutputGenerator.
endMemberHeader() [1/2]
void HtmlGenerator::endMemberHeader () [virtual]
Implements OutputGenerator.
Definition at line 2022 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberHeader -->\n")
  m_t << "</h2></td></tr>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberHeader() [2/2]
void HtmlGenerator::endMemberHeader () [virtual]
Implements OutputGenerator.
endMemberItem() [1/2]
void HtmlGenerator::endMemberItem () [virtual]
Implements OutputGenerator.
Definition at line 1911 of file htmlgen.cpp.
{
  m_t << "</td></tr>\n";
}
References OutputGenerator::m_t.
endMemberItem() [2/2]
void HtmlGenerator::endMemberItem () [virtual]
Implements OutputGenerator.
endMemberList() [1/2]
void HtmlGenerator::endMemberList () [virtual]
Implements OutputGenerator.
Definition at line 1885 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberList -->\n")
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberList() [2/2]
void HtmlGenerator::endMemberList () [virtual]
Implements OutputGenerator.
endMemberSections() [1/2]
void HtmlGenerator::endMemberSections () [virtual]
Implements OutputGenerator.
Definition at line 1993 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberSections -->\n")
  if (!m_emptySection)
  {
    m_t << "</table>\n";
  }
}
References DBG_HTML, m_emptySection, and OutputGenerator::m_t.
endMemberSections() [2/2]
void HtmlGenerator::endMemberSections () [virtual]
Implements OutputGenerator.
endMemberSubtitle() [1/2]
void HtmlGenerator::endMemberSubtitle () [virtual]
Implements OutputGenerator.
Definition at line 2034 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberSubtitle -->\n")
  m_t << "</td></tr>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberSubtitle() [2/2]
void HtmlGenerator::endMemberSubtitle () [virtual]
Implements OutputGenerator.
endMemberTemplateParams() [1/2]
void HtmlGenerator::endMemberTemplateParams (const QCString & anchor, const QCString & inheritId) [virtual]
Implements OutputGenerator.
Definition at line 1920 of file htmlgen.cpp.
{
  m_t << "</td></tr>\n";
  m_t << "<tr class=\"memitem:" << anchor;
  if (!inheritId.isEmpty())
  {
    m_t << " inherit " << inheritId;
  }
  m_t << "\"><td class=\"memTemplItemLeft\" align=\"right\" valign=\"top\">";
}
References QCString::isEmpty(), and OutputGenerator::m_t.
endMemberTemplateParams() [2/2]
void HtmlGenerator::endMemberTemplateParams (const QCString & anchor, const QCString & inheritId) [virtual]
Implements OutputGenerator.
endPageDoc() [1/2]
void HtmlGenerator::endPageDoc () [virtual]
Reimplemented from OutputGenerator.
Definition at line 2845 of file htmlgen.cpp.
{
  m_t << "</div><!-- PageDoc -->\n";
}
References OutputGenerator::m_t.
endPageDoc() [2/2]
void HtmlGenerator::endPageDoc () [virtual]
Reimplemented from OutputGenerator.
endPageRef() [1/2]
void HtmlGenerator::endPageRef (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 257 of file htmlgen.h.
{}
endPageRef() [2/2]
void HtmlGenerator::endPageRef (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 257 of file htmlgen.h.
{}
endParagraph() [1/2]
void HtmlGenerator::endParagraph () [virtual]
Ends a paragraph
Implements BaseOutputDocInterface.
Definition at line 1544 of file htmlgen.cpp.
{
  m_t << "</p>\n";
}
References OutputGenerator::m_t.
endParagraph() [2/2]
void HtmlGenerator::endParagraph () [virtual]
Ends a paragraph
Implements BaseOutputDocInterface.
endParameterList() [1/2]
void HtmlGenerator::endParameterList () [virtual]
Implements OutputGenerator.
Definition at line 2192 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endParameterList -->\n";)
  m_t << "</td>\n";
  m_t << " </tr>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endParameterList() [2/2]
void HtmlGenerator::endParameterList () [virtual]
Implements OutputGenerator.
endParameterName() [1/2]
void HtmlGenerator::endParameterName (bool last, bool emptyList, bool closeBracket) [virtual]
Implements OutputGenerator.
Definition at line 2162 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endParameterName -->\n";)
  if (last)
  {
    if (emptyList)
    {
      if (closeBracket) m_t << "</td><td>)";
      m_t << "</td>\n";
      m_t << " <td>";
    }
    else
    {
      m_t << "&#160;</td>\n";
      m_t << " </tr>\n";
      m_t << " <tr>\n";
      m_t << " <td></td>\n";
      m_t << " <td>";
      if (closeBracket) m_t << ")";
      m_t << "</td>\n";
      m_t << " <td></td><td>";
    }
  }
  else
  {
    m_t << "</td>\n";
    m_t << " </tr>\n";
  }
}
References DBG_HTML, and OutputGenerator::m_t.
endParameterName() [2/2]
void HtmlGenerator::endParameterName (bool last, bool emptyList, bool closeBracket) [virtual]
Implements OutputGenerator.
endParameterType() [1/2]
void HtmlGenerator::endParameterType () [virtual]
Implements OutputGenerator.
Definition at line 2150 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endParameterType -->\n";)
  m_t << "&#160;</td>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endParameterType() [2/2]
void HtmlGenerator::endParameterType () [virtual]
Implements OutputGenerator.
endParamList() [1/2]
void HtmlGenerator::endParamList () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2445 of file htmlgen.cpp.
{
  m_t << "</dl>";
}
References OutputGenerator::m_t.
endParamList() [2/2]
void HtmlGenerator::endParamList () [virtual]
Implements BaseOutputDocInterface.
endProjectNumber() [1/2]
void HtmlGenerator::endProjectNumber () [virtual]
Implements OutputGenerator.
Definition at line 1445 of file htmlgen.cpp.
{
  m_t << "</h3>";
}
References OutputGenerator::m_t.
endProjectNumber() [2/2]
void HtmlGenerator::endProjectNumber () [virtual]
Implements OutputGenerator.
endQuickIndices() [1/2]
void HtmlGenerator::endQuickIndices () [virtual]
Implements OutputGenerator.
Definition at line 2780 of file htmlgen.cpp.
{
  m_t << "</div><!-- top -->\n";
}
References OutputGenerator::m_t.
endQuickIndices() [2/2]
void HtmlGenerator::endQuickIndices () [virtual]
Implements OutputGenerator.
endSection() [1/2]
void HtmlGenerator::endSection (const QCString & , SectionType type) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1707 of file htmlgen.cpp.
{
  switch(type)
  {
    case SectionType::Page: m_t << "</h1>"; break;
    case SectionType::Section: m_t << "</h2>"; break;
    case SectionType::Subsection: m_t << "</h3>"; break;
    case SectionType::Subsubsection: m_t << "</h4>"; break;
    case SectionType::Paragraph: m_t << "</h5>"; break;
    default: ASSERT(0); break;
  }
}
References ASSERT, OutputGenerator::m_t, Page, Paragraph, Section, Subsection, Subsubsection, and type().
endSection() [2/2]
void HtmlGenerator::endSection (const QCString & , SectionType) [virtual]
Implements BaseOutputDocInterface.
endSmall() [1/2]
void HtmlGenerator::endSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 243 of file htmlgen.h.
{ m_t << "</small>\n"; }
References OutputGenerator::m_t.
endSmall() [2/2]
void HtmlGenerator::endSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 243 of file htmlgen.h.
{ m_t << "</small>\n"; }
References OutputGenerator::m_t.
endSubsection() [1/2]
void HtmlGenerator::endSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 237 of file htmlgen.h.
{ m_t << "</h2>\n"; }
References OutputGenerator::m_t.
endSubsection() [2/2]
void HtmlGenerator::endSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 237 of file htmlgen.h.
{ m_t << "</h2>\n"; }
References OutputGenerator::m_t.
endSubsubsection() [1/2]
void HtmlGenerator::endSubsubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 239 of file htmlgen.h.
{ m_t << "</h3>\n"; }
References OutputGenerator::m_t.
endSubsubsection() [2/2]
void HtmlGenerator::endSubsubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 239 of file htmlgen.h.
{ m_t << "</h3>\n"; }
References OutputGenerator::m_t.
endTextBlock() [1/2]
void HtmlGenerator::endTextBlock (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 294 of file htmlgen.h.
    { m_t << "</div>"; }
References OutputGenerator::m_t.
endTextBlock() [2/2]
void HtmlGenerator::endTextBlock (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 294 of file htmlgen.h.
    { m_t << "</div>"; }
References OutputGenerator::m_t.
endTextLink() [1/2]
void HtmlGenerator::endTextLink () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1641 of file htmlgen.cpp.
{
  m_t << "</a>";
}
References OutputGenerator::m_t.
endTextLink() [2/2]
void HtmlGenerator::endTextLink () [virtual]
Implements BaseOutputDocInterface.
endTitle() [1/2]
void HtmlGenerator::endTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 136 of file htmlgen.h.
{ m_t << "</div>"; }
References OutputGenerator::m_t.
Referenced by endTitleHead().
endTitle() [2/2]
void HtmlGenerator::endTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 136 of file htmlgen.h.
{ m_t << "</div>"; }
References OutputGenerator::m_t.
endTitleHead() [1/2]
void HtmlGenerator::endTitleHead (const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 3125 of file htmlgen.cpp.
{
  endTitle();
  m_t << "</div>\n";
}
References endTitle(), and OutputGenerator::m_t.
endTitleHead() [2/2]
void HtmlGenerator::endTitleHead (const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
endTypewriter() [1/2]
void HtmlGenerator::endTypewriter () [inline], [virtual]
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 163 of file htmlgen.h.
{ m_t << "</code>"; }
References OutputGenerator::m_t.
endTypewriter() [2/2]
void HtmlGenerator::endTypewriter () [inline], [virtual]
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 163 of file htmlgen.h.
{ m_t << "</code>"; }
References OutputGenerator::m_t.
exceptionEntry() [1/2]
void HtmlGenerator::exceptionEntry (const QCString & prefix, bool closeBracket) [virtual]
Implements OutputGenerator.
Definition at line 2199 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- exceptionEntry -->\n";)
  m_t << "</td>\n";
  m_t << " </tr>\n";
  m_t << " <tr>\n";
  m_t << " <td align=\"right\">";
  // colspan 2 so it gets both parameter type and parameter name columns
  if (!prefix.isEmpty())
    m_t << prefix << "</td><td>(</td><td colspan=\"2\">";
  else if (closeBracket)
    m_t << "</td><td>)</td><td></td><td>";
  else
    m_t << "</td><td></td><td colspan=\"2\">";
}
References DBG_HTML, QCString::isEmpty(), and OutputGenerator::m_t.
exceptionEntry() [2/2]
void HtmlGenerator::exceptionEntry (const QCString & , bool) [virtual]
Implements OutputGenerator.
getMathJaxMacros() [1/2]
QCString HtmlGenerator::getMathJaxMacros () [static]
Definition at line 3286 of file htmlgen.cpp.
{
  return getConvertLatexMacro();
}
References getConvertLatexMacro().
Referenced by DoxygenContext::Private::createMathJaxMacros().
getMathJaxMacros() [2/2]
static QCString HtmlGenerator::getMathJaxMacros () [static]
getNavTreeCss() [1/2]
QCString HtmlGenerator::getNavTreeCss () [static]
Definition at line 3291 of file htmlgen.cpp.
{
  ResourceMgr &mgr = ResourceMgr::instance();
  return replaceVariables(mgr.getAsString("navtree.css"));
}
References ResourceMgr::getAsString(), ResourceMgr::instance(), and replaceVariables().
Referenced by FTVHelp::generateTreeViewScripts().
getNavTreeCss() [2/2]
static QCString HtmlGenerator::getNavTreeCss () [static]
init() [1/2]
void HtmlGenerator::init () [static]
Definition at line 1042 of file htmlgen.cpp.
{
  QCString dname = Config_getString(HTML_OUTPUT);
  Dir d(dname.str());
  if (!d.exists() && !d.mkdir(dname.str()))
  {
    term("Could not create output directory %s\n",qPrint(dname));
  }
  //writeLogo(dname);
  if (!Config_getString(HTML_HEADER).isEmpty())
  {
    g_header=fileToString(Config_getString(HTML_HEADER));
    //printf("g_header='%s'\n",qPrint(g_header));
  }
  else
  {
    g_header = ResourceMgr::instance().getAsString("header.html");
  }
  if (!Config_getString(HTML_FOOTER).isEmpty())
  {
    g_footer=fileToString(Config_getString(HTML_FOOTER));
    //printf("g_footer='%s'\n",qPrint(g_footer));
  }
  else
  {
    g_footer = ResourceMgr::instance().getAsString("footer.html");
  }
  if (Config_getBool(USE_MATHJAX))
  {
    if (!Config_getString(MATHJAX_CODEFILE).isEmpty())
    {
      g_mathjax_code=fileToString(Config_getString(MATHJAX_CODEFILE));
      //printf("g_mathjax_code='%s'\n",qPrint(g_mathjax_code));
    }
    g_latex_macro=getConvertLatexMacro();
    //printf("converted g_latex_macro='%s'\n",qPrint(g_latex_macro));
  }
  createSubDirs(d);
  fillColorStyleMaps();
  ResourceMgr &mgr = ResourceMgr::instance();
  {
    QCString tabsCss;
    if (Config_getBool(HTML_DYNAMIC_MENUS))
    {
      tabsCss = mgr.getAsString("tabs.css");
    }
    else // stylesheet for the 'old' static tabs
    {
      tabsCss = mgr.getAsString("fixed_tabs.css");
    }
    std::ofstream f(dname.str()+"/tabs.css",std::ofstream::out | std::ofstream::binary);
    if (f.is_open())
    {
      TextStream t(&f);
      t << replaceVariables(tabsCss);
    }
  }
  mgr.copyResource("jquery.js",dname);
  if (Config_getBool(INTERACTIVE_SVG))
  {
    mgr.copyResource("svgpan.js",dname);
  }
  if (!Config_getBool(DISABLE_INDEX) && Config_getBool(HTML_DYNAMIC_MENUS))
  {
    mgr.copyResource("menu.js",dname);
  }
  if (Config_getBool(HTML_COLORSTYLE)==HTML_COLORSTYLE_t::TOGGLE)
  {
    //mgr.copyResource("darkmode_toggle.js",dname);
    std::ofstream f(dname.str()+"/darkmode_toggle.js",std::ofstream::out | std::ofstream::binary);
    if (f.is_open())
    {
      TextStream t(&f);
      t << replaceColorMarkers(mgr.getAsString("darkmode_toggle.js"));
    }
  }
  {
    std::ofstream f(dname.str()+"/dynsections.js",std::ofstream::out | std::ofstream::binary);
    if (f.is_open())
    {
      TextStream t(&f);
      t << mgr.getAsString("dynsections.js");
      if (Config_getBool(SOURCE_BROWSER) && Config_getBool(SOURCE_TOOLTIPS))
      {
        t << mgr.getAsString("dynsections_tooltips.js");
      }
    }
  }
}
References Config_getBool, Config_getString, ResourceMgr::copyResource(), createSubDirs(), Dir::exists(), f, fileToString(), fillColorStyleMaps(), g_footer, g_header, g_latex_macro, g_mathjax_code, ResourceMgr::getAsString(), getConvertLatexMacro(), ResourceMgr::instance(), Dir::mkdir(), out, qPrint(), replaceColorMarkers(), replaceVariables(), QCString::str(), and term().
Referenced by generateOutput().
init() [2/2]
static void HtmlGenerator::init () [static]
insertMemberAlign() [1/2]
void HtmlGenerator::insertMemberAlign (bool templ) [virtual]
Implements OutputGenerator.
Definition at line 1941 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- insertMemberAlign -->\n")
  QCString className = templ ? "memTemplItemRight" : "memItemRight";
  m_t << "&#160;</td><td class=\"" << className << "\" valign=\"bottom\">";
}
References DBG_HTML, and OutputGenerator::m_t.
insertMemberAlign() [2/2]
void HtmlGenerator::insertMemberAlign (bool) [virtual]
Implements OutputGenerator.
insertMemberAlignLeft() [1/2]
void HtmlGenerator::insertMemberAlignLeft (int annoType, bool initTag) [virtual]
Implements OutputGenerator.
Definition at line 1948 of file htmlgen.cpp.
{
  if (!initTag) m_t << "&#160;</td>";
  switch(annoType)
  {
    case 0: m_t << "<td class=\"memItemLeft\" align=\"right\" valign=\"top\">"; break;
    case 1: m_t << "<td class=\"memItemLeft\" >"; break;
    case 2: m_t << "<td class=\"memItemLeft\" valign=\"top\">"; break;
    default: m_t << "<td class=\"memTemplParams\" colspan=\"2\">"; break;
  }
}
References OutputGenerator::m_t.
Referenced by startMemberItem().
insertMemberAlignLeft() [2/2]
void HtmlGenerator::insertMemberAlignLeft (int , bool) [virtual]
Implements OutputGenerator.
lastIndexPage() [1/2]
void HtmlGenerator::lastIndexPage () [inline], [virtual]
Implements OutputGenerator.
Definition at line 296 of file htmlgen.h.
{}
lastIndexPage() [2/2]
void HtmlGenerator::lastIndexPage () [inline], [virtual]
Implements OutputGenerator.
Definition at line 296 of file htmlgen.h.
{}
lineBreak() [1/2]
void HtmlGenerator::lineBreak (const QCString & style) [virtual]
Implements BaseOutputDocInterface.
Definition at line 3102 of file htmlgen.cpp.
{
  if (!style.isEmpty())
  {
    m_t << "<br class=\"" << style << "\" />\n";
  }
  else
  {
    m_t << "<br />\n";
  }
}
References OutputGenerator::m_t, and style.
lineBreak() [2/2]
void HtmlGenerator::lineBreak (const QCString & style) [virtual]
Implements BaseOutputDocInterface.
operator=() [1/2]
HtmlGenerator & HtmlGenerator::operator= (const HtmlGenerator & g)
Definition at line 1026 of file htmlgen.cpp.
{
  OutputGenerator::operator=(og);
  return *this;
}
References OutputGenerator::operator=().
operator=() [2/2]
HtmlGenerator & HtmlGenerator::operator= (const HtmlGenerator & g)
startAnonTypeScope() [1/2]
void HtmlGenerator::startAnonTypeScope (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 183 of file htmlgen.h.
{}
startAnonTypeScope() [2/2]
void HtmlGenerator::startAnonTypeScope (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 183 of file htmlgen.h.
{}
startBold() [1/2]
void HtmlGenerator::startBold () [inline], [virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 214 of file htmlgen.h.
{ m_t << "<b>"; }
References OutputGenerator::m_t.
startBold() [2/2]
void HtmlGenerator::startBold () [inline], [virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 214 of file htmlgen.h.
{ m_t << "<b>"; }
References OutputGenerator::m_t.
startCallGraph() [1/2]
void HtmlGenerator::startCallGraph () [virtual]
Implements OutputGenerator.
Definition at line 2290 of file htmlgen.cpp.
{
  startSectionHeader(m_t,m_relPath,m_sectionCount);
}
References m_relPath, m_sectionCount, OutputGenerator::m_t, and startSectionHeader().
startCallGraph() [2/2]
void HtmlGenerator::startCallGraph () [virtual]
Implements OutputGenerator.
startCenter() [1/2]
void HtmlGenerator::startCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 240 of file htmlgen.h.
{ m_t << "<center>\n"; }
References OutputGenerator::m_t.
startCenter() [2/2]
void HtmlGenerator::startCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 240 of file htmlgen.h.
{ m_t << "<center>\n"; }
References OutputGenerator::m_t.
startClassDiagram() [1/2]
void HtmlGenerator::startClassDiagram () [virtual]
Implements OutputGenerator.
Definition at line 1841 of file htmlgen.cpp.
{
  startSectionHeader(m_t,m_relPath,m_sectionCount);
}
References m_relPath, m_sectionCount, OutputGenerator::m_t, and startSectionHeader().
startClassDiagram() [2/2]
void HtmlGenerator::startClassDiagram () [virtual]
Implements OutputGenerator.
startCodeFragment() [1/2]
void HtmlGenerator::startCodeFragment (const QCString & style) [inline], [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 113 of file htmlgen.h.
    { m_codeGen.startCodeFragment(style); }
References m_codeGen, HtmlCodeGenerator::startCodeFragment(), and style.
startCodeFragment() [2/2]
void HtmlGenerator::startCodeFragment (const QCString & style) [inline], [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 113 of file htmlgen.h.
    { m_codeGen.startCodeFragment(style); }
References m_codeGen, HtmlCodeGenerator::startCodeFragment(), and style.
startCodeLine() [1/2]
void HtmlGenerator::startCodeLine (bool hasLineNumbers) [inline], [virtual]
Implements CodeOutputInterface.
Definition at line 103 of file htmlgen.h.
    { m_codeGen.startCodeLine(hasLineNumbers); }
References m_codeGen, and HtmlCodeGenerator::startCodeLine().
startCodeLine() [2/2]
void HtmlGenerator::startCodeLine (bool hasLineNumbers) [inline], [virtual]
Implements CodeOutputInterface.
Definition at line 103 of file htmlgen.h.
    { m_codeGen.startCodeLine(hasLineNumbers); }
References m_codeGen, and HtmlCodeGenerator::startCodeLine().
startCompoundTemplateParams() [1/2]
void HtmlGenerator::startCompoundTemplateParams () [virtual]
Implements OutputGenerator.
Definition at line 1931 of file htmlgen.cpp.
{
  m_t << "<div class=\"compoundTemplParams\">";
}
References OutputGenerator::m_t.
startCompoundTemplateParams() [2/2]
void HtmlGenerator::startCompoundTemplateParams () [virtual]
Implements OutputGenerator.
startConstraintDocs() [1/2]
void HtmlGenerator::startConstraintDocs () [virtual]
Implements OutputGenerator.
Definition at line 3084 of file htmlgen.cpp.
{
  m_t << "<td>&#160;";
}
References OutputGenerator::m_t.
startConstraintDocs() [2/2]
void HtmlGenerator::startConstraintDocs () [virtual]
Implements OutputGenerator.
startConstraintList() [1/2]
void HtmlGenerator::startConstraintList (const QCString & header) [virtual]
Implements OutputGenerator.
Definition at line 3057 of file htmlgen.cpp.
{
  m_t << "<div class=\"typeconstraint\">\n";
  m_t << "<dl><dt><b>" << header << "</b></dt><dd>\n";
  m_t << "<table border=\"0\" cellspacing=\"2\" cellpadding=\"0\">\n";
}
References OutputGenerator::m_t.
startConstraintList() [2/2]
void HtmlGenerator::startConstraintList (const QCString &) [virtual]
Implements OutputGenerator.
startConstraintParam() [1/2]
void HtmlGenerator::startConstraintParam () [virtual]
Implements OutputGenerator.
Definition at line 3064 of file htmlgen.cpp.
{
  m_t << "<tr><td valign=\"top\"><em>";
}
References OutputGenerator::m_t.
startConstraintParam() [2/2]
void HtmlGenerator::startConstraintParam () [virtual]
Implements OutputGenerator.
startConstraintType() [1/2]
void HtmlGenerator::startConstraintType () [virtual]
Implements OutputGenerator.
Definition at line 3074 of file htmlgen.cpp.
{
  m_t << "<td>&#160;:</td><td valign=\"top\"><em>";
}
References OutputGenerator::m_t.
startConstraintType() [2/2]
void HtmlGenerator::startConstraintType () [virtual]
Implements OutputGenerator.
startContents() [1/2]
void HtmlGenerator::startContents () [virtual]
Implements OutputGenerator.
Definition at line 2830 of file htmlgen.cpp.
{
  m_t << "<div class=\"contents\">\n";
}
References OutputGenerator::m_t.
startContents() [2/2]
void HtmlGenerator::startContents () [virtual]
Implements OutputGenerator.
startDescForItem() [1/2]
void HtmlGenerator::startDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 220 of file htmlgen.h.
{ m_t << "<dd>"; }
References OutputGenerator::m_t.
startDescForItem() [2/2]
void HtmlGenerator::startDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 220 of file htmlgen.h.
{ m_t << "<dd>"; }
References OutputGenerator::m_t.
startDescItem() [1/2]
void HtmlGenerator::startDescItem () [inline], [virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 218 of file htmlgen.h.
{ m_t << "<dt>"; }
References OutputGenerator::m_t.
startDescItem() [2/2]
void HtmlGenerator::startDescItem () [inline], [virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 218 of file htmlgen.h.
{ m_t << "<dt>"; }
References OutputGenerator::m_t.
startDescription() [1/2]
void HtmlGenerator::startDescription () [inline], [virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 216 of file htmlgen.h.
{ m_t << "\n<dl>\n"; }
References OutputGenerator::m_t.
startDescription() [2/2]
void HtmlGenerator::startDescription () [inline], [virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 216 of file htmlgen.h.
{ m_t << "\n<dl>\n"; }
References OutputGenerator::m_t.
startDescTable() [1/2]
void HtmlGenerator::startDescTable (const QCString & title) [virtual]
Implements BaseOutputDocInterface.
Definition at line 2385 of file htmlgen.cpp.
{
  m_t << "<table class=\"fieldtable\">\n"
      << "<tr><th colspan=\"2\">" << title << "</th></tr>";
}
References OutputGenerator::m_t.
startDescTable() [2/2]
void HtmlGenerator::startDescTable (const QCString & title) [virtual]
Implements BaseOutputDocInterface.
startDescTableData() [1/2]
void HtmlGenerator::startDescTableData () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2415 of file htmlgen.cpp.
{
  m_t << "<td class=\"fielddoc\">";
}
References OutputGenerator::m_t.
startDescTableData() [2/2]
void HtmlGenerator::startDescTableData () [virtual]
Implements BaseOutputDocInterface.
startDescTableRow() [1/2]
void HtmlGenerator::startDescTableRow () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2395 of file htmlgen.cpp.
{
  m_t << "<tr>";
}
References OutputGenerator::m_t.
startDescTableRow() [2/2]
void HtmlGenerator::startDescTableRow () [virtual]
Implements BaseOutputDocInterface.
startDescTableTitle() [1/2]
void HtmlGenerator::startDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2405 of file htmlgen.cpp.
{
  m_t << "<td class=\"fieldname\">";
}
References OutputGenerator::m_t.
startDescTableTitle() [2/2]
void HtmlGenerator::startDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
startDirDepGraph() [1/2]
void HtmlGenerator::startDirDepGraph () [virtual]
Implements OutputGenerator.
Definition at line 2308 of file htmlgen.cpp.
{
  startSectionHeader(m_t,m_relPath,m_sectionCount);
}
References m_relPath, m_sectionCount, OutputGenerator::m_t, and startSectionHeader().
startDirDepGraph() [2/2]
void HtmlGenerator::startDirDepGraph () [virtual]
Implements OutputGenerator.
startDotGraph() [1/2]
void HtmlGenerator::startDotGraph () [virtual]
Implements OutputGenerator.
Definition at line 2226 of file htmlgen.cpp.
{
  startSectionHeader(m_t,m_relPath,m_sectionCount);
}
References m_relPath, m_sectionCount, OutputGenerator::m_t, and startSectionHeader().
startDotGraph() [2/2]
void HtmlGenerator::startDotGraph () [virtual]
Implements OutputGenerator.
startDoxyAnchor() [1/2]
void HtmlGenerator::startDoxyAnchor (const QCString & fName, const QCString & manName, const QCString & anchor, const QCString & name, const QCString & args) [virtual]
Implements OutputGenerator.
Definition at line 1520 of file htmlgen.cpp.
{
  m_t << "<a id=\"" << anchor << "\" name=\"" << anchor << "\"></a>";
}
References OutputGenerator::m_t.
startDoxyAnchor() [2/2]
void HtmlGenerator::startDoxyAnchor (const QCString & fName, const QCString & manName, const QCString & anchor, const QCString & name, const QCString & args) [virtual]
Implements OutputGenerator.
startEmphasis() [1/2]
void HtmlGenerator::startEmphasis () [inline], [virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 212 of file htmlgen.h.
{ m_t << "<em>"; }
References OutputGenerator::m_t.
startEmphasis() [2/2]
void HtmlGenerator::startEmphasis () [inline], [virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 212 of file htmlgen.h.
{ m_t << "<em>"; }
References OutputGenerator::m_t.
startExamples() [1/2]
void HtmlGenerator::startExamples () [virtual]
Implements BaseOutputDocInterface.
Definition at line 2425 of file htmlgen.cpp.
{
  m_t << "<dl class=\"section examples\"><dt>";
  docify(theTranslator->trExamples());
  m_t << "</dt>";
}
References docify(), OutputGenerator::m_t, theTranslator, and Translator::trExamples().
startExamples() [2/2]
void HtmlGenerator::startExamples () [virtual]
Implements BaseOutputDocInterface.
startFile() [1/2]
void HtmlGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id) [virtual]
Implements OutputGenerator.
Definition at line 1325 of file htmlgen.cpp.
{
  //printf("HtmlGenerator::startFile(%s)\n",qPrint(name));
  m_relPath = relativePathToRoot(name);
  QCString fileName = addHtmlExtensionIfMissing(name);
  m_lastTitle=title;
  startPlainFile(fileName);
  m_codeGen.setId(id);
  m_codeGen.setRelativePath(m_relPath);
  {
    std::lock_guard<std::mutex> lock(g_indexLock);
    Doxygen::indexList->addIndexFile(fileName);
  }
  m_lastFile = fileName;
  m_t << substituteHtmlKeywords(g_header,convertToHtml(filterTitle(title)),m_relPath);
  m_t << "<!-- " << theTranslator->trGeneratedBy() << " Doxygen "
      << getDoxygenVersion() << " -->\n";
  bool searchEngine = Config_getBool(SEARCHENGINE);
  if (searchEngine /*&& !generateTreeView*/)
  {
    m_t << "<script type=\"text/javascript\">\n";
    m_t << "/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */\n";
    m_t << "var searchBox = new SearchBox(\"searchBox\", \""
        << m_relPath<< "search/\",'" << Doxygen::htmlFileExtension << "');\n";
    m_t << "/* @license-end */\n";
    m_t << "</script>\n";
  }
  m_sectionCount=0;
}
References addHtmlExtensionIfMissing(), IndexList::addIndexFile(), Config_getBool, convertToHtml(), OutputGenerator::fileName(), filterTitle(), g_header, g_indexLock, getDoxygenVersion(), Doxygen::htmlFileExtension, Doxygen::indexList, m_codeGen, m_lastFile, m_lastTitle, m_relPath, m_sectionCount, OutputGenerator::m_t, setup::name, relativePathToRoot(), HtmlCodeGenerator::setId(), HtmlCodeGenerator::setRelativePath(), OutputGenerator::startPlainFile(), substituteHtmlKeywords(), theTranslator, and Translator::trGeneratedBy().
startFile() [2/2]
void HtmlGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id) [virtual]
Implements OutputGenerator.
startFontClass() [1/2]
void HtmlGenerator::startFontClass (const QCString & clsName) [inline], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 107 of file htmlgen.h.
    { m_codeGen.startFontClass(s); }
References m_codeGen, s, and HtmlCodeGenerator::startFontClass().
startFontClass() [2/2]
void HtmlGenerator::startFontClass (const QCString & clsName) [inline], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 107 of file htmlgen.h.
    { m_codeGen.startFontClass(s); }
References m_codeGen, s, and HtmlCodeGenerator::startFontClass().
startGroupCollaboration() [1/2]
void HtmlGenerator::startGroupCollaboration () [virtual]
Implements OutputGenerator.
Definition at line 2272 of file htmlgen.cpp.
{
  startSectionHeader(m_t,m_relPath,m_sectionCount);
}
References m_relPath, m_sectionCount, OutputGenerator::m_t, and startSectionHeader().
startGroupCollaboration() [2/2]
void HtmlGenerator::startGroupCollaboration () [virtual]
Implements OutputGenerator.
startGroupHeader() [1/2]
void HtmlGenerator::startGroupHeader (int extraIndentLevel) [virtual]
Implements OutputGenerator.
Definition at line 1661 of file htmlgen.cpp.
{
  if (extraIndentLevel==2)
  {
    m_t << "<h4 class=\"groupheader\">";
  }
  else if (extraIndentLevel==1)
  {
    m_t << "<h3 class=\"groupheader\">";
  }
  else // extraIndentLevel==0
  {
    m_t << "<h2 class=\"groupheader\">";
  }
}
References OutputGenerator::m_t.
startGroupHeader() [2/2]
void HtmlGenerator::startGroupHeader (int) [virtual]
Implements OutputGenerator.
startHeaderSection() [1/2]
void HtmlGenerator::startHeaderSection () [virtual]
Implements OutputGenerator.
Definition at line 3114 of file htmlgen.cpp.
{
  m_t << "<div class=\"header\">\n";
}
References OutputGenerator::m_t.
startHeaderSection() [2/2]
void HtmlGenerator::startHeaderSection () [virtual]
Implements OutputGenerator.
startHtmlLink() [1/2]
void HtmlGenerator::startHtmlLink (const QCString & url) [virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
Definition at line 1646 of file htmlgen.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  m_t << "<a ";
  if (generateTreeView) m_t << "target=\"top\" ";
  m_t << "href=\"";
  if (!url.isEmpty()) m_t << url;
  m_t << "\">";
}
References Config_getBool, OutputGenerator::m_t, and setup::url.
Referenced by endDotGraph().
startHtmlLink() [2/2]
void HtmlGenerator::startHtmlLink (const QCString & url) [virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
startInclDepGraph() [1/2]
void HtmlGenerator::startInclDepGraph () [virtual]
Implements OutputGenerator.
Definition at line 2254 of file htmlgen.cpp.
{
  startSectionHeader(m_t,m_relPath,m_sectionCount);
}
References m_relPath, m_sectionCount, OutputGenerator::m_t, and startSectionHeader().
startInclDepGraph() [2/2]
void HtmlGenerator::startInclDepGraph () [virtual]
Implements OutputGenerator.
startIndent() [1/2]
void HtmlGenerator::startIndent () [virtual]
Implements OutputGenerator.
Definition at line 2359 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startIndent -->\n";)
  m_t << "<div class=\"memdoc\">\n";
}
References DBG_HTML, and OutputGenerator::m_t.
startIndent() [2/2]
void HtmlGenerator::startIndent () [virtual]
Implements OutputGenerator.
startIndexItem() [1/2]
void HtmlGenerator::startIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
Definition at line 1564 of file htmlgen.cpp.
{
  //printf("HtmlGenerator::startIndexItem(%s,%s)\n",ref,f);
  if (!ref.isEmpty() || !f.isEmpty())
  {
    if (!ref.isEmpty())
    {
      m_t << "<a class=\"elRef\" ";
      m_t << externalLinkTarget();
    }
    else
    {
      m_t << "<a class=\"el\" ";
    }
    m_t << "href=\"";
    m_t << externalRef(m_relPath,ref,TRUE);
    if (!f.isEmpty()) m_t << addHtmlExtensionIfMissing(f);
    m_t << "\">";
  }
  else
  {
    m_t << "<b>";
  }
}
References addHtmlExtensionIfMissing(), externalLinkTarget(), externalRef(), f, QCString::isEmpty(), m_relPath, OutputGenerator::m_t, and TRUE.
startIndexItem() [2/2]
void HtmlGenerator::startIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
startIndexKey() [1/2]
void HtmlGenerator::startIndexKey () [virtual]
Implements OutputGenerator.
Definition at line 2050 of file htmlgen.cpp.
{
  //m_t << " <tr><td class=\"indexkey\">";
}
startIndexKey() [2/2]
void HtmlGenerator::startIndexKey () [virtual]
Implements OutputGenerator.
startIndexList() [1/2]
void HtmlGenerator::startIndexList () [virtual]
Implements OutputGenerator.
Definition at line 2040 of file htmlgen.cpp.
{
  m_t << "<table>\n";
}
References OutputGenerator::m_t.
startIndexList() [2/2]
void HtmlGenerator::startIndexList () [virtual]
Implements OutputGenerator.
startIndexListItem() [1/2]
void HtmlGenerator::startIndexListItem () [virtual]
Implements OutputGenerator.
Definition at line 1554 of file htmlgen.cpp.
{
  m_t << "<li>";
}
References OutputGenerator::m_t.
startIndexListItem() [2/2]
void HtmlGenerator::startIndexListItem () [virtual]
Implements OutputGenerator.
startIndexSection() [1/2]
void HtmlGenerator::startIndexSection (IndexSections) [inline], [virtual]
Implements OutputGenerator.
Definition at line 127 of file htmlgen.h.
{}
startIndexSection() [2/2]
void HtmlGenerator::startIndexSection (IndexSections) [inline], [virtual]
Implements OutputGenerator.
Definition at line 127 of file htmlgen.h.
{}
startIndexValue() [1/2]
void HtmlGenerator::startIndexValue (bool) [virtual]
Implements OutputGenerator.
Definition at line 2060 of file htmlgen.cpp.
{
  //m_t << "<td class=\"indexvalue\">";
}
startIndexValue() [2/2]
void HtmlGenerator::startIndexValue (bool) [virtual]
Implements OutputGenerator.
startInlineHeader() [1/2]
void HtmlGenerator::startInlineHeader () [virtual]
Implements OutputGenerator.
Definition at line 3136 of file htmlgen.cpp.
{
  if (m_emptySection)
  {
    m_t << "<table class=\"memberdecls\">\n";
    m_emptySection=FALSE;
  }
  m_t << "<tr><td colspan=\"2\"><h3>";
}
References FALSE, m_emptySection, and OutputGenerator::m_t.
startInlineHeader() [2/2]
void HtmlGenerator::startInlineHeader () [virtual]
Implements OutputGenerator.
startInlineMemberDoc() [1/2]
void HtmlGenerator::startInlineMemberDoc () [virtual]
Implements OutputGenerator.
Definition at line 3190 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startInlineMemberDoc -->\n";)
  m_t << "<td class=\"fielddoc\">\n";
}
References DBG_HTML, and OutputGenerator::m_t.
startInlineMemberDoc() [2/2]
void HtmlGenerator::startInlineMemberDoc () [virtual]
Implements OutputGenerator.
startInlineMemberName() [1/2]
void HtmlGenerator::startInlineMemberName () [virtual]
Implements OutputGenerator.
Definition at line 3178 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startInlineMemberName -->\n";)
  m_t << "<td class=\"fieldname\">\n";
}
References DBG_HTML, and OutputGenerator::m_t.
startInlineMemberName() [2/2]
void HtmlGenerator::startInlineMemberName () [virtual]
Implements OutputGenerator.
startInlineMemberType() [1/2]
void HtmlGenerator::startInlineMemberType () [virtual]
Implements OutputGenerator.
Definition at line 3166 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startInlineMemberType -->\n";)
  m_t << "<tr><td class=\"fieldtype\">\n";
}
References DBG_HTML, and OutputGenerator::m_t.
startInlineMemberType() [2/2]
void HtmlGenerator::startInlineMemberType () [virtual]
Implements OutputGenerator.
startItemList() [1/2]
void HtmlGenerator::startItemList () [inline], [virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 149 of file htmlgen.h.
{ m_t << "<ul>\n"; }
References OutputGenerator::m_t.
startItemList() [2/2]
void HtmlGenerator::startItemList () [inline], [virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 149 of file htmlgen.h.
{ m_t << "<ul>\n"; }
References OutputGenerator::m_t.
startItemListItem() [1/2]
void HtmlGenerator::startItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
Definition at line 166 of file htmlgen.h.
{ m_t << "<li>"; }
References OutputGenerator::m_t.
startItemListItem() [2/2]
void HtmlGenerator::startItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
Definition at line 166 of file htmlgen.h.
{ m_t << "<li>"; }
References OutputGenerator::m_t.
startLabels() [1/2]
void HtmlGenerator::startLabels () [virtual]
Implements OutputGenerator.
Definition at line 3202 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startLabels -->\n";)
  m_t << "<span class=\"mlabels\">";
}
References DBG_HTML, and OutputGenerator::m_t.
startLabels() [2/2]
void HtmlGenerator::startLabels () [virtual]
Implements OutputGenerator.
startMemberDeclaration() [1/2]
void HtmlGenerator::startMemberDeclaration () [inline], [virtual]
Implements OutputGenerator.
Definition at line 203 of file htmlgen.h.
{}
startMemberDeclaration() [2/2]
void HtmlGenerator::startMemberDeclaration () [inline], [virtual]
Implements OutputGenerator.
Definition at line 203 of file htmlgen.h.
{}
startMemberDescription() [1/2]
void HtmlGenerator::startMemberDescription (const QCString & anchor, const QCString & inheritId, bool typ) [virtual]
Implements OutputGenerator.
Definition at line 1960 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberDescription -->\n")
  if (m_emptySection)
  {
    m_t << "<table class=\"memberdecls\">\n";
    m_emptySection=FALSE;
  }
  m_t << "<tr class=\"memdesc:" << anchor;
  if (!inheritId.isEmpty())
  {
    m_t << " inherit " << inheritId;
  }
  m_t << "\">";
  m_t << "<td class=\"mdescLeft\">&#160;</td>";
  if (typ) m_t << "<td class=\"mdescLeft\">&#160;</td>";
  m_t << "<td class=\"mdescRight\">";;
}
References DBG_HTML, FALSE, QCString::isEmpty(), m_emptySection, and OutputGenerator::m_t.
startMemberDescription() [2/2]
void HtmlGenerator::startMemberDescription (const QCString & anchor, const QCString & inheritId, bool typ) [virtual]
Implements OutputGenerator.
startMemberDoc() [1/2]
void HtmlGenerator::startMemberDoc (const QCString & clName, const QCString & memName, const QCString & anchor, const QCString & title, int memCount, int memTotal, bool showInline) [virtual]
Implements OutputGenerator.
Definition at line 2080 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberDoc -->\n";)
  m_t << "\n<h2 class=\"memtitle\">"
      << "<span class=\"permalink\"><a href=\"#" << anchor << "\">&#9670;&#160;</a></span>";
  docify(title);
  if (memTotal>1)
  {
    m_t << " <span class=\"overload\">[" << memCount << "/" << memTotal <<"]</span>";
  }
  m_t << "</h2>\n";
  m_t << "\n<div class=\"memitem\">\n";
  m_t << "<div class=\"memproto\">\n";
}
References DBG_HTML, docify(), and OutputGenerator::m_t.
startMemberDoc() [2/2]
void HtmlGenerator::startMemberDoc (const QCString & clName, const QCString & memName, const QCString & anchor, const QCString & title, int memCount, int memTotal, bool showInline) [virtual]
Implements OutputGenerator.
startMemberDocList() [1/2]
void HtmlGenerator::startMemberDocList () [virtual]
Implements OutputGenerator.
Definition at line 2070 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberDocList -->\n";)
}
References DBG_HTML, and OutputGenerator::m_t.
startMemberDocList() [2/2]
void HtmlGenerator::startMemberDocList () [virtual]
Implements OutputGenerator.
startMemberDocName() [1/2]
void HtmlGenerator::startMemberDocName (bool) [virtual]
Implements OutputGenerator.
Definition at line 2109 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberDocName -->\n";)
  m_t << " <table class=\"memname\">\n";
  m_t << " <tr>\n";
  m_t << " <td class=\"memname\">";
}
References DBG_HTML, and OutputGenerator::m_t.
startMemberDocName() [2/2]
void HtmlGenerator::startMemberDocName (bool) [virtual]
Implements OutputGenerator.
startMemberDocPrefixItem() [1/2]
void HtmlGenerator::startMemberDocPrefixItem () [virtual]
Implements OutputGenerator.
Definition at line 2097 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberDocPrefixItem -->\n";)
  m_t << "<div class=\"memtemplate\">\n";
}
References DBG_HTML, and OutputGenerator::m_t.
startMemberDocPrefixItem() [2/2]
void HtmlGenerator::startMemberDocPrefixItem () [virtual]
Implements OutputGenerator.
startMemberDocSimple() [1/2]
void HtmlGenerator::startMemberDocSimple (bool isEnum) [virtual]
Implements OutputGenerator.
Definition at line 3151 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberDocSimple -->\n";)
  m_t << "<table class=\"fieldtable\">\n";
  m_t << "<tr><th colspan=\"" << (isEnum?"2":"3") << "\">";
  m_t << (isEnum? theTranslator->trEnumerationValues() :
       theTranslator->trCompoundMembers()) << "</th></tr>\n";
}
References DBG_HTML, OutputGenerator::m_t, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberDocSimple() [2/2]
void HtmlGenerator::startMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
startMemberGroup() [1/2]
void HtmlGenerator::startMemberGroup () [virtual]
Implements OutputGenerator.
Definition at line 2351 of file htmlgen.cpp.
{
}
startMemberGroup() [2/2]
void HtmlGenerator::startMemberGroup () [virtual]
Implements OutputGenerator.
startMemberGroupDocs() [1/2]
void HtmlGenerator::startMemberGroupDocs () [virtual]
Implements OutputGenerator.
Definition at line 2341 of file htmlgen.cpp.
{
  m_t << "<tr><td colspan=\"2\"><div class=\"groupText\">";
}
References OutputGenerator::m_t.
startMemberGroupDocs() [2/2]
void HtmlGenerator::startMemberGroupDocs () [virtual]
Implements OutputGenerator.
startMemberGroupHeader() [1/2]
void HtmlGenerator::startMemberGroupHeader (bool) [virtual]
Implements OutputGenerator.
Definition at line 2331 of file htmlgen.cpp.
{
  m_t << "<tr><td colspan=\"2\"><div class=\"groupHeader\">";
}
References OutputGenerator::m_t.
startMemberGroupHeader() [2/2]
void HtmlGenerator::startMemberGroupHeader (bool) [virtual]
Implements OutputGenerator.
startMemberHeader() [1/2]
void HtmlGenerator::startMemberHeader (const QCString & anchor, int typ) [virtual]
Implements OutputGenerator.
Definition at line 2002 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberHeader -->\n")
  if (!m_emptySection)
  {
    m_t << "</table>";
    m_emptySection=TRUE;
  }
  if (m_emptySection)
  {
    m_t << "<table class=\"memberdecls\">\n";
    m_emptySection=FALSE;
  }
  m_t << "<tr class=\"heading\"><td colspan=\"" << typ << "\"><h2 class=\"groupheader\">";
  if (!anchor.isEmpty())
  {
    m_t << "<a id=\"" << anchor << "\" name=\"" << anchor << "\"></a>\n";
  }
}
References DBG_HTML, FALSE, QCString::isEmpty(), m_emptySection, OutputGenerator::m_t, and TRUE.
startMemberHeader() [2/2]
void HtmlGenerator::startMemberHeader (const QCString & , int) [virtual]
Implements OutputGenerator.
startMemberItem() [1/2]
void HtmlGenerator::startMemberItem (const QCString & anchor, int annoType, const QCString & inheritId) [virtual]
Implements OutputGenerator.
Definition at line 1894 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberItem() -->\n")
  if (m_emptySection)
  {
    m_t << "<table class=\"memberdecls\">\n";
    m_emptySection=FALSE;
  }
  m_t << "<tr class=\"memitem:" << anchor;
  if (!inheritId.isEmpty())
  {
    m_t << " inherit " << inheritId;
  }
  m_t << "\">";
  insertMemberAlignLeft(annoType, true);
}
References DBG_HTML, FALSE, insertMemberAlignLeft(), QCString::isEmpty(), m_emptySection, and OutputGenerator::m_t.
startMemberItem() [2/2]
void HtmlGenerator::startMemberItem (const QCString & anchor, int , const QCString & inheritId) [virtual]
Implements OutputGenerator.
startMemberList() [1/2]
void HtmlGenerator::startMemberList () [virtual]
Implements OutputGenerator.
Definition at line 1880 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberList -->\n")
}
References DBG_HTML, and OutputGenerator::m_t.
startMemberList() [2/2]
void HtmlGenerator::startMemberList () [virtual]
Implements OutputGenerator.
startMemberSections() [1/2]
void HtmlGenerator::startMemberSections () [virtual]
Implements OutputGenerator.
Definition at line 1985 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberSections -->\n")
  m_emptySection=TRUE; // we postpone writing <table> until we actually
                       // write a row to prevent empty tables, which
                       // are not valid XHTML!
}
References DBG_HTML, m_emptySection, OutputGenerator::m_t, and TRUE.
startMemberSections() [2/2]
void HtmlGenerator::startMemberSections () [virtual]
Implements OutputGenerator.
startMemberSubtitle() [1/2]
void HtmlGenerator::startMemberSubtitle () [virtual]
Implements OutputGenerator.
Definition at line 2028 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberSubtitle -->\n")
  m_t << "<tr><td class=\"ititle\" colspan=\"2\">";
}
References DBG_HTML, and OutputGenerator::m_t.
startMemberSubtitle() [2/2]
void HtmlGenerator::startMemberSubtitle () [virtual]
Implements OutputGenerator.
startMemberTemplateParams() [1/2]
void HtmlGenerator::startMemberTemplateParams () [virtual]
Implements OutputGenerator.
Definition at line 1916 of file htmlgen.cpp.
{
}
startMemberTemplateParams() [2/2]
void HtmlGenerator::startMemberTemplateParams () [virtual]
Implements OutputGenerator.
startPageDoc() [1/2]
void HtmlGenerator::startPageDoc (const QCString & pageTitle) [virtual]
Reimplemented from OutputGenerator.
Definition at line 2840 of file htmlgen.cpp.
{
  m_t << "<div>";
}
References OutputGenerator::m_t.
startPageDoc() [2/2]
void HtmlGenerator::startPageDoc (const QCString & pageTitle) [virtual]
Reimplemented from OutputGenerator.
startPageRef() [1/2]
void HtmlGenerator::startPageRef () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 256 of file htmlgen.h.
{}
startPageRef() [2/2]
void HtmlGenerator::startPageRef () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 256 of file htmlgen.h.
{}
startParagraph() [1/2]
void HtmlGenerator::startParagraph (const QCString & classDef) [virtual]
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
Definition at line 1536 of file htmlgen.cpp.
{
  if (!classDef.isEmpty())
    m_t << "\n<p class=\"" << classDef << "\">";
  else
    m_t << "\n<p>";
}
References QCString::isEmpty(), and OutputGenerator::m_t.
startParagraph() [2/2]
void HtmlGenerator::startParagraph (const QCString & classDef) [virtual]
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
startParameterList() [1/2]
void HtmlGenerator::startParameterList (bool openBracket) [virtual]
Implements OutputGenerator.
Definition at line 2125 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startParameterList -->\n";)
  m_t << " <td>";
  if (openBracket) m_t << "(";
  m_t << "</td>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
startParameterList() [2/2]
void HtmlGenerator::startParameterList (bool) [virtual]
Implements OutputGenerator.
startParameterName() [1/2]
void HtmlGenerator::startParameterName (bool) [virtual]
Implements OutputGenerator.
Definition at line 2156 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startParameterName -->\n";)
  m_t << " <td class=\"paramname\">";
}
References DBG_HTML, and OutputGenerator::m_t.
startParameterName() [2/2]
void HtmlGenerator::startParameterName (bool) [virtual]
Implements OutputGenerator.
startParameterType() [1/2]
void HtmlGenerator::startParameterType (bool first, const QCString & key) [virtual]
Implements OutputGenerator.
Definition at line 2133 of file htmlgen.cpp.
{
  if (first)
  {
    DBG_HTML(m_t << "<!-- startFirstParameterType -->\n";)
    m_t << " <td class=\"paramtype\">";
  }
  else
  {
    DBG_HTML(m_t << "<!-- startParameterType -->\n";)
    m_t << " <tr>\n";
    m_t << " <td class=\"paramkey\">" << key << "</td>\n";
    m_t << " <td></td>\n";
    m_t << " <td class=\"paramtype\">";
  }
}
References DBG_HTML, and OutputGenerator::m_t.
startParameterType() [2/2]
void HtmlGenerator::startParameterType (bool first, const QCString & key) [virtual]
Implements OutputGenerator.
startParamList() [1/2]
void HtmlGenerator::startParamList (ParamListTypes , const QCString & title) [virtual]
Implements BaseOutputDocInterface.
Definition at line 2437 of file htmlgen.cpp.
{
  m_t << "<dl><dt><b>";
  docify(title);
  m_t << "</b></dt>";
}
References docify(), and OutputGenerator::m_t.
startParamList() [2/2]
void HtmlGenerator::startParamList (ParamListTypes , const QCString &) [virtual]
Implements BaseOutputDocInterface.
startProjectNumber() [1/2]
void HtmlGenerator::startProjectNumber () [virtual]
Implements OutputGenerator.
Definition at line 1440 of file htmlgen.cpp.
{
  m_t << "<h3 class=\"version\">";
}
References OutputGenerator::m_t.
startProjectNumber() [2/2]
void HtmlGenerator::startProjectNumber () [virtual]
Implements OutputGenerator.
startQuickIndices() [1/2]
void HtmlGenerator::startQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 258 of file htmlgen.h.
{}
startQuickIndices() [2/2]
void HtmlGenerator::startQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 258 of file htmlgen.h.
{}
startSection() [1/2]
void HtmlGenerator::startSection (const QCString & lab, const QCString & , SectionType type) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1693 of file htmlgen.cpp.
{
  switch(type)
  {
    case SectionType::Page: m_t << "\n\n<h1>"; break;
    case SectionType::Section: m_t << "\n\n<h2>"; break;
    case SectionType::Subsection: m_t << "\n\n<h3>"; break;
    case SectionType::Subsubsection: m_t << "\n\n<h4>"; break;
    case SectionType::Paragraph: m_t << "\n\n<h5>"; break;
    default: ASSERT(0); break;
  }
  m_t << "<a id=\"" << lab << "\" name=\"" << lab << "\"></a>";
}
References ASSERT, OutputGenerator::m_t, Page, Paragraph, Section, Subsection, Subsubsection, and type().
startSection() [2/2]
void HtmlGenerator::startSection (const QCString & , const QCString & , SectionType) [virtual]
Implements BaseOutputDocInterface.
startSmall() [1/2]
void HtmlGenerator::startSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 242 of file htmlgen.h.
{ m_t << "<small>\n"; }
References OutputGenerator::m_t.
startSmall() [2/2]
void HtmlGenerator::startSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 242 of file htmlgen.h.
{ m_t << "<small>\n"; }
References OutputGenerator::m_t.
startSubsection() [1/2]
void HtmlGenerator::startSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 236 of file htmlgen.h.
{ m_t << "<h2>"; }
References OutputGenerator::m_t.
startSubsection() [2/2]
void HtmlGenerator::startSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 236 of file htmlgen.h.
{ m_t << "<h2>"; }
References OutputGenerator::m_t.
startSubsubsection() [1/2]
void HtmlGenerator::startSubsubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 238 of file htmlgen.h.
{ m_t << "<h3>"; }
References OutputGenerator::m_t.
startSubsubsection() [2/2]
void HtmlGenerator::startSubsubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 238 of file htmlgen.h.
{ m_t << "<h3>"; }
References OutputGenerator::m_t.
startTextBlock() [1/2]
void HtmlGenerator::startTextBlock (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 292 of file htmlgen.h.
    { m_t << "<div class=\"textblock\">"; }
References OutputGenerator::m_t.
startTextBlock() [2/2]
void HtmlGenerator::startTextBlock (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 292 of file htmlgen.h.
    { m_t << "<div class=\"textblock\">"; }
References OutputGenerator::m_t.
startTextLink() [1/2]
void HtmlGenerator::startTextLink (const QCString & file, const QCString & anchor) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1633 of file htmlgen.cpp.
{
  m_t << "<a href=\"";
  if (!f.isEmpty()) m_t << m_relPath << addHtmlExtensionIfMissing(f);
  if (!anchor.isEmpty()) m_t << "#" << anchor;
  m_t << "\">";
}
References addHtmlExtensionIfMissing(), f, QCString::isEmpty(), m_relPath, and OutputGenerator::m_t.
startTextLink() [2/2]
void HtmlGenerator::startTextLink (const QCString & file, const QCString & anchor) [virtual]
Implements BaseOutputDocInterface.
startTitle() [1/2]
void HtmlGenerator::startTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 135 of file htmlgen.h.
{ m_t << "<div class=\"title\">"; }
References OutputGenerator::m_t.
Referenced by startTitleHead().
startTitle() [2/2]
void HtmlGenerator::startTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 135 of file htmlgen.h.
{ m_t << "<div class=\"title\">"; }
References OutputGenerator::m_t.
startTitleHead() [1/2]
void HtmlGenerator::startTitleHead (const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 3119 of file htmlgen.cpp.
{
  m_t << " <div class=\"headertitle\">";
  startTitle();
}
References OutputGenerator::m_t, and startTitle().
startTitleHead() [2/2]
void HtmlGenerator::startTitleHead (const QCString &) [virtual]
Implements OutputGenerator.
startTypewriter() [1/2]
void HtmlGenerator::startTypewriter () [inline], [virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 162 of file htmlgen.h.
{ m_t << "<code>"; }
References OutputGenerator::m_t.
startTypewriter() [2/2]
void HtmlGenerator::startTypewriter () [inline], [virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 162 of file htmlgen.h.
{ m_t << "<code>"; }
References OutputGenerator::m_t.
type() [1/2]
virtual OutputType HtmlGenerator::type () const [inline], [virtual]
Implements OutputGenerator.
Definition at line 73 of file htmlgen.h.
{ return Html; }
References OutputGenerator::Html.
Referenced by endSection(), startSection(), and writeCodeLink().
type() [2/2]
virtual OutputType HtmlGenerator::type () const [inline], [virtual]
Implements OutputGenerator.
Definition at line 73 of file htmlgen.h.
{ return Html; }
References OutputGenerator::Html.
writeAnchor() [1/2]
void HtmlGenerator::writeAnchor (const QCString & , const QCString & name) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 210 of file htmlgen.h.
                         { m_t << "<a name=\"" << name <<"\" id=\"" << name << "\"></a>"; }
References OutputGenerator::m_t, and setup::name.
writeAnchor() [2/2]
void HtmlGenerator::writeAnchor (const QCString & , const QCString & name) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 210 of file htmlgen.h.
                         { m_t << "<a name=\"" << name <<"\" id=\"" << name << "\"></a>"; }
References OutputGenerator::m_t, and setup::name.
writeChar() [1/2]
void HtmlGenerator::writeChar (char c) [virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
Definition at line 1759 of file htmlgen.cpp.
{
  char cs[2];
  cs[0]=c;
  cs[1]=0;
  docify(cs);
}
References c, cs, and docify().
writeChar() [2/2]
void HtmlGenerator::writeChar (char c) [virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
writeCodeAnchor() [1/2]
void HtmlGenerator::writeCodeAnchor (const QCString & name) [inline], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 111 of file htmlgen.h.
    { m_codeGen.writeCodeAnchor(anchor); }
References m_codeGen, and HtmlCodeGenerator::writeCodeAnchor().
writeCodeAnchor() [2/2]
void HtmlGenerator::writeCodeAnchor (const QCString & name) [inline], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 111 of file htmlgen.h.
    { m_codeGen.writeCodeAnchor(anchor); }
References m_codeGen, and HtmlCodeGenerator::writeCodeAnchor().
writeCodeLink() [1/2]
void HtmlGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [inline], [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 92 of file htmlgen.h.
    { m_codeGen.writeCodeLink(type,ref,file,anchor,name,tooltip); }
References caseconvert::file, m_codeGen, setup::name, type(), and HtmlCodeGenerator::writeCodeLink().
writeCodeLink() [2/2]
void HtmlGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [inline], [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 92 of file htmlgen.h.
    { m_codeGen.writeCodeLink(type,ref,file,anchor,name,tooltip); }
References caseconvert::file, m_codeGen, setup::name, type(), and HtmlCodeGenerator::writeCodeLink().
writeDoc() [1/2]
void HtmlGenerator::writeDoc (const IDocNodeAST * node, const Definition * ctx, const MemberDef * , int id) [virtual]
Implements OutputGenerator.
Definition at line 2450 of file htmlgen.cpp.
{
  const DocNodeAST *astImpl = dynamic_cast<const DocNodeAST*>(ast);
  if (astImpl)
  {
    m_codeGen.setId(id);
    HtmlDocVisitor visitor(m_t,m_codeGen,ctx);
    std::visit(visitor,astImpl->root);
  }
}
References m_codeGen, OutputGenerator::m_t, DocNodeAST::root, and HtmlCodeGenerator::setId().
writeDoc() [2/2]
void HtmlGenerator::writeDoc (const IDocNodeAST * node, const Definition * , const MemberDef * , int id) [virtual]
Implements OutputGenerator.
writeEndAnnoItem() [1/2]
void HtmlGenerator::writeEndAnnoItem (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 235 of file htmlgen.h.
{ m_t << "\n"; }
References OutputGenerator::m_t.
writeEndAnnoItem() [2/2]
void HtmlGenerator::writeEndAnnoItem (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 235 of file htmlgen.h.
{ m_t << "\n"; }
References OutputGenerator::m_t.
writeExternalSearchPage() [1/2]
void HtmlGenerator::writeExternalSearchPage () [static]
Definition at line 2947 of file htmlgen.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  QCString dname = Config_getString(HTML_OUTPUT);
  QCString fileName = dname+"/search"+Doxygen::htmlFileExtension;
  std::ofstream f(fileName.str(),std::ofstream::out | std::ofstream::binary);
  if (f.is_open())
  {
    TextStream t(&f);
    t << substituteHtmlKeywords(g_header,"Search","");
    t << "<!-- " << theTranslator->trGeneratedBy() << " Doxygen "
      << getDoxygenVersion() << " -->\n";
    t << "<script type=\"text/javascript\">\n";
        t << "/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */\n";
        t << "var searchBox = new SearchBox(\"searchBox\", \""
      << "search/\",'" << Doxygen::htmlFileExtension << "');\n";
        t << "/* @license-end */\n";
    t << "</script>\n";
    if (!Config_getBool(DISABLE_INDEX))
    {
      writeDefaultQuickLinks(t,TRUE,HLI_Search,QCString(),QCString());
      if (!Config_getBool(HTML_DYNAMIC_MENUS)) // for dynamic menus, menu.js creates this part
      {
        t << " <input type=\"text\" id=\"MSearchField\" name=\"query\" value=\"\" placeholder=\"" << theTranslator->trSearch() <<
             "\" size=\"20\" accesskey=\"S\" onfocus=\"searchBox.OnSearchFieldFocus(true)\" onblur=\"searchBox.OnSearchFieldFocus(false)\"/>\n";
      }
      t << " </form>\n";
      t << " </div><div class=\"right\"></div>\n";
      t << " </div>\n";
      t << " </li>\n";
      t << " </ul>\n";
      t << " </div>\n";
      t << "</div>\n";
    }
    else
    {
      t << "</div>\n";
    }
    t << writeSplitBarAsString("search","");
    t << "<div class=\"header\">\n";
    t << " <div class=\"headertitle\">\n";
    t << " <div class=\"title\">" << theTranslator->trSearchResultsTitle() << "</div>\n";
    t << " </div>\n";
    t << "</div>\n";
    t << "<div class=\"contents\">\n";
    t << "<div id=\"searchresults\"></div>\n";
    t << "</div>\n";
    if (generateTreeView)
    {
      t << "</div><!-- doc-content -->\n";
    }
    writePageFooter(t,"Search","","");
  }
  f.close();
  QCString scriptName = dname+"/search/search.js";
  f.open(scriptName.str(),std::ofstream::out | std::ofstream::binary);
  if (f.is_open())
  {
    TextStream t(&f);
    t << "var searchResultsText=["
      << "\"" << theTranslator->trSearchResults(0) << "\","
      << "\"" << theTranslator->trSearchResults(1) << "\","
      << "\"" << theTranslator->trSearchResults(2) << "\"];\n";
    t << "var serverUrl=\"" << Config_getString(SEARCHENGINE_URL) << "\";\n";
    t << "var tagMap = {\n";
    bool first=TRUE;
    // add search mappings
    const StringVector &extraSearchMappings = Config_getList(EXTRA_SEARCH_MAPPINGS);
    for (const auto &ml : extraSearchMappings)
    {
      QCString mapLine = ml.c_str();
      int eqPos = mapLine.find('=');
      if (eqPos!=-1) // tag command contains a destination
      {
        QCString tagName = mapLine.left(eqPos).stripWhiteSpace();
        QCString destName = mapLine.right(mapLine.length()-eqPos-1).stripWhiteSpace();
        if (!tagName.isEmpty())
        {
          if (!first) t << ",\n";
          t << " \"" << tagName << "\": \"" << destName << "\"";
          first=FALSE;
        }
      }
    }
    if (!first) t << "\n";
    t << "};\n\n";
    t << ResourceMgr::instance().getAsString("extsearch.js");
    t << "\n";
    t << "$(document).ready(function() {\n";
    t << " var query = trim(getURLParameter('query'));\n";
    t << " if (query) {\n";
    t << " searchFor(query,0,20);\n";
    t << " } else {\n";
    t << " var results = $('#results');\n";
    t << " results.html('<p>" << theTranslator->trSearchResults(0) << "</p>');\n";
    t << " }\n";
    t << "});\n";
  }
  else
  {
     err("Failed to open file '%s' for writing...\n",qPrint(scriptName));
  }
}
References Config_getBool, Config_getList, Config_getString, err(), f, FALSE, OutputGenerator::fileName(), QCString::find(), g_header, ResourceMgr::getAsString(), getDoxygenVersion(), HLI_Search, Doxygen::htmlFileExtension, ResourceMgr::instance(), QCString::isEmpty(), QCString::left(), QCString::length(), out, qPrint(), QCString::right(), QCString::str(), QCString::stripWhiteSpace(), substituteHtmlKeywords(), theTranslator, Translator::trGeneratedBy(), Translator::trSearch(), Translator::trSearchResults(), Translator::trSearchResultsTitle(), TRUE, writeDefaultQuickLinks(), writePageFooter(), and writeSplitBarAsString().
Referenced by generateOutput().
writeExternalSearchPage() [2/2]
static void HtmlGenerator::writeExternalSearchPage () [static]
writeFooter() [1/2]
void HtmlGenerator::writeFooter (const QCString & navPath) [virtual]
Implements OutputGenerator.
Definition at line 1430 of file htmlgen.cpp.
{
  writePageFooter(m_t,m_lastTitle,m_relPath,navPath);
}
References m_lastTitle, m_relPath, OutputGenerator::m_t, and writePageFooter().
writeFooter() [2/2]
void HtmlGenerator::writeFooter (const QCString & navPath) [virtual]
Implements OutputGenerator.
writeFooterFile() [1/2]
void HtmlGenerator::writeFooterFile (TextStream & t) [static]
Definition at line 1317 of file htmlgen.cpp.
{
  t << "<!-- HTML footer for doxygen " << getDoxygenVersion() << "-->\n";
  t << ResourceMgr::instance().getAsString("footer.html");
}
References ResourceMgr::getAsString(), getDoxygenVersion(), and ResourceMgr::instance().
Referenced by readConfiguration().
writeFooterFile() [2/2]
static void HtmlGenerator::writeFooterFile (TextStream & t) [static]
writeGraphicalHierarchy() [1/2]
void HtmlGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable & g) [virtual]
Implements OutputGenerator.
Definition at line 2326 of file htmlgen.cpp.
{
  g.writeGraph(m_t,dir(),fileName());
}
References OutputGenerator::dir(), OutputGenerator::fileName(), g, and OutputGenerator::m_t.
writeGraphicalHierarchy() [2/2]
void HtmlGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable & g) [virtual]
Implements OutputGenerator.
writeHeaderFile() [1/2]
void HtmlGenerator::writeHeaderFile (TextStream & t, const QCString & cssname) [static]
Definition at line 1311 of file htmlgen.cpp.
{
  t << "<!-- HTML header for doxygen " << getDoxygenVersion() << "-->\n";
  t << ResourceMgr::instance().getAsString("header.html");
}
References ResourceMgr::getAsString(), getDoxygenVersion(), and ResourceMgr::instance().
Referenced by readConfiguration().
writeHeaderFile() [2/2]
static void HtmlGenerator::writeHeaderFile (TextStream & t, const QCString & cssname) [static]
writeInheritedSectionTitle() [1/2]
void HtmlGenerator::writeInheritedSectionTitle (const QCString & id, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & title, const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 3222 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- writeInheritedSectionTitle -->\n";)
  QCString a = anchor;
  if (!a.isEmpty()) a.prepend("#");
  QCString classLink = QCString("<a class=\"el\" ");
  if (!ref.isEmpty())
  {
    classLink+= externalLinkTarget();
    classLink += " href=\"";
    classLink+= externalRef(m_relPath,ref,TRUE);
  }
  else
  {
    classLink += "href=\"";
    classLink+=m_relPath;
  }
  classLink=classLink+addHtmlExtensionIfMissing(file)+a;
  classLink+=QCString("\">")+convertToHtml(name,FALSE)+"</a>";
  m_t << "<tr class=\"inherit_header " << id << "\">"
    << "<td colspan=\"2\" onclick=\"javascript:toggleInherit('" << id << "')\">"
    << "<img src=\"" << m_relPath << "closed.png\" alt=\"-\"/>&#160;"
    << theTranslator->trInheritedFrom(convertToHtml(title,FALSE),classLink)
    << "</td></tr>\n";
}
References a, addHtmlExtensionIfMissing(), convertToHtml(), DBG_HTML, externalLinkTarget(), externalRef(), FALSE, caseconvert::file, QCString::isEmpty(), m_relPath, OutputGenerator::m_t, setup::name, theTranslator, Translator::trInheritedFrom(), and TRUE.
writeInheritedSectionTitle() [2/2]
void HtmlGenerator::writeInheritedSectionTitle (const QCString & id, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & title, const QCString & name) [virtual]
Implements OutputGenerator.
writeLabel() [1/2]
void HtmlGenerator::writeLabel (const QCString & l, bool isLast) [virtual]
Implements OutputGenerator.
Definition at line 3208 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- writeLabel(" << l << ") -->\n";)
  //m_t << "<tt>[" << l << "]</tt>";
  //if (!isLast) m_t << ", ";
  m_t << "<span class=\"mlabel\">" << l << "</span>";
}
References DBG_HTML, and OutputGenerator::m_t.
writeLabel() [2/2]
void HtmlGenerator::writeLabel (const QCString & l, bool isLast) [virtual]
Implements OutputGenerator.
writeLatexSpacing() [1/2]
void HtmlGenerator::writeLatexSpacing () [inline], [virtual]
Implements OutputGenerator.
Definition at line 232 of file htmlgen.h.
{}
writeLatexSpacing() [2/2]
void HtmlGenerator::writeLatexSpacing () [inline], [virtual]
Implements OutputGenerator.
Definition at line 232 of file htmlgen.h.
{}
writeLineNumber() [1/2]
void HtmlGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [inline], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 97 of file htmlgen.h.
    { m_codeGen.writeLineNumber(ref,file,anchor,lineNumber,writeLineAnchor); }
References caseconvert::file, m_codeGen, and HtmlCodeGenerator::writeLineNumber().
writeLineNumber() [2/2]
void HtmlGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [inline], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 97 of file htmlgen.h.
    { m_codeGen.writeLineNumber(ref,file,anchor,lineNumber,writeLineAnchor); }
References caseconvert::file, m_codeGen, and HtmlCodeGenerator::writeLineNumber().
writeLogo() [1/2]
void HtmlGenerator::writeLogo () [virtual]
Implements OutputGenerator.
Definition at line 1419 of file htmlgen.cpp.
{
  m_t << writeLogoAsString(m_relPath);
}
References m_relPath, OutputGenerator::m_t, and writeLogoAsString().
writeLogo() [2/2]
void HtmlGenerator::writeLogo () [virtual]
Implements OutputGenerator.
writeLogoAsString() [1/2]
QCString HtmlGenerator::writeLogoAsString (const QCString & path) [static]
Definition at line 1395 of file htmlgen.cpp.
{
  bool timeStamp = Config_getBool(HTML_TIMESTAMP);
  QCString result;
  if (timeStamp)
  {
    result += theTranslator->trGeneratedAt(
               dateToString(TRUE),
               Config_getString(PROJECT_NAME)
              );
  }
  else
  {
    result += theTranslator->trGeneratedBy();
  }
  result += "&#160;\n<a href=\"https://www.doxygen.org/index.html\">\n"
            "<img class=\"footer\" src=\"";
  result += path;
  result += "doxygen.svg\" width=\"104\" height=\"31\" alt=\"doxygen\"/></a> ";
  result += getDoxygenVersion();
  result += " ";
  return result;
}
References Config_getBool, Config_getString, dateToString(), getDoxygenVersion(), theTranslator, Translator::trGeneratedAt(), Translator::trGeneratedBy(), and TRUE.
Referenced by writeLogo(), and writeSearchPage().
writeLogoAsString() [2/2]
static QCString HtmlGenerator::writeLogoAsString (const QCString & path) [static]
writeNavigationPath() [1/2]
void HtmlGenerator::writeNavigationPath (const QCString & s) [virtual]
Implements OutputGenerator.
Definition at line 2825 of file htmlgen.cpp.
{
  m_t << substitute(s,"$relpath^",m_relPath);
}
References m_relPath, OutputGenerator::m_t, s, and substitute().
writeNavigationPath() [2/2]
void HtmlGenerator::writeNavigationPath (const QCString & s) [virtual]
Implements OutputGenerator.
writeNonBreakableSpace() [1/2]
void HtmlGenerator::writeNonBreakableSpace (int n) [virtual]
Implements BaseOutputDocInterface.
Definition at line 2376 of file htmlgen.cpp.
{
  int i;
  for (i=0;i<n;i++)
  {
    m_t << "&#160;";
  }
}
References OutputGenerator::m_t, and n.
writeNonBreakableSpace() [2/2]
void HtmlGenerator::writeNonBreakableSpace (int) [virtual]
Implements BaseOutputDocInterface.
writeObjectLink() [1/2]
void HtmlGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
Definition at line 1612 of file htmlgen.cpp.
{
  if (!ref.isEmpty())
  {
    m_t << "<a class=\"elRef\" ";
    m_t << externalLinkTarget();
  }
  else
  {
    m_t << "<a class=\"el\" ";
  }
  m_t << "href=\"";
  m_t << externalRef(m_relPath,ref,TRUE);
  if (!f.isEmpty()) m_t << addHtmlExtensionIfMissing(f);
  if (!anchor.isEmpty()) m_t << "#" << anchor;
  m_t << "\">";
  docify(name);
  m_t << "</a>";
}
References addHtmlExtensionIfMissing(), docify(), externalLinkTarget(), externalRef(), f, QCString::isEmpty(), m_relPath, OutputGenerator::m_t, setup::name, and TRUE.
writeObjectLink() [2/2]
void HtmlGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
writePageFooter() [1/2]
void HtmlGenerator::writePageFooter (TextStream & t, const QCString & lastTitle, const QCString & relPath, const QCString & navPath) [static], [private]
Definition at line 1424 of file htmlgen.cpp.
{
  t << substituteHtmlKeywords(g_footer,convertToHtml(lastTitle),relPath,navPath);
}
References convertToHtml(), g_footer, and substituteHtmlKeywords().
Referenced by writeExternalSearchPage(), writeFooter(), and writeSearchPage().
writePageFooter() [2/2]
static void HtmlGenerator::writePageFooter (TextStream & t, const QCString & , const QCString & , const QCString &) [static], [private]
writePageLink() [1/2]
void HtmlGenerator::writePageLink (const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 129 of file htmlgen.h.
{}
writePageLink() [2/2]
void HtmlGenerator::writePageLink (const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 129 of file htmlgen.h.
{}
writeQuickLinks() [1/2]
void HtmlGenerator::writeQuickLinks (bool compact, HighlightedItem hli, const QCString & file) [virtual]
Implements OutputGenerator.
Definition at line 2850 of file htmlgen.cpp.
{
  writeDefaultQuickLinks(m_t,compact,hli,file,m_relPath);
}
References caseconvert::file, m_relPath, OutputGenerator::m_t, and writeDefaultQuickLinks().
writeQuickLinks() [2/2]
void HtmlGenerator::writeQuickLinks (bool compact, HighlightedItem hli, const QCString & file) [virtual]
Implements OutputGenerator.
writeRuler() [1/2]
void HtmlGenerator::writeRuler () [inline], [virtual]
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 209 of file htmlgen.h.
{ m_t << "<hr/>"; }
References OutputGenerator::m_t.
writeRuler() [2/2]
void HtmlGenerator::writeRuler () [inline], [virtual]
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 209 of file htmlgen.h.
{ m_t << "<hr/>"; }
References OutputGenerator::m_t.
writeSearchData() [1/2]
void HtmlGenerator::writeSearchData (const QCString & dir) [static]
Definition at line 1189 of file htmlgen.cpp.
{
  //bool serverBasedSearch = Config_getBool(SERVER_BASED_SEARCH);
  //writeImgData(dname,serverBasedSearch ? search_server_data : search_client_data);
  ResourceMgr &mgr = ResourceMgr::instance();
  // server side search resources
  mgr.copyResource("mag.svg",dname);
  mgr.copyResource("mag_d.svg",dname);
  Doxygen::indexList->addImageFile("search/mag.svg");
  Doxygen::indexList->addImageFile("search/mag_d.svg");
  // client side search resources
  mgr.copyResource("close.svg",dname);
  Doxygen::indexList->addImageFile("search/close.svg");
  mgr.copyResource("mag_sel.svg",dname);
  mgr.copyResource("mag_seld.svg",dname);
  Doxygen::indexList->addImageFile("search/mag_sel.svg");
  Doxygen::indexList->addImageFile("search/mag_seld.svg");
  QCString searchDirName = dname;
  std::ofstream f(searchDirName.str()+"/search.css",std::ofstream::out | std::ofstream::binary);
  if (f.is_open())
  {
    TextStream t(&f);
    QCString searchCss;
    // the position of the search box depends on a number of settings.
    // Insert the right piece of CSS code depending on which options are selected
    if (Config_getBool(DISABLE_INDEX))
    {
      if (Config_getBool(GENERATE_TREEVIEW) && Config_getBool(FULL_SIDEBAR))
      {
        searchCss = mgr.getAsString("search_sidebar.css"); // we have a full height side bar
      }
      else if (Config_getBool(HTML_COLORSTYLE)==HTML_COLORSTYLE_t::TOGGLE)
      {
        searchCss = mgr.getAsString("search_nomenu_toggle.css"); // we have no tabs but do have a darkmode button
      }
      else
      {
        searchCss = mgr.getAsString("search_nomenu.css"); // we have no tabs and no darkmode button
      }
    }
    else if (!Config_getBool(HTML_DYNAMIC_MENUS))
    {
      searchCss = mgr.getAsString("search_fixedtabs.css"); // we have tabs, but they are static
    }
    else
    {
      searchCss = mgr.getAsString("search.css"); // default case with a dynamic menu bar
    }
    // and then add the option independent part of the styling
    searchCss += mgr.getAsString("search_common.css");
    searchCss = substitute(searchCss,"$doxygenversion",getDoxygenVersion());
    t << replaceVariables(searchCss);
    Doxygen::indexList->addStyleSheetFile("search/search.css");
  }
}
References IndexList::addImageFile(), IndexList::addStyleSheetFile(), Config_getBool, ResourceMgr::copyResource(), f, ResourceMgr::getAsString(), getDoxygenVersion(), Doxygen::indexList, ResourceMgr::instance(), out, replaceVariables(), QCString::str(), and substitute().
Referenced by generateOutput().
writeSearchData() [2/2]
static void HtmlGenerator::writeSearchData (const QCString & dir) [static]
writeSearchInfo() [1/4]
void HtmlGenerator::writeSearchInfo () [virtual]
Implements OutputGenerator.
Definition at line 1389 of file htmlgen.cpp.
{
  writeSearchInfo(m_t,m_relPath);
}
References m_relPath, OutputGenerator::m_t, and writeSearchInfo().
Referenced by writeSearchInfo().
writeSearchInfo() [2/4]
void HtmlGenerator::writeSearchInfo () [virtual]
Implements OutputGenerator.
writeSearchInfo() [3/4]
void HtmlGenerator::writeSearchInfo (TextStream & t, const QCString & relPath) [static]
Definition at line 1359 of file htmlgen.cpp.
{
  bool searchEngine = Config_getBool(SEARCHENGINE);
  bool serverBasedSearch = Config_getBool(SERVER_BASED_SEARCH);
  if (searchEngine && !serverBasedSearch)
  {
    t << "<!-- window showing the filter options -->\n";
    t << "<div id=\"MSearchSelectWindow\"\n";
    t << " onmouseover=\"return searchBox.OnSearchSelectShow()\"\n";
    t << " onmouseout=\"return searchBox.OnSearchSelectHide()\"\n";
    t << " onkeydown=\"return searchBox.OnSearchSelectKey(event)\">\n";
    t << "</div>\n";
    t << "\n";
    t << "<!-- iframe showing the search results (closed by default) -->\n";
    t << "<div id=\"MSearchResultsWindow\">\n";
    t << "<div id=\"MSearchResults\">\n";
    t << "<div class=\"SRPage\">\n";
    t << "<div id=\"SRIndex\">\n";
    t << "<div id=\"SRResults\"></div>\n"; // here the results will be inserted
    t << "<div class=\"SRStatus\" id=\"Loading\">" << theTranslator->trLoading() << "</div>\n";
    t << "<div class=\"SRStatus\" id=\"Searching\">" << theTranslator->trSearching() << "</div>\n";
    t << "<div class=\"SRStatus\" id=\"NoMatches\">" << theTranslator->trNoMatches() << "</div>\n";
    t << "</div>\n"; // SRIndex
    t << "</div>\n"; // SRPage
    t << "</div>\n"; // MSearchResults
    t << "</div>\n"; // MSearchResultsWindow
    t << "\n";
  }
}
References Config_getBool, theTranslator, Translator::trLoading(), Translator::trNoMatches(), and Translator::trSearching().
writeSearchInfo() [4/4]
static void HtmlGenerator::writeSearchInfo (TextStream & t, const QCString & relPath) [static]
writeSearchPage() [1/2]
void HtmlGenerator::writeSearchPage () [static]
Definition at line 2856 of file htmlgen.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  bool disableIndex = Config_getBool(DISABLE_INDEX);
  QCString projectName = Config_getString(PROJECT_NAME);
  QCString htmlOutput = Config_getString(HTML_OUTPUT);
  // OPENSEARCH_PROVIDER {
  QCString configFileName = htmlOutput+"/search_config.php";
  std::ofstream f(configFileName.str(),std::ofstream::out | std::ofstream::binary);
  if (f.is_open())
  {
    TextStream t(&f);
    t << "<?php\n\n";
    t << "$config = array(\n";
    t << " 'PROJECT_NAME' => \"" << convertToHtml(projectName) << "\",\n";
    t << " 'GENERATE_TREEVIEW' => " << (generateTreeView?"true":"false") << ",\n";
    t << " 'DISABLE_INDEX' => " << (disableIndex?"true":"false") << ",\n";
    t << ");\n\n";
    t << "$translator = array(\n";
    t << " 'search_results_title' => \"" << theTranslator->trSearchResultsTitle() << "\",\n";
    t << " 'search_results' => array(\n";
    t << " 0 => \"" << theTranslator->trSearchResults(0) << "\",\n";
    t << " 1 => \"" << theTranslator->trSearchResults(1) << "\",\n";
    t << " 2 => \"" << substitute(theTranslator->trSearchResults(2), "$", "\\$") << "\",\n";
    t << "),\n";
    t << " 'search_matches' => \"" << theTranslator->trSearchMatches() << "\",\n";
    t << " 'search' => \"" << theTranslator->trSearch() << "\",\n";
    t << " 'split_bar' => \"" << substitute(substitute(writeSplitBarAsString("search",""), "\"","\\\""), "\n","\\n") << "\",\n";
    t << " 'logo' => \"" << substitute(substitute(writeLogoAsString(""), "\"","\\\""), "\n","\\n") << "\",\n";
    t << ");\n\n";
    t << "?>\n";
  }
  f.close();
  ResourceMgr::instance().copyResource("search_functions.php",htmlOutput);
  ResourceMgr::instance().copyResource("search_opensearch.php",htmlOutput);
  // OPENSEARCH_PROVIDER }
  QCString fileName = htmlOutput+"/search.php";
  f.open(fileName.str(),std::ofstream::out | std::ofstream::binary);
  if (f.is_open())
  {
    TextStream t(&f);
    t << substituteHtmlKeywords(g_header,"Search","");
    t << "<!-- " << theTranslator->trGeneratedBy() << " Doxygen "
      << getDoxygenVersion() << " -->\n";
    t << "<script type=\"text/javascript\">\n";
        t << "/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */\n";
        t << "var searchBox = new SearchBox(\"searchBox\", \""
      << "search/\",'" << Doxygen::htmlFileExtension << "');\n";
        t << "/* @license-end */\n";
    t << "</script>\n";
    if (!Config_getBool(DISABLE_INDEX))
    {
      writeDefaultQuickLinks(t,TRUE,HLI_Search,QCString(),QCString());
    }
    else
    {
      t << "</div>\n";
    }
    t << "<?php\n";
    t << "require_once \"search_functions.php\";\n";
    t << "main();\n";
    t << "?>\n";
    // Write empty navigation path, to make footer connect properly
    if (generateTreeView)
    {
      t << "</div><!-- doc-content -->\n";
    }
    writePageFooter(t,"Search","","");
  }
  f.close();
  QCString scriptName = htmlOutput+"/search/search.js";
  f.open(scriptName.str(),std::ofstream::out | std::ofstream::binary);
  if (f.is_open())
  {
    TextStream t(&f);
    t << ResourceMgr::instance().getAsString("extsearch.js");
  }
  else
  {
     err("Failed to open file '%s' for writing...\n",qPrint(scriptName));
  }
}
References Config_getBool, Config_getString, convertToHtml(), ResourceMgr::copyResource(), err(), f, OutputGenerator::fileName(), g_header, ResourceMgr::getAsString(), getDoxygenVersion(), HLI_Search, Doxygen::htmlFileExtension, ResourceMgr::instance(), out, qPrint(), QCString::str(), substitute(), substituteHtmlKeywords(), theTranslator, Translator::trGeneratedBy(), Translator::trSearch(), Translator::trSearchMatches(), Translator::trSearchResults(), Translator::trSearchResultsTitle(), TRUE, writeDefaultQuickLinks(), writeLogoAsString(), writePageFooter(), and writeSplitBarAsString().
Referenced by generateOutput().
writeSearchPage() [2/2]
static void HtmlGenerator::writeSearchPage () [static]
writeSplitBar() [1/2]
void HtmlGenerator::writeSplitBar (const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 2820 of file htmlgen.cpp.
{
  m_t << writeSplitBarAsString(name,m_relPath);
}
References m_relPath, OutputGenerator::m_t, setup::name, and writeSplitBarAsString().
writeSplitBar() [2/2]
void HtmlGenerator::writeSplitBar (const QCString & name) [virtual]
Implements OutputGenerator.
writeSplitBarAsString() [1/2]
QCString HtmlGenerator::writeSplitBarAsString (const QCString & name, const QCString & relpath) [static]
Definition at line 2785 of file htmlgen.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  QCString result;
  // write split bar
  if (generateTreeView)
  {
    if (!Config_getBool(DISABLE_INDEX) || !Config_getBool(FULL_SIDEBAR))
    {
      result += QCString(
        "<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n");
    }
    result+= QCString(
     " <div id=\"nav-tree\">\n"
     " <div id=\"nav-tree-contents\">\n"
     " <div id=\"nav-sync\" class=\"sync\"></div>\n"
     " </div>\n"
     " </div>\n"
     " <div id=\"splitbar\" style=\"-moz-user-select:none;\" \n"
     " class=\"ui-resizable-handle\">\n"
     " </div>\n"
     "</div>\n"
     "<script type=\"text/javascript\">\n"
     "/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */\n"
     "$(document).ready(function(){initNavTree('") +
     QCString(addHtmlExtensionIfMissing(name)) +
     QCString("','") + relpath +
     QCString("'); initResizable(); });\n"
     "/* @license-end */\n"
     "</script>\n"
     "<div id=\"doc-content\">\n");
  }
  return result;
}
References addHtmlExtensionIfMissing(), Config_getBool, and setup::name.
Referenced by writeExternalSearchPage(), writeSearchPage(), and writeSplitBar().
writeSplitBarAsString() [2/2]
static QCString HtmlGenerator::writeSplitBarAsString (const QCString & name, const QCString & relpath) [static]
writeStartAnnoItem() [1/2]
void HtmlGenerator::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 1602 of file htmlgen.cpp.
{
  m_t << "<li>";
  if (!path.isEmpty()) docify(path);
  m_t << "<a class=\"el\" href=\"" << addHtmlExtensionIfMissing(f) << "\">";
  docify(name);
  m_t << "</a> ";
}
References addHtmlExtensionIfMissing(), docify(), f, QCString::isEmpty(), OutputGenerator::m_t, and setup::name.
writeStartAnnoItem() [2/2]
void HtmlGenerator::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) [virtual]
Implements OutputGenerator.
writeString() [1/2]
void HtmlGenerator::writeString (const QCString & text) [virtual]
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
Definition at line 1549 of file htmlgen.cpp.
{
  m_t << text;
}
References OutputGenerator::m_t.
writeString() [2/2]
void HtmlGenerator::writeString (const QCString & text) [virtual]
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
writeStyleInfo() [1/2]
void HtmlGenerator::writeStyleInfo (int part) [virtual]
Implements OutputGenerator.
Definition at line 1450 of file htmlgen.cpp.
{
  //printf("writeStyleInfo(%d)\n",part);
  if (part==0)
  {
    if (Config_getString(HTML_STYLESHEET).isEmpty()) // write default style sheet
    {
      //printf("write doxygen.css\n");
      startPlainFile("doxygen.css");
      writeDefaultStyleSheet(m_t);
      endPlainFile();
      Doxygen::indexList->addStyleSheetFile("doxygen.css");
    }
    else // write user defined style sheet
    {
      QCString cssName=Config_getString(HTML_STYLESHEET);
      if (!cssName.startsWith("http:") && !cssName.startsWith("https:"))
      {
        FileInfo cssfi(cssName.str());
        if (!cssfi.exists() || !cssfi.isFile() || !cssfi.isReadable())
        {
          err("style sheet %s does not exist or is not readable!", qPrint(Config_getString(HTML_STYLESHEET)));
        }
        else
        {
          // convert style sheet to string
          QCString fileStr = fileToString(cssName);
          // write the string into the output dir
          startPlainFile(cssfi.fileName().c_str());
          m_t << fileStr;
          endPlainFile();
        }
        Doxygen::indexList->addStyleSheetFile(cssfi.fileName().c_str());
      }
    }
    const StringVector &extraCssFiles = Config_getList(HTML_EXTRA_STYLESHEET);
    for (const auto &fileName : extraCssFiles)
    {
      if (!fileName.empty())
      {
        FileInfo fi(fileName);
        if (fi.exists())
        {
          Doxygen::indexList->addStyleSheetFile(fi.fileName().c_str());
        }
      }
    }
    Doxygen::indexList->addStyleSheetFile("jquery.js");
    Doxygen::indexList->addStyleSheetFile("dynsections.js");
    if (Config_getEnum(HTML_COLORSTYLE)==HTML_COLORSTYLE_t::TOGGLE)
    {
      Doxygen::indexList->addStyleSheetFile("darkmode_toggle.js");
    }
    if (Config_getBool(INTERACTIVE_SVG))
    {
      Doxygen::indexList->addStyleSheetFile("svgpan.js");
    }
    if (!Config_getBool(DISABLE_INDEX) && Config_getBool(HTML_DYNAMIC_MENUS))
    {
      Doxygen::indexList->addStyleSheetFile("menu.js");
      Doxygen::indexList->addStyleSheetFile("menudata.js");
    }
  }
}
References IndexList::addStyleSheetFile(), Config_getBool, Config_getEnum, Config_getList, Config_getString, OutputGenerator::endPlainFile(), err(), FileInfo::exists(), FileInfo::fileName(), OutputGenerator::fileName(), fileToString(), Doxygen::indexList, FileInfo::isFile(), FileInfo::isReadable(), OutputGenerator::m_t, qPrint(), OutputGenerator::startPlainFile(), QCString::startsWith(), QCString::str(), and writeDefaultStyleSheet().
writeStyleInfo() [2/2]
void HtmlGenerator::writeStyleInfo (int part) [virtual]
Implements OutputGenerator.
writeStyleSheetFile() [1/2]
void HtmlGenerator::writeStyleSheetFile (TextStream & t) [static]
Definition at line 1305 of file htmlgen.cpp.
{
  fillColorStyleMaps();
  writeDefaultStyleSheet(t);
}
References fillColorStyleMaps(), and writeDefaultStyleSheet().
Referenced by readConfiguration().
writeStyleSheetFile() [2/2]
static void HtmlGenerator::writeStyleSheetFile (TextStream & t) [static]
writeSummaryLink() [1/2]
void HtmlGenerator::writeSummaryLink (const QCString & file, const QCString & anchor, const QCString & title, bool first) [virtual]
Implements OutputGenerator.
Definition at line 3251 of file htmlgen.cpp.
{
  if (first)
  {
    m_t << " <div class=\"summary\">\n";
  }
  else
  {
    m_t << " &#124;\n";
  }
  m_t << "<a href=\"";
  if (!file.isEmpty())
  {
    m_t << m_relPath << addHtmlExtensionIfMissing(file);
  }
  else if (!anchor.isEmpty())
  {
    m_t << "#";
    m_t << anchor;
  }
  m_t << "\">";
  m_t << title;
  m_t << "</a>";
}
References addHtmlExtensionIfMissing(), caseconvert::file, QCString::isEmpty(), m_relPath, and OutputGenerator::m_t.
writeSummaryLink() [2/2]
void HtmlGenerator::writeSummaryLink (const QCString & file, const QCString & anchor, const QCString & title, bool first) [virtual]
Implements OutputGenerator.
writeSynopsis() [1/2]
void HtmlGenerator::writeSynopsis () [inline], [virtual]
Implements OutputGenerator.
Definition at line 253 of file htmlgen.h.
{}
writeSynopsis() [2/2]
void HtmlGenerator::writeSynopsis () [inline], [virtual]
Implements OutputGenerator.
Definition at line 253 of file htmlgen.h.
{}
writeTabData() [1/2]
void HtmlGenerator::writeTabData () [static]
Additional initialization after indices have been created.
Definition at line 1151 of file htmlgen.cpp.
{
  Doxygen::indexList->addStyleSheetFile("tabs.css");
  QCString dname=Config_getString(HTML_OUTPUT);
  ResourceMgr &mgr = ResourceMgr::instance();
  //writeColoredImgData(dname,colored_tab_data);
  mgr.copyResource("tab_a.lum",dname); // active, light mode
  mgr.copyResource("tab_b.lum",dname); // normal, light mode
  mgr.copyResource("tab_h.lum",dname); // highlight, light mode
  mgr.copyResource("tab_s.lum",dname); // separator, light mode
  mgr.copyResource("tab_ad.lum",dname); // active, dark mode
  mgr.copyResource("tab_bd.lum",dname); // normal, dark mode
  mgr.copyResource("tab_hd.lum",dname); // highlight, dark mode
  mgr.copyResource("tab_sd.lum",dname); // separator, light mode
  mgr.copyResource("nav_h.lum",dname); // header gradient, light mode
  mgr.copyResource("nav_hd.lum",dname); // header gradient, dark mode
  mgr.copyResource("nav_f.lum",dname); // member definition header, light mode
  mgr.copyResource("nav_fd.lum",dname); // member definition header, dark mode
  mgr.copyResource("bc_s.luma",dname); // breadcrumb separator, light mode
  mgr.copyResource("bc_sd.luma",dname); // breadcrumb separator, dark mode
  mgr.copyResource("doxygen.svg",dname);
  Doxygen::indexList->addImageFile("doxygen.svg");
  mgr.copyResource("closed.luma",dname);
  mgr.copyResource("open.luma",dname);
  mgr.copyResource("bdwn.luma",dname);
  mgr.copyResource("sync_on.luma",dname);
  mgr.copyResource("sync_off.luma",dname);
  //{
  // unsigned char shadow[6] = { 5, 5, 5, 5, 5, 5 };
  // unsigned char shadow_alpha[6] = { 80, 60, 40, 20, 10, 0 };
  // ColoredImage img(1,6,shadow,shadow_alpha,0,0,100);
  // img.save(dname+"/nav_g.png");
  //}
  mgr.copyResource("nav_g.png",dname);
  Doxygen::indexList->addImageFile("nav_g.png");
}
References IndexList::addImageFile(), IndexList::addStyleSheetFile(), Config_getString, ResourceMgr::copyResource(), Doxygen::indexList, and ResourceMgr::instance().
Referenced by generateOutput().
writeTabData() [2/2]
static void HtmlGenerator::writeTabData () [static]
writeTooltip() [1/2]
void HtmlGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 99 of file htmlgen.h.
    { m_codeGen.writeTooltip(id,docInfo,decl,desc,defInfo,declInfo); }
References m_codeGen, and HtmlCodeGenerator::writeTooltip().
writeTooltip() [2/2]
void HtmlGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 99 of file htmlgen.h.
    { m_codeGen.writeTooltip(id,docInfo,decl,desc,defInfo,declInfo); }
References m_codeGen, and HtmlCodeGenerator::writeTooltip().
Member Data Documentation
m_codeGen
HtmlCodeGenerator HtmlGenerator::m_codeGen [private]
Definition at line 341 of file htmlgen.h.
Referenced by codify(), endCodeFragment(), endCodeLine(), endFontClass(), startCodeFragment(), startCodeLine(), startFile(), startFontClass(), writeCodeAnchor(), writeCodeLink(), writeDoc(), writeLineNumber(), and writeTooltip().
m_emptySection
bool HtmlGenerator::m_emptySection = false [private]
Definition at line 340 of file htmlgen.h.
Referenced by endMemberSections(), startInlineHeader(), startMemberDescription(), startMemberHeader(), startMemberItem(), and startMemberSections().
m_lastFile
QCString HtmlGenerator::m_lastFile [private]
Definition at line 335 of file htmlgen.h.
Referenced by startFile().
m_lastTitle
QCString HtmlGenerator::m_lastTitle [private]
Definition at line 334 of file htmlgen.h.
Referenced by startFile(), and writeFooter().
m_relPath
QCString HtmlGenerator::m_relPath [private]
Definition at line 336 of file htmlgen.h.
Referenced by endCallGraph(), endClassDiagram(), endDirDepGraph(), endDotGraph(), endGroupCollaboration(), endInclDepGraph(), startCallGraph(), startClassDiagram(), startDirDepGraph(), startDotGraph(), startFile(), startGroupCollaboration(), startInclDepGraph(), startIndexItem(), startTextLink(), writeFooter(), writeInheritedSectionTitle(), writeLogo(), writeNavigationPath(), writeObjectLink(), writeQuickLinks(), writeSearchInfo(), writeSplitBar(), and writeSummaryLink().
m_sectionCount
int HtmlGenerator::m_sectionCount = 0 [private]
Definition at line 339 of file htmlgen.h.
Referenced by endCallGraph(), endClassDiagram(), endDirDepGraph(), endDotGraph(), endGroupCollaboration(), endInclDepGraph(), startCallGraph(), startClassDiagram(), startDirDepGraph(), startDotGraph(), startFile(), startGroupCollaboration(), and startInclDepGraph().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/htmlgen.h
doxygen/src/htmlgen.h
doxygen/build/doxygen/src/htmlgen.cpp
doxygen/src/htmlgen.cpp