TranslatorAdapter_1_8_15 Class Reference
#include <translator_adapter.h>
Public Member Functions
virtual QCString updateNeededMessage ()
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString updateNeededMessage ()
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
Additional Inherited Members
Detailed Description
Definition at line 101 of file translator_adapter.h.
Member Function Documentation
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 206 of file translator_adapter.h.
    { return english.trCompoundReferenceSlice(clName,compType,isLocal); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundReferenceSlice().
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 206 of file translator_adapter.h.
    { return english.trCompoundReferenceSlice(clName,compType,isLocal); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundReferenceSlice().
trConstantDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 137 of file translator_adapter.h.
    { return english.trConstantDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConstantDocumentation().
trConstantDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 137 of file translator_adapter.h.
    { return english.trConstantDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConstantDocumentation().
trConstants() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 134 of file translator_adapter.h.
    { return english.trConstants(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConstants().
trConstants() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 134 of file translator_adapter.h.
    { return english.trConstants(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConstants().
trCustomReference() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 131 of file translator_adapter.h.
    { return english.trCustomReference(name); }
References TranslatorAdapterBase::english, setup::name, and TranslatorEnglish::trCustomReference().
trCustomReference() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 131 of file translator_adapter.h.
    { return english.trCustomReference(name); }
References TranslatorAdapterBase::english, setup::name, and TranslatorEnglish::trCustomReference().
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 218 of file translator_adapter.h.
    { return english.trDataMemberDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDataMemberDocumentation().
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 218 of file translator_adapter.h.
    { return english.trDataMemberDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDataMemberDocumentation().
trDataMembers() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 215 of file translator_adapter.h.
    { return english.trDataMembers(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDataMembers().
trDataMembers() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 215 of file translator_adapter.h.
    { return english.trDataMembers(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDataMembers().
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trDesignUnitHierarchy () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 107 of file translator_adapter.h.
    { return english.trDesignUnitHierarchy(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnitHierarchy().
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trDesignUnitHierarchy () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 107 of file translator_adapter.h.
    { return english.trDesignUnitHierarchy(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnitHierarchy().
trDesignUnitIndex() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trDesignUnitIndex () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 119 of file translator_adapter.h.
    { return english.trDesignUnitIndex(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnitIndex().
trDesignUnitIndex() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trDesignUnitIndex () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 119 of file translator_adapter.h.
    { return english.trDesignUnitIndex(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnitIndex().
trDesignUnitList() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trDesignUnitList () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 110 of file translator_adapter.h.
    { return english.trDesignUnitList(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnitList().
trDesignUnitList() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trDesignUnitList () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 110 of file translator_adapter.h.
    { return english.trDesignUnitList(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnitList().
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trDesignUnitListDescription () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 116 of file translator_adapter.h.
    { return english.trDesignUnitListDescription(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnitListDescription().
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trDesignUnitListDescription () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 116 of file translator_adapter.h.
    { return english.trDesignUnitListDescription(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnitListDescription().
trDesignUnitMembers() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trDesignUnitMembers () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 113 of file translator_adapter.h.
    { return english.trDesignUnitMembers(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnitMembers().
trDesignUnitMembers() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trDesignUnitMembers () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 113 of file translator_adapter.h.
    { return english.trDesignUnitMembers(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnitMembers().
trDesignUnits() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trDesignUnits () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 122 of file translator_adapter.h.
    { return english.trDesignUnits(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnits().
trDesignUnits() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trDesignUnits () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 122 of file translator_adapter.h.
    { return english.trDesignUnits(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDesignUnits().
trDictionaries() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 146 of file translator_adapter.h.
    { return english.trDictionaries(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDictionaries().
trDictionaries() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 146 of file translator_adapter.h.
    { return english.trDictionaries(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDictionaries().
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 149 of file translator_adapter.h.
    { return english.trDictionaryDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDictionaryDocumentation().
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 149 of file translator_adapter.h.
    { return english.trDictionaryDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDictionaryDocumentation().
trExceptionDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 203 of file translator_adapter.h.
    { return english.trExceptionDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExceptionDocumentation().
trExceptionDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 203 of file translator_adapter.h.
    { return english.trExceptionDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExceptionDocumentation().
trExceptionHierarchy() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 197 of file translator_adapter.h.
    { return english.trExceptionHierarchy(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExceptionHierarchy().
trExceptionHierarchy() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 197 of file translator_adapter.h.
    { return english.trExceptionHierarchy(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExceptionHierarchy().
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 200 of file translator_adapter.h.
    { return english.trExceptionHierarchyDescription(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExceptionHierarchyDescription().
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 200 of file translator_adapter.h.
    { return english.trExceptionHierarchyDescription(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExceptionHierarchyDescription().
trExceptionIndex() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 188 of file translator_adapter.h.
    { return english.trExceptionIndex(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExceptionIndex().
trExceptionIndex() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 188 of file translator_adapter.h.
    { return english.trExceptionIndex(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExceptionIndex().
trExceptionList() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 191 of file translator_adapter.h.
    { return english.trExceptionList(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExceptionList().
trExceptionList() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 191 of file translator_adapter.h.
    { return english.trExceptionList(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExceptionList().
trExceptionListDescription() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 194 of file translator_adapter.h.
    { return english.trExceptionListDescription(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExceptionListDescription().
trExceptionListDescription() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 194 of file translator_adapter.h.
    { return english.trExceptionListDescription(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trExceptionListDescription().
trFunctionAndProc() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trFunctionAndProc () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 125 of file translator_adapter.h.
    { return english.trFunctionAndProc(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trFunctionAndProc().
trFunctionAndProc() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trFunctionAndProc () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 125 of file translator_adapter.h.
    { return english.trFunctionAndProc(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trFunctionAndProc().
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 170 of file translator_adapter.h.
    { return english.trInterfaceDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaceDocumentation().
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 170 of file translator_adapter.h.
    { return english.trInterfaceDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaceDocumentation().
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 164 of file translator_adapter.h.
    { return english.trInterfaceHierarchy(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaceHierarchy().
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 164 of file translator_adapter.h.
    { return english.trInterfaceHierarchy(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaceHierarchy().
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 167 of file translator_adapter.h.
    { return english.trInterfaceHierarchyDescription(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaceHierarchyDescription().
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 167 of file translator_adapter.h.
    { return english.trInterfaceHierarchyDescription(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaceHierarchyDescription().
trInterfaceIndex() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 155 of file translator_adapter.h.
    { return english.trInterfaceIndex(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaceIndex().
trInterfaceIndex() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 155 of file translator_adapter.h.
    { return english.trInterfaceIndex(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaceIndex().
trInterfaceList() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 158 of file translator_adapter.h.
    { return english.trInterfaceList(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaceList().
trInterfaceList() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 158 of file translator_adapter.h.
    { return english.trInterfaceList(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaceList().
trInterfaceListDescription() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 161 of file translator_adapter.h.
    { return english.trInterfaceListDescription(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaceListDescription().
trInterfaceListDescription() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 161 of file translator_adapter.h.
    { return english.trInterfaceListDescription(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInterfaceListDescription().
trOperationDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 212 of file translator_adapter.h.
    { return english.trOperationDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trOperationDocumentation().
trOperationDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 212 of file translator_adapter.h.
    { return english.trOperationDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trOperationDocumentation().
trOperations() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 209 of file translator_adapter.h.
    { return english.trOperations(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trOperations().
trOperations() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 209 of file translator_adapter.h.
    { return english.trOperations(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trOperations().
trSequenceDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 143 of file translator_adapter.h.
    { return english.trSequenceDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSequenceDocumentation().
trSequenceDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 143 of file translator_adapter.h.
    { return english.trSequenceDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSequenceDocumentation().
trSequences() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 140 of file translator_adapter.h.
    { return english.trSequences(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSequences().
trSequences() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 140 of file translator_adapter.h.
    { return english.trSequences(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSequences().
trSliceInterfaces() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 152 of file translator_adapter.h.
    { return english.trSliceInterfaces(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSliceInterfaces().
trSliceInterfaces() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 152 of file translator_adapter.h.
    { return english.trSliceInterfaces(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trSliceInterfaces().
trStructDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 185 of file translator_adapter.h.
    { return english.trStructDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trStructDocumentation().
trStructDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 185 of file translator_adapter.h.
    { return english.trStructDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trStructDocumentation().
trStructIndex() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 176 of file translator_adapter.h.
    { return english.trStructIndex(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trStructIndex().
trStructIndex() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 176 of file translator_adapter.h.
    { return english.trStructIndex(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trStructIndex().
trStructList() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 179 of file translator_adapter.h.
    { return english.trStructList(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trStructList().
trStructList() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 179 of file translator_adapter.h.
    { return english.trStructList(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trStructList().
trStructListDescription() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 182 of file translator_adapter.h.
    { return english.trStructListDescription(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trStructListDescription().
trStructListDescription() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 182 of file translator_adapter.h.
    { return english.trStructListDescription(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trStructListDescription().
trStructs() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 173 of file translator_adapter.h.
    { return english.trStructs(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trStructs().
trStructs() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 173 of file translator_adapter.h.
    { return english.trStructs(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trStructs().
trVhdlType() [1/2]
virtual QCString TranslatorAdapter_1_8_15::trVhdlType (uint64 type, bool single) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 128 of file translator_adapter.h.
    { return english.trVhdlType(type,single); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trVhdlType().
trVhdlType() [2/2]
virtual QCString TranslatorAdapter_1_8_15::trVhdlType (uint64 type, bool single) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorGerman, and TranslatorGerman.
Definition at line 128 of file translator_adapter.h.
    { return english.trVhdlType(type,single); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trVhdlType().
updateNeededMessage() [1/2]
virtual QCString TranslatorAdapter_1_8_15::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_8_19.
Reimplemented in TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 104 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.8.15"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
updateNeededMessage() [2/2]
virtual QCString TranslatorAdapter_1_8_15::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_8_19.
Reimplemented in TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 104 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.8.15"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_adapter.h
doxygen/src/translator_adapter.h