DotCallGraph Class Reference
#include <dotcallgraph.h>
Public Member Functions
DotCallGraph (const MemberDef *md, bool inverse)
~DotCallGraph ()
bool isTrivial () const
bool isTooBig () const
int numNodes () const
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
DotCallGraph (const MemberDef *md, bool inverse)
~DotCallGraph ()
bool isTrivial () const
bool isTooBig () const
int numNodes () const
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
Static Public Member Functions
static bool isTrivial (const MemberDef *md, bool inverse)
static bool isTrivial (const MemberDef *md, bool inverse)
Protected Member Functions
virtual QCString getBaseName () const
virtual QCString getMapLabel () const
virtual void computeTheGraph ()
virtual QCString getBaseName () const
virtual QCString getMapLabel () const
virtual void computeTheGraph ()
Private Member Functions
void buildGraph (DotNode *n, const MemberDef *md, int distance)
void determineVisibleNodes (DotNodeDeque &queue, int &maxNodes)
void determineTruncatedNodes (DotNodeDeque &queue)
void buildGraph (DotNode *n, const MemberDef *md, int distance)
void determineVisibleNodes (DotNodeDeque &queue, int &maxNodes)
void determineTruncatedNodes (DotNodeDeque &queue)
Private Attributes
DotNode * m_startNode
DotNodeMap m_usedNodes
bool m_inverse
QCString m_diskName
const Definition * m_scope
Additional Inherited Members
Detailed Description
Representation of an call graph
Definition at line 26 of file dotcallgraph.h.
Constructor & Destructor Documentation
DotCallGraph() [1/2]
DotCallGraph::DotCallGraph (const MemberDef * md, bool inverse)
Definition at line 120 of file dotcallgraph.cpp.
{
  m_inverse = inverse;
  m_diskName = md->getOutputFileBase()+"_"+md->anchor();
  m_scope = md->getOuterScope();
  QCString uniqueId = getUniqueId(md);
  QCString name;
  if (Config_getBool(HIDE_SCOPE_NAMES))
  {
    name = md->name();
  }
  else
  {
    name = md->qualifiedName();
  }
  QCString tooltip = md->briefDescriptionAsTooltip();
  m_startNode = new DotNode(getNextNodeNumber(),
    linkToText(md->getLanguage(),name,FALSE),
    tooltip,
    uniqueId,
    TRUE // root node
  );
  m_startNode->setDistance(0);
  m_usedNodes.insert(std::make_pair(uniqueId.str(),m_startNode));
  buildGraph(m_startNode,md,1);
  int maxNodes = Config_getInt(DOT_GRAPH_MAX_NODES);
  DotNodeDeque openNodeQueue;
  openNodeQueue.push_back(m_startNode);
  determineVisibleNodes(openNodeQueue,maxNodes);
  openNodeQueue.clear();
  openNodeQueue.push_back(m_startNode);
  determineTruncatedNodes(openNodeQueue);
}
References MemberDef::anchor(), Definition::briefDescriptionAsTooltip(), buildGraph(), Config_getBool, Config_getInt, determineTruncatedNodes(), determineVisibleNodes(), FALSE, Definition::getLanguage(), DotGraph::getNextNodeNumber(), Definition::getOuterScope(), MemberDef::getOutputFileBase(), getUniqueId(), linkToText(), m_diskName, m_inverse, m_scope, m_startNode, m_usedNodes, setup::name, Definition::name(), MemberDef::qualifiedName(), DotNode::setDistance(), QCString::str(), and TRUE.
 DotCallGraph() [1/2]
DotCallGraph::~DotCallGraph ()
Definition at line 155 of file dotcallgraph.cpp.
{
  DotNode::deleteNodes(m_startNode);
}
References DotNode::deleteNodes(), and m_startNode.
DotCallGraph() [2/2]
DotCallGraph::DotCallGraph (const MemberDef * md, bool inverse)
 DotCallGraph() [2/2]
DotCallGraph::~DotCallGraph ()
Member Function Documentation
buildGraph() [1/2]
void DotCallGraph::buildGraph (DotNode * n, const MemberDef * md, int distance) [private]
Definition at line 33 of file dotcallgraph.cpp.
{
  auto refs = m_inverse ? md->getReferencedByMembers() : md->getReferencesMembers();
  for (const auto &rmd : refs)
  {
    if (rmd->showInCallGraph())
    {
      QCString uniqueId = getUniqueId(rmd);
      auto it = m_usedNodes.find(uniqueId.str());
      if (it!=m_usedNodes.end()) // file is already a node in the graph
      {
        DotNode *bn = it->second;
        n->addChild(bn,0,0);
        bn->addParent(n);
        bn->setDistance(distance);
      }
      else
      {
        QCString name;
        if (Config_getBool(HIDE_SCOPE_NAMES))
        {
          name = rmd->getOuterScope()==m_scope ?
            rmd->name() : rmd->qualifiedName();
        }
        else
        {
          name = rmd->qualifiedName();
        }
        QCString tooltip = rmd->briefDescriptionAsTooltip();
        DotNode *bn = new DotNode(
            getNextNodeNumber(),
            linkToText(rmd->getLanguage(),name,FALSE),
            tooltip,
            uniqueId,
            0 //distance
            );
        n->addChild(bn,0,0);
        bn->addParent(n);
        bn->setDistance(distance);
        m_usedNodes.insert(std::make_pair(uniqueId.str(),bn));
        buildGraph(bn,rmd,distance+1);
      }
    }
  }
}
References DotNode::addParent(), buildGraph(), Config_getBool, FALSE, DotGraph::getNextNodeNumber(), Definition::getReferencedByMembers(), Definition::getReferencesMembers(), getUniqueId(), linkToText(), m_inverse, m_scope, m_usedNodes, n, setup::name, Definition::name(), DotNode::setDistance(), and QCString::str().
Referenced by buildGraph(), and DotCallGraph().
buildGraph() [2/2]
void DotCallGraph::buildGraph (DotNode * n, const MemberDef * md, int distance) [private]
computeTheGraph() [1/2]
void DotCallGraph::computeTheGraph () [protected], [virtual]
Implements DotGraph.
Definition at line 165 of file dotcallgraph.cpp.
{
  computeGraph(
    m_startNode,
    CallGraph,
    m_graphFormat,
    m_inverse ? "RL" : "LR",
    FALSE,
    m_inverse,
    m_startNode->label(),
    m_theGraph);
}
References CallGraph, DotGraph::computeGraph(), FALSE, DotNode::label(), DotGraph::m_graphFormat, m_inverse, m_startNode, and DotGraph::m_theGraph.
computeTheGraph() [2/2]
virtual void DotCallGraph::computeTheGraph () [protected], [virtual]
Implements DotGraph.
determineTruncatedNodes() [1/2]
void DotCallGraph::determineTruncatedNodes (DotNodeDeque & queue) [private]
Definition at line 99 of file dotcallgraph.cpp.
{
  while (!queue.empty())
  {
    DotNode *n = queue.front();
    queue.pop_front();
    if (n->isVisible() && n->isTruncated()==DotNode::Unknown)
    {
      bool truncated = FALSE;
      for (const auto &dn : n->children())
      {
        if (!dn->isVisible())
          truncated = TRUE;
        else
          queue.push_back(dn);
      }
      n->markAsTruncated(truncated);
    }
  }
}
References FALSE, n, TRUE, and DotNode::Unknown.
Referenced by DotCallGraph().
determineTruncatedNodes() [2/2]
void DotCallGraph::determineTruncatedNodes (DotNodeDeque & queue) [private]
determineVisibleNodes() [1/2]
void DotCallGraph::determineVisibleNodes (DotNodeDeque & queue, int & maxNodes) [private]
Definition at line 80 of file dotcallgraph.cpp.
{
  while (!queue.empty() && maxNodes>0)
  {
    DotNode *n = queue.front();
    queue.pop_front();
    if (!n->isVisible() && n->distance()<=Config_getInt(MAX_DOT_GRAPH_DEPTH)) // not yet processed
    {
      n->markAsVisible();
      maxNodes--;
      // add direct children
      for (const auto &dn : n->children())
      {
        queue.push_back(dn);
      }
    }
  }
}
References Config_getInt, and n.
Referenced by DotCallGraph().
determineVisibleNodes() [2/2]
void DotCallGraph::determineVisibleNodes (DotNodeDeque & queue, int & maxNodes) [private]
getBaseName() [1/2]
QCString DotCallGraph::getBaseName () const [protected], [virtual]
Implements DotGraph.
Definition at line 160 of file dotcallgraph.cpp.
{
  return m_diskName + (m_inverse ? "_icgraph" : "_cgraph");
}
References m_diskName, and m_inverse.
getBaseName() [2/2]
virtual QCString DotCallGraph::getBaseName () const [protected], [virtual]
Implements DotGraph.
getMapLabel() [1/2]
QCString DotCallGraph::getMapLabel () const [protected], [virtual]
Implements DotGraph.
Definition at line 178 of file dotcallgraph.cpp.
{
  return m_baseName;
}
References DotGraph::m_baseName.
getMapLabel() [2/2]
virtual QCString DotCallGraph::getMapLabel () const [protected], [virtual]
Implements DotGraph.
isTooBig() [1/2]
bool DotCallGraph::isTooBig () const
Definition at line 202 of file dotcallgraph.cpp.
{
  return numNodes()>=Config_getInt(DOT_GRAPH_MAX_NODES);
}
References Config_getInt, and numNodes().
Referenced by MemberDefImpl::_writeCallerGraph(), and MemberDefImpl::_writeCallGraph().
isTooBig() [2/2]
bool DotCallGraph::isTooBig () const
isTrivial() [1/4]
bool DotCallGraph::isTrivial () const
Definition at line 197 of file dotcallgraph.cpp.
{
  return m_startNode->children().empty();
}
References DotNode::children(), and m_startNode.
Referenced by MemberDefImpl::_hasVisibleCallerGraph(), MemberDefImpl::_hasVisibleCallGraph(), MemberDefImpl::_writeCallerGraph(), and MemberDefImpl::_writeCallGraph().
isTrivial() [2/4]
bool DotCallGraph::isTrivial () const
isTrivial() [3/4]
bool DotCallGraph::isTrivial (const MemberDef * md, bool inverse) [static]
Definition at line 212 of file dotcallgraph.cpp.
{
  auto refs = inverse ? md->getReferencedByMembers() : md->getReferencesMembers();
  for (const auto &rmd : refs)
  {
    if (rmd->showInCallGraph())
    {
      return FALSE;
    }
  }
  return TRUE;
}
References FALSE, Definition::getReferencedByMembers(), Definition::getReferencesMembers(), and TRUE.
isTrivial() [4/4]
static bool DotCallGraph::isTrivial (const MemberDef * md, bool inverse) [static]
numNodes() [1/2]
int DotCallGraph::numNodes () const
Definition at line 207 of file dotcallgraph.cpp.
{
  return static_cast<int>(m_startNode->children().size());
}
References DotNode::children(), and m_startNode.
Referenced by MemberDefImpl::_writeCallerGraph(), MemberDefImpl::_writeCallGraph(), and isTooBig().
numNodes() [2/2]
int DotCallGraph::numNodes () const
writeGraph() [1/2]
QCString DotCallGraph::writeGraph (TextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1)
Definition at line 183 of file dotcallgraph.cpp.
{
  m_doNotAddImageToIndex = textFormat!=EOF_Html;
  return DotGraph::writeGraph(out, graphFormat, textFormat, path, fileName, relPath, generateImageMap, graphId);
}
References EOF_Html, DotGraph::m_doNotAddImageToIndex, out, and DotGraph::writeGraph().
writeGraph() [2/2]
QCString DotCallGraph::writeGraph (TextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1)
Member Data Documentation
m_diskName
QCString DotCallGraph::m_diskName [private]
Definition at line 52 of file dotcallgraph.h.
Referenced by DotCallGraph(), and getBaseName().
m_inverse
bool DotCallGraph::m_inverse [private]
Definition at line 51 of file dotcallgraph.h.
Referenced by buildGraph(), computeTheGraph(), DotCallGraph(), and getBaseName().
m_scope
const Definition * DotCallGraph::m_scope [private]
Definition at line 53 of file dotcallgraph.h.
Referenced by buildGraph(), and DotCallGraph().
m_startNode
DotNode * DotCallGraph::m_startNode [private]
Definition at line 49 of file dotcallgraph.h.
Referenced by computeTheGraph(), DotCallGraph(), isTrivial(), numNodes(), and ~DotCallGraph().
m_usedNodes
DotNodeMap DotCallGraph::m_usedNodes [private]
Definition at line 50 of file dotcallgraph.h.
Referenced by buildGraph(), and DotCallGraph().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dotcallgraph.h
doxygen/src/dotcallgraph.h
doxygen/build/doxygen/src/dotcallgraph.cpp
doxygen/src/dotcallgraph.cpp