DirListContext::Private Class Reference
Public Member Functions
Private ()
Private ()
Additional Inherited Members
Detailed Description
Definition at line 6388 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
DirListContext::Private::Private () [inline]
Definition at line 6391 of file context.cpp.
    {
      for (const auto &dir : *Doxygen::dirLinkedMap)
      {
        append(DirContext::alloc(dir.get()));
      }
    }
References DirContext::alloc(), GenericNodeListContext::append(), and Doxygen::dirLinkedMap.
Private() [2/2]
DirListContext::Private::Private () [inline]
Definition at line 6391 of file context.cpp.
    {
      for (const auto &dir : *Doxygen::dirLinkedMap)
      {
        append(DirContext::alloc(dir.get()));
      }
    }
References DirContext::alloc(), and Doxygen::dirLinkedMap.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp