CodeParserInterface Class Reference
Abstract interface for code parsers.
#include <parserintf.h>
Public Member Functions
virtual ~CodeParserInterface ()=default
virtual void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXRefs=TRUE)=0
virtual void resetCodeParserState ()=0
virtual ~CodeParserInterface ()=default
virtual void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXRefs=TRUE)=0
virtual void resetCodeParserState ()=0
Detailed Description
Abstract interface for code parsers.
By implementing the methods of this interface one can add a new language parser to doxygen. This interface is used for syntax highlighting, but also to extract cross references and call graphs.
Definition at line 83 of file parserintf.h.
Constructor & Destructor Documentation
 CodeParserInterface() [1/2]
virtual CodeParserInterface::~CodeParserInterface () [virtual], [default]
 CodeParserInterface() [2/2]
virtual CodeParserInterface::~CodeParserInterface () [virtual], [default]
Member Function Documentation
parseCode() [1/2]
virtual void CodeParserInterface::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [pure virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implemented in CCodeParser, FileCodeParser, FortranCodeParser, PythonCodeParser, VHDLCodeParser, CCodeParser, FileCodeParser, FortranCodeParser, PythonCodeParser, VHDLCodeParser, LexCodeParser, SQLCodeParser, XMLCodeParser, LexCodeParser, SQLCodeParser, and XMLCodeParser.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
parseCode() [2/2]
virtual void CodeParserInterface::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [pure virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implemented in CCodeParser, FileCodeParser, FortranCodeParser, PythonCodeParser, VHDLCodeParser, CCodeParser, FileCodeParser, FortranCodeParser, PythonCodeParser, VHDLCodeParser, LexCodeParser, SQLCodeParser, XMLCodeParser, LexCodeParser, SQLCodeParser, and XMLCodeParser.
resetCodeParserState() [1/2]
virtual void CodeParserInterface::resetCodeParserState () [pure virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implemented in CCodeParser, FileCodeParser, FortranCodeParser, LexCodeParser, PythonCodeParser, SQLCodeParser, VHDLCodeParser, XMLCodeParser, CCodeParser, FileCodeParser, FortranCodeParser, LexCodeParser, PythonCodeParser, SQLCodeParser, VHDLCodeParser, and XMLCodeParser.
resetCodeParserState() [2/2]
virtual void CodeParserInterface::resetCodeParserState () [pure virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implemented in CCodeParser, FileCodeParser, FortranCodeParser, LexCodeParser, PythonCodeParser, SQLCodeParser, VHDLCodeParser, XMLCodeParser, CCodeParser, FileCodeParser, FortranCodeParser, LexCodeParser, PythonCodeParser, SQLCodeParser, VHDLCodeParser, and XMLCodeParser.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/parserintf.h
doxygen/src/parserintf.h