XMLHandlers Class Reference
Event handlers that can installed by the client and called while parsing a XML document.
#include <xml.h>
Public Types
using Attributes = std::unordered_map< std::string, std::string >
using StartDocType = void()
using EndDocType = void()
using StartElementType = void(const std::string &, const Attributes &)
using EndElementType = void(const std::string &)
using ErrorType = void(const std::string, int, const std::string &)
using CharsType = void(const std::string &)
using Attributes = std::unordered_map< std::string, std::string >
using StartDocType = void()
using EndDocType = void()
using StartElementType = void(const std::string &, const Attributes &)
using EndElementType = void(const std::string &)
using ErrorType = void(const std::string, int, const std::string &)
using CharsType = void(const std::string &)
Static Public Member Functions
static std::string value (const Attributes &attrib, const std::string &key)
static std::string value (const Attributes &attrib, const std::string &key)
Public Attributes
std::function< StartDocType > startDocument
std::function< EndDocType > endDocument
std::function< StartElementType > startElement
std::function< EndElementType > endElement
std::function< CharsType > characters
std::function< ErrorType > error
Detailed Description
Event handlers that can installed by the client and called while parsing a XML document.
Definition at line 26 of file xml.h.
Member Typedef Documentation
Attributes [1/2]
using XMLHandlers::Attributes = std::unordered_map<std::string,std::string>
Definition at line 29 of file xml.h.
Attributes [2/2]
using XMLHandlers::Attributes = std::unordered_map<std::string,std::string>
Definition at line 29 of file xml.h.
CharsType [1/2]
using XMLHandlers::CharsType = void(const std::string &)
Definition at line 35 of file xml.h.
CharsType [2/2]
using XMLHandlers::CharsType = void(const std::string &)
Definition at line 35 of file xml.h.
EndDocType [1/2]
using XMLHandlers::EndDocType = void()
Definition at line 31 of file xml.h.
EndDocType [2/2]
using XMLHandlers::EndDocType = void()
Definition at line 31 of file xml.h.
EndElementType [1/2]
using XMLHandlers::EndElementType = void(const std::string &)
Definition at line 33 of file xml.h.
EndElementType [2/2]
using XMLHandlers::EndElementType = void(const std::string &)
Definition at line 33 of file xml.h.
ErrorType [1/2]
using XMLHandlers::ErrorType = void(const std::string,int,const std::string &)
Definition at line 34 of file xml.h.
ErrorType [2/2]
using XMLHandlers::ErrorType = void(const std::string,int,const std::string &)
Definition at line 34 of file xml.h.
StartDocType [1/2]
using XMLHandlers::StartDocType = void()
Definition at line 30 of file xml.h.
StartDocType [2/2]
using XMLHandlers::StartDocType = void()
Definition at line 30 of file xml.h.
StartElementType [1/2]
using XMLHandlers::StartElementType = void(const std::string &,const Attributes &)
Definition at line 32 of file xml.h.
StartElementType [2/2]
using XMLHandlers::StartElementType = void(const std::string &,const Attributes &)
Definition at line 32 of file xml.h.
Member Function Documentation
value() [1/2]
static std::string XMLHandlers::value (const Attributes & attrib, const std::string & key) [inline], [static]
Definition at line 44 of file xml.h.
    {
      auto it = attrib.find(key);
      if (it!=attrib.end())
      {
        return it->second;
      }
      return "";
    }
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), elemIsVisible(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), anonymous_namespace{tagreader.cpp}::TagFileParser::startBase(), anonymous_namespace{tagreader.cpp}::TagFileParser::startCompound(), anonymous_namespace{tagreader.cpp}::TagFileParser::startDocAnchor(), XMLContentHandler::startElement(), anonymous_namespace{tagreader.cpp}::TagFileParser::startEnumValue(), anonymous_namespace{tagreader.cpp}::TagFileParser::startIncludes(), anonymous_namespace{tagreader.cpp}::TagFileParser::startMember(), LayoutParser::startMemberDeclEntry(), LayoutParser::startMemberDefEntry(), LayoutParser::startNavEntry(), LayoutParser::startSectionEntry(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), and doxmlparser.index.MixedContainer::to_etree_simple().
value() [2/2]
static std::string XMLHandlers::value (const Attributes & attrib, const std::string & key) [inline], [static]
Definition at line 44 of file xml.h.
    {
      auto it = attrib.find(key);
      if (it!=attrib.end())
      {
        return it->second;
      }
      return "";
    }
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), and doxmlparser.index.MixedContainer::to_etree_simple().
Member Data Documentation
characters
std::function< CharsType > XMLHandlers::characters
handler invoked when content between tags has been found
Definition at line 41 of file xml.h.
Referenced by main(), and parseTagFile().
endDocument
std::function< EndDocType > XMLHandlers::endDocument
handler invoked at the end of the document
Definition at line 38 of file xml.h.
endElement
std::function< EndElementType > XMLHandlers::endElement
handler invoked when a closing tag has been found
Definition at line 40 of file xml.h.
Referenced by LayoutDocManager::init(), main(), LayoutDocManager::parse(), and parseTagFile().
error
std::function< ErrorType > XMLHandlers::error
handler invoked when the parser encounters an error
Definition at line 42 of file xml.h.
Referenced by LayoutDocManager::init(), main(), LayoutDocManager::parse(), and parseTagFile().
startDocument
std::function< StartDocType > XMLHandlers::startDocument
handler invoked at the start of the document
Definition at line 37 of file xml.h.
Referenced by parseTagFile().
startElement
std::function< StartElementType > XMLHandlers::startElement
handler invoked when an opening tag has been found
Definition at line 39 of file xml.h.
Referenced by LayoutDocManager::init(), main(), LayoutDocManager::parse(), and parseTagFile().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/libxml/xml.h
doxygen/libxml/xml.h