VhdlString Class Reference
Minimal string class with std::string like behaviour that fulfills the JavaCC string requirements.
#include <vhdlstring.h>
Public Member Functions
VhdlString ()
VhdlString (const VhdlString &other)
VhdlString & operator= (const VhdlString &other)
VhdlString (const char *s)
VhdlString (const char *s, int size)
~VhdlString ()
VhdlString & append (const char *s, int size)
VhdlString & append (const char *s)
VhdlString & append (const VhdlString &other)
VhdlString substr (int pos=0, int len=-1)
int copy (char *s, int len, int pos=0) const
const char * c_str () const
const char * data () const
int size () const
int length () const
char & operator[] (int i)
const char & operator[] (int i) const
void clear ()
VhdlString & operator+= (char c)
VhdlString & operator+= (const char *s)
VhdlString & operator+= (VhdlString s)
VhdlString operator+ (const char *s)
VhdlString ()
VhdlString (const VhdlString &other)
VhdlString & operator= (const VhdlString &other)
VhdlString (const char *s)
VhdlString (const char *s, int size)
~VhdlString ()
VhdlString & append (const char *s, int size)
VhdlString & append (const char *s)
VhdlString & append (const VhdlString &other)
VhdlString substr (int pos=0, int len=-1)
int copy (char *s, int len, int pos=0) const
const char * c_str () const
const char * data () const
int size () const
int length () const
char & operator[] (int i)
const char & operator[] (int i) const
void clear ()
VhdlString & operator+= (char c)
VhdlString & operator+= (const char *s)
VhdlString & operator+= (VhdlString s)
VhdlString operator+ (const char *s)
Private Member Functions
void init ()
void init ()
Private Attributes
char * m_str
int m_len
Detailed Description
Minimal string class with std::string like behaviour that fulfills the JavaCC string requirements.
Definition at line 33 of file vhdlstring.h.
Constructor & Destructor Documentation
VhdlString() [1/8]
VhdlString::VhdlString () [inline]
Definition at line 36 of file vhdlstring.h.
    {
      init();
    }
References init().
Referenced by substr().
VhdlString() [2/8]
VhdlString::VhdlString (const VhdlString & other) [inline]
Definition at line 40 of file vhdlstring.h.
    {
      m_str = (char*)malloc(other.m_len+1);
      memcpy(m_str,other.m_str,other.m_len);
      m_len = other.m_len;
      m_str[m_len]=0;
    }
References m_len, and m_str.
VhdlString() [3/8]
VhdlString::VhdlString (const char * s) [inline]
Definition at line 59 of file vhdlstring.h.
    {
      m_len = (int)strlen(s);
      m_str=(char*)malloc(m_len+1);
      memcpy(m_str,s,m_len+1);
    }
References m_len, m_str, and s.
VhdlString() [4/8]
VhdlString::VhdlString (const char * s, int size) [inline]
Definition at line 65 of file vhdlstring.h.
    {
      m_str = (char*)malloc(size+1);
      memcpy(m_str,s,size);
      m_str[size]=0;
      m_len=size;
    }
References m_len, m_str, s, and size().
 VhdlString() [1/2]
VhdlString::~VhdlString () [inline]
Definition at line 72 of file vhdlstring.h.
    {
      free(m_str);
    }
References m_str.
VhdlString() [5/8]
VhdlString::VhdlString () [inline]
Definition at line 36 of file vhdlstring.h.
    {
      init();
    }
References init().
VhdlString() [6/8]
VhdlString::VhdlString (const VhdlString & other) [inline]
Definition at line 40 of file vhdlstring.h.
    {
      m_str = (char*)malloc(other.m_len+1);
      memcpy(m_str,other.m_str,other.m_len);
      m_len = other.m_len;
      m_str[m_len]=0;
    }
References m_len, and m_str.
VhdlString() [7/8]
VhdlString::VhdlString (const char * s) [inline]
Definition at line 59 of file vhdlstring.h.
    {
      m_len = (int)strlen(s);
      m_str=(char*)malloc(m_len+1);
      memcpy(m_str,s,m_len+1);
    }
References m_len, m_str, and s.
VhdlString() [8/8]
VhdlString::VhdlString (const char * s, int size) [inline]
Definition at line 65 of file vhdlstring.h.
    {
      m_str = (char*)malloc(size+1);
      memcpy(m_str,s,size);
      m_str[size]=0;
      m_len=size;
    }
References m_len, m_str, s, and size().
 VhdlString() [2/2]
VhdlString::~VhdlString () [inline]
Definition at line 72 of file vhdlstring.h.
    {
      free(m_str);
    }
References m_str.
Member Function Documentation
append() [1/6]
VhdlString & VhdlString::append (const char * s) [inline]
Definition at line 88 of file vhdlstring.h.
    {
      return append(s,(int)strlen(s));
    }
References append(), and s.
append() [2/6]
VhdlString & VhdlString::append (const char * s) [inline]
Definition at line 88 of file vhdlstring.h.
    {
      return append(s,(int)strlen(s));
    }
References append(), and s.
append() [3/6]
VhdlString & VhdlString::append (const char * s, int size) [inline]
Definition at line 76 of file vhdlstring.h.
    {
      int oldlen = m_len;
      m_len+=size+1;
      if (m_len)
      {
        m_str = (char*)realloc(m_str,m_len);
        memcpy(m_str+oldlen,s,m_len-oldlen-1);
        m_str[m_len-1]=0;
      }
      return *this;
    }
References m_len, m_str, s, and size().
Referenced by append(), operator+(), operator+(), and operator+=().
append() [4/6]
VhdlString & VhdlString::append (const char * s, int size) [inline]
Definition at line 76 of file vhdlstring.h.
    {
      int oldlen = m_len;
      m_len+=size+1;
      if (m_len)
      {
        m_str = (char*)realloc(m_str,m_len);
        memcpy(m_str+oldlen,s,m_len-oldlen-1);
        m_str[m_len-1]=0;
      }
      return *this;
    }
References m_len, m_str, s, and size().
append() [5/6]
VhdlString & VhdlString::append (const VhdlString & other) [inline]
Definition at line 92 of file vhdlstring.h.
    {
      return append(other.m_str,other.m_len);
    }
References append(), m_len, and m_str.
append() [6/6]
VhdlString & VhdlString::append (const VhdlString & other) [inline]
Definition at line 92 of file vhdlstring.h.
    {
      return append(other.m_str,other.m_len);
    }
References append(), m_len, and m_str.
c_str() [1/2]
const char * VhdlString::c_str () const [inline]
Definition at line 108 of file vhdlstring.h.
{ return m_str; }
References m_str.
c_str() [2/2]
const char * VhdlString::c_str () const [inline]
Definition at line 108 of file vhdlstring.h.
{ return m_str; }
References m_str.
clear() [1/2]
void VhdlString::clear () [inline]
Definition at line 114 of file vhdlstring.h.
{ free(m_str); init(); }
References init(), and m_str.
clear() [2/2]
void VhdlString::clear () [inline]
Definition at line 114 of file vhdlstring.h.
{ free(m_str); init(); }
References init(), and m_str.
copy() [1/2]
int VhdlString::copy (char * s, int len, int pos = 0) const [inline]
Definition at line 100 of file vhdlstring.h.
    {
      if (len==0) return 0;
      if (pos>=m_len) { s[0]=0; return 0; }
      int r=m_len<pos+len ? m_len-pos : len;
      memcpy(s,m_str+pos,r);
      return r;
    }
References len, m_len, m_str, r, and s.
copy() [2/2]
int VhdlString::copy (char * s, int len, int pos = 0) const [inline]
Definition at line 100 of file vhdlstring.h.
    {
      if (len==0) return 0;
      if (pos>=m_len) { s[0]=0; return 0; }
      int r=m_len<pos+len ? m_len-pos : len;
      memcpy(s,m_str+pos,r);
      return r;
    }
References len, m_len, m_str, r, and s.
data() [1/2]
const char * VhdlString::data () const [inline]
Definition at line 109 of file vhdlstring.h.
{ return m_str; }
References m_str.
data() [2/2]
const char * VhdlString::data () const [inline]
Definition at line 109 of file vhdlstring.h.
{ return m_str; }
References m_str.
init() [1/2]
void VhdlString::init () [inline], [private]
Definition at line 121 of file vhdlstring.h.
{ m_str=(char*)calloc(1,1); m_len=0; }
References m_len, and m_str.
Referenced by clear(), and VhdlString().
init() [2/2]
void VhdlString::init () [inline], [private]
Definition at line 121 of file vhdlstring.h.
{ m_str=(char*)calloc(1,1); m_len=0; }
References m_len, and m_str.
length() [1/2]
int VhdlString::length () const [inline]
Definition at line 111 of file vhdlstring.h.
{ return m_len; }
References m_len.
length() [2/2]
int VhdlString::length () const [inline]
Definition at line 111 of file vhdlstring.h.
{ return m_len; }
References m_len.
operator+() [1/2]
VhdlString VhdlString::operator+ (const char * s) [inline]
Definition at line 118 of file vhdlstring.h.
{ return append(s); }
References append(), and s.
operator+() [2/2]
VhdlString VhdlString::operator+ (const char * s) [inline]
Definition at line 118 of file vhdlstring.h.
{ return append(s); }
References append(), and s.
operator+=() [1/6]
VhdlString & VhdlString::operator+= (char c) [inline]
Definition at line 115 of file vhdlstring.h.
{ char s[2]; s[0]=c; s[1]=0; return append(s); }
References append(), c, and s.
operator+=() [2/6]
VhdlString & VhdlString::operator+= (char c) [inline]
Definition at line 115 of file vhdlstring.h.
{ char s[2]; s[0]=c; s[1]=0; return append(s); }
References append(), c, and s.
operator+=() [3/6]
VhdlString & VhdlString::operator+= (const char * s) [inline]
Definition at line 116 of file vhdlstring.h.
{ return append(s); }
References append(), and s.
operator+=() [4/6]
VhdlString & VhdlString::operator+= (const char * s) [inline]
Definition at line 116 of file vhdlstring.h.
{ return append(s); }
References append(), and s.
operator+=() [5/6]
VhdlString & VhdlString::operator+= (VhdlString s) [inline]
Definition at line 117 of file vhdlstring.h.
{ return append(s); }
References append(), and s.
operator+=() [6/6]
VhdlString & VhdlString::operator+= (VhdlString s) [inline]
Definition at line 117 of file vhdlstring.h.
{ return append(s); }
References append(), and s.
operator=() [1/2]
VhdlString & VhdlString::operator= (const VhdlString & other) [inline]
Definition at line 47 of file vhdlstring.h.
    {
      if (this!=&other)
      {
        free(m_str);
        m_str = (char*)malloc(other.m_len+1);
        memcpy(m_str,other.m_str,other.m_len);
        m_len = other.m_len;
        m_str[m_len]=0;
      }
      return *this;
    }
References m_len, and m_str.
operator=() [2/2]
VhdlString & VhdlString::operator= (const VhdlString & other) [inline]
Definition at line 47 of file vhdlstring.h.
    {
      if (this!=&other)
      {
        free(m_str);
        m_str = (char*)malloc(other.m_len+1);
        memcpy(m_str,other.m_str,other.m_len);
        m_len = other.m_len;
        m_str[m_len]=0;
      }
      return *this;
    }
References m_len, and m_str.
operator[]() [1/4]
char & VhdlString::operator[] (int i) [inline]
Definition at line 112 of file vhdlstring.h.
{ return m_str[i]; }
References m_str.
operator[]() [2/4]
char & VhdlString::operator[] (int i) [inline]
Definition at line 112 of file vhdlstring.h.
{ return m_str[i]; }
References m_str.
operator[]() [3/4]
const char & VhdlString::operator[] (int i) const [inline]
Definition at line 113 of file vhdlstring.h.
{ return m_str[i]; }
References m_str.
operator[]() [4/4]
const char & VhdlString::operator[] (int i) const [inline]
Definition at line 113 of file vhdlstring.h.
{ return m_str[i]; }
References m_str.
size() [1/2]
int VhdlString::size () const [inline]
Definition at line 110 of file vhdlstring.h.
{ return m_len; }
References m_len.
Referenced by append(), and VhdlString().
size() [2/2]
int VhdlString::size () const [inline]
Definition at line 110 of file vhdlstring.h.
{ return m_len; }
References m_len.
substr() [1/2]
VhdlString VhdlString::substr (int pos = 0, int len = -1) [inline]
Definition at line 96 of file vhdlstring.h.
    {
      return VhdlString(m_str?m_str+pos:0,len==-1?m_len-pos:m_len);
    }
References len, m_len, m_str, and VhdlString().
substr() [2/2]
VhdlString VhdlString::substr (int pos = 0, int len = -1) [inline]
Definition at line 96 of file vhdlstring.h.
    {
      return VhdlString(m_str?m_str+pos:0,len==-1?m_len-pos:m_len);
    }
References len, m_len, m_str, and VhdlString().
Member Data Documentation
m_len
int VhdlString::m_len [private]
Definition at line 123 of file vhdlstring.h.
Referenced by append(), copy(), init(), length(), operator=(), size(), substr(), and VhdlString().
m_str
char * VhdlString::m_str [private]
Definition at line 122 of file vhdlstring.h.
Referenced by append(), c_str(), clear(), copy(), data(), init(), operator=(), operator[](), substr(), VhdlString(), and ~VhdlString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/vhdlparser/vhdlstring.h
doxygen/vhdlparser/vhdlstring.h