ClassIndexContext::Private Class Reference
Public Member Functions
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant list () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
TemplateVariant createClasses () const
TemplateVariant list () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
TemplateVariant createClasses () const
Private Attributes
CachedItem< TemplateVariant, Private, &Private::createClasses > m_classes
Static Private Attributes
static const PropertyMap< ClassIndexContext::Private > s_inst
Detailed Description
Definition at line 5044 of file context.cpp.
Member Function Documentation
createClasses() [1/2]
TemplateVariant ClassIndexContext::Private::createClasses () const [inline], [private]
Definition at line 5065 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(Doxygen::classLinkedMap->size());
      if (Doxygen::classLinkedMap)
      {
        for (const auto &cd : *Doxygen::classLinkedMap)
        {
          if (cd->getLanguage()==SrcLangExt_VHDL &&
              (VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKAGECLASS ||
               VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKBODYCLASS)
             ) // no architecture
          {
            continue;
          }
          if (cd->isLinkableInProject() && cd->templateMaster()==0)
          {
            list.push_back(ClassContext::alloc(cd.get()));
          }
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ClassContext::alloc(), TemplateImmutableList::alloc(), Doxygen::classLinkedMap, VhdlDocGen::convert(), list(), VhdlDocGen::PACKAGECLASS, VhdlDocGen::PACKBODYCLASS, size, and SrcLangExt_VHDL.
createClasses() [2/2]
TemplateVariant ClassIndexContext::Private::createClasses () const [inline], [private]
Definition at line 5065 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(Doxygen::classLinkedMap->size());
      if (Doxygen::classLinkedMap)
      {
        for (const auto &cd : *Doxygen::classLinkedMap)
        {
          if (cd->getLanguage()==SrcLangExt_VHDL &&
              (VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKAGECLASS ||
               VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKBODYCLASS)
             ) // no architecture
          {
            continue;
          }
          if (cd->isLinkableInProject() && cd->templateMaster()==0)
          {
            list.push_back(ClassContext::alloc(cd.get()));
          }
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ClassContext::alloc(), TemplateImmutableList::alloc(), Doxygen::classLinkedMap, VhdlDocGen::convert(), VhdlDocGen::PACKAGECLASS, VhdlDocGen::PACKBODYCLASS, size, and SrcLangExt_VHDL.
fields() [1/2]
StringVector ClassIndexContext::Private::fields () const [inline]
Definition at line 5049 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector ClassIndexContext::Private::fields () const [inline]
Definition at line 5049 of file context.cpp.
{ return s_inst.fields(); }
fileName() [1/2]
TemplateVariant ClassIndexContext::Private::fileName () const [inline], [private]
Definition at line 5054 of file context.cpp.
{ return "classes"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
TemplateVariant ClassIndexContext::Private::fileName () const [inline], [private]
Definition at line 5054 of file context.cpp.
{ return "classes"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
get() [1/2]
TemplateVariant ClassIndexContext::Private::get (const QCString & n) const [inline]
Definition at line 5048 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant ClassIndexContext::Private::get (const QCString & n) const [inline]
Definition at line 5048 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
highlight() [1/2]
TemplateVariant ClassIndexContext::Private::highlight () const [inline], [private]
Definition at line 5056 of file context.cpp.
{ return "classes"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant ClassIndexContext::Private::highlight () const [inline], [private]
Definition at line 5056 of file context.cpp.
{ return "classes"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
list() [1/2]
TemplateVariant ClassIndexContext::Private::list () const [inline], [private]
Definition at line 5053 of file context.cpp.
{ return m_classes.get(this); }
References m_classes.
Referenced by createClasses().
list() [2/2]
TemplateVariant ClassIndexContext::Private::list () const [inline], [private]
Definition at line 5053 of file context.cpp.
{ return m_classes.get(this); }
relPath() [1/2]
TemplateVariant ClassIndexContext::Private::relPath () const [inline], [private]
Definition at line 5055 of file context.cpp.
{ return ""; }
relPath() [2/2]
TemplateVariant ClassIndexContext::Private::relPath () const [inline], [private]
Definition at line 5055 of file context.cpp.
{ return ""; }
subhighlight() [1/2]
TemplateVariant ClassIndexContext::Private::subhighlight () const [inline], [private]
Definition at line 5057 of file context.cpp.
{ return "classindex"; }
subhighlight() [2/2]
TemplateVariant ClassIndexContext::Private::subhighlight () const [inline], [private]
Definition at line 5057 of file context.cpp.
{ return "classindex"; }
title() [1/2]
TemplateVariant ClassIndexContext::Private::title () const [inline], [private]
Definition at line 5058 of file context.cpp.
    {
      return Config_getBool(OPTIMIZE_FOR_FORTRAN) ? theTranslator->trDataTypes() :
             Config_getBool(OPTIMIZE_OUTPUT_VHDL) ? theTranslator->trDesignUnits() :
                                                    theTranslator->trCompoundIndex();
    }
References Config_getBool, theTranslator, Translator::trCompoundIndex(), Translator::trDataTypes(), and Translator::trDesignUnits().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant ClassIndexContext::Private::title () const [inline], [private]
Definition at line 5058 of file context.cpp.
    {
      return Config_getBool(OPTIMIZE_FOR_FORTRAN) ? theTranslator->trDataTypes() :
             Config_getBool(OPTIMIZE_OUTPUT_VHDL) ? theTranslator->trDesignUnits() :
                                                    theTranslator->trCompoundIndex();
    }
References Config_getBool, theTranslator, Translator::trCompoundIndex(), Translator::trDataTypes(), and Translator::trDesignUnits().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
Member Data Documentation
m_classes
CachedItem< TemplateVariant, Private, &Private::createClasses > ClassIndexContext::Private::m_classes [private]
Definition at line 5089 of file context.cpp.
Referenced by list().
s_inst
const PropertyMap< ClassIndexContext::Private > ClassIndexContext::Private::s_inst [static], [private]
Initial value:
{
  { "list", &Private::list },
  { "fileName", &Private::fileName },
  { "relPath", &Private::relPath },
  { "highlight", &Private::highlight },
  { "subhighlight",&Private::subhighlight },
  { "title", &Private::title }
}
Definition at line 5090 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp