ColoredImage Class Reference
#include <image.h>
Public Member Functions
ColoredImage (uint width, uint height, const uchar *greyLevels, const uchar *alphaLevels, int saturation, int hue, int gamma)
~ColoredImage ()
bool save (const QCString &fileName)
ColoredImage (uint width, uint height, const uchar *greyLevels, const uchar *alphaLevels, int saturation, int hue, int gamma)
~ColoredImage ()
bool save (const QCString &fileName)
Static Public Member Functions
static void hsl2rgb (double h, double s, double l, double *pRed, double *pGreen, double *pBlue)
static void hsl2rgb (double h, double s, double l, double *pRed, double *pGreen, double *pBlue)
Private Attributes
uint m_width
uint m_height
std::vector< uchar > m_data
bool m_hasAlpha
Detailed Description
Class representing a bitmap image colored based on hue/sat/gamma settings.
Definition at line 56 of file image.h.
Constructor & Destructor Documentation
ColoredImage() [1/2]
ColoredImage::ColoredImage (uint width, uint height, const uchar * greyLevels, const uchar * alphaLevels, int saturation, int hue, int gamma)
Definition at line 430 of file image.cpp.
{
  m_hasAlpha = alphaLevels!=0;
  m_width = width;
  m_height = height;
  m_data.resize(width*height*4);
  uint i;
  for (i=0;i<width*height;i++)
  {
    Byte r,g,b,a;
    double red,green,blue;
    hsl2rgb(hue/360.0, // hue
            saturation/255.0, // saturation
            pow(greyLevels[i]/255.0,gamma/100.0), // luma (gamma corrected)
            &red,&green,&blue);
    r = static_cast<Byte>(red *255.0);
    g = static_cast<Byte>(green*255.0);
    b = static_cast<Byte>(blue *255.0);
    a = alphaLevels ? alphaLevels[i] : 255;
    m_data[i*4+0]=r;
    m_data[i*4+1]=g;
    m_data[i*4+2]=b;
    m_data[i*4+3]=a;
  }
}
References a, b, blue, g, green, hsl2rgb(), m_data, m_hasAlpha, m_height, m_width, r, and red.
 ColoredImage() [1/2]
ColoredImage::~ColoredImage ()
Definition at line 458 of file image.cpp.
{
}
ColoredImage() [2/2]
ColoredImage::ColoredImage (uint width, uint height, const uchar * greyLevels, const uchar * alphaLevels, int saturation, int hue, int gamma)
 ColoredImage() [2/2]
ColoredImage::~ColoredImage ()
Member Function Documentation
hsl2rgb() [1/2]
void ColoredImage::hsl2rgb (double h, double s, double l, double * pRed, double * pGreen, double * pBlue) [static]
Definition at line 366 of file image.cpp.
{
  double v;
  double r,g,b;
  r = l; // default to gray
  g = l;
  b = l;
  v = (l <= 0.5) ? (l * (1.0 + s)) : (l + s - l * s);
  if (v > 0)
  {
    double m;
    double sv;
    int sextant;
    double fract, vsf, mid1, mid2;
    m = l + l - v;
    sv = (v - m) / v;
    h *= 6.0;
    sextant = static_cast<int>(h);
    fract = h - sextant;
    vsf = v * sv * fract;
    mid1 = m + vsf;
    mid2 = v - vsf;
    switch (sextant)
    {
      case 0:
        r = v;
        g = mid1;
        b = m;
        break;
      case 1:
        r = mid2;
        g = v;
        b = m;
        break;
      case 2:
        r = m;
        g = v;
        b = mid1;
        break;
      case 3:
        r = m;
        g = mid2;
        b = v;
        break;
      case 4:
        r = mid1;
        g = m;
        b = v;
        break;
      case 5:
        r = v;
        g = m;
        b = mid2;
        break;
    }
  }
  *pRed = r;
  *pGreen = g;
  *pBlue = b;
}
References b, g, h, r, and s.
Referenced by ColoredImage(), getDirectoryBackgroundColor(), Image::Image(), and replaceColorMarkers().
hsl2rgb() [2/2]
static void ColoredImage::hsl2rgb (double h, double s, double l, double * pRed, double * pGreen, double * pBlue) [static]
save() [1/2]
bool ColoredImage::save (const QCString & fileName)
Definition at line 462 of file image.cpp.
{
  uchar *buffer;
  size_t bufferSize;
  LodePNG_Encoder encoder;
  LodePNG_Encoder_init(&encoder);
  encoder.infoPng.color.colorType = m_hasAlpha ? 6 : 2; // 2=RGB 24 bit, 6=RGBA 32 bit
  encoder.infoRaw.color.colorType = 6; // 6=RGBA 32 bit
  LodePNG_encode(&encoder, &buffer, &bufferSize, &m_data[0], m_width, m_height);
  LodePNG_saveFile(buffer, bufferSize, fileName.data());
  LodePNG_Encoder_cleanup(&encoder);
  free(buffer);
  return TRUE;
}
References LodePNG_InfoPng::color, LodePNG_InfoRaw::color, LodePNG_InfoColor::colorType, QCString::data(), LodePNG_Encoder::infoPng, LodePNG_Encoder::infoRaw, LodePNG_encode(), LodePNG_Encoder_cleanup(), LodePNG_Encoder_init(), LodePNG_saveFile(), m_data, m_hasAlpha, m_height, m_width, and TRUE.
Referenced by writeColoredImgData().
save() [2/2]
bool ColoredImage::save (const QCString & fileName)
Member Data Documentation
m_data
std::vector< uchar > ColoredImage::m_data [private]
Definition at line 69 of file image.h.
Referenced by ColoredImage(), and save().
m_hasAlpha
bool ColoredImage::m_hasAlpha [private]
Definition at line 70 of file image.h.
Referenced by ColoredImage(), and save().
m_height
uint ColoredImage::m_height [private]
Definition at line 68 of file image.h.
Referenced by ColoredImage(), and save().
m_width
uint ColoredImage::m_width [private]
Definition at line 67 of file image.h.
Referenced by ColoredImage(), and save().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/image.h
doxygen/src/image.h
doxygen/build/doxygen/src/image.cpp
doxygen/src/image.cpp