FileName Class Reference
#include <filename.h>
Public Member Functions
FileName (const QCString &nm, const QCString &fn)
QCString fileName () const
QCString fullName () const
QCString path () const
FileName (const QCString &nm, const QCString &fn)
QCString fileName () const
QCString fullName () const
QCString path () const
Private Attributes
QCString m_name
QCString m_fName
QCString m_pathName
Detailed Description
Class representing all files with a certain base name
Definition at line 29 of file filename.h.
Constructor & Destructor Documentation
FileName() [1/2]
FileName::FileName (const QCString & nm, const QCString & fn) [inline]
Definition at line 32 of file filename.h.
: m_name(nm), m_fName(fn), m_pathName("tmp") {}
FileName() [2/2]
FileName::FileName (const QCString & nm, const QCString & fn) [inline]
Definition at line 32 of file filename.h.
: m_name(nm), m_fName(fn), m_pathName("tmp") {}
Member Function Documentation
fileName() [1/2]
QCString FileName::fileName () const [inline]
Definition at line 33 of file filename.h.
{ return m_name; }
References m_name.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
QCString FileName::fileName () const [inline]
Definition at line 33 of file filename.h.
{ return m_name; }
References m_name.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fullName() [1/2]
QCString FileName::fullName () const [inline]
Definition at line 34 of file filename.h.
{ return m_fName; }
References m_fName.
fullName() [2/2]
QCString FileName::fullName () const [inline]
Definition at line 34 of file filename.h.
{ return m_fName; }
References m_fName.
path() [1/2]
QCString FileName::path () const [inline]
Definition at line 35 of file filename.h.
{ return m_pathName; }
References m_pathName.
path() [2/2]
QCString FileName::path () const [inline]
Definition at line 35 of file filename.h.
{ return m_pathName; }
References m_pathName.
Member Data Documentation
m_fName
QCString FileName::m_fName [private]
Definition at line 39 of file filename.h.
Referenced by fullName().
m_name
QCString FileName::m_name [private]
Definition at line 38 of file filename.h.
Referenced by fileName().
m_pathName
QCString FileName::m_pathName [private]
Definition at line 40 of file filename.h.
Referenced by path().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/filename.h
doxygen/src/filename.h