ConceptContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (const ConceptDef *cd)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant hasDetails () const
TemplateVariant includeInfo () const
TemplateVariant templateDecls () const
TemplateVariant initializer () const
TemplateVariant initializerAsCode () const
Private (const ConceptDef *cd)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant hasDetails () const
TemplateVariant includeInfo () const
TemplateVariant templateDecls () const
TemplateVariant initializer () const
TemplateVariant initializerAsCode () const
Private Member Functions
TemplateVariant createIncludeInfo () const
TemplateVariant createTemplateDecls () const
TemplateVariant createInitializer () const
TemplateVariant createInitializerAsCode () const
TemplateVariant createIncludeInfo () const
TemplateVariant createTemplateDecls () const
TemplateVariant createInitializer () const
TemplateVariant createInitializerAsCode () const
Private Attributes
const ConceptDef * m_conceptDef
Cachable m_cachable
Static Private Attributes
static const PropertyMap< ConceptContext::Private > s_inst
Additional Inherited Members
Detailed Description
Definition at line 4430 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
ConceptContext::Private::Private (const ConceptDef * cd) [inline]
Definition at line 4433 of file context.cpp.
                                  : DefinitionContext<ConceptContext::Private>(cd),
       m_conceptDef(cd)
    {
    }
Private() [2/2]
ConceptContext::Private::Private (const ConceptDef * cd) [inline]
Definition at line 4433 of file context.cpp.
                                  : DefinitionContext<ConceptContext::Private>(cd),
       m_conceptDef(cd)
    {
    }
Member Function Documentation
createIncludeInfo() [1/2]
TemplateVariant ConceptContext::Private::createIncludeInfo () const [inline], [private]
Definition at line 4453 of file context.cpp.
    {
      return m_conceptDef->includeInfo() ?
          TemplateVariant(IncludeInfoContext::alloc(m_conceptDef->includeInfo(),m_conceptDef->getLanguage())) :
          TemplateVariant(false);
    }
References IncludeInfoContext::alloc(), Definition::getLanguage(), ConceptDef::includeInfo(), and m_conceptDef.
createIncludeInfo() [2/2]
TemplateVariant ConceptContext::Private::createIncludeInfo () const [inline], [private]
Definition at line 4453 of file context.cpp.
    {
      return m_conceptDef->includeInfo() ?
          TemplateVariant(IncludeInfoContext::alloc(m_conceptDef->includeInfo(),m_conceptDef->getLanguage())) :
          TemplateVariant(false);
    }
References IncludeInfoContext::alloc().
createInitializer() [1/2]
TemplateVariant ConceptContext::Private::createInitializer () const [inline], [private]
Definition at line 4468 of file context.cpp.
    {
      return createLinkedText(m_conceptDef,relPathAsString(),m_conceptDef->initializer());
    }
References createLinkedText(), ConceptDef::initializer(), m_conceptDef, and DefinitionContext< ConceptContext::Private >::relPathAsString().
createInitializer() [2/2]
TemplateVariant ConceptContext::Private::createInitializer () const [inline], [private]
Definition at line 4468 of file context.cpp.
    {
      return createLinkedText(m_conceptDef,relPathAsString(),m_conceptDef->initializer());
    }
References createLinkedText().
createInitializerAsCode() [1/2]
TemplateVariant ConceptContext::Private::createInitializerAsCode () const [inline], [private]
Definition at line 4472 of file context.cpp.
    {
      QCString scopeName;
      if (m_conceptDef->getOuterScope()!=Doxygen::globalScope)
      {
        scopeName = m_conceptDef->getOuterScope()->name();
      }
      return parseCode(m_conceptDef,
                       scopeName,relPathAsString(),
                       m_conceptDef->initializer());
    }
References Definition::getOuterScope(), Doxygen::globalScope, ConceptDef::initializer(), m_conceptDef, Definition::name(), parseCode(), and DefinitionContext< ConceptContext::Private >::relPathAsString().
createInitializerAsCode() [2/2]
TemplateVariant ConceptContext::Private::createInitializerAsCode () const [inline], [private]
Definition at line 4472 of file context.cpp.
    {
      QCString scopeName;
      if (m_conceptDef->getOuterScope()!=Doxygen::globalScope)
      {
        scopeName = m_conceptDef->getOuterScope()->name();
      }
      return parseCode(m_conceptDef,
                       scopeName,relPathAsString(),
                       m_conceptDef->initializer());
    }
References Doxygen::globalScope, and parseCode().
createTemplateDecls() [1/2]
TemplateVariant ConceptContext::Private::createTemplateDecls () const [inline], [private]
Definition at line 4459 of file context.cpp.
    {
      TemplateVariantList list;
      if (!m_conceptDef->getTemplateParameterList().empty())
      {
        list.push_back(ArgumentListContext::alloc(m_conceptDef->getTemplateParameterList(),m_conceptDef,relPathAsString()));
      }
      return TemplateImmutableList::alloc(list);
    }
References ArgumentListContext::alloc(), TemplateImmutableList::alloc(), ArgumentList::empty(), ConceptDef::getTemplateParameterList(), m_conceptDef, and DefinitionContext< ConceptContext::Private >::relPathAsString().
createTemplateDecls() [2/2]
TemplateVariant ConceptContext::Private::createTemplateDecls () const [inline], [private]
Definition at line 4459 of file context.cpp.
    {
      TemplateVariantList list;
      if (!m_conceptDef->getTemplateParameterList().empty())
      {
        list.push_back(ArgumentListContext::alloc(m_conceptDef->getTemplateParameterList(),m_conceptDef,relPathAsString()));
      }
      return TemplateImmutableList::alloc(list);
    }
References ArgumentListContext::alloc(), and TemplateImmutableList::alloc().
fields() [1/2]
StringVector ConceptContext::Private::fields () const [inline]
Definition at line 4440 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector ConceptContext::Private::fields () const [inline]
Definition at line 4440 of file context.cpp.
{ return s_inst.fields(); }
get() [1/2]
TemplateVariant ConceptContext::Private::get (const QCString & n) const [inline]
Definition at line 4439 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant ConceptContext::Private::get (const QCString & n) const [inline]
Definition at line 4439 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
hasDetails() [1/2]
TemplateVariant ConceptContext::Private::hasDetails () const [inline]
Definition at line 4446 of file context.cpp.
{ return m_conceptDef->hasDetailedDescription(); }
References ConceptDef::hasDetailedDescription(), and m_conceptDef.
hasDetails() [2/2]
TemplateVariant ConceptContext::Private::hasDetails () const [inline]
Definition at line 4446 of file context.cpp.
{ return m_conceptDef->hasDetailedDescription(); }
highlight() [1/2]
TemplateVariant ConceptContext::Private::highlight () const [inline]
Definition at line 4444 of file context.cpp.
{ return TemplateVariant("concepts"); }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant ConceptContext::Private::highlight () const [inline]
Definition at line 4444 of file context.cpp.
{ return TemplateVariant("concepts"); }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
includeInfo() [1/2]
TemplateVariant ConceptContext::Private::includeInfo () const [inline]
Definition at line 4447 of file context.cpp.
{ return m_cachable.includeInfo.get(this); }
References ConceptContext::Private::Cachable::includeInfo, and m_cachable.
includeInfo() [2/2]
TemplateVariant ConceptContext::Private::includeInfo () const [inline]
Definition at line 4447 of file context.cpp.
{ return m_cachable.includeInfo.get(this); }
initializer() [1/2]
TemplateVariant ConceptContext::Private::initializer () const [inline]
Definition at line 4449 of file context.cpp.
{ return m_cachable.initializer.get(this); }
References ConceptContext::Private::Cachable::initializer, and m_cachable.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
initializer() [2/2]
TemplateVariant ConceptContext::Private::initializer () const [inline]
Definition at line 4449 of file context.cpp.
{ return m_cachable.initializer.get(this); }
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
initializerAsCode() [1/2]
TemplateVariant ConceptContext::Private::initializerAsCode () const [inline]
Definition at line 4450 of file context.cpp.
{ return m_cachable.initializerAsCode.get(this); }
References ConceptContext::Private::Cachable::initializerAsCode, and m_cachable.
initializerAsCode() [2/2]
TemplateVariant ConceptContext::Private::initializerAsCode () const [inline]
Definition at line 4450 of file context.cpp.
{ return m_cachable.initializerAsCode.get(this); }
subHighlight() [1/2]
TemplateVariant ConceptContext::Private::subHighlight () const [inline]
Definition at line 4445 of file context.cpp.
{ return TemplateVariant(""); }
subHighlight() [2/2]
TemplateVariant ConceptContext::Private::subHighlight () const [inline]
Definition at line 4445 of file context.cpp.
{ return TemplateVariant(""); }
templateDecls() [1/2]
TemplateVariant ConceptContext::Private::templateDecls () const [inline]
Definition at line 4448 of file context.cpp.
{ return m_cachable.templateDecls.get(this); }
References m_cachable, and ConceptContext::Private::Cachable::templateDecls.
templateDecls() [2/2]
TemplateVariant ConceptContext::Private::templateDecls () const [inline]
Definition at line 4448 of file context.cpp.
{ return m_cachable.templateDecls.get(this); }
title() [1/2]
TemplateVariant ConceptContext::Private::title () const [inline]
Definition at line 4443 of file context.cpp.
{ return TemplateVariant(m_conceptDef->title()); }
References m_conceptDef, and ConceptDef::title().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant ConceptContext::Private::title () const [inline]
Definition at line 4443 of file context.cpp.
{ return TemplateVariant(m_conceptDef->title()); }
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
Member Data Documentation
m_cachable
Cachable ConceptContext::Private::m_cachable [private]
Definition at line 4492 of file context.cpp.
Referenced by includeInfo(), initializer(), initializerAsCode(), and templateDecls().
m_conceptDef
const ConceptDef * ConceptContext::Private::m_conceptDef [private]
Definition at line 4484 of file context.cpp.
Referenced by createIncludeInfo(), createInitializer(), createInitializerAsCode(), createTemplateDecls(), hasDetails(), and title().
s_inst
const PropertyMap< ConceptContext::Private > ConceptContext::Private::s_inst [static], [private]
Initial value:
{
  BASE_PROPERTIES,
  { "title", &Private::title },
  { "highlight", &Private::highlight },
  { "subhighlight", &Private::subHighlight },
  { "hasDetails", &Private::hasDetails },
  { "includeInfo", &Private::includeInfo },
  { "templateDecls", &Private::templateDecls },
  { "initializer", &Private::initializer },
  { "initializerAsCode", &Private::initializerAsCode }
}
Definition at line 4493 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp