ExprAstFunctionVariable Class Reference
Public Member Functions
ExprAstFunctionVariable (ExprAstPtr &&var, ExprAstList &&args)
virtual TemplateVariant resolve (TemplateContext *c)
ExprAstFunctionVariable (ExprAstPtr &&var, ExprAstList &&args)
virtual TemplateVariant resolve (TemplateContext *c)
Private Attributes
ExprAstPtr m_var
ExprAstList m_args
Detailed Description
Definition at line 1705 of file template.cpp.
Constructor & Destructor Documentation
ExprAstFunctionVariable() [1/2]
ExprAstFunctionVariable::ExprAstFunctionVariable (ExprAstPtr && var, ExprAstList && args) [inline]
Definition at line 1708 of file template.cpp.
      : m_var(std::move(var)), m_args(std::move(args))
    { TRACE(("ExprAstFunctionVariable()\n"));
    }
References TRACE.
ExprAstFunctionVariable() [2/2]
ExprAstFunctionVariable::ExprAstFunctionVariable (ExprAstPtr && var, ExprAstList && args) [inline]
Definition at line 1708 of file template.cpp.
      : m_var(std::move(var)), m_args(std::move(args))
    { TRACE(("ExprAstFunctionVariable()\n"));
    }
References TRACE.
Member Function Documentation
resolve() [1/2]
virtual TemplateVariant ExprAstFunctionVariable::resolve (TemplateContext * c) [inline], [virtual]
Reimplemented from ExprAst.
Definition at line 1712 of file template.cpp.
    {
      std::vector<TemplateVariant> args;
      for (const auto &exprArg : m_args)
      {
        TemplateVariant v = exprArg->resolve(c);
        args.push_back(v);
      }
      TemplateVariant v = m_var->resolve(c);
      if (v.isFunction())
      {
        v = v.call(args);
      }
      return v;
    }
References c, TemplateVariant::call(), TemplateVariant::isFunction(), m_args, and m_var.
resolve() [2/2]
virtual TemplateVariant ExprAstFunctionVariable::resolve (TemplateContext * c) [inline], [virtual]
Reimplemented from ExprAst.
Definition at line 1712 of file template.cpp.
    {
      std::vector<TemplateVariant> args;
      for (const auto &exprArg : m_args)
      {
        TemplateVariant v = exprArg->resolve(c);
        args.push_back(v);
      }
      TemplateVariant v = m_var->resolve(c);
      if (v.isFunction())
      {
        v = v.call(args);
      }
      return v;
    }
References c, TemplateVariant::call(), and TemplateVariant::isFunction().
Member Data Documentation
m_args
ExprAstList ExprAstFunctionVariable::m_args [private]
Definition at line 1729 of file template.cpp.
Referenced by resolve().
m_var
ExprAstPtr ExprAstFunctionVariable::m_var [private]
Definition at line 1728 of file template.cpp.
Referenced by resolve().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp