SymbolIndicesContext::Private Class Reference
Public Member Functions
Private (const SearchIndexInfo &info)
Private (const SearchIndexInfo &info)
Additional Inherited Members
Detailed Description
Definition at line 8718 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
SymbolIndicesContext::Private::Private (const SearchIndexInfo & info) [inline]
Definition at line 8721 of file context.cpp.
    {
      // use info->symbolList to populate the list
      for (const auto &kv : info.symbolMap)
      {
        append(SymbolIndexContext::alloc(kv.first,kv.second,info.name));
      }
    }
References SymbolIndexContext::alloc(), GenericNodeListContext::append(), SearchIndexInfo::name, and SearchIndexInfo::symbolMap.
Private() [2/2]
SymbolIndicesContext::Private::Private (const SearchIndexInfo & info) [inline]
Definition at line 8721 of file context.cpp.
    {
      // use info->symbolList to populate the list
      for (const auto &kv : info.symbolMap)
      {
        append(SymbolIndexContext::alloc(kv.first,kv.second,info.name));
      }
    }
References SymbolIndexContext::alloc(), SearchIndexInfo::name, and SearchIndexInfo::symbolMap.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp