Wizard Class Reference
#include <wizard.h>
Public Slots
void refresh ()
void refresh ()
Signals
void done ()
void done ()
Public Member Functions
Wizard (const QHash< QString, Input * > &modelData, QWidget *parent=0)
~Wizard ()
Wizard (const QHash< QString, Input * > &modelData, QWidget *parent=0)
~Wizard ()
Private Slots
void activateTopic (QTreeWidgetItem *item, QTreeWidgetItem *)
void nextTopic ()
void prevTopic ()
void activateTopic (QTreeWidgetItem *item, QTreeWidgetItem *)
void nextTopic ()
void prevTopic ()
Private Attributes
const QHash< QString, Input * > & m_modelData
QTreeWidget * m_treeWidget = 0
QStackedWidget * m_topicStack = 0
Step1 * m_step1 = 0
Step2 * m_step2 = 0
Step3 * m_step3 = 0
Step4 * m_step4 = 0
QPushButton * m_next = 0
QPushButton * m_prev = 0
Detailed Description
Definition at line 221 of file wizard.h.
Constructor & Destructor Documentation
Wizard() [1/2]
Wizard::Wizard (const QHash< QString, Input * > & modelData, QWidget * parent = 0)
Definition at line 1319 of file wizard.cpp.
                                                                      :
  QSplitter(parent), m_modelData(modelData)
{
  m_treeWidget = new QTreeWidget;
  m_treeWidget->setColumnCount(1);
  m_treeWidget->setHeaderLabels(QStringList() << QString::fromLatin1("Topics"));
  QList<QTreeWidgetItem*> items;
  items.append(new QTreeWidgetItem((QTreeWidget*)0,QStringList(tr("Project"))));
  items.append(new QTreeWidgetItem((QTreeWidget*)0,QStringList(tr("Mode"))));
  items.append(new QTreeWidgetItem((QTreeWidget*)0,QStringList(tr("Output"))));
  items.append(new QTreeWidgetItem((QTreeWidget*)0,QStringList(tr("Diagrams"))));
  m_treeWidget->insertTopLevelItems(0,items);
  m_topicStack = new QStackedWidget;
  m_step1 = new Step1(this,modelData);
  m_step2 = new Step2(this,modelData);
  m_step3 = new Step3(this,modelData);
  m_step4 = new Step4(this,modelData);
  m_topicStack->addWidget(m_step1);
  m_topicStack->addWidget(m_step2);
  m_topicStack->addWidget(m_step3);
  m_topicStack->addWidget(m_step4);
  QWidget *rightSide = new QWidget;
  QGridLayout *grid = new QGridLayout(rightSide);
  m_prev = new QPushButton(tr("Previous"));
  m_prev->setEnabled(false);
  m_next = new QPushButton(tr("Next"));
  grid->addWidget(m_topicStack,0,0,1,2);
  grid->addWidget(m_prev,1,0,Qt::AlignLeft);
  grid->addWidget(m_next,1,1,Qt::AlignRight);
  grid->setColumnStretch(0,1);
  grid->setRowStretch(0,1);
  addWidget(m_treeWidget);
  addWidget(rightSide);
  connect(m_treeWidget,
          SIGNAL(currentItemChanged(QTreeWidgetItem *,QTreeWidgetItem *)),
          SLOT(activateTopic(QTreeWidgetItem *,QTreeWidgetItem *)));
  connect(m_next,SIGNAL(clicked()),SLOT(nextTopic()));
  connect(m_prev,SIGNAL(clicked()),SLOT(prevTopic()));
  refresh();
}
References activateTopic(), AlignLeft, AlignRight, m_next, m_prev, m_step1, m_step2, m_step3, m_step4, m_topicStack, m_treeWidget, nextTopic(), prevTopic(), and refresh().
 Wizard() [1/2]
Wizard::~Wizard ()
Definition at line 1364 of file wizard.cpp.
{
}
Wizard() [2/2]
Wizard::Wizard (const QHash< QString, Input * > & modelData, QWidget * parent = 0)
 Wizard() [2/2]
Wizard::~Wizard ()
Member Function Documentation
activateTopic [1/2]
void Wizard::activateTopic (QTreeWidgetItem * item, QTreeWidgetItem *) [private], [slot]
Definition at line 1368 of file wizard.cpp.
{
  if (item)
  {
    QString label = item->text(0);
    if (label==tr("Project"))
    {
      m_topicStack->setCurrentWidget(m_step1);
      m_prev->setEnabled(false);
      m_next->setEnabled(true);
    }
    else if (label==tr("Mode"))
    {
      m_topicStack->setCurrentWidget(m_step2);
      m_prev->setEnabled(true);
      m_next->setEnabled(true);
    }
    else if (label==tr("Output"))
    {
      m_topicStack->setCurrentWidget(m_step3);
      m_prev->setEnabled(true);
      m_next->setEnabled(true);
    }
    else if (label==tr("Diagrams"))
    {
      m_topicStack->setCurrentWidget(m_step4);
      m_prev->setEnabled(true);
      m_next->setEnabled(true);
    }
  }
}
References m_next, m_prev, m_step1, m_step2, m_step3, m_step4, and m_topicStack.
Referenced by Wizard().
activateTopic [2/2]
void Wizard::activateTopic (QTreeWidgetItem * item, QTreeWidgetItem *) [private], [slot]
done [1/2]
void Wizard::done () [signal]
Referenced by nextTopic().
done [2/2]
void Wizard::done () [signal]
nextTopic [1/2]
void Wizard::nextTopic () [private], [slot]
Definition at line 1401 of file wizard.cpp.
{
  if (m_topicStack->currentIndex()+1==m_topicStack->count()) // last topic
  {
    done();
  }
  else
  {
    m_topicStack->setCurrentIndex(m_topicStack->currentIndex()+1);
    m_next->setEnabled(m_topicStack->count()!=m_topicStack->currentIndex()+1);
    m_prev->setEnabled(m_topicStack->currentIndex()!=0);
    m_treeWidget->setCurrentItem(m_treeWidget->invisibleRootItem()->child(m_topicStack->currentIndex()));
  }
}
References done(), m_next, m_prev, m_topicStack, and m_treeWidget.
Referenced by Wizard().
nextTopic [2/2]
void Wizard::nextTopic () [private], [slot]
prevTopic [1/2]
void Wizard::prevTopic () [private], [slot]
Definition at line 1416 of file wizard.cpp.
{
  m_topicStack->setCurrentIndex(m_topicStack->currentIndex()-1);
  m_next->setEnabled(m_topicStack->count()!=m_topicStack->currentIndex()+1);
  m_prev->setEnabled(m_topicStack->currentIndex()!=0);
  m_treeWidget->setCurrentItem(m_treeWidget->invisibleRootItem()->child(m_topicStack->currentIndex()));
}
References m_next, m_prev, m_topicStack, and m_treeWidget.
Referenced by Wizard().
prevTopic [2/2]
void Wizard::prevTopic () [private], [slot]
refresh [1/2]
void Wizard::refresh () [slot]
Definition at line 1424 of file wizard.cpp.
{
  m_treeWidget->setCurrentItem(m_treeWidget->invisibleRootItem()->child(0));
  m_step1->init();
  m_step2->init();
  m_step3->init();
  m_step4->init();
}
References Step1::init(), Step2::init(), Step3::init(), Step4::init(), m_step1, m_step2, m_step3, m_step4, and m_treeWidget.
Referenced by MainWindow::loadConfigFromFile(), MainWindow::MainWindow(), MainWindow::resetToDefaults(), MainWindow::selectTab(), and Wizard().
refresh [2/2]
void Wizard::refresh () [slot]
Member Data Documentation
m_modelData
const QHash< QString, Input * > & Wizard::m_modelData [private]
Definition at line 240 of file wizard.h.
m_next
QPushButton * Wizard::m_next = 0 [private]
Definition at line 247 of file wizard.h.
Referenced by activateTopic(), nextTopic(), prevTopic(), and Wizard().
m_prev
QPushButton * Wizard::m_prev = 0 [private]
Definition at line 248 of file wizard.h.
Referenced by activateTopic(), nextTopic(), prevTopic(), and Wizard().
m_step1
Step1 * Wizard::m_step1 = 0 [private]
Definition at line 243 of file wizard.h.
Referenced by activateTopic(), refresh(), and Wizard().
m_step2
Step2 * Wizard::m_step2 = 0 [private]
Definition at line 244 of file wizard.h.
Referenced by activateTopic(), refresh(), and Wizard().
m_step3
Step3 * Wizard::m_step3 = 0 [private]
Definition at line 245 of file wizard.h.
Referenced by activateTopic(), refresh(), and Wizard().
m_step4
Step4 * Wizard::m_step4 = 0 [private]
Definition at line 246 of file wizard.h.
Referenced by activateTopic(), refresh(), and Wizard().
m_topicStack
QStackedWidget * Wizard::m_topicStack = 0 [private]
Definition at line 242 of file wizard.h.
Referenced by activateTopic(), nextTopic(), prevTopic(), and Wizard().
m_treeWidget
QTreeWidget * Wizard::m_treeWidget = 0 [private]
Definition at line 241 of file wizard.h.
Referenced by nextTopic(), prevTopic(), refresh(), and Wizard().
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/wizard.h
doxygen/build/doxygen/addon/doxywizard/wizard.h
doxygen/addon/doxywizard/wizard.cpp
doxygen/build/doxygen/addon/doxywizard/wizard.cpp