LatexCodeGenerator Class Reference
#include <latexgen.h>
Public Member Functions
LatexCodeGenerator (TextStream &t, const QCString &relPath, const QCString &sourceFile)
LatexCodeGenerator (TextStream &t)
void setRelativePath (const QCString &path)
void setSourceFileName (const QCString &sourceFileName)
void codify (const QCString &text) override
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip) override
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &) override
void writeLineNumber (const QCString &, const QCString &, const QCString &, int, bool) override
void startCodeLine (bool) override
void endCodeLine () override
void startFontClass (const QCString &) override
void endFontClass () override
void writeCodeAnchor (const QCString &) override
void startCodeFragment (const QCString &style) override
void endCodeFragment (const QCString &style) override
void incUsedTableLevel ()
void decUsedTableLevel ()
int usedTableLevel () const
LatexCodeGenerator (TextStream &t, const QCString &relPath, const QCString &sourceFile)
LatexCodeGenerator (TextStream &t)
void setRelativePath (const QCString &path)
void setSourceFileName (const QCString &sourceFileName)
void codify (const QCString &text) override
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip) override
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &) override
void writeLineNumber (const QCString &, const QCString &, const QCString &, int, bool) override
void startCodeLine (bool) override
void endCodeLine () override
void startFontClass (const QCString &) override
void endFontClass () override
void writeCodeAnchor (const QCString &) override
void startCodeFragment (const QCString &style) override
void endCodeFragment (const QCString &style) override
void incUsedTableLevel ()
void decUsedTableLevel ()
int usedTableLevel () const
Private Member Functions
void _writeCodeLink (const QCString &className, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void docify (const QCString &str)
void _writeCodeLink (const QCString &className, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void docify (const QCString &str)
Private Attributes
bool m_streamSet = false
TextStream & m_t
QCString m_relPath
QCString m_sourceFileName
int m_col = 0
bool m_doxyCodeLineOpen = false
int m_usedTableLevel = 0
Detailed Description
Definition at line 28 of file latexgen.h.
Constructor & Destructor Documentation
LatexCodeGenerator() [1/4]
LatexCodeGenerator::LatexCodeGenerator (TextStream & t, const QCString & relPath, const QCString & sourceFile)
Definition at line 51 of file latexgen.cpp.
  : m_t(t), m_relPath(relPath), m_sourceFileName(sourceFileName)
{
}
LatexCodeGenerator() [2/4]
LatexCodeGenerator::LatexCodeGenerator (TextStream & t)
Definition at line 56 of file latexgen.cpp.
                                                    : m_t(t)
{
}
LatexCodeGenerator() [3/4]
LatexCodeGenerator::LatexCodeGenerator (TextStream & t, const QCString & relPath, const QCString & sourceFile)
LatexCodeGenerator() [4/4]
LatexCodeGenerator::LatexCodeGenerator (TextStream & t)
Member Function Documentation
_writeCodeLink() [1/2]
void LatexCodeGenerator::_writeCodeLink (const QCString & className, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [private]
_writeCodeLink() [2/2]
void LatexCodeGenerator::_writeCodeLink (const QCString & className, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [private]
codify() [1/2]
void LatexCodeGenerator::codify (const QCString & s) [override], [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 70 of file latexgen.cpp.
{
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    //char cs[5];
    int spacesToNextTabStop;
    int tabSize = Config_getInt(TAB_SIZE);
    static THREAD_LOCAL char *result = NULL;
    static THREAD_LOCAL int lresult = 0;
    int i;
    while ((c=*p))
    {
      switch(c)
      {
        case 0x0c: p++; // remove ^L
                   break;
        case ' ': m_t <<" ";
                   m_col++;
                   p++;
                   break;
        case '^': m_t <<"\\string^";
                   m_col++;
                   p++;
                   break;
        case '\t': spacesToNextTabStop =
                         tabSize - (m_col%tabSize);
                   for (i = 0; i < spacesToNextTabStop; i++) m_t <<" ";
                   m_col+=spacesToNextTabStop;
                   p++;
                   break;
        case '\n': m_t << '\n';
                   m_col=0;
                   p++;
                   break;
        default:
                   i=0;
#undef COPYCHAR
// helper macro to copy a single utf8 character, dealing with multibyte chars.
#define COPYCHAR() do { \
                     int bytes = getUTF8CharNumBytes(c); \
                     if (lresult < (i + bytes + 1)) \
                     { \
                       lresult += 512; \
                       result = static_cast<char *>(realloc(result, lresult)); \
                     } \
                     for (int j=0; j<bytes && *p; j++) \
                     { \
                       result[i++]=*p++; \
                     } \
                     m_col++; \
                   } while(0)
                   // gather characters until we find whitespace or another special character
                   COPYCHAR();
                   while ((c=*p) &&
                          c!=0x0c && c!='\t' && c!='\n' && c!=' ' && c!='^'
                         )
                   {
                     COPYCHAR();
                   }
                   result[i]=0; // add terminator
                   filterLatexString(m_t,result,
                                     false, // insideTabbing
                                     true, // insidePre
                                     false, // insideItem
                                     m_usedTableLevel>0, // insideTable
                                     false // keepSpaces
                                    );
                   break;
      }
    }
  }
}
References c, Config_getInt, COPYCHAR, QCString::data(), filterLatexString(), QCString::isEmpty(), m_col, m_t, m_usedTableLevel, p, and THREAD_LOCAL.
Referenced by LatexGenerator::codify(), endCodeLine(), writeCodeLink(), and writeLineNumber().
codify() [2/2]
void LatexCodeGenerator::codify (const QCString & s) [override], [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
decUsedTableLevel() [1/2]
void LatexCodeGenerator::decUsedTableLevel () [inline]
Definition at line 58 of file latexgen.h.
{ m_usedTableLevel--; }
References m_usedTableLevel.
Referenced by LatexGenerator::endDescTable(), LatexGenerator::endMemberDocSimple(), and LatexDocVisitor::operator()().
decUsedTableLevel() [2/2]
void LatexCodeGenerator::decUsedTableLevel () [inline]
Definition at line 58 of file latexgen.h.
{ m_usedTableLevel--; }
References m_usedTableLevel.
docify() [1/2]
void LatexCodeGenerator::docify (const QCString & str) [private]
docify() [2/2]
void LatexCodeGenerator::docify (const QCString & str) [private]
endCodeFragment() [1/2]
void LatexCodeGenerator::endCodeFragment (const QCString & style) [override], [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 251 of file latexgen.cpp.
{
  //endCodeLine checks is there is still an open code line, if so closes it.
  endCodeLine();
  m_t << "\\end{" << style << "}\n";
}
References endCodeLine(), m_t, and style.
Referenced by LatexGenerator::endCodeFragment(), and LatexDocVisitor::operator()().
endCodeFragment() [2/2]
void LatexCodeGenerator::endCodeFragment (const QCString & style) [override], [virtual]
Ends a block of code
Implements CodeOutputInterface.
endCodeLine() [1/2]
void LatexCodeGenerator::endCodeLine () [override], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 226 of file latexgen.cpp.
{
  if (m_doxyCodeLineOpen)
  {
    m_t << "}";
    m_doxyCodeLineOpen = FALSE;
  }
  codify("\n");
}
References codify(), FALSE, m_doxyCodeLineOpen, and m_t.
Referenced by endCodeFragment(), and LatexGenerator::endCodeLine().
endCodeLine() [2/2]
void LatexCodeGenerator::endCodeLine () [override], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
endFontClass() [1/2]
void LatexCodeGenerator::endFontClass () [override], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 241 of file latexgen.cpp.
{
  m_t << "}";
}
References m_t.
Referenced by LatexGenerator::endFontClass().
endFontClass() [2/2]
void LatexCodeGenerator::endFontClass () [override], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
incUsedTableLevel() [1/2]
void LatexCodeGenerator::incUsedTableLevel () [inline]
Definition at line 57 of file latexgen.h.
{ m_usedTableLevel++; }
References m_usedTableLevel.
Referenced by LatexDocVisitor::operator()(), LatexGenerator::startDescTable(), and LatexGenerator::startMemberDocSimple().
incUsedTableLevel() [2/2]
void LatexCodeGenerator::incUsedTableLevel () [inline]
Definition at line 57 of file latexgen.h.
{ m_usedTableLevel++; }
References m_usedTableLevel.
setRelativePath() [1/2]
void LatexCodeGenerator::setRelativePath (const QCString & path)
Definition at line 60 of file latexgen.cpp.
{
  m_relPath = path;
}
References m_relPath.
Referenced by LatexGenerator::startFile().
setRelativePath() [2/2]
void LatexCodeGenerator::setRelativePath (const QCString & path)
setSourceFileName() [1/2]
void LatexCodeGenerator::setSourceFileName (const QCString & sourceFileName)
Definition at line 65 of file latexgen.cpp.
{
  m_sourceFileName = name;
}
References m_sourceFileName, and setup::name.
Referenced by LatexGenerator::endFile(), and LatexGenerator::startFile().
setSourceFileName() [2/2]
void LatexCodeGenerator::setSourceFileName (const QCString & sourceFileName)
startCodeFragment() [1/2]
void LatexCodeGenerator::startCodeFragment (const QCString & style) [override], [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 246 of file latexgen.cpp.
{
  m_t << "\n\\begin{" << style << "}{" << m_usedTableLevel << "}\n";
}
References m_t, m_usedTableLevel, and style.
Referenced by LatexDocVisitor::operator()(), and LatexGenerator::startCodeFragment().
startCodeFragment() [2/2]
void LatexCodeGenerator::startCodeFragment (const QCString & style) [override], [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
startCodeLine() [1/2]
void LatexCodeGenerator::startCodeLine (bool) [override], [virtual]
Implements CodeOutputInterface.
Definition at line 216 of file latexgen.cpp.
{
  m_col=0;
  if (!m_doxyCodeLineOpen)
  {
    m_t << "\\DoxyCodeLine{";
    m_doxyCodeLineOpen = TRUE;
  }
}
References m_col, m_doxyCodeLineOpen, m_t, and TRUE.
Referenced by LatexGenerator::startCodeLine().
startCodeLine() [2/2]
void LatexCodeGenerator::startCodeLine (bool) [override], [virtual]
Implements CodeOutputInterface.
startFontClass() [1/2]
void LatexCodeGenerator::startFontClass (const QCString & clsName) [override], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 236 of file latexgen.cpp.
{
  m_t << "\\textcolor{" << name << "}{";
}
References m_t, and setup::name.
Referenced by LatexGenerator::startFontClass().
startFontClass() [2/2]
void LatexCodeGenerator::startFontClass (const QCString & clsName) [override], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
usedTableLevel() [1/2]
int LatexCodeGenerator::usedTableLevel () const [inline]
Definition at line 59 of file latexgen.h.
{ return m_usedTableLevel; }
References m_usedTableLevel.
Referenced by LatexGenerator::docify(), and LatexDocVisitor::filter().
usedTableLevel() [2/2]
int LatexCodeGenerator::usedTableLevel () const [inline]
Definition at line 59 of file latexgen.h.
{ return m_usedTableLevel; }
References m_usedTableLevel.
writeCodeAnchor() [1/2]
void LatexCodeGenerator::writeCodeAnchor (const QCString & name) [inline], [override], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 52 of file latexgen.h.
{}
Referenced by LatexGenerator::writeCodeAnchor().
writeCodeAnchor() [2/2]
void LatexCodeGenerator::writeCodeAnchor (const QCString & name) [inline], [override], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 52 of file latexgen.h.
{}
writeCodeLink() [1/2]
void LatexCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [override], [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 148 of file latexgen.cpp.
{
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  bool usePDFLatex = Config_getBool(USE_PDFLATEX);
  uint l = name.length();
  if (ref.isEmpty() && usePDFLatex && pdfHyperlinks)
  {
    m_t << "\\mbox{\\hyperlink{";
    if (!f.isEmpty()) m_t << stripPath(f);
    if (!f.isEmpty() && !anchor.isEmpty()) m_t << "_";
    if (!anchor.isEmpty()) m_t << anchor;
    m_t << "}{";
    codify(name);
    m_t << "}}";
  }
  else
  {
    codify(name);
  }
  m_col+=l;
}
References codify(), Config_getBool, f, QCString::isEmpty(), m_col, m_t, setup::name, and stripPath().
Referenced by LatexGenerator::writeCodeLink(), and writeLineNumber().
writeCodeLink() [2/2]
void LatexCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [override], [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
writeLineNumber() [1/2]
void LatexCodeGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [override], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 173 of file latexgen.cpp.
{
  bool usePDFLatex = Config_getBool(USE_PDFLATEX);
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  if (!m_doxyCodeLineOpen)
  {
    m_t << "\\DoxyCodeLine{";
    m_doxyCodeLineOpen = TRUE;
  }
  if (Config_getBool(SOURCE_BROWSER))
  {
    QCString lineNumber;
    lineNumber.sprintf("%05d",l);
    QCString lineAnchor;
    if (!m_sourceFileName.isEmpty())
    {
      lineAnchor.sprintf("_l%05d",l);
      lineAnchor.prepend(stripExtensionGeneral(m_sourceFileName, ".tex"));
    }
    bool showTarget = usePDFLatex && pdfHyperlinks && !lineAnchor.isEmpty() && writeLineAnchor;
    if (showTarget)
    {
      m_t << "\\Hypertarget{" << stripPath(lineAnchor) << "}";
    }
    if (!fileName.isEmpty())
    {
      writeCodeLink(CodeSymbolType::Default,ref,fileName,anchor,lineNumber,QCString());
    }
    else
    {
      codify(lineNumber);
    }
    m_t << " ";
  }
  else
  {
    m_t << l << " ";
  }
  m_col=0;
}
References codify(), Config_getBool, Default, QCString::isEmpty(), m_col, m_doxyCodeLineOpen, m_sourceFileName, m_t, QCString::prepend(), QCString::sprintf(), stripExtensionGeneral(), stripPath(), TRUE, and writeCodeLink().
Referenced by LatexGenerator::writeLineNumber().
writeLineNumber() [2/2]
void LatexCodeGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [override], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
writeTooltip() [1/2]
void LatexCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [override], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 40 of file latexgen.h.
                                {}
Referenced by LatexGenerator::writeTooltip().
writeTooltip() [2/2]
void LatexCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [override], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 40 of file latexgen.h.
                                {}
Member Data Documentation
m_col
int LatexCodeGenerator::m_col = 0 [private]
Definition at line 71 of file latexgen.h.
Referenced by codify(), startCodeLine(), writeCodeLink(), and writeLineNumber().
m_doxyCodeLineOpen
bool LatexCodeGenerator::m_doxyCodeLineOpen = false [private]
Definition at line 72 of file latexgen.h.
Referenced by endCodeLine(), startCodeLine(), and writeLineNumber().
m_relPath
QCString LatexCodeGenerator::m_relPath [private]
Definition at line 69 of file latexgen.h.
Referenced by setRelativePath().
m_sourceFileName
QCString LatexCodeGenerator::m_sourceFileName [private]
Definition at line 70 of file latexgen.h.
Referenced by setSourceFileName(), and writeLineNumber().
m_streamSet
bool LatexCodeGenerator::m_streamSet = false [private]
Definition at line 67 of file latexgen.h.
m_t
TextStream & LatexCodeGenerator::m_t [private]
Definition at line 68 of file latexgen.h.
Referenced by codify(), endCodeFragment(), endCodeLine(), endFontClass(), startCodeFragment(), startCodeLine(), startFontClass(), writeCodeLink(), and writeLineNumber().
m_usedTableLevel
int LatexCodeGenerator::m_usedTableLevel = 0 [private]
Definition at line 73 of file latexgen.h.
Referenced by codify(), decUsedTableLevel(), incUsedTableLevel(), startCodeFragment(), and usedTableLevel().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/latexgen.h
doxygen/src/latexgen.h
doxygen/build/doxygen/src/latexgen.cpp
doxygen/src/latexgen.cpp