GlobalsIndexContext::Private Class Reference
Public Member Functions
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Types
using MemberFilter = bool(MemberDef::*)() const
using MemberFilter = bool(MemberDef::*)() const
Private Member Functions
TemplateVariant all () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant enumValues () const
TemplateVariant macros () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant related () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
TemplateVariant createMembersFiltered (MemberFilter filter) const
TemplateVariant createAll () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createTypedefs () const
TemplateVariant createEnums () const
TemplateVariant createEnumValues () const
TemplateVariant createMacros () const
TemplateVariant all () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant enumValues () const
TemplateVariant macros () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant related () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
TemplateVariant createMembersFiltered (MemberFilter filter) const
TemplateVariant createAll () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createTypedefs () const
TemplateVariant createEnums () const
TemplateVariant createEnumValues () const
TemplateVariant createMacros () const
Private Attributes
CachedItem< TemplateVariant, Private, &Private::createAll > m_all
CachedItem< TemplateVariant, Private, &Private::createFunctions > m_functions
CachedItem< TemplateVariant, Private, &Private::createVariables > m_variables
CachedItem< TemplateVariant, Private, &Private::createTypedefs > m_typedefs
CachedItem< TemplateVariant, Private, &Private::createEnums > m_enums
CachedItem< TemplateVariant, Private, &Private::createEnumValues > m_enumValues
CachedItem< TemplateVariant, Private, &Private::createMacros > m_macros
Static Private Attributes
static const PropertyMap< GlobalsIndexContext::Private > s_inst
Detailed Description
Definition at line 7075 of file context.cpp.
Member Typedef Documentation
MemberFilter [1/2]
using GlobalsIndexContext::Private::MemberFilter = bool (MemberDef::*)() const [private]
Definition at line 7101 of file context.cpp.
MemberFilter [2/2]
using GlobalsIndexContext::Private::MemberFilter = bool (MemberDef::*)() const [private]
Definition at line 7101 of file context.cpp.
Member Function Documentation
all() [1/2]
TemplateVariant GlobalsIndexContext::Private::all () const [inline], [private]
Definition at line 7084 of file context.cpp.
{ return m_all.get(this); }
References m_all.
all() [2/2]
TemplateVariant GlobalsIndexContext::Private::all () const [inline], [private]
Definition at line 7084 of file context.cpp.
{ return m_all.get(this); }
createAll() [1/2]
TemplateVariant GlobalsIndexContext::Private::createAll () const [inline], [private]
Definition at line 7122 of file context.cpp.
{ return createMembersFiltered(0); }
References createMembersFiltered().
createAll() [2/2]
TemplateVariant GlobalsIndexContext::Private::createAll () const [inline], [private]
Definition at line 7122 of file context.cpp.
{ return createMembersFiltered(0); }
createEnums() [1/2]
TemplateVariant GlobalsIndexContext::Private::createEnums () const [inline], [private]
Definition at line 7126 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumerate); }
References createMembersFiltered(), and MemberDef::isEnumerate().
createEnums() [2/2]
TemplateVariant GlobalsIndexContext::Private::createEnums () const [inline], [private]
Definition at line 7126 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumerate); }
References MemberDef::isEnumerate().
createEnumValues() [1/2]
TemplateVariant GlobalsIndexContext::Private::createEnumValues () const [inline], [private]
Definition at line 7127 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumValue); }
References createMembersFiltered(), and MemberDef::isEnumValue().
createEnumValues() [2/2]
TemplateVariant GlobalsIndexContext::Private::createEnumValues () const [inline], [private]
Definition at line 7127 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumValue); }
References MemberDef::isEnumValue().
createFunctions() [1/2]
TemplateVariant GlobalsIndexContext::Private::createFunctions () const [inline], [private]
Definition at line 7123 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isFunction); }
References createMembersFiltered(), and MemberDef::isFunction().
createFunctions() [2/2]
TemplateVariant GlobalsIndexContext::Private::createFunctions () const [inline], [private]
Definition at line 7123 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isFunction); }
References MemberDef::isFunction().
createMacros() [1/2]
TemplateVariant GlobalsIndexContext::Private::createMacros () const [inline], [private]
Definition at line 7128 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isDefine); }
References createMembersFiltered(), and MemberDef::isDefine().
createMacros() [2/2]
TemplateVariant GlobalsIndexContext::Private::createMacros () const [inline], [private]
Definition at line 7128 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isDefine); }
References MemberDef::isDefine().
createMembersFiltered() [1/2]
TemplateVariant GlobalsIndexContext::Private::createMembersFiltered (MemberFilter filter) const [inline], [private]
Definition at line 7102 of file context.cpp.
    {
      TemplateVariantList list;
      for (const auto &mn : *Doxygen::functionNameLinkedMap)
      {
        for (const auto &md : *mn)
        {
          const FileDef *fd=md->getFileDef();
          if (fd && fd->isLinkableInProject() &&
              !md->name().isEmpty() && !md->getNamespaceDef() && md->isLinkableInProject())
          {
            if (filter==0 || (md.get()->*filter)())
            {
              list.push_back(MemberContext::alloc(md.get()));
            }
          }
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), filter, Doxygen::functionNameLinkedMap, and FileDef::isLinkableInProject().
Referenced by createAll(), createEnums(), createEnumValues(), createFunctions(), createMacros(), createTypedefs(), and createVariables().
createMembersFiltered() [2/2]
TemplateVariant GlobalsIndexContext::Private::createMembersFiltered (MemberFilter filter) const [inline], [private]
Definition at line 7102 of file context.cpp.
    {
      TemplateVariantList list;
      for (const auto &mn : *Doxygen::functionNameLinkedMap)
      {
        for (const auto &md : *mn)
        {
          const FileDef *fd=md->getFileDef();
          if (fd && fd->isLinkableInProject() &&
              !md->name().isEmpty() && !md->getNamespaceDef() && md->isLinkableInProject())
          {
            if (filter==0 || (md.get()->*filter)())
            {
              list.push_back(MemberContext::alloc(md.get()));
            }
          }
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), filter, Doxygen::functionNameLinkedMap, and FileDef::isLinkableInProject().
createTypedefs() [1/2]
TemplateVariant GlobalsIndexContext::Private::createTypedefs () const [inline], [private]
Definition at line 7125 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isTypedef); }
References createMembersFiltered(), and MemberDef::isTypedef().
createTypedefs() [2/2]
TemplateVariant GlobalsIndexContext::Private::createTypedefs () const [inline], [private]
Definition at line 7125 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isTypedef); }
References MemberDef::isTypedef().
createVariables() [1/2]
TemplateVariant GlobalsIndexContext::Private::createVariables () const [inline], [private]
Definition at line 7124 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isVariable); }
References createMembersFiltered(), and MemberDef::isVariable().
createVariables() [2/2]
TemplateVariant GlobalsIndexContext::Private::createVariables () const [inline], [private]
Definition at line 7124 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isVariable); }
References MemberDef::isVariable().
enums() [1/2]
TemplateVariant GlobalsIndexContext::Private::enums () const [inline], [private]
Definition at line 7088 of file context.cpp.
{ return m_enums.get(this); }
References m_enums.
enums() [2/2]
TemplateVariant GlobalsIndexContext::Private::enums () const [inline], [private]
Definition at line 7088 of file context.cpp.
{ return m_enums.get(this); }
enumValues() [1/2]
TemplateVariant GlobalsIndexContext::Private::enumValues () const [inline], [private]
Definition at line 7089 of file context.cpp.
{ return m_enumValues.get(this); }
References m_enumValues.
enumValues() [2/2]
TemplateVariant GlobalsIndexContext::Private::enumValues () const [inline], [private]
Definition at line 7089 of file context.cpp.
{ return m_enumValues.get(this); }
events() [1/2]
TemplateVariant GlobalsIndexContext::Private::events () const [inline], [private]
Definition at line 7092 of file context.cpp.
{ return FALSE; }
References FALSE.
events() [2/2]
TemplateVariant GlobalsIndexContext::Private::events () const [inline], [private]
Definition at line 7092 of file context.cpp.
{ return FALSE; }
References FALSE.
fields() [1/2]
StringVector GlobalsIndexContext::Private::fields () const [inline]
Definition at line 7080 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector GlobalsIndexContext::Private::fields () const [inline]
Definition at line 7080 of file context.cpp.
{ return s_inst.fields(); }
fileName() [1/2]
TemplateVariant GlobalsIndexContext::Private::fileName () const [inline], [private]
Definition at line 7094 of file context.cpp.
{ return "globals"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
TemplateVariant GlobalsIndexContext::Private::fileName () const [inline], [private]
Definition at line 7094 of file context.cpp.
{ return "globals"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
functions() [1/2]
TemplateVariant GlobalsIndexContext::Private::functions () const [inline], [private]
Definition at line 7085 of file context.cpp.
{ return m_functions.get(this); }
References m_functions.
functions() [2/2]
TemplateVariant GlobalsIndexContext::Private::functions () const [inline], [private]
Definition at line 7085 of file context.cpp.
{ return m_functions.get(this); }
get() [1/2]
TemplateVariant GlobalsIndexContext::Private::get (const QCString & n) const [inline]
Definition at line 7079 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant GlobalsIndexContext::Private::get (const QCString & n) const [inline]
Definition at line 7079 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
highlight() [1/2]
TemplateVariant GlobalsIndexContext::Private::highlight () const [inline], [private]
Definition at line 7096 of file context.cpp.
{ return "files"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant GlobalsIndexContext::Private::highlight () const [inline], [private]
Definition at line 7096 of file context.cpp.
{ return "files"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
macros() [1/2]
TemplateVariant GlobalsIndexContext::Private::macros () const [inline], [private]
Definition at line 7090 of file context.cpp.
{ return m_macros.get(this); }
References m_macros.
macros() [2/2]
TemplateVariant GlobalsIndexContext::Private::macros () const [inline], [private]
Definition at line 7090 of file context.cpp.
{ return m_macros.get(this); }
properties() [1/2]
TemplateVariant GlobalsIndexContext::Private::properties () const [inline], [private]
Definition at line 7091 of file context.cpp.
{ return FALSE; }
References FALSE.
properties() [2/2]
TemplateVariant GlobalsIndexContext::Private::properties () const [inline], [private]
Definition at line 7091 of file context.cpp.
{ return FALSE; }
References FALSE.
related() [1/2]
TemplateVariant GlobalsIndexContext::Private::related () const [inline], [private]
Definition at line 7093 of file context.cpp.
{ return FALSE; }
References FALSE.
related() [2/2]
TemplateVariant GlobalsIndexContext::Private::related () const [inline], [private]
Definition at line 7093 of file context.cpp.
{ return FALSE; }
References FALSE.
relPath() [1/2]
TemplateVariant GlobalsIndexContext::Private::relPath () const [inline], [private]
Definition at line 7095 of file context.cpp.
{ return ""; }
relPath() [2/2]
TemplateVariant GlobalsIndexContext::Private::relPath () const [inline], [private]
Definition at line 7095 of file context.cpp.
{ return ""; }
subhighlight() [1/2]
TemplateVariant GlobalsIndexContext::Private::subhighlight () const [inline], [private]
Definition at line 7097 of file context.cpp.
{ return "filemembers"; }
subhighlight() [2/2]
TemplateVariant GlobalsIndexContext::Private::subhighlight () const [inline], [private]
Definition at line 7097 of file context.cpp.
{ return "filemembers"; }
title() [1/2]
TemplateVariant GlobalsIndexContext::Private::title () const [inline], [private]
Definition at line 7098 of file context.cpp.
{ return theTranslator->trFileMembers(); }
References theTranslator, and Translator::trFileMembers().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant GlobalsIndexContext::Private::title () const [inline], [private]
Definition at line 7098 of file context.cpp.
{ return theTranslator->trFileMembers(); }
References theTranslator, and Translator::trFileMembers().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
typedefs() [1/2]
TemplateVariant GlobalsIndexContext::Private::typedefs () const [inline], [private]
Definition at line 7087 of file context.cpp.
{ return m_typedefs.get(this); }
References m_typedefs.
typedefs() [2/2]
TemplateVariant GlobalsIndexContext::Private::typedefs () const [inline], [private]
Definition at line 7087 of file context.cpp.
{ return m_typedefs.get(this); }
variables() [1/2]
TemplateVariant GlobalsIndexContext::Private::variables () const [inline], [private]
Definition at line 7086 of file context.cpp.
{ return m_variables.get(this); }
References m_variables.
variables() [2/2]
TemplateVariant GlobalsIndexContext::Private::variables () const [inline], [private]
Definition at line 7086 of file context.cpp.
{ return m_variables.get(this); }
Member Data Documentation
m_all
CachedItem< TemplateVariant, Private, &Private::createAll > GlobalsIndexContext::Private::m_all [private]
Definition at line 7130 of file context.cpp.
Referenced by all().
m_enums
CachedItem< TemplateVariant, Private, &Private::createEnums > GlobalsIndexContext::Private::m_enums [private]
Definition at line 7134 of file context.cpp.
Referenced by enums().
m_enumValues
CachedItem< TemplateVariant, Private, &Private::createEnumValues > GlobalsIndexContext::Private::m_enumValues [private]
Definition at line 7135 of file context.cpp.
Referenced by enumValues().
m_functions
CachedItem< TemplateVariant, Private, &Private::createFunctions > GlobalsIndexContext::Private::m_functions [private]
Definition at line 7131 of file context.cpp.
Referenced by functions().
m_macros
CachedItem< TemplateVariant, Private, &Private::createMacros > GlobalsIndexContext::Private::m_macros [private]
Definition at line 7136 of file context.cpp.
Referenced by macros().
m_typedefs
CachedItem< TemplateVariant, Private, &Private::createTypedefs > GlobalsIndexContext::Private::m_typedefs [private]
Definition at line 7133 of file context.cpp.
Referenced by typedefs().
m_variables
CachedItem< TemplateVariant, Private, &Private::createVariables > GlobalsIndexContext::Private::m_variables [private]
Definition at line 7132 of file context.cpp.
Referenced by variables().
s_inst
const PropertyMap< GlobalsIndexContext::Private > GlobalsIndexContext::Private::s_inst [static], [private]
Initial value:
{
  { "all", &Private::all },
  { "functions", &Private::functions },
  { "variables", &Private::variables },
  { "typedefs", &Private::typedefs },
  { "enums", &Private::enums },
  { "enumValues", &Private::enumValues },
  { "macros", &Private::macros },
  { "properties", &Private::properties },
  { "events", &Private::events },
  { "related", &Private::related },
  { "fileName", &Private::fileName },
  { "relPath", &Private::relPath },
  { "highlight", &Private::highlight },
  { "subhighlight",&Private::subhighlight },
  { "title", &Private::title }
}
Definition at line 7137 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp