TranslatorNorwegian Class Reference
#include <translator_no.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
Additional Inherited Members
Detailed Description
Definition at line 46 of file translator_no.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorNorwegian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 82 of file translator_no.h.
    {
      return "0x814 Norwegian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorNorwegian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 82 of file translator_no.h.
    {
      return "0x814 Norwegian";
    }
idLanguage() [1/2]
virtual QCString TranslatorNorwegian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 58 of file translator_no.h.
    { return "norwegian"; }
idLanguage() [2/2]
virtual QCString TranslatorNorwegian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 58 of file translator_no.h.
    { return "norwegian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorNorwegian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 72 of file translator_no.h.
    {
      return
        "\\usepackage[norsk]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorNorwegian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 72 of file translator_no.h.
    {
      return
        "\\usepackage[norsk]{babel}\n";
    }
trAll() [1/2]
virtual QCString TranslatorNorwegian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1407 of file translator_no.h.
    {
      return "Alle";
    }
trAll() [2/2]
virtual QCString TranslatorNorwegian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1407 of file translator_no.h.
    {
      return "Alle";
    }
trAttention() [1/2]
virtual QCString TranslatorNorwegian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 972 of file translator_no.h.
    {
      return "Viktig";
    }
trAttention() [2/2]
virtual QCString TranslatorNorwegian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 972 of file translator_no.h.
    {
      return "Viktig";
    }
trAuthor() [1/2]
virtual QCString TranslatorNorwegian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1278 of file translator_no.h.
    {
      QCString result((first_capital ? "Forfatter" : "forfatter"));
      if (!singular) result+="e";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorNorwegian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1278 of file translator_no.h.
    {
      QCString result((first_capital ? "Forfatter" : "forfatter"));
      if (!singular) result+="e";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorNorwegian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1136 of file translator_no.h.
    {
      return "Feil";
    }
trBug() [2/2]
virtual QCString TranslatorNorwegian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1136 of file translator_no.h.
    {
      return "Feil";
    }
trBugList() [1/2]
virtual QCString TranslatorNorwegian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1141 of file translator_no.h.
    {
      return "Feil-liste";
    }
trBugList() [2/2]
virtual QCString TranslatorNorwegian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1141 of file translator_no.h.
    {
      return "Feil-liste";
    }
trCallGraph() [1/2]
virtual QCString TranslatorNorwegian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1412 of file translator_no.h.
    {
      return "Her er kall-grafen for denne funksjonen:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorNorwegian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1412 of file translator_no.h.
    {
      return "Her er kall-grafen for denne funksjonen:";
    }
trClass() [1/2]
virtual QCString TranslatorNorwegian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1199 of file translator_no.h.
    {
      QCString result((first_capital ? "Klasse" : "klasse"));
      if (!singular) result+="r";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorNorwegian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1199 of file translator_no.h.
    {
      QCString result((first_capital ? "Klasse" : "klasse"));
      if (!singular) result+="r";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorNorwegian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 524 of file translator_no.h.
    {
      return "Arvediagram for "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorNorwegian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 524 of file translator_no.h.
    {
      return "Arvediagram for "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 393 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturdokumentasjon";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klassedokumentasjon";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 393 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturdokumentasjon";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klassedokumentasjon";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorNorwegian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1099 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasser";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorNorwegian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1099 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasser";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorNorwegian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 177 of file translator_no.h.
    { return "Klassehierarki"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorNorwegian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 177 of file translator_no.h.
    { return "Klassehierarki"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorNorwegian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 236 of file translator_no.h.
    { return "Denne arvelisten er grovsortert alfabetisk "
             "(ikke ndvendigvis korrekt):";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorNorwegian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 236 of file translator_no.h.
    { return "Denne arvelisten er grovsortert alfabetisk "
             "(ikke ndvendigvis korrekt):";
    }
trCode() [1/2]
virtual QCString TranslatorNorwegian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 872 of file translator_no.h.
    {
      return "kode";
    }
trCode() [2/2]
virtual QCString TranslatorNorwegian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 872 of file translator_no.h.
    {
      return "kode";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorNorwegian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 826 of file translator_no.h.
    {
      return "Samarbeidsdiagram for "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorNorwegian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 826 of file translator_no.h.
    {
      return "Samarbeidsdiagram for "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorNorwegian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 366 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturindeks";
      }
      else
      {
        return "Klasseindeks";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorNorwegian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 366 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturindeks";
      }
      else
      {
        return "Klasseindeks";
      }
    }
References Config_getBool.
trCompoundList() [1/2]
virtual QCString TranslatorNorwegian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 181 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasseliste";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorNorwegian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 181 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasseliste";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorNorwegian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 251 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
    return "Her er datastrukturene med korte beskrivelser:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
    return "Her er klasser med korte beskrivelser:";
      }
      else
      {
    return "Her er klasser, struct'er, "
           "unioner og interface'er med korte beskrivelser:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorNorwegian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 251 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
    return "Her er datastrukturene med korte beskrivelser:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
    return "Her er klasser med korte beskrivelser:";
      }
      else
      {
    return "Her er klasser, struct'er, "
           "unioner og interface'er med korte beskrivelser:";
      }
    }
References Config_getBool.
trCompoundMembers() [1/2]
virtual QCString TranslatorNorwegian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 198 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datafelt";
      }
      else
      {
        return "Klassemedlemmer";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorNorwegian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 198 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datafelt";
      }
      else
      {
        return "Klassemedlemmer";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorNorwegian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 270 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll)
      {
        result+="dokumenterte ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct- og unionfelter";
      }
      else
      {
        result+="klassemedlemmer";
      }
      result+=" med koblinger til ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struct/union dokumentasjon for hvert felt:";
        }
        else
        {
      result+="klassedokumentasjonen for hvert medlem:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
      result+="struct'ene/unionene de hrer til:";
        }
        else
        {
      result+="klassene de hrer til:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorNorwegian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 270 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll)
      {
        result+="dokumenterte ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct- og unionfelter";
      }
      else
      {
        result+="klassemedlemmer";
      }
      result+=" med koblinger til ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struct/union dokumentasjon for hvert felt:";
        }
        else
        {
      result+="klassedokumentasjonen for hvert medlem:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
      result+="struct'ene/unionene de hrer til:";
        }
        else
        {
      result+="klassene de hrer til:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundReference() [1/2]
virtual QCString TranslatorNorwegian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 599 of file translator_no.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Klasse"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Grensesnitt"; break;
        case ClassDef::Exception: result+=" Unntak"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        default: break;
      }
      if (isTemplate) result+=" Mal";
      result+=" Referanse";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorNorwegian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 599 of file translator_no.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Klasse"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Grensesnitt"; break;
        case ClassDef::Exception: result+=" Unntak"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        default: break;
      }
      if (isTemplate) result+=" Mal";
      result+=" Referanse";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorNorwegian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 500 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasser";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorNorwegian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 500 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasser";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 837 of file translator_no.h.
    {
      return "Konstruktr- & destruktr-dokumentasjon";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 837 of file translator_no.h.
    {
      return "Konstruktr- & destruktr-dokumentasjon";
    }
trDate() [1/2]
virtual QCString TranslatorNorwegian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 538 of file translator_no.h.
    { return "Dato"; }
trDate() [2/2]
virtual QCString TranslatorNorwegian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 538 of file translator_no.h.
    { return "Dato"; }
trDayOfWeek() [1/2]
virtual QCString TranslatorNorwegian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1523 of file translator_no.h.
    {
      static const char *days_short[] = { "m.", "ty.", "on.", "to.", "fr.", "la.", "s." };
      static const char *days_full[] = { "mndag", "tysdag", "onsdag", "torsdag", "fredag", "laurdag", "sndag" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorNorwegian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1523 of file translator_no.h.
    {
      static const char *days_short[] = { "m.", "ty.", "on.", "to.", "fr.", "la.", "s." };
      static const char *days_full[] = { "mndag", "tysdag", "onsdag", "torsdag", "fredag", "laurdag", "sndag" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorNorwegian::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1539 of file translator_no.h.
    {
      static const char *dayPeriod[] = { "f.m.", "e.m." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorNorwegian::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1539 of file translator_no.h.
    {
      static const char *dayPeriod[] = { "f.m.", "e.m." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorNorwegian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 803 of file translator_no.h.
    {
      return "Definisjon p linje @0 i filen @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorNorwegian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 803 of file translator_no.h.
    {
      return "Definisjon p linje @0 i filen @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorNorwegian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 165 of file translator_no.h.
    { return "definert i"; }
trDefinedIn() [2/2]
virtual QCString TranslatorNorwegian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 165 of file translator_no.h.
    { return "definert i"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorNorwegian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 807 of file translator_no.h.
    {
      return "Definisjon i filen @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorNorwegian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 807 of file translator_no.h.
    {
      return "Definisjon i filen @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 464 of file translator_no.h.
    { return "Define-dokumentasjon"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 464 of file translator_no.h.
    { return "Define-dokumentasjon"; }
trDefines() [1/2]
virtual QCString TranslatorNorwegian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 428 of file translator_no.h.
    { return "Definisjoner"; }
trDefines() [2/2]
virtual QCString TranslatorNorwegian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 428 of file translator_no.h.
    { return "Definisjoner"; }
trDefineValue() [1/2]
virtual QCString TranslatorNorwegian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1126 of file translator_no.h.
    {
      return "Verdi:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorNorwegian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1126 of file translator_no.h.
    {
      return "Verdi:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorNorwegian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 816 of file translator_no.h.
    {
      return "Foreldet";
    }
trDeprecated() [2/2]
virtual QCString TranslatorNorwegian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 816 of file translator_no.h.
    {
      return "Foreldet";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorNorwegian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1335 of file translator_no.h.
    {
      return "Liste over foreldede enheter";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorNorwegian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1335 of file translator_no.h.
    {
      return "Liste over foreldede enheter";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorNorwegian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 98 of file translator_no.h.
    { return "Detaljert beskrivelse"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorNorwegian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 98 of file translator_no.h.
    { return "Detaljert beskrivelse"; }
trDir() [1/2]
virtual QCString TranslatorNorwegian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1502 of file translator_no.h.
    {
      QCString result((first_capital ? "Katalog" : "katalog"));
      if (!singular) result+="er";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorNorwegian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1502 of file translator_no.h.
    {
      QCString result((first_capital ? "Katalog" : "katalog"));
      if (!singular) result+="er";
      return result;
    }
trDirDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1484 of file translator_no.h.
    { return "Katalogdokumentasjon"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1484 of file translator_no.h.
    { return "Katalogdokumentasjon"; }
trDirectories() [1/2]
virtual QCString TranslatorNorwegian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1490 of file translator_no.h.
    { return "Kataloger"; }
trDirectories() [2/2]
virtual QCString TranslatorNorwegian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1490 of file translator_no.h.
    { return "Kataloger"; }
trDirIndex() [1/2]
virtual QCString TranslatorNorwegian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1478 of file translator_no.h.
    { return "Katalog hierarki"; }
trDirIndex() [2/2]
virtual QCString TranslatorNorwegian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1478 of file translator_no.h.
    { return "Katalog hierarki"; }
trDirReference() [1/2]
virtual QCString TranslatorNorwegian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1496 of file translator_no.h.
    { QCString result=dirName; result+=" Katalog referanse"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorNorwegian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1496 of file translator_no.h.
    { QCString result=dirName; result+=" Katalog referanse"; return result; }
trDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 348 of file translator_no.h.
    { return "Dokumentasjon"; }
trDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 348 of file translator_no.h.
    { return "Dokumentasjon"; }
trEnumerations() [1/2]
virtual QCString TranslatorNorwegian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 440 of file translator_no.h.
    { return "Enumerasjoner"; }
trEnumerations() [2/2]
virtual QCString TranslatorNorwegian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 440 of file translator_no.h.
    { return "Enumerasjoner"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 476 of file translator_no.h.
    { return "Enumerasjontype dokumentasjon"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 476 of file translator_no.h.
    { return "Enumerasjontype dokumentasjon"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Reimplemented from TranslatorAdapter_1_4_6.
Definition at line 482 of file translator_no.h.
    { return "Enumerasjonsverdi dokumentasjon"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Reimplemented from TranslatorAdapter_1_4_6.
Definition at line 482 of file translator_no.h.
    { return "Enumerasjonsverdi dokumentasjon"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorNorwegian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 458 of file translator_no.h.
    { return "Enumerasjonsverdier"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorNorwegian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 458 of file translator_no.h.
    { return "Enumerasjonsverdier"; }
trEnumName() [1/2]
virtual QCString TranslatorNorwegian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 157 of file translator_no.h.
    { return "enum-navn"; }
trEnumName() [2/2]
virtual QCString TranslatorNorwegian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 157 of file translator_no.h.
    { return "enum-navn"; }
trEnumValue() [1/2]
virtual QCString TranslatorNorwegian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 161 of file translator_no.h.
    { return "enum-verdi"; }
trEnumValue() [2/2]
virtual QCString TranslatorNorwegian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 161 of file translator_no.h.
    { return "enum-verdi"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1352 of file translator_no.h.
    {
      return "Hendelsesdokumentasjon";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1352 of file translator_no.h.
    {
      return "Hendelsesdokumentasjon";
    }
trEvents() [1/2]
virtual QCString TranslatorNorwegian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1347 of file translator_no.h.
    {
      return "Hendelser";
    }
trEvents() [2/2]
virtual QCString TranslatorNorwegian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1347 of file translator_no.h.
    {
      return "Hendelser";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 418 of file translator_no.h.
    { return "Eksempeldokumentasjon"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 418 of file translator_no.h.
    { return "Eksempeldokumentasjon"; }
trExamples() [1/2]
virtual QCString TranslatorNorwegian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 228 of file translator_no.h.
    { return "Eksempler"; }
trExamples() [2/2]
virtual QCString TranslatorNorwegian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 228 of file translator_no.h.
    { return "Eksempler"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorNorwegian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 333 of file translator_no.h.
    { return "Her er en liste over alle eksemplene:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorNorwegian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 333 of file translator_no.h.
    { return "Her er en liste over alle eksemplene:"; }
trExceptions() [1/2]
virtual QCString TranslatorNorwegian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 554 of file translator_no.h.
    { return "Unntak"; }
trExceptions() [2/2]
virtual QCString TranslatorNorwegian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 554 of file translator_no.h.
    { return "Unntak"; }
trFile() [1/2]
virtual QCString TranslatorNorwegian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1210 of file translator_no.h.
    {
      QCString result((first_capital ? "Fil" : "fil"));
      if (!singular) result+="er";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorNorwegian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1210 of file translator_no.h.
    {
      QCString result((first_capital ? "Fil" : "fil"));
      if (!singular) result+="er";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 412 of file translator_no.h.
    { return "Fildokumentasjon"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 412 of file translator_no.h.
    { return "Fildokumentasjon"; }
trFileIndex() [1/2]
virtual QCString TranslatorNorwegian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 381 of file translator_no.h.
    { return "Filindeks"; }
trFileIndex() [2/2]
virtual QCString TranslatorNorwegian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 381 of file translator_no.h.
    { return "Filindeks"; }
trFileList() [1/2]
virtual QCString TranslatorNorwegian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 194 of file translator_no.h.
    { return "Fil-liste"; }
trFileList() [2/2]
virtual QCString TranslatorNorwegian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 194 of file translator_no.h.
    { return "Fil-liste"; }
trFileListDescription() [1/2]
virtual QCString TranslatorNorwegian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 242 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterte ";
      result+="filer med korte beskrivelser:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorNorwegian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 242 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterte ";
      result+="filer med korte beskrivelser:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorNorwegian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 211 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globale";
      }
      else
      {
        return "Filmedlemmer";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorNorwegian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 211 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globale";
      }
      else
      {
        return "Filmedlemmer";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorNorwegian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 311 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterte ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funksjoner, variabler, definisjoner, enum'er, og typedef'er";
      }
      else
      {
        result+="filmedlemmer";
      }
      result+=" med koblinger til ";
      if (extractAll)
        result+="filene de hrer til:";
      else
        result+="dokumentasjonen:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorNorwegian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 311 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterte ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funksjoner, variabler, definisjoner, enum'er, og typedef'er";
      }
      else
      {
        result+="filmedlemmer";
      }
      result+=" med koblinger til ";
      if (extractAll)
        result+="filene de hrer til:";
      else
        result+="dokumentasjonen:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorNorwegian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 621 of file translator_no.h.
    {
      QCString result=fileName;
      result+=" filreferanse";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorNorwegian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 621 of file translator_no.h.
    {
      QCString result=fileName;
      result+=" filreferanse";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorNorwegian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 581 of file translator_no.h.
    { return "Venner"; }
trFriends() [2/2]
virtual QCString TranslatorNorwegian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 581 of file translator_no.h.
    { return "Venner"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 488 of file translator_no.h.
    { return "Funksjonsdokumentasjon"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 488 of file translator_no.h.
    { return "Funksjonsdokumentasjon"; }
trFunctions() [1/2]
virtual QCString TranslatorNorwegian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 446 of file translator_no.h.
    { return "Funksjoner"; }
trFunctions() [2/2]
virtual QCString TranslatorNorwegian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 446 of file translator_no.h.
    { return "Funksjoner"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorNorwegian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 515 of file translator_no.h.
    {
      QCString result="Generert "+date;
      if (!projName.isEmpty()) result+=" for "+projName;
      result+=" av";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorNorwegian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 515 of file translator_no.h.
    {
      QCString result="Generert "+date;
      if (!projName.isEmpty()) result+=" for "+projName;
      result+=" av";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorNorwegian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 149 of file translator_no.h.
    { QCString result="Generert automatisk av Doxygen";
      if (!s.isEmpty()) result+=" for "+s;
      result+=" fra kildekoden.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorNorwegian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 149 of file translator_no.h.
    { QCString result="Generert automatisk av Doxygen";
      if (!s.isEmpty()) result+=" for "+s;
      result+=" fra kildekoden.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorNorwegian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 558 of file translator_no.h.
    { return "Generert av"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorNorwegian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 558 of file translator_no.h.
    { return "Generert av"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorNorwegian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 759 of file translator_no.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentasjonen for ";
      switch(compType)
      {
        case ClassDef::Class: result+="denne klasse"; break;
        case ClassDef::Struct: result+="denne struct"; break;
        case ClassDef::Union: result+="denne union"; break;
        case ClassDef::Interface: result+="dette interface"; break;
        case ClassDef::Exception: result+="dette unntak"; break;
        case ClassDef::Protocol: result+="denne protocol"; break;
        case ClassDef::Category: result+="denne category"; break;
        default: break;
      }
      result+=" ble generert fra flgende fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorNorwegian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 759 of file translator_no.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentasjonen for ";
      switch(compType)
      {
        case ClassDef::Class: result+="denne klasse"; break;
        case ClassDef::Struct: result+="denne struct"; break;
        case ClassDef::Union: result+="denne union"; break;
        case ClassDef::Interface: result+="dette interface"; break;
        case ClassDef::Exception: result+="dette unntak"; break;
        case ClassDef::Protocol: result+="denne protocol"; break;
        case ClassDef::Category: result+="denne category"; break;
        default: break;
      }
      result+=" ble generert fra flgende fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorNorwegian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1265 of file translator_no.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="e";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorNorwegian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1265 of file translator_no.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="e";
      return result;
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 847 of file translator_no.h.
    {
      return "G til dokumentasjonen til denne filen.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 847 of file translator_no.h.
    {
      return "G til dokumentasjonen til denne filen.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorNorwegian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 880 of file translator_no.h.
    {
      return "G til det grafiske klasse hierarkiet";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorNorwegian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 880 of file translator_no.h.
    {
      return "G til det grafiske klasse hierarkiet";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorNorwegian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 842 of file translator_no.h.
    {
      return "G til kildekoden til denne filen.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorNorwegian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 842 of file translator_no.h.
    {
      return "G til kildekoden til denne filen.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorNorwegian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 884 of file translator_no.h.
    {
      return "G til tekst-klassehierarki";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorNorwegian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 884 of file translator_no.h.
    {
      return "G til tekst-klassehierarki";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorNorwegian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_no.h.
    {
      return "Grafisk klassehierarki";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorNorwegian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_no.h.
    {
      return "Grafisk klassehierarki";
    }
trGroup() [1/2]
virtual QCString TranslatorNorwegian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_no.h.
    {
      QCString result((first_capital ? "Gruppe" : "gruppe"));
      if (!singular) result+="r";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorNorwegian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_no.h.
    {
      QCString result((first_capital ? "Gruppe" : "gruppe"));
      if (!singular) result+="r";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorNorwegian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 360 of file translator_no.h.
    { return "Hierarkisk indeks"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorNorwegian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 360 of file translator_no.h.
    { return "Hierarkisk indeks"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorNorwegian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1303 of file translator_no.h.
    {
      return "Implementerer "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorNorwegian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1303 of file translator_no.h.
    {
      return "Implementerer "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorNorwegian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1311 of file translator_no.h.
    {
      return "Implementert i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorNorwegian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1311 of file translator_no.h.
    {
      return "Implementert i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorNorwegian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 976 of file translator_no.h.
    {
      return "Denne grafen viser hvilke filer som direkte eller "
             "indirekte inkluderer denne filen:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorNorwegian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 976 of file translator_no.h.
    {
      return "Denne grafen viser hvilke filer som direkte eller "
             "indirekte inkluderer denne filen:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorNorwegian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 831 of file translator_no.h.
    {
      return "Avhengighetsgraf for "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorNorwegian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 831 of file translator_no.h.
    {
      return "Avhengighetsgraf for "+fName+":";
    }
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorNorwegian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 143 of file translator_no.h.
    { return ", alle arvede medlemmer inkludert."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorNorwegian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 143 of file translator_no.h.
    { return ", alle arvede medlemmer inkludert."; }
trInheritedByList() [1/2]
virtual QCString TranslatorNorwegian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 693 of file translator_no.h.
    {
      return "Arvet av "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorNorwegian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 693 of file translator_no.h.
    {
      return "Arvet av "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorNorwegian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 685 of file translator_no.h.
    {
      return "Arver "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorNorwegian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 685 of file translator_no.h.
    {
      return "Arver "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorNorwegian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 867 of file translator_no.h.
    {
      return "Startverdi:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorNorwegian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 867 of file translator_no.h.
    {
      return "Startverdi:";
    }
trInterfaces() [1/2]
virtual QCString TranslatorNorwegian::trInterfaces () [inline], [virtual]
Used for Java interfaces in the summary section of Java packages
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 1094 of file translator_no.h.
    {
      return "Grensesnitt";
    }
trInterfaces() [2/2]
virtual QCString TranslatorNorwegian::trInterfaces () [inline], [virtual]
Used for Java interfaces in the summary section of Java packages
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 1094 of file translator_no.h.
    {
      return "Grensesnitt";
    }
trInvariant() [1/2]
virtual QCString TranslatorNorwegian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 862 of file translator_no.h.
    {
      return "Invariant";
    }
trInvariant() [2/2]
virtual QCString TranslatorNorwegian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 862 of file translator_no.h.
    {
      return "Invariant";
    }
trISOLang() [1/2]
virtual QCString TranslatorNorwegian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 78 of file translator_no.h.
    {
      return "nn";
    }
trISOLang() [2/2]
virtual QCString TranslatorNorwegian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 78 of file translator_no.h.
    {
      return "nn";
    }
trLegend() [1/2]
virtual QCString TranslatorNorwegian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1054 of file translator_no.h.
    {
      return "symbolforklaring";
    }
trLegend() [2/2]
virtual QCString TranslatorNorwegian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1054 of file translator_no.h.
    {
      return "symbolforklaring";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorNorwegian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 996 of file translator_no.h.
    {
      return
    "Denne siden forklarer hvordan man tolker grafene doxygen genererer.<p>\n"
    "Vi baserer oss p flgende eksempel:\n"
        "\\code\n"
        "/*! Usynlig klasse pga. trunkasjon */\n"
        "class Invisible { };\n\n"
        "/*! Trunkert klasse, arve-relasjon er skjult */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klasse som ikke er dokumentert med doxygen-kommentarer */"
        "class Undocumented { };\n\n"
        "/*! Klasse med public-arv */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasse med protected-arv */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasse med private-arv */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasse som blir brukt av klassen Inherited */\n"
        "class Used { };\n\n"
        "/*! Super-klasse som arver flere andre klasser */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Hvis \\c MAX_DOT_GRAPH_HEIGHT er satt til 200 i "
        "konfigurasjonsfila vil dette resultere i flgende graf:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Boksene i grafen over betyr flgende:\n"
        "<ul>\n"
        "<li>En fylt svart boks representerer klassen grafen "
        "er generert for.\n"
    "<li>En boks med svart ramme angir en dokumentert struct eller klasse.\n"
    "<li>En boks med gr ramme angir en udokumentert struct eller klasse.\n"
    "<li>En boks med rd ramme angir en dokumentert struct eller klasse "
    "der ikke alle relasjoner er vist. En graf blir trunkert om den ikke "
    "passer innenfor de spesifiserte rammene.\n"
    "</ul>\n"
    "Pilene i grafen har flgende betydning:\n"
    "</ul>\n"
    "<li>En mrk bl pil brukes til visualisere public-arv mellom to klasser.\n"
    "<li>En mrk grnn pil brukes for protected-arv.\n"
    "<li>En mrk rd pil angir private-arv.\n"
    "<li>En stiplet lilla pil angir at en klasse er inkludert eller brukt "
    "i en annen klasse. Pilen er merket med variablen(e) klassen "
    "er tilgjengelig gjennom.\n"
    "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorNorwegian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 996 of file translator_no.h.
    {
      return
    "Denne siden forklarer hvordan man tolker grafene doxygen genererer.<p>\n"
    "Vi baserer oss p flgende eksempel:\n"
        "\\code\n"
        "/*! Usynlig klasse pga. trunkasjon */\n"
        "class Invisible { };\n\n"
        "/*! Trunkert klasse, arve-relasjon er skjult */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klasse som ikke er dokumentert med doxygen-kommentarer */"
        "class Undocumented { };\n\n"
        "/*! Klasse med public-arv */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasse med protected-arv */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasse med private-arv */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasse som blir brukt av klassen Inherited */\n"
        "class Used { };\n\n"
        "/*! Super-klasse som arver flere andre klasser */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Hvis \\c MAX_DOT_GRAPH_HEIGHT er satt til 200 i "
        "konfigurasjonsfila vil dette resultere i flgende graf:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Boksene i grafen over betyr flgende:\n"
        "<ul>\n"
        "<li>En fylt svart boks representerer klassen grafen "
        "er generert for.\n"
    "<li>En boks med svart ramme angir en dokumentert struct eller klasse.\n"
    "<li>En boks med gr ramme angir en udokumentert struct eller klasse.\n"
    "<li>En boks med rd ramme angir en dokumentert struct eller klasse "
    "der ikke alle relasjoner er vist. En graf blir trunkert om den ikke "
    "passer innenfor de spesifiserte rammene.\n"
    "</ul>\n"
    "Pilene i grafen har flgende betydning:\n"
    "</ul>\n"
    "<li>En mrk bl pil brukes til visualisere public-arv mellom to klasser.\n"
    "<li>En mrk grnn pil brukes for protected-arv.\n"
    "<li>En mrk rd pil angir private-arv.\n"
    "<li>En stiplet lilla pil angir at en klasse er inkludert eller brukt "
    "i en annen klasse. Pilen er merket med variablen(e) klassen "
    "er tilgjengelig gjennom.\n"
    "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorNorwegian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 991 of file translator_no.h.
    {
      return "Symbolforklaring";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorNorwegian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 991 of file translator_no.h.
    {
      return "Symbolforklaring";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorNorwegian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 131 of file translator_no.h.
    { return "Liste over alle medlemmer"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorNorwegian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 131 of file translator_no.h.
    { return "Liste over alle medlemmer"; }
trMainPage() [1/2]
virtual QCString TranslatorNorwegian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 790 of file translator_no.h.
    { return "Hovedside"; }
trMainPage() [2/2]
virtual QCString TranslatorNorwegian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 790 of file translator_no.h.
    { return "Hovedside"; }
trMember() [1/2]
virtual QCString TranslatorNorwegian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1254 of file translator_no.h.
    {
      QCString result((first_capital ? "Medlem" : "medlem"));
      if (!singular) result+="mer";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorNorwegian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1254 of file translator_no.h.
    {
      QCString result((first_capital ? "Medlem" : "medlem"));
      if (!singular) result+="mer";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 114 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Feltdokumentasjon";
      }
      else
      {
        return "Medlemsdata-dokumentasjon";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 114 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Feltdokumentasjon";
      }
      else
      {
        return "Medlemsdata-dokumentasjon";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 106 of file translator_no.h.
    { return "Medlemsenumerasjon-dokumentasjon"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 106 of file translator_no.h.
    { return "Medlemsenumerasjon-dokumentasjon"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 110 of file translator_no.h.
    { return "Medlemsfunksjon-dokumentasjon"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 110 of file translator_no.h.
    { return "Medlemsfunksjon-dokumentasjon"; }
trMemberList() [1/2]
virtual QCString TranslatorNorwegian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 135 of file translator_no.h.
    { return "Medlemsliste"; }
trMemberList() [2/2]
virtual QCString TranslatorNorwegian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 135 of file translator_no.h.
    { return "Medlemsliste"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 102 of file translator_no.h.
    { return "Medlemstypedef-dokumentasjon"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 102 of file translator_no.h.
    { return "Medlemstypedef-dokumentasjon"; }
trModuleDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 387 of file translator_no.h.
    { return "Moduldokumentasjon"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 387 of file translator_no.h.
    { return "Moduldokumentasjon"; }
trModuleIndex() [1/2]
virtual QCString TranslatorNorwegian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 354 of file translator_no.h.
    { return "Modulindeks"; }
trModuleIndex() [2/2]
virtual QCString TranslatorNorwegian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 354 of file translator_no.h.
    { return "Modulindeks"; }
trModules() [1/2]
virtual QCString TranslatorNorwegian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 173 of file translator_no.h.
    { return "Moduler"; }
trModules() [2/2]
virtual QCString TranslatorNorwegian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 173 of file translator_no.h.
    { return "Moduler"; }
trModulesDescription() [1/2]
virtual QCString TranslatorNorwegian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 341 of file translator_no.h.
    { return "Her er en liste over alle moduler:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorNorwegian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 341 of file translator_no.h.
    { return "Her er en liste over alle moduler:"; }
trMonth() [1/2]
virtual QCString TranslatorNorwegian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1531 of file translator_no.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "mai", "jun", "jul", "aug", "sep", "okt", "nov", "des" };
      static const char *months_full[] = { "januar", "februar", "mars", "april", "mai", "juni", "juli", "august", "september", "oktober", "november", "desember" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorNorwegian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1531 of file translator_no.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "mai", "jun", "jul", "aug", "sep", "okt", "nov", "des" };
      static const char *months_full[] = { "januar", "februar", "mars", "april", "mai", "juni", "juli", "august", "september", "oktober", "november", "desember" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorNorwegian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 127 of file translator_no.h.
    { return "Mer..."; }
trMore() [2/2]
virtual QCString TranslatorNorwegian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 127 of file translator_no.h.
    { return "Mer..."; }
trNamespace() [1/2]
virtual QCString TranslatorNorwegian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1221 of file translator_no.h.
    {
      QCString result((first_capital ? "Navnerom" : "navnerom"));
      if (!singular) result+="";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorNorwegian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1221 of file translator_no.h.
    {
      QCString result((first_capital ? "Navnerom" : "navnerom"));
      if (!singular) result+="";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 739 of file translator_no.h.
    { return "Navneromsdokumentasjon"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 739 of file translator_no.h.
    { return "Navneromsdokumentasjon"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorNorwegian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 733 of file translator_no.h.
    { return "Navneromsindeks"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorNorwegian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 733 of file translator_no.h.
    { return "Navneromsindeks"; }
trNamespaceList() [1/2]
virtual QCString TranslatorNorwegian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 566 of file translator_no.h.
    { return "Navneromsliste"; }
trNamespaceList() [2/2]
virtual QCString TranslatorNorwegian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 566 of file translator_no.h.
    { return "Navneromsliste"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorNorwegian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 570 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterte ";
      result+="navnerom med korte beskrivelser:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorNorwegian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 570 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterte ";
      result+="navnerom med korte beskrivelser:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorNorwegian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 719 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterte ";
      result+="navneromsmedlemmer med koblinger til ";
      if (extractAll)
        result+="navneromsdokumentasjonen for hvert medlem:";
      else
        result+="navnerommet de hrer til:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorNorwegian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 719 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterte ";
      result+="navneromsmedlemmer med koblinger til ";
      if (extractAll)
        result+="navneromsdokumentasjonen for hvert medlem:";
      else
        result+="navnerommet de hrer til:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorNorwegian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 715 of file translator_no.h.
    { return "Navneromsmedlemmer"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorNorwegian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 715 of file translator_no.h.
    { return "Navneromsmedlemmer"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorNorwegian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 629 of file translator_no.h.
    {
      QCString result=namespaceName;
      result+=" navneromsreferanse";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorNorwegian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 629 of file translator_no.h.
    {
      QCString result=namespaceName;
      result+=" navneromsreferanse";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorNorwegian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 749 of file translator_no.h.
    { return "Navnerom"; }
trNamespaces() [2/2]
virtual QCString TranslatorNorwegian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 749 of file translator_no.h.
    { return "Navnerom"; }
trNote() [1/2]
virtual QCString TranslatorNorwegian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_no.h.
    {
      return "Notat";
    }
trNote() [2/2]
virtual QCString TranslatorNorwegian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_no.h.
    {
      return "Notat";
    }
trOverloadText() [1/2]
virtual QCString TranslatorNorwegian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1516 of file translator_no.h.
    {
       return "Dette er en overloaded medlemsfunksjon, "
              "generert for deg. Den skiller seg ut fra "
              "funksjonen ovenfor i argument(ene) den aksepterer.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorNorwegian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1516 of file translator_no.h.
    {
       return "Dette er en overloaded medlemsfunksjon, "
              "generert for deg. Den skiller seg ut fra "
              "funksjonen ovenfor i argument(ene) den aksepterer.";
    }
trPackage() [1/2]
virtual QCString TranslatorNorwegian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1111 of file translator_no.h.
    {
      return "Package "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorNorwegian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1111 of file translator_no.h.
    {
      return "Package "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorNorwegian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1388 of file translator_no.h.
    {
      return "Pakkeattributter";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorNorwegian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1388 of file translator_no.h.
    {
      return "Pakkeattributter";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorNorwegian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1370 of file translator_no.h.
    {
      return "Pakkefunksjoner";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorNorwegian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1370 of file translator_no.h.
    {
      return "Pakkefunksjoner";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorNorwegian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1116 of file translator_no.h.
    {
      return "Her er pakkene med korte beskrivelser (om tilgjengelig):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorNorwegian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1116 of file translator_no.h.
    {
      return "Her er pakkene med korte beskrivelser (om tilgjengelig):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorNorwegian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1374 of file translator_no.h.
    {
      return "Pakkemedlemmer";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorNorwegian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1374 of file translator_no.h.
    {
      return "Pakkemedlemmer";
    }
trPackages() [1/2]
virtual QCString TranslatorNorwegian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1121 of file translator_no.h.
    {
      return "Pakker";
    }
trPackages() [2/2]
virtual QCString TranslatorNorwegian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1121 of file translator_no.h.
    {
      return "Pakker";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorNorwegian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1363 of file translator_no.h.
    {
      return "Pakketyper";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorNorwegian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1363 of file translator_no.h.
    {
      return "Pakketyper";
    }
trPage() [1/2]
virtual QCString TranslatorNorwegian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1243 of file translator_no.h.
    {
      QCString result((first_capital ? "Side" : "side"));
      if (!singular) result+="r";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorNorwegian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1243 of file translator_no.h.
    {
      QCString result((first_capital ? "Side" : "side"));
      if (!singular) result+="r";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorNorwegian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 796 of file translator_no.h.
    { return "s."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorNorwegian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 796 of file translator_no.h.
    { return "s."; }
trPageIndex() [1/2]
virtual QCString TranslatorNorwegian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 888 of file translator_no.h.
    {
      return "Innhold";
    }
trPageIndex() [2/2]
virtual QCString TranslatorNorwegian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 888 of file translator_no.h.
    {
      return "Innhold";
    }
trParameters() [1/2]
virtual QCString TranslatorNorwegian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 550 of file translator_no.h.
    { return "Parametre"; }
trParameters() [2/2]
virtual QCString TranslatorNorwegian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 550 of file translator_no.h.
    { return "Parametre"; }
trPostcondition() [1/2]
virtual QCString TranslatorNorwegian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 857 of file translator_no.h.
    {
      return "Etterbetingelse";
    }
trPostcondition() [2/2]
virtual QCString TranslatorNorwegian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 857 of file translator_no.h.
    {
      return "Etterbetingelse";
    }
trPrecondition() [1/2]
virtual QCString TranslatorNorwegian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 852 of file translator_no.h.
    {
      return "Forhndsbetingelse";
    }
trPrecondition() [2/2]
virtual QCString TranslatorNorwegian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 852 of file translator_no.h.
    {
      return "Forhndsbetingelse";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorNorwegian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 936 of file translator_no.h.
    {
      return "Private attributter";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorNorwegian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 936 of file translator_no.h.
    {
      return "Private attributter";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorNorwegian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 650 of file translator_no.h.
    { return "Private medlemsfunksjoner"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorNorwegian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 650 of file translator_no.h.
    { return "Private medlemsfunksjoner"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorNorwegian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 652 of file translator_no.h.
    { return "Private slots"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorNorwegian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 652 of file translator_no.h.
    { return "Private slots"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorNorwegian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 932 of file translator_no.h.
    {
      return "Private typer";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorNorwegian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 932 of file translator_no.h.
    {
      return "Private typer";
    }
trProperties() [1/2]
virtual QCString TranslatorNorwegian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1079 of file translator_no.h.
    {
      return "Egenskaper";
    }
trProperties() [2/2]
virtual QCString TranslatorNorwegian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1079 of file translator_no.h.
    {
      return "Egenskaper";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1084 of file translator_no.h.
    {
      return "Egenskaps-dokumentasjon";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1084 of file translator_no.h.
    {
      return "Egenskaps-dokumentasjon";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorNorwegian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_no.h.
    {
      return "Protected attributter";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorNorwegian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_no.h.
    {
      return "Protected attributter";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorNorwegian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_no.h.
    { return "Protected memdlemsfunksjoner"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorNorwegian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_no.h.
    { return "Protected memdlemsfunksjoner"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorNorwegian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 646 of file translator_no.h.
    { return "Protected slots"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorNorwegian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 646 of file translator_no.h.
    { return "Protected slots"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorNorwegian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 920 of file translator_no.h.
    {
      return "Protected typer";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorNorwegian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 920 of file translator_no.h.
    {
      return "Protected typer";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorNorwegian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 905 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datafelt";
      }
      else
      {
        return "Public attributter";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorNorwegian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 905 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datafelt";
      }
      else
      {
        return "Public attributter";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorNorwegian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_no.h.
    { return "Public medlemsfunksjoner"; }
trPublicMembers() [2/2]
virtual QCString TranslatorNorwegian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_no.h.
    { return "Public medlemsfunksjoner"; }
trPublicSlots() [1/2]
virtual QCString TranslatorNorwegian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 638 of file translator_no.h.
    { return "Public slots"; }
trPublicSlots() [2/2]
virtual QCString TranslatorNorwegian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 638 of file translator_no.h.
    { return "Public slots"; }
trPublicTypes() [1/2]
virtual QCString TranslatorNorwegian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 901 of file translator_no.h.
    {
      return "Public typer";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorNorwegian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 901 of file translator_no.h.
    {
      return "Public typer";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorNorwegian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_no.h.
    {
      return "Referert av";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorNorwegian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_no.h.
    {
      return "Referert av";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorNorwegian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 422 of file translator_no.h.
    { return "Referansemanual"; }
trReferenceManual() [2/2]
virtual QCString TranslatorNorwegian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 422 of file translator_no.h.
    { return "Referansemanual"; }
trReferences() [1/2]
virtual QCString TranslatorNorwegian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1291 of file translator_no.h.
    {
      return "Referanser";
    }
trReferences() [2/2]
virtual QCString TranslatorNorwegian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1291 of file translator_no.h.
    {
      return "Referanser";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorNorwegian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 701 of file translator_no.h.
    {
      return "Reimplementert fra "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorNorwegian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 701 of file translator_no.h.
    {
      return "Reimplementert fra "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorNorwegian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 709 of file translator_no.h.
    {
      return "Reimplementert i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorNorwegian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 709 of file translator_no.h.
    {
      return "Reimplementert i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 591 of file translator_no.h.
    { return "Venner og relatert funksjonsdokumentasjon"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 591 of file translator_no.h.
    { return "Venner og relatert funksjonsdokumentasjon"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorNorwegian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 90 of file translator_no.h.
    { return "Relaterte funksjoner"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorNorwegian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 90 of file translator_no.h.
    { return "Relaterte funksjoner"; }
trRelatedPages() [1/2]
virtual QCString TranslatorNorwegian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 224 of file translator_no.h.
    { return "Relaterte sider"; }
trRelatedPages() [2/2]
virtual QCString TranslatorNorwegian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 224 of file translator_no.h.
    { return "Relaterte sider"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorNorwegian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 337 of file translator_no.h.
    { return "Her er en liste over alle relaterte dokumentasjonssider:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorNorwegian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 337 of file translator_no.h.
    { return "Her er en liste over alle relaterte dokumentasjonssider:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorNorwegian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 94 of file translator_no.h.
    { return "(Merk at disse ikke er medlemsfunksjoner.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorNorwegian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 94 of file translator_no.h.
    { return "(Merk at disse ikke er medlemsfunksjoner.)"; }
trRemarks() [1/2]
virtual QCString TranslatorNorwegian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 968 of file translator_no.h.
    {
      return "Merknader";
    }
trRemarks() [2/2]
virtual QCString TranslatorNorwegian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 968 of file translator_no.h.
    {
      return "Merknader";
    }
trReturns() [1/2]
virtual QCString TranslatorNorwegian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 542 of file translator_no.h.
    { return "Returnerer"; }
trReturns() [2/2]
virtual QCString TranslatorNorwegian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 542 of file translator_no.h.
    { return "Returnerer"; }
trReturnValues() [1/2]
virtual QCString TranslatorNorwegian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 785 of file translator_no.h.
    { return "Returverdier"; }
trReturnValues() [2/2]
virtual QCString TranslatorNorwegian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 785 of file translator_no.h.
    { return "Returverdier"; }
trRTFansicp() [1/2]
virtual QCString TranslatorNorwegian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1175 of file translator_no.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorNorwegian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1175 of file translator_no.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorNorwegian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1184 of file translator_no.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorNorwegian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1184 of file translator_no.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorNorwegian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1190 of file translator_no.h.
    {
      return "Indeks";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorNorwegian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1190 of file translator_no.h.
    {
      return "Indeks";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorNorwegian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1323 of file translator_no.h.
    {
      return "Innholdsfortegnelse";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorNorwegian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1323 of file translator_no.h.
    {
      return "Innholdsfortegnelse";
    }
trSearch() [1/2]
virtual QCString TranslatorNorwegian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 232 of file translator_no.h.
    { return "Sk"; }
trSearch() [2/2]
virtual QCString TranslatorNorwegian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 232 of file translator_no.h.
    { return "Sk"; }
trSearchMatches() [1/2]
virtual QCString TranslatorNorwegian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1455 of file translator_no.h.
    {
      return "Treff:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorNorwegian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1455 of file translator_no.h.
    {
      return "Treff:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorNorwegian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1436 of file translator_no.h.
    {
      if (numDocuments==0)
      {
        return "Beklager, men ingen dokumenter ble funnet.";
      }
      else if (numDocuments==1)
      {
        return "Fant <b>ett</b> dokument som passet ditt sk.";
      }
      else
      {
        return "Fant <b>$num</b> dokumenter som passet ditt sk. "
               "Viser beste treff frst.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorNorwegian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1436 of file translator_no.h.
    {
      if (numDocuments==0)
      {
        return "Beklager, men ingen dokumenter ble funnet.";
      }
      else if (numDocuments==1)
      {
        return "Fant <b>ett</b> dokument som passet ditt sk.";
      }
      else
      {
        return "Fant <b>$num</b> dokumenter som passet ditt sk. "
               "Viser beste treff frst.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorNorwegian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1424 of file translator_no.h.
    {
      return "Skeresultater";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorNorwegian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1424 of file translator_no.h.
    {
      return "Skeresultater";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorNorwegian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 546 of file translator_no.h.
    { return "Se ogs"; }
trSeeAlso() [2/2]
virtual QCString TranslatorNorwegian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 546 of file translator_no.h.
    { return "Se ogs"; }
trSignals() [1/2]
virtual QCString TranslatorNorwegian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_no.h.
    { return "Signaler"; }
trSignals() [2/2]
virtual QCString TranslatorNorwegian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_no.h.
    { return "Signaler"; }
trSince() [1/2]
virtual QCString TranslatorNorwegian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 981 of file translator_no.h.
    {
      return "Siden";
    }
trSince() [2/2]
virtual QCString TranslatorNorwegian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 981 of file translator_no.h.
    {
      return "Siden";
    }
trSourceFile() [1/2]
virtual QCString TranslatorNorwegian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1466 of file translator_no.h.
    {
        return "Kildefil " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorNorwegian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1466 of file translator_no.h.
    {
        return "Kildefil " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorNorwegian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1395 of file translator_no.h.
    {
      return "Statiske Pakkeattributter";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorNorwegian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1395 of file translator_no.h.
    {
      return "Statiske Pakkeattributter";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorNorwegian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1381 of file translator_no.h.
    {
      return "Statiske Pakkefunksjoner";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorNorwegian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1381 of file translator_no.h.
    {
      return "Statiske Pakkefunksjoner";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorNorwegian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 940 of file translator_no.h.
    {
      return "Statiske private attributter";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorNorwegian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 940 of file translator_no.h.
    {
      return "Statiske private attributter";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorNorwegian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 654 of file translator_no.h.
    { return "Statiske private medlemsfunksjoner"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorNorwegian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 654 of file translator_no.h.
    { return "Statiske private medlemsfunksjoner"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorNorwegian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_no.h.
    {
      return "Statiske protected attributter";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorNorwegian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_no.h.
    {
      return "Statiske protected attributter";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorNorwegian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_no.h.
    { return "Statiske protected medlemsfunksjoner"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorNorwegian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_no.h.
    { return "Statiske protected medlemsfunksjoner"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorNorwegian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_no.h.
    {
      return "Statiske public attributter";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorNorwegian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_no.h.
    {
      return "Statiske public attributter";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorNorwegian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_no.h.
    { return "Statiske public medlemsfunksjoner"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorNorwegian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_no.h.
    { return "Statiske public medlemsfunksjoner"; }
trTest() [1/2]
virtual QCString TranslatorNorwegian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1064 of file translator_no.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorNorwegian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1064 of file translator_no.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorNorwegian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1069 of file translator_no.h.
    {
      return "Test-liste";
    }
trTestList() [2/2]
virtual QCString TranslatorNorwegian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1069 of file translator_no.h.
    {
      return "Test-liste";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorNorwegian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 139 of file translator_no.h.
    { return "Dette er den fullstendige listen over medlemmer for "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorNorwegian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 139 of file translator_no.h.
    { return "Dette er den fullstendige listen over medlemmer for "; }
trTodo() [1/2]
virtual QCString TranslatorNorwegian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 950 of file translator_no.h.
    {
      return "Todo";
    }
trTodo() [2/2]
virtual QCString TranslatorNorwegian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 950 of file translator_no.h.
    {
      return "Todo";
    }
trTodoList() [1/2]
virtual QCString TranslatorNorwegian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 955 of file translator_no.h.
    {
      return "Todo-liste";
    }
trTodoList() [2/2]
virtual QCString TranslatorNorwegian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 955 of file translator_no.h.
    {
      return "Todo-liste";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 470 of file translator_no.h.
    { return "Typedef-dokumentasjon"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 470 of file translator_no.h.
    { return "Typedef-dokumentasjon"; }
trTypedefs() [1/2]
virtual QCString TranslatorNorwegian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 434 of file translator_no.h.
    { return "Typedef'er"; }
trTypedefs() [2/2]
virtual QCString TranslatorNorwegian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 434 of file translator_no.h.
    { return "Typedef'er"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorNorwegian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 494 of file translator_no.h.
    { return "Variabeldokumentasjon"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorNorwegian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 494 of file translator_no.h.
    { return "Variabeldokumentasjon"; }
trVariables() [1/2]
virtual QCString TranslatorNorwegian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 452 of file translator_no.h.
    { return "Variabler"; }
trVariables() [2/2]
virtual QCString TranslatorNorwegian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 452 of file translator_no.h.
    { return "Variabler"; }
trVersion() [1/2]
virtual QCString TranslatorNorwegian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 534 of file translator_no.h.
    { return "Versjon"; }
trVersion() [2/2]
virtual QCString TranslatorNorwegian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 534 of file translator_no.h.
    { return "Versjon"; }
trWarning() [1/2]
virtual QCString TranslatorNorwegian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 530 of file translator_no.h.
    { return "Advarsel"; }
trWarning() [2/2]
virtual QCString TranslatorNorwegian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 530 of file translator_no.h.
    { return "Advarsel"; }
trWriteList() [1/2]
virtual QCString TranslatorNorwegian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 660 of file translator_no.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", og ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorNorwegian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 660 of file translator_no.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", og ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_no.h
doxygen/src/translator_no.h