NamespaceTreeContext::Private Class Reference
Public Member Functions
Private ()
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private ()
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant tree () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant maxDepth () const
TemplateVariant preferredDepth () const
TemplateVariant title () const
int createMaxDepth () const
int createPreferredDepth () const
TemplateVariant tree () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant maxDepth () const
TemplateVariant preferredDepth () const
TemplateVariant title () const
int createMaxDepth () const
int createPreferredDepth () const
Private Attributes
TemplateListIntfPtr m_namespaceTree
CachedItem< int, Private, &Private::createMaxDepth > m_maxDepth
CachedItem< int, Private, &Private::createPreferredDepth > m_preferredDepth
Static Private Attributes
static const PropertyMap< NamespaceTreeContext::Private > s_inst
Detailed Description
Definition at line 6254 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
NamespaceTreeContext::Private::Private () [inline]
Definition at line 6257 of file context.cpp.
    {
      m_namespaceTree = NestingContext::alloc(0,ContextTreeType::Namespace,0);
      auto ctx = std::dynamic_pointer_cast<NestingContext>(m_namespaceTree);
      ClassDefSet visitedClasses;
      ctx->addNamespaces(*Doxygen::namespaceLinkedMap,TRUE,FALSE,TRUE,visitedClasses);
    }
References NestingContext::alloc(), FALSE, m_namespaceTree, Namespace, Doxygen::namespaceLinkedMap, and TRUE.
Private() [2/2]
NamespaceTreeContext::Private::Private () [inline]
Definition at line 6257 of file context.cpp.
    {
      m_namespaceTree = NestingContext::alloc(0,ContextTreeType::Namespace,0);
      auto ctx = std::dynamic_pointer_cast<NestingContext>(m_namespaceTree);
      ClassDefSet visitedClasses;
      ctx->addNamespaces(*Doxygen::namespaceLinkedMap,TRUE,FALSE,TRUE,visitedClasses);
    }
References NestingContext::alloc(), FALSE, Namespace, Doxygen::namespaceLinkedMap, and TRUE.
Member Function Documentation
createMaxDepth() [1/2]
int NamespaceTreeContext::Private::createMaxDepth () const [inline], [private]
Definition at line 6288 of file context.cpp.
    {
      return computeMaxDepth(m_namespaceTree);
    }
References computeMaxDepth(), and m_namespaceTree.
createMaxDepth() [2/2]
int NamespaceTreeContext::Private::createMaxDepth () const [inline], [private]
Definition at line 6288 of file context.cpp.
    {
      return computeMaxDepth(m_namespaceTree);
    }
References computeMaxDepth().
createPreferredDepth() [1/2]
int NamespaceTreeContext::Private::createPreferredDepth () const [inline], [private]
Definition at line 6292 of file context.cpp.
    {
      return computePreferredDepth(m_namespaceTree,m_maxDepth.get(this));
    }
References computePreferredDepth(), m_maxDepth, and m_namespaceTree.
createPreferredDepth() [2/2]
int NamespaceTreeContext::Private::createPreferredDepth () const [inline], [private]
Definition at line 6292 of file context.cpp.
    {
      return computePreferredDepth(m_namespaceTree,m_maxDepth.get(this));
    }
References computePreferredDepth().
fields() [1/2]
StringVector NamespaceTreeContext::Private::fields () const [inline]
Definition at line 6267 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector NamespaceTreeContext::Private::fields () const [inline]
Definition at line 6267 of file context.cpp.
{ return s_inst.fields(); }
fileName() [1/2]
TemplateVariant NamespaceTreeContext::Private::fileName () const [inline], [private]
Definition at line 6272 of file context.cpp.
{ return "namespaces"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
TemplateVariant NamespaceTreeContext::Private::fileName () const [inline], [private]
Definition at line 6272 of file context.cpp.
{ return "namespaces"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
get() [1/2]
TemplateVariant NamespaceTreeContext::Private::get (const QCString & n) const [inline]
Definition at line 6266 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant NamespaceTreeContext::Private::get (const QCString & n) const [inline]
Definition at line 6266 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
highlight() [1/2]
TemplateVariant NamespaceTreeContext::Private::highlight () const [inline], [private]
Definition at line 6274 of file context.cpp.
{ return "namespaces"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant NamespaceTreeContext::Private::highlight () const [inline], [private]
Definition at line 6274 of file context.cpp.
{ return "namespaces"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
maxDepth() [1/2]
TemplateVariant NamespaceTreeContext::Private::maxDepth () const [inline], [private]
Definition at line 6276 of file context.cpp.
{ return m_maxDepth.get(this); }
References m_maxDepth.
maxDepth() [2/2]
TemplateVariant NamespaceTreeContext::Private::maxDepth () const [inline], [private]
Definition at line 6276 of file context.cpp.
{ return m_maxDepth.get(this); }
preferredDepth() [1/2]
TemplateVariant NamespaceTreeContext::Private::preferredDepth () const [inline], [private]
Definition at line 6277 of file context.cpp.
{ return m_preferredDepth.get(this); }
References m_preferredDepth.
preferredDepth() [2/2]
TemplateVariant NamespaceTreeContext::Private::preferredDepth () const [inline], [private]
Definition at line 6277 of file context.cpp.
{ return m_preferredDepth.get(this); }
relPath() [1/2]
TemplateVariant NamespaceTreeContext::Private::relPath () const [inline], [private]
Definition at line 6273 of file context.cpp.
{ return ""; }
relPath() [2/2]
TemplateVariant NamespaceTreeContext::Private::relPath () const [inline], [private]
Definition at line 6273 of file context.cpp.
{ return ""; }
subhighlight() [1/2]
TemplateVariant NamespaceTreeContext::Private::subhighlight () const [inline], [private]
Definition at line 6275 of file context.cpp.
{ return "namespacelist"; }
subhighlight() [2/2]
TemplateVariant NamespaceTreeContext::Private::subhighlight () const [inline], [private]
Definition at line 6275 of file context.cpp.
{ return "namespacelist"; }
title() [1/2]
TemplateVariant NamespaceTreeContext::Private::title () const [inline], [private]
Definition at line 6278 of file context.cpp.
    {
      return Config_getBool(OPTIMIZE_OUTPUT_JAVA) ? theTranslator->trPackageList() :
             Config_getBool(OPTIMIZE_OUTPUT_VHDL) ? theTranslator->trPackageList() :
             Config_getBool(OPTIMIZE_FOR_FORTRAN) ? theTranslator->trModulesList() :
             Config_getBool(OPTIMIZE_OUTPUT_SLICE) ? theTranslator->trModulesList() :
                                                     theTranslator->trNamespaceList();
    }
References Config_getBool, theTranslator, Translator::trModulesList(), Translator::trNamespaceList(), and Translator::trPackageList().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant NamespaceTreeContext::Private::title () const [inline], [private]
Definition at line 6278 of file context.cpp.
    {
      return Config_getBool(OPTIMIZE_OUTPUT_JAVA) ? theTranslator->trPackageList() :
             Config_getBool(OPTIMIZE_OUTPUT_VHDL) ? theTranslator->trPackageList() :
             Config_getBool(OPTIMIZE_FOR_FORTRAN) ? theTranslator->trModulesList() :
             Config_getBool(OPTIMIZE_OUTPUT_SLICE) ? theTranslator->trModulesList() :
                                                     theTranslator->trNamespaceList();
    }
References Config_getBool, theTranslator, Translator::trModulesList(), Translator::trNamespaceList(), and Translator::trPackageList().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
tree() [1/2]
TemplateVariant NamespaceTreeContext::Private::tree () const [inline], [private]
Definition at line 6271 of file context.cpp.
{ return TemplateVariant(m_namespaceTree); }
References m_namespaceTree.
tree() [2/2]
TemplateVariant NamespaceTreeContext::Private::tree () const [inline], [private]
Definition at line 6271 of file context.cpp.
{ return TemplateVariant(m_namespaceTree); }
Member Data Documentation
m_maxDepth
CachedItem< int, Private, &Private::createMaxDepth > NamespaceTreeContext::Private::m_maxDepth [private]
Definition at line 6297 of file context.cpp.
Referenced by createPreferredDepth(), and maxDepth().
m_namespaceTree
TemplateListIntfPtr NamespaceTreeContext::Private::m_namespaceTree [private]
Definition at line 6296 of file context.cpp.
Referenced by createMaxDepth(), createPreferredDepth(), Private(), and tree().
m_preferredDepth
CachedItem< int, Private, &Private::createPreferredDepth > NamespaceTreeContext::Private::m_preferredDepth [private]
Definition at line 6298 of file context.cpp.
Referenced by preferredDepth().
s_inst
const PropertyMap< NamespaceTreeContext::Private > NamespaceTreeContext::Private::s_inst [static], [private]
Initial value:
{
  { "tree", &Private::tree },
  { "fileName", &Private::fileName },
  { "relPath", &Private::relPath },
  { "highlight", &Private::highlight },
  { "subhighlight", &Private::subhighlight },
  { "title", &Private::title },
  { "preferredDepth",&Private::preferredDepth },
  { "maxDepth", &Private::maxDepth }
}
Definition at line 6299 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp