TemplateNodeCreator< T > Class Template Reference
Helper class for creating template AST tag nodes and returning the template for a given node.
Public Member Functions
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Static Public Member Functions
static TemplateNodePtr createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
static TemplateNodePtr createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions
void mkpath (const TemplateContextImpl *ci, const std::string &fileName)
void mkpath (const TemplateContextImpl *ci, const std::string &fileName)
Protected Attributes
QCString m_templateName
int m_line = 0
Detailed Description
template<class T>
class TemplateNodeCreator< T >
Helper class for creating template AST tag nodes and returning the template for a given node.
Definition at line 3038 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeCreator() [1/2]
template<class T >
TemplateNodeCreator< T >::TemplateNodeCreator (TemplateParser * parser, TemplateNode * parent, int line) [inline]
Definition at line 3041 of file template.cpp.
      : TemplateNode(parent), m_templateName(parser->templateName()), m_line(line) {}
TemplateNodeCreator() [2/2]
template<class T >
TemplateNodeCreator< T >::TemplateNodeCreator (TemplateParser * parser, TemplateNode * parent, int line) [inline]
Definition at line 3041 of file template.cpp.
      : TemplateNode(parent), m_templateName(parser->templateName()), m_line(line) {}
Member Function Documentation
createInstance() [1/2]
template<class T >
static TemplateNodePtr TemplateNodeCreator< T >::createInstance (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline], [static]
Definition at line 3043 of file template.cpp.
    {
      return std::make_unique<T>(parser,parent,line,data);
    }
References data, and TemplateNode::parent().
createInstance() [2/2]
template<class T >
static TemplateNodePtr TemplateNodeCreator< T >::createInstance (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline], [static]
Definition at line 3043 of file template.cpp.
    {
      return std::make_unique<T>(parser,parent,line,data);
    }
References data, and TemplateNode::parent().
getTemplate() [1/2]
template<class T >
TemplateImpl * TemplateNodeCreator< T >::getTemplate () [inline]
Definition at line 3050 of file template.cpp.
    {
      TemplateNode *root = this;
      while (root && root->parent())
      {
        root = root->parent();
      }
      return dynamic_cast<TemplateImpl*>(root);
    }
References TemplateNode::parent().
getTemplate() [2/2]
template<class T >
TemplateImpl * TemplateNodeCreator< T >::getTemplate () [inline]
Definition at line 3050 of file template.cpp.
    {
      TemplateNode *root = this;
      while (root && root->parent())
      {
        root = root->parent();
      }
      return dynamic_cast<TemplateImpl*>(root);
    }
References TemplateNode::parent().
mkpath() [1/2]
template<class T >
void TemplateNodeCreator< T >::mkpath (const TemplateContextImpl * ci, const std::string & fileName) [inline], [protected]
Definition at line 3060 of file template.cpp.
    {
      size_t i=fileName.find('/');
      std::string outputDir = ci->outputDirectory().str();
      Dir d(outputDir);
      if (!d.exists())
      {
        Dir rootDir;
        if (!rootDir.mkdir(outputDir))
        {
          err("tag OUTPUT_DIRECTORY: Output directory '%s' does not "
          "exist and cannot be created\n",outputDir.c_str());
          return;
        }
        d.setPath(outputDir);
      }
      size_t j=0;
      while (i!=std::string::npos) // fileName contains path part
      {
        if (d.exists())
        {
          bool ok = d.mkdir(fileName.substr(j,i-j));
          if (!ok)
          {
            err("Failed to create directory '%s'\n",(fileName.substr(j,i-j)).c_str());
            break;
          }
          std::string dirName = outputDir+'/'+fileName.substr(0,i);
          d = Dir(dirName);
          j = i+1;
        }
        i=fileName.find('/',i+1);
      }
    }
References err(), Dir::exists(), Dir::mkdir(), TemplateContextImpl::outputDirectory(), Dir::setPath(), QCString::str(), and string.
mkpath() [2/2]
template<class T >
void TemplateNodeCreator< T >::mkpath (const TemplateContextImpl * ci, const std::string & fileName) [inline], [protected]
Definition at line 3060 of file template.cpp.
    {
      size_t i=fileName.find('/');
      std::string outputDir = ci->outputDirectory().str();
      Dir d(outputDir);
      if (!d.exists())
      {
        Dir rootDir;
        if (!rootDir.mkdir(outputDir))
        {
          err("tag OUTPUT_DIRECTORY: Output directory '%s' does not "
          "exist and cannot be created\n",outputDir.c_str());
          return;
        }
        d.setPath(outputDir);
      }
      size_t j=0;
      while (i!=std::string::npos) // fileName contains path part
      {
        if (d.exists())
        {
          bool ok = d.mkdir(fileName.substr(j,i-j));
          if (!ok)
          {
            err("Failed to create directory '%s'\n",(fileName.substr(j,i-j)).c_str());
            break;
          }
          std::string dirName = outputDir+'/'+fileName.substr(0,i);
          d = Dir(dirName);
          j = i+1;
        }
        i=fileName.find('/',i+1);
      }
    }
References err(), Dir::exists(), Dir::mkdir(), TemplateContextImpl::outputDirectory(), Dir::setPath(), QCString::str(), and string.
Member Data Documentation
m_line
template<class T >
int TemplateNodeCreator< T >::m_line = 0 [protected]
Definition at line 3095 of file template.cpp.
Referenced by TemplateNodeBlock::render().
m_templateName
template<class T >
QCString TemplateNodeCreator< T >::m_templateName [protected]
Definition at line 3094 of file template.cpp.
Referenced by TemplateNodeBlock::render().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp