NamespaceDef Class Reference
#include <namespacedef.h>
Public Member Functions
virtual DefType definitionType () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual int numDocMembers () const =0
virtual const LinkedRefMap< const NamespaceDef > & getUsedNamespaces () const =0
virtual const LinkedRefMap< const ClassDef > & getUsedClasses () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual QCString localName () const =0
virtual bool isConstantGroup () const =0
virtual bool isModule () const =0
virtual bool isLibrary () const =0
virtual bool isInline () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool hasDetailedDescription () const =0
virtual const Definition * findInnerCompound (const QCString &name) const =0
virtual bool subGrouping () const =0
virtual MemberList * getMemberList (MemberListType lt) const =0
virtual const MemberLists & getMemberLists () const =0
virtual const MemberDef * getMemberByName (const QCString &) const =0
virtual const MemberGroupList & getMemberGroups () const =0
virtual ClassLinkedRefMap getClasses () const =0
virtual ClassLinkedRefMap getInterfaces () const =0
virtual ClassLinkedRefMap getStructs () const =0
virtual ClassLinkedRefMap getExceptions () const =0
virtual NamespaceLinkedRefMap getNamespaces () const =0
virtual ConceptLinkedRefMap getConcepts () const =0
virtual QCString title () const =0
virtual QCString compoundTypeString () const =0
virtual DefType definitionType () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual int numDocMembers () const =0
virtual const LinkedRefMap< const NamespaceDef > & getUsedNamespaces () const =0
virtual const LinkedRefMap< const ClassDef > & getUsedClasses () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual QCString localName () const =0
virtual bool isConstantGroup () const =0
virtual bool isModule () const =0
virtual bool isLibrary () const =0
virtual bool isInline () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool hasDetailedDescription () const =0
virtual const Definition * findInnerCompound (const QCString &name) const =0
virtual bool subGrouping () const =0
virtual MemberList * getMemberList (MemberListType lt) const =0
virtual const MemberLists & getMemberLists () const =0
virtual const MemberDef * getMemberByName (const QCString &) const =0
virtual const MemberGroupList & getMemberGroups () const =0
virtual ClassLinkedRefMap getClasses () const =0
virtual ClassLinkedRefMap getInterfaces () const =0
virtual ClassLinkedRefMap getStructs () const =0
virtual ClassLinkedRefMap getExceptions () const =0
virtual NamespaceLinkedRefMap getNamespaces () const =0
virtual ConceptLinkedRefMap getConcepts () const =0
virtual QCString title () const =0
virtual QCString compoundTypeString () const =0
Additional Inherited Members
Detailed Description
An abstract interface of a namespace symbol.
Definition at line 54 of file namespacedef.h.
Member Function Documentation
anchor() [1/2]
virtual QCString NamespaceDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), addToIndices(), NamespaceDefAliasImpl::anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString NamespaceDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
compoundTypeString() [1/2]
virtual QCString NamespaceDef::compoundTypeString () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NamespaceContext::Private::compoundType(), NamespaceDefAliasImpl::compoundTypeString(), and MemberDefImpl::warnIfUndocumented().
compoundTypeString() [2/2]
virtual QCString NamespaceDef::compoundTypeString () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
definitionType() [1/2]
virtual DefType NamespaceDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
definitionType() [2/2]
virtual DefType NamespaceDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
displayName() [1/2]
virtual QCString NamespaceDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in NamespaceDefAliasImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefImpl.
Referenced by addToIndices(), MemberDefImpl::getScopeString(), MemberContext::Private::handleNameWithContextFor(), MemberDefImpl::writeDocumentation(), MemberDefImpl::writeLink(), and writeNamespaceLinkForMember().
displayName() [2/2]
virtual QCString NamespaceDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in NamespaceDefAliasImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefImpl.
findInnerCompound() [1/2]
virtual const Definition * NamespaceDef::findInnerCompound (const QCString & name) const [pure virtual]
Implements Definition.
Implemented in DefinitionMixin< NamespaceDefMutable >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, NamespaceDefAliasImpl, DefinitionMixin< NamespaceDefMutable >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NamespaceDefAliasImpl::findInnerCompound(), and generateClassMemberLink().
findInnerCompound() [2/2]
virtual const Definition * NamespaceDef::findInnerCompound (const QCString & name) const [pure virtual]
Implements Definition.
Implemented in DefinitionMixin< NamespaceDefMutable >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, NamespaceDefAliasImpl, DefinitionMixin< NamespaceDefMutable >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, and NamespaceDefAliasImpl.
getClasses() [1/2]
virtual ClassLinkedRefMap NamespaceDef::getClasses () const [pure virtual]
Returns the classes contained in this namespace
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NestingNodeContext::Private::addNamespaces(), NamespaceContext::Private::createClasses(), NamespaceContext::Private::createInlineClasses(), generateNamespaceDocs(), PerlModGenerator::generatePerlModForNamespace(), generateXMLForNamespace(), NamespaceDefAliasImpl::getClasses(), lookupSymbol(), namespaceHasNestedClass(), writeClassTreeInsideNamespaceElement(), and writeNamespaceTreeElement().
getClasses() [2/2]
virtual ClassLinkedRefMap NamespaceDef::getClasses () const [pure virtual]
Returns the classes contained in this namespace
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
getConcepts() [1/2]
virtual ConceptLinkedRefMap NamespaceDef::getConcepts () const [pure virtual]
Returns the concepts contained in this namespace
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NestingNodeContext::Private::addNamespaces(), generateNamespaceDocs(), generateXMLForNamespace(), NamespaceDefAliasImpl::getConcepts(), namespaceHasNestedConcept(), writeConceptTreeInsideNamespaceElement(), and writeNamespaceTreeElement().
getConcepts() [2/2]
virtual ConceptLinkedRefMap NamespaceDef::getConcepts () const [pure virtual]
Returns the concepts contained in this namespace
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
getExceptions() [1/2]
virtual ClassLinkedRefMap NamespaceDef::getExceptions () const [pure virtual]
Returns the Slice exceptions contained in this namespace
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by generateNamespaceDocs(), NamespaceDefAliasImpl::getExceptions(), namespaceHasNestedClass(), and writeClassTreeInsideNamespaceElement().
getExceptions() [2/2]
virtual ClassLinkedRefMap NamespaceDef::getExceptions () const [pure virtual]
Returns the Slice exceptions contained in this namespace
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
getInterfaces() [1/2]
virtual ClassLinkedRefMap NamespaceDef::getInterfaces () const [pure virtual]
Returns the Slice interfaces contained in this namespace
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by generateNamespaceDocs(), NamespaceDefAliasImpl::getInterfaces(), namespaceHasNestedClass(), and writeClassTreeInsideNamespaceElement().
getInterfaces() [2/2]
virtual ClassLinkedRefMap NamespaceDef::getInterfaces () const [pure virtual]
Returns the Slice interfaces contained in this namespace
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
getMemberByName() [1/2]
virtual const MemberDef * NamespaceDef::getMemberByName (const QCString &) const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefImpl, NamespaceDefAliasImpl, and NamespaceDefAliasImpl.
Referenced by SymbolResolver::Private::followPath(), generateClassOrGlobalLink(), NamespaceDefAliasImpl::getMemberByName(), and setCallContextForVar().
getMemberByName() [2/2]
virtual const MemberDef * NamespaceDef::getMemberByName (const QCString &) const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefImpl, NamespaceDefAliasImpl, and NamespaceDefAliasImpl.
getMemberGroups() [1/2]
virtual const MemberGroupList & NamespaceDef::getMemberGroups () const [pure virtual]
Returns the user defined member groups
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NamespaceContext::Private::createMemberGroups(), PerlModGenerator::generatePerlModForNamespace(), generateXMLForNamespace(), and NamespaceDefAliasImpl::getMemberGroups().
getMemberGroups() [2/2]
virtual const MemberGroupList & NamespaceDef::getMemberGroups () const [pure virtual]
Returns the user defined member groups
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
getMemberList() [1/2]
virtual MemberList * NamespaceDef::getMemberList (MemberListType lt) const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NestingNodeContext::Private::addMembers(), countVisibleMembers(), NamespaceContext::Private::createMemberList(), generateDEFForNamespace(), PerlModGenerator::generatePerlModForNamespace(), NamespaceDefAliasImpl::getMemberList(), and writeNamespaceMembers().
getMemberList() [2/2]
virtual MemberList * NamespaceDef::getMemberList (MemberListType lt) const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
getMemberLists() [1/2]
virtual const MemberLists & NamespaceDef::getMemberLists () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by generateXMLForNamespace(), and NamespaceDefAliasImpl::getMemberLists().
getMemberLists() [2/2]
virtual const MemberLists & NamespaceDef::getMemberLists () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
getNamespaces() [1/2]
virtual NamespaceLinkedRefMap NamespaceDef::getNamespaces () const [pure virtual]
Returns the namespaces contained in this namespace
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NestingNodeContext::Private::addNamespaces(), NamespaceContext::Private::createConstantgroups(), NamespaceContext::Private::createNamespaces(), PerlModGenerator::generatePerlModForNamespace(), generateXMLForNamespace(), NamespaceDefAliasImpl::getNamespaces(), lookupSymbol(), namespaceHasNestedClass(), namespaceHasNestedConcept(), namespaceHasNestedNamespace(), writeClassTreeInsideNamespaceElement(), writeConceptTreeInsideNamespaceElement(), and writeNamespaceTreeElement().
getNamespaces() [2/2]
virtual NamespaceLinkedRefMap NamespaceDef::getNamespaces () const [pure virtual]
Returns the namespaces contained in this namespace
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
getOutputFileBase() [1/2]
virtual QCString NamespaceDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by generateDEFForNamespace(), generateXMLForNamespace(), MemberDefImpl::getOutputFileBase(), NamespaceDefAliasImpl::getOutputFileBase(), writeAlphabeticalClassList(), writeClassTreeInsideNamespaceElement(), writeConceptTreeInsideNamespaceElement(), and writeNamespaceTreeElement().
getOutputFileBase() [2/2]
virtual QCString NamespaceDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
getStructs() [1/2]
virtual ClassLinkedRefMap NamespaceDef::getStructs () const [pure virtual]
Returns the Slice structs contained in this namespace
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by generateNamespaceDocs(), NamespaceDefAliasImpl::getStructs(), namespaceHasNestedClass(), and writeClassTreeInsideNamespaceElement().
getStructs() [2/2]
virtual ClassLinkedRefMap NamespaceDef::getStructs () const [pure virtual]
Returns the Slice structs contained in this namespace
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
getUsedClasses() [1/2]
virtual const LinkedRefMap< const ClassDef > & NamespaceDef::getUsedClasses () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NamespaceDefAliasImpl::getUsedClasses(), SymbolResolver::Private::isAccessibleFrom(), and SymbolResolver::Private::isAccessibleFromWithExpScope().
getUsedClasses() [2/2]
virtual const LinkedRefMap< const ClassDef > & NamespaceDef::getUsedClasses () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
getUsedNamespaces() [1/2]
virtual const LinkedRefMap< const NamespaceDef > & NamespaceDef::getUsedNamespaces () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by findUsingDirectives(), NamespaceDefAliasImpl::getUsedNamespaces(), SymbolResolver::Private::isAccessibleFrom(), and SymbolResolver::Private::isAccessibleFromWithExpScope().
getUsedNamespaces() [2/2]
virtual const LinkedRefMap< const NamespaceDef > & NamespaceDef::getUsedNamespaces () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
hasDetailedDescription() [1/2]
virtual bool NamespaceDef::hasDetailedDescription () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NamespaceDefAliasImpl::hasDetailedDescription(), and NamespaceContext::Private::hasDetails().
hasDetailedDescription() [2/2]
virtual bool NamespaceDef::hasDetailedDescription () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
isConstantGroup() [1/2]
virtual bool NamespaceDef::isConstantGroup () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NamespaceDefAliasImpl::isConstantGroup().
isConstantGroup() [2/2]
virtual bool NamespaceDef::isConstantGroup () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
isInline() [1/2]
virtual bool NamespaceDef::isInline () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by buildNamespaceList(), generateXMLForNamespace(), NamespaceDefAliasImpl::isInline(), and resolveClassNestingRelations().
isInline() [2/2]
virtual bool NamespaceDef::isInline () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
isLibrary() [1/2]
virtual bool NamespaceDef::isLibrary () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NamespaceDefAliasImpl::isLibrary().
isLibrary() [2/2]
virtual bool NamespaceDef::isLibrary () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
isLinkable() [1/2]
virtual bool NamespaceDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by addEnumValuesToEnums(), addMemberToSearchIndex(), generateClassOrGlobalLink(), generateLink(), getDefsOld(), MemberDefImpl::getOutputFileBase(), getScopeDefs(), MemberDefImpl::isDetailedSectionVisible(), NamespaceDefAliasImpl::isLinkable(), writeAlphabeticalClassList(), MemberDefImpl::writeDocumentation(), and writeNamespaceTreeElement().
isLinkable() [2/2]
virtual bool NamespaceDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
isLinkableInProject() [1/2]
virtual bool NamespaceDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by MemberDefImpl::_computeLinkableInProject(), NestingContext::Private::addNamespace(), addNamespaceMemberNameToIndex(), addSourceReferences(), addToIndices(), buildNamespaceList(), NamespaceMembersIndexContext::Private::createMembersFiltered(), generateNamespaceDocs(), NamespaceDefAliasImpl::isLinkableInProject(), writeClassTreeInsideNamespaceElement(), writeConceptTreeInsideNamespaceElement(), and writeTagFile().
isLinkableInProject() [2/2]
virtual bool NamespaceDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
isModule() [1/2]
virtual bool NamespaceDef::isModule () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NamespaceDefAliasImpl::isModule().
isModule() [2/2]
virtual bool NamespaceDef::isModule () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
localName() [1/2]
virtual QCString NamespaceDef::localName () const [pure virtual]
Returns the local name without any scope qualifiers.
Implements Definition.
Implemented in DefinitionMixin< NamespaceDefMutable >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, NamespaceDefAliasImpl, DefinitionMixin< NamespaceDefMutable >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by addToIndices(), NamespaceDefAliasImpl::localName(), makeDisplayName(), writeClassTreeInsideNamespaceElement(), writeConceptTreeInsideNamespaceElement(), and writeNamespaceTreeElement().
localName() [2/2]
virtual QCString NamespaceDef::localName () const [pure virtual]
Returns the local name without any scope qualifiers.
Implements Definition.
Implemented in DefinitionMixin< NamespaceDefMutable >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, NamespaceDefAliasImpl, DefinitionMixin< NamespaceDefMutable >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, and NamespaceDefAliasImpl.
numDocMembers() [1/2]
virtual int NamespaceDef::numDocMembers () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NamespaceDefAliasImpl::numDocMembers().
numDocMembers() [2/2]
virtual int NamespaceDef::numDocMembers () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
subGrouping() [1/2]
virtual bool NamespaceDef::subGrouping () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by NamespaceContext::Private::createMemberGroups(), and NamespaceDefAliasImpl::subGrouping().
subGrouping() [2/2]
virtual bool NamespaceDef::subGrouping () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
title() [1/2]
virtual QCString NamespaceDef::title () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), NamespaceContext::Private::title(), and NamespaceDefAliasImpl::title().
title() [2/2]
virtual QCString NamespaceDef::title () const [pure virtual]
Implemented in NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDefImpl, and NamespaceDefAliasImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/namespacedef.h
doxygen/src/namespacedef.h