Formula Class Reference
#include <formula.h>
Public Member Functions
Formula (const QCString &text, int id, int width=-1, int height=-1)
int width () const
int height () const
int id () const
QCString text () const
bool isCached () const
bool isCachedDark () const
Formula (const QCString &text, int id, int width=-1, int height=-1)
int width () const
int height () const
int id () const
QCString text () const
bool isCached () const
bool isCachedDark () const
Private Member Functions
void setWidth (int width)
void setHeight (int height)
void setCached (bool cached)
void setCachedDark (bool cached)
void setWidth (int width)
void setHeight (int height)
void setCached (bool cached)
void setCachedDark (bool cached)
Private Attributes
QCString m_text
int m_id
int m_width
int m_height
bool m_cached = false
bool m_cachedDark = false
bool m_forceRegen = false
Friends
class FormulaManager
Detailed Description
Class representing a LaTeX formula as found in the documentation
Definition at line 28 of file formula.h.
Constructor & Destructor Documentation
Formula() [1/2]
Formula::Formula (const QCString & text, int id, int width = -1, int height = -1) [inline]
Definition at line 31 of file formula.h.
      : m_text(text), m_id(id), m_width(width), m_height(height) {}
Formula() [2/2]
Formula::Formula (const QCString & text, int id, int width = -1, int height = -1) [inline]
Definition at line 31 of file formula.h.
      : m_text(text), m_id(id), m_width(width), m_height(height) {}
Member Function Documentation
height() [1/2]
int Formula::height () const [inline]
Definition at line 35 of file formula.h.
{ return m_height; }
References m_height.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docImageType::get_height(), doxmlparser.compound.docDotMscType::get_height(), doxmlparser.compound.docImageFileType::get_height(), doxmlparser.compound.docPlantumlType::get_height(), HtmlDocVisitor::operator()(), doxmlparser.compound.docImageType::set_height(), doxmlparser.compound.docDotMscType::set_height(), doxmlparser.compound.docImageFileType::set_height(), doxmlparser.compound.docPlantumlType::set_height(), and setHeight().
height() [2/2]
int Formula::height () const [inline]
Definition at line 35 of file formula.h.
{ return m_height; }
References m_height.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docImageType::get_height(), doxmlparser.compound.docDotMscType::get_height(), doxmlparser.compound.docImageFileType::get_height(), doxmlparser.compound.docPlantumlType::get_height(), doxmlparser.compound.docImageType::set_height(), doxmlparser.compound.docDotMscType::set_height(), doxmlparser.compound.docImageFileType::set_height(), and doxmlparser.compound.docPlantumlType::set_height().
id() [1/2]
int Formula::id () const [inline]
Definition at line 36 of file formula.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), FormulaManager::addFormula(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), FormulaManager::initFromRepository(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
int Formula::id () const [inline]
Definition at line 36 of file formula.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
isCached() [1/2]
bool Formula::isCached () const [inline]
Definition at line 38 of file formula.h.
{ return m_cached && !m_forceRegen; }
References m_cached, and m_forceRegen.
isCached() [2/2]
bool Formula::isCached () const [inline]
Definition at line 38 of file formula.h.
{ return m_cached && !m_forceRegen; }
References m_cached, and m_forceRegen.
isCachedDark() [1/2]
bool Formula::isCachedDark () const [inline]
Definition at line 39 of file formula.h.
{ return m_cached && !m_forceRegen; }
References m_cached, and m_forceRegen.
isCachedDark() [2/2]
bool Formula::isCachedDark () const [inline]
Definition at line 39 of file formula.h.
{ return m_cached && !m_forceRegen; }
References m_cached, and m_forceRegen.
setCached() [1/2]
void Formula::setCached (bool cached) [inline], [private]
Definition at line 45 of file formula.h.
{ m_cached = cached; m_forceRegen = m_forceRegen || !cached; }
References m_cached, and m_forceRegen.
Referenced by FormulaManager::initFromRepository().
setCached() [2/2]
void Formula::setCached (bool cached) [inline], [private]
Definition at line 45 of file formula.h.
{ m_cached = cached; m_forceRegen = m_forceRegen || !cached; }
References m_cached, and m_forceRegen.
setCachedDark() [1/2]
void Formula::setCachedDark (bool cached) [inline], [private]
Definition at line 46 of file formula.h.
{ m_cachedDark = cached; m_forceRegen = m_forceRegen || !cached; }
References m_cachedDark, and m_forceRegen.
Referenced by FormulaManager::initFromRepository().
setCachedDark() [2/2]
void Formula::setCachedDark (bool cached) [inline], [private]
Definition at line 46 of file formula.h.
{ m_cachedDark = cached; m_forceRegen = m_forceRegen || !cached; }
References m_cachedDark, and m_forceRegen.
setHeight() [1/2]
void Formula::setHeight (int height) [inline], [private]
Definition at line 44 of file formula.h.
{ m_height = height; }
References height(), and m_height.
Referenced by FormulaManager::updateFormulaSize().
setHeight() [2/2]
void Formula::setHeight (int height) [inline], [private]
Definition at line 44 of file formula.h.
{ m_height = height; }
References height(), and m_height.
setWidth() [1/2]
void Formula::setWidth (int width) [inline], [private]
Definition at line 43 of file formula.h.
{ m_width = width; }
References m_width, and width().
Referenced by FormulaManager::updateFormulaSize().
setWidth() [2/2]
void Formula::setWidth (int width) [inline], [private]
Definition at line 43 of file formula.h.
{ m_width = width; }
References m_width, and width().
text() [1/2]
QCString Formula::text () const [inline]
Definition at line 37 of file formula.h.
{ return m_text; }
References m_text.
Referenced by DocFormula::DocFormula(), and FormulaManager::initFromRepository().
text() [2/2]
QCString Formula::text () const [inline]
Definition at line 37 of file formula.h.
{ return m_text; }
References m_text.
width() [1/2]
int Formula::width () const [inline]
Definition at line 34 of file formula.h.
{ return m_width; }
References m_width.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docEntryType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docTableType::buildAttributes(), doxmlparser.compound.docEntryType::buildAttributes(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEntryType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docTableType::exportAttributes(), doxmlparser.compound.docTableType::get_width(), doxmlparser.compound.docEntryType::get_width(), doxmlparser.compound.docImageType::get_width(), doxmlparser.compound.docDotMscType::get_width(), doxmlparser.compound.docImageFileType::get_width(), doxmlparser.compound.docPlantumlType::get_width(), HtmlDocVisitor::operator()(), doxmlparser.compound.docTableType::set_width(), doxmlparser.compound.docEntryType::set_width(), doxmlparser.compound.docImageType::set_width(), doxmlparser.compound.docDotMscType::set_width(), doxmlparser.compound.docImageFileType::set_width(), doxmlparser.compound.docPlantumlType::set_width(), and setWidth().
width() [2/2]
int Formula::width () const [inline]
Definition at line 34 of file formula.h.
{ return m_width; }
References m_width.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docEntryType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docTableType::buildAttributes(), doxmlparser.compound.docEntryType::buildAttributes(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEntryType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docTableType::exportAttributes(), doxmlparser.compound.docTableType::get_width(), doxmlparser.compound.docEntryType::get_width(), doxmlparser.compound.docImageType::get_width(), doxmlparser.compound.docDotMscType::get_width(), doxmlparser.compound.docImageFileType::get_width(), doxmlparser.compound.docPlantumlType::get_width(), doxmlparser.compound.docTableType::set_width(), doxmlparser.compound.docEntryType::set_width(), doxmlparser.compound.docImageType::set_width(), doxmlparser.compound.docDotMscType::set_width(), doxmlparser.compound.docImageFileType::set_width(), and doxmlparser.compound.docPlantumlType::set_width().
Friends And Related Function Documentation
FormulaManager
FormulaManager [friend]
Definition at line 42 of file formula.h.
Member Data Documentation
m_cached
bool Formula::m_cached = false [private]
Definition at line 52 of file formula.h.
Referenced by isCached(), isCachedDark(), and setCached().
m_cachedDark
bool Formula::m_cachedDark = false [private]
Definition at line 53 of file formula.h.
Referenced by setCachedDark().
m_forceRegen
bool Formula::m_forceRegen = false [private]
Definition at line 54 of file formula.h.
Referenced by isCached(), isCachedDark(), setCached(), and setCachedDark().
m_height
int Formula::m_height [private]
Definition at line 51 of file formula.h.
Referenced by height(), and setHeight().
m_id
int Formula::m_id [private]
Definition at line 49 of file formula.h.
Referenced by id().
m_text
QCString Formula::m_text [private]
Definition at line 48 of file formula.h.
Referenced by text().
m_width
int Formula::m_width [private]
Definition at line 50 of file formula.h.
Referenced by setWidth(), and width().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/formula.h
doxygen/src/formula.h