FortranOutlineParser Class Reference
Fortran language parser using state-based lexical scanning.
#include <fortranscanner.h>
Classes
struct Private
Public Member Functions
FortranOutlineParser (FortranFormat format=FortranFormat_Unknown)
~FortranOutlineParser ()
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)
bool needsPreprocessing (const QCString &extension) const
void parsePrototype (const QCString &text)
FortranOutlineParser (FortranFormat format=FortranFormat_Unknown)
~FortranOutlineParser ()
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)
bool needsPreprocessing (const QCString &extension) const
void parsePrototype (const QCString &text)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Fortran language parser using state-based lexical scanning.
This is the Fortran language parser for doxygen.
Definition at line 27 of file fortranscanner.h.
Constructor & Destructor Documentation
FortranOutlineParser() [1/2]
FortranOutlineParser::FortranOutlineParser (FortranFormat format = FortranFormat_Unknown)
Definition at line 2906 of file fortranscanner.l.
   : p(std::make_unique<Private>(format))
{
}
 FortranOutlineParser() [1/2]
FortranOutlineParser::~FortranOutlineParser ()
Definition at line 2911 of file fortranscanner.l.
{
}
FortranOutlineParser() [2/2]
FortranOutlineParser::FortranOutlineParser (FortranFormat format = FortranFormat_Unknown)
 FortranOutlineParser() [2/2]
FortranOutlineParser::~FortranOutlineParser ()
Member Function Documentation
needsPreprocessing() [1/2]
bool FortranOutlineParser::needsPreprocessing (const QCString & extension) const [virtual]
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 2930 of file fortranscanner.l.
{
  return extension!=extension.lower(); // use preprocessor only for upper case extensions
}
References QCString::lower().
needsPreprocessing() [2/2]
bool FortranOutlineParser::needsPreprocessing (const QCString & extension) const [virtual]
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
parseInput() [1/2]
void FortranOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) [virtual]
Parses a single input file with the goal to build an Entry tree.
Parameters
 in fileName The full name of the file.
 in fileBuf The contents of the file (zero terminated).
 in,out root The root of the tree of Entry *nodes representing the information extracted from the file.
 in clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
Definition at line 2915 of file fortranscanner.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->thisParser = this;
  printlex(yy_flex_debug, TRUE, __FILE__, qPrint(fileName));
  ::parseMain(p->yyscanner,fileName,fileBuf,root,p->format);
  printlex(yy_flex_debug, FALSE, __FILE__, qPrint(fileName));
}
References FALSE, p, parseMain(), printlex(), qPrint(), and TRUE.
parseInput() [2/2]
void FortranOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) [virtual]
Parses a single input file with the goal to build an Entry tree.
Parameters
 in fileName The full name of the file.
 in fileBuf The contents of the file (zero terminated).
 in,out root The root of the tree of Entry *nodes representing the information extracted from the file.
 in clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
parsePrototype() [1/2]
void FortranOutlineParser::parsePrototype (const QCString & text) [virtual]
Callback function called by the comment block scanner. It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Definition at line 2935 of file fortranscanner.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  pushBuffer(p->yyscanner,text);
  yyextra->parsingPrototype = TRUE;
  BEGIN(Prototype);
  fortranscannerYYlex(p->yyscanner);
  yyextra->parsingPrototype = FALSE;
  popBuffer(p->yyscanner);
}
References FALSE, p, popBuffer(), pushBuffer(), and TRUE.
parsePrototype() [2/2]
void FortranOutlineParser::parsePrototype (const QCString & text) [virtual]
Callback function called by the comment block scanner. It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Member Data Documentation
p
std::unique_ptr< Private > FortranOutlineParser::p [private]
Definition at line 41 of file fortranscanner.h.
Referenced by parseInput(), and parsePrototype().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/fortranscanner.h
doxygen/src/fortranscanner.h
doxygen/build/doxygen/src/fortranscanner.l
doxygen/src/fortranscanner.l