TranslatorArabic Class Reference
#include <translator_ar.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool singular)
virtual QCString trFile (bool, bool singular)
virtual QCString trNamespace (bool, bool singular)
virtual QCString trGroup (bool, bool singular)
virtual QCString trPage (bool, bool singular)
virtual QCString trMember (bool, bool singular)
virtual QCString trGlobal (bool, bool singular)
virtual QCString trAuthor (bool, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool singular)
virtual QCString trFile (bool, bool singular)
virtual QCString trNamespace (bool, bool singular)
virtual QCString trGroup (bool, bool singular)
virtual QCString trPage (bool, bool singular)
virtual QCString trMember (bool, bool singular)
virtual QCString trGlobal (bool, bool singular)
virtual QCString trAuthor (bool, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
Additional Inherited Members
Detailed Description
Definition at line 33 of file translator_ar.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorArabic::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 69 of file translator_ar.h.
    {
      return "0xC01 Arabic (Egypt)";
    }
getLanguageString() [2/2]
virtual QCString TranslatorArabic::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 69 of file translator_ar.h.
    {
      return "0xC01 Arabic (Egypt)";
    }
idLanguage() [1/2]
virtual QCString TranslatorArabic::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 45 of file translator_ar.h.
    { return "arabic"; }
idLanguage() [2/2]
virtual QCString TranslatorArabic::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 45 of file translator_ar.h.
    { return "arabic"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorArabic::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 62 of file translator_ar.h.
    {
      return "";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorArabic::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 62 of file translator_ar.h.
    {
      return "";
    }
trAll() [1/2]
virtual QCString TranslatorArabic::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1396 of file translator_ar.h.
    {
      return "";
    }
trAll() [2/2]
virtual QCString TranslatorArabic::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1396 of file translator_ar.h.
    {
      return "";
    }
trAttention() [1/2]
virtual QCString TranslatorArabic::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 954 of file translator_ar.h.
    {
      return "";
    }
trAttention() [2/2]
virtual QCString TranslatorArabic::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 954 of file translator_ar.h.
    {
      return "";
    }
trAuthor() [1/2]
virtual QCString TranslatorArabic::trAuthor (bool , bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1267 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorArabic::trAuthor (bool , bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1267 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorArabic::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1125 of file translator_ar.h.
    {
      return "";
    }
trBug() [2/2]
virtual QCString TranslatorArabic::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1125 of file translator_ar.h.
    {
      return "";
    }
trBugList() [1/2]
virtual QCString TranslatorArabic::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1130 of file translator_ar.h.
    {
      return " ";
    }
trBugList() [2/2]
virtual QCString TranslatorArabic::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1130 of file translator_ar.h.
    {
      return " ";
    }
trCallGraph() [1/2]
virtual QCString TranslatorArabic::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1401 of file translator_ar.h.
    {
        return " :";
    }
trCallGraph() [2/2]
virtual QCString TranslatorArabic::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1401 of file translator_ar.h.
    {
        return " :";
    }
trClass() [1/2]
virtual QCString TranslatorArabic::trClass (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1188 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorArabic::trClass (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1188 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorArabic::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 507 of file translator_ar.h.
    {
      return "Inheritance diagram for "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorArabic::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 507 of file translator_ar.h.
    {
      return "Inheritance diagram for "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorArabic::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 376 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return " ";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorArabic::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 376 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return " ";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorArabic::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1088 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorArabic::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1088 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorArabic::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 164 of file translator_ar.h.
    { return " "; }
trClassHierarchy() [2/2]
virtual QCString TranslatorArabic::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 164 of file translator_ar.h.
    { return " "; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorArabic::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 223 of file translator_ar.h.
    { return " "
             " :";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorArabic::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 223 of file translator_ar.h.
    { return " "
             " :";
    }
trCode() [1/2]
virtual QCString TranslatorArabic::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 854 of file translator_ar.h.
    {
      return "";
    }
trCode() [2/2]
virtual QCString TranslatorArabic::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 854 of file translator_ar.h.
    {
      return "";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorArabic::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 809 of file translator_ar.h.
    {
      return " "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorArabic::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 809 of file translator_ar.h.
    {
      return " "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorArabic::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 349 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorArabic::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 349 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundList() [1/2]
virtual QCString TranslatorArabic::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 168 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorArabic::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 168 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorArabic::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 238 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " :";
      }
      else
      {
        return " "
            " :";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorArabic::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 238 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " :";
      }
      else
      {
        return " "
            " :";
      }
    }
References Config_getBool.
trCompoundMembers() [1/2]
virtual QCString TranslatorArabic::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 185 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorArabic::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 185 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorArabic::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 253 of file translator_ar.h.
    {
      QCString result=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" ";
      }
      else
      {
        result+=" ";
      }
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" / :";
        }
        else
        {
          result+=" :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="/ :";
        }
        else
        {
          result+=" :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorArabic::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 253 of file translator_ar.h.
    {
      QCString result=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" ";
      }
      else
      {
        result+=" ";
      }
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" / :";
        }
        else
        {
          result+=" :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="/ :";
        }
        else
        {
          result+=" :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundReference() [1/2]
virtual QCString TranslatorArabic::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 582 of file translator_ar.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorArabic::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 582 of file translator_ar.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorArabic::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 483 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorArabic::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 483 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorArabic::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 819 of file translator_ar.h.
    {
      return " ";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorArabic::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 819 of file translator_ar.h.
    {
      return " ";
    }
trDate() [1/2]
virtual QCString TranslatorArabic::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 521 of file translator_ar.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorArabic::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 521 of file translator_ar.h.
    { return ""; }
trDayOfWeek() [1/2]
virtual QCString TranslatorArabic::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1512 of file translator_ar.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorArabic::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1512 of file translator_ar.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayPeriod() [1/2]
virtual QCString TranslatorArabic::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1524 of file translator_ar.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorArabic::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1524 of file translator_ar.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorArabic::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 786 of file translator_ar.h.
    {
      return "Definition at line @0 of file @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorArabic::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 786 of file translator_ar.h.
    {
      return "Definition at line @0 of file @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorArabic::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 152 of file translator_ar.h.
    { return " "; }
trDefinedIn() [2/2]
virtual QCString TranslatorArabic::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 152 of file translator_ar.h.
    { return " "; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorArabic::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 790 of file translator_ar.h.
    {
      return "Definition in file @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorArabic::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 790 of file translator_ar.h.
    {
      return "Definition in file @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorArabic::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 447 of file translator_ar.h.
    { return "Define Documentation"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorArabic::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 447 of file translator_ar.h.
    { return "Define Documentation"; }
trDefines() [1/2]
virtual QCString TranslatorArabic::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 411 of file translator_ar.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorArabic::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 411 of file translator_ar.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorArabic::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1115 of file translator_ar.h.
    {
        return ":";
    }
trDefineValue() [2/2]
virtual QCString TranslatorArabic::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1115 of file translator_ar.h.
    {
        return ":";
    }
trDeprecated() [1/2]
virtual QCString TranslatorArabic::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 799 of file translator_ar.h.
    {
      return "Deprecated";
    }
trDeprecated() [2/2]
virtual QCString TranslatorArabic::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 799 of file translator_ar.h.
    {
      return "Deprecated";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorArabic::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1324 of file translator_ar.h.
    {
      return "Deprecated List";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorArabic::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1324 of file translator_ar.h.
    {
      return "Deprecated List";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorArabic::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 85 of file translator_ar.h.
    { return " "; }
trDetailedDescription() [2/2]
virtual QCString TranslatorArabic::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 85 of file translator_ar.h.
    { return " "; }
trDir() [1/2]
virtual QCString TranslatorArabic::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1491 of file translator_ar.h.
    {
      QCString result((first_capital ? "Director" : "director"));
      if (singular) result+="y"; else result+="ies";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorArabic::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1491 of file translator_ar.h.
    {
      QCString result((first_capital ? "Director" : "director"));
      if (singular) result+="y"; else result+="ies";
      return result;
    }
trDirDocumentation() [1/2]
virtual QCString TranslatorArabic::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1473 of file translator_ar.h.
    { return " "; }
trDirDocumentation() [2/2]
virtual QCString TranslatorArabic::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1473 of file translator_ar.h.
    { return " "; }
trDirectories() [1/2]
virtual QCString TranslatorArabic::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1479 of file translator_ar.h.
    { return ""; }
trDirectories() [2/2]
virtual QCString TranslatorArabic::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1479 of file translator_ar.h.
    { return ""; }
trDirIndex() [1/2]
virtual QCString TranslatorArabic::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1467 of file translator_ar.h.
    { return " "; }
trDirIndex() [2/2]
virtual QCString TranslatorArabic::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1467 of file translator_ar.h.
    { return " "; }
trDirReference() [1/2]
virtual QCString TranslatorArabic::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1485 of file translator_ar.h.
    { QCString result=" "; result+=dirName; return result; }
trDirReference() [2/2]
virtual QCString TranslatorArabic::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1485 of file translator_ar.h.
    { QCString result=" "; result+=dirName; return result; }
trDocumentation() [1/2]
virtual QCString TranslatorArabic::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 331 of file translator_ar.h.
    { return ""; }
trDocumentation() [2/2]
virtual QCString TranslatorArabic::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 331 of file translator_ar.h.
    { return ""; }
trEnumerations() [1/2]
virtual QCString TranslatorArabic::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 423 of file translator_ar.h.
    { return ""; }
trEnumerations() [2/2]
virtual QCString TranslatorArabic::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 423 of file translator_ar.h.
    { return ""; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorArabic::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 459 of file translator_ar.h.
    { return "Enumeration Type Documentation"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorArabic::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 459 of file translator_ar.h.
    { return "Enumeration Type Documentation"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorArabic::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Reimplemented from TranslatorAdapter_1_4_6.
Definition at line 465 of file translator_ar.h.
    { return "Enumerator Documentation"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorArabic::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Reimplemented from TranslatorAdapter_1_4_6.
Definition at line 465 of file translator_ar.h.
    { return "Enumerator Documentation"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorArabic::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 441 of file translator_ar.h.
    { return "Enumerator"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorArabic::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 441 of file translator_ar.h.
    { return "Enumerator"; }
trEnumName() [1/2]
virtual QCString TranslatorArabic::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 144 of file translator_ar.h.
    { return " "; }
trEnumName() [2/2]
virtual QCString TranslatorArabic::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 144 of file translator_ar.h.
    { return " "; }
trEnumValue() [1/2]
virtual QCString TranslatorArabic::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 148 of file translator_ar.h.
    { return " "; }
trEnumValue() [2/2]
virtual QCString TranslatorArabic::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 148 of file translator_ar.h.
    { return " "; }
trEventDocumentation() [1/2]
virtual QCString TranslatorArabic::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1341 of file translator_ar.h.
    {
      return " ";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorArabic::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1341 of file translator_ar.h.
    {
      return " ";
    }
trEvents() [1/2]
virtual QCString TranslatorArabic::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1336 of file translator_ar.h.
    {
      return "";
    }
trEvents() [2/2]
virtual QCString TranslatorArabic::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1336 of file translator_ar.h.
    {
      return "";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorArabic::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 401 of file translator_ar.h.
    { return " "; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorArabic::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 401 of file translator_ar.h.
    { return " "; }
trExamples() [1/2]
virtual QCString TranslatorArabic::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 215 of file translator_ar.h.
    { return ""; }
trExamples() [2/2]
virtual QCString TranslatorArabic::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 215 of file translator_ar.h.
    { return ""; }
trExamplesDescription() [1/2]
virtual QCString TranslatorArabic::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 318 of file translator_ar.h.
    { return " :"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorArabic::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 318 of file translator_ar.h.
    { return " :"; }
trExceptions() [1/2]
virtual QCString TranslatorArabic::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 537 of file translator_ar.h.
    { return ""; }
trExceptions() [2/2]
virtual QCString TranslatorArabic::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 537 of file translator_ar.h.
    { return ""; }
trFile() [1/2]
virtual QCString TranslatorArabic::trFile (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1199 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorArabic::trFile (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1199 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorArabic::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 395 of file translator_ar.h.
    { return " "; }
trFileDocumentation() [2/2]
virtual QCString TranslatorArabic::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 395 of file translator_ar.h.
    { return " "; }
trFileIndex() [1/2]
virtual QCString TranslatorArabic::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 364 of file translator_ar.h.
    { return " "; }
trFileIndex() [2/2]
virtual QCString TranslatorArabic::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 364 of file translator_ar.h.
    { return " "; }
trFileList() [1/2]
virtual QCString TranslatorArabic::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 181 of file translator_ar.h.
    { return " "; }
trFileList() [2/2]
virtual QCString TranslatorArabic::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 181 of file translator_ar.h.
    { return " "; }
trFileListDescription() [1/2]
virtual QCString TranslatorArabic::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 229 of file translator_ar.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorArabic::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 229 of file translator_ar.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorArabic::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 198 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorArabic::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 198 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorArabic::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 296 of file translator_ar.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="functions, variables, defines, enums, and typedefs";
      }
      else
      {
        result+="file members";
      }
      result+=" with links to ";
      if (extractAll)
        result+="the files they belong to:";
      else
        result+="the documentation:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorArabic::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 296 of file translator_ar.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="functions, variables, defines, enums, and typedefs";
      }
      else
      {
        result+="file members";
      }
      result+=" with links to ";
      if (extractAll)
        result+="the files they belong to:";
      else
        result+="the documentation:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorArabic::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 604 of file translator_ar.h.
    {
      QCString result=fileName;
      result+=" File Reference";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorArabic::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 604 of file translator_ar.h.
    {
      QCString result=fileName;
      result+=" File Reference";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorArabic::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 564 of file translator_ar.h.
    { return "Friends"; }
trFriends() [2/2]
virtual QCString TranslatorArabic::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 564 of file translator_ar.h.
    { return "Friends"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorArabic::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 471 of file translator_ar.h.
    { return " "; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorArabic::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 471 of file translator_ar.h.
    { return " "; }
trFunctions() [1/2]
virtual QCString TranslatorArabic::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 429 of file translator_ar.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorArabic::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 429 of file translator_ar.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorArabic::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 498 of file translator_ar.h.
    {
      QCString result="Generated on "+date;
      if (!projName.isEmpty()) result+=" for "+projName;
      result+=" by";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorArabic::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 498 of file translator_ar.h.
    {
      QCString result="Generated on "+date;
      if (!projName.isEmpty()) result+=" for "+projName;
      result+=" by";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorArabic::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 136 of file translator_ar.h.
    { QCString result=" Doxygen";
      if (!s.isEmpty()) result+=" "+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorArabic::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 136 of file translator_ar.h.
    { QCString result=" Doxygen";
      if (!s.isEmpty()) result+=" "+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorArabic::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 541 of file translator_ar.h.
    { return " "; }
trGeneratedBy() [2/2]
virtual QCString TranslatorArabic::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 541 of file translator_ar.h.
    { return " "; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorArabic::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 742 of file translator_ar.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorArabic::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 742 of file translator_ar.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorArabic::trGlobal (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1254 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorArabic::trGlobal (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1254 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorArabic::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 829 of file translator_ar.h.
    {
      return " .";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorArabic::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 829 of file translator_ar.h.
    {
      return " .";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorArabic::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 862 of file translator_ar.h.
    {
      return " ";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorArabic::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 862 of file translator_ar.h.
    {
      return " ";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorArabic::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 824 of file translator_ar.h.
    {
      return " .";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorArabic::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 824 of file translator_ar.h.
    {
      return " .";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorArabic::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 866 of file translator_ar.h.
    {
      return " ";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorArabic::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 866 of file translator_ar.h.
    {
      return " ";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorArabic::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 858 of file translator_ar.h.
    {
      return " ";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorArabic::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 858 of file translator_ar.h.
    {
      return " ";
    }
trGroup() [1/2]
virtual QCString TranslatorArabic::trGroup (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1221 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorArabic::trGroup (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1221 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorArabic::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 343 of file translator_ar.h.
    { return " "; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorArabic::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 343 of file translator_ar.h.
    { return " "; }
trImplementedFromList() [1/2]
virtual QCString TranslatorArabic::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1292 of file translator_ar.h.
    {
      return "Implements "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorArabic::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1292 of file translator_ar.h.
    {
      return "Implements "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorArabic::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1300 of file translator_ar.h.
    {
      return "Implemented in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorArabic::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1300 of file translator_ar.h.
    {
      return "Implemented in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorArabic::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 958 of file translator_ar.h.
    {
      return " "
             " :";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorArabic::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 958 of file translator_ar.h.
    {
      return " "
             " :";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorArabic::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 814 of file translator_ar.h.
    {
      return " "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorArabic::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 814 of file translator_ar.h.
    {
      return " "+fName+":";
    }
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorArabic::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 130 of file translator_ar.h.
    { return ", "; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorArabic::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 130 of file translator_ar.h.
    { return ", "; }
trInheritedByList() [1/2]
virtual QCString TranslatorArabic::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 676 of file translator_ar.h.
    {
      return "Inherited by "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorArabic::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 676 of file translator_ar.h.
    {
      return "Inherited by "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorArabic::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 668 of file translator_ar.h.
    {
      return "Inherits "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorArabic::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 668 of file translator_ar.h.
    {
      return "Inherits "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorArabic::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 849 of file translator_ar.h.
    {
        return " :";
    }
trInitialValue() [2/2]
virtual QCString TranslatorArabic::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 849 of file translator_ar.h.
    {
        return " :";
    }
trInterfaces() [1/2]
virtual QCString TranslatorArabic::trInterfaces () [inline], [virtual]
Used for Java interfaces in the summary section of Java packages
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 1083 of file translator_ar.h.
    {
      return "";
    }
trInterfaces() [2/2]
virtual QCString TranslatorArabic::trInterfaces () [inline], [virtual]
Used for Java interfaces in the summary section of Java packages
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 1083 of file translator_ar.h.
    {
      return "";
    }
trInvariant() [1/2]
virtual QCString TranslatorArabic::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 844 of file translator_ar.h.
    {
      return "";
    }
trInvariant() [2/2]
virtual QCString TranslatorArabic::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 844 of file translator_ar.h.
    {
      return "";
    }
trISOLang() [1/2]
virtual QCString TranslatorArabic::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 67 of file translator_ar.h.
    { return "ar-EG"; }
trISOLang() [2/2]
virtual QCString TranslatorArabic::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 67 of file translator_ar.h.
    { return "ar-EG"; }
trLegend() [1/2]
virtual QCString TranslatorArabic::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1043 of file translator_ar.h.
    {
      return "legend";
    }
trLegend() [2/2]
virtual QCString TranslatorArabic::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1043 of file translator_ar.h.
    {
      return "legend";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorArabic::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 980 of file translator_ar.h.
    {
      return
        "This page explains how to interpret the graphs that are generated "
        "by doxygen.<p>\n"
        "Consider the following example:\n"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "If the \\c MAX_DOT_GRAPH_HEIGHT tag in the configuration file "
        "is set to 240 this will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>%A filled black box represents the struct or class for which the "
        "graph is generated.\n"
        "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.\n"
        "<li>%A box with a red border denotes a documented struct or class for"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries.\n"
        "</ul>\n"
        "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.\n"
        "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible.\n"
        "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "the template class it was instantiated from. The arrow is labeled with "
        "the template parameters of the instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorArabic::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 980 of file translator_ar.h.
    {
      return
        "This page explains how to interpret the graphs that are generated "
        "by doxygen.<p>\n"
        "Consider the following example:\n"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "If the \\c MAX_DOT_GRAPH_HEIGHT tag in the configuration file "
        "is set to 240 this will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>%A filled black box represents the struct or class for which the "
        "graph is generated.\n"
        "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.\n"
        "<li>%A box with a red border denotes a documented struct or class for"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries.\n"
        "</ul>\n"
        "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.\n"
        "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible.\n"
        "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "the template class it was instantiated from. The arrow is labeled with "
        "the template parameters of the instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorArabic::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 973 of file translator_ar.h.
    {
      return "Graph Legend";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorArabic::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 973 of file translator_ar.h.
    {
      return "Graph Legend";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorArabic::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 118 of file translator_ar.h.
    { return " "; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorArabic::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 118 of file translator_ar.h.
    { return " "; }
trMainPage() [1/2]
virtual QCString TranslatorArabic::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 773 of file translator_ar.h.
    { return " "; }
trMainPage() [2/2]
virtual QCString TranslatorArabic::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 773 of file translator_ar.h.
    { return " "; }
trMember() [1/2]
virtual QCString TranslatorArabic::trMember (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1243 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorArabic::trMember (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1243 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorArabic::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 101 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorArabic::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 101 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorArabic::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 93 of file translator_ar.h.
    { return " "; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorArabic::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 93 of file translator_ar.h.
    { return " "; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorArabic::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 97 of file translator_ar.h.
    { return " "; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorArabic::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 97 of file translator_ar.h.
    { return " "; }
trMemberList() [1/2]
virtual QCString TranslatorArabic::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 122 of file translator_ar.h.
    { return " "; }
trMemberList() [2/2]
virtual QCString TranslatorArabic::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 122 of file translator_ar.h.
    { return " "; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorArabic::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 89 of file translator_ar.h.
    { return " "; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorArabic::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 89 of file translator_ar.h.
    { return " "; }
trModuleDocumentation() [1/2]
virtual QCString TranslatorArabic::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 370 of file translator_ar.h.
    { return " "; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorArabic::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 370 of file translator_ar.h.
    { return " "; }
trModuleIndex() [1/2]
virtual QCString TranslatorArabic::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 337 of file translator_ar.h.
    { return " "; }
trModuleIndex() [2/2]
virtual QCString TranslatorArabic::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 337 of file translator_ar.h.
    { return " "; }
trModules() [1/2]
virtual QCString TranslatorArabic::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 160 of file translator_ar.h.
    { return ""; }
trModules() [2/2]
virtual QCString TranslatorArabic::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 160 of file translator_ar.h.
    { return ""; }
trModulesDescription() [1/2]
virtual QCString TranslatorArabic::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 326 of file translator_ar.h.
    { return " :"; }
trModulesDescription() [2/2]
virtual QCString TranslatorArabic::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 326 of file translator_ar.h.
    { return " :"; }
trMonth() [1/2]
virtual QCString TranslatorArabic::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1518 of file translator_ar.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMonth() [2/2]
virtual QCString TranslatorArabic::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1518 of file translator_ar.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMore() [1/2]
virtual QCString TranslatorArabic::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 114 of file translator_ar.h.
    { return " ..."; }
trMore() [2/2]
virtual QCString TranslatorArabic::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 114 of file translator_ar.h.
    { return " ..."; }
trNamespace() [1/2]
virtual QCString TranslatorArabic::trNamespace (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1210 of file translator_ar.h.
    {
      QCString result(" ");
      if (!singular) result=" ";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorArabic::trNamespace (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1210 of file translator_ar.h.
    {
      QCString result(" ");
      if (!singular) result=" ";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorArabic::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 722 of file translator_ar.h.
    { return " "; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorArabic::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 722 of file translator_ar.h.
    { return " "; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorArabic::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 716 of file translator_ar.h.
    { return " "; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorArabic::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 716 of file translator_ar.h.
    { return " "; }
trNamespaceList() [1/2]
virtual QCString TranslatorArabic::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 549 of file translator_ar.h.
    { return " "; }
trNamespaceList() [2/2]
virtual QCString TranslatorArabic::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 549 of file translator_ar.h.
    { return " "; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorArabic::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 553 of file translator_ar.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="namespaces with brief descriptions:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorArabic::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 553 of file translator_ar.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="namespaces with brief descriptions:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorArabic::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 702 of file translator_ar.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="namespace members with links to ";
      if (extractAll)
        result+="the namespace documentation for each member:";
      else
        result+="the namespaces they belong to:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorArabic::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 702 of file translator_ar.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="namespace members with links to ";
      if (extractAll)
        result+="the namespace documentation for each member:";
      else
        result+="the namespaces they belong to:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorArabic::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 698 of file translator_ar.h.
    { return "Namespace Members"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorArabic::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 698 of file translator_ar.h.
    { return "Namespace Members"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorArabic::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 612 of file translator_ar.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Reference";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorArabic::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 612 of file translator_ar.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Reference";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorArabic::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 732 of file translator_ar.h.
    { return " "; }
trNamespaces() [2/2]
virtual QCString TranslatorArabic::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 732 of file translator_ar.h.
    { return " "; }
trNote() [1/2]
virtual QCString TranslatorArabic::trNote () [inline], [virtual]
Implements Translator.
Definition at line 879 of file translator_ar.h.
    {
      return "";
    }
trNote() [2/2]
virtual QCString TranslatorArabic::trNote () [inline], [virtual]
Implements Translator.
Definition at line 879 of file translator_ar.h.
    {
      return "";
    }
trOverloadText() [1/2]
virtual QCString TranslatorArabic::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1505 of file translator_ar.h.
    {
       return " "
              " . "
              " argument(s) .";
    }
trOverloadText() [2/2]
virtual QCString TranslatorArabic::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1505 of file translator_ar.h.
    {
       return " "
              " . "
              " argument(s) .";
    }
trPackage() [1/2]
virtual QCString TranslatorArabic::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1100 of file translator_ar.h.
    {
      return " "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorArabic::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1100 of file translator_ar.h.
    {
      return " "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorArabic::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1377 of file translator_ar.h.
    {
      return " ";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorArabic::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1377 of file translator_ar.h.
    {
      return " ";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorArabic::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1359 of file translator_ar.h.
    {
      return " ";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorArabic::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1359 of file translator_ar.h.
    {
      return " ";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorArabic::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1105 of file translator_ar.h.
    {
        return ") (:";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorArabic::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1105 of file translator_ar.h.
    {
        return ") (:";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorArabic::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1363 of file translator_ar.h.
    {
      return " ";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorArabic::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1363 of file translator_ar.h.
    {
      return " ";
    }
trPackages() [1/2]
virtual QCString TranslatorArabic::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1110 of file translator_ar.h.
    {
      return "";
    }
trPackages() [2/2]
virtual QCString TranslatorArabic::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1110 of file translator_ar.h.
    {
      return "";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorArabic::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1352 of file translator_ar.h.
    {
      return " ";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorArabic::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1352 of file translator_ar.h.
    {
      return " ";
    }
trPage() [1/2]
virtual QCString TranslatorArabic::trPage (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorArabic::trPage (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_ar.h.
    {
      QCString result("");
      if (!singular) result="";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorArabic::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 779 of file translator_ar.h.
    { return "."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorArabic::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 779 of file translator_ar.h.
    { return "."; }
trPageIndex() [1/2]
virtual QCString TranslatorArabic::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 870 of file translator_ar.h.
    {
      return " ";
    }
trPageIndex() [2/2]
virtual QCString TranslatorArabic::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 870 of file translator_ar.h.
    {
      return " ";
    }
trParameters() [1/2]
virtual QCString TranslatorArabic::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 533 of file translator_ar.h.
    { return "Parameters"; }
trParameters() [2/2]
virtual QCString TranslatorArabic::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 533 of file translator_ar.h.
    { return "Parameters"; }
trPostcondition() [1/2]
virtual QCString TranslatorArabic::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 839 of file translator_ar.h.
    {
      return " ";
    }
trPostcondition() [2/2]
virtual QCString TranslatorArabic::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 839 of file translator_ar.h.
    {
      return " ";
    }
trPrecondition() [1/2]
virtual QCString TranslatorArabic::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 834 of file translator_ar.h.
    {
      return " ";
    }
trPrecondition() [2/2]
virtual QCString TranslatorArabic::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 834 of file translator_ar.h.
    {
      return " ";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorArabic::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 918 of file translator_ar.h.
    {
      return " ";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorArabic::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 918 of file translator_ar.h.
    {
      return " ";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorArabic::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 633 of file translator_ar.h.
    { return "Private Member Functions"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorArabic::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 633 of file translator_ar.h.
    { return "Private Member Functions"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorArabic::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 635 of file translator_ar.h.
    { return "Private Slots"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorArabic::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 635 of file translator_ar.h.
    { return "Private Slots"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorArabic::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 914 of file translator_ar.h.
    {
      return " ";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorArabic::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 914 of file translator_ar.h.
    {
      return " ";
    }
trProperties() [1/2]
virtual QCString TranslatorArabic::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1068 of file translator_ar.h.
    {
      return "";
    }
trProperties() [2/2]
virtual QCString TranslatorArabic::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1068 of file translator_ar.h.
    {
      return "";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorArabic::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1073 of file translator_ar.h.
    {
      return " ";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorArabic::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1073 of file translator_ar.h.
    {
      return " ";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorArabic::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 906 of file translator_ar.h.
    {
      return " ";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorArabic::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 906 of file translator_ar.h.
    {
      return " ";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorArabic::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 627 of file translator_ar.h.
    { return "Protected Member Functions"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorArabic::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 627 of file translator_ar.h.
    { return "Protected Member Functions"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorArabic::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 629 of file translator_ar.h.
    { return "Protected Slots"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorArabic::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 629 of file translator_ar.h.
    { return "Protected Slots"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorArabic::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_ar.h.
    {
      return " ";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorArabic::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_ar.h.
    {
      return " ";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorArabic::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 887 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorArabic::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 887 of file translator_ar.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorArabic::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 619 of file translator_ar.h.
    { return "Public Member Functions"; }
trPublicMembers() [2/2]
virtual QCString TranslatorArabic::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 619 of file translator_ar.h.
    { return "Public Member Functions"; }
trPublicSlots() [1/2]
virtual QCString TranslatorArabic::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 621 of file translator_ar.h.
    { return "Public Slots"; }
trPublicSlots() [2/2]
virtual QCString TranslatorArabic::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 621 of file translator_ar.h.
    { return "Public Slots"; }
trPublicTypes() [1/2]
virtual QCString TranslatorArabic::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 883 of file translator_ar.h.
    {
      return " ";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorArabic::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 883 of file translator_ar.h.
    {
      return " ";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorArabic::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 946 of file translator_ar.h.
    {
      return " ";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorArabic::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 946 of file translator_ar.h.
    {
      return " ";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorArabic::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 405 of file translator_ar.h.
    { return " "; }
trReferenceManual() [2/2]
virtual QCString TranslatorArabic::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 405 of file translator_ar.h.
    { return " "; }
trReferences() [1/2]
virtual QCString TranslatorArabic::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1280 of file translator_ar.h.
    {
      return "";
    }
trReferences() [2/2]
virtual QCString TranslatorArabic::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1280 of file translator_ar.h.
    {
      return "";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorArabic::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 684 of file translator_ar.h.
    {
      return "Reimplemented from "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorArabic::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 684 of file translator_ar.h.
    {
      return "Reimplemented from "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorArabic::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 692 of file translator_ar.h.
    {
      return "Reimplemented in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorArabic::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 692 of file translator_ar.h.
    {
      return "Reimplemented in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorArabic::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 574 of file translator_ar.h.
    { return "Friends And Related Function Documentation"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorArabic::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 574 of file translator_ar.h.
    { return "Friends And Related Function Documentation"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorArabic::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 77 of file translator_ar.h.
    { return " "; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorArabic::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 77 of file translator_ar.h.
    { return " "; }
trRelatedPages() [1/2]
virtual QCString TranslatorArabic::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 211 of file translator_ar.h.
    { return " "; }
trRelatedPages() [2/2]
virtual QCString TranslatorArabic::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 211 of file translator_ar.h.
    { return " "; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorArabic::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 322 of file translator_ar.h.
    { return " :"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorArabic::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 322 of file translator_ar.h.
    { return " :"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorArabic::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 81 of file translator_ar.h.
    { return "()"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorArabic::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 81 of file translator_ar.h.
    { return "()"; }
trRemarks() [1/2]
virtual QCString TranslatorArabic::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 950 of file translator_ar.h.
    {
      return "";
    }
trRemarks() [2/2]
virtual QCString TranslatorArabic::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 950 of file translator_ar.h.
    {
      return "";
    }
trReturns() [1/2]
virtual QCString TranslatorArabic::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 525 of file translator_ar.h.
    { return "Returns"; }
trReturns() [2/2]
virtual QCString TranslatorArabic::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 525 of file translator_ar.h.
    { return "Returns"; }
trReturnValues() [1/2]
virtual QCString TranslatorArabic::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 768 of file translator_ar.h.
    { return " "; }
trReturnValues() [2/2]
virtual QCString TranslatorArabic::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 768 of file translator_ar.h.
    { return " "; }
trRTFansicp() [1/2]
virtual QCString TranslatorArabic::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1164 of file translator_ar.h.
    {
      return "1256";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorArabic::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1164 of file translator_ar.h.
    {
      return "1256";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorArabic::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1173 of file translator_ar.h.
    {
      return "178";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorArabic::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1173 of file translator_ar.h.
    {
      return "178";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorArabic::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1179 of file translator_ar.h.
    {
      return "";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorArabic::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1179 of file translator_ar.h.
    {
      return "";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorArabic::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1312 of file translator_ar.h.
    {
      return " ";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorArabic::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1312 of file translator_ar.h.
    {
      return " ";
    }
trSearch() [1/2]
virtual QCString TranslatorArabic::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 219 of file translator_ar.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorArabic::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 219 of file translator_ar.h.
    { return ""; }
trSearchMatches() [1/2]
virtual QCString TranslatorArabic::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1444 of file translator_ar.h.
    {
        return " :";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorArabic::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1444 of file translator_ar.h.
    {
        return " :";
    }
trSearchResults() [1/2]
virtual QCString TranslatorArabic::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1425 of file translator_ar.h.
    {
      if (numDocuments==0)
      {
        return " .";
      }
      else if (numDocuments==1)
      {
        return " . <b>1</b> .";
      }
      else
      {
        return " <b>$num</b> ."
               " .";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorArabic::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1425 of file translator_ar.h.
    {
      if (numDocuments==0)
      {
        return " .";
      }
      else if (numDocuments==1)
      {
        return " . <b>1</b> .";
      }
      else
      {
        return " <b>$num</b> ."
               " .";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorArabic::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1413 of file translator_ar.h.
    {
      return " ";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorArabic::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1413 of file translator_ar.h.
    {
      return " ";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorArabic::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 529 of file translator_ar.h.
    { return " "; }
trSeeAlso() [2/2]
virtual QCString TranslatorArabic::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 529 of file translator_ar.h.
    { return " "; }
trSignals() [1/2]
virtual QCString TranslatorArabic::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 623 of file translator_ar.h.
    { return "Signals"; }
trSignals() [2/2]
virtual QCString TranslatorArabic::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 623 of file translator_ar.h.
    { return "Signals"; }
trSince() [1/2]
virtual QCString TranslatorArabic::trSince () [inline], [virtual]
Implements Translator.
Definition at line 963 of file translator_ar.h.
    {
      return "";
    }
trSince() [2/2]
virtual QCString TranslatorArabic::trSince () [inline], [virtual]
Implements Translator.
Definition at line 963 of file translator_ar.h.
    {
      return "";
    }
trSourceFile() [1/2]
virtual QCString TranslatorArabic::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1455 of file translator_ar.h.
    {
      return " " + filename ;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorArabic::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1455 of file translator_ar.h.
    {
      return " " + filename ;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorArabic::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1384 of file translator_ar.h.
    {
      return " ";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorArabic::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1384 of file translator_ar.h.
    {
      return " ";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorArabic::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1370 of file translator_ar.h.
    {
      return " ";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorArabic::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1370 of file translator_ar.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorArabic::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 922 of file translator_ar.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorArabic::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 922 of file translator_ar.h.
    {
      return " ";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorArabic::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 637 of file translator_ar.h.
    { return "Static Private Member Functions"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorArabic::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 637 of file translator_ar.h.
    { return "Static Private Member Functions"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorArabic::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_ar.h.
    {
      return " ";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorArabic::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_ar.h.
    {
      return " ";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorArabic::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 631 of file translator_ar.h.
    { return "Static Protected Member Functions"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorArabic::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 631 of file translator_ar.h.
    { return "Static Protected Member Functions"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorArabic::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 898 of file translator_ar.h.
    {
      return " ";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorArabic::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 898 of file translator_ar.h.
    {
      return " ";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorArabic::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 625 of file translator_ar.h.
    { return "Static Public Member Functions"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorArabic::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 625 of file translator_ar.h.
    { return "Static Public Member Functions"; }
trTest() [1/2]
virtual QCString TranslatorArabic::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1053 of file translator_ar.h.
    {
      return "";
    }
trTest() [2/2]
virtual QCString TranslatorArabic::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1053 of file translator_ar.h.
    {
      return "";
    }
trTestList() [1/2]
virtual QCString TranslatorArabic::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1058 of file translator_ar.h.
    {
      return " ";
    }
trTestList() [2/2]
virtual QCString TranslatorArabic::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1058 of file translator_ar.h.
    {
      return " ";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorArabic::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 126 of file translator_ar.h.
    { return " "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorArabic::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 126 of file translator_ar.h.
    { return " "; }
trTodo() [1/2]
virtual QCString TranslatorArabic::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 932 of file translator_ar.h.
    {
      return "";
    }
trTodo() [2/2]
virtual QCString TranslatorArabic::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 932 of file translator_ar.h.
    {
      return "";
    }
trTodoList() [1/2]
virtual QCString TranslatorArabic::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 937 of file translator_ar.h.
    {
      return " ";
    }
trTodoList() [2/2]
virtual QCString TranslatorArabic::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 937 of file translator_ar.h.
    {
      return " ";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorArabic::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 453 of file translator_ar.h.
    { return "Typedef Documentation"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorArabic::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 453 of file translator_ar.h.
    { return "Typedef Documentation"; }
trTypedefs() [1/2]
virtual QCString TranslatorArabic::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 417 of file translator_ar.h.
    { return "Typedefs"; }
trTypedefs() [2/2]
virtual QCString TranslatorArabic::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 417 of file translator_ar.h.
    { return "Typedefs"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorArabic::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 477 of file translator_ar.h.
    { return " "; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorArabic::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 477 of file translator_ar.h.
    { return " "; }
trVariables() [1/2]
virtual QCString TranslatorArabic::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 435 of file translator_ar.h.
    { return ""; }
trVariables() [2/2]
virtual QCString TranslatorArabic::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 435 of file translator_ar.h.
    { return ""; }
trVersion() [1/2]
virtual QCString TranslatorArabic::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 517 of file translator_ar.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorArabic::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 517 of file translator_ar.h.
    { return ""; }
trWarning() [1/2]
virtual QCString TranslatorArabic::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 513 of file translator_ar.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorArabic::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 513 of file translator_ar.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorArabic::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 643 of file translator_ar.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", and ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorArabic::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 643 of file translator_ar.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", and ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_ar.h
doxygen/src/translator_ar.h