DocSeparator Class Reference
#include <docnode.h>
Public Member Functions
DocSeparator (DocParser *parser, DocNodeVariant *parent, const QCString &chars)
QCString chars () const
DocSeparator (DocParser *parser, DocNodeVariant *parent, const QCString &chars)
QCString chars () const
Private Attributes
QCString m_chars
Additional Inherited Members
Detailed Description
Node representing a separator
Definition at line 338 of file docnode.h.
Constructor & Destructor Documentation
DocSeparator() [1/2]
DocSeparator::DocSeparator (DocParser * parser, DocNodeVariant * parent, const QCString & chars) [inline]
Definition at line 341 of file docnode.h.
      : DocNode(parser,parent), m_chars(chars) {}
DocSeparator() [2/2]
DocSeparator::DocSeparator (DocParser * parser, DocNodeVariant * parent, const QCString & chars) [inline]
Definition at line 341 of file docnode.h.
      : DocNode(parser,parent), m_chars(chars) {}
Member Function Documentation
chars() [1/2]
QCString DocSeparator::chars () const [inline]
Definition at line 343 of file docnode.h.
{ return m_chars; }
References m_chars.
Referenced by DocbookDocVisitor::operator()(), LatexDocVisitor::operator()(), and RTFDocVisitor::operator()().
chars() [2/2]
QCString DocSeparator::chars () const [inline]
Definition at line 343 of file docnode.h.
{ return m_chars; }
References m_chars.
Member Data Documentation
m_chars
QCString DocSeparator::m_chars [private]
Definition at line 345 of file docnode.h.
Referenced by chars().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h