DocbookGenerator Class Reference
#include <docbookgen.h>
Public Member Functions
DocbookGenerator ()
DocbookGenerator (const DocbookGenerator &o)
DocbookGenerator & operator= (const DocbookGenerator &o)
virtual ~DocbookGenerator ()
virtual std::unique_ptr< OutputGenerator > clone () const
void cleanup ()
OutputType type () const
void codify (const QCString &text)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void startCodeLine (bool hasLineNumbers)
void endCodeLine ()
void startFontClass (const QCString &s)
void endFontClass ()
void writeCodeAnchor (const QCString &anchor)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
void writeDoc (const IDocNodeAST *node, const Definition *ctx, const MemberDef *md, int id)
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id)
void writeSearchInfo ()
void writeFooter (const QCString &)
void endFile ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const QCString &, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int)
void startTitleHead (const QCString &)
void endTitleHead (const QCString &fileName, const QCString &name)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const QCString &, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const QCString &, const QCString &)
void endIndexItem (const QCString &, const QCString &)
void startItemListItem ()
void endItemListItem ()
void docify (const QCString &text)
void writeChar (char)
void writeString (const QCString &)
void startParagraph (const QCString &)
void endParagraph ()
void writeObjectLink (const QCString &, const QCString &, const QCString &, const QCString &)
void startHtmlLink (const QCString &)
void endHtmlLink ()
void startBold ()
void endBold ()
void startTypewriter ()
void endTypewriter ()
void startEmphasis ()
void endEmphasis ()
void writeRuler ()
void startDescription ()
void endDescription ()
void startDescItem ()
void startDescForItem ()
void endDescForItem ()
void endDescItem ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startExamples ()
void endExamples ()
void startParamList (BaseOutputDocInterface::ParamListTypes, const QCString &)
void endParamList ()
void startTitle ()
void endTitle ()
void writeAnchor (const QCString &, const QCString &)
void startSection (const QCString &, const QCString &, SectionType)
void endSection (const QCString &, SectionType)
void lineBreak (const QCString &)
void addIndexItem (const QCString &, const QCString &)
void writeNonBreakableSpace (int)
void startDescTable (const QCString &)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startTextLink (const QCString &, const QCString &)
void endTextLink ()
void startPageRef ()
void endPageRef (const QCString &, const QCString &)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startGroupHeader (int)
void endGroupHeader (int)
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const QCString &anchor, int typ)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const QCString &, int, const QCString &)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const QCString &, const QCString &)
void startCompoundTemplateParams ()
void endCompoundTemplateParams ()
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void insertMemberAlign (bool)
void insertMemberAlignLeft (int, bool)
void startMemberDoc (const QCString &, const QCString &, const QCString &, const QCString &, int, int, bool)
void endMemberDoc (bool)
void startDoxyAnchor (const QCString &fName, const QCString &manName, const QCString &anchor, const QCString &name, const QCString &args)
void endDoxyAnchor (const QCString &fileName, const QCString &anchor)
void writeLatexSpacing ()
void writeStartAnnoItem (const QCString &, const QCString &, const QCString &, const QCString &)
void writeEndAnnoItem (const QCString &)
void startMemberDescription (const QCString &, const QCString &, bool)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const QCString &, const QCString &)
void writeInheritedSectionTitle (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const QCString &, const QCString &)
void startDotGraph ()
void endDotGraph (DotClassGraph &g)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &g)
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &g)
void startCallGraph ()
void endCallGraph (DotCallGraph &g)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &g)
void writeGraphicalHierarchy (DotGfxHierarchyTable &)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const QCString &)
void writeNavigationPath (const QCString &)
void writeLogo ()
void writeQuickLinks (bool, HighlightedItem, const QCString &)
void writeSummaryLink (const QCString &, const QCString &, const QCString &, bool)
void startContents ()
void endContents ()
void startPageDoc (const QCString &)
void endPageDoc ()
void startTextBlock (bool)
void endTextBlock (bool)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool, const QCString &)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool, bool, bool)
void startParameterList (bool)
void endParameterList ()
void exceptionEntry (const QCString &, bool)
void startConstraintList (const QCString &)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const QCString &, bool)
void endLabels ()
void setCurrentDoc (const Definition *, const QCString &, bool)
void addWord (const QCString &, bool)
DocbookGenerator ()
DocbookGenerator (const DocbookGenerator &o)
DocbookGenerator & operator= (const DocbookGenerator &o)
virtual ~DocbookGenerator ()
virtual std::unique_ptr< OutputGenerator > clone () const
void cleanup ()
OutputType type () const
void codify (const QCString &text)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void startCodeLine (bool hasLineNumbers)
void endCodeLine ()
void startFontClass (const QCString &s)
void endFontClass ()
void writeCodeAnchor (const QCString &anchor)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
void writeDoc (const IDocNodeAST *node, const Definition *ctx, const MemberDef *md, int id)
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id)
void writeSearchInfo ()
void writeFooter (const QCString &)
void endFile ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const QCString &, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int)
void startTitleHead (const QCString &)
void endTitleHead (const QCString &fileName, const QCString &name)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const QCString &, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const QCString &, const QCString &)
void endIndexItem (const QCString &, const QCString &)
void startItemListItem ()
void endItemListItem ()
void docify (const QCString &text)
void writeChar (char)
void writeString (const QCString &)
void startParagraph (const QCString &)
void endParagraph ()
void writeObjectLink (const QCString &, const QCString &, const QCString &, const QCString &)
void startHtmlLink (const QCString &)
void endHtmlLink ()
void startBold ()
void endBold ()
void startTypewriter ()
void endTypewriter ()
void startEmphasis ()
void endEmphasis ()
void writeRuler ()
void startDescription ()
void endDescription ()
void startDescItem ()
void startDescForItem ()
void endDescForItem ()
void endDescItem ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startExamples ()
void endExamples ()
void startParamList (BaseOutputDocInterface::ParamListTypes, const QCString &)
void endParamList ()
void startTitle ()
void endTitle ()
void writeAnchor (const QCString &, const QCString &)
void startSection (const QCString &, const QCString &, SectionType)
void endSection (const QCString &, SectionType)
void lineBreak (const QCString &)
void addIndexItem (const QCString &, const QCString &)
void writeNonBreakableSpace (int)
void startDescTable (const QCString &)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startTextLink (const QCString &, const QCString &)
void endTextLink ()
void startPageRef ()
void endPageRef (const QCString &, const QCString &)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startGroupHeader (int)
void endGroupHeader (int)
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const QCString &anchor, int typ)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const QCString &, int, const QCString &)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const QCString &, const QCString &)
void startCompoundTemplateParams ()
void endCompoundTemplateParams ()
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void insertMemberAlign (bool)
void insertMemberAlignLeft (int, bool)
void startMemberDoc (const QCString &, const QCString &, const QCString &, const QCString &, int, int, bool)
void endMemberDoc (bool)
void startDoxyAnchor (const QCString &fName, const QCString &manName, const QCString &anchor, const QCString &name, const QCString &args)
void endDoxyAnchor (const QCString &fileName, const QCString &anchor)
void writeLatexSpacing ()
void writeStartAnnoItem (const QCString &, const QCString &, const QCString &, const QCString &)
void writeEndAnnoItem (const QCString &)
void startMemberDescription (const QCString &, const QCString &, bool)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const QCString &, const QCString &)
void writeInheritedSectionTitle (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const QCString &, const QCString &)
void startDotGraph ()
void endDotGraph (DotClassGraph &g)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &g)
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &g)
void startCallGraph ()
void endCallGraph (DotCallGraph &g)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &g)
void writeGraphicalHierarchy (DotGfxHierarchyTable &)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const QCString &)
void writeNavigationPath (const QCString &)
void writeLogo ()
void writeQuickLinks (bool, HighlightedItem, const QCString &)
void writeSummaryLink (const QCString &, const QCString &, const QCString &, bool)
void startContents ()
void endContents ()
void startPageDoc (const QCString &)
void endPageDoc ()
void startTextBlock (bool)
void endTextBlock (bool)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool, const QCString &)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool, bool, bool)
void startParameterList (bool)
void endParameterList ()
void exceptionEntry (const QCString &, bool)
void startConstraintList (const QCString &)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const QCString &, bool)
void endLabels ()
void setCurrentDoc (const Definition *, const QCString &, bool)
void addWord (const QCString &, bool)
Static Public Member Functions
static void init ()
static void init ()
Private Member Functions
void openSection (const QCString &attr=QCString())
void closeSection ()
void closeAllSections ()
void openSection (const QCString &attr=QCString())
void closeSection ()
void closeAllSections ()
Private Attributes
QCString relPath
DocbookCodeGenerator m_codeGen
bool m_denseText = false
bool m_inGroup = false
int m_levelListItem = 0
bool m_inListItem [20] = { false, }
bool m_inSimpleSect [20] = { false, }
bool m_descTable = false
bool m_simpleTable = false
int m_inLevel = -1
bool m_firstMember = false
int m_openSectionCount = 0
Additional Inherited Members
Detailed Description
Definition at line 90 of file docbookgen.h.
Constructor & Destructor Documentation
DocbookGenerator() [1/4]
DocbookGenerator::DocbookGenerator ()
Definition at line 276 of file docbookgen.cpp.
                                   : OutputGenerator(Config_getString(DOCBOOK_OUTPUT)), m_codeGen(m_t)
{
DB_GEN_C
}
References DB_GEN_C.
DocbookGenerator() [2/4]
DocbookGenerator::DocbookGenerator (const DocbookGenerator & o)
Definition at line 281 of file docbookgen.cpp.
                                                             : OutputGenerator(og), m_codeGen(m_t)
{
}
 DocbookGenerator() [1/2]
DocbookGenerator::~DocbookGenerator () [virtual]
Definition at line 296 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
DocbookGenerator() [3/4]
DocbookGenerator::DocbookGenerator ()
DocbookGenerator() [4/4]
DocbookGenerator::DocbookGenerator (const DocbookGenerator & o)
 DocbookGenerator() [2/2]
virtual DocbookGenerator::~DocbookGenerator () [virtual]
Member Function Documentation
addIndexItem() [1/2]
void DocbookGenerator::addIndexItem (const QCString & prim, const QCString & sec) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1005 of file docbookgen.cpp.
{
DB_GEN_C
  addIndexTerm(m_t, prim, sec);
}
References addIndexTerm(), DB_GEN_C, and OutputGenerator::m_t.
addIndexItem() [2/2]
void DocbookGenerator::addIndexItem (const QCString & , const QCString &) [virtual]
Implements BaseOutputDocInterface.
addWord() [1/2]
void DocbookGenerator::addWord (const QCString & , bool) [inline], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 337 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
addWord() [2/2]
void DocbookGenerator::addWord (const QCString & , bool) [inline], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 337 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
cleanup() [1/2]
void DocbookGenerator::cleanup () [virtual]
Implements OutputGenerator.
Definition at line 312 of file docbookgen.cpp.
{
  QCString dname = Config_getString(DOCBOOK_OUTPUT);
  Dir d(dname.str());
  clearSubDirs(d);
}
References clearSubDirs(), Config_getString, and QCString::str().
cleanup() [2/2]
void DocbookGenerator::cleanup () [virtual]
Implements OutputGenerator.
clone() [1/2]
std::unique_ptr< OutputGenerator > DocbookGenerator::clone () const [virtual]
Implements OutputGenerator.
Definition at line 291 of file docbookgen.cpp.
{
  return std::make_unique<DocbookGenerator>(*this);
}
clone() [2/2]
virtual std::unique_ptr< OutputGenerator > DocbookGenerator::clone () const [virtual]
Implements OutputGenerator.
closeAllSections() [1/2]
void DocbookGenerator::closeAllSections () [private]
Definition at line 1248 of file docbookgen.cpp.
{
  while (m_openSectionCount>0)
  {
    closeSection();
  }
}
References closeSection(), and m_openSectionCount.
Referenced by endFile().
closeAllSections() [2/2]
void DocbookGenerator::closeAllSections () [private]
closeSection() [1/2]
void DocbookGenerator::closeSection () [private]
Definition at line 1242 of file docbookgen.cpp.
{
   m_t << "</section>\n";
   m_openSectionCount--;
}
References m_openSectionCount, and OutputGenerator::m_t.
Referenced by closeAllSections(), endSection(), startDoxyAnchor(), startGroupHeader(), and writeRuler().
closeSection() [2/2]
void DocbookGenerator::closeSection () [private]
codify() [1/2]
void DocbookGenerator::codify (const QCString & s) [inline], [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 105 of file docbookgen.h.
    { m_codeGen.codify(text); }
References DocbookCodeGenerator::codify(), and m_codeGen.
codify() [2/2]
void DocbookGenerator::codify (const QCString & s) [inline], [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 105 of file docbookgen.h.
    { m_codeGen.codify(text); }
References DocbookCodeGenerator::codify(), and m_codeGen.
docify() [1/2]
void DocbookGenerator::docify (const QCString & s) [virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
Definition at line 666 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << convertToDocBook(str);
}
References convertToDocBook(), DB_GEN_C, and OutputGenerator::m_t.
Referenced by startConstraintList(), startExamples(), writeChar(), and writeObjectLink().
docify() [2/2]
void DocbookGenerator::docify (const QCString & s) [virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
endAnonTypeScope() [1/2]
void DocbookGenerator::endAnonTypeScope (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 239 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endAnonTypeScope() [2/2]
void DocbookGenerator::endAnonTypeScope (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 239 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endBold() [1/2]
void DocbookGenerator::endBold () [virtual]
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 720 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</emphasis>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endBold() [2/2]
void DocbookGenerator::endBold () [virtual]
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
endCallGraph() [1/2]
void DocbookGenerator::endCallGraph (DotCallGraph & g) [virtual]
Implements OutputGenerator.
Definition at line 1171 of file docbookgen.cpp.
{
DB_GEN_C
  QCString fn = g.writeGraph(m_t,GOF_BITMAP,EOF_DocBook,dir(),fileName(),relPath,FALSE);
}
References DB_GEN_C, OutputGenerator::dir(), EOF_DocBook, FALSE, OutputGenerator::fileName(), g, GOF_BITMAP, OutputGenerator::m_t, and relPath.
endCallGraph() [2/2]
void DocbookGenerator::endCallGraph (DotCallGraph & g) [virtual]
Implements OutputGenerator.
endCenter() [1/2]
void DocbookGenerator::endCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 189 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endCenter() [2/2]
void DocbookGenerator::endCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 189 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endClassDiagram() [1/2]
void DocbookGenerator::endClassDiagram (const ClassDiagram & d, const QCString & fileName, const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 885 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << " <informalfigure>\n";
  m_t << " <mediaobject>\n";
  m_t << " <imageobject>\n";
  m_t << " <imagedata width=\"50%\" align=\"center\" valign=\"middle\" scalefit=\"0\" fileref=\""
                         << relPath << fileName << ".png\">" << "</imagedata>\n";
  m_t << " </imageobject>\n";
  d.writeImage(m_t,dir(),relPath,fileName,FALSE);
  m_t << " </mediaobject>\n";
  m_t << " </informalfigure>\n";
  m_t << "</para>\n";
}
References DB_GEN_C, OutputGenerator::dir(), FALSE, OutputGenerator::fileName(), OutputGenerator::m_t, relPath, and ClassDiagram::writeImage().
endClassDiagram() [2/2]
void DocbookGenerator::endClassDiagram (const ClassDiagram & , const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
endCodeFragment() [1/2]
void DocbookGenerator::endCodeFragment (const QCString & style) [inline], [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 130 of file docbookgen.h.
    { m_codeGen.endCodeFragment(style); }
References DocbookCodeGenerator::endCodeFragment(), m_codeGen, and style.
endCodeFragment() [2/2]
void DocbookGenerator::endCodeFragment (const QCString & style) [inline], [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 130 of file docbookgen.h.
    { m_codeGen.endCodeFragment(style); }
References DocbookCodeGenerator::endCodeFragment(), m_codeGen, and style.
endCodeLine() [1/2]
void DocbookGenerator::endCodeLine () [inline], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 120 of file docbookgen.h.
    { m_codeGen.endCodeLine(); }
References DocbookCodeGenerator::endCodeLine(), and m_codeGen.
endCodeLine() [2/2]
void DocbookGenerator::endCodeLine () [inline], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 120 of file docbookgen.h.
    { m_codeGen.endCodeLine(); }
References DocbookCodeGenerator::endCodeLine(), and m_codeGen.
endCompoundTemplateParams() [1/2]
void DocbookGenerator::endCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 245 of file docbookgen.h.
{ endSubsubsection(); }
References endSubsubsection().
endCompoundTemplateParams() [2/2]
void DocbookGenerator::endCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 245 of file docbookgen.h.
{ endSubsubsection(); }
References endSubsubsection().
endConstraintDocs() [1/2]
void DocbookGenerator::endConstraintDocs () [virtual]
Implements OutputGenerator.
Definition at line 1224 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endConstraintDocs() [2/2]
void DocbookGenerator::endConstraintDocs () [virtual]
Implements OutputGenerator.
endConstraintList() [1/2]
void DocbookGenerator::endConstraintList () [virtual]
Implements OutputGenerator.
Definition at line 1228 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</simplesect>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endConstraintList() [2/2]
void DocbookGenerator::endConstraintList () [virtual]
Implements OutputGenerator.
endConstraintParam() [1/2]
void DocbookGenerator::endConstraintParam () [virtual]
Implements OutputGenerator.
Definition at line 1206 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endConstraintParam() [2/2]
void DocbookGenerator::endConstraintParam () [virtual]
Implements OutputGenerator.
endConstraintType() [1/2]
void DocbookGenerator::endConstraintType () [virtual]
Implements OutputGenerator.
Definition at line 1215 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</emphasis></para>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endConstraintType() [2/2]
void DocbookGenerator::endConstraintType () [virtual]
Implements OutputGenerator.
endContents() [1/2]
void DocbookGenerator::endContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 296 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endContents() [2/2]
void DocbookGenerator::endContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 296 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endDescForItem() [1/2]
void DocbookGenerator::endDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 186 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endDescForItem() [2/2]
void DocbookGenerator::endDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 186 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endDescItem() [1/2]
void DocbookGenerator::endDescItem () [inline], [virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 187 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endDescItem() [2/2]
void DocbookGenerator::endDescItem () [inline], [virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 187 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endDescription() [1/2]
void DocbookGenerator::endDescription () [inline], [virtual]
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 183 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endDescription() [2/2]
void DocbookGenerator::endDescription () [inline], [virtual]
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 183 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endDescTable() [1/2]
void DocbookGenerator::endDescTable () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1097 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << " </tbody>\n";
  m_t << " </tgroup>\n";
  m_t << "</informaltable>\n";
  m_descTable = FALSE;
}
References DB_GEN_C, FALSE, m_descTable, and OutputGenerator::m_t.
endDescTable() [2/2]
void DocbookGenerator::endDescTable () [virtual]
Implements BaseOutputDocInterface.
endDescTableData() [1/2]
void DocbookGenerator::endDescTableData () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1135 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endDescTableData() [2/2]
void DocbookGenerator::endDescTableData () [virtual]
Implements BaseOutputDocInterface.
endDescTableRow() [1/2]
void DocbookGenerator::endDescTableRow () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1113 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</row>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endDescTableRow() [2/2]
void DocbookGenerator::endDescTableRow () [virtual]
Implements BaseOutputDocInterface.
endDescTableTitle() [1/2]
void DocbookGenerator::endDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1124 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endDescTableTitle() [2/2]
void DocbookGenerator::endDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
endDirDepGraph() [1/2]
void DocbookGenerator::endDirDepGraph (DotDirDeps & g) [virtual]
Implements OutputGenerator.
Definition at line 1180 of file docbookgen.cpp.
{
DB_GEN_C
  QCString fn = g.writeGraph(m_t,GOF_BITMAP,EOF_DocBook,dir(),fileName(),relPath,FALSE);
}
References DB_GEN_C, OutputGenerator::dir(), EOF_DocBook, FALSE, OutputGenerator::fileName(), g, GOF_BITMAP, OutputGenerator::m_t, and relPath.
endDirDepGraph() [2/2]
void DocbookGenerator::endDirDepGraph (DotDirDeps & g) [virtual]
Implements OutputGenerator.
endDotGraph() [1/2]
void DocbookGenerator::endDotGraph (DotClassGraph & g) [virtual]
Implements OutputGenerator.
Definition at line 1153 of file docbookgen.cpp.
{
DB_GEN_C
  g.writeGraph(m_t,GOF_BITMAP,EOF_DocBook,dir(),fileName(),relPath,TRUE,FALSE);
}
References DB_GEN_C, OutputGenerator::dir(), EOF_DocBook, FALSE, OutputGenerator::fileName(), g, GOF_BITMAP, OutputGenerator::m_t, relPath, and TRUE.
endDotGraph() [2/2]
void DocbookGenerator::endDotGraph (DotClassGraph & g) [virtual]
Implements OutputGenerator.
endDoxyAnchor() [1/2]
void DocbookGenerator::endDoxyAnchor (const QCString & fileName, const QCString & anchor) [virtual]
Implements OutputGenerator.
Definition at line 847 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endDoxyAnchor() [2/2]
void DocbookGenerator::endDoxyAnchor (const QCString & fileName, const QCString & anchor) [virtual]
Implements OutputGenerator.
endEmphasis() [1/2]
void DocbookGenerator::endEmphasis () [inline], [virtual]
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 180 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endEmphasis() [2/2]
void DocbookGenerator::endEmphasis () [inline], [virtual]
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 180 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endExamples() [1/2]
void DocbookGenerator::endExamples () [virtual]
Implements BaseOutputDocInterface.
Definition at line 923 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</simplesect>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endExamples() [2/2]
void DocbookGenerator::endExamples () [virtual]
Implements BaseOutputDocInterface.
endFile() [1/2]
void DocbookGenerator::endFile () [virtual]
Implements OutputGenerator.
Definition at line 350 of file docbookgen.cpp.
{
DB_GEN_C
  closeAllSections();
  m_inLevel = -1;
  m_inGroup = FALSE;
  QCString fileType="section";
  QCString fileName= m_codeGen.sourceFileName();
  if (fileName == "index.xml")
  {
    fileType="book";
  }
  else if (fileName == "mainpage.xml")
  {
    fileType="chapter";
  }
  m_t << "</" << fileType << ">\n";
  endPlainFile();
  m_codeGen.setSourceFileName("");
}
References closeAllSections(), DB_GEN_C, OutputGenerator::endPlainFile(), FALSE, OutputGenerator::fileName(), m_codeGen, m_inGroup, m_inLevel, OutputGenerator::m_t, DocbookCodeGenerator::setSourceFileName(), and DocbookCodeGenerator::sourceFileName().
endFile() [2/2]
void DocbookGenerator::endFile () [virtual]
Implements OutputGenerator.
endFontClass() [1/2]
void DocbookGenerator::endFontClass () [inline], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 124 of file docbookgen.h.
    { m_codeGen.endFontClass(); }
References DocbookCodeGenerator::endFontClass(), and m_codeGen.
endFontClass() [2/2]
void DocbookGenerator::endFontClass () [inline], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 124 of file docbookgen.h.
    { m_codeGen.endFontClass(); }
References DocbookCodeGenerator::endFontClass(), and m_codeGen.
endGroupCollaboration() [1/2]
void DocbookGenerator::endGroupCollaboration (DotGroupCollaboration & g) [virtual]
Implements OutputGenerator.
Definition at line 1144 of file docbookgen.cpp.
{
DB_GEN_C
  g.writeGraph(m_t,GOF_BITMAP,EOF_DocBook,dir(),fileName(),relPath,FALSE);
}
References DB_GEN_C, OutputGenerator::dir(), EOF_DocBook, FALSE, OutputGenerator::fileName(), g, GOF_BITMAP, OutputGenerator::m_t, and relPath.
endGroupCollaboration() [2/2]
void DocbookGenerator::endGroupCollaboration (DotGroupCollaboration & g) [virtual]
Implements OutputGenerator.
endGroupHeader() [1/2]
void DocbookGenerator::endGroupHeader (int) [virtual]
Implements OutputGenerator.
Definition at line 746 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</title>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endGroupHeader() [2/2]
void DocbookGenerator::endGroupHeader (int) [virtual]
Implements OutputGenerator.
endHeaderSection() [1/2]
void DocbookGenerator::endHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 227 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endHeaderSection() [2/2]
void DocbookGenerator::endHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 227 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endHtmlLink() [1/2]
void DocbookGenerator::endHtmlLink () [inline], [virtual]
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
Definition at line 174 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endHtmlLink() [2/2]
void DocbookGenerator::endHtmlLink () [inline], [virtual]
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
Definition at line 174 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endInclDepGraph() [1/2]
void DocbookGenerator::endInclDepGraph (DotInclDepGraph & g) [virtual]
Implements OutputGenerator.
Definition at line 1162 of file docbookgen.cpp.
{
DB_GEN_C
  QCString fn = g.writeGraph(m_t,GOF_BITMAP,EOF_DocBook,dir(),fileName(),relPath,FALSE);
}
References DB_GEN_C, OutputGenerator::dir(), EOF_DocBook, FALSE, OutputGenerator::fileName(), g, GOF_BITMAP, OutputGenerator::m_t, and relPath.
endInclDepGraph() [2/2]
void DocbookGenerator::endInclDepGraph (DotInclDepGraph & g) [virtual]
Implements OutputGenerator.
endIndent() [1/2]
void DocbookGenerator::endIndent () [inline], [virtual]
Implements OutputGenerator.
Definition at line 273 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endIndent() [2/2]
void DocbookGenerator::endIndent () [inline], [virtual]
Implements OutputGenerator.
Definition at line 273 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endIndexItem() [1/2]
void DocbookGenerator::endIndexItem (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 164 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexItem() [2/2]
void DocbookGenerator::endIndexItem (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 164 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexKey() [1/2]
void DocbookGenerator::endIndexKey () [inline], [virtual]
Implements OutputGenerator.
Definition at line 157 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexKey() [2/2]
void DocbookGenerator::endIndexKey () [inline], [virtual]
Implements OutputGenerator.
Definition at line 157 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexList() [1/2]
void DocbookGenerator::endIndexList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 155 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexList() [2/2]
void DocbookGenerator::endIndexList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 155 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexListItem() [1/2]
void DocbookGenerator::endIndexListItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 153 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexListItem() [2/2]
void DocbookGenerator::endIndexListItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 153 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexSection() [1/2]
void DocbookGenerator::endIndexSection (IndexSections is) [virtual]
Implements OutputGenerator.
Definition at line 452 of file docbookgen.cpp.
{
DB_GEN_C2("IndexSections " << is)
  switch (is)
  {
    case isTitlePageStart:
      break;
    case isTitlePageAuthor:
      break;
    case isMainPage:
      m_t << "</title>\n";
      m_t << " <xi:include href=\"mainpage.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
      m_t << "</chapter>\n";
      break;
    case isModuleIndex:
      //m_t << "</chapter>\n";
      break;
    case isDirIndex:
      //m_t << "<xi:include href=\"dirs.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>";
      //m_t << "</chapter>\n";
      break;
    case isNamespaceIndex:
      //m_t << "<xi:include href=\"namespaces.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>";
      //m_t << "</chapter>\n";
      break;
    case isConceptIndex:
      //m_t << "<xi:include href=\"concepts.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>";
      //m_t << "</chapter>\n";
      break;
    case isClassHierarchyIndex:
      //m_t << "<xi:include href=\"hierarchy.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>";
      //m_t << "</chapter>\n";
      break;
    case isCompoundIndex:
      //m_t << "</chapter>\n";
      break;
    case isFileIndex:
      //m_t << "<xi:include href=\"files.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>";
      //m_t << "</chapter>\n";
      break;
    case isPageIndex:
      //m_t << "<xi:include href=\"pages.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>";
      //m_t << "</chapter>\n";
      break;
    case isModuleDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &gd : *Doxygen::groupLinkedMap)
        {
          if (!gd->isReference())
          {
            m_t << " <xi:include href=\"" << gd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
          }
        }
      }
      m_t << "</chapter>\n";
      break;
    case isDirDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &dd : *Doxygen::dirLinkedMap)
        {
          if (dd->isLinkableInProject())
          {
            m_t << "< xi:include href=\"" << dd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
          }
        }
      }
      m_t << "</chapter>\n";
      break;
    case isNamespaceDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &nd : *Doxygen::namespaceLinkedMap)
        {
          if (nd->isLinkableInProject() && !nd->isAlias())
          {
            m_t << "<xi:include href=\"" << nd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
          }
        }
      }
      m_t << "</chapter>\n";
      break;
    case isConceptDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &cd : *Doxygen::conceptLinkedMap)
        {
          if (cd->isLinkableInProject() && !cd->isAlias())
          {
            m_t << "<xi:include href=\"" << cd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
          }
        }
      }
      m_t << "</chapter>\n";
      break;
    case isClassDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &cd : *Doxygen::classLinkedMap)
        {
          if (cd->isLinkableInProject() &&
              cd->templateMaster()==0 &&
             !cd->isEmbeddedInOuterScope() &&
             !cd->isAlias()
             )
          {
            m_t << " <xi:include href=\"" << cd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
          }
        }
      }
      m_t << "</chapter>\n";
      break;
    case isFileDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &fn : *Doxygen::inputNameLinkedMap)
        {
          for (const auto &fd : *fn)
          {
            if (fd->isLinkableInProject())
            {
              m_t << " <xi:include href=\"" << fd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
            }
            if (fd->generateSourceFile())
            {
              m_t << " <xi:include href=\"" << fd->getSourceFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
            }
          }
        }
      }
      m_t << "</chapter>\n";
      break;
    case isExampleDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &pd : *Doxygen::exampleLinkedMap)
        {
          m_t << " <xi:include href=\"" << pd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
        }
      }
      m_t << "</chapter>\n";
      break;
    case isPageDocumentation:
      break;
    case isPageDocumentation2:
      break;
    case isEndIndex:
      m_t << "<index/>\n";
      break;
  }
}
References Doxygen::classLinkedMap, Doxygen::conceptLinkedMap, DB_GEN_C2, Doxygen::dirLinkedMap, Doxygen::exampleLinkedMap, Doxygen::groupLinkedMap, Doxygen::inputNameLinkedMap, isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isConceptDocumentation, isConceptIndex, isDirDocumentation, isDirIndex, isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, isTitlePageAuthor, isTitlePageStart, OutputGenerator::m_t, and Doxygen::namespaceLinkedMap.
endIndexSection() [2/2]
void DocbookGenerator::endIndexSection (IndexSections) [virtual]
Implements OutputGenerator.
endIndexValue() [1/2]
void DocbookGenerator::endIndexValue (const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 159 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexValue() [2/2]
void DocbookGenerator::endIndexValue (const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 159 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endInlineHeader() [1/2]
void DocbookGenerator::endInlineHeader () [inline], [virtual]
Implements OutputGenerator.
Definition at line 237 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endInlineHeader() [2/2]
void DocbookGenerator::endInlineHeader () [inline], [virtual]
Implements OutputGenerator.
Definition at line 237 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endInlineMemberDoc() [1/2]
void DocbookGenerator::endInlineMemberDoc () [virtual]
Implements OutputGenerator.
Definition at line 1076 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</entry></row>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endInlineMemberDoc() [2/2]
void DocbookGenerator::endInlineMemberDoc () [virtual]
Implements OutputGenerator.
endInlineMemberName() [1/2]
void DocbookGenerator::endInlineMemberName () [virtual]
Implements OutputGenerator.
Definition at line 1064 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endInlineMemberName() [2/2]
void DocbookGenerator::endInlineMemberName () [virtual]
Implements OutputGenerator.
endInlineMemberType() [1/2]
void DocbookGenerator::endInlineMemberType () [virtual]
Implements OutputGenerator.
Definition at line 1052 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endInlineMemberType() [2/2]
void DocbookGenerator::endInlineMemberType () [virtual]
Implements OutputGenerator.
endItemList() [1/2]
void DocbookGenerator::endItemList () [inline], [virtual]
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 161 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endItemList() [2/2]
void DocbookGenerator::endItemList () [inline], [virtual]
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 161 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endItemListItem() [1/2]
void DocbookGenerator::endItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 166 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endItemListItem() [2/2]
void DocbookGenerator::endItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 166 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endLabels() [1/2]
void DocbookGenerator::endLabels () [virtual]
Implements OutputGenerator.
Definition at line 911 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endLabels() [2/2]
void DocbookGenerator::endLabels () [virtual]
Implements OutputGenerator.
endMemberDeclaration() [1/2]
void DocbookGenerator::endMemberDeclaration (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 268 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberDeclaration() [2/2]
void DocbookGenerator::endMemberDeclaration (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 268 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberDescription() [1/2]
void DocbookGenerator::endMemberDescription () [inline], [virtual]
Implements OutputGenerator.
Definition at line 266 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberDescription() [2/2]
void DocbookGenerator::endMemberDescription () [inline], [virtual]
Implements OutputGenerator.
Definition at line 266 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberDoc() [1/2]
void DocbookGenerator::endMemberDoc (bool) [virtual]
Implements OutputGenerator.
Definition at line 816 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</computeroutput></para>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberDoc() [2/2]
void DocbookGenerator::endMemberDoc (bool) [virtual]
Implements OutputGenerator.
endMemberDocList() [1/2]
void DocbookGenerator::endMemberDocList () [virtual]
Implements OutputGenerator.
Definition at line 1189 of file docbookgen.cpp.
{
DB_GEN_C
  m_inGroup = TRUE;
}
References DB_GEN_C, m_inGroup, and TRUE.
endMemberDocList() [2/2]
void DocbookGenerator::endMemberDocList () [virtual]
Implements OutputGenerator.
endMemberDocName() [1/2]
void DocbookGenerator::endMemberDocName () [virtual]
Implements OutputGenerator.
Definition at line 856 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endMemberDocName() [2/2]
void DocbookGenerator::endMemberDocName () [virtual]
Implements OutputGenerator.
endMemberDocPrefixItem() [1/2]
void DocbookGenerator::endMemberDocPrefixItem () [virtual]
Implements OutputGenerator.
Definition at line 951 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</computeroutput>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberDocPrefixItem() [2/2]
void DocbookGenerator::endMemberDocPrefixItem () [virtual]
Implements OutputGenerator.
endMemberDocSimple() [1/2]
void DocbookGenerator::endMemberDocSimple (bool isEnum) [virtual]
Implements OutputGenerator.
Definition at line 1037 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << " </tbody>\n";
  m_t << " </tgroup>\n";
  m_t << "</table>\n";
  m_simpleTable = false;
}
References DB_GEN_C, m_simpleTable, and OutputGenerator::m_t.
endMemberDocSimple() [2/2]
void DocbookGenerator::endMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
endMemberGroup() [1/2]
void DocbookGenerator::endMemberGroup (bool) [virtual]
Implements OutputGenerator.
Definition at line 874 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</simplesect>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberGroup() [2/2]
void DocbookGenerator::endMemberGroup (bool) [virtual]
Implements OutputGenerator.
endMemberGroupDocs() [1/2]
void DocbookGenerator::endMemberGroupDocs () [inline], [virtual]
Implements OutputGenerator.
Definition at line 249 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberGroupDocs() [2/2]
void DocbookGenerator::endMemberGroupDocs () [inline], [virtual]
Implements OutputGenerator.
Definition at line 249 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberGroupHeader() [1/2]
void DocbookGenerator::endMemberGroupHeader () [virtual]
Implements OutputGenerator.
Definition at line 865 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</title>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberGroupHeader() [2/2]
void DocbookGenerator::endMemberGroupHeader () [virtual]
Implements OutputGenerator.
endMemberHeader() [1/2]
void DocbookGenerator::endMemberHeader () [virtual]
Implements OutputGenerator.
Definition at line 661 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << " </title>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberHeader() [2/2]
void DocbookGenerator::endMemberHeader () [virtual]
Implements OutputGenerator.
endMemberItem() [1/2]
void DocbookGenerator::endMemberItem () [virtual]
Implements OutputGenerator.
Definition at line 710 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</para>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberItem() [2/2]
void DocbookGenerator::endMemberItem () [virtual]
Implements OutputGenerator.
endMemberList() [1/2]
void DocbookGenerator::endMemberList () [virtual]
Implements OutputGenerator.
Definition at line 693 of file docbookgen.cpp.
{
DB_GEN_C
  if (m_inListItem[m_levelListItem]) m_t << "</listitem>\n";
  m_inListItem[m_levelListItem] = FALSE;
  m_t << " </itemizedlist>\n";
  m_levelListItem = (m_levelListItem> 0 ? m_levelListItem - 1 : 0);
  if (m_inSimpleSect[m_levelListItem]) m_t << "</simplesect>\n";
  m_inSimpleSect[m_levelListItem] = FALSE;
}
References DB_GEN_C, FALSE, m_inListItem, m_inSimpleSect, m_levelListItem, and OutputGenerator::m_t.
endMemberList() [2/2]
void DocbookGenerator::endMemberList () [virtual]
Implements OutputGenerator.
endMemberSections() [1/2]
void DocbookGenerator::endMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 225 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberSections() [2/2]
void DocbookGenerator::endMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 225 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberSubtitle() [1/2]
void DocbookGenerator::endMemberSubtitle () [inline], [virtual]
Implements OutputGenerator.
Definition at line 231 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberSubtitle() [2/2]
void DocbookGenerator::endMemberSubtitle () [inline], [virtual]
Implements OutputGenerator.
Definition at line 231 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberTemplateParams() [1/2]
void DocbookGenerator::endMemberTemplateParams (const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 987 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</para>";
  m_t << "<para>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberTemplateParams() [2/2]
void DocbookGenerator::endMemberTemplateParams (const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
endPageDoc() [1/2]
void DocbookGenerator::endPageDoc () [inline], [virtual]
Reimplemented from OutputGenerator.
Definition at line 298 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
endPageDoc() [2/2]
void DocbookGenerator::endPageDoc () [inline], [virtual]
Reimplemented from OutputGenerator.
Definition at line 298 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
endPageRef() [1/2]
void DocbookGenerator::endPageRef (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 215 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endPageRef() [2/2]
void DocbookGenerator::endPageRef (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 215 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endParagraph() [1/2]
void DocbookGenerator::endParagraph () [virtual]
Ends a paragraph
Implements BaseOutputDocInterface.
Definition at line 643 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</para>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endParagraph() [2/2]
void DocbookGenerator::endParagraph () [virtual]
Ends a paragraph
Implements BaseOutputDocInterface.
endParameterList() [1/2]
void DocbookGenerator::endParameterList () [virtual]
Implements OutputGenerator.
Definition at line 757 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endParameterList() [2/2]
void DocbookGenerator::endParameterList () [virtual]
Implements OutputGenerator.
endParameterName() [1/2]
void DocbookGenerator::endParameterName (bool last, bool , bool closeBracket) [virtual]
Implements OutputGenerator.
Definition at line 974 of file docbookgen.cpp.
{
DB_GEN_C
  if (last)
  {
    if (closeBracket) m_t << ")";
  }
}
References DB_GEN_C, and OutputGenerator::m_t.
endParameterName() [2/2]
void DocbookGenerator::endParameterName (bool , bool , bool) [virtual]
Implements OutputGenerator.
endParameterType() [1/2]
void DocbookGenerator::endParameterType () [inline], [virtual]
Implements OutputGenerator.
Definition at line 307 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endParameterType() [2/2]
void DocbookGenerator::endParameterType () [inline], [virtual]
Implements OutputGenerator.
Definition at line 307 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endParamList() [1/2]
void DocbookGenerator::endParamList () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 195 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endParamList() [2/2]
void DocbookGenerator::endParamList () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 195 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endProjectNumber() [1/2]
void DocbookGenerator::endProjectNumber () [inline], [virtual]
Implements OutputGenerator.
Definition at line 148 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endProjectNumber() [2/2]
void DocbookGenerator::endProjectNumber () [inline], [virtual]
Implements OutputGenerator.
Definition at line 148 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endQuickIndices() [1/2]
void DocbookGenerator::endQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 289 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endQuickIndices() [2/2]
void DocbookGenerator::endQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 289 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endSection() [1/2]
void DocbookGenerator::endSection (const QCString & , SectionType) [virtual]
Implements BaseOutputDocInterface.
Definition at line 999 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</title>";
  closeSection();
}
References closeSection(), DB_GEN_C, and OutputGenerator::m_t.
endSection() [2/2]
void DocbookGenerator::endSection (const QCString & , SectionType) [virtual]
Implements BaseOutputDocInterface.
endSmall() [1/2]
void DocbookGenerator::endSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 191 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endSmall() [2/2]
void DocbookGenerator::endSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 191 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endSubsection() [1/2]
void DocbookGenerator::endSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 217 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endSubsection() [2/2]
void DocbookGenerator::endSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 217 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endSubsubsection() [1/2]
void DocbookGenerator::endSubsubsection () [virtual]
Implements BaseOutputDocInterface.
Definition at line 933 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</title></simplesect>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
Referenced by endCompoundTemplateParams().
endSubsubsection() [2/2]
void DocbookGenerator::endSubsubsection () [virtual]
Implements BaseOutputDocInterface.
endTextBlock() [1/2]
void DocbookGenerator::endTextBlock (bool) [virtual]
Implements OutputGenerator.
Definition at line 790 of file docbookgen.cpp.
{
DB_GEN_C
  if (m_denseText)
  {
    m_denseText = FALSE;
    m_t << "</programlisting>";
  }
}
References DB_GEN_C, FALSE, m_denseText, and OutputGenerator::m_t.
endTextBlock() [2/2]
void DocbookGenerator::endTextBlock (bool) [virtual]
Implements OutputGenerator.
endTextLink() [1/2]
void DocbookGenerator::endTextLink () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 213 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endTextLink() [2/2]
void DocbookGenerator::endTextLink () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 213 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endTitle() [1/2]
void DocbookGenerator::endTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 197 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endTitle() [2/2]
void DocbookGenerator::endTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 197 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endTitleHead() [1/2]
void DocbookGenerator::endTitleHead (const QCString & fileName, const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 826 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</title>\n";
  if (!name.isEmpty()) addIndexTerm(m_t, name);
}
References addIndexTerm(), DB_GEN_C, OutputGenerator::m_t, and setup::name.
endTitleHead() [2/2]
void DocbookGenerator::endTitleHead (const QCString & fileName, const QCString & name) [virtual]
Implements OutputGenerator.
endTypewriter() [1/2]
void DocbookGenerator::endTypewriter () [virtual]
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 776 of file docbookgen.cpp.
{
DB_GEN_C
  if (!m_denseText) m_t << "</computeroutput>\n";
}
References DB_GEN_C, m_denseText, and OutputGenerator::m_t.
endTypewriter() [2/2]
void DocbookGenerator::endTypewriter () [virtual]
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
exceptionEntry() [1/2]
void DocbookGenerator::exceptionEntry (const QCString & prefix, bool closeBracket) [virtual]
Implements OutputGenerator.
Definition at line 956 of file docbookgen.cpp.
{
DB_GEN_C
  if (!prefix.isEmpty())
  {
    m_t << " " << prefix << "(";
  }
  else if (closeBracket)
  {
    m_t << ")";
  }
  m_t << " ";
}
References DB_GEN_C, QCString::isEmpty(), and OutputGenerator::m_t.
exceptionEntry() [2/2]
void DocbookGenerator::exceptionEntry (const QCString & , bool) [virtual]
Implements OutputGenerator.
init() [1/2]
void DocbookGenerator::init () [static]
Definition at line 301 of file docbookgen.cpp.
{
  QCString dir=Config_getString(DOCBOOK_OUTPUT);
  Dir d(dir.str());
  if (!d.exists() && !d.mkdir(dir.str()))
  {
    term("Could not create output directory %s\n",qPrint(dir));
  }
  createSubDirs(d);
}
References Config_getString, createSubDirs(), OutputGenerator::dir(), Dir::exists(), Dir::mkdir(), qPrint(), QCString::str(), and term().
Referenced by generateOutput().
init() [2/2]
static void DocbookGenerator::init () [static]
insertMemberAlign() [1/2]
void DocbookGenerator::insertMemberAlign (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 252 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
insertMemberAlign() [2/2]
void DocbookGenerator::insertMemberAlign (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 252 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
insertMemberAlignLeft() [1/2]
void DocbookGenerator::insertMemberAlignLeft (int , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 253 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
insertMemberAlignLeft() [2/2]
void DocbookGenerator::insertMemberAlignLeft (int , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 253 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
lastIndexPage() [1/2]
void DocbookGenerator::lastIndexPage () [inline], [virtual]
Implements OutputGenerator.
Definition at line 301 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
lastIndexPage() [2/2]
void DocbookGenerator::lastIndexPage () [inline], [virtual]
Implements OutputGenerator.
Definition at line 301 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
lineBreak() [1/2]
void DocbookGenerator::lineBreak (const QCString &) [virtual]
Implements BaseOutputDocInterface.
Definition at line 766 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<?linebreak?>";
}
References DB_GEN_C, and OutputGenerator::m_t.
lineBreak() [2/2]
void DocbookGenerator::lineBreak (const QCString &) [virtual]
Implements BaseOutputDocInterface.
openSection() [1/2]
void DocbookGenerator::openSection (const QCString & attr = QCString()) [private]
Definition at line 1234 of file docbookgen.cpp.
{
   m_t << "<section";
   if (!attr.isEmpty()) m_t << " " << attr;
   m_t << ">\n";
   m_openSectionCount++;
}
References QCString::isEmpty(), m_openSectionCount, and OutputGenerator::m_t.
Referenced by startGroupHeader(), startMemberDoc(), and startSection().
openSection() [2/2]
void DocbookGenerator::openSection (const QCString & attr = QCString()) [private]
operator=() [1/2]
DocbookGenerator & DocbookGenerator::operator= (const DocbookGenerator & o)
Definition at line 285 of file docbookgen.cpp.
{
  OutputGenerator::operator=(og);
  return *this;
}
References OutputGenerator::operator=().
operator=() [2/2]
DocbookGenerator & DocbookGenerator::operator= (const DocbookGenerator & o)
setCurrentDoc() [1/2]
void DocbookGenerator::setCurrentDoc (const Definition * , const QCString & , bool) [inline], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 336 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
setCurrentDoc() [2/2]
void DocbookGenerator::setCurrentDoc (const Definition * , const QCString & , bool) [inline], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 336 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
startAnonTypeScope() [1/2]
void DocbookGenerator::startAnonTypeScope (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 238 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startAnonTypeScope() [2/2]
void DocbookGenerator::startAnonTypeScope (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 238 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startBold() [1/2]
void DocbookGenerator::startBold () [virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 715 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<emphasis role=\"strong\">";
}
References DB_GEN_C, and OutputGenerator::m_t.
startBold() [2/2]
void DocbookGenerator::startBold () [virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
startCallGraph() [1/2]
void DocbookGenerator::startCallGraph () [virtual]
Implements OutputGenerator.
Definition at line 1167 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startCallGraph() [2/2]
void DocbookGenerator::startCallGraph () [virtual]
Implements OutputGenerator.
startCenter() [1/2]
void DocbookGenerator::startCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 188 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startCenter() [2/2]
void DocbookGenerator::startCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 188 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startClassDiagram() [1/2]
void DocbookGenerator::startClassDiagram () [virtual]
Implements OutputGenerator.
Definition at line 879 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<para>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startClassDiagram() [2/2]
void DocbookGenerator::startClassDiagram () [virtual]
Implements OutputGenerator.
startCodeFragment() [1/2]
void DocbookGenerator::startCodeFragment (const QCString & style) [inline], [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 128 of file docbookgen.h.
    { m_codeGen.startCodeFragment(style); }
References m_codeGen, DocbookCodeGenerator::startCodeFragment(), and style.
startCodeFragment() [2/2]
void DocbookGenerator::startCodeFragment (const QCString & style) [inline], [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 128 of file docbookgen.h.
    { m_codeGen.startCodeFragment(style); }
References m_codeGen, DocbookCodeGenerator::startCodeFragment(), and style.
startCodeLine() [1/2]
void DocbookGenerator::startCodeLine (bool hasLineNumbers) [inline], [virtual]
Implements CodeOutputInterface.
Definition at line 118 of file docbookgen.h.
    { m_codeGen.startCodeLine(hasLineNumbers); }
References m_codeGen, and DocbookCodeGenerator::startCodeLine().
startCodeLine() [2/2]
void DocbookGenerator::startCodeLine (bool hasLineNumbers) [inline], [virtual]
Implements CodeOutputInterface.
Definition at line 118 of file docbookgen.h.
    { m_codeGen.startCodeLine(hasLineNumbers); }
References m_codeGen, and DocbookCodeGenerator::startCodeLine().
startCompoundTemplateParams() [1/2]
void DocbookGenerator::startCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 244 of file docbookgen.h.
{ startSubsubsection(); }
References startSubsubsection().
startCompoundTemplateParams() [2/2]
void DocbookGenerator::startCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 244 of file docbookgen.h.
{ startSubsubsection(); }
References startSubsubsection().
startConstraintDocs() [1/2]
void DocbookGenerator::startConstraintDocs () [virtual]
Implements OutputGenerator.
Definition at line 1220 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startConstraintDocs() [2/2]
void DocbookGenerator::startConstraintDocs () [virtual]
Implements OutputGenerator.
startConstraintList() [1/2]
void DocbookGenerator::startConstraintList (const QCString & header) [virtual]
Implements OutputGenerator.
Definition at line 1194 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<simplesect><title>";
  docify(header);
  m_t << "</title>\n";
}
References DB_GEN_C, docify(), and OutputGenerator::m_t.
startConstraintList() [2/2]
void DocbookGenerator::startConstraintList (const QCString &) [virtual]
Implements OutputGenerator.
startConstraintParam() [1/2]
void DocbookGenerator::startConstraintParam () [virtual]
Implements OutputGenerator.
Definition at line 1201 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<para><emphasis role=\"strong\">";
}
References DB_GEN_C, and OutputGenerator::m_t.
startConstraintParam() [2/2]
void DocbookGenerator::startConstraintParam () [virtual]
Implements OutputGenerator.
startConstraintType() [1/2]
void DocbookGenerator::startConstraintType () [virtual]
Implements OutputGenerator.
Definition at line 1210 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << ":";
}
References DB_GEN_C, and OutputGenerator::m_t.
startConstraintType() [2/2]
void DocbookGenerator::startConstraintType () [virtual]
Implements OutputGenerator.
startContents() [1/2]
void DocbookGenerator::startContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 295 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startContents() [2/2]
void DocbookGenerator::startContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 295 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startDescForItem() [1/2]
void DocbookGenerator::startDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 185 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startDescForItem() [2/2]
void DocbookGenerator::startDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 185 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startDescItem() [1/2]
void DocbookGenerator::startDescItem () [inline], [virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 184 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startDescItem() [2/2]
void DocbookGenerator::startDescItem () [inline], [virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 184 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startDescription() [1/2]
void DocbookGenerator::startDescription () [inline], [virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 182 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startDescription() [2/2]
void DocbookGenerator::startDescription () [inline], [virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 182 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startDescTable() [1/2]
void DocbookGenerator::startDescTable (const QCString & title) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1082 of file docbookgen.cpp.
{
DB_GEN_C
  int ncols = 2;
  m_t << "<informaltable frame=\"all\">\n";
  if (!title.isEmpty()) m_t << "<title>" << convertToDocBook(title) << "</title>\n";
  m_t << " <tgroup cols=\"" << ncols << "\" align=\"left\" colsep=\"1\" rowsep=\"1\">\n";
  for (int i = 0; i < ncols; i++)
  {
    m_t << " <colspec colname='c" << i+1 << "'/>\n";
  }
  m_t << "<tbody>\n";
  m_descTable = TRUE;
}
References convertToDocBook(), DB_GEN_C, QCString::isEmpty(), m_descTable, OutputGenerator::m_t, and TRUE.
startDescTable() [2/2]
void DocbookGenerator::startDescTable (const QCString &) [virtual]
Implements BaseOutputDocInterface.
startDescTableData() [1/2]
void DocbookGenerator::startDescTableData () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1129 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</entry><entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startDescTableData() [2/2]
void DocbookGenerator::startDescTableData () [virtual]
Implements BaseOutputDocInterface.
startDescTableRow() [1/2]
void DocbookGenerator::startDescTableRow () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1106 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<row>";
  m_t << "<entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startDescTableRow() [2/2]
void DocbookGenerator::startDescTableRow () [virtual]
Implements BaseOutputDocInterface.
startDescTableTitle() [1/2]
void DocbookGenerator::startDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1119 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startDescTableTitle() [2/2]
void DocbookGenerator::startDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
startDirDepGraph() [1/2]
void DocbookGenerator::startDirDepGraph () [virtual]
Implements OutputGenerator.
Definition at line 1176 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startDirDepGraph() [2/2]
void DocbookGenerator::startDirDepGraph () [virtual]
Implements OutputGenerator.
startDotGraph() [1/2]
void DocbookGenerator::startDotGraph () [virtual]
Implements OutputGenerator.
Definition at line 1149 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startDotGraph() [2/2]
void DocbookGenerator::startDotGraph () [virtual]
Implements OutputGenerator.
startDoxyAnchor() [1/2]
void DocbookGenerator::startDoxyAnchor (const QCString & fName, const QCString & manName, const QCString & anchor, const QCString & name, const QCString & args) [virtual]
Implements OutputGenerator.
Definition at line 832 of file docbookgen.cpp.
{
DB_GEN_C
  if (!m_inListItem[m_levelListItem] && !m_descTable && !m_simpleTable)
  {
    if (!m_firstMember) closeSection();
    m_firstMember = FALSE;
  }
  if (!anchor.isEmpty())
  {
    m_t << "<anchor xml:id=\"_" << stripPath(fName) << "_1" << anchor << "\"/>";
  }
}
References closeSection(), DB_GEN_C, FALSE, QCString::isEmpty(), m_descTable, m_firstMember, m_inListItem, m_levelListItem, m_simpleTable, OutputGenerator::m_t, and stripPath().
startDoxyAnchor() [2/2]
void DocbookGenerator::startDoxyAnchor (const QCString & fName, const QCString & manName, const QCString & anchor, const QCString & name, const QCString & args) [virtual]
Implements OutputGenerator.
startEmphasis() [1/2]
void DocbookGenerator::startEmphasis () [inline], [virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 179 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startEmphasis() [2/2]
void DocbookGenerator::startEmphasis () [inline], [virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 179 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startExamples() [1/2]
void DocbookGenerator::startExamples () [virtual]
Implements BaseOutputDocInterface.
Definition at line 915 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<simplesect><title>";
  docify(theTranslator->trExamples());
  m_t << "</title>";
}
References DB_GEN_C, docify(), OutputGenerator::m_t, theTranslator, and Translator::trExamples().
startExamples() [2/2]
void DocbookGenerator::startExamples () [virtual]
Implements BaseOutputDocInterface.
startFile() [1/2]
void DocbookGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id) [virtual]
Implements OutputGenerator.
Definition at line 320 of file docbookgen.cpp.
{
DB_GEN_C
  QCString fileName=name;
  QCString pageName;
  QCString fileType="section";
  if (fileName == "refman")
  {
    fileName="index";
    fileType="book";
  }
  else if (fileName == "index")
  {
    fileName="mainpage";
    fileType="chapter";
  }
  pageName = fileName;
  relPath = relativePathToRoot(fileName);
  if (!fileName.endsWith(".xml")) fileName+=".xml";
  startPlainFile(fileName);
  m_codeGen.setRelativePath(relPath);
  m_codeGen.setSourceFileName(stripPath(fileName));
  m_t << "<?xml version='1.0' encoding='UTF-8' standalone='no'?>\n";;
  m_t << "<" << fileType << " xmlns=\"http://docbook.org/ns/docbook\" version=\"5.0\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"";
  if (!pageName.isEmpty()) m_t << " xml:id=\"_" << stripPath(pageName) << "\"";
  m_t << " xml:lang=\"" << theTranslator->trISOLang() << "\"";
  m_t << ">\n";
}
References DB_GEN_C, QCString::endsWith(), OutputGenerator::fileName(), QCString::isEmpty(), m_codeGen, OutputGenerator::m_t, setup::name, relativePathToRoot(), relPath, DocbookCodeGenerator::setRelativePath(), DocbookCodeGenerator::setSourceFileName(), OutputGenerator::startPlainFile(), stripPath(), theTranslator, and Translator::trISOLang().
startFile() [2/2]
void DocbookGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id) [virtual]
Implements OutputGenerator.
startFontClass() [1/2]
void DocbookGenerator::startFontClass (const QCString & clsName) [inline], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 122 of file docbookgen.h.
    { m_codeGen.startFontClass(s); }
References m_codeGen, s, and DocbookCodeGenerator::startFontClass().
startFontClass() [2/2]
void DocbookGenerator::startFontClass (const QCString & clsName) [inline], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 122 of file docbookgen.h.
    { m_codeGen.startFontClass(s); }
References m_codeGen, s, and DocbookCodeGenerator::startFontClass().
startGroupCollaboration() [1/2]
void DocbookGenerator::startGroupCollaboration () [virtual]
Implements OutputGenerator.
Definition at line 1140 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startGroupCollaboration() [2/2]
void DocbookGenerator::startGroupCollaboration () [virtual]
Implements OutputGenerator.
startGroupHeader() [1/2]
void DocbookGenerator::startGroupHeader (int extraIndentLevel) [virtual]
Implements OutputGenerator.
Definition at line 725 of file docbookgen.cpp.
{
DB_GEN_C2("m_inLevel " << m_inLevel)
DB_GEN_C2("extraIndentLevel " << extraIndentLevel)
  m_firstMember = TRUE;
  if (m_inSimpleSect[m_levelListItem]) m_t << "</simplesect>\n";
  m_inSimpleSect[m_levelListItem] = FALSE;
  if (m_inLevel != -1) m_inGroup = TRUE;
  if (m_inLevel == extraIndentLevel) closeSection();
  m_inLevel = extraIndentLevel;
  openSection();
  m_t << "<title>";
}
References closeSection(), DB_GEN_C2, FALSE, m_firstMember, m_inGroup, m_inLevel, m_inSimpleSect, m_levelListItem, OutputGenerator::m_t, openSection(), and TRUE.
startGroupHeader() [2/2]
void DocbookGenerator::startGroupHeader (int) [virtual]
Implements OutputGenerator.
startHeaderSection() [1/2]
void DocbookGenerator::startHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 226 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startHeaderSection() [2/2]
void DocbookGenerator::startHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 226 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startHtmlLink() [1/2]
void DocbookGenerator::startHtmlLink (const QCString & url) [inline], [virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
Definition at line 173 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startHtmlLink() [2/2]
void DocbookGenerator::startHtmlLink (const QCString & url) [inline], [virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
Definition at line 173 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startInclDepGraph() [1/2]
void DocbookGenerator::startInclDepGraph () [virtual]
Implements OutputGenerator.
Definition at line 1158 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startInclDepGraph() [2/2]
void DocbookGenerator::startInclDepGraph () [virtual]
Implements OutputGenerator.
startIndent() [1/2]
void DocbookGenerator::startIndent () [inline], [virtual]
Implements OutputGenerator.
Definition at line 272 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startIndent() [2/2]
void DocbookGenerator::startIndent () [inline], [virtual]
Implements OutputGenerator.
Definition at line 272 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startIndexItem() [1/2]
void DocbookGenerator::startIndexItem (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 163 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexItem() [2/2]
void DocbookGenerator::startIndexItem (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 163 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexKey() [1/2]
void DocbookGenerator::startIndexKey () [inline], [virtual]
Implements OutputGenerator.
Definition at line 156 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexKey() [2/2]
void DocbookGenerator::startIndexKey () [inline], [virtual]
Implements OutputGenerator.
Definition at line 156 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexList() [1/2]
void DocbookGenerator::startIndexList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 154 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexList() [2/2]
void DocbookGenerator::startIndexList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 154 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexListItem() [1/2]
void DocbookGenerator::startIndexListItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 152 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexListItem() [2/2]
void DocbookGenerator::startIndexListItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 152 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexSection() [1/2]
void DocbookGenerator::startIndexSection (IndexSections is) [virtual]
Implements OutputGenerator.
Definition at line 372 of file docbookgen.cpp.
{
DB_GEN_C2("IndexSections " << is)
  switch (is)
  {
    case isTitlePageStart:
      {
        QCString dbk_projectName = Config_getString(PROJECT_NAME);
        m_t << " <info>\n";
        m_t << " <title>" << convertToDocBook(dbk_projectName) << "</title>\n";
        m_t << " </info>\n";
      }
      break;
    case isTitlePageAuthor:
      break;
    case isMainPage:
      m_t << "<chapter>\n";
      m_t << " <title>";
      break;
    case isModuleIndex:
      //Module Index}\n"
      break;
    case isDirIndex:
      //Directory Index}\n"
      break;
    case isNamespaceIndex:
      //Namespace Index}\n"
      break;
    case isConceptIndex:
      //Concept Index}\n"
      break;
    case isClassHierarchyIndex:
      //Hierarchical Index}\n"
      break;
    case isCompoundIndex:
      //m_t << "{"; //Class Index}\n"
      break;
    case isFileIndex:
      //Annotated File Index}\n"
      break;
    case isPageIndex:
      //Annotated Page Index}\n"
      break;
    case isModuleDocumentation:
      m_t << "<chapter>\n";
      m_t << " <title>";
      break;
    case isDirDocumentation:
      m_t << "<chapter>\n";
      m_t << " <title>";
      break;
    case isNamespaceDocumentation:
      m_t << "<chapter>\n";
      m_t << " <title>";
      break;
    case isConceptDocumentation:
      m_t << "<chapter>\n";
      m_t << " <title>";
      break;
    case isClassDocumentation:
      m_t << "<chapter>\n";
      m_t << " <title>";
      break;
    case isFileDocumentation:
      m_t << "<chapter>\n";
      m_t << " <title>";
      break;
    case isExampleDocumentation:
      m_t << "<chapter>\n";
      m_t << " <title>";
      break;
    case isPageDocumentation:
      break;
    case isPageDocumentation2:
      break;
    case isEndIndex:
      break;
  }
}
References Config_getString, convertToDocBook(), DB_GEN_C2, isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isConceptDocumentation, isConceptIndex, isDirDocumentation, isDirIndex, isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, isTitlePageAuthor, isTitlePageStart, and OutputGenerator::m_t.
startIndexSection() [2/2]
void DocbookGenerator::startIndexSection (IndexSections) [virtual]
Implements OutputGenerator.
startIndexValue() [1/2]
void DocbookGenerator::startIndexValue (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 158 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexValue() [2/2]
void DocbookGenerator::startIndexValue (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 158 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startInlineHeader() [1/2]
void DocbookGenerator::startInlineHeader () [inline], [virtual]
Implements OutputGenerator.
Definition at line 236 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startInlineHeader() [2/2]
void DocbookGenerator::startInlineHeader () [inline], [virtual]
Implements OutputGenerator.
Definition at line 236 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startInlineMemberDoc() [1/2]
void DocbookGenerator::startInlineMemberDoc () [virtual]
Implements OutputGenerator.
Definition at line 1070 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startInlineMemberDoc() [2/2]
void DocbookGenerator::startInlineMemberDoc () [virtual]
Implements OutputGenerator.
startInlineMemberName() [1/2]
void DocbookGenerator::startInlineMemberName () [virtual]
Implements OutputGenerator.
Definition at line 1058 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startInlineMemberName() [2/2]
void DocbookGenerator::startInlineMemberName () [virtual]
Implements OutputGenerator.
startInlineMemberType() [1/2]
void DocbookGenerator::startInlineMemberType () [virtual]
Implements OutputGenerator.
Definition at line 1046 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<row><entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startInlineMemberType() [2/2]
void DocbookGenerator::startInlineMemberType () [virtual]
Implements OutputGenerator.
startItemList() [1/2]
void DocbookGenerator::startItemList () [inline], [virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 160 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startItemList() [2/2]
void DocbookGenerator::startItemList () [inline], [virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 160 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startItemListItem() [1/2]
void DocbookGenerator::startItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
Definition at line 165 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startItemListItem() [2/2]
void DocbookGenerator::startItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
Definition at line 165 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startLabels() [1/2]
void DocbookGenerator::startLabels () [virtual]
Implements OutputGenerator.
Definition at line 899 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startLabels() [2/2]
void DocbookGenerator::startLabels () [virtual]
Implements OutputGenerator.
startMemberDeclaration() [1/2]
void DocbookGenerator::startMemberDeclaration () [inline], [virtual]
Implements OutputGenerator.
Definition at line 267 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberDeclaration() [2/2]
void DocbookGenerator::startMemberDeclaration () [inline], [virtual]
Implements OutputGenerator.
Definition at line 267 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberDescription() [1/2]
void DocbookGenerator::startMemberDescription (const QCString & , const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 265 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberDescription() [2/2]
void DocbookGenerator::startMemberDescription (const QCString & , const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 265 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberDoc() [1/2]
void DocbookGenerator::startMemberDoc (const QCString & clname, const QCString & memname, const QCString & , const QCString & title, int memCount, int memTotal, bool) [virtual]
Implements OutputGenerator.
Definition at line 799 of file docbookgen.cpp.
{
DB_GEN_C2("m_inLevel " << m_inLevel)
  openSection();
  m_t << " <title>" << convertToDocBook(title);
  if (memTotal>1)
  {
    m_t << "<computeroutput>[" << memCount << "/" << memTotal << "]</computeroutput>";
  }
  m_t << "</title>\n";
  if (!memname.isEmpty() && memname[0]!='@')
  {
    addIndexTerm(m_t,memname,clname);
    addIndexTerm(m_t,clname,memname);
  }
}
References addIndexTerm(), convertToDocBook(), DB_GEN_C2, QCString::isEmpty(), m_inLevel, OutputGenerator::m_t, and openSection().
startMemberDoc() [2/2]
void DocbookGenerator::startMemberDoc (const QCString & , const QCString & , const QCString & , const QCString & , int , int , bool) [virtual]
Implements OutputGenerator.
startMemberDocList() [1/2]
void DocbookGenerator::startMemberDocList () [virtual]
Implements OutputGenerator.
Definition at line 1185 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startMemberDocList() [2/2]
void DocbookGenerator::startMemberDocList () [virtual]
Implements OutputGenerator.
startMemberDocName() [1/2]
void DocbookGenerator::startMemberDocName (bool) [virtual]
Implements OutputGenerator.
Definition at line 851 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<para><computeroutput>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startMemberDocName() [2/2]
void DocbookGenerator::startMemberDocName (bool) [virtual]
Implements OutputGenerator.
startMemberDocPrefixItem() [1/2]
void DocbookGenerator::startMemberDocPrefixItem () [virtual]
Implements OutputGenerator.
Definition at line 946 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<computeroutput>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startMemberDocPrefixItem() [2/2]
void DocbookGenerator::startMemberDocPrefixItem () [virtual]
Implements OutputGenerator.
startMemberDocSimple() [1/2]
void DocbookGenerator::startMemberDocSimple (bool isEnum) [virtual]
Implements OutputGenerator.
Definition at line 1011 of file docbookgen.cpp.
{
DB_GEN_C
  int ncols;
  QCString title;
  if (isEnum)
  {
    ncols = 2;
    title = theTranslator->trEnumerationValues();
  }
  else
  {
    ncols = 3;
    title = theTranslator->trCompoundMembers();
  }
  m_t << "<table frame=\"all\">\n";
  if (!title.isEmpty()) m_t << "<title>" << convertToDocBook(title) << "</title>\n";
  m_t << " <tgroup cols=\"" << ncols << "\" align=\"left\" colsep=\"1\" rowsep=\"1\">\n";
  for (int i = 0; i < ncols; i++)
  {
    m_t << " <colspec colname='c" << i+1 << "'/>\n";
  }
  m_t << "<tbody>\n";
  m_simpleTable = true;
}
References convertToDocBook(), DB_GEN_C, QCString::isEmpty(), m_simpleTable, OutputGenerator::m_t, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberDocSimple() [2/2]
void DocbookGenerator::startMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
startMemberGroup() [1/2]
void DocbookGenerator::startMemberGroup () [virtual]
Implements OutputGenerator.
Definition at line 870 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startMemberGroup() [2/2]
void DocbookGenerator::startMemberGroup () [virtual]
Implements OutputGenerator.
startMemberGroupDocs() [1/2]
void DocbookGenerator::startMemberGroupDocs () [inline], [virtual]
Implements OutputGenerator.
Definition at line 248 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberGroupDocs() [2/2]
void DocbookGenerator::startMemberGroupDocs () [inline], [virtual]
Implements OutputGenerator.
Definition at line 248 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberGroupHeader() [1/2]
void DocbookGenerator::startMemberGroupHeader (bool) [virtual]
Implements OutputGenerator.
Definition at line 860 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<simplesect><title>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startMemberGroupHeader() [2/2]
void DocbookGenerator::startMemberGroupHeader (bool) [virtual]
Implements OutputGenerator.
startMemberHeader() [1/2]
void DocbookGenerator::startMemberHeader (const QCString & anchor, int typ) [virtual]
Implements OutputGenerator.
Definition at line 653 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<simplesect>\n";
  m_inSimpleSect[m_levelListItem] = TRUE;
  m_t << " <title>";
}
References DB_GEN_C, m_inSimpleSect, m_levelListItem, OutputGenerator::m_t, and TRUE.
startMemberHeader() [2/2]
void DocbookGenerator::startMemberHeader (const QCString & anchor, int typ) [virtual]
Implements OutputGenerator.
startMemberItem() [1/2]
void DocbookGenerator::startMemberItem (const QCString & , int , const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 703 of file docbookgen.cpp.
{
DB_GEN_C
  if (m_inListItem[m_levelListItem]) m_t << "</listitem>\n";
  m_t << " <listitem><para>";
  m_inListItem[m_levelListItem] = TRUE;
}
References DB_GEN_C, m_inListItem, m_levelListItem, OutputGenerator::m_t, and TRUE.
startMemberItem() [2/2]
void DocbookGenerator::startMemberItem (const QCString & , int , const QCString &) [virtual]
Implements OutputGenerator.
startMemberList() [1/2]
void DocbookGenerator::startMemberList () [virtual]
Implements OutputGenerator.
Definition at line 687 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << " <itemizedlist>\n";
  m_levelListItem++;
}
References DB_GEN_C, m_levelListItem, and OutputGenerator::m_t.
startMemberList() [2/2]
void DocbookGenerator::startMemberList () [virtual]
Implements OutputGenerator.
startMemberSections() [1/2]
void DocbookGenerator::startMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 224 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberSections() [2/2]
void DocbookGenerator::startMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 224 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberSubtitle() [1/2]
void DocbookGenerator::startMemberSubtitle () [inline], [virtual]
Implements OutputGenerator.
Definition at line 230 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberSubtitle() [2/2]
void DocbookGenerator::startMemberSubtitle () [inline], [virtual]
Implements OutputGenerator.
Definition at line 230 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberTemplateParams() [1/2]
void DocbookGenerator::startMemberTemplateParams () [virtual]
Implements OutputGenerator.
Definition at line 982 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startMemberTemplateParams() [2/2]
void DocbookGenerator::startMemberTemplateParams () [virtual]
Implements OutputGenerator.
startPageDoc() [1/2]
void DocbookGenerator::startPageDoc (const QCString &) [inline], [virtual]
Reimplemented from OutputGenerator.
Definition at line 297 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
startPageDoc() [2/2]
void DocbookGenerator::startPageDoc (const QCString &) [inline], [virtual]
Reimplemented from OutputGenerator.
Definition at line 297 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
startPageRef() [1/2]
void DocbookGenerator::startPageRef () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 214 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startPageRef() [2/2]
void DocbookGenerator::startPageRef () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 214 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startParagraph() [1/2]
void DocbookGenerator::startParagraph (const QCString & classDef) [virtual]
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
Definition at line 637 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<para>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
startParagraph() [2/2]
void DocbookGenerator::startParagraph (const QCString & classDef) [virtual]
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
startParameterList() [1/2]
void DocbookGenerator::startParameterList (bool openBracket) [virtual]
Implements OutputGenerator.
Definition at line 752 of file docbookgen.cpp.
{
DB_GEN_C
  if (openBracket) m_t << "(";
}
References DB_GEN_C, and OutputGenerator::m_t.
startParameterList() [2/2]
void DocbookGenerator::startParameterList (bool) [virtual]
Implements OutputGenerator.
startParameterName() [1/2]
void DocbookGenerator::startParameterName (bool) [virtual]
Implements OutputGenerator.
Definition at line 969 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << " ";
}
References DB_GEN_C, and OutputGenerator::m_t.
startParameterName() [2/2]
void DocbookGenerator::startParameterName (bool) [virtual]
Implements OutputGenerator.
startParameterType() [1/2]
void DocbookGenerator::startParameterType (bool , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 306 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startParameterType() [2/2]
void DocbookGenerator::startParameterType (bool , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 306 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startParamList() [1/2]
void DocbookGenerator::startParamList (BaseOutputDocInterface::ParamListTypes , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 194 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startParamList() [2/2]
void DocbookGenerator::startParamList (BaseOutputDocInterface::ParamListTypes , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 194 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startProjectNumber() [1/2]
void DocbookGenerator::startProjectNumber () [inline], [virtual]
Implements OutputGenerator.
Definition at line 147 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startProjectNumber() [2/2]
void DocbookGenerator::startProjectNumber () [inline], [virtual]
Implements OutputGenerator.
Definition at line 147 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startQuickIndices() [1/2]
void DocbookGenerator::startQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 288 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startQuickIndices() [2/2]
void DocbookGenerator::startQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 288 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startSection() [1/2]
void DocbookGenerator::startSection (const QCString & lab, const QCString & , SectionType) [virtual]
Implements BaseOutputDocInterface.
Definition at line 993 of file docbookgen.cpp.
{
DB_GEN_C
  openSection("xml:id=\"_" + stripPath(lab) + "\"");
  m_t << "<title>";
}
References DB_GEN_C, OutputGenerator::m_t, openSection(), and stripPath().
startSection() [2/2]
void DocbookGenerator::startSection (const QCString & , const QCString & , SectionType) [virtual]
Implements BaseOutputDocInterface.
startSmall() [1/2]
void DocbookGenerator::startSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 190 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startSmall() [2/2]
void DocbookGenerator::startSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 190 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startSubsection() [1/2]
void DocbookGenerator::startSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 216 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startSubsection() [2/2]
void DocbookGenerator::startSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 216 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startSubsubsection() [1/2]
void DocbookGenerator::startSubsubsection () [virtual]
Implements BaseOutputDocInterface.
Definition at line 928 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<simplesect><title>";
}
References DB_GEN_C, and OutputGenerator::m_t.
Referenced by startCompoundTemplateParams().
startSubsubsection() [2/2]
void DocbookGenerator::startSubsubsection () [virtual]
Implements BaseOutputDocInterface.
startTextBlock() [1/2]
void DocbookGenerator::startTextBlock (bool dense) [virtual]
Implements OutputGenerator.
Definition at line 781 of file docbookgen.cpp.
{
DB_GEN_C
  if (dense)
  {
    m_denseText = TRUE;
    m_t << "<programlisting linenumbering=\"unnumbered\">";
  }
}
References DB_GEN_C, m_denseText, OutputGenerator::m_t, and TRUE.
startTextBlock() [2/2]
void DocbookGenerator::startTextBlock (bool) [virtual]
Implements OutputGenerator.
startTextLink() [1/2]
void DocbookGenerator::startTextLink (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 212 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startTextLink() [2/2]
void DocbookGenerator::startTextLink (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 212 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startTitle() [1/2]
void DocbookGenerator::startTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 196 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startTitle() [2/2]
void DocbookGenerator::startTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 196 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startTitleHead() [1/2]
void DocbookGenerator::startTitleHead (const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 821 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<title>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startTitleHead() [2/2]
void DocbookGenerator::startTitleHead (const QCString &) [virtual]
Implements OutputGenerator.
startTypewriter() [1/2]
void DocbookGenerator::startTypewriter () [virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 771 of file docbookgen.cpp.
{
DB_GEN_C
  if (!m_denseText) m_t << "<computeroutput>";
}
References DB_GEN_C, m_denseText, and OutputGenerator::m_t.
startTypewriter() [2/2]
void DocbookGenerator::startTypewriter () [virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
type() [1/2]
OutputType DocbookGenerator::type () const [inline], [virtual]
Implements OutputGenerator.
Definition at line 102 of file docbookgen.h.
{ return Docbook; }
References OutputGenerator::Docbook.
Referenced by writeCodeLink().
type() [2/2]
OutputType DocbookGenerator::type () const [inline], [virtual]
Implements OutputGenerator.
Definition at line 102 of file docbookgen.h.
{ return Docbook; }
References OutputGenerator::Docbook.
writeAnchor() [1/2]
void DocbookGenerator::writeAnchor (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 198 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeAnchor() [2/2]
void DocbookGenerator::writeAnchor (const QCString & , const QCString &) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 198 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeChar() [1/2]
void DocbookGenerator::writeChar (char c) [virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
Definition at line 938 of file docbookgen.cpp.
{
DB_GEN_C
  char cs[2];
  cs[0]=c;
  cs[1]=0;
  docify(cs);
}
References c, cs, DB_GEN_C, and docify().
writeChar() [2/2]
void DocbookGenerator::writeChar (char c) [virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
writeCodeAnchor() [1/2]
void DocbookGenerator::writeCodeAnchor (const QCString & name) [inline], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 126 of file docbookgen.h.
    { m_codeGen.writeCodeAnchor(anchor); }
References m_codeGen, and DocbookCodeGenerator::writeCodeAnchor().
writeCodeAnchor() [2/2]
void DocbookGenerator::writeCodeAnchor (const QCString & name) [inline], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 126 of file docbookgen.h.
    { m_codeGen.writeCodeAnchor(anchor); }
References m_codeGen, and DocbookCodeGenerator::writeCodeAnchor().
writeCodeLink() [1/2]
void DocbookGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [inline], [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 107 of file docbookgen.h.
    { m_codeGen.writeCodeLink(type,ref,file,anchor,name,tooltip); }
References caseconvert::file, m_codeGen, setup::name, type(), and DocbookCodeGenerator::writeCodeLink().
writeCodeLink() [2/2]
void DocbookGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [inline], [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 107 of file docbookgen.h.
    { m_codeGen.writeCodeLink(type,ref,file,anchor,name,tooltip); }
References caseconvert::file, m_codeGen, setup::name, type(), and DocbookCodeGenerator::writeCodeLink().
writeDoc() [1/2]
void DocbookGenerator::writeDoc (const IDocNodeAST * node, const Definition * ctx, const MemberDef * md, int id) [virtual]
Implements OutputGenerator.
Definition at line 626 of file docbookgen.cpp.
{
DB_GEN_C
  auto astImpl = dynamic_cast<const DocNodeAST*>(ast);
  if (astImpl)
  {
    auto visitor { DocbookDocVisitor(m_t,*this,ctx?ctx->getDefFileExtension():QCString()) };
    std::visit(visitor,astImpl->root);
  }
}
References DB_GEN_C, Definition::getDefFileExtension(), and OutputGenerator::m_t.
writeDoc() [2/2]
void DocbookGenerator::writeDoc (const IDocNodeAST * node, const Definition * ctx, const MemberDef * md, int id) [virtual]
Implements OutputGenerator.
writeEndAnnoItem() [1/2]
void DocbookGenerator::writeEndAnnoItem (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 264 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeEndAnnoItem() [2/2]
void DocbookGenerator::writeEndAnnoItem (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 264 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeFooter() [1/2]
void DocbookGenerator::writeFooter (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 142 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeFooter() [2/2]
void DocbookGenerator::writeFooter (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 142 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeGraphicalHierarchy() [1/2]
void DocbookGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 287 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeGraphicalHierarchy() [2/2]
void DocbookGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 287 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeInheritedSectionTitle() [1/2]
void DocbookGenerator::writeInheritedSectionTitle (const QCString & , const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 269 of file docbookgen.h.
                                                                      {DB_GEN_NEW};
References DB_GEN_NEW.
writeInheritedSectionTitle() [2/2]
void DocbookGenerator::writeInheritedSectionTitle (const QCString & , const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 269 of file docbookgen.h.
                                                                      {DB_GEN_NEW};
References DB_GEN_NEW.
writeLabel() [1/2]
void DocbookGenerator::writeLabel (const QCString & l, bool isLast) [virtual]
Implements OutputGenerator.
Definition at line 904 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<computeroutput>[" << l << "]</computeroutput>";
  if (!isLast) m_t << ", ";
}
References DB_GEN_C, and OutputGenerator::m_t.
writeLabel() [2/2]
void DocbookGenerator::writeLabel (const QCString & , bool) [virtual]
Implements OutputGenerator.
writeLatexSpacing() [1/2]
void DocbookGenerator::writeLatexSpacing () [inline], [virtual]
Implements OutputGenerator.
Definition at line 261 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
writeLatexSpacing() [2/2]
void DocbookGenerator::writeLatexSpacing () [inline], [virtual]
Implements OutputGenerator.
Definition at line 261 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
writeLineNumber() [1/2]
void DocbookGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [inline], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 112 of file docbookgen.h.
    { m_codeGen.writeLineNumber(ref,file,anchor,lineNumber,writeLineAnchor); }
References caseconvert::file, m_codeGen, and DocbookCodeGenerator::writeLineNumber().
writeLineNumber() [2/2]
void DocbookGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [inline], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 112 of file docbookgen.h.
    { m_codeGen.writeLineNumber(ref,file,anchor,lineNumber,writeLineAnchor); }
References caseconvert::file, m_codeGen, and DocbookCodeGenerator::writeLineNumber().
writeLogo() [1/2]
void DocbookGenerator::writeLogo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 292 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeLogo() [2/2]
void DocbookGenerator::writeLogo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 292 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeNavigationPath() [1/2]
void DocbookGenerator::writeNavigationPath (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 291 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeNavigationPath() [2/2]
void DocbookGenerator::writeNavigationPath (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 291 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeNonBreakableSpace() [1/2]
void DocbookGenerator::writeNonBreakableSpace (int n) [virtual]
Implements BaseOutputDocInterface.
Definition at line 761 of file docbookgen.cpp.
{
DB_GEN_C
  for (int i=0;i<n;i++) m_t << "&#160;";
}
References DB_GEN_C, OutputGenerator::m_t, and n.
writeNonBreakableSpace() [2/2]
void DocbookGenerator::writeNonBreakableSpace (int) [virtual]
Implements BaseOutputDocInterface.
writeObjectLink() [1/2]
void DocbookGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
Definition at line 671 of file docbookgen.cpp.
{
DB_GEN_C
  if (!anchor.isEmpty())
  {
    if (!f.isEmpty()) m_t << "<link linkend=\"_" << stripPath(f) << "_1" << anchor << "\">";
    else m_t << "<link linkend=\"_" << anchor << "\">";
  }
  else
  {
    m_t << "<link linkend=\"_" << stripPath(f) << "\">";
  }
  docify(text);
  m_t << "</link>";
}
References DB_GEN_C, docify(), f, QCString::isEmpty(), OutputGenerator::m_t, and stripPath().
writeObjectLink() [2/2]
void DocbookGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
writePageLink() [1/2]
void DocbookGenerator::writePageLink (const QCString & name, bool) [virtual]
Implements OutputGenerator.
Definition at line 604 of file docbookgen.cpp.
{
DB_GEN_C
  for (const auto &pd : *Doxygen::pageLinkedMap)
  {
    if (!pd->getGroupDef() && !pd->isReference() && pd->name() == stripPath(name))
    {
      m_t << "<chapter>\n";
      if (pd->hasTitle())
      {
        m_t << " <title>" << convertToDocBook(pd->title()) << "</title>\n";
      }
      else
      {
        m_t << " <title>" << convertToDocBook(pd->name()) << "</title>\n";
      }
      m_t << " <xi:include href=\"" << pd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
      m_t << "</chapter>\n";
    }
  }
}
References convertToDocBook(), DB_GEN_C, OutputGenerator::m_t, setup::name, Doxygen::pageLinkedMap, and stripPath().
writePageLink() [2/2]
void DocbookGenerator::writePageLink (const QCString & , bool) [virtual]
Implements OutputGenerator.
writeQuickLinks() [1/2]
void DocbookGenerator::writeQuickLinks (bool , HighlightedItem , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 293 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeQuickLinks() [2/2]
void DocbookGenerator::writeQuickLinks (bool , HighlightedItem , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 293 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeRuler() [1/2]
void DocbookGenerator::writeRuler () [virtual]
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 738 of file docbookgen.cpp.
{
DB_GEN_C2("m_inLevel " << m_inLevel)
DB_GEN_C2("m_inGroup " << m_inGroup)
  if (m_inGroup) closeSection();
  m_inGroup = FALSE;
}
References closeSection(), DB_GEN_C2, FALSE, m_inGroup, and m_inLevel.
writeRuler() [2/2]
void DocbookGenerator::writeRuler () [virtual]
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
writeSearchInfo() [1/2]
void DocbookGenerator::writeSearchInfo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 141 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeSearchInfo() [2/2]
void DocbookGenerator::writeSearchInfo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 141 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeSplitBar() [1/2]
void DocbookGenerator::writeSplitBar (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 290 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeSplitBar() [2/2]
void DocbookGenerator::writeSplitBar (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 290 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeStartAnnoItem() [1/2]
void DocbookGenerator::writeStartAnnoItem (const QCString & , const QCString & , const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 262 of file docbookgen.h.
                                                              {DB_GEN_NEW};
References DB_GEN_NEW.
writeStartAnnoItem() [2/2]
void DocbookGenerator::writeStartAnnoItem (const QCString & , const QCString & , const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 262 of file docbookgen.h.
                                                              {DB_GEN_NEW};
References DB_GEN_NEW.
writeString() [1/2]
void DocbookGenerator::writeString (const QCString & text) [virtual]
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
Definition at line 648 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << text;
}
References DB_GEN_C, and OutputGenerator::m_t.
writeString() [2/2]
void DocbookGenerator::writeString (const QCString & text) [virtual]
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
writeStyleInfo() [1/2]
void DocbookGenerator::writeStyleInfo (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 149 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeStyleInfo() [2/2]
void DocbookGenerator::writeStyleInfo (int) [inline], [virtual]
Implements OutputGenerator.
Definition at line 149 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeSummaryLink() [1/2]
void DocbookGenerator::writeSummaryLink (const QCString & , const QCString & , const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 294 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeSummaryLink() [2/2]
void DocbookGenerator::writeSummaryLink (const QCString & , const QCString & , const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 294 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeSynopsis() [1/2]
void DocbookGenerator::writeSynopsis () [inline], [virtual]
Implements OutputGenerator.
Definition at line 274 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeSynopsis() [2/2]
void DocbookGenerator::writeSynopsis () [inline], [virtual]
Implements OutputGenerator.
Definition at line 274 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeTooltip() [1/2]
void DocbookGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 114 of file docbookgen.h.
    { m_codeGen.writeTooltip(id,docInfo,decl,desc,defInfo,declInfo); }
References m_codeGen, and DocbookCodeGenerator::writeTooltip().
writeTooltip() [2/2]
void DocbookGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 114 of file docbookgen.h.
    { m_codeGen.writeTooltip(id,docInfo,decl,desc,defInfo,declInfo); }
References m_codeGen, and DocbookCodeGenerator::writeTooltip().
Member Data Documentation
m_codeGen
DocbookCodeGenerator DocbookGenerator::m_codeGen [private]
Definition at line 345 of file docbookgen.h.
Referenced by codify(), endCodeFragment(), endCodeLine(), endFile(), endFontClass(), startCodeFragment(), startCodeLine(), startFile(), startFontClass(), writeCodeAnchor(), writeCodeLink(), writeLineNumber(), and writeTooltip().
m_denseText
bool DocbookGenerator::m_denseText = false [private]
Definition at line 346 of file docbookgen.h.
Referenced by endTextBlock(), endTypewriter(), startTextBlock(), and startTypewriter().
m_descTable
bool DocbookGenerator::m_descTable = false [private]
Definition at line 351 of file docbookgen.h.
Referenced by endDescTable(), startDescTable(), and startDoxyAnchor().
m_firstMember
bool DocbookGenerator::m_firstMember = false [private]
Definition at line 354 of file docbookgen.h.
Referenced by startDoxyAnchor(), and startGroupHeader().
m_inGroup
bool DocbookGenerator::m_inGroup = false [private]
Definition at line 347 of file docbookgen.h.
Referenced by endFile(), endMemberDocList(), startGroupHeader(), and writeRuler().
m_inLevel
int DocbookGenerator::m_inLevel = -1 [private]
Definition at line 353 of file docbookgen.h.
Referenced by endFile(), startGroupHeader(), startMemberDoc(), and writeRuler().
m_inListItem
bool DocbookGenerator::m_inListItem = { false, } [private]
Definition at line 349 of file docbookgen.h.
Referenced by endMemberList(), startDoxyAnchor(), and startMemberItem().
m_inSimpleSect
bool DocbookGenerator::m_inSimpleSect = { false, } [private]
Definition at line 350 of file docbookgen.h.
Referenced by endMemberList(), startGroupHeader(), and startMemberHeader().
m_levelListItem
int DocbookGenerator::m_levelListItem = 0 [private]
Definition at line 348 of file docbookgen.h.
Referenced by endMemberList(), startDoxyAnchor(), startGroupHeader(), startMemberHeader(), startMemberItem(), and startMemberList().
m_openSectionCount
int DocbookGenerator::m_openSectionCount = 0 [private]
Definition at line 355 of file docbookgen.h.
Referenced by closeAllSections(), closeSection(), and openSection().
m_simpleTable
bool DocbookGenerator::m_simpleTable = false [private]
Definition at line 352 of file docbookgen.h.
Referenced by endMemberDocSimple(), startDoxyAnchor(), and startMemberDocSimple().
relPath
QCString DocbookGenerator::relPath [private]
Definition at line 344 of file docbookgen.h.
Referenced by endCallGraph(), endClassDiagram(), endDirDepGraph(), endDotGraph(), endGroupCollaboration(), endInclDepGraph(), and startFile().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docbookgen.h
doxygen/src/docbookgen.h
doxygen/build/doxygen/src/docbookgen.cpp
doxygen/src/docbookgen.cpp