Expert Class Reference
#include <expert.h>
Public Slots
void activateTopic (QTreeWidgetItem *, QTreeWidgetItem *)
QWidget * createTopicWidget (QDomElement &elem)
void refresh ()
void activateTopic (QTreeWidgetItem *, QTreeWidgetItem *)
QWidget * createTopicWidget (QDomElement &elem)
void refresh ()
Signals
void changed ()
void done ()
void changed ()
void done ()
Public Member Functions
Expert ()
~Expert ()
void loadSettings (QSettings *)
void saveSettings (QSettings *)
void loadConfig (const QString &fileName)
bool writeConfig (QTextStream &t, bool brief, bool condensed)
QByteArray saveInnerState () const
bool restoreInnerState (const QByteArray &state)
const QHash< QString, Input * > & modelData () const
void resetToDefaults ()
bool htmlOutputPresent (const QString &workingDir) const
bool pdfOutputPresent (const QString &workingDir) const
QString getHtmlOutputIndex (const QString &workingDir) const
void setHeader (const char *name)
void add (const char *name, const char *doc)
Expert ()
~Expert ()
void loadSettings (QSettings *)
void saveSettings (QSettings *)
void loadConfig (const QString &fileName)
bool writeConfig (QTextStream &t, bool brief, bool condensed)
QByteArray saveInnerState () const
bool restoreInnerState (const QByteArray &state)
const QHash< QString, Input * > & modelData () const
void resetToDefaults ()
bool htmlOutputPresent (const QString &workingDir) const
bool pdfOutputPresent (const QString &workingDir) const
QString getHtmlOutputIndex (const QString &workingDir) const
void setHeader (const char *name)
void add (const char *name, const char *doc)
Private Slots
void showHelp (Input *)
void nextTopic ()
void prevTopic ()
void showHelp (Input *)
void nextTopic ()
void prevTopic ()
Private Member Functions
void createTopics (const QDomElement &)
void saveTopic (QTextStream &t, QDomElement &elem, TextCodecAdapter *codec, bool brief, bool dondensed)
void createTopics (const QDomElement &)
void saveTopic (QTextStream &t, QDomElement &elem, TextCodecAdapter *codec, bool brief, bool dondensed)
Private Attributes
QSplitter * m_splitter
QTextBrowser * m_helper
QTreeWidget * m_treeWidget
QStackedWidget * m_topicStack
QHash< QString, QWidget * > m_topics
QHash< QString, QObject * > m_optionWidgets
QHash< QString, Input * > m_options
QPushButton * m_next
QPushButton * m_prev
QDomElement m_rootElement
bool m_inShowHelp
QString m_header
Detailed Description
Definition at line 31 of file expert.h.
Constructor & Destructor Documentation
Expert() [1/2]
Expert::Expert ()
Definition at line 72 of file expert.cpp.
{
  m_treeWidget = new QTreeWidget;
  m_treeWidget->setColumnCount(1);
  m_topicStack = new QStackedWidget;
  m_inShowHelp = false;
  QFile file(SA(":/config.xml"));
  QString err;
  int errLine,errCol;
  QDomDocument configXml;
  if (file.open(QIODevice::ReadOnly))
  {
    if (!configXml.setContent(&file,false,&err,&errLine,&errCol))
    {
      QString msg = tr("Error parsing internal config.xml at line %1 column %2.\n%3").
                  arg(errLine).arg(errCol).arg(err);
      QMessageBox::warning(this, tr("Error"), msg);
      exit(1);
    }
  }
  m_rootElement = configXml.documentElement();
  createTopics(m_rootElement);
  m_helper = new QTextBrowser;
  m_helper->setReadOnly(true);
  m_helper->setOpenExternalLinks(true);
  m_splitter = new QSplitter(Qt::Vertical);
  m_splitter->addWidget(m_treeWidget);
  m_splitter->addWidget(m_helper);
  QWidget *rightSide = new QWidget;
  QGridLayout *grid = new QGridLayout(rightSide);
  m_prev = new QPushButton(tr("Previous"));
  m_prev->setEnabled(false);
  m_next = new QPushButton(tr("Next"));
  grid->addWidget(m_topicStack,0,0,1,2);
  grid->addWidget(m_prev,1,0,Qt::AlignLeft);
  grid->addWidget(m_next,1,1,Qt::AlignRight);
  grid->setColumnStretch(0,1);
  grid->setRowStretch(0,1);
  addWidget(m_splitter);
  addWidget(rightSide);
  connect(m_next,SIGNAL(clicked()),SLOT(nextTopic()));
  connect(m_prev,SIGNAL(clicked()),SLOT(prevTopic()));
  addConfigDocs(this);
}
References addConfigDocs(), AlignLeft, AlignRight, createTopics(), err(), caseconvert::file, m_helper, m_inShowHelp, m_next, m_prev, m_rootElement, m_splitter, m_topicStack, m_treeWidget, msg(), nextTopic(), prevTopic(), and SA.
 Expert() [1/2]
Expert::~Expert ()
Definition at line 123 of file expert.cpp.
{
  QHashIterator<QString,Input*> i(m_options);
  while (i.hasNext())
  {
    i.next();
    delete i.value();
  }
}
References m_options.
Expert() [2/2]
Expert::Expert ()
 Expert() [2/2]
Expert::~Expert ()
Member Function Documentation
activateTopic [1/2]
void Expert::activateTopic (QTreeWidgetItem * item, QTreeWidgetItem *) [slot]
Definition at line 741 of file expert.cpp.
{
  if (item)
  {
    QWidget *w = m_topics[item->text(0)];
    m_topicStack->setCurrentWidget(w);
    m_prev->setEnabled(m_topicStack->currentIndex()!=0);
    m_next->setEnabled(true);
  }
}
References m_next, m_prev, m_topics, m_topicStack, and w.
Referenced by createTopics().
activateTopic [2/2]
void Expert::activateTopic (QTreeWidgetItem * , QTreeWidgetItem *) [slot]
add() [1/2]
void Expert::add (const char * name, const char * doc) [virtual]
Implements DocIntf.
Definition at line 61 of file expert.cpp.
{
  Input *opt = m_options[SA(name)];
  if (opt)
  {
    opt->setTemplateDocs(SA(docs));
  }
}
References m_options, setup::name, SA, and Input::setTemplateDocs().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [2/2]
void Expert::add (const char * name, const char * doc) [virtual]
Implements DocIntf.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
changed [1/2]
void Expert::changed () [signal]
Referenced by createTopicWidget().
changed [2/2]
void Expert::changed () [signal]
createTopics() [1/2]
void Expert::createTopics (const QDomElement & rootElem) [private]
Definition at line 133 of file expert.cpp.
{
  QList<QTreeWidgetItem*> items;
  QDomElement childElem = rootElem.firstChildElement();
  while (!childElem.isNull())
  {
    if (childElem.tagName()==SA("group"))
    {
      // Remove _ from a group name like: Source_Browser
      QString name = childElem.attribute(SA("name")).replace(SA("_"),SA(" "));
      QString setting = childElem.attribute(SA("setting"));
      if (setting.isEmpty() || IS_SUPPORTED(setting.toLatin1()))
      {
        items.append(new QTreeWidgetItem((QTreeWidget*)0,QStringList(name)));
        QWidget *widget = createTopicWidget(childElem);
        m_topics[name] = widget;
        m_topicStack->addWidget(widget);
      }
    }
    childElem = childElem.nextSiblingElement();
  }
  m_treeWidget->setHeaderLabels(QStringList() << SA("Topics"));
  m_treeWidget->insertTopLevelItems(0,items);
  connect(m_treeWidget,
          SIGNAL(currentItemChanged(QTreeWidgetItem *,QTreeWidgetItem *)),
          this,
          SLOT(activateTopic(QTreeWidgetItem *,QTreeWidgetItem *)));
}
References activateTopic(), createTopicWidget(), m_topics, m_topicStack, m_treeWidget, setup::name, and SA.
Referenced by Expert().
createTopics() [2/2]
void Expert::createTopics (const QDomElement &) [private]
createTopicWidget [1/2]
QWidget * Expert::createTopicWidget (QDomElement & elem) [slot]
Definition at line 497 of file expert.cpp.
{
  QScrollArea *area = new QScrollArea;
  QWidget *topic = new QWidget;
  QGridLayout *layout = new QGridLayout(topic);
  QDomElement child = elem.firstChildElement();
  int row=0;
  while (!child.isNull())
  {
    QString setting = child.attribute(SA("setting"));
    if (setting.isEmpty() || IS_SUPPORTED(setting.toLatin1()))
    {
      QString type = child.attribute(SA("type"));
      QString docs = getDocsForNode(child);
      if (type==SA("bool"))
      {
        InputBool *boolOption =
          new InputBool(
              layout,row,
              child.attribute(SA("id")),
              child.attribute(SA("defval"))==SA("1"),
              docs
              );
        m_options.insert(
            child.attribute(SA("id")),
            boolOption
            );
        connect(boolOption,SIGNAL(showHelp(Input*)),SLOT(showHelp(Input*)));
        connect(boolOption,SIGNAL(changed()),SIGNAL(changed()));
      }
      else if (type==SA("string"))
      {
        InputString::StringMode mode;
        QString format = child.attribute(SA("format"));
        if (format==SA("dir"))
        {
          mode = InputString::StringDir;
        }
        else if (format==SA("file"))
        {
          mode = InputString::StringFile;
        }
        else if (format==SA("filedir"))
        {
          mode = InputString::StringFileDir;
        }
        else if (format==SA("image"))
        {
          mode = InputString::StringImage;
        }
        else // format=="string"
        {
          mode = InputString::StringFree;
        }
        InputString *stringOption =
          new InputString(
              layout,row,
              child.attribute(SA("id")),
              child.attribute(SA("defval")),
              mode,
              docs,
              child.attribute(SA("abspath"))
              );
        m_options.insert(
            child.attribute(SA("id")),
            stringOption
            );
        connect(stringOption,SIGNAL(showHelp(Input*)),SLOT(showHelp(Input*)));
        connect(stringOption,SIGNAL(changed()),SIGNAL(changed()));
      }
      else if (type==SA("enum"))
      {
        InputString *enumList = new InputString(
            layout,row,
            child.attribute(SA("id")),
            child.attribute(SA("defval")),
            InputString::StringFixed,
            docs
            );
        QDomElement enumVal = child.firstChildElement();
        while (!enumVal.isNull())
        {
          if (enumVal.tagName()==SA("value"))
          {
            enumList->addValue(enumVal.attribute(SA("name")));
          }
          enumVal = enumVal.nextSiblingElement();
        }
        enumList->setDefault();
        m_options.insert(child.attribute(SA("id")),enumList);
        connect(enumList,SIGNAL(showHelp(Input*)),SLOT(showHelp(Input*)));
        connect(enumList,SIGNAL(changed()),SIGNAL(changed()));
      }
      else if (type==SA("int"))
      {
        InputInt *intOption =
          new InputInt(
              layout,row,
              child.attribute(SA("id")),
              child.attribute(SA("defval")).toInt(),
              child.attribute(SA("minval")).toInt(),
              child.attribute(SA("maxval")).toInt(),
              docs
              );
        m_options.insert(
            child.attribute(SA("id")),
            intOption
            );
        connect(intOption,SIGNAL(showHelp(Input*)),SLOT(showHelp(Input*)));
        connect(intOption,SIGNAL(changed()),SIGNAL(changed()));
      }
      else if (type==SA("list"))
      {
        InputStrList::ListMode mode;
        QString format = child.attribute(SA("format"));
        if (format==SA("dir"))
        {
          mode = InputStrList::ListDir;
        }
        else if (format==SA("file"))
        {
          mode = InputStrList::ListFile;
        }
        else if (format==SA("filedir"))
        {
          mode = InputStrList::ListFileDir;
        }
        else // format=="string"
        {
          mode = InputStrList::ListString;
        }
        QStringList sl;
        QDomElement listVal = child.firstChildElement();
        while (!listVal.isNull())
        {
          if (listVal.tagName()==SA("value"))
          {
            sl.append(listVal.attribute(SA("name")));
          }
          listVal = listVal.nextSiblingElement();
        }
        InputStrList *listOption =
          new InputStrList(
              layout,row,
              child.attribute(SA("id")),
              sl,
              mode,
              docs
              );
        m_options.insert(
            child.attribute(SA("id")),
            listOption
            );
        connect(listOption,SIGNAL(showHelp(Input*)),SLOT(showHelp(Input*)));
        connect(listOption,SIGNAL(changed()),SIGNAL(changed()));
      }
      else if (type==SA("obsolete"))
      {
        Input::Kind orgKind;
        QString orgKindStr = child.attribute(SA("orgtype"));
        if (orgKindStr==SA("int"))
        {
          orgKind = Input::Int;
        }
        else if (orgKindStr==SA("bool"))
        {
          orgKind = Input::Bool;
        }
        else if (orgKindStr==SA("string") || orgKindStr==SA("enum"))
        {
          orgKind = Input::String;
        }
        else if (orgKindStr==SA("strlist"))
        {
          orgKind = Input::StrList;
        }
        else
        {
          orgKind = Input::Obsolete;
        }
        InputObsolete *obsoleteOption =
          new InputObsolete(child.attribute(SA("id")),orgKind);
        m_options.insert(child.attribute(SA("id")),obsoleteOption);
        // ignore
      }
      else // should not happen
      {
        printf("Unsupported type %s\n",qPrintable(child.attribute(SA("type"))));
      }
    } // IS_SUPPORTED
    child = child.nextSiblingElement();
  }
  // compute dependencies between options
  child = elem.firstChildElement();
  while (!child.isNull())
  {
    QString setting = child.attribute(SA("setting"));
    QString dependsOn = child.attribute(SA("depends"));
    QString id = child.attribute(SA("id"));
    if (!dependsOn.isEmpty() &&
        (setting.isEmpty() || IS_SUPPORTED(setting.toLatin1())))
    {
       Input *parentOption = m_options[dependsOn];
       if (parentOption==0)
       {
         printf("%s has depends=%s that is not valid\n",
             qPrintable(id),qPrintable(dependsOn));
       }
       Input *thisOption = m_options[id];
       Q_ASSERT(parentOption);
       Q_ASSERT(thisOption);
       if (parentOption && thisOption)
       {
         //printf("Adding dependency '%s' (%p)->'%s' (%p)\n",
         // qPrintable(dependsOn),parentOption,
         // qPrintable(id),thisOption);
         parentOption->addDependency(thisOption);
       }
    }
    child = child.nextSiblingElement();
  }
  // set initial dependencies
  QHashIterator<QString,Input*> i(m_options);
  while (i.hasNext())
  {
    i.next();
    if (i.value())
    {
      i.value()->updateDependencies();
    }
  }
  layout->setRowStretch(row,1);
  layout->setColumnStretch(1,2);
  layout->setSpacing(5);
  topic->setLayout(layout);
  area->setWidget(topic);
  area->setWidgetResizable(true);
  return area;
}
References Input::addDependency(), InputString::addValue(), Input::Bool, changed(), getDocsForNode(), id, Input::Int, InputStrList::ListDir, InputStrList::ListFile, InputStrList::ListFileDir, InputStrList::ListString, m_options, mode, Input::Obsolete, SA, InputString::setDefault(), showHelp(), caseconvert::sl, Input::String, InputString::StringDir, InputString::StringFile, InputString::StringFileDir, InputString::StringFixed, InputString::StringFree, InputString::StringImage, and Input::StrList.
Referenced by createTopics().
createTopicWidget [2/2]
QWidget * Expert::createTopicWidget (QDomElement & elem) [slot]
done [1/2]
void Expert::done () [signal]
Referenced by nextTopic().
done [2/2]
void Expert::done () [signal]
getHtmlOutputIndex() [1/2]
QString Expert::getHtmlOutputIndex (const QString & workingDir) const
Definition at line 960 of file expert.cpp.
{
  QString outputDir = getStringOption(m_options,QString::fromLatin1("OUTPUT_DIRECTORY"));
  QString htmlOutputDir = getStringOption(m_options,QString::fromLatin1("HTML_OUTPUT"));
  //printf("outputDir=%s\n",qPrintable(outputDir));
  //printf("htmlOutputDir=%s\n",qPrintable(htmlOutputDir));
  QString indexFile = workingDir;
  if (QFileInfo(outputDir).isAbsolute()) // override
  {
    indexFile = outputDir;
  }
  else // append
  {
    indexFile += QString::fromLatin1("/")+outputDir;
  }
  if (QFileInfo(htmlOutputDir).isAbsolute()) // override
  {
    indexFile = htmlOutputDir;
  }
  else // append
  {
    indexFile += QString::fromLatin1("/")+htmlOutputDir;
  }
  indexFile+=QString::fromLatin1("/index.html");
  return indexFile;
}
References getStringOption(), and m_options.
Referenced by htmlOutputPresent(), and MainWindow::showHtmlOutput().
getHtmlOutputIndex() [2/2]
QString Expert::getHtmlOutputIndex (const QString & workingDir) const
htmlOutputPresent() [1/2]
bool Expert::htmlOutputPresent (const QString & workingDir) const
Definition at line 951 of file expert.cpp.
{
  bool generateHtml = getBoolOption(m_options,QString::fromLatin1("GENERATE_HTML"));
  if (!generateHtml || workingDir.isEmpty()) return false;
  QString indexFile = getHtmlOutputIndex(workingDir);
  QFileInfo fi(indexFile);
  return fi.exists() && fi.isFile();
}
References getBoolOption(), getHtmlOutputIndex(), and m_options.
Referenced by MainWindow::updateLaunchButtonState().
htmlOutputPresent() [2/2]
bool Expert::htmlOutputPresent (const QString & workingDir) const
loadConfig() [1/2]
void Expert::loadConfig (const QString & fileName)
Definition at line 782 of file expert.cpp.
{
  //printf("Expert::loadConfig(%s)\n",qPrintable(fileName));
  parseConfig(fileName,m_options);
}
References m_options, and parseConfig().
Referenced by MainWindow::loadConfigFromFile().
loadConfig() [2/2]
void Expert::loadConfig (const QString & fileName)
loadSettings() [1/2]
void Expert::loadSettings (QSettings * s)
Definition at line 752 of file expert.cpp.
{
  QHashIterator<QString,Input*> i(m_options);
  while (i.hasNext())
  {
    i.next();
    QVariant var = s->value(SA("config/")+i.key());
    if (i.value() && var.isValid())
    {
      //printf("Loading key %s: type=%d value='%s'\n",qPrintable(i.key()),var.type(),qPrintable(var.toString()));
      i.value()->value() = var;
      i.value()->update();
    }
  }
}
References m_options, s, SA, and var.
Referenced by MainWindow::loadSettings().
loadSettings() [2/2]
void Expert::loadSettings (QSettings *)
modelData() [1/2]
const QHash< QString, Input * > & Expert::modelData () const [inline]
Definition at line 44 of file expert.h.
{ return m_options; }
References m_options.
Referenced by MainWindow::MainWindow().
modelData() [2/2]
const QHash< QString, Input * > & Expert::modelData () const [inline]
Definition at line 44 of file expert.h.
{ return m_options; }
References m_options.
nextTopic [1/2]
void Expert::nextTopic () [private], [slot]
Definition at line 891 of file expert.cpp.
{
  if (m_topicStack->currentIndex()+1==m_topicStack->count()) // last topic
  {
    done();
  }
  else
  {
    m_topicStack->setCurrentIndex(m_topicStack->currentIndex()+1);
    m_next->setEnabled(m_topicStack->count()!=m_topicStack->currentIndex()+1);
    m_prev->setEnabled(m_topicStack->currentIndex()!=0);
    m_treeWidget->setCurrentItem(m_treeWidget->invisibleRootItem()->child(m_topicStack->currentIndex()));
  }
}
References done(), m_next, m_prev, m_topicStack, and m_treeWidget.
Referenced by Expert().
nextTopic [2/2]
void Expert::nextTopic () [private], [slot]
pdfOutputPresent() [1/2]
bool Expert::pdfOutputPresent (const QString & workingDir) const
Definition at line 987 of file expert.cpp.
{
  bool generateLatex = getBoolOption(m_options,QString::fromLatin1("GENERATE_LATEX"));
  bool pdfLatex = getBoolOption(m_options,QString::fromLatin1("USE_PDFLATEX"));
  if (!generateLatex || !pdfLatex) return false;
  QString latexOutput = getStringOption(m_options,QString::fromLatin1("LATEX_OUTPUT"));
  QString indexFile;
  if (QFileInfo(latexOutput).isAbsolute())
  {
    indexFile = latexOutput+QString::fromLatin1("/refman.pdf");
  }
  else
  {
    indexFile = workingDir+QString::fromLatin1("/")+
                latexOutput+QString::fromLatin1("/refman.pdf");
  }
  QFileInfo fi(indexFile);
  return fi.exists() && fi.isFile();
}
References getBoolOption(), getStringOption(), and m_options.
Referenced by MainWindow::updateLaunchButtonState().
pdfOutputPresent() [2/2]
bool Expert::pdfOutputPresent (const QString & workingDir) const
prevTopic [1/2]
void Expert::prevTopic () [private], [slot]
Definition at line 906 of file expert.cpp.
{
  m_topicStack->setCurrentIndex(m_topicStack->currentIndex()-1);
  m_next->setEnabled(m_topicStack->count()!=m_topicStack->currentIndex()+1);
  m_prev->setEnabled(m_topicStack->currentIndex()!=0);
  m_treeWidget->setCurrentItem(m_treeWidget->invisibleRootItem()->child(m_topicStack->currentIndex()));
}
References m_next, m_prev, m_topicStack, and m_treeWidget.
Referenced by Expert().
prevTopic [2/2]
void Expert::prevTopic () [private], [slot]
refresh [1/2]
void Expert::refresh () [slot]
Definition at line 1007 of file expert.cpp.
{
  m_treeWidget->setCurrentItem(m_treeWidget->invisibleRootItem()->child(0));
}
References m_treeWidget.
Referenced by MainWindow::selectTab().
refresh [2/2]
void Expert::refresh () [slot]
resetToDefaults() [1/2]
void Expert::resetToDefaults ()
Definition at line 914 of file expert.cpp.
{
  //printf("Expert::makeDefaults()\n");
  QHashIterator<QString,Input*> i(m_options);
  while (i.hasNext())
  {
    i.next();
    if (i.value())
    {
      i.value()->reset();
    }
  }
}
References m_options.
Referenced by MainWindow::resetToDefaults().
resetToDefaults() [2/2]
void Expert::resetToDefaults ()
restoreInnerState() [1/2]
bool Expert::restoreInnerState (const QByteArray & state)
Definition at line 869 of file expert.cpp.
{
  return m_splitter->restoreState(state);
}
References m_splitter.
restoreInnerState() [2/2]
bool Expert::restoreInnerState (const QByteArray & state)
saveInnerState() [1/2]
QByteArray Expert::saveInnerState () const
Definition at line 864 of file expert.cpp.
{
  return m_splitter->saveState();
}
References m_splitter.
saveInnerState() [2/2]
QByteArray Expert::saveInnerState () const
saveSettings() [1/2]
void Expert::saveSettings (QSettings * s)
Definition at line 768 of file expert.cpp.
{
  QHashIterator<QString,Input*> i(m_options);
  while (i.hasNext())
  {
    i.next();
    //printf("Saving key %s: type=%d value='%s'\n",qPrintable(i.key()),i.value()->value().type(),qPrintable(i.value()->value().toString()));
    if (i.value())
    {
      s->setValue(SA("config/")+i.key(),i.value()->value());
    }
  }
}
References m_options, s, and SA.
Referenced by MainWindow::makeDefaults().
saveSettings() [2/2]
void Expert::saveSettings (QSettings *)
saveTopic() [1/2]
void Expert::saveTopic (QTextStream & t, QDomElement & elem, TextCodecAdapter * codec, bool brief, bool dondensed) [private]
Definition at line 788 of file expert.cpp.
{
  if (!brief)
  {
    t << "\n";
  }
  if (!condensed)
  {
    t << "#---------------------------------------------------------------------------\n";
    t << "# " << elem.attribute(SA("docs")) << "\n";
    t << "#---------------------------------------------------------------------------\n";
  }
  // write options...
  QDomElement childElem = elem.firstChildElement();
  while (!childElem.isNull())
  {
    QString setting = childElem.attribute(SA("setting"));
    QString type = childElem.attribute(SA("type"));
    QString name = childElem.attribute(SA("id"));
    if (setting.isEmpty() || IS_SUPPORTED(setting.toLatin1()))
    {
      QHash<QString,Input*>::const_iterator i = m_options.find(name);
      if (i!=m_options.end())
      {
        Input *option = i.value();
        if (option->kind()!=Input::Obsolete)
        {
          if (option && !brief)
          {
            t << "\n";
            t << convertToComment(option->templateDocs());
            t << "\n";
          }
          bool toPrint = true;
          if (option && condensed) toPrint = !option->isDefault();
          if (toPrint)
          {
            t << name.leftJustified(MAX_OPTION_LENGTH) << "=";
            if (option && !option->isEmpty())
            {
              t << " ";
              option->writeValue(t,codec);
            }
            t << "\n";
          }
        }
      }
    }
    childElem = childElem.nextSiblingElement();
  }
}
References convertToComment(), Input::isDefault(), Input::isEmpty(), Input::kind(), m_options, MAX_OPTION_LENGTH, setup::name, Input::Obsolete, SA, Input::templateDocs(), Input::value(), and Input::writeValue().
Referenced by writeConfig().
saveTopic() [2/2]
void Expert::saveTopic (QTextStream & t, QDomElement & elem, TextCodecAdapter * codec, bool brief, bool dondensed) [private]
setHeader() [1/2]
void Expert::setHeader (const char * name) [virtual]
Implements DocIntf.
Definition at line 56 of file expert.cpp.
{
  m_header = SA(header);
}
References m_header, and SA.
setHeader() [2/2]
void Expert::setHeader (const char * name) [virtual]
Implements DocIntf.
showHelp [1/2]
void Expert::showHelp (Input * option) [private], [slot]
Definition at line 874 of file expert.cpp.
{
  if (!m_inShowHelp)
  {
    m_inShowHelp = true;
    m_helper->setText(
        QString::fromLatin1("<qt><b>")+option->id()+
        QString::fromLatin1("</b><br>")+
        QString::fromLatin1("<br/>")+
        option->docs().
        replace(QChar::fromLatin1('\n'),QChar::fromLatin1(' '))+
        QString::fromLatin1("</qt>")
        );
    m_inShowHelp = false;
  }
}
References Input::docs(), Input::id(), m_helper, m_inShowHelp, and reg::replace().
Referenced by createTopicWidget().
showHelp [2/2]
void Expert::showHelp (Input *) [private], [slot]
writeConfig() [1/2]
bool Expert::writeConfig (QTextStream & t, bool brief, bool condensed)
Definition at line 841 of file expert.cpp.
{
  // write global header
  t << "# Doxyfile " << getDoxygenVersion() << "\n\n";
  if (!brief && !condensed)
  {
    t << convertToComment(m_header);
  }
  Input *option = m_options[QString::fromLatin1("DOXYFILE_ENCODING")];
  TextCodecAdapter codec(option->value().toString().toLatin1());
  QDomElement childElem = m_rootElement.firstChildElement();
  while (!childElem.isNull())
  {
    if (childElem.tagName()==SA("group"))
    {
      saveTopic(t,childElem,&codec,brief,condensed);
    }
    childElem = childElem.nextSiblingElement();
  }
  return true;
}
References convertToComment(), getDoxygenVersion(), m_header, m_options, m_rootElement, SA, saveTopic(), and Input::value().
Referenced by MainWindow::runDoxygen(), MainWindow::saveConfig(), and MainWindow::showSettings().
writeConfig() [2/2]
bool Expert::writeConfig (QTextStream & t, bool brief, bool condensed)
Member Data Documentation
m_header
QString Expert::m_header [private]
Definition at line 83 of file expert.h.
Referenced by setHeader(), and writeConfig().
m_helper
QTextBrowser * Expert::m_helper [private]
Definition at line 73 of file expert.h.
Referenced by Expert(), and showHelp().
m_inShowHelp
bool Expert::m_inShowHelp [private]
Definition at line 82 of file expert.h.
Referenced by Expert(), and showHelp().
m_next
QPushButton * Expert::m_next [private]
Definition at line 79 of file expert.h.
Referenced by activateTopic(), Expert(), nextTopic(), and prevTopic().
m_options
QHash< QString, Input * > Expert::m_options [private]
Definition at line 78 of file expert.h.
Referenced by add(), createTopicWidget(), getHtmlOutputIndex(), htmlOutputPresent(), loadConfig(), loadSettings(), modelData(), pdfOutputPresent(), resetToDefaults(), saveSettings(), saveTopic(), writeConfig(), and ~Expert().
m_optionWidgets
QHash< QString, QObject * > Expert::m_optionWidgets [private]
Definition at line 77 of file expert.h.
m_prev
QPushButton * Expert::m_prev [private]
Definition at line 80 of file expert.h.
Referenced by activateTopic(), Expert(), nextTopic(), and prevTopic().
m_rootElement
QDomElement Expert::m_rootElement [private]
Definition at line 81 of file expert.h.
Referenced by Expert(), and writeConfig().
m_splitter
QSplitter * Expert::m_splitter [private]
Definition at line 72 of file expert.h.
Referenced by Expert(), restoreInnerState(), and saveInnerState().
m_topics
QHash< QString, QWidget * > Expert::m_topics [private]
Definition at line 76 of file expert.h.
Referenced by activateTopic(), and createTopics().
m_topicStack
QStackedWidget * Expert::m_topicStack [private]
Definition at line 75 of file expert.h.
Referenced by activateTopic(), createTopics(), Expert(), nextTopic(), and prevTopic().
m_treeWidget
QTreeWidget * Expert::m_treeWidget [private]
Definition at line 74 of file expert.h.
Referenced by createTopics(), Expert(), nextTopic(), prevTopic(), and refresh().
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/expert.h
doxygen/build/doxygen/addon/doxywizard/expert.h
doxygen/addon/doxywizard/expert.cpp
doxygen/build/doxygen/addon/doxywizard/expert.cpp