ExampleListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
ExampleListContext ()
virtual ~ExampleListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
ExampleListContext ()
virtual ~ExampleListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc ()
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 837 of file context.h.
Constructor & Destructor Documentation
ExampleListContext() [1/2]
ExampleListContext::ExampleListContext ()
Definition at line 6693 of file context.cpp.
                                       : p(std::make_unique<Private>())
{
}
 ExampleListContext() [1/2]
ExampleListContext::~ExampleListContext () [virtual]
Definition at line 6697 of file context.cpp.
{
}
ExampleListContext() [2/2]
ExampleListContext::ExampleListContext ()
 ExampleListContext() [2/2]
virtual ExampleListContext::~ExampleListContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr ExampleListContext::alloc () [inline], [static]
Definition at line 840 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ExampleListContext>()); }
Referenced by generateOutputViaTemplate().
alloc() [2/2]
static TemplateListIntfPtr ExampleListContext::alloc () [inline], [static]
Definition at line 840 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ExampleListContext>()); }
at() [1/2]
TemplateVariant ExampleListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 6707 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant ExampleListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t ExampleListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 6702 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t ExampleListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr ExampleListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 6712 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr ExampleListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > ExampleListContext::p [private]
Definition at line 853 of file context.h.
Referenced by at(), count(), and createIterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp