TranslatorHindi Class Reference
#include <translator_hi.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
Additional Inherited Members
Detailed Description
It is not necessary to include `translator.h` or `translator_adapter.h` here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 154 of file translator_hi.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorHindi::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 189 of file translator_hi.h.
    { return "0x439 Hindi"; }
getLanguageString() [2/2]
virtual QCString TranslatorHindi::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 189 of file translator_hi.h.
    { return "0x439 Hindi"; }
idLanguage() [1/2]
virtual QCString TranslatorHindi::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 166 of file translator_hi.h.
    { return "hindi"; }
idLanguage() [2/2]
virtual QCString TranslatorHindi::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 166 of file translator_hi.h.
    { return "hindi"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorHindi::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 183 of file translator_hi.h.
    { return ""; }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorHindi::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 183 of file translator_hi.h.
    { return ""; }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorHindi::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1865 of file translator_hi.h.
    { return " "; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorHindi::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1865 of file translator_hi.h.
    { return " "; }
trAll() [1/2]
virtual QCString TranslatorHindi::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1392 of file translator_hi.h.
    { return ""; }
trAll() [2/2]
virtual QCString TranslatorHindi::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1392 of file translator_hi.h.
    { return ""; }
trAndMore() [1/2]
virtual QCString TranslatorHindi::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1841 of file translator_hi.h.
    { return " " + number + " ..."; }
trAndMore() [2/2]
virtual QCString TranslatorHindi::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1841 of file translator_hi.h.
    { return " " + number + " ..."; }
trAttention() [1/2]
virtual QCString TranslatorHindi::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 992 of file translator_hi.h.
    { return ""; }
trAttention() [2/2]
virtual QCString TranslatorHindi::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 992 of file translator_hi.h.
    { return ""; }
trAuthor() [1/2]
virtual QCString TranslatorHindi::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1282 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorHindi::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1282 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorHindi::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1136 of file translator_hi.h.
    { return ""; }
trBug() [2/2]
virtual QCString TranslatorHindi::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1136 of file translator_hi.h.
    { return ""; }
trBugList() [1/2]
virtual QCString TranslatorHindi::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1140 of file translator_hi.h.
    { return " "; }
trBugList() [2/2]
virtual QCString TranslatorHindi::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1140 of file translator_hi.h.
    { return " "; }
trCallerGraph() [1/2]
virtual QCString TranslatorHindi::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1504 of file translator_hi.h.
    {
      return " :";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorHindi::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1504 of file translator_hi.h.
    {
      return " :";
    }
trCallGraph() [1/2]
virtual QCString TranslatorHindi::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1396 of file translator_hi.h.
    { return " :"; }
trCallGraph() [2/2]
virtual QCString TranslatorHindi::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1396 of file translator_hi.h.
    { return " :"; }
trCiteReferences() [1/2]
virtual QCString TranslatorHindi::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1817 of file translator_hi.h.
    { return ""; }
trCiteReferences() [2/2]
virtual QCString TranslatorHindi::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1817 of file translator_hi.h.
    { return ""; }
trClass() [1/2]
virtual QCString TranslatorHindi::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1189 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorHindi::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1189 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorHindi::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 575 of file translator_hi.h.
    { return clName + " :"; }
trClassDiagram() [2/2]
virtual QCString TranslatorHindi::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 575 of file translator_hi.h.
    { return clName + " :"; }
trClassDocumentation() [1/2]
virtual QCString TranslatorHindi::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 459 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
        return trDesignUnitDocumentation();
      else
        return " ";
    }
References Config_getBool, and trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorHindi::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 459 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
        return trDesignUnitDocumentation();
      else
        return " ";
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorHindi::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1107 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return "";
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorHindi::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1107 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return "";
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorHindi::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 280 of file translator_hi.h.
    { return " "; }
trClassHierarchy() [2/2]
virtual QCString TranslatorHindi::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 280 of file translator_hi.h.
    { return " "; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorHindi::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 327 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
        return " :";
      else
        return " , , :";
    }
References Config_getBool.
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorHindi::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 327 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
        return " :";
      else
        return " , , :";
    }
References Config_getBool.
trClassMethods() [1/2]
virtual QCString TranslatorHindi::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1899 of file translator_hi.h.
    { return " "; }
trClassMethods() [2/2]
virtual QCString TranslatorHindi::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1899 of file translator_hi.h.
    { return " "; }
trCode() [1/2]
virtual QCString TranslatorHindi::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 916 of file translator_hi.h.
    { return "-"; }
trCode() [2/2]
virtual QCString TranslatorHindi::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 916 of file translator_hi.h.
    { return "-"; }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorHindi::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 880 of file translator_hi.h.
    { return clName + " :"; }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorHindi::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 880 of file translator_hi.h.
    { return clName + " :"; }
trCompoundIndex() [1/2]
virtual QCString TranslatorHindi::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 436 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return " ";
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorHindi::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 436 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return " ";
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorHindi::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1553 of file translator_hi.h.
    { return " "; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorHindi::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1553 of file translator_hi.h.
    { return " "; }
trCompoundList() [1/2]
virtual QCString TranslatorHindi::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 284 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return " ";
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorHindi::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 284 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return " ";
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorHindi::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 346 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " :";
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
        return " :";
      else
        return " , , :";
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorHindi::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 346 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " :";
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
        return " :";
      else
        return " , , :";
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorHindi::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1532 of file translator_hi.h.
    { return " :"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorHindi::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1532 of file translator_hi.h.
    { return " :"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorHindi::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1524 of file translator_hi.h.
    { return " "; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorHindi::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1524 of file translator_hi.h.
    { return " "; }
trCompoundMembers() [1/2]
virtual QCString TranslatorHindi::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 297 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return " ";
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorHindi::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 297 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return " ";
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorHindi::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 357 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        result += " ";
      else
        result += " ";
      result += " ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result += " / ";
        else
          result += " ";
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result += " / ";
        else
          result += " ";
      }
      result += " :";
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorHindi::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 357 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        result += " ";
      else
        result += " ";
      result += " ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result += " / ";
        else
          result += " ";
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result += " / ";
        else
          result += " ";
      }
      result += " :";
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorHindi::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1536 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += " ";
      if (!extractAll)
        result += " ";
      else
        result += " ";
      result += " :";
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorHindi::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1536 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += " ";
      if (!extractAll)
        result += " ";
      else
        result += " ";
      result += " :";
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorHindi::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1528 of file translator_hi.h.
    { return " "; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorHindi::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1528 of file translator_hi.h.
    { return " "; }
trCompoundReference() [1/2]
virtual QCString TranslatorHindi::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 649 of file translator_hi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result += " "; break;
        case ClassDef::Struct: result += " "; break;
        case ClassDef::Union: result += " "; break;
        case ClassDef::Interface: result += " "; break;
        case ClassDef::Protocol: result += " "; break;
        case ClassDef::Category: result += " "; break;
        case ClassDef::Exception: result += " "; break;
        default: break;
      }
      if (isTemplate)
        result += " ";
      result += " ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorHindi::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 649 of file translator_hi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result += " "; break;
        case ClassDef::Struct: result += " "; break;
        case ClassDef::Union: result += " "; break;
        case ClassDef::Interface: result += " "; break;
        case ClassDef::Protocol: result += " "; break;
        case ClassDef::Category: result += " "; break;
        case ClassDef::Exception: result += " "; break;
        default: break;
      }
      if (isTemplate)
        result += " ";
      result += " ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorHindi::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1595 of file translator_hi.h.
    {
      QCString result = clName;
      switch (compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate)
        result += " ";
      result += " ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorHindi::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1595 of file translator_hi.h.
    {
      QCString result = clName;
      switch (compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate)
        result += " ";
      result += " ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorHindi::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2169 of file translator_hi.h.
    {
      QCString result = clName;
      if (isLocal) result += " ";
      switch (compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result += " ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorHindi::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2169 of file translator_hi.h.
    {
      QCString result = clName;
      if (isLocal) result += " ";
      switch (compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result += " ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorHindi::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 554 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return "";
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorHindi::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 554 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return "";
    }
References Config_getBool.
trConcept() [1/2]
virtual QCString TranslatorHindi::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2213 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular) result += "";
      return result;
    }
trConcept() [2/2]
virtual QCString TranslatorHindi::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2213 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular) result += "";
      return result;
    }
trConceptDefinition() [1/2]
virtual QCString TranslatorHindi::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2251 of file translator_hi.h.
    { return " "; }
trConceptDefinition() [2/2]
virtual QCString TranslatorHindi::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2251 of file translator_hi.h.
    { return " "; }
trConceptDocumentation() [1/2]
virtual QCString TranslatorHindi::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2237 of file translator_hi.h.
    { return " "; }
trConceptDocumentation() [2/2]
virtual QCString TranslatorHindi::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2237 of file translator_hi.h.
    { return " "; }
trConceptIndex() [1/2]
virtual QCString TranslatorHindi::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2233 of file translator_hi.h.
    { return " "; }
trConceptIndex() [2/2]
virtual QCString TranslatorHindi::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2233 of file translator_hi.h.
    { return " "; }
trConceptList() [1/2]
virtual QCString TranslatorHindi::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2229 of file translator_hi.h.
    { return " "; }
trConceptList() [2/2]
virtual QCString TranslatorHindi::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2229 of file translator_hi.h.
    { return " "; }
trConceptListDescription() [1/2]
virtual QCString TranslatorHindi::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2241 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += " :";
      return result;
    }
trConceptListDescription() [2/2]
virtual QCString TranslatorHindi::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2241 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += " :";
      return result;
    }
trConceptReference() [1/2]
virtual QCString TranslatorHindi::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2221 of file translator_hi.h.
    {
      QCString result = conceptName;
      result += " ";
      return result;
    }
trConceptReference() [2/2]
virtual QCString TranslatorHindi::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2221 of file translator_hi.h.
    {
      QCString result = conceptName;
      result += " ";
      return result;
    }
trConstantDocumentation() [1/2]
virtual QCString TranslatorHindi::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2100 of file translator_hi.h.
    { return " "; }
trConstantDocumentation() [2/2]
virtual QCString TranslatorHindi::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2100 of file translator_hi.h.
    { return " "; }
trConstantGroupReference() [1/2]
virtual QCString TranslatorHindi::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1930 of file translator_hi.h.
    {
      QCString result = namespaceName;
      result += " ";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorHindi::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1930 of file translator_hi.h.
    {
      QCString result = namespaceName;
      result += " ";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorHindi::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1926 of file translator_hi.h.
    { return " "; }
trConstantGroups() [2/2]
virtual QCString TranslatorHindi::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1926 of file translator_hi.h.
    { return " "; }
trConstants() [1/2]
virtual QCString TranslatorHindi::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2097 of file translator_hi.h.
    { return ""; }
trConstants() [2/2]
virtual QCString TranslatorHindi::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2097 of file translator_hi.h.
    { return ""; }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorHindi::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 888 of file translator_hi.h.
    { return " "; }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorHindi::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 888 of file translator_hi.h.
    { return " "; }
trCopyright() [1/2]
virtual QCString TranslatorHindi::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1821 of file translator_hi.h.
    { return ""; }
trCopyright() [2/2]
virtual QCString TranslatorHindi::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1821 of file translator_hi.h.
    { return ""; }
trCustomReference() [1/2]
virtual QCString TranslatorHindi::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2094 of file translator_hi.h.
    { return name + " "; }
References setup::name.
trCustomReference() [2/2]
virtual QCString TranslatorHindi::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2094 of file translator_hi.h.
    { return name + " "; }
References setup::name.
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorHindi::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2197 of file translator_hi.h.
    { return " "; }
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorHindi::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2197 of file translator_hi.h.
    { return " "; }
trDataMembers() [1/2]
virtual QCString TranslatorHindi::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2194 of file translator_hi.h.
    { return " "; }
trDataMembers() [2/2]
virtual QCString TranslatorHindi::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2194 of file translator_hi.h.
    { return " "; }
trDataTypes() [1/2]
virtual QCString TranslatorHindi::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1577 of file translator_hi.h.
    { return " "; }
trDataTypes() [2/2]
virtual QCString TranslatorHindi::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1577 of file translator_hi.h.
    { return " "; }
trDate() [1/2]
virtual QCString TranslatorHindi::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 587 of file translator_hi.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorHindi::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 587 of file translator_hi.h.
    { return ""; }
trDateTime() [1/2]
virtual QCString TranslatorHindi::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1774 of file translator_hi.h.
    {
      static const char *days[] = { "", "", "", "",
                                    "", "", "" };
      static const char *months[] = { "", "", "", "", "", "",
                                    "", "", "", "", "", "" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d", days[dayOfWeek - 1], months[month - 1], day, year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d", hour, minutes, seconds);
        sdate += stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorHindi::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1774 of file translator_hi.h.
    {
      static const char *days[] = { "", "", "", "",
                                    "", "", "" };
      static const char *months[] = { "", "", "", "", "", "",
                                    "", "", "", "", "", "" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d", days[dayOfWeek - 1], months[month - 1], day, year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d", hour, minutes, seconds);
        sdate += stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorHindi::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1792 of file translator_hi.h.
    {
      static const char *days_short[] = { ".", ".", ".", ".", ".", ".", "." };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorHindi::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1792 of file translator_hi.h.
    {
      static const char *days_short[] = { ".", ".", ".", ".", ".", ".", "." };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorHindi::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1806 of file translator_hi.h.
    {
      static const char *dayPeriod[] = { "am", "pm" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorHindi::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1806 of file translator_hi.h.
    {
      static const char *dayPeriod[] = { "am", "pm" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorHindi::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 862 of file translator_hi.h.
    { return " @1 @0 "; }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorHindi::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 862 of file translator_hi.h.
    { return " @1 @0 "; }
trDefinedIn() [1/2]
virtual QCString TranslatorHindi::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 268 of file translator_hi.h.
    { return " "; }
trDefinedIn() [2/2]
virtual QCString TranslatorHindi::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 268 of file translator_hi.h.
    { return " "; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorHindi::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 865 of file translator_hi.h.
    { return " @0 "; }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorHindi::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 865 of file translator_hi.h.
    { return " @0 "; }
trDefineDocumentation() [1/2]
virtual QCString TranslatorHindi::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 524 of file translator_hi.h.
    { return " "; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorHindi::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 524 of file translator_hi.h.
    { return " "; }
trDefines() [1/2]
virtual QCString TranslatorHindi::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 488 of file translator_hi.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorHindi::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 488 of file translator_hi.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorHindi::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1128 of file translator_hi.h.
    { return ":"; }
trDefineValue() [2/2]
virtual QCString TranslatorHindi::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1128 of file translator_hi.h.
    { return ":"; }
trDeprecated() [1/2]
virtual QCString TranslatorHindi::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 872 of file translator_hi.h.
    { return ""; }
trDeprecated() [2/2]
virtual QCString TranslatorHindi::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 872 of file translator_hi.h.
    { return ""; }
trDeprecatedList() [1/2]
virtual QCString TranslatorHindi::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1333 of file translator_hi.h.
    { return " "; }
trDeprecatedList() [2/2]
virtual QCString TranslatorHindi::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1333 of file translator_hi.h.
    { return " "; }
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorHindi::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2205 of file translator_hi.h.
    { return " "; }
Referenced by trClassDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorHindi::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2205 of file translator_hi.h.
    { return " "; }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorHindi::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 1980 of file translator_hi.h.
    { return " "; }
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorHindi::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 1980 of file translator_hi.h.
    { return " "; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorHindi::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 1996 of file translator_hi.h.
    { return " "; }
trDesignUnitIndex() [2/2]
virtual QCString TranslatorHindi::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 1996 of file translator_hi.h.
    { return " "; }
trDesignUnitList() [1/2]
virtual QCString TranslatorHindi::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 1984 of file translator_hi.h.
    { return " "; }
trDesignUnitList() [2/2]
virtual QCString TranslatorHindi::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 1984 of file translator_hi.h.
    { return " "; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorHindi::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 1992 of file translator_hi.h.
    { return " :"; }
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorHindi::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 1992 of file translator_hi.h.
    { return " :"; }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorHindi::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 1988 of file translator_hi.h.
    { return " "; }
trDesignUnitMembers() [2/2]
virtual QCString TranslatorHindi::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 1988 of file translator_hi.h.
    { return " "; }
trDesignUnits() [1/2]
virtual QCString TranslatorHindi::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2000 of file translator_hi.h.
    { return " "; }
trDesignUnits() [2/2]
virtual QCString TranslatorHindi::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2000 of file translator_hi.h.
    { return " "; }
trDetailedDescription() [1/2]
virtual QCString TranslatorHindi::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 203 of file translator_hi.h.
    { return " "; }
trDetailedDescription() [2/2]
virtual QCString TranslatorHindi::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 203 of file translator_hi.h.
    { return " "; }
trDetailLevel() [1/2]
virtual QCString TranslatorHindi::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1833 of file translator_hi.h.
    { return " "; }
trDetailLevel() [2/2]
virtual QCString TranslatorHindi::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1833 of file translator_hi.h.
    { return " "; }
trDictionaries() [1/2]
virtual QCString TranslatorHindi::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2109 of file translator_hi.h.
    { return ""; }
trDictionaries() [2/2]
virtual QCString TranslatorHindi::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2109 of file translator_hi.h.
    { return ""; }
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorHindi::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2112 of file translator_hi.h.
    { return " "; }
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorHindi::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2112 of file translator_hi.h.
    { return " "; }
trDir() [1/2]
virtual QCString TranslatorHindi::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1477 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorHindi::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1477 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorHindi::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1825 of file translator_hi.h.
    { return name + " :"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorHindi::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1825 of file translator_hi.h.
    { return name + " :"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorHindi::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1455 of file translator_hi.h.
    { return " "; }
trDirDocumentation() [2/2]
virtual QCString TranslatorHindi::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1455 of file translator_hi.h.
    { return " "; }
trDirectories() [1/2]
virtual QCString TranslatorHindi::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1461 of file translator_hi.h.
    { return ""; }
trDirectories() [2/2]
virtual QCString TranslatorHindi::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1461 of file translator_hi.h.
    { return ""; }
trDirIndex() [1/2]
virtual QCString TranslatorHindi::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1449 of file translator_hi.h.
    { return " "; }
trDirIndex() [2/2]
virtual QCString TranslatorHindi::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1449 of file translator_hi.h.
    { return " "; }
trDirReference() [1/2]
virtual QCString TranslatorHindi::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1467 of file translator_hi.h.
    {
      QCString result = dirName;
      result += " ";
      return result;
    }
trDirReference() [2/2]
virtual QCString TranslatorHindi::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1467 of file translator_hi.h.
    {
      QCString result = dirName;
      result += " ";
      return result;
    }
trDirRelation() [1/2]
virtual QCString TranslatorHindi::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1727 of file translator_hi.h.
    { return name + " "; }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorHindi::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1727 of file translator_hi.h.
    { return name + " "; }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorHindi::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 418 of file translator_hi.h.
    { return ""; }
trDocumentation() [2/2]
virtual QCString TranslatorHindi::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 418 of file translator_hi.h.
    { return ""; }
trEnumerations() [1/2]
virtual QCString TranslatorHindi::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 500 of file translator_hi.h.
    { return ""; }
trEnumerations() [2/2]
virtual QCString TranslatorHindi::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 500 of file translator_hi.h.
    { return ""; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorHindi::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 536 of file translator_hi.h.
    { return " "; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorHindi::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 536 of file translator_hi.h.
    { return " "; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorHindi::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1512 of file translator_hi.h.
    { return " "; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorHindi::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1512 of file translator_hi.h.
    { return " "; }
trEnumerationValues() [1/2]
virtual QCString TranslatorHindi::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 518 of file translator_hi.h.
    { return ""; }
trEnumerationValues() [2/2]
virtual QCString TranslatorHindi::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 518 of file translator_hi.h.
    { return ""; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorHindi::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1845 of file translator_hi.h.
    {
      QCString result = " ";
      if (!single)
        result += "";
      result += " :";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorHindi::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1845 of file translator_hi.h.
    {
      QCString result = " ";
      if (!single)
        result += "";
      result += " :";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorHindi::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 260 of file translator_hi.h.
    { return " "; }
trEnumName() [2/2]
virtual QCString TranslatorHindi::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 260 of file translator_hi.h.
    { return " "; }
trEnumReference() [1/2]
virtual QCString TranslatorHindi::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1855 of file translator_hi.h.
    { return name + " "; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorHindi::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1855 of file translator_hi.h.
    { return name + " "; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorHindi::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 264 of file translator_hi.h.
    { return " "; }
trEnumValue() [2/2]
virtual QCString TranslatorHindi::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 264 of file translator_hi.h.
    { return " "; }
trEventDocumentation() [1/2]
virtual QCString TranslatorHindi::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1347 of file translator_hi.h.
    { return " "; }
trEventDocumentation() [2/2]
virtual QCString TranslatorHindi::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1347 of file translator_hi.h.
    { return " "; }
trEvents() [1/2]
virtual QCString TranslatorHindi::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1343 of file translator_hi.h.
    { return ""; }
trEvents() [2/2]
virtual QCString TranslatorHindi::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1343 of file translator_hi.h.
    { return ""; }
trExampleDocumentation() [1/2]
virtual QCString TranslatorHindi::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 478 of file translator_hi.h.
    { return " "; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorHindi::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 478 of file translator_hi.h.
    { return " "; }
trExamples() [1/2]
virtual QCString TranslatorHindi::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 319 of file translator_hi.h.
    { return ""; }
trExamples() [2/2]
virtual QCString TranslatorHindi::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 319 of file translator_hi.h.
    { return ""; }
trExamplesDescription() [1/2]
virtual QCString TranslatorHindi::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 404 of file translator_hi.h.
    { return " :"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorHindi::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 404 of file translator_hi.h.
    { return " :"; }
trExceptionDocumentation() [1/2]
virtual QCString TranslatorHindi::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2166 of file translator_hi.h.
    { return " "; }
trExceptionDocumentation() [2/2]
virtual QCString TranslatorHindi::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2166 of file translator_hi.h.
    { return " "; }
trExceptionHierarchy() [1/2]
virtual QCString TranslatorHindi::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2160 of file translator_hi.h.
    { return " "; }
trExceptionHierarchy() [2/2]
virtual QCString TranslatorHindi::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2160 of file translator_hi.h.
    { return " "; }
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorHindi::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2163 of file translator_hi.h.
    { return " , , :"; }
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorHindi::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2163 of file translator_hi.h.
    { return " , , :"; }
trExceptionIndex() [1/2]
virtual QCString TranslatorHindi::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2151 of file translator_hi.h.
    { return " "; }
trExceptionIndex() [2/2]
virtual QCString TranslatorHindi::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2151 of file translator_hi.h.
    { return " "; }
trExceptionList() [1/2]
virtual QCString TranslatorHindi::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2154 of file translator_hi.h.
    { return " "; }
trExceptionList() [2/2]
virtual QCString TranslatorHindi::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2154 of file translator_hi.h.
    { return " "; }
trExceptionListDescription() [1/2]
virtual QCString TranslatorHindi::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2157 of file translator_hi.h.
    { return " :"; }
trExceptionListDescription() [2/2]
virtual QCString TranslatorHindi::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2157 of file translator_hi.h.
    { return " :"; }
trExceptions() [1/2]
virtual QCString TranslatorHindi::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 603 of file translator_hi.h.
    { return ""; }
trExceptions() [2/2]
virtual QCString TranslatorHindi::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 603 of file translator_hi.h.
    { return ""; }
trExtendsClass() [1/2]
virtual QCString TranslatorHindi::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1893 of file translator_hi.h.
    { return " @0 "; }
trExtendsClass() [2/2]
virtual QCString TranslatorHindi::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1893 of file translator_hi.h.
    { return " @0 "; }
trFile() [1/2]
virtual QCString TranslatorHindi::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1202 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorHindi::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1202 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorHindi::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 472 of file translator_hi.h.
    { return " "; }
trFileDocumentation() [2/2]
virtual QCString TranslatorHindi::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 472 of file translator_hi.h.
    { return " "; }
trFileIn() [1/2]
virtual QCString TranslatorHindi::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1754 of file translator_hi.h.
    { return name + " "; }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorHindi::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1754 of file translator_hi.h.
    { return name + " "; }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorHindi::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 447 of file translator_hi.h.
    { return " "; }
trFileIndex() [2/2]
virtual QCString TranslatorHindi::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 447 of file translator_hi.h.
    { return " "; }
trFileList() [1/2]
virtual QCString TranslatorHindi::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 293 of file translator_hi.h.
    { return " "; }
trFileList() [2/2]
virtual QCString TranslatorHindi::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 293 of file translator_hi.h.
    { return " "; }
trFileListDescription() [1/2]
virtual QCString TranslatorHindi::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 336 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += " :";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorHindi::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 336 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += " :";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorHindi::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 306 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return "";
      else
        return " ";
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorHindi::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 306 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return "";
      else
        return " ";
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorHindi::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 386 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll) result += " ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        result += ", , , -";
      else
        result += " ";
      result += " ";
      if (extractAll)
        result += " ";
      else
        result += " ";
      result += " :";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorHindi::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 386 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll) result += " ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        result += ", , , -";
      else
        result += " ";
      result += " ";
      if (extractAll)
        result += " ";
      else
        result += " ";
      result += " :";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorHindi::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 673 of file translator_hi.h.
    {
      QCString result = fileName;
      result += " ";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorHindi::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 673 of file translator_hi.h.
    {
      QCString result = fileName;
      result += " ";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorHindi::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 631 of file translator_hi.h.
    { return ""; }
trFriends() [2/2]
virtual QCString TranslatorHindi::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 631 of file translator_hi.h.
    { return ""; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorHindi::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2004 of file translator_hi.h.
    { return "//"; }
trFunctionAndProc() [2/2]
virtual QCString TranslatorHindi::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2004 of file translator_hi.h.
    { return "//"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorHindi::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 542 of file translator_hi.h.
    { return " "; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorHindi::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 542 of file translator_hi.h.
    { return " "; }
trFunctions() [1/2]
virtual QCString TranslatorHindi::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 506 of file translator_hi.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorHindi::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 506 of file translator_hi.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorHindi::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 565 of file translator_hi.h.
    {
      QCString result;
      if (!projName.isEmpty())
        result += projName + " ";
      result += date + " : ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorHindi::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 565 of file translator_hi.h.
    {
      QCString result;
      if (!projName.isEmpty())
        result += projName + " ";
      result += date + " : ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorHindi::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 250 of file translator_hi.h.
    {
      QCString result = " - ";
      if (!s.isEmpty())
        result += s + " ";
      result += " ";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorHindi::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 250 of file translator_hi.h.
    {
      QCString result = " - ";
      if (!s.isEmpty())
        result += s + " ";
      result += " ";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorHindi::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 607 of file translator_hi.h.
    { return " "; }
trGeneratedBy() [2/2]
virtual QCString TranslatorHindi::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 607 of file translator_hi.h.
    { return " "; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorHindi::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 814 of file translator_hi.h.
    {
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result;
      switch (compType)
      {
        case ClassDef::Class: result += vhdlOpt ? " " : ""; break;
        case ClassDef::Struct: result += ""; break;
        case ClassDef::Union: result += ""; break;
        case ClassDef::Interface: result += ""; break;
        case ClassDef::Protocol: result += ""; break;
        case ClassDef::Category: result += ""; break;
        case ClassDef::Exception: result += ""; break;
        default: break;
      }
      result += " ";
      if (single)
        result += " :";
      else
        result += " :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorHindi::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 814 of file translator_hi.h.
    {
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result;
      switch (compType)
      {
        case ClassDef::Class: result += vhdlOpt ? " " : ""; break;
        case ClassDef::Struct: result += ""; break;
        case ClassDef::Union: result += ""; break;
        case ClassDef::Interface: result += ""; break;
        case ClassDef::Protocol: result += ""; break;
        case ClassDef::Category: result += ""; break;
        case ClassDef::Exception: result += ""; break;
        default: break;
      }
      result += " ";
      if (single)
        result += " :";
      else
        result += " :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorHindi::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1667 of file translator_hi.h.
    {
      // single is true implies a single file
      QCString result;
      switch(compType)
      {
        case ClassDef::Class: result += ""; break;
        case ClassDef::Struct: result += ""; break;
        case ClassDef::Union: result += ""; break;
        case ClassDef::Interface: result += ""; break;
        case ClassDef::Protocol: result += ""; break;
        case ClassDef::Category: result += ""; break;
        case ClassDef::Exception: result += ""; break;
        default: break;
      }
      result += " ";
      if (single)
        result += " :";
      else
        result += " :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorHindi::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1667 of file translator_hi.h.
    {
      // single is true implies a single file
      QCString result;
      switch(compType)
      {
        case ClassDef::Class: result += ""; break;
        case ClassDef::Struct: result += ""; break;
        case ClassDef::Union: result += ""; break;
        case ClassDef::Interface: result += ""; break;
        case ClassDef::Protocol: result += ""; break;
        case ClassDef::Category: result += ""; break;
        case ClassDef::Exception: result += ""; break;
        default: break;
      }
      result += " ";
      if (single)
        result += " :";
      else
        result += " :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorHindi::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1267 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorHindi::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1267 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorHindi::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1735 of file translator_hi.h.
    { return " -"; }
trGlobalNamespace() [2/2]
virtual QCString TranslatorHindi::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1735 of file translator_hi.h.
    { return " -"; }
trGotoDocumentation() [1/2]
virtual QCString TranslatorHindi::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 896 of file translator_hi.h.
    { return " "; }
trGotoDocumentation() [2/2]
virtual QCString TranslatorHindi::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 896 of file translator_hi.h.
    { return " "; }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorHindi::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 922 of file translator_hi.h.
    { return " "; }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorHindi::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 922 of file translator_hi.h.
    { return " "; }
trGotoSourceCode() [1/2]
virtual QCString TranslatorHindi::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 892 of file translator_hi.h.
    { return " - "; }
trGotoSourceCode() [2/2]
virtual QCString TranslatorHindi::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 892 of file translator_hi.h.
    { return " - "; }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorHindi::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 925 of file translator_hi.h.
    { return " "; }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorHindi::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 925 of file translator_hi.h.
    { return " "; }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorHindi::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 919 of file translator_hi.h.
    { return " "; }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorHindi::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 919 of file translator_hi.h.
    { return " "; }
trGroup() [1/2]
virtual QCString TranslatorHindi::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1228 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorHindi::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1228 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorHindi::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 430 of file translator_hi.h.
    { return " "; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorHindi::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 430 of file translator_hi.h.
    { return " "; }
trImplementedFromList() [1/2]
virtual QCString TranslatorHindi::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1307 of file translator_hi.h.
    { return trWriteList(numEntries) + " "; }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorHindi::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1307 of file translator_hi.h.
    { return trWriteList(numEntries) + " "; }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorHindi::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1313 of file translator_hi.h.
    { return trWriteList(numEntries) + " "; }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorHindi::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1313 of file translator_hi.h.
    { return trWriteList(numEntries) + " "; }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorHindi::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 995 of file translator_hi.h.
    { return " :"; }
trInclByDepGraph() [2/2]
virtual QCString TranslatorHindi::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 995 of file translator_hi.h.
    { return " :"; }
trInclDepGraph() [1/2]
virtual QCString TranslatorHindi::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 884 of file translator_hi.h.
    { return fName + " :"; }
trInclDepGraph() [2/2]
virtual QCString TranslatorHindi::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 884 of file translator_hi.h.
    { return fName + " :"; }
trIncludesFileIn() [1/2]
virtual QCString TranslatorHindi::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1761 of file translator_hi.h.
    { return name + " "; }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorHindi::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1761 of file translator_hi.h.
    { return name + " "; }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorHindi::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 244 of file translator_hi.h.
    { return ", "; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorHindi::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 244 of file translator_hi.h.
    { return ", "; }
trInheritedByList() [1/2]
virtual QCString TranslatorHindi::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 751 of file translator_hi.h.
    { return trWriteList(numEntries) + " "; }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorHindi::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 751 of file translator_hi.h.
    { return trWriteList(numEntries) + " "; }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorHindi::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1859 of file translator_hi.h.
    { return what + " " + members; }
trInheritedFrom() [2/2]
virtual QCString TranslatorHindi::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1859 of file translator_hi.h.
    { return what + " " + members; }
trInheritsList() [1/2]
virtual QCString TranslatorHindi::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 745 of file translator_hi.h.
    { return trWriteList(numEntries) + " "; }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorHindi::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 745 of file translator_hi.h.
    { return trWriteList(numEntries) + " "; }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorHindi::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 912 of file translator_hi.h.
    { return " :"; }
trInitialValue() [2/2]
virtual QCString TranslatorHindi::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 912 of file translator_hi.h.
    { return " :"; }
trInstanceMethods() [1/2]
virtual QCString TranslatorHindi::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1905 of file translator_hi.h.
    { return " "; }
trInstanceMethods() [2/2]
virtual QCString TranslatorHindi::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1905 of file translator_hi.h.
    { return " "; }
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorHindi::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2133 of file translator_hi.h.
    { return " "; }
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorHindi::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2133 of file translator_hi.h.
    { return " "; }
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorHindi::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2127 of file translator_hi.h.
    { return " "; }
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorHindi::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2127 of file translator_hi.h.
    { return " "; }
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorHindi::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2130 of file translator_hi.h.
    { return " , , :"; }
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorHindi::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2130 of file translator_hi.h.
    { return " , , :"; }
trInterfaceIndex() [1/2]
virtual QCString TranslatorHindi::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2118 of file translator_hi.h.
    { return " "; }
trInterfaceIndex() [2/2]
virtual QCString TranslatorHindi::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2118 of file translator_hi.h.
    { return " "; }
trInterfaceList() [1/2]
virtual QCString TranslatorHindi::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2121 of file translator_hi.h.
    { return " "; }
trInterfaceList() [2/2]
virtual QCString TranslatorHindi::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2121 of file translator_hi.h.
    { return " "; }
trInterfaceListDescription() [1/2]
virtual QCString TranslatorHindi::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2124 of file translator_hi.h.
    { return " :"; }
trInterfaceListDescription() [2/2]
virtual QCString TranslatorHindi::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2124 of file translator_hi.h.
    { return " :"; }
trInterfaces() [1/2]
virtual QCString TranslatorHindi::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1918 of file translator_hi.h.
    { return " "; }
trInterfaces() [2/2]
virtual QCString TranslatorHindi::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1918 of file translator_hi.h.
    { return " "; }
trInvariant() [1/2]
virtual QCString TranslatorHindi::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 908 of file translator_hi.h.
    { return ""; }
trInvariant() [2/2]
virtual QCString TranslatorHindi::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 908 of file translator_hi.h.
    { return ""; }
trISOLang() [1/2]
virtual QCString TranslatorHindi::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 186 of file translator_hi.h.
    { return "hi-IN"; }
trISOLang() [2/2]
virtual QCString TranslatorHindi::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 186 of file translator_hi.h.
    { return "hi-IN"; }
trLegend() [1/2]
virtual QCString TranslatorHindi::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1076 of file translator_hi.h.
    { return ""; }
trLegend() [2/2]
virtual QCString TranslatorHindi::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1076 of file translator_hi.h.
    { return ""; }
trLegendDocs() [1/2]
virtual QCString TranslatorHindi::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1012 of file translator_hi.h.
    {
      return
        " \n"
        "<p>\n"
        " :\n"
        "\\code\n"
        "/*! - */\n"
        "class Invisible { };\n\n"
        "/*! , - */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* */\n"
        "class Undocumented { };\n\n"
        "/*! */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ { };\n\n"
        "/*! */\n"
        "class ProtectedBase { };\n\n"
        "/*! */\n"
        "class PrivateBase { };\n\n"
        "/*! */\n"
        "class Used { };\n\n"
        "/*! */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " :"
        "<p><center><img alt=\"\" src=\"graph_legend." + getDotImageExtension() + "\"></center></p>\n"
        "<p>\n"
        " :\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A </li>\n"
        "<li>%A , , </li>\n"
        "<li>%A , , </li>\n"
        "<li>%A , , "
        " %A - "
        " </li>\n"
        "</ul>\n"
        "<p>\n"
        " :\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A "
        " </li>\n"
        "<li>%A </li>\n"
        "<li>%A </li>\n"
        "<li>%A "
        " () "
        " </li>\n"
        "<li>%A "
        " </li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorHindi::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1012 of file translator_hi.h.
    {
      return
        " \n"
        "<p>\n"
        " :\n"
        "\\code\n"
        "/*! - */\n"
        "class Invisible { };\n\n"
        "/*! , - */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* */\n"
        "class Undocumented { };\n\n"
        "/*! */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ { };\n\n"
        "/*! */\n"
        "class ProtectedBase { };\n\n"
        "/*! */\n"
        "class PrivateBase { };\n\n"
        "/*! */\n"
        "class Used { };\n\n"
        "/*! */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " :"
        "<p><center><img alt=\"\" src=\"graph_legend." + getDotImageExtension() + "\"></center></p>\n"
        "<p>\n"
        " :\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A </li>\n"
        "<li>%A , , </li>\n"
        "<li>%A , , </li>\n"
        "<li>%A , , "
        " %A - "
        " </li>\n"
        "</ul>\n"
        "<p>\n"
        " :\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A "
        " </li>\n"
        "<li>%A </li>\n"
        "<li>%A </li>\n"
        "<li>%A "
        " () "
        " </li>\n"
        "<li>%A "
        " </li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorHindi::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1006 of file translator_hi.h.
    { return " "; }
trLegendTitle() [2/2]
virtual QCString TranslatorHindi::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1006 of file translator_hi.h.
    { return " "; }
trListOfAllMembers() [1/2]
virtual QCString TranslatorHindi::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 232 of file translator_hi.h.
    { return " "; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorHindi::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 232 of file translator_hi.h.
    { return " "; }
trLoading() [1/2]
virtual QCString TranslatorHindi::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1731 of file translator_hi.h.
    { return " ..."; }
trLoading() [2/2]
virtual QCString TranslatorHindi::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1731 of file translator_hi.h.
    { return " ..."; }
trMainPage() [1/2]
virtual QCString TranslatorHindi::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 849 of file translator_hi.h.
    { return " "; }
trMainPage() [2/2]
virtual QCString TranslatorHindi::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 849 of file translator_hi.h.
    { return " "; }
trMember() [1/2]
virtual QCString TranslatorHindi::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1254 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorHindi::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1254 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorHindi::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 219 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return " ";
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorHindi::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 219 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return " ";
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorHindi::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 211 of file translator_hi.h.
    { return " "; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorHindi::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 211 of file translator_hi.h.
    { return " "; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorHindi::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 215 of file translator_hi.h.
    { return " "; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorHindi::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 215 of file translator_hi.h.
    { return " "; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorHindi::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1520 of file translator_hi.h.
    { return " / "; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorHindi::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1520 of file translator_hi.h.
    { return " / "; }
trMemberList() [1/2]
virtual QCString TranslatorHindi::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 236 of file translator_hi.h.
    { return " "; }
trMemberList() [2/2]
virtual QCString TranslatorHindi::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 236 of file translator_hi.h.
    { return " "; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorHindi::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 207 of file translator_hi.h.
    { return " - "; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorHindi::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 207 of file translator_hi.h.
    { return " - "; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorHindi::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1910 of file translator_hi.h.
    { return " "; }
trMethodDocumentation() [2/2]
virtual QCString TranslatorHindi::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1910 of file translator_hi.h.
    { return " "; }
trModule() [1/2]
virtual QCString TranslatorHindi::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1655 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorHindi::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1655 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorHindi::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 453 of file translator_hi.h.
    { return " "; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorHindi::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 453 of file translator_hi.h.
    { return " "; }
trModuleIndex() [1/2]
virtual QCString TranslatorHindi::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 424 of file translator_hi.h.
    { return " "; }
trModuleIndex() [2/2]
virtual QCString TranslatorHindi::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 424 of file translator_hi.h.
    { return " "; }
trModuleReference() [1/2]
virtual QCString TranslatorHindi::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1619 of file translator_hi.h.
    {
      QCString result = namespaceName;
      result += " ";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorHindi::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1619 of file translator_hi.h.
    {
      QCString result = namespaceName;
      result += " ";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorHindi::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 276 of file translator_hi.h.
    { return ""; }
trModules() [2/2]
virtual QCString TranslatorHindi::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 276 of file translator_hi.h.
    { return ""; }
trModulesDescription() [1/2]
virtual QCString TranslatorHindi::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 412 of file translator_hi.h.
    { return " :"; }
trModulesDescription() [2/2]
virtual QCString TranslatorHindi::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 412 of file translator_hi.h.
    { return " :"; }
trModulesIndex() [1/2]
virtual QCString TranslatorHindi::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1648 of file translator_hi.h.
    { return " "; }
trModulesIndex() [2/2]
virtual QCString TranslatorHindi::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1648 of file translator_hi.h.
    { return " "; }
trModulesList() [1/2]
virtual QCString TranslatorHindi::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1581 of file translator_hi.h.
    { return " "; }
trModulesList() [2/2]
virtual QCString TranslatorHindi::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1581 of file translator_hi.h.
    { return " "; }
trModulesListDescription() [1/2]
virtual QCString TranslatorHindi::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1585 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += " :";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorHindi::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1585 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += " :";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorHindi::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1631 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += " ";
      if (extractAll)
        result += " ";
      else
        result += " ";
      result += " :";
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorHindi::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1631 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += " ";
      if (extractAll)
        result += " ";
      else
        result += " ";
      result += " :";
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorHindi::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1627 of file translator_hi.h.
    { return " "; }
trModulesMembers() [2/2]
virtual QCString TranslatorHindi::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1627 of file translator_hi.h.
    { return " "; }
trMonth() [1/2]
virtual QCString TranslatorHindi::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1799 of file translator_hi.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorHindi::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1799 of file translator_hi.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
virtual QCString TranslatorHindi::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 228 of file translator_hi.h.
    { return "..."; }
trMore() [2/2]
virtual QCString TranslatorHindi::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 228 of file translator_hi.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorHindi::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1215 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "-";
      if (!singular)
        result += "";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorHindi::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1215 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "-";
      if (!singular)
        result += "";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorHindi::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 794 of file translator_hi.h.
    { return "- "; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorHindi::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 794 of file translator_hi.h.
    { return "- "; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorHindi::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 788 of file translator_hi.h.
    { return "- "; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorHindi::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 788 of file translator_hi.h.
    { return "- "; }
trNamespaceList() [1/2]
virtual QCString TranslatorHindi::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 615 of file translator_hi.h.
    { return "- "; }
trNamespaceList() [2/2]
virtual QCString TranslatorHindi::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 615 of file translator_hi.h.
    { return "- "; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorHindi::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 619 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += "- :";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorHindi::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 619 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += "- :";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorHindi::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 771 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += "- ";
      if (extractAll)
        result += " - ";
      else
        result += " - ";
      result += " :";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorHindi::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 771 of file translator_hi.h.
    {
      QCString result = " ";
      if (!extractAll)
        result += " ";
      result += "- ";
      if (extractAll)
        result += " - ";
      else
        result += " - ";
      result += " :";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorHindi::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 767 of file translator_hi.h.
    { return "- "; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorHindi::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 767 of file translator_hi.h.
    { return "- "; }
trNamespaceReference() [1/2]
virtual QCString TranslatorHindi::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 681 of file translator_hi.h.
    {
      QCString result = namespaceName;
      result += " - ";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorHindi::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 681 of file translator_hi.h.
    {
      QCString result = namespaceName;
      result += " - ";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorHindi::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 804 of file translator_hi.h.
    { return "-"; }
trNamespaces() [2/2]
virtual QCString TranslatorHindi::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 804 of file translator_hi.h.
    { return "-"; }
trNoMatches() [1/2]
virtual QCString TranslatorHindi::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1743 of file translator_hi.h.
    { return " "; }
trNoMatches() [2/2]
virtual QCString TranslatorHindi::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1743 of file translator_hi.h.
    { return " "; }
trNote() [1/2]
virtual QCString TranslatorHindi::trNote () [inline], [virtual]
Implements Translator.
Definition at line 935 of file translator_hi.h.
    { return " "; }
trNote() [2/2]
virtual QCString TranslatorHindi::trNote () [inline], [virtual]
Implements Translator.
Definition at line 935 of file translator_hi.h.
    { return " "; }
trOperationDocumentation() [1/2]
virtual QCString TranslatorHindi::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2191 of file translator_hi.h.
    { return " "; }
trOperationDocumentation() [2/2]
virtual QCString TranslatorHindi::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2191 of file translator_hi.h.
    { return " "; }
trOperations() [1/2]
virtual QCString TranslatorHindi::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2188 of file translator_hi.h.
    { return ""; }
trOperations() [2/2]
virtual QCString TranslatorHindi::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2188 of file translator_hi.h.
    { return ""; }
trOverloadText() [1/2]
virtual QCString TranslatorHindi::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1493 of file translator_hi.h.
    {
      return " "
              " ";
    }
trOverloadText() [2/2]
virtual QCString TranslatorHindi::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1493 of file translator_hi.h.
    {
      return " "
              " ";
    }
trPackage() [1/2]
virtual QCString TranslatorHindi::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1116 of file translator_hi.h.
    { return " " + name; }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorHindi::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1116 of file translator_hi.h.
    { return " " + name; }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorHindi::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1376 of file translator_hi.h.
    { return " "; }
trPackageAttribs() [2/2]
virtual QCString TranslatorHindi::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1376 of file translator_hi.h.
    { return " "; }
trPackageFunctions() [1/2]
virtual QCString TranslatorHindi::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1362 of file translator_hi.h.
    { return " "; }
trPackageFunctions() [2/2]
virtual QCString TranslatorHindi::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1362 of file translator_hi.h.
    { return " "; }
trPackageListDescription() [1/2]
virtual QCString TranslatorHindi::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1120 of file translator_hi.h.
    { return " ():"; }
trPackageListDescription() [2/2]
virtual QCString TranslatorHindi::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1120 of file translator_hi.h.
    { return " ():"; }
trPackageMembers() [1/2]
virtual QCString TranslatorHindi::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1364 of file translator_hi.h.
    { return " "; }
trPackageMembers() [2/2]
virtual QCString TranslatorHindi::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1364 of file translator_hi.h.
    { return " "; }
trPackages() [1/2]
virtual QCString TranslatorHindi::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1124 of file translator_hi.h.
    { return ""; }
trPackages() [2/2]
virtual QCString TranslatorHindi::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1124 of file translator_hi.h.
    { return ""; }
trPackageTypes() [1/2]
virtual QCString TranslatorHindi::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1356 of file translator_hi.h.
    { return " "; }
trPackageTypes() [2/2]
virtual QCString TranslatorHindi::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1356 of file translator_hi.h.
    { return " "; }
trPage() [1/2]
virtual QCString TranslatorHindi::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1241 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorHindi::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1241 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorHindi::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 855 of file translator_hi.h.
    { return "."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorHindi::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 855 of file translator_hi.h.
    { return "."; }
trPageIndex() [1/2]
virtual QCString TranslatorHindi::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_hi.h.
    { return " "; }
trPageIndex() [2/2]
virtual QCString TranslatorHindi::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_hi.h.
    { return " "; }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorHindi::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1876 of file translator_hi.h.
    {
      QCString opt = enable ? "" : "";
      return " " + opt + " ";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorHindi::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1876 of file translator_hi.h.
    {
      QCString opt = enable ? "" : "";
      return " " + opt + " ";
    }
trParameters() [1/2]
virtual QCString TranslatorHindi::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 599 of file translator_hi.h.
    { return ""; }
trParameters() [2/2]
virtual QCString TranslatorHindi::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 599 of file translator_hi.h.
    { return ""; }
trPostcondition() [1/2]
virtual QCString TranslatorHindi::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 904 of file translator_hi.h.
    { return ""; }
trPostcondition() [2/2]
virtual QCString TranslatorHindi::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 904 of file translator_hi.h.
    { return ""; }
trPrecondition() [1/2]
virtual QCString TranslatorHindi::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 900 of file translator_hi.h.
    { return ""; }
trPrecondition() [2/2]
virtual QCString TranslatorHindi::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 900 of file translator_hi.h.
    { return ""; }
trPrivateAttribs() [1/2]
virtual QCString TranslatorHindi::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_hi.h.
    { return " "; }
trPrivateAttribs() [2/2]
virtual QCString TranslatorHindi::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_hi.h.
    { return " "; }
trPrivateMembers() [1/2]
virtual QCString TranslatorHindi::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 709 of file translator_hi.h.
    { return " "; }
trPrivateMembers() [2/2]
virtual QCString TranslatorHindi::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 709 of file translator_hi.h.
    { return " "; }
trPrivateSlots() [1/2]
virtual QCString TranslatorHindi::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 712 of file translator_hi.h.
    { return " "; }
trPrivateSlots() [2/2]
virtual QCString TranslatorHindi::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 712 of file translator_hi.h.
    { return " "; }
trPrivateTypes() [1/2]
virtual QCString TranslatorHindi::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 961 of file translator_hi.h.
    { return " "; }
trPrivateTypes() [2/2]
virtual QCString TranslatorHindi::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 961 of file translator_hi.h.
    { return " "; }
trProperties() [1/2]
virtual QCString TranslatorHindi::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1095 of file translator_hi.h.
    { return ""; }
trProperties() [2/2]
virtual QCString TranslatorHindi::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1095 of file translator_hi.h.
    { return ""; }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorHindi::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1099 of file translator_hi.h.
    { return " "; }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorHindi::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1099 of file translator_hi.h.
    { return " "; }
trProtectedAttribs() [1/2]
virtual QCString TranslatorHindi::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 955 of file translator_hi.h.
    { return " "; }
trProtectedAttribs() [2/2]
virtual QCString TranslatorHindi::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 955 of file translator_hi.h.
    { return " "; }
trProtectedMembers() [1/2]
virtual QCString TranslatorHindi::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 700 of file translator_hi.h.
    { return " "; }
trProtectedMembers() [2/2]
virtual QCString TranslatorHindi::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 700 of file translator_hi.h.
    { return " "; }
trProtectedSlots() [1/2]
virtual QCString TranslatorHindi::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 703 of file translator_hi.h.
    { return " "; }
trProtectedSlots() [2/2]
virtual QCString TranslatorHindi::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 703 of file translator_hi.h.
    { return " "; }
trProtectedTypes() [1/2]
virtual QCString TranslatorHindi::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_hi.h.
    { return " "; }
trProtectedTypes() [2/2]
virtual QCString TranslatorHindi::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_hi.h.
    { return " "; }
trProvidedByCategory() [1/2]
virtual QCString TranslatorHindi::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1886 of file translator_hi.h.
    { return " @0 "; }
trProvidedByCategory() [2/2]
virtual QCString TranslatorHindi::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1886 of file translator_hi.h.
    { return " @0 "; }
trPublicAttribs() [1/2]
virtual QCString TranslatorHindi::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 941 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return " ";
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorHindi::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 941 of file translator_hi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        return " ";
      else
        return " ";
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorHindi::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 688 of file translator_hi.h.
    { return " "; }
trPublicMembers() [2/2]
virtual QCString TranslatorHindi::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 688 of file translator_hi.h.
    { return " "; }
trPublicSlots() [1/2]
virtual QCString TranslatorHindi::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 691 of file translator_hi.h.
    { return " "; }
trPublicSlots() [2/2]
virtual QCString TranslatorHindi::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 691 of file translator_hi.h.
    { return " "; }
trPublicTypes() [1/2]
virtual QCString TranslatorHindi::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 938 of file translator_hi.h.
    { return " "; }
trPublicTypes() [2/2]
virtual QCString TranslatorHindi::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 938 of file translator_hi.h.
    { return " "; }
trReferencedBy() [1/2]
virtual QCString TranslatorHindi::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 986 of file translator_hi.h.
    { return " "; }
trReferencedBy() [2/2]
virtual QCString TranslatorHindi::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 986 of file translator_hi.h.
    { return " "; }
trReferenceManual() [1/2]
virtual QCString TranslatorHindi::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 482 of file translator_hi.h.
    { return " "; }
trReferenceManual() [2/2]
virtual QCString TranslatorHindi::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 482 of file translator_hi.h.
    { return " "; }
trReferences() [1/2]
virtual QCString TranslatorHindi::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1297 of file translator_hi.h.
    { return ""; }
trReferences() [2/2]
virtual QCString TranslatorHindi::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1297 of file translator_hi.h.
    { return ""; }
trReimplementedFromList() [1/2]
virtual QCString TranslatorHindi::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 757 of file translator_hi.h.
    { return trWriteList(numEntries) + " : "; }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorHindi::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 757 of file translator_hi.h.
    { return trWriteList(numEntries) + " : "; }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorHindi::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 763 of file translator_hi.h.
    { return trWriteList(numEntries) + " : "; }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorHindi::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 763 of file translator_hi.h.
    { return trWriteList(numEntries) + " : "; }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorHindi::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 641 of file translator_hi.h.
    { return " "; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorHindi::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 641 of file translator_hi.h.
    { return " "; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorHindi::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 195 of file translator_hi.h.
    { return " "; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorHindi::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 195 of file translator_hi.h.
    { return " "; }
trRelatedPages() [1/2]
virtual QCString TranslatorHindi::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 315 of file translator_hi.h.
    { return " "; }
trRelatedPages() [2/2]
virtual QCString TranslatorHindi::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 315 of file translator_hi.h.
    { return " "; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorHindi::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 408 of file translator_hi.h.
    { return " :"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorHindi::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 408 of file translator_hi.h.
    { return " :"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorHindi::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 199 of file translator_hi.h.
    { return "()"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorHindi::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 199 of file translator_hi.h.
    { return "()"; }
trRemarks() [1/2]
virtual QCString TranslatorHindi::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 989 of file translator_hi.h.
    { return ""; }
trRemarks() [2/2]
virtual QCString TranslatorHindi::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 989 of file translator_hi.h.
    { return ""; }
trReturns() [1/2]
virtual QCString TranslatorHindi::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 591 of file translator_hi.h.
    { return ""; }
trReturns() [2/2]
virtual QCString TranslatorHindi::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 591 of file translator_hi.h.
    { return ""; }
trReturnValues() [1/2]
virtual QCString TranslatorHindi::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 844 of file translator_hi.h.
    { return " "; }
trReturnValues() [2/2]
virtual QCString TranslatorHindi::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 844 of file translator_hi.h.
    { return " "; }
trRTFansicp() [1/2]
virtual QCString TranslatorHindi::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1172 of file translator_hi.h.
    { return "65001"; }
trRTFansicp() [2/2]
virtual QCString TranslatorHindi::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1172 of file translator_hi.h.
    { return "65001"; }
trRTFCharSet() [1/2]
virtual QCString TranslatorHindi::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1178 of file translator_hi.h.
    { return "1252"; }
trRTFCharSet() [2/2]
virtual QCString TranslatorHindi::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1178 of file translator_hi.h.
    { return "1252"; }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorHindi::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1182 of file translator_hi.h.
    { return ""; }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorHindi::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1182 of file translator_hi.h.
    { return ""; }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorHindi::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1323 of file translator_hi.h.
    { return "-"; }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorHindi::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1323 of file translator_hi.h.
    { return "-"; }
trSearch() [1/2]
virtual QCString TranslatorHindi::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 323 of file translator_hi.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorHindi::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 323 of file translator_hi.h.
    { return ""; }
trSearching() [1/2]
virtual QCString TranslatorHindi::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1739 of file translator_hi.h.
    { return " ..."; }
trSearching() [2/2]
virtual QCString TranslatorHindi::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1739 of file translator_hi.h.
    { return " ..."; }
trSearchMatches() [1/2]
virtual QCString TranslatorHindi::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1430 of file translator_hi.h.
    { return ":"; }
trSearchMatches() [2/2]
virtual QCString TranslatorHindi::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1430 of file translator_hi.h.
    { return ":"; }
trSearchResults() [1/2]
virtual QCString TranslatorHindi::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1417 of file translator_hi.h.
    {
      if (numDocuments == 0)
        return " , ";
      else if (numDocuments == 1)
        return " <b>1</b> ";
      else
        return " <b>$num</b> ";
    }
trSearchResults() [2/2]
virtual QCString TranslatorHindi::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1417 of file translator_hi.h.
    {
      if (numDocuments == 0)
        return " , ";
      else if (numDocuments == 1)
        return " <b>1</b> ";
      else
        return " <b>$num</b> ";
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorHindi::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1406 of file translator_hi.h.
    { return " "; }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorHindi::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1406 of file translator_hi.h.
    { return " "; }
trSeeAlso() [1/2]
virtual QCString TranslatorHindi::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 595 of file translator_hi.h.
    { return " "; }
trSeeAlso() [2/2]
virtual QCString TranslatorHindi::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 595 of file translator_hi.h.
    { return " "; }
trSequenceDocumentation() [1/2]
virtual QCString TranslatorHindi::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2106 of file translator_hi.h.
    { return " "; }
trSequenceDocumentation() [2/2]
virtual QCString TranslatorHindi::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2106 of file translator_hi.h.
    { return " "; }
trSequences() [1/2]
virtual QCString TranslatorHindi::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2103 of file translator_hi.h.
    { return ""; }
trSequences() [2/2]
virtual QCString TranslatorHindi::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2103 of file translator_hi.h.
    { return ""; }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorHindi::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1954 of file translator_hi.h.
    {
      // single is true implies a single file
      QCString result = " ";
      if (!single)
        result += "";
      result += " :";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorHindi::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1954 of file translator_hi.h.
    {
      // single is true implies a single file
      QCString result = " ";
      if (!single)
        result += "";
      result += " :";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorHindi::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1938 of file translator_hi.h.
    {
      QCString result = sName;
      result += " ";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorHindi::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1938 of file translator_hi.h.
    {
      QCString result = sName;
      result += " ";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorHindi::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1922 of file translator_hi.h.
    { return " "; }
trServices() [2/2]
virtual QCString TranslatorHindi::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1922 of file translator_hi.h.
    { return " "; }
trSignals() [1/2]
virtual QCString TranslatorHindi::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 694 of file translator_hi.h.
    { return ""; }
trSignals() [2/2]
virtual QCString TranslatorHindi::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 694 of file translator_hi.h.
    { return ""; }
trSince() [1/2]
virtual QCString TranslatorHindi::trSince () [inline], [virtual]
Implements Translator.
Definition at line 998 of file translator_hi.h.
    { return ""; }
trSince() [2/2]
virtual QCString TranslatorHindi::trSince () [inline], [virtual]
Implements Translator.
Definition at line 998 of file translator_hi.h.
    { return ""; }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorHindi::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1965 of file translator_hi.h.
    {
      // single is true implies a single file
      QCString result = " ";
      if (!single)
        result += "";
      result += " :";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorHindi::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1965 of file translator_hi.h.
    {
      // single is true implies a single file
      QCString result = " ";
      if (!single)
        result += "";
      result += " :";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorHindi::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1946 of file translator_hi.h.
    {
      QCString result = sName;
      result += " ";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorHindi::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1946 of file translator_hi.h.
    {
      QCString result = sName;
      result += " ";
      return result;
    }
trSliceInterfaces() [1/2]
virtual QCString TranslatorHindi::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2115 of file translator_hi.h.
    { return ""; }
trSliceInterfaces() [2/2]
virtual QCString TranslatorHindi::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2115 of file translator_hi.h.
    { return ""; }
trSourceFile() [1/2]
virtual QCString TranslatorHindi::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1439 of file translator_hi.h.
    { return filename + " "; }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorHindi::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1439 of file translator_hi.h.
    { return filename + " "; }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorHindi::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1382 of file translator_hi.h.
    { return " "; }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorHindi::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1382 of file translator_hi.h.
    { return " "; }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorHindi::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1370 of file translator_hi.h.
    { return " "; }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorHindi::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1370 of file translator_hi.h.
    { return " "; }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorHindi::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 967 of file translator_hi.h.
    { return " "; }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorHindi::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 967 of file translator_hi.h.
    { return " "; }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorHindi::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 715 of file translator_hi.h.
    { return " "; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorHindi::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 715 of file translator_hi.h.
    { return " "; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorHindi::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 958 of file translator_hi.h.
    { return " "; }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorHindi::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 958 of file translator_hi.h.
    { return " "; }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorHindi::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 706 of file translator_hi.h.
    { return " "; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorHindi::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 706 of file translator_hi.h.
    { return " "; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorHindi::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_hi.h.
    { return " "; }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorHindi::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_hi.h.
    { return " "; }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorHindi::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 697 of file translator_hi.h.
    { return " "; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorHindi::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 697 of file translator_hi.h.
    { return " "; }
trStructDocumentation() [1/2]
virtual QCString TranslatorHindi::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2148 of file translator_hi.h.
    { return " "; }
trStructDocumentation() [2/2]
virtual QCString TranslatorHindi::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2148 of file translator_hi.h.
    { return " "; }
trStructIndex() [1/2]
virtual QCString TranslatorHindi::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2139 of file translator_hi.h.
    { return " "; }
trStructIndex() [2/2]
virtual QCString TranslatorHindi::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2139 of file translator_hi.h.
    { return " "; }
trStructList() [1/2]
virtual QCString TranslatorHindi::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2142 of file translator_hi.h.
    { return " "; }
trStructList() [2/2]
virtual QCString TranslatorHindi::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2142 of file translator_hi.h.
    { return " "; }
trStructListDescription() [1/2]
virtual QCString TranslatorHindi::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2145 of file translator_hi.h.
    { return " :"; }
trStructListDescription() [2/2]
virtual QCString TranslatorHindi::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2145 of file translator_hi.h.
    { return " :"; }
trStructs() [1/2]
virtual QCString TranslatorHindi::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2136 of file translator_hi.h.
    { return ""; }
trStructs() [2/2]
virtual QCString TranslatorHindi::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2136 of file translator_hi.h.
    { return ""; }
trSubprogram() [1/2]
virtual QCString TranslatorHindi::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1709 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorHindi::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1709 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorHindi::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1571 of file translator_hi.h.
    { return "/ "; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorHindi::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1571 of file translator_hi.h.
    { return "/ "; }
trSubprograms() [1/2]
virtual QCString TranslatorHindi::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1565 of file translator_hi.h.
    { return "/"; }
trSubprograms() [2/2]
virtual QCString TranslatorHindi::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1565 of file translator_hi.h.
    { return "/"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorHindi::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1837 of file translator_hi.h.
    { return " "; }
trTemplateParameters() [2/2]
virtual QCString TranslatorHindi::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1837 of file translator_hi.h.
    { return " "; }
trTest() [1/2]
virtual QCString TranslatorHindi::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1084 of file translator_hi.h.
    { return ""; }
trTest() [2/2]
virtual QCString TranslatorHindi::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1084 of file translator_hi.h.
    { return ""; }
trTestList() [1/2]
virtual QCString TranslatorHindi::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1087 of file translator_hi.h.
    { return " "; }
trTestList() [2/2]
virtual QCString TranslatorHindi::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1087 of file translator_hi.h.
    { return " "; }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorHindi::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 240 of file translator_hi.h.
    { return " "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorHindi::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 240 of file translator_hi.h.
    { return " "; }
trTodo() [1/2]
virtual QCString TranslatorHindi::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 975 of file translator_hi.h.
    { return " "; }
trTodo() [2/2]
virtual QCString TranslatorHindi::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 975 of file translator_hi.h.
    { return " "; }
trTodoList() [1/2]
virtual QCString TranslatorHindi::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 979 of file translator_hi.h.
    { return " "; }
trTodoList() [2/2]
virtual QCString TranslatorHindi::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 979 of file translator_hi.h.
    { return " "; }
trType() [1/2]
virtual QCString TranslatorHindi::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1696 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorHindi::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1696 of file translator_hi.h.
    {
      // There is no first-letter capitalization notion in Hindi.
      QCString result = "";
      if (!singular)
        result += "";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorHindi::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1719 of file translator_hi.h.
    { return " "; }
trTypeConstraints() [2/2]
virtual QCString TranslatorHindi::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1719 of file translator_hi.h.
    { return " "; }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorHindi::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 530 of file translator_hi.h.
    { return "- "; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorHindi::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 530 of file translator_hi.h.
    { return "- "; }
trTypedefs() [1/2]
virtual QCString TranslatorHindi::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 494 of file translator_hi.h.
    { return "-"; }
trTypedefs() [2/2]
virtual QCString TranslatorHindi::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 494 of file translator_hi.h.
    { return "-"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorHindi::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1559 of file translator_hi.h.
    { return " "; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorHindi::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1559 of file translator_hi.h.
    { return " "; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorHindi::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 548 of file translator_hi.h.
    { return " "; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorHindi::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 548 of file translator_hi.h.
    { return " "; }
trVariables() [1/2]
virtual QCString TranslatorHindi::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 512 of file translator_hi.h.
    { return ""; }
trVariables() [2/2]
virtual QCString TranslatorHindi::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 512 of file translator_hi.h.
    { return ""; }
trVersion() [1/2]
virtual QCString TranslatorHindi::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 583 of file translator_hi.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorHindi::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 583 of file translator_hi.h.
    { return ""; }
trVhdlType() [1/2]
virtual QCString TranslatorHindi::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2008 of file translator_hi.h.
    {
      switch (type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "";
          else return "";
        case VhdlDocGen::PACKAGE:
          if (single) return "";
          else return "";
        case VhdlDocGen::SIGNAL:
          if (single) return "";
          else return "";
        case VhdlDocGen::COMPONENT:
          if (single) return "";
          else return "";
        case VhdlDocGen::CONSTANT:
          if (single) return "";
          else return "";
        case VhdlDocGen::ENTITY:
          if (single) return "";
          else return "";
        case VhdlDocGen::TYPE:
          if (single) return "";
          else return "";
        case VhdlDocGen::SUBTYPE:
          if (single) return "";
          else return "";
        case VhdlDocGen::FUNCTION:
          if (single) return "";
          else return "";
        case VhdlDocGen::RECORD:
          if (single) return "";
          else return "";
        case VhdlDocGen::PROCEDURE:
          if (single) return "";
          else return "";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "";
          else return "";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "";
          else return "";
        case VhdlDocGen::PROCESS:
          if (single) return "";
          else return "";
        case VhdlDocGen::PORT:
          if (single) return "";
          else return "";
        case VhdlDocGen::USE:
          if (single) return " ";
          else return " ";
        case VhdlDocGen::GENERIC:
          if (single) return "";
          else return "";
        case VhdlDocGen::PACKAGE_BODY:
          return " ";
        case VhdlDocGen::UNITS:
          return "";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return " ";
          else return " ";
        case VhdlDocGen::VFILE:
          if (single) return "";
          else return "";
        case VhdlDocGen::GROUP:
          if (single) return "";
          else return "";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "";
          else return "";
        case VhdlDocGen::ALIAS:
          if (single) return "";
          else return "";
        case VhdlDocGen::CONFIG:
          if (single) return "";
          else return "";
        case VhdlDocGen::MISCELLANEOUS:
          return "";
        case VhdlDocGen::UCF_CONST:
          return "";
        default:
          return "";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trVhdlType() [2/2]
virtual QCString TranslatorHindi::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2008 of file translator_hi.h.
    {
      switch (type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "";
          else return "";
        case VhdlDocGen::PACKAGE:
          if (single) return "";
          else return "";
        case VhdlDocGen::SIGNAL:
          if (single) return "";
          else return "";
        case VhdlDocGen::COMPONENT:
          if (single) return "";
          else return "";
        case VhdlDocGen::CONSTANT:
          if (single) return "";
          else return "";
        case VhdlDocGen::ENTITY:
          if (single) return "";
          else return "";
        case VhdlDocGen::TYPE:
          if (single) return "";
          else return "";
        case VhdlDocGen::SUBTYPE:
          if (single) return "";
          else return "";
        case VhdlDocGen::FUNCTION:
          if (single) return "";
          else return "";
        case VhdlDocGen::RECORD:
          if (single) return "";
          else return "";
        case VhdlDocGen::PROCEDURE:
          if (single) return "";
          else return "";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "";
          else return "";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "";
          else return "";
        case VhdlDocGen::PROCESS:
          if (single) return "";
          else return "";
        case VhdlDocGen::PORT:
          if (single) return "";
          else return "";
        case VhdlDocGen::USE:
          if (single) return " ";
          else return " ";
        case VhdlDocGen::GENERIC:
          if (single) return "";
          else return "";
        case VhdlDocGen::PACKAGE_BODY:
          return " ";
        case VhdlDocGen::UNITS:
          return "";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return " ";
          else return " ";
        case VhdlDocGen::VFILE:
          if (single) return "";
          else return "";
        case VhdlDocGen::GROUP:
          if (single) return "";
          else return "";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "";
          else return "";
        case VhdlDocGen::ALIAS:
          if (single) return "";
          else return "";
        case VhdlDocGen::CONFIG:
          if (single) return "";
          else return "";
        case VhdlDocGen::MISCELLANEOUS:
          return "";
        case VhdlDocGen::UCF_CONST:
          return "";
        default:
          return "";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
virtual QCString TranslatorHindi::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 579 of file translator_hi.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorHindi::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 579 of file translator_hi.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorHindi::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 721 of file translator_hi.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i = 0; i < numEntries; ++i)
      {
        // use generateMarker to generate placeholders for the class links!
        result += generateMarker(i); // generate marker for entry i in the list
                                    // (order is left to right)
        if (i != numEntries - 1) // not the last entry, so we need a separator
        {
          if (i < numEntries - 2) // not the fore last entry
            result += ", ";
          else // the fore last entry
            result += ", ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorHindi::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 721 of file translator_hi.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i = 0; i < numEntries; ++i)
      {
        // use generateMarker to generate placeholders for the class links!
        result += generateMarker(i); // generate marker for entry i in the list
                                    // (order is left to right)
        if (i != numEntries - 1) // not the last entry, so we need a separator
        {
          if (i < numEntries - 2) // not the fore last entry
            result += ", ";
          else // the fore last entry
            result += ", ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_hi.h
doxygen/src/translator_hi.h