ExampleList Class Reference
#include <example.h>
Public Member Functions
bool inSort (const Example &ex)
bool inSort (const Example &ex)
Detailed Description
Definition at line 36 of file example.h.
Member Function Documentation
inSort() [1/2]
bool ExampleList::inSort (const Example & ex) [inline]
Definition at line 39 of file example.h.
    {
      auto it = std::find_if(begin(),end(),[&ex](const Example &e) { return e.name==ex.name; });
      if (it==end())
      {
        insert(std::upper_bound(begin(), end(), ex,
                 [](const auto &e1,const auto &e2) { return e1.name < e2.name; }
                ), ex
              );
        return true;
      }
      return false;
    }
References ghc::filesystem::begin(), e, ghc::filesystem::end(), and Example::name.
Referenced by ClassDefImpl::addExample(), and MemberDefImpl::addExample().
inSort() [2/2]
bool ExampleList::inSort (const Example & ex) [inline]
Definition at line 39 of file example.h.
    {
      auto it = std::find_if(begin(),end(),[&ex](const Example &e) { return e.name==ex.name; });
      if (it==end())
      {
        insert(std::upper_bound(begin(), end(), ex,
                 [](const auto &e1,const auto &e2) { return e1.name < e2.name; }
                ), ex
              );
        return true;
      }
      return false;
    }
References ghc::filesystem::begin(), e, ghc::filesystem::end(), and Example::name.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/example.h
doxygen/src/example.h