DefineManager Class Reference
Class that manages the defines available while preprocessing files.
Classes
class DefinesPerFile
Public Member Functions
void addInclude (std::string fromFileName, std::string toFileName)
void store (std::string fileName, const DefineMap &fromMap)
void retrieve (std::string fileName, DefineMap &toMap)
bool alreadyProcessed (std::string fileName) const
void addInclude (std::string fromFileName, std::string toFileName)
void store (std::string fileName, const DefineMap &fromMap)
void retrieve (std::string fileName, DefineMap &toMap)
bool alreadyProcessed (std::string fileName) const
Private Member Functions
DefinesPerFile * find (std::string fileName) const
DefinesPerFile * find (std::string fileName) const
Private Attributes
std::unordered_map< std::string, std::unique_ptr< DefinesPerFile > > m_fileMap
Friends
class DefinesPerFile
Detailed Description
Class that manages the defines available while preprocessing files.
Definition at line 121 of file pre.l.
Member Function Documentation
addInclude() [1/2]
void DefineManager::addInclude (std::string fromFileName, std::string toFileName) [inline]
Definition at line 180 of file pre.l.
    {
      //printf("DefineManager::addInclude('%s'->'%s')\n",fromFileName.c_str(),toFileName.c_str());
      auto it = m_fileMap.find(fromFileName);
      if (it==m_fileMap.end())
      {
        it = m_fileMap.emplace(fromFileName,std::make_unique<DefinesPerFile>(this)).first;
      }
      auto &dpf = it->second;
      dpf->addInclude(toFileName);
    }
References m_fileMap.
Referenced by readIncludeFile().
addInclude() [2/2]
void DefineManager::addInclude (std::string fromFileName, std::string toFileName) [inline]
Definition at line 180 of file pre.l.
    {
      //printf("DefineManager::addInclude('%s'->'%s')\n",fromFileName.c_str(),toFileName.c_str());
      auto it = m_fileMap.find(fromFileName);
      if (it==m_fileMap.end())
      {
        it = m_fileMap.emplace(fromFileName,std::make_unique<DefinesPerFile>(this)).first;
      }
      auto &dpf = it->second;
      dpf->addInclude(toFileName);
    }
References m_fileMap.
alreadyProcessed() [1/2]
bool DefineManager::alreadyProcessed (std::string fileName) const [inline]
Definition at line 214 of file pre.l.
    {
      auto it = m_fileMap.find(fileName);
      if (it!=m_fileMap.end())
      {
        return it->second->stored();
      }
      return false;
    }
References m_fileMap.
Referenced by checkAndOpenFile().
alreadyProcessed() [2/2]
bool DefineManager::alreadyProcessed (std::string fileName) const [inline]
Definition at line 214 of file pre.l.
    {
      auto it = m_fileMap.find(fileName);
      if (it!=m_fileMap.end())
      {
        return it->second->stored();
      }
      return false;
    }
References m_fileMap.
find() [1/2]
DefinesPerFile * DefineManager::find (std::string fileName) const [inline], [private]
Helper function to return the DefinesPerFile object for a given file name.
Definition at line 226 of file pre.l.
    {
      auto it = m_fileMap.find(fileName);
      return it!=m_fileMap.end() ? it->second.get() : nullptr;
    }
References m_fileMap.
Referenced by DefineManager::DefinesPerFile::retrieveRec().
find() [2/2]
DefinesPerFile * DefineManager::find (std::string fileName) const [inline], [private]
Helper function to return the DefinesPerFile object for a given file name.
Definition at line 226 of file pre.l.
    {
      auto it = m_fileMap.find(fileName);
      return it!=m_fileMap.end() ? it->second.get() : nullptr;
    }
References m_fileMap.
retrieve() [1/2]
void DefineManager::retrieve (std::string fileName, DefineMap & toMap) [inline]
Definition at line 203 of file pre.l.
    {
      auto it = m_fileMap.find(fileName);
      if (it!=m_fileMap.end())
      {
        auto &dpf = it->second;
        dpf->retrieve(toMap);
      }
      //printf("DefineManager::retrieve(%s,#=%zu)\n",fileName.c_str(),toMap.size());
    }
References m_fileMap.
Referenced by readIncludeFile().
retrieve() [2/2]
void DefineManager::retrieve (std::string fileName, DefineMap & toMap) [inline]
Definition at line 203 of file pre.l.
    {
      auto it = m_fileMap.find(fileName);
      if (it!=m_fileMap.end())
      {
        auto &dpf = it->second;
        dpf->retrieve(toMap);
      }
      //printf("DefineManager::retrieve(%s,#=%zu)\n",fileName.c_str(),toMap.size());
    }
References m_fileMap.
store() [1/2]
void DefineManager::store (std::string fileName, const DefineMap & fromMap) [inline]
Definition at line 192 of file pre.l.
    {
      //printf("DefineManager::store(%s,#=%zu)\n",fileName.c_str(),fromMap.size());
      auto it = m_fileMap.find(fileName);
      if (it==m_fileMap.end())
      {
        it = m_fileMap.emplace(fileName,std::make_unique<DefinesPerFile>(this)).first;
      }
      it->second->store(fromMap);
    }
References m_fileMap.
store() [2/2]
void DefineManager::store (std::string fileName, const DefineMap & fromMap) [inline]
Definition at line 192 of file pre.l.
    {
      //printf("DefineManager::store(%s,#=%zu)\n",fileName.c_str(),fromMap.size());
      auto it = m_fileMap.find(fileName);
      if (it==m_fileMap.end())
      {
        it = m_fileMap.emplace(fileName,std::make_unique<DefinesPerFile>(this)).first;
      }
      it->second->store(fromMap);
    }
References m_fileMap.
Friends And Related Function Documentation
DefinesPerFile
DefinesPerFile [friend]
Definition at line 177 of file pre.l.
Member Data Documentation
m_fileMap
std::unordered_map< std::string, std::unique_ptr< DefinesPerFile > > DefineManager::m_fileMap [private]
Definition at line 232 of file pre.l.
Referenced by addInclude(), alreadyProcessed(), find(), retrieve(), and store().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/pre.l
doxygen/src/pre.l