FileDef Class Reference
#include <filedef.h>
Public Member Functions
virtual DefType definitionType () const =0
virtual QCString name () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual QCString fileName () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual QCString getSourceFileBase () const =0
virtual QCString includeName () const =0
virtual QCString includeDependencyGraphFileName () const =0
virtual QCString includedByDependencyGraphFileName () const =0
virtual QCString absFilePath () const =0
virtual const QCString & docName () const =0
virtual bool isSource () const =0
virtual bool isDocumentationFile () const =0
virtual const Definition * getSourceDefinition (int lineNr) const =0
virtual const MemberDef * getSourceMember (int lineNr) const =0
virtual QCString getPath () const =0
virtual QCString getVersion () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isIncluded (const QCString &name) const =0
virtual PackageDef * packageDef () const =0
virtual DirDef * getDirDef () const =0
virtual const LinkedRefMap< const NamespaceDef > & getUsedNamespaces () const =0
virtual const LinkedRefMap< const ClassDef > & getUsedClasses () const =0
virtual const IncludeInfoList & includeFileList () const =0
virtual const IncludeInfoList & includedByFileList () const =0
virtual void getAllIncludeFilesRecursively (StringVector &incFiles) const =0
virtual MemberList * getMemberList (MemberListType lt) const =0
virtual const MemberLists & getMemberLists () const =0
virtual const MemberGroupList & getMemberGroups () const =0
virtual const NamespaceLinkedRefMap & getNamespaces () const =0
virtual const ConceptLinkedRefMap & getConcepts () const =0
virtual const ClassLinkedRefMap & getClasses () const =0
virtual QCString title () const =0
virtual bool hasDetailedDescription () const =0
virtual QCString fileVersion () const =0
virtual bool subGrouping () const =0
virtual void countMembers ()=0
virtual int numDocMembers () const =0
virtual int numDecMembers () const =0
virtual void addSourceRef (int line, const Definition *d, const MemberDef *md)=0
virtual void writeDocumentation (OutputList &ol)=0
virtual void writeMemberPages (OutputList &ol)=0
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const =0
virtual void writeSummaryLinks (OutputList &ol) const =0
virtual void writeTagFile (TextStream &t)=0
virtual void writeSourceHeader (OutputList &ol)=0
virtual void writeSourceBody (OutputList &ol, ClangTUParser *clangParser)=0
virtual void writeSourceFooter (OutputList &ol)=0
virtual void parseSource (ClangTUParser *clangParser)=0
virtual void setDiskName (const QCString &name)=0
virtual void insertMember (MemberDef *md)=0
virtual void insertClass (const ClassDef *cd)=0
virtual void insertConcept (const ConceptDef *cd)=0
virtual void insertNamespace (const NamespaceDef *nd)=0
virtual void computeAnchors ()=0
virtual void setPackageDef (PackageDef *pd)=0
virtual void setDirDef (DirDef *dd)=0
virtual void addUsingDirective (const NamespaceDef *nd)=0
virtual void addUsingDeclaration (const ClassDef *cd)=0
virtual void combineUsingRelations ()=0
virtual bool generateSourceFile () const =0
virtual void sortMemberLists ()=0
virtual void addIncludeDependency (const FileDef *fd, const QCString &incName, bool local, bool imported)=0
virtual void addIncludedByDependency (const FileDef *fd, const QCString &incName, bool local, bool imported)=0
virtual void addMembersToMemberGroup ()=0
virtual void distributeMemberGroupDocumentation ()=0
virtual void findSectionsInDocumentation ()=0
virtual void addIncludedUsingDirectives (FileDefSet &visitedFiles)=0
virtual void addListReferences ()=0
virtual DefType definitionType () const =0
virtual QCString name () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual QCString fileName () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual QCString getSourceFileBase () const =0
virtual QCString includeName () const =0
virtual QCString includeDependencyGraphFileName () const =0
virtual QCString includedByDependencyGraphFileName () const =0
virtual QCString absFilePath () const =0
virtual const QCString & docName () const =0
virtual bool isSource () const =0
virtual bool isDocumentationFile () const =0
virtual const Definition * getSourceDefinition (int lineNr) const =0
virtual const MemberDef * getSourceMember (int lineNr) const =0
virtual QCString getPath () const =0
virtual QCString getVersion () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isIncluded (const QCString &name) const =0
virtual PackageDef * packageDef () const =0
virtual DirDef * getDirDef () const =0
virtual const LinkedRefMap< const NamespaceDef > & getUsedNamespaces () const =0
virtual const LinkedRefMap< const ClassDef > & getUsedClasses () const =0
virtual const IncludeInfoList & includeFileList () const =0
virtual const IncludeInfoList & includedByFileList () const =0
virtual void getAllIncludeFilesRecursively (StringVector &incFiles) const =0
virtual MemberList * getMemberList (MemberListType lt) const =0
virtual const MemberLists & getMemberLists () const =0
virtual const MemberGroupList & getMemberGroups () const =0
virtual const NamespaceLinkedRefMap & getNamespaces () const =0
virtual const ConceptLinkedRefMap & getConcepts () const =0
virtual const ClassLinkedRefMap & getClasses () const =0
virtual QCString title () const =0
virtual bool hasDetailedDescription () const =0
virtual QCString fileVersion () const =0
virtual bool subGrouping () const =0
virtual void countMembers ()=0
virtual int numDocMembers () const =0
virtual int numDecMembers () const =0
virtual void addSourceRef (int line, const Definition *d, const MemberDef *md)=0
virtual void writeDocumentation (OutputList &ol)=0
virtual void writeMemberPages (OutputList &ol)=0
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const =0
virtual void writeSummaryLinks (OutputList &ol) const =0
virtual void writeTagFile (TextStream &t)=0
virtual void writeSourceHeader (OutputList &ol)=0
virtual void writeSourceBody (OutputList &ol, ClangTUParser *clangParser)=0
virtual void writeSourceFooter (OutputList &ol)=0
virtual void parseSource (ClangTUParser *clangParser)=0
virtual void setDiskName (const QCString &name)=0
virtual void insertMember (MemberDef *md)=0
virtual void insertClass (const ClassDef *cd)=0
virtual void insertConcept (const ConceptDef *cd)=0
virtual void insertNamespace (const NamespaceDef *nd)=0
virtual void computeAnchors ()=0
virtual void setPackageDef (PackageDef *pd)=0
virtual void setDirDef (DirDef *dd)=0
virtual void addUsingDirective (const NamespaceDef *nd)=0
virtual void addUsingDeclaration (const ClassDef *cd)=0
virtual void combineUsingRelations ()=0
virtual bool generateSourceFile () const =0
virtual void sortMemberLists ()=0
virtual void addIncludeDependency (const FileDef *fd, const QCString &incName, bool local, bool imported)=0
virtual void addIncludedByDependency (const FileDef *fd, const QCString &incName, bool local, bool imported)=0
virtual void addMembersToMemberGroup ()=0
virtual void distributeMemberGroupDocumentation ()=0
virtual void findSectionsInDocumentation ()=0
virtual void addIncludedUsingDirectives (FileDefSet &visitedFiles)=0
virtual void addListReferences ()=0
Additional Inherited Members
Detailed Description
A model of a file symbol.
An object of this class contains all file information that is gathered. This includes the members and compounds defined in the file.
The member writeDocumentation() can be used to generate the page of documentation to HTML and LaTeX.
Definition at line 72 of file filedef.h.
Member Function Documentation
absFilePath() [1/2]
virtual QCString FileDef::absFilePath () const [pure virtual]
Returns the absolute path including the file name.
Implemented in FileDefImpl, and FileDefImpl.
Referenced by FileDefImpl::addIncludedByDependency(), FileDefImpl::addIncludeDependency(), addIncludeFile(), addVariableToFile(), DotInclDepGraph::buildGraph(), VhdlDocGen::createFlowChart(), MemberContext::Private::createSourceCode(), DotInclDepGraph::DotInclDepGraph(), DocParser::findAndCopyImage(), findDefineDocumentation(), findXRefSymbols(), generateFileSources(), generateXMLForClass(), generateXMLForMember(), SymbolResolver::Private::getResolvedTypeRec(), DocbookDocVisitor::operator()(), XmlDocVisitor::operator()(), DocDotFile::parse(), DocMscFile::parse(), DocDiaFile::parse(), parseCode(), DocParser::readTextFileByName(), DefinitionImpl::writeInlineCode(), and writeXMLCodeBlock().
absFilePath() [2/2]
virtual QCString FileDef::absFilePath () const [pure virtual]
Returns the absolute path including the file name.
Implemented in FileDefImpl, and FileDefImpl.
addIncludedByDependency() [1/2]
virtual void FileDef::addIncludedByDependency (const FileDef * fd, const QCString & incName, bool local, bool imported) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
addIncludedByDependency() [2/2]
virtual void FileDef::addIncludedByDependency (const FileDef * fd, const QCString & incName, bool local, bool imported) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
addIncludeDependency() [1/2]
virtual void FileDef::addIncludeDependency (const FileDef * fd, const QCString & incName, bool local, bool imported) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
addIncludeDependency() [2/2]
virtual void FileDef::addIncludeDependency (const FileDef * fd, const QCString & incName, bool local, bool imported) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
addIncludedUsingDirectives() [1/2]
virtual void FileDef::addIncludedUsingDirectives (FileDefSet & visitedFiles) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
addIncludedUsingDirectives() [2/2]
virtual void FileDef::addIncludedUsingDirectives (FileDefSet & visitedFiles) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
addListReferences() [1/2]
virtual void FileDef::addListReferences () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by addListReferences().
addListReferences() [2/2]
virtual void FileDef::addListReferences () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
addMembersToMemberGroup() [1/2]
virtual void FileDef::addMembersToMemberGroup () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by addMembersToMemberGroup().
addMembersToMemberGroup() [2/2]
virtual void FileDef::addMembersToMemberGroup () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
addSourceRef() [1/2]
virtual void FileDef::addSourceRef (int line, const Definition * d, const MemberDef * md) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
addSourceRef() [2/2]
virtual void FileDef::addSourceRef (int line, const Definition * d, const MemberDef * md) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
addUsingDeclaration() [1/2]
virtual void FileDef::addUsingDeclaration (const ClassDef * cd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by findUsingDeclarations().
addUsingDeclaration() [2/2]
virtual void FileDef::addUsingDeclaration (const ClassDef * cd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
addUsingDirective() [1/2]
virtual void FileDef::addUsingDirective (const NamespaceDef * nd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by findUsingDirectives().
addUsingDirective() [2/2]
virtual void FileDef::addUsingDirective (const NamespaceDef * nd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
anchor() [1/2]
virtual QCString FileDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in FileDefImpl, and FileDefImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), MemberDefImpl::_writeGroupInclude(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), addToIndices(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString FileDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in FileDefImpl, and FileDefImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
combineUsingRelations() [1/2]
virtual void FileDef::combineUsingRelations () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by combineUsingRelations().
combineUsingRelations() [2/2]
virtual void FileDef::combineUsingRelations () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
computeAnchors() [1/2]
virtual void FileDef::computeAnchors () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by computeMemberReferences().
computeAnchors() [2/2]
virtual void FileDef::computeAnchors () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
countMembers() [1/2]
virtual void FileDef::countMembers () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by countMembers().
countMembers() [2/2]
virtual void FileDef::countMembers () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
definitionType() [1/2]
virtual DefType FileDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in FileDefImpl, and FileDefImpl.
definitionType() [2/2]
virtual DefType FileDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in FileDefImpl, and FileDefImpl.
displayName() [1/2]
virtual QCString FileDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in FileDefImpl, and FileDefImpl.
Referenced by MemberDefImpl::writeDocumentation().
displayName() [2/2]
virtual QCString FileDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in FileDefImpl, and FileDefImpl.
distributeMemberGroupDocumentation() [1/2]
virtual void FileDef::distributeMemberGroupDocumentation () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by distributeMemberGroupDocumentation().
distributeMemberGroupDocumentation() [2/2]
virtual void FileDef::distributeMemberGroupDocumentation () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
docName() [1/2]
virtual const QCString & FileDef::docName () const [pure virtual]
Returns the name as it is used in the documentation
Implemented in FileDefImpl, and FileDefImpl.
Referenced by MemberDefImpl::_writeGroupInclude(), PerlModGenerator::addIncludeInfo(), DotInclDepGraph::DotInclDepGraph(), generateFileDocs(), generateFileSources(), and writeIncludeInfo().
docName() [2/2]
virtual const QCString & FileDef::docName () const [pure virtual]
Returns the name as it is used in the documentation
Implemented in FileDefImpl, and FileDefImpl.
fileName() [1/2]
virtual QCString FileDef::fileName () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), CCodeParser::parseCode(), FortranCodeParser::parseCode(), PythonCodeParser::parseCode(), VHDLCodeParser::parseCode(), LexCodeParser::parseCode(), SQLCodeParser::parseCode(), XMLCodeParser::parseCode(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
virtual QCString FileDef::fileName () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileVersion() [1/2]
virtual QCString FileDef::fileVersion () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by FileContext::Private::version().
fileVersion() [2/2]
virtual QCString FileDef::fileVersion () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
findSectionsInDocumentation() [1/2]
virtual void FileDef::findSectionsInDocumentation () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by findSectionsInDocumentation().
findSectionsInDocumentation() [2/2]
virtual void FileDef::findSectionsInDocumentation () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
generateSourceFile() [1/2]
virtual bool FileDef::generateSourceFile () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by addIncludeFile(), addSourceReferences(), DotInclDepGraph::buildGraph(), FileContext::Private::createSources(), fileVisibleInIndex(), generateFileSources(), FileContext::Private::hasSourceFile(), FileDefImpl::writeIncludeFiles(), and writeSingleFileIndex().
generateSourceFile() [2/2]
virtual bool FileDef::generateSourceFile () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getAllIncludeFilesRecursively() [1/2]
virtual void FileDef::getAllIncludeFilesRecursively (StringVector & incFiles) const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by generateFileSources().
getAllIncludeFilesRecursively() [2/2]
virtual void FileDef::getAllIncludeFilesRecursively (StringVector & incFiles) const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getClasses() [1/2]
virtual const ClassLinkedRefMap & FileDef::getClasses () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by FileContext::Private::createClasses(), FileContext::Private::createInlineClasses(), and generateXMLForFile().
getClasses() [2/2]
virtual const ClassLinkedRefMap & FileDef::getClasses () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getConcepts() [1/2]
virtual const ConceptLinkedRefMap & FileDef::getConcepts () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by generateXMLForFile().
getConcepts() [2/2]
virtual const ConceptLinkedRefMap & FileDef::getConcepts () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getDirDef() [1/2]
virtual DirDef * FileDef::getDirDef () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by DefinitionImpl::navigationPathAsString(), and writePartialFilePath().
getDirDef() [2/2]
virtual DirDef * FileDef::getDirDef () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getMemberGroups() [1/2]
virtual const MemberGroupList & FileDef::getMemberGroups () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by FileContext::Private::createMemberGroups(), PerlModGenerator::generatePerlModForFile(), and generateXMLForFile().
getMemberGroups() [2/2]
virtual const MemberGroupList & FileDef::getMemberGroups () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getMemberList() [1/2]
virtual MemberList * FileDef::getMemberList (MemberListType lt) const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by NestingNodeContext::Private::addMembers(), cModule(), FileContext::Private::createMemberList(), generateDEFForFile(), and PerlModGenerator::generatePerlModForFile().
getMemberList() [2/2]
virtual MemberList * FileDef::getMemberList (MemberListType lt) const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getMemberLists() [1/2]
virtual const MemberLists & FileDef::getMemberLists () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by generateXMLForFile().
getMemberLists() [2/2]
virtual const MemberLists & FileDef::getMemberLists () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getNamespaces() [1/2]
virtual const NamespaceLinkedRefMap & FileDef::getNamespaces () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by FileContext::Private::createConstantgroups(), FileContext::Private::createNamespaces(), and generateXMLForFile().
getNamespaces() [2/2]
virtual const NamespaceLinkedRefMap & FileDef::getNamespaces () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getOutputFileBase() [1/2]
virtual QCString FileDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in FileDefImpl, and FileDefImpl.
Referenced by MemberDefImpl::_writeGroupInclude(), DotInclDepGraph::buildGraph(), cModule(), DotInclDepGraph::DotInclDepGraph(), generateDEFForFile(), generateFileRef(), generateXMLForFile(), ClassDefImpl::getOutputFileBase(), MemberDefImpl::getOutputFileBase(), ignoreStaticExternalCall(), FileContext::Private::includedByGraph(), FileContext::Private::includeGraph(), FilePair::key(), node2URL(), referenceTo(), FileDefImpl::writeIncludeFiles(), writeIncludeInfo(), writeMemberReference(), writePartialFilePath(), writeSingleFileIndex(), and FileDefImpl::writeTagFile().
getOutputFileBase() [2/2]
virtual QCString FileDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in FileDefImpl, and FileDefImpl.
getPath() [1/2]
virtual QCString FileDef::getPath () const [pure virtual]
Returns the absolute path of this file.
Implemented in FileDefImpl, and FileDefImpl.
Referenced by buildDirectories(), findFileDef(), generateDiskNames(), and writeSingleFileIndex().
getPath() [2/2]
virtual QCString FileDef::getPath () const [pure virtual]
Returns the absolute path of this file.
Implemented in FileDefImpl, and FileDefImpl.
getSourceDefinition() [1/2]
virtual const Definition * FileDef::getSourceDefinition (int lineNr) const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getSourceDefinition() [2/2]
virtual const Definition * FileDef::getSourceDefinition (int lineNr) const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getSourceFileBase() [1/2]
virtual QCString FileDef::getSourceFileBase () const [pure virtual]
Returns the name of the source listing of this definition.
Implements Definition.
Implemented in DefinitionMixin< FileDef >, FileDefImpl, DefinitionMixin< FileDef >, and FileDefImpl.
Referenced by DefinitionImpl::_writeSourceRefList(), DotInclDepGraph::buildGraph(), FTVHelp::Private::generateTree(), DefinitionImpl::getSourceFileBase(), node2URL(), and writeSingleFileIndex().
getSourceFileBase() [2/2]
virtual QCString FileDef::getSourceFileBase () const [pure virtual]
Returns the name of the source listing of this definition.
Implements Definition.
Implemented in DefinitionMixin< FileDef >, FileDefImpl, DefinitionMixin< FileDef >, and FileDefImpl.
getSourceMember() [1/2]
virtual const MemberDef * FileDef::getSourceMember (int lineNr) const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getSourceMember() [2/2]
virtual const MemberDef * FileDef::getSourceMember (int lineNr) const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getUsedClasses() [1/2]
virtual const LinkedRefMap< const ClassDef > & FileDef::getUsedClasses () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by SymbolResolver::Private::getResolvedTypeRec().
getUsedClasses() [2/2]
virtual const LinkedRefMap< const ClassDef > & FileDef::getUsedClasses () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getUsedNamespaces() [1/2]
virtual const LinkedRefMap< const NamespaceDef > & FileDef::getUsedNamespaces () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by findGlobalMember(), findMember(), findScopeFromQualifiedName(), findUsingDirectives(), generateClassOrGlobalLink(), and SymbolResolver::Private::getResolvedTypeRec().
getUsedNamespaces() [2/2]
virtual const LinkedRefMap< const NamespaceDef > & FileDef::getUsedNamespaces () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
getVersion() [1/2]
virtual QCString FileDef::getVersion () const [pure virtual]
Returns version of this file.
Implemented in FileDefImpl, and FileDefImpl.
Referenced by FileContext::Private::versionInfo().
getVersion() [2/2]
virtual QCString FileDef::getVersion () const [pure virtual]
Returns version of this file.
Implemented in FileDefImpl, and FileDefImpl.
hasDetailedDescription() [1/2]
virtual bool FileDef::hasDetailedDescription () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by FileContext::Private::hasDetails().
hasDetailedDescription() [2/2]
virtual bool FileDef::hasDetailedDescription () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
includedByDependencyGraphFileName() [1/2]
virtual QCString FileDef::includedByDependencyGraphFileName () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by DotInclDepGraph::DotInclDepGraph().
includedByDependencyGraphFileName() [2/2]
virtual QCString FileDef::includedByDependencyGraphFileName () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
includedByFileList() [1/2]
virtual const IncludeInfoList & FileDef::includedByFileList () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by DotInclDepGraph::buildGraph(), PerlModGenerator::generatePerlModForFile(), and generateXMLForFile().
includedByFileList() [2/2]
virtual const IncludeInfoList & FileDef::includedByFileList () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
includeDependencyGraphFileName() [1/2]
virtual QCString FileDef::includeDependencyGraphFileName () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by DotInclDepGraph::DotInclDepGraph().
includeDependencyGraphFileName() [2/2]
virtual QCString FileDef::includeDependencyGraphFileName () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
includeFileList() [1/2]
virtual const IncludeInfoList & FileDef::includeFileList () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by DotInclDepGraph::buildGraph(), FileContext::Private::createIncludeList(), PerlModGenerator::generatePerlModForFile(), generateXMLForFile(), getAllIncludeFilesRecursively(), and lookupSymbol().
includeFileList() [2/2]
virtual const IncludeInfoList & FileDef::includeFileList () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
includeName() [1/2]
virtual QCString FileDef::includeName () const [pure virtual]
Returns the name of the verbatim copy of this file (if any).
Implemented in FileDefImpl, and FileDefImpl.
Referenced by FileDefImpl::writeIncludeFiles(), and writeSingleFileIndex().
includeName() [2/2]
virtual QCString FileDef::includeName () const [pure virtual]
Returns the name of the verbatim copy of this file (if any).
Implemented in FileDefImpl, and FileDefImpl.
insertClass() [1/2]
virtual void FileDef::insertClass (const ClassDef * cd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by addClassToContext(), and createTagLessInstance().
insertClass() [2/2]
virtual void FileDef::insertClass (const ClassDef * cd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
insertConcept() [1/2]
virtual void FileDef::insertConcept (const ConceptDef * cd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by addConceptToContext().
insertConcept() [2/2]
virtual void FileDef::insertConcept (const ConceptDef * cd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
insertMember() [1/2]
virtual void FileDef::insertMember (MemberDef * md) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by addVariableToFile(), findEnums(), and NamespaceDefImpl::insertMember().
insertMember() [2/2]
virtual void FileDef::insertMember (MemberDef * md) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
insertNamespace() [1/2]
virtual void FileDef::insertNamespace (const NamespaceDef * nd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by buildNamespaceList(), and findUsingDirectives().
insertNamespace() [2/2]
virtual void FileDef::insertNamespace (const NamespaceDef * nd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
isDocumentationFile() [1/2]
virtual bool FileDef::isDocumentationFile () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by buildDirectories(), fileVisibleInIndex(), and writeSingleFileIndex().
isDocumentationFile() [2/2]
virtual bool FileDef::isDocumentationFile () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
isIncluded() [1/2]
virtual bool FileDef::isIncluded (const QCString & name) const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
isIncluded() [2/2]
virtual bool FileDef::isIncluded (const QCString & name) const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
isLinkable() [1/2]
virtual bool FileDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in FileDefImpl, and FileDefImpl.
Referenced by MemberDefImpl::_writeGroupInclude(), addMemberToSearchIndex(), DotInclDepGraph::buildGraph(), fileVisibleInIndex(), findMembersWithSpecificName(), generateFileRef(), getDefsOld(), getFortranDefs(), resolveLink(), FileDefImpl::writeIncludeFiles(), writePartialFilePath(), and FileDefImpl::writeTagFile().
isLinkable() [2/2]
virtual bool FileDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in FileDefImpl, and FileDefImpl.
isLinkableInProject() [1/2]
virtual bool FileDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in FileDefImpl, and FileDefImpl.
Referenced by MemberDefImpl::_computeLinkableInProject(), addFileMemberNameToIndex(), addToIndices(), GlobalsIndexContext::Private::createMembersFiltered(), fileVisibleInIndex(), generateFileDocs(), ClassDefImpl::isEmbeddedInOuterScope(), writeSingleFileIndex(), and writeTagFile().
isLinkableInProject() [2/2]
virtual bool FileDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in FileDefImpl, and FileDefImpl.
isSource() [1/2]
virtual bool FileDef::isSource () const [pure virtual]
Returns TRUE if this file is a source file.
Implemented in FileDefImpl, and FileDefImpl.
Referenced by generateFileSources(), parseFilesMultiThreading(), and parseFilesSingleThreading().
isSource() [2/2]
virtual bool FileDef::isSource () const [pure virtual]
Returns TRUE if this file is a source file.
Implemented in FileDefImpl, and FileDefImpl.
name() [1/2]
virtual QCString FileDef::name () const [pure virtual]
Returns the unique file name (this may include part of the path).
Implements Definition.
Implemented in DefinitionMixin< FileDef >, FileDefImpl, DefinitionMixin< FileDef >, and FileDefImpl.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), addIncludeFile(), DocSets::addIndexItem(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), compareFileDefs(), DefinitionContext< T >::DefinitionContext(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), DocParser::findAndCopyImage(), findEnumDocumentation(), findUsingDeclarations(), findXRefSymbols(), search.Finder::function(), generateDEFForFile(), PerlModGenerator::generatePerlModForFile(), generateXMLForFile(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), getDefs(), getDefsOld(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), isVarWithConstructor(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), search.Finder::variable(), writeFileLinkForMember(), writePartialFilePath(), writeSingleFileIndex(), DefinitionImpl::writeSourceDef(), FileDefImpl::writeTagFile(), and TooltipManager::writeTooltips().
name() [2/2]
virtual QCString FileDef::name () const [pure virtual]
Returns the unique file name (this may include part of the path).
Implements Definition.
Implemented in DefinitionMixin< FileDef >, FileDefImpl, DefinitionMixin< FileDef >, and FileDefImpl.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
numDecMembers() [1/2]
virtual int FileDef::numDecMembers () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
numDecMembers() [2/2]
virtual int FileDef::numDecMembers () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
numDocMembers() [1/2]
virtual int FileDef::numDocMembers () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
numDocMembers() [2/2]
virtual int FileDef::numDocMembers () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
packageDef() [1/2]
virtual PackageDef * FileDef::packageDef () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
packageDef() [2/2]
virtual PackageDef * FileDef::packageDef () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
parseSource() [1/2]
virtual void FileDef::parseSource (ClangTUParser * clangParser) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by generateFileSources().
parseSource() [2/2]
virtual void FileDef::parseSource (ClangTUParser * clangParser) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
setDirDef() [1/2]
virtual void FileDef::setDirDef (DirDef * dd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
setDirDef() [2/2]
virtual void FileDef::setDirDef (DirDef * dd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
setDiskName() [1/2]
virtual void FileDef::setDiskName (const QCString & name) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by generateDiskNames().
setDiskName() [2/2]
virtual void FileDef::setDiskName (const QCString & name) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
setPackageDef() [1/2]
virtual void FileDef::setPackageDef (PackageDef * pd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
setPackageDef() [2/2]
virtual void FileDef::setPackageDef (PackageDef * pd) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
sortMemberLists() [1/2]
virtual void FileDef::sortMemberLists () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by sortMemberLists().
sortMemberLists() [2/2]
virtual void FileDef::sortMemberLists () [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
subGrouping() [1/2]
virtual bool FileDef::subGrouping () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by FileContext::Private::createMemberGroups().
subGrouping() [2/2]
virtual bool FileDef::subGrouping () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
title() [1/2]
virtual QCString FileDef::title () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), and FileContext::Private::title().
title() [2/2]
virtual QCString FileDef::title () const [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
writeDocumentation() [1/2]
virtual void FileDef::writeDocumentation (OutputList & ol) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by generateFileDocs().
writeDocumentation() [2/2]
virtual void FileDef::writeDocumentation (OutputList & ol) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
writeMemberPages() [1/2]
virtual void FileDef::writeMemberPages (OutputList & ol) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
writeMemberPages() [2/2]
virtual void FileDef::writeMemberPages (OutputList & ol) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
writeQuickMemberLinks() [1/2]
virtual void FileDef::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const [pure virtual]
Implements DefinitionMutable.
Implemented in FileDefImpl, FileDefImpl, DefinitionMixin< FileDef >, and DefinitionMixin< FileDef >.
writeQuickMemberLinks() [2/2]
virtual void FileDef::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const [pure virtual]
Implements DefinitionMutable.
Implemented in FileDefImpl, FileDefImpl, DefinitionMixin< FileDef >, and DefinitionMixin< FileDef >.
writeSourceBody() [1/2]
virtual void FileDef::writeSourceBody (OutputList & ol, ClangTUParser * clangParser) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by generateFileSources().
writeSourceBody() [2/2]
virtual void FileDef::writeSourceBody (OutputList & ol, ClangTUParser * clangParser) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
writeSourceFooter() [1/2]
virtual void FileDef::writeSourceFooter (OutputList & ol) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by generateFileSources().
writeSourceFooter() [2/2]
virtual void FileDef::writeSourceFooter (OutputList & ol) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
writeSourceHeader() [1/2]
virtual void FileDef::writeSourceHeader (OutputList & ol) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by generateFileSources().
writeSourceHeader() [2/2]
virtual void FileDef::writeSourceHeader (OutputList & ol) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
writeSummaryLinks() [1/2]
virtual void FileDef::writeSummaryLinks (OutputList & ol) const [pure virtual]
Implements DefinitionMutable.
Implemented in DefinitionMixin< FileDef >, FileDefImpl, DefinitionMixin< FileDef >, and FileDefImpl.
writeSummaryLinks() [2/2]
virtual void FileDef::writeSummaryLinks (OutputList & ol) const [pure virtual]
Implements DefinitionMutable.
Implemented in DefinitionMixin< FileDef >, FileDefImpl, DefinitionMixin< FileDef >, and FileDefImpl.
writeTagFile() [1/2]
virtual void FileDef::writeTagFile (TextStream & t) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
Referenced by writeTagFile().
writeTagFile() [2/2]
virtual void FileDef::writeTagFile (TextStream & t) [pure virtual]
Implemented in FileDefImpl, and FileDefImpl.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/filedef.h
doxygen/src/filedef.h