NamespaceContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (const NamespaceDef *nd)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (const NamespaceDef *nd)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant compoundType () const
TemplateVariant hasDetails () const
TemplateVariant classes () const
TemplateVariant namespaces () const
TemplateVariant constantgroups () const
TemplateVariant typedefs () const
TemplateVariant sequences () const
TemplateVariant dictionaries () const
TemplateVariant enums () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant memberGroups () const
TemplateVariant detailedTypedefs () const
TemplateVariant detailedSequences () const
TemplateVariant detailedDictionaries () const
TemplateVariant detailedEnums () const
TemplateVariant detailedFunctions () const
TemplateVariant detailedVariables () const
TemplateVariant inlineClasses () const
TemplateVariant createClasses () const
TemplateVariant createNamespaces () const
TemplateVariant createConstantgroups () const
TemplateVariant createMemberList (MemberListType type, const QCString &title) const
TemplateVariant createTypedefs () const
TemplateVariant createSequences () const
TemplateVariant createDictionaries () const
TemplateVariant createEnums () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createDetailedTypedefs () const
TemplateVariant createDetailedSequences () const
TemplateVariant createDetailedDictionaries () const
TemplateVariant createDetailedEnums () const
TemplateVariant createDetailedFunctions () const
TemplateVariant createDetailedVariables () const
TemplateVariant createMemberGroups () const
TemplateVariant createInlineClasses () const
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant compoundType () const
TemplateVariant hasDetails () const
TemplateVariant classes () const
TemplateVariant namespaces () const
TemplateVariant constantgroups () const
TemplateVariant typedefs () const
TemplateVariant sequences () const
TemplateVariant dictionaries () const
TemplateVariant enums () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant memberGroups () const
TemplateVariant detailedTypedefs () const
TemplateVariant detailedSequences () const
TemplateVariant detailedDictionaries () const
TemplateVariant detailedEnums () const
TemplateVariant detailedFunctions () const
TemplateVariant detailedVariables () const
TemplateVariant inlineClasses () const
TemplateVariant createClasses () const
TemplateVariant createNamespaces () const
TemplateVariant createConstantgroups () const
TemplateVariant createMemberList (MemberListType type, const QCString &title) const
TemplateVariant createTypedefs () const
TemplateVariant createSequences () const
TemplateVariant createDictionaries () const
TemplateVariant createEnums () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createDetailedTypedefs () const
TemplateVariant createDetailedSequences () const
TemplateVariant createDetailedDictionaries () const
TemplateVariant createDetailedEnums () const
TemplateVariant createDetailedFunctions () const
TemplateVariant createDetailedVariables () const
TemplateVariant createMemberGroups () const
TemplateVariant createInlineClasses () const
Private Attributes
const NamespaceDef * m_namespaceDef
Cachable m_cachable
Static Private Attributes
static const PropertyMap< NamespaceContext::Private > s_inst
Additional Inherited Members
Detailed Description
Definition at line 2492 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
NamespaceContext::Private::Private (const NamespaceDef * nd) [inline]
Definition at line 2495 of file context.cpp.
                                    : DefinitionContext<NamespaceContext::Private>(nd),
                                m_namespaceDef(nd)
    {
    }
Private() [2/2]
NamespaceContext::Private::Private (const NamespaceDef * nd) [inline]
Definition at line 2495 of file context.cpp.
                                    : DefinitionContext<NamespaceContext::Private>(nd),
                                m_namespaceDef(nd)
    {
    }
Member Function Documentation
classes() [1/2]
TemplateVariant NamespaceContext::Private::classes () const [inline], [private]
Definition at line 2511 of file context.cpp.
{ return m_cachable.classes.get(this); }
References NamespaceContext::Private::Cachable::classes, and m_cachable.
classes() [2/2]
TemplateVariant NamespaceContext::Private::classes () const [inline], [private]
Definition at line 2511 of file context.cpp.
{ return m_cachable.classes.get(this); }
compoundType() [1/2]
TemplateVariant NamespaceContext::Private::compoundType () const [inline], [private]
Definition at line 2509 of file context.cpp.
{ return m_namespaceDef->compoundTypeString(); }
References NamespaceDef::compoundTypeString(), and m_namespaceDef.
compoundType() [2/2]
TemplateVariant NamespaceContext::Private::compoundType () const [inline], [private]
Definition at line 2509 of file context.cpp.
{ return m_namespaceDef->compoundTypeString(); }
constantgroups() [1/2]
TemplateVariant NamespaceContext::Private::constantgroups () const [inline], [private]
Definition at line 2513 of file context.cpp.
{ return m_cachable.constantgroups.get(this); }
References NamespaceContext::Private::Cachable::constantgroups, and m_cachable.
constantgroups() [2/2]
TemplateVariant NamespaceContext::Private::constantgroups () const [inline], [private]
Definition at line 2513 of file context.cpp.
{ return m_cachable.constantgroups.get(this); }
createClasses() [1/2]
TemplateVariant NamespaceContext::Private::createClasses () const [inline], [private]
Definition at line 2530 of file context.cpp.
    {
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      TemplateVariantList classList;
      classList.reserve(m_namespaceDef->getClasses().size());
      for (const auto &cd : m_namespaceDef->getClasses())
      {
        if (sliceOpt && (cd->compoundType()==ClassDef::Struct ||
                         cd->compoundType()==ClassDef::Interface ||
                         cd->compoundType()==ClassDef::Exception))
        {
          continue; // These types appear in their own sections.
        }
        if (cd->visibleInParentsDeclList())
        {
          classList.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(classList);
    }
References ClassContext::alloc(), TemplateImmutableList::alloc(), Config_getBool, ClassDef::Exception, NamespaceDef::getClasses(), ClassDef::Interface, m_namespaceDef, LinkedRefMap< T, Hash, KeyEqual, Map >::size(), and ClassDef::Struct.
createClasses() [2/2]
TemplateVariant NamespaceContext::Private::createClasses () const [inline], [private]
Definition at line 2530 of file context.cpp.
    {
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      TemplateVariantList classList;
      classList.reserve(m_namespaceDef->getClasses().size());
      for (const auto &cd : m_namespaceDef->getClasses())
      {
        if (sliceOpt && (cd->compoundType()==ClassDef::Struct ||
                         cd->compoundType()==ClassDef::Interface ||
                         cd->compoundType()==ClassDef::Exception))
        {
          continue; // These types appear in their own sections.
        }
        if (cd->visibleInParentsDeclList())
        {
          classList.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(classList);
    }
References ClassContext::alloc(), TemplateImmutableList::alloc(), Config_getBool, ClassDef::Exception, ClassDef::Interface, and ClassDef::Struct.
createConstantgroups() [1/2]
TemplateVariant NamespaceContext::Private::createConstantgroups () const [inline], [private]
Definition at line 2563 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_namespaceDef->getNamespaces().size());
      for (const auto &nd : m_namespaceDef->getNamespaces())
      {
        if (nd->isLinkable() && nd->isConstantGroup())
        {
          list.push_back(NamespaceContext::alloc(nd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References NamespaceContext::alloc(), TemplateImmutableList::alloc(), NamespaceDef::getNamespaces(), m_namespaceDef, and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
createConstantgroups() [2/2]
TemplateVariant NamespaceContext::Private::createConstantgroups () const [inline], [private]
Definition at line 2563 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_namespaceDef->getNamespaces().size());
      for (const auto &nd : m_namespaceDef->getNamespaces())
      {
        if (nd->isLinkable() && nd->isConstantGroup())
        {
          list.push_back(NamespaceContext::alloc(nd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References NamespaceContext::alloc(), and TemplateImmutableList::alloc().
createDetailedDictionaries() [1/2]
TemplateVariant NamespaceContext::Private::createDetailedDictionaries () const [inline], [private]
Definition at line 2619 of file context.cpp.
    {
      return createMemberList(MemberListType_docDictionaryMembers,theTranslator->trDictionaryDocumentation());
    }
References createMemberList(), MemberListType_docDictionaryMembers, theTranslator, and Translator::trDictionaryDocumentation().
createDetailedDictionaries() [2/2]
TemplateVariant NamespaceContext::Private::createDetailedDictionaries () const [inline], [private]
Definition at line 2619 of file context.cpp.
    {
      return createMemberList(MemberListType_docDictionaryMembers,theTranslator->trDictionaryDocumentation());
    }
References MemberListType_docDictionaryMembers, theTranslator, and Translator::trDictionaryDocumentation().
createDetailedEnums() [1/2]
TemplateVariant NamespaceContext::Private::createDetailedEnums () const [inline], [private]
Definition at line 2623 of file context.cpp.
    {
      return createMemberList(MemberListType_docEnumMembers,theTranslator->trEnumerationTypeDocumentation());
    }
References createMemberList(), MemberListType_docEnumMembers, theTranslator, and Translator::trEnumerationTypeDocumentation().
createDetailedEnums() [2/2]
TemplateVariant NamespaceContext::Private::createDetailedEnums () const [inline], [private]
Definition at line 2623 of file context.cpp.
    {
      return createMemberList(MemberListType_docEnumMembers,theTranslator->trEnumerationTypeDocumentation());
    }
References MemberListType_docEnumMembers, theTranslator, and Translator::trEnumerationTypeDocumentation().
createDetailedFunctions() [1/2]
TemplateVariant NamespaceContext::Private::createDetailedFunctions () const [inline], [private]
Definition at line 2627 of file context.cpp.
    {
      SrcLangExt lang = m_namespaceDef->getLanguage();
      return createMemberList(MemberListType_docFuncMembers, lang==SrcLangExt_Fortran ? theTranslator->trSubprogramDocumentation() :
                                                                                        theTranslator->trFunctionDocumentation());
    }
References createMemberList(), Definition::getLanguage(), m_namespaceDef, MemberListType_docFuncMembers, SrcLangExt_Fortran, theTranslator, Translator::trFunctionDocumentation(), and Translator::trSubprogramDocumentation().
createDetailedFunctions() [2/2]
TemplateVariant NamespaceContext::Private::createDetailedFunctions () const [inline], [private]
Definition at line 2627 of file context.cpp.
    {
      SrcLangExt lang = m_namespaceDef->getLanguage();
      return createMemberList(MemberListType_docFuncMembers, lang==SrcLangExt_Fortran ? theTranslator->trSubprogramDocumentation() :
                                                                                        theTranslator->trFunctionDocumentation());
    }
References MemberListType_docFuncMembers, SrcLangExt_Fortran, theTranslator, Translator::trFunctionDocumentation(), and Translator::trSubprogramDocumentation().
createDetailedSequences() [1/2]
TemplateVariant NamespaceContext::Private::createDetailedSequences () const [inline], [private]
Definition at line 2615 of file context.cpp.
    {
      return createMemberList(MemberListType_docSequenceMembers,theTranslator->trSequenceDocumentation());
    }
References createMemberList(), MemberListType_docSequenceMembers, theTranslator, and Translator::trSequenceDocumentation().
createDetailedSequences() [2/2]
TemplateVariant NamespaceContext::Private::createDetailedSequences () const [inline], [private]
Definition at line 2615 of file context.cpp.
    {
      return createMemberList(MemberListType_docSequenceMembers,theTranslator->trSequenceDocumentation());
    }
References MemberListType_docSequenceMembers, theTranslator, and Translator::trSequenceDocumentation().
createDetailedTypedefs() [1/2]
TemplateVariant NamespaceContext::Private::createDetailedTypedefs () const [inline], [private]
Definition at line 2611 of file context.cpp.
    {
      return createMemberList(MemberListType_docTypedefMembers,theTranslator->trTypedefDocumentation());
    }
References createMemberList(), MemberListType_docTypedefMembers, theTranslator, and Translator::trTypedefDocumentation().
createDetailedTypedefs() [2/2]
TemplateVariant NamespaceContext::Private::createDetailedTypedefs () const [inline], [private]
Definition at line 2611 of file context.cpp.
    {
      return createMemberList(MemberListType_docTypedefMembers,theTranslator->trTypedefDocumentation());
    }
References MemberListType_docTypedefMembers, theTranslator, and Translator::trTypedefDocumentation().
createDetailedVariables() [1/2]
TemplateVariant NamespaceContext::Private::createDetailedVariables () const [inline], [private]
Definition at line 2633 of file context.cpp.
    {
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      return createMemberList(MemberListType_docVarMembers, sliceOpt ? theTranslator->trConstantDocumentation() :
                                                                       theTranslator->trVariableDocumentation());
    }
References Config_getBool, createMemberList(), MemberListType_docVarMembers, theTranslator, Translator::trConstantDocumentation(), and Translator::trVariableDocumentation().
createDetailedVariables() [2/2]
TemplateVariant NamespaceContext::Private::createDetailedVariables () const [inline], [private]
Definition at line 2633 of file context.cpp.
    {
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      return createMemberList(MemberListType_docVarMembers, sliceOpt ? theTranslator->trConstantDocumentation() :
                                                                       theTranslator->trVariableDocumentation());
    }
References Config_getBool, MemberListType_docVarMembers, theTranslator, Translator::trConstantDocumentation(), and Translator::trVariableDocumentation().
createDictionaries() [1/2]
TemplateVariant NamespaceContext::Private::createDictionaries () const [inline], [private]
Definition at line 2590 of file context.cpp.
    {
      return createMemberList(MemberListType_decDictionaryMembers,theTranslator->trDictionaries());
    }
References createMemberList(), MemberListType_decDictionaryMembers, theTranslator, and Translator::trDictionaries().
createDictionaries() [2/2]
TemplateVariant NamespaceContext::Private::createDictionaries () const [inline], [private]
Definition at line 2590 of file context.cpp.
    {
      return createMemberList(MemberListType_decDictionaryMembers,theTranslator->trDictionaries());
    }
References MemberListType_decDictionaryMembers, theTranslator, and Translator::trDictionaries().
createEnums() [1/2]
TemplateVariant NamespaceContext::Private::createEnums () const [inline], [private]
Definition at line 2594 of file context.cpp.
    {
      return createMemberList(MemberListType_decEnumMembers,theTranslator->trEnumerations());
    }
References createMemberList(), MemberListType_decEnumMembers, theTranslator, and Translator::trEnumerations().
createEnums() [2/2]
TemplateVariant NamespaceContext::Private::createEnums () const [inline], [private]
Definition at line 2594 of file context.cpp.
    {
      return createMemberList(MemberListType_decEnumMembers,theTranslator->trEnumerations());
    }
References MemberListType_decEnumMembers, theTranslator, and Translator::trEnumerations().
createFunctions() [1/2]
TemplateVariant NamespaceContext::Private::createFunctions () const [inline], [private]
Definition at line 2598 of file context.cpp.
    {
      SrcLangExt lang = m_namespaceDef->getLanguage();
      return createMemberList(MemberListType_decFuncMembers,lang==SrcLangExt_Fortran ? theTranslator->trSubprograms() :
                                                            lang==SrcLangExt_VHDL ? theTranslator->trFunctionAndProc() :
                                                                                       theTranslator->trFunctions());
    }
References createMemberList(), Definition::getLanguage(), m_namespaceDef, MemberListType_decFuncMembers, SrcLangExt_Fortran, SrcLangExt_VHDL, theTranslator, Translator::trFunctionAndProc(), Translator::trFunctions(), and Translator::trSubprograms().
createFunctions() [2/2]
TemplateVariant NamespaceContext::Private::createFunctions () const [inline], [private]
Definition at line 2598 of file context.cpp.
    {
      SrcLangExt lang = m_namespaceDef->getLanguage();
      return createMemberList(MemberListType_decFuncMembers,lang==SrcLangExt_Fortran ? theTranslator->trSubprograms() :
                                                            lang==SrcLangExt_VHDL ? theTranslator->trFunctionAndProc() :
                                                                                       theTranslator->trFunctions());
    }
References MemberListType_decFuncMembers, SrcLangExt_Fortran, SrcLangExt_VHDL, theTranslator, Translator::trFunctionAndProc(), Translator::trFunctions(), and Translator::trSubprograms().
createInlineClasses() [1/2]
TemplateVariant NamespaceContext::Private::createInlineClasses () const [inline], [private]
Definition at line 2647 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_namespaceDef->getClasses().size());
      for (const auto &cd : m_namespaceDef->getClasses())
      {
        if (!cd->isAnonymous() &&
            cd->isLinkableInProject() &&
            cd->isEmbeddedInOuterScope() &&
            cd->partOfGroups().empty())
        {
          list.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ClassContext::alloc(), TemplateImmutableList::alloc(), NamespaceDef::getClasses(), m_namespaceDef, and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
createInlineClasses() [2/2]
TemplateVariant NamespaceContext::Private::createInlineClasses () const [inline], [private]
Definition at line 2647 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_namespaceDef->getClasses().size());
      for (const auto &cd : m_namespaceDef->getClasses())
      {
        if (!cd->isAnonymous() &&
            cd->isLinkableInProject() &&
            cd->isEmbeddedInOuterScope() &&
            cd->partOfGroups().empty())
        {
          list.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ClassContext::alloc(), and TemplateImmutableList::alloc().
createMemberGroups() [1/2]
TemplateVariant NamespaceContext::Private::createMemberGroups () const [inline], [private]
Definition at line 2639 of file context.cpp.
    {
      return !m_namespaceDef->getMemberGroups().empty() ?
              MemberGroupListContext::alloc(m_namespaceDef,relPathAsString(),
                                                            m_namespaceDef->getMemberGroups(),
                                                            m_namespaceDef->subGrouping()) :
              MemberGroupListContext::alloc();
    }
References MemberGroupListContext::alloc(), NamespaceDef::getMemberGroups(), m_namespaceDef, DefinitionContext< NamespaceContext::Private >::relPathAsString(), and NamespaceDef::subGrouping().
createMemberGroups() [2/2]
TemplateVariant NamespaceContext::Private::createMemberGroups () const [inline], [private]
Definition at line 2639 of file context.cpp.
    {
      return !m_namespaceDef->getMemberGroups().empty() ?
              MemberGroupListContext::alloc(m_namespaceDef,relPathAsString(),
                                                            m_namespaceDef->getMemberGroups(),
                                                            m_namespaceDef->subGrouping()) :
              MemberGroupListContext::alloc();
    }
References MemberGroupListContext::alloc().
createMemberList() [1/2]
TemplateVariant NamespaceContext::Private::createMemberList (MemberListType type, const QCString & title) const [inline], [private]
Definition at line 2576 of file context.cpp.
    {
      const MemberList *ml = m_namespaceDef->getMemberList(type);
      return ml ? TemplateVariant(MemberListInfoContext::alloc(m_namespaceDef,relPathAsString(),ml,title,""))
                : TemplateVariant(false);
    }
References MemberListInfoContext::alloc(), NamespaceDef::getMemberList(), m_namespaceDef, DefinitionContext< NamespaceContext::Private >::relPathAsString(), and title().
Referenced by createDetailedDictionaries(), createDetailedEnums(), createDetailedFunctions(), createDetailedSequences(), createDetailedTypedefs(), createDetailedVariables(), createDictionaries(), createEnums(), createFunctions(), createSequences(), createTypedefs(), and createVariables().
createMemberList() [2/2]
TemplateVariant NamespaceContext::Private::createMemberList (MemberListType type, const QCString & title) const [inline], [private]
Definition at line 2576 of file context.cpp.
    {
      const MemberList *ml = m_namespaceDef->getMemberList(type);
      return ml ? TemplateVariant(MemberListInfoContext::alloc(m_namespaceDef,relPathAsString(),ml,title,""))
                : TemplateVariant(false);
    }
References MemberListInfoContext::alloc().
createNamespaces() [1/2]
TemplateVariant NamespaceContext::Private::createNamespaces () const [inline], [private]
Definition at line 2550 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_namespaceDef->getNamespaces().size());
      for (const auto &nd : m_namespaceDef->getNamespaces())
      {
        if (nd->isLinkable() && !nd->isConstantGroup())
        {
          list.push_back(NamespaceContext::alloc(nd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References NamespaceContext::alloc(), TemplateImmutableList::alloc(), NamespaceDef::getNamespaces(), m_namespaceDef, and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
createNamespaces() [2/2]
TemplateVariant NamespaceContext::Private::createNamespaces () const [inline], [private]
Definition at line 2550 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_namespaceDef->getNamespaces().size());
      for (const auto &nd : m_namespaceDef->getNamespaces())
      {
        if (nd->isLinkable() && !nd->isConstantGroup())
        {
          list.push_back(NamespaceContext::alloc(nd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References NamespaceContext::alloc(), and TemplateImmutableList::alloc().
createSequences() [1/2]
TemplateVariant NamespaceContext::Private::createSequences () const [inline], [private]
Definition at line 2586 of file context.cpp.
    {
      return createMemberList(MemberListType_decSequenceMembers,theTranslator->trSequences());
    }
References createMemberList(), MemberListType_decSequenceMembers, theTranslator, and Translator::trSequences().
createSequences() [2/2]
TemplateVariant NamespaceContext::Private::createSequences () const [inline], [private]
Definition at line 2586 of file context.cpp.
    {
      return createMemberList(MemberListType_decSequenceMembers,theTranslator->trSequences());
    }
References MemberListType_decSequenceMembers, theTranslator, and Translator::trSequences().
createTypedefs() [1/2]
TemplateVariant NamespaceContext::Private::createTypedefs () const [inline], [private]
Definition at line 2582 of file context.cpp.
    {
      return createMemberList(MemberListType_decTypedefMembers,theTranslator->trTypedefs());
    }
References createMemberList(), MemberListType_decTypedefMembers, theTranslator, and Translator::trTypedefs().
createTypedefs() [2/2]
TemplateVariant NamespaceContext::Private::createTypedefs () const [inline], [private]
Definition at line 2582 of file context.cpp.
    {
      return createMemberList(MemberListType_decTypedefMembers,theTranslator->trTypedefs());
    }
References MemberListType_decTypedefMembers, theTranslator, and Translator::trTypedefs().
createVariables() [1/2]
TemplateVariant NamespaceContext::Private::createVariables () const [inline], [private]
Definition at line 2605 of file context.cpp.
    {
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      return createMemberList(MemberListType_decVarMembers, sliceOpt ? theTranslator->trConstants() :
                                                                       theTranslator->trVariables());
    }
References Config_getBool, createMemberList(), MemberListType_decVarMembers, theTranslator, Translator::trConstants(), and Translator::trVariables().
createVariables() [2/2]
TemplateVariant NamespaceContext::Private::createVariables () const [inline], [private]
Definition at line 2605 of file context.cpp.
    {
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      return createMemberList(MemberListType_decVarMembers, sliceOpt ? theTranslator->trConstants() :
                                                                       theTranslator->trVariables());
    }
References Config_getBool, MemberListType_decVarMembers, theTranslator, Translator::trConstants(), and Translator::trVariables().
detailedDictionaries() [1/2]
TemplateVariant NamespaceContext::Private::detailedDictionaries () const [inline], [private]
Definition at line 2523 of file context.cpp.
{ return m_cachable.detailedDictionaries.get(this); }
References NamespaceContext::Private::Cachable::detailedDictionaries, and m_cachable.
detailedDictionaries() [2/2]
TemplateVariant NamespaceContext::Private::detailedDictionaries () const [inline], [private]
Definition at line 2523 of file context.cpp.
{ return m_cachable.detailedDictionaries.get(this); }
detailedEnums() [1/2]
TemplateVariant NamespaceContext::Private::detailedEnums () const [inline], [private]
Definition at line 2524 of file context.cpp.
{ return m_cachable.detailedEnums.get(this); }
References NamespaceContext::Private::Cachable::detailedEnums, and m_cachable.
detailedEnums() [2/2]
TemplateVariant NamespaceContext::Private::detailedEnums () const [inline], [private]
Definition at line 2524 of file context.cpp.
{ return m_cachable.detailedEnums.get(this); }
detailedFunctions() [1/2]
TemplateVariant NamespaceContext::Private::detailedFunctions () const [inline], [private]
Definition at line 2525 of file context.cpp.
{ return m_cachable.detailedFunctions.get(this); }
References NamespaceContext::Private::Cachable::detailedFunctions, and m_cachable.
detailedFunctions() [2/2]
TemplateVariant NamespaceContext::Private::detailedFunctions () const [inline], [private]
Definition at line 2525 of file context.cpp.
{ return m_cachable.detailedFunctions.get(this); }
detailedSequences() [1/2]
TemplateVariant NamespaceContext::Private::detailedSequences () const [inline], [private]
Definition at line 2522 of file context.cpp.
{ return m_cachable.detailedSequences.get(this); }
References NamespaceContext::Private::Cachable::detailedSequences, and m_cachable.
detailedSequences() [2/2]
TemplateVariant NamespaceContext::Private::detailedSequences () const [inline], [private]
Definition at line 2522 of file context.cpp.
{ return m_cachable.detailedSequences.get(this); }
detailedTypedefs() [1/2]
TemplateVariant NamespaceContext::Private::detailedTypedefs () const [inline], [private]
Definition at line 2521 of file context.cpp.
{ return m_cachable.detailedTypedefs.get(this); }
References NamespaceContext::Private::Cachable::detailedTypedefs, and m_cachable.
detailedTypedefs() [2/2]
TemplateVariant NamespaceContext::Private::detailedTypedefs () const [inline], [private]
Definition at line 2521 of file context.cpp.
{ return m_cachable.detailedTypedefs.get(this); }
detailedVariables() [1/2]
TemplateVariant NamespaceContext::Private::detailedVariables () const [inline], [private]
Definition at line 2526 of file context.cpp.
{ return m_cachable.detailedVariables.get(this); }
References NamespaceContext::Private::Cachable::detailedVariables, and m_cachable.
detailedVariables() [2/2]
TemplateVariant NamespaceContext::Private::detailedVariables () const [inline], [private]
Definition at line 2526 of file context.cpp.
{ return m_cachable.detailedVariables.get(this); }
dictionaries() [1/2]
TemplateVariant NamespaceContext::Private::dictionaries () const [inline], [private]
Definition at line 2516 of file context.cpp.
{ return m_cachable.dictionaries.get(this); }
References NamespaceContext::Private::Cachable::dictionaries, and m_cachable.
dictionaries() [2/2]
TemplateVariant NamespaceContext::Private::dictionaries () const [inline], [private]
Definition at line 2516 of file context.cpp.
{ return m_cachable.dictionaries.get(this); }
enums() [1/2]
TemplateVariant NamespaceContext::Private::enums () const [inline], [private]
Definition at line 2517 of file context.cpp.
{ return m_cachable.enums.get(this); }
References NamespaceContext::Private::Cachable::enums, and m_cachable.
enums() [2/2]
TemplateVariant NamespaceContext::Private::enums () const [inline], [private]
Definition at line 2517 of file context.cpp.
{ return m_cachable.enums.get(this); }
fields() [1/2]
StringVector NamespaceContext::Private::fields () const [inline]
Definition at line 2502 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector NamespaceContext::Private::fields () const [inline]
Definition at line 2502 of file context.cpp.
{ return s_inst.fields(); }
functions() [1/2]
TemplateVariant NamespaceContext::Private::functions () const [inline], [private]
Definition at line 2518 of file context.cpp.
{ return m_cachable.functions.get(this); }
References NamespaceContext::Private::Cachable::functions, and m_cachable.
functions() [2/2]
TemplateVariant NamespaceContext::Private::functions () const [inline], [private]
Definition at line 2518 of file context.cpp.
{ return m_cachable.functions.get(this); }
get() [1/2]
TemplateVariant NamespaceContext::Private::get (const QCString & n) const [inline]
Definition at line 2501 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant NamespaceContext::Private::get (const QCString & n) const [inline]
Definition at line 2501 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
hasDetails() [1/2]
TemplateVariant NamespaceContext::Private::hasDetails () const [inline], [private]
Definition at line 2510 of file context.cpp.
{ return m_namespaceDef->hasDetailedDescription(); }
References NamespaceDef::hasDetailedDescription(), and m_namespaceDef.
hasDetails() [2/2]
TemplateVariant NamespaceContext::Private::hasDetails () const [inline], [private]
Definition at line 2510 of file context.cpp.
{ return m_namespaceDef->hasDetailedDescription(); }
highlight() [1/2]
TemplateVariant NamespaceContext::Private::highlight () const [inline], [private]
Definition at line 2507 of file context.cpp.
{ return TemplateVariant("namespaces"); }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant NamespaceContext::Private::highlight () const [inline], [private]
Definition at line 2507 of file context.cpp.
{ return TemplateVariant("namespaces"); }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
inlineClasses() [1/2]
TemplateVariant NamespaceContext::Private::inlineClasses () const [inline], [private]
Definition at line 2527 of file context.cpp.
{ return m_cachable.inlineClasses.get(this); }
References NamespaceContext::Private::Cachable::inlineClasses, and m_cachable.
inlineClasses() [2/2]
TemplateVariant NamespaceContext::Private::inlineClasses () const [inline], [private]
Definition at line 2527 of file context.cpp.
{ return m_cachable.inlineClasses.get(this); }
memberGroups() [1/2]
TemplateVariant NamespaceContext::Private::memberGroups () const [inline], [private]
Definition at line 2520 of file context.cpp.
{ return m_cachable.memberGroups.get(this); }
References m_cachable, and NamespaceContext::Private::Cachable::memberGroups.
memberGroups() [2/2]
TemplateVariant NamespaceContext::Private::memberGroups () const [inline], [private]
Definition at line 2520 of file context.cpp.
{ return m_cachable.memberGroups.get(this); }
namespaces() [1/2]
TemplateVariant NamespaceContext::Private::namespaces () const [inline], [private]
Definition at line 2512 of file context.cpp.
{ return m_cachable.namespaces.get(this); }
References m_cachable, and NamespaceContext::Private::Cachable::namespaces.
namespaces() [2/2]
TemplateVariant NamespaceContext::Private::namespaces () const [inline], [private]
Definition at line 2512 of file context.cpp.
{ return m_cachable.namespaces.get(this); }
sequences() [1/2]
TemplateVariant NamespaceContext::Private::sequences () const [inline], [private]
Definition at line 2515 of file context.cpp.
{ return m_cachable.sequences.get(this); }
References m_cachable, and NamespaceContext::Private::Cachable::sequences.
sequences() [2/2]
TemplateVariant NamespaceContext::Private::sequences () const [inline], [private]
Definition at line 2515 of file context.cpp.
{ return m_cachable.sequences.get(this); }
subHighlight() [1/2]
TemplateVariant NamespaceContext::Private::subHighlight () const [inline], [private]
Definition at line 2508 of file context.cpp.
{ return TemplateVariant(""); }
subHighlight() [2/2]
TemplateVariant NamespaceContext::Private::subHighlight () const [inline], [private]
Definition at line 2508 of file context.cpp.
{ return TemplateVariant(""); }
title() [1/2]
TemplateVariant NamespaceContext::Private::title () const [inline], [private]
Definition at line 2506 of file context.cpp.
{ return TemplateVariant(m_namespaceDef->title()); }
References m_namespaceDef, and NamespaceDef::title().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), createMemberList(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant NamespaceContext::Private::title () const [inline], [private]
Definition at line 2506 of file context.cpp.
{ return TemplateVariant(m_namespaceDef->title()); }
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
typedefs() [1/2]
TemplateVariant NamespaceContext::Private::typedefs () const [inline], [private]
Definition at line 2514 of file context.cpp.
{ return m_cachable.typedefs.get(this); }
References m_cachable, and NamespaceContext::Private::Cachable::typedefs.
typedefs() [2/2]
TemplateVariant NamespaceContext::Private::typedefs () const [inline], [private]
Definition at line 2514 of file context.cpp.
{ return m_cachable.typedefs.get(this); }
variables() [1/2]
TemplateVariant NamespaceContext::Private::variables () const [inline], [private]
Definition at line 2519 of file context.cpp.
{ return m_cachable.variables.get(this); }
References m_cachable, and NamespaceContext::Private::Cachable::variables.
variables() [2/2]
TemplateVariant NamespaceContext::Private::variables () const [inline], [private]
Definition at line 2519 of file context.cpp.
{ return m_cachable.variables.get(this); }
Member Data Documentation
m_cachable
Cachable NamespaceContext::Private::m_cachable [private]
Definition at line 2685 of file context.cpp.
Referenced by classes(), constantgroups(), detailedDictionaries(), detailedEnums(), detailedFunctions(), detailedSequences(), detailedTypedefs(), detailedVariables(), dictionaries(), enums(), functions(), inlineClasses(), memberGroups(), namespaces(), sequences(), typedefs(), and variables().
m_namespaceDef
const NamespaceDef * NamespaceContext::Private::m_namespaceDef [private]
Definition at line 2664 of file context.cpp.
Referenced by compoundType(), createClasses(), createConstantgroups(), createDetailedFunctions(), createFunctions(), createInlineClasses(), createMemberGroups(), createMemberList(), createNamespaces(), hasDetails(), and title().
s_inst
const PropertyMap< NamespaceContext::Private > NamespaceContext::Private::s_inst [static], [private]
Initial value:
{
  BASE_PROPERTIES,
  { "title", &Private::title },
  { "highlight", &Private::highlight },
  { "subhighlight", &Private::subHighlight },
  { "compoundType", &Private::compoundType },
  { "hasDetails", &Private::hasDetails },
  { "classes", &Private::classes },
  { "namespaces", &Private::namespaces },
  { "constantgroups", &Private::constantgroups },
  { "typedefs", &Private::typedefs },
  { "sequences", &Private::sequences },
  { "dictionaries", &Private::dictionaries },
  { "enums", &Private::enums },
  { "functions", &Private::functions },
  { "variables", &Private::variables },
  { "memberGroups", &Private::memberGroups },
  { "detailedTypedefs", &Private::detailedTypedefs },
  { "detailedSequences", &Private::detailedSequences },
  { "detailedDictionaries", &Private::detailedDictionaries },
  { "detailedEnums", &Private::detailedEnums },
  { "detailedFunctions", &Private::detailedFunctions },
  { "detailedVariables", &Private::detailedVariables },
  { "inlineClasses", &Private::inlineClasses }
}
Definition at line 2686 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp