ConfigObsolete Class Reference
#include <configimpl.h>
Public Member Functions
ConfigObsolete (const char *name, OptionType orgType)
void writeTemplate (TextStream &, bool, bool)
void compareDoxyfile (TextStream &, Config::CompareMode)
void writeXMLDoxyfile (TextStream &)
void substEnvVars ()
OptionType orgType () const
StringVector * valueListRef ()
QCString * valueStringRef ()
void markAsPresent ()
bool isPresent () const
ConfigObsolete (const char *name, OptionType orgType)
void writeTemplate (TextStream &, bool, bool)
void compareDoxyfile (TextStream &, Config::CompareMode)
void writeXMLDoxyfile (TextStream &)
void substEnvVars ()
OptionType orgType () const
StringVector * valueListRef ()
QCString * valueStringRef ()
void markAsPresent ()
bool isPresent () const
Private Attributes
OptionType m_orgType
StringVector m_listvalue
QCString m_valueString
bool m_present = false
Additional Inherited Members
Detailed Description
Section marker for obsolete options
Definition at line 280 of file configimpl.h.
Constructor & Destructor Documentation
ConfigObsolete() [1/2]
ConfigObsolete::ConfigObsolete (const char * name, OptionType orgType) [inline]
Definition at line 283 of file configimpl.h.
                                                        : ConfigOption(O_Obsolete), m_orgType(orgType)
    { m_name = name; }
References ConfigOption::m_name, and ConfigOption::name().
ConfigObsolete() [2/2]
ConfigObsolete::ConfigObsolete (const char * name, OptionType orgType) [inline]
Definition at line 283 of file configimpl.h.
                                                        : ConfigOption(O_Obsolete), m_orgType(orgType)
    { m_name = name; }
References ConfigOption::m_name, and ConfigOption::name().
Member Function Documentation
compareDoxyfile() [1/2]
void ConfigObsolete::compareDoxyfile (TextStream & , Config::CompareMode) [inline], [virtual]
Implements ConfigOption.
Definition at line 286 of file configimpl.h.
{}
compareDoxyfile() [2/2]
void ConfigObsolete::compareDoxyfile (TextStream & , Config::CompareMode) [inline], [virtual]
Implements ConfigOption.
Definition at line 286 of file configimpl.h.
{}
isPresent() [1/2]
bool ConfigObsolete::isPresent () const [inline]
Definition at line 293 of file configimpl.h.
{ return m_present; }
References m_present.
Referenced by Config::updateObsolete().
isPresent() [2/2]
bool ConfigObsolete::isPresent () const [inline]
Definition at line 293 of file configimpl.h.
{ return m_present; }
References m_present.
markAsPresent() [1/2]
void ConfigObsolete::markAsPresent () [inline]
Definition at line 292 of file configimpl.h.
{ m_present = true; }
References m_present.
markAsPresent() [2/2]
void ConfigObsolete::markAsPresent () [inline]
Definition at line 292 of file configimpl.h.
{ m_present = true; }
References m_present.
orgType() [1/2]
OptionType ConfigObsolete::orgType () const [inline]
Definition at line 289 of file configimpl.h.
{ return m_orgType; }
References m_orgType.
Referenced by Config::updateObsolete().
orgType() [2/2]
OptionType ConfigObsolete::orgType () const [inline]
Definition at line 289 of file configimpl.h.
{ return m_orgType; }
References m_orgType.
substEnvVars() [1/2]
void ConfigObsolete::substEnvVars () [inline], [virtual]
Implements ConfigOption.
Definition at line 288 of file configimpl.h.
{}
substEnvVars() [2/2]
void ConfigObsolete::substEnvVars () [inline], [virtual]
Implements ConfigOption.
Definition at line 288 of file configimpl.h.
{}
valueListRef() [1/2]
StringVector * ConfigObsolete::valueListRef () [inline]
Definition at line 290 of file configimpl.h.
{ return &m_listvalue; }
References m_listvalue.
valueListRef() [2/2]
StringVector * ConfigObsolete::valueListRef () [inline]
Definition at line 290 of file configimpl.h.
{ return &m_listvalue; }
References m_listvalue.
valueStringRef() [1/2]
QCString * ConfigObsolete::valueStringRef () [inline]
Definition at line 291 of file configimpl.h.
{ return &m_valueString; }
References m_valueString.
Referenced by updateAttribute(), and Config::updateObsolete().
valueStringRef() [2/2]
QCString * ConfigObsolete::valueStringRef () [inline]
Definition at line 291 of file configimpl.h.
{ return &m_valueString; }
References m_valueString.
writeTemplate() [1/2]
void ConfigObsolete::writeTemplate (TextStream & , bool , bool) [virtual]
Implements ConfigOption.
Definition at line 606 of file configimpl.l.
{}
writeTemplate() [2/2]
void ConfigObsolete::writeTemplate (TextStream & , bool , bool) [virtual]
Implements ConfigOption.
writeXMLDoxyfile() [1/2]
void ConfigObsolete::writeXMLDoxyfile (TextStream &) [inline], [virtual]
Implements ConfigOption.
Definition at line 287 of file configimpl.h.
{}
writeXMLDoxyfile() [2/2]
void ConfigObsolete::writeXMLDoxyfile (TextStream &) [inline], [virtual]
Implements ConfigOption.
Definition at line 287 of file configimpl.h.
{}
Member Data Documentation
m_listvalue
StringVector ConfigObsolete::m_listvalue [private]
Definition at line 296 of file configimpl.h.
Referenced by valueListRef().
m_orgType
OptionType ConfigObsolete::m_orgType [private]
Definition at line 295 of file configimpl.h.
Referenced by orgType().
m_present
bool ConfigObsolete::m_present = false [private]
Definition at line 298 of file configimpl.h.
Referenced by isPresent(), and markAsPresent().
m_valueString
QCString ConfigObsolete::m_valueString [private]
Definition at line 297 of file configimpl.h.
Referenced by valueStringRef().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/configimpl.h
doxygen/src/configimpl.h
doxygen/build/doxygen/src/configimpl.l
doxygen/src/configimpl.l