NestingContext::Private Class Reference
Public Member Functions
Private (const NestingNodeContext *parent, ContextTreeType type, int level)
void addNamespace (const NamespaceDef *nd, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet &visitedClasses)
void addNamespaces (const NamespaceLinkedMap &nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet &visitedClasses)
void addNamespaces (const NamespaceLinkedRefMap &nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet &visitedClasses)
void addClass (const ClassDef *cd, bool rootOnly, ClassDefSet &visitedClasses)
void addConcept (const ConceptDef *cd, bool rootOnly, ClassDefSet &visitedClasses)
void addClasses (const ClassLinkedRefMap &clLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addClasses (const ClassLinkedMap &clLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addConcepts (const ConceptLinkedRefMap &cpLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addConcepts (const ConceptLinkedMap &cpLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addDirs (const DirLinkedMap &dirLinkedMap, ClassDefSet &visitedClasses)
void addDirs (const DirList &dirList, ClassDefSet &visitedClasses)
void addFiles (const FileNameLinkedMap &fnList, ClassDefSet &visitedClasses)
void addFiles (const FileList &fList, ClassDefSet &visitedClasses)
void addPage (const PageDef *pd, bool rootOnly, ClassDefSet &visitedClasses)
void addPages (const PageLinkedMap &pages, bool rootOnly, ClassDefSet &visitedClasses)
void addPages (const PageLinkedRefMap &pages, bool rootOnly, ClassDefSet &visitedClasses)
void addModules (const GroupLinkedMap &groups, ClassDefSet &visitedClasses)
void addModules (const GroupList &groups, ClassDefSet &visitedClasses)
void addDerivedClasses (const BaseClassList &bcl, bool hideSuper, ClassDefSet &visitedClasses)
void addClassHierarchy (const ClassLinkedMap &classLinkedMap, ClassDefSet &visitedClasses)
void addMembers (const MemberVector &mv, ClassDefSet &visitedClasses)
Private (const NestingNodeContext *parent, ContextTreeType type, int level)
void addNamespace (const NamespaceDef *nd, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet &visitedClasses)
void addNamespaces (const NamespaceLinkedMap &nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet &visitedClasses)
void addNamespaces (const NamespaceLinkedRefMap &nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet &visitedClasses)
void addClass (const ClassDef *cd, bool rootOnly, ClassDefSet &visitedClasses)
void addConcept (const ConceptDef *cd, bool rootOnly, ClassDefSet &visitedClasses)
void addClasses (const ClassLinkedRefMap &clLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addClasses (const ClassLinkedMap &clLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addConcepts (const ConceptLinkedRefMap &cpLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addConcepts (const ConceptLinkedMap &cpLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addDirs (const DirLinkedMap &dirLinkedMap, ClassDefSet &visitedClasses)
void addDirs (const DirList &dirList, ClassDefSet &visitedClasses)
void addFiles (const FileNameLinkedMap &fnList, ClassDefSet &visitedClasses)
void addFiles (const FileList &fList, ClassDefSet &visitedClasses)
void addPage (const PageDef *pd, bool rootOnly, ClassDefSet &visitedClasses)
void addPages (const PageLinkedMap &pages, bool rootOnly, ClassDefSet &visitedClasses)
void addPages (const PageLinkedRefMap &pages, bool rootOnly, ClassDefSet &visitedClasses)
void addModules (const GroupLinkedMap &groups, ClassDefSet &visitedClasses)
void addModules (const GroupList &groups, ClassDefSet &visitedClasses)
void addDerivedClasses (const BaseClassList &bcl, bool hideSuper, ClassDefSet &visitedClasses)
void addClassHierarchy (const ClassLinkedMap &classLinkedMap, ClassDefSet &visitedClasses)
void addMembers (const MemberVector &mv, ClassDefSet &visitedClasses)
Private Attributes
const NestingNodeContext * m_parent
ContextTreeType m_type
int m_level
int m_index = 0
Additional Inherited Members
Detailed Description
Definition at line 5698 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
NestingContext::Private::Private (const NestingNodeContext * parent, ContextTreeType type, int level) [inline]
Definition at line 5701 of file context.cpp.
      : m_parent(parent), m_type(type), m_level(level) {}
Private() [2/2]
NestingContext::Private::Private (const NestingNodeContext * parent, ContextTreeType type, int level) [inline]
Definition at line 5701 of file context.cpp.
      : m_parent(parent), m_type(type), m_level(level) {}
Member Function Documentation
addClass() [1/2]
void NestingContext::Private::addClass (const ClassDef * cd, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5737 of file context.cpp.
    {
      if (cd->getLanguage()==SrcLangExt_VHDL)
      {
        if (VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKAGECLASS ||
            VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKBODYCLASS
           )// no architecture
        {
          return;
        }
      }
      if (!rootOnly ||
          cd->getOuterScope()==0 ||
          cd->getOuterScope()==Doxygen::globalScope
         )
      {
        if (classVisibleInIndex(cd) && cd->templateMaster()==0)
        {
          append(NestingNodeContext::alloc(m_parent,m_type,cd,m_index,m_level,
                                           TRUE,FALSE,FALSE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), GenericNodeListContext::append(), classVisibleInIndex(), VhdlDocGen::convert(), FALSE, Definition::getLanguage(), Definition::getOuterScope(), Doxygen::globalScope, m_index, m_level, m_parent, m_type, VhdlDocGen::PACKAGECLASS, VhdlDocGen::PACKBODYCLASS, ClassDef::protection(), SrcLangExt_VHDL, ClassDef::templateMaster(), and TRUE.
Referenced by addClasses().
addClass() [2/2]
void NestingContext::Private::addClass (const ClassDef * cd, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5737 of file context.cpp.
    {
      if (cd->getLanguage()==SrcLangExt_VHDL)
      {
        if (VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKAGECLASS ||
            VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKBODYCLASS
           )// no architecture
        {
          return;
        }
      }
      if (!rootOnly ||
          cd->getOuterScope()==0 ||
          cd->getOuterScope()==Doxygen::globalScope
         )
      {
        if (classVisibleInIndex(cd) && cd->templateMaster()==0)
        {
          append(NestingNodeContext::alloc(m_parent,m_type,cd,m_index,m_level,
                                           TRUE,FALSE,FALSE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), classVisibleInIndex(), VhdlDocGen::convert(), FALSE, Definition::getLanguage(), Definition::getOuterScope(), Doxygen::globalScope, VhdlDocGen::PACKAGECLASS, VhdlDocGen::PACKBODYCLASS, ClassDef::protection(), SrcLangExt_VHDL, ClassDef::templateMaster(), and TRUE.
addClasses() [1/4]
void NestingContext::Private::addClasses (const ClassLinkedMap & clLinkedMap, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5780 of file context.cpp.
    {
      for (const auto &cd : clLinkedMap)
      {
        addClass(cd.get(),rootOnly,visitedClasses);
      }
    }
References addClass().
addClasses() [2/4]
void NestingContext::Private::addClasses (const ClassLinkedMap & clLinkedMap, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5780 of file context.cpp.
    {
      for (const auto &cd : clLinkedMap)
      {
        addClass(cd.get(),rootOnly,visitedClasses);
      }
    }
addClasses() [3/4]
void NestingContext::Private::addClasses (const ClassLinkedRefMap & clLinkedMap, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5773 of file context.cpp.
    {
      for (const auto &cd : clLinkedMap)
      {
        addClass(cd,rootOnly,visitedClasses);
      }
    }
References addClass().
Referenced by addNamespace(), and addNamespaces().
addClasses() [4/4]
void NestingContext::Private::addClasses (const ClassLinkedRefMap & clLinkedMap, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5773 of file context.cpp.
    {
      for (const auto &cd : clLinkedMap)
      {
        addClass(cd,rootOnly,visitedClasses);
      }
    }
addClassHierarchy() [1/2]
void NestingContext::Private::addClassHierarchy (const ClassLinkedMap & classLinkedMap, ClassDefSet & visitedClasses) [inline]
Definition at line 5926 of file context.cpp.
    {
      for (const auto &cd : classLinkedMap)
      {
        bool b;
        if (cd->getLanguage()==SrcLangExt_VHDL)
        {
          if (VhdlDocGen::convert(cd->protection())!=VhdlDocGen::ENTITYCLASS)
          {
            continue;
          }
          b=!hasVisibleRoot(cd->subClasses());
        }
        else
        {
          b=!hasVisibleRoot(cd->baseClasses());
        }
        if (b)
        {
          if (cd->isVisibleInHierarchy()) // should it be visible
          {
            // new root level class
            append(NestingNodeContext::alloc(m_parent,m_type,cd.get(),m_index,m_level,
                                             TRUE,FALSE,TRUE,FALSE,visitedClasses));
            m_index++;
          }
        }
      }
    }
References NestingNodeContext::alloc(), GenericNodeListContext::append(), b, VhdlDocGen::convert(), VhdlDocGen::ENTITYCLASS, FALSE, hasVisibleRoot(), m_index, m_level, m_parent, m_type, SrcLangExt_VHDL, and TRUE.
addClassHierarchy() [2/2]
void NestingContext::Private::addClassHierarchy (const ClassLinkedMap & classLinkedMap, ClassDefSet & visitedClasses) [inline]
Definition at line 5926 of file context.cpp.
    {
      for (const auto &cd : classLinkedMap)
      {
        bool b;
        if (cd->getLanguage()==SrcLangExt_VHDL)
        {
          if (VhdlDocGen::convert(cd->protection())!=VhdlDocGen::ENTITYCLASS)
          {
            continue;
          }
          b=!hasVisibleRoot(cd->subClasses());
        }
        else
        {
          b=!hasVisibleRoot(cd->baseClasses());
        }
        if (b)
        {
          if (cd->isVisibleInHierarchy()) // should it be visible
          {
            // new root level class
            append(NestingNodeContext::alloc(m_parent,m_type,cd.get(),m_index,m_level,
                                             TRUE,FALSE,TRUE,FALSE,visitedClasses));
            m_index++;
          }
        }
      }
    }
References NestingNodeContext::alloc(), b, VhdlDocGen::convert(), VhdlDocGen::ENTITYCLASS, FALSE, hasVisibleRoot(), SrcLangExt_VHDL, and TRUE.
addConcept() [1/2]
void NestingContext::Private::addConcept (const ConceptDef * cd, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5761 of file context.cpp.
    {
      if (!rootOnly || cd->getOuterScope()==0 || cd->getOuterScope()==Doxygen::globalScope)
      {
        if (cd->isLinkable())
        {
          append(NestingNodeContext::alloc(m_parent,m_type,cd,m_index,m_level,
                                           FALSE,TRUE,FALSE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), GenericNodeListContext::append(), FALSE, Definition::getOuterScope(), Doxygen::globalScope, ConceptDef::isLinkable(), m_index, m_level, m_parent, m_type, and TRUE.
Referenced by addConcepts().
addConcept() [2/2]
void NestingContext::Private::addConcept (const ConceptDef * cd, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5761 of file context.cpp.
    {
      if (!rootOnly || cd->getOuterScope()==0 || cd->getOuterScope()==Doxygen::globalScope)
      {
        if (cd->isLinkable())
        {
          append(NestingNodeContext::alloc(m_parent,m_type,cd,m_index,m_level,
                                           FALSE,TRUE,FALSE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), FALSE, Definition::getOuterScope(), Doxygen::globalScope, ConceptDef::isLinkable(), and TRUE.
addConcepts() [1/4]
void NestingContext::Private::addConcepts (const ConceptLinkedMap & cpLinkedMap, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5794 of file context.cpp.
    {
      for (const auto &cd : cpLinkedMap)
      {
        addConcept(cd.get(),rootOnly,visitedClasses);
      }
    }
References addConcept().
addConcepts() [2/4]
void NestingContext::Private::addConcepts (const ConceptLinkedMap & cpLinkedMap, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5794 of file context.cpp.
    {
      for (const auto &cd : cpLinkedMap)
      {
        addConcept(cd.get(),rootOnly,visitedClasses);
      }
    }
addConcepts() [3/4]
void NestingContext::Private::addConcepts (const ConceptLinkedRefMap & cpLinkedMap, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5787 of file context.cpp.
    {
      for (const auto &cd : cpLinkedMap)
      {
        addConcept(cd,rootOnly,visitedClasses);
      }
    }
References addConcept().
Referenced by addNamespace(), and addNamespaces().
addConcepts() [4/4]
void NestingContext::Private::addConcepts (const ConceptLinkedRefMap & cpLinkedMap, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5787 of file context.cpp.
    {
      for (const auto &cd : cpLinkedMap)
      {
        addConcept(cd,rootOnly,visitedClasses);
      }
    }
addDerivedClasses() [1/2]
void NestingContext::Private::addDerivedClasses (const BaseClassList & bcl, bool hideSuper, ClassDefSet & visitedClasses) [inline]
Definition at line 5898 of file context.cpp.
    {
      for (const auto &bcd : bcl)
      {
        const ClassDef *cd=bcd.classDef;
        if (cd->getLanguage()==SrcLangExt_VHDL && VhdlDocGen::convert(cd->protection())!=VhdlDocGen::ENTITYCLASS)
        {
          continue;
        }
        bool b;
        if (cd->getLanguage()==SrcLangExt_VHDL)
        {
          b=hasVisibleRoot(cd->subClasses());
        }
        else
        {
          b=hasVisibleRoot(cd->baseClasses());
        }
        if (cd->isVisibleInHierarchy() && b)
        {
          append(NestingNodeContext::alloc(m_parent,m_type,cd,m_index,m_level,
                                           TRUE,FALSE,TRUE,hideSuper,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), GenericNodeListContext::append(), b, ClassDef::baseClasses(), VhdlDocGen::convert(), VhdlDocGen::ENTITYCLASS, FALSE, Definition::getLanguage(), hasVisibleRoot(), ClassDef::isVisibleInHierarchy(), m_index, m_level, m_parent, m_type, ClassDef::protection(), SrcLangExt_VHDL, ClassDef::subClasses(), and TRUE.
addDerivedClasses() [2/2]
void NestingContext::Private::addDerivedClasses (const BaseClassList & bcl, bool hideSuper, ClassDefSet & visitedClasses) [inline]
Definition at line 5898 of file context.cpp.
    {
      for (const auto &bcd : bcl)
      {
        const ClassDef *cd=bcd.classDef;
        if (cd->getLanguage()==SrcLangExt_VHDL && VhdlDocGen::convert(cd->protection())!=VhdlDocGen::ENTITYCLASS)
        {
          continue;
        }
        bool b;
        if (cd->getLanguage()==SrcLangExt_VHDL)
        {
          b=hasVisibleRoot(cd->subClasses());
        }
        else
        {
          b=hasVisibleRoot(cd->baseClasses());
        }
        if (cd->isVisibleInHierarchy() && b)
        {
          append(NestingNodeContext::alloc(m_parent,m_type,cd,m_index,m_level,
                                           TRUE,FALSE,TRUE,hideSuper,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), b, ClassDef::baseClasses(), VhdlDocGen::convert(), VhdlDocGen::ENTITYCLASS, FALSE, Definition::getLanguage(), hasVisibleRoot(), ClassDef::isVisibleInHierarchy(), ClassDef::protection(), SrcLangExt_VHDL, ClassDef::subClasses(), and TRUE.
addDirs() [1/4]
void NestingContext::Private::addDirs (const DirLinkedMap & dirLinkedMap, ClassDefSet & visitedClasses) [inline]
Definition at line 5801 of file context.cpp.
    {
      for (const auto &dd : dirLinkedMap)
      {
        if (dd->getOuterScope()==Doxygen::globalScope)
        {
          append(NestingNodeContext::alloc(m_parent,m_type,dd.get(),m_index,m_level,
                                           FALSE,FALSE,FALSE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), GenericNodeListContext::append(), FALSE, Doxygen::globalScope, m_index, m_level, m_parent, and m_type.
addDirs() [2/4]
void NestingContext::Private::addDirs (const DirLinkedMap & dirLinkedMap, ClassDefSet & visitedClasses) [inline]
Definition at line 5801 of file context.cpp.
    {
      for (const auto &dd : dirLinkedMap)
      {
        if (dd->getOuterScope()==Doxygen::globalScope)
        {
          append(NestingNodeContext::alloc(m_parent,m_type,dd.get(),m_index,m_level,
                                           FALSE,FALSE,FALSE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), FALSE, and Doxygen::globalScope.
addDirs() [3/4]
void NestingContext::Private::addDirs (const DirList & dirList, ClassDefSet & visitedClasses) [inline]
Definition at line 5813 of file context.cpp.
    {
      for(const auto dd : dirList)
      {
        append(NestingNodeContext::alloc(m_parent,m_type,dd,m_index,m_level,
                                         FALSE,FALSE,FALSE,FALSE,visitedClasses));
        m_index++;
      }
    }
References NestingNodeContext::alloc(), GenericNodeListContext::append(), FALSE, m_index, m_level, m_parent, and m_type.
addDirs() [4/4]
void NestingContext::Private::addDirs (const DirList & dirList, ClassDefSet & visitedClasses) [inline]
Definition at line 5813 of file context.cpp.
    {
      for(const auto dd : dirList)
      {
        append(NestingNodeContext::alloc(m_parent,m_type,dd,m_index,m_level,
                                         FALSE,FALSE,FALSE,FALSE,visitedClasses));
        m_index++;
      }
    }
References NestingNodeContext::alloc(), and FALSE.
addFiles() [1/4]
void NestingContext::Private::addFiles (const FileList & fList, ClassDefSet & visitedClasses) [inline]
Definition at line 5837 of file context.cpp.
    {
      for (const auto &fd : fList)
      {
        append(NestingNodeContext::alloc(m_parent,m_type,fd,m_index,m_level,
                                         FALSE,FALSE,FALSE,FALSE,visitedClasses));
        m_index++;
      }
    }
References NestingNodeContext::alloc(), GenericNodeListContext::append(), FALSE, fList, m_index, m_level, m_parent, and m_type.
addFiles() [2/4]
void NestingContext::Private::addFiles (const FileList & fList, ClassDefSet & visitedClasses) [inline]
Definition at line 5837 of file context.cpp.
    {
      for (const auto &fd : fList)
      {
        append(NestingNodeContext::alloc(m_parent,m_type,fd,m_index,m_level,
                                         FALSE,FALSE,FALSE,FALSE,visitedClasses));
        m_index++;
      }
    }
References NestingNodeContext::alloc(), FALSE, and fList.
addFiles() [3/4]
void NestingContext::Private::addFiles (const FileNameLinkedMap & fnList, ClassDefSet & visitedClasses) [inline]
Definition at line 5822 of file context.cpp.
    {
      for (const FileNameLinkedMap::Ptr &fn : fnList)
      {
        for (const auto &fd : *fn)
        {
          if (fd->getDirDef()==0) // top level file
          {
            append(NestingNodeContext::alloc(m_parent,m_type,fd.get(),m_index,m_level,
                                             FALSE,FALSE,FALSE,FALSE,visitedClasses));
            m_index++;
          }
        }
      }
    }
References NestingNodeContext::alloc(), GenericNodeListContext::append(), FALSE, m_index, m_level, m_parent, and m_type.
addFiles() [4/4]
void NestingContext::Private::addFiles (const FileNameLinkedMap & fnList, ClassDefSet & visitedClasses) [inline]
Definition at line 5822 of file context.cpp.
    {
      for (const FileNameLinkedMap::Ptr &fn : fnList)
      {
        for (const auto &fd : *fn)
        {
          if (fd->getDirDef()==0) // top level file
          {
            append(NestingNodeContext::alloc(m_parent,m_type,fd.get(),m_index,m_level,
                                             FALSE,FALSE,FALSE,FALSE,visitedClasses));
            m_index++;
          }
        }
      }
    }
References NestingNodeContext::alloc(), and FALSE.
addMembers() [1/2]
void NestingContext::Private::addMembers (const MemberVector & mv, ClassDefSet & visitedClasses) [inline]
Definition at line 5955 of file context.cpp.
    {
      for (const auto &md : mv)
      {
        if (md->visibleInIndex())
        {
          append(NestingNodeContext::alloc(m_parent,m_type,md,m_index,m_level+1,
                                           TRUE,FALSE,TRUE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), GenericNodeListContext::append(), FALSE, m_index, m_level, m_parent, m_type, and TRUE.
addMembers() [2/2]
void NestingContext::Private::addMembers (const MemberVector & mv, ClassDefSet & visitedClasses) [inline]
Definition at line 5955 of file context.cpp.
    {
      for (const auto &md : mv)
      {
        if (md->visibleInIndex())
        {
          append(NestingNodeContext::alloc(m_parent,m_type,md,m_index,m_level+1,
                                           TRUE,FALSE,TRUE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), FALSE, and TRUE.
addModules() [1/4]
void NestingContext::Private::addModules (const GroupLinkedMap & groups, ClassDefSet & visitedClasses) [inline]
Definition at line 5871 of file context.cpp.
    {
      for (const auto &gd : groups)
      {
        bool externalGroups = Config_getBool(EXTERNAL_GROUPS);
        if (!gd->isASubGroup() && gd->isVisible() &&
            (!gd->isReference() || externalGroups)
           )
        {
          append(NestingNodeContext::alloc(m_parent,m_type,gd.get(),m_index,m_level,
                                           FALSE,FALSE,FALSE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), GenericNodeListContext::append(), Config_getBool, FALSE, m_index, m_level, m_parent, and m_type.
addModules() [2/4]
void NestingContext::Private::addModules (const GroupLinkedMap & groups, ClassDefSet & visitedClasses) [inline]
Definition at line 5871 of file context.cpp.
    {
      for (const auto &gd : groups)
      {
        bool externalGroups = Config_getBool(EXTERNAL_GROUPS);
        if (!gd->isASubGroup() && gd->isVisible() &&
            (!gd->isReference() || externalGroups)
           )
        {
          append(NestingNodeContext::alloc(m_parent,m_type,gd.get(),m_index,m_level,
                                           FALSE,FALSE,FALSE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), Config_getBool, and FALSE.
addModules() [3/4]
void NestingContext::Private::addModules (const GroupList & groups, ClassDefSet & visitedClasses) [inline]
Definition at line 5886 of file context.cpp.
    {
      for (const auto &gd : groups)
      {
        if (gd->isVisible())
        {
          append(NestingNodeContext::alloc(m_parent,m_type,gd,m_index,m_level,
                                           FALSE,FALSE,FALSE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), GenericNodeListContext::append(), FALSE, m_index, m_level, m_parent, and m_type.
addModules() [4/4]
void NestingContext::Private::addModules (const GroupList & groups, ClassDefSet & visitedClasses) [inline]
Definition at line 5886 of file context.cpp.
    {
      for (const auto &gd : groups)
      {
        if (gd->isVisible())
        {
          append(NestingNodeContext::alloc(m_parent,m_type,gd,m_index,m_level,
                                           FALSE,FALSE,FALSE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), and FALSE.
addNamespace() [1/2]
void NestingContext::Private::addNamespace (const NamespaceDef * nd, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet & visitedClasses) [inline]
Definition at line 5704 of file context.cpp.
    {
      if (!nd->isAnonymous() &&
          (!rootOnly || nd->getOuterScope()==Doxygen::globalScope))
      {
        bool hasChildren = namespaceHasNestedNamespace(nd) ||
                           (addClasses && namespaceHasNestedClass(nd,false,ClassDef::Class)) ||
                           (addConcepts && namespaceHasNestedConcept(nd)) ||
                           (m_type==ContextTreeType::Namespace && countVisibleMembers(nd));
        bool isLinkable = nd->isLinkableInProject();
        if (isLinkable && hasChildren)
        {
          append(NestingNodeContext::alloc(m_parent,m_type,nd,m_index,m_level,
                                           addClasses,addConcepts,FALSE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References addClasses(), addConcepts(), NestingNodeContext::alloc(), GenericNodeListContext::append(), ClassDef::Class, countVisibleMembers(), FALSE, Definition::getOuterScope(), Doxygen::globalScope, Definition::isAnonymous(), NamespaceDef::isLinkableInProject(), m_index, m_level, m_parent, m_type, Namespace, namespaceHasNestedClass(), namespaceHasNestedConcept(), and namespaceHasNestedNamespace().
Referenced by addNamespaces().
addNamespace() [2/2]
void NestingContext::Private::addNamespace (const NamespaceDef * nd, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet & visitedClasses) [inline]
Definition at line 5704 of file context.cpp.
    {
      if (!nd->isAnonymous() &&
          (!rootOnly || nd->getOuterScope()==Doxygen::globalScope))
      {
        bool hasChildren = namespaceHasNestedNamespace(nd) ||
                           (addClasses && namespaceHasNestedClass(nd,false,ClassDef::Class)) ||
                           (addConcepts && namespaceHasNestedConcept(nd)) ||
                           (m_type==ContextTreeType::Namespace && countVisibleMembers(nd));
        bool isLinkable = nd->isLinkableInProject();
        if (isLinkable && hasChildren)
        {
          append(NestingNodeContext::alloc(m_parent,m_type,nd,m_index,m_level,
                                           addClasses,addConcepts,FALSE,FALSE,visitedClasses));
          m_index++;
        }
      }
    }
References NestingNodeContext::alloc(), ClassDef::Class, countVisibleMembers(), FALSE, Definition::getOuterScope(), Doxygen::globalScope, Definition::isAnonymous(), NamespaceDef::isLinkableInProject(), Namespace, namespaceHasNestedClass(), namespaceHasNestedConcept(), and namespaceHasNestedNamespace().
addNamespaces() [1/4]
void NestingContext::Private::addNamespaces (const NamespaceLinkedMap & nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet & visitedClasses) [inline]
Definition at line 5723 of file context.cpp.
    {
      for (const auto &nd : nsLinkedMap)
      {
        addNamespace(nd.get(),rootOnly,addClasses,addConcepts,visitedClasses);
      }
    }
References addClasses(), addConcepts(), and addNamespace().
addNamespaces() [2/4]
void NestingContext::Private::addNamespaces (const NamespaceLinkedMap & nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet & visitedClasses) [inline]
Definition at line 5723 of file context.cpp.
    {
      for (const auto &nd : nsLinkedMap)
      {
        addNamespace(nd.get(),rootOnly,addClasses,addConcepts,visitedClasses);
      }
    }
addNamespaces() [3/4]
void NestingContext::Private::addNamespaces (const NamespaceLinkedRefMap & nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet & visitedClasses) [inline]
Definition at line 5730 of file context.cpp.
    {
      for (const auto &nd : nsLinkedMap)
      {
        addNamespace(nd,rootOnly,addClasses,addConcepts,visitedClasses);
      }
    }
References addClasses(), addConcepts(), and addNamespace().
addNamespaces() [4/4]
void NestingContext::Private::addNamespaces (const NamespaceLinkedRefMap & nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet & visitedClasses) [inline]
Definition at line 5730 of file context.cpp.
    {
      for (const auto &nd : nsLinkedMap)
      {
        addNamespace(nd,rootOnly,addClasses,addConcepts,visitedClasses);
      }
    }
addPage() [1/2]
void NestingContext::Private::addPage (const PageDef * pd, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5846 of file context.cpp.
    {
      if (!rootOnly ||
          pd->getOuterScope()==0 ||
          pd->getOuterScope()->definitionType()!=Definition::TypePage)
      {
        append(NestingNodeContext::alloc(m_parent,m_type,pd,m_index,m_level,
                                          FALSE,FALSE,FALSE,FALSE,visitedClasses));
        m_index++;
      }
    }
References NestingNodeContext::alloc(), GenericNodeListContext::append(), Definition::definitionType(), FALSE, Definition::getOuterScope(), m_index, m_level, m_parent, m_type, and Definition::TypePage.
Referenced by addPages().
addPage() [2/2]
void NestingContext::Private::addPage (const PageDef * pd, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5846 of file context.cpp.
    {
      if (!rootOnly ||
          pd->getOuterScope()==0 ||
          pd->getOuterScope()->definitionType()!=Definition::TypePage)
      {
        append(NestingNodeContext::alloc(m_parent,m_type,pd,m_index,m_level,
                                          FALSE,FALSE,FALSE,FALSE,visitedClasses));
        m_index++;
      }
    }
References NestingNodeContext::alloc(), Definition::definitionType(), FALSE, Definition::getOuterScope(), and Definition::TypePage.
addPages() [1/4]
void NestingContext::Private::addPages (const PageLinkedMap & pages, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5857 of file context.cpp.
    {
      for (const auto &pd : pages)
      {
        addPage(pd.get(),rootOnly,visitedClasses);
      }
    }
References addPage().
addPages() [2/4]
void NestingContext::Private::addPages (const PageLinkedMap & pages, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5857 of file context.cpp.
    {
      for (const auto &pd : pages)
      {
        addPage(pd.get(),rootOnly,visitedClasses);
      }
    }
addPages() [3/4]
void NestingContext::Private::addPages (const PageLinkedRefMap & pages, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5864 of file context.cpp.
    {
      for (const auto &pd : pages)
      {
        addPage(pd,rootOnly,visitedClasses);
      }
    }
References addPage().
addPages() [4/4]
void NestingContext::Private::addPages (const PageLinkedRefMap & pages, bool rootOnly, ClassDefSet & visitedClasses) [inline]
Definition at line 5864 of file context.cpp.
    {
      for (const auto &pd : pages)
      {
        addPage(pd,rootOnly,visitedClasses);
      }
    }
Member Data Documentation
m_index
int NestingContext::Private::m_index = 0 [private]
Definition at line 5972 of file context.cpp.
Referenced by addClass(), addClassHierarchy(), addConcept(), addDerivedClasses(), addDirs(), addFiles(), addMembers(), addModules(), addNamespace(), and addPage().
m_level
int NestingContext::Private::m_level [private]
Definition at line 5971 of file context.cpp.
Referenced by addClass(), addClassHierarchy(), addConcept(), addDerivedClasses(), addDirs(), addFiles(), addMembers(), addModules(), addNamespace(), and addPage().
m_parent
const NestingNodeContext * NestingContext::Private::m_parent [private]
Definition at line 5969 of file context.cpp.
Referenced by addClass(), addClassHierarchy(), addConcept(), addDerivedClasses(), addDirs(), addFiles(), addMembers(), addModules(), addNamespace(), and addPage().
m_type
ContextTreeType NestingContext::Private::m_type [private]
Definition at line 5970 of file context.cpp.
Referenced by addClass(), addClassHierarchy(), addConcept(), addDerivedClasses(), addDirs(), addFiles(), addMembers(), addModules(), addNamespace(), and addPage().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp