DocHtmlRow Class Reference
#include <docnode.h>
Public Member Functions
DocHtmlRow (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs)
size_t numCells () const
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
int parseXml (DocNodeVariant *, bool header)
bool isHeading () const
void setVisibleCells (uint n)
uint visibleCells () const
uint rowIndex () const
DocHtmlRow (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs)
size_t numCells () const
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
int parseXml (DocNodeVariant *, bool header)
bool isHeading () const
void setVisibleCells (uint n)
uint visibleCells () const
uint rowIndex () const
Private Member Functions
void setRowIndex (uint idx)
void setRowIndex (uint idx)
Private Attributes
HtmlAttribList m_attribs
uint m_visibleCells = 0
uint m_rowIdx = static_cast<uint>(-1)
Friends
class DocHtmlTable
Additional Inherited Members
Detailed Description
Node representing a HTML table row
Definition at line 1198 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlRow() [1/2]
DocHtmlRow::DocHtmlRow (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs) [inline]
Definition at line 1202 of file docnode.h.
      : DocCompoundNode(parser,parent), m_attribs(attribs) {}
DocHtmlRow() [2/2]
DocHtmlRow::DocHtmlRow (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs) [inline]
Definition at line 1202 of file docnode.h.
      : DocCompoundNode(parser,parent), m_attribs(attribs) {}
Member Function Documentation
attribs() [1/2]
const HtmlAttribList & DocHtmlRow::attribs () const [inline]
Definition at line 1205 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by DocbookDocVisitor::operator()(), and HtmlDocVisitor::operator()().
attribs() [2/2]
const HtmlAttribList & DocHtmlRow::attribs () const [inline]
Definition at line 1205 of file docnode.h.
{ return m_attribs; }
References m_attribs.
isHeading() [1/2]
bool DocHtmlRow::isHeading () const
Definition at line 1781 of file docnode.cpp.
{ // a row is a table heading if all cells are marked as such
  bool heading=TRUE;
  for (const auto &n : children())
  {
    const DocHtmlCell *cell = std::get_if<DocHtmlCell>(&n);
    if (cell && !cell->isHeading())
    {
      heading = FALSE;
      break;
    }
  }
  return !children().empty() && heading;
}
References DocCompoundNode::children(), GrowVector< T >::empty(), FALSE, DocHtmlCell::isHeading(), n, and TRUE.
Referenced by DocbookDocVisitor::operator()(), LatexDocVisitor::operator()(), parse(), and parseXml().
isHeading() [2/2]
bool DocHtmlRow::isHeading () const
numCells() [1/2]
size_t DocHtmlRow::numCells () const [inline]
Definition at line 1204 of file docnode.h.
{ return children().size(); }
References DocCompoundNode::children(), and GrowVector< T >::size().
numCells() [2/2]
size_t DocHtmlRow::numCells () const [inline]
Definition at line 1204 of file docnode.h.
{ return children().size(); }
References DocCompoundNode::children(), and GrowVector< T >::size().
parse() [1/2]
int DocHtmlRow::parse (DocNodeVariant * thisVariant)
Definition at line 1796 of file docnode.cpp.
{
  int retval=RetVal_OK;
  auto ns = AutoNodeStack(parser(),thisVariant);
  DBG(("DocHtmlRow::parse() start\n"));
  bool isHeading=FALSE;
  bool isFirst=TRUE;
  DocHtmlCell *cell=0;
  // get next token
  int tok=parser()->tokenizer.lex();
  // skip whitespace
  while (tok==TK_WHITESPACE || tok==TK_NEWPARA) tok=parser()->tokenizer.lex();
  // should find a html tag now
  if (tok==TK_HTMLTAG)
  {
    int tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
    if (tagId==HTML_TD && !parser()->context.token->endTag) // found <td> tag
    {
    }
    else if (tagId==HTML_TH && !parser()->context.token->endTag) // found <th> tag
    {
      isHeading=TRUE;
    }
    else // found some other tag
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <td> or <th> tag but "
          "found <%s> instead!",qPrint(parser()->context.token->name));
      parser()->tokenizer.pushBackHtmlTag(parser()->context.token->name);
      goto endrow;
    }
  }
  else if (tok==0) // premature end of comment
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected end of comment while looking"
        " for a html description title");
    goto endrow;
  }
  else // token other than html token
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <td> or <th> tag but found %s token instead!",
        DocTokenizer::tokToString(tok));
    goto endrow;
  }
  // parse one or more cells
  do
  {
    auto vDocHtmlCell = children().append<DocHtmlCell>(parser(),thisVariant,
                                                       parser()->context.token->attribs,
                                                       isHeading);
    cell = children().get_last<DocHtmlCell>();
    cell->markFirst(isFirst);
    isFirst=FALSE;
    retval=cell->parse(vDocHtmlCell);
    isHeading = retval==RetVal_TableHCell;
  }
  while (retval==RetVal_TableCell || retval==RetVal_TableHCell);
  cell->markLast(TRUE);
endrow:
  DBG(("DocHtmlRow::parse() end\n"));
  return retval;
}
References DocNodeList::append(), TokenInfo::attribs, DocCompoundNode::children(), DocParser::context, DBG, FALSE, DocNodeList::get_last(), HTML_TD, HTML_TH, Mappers::htmlTagMapper, isHeading(), DocTokenizer::lex(), Mapper::map(), DocHtmlCell::markFirst(), DocHtmlCell::markLast(), DocHtmlCell::parse(), DocNode::parser(), DocTokenizer::pushBackHtmlTag(), qPrint(), RetVal_OK, RetVal_TableCell, RetVal_TableHCell, TK_HTMLTAG, TK_NEWPARA, TK_WHITESPACE, DocParserContext::token, DocParser::tokenizer, DocTokenizer::tokToString(), TRUE, and warn_doc_error().
parse() [2/2]
int DocHtmlRow::parse (DocNodeVariant *)
parseXml() [1/2]
int DocHtmlRow::parseXml (DocNodeVariant * thisVariant, bool header)
Definition at line 1862 of file docnode.cpp.
{
  int retval=RetVal_OK;
  auto ns = AutoNodeStack(parser(),thisVariant);
  DBG(("DocHtmlRow::parseXml() start\n"));
  bool isFirst=TRUE;
  DocHtmlCell *cell=0;
  // get next token
  int tok=parser()->tokenizer.lex();
  // skip whitespace
  while (tok==TK_WHITESPACE || tok==TK_NEWPARA) tok=parser()->tokenizer.lex();
  // should find a html tag now
  if (tok==TK_HTMLTAG)
  {
    int tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
    if (tagId==XML_TERM && !parser()->context.token->endTag) // found <term> tag
    {
    }
    else if (tagId==XML_DESCRIPTION && !parser()->context.token->endTag) // found <description> tag
    {
    }
    else // found some other tag
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <term> or <description> tag but "
          "found <%s> instead!",qPrint(parser()->context.token->name));
      parser()->tokenizer.pushBackHtmlTag(parser()->context.token->name);
      goto endrow;
    }
  }
  else if (tok==0) // premature end of comment
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected end of comment while looking"
        " for a html description title");
    goto endrow;
  }
  else // token other than html token
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <td> or <th> tag but found %s token instead!",
        DocTokenizer::tokToString(tok));
    goto endrow;
  }
  do
  {
    auto vDocHtmlCell = children().append<DocHtmlCell>(parser(),thisVariant,parser()->context.token->attribs,isHeading);
    cell = children().get_last<DocHtmlCell>();
    cell->markFirst(isFirst);
    isFirst=FALSE;
    retval=cell->parseXml(vDocHtmlCell);
  }
  while (retval==RetVal_TableCell || retval==RetVal_TableHCell);
  cell->markLast(TRUE);
endrow:
  DBG(("DocHtmlRow::parseXml() end\n"));
  return retval;
}
References DocNodeList::append(), TokenInfo::attribs, DocCompoundNode::children(), DocParser::context, DBG, FALSE, DocNodeList::get_last(), Mappers::htmlTagMapper, isHeading(), DocTokenizer::lex(), Mapper::map(), DocHtmlCell::markFirst(), DocHtmlCell::markLast(), DocNode::parser(), DocHtmlCell::parseXml(), DocTokenizer::pushBackHtmlTag(), qPrint(), RetVal_OK, RetVal_TableCell, RetVal_TableHCell, TK_HTMLTAG, TK_NEWPARA, TK_WHITESPACE, DocParserContext::token, DocParser::tokenizer, DocTokenizer::tokToString(), TRUE, warn_doc_error(), XML_DESCRIPTION, and XML_TERM.
Referenced by DocHtmlTable::parseXml().
parseXml() [2/2]
int DocHtmlRow::parseXml (DocNodeVariant * , bool header)
rowIndex() [1/2]
uint DocHtmlRow::rowIndex () const [inline]
Definition at line 1211 of file docnode.h.
{ return m_rowIdx; }
References m_rowIdx.
Referenced by LatexDocVisitor::operator()().
rowIndex() [2/2]
uint DocHtmlRow::rowIndex () const [inline]
Definition at line 1211 of file docnode.h.
{ return m_rowIdx; }
References m_rowIdx.
setRowIndex() [1/2]
void DocHtmlRow::setRowIndex (uint idx) [inline], [private]
Definition at line 1214 of file docnode.h.
{ m_rowIdx = idx; }
References m_rowIdx.
Referenced by DocHtmlTable::computeTableGrid().
setRowIndex() [2/2]
void DocHtmlRow::setRowIndex (uint idx) [inline], [private]
Definition at line 1214 of file docnode.h.
{ m_rowIdx = idx; }
References m_rowIdx.
setVisibleCells() [1/2]
void DocHtmlRow::setVisibleCells (uint n) [inline]
Definition at line 1209 of file docnode.h.
{ m_visibleCells = n; }
References m_visibleCells, and n.
Referenced by DocHtmlTable::computeTableGrid().
setVisibleCells() [2/2]
void DocHtmlRow::setVisibleCells (uint n) [inline]
Definition at line 1209 of file docnode.h.
{ m_visibleCells = n; }
References m_visibleCells, and n.
visibleCells() [1/2]
uint DocHtmlRow::visibleCells () const [inline]
Definition at line 1210 of file docnode.h.
{ return m_visibleCells; }
References m_visibleCells.
visibleCells() [2/2]
uint DocHtmlRow::visibleCells () const [inline]
Definition at line 1210 of file docnode.h.
{ return m_visibleCells; }
References m_visibleCells.
Friends And Related Function Documentation
DocHtmlTable
DocHtmlTable [friend]
Definition at line 1200 of file docnode.h.
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlRow::m_attribs [private]
Definition at line 1215 of file docnode.h.
Referenced by attribs().
m_rowIdx
uint DocHtmlRow::m_rowIdx = static_cast<uint>(-1) [private]
Definition at line 1217 of file docnode.h.
Referenced by rowIndex(), and setRowIndex().
m_visibleCells
uint DocHtmlRow::m_visibleCells = 0 [private]
Definition at line 1216 of file docnode.h.
Referenced by setVisibleCells(), and visibleCells().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp