ClassInheritanceContext Class Reference
#include <context.h>
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
ClassInheritanceContext ()
virtual ~ClassInheritanceContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
ClassInheritanceContext ()
virtual ~ClassInheritanceContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc ()
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 440 of file context.h.
Constructor & Destructor Documentation
ClassInheritanceContext() [1/2]
ClassInheritanceContext::ClassInheritanceContext ()
 ClassInheritanceContext() [1/2]
virtual ClassInheritanceContext::~ClassInheritanceContext () [virtual]
ClassInheritanceContext() [2/2]
ClassInheritanceContext::ClassInheritanceContext ()
 ClassInheritanceContext() [2/2]
virtual ClassInheritanceContext::~ClassInheritanceContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr ClassInheritanceContext::alloc () [inline], [static]
Definition at line 443 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ClassInheritanceContext>()); }
alloc() [2/2]
static TemplateListIntfPtr ClassInheritanceContext::alloc () [inline], [static]
Definition at line 443 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ClassInheritanceContext>()); }
at() [1/2]
virtual TemplateVariant ClassInheritanceContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
at() [2/2]
virtual TemplateVariant ClassInheritanceContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
virtual size_t ClassInheritanceContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t ClassInheritanceContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
virtual TemplateListIntf::ConstIteratorPtr ClassInheritanceContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr ClassInheritanceContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > ClassInheritanceContext::p [private]
Definition at line 456 of file context.h.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h