DotNode Class Reference
#include <dotnode.h>
Public Types
enum TruncState {
Unknown
, Truncated
, Untruncated
, Unknown
,
Truncated
, Untruncated
 }
enum TruncState {
Unknown
, Truncated
, Untruncated
, Unknown
,
Truncated
, Untruncated
 }
Public Member Functions
DotNode (int n, const QCString &lab, const QCString &tip, const QCString &url, bool rootNode=FALSE, const ClassDef *cd=0)
~DotNode ()
void addChild (DotNode *n, int edgeColor=EdgeInfo::Purple, int edgeStyle=EdgeInfo::Solid, const QCString &edgeLab=QCString(), const QCString &edgeURL=QCString(), int edgeLabCol=-1)
void addParent (DotNode *n)
void deleteNode (DotNodeRefVector &deletedList)
void removeChild (DotNode *n)
void removeParent (DotNode *n)
int findParent (DotNode *n)
void write (TextStream &t, GraphType gt, GraphOutputFormat f, bool topDown, bool toChildren, bool backArrows) const
void writeXML (TextStream &t, bool isClassGraph) const
void writeDocbook (TextStream &t, bool isClassGraph) const
void writeDEF (TextStream &t) const
void writeLabel (TextStream &t, GraphType gt) const
void writeUrl (TextStream &t) const
void writeBox (TextStream &t, GraphType gt, GraphOutputFormat f, bool hasNonReachableChildren) const
void writeArrow (TextStream &t, GraphType gt, GraphOutputFormat f, const DotNode *cn, const EdgeInfo *ei, bool topDown, bool pointBack=TRUE) const
QCString label () const
int number () const
bool isVisible () const
TruncState isTruncated () const
int distance () const
int subgraphId () const
bool isRenumbered () const
bool hasDocumentation () const
bool isWritten () const
void clearWriteFlag ()
void renumberNodes (int &number)
void markRenumbered ()
DotNode & markHasDocumentation ()
void setSubgraphId (int id)
void colorConnectedNodes (int curColor)
void setDistance (int distance)
void markAsVisible (bool b=TRUE)
DotNode & markAsTruncated (bool b=TRUE)
const DotNodeRefVector & children () const
const DotNodeRefVector & parents () const
const EdgeInfoVector & edgeInfo () const
DotNode (int n, const QCString &lab, const QCString &tip, const QCString &url, bool rootNode=FALSE, const ClassDef *cd=0)
~DotNode ()
void addChild (DotNode *n, int edgeColor=EdgeInfo::Purple, int edgeStyle=EdgeInfo::Solid, const QCString &edgeLab=QCString(), const QCString &edgeURL=QCString(), int edgeLabCol=-1)
void addParent (DotNode *n)
void deleteNode (DotNodeRefVector &deletedList)
void removeChild (DotNode *n)
void removeParent (DotNode *n)
int findParent (DotNode *n)
void write (TextStream &t, GraphType gt, GraphOutputFormat f, bool topDown, bool toChildren, bool backArrows) const
void writeXML (TextStream &t, bool isClassGraph) const
void writeDocbook (TextStream &t, bool isClassGraph) const
void writeDEF (TextStream &t) const
void writeLabel (TextStream &t, GraphType gt) const
void writeUrl (TextStream &t) const
void writeBox (TextStream &t, GraphType gt, GraphOutputFormat f, bool hasNonReachableChildren) const
void writeArrow (TextStream &t, GraphType gt, GraphOutputFormat f, const DotNode *cn, const EdgeInfo *ei, bool topDown, bool pointBack=TRUE) const
QCString label () const
int number () const
bool isVisible () const
TruncState isTruncated () const
int distance () const
int subgraphId () const
bool isRenumbered () const
bool hasDocumentation () const
bool isWritten () const
void clearWriteFlag ()
void renumberNodes (int &number)
void markRenumbered ()
DotNode & markHasDocumentation ()
void setSubgraphId (int id)
void colorConnectedNodes (int curColor)
void setDistance (int distance)
void markAsVisible (bool b=TRUE)
DotNode & markAsTruncated (bool b=TRUE)
const DotNodeRefVector & children () const
const DotNodeRefVector & parents () const
const EdgeInfoVector & edgeInfo () const
Static Public Member Functions
static void deleteNodes (DotNode *node)
static QCString convertLabel (const QCString &l)
static void deleteNodes (DotNode *node)
static QCString convertLabel (const QCString &l)
Private Attributes
int m_number
QCString m_label
label text
QCString m_tooltip
node's tooltip
QCString m_url
url of the node (format: remote$local)
DotNodeRefVector m_parents
list of parent nodes (incoming arrows)
DotNodeRefVector m_children
list of child nodes (outgoing arrows)
EdgeInfoVector m_edgeInfo
edge info for each child
bool m_deleted = false
used to mark a node as deleted
bool m_written = false
used to mark a node as written
bool m_hasDoc = false
used to mark a node as documented
bool m_isRoot
indicates if this is a root node
const ClassDef * m_classDef
class representing this node (can be 0)
bool m_visible = false
is the node visible in the output
TruncState m_truncated = Unknown
does the node have non-visible children/parents
int m_distance = 1000
shortest path to the root node
bool m_renumbered = false
indicates if the node has been renumbered (to prevent endless loops)
int m_subgraphId = -1
Detailed Description
A node in a dot graph
Definition at line 56 of file dotnode.h.
Member Enumeration Documentation
TruncState [1/2]
enum DotNode::TruncState
Enumerator
Unknown
Truncated
Untruncated
Unknown
Truncated
Untruncated
Definition at line 65 of file dotnode.h.
{ Unknown, Truncated, Untruncated };
TruncState [2/2]
enum DotNode::TruncState
Enumerator
Unknown
Truncated
Untruncated
Unknown
Truncated
Untruncated
Definition at line 65 of file dotnode.h.
{ Unknown, Truncated, Untruncated };
Constructor & Destructor Documentation
DotNode() [1/2]
DotNode::DotNode (int n, const QCString & lab, const QCString & tip, const QCString & url, bool rootNode = FALSE, const ClassDef * cd = 0)
Definition at line 266 of file dotnode.cpp.
  : m_number(n)
  , m_label(lab)
  , m_tooltip(tip)
  , m_url(url)
  , m_isRoot(isRoot)
  , m_classDef(cd)
{
}
 DotNode() [1/2]
DotNode::~DotNode ()
Definition at line 277 of file dotnode.cpp.
{
}
DotNode() [2/2]
DotNode::DotNode (int n, const QCString & lab, const QCString & tip, const QCString & url, bool rootNode = FALSE, const ClassDef * cd = 0)
 DotNode() [2/2]
DotNode::~DotNode ()
Member Function Documentation
addChild() [1/2]
void DotNode::addChild (DotNode * n, int edgeColor = EdgeInfo::Purple, int edgeStyle = EdgeInfo::Solid, const QCString & edgeLab = QCString(), const QCString & edgeURL = QCString(), int edgeLabCol = -1)
Definition at line 281 of file dotnode.cpp.
{
  m_children.push_back(n);
  m_edgeInfo.emplace_back(
      edgeColor,
      edgeStyle,
      edgeLab,
      edgeURL,
      edgeLabCol==-1 ? edgeColor : edgeLabCol);
}
References m_children, m_edgeInfo, and n.
Referenced by DotClassGraph::addClass().
addChild() [2/2]
void DotNode::addChild (DotNode * n, int edgeColor = EdgeInfo::Purple, int edgeStyle = EdgeInfo::Solid, const QCString & edgeLab = QCString(), const QCString & edgeURL = QCString(), int edgeLabCol = -1)
addParent() [1/2]
void DotNode::addParent (DotNode * n)
Definition at line 298 of file dotnode.cpp.
{
  m_parents.push_back(n);
}
References m_parents, and n.
Referenced by DotClassGraph::addClass(), DotInclDepGraph::buildGraph(), and DotCallGraph::buildGraph().
addParent() [2/2]
void DotNode::addParent (DotNode * n)
children() [1/2]
const DotNodeRefVector & DotNode::children () const [inline]
Definition at line 111 of file dotnode.h.
{ return m_children; }
References m_children.
Referenced by DotCallGraph::isTrivial(), DotClassGraph::isTrivial(), DotInclDepGraph::isTrivial(), DotCallGraph::numNodes(), DotClassGraph::numNodes(), DotInclDepGraph::numNodes(), and write().
children() [2/2]
const DotNodeRefVector & DotNode::children () const [inline]
Definition at line 111 of file dotnode.h.
{ return m_children; }
References m_children.
clearWriteFlag() [1/2]
void DotNode::clearWriteFlag ()
Definition at line 810 of file dotnode.cpp.
{
  m_written=FALSE;
  for (const auto &pn : m_parents) if (pn->isWritten()) pn->clearWriteFlag();
  for (const auto &cn : m_children) if (cn->isWritten()) cn->clearWriteFlag();
}
References FALSE, m_children, m_parents, and m_written.
Referenced by DotGraph::computeGraph().
clearWriteFlag() [2/2]
void DotNode::clearWriteFlag ()
colorConnectedNodes() [1/2]
void DotNode::colorConnectedNodes (int curColor)
Definition at line 817 of file dotnode.cpp.
{
  for (const auto &cn : m_children)
  {
    if (cn->subgraphId()==-1) // uncolored child node
    {
      cn->setSubgraphId(curColor);
      cn->markAsVisible();
      cn->colorConnectedNodes(curColor);
      //printf("coloring node %s (%p): %d\n",qPrint(cn->label()),cn,cn->subgraphId());
    }
  }
  for (const auto &pn : m_parents)
  {
    if (pn->subgraphId()==-1) // uncolored parent node
    {
      pn->setSubgraphId(curColor);
      pn->markAsVisible();
      pn->colorConnectedNodes(curColor);
      //printf("coloring node %s (%p): %d\n",qPrint(pn->label()),pn,pn->subgraphId());
    }
  }
}
References m_children, and m_parents.
colorConnectedNodes() [2/2]
void DotNode::colorConnectedNodes (int curColor)
convertLabel() [1/2]
QCString DotNode::convertLabel (const QCString & l) [static]
Definition at line 184 of file dotnode.cpp.
{
  QCString bBefore("\\_/<({[: =-+@%#~?$"); // break before character set
  QCString bAfter(">]),:;|"); // break after character set
  QCString p(l);
  if (p.isEmpty()) return QCString();
  QCString result;
  char c,pc=0;
  uint idx = 0;
  int len=p.length();
  int charsLeft=len;
  int sinceLast=0;
  int foldLen = Config_getInt(DOT_WRAP_THRESHOLD); // ideal text length
  while (idx < p.length())
  {
    c = p[idx++];
    QCString replacement;
    switch(c)
    {
      case '\\': replacement="\\\\"; break;
      case '\n': replacement="\\n"; break;
      case '<': replacement="\\<"; break;
      case '>': replacement="\\>"; break;
      case '|': replacement="\\|"; break;
      case '{': replacement="\\{"; break;
      case '}': replacement="\\}"; break;
      case '"': replacement="\\\""; break;
      default: replacement+=c; break;
    }
    // Some heuristics to insert newlines to prevent too long
    // boxes and at the same time prevent ugly breaks
    if (c=='\n')
    {
      result+=replacement;
      foldLen = (3*foldLen+sinceLast+2)/4;
      sinceLast=1;
    }
    else if ((pc!=':' || c!=':') && charsLeft>foldLen/3 && sinceLast>foldLen && bBefore.contains(c))
    {
      result+="\\l";
      result+=replacement;
      foldLen = (foldLen+sinceLast+1)/2;
      sinceLast=1;
    }
    else if (charsLeft>1+foldLen/4 && sinceLast>foldLen+foldLen/3 &&
      !isupper(c) && isupper(p[idx]))
    {
      result+=replacement;
      result+="\\l";
      foldLen = (foldLen+sinceLast+1)/2;
      sinceLast=0;
    }
    else if (charsLeft>foldLen/3 && sinceLast>foldLen && bAfter.contains(c) && (c!=':' || p[idx]!=':'))
    {
      result+=replacement;
      result+="\\l";
      foldLen = (foldLen+sinceLast+1)/2;
      sinceLast=0;
    }
    else
    {
      result+=replacement;
      sinceLast++;
    }
    charsLeft--;
    pc=c;
  }
  return result;
}
References c, Config_getInt, QCString::contains(), len, and p.
Referenced by drawClusterOpening(), drawDirectory(), DotGroupCollaboration::Edge::write(), writeArrow(), writeBoxMemberList(), and writeLabel().
convertLabel() [2/2]
static QCString DotNode::convertLabel (const QCString & l) [static]
deleteNode() [1/2]
void DotNode::deleteNode (DotNodeRefVector & deletedList)
Definition at line 315 of file dotnode.cpp.
{
  if (m_deleted) return; // avoid recursive loops in case the graph has cycles
  m_deleted=TRUE;
  // delete all parent nodes of this node
  for (const auto &pn : m_parents)
  {
    pn->deleteNode(deletedList);
  }
  // delete all child nodes of this node
  for (const auto &cn : m_children)
  {
    cn->deleteNode(deletedList);
  }
  // add this node to the list of deleted nodes.
  deletedList.push_back(this);
}
References m_children, m_deleted, m_parents, and TRUE.
Referenced by deleteNodes().
deleteNode() [2/2]
void DotNode::deleteNode (DotNodeRefVector & deletedList)
deleteNodes() [1/2]
void DotNode::deleteNodes (DotNode * node) [static]
helper function that deletes all nodes in a connected graph, given one of the graph's nodes
Definition at line 347 of file dotnode.cpp.
{
  DotNodeRefVector deletedNodes;
  node->deleteNode(deletedNodes); // collect nodes to be deleted.
  for (const auto &dotNode : deletedNodes)
  {
    delete dotNode;
  }
}
References deleteNode().
Referenced by DotCallGraph::~DotCallGraph(), DotClassGraph::~DotClassGraph(), and DotInclDepGraph::~DotInclDepGraph().
deleteNodes() [2/2]
static void DotNode::deleteNodes (DotNode * node) [static]
distance() [1/2]
int DotNode::distance () const [inline]
Definition at line 95 of file dotnode.h.
{ return m_distance; }
References m_distance.
Referenced by setDistance().
distance() [2/2]
int DotNode::distance () const [inline]
Definition at line 95 of file dotnode.h.
{ return m_distance; }
References m_distance.
edgeInfo() [1/2]
const EdgeInfoVector & DotNode::edgeInfo () const [inline]
Definition at line 113 of file dotnode.h.
{ return m_edgeInfo; }
References m_edgeInfo.
Referenced by writeDEF(), writeDocbook(), and writeXML().
edgeInfo() [2/2]
const EdgeInfoVector & DotNode::edgeInfo () const [inline]
Definition at line 113 of file dotnode.h.
{ return m_edgeInfo; }
References m_edgeInfo.
findParent() [1/2]
int DotNode::findParent (DotNode * n) [inline]
Definition at line 338 of file dotnode.cpp.
{
  auto it = std::find(m_parents.begin(),m_parents.end(),n);
  return it!=m_parents.end() ? static_cast<int>(it-m_parents.begin()) : -1;
}
References m_parents, and n.
findParent() [2/2]
int DotNode::findParent (DotNode * n)
hasDocumentation() [1/2]
bool DotNode::hasDocumentation () const [inline]
Definition at line 98 of file dotnode.h.
{ return m_hasDoc; }
References m_hasDoc.
hasDocumentation() [2/2]
bool DotNode::hasDocumentation () const [inline]
Definition at line 98 of file dotnode.h.
{ return m_hasDoc; }
References m_hasDoc.
isRenumbered() [1/2]
bool DotNode::isRenumbered () const [inline]
Definition at line 97 of file dotnode.h.
{ return m_renumbered; }
References m_renumbered.
Referenced by renumberNodes().
isRenumbered() [2/2]
bool DotNode::isRenumbered () const [inline]
Definition at line 97 of file dotnode.h.
{ return m_renumbered; }
References m_renumbered.
isTruncated() [1/2]
TruncState DotNode::isTruncated () const [inline]
Definition at line 94 of file dotnode.h.
{ return m_truncated; }
References m_truncated.
isTruncated() [2/2]
TruncState DotNode::isTruncated () const [inline]
Definition at line 94 of file dotnode.h.
{ return m_truncated; }
References m_truncated.
isVisible() [1/2]
bool DotNode::isVisible () const [inline]
Definition at line 93 of file dotnode.h.
{ return m_visible; }
References m_visible.
isVisible() [2/2]
bool DotNode::isVisible () const [inline]
Definition at line 93 of file dotnode.h.
{ return m_visible; }
References m_visible.
isWritten() [1/2]
bool DotNode::isWritten () const [inline]
Definition at line 99 of file dotnode.h.
{ return m_written; }
References m_written.
isWritten() [2/2]
bool DotNode::isWritten () const [inline]
Definition at line 99 of file dotnode.h.
{ return m_written; }
References m_written.
label() [1/2]
QCString DotNode::label () const [inline]
Definition at line 91 of file dotnode.h.
{ return m_label; }
References m_label.
Referenced by doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.nodeType::buildChildren(), DotCallGraph::computeTheGraph(), DotClassGraph::computeTheGraph(), DotGroupCollaboration::computeTheGraph(), DotInclDepGraph::computeTheGraph(), doxmlparser.compound.nodeType::exportChildren(), doxmlparser.compound.nodeType::get_label(), DotClassGraph::getMapLabel(), DotGfxHierarchyTable::getMapLabel(), DotInclDepGraph::getMapLabel(), doxmlparser.compound.nodeType::hasContent_(), and doxmlparser.compound.nodeType::set_label().
label() [2/2]
QCString DotNode::label () const [inline]
Definition at line 91 of file dotnode.h.
{ return m_label; }
References m_label.
Referenced by doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.nodeType::buildChildren(), doxmlparser.compound.nodeType::exportChildren(), doxmlparser.compound.nodeType::get_label(), doxmlparser.compound.nodeType::hasContent_(), and doxmlparser.compound.nodeType::set_label().
markAsTruncated() [1/2]
DotNode & DotNode::markAsTruncated (bool b = TRUE) [inline]
Definition at line 110 of file dotnode.h.
{ m_truncated=b ? Truncated : Untruncated; return *this;}
References b, m_truncated, Truncated, and Untruncated.
Referenced by DotLegendGraph::computeTheGraph().
markAsTruncated() [2/2]
DotNode & DotNode::markAsTruncated (bool b = TRUE) [inline]
Definition at line 110 of file dotnode.h.
{ m_truncated=b ? Truncated : Untruncated; return *this;}
References b, m_truncated, Truncated, and Untruncated.
markAsVisible() [1/2]
void DotNode::markAsVisible (bool b = TRUE) [inline]
Definition at line 109 of file dotnode.h.
{ m_visible=b; }
References b, and m_visible.
Referenced by DotGroupCollaboration::addCollaborationMember(), DotGroupCollaboration::buildGraph(), and DotGroupCollaboration::DotGroupCollaboration().
markAsVisible() [2/2]
void DotNode::markAsVisible (bool b = TRUE) [inline]
Definition at line 109 of file dotnode.h.
{ m_visible=b; }
References b, and m_visible.
markHasDocumentation() [1/2]
DotNode & DotNode::markHasDocumentation () [inline]
Definition at line 104 of file dotnode.h.
{ m_hasDoc = true; return *this;}
References m_hasDoc.
Referenced by DotLegendGraph::computeTheGraph().
markHasDocumentation() [2/2]
DotNode & DotNode::markHasDocumentation () [inline]
Definition at line 104 of file dotnode.h.
{ m_hasDoc = true; return *this;}
References m_hasDoc.
markRenumbered() [1/2]
void DotNode::markRenumbered () [inline]
Definition at line 103 of file dotnode.h.
{ m_renumbered = true; }
References m_renumbered.
Referenced by renumberNodes().
markRenumbered() [2/2]
void DotNode::markRenumbered () [inline]
Definition at line 103 of file dotnode.h.
{ m_renumbered = true; }
References m_renumbered.
number() [1/2]
int DotNode::number () const [inline]
Definition at line 92 of file dotnode.h.
{ return m_number; }
References m_number.
Referenced by renumberNodes(), DotGroupCollaboration::Edge::write(), and writeArrow().
number() [2/2]
int DotNode::number () const [inline]
Definition at line 92 of file dotnode.h.
{ return m_number; }
References m_number.
parents() [1/2]
const DotNodeRefVector & DotNode::parents () const [inline]
Definition at line 112 of file dotnode.h.
{ return m_parents; }
References m_parents.
Referenced by DotGraph::computeGraph(), DotClassGraph::isTrivial(), and DotClassGraph::numNodes().
parents() [2/2]
const DotNodeRefVector & DotNode::parents () const [inline]
Definition at line 112 of file dotnode.h.
{ return m_parents; }
References m_parents.
removeChild() [1/2]
void DotNode::removeChild (DotNode * n)
Definition at line 303 of file dotnode.cpp.
{
  auto it = std::find(m_children.begin(),m_children.end(),n);
  if (it!=m_children.end()) m_children.erase(it);
}
References m_children, and n.
removeChild() [2/2]
void DotNode::removeChild (DotNode * n)
removeParent() [1/2]
void DotNode::removeParent (DotNode * n)
Definition at line 309 of file dotnode.cpp.
{
  auto it = std::find(m_parents.begin(),m_parents.end(),n);
  if (it!=m_parents.end()) m_parents.erase(it);
}
References m_parents, and n.
removeParent() [2/2]
void DotNode::removeParent (DotNode * n)
renumberNodes() [1/2]
void DotNode::renumberNodes (int & number)
Definition at line 844 of file dotnode.cpp.
{
  if (!isRenumbered())
  {
#if DEBUG_RENUMBERING
    static int level = 0;
    printf("%3d: ",subgraphId());
    for (int i = 0; i < level; i++) printf(" ");
    printf("> %s old = %d new = %d\n",qPrint(m_label),m_number,number);
    level++;
#endif
    m_number = number++;
    markRenumbered();
    for (const auto &cn : m_children)
    {
      cn->renumberNodes(number);
    }
    for (const auto &pn : m_parents)
    {
      pn->renumberNodes(number);
    }
#if DEBUG_RENUMBERING
    level--;
    printf("%3d: ",subgraphId());
    for (int i = 0; i < level; i++) printf(" ");
    printf("< %s assigned = %d\n",qPrint(m_label),m_number);
#endif
  }
}
References isRenumbered(), level, m_children, m_label, m_number, m_parents, markRenumbered(), number(), qPrint(), and subgraphId().
renumberNodes() [2/2]
void DotNode::renumberNodes (int & number)
setDistance() [1/2]
void DotNode::setDistance (int distance)
Definition at line 333 of file dotnode.cpp.
{
  if (distance<m_distance) m_distance = distance;
}
References distance(), and m_distance.
Referenced by DotClassGraph::addClass(), DotInclDepGraph::buildGraph(), DotCallGraph::buildGraph(), DotCallGraph::DotCallGraph(), DotClassGraph::DotClassGraph(), and DotInclDepGraph::DotInclDepGraph().
setDistance() [2/2]
void DotNode::setDistance (int distance)
setSubgraphId() [1/2]
void DotNode::setSubgraphId (int id) [inline]
Definition at line 105 of file dotnode.h.
{ m_subgraphId = id; }
References id, and m_subgraphId.
setSubgraphId() [2/2]
void DotNode::setSubgraphId (int id) [inline]
Definition at line 105 of file dotnode.h.
{ m_subgraphId = id; }
References id, and m_subgraphId.
subgraphId() [1/2]
int DotNode::subgraphId () const [inline]
Definition at line 96 of file dotnode.h.
{ return m_subgraphId; }
References m_subgraphId.
Referenced by DotGfxHierarchyTable::computeTheGraph(), and renumberNodes().
subgraphId() [2/2]
int DotNode::subgraphId () const [inline]
Definition at line 96 of file dotnode.h.
{ return m_subgraphId; }
References m_subgraphId.
write() [1/2]
void DotNode::write (TextStream & t, GraphType gt, GraphOutputFormat f, bool topDown, bool toChildren, bool backArrows) const
Definition at line 577 of file dotnode.cpp.
{
  //printf("DotNode::write(%d) name=%s this=%p written=%d visible=%d\n",m_distance,qPrint(m_label),this,m_written,m_visible);
  if (m_written) return; // node already written to the output
  if (!m_visible) return; // node is not visible
  writeBox(t,gt,format,m_truncated==Truncated);
  m_written=TRUE;
  if (toChildren)
  {
    auto it = m_edgeInfo.begin();
    for (const auto &cn : m_children)
    {
      if (cn->isVisible())
      {
        //printf("write arrow %s%s%s\n",qPrint(label()),backArrows?"<-":"->",qPrint(cn->label()));
        writeArrow(t,gt,format,cn,&(*it),topDown,backArrows);
      }
      cn->write(t,gt,format,topDown,toChildren,backArrows);
      ++it;
    }
  }
  else // render parents
  {
    for (const auto &pn : m_parents)
    {
      if (pn->isVisible())
      {
        const auto &children = pn->children();
        auto child_it = std::find(children.begin(),children.end(),this);
        size_t index = child_it - children.begin();
        //printf("write arrow %s%s%s\n",qPrint(label()),backArrows?"<-":"->",qPrint(pn->label()));
        writeArrow(t,
          gt,
          format,
          pn,
          &pn->edgeInfo()[index],
          FALSE,
          backArrows
        );
      }
      pn->write(t,gt,format,TRUE,FALSE,backArrows);
    }
  }
  //printf("end DotNode::write(%d) name=%s\n",distance,qPrint(m_label));
}
References children(), FALSE, m_children, m_edgeInfo, m_parents, m_truncated, m_visible, m_written, TRUE, Truncated, writeArrow(), and writeBox().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), DotGraph::computeGraph(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_write(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_write().
write() [2/2]
void DotNode::write (TextStream & t, GraphType gt, GraphOutputFormat f, bool topDown, bool toChildren, bool backArrows) const
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_write(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_write().
writeArrow() [1/2]
void DotNode::writeArrow (TextStream & t, GraphType gt, GraphOutputFormat f, const DotNode * cn, const EdgeInfo * ei, bool topDown, bool pointBack = TRUE) const
Definition at line 530 of file dotnode.cpp.
{
  t << " Node";
  if (topDown)
    t << cn->number();
  else
    t << m_number;
  t << " -> Node";
  if (topDown)
    t << m_number;
  else
    t << cn->number();
  t << " [";
  const EdgeProperties *eProps = Config_getBool(UML_LOOK) ? &umlEdgeProps : &normalEdgeProps;
  QCString aStyle = eProps->arrowStyleMap[ei->color()];
  bool umlUseArrow = aStyle=="odiamond";
  if (pointBack && !umlUseArrow) t << "dir=\"back\",";
  t << "color=\"" << eProps->edgeColorMap[ei->color()] << "\",";
  t << "style=\"" << eProps->edgeStyleMap[ei->style()] << "\"";
  if (!ei->label().isEmpty())
  {
    t << ",label=\" " << convertLabel(ei->label()) << "\" ";
  }
  if (Config_getBool(UML_LOOK) &&
    eProps->arrowStyleMap[ei->color()] &&
    (gt==Inheritance || gt==Collaboration)
    )
  {
    bool rev = pointBack;
    if (umlUseArrow) rev=!rev; // UML use relates has arrow on the start side
    if (rev)
      t << ",arrowtail=\"" << eProps->arrowStyleMap[ei->color()] << "\"";
    else
      t << ",arrowhead=\"" << eProps->arrowStyleMap[ei->color()] << "\"";
  }
  t << "];\n";
}
References EdgeProperties::arrowStyleMap, Collaboration, EdgeInfo::color(), Config_getBool, convertLabel(), EdgeProperties::edgeColorMap, EdgeProperties::edgeStyleMap, Inheritance, QCString::isEmpty(), EdgeInfo::label(), m_number, normalEdgeProps, number(), EdgeInfo::style(), and umlEdgeProps.
Referenced by DotGraph::computeGraph(), and write().
writeArrow() [2/2]
void DotNode::writeArrow (TextStream & t, GraphType gt, GraphOutputFormat f, const DotNode * cn, const EdgeInfo * ei, bool topDown, bool pointBack = TRUE) const
writeBox() [1/2]
void DotNode::writeBox (TextStream & t, GraphType gt, GraphOutputFormat f, bool hasNonReachableChildren) const
Definition at line 473 of file dotnode.cpp.
{
  const char *labCol;
  const char *fillCol = "white";
  if (m_classDef)
  {
    if (m_classDef->hasDocumentation() && hasNonReachableChildren)
    {
      labCol = "red";
      fillCol = "#FFF0F0";
    }
    else if (m_classDef->hasDocumentation() && !hasNonReachableChildren)
      labCol = "gray40";
    else if (!m_classDef->hasDocumentation() && hasNonReachableChildren)
      labCol = "orangered";
    else // (!m_classDef->hasDocumentation() && !hasNonReachableChildren)
    {
      labCol = "grey75";
      if (m_classDef->templateMaster() && m_classDef->templateMaster()->hasDocumentation())
        labCol = "gray40";
    }
  }
  else
  {
    labCol = m_url.isEmpty() ? "grey60" : // non link
    (hasNonReachableChildren ? "red" : "grey40");
    fillCol = m_url.isEmpty() ? "#E0E0E0" :
    (hasNonReachableChildren ? "#FFF0F0" : "white");
  }
  t << " Node" << m_number << " [";
  writeLabel(t,gt);
  t << ",height=0.2,width=0.4";
  if (m_isRoot)
  {
    t << ",color=\"gray40\", fillcolor=\"grey60\", style=\"filled\", fontcolor=\"black\"";
  }
  else
  {
    t << ",color=\"" << labCol << "\"";
    t << ", fillcolor=\"" << fillCol << "\"";
    t << ", style=\"filled\"";
    writeUrl(t);
  }
  if (!m_tooltip.isEmpty())
  {
    t << ",tooltip=\"" << escapeTooltip(m_tooltip) << "\"";
  }
  else
  {
    t << ",tooltip=\" \""; // space in tooltip is required otherwise still something like 'Node0' is used
  }
  t << "];\n";
}
References escapeTooltip(), ClassDef::hasDocumentation(), QCString::isEmpty(), m_classDef, m_isRoot, m_number, m_tooltip, m_url, ClassDef::templateMaster(), writeLabel(), and writeUrl().
Referenced by DotLegendGraph::computeTheGraph(), and write().
writeBox() [2/2]
void DotNode::writeBox (TextStream & t, GraphType gt, GraphOutputFormat f, bool hasNonReachableChildren) const
writeDEF() [1/2]
void DotNode::writeDEF (TextStream & t) const
Definition at line 753 of file dotnode.cpp.
{
  const char* nodePrefix = " node-";
  t << " node = {\n";
  t << nodePrefix << "id = " << m_number << ";\n";
  t << nodePrefix << "label = '" << m_label << "';\n";
  if (!m_url.isEmpty())
  {
    QCString url(m_url);
    int dollarPos = url.find('$');
    if (dollarPos!=-1)
    {
      t << nodePrefix << "link = {\n" << " "
        << nodePrefix << "link-id = '" << url.mid(dollarPos+1) << "';\n";
      if (dollarPos>0)
      {
        t << " " << nodePrefix << "link-external = '"
          << url.left(dollarPos) << "';\n";
      }
      t << " };\n";
    }
  }
  auto it = m_edgeInfo.begin();
  for (const auto &childNode : m_children)
  {
    const EdgeInfo &edgeInfo = *it;
    t << " node-child = {\n";
    t << " child-id = '" << childNode->number() << "';\n";
    t << " relation = ";
    switch (edgeInfo.color())
    {
      case EdgeInfo::Blue: t << "public-inheritance"; break;
      case EdgeInfo::Green: t << "protected-inheritance"; break;
      case EdgeInfo::Red: t << "private-inheritance"; break;
      case EdgeInfo::Purple: t << "usage"; break;
      case EdgeInfo::Orange: t << "template-instance"; break;
      case EdgeInfo::Orange2: t << "type-constraint"; break;
      case EdgeInfo::Grey: ASSERT(0); break;
    }
    t << ";\n";
    if (!edgeInfo.label().isEmpty())
    {
      t << " edgelabel = <<_EnD_oF_dEf_TeXt_\n"
        << edgeInfo.label() << "\n"
        << "_EnD_oF_dEf_TeXt_;\n";
    }
    t << " }; /* node-child */\n";
    ++it;
  }
  t << " }; /* node */\n";
}
References ASSERT, EdgeInfo::Blue, edgeInfo(), EdgeInfo::Green, EdgeInfo::Grey, QCString::isEmpty(), m_children, m_edgeInfo, m_label, m_number, m_url, EdgeInfo::Orange, EdgeInfo::Orange2, EdgeInfo::Purple, EdgeInfo::Red, and setup::url.
writeDEF() [2/2]
void DotNode::writeDEF (TextStream & t) const
writeDocbook() [1/2]
void DotNode::writeDocbook (TextStream & t, bool isClassGraph) const
Definition at line 690 of file dotnode.cpp.
{
  t << " <node id=\"" << m_number << "\">\n";
  t << " <label>" << convertToXML(m_label) << "</label>\n";
  if (!m_url.isEmpty())
  {
    QCString url(m_url);
    int dollarPos = url.find('$');
    if (dollarPos!=-1)
    {
      t << " <link refid=\"" << convertToXML(url.mid(dollarPos+1)) << "\"";
      if (dollarPos>0)
      {
        t << " external=\"" << convertToXML(url.left(dollarPos)) << "\"";
      }
      t << "/>\n";
    }
  }
  auto it = m_edgeInfo.begin();
  for (const auto &childNode : m_children)
  {
    const EdgeInfo &edgeInfo = *it;
    t << " <childnode refid=\"" << childNode->number() << "\" relation=\"";
    if (isClassGraph)
    {
      switch(edgeInfo.color())
      {
      case EdgeInfo::Blue: t << "public-inheritance"; break;
      case EdgeInfo::Green: t << "protected-inheritance"; break;
      case EdgeInfo::Red: t << "private-inheritance"; break;
      case EdgeInfo::Purple: t << "usage"; break;
      case EdgeInfo::Orange: t << "template-instance"; break;
      case EdgeInfo::Orange2: t << "type-constraint"; break;
      case EdgeInfo::Grey: ASSERT(0); break;
      }
    }
    else // include graph
    {
      t << "include";
    }
    t << "\">\n";
    if (!edgeInfo.label().isEmpty())
    {
      int p=0;
      int ni;
      while ((ni=edgeInfo.label().find('\n',p))!=-1)
      {
        t << " <edgelabel>"
          << convertToXML(edgeInfo.label().mid(p,ni-p))
          << "</edgelabel>\n";
        p=ni+1;
      }
      t << " <edgelabel>"
        << convertToXML(edgeInfo.label().right(edgeInfo.label().length()-p))
        << "</edgelabel>\n";
    }
    t << " </childnode>\n";
    ++it;
  }
  t << " </node>\n";
}
References ASSERT, EdgeInfo::Blue, convertToXML(), edgeInfo(), EdgeInfo::Green, EdgeInfo::Grey, QCString::isEmpty(), m_children, m_edgeInfo, m_label, m_number, m_url, EdgeInfo::Orange, EdgeInfo::Orange2, p, EdgeInfo::Purple, EdgeInfo::Red, and setup::url.
writeDocbook() [2/2]
void DotNode::writeDocbook (TextStream & t, bool isClassGraph) const
writeLabel() [1/2]
void DotNode::writeLabel (TextStream & t, GraphType gt) const
Definition at line 357 of file dotnode.cpp.
{
  if (m_classDef && Config_getBool(UML_LOOK) && (gt==Inheritance || gt==Collaboration))
  {
    // Set shape to the record-based type.
    // Record-based shape represent recursive lists of fields, which are drawn as alternating horizontal and vertical rows of boxes. Special characters are: Literal braces, vertical bars and angle brackets.
    // Only shape types: record and Mrecord support record-based label. See dot User's Manual, Ch. 21, p. 6.
    t << "shape=record,label=";
    // add names shown as relations to a set, so we don't show
    // them as attributes as well
    StringUnorderedSet arrowNames;
    // for each edge
    for (const auto &ei : m_edgeInfo)
    {
      if (!ei.label().isEmpty()) // labels joined by \n
      {
        int i;
        int p=0;
        QCString lab;
        while ((i=ei.label().find('\n',p))!=-1)
        {
          lab = stripProtectionPrefix(ei.label().mid(p,i-p));
          arrowNames.insert(lab.str());
          p=i+1;
        }
        lab = stripProtectionPrefix(ei.label().right(ei.label().length()-p));
        arrowNames.insert(lab.str());
      }
    }
    //printf("DotNode::writeBox for %s\n",qPrint(m_classDef->name()));
    t << "\"{" << convertLabel(m_label) << "\\n";
    auto dotUmlDetails = Config_getEnum(DOT_UML_DETAILS);
    if (dotUmlDetails!=DOT_UML_DETAILS_t::NONE)
    {
      t << "|";
      writeBoxMemberList(t,'+',m_classDef->getMemberList(MemberListType_pubAttribs),m_classDef,FALSE,&arrowNames);
      writeBoxMemberList(t,'+',m_classDef->getMemberList(MemberListType_pubStaticAttribs),m_classDef,TRUE,&arrowNames);
      writeBoxMemberList(t,'+',m_classDef->getMemberList(MemberListType_properties),m_classDef,FALSE,&arrowNames);
      writeBoxMemberList(t,'~',m_classDef->getMemberList(MemberListType_pacAttribs),m_classDef,FALSE,&arrowNames);
      writeBoxMemberList(t,'~',m_classDef->getMemberList(MemberListType_pacStaticAttribs),m_classDef,TRUE,&arrowNames);
      writeBoxMemberList(t,'#',m_classDef->getMemberList(MemberListType_proAttribs),m_classDef,FALSE,&arrowNames);
      writeBoxMemberList(t,'#',m_classDef->getMemberList(MemberListType_proStaticAttribs),m_classDef,TRUE,&arrowNames);
      if (Config_getBool(EXTRACT_PRIVATE))
      {
        writeBoxMemberList(t,'-',m_classDef->getMemberList(MemberListType_priAttribs),m_classDef,FALSE,&arrowNames);
        writeBoxMemberList(t,'-',m_classDef->getMemberList(MemberListType_priStaticAttribs),m_classDef,TRUE,&arrowNames);
      }
      t << "|";
      writeBoxMemberList(t,'+',m_classDef->getMemberList(MemberListType_pubMethods),m_classDef);
      writeBoxMemberList(t,'+',m_classDef->getMemberList(MemberListType_pubStaticMethods),m_classDef,TRUE);
      writeBoxMemberList(t,'+',m_classDef->getMemberList(MemberListType_pubSlots),m_classDef);
      writeBoxMemberList(t,'~',m_classDef->getMemberList(MemberListType_pacMethods),m_classDef);
      writeBoxMemberList(t,'~',m_classDef->getMemberList(MemberListType_pacStaticMethods),m_classDef,TRUE);
      writeBoxMemberList(t,'#',m_classDef->getMemberList(MemberListType_proMethods),m_classDef);
      writeBoxMemberList(t,'#',m_classDef->getMemberList(MemberListType_proStaticMethods),m_classDef,TRUE);
      writeBoxMemberList(t,'#',m_classDef->getMemberList(MemberListType_proSlots),m_classDef);
      if (Config_getBool(EXTRACT_PRIVATE))
      {
        writeBoxMemberList(t,'-',m_classDef->getMemberList(MemberListType_priMethods),m_classDef);
        writeBoxMemberList(t,'-',m_classDef->getMemberList(MemberListType_priStaticMethods),m_classDef,TRUE);
        writeBoxMemberList(t,'-',m_classDef->getMemberList(MemberListType_priSlots),m_classDef);
      }
      if (m_classDef->getLanguage()!=SrcLangExt_Fortran)
      {
        for (const auto &mg : m_classDef->getMemberGroups())
        {
          if (!mg->members().empty())
          {
            writeBoxMemberList(t,'*',&mg->members(),m_classDef,FALSE,&arrowNames);
          }
        }
      }
    }
    t << "}\"";
  }
  else if (Config_getString(DOT_NODE_ATTR).contains("shape=plain"))
  {
    t << "label=";
    if (m_isRoot)
      t << "<<b>" << convertToXML(m_label) << "</b>>";
    else if (m_truncated == Truncated)
      t << "<<i>" << convertToXML(m_label) << "</i>>";
    else
      t << '"' << convertLabel(m_label) << '"';
  }
  else // standard look
  {
    t << "label=" << '"' << convertLabel(m_label) << '"';
  }
}
References Collaboration, Config_getBool, Config_getEnum, Config_getString, convertLabel(), convertToXML(), FALSE, Definition::getLanguage(), ClassDef::getMemberGroups(), ClassDef::getMemberList(), Inheritance, m_classDef, m_edgeInfo, m_isRoot, m_label, m_truncated, MemberListType_pacAttribs, MemberListType_pacMethods, MemberListType_pacStaticAttribs, MemberListType_pacStaticMethods, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_properties, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, NONE, p, SrcLangExt_Fortran, QCString::str(), stripProtectionPrefix(), TRUE, Truncated, and writeBoxMemberList().
Referenced by writeBox().
writeLabel() [2/2]
void DotNode::writeLabel (TextStream & t, GraphType gt) const
writeUrl() [1/2]
void DotNode::writeUrl (TextStream & t) const
Definition at line 449 of file dotnode.cpp.
{
  if (m_url.isEmpty())
    return;
  int tagPos = m_url.findRev('$');
  t << ",URL=\"";
  QCString noTagURL = m_url;
  if (tagPos!=-1)
  {
    t << m_url.left(tagPos);
    noTagURL = m_url.mid(tagPos);
  }
  int anchorPos = noTagURL.findRev('#');
  if (anchorPos==-1)
  {
    t << addHtmlExtensionIfMissing(noTagURL) << "\"";
  }
  else
  {
    t << addHtmlExtensionIfMissing(noTagURL.left(anchorPos))
      << noTagURL.right(noTagURL.length() - anchorPos) << "\"";
  }
}
References addHtmlExtensionIfMissing(), QCString::findRev(), QCString::isEmpty(), QCString::left(), QCString::length(), m_url, QCString::mid(), and QCString::right().
Referenced by writeBox().
writeUrl() [2/2]
void DotNode::writeUrl (TextStream & t) const
writeXML() [1/2]
void DotNode::writeXML (TextStream & t, bool isClassGraph) const
Definition at line 628 of file dotnode.cpp.
{
  t << " <node id=\"" << m_number << "\">\n";
  t << " <label>" << convertToXML(m_label) << "</label>\n";
  if (!m_url.isEmpty())
  {
    QCString url(m_url);
    int dollarPos = url.find('$');
    if (dollarPos!=-1)
    {
      t << " <link refid=\"" << convertToXML(url.mid(dollarPos+1)) << "\"";
      if (dollarPos>0)
      {
        t << " external=\"" << convertToXML(url.left(dollarPos)) << "\"";
      }
      t << "/>\n";
    }
  }
  auto it = m_edgeInfo.begin();
  for (const auto &childNode : m_children)
  {
    const EdgeInfo &edgeInfo = *it;
    t << " <childnode refid=\"" << childNode->number() << "\" relation=\"";
    if (isClassGraph)
    {
      switch(edgeInfo.color())
      {
      case EdgeInfo::Blue: t << "public-inheritance"; break;
      case EdgeInfo::Green: t << "protected-inheritance"; break;
      case EdgeInfo::Red: t << "private-inheritance"; break;
      case EdgeInfo::Purple: t << "usage"; break;
      case EdgeInfo::Orange: t << "template-instance"; break;
      case EdgeInfo::Orange2: t << "type-constraint"; break;
      case EdgeInfo::Grey: ASSERT(0); break;
      }
    }
    else // include graph
    {
      t << "include";
    }
    t << "\">\n";
    if (!edgeInfo.label().isEmpty())
    {
      int p=0;
      int ni;
      while ((ni=edgeInfo.label().find('\n',p))!=-1)
      {
        t << " <edgelabel>"
          << convertToXML(edgeInfo.label().mid(p,ni-p))
          << "</edgelabel>\n";
        p=ni+1;
      }
      t << " <edgelabel>"
        << convertToXML(edgeInfo.label().right(edgeInfo.label().length()-p))
        << "</edgelabel>\n";
    }
    t << " </childnode>\n";
    ++it;
  }
  t << " </node>\n";
}
References ASSERT, EdgeInfo::Blue, convertToXML(), edgeInfo(), EdgeInfo::Green, EdgeInfo::Grey, QCString::isEmpty(), m_children, m_edgeInfo, m_label, m_number, m_url, EdgeInfo::Orange, EdgeInfo::Orange2, p, EdgeInfo::Purple, EdgeInfo::Red, and setup::url.
writeXML() [2/2]
void DotNode::writeXML (TextStream & t, bool isClassGraph) const
Member Data Documentation
m_children
DotNodeRefVector DotNode::m_children [private]
list of child nodes (outgoing arrows)
Definition at line 121 of file dotnode.h.
Referenced by addChild(), children(), clearWriteFlag(), colorConnectedNodes(), deleteNode(), removeChild(), renumberNodes(), write(), writeDEF(), writeDocbook(), and writeXML().
m_classDef
const ClassDef * DotNode::m_classDef [private]
class representing this node (can be 0)
Definition at line 127 of file dotnode.h.
Referenced by writeBox(), and writeLabel().
m_deleted
bool DotNode::m_deleted = false [private]
used to mark a node as deleted
Definition at line 123 of file dotnode.h.
Referenced by deleteNode().
m_distance
int DotNode::m_distance = 1000 [private]
shortest path to the root node
Definition at line 130 of file dotnode.h.
Referenced by distance(), and setDistance().
m_edgeInfo
EdgeInfoVector DotNode::m_edgeInfo [private]
edge info for each child
Definition at line 122 of file dotnode.h.
Referenced by addChild(), edgeInfo(), write(), writeDEF(), writeDocbook(), writeLabel(), and writeXML().
m_hasDoc
bool DotNode::m_hasDoc = false [private]
used to mark a node as documented
Definition at line 125 of file dotnode.h.
Referenced by hasDocumentation(), and markHasDocumentation().
m_isRoot
bool DotNode::m_isRoot [private]
indicates if this is a root node
Definition at line 126 of file dotnode.h.
Referenced by writeBox(), and writeLabel().
m_label
QCString DotNode::m_label [private]
label text
Definition at line 117 of file dotnode.h.
Referenced by label(), renumberNodes(), writeDEF(), writeDocbook(), writeLabel(), and writeXML().
m_number
int DotNode::m_number [private]
Definition at line 116 of file dotnode.h.
Referenced by number(), renumberNodes(), writeArrow(), writeBox(), writeDEF(), writeDocbook(), and writeXML().
m_parents
DotNodeRefVector DotNode::m_parents [private]
list of parent nodes (incoming arrows)
Definition at line 120 of file dotnode.h.
Referenced by addParent(), clearWriteFlag(), colorConnectedNodes(), deleteNode(), findParent(), parents(), removeParent(), renumberNodes(), and write().
m_renumbered
bool DotNode::m_renumbered = false [private]
indicates if the node has been renumbered (to prevent endless loops)
Definition at line 131 of file dotnode.h.
Referenced by isRenumbered(), and markRenumbered().
m_subgraphId
int DotNode::m_subgraphId = -1 [private]
Definition at line 132 of file dotnode.h.
Referenced by setSubgraphId(), and subgraphId().
m_tooltip
QCString DotNode::m_tooltip [private]
node's tooltip
Definition at line 118 of file dotnode.h.
Referenced by writeBox().
m_truncated
TruncState DotNode::m_truncated = Unknown [private]
does the node have non-visible children/parents
Definition at line 129 of file dotnode.h.
Referenced by isTruncated(), markAsTruncated(), write(), and writeLabel().
m_url
QCString DotNode::m_url [private]
url of the node (format: remote$local)
Definition at line 119 of file dotnode.h.
Referenced by writeBox(), writeDEF(), writeDocbook(), writeUrl(), and writeXML().
m_visible
bool DotNode::m_visible = false [private]
is the node visible in the output
Definition at line 128 of file dotnode.h.
Referenced by isVisible(), markAsVisible(), and write().
m_written
bool DotNode::m_written = false [mutable], [private]
used to mark a node as written
Definition at line 124 of file dotnode.h.
Referenced by clearWriteFlag(), isWritten(), and write().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dotnode.h
doxygen/src/dotnode.h
doxygen/build/doxygen/src/dotnode.cpp
doxygen/src/dotnode.cpp