CommentScanner Class Reference
#include <commentscan.h>
Classes
struct Private
Public Member Functions
CommentScanner ()
~CommentScanner ()
bool parseCommentBlock (OutlineParserInterface *parser, Entry *curEntry, const QCString &comment, const QCString &fileName, int &lineNr, bool isBrief, bool isJavadocStyle, bool isInbody, Protection &prot, int &position, bool &newEntryNeeded, bool markdownEnabled)
void initGroupInfo (Entry *entry)
void enterFile (const QCString &fileName, int lineNr)
void leaveFile (const QCString &fileName, int lineNr)
void enterCompound (const QCString &fileName, int line, const QCString &name)
void leaveCompound (const QCString &fileName, int line, const QCString &name)
void open (Entry *e, const QCString &fileName, int line, bool implicit=false)
void close (Entry *e, const QCString &fileName, int line, bool foundInline, bool implicit=false)
CommentScanner ()
~CommentScanner ()
bool parseCommentBlock (OutlineParserInterface *parser, Entry *curEntry, const QCString &comment, const QCString &fileName, int &lineNr, bool isBrief, bool isJavadocStyle, bool isInbody, Protection &prot, int &position, bool &newEntryNeeded, bool markdownEnabled)
void initGroupInfo (Entry *entry)
void enterFile (const QCString &fileName, int lineNr)
void leaveFile (const QCString &fileName, int lineNr)
void enterCompound (const QCString &fileName, int line, const QCString &name)
void leaveCompound (const QCString &fileName, int line, const QCString &name)
void open (Entry *e, const QCString &fileName, int line, bool implicit=false)
void close (Entry *e, const QCString &fileName, int line, bool foundInline, bool implicit=false)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 28 of file commentscan.h.
Constructor & Destructor Documentation
CommentScanner() [1/2]
CommentScanner::CommentScanner ()
Definition at line 3643 of file commentscan.l.
                               : p(std::make_unique<Private>())
{
  commentscanYYlex_init_extra(&p->extra,&p->yyscanner);
#ifdef FLEX_DEBUG
  commentscanYYset_debug(1,p->yyscanner);
#endif
}
References p.
 CommentScanner() [1/2]
CommentScanner::~CommentScanner ()
Definition at line 3651 of file commentscan.l.
{
  commentscanYYlex_destroy(p->yyscanner);
}
References p.
CommentScanner() [2/2]
CommentScanner::CommentScanner ()
 CommentScanner() [2/2]
CommentScanner::~CommentScanner ()
Member Function Documentation
close() [1/2]
void CommentScanner::close (Entry * e, const QCString & fileName, int line, bool foundInline, bool implicit = false)
Definition at line 3851 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->docGroup.close(e,fileName,lineNr,foundInline,implicit);
}
References e, and p.
close() [2/2]
void CommentScanner::close (Entry * e, const QCString & fileName, int line, bool foundInline, bool implicit = false)
enterCompound() [1/2]
void CommentScanner::enterCompound (const QCString & fileName, int line, const QCString & name)
Definition at line 3833 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->docGroup.enterCompound(fileName,lineNr,name);
}
References setup::name, and p.
enterCompound() [2/2]
void CommentScanner::enterCompound (const QCString & fileName, int line, const QCString & name)
enterFile() [1/2]
void CommentScanner::enterFile (const QCString & fileName, int lineNr)
Definition at line 3821 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->docGroup.enterFile(fileName,lineNr);
}
References p.
enterFile() [2/2]
void CommentScanner::enterFile (const QCString & fileName, int lineNr)
initGroupInfo() [1/2]
void CommentScanner::initGroupInfo (Entry * entry)
Definition at line 3815 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->docGroup.initGroupInfo(entry);
}
References p.
initGroupInfo() [2/2]
void CommentScanner::initGroupInfo (Entry * entry)
leaveCompound() [1/2]
void CommentScanner::leaveCompound (const QCString & fileName, int line, const QCString & name)
Definition at line 3839 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->docGroup.leaveCompound(fileName,lineNr,name);
}
References setup::name, and p.
leaveCompound() [2/2]
void CommentScanner::leaveCompound (const QCString & fileName, int line, const QCString & name)
leaveFile() [1/2]
void CommentScanner::leaveFile (const QCString & fileName, int lineNr)
Definition at line 3827 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->docGroup.leaveFile(fileName,lineNr);
}
References p.
leaveFile() [2/2]
void CommentScanner::leaveFile (const QCString & fileName, int lineNr)
open() [1/2]
void CommentScanner::open (Entry * e, const QCString & fileName, int line, bool implicit = false)
Definition at line 3845 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->docGroup.open(e,fileName,lineNr,implicit);
}
References e, and p.
open() [2/2]
void CommentScanner::open (Entry * e, const QCString & fileName, int line, bool implicit = false)
parseCommentBlock() [1/2]
bool CommentScanner::parseCommentBlock (OutlineParserInterface * parser, Entry * curEntry, const QCString & comment, const QCString & fileName, int & lineNr, bool isBrief, bool isJavadocStyle, bool isInbody, Protection & prot, int & position, bool & newEntryNeeded, bool markdownEnabled)
Invokes the comment block parser with the request to parse a single comment block.
Parameters
 in parser The language parse that invoked this function. The comment block parse may invoke ParserInterface::parsePrototype() in order to parse the argument of a @fn command.
 in curEntry The Entry to which the comment block belongs. Any information (like documentation) that is found in the comment block will be stored in this entry.
 in comment A string representing the actual comment block. Note that leading *'s are already stripped from the comment block.
 in fileName The name of the file in which the comment is found. Mainly used for producing warnings.
 in,out lineNr The line number at which the comment block was found. When the function returns it will be set to the last line parsed.
 in isBrief TRUE iff this comment block represents a brief description.
 in isJavadocStyle TRUE iff this comment block is in `Javadoc` style. This means that it starts as a brief description until the end of the sentences is found and then proceeds as a detailed description.
 in isInbody TRUE iff this comment block is located in the body of a function.
 in,out prot The protection level in which this comment block was found. Commands in the comment block may override this.
 in,out position The character position within comment where the comment block starts. Typically used in case the comment block contains multiple structural commands.
 out newEntryNeeded Boolean that is TRUE if the comment block parser finds that a the comment block finishes the entry and a new one needs to be started.
 in markdownEnabled Indicates if markdown specific processing should be done.
Returns
TRUE if the comment requires further processing. The parameter newEntryNeeded will typically be true in this case and position will indicate the offset inside the comment string where to proceed parsing. FALSE indicates no further processing is needed.
Definition at line 3656 of file commentscan.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  //printf("parseCommentBlock() isBrief=%d isAutoBriefOn=%d lineNr=%d\n",
  // isBrief,isAutoBriefOn,lineNr);
  initParser(yyscanner);
  yyextra->guards = std::stack<GuardedSection>();
  yyextra->langParser = parser;
  yyextra->current = curEntry;
  yyextra->current->docLine = (lineNr > 1 ? lineNr : 1);
  if (comment.isEmpty()) return FALSE; // avoid empty strings
  yyextra->inputString = comment;
  yyextra->inputString.append(" ");
  yyextra->inputPosition = position;
  yyextra->lineNr = lineNr;
  yyextra->fileName = fileName;
  yyextra->protection = prot;
  yyextra->needNewEntry = FALSE;
  yyextra->xrefKind = XRef_None;
  yyextra->xrefAppendFlag = FALSE;
  yyextra->insidePre = FALSE;
  yyextra->parseMore = FALSE;
  yyextra->inBody = isInbody;
  yyextra->markdownSupport= markdownSupport;
  yyextra->outputXRef.resize(0);
  if (!isBrief && !isAutoBriefOn && !yyextra->current->doc.isEmpty())
  { // add newline separator between detailed comment blocks
    yyextra->current->doc += '\n';
  }
  setOutput(yyscanner, isBrief || isAutoBriefOn ? OutputBrief : OutputDoc);
  yyextra->briefEndsAtDot = isAutoBriefOn;
  yyextra->condCount = 0;
  yyextra->sectionLevel = 0;
  yyextra->spaceBeforeCmd.resize(0);
  yyextra->spaceBeforeIf.resize(0);
  printlex(yy_flex_debug, TRUE, __FILE__, !fileName.isEmpty() ? qPrint(fileName): NULL);
  if (!yyextra->current->inbodyDocs.isEmpty() && isInbody) // separate in body fragments
  {
    yyextra->current->inbodyDocs+="\n\n";
  }
  Debug::print(Debug::CommentScan,0,"-----------\nCommentScanner: %s:%d\n"
               "input=[\n%s]\n",qPrint(fileName),lineNr,qPrint(yyextra->inputString)
              );
  commentscanYYrestart(0, yyscanner);
  BEGIN(Comment);
  commentscanYYlex(yyscanner);
  setOutput(yyscanner, OutputDoc);
  if (YY_START==OverloadParam) // comment ended with \overload
  {
    addOutput(yyscanner,getOverloadDocs());
  }
  if (!yyextra->guards.empty())
  {
    warn(yyextra->fileName,yyextra->lineNr,"Documentation block ended in the middle of a conditional section!");
  }
  if (yyextra->insideParBlock)
  {
    warn(yyextra->fileName,yyextra->lineNr,
        "Documentation block ended while inside a \\parblock. Missing \\endparblock");
  }
  yyextra->current->doc=stripLeadingAndTrailingEmptyLines(yyextra->current->doc,yyextra->current->docLine);
  if (yyextra->current->section==Entry::FILEDOC_SEC && yyextra->current->doc.isEmpty())
  {
    // to allow a comment block with just a @file command.
    yyextra->current->doc="\n\n";
  }
  if (yyextra->current->section==Entry::MEMBERGRP_SEC &&
      yyextra->docGroup.isEmpty()) // @name section but no group started yet
  {
    yyextra->docGroup.open(yyextra->current,yyextra->fileName,yyextra->lineNr,true);
  }
  Debug::print(Debug::CommentScan,0,"-----------\nCommentScanner: %s:%d\noutput=[\n"
               "brief=[line=%d\n%s]\ndocs=[line=%d\n%s]\ninbody=[line=%d\n%s]\n]\n===========\n",
               qPrint(fileName),lineNr,
               yyextra->current->briefLine,qPrint(yyextra->current->brief),
               yyextra->current->docLine,qPrint(yyextra->current->doc),
               yyextra->current->inbodyLine,qPrint(yyextra->current->inbodyDocs)
              );
  checkFormula(yyscanner);
  prot = yyextra->protection;
  yyextra->docGroup.addDocs(curEntry);
  newEntryNeeded = yyextra->needNewEntry;
  // if we did not proceed during this call, it does not make
  // sense to continue, since we get stuck. See bug 567346 for situations
  // were this happens
  if (yyextra->parseMore && position==yyextra->inputPosition) yyextra->parseMore=FALSE;
  if (yyextra->parseMore) position=yyextra->inputPosition; else position=0;
  lineNr = yyextra->lineNr;
  //printf("position=%d yyextra->parseMore=%d newEntryNeeded=%d\n",
  // position,yyextra->parseMore,newEntryNeeded);
  printlex(yy_flex_debug, FALSE, __FILE__, !fileName.isEmpty() ? qPrint(fileName): NULL);
  return yyextra->parseMore;
}
References addOutput(), checkFormula(), comment, Debug::CommentScan, Entry::docLine, FALSE, Entry::FILEDOC_SEC, getOverloadDocs(), initParser(), QCString::isEmpty(), Entry::MEMBERGRP_SEC, OutputBrief, OutputDoc, p, Debug::print(), printlex(), qPrint(), setOutput(), stripLeadingAndTrailingEmptyLines(), TRUE, warn(), and XRef_None.
parseCommentBlock() [2/2]
bool CommentScanner::parseCommentBlock (OutlineParserInterface * parser, Entry * curEntry, const QCString & comment, const QCString & fileName, int & lineNr, bool isBrief, bool isJavadocStyle, bool isInbody, Protection & prot, int & position, bool & newEntryNeeded, bool markdownEnabled)
Invokes the comment block parser with the request to parse a single comment block.
Parameters
 in parser The language parse that invoked this function. The comment block parse may invoke ParserInterface::parsePrototype() in order to parse the argument of a @fn command.
 in curEntry The Entry to which the comment block belongs. Any information (like documentation) that is found in the comment block will be stored in this entry.
 in comment A string representing the actual comment block. Note that leading *'s are already stripped from the comment block.
 in fileName The name of the file in which the comment is found. Mainly used for producing warnings.
 in,out lineNr The line number at which the comment block was found. When the function returns it will be set to the last line parsed.
 in isBrief TRUE iff this comment block represents a brief description.
 in isJavadocStyle TRUE iff this comment block is in `Javadoc` style. This means that it starts as a brief description until the end of the sentences is found and then proceeds as a detailed description.
 in isInbody TRUE iff this comment block is located in the body of a function.
 in,out prot The protection level in which this comment block was found. Commands in the comment block may override this.
 in,out position The character position within comment where the comment block starts. Typically used in case the comment block contains multiple structural commands.
 out newEntryNeeded Boolean that is TRUE if the comment block parser finds that a the comment block finishes the entry and a new one needs to be started.
 in markdownEnabled Indicates if markdown specific processing should be done.
Returns
TRUE if the comment requires further processing. The parameter newEntryNeeded will typically be true in this case and position will indicate the offset inside the comment string where to proceed parsing. FALSE indicates no further processing is needed.
Member Data Documentation
p
std::unique_ptr< Private > CommentScanner::p [private]
Definition at line 92 of file commentscan.h.
Referenced by close(), CommentScanner(), enterCompound(), enterFile(), initGroupInfo(), leaveCompound(), leaveFile(), open(), parseCommentBlock(), and ~CommentScanner().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/commentscan.h
doxygen/src/commentscan.h
doxygen/build/doxygen/src/commentscan.l
doxygen/src/commentscan.l