ParserManager Class Reference
Manages programming language parsers.
#include <parserintf.h>
Classes
struct ParserPair
Public Member Functions
ParserManager (OutlineParserFactory outlineParserFactory, CodeParserFactory codeParserFactory)
void registerParser (const QCString &name, OutlineParserFactory outlineParserFactory, CodeParserFactory codeParserFactory)
bool registerExtension (const QCString &extension, const QCString &parserName)
std::unique_ptr< OutlineParserInterface > getOutlineParser (const QCString &extension)
std::unique_ptr< CodeParserInterface > getCodeParser (const QCString &extension)
CodeParserFactory & getCodeParserFactory (const QCString &extension)
QCString getParserName (const QCString &extension)
ParserManager (OutlineParserFactory outlineParserFactory, CodeParserFactory codeParserFactory)
void registerParser (const QCString &name, OutlineParserFactory outlineParserFactory, CodeParserFactory codeParserFactory)
bool registerExtension (const QCString &extension, const QCString &parserName)
std::unique_ptr< OutlineParserInterface > getOutlineParser (const QCString &extension)
std::unique_ptr< CodeParserInterface > getCodeParser (const QCString &extension)
CodeParserFactory & getCodeParserFactory (const QCString &extension)
QCString getParserName (const QCString &extension)
Private Member Functions
ParserPair & getParsers (const QCString &extension)
ParserPair & getParsers (const QCString &extension)
Private Attributes
std::map< std::string, ParserPair > m_parsers
std::map< std::string, ParserPair & > m_extensions
ParserPair m_defaultParsers
Detailed Description
Manages programming language parsers.
This class manages the language parsers in the system. One can register parsers, and obtain a parser given a file extension.
Definition at line 145 of file parserintf.h.
Constructor & Destructor Documentation
ParserManager() [1/2]
ParserManager::ParserManager (OutlineParserFactory outlineParserFactory, CodeParserFactory codeParserFactory) [inline]
Create the parser manager
Parameters
outlineParserFactory the fallback outline parser factory to use for unknown extensions
codeParserFactory the fallback code parser factory to use for unknown extensions
Definition at line 165 of file parserintf.h.
      : m_defaultParsers(outlineParserFactory,codeParserFactory, QCString())
    {
    }
ParserManager() [2/2]
ParserManager::ParserManager (OutlineParserFactory outlineParserFactory, CodeParserFactory codeParserFactory) [inline]
Create the parser manager
Parameters
outlineParserFactory the fallback outline parser factory to use for unknown extensions
codeParserFactory the fallback code parser factory to use for unknown extensions
Definition at line 165 of file parserintf.h.
      : m_defaultParsers(outlineParserFactory,codeParserFactory, QCString())
    {
    }
Member Function Documentation
getCodeParser() [1/2]
std::unique_ptr< CodeParserInterface > ParserManager::getCodeParser (const QCString & extension) [inline]
Gets the interface to the parser associated with a given extension. If there is no parser explicitly registered for the supplied extension, the interface to the default parser will be returned.
Definition at line 217 of file parserintf.h.
    {
      auto factory = getCodeParserFactory(extension);
      return factory();
    }
References getCodeParserFactory().
Referenced by MemberDefImpl::_writeMultiLineInitializer(), findXRefSymbols(), generateExampleDocs(), parseCode(), FileDefImpl::parseSource(), ConceptDefImpl::writeDefinition(), DefinitionImpl::writeInlineCode(), VhdlDocGen::writeSource(), FileDefImpl::writeSourceBody(), and writeXMLCodeBlock().
getCodeParser() [2/2]
std::unique_ptr< CodeParserInterface > ParserManager::getCodeParser (const QCString & extension) [inline]
Gets the interface to the parser associated with a given extension. If there is no parser explicitly registered for the supplied extension, the interface to the default parser will be returned.
Definition at line 217 of file parserintf.h.
    {
      auto factory = getCodeParserFactory(extension);
      return factory();
    }
References getCodeParserFactory().
getCodeParserFactory() [1/2]
CodeParserFactory & ParserManager::getCodeParserFactory (const QCString & extension) [inline]
Get the factory for create code parser objects with a given extension.
Definition at line 224 of file parserintf.h.
    {
      return getParsers(extension).codeParserFactory;
    }
References ParserManager::ParserPair::codeParserFactory, and getParsers().
Referenced by getCodeParser(), and DocVisitor::getCodeParser().
getCodeParserFactory() [2/2]
CodeParserFactory & ParserManager::getCodeParserFactory (const QCString & extension) [inline]
Get the factory for create code parser objects with a given extension.
Definition at line 224 of file parserintf.h.
    {
      return getParsers(extension).codeParserFactory;
    }
References ParserManager::ParserPair::codeParserFactory, and getParsers().
getOutlineParser() [1/2]
std::unique_ptr< OutlineParserInterface > ParserManager::getOutlineParser (const QCString & extension) [inline]
Gets the interface to the parser associated with a given extension. If there is no parser explicitly registered for the supplied extension, the interface to the default parser will be returned.
Definition at line 208 of file parserintf.h.
    {
      return getParsers(extension).outlineParserFactory();
    }
References getParsers(), and ParserManager::ParserPair::outlineParserFactory.
Referenced by VhdlDocGen::createFlowChart(), getParserForFile(), and MarkdownOutlineParser::parsePrototype().
getOutlineParser() [2/2]
std::unique_ptr< OutlineParserInterface > ParserManager::getOutlineParser (const QCString & extension) [inline]
Gets the interface to the parser associated with a given extension. If there is no parser explicitly registered for the supplied extension, the interface to the default parser will be returned.
Definition at line 208 of file parserintf.h.
    {
      return getParsers(extension).outlineParserFactory();
    }
References getParsers(), and ParserManager::ParserPair::outlineParserFactory.
getParserName() [1/2]
QCString ParserManager::getParserName (const QCString & extension) [inline]
Gets the name of the parser associated with given extension. If there is no parser explicitly registered for the supplied extension, te empty string will be reurned.
Definition at line 233 of file parserintf.h.
    {
      return getParsers(extension).parserName;
    }
References getParsers(), and ParserManager::ParserPair::parserName.
Referenced by convertFileNameFortranParserCode().
getParserName() [2/2]
QCString ParserManager::getParserName (const QCString & extension) [inline]
Gets the name of the parser associated with given extension. If there is no parser explicitly registered for the supplied extension, te empty string will be reurned.
Definition at line 233 of file parserintf.h.
    {
      return getParsers(extension).parserName;
    }
References getParsers(), and ParserManager::ParserPair::parserName.
getParsers() [1/2]
ParserPair & ParserManager::getParsers (const QCString & extension) [inline], [private]
Definition at line 239 of file parserintf.h.
    {
      QCString ext = extension.lower();
      if (ext.isEmpty()) ext=".no_extension";
      auto it = m_extensions.find(ext.data());
      if (it==m_extensions.end() && ext.length()>4)
      {
        it = m_extensions.find(ext.left(4).data());
      }
      return it!=m_extensions.end() ? it->second : m_defaultParsers;
    }
References QCString::data(), QCString::isEmpty(), QCString::left(), QCString::length(), QCString::lower(), m_defaultParsers, and m_extensions.
Referenced by getCodeParserFactory(), getOutlineParser(), and getParserName().
getParsers() [2/2]
ParserPair & ParserManager::getParsers (const QCString & extension) [inline], [private]
Definition at line 239 of file parserintf.h.
    {
      QCString ext = extension.lower();
      if (ext.isEmpty()) ext=".no_extension";
      auto it = m_extensions.find(ext.data());
      if (it==m_extensions.end() && ext.length()>4)
      {
        it = m_extensions.find(ext.left(4).data());
      }
      return it!=m_extensions.end() ? it->second : m_defaultParsers;
    }
References QCString::data(), QCString::isEmpty(), QCString::left(), QCString::length(), QCString::lower(), m_defaultParsers, and m_extensions.
registerExtension() [1/2]
bool ParserManager::registerExtension (const QCString & extension, const QCString & parserName) [inline]
Registers a file extension with a parser with name parserName. Returns TRUE if the extension was successfully registered.
Definition at line 188 of file parserintf.h.
    {
      if (parserName.isEmpty() || extension.isEmpty()) return FALSE;
      const auto &parserIt = m_parsers.find(parserName.str());
      if (parserIt == m_parsers.end()) return FALSE;
      auto extensionIt = m_extensions.find(extension.str());
      if (extensionIt != m_extensions.end()) // extension already exists
      {
        m_extensions.erase(extensionIt); // remove it (e.g. user specified extension overrules built in one)
      }
      m_extensions.emplace(extension.str(),parserIt->second); // add new mapping
      return TRUE;
    }
References FALSE, QCString::isEmpty(), m_extensions, m_parsers, QCString::str(), and TRUE.
registerExtension() [2/2]
bool ParserManager::registerExtension (const QCString & extension, const QCString & parserName) [inline]
Registers a file extension with a parser with name parserName. Returns TRUE if the extension was successfully registered.
Definition at line 188 of file parserintf.h.
    {
      if (parserName.isEmpty() || extension.isEmpty()) return FALSE;
      const auto &parserIt = m_parsers.find(parserName.str());
      if (parserIt == m_parsers.end()) return FALSE;
      auto extensionIt = m_extensions.find(extension.str());
      if (extensionIt != m_extensions.end()) // extension already exists
      {
        m_extensions.erase(extensionIt); // remove it (e.g. user specified extension overrules built in one)
      }
      m_extensions.emplace(extension.str(),parserIt->second); // add new mapping
      return TRUE;
    }
References FALSE, QCString::isEmpty(), m_extensions, m_parsers, QCString::str(), and TRUE.
registerParser() [1/2]
void ParserManager::registerParser (const QCString & name, OutlineParserFactory outlineParserFactory, CodeParserFactory codeParserFactory) [inline]
Registers an additional parser.
Parameters
 in name A symbolic name of the parser, i.e. `c`, `python`, `fortran`, `vhdl`, ...
 in outlineParserFactory A factory method to create a language parser (scanner) that is to be used for the given name.
 in codeParserFactory A factory method to create a code parser that is to be used for the given name.
Definition at line 179 of file parserintf.h.
    {
      m_parsers.emplace(name.str(),ParserPair(outlineParserFactory,codeParserFactory,name));
    }
References m_parsers, and setup::name.
Referenced by initDoxygen().
registerParser() [2/2]
void ParserManager::registerParser (const QCString & name, OutlineParserFactory outlineParserFactory, CodeParserFactory codeParserFactory) [inline]
Registers an additional parser.
Parameters
 in name A symbolic name of the parser, i.e. `c`, `python`, `fortran`, `vhdl`, ...
 in outlineParserFactory A factory method to create a language parser (scanner) that is to be used for the given name.
 in codeParserFactory A factory method to create a code parser that is to be used for the given name.
Definition at line 179 of file parserintf.h.
    {
      m_parsers.emplace(name.str(),ParserPair(outlineParserFactory,codeParserFactory,name));
    }
References m_parsers, and setup::name.
Member Data Documentation
m_defaultParsers
ParserPair ParserManager::m_defaultParsers [private]
Definition at line 253 of file parserintf.h.
Referenced by getParsers().
m_extensions
std::map< std::string, ParserPair & > ParserManager::m_extensions [private]
Definition at line 252 of file parserintf.h.
Referenced by getParsers(), and registerExtension().
m_parsers
std::map< std::string, ParserPair > ParserManager::m_parsers [private]
Definition at line 251 of file parserintf.h.
Referenced by registerExtension(), and registerParser().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/parserintf.h
doxygen/src/parserintf.h