Test< T, i > Class Template Reference
A Test class.
#include `inc/class.h`
Public Member Functions
Test ()
Test (const Test &)
void test ()
void example ()
a member function
void example ()
An example member function.
int example (int p1, int p2) throw (std::out_of_range)
void ungrouped ()
void drawRect (int, int, int, int)
void drawRect (const Rect &r)
void drawRect (const Point &topLeft, const Point &bottomRight)
void method ()
template<typename... Args>
void func (int p, Args... args) const
template<typename... Args>
void func (int p, Args... args) const
Test ()
Test (const Test &)
void test ()
void example ()
a member function
void example ()
An example member function.
int example (int p1, int p2) throw (std::out_of_range)
void ungrouped ()
void drawRect (int, int, int, int)
void drawRect (const Rect &r)
void drawRect (const Point &topLeft, const Point &bottomRight)
void method ()
template<typename... Args>
void func (int p, Args... args) const
template<typename... Args>
void func (int p, Args... args) const
 A group of functions.
void foo ()
void bar ()
void foo ()
void bar ()
Related Functions
(Note that these are not member functions.)
void function ()
void another ()
Detailed Description
template<class T, int i = 100>
class Test< T, i >
A Test class.
A short description.
This is a test class.
A template class
Test
Test This is part of testing
A test class.
More details about this class.
A Test class. More details about this class.
Template Parameters
T A template parameter.
A test
A test class
See also
Test::method()
Test
Test This is part of testing
Some details about the Test class.
More text.
Definition at line 3 of file class.h.
Constructor & Destructor Documentation
Test() [1/4]
template<class T , int i>
Test< T, i >::Test
The constructor of the template class
Definition at line 25 of file templ.cpp.
{}
Test() [2/4]
template<class T , int i>
Test< T, i >::Test (const Test< T, i > & t)
The copy constructor
Definition at line 28 of file templ.cpp.
{}
Test() [3/4]
template<class T , int i = 100>
Test< T, i >::Test ()
Test() [4/4]
template<class T , int i = 100>
Test< T, i >::Test (const Test< T, i > &)
Member Function Documentation
bar() [1/2]
template<class T , int i = 100>
void Test< T, i >::bar ()
bar function
bar() [2/2]
template<class T , int i = 100>
void Test< T, i >::bar ()
bar function
drawRect() [1/6]
template<class T , int i = 100>
void Test< T, i >::drawRect (const Point & topLeft, const Point & bottomRight)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
More text.
Definition at line 18 of file 041_overload.cpp.
{}
drawRect() [2/6]
template<class T , int i = 100>
void Test< T, i >::drawRect (const Point & topLeft, const Point & bottomRight)
drawRect() [3/6]
template<class T , int i = 100>
void Test< T, i >::drawRect (const Rect & r)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 13 of file 041_overload.cpp.
{}
drawRect() [4/6]
template<class T , int i = 100>
void Test< T, i >::drawRect (const Rect & r)
drawRect() [5/6]
template<class T , int i = 100>
void Test< T, i >::drawRect (int x, int y, int w, int h)
This command draws a rectangle with a left upper corner at (x , y), width w and height h.
Definition at line 12 of file 041_overload.cpp.
{}
drawRect() [6/6]
template<class T , int i = 100>
void Test< T, i >::drawRect (int , int , int , int)
example() [1/6]
template<class T , int i = 100>
void Test< T, i >::example ()
a member function
Definition at line 20 of file 025_example.cpp.
{}
Referenced by main().
example() [2/6]
template<class T , int i = 100>
void Test< T, i >::example ()
An example member function.
More details about this function.
example() [3/6]
template<class T , int i = 100>
void Test< T, i >::example ()
a member function
example() [4/6]
template<class T , int i = 100>
void Test< T, i >::example ()
An example member function.
More details about this function.
example() [5/6]
template<class T , int i = 100>
int Test< T, i >::example (int p1, int p2) throw (std::out_of_range)
An example member function.
Parameters
p1 First parameter.
p2 Second parameter.
Exceptions
std::out_of_range parameter is out of range.
Return values
0 if p1 and p2 are equal
-1 if p1 is smaller than p2
1 if p1 is bigger than p2
example() [6/6]
template<class T , int i = 100>
int Test< T, i >::example (int p1, int p2) throw (std::out_of_range)
An example member function.
Parameters
p1 First parameter.
p2 Second parameter.
Exceptions
std::out_of_range parameter is out of range.
Return values
0 if p1 and p2 are equal
-1 if p1 is smaller than p2
1 if p1 is bigger than p2
foo() [1/2]
template<class T , int i = 100>
void Test< T, i >::foo ()
foo function
foo() [2/2]
template<class T , int i = 100>
void Test< T, i >::foo ()
foo function
func() [1/4]
template<class T , int i = 100>
template<typename... Args>
void Test< T, i >::func (int p, Args... args) const
A variadic template method
func() [2/4]
template<class T , int i = 100>
template<typename... Args>
void Test< T, i >::func (int p, Args... args) const
A variadic template method
func() [3/4]
template<class T , int i = 100>
template<typename... Args>
void Test< T, i >::func (int p, Args... args) const
A variadic template method
func() [4/4]
template<class T , int i = 100>
template<typename... Args>
void Test< T, i >::func (int p, Args... args) const
A variadic template method
method() [1/2]
template<class T , int i = 100>
void Test< T, i >::method ()
A method
method() [2/2]
template<class T , int i = 100>
void Test< T, i >::method ()
A method
test() [1/2]
template<class T , int i = 100>
void Test< T, i >::test ()
Test
Test more things to test.
Referenced by runtests.Tester::__init__(), runtests.Tester::get_config(), and runtests.Tester::prepare_test().
test() [2/2]
template<class T , int i = 100>
void Test< T, i >::test ()
Test
Test more things to test.
Referenced by runtests.Tester::__init__(), runtests.Tester::get_config(), and runtests.Tester::prepare_test().
ungrouped() [1/2]
template<class T , int i = 100>
void Test< T, i >::ungrouped ()
ungrouped function
ungrouped() [2/2]
template<class T , int i = 100>
void Test< T, i >::ungrouped ()
ungrouped function
Friends And Related Function Documentation
another()
template<class T , int i = 100>
void another () [related]
Another function
function()
template<class T , int i = 100>
void function () [related]
A function.
See also
another()
The documentation for this class was generated from the following files:
doxygen/build/doxygen/examples/class.h
doxygen/build/doxygen/examples/templ.cpp
doxygen/build/doxygen/testing/009_bug.cpp
doxygen/build/doxygen/testing/021_dontinclude.cpp
doxygen/build/doxygen/testing/025_example.cpp
doxygen/build/doxygen/testing/026_exception.cpp
doxygen/build/doxygen/testing/039_name.cpp
doxygen/build/doxygen/testing/041_overload.cpp
doxygen/build/doxygen/testing/046_related.cpp
doxygen/build/doxygen/testing/069_link_variadic_template.cpp
doxygen/build/doxygen/testing/070_ref_variadic_template.cpp
doxygen/examples/templ.cpp
doxygen/testing/009_bug.cpp
doxygen/testing/021_dontinclude.cpp
doxygen/testing/025_example.cpp
doxygen/testing/026_exception.cpp
doxygen/testing/039_name.cpp
doxygen/testing/041_overload.cpp
doxygen/testing/046_related.cpp
doxygen/testing/069_link_variadic_template.cpp
doxygen/testing/070_ref_variadic_template.cpp