ModuleContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
ModuleContext (const GroupDef *)
virtual ~ModuleContext ()
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
ModuleContext (const GroupDef *)
virtual ~ModuleContext ()
Static Public Member Functions
static TemplateStructIntfPtr alloc (const GroupDef *gd)
static TemplateStructIntfPtr alloc (const GroupDef *gd)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 338 of file context.h.
Constructor & Destructor Documentation
ModuleContext() [1/2]
ModuleContext::ModuleContext (const GroupDef * gd)
Definition at line 4972 of file context.cpp.
                                               : p(std::make_unique<Private>(gd))
{
}
 ModuleContext() [1/2]
ModuleContext::~ModuleContext () [virtual]
Definition at line 4976 of file context.cpp.
{
}
ModuleContext() [2/2]
ModuleContext::ModuleContext (const GroupDef *)
 ModuleContext() [2/2]
virtual ModuleContext::~ModuleContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateStructIntfPtr ModuleContext::alloc (const GroupDef * gd) [inline], [static]
Definition at line 341 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<ModuleContext>(gd)); }
Referenced by ModuleListContext::Private::addModules(), NestingNodeContext::Private::createModule(), ModuleContext::Private::createModules(), and DefinitionContext< T >::createPartOfGroups().
alloc() [2/2]
static TemplateStructIntfPtr ModuleContext::alloc (const GroupDef * gd) [inline], [static]
Definition at line 341 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<ModuleContext>(gd)); }
fields() [1/2]
StringVector ModuleContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 4985 of file context.cpp.
{
  return p->fields();
}
References p.
fields() [2/2]
virtual StringVector ModuleContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant ModuleContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 4980 of file context.cpp.
{
  return p->get(n);
}
References n, and p.
get() [2/2]
virtual TemplateVariant ModuleContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Member Data Documentation
p
std::unique_ptr< Private > ModuleContext::p [private]
Definition at line 353 of file context.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp