NestingNodeContext::Private Class Reference
Public Member Functions
Private (const NestingNodeContext *parent, const NestingNodeContext *thisNode, ContextTreeType type, const Definition *d, int index, int level, bool addCls, bool addCps, bool inherit, bool hideSuper, ClassDefSet &visitedClasses)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant id () const
Private (const NestingNodeContext *parent, const NestingNodeContext *thisNode, ContextTreeType type, const Definition *d, int index, int level, bool addCls, bool addCps, bool inherit, bool hideSuper, ClassDefSet &visitedClasses)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant id () const
Private Member Functions
TemplateVariant isLeafNode () const
TemplateVariant children () const
TemplateVariant members () const
TemplateVariant getClass () const
TemplateVariant getNamespace () const
TemplateVariant getDir () const
TemplateVariant getFile () const
TemplateVariant getPage () const
TemplateVariant getModule () const
TemplateVariant getMember () const
TemplateVariant level () const
TemplateVariant brief () const
TemplateVariant isLinkable () const
TemplateVariant anchor () const
TemplateVariant fileName () const
TemplateVariant isReference () const
TemplateVariant externalReference () const
TemplateVariant name () const
TemplateVariant partOfGroup () const
QCString relPathAsString () const
void addClasses (bool inherit, bool hideSuper, ClassDefSet &visitedClasses)
void addConcepts (ClassDefSet &visitedClasses)
void addNamespaces (bool addClasses, bool addConcepts, ClassDefSet &visitedClasses)
void addDirFiles (ClassDefSet &visitedClasses)
void addPages (ClassDefSet &visitedClasses)
void addModules (ClassDefSet &visitedClasses)
void addMembers (ClassDefSet &visitedClasses)
TemplateVariant createClass () const
TemplateVariant createNamespace () const
TemplateVariant createDir () const
TemplateVariant createFile () const
TemplateVariant createPage () const
TemplateVariant createModule () const
TemplateVariant createMember () const
TemplateVariant createBrief () const
TemplateVariant isLeafNode () const
TemplateVariant children () const
TemplateVariant members () const
TemplateVariant getClass () const
TemplateVariant getNamespace () const
TemplateVariant getDir () const
TemplateVariant getFile () const
TemplateVariant getPage () const
TemplateVariant getModule () const
TemplateVariant getMember () const
TemplateVariant level () const
TemplateVariant brief () const
TemplateVariant isLinkable () const
TemplateVariant anchor () const
TemplateVariant fileName () const
TemplateVariant isReference () const
TemplateVariant externalReference () const
TemplateVariant name () const
TemplateVariant partOfGroup () const
QCString relPathAsString () const
void addClasses (bool inherit, bool hideSuper, ClassDefSet &visitedClasses)
void addConcepts (ClassDefSet &visitedClasses)
void addNamespaces (bool addClasses, bool addConcepts, ClassDefSet &visitedClasses)
void addDirFiles (ClassDefSet &visitedClasses)
void addPages (ClassDefSet &visitedClasses)
void addModules (ClassDefSet &visitedClasses)
void addMembers (ClassDefSet &visitedClasses)
TemplateVariant createClass () const
TemplateVariant createNamespace () const
TemplateVariant createDir () const
TemplateVariant createFile () const
TemplateVariant createPage () const
TemplateVariant createModule () const
TemplateVariant createMember () const
TemplateVariant createBrief () const
Private Attributes
const NestingNodeContext * m_parent
ContextTreeType m_type
const Definition * m_def
std::shared_ptr< NestingContext > m_children
std::shared_ptr< NestingContext > m_members
int m_level
int m_index
CachedItem< TemplateVariant, Private, &Private::createClass > m_class
CachedItem< TemplateVariant, Private, &Private::createNamespace > m_namespace
CachedItem< TemplateVariant, Private, &Private::createDir > m_dir
CachedItem< TemplateVariant, Private, &Private::createFile > m_file
CachedItem< TemplateVariant, Private, &Private::createPage > m_page
CachedItem< TemplateVariant, Private, &Private::createModule > m_module
CachedItem< TemplateVariant, Private, &Private::createMember > m_member
CachedItem< TemplateVariant, Private, &Private::createBrief > m_brief
Static Private Attributes
static const PropertyMap< NestingNodeContext::Private > s_inst
Detailed Description
Definition at line 5290 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
NestingNodeContext::Private::Private (const NestingNodeContext * parent, const NestingNodeContext * thisNode, ContextTreeType type, const Definition * d, int index, int level, bool addCls, bool addCps, bool inherit, bool hideSuper, ClassDefSet & visitedClasses) [inline]
Definition at line 5293 of file context.cpp.
      : m_parent(parent), m_type(type), m_def(d), m_level(level), m_index(index)
    {
      m_children = std::dynamic_pointer_cast<NestingContext>(NestingContext::alloc(thisNode,m_type,level+1));
      m_members = std::dynamic_pointer_cast<NestingContext>(NestingContext::alloc(thisNode,m_type,level+1));
      addNamespaces(addCls,addCps,visitedClasses);
      addClasses(inherit,hideSuper,visitedClasses);
      addDirFiles(visitedClasses);
      addPages(visitedClasses);
      addModules(visitedClasses);
      addMembers(visitedClasses);
    }
References addClasses(), addDirFiles(), addMembers(), addModules(), addNamespaces(), addPages(), NestingContext::alloc(), level(), m_children, m_members, and m_type.
Private() [2/2]
NestingNodeContext::Private::Private (const NestingNodeContext * parent, const NestingNodeContext * thisNode, ContextTreeType type, const Definition * d, int index, int level, bool addCls, bool addCps, bool inherit, bool hideSuper, ClassDefSet & visitedClasses) [inline]
Definition at line 5293 of file context.cpp.
      : m_parent(parent), m_type(type), m_def(d), m_level(level), m_index(index)
    {
      m_children = std::dynamic_pointer_cast<NestingContext>(NestingContext::alloc(thisNode,m_type,level+1));
      m_members = std::dynamic_pointer_cast<NestingContext>(NestingContext::alloc(thisNode,m_type,level+1));
      addNamespaces(addCls,addCps,visitedClasses);
      addClasses(inherit,hideSuper,visitedClasses);
      addDirFiles(visitedClasses);
      addPages(visitedClasses);
      addModules(visitedClasses);
      addMembers(visitedClasses);
    }
References NestingContext::alloc(), and level.
Member Function Documentation
addClasses() [1/2]
void NestingNodeContext::Private::addClasses (bool inherit, bool hideSuper, ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5365 of file context.cpp.
    {
      const ClassDef *cd = toClassDef(m_def);
      if (cd)
      {
        if (inherit)
        {
          bool hasChildren = visitedClasses.find(cd)==visitedClasses.end() &&
            !hideSuper && classHasVisibleChildren(cd);
          if (hasChildren)
          {
            visitedClasses.insert(cd);
            if (cd->getLanguage()==SrcLangExt_VHDL)
            {
              m_children->addDerivedClasses(cd->baseClasses(),false,visitedClasses);
            }
            else
            {
              m_children->addDerivedClasses(cd->subClasses(),false,visitedClasses);
            }
          }
        }
        else
        {
          m_children->addClasses(cd->getClasses(),FALSE,visitedClasses);
        }
      }
      const GroupDef *gd = toGroupDef(m_def);
      if (gd)
      {
        m_children->addClasses(gd->getClasses(),FALSE,visitedClasses);
      }
    }
References ClassDef::baseClasses(), classHasVisibleChildren(), FALSE, ClassDef::getClasses(), GroupDef::getClasses(), Definition::getLanguage(), m_children, m_def, SrcLangExt_VHDL, ClassDef::subClasses(), toClassDef(), and toGroupDef().
Referenced by addNamespaces(), and Private().
addClasses() [2/2]
void NestingNodeContext::Private::addClasses (bool inherit, bool hideSuper, ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5365 of file context.cpp.
    {
      const ClassDef *cd = toClassDef(m_def);
      if (cd)
      {
        if (inherit)
        {
          bool hasChildren = visitedClasses.find(cd)==visitedClasses.end() &&
            !hideSuper && classHasVisibleChildren(cd);
          if (hasChildren)
          {
            visitedClasses.insert(cd);
            if (cd->getLanguage()==SrcLangExt_VHDL)
            {
              m_children->addDerivedClasses(cd->baseClasses(),false,visitedClasses);
            }
            else
            {
              m_children->addDerivedClasses(cd->subClasses(),false,visitedClasses);
            }
          }
        }
        else
        {
          m_children->addClasses(cd->getClasses(),FALSE,visitedClasses);
        }
      }
      const GroupDef *gd = toGroupDef(m_def);
      if (gd)
      {
        m_children->addClasses(gd->getClasses(),FALSE,visitedClasses);
      }
    }
References ClassDef::baseClasses(), classHasVisibleChildren(), FALSE, ClassDef::getClasses(), GroupDef::getClasses(), Definition::getLanguage(), SrcLangExt_VHDL, ClassDef::subClasses(), toClassDef(), and toGroupDef().
addConcepts() [1/2]
void NestingNodeContext::Private::addConcepts (ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5398 of file context.cpp.
    {
      const GroupDef *gd = toGroupDef(m_def);
      if (gd)
      {
        m_children->addConcepts(gd->getConcepts(),FALSE,visitedClasses);
      }
    }
References FALSE, GroupDef::getConcepts(), m_children, m_def, and toGroupDef().
Referenced by addNamespaces().
addConcepts() [2/2]
void NestingNodeContext::Private::addConcepts (ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5398 of file context.cpp.
    {
      const GroupDef *gd = toGroupDef(m_def);
      if (gd)
      {
        m_children->addConcepts(gd->getConcepts(),FALSE,visitedClasses);
      }
    }
References FALSE, GroupDef::getConcepts(), and toGroupDef().
addDirFiles() [1/2]
void NestingNodeContext::Private::addDirFiles (ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5430 of file context.cpp.
    {
      const DirDef *dd = toDirDef(m_def);
      if (dd)
      {
        m_children->addDirs(dd->subDirs(),visitedClasses);
        m_children->addFiles(dd->getFiles(),visitedClasses);
      }
      const GroupDef *gd = toGroupDef(m_def);
      if (gd)
      {
        m_children->addDirs(gd->getDirs(),visitedClasses);
      }
    }
References GroupDef::getDirs(), DirDef::getFiles(), m_children, m_def, DirDef::subDirs(), toDirDef(), and toGroupDef().
Referenced by Private().
addDirFiles() [2/2]
void NestingNodeContext::Private::addDirFiles (ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5430 of file context.cpp.
    {
      const DirDef *dd = toDirDef(m_def);
      if (dd)
      {
        m_children->addDirs(dd->subDirs(),visitedClasses);
        m_children->addFiles(dd->getFiles(),visitedClasses);
      }
      const GroupDef *gd = toGroupDef(m_def);
      if (gd)
      {
        m_children->addDirs(gd->getDirs(),visitedClasses);
      }
    }
References GroupDef::getDirs(), DirDef::getFiles(), DirDef::subDirs(), toDirDef(), and toGroupDef().
addMembers() [1/2]
void NestingNodeContext::Private::addMembers (ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5465 of file context.cpp.
    {
      if (m_type!=ContextTreeType::Module && m_def->partOfGroups().empty()) // show outside of group
      {
        if (m_def->definitionType()==Definition::TypeNamespace)
        {
          // add namespace members
          for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Namespace))
          {
            if (lde->kind()==LayoutDocEntry::MemberDef)
            {
              const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
              if (lmd)
              {
                const MemberList *ml = toNamespaceDef(m_def)->getMemberList(lmd->type);
                if (ml)
                {
                  m_members->addMembers(*ml,visitedClasses);
                }
              }
            }
          }
        }
        else if (m_def->definitionType()==Definition::TypeClass)
        {
          // add class members
          for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
          {
            if (lde->kind()==LayoutDocEntry::MemberDef)
            {
              const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
              if (lmd)
              {
                const MemberList *ml = toClassDef(m_def)->getMemberList(lmd->type);
                if (ml)
                {
                  m_members->addMembers(*ml,visitedClasses);
                }
              }
            }
          }
        }
        else if (m_def->definitionType()==Definition::TypeFile)
        {
          // add class members
          for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::File))
          {
            if (lde->kind()==LayoutDocEntry::MemberDef)
            {
              const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
              if (lmd)
              {
                const MemberList *ml = toFileDef(m_def)->getMemberList(lmd->type);
                if (ml)
                {
                  m_members->addMembers(*ml,visitedClasses);
                }
              }
            }
          }
        }
      }
      else if (m_def->definitionType()==Definition::TypeGroup && m_type==ContextTreeType::Module) // show as part of group
      {
        // add class members
        for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Group))
        {
          if (lde->kind()==LayoutDocEntry::MemberDef)
          {
            const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
            if (lmd)
            {
              const MemberList *ml = toGroupDef(m_def)->getMemberList(lmd->type);
              if (ml)
              {
                m_members->addMembers(*ml,visitedClasses);
              }
            }
          }
        }
      }
      if (m_def->definitionType()==Definition::TypeMember)
      {
        const MemberDef *md = toMemberDef(m_def);
        if (md->isEnumerate() && md->isStrong())
        {
          m_members->addMembers(md->enumFieldList(),visitedClasses);
        }
      }
    }
References LayoutDocManager::Class, Definition::definitionType(), MemberDef::enumFieldList(), LayoutDocManager::File, ClassDef::getMemberList(), FileDef::getMemberList(), GroupDef::getMemberList(), NamespaceDef::getMemberList(), LayoutDocManager::Group, LayoutDocManager::instance(), MemberDef::isEnumerate(), MemberDef::isStrong(), m_def, m_members, m_type, LayoutDocEntry::MemberDef, Module, LayoutDocManager::Namespace, Definition::partOfGroups(), toClassDef(), toFileDef(), toGroupDef(), toMemberDef(), toNamespaceDef(), LayoutDocEntryMemberDef::type, Definition::TypeClass, Definition::TypeFile, Definition::TypeGroup, Definition::TypeMember, and Definition::TypeNamespace.
Referenced by Private().
addMembers() [2/2]
void NestingNodeContext::Private::addMembers (ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5465 of file context.cpp.
    {
      if (m_type!=ContextTreeType::Module && m_def->partOfGroups().empty()) // show outside of group
      {
        if (m_def->definitionType()==Definition::TypeNamespace)
        {
          // add namespace members
          for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Namespace))
          {
            if (lde->kind()==LayoutDocEntry::MemberDef)
            {
              const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
              if (lmd)
              {
                const MemberList *ml = toNamespaceDef(m_def)->getMemberList(lmd->type);
                if (ml)
                {
                  m_members->addMembers(*ml,visitedClasses);
                }
              }
            }
          }
        }
        else if (m_def->definitionType()==Definition::TypeClass)
        {
          // add class members
          for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
          {
            if (lde->kind()==LayoutDocEntry::MemberDef)
            {
              const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
              if (lmd)
              {
                const MemberList *ml = toClassDef(m_def)->getMemberList(lmd->type);
                if (ml)
                {
                  m_members->addMembers(*ml,visitedClasses);
                }
              }
            }
          }
        }
        else if (m_def->definitionType()==Definition::TypeFile)
        {
          // add class members
          for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::File))
          {
            if (lde->kind()==LayoutDocEntry::MemberDef)
            {
              const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
              if (lmd)
              {
                const MemberList *ml = toFileDef(m_def)->getMemberList(lmd->type);
                if (ml)
                {
                  m_members->addMembers(*ml,visitedClasses);
                }
              }
            }
          }
        }
      }
      else if (m_def->definitionType()==Definition::TypeGroup && m_type==ContextTreeType::Module) // show as part of group
      {
        // add class members
        for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Group))
        {
          if (lde->kind()==LayoutDocEntry::MemberDef)
          {
            const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
            if (lmd)
            {
              const MemberList *ml = toGroupDef(m_def)->getMemberList(lmd->type);
              if (ml)
              {
                m_members->addMembers(*ml,visitedClasses);
              }
            }
          }
        }
      }
      if (m_def->definitionType()==Definition::TypeMember)
      {
        const MemberDef *md = toMemberDef(m_def);
        if (md->isEnumerate() && md->isStrong())
        {
          m_members->addMembers(md->enumFieldList(),visitedClasses);
        }
      }
    }
References LayoutDocManager::Class, MemberDef::enumFieldList(), LayoutDocManager::File, ClassDef::getMemberList(), FileDef::getMemberList(), GroupDef::getMemberList(), NamespaceDef::getMemberList(), LayoutDocManager::Group, LayoutDocManager::instance(), MemberDef::isEnumerate(), MemberDef::isStrong(), LayoutDocEntry::MemberDef, Module, LayoutDocManager::Namespace, toClassDef(), toFileDef(), toGroupDef(), toMemberDef(), toNamespaceDef(), LayoutDocEntryMemberDef::type, Definition::TypeClass, Definition::TypeFile, Definition::TypeGroup, Definition::TypeMember, and Definition::TypeNamespace.
addModules() [1/2]
void NestingNodeContext::Private::addModules (ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5457 of file context.cpp.
    {
      const GroupDef *gd = toGroupDef(m_def);
      if (gd && !gd->getSubGroups().empty())
      {
        m_children->addModules(gd->getSubGroups(),visitedClasses);
      }
    }
References GroupDef::getSubGroups(), m_children, m_def, and toGroupDef().
Referenced by Private().
addModules() [2/2]
void NestingNodeContext::Private::addModules (ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5457 of file context.cpp.
    {
      const GroupDef *gd = toGroupDef(m_def);
      if (gd && !gd->getSubGroups().empty())
      {
        m_children->addModules(gd->getSubGroups(),visitedClasses);
      }
    }
References GroupDef::getSubGroups(), and toGroupDef().
addNamespaces() [1/2]
void NestingNodeContext::Private::addNamespaces (bool addClasses, bool addConcepts, ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5406 of file context.cpp.
    {
      const NamespaceDef *nd = toNamespaceDef(m_def);
      if (nd)
      {
        if (!nd->getNamespaces().empty())
        {
          m_children->addNamespaces(nd->getNamespaces(),FALSE,addClasses,addConcepts,visitedClasses);
        }
        if (addClasses)
        {
          m_children->addClasses(nd->getClasses(),FALSE,visitedClasses);
        }
        if (addConcepts)
        {
          m_children->addConcepts(nd->getConcepts(),FALSE,visitedClasses);
        }
      }
      const GroupDef *gd = toGroupDef(m_def);
      if (gd)
      {
        m_children->addConcepts(gd->getConcepts(),false,visitedClasses);
      }
    }
References addClasses(), addConcepts(), LinkedRefMap< T, Hash, KeyEqual, Map >::empty(), FALSE, NamespaceDef::getClasses(), GroupDef::getConcepts(), NamespaceDef::getConcepts(), NamespaceDef::getNamespaces(), m_children, m_def, toGroupDef(), and toNamespaceDef().
Referenced by Private().
addNamespaces() [2/2]
void NestingNodeContext::Private::addNamespaces (bool addClasses, bool addConcepts, ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5406 of file context.cpp.
    {
      const NamespaceDef *nd = toNamespaceDef(m_def);
      if (nd)
      {
        if (!nd->getNamespaces().empty())
        {
          m_children->addNamespaces(nd->getNamespaces(),FALSE,addClasses,addConcepts,visitedClasses);
        }
        if (addClasses)
        {
          m_children->addClasses(nd->getClasses(),FALSE,visitedClasses);
        }
        if (addConcepts)
        {
          m_children->addConcepts(nd->getConcepts(),FALSE,visitedClasses);
        }
      }
      const GroupDef *gd = toGroupDef(m_def);
      if (gd)
      {
        m_children->addConcepts(gd->getConcepts(),false,visitedClasses);
      }
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::empty(), FALSE, NamespaceDef::getClasses(), GroupDef::getConcepts(), NamespaceDef::getConcepts(), NamespaceDef::getNamespaces(), toGroupDef(), and toNamespaceDef().
addPages() [1/2]
void NestingNodeContext::Private::addPages (ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5444 of file context.cpp.
    {
      const PageDef *pd = toPageDef(m_def);
      if (pd && !pd->getSubPages().empty())
      {
        m_children->addPages(pd->getSubPages(),FALSE,visitedClasses);
      }
      const GroupDef *gd = toGroupDef(m_def);
      if (gd)
      {
        m_children->addPages(gd->getPages(),FALSE,visitedClasses);
      }
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::empty(), FALSE, GroupDef::getPages(), PageDef::getSubPages(), m_children, m_def, toGroupDef(), and toPageDef().
Referenced by Private().
addPages() [2/2]
void NestingNodeContext::Private::addPages (ClassDefSet & visitedClasses) [inline], [private]
Definition at line 5444 of file context.cpp.
    {
      const PageDef *pd = toPageDef(m_def);
      if (pd && !pd->getSubPages().empty())
      {
        m_children->addPages(pd->getSubPages(),FALSE,visitedClasses);
      }
      const GroupDef *gd = toGroupDef(m_def);
      if (gd)
      {
        m_children->addPages(gd->getPages(),FALSE,visitedClasses);
      }
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::empty(), FALSE, GroupDef::getPages(), PageDef::getSubPages(), toGroupDef(), and toPageDef().
anchor() [1/2]
TemplateVariant NestingNodeContext::Private::anchor () const [inline], [private]
Definition at line 5337 of file context.cpp.
{ return m_def->anchor(); }
References Definition::anchor(), and m_def.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
TemplateVariant NestingNodeContext::Private::anchor () const [inline], [private]
Definition at line 5337 of file context.cpp.
{ return m_def->anchor(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
brief() [1/2]
TemplateVariant NestingNodeContext::Private::brief () const [inline], [private]
Definition at line 5335 of file context.cpp.
{ return m_brief.get(this); }
References m_brief.
brief() [2/2]
TemplateVariant NestingNodeContext::Private::brief () const [inline], [private]
Definition at line 5335 of file context.cpp.
{ return m_brief.get(this); }
children() [1/2]
TemplateVariant NestingNodeContext::Private::children () const [inline], [private]
Definition at line 5325 of file context.cpp.
{ return std::static_pointer_cast<TemplateListIntf>(m_children); }
References m_children.
children() [2/2]
TemplateVariant NestingNodeContext::Private::children () const [inline], [private]
Definition at line 5325 of file context.cpp.
{ return std::static_pointer_cast<TemplateListIntf>(m_children); }
createBrief() [1/2]
TemplateVariant NestingNodeContext::Private::createBrief () const [inline], [private]
Definition at line 5598 of file context.cpp.
    {
      return m_def->hasBriefDescription() ?
          TemplateVariant(parseDoc(m_def,m_def->briefFile(),m_def->briefLine(),
                          "",m_def->briefDescription(),TRUE)) :
          TemplateVariant("");
    }
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Definition::hasBriefDescription(), m_def, parseDoc(), and TRUE.
createBrief() [2/2]
TemplateVariant NestingNodeContext::Private::createBrief () const [inline], [private]
Definition at line 5598 of file context.cpp.
    {
      return m_def->hasBriefDescription() ?
          TemplateVariant(parseDoc(m_def,m_def->briefFile(),m_def->briefLine(),
                          "",m_def->briefDescription(),TRUE)) :
          TemplateVariant("");
    }
References parseDoc(), and TRUE.
createClass() [1/2]
TemplateVariant NestingNodeContext::Private::createClass () const [inline], [private]
Definition at line 5556 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeClass ?
          TemplateVariant(ClassContext::alloc(toClassDef(m_def))) :
          TemplateVariant(false);
    }
References ClassContext::alloc(), Definition::definitionType(), m_def, toClassDef(), and Definition::TypeClass.
createClass() [2/2]
TemplateVariant NestingNodeContext::Private::createClass () const [inline], [private]
Definition at line 5556 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeClass ?
          TemplateVariant(ClassContext::alloc(toClassDef(m_def))) :
          TemplateVariant(false);
    }
References ClassContext::alloc(), toClassDef(), and Definition::TypeClass.
createDir() [1/2]
TemplateVariant NestingNodeContext::Private::createDir () const [inline], [private]
Definition at line 5568 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeDir ?
          TemplateVariant(DirContext::alloc(toDirDef(m_def))) :
          TemplateVariant(false);
    }
References DirContext::alloc(), Definition::definitionType(), m_def, toDirDef(), and Definition::TypeDir.
createDir() [2/2]
TemplateVariant NestingNodeContext::Private::createDir () const [inline], [private]
Definition at line 5568 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeDir ?
          TemplateVariant(DirContext::alloc(toDirDef(m_def))) :
          TemplateVariant(false);
    }
References DirContext::alloc(), toDirDef(), and Definition::TypeDir.
createFile() [1/2]
TemplateVariant NestingNodeContext::Private::createFile () const [inline], [private]
Definition at line 5574 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeFile ?
          TemplateVariant(FileContext::alloc(toFileDef(m_def))) :
          TemplateVariant(false);
    }
References FileContext::alloc(), Definition::definitionType(), m_def, toFileDef(), and Definition::TypeFile.
createFile() [2/2]
TemplateVariant NestingNodeContext::Private::createFile () const [inline], [private]
Definition at line 5574 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeFile ?
          TemplateVariant(FileContext::alloc(toFileDef(m_def))) :
          TemplateVariant(false);
    }
References FileContext::alloc(), toFileDef(), and Definition::TypeFile.
createMember() [1/2]
TemplateVariant NestingNodeContext::Private::createMember () const [inline], [private]
Definition at line 5592 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeMember ?
          TemplateVariant(MemberContext::alloc(toMemberDef(m_def))) :
          TemplateVariant(false);
    }
References MemberContext::alloc(), Definition::definitionType(), m_def, toMemberDef(), and Definition::TypeMember.
createMember() [2/2]
TemplateVariant NestingNodeContext::Private::createMember () const [inline], [private]
Definition at line 5592 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeMember ?
          TemplateVariant(MemberContext::alloc(toMemberDef(m_def))) :
          TemplateVariant(false);
    }
References MemberContext::alloc(), toMemberDef(), and Definition::TypeMember.
createModule() [1/2]
TemplateVariant NestingNodeContext::Private::createModule () const [inline], [private]
Definition at line 5586 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeGroup ?
          TemplateVariant(ModuleContext::alloc(toGroupDef(m_def))) :
          TemplateVariant(false);
    }
References ModuleContext::alloc(), Definition::definitionType(), m_def, toGroupDef(), and Definition::TypeGroup.
createModule() [2/2]
TemplateVariant NestingNodeContext::Private::createModule () const [inline], [private]
Definition at line 5586 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeGroup ?
          TemplateVariant(ModuleContext::alloc(toGroupDef(m_def))) :
          TemplateVariant(false);
    }
References ModuleContext::alloc(), toGroupDef(), and Definition::TypeGroup.
createNamespace() [1/2]
TemplateVariant NestingNodeContext::Private::createNamespace () const [inline], [private]
Definition at line 5562 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeNamespace ?
          TemplateVariant(NamespaceContext::alloc(toNamespaceDef(m_def))) :
          TemplateVariant(false);
    }
References NamespaceContext::alloc(), Definition::definitionType(), m_def, toNamespaceDef(), and Definition::TypeNamespace.
createNamespace() [2/2]
TemplateVariant NestingNodeContext::Private::createNamespace () const [inline], [private]
Definition at line 5562 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeNamespace ?
          TemplateVariant(NamespaceContext::alloc(toNamespaceDef(m_def))) :
          TemplateVariant(false);
    }
References NamespaceContext::alloc(), toNamespaceDef(), and Definition::TypeNamespace.
createPage() [1/2]
TemplateVariant NestingNodeContext::Private::createPage () const [inline], [private]
Definition at line 5580 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypePage ?
          TemplateVariant(PageContext::alloc(toPageDef(m_def),FALSE,FALSE)) :
          TemplateVariant(false);
    }
References PageContext::alloc(), Definition::definitionType(), FALSE, m_def, toPageDef(), and Definition::TypePage.
createPage() [2/2]
TemplateVariant NestingNodeContext::Private::createPage () const [inline], [private]
Definition at line 5580 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypePage ?
          TemplateVariant(PageContext::alloc(toPageDef(m_def),FALSE,FALSE)) :
          TemplateVariant(false);
    }
References PageContext::alloc(), FALSE, toPageDef(), and Definition::TypePage.
externalReference() [1/2]
TemplateVariant NestingNodeContext::Private::externalReference () const [inline], [private]
Definition at line 5340 of file context.cpp.
{ return m_def->externalReference(relPathAsString()); }
References Definition::externalReference(), m_def, and relPathAsString().
externalReference() [2/2]
TemplateVariant NestingNodeContext::Private::externalReference () const [inline], [private]
Definition at line 5340 of file context.cpp.
{ return m_def->externalReference(relPathAsString()); }
fields() [1/2]
StringVector NestingNodeContext::Private::fields () const [inline]
Definition at line 5312 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector NestingNodeContext::Private::fields () const [inline]
Definition at line 5312 of file context.cpp.
{ return s_inst.fields(); }
fileName() [1/2]
TemplateVariant NestingNodeContext::Private::fileName () const [inline], [private]
Definition at line 5338 of file context.cpp.
{ return m_def->getOutputFileBase(); }
References Definition::getOutputFileBase(), and m_def.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
TemplateVariant NestingNodeContext::Private::fileName () const [inline], [private]
Definition at line 5338 of file context.cpp.
{ return m_def->getOutputFileBase(); }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
get() [1/2]
TemplateVariant NestingNodeContext::Private::get (const QCString & n) const [inline]
Definition at line 5311 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant NestingNodeContext::Private::get (const QCString & n) const [inline]
Definition at line 5311 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
getClass() [1/2]
TemplateVariant NestingNodeContext::Private::getClass () const [inline], [private]
Definition at line 5327 of file context.cpp.
{ return m_class.get(this); }
References m_class.
getClass() [2/2]
TemplateVariant NestingNodeContext::Private::getClass () const [inline], [private]
Definition at line 5327 of file context.cpp.
{ return m_class.get(this); }
getDir() [1/2]
TemplateVariant NestingNodeContext::Private::getDir () const [inline], [private]
Definition at line 5329 of file context.cpp.
{ return m_dir.get(this); }
References m_dir.
getDir() [2/2]
TemplateVariant NestingNodeContext::Private::getDir () const [inline], [private]
Definition at line 5329 of file context.cpp.
{ return m_dir.get(this); }
getFile() [1/2]
TemplateVariant NestingNodeContext::Private::getFile () const [inline], [private]
Definition at line 5330 of file context.cpp.
{ return m_file.get(this); }
References m_file.
getFile() [2/2]
TemplateVariant NestingNodeContext::Private::getFile () const [inline], [private]
Definition at line 5330 of file context.cpp.
{ return m_file.get(this); }
getMember() [1/2]
TemplateVariant NestingNodeContext::Private::getMember () const [inline], [private]
Definition at line 5333 of file context.cpp.
{ return m_member.get(this); }
References m_member.
getMember() [2/2]
TemplateVariant NestingNodeContext::Private::getMember () const [inline], [private]
Definition at line 5333 of file context.cpp.
{ return m_member.get(this); }
getModule() [1/2]
TemplateVariant NestingNodeContext::Private::getModule () const [inline], [private]
Definition at line 5332 of file context.cpp.
{ return m_module.get(this); }
References m_module.
getModule() [2/2]
TemplateVariant NestingNodeContext::Private::getModule () const [inline], [private]
Definition at line 5332 of file context.cpp.
{ return m_module.get(this); }
getNamespace() [1/2]
TemplateVariant NestingNodeContext::Private::getNamespace () const [inline], [private]
Definition at line 5328 of file context.cpp.
{ return m_namespace.get(this); }
References m_namespace.
getNamespace() [2/2]
TemplateVariant NestingNodeContext::Private::getNamespace () const [inline], [private]
Definition at line 5328 of file context.cpp.
{ return m_namespace.get(this); }
getPage() [1/2]
TemplateVariant NestingNodeContext::Private::getPage () const [inline], [private]
Definition at line 5331 of file context.cpp.
{ return m_page.get(this); }
References m_page.
getPage() [2/2]
TemplateVariant NestingNodeContext::Private::getPage () const [inline], [private]
Definition at line 5331 of file context.cpp.
{ return m_page.get(this); }
id() [1/2]
TemplateVariant NestingNodeContext::Private::id () const [inline]
Definition at line 5314 of file context.cpp.
    {
      QCString result;
      if (m_parent) result=m_parent->id();
      result+=QCString().setNum(m_index)+"_";
      return result;
    }
References NestingNodeContext::id(), m_index, m_parent, and QCString::setNum().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
TemplateVariant NestingNodeContext::Private::id () const [inline]
Definition at line 5314 of file context.cpp.
    {
      QCString result;
      if (m_parent) result=m_parent->id();
      result+=QCString().setNum(m_index)+"_";
      return result;
    }
References QCString::setNum().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
isLeafNode() [1/2]
TemplateVariant NestingNodeContext::Private::isLeafNode () const [inline], [private]
Definition at line 5324 of file context.cpp.
{ return m_children->count()==0; }
References m_children.
isLeafNode() [2/2]
TemplateVariant NestingNodeContext::Private::isLeafNode () const [inline], [private]
Definition at line 5324 of file context.cpp.
{ return m_children->count()==0; }
isLinkable() [1/2]
TemplateVariant NestingNodeContext::Private::isLinkable () const [inline], [private]
Definition at line 5336 of file context.cpp.
{ return m_def->isLinkable(); }
References Definition::isLinkable(), and m_def.
isLinkable() [2/2]
TemplateVariant NestingNodeContext::Private::isLinkable () const [inline], [private]
Definition at line 5336 of file context.cpp.
{ return m_def->isLinkable(); }
isReference() [1/2]
TemplateVariant NestingNodeContext::Private::isReference () const [inline], [private]
Definition at line 5339 of file context.cpp.
{ return m_def->isReference(); }
References Definition::isReference(), and m_def.
isReference() [2/2]
TemplateVariant NestingNodeContext::Private::isReference () const [inline], [private]
Definition at line 5339 of file context.cpp.
{ return m_def->isReference(); }
level() [1/2]
TemplateVariant NestingNodeContext::Private::level () const [inline], [private]
Definition at line 5334 of file context.cpp.
{ return m_level; }
References m_level.
Referenced by doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docHeadingType::buildAttributes(), doxmlparser.compound.docHeadingType::exportAttributes(), doxmlparser.compound.docHeadingType::get_level(), Private(), and doxmlparser.compound.docHeadingType::set_level().
level() [2/2]
TemplateVariant NestingNodeContext::Private::level () const [inline], [private]
Definition at line 5334 of file context.cpp.
{ return m_level; }
Referenced by doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docHeadingType::buildAttributes(), doxmlparser.compound.docHeadingType::exportAttributes(), doxmlparser.compound.docHeadingType::get_level(), and doxmlparser.compound.docHeadingType::set_level().
members() [1/2]
TemplateVariant NestingNodeContext::Private::members () const [inline], [private]
Definition at line 5326 of file context.cpp.
{ return std::static_pointer_cast<TemplateListIntf>(m_members); }
References m_members.
members() [2/2]
TemplateVariant NestingNodeContext::Private::members () const [inline], [private]
Definition at line 5326 of file context.cpp.
{ return std::static_pointer_cast<TemplateListIntf>(m_members); }
name() [1/2]
TemplateVariant NestingNodeContext::Private::name () const [inline], [private]
Definition at line 5341 of file context.cpp.
    {
      if (m_def->definitionType()==Definition::TypeMember && m_type==ContextTreeType::Module)
      {
        return toMemberDef(m_def)->qualifiedName();
      }
      else
      {
        return m_def->displayName(m_type==ContextTreeType::Module);
      }
    }
References Definition::definitionType(), Definition::displayName(), m_def, m_type, Module, MemberDef::qualifiedName(), toMemberDef(), and Definition::TypeMember.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
TemplateVariant NestingNodeContext::Private::name () const [inline], [private]
Definition at line 5341 of file context.cpp.
    {
      if (m_def->definitionType()==Definition::TypeMember && m_type==ContextTreeType::Module)
      {
        return toMemberDef(m_def)->qualifiedName();
      }
      else
      {
        return m_def->displayName(m_type==ContextTreeType::Module);
      }
    }
References Module, MemberDef::qualifiedName(), toMemberDef(), and Definition::TypeMember.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
partOfGroup() [1/2]
TemplateVariant NestingNodeContext::Private::partOfGroup () const [inline], [private]
Definition at line 5352 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeMember ? toMemberDef(m_def)->getGroupDef()!=0 :
             !m_def->partOfGroups().empty();
    }
References Definition::definitionType(), MemberDef::getGroupDef(), m_def, Definition::partOfGroups(), toMemberDef(), and Definition::TypeMember.
partOfGroup() [2/2]
TemplateVariant NestingNodeContext::Private::partOfGroup () const [inline], [private]
Definition at line 5352 of file context.cpp.
    {
      return m_def->definitionType()==Definition::TypeMember ? toMemberDef(m_def)->getGroupDef()!=0 :
             !m_def->partOfGroups().empty();
    }
References MemberDef::getGroupDef(), Definition::partOfGroups(), toMemberDef(), and Definition::TypeMember.
relPathAsString() [1/2]
QCString NestingNodeContext::Private::relPathAsString () const [inline], [private]
Definition at line 5357 of file context.cpp.
    {
      bool createSubdirs = Config_getBool(CREATE_SUBDIRS);
      return createSubdirs ? QCString("../../") : QCString("");
    }
References Config_getBool.
Referenced by externalReference().
relPathAsString() [2/2]
QCString NestingNodeContext::Private::relPathAsString () const [inline], [private]
Definition at line 5357 of file context.cpp.
    {
      bool createSubdirs = Config_getBool(CREATE_SUBDIRS);
      return createSubdirs ? QCString("../../") : QCString("");
    }
References Config_getBool.
Member Data Documentation
m_brief
CachedItem< TemplateVariant, Private, &Private::createBrief > NestingNodeContext::Private::m_brief [private]
Definition at line 5620 of file context.cpp.
Referenced by brief().
m_children
std::shared_ptr< NestingContext > NestingNodeContext::Private::m_children [private]
Definition at line 5609 of file context.cpp.
Referenced by addClasses(), addConcepts(), addDirFiles(), addModules(), addNamespaces(), addPages(), children(), isLeafNode(), and Private().
m_class
CachedItem< TemplateVariant, Private, &Private::createClass > NestingNodeContext::Private::m_class [private]
Definition at line 5613 of file context.cpp.
Referenced by getClass().
m_def
const Definition * NestingNodeContext::Private::m_def [private]
Definition at line 5608 of file context.cpp.
Referenced by addClasses(), addConcepts(), addDirFiles(), addMembers(), addModules(), addNamespaces(), addPages(), anchor(), createBrief(), createClass(), createDir(), createFile(), createMember(), createModule(), createNamespace(), createPage(), externalReference(), fileName(), isLinkable(), isReference(), name(), and partOfGroup().
m_dir
CachedItem< TemplateVariant, Private, &Private::createDir > NestingNodeContext::Private::m_dir [private]
Definition at line 5615 of file context.cpp.
Referenced by getDir().
m_file
CachedItem< TemplateVariant, Private, &Private::createFile > NestingNodeContext::Private::m_file [private]
Definition at line 5616 of file context.cpp.
Referenced by getFile().
m_index
int NestingNodeContext::Private::m_index [private]
Definition at line 5612 of file context.cpp.
Referenced by id().
m_level
int NestingNodeContext::Private::m_level [private]
Definition at line 5611 of file context.cpp.
Referenced by level().
m_member
CachedItem< TemplateVariant, Private, &Private::createMember > NestingNodeContext::Private::m_member [private]
Definition at line 5619 of file context.cpp.
Referenced by getMember().
m_members
std::shared_ptr< NestingContext > NestingNodeContext::Private::m_members [private]
Definition at line 5610 of file context.cpp.
Referenced by addMembers(), members(), and Private().
m_module
CachedItem< TemplateVariant, Private, &Private::createModule > NestingNodeContext::Private::m_module [private]
Definition at line 5618 of file context.cpp.
Referenced by getModule().
m_namespace
CachedItem< TemplateVariant, Private, &Private::createNamespace > NestingNodeContext::Private::m_namespace [private]
Definition at line 5614 of file context.cpp.
Referenced by getNamespace().
m_page
CachedItem< TemplateVariant, Private, &Private::createPage > NestingNodeContext::Private::m_page [private]
Definition at line 5617 of file context.cpp.
Referenced by getPage().
m_parent
const NestingNodeContext * NestingNodeContext::Private::m_parent [private]
Definition at line 5606 of file context.cpp.
Referenced by id().
m_type
ContextTreeType NestingNodeContext::Private::m_type [private]
Definition at line 5607 of file context.cpp.
Referenced by addMembers(), name(), and Private().
s_inst
const PropertyMap< NestingNodeContext::Private > NestingNodeContext::Private::s_inst [static], [private]
Definition at line 5621 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp