QhpSectionTree Class Reference
Classes
struct Node
Public Member Functions
void addSection (const QCString &title, const QCString &ref)
void incLevel ()
void decLevel ()
void writeToc (TextStream &t) const
void addSection (const QCString &title, const QCString &ref)
void incLevel ()
void decLevel ()
void writeToc (TextStream &t) const
Private Member Functions
void traverse (const Node &root, TextStream &t, int indent) const
void traverse (const Node &root, TextStream &t, int indent) const
Private Attributes
Node m_root
Node * m_current = &m_root
Detailed Description
Definition at line 39 of file qhp.cpp.
Member Function Documentation
addSection() [1/2]
void QhpSectionTree::addSection (const QCString & title, const QCString & ref) [inline]
Definition at line 117 of file qhp.cpp.
    {
      m_current->children.push_back(std::make_unique<Node>(m_current,title,ref));
    }
References QhpSectionTree::Node::children, and m_current.
addSection() [2/2]
void QhpSectionTree::addSection (const QCString & title, const QCString & ref) [inline]
Definition at line 117 of file qhp.cpp.
    {
      m_current->children.push_back(std::make_unique<Node>(m_current,title,ref));
    }
References QhpSectionTree::Node::children, and m_current.
decLevel() [1/2]
void QhpSectionTree::decLevel () [inline]
Definition at line 127 of file qhp.cpp.
    {
      assert(m_current->parent!=0);
      if (m_current->parent)
      {
        m_current = m_current->parent;
      }
    }
References m_current, and QhpSectionTree::Node::parent.
decLevel() [2/2]
void QhpSectionTree::decLevel () [inline]
Definition at line 127 of file qhp.cpp.
    {
      assert(m_current->parent!=0);
      if (m_current->parent)
      {
        m_current = m_current->parent;
      }
    }
References m_current, and QhpSectionTree::Node::parent.
incLevel() [1/2]
void QhpSectionTree::incLevel () [inline]
Definition at line 121 of file qhp.cpp.
    {
      auto newNode = new Node(m_current);
      m_current->children.push_back(std::unique_ptr<Node>(newNode));
      m_current = newNode;
    }
References QhpSectionTree::Node::children, and m_current.
incLevel() [2/2]
void QhpSectionTree::incLevel () [inline]
Definition at line 121 of file qhp.cpp.
    {
      auto newNode = new Node(m_current);
      m_current->children.push_back(std::unique_ptr<Node>(newNode));
      m_current = newNode;
    }
References QhpSectionTree::Node::children, and m_current.
traverse() [1/2]
void QhpSectionTree::traverse (const Node & root, TextStream & t, int indent) const [inline], [private]
Definition at line 62 of file qhp.cpp.
    {
      /* Input: Output:
       * =================================================
       * Section1 <section title=".." ref="..">
       * Dir1
       * Section2 <section title=".." ref="..">
       * Dir2
       * Section3 <section title=".." ref=".."/>
       * </section>
       * </section>
       * Section4 <section title=".." ref="..>
       * Dir3
       * Dir4
       * Section5 <section title=.." ref=.."/>
       * </section>
       * Section6 <section title=".." ref=".."/>
       */
      size_t numChildren = root.children.size();
      size_t i=0;
      while (i<numChildren)
      {
        if (root.children[i]->type==Node::Type::Section)
        {
          i++;
          if (i<numChildren && root.children[i]->type==Node::Type::Dir)
          {
            // we have a dir node
            writeIndent(t,indent);
            t << "<section title=\"" << convertToXML(root.children[i-1]->title) << "\""
              << " ref=\"" << convertToXML(root.children[i-1]->ref) << "\">\n";
            while (i<numChildren && root.children[i]->type==Node::Type::Dir)
            {
              traverse(*root.children[i].get(),t,indent+1);
              i++;
            }
            writeIndent(t,indent);
            t << "</section>\n";
          }
          else // we have a leaf section node
          {
            writeIndent(t,indent);
            t << "<section title=\"" << convertToXML(root.children[i-1]->title) << "\""
              << " ref=\"" << convertToXML(root.children[i-1]->ref) << "\"/>\n";
          }
        }
        else // dir without preceding section (no extra indent)
        {
          traverse(*root.children[i].get(),t,indent);
          i++;
        }
      }
    }
References QhpSectionTree::Node::children, convertToXML(), QhpSectionTree::Node::Dir, QhpSectionTree::Node::Section, traverse(), and writeIndent().
Referenced by traverse(), and writeToc().
traverse() [2/2]
void QhpSectionTree::traverse (const Node & root, TextStream & t, int indent) const [inline], [private]
Definition at line 62 of file qhp.cpp.
    {
      /* Input: Output:
       * =================================================
       * Section1 <section title=".." ref="..">
       * Dir1
       * Section2 <section title=".." ref="..">
       * Dir2
       * Section3 <section title=".." ref=".."/>
       * </section>
       * </section>
       * Section4 <section title=".." ref="..>
       * Dir3
       * Dir4
       * Section5 <section title=.." ref=.."/>
       * </section>
       * Section6 <section title=".." ref=".."/>
       */
      size_t numChildren = root.children.size();
      size_t i=0;
      while (i<numChildren)
      {
        if (root.children[i]->type==Node::Type::Section)
        {
          i++;
          if (i<numChildren && root.children[i]->type==Node::Type::Dir)
          {
            // we have a dir node
            writeIndent(t,indent);
            t << "<section title=\"" << convertToXML(root.children[i-1]->title) << "\""
              << " ref=\"" << convertToXML(root.children[i-1]->ref) << "\">\n";
            while (i<numChildren && root.children[i]->type==Node::Type::Dir)
            {
              traverse(*root.children[i].get(),t,indent+1);
              i++;
            }
            writeIndent(t,indent);
            t << "</section>\n";
          }
          else // we have a leaf section node
          {
            writeIndent(t,indent);
            t << "<section title=\"" << convertToXML(root.children[i-1]->title) << "\""
              << " ref=\"" << convertToXML(root.children[i-1]->ref) << "\"/>\n";
          }
        }
        else // dir without preceding section (no extra indent)
        {
          traverse(*root.children[i].get(),t,indent);
          i++;
        }
      }
    }
References convertToXML(), QhpSectionTree::Node::Dir, QhpSectionTree::Node::Section, traverse(), and writeIndent().
writeToc() [1/2]
void QhpSectionTree::writeToc (TextStream & t) const [inline]
Definition at line 135 of file qhp.cpp.
    {
      writeIndent(t,2);
      t << "<toc>\n";
      traverse(m_root,t,3);
      writeIndent(t,2);
      t << "</toc>\n";
    }
References m_root, traverse(), and writeIndent().
writeToc() [2/2]
void QhpSectionTree::writeToc (TextStream & t) const [inline]
Definition at line 135 of file qhp.cpp.
    {
      writeIndent(t,2);
      t << "<toc>\n";
      traverse(m_root,t,3);
      writeIndent(t,2);
      t << "</toc>\n";
    }
References m_root, traverse(), and writeIndent().
Member Data Documentation
m_current
Node * QhpSectionTree::m_current = &m_root [private]
Definition at line 60 of file qhp.cpp.
Referenced by addSection(), decLevel(), and incLevel().
m_root
Node QhpSectionTree::m_root [private]
Definition at line 59 of file qhp.cpp.
Referenced by writeToc().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/qhp.cpp
doxygen/src/qhp.cpp