LinkedRefMap< T, Hash, KeyEqual, Map > Class Template Reference
Container class representing a vector of objects with keys.
#include <linkedmap.h>
Public Types
using Ptr = T *
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
using reverse_iterator = typename Vec::reverse_iterator
using const_reverse_iterator = typename Vec::const_reverse_iterator
using Ptr = T *
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
using reverse_iterator = typename Vec::reverse_iterator
using const_reverse_iterator = typename Vec::const_reverse_iterator
Public Member Functions
const T * find (const std::string &key) const
const T * find (const QCString &key) const
const T * find (const char *key) const
T * find (const char *key)
non-const wrapper for find() const
T * find (const QCString &key)
T * find (const std::string &key)
non-const wrapper for find() const
bool add (const char *k, T *obj)
bool add (const QCString &k, T *obj)
bool prepend (const char *k, T *obj)
bool prepend (const QCString &key, T *obj)
bool del (const QCString &key)
Ptr & operator[] (size_t pos)
const Ptr & operator[] (size_t pos) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const
size_t size () const
void clear ()
const T * find (const std::string &key) const
const T * find (const QCString &key) const
const T * find (const char *key) const
T * find (const char *key)
non-const wrapper for find() const
T * find (const QCString &key)
T * find (const std::string &key)
non-const wrapper for find() const
bool add (const char *k, T *obj)
bool add (const QCString &k, T *obj)
bool prepend (const char *k, T *obj)
bool prepend (const QCString &key, T *obj)
bool del (const QCString &key)
Ptr & operator[] (size_t pos)
const Ptr & operator[] (size_t pos) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const
size_t size () const
void clear ()
Private Attributes
Map m_lookup
Vec m_entries
Detailed Description
template<class T, class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
class LinkedRefMap< T, Hash, KeyEqual, Map >
Container class representing a vector of objects with keys.
Objects can be efficiently be looked up given the key. Objects are not owned by the container, the container will only hold references. When adding objects the order of addition is kept, and used while iterating.
Definition at line 231 of file linkedmap.h.
Member Typedef Documentation
const_iterator [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedRefMap< T, Hash, KeyEqual, Map >::const_iterator = typename Vec::const_iterator
Definition at line 237 of file linkedmap.h.
const_iterator [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedRefMap< T, Hash, KeyEqual, Map >::const_iterator = typename Vec::const_iterator
Definition at line 237 of file linkedmap.h.
const_reverse_iterator [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedRefMap< T, Hash, KeyEqual, Map >::const_reverse_iterator = typename Vec::const_reverse_iterator
Definition at line 239 of file linkedmap.h.
const_reverse_iterator [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedRefMap< T, Hash, KeyEqual, Map >::const_reverse_iterator = typename Vec::const_reverse_iterator
Definition at line 239 of file linkedmap.h.
iterator [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedRefMap< T, Hash, KeyEqual, Map >::iterator = typename Vec::iterator
Definition at line 236 of file linkedmap.h.
iterator [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedRefMap< T, Hash, KeyEqual, Map >::iterator = typename Vec::iterator
Definition at line 236 of file linkedmap.h.
Ptr [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedRefMap< T, Hash, KeyEqual, Map >::Ptr = T*
Definition at line 234 of file linkedmap.h.
Ptr [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedRefMap< T, Hash, KeyEqual, Map >::Ptr = T*
Definition at line 234 of file linkedmap.h.
reverse_iterator [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedRefMap< T, Hash, KeyEqual, Map >::reverse_iterator = typename Vec::reverse_iterator
Definition at line 238 of file linkedmap.h.
reverse_iterator [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedRefMap< T, Hash, KeyEqual, Map >::reverse_iterator = typename Vec::reverse_iterator
Definition at line 238 of file linkedmap.h.
Vec [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedRefMap< T, Hash, KeyEqual, Map >::Vec = std::vector<Ptr>
Definition at line 235 of file linkedmap.h.
Vec [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedRefMap< T, Hash, KeyEqual, Map >::Vec = std::vector<Ptr>
Definition at line 235 of file linkedmap.h.
Member Function Documentation
add() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedRefMap< T, Hash, KeyEqual, Map >::add (const char * k, T * obj) [inline]
Adds an object reference to the ordered vector if it was not added already. Return true if the reference was added, and false if an object with the same key was already added before
Definition at line 284 of file linkedmap.h.
    {
      if (find(k)==nullptr) // new element
      {
        std::string key(k ? k : "");
        m_lookup.insert({key,obj});
        m_entries.push_back(obj);
        return true;
      }
      else // already existing, don't add
      {
        return false;
      }
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries, LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup, and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), GroupDefImpl::addClass(), GroupDefImpl::addConcept(), GroupDefImpl::addExample(), ClassDefImpl::addInnerCompound(), NamespaceDefImpl::addInnerCompound(), PageDefImpl::addInnerCompound(), GroupDefImpl::addNamespace(), GroupDefImpl::addPage(), FileDefImpl::addUsingDeclaration(), NamespaceDefImpl::addUsingDeclaration(), FileDefImpl::addUsingDirective(), NamespaceDefImpl::addUsingDirective(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), FileDefImpl::insertClass(), NamespaceDefImpl::insertClass(), FileDefImpl::insertConcept(), NamespaceDefImpl::insertConcept(), NamespaceDefImpl::insertMember(), FileDefImpl::insertNamespace(), NamespaceDefImpl::insertNamespace(), and doxmlparser.compound.memberdefType::set_add().
add() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedRefMap< T, Hash, KeyEqual, Map >::add (const char * k, T * obj) [inline]
Adds an object reference to the ordered vector if it was not added already. Return true if the reference was added, and false if an object with the same key was already added before
Definition at line 284 of file linkedmap.h.
    {
      if (find(k)==nullptr) // new element
      {
        std::string key(k ? k : "");
        m_lookup.insert({key,obj});
        m_entries.push_back(obj);
        return true;
      }
      else // already existing, don't add
      {
        return false;
      }
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries, LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup, and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedRefMap< T, Hash, KeyEqual, Map >::add (const QCString & k, T * obj) [inline]
Definition at line 299 of file linkedmap.h.
    {
      std::string key = k.str();
      if (find(key)==nullptr) // new element
      {
        m_lookup.insert({key,obj});
        m_entries.push_back(obj);
        return true;
      }
      else // already existing, don't add
      {
        return false;
      }
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries, LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup, QCString::str(), and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedRefMap< T, Hash, KeyEqual, Map >::add (const QCString & k, T * obj) [inline]
Definition at line 299 of file linkedmap.h.
    {
      std::string key = k.str();
      if (find(key)==nullptr) // new element
      {
        m_lookup.insert({key,obj});
        m_entries.push_back(obj);
        return true;
      }
      else // already existing, don't add
      {
        return false;
      }
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries, LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup, QCString::str(), and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
begin() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
iterator LinkedRefMap< T, Hash, KeyEqual, Map >::begin () [inline]
Definition at line 366 of file linkedmap.h.
{ return m_entries.begin(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
Referenced by ClassDefImpl::sortMemberLists(), FileDefImpl::sortMemberLists(), GroupDefImpl::sortMemberLists(), and NamespaceDefImpl::sortMemberLists().
begin() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
iterator LinkedRefMap< T, Hash, KeyEqual, Map >::begin () [inline]
Definition at line 366 of file linkedmap.h.
{ return m_entries.begin(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
begin() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_iterator LinkedRefMap< T, Hash, KeyEqual, Map >::begin () const [inline]
Definition at line 368 of file linkedmap.h.
{ return m_entries.cbegin(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
begin() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_iterator LinkedRefMap< T, Hash, KeyEqual, Map >::begin () const [inline]
Definition at line 368 of file linkedmap.h.
{ return m_entries.cbegin(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
clear() [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
void LinkedRefMap< T, Hash, KeyEqual, Map >::clear () [inline]
Definition at line 377 of file linkedmap.h.
    {
      m_entries.clear();
      m_lookup.clear();
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries, and LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup.
clear() [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
void LinkedRefMap< T, Hash, KeyEqual, Map >::clear () [inline]
Definition at line 377 of file linkedmap.h.
    {
      m_entries.clear();
      m_lookup.clear();
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries, and LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup.
del() [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedRefMap< T, Hash, KeyEqual, Map >::del (const QCString & key) [inline]
Removes an object from the container and deletes it. Returns true if the object was deleted or false it is was not found.
Definition at line 348 of file linkedmap.h.
    {
      auto it = m_lookup.find(key.str());
      if (it!=m_lookup.end())
      {
        auto vecit = std::find_if(m_entries.begin(),m_entries.end(),[obj=it->second](auto &el) { return el.get()==obj; });
        if (vecit!=m_entries.end()) // should always be true
        {
          m_entries.erase(vecit);
          m_lookup.erase(it);
          return true;
        }
      }
      return false;
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries, LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup, and QCString::str().
del() [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedRefMap< T, Hash, KeyEqual, Map >::del (const QCString & key) [inline]
Removes an object from the container and deletes it. Returns true if the object was deleted or false it is was not found.
Definition at line 348 of file linkedmap.h.
    {
      auto it = m_lookup.find(key.str());
      if (it!=m_lookup.end())
      {
        auto vecit = std::find_if(m_entries.begin(),m_entries.end(),[obj=it->second](auto &el) { return el.get()==obj; });
        if (vecit!=m_entries.end()) // should always be true
        {
          m_entries.erase(vecit);
          m_lookup.erase(it);
          return true;
        }
      }
      return false;
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries, LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup, and QCString::str().
empty() [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedRefMap< T, Hash, KeyEqual, Map >::empty () const [inline]
Definition at line 374 of file linkedmap.h.
{ return m_entries.empty(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
Referenced by NestingNodeContext::Private::addNamespaces(), NestingNodeContext::Private::addPages(), NamespaceDefImpl::findInnerCompound(), findScopeFromQualifiedName(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForNamespace(), SymbolResolver::Private::getResolvedTypeRec(), PageDefImpl::hasSubPages(), processTagLessClasses(), and writeGroupTreeNode().
empty() [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedRefMap< T, Hash, KeyEqual, Map >::empty () const [inline]
Definition at line 374 of file linkedmap.h.
{ return m_entries.empty(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
end() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
iterator LinkedRefMap< T, Hash, KeyEqual, Map >::end () [inline]
Definition at line 367 of file linkedmap.h.
{ return m_entries.end(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
Referenced by ClassDefImpl::sortMemberLists(), FileDefImpl::sortMemberLists(), GroupDefImpl::sortMemberLists(), and NamespaceDefImpl::sortMemberLists().
end() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
iterator LinkedRefMap< T, Hash, KeyEqual, Map >::end () [inline]
Definition at line 367 of file linkedmap.h.
{ return m_entries.end(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
end() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_iterator LinkedRefMap< T, Hash, KeyEqual, Map >::end () const [inline]
Definition at line 369 of file linkedmap.h.
{ return m_entries.cend(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
end() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_iterator LinkedRefMap< T, Hash, KeyEqual, Map >::end () const [inline]
Definition at line 369 of file linkedmap.h.
{ return m_entries.cend(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
find() [1/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedRefMap< T, Hash, KeyEqual, Map >::find (const char * key) [inline]
non-const wrapper for find() const
Definition at line 265 of file linkedmap.h.
    {
      return const_cast<T*>(static_cast<const LinkedRefMap&>(*this).find(key));
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find().
find() [2/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedRefMap< T, Hash, KeyEqual, Map >::find (const char * key) [inline]
non-const wrapper for find() const
Definition at line 265 of file linkedmap.h.
    {
      return const_cast<T*>(static_cast<const LinkedRefMap&>(*this).find(key));
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find().
find() [3/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const T * LinkedRefMap< T, Hash, KeyEqual, Map >::find (const char * key) const [inline]
find an object given the key. Returns a pointer to the object if found or nullptr if it is not found.
Definition at line 259 of file linkedmap.h.
    {
      return find(std::string(key ? key : ""));
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), and string.
find() [4/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const T * LinkedRefMap< T, Hash, KeyEqual, Map >::find (const char * key) const [inline]
find an object given the key. Returns a pointer to the object if found or nullptr if it is not found.
Definition at line 259 of file linkedmap.h.
    {
      return find(std::string(key ? key : ""));
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), and string.
find() [5/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedRefMap< T, Hash, KeyEqual, Map >::find (const QCString & key) [inline]
Definition at line 270 of file linkedmap.h.
    {
      return const_cast<T*>(static_cast<const LinkedRefMap&>(*this).find(key));
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find().
find() [6/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedRefMap< T, Hash, KeyEqual, Map >::find (const QCString & key) [inline]
Definition at line 270 of file linkedmap.h.
    {
      return const_cast<T*>(static_cast<const LinkedRefMap&>(*this).find(key));
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find().
find() [7/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const T * LinkedRefMap< T, Hash, KeyEqual, Map >::find (const QCString & key) const [inline]
find an object given the key. Returns a pointer to the object if found or nullptr if it is not found.
Definition at line 251 of file linkedmap.h.
    {
      auto it = m_lookup.find(key.str());
      return it!=m_lookup.end() ? it->second : nullptr;
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup, and QCString::str().
find() [8/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const T * LinkedRefMap< T, Hash, KeyEqual, Map >::find (const QCString & key) const [inline]
find an object given the key. Returns a pointer to the object if found or nullptr if it is not found.
Definition at line 251 of file linkedmap.h.
    {
      auto it = m_lookup.find(key.str());
      return it!=m_lookup.end() ? it->second : nullptr;
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup, and QCString::str().
find() [9/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedRefMap< T, Hash, KeyEqual, Map >::find (const std::string & key) [inline]
non-const wrapper for find() const
Definition at line 276 of file linkedmap.h.
    {
      return const_cast<T*>(static_cast<const LinkedRefMap&>(*this).find(key));
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find().
find() [10/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedRefMap< T, Hash, KeyEqual, Map >::find (const std::string & key) [inline]
non-const wrapper for find() const
Definition at line 276 of file linkedmap.h.
    {
      return const_cast<T*>(static_cast<const LinkedRefMap&>(*this).find(key));
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find().
find() [11/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const T * LinkedRefMap< T, Hash, KeyEqual, Map >::find (const std::string & key) const [inline]
find an object given the key. Returns a pointer to the object if found or nullptr if it is not found.
Definition at line 243 of file linkedmap.h.
    {
      auto it = m_lookup.find(key);
      return it!=m_lookup.end() ? it->second : nullptr;
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup.
Referenced by LinkedRefMap< T, Hash, KeyEqual, Map >::add(), GroupDefImpl::addClass(), GroupDefImpl::addConcept(), ClassDefImpl::addMembersToTemplateInstance(), GroupDefImpl::addNamespace(), LinkedRefMap< T, Hash, KeyEqual, Map >::find(), findGlobalMember(), ClassDefImpl::findInnerCompound(), NamespaceDefImpl::findInnerCompound(), NamespaceDefImpl::getMemberByName(), and LinkedRefMap< T, Hash, KeyEqual, Map >::prepend().
find() [12/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const T * LinkedRefMap< T, Hash, KeyEqual, Map >::find (const std::string & key) const [inline]
find an object given the key. Returns a pointer to the object if found or nullptr if it is not found.
Definition at line 243 of file linkedmap.h.
    {
      auto it = m_lookup.find(key);
      return it!=m_lookup.end() ? it->second : nullptr;
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup.
operator[]() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
Ptr & LinkedRefMap< T, Hash, KeyEqual, Map >::operator[] (size_t pos) [inline]
Definition at line 364 of file linkedmap.h.
{ return m_entries[pos]; }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
operator[]() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
Ptr & LinkedRefMap< T, Hash, KeyEqual, Map >::operator[] (size_t pos) [inline]
Definition at line 364 of file linkedmap.h.
{ return m_entries[pos]; }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
operator[]() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const Ptr & LinkedRefMap< T, Hash, KeyEqual, Map >::operator[] (size_t pos) const [inline]
Definition at line 365 of file linkedmap.h.
{ return m_entries[pos]; }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
operator[]() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const Ptr & LinkedRefMap< T, Hash, KeyEqual, Map >::operator[] (size_t pos) const [inline]
Definition at line 365 of file linkedmap.h.
{ return m_entries[pos]; }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
prepend() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedRefMap< T, Hash, KeyEqual, Map >::prepend (const char * k, T * obj) [inline]
Prepends an object reference to the ordered vector if it was not added already. Return true if the reference was added, and false if an object with the same key was already added before
Definition at line 317 of file linkedmap.h.
    {
      if (find(k)==nullptr) // new element
      {
        std::string key(k ? k : "");
        m_lookup.insert({key,obj});
        m_entries.insert(m_entries.begin(),obj);
        return true;
      }
      else // already existing, don't add
      {
        return false;
      }
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries, LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup, and string.
Referenced by FileDefImpl::addIncludedUsingDirectives().
prepend() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedRefMap< T, Hash, KeyEqual, Map >::prepend (const char * k, T * obj) [inline]
Prepends an object reference to the ordered vector if it was not added already. Return true if the reference was added, and false if an object with the same key was already added before
Definition at line 317 of file linkedmap.h.
    {
      if (find(k)==nullptr) // new element
      {
        std::string key(k ? k : "");
        m_lookup.insert({key,obj});
        m_entries.insert(m_entries.begin(),obj);
        return true;
      }
      else // already existing, don't add
      {
        return false;
      }
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries, LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup, and string.
prepend() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedRefMap< T, Hash, KeyEqual, Map >::prepend (const QCString & key, T * obj) [inline]
Definition at line 332 of file linkedmap.h.
    {
      if (find(key)==nullptr) // new element
      {
        m_lookup.insert({key.str(),obj});
        m_entries.insert(m_entries.begin(),obj);
        return true;
      }
      else // already existing, don't add
      {
        return false;
      }
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries, LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup, and QCString::str().
prepend() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedRefMap< T, Hash, KeyEqual, Map >::prepend (const QCString & key, T * obj) [inline]
Definition at line 332 of file linkedmap.h.
    {
      if (find(key)==nullptr) // new element
      {
        m_lookup.insert({key.str(),obj});
        m_entries.insert(m_entries.begin(),obj);
        return true;
      }
      else // already existing, don't add
      {
        return false;
      }
    }
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries, LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup, and QCString::str().
rbegin() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
reverse_iterator LinkedRefMap< T, Hash, KeyEqual, Map >::rbegin () [inline]
Definition at line 370 of file linkedmap.h.
{ return m_entries.rbegin(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
rbegin() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
reverse_iterator LinkedRefMap< T, Hash, KeyEqual, Map >::rbegin () [inline]
Definition at line 370 of file linkedmap.h.
{ return m_entries.rbegin(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
rbegin() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_reverse_iterator LinkedRefMap< T, Hash, KeyEqual, Map >::rbegin () const [inline]
Definition at line 372 of file linkedmap.h.
{ return m_entries.crbegin(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
rbegin() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_reverse_iterator LinkedRefMap< T, Hash, KeyEqual, Map >::rbegin () const [inline]
Definition at line 372 of file linkedmap.h.
{ return m_entries.crbegin(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
rend() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
reverse_iterator LinkedRefMap< T, Hash, KeyEqual, Map >::rend () [inline]
Definition at line 371 of file linkedmap.h.
{ return m_entries.rend(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
rend() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
reverse_iterator LinkedRefMap< T, Hash, KeyEqual, Map >::rend () [inline]
Definition at line 371 of file linkedmap.h.
{ return m_entries.rend(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
rend() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_reverse_iterator LinkedRefMap< T, Hash, KeyEqual, Map >::rend () const [inline]
Definition at line 373 of file linkedmap.h.
{ return m_entries.crend(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
rend() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_reverse_iterator LinkedRefMap< T, Hash, KeyEqual, Map >::rend () const [inline]
Definition at line 373 of file linkedmap.h.
{ return m_entries.crend(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
size() [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
size_t LinkedRefMap< T, Hash, KeyEqual, Map >::size () const [inline]
Definition at line 375 of file linkedmap.h.
{ return m_entries.size(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
Referenced by ClassContext::Private::createClasses(), NamespaceContext::Private::createClasses(), FileContext::Private::createClasses(), ModuleContext::Private::createClasses(), NamespaceContext::Private::createConstantgroups(), FileContext::Private::createConstantgroups(), ModuleContext::Private::createConstantgroups(), ModuleContext::Private::createExamples(), NamespaceContext::Private::createInlineClasses(), FileContext::Private::createInlineClasses(), ClassContext::Private::createInnerClasses(), NamespaceContext::Private::createNamespaces(), FileContext::Private::createNamespaces(), ModuleContext::Private::createNamespaces(), ModuleContext::Private::createPages(), GroupDefImpl::hasDetailedDescription(), lookupSymbol(), GroupDefImpl::numDocMembers(), NamespaceDefImpl::numDocMembers(), GroupDefImpl::writeDetailedDescription(), and writeGroupTreeNode().
size() [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
size_t LinkedRefMap< T, Hash, KeyEqual, Map >::size () const [inline]
Definition at line 375 of file linkedmap.h.
{ return m_entries.size(); }
References LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries.
Member Data Documentation
m_entries
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
Vec LinkedRefMap< T, Hash, KeyEqual, Map >::m_entries [private]
Definition at line 385 of file linkedmap.h.
Referenced by LinkedRefMap< T, Hash, KeyEqual, Map >::add(), LinkedRefMap< T, Hash, KeyEqual, Map >::begin(), LinkedRefMap< T, Hash, KeyEqual, Map >::clear(), LinkedRefMap< T, Hash, KeyEqual, Map >::del(), LinkedRefMap< T, Hash, KeyEqual, Map >::empty(), LinkedRefMap< T, Hash, KeyEqual, Map >::end(), LinkedRefMap< T, Hash, KeyEqual, Map >::operator[](), LinkedRefMap< T, Hash, KeyEqual, Map >::prepend(), LinkedRefMap< T, Hash, KeyEqual, Map >::rbegin(), LinkedRefMap< T, Hash, KeyEqual, Map >::rend(), and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
m_lookup
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
Map LinkedRefMap< T, Hash, KeyEqual, Map >::m_lookup [private]
Definition at line 384 of file linkedmap.h.
Referenced by LinkedRefMap< T, Hash, KeyEqual, Map >::add(), LinkedRefMap< T, Hash, KeyEqual, Map >::clear(), LinkedRefMap< T, Hash, KeyEqual, Map >::del(), LinkedRefMap< T, Hash, KeyEqual, Map >::find(), and LinkedRefMap< T, Hash, KeyEqual, Map >::prepend().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/linkedmap.h
doxygen/src/linkedmap.h