TemplateNodeTabbing Class Reference
Class representing an 'tabbing' tag in a template.
Public Member Functions
TemplateNodeTabbing (TemplateParser *parser, TemplateNode *parent, int line, const QCString &)
void render (TextStream &ts, TemplateContext *c)
TemplateNodeTabbing (TemplateParser *parser, TemplateNode *parent, int line, const QCString &)
void render (TextStream &ts, TemplateContext *c)
Private Attributes
TemplateNodeList m_nodes
Additional Inherited Members
Detailed Description
Class representing an 'tabbing' tag in a template.
Definition at line 4508 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeTabbing() [1/2]
TemplateNodeTabbing::TemplateNodeTabbing (TemplateParser * parser, TemplateNode * parent, int line, const QCString &) [inline]
Definition at line 4511 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeTabbing>(parser,parent,line)
    {
      TRACE(("{TemplateNodeTabbing()\n"));
      StringVector stopAt = { "endtabbing" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endtabbing
      TRACE(("}TemplateNodeTabbing()\n"));
    }
References m_nodes, TemplateParser::parse(), TemplateParser::removeNextToken(), and TRACE.
TemplateNodeTabbing() [2/2]
TemplateNodeTabbing::TemplateNodeTabbing (TemplateParser * parser, TemplateNode * parent, int line, const QCString &) [inline]
Definition at line 4511 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeTabbing>(parser,parent,line)
    {
      TRACE(("{TemplateNodeTabbing()\n"));
      StringVector stopAt = { "endtabbing" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endtabbing
      TRACE(("}TemplateNodeTabbing()\n"));
    }
References m_nodes, TemplateParser::parse(), TemplateParser::removeNextToken(), and TRACE.
Member Function Documentation
render() [1/2]
void TemplateNodeTabbing::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4520 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      bool wasTabbing = ci->tabbingEnabled();
      ci->enableTabbing(TRUE);
      m_nodes.render(ts,c);
      ci->enableTabbing(wasTabbing);
    }
References c, TemplateContextImpl::enableTabbing(), TemplateNodeCreator< TemplateNodeTabbing >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeTabbing >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::setLocation(), TemplateContextImpl::tabbingEnabled(), and TRUE.
render() [2/2]
void TemplateNodeTabbing::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4520 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      bool wasTabbing = ci->tabbingEnabled();
      ci->enableTabbing(TRUE);
      m_nodes.render(ts,c);
      ci->enableTabbing(wasTabbing);
    }
References c, TemplateContextImpl::enableTabbing(), TemplateNodeCreator< TemplateNodeTabbing >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeTabbing >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::setLocation(), TemplateContextImpl::tabbingEnabled(), and TRUE.
Member Data Documentation
m_nodes
TemplateNodeList TemplateNodeTabbing::m_nodes [private]
Definition at line 4531 of file template.cpp.
Referenced by render(), and TemplateNodeTabbing().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp