TranslatorDutch Class Reference
#include <translator_nl.h>
Public Member Functions
QCString idLanguage ()
QCString latexLanguageSupportCommand ()
QCString trISOLang ()
virtual QCString getLanguageString ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const QCString &s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trEnumerationValueDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const QCString &date, const QCString &projName)
QCString trClassDiagram (const QCString &clName)
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
QCString trNamespaceList ()
QCString trNamespaceListDescription (bool extractAll)
QCString trFriends ()
QCString trRelatedFunctionDocumentation ()
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
QCString trFileReference (const QCString &fileName)
QCString trNamespaceReference (const QCString &namespaceName)
QCString trPublicMembers ()
QCString trPublicSlots ()
QCString trSignals ()
QCString trStaticPublicMembers ()
QCString trProtectedMembers ()
QCString trProtectedSlots ()
QCString trStaticProtectedMembers ()
QCString trPrivateMembers ()
QCString trPrivateSlots ()
QCString trStaticPrivateMembers ()
QCString trWriteList (int numEntries)
QCString trInheritsList (int numEntries)
QCString trInheritedByList (int numEntries)
QCString trReimplementedFromList (int numEntries)
QCString trReimplementedInList (int numEntries)
QCString trNamespaceMembers ()
QCString trNamespaceMemberDescription (bool extractAll)
QCString trNamespaceIndex ()
QCString trNamespaceDocumentation ()
QCString trNamespaces ()
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
QCString trReturnValues ()
QCString trMainPage ()
QCString trPageAbbreviation ()
QCString trDefinedAtLineInSourceFile ()
QCString trDefinedInSourceFile ()
QCString trDeprecated ()
QCString trCollaborationDiagram (const QCString &clName)
QCString trInclDepGraph (const QCString &fName)
QCString trConstructorDocumentation ()
QCString trGotoSourceCode ()
QCString trGotoDocumentation ()
QCString trPrecondition ()
QCString trPostcondition ()
QCString trInvariant ()
QCString trInitialValue ()
QCString trCode ()
QCString trGraphicalHierarchy ()
QCString trGotoGraphicalHierarchy ()
QCString trGotoTextualHierarchy ()
QCString trPageIndex ()
QCString trNote ()
QCString trPublicTypes ()
QCString trPublicAttribs ()
QCString trStaticPublicAttribs ()
QCString trProtectedTypes ()
QCString trProtectedAttribs ()
QCString trStaticProtectedAttribs ()
QCString trPrivateTypes ()
QCString trPrivateAttribs ()
QCString trStaticPrivateAttribs ()
QCString trTodo ()
QCString trTodoList ()
QCString trReferencedBy ()
QCString trRemarks ()
QCString trAttention ()
QCString trInclByDepGraph ()
QCString trSince ()
QCString trLegendTitle ()
QCString trLegendDocs ()
QCString trLegend ()
QCString trTest ()
QCString trTestList ()
QCString trProperties ()
QCString trPropertyDocumentation ()
QCString trClasses ()
QCString trPackage (const QCString &name)
QCString trPackageListDescription ()
QCString trPackages ()
QCString trDefineValue ()
QCString trBug ()
QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString trPackageList ()
virtual QCString trFlowchart ()
QCString idLanguage ()
QCString latexLanguageSupportCommand ()
QCString trISOLang ()
virtual QCString getLanguageString ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const QCString &s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trEnumerationValueDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const QCString &date, const QCString &projName)
QCString trClassDiagram (const QCString &clName)
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
QCString trNamespaceList ()
QCString trNamespaceListDescription (bool extractAll)
QCString trFriends ()
QCString trRelatedFunctionDocumentation ()
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
QCString trFileReference (const QCString &fileName)
QCString trNamespaceReference (const QCString &namespaceName)
QCString trPublicMembers ()
QCString trPublicSlots ()
QCString trSignals ()
QCString trStaticPublicMembers ()
QCString trProtectedMembers ()
QCString trProtectedSlots ()
QCString trStaticProtectedMembers ()
QCString trPrivateMembers ()
QCString trPrivateSlots ()
QCString trStaticPrivateMembers ()
QCString trWriteList (int numEntries)
QCString trInheritsList (int numEntries)
QCString trInheritedByList (int numEntries)
QCString trReimplementedFromList (int numEntries)
QCString trReimplementedInList (int numEntries)
QCString trNamespaceMembers ()
QCString trNamespaceMemberDescription (bool extractAll)
QCString trNamespaceIndex ()
QCString trNamespaceDocumentation ()
QCString trNamespaces ()
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
QCString trReturnValues ()
QCString trMainPage ()
QCString trPageAbbreviation ()
QCString trDefinedAtLineInSourceFile ()
QCString trDefinedInSourceFile ()
QCString trDeprecated ()
QCString trCollaborationDiagram (const QCString &clName)
QCString trInclDepGraph (const QCString &fName)
QCString trConstructorDocumentation ()
QCString trGotoSourceCode ()
QCString trGotoDocumentation ()
QCString trPrecondition ()
QCString trPostcondition ()
QCString trInvariant ()
QCString trInitialValue ()
QCString trCode ()
QCString trGraphicalHierarchy ()
QCString trGotoGraphicalHierarchy ()
QCString trGotoTextualHierarchy ()
QCString trPageIndex ()
QCString trNote ()
QCString trPublicTypes ()
QCString trPublicAttribs ()
QCString trStaticPublicAttribs ()
QCString trProtectedTypes ()
QCString trProtectedAttribs ()
QCString trStaticProtectedAttribs ()
QCString trPrivateTypes ()
QCString trPrivateAttribs ()
QCString trStaticPrivateAttribs ()
QCString trTodo ()
QCString trTodoList ()
QCString trReferencedBy ()
QCString trRemarks ()
QCString trAttention ()
QCString trInclByDepGraph ()
QCString trSince ()
QCString trLegendTitle ()
QCString trLegendDocs ()
QCString trLegend ()
QCString trTest ()
QCString trTestList ()
QCString trProperties ()
QCString trPropertyDocumentation ()
QCString trClasses ()
QCString trPackage (const QCString &name)
QCString trPackageListDescription ()
QCString trPackages ()
QCString trDefineValue ()
QCString trBug ()
QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString trPackageList ()
virtual QCString trFlowchart ()
Detailed Description
Definition at line 21 of file translator_nl.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorDutch::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 41 of file translator_nl.h.
    {
      return "0x413 Dutch";
    }
getLanguageString() [2/2]
virtual QCString TranslatorDutch::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 41 of file translator_nl.h.
    {
      return "0x413 Dutch";
    }
idLanguage() [1/2]
QCString TranslatorDutch::idLanguage () [inline], [virtual]
Implements Translator.
Definition at line 24 of file translator_nl.h.
    { return "dutch"; }
idLanguage() [2/2]
QCString TranslatorDutch::idLanguage () [inline], [virtual]
Implements Translator.
Definition at line 24 of file translator_nl.h.
    { return "dutch"; }
latexLanguageSupportCommand() [1/2]
QCString TranslatorDutch::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 37 of file translator_nl.h.
    { return "\\usepackage[dutch]{babel}\n"; }
latexLanguageSupportCommand() [2/2]
QCString TranslatorDutch::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 37 of file translator_nl.h.
    { return "\\usepackage[dutch]{babel}\n"; }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorDutch::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1524 of file translator_nl.h.
    { return "Additionele Overge&euml;rfde Members"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorDutch::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1524 of file translator_nl.h.
    { return "Additionele Overge&euml;rfde Members"; }
trAll() [1/2]
virtual QCString TranslatorDutch::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1065 of file translator_nl.h.
    {
      return "Alle";
    }
trAll() [2/2]
virtual QCString TranslatorDutch::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1065 of file translator_nl.h.
    {
      return "Alle";
    }
trAndMore() [1/2]
virtual QCString TranslatorDutch::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1501 of file translator_nl.h.
    { return "en "+number+ " anderen..."; }
trAndMore() [2/2]
virtual QCString TranslatorDutch::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1501 of file translator_nl.h.
    { return "en "+number+ " anderen..."; }
trAttention() [1/2]
QCString TranslatorDutch::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_nl.h.
    {
      return "Attentie";
    }
trAttention() [2/2]
QCString TranslatorDutch::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_nl.h.
    {
      return "Attentie";
    }
trAuthor() [1/2]
virtual QCString TranslatorDutch::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 942 of file translator_nl.h.
    {
      QCString result((first_capital ? "Auteur" : "auteur"));
      if (!singular) result+="s";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorDutch::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 942 of file translator_nl.h.
    {
      QCString result((first_capital ? "Auteur" : "auteur"));
      if (!singular) result+="s";
      return result;
    }
trBug() [1/2]
QCString TranslatorDutch::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 800 of file translator_nl.h.
    {
      return "Bug";
    }
trBug() [2/2]
QCString TranslatorDutch::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 800 of file translator_nl.h.
    {
      return "Bug";
    }
trBugList() [1/2]
QCString TranslatorDutch::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 805 of file translator_nl.h.
    {
      return "Bug Lijst";
    }
trBugList() [2/2]
QCString TranslatorDutch::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 805 of file translator_nl.h.
    {
      return "Bug Lijst";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorDutch::trCallerGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1186 of file translator_nl.h.
    {
      return "Hier is de caller graaf voor deze functie:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorDutch::trCallerGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1186 of file translator_nl.h.
    {
      return "Hier is de caller graaf voor deze functie:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorDutch::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1070 of file translator_nl.h.
    {
      return "Hier is de call graaf voor deze functie:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorDutch::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1070 of file translator_nl.h.
    {
      return "Hier is de call graaf voor deze functie:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorDutch::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1477 of file translator_nl.h.
    { return "Bibliografie"; }
trCiteReferences() [2/2]
virtual QCString TranslatorDutch::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1477 of file translator_nl.h.
    { return "Bibliografie"; }
trClass() [1/2]
virtual QCString TranslatorDutch::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 863 of file translator_nl.h.
    {
      QCString result((first_capital ? "Klasse" : "klasse"));
      if (!singular) result+="n";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorDutch::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 863 of file translator_nl.h.
    {
      QCString result((first_capital ? "Klasse" : "klasse"));
      if (!singular) result+="n";
      return result;
    }
trClassDiagram() [1/2]
QCString TranslatorDutch::trClassDiagram (const QCString & clName) [inline], [virtual]
Implements Translator.
Definition at line 236 of file translator_nl.h.
    {
      return "Klasse diagram voor "+clName;
    }
trClassDiagram() [2/2]
QCString TranslatorDutch::trClassDiagram (const QCString & clName) [inline], [virtual]
Implements Translator.
Definition at line 236 of file translator_nl.h.
    {
      return "Klasse diagram voor "+clName;
    }
trClassDocumentation() [1/2]
QCString TranslatorDutch::trClassDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 181 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Klassen Documentatie";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klassen Documentatie";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClassDocumentation() [2/2]
QCString TranslatorDutch::trClassDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 181 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Klassen Documentatie";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klassen Documentatie";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses() [1/2]
QCString TranslatorDutch::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 770 of file translator_nl.h.
    {
      return "Klassen";
    }
trClasses() [2/2]
QCString TranslatorDutch::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 770 of file translator_nl.h.
    {
      return "Klassen";
    }
trClassHierarchy() [1/2]
QCString TranslatorDutch::trClassHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 92 of file translator_nl.h.
    { return "Klasse Hi&euml;rarchie"; }
trClassHierarchy() [2/2]
QCString TranslatorDutch::trClassHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 92 of file translator_nl.h.
    { return "Klasse Hi&euml;rarchie"; }
trClassHierarchyDescription() [1/2]
QCString TranslatorDutch::trClassHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 108 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Hieronder is een hi&euml;rarchische lijst met alle entiteiten:";
      }
      else
      {
        return "Deze inheritance lijst is min of meer alfabetisch gesorteerd:";
      }
    }
References Config_getBool.
trClassHierarchyDescription() [2/2]
QCString TranslatorDutch::trClassHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 108 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Hieronder is een hi&euml;rarchische lijst met alle entiteiten:";
      }
      else
      {
        return "Deze inheritance lijst is min of meer alfabetisch gesorteerd:";
      }
    }
References Config_getBool.
trClassMethods() [1/2]
virtual QCString TranslatorDutch::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1562 of file translator_nl.h.
    {
      return "Klasse Methoden";
    }
trClassMethods() [2/2]
virtual QCString TranslatorDutch::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1562 of file translator_nl.h.
    {
      return "Klasse Methoden";
    }
trCode() [1/2]
QCString TranslatorDutch::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 550 of file translator_nl.h.
    {
      return "code";
    }
trCode() [2/2]
QCString TranslatorDutch::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 550 of file translator_nl.h.
    {
      return "code";
    }
trCollaborationDiagram() [1/2]
QCString TranslatorDutch::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 505 of file translator_nl.h.
    {
      return "Collaboratie diagram voor "+clName+":";
    }
trCollaborationDiagram() [2/2]
QCString TranslatorDutch::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 505 of file translator_nl.h.
    {
      return "Collaboratie diagram voor "+clName+":";
    }
trCompoundIndex() [1/2]
QCString TranslatorDutch::trCompoundIndex () [inline], [virtual]
Implements Translator.
Definition at line 175 of file translator_nl.h.
    { return "Klasse Index"; }
trCompoundIndex() [2/2]
QCString TranslatorDutch::trCompoundIndex () [inline], [virtual]
Implements Translator.
Definition at line 175 of file translator_nl.h.
    { return "Klasse Index"; }
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorDutch::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1225 of file translator_nl.h.
    { return "Data Type Index"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorDutch::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1225 of file translator_nl.h.
    { return "Data Type Index"; }
trCompoundList() [1/2]
QCString TranslatorDutch::trCompoundList () [inline], [virtual]
Implements Translator.
Definition at line 94 of file translator_nl.h.
    { return "Klasse Lijst"; }
trCompoundList() [2/2]
QCString TranslatorDutch::trCompoundList () [inline], [virtual]
Implements Translator.
Definition at line 94 of file translator_nl.h.
    { return "Klasse Lijst"; }
trCompoundListDescription() [1/2]
QCString TranslatorDutch::trCompoundListDescription () [inline], [virtual]
Implements Translator.
Definition at line 126 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Hieronder volgen de structs "
               "met voor elk een korte beschrijving:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Hieronder volgen de klassen "
               "met voor elk een korte beschrijving:";
      }
      else
      {
        return "Hieronder volgen de klassen, structs en "
               "unions met voor elk een korte beschrijving:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
QCString TranslatorDutch::trCompoundListDescription () [inline], [virtual]
Implements Translator.
Definition at line 126 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Hieronder volgen de structs "
               "met voor elk een korte beschrijving:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Hieronder volgen de klassen "
               "met voor elk een korte beschrijving:";
      }
      else
      {
        return "Hieronder volgen de klassen, structs en "
               "unions met voor elk een korte beschrijving:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorDutch::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1208 of file translator_nl.h.
    { return "Hieronder volgen de data types elk een korte beschrijving:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorDutch::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1208 of file translator_nl.h.
    { return "Hieronder volgen de data types elk een korte beschrijving:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorDutch::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1200 of file translator_nl.h.
    { return "Lijst met data types"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorDutch::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1200 of file translator_nl.h.
    { return "Lijst met data types"; }
trCompoundMembers() [1/2]
QCString TranslatorDutch::trCompoundMembers () [inline], [virtual]
Implements Translator.
Definition at line 98 of file translator_nl.h.
    { return "Klasse Members"; }
trCompoundMembers() [2/2]
QCString TranslatorDutch::trCompoundMembers () [inline], [virtual]
Implements Translator.
Definition at line 98 of file translator_nl.h.
    { return "Klasse Members"; }
trCompoundMembersDescription() [1/2]
QCString TranslatorDutch::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 144 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="klasse members met links naar ";
      if (!extractAll) result+="de klasse documentatie voor elke member:";
      else result+="de klassen waartoe ze behoren:";
      return result;
    }
trCompoundMembersDescription() [2/2]
QCString TranslatorDutch::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 144 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="klasse members met links naar ";
      if (!extractAll) result+="de klasse documentatie voor elke member:";
      else result+="de klassen waartoe ze behoren:";
      return result;
    }
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorDutch::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1212 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="data types met links naar ";
      if (!extractAll) result+="de klasse documentatie voor elke member:";
      else result+="de klassen waartoe ze behoren:";
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorDutch::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1212 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="data types met links naar ";
      if (!extractAll) result+="de klasse documentatie voor elke member:";
      else result+="de klassen waartoe ze behoren:";
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorDutch::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1204 of file translator_nl.h.
    { return "Data velden"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorDutch::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1204 of file translator_nl.h.
    { return "Data velden"; }
trCompoundReference() [1/2]
QCString TranslatorDutch::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
Implements Translator.
Definition at line 284 of file translator_nl.h.
    {
      QCString result=clName;
      if (isTemplate) result+=" Template";
      switch(compType)
      {
        case ClassDef::Class: result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      result+=" Referentie";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
QCString TranslatorDutch::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
Implements Translator.
Definition at line 284 of file translator_nl.h.
    {
      QCString result=clName;
      if (isTemplate) result+=" Template";
      switch(compType)
      {
        case ClassDef::Class: result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      result+=" Referentie";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorDutch::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1266 of file translator_nl.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Module"; break;
        case ClassDef::Struct: result+=" Type"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Referentie";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorDutch::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1266 of file translator_nl.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Module"; break;
        case ClassDef::Struct: result+=" Type"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Referentie";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorDutch::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 1802 of file translator_nl.h.
    {
      QCString result=clName;
      if (isLocal) result+=" Lokale";
      switch(compType)
      {
        case ClassDef::Class: result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      result+=" Referentie";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorDutch::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 1802 of file translator_nl.h.
    {
      QCString result=clName;
      if (isLocal) result+=" Lokale";
      switch(compType)
      {
        case ClassDef::Class: result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      result+=" Referentie";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
QCString TranslatorDutch::trCompounds () [inline], [virtual]
Implements Translator.
Definition at line 227 of file translator_nl.h.
    { return "Klassen"; }
trCompounds() [2/2]
QCString TranslatorDutch::trCompounds () [inline], [virtual]
Implements Translator.
Definition at line 227 of file translator_nl.h.
    { return "Klassen"; }
trConcept() [1/2]
virtual QCString TranslatorDutch::trConcept (bool first_capital, bool singular) [inline], [virtual]
Implements Translator.
Definition at line 1838 of file translator_nl.h.
    {
      QCString result((first_capital ? "Concept" : "concept"));
      if (!singular) result+="en";
      return result;
    }
trConcept() [2/2]
virtual QCString TranslatorDutch::trConcept (bool first_capital, bool singular) [inline], [virtual]
Implements Translator.
Definition at line 1838 of file translator_nl.h.
    {
      QCString result((first_capital ? "Concept" : "concept"));
      if (!singular) result+="en";
      return result;
    }
trConceptDefinition() [1/2]
virtual QCString TranslatorDutch::trConceptDefinition () [inline], [virtual]
Implements Translator.
Definition at line 1869 of file translator_nl.h.
    {
      return "Concept definitie";
    }
trConceptDefinition() [2/2]
virtual QCString TranslatorDutch::trConceptDefinition () [inline], [virtual]
Implements Translator.
Definition at line 1869 of file translator_nl.h.
    {
      return "Concept definitie";
    }
trConceptDocumentation() [1/2]
virtual QCString TranslatorDutch::trConceptDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1858 of file translator_nl.h.
    { return "Concept Documentatie"; }
trConceptDocumentation() [2/2]
virtual QCString TranslatorDutch::trConceptDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1858 of file translator_nl.h.
    { return "Concept Documentatie"; }
trConceptIndex() [1/2]
virtual QCString TranslatorDutch::trConceptIndex () [inline], [virtual]
Implements Translator.
Definition at line 1855 of file translator_nl.h.
    { return "Concept Index"; }
trConceptIndex() [2/2]
virtual QCString TranslatorDutch::trConceptIndex () [inline], [virtual]
Implements Translator.
Definition at line 1855 of file translator_nl.h.
    { return "Concept Index"; }
trConceptList() [1/2]
virtual QCString TranslatorDutch::trConceptList () [inline], [virtual]
Implements Translator.
Definition at line 1852 of file translator_nl.h.
    { return "Concept Lijst"; }
trConceptList() [2/2]
virtual QCString TranslatorDutch::trConceptList () [inline], [virtual]
Implements Translator.
Definition at line 1852 of file translator_nl.h.
    { return "Concept Lijst"; }
trConceptListDescription() [1/2]
virtual QCString TranslatorDutch::trConceptListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 1861 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="concepten, elk met een korte beschrijving:";
      return result;
    }
trConceptListDescription() [2/2]
virtual QCString TranslatorDutch::trConceptListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 1861 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="concepten, elk met een korte beschrijving:";
      return result;
    }
trConceptReference() [1/2]
virtual QCString TranslatorDutch::trConceptReference (const QCString & conceptName) [inline], [virtual]
Implements Translator.
Definition at line 1845 of file translator_nl.h.
    {
      QCString result=conceptName;
      result+=" Concept Referentie";
      return result;
    }
trConceptReference() [2/2]
virtual QCString TranslatorDutch::trConceptReference (const QCString & conceptName) [inline], [virtual]
Implements Translator.
Definition at line 1845 of file translator_nl.h.
    {
      QCString result=conceptName;
      result+=" Concept Referentie";
      return result;
    }
trConstantDocumentation() [1/2]
virtual QCString TranslatorDutch::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1756 of file translator_nl.h.
    { return "Documentatie van konstanten"; }
trConstantDocumentation() [2/2]
virtual QCString TranslatorDutch::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1756 of file translator_nl.h.
    { return "Documentatie van konstanten"; }
trConstantGroupReference() [1/2]
virtual QCString TranslatorDutch::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1599 of file translator_nl.h.
    {
      QCString result=namespaceName;
      result+=" Konstanten Groepen Referentie";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorDutch::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1599 of file translator_nl.h.
    {
      QCString result=namespaceName;
      result+=" Konstanten Groepen Referentie";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorDutch::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1595 of file translator_nl.h.
    { return "Konstanten Groepen"; }
trConstantGroups() [2/2]
virtual QCString TranslatorDutch::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1595 of file translator_nl.h.
    { return "Konstanten Groepen"; }
trConstants() [1/2]
virtual QCString TranslatorDutch::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 1754 of file translator_nl.h.
    { return "Konstanten"; }
trConstants() [2/2]
virtual QCString TranslatorDutch::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 1754 of file translator_nl.h.
    { return "Konstanten"; }
trConstructorDocumentation() [1/2]
QCString TranslatorDutch::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 515 of file translator_nl.h.
    {
      return "Constructor & Destructor Documentatie";
    }
trConstructorDocumentation() [2/2]
QCString TranslatorDutch::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 515 of file translator_nl.h.
    {
      return "Constructor & Destructor Documentatie";
    }
trCopyright() [1/2]
virtual QCString TranslatorDutch::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1481 of file translator_nl.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorDutch::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1481 of file translator_nl.h.
    { return "Copyright"; }
trCustomReference() [1/2]
virtual QCString TranslatorDutch::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 1750 of file translator_nl.h.
    { return name+" Referentie"; }
References setup::name.
trCustomReference() [2/2]
virtual QCString TranslatorDutch::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 1750 of file translator_nl.h.
    { return name+" Referentie"; }
References setup::name.
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorDutch::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1826 of file translator_nl.h.
    { return "Documentatie van data members"; }
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorDutch::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1826 of file translator_nl.h.
    { return "Documentatie van data members"; }
trDataMembers() [1/2]
virtual QCString TranslatorDutch::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 1824 of file translator_nl.h.
    { return "Data members"; }
trDataMembers() [2/2]
virtual QCString TranslatorDutch::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 1824 of file translator_nl.h.
    { return "Data members"; }
trDataTypes() [1/2]
virtual QCString TranslatorDutch::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1249 of file translator_nl.h.
    { return "Data Types"; }
trDataTypes() [2/2]
virtual QCString TranslatorDutch::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1249 of file translator_nl.h.
    { return "Data Types"; }
trDate() [1/2]
QCString TranslatorDutch::trDate () [inline], [virtual]
Implements Translator.
Definition at line 244 of file translator_nl.h.
    { return "Datum"; }
trDate() [2/2]
QCString TranslatorDutch::trDate () [inline], [virtual]
Implements Translator.
Definition at line 244 of file translator_nl.h.
    { return "Datum"; }
trDateTime() [1/2]
virtual QCString TranslatorDutch::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Implements Translator.
Definition at line 1434 of file translator_nl.h.
    {
      static const char *days[] = { "Ma","Di","Wo","Do","Vr","Za","Zo" };
      static const char *months[] = { "Jan","Feb","Maa","Apr","Mei","Jun","Jul","Aug","Sep","Okt","Nov","Dec" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorDutch::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Implements Translator.
Definition at line 1434 of file translator_nl.h.
    {
      static const char *days[] = { "Ma","Di","Wo","Do","Vr","Za","Zo" };
      static const char *months[] = { "Jan","Feb","Maa","Apr","Mei","Jun","Jul","Aug","Sep","Okt","Nov","Dec" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorDutch::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1450 of file translator_nl.h.
    {
      static const char *days_short[] = { "ma", "di", "wo", "do", "vr", "za", "zo" };
      static const char *days_full[] = { "maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorDutch::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1450 of file translator_nl.h.
    {
      static const char *days_short[] = { "ma", "di", "wo", "do", "vr", "za", "zo" };
      static const char *days_full[] = { "maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorDutch::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1466 of file translator_nl.h.
    {
      static const char *dayPeriod[] = { "a.m.", "p.m." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorDutch::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1466 of file translator_nl.h.
    {
      static const char *dayPeriod[] = { "a.m.", "p.m." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
QCString TranslatorDutch::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 482 of file translator_nl.h.
    {
      return "De definitie bevindt zich op regel @0 in het bestand @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
QCString TranslatorDutch::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 482 of file translator_nl.h.
    {
      return "De definitie bevindt zich op regel @0 in het bestand @1.";
    }
trDefinedIn() [1/2]
QCString TranslatorDutch::trDefinedIn () [inline], [virtual]
Implements Translator.
Definition at line 88 of file translator_nl.h.
    { return "gedefinieerd in"; }
trDefinedIn() [2/2]
QCString TranslatorDutch::trDefinedIn () [inline], [virtual]
Implements Translator.
Definition at line 88 of file translator_nl.h.
    { return "gedefinieerd in"; }
trDefinedInSourceFile() [1/2]
QCString TranslatorDutch::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 486 of file translator_nl.h.
    {
      return "De definitie bevindt zich in het bestand @0.";
    }
trDefinedInSourceFile() [2/2]
QCString TranslatorDutch::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 486 of file translator_nl.h.
    {
      return "De definitie bevindt zich in het bestand @0.";
    }
trDefineDocumentation() [1/2]
QCString TranslatorDutch::trDefineDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 215 of file translator_nl.h.
    { return "Documentatie van macro's"; }
trDefineDocumentation() [2/2]
QCString TranslatorDutch::trDefineDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 215 of file translator_nl.h.
    { return "Documentatie van macro's"; }
trDefines() [1/2]
QCString TranslatorDutch::trDefines () [inline], [virtual]
Implements Translator.
Definition at line 203 of file translator_nl.h.
    { return "Macros"; }
trDefines() [2/2]
QCString TranslatorDutch::trDefines () [inline], [virtual]
Implements Translator.
Definition at line 203 of file translator_nl.h.
    { return "Macros"; }
trDefineValue() [1/2]
QCString TranslatorDutch::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 790 of file translator_nl.h.
    {
      return "Waarde:";
    }
trDefineValue() [2/2]
QCString TranslatorDutch::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 790 of file translator_nl.h.
    {
      return "Waarde:";
    }
trDeprecated() [1/2]
QCString TranslatorDutch::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 495 of file translator_nl.h.
    {
      return "Verouderd";
    }
trDeprecated() [2/2]
QCString TranslatorDutch::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 495 of file translator_nl.h.
    {
      return "Verouderd";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorDutch::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 994 of file translator_nl.h.
    {
      return "Deprecated Lijst";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorDutch::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 994 of file translator_nl.h.
    {
      return "Deprecated Lijst";
    }
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorDutch::trDesignUnitDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1832 of file translator_nl.h.
    { return "Ontwerp Eenheid Documentatie"; }
Referenced by trClassDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorDutch::trDesignUnitDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1832 of file translator_nl.h.
    { return "Ontwerp Eenheid Documentatie"; }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorDutch::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 1641 of file translator_nl.h.
    { return "Ontwerp Eenheid Hi&euml;rarchie"; }
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorDutch::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 1641 of file translator_nl.h.
    { return "Ontwerp Eenheid Hi&euml;rarchie"; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorDutch::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 1656 of file translator_nl.h.
    { return "Ontwerp Eenheid Index"; }
trDesignUnitIndex() [2/2]
virtual QCString TranslatorDutch::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 1656 of file translator_nl.h.
    { return "Ontwerp Eenheid Index"; }
trDesignUnitList() [1/2]
virtual QCString TranslatorDutch::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 1644 of file translator_nl.h.
    { return "Ontwerp Eenheid Lijst"; }
trDesignUnitList() [2/2]
virtual QCString TranslatorDutch::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 1644 of file translator_nl.h.
    { return "Ontwerp Eenheid Lijst"; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorDutch::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 1650 of file translator_nl.h.
    {
      return "hieronder volgt de lijst met all ontwerp eenheden met links "
             "naar de entiteiten waar ze bij behoren:";
    }
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorDutch::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 1650 of file translator_nl.h.
    {
      return "hieronder volgt de lijst met all ontwerp eenheden met links "
             "naar de entiteiten waar ze bij behoren:";
    }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorDutch::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 1647 of file translator_nl.h.
    { return "Ontwerp Eenheid Members"; }
trDesignUnitMembers() [2/2]
virtual QCString TranslatorDutch::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 1647 of file translator_nl.h.
    { return "Ontwerp Eenheid Members"; }
trDesignUnits() [1/2]
virtual QCString TranslatorDutch::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 1659 of file translator_nl.h.
    { return "Ontwerp Eenheden"; }
trDesignUnits() [2/2]
virtual QCString TranslatorDutch::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 1659 of file translator_nl.h.
    { return "Ontwerp Eenheden"; }
trDetailedDescription() [1/2]
QCString TranslatorDutch::trDetailedDescription () [inline], [virtual]
Implements Translator.
Definition at line 49 of file translator_nl.h.
    { return "Gedetailleerde Beschrijving"; }
trDetailedDescription() [2/2]
QCString TranslatorDutch::trDetailedDescription () [inline], [virtual]
Implements Translator.
Definition at line 49 of file translator_nl.h.
    { return "Gedetailleerde Beschrijving"; }
trDetailLevel() [1/2]
virtual QCString TranslatorDutch::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1493 of file translator_nl.h.
    { return "detail niveau"; }
trDetailLevel() [2/2]
virtual QCString TranslatorDutch::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1493 of file translator_nl.h.
    { return "detail niveau"; }
trDictionaries() [1/2]
virtual QCString TranslatorDutch::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 1762 of file translator_nl.h.
    { return "Vertalingslijsten"; }
trDictionaries() [2/2]
virtual QCString TranslatorDutch::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 1762 of file translator_nl.h.
    { return "Vertalingslijsten"; }
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorDutch::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1764 of file translator_nl.h.
    { return "Documentatie van vertalingslijsten"; }
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorDutch::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1764 of file translator_nl.h.
    { return "Documentatie van vertalingslijsten"; }
trDir() [1/2]
virtual QCString TranslatorDutch::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1160 of file translator_nl.h.
    {
      QCString result((first_capital ? "Folder" : "folder"));
      if (!singular) result+="s";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorDutch::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1160 of file translator_nl.h.
    {
      QCString result((first_capital ? "Folder" : "folder"));
      if (!singular) result+="s";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorDutch::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1485 of file translator_nl.h.
    { return "Folder afhankelijkheidsgraaf voor "+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorDutch::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1485 of file translator_nl.h.
    { return "Folder afhankelijkheidsgraaf voor "+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorDutch::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1142 of file translator_nl.h.
    { return "Folder Documentatie"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorDutch::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1142 of file translator_nl.h.
    { return "Folder Documentatie"; }
trDirectories() [1/2]
virtual QCString TranslatorDutch::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1148 of file translator_nl.h.
    { return "Folders"; }
trDirectories() [2/2]
virtual QCString TranslatorDutch::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1148 of file translator_nl.h.
    { return "Folders"; }
trDirIndex() [1/2]
virtual QCString TranslatorDutch::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1136 of file translator_nl.h.
    { return "Folder Hi&euml;rarchie"; }
trDirIndex() [2/2]
virtual QCString TranslatorDutch::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1136 of file translator_nl.h.
    { return "Folder Hi&euml;rarchie"; }
trDirReference() [1/2]
virtual QCString TranslatorDutch::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1154 of file translator_nl.h.
    { QCString result=dirName; result+=" Folder Referentie"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorDutch::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1154 of file translator_nl.h.
    { QCString result=dirName; result+=" Folder Referentie"; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorDutch::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1384 of file translator_nl.h.
    {
      return name+" Relatie";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorDutch::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1384 of file translator_nl.h.
    {
      return name+" Relatie";
    }
References setup::name.
trDocumentation() [1/2]
QCString TranslatorDutch::trDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 169 of file translator_nl.h.
    { return "Documentatie"; }
trDocumentation() [2/2]
QCString TranslatorDutch::trDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 169 of file translator_nl.h.
    { return "Documentatie"; }
trEnumerations() [1/2]
QCString TranslatorDutch::trEnumerations () [inline], [virtual]
Implements Translator.
Definition at line 207 of file translator_nl.h.
    { return "Enumeraties"; }
trEnumerations() [2/2]
QCString TranslatorDutch::trEnumerations () [inline], [virtual]
Implements Translator.
Definition at line 207 of file translator_nl.h.
    { return "Enumeraties"; }
trEnumerationTypeDocumentation() [1/2]
QCString TranslatorDutch::trEnumerationTypeDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 219 of file translator_nl.h.
    { return "Documentatie van enumeratie types"; }
trEnumerationTypeDocumentation() [2/2]
QCString TranslatorDutch::trEnumerationTypeDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 219 of file translator_nl.h.
    { return "Documentatie van enumeratie types"; }
trEnumerationValueDocumentation() [1/2]
QCString TranslatorDutch::trEnumerationValueDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 221 of file translator_nl.h.
    { return "Documentatie van enumeratie waarden"; }
trEnumerationValueDocumentation() [2/2]
QCString TranslatorDutch::trEnumerationValueDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 221 of file translator_nl.h.
    { return "Documentatie van enumeratie waarden"; }
trEnumerationValues() [1/2]
QCString TranslatorDutch::trEnumerationValues () [inline], [virtual]
Implements Translator.
Definition at line 213 of file translator_nl.h.
    { return "Enumeratie waarden"; }
trEnumerationValues() [2/2]
QCString TranslatorDutch::trEnumerationValues () [inline], [virtual]
Implements Translator.
Definition at line 213 of file translator_nl.h.
    { return "Enumeratie waarden"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorDutch::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1505 of file translator_nl.h.
    { QCString result = "De documentatie voor deze enum is gegenereerd op grond van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorDutch::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1505 of file translator_nl.h.
    { QCString result = "De documentatie voor deze enum is gegenereerd op grond van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
trEnumName() [1/2]
QCString TranslatorDutch::trEnumName () [inline], [virtual]
Implements Translator.
Definition at line 84 of file translator_nl.h.
    { return "enum naam"; }
trEnumName() [2/2]
QCString TranslatorDutch::trEnumName () [inline], [virtual]
Implements Translator.
Definition at line 84 of file translator_nl.h.
    { return "enum naam"; }
trEnumReference() [1/2]
virtual QCString TranslatorDutch::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1514 of file translator_nl.h.
    { return name+" Enum Referentie"; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorDutch::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1514 of file translator_nl.h.
    { return name+" Enum Referentie"; }
References setup::name.
trEnumValue() [1/2]
QCString TranslatorDutch::trEnumValue () [inline], [virtual]
Implements Translator.
Definition at line 86 of file translator_nl.h.
    { return "enum waarde"; }
trEnumValue() [2/2]
QCString TranslatorDutch::trEnumValue () [inline], [virtual]
Implements Translator.
Definition at line 86 of file translator_nl.h.
    { return "enum waarde"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorDutch::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1010 of file translator_nl.h.
    {
      return "Event Documentatie";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorDutch::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1010 of file translator_nl.h.
    {
      return "Event Documentatie";
    }
trEvents() [1/2]
virtual QCString TranslatorDutch::trEvents () [inline], [virtual]
Used as a header for a section of events found in a C# program
Implements Translator.
Definition at line 1005 of file translator_nl.h.
    {
      return "Events";
    }
trEvents() [2/2]
virtual QCString TranslatorDutch::trEvents () [inline], [virtual]
Used as a header for a section of events found in a C# program
Implements Translator.
Definition at line 1005 of file translator_nl.h.
    {
      return "Events";
    }
trExampleDocumentation() [1/2]
QCString TranslatorDutch::trExampleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 198 of file translator_nl.h.
    { return "Documentatie van voorbeelden"; }
trExampleDocumentation() [2/2]
QCString TranslatorDutch::trExampleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 198 of file translator_nl.h.
    { return "Documentatie van voorbeelden"; }
trExamples() [1/2]
QCString TranslatorDutch::trExamples () [inline], [virtual]
Implements Translator.
Definition at line 104 of file translator_nl.h.
    { return "Voorbeelden"; }
trExamples() [2/2]
QCString TranslatorDutch::trExamples () [inline], [virtual]
Implements Translator.
Definition at line 104 of file translator_nl.h.
    { return "Voorbeelden"; }
trExamplesDescription() [1/2]
QCString TranslatorDutch::trExamplesDescription () [inline], [virtual]
Implements Translator.
Definition at line 162 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle voorbeelden:"; }
trExamplesDescription() [2/2]
QCString TranslatorDutch::trExamplesDescription () [inline], [virtual]
Implements Translator.
Definition at line 162 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle voorbeelden:"; }
trExceptionDocumentation() [1/2]
virtual QCString TranslatorDutch::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1800 of file translator_nl.h.
    { return "Documentatie van exceptions"; }
trExceptionDocumentation() [2/2]
virtual QCString TranslatorDutch::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1800 of file translator_nl.h.
    { return "Documentatie van exceptions"; }
trExceptionHierarchy() [1/2]
virtual QCString TranslatorDutch::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 1796 of file translator_nl.h.
    { return "Exception Hi&euml;rarchie"; }
trExceptionHierarchy() [2/2]
virtual QCString TranslatorDutch::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 1796 of file translator_nl.h.
    { return "Exception Hi&euml;rarchie"; }
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorDutch::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 1798 of file translator_nl.h.
    { return "Deze inheritance lijst is min of meer alfabetisch gesorteerd:"; }
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorDutch::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 1798 of file translator_nl.h.
    { return "Deze inheritance lijst is min of meer alfabetisch gesorteerd:"; }
trExceptionIndex() [1/2]
virtual QCString TranslatorDutch::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 1790 of file translator_nl.h.
    { return "Index van exceptions"; }
trExceptionIndex() [2/2]
virtual QCString TranslatorDutch::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 1790 of file translator_nl.h.
    { return "Index van exceptions"; }
trExceptionList() [1/2]
virtual QCString TranslatorDutch::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 1792 of file translator_nl.h.
    { return "Lijst van exceptions"; }
trExceptionList() [2/2]
virtual QCString TranslatorDutch::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 1792 of file translator_nl.h.
    { return "Lijst van exceptions"; }
trExceptionListDescription() [1/2]
virtual QCString TranslatorDutch::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 1794 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle exeptions, elk met een korte beschrijving:"; }
trExceptionListDescription() [2/2]
virtual QCString TranslatorDutch::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 1794 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle exeptions, elk met een korte beschrijving:"; }
trExceptions() [1/2]
QCString TranslatorDutch::trExceptions () [inline], [virtual]
Implements Translator.
Definition at line 252 of file translator_nl.h.
    { return "Excepties"; }
trExceptions() [2/2]
QCString TranslatorDutch::trExceptions () [inline], [virtual]
Implements Translator.
Definition at line 252 of file translator_nl.h.
    { return "Excepties"; }
trExtendsClass() [1/2]
virtual QCString TranslatorDutch::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1554 of file translator_nl.h.
    {
      return "Uitbereiding van klasse @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorDutch::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1554 of file translator_nl.h.
    {
      return "Uitbereiding van klasse @0.";
    }
trFile() [1/2]
virtual QCString TranslatorDutch::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 874 of file translator_nl.h.
    {
      QCString result((first_capital ? "Bestand" : "bestand"));
      if (!singular) result+="en";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorDutch::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 874 of file translator_nl.h.
    {
      QCString result((first_capital ? "Bestand" : "bestand"));
      if (!singular) result+="en";
      return result;
    }
trFileDocumentation() [1/2]
QCString TranslatorDutch::trFileDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 196 of file translator_nl.h.
    { return "Bestand Documentatie"; }
trFileDocumentation() [2/2]
QCString TranslatorDutch::trFileDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 196 of file translator_nl.h.
    { return "Bestand Documentatie"; }
trFileIn() [1/2]
virtual QCString TranslatorDutch::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1421 of file translator_nl.h.
    {
      return "Bestand in "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorDutch::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1421 of file translator_nl.h.
    {
      return "Bestand in "+name;
    }
References setup::name.
trFileIndex() [1/2]
QCString TranslatorDutch::trFileIndex () [inline], [virtual]
Implements Translator.
Definition at line 177 of file translator_nl.h.
    { return "Bestand Index"; }
trFileIndex() [2/2]
QCString TranslatorDutch::trFileIndex () [inline], [virtual]
Implements Translator.
Definition at line 177 of file translator_nl.h.
    { return "Bestand Index"; }
trFileList() [1/2]
QCString TranslatorDutch::trFileList () [inline], [virtual]
Implements Translator.
Definition at line 96 of file translator_nl.h.
    { return "Bestandslijst"; }
trFileList() [2/2]
QCString TranslatorDutch::trFileList () [inline], [virtual]
Implements Translator.
Definition at line 96 of file translator_nl.h.
    { return "Bestandslijst"; }
trFileListDescription() [1/2]
QCString TranslatorDutch::trFileListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 119 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="bestanden, elk met een korte beschrijving:";
      return result;
    }
trFileListDescription() [2/2]
QCString TranslatorDutch::trFileListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 119 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="bestanden, elk met een korte beschrijving:";
      return result;
    }
trFileMembers() [1/2]
QCString TranslatorDutch::trFileMembers () [inline], [virtual]
Implements Translator.
Definition at line 100 of file translator_nl.h.
    { return "Bestand members"; }
trFileMembers() [2/2]
QCString TranslatorDutch::trFileMembers () [inline], [virtual]
Implements Translator.
Definition at line 100 of file translator_nl.h.
    { return "Bestand members"; }
trFileMembersDescription() [1/2]
QCString TranslatorDutch::trFileMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 153 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="bestand members met links naar ";
      if (extractAll) result+="de bestand's documentatie voor elke member:";
      else result+="de bestanden waartoe ze behoren:";
      return result;
    }
trFileMembersDescription() [2/2]
QCString TranslatorDutch::trFileMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 153 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="bestand members met links naar ";
      if (extractAll) result+="de bestand's documentatie voor elke member:";
      else result+="de bestanden waartoe ze behoren:";
      return result;
    }
trFileReference() [1/2]
QCString TranslatorDutch::trFileReference (const QCString & fileName) [inline], [virtual]
Implements Translator.
Definition at line 305 of file translator_nl.h.
    {
      QCString result=fileName;
      result+=" Bestand Referentie";
      return result;
    }
trFileReference() [2/2]
QCString TranslatorDutch::trFileReference (const QCString & fileName) [inline], [virtual]
Implements Translator.
Definition at line 305 of file translator_nl.h.
    {
      QCString result=fileName;
      result+=" Bestand Referentie";
      return result;
    }
trFlowchart() [1/2]
virtual QCString TranslatorDutch::trFlowchart () [inline], [virtual]
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 1888 of file translator_nl.h.
    { return "Stroomschema: "; }
trFlowchart() [2/2]
virtual QCString TranslatorDutch::trFlowchart () [inline], [virtual]
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 1888 of file translator_nl.h.
    { return "Stroomschema: "; }
trFriends() [1/2]
QCString TranslatorDutch::trFriends () [inline], [virtual]
Implements Translator.
Definition at line 270 of file translator_nl.h.
    { return "Friends"; }
trFriends() [2/2]
QCString TranslatorDutch::trFriends () [inline], [virtual]
Implements Translator.
Definition at line 270 of file translator_nl.h.
    { return "Friends"; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorDutch::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 1662 of file translator_nl.h.
    { return "Functies/Procedures/Processen"; }
trFunctionAndProc() [2/2]
virtual QCString TranslatorDutch::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 1662 of file translator_nl.h.
    { return "Functies/Procedures/Processen"; }
trFunctionDocumentation() [1/2]
QCString TranslatorDutch::trFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 223 of file translator_nl.h.
    { return "Documentatie van functies"; }
trFunctionDocumentation() [2/2]
QCString TranslatorDutch::trFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 223 of file translator_nl.h.
    { return "Documentatie van functies"; }
trFunctions() [1/2]
QCString TranslatorDutch::trFunctions () [inline], [virtual]
Implements Translator.
Definition at line 209 of file translator_nl.h.
    { return "Functies"; }
trFunctions() [2/2]
QCString TranslatorDutch::trFunctions () [inline], [virtual]
Implements Translator.
Definition at line 209 of file translator_nl.h.
    { return "Functies"; }
trGeneratedAt() [1/2]
QCString TranslatorDutch::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
Implements Translator.
Definition at line 229 of file translator_nl.h.
    {
      QCString result="Gegenereerd op "+date;
      if (!projName.isEmpty()) result+=" voor "+projName;
      result+=" door";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
QCString TranslatorDutch::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
Implements Translator.
Definition at line 229 of file translator_nl.h.
    {
      QCString result="Gegenereerd op "+date;
      if (!projName.isEmpty()) result+=" voor "+projName;
      result+=" door";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
QCString TranslatorDutch::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
Implements Translator.
Definition at line 78 of file translator_nl.h.
    { QCString result="Automatisch gegenereerd door Doxygen";
      if (!s.isEmpty()) result+=" voor "+s;
      result+=" uit de programmatekst.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
QCString TranslatorDutch::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
Implements Translator.
Definition at line 78 of file translator_nl.h.
    { QCString result="Automatisch gegenereerd door Doxygen";
      if (!s.isEmpty()) result+=" voor "+s;
      result+=" uit de programmatekst.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
QCString TranslatorDutch::trGeneratedBy () [inline], [virtual]
Implements Translator.
Definition at line 254 of file translator_nl.h.
    { return "Gegenereerd door"; }
trGeneratedBy() [2/2]
QCString TranslatorDutch::trGeneratedBy () [inline], [virtual]
Implements Translator.
Definition at line 254 of file translator_nl.h.
    { return "Gegenereerd door"; }
trGeneratedFromFiles() [1/2]
QCString TranslatorDutch::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 435 of file translator_nl.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="De documentatie voor ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?"deze ontwerp eenheid":"deze klasse"; break;
        case ClassDef::Struct: result+="deze struct"; break;
        case ClassDef::Union: result+="deze union"; break;
        case ClassDef::Interface: result+="dit interface"; break;
        case ClassDef::Protocol: result+="dit protocol"; break;
        case ClassDef::Category: result+="deze categorie"; break;
        case ClassDef::Exception: result+="deze exceptie"; break;
        default: break;
      }
      result+=" is gegenereerd op grond van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
QCString TranslatorDutch::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 435 of file translator_nl.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="De documentatie voor ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?"deze ontwerp eenheid":"deze klasse"; break;
        case ClassDef::Struct: result+="deze struct"; break;
        case ClassDef::Union: result+="deze union"; break;
        case ClassDef::Interface: result+="dit interface"; break;
        case ClassDef::Protocol: result+="dit protocol"; break;
        case ClassDef::Category: result+="deze categorie"; break;
        case ClassDef::Exception: result+="deze exceptie"; break;
        default: break;
      }
      result+=" is gegenereerd op grond van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorDutch::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1330 of file translator_nl.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="De documentatie voor ";
      switch(compType)
      {
        case ClassDef::Class: result+="deze module"; break;
        case ClassDef::Struct: result+="dit type"; break;
        case ClassDef::Union: result+="deze union"; break;
        case ClassDef::Interface: result+="dit interface"; break;
        case ClassDef::Protocol: result+="dit protocol"; break;
        case ClassDef::Category: result+="deze category"; break;
        case ClassDef::Exception: result+="deze exception"; break;
        default: break;
      }
      result+=" is gegenereerd op grond van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorDutch::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1330 of file translator_nl.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="De documentatie voor ";
      switch(compType)
      {
        case ClassDef::Class: result+="deze module"; break;
        case ClassDef::Struct: result+="dit type"; break;
        case ClassDef::Union: result+="deze union"; break;
        case ClassDef::Interface: result+="dit interface"; break;
        case ClassDef::Protocol: result+="dit protocol"; break;
        case ClassDef::Category: result+="deze category"; break;
        case ClassDef::Exception: result+="deze exception"; break;
        default: break;
      }
      result+=" is gegenereerd op grond van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorDutch::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 929 of file translator_nl.h.
    {
      QCString result((first_capital ? "Globale member" : "globale member"));
      if (!singular) result+="s";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorDutch::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 929 of file translator_nl.h.
    {
      QCString result((first_capital ? "Globale member" : "globale member"));
      if (!singular) result+="s";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorDutch::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1396 of file translator_nl.h.
    {
      return "Globale Namespace";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorDutch::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1396 of file translator_nl.h.
    {
      return "Globale Namespace";
    }
trGotoDocumentation() [1/2]
QCString TranslatorDutch::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 525 of file translator_nl.h.
    {
      return "Ga naar de documentatie van dit bestand.";
    }
trGotoDocumentation() [2/2]
QCString TranslatorDutch::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 525 of file translator_nl.h.
    {
      return "Ga naar de documentatie van dit bestand.";
    }
trGotoGraphicalHierarchy() [1/2]
QCString TranslatorDutch::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 558 of file translator_nl.h.
    {
      return "Ga naar de grafische klasse hi&euml;rarchie";
    }
trGotoGraphicalHierarchy() [2/2]
QCString TranslatorDutch::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 558 of file translator_nl.h.
    {
      return "Ga naar de grafische klasse hi&euml;rarchie";
    }
trGotoSourceCode() [1/2]
QCString TranslatorDutch::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 520 of file translator_nl.h.
    {
      return "Ga naar de broncode van dit bestand.";
    }
trGotoSourceCode() [2/2]
QCString TranslatorDutch::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 520 of file translator_nl.h.
    {
      return "Ga naar de broncode van dit bestand.";
    }
trGotoTextualHierarchy() [1/2]
QCString TranslatorDutch::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 562 of file translator_nl.h.
    {
      return "Ga naar de tekstuele klasse hi&euml;rarchie";
    }
trGotoTextualHierarchy() [2/2]
QCString TranslatorDutch::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 562 of file translator_nl.h.
    {
      return "Ga naar de tekstuele klasse hi&euml;rarchie";
    }
trGraphicalHierarchy() [1/2]
QCString TranslatorDutch::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 554 of file translator_nl.h.
    {
      return "Grafische Klasse Hi&euml;rarchie";
    }
trGraphicalHierarchy() [2/2]
QCString TranslatorDutch::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 554 of file translator_nl.h.
    {
      return "Grafische Klasse Hi&euml;rarchie";
    }
trGroup() [1/2]
virtual QCString TranslatorDutch::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 896 of file translator_nl.h.
    {
      QCString result((first_capital ? "Groep" : "groep"));
      if (!singular) result+="en";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorDutch::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 896 of file translator_nl.h.
    {
      QCString result((first_capital ? "Groep" : "groep"));
      if (!singular) result+="en";
      return result;
    }
trHierarchicalIndex() [1/2]
QCString TranslatorDutch::trHierarchicalIndex () [inline], [virtual]
Implements Translator.
Definition at line 173 of file translator_nl.h.
    { return "Hi&euml;rarchische Index"; }
trHierarchicalIndex() [2/2]
QCString TranslatorDutch::trHierarchicalIndex () [inline], [virtual]
Implements Translator.
Definition at line 173 of file translator_nl.h.
    { return "Hi&euml;rarchische Index"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorDutch::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 967 of file translator_nl.h.
    {
      return "Implementeert "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorDutch::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 967 of file translator_nl.h.
    {
      return "Implementeert "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorDutch::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 975 of file translator_nl.h.
    {
      return "Wordt ge&iuml;mplementeerd door "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorDutch::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 975 of file translator_nl.h.
    {
      return "Wordt ge&iuml;mplementeerd door "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
QCString TranslatorDutch::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_nl.h.
    {
      return "Deze graaf geeft aan welke bestanden direct of "
             "indirect afhankelijk zijn van dit bestand:";
    }
trInclByDepGraph() [2/2]
QCString TranslatorDutch::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_nl.h.
    {
      return "Deze graaf geeft aan welke bestanden direct of "
             "indirect afhankelijk zijn van dit bestand:";
    }
trInclDepGraph() [1/2]
QCString TranslatorDutch::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 510 of file translator_nl.h.
    {
      return "Include afhankelijkheidsgraaf voor "+fName+":";
    }
trInclDepGraph() [2/2]
QCString TranslatorDutch::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 510 of file translator_nl.h.
    {
      return "Include afhankelijkheidsgraaf voor "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorDutch::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1430 of file translator_nl.h.
    {
      return "Includeert bestand in "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorDutch::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1430 of file translator_nl.h.
    {
      return "Includeert bestand in "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
QCString TranslatorDutch::trIncludingInheritedMembers () [inline], [virtual]
Implements Translator.
Definition at line 76 of file translator_nl.h.
    { return ", inclusief alle overge&euml;rfde members."; }
trIncludingInheritedMembers() [2/2]
QCString TranslatorDutch::trIncludingInheritedMembers () [inline], [virtual]
Implements Translator.
Definition at line 76 of file translator_nl.h.
    { return ", inclusief alle overge&euml;rfde members."; }
trInheritedByList() [1/2]
QCString TranslatorDutch::trInheritedByList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 373 of file translator_nl.h.
    {
      return "Wordt overge&euml;rfd door "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
QCString TranslatorDutch::trInheritedByList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 373 of file translator_nl.h.
    {
      return "Wordt overge&euml;rfd door "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorDutch::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1518 of file translator_nl.h.
    { return members+" overge&euml;rfd van "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorDutch::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1518 of file translator_nl.h.
    { return members+" overge&euml;rfd van "+what; }
trInheritsList() [1/2]
QCString TranslatorDutch::trInheritsList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 367 of file translator_nl.h.
    {
      return "Erft over van "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
QCString TranslatorDutch::trInheritsList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 367 of file translator_nl.h.
    {
      return "Erft over van "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
QCString TranslatorDutch::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 545 of file translator_nl.h.
    {
      return "Initi&euml;le waarde:";
    }
trInitialValue() [2/2]
QCString TranslatorDutch::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 545 of file translator_nl.h.
    {
      return "Initi&euml;le waarde:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorDutch::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1570 of file translator_nl.h.
    {
      return "Instantie Methoden";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorDutch::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1570 of file translator_nl.h.
    {
      return "Instantie Methoden";
    }
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorDutch::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1778 of file translator_nl.h.
    { return "Documentatie van interfaces"; }
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorDutch::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1778 of file translator_nl.h.
    { return "Documentatie van interfaces"; }
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorDutch::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 1774 of file translator_nl.h.
    { return "Interface Hi&euml;rarchie"; }
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorDutch::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 1774 of file translator_nl.h.
    { return "Interface Hi&euml;rarchie"; }
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorDutch::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 1776 of file translator_nl.h.
    { return "Deze inheritance lijst is min of meer alfabetisch gesorteerd:"; }
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorDutch::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 1776 of file translator_nl.h.
    { return "Deze inheritance lijst is min of meer alfabetisch gesorteerd:"; }
trInterfaceIndex() [1/2]
virtual QCString TranslatorDutch::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 1768 of file translator_nl.h.
    { return "Index van interfaces"; }
trInterfaceIndex() [2/2]
virtual QCString TranslatorDutch::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 1768 of file translator_nl.h.
    { return "Index van interfaces"; }
trInterfaceList() [1/2]
virtual QCString TranslatorDutch::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 1770 of file translator_nl.h.
    { return "Lijst van interfaces"; }
trInterfaceList() [2/2]
virtual QCString TranslatorDutch::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 1770 of file translator_nl.h.
    { return "Lijst van interfaces"; }
trInterfaceListDescription() [1/2]
virtual QCString TranslatorDutch::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 1772 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle interfaces, elk met een korte beschrijving:"; }
trInterfaceListDescription() [2/2]
virtual QCString TranslatorDutch::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 1772 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle interfaces, elk met een korte beschrijving:"; }
trInterfaces() [1/2]
virtual QCString TranslatorDutch::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1587 of file translator_nl.h.
    { return "Ge&euml;porteerde Interfaces"; }
trInterfaces() [2/2]
virtual QCString TranslatorDutch::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1587 of file translator_nl.h.
    { return "Ge&euml;porteerde Interfaces"; }
trInvariant() [1/2]
QCString TranslatorDutch::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 540 of file translator_nl.h.
    {
      return "Invariant";
    }
trInvariant() [2/2]
QCString TranslatorDutch::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 540 of file translator_nl.h.
    {
      return "Invariant";
    }
trISOLang() [1/2]
QCString TranslatorDutch::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 39 of file translator_nl.h.
    { return "nl"; }
trISOLang() [2/2]
QCString TranslatorDutch::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 39 of file translator_nl.h.
    { return "nl"; }
trLegend() [1/2]
QCString TranslatorDutch::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 730 of file translator_nl.h.
    {
      return "legenda";
    }
trLegend() [2/2]
QCString TranslatorDutch::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 730 of file translator_nl.h.
    {
      return "legenda";
    }
trLegendDocs() [1/2]
QCString TranslatorDutch::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 668 of file translator_nl.h.
    {
      return
        "Deze pagina legt uit hoe de grafen die gegenereerd worden door doxygen "
        "ge&iuml;nterpreteerd dienen te worden.<p>\n"
        "Beschouw het volgende voorbeeld:\n"
        "\\code\n"
        "/*! Onzichtbare klasse vanwege afkappen van de graaf */\n"
        "class Invisible { };\n\n"
        "/*! Afgekapte klasse, overervingsrelatie is verborgen */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klasse is niet gedocumenteerd met doxygen commentaar */\n"
        "class Undocumented { };\n\n"
        "/*! Klasse met public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasse met protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasse met private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasse die wordt gebruikt door de klasse Inherited */\n"
        "class Used { };\n\n"
        "/*! Super klasse die overerft van een aantal andere klassen */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Dit voorbeeld zal resulteren in de volgende graaf:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "De rechthoeken in the bovenstaande graaf hebben de volgende betekenis:\n"
        "<ul>\n"
        "<li>Een gevulde grijze rechthoek representeert de structure of klasse waarvoor "
        "de graaf is gegenereerd.\n"
        "<li>Een rechthoek met een zwarte rand representeert een gedocumenteerde structure of klasse.\n"
        "<li>Een rechthoek met een grijze rand representeert een ongedocumenteerde structure of klasse.\n"
        "<li>Een rechthoek met een rode rand representeert een gedocumenteerde structure or klasse waarvoor\n"
        "niet alle overervings- of gebruiksrelaties konden worden getoond. Een graaf wordt "
        "afgekapt als hij niet past binnen de gespecificeerde grenzen."
        "</ul>\n"
        "De pijlen hebben de volgende betekenis:\n"
        "<ul>\n"
        "<li>Een blauwe pijl visualizeert een public inheritance "
        "relatie tussen twee klassen.\n"
        "<li>Een donkergroene pijl wordt gebruikt voor protected inheritance.\n"
        "<li>Een donkerrode pijl wordt gebruikt voor private inheritance.\n"
        "<li>Een paars gestippelde pijl wordt gebruikt indien een klasse bevat is of gebruikt wordt "
        "door een andere klasse. De pijl is gelabeled met de variable(n) "
        "die toegang geven tot de aangewezen klasse of structure. \n"
        "<li>Een geel gestippelde pijl wordt gebruikt om een relatie tussen een \n"
        "template instantie en een template klasse aan te geven. De pijl is gelabeld met \n"
        "template parameters van de instantie.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
QCString TranslatorDutch::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 668 of file translator_nl.h.
    {
      return
        "Deze pagina legt uit hoe de grafen die gegenereerd worden door doxygen "
        "ge&iuml;nterpreteerd dienen te worden.<p>\n"
        "Beschouw het volgende voorbeeld:\n"
        "\\code\n"
        "/*! Onzichtbare klasse vanwege afkappen van de graaf */\n"
        "class Invisible { };\n\n"
        "/*! Afgekapte klasse, overervingsrelatie is verborgen */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klasse is niet gedocumenteerd met doxygen commentaar */\n"
        "class Undocumented { };\n\n"
        "/*! Klasse met public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasse met protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasse met private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasse die wordt gebruikt door de klasse Inherited */\n"
        "class Used { };\n\n"
        "/*! Super klasse die overerft van een aantal andere klassen */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Dit voorbeeld zal resulteren in de volgende graaf:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "De rechthoeken in the bovenstaande graaf hebben de volgende betekenis:\n"
        "<ul>\n"
        "<li>Een gevulde grijze rechthoek representeert de structure of klasse waarvoor "
        "de graaf is gegenereerd.\n"
        "<li>Een rechthoek met een zwarte rand representeert een gedocumenteerde structure of klasse.\n"
        "<li>Een rechthoek met een grijze rand representeert een ongedocumenteerde structure of klasse.\n"
        "<li>Een rechthoek met een rode rand representeert een gedocumenteerde structure or klasse waarvoor\n"
        "niet alle overervings- of gebruiksrelaties konden worden getoond. Een graaf wordt "
        "afgekapt als hij niet past binnen de gespecificeerde grenzen."
        "</ul>\n"
        "De pijlen hebben de volgende betekenis:\n"
        "<ul>\n"
        "<li>Een blauwe pijl visualizeert een public inheritance "
        "relatie tussen twee klassen.\n"
        "<li>Een donkergroene pijl wordt gebruikt voor protected inheritance.\n"
        "<li>Een donkerrode pijl wordt gebruikt voor private inheritance.\n"
        "<li>Een paars gestippelde pijl wordt gebruikt indien een klasse bevat is of gebruikt wordt "
        "door een andere klasse. De pijl is gelabeled met de variable(n) "
        "die toegang geven tot de aangewezen klasse of structure. \n"
        "<li>Een geel gestippelde pijl wordt gebruikt om een relatie tussen een \n"
        "template instantie en een template klasse aan te geven. De pijl is gelabeld met \n"
        "template parameters van de instantie.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
QCString TranslatorDutch::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 663 of file translator_nl.h.
    {
      return "Graaf Legenda";
    }
trLegendTitle() [2/2]
QCString TranslatorDutch::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 663 of file translator_nl.h.
    {
      return "Graaf Legenda";
    }
trListOfAllMembers() [1/2]
QCString TranslatorDutch::trListOfAllMembers () [inline], [virtual]
Implements Translator.
Definition at line 70 of file translator_nl.h.
    { return "Lijst van alle members"; }
trListOfAllMembers() [2/2]
QCString TranslatorDutch::trListOfAllMembers () [inline], [virtual]
Implements Translator.
Definition at line 70 of file translator_nl.h.
    { return "Lijst van alle members"; }
trLoading() [1/2]
virtual QCString TranslatorDutch::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1390 of file translator_nl.h.
    {
      return "Laden...";
    }
trLoading() [2/2]
virtual QCString TranslatorDutch::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1390 of file translator_nl.h.
    {
      return "Laden...";
    }
trMainPage() [1/2]
QCString TranslatorDutch::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 469 of file translator_nl.h.
    { return "Hoofd Pagina"; }
trMainPage() [2/2]
QCString TranslatorDutch::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 469 of file translator_nl.h.
    { return "Hoofd Pagina"; }
trMember() [1/2]
virtual QCString TranslatorDutch::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 918 of file translator_nl.h.
    {
      QCString result((first_capital ? "Member" : "member"));
      if (!singular) result+="s";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorDutch::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 918 of file translator_nl.h.
    {
      QCString result((first_capital ? "Member" : "member"));
      if (!singular) result+="s";
      return result;
    }
trMemberDataDocumentation() [1/2]
QCString TranslatorDutch::trMemberDataDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 66 of file translator_nl.h.
    { return "Documentatie van data members"; }
trMemberDataDocumentation() [2/2]
QCString TranslatorDutch::trMemberDataDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 66 of file translator_nl.h.
    { return "Documentatie van data members"; }
trMemberEnumerationDocumentation() [1/2]
QCString TranslatorDutch::trMemberEnumerationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 53 of file translator_nl.h.
    { return "Documentatie van enumeratie members"; }
trMemberEnumerationDocumentation() [2/2]
QCString TranslatorDutch::trMemberEnumerationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 53 of file translator_nl.h.
    { return "Documentatie van enumeratie members"; }
trMemberFunctionDocumentation() [1/2]
QCString TranslatorDutch::trMemberFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 55 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Documentatie van functie/procedure/process members";
      }
      else
      {
        return "Documentatie van functie members";
      }
    }
References Config_getBool.
trMemberFunctionDocumentation() [2/2]
QCString TranslatorDutch::trMemberFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 55 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Documentatie van functie/procedure/process members";
      }
      else
      {
        return "Documentatie van functie members";
      }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorDutch::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1192 of file translator_nl.h.
    { return "Member Functie/Subroutine Documentatie"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorDutch::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1192 of file translator_nl.h.
    { return "Member Functie/Subroutine Documentatie"; }
trMemberList() [1/2]
QCString TranslatorDutch::trMemberList () [inline], [virtual]
Implements Translator.
Definition at line 72 of file translator_nl.h.
    { return "Member Lijst"; }
trMemberList() [2/2]
QCString TranslatorDutch::trMemberList () [inline], [virtual]
Implements Translator.
Definition at line 72 of file translator_nl.h.
    { return "Member Lijst"; }
trMemberTypedefDocumentation() [1/2]
QCString TranslatorDutch::trMemberTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 51 of file translator_nl.h.
    { return "Documentatie van type definitie members"; }
trMemberTypedefDocumentation() [2/2]
QCString TranslatorDutch::trMemberTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 51 of file translator_nl.h.
    { return "Documentatie van type definitie members"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorDutch::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1577 of file translator_nl.h.
    {
      return "Methode Documentatie";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorDutch::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1577 of file translator_nl.h.
    {
      return "Methode Documentatie";
    }
trModule() [1/2]
virtual QCString TranslatorDutch::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1321 of file translator_nl.h.
    {
      QCString result((first_capital ? "Module" : "module"));
      if (!singular) result+="n";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorDutch::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1321 of file translator_nl.h.
    {
      QCString result((first_capital ? "Module" : "module"));
      if (!singular) result+="n";
      return result;
    }
trModuleDocumentation() [1/2]
QCString TranslatorDutch::trModuleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 179 of file translator_nl.h.
    { return "Module Documentatie"; }
trModuleDocumentation() [2/2]
QCString TranslatorDutch::trModuleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 179 of file translator_nl.h.
    { return "Module Documentatie"; }
trModuleIndex() [1/2]
QCString TranslatorDutch::trModuleIndex () [inline], [virtual]
Implements Translator.
Definition at line 171 of file translator_nl.h.
    { return "Module Index"; }
trModuleIndex() [2/2]
QCString TranslatorDutch::trModuleIndex () [inline], [virtual]
Implements Translator.
Definition at line 171 of file translator_nl.h.
    { return "Module Index"; }
trModuleReference() [1/2]
virtual QCString TranslatorDutch::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1287 of file translator_nl.h.
    {
      QCString result=namespaceName;
      result+=" Module Referentie";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorDutch::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1287 of file translator_nl.h.
    {
      QCString result=namespaceName;
      result+=" Module Referentie";
      return result;
    }
trModules() [1/2]
QCString TranslatorDutch::trModules () [inline], [virtual]
Implements Translator.
Definition at line 90 of file translator_nl.h.
    { return "Modules"; }
trModules() [2/2]
QCString TranslatorDutch::trModules () [inline], [virtual]
Implements Translator.
Definition at line 90 of file translator_nl.h.
    { return "Modules"; }
trModulesDescription() [1/2]
QCString TranslatorDutch::trModulesDescription () [inline], [virtual]
Implements Translator.
Definition at line 166 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle modules:"; }
trModulesDescription() [2/2]
QCString TranslatorDutch::trModulesDescription () [inline], [virtual]
Implements Translator.
Definition at line 166 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle modules:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorDutch::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1314 of file translator_nl.h.
    { return "Module Index"; }
trModulesIndex() [2/2]
virtual QCString TranslatorDutch::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1314 of file translator_nl.h.
    { return "Module Index"; }
trModulesList() [1/2]
virtual QCString TranslatorDutch::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1253 of file translator_nl.h.
    { return "Module Lijst"; }
trModulesList() [2/2]
virtual QCString TranslatorDutch::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1253 of file translator_nl.h.
    { return "Module Lijst"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorDutch::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1257 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="modulen, elk met een korte beschrijving:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorDutch::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1257 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="modulen, elk met een korte beschrijving:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorDutch::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1299 of file translator_nl.h.
    {
      QCString result="Hier is een lijst van alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="module members met links naar ";
      if (extractAll)
        result+="de module documentatie voor iedere member:";
      else
        result+="de module waartoe ze behoren:";
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorDutch::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1299 of file translator_nl.h.
    {
      QCString result="Hier is een lijst van alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="module members met links naar ";
      if (extractAll)
        result+="de module documentatie voor iedere member:";
      else
        result+="de module waartoe ze behoren:";
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorDutch::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1295 of file translator_nl.h.
    { return "Module Members"; }
trModulesMembers() [2/2]
virtual QCString TranslatorDutch::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1295 of file translator_nl.h.
    { return "Module Members"; }
trMonth() [1/2]
virtual QCString TranslatorDutch::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1458 of file translator_nl.h.
    {
      static const char *months_short[] = { "jan", "feb", "mrt", "apr", "mei", "jun", "jul", "aug", "sep", "okt", "nov", "dec" };
      static const char *months_full[] = { "januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorDutch::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1458 of file translator_nl.h.
    {
      static const char *months_short[] = { "jan", "feb", "mrt", "apr", "mei", "jun", "jul", "aug", "sep", "okt", "nov", "dec" };
      static const char *months_full[] = { "januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
QCString TranslatorDutch::trMore () [inline], [virtual]
Implements Translator.
Definition at line 68 of file translator_nl.h.
    { return "Meer..."; }
trMore() [2/2]
QCString TranslatorDutch::trMore () [inline], [virtual]
Implements Translator.
Definition at line 68 of file translator_nl.h.
    { return "Meer..."; }
trNamespace() [1/2]
virtual QCString TranslatorDutch::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 885 of file translator_nl.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorDutch::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 885 of file translator_nl.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespaceDocumentation() [1/2]
QCString TranslatorDutch::trNamespaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 411 of file translator_nl.h.
    { return "Namespace Documentatie"; }
trNamespaceDocumentation() [2/2]
QCString TranslatorDutch::trNamespaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 411 of file translator_nl.h.
    { return "Namespace Documentatie"; }
trNamespaceIndex() [1/2]
QCString TranslatorDutch::trNamespaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 407 of file translator_nl.h.
    { return "Namespace Index"; }
trNamespaceIndex() [2/2]
QCString TranslatorDutch::trNamespaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 407 of file translator_nl.h.
    { return "Namespace Index"; }
trNamespaceList() [1/2]
QCString TranslatorDutch::trNamespaceList () [inline], [virtual]
Implements Translator.
Definition at line 261 of file translator_nl.h.
    { return "Namespace Lijst"; }
trNamespaceList() [2/2]
QCString TranslatorDutch::trNamespaceList () [inline], [virtual]
Implements Translator.
Definition at line 261 of file translator_nl.h.
    { return "Namespace Lijst"; }
trNamespaceListDescription() [1/2]
QCString TranslatorDutch::trNamespaceListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 263 of file translator_nl.h.
    {
      QCString result="Hier is een lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="namespaces met voor elk een korte beschrijving:";
      return result;
    }
trNamespaceListDescription() [2/2]
QCString TranslatorDutch::trNamespaceListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 263 of file translator_nl.h.
    {
      QCString result="Hier is een lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="namespaces met voor elk een korte beschrijving:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
QCString TranslatorDutch::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 395 of file translator_nl.h.
    {
      QCString result="Hier is een lijst van alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="namespace members met links naar ";
      if (extractAll)
        result+="de namespace documentatie voor iedere member:";
      else
        result+="de namespaces waartoe ze behoren:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
QCString TranslatorDutch::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 395 of file translator_nl.h.
    {
      QCString result="Hier is een lijst van alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="namespace members met links naar ";
      if (extractAll)
        result+="de namespace documentatie voor iedere member:";
      else
        result+="de namespaces waartoe ze behoren:";
      return result;
    }
trNamespaceMembers() [1/2]
QCString TranslatorDutch::trNamespaceMembers () [inline], [virtual]
Implements Translator.
Definition at line 392 of file translator_nl.h.
    { return "Namespace Members"; }
trNamespaceMembers() [2/2]
QCString TranslatorDutch::trNamespaceMembers () [inline], [virtual]
Implements Translator.
Definition at line 392 of file translator_nl.h.
    { return "Namespace Members"; }
trNamespaceReference() [1/2]
QCString TranslatorDutch::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
Implements Translator.
Definition at line 312 of file translator_nl.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Referentie";
      return result;
    }
trNamespaceReference() [2/2]
QCString TranslatorDutch::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
Implements Translator.
Definition at line 312 of file translator_nl.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Referentie";
      return result;
    }
trNamespaces() [1/2]
QCString TranslatorDutch::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 423 of file translator_nl.h.
    {
      return "Namespaces";
    }
trNamespaces() [2/2]
QCString TranslatorDutch::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 423 of file translator_nl.h.
    {
      return "Namespaces";
    }
trNoMatches() [1/2]
virtual QCString TranslatorDutch::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1408 of file translator_nl.h.
    {
      return "Niets gevonden";
    }
trNoMatches() [2/2]
virtual QCString TranslatorDutch::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1408 of file translator_nl.h.
    {
      return "Niets gevonden";
    }
trNote() [1/2]
QCString TranslatorDutch::trNote () [inline], [virtual]
Implements Translator.
Definition at line 575 of file translator_nl.h.
    {
      return "Noot";
    }
trNote() [2/2]
QCString TranslatorDutch::trNote () [inline], [virtual]
Implements Translator.
Definition at line 575 of file translator_nl.h.
    {
      return "Noot";
    }
trOperationDocumentation() [1/2]
virtual QCString TranslatorDutch::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1822 of file translator_nl.h.
    { return "Documentatie van bewerkingen"; }
trOperationDocumentation() [2/2]
virtual QCString TranslatorDutch::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1822 of file translator_nl.h.
    { return "Documentatie van bewerkingen"; }
trOperations() [1/2]
virtual QCString TranslatorDutch::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 1820 of file translator_nl.h.
    { return "Bewerkingen"; }
trOperations() [2/2]
virtual QCString TranslatorDutch::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 1820 of file translator_nl.h.
    { return "Bewerkingen"; }
trOverloadText() [1/2]
virtual QCString TranslatorDutch::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a function.
Implements Translator.
Definition at line 1174 of file translator_nl.h.
    {
      return "Deze functie is overloaded en is beschikbaar gemaakt om het "
             "gebruik te vergemakkelijken. Ze verschilt alleen van de "
             "bovenstaande functie wat betreft de parameterlijst.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorDutch::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a function.
Implements Translator.
Definition at line 1174 of file translator_nl.h.
    {
      return "Deze functie is overloaded en is beschikbaar gemaakt om het "
             "gebruik te vergemakkelijken. Ze verschilt alleen van de "
             "bovenstaande functie wat betreft de parameterlijst.";
    }
trPackage() [1/2]
QCString TranslatorDutch::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 775 of file translator_nl.h.
    {
      return "Package "+name;
    }
References setup::name.
trPackage() [2/2]
QCString TranslatorDutch::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 775 of file translator_nl.h.
    {
      return "Package "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorDutch::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1046 of file translator_nl.h.
    {
      return "Package Attributen";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorDutch::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1046 of file translator_nl.h.
    {
      return "Package Attributen";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorDutch::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1028 of file translator_nl.h.
    {
      return "Package Functies";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorDutch::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1028 of file translator_nl.h.
    {
      return "Package Functies";
    }
trPackageList() [1/2]
virtual QCString TranslatorDutch::trPackageList () [inline], [virtual]
Implements Translator.
Definition at line 1878 of file translator_nl.h.
    { return "Package Lijst"; }
trPackageList() [2/2]
virtual QCString TranslatorDutch::trPackageList () [inline], [virtual]
Implements Translator.
Definition at line 1878 of file translator_nl.h.
    { return "Package Lijst"; }
trPackageListDescription() [1/2]
QCString TranslatorDutch::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 780 of file translator_nl.h.
    {
      return "Hier volgen de packages, elk met een korte beschrijving (indien aanwezig):";
    }
trPackageListDescription() [2/2]
QCString TranslatorDutch::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 780 of file translator_nl.h.
    {
      return "Hier volgen de packages, elk met een korte beschrijving (indien aanwezig):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorDutch::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1032 of file translator_nl.h.
    {
      return "Package Members";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorDutch::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1032 of file translator_nl.h.
    {
      return "Package Members";
    }
trPackages() [1/2]
QCString TranslatorDutch::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 785 of file translator_nl.h.
    {
      return "Packages";
    }
trPackages() [2/2]
QCString TranslatorDutch::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 785 of file translator_nl.h.
    {
      return "Packages";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorDutch::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1021 of file translator_nl.h.
    {
      return "Package Types";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorDutch::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1021 of file translator_nl.h.
    {
      return "Package Types";
    }
trPage() [1/2]
virtual QCString TranslatorDutch::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 907 of file translator_nl.h.
    {
      QCString result((first_capital ? "Pagina" : "pagina"));
      if (!singular) result+="s";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorDutch::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 907 of file translator_nl.h.
    {
      QCString result((first_capital ? "Pagina" : "pagina"));
      if (!singular) result+="s";
      return result;
    }
trPageAbbreviation() [1/2]
QCString TranslatorDutch::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 475 of file translator_nl.h.
    { return "p."; }
trPageAbbreviation() [2/2]
QCString TranslatorDutch::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 475 of file translator_nl.h.
    { return "p."; }
trPageIndex() [1/2]
QCString TranslatorDutch::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 566 of file translator_nl.h.
    {
      return "Pagina Index";
    }
trPageIndex() [2/2]
QCString TranslatorDutch::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 566 of file translator_nl.h.
    {
      return "Pagina Index";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorDutch::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1535 of file translator_nl.h.
    {
      QCString opt = enable ? "in" : "uit";
      return "klik hier de paneel synchronisatie "+opt+" the schakelen";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorDutch::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1535 of file translator_nl.h.
    {
      QCString opt = enable ? "in" : "uit";
      return "klik hier de paneel synchronisatie "+opt+" the schakelen";
    }
trParameters() [1/2]
QCString TranslatorDutch::trParameters () [inline], [virtual]
Implements Translator.
Definition at line 250 of file translator_nl.h.
    { return "Parameters"; }
trParameters() [2/2]
QCString TranslatorDutch::trParameters () [inline], [virtual]
Implements Translator.
Definition at line 250 of file translator_nl.h.
    { return "Parameters"; }
trPostcondition() [1/2]
QCString TranslatorDutch::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 535 of file translator_nl.h.
    {
      return "Postconditie";
    }
trPostcondition() [2/2]
QCString TranslatorDutch::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 535 of file translator_nl.h.
    {
      return "Postconditie";
    }
trPrecondition() [1/2]
QCString TranslatorDutch::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 530 of file translator_nl.h.
    {
      return "Preconditie";
    }
trPrecondition() [2/2]
QCString TranslatorDutch::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 530 of file translator_nl.h.
    {
      return "Preconditie";
    }
trPrivateAttribs() [1/2]
QCString TranslatorDutch::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 607 of file translator_nl.h.
    {
      return "Private Attributen";
    }
trPrivateAttribs() [2/2]
QCString TranslatorDutch::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 607 of file translator_nl.h.
    {
      return "Private Attributen";
    }
trPrivateMembers() [1/2]
QCString TranslatorDutch::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 335 of file translator_nl.h.
    { return "Private Members"; }
trPrivateMembers() [2/2]
QCString TranslatorDutch::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 335 of file translator_nl.h.
    { return "Private Members"; }
trPrivateSlots() [1/2]
QCString TranslatorDutch::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 337 of file translator_nl.h.
    { return "Private Slots"; }
trPrivateSlots() [2/2]
QCString TranslatorDutch::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 337 of file translator_nl.h.
    { return "Private Slots"; }
trPrivateTypes() [1/2]
QCString TranslatorDutch::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 603 of file translator_nl.h.
    {
      return "Private Typen";
    }
trPrivateTypes() [2/2]
QCString TranslatorDutch::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 603 of file translator_nl.h.
    {
      return "Private Typen";
    }
trProperties() [1/2]
QCString TranslatorDutch::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 755 of file translator_nl.h.
    {
      return "Properties";
    }
trProperties() [2/2]
QCString TranslatorDutch::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 755 of file translator_nl.h.
    {
      return "Properties";
    }
trPropertyDocumentation() [1/2]
QCString TranslatorDutch::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 760 of file translator_nl.h.
    {
      return "Property Documentatie";
    }
trPropertyDocumentation() [2/2]
QCString TranslatorDutch::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 760 of file translator_nl.h.
    {
      return "Property Documentatie";
    }
trProtectedAttribs() [1/2]
QCString TranslatorDutch::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 595 of file translator_nl.h.
    {
      return "Protected Attributen";
    }
trProtectedAttribs() [2/2]
QCString TranslatorDutch::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 595 of file translator_nl.h.
    {
      return "Protected Attributen";
    }
trProtectedMembers() [1/2]
QCString TranslatorDutch::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 329 of file translator_nl.h.
    { return "Protected Members"; }
trProtectedMembers() [2/2]
QCString TranslatorDutch::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 329 of file translator_nl.h.
    { return "Protected Members"; }
trProtectedSlots() [1/2]
QCString TranslatorDutch::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 331 of file translator_nl.h.
    { return "Protected Slots"; }
trProtectedSlots() [2/2]
QCString TranslatorDutch::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 331 of file translator_nl.h.
    { return "Protected Slots"; }
trProtectedTypes() [1/2]
QCString TranslatorDutch::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 591 of file translator_nl.h.
    {
      return "Protected Typen";
    }
trProtectedTypes() [2/2]
QCString TranslatorDutch::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 591 of file translator_nl.h.
    {
      return "Protected Typen";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorDutch::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1545 of file translator_nl.h.
    {
      return "Wordt aangeboden door category @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorDutch::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1545 of file translator_nl.h.
    {
      return "Wordt aangeboden door category @0.";
    }
trPublicAttribs() [1/2]
QCString TranslatorDutch::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 583 of file translator_nl.h.
    {
      return "Public Attributen";
    }
trPublicAttribs() [2/2]
QCString TranslatorDutch::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 583 of file translator_nl.h.
    {
      return "Public Attributen";
    }
trPublicMembers() [1/2]
QCString TranslatorDutch::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 321 of file translator_nl.h.
    { return "Public Members"; }
trPublicMembers() [2/2]
QCString TranslatorDutch::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 321 of file translator_nl.h.
    { return "Public Members"; }
trPublicSlots() [1/2]
QCString TranslatorDutch::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 323 of file translator_nl.h.
    { return "Public Slots"; }
trPublicSlots() [2/2]
QCString TranslatorDutch::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 323 of file translator_nl.h.
    { return "Public Slots"; }
trPublicTypes() [1/2]
QCString TranslatorDutch::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 579 of file translator_nl.h.
    {
      return "Public Typen";
    }
trPublicTypes() [2/2]
QCString TranslatorDutch::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 579 of file translator_nl.h.
    {
      return "Public Typen";
    }
trReferencedBy() [1/2]
QCString TranslatorDutch::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_nl.h.
    {
      return "Wordt aangeroepen door";
    }
trReferencedBy() [2/2]
QCString TranslatorDutch::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_nl.h.
    {
      return "Wordt aangeroepen door";
    }
trReferenceManual() [1/2]
QCString TranslatorDutch::trReferenceManual () [inline], [virtual]
Implements Translator.
Definition at line 200 of file translator_nl.h.
    { return "Naslagwerk"; }
trReferenceManual() [2/2]
QCString TranslatorDutch::trReferenceManual () [inline], [virtual]
Implements Translator.
Definition at line 200 of file translator_nl.h.
    { return "Naslagwerk"; }
trReferences() [1/2]
virtual QCString TranslatorDutch::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 955 of file translator_nl.h.
    {
      return "Gebruikt";
    }
trReferences() [2/2]
virtual QCString TranslatorDutch::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 955 of file translator_nl.h.
    {
      return "Gebruikt";
    }
trReimplementedFromList() [1/2]
QCString TranslatorDutch::trReimplementedFromList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 379 of file translator_nl.h.
    {
      return "Nieuwe implementatie van "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
QCString TranslatorDutch::trReimplementedFromList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 379 of file translator_nl.h.
    {
      return "Nieuwe implementatie van "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
QCString TranslatorDutch::trReimplementedInList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 385 of file translator_nl.h.
    {
      // used in member documentation blocks to produce a list of
      // all member that overwrite the implementation of this member.
      return "Opnieuw ge&iuml;mplementeerd in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
QCString TranslatorDutch::trReimplementedInList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 385 of file translator_nl.h.
    {
      // used in member documentation blocks to produce a list of
      // all member that overwrite the implementation of this member.
      return "Opnieuw ge&iuml;mplementeerd in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
QCString TranslatorDutch::trRelatedFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 277 of file translator_nl.h.
    { return "Documentatie van friends en gerelateerde functies"; }
trRelatedFunctionDocumentation() [2/2]
QCString TranslatorDutch::trRelatedFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 277 of file translator_nl.h.
    { return "Documentatie van friends en gerelateerde functies"; }
trRelatedFunctions() [1/2]
QCString TranslatorDutch::trRelatedFunctions () [inline], [virtual]
Implements Translator.
Definition at line 45 of file translator_nl.h.
    { return "Gerelateerde functies"; }
trRelatedFunctions() [2/2]
QCString TranslatorDutch::trRelatedFunctions () [inline], [virtual]
Implements Translator.
Definition at line 45 of file translator_nl.h.
    { return "Gerelateerde functies"; }
trRelatedPages() [1/2]
QCString TranslatorDutch::trRelatedPages () [inline], [virtual]
Implements Translator.
Definition at line 102 of file translator_nl.h.
    { return "Gerelateerde pagina's"; }
trRelatedPages() [2/2]
QCString TranslatorDutch::trRelatedPages () [inline], [virtual]
Implements Translator.
Definition at line 102 of file translator_nl.h.
    { return "Gerelateerde pagina's"; }
trRelatedPagesDescription() [1/2]
QCString TranslatorDutch::trRelatedPagesDescription () [inline], [virtual]
Implements Translator.
Definition at line 164 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle pagina's die gerelateerde documentatie bevatten:"; }
trRelatedPagesDescription() [2/2]
QCString TranslatorDutch::trRelatedPagesDescription () [inline], [virtual]
Implements Translator.
Definition at line 164 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle pagina's die gerelateerde documentatie bevatten:"; }
trRelatedSubscript() [1/2]
QCString TranslatorDutch::trRelatedSubscript () [inline], [virtual]
Implements Translator.
Definition at line 47 of file translator_nl.h.
    { return "(Merk op dat dit geen member functies zijn.)"; }
trRelatedSubscript() [2/2]
QCString TranslatorDutch::trRelatedSubscript () [inline], [virtual]
Implements Translator.
Definition at line 47 of file translator_nl.h.
    { return "(Merk op dat dit geen member functies zijn.)"; }
trRemarks() [1/2]
QCString TranslatorDutch::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_nl.h.
    {
      return "Opmerkingen";
    }
trRemarks() [2/2]
QCString TranslatorDutch::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_nl.h.
    {
      return "Opmerkingen";
    }
trReturns() [1/2]
QCString TranslatorDutch::trReturns () [inline], [virtual]
Implements Translator.
Definition at line 246 of file translator_nl.h.
    { return "Retourneert"; }
trReturns() [2/2]
QCString TranslatorDutch::trReturns () [inline], [virtual]
Implements Translator.
Definition at line 246 of file translator_nl.h.
    { return "Retourneert"; }
trReturnValues() [1/2]
QCString TranslatorDutch::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 464 of file translator_nl.h.
    { return "Retour waarden"; }
trReturnValues() [2/2]
QCString TranslatorDutch::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 464 of file translator_nl.h.
    { return "Retour waarden"; }
trRTFansicp() [1/2]
virtual QCString TranslatorDutch::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 839 of file translator_nl.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorDutch::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 839 of file translator_nl.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorDutch::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 848 of file translator_nl.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorDutch::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 848 of file translator_nl.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorDutch::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 854 of file translator_nl.h.
    {
      return "Index";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorDutch::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 854 of file translator_nl.h.
    {
      return "Index";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorDutch::trRTFTableOfContents () [inline], [virtual]
Implements Translator.
Definition at line 984 of file translator_nl.h.
    { return "Inhoudsopgave"; }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorDutch::trRTFTableOfContents () [inline], [virtual]
Implements Translator.
Definition at line 984 of file translator_nl.h.
    { return "Inhoudsopgave"; }
trSearch() [1/2]
QCString TranslatorDutch::trSearch () [inline], [virtual]
Implements Translator.
Definition at line 106 of file translator_nl.h.
    { return "Zoeken"; }
trSearch() [2/2]
QCString TranslatorDutch::trSearch () [inline], [virtual]
Implements Translator.
Definition at line 106 of file translator_nl.h.
    { return "Zoeken"; }
trSearching() [1/2]
virtual QCString TranslatorDutch::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1402 of file translator_nl.h.
    {
      return "Zoeken...";
    }
trSearching() [2/2]
virtual QCString TranslatorDutch::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1402 of file translator_nl.h.
    {
      return "Zoeken...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorDutch::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1113 of file translator_nl.h.
    {
      return "Gevonden:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorDutch::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1113 of file translator_nl.h.
    {
      return "Gevonden:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorDutch::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1094 of file translator_nl.h.
    {
      if (numDocuments==0)
      {
        return "Helaas, er zijn geen documenten gevonden die aan de zoekopdracht voldoen.";
      }
      else if (numDocuments==1)
      {
        return "Er is <b>1</b> document gevonden dat aan de zoekopdracht voldoet.";
      }
      else
      {
        return "Er zijn <b>$num</b> documenten gevonden die aan de zoekopdracht voldoen. "
               "De beste resultaten worden eerst getoond.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorDutch::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1094 of file translator_nl.h.
    {
      if (numDocuments==0)
      {
        return "Helaas, er zijn geen documenten gevonden die aan de zoekopdracht voldoen.";
      }
      else if (numDocuments==1)
      {
        return "Er is <b>1</b> document gevonden dat aan de zoekopdracht voldoet.";
      }
      else
      {
        return "Er zijn <b>$num</b> documenten gevonden die aan de zoekopdracht voldoen. "
               "De beste resultaten worden eerst getoond.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorDutch::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1082 of file translator_nl.h.
    {
      return "Zoek Resultaten";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorDutch::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1082 of file translator_nl.h.
    {
      return "Zoek Resultaten";
    }
trSeeAlso() [1/2]
QCString TranslatorDutch::trSeeAlso () [inline], [virtual]
Implements Translator.
Definition at line 248 of file translator_nl.h.
    { return "Zie ook"; }
trSeeAlso() [2/2]
QCString TranslatorDutch::trSeeAlso () [inline], [virtual]
Implements Translator.
Definition at line 248 of file translator_nl.h.
    { return "Zie ook"; }
trSequenceDocumentation() [1/2]
virtual QCString TranslatorDutch::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1760 of file translator_nl.h.
    { return "Documentatie van reeksen"; }
trSequenceDocumentation() [2/2]
virtual QCString TranslatorDutch::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1760 of file translator_nl.h.
    { return "Documentatie van reeksen"; }
trSequences() [1/2]
virtual QCString TranslatorDutch::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 1758 of file translator_nl.h.
    { return "Reeksen"; }
trSequences() [2/2]
virtual QCString TranslatorDutch::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 1758 of file translator_nl.h.
    { return "Reeksen"; }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorDutch::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1620 of file translator_nl.h.
    { QCString result = "De documentatie voor deze service is gegenereerd op grond van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorDutch::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1620 of file translator_nl.h.
    { QCString result = "De documentatie voor deze service is gegenereerd op grond van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorDutch::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1606 of file translator_nl.h.
    {
      QCString result=sName;
      result+=" Service Referentie";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorDutch::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1606 of file translator_nl.h.
    {
      QCString result=sName;
      result+=" Service Referentie";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorDutch::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1591 of file translator_nl.h.
    { return "Ge&iuml;ncludeerde Services"; }
trServices() [2/2]
virtual QCString TranslatorDutch::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1591 of file translator_nl.h.
    { return "Ge&iuml;ncludeerde Services"; }
trSignals() [1/2]
QCString TranslatorDutch::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 325 of file translator_nl.h.
    { return "Signals"; }
trSignals() [2/2]
QCString TranslatorDutch::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 325 of file translator_nl.h.
    { return "Signals"; }
trSince() [1/2]
QCString TranslatorDutch::trSince () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_nl.h.
    {
      return "Sinds";
    }
trSince() [2/2]
QCString TranslatorDutch::trSince () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_nl.h.
    {
      return "Sinds";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorDutch::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1628 of file translator_nl.h.
    { QCString result = "De documentatie voor deze singleton is gegenereerd op grond van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorDutch::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1628 of file translator_nl.h.
    { QCString result = "De documentatie voor deze singleton is gegenereerd op grond van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorDutch::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1613 of file translator_nl.h.
    {
      QCString result=sName;
      result+=" Singleton Referentie";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorDutch::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1613 of file translator_nl.h.
    {
      QCString result=sName;
      result+=" Singleton Referentie";
      return result;
    }
trSliceInterfaces() [1/2]
virtual QCString TranslatorDutch::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 1766 of file translator_nl.h.
    { return "Interfaces"; }
trSliceInterfaces() [2/2]
virtual QCString TranslatorDutch::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 1766 of file translator_nl.h.
    { return "Interfaces"; }
trSourceFile() [1/2]
virtual QCString TranslatorDutch::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1124 of file translator_nl.h.
    {
      return filename + " Bron Bestand";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorDutch::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1124 of file translator_nl.h.
    {
      return filename + " Bron Bestand";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorDutch::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1053 of file translator_nl.h.
    {
      return "Statische Package Attributen";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorDutch::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1053 of file translator_nl.h.
    {
      return "Statische Package Attributen";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorDutch::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1039 of file translator_nl.h.
    {
      return "Statische Package Functies";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorDutch::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1039 of file translator_nl.h.
    {
      return "Statische Package Functies";
    }
trStaticPrivateAttribs() [1/2]
QCString TranslatorDutch::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 611 of file translator_nl.h.
    {
      return "Static Private Attributen";
    }
trStaticPrivateAttribs() [2/2]
QCString TranslatorDutch::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 611 of file translator_nl.h.
    {
      return "Static Private Attributen";
    }
trStaticPrivateMembers() [1/2]
QCString TranslatorDutch::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 339 of file translator_nl.h.
    { return "Static Private Members"; }
trStaticPrivateMembers() [2/2]
QCString TranslatorDutch::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 339 of file translator_nl.h.
    { return "Static Private Members"; }
trStaticProtectedAttribs() [1/2]
QCString TranslatorDutch::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 599 of file translator_nl.h.
    {
      return "Static Protected Attributen";
    }
trStaticProtectedAttribs() [2/2]
QCString TranslatorDutch::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 599 of file translator_nl.h.
    {
      return "Static Protected Attributen";
    }
trStaticProtectedMembers() [1/2]
QCString TranslatorDutch::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 333 of file translator_nl.h.
    { return "Static Protected Members"; }
trStaticProtectedMembers() [2/2]
QCString TranslatorDutch::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 333 of file translator_nl.h.
    { return "Static Protected Members"; }
trStaticPublicAttribs() [1/2]
QCString TranslatorDutch::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 587 of file translator_nl.h.
    {
      return "Static Public Attributen";
    }
trStaticPublicAttribs() [2/2]
QCString TranslatorDutch::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 587 of file translator_nl.h.
    {
      return "Static Public Attributen";
    }
trStaticPublicMembers() [1/2]
QCString TranslatorDutch::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 327 of file translator_nl.h.
    { return "Static Public Members"; }
trStaticPublicMembers() [2/2]
QCString TranslatorDutch::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 327 of file translator_nl.h.
    { return "Static Public Members"; }
trStructDocumentation() [1/2]
virtual QCString TranslatorDutch::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1788 of file translator_nl.h.
    { return "Documentatie van structs"; }
trStructDocumentation() [2/2]
virtual QCString TranslatorDutch::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 1788 of file translator_nl.h.
    { return "Documentatie van structs"; }
trStructIndex() [1/2]
virtual QCString TranslatorDutch::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 1782 of file translator_nl.h.
    { return "Index van struct"; }
trStructIndex() [2/2]
virtual QCString TranslatorDutch::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 1782 of file translator_nl.h.
    { return "Index van struct"; }
trStructList() [1/2]
virtual QCString TranslatorDutch::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 1784 of file translator_nl.h.
    { return "Lijst van struct"; }
trStructList() [2/2]
virtual QCString TranslatorDutch::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 1784 of file translator_nl.h.
    { return "Lijst van struct"; }
trStructListDescription() [1/2]
virtual QCString TranslatorDutch::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 1786 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle structs, elk met een korte beschrijving:"; }
trStructListDescription() [2/2]
virtual QCString TranslatorDutch::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 1786 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle structs, elk met een korte beschrijving:"; }
trStructs() [1/2]
virtual QCString TranslatorDutch::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 1780 of file translator_nl.h.
    { return "Structs"; }
trStructs() [2/2]
virtual QCString TranslatorDutch::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 1780 of file translator_nl.h.
    { return "Structs"; }
trSubprogram() [1/2]
virtual QCString TranslatorDutch::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1366 of file translator_nl.h.
    {
      QCString result((first_capital ? "Subprogramma" : "subprogramma"));
      if (!singular) result+="s";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorDutch::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1366 of file translator_nl.h.
    {
      QCString result((first_capital ? "Subprogramma" : "subprogramma"));
      if (!singular) result+="s";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorDutch::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1243 of file translator_nl.h.
    { return "Functie/Subroutine Documentatie"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorDutch::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1243 of file translator_nl.h.
    { return "Functie/Subroutine Documentatie"; }
trSubprograms() [1/2]
virtual QCString TranslatorDutch::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1237 of file translator_nl.h.
    { return "Functies/Subroutines"; }
trSubprograms() [2/2]
virtual QCString TranslatorDutch::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1237 of file translator_nl.h.
    { return "Functies/Subroutines"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorDutch::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1497 of file translator_nl.h.
    { return "Template Parameters"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorDutch::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1497 of file translator_nl.h.
    { return "Template Parameters"; }
trTest() [1/2]
QCString TranslatorDutch::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 740 of file translator_nl.h.
    {
      return "Test";
    }
trTest() [2/2]
QCString TranslatorDutch::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 740 of file translator_nl.h.
    {
      return "Test";
    }
trTestList() [1/2]
QCString TranslatorDutch::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 745 of file translator_nl.h.
    {
      return "Test Lijst";
    }
trTestList() [2/2]
QCString TranslatorDutch::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 745 of file translator_nl.h.
    {
      return "Test Lijst";
    }
trThisIsTheListOfAllMembers() [1/2]
QCString TranslatorDutch::trThisIsTheListOfAllMembers () [inline], [virtual]
Implements Translator.
Definition at line 74 of file translator_nl.h.
    { return "Dit is de complete lijst van alle members voor"; }
trThisIsTheListOfAllMembers() [2/2]
QCString TranslatorDutch::trThisIsTheListOfAllMembers () [inline], [virtual]
Implements Translator.
Definition at line 74 of file translator_nl.h.
    { return "Dit is de complete lijst van alle members voor"; }
trTodo() [1/2]
QCString TranslatorDutch::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 622 of file translator_nl.h.
    {
      return "Todo";
    }
trTodo() [2/2]
QCString TranslatorDutch::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 622 of file translator_nl.h.
    {
      return "Todo";
    }
trTodoList() [1/2]
QCString TranslatorDutch::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 627 of file translator_nl.h.
    {
      return "Todo Lijst";
    }
trTodoList() [2/2]
QCString TranslatorDutch::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 627 of file translator_nl.h.
    {
      return "Todo Lijst";
    }
trType() [1/2]
virtual QCString TranslatorDutch::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1356 of file translator_nl.h.
    {
      QCString result((first_capital ? "Type" : "type"));
      if (!singular) result+="s";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorDutch::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1356 of file translator_nl.h.
    {
      QCString result((first_capital ? "Type" : "type"));
      if (!singular) result+="s";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorDutch::trTypeConstraints () [inline], [virtual]
C# Type Contraint list
Implements Translator.
Definition at line 1374 of file translator_nl.h.
    {
      return "Type Beperkingen";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorDutch::trTypeConstraints () [inline], [virtual]
C# Type Contraint list
Implements Translator.
Definition at line 1374 of file translator_nl.h.
    {
      return "Type Beperkingen";
    }
trTypedefDocumentation() [1/2]
QCString TranslatorDutch::trTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 217 of file translator_nl.h.
    { return "Documentatie van typedefs"; }
trTypedefDocumentation() [2/2]
QCString TranslatorDutch::trTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 217 of file translator_nl.h.
    { return "Documentatie van typedefs"; }
trTypedefs() [1/2]
QCString TranslatorDutch::trTypedefs () [inline], [virtual]
Implements Translator.
Definition at line 205 of file translator_nl.h.
    { return "Typedefs"; }
trTypedefs() [2/2]
QCString TranslatorDutch::trTypedefs () [inline], [virtual]
Implements Translator.
Definition at line 205 of file translator_nl.h.
    { return "Typedefs"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorDutch::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1231 of file translator_nl.h.
    { return "Data Type Documentatie"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorDutch::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1231 of file translator_nl.h.
    { return "Data Type Documentatie"; }
trVariableDocumentation() [1/2]
QCString TranslatorDutch::trVariableDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 225 of file translator_nl.h.
    { return "Documentatie van variabelen"; }
trVariableDocumentation() [2/2]
QCString TranslatorDutch::trVariableDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 225 of file translator_nl.h.
    { return "Documentatie van variabelen"; }
trVariables() [1/2]
QCString TranslatorDutch::trVariables () [inline], [virtual]
Implements Translator.
Definition at line 211 of file translator_nl.h.
    { return "Variabelen"; }
trVariables() [2/2]
QCString TranslatorDutch::trVariables () [inline], [virtual]
Implements Translator.
Definition at line 211 of file translator_nl.h.
    { return "Variabelen"; }
trVersion() [1/2]
QCString TranslatorDutch::trVersion () [inline], [virtual]
Implements Translator.
Definition at line 242 of file translator_nl.h.
    { return "Versie"; }
trVersion() [2/2]
QCString TranslatorDutch::trVersion () [inline], [virtual]
Implements Translator.
Definition at line 242 of file translator_nl.h.
    { return "Versie"; }
trVhdlType() [1/2]
virtual QCString TranslatorDutch::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 1665 of file translator_nl.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Bibliotheek";
          else return "Bibliotheken";
        case VhdlDocGen::PACKAGE:
          if (single) return "Package";
          else return "Packages";
        case VhdlDocGen::SIGNAL:
          if (single) return "Signal";
          else return "Signals";
        case VhdlDocGen::COMPONENT:
          if (single) return "Bestanddeel";
          else return "Bestanddelen";
        case VhdlDocGen::CONSTANT:
          if (single) return "Konstante";
          else return "Konstanten";
        case VhdlDocGen::ENTITY:
          if (single) return "Entiteit";
          else return "Entiteiten";
        case VhdlDocGen::TYPE:
          if (single) return "Type";
          else return "Types";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Ondertype";
          else return "Ondertypes";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funktie";
          else return "Funkties";
        case VhdlDocGen::RECORD:
          if (single) return "Record";
          else return "Records";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedure";
          else return "Procedures";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Architectuur";
          else return "Architecturen";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Attribuut";
          else return "Attributen";
        case VhdlDocGen::PROCESS:
          if (single) return "Proces";
          else return "Processen";
        case VhdlDocGen::PORT:
          if (single) return "Poort";
          else return "Porten";
        case VhdlDocGen::USE:
          if (single) return "gebruiks clausule";
          else return "Gebruiks Clausules";
        case VhdlDocGen::GENERIC:
          if (single) return "Algemeen";
          else return "Algemene";
        case VhdlDocGen::PACKAGE_BODY:
          return "Package Body";
        case VhdlDocGen::UNITS:
          return "Eenheden";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Gedeelde Variable";
          else return "Gedeelde Variablen";
        case VhdlDocGen::VFILE:
          if (single) return "Bestand";
          else return "Bestanden";
        case VhdlDocGen::GROUP:
          if (single) return "Groep";
          else return "Groepen";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instanti&euml;ring";
          else return "Instanti&euml;ringen";
        case VhdlDocGen::ALIAS:
          if (single) return "Alias";
          else return "Aliases";
        case VhdlDocGen::CONFIG:
          if (single) return "Configuratie";
          else return "Configuraties";
        case VhdlDocGen::MISCELLANEOUS:
          return "Diverse";
        case VhdlDocGen::UCF_CONST:
          return "Limiteringen";
        default:
          return "Klasse";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trVhdlType() [2/2]
virtual QCString TranslatorDutch::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 1665 of file translator_nl.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Bibliotheek";
          else return "Bibliotheken";
        case VhdlDocGen::PACKAGE:
          if (single) return "Package";
          else return "Packages";
        case VhdlDocGen::SIGNAL:
          if (single) return "Signal";
          else return "Signals";
        case VhdlDocGen::COMPONENT:
          if (single) return "Bestanddeel";
          else return "Bestanddelen";
        case VhdlDocGen::CONSTANT:
          if (single) return "Konstante";
          else return "Konstanten";
        case VhdlDocGen::ENTITY:
          if (single) return "Entiteit";
          else return "Entiteiten";
        case VhdlDocGen::TYPE:
          if (single) return "Type";
          else return "Types";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Ondertype";
          else return "Ondertypes";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funktie";
          else return "Funkties";
        case VhdlDocGen::RECORD:
          if (single) return "Record";
          else return "Records";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedure";
          else return "Procedures";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Architectuur";
          else return "Architecturen";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Attribuut";
          else return "Attributen";
        case VhdlDocGen::PROCESS:
          if (single) return "Proces";
          else return "Processen";
        case VhdlDocGen::PORT:
          if (single) return "Poort";
          else return "Porten";
        case VhdlDocGen::USE:
          if (single) return "gebruiks clausule";
          else return "Gebruiks Clausules";
        case VhdlDocGen::GENERIC:
          if (single) return "Algemeen";
          else return "Algemene";
        case VhdlDocGen::PACKAGE_BODY:
          return "Package Body";
        case VhdlDocGen::UNITS:
          return "Eenheden";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Gedeelde Variable";
          else return "Gedeelde Variablen";
        case VhdlDocGen::VFILE:
          if (single) return "Bestand";
          else return "Bestanden";
        case VhdlDocGen::GROUP:
          if (single) return "Groep";
          else return "Groepen";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instanti&euml;ring";
          else return "Instanti&euml;ringen";
        case VhdlDocGen::ALIAS:
          if (single) return "Alias";
          else return "Aliases";
        case VhdlDocGen::CONFIG:
          if (single) return "Configuratie";
          else return "Configuraties";
        case VhdlDocGen::MISCELLANEOUS:
          return "Diverse";
        case VhdlDocGen::UCF_CONST:
          return "Limiteringen";
        default:
          return "Klasse";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
QCString TranslatorDutch::trWarning () [inline], [virtual]
Implements Translator.
Definition at line 240 of file translator_nl.h.
    { return "Waarschuwing"; }
trWarning() [2/2]
QCString TranslatorDutch::trWarning () [inline], [virtual]
Implements Translator.
Definition at line 240 of file translator_nl.h.
    { return "Waarschuwing"; }
trWriteList() [1/2]
QCString TranslatorDutch::trWriteList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 343 of file translator_nl.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" en ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
QCString TranslatorDutch::trWriteList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 343 of file translator_nl.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" en ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_nl.h
doxygen/src/translator_nl.h