MemberGroupListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
MemberGroupListContext ()
MemberGroupListContext (const Definition *def, const QCString &relPath, const MemberGroupRefList &list)
MemberGroupListContext (const Definition *def, const QCString &relPath, const MemberGroupList &list, bool subGrouping)
virtual ~MemberGroupListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
MemberGroupListContext ()
MemberGroupListContext (const Definition *def, const QCString &relPath, const MemberGroupRefList &list)
MemberGroupListContext (const Definition *def, const QCString &relPath, const MemberGroupList &list, bool subGrouping)
virtual ~MemberGroupListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc (const Definition *def, const QCString &relPath, const MemberGroupRefList &list)
static TemplateListIntfPtr alloc (const Definition *def, const QCString &relPath, const MemberGroupList &list, bool subGrouping)
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc (const Definition *def, const QCString &relPath, const MemberGroupRefList &list)
static TemplateListIntfPtr alloc (const Definition *def, const QCString &relPath, const MemberGroupList &list, bool subGrouping)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 1048 of file context.h.
Constructor & Destructor Documentation
MemberGroupListContext() [1/6]
MemberGroupListContext::MemberGroupListContext ()
Definition at line 7861 of file context.cpp.
                                               : p(std::make_unique<Private>())
{
}
MemberGroupListContext() [2/6]
MemberGroupListContext::MemberGroupListContext (const Definition * def, const QCString & relPath, const MemberGroupRefList & list)
Definition at line 7865 of file context.cpp.
                                                                                                                           : p(std::make_unique<Private>())
{
  for (const auto &mg : list)
  {
    p->addMemberGroup(def,relPath,mg);
  }
}
References p.
MemberGroupListContext() [3/6]
MemberGroupListContext::MemberGroupListContext (const Definition * def, const QCString & relPath, const MemberGroupList & list, bool subGrouping)
Definition at line 7873 of file context.cpp.
                                                                                                                                         : p(std::make_unique<Private>())
{
  for (const auto &mg : list)
  {
    if (!mg->allMembersInSameSection() || !subGrouping)
    {
      p->addMemberGroup(def,relPath,mg.get());
    }
  }
}
References p.
 MemberGroupListContext() [1/2]
MemberGroupListContext::~MemberGroupListContext () [virtual]
Definition at line 7884 of file context.cpp.
{
}
MemberGroupListContext() [4/6]
MemberGroupListContext::MemberGroupListContext ()
MemberGroupListContext() [5/6]
MemberGroupListContext::MemberGroupListContext (const Definition * def, const QCString & relPath, const MemberGroupRefList & list)
MemberGroupListContext() [6/6]
MemberGroupListContext::MemberGroupListContext (const Definition * def, const QCString & relPath, const MemberGroupList & list, bool subGrouping)
 MemberGroupListContext() [2/2]
virtual MemberGroupListContext::~MemberGroupListContext () [virtual]
Member Function Documentation
alloc() [1/6]
static TemplateListIntfPtr MemberGroupListContext::alloc () [inline], [static]
Definition at line 1051 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<MemberGroupListContext>()); }
Referenced by ClassContext::Private::createMemberGroups(), NamespaceContext::Private::createMemberGroups(), FileContext::Private::createMemberGroups(), ModuleContext::Private::createMemberGroups(), MemberGroupInfoContext::Private::createMemberGroups(), and MemberListInfoContext::Private::createMemberGroups().
alloc() [2/6]
static TemplateListIntfPtr MemberGroupListContext::alloc () [inline], [static]
Definition at line 1051 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<MemberGroupListContext>()); }
alloc() [3/6]
static TemplateListIntfPtr MemberGroupListContext::alloc (const Definition * def, const QCString & relPath, const MemberGroupList & list, bool subGrouping) [inline], [static]
Definition at line 1055 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<MemberGroupListContext>(def,relPath,list,subGrouping)); }
alloc() [4/6]
static TemplateListIntfPtr MemberGroupListContext::alloc (const Definition * def, const QCString & relPath, const MemberGroupList & list, bool subGrouping) [inline], [static]
Definition at line 1055 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<MemberGroupListContext>(def,relPath,list,subGrouping)); }
alloc() [5/6]
static TemplateListIntfPtr MemberGroupListContext::alloc (const Definition * def, const QCString & relPath, const MemberGroupRefList & list) [inline], [static]
Definition at line 1053 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<MemberGroupListContext>(def,relPath,list)); }
alloc() [6/6]
static TemplateListIntfPtr MemberGroupListContext::alloc (const Definition * def, const QCString & relPath, const MemberGroupRefList & list) [inline], [static]
Definition at line 1053 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<MemberGroupListContext>(def,relPath,list)); }
at() [1/2]
TemplateVariant MemberGroupListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 7894 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant MemberGroupListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t MemberGroupListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 7889 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t MemberGroupListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr MemberGroupListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 7899 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr MemberGroupListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > MemberGroupListContext::p [private]
Definition at line 1070 of file context.h.
Referenced by at(), count(), createIterator(), and MemberGroupListContext().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp