ClassDefImpl Class Reference
Classes
class IMPL
Public Member Functions
ClassDefImpl (const QCString &fileName, int startLine, int startColumn, const QCString &name, CompoundType ct, const QCString &ref=QCString(), const QCString &fName=QCString(), bool isSymbol=TRUE, bool isJavaEnum=FALSE)
~ClassDefImpl ()
virtual ClassDef * resolveAlias ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString getInstanceOutputFileBase () const
virtual QCString getSourceFileBase () const
virtual QCString getReference () const
virtual bool isReference () const
virtual bool isLocal () const
virtual ClassLinkedRefMap getClasses () const
virtual bool hasDocumentation () const
virtual bool hasDetailedDescription () const
virtual QCString collaborationGraphFileName () const
virtual QCString inheritanceGraphFileName () const
virtual QCString displayName (bool includeScope=TRUE) const
virtual CompoundType compoundType () const
virtual QCString compoundTypeString () const
virtual const BaseClassList & baseClasses () const
virtual void updateBaseClasses (const BaseClassList &bcd)
virtual const BaseClassList & subClasses () const
virtual void updateSubClasses (const BaseClassList &bcd)
virtual const MemberNameInfoLinkedMap & memberNameInfoLinkedMap () const
virtual Protection protection () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool isVisibleInHierarchy () const
virtual bool visibleInParentsDeclList () const
virtual const ArgumentList & templateArguments () const
virtual FileDef * getFileDef () const
virtual const MemberDef * getMemberByName (const QCString &) const
virtual int isBaseClass (const ClassDef *bcd, bool followInstances) const
virtual bool isSubClass (ClassDef *bcd, int level=0) const
virtual bool isAccessibleMember (const MemberDef *md) const
virtual const TemplateInstanceList & getTemplateInstances () const
virtual const ClassDef * templateMaster () const
virtual bool isTemplate () const
virtual const IncludeInfo * includeInfo () const
virtual const UsesClassList & usedImplementationClasses () const
virtual const UsesClassList & usedByImplementationClasses () const
virtual const ConstraintClassList & templateTypeConstraints () const
virtual bool isTemplateArgument () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual ArgumentLists getTemplateParameterLists () const
virtual QCString qualifiedNameWithTemplateParameters (const ArgumentLists *actualParams=0, uint *actualParamIndex=0) const
virtual bool isAbstract () const
virtual bool isObjectiveC () const
virtual bool isFortran () const
virtual bool isCSharp () const
virtual bool isFinal () const
virtual bool isSealed () const
virtual bool isPublished () const
virtual bool isExtension () const
virtual bool isForwardDeclared () const
virtual bool isInterface () const
virtual ClassDef * categoryOf () const
virtual QCString className () const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberGroupList & getMemberGroups () const
virtual const TemplateNameMap & getTemplateBaseClassNames () const
virtual bool isUsedOnly () const
virtual QCString anchor () const
virtual bool isEmbeddedInOuterScope () const
virtual bool isSimple () const
virtual const ClassDef * tagLessReference () const
virtual const MemberDef * isSmartPointer () const
virtual bool isJavaEnum () const
virtual QCString title () const
virtual QCString generatedFromFiles () const
virtual const FileList & usedFiles () const
virtual const ArgumentList & typeConstraints () const
virtual const ExampleList & getExamples () const
virtual bool hasExamples () const
virtual QCString getMemberListFileName () const
virtual bool subGrouping () const
virtual bool isSliceLocal () const
virtual bool hasNonReferenceSuperClass () const
virtual QCString requiresClause () const
virtual ClassDef * insertTemplateInstance (const QCString &fileName, int startLine, int startColumn, const QCString &templSpec, bool &freshInstance) const
virtual void insertBaseClass (ClassDef *, const QCString &name, Protection p, Specifier s, const QCString &t=QCString())
virtual void insertSubClass (ClassDef *, Protection p, Specifier s, const QCString &t=QCString())
virtual void setIncludeFile (FileDef *fd, const QCString &incName, bool local, bool force)
virtual void insertMember (MemberDef *)
virtual void insertUsedFile (const FileDef *)
virtual bool addExample (const QCString &anchor, const QCString &name, const QCString &file)
virtual void mergeCategory (ClassDef *category)
virtual void setFileDef (FileDef *fd)
virtual void setSubGrouping (bool enabled)
virtual void setProtection (Protection p)
virtual void setGroupDefForAllMembers (GroupDef *g, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs)
virtual void addInnerCompound (const Definition *d)
virtual void addUsedClass (ClassDef *cd, const QCString &accessName, Protection prot)
virtual void addUsedByClass (ClassDef *cd, const QCString &accessName, Protection prot)
virtual void setIsStatic (bool b)
virtual void setCompoundType (CompoundType t)
virtual void setClassName (const QCString &name)
virtual void setClassSpecifier (uint64 spec)
virtual void setTemplateArguments (const ArgumentList &al)
virtual void setTemplateBaseClassNames (const TemplateNameMap &templateNames)
virtual void setTemplateMaster (const ClassDef *tm)
virtual void setTypeConstraints (const ArgumentList &al)
virtual void addMembersToTemplateInstance (const ClassDef *cd, const ArgumentList &templateArguments, const QCString &templSpec)
virtual void makeTemplateArgument (bool b=TRUE)
virtual void setCategoryOf (ClassDef *cd)
virtual void setUsedOnly (bool b)
virtual void setTagLessReference (const ClassDef *cd)
virtual void setName (const QCString &name)
virtual void setMetaData (const QCString &md)
virtual void findSectionsInDocumentation ()
virtual void addMembersToMemberGroup ()
virtual void addListReferences ()
virtual void addTypeConstraints ()
virtual void computeAnchors ()
virtual void mergeMembers ()
virtual void sortMemberLists ()
virtual void distributeMemberGroupDocumentation ()
virtual void writeDocumentation (OutputList &ol) const
virtual void writeDocumentationForInnerClasses (OutputList &ol) const
virtual void writeMemberPages (OutputList &ol) const
virtual void writeMemberList (OutputList &ol) const
virtual void writeDeclaration (OutputList &ol, const MemberDef *md, bool inGroup, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const
virtual void writeSummaryLinks (OutputList &ol) const
virtual void reclassifyMember (MemberDefMutable *md, MemberType t)
virtual void writeInlineDocumentation (OutputList &ol) const
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const
virtual void removeMemberFromLists (MemberDef *md)
virtual void setAnonymousEnumType ()
virtual void countMembers ()
virtual void sortAllMembersList ()
virtual void addGroupedInheritedMembers (OutputList &ol, MemberListType lt, const ClassDef *inheritedFrom, const QCString &inheritId) const
virtual void writeTagFile (TextStream &)
virtual int countMembersIncludingGrouped (MemberListType lt, const ClassDef *inheritedFrom, bool additional) const
virtual int countInheritanceNodes () const
virtual int countMemberDeclarations (MemberListType lt, const ClassDef *inheritedFrom, int lt2, bool invert, bool showAlways, ClassDefSet &visitedClasses) const
virtual void writeMemberDeclarations (OutputList &ol, ClassDefSet &visitedClasses, MemberListType lt, const QCString &title, const QCString &subTitle=QCString(), bool showInline=FALSE, const ClassDef *inheritedFrom=0, int lt2=-1, bool invert=FALSE, bool showAlways=FALSE) const
virtual void setRequiresClause (const QCString &req)
ClassDefImpl (const QCString &fileName, int startLine, int startColumn, const QCString &name, CompoundType ct, const QCString &ref=QCString(), const QCString &fName=QCString(), bool isSymbol=TRUE, bool isJavaEnum=FALSE)
~ClassDefImpl ()
virtual ClassDef * resolveAlias ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString getInstanceOutputFileBase () const
virtual QCString getSourceFileBase () const
virtual QCString getReference () const
virtual bool isReference () const
virtual bool isLocal () const
virtual ClassLinkedRefMap getClasses () const
virtual bool hasDocumentation () const
virtual bool hasDetailedDescription () const
virtual QCString collaborationGraphFileName () const
virtual QCString inheritanceGraphFileName () const
virtual QCString displayName (bool includeScope=TRUE) const
virtual CompoundType compoundType () const
virtual QCString compoundTypeString () const
virtual const BaseClassList & baseClasses () const
virtual void updateBaseClasses (const BaseClassList &bcd)
virtual const BaseClassList & subClasses () const
virtual void updateSubClasses (const BaseClassList &bcd)
virtual const MemberNameInfoLinkedMap & memberNameInfoLinkedMap () const
virtual Protection protection () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool isVisibleInHierarchy () const
virtual bool visibleInParentsDeclList () const
virtual const ArgumentList & templateArguments () const
virtual FileDef * getFileDef () const
virtual const MemberDef * getMemberByName (const QCString &) const
virtual int isBaseClass (const ClassDef *bcd, bool followInstances) const
virtual bool isSubClass (ClassDef *bcd, int level=0) const
virtual bool isAccessibleMember (const MemberDef *md) const
virtual const TemplateInstanceList & getTemplateInstances () const
virtual const ClassDef * templateMaster () const
virtual bool isTemplate () const
virtual const IncludeInfo * includeInfo () const
virtual const UsesClassList & usedImplementationClasses () const
virtual const UsesClassList & usedByImplementationClasses () const
virtual const ConstraintClassList & templateTypeConstraints () const
virtual bool isTemplateArgument () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual ArgumentLists getTemplateParameterLists () const
virtual QCString qualifiedNameWithTemplateParameters (const ArgumentLists *actualParams=0, uint *actualParamIndex=0) const
virtual bool isAbstract () const
virtual bool isObjectiveC () const
virtual bool isFortran () const
virtual bool isCSharp () const
virtual bool isFinal () const
virtual bool isSealed () const
virtual bool isPublished () const
virtual bool isExtension () const
virtual bool isForwardDeclared () const
virtual bool isInterface () const
virtual ClassDef * categoryOf () const
virtual QCString className () const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberGroupList & getMemberGroups () const
virtual const TemplateNameMap & getTemplateBaseClassNames () const
virtual bool isUsedOnly () const
virtual QCString anchor () const
virtual bool isEmbeddedInOuterScope () const
virtual bool isSimple () const
virtual const ClassDef * tagLessReference () const
virtual const MemberDef * isSmartPointer () const
virtual bool isJavaEnum () const
virtual QCString title () const
virtual QCString generatedFromFiles () const
virtual const FileList & usedFiles () const
virtual const ArgumentList & typeConstraints () const
virtual const ExampleList & getExamples () const
virtual bool hasExamples () const
virtual QCString getMemberListFileName () const
virtual bool subGrouping () const
virtual bool isSliceLocal () const
virtual bool hasNonReferenceSuperClass () const
virtual QCString requiresClause () const
virtual ClassDef * insertTemplateInstance (const QCString &fileName, int startLine, int startColumn, const QCString &templSpec, bool &freshInstance) const
virtual void insertBaseClass (ClassDef *, const QCString &name, Protection p, Specifier s, const QCString &t=QCString())
virtual void insertSubClass (ClassDef *, Protection p, Specifier s, const QCString &t=QCString())
virtual void setIncludeFile (FileDef *fd, const QCString &incName, bool local, bool force)
virtual void insertMember (MemberDef *)
virtual void insertUsedFile (const FileDef *)
virtual bool addExample (const QCString &anchor, const QCString &name, const QCString &file)
virtual void mergeCategory (ClassDef *category)
virtual void setFileDef (FileDef *fd)
virtual void setSubGrouping (bool enabled)
virtual void setProtection (Protection p)
virtual void setGroupDefForAllMembers (GroupDef *g, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs)
virtual void addInnerCompound (const Definition *d)
virtual void addUsedClass (ClassDef *cd, const QCString &accessName, Protection prot)
virtual void addUsedByClass (ClassDef *cd, const QCString &accessName, Protection prot)
virtual void setIsStatic (bool b)
virtual void setCompoundType (CompoundType t)
virtual void setClassName (const QCString &name)
virtual void setClassSpecifier (uint64 spec)
virtual void setTemplateArguments (const ArgumentList &al)
virtual void setTemplateBaseClassNames (const TemplateNameMap &templateNames)
virtual void setTemplateMaster (const ClassDef *tm)
virtual void setTypeConstraints (const ArgumentList &al)
virtual void addMembersToTemplateInstance (const ClassDef *cd, const ArgumentList &templateArguments, const QCString &templSpec)
virtual void makeTemplateArgument (bool b=TRUE)
virtual void setCategoryOf (ClassDef *cd)
virtual void setUsedOnly (bool b)
virtual void setTagLessReference (const ClassDef *cd)
virtual void setName (const QCString &name)
virtual void setMetaData (const QCString &md)
virtual void findSectionsInDocumentation ()
virtual void addMembersToMemberGroup ()
virtual void addListReferences ()
virtual void addTypeConstraints ()
virtual void computeAnchors ()
virtual void mergeMembers ()
virtual void sortMemberLists ()
virtual void distributeMemberGroupDocumentation ()
virtual void writeDocumentation (OutputList &ol) const
virtual void writeDocumentationForInnerClasses (OutputList &ol) const
virtual void writeMemberPages (OutputList &ol) const
virtual void writeMemberList (OutputList &ol) const
virtual void writeDeclaration (OutputList &ol, const MemberDef *md, bool inGroup, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const
virtual void writeSummaryLinks (OutputList &ol) const
virtual void reclassifyMember (MemberDefMutable *md, MemberType t)
virtual void writeInlineDocumentation (OutputList &ol) const
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const
virtual void removeMemberFromLists (MemberDef *md)
virtual void setAnonymousEnumType ()
virtual void countMembers ()
virtual void sortAllMembersList ()
virtual void addGroupedInheritedMembers (OutputList &ol, MemberListType lt, const ClassDef *inheritedFrom, const QCString &inheritId) const
virtual void writeTagFile (TextStream &)
virtual int countMembersIncludingGrouped (MemberListType lt, const ClassDef *inheritedFrom, bool additional) const
virtual int countInheritanceNodes () const
virtual int countMemberDeclarations (MemberListType lt, const ClassDef *inheritedFrom, int lt2, bool invert, bool showAlways, ClassDefSet &visitedClasses) const
virtual void writeMemberDeclarations (OutputList &ol, ClassDefSet &visitedClasses, MemberListType lt, const QCString &title, const QCString &subTitle=QCString(), bool showInline=FALSE, const ClassDef *inheritedFrom=0, int lt2=-1, bool invert=FALSE, bool showAlways=FALSE) const
virtual void setRequiresClause (const QCString &req)
Private Member Functions
void addUsedInterfaceClasses (MemberDef *md, const QCString &typeStr)
void showUsedFiles (OutputList &ol) const
void writeDocumentationContents (OutputList &ol, const QCString &pageTitle) const
void internalInsertMember (const MemberDef *md, Protection prot, bool addToAllList)
void addMemberToList (MemberListType lt, const MemberDef *md, bool isBrief)
void writeInheritedMemberDeclarations (OutputList &ol, ClassDefSet &visitedClasses, MemberListType lt, int lt2, const QCString &title, const ClassDef *inheritedFrom, bool invert, bool showAlways) const
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title, bool showInline=FALSE) const
void writeSimpleMemberDocumentation (OutputList &ol, MemberListType lt) const
void writePlainMemberDeclaration (OutputList &ol, MemberListType lt, bool inGroup, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const
void writeBriefDescription (OutputList &ol, bool exampleFlag) const
void writeDetailedDescription (OutputList &ol, const QCString &pageType, bool exampleFlag, const QCString &title, const QCString &anchor=QCString()) const
void writeIncludeFiles (OutputList &ol) const
void writeIncludeFilesForSlice (OutputList &ol) const
void writeInheritanceGraph (OutputList &ol) const
void writeCollaborationGraph (OutputList &ol) const
void writeMemberGroups (OutputList &ol, bool showInline=FALSE) const
void writeNestedClasses (OutputList &ol, const QCString &title) const
void writeInlineClasses (OutputList &ol) const
void startMemberDeclarations (OutputList &ol) const
void endMemberDeclarations (OutputList &ol) const
void startMemberDocumentation (OutputList &ol) const
void endMemberDocumentation (OutputList &ol) const
void writeAuthorSection (OutputList &ol) const
void writeMoreLink (OutputList &ol, const QCString &anchor) const
void writeDetailedDocumentationBody (OutputList &ol) const
int countAdditionalInheritedMembers () const
void writeAdditionalInheritedMembers (OutputList &ol) const
void addClassAttributes (OutputList &ol) const
int countInheritedDecMembers (MemberListType lt, const ClassDef *inheritedFrom, bool invert, bool showAlways, ClassDefSet &visitedClasses) const
void getTitleForMemberListType (MemberListType type, QCString &title, QCString &subtitle) const
QCString includeStatement () const
void addTypeConstraint (const QCString &typeConstraint, const QCString &type)
void writeTemplateSpec (OutputList &ol, const Definition *d, const QCString &type, SrcLangExt lang) const
void addUsedInterfaceClasses (MemberDef *md, const QCString &typeStr)
void showUsedFiles (OutputList &ol) const
void writeDocumentationContents (OutputList &ol, const QCString &pageTitle) const
void internalInsertMember (const MemberDef *md, Protection prot, bool addToAllList)
void addMemberToList (MemberListType lt, const MemberDef *md, bool isBrief)
void writeInheritedMemberDeclarations (OutputList &ol, ClassDefSet &visitedClasses, MemberListType lt, int lt2, const QCString &title, const ClassDef *inheritedFrom, bool invert, bool showAlways) const
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title, bool showInline=FALSE) const
void writeSimpleMemberDocumentation (OutputList &ol, MemberListType lt) const
void writePlainMemberDeclaration (OutputList &ol, MemberListType lt, bool inGroup, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const
void writeBriefDescription (OutputList &ol, bool exampleFlag) const
void writeDetailedDescription (OutputList &ol, const QCString &pageType, bool exampleFlag, const QCString &title, const QCString &anchor=QCString()) const
void writeIncludeFiles (OutputList &ol) const
void writeIncludeFilesForSlice (OutputList &ol) const
void writeInheritanceGraph (OutputList &ol) const
void writeCollaborationGraph (OutputList &ol) const
void writeMemberGroups (OutputList &ol, bool showInline=FALSE) const
void writeNestedClasses (OutputList &ol, const QCString &title) const
void writeInlineClasses (OutputList &ol) const
void startMemberDeclarations (OutputList &ol) const
void endMemberDeclarations (OutputList &ol) const
void startMemberDocumentation (OutputList &ol) const
void endMemberDocumentation (OutputList &ol) const
void writeAuthorSection (OutputList &ol) const
void writeMoreLink (OutputList &ol, const QCString &anchor) const
void writeDetailedDocumentationBody (OutputList &ol) const
int countAdditionalInheritedMembers () const
void writeAdditionalInheritedMembers (OutputList &ol) const
void addClassAttributes (OutputList &ol) const
int countInheritedDecMembers (MemberListType lt, const ClassDef *inheritedFrom, bool invert, bool showAlways, ClassDefSet &visitedClasses) const
void getTitleForMemberListType (MemberListType type, QCString &title, QCString &subtitle) const
QCString includeStatement () const
void addTypeConstraint (const QCString &typeConstraint, const QCString &type)
void writeTemplateSpec (OutputList &ol, const Definition *d, const QCString &type, SrcLangExt lang) const
Private Attributes
IMPL * m_impl = 0
Additional Inherited Members
Detailed Description
Implementation of the ClassDef interface
Definition at line 150 of file classdef.cpp.
Constructor & Destructor Documentation
ClassDefImpl() [1/2]
ClassDefImpl::ClassDefImpl (const QCString & fileName, int startLine, int startColumn, const QCString & name, CompoundType ct, const QCString & ref = QCString(), const QCString & fName = QCString(), bool isSymbol = TRUE, bool isJavaEnum = FALSE)
Definition at line 769 of file classdef.cpp.
 : DefinitionMixin(defFileName,defLine,defColumn,removeRedundantWhiteSpace(nm),0,0,isSymbol)
{
  setReference(lref);
  m_impl = new ClassDefImpl::IMPL;
  m_impl->compType = ct;
  m_impl->isJavaEnum = isJavaEnum;
  m_impl->init(defFileName,name(),compoundTypeString(),fName);
  m_impl->memberListFileName = convertNameToFile(compoundTypeString()+name()+"-members");
  m_impl->collabFileName = convertNameToFile(m_impl->fileName+"_coll_graph");
  m_impl->inheritFileName = convertNameToFile(m_impl->fileName+"_inherit_graph");
  if (lref.isEmpty())
  {
    m_impl->fileName = convertNameToFile(m_impl->fileName);
  }
}
References ClassDefImpl::IMPL::collabFileName, compoundTypeString(), ClassDefImpl::IMPL::compType, convertNameToFile(), ClassDefImpl::IMPL::fileName, ClassDefImpl::IMPL::inheritFileName, ClassDefImpl::IMPL::init(), QCString::isEmpty(), isJavaEnum(), ClassDefImpl::IMPL::isJavaEnum, m_impl, ClassDefImpl::IMPL::memberListFileName, DefinitionMixin< ClassDefMutable >::name(), and DefinitionMixin< ClassDefMutable >::setReference().
Referenced by addTypeConstraint(), and insertTemplateInstance().
 ClassDefImpl() [1/2]
ClassDefImpl::~ClassDefImpl ()
Destroys a compound definition.
Definition at line 791 of file classdef.cpp.
{
  delete m_impl;
}
References m_impl.
ClassDefImpl() [2/2]
ClassDefImpl::ClassDefImpl (const QCString & fileName, int startLine, int startColumn, const QCString & name, CompoundType ct, const QCString & ref = QCString(), const QCString & fName = QCString(), bool isSymbol = TRUE, bool isJavaEnum = FALSE)
 ClassDefImpl() [2/2]
ClassDefImpl::~ClassDefImpl ()
Destroys a compound definition.
Member Function Documentation
addClassAttributes() [1/2]
void ClassDefImpl::addClassAttributes (OutputList & ol) const [private]
Definition at line 2474 of file classdef.cpp.
{
  StringVector sl;
  if (isFinal()) sl.push_back("final");
  if (isSealed()) sl.push_back("sealed");
  if (isAbstract()) sl.push_back("abstract");
  if (getLanguage()==SrcLangExt_IDL && isPublished()) sl.push_back("published");
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  if (!sl.empty())
  {
    ol.startLabels();
    size_t i=0;
    for (const auto &s : sl)
    {
      i++;
      ol.writeLabel(s.c_str(),i==sl.size());
    }
    ol.endLabels();
  }
  ol.popGeneratorState();
}
References OutputList::disableAllBut(), OutputList::endLabels(), DefinitionMixin< ClassDefMutable >::getLanguage(), OutputGenerator::Html, isAbstract(), isFinal(), isPublished(), isSealed(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), s, caseconvert::sl, SrcLangExt_IDL, OutputList::startLabels(), and OutputList::writeLabel().
Referenced by writeDocumentation().
addClassAttributes() [2/2]
void ClassDefImpl::addClassAttributes (OutputList & ol) const [private]
addExample() [1/2]
bool ClassDefImpl::addExample (const QCString & anchor, const QCString & name, const QCString & file) [virtual]
Implements ClassDefMutable.
Definition at line 3121 of file classdef.cpp.
{
  return m_impl->examples.inSort(Example(anchor,nameStr,file));
}
References anchor(), Example, ClassDefImpl::IMPL::examples, caseconvert::file, ExampleList::inSort(), and m_impl.
addExample() [2/2]
virtual bool ClassDefImpl::addExample (const QCString & anchor, const QCString & name, const QCString & file) [virtual]
Implements ClassDefMutable.
addGroupedInheritedMembers() [1/2]
void ClassDefImpl::addGroupedInheritedMembers (OutputList & ol, MemberListType lt, const ClassDef * inheritedFrom, const QCString & inheritId) const [virtual]
Implements ClassDefMutable.
Definition at line 4535 of file classdef.cpp.
{
  //printf("** %s::addGroupedInheritedMembers(%p) inheritId=%s\n",qPrint(name()),m_impl->memberGroupSDict,qPrint(inheritId));
  for (const auto &mg : m_impl->memberGroups)
  {
    if (!mg->allMembersInSameSection() || !m_impl->subGrouping) // group is in its own section
    {
      mg->addGroupedInheritedMembers(ol,this,lt,inheritedFrom,inheritId);
    }
  }
}
References m_impl, ClassDefImpl::IMPL::memberGroups, and ClassDefImpl::IMPL::subGrouping.
addGroupedInheritedMembers() [2/2]
virtual void ClassDefImpl::addGroupedInheritedMembers (OutputList & ol, MemberListType lt, const ClassDef * inheritedFrom, const QCString & inheritId) const [virtual]
Implements ClassDefMutable.
addInnerCompound() [1/2]
void ClassDefImpl::addInnerCompound (const Definition * d) [virtual]
Reimplemented from DefinitionMixin< ClassDefMutable >.
Definition at line 3958 of file classdef.cpp.
{
  //printf("**** %s::addInnerCompound(%s)\n",qPrint(name()),qPrint(d->name()));
  if (d->definitionType()==Definition::TypeClass) // only classes can be
                                                  // nested in classes.
  {
    m_impl->innerClasses.add(d->localName(),toClassDef(d));
  }
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::definitionType(), ClassDefImpl::IMPL::innerClasses, Definition::localName(), m_impl, toClassDef(), and Definition::TypeClass.
addInnerCompound() [2/2]
virtual void ClassDefImpl::addInnerCompound (const Definition * d) [virtual]
Reimplemented from DefinitionMixin< ClassDefMutable >.
addListReferences() [1/2]
void ClassDefImpl::addListReferences () [virtual]
Implements ClassDefMutable.
Definition at line 4144 of file classdef.cpp.
{
  SrcLangExt lang = getLanguage();
  if (!isLinkableInProject()) return;
  //printf("ClassDef(%s)::addListReferences()\n",qPrint(name()));
  {
    const RefItemVector &xrefItems = xrefListItems();
    addRefItem(xrefItems,
             qualifiedName(),
             lang==SrcLangExt_Fortran ? theTranslator->trType(TRUE,TRUE)
                                      : theTranslator->trClass(TRUE,TRUE),
             getOutputFileBase(),
             displayName(),
             QCString(),
             this
            );
  }
  for (const auto &mg : m_impl->memberGroups)
  {
    mg->addListReferences(this);
  }
  for (auto &ml : m_impl->memberLists)
  {
    if (ml->listType()&MemberListType_detailedLists)
    {
      ml->addListReferences(this);
    }
  }
}
References addRefItem(), displayName(), DefinitionMixin< ClassDefMutable >::getLanguage(), getOutputFileBase(), isLinkableInProject(), m_impl, ClassDefImpl::IMPL::memberGroups, ClassDefImpl::IMPL::memberLists, MemberListType_detailedLists, DefinitionMixin< ClassDefMutable >::qualifiedName(), SrcLangExt_Fortran, theTranslator, Translator::trClass(), Translator::trType(), TRUE, and DefinitionMixin< ClassDefMutable >::xrefListItems().
addListReferences() [2/2]
virtual void ClassDefImpl::addListReferences () [virtual]
Implements ClassDefMutable.
addMembersToMemberGroup() [1/2]
void ClassDefImpl::addMembersToMemberGroup () [virtual]
Implements ClassDefMutable.
Definition at line 826 of file classdef.cpp.
{
  for (auto &ml : m_impl->memberLists)
  {
    if ((ml->listType()&MemberListType_detailedLists)==0)
    {
      ::addMembersToMemberGroup(ml.get(),&m_impl->memberGroups,this);
    }
  }
  // add members inside sections to their groups
  for (const auto &mg : m_impl->memberGroups)
  {
    if (mg->allMembersInSameSection() && m_impl->subGrouping)
    {
      //printf("addToDeclarationSection(%s)\n",qPrint(mg->header()));
      mg->addToDeclarationSection();
    }
  }
}
References addMembersToMemberGroup(), m_impl, ClassDefImpl::IMPL::memberGroups, ClassDefImpl::IMPL::memberLists, MemberListType_detailedLists, and ClassDefImpl::IMPL::subGrouping.
Referenced by addMembersToMemberGroup().
addMembersToMemberGroup() [2/2]
virtual void ClassDefImpl::addMembersToMemberGroup () [virtual]
Implements ClassDefMutable.
addMembersToTemplateInstance() [1/2]
void ClassDefImpl::addMembersToTemplateInstance (const ClassDef * cd, const ArgumentList & templateArguments, const QCString & templSpec) [virtual]
Implements ClassDefMutable.
Definition at line 4041 of file classdef.cpp.
{
  //printf("%s::addMembersToTemplateInstance(%s,%s)\n",qPrint(name()),qPrint(cd->name()),templSpec);
  for (const auto &mni : cd->memberNameInfoLinkedMap())
  {
    for (const auto &mi : *mni)
    {
      auto actualArguments_p = stringToArgumentList(getLanguage(),templSpec);
      const MemberDef *md = mi->memberDef();
      std::unique_ptr<MemberDefMutable> imd { md->createTemplateInstanceMember(
                          templateArguments,actualArguments_p) };
      //printf("%s->setMemberClass(%p)\n",qPrint(imd->name()),this);
      imd->setMemberClass(this);
      imd->setTemplateMaster(md);
      imd->setDocumentation(md->documentation(),md->docFile(),md->docLine());
      imd->setBriefDescription(md->briefDescription(),md->briefFile(),md->briefLine());
      imd->setInbodyDocumentation(md->inbodyDocumentation(),md->inbodyFile(),md->inbodyLine());
      imd->setMemberSpecifiers(md->getMemberSpecifiers());
      imd->setMemberGroupId(md->getMemberGroupId());
      insertMember(imd.get());
      //printf("Adding member=%s %s%s to class %s templSpec %s\n",
      // imd->typeString(),qPrint(imd->name()),imd->argsString(),
      // qPrint(imd->getClassDef()->name()),templSpec);
      // insert imd in the list of all members
      //printf("Adding member=%s class=%s\n",qPrint(imd->name()),qPrint(name()));
      MemberName *mn = Doxygen::memberNameLinkedMap->add(imd->name());
      mn->push_back(std::move(imd));
    }
  }
  // also instantatie members for nested classes
  for (const auto &innerCd : cd->getClasses())
  {
    ClassDefMutable *ncd = toClassDefMutable(m_impl->innerClasses.find(innerCd->localName()));
    if (ncd)
    {
      ncd->addMembersToTemplateInstance(innerCd,cd->templateArguments(),templSpec);
    }
  }
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), ClassDefMutable::addMembersToTemplateInstance(), MemberDef::briefDescription(), Definition::briefFile(), Definition::briefLine(), MemberDef::createTemplateInstanceMember(), Definition::docFile(), Definition::docLine(), MemberDef::documentation(), LinkedRefMap< T, Hash, KeyEqual, Map >::find(), ClassDef::getClasses(), DefinitionMixin< ClassDefMutable >::getLanguage(), MemberDef::getMemberGroupId(), MemberDef::getMemberSpecifiers(), Definition::inbodyDocumentation(), Definition::inbodyFile(), Definition::inbodyLine(), ClassDefImpl::IMPL::innerClasses, insertMember(), m_impl, ClassDef::memberNameInfoLinkedMap(), Doxygen::memberNameLinkedMap, MemberName::push_back(), MemberDefMutable::setMemberClass(), stringToArgumentList(), templateArguments(), ClassDef::templateArguments(), and toClassDefMutable().
addMembersToTemplateInstance() [2/2]
virtual void ClassDefImpl::addMembersToTemplateInstance (const ClassDef * cd, const ArgumentList & templateArguments, const QCString & templSpec) [virtual]
Implements ClassDefMutable.
addMemberToList() [1/2]
void ClassDefImpl::addMemberToList (MemberListType lt, const MemberDef * md, bool isBrief) [private]
Definition at line 4216 of file classdef.cpp.
{
  bool sortBriefDocs = Config_getBool(SORT_BRIEF_DOCS);
  bool sortMemberDocs = Config_getBool(SORT_MEMBER_DOCS);
  const auto &ml = m_impl->memberLists.get(lt,MemberListContainer::Class);
  ml->setNeedsSorting((isBrief && sortBriefDocs) || (!isBrief && sortMemberDocs));
  ml->push_back(md);
  // for members in the declaration lists we set the section, needed for member grouping
  if ((ml->listType()&MemberListType_detailedLists)==0)
  {
    MemberDefMutable *mdm = toMemberDefMutable(md);
    if (mdm)
    {
      mdm->setSectionList(this,ml.get());
    }
  }
}
References Class, Config_getBool, MemberLists::get(), m_impl, ClassDefImpl::IMPL::memberLists, MemberListType_detailedLists, MemberDefMutable::setSectionList(), and toMemberDefMutable().
Referenced by internalInsertMember().
addMemberToList() [2/2]
void ClassDefImpl::addMemberToList (MemberListType lt, const MemberDef * md, bool isBrief) [private]
addTypeConstraint() [1/2]
void ClassDefImpl::addTypeConstraint (const QCString & typeConstraint, const QCString & type) [private]
Definition at line 3132 of file classdef.cpp.
{
  //printf("addTypeConstraint(%s,%s)\n",qPrint(type),qPrint(typeConstraint));
  bool hideUndocRelation = Config_getBool(HIDE_UNDOC_RELATIONS);
  if (typeConstraint.isEmpty() || type.isEmpty()) return;
  SymbolResolver resolver(getFileDef());
  ClassDefMutable *cd = resolver.resolveClassMutable(this,typeConstraint);
  if (cd==0 && !hideUndocRelation)
  {
    cd = toClassDefMutable(
           Doxygen::hiddenClassLinkedMap->add(typeConstraint,
             std::unique_ptr<ClassDef>(
               new ClassDefImpl(
                 getDefFileName(),getDefLine(),
                 getDefColumn(),
                 typeConstraint,
                 ClassDef::Class))));
    if (cd)
    {
      cd->setUsedOnly(TRUE);
      cd->setLanguage(getLanguage());
      //printf("Adding undocumented constraint '%s' to class %s on type %s\n",
      // qPrint(typeConstraint),qPrint(name()),qPrint(type));
    }
  }
  if (cd)
  {
    auto it = std::find_if(m_impl->constraintClassList.begin(),
                           m_impl->constraintClassList.end(),
                           [&cd](const auto &ccd) { return ccd.classDef==cd; });
    if (it==m_impl->constraintClassList.end())
    {
      m_impl->constraintClassList.emplace_back(cd);
      it = m_impl->constraintClassList.end()-1;
    }
    (*it).addAccessor(type);
    //printf("Adding constraint '%s' to class %s on type %s\n",
    // qPrint(typeConstraint),qPrint(name()),qPrint(type));
  }
}
References add(), ClassDef::Class, ClassDefImpl(), Config_getBool, ClassDefImpl::IMPL::constraintClassList, DefinitionMixin< ClassDefMutable >::getDefColumn(), DefinitionMixin< ClassDefMutable >::getDefFileName(), DefinitionMixin< ClassDefMutable >::getDefLine(), getFileDef(), DefinitionMixin< ClassDefMutable >::getLanguage(), Doxygen::hiddenClassLinkedMap, QCString::isEmpty(), m_impl, SymbolResolver::resolveClassMutable(), DefinitionMutable::setLanguage(), ClassDefMutable::setUsedOnly(), toClassDefMutable(), and TRUE.
Referenced by addTypeConstraints().
addTypeConstraint() [2/2]
void ClassDefImpl::addTypeConstraint (const QCString & typeConstraint, const QCString & type) [private]
addTypeConstraints() [1/2]
void ClassDefImpl::addTypeConstraints () [virtual]
Implements ClassDefMutable.
Definition at line 3175 of file classdef.cpp.
{
  for (const Argument &a : m_impl->tempArgs)
  {
    if (!a.typeConstraint.isEmpty())
    {
      QCString typeConstraint;
      int i=0,p=0;
      while ((i=a.typeConstraint.find('&',p))!=-1) // typeConstraint="A &I" for C<T extends A & I>
      {
        typeConstraint = a.typeConstraint.mid(p,i-p).stripWhiteSpace();
        addTypeConstraint(typeConstraint,a.type);
        p=i+1;
      }
      typeConstraint = a.typeConstraint.right(a.typeConstraint.length()-p).stripWhiteSpace();
      addTypeConstraint(typeConstraint,a.type);
    }
  }
}
References a, addTypeConstraint(), m_impl, p, and ClassDefImpl::IMPL::tempArgs.
addTypeConstraints() [2/2]
virtual void ClassDefImpl::addTypeConstraints () [virtual]
Implements ClassDefMutable.
addUsedByClass() [1/2]
void ClassDefImpl::addUsedByClass (ClassDef * cd, const QCString & accessName, Protection prot) [virtual]
Implements ClassDefMutable.
Definition at line 3817 of file classdef.cpp.
{
  bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
  bool umlLook = Config_getBool(UML_LOOK);
  if (prot==Private && !extractPrivate) return;
  //printf("%s::addUsedByClass(%s,%s)\n",qPrint(name()),qPrint(cd->name()),accessName);
  //
  auto it = std::find_if(m_impl->usedByImplClassList.begin(),
                         m_impl->usedByImplClassList.end(),
                         [&cd](const auto &ucd) { return ucd.classDef==cd; });
  if (it==m_impl->usedByImplClassList.end())
  {
     m_impl->usedByImplClassList.emplace_back(cd);
     //printf("Adding used by class %s to class %s\n",
     // qPrint(cd->name()),qPrint(name()));
     it = m_impl->usedByImplClassList.end()-1;
  }
  QCString acc = accessName;
  if (umlLook)
  {
    switch(prot)
    {
      case Public: acc.prepend("+"); break;
      case Private: acc.prepend("-"); break;
      case Protected: acc.prepend("#"); break;
      case Package: acc.prepend("~"); break;
    }
  }
  (*it).addAccessor(acc);
}
References Config_getBool, m_impl, Package, QCString::prepend(), Private, Protected, Public, and ClassDefImpl::IMPL::usedByImplClassList.
addUsedByClass() [2/2]
virtual void ClassDefImpl::addUsedByClass (ClassDef * cd, const QCString & accessName, Protection prot) [virtual]
Implements ClassDefMutable.
addUsedClass() [1/2]
void ClassDefImpl::addUsedClass (ClassDef * cd, const QCString & accessName, Protection prot) [virtual]
Implements ClassDefMutable.
Definition at line 3785 of file classdef.cpp.
{
  bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
  bool umlLook = Config_getBool(UML_LOOK);
  if (prot==Private && !extractPrivate) return;
  //printf("%s::addUsedClass(%s,%s)\n",qPrint(name()),qPrint(cd->name()),accessName);
  auto it = std::find_if(m_impl->usesImplClassList.begin(),
                         m_impl->usesImplClassList.end(),
                         [&cd](const auto &ucd) { return ucd.classDef==cd; });
  if (it==m_impl->usesImplClassList.end())
  {
    m_impl->usesImplClassList.emplace_back(cd);
    //printf("Adding used class %s to class %s via accessor %s\n",
    // qPrint(cd->name()),qPrint(name()),accessName);
    it = m_impl->usesImplClassList.end()-1;
  }
  QCString acc = accessName;
  if (umlLook)
  {
    switch(prot)
    {
      case Public: acc.prepend("+"); break;
      case Private: acc.prepend("-"); break;
      case Protected: acc.prepend("#"); break;
      case Package: acc.prepend("~"); break;
    }
  }
  (*it).addAccessor(acc);
}
References Config_getBool, m_impl, Package, QCString::prepend(), Private, Protected, Public, and ClassDefImpl::IMPL::usesImplClassList.
addUsedClass() [2/2]
virtual void ClassDefImpl::addUsedClass (ClassDef * cd, const QCString & accessName, Protection prot) [virtual]
Implements ClassDefMutable.
addUsedInterfaceClasses() [1/2]
void ClassDefImpl::addUsedInterfaceClasses (MemberDef * md, const QCString & typeStr) [private]
addUsedInterfaceClasses() [2/2]
void ClassDefImpl::addUsedInterfaceClasses (MemberDef * md, const QCString & typeStr) [private]
anchor() [1/2]
QCString ClassDefImpl::anchor () const [virtual]
Returns the anchor within a page where this item can be found
Implements ClassDef.
Definition at line 4814 of file classdef.cpp.
{
  QCString anc;
  if (isEmbeddedInOuterScope() && !Doxygen::generatingXmlOutput)
  {
    if (m_impl->templateMaster)
    {
      // point to the template of which this class is an instance
      anc = m_impl->templateMaster->getOutputFileBase();
    }
    else
    {
      anc = m_impl->fileName;
    }
  }
  return anc;
}
References ClassDefImpl::IMPL::fileName, Doxygen::generatingXmlOutput, ClassDef::getOutputFileBase(), isEmbeddedInOuterScope(), m_impl, and ClassDefImpl::IMPL::templateMaster.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), addExample(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), doxmlparser.compound.docTocItemType::set_anchor(), writeBriefDescription(), writeDeclarationLink(), writeDetailedDescription(), writeInlineDocumentation(), writeMemberList(), writeMoreLink(), and writeTagFile().
anchor() [2/2]
virtual QCString ClassDefImpl::anchor () const [virtual]
Returns the anchor within a page where this item can be found
Implements ClassDef.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
baseClasses() [1/2]
const BaseClassList & ClassDefImpl::baseClasses () const [virtual]
Returns the list of base classes from which this class directly inherits.
Implements ClassDef.
Definition at line 4589 of file classdef.cpp.
{
  return m_impl->inherits;
}
References ClassDefImpl::IMPL::inherits, and m_impl.
Referenced by isBaseClass(), and mergeMembers().
baseClasses() [2/2]
virtual const BaseClassList & ClassDefImpl::baseClasses () const [virtual]
Returns the list of base classes from which this class directly inherits.
Implements ClassDef.
categoryOf() [1/2]
ClassDef * ClassDefImpl::categoryOf () const [virtual]
Returns the class of which this is a category (Objective-C only)
Implements ClassDef.
Definition at line 4729 of file classdef.cpp.
{
  return m_impl->categoryOf;
}
References ClassDefImpl::IMPL::categoryOf, and m_impl.
categoryOf() [2/2]
virtual ClassDef * ClassDefImpl::categoryOf () const [virtual]
Returns the class of which this is a category (Objective-C only)
Implements ClassDef.
className() [1/2]
QCString ClassDefImpl::className () const [virtual]
Returns the name of the class including outer classes, but not including namespaces.
Implements ClassDef.
Definition at line 4127 of file classdef.cpp.
{
  if (m_impl->className.isEmpty())
  {
    return localName();
  }
  else
  {
    return m_impl->className;
  }
}
References ClassDefImpl::IMPL::className, QCString::isEmpty(), DefinitionMixin< ClassDefMutable >::localName(), and m_impl.
className() [2/2]
virtual QCString ClassDefImpl::className () const [virtual]
Returns the name of the class including outer classes, but not including namespaces.
Implements ClassDef.
codeSymbolType() [1/2]
CodeSymbolType ClassDefImpl::codeSymbolType () const [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 4944 of file classdef.cpp.
{
  switch (compoundType())
  {
    case Class: return CodeSymbolType::Class; break;
    case Struct: return CodeSymbolType::Struct; break;
    case Union: return CodeSymbolType::Union; break;
    case Interface: return CodeSymbolType::Interface; break;
    case Protocol: return CodeSymbolType::Protocol; break;
    case Category: return CodeSymbolType::Category; break;
    case Exception: return CodeSymbolType::Exception; break;
    case Service: return CodeSymbolType::Service; break;
    case Singleton: return CodeSymbolType::Singleton; break;
  }
  return CodeSymbolType::Class;
}
References ClassDef::Category, Category, ClassDef::Class, Class, compoundType(), ClassDef::Exception, Exception, ClassDef::Interface, Interface, ClassDef::Protocol, Protocol, ClassDef::Service, Service, ClassDef::Singleton, Singleton, ClassDef::Struct, Struct, ClassDef::Union, and Union.
codeSymbolType() [2/2]
virtual CodeSymbolType ClassDefImpl::codeSymbolType () const [virtual]
Used for syntax highlighting symbol class
Implements Definition.
collaborationGraphFileName() [1/2]
QCString ClassDefImpl::collaborationGraphFileName () const [virtual]
returns the file name to use for the collaboration graph
Implements ClassDef.
Definition at line 4934 of file classdef.cpp.
{
  return m_impl->collabFileName;
}
References ClassDefImpl::IMPL::collabFileName, and m_impl.
collaborationGraphFileName() [2/2]
virtual QCString ClassDefImpl::collaborationGraphFileName () const [virtual]
returns the file name to use for the collaboration graph
Implements ClassDef.
compoundType() [1/2]
ClassDefImpl::CompoundType ClassDefImpl::compoundType () const [virtual]
Returns the type of compound this is, i.e. class/struct/union/..
Implements ClassDef.
Definition at line 4584 of file classdef.cpp.
{
  return m_impl->compType;
}
References ClassDefImpl::IMPL::compType, and m_impl.
Referenced by codeSymbolType(), writeDeclarationLink(), writeDocumentation(), and writeMemberList().
compoundType() [2/2]
virtual CompoundType ClassDefImpl::compoundType () const [virtual]
Returns the type of compound this is, i.e. class/struct/union/..
Implements ClassDef.
compoundTypeString() [1/2]
QCString ClassDefImpl::compoundTypeString () const [virtual]
Returns the type of compound as a string
Implements ClassDef.
Definition at line 3850 of file classdef.cpp.
{
  if (getLanguage()==SrcLangExt_Fortran)
  {
    switch (m_impl->compType)
    {
      case Class: return "module";
      case Struct: return "type";
      case Union: return "union";
      case Interface: return "interface";
      case Protocol: return "protocol";
      case Category: return "category";
      case Exception: return "exception";
      default: return "unknown";
    }
  }
  else
  {
    switch (m_impl->compType)
    {
      case Class: return isJavaEnum() ? "enum" : "class";
      case Struct: return "struct";
      case Union: return "union";
      case Interface: return getLanguage()==SrcLangExt_ObjC ? "class" : "interface";
      case Protocol: return "protocol";
      case Category: return "category";
      case Exception: return "exception";
      case Service: return "service";
      case Singleton: return "singleton";
      default: return "unknown";
    }
  }
}
References ClassDef::Category, ClassDef::Class, ClassDefImpl::IMPL::compType, ClassDef::Exception, DefinitionMixin< ClassDefMutable >::getLanguage(), ClassDef::Interface, isJavaEnum(), m_impl, ClassDef::Protocol, ClassDef::Service, ClassDef::Singleton, SrcLangExt_Fortran, SrcLangExt_ObjC, ClassDef::Struct, and ClassDef::Union.
Referenced by ClassDefImpl(), writeDeclaration(), writeDeclarationLink(), writeDetailedDocumentationBody(), writeDocumentationContents(), writeInlineDocumentation(), and writeTagFile().
compoundTypeString() [2/2]
virtual QCString ClassDefImpl::compoundTypeString () const [virtual]
Returns the type of compound as a string
Implements ClassDef.
computeAnchors() [1/2]
void ClassDefImpl::computeAnchors () [virtual]
Implements ClassDefMutable.
Definition at line 1144 of file classdef.cpp.
{
  for (auto &ml : m_impl->memberLists)
  {
    if ((ml->listType()&MemberListType_detailedLists)==0)
    {
      ml->setAnchors();
    }
  }
  for (const auto &mg : m_impl->memberGroups)
  {
    mg->setAnchors();
  }
}
References m_impl, ClassDefImpl::IMPL::memberGroups, ClassDefImpl::IMPL::memberLists, and MemberListType_detailedLists.
computeAnchors() [2/2]
virtual void ClassDefImpl::computeAnchors () [virtual]
Implements ClassDefMutable.
countAdditionalInheritedMembers() [1/2]
int ClassDefImpl::countAdditionalInheritedMembers () const [private]
Definition at line 4384 of file classdef.cpp.
{
  int totalCount=0;
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd && lmd->type!=MemberListType_friends) // friendship is not inherited
      {
        ClassDefSet visited;
        totalCount+=countInheritedDecMembers(lmd->type,this,TRUE,FALSE,visited);
      }
    }
  }
  //printf("countAdditionalInheritedMembers()=%d\n",totalCount);
  return totalCount;
}
References LayoutDocManager::Class, countInheritedDecMembers(), FALSE, LayoutDocManager::instance(), LayoutDocEntry::MemberDecl, MemberListType_friends, TRUE, and LayoutDocEntryMemberDecl::type.
Referenced by endMemberDeclarations().
countAdditionalInheritedMembers() [2/2]
int ClassDefImpl::countAdditionalInheritedMembers () const [private]
countInheritanceNodes() [1/2]
int ClassDefImpl::countInheritanceNodes () const [virtual]
Implements ClassDef.
Definition at line 1589 of file classdef.cpp.
{
  int count=0;
  for (const auto &ibcd : m_impl->inheritedBy)
  {
    const ClassDef *icd=ibcd.classDef;
    if (icd->isVisibleInHierarchy()) count++;
  }
  for (const auto &ibcd : m_impl->inherits)
  {
    const ClassDef *icd=ibcd.classDef;
    if (icd->isVisibleInHierarchy()) count++;
  }
  return count;
}
References ClassDefImpl::IMPL::inheritedBy, ClassDefImpl::IMPL::inherits, ClassDef::isVisibleInHierarchy(), and m_impl.
Referenced by writeInheritanceGraph().
countInheritanceNodes() [2/2]
virtual int ClassDefImpl::countInheritanceNodes () const [virtual]
Implements ClassDef.
countInheritedDecMembers() [1/2]
int ClassDefImpl::countInheritedDecMembers (MemberListType lt, const ClassDef * inheritedFrom, bool invert, bool showAlways, ClassDefSet & visitedClasses) const [private]
Definition at line 4329 of file classdef.cpp.
{
  int inhCount = 0;
  int count = countMembersIncludingGrouped(lt,inheritedFrom,FALSE);
  bool process = count>0;
  //printf("%s: countInheritedDecMembers: lt=%d process=%d count=%d invert=%d\n",
  // qPrint(name()),lt,process,count,invert);
  if ((process^invert) || showAlways)
  {
    for (const auto &ibcd : m_impl->inherits)
    {
      ClassDefMutable *icd=toClassDefMutable(ibcd.classDef);
      int lt1,lt2;
      if (icd && icd->isLinkable())
      {
        convertProtectionLevel(lt,ibcd.prot,&lt1,&lt2);
        //printf("%s: convert %d->(%d,%d) prot=%d\n",
        // qPrint(icd->name()),lt,lt1,lt2,ibcd->prot);
        if (visitedClasses.find(icd)==visitedClasses.end())
        {
          visitedClasses.insert(icd); // guard for multiple virtual inheritance
          if (lt1!=-1)
          {
            inhCount+=icd->countMemberDeclarations(static_cast<MemberListType>(lt1),inheritedFrom,lt2,FALSE,TRUE,visitedClasses);
          }
        }
      }
    }
  }
  return inhCount;
}
References convertProtectionLevel(), ClassDef::countMemberDeclarations(), countMembersIncludingGrouped(), FALSE, ClassDefImpl::IMPL::inherits, ClassDef::isLinkable(), m_impl, search::process(), toClassDefMutable(), and TRUE.
Referenced by countAdditionalInheritedMembers(), and countMemberDeclarations().
countInheritedDecMembers() [2/2]
int ClassDefImpl::countInheritedDecMembers (MemberListType lt, const ClassDef * inheritedFrom, bool invert, bool showAlways, ClassDefSet & visitedClasses) const [private]
countMemberDeclarations() [1/2]
int ClassDefImpl::countMemberDeclarations (MemberListType lt, const ClassDef * inheritedFrom, int lt2, bool invert, bool showAlways, ClassDefSet & visitedClasses) const [virtual]
Implements ClassDef.
Definition at line 4251 of file classdef.cpp.
{
  //printf("%s: countMemberDeclarations for %d and %d\n",qPrint(name()),lt,lt2);
  int count=0;
  MemberList * ml = getMemberList(lt);
  MemberList * ml2 = getMemberList(static_cast<MemberListType>(lt2));
  if (getLanguage()!=SrcLangExt_VHDL) // use specific declarations function
  {
    if (ml)
    {
      count+=ml->numDecMembers();
      //printf("-> ml=%d\n",ml->numDecMembers());
    }
    if (ml2)
    {
      count+=ml2->numDecMembers();
      //printf("-> ml2=%d\n",ml2->numDecMembers());
    }
    // also include grouped members that have their own section in the class (see bug 722759)
    if (inheritedFrom)
    {
      for (const auto &mg : m_impl->memberGroups)
      {
        count+=mg->countGroupedInheritedMembers(lt);
        if (lt2!=-1) count+=mg->countGroupedInheritedMembers(static_cast<MemberListType>(lt2));
      }
    }
    bool inlineInheritedMembers = Config_getBool(INLINE_INHERITED_MEMB);
    if (!inlineInheritedMembers) // show inherited members as separate lists
    {
      count+=countInheritedDecMembers(lt,inheritedFrom,invert,showAlways,visitedClasses);
    }
  }
  //printf("-> %d\n",count);
  return count;
}
References Config_getBool, countInheritedDecMembers(), DefinitionMixin< ClassDefMutable >::getLanguage(), getMemberList(), m_impl, ClassDefImpl::IMPL::memberGroups, MemberList::numDecMembers(), and SrcLangExt_VHDL.
countMemberDeclarations() [2/2]
virtual int ClassDefImpl::countMemberDeclarations (MemberListType lt, const ClassDef * inheritedFrom, int lt2, bool invert, bool showAlways, ClassDefSet & visitedClasses) const [virtual]
Implements ClassDef.
countMembers() [1/2]
void ClassDefImpl::countMembers () [virtual]
Implements ClassDefMutable.
Definition at line 4315 of file classdef.cpp.
{
  for (auto &ml : m_impl->memberLists)
  {
    ml->countDecMembers();
    ml->countDocMembers();
  }
  for (const auto &mg : m_impl->memberGroups)
  {
    mg->countDecMembers();
    mg->countDocMembers();
  }
}
References m_impl, ClassDefImpl::IMPL::memberGroups, and ClassDefImpl::IMPL::memberLists.
countMembers() [2/2]
virtual void ClassDefImpl::countMembers () [virtual]
Implements ClassDefMutable.
countMembersIncludingGrouped() [1/2]
int ClassDefImpl::countMembersIncludingGrouped (MemberListType lt, const ClassDef * inheritedFrom, bool additional) const [virtual]
Implements ClassDef.
Definition at line 4420 of file classdef.cpp.
{
  int count=0;
  MemberList *ml = getMemberList(lt);
  if (ml)
  {
    count=ml->countInheritableMembers(inheritedFrom);
  }
  //printf("%s:countMembersIncludingGrouped: count=%d\n",qPrint(name()),count);
  for (const auto &mg : m_impl->memberGroups)
  {
    bool hasOwnSection = !mg->allMembersInSameSection() ||
                         !m_impl->subGrouping; // group is in its own section
    if ((additional && hasOwnSection) || (!additional && !hasOwnSection))
    {
      count+=mg->countGroupedInheritedMembers(lt);
    }
  }
  //printf("%s:countMembersIncludingGrouped(lt=%d,%s)=%d\n",
  // qPrint(name()),lt,ml?qPrint(ml->listTypeAsString(ml->listType())):"<none>",count);
  return count;
}
References MemberList::countInheritableMembers(), getMemberList(), m_impl, ClassDefImpl::IMPL::memberGroups, and ClassDefImpl::IMPL::subGrouping.
Referenced by countInheritedDecMembers(), and writeInheritedMemberDeclarations().
countMembersIncludingGrouped() [2/2]
virtual int ClassDefImpl::countMembersIncludingGrouped (MemberListType lt, const ClassDef * inheritedFrom, bool additional) const [virtual]
Implements ClassDef.
definitionType() [1/2]
virtual DefType ClassDefImpl::definitionType () const [inline], [virtual]
Used for RTTI, this is a class
Implements ClassDef.
Definition at line 161 of file classdef.cpp.
{ return TypeClass; }
References Definition::TypeClass.
definitionType() [2/2]
virtual DefType ClassDefImpl::definitionType () const [inline], [virtual]
Used for RTTI, this is a class
Implements ClassDef.
Definition at line 161 of file classdef.cpp.
{ return TypeClass; }
References Definition::TypeClass.
displayName() [1/2]
QCString ClassDefImpl::displayName (bool includeScope = TRUE) const [virtual]
Returns the name as it is appears in the documentation
Implements ClassDef.
Definition at line 801 of file classdef.cpp.
{
  return makeDisplayName(this,includeScope);
}
References makeDisplayName().
Referenced by addListReferences(), title(), writeCollaborationGraph(), writeDeclaration(), writeDeclarationLink(), writeDocumentation(), writeInheritanceGraph(), writeMemberDocumentation(), writeMemberList(), and writeMemberPages().
displayName() [2/2]
virtual QCString ClassDefImpl::displayName (bool includeScope = TRUE) const [virtual]
Returns the name as it is appears in the documentation
Implements ClassDef.
distributeMemberGroupDocumentation() [1/2]
void ClassDefImpl::distributeMemberGroupDocumentation () [virtual]
Implements ClassDefMutable.
Definition at line 1160 of file classdef.cpp.
{
  for (const auto &mg : m_impl->memberGroups)
  {
    mg->distributeMemberGroupDocumentation();
  }
}
References m_impl, and ClassDefImpl::IMPL::memberGroups.
distributeMemberGroupDocumentation() [2/2]
virtual void ClassDefImpl::distributeMemberGroupDocumentation () [virtual]
Implements ClassDefMutable.
endMemberDeclarations() [1/2]
void ClassDefImpl::endMemberDeclarations (OutputList & ol) const [private]
Definition at line 1995 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::endMemberDeclarations()\n",qPrint(name()));
  bool inlineInheritedMembers = Config_getBool(INLINE_INHERITED_MEMB);
  if (!inlineInheritedMembers && countAdditionalInheritedMembers()>0)
  {
    ol.startMemberHeader("inherited");
    ol.parseText(theTranslator->trAdditionalInheritedMembers());
    ol.endMemberHeader();
    writeAdditionalInheritedMembers(ol);
  }
  ol.endMemberSections();
}
References Config_getBool, countAdditionalInheritedMembers(), OutputList::endMemberHeader(), OutputList::endMemberSections(), OutputList::parseText(), OutputList::startMemberHeader(), theTranslator, Translator::trAdditionalInheritedMembers(), and writeAdditionalInheritedMembers().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
endMemberDeclarations() [2/2]
void ClassDefImpl::endMemberDeclarations (OutputList & ol) const [private]
endMemberDocumentation() [1/2]
void ClassDefImpl::endMemberDocumentation (OutputList & ol) const [private]
Definition at line 1979 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::endMemberDocumentation()\n",qPrint(name()));
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.enable(OutputGenerator::Html);
    Doxygen::suppressDocWarnings = FALSE;
  }
}
References Config_getBool, OutputList::enable(), FALSE, OutputGenerator::Html, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
endMemberDocumentation() [2/2]
void ClassDefImpl::endMemberDocumentation (OutputList & ol) const [private]
findInnerCompound() [1/2]
const Definition * ClassDefImpl::findInnerCompound (const QCString & name) const [virtual]
Returns the definition of a nested compound if available, or 0 otherwise.
Parameters
name The name of the nested compound
Reimplemented from DefinitionMixin< ClassDefMutable >.
Definition at line 3968 of file classdef.cpp.
{
  return m_impl->innerClasses.find(name);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), ClassDefImpl::IMPL::innerClasses, m_impl, and DefinitionMixin< ClassDefMutable >::name().
findInnerCompound() [2/2]
virtual const Definition * ClassDefImpl::findInnerCompound (const QCString & name) const [virtual]
Returns the definition of a nested compound if available, or 0 otherwise.
Parameters
name The name of the nested compound
Reimplemented from DefinitionMixin< ClassDefMutable >.
findSectionsInDocumentation() [1/2]
void ClassDefImpl::findSectionsInDocumentation () [virtual]
Implements ClassDefMutable.
Definition at line 1168 of file classdef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
  for (const auto &mg : m_impl->memberGroups)
  {
    mg->findSectionsInDocumentation(this);
  }
  for (auto &ml : m_impl->memberLists)
  {
    if ((ml->listType()&MemberListType_detailedLists)==0)
    {
      ml->findSectionsInDocumentation(this);
    }
  }
}
References DefinitionMixin< ClassDefMutable >::briefDescription(), DefinitionMixin< ClassDefMutable >::docFile(), docFindSections(), DefinitionMixin< ClassDefMutable >::documentation(), m_impl, ClassDefImpl::IMPL::memberGroups, ClassDefImpl::IMPL::memberLists, and MemberListType_detailedLists.
findSectionsInDocumentation() [2/2]
virtual void ClassDefImpl::findSectionsInDocumentation () [virtual]
Implements ClassDefMutable.
generatedFromFiles() [1/2]
QCString ClassDefImpl::generatedFromFiles () const [virtual]
Implements ClassDef.
Definition at line 1481 of file classdef.cpp.
{
  QCString result;
  SrcLangExt lang = getLanguage();
  size_t numFiles = m_impl->files.size();
  if (lang==SrcLangExt_Fortran)
  {
    result = theTranslator->trGeneratedFromFilesFortran(
          getLanguage()==SrcLangExt_ObjC && m_impl->compType==Interface ? Class : m_impl->compType,
          numFiles==1);
  }
  else if (isJavaEnum())
  {
    result = theTranslator->trEnumGeneratedFromFiles(numFiles==1);
  }
  else if (m_impl->compType==Service)
  {
    result = theTranslator->trServiceGeneratedFromFiles(numFiles==1);
  }
  else if (m_impl->compType==Singleton)
  {
    result = theTranslator->trSingletonGeneratedFromFiles(numFiles==1);
  }
  else
  {
    result = theTranslator->trGeneratedFromFiles(
          getLanguage()==SrcLangExt_ObjC && m_impl->compType==Interface ? Class : m_impl->compType,
          numFiles==1);
  }
  return result;
}
References ClassDefImpl::IMPL::compType, ClassDefImpl::IMPL::files, DefinitionMixin< ClassDefMutable >::getLanguage(), isJavaEnum(), m_impl, ClassDef::Service, ClassDef::Singleton, SrcLangExt_Fortran, SrcLangExt_ObjC, theTranslator, Translator::trEnumGeneratedFromFiles(), Translator::trGeneratedFromFiles(), Translator::trGeneratedFromFilesFortran(), Translator::trServiceGeneratedFromFiles(), and Translator::trSingletonGeneratedFromFiles().
Referenced by showUsedFiles().
generatedFromFiles() [2/2]
virtual QCString ClassDefImpl::generatedFromFiles () const [virtual]
Implements ClassDef.
getClasses() [1/2]
ClassLinkedRefMap ClassDefImpl::getClasses () const [virtual]
returns the classes nested into this class
Implements ClassDef.
Definition at line 4579 of file classdef.cpp.
{
  return m_impl->innerClasses;
}
References ClassDefImpl::IMPL::innerClasses, and m_impl.
getClasses() [2/2]
virtual ClassLinkedRefMap ClassDefImpl::getClasses () const [virtual]
returns the classes nested into this class
Implements ClassDef.
getExamples() [1/2]
const ExampleList & ClassDefImpl::getExamples () const [virtual]
Implements ClassDef.
Definition at line 4909 of file classdef.cpp.
{
  return m_impl->examples;
}
References ClassDefImpl::IMPL::examples, and m_impl.
getExamples() [2/2]
virtual const ExampleList & ClassDefImpl::getExamples () const [virtual]
Implements ClassDef.
getFileDef() [1/2]
FileDef * ClassDefImpl::getFileDef () const [virtual]
Returns the namespace this compound is in, or 0 if it has a global scope. Returns the file in which this compound's definition can be found. Should not return 0 (but it might be a good idea to check anyway).
Implements ClassDef.
Definition at line 4639 of file classdef.cpp.
{
  return m_impl->fileDef;
}
References ClassDefImpl::IMPL::fileDef, and m_impl.
Referenced by addTypeConstraint(), getOutputFileBase(), isEmbeddedInOuterScope(), and writeTemplateSpec().
getFileDef() [2/2]
virtual FileDef * ClassDefImpl::getFileDef () const [virtual]
Returns the namespace this compound is in, or 0 if it has a global scope. Returns the file in which this compound's definition can be found. Should not return 0 (but it might be a good idea to check anyway).
Implements ClassDef.
getInstanceOutputFileBase() [1/2]
QCString ClassDefImpl::getInstanceOutputFileBase () const [virtual]
Implements ClassDef.
Definition at line 3921 of file classdef.cpp.
{
  return m_impl->fileName;
}
References ClassDefImpl::IMPL::fileName, and m_impl.
getInstanceOutputFileBase() [2/2]
virtual QCString ClassDefImpl::getInstanceOutputFileBase () const [virtual]
Implements ClassDef.
getMemberByName() [1/2]
const MemberDef * ClassDefImpl::getMemberByName (const QCString &) const [virtual]
Returns the member with the given name
Implements ClassDef.
Definition at line 4174 of file classdef.cpp.
{
  const MemberDef *xmd = 0;
  MemberNameInfo *mni = m_impl->allMemberNameInfoLinkedMap.find(name);
  if (mni)
  {
    const int maxInheritanceDepth = 100000;
    int mdist=maxInheritanceDepth;
    for (auto &mi : *mni)
    {
      const ClassDef *mcd=mi->memberDef()->getClassDef();
      int m=minClassDistance(this,mcd);
      //printf("found member in %s linkable=%d m=%d\n",
      // qPrint(mcd->name()),mcd->isLinkable(),m);
      if (m<mdist && mcd->isLinkable())
      {
        mdist=m;
        xmd=mi->memberDef();
      }
    }
  }
  //printf("getMemberByName(%s)=%p\n",qPrint(name),xmd);
  return xmd;
}
References ClassDefImpl::IMPL::allMemberNameInfoLinkedMap, LinkedMap< T, Hash, KeyEqual, Map >::find(), isLinkable(), m_impl, maxInheritanceDepth, minClassDistance(), and DefinitionMixin< ClassDefMutable >::name().
getMemberByName() [2/2]
virtual const MemberDef * ClassDefImpl::getMemberByName (const QCString &) const [virtual]
Returns the member with the given name
Implements ClassDef.
getMemberGroups() [1/2]
const MemberGroupList & ClassDefImpl::getMemberGroups () const [virtual]
Returns the member groups defined for this class
Implements ClassDef.
Definition at line 4739 of file classdef.cpp.
{
  return m_impl->memberGroups;
}
References m_impl, and ClassDefImpl::IMPL::memberGroups.
getMemberGroups() [2/2]
virtual const MemberGroupList & ClassDefImpl::getMemberGroups () const [virtual]
Returns the member groups defined for this class
Implements ClassDef.
getMemberList() [1/2]
MemberList * ClassDefImpl::getMemberList (MemberListType lt) const [virtual]
Returns the members in the list identified by lt
Implements ClassDef.
Definition at line 4204 of file classdef.cpp.
{
  for (auto &ml : m_impl->memberLists)
  {
    if (ml->listType()==lt)
    {
      return ml.get();
    }
  }
  return 0;
}
References m_impl, and ClassDefImpl::IMPL::memberLists.
Referenced by countMemberDeclarations(), countMembersIncludingGrouped(), setAnonymousEnumType(), writeMemberDeclarations(), writeMemberDocumentation(), writePlainMemberDeclaration(), writeSimpleMemberDocumentation(), writeSummaryLinks(), and writeTagFile().
getMemberList() [2/2]
virtual MemberList * ClassDefImpl::getMemberList (MemberListType lt) const [virtual]
Returns the members in the list identified by lt
Implements ClassDef.
getMemberListFileName() [1/2]
QCString ClassDefImpl::getMemberListFileName () const [virtual]
Implements ClassDef.
Definition at line 796 of file classdef.cpp.
{
  return m_impl->memberListFileName;
}
References m_impl, and ClassDefImpl::IMPL::memberListFileName.
Referenced by writeMemberList(), and writeSummaryLinks().
getMemberListFileName() [2/2]
virtual QCString ClassDefImpl::getMemberListFileName () const [virtual]
Implements ClassDef.
getMemberLists() [1/2]
const MemberLists & ClassDefImpl::getMemberLists () const [virtual]
Returns the list containing the list of members sorted per type
Implements ClassDef.
Definition at line 4734 of file classdef.cpp.
{
  return m_impl->memberLists;
}
References m_impl, and ClassDefImpl::IMPL::memberLists.
getMemberLists() [2/2]
virtual const MemberLists & ClassDefImpl::getMemberLists () const [virtual]
Returns the list containing the list of members sorted per type
Implements ClassDef.
getOutputFileBase() [1/2]
QCString ClassDefImpl::getOutputFileBase () const [virtual]
Returns the unique base name (without extension) of the class's file on disk
Implements ClassDef.
Definition at line 3884 of file classdef.cpp.
{
  bool inlineGroupedClasses = Config_getBool(INLINE_GROUPED_CLASSES);
  bool inlineSimpleClasses = Config_getBool(INLINE_SIMPLE_STRUCTS);
  if (!Doxygen::generatingXmlOutput)
  {
    Definition *scope=0;
    if (inlineGroupedClasses && !partOfGroups().empty())
    {
      // point to the group that embeds this class
      return partOfGroups().front()->getOutputFileBase();
    }
    else if (inlineSimpleClasses && m_impl->isSimple && !partOfGroups().empty())
    {
      // point to simple struct inside a group
      return partOfGroups().front()->getOutputFileBase();
    }
    else if (inlineSimpleClasses && m_impl->isSimple && (scope=getOuterScope()))
    {
      if (scope==Doxygen::globalScope && getFileDef() && getFileDef()->isLinkableInProject()) // simple struct embedded in file
      {
        return getFileDef()->getOutputFileBase();
      }
      else if (scope->isLinkableInProject()) // simple struct embedded in other container (namespace/group/class)
      {
        return getOuterScope()->getOutputFileBase();
      }
    }
  }
  if (m_impl->templateMaster)
  {
    // point to the template of which this class is an instance
    return m_impl->templateMaster->getOutputFileBase();
  }
  return m_impl->fileName;
}
References Config_getBool, ClassDefImpl::IMPL::fileName, Doxygen::generatingXmlOutput, getFileDef(), DefinitionMixin< ClassDefMutable >::getOuterScope(), ClassDef::getOutputFileBase(), Definition::getOutputFileBase(), FileDef::getOutputFileBase(), Doxygen::globalScope, isLinkableInProject(), Definition::isLinkableInProject(), ClassDefImpl::IMPL::isSimple, m_impl, DefinitionMixin< ClassDefMutable >::partOfGroups(), and ClassDefImpl::IMPL::templateMaster.
Referenced by addListReferences(), writeDeclarationLink(), writeDetailedDescription(), writeDocumentation(), writeInheritanceGraph(), writeInlineDocumentation(), writeMemberList(), writeMoreLink(), and writeTagFile().
getOutputFileBase() [2/2]
virtual QCString ClassDefImpl::getOutputFileBase () const [virtual]
Returns the unique base name (without extension) of the class's file on disk
Implements ClassDef.
getReference() [1/2]
QCString ClassDefImpl::getReference () const [virtual]
If this class originated from a tagfile, this will return the tag file reference
Reimplemented from DefinitionMixin< ClassDefMutable >.
Definition at line 4081 of file classdef.cpp.
{
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->getReference();
  }
  else
  {
    return DefinitionMixin::getReference();
  }
}
References DefinitionMixin< Base >::getReference(), ClassDef::getReference(), m_impl, and ClassDefImpl::IMPL::templateMaster.
Referenced by writeDeclarationLink(), and writeMemberList().
getReference() [2/2]
virtual QCString ClassDefImpl::getReference () const [virtual]
If this class originated from a tagfile, this will return the tag file reference
Reimplemented from DefinitionMixin< ClassDefMutable >.
getSourceFileBase() [1/2]
QCString ClassDefImpl::getSourceFileBase () const [virtual]
Returns the base name for the source code file
Reimplemented from DefinitionMixin< ClassDefMutable >.
Definition at line 3926 of file classdef.cpp.
{
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->getSourceFileBase();
  }
  else
  {
    return DefinitionMixin::getSourceFileBase();
  }
}
References DefinitionMixin< Base >::getSourceFileBase(), ClassDef::getSourceFileBase(), m_impl, and ClassDefImpl::IMPL::templateMaster.
getSourceFileBase() [2/2]
virtual QCString ClassDefImpl::getSourceFileBase () const [virtual]
Returns the base name for the source code file
Reimplemented from DefinitionMixin< ClassDefMutable >.
getTemplateBaseClassNames() [1/2]
const TemplateNameMap & ClassDefImpl::getTemplateBaseClassNames () const [virtual]
Implements ClassDef.
Definition at line 4036 of file classdef.cpp.
{
  return m_impl->templBaseClassNames;
}
References m_impl, and ClassDefImpl::IMPL::templBaseClassNames.
getTemplateBaseClassNames() [2/2]
virtual const TemplateNameMap & ClassDefImpl::getTemplateBaseClassNames () const [virtual]
Implements ClassDef.
getTemplateInstances() [1/2]
const TemplateInstanceList & ClassDefImpl::getTemplateInstances () const [virtual]
Returns a sorted dictionary with all template instances found for this template class. Returns 0 if not a template or no instances.
Implements ClassDef.
Definition at line 4644 of file classdef.cpp.
{
  return m_impl->templateInstances;
}
References m_impl, and ClassDefImpl::IMPL::templateInstances.
getTemplateInstances() [2/2]
virtual const TemplateInstanceList & ClassDefImpl::getTemplateInstances () const [virtual]
Returns a sorted dictionary with all template instances found for this template class. Returns 0 if not a template or no instances.
Implements ClassDef.
getTemplateParameterLists() [1/2]
ArgumentLists ClassDefImpl::getTemplateParameterLists () const [virtual]
Returns the template parameter lists that form the template declaration of this class.
Example: template<class T> class TC {} = 0; will return a list with one ArgumentList containing one argument with type=`class` and name=`T`.
Implements ClassDef.
Definition at line 4105 of file classdef.cpp.
{
  ArgumentLists result;
  Definition *d=getOuterScope();
  while (d && d->definitionType()==Definition::TypeClass)
  {
    result.insert(result.begin(),toClassDef(d)->templateArguments());
    d = d->getOuterScope();
  }
  if (!templateArguments().empty())
  {
    result.push_back(templateArguments());
  }
  return result;
}
References Definition::definitionType(), DefinitionMixin< ClassDefMutable >::getOuterScope(), Definition::getOuterScope(), templateArguments(), toClassDef(), and Definition::TypeClass.
getTemplateParameterLists() [2/2]
virtual ArgumentLists ClassDefImpl::getTemplateParameterLists () const [virtual]
Returns the template parameter lists that form the template declaration of this class.
Example: template<class T> class TC {} = 0; will return a list with one ArgumentList containing one argument with type=`class` and name=`T`.
Implements ClassDef.
getTitleForMemberListType() [1/2]
void ClassDefImpl::getTitleForMemberListType (MemberListType type, QCString & title, QCString & subtitle) const [private]
Definition at line 4363 of file classdef.cpp.
{
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd && lmd->type==type)
      {
        title = lmd->title(lang);
        subtitle = lmd->subtitle(lang);
        return;
      }
    }
  }
  title="";
  subtitle="";
}
References LayoutDocManager::Class, DefinitionMixin< ClassDefMutable >::getLanguage(), LayoutDocManager::instance(), LayoutDocEntry::MemberDecl, LayoutDocEntryMemberDecl::subtitle(), title(), LayoutDocEntryMemberDecl::title(), and LayoutDocEntryMemberDecl::type.
getTitleForMemberListType() [2/2]
void ClassDefImpl::getTitleForMemberListType (MemberListType type, QCString & title, QCString & subtitle) const [private]
hasDetailedDescription() [1/2]
bool ClassDefImpl::hasDetailedDescription () const [virtual]
returns TRUE if this class has a non-empty detailed description
Implements ClassDef.
Definition at line 1435 of file classdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  bool sourceBrowser = Config_getBool(SOURCE_BROWSER);
  return ((!briefDescription().isEmpty() && repeatBrief) ||
          !documentation().isEmpty() ||
          (sourceBrowser && getStartBodyLine()!=-1 && getBodyDef()));
}
References DefinitionMixin< ClassDefMutable >::briefDescription(), Config_getBool, DefinitionMixin< ClassDefMutable >::documentation(), DefinitionMixin< ClassDefMutable >::getBodyDef(), and DefinitionMixin< ClassDefMutable >::getStartBodyLine().
Referenced by writeBriefDescription(), and writeDetailedDescription().
hasDetailedDescription() [2/2]
virtual bool ClassDefImpl::hasDetailedDescription () const [virtual]
returns TRUE if this class has a non-empty detailed description
Implements ClassDef.
hasDocumentation() [1/2]
bool ClassDefImpl::hasDocumentation () const [virtual]
returns TRUE if this class has documentation
Reimplemented from DefinitionMixin< ClassDefMutable >.
Definition at line 3364 of file classdef.cpp.
{
  return DefinitionMixin::hasDocumentation();
}
References DefinitionMixin< Base >::hasDocumentation().
Referenced by isLinkableInProject(), and isVisibleInHierarchy().
hasDocumentation() [2/2]
virtual bool ClassDefImpl::hasDocumentation () const [virtual]
returns TRUE if this class has documentation
Reimplemented from DefinitionMixin< ClassDefMutable >.
hasExamples() [1/2]
bool ClassDefImpl::hasExamples () const [virtual]
Implements ClassDef.
Definition at line 3127 of file classdef.cpp.
{
  return !m_impl->examples.empty();
}
References ClassDefImpl::IMPL::examples, and m_impl.
Referenced by writeDetailedDocumentationBody(), and writeDocumentationContents().
hasExamples() [2/2]
virtual bool ClassDefImpl::hasExamples () const [virtual]
Implements ClassDef.
hasNonReferenceSuperClass() [1/2]
bool ClassDefImpl::hasNonReferenceSuperClass () const [virtual]
Returns TRUE iff this class or a class inheriting from this class is not defined in an external tag file.
Implements ClassDef.
Definition at line 3244 of file classdef.cpp.
{
  return hasNonReferenceSuperClassRec(this,0);
}
References hasNonReferenceSuperClassRec().
Referenced by isVisibleInHierarchy().
hasNonReferenceSuperClass() [2/2]
virtual bool ClassDefImpl::hasNonReferenceSuperClass () const [virtual]
Implements ClassDef.
includeInfo() [1/2]
const IncludeInfo * ClassDefImpl::includeInfo () const [virtual]
Implements ClassDef.
Definition at line 4659 of file classdef.cpp.
{
  return m_impl->incInfo.get();
}
References ClassDefImpl::IMPL::incInfo, and m_impl.
includeInfo() [2/2]
virtual const IncludeInfo * ClassDefImpl::includeInfo () const [virtual]
Implements ClassDef.
includeStatement() [1/2]
QCString ClassDefImpl::includeStatement () const [private]
Definition at line 1736 of file classdef.cpp.
{
  SrcLangExt lang = getLanguage();
  bool isIDLorJava = lang==SrcLangExt_IDL || lang==SrcLangExt_Java;
  if (isIDLorJava)
  {
    return "import";
  }
  else if (isObjectiveC())
  {
    return "#import ";
  }
  else
  {
    return "#include ";
  }
}
References DefinitionMixin< ClassDefMutable >::getLanguage(), isObjectiveC(), SrcLangExt_IDL, and SrcLangExt_Java.
Referenced by writeIncludeFiles().
includeStatement() [2/2]
QCString ClassDefImpl::includeStatement () const [private]
inheritanceGraphFileName() [1/2]
QCString ClassDefImpl::inheritanceGraphFileName () const [virtual]
returns the file name to use for the inheritance graph
Implements ClassDef.
Definition at line 4939 of file classdef.cpp.
{
  return m_impl->inheritFileName;
}
References ClassDefImpl::IMPL::inheritFileName, and m_impl.
inheritanceGraphFileName() [2/2]
virtual QCString ClassDefImpl::inheritanceGraphFileName () const [virtual]
returns the file name to use for the inheritance graph
Implements ClassDef.
insertBaseClass() [1/2]
void ClassDefImpl::insertBaseClass (ClassDef * cd, const QCString & name, Protection p, Specifier s, const QCString & t = QCString()) [virtual]
Implements ClassDefMutable.
Definition at line 807 of file classdef.cpp.
{
  //printf("*** insert base class %s into %s\n",qPrint(cd->name()),qPrint(name()));
  m_impl->inherits.push_back(BaseClassDef(cd,n,p,s,t));
  m_impl->isSimple = FALSE;
}
References FALSE, ClassDefImpl::IMPL::inherits, ClassDefImpl::IMPL::isSimple, m_impl, n, p, and s.
Referenced by mergeCategory().
insertBaseClass() [2/2]
virtual void ClassDefImpl::insertBaseClass (ClassDef * , const QCString & name, Protection p, Specifier s, const QCString & t = QCString()) [virtual]
Implements ClassDefMutable.
insertMember() [1/2]
void ClassDefImpl::insertMember (MemberDef * md) [virtual]
Implements ClassDefMutable.
Definition at line 1138 of file classdef.cpp.
{
  internalInsertMember(md,md->protection(),TRUE);
}
References internalInsertMember(), MemberDef::protection(), and TRUE.
Referenced by addMembersToTemplateInstance(), and reclassifyMember().
insertMember() [2/2]
virtual void ClassDefImpl::insertMember (MemberDef *) [virtual]
Implements ClassDefMutable.
insertSubClass() [1/2]
void ClassDefImpl::insertSubClass (ClassDef * cd, Protection p, Specifier s, const QCString & t = QCString()) [virtual]
Implements ClassDefMutable.
Definition at line 816 of file classdef.cpp.
{
  //printf("*** insert sub class %s into %s\n",qPrint(cd->name()),qPrint(name()));
  bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
  if (!extractPrivate && cd->protection()==Private) return;
  m_impl->inheritedBy.push_back(BaseClassDef(cd,QCString(),p,s,t));
  m_impl->isSimple = FALSE;
}
References Config_getBool, FALSE, ClassDefImpl::IMPL::inheritedBy, ClassDefImpl::IMPL::isSimple, m_impl, p, Private, ClassDef::protection(), and s.
insertSubClass() [2/2]
virtual void ClassDefImpl::insertSubClass (ClassDef * , Protection p, Specifier s, const QCString & t = QCString()) [virtual]
Implements ClassDefMutable.
insertTemplateInstance() [1/2]
ClassDef * ClassDefImpl::insertTemplateInstance (const QCString & fileName, int startLine, int startColumn, const QCString & templSpec, bool & freshInstance) const [virtual]
Implements ClassDef.
Definition at line 3973 of file classdef.cpp.
{
  freshInstance = FALSE;
  auto it = std::find_if(m_impl->templateInstances.begin(),
                         m_impl->templateInstances.end(),
                         [&templSpec](const auto &ti) { return templSpec==ti.templSpec; });
  ClassDefMutable *templateClass=0;
  if (it!=m_impl->templateInstances.end())
  {
    templateClass = toClassDefMutable((*it).classDef);
  }
  if (templateClass==0)
  {
    QCString tcname = removeRedundantWhiteSpace(localName()+templSpec);
    Debug::print(Debug::Classes,0," New template instance class '%s''%s' inside '%s' hidden=%d\n",qPrint(name()),qPrint(templSpec),qPrint(name()),isHidden());
    ClassDef *foundCd = Doxygen::classLinkedMap->find(tcname);
    if (foundCd)
    {
      return foundCd;
    }
    templateClass =
      toClassDefMutable(
          Doxygen::classLinkedMap->add(tcname,
            std::unique_ptr<ClassDef>(
              new ClassDefImpl(fileName,startLine,startColumn,tcname,ClassDef::Class))));
    if (templateClass)
    {
      templateClass->setTemplateMaster(this);
      templateClass->setOuterScope(getOuterScope());
      templateClass->setHidden(isHidden());
      templateClass->setArtificial(isArtificial());
      m_impl->templateInstances.push_back(TemplateInstanceDef(templSpec,templateClass));
      // also add nested classes
      for (const auto &innerCd : m_impl->innerClasses)
      {
        QCString innerName = tcname+"::"+innerCd->localName();
        ClassDefMutable *innerClass =
          toClassDefMutable(
              Doxygen::classLinkedMap->add(innerName,
                std::unique_ptr<ClassDef>(
                  new ClassDefImpl(fileName,startLine,startColumn,innerName,ClassDef::Class))));
        if (innerClass)
        {
          templateClass->addInnerCompound(innerClass);
          innerClass->setOuterScope(templateClass);
          innerClass->setHidden(isHidden());
          innerClass->setArtificial(TRUE);
        }
      }
      freshInstance=TRUE;
    }
  }
  return templateClass;
}
References add(), ClassDefMutable::addInnerCompound(), ClassDef::Class, ClassDefImpl(), Debug::Classes, Doxygen::classLinkedMap, FALSE, LinkedMap< T, Hash, KeyEqual, Map >::find(), DefinitionMixin< ClassDefMutable >::getOuterScope(), ClassDefImpl::IMPL::innerClasses, DefinitionMixin< ClassDefMutable >::isArtificial(), DefinitionMixin< ClassDefMutable >::isHidden(), DefinitionMixin< ClassDefMutable >::localName(), m_impl, DefinitionMixin< ClassDefMutable >::name(), Debug::print(), qPrint(), removeRedundantWhiteSpace(), DefinitionMutable::setArtificial(), DefinitionMutable::setHidden(), DefinitionMutable::setOuterScope(), ClassDefMutable::setTemplateMaster(), ClassDefImpl::IMPL::templateInstances, toClassDefMutable(), and TRUE.
insertTemplateInstance() [2/2]
virtual ClassDef * ClassDefImpl::insertTemplateInstance (const QCString & fileName, int startLine, int startColumn, const QCString & templSpec, bool & freshInstance) const [virtual]
Implements ClassDef.
insertUsedFile() [1/2]
void ClassDefImpl::insertUsedFile (const FileDef * fd) [virtual]
Implements ClassDefMutable.
Definition at line 1187 of file classdef.cpp.
{
  if (fd==0) return;
  auto it = std::find(m_impl->files.begin(),m_impl->files.end(),fd);
  if (it==m_impl->files.end())
  {
    m_impl->files.push_back(fd);
  }
  for (const auto &ti : m_impl->templateInstances)
  {
    ClassDefMutable *cdm = toClassDefMutable(ti.classDef);
    if (cdm)
    {
      cdm->insertUsedFile(fd);
    }
  }
}
References ClassDefImpl::IMPL::files, ClassDefMutable::insertUsedFile(), m_impl, ClassDefImpl::IMPL::templateInstances, and toClassDefMutable().
insertUsedFile() [2/2]
virtual void ClassDefImpl::insertUsedFile (const FileDef *) [virtual]
Implements ClassDefMutable.
internalInsertMember() [1/2]
void ClassDefImpl::internalInsertMember (const MemberDef * md, Protection prot, bool addToAllList) [private]
isReference()
Definition at line 848 of file classdef.cpp.
{
  //printf("insertInternalMember(%s) isHidden()=%d\n",qPrint(md->name()),md->isHidden());
  if (md->isHidden()) return;
  if (getLanguage()==SrcLangExt_VHDL)
  {
    QCString title=theTranslator->trVhdlType(md->getMemberSpecifiers(),FALSE);
    m_impl->vhdlSummaryTitles.insert(title.str());
  }
  if (1) // changed to 1 for showing members of external
                            // classes when HAVE_DOT and UML_LOOK are enabled.
  {
    bool isSimple=FALSE;
    /********************************************/
    /* insert member in the declaration section */
    /********************************************/
    if (md->isRelated() && protectionLevelVisible(prot))
    {
      addMemberToList(MemberListType_related,md,TRUE);
    }
    else if (md->isFriend())
    {
      addMemberToList(MemberListType_friends,md,TRUE);
    }
    else
    {
      switch (md->memberType())
      {
        case MemberType_Service: // UNO IDL
          addMemberToList(MemberListType_services,md,TRUE);
          break;
        case MemberType_Interface: // UNO IDL
          addMemberToList(MemberListType_interfaces,md,TRUE);
          break;
        case MemberType_Signal: // Qt specific
          addMemberToList(MemberListType_signals,md,TRUE);
          break;
        case MemberType_DCOP: // KDE2 specific
          addMemberToList(MemberListType_dcopMethods,md,TRUE);
          break;
        case MemberType_Property:
          addMemberToList(MemberListType_properties,md,TRUE);
          break;
        case MemberType_Event:
          addMemberToList(MemberListType_events,md,TRUE);
          break;
        case MemberType_Slot: // Qt specific
          switch (prot)
          {
            case Protected:
            case Package: // slots in packages are not possible!
              addMemberToList(MemberListType_proSlots,md,TRUE);
              break;
            case Public:
              addMemberToList(MemberListType_pubSlots,md,TRUE);
              break;
            case Private:
              addMemberToList(MemberListType_priSlots,md,TRUE);
              break;
          }
          break;
        default: // any of the other members
          if (md->isStatic())
          {
            if (md->isVariable())
            {
              switch (prot)
              {
                case Protected:
                  addMemberToList(MemberListType_proStaticAttribs,md,TRUE);
                  break;
                case Package:
                  addMemberToList(MemberListType_pacStaticAttribs,md,TRUE);
                  break;
                case Public:
                  addMemberToList(MemberListType_pubStaticAttribs,md,TRUE);
                  break;
                case Private:
                  addMemberToList(MemberListType_priStaticAttribs,md,TRUE);
                  break;
              }
            }
            else // function
            {
              switch (prot)
              {
                case Protected:
                  addMemberToList(MemberListType_proStaticMethods,md,TRUE);
                  break;
                case Package:
                  addMemberToList(MemberListType_pacStaticMethods,md,TRUE);
                  break;
                case Public:
                  addMemberToList(MemberListType_pubStaticMethods,md,TRUE);
                  break;
                case Private:
                  addMemberToList(MemberListType_priStaticMethods,md,TRUE);
                  break;
              }
            }
          }
          else // not static
          {
            if (md->isVariable())
            {
              switch (prot)
              {
                case Protected:
                  addMemberToList(MemberListType_proAttribs,md,TRUE);
                  break;
                case Package:
                  addMemberToList(MemberListType_pacAttribs,md,TRUE);
                  break;
                case Public:
                  addMemberToList(MemberListType_pubAttribs,md,TRUE);
                  isSimple=!md->isFunctionPtr();
                  break;
                case Private:
                  addMemberToList(MemberListType_priAttribs,md,TRUE);
                  break;
              }
            }
            else if (md->isTypedef() || md->isEnumerate() || md->isEnumValue())
            {
              switch (prot)
              {
                case Protected:
                  addMemberToList(MemberListType_proTypes,md,TRUE);
                  break;
                case Package:
                  addMemberToList(MemberListType_pacTypes,md,TRUE);
                  break;
                case Public:
                  addMemberToList(MemberListType_pubTypes,md,TRUE);
                  isSimple=!md->isEnumerate() &&
                           !md->isEnumValue() &&
                           QCString(md->typeString()).find(")(")==-1; // func ptr typedef
                  break;
                case Private:
                  addMemberToList(MemberListType_priTypes,md,TRUE);
                  break;
              }
            }
            else // member function
            {
              switch (prot)
              {
                case Protected:
                  addMemberToList(MemberListType_proMethods,md,TRUE);
                  break;
                case Package:
                  addMemberToList(MemberListType_pacMethods,md,TRUE);
                  break;
                case Public:
                  addMemberToList(MemberListType_pubMethods,md,TRUE);
                  break;
                case Private:
                  addMemberToList(MemberListType_priMethods,md,TRUE);
                  break;
              }
            }
          }
          break;
      }
    }
    if (!isSimple) // not a simple field -> not a simple struct
    {
      m_impl->isSimple = FALSE;
    }
    //printf("adding %s simple=%d total_simple=%d\n",qPrint(name()),isSimple,m_impl->isSimple);
    /*******************************************************/
    /* insert member in the detailed documentation section */
    /*******************************************************/
    if ((md->isRelated() && protectionLevelVisible(prot)) || md->isFriend())
    {
      addMemberToList(MemberListType_relatedMembers,md,FALSE);
    }
    else if (md->isFunction() &&
             md->protection()==Private &&
             (md->virtualness()!=Normal || md->isOverride() || md->isFinal()) &&
             Config_getBool(EXTRACT_PRIV_VIRTUAL))
    {
      addMemberToList(MemberListType_functionMembers,md,FALSE);
    }
    else
    {
      switch (md->memberType())
      {
        case MemberType_Service: // UNO IDL
          addMemberToList(MemberListType_serviceMembers,md,FALSE);
          break;
        case MemberType_Interface: // UNO IDL
          addMemberToList(MemberListType_interfaceMembers,md,FALSE);
          break;
        case MemberType_Property:
          addMemberToList(MemberListType_propertyMembers,md,FALSE);
          break;
        case MemberType_Event:
          addMemberToList(MemberListType_eventMembers,md,FALSE);
          break;
        case MemberType_Signal: // fall through
        case MemberType_DCOP:
          addMemberToList(MemberListType_functionMembers,md,FALSE);
          break;
        case MemberType_Slot:
          if (protectionLevelVisible(prot))
          {
            addMemberToList(MemberListType_functionMembers,md,FALSE);
          }
          break;
        default: // any of the other members
          if (protectionLevelVisible(prot))
          {
            switch (md->memberType())
            {
              case MemberType_Typedef:
                addMemberToList(MemberListType_typedefMembers,md,FALSE);
                break;
              case MemberType_Enumeration:
                addMemberToList(MemberListType_enumMembers,md,FALSE);
                break;
              case MemberType_EnumValue:
                addMemberToList(MemberListType_enumValMembers,md,FALSE);
                break;
              case MemberType_Function:
                if (md->isConstructor() || md->isDestructor())
                {
                  m_impl->memberLists.get(MemberListType_constructors,MemberListContainer::Class)->push_back(md);
                }
                else
                {
                  addMemberToList(MemberListType_functionMembers,md,FALSE);
                }
                break;
              case MemberType_Variable:
                addMemberToList(MemberListType_variableMembers,md,FALSE);
                break;
              case MemberType_Define:
                warn(md->getDefFileName(),md->getDefLine()-1,"A define (%s) cannot be made a member of %s",
                     qPrint(md->name()), qPrint(this->name()));
                break;
              default:
                err("Unexpected member type %d found!\n",md->memberType());
            }
          }
          break;
      }
    }
    /*************************************************/
    /* insert member in the appropriate member group */
    /*************************************************/
    // Note: this must be done AFTER inserting the member in the
    // regular groups
    //addMemberToGroup(md,groupId);
  }
  if (md->virtualness()==Pure)
  {
    m_impl->isAbstract=TRUE;
  }
  if (md->name()=="operator->")
  {
    m_impl->arrowOperator=md;
  }
  //::addClassMemberNameToIndex(md);
  if (addToAllList &&
      !(Config_getBool(HIDE_FRIEND_COMPOUNDS) &&
        md->isFriend() &&
        (QCString(md->typeString())=="friend class" ||
         QCString(md->typeString())=="friend struct" ||
         QCString(md->typeString())=="friend union")))
  {
    //printf("=======> adding member %s to class %s\n",qPrint(md->name()),qPrint(name()));
    MemberNameInfo *mni = m_impl->allMemberNameInfoLinkedMap.add(md->name());
    mni->push_back(std::make_unique<MemberInfo>(md,prot,md->virtualness(),FALSE));
  }
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), addMemberToList(), ClassDefImpl::IMPL::allMemberNameInfoLinkedMap, ClassDefImpl::IMPL::arrowOperator, Class, Config_getBool, err(), FALSE, QCString::find(), MemberLists::get(), Definition::getDefFileName(), Definition::getDefLine(), DefinitionMixin< ClassDefMutable >::getLanguage(), MemberDef::getMemberSpecifiers(), ClassDefImpl::IMPL::isAbstract, MemberDef::isConstructor(), MemberDef::isDestructor(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isFinal(), MemberDef::isFriend(), MemberDef::isFunction(), MemberDef::isFunctionPtr(), Definition::isHidden(), MemberDef::isOverride(), MemberDef::isRelated(), isSimple(), ClassDefImpl::IMPL::isSimple, MemberDef::isStatic(), MemberDef::isTypedef(), MemberDef::isVariable(), m_impl, ClassDefImpl::IMPL::memberLists, MemberListType_constructors, MemberListType_dcopMethods, MemberListType_enumMembers, MemberListType_enumValMembers, MemberListType_eventMembers, MemberListType_events, MemberListType_friends, MemberListType_functionMembers, MemberListType_interfaceMembers, MemberListType_interfaces, MemberListType_pacAttribs, MemberListType_pacMethods, MemberListType_pacStaticAttribs, MemberListType_pacStaticMethods, MemberListType_pacTypes, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_priTypes, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_properties, MemberListType_propertyMembers, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_proTypes, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, MemberListType_pubTypes, MemberListType_related, MemberListType_relatedMembers, MemberListType_serviceMembers, MemberListType_services, MemberListType_signals, MemberListType_typedefMembers, MemberListType_variableMembers, MemberDef::memberType(), MemberType_DCOP, MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, DefinitionMixin< ClassDefMutable >::name(), Definition::name(), Normal, Package, Private, Protected, MemberDef::protection(), protectionLevelVisible(), Public, Pure, MemberNameInfo::push_back(), qPrint(), SrcLangExt_VHDL, QCString::str(), theTranslator, title(), TRUE, Translator::trVhdlType(), MemberDef::typeString(), ClassDefImpl::IMPL::vhdlSummaryTitles, MemberDef::virtualness(), and warn().
Referenced by insertMember(), mergeCategory(), and mergeMembers().
internalInsertMember() [2/2]
void ClassDefImpl::internalInsertMember (const MemberDef * md, Protection prot, bool addToAllList) [private]
isAbstract() [1/2]
bool ClassDefImpl::isAbstract () const [virtual]
Returns TRUE if there is at least one pure virtual member in this class.
Implements ClassDef.
Definition at line 4684 of file classdef.cpp.
{
  return m_impl->isAbstract || (m_impl->spec&Entry::Abstract);
}
References Entry::Abstract, ClassDefImpl::IMPL::isAbstract, m_impl, and ClassDefImpl::IMPL::spec.
Referenced by addClassAttributes().
isAbstract() [2/2]
virtual bool ClassDefImpl::isAbstract () const [virtual]
Returns TRUE if there is at least one pure virtual member in this class.
Implements ClassDef.
isAccessibleMember() [1/2]
bool ClassDefImpl::isAccessibleMember (const MemberDef * md) const [virtual]
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
Implements ClassDef.
Definition at line 4199 of file classdef.cpp.
{
  return md->getClassDef() && isBaseClass(md->getClassDef(),TRUE);
}
References MemberDef::getClassDef(), isBaseClass(), and TRUE.
isAccessibleMember() [2/2]
virtual bool ClassDefImpl::isAccessibleMember (const MemberDef * md) const [virtual]
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
Implements ClassDef.
isBaseClass() [1/2]
int ClassDefImpl::isBaseClass (const ClassDef * bcd, bool followInstances) const [virtual]
Returns TRUE iff bcd is a direct or indirect base class of this class. This function will recursively traverse all branches of the inheritance tree.
Implements ClassDef.
Definition at line 3374 of file classdef.cpp.
{
  int distance=0;
  //printf("isBaseClass(cd=%s) looking for %s\n",qPrint(name()),qPrint(bcd->name()));
  for (const auto &bclass : baseClasses())
  {
    const ClassDef *ccd = bclass.classDef;
    if (!followInstances && ccd->templateMaster()) ccd=ccd->templateMaster();
    if (ccd==bcd)
    {
      distance=1;
      break; // no shorter path possible
    }
    else
    {
      int d = ccd->isBaseClass(bcd,followInstances);
      if (d>256)
      {
        err("Possible recursive class relation while inside %s and looking for base class %s\n",qPrint(name()),qPrint(bcd->name()));
        return 0;
      }
      else if (d>0) // path found
      {
        if (distance==0 || d+1<distance) // update if no path found yet or shorter path found
        {
          distance=d+1;
        }
      }
    }
  }
  return distance;
}
References baseClasses(), err(), ClassDef::isBaseClass(), DefinitionMixin< ClassDefMutable >::name(), Definition::name(), qPrint(), and ClassDef::templateMaster().
Referenced by isAccessibleMember().
isBaseClass() [2/2]
virtual int ClassDefImpl::isBaseClass (const ClassDef * bcd, bool followInstances) const [virtual]
Returns TRUE iff bcd is a direct or indirect base class of this class. This function will recursively traverse all branches of the inheritance tree.
Implements ClassDef.
isCSharp() [1/2]
bool ClassDefImpl::isCSharp () const [virtual]
Returns TRUE if this class is implemented in C#
Implements ClassDef.
Definition at line 4724 of file classdef.cpp.
{
  return getLanguage()==SrcLangExt_CSharp;
}
References DefinitionMixin< ClassDefMutable >::getLanguage(), and SrcLangExt_CSharp.
isCSharp() [2/2]
virtual bool ClassDefImpl::isCSharp () const [virtual]
Returns TRUE if this class is implemented in C#
Implements ClassDef.
isEmbeddedInOuterScope() [1/2]
bool ClassDefImpl::isEmbeddedInOuterScope () const [virtual]
Implements ClassDef.
Definition at line 4832 of file classdef.cpp.
{
  bool inlineGroupedClasses = Config_getBool(INLINE_GROUPED_CLASSES);
  bool inlineSimpleClasses = Config_getBool(INLINE_SIMPLE_STRUCTS);
  Definition *container = getOuterScope();
  bool containerLinkable =
    container &&
       (
        (container==Doxygen::globalScope && getFileDef() && getFileDef()->isLinkableInProject()) || // global class in documented file
        container->isLinkableInProject() // class in documented scope
       );
  // inline because of INLINE_GROUPED_CLASSES=YES ?
  bool b1 = (inlineGroupedClasses && !partOfGroups().empty()); // a grouped class
  // inline because of INLINE_SIMPLE_STRUCTS=YES ?
  bool b2 = (inlineSimpleClasses && m_impl->isSimple && // a simple class
             (containerLinkable || // in a documented container
              !partOfGroups().empty() // or part of a group
             )
           );
  //printf("%s::isEmbeddedInOuterScope(): inlineGroupedClasses=%d "
  // "inlineSimpleClasses=%d partOfGroups()=%p m_impl->isSimple=%d "
  // "getOuterScope()=%s b1=%d b2=%d\n",
  // qPrint(name()),inlineGroupedClasses,inlineSimpleClasses,
  // partOfGroups().pointer(),m_impl->isSimple,getOuterScope()?qPrint(getOuterScope()->name()):"<none>",b1,b2);
  return b1 || b2; // either reason will do
}
References Config_getBool, getFileDef(), DefinitionMixin< ClassDefMutable >::getOuterScope(), Doxygen::globalScope, Definition::isLinkableInProject(), FileDef::isLinkableInProject(), ClassDefImpl::IMPL::isSimple, m_impl, and DefinitionMixin< ClassDefMutable >::partOfGroups().
Referenced by anchor().
isEmbeddedInOuterScope() [2/2]
virtual bool ClassDefImpl::isEmbeddedInOuterScope () const [virtual]
Implements ClassDef.
isExtension() [1/2]
bool ClassDefImpl::isExtension () const [virtual]
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
Implements ClassDef.
Definition at line 4890 of file classdef.cpp.
{
  QCString n = name();
  int si = n.find('(');
  int ei = n.find(')');
  bool b = ei>si && n.mid(si+1,ei-si-1).stripWhiteSpace().isEmpty();
  return b;
}
References b, n, and DefinitionMixin< ClassDefMutable >::name().
Referenced by mergeCategory(), and visibleInParentsDeclList().
isExtension() [2/2]
virtual bool ClassDefImpl::isExtension () const [virtual]
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
Implements ClassDef.
isFinal() [1/2]
bool ClassDefImpl::isFinal () const [virtual]
Returns TRUE if this class is marked as final
Implements ClassDef.
Definition at line 4689 of file classdef.cpp.
{
  return m_impl->spec&Entry::Final;
}
References Entry::Final, m_impl, and ClassDefImpl::IMPL::spec.
Referenced by addClassAttributes().
isFinal() [2/2]
virtual bool ClassDefImpl::isFinal () const [virtual]
Returns TRUE if this class is marked as final
Implements ClassDef.
isFortran() [1/2]
bool ClassDefImpl::isFortran () const [virtual]
Returns TRUE if this class is implemented in Fortran
Implements ClassDef.
Definition at line 4719 of file classdef.cpp.
{
  return getLanguage()==SrcLangExt_Fortran;
}
References DefinitionMixin< ClassDefMutable >::getLanguage(), and SrcLangExt_Fortran.
Referenced by writeTagFile().
isFortran() [2/2]
virtual bool ClassDefImpl::isFortran () const [virtual]
Returns TRUE if this class is implemented in Fortran
Implements ClassDef.
isForwardDeclared() [1/2]
bool ClassDefImpl::isForwardDeclared () const [virtual]
Returns TRUE if this class represents a forward declaration of a template class
Implements ClassDef.
Definition at line 4704 of file classdef.cpp.
{
  return m_impl->spec&Entry::ForwardDecl;
}
References Entry::ForwardDecl, m_impl, and ClassDefImpl::IMPL::spec.
isForwardDeclared() [2/2]
virtual bool ClassDefImpl::isForwardDeclared () const [virtual]
Returns TRUE if this class represents a forward declaration of a template class
Implements ClassDef.
isInterface() [1/2]
bool ClassDefImpl::isInterface () const [virtual]
Returns TRUE if this class represents an interface
Implements ClassDef.
Definition at line 4709 of file classdef.cpp.
{
  return m_impl->spec&Entry::Interface;
}
References Entry::Interface, m_impl, and ClassDefImpl::IMPL::spec.
isInterface() [2/2]
virtual bool ClassDefImpl::isInterface () const [virtual]
Returns TRUE if this class represents an interface
Implements ClassDef.
isJavaEnum() [1/2]
bool ClassDefImpl::isJavaEnum () const [virtual]
Implements ClassDef.
Definition at line 4880 of file classdef.cpp.
{
  return m_impl->isJavaEnum;
}
References ClassDefImpl::IMPL::isJavaEnum, and m_impl.
Referenced by ClassDefImpl(), compoundTypeString(), generatedFromFiles(), and title().
isJavaEnum() [2/2]
virtual bool ClassDefImpl::isJavaEnum () const [virtual]
Implements ClassDef.
isLinkable() [1/2]
bool ClassDefImpl::isLinkable () const [virtual]
return TRUE iff a link to this class is possible (either within this project, or as a cross-reference to another project).
Implements ClassDef.
Definition at line 3328 of file classdef.cpp.
{
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->isLinkable();
  }
  else
  {
    return isReference() || isLinkableInProject();
  }
}
References ClassDef::isLinkable(), isLinkableInProject(), isReference(), m_impl, and ClassDefImpl::IMPL::templateMaster.
Referenced by getMemberByName(), visibleInParentsDeclList(), writeDeclaration(), and writeDeclarationLink().
isLinkable() [2/2]
virtual bool ClassDefImpl::isLinkable () const [virtual]
return TRUE iff a link to this class is possible (either within this project, or as a cross-reference to another project).
Implements ClassDef.
isLinkableInProject() [1/2]
bool ClassDefImpl::isLinkableInProject () const [virtual]
a link to this class is possible within this project
Implements ClassDef.
Definition at line 3306 of file classdef.cpp.
{
  bool extractLocal = Config_getBool(EXTRACT_LOCAL_CLASSES);
  bool extractStatic = Config_getBool(EXTRACT_STATIC);
  bool hideUndoc = Config_getBool(HIDE_UNDOC_CLASSES);
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->isLinkableInProject();
  }
  else
  {
    return !name().isEmpty() && /* has a name */
      !isArtificial() && !isHidden() && /* not hidden */
      !isAnonymous() && /* not anonymous */
      protectionLevelVisible(m_impl->prot) && /* private/internal */
      (!m_impl->isLocal || extractLocal) && /* local */
      (hasDocumentation() || !hideUndoc) && /* documented */
      (!m_impl->isStatic || extractStatic) && /* static */
      !isReference(); /* not an external reference */
  }
}
References Config_getBool, hasDocumentation(), DefinitionMixin< ClassDefMutable >::isAnonymous(), DefinitionMixin< ClassDefMutable >::isArtificial(), QCString::isEmpty(), DefinitionMixin< ClassDefMutable >::isHidden(), ClassDef::isLinkableInProject(), ClassDefImpl::IMPL::isLocal, isReference(), ClassDefImpl::IMPL::isStatic, m_impl, DefinitionMixin< ClassDefMutable >::name(), ClassDefImpl::IMPL::prot, protectionLevelVisible(), and ClassDefImpl::IMPL::templateMaster.
Referenced by addListReferences(), getOutputFileBase(), isLinkable(), writeDeclarationLink(), and writeTagFile().
isLinkableInProject() [2/2]
virtual bool ClassDefImpl::isLinkableInProject () const [virtual]
returns TRUE iff a link is possible to this item within this project.
Implements ClassDef.
isLocal() [1/2]
bool ClassDefImpl::isLocal () const [virtual]
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES
Implements ClassDef.
Definition at line 4574 of file classdef.cpp.
{
  return m_impl->isLocal;
}
References ClassDefImpl::IMPL::isLocal, and m_impl.
Referenced by visibleInParentsDeclList().
isLocal() [2/2]
virtual bool ClassDefImpl::isLocal () const [virtual]
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES
Implements ClassDef.
isObjectiveC() [1/2]
bool ClassDefImpl::isObjectiveC () const [virtual]
Returns TRUE if this class is implemented in Objective-C
Implements ClassDef.
Definition at line 4714 of file classdef.cpp.
{
  return getLanguage()==SrcLangExt_ObjC;
}
References DefinitionMixin< ClassDefMutable >::getLanguage(), and SrcLangExt_ObjC.
Referenced by includeStatement(), and writeTagFile().
isObjectiveC() [2/2]
virtual bool ClassDefImpl::isObjectiveC () const [virtual]
Returns TRUE if this class is implemented in Objective-C
Implements ClassDef.
isPublished() [1/2]
bool ClassDefImpl::isPublished () const [virtual]
Returns TRUE if this class is marked as published
Implements ClassDef.
Definition at line 4699 of file classdef.cpp.
{
  return m_impl->spec&Entry::Published;
}
References m_impl, Entry::Published, and ClassDefImpl::IMPL::spec.
Referenced by addClassAttributes().
isPublished() [2/2]
virtual bool ClassDefImpl::isPublished () const [virtual]
Returns TRUE if this class is marked as published
Implements ClassDef.
isReference() [1/2]
bool ClassDefImpl::isReference () const [virtual]
Returns TRUE if this class is imported via a tag file
Reimplemented from DefinitionMixin< ClassDefMutable >.
Definition at line 4093 of file classdef.cpp.
{
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->isReference();
  }
  else
  {
    return DefinitionMixin::isReference();
  }
}
References DefinitionMixin< Base >::isReference(), ClassDef::isReference(), m_impl, and ClassDefImpl::IMPL::templateMaster.
Referenced by isLinkable(), isLinkableInProject(), and isVisibleInHierarchy().
isReference() [2/2]
virtual bool ClassDefImpl::isReference () const [virtual]
Returns TRUE if this class is imported via a tag file
Reimplemented from DefinitionMixin< ClassDefMutable >.
isSealed() [1/2]
bool ClassDefImpl::isSealed () const [virtual]
Returns TRUE if this class is marked as sealed
Implements ClassDef.
Definition at line 4694 of file classdef.cpp.
{
  return m_impl->spec&Entry::Sealed;
}
References m_impl, Entry::Sealed, and ClassDefImpl::IMPL::spec.
Referenced by addClassAttributes().
isSealed() [2/2]
virtual bool ClassDefImpl::isSealed () const [virtual]
Returns TRUE if this class is marked as sealed
Implements ClassDef.
isSimple() [1/2]
bool ClassDefImpl::isSimple () const [virtual]
Implements ClassDef.
Definition at line 4794 of file classdef.cpp.
{
  return m_impl->isSimple;
}
References ClassDefImpl::IMPL::isSimple, and m_impl.
Referenced by internalInsertMember(), and writeInlineDocumentation().
isSimple() [2/2]
virtual bool ClassDefImpl::isSimple () const [virtual]
Implements ClassDef.
isSliceLocal() [1/2]
bool ClassDefImpl::isSliceLocal () const [virtual]
Implements ClassDef.
Definition at line 4919 of file classdef.cpp.
{
  return m_impl->spec&Entry::Local;
}
References Entry::Local, m_impl, and ClassDefImpl::IMPL::spec.
Referenced by title(), and writeDeclarationLink().
isSliceLocal() [2/2]
virtual bool ClassDefImpl::isSliceLocal () const [virtual]
Implements ClassDef.
isSmartPointer() [1/2]
const MemberDef * ClassDefImpl::isSmartPointer () const [virtual]
Implements ClassDef.
Definition at line 4799 of file classdef.cpp.
{
  return m_impl->arrowOperator;
}
References ClassDefImpl::IMPL::arrowOperator, and m_impl.
isSmartPointer() [2/2]
virtual const MemberDef * ClassDefImpl::isSmartPointer () const [virtual]
Implements ClassDef.
isSubClass() [1/2]
bool ClassDefImpl::isSubClass (ClassDef * bcd, int level = 0) const [virtual]
Returns TRUE iff bcd is a direct or indirect sub class of this class.
Implements ClassDef.
Definition at line 3409 of file classdef.cpp.
{
  bool found=FALSE;
  if (level>256)
  {
    err("Possible recursive class relation while inside %s and looking for derived class %s\n",qPrint(name()),qPrint(cd->name()));
    return FALSE;
  }
  for (const auto &iscd : subClasses())
  {
    ClassDef *ccd=iscd.classDef;
    found = (ccd==cd) || ccd->isSubClass(cd,level+1);
    if (found) break;
  }
  return found;
}
References err(), FALSE, found, ClassDef::isSubClass(), level, DefinitionMixin< ClassDefMutable >::name(), Definition::name(), qPrint(), and subClasses().
isSubClass() [2/2]
virtual bool ClassDefImpl::isSubClass (ClassDef * bcd, int level = 0) const [virtual]
Returns TRUE iff bcd is a direct or indirect sub class of this class.
Implements ClassDef.
isTemplate() [1/2]
bool ClassDefImpl::isTemplate () const [virtual]
Returns TRUE if this class is a template
Implements ClassDef.
Definition at line 4654 of file classdef.cpp.
{
  return !m_impl->tempArgs.empty();
}
References ArgumentList::empty(), m_impl, and ClassDefImpl::IMPL::tempArgs.
isTemplate() [2/2]
virtual bool ClassDefImpl::isTemplate () const [virtual]
Returns TRUE if this class is a template
Implements ClassDef.
isTemplateArgument() [1/2]
bool ClassDefImpl::isTemplateArgument () const [virtual]
Implements ClassDef.
Definition at line 4679 of file classdef.cpp.
{
  return m_impl->isTemplArg;
}
References ClassDefImpl::IMPL::isTemplArg, and m_impl.
isTemplateArgument() [2/2]
virtual bool ClassDefImpl::isTemplateArgument () const [virtual]
Implements ClassDef.
isUsedOnly() [1/2]
bool ClassDefImpl::isUsedOnly () const [virtual]
Implements ClassDef.
Definition at line 4789 of file classdef.cpp.
{
  return m_impl->usedOnly;
}
References m_impl, and ClassDefImpl::IMPL::usedOnly.
isUsedOnly() [2/2]
virtual bool ClassDefImpl::isUsedOnly () const [virtual]
Implements ClassDef.
isVisibleInHierarchy() [1/2]
bool ClassDefImpl::isVisibleInHierarchy () const [virtual]
the class is visible in a class diagram, or class hierarchy
Implements ClassDef.
Definition at line 3342 of file classdef.cpp.
{
  bool allExternals = Config_getBool(ALLEXTERNALS);
  bool hideUndocClasses = Config_getBool(HIDE_UNDOC_CLASSES);
  bool extractStatic = Config_getBool(EXTRACT_STATIC);
  return // show all classes or a subclass is visible
      ((allExternals && !isArtificial()) || hasNonReferenceSuperClass()) &&
      // and not an anonymous compound
      !isAnonymous() &&
      // and not privately inherited
      protectionLevelVisible(m_impl->prot) &&
      // documented or shown anyway or documentation is external
      (hasDocumentation() ||
       !hideUndocClasses ||
       (m_impl->templateMaster && m_impl->templateMaster->hasDocumentation()) ||
       isReference()
      ) &&
      // is not part of an unnamed namespace or shown anyway
      (!m_impl->isStatic || extractStatic);
}
References Config_getBool, hasDocumentation(), ClassDef::hasDocumentation(), hasNonReferenceSuperClass(), DefinitionMixin< ClassDefMutable >::isAnonymous(), DefinitionMixin< ClassDefMutable >::isArtificial(), isReference(), ClassDefImpl::IMPL::isStatic, m_impl, ClassDefImpl::IMPL::prot, protectionLevelVisible(), and ClassDefImpl::IMPL::templateMaster.
isVisibleInHierarchy() [2/2]
virtual bool ClassDefImpl::isVisibleInHierarchy () const [virtual]
the class is visible in a class diagram, or class hierarchy
Implements ClassDef.
makeTemplateArgument() [1/2]
void ClassDefImpl::makeTemplateArgument (bool b = TRUE) [virtual]
Implements ClassDefMutable.
Definition at line 4774 of file classdef.cpp.
{
  m_impl->isTemplArg = b;
}
References b, ClassDefImpl::IMPL::isTemplArg, and m_impl.
makeTemplateArgument() [2/2]
virtual void ClassDefImpl::makeTemplateArgument (bool b = TRUE) [virtual]
Implements ClassDefMutable.
memberNameInfoLinkedMap() [1/2]
const MemberNameInfoLinkedMap & ClassDefImpl::memberNameInfoLinkedMap () const [virtual]
Returns a dictionary of all members. This includes any inherited members. Members are sorted alphabetically.
Implements ClassDef.
Definition at line 4609 of file classdef.cpp.
{
  return m_impl->allMemberNameInfoLinkedMap;
}
References ClassDefImpl::IMPL::allMemberNameInfoLinkedMap, and m_impl.
memberNameInfoLinkedMap() [2/2]
virtual const MemberNameInfoLinkedMap & ClassDefImpl::memberNameInfoLinkedMap () const [virtual]
Returns a dictionary of all members. This includes any inherited members. Members are sorted alphabetically.
Implements ClassDef.
mergeCategory() [1/2]
void ClassDefImpl::mergeCategory (ClassDef * cat) [virtual]
Merges the members of a Objective-C category into this class.
Implements ClassDefMutable.
Definition at line 3670 of file classdef.cpp.
{
  ClassDefMutable *category = toClassDefMutable(cat);
  if (category)
  {
    bool extractLocalMethods = Config_getBool(EXTRACT_LOCAL_METHODS);
    bool makePrivate = category->isLocal();
    // in case extract local methods is not enabled we don't add the methods
    // of the category in case it is defined in the .m file.
    if (makePrivate && !extractLocalMethods) return;
    bool isExtension = category->isExtension();
    category->setCategoryOf(this);
    if (isExtension)
    {
      category->setArtificial(TRUE);
      // copy base classes/protocols from extension
      for (const auto &bcd : category->baseClasses())
      {
        insertBaseClass(bcd.classDef,bcd.usedName,bcd.prot,bcd.virt,bcd.templSpecifiers);
        // correct bcd.classDef so that they do no longer derive from
        // category, but from this class!
        BaseClassList scl = bcd.classDef->subClasses();
        for (auto &scd : scl)
        {
          if (scd.classDef==category)
          {
            scd.classDef=this;
          }
        }
        bcd.classDef->updateSubClasses(scl);
      }
    }
    // make methods private for categories defined in the .m file
    //printf("%s::mergeCategory makePrivate=%d\n",qPrint(name()),makePrivate);
    const MemberNameInfoLinkedMap &srcMnd = category->memberNameInfoLinkedMap();
    MemberNameInfoLinkedMap &dstMnd = m_impl->allMemberNameInfoLinkedMap;
    for (auto &srcMni : srcMnd)
    {
      MemberNameInfo *dstMni=dstMnd.find(srcMni->memberName());
      if (dstMni) // method is already defined in the class
      {
        //printf("Existing member %s\n",srcMni->memberName());
        auto &dstMi = dstMni->front();
        auto &srcMi = srcMni->front();
        if (srcMi && dstMi)
        {
          MemberDefMutable *smdm = toMemberDefMutable(srcMi->memberDef());
          MemberDefMutable *dmdm = toMemberDefMutable(dstMi->memberDef());
          if (smdm && dmdm)
          {
            combineDeclarationAndDefinition(smdm,dmdm);
            dmdm->setCategory(category);
            dmdm->setCategoryRelation(smdm);
            smdm->setCategoryRelation(dmdm);
          }
        }
      }
      else // new method name
      {
        //printf("New member %s\n",srcMni->memberName());
        // create a deep copy of the list
        MemberNameInfo *newMni = dstMnd.add(srcMni->memberName());
        // copy the member(s) from the category to this class
        for (auto &mi : *srcMni)
        {
          //printf("Adding '%s'\n",qPrint(mi->memberDef->name()));
          Protection prot = mi->prot();
          //if (makePrivate) prot = Private;
          std::unique_ptr<MemberDefMutable> newMd { toMemberDefMutable(mi->memberDef()->deepCopy()) };
          if (newMd)
          {
            //printf("Copying member %s\n",qPrint(mi->memberDef->name()));
            newMd->moveTo(this);
            std::unique_ptr<MemberInfo> newMi=std::make_unique<MemberInfo>(newMd.get(),prot,mi->virt(),mi->inherited());
            newMi->setScopePath(mi->scopePath());
            newMi->setAmbigClass(mi->ambigClass());
            newMi->setAmbiguityResolutionScope(mi->ambiguityResolutionScope());
            newMni->push_back(std::move(newMi));
            // also add the newly created member to the global members list
            QCString name = newMd->name();
            MemberName *mn = Doxygen::memberNameLinkedMap->add(name);
            if (newMd)
            {
              newMd->setCategory(category);
              newMd->setCategoryRelation(mi->memberDef());
            }
            MemberDefMutable *mdm = toMemberDefMutable(mi->memberDef());
            if (mdm)
            {
              mdm->setCategoryRelation(newMd.get());
            }
            if (newMd && (makePrivate || isExtension))
            {
              newMd->makeImplementationDetail();
            }
            internalInsertMember(newMd.get(),prot,FALSE);
            mn->push_back(std::move(newMd));
          }
        }
      }
    }
  }
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), ClassDefImpl::IMPL::allMemberNameInfoLinkedMap, ClassDef::baseClasses(), combineDeclarationAndDefinition(), Config_getBool, FALSE, LinkedMap< T, Hash, KeyEqual, Map >::find(), MemberNameInfo::front(), insertBaseClass(), internalInsertMember(), isExtension(), ClassDef::isExtension(), ClassDef::isLocal(), m_impl, ClassDef::memberNameInfoLinkedMap(), Doxygen::memberNameLinkedMap, MemberDef::moveTo(), DefinitionMixin< ClassDefMutable >::name(), MemberName::push_back(), MemberNameInfo::push_back(), DefinitionMutable::setArtificial(), MemberDefMutable::setCategory(), ClassDefMutable::setCategoryOf(), MemberDefMutable::setCategoryRelation(), toClassDefMutable(), toMemberDefMutable(), and TRUE.
mergeCategory() [2/2]
virtual void ClassDefImpl::mergeCategory (ClassDef * category) [virtual]
Implements ClassDefMutable.
mergeMembers() [1/2]
void ClassDefImpl::mergeMembers () [virtual]
recursively merges the 'all members' lists of a class base with that of this class. Must only be called for classes without subclasses!
Implements ClassDefMutable.
Definition at line 3440 of file classdef.cpp.
{
  if (m_impl->membersMerged) return;
  //bool optimizeOutputForJava = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
  //bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  SrcLangExt lang = getLanguage();
  QCString sep=getLanguageSpecificSeparator(lang,TRUE);
  uint sepLen = sep.length();
  m_impl->membersMerged=TRUE;
  //printf(" mergeMembers for %s\n",qPrint(name()));
  bool inlineInheritedMembers = Config_getBool(INLINE_INHERITED_MEMB);
  bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
  for (const auto &bcd : baseClasses())
  {
    ClassDefMutable *bClass=toClassDefMutable(bcd.classDef);
    if (bClass)
    {
      // merge the members in the base class of this inheritance branch first
      bClass->mergeMembers();
      if (bClass->getLanguage()==SrcLangExt_Python) continue; // python does not have member overloading, see issue 8480
      const MemberNameInfoLinkedMap &srcMnd = bClass->memberNameInfoLinkedMap();
      MemberNameInfoLinkedMap &dstMnd = m_impl->allMemberNameInfoLinkedMap;
      for (auto &srcMni : srcMnd)
      {
        //printf(" Base member name %s\n",srcMni->memberName());
        MemberNameInfo *dstMni;
        if ((dstMni=dstMnd.find(srcMni->memberName())))
          // a member with that name is already in the class.
          // the member may hide or reimplement the one in the sub class
          // or there may be another path to the base class that is already
          // visited via another branch in the class hierarchy.
        {
          for (auto &srcMi : *srcMni)
          {
            const MemberDef *srcMd = srcMi->memberDef();
            bool found=FALSE;
            bool ambiguous=FALSE;
            bool hidden=FALSE;
            const ClassDef *srcCd = srcMd->getClassDef();
            for (auto &dstMi : *dstMni)
            {
              const MemberDef *dstMd = dstMi->memberDef();
              if (srcMd!=dstMd) // different members
              {
                const ClassDef *dstCd = dstMd->getClassDef();
                //printf(" Is %s a base class of %s?\n",qPrint(srcCd->name()),qPrint(dstCd->name()));
                if (srcCd==dstCd || dstCd->isBaseClass(srcCd,TRUE))
                  // member is in the same or a base class
                {
                  ArgumentList &srcAl = const_cast<ArgumentList&>(srcMd->argumentList());
                  ArgumentList &dstAl = const_cast<ArgumentList&>(dstMd->argumentList());
                  found=matchArguments2(
                      srcMd->getOuterScope(),srcMd->getFileDef(),&srcAl,
                      dstMd->getOuterScope(),dstMd->getFileDef(),&dstAl,
                      TRUE,getLanguage()
                      );
                  //printf(" Yes, matching (%s<->%s): %d\n",
                  // qPrint(argListToString(srcMd->argumentList())),
                  // qPrint(argListToString(dstMd->argumentList())),
                  // found);
                  hidden = hidden || !found;
                }
                else // member is in a non base class => multiple inheritance
                  // using the same base class.
                {
                  //printf("$$ Existing member %s %s add scope %s\n",
                  // qPrint(dstMi->ambiguityResolutionScope),
                  // qPrint(dstMd->name()),
                  // qPrint(dstMi->scopePath.left(dstMi->scopePath.find("::")+2));
                  QCString scope=dstMi->scopePath().left(dstMi->scopePath().find(sep)+sepLen);
                  if (scope!=dstMi->ambiguityResolutionScope().left(scope.length()))
                  {
                    dstMi->setAmbiguityResolutionScope(scope+dstMi->ambiguityResolutionScope());
                  }
                  ambiguous=TRUE;
                }
              }
              else // same members
              {
                // do not add if base class is virtual or
                // if scope paths are equal or
                // if base class is an interface (and thus implicitly virtual).
                //printf("same member found srcMi->virt=%d dstMi->virt=%d\n",srcMi->virt,dstMi->virt);
                if ((srcMi->virt()!=Normal && dstMi->virt()!=Normal) ||
                    bClass->name()+sep+srcMi->scopePath() == dstMi->scopePath() ||
                    dstMd->getClassDef()->compoundType()==Interface
                   )
                {
                  found=TRUE;
                }
                else // member can be reached via multiple paths in the
                  // inheritance tree
                {
                  //printf("$$ Existing member %s %s add scope %s\n",
                  // qPrint(dstMi->ambiguityResolutionScope),
                  // qPrint(dstMd->name()),
                  // qPrint(dstMi->scopePath.left(dstMi->scopePath.find("::")+2));
                  QCString scope=dstMi->scopePath().left(dstMi->scopePath().find(sep)+sepLen);
                  if (scope!=dstMi->ambiguityResolutionScope().left(scope.length()))
                  {
                    dstMi->setAmbiguityResolutionScope(dstMi->ambiguityResolutionScope()+scope);
                  }
                  ambiguous=TRUE;
                }
              }
              if (found) break;
            }
            //printf("member %s::%s hidden %d ambiguous %d srcMi->ambigClass=%p\n",
            // qPrint(srcCd->name()),qPrint(srcMd->name()),hidden,ambiguous,srcMi->ambigClass);
            // TODO: fix the case where a member is hidden by inheritance
            // of a member with the same name but with another prototype,
            // while there is more than one path to the member in the
            // base class due to multiple inheritance. In this case
            // it seems that the member is not reachable by prefixing a
            // scope name either (according to my compiler). Currently,
            // this case is shown anyway.
            if (!found && srcMd->protection()!=Private && !srcMd->isFriend())
            {
              Protection prot=srcMd->protection();
              if (bcd.prot==Protected && prot==Public) prot=bcd.prot;
              else if (bcd.prot==Private) prot=bcd.prot;
              if (inlineInheritedMembers)
              {
                if (!isStandardFunc(srcMd))
                {
                  //printf(" insertMember '%s'\n",qPrint(srcMd->name()));
                  internalInsertMember(srcMd,prot,FALSE);
                }
              }
              Specifier virt=srcMi->virt();
              if (virt==Normal && bcd.virt!=Normal) virt=bcd.virt;
              std::unique_ptr<MemberInfo> newMi = std::make_unique<MemberInfo>(srcMd,prot,virt,TRUE);
              newMi->setScopePath(bClass->name()+sep+srcMi->scopePath());
              if (ambiguous)
              {
                //printf("$$ New member %s %s add scope %s::\n",
                // qPrint(srcMi->ambiguityResolutionScope),
                // qPrint(srcMd->name()),
                // qPrint(bClass->name()));
                QCString scope=bClass->name()+sep;
                if (scope!=srcMi->ambiguityResolutionScope().left(scope.length()))
                {
                  newMi->setAmbiguityResolutionScope(scope+srcMi->ambiguityResolutionScope());
                }
              }
              if (hidden)
              {
                if (srcMi->ambigClass()==0)
                {
                  newMi->setAmbigClass(bClass);
                  newMi->setAmbiguityResolutionScope(bClass->name()+sep);
                }
                else
                {
                  newMi->setAmbigClass(srcMi->ambigClass());
                  newMi->setAmbiguityResolutionScope(srcMi->ambigClass()->name()+sep);
                }
              }
              dstMni->push_back(std::move(newMi));
            }
          }
        }
        else // base class has a member that is not in the sub class => copy
        {
          // create a deep copy of the list (only the MemberInfo's will be
          // copied, not the actual MemberDef's)
          MemberNameInfo *newMni = dstMnd.add(srcMni->memberName());
          // copy the member(s) from the base to the sub class
          for (auto &mi : *srcMni)
          {
            if (!mi->memberDef()->isFriend()) // don't inherit friends
            {
              Protection prot = mi->prot();
              if (bcd.prot==Protected)
              {
                if (prot==Public) prot=Protected;
              }
              else if (bcd.prot==Private)
              {
                prot=Private;
              }
              //printf("%s::%s: prot=%d bcd.prot=%d result=%d\n",
              // qPrint(name()),qPrint(mi->memberDef->name()),mi->prot,
              // bcd.prot,prot);
              if (prot!=Private || extractPrivate)
              {
                Specifier virt=mi->virt();
                if (virt==Normal && bcd.virt!=Normal) virt=bcd.virt;
                if (inlineInheritedMembers)
                {
                  if (!isStandardFunc(mi->memberDef()))
                  {
                    //printf(" insertMember '%s'\n",qPrint(mi->memberDef->name()));
                    internalInsertMember(mi->memberDef(),prot,FALSE);
                  }
                }
                //printf("Adding!\n");
                std::unique_ptr<MemberInfo> newMi = std::make_unique<MemberInfo>(mi->memberDef(),prot,virt,TRUE);
                newMi->setScopePath(bClass->name()+sep+mi->scopePath());
                newMi->setAmbigClass(mi->ambigClass());
                newMi->setAmbiguityResolutionScope(mi->ambiguityResolutionScope());
                newMni->push_back(std::move(newMi));
              }
            }
          }
        }
      }
    }
  }
  //printf(" end mergeMembers\n");
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), ClassDefImpl::IMPL::allMemberNameInfoLinkedMap, MemberDef::argumentList(), baseClasses(), ClassDef::compoundType(), Config_getBool, FALSE, LinkedMap< T, Hash, KeyEqual, Map >::find(), found, MemberDef::getClassDef(), MemberDef::getFileDef(), DefinitionMixin< ClassDefMutable >::getLanguage(), Definition::getLanguage(), getLanguageSpecificSeparator(), Definition::getOuterScope(), internalInsertMember(), ClassDef::isBaseClass(), MemberDef::isFriend(), isStandardFunc(), QCString::left(), QCString::length(), m_impl, matchArguments2(), ClassDef::memberNameInfoLinkedMap(), ClassDefImpl::IMPL::membersMerged, ClassDefMutable::mergeMembers(), Definition::name(), Normal, Private, Protected, MemberDef::protection(), Public, MemberNameInfo::push_back(), SrcLangExt_Python, toClassDefMutable(), and TRUE.
mergeMembers() [2/2]
virtual void ClassDefImpl::mergeMembers () [virtual]
Implements ClassDefMutable.
protection() [1/2]
Protection ClassDefImpl::protection () const [virtual]
Return the protection level (Public,Protected,Private) in which this compound was found.
Implements ClassDef.
Definition at line 4624 of file classdef.cpp.
{
  return m_impl->prot;
}
References m_impl, and ClassDefImpl::IMPL::prot.
Referenced by visibleInParentsDeclList(), and writeDeclarationLink().
protection() [2/2]
virtual Protection ClassDefImpl::protection () const [virtual]
Return the protection level (Public,Protected,Private) in which this compound was found.
Implements ClassDef.
qualifiedNameWithTemplateParameters() [1/2]
QCString ClassDefImpl::qualifiedNameWithTemplateParameters (const ArgumentLists * actualParams = 0, uint * actualParamIndex = 0) const [virtual]
Implements ClassDef.
Definition at line 4121 of file classdef.cpp.
{
  return makeQualifiedNameWithTemplateParameters(this,actualParams,actualParamIndex);
}
References makeQualifiedNameWithTemplateParameters().
qualifiedNameWithTemplateParameters() [2/2]
virtual QCString ClassDefImpl::qualifiedNameWithTemplateParameters (const ArgumentLists * actualParams = 0, uint * actualParamIndex = 0) const [virtual]
Implements ClassDef.
reclassifyMember() [1/2]
void ClassDefImpl::reclassifyMember (MemberDefMutable * md, MemberType t) [virtual]
Implements ClassDefMutable.
Definition at line 4804 of file classdef.cpp.
{
  md->setMemberType(t);
  for (auto &ml : m_impl->memberLists)
  {
    ml->remove(md);
  }
  insertMember(md);
}
References insertMember(), m_impl, ClassDefImpl::IMPL::memberLists, and MemberDefMutable::setMemberType().
reclassifyMember() [2/2]
virtual void ClassDefImpl::reclassifyMember (MemberDefMutable * md, MemberType t) [virtual]
Implements ClassDefMutable.
removeMemberFromLists() [1/2]
void ClassDefImpl::removeMemberFromLists (MemberDef * md) [virtual]
Implements ClassDefMutable.
Definition at line 4872 of file classdef.cpp.
{
  for (auto &ml : m_impl->memberLists)
  {
    ml->remove(md);
  }
}
References m_impl, and ClassDefImpl::IMPL::memberLists.
removeMemberFromLists() [2/2]
virtual void ClassDefImpl::removeMemberFromLists (MemberDef * md) [virtual]
Implements ClassDefMutable.
requiresClause() [1/2]
QCString ClassDefImpl::requiresClause () const [virtual]
Implements ClassDef.
Definition at line 3249 of file classdef.cpp.
{
  return m_impl->requiresClause;
}
References m_impl, and ClassDefImpl::IMPL::requiresClause.
requiresClause() [2/2]
virtual QCString ClassDefImpl::requiresClause () const [virtual]
Implements ClassDef.
resolveAlias() [1/2]
virtual ClassDef * ClassDefImpl::resolveAlias () [inline], [virtual]
Definition at line 160 of file classdef.cpp.
{ return this; }
resolveAlias() [2/2]
virtual ClassDef * ClassDefImpl::resolveAlias () [inline], [virtual]
Definition at line 160 of file classdef.cpp.
{ return this; }
setAnonymousEnumType() [1/2]
void ClassDefImpl::setAnonymousEnumType () [virtual]
Implements ClassDefMutable.
Definition at line 4289 of file classdef.cpp.
{
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd)
      {
        MemberList * ml = getMemberList(lmd->type);
        if (ml)
        {
          ml->setAnonymousEnumType();
        }
      }
    }
    else if (lde->kind()==LayoutDocEntry::MemberGroups)
    {
      for (const auto &mg : m_impl->memberGroups)
      {
        mg->setAnonymousEnumType();
      }
    }
  }
}
References LayoutDocManager::Class, getMemberList(), LayoutDocManager::instance(), m_impl, LayoutDocEntry::MemberDecl, ClassDefImpl::IMPL::memberGroups, LayoutDocEntry::MemberGroups, MemberList::setAnonymousEnumType(), and LayoutDocEntryMemberDecl::type.
setAnonymousEnumType() [2/2]
virtual void ClassDefImpl::setAnonymousEnumType () [virtual]
Implements ClassDefMutable.
setCategoryOf() [1/2]
void ClassDefImpl::setCategoryOf (ClassDef * cd) [virtual]
Implements ClassDefMutable.
Definition at line 4779 of file classdef.cpp.
{
  m_impl->categoryOf = cd;
}
References ClassDefImpl::IMPL::categoryOf, and m_impl.
setCategoryOf() [2/2]
virtual void ClassDefImpl::setCategoryOf (ClassDef * cd) [virtual]
Implements ClassDefMutable.
setClassName() [1/2]
void ClassDefImpl::setClassName (const QCString & name) [virtual]
Implements ClassDefMutable.
Definition at line 4139 of file classdef.cpp.
{
  m_impl->className = name;
}
References ClassDefImpl::IMPL::className, m_impl, and DefinitionMixin< ClassDefMutable >::name().
setClassName() [2/2]
virtual void ClassDefImpl::setClassName (const QCString & name) [virtual]
Implements ClassDefMutable.
setClassSpecifier() [1/2]
void ClassDefImpl::setClassSpecifier (uint64 spec) [virtual]
Implements ClassDefMutable.
Definition at line 4885 of file classdef.cpp.
{
  m_impl->spec = spec;
}
References m_impl, and ClassDefImpl::IMPL::spec.
setClassSpecifier() [2/2]
virtual void ClassDefImpl::setClassSpecifier (uint64 spec) [virtual]
Implements ClassDefMutable.
setCompoundType() [1/2]
void ClassDefImpl::setCompoundType (CompoundType t) [virtual]
Implements ClassDefMutable.
Definition at line 4764 of file classdef.cpp.
{
  m_impl->compType = t;
}
References ClassDefImpl::IMPL::compType, and m_impl.
setCompoundType() [2/2]
virtual void ClassDefImpl::setCompoundType (CompoundType t) [virtual]
Implements ClassDefMutable.
setFileDef() [1/2]
void ClassDefImpl::setFileDef (FileDef * fd) [virtual]
Implements ClassDefMutable.
Definition at line 4744 of file classdef.cpp.
{
  m_impl->fileDef=fd;
}
References ClassDefImpl::IMPL::fileDef, and m_impl.
setFileDef() [2/2]
virtual void ClassDefImpl::setFileDef (FileDef * fd) [virtual]
Implements ClassDefMutable.
setGroupDefForAllMembers() [1/2]
void ClassDefImpl::setGroupDefForAllMembers (GroupDef * g, Grouping::GroupPri_t pri, const QCString & fileName, int startLine, bool hasDocs) [virtual]
Implements ClassDefMutable.
Definition at line 3938 of file classdef.cpp.
{
  gd->addClass(this);
  //printf("ClassDefImpl::setGroupDefForAllMembers(%s)\n",qPrint(gd->name()));
  for (auto &mni : m_impl->allMemberNameInfoLinkedMap)
  {
    for (auto &mi : *mni)
    {
      MemberDefMutable *md = toMemberDefMutable(mi->memberDef());
      if (md)
      {
        md->setGroupDef(gd,pri,fileName,startLine,hasDocs);
        gd->insertMember(md,TRUE);
        ClassDefMutable *innerClass = toClassDefMutable(md->getClassDefOfAnonymousType());
        if (innerClass) innerClass->setGroupDefForAllMembers(gd,pri,fileName,startLine,hasDocs);
      }
    }
  }
}
References GroupDef::addClass(), ClassDefImpl::IMPL::allMemberNameInfoLinkedMap, MemberDef::getClassDefOfAnonymousType(), GroupDef::insertMember(), m_impl, MemberDefMutable::setGroupDef(), ClassDefMutable::setGroupDefForAllMembers(), toClassDefMutable(), toMemberDefMutable(), and TRUE.
setGroupDefForAllMembers() [2/2]
virtual void ClassDefImpl::setGroupDefForAllMembers (GroupDef * g, Grouping::GroupPri_t pri, const QCString & fileName, int startLine, bool hasDocs) [virtual]
Implements ClassDefMutable.
setIncludeFile() [1/2]
void ClassDefImpl::setIncludeFile (FileDef * fd, const QCString & incName, bool local, bool force) [virtual]
Implements ClassDefMutable.
Definition at line 1227 of file classdef.cpp.
{
  //printf("ClassDefImpl::setIncludeFile(%p,%s,%d,%d)\n",fd,includeName,local,force);
  if (!m_impl->incInfo) m_impl->incInfo = std::make_unique<IncludeInfo>();
  if ((!includeName.isEmpty() && m_impl->incInfo->includeName.isEmpty()) ||
      (fd!=0 && m_impl->incInfo->fileDef==0)
     )
  {
    //printf("Setting file info\n");
    m_impl->incInfo->fileDef = fd;
    m_impl->incInfo->includeName = includeName;
    m_impl->incInfo->local = local;
  }
  if (force && !includeName.isEmpty())
  {
    m_impl->incInfo->includeName = includeName;
    m_impl->incInfo->local = local;
  }
}
References ClassDefImpl::IMPL::incInfo, QCString::isEmpty(), and m_impl.
setIncludeFile() [2/2]
virtual void ClassDefImpl::setIncludeFile (FileDef * fd, const QCString & incName, bool local, bool force) [virtual]
Implements ClassDefMutable.
setIsStatic() [1/2]
void ClassDefImpl::setIsStatic (bool b) [virtual]
Implements ClassDefMutable.
Definition at line 4759 of file classdef.cpp.
{
  m_impl->isStatic=b;
}
References b, ClassDefImpl::IMPL::isStatic, and m_impl.
setIsStatic() [2/2]
virtual void ClassDefImpl::setIsStatic (bool b) [virtual]
Implements ClassDefMutable.
setMetaData() [1/2]
void ClassDefImpl::setMetaData (const QCString & md) [virtual]
Implements ClassDefMutable.
Definition at line 4929 of file classdef.cpp.
{
  m_impl->metaData = md;
}
References m_impl, and ClassDefImpl::IMPL::metaData.
setMetaData() [2/2]
virtual void ClassDefImpl::setMetaData (const QCString & md) [virtual]
Implements ClassDefMutable.
setName() [1/2]
void ClassDefImpl::setName (const QCString & name) [virtual]
Sets a new name for the definition
Reimplemented from DefinitionMixin< ClassDefMutable >.
Definition at line 4924 of file classdef.cpp.
{
  DefinitionMixin::setName(name);
}
References DefinitionMixin< ClassDefMutable >::name(), and DefinitionMixin< Base >::setName().
setName() [2/2]
virtual void ClassDefImpl::setName (const QCString & name) [virtual]
Sets a new name for the definition
Reimplemented from DefinitionMixin< ClassDefMutable >.
setProtection() [1/2]
void ClassDefImpl::setProtection (Protection p) [virtual]
Implements ClassDefMutable.
Definition at line 4754 of file classdef.cpp.
{
  m_impl->prot=p;
}
References m_impl, p, and ClassDefImpl::IMPL::prot.
setProtection() [2/2]
virtual void ClassDefImpl::setProtection (Protection p) [virtual]
Implements ClassDefMutable.
setRequiresClause() [1/2]
void ClassDefImpl::setRequiresClause (const QCString & req) [virtual]
Implements ClassDefMutable.
Definition at line 3254 of file classdef.cpp.
{
  m_impl->requiresClause = req;
}
References m_impl, and ClassDefImpl::IMPL::requiresClause.
setRequiresClause() [2/2]
virtual void ClassDefImpl::setRequiresClause (const QCString & req) [virtual]
Implements ClassDefMutable.
setSubGrouping() [1/2]
void ClassDefImpl::setSubGrouping (bool enabled) [virtual]
Implements ClassDefMutable.
Definition at line 4749 of file classdef.cpp.
{
  m_impl->subGrouping = enabled;
}
References m_impl, and ClassDefImpl::IMPL::subGrouping.
setSubGrouping() [2/2]
virtual void ClassDefImpl::setSubGrouping (bool enabled) [virtual]
Implements ClassDefMutable.
setTagLessReference() [1/2]
void ClassDefImpl::setTagLessReference (const ClassDef * cd) [virtual]
Implements ClassDefMutable.
Definition at line 4867 of file classdef.cpp.
{
  m_impl->tagLessRef = cd;
}
References m_impl, and ClassDefImpl::IMPL::tagLessRef.
setTagLessReference() [2/2]
virtual void ClassDefImpl::setTagLessReference (const ClassDef * cd) [virtual]
Implements ClassDefMutable.
setTemplateArguments() [1/2]
void ClassDefImpl::setTemplateArguments (const ArgumentList & al) [virtual]
Implements ClassDefMutable.
Definition at line 3201 of file classdef.cpp.
{
  m_impl->tempArgs = al;
}
References m_impl, and ClassDefImpl::IMPL::tempArgs.
setTemplateArguments() [2/2]
virtual void ClassDefImpl::setTemplateArguments (const ArgumentList & al) [virtual]
Implements ClassDefMutable.
setTemplateBaseClassNames() [1/2]
void ClassDefImpl::setTemplateBaseClassNames (const TemplateNameMap & templateNames) [virtual]
Implements ClassDefMutable.
Definition at line 4031 of file classdef.cpp.
{
  m_impl->templBaseClassNames = templateNames;
}
References m_impl, and ClassDefImpl::IMPL::templBaseClassNames.
setTemplateBaseClassNames() [2/2]
virtual void ClassDefImpl::setTemplateBaseClassNames (const TemplateNameMap & templateNames) [virtual]
Implements ClassDefMutable.
setTemplateMaster() [1/2]
void ClassDefImpl::setTemplateMaster (const ClassDef * tm) [virtual]
Implements ClassDefMutable.
Definition at line 4769 of file classdef.cpp.
{
  m_impl->templateMaster=tm;
}
References m_impl, and ClassDefImpl::IMPL::templateMaster.
setTemplateMaster() [2/2]
virtual void ClassDefImpl::setTemplateMaster (const ClassDef * tm) [virtual]
Implements ClassDefMutable.
setTypeConstraints() [1/2]
void ClassDefImpl::setTypeConstraints (const ArgumentList & al) [virtual]
Implements ClassDefMutable.
Definition at line 3196 of file classdef.cpp.
{
  m_impl->typeConstraints = al;
}
References m_impl, and ClassDefImpl::IMPL::typeConstraints.
setTypeConstraints() [2/2]
virtual void ClassDefImpl::setTypeConstraints (const ArgumentList & al) [virtual]
Implements ClassDefMutable.
setUsedOnly() [1/2]
void ClassDefImpl::setUsedOnly (bool b) [virtual]
Implements ClassDefMutable.
Definition at line 4784 of file classdef.cpp.
{
  m_impl->usedOnly = b;
}
References b, m_impl, and ClassDefImpl::IMPL::usedOnly.
setUsedOnly() [2/2]
virtual void ClassDefImpl::setUsedOnly (bool b) [virtual]
Implements ClassDefMutable.
showUsedFiles() [1/2]
void ClassDefImpl::showUsedFiles (OutputList & ol) const [private]
Definition at line 1513 of file classdef.cpp.
{
  ol.pushGeneratorState();
  ol.disable(OutputGenerator::Man);
  ol.writeRuler();
  ol.pushGeneratorState();
    ol.disableAllBut(OutputGenerator::Docbook);
    ol.startParagraph();
    ol.parseText(generatedFromFiles());
    ol.endParagraph();
  ol.popGeneratorState();
  ol.disable(OutputGenerator::Docbook);
    ol.parseText(generatedFromFiles());
  ol.enable(OutputGenerator::Docbook);
  bool first=TRUE;
  for (const auto &fd : m_impl->files)
  {
    if (first)
    {
      first=FALSE;
      ol.startItemList();
    }
    ol.startItemListItem();
    QCString path=fd->getPath();
    if (Config_getBool(FULL_PATH_NAMES))
    {
      ol.docify(stripFromPath(path));
    }
    QCString fname = fd->name();
    if (!fd->getVersion().isEmpty()) // append version if available
    {
      fname += " (" + fd->getVersion() + ")";
    }
    // for HTML
    ol.pushGeneratorState();
    ol.disableAllBut(OutputGenerator::Html);
    if (fd->generateSourceFile())
    {
      ol.writeObjectLink(QCString(),fd->getSourceFileBase(),QCString(),fname);
    }
    else if (fd->isLinkable())
    {
      ol.writeObjectLink(fd->getReference(),fd->getOutputFileBase(),QCString(),fname);
    }
    else
    {
      ol.docify(fname);
    }
    ol.popGeneratorState();
    // for other output formats
    ol.pushGeneratorState();
    ol.disable(OutputGenerator::Html);
    if (fd->isLinkable())
    {
      ol.writeObjectLink(fd->getReference(),fd->getOutputFileBase(),QCString(),fname);
    }
    else
    {
      ol.docify(fname);
    }
    ol.popGeneratorState();
    ol.endItemListItem();
  }
  if (!first) ol.endItemList();
  ol.popGeneratorState();
}
References Config_getBool, OutputList::disable(), OutputList::disableAllBut(), OutputGenerator::Docbook, OutputList::docify(), OutputList::enable(), OutputList::endItemList(), OutputList::endItemListItem(), OutputList::endParagraph(), FALSE, ClassDefImpl::IMPL::files, generatedFromFiles(), OutputGenerator::Html, m_impl, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startItemList(), OutputList::startItemListItem(), OutputList::startParagraph(), stripFromPath(), TRUE, OutputList::writeObjectLink(), and OutputList::writeRuler().
Referenced by writeDocumentationContents().
showUsedFiles() [2/2]
void ClassDefImpl::showUsedFiles (OutputList & ol) const [private]
sortAllMembersList() [1/2]
void ClassDefImpl::sortAllMembersList () [virtual]
Implements ClassDefMutable.
Definition at line 4614 of file classdef.cpp.
{
  std::sort(m_impl->allMemberNameInfoLinkedMap.begin(),
            m_impl->allMemberNameInfoLinkedMap.end(),
            [](const auto &m1,const auto &m2)
            {
              return qstricmp(m1->memberName(),m2->memberName())<0;
            });
}
References ClassDefImpl::IMPL::allMemberNameInfoLinkedMap, LinkedMap< T, Hash, KeyEqual, Map >::begin(), LinkedMap< T, Hash, KeyEqual, Map >::end(), and m_impl.
sortAllMembersList() [2/2]
virtual void ClassDefImpl::sortAllMembersList () [virtual]
Implements ClassDefMutable.
sortMemberLists() [1/2]
void ClassDefImpl::sortMemberLists () [virtual]
Implements ClassDefMutable.
Definition at line 4235 of file classdef.cpp.
{
  for (auto &ml : m_impl->memberLists)
  {
    if (ml->needsSorting()) { ml->sort(); ml->setNeedsSorting(FALSE); }
  }
  std::sort(m_impl->innerClasses.begin(),
            m_impl->innerClasses.end(),
            [](const auto &c1,const auto &c2)
            {
               return Config_getBool(SORT_BY_SCOPE_NAME) ?
                      qstricmp(c1->name(), c2->name())<0 :
                      qstricmp(c1->className(), c2->className())<0 ;
            });
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::begin(), LinkedRefMap< T, Hash, KeyEqual, Map >::end(), FALSE, ClassDefImpl::IMPL::innerClasses, m_impl, and ClassDefImpl::IMPL::memberLists.
sortMemberLists() [2/2]
virtual void ClassDefImpl::sortMemberLists () [virtual]
Implements ClassDefMutable.
startMemberDeclarations() [1/2]
void ClassDefImpl::startMemberDeclarations (OutputList & ol) const [private]
Definition at line 1989 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::startMemberDeclarations()\n",qPrint(name()));
  ol.startMemberSections();
}
References OutputList::startMemberSections().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
startMemberDeclarations() [2/2]
void ClassDefImpl::startMemberDeclarations (OutputList & ol) const [private]
startMemberDocumentation() [1/2]
void ClassDefImpl::startMemberDocumentation (OutputList & ol) const [private]
Definition at line 1969 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::startMemberDocumentation()\n",qPrint(name()));
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.disable(OutputGenerator::Html);
    Doxygen::suppressDocWarnings = TRUE;
  }
}
References Config_getBool, OutputList::disable(), OutputGenerator::Html, Doxygen::suppressDocWarnings, and TRUE.
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
startMemberDocumentation() [2/2]
void ClassDefImpl::startMemberDocumentation (OutputList & ol) const [private]
subClasses() [1/2]
const BaseClassList & ClassDefImpl::subClasses () const [virtual]
Returns the list of sub classes that directly derive from this class
Implements ClassDef.
Definition at line 4599 of file classdef.cpp.
{
  return m_impl->inheritedBy;
}
References ClassDefImpl::IMPL::inheritedBy, and m_impl.
Referenced by isSubClass().
subClasses() [2/2]
virtual const BaseClassList & ClassDefImpl::subClasses () const [virtual]
Returns the list of sub classes that directly derive from this class
Implements ClassDef.
subGrouping() [1/2]
bool ClassDefImpl::subGrouping () const [virtual]
Implements ClassDef.
Definition at line 4914 of file classdef.cpp.
{
  return m_impl->subGrouping;
}
References m_impl, and ClassDefImpl::IMPL::subGrouping.
subGrouping() [2/2]
virtual bool ClassDefImpl::subGrouping () const [virtual]
Implements ClassDef.
tagLessReference() [1/2]
const ClassDef * ClassDefImpl::tagLessReference () const [virtual]
Implements ClassDef.
Definition at line 4862 of file classdef.cpp.
{
  return m_impl->tagLessRef;
}
References m_impl, and ClassDefImpl::IMPL::tagLessRef.
tagLessReference() [2/2]
virtual const ClassDef * ClassDefImpl::tagLessReference () const [virtual]
Implements ClassDef.
templateArguments() [1/2]
const ArgumentList & ClassDefImpl::templateArguments () const [virtual]
Returns the template arguments of this class
Implements ClassDef.
Definition at line 4629 of file classdef.cpp.
{
  return m_impl->tempArgs;
}
References m_impl, and ClassDefImpl::IMPL::tempArgs.
Referenced by addMembersToTemplateInstance(), and getTemplateParameterLists().
templateArguments() [2/2]
virtual const ArgumentList & ClassDefImpl::templateArguments () const [virtual]
Returns the template arguments of this class
Implements ClassDef.
templateMaster() [1/2]
const ClassDef * ClassDefImpl::templateMaster () const [virtual]
Returns the template master of which this class is an instance. Returns 0 if not applicable.
Implements ClassDef.
Definition at line 4649 of file classdef.cpp.
{
  return m_impl->templateMaster;
}
References m_impl, and ClassDefImpl::IMPL::templateMaster.
templateMaster() [2/2]
virtual const ClassDef * ClassDefImpl::templateMaster () const [virtual]
Returns the template master of which this class is an instance. Returns 0 if not applicable.
Implements ClassDef.
templateTypeConstraints() [1/2]
const ConstraintClassList & ClassDefImpl::templateTypeConstraints () const [virtual]
Implements ClassDef.
Definition at line 4674 of file classdef.cpp.
{
  return m_impl->constraintClassList;
}
References ClassDefImpl::IMPL::constraintClassList, and m_impl.
templateTypeConstraints() [2/2]
virtual const ConstraintClassList & ClassDefImpl::templateTypeConstraints () const [virtual]
Implements ClassDef.
title() [1/2]
QCString ClassDefImpl::title () const [virtual]
Implements ClassDef.
Definition at line 2640 of file classdef.cpp.
{
  QCString pageTitle;
  SrcLangExt lang = getLanguage();
  if (lang==SrcLangExt_Fortran)
  {
    pageTitle = theTranslator->trCompoundReferenceFortran(displayName(),
              m_impl->compType,
              !m_impl->tempArgs.empty());
  }
  else if (lang==SrcLangExt_Slice)
  {
    pageTitle = theTranslator->trCompoundReferenceSlice(displayName(),
              m_impl->compType,
              isSliceLocal());
  }
  else if (lang==SrcLangExt_VHDL)
  {
    pageTitle = theTranslator->trCustomReference(VhdlDocGen::getClassTitle(this));
  }
  else if (isJavaEnum())
  {
    pageTitle = theTranslator->trEnumReference(displayName());
  }
  else if (m_impl->compType==Service)
  {
    pageTitle = theTranslator->trServiceReference(displayName());
  }
  else if (m_impl->compType==Singleton)
  {
    pageTitle = theTranslator->trSingletonReference(displayName());
  }
  else
  {
    if (Config_getBool(HIDE_COMPOUND_REFERENCE))
    {
      pageTitle = displayName();
    }
    else
    {
      pageTitle = theTranslator->trCompoundReference(displayName(),
                m_impl->compType == Interface && getLanguage()==SrcLangExt_ObjC ? Class : m_impl->compType,
                !m_impl->tempArgs.empty());
    }
  }
  return pageTitle;
}
References ClassDefImpl::IMPL::compType, Config_getBool, displayName(), ArgumentList::empty(), VhdlDocGen::getClassTitle(), DefinitionMixin< ClassDefMutable >::getLanguage(), isJavaEnum(), isSliceLocal(), m_impl, ClassDef::Service, ClassDef::Singleton, SrcLangExt_Fortran, SrcLangExt_ObjC, SrcLangExt_Slice, SrcLangExt_VHDL, ClassDefImpl::IMPL::tempArgs, theTranslator, Translator::trCompoundReference(), Translator::trCompoundReferenceFortran(), Translator::trCompoundReferenceSlice(), Translator::trCustomReference(), Translator::trEnumReference(), Translator::trServiceReference(), and Translator::trSingletonReference().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), getTitleForMemberListType(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), internalInsertMember(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), writeDetailedDescription(), writeDocumentation(), writeInheritedMemberDeclarations(), writeMemberDeclarations(), writeMemberDocumentation(), and writeNestedClasses().
title() [2/2]
virtual QCString ClassDefImpl::title () const [virtual]
Implements ClassDef.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
typeConstraints() [1/2]
const ArgumentList & ClassDefImpl::typeConstraints () const [virtual]
Implements ClassDef.
Definition at line 4904 of file classdef.cpp.
{
  return m_impl->typeConstraints;
}
References m_impl, and ClassDefImpl::IMPL::typeConstraints.
typeConstraints() [2/2]
virtual const ArgumentList & ClassDefImpl::typeConstraints () const [virtual]
Implements ClassDef.
updateBaseClasses() [1/2]
void ClassDefImpl::updateBaseClasses (const BaseClassList & bcd) [virtual]
Update the list of base classes to the one passed
Implements ClassDef.
Definition at line 4594 of file classdef.cpp.
{
  m_impl->inherits = bcd;
}
References ClassDefImpl::IMPL::inherits, and m_impl.
updateBaseClasses() [2/2]
virtual void ClassDefImpl::updateBaseClasses (const BaseClassList & bcd) [virtual]
Update the list of base classes to the one passed
Implements ClassDef.
updateSubClasses() [1/2]
void ClassDefImpl::updateSubClasses (const BaseClassList & bcd) [virtual]
Update the list of sub classes to the one passed
Implements ClassDef.
Definition at line 4604 of file classdef.cpp.
{
  m_impl->inheritedBy = bcd;
}
References ClassDefImpl::IMPL::inheritedBy, and m_impl.
updateSubClasses() [2/2]
virtual void ClassDefImpl::updateSubClasses (const BaseClassList & bcd) [virtual]
Update the list of sub classes to the one passed
Implements ClassDef.
usedByImplementationClasses() [1/2]
const UsesClassList & ClassDefImpl::usedByImplementationClasses () const [virtual]
Implements ClassDef.
Definition at line 4669 of file classdef.cpp.
{
  return m_impl->usedByImplClassList;
}
References m_impl, and ClassDefImpl::IMPL::usedByImplClassList.
usedByImplementationClasses() [2/2]
virtual const UsesClassList & ClassDefImpl::usedByImplementationClasses () const [virtual]
Implements ClassDef.
usedFiles() [1/2]
const FileList & ClassDefImpl::usedFiles () const [virtual]
Implements ClassDef.
Definition at line 4899 of file classdef.cpp.
{
  return m_impl->files;
}
References ClassDefImpl::IMPL::files, and m_impl.
usedFiles() [2/2]
virtual const FileList & ClassDefImpl::usedFiles () const [virtual]
Implements ClassDef.
usedImplementationClasses() [1/2]
const UsesClassList & ClassDefImpl::usedImplementationClasses () const [virtual]
Implements ClassDef.
Definition at line 4664 of file classdef.cpp.
{
  return m_impl->usesImplClassList;
}
References m_impl, and ClassDefImpl::IMPL::usesImplClassList.
usedImplementationClasses() [2/2]
virtual const UsesClassList & ClassDefImpl::usedImplementationClasses () const [virtual]
Implements ClassDef.
visibleInParentsDeclList() [1/2]
bool ClassDefImpl::visibleInParentsDeclList () const [virtual]
show this class in the declaration section of its parent?
Implements ClassDef.
Definition at line 2351 of file classdef.cpp.
{
  bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
  bool hideUndocClasses = Config_getBool(HIDE_UNDOC_CLASSES);
  bool extractLocalClasses = Config_getBool(EXTRACT_LOCAL_CLASSES);
  bool linkable = isLinkable();
  return (!isAnonymous() && !isExtension() &&
          (protection()!=::Private || extractPrivate) &&
          (linkable || (!hideUndocClasses && (!isLocal() || extractLocalClasses)))
         );
}
References Config_getBool, DefinitionMixin< ClassDefMutable >::isAnonymous(), isExtension(), isLinkable(), isLocal(), Private, and protection().
Referenced by writeDeclarationLink().
visibleInParentsDeclList() [2/2]
virtual bool ClassDefImpl::visibleInParentsDeclList () const [virtual]
show this class in the declaration section of its parent?
Implements ClassDef.
writeAdditionalInheritedMembers() [1/2]
void ClassDefImpl::writeAdditionalInheritedMembers (OutputList & ol) const [private]
Definition at line 4403 of file classdef.cpp.
{
  //printf("**** writeAdditionalInheritedMembers()\n");
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd && lmd->type!=MemberListType_friends)
      {
        ClassDefSet visited;
        writeInheritedMemberDeclarations(ol,visited,lmd->type,-1,lmd->title(getLanguage()),this,TRUE,FALSE);
      }
    }
  }
}
References LayoutDocManager::Class, FALSE, DefinitionMixin< ClassDefMutable >::getLanguage(), LayoutDocManager::instance(), LayoutDocEntry::MemberDecl, MemberListType_friends, LayoutDocEntryMemberDecl::title(), TRUE, LayoutDocEntryMemberDecl::type, and writeInheritedMemberDeclarations().
Referenced by endMemberDeclarations().
writeAdditionalInheritedMembers() [2/2]
void ClassDefImpl::writeAdditionalInheritedMembers (OutputList & ol) const [private]
writeAuthorSection() [1/2]
void ClassDefImpl::writeAuthorSection (OutputList & ol) const [private]
Definition at line 2009 of file classdef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Man);
  ol.writeString("\n");
  ol.startGroupHeader();
  ol.parseText(theTranslator->trAuthor(TRUE,TRUE));
  ol.endGroupHeader();
  ol.parseText(theTranslator->trGeneratedAutomatically(Config_getString(PROJECT_NAME)));
  ol.popGeneratorState();
}
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), TRUE, and OutputList::writeString().
Referenced by writeDocumentationContents().
writeAuthorSection() [2/2]
void ClassDefImpl::writeAuthorSection (OutputList & ol) const [private]
writeBriefDescription() [1/2]
void ClassDefImpl::writeBriefDescription (OutputList & ol, bool exampleFlag) const [private]
Definition at line 1357 of file classdef.cpp.
{
  if (hasBriefDescription())
  {
    ol.startParagraph();
    ol.pushGeneratorState();
    ol.disableAllBut(OutputGenerator::Man);
    ol.writeString(" - ");
    ol.popGeneratorState();
    ol.generateDoc(briefFile(),briefLine(),this,0,
                   briefDescription(),TRUE,FALSE,QCString(),
                   TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    ol.pushGeneratorState();
    ol.disable(OutputGenerator::RTF);
    ol.writeString(" \n");
    ol.enable(OutputGenerator::RTF);
    ol.popGeneratorState();
    if (hasDetailedDescription() || exampleFlag)
    {
      writeMoreLink(ol,anchor());
    }
    ol.endParagraph();
  }
  ol.writeSynopsis();
}
References anchor(), DefinitionMixin< ClassDefMutable >::briefDescription(), DefinitionMixin< ClassDefMutable >::briefFile(), DefinitionMixin< ClassDefMutable >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), OutputList::enable(), OutputList::endParagraph(), FALSE, OutputList::generateDoc(), DefinitionMixin< ClassDefMutable >::hasBriefDescription(), hasDetailedDescription(), OutputGenerator::Man, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startParagraph(), TRUE, writeMoreLink(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentationContents().
writeBriefDescription() [2/2]
void ClassDefImpl::writeBriefDescription (OutputList & ol, bool exampleFlag) const [private]
writeCollaborationGraph() [1/2]
void ClassDefImpl::writeCollaborationGraph (OutputList & ol) const [private]
Definition at line 1719 of file classdef.cpp.
{
  if (Config_getBool(HAVE_DOT) /*&& Config_getBool(COLLABORATION_GRAPH)*/)
  {
    DotClassGraph usageImplGraph(this,Collaboration);
    if (!usageImplGraph.isTrivial())
    {
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::Man);
      ol.startDotGraph();
      ol.parseText(theTranslator->trCollaborationDiagram(displayName()));
      ol.endDotGraph(usageImplGraph);
      ol.popGeneratorState();
    }
  }
}
References Collaboration, Config_getBool, OutputList::disable(), displayName(), OutputList::endDotGraph(), DotClassGraph::isTrivial(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startDotGraph(), theTranslator, and Translator::trCollaborationDiagram().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeCollaborationGraph() [2/2]
void ClassDefImpl::writeCollaborationGraph (OutputList & ol) const [private]
writeDeclaration() [1/2]
void ClassDefImpl::writeDeclaration (OutputList & ol, const MemberDef * md, bool inGroup, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const [virtual]
called from MemberDef::writeDeclaration() to (recursively) write the definition of an anonymous struct, union or class.
Implements ClassDefMutable.
Definition at line 3262 of file classdef.cpp.
{
  //printf("ClassName='%s' inGroup=%d\n",qPrint(name()),inGroup);
  ol.docify(compoundTypeString());
  QCString cn = displayName(FALSE);
  if (!cn.isEmpty())
  {
    ol.docify(" ");
    if (md && isLinkable())
    {
      ol.writeObjectLink(QCString(),QCString(),md->anchor(),cn);
    }
    else
    {
      ol.startBold();
      ol.docify(cn);
      ol.endBold();
    }
  }
  ol.docify(" {");
  ol.endMemberItem();
  // write user defined member groups
  for (const auto &mg : m_impl->memberGroups)
  {
    mg->writePlainDeclarations(ol,inGroup,this,0,0,0,indentLevel,inheritedFrom,inheritId);
  }
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd)
      {
        writePlainMemberDeclaration(ol,lmd->type,inGroup,indentLevel,inheritedFrom,inheritId);
      }
    }
  }
}
References MemberDef::anchor(), LayoutDocManager::Class, compoundTypeString(), displayName(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberItem(), FALSE, LayoutDocManager::instance(), QCString::isEmpty(), isLinkable(), m_impl, LayoutDocEntry::MemberDecl, ClassDefImpl::IMPL::memberGroups, OutputList::startBold(), LayoutDocEntryMemberDecl::type, OutputList::writeObjectLink(), and writePlainMemberDeclaration().
writeDeclaration() [2/2]
virtual void ClassDefImpl::writeDeclaration (OutputList & ol, const MemberDef * md, bool inGroup, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const [virtual]
Implements ClassDefMutable.
writeDeclarationLink() [1/2]
void ClassDefImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const [virtual]
Implements ClassDef.
Definition at line 2363 of file classdef.cpp.
{
  //bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  //bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
  SrcLangExt lang = getLanguage();
  if (visibleInParentsDeclList())
  {
    if (!found) // first class
    {
      if (sliceOpt)
      {
        if (compoundType()==Interface)
        {
          ol.startMemberHeader("interfaces");
        }
        else if (compoundType()==Struct)
        {
          ol.startMemberHeader("structs");
        }
        else if (compoundType()==Exception)
        {
          ol.startMemberHeader("exceptions");
        }
        else // compoundType==Class
        {
          ol.startMemberHeader("nested-classes");
        }
      }
      else // non-Slice optimization: single header for class/struct/..
      {
        ol.startMemberHeader("nested-classes");
      }
      if (!header.isEmpty())
      {
        ol.parseText(header);
      }
      else if (lang==SrcLangExt_VHDL)
      {
        ol.parseText(theTranslator->trVhdlType(VhdlDocGen::ARCHITECTURE,FALSE));
      }
      else
      {
        ol.parseText(lang==SrcLangExt_Fortran ?
            theTranslator->trDataTypes() :
            theTranslator->trCompounds());
      }
      ol.endMemberHeader();
      ol.startMemberList();
      found=TRUE;
    }
    ol.startMemberDeclaration();
    ol.startMemberItem(anchor(),FALSE);
    QCString ctype = compoundTypeString();
    QCString cname = displayName(!localNames);
    if (lang!=SrcLangExt_VHDL) // for VHDL we swap the name and the type
    {
      if (isSliceLocal())
      {
        ol.writeString("local ");
      }
      ol.writeString(ctype);
      ol.writeString(" ");
      ol.insertMemberAlign();
    }
    if (isLinkable())
    {
      ol.writeObjectLink(getReference(),
          getOutputFileBase(),
          anchor(),
          cname
          );
    }
    else
    {
      ol.startBold();
      ol.docify(cname);
      ol.endBold();
    }
    if (lang==SrcLangExt_VHDL) // now write the type
    {
      ol.writeString(" ");
      ol.insertMemberAlign();
      ol.writeString(VhdlDocGen::getProtectionName(VhdlDocGen::convert(protection())));
    }
    ol.endMemberItem();
    // add the brief description if available
    if (!briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
    {
      auto parser { createDocParser() };
      auto ast { validatingParseDoc(*parser.get(),
                                briefFile(),briefLine(),this,0,
                                briefDescription(),FALSE,FALSE,
                                QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
      if (!ast->isEmpty())
      {
        ol.startMemberDescription(anchor());
        ol.writeDoc(ast.get(),this,0);
        if (isLinkableInProject())
        {
          writeMoreLink(ol,anchor());
        }
        ol.endMemberDescription();
      }
    }
    ol.endMemberDeclaration(anchor(),QCString());
  }
}
References anchor(), VhdlDocGen::ARCHITECTURE, DefinitionMixin< ClassDefMutable >::briefDescription(), DefinitionMixin< ClassDefMutable >::briefFile(), DefinitionMixin< ClassDefMutable >::briefLine(), compoundType(), compoundTypeString(), Config_getBool, VhdlDocGen::convert(), createDocParser(), displayName(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), ClassDef::Exception, FALSE, found, DefinitionMixin< ClassDefMutable >::getLanguage(), getOutputFileBase(), VhdlDocGen::getProtectionName(), getReference(), OutputList::insertMemberAlign(), QCString::isEmpty(), isLinkable(), isLinkableInProject(), isSliceLocal(), OutputList::parseText(), protection(), SrcLangExt_Fortran, SrcLangExt_VHDL, OutputList::startBold(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), ClassDef::Struct, theTranslator, Translator::trCompounds(), Translator::trDataTypes(), TRUE, Translator::trVhdlType(), validatingParseDoc(), visibleInParentsDeclList(), OutputList::writeDoc(), writeMoreLink(), OutputList::writeObjectLink(), and OutputList::writeString().
writeDeclarationLink() [2/2]
virtual void ClassDefImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const [virtual]
Implements ClassDef.
writeDetailedDescription() [1/2]
void ClassDefImpl::writeDetailedDescription (OutputList & ol, const QCString & pageType, bool exampleFlag, const QCString & title, const QCString & anchor = QCString()) const [private]
Definition at line 1445 of file classdef.cpp.
{
  if (hasDetailedDescription() || exampleFlag)
  {
    ol.pushGeneratorState();
      ol.disable(OutputGenerator::Html);
      ol.writeRuler();
    ol.popGeneratorState();
    ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Html);
      ol.writeAnchor(QCString(),anchor.isEmpty() ? QCString("details") : anchor);
    ol.popGeneratorState();
    if (!anchor.isEmpty())
    {
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::Html);
      ol.disable(OutputGenerator::Man);
      ol.writeAnchor(getOutputFileBase(),anchor);
      ol.popGeneratorState();
    }
    ol.startGroupHeader();
    ol.parseText(title);
    ol.endGroupHeader();
    writeDetailedDocumentationBody(ol);
  }
  else
  {
    //writeTemplateSpec(ol,this,pageType);
  }
}
References anchor(), OutputList::disable(), OutputList::disableAllBut(), OutputList::endGroupHeader(), getOutputFileBase(), hasDetailedDescription(), OutputGenerator::Html, QCString::isEmpty(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), title(), OutputList::writeAnchor(), writeDetailedDocumentationBody(), and OutputList::writeRuler().
Referenced by writeDocumentationContents().
writeDetailedDescription() [2/2]
void ClassDefImpl::writeDetailedDescription (OutputList & ol, const QCString & pageType, bool exampleFlag, const QCString & title, const QCString & anchor = QCString()) const [private]
writeDetailedDocumentationBody() [1/2]
void ClassDefImpl::writeDetailedDocumentationBody (OutputList & ol) const [private]
Definition at line 1385 of file classdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  ol.startTextBlock();
  if (getLanguage()==SrcLangExt_Cpp)
  {
    writeTemplateSpec(ol,this,compoundTypeString(),getLanguage());
  }
  // repeat brief description
  if (!briefDescription().isEmpty() && repeatBrief)
  {
    ol.generateDoc(briefFile(),briefLine(),this,0,briefDescription(),FALSE,FALSE,
                   QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
  }
  if (!briefDescription().isEmpty() && repeatBrief &&
      !documentation().isEmpty())
  {
    ol.pushGeneratorState();
    ol.disable(OutputGenerator::Html);
    ol.writeString("\n\n");
    ol.popGeneratorState();
  }
  // write documentation
  if (!documentation().isEmpty())
  {
    ol.generateDoc(docFile(),docLine(),this,0,documentation(),TRUE,FALSE,
                   QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
  }
  // write type constraints
  writeTypeConstraints(ol,this,m_impl->typeConstraints);
  // write examples
  if (hasExamples())
  {
    ol.startExamples();
    ol.startDescForItem();
    //ol.startParagraph();
    writeExamples(ol,m_impl->examples);
    //ol.endParagraph();
    ol.endDescForItem();
    ol.endExamples();
  }
  //ol.newParagraph();
  writeSourceDef(ol,name());
  ol.endTextBlock();
}
References DefinitionMixin< ClassDefMutable >::briefDescription(), DefinitionMixin< ClassDefMutable >::briefFile(), DefinitionMixin< ClassDefMutable >::briefLine(), compoundTypeString(), Config_getBool, OutputList::disable(), DefinitionMixin< ClassDefMutable >::docFile(), DefinitionMixin< ClassDefMutable >::docLine(), DefinitionMixin< ClassDefMutable >::documentation(), OutputList::endDescForItem(), OutputList::endExamples(), OutputList::endTextBlock(), ClassDefImpl::IMPL::examples, FALSE, OutputList::generateDoc(), DefinitionMixin< ClassDefMutable >::getLanguage(), hasExamples(), OutputGenerator::Html, m_impl, DefinitionMixin< ClassDefMutable >::name(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), SrcLangExt_Cpp, OutputList::startDescForItem(), OutputList::startExamples(), OutputList::startTextBlock(), TRUE, ClassDefImpl::IMPL::typeConstraints, writeExamples(), DefinitionMixin< ClassDefMutable >::writeSourceDef(), OutputList::writeString(), writeTemplateSpec(), and writeTypeConstraints().
Referenced by writeDetailedDescription(), and writeInlineDocumentation().
writeDetailedDocumentationBody() [2/2]
void ClassDefImpl::writeDetailedDocumentationBody (OutputList & ol) const [private]
writeDocumentation() [1/2]
void ClassDefImpl::writeDocumentation (OutputList & ol) const [virtual]
Implements ClassDefMutable.
Definition at line 2690 of file classdef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  //bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  //bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
  QCString pageTitle = title();
  HighlightedItem hli;
  if (sliceOpt)
  {
    if (compoundType()==Interface)
    {
      hli = HLI_InterfaceVisible;
    }
    else if (compoundType()==Struct)
    {
      hli = HLI_StructVisible;
    }
    else if (compoundType()==Exception)
    {
      hli = HLI_ExceptionVisible;
    }
    else
    {
      hli = HLI_ClassVisible;
    }
  }
  else
  {
    hli = HLI_ClassVisible;
  }
  startFile(ol,getOutputFileBase(),name(),pageTitle,hli,!generateTreeView);
  if (!generateTreeView)
  {
    if (getOuterScope()!=Doxygen::globalScope)
    {
      writeNavigationPath(ol);
    }
    ol.endQuickIndices();
  }
  startTitle(ol,getOutputFileBase(),this);
  ol.parseText(pageTitle);
  addClassAttributes(ol);
  addGroupListToTitle(ol,this);
  endTitle(ol,getOutputFileBase(),displayName());
  writeDocumentationContents(ol,pageTitle);
  endFileWithNavPath(this,ol);
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    writeMemberPages(ol);
  }
}
References addClassAttributes(), addGroupListToTitle(), compoundType(), Config_getBool, displayName(), endFileWithNavPath(), OutputList::endQuickIndices(), endTitle(), ClassDef::Exception, DefinitionMixin< ClassDefMutable >::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, HLI_ClassVisible, HLI_ExceptionVisible, HLI_InterfaceVisible, HLI_StructVisible, DefinitionMixin< ClassDefMutable >::name(), OutputList::parseText(), startFile(), startTitle(), ClassDef::Struct, title(), writeDocumentationContents(), writeMemberPages(), and DefinitionMixin< ClassDefMutable >::writeNavigationPath().
writeDocumentation() [2/2]
virtual void ClassDefImpl::writeDocumentation (OutputList & ol) const [virtual]
Implements ClassDefMutable.
writeDocumentationContents() [1/2]
void ClassDefImpl::writeDocumentationContents (OutputList & ol, const QCString & pageTitle) const [private]
Definition at line 2498 of file classdef.cpp.
{
  ol.startContents();
  QCString pageType = " ";
  pageType += compoundTypeString();
  bool exampleFlag=hasExamples();
  //---------------------------------------- start flexible part -------------------------------
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol,exampleFlag);
        break;
      case LayoutDocEntry::ClassIncludes:
        if (lang==SrcLangExt_Slice)
        {
          writeIncludeFilesForSlice(ol);
        }
        else
        {
          writeIncludeFiles(ol);
        }
        break;
      case LayoutDocEntry::ClassInheritanceGraph:
        writeInheritanceGraph(ol);
        break;
      case LayoutDocEntry::ClassCollaborationGraph:
        writeCollaborationGraph(ol);
        break;
      case LayoutDocEntry::ClassAllMembersLink:
        //writeAllMembersLink(ol); // this is now part of the summary links
        break;
      case LayoutDocEntry::MemberDeclStart:
        startMemberDeclarations(ol);
        break;
      case LayoutDocEntry::MemberGroups:
        writeMemberGroups(ol);
        break;
      case LayoutDocEntry::MemberDecl:
        {
          ClassDefSet visitedClasses;
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            writeMemberDeclarations(ol,visitedClasses,lmd->type,lmd->title(lang),lmd->subtitle(lang));
          }
        }
        break;
      case LayoutDocEntry::ClassNestedClasses:
        {
          const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
          if (ls)
          {
            writeNestedClasses(ol,ls->title(lang));
          }
        }
        break;
      case LayoutDocEntry::MemberDeclEnd:
        endMemberDeclarations(ol);
        break;
      case LayoutDocEntry::DetailedDesc:
        {
          const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
          if (ls)
          {
            writeDetailedDescription(ol,pageType,exampleFlag,ls->title(lang));
          }
        }
        break;
      case LayoutDocEntry::MemberDefStart:
        startMemberDocumentation(ol);
        break;
      case LayoutDocEntry::ClassInlineClasses:
        writeInlineClasses(ol);
        break;
      case LayoutDocEntry::MemberDef:
        {
          const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
          if (lmd)
          {
            writeMemberDocumentation(ol,lmd->type,lmd->title(lang));
          }
        }
        break;
      case LayoutDocEntry::MemberDefEnd:
        endMemberDocumentation(ol);
        break;
      case LayoutDocEntry::ClassUsedFiles:
        showUsedFiles(ol);
        break;
      case LayoutDocEntry::AuthorSection:
        writeAuthorSection(ol);
        break;
      case LayoutDocEntry::NamespaceNestedNamespaces:
      case LayoutDocEntry::NamespaceNestedConstantGroups:
      case LayoutDocEntry::NamespaceClasses:
      case LayoutDocEntry::NamespaceConcepts:
      case LayoutDocEntry::NamespaceInterfaces:
      case LayoutDocEntry::NamespaceStructs:
      case LayoutDocEntry::NamespaceExceptions:
      case LayoutDocEntry::NamespaceInlineClasses:
      case LayoutDocEntry::ConceptDefinition:
      case LayoutDocEntry::FileClasses:
      case LayoutDocEntry::FileConcepts:
      case LayoutDocEntry::FileInterfaces:
      case LayoutDocEntry::FileStructs:
      case LayoutDocEntry::FileExceptions:
      case LayoutDocEntry::FileNamespaces:
      case LayoutDocEntry::FileConstantGroups:
      case LayoutDocEntry::FileIncludes:
      case LayoutDocEntry::FileIncludeGraph:
      case LayoutDocEntry::FileIncludedByGraph:
      case LayoutDocEntry::FileSourceLink:
      case LayoutDocEntry::FileInlineClasses:
      case LayoutDocEntry::GroupClasses:
      case LayoutDocEntry::GroupConcepts:
      case LayoutDocEntry::GroupInlineClasses:
      case LayoutDocEntry::GroupNamespaces:
      case LayoutDocEntry::GroupDirs:
      case LayoutDocEntry::GroupNestedGroups:
      case LayoutDocEntry::GroupFiles:
      case LayoutDocEntry::GroupGraph:
      case LayoutDocEntry::GroupPageDocs:
      case LayoutDocEntry::DirSubDirs:
      case LayoutDocEntry::DirFiles:
      case LayoutDocEntry::DirGraph:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::Class entry list\n",lde->kind());
        break;
    }
  }
  ol.endContents();
}
References LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocManager::Class, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, compoundTypeString(), LayoutDocEntry::ConceptDefinition, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, OutputList::endContents(), endMemberDeclarations(), endMemberDocumentation(), err(), LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, LayoutDocEntry::FileStructs, DefinitionMixin< ClassDefMutable >::getLanguage(), LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, hasExamples(), LayoutDocManager::instance(), LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, LayoutDocEntry::NamespaceStructs, showUsedFiles(), SrcLangExt_Slice, OutputList::startContents(), startMemberDeclarations(), startMemberDocumentation(), LayoutDocEntryMemberDecl::subtitle(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeCollaborationGraph(), writeDetailedDescription(), writeIncludeFiles(), writeIncludeFilesForSlice(), writeInheritanceGraph(), writeInlineClasses(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), and writeNestedClasses().
Referenced by writeDocumentation().
writeDocumentationContents() [2/2]
void ClassDefImpl::writeDocumentationContents (OutputList & ol, const QCString & pageTitle) const [private]
writeDocumentationForInnerClasses() [1/2]
void ClassDefImpl::writeDocumentationForInnerClasses (OutputList & ol) const [virtual]
Implements ClassDefMutable.
Definition at line 2811 of file classdef.cpp.
{
  // write inner classes after the parent, so the tag files contain
  // the definition in proper order!
  for (const auto &innerCd : m_impl->innerClasses)
  {
    ClassDefMutable *innerCdm = toClassDefMutable(innerCd);
    if (innerCdm)
    {
      if (
          innerCd->isLinkableInProject() && innerCd->templateMaster()==0 &&
          protectionLevelVisible(innerCd->protection()) &&
          !innerCd->isEmbeddedInOuterScope()
         )
      {
        msg("Generating docs for nested compound %s...\n",qPrint(innerCd->name()));
        innerCdm->writeDocumentation(ol);
        innerCdm->writeMemberList(ol);
      }
      innerCdm->writeDocumentationForInnerClasses(ol);
    }
  }
}
References ClassDefImpl::IMPL::innerClasses, m_impl, msg(), protectionLevelVisible(), qPrint(), toClassDefMutable(), ClassDefMutable::writeDocumentation(), ClassDefMutable::writeDocumentationForInnerClasses(), and ClassDefMutable::writeMemberList().
writeDocumentationForInnerClasses() [2/2]
virtual void ClassDefImpl::writeDocumentationForInnerClasses (OutputList & ol) const [virtual]
Implements ClassDefMutable.
writeIncludeFiles() [1/2]
void ClassDefImpl::writeIncludeFiles (OutputList & ol) const [private]
Definition at line 1895 of file classdef.cpp.
{
  if (m_impl->incInfo /*&& Config_getBool(SHOW_HEADERFILE)*/)
  {
    SrcLangExt lang = getLanguage();
    QCString nm=m_impl->incInfo->includeName.isEmpty() ?
      (m_impl->incInfo->fileDef ?
       m_impl->incInfo->fileDef->docName() : QCString()
      ) :
      m_impl->incInfo->includeName;
    if (!nm.isEmpty())
    {
      ol.startParagraph();
      ol.startTypewriter();
      ol.docify(includeStatement());
      bool isIDLorJava = lang==SrcLangExt_IDL || lang==SrcLangExt_Java;
      if (m_impl->incInfo->local || isIDLorJava)
        ol.docify("\"");
      else
        ol.docify("<");
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::Html);
      ol.docify(nm);
      ol.disableAllBut(OutputGenerator::Html);
      ol.enable(OutputGenerator::Html);
      if (m_impl->incInfo->fileDef)
      {
        ol.writeObjectLink(QCString(),m_impl->incInfo->fileDef->includeName(),QCString(),nm);
      }
      else
      {
        ol.docify(nm);
      }
      ol.popGeneratorState();
      if (m_impl->incInfo->local || isIDLorJava)
        ol.docify("\"");
      else
        ol.docify(">");
      if (isIDLorJava)
        ol.docify(";");
      ol.endTypewriter();
      ol.endParagraph();
    }
  }
}
References OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTypewriter(), DefinitionMixin< ClassDefMutable >::getLanguage(), OutputGenerator::Html, if(), ClassDefImpl::IMPL::incInfo, includeStatement(), QCString::isEmpty(), m_impl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), SrcLangExt_IDL, SrcLangExt_Java, OutputList::startParagraph(), OutputList::startTypewriter(), and OutputList::writeObjectLink().
Referenced by writeDocumentationContents().
writeIncludeFiles() [2/2]
void ClassDefImpl::writeIncludeFiles (OutputList & ol) const [private]
writeIncludeFilesForSlice() [1/2]
void ClassDefImpl::writeIncludeFilesForSlice (OutputList & ol) const [private]
Definition at line 1754 of file classdef.cpp.
{
  if (m_impl->incInfo)
  {
    QCString nm;
    const StringVector &paths = Config_getList(STRIP_FROM_PATH);
    if (!paths.empty() && m_impl->incInfo->fileDef)
    {
      QCString abs = m_impl->incInfo->fileDef->absFilePath();
      QCString potential;
      unsigned int length = 0;
      for (const auto &s : paths)
      {
        FileInfo info(s);
        if (info.exists())
        {
          QCString prefix = info.absFilePath();
          if (prefix.at(prefix.length() - 1) != '/')
          {
            prefix += '/';
          }
          if (prefix.length() > length &&
              qstricmp(abs.left(prefix.length()).data(), prefix.data()) == 0) // case insensitive compare
          {
            length = prefix.length();
            potential = abs.right(abs.length() - prefix.length());
          }
        }
      }
      if (length > 0)
      {
        nm = potential;
      }
    }
    if (nm.isEmpty())
    {
      nm = m_impl->incInfo->includeName;
    }
    ol.startParagraph();
    ol.docify(theTranslator->trDefinedIn()+" ");
    ol.startTypewriter();
    ol.docify("<");
    if (m_impl->incInfo->fileDef)
    {
      ol.writeObjectLink(QCString(),m_impl->incInfo->fileDef->includeName(),QCString(),nm);
    }
    else
    {
      ol.docify(nm);
    }
    ol.docify(">");
    ol.endTypewriter();
    ol.endParagraph();
  }
  // Write a summary of the Slice definition including metadata.
  ol.startParagraph();
  ol.startTypewriter();
  if (!m_impl->metaData.isEmpty())
  {
    ol.docify(m_impl->metaData);
    ol.lineBreak();
  }
  if (m_impl->spec & Entry::Local)
  {
    ol.docify("local ");
  }
  if (m_impl->spec & Entry::Interface)
  {
    ol.docify("interface ");
  }
  else if (m_impl->spec & Entry::Struct)
  {
    ol.docify("struct ");
  }
  else if (m_impl->spec & Entry::Exception)
  {
    ol.docify("exception ");
  }
  else
  {
    ol.docify("class ");
  }
  ol.docify(stripScope(name()));
  if (!m_impl->inherits.empty())
  {
    if (m_impl->spec & (Entry::Interface|Entry::Exception))
    {
      ol.docify(" extends ");
      bool first=true;
      for (const auto &ibcd : m_impl->inherits)
      {
        if (!first) ol.docify(", ");
        ClassDef *icd = ibcd.classDef;
        ol.docify(icd->name());
        first=false;
      }
    }
    else
    {
      // Must be a class.
      bool implements = false;
      for (const auto &ibcd : m_impl->inherits)
      {
        ClassDef *icd = ibcd.classDef;
        if (icd->isInterface())
        {
          implements = true;
        }
        else
        {
          ol.docify(" extends ");
          ol.docify(icd->name());
        }
      }
      if (implements)
      {
        ol.docify(" implements ");
        bool first = true;
        for (const auto &ibcd : m_impl->inherits)
        {
          ClassDef *icd = ibcd.classDef;
          if (icd->isInterface())
          {
            if (!first) ol.docify(", ");
            first = false;
            ol.docify(icd->name());
          }
        }
      }
    }
  }
  ol.docify(" { ... }");
  ol.endTypewriter();
  ol.endParagraph();
}
References FileInfo::absFilePath(), QCString::at(), Config_getList, QCString::data(), OutputList::docify(), OutputList::endParagraph(), OutputList::endTypewriter(), Entry::Exception, FileInfo::exists(), ClassDefImpl::IMPL::incInfo, ClassDefImpl::IMPL::inherits, Entry::Interface, QCString::isEmpty(), ClassDef::isInterface(), QCString::left(), QCString::length(), OutputList::lineBreak(), Entry::Local, m_impl, ClassDefImpl::IMPL::metaData, DefinitionMixin< ClassDefMutable >::name(), Definition::name(), qstricmp(), QCString::right(), s, ClassDefImpl::IMPL::spec, OutputList::startParagraph(), OutputList::startTypewriter(), stripScope(), Entry::Struct, theTranslator, Translator::trDefinedIn(), and OutputList::writeObjectLink().
Referenced by writeDocumentationContents().
writeIncludeFilesForSlice() [2/2]
void ClassDefImpl::writeIncludeFilesForSlice (OutputList & ol) const [private]
writeInheritanceGraph() [1/2]
void ClassDefImpl::writeInheritanceGraph (OutputList & ol) const [private]
Definition at line 1605 of file classdef.cpp.
{
  bool haveDot = Config_getBool(HAVE_DOT);
  auto classGraph = Config_getEnum(CLASS_GRAPH);
  if (classGraph == CLASS_GRAPH_t::NO) return;
  // count direct inheritance relations
  const int count=countInheritanceNodes();
  bool renderDiagram = FALSE;
  if (haveDot && (classGraph==CLASS_GRAPH_t::YES || classGraph==CLASS_GRAPH_t::GRAPH))
    // write class diagram using dot
  {
    DotClassGraph inheritanceGraph(this,Inheritance);
    if (inheritanceGraph.isTooBig())
    {
       warn_uncond("Inheritance graph for '%s' not generated, too many nodes (%d), threshold is %d. Consider increasing DOT_GRAPH_MAX_NODES.\n",
           qPrint(name()), inheritanceGraph.numNodes(), Config_getInt(DOT_GRAPH_MAX_NODES));
    }
    else if (!inheritanceGraph.isTrivial())
    {
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::Man);
      ol.startDotGraph();
      ol.parseText(theTranslator->trClassDiagram(displayName()));
      ol.endDotGraph(inheritanceGraph);
      ol.popGeneratorState();
      renderDiagram = TRUE;
    }
  }
  else if ((classGraph==CLASS_GRAPH_t::YES || classGraph==CLASS_GRAPH_t::GRAPH) && count>0)
    // write class diagram using built-in generator
  {
    ClassDiagram diagram(this); // create a diagram of this class.
    ol.startClassDiagram();
    ol.disable(OutputGenerator::Man);
    ol.parseText(theTranslator->trClassDiagram(displayName()));
    ol.enable(OutputGenerator::Man);
    ol.endClassDiagram(diagram,getOutputFileBase(),displayName());
    renderDiagram = TRUE;
  }
  if (renderDiagram) // if we already show the inheritance relations graphically,
                     // then hide the text version
  {
    ol.disableAllBut(OutputGenerator::Man);
  }
  if (!m_impl->inherits.empty())
  {
    auto replaceFunc = [this,&ol](size_t entryIndex)
    {
      BaseClassDef &bcd=m_impl->inherits[entryIndex];
      ClassDef *cd=bcd.classDef;
      // use the class name but with the template arguments as given
      // in the inheritance relation
      QCString displayName = insertTemplateSpecifierInScope(
          cd->displayName(),bcd.templSpecifiers);
      if (cd->isLinkable())
      {
        ol.writeObjectLink(cd->getReference(),
            cd->getOutputFileBase(),
            cd->anchor(),
            displayName);
      }
      else
      {
        ol.docify(displayName);
      }
    };
    ol.startParagraph();
    writeMarkerList(ol,
                    theTranslator->trInheritsList(static_cast<int>(m_impl->inherits.size())).str(),
                    m_impl->inherits.size(),
                    replaceFunc);
    ol.endParagraph();
  }
  // write subclasses
  if (!m_impl->inheritedBy.empty())
  {
    auto replaceFunc = [this,&ol](size_t entryIndex)
    {
      BaseClassDef &bcd=m_impl->inheritedBy[entryIndex];
      ClassDef *cd=bcd.classDef;
      if (cd->isLinkable())
      {
        ol.writeObjectLink(cd->getReference(),cd->getOutputFileBase(),cd->anchor(),cd->displayName());
      }
      else
      {
        ol.docify(cd->displayName());
      }
      writeInheritanceSpecifier(ol,bcd);
    };
    ol.startParagraph();
    writeMarkerList(ol,
                    theTranslator->trInheritedByList(static_cast<int>(m_impl->inheritedBy.size())).str(),
                    m_impl->inheritedBy.size(),
                    replaceFunc);
    ol.endParagraph();
  }
  if (renderDiagram)
  {
    ol.enableAll();
  }
}
References ClassDef::anchor(), BaseClassDef::classDef, Config_getBool, Config_getEnum, Config_getInt, countInheritanceNodes(), OutputList::disable(), OutputList::disableAllBut(), displayName(), ClassDef::displayName(), OutputList::docify(), OutputList::enable(), OutputList::enableAll(), OutputList::endClassDiagram(), OutputList::endDotGraph(), OutputList::endParagraph(), FALSE, getOutputFileBase(), ClassDef::getOutputFileBase(), ClassDef::getReference(), Inheritance, ClassDefImpl::IMPL::inheritedBy, ClassDefImpl::IMPL::inherits, insertTemplateSpecifierInScope(), ClassDef::isLinkable(), DotClassGraph::isTooBig(), DotClassGraph::isTrivial(), m_impl, OutputGenerator::Man, DefinitionMixin< ClassDefMutable >::name(), DotClassGraph::numNodes(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), qPrint(), OutputList::startClassDiagram(), OutputList::startDotGraph(), OutputList::startParagraph(), QCString::str(), BaseClassDef::templSpecifiers, theTranslator, Translator::trClassDiagram(), Translator::trInheritedByList(), Translator::trInheritsList(), TRUE, warn_uncond(), writeInheritanceSpecifier(), writeMarkerList(), and OutputList::writeObjectLink().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeInheritanceGraph() [2/2]
void ClassDefImpl::writeInheritanceGraph (OutputList & ol) const [private]
writeInheritedMemberDeclarations() [1/2]
void ClassDefImpl::writeInheritedMemberDeclarations (OutputList & ol, ClassDefSet & visitedClasses, MemberListType lt, int lt2, const QCString & title, const ClassDef * inheritedFrom, bool invert, bool showAlways) const [private]
Definition at line 4445 of file classdef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  int count = countMembersIncludingGrouped(lt,inheritedFrom,FALSE);
  bool process = count>0;
  //printf("%s: writeInheritedMemberDec: lt=%d process=%d invert=%d always=%d\n",
  // qPrint(name()),lt,process,invert,showAlways);
  if ((process^invert) || showAlways)
  {
    for (const auto &ibcd : m_impl->inherits)
    {
      ClassDefMutable *icd=toClassDefMutable(ibcd.classDef);
      if (icd && icd->isLinkable())
      {
        int lt1,lt3;
        convertProtectionLevel(lt,ibcd.prot,&lt1,&lt3);
        if (lt2==-1 && lt3!=-1)
        {
          lt2=lt3;
        }
        //printf("%s:convert %d->(%d,%d) prot=%d\n",qPrint(icd->name()),lt,lt1,lt2,ibcd->prot);
        if (visitedClasses.find(icd)==visitedClasses.end())
        {
          visitedClasses.insert(icd); // guard for multiple virtual inheritance
          if (lt1!=-1)
          {
            icd->writeMemberDeclarations(ol,visitedClasses,static_cast<MemberListType>(lt1),
                title,QCString(),FALSE,inheritedFrom,lt2,FALSE,TRUE);
          }
        }
        else
        {
          //printf("%s: class already visited!\n",qPrint(icd->name()));
        }
      }
    }
  }
  ol.popGeneratorState();
}
References convertProtectionLevel(), countMembersIncludingGrouped(), OutputList::disableAllBut(), FALSE, OutputGenerator::Html, ClassDefImpl::IMPL::inherits, ClassDef::isLinkable(), m_impl, OutputList::popGeneratorState(), search::process(), OutputList::pushGeneratorState(), title(), toClassDefMutable(), TRUE, and ClassDefMutable::writeMemberDeclarations().
Referenced by writeAdditionalInheritedMembers(), and writeMemberDeclarations().
writeInheritedMemberDeclarations() [2/2]
void ClassDefImpl::writeInheritedMemberDeclarations (OutputList & ol, ClassDefSet & visitedClasses, MemberListType lt, int lt2, const QCString & title, const ClassDef * inheritedFrom, bool invert, bool showAlways) const [private]
writeInlineClasses() [1/2]
void ClassDefImpl::writeInlineClasses (OutputList & ol) const [private]
Definition at line 1964 of file classdef.cpp.
{
  m_impl->innerClasses.writeDocumentation(ol,this);
}
References ClassDefImpl::IMPL::innerClasses, m_impl, and ClassLinkedRefMap::writeDocumentation().
Referenced by writeDocumentationContents().
writeInlineClasses() [2/2]
void ClassDefImpl::writeInlineClasses (OutputList & ol) const [private]
writeInlineDocumentation() [1/2]
void ClassDefImpl::writeInlineDocumentation (OutputList & ol) const [virtual]
Write class documentation inside another container (i.e. a group)
Implements ClassDefMutable.
Definition at line 2186 of file classdef.cpp.
{
  bool isSimple = m_impl->isSimple;
  ol.addIndexItem(name(),QCString());
  //printf("ClassDefImpl::writeInlineDocumentation(%s)\n",qPrint(name()));
  // part 1: anchor and title
  QCString s = compoundTypeString()+" "+name();
  // part 1a
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  { // only HTML only
    ol.writeAnchor(QCString(),anchor());
    ol.startMemberDoc(QCString(),QCString(),anchor(),name(),1,1,FALSE);
    ol.startMemberDocName(FALSE);
    ol.parseText(s);
    ol.endMemberDocName();
    ol.endMemberDoc(FALSE);
    ol.writeString("</div>");
    ol.startIndent();
  }
  ol.popGeneratorState();
  // part 1b
  ol.pushGeneratorState();
  ol.disable(OutputGenerator::Html);
  ol.disable(OutputGenerator::Man);
  { // for LaTeX/RTF only
    ol.writeAnchor(getOutputFileBase(),anchor());
  }
  ol.popGeneratorState();
  // part 1c
  ol.pushGeneratorState();
  ol.disable(OutputGenerator::Html);
  {
    // for LaTeX/RTF/Man
    ol.startGroupHeader(1);
    ol.parseText(s);
    ol.endGroupHeader(1);
  }
  ol.popGeneratorState();
  SrcLangExt lang=getLanguage();
  // part 2: the header and detailed description
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        {
          // since we already shown the brief description in the
          // declaration part of the container, so we use this to
          // show the details on top.
          writeDetailedDocumentationBody(ol);
        }
        break;
      case LayoutDocEntry::ClassInheritanceGraph:
        writeInheritanceGraph(ol);
        break;
      case LayoutDocEntry::ClassCollaborationGraph:
        writeCollaborationGraph(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
        if (!isSimple) startMemberDeclarations(ol);
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            ClassDefSet visitedClasses;
            if (!isSimple) writeMemberDeclarations(ol,visitedClasses,lmd->type,lmd->title(lang),lmd->subtitle(lang),TRUE);
          }
        }
        break;
      case LayoutDocEntry::MemberGroups:
        if (!isSimple) writeMemberGroups(ol,TRUE);
        break;
      case LayoutDocEntry::MemberDeclEnd:
        if (!isSimple) endMemberDeclarations(ol);
        break;
      case LayoutDocEntry::MemberDefStart:
        if (!isSimple) startMemberDocumentation(ol);
        break;
      case LayoutDocEntry::MemberDef:
        {
          const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
          if (lmd)
          {
            if (isSimple)
            {
              writeSimpleMemberDocumentation(ol,lmd->type);
            }
            else
            {
              writeMemberDocumentation(ol,lmd->type,lmd->title(lang),TRUE);
            }
          }
        }
        break;
      case LayoutDocEntry::MemberDefEnd:
        if (!isSimple) endMemberDocumentation(ol);
        break;
      default:
        break;
    }
  }
  // part 3: close the block
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  { // HTML only
    ol.endIndent();
  }
  ol.popGeneratorState();
}
References OutputList::addIndexItem(), anchor(), LayoutDocEntry::BriefDesc, LayoutDocManager::Class, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassInheritanceGraph, compoundTypeString(), OutputList::disable(), OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputList::endIndent(), endMemberDeclarations(), OutputList::endMemberDoc(), OutputList::endMemberDocName(), endMemberDocumentation(), FALSE, DefinitionMixin< ClassDefMutable >::getLanguage(), getOutputFileBase(), OutputGenerator::Html, LayoutDocManager::instance(), isSimple(), ClassDefImpl::IMPL::isSimple, m_impl, OutputGenerator::Man, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, DefinitionMixin< ClassDefMutable >::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), s, OutputList::startGroupHeader(), OutputList::startIndent(), startMemberDeclarations(), OutputList::startMemberDoc(), OutputList::startMemberDocName(), startMemberDocumentation(), LayoutDocEntryMemberDecl::subtitle(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), TRUE, LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, OutputList::writeAnchor(), writeCollaborationGraph(), writeDetailedDocumentationBody(), writeInheritanceGraph(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), writeSimpleMemberDocumentation(), and OutputList::writeString().
writeInlineDocumentation() [2/2]
virtual void ClassDefImpl::writeInlineDocumentation (OutputList & ol) const [virtual]
Implements ClassDefMutable.
writeMemberDeclarations() [1/2]
void ClassDefImpl::writeMemberDeclarations (OutputList & ol, ClassDefSet & visitedClasses, MemberListType lt, const QCString & title, const QCString & subTitle = QCString(), bool showInline = FALSE, const ClassDef * inheritedFrom = 0, int lt2 = -1, bool invert = FALSE, bool showAlways = FALSE) const [virtual]
Implements ClassDefMutable.
Definition at line 4488 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::writeMemberDeclarations lt=%d lt2=%d\n",qPrint(name()),lt,lt2);
  MemberList * ml = getMemberList(lt);
  MemberList * ml2 = getMemberList(static_cast<MemberListType>(lt2));
  if (getLanguage()==SrcLangExt_VHDL) // use specific declarations function
  {
    static const ClassDef *cdef;
    if (cdef!=this)
    { // only one inline link
      VhdlDocGen::writeInlineClassLink(this,ol);
      cdef=this;
    }
    if (ml)
    {
      VhdlDocGen::writeVhdlDeclarations(ml,ol,0,this,0,0);
    }
  }
  else
  {
    //printf("%s::writeMemberDeclarations(%s) ml=%p ml2=%p\n",qPrint(name()),qPrint(title),ml,ml2);
    QCString tt = title, st = subTitle;
    if (ml)
    {
      //printf(" writeDeclaration type=%d count=%d\n",lt,ml->numDecMembers());
      ml->writeDeclarations(ol,this,0,0,0,tt,st,FALSE,showInline,inheritedFrom,lt);
      tt.resize(0);
      st.resize(0);
    }
    if (ml2)
    {
      //printf(" writeDeclaration type=%d count=%d\n",lt2,ml2->numDecMembers());
      ml2->writeDeclarations(ol,this,0,0,0,tt,st,FALSE,showInline,inheritedFrom,lt);
    }
    bool inlineInheritedMembers = Config_getBool(INLINE_INHERITED_MEMB);
    if (!inlineInheritedMembers) // show inherited members as separate lists
    {
      writeInheritedMemberDeclarations(ol,visitedClasses,lt,lt2,title,
          inheritedFrom ? inheritedFrom : this,
          invert,showAlways);
    }
  }
}
References Config_getBool, FALSE, DefinitionMixin< ClassDefMutable >::getLanguage(), getMemberList(), QCString::resize(), SrcLangExt_VHDL, title(), MemberList::writeDeclarations(), writeInheritedMemberDeclarations(), VhdlDocGen::writeInlineClassLink(), and VhdlDocGen::writeVhdlDeclarations().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeMemberDeclarations() [2/2]
virtual void ClassDefImpl::writeMemberDeclarations (OutputList & ol, ClassDefSet & visitedClasses, MemberListType lt, const QCString & title, const QCString & subTitle = QCString(), bool showInline = FALSE, const ClassDef * inheritedFrom = 0, int lt2 = -1, bool invert = FALSE, bool showAlways = FALSE) const [virtual]
Implements ClassDefMutable.
writeMemberDocumentation() [1/2]
void ClassDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title, bool showInline = FALSE) const [private]
Definition at line 4548 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::writeMemberDocumentation()\n",qPrint(name()));
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeDocumentation(ol,displayName(),this,title,FALSE,showInline);
}
References displayName(), FALSE, getMemberList(), title(), and MemberList::writeDocumentation().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeMemberDocumentation() [2/2]
void ClassDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title, bool showInline = FALSE) const [private]
writeMemberGroups() [1/2]
void ClassDefImpl::writeMemberGroups (OutputList & ol, bool showInline = FALSE) const [private]
Definition at line 1941 of file classdef.cpp.
{
  // write user defined member groups
  for (const auto &mg : m_impl->memberGroups)
  {
    if (!mg->allMembersInSameSection() || !m_impl->subGrouping) // group is in its own section
    {
      mg->writeDeclarations(ol,this,0,0,0,showInline);
    }
    else // add this group to the corresponding member section
    {
      //printf("addToDeclarationSection(%s)\n",qPrint(mg->header()));
      //mg->addToDeclarationSection();
    }
  }
}
References m_impl, ClassDefImpl::IMPL::memberGroups, and ClassDefImpl::IMPL::subGrouping.
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeMemberGroups() [2/2]
void ClassDefImpl::writeMemberGroups (OutputList & ol, bool showInline = FALSE) const [private]
writeMemberList() [1/2]
void ClassDefImpl::writeMemberList (OutputList & ol) const [virtual]
Implements ClassDefMutable.
Definition at line 2836 of file classdef.cpp.
{
  bool cOpt = Config_getBool(OPTIMIZE_OUTPUT_FOR_C);
  //bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  if (m_impl->allMemberNameInfoLinkedMap.empty() || cOpt) return;
  // only for HTML
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  HighlightedItem hli;
  if (sliceOpt)
  {
    if (compoundType()==Interface)
    {
      hli = HLI_InterfaceVisible;
    }
    else if (compoundType()==Struct)
    {
      hli = HLI_StructVisible;
    }
    else if (compoundType()==Exception)
    {
      hli = HLI_ExceptionVisible;
    }
    else
    {
      hli = HLI_ClassVisible;
    }
  }
  else
  {
    hli = HLI_ClassVisible;
  }
  QCString memListFile = getMemberListFileName();
  startFile(ol,memListFile,memListFile,theTranslator->trMemberList(),hli,!generateTreeView,getOutputFileBase());
  if (!generateTreeView)
  {
    if (getOuterScope()!=Doxygen::globalScope)
    {
      writeNavigationPath(ol);
    }
    ol.endQuickIndices();
  }
  startTitle(ol,QCString());
  ol.parseText(displayName()+" "+theTranslator->trMemberList());
  endTitle(ol,QCString(),QCString());
  ol.startContents();
  ol.startParagraph();
  ol.parseText(theTranslator->trThisIsTheListOfAllMembers());
  ol.writeObjectLink(getReference(),getOutputFileBase(),anchor(),displayName());
  ol.parseText(theTranslator->trIncludingInheritedMembers());
  ol.endParagraph();
  //ol.startItemList();
  bool first = true; // to prevent empty table
  int idx=0;
  for (auto &mni : m_impl->allMemberNameInfoLinkedMap)
  {
    for (auto &mi : *mni)
    {
      const MemberDef *md=mi->memberDef();
      const ClassDef *cd=md->getClassDef();
      Protection prot = mi->prot();
      Specifier virt=md->virtualness();
      //printf("%s: Member %s of class %s md->protection()=%d mi->prot=%d prot=%d inherited=%d\n",
      // qPrint(name()),qPrint(md->name()),qPrint(cd->name()),md->protection(),mi->prot,prot,mi->inherited);
      if (cd && !md->name().isEmpty() && !md->isAnonymous())
      {
        bool memberWritten=FALSE;
        if (cd->isLinkable() && md->isLinkable())
          // create a link to the documentation
        {
          QCString name=mi->ambiguityResolutionScope()+md->name();
          //ol.writeListItem();
          if (first)
          {
            ol.writeString("<table class=\"directory\">\n");
            first = false;
          }
          ol.writeString(" <tr");
          if ((idx&1)==0) ol.writeString(" class=\"even\""); else ol.writeString(" class=\"odd\"");
          idx++;
          ol.writeString("><td class=\"entry\">");
          if (cd->isObjectiveC())
          {
            if (md->isObjCMethod())
            {
              if (md->isStatic())
                ol.writeString("+&#160;</td><td>");
              else
                ol.writeString("-&#160;</td><td>");
            }
            else
              ol.writeString("</td><td class=\"entry\">");
          }
          if (md->isObjCMethod())
          {
            ol.writeObjectLink(md->getReference(),
                md->getOutputFileBase(),
                md->anchor(),md->name());
          }
          else
          {
            //Definition *bd = md->getGroupDef();
            //if (bd==0) bd=cd;
            ol.writeObjectLink(md->getReference(),
                md->getOutputFileBase(),
                md->anchor(),name);
            if (md->isFunction() || md->isSignal() || md->isSlot() ||
                (md->isFriend() && md->argsString().isEmpty()))
              ol.docify(md->argsString());
            else if (md->isEnumerate())
              ol.parseText(" "+theTranslator->trEnumName());
            else if (md->isEnumValue())
              ol.parseText(" "+theTranslator->trEnumValue());
            else if (md->isTypedef())
              ol.docify(" typedef");
            else if (md->isFriend() && md->typeString()=="friend class")
              ol.docify(" class");
            //ol.writeString("\n");
          }
          ol.writeString("</td>");
          memberWritten=TRUE;
        }
        else if (!cd->isArtificial() &&
                 !Config_getBool(HIDE_UNDOC_MEMBERS) &&
                  (protectionLevelVisible(md->protection()) || md->isFriend())
                ) // no documentation,
                  // generate link to the class instead.
        {
          //ol.writeListItem();
          if (first)
          {
            ol.writeString("<table class=\"directory\">\n");
            first = false;
          }
          ol.writeString(" <tr bgcolor=\"#f0f0f0\"");
          if ((idx&1)==0) ol.writeString(" class=\"even\""); else ol.writeString(" class=\"odd\"");
          idx++;
          ol.writeString("><td class=\"entry\">");
          if (cd->isObjectiveC())
          {
            if (md->isObjCMethod())
            {
              if (md->isStatic())
                ol.writeString("+&#160;</td><td class=\"entry\">");
              else
                ol.writeString("-&#160;</td><td class=\"entry\">");
            }
            else
              ol.writeString("</td><td class=\"entry\">");
          }
          ol.startBold();
          ol.docify(md->name());
          ol.endBold();
          if (!md->isObjCMethod())
          {
            if (md->isFunction() || md->isSignal() || md->isSlot())
              ol.docify(md->argsString());
            else if (md->isEnumerate())
              ol.parseText(" "+theTranslator->trEnumName());
            else if (md->isEnumValue())
              ol.parseText(" "+theTranslator->trEnumValue());
            else if (md->isTypedef())
              ol.docify(" typedef");
          }
          ol.writeString(" (");
          ol.parseText(theTranslator->trDefinedIn()+" ");
          if (cd->isLinkable())
          {
            ol.writeObjectLink(
                cd->getReference(),
                cd->getOutputFileBase(),
                cd->anchor(),
                cd->displayName());
          }
          else
          {
            ol.startBold();
            ol.docify(cd->displayName());
            ol.endBold();
          }
          ol.writeString(")");
          ol.writeString("</td>");
          memberWritten=TRUE;
        }
        if (memberWritten)
        {
          ol.writeString("<td class=\"entry\">");
          ol.writeObjectLink(cd->getReference(),
                             cd->getOutputFileBase(),
                             cd->anchor(),
                             md->category() ?
                                md->category()->displayName() :
                                cd->displayName());
          ol.writeString("</td>");
          ol.writeString("<td class=\"entry\">");
        }
        SrcLangExt lang = md->getLanguage();
        if (
            (prot!=Public || (virt!=Normal && getLanguage()!=SrcLangExt_ObjC) ||
             md->isFriend() || md->isRelated() || md->isExplicit() ||
             md->isMutable() || (md->isInline() && Config_getBool(INLINE_INFO)) ||
             md->isSignal() || md->isSlot() ||
             (getLanguage()==SrcLangExt_IDL &&
              (md->isOptional() || md->isAttribute() || md->isUNOProperty())) ||
             md->isStatic() || lang==SrcLangExt_VHDL
            )
            && memberWritten)
        {
          StringVector sl;
          if (lang==SrcLangExt_VHDL)
          {
            sl.push_back(theTranslator->trVhdlType(md->getMemberSpecifiers(),TRUE).str()); //append vhdl type
          }
          else if (md->isFriend()) sl.push_back("friend");
          else if (md->isRelated()) sl.push_back("related");
          else
          {
            if (Config_getBool(INLINE_INFO) && md->isInline())
                                       sl.push_back("inline");
            if (md->isExplicit()) sl.push_back("explicit");
            if (md->isMutable()) sl.push_back("mutable");
            if (prot==Protected) sl.push_back("protected");
            else if (prot==Private) sl.push_back("private");
            else if (prot==Package) sl.push_back("package");
            if (virt==Virtual && getLanguage()!=SrcLangExt_ObjC)
                                       sl.push_back("virtual");
            else if (virt==Pure) sl.push_back("pure virtual");
            if (md->isStatic()) sl.push_back("static");
            if (md->isSignal()) sl.push_back("signal");
            if (md->isSlot()) sl.push_back("slot");
// this is the extra member page
            if (md->isOptional()) sl.push_back("optional");
            if (md->isAttribute()) sl.push_back("attribute");
            if (md->isUNOProperty()) sl.push_back("property");
            if (md->isReadonly()) sl.push_back("readonly");
            if (md->isBound()) sl.push_back("bound");
            if (md->isRemovable()) sl.push_back("removable");
            if (md->isConstrained()) sl.push_back("constrained");
            if (md->isTransient()) sl.push_back("transient");
            if (md->isMaybeVoid()) sl.push_back("maybevoid");
            if (md->isMaybeDefault()) sl.push_back("maybedefault");
            if (md->isMaybeAmbiguous())sl.push_back("maybeambiguous");
          }
          bool firstSpan=true;
          for (const auto &s : sl)
          {
            if (!firstSpan)
            {
              ol.writeString("</span><span class=\"mlabel\">");
            }
            else
            {
              ol.writeString("<span class=\"mlabel\">");
              firstSpan=false;
            }
            ol.docify(s.c_str());
          }
          if (!firstSpan) ol.writeString("</span>");
        }
        if (memberWritten)
        {
          ol.writeString("</td>");
          ol.writeString("</tr>\n");
        }
      }
    }
  }
  //ol.endItemList();
  if (!first) ol.writeString("</table>");
  endFile(ol);
  ol.popGeneratorState();
}
References ClassDefImpl::IMPL::allMemberNameInfoLinkedMap, anchor(), ClassDef::anchor(), MemberDef::anchor(), MemberDef::argsString(), MemberDef::category(), compoundType(), Config_getBool, OutputList::disableAllBut(), displayName(), ClassDef::displayName(), OutputList::docify(), LinkedMap< T, Hash, KeyEqual, Map >::empty(), OutputList::endBold(), endFile(), OutputList::endParagraph(), OutputList::endQuickIndices(), endTitle(), ClassDef::Exception, FALSE, MemberDef::getClassDef(), DefinitionMixin< ClassDefMutable >::getLanguage(), Definition::getLanguage(), getMemberListFileName(), MemberDef::getMemberSpecifiers(), DefinitionMixin< ClassDefMutable >::getOuterScope(), getOutputFileBase(), ClassDef::getOutputFileBase(), MemberDef::getOutputFileBase(), getReference(), ClassDef::getReference(), MemberDef::getReference(), Doxygen::globalScope, HLI_ClassVisible, HLI_ExceptionVisible, HLI_InterfaceVisible, HLI_StructVisible, OutputGenerator::Html, Definition::isAnonymous(), Definition::isArtificial(), MemberDef::isAttribute(), MemberDef::isBound(), MemberDef::isConstrained(), QCString::isEmpty(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isExplicit(), MemberDef::isFriend(), MemberDef::isFunction(), MemberDef::isInline(), ClassDef::isLinkable(), MemberDef::isLinkable(), MemberDef::isMaybeAmbiguous(), MemberDef::isMaybeDefault(), MemberDef::isMaybeVoid(), MemberDef::isMutable(), MemberDef::isObjCMethod(), ClassDef::isObjectiveC(), MemberDef::isOptional(), MemberDef::isReadonly(), MemberDef::isRelated(), MemberDef::isRemovable(), MemberDef::isSignal(), MemberDef::isSlot(), MemberDef::isStatic(), MemberDef::isTransient(), MemberDef::isTypedef(), MemberDef::isUNOProperty(), m_impl, DefinitionMixin< ClassDefMutable >::name(), Definition::name(), Normal, Package, OutputList::parseText(), OutputList::popGeneratorState(), Private, Protected, MemberDef::protection(), protectionLevelVisible(), Public, Pure, OutputList::pushGeneratorState(), s, caseconvert::sl, SrcLangExt_IDL, SrcLangExt_ObjC, SrcLangExt_VHDL, OutputList::startBold(), OutputList::startContents(), startFile(), OutputList::startParagraph(), startTitle(), QCString::str(), ClassDef::Struct, theTranslator, Translator::trDefinedIn(), Translator::trEnumName(), Translator::trEnumValue(), Translator::trIncludingInheritedMembers(), Translator::trMemberList(), Translator::trThisIsTheListOfAllMembers(), TRUE, Translator::trVhdlType(), MemberDef::typeString(), Virtual, MemberDef::virtualness(), DefinitionMixin< ClassDefMutable >::writeNavigationPath(), OutputList::writeObjectLink(), and OutputList::writeString().
writeMemberList() [2/2]
virtual void ClassDefImpl::writeMemberList (OutputList & ol) const [virtual]
Implements ClassDefMutable.
writeMemberPages() [1/2]
void ClassDefImpl::writeMemberPages (OutputList & ol) const [virtual]
Implements ClassDefMutable.
Definition at line 2748 of file classdef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  for (const auto &ml : m_impl->memberLists)
  {
    if (ml->numDocMembers()>ml->numDocEnumValues() && (ml->listType()&MemberListType_detailedLists))
    {
      ml->writeDocumentationPage(ol,displayName(),this);
    }
  }
  ol.popGeneratorState();
}
References OutputList::disableAllBut(), displayName(), OutputGenerator::Html, m_impl, ClassDefImpl::IMPL::memberLists, MemberListType_detailedLists, OutputList::popGeneratorState(), and OutputList::pushGeneratorState().
Referenced by writeDocumentation().
writeMemberPages() [2/2]
virtual void ClassDefImpl::writeMemberPages (OutputList & ol) const [virtual]
Implements ClassDefMutable.
writeMoreLink() [1/2]
void ClassDefImpl::writeMoreLink (OutputList & ol, const QCString & anchor) const [private]
Definition at line 2307 of file classdef.cpp.
{
  // TODO: clean up this mess by moving it to
  // the output generators...
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  bool rtfHyperlinks = Config_getBool(RTF_HYPERLINKS);
  bool usePDFLatex = Config_getBool(USE_PDFLATEX);
  // HTML only
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  ol.docify(" ");
  ol.startTextLink(getOutputFileBase(),
      anchor.isEmpty() ? QCString("details") : anchor);
  ol.parseText(theTranslator->trMore());
  ol.endTextLink();
  ol.popGeneratorState();
  if (!anchor.isEmpty())
  {
    ol.pushGeneratorState();
    // LaTeX + RTF
    ol.disable(OutputGenerator::Html);
    ol.disable(OutputGenerator::Man);
    ol.disable(OutputGenerator::Docbook);
    if (!(usePDFLatex && pdfHyperlinks))
    {
      ol.disable(OutputGenerator::Latex);
    }
    if (!rtfHyperlinks)
    {
      ol.disable(OutputGenerator::RTF);
    }
    ol.docify(" ");
    ol.startTextLink(getOutputFileBase(), anchor);
    ol.parseText(theTranslator->trMore());
    ol.endTextLink();
    // RTF only
    ol.disable(OutputGenerator::Latex);
    ol.writeString("\\par");
    ol.popGeneratorState();
  }
}
References anchor(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), OutputGenerator::Docbook, OutputList::docify(), OutputList::endTextLink(), getOutputFileBase(), OutputGenerator::Html, QCString::isEmpty(), OutputGenerator::Latex, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startTextLink(), theTranslator, Translator::trMore(), and OutputList::writeString().
Referenced by writeBriefDescription(), and writeDeclarationLink().
writeMoreLink() [2/2]
void ClassDefImpl::writeMoreLink (OutputList & ol, const QCString & anchor) const [private]
writeNestedClasses() [1/2]
void ClassDefImpl::writeNestedClasses (OutputList & ol, const QCString & title) const [private]
Definition at line 1958 of file classdef.cpp.
{
  // nested classes
  m_impl->innerClasses.writeDeclaration(ol,0,title,TRUE);
}
References ClassDefImpl::IMPL::innerClasses, m_impl, title(), TRUE, and ClassLinkedRefMap::writeDeclaration().
Referenced by writeDocumentationContents().
writeNestedClasses() [2/2]
void ClassDefImpl::writeNestedClasses (OutputList & ol, const QCString & title) const [private]
writePlainMemberDeclaration() [1/2]
void ClassDefImpl::writePlainMemberDeclaration (OutputList & ol, MemberListType lt, bool inGroup, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const [private]
Definition at line 4562 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::writePlainMemberDeclaration()\n",qPrint(name()));
  MemberList * ml = getMemberList(lt);
  if (ml)
  {
    ml->writePlainDeclarations(ol,inGroup,this,0,0,0,indentLevel,inheritedFrom,inheritId);
  }
}
References getMemberList(), and MemberList::writePlainDeclarations().
Referenced by writeDeclaration().
writePlainMemberDeclaration() [2/2]
void ClassDefImpl::writePlainMemberDeclaration (OutputList & ol, MemberListType lt, bool inGroup, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const [private]
writeQuickMemberLinks() [1/2]
void ClassDefImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * md) const [virtual]
Reimplemented from DefinitionMixin< ClassDefMutable >.
Definition at line 2768 of file classdef.cpp.
{
  bool createSubDirs=Config_getBool(CREATE_SUBDIRS);
  ol.writeString(" <div class=\"navtab\">\n");
  ol.writeString(" <table>\n");
  for (auto &mni : m_impl->allMemberNameInfoLinkedMap)
  {
    for (auto &mi : *mni)
    {
      const MemberDef *md=mi->memberDef();
      if (md->getClassDef()==this && md->isLinkable() && !md->isEnumValue())
      {
        if (md->isLinkableInProject())
        {
          if (md==currentMd) // selected item => highlight
          {
            ol.writeString(" <tr><td class=\"navtabHL\">");
          }
          else
          {
            ol.writeString(" <tr><td class=\"navtab\">");
          }
          ol.writeString("<a class=\"navtab\" ");
          ol.writeString("href=\"");
          if (createSubDirs) ol.writeString("../../");
          ol.writeString(addHtmlExtensionIfMissing(md->getOutputFileBase())+"#"+md->anchor());
          ol.writeString("\">");
          ol.writeString(convertToHtml(md->name()));
          ol.writeString("</a>");
          ol.writeString("</td></tr>\n");
        }
      }
    }
  }
  ol.writeString(" </table>\n");
  ol.writeString(" </div>\n");
}
References addHtmlExtensionIfMissing(), ClassDefImpl::IMPL::allMemberNameInfoLinkedMap, MemberDef::anchor(), Config_getBool, convertToHtml(), createSubDirs(), MemberDef::getClassDef(), MemberDef::getOutputFileBase(), MemberDef::isEnumValue(), MemberDef::isLinkable(), MemberDef::isLinkableInProject(), m_impl, Definition::name(), and OutputList::writeString().
writeQuickMemberLinks() [2/2]
virtual void ClassDefImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * md) const [virtual]
Reimplemented from DefinitionMixin< ClassDefMutable >.
writeSimpleMemberDocumentation() [1/2]
void ClassDefImpl::writeSimpleMemberDocumentation (OutputList & ol, MemberListType lt) const [private]
Definition at line 4555 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::writeSimpleMemberDocumentation()\n",qPrint(name()));
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeSimpleDocumentation(ol,this);
}
References getMemberList(), and MemberList::writeSimpleDocumentation().
Referenced by writeInlineDocumentation().
writeSimpleMemberDocumentation() [2/2]
void ClassDefImpl::writeSimpleMemberDocumentation (OutputList & ol, MemberListType lt) const [private]
writeSummaryLinks() [1/2]
void ClassDefImpl::writeSummaryLinks (OutputList & ol) const [virtual]
Reimplemented from DefinitionMixin< ClassDefMutable >.
Definition at line 2022 of file classdef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  bool first=TRUE;
  SrcLangExt lang = getLanguage();
  if (lang!=SrcLangExt_VHDL)
  {
    for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
    {
      if (lde->kind()==LayoutDocEntry::ClassNestedClasses &&
          m_impl->innerClasses.declVisible()
         )
      {
        const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
        if (ls)
        {
          ol.writeSummaryLink(QCString(),"nested-classes",ls->title(lang),first);
          first=FALSE;
        }
      }
      else if (lde->kind()==LayoutDocEntry::ClassAllMembersLink &&
               !m_impl->allMemberNameInfoLinkedMap.empty() &&
               !Config_getBool(OPTIMIZE_OUTPUT_FOR_C)
              )
      {
        ol.writeSummaryLink(getMemberListFileName(),"all-members-list",theTranslator->trListOfAllMembers(),first);
        first=FALSE;
      }
      else if (lde->kind()==LayoutDocEntry::MemberDecl)
      {
        const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
        if (lmd)
        {
          MemberList * ml = getMemberList(lmd->type);
          if (ml && ml->declVisible())
          {
            ol.writeSummaryLink(QCString(),MemberList::listTypeAsString(ml->listType()),lmd->title(lang),first);
            first=FALSE;
          }
        }
      }
    }
  }
  else // VDHL only
  {
    for (const auto &s : m_impl->vhdlSummaryTitles)
    {
      ol.writeSummaryLink(QCString(),convertToId(QCString(s)),QCString(s),first);
      first=FALSE;
    }
  }
  if (!first)
  {
    ol.writeString(" </div>\n");
  }
  ol.popGeneratorState();
}
References ClassDefImpl::IMPL::allMemberNameInfoLinkedMap, LayoutDocManager::Class, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassNestedClasses, Config_getBool, convertToId(), MemberList::declVisible(), ClassLinkedRefMap::declVisible(), OutputList::disableAllBut(), LinkedMap< T, Hash, KeyEqual, Map >::empty(), FALSE, DefinitionMixin< ClassDefMutable >::getLanguage(), getMemberList(), getMemberListFileName(), OutputGenerator::Html, ClassDefImpl::IMPL::innerClasses, LayoutDocManager::instance(), MemberList::listType(), MemberList::listTypeAsString(), m_impl, LayoutDocEntry::MemberDecl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), s, SrcLangExt_VHDL, theTranslator, LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), Translator::trListOfAllMembers(), TRUE, LayoutDocEntryMemberDecl::type, ClassDefImpl::IMPL::vhdlSummaryTitles, OutputList::writeString(), and OutputList::writeSummaryLink().
writeSummaryLinks() [2/2]
virtual void ClassDefImpl::writeSummaryLinks (OutputList & ol) const [virtual]
Reimplemented from DefinitionMixin< ClassDefMutable >.
writeTagFile() [1/2]
void ClassDefImpl::writeTagFile (TextStream & tagFile) [virtual]
Implements ClassDefMutable.
Definition at line 2082 of file classdef.cpp.
{
  if (!isLinkableInProject() || isArtificial()) return;
  tagFile << " <compound kind=\"";
  if (isFortran() && (compoundTypeString() == "type"))
    tagFile << "struct";
  else
    tagFile << compoundTypeString();
  tagFile << "\"";
  if (isObjectiveC()) { tagFile << " objc=\"yes\""; }
  tagFile << ">\n";
  tagFile << " <name>" << convertToXML(name()) << "</name>\n";
  tagFile << " <filename>" << convertToXML(addHtmlExtensionIfMissing(getOutputFileBase())) << "</filename>\n";
  if (!anchor().isEmpty())
  {
    tagFile << " <anchor>" << convertToXML(anchor()) << "</anchor>\n";
  }
  QCString idStr = id();
  if (!idStr.isEmpty())
  {
    tagFile << " <clangid>" << convertToXML(idStr) << "</clangid>\n";
  }
  for (const Argument &a : m_impl->tempArgs)
  {
    tagFile << " <templarg>" << convertToXML(a.type);
    if (!a.name.isEmpty())
    {
      tagFile << " " << convertToXML(a.name);
    }
    tagFile << "</templarg>\n";
  }
  for (const auto &ibcd : m_impl->inherits)
  {
    ClassDef *cd=ibcd.classDef;
    if (cd && cd->isLinkable())
    {
      if (!Config_getString(GENERATE_TAGFILE).isEmpty())
      {
        tagFile << " <base";
        if (ibcd.prot==Protected)
        {
          tagFile << " protection=\"protected\"";
        }
        else if (ibcd.prot==Private)
        {
          tagFile << " protection=\"private\"";
        }
        if (ibcd.virt==Virtual)
        {
          tagFile << " virtualness=\"virtual\"";
        }
        tagFile << ">" << convertToXML(cd->name()) << "</base>\n";
      }
    }
  }
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::ClassNestedClasses:
        {
          for (const auto &innerCd : m_impl->innerClasses)
          {
            if (innerCd->isLinkableInProject() && innerCd->templateMaster()==0 &&
                protectionLevelVisible(innerCd->protection()) &&
                !innerCd->isEmbeddedInOuterScope()
               )
            {
              tagFile << " <class kind=\"" << innerCd->compoundTypeString() <<
                "\">" << convertToXML(innerCd->name()) << "</class>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            MemberList * ml = getMemberList(lmd->type);
            if (ml)
            {
              ml->writeTagFile(tagFile);
            }
          }
        }
        break;
      case LayoutDocEntry::MemberGroups:
        {
          for (const auto &mg : m_impl->memberGroups)
          {
            mg->writeTagFile(tagFile);
          }
        }
        break;
     default:
        break;
    }
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << " </compound>\n";
}
References a, addHtmlExtensionIfMissing(), anchor(), LayoutDocManager::Class, LayoutDocEntry::ClassNestedClasses, compoundTypeString(), Config_getString, convertToXML(), getMemberList(), getOutputFileBase(), DefinitionMixin< ClassDefMutable >::id(), ClassDefImpl::IMPL::inherits, ClassDefImpl::IMPL::innerClasses, LayoutDocManager::instance(), DefinitionMixin< ClassDefMutable >::isArtificial(), QCString::isEmpty(), isFortran(), ClassDef::isLinkable(), isLinkableInProject(), isObjectiveC(), m_impl, LayoutDocEntry::MemberDecl, ClassDefImpl::IMPL::memberGroups, LayoutDocEntry::MemberGroups, DefinitionMixin< ClassDefMutable >::name(), Definition::name(), Private, Protected, protectionLevelVisible(), ClassDefImpl::IMPL::tempArgs, LayoutDocEntryMemberDecl::type, Virtual, DefinitionMixin< ClassDefMutable >::writeDocAnchorsToTagFile(), and MemberList::writeTagFile().
writeTagFile() [2/2]
virtual void ClassDefImpl::writeTagFile (TextStream &) [virtual]
Implements ClassDefMutable.
writeTemplateSpec() [1/2]
void ClassDefImpl::writeTemplateSpec (OutputList & ol, const Definition * d, const QCString & type, SrcLangExt lang) const [private]
Definition at line 1301 of file classdef.cpp.
{
  ArgumentLists specs;
  QCString name;
  searchTemplateSpecs(d,specs,name,lang);
  if (!specs.empty()) // class has template scope specifiers
  {
    ol.startCompoundTemplateParams();
    for (const ArgumentList &al : specs)
    {
      ol.docify("template<");
      auto it = al.begin();
      while (it!=al.end())
      {
        Argument a = *it;
        linkifyText(TextGeneratorOLImpl(ol), // out
          d, // scope
          getFileDef(), // fileScope
          this, // self
          a.type, // text
          FALSE // autoBreak
          );
        if (!a.name.isEmpty())
        {
          ol.docify(" ");
          ol.docify(a.name);
        }
        if (a.defval.length()!=0)
        {
          ol.docify(" = ");
          ol.docify(a.defval);
        }
        ++it;
        if (it!=al.end()) ol.docify(", ");
      }
      ol.docify(">");
      ol.lineBreak();
    }
    if (!m_impl->requiresClause.isEmpty())
    {
      ol.docify("requires ");
      linkifyText(TextGeneratorOLImpl(ol), // out
          d, // scope
          getFileDef(), // fileScope
          this, // self
          m_impl->requiresClause, // text
          FALSE // autoBreak
          );
      ol.lineBreak();
    }
    ol.docify(type.lower()+" "+name);
    ol.endCompoundTemplateParams();
  }
}
References a, OutputList::docify(), OutputList::endCompoundTemplateParams(), FALSE, getFileDef(), QCString::isEmpty(), OutputList::lineBreak(), linkifyText(), QCString::lower(), m_impl, DefinitionMixin< ClassDefMutable >::name(), ClassDefImpl::IMPL::requiresClause, searchTemplateSpecs(), and OutputList::startCompoundTemplateParams().
Referenced by writeDetailedDocumentationBody().
writeTemplateSpec() [2/2]
void ClassDefImpl::writeTemplateSpec (OutputList & ol, const Definition * d, const QCString & type, SrcLangExt lang) const [private]
Member Data Documentation
m_impl
IMPL * ClassDefImpl::m_impl = 0 [private]
Definition at line 360 of file classdef.cpp.
Referenced by addExample(), addGroupedInheritedMembers(), addInnerCompound(), addListReferences(), addMembersToMemberGroup(), addMembersToTemplateInstance(), addMemberToList(), addTypeConstraint(), addTypeConstraints(), addUsedByClass(), addUsedClass(), anchor(), baseClasses(), categoryOf(), ClassDefImpl(), className(), collaborationGraphFileName(), compoundType(), compoundTypeString(), computeAnchors(), countInheritanceNodes(), countInheritedDecMembers(), countMemberDeclarations(), countMembers(), countMembersIncludingGrouped(), distributeMemberGroupDocumentation(), findInnerCompound(), findSectionsInDocumentation(), generatedFromFiles(), getClasses(), getExamples(), getFileDef(), getInstanceOutputFileBase(), getMemberByName(), getMemberGroups(), getMemberList(), getMemberListFileName(), getMemberLists(), getOutputFileBase(), getReference(), getSourceFileBase(), getTemplateBaseClassNames(), getTemplateInstances(), hasExamples(), includeInfo(), inheritanceGraphFileName(), insertBaseClass(), insertSubClass(), insertTemplateInstance(), insertUsedFile(), internalInsertMember(), isAbstract(), isEmbeddedInOuterScope(), isFinal(), isForwardDeclared(), isInterface(), isJavaEnum(), isLinkable(), isLinkableInProject(), isLocal(), isPublished(), isReference(), isSealed(), isSimple(), isSliceLocal(), isSmartPointer(), isTemplate(), isTemplateArgument(), isUsedOnly(), isVisibleInHierarchy(), makeTemplateArgument(), memberNameInfoLinkedMap(), mergeCategory(), mergeMembers(), protection(), reclassifyMember(), removeMemberFromLists(), requiresClause(), setAnonymousEnumType(), setCategoryOf(), setClassName(), setClassSpecifier(), setCompoundType(), setFileDef(), setGroupDefForAllMembers(), setIncludeFile(), setIsStatic(), setMetaData(), setProtection(), setRequiresClause(), setSubGrouping(), setTagLessReference(), setTemplateArguments(), setTemplateBaseClassNames(), setTemplateMaster(), setTypeConstraints(), setUsedOnly(), showUsedFiles(), sortAllMembersList(), sortMemberLists(), subClasses(), subGrouping(), tagLessReference(), templateArguments(), templateMaster(), templateTypeConstraints(), title(), typeConstraints(), updateBaseClasses(), updateSubClasses(), usedByImplementationClasses(), usedFiles(), usedImplementationClasses(), writeDeclaration(), writeDetailedDocumentationBody(), writeDocumentationForInnerClasses(), writeIncludeFiles(), writeIncludeFilesForSlice(), writeInheritanceGraph(), writeInheritedMemberDeclarations(), writeInlineClasses(), writeInlineDocumentation(), writeMemberGroups(), writeMemberList(), writeMemberPages(), writeNestedClasses(), writeQuickMemberLinks(), writeSummaryLinks(), writeTagFile(), writeTemplateSpec(), and ~ClassDefImpl().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/classdef.cpp
doxygen/src/classdef.cpp