DiagramRow Class Reference
Public Types
using Ptr = std::unique_ptr< DiagramItem >
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using reverse_iterator = typename Vec::reverse_iterator
using Ptr = std::unique_ptr< DiagramItem >
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using reverse_iterator = typename Vec::reverse_iterator
Public Member Functions
DiagramRow (TreeDiagram *d, uint l)
void insertClass (DiagramItem *parent, const ClassDef *cd, bool doBases, Protection prot, Specifier virt, const QCString &ts)
uint number ()
DiagramItem * item (int index)
uint numItems () const
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
DiagramRow (TreeDiagram *d, uint l)
void insertClass (DiagramItem *parent, const ClassDef *cd, bool doBases, Protection prot, Specifier virt, const QCString &ts)
uint number ()
DiagramItem * item (int index)
uint numItems () const
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
Private Attributes
TreeDiagram * m_diagram
uint m_level
Vec m_items
Detailed Description
Class representing a row in the built-in class diagram
Definition at line 77 of file diagram.cpp.
Member Typedef Documentation
iterator [1/2]
using DiagramRow::iterator = typename Vec::iterator
Definition at line 82 of file diagram.cpp.
iterator [2/2]
using DiagramRow::iterator = typename Vec::iterator
Definition at line 82 of file diagram.cpp.
Ptr [1/2]
using DiagramRow::Ptr = std::unique_ptr<DiagramItem>
Definition at line 80 of file diagram.cpp.
Ptr [2/2]
using DiagramRow::Ptr = std::unique_ptr<DiagramItem>
Definition at line 80 of file diagram.cpp.
reverse_iterator [1/2]
using DiagramRow::reverse_iterator = typename Vec::reverse_iterator
Definition at line 83 of file diagram.cpp.
reverse_iterator [2/2]
using DiagramRow::reverse_iterator = typename Vec::reverse_iterator
Definition at line 83 of file diagram.cpp.
Vec [1/2]
using DiagramRow::Vec = std::vector<Ptr>
Definition at line 81 of file diagram.cpp.
Vec [2/2]
using DiagramRow::Vec = std::vector<Ptr>
Definition at line 81 of file diagram.cpp.
Constructor & Destructor Documentation
DiagramRow() [1/2]
DiagramRow::DiagramRow (TreeDiagram * d, uint l) [inline]
Definition at line 84 of file diagram.cpp.
: m_diagram(d), m_level(l) {}
DiagramRow() [2/2]
DiagramRow::DiagramRow (TreeDiagram * d, uint l) [inline]
Definition at line 84 of file diagram.cpp.
: m_diagram(d), m_level(l) {}
Member Function Documentation
begin() [1/2]
iterator DiagramRow::begin () [inline]
Definition at line 91 of file diagram.cpp.
{ return m_items.begin(); }
References m_items.
Referenced by TreeDiagram::computeLayout().
begin() [2/2]
iterator DiagramRow::begin () [inline]
Definition at line 91 of file diagram.cpp.
{ return m_items.begin(); }
References m_items.
end() [1/2]
iterator DiagramRow::end () [inline]
Definition at line 92 of file diagram.cpp.
{ return m_items.end(); }
References m_items.
Referenced by TreeDiagram::computeLayout().
end() [2/2]
iterator DiagramRow::end () [inline]
Definition at line 92 of file diagram.cpp.
{ return m_items.end(); }
References m_items.
insertClass() [1/2]
void DiagramRow::insertClass (DiagramItem * parent, const ClassDef * cd, bool doBases, Protection prot, Specifier virt, const QCString & ts)
Definition at line 337 of file diagram.cpp.
{
  auto di = std::make_unique<DiagramItem>(parent, m_diagram->row(m_level)->numItems(),
                                          cd,prot,virt,ts);
  DiagramItem *di_ptr = di.get();
  if (parent) parent->addChild(di_ptr);
  di->move(static_cast<int>(m_items.size()*gridWidth),static_cast<int>(m_level*gridHeight));
  m_items.push_back(std::move(di));
  int count=0;
  for (const auto &bcd : doBases ? cd->baseClasses() : cd->subClasses())
  {
    /* there are base/sub classes */
    ClassDef *ccd=bcd.classDef;
    if (ccd && ccd->isVisibleInHierarchy()) count++;
  }
  if (count>0 && (prot!=Private || !doBases))
  {
    DiagramRow *row=0;
    if (m_diagram->numRows()<=m_level+1) /* add new row */
    {
      row=m_diagram->addRow(m_level+1);
    }
    else /* get next row */
    {
      row=m_diagram->row(m_level+1);
    }
    for (const auto &bcd : doBases ? cd->baseClasses() : cd->subClasses())
    {
      ClassDef *ccd=bcd.classDef;
      if (ccd && ccd->isVisibleInHierarchy())
      {
        row->insertClass(di_ptr,ccd,doBases,bcd.prot,
            doBases?bcd.virt:Normal,
            doBases?bcd.templSpecifiers:QCString());
      }
    }
  }
}
References TreeDiagram::addRow(), ClassDef::baseClasses(), gridHeight, gridWidth, insertClass(), ClassDef::isVisibleInHierarchy(), m_diagram, m_items, m_level, Normal, numItems(), TreeDiagram::numRows(), parent(), Private, TreeDiagram::row(), and ClassDef::subClasses().
Referenced by insertClass(), and TreeDiagram::TreeDiagram().
insertClass() [2/2]
void DiagramRow::insertClass (DiagramItem * parent, const ClassDef * cd, bool doBases, Protection prot, Specifier virt, const QCString & ts)
item() [1/2]
DiagramItem * DiagramRow::item (int index) [inline]
Definition at line 89 of file diagram.cpp.
{ return m_items.at(index).get(); }
References m_items.
Referenced by TreeDiagram::layoutTree().
item() [2/2]
DiagramItem * DiagramRow::item (int index) [inline]
Definition at line 89 of file diagram.cpp.
{ return m_items.at(index).get(); }
References m_items.
number() [1/2]
uint DiagramRow::number () [inline]
Definition at line 87 of file diagram.cpp.
{ return m_level; }
References m_level.
number() [2/2]
uint DiagramRow::number () [inline]
Definition at line 87 of file diagram.cpp.
{ return m_level; }
References m_level.
numItems() [1/2]
uint DiagramRow::numItems () const [inline]
Definition at line 90 of file diagram.cpp.
{ return static_cast<uint>(m_items.size()); }
References m_items.
Referenced by insertClass().
numItems() [2/2]
uint DiagramRow::numItems () const [inline]
Definition at line 90 of file diagram.cpp.
{ return static_cast<uint>(m_items.size()); }
References m_items.
rbegin() [1/2]
reverse_iterator DiagramRow::rbegin () [inline]
Definition at line 93 of file diagram.cpp.
{ return m_items.rbegin(); }
References m_items.
rbegin() [2/2]
reverse_iterator DiagramRow::rbegin () [inline]
Definition at line 93 of file diagram.cpp.
{ return m_items.rbegin(); }
References m_items.
rend() [1/2]
reverse_iterator DiagramRow::rend () [inline]
Definition at line 94 of file diagram.cpp.
{ return m_items.rend(); }
References m_items.
rend() [2/2]
reverse_iterator DiagramRow::rend () [inline]
Definition at line 94 of file diagram.cpp.
{ return m_items.rend(); }
References m_items.
Member Data Documentation
m_diagram
TreeDiagram * DiagramRow::m_diagram [private]
Definition at line 96 of file diagram.cpp.
Referenced by insertClass().
m_items
Vec DiagramRow::m_items [private]
Definition at line 98 of file diagram.cpp.
Referenced by begin(), end(), insertClass(), item(), numItems(), rbegin(), and rend().
m_level
uint DiagramRow::m_level [private]
Definition at line 97 of file diagram.cpp.
Referenced by insertClass(), and number().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/diagram.cpp
doxygen/src/diagram.cpp