TemplateNodeMsg Class Reference
Class representing an 'markers' tag in a template.
Public Member Functions
TemplateNodeMsg (TemplateParser *parser, TemplateNode *parent, int line, const QCString &)
void render (TextStream &, TemplateContext *c)
TemplateNodeMsg (TemplateParser *parser, TemplateNode *parent, int line, const QCString &)
void render (TextStream &, TemplateContext *c)
Private Attributes
TemplateNodeList m_nodes
Additional Inherited Members
Detailed Description
Class representing an 'markers' tag in a template.
Definition at line 3561 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeMsg() [1/2]
TemplateNodeMsg::TemplateNodeMsg (TemplateParser * parser, TemplateNode * parent, int line, const QCString &) [inline]
Definition at line 3564 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeMsg>(parser,parent,line)
    {
      TRACE(("{TemplateNodeMsg()\n"));
      StringVector stopAt = { "endmsg" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endmsg
      TRACE(("}TemplateNodeMsg()\n"));
    }
References m_nodes, TemplateParser::parse(), TemplateParser::removeNextToken(), and TRACE.
TemplateNodeMsg() [2/2]
TemplateNodeMsg::TemplateNodeMsg (TemplateParser * parser, TemplateNode * parent, int line, const QCString &) [inline]
Definition at line 3564 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeMsg>(parser,parent,line)
    {
      TRACE(("{TemplateNodeMsg()\n"));
      StringVector stopAt = { "endmsg" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endmsg
      TRACE(("}TemplateNodeMsg()\n"));
    }
References m_nodes, TemplateParser::parse(), TemplateParser::removeNextToken(), and TRACE.
Member Function Documentation
render() [1/2]
void TemplateNodeMsg::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3573 of file template.cpp.
    {
      TRACE(("{TemplateNodeMsg::render\n"));
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      TemplateEscapeIntf *escIntf = ci->escapeIntf();
      ci->setActiveEscapeIntf(0); // avoid escaping things we send to standard out
      bool enable = ci->spacelessEnabled();
      ci->enableSpaceless(FALSE);
      TextStream t(&std::cout);
      m_nodes.render(t,c);
      t.flush();
      std::cout << "\n";
      ci->setActiveEscapeIntf(escIntf);
      ci->enableSpaceless(enable);
      TRACE(("}TemplateNodeMsg::render\n"));
    }
References c, TemplateContextImpl::enableSpaceless(), TemplateContextImpl::escapeIntf(), FALSE, TextStream::flush(), TemplateNodeCreator< TemplateNodeMsg >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeMsg >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::setActiveEscapeIntf(), TemplateContextImpl::setLocation(), TemplateContextImpl::spacelessEnabled(), and TRACE.
render() [2/2]
void TemplateNodeMsg::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3573 of file template.cpp.
    {
      TRACE(("{TemplateNodeMsg::render\n"));
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      TemplateEscapeIntf *escIntf = ci->escapeIntf();
      ci->setActiveEscapeIntf(0); // avoid escaping things we send to standard out
      bool enable = ci->spacelessEnabled();
      ci->enableSpaceless(FALSE);
      TextStream t(&std::cout);
      m_nodes.render(t,c);
      t.flush();
      std::cout << "\n";
      ci->setActiveEscapeIntf(escIntf);
      ci->enableSpaceless(enable);
      TRACE(("}TemplateNodeMsg::render\n"));
    }
References c, TemplateContextImpl::enableSpaceless(), TemplateContextImpl::escapeIntf(), FALSE, TextStream::flush(), TemplateNodeCreator< TemplateNodeMsg >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeMsg >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::setActiveEscapeIntf(), TemplateContextImpl::setLocation(), TemplateContextImpl::spacelessEnabled(), and TRACE.
Member Data Documentation
m_nodes
TemplateNodeList TemplateNodeMsg::m_nodes [private]
Definition at line 3592 of file template.cpp.
Referenced by render(), and TemplateNodeMsg().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp