TranslatorPersian Class Reference
#include <translator_fa.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
Private Member Functions
QCString convertDigitsToFarsi (QCString str)
QCString convertDigitsToFarsi (QCString str)
Additional Inherited Members
Detailed Description
Definition at line 42 of file translator_fa.h.
Member Function Documentation
convertDigitsToFarsi() [1/2]
QCString TranslatorPersian::convertDigitsToFarsi (QCString str) [inline], [private]
Converts english digits of an input string to persian equivalents.
Definition at line 47 of file translator_fa.h.
    {
        QCString output;
        const char * PersianDigits[] = { "", "", "", "", "", "", "", "", "", "" };
        for(unsigned i=0; i<str.length(); i++)
        {
            if (str.at(i) >= '0' && str.at(i) <= '9')
                output += PersianDigits[ str.at(i) - '0' ];
            else
                output += str.at(i);
        }
        return output;
    }
References QCString::at(), and QCString::length().
Referenced by trDateTime().
convertDigitsToFarsi() [2/2]
QCString TranslatorPersian::convertDigitsToFarsi (QCString str) [inline], [private]
Converts english digits of an input string to persian equivalents.
Definition at line 47 of file translator_fa.h.
    {
        QCString output;
        const char * PersianDigits[] = { "", "", "", "", "", "", "", "", "", "" };
        for(unsigned i=0; i<str.length(); i++)
        {
            if (str.at(i) >= '0' && str.at(i) <= '9')
                output += PersianDigits[ str.at(i) - '0' ];
            else
                output += str.at(i);
        }
        return output;
    }
References QCString::at(), and QCString::length().
getLanguageString() [1/2]
virtual QCString TranslatorPersian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 99 of file translator_fa.h.
    {
      return "0x429 Persian (Iran)";
    }
getLanguageString() [2/2]
virtual QCString TranslatorPersian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 99 of file translator_fa.h.
    {
      return "0x429 Persian (Iran)";
    }
idLanguage() [1/2]
virtual QCString TranslatorPersian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in Persian using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 72 of file translator_fa.h.
    { return "persian"; }
idLanguage() [2/2]
virtual QCString TranslatorPersian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in Persian using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 72 of file translator_fa.h.
    { return "persian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorPersian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The Persian LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 89 of file translator_fa.h.
    {
      return "";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorPersian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The Persian LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 89 of file translator_fa.h.
    {
      return "";
    }
trAll() [1/2]
virtual QCString TranslatorPersian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1396 of file translator_fa.h.
    {
      return "";
    }
trAll() [2/2]
virtual QCString TranslatorPersian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1396 of file translator_fa.h.
    {
      return "";
    }
trAttention() [1/2]
virtual QCString TranslatorPersian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 960 of file translator_fa.h.
    {
      return "";
    }
trAttention() [2/2]
virtual QCString TranslatorPersian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 960 of file translator_fa.h.
    {
      return "";
    }
trAuthor() [1/2]
virtual QCString TranslatorPersian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1267 of file translator_fa.h.
    {
      QCString result((first_capital ? "Author" : "author"));
      if (!singular) result+="s";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorPersian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1267 of file translator_fa.h.
    {
      QCString result((first_capital ? "Author" : "author"));
      if (!singular) result+="s";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorPersian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1125 of file translator_fa.h.
    {
      return "";
    }
trBug() [2/2]
virtual QCString TranslatorPersian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1125 of file translator_fa.h.
    {
      return "";
    }
trBugList() [1/2]
virtual QCString TranslatorPersian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1130 of file translator_fa.h.
    {
      return " ";
    }
trBugList() [2/2]
virtual QCString TranslatorPersian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1130 of file translator_fa.h.
    {
      return " ";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorPersian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1517 of file translator_fa.h.
    {
      return " :";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorPersian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1517 of file translator_fa.h.
    {
      return " :";
    }
trCallGraph() [1/2]
virtual QCString TranslatorPersian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1401 of file translator_fa.h.
    {
      return " :";
    }
trCallGraph() [2/2]
virtual QCString TranslatorPersian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1401 of file translator_fa.h.
    {
      return " :";
    }
trClass() [1/2]
virtual QCString TranslatorPersian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1188 of file translator_fa.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorPersian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1188 of file translator_fa.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorPersian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 516 of file translator_fa.h.
    {
      return ""+clName+" :";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorPersian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 516 of file translator_fa.h.
    {
      return ""+clName+" :";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorPersian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 385 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return " ";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorPersian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 385 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return " ";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorPersian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1088 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorPersian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1088 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorPersian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 193 of file translator_fa.h.
    { return " "; }
trClassHierarchy() [2/2]
virtual QCString TranslatorPersian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 193 of file translator_fa.h.
    { return " "; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorPersian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 252 of file translator_fa.h.
    { return " :";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorPersian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 252 of file translator_fa.h.
    { return " :";
    }
trCode() [1/2]
virtual QCString TranslatorPersian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 860 of file translator_fa.h.
    {
      return "";
    }
trCode() [2/2]
virtual QCString TranslatorPersian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 860 of file translator_fa.h.
    {
      return "";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorPersian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 815 of file translator_fa.h.
    {
      return "Collaboration diagram for "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorPersian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 815 of file translator_fa.h.
    {
      return "Collaboration diagram for "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorPersian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 358 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorPersian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 358 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorPersian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1550 of file translator_fa.h.
    { return "Data Type Index"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorPersian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1550 of file translator_fa.h.
    { return "Data Type Index"; }
trCompoundList() [1/2]
virtual QCString TranslatorPersian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 197 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorPersian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 197 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorPersian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 266 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " :";
      }
      else
      {
        return " ... :";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorPersian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 266 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " :";
      }
      else
      {
        return " ... :";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorPersian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1538 of file translator_fa.h.
    { return " :"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorPersian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1538 of file translator_fa.h.
    { return " :"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorPersian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1530 of file translator_fa.h.
    { return " "; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorPersian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1530 of file translator_fa.h.
    { return " "; }
trCompoundMembers() [1/2]
virtual QCString TranslatorPersian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 214 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorPersian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 214 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorPersian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 280 of file translator_fa.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" ";
      }
      else
      {
        result+=" ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
          result+=" ";
      }
        else
      {
          result+=" ";
      }
      result+=" :";
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorPersian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 280 of file translator_fa.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" ";
      }
      else
      {
        result+=" ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
          result+=" ";
      }
        else
      {
          result+=" ";
      }
      result+=" :";
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorPersian::trCompoundMembersDescriptionFortran (bool) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1542 of file translator_fa.h.
    {
      return " ";
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorPersian::trCompoundMembersDescriptionFortran (bool) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1542 of file translator_fa.h.
    {
      return " ";
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorPersian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1534 of file translator_fa.h.
    { return " "; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorPersian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1534 of file translator_fa.h.
    { return " "; }
trCompoundReference() [1/2]
virtual QCString TranslatorPersian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 591 of file translator_fa.h.
    {
      QCString result;
      switch(compType)
      {
        case ClassDef::Class: result=" "; break;
        case ClassDef::Struct: result=" "; break;
        case ClassDef::Union: result=" Union"; break;
        case ClassDef::Interface: result=" Interface"; break;
        case ClassDef::Protocol: result=" Protocol"; break;
        case ClassDef::Category: result=" Category"; break;
        case ClassDef::Exception: result=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result=QCString(clName) + " " +result ;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorPersian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 591 of file translator_fa.h.
    {
      QCString result;
      switch(compType)
      {
        case ClassDef::Class: result=" "; break;
        case ClassDef::Struct: result=" "; break;
        case ClassDef::Union: result=" Union"; break;
        case ClassDef::Interface: result=" Interface"; break;
        case ClassDef::Protocol: result=" Protocol"; break;
        case ClassDef::Category: result=" Category"; break;
        case ClassDef::Exception: result=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result=QCString(clName) + " " +result ;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorPersian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1589 of file translator_fa.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Module"; break;
        case ClassDef::Struct: result+=" Type"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorPersian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1589 of file translator_fa.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Module"; break;
        case ClassDef::Struct: result+=" Type"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorPersian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 492 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorPersian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 492 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorPersian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 825 of file translator_fa.h.
    {
      return " ";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorPersian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 825 of file translator_fa.h.
    {
      return " ";
    }
trDataTypes() [1/2]
virtual QCString TranslatorPersian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1574 of file translator_fa.h.
    { return " "; }
trDataTypes() [2/2]
virtual QCString TranslatorPersian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1574 of file translator_fa.h.
    { return " "; }
trDate() [1/2]
virtual QCString TranslatorPersian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 530 of file translator_fa.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorPersian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 530 of file translator_fa.h.
    { return ""; }
trDateTime() [1/2]
virtual QCString TranslatorPersian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1760 of file translator_fa.h.
    {
      static const char *days[] = { "","","","","","","" };
      static const char *months[] = { "","","","","","","","","","","","" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return convertDigitsToFarsi(sdate);
    }
References convertDigitsToFarsi(), and QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorPersian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1760 of file translator_fa.h.
    {
      static const char *days[] = { "","","","","","","" };
      static const char *months[] = { "","","","","","","","","","","","" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return convertDigitsToFarsi(sdate);
    }
References convertDigitsToFarsi(), and QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorPersian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1776 of file translator_fa.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorPersian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1776 of file translator_fa.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorPersian::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1790 of file translator_fa.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorPersian::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1790 of file translator_fa.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorPersian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 792 of file translator_fa.h.
    {
      return ". @0 @1 ";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorPersian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 792 of file translator_fa.h.
    {
      return ". @0 @1 ";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorPersian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 181 of file translator_fa.h.
    { return " "; }
trDefinedIn() [2/2]
virtual QCString TranslatorPersian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 181 of file translator_fa.h.
    { return " "; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorPersian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 796 of file translator_fa.h.
    {
      return ". @0 ";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorPersian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 796 of file translator_fa.h.
    {
      return ". @0 ";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorPersian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 456 of file translator_fa.h.
    { return "Define Documentation"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorPersian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 456 of file translator_fa.h.
    { return "Define Documentation"; }
trDefines() [1/2]
virtual QCString TranslatorPersian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 420 of file translator_fa.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorPersian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 420 of file translator_fa.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorPersian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1115 of file translator_fa.h.
    {
      return ":";
    }
trDefineValue() [2/2]
virtual QCString TranslatorPersian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1115 of file translator_fa.h.
    {
      return ":";
    }
trDeprecated() [1/2]
virtual QCString TranslatorPersian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 805 of file translator_fa.h.
    {
      return " ";
    }
trDeprecated() [2/2]
virtual QCString TranslatorPersian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 805 of file translator_fa.h.
    {
      return " ";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorPersian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1324 of file translator_fa.h.
    {
      return " ";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorPersian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1324 of file translator_fa.h.
    {
      return " ";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorPersian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 114 of file translator_fa.h.
    { return " "; }
trDetailedDescription() [2/2]
virtual QCString TranslatorPersian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 114 of file translator_fa.h.
    { return " "; }
trDir() [1/2]
virtual QCString TranslatorPersian::trDir (bool , bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1491 of file translator_fa.h.
    {
      QCString result("");
      if (singular) result+=" "+result;
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorPersian::trDir (bool , bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1491 of file translator_fa.h.
    {
      QCString result("");
      if (singular) result+=" "+result;
      return result;
    }
trDirDocumentation() [1/2]
virtual QCString TranslatorPersian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1473 of file translator_fa.h.
    { return " "; }
trDirDocumentation() [2/2]
virtual QCString TranslatorPersian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1473 of file translator_fa.h.
    { return " "; }
trDirectories() [1/2]
virtual QCString TranslatorPersian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1479 of file translator_fa.h.
    { return " "; }
trDirectories() [2/2]
virtual QCString TranslatorPersian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1479 of file translator_fa.h.
    { return " "; }
trDirIndex() [1/2]
virtual QCString TranslatorPersian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1467 of file translator_fa.h.
    { return " "; }
trDirIndex() [2/2]
virtual QCString TranslatorPersian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1467 of file translator_fa.h.
    { return " "; }
trDirReference() [1/2]
virtual QCString TranslatorPersian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1485 of file translator_fa.h.
    { QCString result=dirName; result+=" "; return result; }
trDirReference() [2/2]
virtual QCString TranslatorPersian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1485 of file translator_fa.h.
    { QCString result=dirName; result+=" "; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorPersian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1699 of file translator_fa.h.
    {
      return QCString(name) + " Relation";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorPersian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1699 of file translator_fa.h.
    {
      return QCString(name) + " Relation";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorPersian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 340 of file translator_fa.h.
    { return ""; }
trDocumentation() [2/2]
virtual QCString TranslatorPersian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 340 of file translator_fa.h.
    { return ""; }
trEnumerations() [1/2]
virtual QCString TranslatorPersian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 432 of file translator_fa.h.
    { return ""; }
trEnumerations() [2/2]
virtual QCString TranslatorPersian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 432 of file translator_fa.h.
    { return ""; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorPersian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 468 of file translator_fa.h.
    { return " "; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorPersian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 468 of file translator_fa.h.
    { return " "; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorPersian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 474 of file translator_fa.h.
    { return " "; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorPersian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 474 of file translator_fa.h.
    { return " "; }
trEnumerationValues() [1/2]
virtual QCString TranslatorPersian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 450 of file translator_fa.h.
    { return " "; }
trEnumerationValues() [2/2]
virtual QCString TranslatorPersian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 450 of file translator_fa.h.
    { return " "; }
trEnumName() [1/2]
virtual QCString TranslatorPersian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 173 of file translator_fa.h.
    { return "enum "; }
trEnumName() [2/2]
virtual QCString TranslatorPersian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 173 of file translator_fa.h.
    { return "enum "; }
trEnumValue() [1/2]
virtual QCString TranslatorPersian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 177 of file translator_fa.h.
    { return "enum "; }
trEnumValue() [2/2]
virtual QCString TranslatorPersian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 177 of file translator_fa.h.
    { return "enum "; }
trEventDocumentation() [1/2]
virtual QCString TranslatorPersian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1341 of file translator_fa.h.
    {
      return " ";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorPersian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1341 of file translator_fa.h.
    {
      return " ";
    }
trEvents() [1/2]
virtual QCString TranslatorPersian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1336 of file translator_fa.h.
    {
      return " ";
    }
trEvents() [2/2]
virtual QCString TranslatorPersian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1336 of file translator_fa.h.
    {
      return " ";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorPersian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 410 of file translator_fa.h.
    { return " "; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorPersian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 410 of file translator_fa.h.
    { return " "; }
trExamples() [1/2]
virtual QCString TranslatorPersian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 244 of file translator_fa.h.
    { return " "; }
trExamples() [2/2]
virtual QCString TranslatorPersian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 244 of file translator_fa.h.
    { return " "; }
trExamplesDescription() [1/2]
virtual QCString TranslatorPersian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 325 of file translator_fa.h.
    { return " :"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorPersian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 325 of file translator_fa.h.
    { return " :"; }
trExceptions() [1/2]
virtual QCString TranslatorPersian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 546 of file translator_fa.h.
    { return " "; }
trExceptions() [2/2]
virtual QCString TranslatorPersian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 546 of file translator_fa.h.
    { return " "; }
trFile() [1/2]
virtual QCString TranslatorPersian::trFile (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1199 of file translator_fa.h.
    {
      QCString result("");
      if (!singular) result=result+" ";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorPersian::trFile (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1199 of file translator_fa.h.
    {
      QCString result("");
      if (!singular) result=result+" ";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorPersian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 404 of file translator_fa.h.
    { return " "; }
trFileDocumentation() [2/2]
virtual QCString TranslatorPersian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 404 of file translator_fa.h.
    { return " "; }
trFileIn() [1/2]
virtual QCString TranslatorPersian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1736 of file translator_fa.h.
    {
      return " "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorPersian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1736 of file translator_fa.h.
    {
      return " "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorPersian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 373 of file translator_fa.h.
    { return " "; }
trFileIndex() [2/2]
virtual QCString TranslatorPersian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 373 of file translator_fa.h.
    { return " "; }
trFileList() [1/2]
virtual QCString TranslatorPersian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 210 of file translator_fa.h.
    { return " "; }
trFileList() [2/2]
virtual QCString TranslatorPersian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 210 of file translator_fa.h.
    { return " "; }
trFileListDescription() [1/2]
virtual QCString TranslatorPersian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 257 of file translator_fa.h.
    {
      QCString result=" ";
      if (!extractAll) result+="() ";
      result+=" :";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorPersian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 257 of file translator_fa.h.
    {
      QCString result=" ";
      if (!extractAll) result+="() ";
      result+=" :";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorPersian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 227 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorPersian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 227 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorPersian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 314 of file translator_fa.h.
    {
      QCString result=" ... ";
      if (!extractAll) result+="() ";
      result+=" ";
      result+=" :";
      return result;
    }
trFileMembersDescription() [2/2]
virtual QCString TranslatorPersian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 314 of file translator_fa.h.
    {
      QCString result=" ... ";
      if (!extractAll) result+="() ";
      result+=" ";
      result+=" :";
      return result;
    }
trFileReference() [1/2]
virtual QCString TranslatorPersian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 613 of file translator_fa.h.
    {
      QCString result=fileName;
      result+=" ";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorPersian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 613 of file translator_fa.h.
    {
      QCString result=fileName;
      result+=" ";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorPersian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 573 of file translator_fa.h.
    { return " "; }
trFriends() [2/2]
virtual QCString TranslatorPersian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 573 of file translator_fa.h.
    { return " "; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorPersian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 480 of file translator_fa.h.
    { return " "; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorPersian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 480 of file translator_fa.h.
    { return " "; }
trFunctions() [1/2]
virtual QCString TranslatorPersian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 438 of file translator_fa.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorPersian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 438 of file translator_fa.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorPersian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 507 of file translator_fa.h.
    {
      QCString result = HtmlDivEnd + HtmlRightToLeft + QCString(" ") +date ;
      if (!projName.isEmpty()) result+=" "+projName;
      result+=" ";
      return result;
    }
References HtmlDivEnd, HtmlRightToLeft, and QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorPersian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 507 of file translator_fa.h.
    {
      QCString result = HtmlDivEnd + HtmlRightToLeft + QCString(" ") +date ;
      if (!projName.isEmpty()) result+=" "+projName;
      result+=" ";
      return result;
    }
References HtmlDivEnd, HtmlRightToLeft, and QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorPersian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 165 of file translator_fa.h.
    { QCString result=" ";
      if (!s.isEmpty()) result+=" "+s;
      result+=" ";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorPersian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 165 of file translator_fa.h.
    { QCString result=" ";
      if (!s.isEmpty()) result+=" "+s;
      result+=" ";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorPersian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 550 of file translator_fa.h.
    { return " "; }
trGeneratedBy() [2/2]
virtual QCString TranslatorPersian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 550 of file translator_fa.h.
    { return " "; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorPersian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 748 of file translator_fa.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" ";
      if (single) result+=""; else result+=" ";
      result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorPersian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 748 of file translator_fa.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" ";
      if (single) result+=""; else result+=" ";
      result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorPersian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1647 of file translator_fa.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="The documentation for this ";
      switch(compType)
      {
        case ClassDef::Class: result+="module"; break;
        case ClassDef::Struct: result+="type"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" was generated from the following file";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorPersian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1647 of file translator_fa.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="The documentation for this ";
      switch(compType)
      {
        case ClassDef::Class: result+="module"; break;
        case ClassDef::Struct: result+="type"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" was generated from the following file";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorPersian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1254 of file translator_fa.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorPersian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1254 of file translator_fa.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorPersian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1711 of file translator_fa.h.
    {
      return " ";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorPersian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1711 of file translator_fa.h.
    {
      return " ";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorPersian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 835 of file translator_fa.h.
    {
      return " .";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorPersian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 835 of file translator_fa.h.
    {
      return " .";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorPersian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 868 of file translator_fa.h.
    {
      return " ";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorPersian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 868 of file translator_fa.h.
    {
      return " ";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorPersian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 830 of file translator_fa.h.
    {
      return " .";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorPersian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 830 of file translator_fa.h.
    {
      return " .";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorPersian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 872 of file translator_fa.h.
    {
      return " ";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorPersian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 872 of file translator_fa.h.
    {
      return " ";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorPersian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 864 of file translator_fa.h.
    {
      return " ";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorPersian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 864 of file translator_fa.h.
    {
      return " ";
    }
trGroup() [1/2]
virtual QCString TranslatorPersian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1221 of file translator_fa.h.
    {
      QCString result((first_capital ? "Group" : "group"));
      if (!singular) result+="s";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorPersian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1221 of file translator_fa.h.
    {
      QCString result((first_capital ? "Group" : "group"));
      if (!singular) result+="s";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorPersian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 352 of file translator_fa.h.
    { return " "; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorPersian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 352 of file translator_fa.h.
    { return " "; }
trImplementedFromList() [1/2]
virtual QCString TranslatorPersian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1292 of file translator_fa.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorPersian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1292 of file translator_fa.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorPersian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1300 of file translator_fa.h.
    {
      return ". "+trWriteList(numEntries)+" ";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorPersian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1300 of file translator_fa.h.
    {
      return ". "+trWriteList(numEntries)+" ";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorPersian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_fa.h.
    {
      return " ";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorPersian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_fa.h.
    {
      return " ";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorPersian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 820 of file translator_fa.h.
    {
      return " "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorPersian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 820 of file translator_fa.h.
    {
      return " "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorPersian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1745 of file translator_fa.h.
    {
      return "Includes file in "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorPersian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1745 of file translator_fa.h.
    {
      return "Includes file in "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorPersian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 159 of file translator_fa.h.
    { return " ."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorPersian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 159 of file translator_fa.h.
    { return " ."; }
trInheritedByList() [1/2]
virtual QCString TranslatorPersian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 685 of file translator_fa.h.
    {
      return ". "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorPersian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 685 of file translator_fa.h.
    {
      return ". "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorPersian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 677 of file translator_fa.h.
    {
      return ". "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorPersian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 677 of file translator_fa.h.
    {
      return ". "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorPersian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 855 of file translator_fa.h.
    {
      return " :";
    }
trInitialValue() [2/2]
virtual QCString TranslatorPersian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 855 of file translator_fa.h.
    {
      return " :";
    }
trInvariant() [1/2]
virtual QCString TranslatorPersian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 850 of file translator_fa.h.
    {
      return "Invariant";
    }
trInvariant() [2/2]
virtual QCString TranslatorPersian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 850 of file translator_fa.h.
    {
      return "Invariant";
    }
trISOLang() [1/2]
virtual QCString TranslatorPersian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 94 of file translator_fa.h.
    {
      return "fa";
    }
trISOLang() [2/2]
virtual QCString TranslatorPersian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 94 of file translator_fa.h.
    {
      return "fa";
    }
trLegend() [1/2]
virtual QCString TranslatorPersian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1048 of file translator_fa.h.
    {
      return "";
    }
trLegend() [2/2]
virtual QCString TranslatorPersian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1048 of file translator_fa.h.
    {
      return "";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorPersian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 985 of file translator_fa.h.
    {
      return
        "This page explains how to interpret the graphs that are generated "
        "by doxygen.<p>\n"
        "Consider the following example:\n"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "If the \\c MAX_DOT_GRAPH_HEIGHT tag in the configuration file "
        "is set to 240 this will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>%A filled black box represents the struct or class for which the "
        "graph is generated.\n"
        "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.\n"
        "<li>%A box with a red border denotes a documented struct or class for"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries.\n"
        "</ul>\n"
        "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.\n"
        "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible.\n"
        "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "the template class it was instantiated from. The arrow is labeled with "
        "the template parameters of the instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorPersian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 985 of file translator_fa.h.
    {
      return
        "This page explains how to interpret the graphs that are generated "
        "by doxygen.<p>\n"
        "Consider the following example:\n"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "If the \\c MAX_DOT_GRAPH_HEIGHT tag in the configuration file "
        "is set to 240 this will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>%A filled black box represents the struct or class for which the "
        "graph is generated.\n"
        "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.\n"
        "<li>%A box with a red border denotes a documented struct or class for"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries.\n"
        "</ul>\n"
        "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.\n"
        "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible.\n"
        "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "the template class it was instantiated from. The arrow is labeled with "
        "the template parameters of the instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorPersian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 978 of file translator_fa.h.
    {
      return " ";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorPersian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 978 of file translator_fa.h.
    {
      return " ";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorPersian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 147 of file translator_fa.h.
    { return " "; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorPersian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 147 of file translator_fa.h.
    { return " "; }
trLoading() [1/2]
virtual QCString TranslatorPersian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1705 of file translator_fa.h.
    {
      return " ...";
    }
trLoading() [2/2]
virtual QCString TranslatorPersian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1705 of file translator_fa.h.
    {
      return " ...";
    }
trMainPage() [1/2]
virtual QCString TranslatorPersian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 780 of file translator_fa.h.
    { return " "; }
trMainPage() [2/2]
virtual QCString TranslatorPersian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 780 of file translator_fa.h.
    { return " "; }
trMember() [1/2]
virtual QCString TranslatorPersian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1243 of file translator_fa.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorPersian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1243 of file translator_fa.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorPersian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 130 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Field ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorPersian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 130 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Field ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorPersian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 122 of file translator_fa.h.
    { return " Enumeration "; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorPersian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 122 of file translator_fa.h.
    { return " Enumeration "; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorPersian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 126 of file translator_fa.h.
    { return " "; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorPersian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 126 of file translator_fa.h.
    { return " "; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorPersian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1526 of file translator_fa.h.
    { return " "; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorPersian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1526 of file translator_fa.h.
    { return " "; }
trMemberList() [1/2]
virtual QCString TranslatorPersian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 151 of file translator_fa.h.
    { return " "; }
trMemberList() [2/2]
virtual QCString TranslatorPersian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 151 of file translator_fa.h.
    { return " "; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorPersian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 118 of file translator_fa.h.
    { return " "; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorPersian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 118 of file translator_fa.h.
    { return " "; }
trModule() [1/2]
virtual QCString TranslatorPersian::trModule (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1638 of file translator_fa.h.
    {
      QCString result("");
      if (!singular) result+=" ";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorPersian::trModule (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1638 of file translator_fa.h.
    {
      QCString result("");
      if (!singular) result+=" ";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorPersian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 379 of file translator_fa.h.
    { return " "; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorPersian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 379 of file translator_fa.h.
    { return " "; }
trModuleIndex() [1/2]
virtual QCString TranslatorPersian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 346 of file translator_fa.h.
    { return " "; }
trModuleIndex() [2/2]
virtual QCString TranslatorPersian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 346 of file translator_fa.h.
    { return " "; }
trModuleReference() [1/2]
virtual QCString TranslatorPersian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1610 of file translator_fa.h.
    {
      QCString result=namespaceName;
      result+=" Module Reference";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorPersian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1610 of file translator_fa.h.
    {
      QCString result=namespaceName;
      result+=" Module Reference";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorPersian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 189 of file translator_fa.h.
    { return "Modules"; }
trModules() [2/2]
virtual QCString TranslatorPersian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 189 of file translator_fa.h.
    { return "Modules"; }
trModulesDescription() [1/2]
virtual QCString TranslatorPersian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 333 of file translator_fa.h.
    { return " :"; }
trModulesDescription() [2/2]
virtual QCString TranslatorPersian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 333 of file translator_fa.h.
    { return " :"; }
trModulesIndex() [1/2]
virtual QCString TranslatorPersian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1631 of file translator_fa.h.
    { return "Modules Index"; }
trModulesIndex() [2/2]
virtual QCString TranslatorPersian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1631 of file translator_fa.h.
    { return "Modules Index"; }
trModulesList() [1/2]
virtual QCString TranslatorPersian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1578 of file translator_fa.h.
    { return " "; }
trModulesList() [2/2]
virtual QCString TranslatorPersian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1578 of file translator_fa.h.
    { return " "; }
trModulesListDescription() [1/2]
virtual QCString TranslatorPersian::trModulesListDescription (bool) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1582 of file translator_fa.h.
    {
      QCString result=" ";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorPersian::trModulesListDescription (bool) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1582 of file translator_fa.h.
    {
      QCString result=" ";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorPersian::trModulesMemberDescription (bool) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1622 of file translator_fa.h.
    {
      QCString result=" ";
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorPersian::trModulesMemberDescription (bool) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1622 of file translator_fa.h.
    {
      QCString result=" ";
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorPersian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1618 of file translator_fa.h.
    { return " "; }
trModulesMembers() [2/2]
virtual QCString TranslatorPersian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1618 of file translator_fa.h.
    { return " "; }
trMonth() [1/2]
virtual QCString TranslatorPersian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1783 of file translator_fa.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorPersian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1783 of file translator_fa.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
virtual QCString TranslatorPersian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 143 of file translator_fa.h.
    { return "..."; }
trMore() [2/2]
virtual QCString TranslatorPersian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 143 of file translator_fa.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorPersian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1210 of file translator_fa.h.
    {
      QCString result((first_capital ? " " : " "));
      if (!singular) result+="";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorPersian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1210 of file translator_fa.h.
    {
      QCString result((first_capital ? " " : " "));
      if (!singular) result+="";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorPersian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 728 of file translator_fa.h.
    { return " "; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorPersian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 728 of file translator_fa.h.
    { return " "; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorPersian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 722 of file translator_fa.h.
    { return " "; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorPersian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 722 of file translator_fa.h.
    { return " "; }
trNamespaceList() [1/2]
virtual QCString TranslatorPersian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 558 of file translator_fa.h.
    { return " "; }
trNamespaceList() [2/2]
virtual QCString TranslatorPersian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 558 of file translator_fa.h.
    { return " "; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorPersian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 562 of file translator_fa.h.
    {
      QCString result=" ";
      if (!extractAll) result+="() ";
      result+=" :";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorPersian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 562 of file translator_fa.h.
    {
      QCString result=" ";
      if (!extractAll) result+="() ";
      result+=" :";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorPersian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 711 of file translator_fa.h.
    {
      QCString result=" ";
      if (!extractAll) result+="() ";
      result+=" ";
      result+=" :";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorPersian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 711 of file translator_fa.h.
    {
      QCString result=" ";
      if (!extractAll) result+="() ";
      result+=" ";
      result+=" :";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorPersian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 707 of file translator_fa.h.
    { return " "; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorPersian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 707 of file translator_fa.h.
    { return " "; }
trNamespaceReference() [1/2]
virtual QCString TranslatorPersian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 621 of file translator_fa.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorPersian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 621 of file translator_fa.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorPersian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 738 of file translator_fa.h.
    { return " "; }
trNamespaces() [2/2]
virtual QCString TranslatorPersian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 738 of file translator_fa.h.
    { return " "; }
trNoMatches() [1/2]
virtual QCString TranslatorPersian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1723 of file translator_fa.h.
    {
      return " ";
    }
trNoMatches() [2/2]
virtual QCString TranslatorPersian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1723 of file translator_fa.h.
    {
      return " ";
    }
trNote() [1/2]
virtual QCString TranslatorPersian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_fa.h.
    {
      return "";
    }
trNote() [2/2]
virtual QCString TranslatorPersian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_fa.h.
    {
      return "";
    }
trOverloadText() [1/2]
virtual QCString TranslatorPersian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1505 of file translator_fa.h.
    {
       return "This is an overloaded member function, "
              "provided for convenience. It differs from the above "
              "function only in what argument(s) it accepts.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorPersian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1505 of file translator_fa.h.
    {
       return "This is an overloaded member function, "
              "provided for convenience. It differs from the above "
              "function only in what argument(s) it accepts.";
    }
trPackage() [1/2]
virtual QCString TranslatorPersian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1100 of file translator_fa.h.
    {
      return "Package "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorPersian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1100 of file translator_fa.h.
    {
      return "Package "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorPersian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1377 of file translator_fa.h.
    {
      return " ";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorPersian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1377 of file translator_fa.h.
    {
      return " ";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorPersian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1359 of file translator_fa.h.
    {
      return " ";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorPersian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1359 of file translator_fa.h.
    {
      return " ";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorPersian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1105 of file translator_fa.h.
    {
      return " :";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorPersian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1105 of file translator_fa.h.
    {
      return " :";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorPersian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1363 of file translator_fa.h.
    {
      return " ";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorPersian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1363 of file translator_fa.h.
    {
      return " ";
    }
trPackages() [1/2]
virtual QCString TranslatorPersian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1110 of file translator_fa.h.
    {
      return " ";
    }
trPackages() [2/2]
virtual QCString TranslatorPersian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1110 of file translator_fa.h.
    {
      return " ";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorPersian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1352 of file translator_fa.h.
    {
      return " ";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorPersian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1352 of file translator_fa.h.
    {
      return " ";
    }
trPage() [1/2]
virtual QCString TranslatorPersian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_fa.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=" ";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorPersian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_fa.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=" ";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorPersian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 786 of file translator_fa.h.
    { return "."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorPersian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 786 of file translator_fa.h.
    { return "."; }
trPageIndex() [1/2]
virtual QCString TranslatorPersian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_fa.h.
    {
      return " ";
    }
trPageIndex() [2/2]
virtual QCString TranslatorPersian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_fa.h.
    {
      return " ";
    }
trParameters() [1/2]
virtual QCString TranslatorPersian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 542 of file translator_fa.h.
    { return ""; }
trParameters() [2/2]
virtual QCString TranslatorPersian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 542 of file translator_fa.h.
    { return ""; }
trPostcondition() [1/2]
virtual QCString TranslatorPersian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 845 of file translator_fa.h.
    {
      return " ";
    }
trPostcondition() [2/2]
virtual QCString TranslatorPersian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 845 of file translator_fa.h.
    {
      return " ";
    }
trPrecondition() [1/2]
virtual QCString TranslatorPersian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 840 of file translator_fa.h.
    {
      return " ";
    }
trPrecondition() [2/2]
virtual QCString TranslatorPersian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 840 of file translator_fa.h.
    {
      return " ";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorPersian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_fa.h.
    {
      return " () ";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorPersian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_fa.h.
    {
      return " () ";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorPersian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_fa.h.
    { return " "; }
trPrivateMembers() [2/2]
virtual QCString TranslatorPersian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_fa.h.
    { return " "; }
trPrivateSlots() [1/2]
virtual QCString TranslatorPersian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_fa.h.
    { return " Slot"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorPersian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_fa.h.
    { return " Slot"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorPersian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 920 of file translator_fa.h.
    {
      return " Type";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorPersian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 920 of file translator_fa.h.
    {
      return " Type";
    }
trProperties() [1/2]
virtual QCString TranslatorPersian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1073 of file translator_fa.h.
    {
      return " ";
    }
trProperties() [2/2]
virtual QCString TranslatorPersian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1073 of file translator_fa.h.
    {
      return " ";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorPersian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1078 of file translator_fa.h.
    {
      return " ";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorPersian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1078 of file translator_fa.h.
    {
      return " ";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorPersian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_fa.h.
    {
      return " () ";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorPersian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_fa.h.
    {
      return " () ";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorPersian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_fa.h.
    { return " "; }
trProtectedMembers() [2/2]
virtual QCString TranslatorPersian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_fa.h.
    { return " "; }
trProtectedSlots() [1/2]
virtual QCString TranslatorPersian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 638 of file translator_fa.h.
    { return " Slot"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorPersian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 638 of file translator_fa.h.
    { return " Slot"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorPersian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_fa.h.
    {
      return " Type";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorPersian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_fa.h.
    {
      return " Type";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorPersian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " () ";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorPersian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_fa.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " () ";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorPersian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 628 of file translator_fa.h.
    { return " "; }
trPublicMembers() [2/2]
virtual QCString TranslatorPersian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 628 of file translator_fa.h.
    { return " "; }
trPublicSlots() [1/2]
virtual QCString TranslatorPersian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 630 of file translator_fa.h.
    { return " Slot"; }
trPublicSlots() [2/2]
virtual QCString TranslatorPersian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 630 of file translator_fa.h.
    { return " Slot"; }
trPublicTypes() [1/2]
virtual QCString TranslatorPersian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_fa.h.
    {
      return " Type";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorPersian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_fa.h.
    {
      return " Type";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorPersian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_fa.h.
    {
      return " ";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorPersian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_fa.h.
    {
      return " ";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorPersian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 414 of file translator_fa.h.
    { return " "; }
trReferenceManual() [2/2]
virtual QCString TranslatorPersian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 414 of file translator_fa.h.
    { return " "; }
trReferences() [1/2]
virtual QCString TranslatorPersian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1280 of file translator_fa.h.
    {
      return " ";
    }
trReferences() [2/2]
virtual QCString TranslatorPersian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1280 of file translator_fa.h.
    {
      return " ";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorPersian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 693 of file translator_fa.h.
    {
      return "Reimplemented from "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorPersian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 693 of file translator_fa.h.
    {
      return "Reimplemented from "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorPersian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 701 of file translator_fa.h.
    {
      return " "+trWriteList(numEntries)+" ";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorPersian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 701 of file translator_fa.h.
    {
      return " "+trWriteList(numEntries)+" ";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorPersian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 583 of file translator_fa.h.
    { return " "; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorPersian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 583 of file translator_fa.h.
    { return " "; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorPersian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 106 of file translator_fa.h.
    { return " "; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorPersian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 106 of file translator_fa.h.
    { return " "; }
trRelatedPages() [1/2]
virtual QCString TranslatorPersian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 240 of file translator_fa.h.
    { return " "; }
trRelatedPages() [2/2]
virtual QCString TranslatorPersian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 240 of file translator_fa.h.
    { return " "; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorPersian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 329 of file translator_fa.h.
    { return " :"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorPersian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 329 of file translator_fa.h.
    { return " :"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorPersian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 110 of file translator_fa.h.
    { return "()"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorPersian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 110 of file translator_fa.h.
    { return "()"; }
trRemarks() [1/2]
virtual QCString TranslatorPersian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 956 of file translator_fa.h.
    {
      return "";
    }
trRemarks() [2/2]
virtual QCString TranslatorPersian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 956 of file translator_fa.h.
    {
      return "";
    }
trReturns() [1/2]
virtual QCString TranslatorPersian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 534 of file translator_fa.h.
    { return ""; }
trReturns() [2/2]
virtual QCString TranslatorPersian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 534 of file translator_fa.h.
    { return ""; }
trReturnValues() [1/2]
virtual QCString TranslatorPersian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 775 of file translator_fa.h.
    { return " "; }
trReturnValues() [2/2]
virtual QCString TranslatorPersian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 775 of file translator_fa.h.
    { return " "; }
trRTFansicp() [1/2]
virtual QCString TranslatorPersian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1164 of file translator_fa.h.
    {
      return "1256";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorPersian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1164 of file translator_fa.h.
    {
      return "1256";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorPersian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1173 of file translator_fa.h.
    {
      return "178";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorPersian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1173 of file translator_fa.h.
    {
      return "178";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorPersian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1179 of file translator_fa.h.
    {
      return "";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorPersian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1179 of file translator_fa.h.
    {
      return "";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorPersian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1312 of file translator_fa.h.
    {
      return "";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorPersian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1312 of file translator_fa.h.
    {
      return "";
    }
trSearch() [1/2]
virtual QCString TranslatorPersian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 248 of file translator_fa.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorPersian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 248 of file translator_fa.h.
    { return ""; }
trSearching() [1/2]
virtual QCString TranslatorPersian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1717 of file translator_fa.h.
    {
      return " ...";
    }
trSearching() [2/2]
virtual QCString TranslatorPersian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1717 of file translator_fa.h.
    {
      return " ...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorPersian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1444 of file translator_fa.h.
    {
      return "Matches:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorPersian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1444 of file translator_fa.h.
    {
      return "Matches:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorPersian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1425 of file translator_fa.h.
    {
      if (numDocuments==0)
      {
        return " .";
      }
      else if (numDocuments==1)
      {
        return " .";
      }
      else
      {
        return "Found <b>$num</b> documents matching your query. "
               "Showing best matches first.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorPersian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1425 of file translator_fa.h.
    {
      if (numDocuments==0)
      {
        return " .";
      }
      else if (numDocuments==1)
      {
        return " .";
      }
      else
      {
        return "Found <b>$num</b> documents matching your query. "
               "Showing best matches first.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorPersian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1413 of file translator_fa.h.
    {
      return " ";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorPersian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1413 of file translator_fa.h.
    {
      return " ";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorPersian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 538 of file translator_fa.h.
    { return "See also"; }
trSeeAlso() [2/2]
virtual QCString TranslatorPersian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 538 of file translator_fa.h.
    { return "See also"; }
trSignals() [1/2]
virtual QCString TranslatorPersian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 632 of file translator_fa.h.
    { return " "; }
trSignals() [2/2]
virtual QCString TranslatorPersian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 632 of file translator_fa.h.
    { return " "; }
trSince() [1/2]
virtual QCString TranslatorPersian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 968 of file translator_fa.h.
    {
      return "";
    }
trSince() [2/2]
virtual QCString TranslatorPersian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 968 of file translator_fa.h.
    {
      return "";
    }
trSourceFile() [1/2]
virtual QCString TranslatorPersian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1455 of file translator_fa.h.
    {
      return filename + " ";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorPersian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1455 of file translator_fa.h.
    {
      return filename + " ";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorPersian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1384 of file translator_fa.h.
    {
      return "Static Package Attributes";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorPersian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1384 of file translator_fa.h.
    {
      return "Static Package Attributes";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorPersian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1370 of file translator_fa.h.
    {
      return "Static Package Functions";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorPersian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1370 of file translator_fa.h.
    {
      return "Static Package Functions";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorPersian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_fa.h.
    {
      return " () ";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorPersian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_fa.h.
    {
      return " () ";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorPersian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 646 of file translator_fa.h.
    { return " "; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorPersian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 646 of file translator_fa.h.
    { return " "; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorPersian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_fa.h.
    {
      return " () ";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorPersian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_fa.h.
    {
      return " () ";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorPersian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_fa.h.
    { return " "; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorPersian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_fa.h.
    { return " "; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorPersian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_fa.h.
    {
      return " () ";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorPersian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_fa.h.
    {
      return " () ";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorPersian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 634 of file translator_fa.h.
    { return " "; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorPersian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 634 of file translator_fa.h.
    { return " "; }
trSubprogram() [1/2]
virtual QCString TranslatorPersian::trSubprogram (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1681 of file translator_fa.h.
    {
      QCString result("");
      if (!singular) result+=" ";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorPersian::trSubprogram (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1681 of file translator_fa.h.
    {
      QCString result("");
      if (!singular) result+=" ";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorPersian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1568 of file translator_fa.h.
    { return " "; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorPersian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1568 of file translator_fa.h.
    { return " "; }
trSubprograms() [1/2]
virtual QCString TranslatorPersian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1562 of file translator_fa.h.
    { return " "; }
trSubprograms() [2/2]
virtual QCString TranslatorPersian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1562 of file translator_fa.h.
    { return " "; }
trTest() [1/2]
virtual QCString TranslatorPersian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1058 of file translator_fa.h.
    {
      return "";
    }
trTest() [2/2]
virtual QCString TranslatorPersian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1058 of file translator_fa.h.
    {
      return "";
    }
trTestList() [1/2]
virtual QCString TranslatorPersian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1063 of file translator_fa.h.
    {
      return "Test List";
    }
trTestList() [2/2]
virtual QCString TranslatorPersian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1063 of file translator_fa.h.
    {
      return "Test List";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorPersian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 155 of file translator_fa.h.
    { return " "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorPersian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 155 of file translator_fa.h.
    { return " "; }
trTodo() [1/2]
virtual QCString TranslatorPersian::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 938 of file translator_fa.h.
    {
      return " ";
    }
trTodo() [2/2]
virtual QCString TranslatorPersian::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 938 of file translator_fa.h.
    {
      return " ";
    }
trTodoList() [1/2]
virtual QCString TranslatorPersian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 943 of file translator_fa.h.
    {
      return " ";
    }
trTodoList() [2/2]
virtual QCString TranslatorPersian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 943 of file translator_fa.h.
    {
      return " ";
    }
trType() [1/2]
virtual QCString TranslatorPersian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1671 of file translator_fa.h.
    {
      QCString result((first_capital ? "Type" : "type"));
      if (!singular) result+="s";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorPersian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1671 of file translator_fa.h.
    {
      QCString result((first_capital ? "Type" : "type"));
      if (!singular) result+="s";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorPersian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1689 of file translator_fa.h.
    {
      return "Type Constraints";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorPersian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1689 of file translator_fa.h.
    {
      return "Type Constraints";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorPersian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 462 of file translator_fa.h.
    { return "Typedef"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorPersian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 462 of file translator_fa.h.
    { return "Typedef"; }
trTypedefs() [1/2]
virtual QCString TranslatorPersian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 426 of file translator_fa.h.
    { return " "; }
trTypedefs() [2/2]
virtual QCString TranslatorPersian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 426 of file translator_fa.h.
    { return " "; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorPersian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1556 of file translator_fa.h.
    { return "Data Type Documentation"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorPersian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1556 of file translator_fa.h.
    { return "Data Type Documentation"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorPersian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 486 of file translator_fa.h.
    { return " "; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorPersian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 486 of file translator_fa.h.
    { return " "; }
trVariables() [1/2]
virtual QCString TranslatorPersian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 444 of file translator_fa.h.
    { return " "; }
trVariables() [2/2]
virtual QCString TranslatorPersian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 444 of file translator_fa.h.
    { return " "; }
trVersion() [1/2]
virtual QCString TranslatorPersian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 526 of file translator_fa.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorPersian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 526 of file translator_fa.h.
    { return ""; }
trWarning() [1/2]
virtual QCString TranslatorPersian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 522 of file translator_fa.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorPersian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 522 of file translator_fa.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorPersian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 652 of file translator_fa.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorPersian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 652 of file translator_fa.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_fa.h
doxygen/src/translator_fa.h