SearchIndexContext::Private Class Reference
Public Member Functions
Private (const SearchIndexInfo &info)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (const SearchIndexInfo &info)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant name () const
TemplateVariant text () const
TemplateVariant symbolIndices () const
TemplateVariant createSymbolIndices () const
TemplateVariant name () const
TemplateVariant text () const
TemplateVariant symbolIndices () const
TemplateVariant createSymbolIndices () const
Private Attributes
const SearchIndexInfo & m_info
CachedItem< TemplateVariant, Private, &Private::createSymbolIndices > m_symbolIndices
Static Private Attributes
static const PropertyMap< SearchIndexContext::Private > s_inst
Detailed Description
Definition at line 8757 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
SearchIndexContext::Private::Private (const SearchIndexInfo & info) [inline]
Definition at line 8760 of file context.cpp.
: m_info(info) {}
Private() [2/2]
SearchIndexContext::Private::Private (const SearchIndexInfo & info) [inline]
Definition at line 8760 of file context.cpp.
: m_info(info) {}
Member Function Documentation
createSymbolIndices() [1/2]
TemplateVariant SearchIndexContext::Private::createSymbolIndices () const [inline], [private]
Definition at line 8773 of file context.cpp.
    {
      return SymbolIndicesContext::alloc(m_info);
    }
References SymbolIndicesContext::alloc(), and m_info.
createSymbolIndices() [2/2]
TemplateVariant SearchIndexContext::Private::createSymbolIndices () const [inline], [private]
Definition at line 8773 of file context.cpp.
    {
      return SymbolIndicesContext::alloc(m_info);
    }
References SymbolIndicesContext::alloc().
fields() [1/2]
StringVector SearchIndexContext::Private::fields () const [inline]
Definition at line 8764 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector SearchIndexContext::Private::fields () const [inline]
Definition at line 8764 of file context.cpp.
{ return s_inst.fields(); }
get() [1/2]
TemplateVariant SearchIndexContext::Private::get (const QCString & n) const [inline]
Definition at line 8763 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant SearchIndexContext::Private::get (const QCString & n) const [inline]
Definition at line 8763 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
name() [1/2]
TemplateVariant SearchIndexContext::Private::name () const [inline], [private]
Definition at line 8768 of file context.cpp.
{ return m_info.name; }
References m_info, and SearchIndexInfo::name.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
TemplateVariant SearchIndexContext::Private::name () const [inline], [private]
Definition at line 8768 of file context.cpp.
{ return m_info.name; }
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
symbolIndices() [1/2]
TemplateVariant SearchIndexContext::Private::symbolIndices () const [inline], [private]
Definition at line 8770 of file context.cpp.
{ return m_symbolIndices.get(this); }
References m_symbolIndices.
symbolIndices() [2/2]
TemplateVariant SearchIndexContext::Private::symbolIndices () const [inline], [private]
Definition at line 8770 of file context.cpp.
{ return m_symbolIndices.get(this); }
text() [1/2]
TemplateVariant SearchIndexContext::Private::text () const [inline], [private]
Definition at line 8769 of file context.cpp.
{ return m_info.getText(); }
References SearchIndexInfo::getText, and m_info.
text() [2/2]
TemplateVariant SearchIndexContext::Private::text () const [inline], [private]
Definition at line 8769 of file context.cpp.
{ return m_info.getText(); }
Member Data Documentation
m_info
const SearchIndexInfo & SearchIndexContext::Private::m_info [private]
Definition at line 8778 of file context.cpp.
Referenced by createSymbolIndices(), name(), and text().
m_symbolIndices
CachedItem< TemplateVariant, Private, &Private::createSymbolIndices > SearchIndexContext::Private::m_symbolIndices [private]
Definition at line 8779 of file context.cpp.
Referenced by symbolIndices().
s_inst
const PropertyMap< SearchIndexContext::Private > SearchIndexContext::Private::s_inst [static], [private]
Initial value:
{
  { "name", &Private::name },
  { "text", &Private::text },
  { "symbolIndices",&Private::symbolIndices }
}
Definition at line 8780 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp