HtmlHelp Class Reference
#include <htmlhelp.h>
Classes
class Private
Public Member Functions
HtmlHelp ()
~HtmlHelp ()
HtmlHelp (HtmlHelp &&)
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex, bool addToNavIndex, const Definition *def)
void addIndexItem (const Definition *context, const MemberDef *md, const QCString &sectionAnchor, const QCString &title)
void addIndexFile (const QCString &name)
void addImageFile (const QCString &)
void addStyleSheetFile (const QCString &)
HtmlHelp ()
~HtmlHelp ()
HtmlHelp (HtmlHelp &&)
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex, bool addToNavIndex, const Definition *def)
void addIndexItem (const Definition *context, const MemberDef *md, const QCString &sectionAnchor, const QCString &title)
void addIndexFile (const QCString &name)
void addImageFile (const QCString &)
void addStyleSheetFile (const QCString &)
Static Public Attributes
static const QCString hhcFileName = `index.hhc`
static const QCString hhkFileName = `index.hhk`
static const QCString hhpFileName = `index.hhp`
Private Types
enum ImageNumber {
BOOK_CLOSED =1
, BOOK_OPEN
, BOOK_CLOSED_NEW
, BOOK_OPEN_NEW
,
FOLDER_CLOSED
, FOLDER_OPEN
, FOLDER_CLOSED_NEW
, FOLDER_OPEN_NEW
,
QUERY
, QUERY_NEW
, TEXT
, TEXT_NEW
,
WEB_DOC
, WEB_DOC_NEW
, WEB_LINK
, WEB_LINK_NEW
,
INFO
, INFO_NEW
, LINK
, LINK_NEW
,
BOOKLET
, BOOKLET_NEW
, EMAIL
, EMAIL_NEW
,
EMAIL2
, EMAIL2_NEW
, IMAGE
, IMAGE_NEW
,
AUDIO
, AUDIO_NEW
, MUSIC
, MUSIC_NEW
,
VIDEO
, VIDEO_NEW
, INDEX
, INDEX_NEW
,
IDEA
, IDEA_NEW
, NOTE
, NOTE_NEW
,
TOOL
, TOOL_NEW
, BOOK_CLOSED =1
, BOOK_OPEN
,
BOOK_CLOSED_NEW
, BOOK_OPEN_NEW
, FOLDER_CLOSED
, FOLDER_OPEN
,
FOLDER_CLOSED_NEW
, FOLDER_OPEN_NEW
, QUERY
, QUERY_NEW
,
TEXT
, TEXT_NEW
, WEB_DOC
, WEB_DOC_NEW
,
WEB_LINK
, WEB_LINK_NEW
, INFO
, INFO_NEW
,
LINK
, LINK_NEW
, BOOKLET
, BOOKLET_NEW
,
EMAIL
, EMAIL_NEW
, EMAIL2
, EMAIL2_NEW
,
IMAGE
, IMAGE_NEW
, AUDIO
, AUDIO_NEW
,
MUSIC
, MUSIC_NEW
, VIDEO
, VIDEO_NEW
,
INDEX
, INDEX_NEW
, IDEA
, IDEA_NEW
,
NOTE
, NOTE_NEW
, TOOL
, TOOL_NEW
 }
enum ImageNumber {
BOOK_CLOSED =1
, BOOK_OPEN
, BOOK_CLOSED_NEW
, BOOK_OPEN_NEW
,
FOLDER_CLOSED
, FOLDER_OPEN
, FOLDER_CLOSED_NEW
, FOLDER_OPEN_NEW
,
QUERY
, QUERY_NEW
, TEXT
, TEXT_NEW
,
WEB_DOC
, WEB_DOC_NEW
, WEB_LINK
, WEB_LINK_NEW
,
INFO
, INFO_NEW
, LINK
, LINK_NEW
,
BOOKLET
, BOOKLET_NEW
, EMAIL
, EMAIL_NEW
,
EMAIL2
, EMAIL2_NEW
, IMAGE
, IMAGE_NEW
,
AUDIO
, AUDIO_NEW
, MUSIC
, MUSIC_NEW
,
VIDEO
, VIDEO_NEW
, INDEX
, INDEX_NEW
,
IDEA
, IDEA_NEW
, NOTE
, NOTE_NEW
,
TOOL
, TOOL_NEW
, BOOK_CLOSED =1
, BOOK_OPEN
,
BOOK_CLOSED_NEW
, BOOK_OPEN_NEW
, FOLDER_CLOSED
, FOLDER_OPEN
,
FOLDER_CLOSED_NEW
, FOLDER_OPEN_NEW
, QUERY
, QUERY_NEW
,
TEXT
, TEXT_NEW
, WEB_DOC
, WEB_DOC_NEW
,
WEB_LINK
, WEB_LINK_NEW
, INFO
, INFO_NEW
,
LINK
, LINK_NEW
, BOOKLET
, BOOKLET_NEW
,
EMAIL
, EMAIL_NEW
, EMAIL2
, EMAIL2_NEW
,
IMAGE
, IMAGE_NEW
, AUDIO
, AUDIO_NEW
,
MUSIC
, MUSIC_NEW
, VIDEO
, VIDEO_NEW
,
INDEX
, INDEX_NEW
, IDEA
, IDEA_NEW
,
NOTE
, NOTE_NEW
, TOOL
, TOOL_NEW
 }
Private Member Functions
QCString recode (const QCString &s)
QCString recode (const QCString &s)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
A class that generated the HTML Help specific files.
These files can be used with the Microsoft HTML Help workshop to generate compressed HTML files (.chm).
Definition at line 33 of file htmlhelp.h.
Member Enumeration Documentation
ImageNumber [1/2]
enum HtmlHelp::ImageNumber [private]
used in imageNumber param of HTMLHelp::addContentsItem() function to specify document icon in tree view. Writes <param name=`ImageNumber` value=`xx`> in .HHC file.
Enumerator
BOOK_CLOSED
BOOK_OPEN
BOOK_CLOSED_NEW
BOOK_OPEN_NEW
FOLDER_CLOSED
FOLDER_OPEN
FOLDER_CLOSED_NEW
FOLDER_OPEN_NEW
QUERY
QUERY_NEW
TEXT
TEXT_NEW
WEB_DOC
WEB_DOC_NEW
WEB_LINK
WEB_LINK_NEW
INFO
INFO_NEW
LINK
LINK_NEW
BOOKLET
BOOKLET_NEW
EMAIL
EMAIL_NEW
EMAIL2
EMAIL2_NEW
IMAGE
IMAGE_NEW
AUDIO
AUDIO_NEW
MUSIC
MUSIC_NEW
VIDEO
VIDEO_NEW
INDEX
INDEX_NEW
IDEA
IDEA_NEW
NOTE
NOTE_NEW
TOOL
TOOL_NEW
BOOK_CLOSED
BOOK_OPEN
BOOK_CLOSED_NEW
BOOK_OPEN_NEW
FOLDER_CLOSED
FOLDER_OPEN
FOLDER_CLOSED_NEW
FOLDER_OPEN_NEW
QUERY
QUERY_NEW
TEXT
TEXT_NEW
WEB_DOC
WEB_DOC_NEW
WEB_LINK
WEB_LINK_NEW
INFO
INFO_NEW
LINK
LINK_NEW
BOOKLET
BOOKLET_NEW
EMAIL
EMAIL_NEW
EMAIL2
EMAIL2_NEW
IMAGE
IMAGE_NEW
AUDIO
AUDIO_NEW
MUSIC
MUSIC_NEW
VIDEO
VIDEO_NEW
INDEX
INDEX_NEW
IDEA
IDEA_NEW
NOTE
NOTE_NEW
TOOL
TOOL_NEW
Definition at line 38 of file htmlhelp.h.
                     {
      BOOK_CLOSED=1, BOOK_OPEN,
      BOOK_CLOSED_NEW, BOOK_OPEN_NEW,
      FOLDER_CLOSED, FOLDER_OPEN,
      FOLDER_CLOSED_NEW,FOLDER_OPEN_NEW,
      QUERY, QUERY_NEW,
      TEXT, TEXT_NEW,
      WEB_DOC, WEB_DOC_NEW,
      WEB_LINK, WEB_LINK_NEW,
      INFO, INFO_NEW,
      LINK, LINK_NEW,
      BOOKLET, BOOKLET_NEW,
      EMAIL, EMAIL_NEW,
      EMAIL2, EMAIL2_NEW,
      IMAGE, IMAGE_NEW,
      AUDIO, AUDIO_NEW,
      MUSIC, MUSIC_NEW,
      VIDEO, VIDEO_NEW,
      INDEX, INDEX_NEW,
      IDEA, IDEA_NEW,
      NOTE, NOTE_NEW,
      TOOL, TOOL_NEW
    };
ImageNumber [2/2]
enum HtmlHelp::ImageNumber [private]
used in imageNumber param of HTMLHelp::addContentsItem() function to specify document icon in tree view. Writes <param name=`ImageNumber` value=`xx`> in .HHC file.
Enumerator
BOOK_CLOSED
BOOK_OPEN
BOOK_CLOSED_NEW
BOOK_OPEN_NEW
FOLDER_CLOSED
FOLDER_OPEN
FOLDER_CLOSED_NEW
FOLDER_OPEN_NEW
QUERY
QUERY_NEW
TEXT
TEXT_NEW
WEB_DOC
WEB_DOC_NEW
WEB_LINK
WEB_LINK_NEW
INFO
INFO_NEW
LINK
LINK_NEW
BOOKLET
BOOKLET_NEW
EMAIL
EMAIL_NEW
EMAIL2
EMAIL2_NEW
IMAGE
IMAGE_NEW
AUDIO
AUDIO_NEW
MUSIC
MUSIC_NEW
VIDEO
VIDEO_NEW
INDEX
INDEX_NEW
IDEA
IDEA_NEW
NOTE
NOTE_NEW
TOOL
TOOL_NEW
BOOK_CLOSED
BOOK_OPEN
BOOK_CLOSED_NEW
BOOK_OPEN_NEW
FOLDER_CLOSED
FOLDER_OPEN
FOLDER_CLOSED_NEW
FOLDER_OPEN_NEW
QUERY
QUERY_NEW
TEXT
TEXT_NEW
WEB_DOC
WEB_DOC_NEW
WEB_LINK
WEB_LINK_NEW
INFO
INFO_NEW
LINK
LINK_NEW
BOOKLET
BOOKLET_NEW
EMAIL
EMAIL_NEW
EMAIL2
EMAIL2_NEW
IMAGE
IMAGE_NEW
AUDIO
AUDIO_NEW
MUSIC
MUSIC_NEW
VIDEO
VIDEO_NEW
INDEX
INDEX_NEW
IDEA
IDEA_NEW
NOTE
NOTE_NEW
TOOL
TOOL_NEW
Definition at line 38 of file htmlhelp.h.
                     {
      BOOK_CLOSED=1, BOOK_OPEN,
      BOOK_CLOSED_NEW, BOOK_OPEN_NEW,
      FOLDER_CLOSED, FOLDER_OPEN,
      FOLDER_CLOSED_NEW,FOLDER_OPEN_NEW,
      QUERY, QUERY_NEW,
      TEXT, TEXT_NEW,
      WEB_DOC, WEB_DOC_NEW,
      WEB_LINK, WEB_LINK_NEW,
      INFO, INFO_NEW,
      LINK, LINK_NEW,
      BOOKLET, BOOKLET_NEW,
      EMAIL, EMAIL_NEW,
      EMAIL2, EMAIL2_NEW,
      IMAGE, IMAGE_NEW,
      AUDIO, AUDIO_NEW,
      MUSIC, MUSIC_NEW,
      VIDEO, VIDEO_NEW,
      INDEX, INDEX_NEW,
      IDEA, IDEA_NEW,
      NOTE, NOTE_NEW,
      TOOL, TOOL_NEW
    };
Constructor & Destructor Documentation
HtmlHelp() [1/4]
HtmlHelp::HtmlHelp ()
Constructs an html object. The object has to be initialized before it can be used.
Definition at line 335 of file htmlhelp.cpp.
: p(std::make_unique<Private>()) {}
 HtmlHelp() [1/2]
HtmlHelp::~HtmlHelp () [default]
HtmlHelp() [2/4]
HtmlHelp::HtmlHelp (HtmlHelp &&) [default]
HtmlHelp() [3/4]
HtmlHelp::HtmlHelp ()
 HtmlHelp() [2/2]
HtmlHelp::~HtmlHelp ()
HtmlHelp() [4/4]
HtmlHelp::HtmlHelp (HtmlHelp &&)
Member Function Documentation
addContentsItem() [1/2]
void HtmlHelp::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex, bool addToNavIndex, const Definition * def)
Add an list item to the contents file.
Parameters
isDir boolean indicating if this is a dir or file entry
name the name of the item.
ref the URL of to the item.
file the file in which the item is defined.
anchor the anchor of the item.
separateIndex not used.
addToNavIndex not used.
def not used.
Definition at line 518 of file htmlhelp.cpp.
{
  p->ctsItemPresent = true;
  int i; for (i=0;i<p->dc;i++) p->cts << " ";
  p->cts << "<LI><OBJECT type=\"text/sitemap\">";
  p->cts << "<param name=\"Name\" value=\"" << convertToHtml(p->recoder.recode(name),TRUE) << "\">";
  if (!file.isEmpty()) // made file optional param - KPW
  {
    if (file[0]=='!' || file[0]=='^') // special markers for user defined URLs
    {
      p->cts << "<param name=\"";
      if (file[0]=='^') p->cts << "URL"; else p->cts << "Local";
      p->cts << "\" value=\"";
      p->cts << &file[1];
      p->cts << "\">";
    }
    else
    {
      QCString currFile = addHtmlExtensionIfMissing(file);
      QCString currAnc = anchor;
      p->cts << "<param name=\"Local\" value=\"";
      p->cts << currFile;
      if (p->prevFile == currFile && p->prevAnc.isEmpty() && currAnc.isEmpty())
      {
        currAnc = "top";
      }
      if (!currAnc.isEmpty()) p->cts << "#" << currAnc;
      p->cts << "\">";
      p->prevFile = currFile;
      p->prevAnc = currAnc;
    }
  }
  p->cts << "<param name=\"ImageNumber\" value=\"";
  if (isDir) // added - KPW
  {
    p->cts << static_cast<int>(BOOK_CLOSED);
  }
  else
  {
    p->cts << static_cast<int>(TEXT);
  }
  p->cts << "\">";
  p->cts << "</OBJECT>\n";
}
References addHtmlExtensionIfMissing(), BOOK_CLOSED, convertToHtml(), caseconvert::file, QCString::isEmpty(), setup::name, p, TEXT, and TRUE.
addContentsItem() [2/2]
void HtmlHelp::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex, bool addToNavIndex, const Definition * def)
addImageFile() [1/2]
void HtmlHelp::addImageFile (const QCString & fileName)
Definition at line 609 of file htmlhelp.cpp.
{
  p->imageFiles.insert(fileName.str());
}
References p, and QCString::str().
addImageFile() [2/2]
void HtmlHelp::addImageFile (const QCString &)
addIndexFile() [1/2]
void HtmlHelp::addIndexFile (const QCString & name)
Definition at line 456 of file htmlhelp.cpp.
{
  p->indexFiles.insert(s.str());
}
References p, and s.
addIndexFile() [2/2]
void HtmlHelp::addIndexFile (const QCString & name)
addIndexItem() [1/2]
void HtmlHelp::addIndexItem (const Definition * context, const MemberDef * md, const QCString & sectionAnchor, const QCString & title)
Definition at line 571 of file htmlhelp.cpp.
{
  if (md)
  {
    bool separateMemberPages = Config_getBool(SEPARATE_MEMBER_PAGES);
    if (context==0) // global member
    {
      if (md->getGroupDef())
        context = md->getGroupDef();
      else if (md->getFileDef())
        context = md->getFileDef();
    }
    if (context==0) return; // should not happen
    QCString cfname = md->getOutputFileBase();
    QCString argStr = md->argsString();
    QCString cfiname = context->getOutputFileBase();
    QCString level1 = context->name();
    QCString level2 = md->name() + argStr;
    QCString contRef = separateMemberPages ? cfname : cfiname;
    QCString memRef = cfname;
    QCString anchor = !sectionAnchor.isEmpty() ? sectionAnchor : md->anchor();
    p->index.addItem(level1,level2,contRef,anchor,TRUE,FALSE);
    p->index.addItem(level2,level1,memRef,anchor,TRUE,TRUE);
  }
  else if (context)
  {
    QCString level1 = !word.isEmpty() ? word : context->name();
    p->index.addItem(level1,QCString(),context->getOutputFileBase(),sectionAnchor,TRUE,FALSE);
  }
}
References MemberDef::anchor(), MemberDef::argsString(), Config_getBool, FALSE, MemberDef::getFileDef(), MemberDef::getGroupDef(), Definition::getOutputFileBase(), MemberDef::getOutputFileBase(), QCString::isEmpty(), Definition::name(), p, TRUE, and word.
addIndexItem() [2/2]
void HtmlHelp::addIndexItem (const Definition * context, const MemberDef * md, const QCString & sectionAnchor, const QCString & title)
addStyleSheetFile() [1/2]
void HtmlHelp::addStyleSheetFile (const QCString & fileName)
Definition at line 604 of file htmlhelp.cpp.
{
  p->styleFiles.insert(fileName.str());
}
References p, and QCString::str().
addStyleSheetFile() [2/2]
void HtmlHelp::addStyleSheetFile (const QCString &)
decContentsDepth() [1/2]
void HtmlHelp::decContentsDepth ()
Decrease the level of the contents hierarchy. This will end the unnumber HTML list.
See also
incContentsDepth()
Definition at line 501 of file htmlhelp.cpp.
{
  int i; for (i=0;i<p->dc;i++) p->cts << " ";
  p->cts << "</UL>\n";
  --p->dc;
}
References p.
decContentsDepth() [2/2]
void HtmlHelp::decContentsDepth ()
finalize() [1/2]
void HtmlHelp::finalize ()
Finalizes the HTML help. This will finish and close the htmlhelp contents file and the htmlhelp index file.
See also
initialize()
Definition at line 465 of file htmlhelp.cpp.
{
  // end the contents file
  p->cts << "</UL>\n";
  p->cts << "</BODY>\n";
  p->cts << "</HTML>\n";
  p->cts.close();
  p->index.writeFields(p->kts);
  // end the index file
  p->kts << "</UL>\n";
  p->kts << "</BODY>\n";
  p->kts << "</HTML>\n";
  p->kts.close();
  p->createProjectFile();
  p->recoder.finalize();
}
References p.
finalize() [2/2]
void HtmlHelp::finalize ()
incContentsDepth() [1/2]
void HtmlHelp::incContentsDepth ()
Increase the level of the contents hierarchy. This will start a new unnumbered HTML list in contents file.
See also
decContentsDepth()
Definition at line 490 of file htmlhelp.cpp.
{
  int i; for (i=0;i<p->dc+1;i++) p->cts << " ";
  p->cts << "<UL>\n";
  ++p->dc;
}
References p.
incContentsDepth() [2/2]
void HtmlHelp::incContentsDepth ()
initialize() [1/2]
void HtmlHelp::initialize ()
This will create a contents file (index.hhc) and a index file (index.hhk) and write the header of those files. It also creates a project file (index.hhp)
See also
finalize()
Definition at line 344 of file htmlhelp.cpp.
{
  p->recoder.initialize();
  /* open the contents file */
  QCString fName = Config_getString(HTML_OUTPUT) + "/" + hhcFileName;
  p->cts.open(fName.str(),std::ofstream::out | std::ofstream::binary);
  if (!p->cts.is_open())
  {
    term("Could not open file %s for writing\n",qPrint(fName));
  }
  /* Write the header of the contents file */
  p->cts << "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML//EN\">\n"
         "<HTML><HEAD></HEAD><BODY>\n"
         "<OBJECT type=\"text/site properties\">\n"
         "<param name=\"FrameName\" value=\"right\">\n"
         "</OBJECT>\n"
         "<UL>\n";
  /* open the index file */
  fName = Config_getString(HTML_OUTPUT) + "/" + hhkFileName;
  p->kts.open(fName.str(),std::ofstream::out | std::ofstream::binary);
  if (!p->kts.is_open())
  {
    term("Could not open file %s for writing\n",qPrint(fName));
  }
  /* Write the header of the contents file */
  p->kts << "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML//EN\">\n"
         "<HTML><HEAD></HEAD><BODY>\n"
         "<OBJECT type=\"text/site properties\">\n"
         "<param name=\"FrameName\" value=\"right\">\n"
         "</OBJECT>\n"
         "<UL>\n";
}
References Config_getString, hhcFileName, hhkFileName, out, p, qPrint(), QCString::str(), and term().
initialize() [2/2]
void HtmlHelp::initialize ()
recode() [1/2]
QCString HtmlHelp::recode (const QCString & s) [private]
recode() [2/2]
QCString HtmlHelp::recode (const QCString & s) [private]
Member Data Documentation
hhcFileName
static const QCString HtmlHelp::hhcFileName = `index.hhc` [inline], [static]
Definition at line 84 of file htmlhelp.h.
Referenced by HtmlHelp::Private::createProjectFile(), and initialize().
hhkFileName
static const QCString HtmlHelp::hhkFileName = `index.hhk` [inline], [static]
Definition at line 85 of file htmlhelp.h.
Referenced by HtmlHelp::Private::createProjectFile(), and initialize().
hhpFileName
static const QCString HtmlHelp::hhpFileName = `index.hhp` [inline], [static]
Definition at line 86 of file htmlhelp.h.
Referenced by HtmlHelp::Private::createProjectFile(), and runHtmlHelpCompiler().
p
std::unique_ptr< Private > HtmlHelp::p [private]
Definition at line 89 of file htmlhelp.h.
Referenced by addContentsItem(), addImageFile(), addIndexFile(), addIndexItem(), addStyleSheetFile(), decContentsDepth(), finalize(), incContentsDepth(), and initialize().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/htmlhelp.h
doxygen/src/htmlhelp.h
doxygen/build/doxygen/src/htmlhelp.cpp
doxygen/src/htmlhelp.cpp