vhdl::parser::CharStream Class Reference
#include <CharStream.h>
Public Member Functions
void setTabSize (int i)
int getTabSize (int i)
virtual int getColumn ()
virtual int getLine ()
virtual int getEndColumn ()
virtual int getEndLine ()
virtual int getBeginColumn ()
virtual int getBeginLine ()
virtual bool getTrackLineColumn ()
virtual void setTrackLineColumn (bool val)
virtual void backup (int amount)
virtual JJChar BeginToken ()
virtual JJChar readChar ()
virtual void ExpandBuff (bool wrapAround)
virtual void FillBuff ()
virtual JJString GetImage ()
virtual JJString GetSuffix (int len)
virtual void DeleteBuffers ()
virtual ~CharStream ()
bool endOfInput ()
CharStream (const JJChar *buf, int sz, int startline, int startcolumn, int buffersize)
CharStream (const JJChar *buf, int sz, int startline, int startcolumn)
CharStream (const JJString &str, int startline, int startcolumn, int buffersize)
CharStream (const JJString &str, int startline, int startcolumn)
CharStream (ReaderStream *input_stream, int startline, int startcolumn, int buffersize)
CharStream (ReaderStream *input_stream, int startline, int startcolumn)
CharStream (ReaderStream *input_stream)
virtual void ReInit (ReaderStream *input_stream, int startline, int startcolumn, int buffersize)
virtual void ReInit (ReaderStream *input_stream, int startline, int startcolumn)
virtual void ReInit (ReaderStream *input_stream)
virtual void ReInit (const JJString &str, int startline, int startcolumn, int buffersize)
virtual void ReInit (const JJString &str, int startline, int startcolumn)
virtual void adjustBeginLineColumn (int newLine, int newCol)
void setTabSize (int i)
int getTabSize (int i)
virtual int getColumn ()
virtual int getLine ()
virtual int getEndColumn ()
virtual int getEndLine ()
virtual int getBeginColumn ()
virtual int getBeginLine ()
virtual bool getTrackLineColumn ()
virtual void setTrackLineColumn (bool val)
virtual void backup (int amount)
virtual JJChar BeginToken ()
virtual JJChar readChar ()
virtual void ExpandBuff (bool wrapAround)
virtual void FillBuff ()
virtual JJString GetImage ()
virtual JJString GetSuffix (int len)
virtual void DeleteBuffers ()
virtual ~CharStream ()
bool endOfInput ()
CharStream (const JJChar *buf, int sz, int startline, int startcolumn, int buffersize)
CharStream (const JJChar *buf, int sz, int startline, int startcolumn)
CharStream (const JJString &str, int startline, int startcolumn, int buffersize)
CharStream (const JJString &str, int startline, int startcolumn)
CharStream (ReaderStream *input_stream, int startline, int startcolumn, int buffersize)
CharStream (ReaderStream *input_stream, int startline, int startcolumn)
CharStream (ReaderStream *input_stream)
virtual void ReInit (ReaderStream *input_stream, int startline, int startcolumn, int buffersize)
virtual void ReInit (ReaderStream *input_stream, int startline, int startcolumn)
virtual void ReInit (ReaderStream *input_stream)
virtual void ReInit (const JJString &str, int startline, int startcolumn, int buffersize)
virtual void ReInit (const JJString &str, int startline, int startcolumn)
virtual void adjustBeginLineColumn (int newLine, int newCol)
Protected Member Functions
virtual void UpdateLineColumn (JJChar c)
virtual void UpdateLineColumn (JJChar c)
Protected Attributes
int * bufline
int * bufcolumn
JJChar * buffer
int bufpos
int bufsize
int tokenBegin
int column
int line
bool prevCharIsCR
bool prevCharIsLF
int available
int maxNextCharInd
int inBuf
int tabSize
bool trackLineColumn
ReaderStream * inputStream
bool deleteStream
Private Member Functions
int getBufcolumn (int pos)
int getBufline (int pos)
int getBufcolumn (int pos)
int getBufline (int pos)
Detailed Description
This class describes a character stream that maintains line and column number positions of the characters. It also has the capability to backup the stream to some extent. An implementation of this class is used in the TokenManager implementation generated by JavaCCParser.
All the methods except backup can be implemented in any fashion. backup needs to be implemented correctly for the correct operation of the lexer. Rest of the methods are all used to get information like line number, column number and the string that constitutes a token and are not used by the lexer. Hence their implementation won't affect the generated lexer's operation.
Definition at line 31 of file CharStream.h.
Constructor & Destructor Documentation
 CharStream() [1/2]
virtual vhdl::parser::CharStream::~CharStream () [inline], [virtual]
Definition at line 155 of file CharStream.h.
                        {
    if (deleteStream) {
     delete inputStream;
    }
    DeleteBuffers();
  }
References DeleteBuffers(), deleteStream, and inputStream.
CharStream() [1/14]
vhdl::parser::CharStream::CharStream (const JJChar * buf, int sz, int startline, int startcolumn, int buffersize) [inline]
Definition at line 166 of file CharStream.h.
                                                       :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(JJString(buf, sz), startline, startcolumn, buffersize);
  }
References ReInit().
CharStream() [2/14]
vhdl::parser::CharStream::CharStream (const JJChar * buf, int sz, int startline, int startcolumn) [inline]
Definition at line 175 of file CharStream.h.
                                                                        :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(JJString(buf, sz), startline, startcolumn, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
CharStream() [3/14]
vhdl::parser::CharStream::CharStream (const JJString & str, int startline, int startcolumn, int buffersize) [inline]
Definition at line 183 of file CharStream.h.
                                                       :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(str, startline, startcolumn, buffersize);
  }
References ReInit().
CharStream() [4/14]
vhdl::parser::CharStream::CharStream (const JJString & str, int startline, int startcolumn) [inline]
Definition at line 192 of file CharStream.h.
                                                                  :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(str, startline, startcolumn, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
CharStream() [5/14]
vhdl::parser::CharStream::CharStream (ReaderStream * input_stream, int startline, int startcolumn, int buffersize) [inline]
Definition at line 200 of file CharStream.h.
                                              :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(input_stream, startline, startcolumn, buffersize);
  }
References ReInit().
CharStream() [6/14]
vhdl::parser::CharStream::CharStream (ReaderStream * input_stream, int startline, int startcolumn) [inline]
Definition at line 209 of file CharStream.h.
                                                                         :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(input_stream, startline, startcolumn, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
CharStream() [7/14]
vhdl::parser::CharStream::CharStream (ReaderStream * input_stream) [inline]
Definition at line 217 of file CharStream.h.
                                         :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(input_stream, 1, 1, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
 CharStream() [2/2]
virtual vhdl::parser::CharStream::~CharStream () [inline], [virtual]
Definition at line 155 of file CharStream.h.
                        {
    if (deleteStream) {
     delete inputStream;
    }
    DeleteBuffers();
  }
References DeleteBuffers(), deleteStream, and inputStream.
CharStream() [8/14]
vhdl::parser::CharStream::CharStream (const JJChar * buf, int sz, int startline, int startcolumn, int buffersize) [inline]
Definition at line 166 of file CharStream.h.
                                                       :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(JJString(buf, sz), startline, startcolumn, buffersize);
  }
References ReInit().
CharStream() [9/14]
vhdl::parser::CharStream::CharStream (const JJChar * buf, int sz, int startline, int startcolumn) [inline]
Definition at line 175 of file CharStream.h.
                                                                        :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(JJString(buf, sz), startline, startcolumn, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
CharStream() [10/14]
vhdl::parser::CharStream::CharStream (const JJString & str, int startline, int startcolumn, int buffersize) [inline]
Definition at line 183 of file CharStream.h.
                                                       :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(str, startline, startcolumn, buffersize);
  }
References ReInit().
CharStream() [11/14]
vhdl::parser::CharStream::CharStream (const JJString & str, int startline, int startcolumn) [inline]
Definition at line 192 of file CharStream.h.
                                                                  :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(str, startline, startcolumn, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
CharStream() [12/14]
vhdl::parser::CharStream::CharStream (ReaderStream * input_stream, int startline, int startcolumn, int buffersize) [inline]
Definition at line 200 of file CharStream.h.
                                              :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(input_stream, startline, startcolumn, buffersize);
  }
References ReInit().
CharStream() [13/14]
vhdl::parser::CharStream::CharStream (ReaderStream * input_stream, int startline, int startcolumn) [inline]
Definition at line 209 of file CharStream.h.
                                                                         :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(input_stream, startline, startcolumn, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
CharStream() [14/14]
vhdl::parser::CharStream::CharStream (ReaderStream * input_stream) [inline]
Definition at line 217 of file CharStream.h.
                                         :
    bufline(nullptr), bufcolumn(nullptr), buffer(nullptr), bufpos(0), bufsize(0),
    tokenBegin(0), column(0), line(0), prevCharIsCR(false), prevCharIsLF(false),
    available(0), maxNextCharInd(0), inBuf(0), tabSize(1), trackLineColumn(true),
    inputStream(nullptr), deleteStream(false) {
    ReInit(input_stream, 1, 1, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
Member Function Documentation
adjustBeginLineColumn() [1/2]
void vhdl::parser::CharStream::adjustBeginLineColumn (int newLine, int newCol) [virtual]
Definition at line 73 of file CharStream.cc.
                                                              {
  int start = tokenBegin;
  int len;
  if (bufpos >= tokenBegin) {
    len = bufpos - tokenBegin + inBuf + 1;
  } else {
    len = bufsize - tokenBegin + bufpos + 1 + inBuf;
  }
  int i = 0, j = 0, k = 0;
  int nextColDiff = 0, columnDiff = 0;
  while (i < len && bufline[j = start % bufsize] ==
         bufline[k = (start + 1) % bufsize]) {
    bufline[j] = newLine;
    nextColDiff = columnDiff + bufcolumn[k] - bufcolumn[j];
    bufcolumn[j] = newCol + columnDiff;
    columnDiff = nextColDiff;
    i++;
    start++;
  }
  if (i < len) {
    bufline[j] = newLine++;
    bufcolumn[j] = newCol + columnDiff;
    while (i++ < len) {
      if (bufline[j = start % bufsize] != bufline[(start + 1) % bufsize])
        bufline[j] = newLine++;
      else
        bufline[j] = newLine;
      start++;
    }
  }
  line = bufline[j];
  column = bufcolumn[j];
}
References bufcolumn, bufline, bufpos, bufsize, column, inBuf, len, line, newLine(), and tokenBegin.
adjustBeginLineColumn() [2/2]
virtual void vhdl::parser::CharStream::adjustBeginLineColumn (int newLine, int newCol) [virtual]
backup() [1/2]
virtual void vhdl::parser::CharStream::backup (int amount) [inline], [virtual]
Backs up the input stream by amount steps. Lexer calls this method if it had already read some characters, but could not use them to match a (longer) token. So, they will be used again as the prefix of the next token and it is the implementation's responsibility to do this right.
Definition at line 69 of file CharStream.h.
                                         {
    inBuf += amount;
    bufpos -= amount;
    if (bufpos < 0) {
      bufpos += bufsize;
    }
  }
References bufpos, bufsize, and inBuf.
Referenced by FillBuff().
backup() [2/2]
virtual void vhdl::parser::CharStream::backup (int amount) [inline], [virtual]
Backs up the input stream by amount steps. Lexer calls this method if it had already read some characters, but could not use them to match a (longer) token. So, they will be used again as the prefix of the next token and it is the implementation's responsibility to do this right.
Definition at line 69 of file CharStream.h.
                                         {
    inBuf += amount;
    bufpos -= amount;
    if (bufpos < 0) {
      bufpos += bufsize;
    }
  }
References bufpos, bufsize, and inBuf.
BeginToken() [1/2]
virtual JJChar vhdl::parser::CharStream::BeginToken () [inline], [virtual]
Returns the next character that marks the beginning of the next token. All characters must remain in the buffer between two successive calls to this method to implement backup correctly.
Definition at line 82 of file CharStream.h.
                                     {
    tokenBegin = -1;
    JJChar c = readChar();
    tokenBegin = bufpos;
    return c;
  }
References bufpos, c, readChar(), and tokenBegin.
BeginToken() [2/2]
virtual JJChar vhdl::parser::CharStream::BeginToken () [inline], [virtual]
Returns the next character that marks the beginning of the next token. All characters must remain in the buffer between two successive calls to this method to implement backup correctly.
Definition at line 82 of file CharStream.h.
                                     {
    tokenBegin = -1;
    JJChar c = readChar();
    tokenBegin = bufpos;
    return c;
  }
References bufpos, c, readChar(), and tokenBegin.
DeleteBuffers() [1/2]
void vhdl::parser::CharStream::DeleteBuffers () [virtual]
The lexer calls this function to indicate that it is done with the stream and hence implementations can free any resources held by this class.
Definition at line 67 of file CharStream.cc.
                               {
  delete[] buffer;
  delete[] bufline;
  delete[] bufcolumn;
}
References bufcolumn, buffer, and bufline.
Referenced by ExpandBuff(), ReInit(), and ~CharStream().
DeleteBuffers() [2/2]
virtual void vhdl::parser::CharStream::DeleteBuffers () [virtual]
The lexer calls this function to indicate that it is done with the stream and hence implementations can free any resources held by this class.
endOfInput() [1/2]
bool vhdl::parser::CharStream::endOfInput () [inline]
Definition at line 162 of file CharStream.h.
                    {
    return inBuf == 0 && bufpos + 1 >= maxNextCharInd && inputStream->endOfInput();
  }
References bufpos, ReaderStream::endOfInput(), inBuf, inputStream, and maxNextCharInd.
endOfInput() [2/2]
bool vhdl::parser::CharStream::endOfInput () [inline]
Definition at line 162 of file CharStream.h.
                    {
    return inBuf == 0 && bufpos + 1 >= maxNextCharInd && inputStream->endOfInput();
  }
References bufpos, ReaderStream::endOfInput(), inBuf, inputStream, and maxNextCharInd.
ExpandBuff() [1/2]
void vhdl::parser::CharStream::ExpandBuff (bool wrapAround) [virtual]
Definition at line 113 of file CharStream.cc.
                                           {
  JJChar *newbuffer = new JJChar[bufsize + 2048];
  int *newbufline = new int[bufsize + 2048];
  int *newbufcolumn = new int[bufsize + 2048];
  if (wrapAround) {
    ArrayCopy(buffer, tokenBegin, newbuffer, 0, bufsize - tokenBegin);
    ArrayCopy(buffer, 0, newbuffer, bufsize - tokenBegin, bufpos);
    ArrayCopy(bufline, tokenBegin, newbufline, 0, bufsize - tokenBegin);
    ArrayCopy(bufline, 0, newbufline, bufsize - tokenBegin, bufpos);
    ArrayCopy(bufcolumn, tokenBegin, newbufcolumn, 0, bufsize - tokenBegin);
    ArrayCopy(bufcolumn, 0, newbufcolumn, bufsize - tokenBegin, bufpos);
    bufpos += (bufsize - tokenBegin);
  } else {
    ArrayCopy(buffer, tokenBegin, newbuffer, 0, bufsize - tokenBegin);
    ArrayCopy(bufline, tokenBegin, newbufline, 0, bufsize - tokenBegin);
    ArrayCopy(bufcolumn, tokenBegin, newbufcolumn, 0, bufsize - tokenBegin);
    bufpos -= tokenBegin;
  }
  maxNextCharInd = bufpos;
  DeleteBuffers();
  buffer = newbuffer;
  bufline = newbufline;
  bufcolumn = newbufcolumn;
  bufsize += 2048;
  available = bufsize;
  tokenBegin = 0;
}
References anonymous_namespace{CharStream.cc}::ArrayCopy(), available, bufcolumn, buffer, bufline, bufpos, bufsize, DeleteBuffers(), maxNextCharInd, and tokenBegin.
Referenced by FillBuff().
ExpandBuff() [2/2]
virtual void vhdl::parser::CharStream::ExpandBuff (bool wrapAround) [virtual]
FillBuff() [1/2]
void vhdl::parser::CharStream::FillBuff () [virtual]
Definition at line 143 of file CharStream.cc.
                          {
  if (maxNextCharInd == available) {
    if (available == bufsize) {
      if (tokenBegin > 2048) {
        bufpos = maxNextCharInd = 0;
        available = tokenBegin;
      } else if (tokenBegin < 0) {
        bufpos = maxNextCharInd = 0;
      } else {
        ExpandBuff(false);
      }
    } else if (available > tokenBegin) {
      available = bufsize;
    } else if ((tokenBegin - available) < 2048) {
      ExpandBuff(true);
    } else {
      available = tokenBegin;
    }
  }
  size_t i = inputStream->read(buffer, maxNextCharInd, available - maxNextCharInd);
  if (i > 0) {
    maxNextCharInd += i;
  } else {
    --bufpos;
    backup(0);
    if (tokenBegin == -1) {
      tokenBegin = bufpos;
    }
  }
}
References available, backup(), buffer, bufpos, bufsize, ExpandBuff(), inputStream, maxNextCharInd, ReaderStream::read(), and tokenBegin.
Referenced by readChar().
FillBuff() [2/2]
virtual void vhdl::parser::CharStream::FillBuff () [virtual]
getBeginColumn() [1/2]
virtual int vhdl::parser::CharStream::getBeginColumn () [inline], [virtual]
Definition at line 57 of file CharStream.h.
{ return getBufcolumn(tokenBegin); }
References getBufcolumn(), and tokenBegin.
getBeginColumn() [2/2]
virtual int vhdl::parser::CharStream::getBeginColumn () [inline], [virtual]
Definition at line 57 of file CharStream.h.
{ return getBufcolumn(tokenBegin); }
References getBufcolumn(), and tokenBegin.
getBeginLine() [1/2]
virtual int vhdl::parser::CharStream::getBeginLine () [inline], [virtual]
Definition at line 58 of file CharStream.h.
{ return getBufline(tokenBegin); }
References getBufline(), and tokenBegin.
getBeginLine() [2/2]
virtual int vhdl::parser::CharStream::getBeginLine () [inline], [virtual]
Definition at line 58 of file CharStream.h.
{ return getBufline(tokenBegin); }
References getBufline(), and tokenBegin.
getBufcolumn() [1/2]
int vhdl::parser::CharStream::getBufcolumn (int pos) [inline], [private]
Definition at line 37 of file CharStream.h.
                            {
    if (trackLineColumn && pos>=0) {
      return bufcolumn[pos];
    } else {
      return -1;
    }
  }
References bufcolumn, and trackLineColumn.
Referenced by getBeginColumn(), getColumn(), and getEndColumn().
getBufcolumn() [2/2]
int vhdl::parser::CharStream::getBufcolumn (int pos) [inline], [private]
Definition at line 37 of file CharStream.h.
                            {
    if (trackLineColumn && pos>=0) {
      return bufcolumn[pos];
    } else {
      return -1;
    }
  }
References bufcolumn, and trackLineColumn.
getBufline() [1/2]
int vhdl::parser::CharStream::getBufline (int pos) [inline], [private]
Definition at line 44 of file CharStream.h.
                          {
    if (trackLineColumn && pos>=0) {
      return bufline[pos];
    } else {
      return -1;
    }
  }
References bufline, and trackLineColumn.
Referenced by getBeginLine(), getEndLine(), and getLine().
getBufline() [2/2]
int vhdl::parser::CharStream::getBufline (int pos) [inline], [private]
Definition at line 44 of file CharStream.h.
                          {
    if (trackLineColumn && pos>=0) {
      return bufline[pos];
    } else {
      return -1;
    }
  }
References bufline, and trackLineColumn.
getColumn() [1/2]
virtual int vhdl::parser::CharStream::getColumn () [inline], [virtual]
Definition at line 53 of file CharStream.h.
{ return getBufcolumn(bufpos); }
References bufpos, and getBufcolumn().
getColumn() [2/2]
virtual int vhdl::parser::CharStream::getColumn () [inline], [virtual]
Definition at line 53 of file CharStream.h.
{ return getBufcolumn(bufpos); }
References bufpos, and getBufcolumn().
getEndColumn() [1/2]
virtual int vhdl::parser::CharStream::getEndColumn () [inline], [virtual]
Definition at line 55 of file CharStream.h.
{ return getBufcolumn(bufpos); }
References bufpos, and getBufcolumn().
getEndColumn() [2/2]
virtual int vhdl::parser::CharStream::getEndColumn () [inline], [virtual]
Definition at line 55 of file CharStream.h.
{ return getBufcolumn(bufpos); }
References bufpos, and getBufcolumn().
getEndLine() [1/2]
virtual int vhdl::parser::CharStream::getEndLine () [inline], [virtual]
Definition at line 56 of file CharStream.h.
{ return getBufline(bufpos); }
References bufpos, and getBufline().
getEndLine() [2/2]
virtual int vhdl::parser::CharStream::getEndLine () [inline], [virtual]
Definition at line 56 of file CharStream.h.
{ return getBufline(bufpos); }
References bufpos, and getBufline().
GetImage() [1/2]
virtual JJString vhdl::parser::CharStream::GetImage () [inline], [virtual]
Returns a string made up of characters from the marked token beginning to the current buffer position. Implementations can return anything that they want to. For example, for efficiency, one might decide to just return NULL, which is a valid implementation.
Definition at line 129 of file CharStream.h.
                              {
    if (bufpos >= tokenBegin)
      return JJString(buffer + tokenBegin, bufpos - tokenBegin + 1);
    else
      return JJString(buffer + tokenBegin, bufsize - tokenBegin).append(buffer, bufpos + 1);
  }
References buffer, bufpos, bufsize, and tokenBegin.
GetImage() [2/2]
virtual JJString vhdl::parser::CharStream::GetImage () [inline], [virtual]
Returns a string made up of characters from the marked token beginning to the current buffer position. Implementations can return anything that they want to. For example, for efficiency, one might decide to just return NULL, which is a valid implementation.
Definition at line 129 of file CharStream.h.
                              {
    if (bufpos >= tokenBegin)
      return JJString(buffer + tokenBegin, bufpos - tokenBegin + 1);
    else
      return JJString(buffer + tokenBegin, bufsize - tokenBegin).append(buffer, bufpos + 1);
  }
References buffer, bufpos, bufsize, and tokenBegin.
getLine() [1/2]
virtual int vhdl::parser::CharStream::getLine () [inline], [virtual]
Definition at line 54 of file CharStream.h.
{ return getBufline(bufpos); }
References bufpos, and getBufline().
getLine() [2/2]
virtual int vhdl::parser::CharStream::getLine () [inline], [virtual]
Definition at line 54 of file CharStream.h.
{ return getBufline(bufpos); }
References bufpos, and getBufline().
GetSuffix() [1/2]
virtual JJString vhdl::parser::CharStream::GetSuffix (int len) [inline], [virtual]
Returns an array of characters that make up the suffix of length 'len' for the currently matched token. This is used to build up the matched string for use in actions in the case of MORE. A simple and inefficient implementation of this is as follows :
Definition at line 142 of file CharStream.h.
                                      {
    if ((bufpos + 1) >= len) {
      return JJString(buffer + bufpos - len + 1, len);
    }
    return JJString(buffer + bufsize - (len - bufpos - 1), len - bufpos - 1).append(buffer, bufpos + 1);
  }
References buffer, bufpos, bufsize, and len.
GetSuffix() [2/2]
virtual JJString vhdl::parser::CharStream::GetSuffix (int len) [inline], [virtual]
Returns an array of characters that make up the suffix of length 'len' for the currently matched token. This is used to build up the matched string for use in actions in the case of MORE. A simple and inefficient implementation of this is as follows :
Definition at line 142 of file CharStream.h.
                                      {
    if ((bufpos + 1) >= len) {
      return JJString(buffer + bufpos - len + 1, len);
    }
    return JJString(buffer + bufsize - (len - bufpos - 1), len - bufpos - 1).append(buffer, bufpos + 1);
  }
References buffer, bufpos, bufsize, and len.
getTabSize() [1/2]
int vhdl::parser::CharStream::getTabSize (int i) [inline]
Definition at line 34 of file CharStream.h.
{ return tabSize; }
References tabSize.
getTabSize() [2/2]
int vhdl::parser::CharStream::getTabSize (int i) [inline]
Definition at line 34 of file CharStream.h.
{ return tabSize; }
References tabSize.
getTrackLineColumn() [1/2]
virtual bool vhdl::parser::CharStream::getTrackLineColumn () [inline], [virtual]
Definition at line 60 of file CharStream.h.
{ return trackLineColumn; }
References trackLineColumn.
getTrackLineColumn() [2/2]
virtual bool vhdl::parser::CharStream::getTrackLineColumn () [inline], [virtual]
Definition at line 60 of file CharStream.h.
{ return trackLineColumn; }
References trackLineColumn.
readChar() [1/2]
virtual JJChar vhdl::parser::CharStream::readChar () [inline], [virtual]
Returns the next character from the selected input. The method of selecting the input is the responsibility of the class implementing this class.
Definition at line 95 of file CharStream.h.
                                   {
    if (inBuf > 0) {
      --inBuf;
      ++bufpos;
      if (bufpos == bufsize) {
        bufpos = 0;
      }
      return buffer[bufpos];
    }
    ++bufpos;
    if (bufpos >= maxNextCharInd) {
      FillBuff();
    }
    JJChar c = buffer[bufpos];
    if (trackLineColumn) {
      UpdateLineColumn(c);
    }
    return c;
  }
References buffer, bufpos, bufsize, c, FillBuff(), inBuf, maxNextCharInd, trackLineColumn, and UpdateLineColumn().
Referenced by BeginToken().
readChar() [2/2]
virtual JJChar vhdl::parser::CharStream::readChar () [inline], [virtual]
Returns the next character from the selected input. The method of selecting the input is the responsibility of the class implementing this class.
Definition at line 95 of file CharStream.h.
                                   {
    if (inBuf > 0) {
      --inBuf;
      ++bufpos;
      if (bufpos == bufsize) {
        bufpos = 0;
      }
      return buffer[bufpos];
    }
    ++bufpos;
    if (bufpos >= maxNextCharInd) {
      FillBuff();
    }
    JJChar c = buffer[bufpos];
    if (trackLineColumn) {
      UpdateLineColumn(c);
    }
    return c;
  }
References buffer, bufpos, bufsize, c, FillBuff(), inBuf, maxNextCharInd, trackLineColumn, and UpdateLineColumn().
ReInit() [1/10]
virtual void vhdl::parser::CharStream::ReInit (const JJString & str, int startline, int startcolumn) [inline], [virtual]
Definition at line 238 of file CharStream.h.
                                       {
    ReInit(str, startline, startcolumn, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
ReInit() [2/10]
virtual void vhdl::parser::CharStream::ReInit (const JJString & str, int startline, int startcolumn) [inline], [virtual]
Definition at line 238 of file CharStream.h.
                                       {
    ReInit(str, startline, startcolumn, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
ReInit() [3/10]
void vhdl::parser::CharStream::ReInit (const JJString & str, int startline, int startcolumn, int buffersize) [virtual]
Definition at line 36 of file CharStream.cc.
                                                         {
  StringReaderStream *stream = new StringReaderStream(str);
  ReInit(stream, startline, startcolumn, buffersize);
  deleteStream = true;
}
References deleteStream, and ReInit().
ReInit() [4/10]
virtual void vhdl::parser::CharStream::ReInit (const JJString & str, int startline, int startcolumn, int buffersize) [virtual]
ReInit() [5/10]
virtual void vhdl::parser::CharStream::ReInit (ReaderStream * input_stream) [inline], [virtual]
Definition at line 231 of file CharStream.h.
                                                  {
    ReInit(input_stream, 1, 1, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
ReInit() [6/10]
virtual void vhdl::parser::CharStream::ReInit (ReaderStream * input_stream) [inline], [virtual]
Definition at line 231 of file CharStream.h.
                                                  {
    ReInit(input_stream, 1, 1, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
ReInit() [7/10]
virtual void vhdl::parser::CharStream::ReInit (ReaderStream * input_stream, int startline, int startcolumn) [inline], [virtual]
Definition at line 227 of file CharStream.h.
                                                                                  {
    ReInit(input_stream, startline, startcolumn, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
ReInit() [8/10]
virtual void vhdl::parser::CharStream::ReInit (ReaderStream * input_stream, int startline, int startcolumn) [inline], [virtual]
Definition at line 227 of file CharStream.h.
                                                                                  {
    ReInit(input_stream, startline, startcolumn, INITIAL_BUFFER_SIZE);
  }
References INITIAL_BUFFER_SIZE, and ReInit().
ReInit() [9/10]
void vhdl::parser::CharStream::ReInit (ReaderStream * input_stream, int startline, int startcolumn, int buffersize) [virtual]
Definition at line 43 of file CharStream.cc.
                                                         {
  if (deleteStream) {
   delete inputStream;
  }
  if (buffer) {
    DeleteBuffers();
  }
  available = bufsize = buffersize;
  buffer = new JJChar[buffersize];
  bufline = new int[buffersize];
  bufcolumn = new int[buffersize];
  column = startcolumn - 1;
  inputStream = input_stream;
  line = startline;
  prevCharIsLF = prevCharIsCR = false;
  tokenBegin = inBuf = maxNextCharInd = 0;
  bufpos = -1;
  deleteStream = false;
}
References available, bufcolumn, buffer, bufline, bufpos, bufsize, column, DeleteBuffers(), deleteStream, inBuf, inputStream, line, maxNextCharInd, prevCharIsCR, prevCharIsLF, and tokenBegin.
Referenced by CharStream(), and ReInit().
ReInit() [10/10]
virtual void vhdl::parser::CharStream::ReInit (ReaderStream * input_stream, int startline, int startcolumn, int buffersize) [virtual]
setTabSize() [1/2]
void vhdl::parser::CharStream::setTabSize (int i) [inline]
Definition at line 33 of file CharStream.h.
{ tabSize = i; }
References tabSize.
setTabSize() [2/2]
void vhdl::parser::CharStream::setTabSize (int i) [inline]
Definition at line 33 of file CharStream.h.
{ tabSize = i; }
References tabSize.
setTrackLineColumn() [1/2]
virtual void vhdl::parser::CharStream::setTrackLineColumn (bool val) [inline], [virtual]
Definition at line 61 of file CharStream.h.
{ trackLineColumn = val; }
References trackLineColumn, and testsqlite3::val.
setTrackLineColumn() [2/2]
virtual void vhdl::parser::CharStream::setTrackLineColumn (bool val) [inline], [virtual]
Definition at line 61 of file CharStream.h.
{ trackLineColumn = val; }
References trackLineColumn, and testsqlite3::val.
UpdateLineColumn() [1/2]
void vhdl::parser::CharStream::UpdateLineColumn (JJChar c) [protected], [virtual]
Definition at line 175 of file CharStream.cc.
                                          {
  column++;
  if (prevCharIsLF) {
    prevCharIsLF = false;
    column = 1;
    line++;
  } else if (prevCharIsCR) {
    prevCharIsCR = false;
    if (c == '\n') {
      prevCharIsLF = true;
    } else {
      column = 1;
      line++;
    }
  }
  switch (c) {
    case '\r' :
      prevCharIsCR = true;
      break;
    case '\n' :
      prevCharIsLF = true;
      break;
    case '\t' :
      column--;
      column += (tabSize - (column % tabSize));
      break;
    default :
      break;
  }
  bufline[bufpos] = line;
  bufcolumn[bufpos] = column;
}
References bufcolumn, bufline, bufpos, c, column, line, prevCharIsCR, prevCharIsLF, and tabSize.
Referenced by readChar().
UpdateLineColumn() [2/2]
virtual void vhdl::parser::CharStream::UpdateLineColumn (JJChar c) [protected], [virtual]
Member Data Documentation
available
int vhdl::parser::CharStream::available [protected]
Definition at line 258 of file CharStream.h.
Referenced by ExpandBuff(), FillBuff(), and ReInit().
bufcolumn
int * vhdl::parser::CharStream::bufcolumn [protected]
Definition at line 249 of file CharStream.h.
Referenced by adjustBeginLineColumn(), DeleteBuffers(), ExpandBuff(), getBufcolumn(), ReInit(), and UpdateLineColumn().
buffer
JJChar * vhdl::parser::CharStream::buffer [protected]
Definition at line 250 of file CharStream.h.
Referenced by DeleteBuffers(), ExpandBuff(), FillBuff(), GetImage(), GetSuffix(), readChar(), and ReInit().
bufline
int * vhdl::parser::CharStream::bufline [protected]
Definition at line 248 of file CharStream.h.
Referenced by adjustBeginLineColumn(), DeleteBuffers(), ExpandBuff(), getBufline(), ReInit(), and UpdateLineColumn().
bufpos
int vhdl::parser::CharStream::bufpos [protected]
Definition at line 251 of file CharStream.h.
Referenced by adjustBeginLineColumn(), backup(), BeginToken(), endOfInput(), ExpandBuff(), FillBuff(), getColumn(), getEndColumn(), getEndLine(), GetImage(), getLine(), GetSuffix(), readChar(), ReInit(), and UpdateLineColumn().
bufsize
int vhdl::parser::CharStream::bufsize [protected]
Definition at line 252 of file CharStream.h.
Referenced by adjustBeginLineColumn(), backup(), ExpandBuff(), FillBuff(), GetImage(), GetSuffix(), readChar(), and ReInit().
column
int vhdl::parser::CharStream::column [protected]
Definition at line 254 of file CharStream.h.
Referenced by doxmlparser.compound.locationType::__init__(), adjustBeginLineColumn(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_column(), ReInit(), doxmlparser.compound.locationType::set_column(), and UpdateLineColumn().
deleteStream
bool vhdl::parser::CharStream::deleteStream [protected]
Definition at line 264 of file CharStream.h.
Referenced by ReInit(), and ~CharStream().
inBuf
int vhdl::parser::CharStream::inBuf [protected]
Definition at line 260 of file CharStream.h.
Referenced by adjustBeginLineColumn(), backup(), endOfInput(), readChar(), and ReInit().
inputStream
ReaderStream * vhdl::parser::CharStream::inputStream [protected]
Definition at line 263 of file CharStream.h.
Referenced by endOfInput(), FillBuff(), ReInit(), and ~CharStream().
line
int vhdl::parser::CharStream::line [protected]
Definition at line 255 of file CharStream.h.
Referenced by doxmlparser.compound.locationType::__init__(), adjustBeginLineColumn(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_line(), ReInit(), doxmlparser.compound.locationType::set_line(), and UpdateLineColumn().
maxNextCharInd
int vhdl::parser::CharStream::maxNextCharInd [protected]
Definition at line 259 of file CharStream.h.
Referenced by endOfInput(), ExpandBuff(), FillBuff(), readChar(), and ReInit().
prevCharIsCR
bool vhdl::parser::CharStream::prevCharIsCR [protected]
Definition at line 256 of file CharStream.h.
Referenced by ReInit(), and UpdateLineColumn().
prevCharIsLF
bool vhdl::parser::CharStream::prevCharIsLF [protected]
Definition at line 257 of file CharStream.h.
Referenced by ReInit(), and UpdateLineColumn().
tabSize
int vhdl::parser::CharStream::tabSize [protected]
Definition at line 261 of file CharStream.h.
Referenced by getTabSize(), setTabSize(), and UpdateLineColumn().
tokenBegin
int vhdl::parser::CharStream::tokenBegin [protected]
Definition at line 253 of file CharStream.h.
Referenced by adjustBeginLineColumn(), BeginToken(), ExpandBuff(), FillBuff(), getBeginColumn(), getBeginLine(), GetImage(), and ReInit().
trackLineColumn
bool vhdl::parser::CharStream::trackLineColumn [protected]
Definition at line 262 of file CharStream.h.
Referenced by getBufcolumn(), getBufline(), getTrackLineColumn(), readChar(), and setTrackLineColumn().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/vhdlparser/CharStream.h
doxygen/vhdlparser/CharStream.h
doxygen/build/doxygen/vhdlparser/CharStream.cc
doxygen/vhdlparser/CharStream.cc