CiteInfoImpl Class Reference
Public Member Functions
CiteInfoImpl (const QCString &label, const QCString &text=QCString())
virtual QCString label () const
virtual QCString text () const
void setText (const QCString &s)
CiteInfoImpl (const QCString &label, const QCString &text=QCString())
virtual QCString label () const
virtual QCString text () const
void setText (const QCString &s)
Private Attributes
QCString m_label
QCString m_text
Detailed Description
Definition at line 42 of file cite.cpp.
Constructor & Destructor Documentation
CiteInfoImpl() [1/2]
CiteInfoImpl::CiteInfoImpl (const QCString & label, const QCString & text = QCString()) [inline]
Definition at line 45 of file cite.cpp.
    : m_label(label), m_text(text) { }
CiteInfoImpl() [2/2]
CiteInfoImpl::CiteInfoImpl (const QCString & label, const QCString & text = QCString()) [inline]
Definition at line 45 of file cite.cpp.
    : m_label(label), m_text(text) { }
Member Function Documentation
label() [1/2]
virtual QCString CiteInfoImpl::label () const [inline], [virtual]
Implements CiteInfo.
Definition at line 48 of file cite.cpp.
{ return m_label; }
References m_label.
Referenced by doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.nodeType::buildChildren(), doxmlparser.compound.nodeType::exportChildren(), doxmlparser.compound.nodeType::get_label(), doxmlparser.compound.nodeType::hasContent_(), and doxmlparser.compound.nodeType::set_label().
label() [2/2]
virtual QCString CiteInfoImpl::label () const [inline], [virtual]
Implements CiteInfo.
Definition at line 48 of file cite.cpp.
{ return m_label; }
References m_label.
Referenced by doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.nodeType::buildChildren(), doxmlparser.compound.nodeType::exportChildren(), doxmlparser.compound.nodeType::get_label(), doxmlparser.compound.nodeType::hasContent_(), and doxmlparser.compound.nodeType::set_label().
setText() [1/2]
void CiteInfoImpl::setText (const QCString & s) [inline]
Definition at line 51 of file cite.cpp.
{ m_text = s; }
References m_text, and s.
setText() [2/2]
void CiteInfoImpl::setText (const QCString & s) [inline]
Definition at line 51 of file cite.cpp.
{ m_text = s; }
References m_text, and s.
text() [1/2]
virtual QCString CiteInfoImpl::text () const [inline], [virtual]
Implements CiteInfo.
Definition at line 49 of file cite.cpp.
{ return m_text; }
References m_text.
text() [2/2]
virtual QCString CiteInfoImpl::text () const [inline], [virtual]
Implements CiteInfo.
Definition at line 49 of file cite.cpp.
{ return m_text; }
References m_text.
Member Data Documentation
m_label
QCString CiteInfoImpl::m_label [private]
Definition at line 54 of file cite.cpp.
Referenced by label().
m_text
QCString CiteInfoImpl::m_text [private]
Definition at line 55 of file cite.cpp.
Referenced by setText(), and text().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/cite.cpp
doxygen/src/cite.cpp