DocURL Class Reference
#include <docnode.h>
Public Member Functions
DocURL (DocParser *parser, DocNodeVariant *parent, const QCString &url, bool isEmail)
QCString url () const
bool isEmail () const
DocURL (DocParser *parser, DocNodeVariant *parent, const QCString &url, bool isEmail)
QCString url () const
bool isEmail () const
Private Attributes
QCString m_url
bool m_isEmail = false
Additional Inherited Members
Detailed Description
Node representing a URL (or email address)
Definition at line 180 of file docnode.h.
Constructor & Destructor Documentation
DocURL() [1/2]
DocURL::DocURL (DocParser * parser, DocNodeVariant * parent, const QCString & url, bool isEmail) [inline]
Definition at line 183 of file docnode.h.
                                                                                      :
      DocNode(parser,parent), m_url(url), m_isEmail(isEmail) {}
DocURL() [2/2]
DocURL::DocURL (DocParser * parser, DocNodeVariant * parent, const QCString & url, bool isEmail) [inline]
Definition at line 183 of file docnode.h.
                                                                                      :
      DocNode(parser,parent), m_url(url), m_isEmail(isEmail) {}
Member Function Documentation
isEmail() [1/2]
bool DocURL::isEmail () const [inline]
Definition at line 186 of file docnode.h.
{ return m_isEmail; }
References m_isEmail.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
isEmail() [2/2]
bool DocURL::isEmail () const [inline]
Definition at line 186 of file docnode.h.
{ return m_isEmail; }
References m_isEmail.
url() [1/2]
QCString DocURL::url () const [inline]
Definition at line 185 of file docnode.h.
{ return m_url; }
References m_url.
Referenced by doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docURLLink::buildAttributes(), doxmlparser.compound.docURLLink::exportAttributes(), doxmlparser.compound.docURLLink::get_url(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), TextDocVisitor::operator()(), and doxmlparser.compound.docURLLink::set_url().
url() [2/2]
QCString DocURL::url () const [inline]
Definition at line 185 of file docnode.h.
{ return m_url; }
References m_url.
Referenced by doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docURLLink::buildAttributes(), doxmlparser.compound.docURLLink::exportAttributes(), doxmlparser.compound.docURLLink::get_url(), and doxmlparser.compound.docURLLink::set_url().
Member Data Documentation
m_isEmail
bool DocURL::m_isEmail = false [private]
Definition at line 190 of file docnode.h.
Referenced by isEmail().
m_url
QCString DocURL::m_url [private]
Definition at line 189 of file docnode.h.
Referenced by url().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h