ColorPicker Class Reference
#include <wizard.h>
Public Types
enum Mode {
Hue
, Saturation
, Gamma
, Hue
,
Saturation
, Gamma
 }
enum Mode {
Hue
, Saturation
, Gamma
, Hue
,
Saturation
, Gamma
 }
Public Slots
void setCol (int h, int s, int g)
void setCol (int h, int s, int g)
Signals
void newHsv (int h, int s, int g)
void newHsv (int h, int s, int g)
Public Member Functions
ColorPicker (Mode m)
~ColorPicker ()
ColorPicker (Mode m)
~ColorPicker ()
Protected Member Functions
void paintEvent (QPaintEvent *)
void mouseMoveEvent (QMouseEvent *)
void mousePressEvent (QMouseEvent *)
void paintEvent (QPaintEvent *)
void mouseMoveEvent (QMouseEvent *)
void mousePressEvent (QMouseEvent *)
Private Types
enum { foff = 3
, coff = 4
 }
enum { foff = 3
, coff = 4
 }
Private Member Functions
int y2hue (int y)
int y2sat (int y)
int y2gam (int y)
int hue2y (int hue)
int sat2y (int sat)
int gam2y (int gamma)
void setHue (int v)
void setSat (int v)
void setGam (int v)
int y2hue (int y)
int y2sat (int y)
int y2gam (int y)
int hue2y (int hue)
int sat2y (int sat)
int gam2y (int gamma)
void setHue (int v)
void setSat (int v)
void setGam (int v)
Private Attributes
QPixmap * m_pix = 0
Mode m_mode = Hue
int m_gam = 0
int m_hue = 0
int m_sat = 0
Detailed Description
Definition at line 55 of file wizard.h.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
foff
coff
Definition at line 76 of file wizard.h.
{ foff = 3, coff = 4 }; //frame and contents offset
anonymous enum
anonymous enum [private]
Enumerator
foff
coff
Definition at line 76 of file wizard.h.
{ foff = 3, coff = 4 }; //frame and contents offset
Mode [1/2]
enum ColorPicker::Mode
Enumerator
Hue
Saturation
Gamma
Hue
Saturation
Gamma
Definition at line 59 of file wizard.h.
{ Hue, Saturation, Gamma };
Mode [2/2]
enum ColorPicker::Mode
Enumerator
Hue
Saturation
Gamma
Hue
Saturation
Gamma
Definition at line 59 of file wizard.h.
{ Hue, Saturation, Gamma };
Constructor & Destructor Documentation
ColorPicker() [1/2]
ColorPicker::ColorPicker (Mode m)
Definition at line 330 of file wizard.cpp.
{
  m_hue = 220;
  m_gam = 100;
  m_sat = 100;
  m_mode = m;
  m_pix = 0;
}
References m_gam, m_hue, m_mode, m_pix, and m_sat.
 ColorPicker() [1/2]
ColorPicker::~ColorPicker ()
Definition at line 339 of file wizard.cpp.
{
  delete m_pix;
}
References m_pix.
ColorPicker() [2/2]
ColorPicker::ColorPicker (Mode m)
 ColorPicker() [2/2]
ColorPicker::~ColorPicker ()
Member Function Documentation
gam2y() [1/2]
int ColorPicker::gam2y (int gamma) [private]
Definition at line 471 of file wizard.cpp.
{
  int d = height() - 2*coff - 1;
  return coff + (240-g)*d/200;
}
References coff, and g.
Referenced by paintEvent().
gam2y() [2/2]
int ColorPicker::gam2y (int gamma) [private]
hue2y() [1/2]
int ColorPicker::hue2y (int hue) [private]
Definition at line 447 of file wizard.cpp.
{
  int d = height() - 2*coff - 1;
  return coff + v*d/359;
}
References coff.
Referenced by paintEvent().
hue2y() [2/2]
int ColorPicker::hue2y (int hue) [private]
mouseMoveEvent() [1/2]
void ColorPicker::mouseMoveEvent (QMouseEvent * m) [protected]
Definition at line 388 of file wizard.cpp.
{
  if (m_mode==Hue) setHue(y2hue(getMouseYPositionFromEvent(m)));
  else if (m_mode==Saturation) setSat(y2sat(getMouseYPositionFromEvent(m)));
  else setGam(y2gam(getMouseYPositionFromEvent(m)));
}
References getMouseYPositionFromEvent(), Hue, m_mode, Saturation, setGam(), setHue(), setSat(), y2gam(), y2hue(), and y2sat().
mouseMoveEvent() [2/2]
void ColorPicker::mouseMoveEvent (QMouseEvent *) [protected]
mousePressEvent() [1/2]
void ColorPicker::mousePressEvent (QMouseEvent * m) [protected]
Definition at line 395 of file wizard.cpp.
{
  if (m_mode==Hue) setHue(y2hue(getMouseYPositionFromEvent(m)));
  else if (m_mode==Saturation) setSat(y2sat(getMouseYPositionFromEvent(m)));
  else setGam(y2gam(getMouseYPositionFromEvent(m)));
}
References getMouseYPositionFromEvent(), Hue, m_mode, Saturation, setGam(), setHue(), setSat(), y2gam(), y2hue(), and y2sat().
mousePressEvent() [2/2]
void ColorPicker::mousePressEvent (QMouseEvent *) [protected]
newHsv [1/2]
void ColorPicker::newHsv (int h, int s, int g) [signal]
Referenced by setGam(), setHue(), and setSat().
newHsv [2/2]
void ColorPicker::newHsv (int h, int s, int g) [signal]
paintEvent() [1/2]
void ColorPicker::paintEvent (QPaintEvent *) [protected]
Definition at line 344 of file wizard.cpp.
{
  int w = width() - 5;
  QRect r(0, foff, w, height() - 2*foff);
  int wi = r.width() - 2;
  int hi = r.height() - 2;
  if (!m_pix || m_pix->height() != hi || m_pix->width() != wi)
  {
    delete m_pix;
    QImage img(wi, hi, QImage::Format_RGB32);
    int y;
    uint *pixel = (uint *) img.scanLine(0);
    for (y = 0; y < hi; y++)
    {
      const uint *end = pixel + wi;
      int yh = y2hue(y+coff);
      int ys = y2sat(y+coff);
      int yg = y2gam(y+coff);
      while (pixel < end)
      {
        QColor c;
        c.setHsv(yh, ys, (int)(255*pow(0.7,yg/100.0)));
        *pixel = c.rgb();
        ++pixel;
      }
    }
    m_pix = new QPixmap(QPixmap::fromImage(img));
  }
  QPainter p(this);
  p.drawPixmap(1, coff, *m_pix);
  const QPalette &g = palette();
  qDrawShadePanel(&p, r, g, true);
  p.setPen(g.windowText().color());
  p.setBrush(g.windowText());
  QPolygon a;
  int y = m_mode==Hue ? hue2y(m_hue) :
          m_mode==Saturation ? sat2y(m_sat) :
                               gam2y(m_gam);
  a.setPoints(3, w, y, w+5, y+5, w+5, y-5);
  p.eraseRect(w, 0, 5, height());
  p.drawPolygon(a);
}
References a, c, coff, ghc::filesystem::end(), foff, g, gam2y(), Hue, hue2y(), m_gam, m_hue, m_mode, m_pix, m_sat, p, palette, r, sat2y(), Saturation, w, y, y2gam(), y2hue(), and y2sat().
paintEvent() [2/2]
void ColorPicker::paintEvent (QPaintEvent *) [protected]
sat2y() [1/2]
int ColorPicker::sat2y (int sat) [private]
Definition at line 459 of file wizard.cpp.
{
  int d = height() - 2*coff - 1;
  return coff + (255-v)*d/255;
}
References coff.
Referenced by paintEvent().
sat2y() [2/2]
int ColorPicker::sat2y (int sat) [private]
setCol [1/2]
void ColorPicker::setCol (int h, int s, int g) [slot]
Definition at line 429 of file wizard.cpp.
{
  if (m_hue!=h || m_sat!=s || m_gam!=g)
  {
    m_hue = h;
    m_sat = s;
    m_gam = g;
    delete m_pix; m_pix=0;
    repaint();
  }
}
References g, h, m_gam, m_hue, m_pix, m_sat, and s.
Referenced by TuneColorDialog::TuneColorDialog().
setCol [2/2]
void ColorPicker::setCol (int h, int s, int g) [slot]
setGam() [1/2]
void ColorPicker::setGam (int v) [private]
Definition at line 420 of file wizard.cpp.
{
  if (g==m_gam) return;
  m_gam = qMax(40,qMin(g,240));
  delete m_pix; m_pix=0;
  repaint();
  emit newHsv(m_hue,m_sat,m_gam);
}
References g, m_gam, m_hue, m_pix, m_sat, and newHsv().
Referenced by mouseMoveEvent(), and mousePressEvent().
setGam() [2/2]
void ColorPicker::setGam (int v) [private]
setHue() [1/2]
void ColorPicker::setHue (int v) [private]
Definition at line 402 of file wizard.cpp.
{
  if (h==m_hue) return;
  m_hue = qMax(0,qMin(h,359));
  delete m_pix; m_pix=0;
  repaint();
  emit newHsv(m_hue,m_sat,m_gam);
}
References h, m_gam, m_hue, m_pix, m_sat, and newHsv().
Referenced by mouseMoveEvent(), and mousePressEvent().
setHue() [2/2]
void ColorPicker::setHue (int v) [private]
setSat() [1/2]
void ColorPicker::setSat (int v) [private]
Definition at line 411 of file wizard.cpp.
{
  if (s==m_sat) return;
  m_sat = qMax(0,qMin(s,255));
  delete m_pix; m_pix=0;
  repaint();
  emit newHsv(m_hue,m_sat,m_gam);
}
References m_gam, m_hue, m_pix, m_sat, newHsv(), and s.
Referenced by mouseMoveEvent(), and mousePressEvent().
setSat() [2/2]
void ColorPicker::setSat (int v) [private]
y2gam() [1/2]
int ColorPicker::y2gam (int y) [private]
Definition at line 465 of file wizard.cpp.
{
  int d = height() - 2*coff - 1;
  return m_mode==Gamma ? 240 - (y - coff)*200/d : m_gam;
}
References coff, Gamma, m_gam, m_mode, and y.
Referenced by mouseMoveEvent(), mousePressEvent(), and paintEvent().
y2gam() [2/2]
int ColorPicker::y2gam (int y) [private]
y2hue() [1/2]
int ColorPicker::y2hue (int y) [private]
Definition at line 441 of file wizard.cpp.
{
  int d = height() - 2*coff - 1;
  return m_mode==Hue ? (y - coff)*359/d : m_hue;
}
References coff, Hue, m_hue, m_mode, and y.
Referenced by mouseMoveEvent(), mousePressEvent(), and paintEvent().
y2hue() [2/2]
int ColorPicker::y2hue (int y) [private]
y2sat() [1/2]
int ColorPicker::y2sat (int y) [private]
Definition at line 453 of file wizard.cpp.
{
  int d = height() - 2*coff - 1;
  return m_mode==Saturation ? 255 - (y - coff)*255/d : m_sat;
}
References coff, m_mode, m_sat, Saturation, and y.
Referenced by mouseMoveEvent(), mousePressEvent(), and paintEvent().
y2sat() [2/2]
int ColorPicker::y2sat (int y) [private]
Member Data Documentation
m_gam
int ColorPicker::m_gam = 0 [private]
Definition at line 89 of file wizard.h.
Referenced by ColorPicker(), paintEvent(), setCol(), setGam(), setHue(), setSat(), and y2gam().
m_hue
int ColorPicker::m_hue = 0 [private]
Definition at line 90 of file wizard.h.
Referenced by ColorPicker(), paintEvent(), setCol(), setGam(), setHue(), setSat(), and y2hue().
m_mode
Mode ColorPicker::m_mode = Hue [private]
Definition at line 88 of file wizard.h.
Referenced by ColorPicker(), mouseMoveEvent(), mousePressEvent(), paintEvent(), y2gam(), y2hue(), and y2sat().
m_pix
QPixmap * ColorPicker::m_pix = 0 [private]
Definition at line 87 of file wizard.h.
Referenced by ColorPicker(), paintEvent(), setCol(), setGam(), setHue(), setSat(), and ~ColorPicker().
m_sat
int ColorPicker::m_sat = 0 [private]
Definition at line 91 of file wizard.h.
Referenced by ColorPicker(), paintEvent(), setCol(), setGam(), setHue(), setSat(), and y2sat().
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/wizard.h
doxygen/build/doxygen/addon/doxywizard/wizard.h
doxygen/addon/doxywizard/wizard.cpp
doxygen/build/doxygen/addon/doxywizard/wizard.cpp