LexCodeParser Class Reference
#include <lexcode.h>
Classes
struct Private
Public Member Functions
LexCodeParser ()
virtual ~LexCodeParser ()
void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXRefs=TRUE)
void resetCodeParserState ()
LexCodeParser ()
virtual ~LexCodeParser ()
void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXRefs=TRUE)
void resetCodeParserState ()
Private Attributes
std::unique_ptr< Private > p
Detailed Description
LEX code scanner.
Definition at line 30 of file lexcode.h.
Constructor & Destructor Documentation
LexCodeParser() [1/2]
LexCodeParser::LexCodeParser ()
Definition at line 1176 of file lexcode.l.
                             : p(std::make_unique<Private>())
{
  lexcodeYYlex_init_extra(&p->state, &p->yyscanner);
#ifdef FLEX_DEBUG
  lexcodeYYset_debug(1,p->yyscanner);
#endif
  resetCodeParserState();
}
References p, and resetCodeParserState().
 LexCodeParser() [1/2]
LexCodeParser::~LexCodeParser () [virtual]
Definition at line 1185 of file lexcode.l.
{
  lexcodeYYlex_destroy(p->yyscanner);
}
References p.
LexCodeParser() [2/2]
LexCodeParser::LexCodeParser ()
 LexCodeParser() [2/2]
virtual LexCodeParser::~LexCodeParser () [virtual]
Member Function Documentation
parseCode() [1/2]
void LexCodeParser::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
Definition at line 1197 of file lexcode.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (input.isEmpty()) return;
  printlex(yy_flex_debug, true, __FILE__, fileDef ? qPrint(fileDef->fileName()): NULL);
  yyextra->code = &codeOutIntf;
  yyextra->inputString = input.data();
  yyextra->inputPosition = 0;
  yyextra->fileName = fileDef ? fileDef->fileName():"";
  yyextra->currentFontClass = 0;
  yyextra->insideCodeLine = false;
  yyextra->classScope=scopeName;
  yyextra->currentMemberDef=memberDef;
  yyextra->searchCtx=searchCtx;
  yyextra->collectXRefs=collectXRefs;
  if (startLine!=-1)
    yyextra->yyLineNr = startLine;
  else
    yyextra->yyLineNr = 1;
  if (endLine!=-1)
    yyextra->inputLines = endLine+1;
  else
    yyextra->inputLines = yyextra->yyLineNr + countLines(yyscanner) - 1;
  yyextra->startCCodeLine = yyextra->yyLineNr;
  yyextra->exampleBlock = isExampleBlock;
  yyextra->exampleName = exampleName;
  yyextra->sourceFileDef = fileDef;
  yyextra->lineNumbers = fileDef!=0 && showLineNumbers;
  bool cleanupSourceDef = false;
  if (isExampleBlock && fileDef==0)
  {
    // create a dummy filedef for the example
    yyextra->sourceFileDef = createFileDef(QCString(),!exampleName.isEmpty() ? exampleName : QCString("generated"));
    cleanupSourceDef = true;
  }
  if (yyextra->sourceFileDef)
  {
    setCurrentDoc(yyscanner,"l00001");
  }
  yyextra->includeCodeFragment = inlineFragment;
  // Starts line 1 on the output
  startCodeLine(yyscanner);
  lexcodeYYrestart(0, yyscanner);
  BEGIN(DefSection);
  lexcodeYYlex(yyscanner);
  if (yyextra->insideCodeLine)
  {
    endCodeLine(yyscanner);
  }
  if (cleanupSourceDef)
  {
    // delete the temporary file definition used for this example
    delete yyextra->sourceFileDef;
    yyextra->sourceFileDef=0;
  }
  printlex(yy_flex_debug, false, __FILE__, fileDef ? qPrint(fileDef->fileName()): NULL);
}
References countLines(), createFileDef(), QCString::data(), endCodeLine(), FileDef::fileName(), QCString::isEmpty(), p, printlex(), qPrint(), setCurrentDoc(), and startCodeLine().
parseCode() [2/2]
void LexCodeParser::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
resetCodeParserState() [1/2]
void LexCodeParser::resetCodeParserState () [virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Definition at line 1190 of file lexcode.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->currentDefinition = 0;
  yyextra->currentMemberDef = 0;
}
References p.
Referenced by LexCodeParser().
resetCodeParserState() [2/2]
void LexCodeParser::resetCodeParserState () [virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Member Data Documentation
p
std::unique_ptr< Private > LexCodeParser::p [private]
Definition at line 53 of file lexcode.h.
Referenced by LexCodeParser(), parseCode(), resetCodeParserState(), and ~LexCodeParser().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/lexcode.h
doxygen/src/lexcode.h
doxygen/build/doxygen/src/lexcode.l
doxygen/src/lexcode.l