TemplateImmutableStruct Class Reference
Default implementation of an immutable context value of type struct.
#include <template.h>
Classes
class Private
Private data of a template struct object.
Public Types
using StructField = std::pair< const std::string, TemplateVariant >
using StructField = std::pair< const std::string, TemplateVariant >
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
TemplateImmutableStruct (std::initializer_list< StructField > fields)
virtual ~TemplateImmutableStruct ()
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
TemplateImmutableStruct (std::initializer_list< StructField > fields)
virtual ~TemplateImmutableStruct ()
Static Public Member Functions
static TemplateStructIntfPtr alloc (std::initializer_list< StructField > fields)
static TemplateStructIntfPtr alloc (std::initializer_list< StructField > fields)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Default implementation of an immutable context value of type struct.
Definition at line 367 of file template.h.
Member Typedef Documentation
StructField [1/2]
using TemplateImmutableStruct::StructField = std::pair<const std::string,TemplateVariant>
Definition at line 374 of file template.h.
StructField [2/2]
using TemplateImmutableStruct::StructField = std::pair<const std::string,TemplateVariant>
Definition at line 374 of file template.h.
Constructor & Destructor Documentation
TemplateImmutableStruct() [1/2]
TemplateImmutableStruct::TemplateImmutableStruct (std::initializer_list< StructField > fields)
Creates a struct
Definition at line 469 of file template.cpp.
  : p(std::make_unique<Private>(fields))
{
}
 TemplateImmutableStruct() [1/2]
TemplateImmutableStruct::~TemplateImmutableStruct () [virtual]
Destroys the struct
Definition at line 475 of file template.cpp.
{
}
TemplateImmutableStruct() [2/2]
TemplateImmutableStruct::TemplateImmutableStruct (std::initializer_list< StructField > fields)
Creates a struct
 TemplateImmutableStruct() [2/2]
virtual TemplateImmutableStruct::~TemplateImmutableStruct () [virtual]
Destroys the struct
Member Function Documentation
alloc() [1/2]
TemplateStructIntfPtr TemplateImmutableStruct::alloc (std::initializer_list< StructField > fields) [static]
Creates an instance and returns a shared pointer to it
Parameters
fields the fields of the struct as key/value pairs.
Definition at line 496 of file template.cpp.
{
  return std::make_shared<TemplateImmutableStruct>(fields);
}
References fields().
Referenced by ClassContext::Private::createExamples(), MemberContext::Private::createExamples(), and DefinitionContext< T >::DefinitionContext().
alloc() [2/2]
static TemplateStructIntfPtr TemplateImmutableStruct::alloc (std::initializer_list< StructField > fields) [static]
Creates an instance and returns a shared pointer to it
Parameters
fields the fields of the struct as key/value pairs.
fields() [1/2]
StringVector TemplateImmutableStruct::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 485 of file template.cpp.
{
  StringVector result;
  for (const auto &kv : p->fields)
  {
    result.push_back(kv.first);
  }
  std::sort(result.begin(),result.end());
  return result;
}
References p.
Referenced by alloc().
fields() [2/2]
virtual StringVector TemplateImmutableStruct::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant TemplateImmutableStruct::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 479 of file template.cpp.
{
  auto it = p->fields.find(name.str());
  return it!=p->fields.end() ? it->second : TemplateVariant();
}
References setup::name, and p.
get() [2/2]
virtual TemplateVariant TemplateImmutableStruct::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Member Data Documentation
p
std::unique_ptr< Private > TemplateImmutableStruct::p [private]
Definition at line 389 of file template.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.h
doxygen/src/template.h
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp