TemplateLexer Class Reference
Lexer class for turning a template into a list of tokens.
Public Member Functions
TemplateLexer (const TemplateEngine *engine, const QCString &fileName, const QCString &data)
void tokenize (TemplateTokenStream &tokens)
void setOpenCloseCharacters (char openChar, char closeChar)
TemplateLexer (const TemplateEngine *engine, const QCString &fileName, const QCString &data)
void tokenize (TemplateTokenStream &tokens)
void setOpenCloseCharacters (char openChar, char closeChar)
Private Member Functions
void addToken (TemplateTokenStream &tokens, const QCString &data, int line, int startPos, int endPos, TemplateToken::Type type)
void reset ()
void addToken (TemplateTokenStream &tokens, const QCString &data, int line, int startPos, int endPos, TemplateToken::Type type)
void reset ()
Private Attributes
const TemplateEngine * m_engine = 0
QCString m_fileName
QCString m_data
char m_openChar = 0
char m_closeChar = 0
Detailed Description
Lexer class for turning a template into a list of tokens.
Definition at line 4804 of file template.cpp.
Constructor & Destructor Documentation
TemplateLexer() [1/2]
TemplateLexer::TemplateLexer (const TemplateEngine * engine, const QCString & fileName, const QCString & data)
Definition at line 4823 of file template.cpp.
                                                                                                       :
  m_engine(engine), m_fileName(fileName), m_data(data)
{
  m_openChar='{';
  m_closeChar='}';
}
References m_closeChar, and m_openChar.
TemplateLexer() [2/2]
TemplateLexer::TemplateLexer (const TemplateEngine * engine, const QCString & fileName, const QCString & data)
Member Function Documentation
addToken() [1/2]
void TemplateLexer::addToken (TemplateTokenStream & tokens, const QCString & data, int line, int startPos, int endPos, TemplateToken::Type type) [private]
Definition at line 5033 of file template.cpp.
{
  if (startPos<endPos)
  {
    int len = endPos-startPos;
    QCString text = data.mid(startPos,len);
    if (type!=TemplateToken::Text) text = text.stripWhiteSpace();
    tokens.push_back(std::make_unique<TemplateToken>(type,text,line));
  }
}
References data, len, QCString::stripWhiteSpace(), and TemplateToken::Text.
Referenced by tokenize().
addToken() [2/2]
void TemplateLexer::addToken (TemplateTokenStream & tokens, const QCString & data, int line, int startPos, int endPos, TemplateToken::Type type) [private]
reset() [1/2]
void TemplateLexer::reset () [private]
reset() [2/2]
void TemplateLexer::reset () [private]
setOpenCloseCharacters() [1/2]
void TemplateLexer::setOpenCloseCharacters (char openChar, char closeChar) [inline]
Definition at line 4809 of file template.cpp.
    { m_openChar=openChar; m_closeChar=closeChar; }
References m_closeChar, and m_openChar.
Referenced by TemplateImpl::TemplateImpl().
setOpenCloseCharacters() [2/2]
void TemplateLexer::setOpenCloseCharacters (char openChar, char closeChar) [inline]
Definition at line 4809 of file template.cpp.
    { m_openChar=openChar; m_closeChar=closeChar; }
References m_closeChar, and m_openChar.
tokenize() [1/2]
void TemplateLexer::tokenize (TemplateTokenStream & tokens)
Definition at line 4830 of file template.cpp.
{
  enum LexerStates
  {
    StateText,
    StateBeginTemplate,
    StateTag,
    StateEndTag,
    StateComment,
    StateEndComment,
    StateMaybeVar,
    StateVariable,
    StateEndVariable
  };
  if (m_data.isEmpty()) return;
  const char *p=m_data.data();
  int state=StateText;
  int pos=0;
  int lastTokenPos=0;
  int startLinePos=0;
  bool emptyOutputLine=TRUE;
  int line=1;
  char c;
  int markStartPos=-1;
  for (;(c=*p);p++,pos++)
  {
    switch (state)
    {
      case StateText:
        if (c==m_openChar) // {{ or {% or {# or something else
        {
          state=StateBeginTemplate;
        }
        else if (c!=' ' && c!='\t' && c!='\n') // non-whitespace text
        {
          emptyOutputLine=FALSE;
        }
        break;
      case StateBeginTemplate:
        switch (c)
        {
          case '%': // {%
            state=StateTag;
            markStartPos=pos-1;
            break;
          case '#': // {#
            state=StateComment;
            markStartPos=pos-1;
            break;
          case '{': // {{
            if (m_openChar=='{')
            {
              state=StateMaybeVar;
            }
            else
            {
              state=StateVariable;
            }
            markStartPos=pos-1;
            break;
          default:
            state=StateText;
            emptyOutputLine=FALSE;
            break;
        }
        break;
      case StateTag:
        if (c=='\n')
        {
          warn(m_fileName,line,"unexpected new line inside %c%%...%%%c block",m_openChar,m_closeChar);
          m_engine->printIncludeContext(m_fileName,line);
        }
        else if (c=='%') // %} or something else
        {
          state=StateEndTag;
        }
        break;
      case StateEndTag:
        if (c==m_closeChar) // %}
        {
          // found tag!
          state=StateText;
          addToken(tokens,m_data,line,lastTokenPos,
                   emptyOutputLine ? startLinePos : markStartPos,
                   TemplateToken::Text);
          addToken(tokens,m_data,line,markStartPos+2,
                   pos-1,TemplateToken::Block);
          lastTokenPos = pos+1;
        }
        else // something else
        {
          if (c=='\n')
          {
            warn(m_fileName,line,"unexpected new line inside %c%%...%%%c block",m_openChar,m_closeChar);
            m_engine->printIncludeContext(m_fileName,line);
          }
          state=StateTag;
        }
        break;
      case StateComment:
        if (c=='\n')
        {
          warn(m_fileName,line,"unexpected new line inside %c#...#%c block",m_openChar,m_closeChar);
          m_engine->printIncludeContext(m_fileName,line);
        }
        else if (c=='#') // #} or something else
        {
          state=StateEndComment;
        }
        break;
      case StateEndComment:
        if (c==m_closeChar) // #}
        {
          // found comment tag!
          state=StateText;
          addToken(tokens,m_data,line,lastTokenPos,
                   emptyOutputLine ? startLinePos : markStartPos,
                   TemplateToken::Text);
          lastTokenPos = pos+1;
        }
        else // something else
        {
          if (c=='\n')
          {
            warn(m_fileName,line,"unexpected new line inside %c#...#%c block",m_openChar,m_closeChar);
            m_engine->printIncludeContext(m_fileName,line);
          }
          state=StateComment;
        }
        break;
      case StateMaybeVar:
        switch (c)
        {
          case '#': // {{#
            state=StateComment;
            markStartPos=pos-1;
            break;
          case '%': // {{%
            state=StateTag;
            markStartPos=pos-1;
            break;
          default: // {{
            state=StateVariable;
            break;
        }
        break;
      case StateVariable:
        emptyOutputLine=FALSE; // assume a variable expands to content
        if (c=='\n')
        {
          warn(m_fileName,line,"unexpected new line inside %c{...}%c block",m_openChar,m_closeChar);
          m_engine->printIncludeContext(m_fileName,line);
        }
        else if (c=='}') // }} or something else
        {
          state=StateEndVariable;
        }
        break;
      case StateEndVariable:
        if (c==m_closeChar) // }}
        {
          // found variable tag!
          state=StateText;
          addToken(tokens,m_data,line,lastTokenPos,
                   emptyOutputLine ? startLinePos : markStartPos,
                   TemplateToken::Text);
          addToken(tokens,m_data,line,markStartPos+2,
                   pos-1,TemplateToken::Variable);
          lastTokenPos = pos+1;
        }
        else // something else
        {
          if (c=='\n')
          {
            warn(m_fileName,line,"unexpected new line inside %c{...}%c block",m_openChar,m_closeChar);
            m_engine->printIncludeContext(m_fileName,line);
          }
          state=StateVariable;
        }
        break;
    }
    if (c=='\n') // new line
    {
      state=StateText;
      startLinePos=pos+1;
      // if the current line only contain commands and whitespace,
      // then skip it in the output by moving lastTokenPos
      if (markStartPos!=-1 && emptyOutputLine) lastTokenPos = startLinePos;
      // reset markers
      markStartPos=-1;
      line++;
      emptyOutputLine=TRUE;
    }
  }
  if (lastTokenPos<pos)
  {
    addToken(tokens,m_data,line,
             lastTokenPos,pos,
             TemplateToken::Text);
  }
}
References addToken(), TemplateToken::Block, c, QCString::data(), FALSE, QCString::isEmpty(), m_closeChar, m_data, m_engine, m_fileName, m_openChar, p, TemplateEngine::printIncludeContext(), TemplateToken::Text, TRUE, TemplateToken::Variable, and warn().
Referenced by TemplateImpl::TemplateImpl().
tokenize() [2/2]
void TemplateLexer::tokenize (TemplateTokenStream & tokens)
Member Data Documentation
m_closeChar
char TemplateLexer::m_closeChar = 0 [private]
Definition at line 4820 of file template.cpp.
Referenced by setOpenCloseCharacters(), TemplateLexer(), and tokenize().
m_data
QCString TemplateLexer::m_data [private]
Definition at line 4818 of file template.cpp.
Referenced by tokenize().
m_engine
const TemplateEngine * TemplateLexer::m_engine = 0 [private]
Definition at line 4816 of file template.cpp.
Referenced by tokenize().
m_fileName
QCString TemplateLexer::m_fileName [private]
Definition at line 4817 of file template.cpp.
Referenced by tokenize().
m_openChar
char TemplateLexer::m_openChar = 0 [private]
Definition at line 4819 of file template.cpp.
Referenced by setOpenCloseCharacters(), TemplateLexer(), and tokenize().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp