NestingNodeContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
QCString id () const
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
NestingNodeContext (const NestingNodeContext *parent, ContextTreeType type, const Definition *, int index, int level, bool addClasses, bool addConcepts, bool inherit, bool hideSuper, ClassDefSet &visitedClasses)
virtual ~NestingNodeContext ()
QCString id () const
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
NestingNodeContext (const NestingNodeContext *parent, ContextTreeType type, const Definition *, int index, int level, bool addClasses, bool addConcepts, bool inherit, bool hideSuper, ClassDefSet &visitedClasses)
virtual ~NestingNodeContext ()
Static Public Member Functions
static TemplateStructIntfPtr alloc (const NestingNodeContext *parent, ContextTreeType type, const Definition *def, int index, int level, bool addClasses, bool addConcepts, bool inherit, bool hideSuper, ClassDefSet &visitedClasses)
static TemplateStructIntfPtr alloc (const NestingNodeContext *parent, ContextTreeType type, const Definition *def, int index, int level, bool addClasses, bool addConcepts, bool inherit, bool hideSuper, ClassDefSet &visitedClasses)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 493 of file context.h.
Constructor & Destructor Documentation
NestingNodeContext() [1/2]
NestingNodeContext::NestingNodeContext (const NestingNodeContext * parent, ContextTreeType type, const Definition * d, int index, int level, bool addClasses, bool addConcepts, bool inherit, bool hideSuper, ClassDefSet & visitedClasses)
Definition at line 5666 of file context.cpp.
  : p(std::make_unique<Private>(parent,this,type,d,index,level,addClass,addConcepts,inherit,hideSuper,visitedClasses))
{
}
 NestingNodeContext() [1/2]
NestingNodeContext::~NestingNodeContext () [virtual]
Definition at line 5676 of file context.cpp.
{
}
NestingNodeContext() [2/2]
NestingNodeContext::NestingNodeContext (const NestingNodeContext * parent, ContextTreeType type, const Definition * , int index, int level, bool addClasses, bool addConcepts, bool inherit, bool hideSuper, ClassDefSet & visitedClasses)
 NestingNodeContext() [2/2]
virtual NestingNodeContext::~NestingNodeContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateStructIntfPtr NestingNodeContext::alloc (const NestingNodeContext * parent, ContextTreeType type, const Definition * def, int index, int level, bool addClasses, bool addConcepts, bool inherit, bool hideSuper, ClassDefSet & visitedClasses) [inline], [static]
Definition at line 496 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<NestingNodeContext>
             (parent,type,def,index,level,addClasses,addConcepts,inherit,hideSuper,visitedClasses)); }
References level, and parent().
Referenced by NestingContext::Private::addClass(), NestingContext::Private::addClassHierarchy(), NestingContext::Private::addConcept(), NestingContext::Private::addDerivedClasses(), NestingContext::Private::addDirs(), NestingContext::Private::addFiles(), NestingContext::Private::addMembers(), NestingContext::Private::addModules(), NestingContext::Private::addNamespace(), and NestingContext::Private::addPage().
alloc() [2/2]
static TemplateStructIntfPtr NestingNodeContext::alloc (const NestingNodeContext * parent, ContextTreeType type, const Definition * def, int index, int level, bool addClasses, bool addConcepts, bool inherit, bool hideSuper, ClassDefSet & visitedClasses) [inline], [static]
Definition at line 496 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<NestingNodeContext>
             (parent,type,def,index,level,addClasses,addConcepts,inherit,hideSuper,visitedClasses)); }
References level, and parent().
fields() [1/2]
StringVector NestingNodeContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 5685 of file context.cpp.
{
  return p->fields();
}
References p.
fields() [2/2]
virtual StringVector NestingNodeContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant NestingNodeContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 5680 of file context.cpp.
{
  return p->get(n);
}
References n, and p.
get() [2/2]
virtual TemplateVariant NestingNodeContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
id() [1/2]
QCString NestingNodeContext::id () const
Definition at line 5690 of file context.cpp.
{
  return p->id().toString();
}
References p.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), NestingNodeContext::Private::id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
QCString NestingNodeContext::id () const
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
Member Data Documentation
p
std::unique_ptr< Private > NestingNodeContext::p [private]
Definition at line 521 of file context.h.
Referenced by fields(), get(), and id().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp