DocSimpleSect Class Reference
#include <docnode.h>
Public Types
enum Type {
Unknown
, See
, Return
, Author
,
Authors
, Version
, Since
, Date
,
Note
, Warning
, Copyright
, Pre
,
Post
, Invar
, Remark
, Attention
,
User
, Rcs
, Unknown
, See
,
Return
, Author
, Authors
, Version
,
Since
, Date
, Note
, Warning
,
Copyright
, Pre
, Post
, Invar
,
Remark
, Attention
, User
, Rcs
 }
enum Type {
Unknown
, See
, Return
, Author
,
Authors
, Version
, Since
, Date
,
Note
, Warning
, Copyright
, Pre
,
Post
, Invar
, Remark
, Attention
,
User
, Rcs
, Unknown
, See
,
Return
, Author
, Authors
, Version
,
Since
, Date
, Note
, Warning
,
Copyright
, Pre
, Post
, Invar
,
Remark
, Attention
, User
, Rcs
 }
Public Member Functions
DocSimpleSect (DocParser *parser, DocNodeVariant *parent, Type t)
Type type () const
QCString typeString () const
int parse (DocNodeVariant *, bool userTitle, bool needsSeparator)
int parseRcs (DocNodeVariant *)
int parseXml (DocNodeVariant *)
void appendLinkWord (DocNodeVariant *, const QCString &word)
bool hasTitle () const
const DocNodeVariant * title () const
DocSimpleSect (DocParser *parser, DocNodeVariant *parent, Type t)
Type type () const
QCString typeString () const
int parse (DocNodeVariant *, bool userTitle, bool needsSeparator)
int parseRcs (DocNodeVariant *)
int parseXml (DocNodeVariant *)
void appendLinkWord (DocNodeVariant *, const QCString &word)
bool hasTitle () const
const DocNodeVariant * title () const
Private Attributes
Type m_type = Unknown
std::unique_ptr< DocNodeVariant > m_title
Additional Inherited Members
Detailed Description
Node representing a simple section
Definition at line 969 of file docnode.h.
Member Enumeration Documentation
Type [1/2]
enum DocSimpleSect::Type
Enumerator
Unknown
See
Return
Author
Authors
Version
Since
Date
Note
Warning
Copyright
Pre
Post
Invar
Remark
Attention
User
Rcs
Unknown
See
Return
Author
Authors
Version
Since
Date
Note
Warning
Copyright
Pre
Post
Invar
Remark
Attention
User
Rcs
Definition at line 972 of file docnode.h.
    {
       Unknown, See, Return, Author, Authors, Version, Since, Date,
       Note, Warning, Copyright, Pre, Post, Invar, Remark, Attention, User, Rcs
    };
Type [2/2]
enum DocSimpleSect::Type
Enumerator
Unknown
See
Return
Author
Authors
Version
Since
Date
Note
Warning
Copyright
Pre
Post
Invar
Remark
Attention
User
Rcs
Unknown
See
Return
Author
Authors
Version
Since
Date
Note
Warning
Copyright
Pre
Post
Invar
Remark
Attention
User
Rcs
Definition at line 972 of file docnode.h.
    {
       Unknown, See, Return, Author, Authors, Version, Since, Date,
       Note, Warning, Copyright, Pre, Post, Invar, Remark, Attention, User, Rcs
    };
Constructor & Destructor Documentation
DocSimpleSect() [1/2]
DocSimpleSect::DocSimpleSect (DocParser * parser, DocNodeVariant * parent, Type t)
Definition at line 2755 of file docnode.cpp.
                                                                            :
     DocCompoundNode(parser,parent), m_type(t)
{
}
DocSimpleSect() [2/2]
DocSimpleSect::DocSimpleSect (DocParser * parser, DocNodeVariant * parent, Type t)
Member Function Documentation
appendLinkWord() [1/2]
void DocSimpleSect::appendLinkWord (DocNodeVariant * thisVariant, const QCString & word)
Definition at line 2857 of file docnode.cpp.
{
  DocPara *p=0;
  if (children().empty() || (p=std::get_if<DocPara>(&children().back()))==0)
  {
    children().append<DocPara>(parser(),thisVariant);
    p = children().get_last<DocPara>();
  }
  else
  {
    // Comma-separate <seealso> links.
    p->injectToken(thisVariant,TK_WORD,",");
    p->injectToken(thisVariant,TK_WHITESPACE," ");
  }
  parser()->context.inSeeBlock=TRUE;
  p->injectToken(thisVariant,TK_LNKWORD,word);
  parser()->context.inSeeBlock=FALSE;
}
References DocNodeList::append(), DocCompoundNode::children(), DocParser::context, FALSE, DocNodeList::get_last(), DocParserContext::inSeeBlock, p, DocNode::parser(), TK_LNKWORD, TK_WHITESPACE, TK_WORD, TRUE, and word.
Referenced by DocPara::handleHtmlStartTag().
appendLinkWord() [2/2]
void DocSimpleSect::appendLinkWord (DocNodeVariant * , const QCString & word)
hasTitle() [1/2]
bool DocSimpleSect::hasTitle () const
Definition at line 2760 of file docnode.cpp.
{
  return m_title && std::get<DocTitle>(*m_title).hasTitle();
}
References m_title.
hasTitle() [2/2]
bool DocSimpleSect::hasTitle () const
parse() [1/2]
int DocSimpleSect::parse (DocNodeVariant * thisVariant, bool userTitle, bool needsSeparator)
Definition at line 2765 of file docnode.cpp.
{
  DBG(("DocSimpleSect::parse() start\n"));
  auto ns = AutoNodeStack(parser(),thisVariant);
  // handle case for user defined title
  if (userTitle)
  {
    m_title = std::make_unique<DocNodeVariant>(DocTitle(parser(),thisVariant));
    DocTitle *title = &std::get<DocTitle>(*m_title);
    title->parse(m_title.get());
  }
  // add new paragraph as child
  if (!children().empty() && std::holds_alternative<DocPara>(children().back()))
  {
    std::get<DocPara>(children().back()).markLast(FALSE);
  }
  bool markFirst = children().empty();
  if (needsSeparator)
  {
    children().append<DocSimpleSectSep>(parser(),thisVariant);
  }
  auto vDocPara = children().append<DocPara>(parser(),thisVariant);
  DocPara *par = children().get_last<DocPara>();
  if (markFirst)
  {
    par->markFirst();
  }
  par->markLast();
  // parse the contents of the paragraph
  int retval = par->parse(vDocPara);
  DBG(("DocSimpleSect::parse() end retval=%d\n",retval));
  return retval; // 0==EOF, TK_NEWPARA, TK_LISTITEM, TK_ENDLIST, RetVal_SimpleSec
}
References DocNodeList::append(), DocCompoundNode::children(), DBG, GrowVector< T >::empty(), FALSE, DocNodeList::get_last(), m_title, DocPara::markFirst(), DocNode::parser(), and title().
Referenced by DocPara::handleSimpleSection().
parse() [2/2]
int DocSimpleSect::parse (DocNodeVariant * , bool userTitle, bool needsSeparator)
parseRcs() [1/2]
int DocSimpleSect::parseRcs (DocNodeVariant * thisVariant)
Definition at line 2803 of file docnode.cpp.
{
  DBG(("DocSimpleSect::parseRcs() start\n"));
  auto ns = AutoNodeStack(parser(),thisVariant);
  m_title = std::make_unique<DocNodeVariant>(DocTitle(parser(),thisVariant));
  DocTitle *title = &std::get<DocTitle>(*m_title);
  title->parseFromString(thisVariant,parser()->context.token->name);
  QCString text = parser()->context.token->text;
  parser()->pushContext(); // this will create a new parser->context.token
  parser()->internalValidatingParseDoc(thisVariant,children(),text);
  parser()->popContext(); // this will restore the old parser->context.token
  DBG(("DocSimpleSect::parseRcs()\n"));
  return RetVal_OK;
}
References DocCompoundNode::children(), DocParser::context, DBG, DocParser::internalValidatingParseDoc(), m_title, DocNode::parser(), DocParser::popContext(), DocParser::pushContext(), RetVal_OK, TokenInfo::text, title(), and DocParserContext::token.
parseRcs() [2/2]
int DocSimpleSect::parseRcs (DocNodeVariant *)
parseXml() [1/2]
int DocSimpleSect::parseXml (DocNodeVariant * thisVariant)
Definition at line 2821 of file docnode.cpp.
{
  DBG(("DocSimpleSect::parse() start\n"));
  auto ns = AutoNodeStack(parser(),thisVariant);
  int retval = RetVal_OK;
  for (;;)
  {
    // add new paragraph as child
    if (!children().empty() && std::holds_alternative<DocPara>(children().back()))
    {
      std::get<DocPara>(children().back()).markLast(false);
    }
    bool markFirst = children().empty();
    auto vDocPara = children().append<DocPara>(parser(),thisVariant);
    DocPara *par = children().get_last<DocPara>();
    if (markFirst)
    {
      par->markFirst();
    }
    par->markLast();
    // parse the contents of the paragraph
    retval = par->parse(vDocPara);
    if (retval == 0) break;
    if (retval == RetVal_CloseXml)
    {
      retval = RetVal_OK;
      break;
    }
  }
  DBG(("DocSimpleSect::parseXml() end retval=%d\n",retval));
  return retval;
}
References DocNodeList::append(), DocCompoundNode::children(), DBG, GrowVector< T >::empty(), DocNodeList::get_last(), DocPara::markFirst(), DocNode::parser(), RetVal_CloseXml, and RetVal_OK.
Referenced by DocPara::handleSimpleSection().
parseXml() [2/2]
int DocSimpleSect::parseXml (DocNodeVariant *)
title() [1/2]
const DocNodeVariant * DocSimpleSect::title () const [inline]
Definition at line 985 of file docnode.h.
{ return m_title.get(); }
References m_title.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), parse(), parseRcs(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
const DocNodeVariant * DocSimpleSect::title () const [inline]
Definition at line 985 of file docnode.h.
{ return m_title.get(); }
References m_title.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
type() [1/2]
Type DocSimpleSect::type () const [inline]
Definition at line 978 of file docnode.h.
{ return m_type; }
References m_type.
Referenced by DocPara::handleHtmlStartTag(), and DocPara::handleSimpleSection().
type() [2/2]
Type DocSimpleSect::type () const [inline]
Definition at line 978 of file docnode.h.
{ return m_type; }
References m_type.
typeString() [1/2]
QCString DocSimpleSect::typeString () const
Definition at line 2877 of file docnode.cpp.
{
  switch (m_type)
  {
    case Unknown: break;
    case See: return "see";
    case Return: return "return";
    case Author: // fall through
    case Authors: return "author";
    case Version: return "version";
    case Since: return "since";
    case Date: return "date";
    case Note: return "note";
    case Warning: return "warning";
    case Pre: return "pre";
    case Post: return "post";
    case Copyright: return "copyright";
    case Invar: return "invariant";
    case Remark: return "remark";
    case Attention: return "attention";
    case User: return "user";
    case Rcs: return "rcs";
  }
  return "unknown";
}
References Attention, Author, Authors, Copyright, Date, Invar, m_type, Note, Post, Pre, Rcs, Remark, Return, See, Since, Unknown, User, Version, and Warning.
typeString() [2/2]
QCString DocSimpleSect::typeString () const
Member Data Documentation
m_title
std::unique_ptr< DocNodeVariant > DocSimpleSect::m_title [private]
Definition at line 989 of file docnode.h.
Referenced by hasTitle(), parse(), parseRcs(), and title().
m_type
Type DocSimpleSect::m_type = Unknown [private]
Definition at line 988 of file docnode.h.
Referenced by type(), and typeString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp