SearchIndex Class Reference
#include <searchindex.h>
Classes
class IndexWord
struct URL
struct URLInfo
Public Member Functions
SearchIndex ()
void setCurrentDoc (const Definition *ctx, const QCString &anchor, bool isSourceFile)
void addWord (const QCString &word, bool hiPriority)
void write (const QCString &file)
SearchIndex ()
void setCurrentDoc (const Definition *ctx, const QCString &anchor, bool isSourceFile)
void addWord (const QCString &word, bool hiPriority)
void write (const QCString &file)
Private Member Functions
void addWordRec (const QCString &word, bool hiPrio, bool recurse)
void addWordRec (const QCString &word, bool hiPrio, bool recurse)
Private Attributes
std::unordered_map< std::string, int > m_words
std::vector< std::vector< IndexWord > > m_index
std::unordered_map< std::string, int > m_url2IdMap
std::map< int, URL > m_urls
int m_urlIndex = -1
Detailed Description
Writes search index for doxygen provided server based search engine that uses PHP.
Definition at line 89 of file searchindex.h.
Constructor & Destructor Documentation
SearchIndex() [1/2]
SearchIndex::SearchIndex ()
Definition at line 67 of file searchindex.cpp.
{
  m_index.resize(numIndexEntries);
}
References m_index, and numIndexEntries.
SearchIndex() [2/2]
SearchIndex::SearchIndex ()
Member Function Documentation
addWord() [1/2]
void SearchIndex::addWord (const QCString & word, bool hiPriority)
Definition at line 228 of file searchindex.cpp.
{
  addWordRec(word,hiPriority,FALSE);
}
References addWordRec(), FALSE, and word.
addWord() [2/2]
void SearchIndex::addWord (const QCString & word, bool hiPriority)
addWordRec() [1/2]
void SearchIndex::addWordRec (const QCString & word, bool hiPrio, bool recurse) [private]
Definition at line 186 of file searchindex.cpp.
{
  if (word.isEmpty()) return;
  QCString wStr = QCString(word).lower();
  //printf("SearchIndex::addWord(%s,%d) wStr=%s\n",word,hiPriority,qPrint(wStr));
  int idx=charsToIndex(wStr);
  if (idx<0 || idx>=static_cast<int>(m_index.size())) return;
  auto it = m_words.find(wStr.str());
  if (it==m_words.end())
  {
    //fprintf(stderr,"addWord(%s) at index %d\n",word,idx);
    m_index[idx].push_back(IndexWord(wStr));
    it = m_words.insert({ wStr.str(), static_cast<int>(m_index[idx].size())-1 }).first;
  }
  m_index[idx][it->second].addUrlIndex(m_urlIndex,hiPriority);
  int i;
  bool found=FALSE;
  if (!recurse) // the first time we check if we can strip the prefix
  {
    i=getPrefixIndex(word);
    if (i>0)
    {
      addWordRec(word.data()+i,hiPriority,TRUE);
      found=TRUE;
    }
  }
  if (!found) // no prefix stripped
  {
    i=0;
    while (word[i]!=0 &&
           !((word[i]=='_' || word[i]==':' || (word[i]>='a' && word[i]<='z')) && // [_a-z:]
             (word[i+1]>='A' && word[i+1]<='Z'))) // [A-Z]
    {
      i++;
    }
    if (word[i]!=0 && i>=1)
    {
      addWordRec(word.data()+i+1,hiPriority,TRUE);
    }
  }
}
References addWordRec(), charsToIndex(), FALSE, found, getPrefixIndex(), QCString::lower(), m_index, m_urlIndex, m_words, size, QCString::str(), TRUE, and word.
Referenced by addWord(), and addWordRec().
addWordRec() [2/2]
void SearchIndex::addWordRec (const QCString & word, bool hiPrio, bool recurse) [private]
setCurrentDoc() [1/2]
void SearchIndex::setCurrentDoc (const Definition * ctx, const QCString & anchor, bool isSourceFile)
Definition at line 72 of file searchindex.cpp.
{
  if (ctx==0) return;
  assert(!isSourceFile || ctx->definitionType()==Definition::TypeFile);
  //printf("SearchIndex::setCurrentDoc(%s,%s,%s)\n",name,baseName,anchor);
  QCString url=isSourceFile ? (toFileDef(ctx))->getSourceFileBase() : ctx->getOutputFileBase();
  url+=Config_getString(HTML_FILE_EXTENSION);
  QCString baseUrl = url;
  if (!anchor.isEmpty()) url+=QCString("#")+anchor;
  if (!isSourceFile) baseUrl=url;
  QCString name=ctx->qualifiedName();
  if (ctx->definitionType()==Definition::TypeMember)
  {
    const MemberDef *md = toMemberDef(ctx);
    name.prepend((md->getLanguage()==SrcLangExt_Fortran ?
                 theTranslator->trSubprogram(TRUE,TRUE) :
                 theTranslator->trMember(TRUE,TRUE))+" ");
  }
  else // compound type
  {
    SrcLangExt lang = ctx->getLanguage();
    QCString sep = getLanguageSpecificSeparator(lang);
    if (sep!="::")
    {
      name = substitute(name,"::",sep);
    }
    switch (ctx->definitionType())
    {
      case Definition::TypePage:
        {
          const PageDef *pd = toPageDef(ctx);
          if (pd->hasTitle())
          {
            name = theTranslator->trPage(TRUE,TRUE)+" "+pd->title();
          }
          else
          {
            name = theTranslator->trPage(TRUE,TRUE)+" "+pd->name();
          }
        }
        break;
      case Definition::TypeClass:
        {
          const ClassDef *cd = toClassDef(ctx);
          name.prepend(cd->compoundTypeString()+" ");
        }
        break;
      case Definition::TypeNamespace:
        {
          if (lang==SrcLangExt_Java || lang==SrcLangExt_CSharp)
          {
            name = theTranslator->trPackage(name);
          }
          else if (lang==SrcLangExt_Fortran)
          {
            name.prepend(theTranslator->trModule(TRUE,TRUE)+" ");
          }
          else
          {
            name.prepend(theTranslator->trNamespace(TRUE,TRUE)+" ");
          }
        }
        break;
      case Definition::TypeGroup:
        {
          const GroupDef *gd = toGroupDef(ctx);
          if (!gd->groupTitle().isEmpty())
          {
            name = theTranslator->trGroup(TRUE,TRUE)+" "+gd->groupTitle();
          }
          else
          {
            name.prepend(theTranslator->trGroup(TRUE,TRUE)+" ");
          }
        }
        break;
      default:
        break;
    }
  }
  auto it = m_url2IdMap.find(baseUrl.str());
  if (it == m_url2IdMap.end())
  {
    ++m_urlIndex;
    m_url2IdMap.insert(std::make_pair(baseUrl.str(),m_urlIndex));
    m_urls.insert(std::make_pair(m_urlIndex,URL(name,url)));
  }
  else
  {
    m_urls.insert(std::make_pair(it->second,URL(name,url)));
  }
}
References ClassDef::compoundTypeString(), Config_getString, Definition::definitionType(), Definition::getLanguage(), getLanguageSpecificSeparator(), Definition::getOutputFileBase(), GroupDef::groupTitle(), PageDef::hasTitle(), QCString::isEmpty(), m_url2IdMap, m_urlIndex, m_urls, setup::name, Definition::name(), Definition::qualifiedName(), SrcLangExt_CSharp, SrcLangExt_Fortran, SrcLangExt_Java, QCString::str(), substitute(), theTranslator, PageDef::title(), toClassDef(), toFileDef(), toGroupDef(), toMemberDef(), toPageDef(), Translator::trGroup(), Translator::trMember(), Translator::trModule(), Translator::trNamespace(), Translator::trPackage(), Translator::trPage(), Translator::trSubprogram(), TRUE, Definition::TypeClass, Definition::TypeFile, Definition::TypeGroup, Definition::TypeMember, Definition::TypeNamespace, Definition::TypePage, and setup::url.
setCurrentDoc() [2/2]
void SearchIndex::setCurrentDoc (const Definition * ctx, const QCString & anchor, bool isSourceFile)
write() [1/2]
void SearchIndex::write (const QCString & file)
Definition at line 248 of file searchindex.cpp.
{
  size_t i;
  size_t size=4; // for the header
  size+=4*numIndexEntries; // for the index
  size_t wordsOffset = size;
  // first pass: compute the size of the wordlist
  for (i=0;i<numIndexEntries;i++)
  {
    const auto &wlist = m_index[i];
    if (!wlist.empty())
    {
      for (const auto &iw : wlist)
      {
        int ws = iw.word().length()+1;
        size+=ws+4; // word + url info list offset
      }
      size+=1; // zero list terminator
    }
  }
  // second pass: compute the offsets in the index
  size_t indexOffsets[numIndexEntries];
  size_t offset=wordsOffset;
  for (i=0;i<numIndexEntries;i++)
  {
    const auto &wlist = m_index[i];
    if (!wlist.empty())
    {
      indexOffsets[i]=offset;
      for (const auto &iw : wlist)
      {
        offset+= iw.word().length()+1;
        offset+=4; // word + offset to url info array
      }
      offset+=1; // zero list terminator
    }
    else
    {
      indexOffsets[i]=0;
    }
  }
  size_t padding = size;
  size = (size+3)&~3; // round up to 4 byte boundary
  padding = size - padding;
  std::vector<size_t> wordStatOffsets(m_words.size());
  int count=0;
  // third pass: compute offset to stats info for each word
  for (i=0;i<numIndexEntries;i++)
  {
    const auto &wlist = m_index[i];
    if (!wlist.empty())
    {
      for (const auto &iw : wlist)
      {
        //printf("wordStatOffsets[%d]=%d\n",count,size);
        wordStatOffsets[count++] = size;
        size+=4 + iw.urls().size() * 8; // count + (url_index,freq) per url
      }
    }
  }
  std::vector<size_t> urlOffsets(m_urls.size());
  for (const auto &udi : m_urls)
  {
    urlOffsets[udi.first]=size;
    size+=udi.second.name.length()+1+
          udi.second.url.length()+1;
  }
  //printf("Total size %x bytes (word=%x stats=%x urls=%x)\n",size,wordsOffset,statsOffset,urlsOffset);
  std::ofstream f(fileName.str(),std::ofstream::out | std::ofstream::binary);
  if (f.is_open())
  {
    // write header
    f.put('D'); f.put('O'); f.put('X'); f.put('S');
    // write index
    for (i=0;i<numIndexEntries;i++)
    {
      writeInt(f,indexOffsets[i]);
    }
    // write word lists
    count=0;
    for (i=0;i<numIndexEntries;i++)
    {
      const auto &wlist = m_index[i];
      if (!wlist.empty())
      {
        for (const auto &iw : wlist)
        {
          writeString(f,iw.word());
          writeInt(f,wordStatOffsets[count++]);
        }
        f.put(0);
      }
    }
    // write extra padding bytes
    for (i=0;i<padding;i++) f.put(0);
    // write word statistics
    for (i=0;i<numIndexEntries;i++)
    {
      const auto &wlist = m_index[i];
      if (!wlist.empty())
      {
        for (const auto &iw : wlist)
        {
          size_t numUrls = iw.urls().size();
          writeInt(f,numUrls);
          for (const auto &ui : iw.urls())
          {
            writeInt(f,urlOffsets[ui.second.urlIdx]);
            writeInt(f,ui.second.freq);
          }
        }
      }
    }
    // write urls
    for (const auto &udi : m_urls)
    {
      writeString(f,udi.second.name);
      writeString(f,udi.second.url);
    }
  }
}
References f, m_index, m_urls, m_words, numIndexEntries, offset, out, size, QCString::str(), writeInt(), and writeString().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_write(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_write().
write() [2/2]
void SearchIndex::write (const QCString & file)
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_write(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_write().
Member Data Documentation
m_index
std::vector< std::vector< IndexWord > > SearchIndex::m_index [private]
Definition at line 127 of file searchindex.h.
Referenced by addWordRec(), SearchIndex(), and write().
m_url2IdMap
std::unordered_map< std::string, int > SearchIndex::m_url2IdMap [private]
Definition at line 128 of file searchindex.h.
Referenced by setCurrentDoc().
m_urlIndex
int SearchIndex::m_urlIndex = -1 [private]
Definition at line 130 of file searchindex.h.
Referenced by addWordRec(), and setCurrentDoc().
m_urls
std::map< int, URL > SearchIndex::m_urls [private]
Definition at line 129 of file searchindex.h.
Referenced by setCurrentDoc(), and write().
m_words
std::unordered_map< std::string, int > SearchIndex::m_words [private]
Definition at line 126 of file searchindex.h.
Referenced by addWordRec(), and write().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/searchindex.h
doxygen/src/searchindex.h
doxygen/build/doxygen/src/searchindex.cpp
doxygen/src/searchindex.cpp