MemberDef Class Reference
#include <memberdef.h>
Public Member Functions
virtual DefType definitionType () const =0
virtual MemberDef * deepCopy () const =0
virtual void moveTo (Definition *)=0
virtual MemberDef * resolveAlias ()=0
virtual const MemberDef * resolveAlias () const =0
ClassDefMutable * getClassDefMutable () const
virtual QCString getOutputFileBase () const =0
virtual QCString getReference () const =0
virtual QCString anchor () const =0
virtual QCString declaration () const =0
virtual QCString definition () const =0
virtual QCString typeString () const =0
virtual QCString argsString () const =0
virtual QCString excpString () const =0
virtual QCString bitfieldString () const =0
virtual QCString extraTypeChars () const =0
virtual const QCString & initializer () const =0
virtual int initializerLines () const =0
virtual uint64 getMemberSpecifiers () const =0
virtual const MemberList * getSectionList (const Definition *container) const =0
virtual QCString displayDefinition () const =0
virtual const FileDef * getFileDef () const =0
virtual const ClassDef * getClassDef () const =0
virtual const NamespaceDef * getNamespaceDef () const =0
virtual const ClassDef * accessorClass () const =0
virtual QCString getReadAccessor () const =0
virtual QCString getWriteAccessor () const =0
virtual const GroupDef * getGroupDef () const =0
virtual Grouping::GroupPri_t getGroupPri () const =0
virtual QCString getGroupFileName () const =0
virtual int getGroupStartLine () const =0
virtual bool getGroupHasDocs () const =0
virtual QCString qualifiedName () const =0
virtual QCString objCMethodName (bool localLink, bool showStatic) const =0
virtual Protection protection () const =0
virtual Specifier virtualness (int count=0) const =0
virtual MemberType memberType () const =0
virtual QCString memberTypeName () const =0
virtual bool isSignal () const =0
virtual bool isSlot () const =0
virtual bool isVariable () const =0
virtual bool isEnumerate () const =0
virtual bool isEnumValue () const =0
virtual bool isTypedef () const =0
virtual bool isSequence () const =0
virtual bool isDictionary () const =0
virtual bool isFunction () const =0
virtual bool isFunctionPtr () const =0
virtual bool isDefine () const =0
virtual bool isFriend () const =0
virtual bool isDCOP () const =0
virtual bool isProperty () const =0
virtual bool isEvent () const =0
virtual bool isRelated () const =0
virtual bool isForeign () const =0
virtual bool isStatic () const =0
virtual bool isInline () const =0
virtual bool isExplicit () const =0
virtual bool isMutable () const =0
virtual bool isGettable () const =0
virtual bool isPrivateGettable () const =0
virtual bool isProtectedGettable () const =0
virtual bool isSettable () const =0
virtual bool isPrivateSettable () const =0
virtual bool isProtectedSettable () const =0
virtual bool isReadable () const =0
virtual bool isWritable () const =0
virtual bool isAddable () const =0
virtual bool isRemovable () const =0
virtual bool isRaisable () const =0
virtual bool isFinal () const =0
virtual bool isAbstract () const =0
virtual bool isOverride () const =0
virtual bool isInitonly () const =0
virtual bool isOptional () const =0
virtual bool isRequired () const =0
virtual bool isNonAtomic () const =0
virtual bool isCopy () const =0
virtual bool isAssign () const =0
virtual bool isRetain () const =0
virtual bool isWeak () const =0
virtual bool isStrong () const =0
virtual bool isEnumStruct () const =0
virtual bool isUnretained () const =0
virtual bool isNew () const =0
virtual bool isSealed () const =0
virtual bool isImplementation () const =0
virtual bool isExternal () const =0
virtual bool isTypeAlias () const =0
virtual bool isDefault () const =0
virtual bool isDelete () const =0
virtual bool isNoExcept () const =0
virtual bool isAttribute () const =0
virtual bool isUNOProperty () const =0
virtual bool isReadonly () const =0
virtual bool isBound () const =0
virtual bool isConstrained () const =0
virtual bool isTransient () const =0
virtual bool isMaybeVoid () const =0
virtual bool isMaybeDefault () const =0
virtual bool isMaybeAmbiguous () const =0
virtual bool isPublished () const =0
virtual bool isTemplateSpecialization () const =0
virtual bool isObjCMethod () const =0
virtual bool isObjCProperty () const =0
virtual bool isCSharpProperty () const =0
virtual bool isConstructor () const =0
virtual bool isDestructor () const =0
virtual bool hasOneLineInitializer () const =0
virtual bool hasMultiLineInitializer () const =0
virtual bool showInCallGraph () const =0
virtual bool isStrongEnumValue () const =0
virtual bool livesInsideEnum () const =0
virtual bool isSliceLocal () const =0
virtual bool isConstExpr () const =0
virtual int numberOfFlowKeyWords () const =0
virtual bool isFriendToHide () const =0
virtual bool isNotFriend () const =0
virtual bool isFunctionOrSignalSlot () const =0
virtual bool isRelatedOrFriend () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool hasDocumentation () const =0
virtual bool isDeleted () const =0
virtual bool isBriefSectionVisible () const =0
virtual bool isDetailedSectionVisible (MemberListContainer container) const =0
virtual bool hasDetailedDescription () const =0
virtual bool isFriendClass () const =0
virtual bool isDocumentedFriendClass () const =0
virtual const MemberDef * reimplements () const =0
virtual const MemberVector & reimplementedBy () const =0
virtual bool isReimplementedBy (const ClassDef *cd) const =0
virtual ClassDef * relatedAlso () const =0
virtual bool hasDocumentedEnumValues () const =0
virtual const MemberDef * getAnonymousEnumType () const =0
virtual bool isDocsForDefinition () const =0
virtual const MemberDef * getEnumScope () const =0
virtual const MemberVector & enumFieldList () const =0
virtual QCString enumBaseType () const =0
virtual bool hasExamples () const =0
virtual const ExampleList & getExamples () const =0
virtual bool isPrototype () const =0
virtual const ArgumentList & argumentList () const =0
virtual const ArgumentList & declArgumentList () const =0
virtual const ArgumentList & templateArguments () const =0
virtual const ArgumentLists & definitionTemplateParameterLists () const =0
virtual int getMemberGroupId () const =0
virtual MemberGroup * getMemberGroup () const =0
virtual bool fromAnonymousScope () const =0
virtual bool anonymousDeclShown () const =0
virtual MemberDef * fromAnonymousMember () const =0
virtual bool hasCallGraph () const =0
virtual bool hasCallerGraph () const =0
virtual bool hasReferencesRelation () const =0
virtual bool hasReferencedByRelation () const =0
virtual const MemberDef * templateMaster () const =0
virtual QCString getScopeString () const =0
virtual ClassDef * getClassDefOfAnonymousType () const =0
virtual bool isTypedefValCached () const =0
virtual const ClassDef * getCachedTypedefVal () const =0
virtual QCString getCachedTypedefTemplSpec () const =0
virtual QCString getCachedResolvedTypedef () const =0
virtual MemberDef * memberDefinition () const =0
virtual MemberDef * memberDeclaration () const =0
virtual const MemberDef * inheritsDocsFrom () const =0
virtual const MemberDef * getGroupAlias () const =0
virtual ClassDef * category () const =0
virtual const MemberDef * categoryRelation () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual QCString getDeclType () const =0
virtual StringVector getLabels (const Definition *container) const =0
virtual const ArgumentList & typeConstraints () const =0
virtual QCString requiresClause () const =0
virtual QCString documentation () const =0
virtual QCString briefDescription (bool abbr=FALSE) const =0
virtual QCString fieldType () const =0
virtual bool isReference () const =0
virtual QCString getDeclFileName () const =0
virtual int getDeclLine () const =0
virtual int getDeclColumn () const =0
virtual MemberDefMutable * createTemplateInstanceMember (const ArgumentList &formalArgs, const std::unique_ptr< ArgumentList > &actualArgs) const =0
virtual void writeDeclaration (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool inGroup, int indentLevel=0, const ClassDef *inheritFrom=0, const QCString &inheritId=QCString()) const =0
virtual void writeEnumDeclaration (OutputList &typeDecl, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd) const =0
virtual void detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const =0
virtual void warnIfUndocumented () const =0
virtual void warnIfUndocumentedParams () const =0
virtual bool visibleInIndex () const =0
virtual void setMemberGroup (MemberGroup *grp)=0
virtual DefType definitionType () const =0
virtual MemberDef * deepCopy () const =0
virtual void moveTo (Definition *)=0
virtual MemberDef * resolveAlias ()=0
virtual const MemberDef * resolveAlias () const =0
ClassDefMutable * getClassDefMutable () const
virtual QCString getOutputFileBase () const =0
virtual QCString getReference () const =0
virtual QCString anchor () const =0
virtual QCString declaration () const =0
virtual QCString definition () const =0
virtual QCString typeString () const =0
virtual QCString argsString () const =0
virtual QCString excpString () const =0
virtual QCString bitfieldString () const =0
virtual QCString extraTypeChars () const =0
virtual const QCString & initializer () const =0
virtual int initializerLines () const =0
virtual uint64 getMemberSpecifiers () const =0
virtual const MemberList * getSectionList (const Definition *container) const =0
virtual QCString displayDefinition () const =0
virtual const FileDef * getFileDef () const =0
virtual const ClassDef * getClassDef () const =0
virtual const NamespaceDef * getNamespaceDef () const =0
virtual const ClassDef * accessorClass () const =0
virtual QCString getReadAccessor () const =0
virtual QCString getWriteAccessor () const =0
virtual const GroupDef * getGroupDef () const =0
virtual Grouping::GroupPri_t getGroupPri () const =0
virtual QCString getGroupFileName () const =0
virtual int getGroupStartLine () const =0
virtual bool getGroupHasDocs () const =0
virtual QCString qualifiedName () const =0
virtual QCString objCMethodName (bool localLink, bool showStatic) const =0
virtual Protection protection () const =0
virtual Specifier virtualness (int count=0) const =0
virtual MemberType memberType () const =0
virtual QCString memberTypeName () const =0
virtual bool isSignal () const =0
virtual bool isSlot () const =0
virtual bool isVariable () const =0
virtual bool isEnumerate () const =0
virtual bool isEnumValue () const =0
virtual bool isTypedef () const =0
virtual bool isSequence () const =0
virtual bool isDictionary () const =0
virtual bool isFunction () const =0
virtual bool isFunctionPtr () const =0
virtual bool isDefine () const =0
virtual bool isFriend () const =0
virtual bool isDCOP () const =0
virtual bool isProperty () const =0
virtual bool isEvent () const =0
virtual bool isRelated () const =0
virtual bool isForeign () const =0
virtual bool isStatic () const =0
virtual bool isInline () const =0
virtual bool isExplicit () const =0
virtual bool isMutable () const =0
virtual bool isGettable () const =0
virtual bool isPrivateGettable () const =0
virtual bool isProtectedGettable () const =0
virtual bool isSettable () const =0
virtual bool isPrivateSettable () const =0
virtual bool isProtectedSettable () const =0
virtual bool isReadable () const =0
virtual bool isWritable () const =0
virtual bool isAddable () const =0
virtual bool isRemovable () const =0
virtual bool isRaisable () const =0
virtual bool isFinal () const =0
virtual bool isAbstract () const =0
virtual bool isOverride () const =0
virtual bool isInitonly () const =0
virtual bool isOptional () const =0
virtual bool isRequired () const =0
virtual bool isNonAtomic () const =0
virtual bool isCopy () const =0
virtual bool isAssign () const =0
virtual bool isRetain () const =0
virtual bool isWeak () const =0
virtual bool isStrong () const =0
virtual bool isEnumStruct () const =0
virtual bool isUnretained () const =0
virtual bool isNew () const =0
virtual bool isSealed () const =0
virtual bool isImplementation () const =0
virtual bool isExternal () const =0
virtual bool isTypeAlias () const =0
virtual bool isDefault () const =0
virtual bool isDelete () const =0
virtual bool isNoExcept () const =0
virtual bool isAttribute () const =0
virtual bool isUNOProperty () const =0
virtual bool isReadonly () const =0
virtual bool isBound () const =0
virtual bool isConstrained () const =0
virtual bool isTransient () const =0
virtual bool isMaybeVoid () const =0
virtual bool isMaybeDefault () const =0
virtual bool isMaybeAmbiguous () const =0
virtual bool isPublished () const =0
virtual bool isTemplateSpecialization () const =0
virtual bool isObjCMethod () const =0
virtual bool isObjCProperty () const =0
virtual bool isCSharpProperty () const =0
virtual bool isConstructor () const =0
virtual bool isDestructor () const =0
virtual bool hasOneLineInitializer () const =0
virtual bool hasMultiLineInitializer () const =0
virtual bool showInCallGraph () const =0
virtual bool isStrongEnumValue () const =0
virtual bool livesInsideEnum () const =0
virtual bool isSliceLocal () const =0
virtual bool isConstExpr () const =0
virtual int numberOfFlowKeyWords () const =0
virtual bool isFriendToHide () const =0
virtual bool isNotFriend () const =0
virtual bool isFunctionOrSignalSlot () const =0
virtual bool isRelatedOrFriend () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool hasDocumentation () const =0
virtual bool isDeleted () const =0
virtual bool isBriefSectionVisible () const =0
virtual bool isDetailedSectionVisible (MemberListContainer container) const =0
virtual bool hasDetailedDescription () const =0
virtual bool isFriendClass () const =0
virtual bool isDocumentedFriendClass () const =0
virtual const MemberDef * reimplements () const =0
virtual const MemberVector & reimplementedBy () const =0
virtual bool isReimplementedBy (const ClassDef *cd) const =0
virtual ClassDef * relatedAlso () const =0
virtual bool hasDocumentedEnumValues () const =0
virtual const MemberDef * getAnonymousEnumType () const =0
virtual bool isDocsForDefinition () const =0
virtual const MemberDef * getEnumScope () const =0
virtual const MemberVector & enumFieldList () const =0
virtual QCString enumBaseType () const =0
virtual bool hasExamples () const =0
virtual const ExampleList & getExamples () const =0
virtual bool isPrototype () const =0
virtual const ArgumentList & argumentList () const =0
virtual const ArgumentList & declArgumentList () const =0
virtual const ArgumentList & templateArguments () const =0
virtual const ArgumentLists & definitionTemplateParameterLists () const =0
virtual int getMemberGroupId () const =0
virtual MemberGroup * getMemberGroup () const =0
virtual bool fromAnonymousScope () const =0
virtual bool anonymousDeclShown () const =0
virtual MemberDef * fromAnonymousMember () const =0
virtual bool hasCallGraph () const =0
virtual bool hasCallerGraph () const =0
virtual bool hasReferencesRelation () const =0
virtual bool hasReferencedByRelation () const =0
virtual const MemberDef * templateMaster () const =0
virtual QCString getScopeString () const =0
virtual ClassDef * getClassDefOfAnonymousType () const =0
virtual bool isTypedefValCached () const =0
virtual const ClassDef * getCachedTypedefVal () const =0
virtual QCString getCachedTypedefTemplSpec () const =0
virtual QCString getCachedResolvedTypedef () const =0
virtual MemberDef * memberDefinition () const =0
virtual MemberDef * memberDeclaration () const =0
virtual const MemberDef * inheritsDocsFrom () const =0
virtual const MemberDef * getGroupAlias () const =0
virtual ClassDef * category () const =0
virtual const MemberDef * categoryRelation () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual QCString getDeclType () const =0
virtual StringVector getLabels (const Definition *container) const =0
virtual const ArgumentList & typeConstraints () const =0
virtual QCString requiresClause () const =0
virtual QCString documentation () const =0
virtual QCString briefDescription (bool abbr=FALSE) const =0
virtual QCString fieldType () const =0
virtual bool isReference () const =0
virtual QCString getDeclFileName () const =0
virtual int getDeclLine () const =0
virtual int getDeclColumn () const =0
virtual MemberDefMutable * createTemplateInstanceMember (const ArgumentList &formalArgs, const std::unique_ptr< ArgumentList > &actualArgs) const =0
virtual void writeDeclaration (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool inGroup, int indentLevel=0, const ClassDef *inheritFrom=0, const QCString &inheritId=QCString()) const =0
virtual void writeEnumDeclaration (OutputList &typeDecl, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd) const =0
virtual void detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const =0
virtual void warnIfUndocumented () const =0
virtual void warnIfUndocumentedParams () const =0
virtual bool visibleInIndex () const =0
virtual void setMemberGroup (MemberGroup *grp)=0
Additional Inherited Members
Detailed Description
A model of a class/file/namespace member symbol.
Definition at line 45 of file memberdef.h.
Member Function Documentation
accessorClass() [1/2]
virtual const ClassDef * MemberDef::accessorClass () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::accessorClass().
accessorClass() [2/2]
virtual const ClassDef * MemberDef::accessorClass () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
anchor() [1/2]
virtual QCString MemberDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DefinitionImpl::_writeSourceRefList(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), DocSets::addIndexItem(), HtmlHelp::addIndexItem(), Qhp::addIndexItem(), addToIndices(), MemberDefImpl::anchor(), MemberDefAliasImpl::anchor(), DotCallGraph::DotCallGraph(), dumpSymbol(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), generateDEFForMember(), generateXMLForMember(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), MemberDefImpl::getOutputFileBase(), getUniqueId(), DocParser::handleLinkedWord(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), if(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), resolveLink(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), doxmlparser.compound.docTocItemType::set_anchor(), validatingParseDoc(), writeClassLinkForMember(), writeColumn(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclaration(), writeFileLinkForMember(), writeLink(), writeListOfAllMembers(), ClassDefImpl::writeMemberList(), writeMemberReference(), writeMemberToIndex(), writeNamespaceLinkForMember(), ClassDefImpl::writeQuickMemberLinks(), VhdlDocGen::writeTagFile(), and VhdlDocGen::writeVHDLDeclaration().
anchor() [2/2]
virtual QCString MemberDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anonymousDeclShown() [1/2]
virtual bool MemberDef::anonymousDeclShown () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::anonymousDeclShown().
anonymousDeclShown() [2/2]
virtual bool MemberDef::anonymousDeclShown () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
argsString() [1/2]
virtual QCString MemberDef::argsString () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by HtmlHelp::addIndexItem(), Qhp::addIndexItem(), addMemberFunction(), addVariableToFile(), MemberDefAliasImpl::argsString(), combineDeclarationAndDefinition(), VhdlDocGen::correctMemberProperties(), MemberContext::Private::createDeclArgs(), SymbolContext::Private::createScope(), findMember(), findUsedClassesForClass(), findUsingDeclImports(), generateClassMemberLink(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), genericCompareMembers(), SymbolResolver::Private::getResolvedType(), resolveTypeDef(), writeColumn(), writeJavaScriptSearchIndex(), ClassDefImpl::writeMemberList(), VhdlDocGen::writeTagFile(), writeUCFLink(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVHDLTypeDocumentation().
argsString() [2/2]
virtual QCString MemberDef::argsString () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
argumentList() [1/2]
virtual const ArgumentList & MemberDef::argumentList () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberDocs(), addMemberFunction(), MemberDefAliasImpl::argumentList(), DocParser::checkArgumentName(), DocParser::checkUnOrMultipleDocumentedParams(), combineDeclarationAndDefinition(), computeMemberRelations(), MemberDefImpl::copyArgumentNames(), MemberContext::Private::createParamDocs(), findMember(), findMembersWithSpecificName(), findUsingDeclImports(), functionInformation(), functionSignature(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), MemberContext::Private::getDefArgList(), getDefsOld(), SymbolResolver::Private::getResolvedSymbol(), MemberDefImpl::hasDetailedDescription(), GroupDefImpl::insertMember(), ClassDefImpl::mergeMembers(), prototypeInformation(), MemberDefImpl::resolveUnnamedParameters(), setParameterList(), transferFunctionReferences(), transferRelatedFunctionDocumentation(), writeDefArgumentList(), MemberDefImpl::writeDocumentation(), VhdlDocGen::writeTagFile(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVHDLTypeDocumentation().
argumentList() [2/2]
virtual const ArgumentList & MemberDef::argumentList () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
bitfieldString() [1/2]
virtual QCString MemberDef::bitfieldString () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::bitfieldString(), MemberContext::Private::createBitfields(), findUsingDeclImports(), PerlModGenerator::generatePerlModForMember(), and generateXMLForMember().
bitfieldString() [2/2]
virtual QCString MemberDef::bitfieldString () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
briefDescription() [1/2]
virtual QCString MemberDef::briefDescription (bool abbreviate = FALSE) const [pure virtual]
Returns the brief description of this definition. This can include commands.
Implements Definition.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, DefinitionMixin< MemberDefMutable >, and DefinitionAliasMixin< MemberDef >.
Referenced by ClassDefImpl::addMembersToTemplateInstance(), MemberDefImpl::briefDescription(), MemberDefAliasImpl::briefDescription(), combineDeclarationAndDefinition(), MemberGroup::distributeMemberGroupDocumentation(), DocParser::findDocsForMemberOrCompound(), findUsingDeclImports(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), DocPara::handleInheritDoc(), inheritDocumentation(), and VhdlDocGen::writeVHDLDeclaration().
briefDescription() [2/2]
virtual QCString MemberDef::briefDescription (bool abbreviate = FALSE) const [pure virtual]
Returns the brief description of this definition. This can include commands.
Implements Definition.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, DefinitionMixin< MemberDefMutable >, and DefinitionAliasMixin< MemberDef >.
category() [1/2]
virtual ClassDef * MemberDef::category () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), MemberDefAliasImpl::category(), MemberContext::Private::createCategory(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::getCategory(), doxmlparser.index.MixedContainer::getCategory(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), and ClassDefImpl::writeMemberList().
category() [2/2]
virtual ClassDef * MemberDef::category () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::getCategory(), doxmlparser.index.MixedContainer::getCategory(), doxmlparser.compound.MixedContainer::to_etree(), and doxmlparser.index.MixedContainer::to_etree().
categoryRelation() [1/2]
virtual const MemberDef * MemberDef::categoryRelation () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::categoryRelation(), and MemberContext::Private::createCategoryRelation().
categoryRelation() [2/2]
virtual const MemberDef * MemberDef::categoryRelation () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
createTemplateInstanceMember() [1/2]
virtual MemberDefMutable * MemberDef::createTemplateInstanceMember (const ArgumentList & formalArgs, const std::unique_ptr< ArgumentList > & actualArgs) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by ClassDefImpl::addMembersToTemplateInstance(), and MemberDefAliasImpl::createTemplateInstanceMember().
createTemplateInstanceMember() [2/2]
virtual MemberDefMutable * MemberDef::createTemplateInstanceMember (const ArgumentList & formalArgs, const std::unique_ptr< ArgumentList > & actualArgs) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
declaration() [1/2]
virtual QCString MemberDef::declaration () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::declaration(), findGlobalMember(), and TooltipManager::writeTooltips().
declaration() [2/2]
virtual QCString MemberDef::declaration () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
declArgumentList() [1/2]
virtual const ArgumentList & MemberDef::declArgumentList () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DocParser::checkArgumentName(), DocParser::checkUnOrMultipleDocumentedParams(), MemberDefImpl::copyArgumentNames(), MemberDefAliasImpl::declArgumentList(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), MemberContext::Private::getDefArgList(), MemberDefImpl::resolveUnnamedParameters(), and writeDefArgumentList().
declArgumentList() [2/2]
virtual const ArgumentList & MemberDef::declArgumentList () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
deepCopy() [1/2]
virtual MemberDef * MemberDef::deepCopy () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
deepCopy() [2/2]
virtual MemberDef * MemberDef::deepCopy () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
definition() [1/2]
virtual QCString MemberDef::definition () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), MemberDefAliasImpl::definition(), doxmlparser.compound.memberdefType::exportChildren(), findUsingDeclImports(), generateXMLForMember(), doxmlparser.compound.memberdefType::get_definition(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_definition().
definition() [2/2]
virtual QCString MemberDef::definition () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_definition(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_definition().
definitionTemplateParameterLists() [1/2]
virtual const ArgumentLists & MemberDef::definitionTemplateParameterLists () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createTemplateDecls(), and MemberDefAliasImpl::definitionTemplateParameterLists().
definitionTemplateParameterLists() [2/2]
virtual const ArgumentLists & MemberDef::definitionTemplateParameterLists () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
definitionType() [1/2]
virtual DefType MemberDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateClassOrGlobalLink().
definitionType() [2/2]
virtual DefType MemberDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
detectUndocumentedParams() [1/2]
virtual void MemberDef::detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by validatingParseDoc().
detectUndocumentedParams() [2/2]
virtual void MemberDef::detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
displayDefinition() [1/2]
virtual QCString MemberDef::displayDefinition () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createDefinition(), and MemberDefAliasImpl::displayDefinition().
displayDefinition() [2/2]
virtual QCString MemberDef::displayDefinition () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
displayName() [1/2]
virtual QCString MemberDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in MemberDefAliasImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefImpl.
Referenced by MemberDefAliasImpl::displayName(), MemberContext::Private::handleNameWithContextFor(), and MemberDefImpl::writeLink().
displayName() [2/2]
virtual QCString MemberDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in MemberDefAliasImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefImpl.
documentation() [1/2]
virtual QCString MemberDef::documentation () const [pure virtual]
Returns the detailed description of this definition
Implements Definition.
Implemented in DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, and MemberDefAliasImpl.
Referenced by ClassDefImpl::addMembersToTemplateInstance(), combineDeclarationAndDefinition(), MemberGroup::distributeMemberGroupDocumentation(), MemberDefImpl::documentation(), MemberDefAliasImpl::documentation(), DocParser::findDocsForMemberOrCompound(), findUsingDeclImports(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), DocPara::handleInheritDoc(), inheritDocumentation(), and VhdlDocGen::writeSource().
documentation() [2/2]
virtual QCString MemberDef::documentation () const [pure virtual]
Returns the detailed description of this definition
Implements Definition.
Implemented in DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, and MemberDefAliasImpl.
enumBaseType() [1/2]
virtual QCString MemberDef::enumBaseType () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::enumBaseType(), MemberDefAliasImpl::enumBaseType(), and generateXMLForMember().
enumBaseType() [2/2]
virtual QCString MemberDef::enumBaseType () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
enumFieldList() [1/2]
virtual const MemberVector & MemberDef::enumFieldList () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberList::addListReferences(), NestingNodeContext::Private::addMembers(), addMembersToMemberGroup(), addMemberToGroups(), addToIndices(), MemberContext::Private::createEnumValues(), MemberDefAliasImpl::enumFieldList(), findDEV(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), getDefsOld(), writeMemberToIndex(), and MemberList::writeTagFile().
enumFieldList() [2/2]
virtual const MemberVector & MemberDef::enumFieldList () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
excpString() [1/2]
virtual QCString MemberDef::excpString () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createException(), MemberDefAliasImpl::excpString(), findUsingDeclImports(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), writeExceptionList(), and VhdlDocGen::writeFunctionProto().
excpString() [2/2]
virtual QCString MemberDef::excpString () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
extraTypeChars() [1/2]
virtual QCString MemberDef::extraTypeChars () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::extraTypeChars(), MemberDefAliasImpl::extraTypeChars(), and writeDefArgumentList().
extraTypeChars() [2/2]
virtual QCString MemberDef::extraTypeChars () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
fieldType() [1/2]
virtual QCString MemberDef::fieldType () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createFieldType(), and MemberDefAliasImpl::fieldType().
fieldType() [2/2]
virtual QCString MemberDef::fieldType () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
fromAnonymousMember() [1/2]
virtual MemberDef * MemberDef::fromAnonymousMember () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createAnonymousMember(), and MemberDefAliasImpl::fromAnonymousMember().
fromAnonymousMember() [2/2]
virtual MemberDef * MemberDef::fromAnonymousMember () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
fromAnonymousScope() [1/2]
virtual bool MemberDef::fromAnonymousScope () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::fromAnonymousScope().
fromAnonymousScope() [2/2]
virtual bool MemberDef::fromAnonymousScope () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getAnonymousEnumType() [1/2]
virtual const MemberDef * MemberDef::getAnonymousEnumType () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::getAnonymousEnumType().
getAnonymousEnumType() [2/2]
virtual const MemberDef * MemberDef::getAnonymousEnumType () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getCachedResolvedTypedef() [1/2]
virtual QCString MemberDef::getCachedResolvedTypedef () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::getCachedResolvedTypedef(), and SymbolResolver::Private::newResolveTypedef().
getCachedResolvedTypedef() [2/2]
virtual QCString MemberDef::getCachedResolvedTypedef () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getCachedTypedefTemplSpec() [1/2]
virtual QCString MemberDef::getCachedTypedefTemplSpec () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::getCachedTypedefTemplSpec(), and SymbolResolver::Private::newResolveTypedef().
getCachedTypedefTemplSpec() [2/2]
virtual QCString MemberDef::getCachedTypedefTemplSpec () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getCachedTypedefVal() [1/2]
virtual const ClassDef * MemberDef::getCachedTypedefVal () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by flushCachedTemplateRelations(), MemberDefAliasImpl::getCachedTypedefVal(), and SymbolResolver::Private::newResolveTypedef().
getCachedTypedefVal() [2/2]
virtual const ClassDef * MemberDef::getCachedTypedefVal () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getClassDef() [1/2]
virtual const ClassDef * MemberDef::getClassDef () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefImpl::_isReimplements(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), addClassMemberNameToIndex(), addEnumValuesToEnums(), DocSets::addIndexItem(), PerlModGenerator::addListOfAllMembers(), addMemberFunction(), addMemberSpecialization(), addMemberToSearchIndex(), addToIndices(), addVariableToClass(), computeMemberRelations(), MemberContext::Private::createClassDef(), MemberContext::Private::createImplements(), MemberContext::Private::createInitializerAsCode(), MemberContext::Private::createReimplements(), SymbolContext::Private::createScope(), MemberContext::Private::createSourceCode(), MemberContext::Private::createTemplateDecls(), DocRef::DocRef(), findEnumDocumentation(), generateClassMemberLink(), generateDEFForMember(), MemberDefAliasImpl::getClassDef(), getClassDefMutable(), getDefsNew(), getDefsOld(), DocParser::handleLinkedWord(), MemberContext::Private::handleNameWithContextFor(), GroupDefImpl::insertMember(), FileDefImpl::insertMember(), NamespaceDefImpl::insertMember(), ClassDefImpl::isAccessibleMember(), isPartOfCStruct(), MemberGroup::memberContainer(), ClassDefImpl::mergeMembers(), SymbolResolver::Private::newResolveTypedef(), VHDLCodeParser::parseCode(), AllMembersListContext::Private::Private(), referenceTo(), setParameterList(), writeClassLinkForMember(), MemberDefImpl::writeDeclaration(), writeJavaScriptSearchIndex(), ClassDefImpl::writeMemberList(), writeMemberTemplateLists(), ClassDefImpl::writeQuickMemberLinks(), and VhdlDocGen::writeStringLink().
getClassDef() [2/2]
virtual const ClassDef * MemberDef::getClassDef () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getClassDefMutable() [1/2]
ClassDefMutable * MemberDef::getClassDefMutable () const [inline]
Definition at line 431 of file memberdef.h.
{
  return toClassDefMutable(getClassDef());
}
References getClassDef(), and toClassDefMutable().
Referenced by addMemberDocs(), and addMemberFunction().
getClassDefMutable() [2/2]
ClassDefMutable * MemberDef::getClassDefMutable () const
getClassDefOfAnonymousType() [1/2]
virtual ClassDef * MemberDef::getClassDefOfAnonymousType () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberToGroups(), MemberContext::Private::createAnonymousType(), MemberDefAliasImpl::getClassDefOfAnonymousType(), ClassDefImpl::setGroupDefForAllMembers(), and VhdlDocGen::writeVHDLDeclaration().
getClassDefOfAnonymousType() [2/2]
virtual ClassDef * MemberDef::getClassDefOfAnonymousType () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getDeclColumn() [1/2]
virtual int MemberDef::getDeclColumn () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), and MemberDefAliasImpl::getDeclColumn().
getDeclColumn() [2/2]
virtual int MemberDef::getDeclColumn () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getDeclFileName() [1/2]
virtual QCString MemberDef::getDeclFileName () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), and MemberDefAliasImpl::getDeclFileName().
getDeclFileName() [2/2]
virtual QCString MemberDef::getDeclFileName () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getDeclLine() [1/2]
virtual int MemberDef::getDeclLine () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), and MemberDefAliasImpl::getDeclLine().
getDeclLine() [2/2]
virtual int MemberDef::getDeclLine () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getDeclType() [1/2]
virtual QCString MemberDef::getDeclType () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createDeclType(), and MemberDefAliasImpl::getDeclType().
getDeclType() [2/2]
virtual QCString MemberDef::getDeclType () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getEnumScope() [1/2]
virtual const MemberDef * MemberDef::getEnumScope () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addClassMemberNameToIndex(), addFileMemberNameToIndex(), addMemberFunction(), addNamespaceMemberNameToIndex(), findGlobalMember(), getDefsOld(), MemberDefAliasImpl::getEnumScope(), MemberContext::Private::handleNameWithContextFor(), SymbolResolver::Private::isAccessibleFrom(), and SymbolResolver::Private::isAccessibleFromWithExpScope().
getEnumScope() [2/2]
virtual const MemberDef * MemberDef::getEnumScope () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getExamples() [1/2]
virtual const ExampleList & MemberDef::getExamples () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createExamples(), and MemberDefAliasImpl::getExamples().
getExamples() [2/2]
virtual const ExampleList & MemberDef::getExamples () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getFileDef() [1/2]
virtual const FileDef * MemberDef::getFileDef () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addEnumValuesToEnums(), addFileMemberNameToIndex(), DocSets::addIndexItem(), HtmlHelp::addIndexItem(), Qhp::addIndexItem(), addMemberDocs(), addMemberFunction(), addMemberToSearchIndex(), addToIndices(), addVariableToFile(), combineDeclarationAndDefinition(), computeMemberRelations(), MemberContext::Private::createFileDef(), VhdlDocGen::createFlowChart(), SymbolContext::Private::createScope(), findDefineDocumentation(), findEnumDocumentation(), findGlobalMember(), findMember(), findMembersWithSpecificName(), generateClassMemberLink(), generateClassOrGlobalLink(), generateXMLForMember(), getDefsNew(), getDefsOld(), MemberDefAliasImpl::getFileDef(), getLinkInScope(), SymbolResolver::Private::getResolvedSymbol(), ignoreStaticExternalCall(), GroupDefImpl::insertMember(), SymbolResolver::Private::isAccessibleFrom(), MemberGroup::memberContainer(), ClassDefImpl::mergeMembers(), referenceTo(), transferFunctionReferences(), transferRelatedFunctionDocumentation(), MemberDefImpl::writeDeclaration(), writeFileLinkForMember(), writeJavaScriptSearchIndex(), writeMemberTemplateLists(), and VhdlDocGen::writeSource().
getFileDef() [2/2]
virtual const FileDef * MemberDef::getFileDef () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getGroupAlias() [1/2]
virtual const MemberDef * MemberDef::getGroupAlias () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::getGroupAlias(), and GroupDefImpl::insertMember().
getGroupAlias() [2/2]
virtual const MemberDef * MemberDef::getGroupAlias () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getGroupDef() [1/2]
virtual const GroupDef * MemberDef::getGroupDef () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addEnumDocs(), DocSets::addIndexItem(), HtmlHelp::addIndexItem(), Qhp::addIndexItem(), MemberList::addListReferences(), addMemberToGroups(), addMemberToSearchIndex(), addToIndices(), combineDeclarationAndDefinition(), findMembersWithSpecificName(), generateClassMemberLink(), generateClassOrGlobalLink(), generateXMLForMember(), getDefsNew(), getDefsOld(), MemberDefAliasImpl::getGroupDef(), getLink(), getLinkInScope(), MemberGroup::insertMember(), NestingNodeContext::Private::partOfGroup(), MemberDefImpl::setEnumScope(), MemberDefImpl::writeDeclaration(), MemberDefImpl::writeLink(), writeMemberToIndex(), and VhdlDocGen::writeVHDLDeclaration().
getGroupDef() [2/2]
virtual const GroupDef * MemberDef::getGroupDef () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getGroupFileName() [1/2]
virtual QCString MemberDef::getGroupFileName () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberToGroups(), MemberDefAliasImpl::getGroupFileName(), MemberGroup::insertMember(), and MemberDefImpl::setEnumScope().
getGroupFileName() [2/2]
virtual QCString MemberDef::getGroupFileName () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getGroupHasDocs() [1/2]
virtual bool MemberDef::getGroupHasDocs () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberToGroups(), MemberDefAliasImpl::getGroupHasDocs(), MemberGroup::insertMember(), and MemberDefImpl::setEnumScope().
getGroupHasDocs() [2/2]
virtual bool MemberDef::getGroupHasDocs () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getGroupPri() [1/2]
virtual Grouping::GroupPri_t MemberDef::getGroupPri () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberToGroups(), combineDeclarationAndDefinition(), MemberDefAliasImpl::getGroupPri(), MemberGroup::insertMember(), and MemberDefImpl::setEnumScope().
getGroupPri() [2/2]
virtual Grouping::GroupPri_t MemberDef::getGroupPri () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getGroupStartLine() [1/2]
virtual int MemberDef::getGroupStartLine () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberToGroups(), MemberDefAliasImpl::getGroupStartLine(), MemberGroup::insertMember(), and MemberDefImpl::setEnumScope().
getGroupStartLine() [2/2]
virtual int MemberDef::getGroupStartLine () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getLabels() [1/2]
virtual StringVector MemberDef::getLabels (const Definition * container) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createLabels(), and MemberDefAliasImpl::getLabels().
getLabels() [2/2]
virtual StringVector MemberDef::getLabels (const Definition * container) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getMemberGroup() [1/2]
virtual MemberGroup * MemberDef::getMemberGroup () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getMemberGroup() [2/2]
virtual MemberGroup * MemberDef::getMemberGroup () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getMemberGroupId() [1/2]
virtual int MemberDef::getMemberGroupId () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addEnumDocs(), addMemberDocs(), addMembersToMemberGroup(), ClassDefImpl::addMembersToTemplateInstance(), and MemberDefAliasImpl::getMemberGroupId().
getMemberGroupId() [2/2]
virtual int MemberDef::getMemberGroupId () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getMemberSpecifiers() [1/2]
virtual uint64 MemberDef::getMemberSpecifiers () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by ClassDefImpl::addMembersToTemplateInstance(), combineDeclarationAndDefinition(), VhdlDocGen::correctMemberProperties(), findUsingDeclImports(), MemberDefAliasImpl::getMemberSpecifiers(), ClassDefImpl::internalInsertMember(), VhdlDocGen::isAlias(), VhdlDocGen::isArchitecture(), VhdlDocGen::isAttribute(), VhdlDocGen::isCompInst(), VhdlDocGen::isComponent(), VhdlDocGen::isConfig(), VhdlDocGen::isConstant(), VhdlDocGen::isConstraint(), VhdlDocGen::isEntity(), VhdlDocGen::isFile(), VhdlDocGen::isGeneric(), VhdlDocGen::isGroup(), VhdlDocGen::isLibrary(), VhdlDocGen::isMisc(), VhdlDocGen::isPackage(), VhdlDocGen::isPackageBody(), VhdlDocGen::isPort(), VhdlDocGen::isProcedure(), VhdlDocGen::isProcess(), VhdlDocGen::isRecord(), VhdlDocGen::isSignal(), VhdlDocGen::isSignals(), VhdlDocGen::isSubType(), VhdlDocGen::isUnit(), VhdlDocGen::isVariable(), VhdlDocGen::isVhdlFunction(), VhdlDocGen::isVType(), ClassDefImpl::writeMemberList(), VhdlDocGen::writePlainVHDLDeclarations(), and VhdlDocGen::writeVHDLDeclaration().
getMemberSpecifiers() [2/2]
virtual uint64 MemberDef::getMemberSpecifiers () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getNamespaceDef() [1/2]
virtual const NamespaceDef * MemberDef::getNamespaceDef () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addEnumValuesToEnums(), DocSets::addIndexItem(), addMemberDocs(), addMembersToIndex(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), addToIndices(), addVariableToFile(), MemberContext::Private::createInitializerAsCode(), MemberContext::Private::createNamespaceDef(), SymbolContext::Private::createScope(), MemberContext::Private::createSourceCode(), findEnumDocumentation(), findGlobalMember(), findMembersWithSpecificName(), generateDEFForMember(), getDefsNew(), getDefsOld(), MemberDefAliasImpl::getNamespaceDef(), MemberContext::Private::handleNameWithContextFor(), MemberGroup::memberContainer(), memberVisible(), referenceTo(), transferFunctionDocumentation(), MemberDefImpl::writeDeclaration(), writeJavaScriptSearchIndex(), and writeNamespaceLinkForMember().
getNamespaceDef() [2/2]
virtual const NamespaceDef * MemberDef::getNamespaceDef () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getOutputFileBase() [1/2]
virtual QCString MemberDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DefinitionImpl::_writeSourceRefList(), HtmlHelp::addIndexItem(), Qhp::addIndexItem(), MemberContext::Private::callerGraph(), MemberContext::Private::callGraph(), DotCallGraph::DotCallGraph(), generateDEFForMember(), MemberDefImpl::getOutputFileBase(), MemberDefAliasImpl::getOutputFileBase(), getUniqueId(), DocParser::handleLinkedWord(), if(), memberOutputFileBase(), validatingParseDoc(), writeClassLinkForMember(), writeColumn(), MemberDefImpl::writeDeclaration(), MemberList::writeDocumentationPage(), writeFileLinkForMember(), writeLink(), ClassDefImpl::writeMemberList(), writeMemberReference(), writeMemberToIndex(), writeNamespaceLinkForMember(), ClassDefImpl::writeQuickMemberLinks(), VhdlDocGen::writeTagFile(), and VhdlDocGen::writeVHDLDeclaration().
getOutputFileBase() [2/2]
virtual QCString MemberDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getReadAccessor() [1/2]
virtual QCString MemberDef::getReadAccessor () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), and MemberDefAliasImpl::getReadAccessor().
getReadAccessor() [2/2]
virtual QCString MemberDef::getReadAccessor () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getReference() [1/2]
virtual QCString MemberDef::getReference () const [pure virtual]
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Implements Definition.
Implemented in DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DefinitionImpl::_writeSourceRefList(), MemberDefImpl::getReference(), MemberDefAliasImpl::getReference(), getUniqueId(), DocParser::handleLinkedWord(), if(), writeClassLinkForMember(), writeFileLinkForMember(), writeLink(), ClassDefImpl::writeMemberList(), writeMemberToIndex(), writeNamespaceLinkForMember(), and VhdlDocGen::writeVHDLDeclaration().
getReference() [2/2]
virtual QCString MemberDef::getReference () const [pure virtual]
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Implements Definition.
Implemented in DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, and MemberDefAliasImpl.
getScopeString() [1/2]
virtual QCString MemberDef::getScopeString () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DefinitionImpl::_writeSourceRefList(), DefinitionImpl::addSourceReferencedBy(), DefinitionImpl::addSourceReferences(), DocParser::checkArgumentName(), MemberDefAliasImpl::getScopeString(), and writeMemberReference().
getScopeString() [2/2]
virtual QCString MemberDef::getScopeString () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
getSectionList() [1/2]
virtual const MemberList * MemberDef::getSectionList (const Definition * container) const [pure virtual]
Implemented in MemberDefImpl, MemberDefImpl, MemberDefAliasImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::getSectionList(), and MemberGroup::insertMember().
getSectionList() [2/2]
virtual const MemberList * MemberDef::getSectionList (const Definition * container) const [pure virtual]
Implemented in MemberDefImpl, MemberDefImpl, MemberDefAliasImpl, and MemberDefAliasImpl.
getWriteAccessor() [1/2]
virtual QCString MemberDef::getWriteAccessor () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), and MemberDefAliasImpl::getWriteAccessor().
getWriteAccessor() [2/2]
virtual QCString MemberDef::getWriteAccessor () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
hasCallerGraph() [1/2]
virtual bool MemberDef::hasCallerGraph () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberDocs(), combineDeclarationAndDefinition(), MemberContext::Private::hasCallerGraph(), and MemberDefAliasImpl::hasCallerGraph().
hasCallerGraph() [2/2]
virtual bool MemberDef::hasCallerGraph () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
hasCallGraph() [1/2]
virtual bool MemberDef::hasCallGraph () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberDocs(), combineDeclarationAndDefinition(), MemberContext::Private::hasCallGraph(), and MemberDefAliasImpl::hasCallGraph().
hasCallGraph() [2/2]
virtual bool MemberDef::hasCallGraph () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
hasDetailedDescription() [1/2]
virtual bool MemberDef::hasDetailedDescription () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::hasDetailedDescription(), MemberContext::Private::hasDetails(), MemberList::writeDocumentationPage(), and VhdlDocGen::writeVHDLDeclaration().
hasDetailedDescription() [2/2]
virtual bool MemberDef::hasDetailedDescription () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
hasDocumentation() [1/2]
virtual bool MemberDef::hasDocumentation () const [pure virtual]
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Implements Definition.
Implemented in DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, and MemberDefAliasImpl.
Referenced by combineDeclarationAndDefinition(), MemberDefAliasImpl::hasDocumentation(), and MemberDefImpl::writeEnumDeclaration().
hasDocumentation() [2/2]
virtual bool MemberDef::hasDocumentation () const [pure virtual]
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Implements Definition.
Implemented in DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, and MemberDefAliasImpl.
hasDocumentedEnumValues() [1/2]
virtual bool MemberDef::hasDocumentedEnumValues () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::hasDocumentedEnumValues().
hasDocumentedEnumValues() [2/2]
virtual bool MemberDef::hasDocumentedEnumValues () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
hasExamples() [1/2]
virtual bool MemberDef::hasExamples () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createExamples(), and MemberDefAliasImpl::hasExamples().
hasExamples() [2/2]
virtual bool MemberDef::hasExamples () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
hasMultiLineInitializer() [1/2]
virtual bool MemberDef::hasMultiLineInitializer () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::hasMultiLineInitializer(), and MemberDefAliasImpl::hasMultiLineInitializer().
hasMultiLineInitializer() [2/2]
virtual bool MemberDef::hasMultiLineInitializer () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
hasOneLineInitializer() [1/2]
virtual bool MemberDef::hasOneLineInitializer () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::hasOneLineInitializer(), MemberDefAliasImpl::hasOneLineInitializer(), and MemberDefImpl::writeEnumDeclaration().
hasOneLineInitializer() [2/2]
virtual bool MemberDef::hasOneLineInitializer () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
hasReferencedByRelation() [1/2]
virtual bool MemberDef::hasReferencedByRelation () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberDocs(), combineDeclarationAndDefinition(), MemberContext::Private::hasReferencedByRelation(), MemberDefAliasImpl::hasReferencedByRelation(), and VhdlDocGen::writeSource().
hasReferencedByRelation() [2/2]
virtual bool MemberDef::hasReferencedByRelation () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
hasReferencesRelation() [1/2]
virtual bool MemberDef::hasReferencesRelation () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberDocs(), combineDeclarationAndDefinition(), MemberContext::Private::hasReferencesRelation(), MemberDefAliasImpl::hasReferencesRelation(), and VhdlDocGen::writeSource().
hasReferencesRelation() [2/2]
virtual bool MemberDef::hasReferencesRelation () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
inheritsDocsFrom() [1/2]
virtual const MemberDef * MemberDef::inheritsDocsFrom () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DocParser::checkArgumentName(), and MemberDefAliasImpl::inheritsDocsFrom().
inheritsDocsFrom() [2/2]
virtual const MemberDef * MemberDef::inheritsDocsFrom () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
initializer() [1/2]
virtual const QCString & MemberDef::initializer () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), addMemberDocs(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), MemberContext::Private::createInitializer(), MemberContext::Private::createInitializerAsCode(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), findMember(), findUsingDeclImports(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), MemberDefAliasImpl::initializer(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), doxmlparser.compound.enumvalueType::set_initializer(), and MemberDefImpl::writeEnumDeclaration().
initializer() [2/2]
virtual const QCString & MemberDef::initializer () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
initializerLines() [1/2]
virtual int MemberDef::initializerLines () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by findUsingDeclImports(), and MemberDefAliasImpl::initializerLines().
initializerLines() [2/2]
virtual int MemberDef::initializerLines () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isAbstract() [1/2]
virtual bool MemberDef::isAbstract () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::isAbstract(), and MemberDefAliasImpl::isAbstract().
isAbstract() [2/2]
virtual bool MemberDef::isAbstract () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isAddable() [1/2]
virtual bool MemberDef::isAddable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createEventAttrs(), generateXMLForMember(), MemberContext::Private::isAddable(), and MemberDefAliasImpl::isAddable().
isAddable() [2/2]
virtual bool MemberDef::isAddable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isAssign() [1/2]
virtual bool MemberDef::isAssign () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isAssign(), and MemberDefAliasImpl::isAssign().
isAssign() [2/2]
virtual bool MemberDef::isAssign () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isAttribute() [1/2]
virtual bool MemberDef::isAttribute () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isAttribute(), MemberDefAliasImpl::isAttribute(), and ClassDefImpl::writeMemberList().
isAttribute() [2/2]
virtual bool MemberDef::isAttribute () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isBound() [1/2]
virtual bool MemberDef::isBound () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isBound(), MemberDefAliasImpl::isBound(), and ClassDefImpl::writeMemberList().
isBound() [2/2]
virtual bool MemberDef::isBound () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isBriefSectionVisible() [1/2]
virtual bool MemberDef::isBriefSectionVisible () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::isBriefSectionVisible(), MemberDefImpl::writeEnumDeclaration(), and VhdlDocGen::writePlainVHDLDeclarations().
isBriefSectionVisible() [2/2]
virtual bool MemberDef::isBriefSectionVisible () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isConstExpr() [1/2]
virtual bool MemberDef::isConstExpr () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), and MemberDefAliasImpl::isConstExpr().
isConstExpr() [2/2]
virtual bool MemberDef::isConstExpr () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isConstrained() [1/2]
virtual bool MemberDef::isConstrained () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isConstrained(), MemberDefAliasImpl::isConstrained(), and ClassDefImpl::writeMemberList().
isConstrained() [2/2]
virtual bool MemberDef::isConstrained () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isConstructor() [1/2]
virtual bool MemberDef::isConstructor () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by genericCompareMembers(), ClassDefImpl::internalInsertMember(), MemberDefAliasImpl::isConstructor(), and isStandardFunc().
isConstructor() [2/2]
virtual bool MemberDef::isConstructor () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isCopy() [1/2]
virtual bool MemberDef::isCopy () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isCopy(), and MemberDefAliasImpl::isCopy().
isCopy() [2/2]
virtual bool MemberDef::isCopy () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isCSharpProperty() [1/2]
virtual bool MemberDef::isCSharpProperty () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by computeMemberRelations(), MemberContext::Private::isCSharpProperty(), and MemberDefAliasImpl::isCSharpProperty().
isCSharpProperty() [2/2]
virtual bool MemberDef::isCSharpProperty () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isDCOP() [1/2]
virtual bool MemberDef::isDCOP () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::isDCOP().
isDCOP() [2/2]
virtual bool MemberDef::isDCOP () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isDefault() [1/2]
virtual bool MemberDef::isDefault () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::isDefault(), and MemberDefAliasImpl::isDefault().
isDefault() [2/2]
virtual bool MemberDef::isDefault () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isDefine() [1/2]
virtual bool MemberDef::isDefine () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addFileMemberNameToIndex(), addMemberToSearchIndex(), addVariableToFile(), DocParser::checkArgumentName(), DocParser::checkUnOrMultipleDocumentedParams(), GlobalsIndexContext::Private::createMacros(), definitionToName(), findMember(), findMembersWithSpecificName(), MemberContext::Private::isDefine(), MemberDefAliasImpl::isDefine(), and writeDefArgumentList().
isDefine() [2/2]
virtual bool MemberDef::isDefine () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isDelete() [1/2]
virtual bool MemberDef::isDelete () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::isDelete(), and MemberDefAliasImpl::isDelete().
isDelete() [2/2]
virtual bool MemberDef::isDelete () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isDeleted() [1/2]
virtual bool MemberDef::isDeleted () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::isDeleted().
isDeleted() [2/2]
virtual bool MemberDef::isDeleted () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isDestructor() [1/2]
virtual bool MemberDef::isDestructor () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by genericCompareMembers(), ClassDefImpl::internalInsertMember(), MemberDefAliasImpl::isDestructor(), and isStandardFunc().
isDestructor() [2/2]
virtual bool MemberDef::isDestructor () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isDetailedSectionVisible() [1/2]
virtual bool MemberDef::isDetailedSectionVisible (MemberListContainer container) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::handleDetailsVisibleFor(), and MemberDefAliasImpl::isDetailedSectionVisible().
isDetailedSectionVisible() [2/2]
virtual bool MemberDef::isDetailedSectionVisible (MemberListContainer container) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isDictionary() [1/2]
virtual bool MemberDef::isDictionary () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addFileMemberNameToIndex(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), and MemberDefAliasImpl::isDictionary().
isDictionary() [2/2]
virtual bool MemberDef::isDictionary () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isDocsForDefinition() [1/2]
virtual bool MemberDef::isDocsForDefinition () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DocParser::checkArgumentName(), DocParser::checkUnOrMultipleDocumentedParams(), combineDeclarationAndDefinition(), MemberContext::Private::getDefArgList(), inheritDocumentation(), MemberDefAliasImpl::isDocsForDefinition(), and writeDefArgumentList().
isDocsForDefinition() [2/2]
virtual bool MemberDef::isDocsForDefinition () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isDocumentedFriendClass() [1/2]
virtual bool MemberDef::isDocumentedFriendClass () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::isDocumentedFriendClass().
isDocumentedFriendClass() [2/2]
virtual bool MemberDef::isDocumentedFriendClass () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isEnumerate() [1/2]
virtual bool MemberDef::isEnumerate () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addClassMemberNameToIndex(), addEnumValuesToEnums(), addFileMemberNameToIndex(), NestingNodeContext::Private::addMembers(), addMembersToMemberGroup(), addMemberToGroups(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), addToIndices(), addVariableToFile(), GlobalsIndexContext::Private::createEnums(), ClassMembersIndexContext::Private::createEnums(), NamespaceMembersIndexContext::Private::createEnums(), MemberContext::Private::createEnumValues(), definitionToName(), findDEV(), findEnumDocumentation(), findMember(), SymbolResolver::Private::followPath(), getCanonicalTypeForIdentifier(), getDefsOld(), SymbolResolver::Private::getResolvedType(), ClassDefImpl::internalInsertMember(), SymbolResolver::Private::isAccessibleFrom(), MemberDefAliasImpl::isEnumerate(), MemberContext::Private::isEnumeration(), SymbolResolver::Private::newResolveTypedef(), ClassDefImpl::writeMemberList(), and writeMemberToIndex().
isEnumerate() [2/2]
virtual bool MemberDef::isEnumerate () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isEnumStruct() [1/2]
virtual bool MemberDef::isEnumStruct () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::isEnumStruct(), and MemberDefAliasImpl::isEnumStruct().
isEnumStruct() [2/2]
virtual bool MemberDef::isEnumStruct () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isEnumValue() [1/2]
virtual bool MemberDef::isEnumValue () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addClassMemberNameToIndex(), addEnumValuesToEnums(), addFileMemberNameToIndex(), addMemberFunction(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), GlobalsIndexContext::Private::createEnumValues(), ClassMembersIndexContext::Private::createEnumValues(), NamespaceMembersIndexContext::Private::createEnumValues(), definitionToName(), findGlobalMember(), ClassDefImpl::internalInsertMember(), SymbolResolver::Private::isAccessibleFromWithExpScope(), MemberContext::Private::isEnumValue(), MemberDefAliasImpl::isEnumValue(), ClassDefImpl::writeMemberList(), and ClassDefImpl::writeQuickMemberLinks().
isEnumValue() [2/2]
virtual bool MemberDef::isEnumValue () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isEvent() [1/2]
virtual bool MemberDef::isEvent () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addClassMemberNameToIndex(), addMemberToSearchIndex(), MemberContext::Private::createEventAttrs(), ClassMembersIndexContext::Private::createEvents(), definitionToName(), MemberContext::Private::isEvent(), and MemberDefAliasImpl::isEvent().
isEvent() [2/2]
virtual bool MemberDef::isEvent () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isExplicit() [1/2]
virtual bool MemberDef::isExplicit () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isExplicit(), MemberDefAliasImpl::isExplicit(), and ClassDefImpl::writeMemberList().
isExplicit() [2/2]
virtual bool MemberDef::isExplicit () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isExternal() [1/2]
virtual bool MemberDef::isExternal () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addVariableToFile(), combineDeclarationAndDefinition(), MemberContext::Private::isExternal(), MemberDefAliasImpl::isExternal(), transferFunctionDocumentation(), and transferFunctionReferences().
isExternal() [2/2]
virtual bool MemberDef::isExternal () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isFinal() [1/2]
virtual bool MemberDef::isFinal () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), ClassDefImpl::internalInsertMember(), MemberContext::Private::isFinal(), and MemberDefAliasImpl::isFinal().
isFinal() [2/2]
virtual bool MemberDef::isFinal () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isForeign() [1/2]
virtual bool MemberDef::isForeign () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addClassMemberNameToIndex(), addMemberToSearchIndex(), definitionToName(), getDefsOld(), MemberContext::Private::isForeign(), MemberDefAliasImpl::isForeign(), and transferRelatedFunctionDocumentation().
isForeign() [2/2]
virtual bool MemberDef::isForeign () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isFriend() [1/2]
virtual bool MemberDef::isFriend () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addClassMemberNameToIndex(), addMemberToSearchIndex(), definitionToName(), ClassDefImpl::internalInsertMember(), MemberContext::Private::isFriend(), MemberDefAliasImpl::isFriend(), ClassDefImpl::mergeMembers(), AllMembersListContext::Private::Private(), and ClassDefImpl::writeMemberList().
isFriend() [2/2]
virtual bool MemberDef::isFriend () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isFriendClass() [1/2]
virtual bool MemberDef::isFriendClass () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), and MemberDefAliasImpl::isFriendClass().
isFriendClass() [2/2]
virtual bool MemberDef::isFriendClass () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isFriendToHide() [1/2]
virtual bool MemberDef::isFriendToHide () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::isFriendToHide().
isFriendToHide() [2/2]
virtual bool MemberDef::isFriendToHide () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isFunction() [1/2]
virtual bool MemberDef::isFunction () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DefinitionImpl::_writeSourceRefList(), addClassMemberNameToIndex(), addFileMemberNameToIndex(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), checkOverrideArg(), combineDeclarationAndDefinition(), computeMemberRelations(), GlobalsIndexContext::Private::createFunctions(), NamespaceMembersIndexContext::Private::createFunctions(), SymbolContext::Private::createScope(), definitionToName(), MemberContext::Private::functionQualifier(), functionSignature(), SymbolResolver::Private::getResolvedSymbol(), MemberContext::Private::hasCallerGraph(), MemberContext::Private::hasCallGraph(), GroupDefImpl::insertMember(), ClassDefImpl::internalInsertMember(), MemberContext::Private::isFunction(), MemberDefAliasImpl::isFunction(), lookupSymbol(), transferFunctionReferences(), validatingParseDoc(), writeJavaScriptSearchIndex(), and ClassDefImpl::writeMemberList().
isFunction() [2/2]
virtual bool MemberDef::isFunction () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isFunctionOrSignalSlot() [1/2]
virtual bool MemberDef::isFunctionOrSignalSlot () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by ClassMembersIndexContext::Private::createFunctions(), and MemberDefAliasImpl::isFunctionOrSignalSlot().
isFunctionOrSignalSlot() [2/2]
virtual bool MemberDef::isFunctionOrSignalSlot () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isFunctionPtr() [1/2]
virtual bool MemberDef::isFunctionPtr () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by ClassDefImpl::internalInsertMember(), MemberContext::Private::isFunctionPtr(), and MemberDefAliasImpl::isFunctionPtr().
isFunctionPtr() [2/2]
virtual bool MemberDef::isFunctionPtr () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isGettable() [1/2]
virtual bool MemberDef::isGettable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createPropertyAttrs(), generateXMLForMember(), MemberContext::Private::isGettable(), and MemberDefAliasImpl::isGettable().
isGettable() [2/2]
virtual bool MemberDef::isGettable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isImplementation() [1/2]
virtual bool MemberDef::isImplementation () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::isImplementation(), and MemberDefAliasImpl::isImplementation().
isImplementation() [2/2]
virtual bool MemberDef::isImplementation () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isInitonly() [1/2]
virtual bool MemberDef::isInitonly () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isInitonly(), and MemberDefAliasImpl::isInitonly().
isInitonly() [2/2]
virtual bool MemberDef::isInitonly () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isInline() [1/2]
virtual bool MemberDef::isInline () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isInline(), MemberDefAliasImpl::isInline(), and ClassDefImpl::writeMemberList().
isInline() [2/2]
virtual bool MemberDef::isInline () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isLinkable() [1/2]
virtual bool MemberDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DefinitionImpl::_writeSourceRefList(), DocSets::addIndexItem(), addMemberToSearchIndex(), findMembersWithSpecificName(), generateClassOrGlobalLink(), generateFuncLink(), generateMemLink(), getDefsOld(), getLink(), getLinkInScope(), DocParser::handleLinkedWord(), if(), MemberDefImpl::isLinkable(), MemberDefAliasImpl::isLinkable(), AllMembersListContext::Private::Private(), ClassDefImpl::writeMemberList(), writeObjCMethodCall(), ClassDefImpl::writeQuickMemberLinks(), VhdlDocGen::writeStringLink(), and VhdlDocGen::writeVHDLTypeDocumentation().
isLinkable() [2/2]
virtual bool MemberDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isLinkableInProject() [1/2]
virtual bool MemberDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefImpl::_computeLinkableInProject(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), addClassMemberNameToIndex(), addFileMemberNameToIndex(), addNamespaceMemberNameToIndex(), addSourceReferences(), addToIndices(), findDEV(), if(), MemberDefAliasImpl::isLinkableInProject(), and ClassDefImpl::writeQuickMemberLinks().
isLinkableInProject() [2/2]
virtual bool MemberDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isMaybeAmbiguous() [1/2]
virtual bool MemberDef::isMaybeAmbiguous () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isMaybeAmbiguous(), MemberDefAliasImpl::isMaybeAmbiguous(), and ClassDefImpl::writeMemberList().
isMaybeAmbiguous() [2/2]
virtual bool MemberDef::isMaybeAmbiguous () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isMaybeDefault() [1/2]
virtual bool MemberDef::isMaybeDefault () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isMaybeDefault(), MemberDefAliasImpl::isMaybeDefault(), and ClassDefImpl::writeMemberList().
isMaybeDefault() [2/2]
virtual bool MemberDef::isMaybeDefault () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isMaybeVoid() [1/2]
virtual bool MemberDef::isMaybeVoid () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isMaybeVoid(), MemberDefAliasImpl::isMaybeVoid(), and ClassDefImpl::writeMemberList().
isMaybeVoid() [2/2]
virtual bool MemberDef::isMaybeVoid () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isMutable() [1/2]
virtual bool MemberDef::isMutable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isMutable(), MemberDefAliasImpl::isMutable(), and ClassDefImpl::writeMemberList().
isMutable() [2/2]
virtual bool MemberDef::isMutable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isNew() [1/2]
virtual bool MemberDef::isNew () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isNew(), and MemberDefAliasImpl::isNew().
isNew() [2/2]
virtual bool MemberDef::isNew () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isNoExcept() [1/2]
virtual bool MemberDef::isNoExcept () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isNoExcept(), and MemberDefAliasImpl::isNoExcept().
isNoExcept() [2/2]
virtual bool MemberDef::isNoExcept () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isNonAtomic() [1/2]
virtual bool MemberDef::isNonAtomic () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::isNonAtomic(), and MemberDefAliasImpl::isNonAtomic().
isNonAtomic() [2/2]
virtual bool MemberDef::isNonAtomic () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isNotFriend() [1/2]
virtual bool MemberDef::isNotFriend () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by ClassMembersIndexContext::Private::createAll(), and MemberDefAliasImpl::isNotFriend().
isNotFriend() [2/2]
virtual bool MemberDef::isNotFriend () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isObjCMethod() [1/2]
virtual bool MemberDef::isObjCMethod () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DefinitionImpl::_writeSourceRefList(), DocSets::addIndexItem(), DocRef::DocRef(), MemberContext::Private::functionQualifier(), DocParser::handleLinkedWord(), MemberContext::Private::isObjCMethod(), MemberDefAliasImpl::isObjCMethod(), writeDefArgumentList(), and ClassDefImpl::writeMemberList().
isObjCMethod() [2/2]
virtual bool MemberDef::isObjCMethod () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isObjCProperty() [1/2]
virtual bool MemberDef::isObjCProperty () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DocSets::addIndexItem(), findUsedClassesForClass(), MemberContext::Private::isObjCProperty(), and MemberDefAliasImpl::isObjCProperty().
isObjCProperty() [2/2]
virtual bool MemberDef::isObjCProperty () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isOptional() [1/2]
virtual bool MemberDef::isOptional () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isOptional(), MemberDefAliasImpl::isOptional(), and ClassDefImpl::writeMemberList().
isOptional() [2/2]
virtual bool MemberDef::isOptional () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isOverride() [1/2]
virtual bool MemberDef::isOverride () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by ClassDefImpl::internalInsertMember(), MemberContext::Private::isOverride(), and MemberDefAliasImpl::isOverride().
isOverride() [2/2]
virtual bool MemberDef::isOverride () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isPrivateGettable() [1/2]
virtual bool MemberDef::isPrivateGettable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createPropertyAttrs(), generateXMLForMember(), MemberContext::Private::isPrivateGettable(), and MemberDefAliasImpl::isPrivateGettable().
isPrivateGettable() [2/2]
virtual bool MemberDef::isPrivateGettable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isPrivateSettable() [1/2]
virtual bool MemberDef::isPrivateSettable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createPropertyAttrs(), generateXMLForMember(), MemberContext::Private::isPrivateSettable(), and MemberDefAliasImpl::isPrivateSettable().
isPrivateSettable() [2/2]
virtual bool MemberDef::isPrivateSettable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isProperty() [1/2]
virtual bool MemberDef::isProperty () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addClassMemberNameToIndex(), addMemberToSearchIndex(), MemberContext::Private::createParameters(), ClassMembersIndexContext::Private::createProperties(), MemberContext::Private::createPropertyAttrs(), definitionToName(), MemberContext::Private::isProperty(), MemberDefAliasImpl::isProperty(), and writeDefArgumentList().
isProperty() [2/2]
virtual bool MemberDef::isProperty () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isProtectedGettable() [1/2]
virtual bool MemberDef::isProtectedGettable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createPropertyAttrs(), generateXMLForMember(), MemberContext::Private::isProtectedGettable(), and MemberDefAliasImpl::isProtectedGettable().
isProtectedGettable() [2/2]
virtual bool MemberDef::isProtectedGettable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isProtectedSettable() [1/2]
virtual bool MemberDef::isProtectedSettable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createPropertyAttrs(), generateXMLForMember(), MemberContext::Private::isProtectedSettable(), and MemberDefAliasImpl::isProtectedSettable().
isProtectedSettable() [2/2]
virtual bool MemberDef::isProtectedSettable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isPrototype() [1/2]
virtual bool MemberDef::isPrototype () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DefinitionImpl::_writeSourceRefList(), combineDeclarationAndDefinition(), MemberContext::Private::functionQualifier(), MemberDefAliasImpl::isPrototype(), lookupSymbol(), transferFunctionDocumentation(), and transferFunctionReferences().
isPrototype() [2/2]
virtual bool MemberDef::isPrototype () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isPublished() [1/2]
virtual bool MemberDef::isPublished () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::isPublished(), and MemberDefAliasImpl::isPublished().
isPublished() [2/2]
virtual bool MemberDef::isPublished () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isRaisable() [1/2]
virtual bool MemberDef::isRaisable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createEventAttrs(), generateXMLForMember(), MemberContext::Private::isRaisable(), and MemberDefAliasImpl::isRaisable().
isRaisable() [2/2]
virtual bool MemberDef::isRaisable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isReadable() [1/2]
virtual bool MemberDef::isReadable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isReadable(), MemberDefAliasImpl::isReadable(), and MemberDefAliasImpl::isReadonly().
isReadable() [2/2]
virtual bool MemberDef::isReadable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isReadonly() [1/2]
virtual bool MemberDef::isReadonly () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isReadonly(), and ClassDefImpl::writeMemberList().
isReadonly() [2/2]
virtual bool MemberDef::isReadonly () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isReference() [1/2]
virtual bool MemberDef::isReference () const [pure virtual]
Returns TRUE if this definition is imported via a tag file.
Implements Definition.
Implemented in DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, and MemberDefAliasImpl.
Referenced by findMembersWithSpecificName(), SymbolResolver::Private::getResolvedType(), MemberDefImpl::isReference(), MemberDefAliasImpl::isReference(), and MemberList::setAnchors().
isReference() [2/2]
virtual bool MemberDef::isReference () const [pure virtual]
Returns TRUE if this definition is imported via a tag file.
Implements Definition.
Implemented in DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, and MemberDefAliasImpl.
isReimplementedBy() [1/2]
virtual bool MemberDef::isReimplementedBy (const ClassDef * cd) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::isReimplementedBy().
isReimplementedBy() [2/2]
virtual bool MemberDef::isReimplementedBy (const ClassDef * cd) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isRelated() [1/2]
virtual bool MemberDef::isRelated () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addClassMemberNameToIndex(), addMemberToSearchIndex(), ClassMembersIndexContext::Private::createRelated(), MemberContext::Private::createTemplateDecls(), definitionToName(), getDefsOld(), MemberContext::Private::handleNameWithContextFor(), ClassDefImpl::internalInsertMember(), MemberContext::Private::isRelated(), MemberDefAliasImpl::isRelated(), transferRelatedFunctionDocumentation(), and ClassDefImpl::writeMemberList().
isRelated() [2/2]
virtual bool MemberDef::isRelated () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isRelatedOrFriend() [1/2]
virtual bool MemberDef::isRelatedOrFriend () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::isRelatedOrFriend().
isRelatedOrFriend() [2/2]
virtual bool MemberDef::isRelatedOrFriend () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isRemovable() [1/2]
virtual bool MemberDef::isRemovable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createEventAttrs(), generateXMLForMember(), MemberContext::Private::isRemovable(), MemberDefAliasImpl::isRemovable(), and ClassDefImpl::writeMemberList().
isRemovable() [2/2]
virtual bool MemberDef::isRemovable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isRequired() [1/2]
virtual bool MemberDef::isRequired () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isRequired(), and MemberDefAliasImpl::isRequired().
isRequired() [2/2]
virtual bool MemberDef::isRequired () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isRetain() [1/2]
virtual bool MemberDef::isRetain () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isRetain(), and MemberDefAliasImpl::isRetain().
isRetain() [2/2]
virtual bool MemberDef::isRetain () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isSealed() [1/2]
virtual bool MemberDef::isSealed () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isSealed(), and MemberDefAliasImpl::isSealed().
isSealed() [2/2]
virtual bool MemberDef::isSealed () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isSequence() [1/2]
virtual bool MemberDef::isSequence () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addFileMemberNameToIndex(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), and MemberDefAliasImpl::isSequence().
isSequence() [2/2]
virtual bool MemberDef::isSequence () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isSettable() [1/2]
virtual bool MemberDef::isSettable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createPropertyAttrs(), generateXMLForMember(), MemberContext::Private::isSettable(), and MemberDefAliasImpl::isSettable().
isSettable() [2/2]
virtual bool MemberDef::isSettable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isSignal() [1/2]
virtual bool MemberDef::isSignal () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DefinitionImpl::_writeSourceRefList(), addClassMemberNameToIndex(), addMemberToSearchIndex(), SymbolContext::Private::createScope(), definitionToName(), MemberContext::Private::functionQualifier(), MemberContext::Private::hasCallerGraph(), MemberContext::Private::hasCallGraph(), MemberContext::Private::isSignal(), MemberDefAliasImpl::isSignal(), and ClassDefImpl::writeMemberList().
isSignal() [2/2]
virtual bool MemberDef::isSignal () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isSliceLocal() [1/2]
virtual bool MemberDef::isSliceLocal () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::isSliceLocal().
isSliceLocal() [2/2]
virtual bool MemberDef::isSliceLocal () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isSlot() [1/2]
virtual bool MemberDef::isSlot () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DefinitionImpl::_writeSourceRefList(), addClassMemberNameToIndex(), addMemberToSearchIndex(), SymbolContext::Private::createScope(), definitionToName(), MemberContext::Private::functionQualifier(), MemberContext::Private::hasCallerGraph(), MemberContext::Private::hasCallGraph(), MemberContext::Private::isSlot(), MemberDefAliasImpl::isSlot(), writeJavaScriptSearchIndex(), and ClassDefImpl::writeMemberList().
isSlot() [2/2]
virtual bool MemberDef::isSlot () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isStatic() [1/2]
virtual bool MemberDef::isStatic () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DocSets::addIndexItem(), addMemberFunction(), addVariableToFile(), combineDeclarationAndDefinition(), findGlobalMember(), findMembersWithSpecificName(), findUsingDeclImports(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), ignoreStaticExternalCall(), ClassDefImpl::internalInsertMember(), MemberContext::Private::isStatic(), MemberDefAliasImpl::isStatic(), transferFunctionReferences(), and ClassDefImpl::writeMemberList().
isStatic() [2/2]
virtual bool MemberDef::isStatic () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isStrong() [1/2]
virtual bool MemberDef::isStrong () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addClassMemberNameToIndex(), addFileMemberNameToIndex(), NestingNodeContext::Private::addMembers(), addMemberToGroups(), addNamespaceMemberNameToIndex(), findMember(), generateXMLForMember(), getDefsOld(), MemberContext::Private::isStrong(), MemberDefAliasImpl::isStrong(), MemberDefImpl::isStrongEnumValue(), MemberDefImpl::qualifiedName(), and MemberList::writeTagFile().
isStrong() [2/2]
virtual bool MemberDef::isStrong () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isStrongEnumValue() [1/2]
virtual bool MemberDef::isStrongEnumValue () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addEnumValuesToEnums(), getDefsOld(), SymbolResolver::Private::isAccessibleFrom(), MemberDefAliasImpl::isStrongEnumValue(), and resolveRef().
isStrongEnumValue() [2/2]
virtual bool MemberDef::isStrongEnumValue () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isTemplateSpecialization() [1/2]
virtual bool MemberDef::isTemplateSpecialization () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createTemplateDecls(), MemberContext::Private::isTemplateSpecialization(), and MemberDefAliasImpl::isTemplateSpecialization().
isTemplateSpecialization() [2/2]
virtual bool MemberDef::isTemplateSpecialization () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isTransient() [1/2]
virtual bool MemberDef::isTransient () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isTransient(), MemberDefAliasImpl::isTransient(), and ClassDefImpl::writeMemberList().
isTransient() [2/2]
virtual bool MemberDef::isTransient () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isTypeAlias() [1/2]
virtual bool MemberDef::isTypeAlias () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createTemplateAlias(), MemberContext::Private::isTypeAlias(), and MemberDefAliasImpl::isTypeAlias().
isTypeAlias() [2/2]
virtual bool MemberDef::isTypeAlias () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isTypedef() [1/2]
virtual bool MemberDef::isTypedef () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addClassMemberNameToIndex(), addFileMemberNameToIndex(), addMemberFunction(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), checkIfTypedef(), GlobalsIndexContext::Private::createTypedefs(), ClassMembersIndexContext::Private::createTypedefs(), NamespaceMembersIndexContext::Private::createTypedefs(), definitionToName(), findGlobalMember(), getCanonicalTypeForIdentifier(), SymbolResolver::Private::getResolvedType(), ClassDefImpl::internalInsertMember(), MemberContext::Private::isTypedef(), MemberDefAliasImpl::isTypedef(), SymbolResolver::Private::newResolveTypedef(), resolveTypeDef(), SymbolResolver::Private::substTypedef(), writeDefArgumentList(), and ClassDefImpl::writeMemberList().
isTypedef() [2/2]
virtual bool MemberDef::isTypedef () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isTypedefValCached() [1/2]
virtual bool MemberDef::isTypedefValCached () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by flushCachedTemplateRelations(), MemberDefAliasImpl::isTypedefValCached(), and SymbolResolver::Private::newResolveTypedef().
isTypedefValCached() [2/2]
virtual bool MemberDef::isTypedefValCached () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isUNOProperty() [1/2]
virtual bool MemberDef::isUNOProperty () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isUNOProperty(), MemberDefAliasImpl::isUNOProperty(), and ClassDefImpl::writeMemberList().
isUNOProperty() [2/2]
virtual bool MemberDef::isUNOProperty () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isUnretained() [1/2]
virtual bool MemberDef::isUnretained () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::isUnretained(), and MemberDefAliasImpl::isUnretained().
isUnretained() [2/2]
virtual bool MemberDef::isUnretained () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isVariable() [1/2]
virtual bool MemberDef::isVariable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addClassMemberNameToIndex(), addFileMemberNameToIndex(), addMemberFunction(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), combineDeclarationAndDefinition(), GlobalsIndexContext::Private::createVariables(), ClassMembersIndexContext::Private::createVariables(), NamespaceMembersIndexContext::Private::createVariables(), definitionToName(), findGlobalMember(), findUsedClassesForClass(), getLink(), getLinkInScope(), if(), ClassDefImpl::internalInsertMember(), MemberContext::Private::isVariable(), MemberDefAliasImpl::isVariable(), transferFunctionDocumentation(), transferFunctionReferences(), and VhdlDocGen::writeVHDLTypeDocumentation().
isVariable() [2/2]
virtual bool MemberDef::isVariable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isWeak() [1/2]
virtual bool MemberDef::isWeak () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isWeak(), and MemberDefAliasImpl::isWeak().
isWeak() [2/2]
virtual bool MemberDef::isWeak () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
isWritable() [1/2]
virtual bool MemberDef::isWritable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by generateXMLForMember(), MemberContext::Private::isWritable(), and MemberDefAliasImpl::isWritable().
isWritable() [2/2]
virtual bool MemberDef::isWritable () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
livesInsideEnum() [1/2]
virtual bool MemberDef::livesInsideEnum () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::handleNameWithContextFor(), and MemberDefAliasImpl::livesInsideEnum().
livesInsideEnum() [2/2]
virtual bool MemberDef::livesInsideEnum () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
memberDeclaration() [1/2]
virtual MemberDef * MemberDef::memberDeclaration () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::memberDeclaration().
memberDeclaration() [2/2]
virtual MemberDef * MemberDef::memberDeclaration () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
memberDefinition() [1/2]
virtual MemberDef * MemberDef::memberDefinition () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by getUniqueId(), and MemberDefAliasImpl::memberDefinition().
memberDefinition() [2/2]
virtual MemberDef * MemberDef::memberDefinition () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
memberType() [1/2]
virtual MemberType MemberDef::memberType () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DocSets::addIndexItem(), MemberList::addListReferences(), addVariableToClass(), findDefineDocumentation(), findUsingDeclImports(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), GroupDefImpl::insertMember(), FileDefImpl::insertMember(), NamespaceDefImpl::insertMember(), ClassDefImpl::internalInsertMember(), MemberDefAliasImpl::memberType(), GroupDefImpl::removeMember(), and MemberList::writeTagFile().
memberType() [2/2]
virtual MemberType MemberDef::memberType () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
memberTypeName() [1/2]
virtual QCString MemberDef::memberTypeName () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by lookupSymbol(), MemberDefAliasImpl::memberTypeName(), and referenceTo().
memberTypeName() [2/2]
virtual QCString MemberDef::memberTypeName () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
moveTo() [1/2]
virtual void MemberDef::moveTo (Definition *) [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by ClassDefImpl::mergeCategory().
moveTo() [2/2]
virtual void MemberDef::moveTo (Definition *) [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
numberOfFlowKeyWords() [1/2]
virtual int MemberDef::numberOfFlowKeyWords () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::numberOfFlowKeyWords(), and printNumberOfConditionalPaths().
numberOfFlowKeyWords() [2/2]
virtual int MemberDef::numberOfFlowKeyWords () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
objCMethodName() [1/2]
virtual QCString MemberDef::objCMethodName (bool localLink, bool showStatic) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by DocRef::DocRef(), DocParser::handleLinkedWord(), and MemberDefAliasImpl::objCMethodName().
objCMethodName() [2/2]
virtual QCString MemberDef::objCMethodName (bool localLink, bool showStatic) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
protection() [1/2]
virtual Protection MemberDef::protection () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberFunction(), addMemberSpecialization(), findUsedClassesForClass(), findUsingDeclImports(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), GroupDefImpl::insertMember(), ClassDefImpl::insertMember(), ClassDefImpl::internalInsertMember(), lookupSymbol(), ClassDefImpl::mergeMembers(), AllMembersListContext::Private::Private(), MemberDefAliasImpl::protection(), GroupDefImpl::removeMember(), and ClassDefImpl::writeMemberList().
protection() [2/2]
virtual Protection MemberDef::protection () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
qualifiedName() [1/2]
virtual QCString MemberDef::qualifiedName () const [pure virtual]
Returns the fully qualified name of this definition
Implements Definition.
Implemented in DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addEnumValuesToEnums(), addToIndices(), DocParser::checkRetvalName(), DocParser::checkUnOrMultipleDocumentedParams(), DotCallGraph::DotCallGraph(), generateXMLForMember(), getCanonicalTypeForIdentifier(), getLinkInScope(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedType(), NestingNodeContext::Private::name(), SymbolResolver::Private::newResolveTypedef(), MemberDefImpl::qualifiedName(), MemberDefAliasImpl::qualifiedName(), MemberList::writeDocumentationPage(), and VhdlDocGen::writeVHDLDeclaration().
qualifiedName() [2/2]
virtual QCString MemberDef::qualifiedName () const [pure virtual]
Returns the fully qualified name of this definition
Implements Definition.
Implemented in DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< MemberDefMutable >, DefinitionAliasMixin< MemberDef >, MemberDefImpl, and MemberDefAliasImpl.
reimplementedBy() [1/2]
virtual const MemberVector & MemberDef::reimplementedBy () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createImplementedBy(), MemberContext::Private::createReimplementedBy(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), and MemberDefAliasImpl::reimplementedBy().
reimplementedBy() [2/2]
virtual const MemberVector & MemberDef::reimplementedBy () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
reimplements() [1/2]
virtual const MemberDef * MemberDef::reimplements () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::add_reimplements(), doxmlparser.compound.memberdefType::buildChildren(), computeMemberRelations(), MemberContext::Private::createImplements(), MemberContext::Private::createReimplements(), doxmlparser.compound.memberdefType::exportChildren(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), doxmlparser.compound.memberdefType::get_reimplements(), DocPara::handleInheritDoc(), doxmlparser.compound.memberdefType::hasContent_(), inheritDocumentation(), doxmlparser.compound.memberdefType::insert_reimplements_at(), MemberDefAliasImpl::reimplements(), doxmlparser.compound.memberdefType::replace_reimplements_at(), doxmlparser.compound.memberdefType::set_reimplements(), and MemberDefImpl::virtualness().
reimplements() [2/2]
virtual const MemberDef * MemberDef::reimplements () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::add_reimplements(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_reimplements(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.memberdefType::insert_reimplements_at(), doxmlparser.compound.memberdefType::replace_reimplements_at(), and doxmlparser.compound.memberdefType::set_reimplements().
relatedAlso() [1/2]
virtual ClassDef * MemberDef::relatedAlso () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::relatedAlso(), and transferRelatedFunctionDocumentation().
relatedAlso() [2/2]
virtual ClassDef * MemberDef::relatedAlso () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
requiresClause() [1/2]
virtual QCString MemberDef::requiresClause () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberDocs(), findGlobalMember(), findUsingDeclImports(), generateXMLForMember(), and MemberDefAliasImpl::requiresClause().
requiresClause() [2/2]
virtual QCString MemberDef::requiresClause () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
resolveAlias() [1/4]
virtual const MemberDef * MemberDef::resolveAlias () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
resolveAlias() [2/4]
virtual const MemberDef * MemberDef::resolveAlias () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
resolveAlias() [3/4]
virtual MemberDef * MemberDef::resolveAlias () [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by SymbolContext::Private::createScope(), findGlobalMember(), getDefsOld(), getLinkInScope(), and writeJavaScriptSearchIndex().
resolveAlias() [4/4]
virtual MemberDef * MemberDef::resolveAlias () [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
setMemberGroup() [1/2]
virtual void MemberDef::setMemberGroup (MemberGroup * grp) [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMembersToMemberGroup().
setMemberGroup() [2/2]
virtual void MemberDef::setMemberGroup (MemberGroup * grp) [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
showInCallGraph() [1/2]
virtual bool MemberDef::showInCallGraph () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::showInCallGraph().
showInCallGraph() [2/2]
virtual bool MemberDef::showInCallGraph () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
templateArguments() [1/2]
virtual const ArgumentList & MemberDef::templateArguments () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addMemberFunction(), combineDeclarationAndDefinition(), MemberContext::Private::createTemplateArgs(), MemberContext::Private::createTemplateDecls(), findGlobalMember(), findUsingDeclImports(), GroupDefImpl::insertMember(), MemberDefAliasImpl::templateArguments(), and writeMemberTemplateLists().
templateArguments() [2/2]
virtual const ArgumentList & MemberDef::templateArguments () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
templateMaster() [1/2]
virtual const MemberDef * MemberDef::templateMaster () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::templateMaster().
templateMaster() [2/2]
virtual const MemberDef * MemberDef::templateMaster () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
typeConstraints() [1/2]
virtual const ArgumentList & MemberDef::typeConstraints () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberContext::Private::createTypeConstraints(), and MemberDefAliasImpl::typeConstraints().
typeConstraints() [2/2]
virtual const ArgumentList & MemberDef::typeConstraints () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
typeString() [1/2]
virtual QCString MemberDef::typeString () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by addClassMemberNameToIndex(), addMemberFunction(), addMemberToSearchIndex(), addVariableToClass(), VhdlDocGen::correctMemberProperties(), MemberContext::Private::createTemplateAlias(), findGlobalMember(), findUsedClassesForClass(), findUsingDeclImports(), generateClassMemberLink(), generateClassOrGlobalLink(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), getCanonicalTypeForIdentifier(), getLinkInScope(), ClassDefImpl::internalInsertMember(), SymbolResolver::Private::newResolveTypedef(), resolveTypeDef(), setCallContextForVar(), SymbolResolver::Private::substTypedef(), MemberContext::Private::type(), MemberDefAliasImpl::typeString(), updateCallContextForSmartPointer(), writeColumn(), ClassDefImpl::writeMemberList(), writeObjCMethodCall(), VhdlDocGen::writeTagFile(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVHDLTypeDocumentation().
typeString() [2/2]
virtual QCString MemberDef::typeString () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
virtualness() [1/2]
virtual Specifier MemberDef::virtualness (int count = 0) const [pure virtual]
Implemented in MemberDefAliasImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefImpl.
Referenced by MemberDefImpl::_writeReimplements(), PerlModGenerator::addListOfAllMembers(), addMemberFunction(), computeMemberRelations(), MemberContext::Private::createImplements(), MemberContext::Private::createReimplements(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), GroupDefImpl::insertMember(), ClassDefImpl::internalInsertMember(), MemberDefAliasImpl::virtualness(), MemberDefImpl::virtualness(), writeListOfAllMembers(), and ClassDefImpl::writeMemberList().
virtualness() [2/2]
virtual Specifier MemberDef::virtualness (int count = 0) const [pure virtual]
Implemented in MemberDefAliasImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefImpl.
visibleInIndex() [1/2]
virtual bool MemberDef::visibleInIndex () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::visibleInIndex().
visibleInIndex() [2/2]
virtual bool MemberDef::visibleInIndex () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
warnIfUndocumented() [1/2]
virtual void MemberDef::warnIfUndocumented () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by VhdlDocGen::writeVHDLDeclaration().
warnIfUndocumented() [2/2]
virtual void MemberDef::warnIfUndocumented () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
warnIfUndocumentedParams() [1/2]
virtual void MemberDef::warnIfUndocumentedParams () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
warnIfUndocumentedParams() [2/2]
virtual void MemberDef::warnIfUndocumentedParams () const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
writeDeclaration() [1/2]
virtual void MemberDef::writeDeclaration (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool inGroup, int indentLevel = 0, const ClassDef * inheritFrom = 0, const QCString & inheritId = QCString()) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefAliasImpl::writeDeclaration().
writeDeclaration() [2/2]
virtual void MemberDef::writeDeclaration (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool inGroup, int indentLevel = 0, const ClassDef * inheritFrom = 0, const QCString & inheritId = QCString()) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
writeEnumDeclaration() [1/2]
virtual void MemberDef::writeEnumDeclaration (OutputList & typeDecl, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
Referenced by MemberDefImpl::writeDeclaration(), and MemberDefAliasImpl::writeEnumDeclaration().
writeEnumDeclaration() [2/2]
virtual void MemberDef::writeEnumDeclaration (OutputList & typeDecl, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd) const [pure virtual]
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, and MemberDefAliasImpl.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/memberdef.h
doxygen/src/memberdef.h