LexOutlineParser Class Reference
Lex language parser using state-based lexical scanning.
#include <lexscanner.h>
Classes
struct Private
Public Member Functions
LexOutlineParser ()
~LexOutlineParser ()
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)
bool needsPreprocessing (const QCString &extension) const
void parsePrototype (const QCString &text)
LexOutlineParser ()
~LexOutlineParser ()
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)
bool needsPreprocessing (const QCString &extension) const
void parsePrototype (const QCString &text)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Lex language parser using state-based lexical scanning.
This is the Lex language parser for doxygen.
Definition at line 27 of file lexscanner.h.
Constructor & Destructor Documentation
LexOutlineParser() [1/2]
LexOutlineParser::LexOutlineParser ()
Definition at line 1006 of file lexscanner.l.
                                   : p(std::make_unique<LexOutlineParser::Private>())
{
  lexscannerYYlex_init_extra(&p->state,&p->yyscanner);
#ifdef FLEX_DEBUG
  lexscannerYYset_debug(1,p->yyscanner);
#endif
}
References p.
 LexOutlineParser() [1/2]
LexOutlineParser::~LexOutlineParser ()
Definition at line 1014 of file lexscanner.l.
{
  lexscannerYYlex_destroy(p->yyscanner);
}
References p.
LexOutlineParser() [2/2]
LexOutlineParser::LexOutlineParser ()
 LexOutlineParser() [2/2]
LexOutlineParser::~LexOutlineParser ()
Member Function Documentation
needsPreprocessing() [1/2]
bool LexOutlineParser::needsPreprocessing (const QCString & extension) const [inline], [virtual]
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 36 of file lexscanner.h.
{ return TRUE; };
References TRUE.
needsPreprocessing() [2/2]
bool LexOutlineParser::needsPreprocessing (const QCString & extension) const [inline], [virtual]
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 36 of file lexscanner.h.
{ return TRUE; };
References TRUE.
parseInput() [1/2]
void LexOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) [virtual]
Parses a single input file with the goal to build an Entry tree.
Parameters
 in fileName The full name of the file.
 in fileBuf The contents of the file (zero terminated).
 in,out root The root of the tree of Entry *nodes representing the information extracted from the file.
 in clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
Definition at line 1019 of file lexscanner.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->fileName = fileName;
  printlex(yy_flex_debug, TRUE, __FILE__, qPrint(fileName));
  ::parseMain(p->yyscanner,fileName,fileBuf,root,clangParser);
  printlex(yy_flex_debug, FALSE, __FILE__, qPrint(fileName));
}
References FALSE, p, parseMain(), printlex(), qPrint(), and TRUE.
parseInput() [2/2]
void LexOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) [virtual]
Parses a single input file with the goal to build an Entry tree.
Parameters
 in fileName The full name of the file.
 in fileBuf The contents of the file (zero terminated).
 in,out root The root of the tree of Entry *nodes representing the information extracted from the file.
 in clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
parsePrototype() [1/2]
void LexOutlineParser::parsePrototype (const QCString & text) [inline], [virtual]
Callback function called by the comment block scanner. It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Definition at line 37 of file lexscanner.h.
{}
parsePrototype() [2/2]
void LexOutlineParser::parsePrototype (const QCString & text) [inline], [virtual]
Callback function called by the comment block scanner. It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Definition at line 37 of file lexscanner.h.
{}
Member Data Documentation
p
std::unique_ptr< Private > LexOutlineParser::p [private]
Definition at line 41 of file lexscanner.h.
Referenced by LexOutlineParser(), parseInput(), and ~LexOutlineParser().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/lexscanner.h
doxygen/src/lexscanner.h
doxygen/build/doxygen/src/lexscanner.l
doxygen/src/lexscanner.l