HelpLabel Class Reference
#include <helplabel.h>
Signals
void enter ()
void reset ()
void enter ()
void reset ()
Public Member Functions
HelpLabel (const QString &text)
HelpLabel (const QString &text)
Protected Member Functions
void enterEvent (QEnterEvent *event)
void enterEvent (QEnterEvent *event)
Private Slots
void showMenu (const QPoint &p)
void showMenu (const QPoint &p)
Detailed Description
Definition at line 19 of file helplabel.h.
Constructor & Destructor Documentation
HelpLabel() [1/2]
HelpLabel::HelpLabel (const QString & text) [inline]
Definition at line 23 of file helplabel.h.
                                   : QLabel(text)
    { setContextMenuPolicy(Qt::CustomContextMenu);
      connect(this,SIGNAL(customContextMenuRequested(const QPoint&)),
              this,SLOT(showMenu(const QPoint&)));
    }
References showMenu().
HelpLabel() [2/2]
HelpLabel::HelpLabel (const QString & text) [inline]
Definition at line 23 of file helplabel.h.
                                   : QLabel(text)
    { setContextMenuPolicy(Qt::CustomContextMenu);
      connect(this,SIGNAL(customContextMenuRequested(const QPoint&)),
              this,SLOT(showMenu(const QPoint&)));
    }
References showMenu().
Member Function Documentation
enter [1/2]
void HelpLabel::enter () [signal]
Referenced by enterEvent().
enter [2/2]
void HelpLabel::enter () [signal]
enterEvent() [1/2]
void HelpLabel::enterEvent (QEnterEvent * event) [inline], [protected]
Definition at line 42 of file helplabel.h.
      { enter(); QLabel::enterEvent(event); }
References enter().
enterEvent() [2/2]
void HelpLabel::enterEvent (QEnterEvent * event) [inline], [protected]
Definition at line 42 of file helplabel.h.
      { enter(); QLabel::enterEvent(event); }
References enter().
reset [1/2]
void HelpLabel::reset () [signal]
Referenced by showMenu().
reset [2/2]
void HelpLabel::reset () [signal]
showMenu [1/2]
void HelpLabel::showMenu (const QPoint & p) [inline], [private], [slot]
Definition at line 32 of file helplabel.h.
    {
      QMenu menu(this);
      QAction *a = menu.addAction(tr("Reset to default"));
      if (menu.exec(mapToGlobal(p))==a)
      {
        reset();
      }
    }
References a, p, and reset().
Referenced by HelpLabel().
showMenu [2/2]
void HelpLabel::showMenu (const QPoint & p) [inline], [private], [slot]
Definition at line 32 of file helplabel.h.
    {
      QMenu menu(this);
      QAction *a = menu.addAction(tr("Reset to default"));
      if (menu.exec(mapToGlobal(p))==a)
      {
        reset();
      }
    }
References a, p, and reset().
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/helplabel.h
doxygen/build/doxygen/addon/doxywizard/helplabel.h