MemberLists Class Reference
#include <memberlist.h>
Public Member Functions
MemberLists ()=default
const std::unique_ptr< MemberList > & get (MemberListType lt, MemberListContainer con)
MemberLists ()=default
const std::unique_ptr< MemberList > & get (MemberListType lt, MemberListContainer con)
Private Member Functions
MemberLists (const MemberLists &)=delete
MemberLists & operator= (const MemberLists &)=delete
MemberLists (const MemberLists &)=delete
MemberLists & operator= (const MemberLists &)=delete
Detailed Description
Definition at line 138 of file memberlist.h.
Constructor & Destructor Documentation
MemberLists() [1/4]
MemberLists::MemberLists () [default]
MemberLists() [2/4]
MemberLists::MemberLists (const MemberLists &) [private], [delete]
MemberLists() [3/4]
MemberLists::MemberLists () [default]
MemberLists() [4/4]
MemberLists::MemberLists (const MemberLists &) [private], [delete]
Member Function Documentation
get() [1/2]
const std::unique_ptr< MemberList > & MemberLists::get (MemberListType lt, MemberListContainer con) [inline]
Definition at line 142 of file memberlist.h.
    {
      // find the list with the given type
      auto it = std::find_if(begin(),end(),[&lt](const auto &ml) { return ml->listType()==lt; });
      if (it!=end()) return *it;
      // or create a new list if it is not found
      emplace_back(std::make_unique<MemberList>(lt,con));
      return back();
    }
References ghc::filesystem::begin(), and ghc::filesystem::end().
Referenced by GroupDefImpl::addMemberToList(), ClassDefImpl::addMemberToList(), FileDefImpl::addMemberToList(), NamespaceDefImpl::addMemberToList(), FileDefImpl::insertMember(), NamespaceDefImpl::insertMember(), and ClassDefImpl::internalInsertMember().
get() [2/2]
const std::unique_ptr< MemberList > & MemberLists::get (MemberListType lt, MemberListContainer con) [inline]
Definition at line 142 of file memberlist.h.
    {
      // find the list with the given type
      auto it = std::find_if(begin(),end(),[&lt](const auto &ml) { return ml->listType()==lt; });
      if (it!=end()) return *it;
      // or create a new list if it is not found
      emplace_back(std::make_unique<MemberList>(lt,con));
      return back();
    }
References ghc::filesystem::begin(), and ghc::filesystem::end().
operator=() [1/2]
MemberLists & MemberLists::operator= (const MemberLists &) [private], [delete]
operator=() [2/2]
MemberLists & MemberLists::operator= (const MemberLists &) [private], [delete]
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/memberlist.h
doxygen/src/memberlist.h