DirDef Class Reference
#include <dirdef.h>
Classes
class UsedDirLinkedMap
Public Member Functions
virtual DefType definitionType () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual const QCString shortName () const =0
virtual void addSubDir (DirDef *subdir)=0
virtual const FileList & getFiles () const =0
virtual void addFile (const FileDef *fd)=0
virtual const DirList & subDirs () const =0
virtual bool hasSubdirs () const =0
virtual int level () const =0
virtual DirDef * parent () const =0
virtual int dirCount () const =0
virtual const UsedDirLinkedMap & usedDirs () const =0
virtual bool isParentOf (const DirDef *dir) const =0
virtual bool depGraphIsTrivial () const =0
virtual QCString shortTitle () const =0
virtual bool hasDetailedDescription () const =0
virtual void writeDocumentation (OutputList &ol)=0
virtual void writeTagFile (TextStream &t)=0
virtual void setDiskName (const QCString &name)=0
virtual void setDirCount (int count)=0
virtual void sort ()=0
virtual void setParent (DirDef *parent)=0
virtual void setLevel ()=0
virtual void addUsesDependency (const DirDef *usedDir, const FileDef *srcFd, const FileDef *dstFd, bool srcDirect, bool dstDirect)=0
virtual void computeDependencies ()=0
virtual DefType definitionType () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual const QCString shortName () const =0
virtual void addSubDir (DirDef *subdir)=0
virtual const FileList & getFiles () const =0
virtual void addFile (const FileDef *fd)=0
virtual const DirList & subDirs () const =0
virtual bool hasSubdirs () const =0
virtual int level () const =0
virtual DirDef * parent () const =0
virtual int dirCount () const =0
virtual const UsedDirLinkedMap & usedDirs () const =0
virtual bool isParentOf (const DirDef *dir) const =0
virtual bool depGraphIsTrivial () const =0
virtual QCString shortTitle () const =0
virtual bool hasDetailedDescription () const =0
virtual void writeDocumentation (OutputList &ol)=0
virtual void writeTagFile (TextStream &t)=0
virtual void setDiskName (const QCString &name)=0
virtual void setDirCount (int count)=0
virtual void sort ()=0
virtual void setParent (DirDef *parent)=0
virtual void setLevel ()=0
virtual void addUsesDependency (const DirDef *usedDir, const FileDef *srcFd, const FileDef *dstFd, bool srcDirect, bool dstDirect)=0
virtual void computeDependencies ()=0
Additional Inherited Members
Detailed Description
A model of a directory symbol.
Definition at line 110 of file dirdef.h.
Member Function Documentation
addFile() [1/2]
virtual void DirDef::addFile (const FileDef * fd) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by buildDirectories().
addFile() [2/2]
virtual void DirDef::addFile (const FileDef * fd) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
addSubDir() [1/2]
virtual void DirDef::addSubDir (DirDef * subdir) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
addSubDir() [2/2]
virtual void DirDef::addSubDir (DirDef * subdir) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
addUsesDependency() [1/2]
virtual void DirDef::addUsesDependency (const DirDef * usedDir, const FileDef * srcFd, const FileDef * dstFd, bool srcDirect, bool dstDirect) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by DirDefImpl::addUsesDependency().
addUsesDependency() [2/2]
virtual void DirDef::addUsesDependency (const DirDef * usedDir, const FileDef * srcFd, const FileDef * dstFd, bool srcDirect, bool dstDirect) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
anchor() [1/2]
virtual QCString DirDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in DirDefImpl, and DirDefImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString DirDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in DirDefImpl, and DirDefImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
computeDependencies() [1/2]
virtual void DirDef::computeDependencies () [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by computeDirDependencies().
computeDependencies() [2/2]
virtual void DirDef::computeDependencies () [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
definitionType() [1/2]
virtual DefType DirDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in DirDefImpl, and DirDefImpl.
definitionType() [2/2]
virtual DefType DirDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in DirDefImpl, and DirDefImpl.
depGraphIsTrivial() [1/2]
virtual bool DirDef::depGraphIsTrivial () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by DotDirDeps::isTrivial().
depGraphIsTrivial() [2/2]
virtual bool DirDef::depGraphIsTrivial () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
dirCount() [1/2]
virtual int DirDef::dirCount () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by addDependencies().
dirCount() [2/2]
virtual int DirDef::dirCount () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
displayName() [1/2]
virtual QCString DirDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in DirDefImpl, and DirDefImpl.
Referenced by DotDirDeps::computeTheGraph(), generateXMLForDir(), DotDirDeps::getImgAltText(), and DirRelation::writeDocumentation().
displayName() [2/2]
virtual QCString DirDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in DirDefImpl, and DirDefImpl.
getFiles() [1/2]
virtual const FileList & DirDef::getFiles () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by NestingNodeContext::Private::addDirFiles(), DirContext::Private::createFiles(), dirHasVisibleChildren(), generateXMLForDir(), and writeDirTreeNode().
getFiles() [2/2]
virtual const FileList & DirDef::getFiles () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
getOutputFileBase() [1/2]
virtual QCString DirDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in DirDefImpl, and DirDefImpl.
Referenced by DirDefImpl::addUsesDependency(), common_attributes(), DirContext::Private::dirGraph(), generateXMLForDir(), DotDirDeps::getBaseName(), writeDirTreeNode(), DirRelation::writeDocumentation(), writeDotDirDepGraph(), and writePartialDirPath().
getOutputFileBase() [2/2]
virtual QCString DirDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in DirDefImpl, and DirDefImpl.
hasDetailedDescription() [1/2]
virtual bool DirDef::hasDetailedDescription () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by DirContext::Private::hasDetails().
hasDetailedDescription() [2/2]
virtual bool DirDef::hasDetailedDescription () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
hasSubdirs() [1/2]
virtual bool DirDef::hasSubdirs () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
hasSubdirs() [2/2]
virtual bool DirDef::hasSubdirs () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
isLinkable() [1/2]
virtual bool DirDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in DirDefImpl, and DirDefImpl.
Referenced by resolveLink().
isLinkable() [2/2]
virtual bool DirDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in DirDefImpl, and DirDefImpl.
isLinkableInProject() [1/2]
virtual bool DirDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in DirDefImpl, and DirDefImpl.
isLinkableInProject() [2/2]
virtual bool DirDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in DirDefImpl, and DirDefImpl.
isParentOf() [1/2]
virtual bool DirDef::isParentOf (const DirDef * dir) const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
isParentOf() [2/2]
virtual bool DirDef::isParentOf (const DirDef * dir) const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
level() [1/2]
virtual int DirDef::level () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docHeadingType::buildAttributes(), doxmlparser.compound.docHeadingType::exportAttributes(), doxmlparser.compound.docHeadingType::get_level(), and doxmlparser.compound.docHeadingType::set_level().
level() [2/2]
virtual int DirDef::level () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docHeadingType::buildAttributes(), doxmlparser.compound.docHeadingType::exportAttributes(), doxmlparser.compound.docHeadingType::get_level(), and doxmlparser.compound.docHeadingType::set_level().
parent() [1/2]
virtual DirDef * DirDef::parent () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by DirDefImpl::addUsesDependency(), DirDefImpl::isParentOf(), writeDotDirDepGraph(), and writePartialDirPath().
parent() [2/2]
virtual DirDef * DirDef::parent () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
setDirCount() [1/2]
virtual void DirDef::setDirCount (int count) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by buildDirectories().
setDirCount() [2/2]
virtual void DirDef::setDirCount (int count) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
setDiskName() [1/2]
virtual void DirDef::setDiskName (const QCString & name) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by computeCommonDirPrefix().
setDiskName() [2/2]
virtual void DirDef::setDiskName (const QCString & name) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
setLevel() [1/2]
virtual void DirDef::setLevel () [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by computeDirDependencies().
setLevel() [2/2]
virtual void DirDef::setLevel () [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
setParent() [1/2]
virtual void DirDef::setParent (DirDef * parent) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by DirDefImpl::addSubDir().
setParent() [2/2]
virtual void DirDef::setParent (DirDef * parent) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
shortName() [1/2]
virtual const QCString DirDef::shortName () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by compareDirDefs(), DirContext::Private::dirName(), writeDirTreeNode(), DirRelation::writeDocumentation(), and writePartialDirPath().
shortName() [2/2]
virtual const QCString DirDef::shortName () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
shortTitle() [1/2]
virtual QCString DirDef::shortTitle () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by DirContext::Private::title().
shortTitle() [2/2]
virtual QCString DirDef::shortTitle () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
sort() [1/2]
virtual void DirDef::sort () [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by buildDirectories(), and translator.TrManager::generateTranslatorReport().
sort() [2/2]
virtual void DirDef::sort () [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by translator.TrManager::generateTranslatorReport().
subDirs() [1/2]
virtual const DirList & DirDef::subDirs () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by NestingNodeContext::Private::addDirFiles(), DirContext::Private::createDirs(), dirHasVisibleChildren(), generateXMLForDir(), and writeDirTreeNode().
subDirs() [2/2]
virtual const DirList & DirDef::subDirs () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
usedDirs() [1/2]
virtual const UsedDirLinkedMap & DirDef::usedDirs () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by addDependencies(), and writeDotDirDepGraph().
usedDirs() [2/2]
virtual const UsedDirLinkedMap & DirDef::usedDirs () const [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
writeDocumentation() [1/2]
virtual void DirDef::writeDocumentation (OutputList & ol) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
Referenced by generateDirDocs().
writeDocumentation() [2/2]
virtual void DirDef::writeDocumentation (OutputList & ol) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
writeTagFile() [1/2]
virtual void DirDef::writeTagFile (TextStream & t) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
writeTagFile() [2/2]
virtual void DirDef::writeTagFile (TextStream & t) [pure virtual]
Implemented in DirDefImpl, and DirDefImpl.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dirdef.h
doxygen/src/dirdef.h