PageListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
void addPages (const PageLinkedMap &pages)
PageListContext (const PageLinkedMap &pages)
virtual ~PageListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
void addPages (const PageLinkedMap &pages)
PageListContext (const PageLinkedMap &pages)
virtual ~PageListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc (const PageLinkedMap &pages)
static TemplateListIntfPtr alloc (const PageLinkedMap &pages)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 710 of file context.h.
Constructor & Destructor Documentation
PageListContext() [1/2]
PageListContext::PageListContext (const PageLinkedMap & pages)
Definition at line 6650 of file context.cpp.
                                                           : p(std::make_unique<Private>())
{
  p->addPages(pages);
}
References p.
 PageListContext() [1/2]
PageListContext::~PageListContext () [virtual]
Definition at line 6655 of file context.cpp.
{
}
PageListContext() [2/2]
PageListContext::PageListContext (const PageLinkedMap & pages)
 PageListContext() [2/2]
virtual PageListContext::~PageListContext () [virtual]
Member Function Documentation
addPages() [1/2]
void PageListContext::addPages (const PageLinkedMap & pages)
addPages() [2/2]
void PageListContext::addPages (const PageLinkedMap & pages)
alloc() [1/2]
static TemplateListIntfPtr PageListContext::alloc (const PageLinkedMap & pages) [inline], [static]
Definition at line 713 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<PageListContext>(pages)); }
Referenced by generateOutputViaTemplate().
alloc() [2/2]
static TemplateListIntfPtr PageListContext::alloc (const PageLinkedMap & pages) [inline], [static]
Definition at line 713 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<PageListContext>(pages)); }
at() [1/2]
TemplateVariant PageListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 6665 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant PageListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t PageListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 6660 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t PageListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr PageListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 6670 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr PageListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > PageListContext::p [private]
Definition at line 728 of file context.h.
Referenced by at(), count(), createIterator(), and PageListContext().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp