UsedFilesContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
void addFile (const FileDef *fd)
UsedFilesContext (const ClassDef *cd)
virtual ~UsedFilesContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
void addFile (const FileDef *fd)
UsedFilesContext (const ClassDef *cd)
virtual ~UsedFilesContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc (const ClassDef *cd)
static TemplateListIntfPtr alloc (const ClassDef *cd)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 132 of file context.h.
Constructor & Destructor Documentation
UsedFilesContext() [1/2]
UsedFilesContext::UsedFilesContext (const ClassDef * cd)
Definition at line 6437 of file context.cpp.
                                                     : p(std::make_unique<Private>())
{
  if (cd)
  {
    for (const auto &fd : cd->usedFiles())
    {
      p->addFile(fd);
    }
  }
}
References p, and ClassDef::usedFiles().
 UsedFilesContext() [1/2]
UsedFilesContext::~UsedFilesContext () [virtual]
Definition at line 6448 of file context.cpp.
{
}
UsedFilesContext() [2/2]
UsedFilesContext::UsedFilesContext (const ClassDef * cd)
 UsedFilesContext() [2/2]
virtual UsedFilesContext::~UsedFilesContext () [virtual]
Member Function Documentation
addFile() [1/2]
void UsedFilesContext::addFile (const FileDef * fd)
Definition at line 6468 of file context.cpp.
{
  p->addFile(fd);
}
References p.
addFile() [2/2]
void UsedFilesContext::addFile (const FileDef * fd)
alloc() [1/2]
static TemplateListIntfPtr UsedFilesContext::alloc (const ClassDef * cd) [inline], [static]
Definition at line 135 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<UsedFilesContext>(cd)); }
Referenced by ClassContext::Private::createUsedFiles().
alloc() [2/2]
static TemplateListIntfPtr UsedFilesContext::alloc (const ClassDef * cd) [inline], [static]
Definition at line 135 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<UsedFilesContext>(cd)); }
at() [1/2]
TemplateVariant UsedFilesContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 6458 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant UsedFilesContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t UsedFilesContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 6453 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t UsedFilesContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr UsedFilesContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 6463 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr UsedFilesContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > UsedFilesContext::p [private]
Definition at line 150 of file context.h.
Referenced by addFile(), at(), count(), createIterator(), and UsedFilesContext().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp