ConceptTreeContext::Private Class Reference
Public Member Functions
Private ()
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private ()
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant tree () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant maxDepth () const
TemplateVariant preferredDepth () const
TemplateVariant title () const
int createMaxDepth () const
int createPreferredDepth () const
TemplateVariant tree () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant maxDepth () const
TemplateVariant preferredDepth () const
TemplateVariant title () const
int createMaxDepth () const
int createPreferredDepth () const
Private Attributes
TemplateListIntfPtr m_conceptTree
CachedItem< int, Private, &Private::createMaxDepth > m_maxDepth
CachedItem< int, Private, &Private::createPreferredDepth > m_preferredDepth
Static Private Attributes
static const PropertyMap< ConceptTreeContext::Private > s_inst
Detailed Description
Definition at line 6762 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
ConceptTreeContext::Private::Private () [inline]
Definition at line 6765 of file context.cpp.
    {
      m_conceptTree = NestingContext::alloc(0,ContextTreeType::Concept,0);
      auto ctx = std::dynamic_pointer_cast<NestingContext>(m_conceptTree);
      ClassDefSet visitedClasses;
      // Add concepts
      ctx->addNamespaces(*Doxygen::namespaceLinkedMap,TRUE,FALSE,TRUE,visitedClasses);
      ctx->addConcepts(*Doxygen::conceptLinkedMap,TRUE,visitedClasses);
    }
References NestingContext::alloc(), Concept, Doxygen::conceptLinkedMap, FALSE, m_conceptTree, Doxygen::namespaceLinkedMap, and TRUE.
Private() [2/2]
ConceptTreeContext::Private::Private () [inline]
Definition at line 6765 of file context.cpp.
    {
      m_conceptTree = NestingContext::alloc(0,ContextTreeType::Concept,0);
      auto ctx = std::dynamic_pointer_cast<NestingContext>(m_conceptTree);
      ClassDefSet visitedClasses;
      // Add concepts
      ctx->addNamespaces(*Doxygen::namespaceLinkedMap,TRUE,FALSE,TRUE,visitedClasses);
      ctx->addConcepts(*Doxygen::conceptLinkedMap,TRUE,visitedClasses);
    }
References NestingContext::alloc(), Concept, Doxygen::conceptLinkedMap, FALSE, Doxygen::namespaceLinkedMap, and TRUE.
Member Function Documentation
createMaxDepth() [1/2]
int ConceptTreeContext::Private::createMaxDepth () const [inline], [private]
Definition at line 6791 of file context.cpp.
    {
      return computeMaxDepth(m_conceptTree);
    }
References computeMaxDepth(), and m_conceptTree.
createMaxDepth() [2/2]
int ConceptTreeContext::Private::createMaxDepth () const [inline], [private]
Definition at line 6791 of file context.cpp.
    {
      return computeMaxDepth(m_conceptTree);
    }
References computeMaxDepth().
createPreferredDepth() [1/2]
int ConceptTreeContext::Private::createPreferredDepth () const [inline], [private]
Definition at line 6795 of file context.cpp.
    {
      return computePreferredDepth(m_conceptTree,m_maxDepth.get(this));
    }
References computePreferredDepth(), m_conceptTree, and m_maxDepth.
createPreferredDepth() [2/2]
int ConceptTreeContext::Private::createPreferredDepth () const [inline], [private]
Definition at line 6795 of file context.cpp.
    {
      return computePreferredDepth(m_conceptTree,m_maxDepth.get(this));
    }
References computePreferredDepth().
fields() [1/2]
StringVector ConceptTreeContext::Private::fields () const [inline]
Definition at line 6777 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector ConceptTreeContext::Private::fields () const [inline]
Definition at line 6777 of file context.cpp.
{ return s_inst.fields(); }
fileName() [1/2]
TemplateVariant ConceptTreeContext::Private::fileName () const [inline], [private]
Definition at line 6782 of file context.cpp.
{ return "concepts"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
TemplateVariant ConceptTreeContext::Private::fileName () const [inline], [private]
Definition at line 6782 of file context.cpp.
{ return "concepts"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
get() [1/2]
TemplateVariant ConceptTreeContext::Private::get (const QCString & n) const [inline]
Definition at line 6776 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant ConceptTreeContext::Private::get (const QCString & n) const [inline]
Definition at line 6776 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
highlight() [1/2]
TemplateVariant ConceptTreeContext::Private::highlight () const [inline], [private]
Definition at line 6784 of file context.cpp.
{ return "concepts"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant ConceptTreeContext::Private::highlight () const [inline], [private]
Definition at line 6784 of file context.cpp.
{ return "concepts"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
maxDepth() [1/2]
TemplateVariant ConceptTreeContext::Private::maxDepth () const [inline], [private]
Definition at line 6786 of file context.cpp.
{ return m_maxDepth.get(this); }
References m_maxDepth.
maxDepth() [2/2]
TemplateVariant ConceptTreeContext::Private::maxDepth () const [inline], [private]
Definition at line 6786 of file context.cpp.
{ return m_maxDepth.get(this); }
preferredDepth() [1/2]
TemplateVariant ConceptTreeContext::Private::preferredDepth () const [inline], [private]
Definition at line 6787 of file context.cpp.
{ return m_preferredDepth.get(this); }
References m_preferredDepth.
preferredDepth() [2/2]
TemplateVariant ConceptTreeContext::Private::preferredDepth () const [inline], [private]
Definition at line 6787 of file context.cpp.
{ return m_preferredDepth.get(this); }
relPath() [1/2]
TemplateVariant ConceptTreeContext::Private::relPath () const [inline], [private]
Definition at line 6783 of file context.cpp.
{ return ""; }
relPath() [2/2]
TemplateVariant ConceptTreeContext::Private::relPath () const [inline], [private]
Definition at line 6783 of file context.cpp.
{ return ""; }
subhighlight() [1/2]
TemplateVariant ConceptTreeContext::Private::subhighlight () const [inline], [private]
Definition at line 6785 of file context.cpp.
{ return ""; }
subhighlight() [2/2]
TemplateVariant ConceptTreeContext::Private::subhighlight () const [inline], [private]
Definition at line 6785 of file context.cpp.
{ return ""; }
title() [1/2]
TemplateVariant ConceptTreeContext::Private::title () const [inline], [private]
Definition at line 6788 of file context.cpp.
{ return theTranslator->trConcept(true,false); }
References theTranslator, and Translator::trConcept().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant ConceptTreeContext::Private::title () const [inline], [private]
Definition at line 6788 of file context.cpp.
{ return theTranslator->trConcept(true,false); }
References theTranslator, and Translator::trConcept().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
tree() [1/2]
TemplateVariant ConceptTreeContext::Private::tree () const [inline], [private]
Definition at line 6781 of file context.cpp.
{ return TemplateVariant(m_conceptTree); }
References m_conceptTree.
tree() [2/2]
TemplateVariant ConceptTreeContext::Private::tree () const [inline], [private]
Definition at line 6781 of file context.cpp.
{ return TemplateVariant(m_conceptTree); }
Member Data Documentation
m_conceptTree
TemplateListIntfPtr ConceptTreeContext::Private::m_conceptTree [private]
Definition at line 6799 of file context.cpp.
Referenced by createMaxDepth(), createPreferredDepth(), Private(), and tree().
m_maxDepth
CachedItem< int, Private, &Private::createMaxDepth > ConceptTreeContext::Private::m_maxDepth [private]
Definition at line 6800 of file context.cpp.
Referenced by createPreferredDepth(), and maxDepth().
m_preferredDepth
CachedItem< int, Private, &Private::createPreferredDepth > ConceptTreeContext::Private::m_preferredDepth [private]
Definition at line 6801 of file context.cpp.
Referenced by preferredDepth().
s_inst
const PropertyMap< ConceptTreeContext::Private > ConceptTreeContext::Private::s_inst [static], [private]
Initial value:
{
  { "tree", &Private::tree },
  { "fileName", &Private::fileName },
  { "relPath", &Private::relPath },
  { "highlight", &Private::highlight },
  { "subhighlight", &Private::subhighlight },
  { "title", &Private::title },
  { "preferredDepth",&Private::preferredDepth },
  { "maxDepth", &Private::maxDepth }
}
Definition at line 6802 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp