TranslatorCatalan Class Reference
#include <translator_ca.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
Additional Inherited Members
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include `translator.h` or `translator_adapter.h` here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 43 of file translator_ca.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorCatalan::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 82 of file translator_ca.h.
    {
      return "0x403 Catalan";
    }
getLanguageString() [2/2]
virtual QCString TranslatorCatalan::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 82 of file translator_ca.h.
    {
      return "0x403 Catalan";
    }
idLanguage() [1/2]
virtual QCString TranslatorCatalan::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 55 of file translator_ca.h.
    { return "catalan"; }
idLanguage() [2/2]
virtual QCString TranslatorCatalan::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 55 of file translator_ca.h.
    { return "catalan"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorCatalan::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 72 of file translator_ca.h.
    {
      //return "\\usepackage[catalan]{babel}\n\\usepackage[latin1]{inputenc}";
      return "\\usepackage[catalan]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorCatalan::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 72 of file translator_ca.h.
    {
      //return "\\usepackage[catalan]{babel}\n\\usepackage[latin1]{inputenc}";
      return "\\usepackage[catalan]{babel}\n";
    }
trAll() [1/2]
virtual QCString TranslatorCatalan::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1399 of file translator_ca.h.
    {
      return "Tot";
    }
trAll() [2/2]
virtual QCString TranslatorCatalan::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1399 of file translator_ca.h.
    {
      return "Tot";
    }
trAttention() [1/2]
virtual QCString TranslatorCatalan::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 969 of file translator_ca.h.
    {
      return "Atenci";
    }
trAttention() [2/2]
virtual QCString TranslatorCatalan::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 969 of file translator_ca.h.
    {
      return "Atenci";
    }
trAuthor() [1/2]
virtual QCString TranslatorCatalan::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1270 of file translator_ca.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      if (!singular) result+="s";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorCatalan::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1270 of file translator_ca.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      if (!singular) result+="s";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorCatalan::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1128 of file translator_ca.h.
    {
      return "Error";
    }
trBug() [2/2]
virtual QCString TranslatorCatalan::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1128 of file translator_ca.h.
    {
      return "Error";
    }
trBugList() [1/2]
virtual QCString TranslatorCatalan::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1133 of file translator_ca.h.
    {
      return "Llista d'Errors";
    }
trBugList() [2/2]
virtual QCString TranslatorCatalan::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1133 of file translator_ca.h.
    {
      return "Llista d'Errors";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorCatalan::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1520 of file translator_ca.h.
    {
      return "Grfic de crides a aquesta funci:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorCatalan::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1520 of file translator_ca.h.
    {
      return "Grfic de crides a aquesta funci:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorCatalan::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1404 of file translator_ca.h.
    {
      return "Grfic de crides d'aquesta funci:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorCatalan::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1404 of file translator_ca.h.
    {
      return "Grfic de crides d'aquesta funci:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorCatalan::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1849 of file translator_ca.h.
    { return "Referncies Bibliogrfiques"; }
trCiteReferences() [2/2]
virtual QCString TranslatorCatalan::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1849 of file translator_ca.h.
    { return "Referncies Bibliogrfiques"; }
trClass() [1/2]
virtual QCString TranslatorCatalan::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1191 of file translator_ca.h.
    {
      QCString result((first_capital ? "Classe" : "classe"));
      if (!singular) result+="s";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorCatalan::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1191 of file translator_ca.h.
    {
      QCString result((first_capital ? "Classe" : "classe"));
      if (!singular) result+="s";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorCatalan::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 518 of file translator_ca.h.
    {
      return "Diagrama d'Herncia per a "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorCatalan::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 518 of file translator_ca.h.
    {
      return "Diagrama d'Herncia per a "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorCatalan::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 393 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentaci de les Estructures de Dades";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentaci de les Classes";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorCatalan::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 393 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentaci de les Estructures de Dades";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentaci de les Classes";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorCatalan::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1091 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructures de Dades";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorCatalan::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1091 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructures de Dades";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorCatalan::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 177 of file translator_ca.h.
    { return "Jerarquia de Classes"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorCatalan::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 177 of file translator_ca.h.
    { return "Jerarquia de Classes"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorCatalan::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 236 of file translator_ca.h.
    { return "Aquesta llista d'herncia est ordenada toscament, "
             "per no completa, de forma alfabtica:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorCatalan::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 236 of file translator_ca.h.
    { return "Aquesta llista d'herncia est ordenada toscament, "
             "per no completa, de forma alfabtica:";
    }
trCode() [1/2]
virtual QCString TranslatorCatalan::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 869 of file translator_ca.h.
    {
      return "codi";
    }
trCode() [2/2]
virtual QCString TranslatorCatalan::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 869 of file translator_ca.h.
    {
      return "codi";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorCatalan::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 824 of file translator_ca.h.
    {
      return "Diagrama de collaboraci per a "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorCatalan::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 824 of file translator_ca.h.
    {
      return "Diagrama de collaboraci per a "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorCatalan::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 366 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "ndex d'Estructures de Dades";
      }
      else
      {
        return "ndex de Classes";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorCatalan::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 366 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "ndex d'Estructures de Dades";
      }
      else
      {
        return "ndex de Classes";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorCatalan::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1574 of file translator_ca.h.
    { return "ndex de Tipus de Dades"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorCatalan::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1574 of file translator_ca.h.
    { return "ndex de Tipus de Dades"; }
trCompoundList() [1/2]
virtual QCString TranslatorCatalan::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 181 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructures de Dades";
      }
      else
      {
        return "Llista de Classes";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorCatalan::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 181 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructures de Dades";
      }
      else
      {
        return "Llista de Classes";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorCatalan::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 251 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Aquestes sn les estructures de dades acompanyades amb breus descripcions:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Aquestes sn les classes acompanyades amb breus descripcions:";
      }
      else
      {
        return "Aquestes sn les classes, estructures, "
               "unions i interfcies acompanyades amb breus descripcions:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorCatalan::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 251 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Aquestes sn les estructures de dades acompanyades amb breus descripcions:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Aquestes sn les classes acompanyades amb breus descripcions:";
      }
      else
      {
        return "Aquestes sn les classes, estructures, "
               "unions i interfcies acompanyades amb breus descripcions:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorCatalan::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1548 of file translator_ca.h.
    { return "Aquests sn els tipus de dades acompanyats amb breus descripcions:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorCatalan::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1548 of file translator_ca.h.
    { return "Aquests sn els tipus de dades acompanyats amb breus descripcions:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorCatalan::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1540 of file translator_ca.h.
    { return "Llista de Tipus de Dades"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorCatalan::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1540 of file translator_ca.h.
    { return "Llista de Tipus de Dades"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorCatalan::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 198 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Camps de Dades";
      }
      else
      {
        return "Membres de Classes";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorCatalan::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 198 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Camps de Dades";
      }
      else
      {
        return "Membres de Classes";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorCatalan::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 270 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="camps d'estructures i unions";
      }
      else
      {
        result+="membres de classe";
      }
      if (!extractAll)
      {
        result+=" documentats";
      }
      result+=" amb enllaos a ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la documentaci de l'estructura/uni per a cada camp:";
        }
        else
        {
          result+="la documentaci de la classe per a cada membre:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="les estructures/unions a que pertanyen:";
        }
        else
        {
          result+="les classes a que pertanyen:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorCatalan::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 270 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="camps d'estructures i unions";
      }
      else
      {
        result+="membres de classe";
      }
      if (!extractAll)
      {
        result+=" documentats";
      }
      result+=" amb enllaos a ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la documentaci de l'estructura/uni per a cada camp:";
        }
        else
        {
          result+="la documentaci de la classe per a cada membre:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="les estructures/unions a que pertanyen:";
        }
        else
        {
          result+="les classes a que pertanyen:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorCatalan::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1552 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els membres de tipus de dades";
      if (!extractAll)
      {
        result+=" documentats";
      }
      result+=" amb enllaos a ";
      if (!extractAll)
      {
        result+="la documentaci del tipus de dades per a cada membre:";
      }
      else
      {
        result+="els tipus de dades a que pertanyen:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorCatalan::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1552 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els membres de tipus de dades";
      if (!extractAll)
      {
        result+=" documentats";
      }
      result+=" amb enllaos a ";
      if (!extractAll)
      {
        result+="la documentaci del tipus de dades per a cada membre:";
      }
      else
      {
        result+="els tipus de dades a que pertanyen:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorCatalan::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1544 of file translator_ca.h.
    { return "Camps de Dades"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorCatalan::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1544 of file translator_ca.h.
    { return "Camps de Dades"; }
trCompoundReference() [1/2]
virtual QCString TranslatorCatalan::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 593 of file translator_ca.h.
    {
      QCString result="Referncia de";
      switch(compType)
      {
        case ClassDef::Class: result+=" la Classe "; break;
        case ClassDef::Struct: result+=" l'Estructura "; break;
        case ClassDef::Union: result+=" la Uni "; break;
        case ClassDef::Interface: result+=" la Interfcie "; break;
        case ClassDef::Protocol: result+="l Protocol "; break;
        case ClassDef::Category: result+=" la Categoria "; break;
        case ClassDef::Exception: result+=" l'Excepci "; break;
        default: break;
      }
      if (isTemplate) result+="Template ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorCatalan::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 593 of file translator_ca.h.
    {
      QCString result="Referncia de";
      switch(compType)
      {
        case ClassDef::Class: result+=" la Classe "; break;
        case ClassDef::Struct: result+=" l'Estructura "; break;
        case ClassDef::Union: result+=" la Uni "; break;
        case ClassDef::Interface: result+=" la Interfcie "; break;
        case ClassDef::Protocol: result+="l Protocol "; break;
        case ClassDef::Category: result+=" la Categoria "; break;
        case ClassDef::Exception: result+=" l'Excepci "; break;
        default: break;
      }
      if (isTemplate) result+="Template ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorCatalan::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1615 of file translator_ca.h.
    {
      QCString result="Referncia de";
      switch(compType)
      {
        case ClassDef::Class: result+=" el Mdul "; break;
        case ClassDef::Struct: result+=" el Tipus "; break;
        case ClassDef::Union: result+=" la Uni "; break;
        case ClassDef::Interface: result+=" la Interfcie "; break;
        case ClassDef::Protocol: result+="l Protocol "; break;
        case ClassDef::Category: result+=" la Categoria "; break;
        case ClassDef::Exception: result+=" l'Excepci "; break;
        default: break;
      }
      if (isTemplate) result+="Template ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorCatalan::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1615 of file translator_ca.h.
    {
      QCString result="Referncia de";
      switch(compType)
      {
        case ClassDef::Class: result+=" el Mdul "; break;
        case ClassDef::Struct: result+=" el Tipus "; break;
        case ClassDef::Union: result+=" la Uni "; break;
        case ClassDef::Interface: result+=" la Interfcie "; break;
        case ClassDef::Protocol: result+="l Protocol "; break;
        case ClassDef::Category: result+=" la Categoria "; break;
        case ClassDef::Exception: result+=" l'Excepci "; break;
        default: break;
      }
      if (isTemplate) result+="Template ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorCatalan::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 494 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructures de Dades";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorCatalan::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 494 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructures de Dades";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorCatalan::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 834 of file translator_ca.h.
    {
      return "Documentaci del Constructor i el Destructor";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorCatalan::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 834 of file translator_ca.h.
    {
      return "Documentaci del Constructor i el Destructor";
    }
trCopyright() [1/2]
virtual QCString TranslatorCatalan::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1853 of file translator_ca.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorCatalan::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1853 of file translator_ca.h.
    { return "Copyright"; }
trDataTypes() [1/2]
virtual QCString TranslatorCatalan::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1598 of file translator_ca.h.
    { return "Tipus de Dades"; }
trDataTypes() [2/2]
virtual QCString TranslatorCatalan::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1598 of file translator_ca.h.
    { return "Tipus de Dades"; }
trDate() [1/2]
virtual QCString TranslatorCatalan::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 532 of file translator_ca.h.
    { return "Data"; }
trDate() [2/2]
virtual QCString TranslatorCatalan::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 532 of file translator_ca.h.
    { return "Data"; }
trDateTime() [1/2]
virtual QCString TranslatorCatalan::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1806 of file translator_ca.h.
    {
      static const char *days[] = { "Dl","Dt","Dc","Dj","Dv","Ds","Dg" };
      static const char *months[] = { "Gen","Feb","Mar","Abr","Mai","Jun","Jul","Ago","Sep","Oct","Nov","Dec" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorCatalan::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1806 of file translator_ca.h.
    {
      static const char *days[] = { "Dl","Dt","Dc","Dj","Dv","Ds","Dg" };
      static const char *months[] = { "Gen","Feb","Mar","Abr","Mai","Jun","Jul","Ago","Sep","Oct","Nov","Dec" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorCatalan::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1822 of file translator_ca.h.
    {
      static const char *days_short[] = { "dl.", "dt.", "dc.", "dj.", "dv.", "ds.", "dg." };
      static const char *days_full[] = { "dilluns", "dimarts", "dimecres", "dijous", "divendres", "dissabte", "diumenge" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorCatalan::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1822 of file translator_ca.h.
    {
      static const char *days_short[] = { "dl.", "dt.", "dc.", "dj.", "dv.", "ds.", "dg." };
      static const char *days_full[] = { "dilluns", "dimarts", "dimecres", "dijous", "divendres", "dissabte", "diumenge" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorCatalan::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1838 of file translator_ca.h.
    {
      static const char *dayPeriod[] = { "a.m.", "p.m." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorCatalan::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1838 of file translator_ca.h.
    {
      static const char *dayPeriod[] = { "a.m.", "p.m." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorCatalan::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 801 of file translator_ca.h.
    {
      return "Definici a la lnia @0 del fitxer @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorCatalan::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 801 of file translator_ca.h.
    {
      return "Definici a la lnia @0 del fitxer @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorCatalan::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 165 of file translator_ca.h.
    { return "definit a"; }
trDefinedIn() [2/2]
virtual QCString TranslatorCatalan::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 165 of file translator_ca.h.
    { return "definit a"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorCatalan::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 805 of file translator_ca.h.
    {
      return "Definici al fitxer @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorCatalan::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 805 of file translator_ca.h.
    {
      return "Definici al fitxer @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorCatalan::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 464 of file translator_ca.h.
    { return "Documentaci de les Definicions"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorCatalan::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 464 of file translator_ca.h.
    { return "Documentaci de les Definicions"; }
trDefines() [1/2]
virtual QCString TranslatorCatalan::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 428 of file translator_ca.h.
    { return "Definicions"; }
trDefines() [2/2]
virtual QCString TranslatorCatalan::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 428 of file translator_ca.h.
    { return "Definicions"; }
trDefineValue() [1/2]
virtual QCString TranslatorCatalan::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1118 of file translator_ca.h.
    {
      return "Valor:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorCatalan::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1118 of file translator_ca.h.
    {
      return "Valor:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorCatalan::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 814 of file translator_ca.h.
    {
      return "Antiquat";
    }
trDeprecated() [2/2]
virtual QCString TranslatorCatalan::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 814 of file translator_ca.h.
    {
      return "Antiquat";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorCatalan::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1327 of file translator_ca.h.
    {
      return "Llista d'Antiquats";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorCatalan::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1327 of file translator_ca.h.
    {
      return "Llista d'Antiquats";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorCatalan::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 98 of file translator_ca.h.
    { return "Descripci Detallada"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorCatalan::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 98 of file translator_ca.h.
    { return "Descripci Detallada"; }
trDir() [1/2]
virtual QCString TranslatorCatalan::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1494 of file translator_ca.h.
    {
      QCString result((first_capital ? "Directori" : "directori"));
      if (!singular) result+="s";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorCatalan::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1494 of file translator_ca.h.
    {
      QCString result((first_capital ? "Directori" : "directori"));
      if (!singular) result+="s";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorCatalan::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1857 of file translator_ca.h.
    { return QCString("Graf de dependncia de directoris per a ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorCatalan::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1857 of file translator_ca.h.
    { return QCString("Graf de dependncia de directoris per a ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorCatalan::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1476 of file translator_ca.h.
    { return "Documentaci dels Directoris"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorCatalan::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1476 of file translator_ca.h.
    { return "Documentaci dels Directoris"; }
trDirectories() [1/2]
virtual QCString TranslatorCatalan::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1482 of file translator_ca.h.
    { return "Directoris"; }
trDirectories() [2/2]
virtual QCString TranslatorCatalan::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1482 of file translator_ca.h.
    { return "Directoris"; }
trDirIndex() [1/2]
virtual QCString TranslatorCatalan::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1470 of file translator_ca.h.
    { return "Jerarquia de Directoris"; }
trDirIndex() [2/2]
virtual QCString TranslatorCatalan::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1470 of file translator_ca.h.
    { return "Jerarquia de Directoris"; }
trDirReference() [1/2]
virtual QCString TranslatorCatalan::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1488 of file translator_ca.h.
    { QCString result="Referncia del Directori "; result+=dirName; return result; }
trDirReference() [2/2]
virtual QCString TranslatorCatalan::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1488 of file translator_ca.h.
    { QCString result="Referncia del Directori "; result+=dirName; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorCatalan::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1745 of file translator_ca.h.
    {
      return QCString(name)+" Relaci";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorCatalan::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1745 of file translator_ca.h.
    {
      return QCString(name)+" Relaci";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorCatalan::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 348 of file translator_ca.h.
    { return ": Documentaci"; }
trDocumentation() [2/2]
virtual QCString TranslatorCatalan::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 348 of file translator_ca.h.
    { return ": Documentaci"; }
trEnumerations() [1/2]
virtual QCString TranslatorCatalan::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 440 of file translator_ca.h.
    { return "Enumeracions"; }
trEnumerations() [2/2]
virtual QCString TranslatorCatalan::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 440 of file translator_ca.h.
    { return "Enumeracions"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorCatalan::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 476 of file translator_ca.h.
    { return "Documentaci dels Tipus de les Enumeracions"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorCatalan::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 476 of file translator_ca.h.
    { return "Documentaci dels Tipus de les Enumeracions"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorCatalan::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1528 of file translator_ca.h.
    { return "Documentaci de les Enumeracions"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorCatalan::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1528 of file translator_ca.h.
    { return "Documentaci de les Enumeracions"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorCatalan::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 458 of file translator_ca.h.
    { return "Valors de les Enumeracions"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorCatalan::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 458 of file translator_ca.h.
    { return "Valors de les Enumeracions"; }
trEnumName() [1/2]
virtual QCString TranslatorCatalan::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 157 of file translator_ca.h.
    { return "nom de la enum"; }
trEnumName() [2/2]
virtual QCString TranslatorCatalan::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 157 of file translator_ca.h.
    { return "nom de la enum"; }
trEnumValue() [1/2]
virtual QCString TranslatorCatalan::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 161 of file translator_ca.h.
    { return "valors de la enum"; }
trEnumValue() [2/2]
virtual QCString TranslatorCatalan::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 161 of file translator_ca.h.
    { return "valors de la enum"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorCatalan::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1344 of file translator_ca.h.
    {
      return "Documentaci dels Esdeveniments";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorCatalan::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1344 of file translator_ca.h.
    {
      return "Documentaci dels Esdeveniments";
    }
trEvents() [1/2]
virtual QCString TranslatorCatalan::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1339 of file translator_ca.h.
    {
      return "Esdeveniments";
    }
trEvents() [2/2]
virtual QCString TranslatorCatalan::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1339 of file translator_ca.h.
    {
      return "Esdeveniments";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorCatalan::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 418 of file translator_ca.h.
    { return "Documentaci dels Exemples"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorCatalan::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 418 of file translator_ca.h.
    { return "Documentaci dels Exemples"; }
trExamples() [1/2]
virtual QCString TranslatorCatalan::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 228 of file translator_ca.h.
    { return "Exemples"; }
trExamples() [2/2]
virtual QCString TranslatorCatalan::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 228 of file translator_ca.h.
    { return "Exemples"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorCatalan::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 333 of file translator_ca.h.
    { return "Aquesta s la llista de tots els exemples:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorCatalan::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 333 of file translator_ca.h.
    { return "Aquesta s la llista de tots els exemples:"; }
trExceptions() [1/2]
virtual QCString TranslatorCatalan::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 548 of file translator_ca.h.
    { return "Excepcions"; }
trExceptions() [2/2]
virtual QCString TranslatorCatalan::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 548 of file translator_ca.h.
    { return "Excepcions"; }
trFile() [1/2]
virtual QCString TranslatorCatalan::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1202 of file translator_ca.h.
    {
      QCString result((first_capital ? "Fitxer" : "fitxer"));
      if (!singular) result+="s";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorCatalan::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1202 of file translator_ca.h.
    {
      QCString result((first_capital ? "Fitxer" : "fitxer"));
      if (!singular) result+="s";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorCatalan::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 412 of file translator_ca.h.
    { return "Documentaci dels Fitxers"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorCatalan::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 412 of file translator_ca.h.
    { return "Documentaci dels Fitxers"; }
trFileIn() [1/2]
virtual QCString TranslatorCatalan::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1782 of file translator_ca.h.
    {
      return "Fitxer a "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorCatalan::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1782 of file translator_ca.h.
    {
      return "Fitxer a "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorCatalan::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 381 of file translator_ca.h.
    { return "ndex de Fitxers"; }
trFileIndex() [2/2]
virtual QCString TranslatorCatalan::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 381 of file translator_ca.h.
    { return "ndex de Fitxers"; }
trFileList() [1/2]
virtual QCString TranslatorCatalan::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 194 of file translator_ca.h.
    { return "Llista dels Fitxers"; }
trFileList() [2/2]
virtual QCString TranslatorCatalan::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 194 of file translator_ca.h.
    { return "Llista dels Fitxers"; }
trFileListDescription() [1/2]
virtual QCString TranslatorCatalan::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 242 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els fitxers ";
      if (!extractAll) result+="documentats ";
      result+="acompanyats amb breus descripcions:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorCatalan::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 242 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els fitxers ";
      if (!extractAll) result+="documentats ";
      result+="acompanyats amb breus descripcions:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorCatalan::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 211 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals";
      }
      else
      {
        return "Membres de Fitxers";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorCatalan::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 211 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals";
      }
      else
      {
        return "Membres de Fitxers";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorCatalan::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 311 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="totes les funcions, variables, definicions, enumeracions, i definicions de tipus";
        if (!extractAll) result+=" documentades";
      }
      else
      {
        result+="tots els membres de fitxers";
        if (!extractAll) result+=" documentats";
      }
      result+=" amb enllaos ";
      if (extractAll)
        result+="als fitxers als quals corresponen:";
      else
        result+="a la documentaci:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorCatalan::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 311 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="totes les funcions, variables, definicions, enumeracions, i definicions de tipus";
        if (!extractAll) result+=" documentades";
      }
      else
      {
        result+="tots els membres de fitxers";
        if (!extractAll) result+=" documentats";
      }
      result+=" amb enllaos ";
      if (extractAll)
        result+="als fitxers als quals corresponen:";
      else
        result+="a la documentaci:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorCatalan::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 615 of file translator_ca.h.
    {
      QCString result="Referncia del Fitxer ";
      result+=fileName;
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorCatalan::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 615 of file translator_ca.h.
    {
      QCString result="Referncia del Fitxer ";
      result+=fileName;
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorCatalan::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 575 of file translator_ca.h.
    { return "Classes Amigues"; }
trFriends() [2/2]
virtual QCString TranslatorCatalan::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 575 of file translator_ca.h.
    { return "Classes Amigues"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorCatalan::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 482 of file translator_ca.h.
    { return "Documentaci de les Funcions"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorCatalan::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 482 of file translator_ca.h.
    { return "Documentaci de les Funcions"; }
trFunctions() [1/2]
virtual QCString TranslatorCatalan::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 446 of file translator_ca.h.
    { return "Funcions"; }
trFunctions() [2/2]
virtual QCString TranslatorCatalan::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 446 of file translator_ca.h.
    { return "Funcions"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorCatalan::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 509 of file translator_ca.h.
    {
      QCString result="Generat a "+date;
      if (!projName.isEmpty()) result+=" per a "+projName;
      result+=" per";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorCatalan::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 509 of file translator_ca.h.
    {
      QCString result="Generat a "+date;
      if (!projName.isEmpty()) result+=" per a "+projName;
      result+=" per";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorCatalan::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 149 of file translator_ca.h.
    { QCString result="Generat automticament per Doxygen";
      if (!s.isEmpty()) result+=" per a "+s;
      result+=" a partir del codi font.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorCatalan::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 149 of file translator_ca.h.
    { QCString result="Generat automticament per Doxygen";
      if (!s.isEmpty()) result+=" per a "+s;
      result+=" a partir del codi font.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorCatalan::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 552 of file translator_ca.h.
    { return "Generat per"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorCatalan::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 552 of file translator_ca.h.
    { return "Generat per"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorCatalan::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 753 of file translator_ca.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentaci d'aquest";
      switch(compType)
      {
        case ClassDef::Class: result+="a classe"; break;
        case ClassDef::Struct: result+="a estructura"; break;
        case ClassDef::Union: result+="a uni"; break;
        case ClassDef::Interface: result+="a interfcie"; break;
        case ClassDef::Protocol: result+=" protocol"; break;
        case ClassDef::Category: result+="a categoria"; break;
        case ClassDef::Exception: result+="a excepci"; break;
        default: break;
      }
      result+=" es va generar a partir del";
      if (!single) result+="s";
      result+=" segent";
      if (!single) result+="s";
      result+=" fitxer";
      if (!single) result+="s:"; else result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorCatalan::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 753 of file translator_ca.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentaci d'aquest";
      switch(compType)
      {
        case ClassDef::Class: result+="a classe"; break;
        case ClassDef::Struct: result+="a estructura"; break;
        case ClassDef::Union: result+="a uni"; break;
        case ClassDef::Interface: result+="a interfcie"; break;
        case ClassDef::Protocol: result+=" protocol"; break;
        case ClassDef::Category: result+="a categoria"; break;
        case ClassDef::Exception: result+="a excepci"; break;
        default: break;
      }
      result+=" es va generar a partir del";
      if (!single) result+="s";
      result+=" segent";
      if (!single) result+="s";
      result+=" fitxer";
      if (!single) result+="s:"; else result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorCatalan::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1687 of file translator_ca.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentaci d'aquest";
      switch(compType)
      {
        case ClassDef::Class: result+=" mdul"; break;
        case ClassDef::Struct: result+=" tipus"; break;
        case ClassDef::Union: result+="a uni"; break;
        case ClassDef::Interface: result+="a interfcie"; break;
        case ClassDef::Protocol: result+=" protocol"; break;
        case ClassDef::Category: result+="a categoria"; break;
        case ClassDef::Exception: result+="a excepci"; break;
        default: break;
      }
      result+=" es va generar a partir del";
      if (!single) result+="s";
      result+=" segent";
      if (!single) result+="s";
      result+=" fitxer";
      if (!single) result+="s:"; else result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorCatalan::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1687 of file translator_ca.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentaci d'aquest";
      switch(compType)
      {
        case ClassDef::Class: result+=" mdul"; break;
        case ClassDef::Struct: result+=" tipus"; break;
        case ClassDef::Union: result+="a uni"; break;
        case ClassDef::Interface: result+="a interfcie"; break;
        case ClassDef::Protocol: result+=" protocol"; break;
        case ClassDef::Category: result+="a categoria"; break;
        case ClassDef::Exception: result+="a excepci"; break;
        default: break;
      }
      result+=" es va generar a partir del";
      if (!single) result+="s";
      result+=" segent";
      if (!single) result+="s";
      result+=" fitxer";
      if (!single) result+="s:"; else result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorCatalan::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1257 of file translator_ca.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorCatalan::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1257 of file translator_ca.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorCatalan::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1757 of file translator_ca.h.
    {
      return "Espai de Noms Global";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorCatalan::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1757 of file translator_ca.h.
    {
      return "Espai de Noms Global";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorCatalan::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 844 of file translator_ca.h.
    {
      return "Veure la documentaci d'aquest fitxer.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorCatalan::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 844 of file translator_ca.h.
    {
      return "Veure la documentaci d'aquest fitxer.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorCatalan::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_ca.h.
    {
      return "Veure la jerarquia grfica de la classe";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorCatalan::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_ca.h.
    {
      return "Veure la jerarquia grfica de la classe";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorCatalan::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 839 of file translator_ca.h.
    {
      return "Veure el codi d'aquest fitxer.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorCatalan::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 839 of file translator_ca.h.
    {
      return "Veure el codi d'aquest fitxer.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorCatalan::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_ca.h.
    {
      return "Veure la jerarquia textual de la classe";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorCatalan::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_ca.h.
    {
      return "Veure la jerarquia textual de la classe";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorCatalan::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 873 of file translator_ca.h.
    {
      return "Jerarquia Grfica de la Classe";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorCatalan::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 873 of file translator_ca.h.
    {
      return "Jerarquia Grfica de la Classe";
    }
trGroup() [1/2]
virtual QCString TranslatorCatalan::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1224 of file translator_ca.h.
    {
      QCString result((first_capital ? "Grup" : "grup"));
      if (!singular) result+="s";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorCatalan::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1224 of file translator_ca.h.
    {
      QCString result((first_capital ? "Grup" : "grup"));
      if (!singular) result+="s";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorCatalan::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 360 of file translator_ca.h.
    { return "ndex Jerrquic"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorCatalan::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 360 of file translator_ca.h.
    { return "ndex Jerrquic"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorCatalan::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1295 of file translator_ca.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorCatalan::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1295 of file translator_ca.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorCatalan::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1303 of file translator_ca.h.
    {
      return "Implementat a "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorCatalan::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1303 of file translator_ca.h.
    {
      return "Implementat a "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorCatalan::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_ca.h.
    {
      return "Aquest grfic mostra quins fitxers inclouen, "
             "de forma directa o indirecta, aquest fitxer:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorCatalan::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_ca.h.
    {
      return "Aquest grfic mostra quins fitxers inclouen, "
             "de forma directa o indirecta, aquest fitxer:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorCatalan::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 829 of file translator_ca.h.
    {
      return "Inclou el graf de dependncies per a "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorCatalan::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 829 of file translator_ca.h.
    {
      return "Inclou el graf de dependncies per a "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorCatalan::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1791 of file translator_ca.h.
    {
      return "Inclou fitxer a "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorCatalan::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1791 of file translator_ca.h.
    {
      return "Inclou fitxer a "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorCatalan::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 143 of file translator_ca.h.
    { return ", incloent tots els membres heretats."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorCatalan::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 143 of file translator_ca.h.
    { return ", incloent tots els membres heretats."; }
trInheritedByList() [1/2]
virtual QCString TranslatorCatalan::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 687 of file translator_ca.h.
    {
      return "Heretat per "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorCatalan::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 687 of file translator_ca.h.
    {
      return "Heretat per "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorCatalan::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 679 of file translator_ca.h.
    {
      return "Hereta de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorCatalan::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 679 of file translator_ca.h.
    {
      return "Hereta de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorCatalan::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 864 of file translator_ca.h.
    {
      return "Valor inicial:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorCatalan::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 864 of file translator_ca.h.
    {
      return "Valor inicial:";
    }
trInvariant() [1/2]
virtual QCString TranslatorCatalan::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 859 of file translator_ca.h.
    {
      return "Invariant";
    }
trInvariant() [2/2]
virtual QCString TranslatorCatalan::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 859 of file translator_ca.h.
    {
      return "Invariant";
    }
trISOLang() [1/2]
virtual QCString TranslatorCatalan::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 78 of file translator_ca.h.
    {
      return "ca";
    }
trISOLang() [2/2]
virtual QCString TranslatorCatalan::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 78 of file translator_ca.h.
    {
      return "ca";
    }
trLegend() [1/2]
virtual QCString TranslatorCatalan::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1051 of file translator_ca.h.
    {
      return "llegenda";
    }
trLegend() [2/2]
virtual QCString TranslatorCatalan::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1051 of file translator_ca.h.
    {
      return "llegenda";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorCatalan::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 995 of file translator_ca.h.
    {
      return
        "Aquesta pgina explica com s'interpreten els grfics generats per doxygen.<p>\n"
        "Considera aquest exemple:\n"
        "\\code\n"
        "/*! Classe invisible per culpa del retall */\n"
        "class Invisible { };\n\n"
        "/*! Classe truncada, l'herncia est amagada */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Classe no documentada amb comentaris doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Classe heredada amb herncia pblica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Una classe Template */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe heredada utilitzant herncia protegida */\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe heredada utiltzant herncia privada */\n"
        "class PrivateBase { };\n\n"
        "/*! Classe usada per la classe heretada */\n"
        "class Used { };\n\n"
        "/*! Super classe que hereda una quantitat de classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Resultar el grfic segent:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Les caixes del grfic superior tenen aquesta interpretaci:\n"
        "<ul>\n"
        "<li>Una caixa negra plena represent l'estructura o classe per la qual el grfic s'ha generat.\n"
        "<li>Una caixa de vora negra representa una estructura o classe documentada.\n"
        "<li>Una caixa de vora verda representa una estructura o classe indocumentada.\n"
        "<li>Una caixa de vora vermalla representa una estructura o classe documentada de la qual "
        "no es mostren totes les relacions d'herncia/inclusi. Un grfic s truncat si no s'ajusta als lmits.\n"
        "</ul>\n"
        "Les sagetes tenen aquest significat:\n"
        "<ul>\n"
        "<li>Una sageta blau fosc remarca una relaci d'herncia de tipus pblica entre dues classes.\n"
        "<li>Una sageta verd fosc remarca una relaci d'herncia de tipus protegida entre dues classes.\n"
        "<li>Una sageta roig fosc remarca una relaci d'herncia de tipus privada entre dues classes.\n"
        "<li>Una sageta puntejada de color porpra indica que una classe s continguda o usada per una altra classe."
        " La sageta s'etiqueta amb la variable o variables a travs de les quals la classe o estructura apuntada s accessible.\n"
        "<li>Una sageta puntejada de color groc indica la relaci entre una instncia template i la classe template de qu ha set instanciada."
        " La sageta s'etiqueta amb els parmetres template de la instncia.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorCatalan::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 995 of file translator_ca.h.
    {
      return
        "Aquesta pgina explica com s'interpreten els grfics generats per doxygen.<p>\n"
        "Considera aquest exemple:\n"
        "\\code\n"
        "/*! Classe invisible per culpa del retall */\n"
        "class Invisible { };\n\n"
        "/*! Classe truncada, l'herncia est amagada */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Classe no documentada amb comentaris doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Classe heredada amb herncia pblica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Una classe Template */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe heredada utilitzant herncia protegida */\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe heredada utiltzant herncia privada */\n"
        "class PrivateBase { };\n\n"
        "/*! Classe usada per la classe heretada */\n"
        "class Used { };\n\n"
        "/*! Super classe que hereda una quantitat de classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Resultar el grfic segent:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Les caixes del grfic superior tenen aquesta interpretaci:\n"
        "<ul>\n"
        "<li>Una caixa negra plena represent l'estructura o classe per la qual el grfic s'ha generat.\n"
        "<li>Una caixa de vora negra representa una estructura o classe documentada.\n"
        "<li>Una caixa de vora verda representa una estructura o classe indocumentada.\n"
        "<li>Una caixa de vora vermalla representa una estructura o classe documentada de la qual "
        "no es mostren totes les relacions d'herncia/inclusi. Un grfic s truncat si no s'ajusta als lmits.\n"
        "</ul>\n"
        "Les sagetes tenen aquest significat:\n"
        "<ul>\n"
        "<li>Una sageta blau fosc remarca una relaci d'herncia de tipus pblica entre dues classes.\n"
        "<li>Una sageta verd fosc remarca una relaci d'herncia de tipus protegida entre dues classes.\n"
        "<li>Una sageta roig fosc remarca una relaci d'herncia de tipus privada entre dues classes.\n"
        "<li>Una sageta puntejada de color porpra indica que una classe s continguda o usada per una altra classe."
        " La sageta s'etiqueta amb la variable o variables a travs de les quals la classe o estructura apuntada s accessible.\n"
        "<li>Una sageta puntejada de color groc indica la relaci entre una instncia template i la classe template de qu ha set instanciada."
        " La sageta s'etiqueta amb els parmetres template de la instncia.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorCatalan::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 988 of file translator_ca.h.
    {
      return "Llegenda del Grfic";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorCatalan::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 988 of file translator_ca.h.
    {
      return "Llegenda del Grfic";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorCatalan::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 131 of file translator_ca.h.
    { return "Llista de tots els membres"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorCatalan::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 131 of file translator_ca.h.
    { return "Llista de tots els membres"; }
trLoading() [1/2]
virtual QCString TranslatorCatalan::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1751 of file translator_ca.h.
    {
      return "Carregant...";
    }
trLoading() [2/2]
virtual QCString TranslatorCatalan::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1751 of file translator_ca.h.
    {
      return "Carregant...";
    }
trMainPage() [1/2]
virtual QCString TranslatorCatalan::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 788 of file translator_ca.h.
    { return "Pgina principal"; }
trMainPage() [2/2]
virtual QCString TranslatorCatalan::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 788 of file translator_ca.h.
    { return "Pgina principal"; }
trMember() [1/2]
virtual QCString TranslatorCatalan::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1246 of file translator_ca.h.
    {
      QCString result((first_capital ? "Membre" : "membre"));
      if (!singular) result+="s";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorCatalan::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1246 of file translator_ca.h.
    {
      QCString result((first_capital ? "Membre" : "membre"));
      if (!singular) result+="s";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorCatalan::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 114 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentaci dels Camps";
      }
      else
      {
        return "Documentaci de les Dades Membre";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorCatalan::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 114 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentaci dels Camps";
      }
      else
      {
        return "Documentaci de les Dades Membre";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorCatalan::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 106 of file translator_ca.h.
    { return "Documentaci de les Enumeracions Membre"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorCatalan::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 106 of file translator_ca.h.
    { return "Documentaci de les Enumeracions Membre"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorCatalan::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 110 of file translator_ca.h.
    { return "Documentaci de les Funcions Membre"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorCatalan::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 110 of file translator_ca.h.
    { return "Documentaci de les Funcions Membre"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorCatalan::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1536 of file translator_ca.h.
    { return "Documentaci de les Funcions/Subrutines Membre"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorCatalan::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1536 of file translator_ca.h.
    { return "Documentaci de les Funcions/Subrutines Membre"; }
trMemberList() [1/2]
virtual QCString TranslatorCatalan::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 135 of file translator_ca.h.
    { return "Llista dels Membres"; }
trMemberList() [2/2]
virtual QCString TranslatorCatalan::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 135 of file translator_ca.h.
    { return "Llista dels Membres"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorCatalan::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 102 of file translator_ca.h.
    { return "Documentaci de les Definicions de Tipus Membre"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorCatalan::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 102 of file translator_ca.h.
    { return "Documentaci de les Definicions de Tipus Membre"; }
trModule() [1/2]
virtual QCString TranslatorCatalan::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1678 of file translator_ca.h.
    {
      QCString result((first_capital ? "Mdul" : "mdul"));
      if (!singular) result+="s";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorCatalan::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1678 of file translator_ca.h.
    {
      QCString result((first_capital ? "Mdul" : "mdul"));
      if (!singular) result+="s";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorCatalan::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 387 of file translator_ca.h.
    { return "Documentaci dels Mduls"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorCatalan::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 387 of file translator_ca.h.
    { return "Documentaci dels Mduls"; }
trModuleIndex() [1/2]
virtual QCString TranslatorCatalan::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 354 of file translator_ca.h.
    { return "ndex de Mduls"; }
trModuleIndex() [2/2]
virtual QCString TranslatorCatalan::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 354 of file translator_ca.h.
    { return "ndex de Mduls"; }
trModuleReference() [1/2]
virtual QCString TranslatorCatalan::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1637 of file translator_ca.h.
    {
      QCString result="Referncia del Mdul ";
      result+=namespaceName;
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorCatalan::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1637 of file translator_ca.h.
    {
      QCString result="Referncia del Mdul ";
      result+=namespaceName;
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorCatalan::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 173 of file translator_ca.h.
    { return "Mduls"; }
trModules() [2/2]
virtual QCString TranslatorCatalan::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 173 of file translator_ca.h.
    { return "Mduls"; }
trModulesDescription() [1/2]
virtual QCString TranslatorCatalan::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 341 of file translator_ca.h.
    { return "Aquesta s la llista de mduls:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorCatalan::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 341 of file translator_ca.h.
    { return "Aquesta s la llista de mduls:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorCatalan::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1671 of file translator_ca.h.
    { return "ndex de Mduls"; }
trModulesIndex() [2/2]
virtual QCString TranslatorCatalan::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1671 of file translator_ca.h.
    { return "ndex de Mduls"; }
trModulesList() [1/2]
virtual QCString TranslatorCatalan::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1602 of file translator_ca.h.
    { return "Llista de Mduls"; }
trModulesList() [2/2]
virtual QCString TranslatorCatalan::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1602 of file translator_ca.h.
    { return "Llista de Mduls"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorCatalan::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1606 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els mduls ";
      if (!extractAll) result+="documentats ";
      result+="amb breus descripcions:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorCatalan::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1606 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els mduls ";
      if (!extractAll) result+="documentats ";
      result+="amb breus descripcions:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorCatalan::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1649 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els membres del mdul";
      if (!extractAll)
      {
        result+=" documentats";
      }
      result+=" amb enllaos a ";
      if (!extractAll)
      {
        result+="la documentaci del mdul per a cada membre:";
      }
      else
      {
        result+="els mduls a que pertanyen:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorCatalan::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1649 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els membres del mdul";
      if (!extractAll)
      {
        result+=" documentats";
      }
      result+=" amb enllaos a ";
      if (!extractAll)
      {
        result+="la documentaci del mdul per a cada membre:";
      }
      else
      {
        result+="els mduls a que pertanyen:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorCatalan::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1645 of file translator_ca.h.
    { return "Membres del Mdul"; }
trModulesMembers() [2/2]
virtual QCString TranslatorCatalan::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1645 of file translator_ca.h.
    { return "Membres del Mdul"; }
trMonth() [1/2]
virtual QCString TranslatorCatalan::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1830 of file translator_ca.h.
    {
      static const char *months_short[] = { "gen.", "febr.", "mar", "abr.", "maig", "juny", "jul.", "ag.", "set.", "oct.", "nov.", "des." };
      static const char *months_full[] = { "gener", "febrer", "mar", "abril", "maig", "juny", "juliol", "agost", "setembre", "octubre", "novembre", "desembre" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorCatalan::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1830 of file translator_ca.h.
    {
      static const char *months_short[] = { "gen.", "febr.", "mar", "abr.", "maig", "juny", "jul.", "ag.", "set.", "oct.", "nov.", "des." };
      static const char *months_full[] = { "gener", "febrer", "mar", "abril", "maig", "juny", "juliol", "agost", "setembre", "octubre", "novembre", "desembre" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorCatalan::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 127 of file translator_ca.h.
    { return "Ms..."; }
trMore() [2/2]
virtual QCString TranslatorCatalan::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 127 of file translator_ca.h.
    { return "Ms..."; }
trNamespace() [1/2]
virtual QCString TranslatorCatalan::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1213 of file translator_ca.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorCatalan::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1213 of file translator_ca.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorCatalan::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 733 of file translator_ca.h.
    { return "Documentaci de l'Espai de Noms"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorCatalan::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 733 of file translator_ca.h.
    { return "Documentaci de l'Espai de Noms"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorCatalan::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 727 of file translator_ca.h.
    { return "ndex d'Espais de Noms"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorCatalan::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 727 of file translator_ca.h.
    { return "ndex d'Espais de Noms"; }
trNamespaceList() [1/2]
virtual QCString TranslatorCatalan::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 560 of file translator_ca.h.
    { return "Llista dels Espais de Noms"; }
trNamespaceList() [2/2]
virtual QCString TranslatorCatalan::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 560 of file translator_ca.h.
    { return "Llista dels Espais de Noms"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorCatalan::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 564 of file translator_ca.h.
    {
      QCString result="Aquests sn tots els espais de noms ";
      if (!extractAll) result+="documentats ";
      result+="amb breus descripcions:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorCatalan::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 564 of file translator_ca.h.
    {
      QCString result="Aquests sn tots els espais de noms ";
      if (!extractAll) result+="documentats ";
      result+="amb breus descripcions:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorCatalan::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 713 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els membres de l'espai de noms ";
      if (!extractAll) result+="documentats ";
      result+="amb enllaos a ";
      if (extractAll)
        result+="la documentaci de l'espai de noms de cada membre:";
      else
        result+="l'espai de noms al qual corresponen:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorCatalan::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 713 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els membres de l'espai de noms ";
      if (!extractAll) result+="documentats ";
      result+="amb enllaos a ";
      if (extractAll)
        result+="la documentaci de l'espai de noms de cada membre:";
      else
        result+="l'espai de noms al qual corresponen:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorCatalan::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 709 of file translator_ca.h.
    { return "Membres de l'Espai de Noms"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorCatalan::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 709 of file translator_ca.h.
    { return "Membres de l'Espai de Noms"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorCatalan::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 623 of file translator_ca.h.
    {
      QCString result="Referncia de l'Espai de Noms ";
      result+=namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorCatalan::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 623 of file translator_ca.h.
    {
      QCString result="Referncia de l'Espai de Noms ";
      result+=namespaceName;
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorCatalan::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 743 of file translator_ca.h.
    { return "Espais de Noms"; }
trNamespaces() [2/2]
virtual QCString TranslatorCatalan::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 743 of file translator_ca.h.
    { return "Espais de Noms"; }
trNoMatches() [1/2]
virtual QCString TranslatorCatalan::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1769 of file translator_ca.h.
    {
      return "Cap coincidncia";
    }
trNoMatches() [2/2]
virtual QCString TranslatorCatalan::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1769 of file translator_ca.h.
    {
      return "Cap coincidncia";
    }
trNote() [1/2]
virtual QCString TranslatorCatalan::trNote () [inline], [virtual]
Implements Translator.
Definition at line 894 of file translator_ca.h.
    {
      return "Nota";
    }
trNote() [2/2]
virtual QCString TranslatorCatalan::trNote () [inline], [virtual]
Implements Translator.
Definition at line 894 of file translator_ca.h.
    {
      return "Nota";
    }
trOverloadText() [1/2]
virtual QCString TranslatorCatalan::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1508 of file translator_ca.h.
    {
       return "Aquesta s una funci membre sobrecarregada, "
              "proveda per convenincia. Es diferencia de la funci "
              "anterior noms en els arguments que accepta.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorCatalan::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1508 of file translator_ca.h.
    {
       return "Aquesta s una funci membre sobrecarregada, "
              "proveda per convenincia. Es diferencia de la funci "
              "anterior noms en els arguments que accepta.";
    }
trPackage() [1/2]
virtual QCString TranslatorCatalan::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1103 of file translator_ca.h.
    {
      return "Paquet "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorCatalan::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1103 of file translator_ca.h.
    {
      return "Paquet "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorCatalan::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1380 of file translator_ca.h.
    {
      return "Atributs de Paquet";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorCatalan::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1380 of file translator_ca.h.
    {
      return "Atributs de Paquet";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorCatalan::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1362 of file translator_ca.h.
    {
      return "Funcions de Paquet";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorCatalan::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1362 of file translator_ca.h.
    {
      return "Funcions de Paquet";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorCatalan::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1108 of file translator_ca.h.
    {
      return "Aquesta s la llista de paquets, amb una breu descripci (si se'n disposa):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorCatalan::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1108 of file translator_ca.h.
    {
      return "Aquesta s la llista de paquets, amb una breu descripci (si se'n disposa):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorCatalan::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1366 of file translator_ca.h.
    {
      return "Membres de Paquet";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorCatalan::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1366 of file translator_ca.h.
    {
      return "Membres de Paquet";
    }
trPackages() [1/2]
virtual QCString TranslatorCatalan::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1113 of file translator_ca.h.
    {
      return "Paquets";
    }
trPackages() [2/2]
virtual QCString TranslatorCatalan::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1113 of file translator_ca.h.
    {
      return "Paquets";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorCatalan::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1355 of file translator_ca.h.
    {
      return "Tipus de paquets";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorCatalan::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1355 of file translator_ca.h.
    {
      return "Tipus de paquets";
    }
trPage() [1/2]
virtual QCString TranslatorCatalan::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1235 of file translator_ca.h.
    {
      QCString result((first_capital ? "Pgin" : "pgin"));
      if (!singular) result+="es"; else result+="a";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorCatalan::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1235 of file translator_ca.h.
    {
      QCString result((first_capital ? "Pgin" : "pgin"));
      if (!singular) result+="es"; else result+="a";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorCatalan::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 794 of file translator_ca.h.
    { return "p."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorCatalan::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 794 of file translator_ca.h.
    { return "p."; }
trPageIndex() [1/2]
virtual QCString TranslatorCatalan::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_ca.h.
    {
      return "ndex de Pgines";
    }
trPageIndex() [2/2]
virtual QCString TranslatorCatalan::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_ca.h.
    {
      return "ndex de Pgines";
    }
trParameters() [1/2]
virtual QCString TranslatorCatalan::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 544 of file translator_ca.h.
    { return "Parmetres"; }
trParameters() [2/2]
virtual QCString TranslatorCatalan::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 544 of file translator_ca.h.
    { return "Parmetres"; }
trPostcondition() [1/2]
virtual QCString TranslatorCatalan::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 854 of file translator_ca.h.
    {
      return "Postcondici";
    }
trPostcondition() [2/2]
virtual QCString TranslatorCatalan::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 854 of file translator_ca.h.
    {
      return "Postcondici";
    }
trPrecondition() [1/2]
virtual QCString TranslatorCatalan::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 849 of file translator_ca.h.
    {
      return "Precondici";
    }
trPrecondition() [2/2]
virtual QCString TranslatorCatalan::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 849 of file translator_ca.h.
    {
      return "Precondici";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorCatalan::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 933 of file translator_ca.h.
    {
      return "Atributs Privats";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorCatalan::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 933 of file translator_ca.h.
    {
      return "Atributs Privats";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorCatalan::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_ca.h.
    { return "Mtodes Privats"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorCatalan::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_ca.h.
    { return "Mtodes Privats"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorCatalan::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 646 of file translator_ca.h.
    { return "Slots Privats"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorCatalan::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 646 of file translator_ca.h.
    { return "Slots Privats"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorCatalan::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 929 of file translator_ca.h.
    {
      return "Tipus Privats";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorCatalan::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 929 of file translator_ca.h.
    {
      return "Tipus Privats";
    }
trProperties() [1/2]
virtual QCString TranslatorCatalan::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1076 of file translator_ca.h.
    {
      return "Propietats";
    }
trProperties() [2/2]
virtual QCString TranslatorCatalan::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1076 of file translator_ca.h.
    {
      return "Propietats";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorCatalan::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1081 of file translator_ca.h.
    {
      return "Documentaci de les Propietats";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorCatalan::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1081 of file translator_ca.h.
    {
      return "Documentaci de les Propietats";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorCatalan::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 921 of file translator_ca.h.
    {
      return "Atributs Protegits";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorCatalan::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 921 of file translator_ca.h.
    {
      return "Atributs Protegits";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorCatalan::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 638 of file translator_ca.h.
    { return "Mtodes Protegits"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorCatalan::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 638 of file translator_ca.h.
    { return "Mtodes Protegits"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorCatalan::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_ca.h.
    { return "Slots Protegits"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorCatalan::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_ca.h.
    { return "Slots Protegits"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorCatalan::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 917 of file translator_ca.h.
    {
      return "Tipus Protegits";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorCatalan::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 917 of file translator_ca.h.
    {
      return "Tipus Protegits";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorCatalan::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Camps de Dades";
      }
      else
      {
        return "Atributs Pblics";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorCatalan::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Camps de Dades";
      }
      else
      {
        return "Atributs Pblics";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorCatalan::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 630 of file translator_ca.h.
    { return "Mtodes pblics"; }
trPublicMembers() [2/2]
virtual QCString TranslatorCatalan::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 630 of file translator_ca.h.
    { return "Mtodes pblics"; }
trPublicSlots() [1/2]
virtual QCString TranslatorCatalan::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 632 of file translator_ca.h.
    { return "Slots pblics"; }
trPublicSlots() [2/2]
virtual QCString TranslatorCatalan::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 632 of file translator_ca.h.
    { return "Slots pblics"; }
trPublicTypes() [1/2]
virtual QCString TranslatorCatalan::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 898 of file translator_ca.h.
    {
      return "Tipus Pblics";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorCatalan::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 898 of file translator_ca.h.
    {
      return "Tipus Pblics";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorCatalan::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 961 of file translator_ca.h.
    {
      return "Referenciat a";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorCatalan::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 961 of file translator_ca.h.
    {
      return "Referenciat a";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorCatalan::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 422 of file translator_ca.h.
    { return "Manual de Referncia"; }
trReferenceManual() [2/2]
virtual QCString TranslatorCatalan::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 422 of file translator_ca.h.
    { return "Manual de Referncia"; }
trReferences() [1/2]
virtual QCString TranslatorCatalan::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1283 of file translator_ca.h.
    {
      return "Referncies";
    }
trReferences() [2/2]
virtual QCString TranslatorCatalan::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1283 of file translator_ca.h.
    {
      return "Referncies";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorCatalan::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 695 of file translator_ca.h.
    {
      return "Reimplementat de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorCatalan::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 695 of file translator_ca.h.
    {
      return "Reimplementat de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorCatalan::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 703 of file translator_ca.h.
    {
      return "Reimplementat a "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorCatalan::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 703 of file translator_ca.h.
    {
      return "Reimplementat a "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorCatalan::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 585 of file translator_ca.h.
    { return "Documentaci de funcions amigues i relacionades"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorCatalan::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 585 of file translator_ca.h.
    { return "Documentaci de funcions amigues i relacionades"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorCatalan::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 90 of file translator_ca.h.
    { return "Funcions Associades"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorCatalan::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 90 of file translator_ca.h.
    { return "Funcions Associades"; }
trRelatedPages() [1/2]
virtual QCString TranslatorCatalan::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 224 of file translator_ca.h.
    { return "Pgines Relacionades"; }
trRelatedPages() [2/2]
virtual QCString TranslatorCatalan::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 224 of file translator_ca.h.
    { return "Pgines Relacionades"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorCatalan::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 337 of file translator_ca.h.
    { return "Aquesta s la llista de totes les pgines de documentaci associades:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorCatalan::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 337 of file translator_ca.h.
    { return "Aquesta s la llista de totes les pgines de documentaci associades:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorCatalan::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 94 of file translator_ca.h.
    { return "(Remarcar que aquestes funcions no sn funcions membre.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorCatalan::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 94 of file translator_ca.h.
    { return "(Remarcar que aquestes funcions no sn funcions membre.)"; }
trRemarks() [1/2]
virtual QCString TranslatorCatalan::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 965 of file translator_ca.h.
    {
      return "Remarca";
    }
trRemarks() [2/2]
virtual QCString TranslatorCatalan::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 965 of file translator_ca.h.
    {
      return "Remarca";
    }
trReturns() [1/2]
virtual QCString TranslatorCatalan::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 536 of file translator_ca.h.
    { return "Retorna"; }
trReturns() [2/2]
virtual QCString TranslatorCatalan::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 536 of file translator_ca.h.
    { return "Retorna"; }
trReturnValues() [1/2]
virtual QCString TranslatorCatalan::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 783 of file translator_ca.h.
    { return "Valors de retorn"; }
trReturnValues() [2/2]
virtual QCString TranslatorCatalan::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 783 of file translator_ca.h.
    { return "Valors de retorn"; }
trRTFansicp() [1/2]
virtual QCString TranslatorCatalan::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1167 of file translator_ca.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorCatalan::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1167 of file translator_ca.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorCatalan::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1176 of file translator_ca.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorCatalan::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1176 of file translator_ca.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorCatalan::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1182 of file translator_ca.h.
    {
      return "ndex";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorCatalan::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1182 of file translator_ca.h.
    {
      return "ndex";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorCatalan::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1315 of file translator_ca.h.
    {
      return "Taula de Continguts";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorCatalan::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1315 of file translator_ca.h.
    {
      return "Taula de Continguts";
    }
trSearch() [1/2]
virtual QCString TranslatorCatalan::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 232 of file translator_ca.h.
    { return "Cerca"; }
trSearch() [2/2]
virtual QCString TranslatorCatalan::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 232 of file translator_ca.h.
    { return "Cerca"; }
trSearching() [1/2]
virtual QCString TranslatorCatalan::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1763 of file translator_ca.h.
    {
      return "Cercant...";
    }
trSearching() [2/2]
virtual QCString TranslatorCatalan::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1763 of file translator_ca.h.
    {
      return "Cercant...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorCatalan::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1447 of file translator_ca.h.
    {
      return "Resultats:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorCatalan::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1447 of file translator_ca.h.
    {
      return "Resultats:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorCatalan::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1428 of file translator_ca.h.
    {
      if (numDocuments==0)
      {
        return "No s'ha trobat cap document.";
      }
      else if (numDocuments==1)
      {
        return "Trobat <b>1</b> document.";
      }
      else
      {
        return "Trobats <b>$num</b> documents. "
               "Mostrant els millors resultats primer.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorCatalan::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1428 of file translator_ca.h.
    {
      if (numDocuments==0)
      {
        return "No s'ha trobat cap document.";
      }
      else if (numDocuments==1)
      {
        return "Trobat <b>1</b> document.";
      }
      else
      {
        return "Trobats <b>$num</b> documents. "
               "Mostrant els millors resultats primer.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorCatalan::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1416 of file translator_ca.h.
    {
      return "Resultats de la Bsqueda";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorCatalan::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1416 of file translator_ca.h.
    {
      return "Resultats de la Bsqueda";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorCatalan::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 540 of file translator_ca.h.
    { return "Mireu tamb"; }
trSeeAlso() [2/2]
virtual QCString TranslatorCatalan::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 540 of file translator_ca.h.
    { return "Mireu tamb"; }
trSignals() [1/2]
virtual QCString TranslatorCatalan::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 634 of file translator_ca.h.
    { return "Senyals"; }
trSignals() [2/2]
virtual QCString TranslatorCatalan::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 634 of file translator_ca.h.
    { return "Senyals"; }
trSince() [1/2]
virtual QCString TranslatorCatalan::trSince () [inline], [virtual]
Implements Translator.
Definition at line 978 of file translator_ca.h.
    {
      return "Des de";
    }
trSince() [2/2]
virtual QCString TranslatorCatalan::trSince () [inline], [virtual]
Implements Translator.
Definition at line 978 of file translator_ca.h.
    {
      return "Des de";
    }
trSourceFile() [1/2]
virtual QCString TranslatorCatalan::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1458 of file translator_ca.h.
    {
      return "Fitxer de Codi " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorCatalan::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1458 of file translator_ca.h.
    {
      return "Fitxer de Codi " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorCatalan::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1387 of file translator_ca.h.
    {
      return "Atributs Esttics de Paquet";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorCatalan::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1387 of file translator_ca.h.
    {
      return "Atributs Esttics de Paquet";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorCatalan::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1373 of file translator_ca.h.
    {
      return "Funcions Esttiques de Paquet";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorCatalan::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1373 of file translator_ca.h.
    {
      return "Funcions Esttiques de Paquet";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorCatalan::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_ca.h.
    {
      return "Atributs Privats Esttics";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorCatalan::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_ca.h.
    {
      return "Atributs Privats Esttics";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorCatalan::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_ca.h.
    { return "Mtodes Privats Esttics"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorCatalan::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_ca.h.
    { return "Mtodes Privats Esttics"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorCatalan::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 925 of file translator_ca.h.
    {
      return "Atributs Protegits Esttics";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorCatalan::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 925 of file translator_ca.h.
    {
      return "Atributs Protegits Esttics";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorCatalan::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_ca.h.
    { return "Mtodes Protegits Esttics"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorCatalan::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_ca.h.
    { return "Mtodes Protegits Esttics"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorCatalan::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 913 of file translator_ca.h.
    {
      return "Atributs Pblics Esttics";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorCatalan::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 913 of file translator_ca.h.
    {
      return "Atributs Pblics Esttics";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorCatalan::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_ca.h.
    { return "Mtodes Pblics Esttics"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorCatalan::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_ca.h.
    { return "Mtodes Pblics Esttics"; }
trSubprogram() [1/2]
virtual QCString TranslatorCatalan::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1726 of file translator_ca.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram"));
      if (!singular) result+="es";
      else result+="a";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorCatalan::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1726 of file translator_ca.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram"));
      if (!singular) result+="es";
      else result+="a";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorCatalan::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1592 of file translator_ca.h.
    { return "Documentaci de les Funcions/Subrutines"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorCatalan::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1592 of file translator_ca.h.
    { return "Documentaci de les Funcions/Subrutines"; }
trSubprograms() [1/2]
virtual QCString TranslatorCatalan::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1586 of file translator_ca.h.
    { return "Funcions/Subrutines"; }
trSubprograms() [2/2]
virtual QCString TranslatorCatalan::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1586 of file translator_ca.h.
    { return "Funcions/Subrutines"; }
trTest() [1/2]
virtual QCString TranslatorCatalan::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1061 of file translator_ca.h.
    {
      return "Prova";
    }
trTest() [2/2]
virtual QCString TranslatorCatalan::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1061 of file translator_ca.h.
    {
      return "Prova";
    }
trTestList() [1/2]
virtual QCString TranslatorCatalan::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1066 of file translator_ca.h.
    {
      return "Llista de proves";
    }
trTestList() [2/2]
virtual QCString TranslatorCatalan::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1066 of file translator_ca.h.
    {
      return "Llista de proves";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorCatalan::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 139 of file translator_ca.h.
    { return "Aquesta s la llista complerta dels membres de "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorCatalan::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 139 of file translator_ca.h.
    { return "Aquesta s la llista complerta dels membres de "; }
trTodo() [1/2]
virtual QCString TranslatorCatalan::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 947 of file translator_ca.h.
    {
      return "Per fer";
    }
trTodo() [2/2]
virtual QCString TranslatorCatalan::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 947 of file translator_ca.h.
    {
      return "Per fer";
    }
trTodoList() [1/2]
virtual QCString TranslatorCatalan::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 952 of file translator_ca.h.
    {
      return "Llista de coses per fer";
    }
trTodoList() [2/2]
virtual QCString TranslatorCatalan::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 952 of file translator_ca.h.
    {
      return "Llista de coses per fer";
    }
trType() [1/2]
virtual QCString TranslatorCatalan::trType (bool first_capital, bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1716 of file translator_ca.h.
    {
      QCString result((first_capital ? "Tipus" : "tipus"));
      //if (!singular) result+="s";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorCatalan::trType (bool first_capital, bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1716 of file translator_ca.h.
    {
      QCString result((first_capital ? "Tipus" : "tipus"));
      //if (!singular) result+="s";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorCatalan::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1735 of file translator_ca.h.
    {
      return "Restriccions de Tipus";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorCatalan::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1735 of file translator_ca.h.
    {
      return "Restriccions de Tipus";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorCatalan::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 470 of file translator_ca.h.
    { return "Documentaci de les Definicions de Tipus"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorCatalan::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 470 of file translator_ca.h.
    { return "Documentaci de les Definicions de Tipus"; }
trTypedefs() [1/2]
virtual QCString TranslatorCatalan::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 434 of file translator_ca.h.
    { return "Definicions de Tipus"; }
trTypedefs() [2/2]
virtual QCString TranslatorCatalan::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 434 of file translator_ca.h.
    { return "Definicions de Tipus"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorCatalan::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1580 of file translator_ca.h.
    { return "Documentaci dels Tipus de Dades"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorCatalan::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1580 of file translator_ca.h.
    { return "Documentaci dels Tipus de Dades"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorCatalan::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 488 of file translator_ca.h.
    { return "Documentaci de les Variables"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorCatalan::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 488 of file translator_ca.h.
    { return "Documentaci de les Variables"; }
trVariables() [1/2]
virtual QCString TranslatorCatalan::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 452 of file translator_ca.h.
    { return "Variables"; }
trVariables() [2/2]
virtual QCString TranslatorCatalan::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 452 of file translator_ca.h.
    { return "Variables"; }
trVersion() [1/2]
virtual QCString TranslatorCatalan::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 528 of file translator_ca.h.
    { return "Versi"; }
trVersion() [2/2]
virtual QCString TranslatorCatalan::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 528 of file translator_ca.h.
    { return "Versi"; }
trWarning() [1/2]
virtual QCString TranslatorCatalan::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 524 of file translator_ca.h.
    { return "Atenci"; }
trWarning() [2/2]
virtual QCString TranslatorCatalan::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 524 of file translator_ca.h.
    { return "Atenci"; }
trWriteList() [1/2]
virtual QCString TranslatorCatalan::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 654 of file translator_ca.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" i ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorCatalan::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 654 of file translator_ca.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" i ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_ca.h
doxygen/src/translator_ca.h