FilterDecodeURL Class Reference
The implementation of the `decodeURL` filter The leading character is removed from the value in case it is a ^ or !.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `decodeURL` filter The leading character is removed from the value in case it is a ^ or !.
^ is used to encode a absolute URL
! is used to encode a relative URL
Definition at line 1561 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterDecodeURL::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1564 of file template.cpp.
    {
      if (v.isValid() && v.isString())
      {
        QCString s = v.toString();
        if (!s.isEmpty() && (s.at(0)=='^' || s.at(0)=='!'))
        {
          return s.mid(1);
        }
      }
      return v;
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), s, and TemplateVariant::toString().
apply() [2/2]
static TemplateVariant FilterDecodeURL::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1564 of file template.cpp.
    {
      if (v.isValid() && v.isString())
      {
        QCString s = v.toString();
        if (!s.isEmpty() && (s.at(0)=='^' || s.at(0)=='!'))
        {
          return s.mid(1);
        }
      }
      return v;
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), s, and TemplateVariant::toString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp