DirListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
DirListContext ()
virtual ~DirListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
DirListContext ()
virtual ~DirListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc ()
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 648 of file context.h.
Constructor & Destructor Documentation
DirListContext() [1/2]
DirListContext::DirListContext ()
Definition at line 6400 of file context.cpp.
                               : p(std::make_unique<Private>())
{
}
 DirListContext() [1/2]
DirListContext::~DirListContext () [virtual]
Definition at line 6404 of file context.cpp.
{
}
DirListContext() [2/2]
DirListContext::DirListContext ()
 DirListContext() [2/2]
virtual DirListContext::~DirListContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr DirListContext::alloc () [inline], [static]
Definition at line 651 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<DirListContext>()); }
Referenced by generateOutputViaTemplate().
alloc() [2/2]
static TemplateListIntfPtr DirListContext::alloc () [inline], [static]
Definition at line 651 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<DirListContext>()); }
at() [1/2]
TemplateVariant DirListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 6414 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant DirListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t DirListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 6409 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t DirListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr DirListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 6419 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr DirListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > DirListContext::p [private]
Definition at line 664 of file context.h.
Referenced by at(), count(), and createIterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp