DocHRef Class Reference
#include <docnode.h>
Public Member Functions
DocHRef (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, const QCString &url, const QCString &relPath, const QCString &file)
int parse (DocNodeVariant *)
QCString url () const
QCString file () const
QCString relPath () const
const HtmlAttribList & attribs () const
DocHRef (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, const QCString &url, const QCString &relPath, const QCString &file)
int parse (DocNodeVariant *)
QCString url () const
QCString file () const
QCString relPath () const
const HtmlAttribList & attribs () const
Private Attributes
HtmlAttribList m_attribs
QCString m_url
QCString m_relPath
QCString m_file
Additional Inherited Members
Detailed Description
Node representing a Hypertext reference
Definition at line 775 of file docnode.h.
Constructor & Destructor Documentation
DocHRef() [1/2]
DocHRef::DocHRef (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, const QCString & url, const QCString & relPath, const QCString & file) [inline]
Definition at line 778 of file docnode.h.
    : DocCompoundNode(parser,parent), m_attribs(attribs), m_url(url),
      m_relPath(relPath), m_file(file) {}
DocHRef() [2/2]
DocHRef::DocHRef (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, const QCString & url, const QCString & relPath, const QCString & file) [inline]
Definition at line 778 of file docnode.h.
    : DocCompoundNode(parser,parent), m_attribs(attribs), m_url(url),
      m_relPath(relPath), m_file(file) {}
Member Function Documentation
attribs() [1/2]
const HtmlAttribList & DocHRef::attribs () const [inline]
Definition at line 786 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by HtmlDocVisitor::operator()().
attribs() [2/2]
const HtmlAttribList & DocHRef::attribs () const [inline]
Definition at line 786 of file docnode.h.
{ return m_attribs; }
References m_attribs.
file() [1/2]
QCString DocHRef::file () const [inline]
Definition at line 784 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), DocbookDocVisitor::operator()(), RTFDocVisitor::operator()(), and doxmlparser.compound.locationType::set_file().
file() [2/2]
QCString DocHRef::file () const [inline]
Definition at line 784 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), and doxmlparser.compound.locationType::set_file().
parse() [1/2]
int DocHRef::parse (DocNodeVariant * thisVariant)
Definition at line 1349 of file docnode.cpp.
{
  int retval=RetVal_OK;
  auto ns = AutoNodeStack(parser(),thisVariant);
  DBG(("DocHRef::parse() start\n"));
  int tok;
  while ((tok=parser()->tokenizer.lex()))
  {
    if (!parser()->defaultHandleToken(thisVariant,tok,children()))
    {
      switch (tok)
      {
        case TK_HTMLTAG:
          {
            int tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
            if (tagId==HTML_A && parser()->context.token->endTag) // found </a> tag
            {
              goto endhref;
            }
            else if (tagId==HTML_BR)
            {
              children().append<DocLineBreak>(parser(),thisVariant,parser()->context.token->attribs);
            }
            else
            {
              warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected html tag <%s%s> found within <a href=...> context",
                  parser()->context.token->endTag?"/":"",qPrint(parser()->context.token->name));
            }
          }
          break;
        default:
          parser()->errorHandleDefaultToken(thisVariant,tok,children(),"<a>..</a> block");
          break;
      }
    }
  }
  if (tok==0)
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected end of comment while inside"
           " <a href=...> tag");
  }
endhref:
  parser()->handlePendingStyleCommands(thisVariant,children());
  DBG(("DocHRef::parse() end\n"));
  return retval;
}
References DocNodeList::append(), TokenInfo::attribs, DocCompoundNode::children(), DocParser::context, DBG, DocParser::errorHandleDefaultToken(), DocParser::handlePendingStyleCommands(), HTML_A, HTML_BR, Mappers::htmlTagMapper, Mapper::map(), DocNode::parser(), qPrint(), RetVal_OK, TK_HTMLTAG, DocParserContext::token, and warn_doc_error().
parse() [2/2]
int DocHRef::parse (DocNodeVariant *)
relPath() [1/2]
QCString DocHRef::relPath () const [inline]
Definition at line 785 of file docnode.h.
{ return m_relPath; }
References m_relPath.
Referenced by HtmlDocVisitor::operator()().
relPath() [2/2]
QCString DocHRef::relPath () const [inline]
Definition at line 785 of file docnode.h.
{ return m_relPath; }
References m_relPath.
url() [1/2]
QCString DocHRef::url () const [inline]
Definition at line 783 of file docnode.h.
{ return m_url; }
References m_url.
Referenced by doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docURLLink::buildAttributes(), doxmlparser.compound.docURLLink::exportAttributes(), doxmlparser.compound.docURLLink::get_url(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), and doxmlparser.compound.docURLLink::set_url().
url() [2/2]
QCString DocHRef::url () const [inline]
Definition at line 783 of file docnode.h.
{ return m_url; }
References m_url.
Referenced by doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docURLLink::buildAttributes(), doxmlparser.compound.docURLLink::exportAttributes(), doxmlparser.compound.docURLLink::get_url(), and doxmlparser.compound.docURLLink::set_url().
Member Data Documentation
m_attribs
HtmlAttribList DocHRef::m_attribs [private]
Definition at line 789 of file docnode.h.
Referenced by attribs().
m_file
QCString DocHRef::m_file [private]
Definition at line 792 of file docnode.h.
Referenced by file().
m_relPath
QCString DocHRef::m_relPath [private]
Definition at line 791 of file docnode.h.
Referenced by relPath().
m_url
QCString DocHRef::m_url [private]
Definition at line 790 of file docnode.h.
Referenced by url().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp