DefinitionMutable Class Reference
#include <definition.h>
Public Member Functions
virtual void setName (const QCString &name)=0
virtual void setId (const QCString &name)=0
virtual void setDefFile (const QCString &df, int defLine, int defColumn)=0
virtual void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)=0
virtual void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)=0
virtual void setInbodyDocumentation (const QCString &d, const QCString &docFile, int docLine)=0
virtual void setReference (const QCString &r)=0
virtual void setBodySegment (int defLine, int bls, int ble)=0
virtual void setBodyDef (const FileDef *fd)=0
virtual void setRefItems (const RefItemVector &sli)=0
virtual void setOuterScope (Definition *d)=0
virtual void setHidden (bool b)=0
virtual void setArtificial (bool b)=0
virtual void setLanguage (SrcLangExt lang)=0
virtual void setLocalName (const QCString &name)=0
virtual void makePartOfGroup (const GroupDef *gd)=0
virtual void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)=0
virtual void addSourceReferencedBy (const MemberDef *d)=0
virtual void addSourceReferences (const MemberDef *d)=0
virtual void mergeRefItems (Definition *d)=0
virtual void addInnerCompound (const Definition *d)=0
virtual void addSectionsToIndex ()=0
virtual void mergeReferences (const Definition *other)=0
virtual void mergeReferencedBy (const Definition *other)=0
virtual void computeTooltip ()=0
virtual void writeSourceDef (OutputList &ol, const QCString &scopeName) const =0
virtual void writeInlineCode (OutputList &ol, const QCString &scopeName) const =0
virtual bool hasSourceRefs () const =0
virtual bool hasSourceReffedBy () const =0
virtual void writeSourceRefs (OutputList &ol, const QCString &scopeName) const =0
virtual void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const =0
virtual void writeNavigationPath (OutputList &ol) const =0
virtual void writeQuickMemberLinks (OutputList &, const MemberDef *) const =0
virtual void writeSummaryLinks (OutputList &) const =0
virtual void writeDocAnchorsToTagFile (TextStream &) const =0
virtual void writeToc (OutputList &ol, const LocalToc &lt) const =0
virtual ~DefinitionMutable ()=default
virtual void setName (const QCString &name)=0
virtual void setId (const QCString &name)=0
virtual void setDefFile (const QCString &df, int defLine, int defColumn)=0
virtual void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)=0
virtual void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)=0
virtual void setInbodyDocumentation (const QCString &d, const QCString &docFile, int docLine)=0
virtual void setReference (const QCString &r)=0
virtual void setBodySegment (int defLine, int bls, int ble)=0
virtual void setBodyDef (const FileDef *fd)=0
virtual void setRefItems (const RefItemVector &sli)=0
virtual void setOuterScope (Definition *d)=0
virtual void setHidden (bool b)=0
virtual void setArtificial (bool b)=0
virtual void setLanguage (SrcLangExt lang)=0
virtual void setLocalName (const QCString &name)=0
virtual void makePartOfGroup (const GroupDef *gd)=0
virtual void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)=0
virtual void addSourceReferencedBy (const MemberDef *d)=0
virtual void addSourceReferences (const MemberDef *d)=0
virtual void mergeRefItems (Definition *d)=0
virtual void addInnerCompound (const Definition *d)=0
virtual void addSectionsToIndex ()=0
virtual void mergeReferences (const Definition *other)=0
virtual void mergeReferencedBy (const Definition *other)=0
virtual void computeTooltip ()=0
virtual void writeSourceDef (OutputList &ol, const QCString &scopeName) const =0
virtual void writeInlineCode (OutputList &ol, const QCString &scopeName) const =0
virtual bool hasSourceRefs () const =0
virtual bool hasSourceReffedBy () const =0
virtual void writeSourceRefs (OutputList &ol, const QCString &scopeName) const =0
virtual void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const =0
virtual void writeNavigationPath (OutputList &ol) const =0
virtual void writeQuickMemberLinks (OutputList &, const MemberDef *) const =0
virtual void writeSummaryLinks (OutputList &) const =0
virtual void writeDocAnchorsToTagFile (TextStream &) const =0
virtual void writeToc (OutputList &ol, const LocalToc &lt) const =0
virtual ~DefinitionMutable ()=default
Private Member Functions
virtual Definition * toDefinition_ ()=0
virtual Definition * toDefinition_ ()=0
Friends
Definition * toDefinition (DefinitionMutable *)
Definition * toDefinition (DefinitionMutable *)
Detailed Description
Definition at line 303 of file definition.h.
Constructor & Destructor Documentation
 DefinitionMutable() [1/2]
virtual DefinitionMutable::~DefinitionMutable () [virtual], [default]
 DefinitionMutable() [2/2]
virtual DefinitionMutable::~DefinitionMutable () [virtual], [default]
Member Function Documentation
addInnerCompound() [1/2]
virtual void DefinitionMutable::addInnerCompound (const Definition * d) [pure virtual]
Implemented in PageDef, PageDef, ClassDefImpl, NamespaceDefImpl, PageDefImpl, ClassDefImpl, NamespaceDefImpl, PageDefImpl, ClassDefMutable, NamespaceDefMutable, ClassDefMutable, NamespaceDefMutable, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addConceptToContext(), buildNamespaceList(), buildScopeFromQualifiedName(), createTagLessInstance(), and resolveClassNestingRelations().
addInnerCompound() [2/2]
virtual void DefinitionMutable::addInnerCompound (const Definition * d) [pure virtual]
Implemented in PageDef, PageDef, ClassDefImpl, NamespaceDefImpl, PageDefImpl, ClassDefImpl, NamespaceDefImpl, PageDefImpl, ClassDefMutable, NamespaceDefMutable, ClassDefMutable, NamespaceDefMutable, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
addSectionsToDefinition() [1/2]
virtual void DefinitionMutable::addSectionsToDefinition (const std::vector< const SectionInfo * > & anchorList) [pure virtual]
Add the list of anchors that mark the sections that are found in the documentation.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addClassToContext(), addConceptToContext(), addEnumDocs(), addEnumValuesToEnums(), addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), addRelatedPage(), buildExampleList(), buildFileList(), buildGroupListFiltered(), buildNamespaceList(), findDefineDocumentation(), findEnums(), findMember(), and findUsingDirectives().
addSectionsToDefinition() [2/2]
virtual void DefinitionMutable::addSectionsToDefinition (const std::vector< const SectionInfo * > & anchorList) [pure virtual]
Add the list of anchors that mark the sections that are found in the documentation.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
addSectionsToIndex() [1/2]
virtual void DefinitionMutable::addSectionsToIndex () [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
addSectionsToIndex() [2/2]
virtual void DefinitionMutable::addSectionsToIndex () [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
addSourceReferencedBy() [1/2]
virtual void DefinitionMutable::addSourceReferencedBy (const MemberDef * d) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addDocCrossReference().
addSourceReferencedBy() [2/2]
virtual void DefinitionMutable::addSourceReferencedBy (const MemberDef * d) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
addSourceReferences() [1/2]
virtual void DefinitionMutable::addSourceReferences (const MemberDef * d) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addDocCrossReference().
addSourceReferences() [2/2]
virtual void DefinitionMutable::addSourceReferences (const MemberDef * d) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
computeTooltip() [1/2]
virtual void DefinitionMutable::computeTooltip () [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by computeTooltipTexts().
computeTooltip() [2/2]
virtual void DefinitionMutable::computeTooltip () [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
hasSourceReffedBy() [1/2]
virtual bool DefinitionMutable::hasSourceReffedBy () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
hasSourceReffedBy() [2/2]
virtual bool DefinitionMutable::hasSourceReffedBy () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
hasSourceRefs() [1/2]
virtual bool DefinitionMutable::hasSourceRefs () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
hasSourceRefs() [2/2]
virtual bool DefinitionMutable::hasSourceRefs () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
makePartOfGroup() [1/2]
virtual void DefinitionMutable::makePartOfGroup (const GroupDef * gd) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addClassToGroups(), addConceptToGroups(), addDirToGroups(), addExampleToGroups(), addGroupToGroups(), addNamespaceToGroups(), buildFileList(), createTagLessInstance(), distributeClassGroupRelations(), and distributeConceptGroups().
makePartOfGroup() [2/2]
virtual void DefinitionMutable::makePartOfGroup (const GroupDef * gd) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
mergeReferencedBy() [1/2]
virtual void DefinitionMutable::mergeReferencedBy (const Definition * other) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by transferFunctionReferences().
mergeReferencedBy() [2/2]
virtual void DefinitionMutable::mergeReferencedBy (const Definition * other) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
mergeReferences() [1/2]
virtual void DefinitionMutable::mergeReferences (const Definition * other) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by transferFunctionReferences().
mergeReferences() [2/2]
virtual void DefinitionMutable::mergeReferences (const Definition * other) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
mergeRefItems() [1/2]
virtual void DefinitionMutable::mergeRefItems (Definition * d) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by combineDeclarationAndDefinition().
mergeRefItems() [2/2]
virtual void DefinitionMutable::mergeRefItems (Definition * d) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setArtificial() [1/2]
virtual void DefinitionMutable::setArtificial (bool b) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addClassToContext(), buildNamespaceList(), buildScopeFromQualifiedName(), findClassRelation(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsingDeclarations(), findUsingDirectives(), ClassDefImpl::insertTemplateInstance(), and ClassDefImpl::mergeCategory().
setArtificial() [2/2]
virtual void DefinitionMutable::setArtificial (bool b) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setBodyDef() [1/2]
virtual void DefinitionMutable::setBodyDef (const FileDef * fd) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addClassToContext(), addConceptToContext(), addInstance(), addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), buildNamespaceList(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberDefImpl::createTemplateInstanceMember(), findDefineDocumentation(), findEnums(), and findMember().
setBodyDef() [2/2]
virtual void DefinitionMutable::setBodyDef (const FileDef * fd) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setBodySegment() [1/2]
virtual void DefinitionMutable::setBodySegment (int defLine, int bls, int ble) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addClassToContext(), addConceptToContext(), addInstance(), addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), addRelatedPage(), buildNamespaceList(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberDefImpl::createTemplateInstanceMember(), findDefineDocumentation(), findEnums(), and findMember().
setBodySegment() [2/2]
virtual void DefinitionMutable::setBodySegment (int defLine, int bls, int ble) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setBriefDescription() [1/2]
virtual void DefinitionMutable::setBriefDescription (const QCString & b, const QCString & briefFile, int briefLine) [pure virtual]
Sets the brief description of this definition to b. A dot is added to the sentence if not available.
Implemented in MemberDefImpl, MemberDefImpl, MemberDefMutable, MemberDefMutable, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addClassToContext(), addConceptToContext(), addRelatedPage(), addVariableToFile(), buildExampleList(), buildFileList(), buildGroupListFiltered(), buildNamespaceList(), createTagLessInstance(), findDirDocumentation(), and findUsingDirectives().
setBriefDescription() [2/2]
virtual void DefinitionMutable::setBriefDescription (const QCString & b, const QCString & briefFile, int briefLine) [pure virtual]
Sets the brief description of this definition to b. A dot is added to the sentence if not available.
Implemented in MemberDefImpl, MemberDefImpl, MemberDefMutable, MemberDefMutable, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setDefFile() [1/2]
virtual void DefinitionMutable::setDefFile (const QCString & df, int defLine, int defColumn) [pure virtual]
Set a new file name and position
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addClassToContext(), and buildNamespaceList().
setDefFile() [2/2]
virtual void DefinitionMutable::setDefFile (const QCString & df, int defLine, int defColumn) [pure virtual]
Set a new file name and position
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setDocumentation() [1/2]
virtual void DefinitionMutable::setDocumentation (const QCString & d, const QCString & docFile, int docLine, bool stripWhiteSpace = TRUE) [pure virtual]
Sets the documentation of this definition to d.
Implemented in MemberDefImpl, MemberDefImpl, MemberDefMutable, MemberDefMutable, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addClassToContext(), addConceptToContext(), addRelatedPage(), addVariableToFile(), buildFileList(), buildGroupListFiltered(), buildNamespaceList(), createTagLessInstance(), findDirDocumentation(), and findUsingDirectives().
setDocumentation() [2/2]
virtual void DefinitionMutable::setDocumentation (const QCString & d, const QCString & docFile, int docLine, bool stripWhiteSpace = TRUE) [pure virtual]
Sets the documentation of this definition to d.
Implemented in MemberDefImpl, MemberDefImpl, MemberDefMutable, MemberDefMutable, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setHidden() [1/2]
virtual void DefinitionMutable::setHidden (bool b) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, MemberDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, MemberDefImpl, MemberDefMutable, and MemberDefMutable.
Referenced by addClassToContext(), addConceptToContext(), buildNamespaceList(), findUsingDirectives(), and ClassDefImpl::insertTemplateInstance().
setHidden() [2/2]
virtual void DefinitionMutable::setHidden (bool b) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, MemberDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, MemberDefImpl, MemberDefMutable, and MemberDefMutable.
setId() [1/2]
virtual void DefinitionMutable::setId (const QCString & name) [pure virtual]
Sets a unique id for the symbol. Used for libclang integration.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addClassToContext(), addConceptToContext(), addEnumValuesToEnums(), addLocalObjCMethod(), addMemberSpecialization(), addOverloaded(), buildNamespaceList(), findEnums(), findMember(), and findUsingDirectives().
setId() [2/2]
virtual void DefinitionMutable::setId (const QCString & name) [pure virtual]
Sets a unique id for the symbol. Used for libclang integration.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setInbodyDocumentation() [1/2]
virtual void DefinitionMutable::setInbodyDocumentation (const QCString & d, const QCString & docFile, int docLine) [pure virtual]
Set the documentation that was found inside the body of an item. If there was already some documentation set, the new documentation will be appended.
Implemented in MemberDefImpl, MemberDefImpl, MemberDefMutable, MemberDefMutable, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by buildGroupListFiltered().
setInbodyDocumentation() [2/2]
virtual void DefinitionMutable::setInbodyDocumentation (const QCString & d, const QCString & docFile, int docLine) [pure virtual]
Set the documentation that was found inside the body of an item. If there was already some documentation set, the new documentation will be appended.
Implemented in MemberDefImpl, MemberDefImpl, MemberDefMutable, MemberDefMutable, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setLanguage() [1/2]
virtual void DefinitionMutable::setLanguage (SrcLangExt lang) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addClassToContext(), addConceptToContext(), addEnumValuesToEnums(), addInstance(), addLocalObjCMethod(), addMemberSpecialization(), addOverloaded(), addRelatedPage(), ClassDefImpl::addTypeConstraint(), buildExampleList(), buildGroupListFiltered(), buildNamespaceList(), buildScopeFromQualifiedName(), createTagLessInstance(), findClassRelation(), findDefineDocumentation(), findEnums(), findMember(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsingDeclarations(), and findUsingDirectives().
setLanguage() [2/2]
virtual void DefinitionMutable::setLanguage (SrcLangExt lang) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setLocalName() [1/2]
virtual void DefinitionMutable::setLocalName (const QCString & name) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setLocalName() [2/2]
virtual void DefinitionMutable::setLocalName (const QCString & name) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setName() [1/2]
virtual void DefinitionMutable::setName (const QCString & name) [pure virtual]
Sets a new name for the definition
Implemented in ClassDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, ClassDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, ClassDefMutable, and ClassDefMutable.
Referenced by buildNamespaceList(), and VhdlDocGen::correctMemberProperties().
setName() [2/2]
virtual void DefinitionMutable::setName (const QCString & name) [pure virtual]
Sets a new name for the definition
Implemented in ClassDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, ClassDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, ClassDefMutable, and ClassDefMutable.
setOuterScope() [1/2]
virtual void DefinitionMutable::setOuterScope (Definition * d) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addConceptToContext(), addEnumValuesToEnums(), PageDefImpl::addInnerCompound(), DirDefImpl::addSubDir(), buildNamespaceList(), buildScopeFromQualifiedName(), createTagLessInstance(), findClassRelation(), NamespaceDefImpl::insertMember(), ClassDefImpl::insertTemplateInstance(), and resolveClassNestingRelations().
setOuterScope() [2/2]
virtual void DefinitionMutable::setOuterScope (Definition * d) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setReference() [1/2]
virtual void DefinitionMutable::setReference (const QCString & r) [pure virtual]
Sets the tag file id via which this definition was imported.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addRelatedPage(), buildGroupListFiltered(), and buildNamespaceList().
setReference() [2/2]
virtual void DefinitionMutable::setReference (const QCString & r) [pure virtual]
Sets the tag file id via which this definition was imported.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
setRefItems() [1/2]
virtual void DefinitionMutable::setRefItems (const RefItemVector & sli) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by addClassToContext(), addConceptToContext(), addEnumDocs(), addEnumValuesToEnums(), addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), addRelatedPage(), addVariableToFile(), buildFileList(), buildGroupListFiltered(), buildNamespaceList(), findDefineDocumentation(), findDirDocumentation(), findEnums(), findMember(), and findUsingDirectives().
setRefItems() [2/2]
virtual void DefinitionMutable::setRefItems (const RefItemVector & sli) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
toDefinition_() [1/2]
virtual Definition * DefinitionMutable::toDefinition_ () [private], [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by toDefinition().
toDefinition_() [2/2]
virtual Definition * DefinitionMutable::toDefinition_ () [private], [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
writeDocAnchorsToTagFile() [1/2]
virtual void DefinitionMutable::writeDocAnchorsToTagFile (TextStream &) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by VhdlDocGen::writeTagFile().
writeDocAnchorsToTagFile() [2/2]
virtual void DefinitionMutable::writeDocAnchorsToTagFile (TextStream &) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
writeInlineCode() [1/2]
virtual void DefinitionMutable::writeInlineCode (OutputList & ol, const QCString & scopeName) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
writeInlineCode() [2/2]
virtual void DefinitionMutable::writeInlineCode (OutputList & ol, const QCString & scopeName) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
writeNavigationPath() [1/2]
virtual void DefinitionMutable::writeNavigationPath (OutputList & ol) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), and FileDefImpl::writeSourceHeader().
writeNavigationPath() [2/2]
virtual void DefinitionMutable::writeNavigationPath (OutputList & ol) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
writeQuickMemberLinks() [1/2]
virtual void DefinitionMutable::writeQuickMemberLinks (OutputList & , const MemberDef *) const [pure virtual]
Implemented in FileDefImpl, GroupDefImpl, NamespaceDefImpl, FileDefImpl, GroupDefImpl, NamespaceDefImpl, FileDef, GroupDef, NamespaceDefMutable, FileDef, GroupDef, NamespaceDefMutable, ClassDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, ClassDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, ClassDefMutable, and ClassDefMutable.
writeQuickMemberLinks() [2/2]
virtual void DefinitionMutable::writeQuickMemberLinks (OutputList & , const MemberDef *) const [pure virtual]
Implemented in FileDefImpl, GroupDefImpl, NamespaceDefImpl, FileDefImpl, GroupDefImpl, NamespaceDefImpl, FileDef, GroupDef, NamespaceDefMutable, FileDef, GroupDef, NamespaceDefMutable, ClassDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, ClassDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, ClassDefMutable, and ClassDefMutable.
writeSourceDef() [1/2]
virtual void DefinitionMutable::writeSourceDef (OutputList & ol, const QCString & scopeName) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by VhdlDocGen::writeSource().
writeSourceDef() [2/2]
virtual void DefinitionMutable::writeSourceDef (OutputList & ol, const QCString & scopeName) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
writeSourceReffedBy() [1/2]
virtual void DefinitionMutable::writeSourceReffedBy (OutputList & ol, const QCString & scopeName) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by VhdlDocGen::writeSource().
writeSourceReffedBy() [2/2]
virtual void DefinitionMutable::writeSourceReffedBy (OutputList & ol, const QCString & scopeName) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
writeSourceRefs() [1/2]
virtual void DefinitionMutable::writeSourceRefs (OutputList & ol, const QCString & scopeName) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Referenced by VhdlDocGen::writeSource().
writeSourceRefs() [2/2]
virtual void DefinitionMutable::writeSourceRefs (OutputList & ol, const QCString & scopeName) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
writeSummaryLinks() [1/2]
virtual void DefinitionMutable::writeSummaryLinks (OutputList &) const [pure virtual]
Implemented in ClassDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, FileDefImpl, GroupDefImpl, NamespaceDefImpl, ClassDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, FileDefImpl, GroupDefImpl, NamespaceDefImpl, ClassDefMutable, FileDef, ClassDefMutable, and FileDef.
Referenced by startTitle().
writeSummaryLinks() [2/2]
virtual void DefinitionMutable::writeSummaryLinks (OutputList &) const [pure virtual]
Implemented in ClassDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, FileDefImpl, GroupDefImpl, NamespaceDefImpl, ClassDefImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, FileDefImpl, GroupDefImpl, NamespaceDefImpl, ClassDefMutable, FileDef, ClassDefMutable, and FileDef.
writeToc() [1/2]
virtual void DefinitionMutable::writeToc (OutputList & ol, const LocalToc & lt) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
writeToc() [2/2]
virtual void DefinitionMutable::writeToc (OutputList & ol, const LocalToc & lt) const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, and DefinitionMixin< PageDef >.
Friends And Related Function Documentation
toDefinition [1/2]
Definition * toDefinition (DefinitionMutable *) [friend]
Definition at line 1952 of file definition.cpp.
{
  if (dm==0) return 0;
  return dm->toDefinition_();
}
Referenced by toClassDef(), and toMemberDef().
toDefinition [2/2]
Definition * toDefinition (DefinitionMutable *) [friend]
Definition at line 1952 of file definition.cpp.
{
  if (dm==0) return 0;
  return dm->toDefinition_();
}
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/definition.h
doxygen/src/definition.h