TranslatorVietnamese Class Reference
#include <translator_vi.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString latexFontenc ()
virtual QCString latexCommandName ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString latexFontenc ()
virtual QCString latexCommandName ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
Additional Inherited Members
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include `translator.h` or `translator_adapter.h` here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 50 of file translator_vi.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorVietnamese::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 102 of file translator_vi.h.
    {
      return "0x42A Vietnamese";
    }
getLanguageString() [2/2]
virtual QCString TranslatorVietnamese::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 102 of file translator_vi.h.
    {
      return "0x42A Vietnamese";
    }
idLanguage() [1/2]
virtual QCString TranslatorVietnamese::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 62 of file translator_vi.h.
    { return "vietnamese"; }
idLanguage() [2/2]
virtual QCString TranslatorVietnamese::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 62 of file translator_vi.h.
    { return "vietnamese"; }
latexCommandName() [1/2]
virtual QCString TranslatorVietnamese::latexCommandName () [inline], [virtual]
Set the name to be used as latex command.
Reimplemented from Translator.
Definition at line 88 of file translator_vi.h.
    {
      QCString latex_command = Config_getString(LATEX_CMD_NAME);
      if (latex_command.isEmpty()) latex_command = "latex";
      if (Config_getBool(USE_PDFLATEX))
      {
        if (latex_command == "latex") latex_command = "xelatex";
      }
      return latex_command;
    }
References Config_getBool, Config_getString, and QCString::isEmpty().
latexCommandName() [2/2]
virtual QCString TranslatorVietnamese::latexCommandName () [inline], [virtual]
Set the name to be used as latex command.
Reimplemented from Translator.
Definition at line 88 of file translator_vi.h.
    {
      QCString latex_command = Config_getString(LATEX_CMD_NAME);
      if (latex_command.isEmpty()) latex_command = "latex";
      if (Config_getBool(USE_PDFLATEX))
      {
        if (latex_command == "latex") latex_command = "xelatex";
      }
      return latex_command;
    }
References Config_getBool, Config_getString, and QCString::isEmpty().
latexFontenc() [1/2]
virtual QCString TranslatorVietnamese::latexFontenc () [inline], [virtual]
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 84 of file translator_vi.h.
    {
      return "";
    }
latexFontenc() [2/2]
virtual QCString TranslatorVietnamese::latexFontenc () [inline], [virtual]
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 84 of file translator_vi.h.
    {
      return "";
    }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorVietnamese::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 79 of file translator_vi.h.
    {
      return
        "\\usepackage[vietnamese]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorVietnamese::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 79 of file translator_vi.h.
    {
      return
        "\\usepackage[vietnamese]{babel}\n";
    }
trAll() [1/2]
virtual QCString TranslatorVietnamese::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1419 of file translator_vi.h.
    {
      return "Tt c";
    }
trAll() [2/2]
virtual QCString TranslatorVietnamese::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1419 of file translator_vi.h.
    {
      return "Tt c";
    }
trAttention() [1/2]
virtual QCString TranslatorVietnamese::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 983 of file translator_vi.h.
    {
      return "Ch ";
    }
trAttention() [2/2]
virtual QCString TranslatorVietnamese::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 983 of file translator_vi.h.
    {
      return "Ch ";
    }
trAuthor() [1/2]
virtual QCString TranslatorVietnamese::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1290 of file translator_vi.h.
    {
      QCString result((first_capital ? "Tc gi" : "tc gi"));
      if (!singular) result+="";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorVietnamese::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1290 of file translator_vi.h.
    {
      QCString result((first_capital ? "Tc gi" : "tc gi"));
      if (!singular) result+="";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorVietnamese::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1148 of file translator_vi.h.
    {
      return "Li";
    }
trBug() [2/2]
virtual QCString TranslatorVietnamese::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1148 of file translator_vi.h.
    {
      return "Li";
    }
trBugList() [1/2]
virtual QCString TranslatorVietnamese::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1153 of file translator_vi.h.
    {
      return "Danh sch li";
    }
trBugList() [2/2]
virtual QCString TranslatorVietnamese::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1153 of file translator_vi.h.
    {
      return "Danh sch li";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorVietnamese::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1539 of file translator_vi.h.
    {
      return "Biu cc li gi cho hm ny:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorVietnamese::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1539 of file translator_vi.h.
    {
      return "Biu cc li gi cho hm ny:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorVietnamese::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1424 of file translator_vi.h.
    {
      return "Biu cc li gi cho hm ny:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorVietnamese::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1424 of file translator_vi.h.
    {
      return "Biu cc li gi cho hm ny:";
    }
trClass() [1/2]
virtual QCString TranslatorVietnamese::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1211 of file translator_vi.h.
    {
      QCString result((first_capital ? "Class" : "class"));
      if (!singular) result+="es";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorVietnamese::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1211 of file translator_vi.h.
    {
      QCString result((first_capital ? "Class" : "class"));
      if (!singular) result+="es";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorVietnamese::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 537 of file translator_vi.h.
    {
      return "S k tha cho "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorVietnamese::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 537 of file translator_vi.h.
    {
      return "S k tha cho "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 412 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Thng tin v cu trc c s d liu";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Thng tin v Class";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 412 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Thng tin v cu trc c s d liu";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Thng tin v Class";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorVietnamese::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1111 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cu trc d liu";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorVietnamese::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1111 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cu trc d liu";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorVietnamese::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 196 of file translator_vi.h.
    { return "Kin trc Class"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorVietnamese::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 196 of file translator_vi.h.
    { return "Kin trc Class"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorVietnamese::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 255 of file translator_vi.h.
    { return "Danh sch k tha c sp xp theo ABC, "
             "nhng cha y :";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorVietnamese::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 255 of file translator_vi.h.
    { return "Danh sch k tha c sp xp theo ABC, "
             "nhng cha y :";
    }
trCode() [1/2]
virtual QCString TranslatorVietnamese::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 883 of file translator_vi.h.
    {
      return "m ngun";
    }
trCode() [2/2]
virtual QCString TranslatorVietnamese::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 883 of file translator_vi.h.
    {
      return "m ngun";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorVietnamese::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 838 of file translator_vi.h.
    {
      return "S lin kt cho "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorVietnamese::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 838 of file translator_vi.h.
    {
      return "S lin kt cho "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorVietnamese::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 385 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Index cu trc c s d liu";
      }
      else
      {
        return "Class Index";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorVietnamese::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 385 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Index cu trc c s d liu";
      }
      else
      {
        return "Class Index";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorVietnamese::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1594 of file translator_vi.h.
    { return "Ch mc kiu d liu"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorVietnamese::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1594 of file translator_vi.h.
    { return "Ch mc kiu d liu"; }
trCompoundList() [1/2]
virtual QCString TranslatorVietnamese::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 200 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cu trc c s d liu (Data Structures)";
      }
      else
      {
        return "Danh mc cc Class";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorVietnamese::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 200 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cu trc c s d liu (Data Structures)";
      }
      else
      {
        return "Danh mc cc Class";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorVietnamese::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 270 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "y l cu trc c s d liu vi m t tm tt:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "y l cc classes vi cc m t tm tt:";
      }
      else
      {
        return "y l cc classes, structs, "
               "unions v interfaces vi cc m t tm tt:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorVietnamese::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 270 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "y l cu trc c s d liu vi m t tm tt:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "y l cc classes vi cc m t tm tt:";
      }
      else
      {
        return "y l cc classes, structs, "
               "unions v interfaces vi cc m t tm tt:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorVietnamese::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1567 of file translator_vi.h.
    { return "Kiu d liu vi cc m t tm tt:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorVietnamese::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1567 of file translator_vi.h.
    { return "Kiu d liu vi cc m t tm tt:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorVietnamese::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1559 of file translator_vi.h.
    { return "Danh sch kiu d liu"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorVietnamese::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1559 of file translator_vi.h.
    { return "Danh sch kiu d liu"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorVietnamese::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 217 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cc trng d liu";
      }
      else
      {
        return "Cc thnh vin ca Class";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorVietnamese::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 217 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cc trng d liu";
      }
      else
      {
        return "Cc thnh vin ca Class";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorVietnamese::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 289 of file translator_vi.h.
    {
      QCString result="Danh mc tt c cc ";
      if (!extractAll)
      {
        result+="(c m t) ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct v union fields";
      }
      else
      {
        result+="class members";
      }
      result+=" cng vi cc cc lin kt n ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="Thng tin v struct/union cho tng trng:";
        }
        else
        {
          result+="Thng tin v class cho tng thnh vin:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="cc structures/unions thuc:";
        }
        else
        {
          result+="cc lp thuc:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorVietnamese::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 289 of file translator_vi.h.
    {
      QCString result="Danh mc tt c cc ";
      if (!extractAll)
      {
        result+="(c m t) ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct v union fields";
      }
      else
      {
        result+="class members";
      }
      result+=" cng vi cc cc lin kt n ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="Thng tin v struct/union cho tng trng:";
        }
        else
        {
          result+="Thng tin v class cho tng thnh vin:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="cc structures/unions thuc:";
        }
        else
        {
          result+="cc lp thuc:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorVietnamese::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1571 of file translator_vi.h.
    {
      QCString result="Danh sch tt c ";
      if (!extractAll)
      {
        result+="(c m t) ";
      }
      result+="cc kiu d liu thnh vin";
      result+=" cng vi lin kt vi ";
      if (!extractAll)
      {
         result+="Thng tin cu trc d liu cho tng thnh vin";
      }
      else
      {
         result+=" cc kiu d liu thuc:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorVietnamese::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1571 of file translator_vi.h.
    {
      QCString result="Danh sch tt c ";
      if (!extractAll)
      {
        result+="(c m t) ";
      }
      result+="cc kiu d liu thnh vin";
      result+=" cng vi lin kt vi ";
      if (!extractAll)
      {
         result+="Thng tin cu trc d liu cho tng thnh vin";
      }
      else
      {
         result+=" cc kiu d liu thuc:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorVietnamese::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1563 of file translator_vi.h.
    { return "Trng d liu"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorVietnamese::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1563 of file translator_vi.h.
    { return "Trng d liu"; }
trCompoundReference() [1/2]
virtual QCString TranslatorVietnamese::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 612 of file translator_vi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Tham chiu";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorVietnamese::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 612 of file translator_vi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Tham chiu";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorVietnamese::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1635 of file translator_vi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Module"; break;
        case ClassDef::Struct: result+=" Type"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Tham chiu";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorVietnamese::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1635 of file translator_vi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Module"; break;
        case ClassDef::Struct: result+=" Type"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Tham chiu";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorVietnamese::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 513 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cu trc c s d liu";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorVietnamese::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 513 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cu trc c s d liu";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 848 of file translator_vi.h.
    {
      return "Thng tin v Constructor v Destructor";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 848 of file translator_vi.h.
    {
      return "Thng tin v Constructor v Destructor";
    }
trDataTypes() [1/2]
virtual QCString TranslatorVietnamese::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1618 of file translator_vi.h.
    { return "Kiu d liu"; }
trDataTypes() [2/2]
virtual QCString TranslatorVietnamese::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1618 of file translator_vi.h.
    { return "Kiu d liu"; }
trDate() [1/2]
virtual QCString TranslatorVietnamese::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 551 of file translator_vi.h.
    { return "Ngy"; }
trDate() [2/2]
virtual QCString TranslatorVietnamese::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 551 of file translator_vi.h.
    { return "Ngy"; }
trDayOfWeek() [1/2]
virtual QCString TranslatorVietnamese::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1750 of file translator_vi.h.
    {
      static const char *days_short[] = { "T2", "T3", "T4", "T5", "T6", "T7", "CN" };
      static const char *days_full[] = { "Th Hai", "Th Ba", "Th T", "Th Nm", "Th Sau", "Th Bay", "Chu Nht" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorVietnamese::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1750 of file translator_vi.h.
    {
      static const char *days_short[] = { "T2", "T3", "T4", "T5", "T6", "T7", "CN" };
      static const char *days_full[] = { "Th Hai", "Th Ba", "Th T", "Th Nm", "Th Sau", "Th Bay", "Chu Nht" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorVietnamese::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1764 of file translator_vi.h.
    {
      static const char *dayPeriod[] = { "SA", "CH" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorVietnamese::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1764 of file translator_vi.h.
    {
      static const char *dayPeriod[] = { "SA", "CH" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorVietnamese::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 815 of file translator_vi.h.
    {
      return "nh ngha ti dng @0 trong file @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorVietnamese::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 815 of file translator_vi.h.
    {
      return "nh ngha ti dng @0 trong file @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorVietnamese::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 184 of file translator_vi.h.
    { return "c nh ngha trong"; }
trDefinedIn() [2/2]
virtual QCString TranslatorVietnamese::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 184 of file translator_vi.h.
    { return "c nh ngha trong"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorVietnamese::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 819 of file translator_vi.h.
    {
      return "nh ngha trong file @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorVietnamese::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 819 of file translator_vi.h.
    {
      return "nh ngha trong file @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 483 of file translator_vi.h.
    { return "Thng tin v nh ngha"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 483 of file translator_vi.h.
    { return "Thng tin v nh ngha"; }
trDefines() [1/2]
virtual QCString TranslatorVietnamese::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 447 of file translator_vi.h.
    { return "nh ngha"; }
trDefines() [2/2]
virtual QCString TranslatorVietnamese::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 447 of file translator_vi.h.
    { return "nh ngha"; }
trDefineValue() [1/2]
virtual QCString TranslatorVietnamese::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1138 of file translator_vi.h.
    {
      return "Gi tr:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorVietnamese::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1138 of file translator_vi.h.
    {
      return "Gi tr:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorVietnamese::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 828 of file translator_vi.h.
    {
      return "Khng tn thnh";
    }
trDeprecated() [2/2]
virtual QCString TranslatorVietnamese::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 828 of file translator_vi.h.
    {
      return "Khng tn thnh";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorVietnamese::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1347 of file translator_vi.h.
    {
      return "Danh sch Deprecated";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorVietnamese::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1347 of file translator_vi.h.
    {
      return "Danh sch Deprecated";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorVietnamese::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 117 of file translator_vi.h.
    { return "M t chi tit"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorVietnamese::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 117 of file translator_vi.h.
    { return "M t chi tit"; }
trDir() [1/2]
virtual QCString TranslatorVietnamese::trDir (bool first_capital, bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1514 of file translator_vi.h.
    {
      QCString result((first_capital ? "Th mc" : "th mc"));
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorVietnamese::trDir (bool first_capital, bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1514 of file translator_vi.h.
    {
      QCString result((first_capital ? "Th mc" : "th mc"));
      return result;
    }
trDirDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1496 of file translator_vi.h.
    { return "Thng tin v th mc"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1496 of file translator_vi.h.
    { return "Thng tin v th mc"; }
trDirectories() [1/2]
virtual QCString TranslatorVietnamese::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1502 of file translator_vi.h.
    { return "Cc th mc"; }
trDirectories() [2/2]
virtual QCString TranslatorVietnamese::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1502 of file translator_vi.h.
    { return "Cc th mc"; }
trDirIndex() [1/2]
virtual QCString TranslatorVietnamese::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1490 of file translator_vi.h.
    { return "Cu trc th mc"; }
trDirIndex() [2/2]
virtual QCString TranslatorVietnamese::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1490 of file translator_vi.h.
    { return "Cu trc th mc"; }
trDirReference() [1/2]
virtual QCString TranslatorVietnamese::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1508 of file translator_vi.h.
    { QCString result=dirName; result+=" Tham chiu th mc"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorVietnamese::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1508 of file translator_vi.h.
    { QCString result=dirName; result+=" Tham chiu th mc"; return result; }
trDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 367 of file translator_vi.h.
    { return "Thng tin"; }
trDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 367 of file translator_vi.h.
    { return "Thng tin"; }
trEnumerations() [1/2]
virtual QCString TranslatorVietnamese::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 459 of file translator_vi.h.
    { return "Enumerations"; }
trEnumerations() [2/2]
virtual QCString TranslatorVietnamese::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 459 of file translator_vi.h.
    { return "Enumerations"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 495 of file translator_vi.h.
    { return "Thng tin v Enumeration Type"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 495 of file translator_vi.h.
    { return "Thng tin v Enumeration Type"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1547 of file translator_vi.h.
    { return "Thng tin Enumerator"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1547 of file translator_vi.h.
    { return "Thng tin Enumerator"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorVietnamese::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 477 of file translator_vi.h.
    { return "Enumerator"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorVietnamese::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 477 of file translator_vi.h.
    { return "Enumerator"; }
trEnumName() [1/2]
virtual QCString TranslatorVietnamese::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 176 of file translator_vi.h.
    { return "tn enum"; }
trEnumName() [2/2]
virtual QCString TranslatorVietnamese::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 176 of file translator_vi.h.
    { return "tn enum"; }
trEnumValue() [1/2]
virtual QCString TranslatorVietnamese::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 180 of file translator_vi.h.
    { return "gi tr enum"; }
trEnumValue() [2/2]
virtual QCString TranslatorVietnamese::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 180 of file translator_vi.h.
    { return "gi tr enum"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1364 of file translator_vi.h.
    {
      return "Thng tin v s kin";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1364 of file translator_vi.h.
    {
      return "Thng tin v s kin";
    }
trEvents() [1/2]
virtual QCString TranslatorVietnamese::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1359 of file translator_vi.h.
    {
      return "S kin";
    }
trEvents() [2/2]
virtual QCString TranslatorVietnamese::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1359 of file translator_vi.h.
    {
      return "S kin";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 437 of file translator_vi.h.
    { return "Thng tin v cc v d"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 437 of file translator_vi.h.
    { return "Thng tin v cc v d"; }
trExamples() [1/2]
virtual QCString TranslatorVietnamese::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 247 of file translator_vi.h.
    { return "Cc v d"; }
trExamples() [2/2]
virtual QCString TranslatorVietnamese::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 247 of file translator_vi.h.
    { return "Cc v d"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorVietnamese::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 353 of file translator_vi.h.
    { return "Danh sch tt c cc v d:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorVietnamese::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 353 of file translator_vi.h.
    { return "Danh sch tt c cc v d:"; }
trExceptions() [1/2]
virtual QCString TranslatorVietnamese::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 567 of file translator_vi.h.
    { return "Exceptions"; }
trExceptions() [2/2]
virtual QCString TranslatorVietnamese::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 567 of file translator_vi.h.
    { return "Exceptions"; }
trFile() [1/2]
virtual QCString TranslatorVietnamese::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1222 of file translator_vi.h.
    {
      QCString result((first_capital ? "File" : "file"));
      if (!singular) result+="s";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorVietnamese::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1222 of file translator_vi.h.
    {
      QCString result((first_capital ? "File" : "file"));
      if (!singular) result+="s";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 431 of file translator_vi.h.
    { return "Thng tin v File"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 431 of file translator_vi.h.
    { return "Thng tin v File"; }
trFileIndex() [1/2]
virtual QCString TranslatorVietnamese::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 400 of file translator_vi.h.
    { return "File Index"; }
trFileIndex() [2/2]
virtual QCString TranslatorVietnamese::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 400 of file translator_vi.h.
    { return "File Index"; }
trFileList() [1/2]
virtual QCString TranslatorVietnamese::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 213 of file translator_vi.h.
    { return "Danh mc File"; }
trFileList() [2/2]
virtual QCString TranslatorVietnamese::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 213 of file translator_vi.h.
    { return "Danh mc File"; }
trFileListDescription() [1/2]
virtual QCString TranslatorVietnamese::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 261 of file translator_vi.h.
    {
      QCString result="Danh mc y tt c cc ";
      if (!extractAll) result+="(c bin son) ";
      result+="files cng vi cc m t tm tt:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorVietnamese::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 261 of file translator_vi.h.
    {
      QCString result="Danh mc y tt c cc ";
      if (!extractAll) result+="(c bin son) ";
      result+="files cng vi cc m t tm tt:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorVietnamese::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 230 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Ton cc";
      }
      else
      {
        return "File thnh vin";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorVietnamese::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 230 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Ton cc";
      }
      else
      {
        return "File thnh vin";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorVietnamese::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 331 of file translator_vi.h.
    {
      QCString result="Danh sch tt c cc ";
      if (!extractAll) result+="(c m tat) ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="functions, variables, defines, enums, v typedefs";
      }
      else
      {
        result+="cc file thnh vin";
      }
      result+=" cng vi links ti ";
      if (extractAll)
        result+="cc files thuc:";
      else
        result+="ti liu:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorVietnamese::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 331 of file translator_vi.h.
    {
      QCString result="Danh sch tt c cc ";
      if (!extractAll) result+="(c m tat) ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="functions, variables, defines, enums, v typedefs";
      }
      else
      {
        result+="cc file thnh vin";
      }
      result+=" cng vi links ti ";
      if (extractAll)
        result+="cc files thuc:";
      else
        result+="ti liu:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorVietnamese::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 634 of file translator_vi.h.
    {
      QCString result=fileName;
      result+=" File Tham chiu";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorVietnamese::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 634 of file translator_vi.h.
    {
      QCString result=fileName;
      result+=" File Tham chiu";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorVietnamese::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 594 of file translator_vi.h.
    { return "Friends"; }
trFriends() [2/2]
virtual QCString TranslatorVietnamese::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 594 of file translator_vi.h.
    { return "Friends"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 501 of file translator_vi.h.
    { return "Thng tin v hm"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 501 of file translator_vi.h.
    { return "Thng tin v hm"; }
trFunctions() [1/2]
virtual QCString TranslatorVietnamese::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 465 of file translator_vi.h.
    { return "Cc hm"; }
trFunctions() [2/2]
virtual QCString TranslatorVietnamese::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 465 of file translator_vi.h.
    { return "Cc hm"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorVietnamese::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 528 of file translator_vi.h.
    {
      QCString result="c bin son vo "+date;
      if (!projName.isEmpty()) result+=" cho m ngun d n "+projName;
      result+=" bi";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorVietnamese::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 528 of file translator_vi.h.
    {
      QCString result="c bin son vo "+date;
      if (!projName.isEmpty()) result+=" cho m ngun d n "+projName;
      result+=" bi";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorVietnamese::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 168 of file translator_vi.h.
    { QCString result="c to ra bi Doxygen";
      if (!s.isEmpty()) result+=" cho "+s;
      result+=" t m ngun.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorVietnamese::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 168 of file translator_vi.h.
    { QCString result="c to ra bi Doxygen";
      if (!s.isEmpty()) result+=" cho "+s;
      result+=" t m ngun.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorVietnamese::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 571 of file translator_vi.h.
    { return "c bin son bi"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorVietnamese::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 571 of file translator_vi.h.
    { return "c bin son bi"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorVietnamese::trGeneratedFromFiles (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 772 of file translator_vi.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Thng tin cho ";
      switch(compType)
      {
        case ClassDef::Class: result+="class"; break;
        case ClassDef::Struct: result+="struct"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" c bin son t cc file sau y";
      result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorVietnamese::trGeneratedFromFiles (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 772 of file translator_vi.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Thng tin cho ";
      switch(compType)
      {
        case ClassDef::Class: result+="class"; break;
        case ClassDef::Struct: result+="struct"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" c bin son t cc file sau y";
      result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorVietnamese::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1703 of file translator_vi.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Thng tin cho ";
      switch(compType)
      {
        case ClassDef::Class: result+="module"; break;
        case ClassDef::Struct: result+="type"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" c bin son t cc file sau y";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorVietnamese::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1703 of file translator_vi.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Thng tin cho ";
      switch(compType)
      {
        case ClassDef::Class: result+="module"; break;
        case ClassDef::Struct: result+="type"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" c bin son t cc file sau y";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorVietnamese::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1277 of file translator_vi.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorVietnamese::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1277 of file translator_vi.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 858 of file translator_vi.h.
    {
      return "Ti Thng tin ca file ny.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 858 of file translator_vi.h.
    {
      return "Ti Thng tin ca file ny.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorVietnamese::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 891 of file translator_vi.h.
    {
      return "Ti kin trc ha ca Class";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorVietnamese::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 891 of file translator_vi.h.
    {
      return "Ti kin trc ha ca Class";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorVietnamese::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 853 of file translator_vi.h.
    {
      return "Ti m ngun ca file ny.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorVietnamese::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 853 of file translator_vi.h.
    {
      return "Ti m ngun ca file ny.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorVietnamese::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 895 of file translator_vi.h.
    {
      return "Ti kin trc text ca Class";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorVietnamese::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 895 of file translator_vi.h.
    {
      return "Ti kin trc text ca Class";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorVietnamese::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 887 of file translator_vi.h.
    {
      return "Kin trc ha ca Class";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorVietnamese::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 887 of file translator_vi.h.
    {
      return "Kin trc ha ca Class";
    }
trGroup() [1/2]
virtual QCString TranslatorVietnamese::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1244 of file translator_vi.h.
    {
      QCString result((first_capital ? "Group" : "group"));
      if (!singular) result+="s";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorVietnamese::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1244 of file translator_vi.h.
    {
      QCString result((first_capital ? "Group" : "group"));
      if (!singular) result+="s";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorVietnamese::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 379 of file translator_vi.h.
    { return "Hierarchical Index"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorVietnamese::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 379 of file translator_vi.h.
    { return "Hierarchical Index"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorVietnamese::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1315 of file translator_vi.h.
    {
      return "Thc hin "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorVietnamese::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1315 of file translator_vi.h.
    {
      return "Thc hin "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorVietnamese::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1323 of file translator_vi.h.
    {
      return "c thc hin trong "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorVietnamese::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1323 of file translator_vi.h.
    {
      return "c thc hin trong "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorVietnamese::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 987 of file translator_vi.h.
    {
      return " th ny biu th nhng file no trc tip hoc"
             "khng trc tip bao gm file ny:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorVietnamese::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 987 of file translator_vi.h.
    {
      return " th ny biu th nhng file no trc tip hoc"
             "khng trc tip bao gm file ny:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorVietnamese::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 843 of file translator_vi.h.
    {
      return "Km theo graph ph thuc cho "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorVietnamese::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 843 of file translator_vi.h.
    {
      return "Km theo graph ph thuc cho "+fName+":";
    }
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorVietnamese::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 162 of file translator_vi.h.
    { return ", cng vi tt c cc thnh vin k tha."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorVietnamese::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 162 of file translator_vi.h.
    { return ", cng vi tt c cc thnh vin k tha."; }
trInheritedByList() [1/2]
virtual QCString TranslatorVietnamese::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 706 of file translator_vi.h.
    {
      return "c k tha bi "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorVietnamese::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 706 of file translator_vi.h.
    {
      return "c k tha bi "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorVietnamese::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 698 of file translator_vi.h.
    {
      return "K tha "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorVietnamese::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 698 of file translator_vi.h.
    {
      return "K tha "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorVietnamese::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 878 of file translator_vi.h.
    {
      return "Gi tr khi to:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorVietnamese::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 878 of file translator_vi.h.
    {
      return "Gi tr khi to:";
    }
trInvariant() [1/2]
virtual QCString TranslatorVietnamese::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 873 of file translator_vi.h.
    {
      return "Bt bin";
    }
trInvariant() [2/2]
virtual QCString TranslatorVietnamese::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 873 of file translator_vi.h.
    {
      return "Bt bin";
    }
trISOLang() [1/2]
virtual QCString TranslatorVietnamese::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 98 of file translator_vi.h.
    {
      return "vi";
    }
trISOLang() [2/2]
virtual QCString TranslatorVietnamese::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 98 of file translator_vi.h.
    {
      return "vi";
    }
trLegend() [1/2]
virtual QCString TranslatorVietnamese::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1071 of file translator_vi.h.
    {
      return "Ch gii";
    }
trLegend() [2/2]
virtual QCString TranslatorVietnamese::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1071 of file translator_vi.h.
    {
      return "Ch gii";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorVietnamese::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1009 of file translator_vi.h.
    {
      return
        "Trang ny gii ngha cc biu c bin son bi "
        " doxygen.<p>\n"
        "Hy xem xt cc v d sau:\n"
        "\\code\n"
        "/*! Cc lp khng thy c bi s ct ngn */\n"
        "Lp khng nhn thy class { };\n\n"
        "/*! class b ct, quan h k tha b n */\n"
        "class b ct : b n ton cc { };\n\n"
        "/* Class khng c m t vi cc ch gii doxygen */\n"
        "class khng c m t { };\n\n"
        "/*! Class c k tha s dng cc k tha public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class c k tha s dng k tha protected */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class c k tha s dng k tha protected private */\n"
        "class PrivateBase { };\n\n"
        "/*! Class c s dng bi cc class k tha */\n"
        "class c s dng { };\n\n"
        "/*! Super class k tha mt s cc class khc */\n"
        "class c k tha : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Kt qu trong biu sau y:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Cc hp trong biu trn c ngha nh sau:\n"
        "<ul>\n"
        "<li>%Hp mu xm biu th cu trc clas cho "
        "biu c th hin.\n"
        "<li>%Hp c khung mu en biu th struct hoc class c m t.\n"
        "<li>%Hp c khung mu xm biu th struct hoc class cha c m t.\n"
        "<li>%Hp c khung mu biu th struct hoc class c m t "
        "khi m khng phi tt c cc quan h k tha/containment c bin din.. %Biu b "
        "ct nu n khng nm trn trong cc bin c cho trc..\n"
        "</ul>\n"
        "Cc mi tn c ngha nh sau::\n"
        "<ul>\n"
        "<li>%Mi tn mu xanh m biu th cc quan h k tha cng khai "
        "gia 2 class.\n"
        "<li>%Mi tn mu xanh l cy m biu th k tha c bo v (protected).\n"
        "<li>%Mi tn m biu th k tha dng private.\n"
        "<li>%Mi tn mu hng t qung biu th class c s dng "
        "bi class khc. Mi tn c gn nhn vi cc gi tr "
        "m cc calsss hoc struct c truy cp ti.\n"
        "<li>%Mi tn vng t qung c th quan h gia template instance v "
        "template class c dn xut t . Mi tn c gn nhn vi "
        "tham s ca template.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorVietnamese::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1009 of file translator_vi.h.
    {
      return
        "Trang ny gii ngha cc biu c bin son bi "
        " doxygen.<p>\n"
        "Hy xem xt cc v d sau:\n"
        "\\code\n"
        "/*! Cc lp khng thy c bi s ct ngn */\n"
        "Lp khng nhn thy class { };\n\n"
        "/*! class b ct, quan h k tha b n */\n"
        "class b ct : b n ton cc { };\n\n"
        "/* Class khng c m t vi cc ch gii doxygen */\n"
        "class khng c m t { };\n\n"
        "/*! Class c k tha s dng cc k tha public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class c k tha s dng k tha protected */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class c k tha s dng k tha protected private */\n"
        "class PrivateBase { };\n\n"
        "/*! Class c s dng bi cc class k tha */\n"
        "class c s dng { };\n\n"
        "/*! Super class k tha mt s cc class khc */\n"
        "class c k tha : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Kt qu trong biu sau y:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Cc hp trong biu trn c ngha nh sau:\n"
        "<ul>\n"
        "<li>%Hp mu xm biu th cu trc clas cho "
        "biu c th hin.\n"
        "<li>%Hp c khung mu en biu th struct hoc class c m t.\n"
        "<li>%Hp c khung mu xm biu th struct hoc class cha c m t.\n"
        "<li>%Hp c khung mu biu th struct hoc class c m t "
        "khi m khng phi tt c cc quan h k tha/containment c bin din.. %Biu b "
        "ct nu n khng nm trn trong cc bin c cho trc..\n"
        "</ul>\n"
        "Cc mi tn c ngha nh sau::\n"
        "<ul>\n"
        "<li>%Mi tn mu xanh m biu th cc quan h k tha cng khai "
        "gia 2 class.\n"
        "<li>%Mi tn mu xanh l cy m biu th k tha c bo v (protected).\n"
        "<li>%Mi tn m biu th k tha dng private.\n"
        "<li>%Mi tn mu hng t qung biu th class c s dng "
        "bi class khc. Mi tn c gn nhn vi cc gi tr "
        "m cc calsss hoc struct c truy cp ti.\n"
        "<li>%Mi tn vng t qung c th quan h gia template instance v "
        "template class c dn xut t . Mi tn c gn nhn vi "
        "tham s ca template.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorVietnamese::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1002 of file translator_vi.h.
    {
      return "Ch gii Graph";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorVietnamese::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1002 of file translator_vi.h.
    {
      return "Ch gii Graph";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorVietnamese::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 150 of file translator_vi.h.
    { return "Lit k tt c cc thnh vin"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorVietnamese::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 150 of file translator_vi.h.
    { return "Lit k tt c cc thnh vin"; }
trMainPage() [1/2]
virtual QCString TranslatorVietnamese::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 802 of file translator_vi.h.
    { return "Tranh chnh"; }
trMainPage() [2/2]
virtual QCString TranslatorVietnamese::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 802 of file translator_vi.h.
    { return "Tranh chnh"; }
trMember() [1/2]
virtual QCString TranslatorVietnamese::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1266 of file translator_vi.h.
    {
      QCString result((first_capital ? "Member" : "member"));
      if (!singular) result+="s";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorVietnamese::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1266 of file translator_vi.h.
    {
      QCString result((first_capital ? "Member" : "member"));
      if (!singular) result+="s";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 133 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Thng tin v trng";
      }
      else
      {
        return "Thng tin v Member Data";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 133 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Thng tin v trng";
      }
      else
      {
        return "Thng tin v Member Data";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 125 of file translator_vi.h.
    { return "Thng tin v Member Enumeration"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 125 of file translator_vi.h.
    { return "Thng tin v Member Enumeration"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 129 of file translator_vi.h.
    { return "Thng tin v hm thnh vin"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 129 of file translator_vi.h.
    { return "Thng tin v hm thnh vin"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorVietnamese::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1555 of file translator_vi.h.
    { return "Thng tin v cc hm v cc th tc thnh vin"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorVietnamese::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1555 of file translator_vi.h.
    { return "Thng tin v cc hm v cc th tc thnh vin"; }
trMemberList() [1/2]
virtual QCString TranslatorVietnamese::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 154 of file translator_vi.h.
    { return "Danh sch thnh vin"; }
trMemberList() [2/2]
virtual QCString TranslatorVietnamese::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 154 of file translator_vi.h.
    { return "Danh sch thnh vin"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 121 of file translator_vi.h.
    { return "Thng tin v Member Typedef"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 121 of file translator_vi.h.
    { return "Thng tin v Member Typedef"; }
trModule() [1/2]
virtual QCString TranslatorVietnamese::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1694 of file translator_vi.h.
    {
      QCString result((first_capital ? "Module" : "module"));
      if (!singular) result+="";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorVietnamese::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1694 of file translator_vi.h.
    {
      QCString result((first_capital ? "Module" : "module"));
      if (!singular) result+="";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 406 of file translator_vi.h.
    { return "Thng tin v cc Module"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 406 of file translator_vi.h.
    { return "Thng tin v cc Module"; }
trModuleIndex() [1/2]
virtual QCString TranslatorVietnamese::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 373 of file translator_vi.h.
    { return "Ch mc (Index) Module"; }
trModuleIndex() [2/2]
virtual QCString TranslatorVietnamese::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 373 of file translator_vi.h.
    { return "Ch mc (Index) Module"; }
trModuleReference() [1/2]
virtual QCString TranslatorVietnamese::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1656 of file translator_vi.h.
    {
      QCString result=namespaceName;
      result+=" Tham chiu Module";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorVietnamese::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1656 of file translator_vi.h.
    {
      QCString result=namespaceName;
      result+=" Tham chiu Module";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorVietnamese::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 192 of file translator_vi.h.
    { return "Cc Modules"; }
trModules() [2/2]
virtual QCString TranslatorVietnamese::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 192 of file translator_vi.h.
    { return "Cc Modules"; }
trModulesDescription() [1/2]
virtual QCString TranslatorVietnamese::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 361 of file translator_vi.h.
    { return "Danh sch tt c cc thnh vin:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorVietnamese::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 361 of file translator_vi.h.
    { return "Danh sch tt c cc thnh vin:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorVietnamese::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1687 of file translator_vi.h.
    { return "Ch mc cc Module"; }
trModulesIndex() [2/2]
virtual QCString TranslatorVietnamese::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1687 of file translator_vi.h.
    { return "Ch mc cc Module"; }
trModulesList() [1/2]
virtual QCString TranslatorVietnamese::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1622 of file translator_vi.h.
    { return "Danh sch Modules"; }
trModulesList() [2/2]
virtual QCString TranslatorVietnamese::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1622 of file translator_vi.h.
    { return "Danh sch Modules"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorVietnamese::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1626 of file translator_vi.h.
    {
      QCString result="Danh sch tt c ";
      if (!extractAll) result+="(c m t) ";
      result+="cc module vi m t tm tt:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorVietnamese::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1626 of file translator_vi.h.
    {
      QCString result="Danh sch tt c ";
      if (!extractAll) result+="(c m t) ";
      result+="cc module vi m t tm tt:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorVietnamese::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1668 of file translator_vi.h.
    {
      QCString result="Danh sch tt c ";
      if (!extractAll) result+="(c m t) ";
      result+="cc module thnh vin cng vi lin kt ti ";
      if (extractAll)
      {
        result+="Thng tin module cho tng thnh vin:";
      }
      else
      {
        result+="cc module thuc:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorVietnamese::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1668 of file translator_vi.h.
    {
      QCString result="Danh sch tt c ";
      if (!extractAll) result+="(c m t) ";
      result+="cc module thnh vin cng vi lin kt ti ";
      if (extractAll)
      {
        result+="Thng tin module cho tng thnh vin:";
      }
      else
      {
        result+="cc module thuc:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorVietnamese::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1664 of file translator_vi.h.
    { return "Thnh vin Module"; }
trModulesMembers() [2/2]
virtual QCString TranslatorVietnamese::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1664 of file translator_vi.h.
    { return "Thnh vin Module"; }
trMonth() [1/2]
virtual QCString TranslatorVietnamese::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1757 of file translator_vi.h.
    {
      static const char *months_short[] = { "Thg1", "Thg2", "Thg3", "Thg4", "Thg5", "Thg6", "Thg7", "Thg8", "Thg9", "Thg10", "Thg11", "Thg12" };
      static const char *months_full[] = { "Thang Ging", "Thang Hai", "Thang Ba", "Thang T", "Thang Nm", "Thang Sau", "Thang Bay", "Thang Tam", "Thang Chin", "Thang Mi", "Thang Mi Mt", "Thang Mi Hai" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorVietnamese::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1757 of file translator_vi.h.
    {
      static const char *months_short[] = { "Thg1", "Thg2", "Thg3", "Thg4", "Thg5", "Thg6", "Thg7", "Thg8", "Thg9", "Thg10", "Thg11", "Thg12" };
      static const char *months_full[] = { "Thang Ging", "Thang Hai", "Thang Ba", "Thang T", "Thang Nm", "Thang Sau", "Thang Bay", "Thang Tam", "Thang Chin", "Thang Mi", "Thang Mi Mt", "Thang Mi Hai" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
virtual QCString TranslatorVietnamese::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 146 of file translator_vi.h.
    { return "Tip..."; }
trMore() [2/2]
virtual QCString TranslatorVietnamese::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 146 of file translator_vi.h.
    { return "Tip..."; }
trNamespace() [1/2]
virtual QCString TranslatorVietnamese::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1233 of file translator_vi.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorVietnamese::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1233 of file translator_vi.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 752 of file translator_vi.h.
    { return "Thng tin v Namespace"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 752 of file translator_vi.h.
    { return "Thng tin v Namespace"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorVietnamese::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 746 of file translator_vi.h.
    { return "Namespace Index"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorVietnamese::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 746 of file translator_vi.h.
    { return "Namespace Index"; }
trNamespaceList() [1/2]
virtual QCString TranslatorVietnamese::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 579 of file translator_vi.h.
    { return "Danh sch Namespace"; }
trNamespaceList() [2/2]
virtual QCString TranslatorVietnamese::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 579 of file translator_vi.h.
    { return "Danh sch Namespace"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorVietnamese::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 583 of file translator_vi.h.
    {
      QCString result="Danh sch tt c cc ";
      if (!extractAll) result+="(c bin tp) ";
      result+="namespaces vi m t tm tt:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorVietnamese::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 583 of file translator_vi.h.
    {
      QCString result="Danh sch tt c cc ";
      if (!extractAll) result+="(c bin tp) ";
      result+="namespaces vi m t tm tt:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorVietnamese::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 732 of file translator_vi.h.
    {
      QCString result="Danh sch tt c cc ";
      if (!extractAll) result+="(c bin son) ";
      result+="cc thnh vin namespace cng vi link ti ";
      if (extractAll)
        result+="Thng tin namespace cho tng thnh vin:";
      else
        result+=" namespaces m ph thuc bi:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorVietnamese::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 732 of file translator_vi.h.
    {
      QCString result="Danh sch tt c cc ";
      if (!extractAll) result+="(c bin son) ";
      result+="cc thnh vin namespace cng vi link ti ";
      if (extractAll)
        result+="Thng tin namespace cho tng thnh vin:";
      else
        result+=" namespaces m ph thuc bi:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorVietnamese::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 728 of file translator_vi.h.
    { return "Thnh vin Namespace"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorVietnamese::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 728 of file translator_vi.h.
    { return "Thnh vin Namespace"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorVietnamese::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 642 of file translator_vi.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Tham chiu";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorVietnamese::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 642 of file translator_vi.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Tham chiu";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorVietnamese::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 762 of file translator_vi.h.
    { return "Namespaces"; }
trNamespaces() [2/2]
virtual QCString TranslatorVietnamese::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 762 of file translator_vi.h.
    { return "Namespaces"; }
trNote() [1/2]
virtual QCString TranslatorVietnamese::trNote () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_vi.h.
    {
      return "Ghi ch";
    }
trNote() [2/2]
virtual QCString TranslatorVietnamese::trNote () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_vi.h.
    {
      return "Ghi ch";
    }
trOverloadText() [1/2]
virtual QCString TranslatorVietnamese::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1527 of file translator_vi.h.
    {
       return "Hm thnh vin dng overloaded, "
              "c ch ra cho vic tra cu d dng. N khc vi hm trn"
              "ch ch nhng tham s no n chp nhn.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorVietnamese::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1527 of file translator_vi.h.
    {
       return "Hm thnh vin dng overloaded, "
              "c ch ra cho vic tra cu d dng. N khc vi hm trn"
              "ch ch nhng tham s no n chp nhn.";
    }
trPackage() [1/2]
virtual QCString TranslatorVietnamese::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1123 of file translator_vi.h.
    {
      return "Gi "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorVietnamese::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1123 of file translator_vi.h.
    {
      return "Gi "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorVietnamese::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1400 of file translator_vi.h.
    {
      return "Cc thuc tnh Package";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorVietnamese::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1400 of file translator_vi.h.
    {
      return "Cc thuc tnh Package";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorVietnamese::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1382 of file translator_vi.h.
    {
      return "Cc hm Package";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorVietnamese::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1382 of file translator_vi.h.
    {
      return "Cc hm Package";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorVietnamese::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1128 of file translator_vi.h.
    {
      return "Danh sch cc gi cng vi m t tm tt (khi c th c):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorVietnamese::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1128 of file translator_vi.h.
    {
      return "Danh sch cc gi cng vi m t tm tt (khi c th c):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorVietnamese::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1386 of file translator_vi.h.
    {
      return "Members Package";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorVietnamese::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1386 of file translator_vi.h.
    {
      return "Members Package";
    }
trPackages() [1/2]
virtual QCString TranslatorVietnamese::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1133 of file translator_vi.h.
    {
      return "Cc gi";
    }
trPackages() [2/2]
virtual QCString TranslatorVietnamese::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1133 of file translator_vi.h.
    {
      return "Cc gi";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorVietnamese::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1375 of file translator_vi.h.
    {
      return "Kiu gi";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorVietnamese::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1375 of file translator_vi.h.
    {
      return "Kiu gi";
    }
trPage() [1/2]
virtual QCString TranslatorVietnamese::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1255 of file translator_vi.h.
    {
      QCString result((first_capital ? "Trang" : "trang"));
      if (!singular) result+="";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorVietnamese::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1255 of file translator_vi.h.
    {
      QCString result((first_capital ? "Trang" : "trang"));
      if (!singular) result+="";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorVietnamese::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 808 of file translator_vi.h.
    { return "tr."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorVietnamese::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 808 of file translator_vi.h.
    { return "tr."; }
trPageIndex() [1/2]
virtual QCString TranslatorVietnamese::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 899 of file translator_vi.h.
    {
      return "Ch mc trang";
    }
trPageIndex() [2/2]
virtual QCString TranslatorVietnamese::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 899 of file translator_vi.h.
    {
      return "Ch mc trang";
    }
trParameters() [1/2]
virtual QCString TranslatorVietnamese::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 563 of file translator_vi.h.
    { return "Cc tham s"; }
trParameters() [2/2]
virtual QCString TranslatorVietnamese::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 563 of file translator_vi.h.
    { return "Cc tham s"; }
trPostcondition() [1/2]
virtual QCString TranslatorVietnamese::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 868 of file translator_vi.h.
    {
      return "iu kin sau";
    }
trPostcondition() [2/2]
virtual QCString TranslatorVietnamese::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 868 of file translator_vi.h.
    {
      return "iu kin sau";
    }
trPrecondition() [1/2]
virtual QCString TranslatorVietnamese::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 863 of file translator_vi.h.
    {
      return "iu kin trc";
    }
trPrecondition() [2/2]
virtual QCString TranslatorVietnamese::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 863 of file translator_vi.h.
    {
      return "iu kin trc";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorVietnamese::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_vi.h.
    {
      return "Cc thuc tnh Private";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorVietnamese::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_vi.h.
    {
      return "Cc thuc tnh Private";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorVietnamese::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 663 of file translator_vi.h.
    { return "Cc hm thnh vin Private"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorVietnamese::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 663 of file translator_vi.h.
    { return "Cc hm thnh vin Private"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorVietnamese::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 665 of file translator_vi.h.
    { return "Private Slots"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorVietnamese::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 665 of file translator_vi.h.
    { return "Private Slots"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorVietnamese::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_vi.h.
    {
      return "Cc kiu Private";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorVietnamese::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_vi.h.
    {
      return "Cc kiu Private";
    }
trProperties() [1/2]
virtual QCString TranslatorVietnamese::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1096 of file translator_vi.h.
    {
      return "Thuc tnh";
    }
trProperties() [2/2]
virtual QCString TranslatorVietnamese::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1096 of file translator_vi.h.
    {
      return "Thuc tnh";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1101 of file translator_vi.h.
    {
      return "Thng tin thuc tnh (Property)";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1101 of file translator_vi.h.
    {
      return "Thng tin thuc tnh (Property)";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorVietnamese::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 935 of file translator_vi.h.
    {
      return "cc thuc tnh Protected";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorVietnamese::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 935 of file translator_vi.h.
    {
      return "cc thuc tnh Protected";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorVietnamese::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 657 of file translator_vi.h.
    { return "Cc hm thnh vin Protected"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorVietnamese::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 657 of file translator_vi.h.
    { return "Cc hm thnh vin Protected"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorVietnamese::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 659 of file translator_vi.h.
    { return "Protected Slots"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorVietnamese::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 659 of file translator_vi.h.
    { return "Protected Slots"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorVietnamese::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 931 of file translator_vi.h.
    {
      return "Cc kiu Protected";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorVietnamese::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 931 of file translator_vi.h.
    {
      return "Cc kiu Protected";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorVietnamese::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "cc trng liu";
      }
      else
      {
        return "Cc thuc tnh Public";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorVietnamese::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "cc trng liu";
      }
      else
      {
        return "Cc thuc tnh Public";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorVietnamese::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 649 of file translator_vi.h.
    { return "Cc hm thnh vin Public"; }
trPublicMembers() [2/2]
virtual QCString TranslatorVietnamese::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 649 of file translator_vi.h.
    { return "Cc hm thnh vin Public"; }
trPublicSlots() [1/2]
virtual QCString TranslatorVietnamese::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 651 of file translator_vi.h.
    { return "Public Slots"; }
trPublicSlots() [2/2]
virtual QCString TranslatorVietnamese::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 651 of file translator_vi.h.
    { return "Public Slots"; }
trPublicTypes() [1/2]
virtual QCString TranslatorVietnamese::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_vi.h.
    {
      return "Public Types";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorVietnamese::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_vi.h.
    {
      return "Public Types";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorVietnamese::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 975 of file translator_vi.h.
    {
      return "Tham chiu bi";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorVietnamese::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 975 of file translator_vi.h.
    {
      return "Tham chiu bi";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorVietnamese::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 441 of file translator_vi.h.
    { return "Thng tin tham chiu"; }
trReferenceManual() [2/2]
virtual QCString TranslatorVietnamese::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 441 of file translator_vi.h.
    { return "Thng tin tham chiu"; }
trReferences() [1/2]
virtual QCString TranslatorVietnamese::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1303 of file translator_vi.h.
    {
      return "Tham chiu";
    }
trReferences() [2/2]
virtual QCString TranslatorVietnamese::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1303 of file translator_vi.h.
    {
      return "Tham chiu";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorVietnamese::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 714 of file translator_vi.h.
    {
      return "c thc thi li t "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorVietnamese::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 714 of file translator_vi.h.
    {
      return "c thc thi li t "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorVietnamese::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 722 of file translator_vi.h.
    {
      return "c thc thi li trong "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorVietnamese::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 722 of file translator_vi.h.
    {
      return "c thc thi li trong "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 604 of file translator_vi.h.
    { return "Thng tin v Friends v cc hm lin quan"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 604 of file translator_vi.h.
    { return "Thng tin v Friends v cc hm lin quan"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorVietnamese::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 109 of file translator_vi.h.
    { return "Nhng hm lin quan"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorVietnamese::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 109 of file translator_vi.h.
    { return "Nhng hm lin quan"; }
trRelatedPages() [1/2]
virtual QCString TranslatorVietnamese::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 243 of file translator_vi.h.
    { return "Cc trang lin quan"; }
trRelatedPages() [2/2]
virtual QCString TranslatorVietnamese::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 243 of file translator_vi.h.
    { return "Cc trang lin quan"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorVietnamese::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 357 of file translator_vi.h.
    { return "Danh sch tt c cc trang Thng tin c lin quan:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorVietnamese::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 357 of file translator_vi.h.
    { return "Danh sch tt c cc trang Thng tin c lin quan:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorVietnamese::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 113 of file translator_vi.h.
    { return "(Ch nhng hm ny khng phi l hm thnh vin.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorVietnamese::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 113 of file translator_vi.h.
    { return "(Ch nhng hm ny khng phi l hm thnh vin.)"; }
trRemarks() [1/2]
virtual QCString TranslatorVietnamese::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 979 of file translator_vi.h.
    {
      return "Ghi ch";
    }
trRemarks() [2/2]
virtual QCString TranslatorVietnamese::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 979 of file translator_vi.h.
    {
      return "Ghi ch";
    }
trReturns() [1/2]
virtual QCString TranslatorVietnamese::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 555 of file translator_vi.h.
    { return "Gi tr tr v"; }
trReturns() [2/2]
virtual QCString TranslatorVietnamese::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 555 of file translator_vi.h.
    { return "Gi tr tr v"; }
trReturnValues() [1/2]
virtual QCString TranslatorVietnamese::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 797 of file translator_vi.h.
    { return "Cc gi tr tr v"; }
trReturnValues() [2/2]
virtual QCString TranslatorVietnamese::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 797 of file translator_vi.h.
    { return "Cc gi tr tr v"; }
trRTFansicp() [1/2]
virtual QCString TranslatorVietnamese::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1187 of file translator_vi.h.
    {
      return "1258";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorVietnamese::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1187 of file translator_vi.h.
    {
      return "1258";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorVietnamese::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1196 of file translator_vi.h.
    {
      return "163";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorVietnamese::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1196 of file translator_vi.h.
    {
      return "163";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorVietnamese::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1202 of file translator_vi.h.
    {
      return "Ch s";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorVietnamese::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1202 of file translator_vi.h.
    {
      return "Ch s";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorVietnamese::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1335 of file translator_vi.h.
    {
      return "Mc lc";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorVietnamese::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1335 of file translator_vi.h.
    {
      return "Mc lc";
    }
trSearch() [1/2]
virtual QCString TranslatorVietnamese::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 251 of file translator_vi.h.
    { return "Tm kim"; }
trSearch() [2/2]
virtual QCString TranslatorVietnamese::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 251 of file translator_vi.h.
    { return "Tm kim"; }
trSearchMatches() [1/2]
virtual QCString TranslatorVietnamese::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1467 of file translator_vi.h.
    {
      return "Cc kt qu tha mn k:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorVietnamese::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1467 of file translator_vi.h.
    {
      return "Cc kt qu tha mn k:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorVietnamese::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1448 of file translator_vi.h.
    {
      if (numDocuments==0)
      {
        return "Khng c ti liu no tha mn cc truy vn ca bn.";
      }
      else if (numDocuments==1)
      {
        return "Tm thy <b>1</b> ti liu tha m truy vn ca bn.";
      }
      else
      {
        return "Tm thy tt c <b>$num</b> ti liu tha m truy vn ca bn. "
               "Hin th nhng tha mn tt nht trc.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorVietnamese::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1448 of file translator_vi.h.
    {
      if (numDocuments==0)
      {
        return "Khng c ti liu no tha mn cc truy vn ca bn.";
      }
      else if (numDocuments==1)
      {
        return "Tm thy <b>1</b> ti liu tha m truy vn ca bn.";
      }
      else
      {
        return "Tm thy tt c <b>$num</b> ti liu tha m truy vn ca bn. "
               "Hin th nhng tha mn tt nht trc.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorVietnamese::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1436 of file translator_vi.h.
    {
      return "Kt qu tm kim";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorVietnamese::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1436 of file translator_vi.h.
    {
      return "Kt qu tm kim";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorVietnamese::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 559 of file translator_vi.h.
    { return "Xem thm"; }
trSeeAlso() [2/2]
virtual QCString TranslatorVietnamese::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 559 of file translator_vi.h.
    { return "Xem thm"; }
trSignals() [1/2]
virtual QCString TranslatorVietnamese::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_vi.h.
    { return "Signals"; }
trSignals() [2/2]
virtual QCString TranslatorVietnamese::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_vi.h.
    { return "Signals"; }
trSince() [1/2]
virtual QCString TranslatorVietnamese::trSince () [inline], [virtual]
Implements Translator.
Definition at line 992 of file translator_vi.h.
    {
      return "T";
    }
trSince() [2/2]
virtual QCString TranslatorVietnamese::trSince () [inline], [virtual]
Implements Translator.
Definition at line 992 of file translator_vi.h.
    {
      return "T";
    }
trSourceFile() [1/2]
virtual QCString TranslatorVietnamese::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1478 of file translator_vi.h.
    {
      return filename + " File ngun";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorVietnamese::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1478 of file translator_vi.h.
    {
      return filename + " File ngun";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorVietnamese::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1407 of file translator_vi.h.
    {
      return "Cc thuc tnh Static Package";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorVietnamese::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1407 of file translator_vi.h.
    {
      return "Cc thuc tnh Static Package";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorVietnamese::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1393 of file translator_vi.h.
    {
      return "Cc hm Static Package";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorVietnamese::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1393 of file translator_vi.h.
    {
      return "Cc hm Static Package";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorVietnamese::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 951 of file translator_vi.h.
    {
      return "Cc thuc tnh Static Private";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorVietnamese::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 951 of file translator_vi.h.
    {
      return "Cc thuc tnh Static Private";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorVietnamese::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 667 of file translator_vi.h.
    { return "Cc hm thnh vin Static Private"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorVietnamese::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 667 of file translator_vi.h.
    { return "Cc hm thnh vin Static Private"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorVietnamese::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 939 of file translator_vi.h.
    {
      return "Cc thuc tnh Static Protected";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorVietnamese::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 939 of file translator_vi.h.
    {
      return "Cc thuc tnh Static Protected";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorVietnamese::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 661 of file translator_vi.h.
    { return "Cc hm thnh vin Static Protected"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorVietnamese::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 661 of file translator_vi.h.
    { return "Cc hm thnh vin Static Protected"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorVietnamese::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 927 of file translator_vi.h.
    {
      return "Cc thuc tnh Static Public";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorVietnamese::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 927 of file translator_vi.h.
    {
      return "Cc thuc tnh Static Public";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorVietnamese::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 655 of file translator_vi.h.
    { return "Cc hm Static Public"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorVietnamese::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 655 of file translator_vi.h.
    { return "Cc hm Static Public"; }
trSubprogram() [1/2]
virtual QCString TranslatorVietnamese::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1737 of file translator_vi.h.
    {
      QCString result((first_capital ? "Chng trnh con" : "chng trnh con"));
      if (!singular) result+="";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorVietnamese::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1737 of file translator_vi.h.
    {
      QCString result((first_capital ? "Chng trnh con" : "chng trnh con"));
      if (!singular) result+="";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1612 of file translator_vi.h.
    { return "Thng tin v Function/Subroutine"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1612 of file translator_vi.h.
    { return "Thng tin v Function/Subroutine"; }
trSubprograms() [1/2]
virtual QCString TranslatorVietnamese::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1606 of file translator_vi.h.
    { return "Functions/Subroutines"; }
trSubprograms() [2/2]
virtual QCString TranslatorVietnamese::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1606 of file translator_vi.h.
    { return "Functions/Subroutines"; }
trTest() [1/2]
virtual QCString TranslatorVietnamese::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1081 of file translator_vi.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorVietnamese::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1081 of file translator_vi.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorVietnamese::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1086 of file translator_vi.h.
    {
      return "Danh sch Test";
    }
trTestList() [2/2]
virtual QCString TranslatorVietnamese::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1086 of file translator_vi.h.
    {
      return "Danh sch Test";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorVietnamese::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 158 of file translator_vi.h.
    { return "Danh sch cc thnh vin y cho "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorVietnamese::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 158 of file translator_vi.h.
    { return "Danh sch cc thnh vin y cho "; }
trTodo() [1/2]
virtual QCString TranslatorVietnamese::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 961 of file translator_vi.h.
    {
      return "Mc tiu";
    }
trTodo() [2/2]
virtual QCString TranslatorVietnamese::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 961 of file translator_vi.h.
    {
      return "Mc tiu";
    }
trTodoList() [1/2]
virtual QCString TranslatorVietnamese::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 966 of file translator_vi.h.
    {
      return "Danh sch hng mc cn thc hin";
    }
trTodoList() [2/2]
virtual QCString TranslatorVietnamese::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 966 of file translator_vi.h.
    {
      return "Danh sch hng mc cn thc hin";
    }
trType() [1/2]
virtual QCString TranslatorVietnamese::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1727 of file translator_vi.h.
    {
      QCString result((first_capital ? "Kiu" : "kiu"));
      if (!singular) result+="";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorVietnamese::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1727 of file translator_vi.h.
    {
      QCString result((first_capital ? "Kiu" : "kiu"));
      if (!singular) result+="";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorVietnamese::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1745 of file translator_vi.h.
    {
      return "Rng buc ca kiu (Type)";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorVietnamese::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1745 of file translator_vi.h.
    {
      return "Rng buc ca kiu (Type)";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 489 of file translator_vi.h.
    { return "Thng tin v Typedef"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 489 of file translator_vi.h.
    { return "Thng tin v Typedef"; }
trTypedefs() [1/2]
virtual QCString TranslatorVietnamese::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 453 of file translator_vi.h.
    { return "Typedefs"; }
trTypedefs() [2/2]
virtual QCString TranslatorVietnamese::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 453 of file translator_vi.h.
    { return "Typedefs"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1600 of file translator_vi.h.
    { return "Thng tin v kiu d liu"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1600 of file translator_vi.h.
    { return "Thng tin v kiu d liu"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorVietnamese::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 507 of file translator_vi.h.
    { return "Thng tin v cc bin"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorVietnamese::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 507 of file translator_vi.h.
    { return "Thng tin v cc bin"; }
trVariables() [1/2]
virtual QCString TranslatorVietnamese::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 471 of file translator_vi.h.
    { return "Cc bin"; }
trVariables() [2/2]
virtual QCString TranslatorVietnamese::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 471 of file translator_vi.h.
    { return "Cc bin"; }
trVersion() [1/2]
virtual QCString TranslatorVietnamese::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 547 of file translator_vi.h.
    { return "Phin bn"; }
trVersion() [2/2]
virtual QCString TranslatorVietnamese::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 547 of file translator_vi.h.
    { return "Phin bn"; }
trWarning() [1/2]
virtual QCString TranslatorVietnamese::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 543 of file translator_vi.h.
    { return "Lu "; }
trWarning() [2/2]
virtual QCString TranslatorVietnamese::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 543 of file translator_vi.h.
    { return "Lu "; }
trWriteList() [1/2]
virtual QCString TranslatorVietnamese::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 673 of file translator_vi.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", v ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorVietnamese::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 673 of file translator_vi.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", v ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_vi.h
doxygen/src/translator_vi.h