Qhp Class Reference
#include <qhp.h>
Classes
class Private
Public Member Functions
Qhp ()
~Qhp ()
Qhp (Qhp &&)
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex, bool addToNavIndex, const Definition *def)
void addIndexItem (const Definition *context, const MemberDef *md, const QCString &sectionAnchor, const QCString &title)
void addIndexFile (const QCString &name)
void addImageFile (const QCString &name)
void addStyleSheetFile (const QCString &name)
Qhp ()
~Qhp ()
Qhp (Qhp &&)
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex, bool addToNavIndex, const Definition *def)
void addIndexItem (const Definition *context, const MemberDef *md, const QCString &sectionAnchor, const QCString &title)
void addIndexFile (const QCString &name)
void addImageFile (const QCString &name)
void addStyleSheetFile (const QCString &name)
Static Public Member Functions
static QCString getQchFileName ()
static QCString getQchFileName ()
Static Public Attributes
static const QCString qhpFileName = `index.qhp`
Private Member Functions
void addFile (const QCString &)
void addFile (const QCString &)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 24 of file qhp.h.
Constructor & Destructor Documentation
Qhp() [1/4]
Qhp::Qhp ()
Definition at line 190 of file qhp.cpp.
: p(std::make_unique<Private>()) {}
 Qhp() [1/2]
Qhp::~Qhp () [default]
Qhp() [2/4]
Qhp::Qhp (Qhp &&) [default]
Qhp() [3/4]
Qhp::Qhp ()
 Qhp() [2/2]
Qhp::~Qhp ()
Qhp() [4/4]
Qhp::Qhp (Qhp &&)
Member Function Documentation
addContentsItem() [1/2]
void Qhp::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex, bool addToNavIndex, const Definition * def)
Definition at line 309 of file qhp.cpp.
{
  /*
  <toc>
    <section title="My Application Manual" ref="index.html">
      <section title="Chapter 1" ref="doc.html#chapter1"/>
      <section title="Chapter 2" ref="doc.html#chapter2"/>
      <section title="Chapter 3" ref="doc.html#chapter3"/>
    </section>
  </toc>
  */
  QCString f = file;
  if (!f.isEmpty() && f.at(0)=='^') return; // absolute URL not supported
  QCString finalRef = makeRef(f, anchor);
  p->sectionTree.addSection(name,finalRef);
}
References f, caseconvert::file, makeRef(), setup::name, and p.
addContentsItem() [2/2]
void Qhp::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex, bool addToNavIndex, const Definition * def)
addFile() [1/2]
void Qhp::addFile (const QCString & fileName) [private]
Definition at line 382 of file qhp.cpp.
{
  p->files.insert(("<file>" + convertToXML(fileName) + "</file>").str());
}
References convertToXML(), and p.
Referenced by addImageFile(), addIndexFile(), and addStyleSheetFile().
addFile() [2/2]
void Qhp::addFile (const QCString &) [private]
addImageFile() [1/2]
void Qhp::addImageFile (const QCString & name)
Definition at line 392 of file qhp.cpp.
{
  addFile(fileName);
}
References addFile().
addImageFile() [2/2]
void Qhp::addImageFile (const QCString & name)
addIndexFile() [1/2]
void Qhp::addIndexFile (const QCString & name)
Definition at line 387 of file qhp.cpp.
{
  addFile(fileName);
}
References addFile().
addIndexFile() [2/2]
void Qhp::addIndexFile (const QCString & name)
addIndexItem() [1/2]
void Qhp::addIndexItem (const Definition * context, const MemberDef * md, const QCString & sectionAnchor, const QCString & title)
Definition at line 332 of file qhp.cpp.
{
  (void)word;
  //printf("addIndexItem(%s %s %s\n",
  // context?context->name().data():"<none>",
  // md?md->name().data():"<none>",
  // qPrint(word));
  if (md) // member
  {
    bool separateMemberPages = Config_getBool(SEPARATE_MEMBER_PAGES);
    if (context==0) // global member
    {
      if (md->getGroupDef())
        context = md->getGroupDef();
      else if (md->getFileDef())
        context = md->getFileDef();
    }
    if (context==0) return; // should not happen
    QCString cfname = md->getOutputFileBase();
    QCString argStr = md->argsString();
    QCString cfiname = context->getOutputFileBase();
    QCString level1 = context->name();
    QCString level2 = !word.isEmpty() ? word : md->name();
    QCString contRef = separateMemberPages ? cfname : cfiname;
    QCString anchor = !sectionAnchor.isEmpty() ? sectionAnchor : md->anchor();
    QCString ref;
    // <keyword name="foo" id="MyApplication::foo" ref="doc.html#foo"/>
    ref = makeRef(contRef, anchor);
    QCString id = level1+"::"+level2;
    writeIndent(p->index,3);
    p->index << "<keyword name=\"" << convertToXML(level2 + argStr) << "\""
                          " id=\"" << convertToXML(id + "_" + anchor) << "\""
                         " ref=\"" << convertToXML(ref) << "\"/>\n";
  }
  else if (context) // container
  {
    // <keyword name="Foo" id="Foo" ref="doc.html#Foo"/>
    QCString contRef = context->getOutputFileBase();
    QCString level1 = !word.isEmpty() ? word : context->name();
    QCString ref = makeRef(contRef,sectionAnchor);
    writeIndent(p->index,3);
    p->index << "<keyword name=\"" << convertToXML(level1) << "\""
             << " id=\"" << convertToXML(level1 +"_" + sectionAnchor) << "\""
             << " ref=\"" << convertToXML(ref) << "\"/>\n";
  }
}
References MemberDef::anchor(), MemberDef::argsString(), Config_getBool, convertToXML(), MemberDef::getFileDef(), MemberDef::getGroupDef(), Definition::getOutputFileBase(), MemberDef::getOutputFileBase(), QCString::isEmpty(), makeRef(), Definition::name(), p, word, and writeIndent().
addIndexItem() [2/2]
void Qhp::addIndexItem (const Definition * context, const MemberDef * md, const QCString & sectionAnchor, const QCString & title)
addStyleSheetFile() [1/2]
void Qhp::addStyleSheetFile (const QCString & name)
Definition at line 397 of file qhp.cpp.
{
  addFile(fileName);
}
References addFile().
addStyleSheetFile() [2/2]
void Qhp::addStyleSheetFile (const QCString & name)
decContentsDepth() [1/2]
void Qhp::decContentsDepth ()
Definition at line 304 of file qhp.cpp.
{
  p->sectionTree.decLevel();
}
References p.
decContentsDepth() [2/2]
void Qhp::decContentsDepth ()
finalize() [1/2]
void Qhp::finalize ()
Definition at line 267 of file qhp.cpp.
{
  // close root node
  p->sectionTree.decLevel();
  // Finish TOC
  p->sectionTree.writeToc(p->doc);
  // Finish index
  writeIndent(p->index,2);
  p->index << "</keywords>\n";
  p->doc << p->index.str();
  // Finish files
  writeIndent(p->doc,2);
  p->doc << "<files>\n";
  for (auto &s : p->files)
  {
    writeIndent(p->doc,3);
    p->doc << s.c_str() << "\n";
  }
  writeIndent(p->doc,2);
  p->doc << "</files>\n";
  writeIndent(p->doc,1);
  p->doc << "</filterSection>\n";
  p->doc << "</QtHelpProject>\n";
  p->doc.flush();
  p->docFile.close();
}
References p, s, and writeIndent().
finalize() [2/2]
void Qhp::finalize ()
getQchFileName() [1/2]
QCString Qhp::getQchFileName () [static]
Definition at line 402 of file qhp.cpp.
{
  QCString const & qchFile = Config_getString(QCH_FILE);
  if (!qchFile.isEmpty())
  {
    return qchFile;
  }
  QCString const & projectName = Config_getString(PROJECT_NAME);
  QCString const & versionText = Config_getString(PROJECT_NUMBER);
  return QCString("../qch/")
      + (projectName.isEmpty() ? QCString("index") : projectName)
      + (versionText.isEmpty() ? QCString("") : QCString("-") + versionText)
      + QCString(".qch");
}
References Config_getString, and QCString::isEmpty().
Referenced by runQHelpGenerator().
getQchFileName() [2/2]
static QCString Qhp::getQchFileName () [static]
incContentsDepth() [1/2]
void Qhp::incContentsDepth ()
Definition at line 299 of file qhp.cpp.
{
  p->sectionTree.incLevel();
}
References p.
incContentsDepth() [2/2]
void Qhp::incContentsDepth ()
initialize() [1/2]
void Qhp::initialize ()
Definition at line 194 of file qhp.cpp.
{
  /*
  <QtHelpProject version="1.0">
    <namespace>mycompany.com.myapplication.1_0</namespace>
    <virtualFolder>doc</virtualFolder>
    <customFilter name="My Application 1.0">
      <filterAttribute>myapp</filterAttribute>
      <filterAttribute>1.0</filterAttribute>
    </customFilter>
    <filterSection>
      <filterAttribute>myapp</filterAttribute>
      <filterAttribute>1.0</filterAttribute>
  ..
  */
  QCString fileName = Config_getString(HTML_OUTPUT) + "/" + qhpFileName;
  p->docFile.open(fileName.str(), std::ofstream::out | std::ofstream::binary);
  if (!p->docFile.is_open())
  {
    term("Could not open file %s for writing\n", fileName.data());
  }
  p->doc.setStream(&p->docFile);
  p->doc << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
  p->doc << "<QtHelpProject version=\"1.0\">\n";
  writeIndent(p->doc,1);
  p->doc << "<namespace>" << convertToXML(Config_getString(QHP_NAMESPACE)) << "</namespace>\n";
  writeIndent(p->doc,1);
  p->doc << "<virtualFolder>" << convertToXML(Config_getString(QHP_VIRTUAL_FOLDER)) << "</virtualFolder>\n";
  // Add custom filter
  QCString filterName = Config_getString(QHP_CUST_FILTER_NAME);
  if (!filterName.isEmpty())
  {
    writeIndent(p->doc,1);
    p->doc << "<customFilter name=\"" << convertToXML(filterName) << "\">\n";
    StringVector customFilterAttributes =
        split(Config_getString(QHP_CUST_FILTER_ATTRS).str(), " ");
    for (const auto &attr : customFilterAttributes)
    {
      writeIndent(p->doc,2);
      p->doc << "<filterAttribute>" << convertToXML(QCString(attr)) << "</filterAttribute>\n";
    }
    writeIndent(p->doc,1);
    p->doc << "</customFilter>\n";
  }
  writeIndent(p->doc,1);
  p->doc << "<filterSection>\n";
  // Add section attributes
  StringVector sectionFilterAttributes = split(Config_getString(QHP_SECT_FILTER_ATTRS).str(), " ");
  // always add doxygen as filter attribute
  if (std::find(sectionFilterAttributes.begin(), sectionFilterAttributes.end(), "doxygen") ==
      sectionFilterAttributes.end())
  {
    sectionFilterAttributes.push_back("doxygen");
  }
  for (const auto &attr : sectionFilterAttributes)
  {
    writeIndent(p->doc,2);
    p->doc << "<filterAttribute>" << convertToXML(QCString(attr)) << "</filterAttribute>\n";
  }
  // Add extra root node to the TOC
  p->sectionTree.addSection(getFullProjectName(),"index"+Doxygen::htmlFileExtension);
  p->sectionTree.incLevel();
  writeIndent(p->index,2);
  p->index << "<keywords>\n";
}
References Config_getString, convertToXML(), QCString::data(), getFullProjectName(), Doxygen::htmlFileExtension, QCString::isEmpty(), out, p, qhpFileName, split(), QCString::str(), term(), and writeIndent().
initialize() [2/2]
void Qhp::initialize ()
Member Data Documentation
p
std::unique_ptr< Private > Qhp::p [private]
Definition at line 51 of file qhp.h.
Referenced by addContentsItem(), addFile(), addIndexItem(), decContentsDepth(), finalize(), incContentsDepth(), and initialize().
qhpFileName
static const QCString Qhp::qhpFileName = `index.qhp` [inline], [static]
Definition at line 45 of file qhp.h.
Referenced by initialize(), and runQHelpGenerator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/qhp.h
doxygen/src/qhp.h
doxygen/build/doxygen/src/qhp.cpp
doxygen/src/qhp.cpp