Operator Class Reference
Class representing operators that can appear in template expressions.
Public Types
enum Type {
Or
, And
, Not
, In
,
Equal
, NotEqual
, Less
, Greater
,
LessEqual
, GreaterEqual
, Plus
, Minus
,
Multiply
, Divide
, Modulo
, Filter
,
Colon
, Comma
, LeftParen
, RightParen
,
Last
, Or
, And
, Not
,
In
, Equal
, NotEqual
, Less
,
Greater
, LessEqual
, GreaterEqual
, Plus
,
Minus
, Multiply
, Divide
, Modulo
,
Filter
, Colon
, Comma
, LeftParen
,
RightParen
, Last
 }
enum Type {
Or
, And
, Not
, In
,
Equal
, NotEqual
, Less
, Greater
,
LessEqual
, GreaterEqual
, Plus
, Minus
,
Multiply
, Divide
, Modulo
, Filter
,
Colon
, Comma
, LeftParen
, RightParen
,
Last
, Or
, And
, Not
,
In
, Equal
, NotEqual
, Less
,
Greater
, LessEqual
, GreaterEqual
, Plus
,
Minus
, Multiply
, Divide
, Modulo
,
Filter
, Colon
, Comma
, LeftParen
,
RightParen
, Last
 }
Static Public Member Functions
static const char * toString (Type op)
static const char * toString (Type op)
Detailed Description
Class representing operators that can appear in template expressions.
Definition at line 555 of file template.cpp.
Member Enumeration Documentation
Type [1/2]
enum Operator::Type
Enumerator
Or
And
Not
In
Equal
NotEqual
Less
Greater
LessEqual
GreaterEqual
Plus
Minus
Multiply
Divide
Modulo
Filter
Colon
Comma
LeftParen
RightParen
Last
Or
And
Not
In
Equal
NotEqual
Less
Greater
LessEqual
GreaterEqual
Plus
Minus
Multiply
Divide
Modulo
Filter
Colon
Comma
LeftParen
RightParen
Last
Definition at line 570 of file template.cpp.
    {
      Or, And, Not, In, Equal, NotEqual, Less, Greater, LessEqual,
      GreaterEqual, Plus, Minus, Multiply, Divide, Modulo, Filter, Colon, Comma,
      LeftParen, RightParen,
      Last
    };
Type [2/2]
enum Operator::Type
Enumerator
Or
And
Not
In
Equal
NotEqual
Less
Greater
LessEqual
GreaterEqual
Plus
Minus
Multiply
Divide
Modulo
Filter
Colon
Comma
LeftParen
RightParen
Last
Or
And
Not
In
Equal
NotEqual
Less
Greater
LessEqual
GreaterEqual
Plus
Minus
Multiply
Divide
Modulo
Filter
Colon
Comma
LeftParen
RightParen
Last
Definition at line 570 of file template.cpp.
    {
      Or, And, Not, In, Equal, NotEqual, Less, Greater, LessEqual,
      GreaterEqual, Plus, Minus, Multiply, Divide, Modulo, Filter, Colon, Comma,
      LeftParen, RightParen,
      Last
    };
Member Function Documentation
toString() [1/2]
static const char * Operator::toString (Type op) [inline], [static]
Definition at line 578 of file template.cpp.
    {
      switch(op)
      {
        case Or: return "or";
        case And: return "and";
        case Not: return "not";
        case In: return "in";
        case Equal: return "==";
        case NotEqual: return "!=";
        case Less: return "<";
        case Greater: return ">";
        case LessEqual: return "<=";
        case GreaterEqual: return ">=";
        case Plus: return "+";
        case Minus: return "-";
        case Multiply: return "*";
        case Divide: return "/";
        case Modulo: return "%";
        case Filter: return "|";
        case Colon: return ":";
        case Comma: return ",";
        case LeftParen: return "(";
        case RightParen: return ")";
        case Last: return "?";
      }
      return "?";
    }
References And, Colon, Comma, Divide, Equal, Filter, Greater, GreaterEqual, In, Last, LeftParen, Less, LessEqual, Minus, Modulo, Multiply, Not, NotEqual, Or, Plus, and RightParen.
Referenced by ExprAstBinary::ExprAstBinary(), ExprAstUnary::ExprAstUnary(), and ExpressionParser::parsePrimaryExpression().
toString() [2/2]
static const char * Operator::toString (Type op) [inline], [static]
Definition at line 578 of file template.cpp.
    {
      switch(op)
      {
        case Or: return "or";
        case And: return "and";
        case Not: return "not";
        case In: return "in";
        case Equal: return "==";
        case NotEqual: return "!=";
        case Less: return "<";
        case Greater: return ">";
        case LessEqual: return "<=";
        case GreaterEqual: return ">=";
        case Plus: return "+";
        case Minus: return "-";
        case Multiply: return "*";
        case Divide: return "/";
        case Modulo: return "%";
        case Filter: return "|";
        case Colon: return ":";
        case Comma: return ",";
        case LeftParen: return "(";
        case RightParen: return ")";
        case Last: return "?";
      }
      return "?";
    }
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp