DirDefImpl Class Reference
Public Member Functions
DirDefImpl (const QCString &path)
virtual ~DirDefImpl ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual QCString displayName (bool=TRUE) const
virtual const QCString shortName () const
virtual void addSubDir (DirDef *subdir)
virtual const FileList & getFiles () const
virtual void addFile (const FileDef *fd)
virtual const DirList & subDirs () const
virtual bool hasSubdirs () const
virtual int level () const
virtual DirDef * parent () const
virtual int dirCount () const
virtual const UsedDirLinkedMap & usedDirs () const
virtual bool isParentOf (const DirDef *dir) const
virtual bool depGraphIsTrivial () const
virtual QCString shortTitle () const
virtual bool hasDetailedDescription () const
virtual void writeDocumentation (OutputList &ol)
virtual void writeTagFile (TextStream &t)
virtual void setDiskName (const QCString &name)
virtual void sort ()
virtual void setParent (DirDef *parent)
virtual void setDirCount (int count)
virtual void setLevel ()
virtual void addUsesDependency (const DirDef *usedDir, const FileDef *srcFd, const FileDef *dstFd, bool srcDirect, bool dstDirect)
virtual void computeDependencies ()
DirDefImpl (const QCString &path)
virtual ~DirDefImpl ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual QCString displayName (bool=TRUE) const
virtual const QCString shortName () const
virtual void addSubDir (DirDef *subdir)
virtual const FileList & getFiles () const
virtual void addFile (const FileDef *fd)
virtual const DirList & subDirs () const
virtual bool hasSubdirs () const
virtual int level () const
virtual DirDef * parent () const
virtual int dirCount () const
virtual const UsedDirLinkedMap & usedDirs () const
virtual bool isParentOf (const DirDef *dir) const
virtual bool depGraphIsTrivial () const
virtual QCString shortTitle () const
virtual bool hasDetailedDescription () const
virtual void writeDocumentation (OutputList &ol)
virtual void writeTagFile (TextStream &t)
virtual void setDiskName (const QCString &name)
virtual void sort ()
virtual void setParent (DirDef *parent)
virtual void setDirCount (int count)
virtual void setLevel ()
virtual void addUsesDependency (const DirDef *usedDir, const FileDef *srcFd, const FileDef *dstFd, bool srcDirect, bool dstDirect)
virtual void computeDependencies ()
Static Public Member Functions
static DirDef * mergeDirectoryInTree (const QCString &path)
static DirDef * mergeDirectoryInTree (const QCString &path)
Private Member Functions
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void writeDirectoryGraph (OutputList &ol)
void writeSubDirList (OutputList &ol)
void writeFileList (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void writeDirectoryGraph (OutputList &ol)
void writeSubDirList (OutputList &ol)
void writeFileList (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
Static Private Member Functions
static DirDef * createNewDir (const QCString &path)
static bool matchPath (const QCString &path, const StringVector &l)
static DirDef * createNewDir (const QCString &path)
static bool matchPath (const QCString &path, const StringVector &l)
Private Attributes
DirList m_subdirs
QCString m_dispName
QCString m_shortName
QCString m_diskName
FileList m_fileList
int m_dirCount = -1
int m_level
DirDef * m_parent
UsedDirLinkedMap m_usedDirs
Additional Inherited Members
Detailed Description
Definition at line 37 of file dirdef.cpp.
Constructor & Destructor Documentation
DirDefImpl() [1/2]
DirDefImpl::DirDefImpl (const QCString & path)
Definition at line 111 of file dirdef.cpp.
                                           : DefinitionMixin(path,1,1,path)
{
  bool fullPathNames = Config_getBool(FULL_PATH_NAMES);
  // get display name (stripping the paths mentioned in STRIP_FROM_PATH)
  // get short name (last part of path)
  m_shortName = path;
  m_diskName = path;
  if (m_shortName.at(m_shortName.length()-1)=='/')
  { // strip trailing /
    m_shortName = m_shortName.left(m_shortName.length()-1);
  }
  int pi=m_shortName.findRev('/');
  if (pi!=-1)
  { // remove everything till the last /
    m_shortName = m_shortName.mid(pi+1);
  }
  setLocalName(m_shortName);
  m_dispName = fullPathNames ? stripFromPath(path) : m_shortName;
  if (m_dispName.length()>0 && m_dispName.at(m_dispName.length()-1)=='/')
  { // strip trailing /
    m_dispName = m_dispName.left(m_dispName.length()-1);
  }
  m_level=-1;
  m_parent=0;
}
References QCString::at(), Config_getBool, QCString::findRev(), QCString::left(), QCString::length(), m_diskName, m_dispName, m_level, m_parent, m_shortName, QCString::mid(), DefinitionMixin< DirDef >::setLocalName(), and stripFromPath().
 DirDefImpl() [1/2]
DirDefImpl::~DirDefImpl () [virtual]
Definition at line 138 of file dirdef.cpp.
{
}
DirDefImpl() [2/2]
DirDefImpl::DirDefImpl (const QCString & path)
 DirDefImpl() [2/2]
virtual DirDefImpl::~DirDefImpl () [virtual]
Member Function Documentation
addFile() [1/2]
void DirDefImpl::addFile (const FileDef * fd) [virtual]
Implements DirDef.
Definition at line 169 of file dirdef.cpp.
{
  m_fileList.push_back(fd);
  const_cast<FileDef*>(fd)->setDirDef(this);
}
References m_fileList.
addFile() [2/2]
virtual void DirDefImpl::addFile (const FileDef * fd) [virtual]
Implements DirDef.
addSubDir() [1/2]
void DirDefImpl::addSubDir (DirDef * subdir) [virtual]
Implements DirDef.
Definition at line 152 of file dirdef.cpp.
{
  m_subdirs.push_back(subdir);
  subdir->setOuterScope(this);
  subdir->setParent(this);
}
References m_subdirs, DefinitionMutable::setOuterScope(), and DirDef::setParent().
addSubDir() [2/2]
virtual void DirDefImpl::addSubDir (DirDef * subdir) [virtual]
Implements DirDef.
addUsesDependency() [1/2]
void DirDefImpl::addUsesDependency (const DirDef * dir, const FileDef * srcFd, const FileDef * dstFd, bool srcDirect, bool dstDirect) [virtual]
Add as `uses` dependency between this dir and dir, that was caused by a dependency on file fd. srcDirect and dstDirect indicate if it is a direct dependencies (true) or if the dependencies was indirect (e.g. a parent dir that has a child dir that has the dependencies)
Implements DirDef.
Definition at line 648 of file dirdef.cpp.
{
  if (this==dir) return; // do not add self-dependencies
  //static int count=0;
  //printf(" %d add dependency %s->%s due to %s->%s\n",
  // count++,qPrint(shortName()),
  // qPrint(dir->shortName()),
  // qPrint(srcFd->name()),
  // qPrint(dstFd->name()));
  // levels match => add direct dependency
  bool added=FALSE;
  UsedDir *usedDir = m_usedDirs.find(dir->getOutputFileBase());
  if (usedDir) // dir dependency already present
  {
     const FilePair *usedPair = usedDir->findFilePair(FilePair::key(srcFd,dstFd));
     if (usedPair==0) // new file dependency
     {
       //printf(" => new file\n");
       usedDir->addFileDep(srcFd,dstFd, srcDirect, dstDirect);
       added=TRUE;
     }
     else
     {
       // dir & file dependency already added
     }
  }
  else // new directory dependency
  {
    //printf(" => new file\n");
    auto newUsedDir = std::make_unique<UsedDir>(dir);
    newUsedDir->addFileDep(srcFd,dstFd, srcDirect, dstDirect);
    m_usedDirs.add(dir->getOutputFileBase(),std::move(newUsedDir));
    added=TRUE;
  }
  if (added)
  {
    if (dir->parent())
    {
      // add relation to parent of used dir
      addUsesDependency(dir->parent(),
                        srcFd,
                        dstFd,
                        srcDirect,
                        false); // indirect dependency on dest dir
    }
    if (parent())
    {
      // add relation for the parent of this dir as well
      parent()->addUsesDependency(dir,
                                 srcFd,
                                 dstFd,
                                 false, // indirect dependency from source dir
                                 dstDirect);
    }
  }
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), UsedDir::addFileDep(), addUsesDependency(), DirDef::addUsesDependency(), FALSE, LinkedMap< T, Hash, KeyEqual, Map >::find(), UsedDir::findFilePair(), DirDef::getOutputFileBase(), FilePair::key(), m_usedDirs, parent(), DirDef::parent(), and TRUE.
Referenced by addUsesDependency(), and computeDependencies().
addUsesDependency() [2/2]
virtual void DirDefImpl::addUsesDependency (const DirDef * usedDir, const FileDef * srcFd, const FileDef * dstFd, bool srcDirect, bool dstDirect) [virtual]
Implements DirDef.
anchor() [1/2]
virtual QCString DirDefImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements DirDef.
Definition at line 46 of file dirdef.cpp.
{ return QCString(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString DirDefImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements DirDef.
Definition at line 46 of file dirdef.cpp.
{ return QCString(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
codeSymbolType() [1/2]
virtual CodeSymbolType DirDefImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 44 of file dirdef.cpp.
{ return CodeSymbolType::Default; }
References Default.
codeSymbolType() [2/2]
virtual CodeSymbolType DirDefImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 44 of file dirdef.cpp.
{ return CodeSymbolType::Default; }
References Default.
computeDependencies() [1/2]
void DirDefImpl::computeDependencies () [virtual]
Computes the dependencies between directories
Implements DirDef.
Definition at line 709 of file dirdef.cpp.
{
  for (const auto &fd : m_fileList)
  {
    //printf(" File %s\n",qPrint(fd->name()));
    //printf("** dir=%s file=%s\n",qPrint(shortName()),qPrint(fd->name()));
    for (const auto &ii : fd->includeFileList())
    {
      //printf(" > %s\n",qPrint(ii->includeName));
      //printf(" #include %s\n",qPrint(ii->includeName));
      if (ii.fileDef && ii.fileDef->isLinkable()) // linkable file
      {
        DirDef *usedDir = ii.fileDef->getDirDef();
        if (usedDir)
        {
          // add dependency: thisDir->usedDir
          //static int count=0;
          //printf(" %d: add dependency %s->%s\n",count++,qPrint(name()),qPrint(usedDir->name()));
          addUsesDependency(usedDir,fd,ii.fileDef,true,true);
        }
      }
    }
  }
  std::sort(m_usedDirs.begin(),m_usedDirs.end(),
            [](const auto &u1,const auto &u2)
            { return qstricmp(u1->dir()->getOutputFileBase(),u2->dir()->getOutputFileBase())<0; });
  for (const auto& usedDirectory : m_usedDirs)
  {
    usedDirectory->sort();
  }
}
References addUsesDependency(), LinkedMap< T, Hash, KeyEqual, Map >::begin(), LinkedMap< T, Hash, KeyEqual, Map >::end(), m_fileList, and m_usedDirs.
computeDependencies() [2/2]
virtual void DirDefImpl::computeDependencies () [virtual]
Implements DirDef.
createNewDir() [1/2]
DirDef * DirDefImpl::createNewDir (const QCString & path) [static], [private]
Definition at line 796 of file dirdef.cpp.
{
  ASSERT(path!=0);
  DirDef *dir = Doxygen::dirLinkedMap->find(path);
  if (dir==0) // new dir
  {
    dir = Doxygen::dirLinkedMap->add(path,
            std::unique_ptr<DirDef>(
              createDirDef(path)));
    //printf("Adding new dir %s\n",path);
    //printf("createNewDir %s short=%s\n",path,qPrint(dir->shortName()));
  }
  return dir;
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), ASSERT, createDirDef(), Doxygen::dirLinkedMap, and LinkedMap< T, Hash, KeyEqual, Map >::find().
Referenced by mergeDirectoryInTree().
createNewDir() [2/2]
static DirDef * DirDefImpl::createNewDir (const QCString & path) [static], [private]
definitionType() [1/2]
virtual DefType DirDefImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements DirDef.
Definition at line 43 of file dirdef.cpp.
{ return TypeDir; }
References Definition::TypeDir.
definitionType() [2/2]
virtual DefType DirDefImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements DirDef.
Definition at line 43 of file dirdef.cpp.
{ return TypeDir; }
References Definition::TypeDir.
depGraphIsTrivial() [1/2]
bool DirDefImpl::depGraphIsTrivial () const [virtual]
Implements DirDef.
Definition at line 753 of file dirdef.cpp.
{
  return m_usedDirs.empty() && m_parent==nullptr;
}
References LinkedMap< T, Hash, KeyEqual, Map >::empty(), m_parent, and m_usedDirs.
depGraphIsTrivial() [2/2]
virtual bool DirDefImpl::depGraphIsTrivial () const [virtual]
Implements DirDef.
dirCount() [1/2]
virtual int DirDefImpl::dirCount () const [inline], [virtual]
Implements DirDef.
Definition at line 58 of file dirdef.cpp.
{ return m_dirCount; }
References m_dirCount.
dirCount() [2/2]
virtual int DirDefImpl::dirCount () const [inline], [virtual]
Implements DirDef.
Definition at line 58 of file dirdef.cpp.
{ return m_dirCount; }
References m_dirCount.
displayName() [1/2]
virtual QCString DirDefImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements DirDef.
Definition at line 49 of file dirdef.cpp.
{ return m_dispName; }
References m_dispName.
Referenced by writeDirectoryGraph(), and writeTagFile().
displayName() [2/2]
virtual QCString DirDefImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements DirDef.
Definition at line 49 of file dirdef.cpp.
{ return m_dispName; }
References m_dispName.
endMemberDeclarations() [1/2]
void DirDefImpl::endMemberDeclarations (OutputList & ol) [private]
Definition at line 455 of file dirdef.cpp.
{
  ol.endMemberSections();
}
References OutputList::endMemberSections().
Referenced by writeDocumentation().
endMemberDeclarations() [2/2]
void DirDefImpl::endMemberDeclarations (OutputList & ol) [private]
getFiles() [1/2]
virtual const FileList & DirDefImpl::getFiles () const [inline], [virtual]
Implements DirDef.
Definition at line 52 of file dirdef.cpp.
{ return m_fileList; }
References m_fileList.
getFiles() [2/2]
virtual const FileList & DirDefImpl::getFiles () const [inline], [virtual]
Implements DirDef.
Definition at line 52 of file dirdef.cpp.
{ return m_fileList; }
References m_fileList.
getOutputFileBase() [1/2]
QCString DirDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements DirDef.
Definition at line 213 of file dirdef.cpp.
{
  //printf("DirDefImpl::getOutputFileBase() %s->dir_%s\n",
  // qPrint(m_diskName),qPrint(encodeDirName(m_diskName)));
  return "dir_"+encodeDirName(m_diskName);
}
References encodeDirName(), and m_diskName.
Referenced by writeDocumentation(), and writeTagFile().
getOutputFileBase() [2/2]
virtual QCString DirDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements DirDef.
hasDetailedDescription() [1/2]
bool DirDefImpl::hasDetailedDescription () const [virtual]
Implements DirDef.
Definition at line 465 of file dirdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  return (!briefDescription().isEmpty() && repeatBrief) || !documentation().isEmpty();
}
References DefinitionMixin< DirDef >::briefDescription(), Config_getBool, DefinitionMixin< DirDef >::documentation(), and QCString::isEmpty().
hasDetailedDescription() [2/2]
virtual bool DirDefImpl::hasDetailedDescription () const [virtual]
Implements DirDef.
hasSubdirs() [1/2]
virtual bool DirDefImpl::hasSubdirs () const [inline], [virtual]
Implements DirDef.
Definition at line 55 of file dirdef.cpp.
{ return !m_subdirs.empty(); }
References m_subdirs.
hasSubdirs() [2/2]
virtual bool DirDefImpl::hasSubdirs () const [inline], [virtual]
Implements DirDef.
Definition at line 55 of file dirdef.cpp.
{ return !m_subdirs.empty(); }
References m_subdirs.
isLinkable() [1/2]
bool DirDefImpl::isLinkable () const [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements DirDef.
Definition at line 147 of file dirdef.cpp.
{
  return isReference() || isLinkableInProject();
}
References isLinkableInProject(), and DefinitionMixin< DirDef >::isReference().
isLinkable() [2/2]
virtual bool DirDefImpl::isLinkable () const [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements DirDef.
isLinkableInProject() [1/2]
bool DirDefImpl::isLinkableInProject () const [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements DirDef.
Definition at line 142 of file dirdef.cpp.
{
  return !isReference();
}
References DefinitionMixin< DirDef >::isReference().
Referenced by isLinkable().
isLinkableInProject() [2/2]
virtual bool DirDefImpl::isLinkableInProject () const [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements DirDef.
isParentOf() [1/2]
bool DirDefImpl::isParentOf (const DirDef * dir) const [virtual]
Implements DirDef.
Definition at line 743 of file dirdef.cpp.
{
  if (dir->parent()==this) // this is a parent of dir
    return TRUE;
  else if (dir->parent()) // repeat for the parent of dir
    return isParentOf(dir->parent());
  else
    return FALSE;
}
References FALSE, isParentOf(), DirDef::parent(), and TRUE.
Referenced by isParentOf().
isParentOf() [2/2]
virtual bool DirDefImpl::isParentOf (const DirDef * dir) const [virtual]
Implements DirDef.
level() [1/2]
virtual int DirDefImpl::level () const [inline], [virtual]
Implements DirDef.
Definition at line 56 of file dirdef.cpp.
{ return m_level; }
References m_level.
Referenced by doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docHeadingType::buildAttributes(), doxmlparser.compound.docHeadingType::exportAttributes(), doxmlparser.compound.docHeadingType::get_level(), and doxmlparser.compound.docHeadingType::set_level().
level() [2/2]
virtual int DirDefImpl::level () const [inline], [virtual]
Implements DirDef.
Definition at line 56 of file dirdef.cpp.
{ return m_level; }
References m_level.
Referenced by doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docHeadingType::buildAttributes(), doxmlparser.compound.docHeadingType::exportAttributes(), doxmlparser.compound.docHeadingType::get_level(), and doxmlparser.compound.docHeadingType::set_level().
matchPath() [1/2]
bool DirDefImpl::matchPath (const QCString & path, const StringVector & l) [static], [private]
Definition at line 811 of file dirdef.cpp.
{
  for (const auto &s : l)
  {
    std::string prefix = s.substr(0,path.length());
    if (qstricmp(prefix.c_str(),path)==0) // case insensitive compare
    {
      return TRUE;
    }
  }
  return FALSE;
}
References FALSE, QCString::length(), qstricmp(), s, string, and TRUE.
Referenced by mergeDirectoryInTree().
matchPath() [2/2]
static bool DirDefImpl::matchPath (const QCString & path, const StringVector & l) [static], [private]
mergeDirectoryInTree() [1/2]
DirDef * DirDefImpl::mergeDirectoryInTree (const QCString & path) [static]
strip part of path if it matches one of the paths in the Config_getList(STRIP_FROM_PATH) list
Definition at line 827 of file dirdef.cpp.
{
  //printf("DirDefImpl::mergeDirectoryInTree(%s)\n",qPrint(path));
  int p=0,i=0;
  DirDef *dir=0;
  while ((i=path.find('/',p))!=-1)
  {
    QCString part=path.left(i+1);
    if (!matchPath(part,Config_getList(STRIP_FROM_PATH)) && (part!="/" && part!="//"))
    {
      dir=createNewDir(part);
    }
    p=i+1;
  }
  return dir;
}
References Config_getList, createNewDir(), QCString::find(), QCString::left(), matchPath(), and p.
Referenced by buildDirectories().
mergeDirectoryInTree() [2/2]
static DirDef * DirDefImpl::mergeDirectoryInTree (const QCString & path) [static]
parent() [1/2]
virtual DirDef * DirDefImpl::parent () const [inline], [virtual]
Implements DirDef.
Definition at line 57 of file dirdef.cpp.
{ return m_parent; }
References m_parent.
Referenced by addUsesDependency(), and setLevel().
parent() [2/2]
virtual DirDef * DirDefImpl::parent () const [inline], [virtual]
Implements DirDef.
Definition at line 57 of file dirdef.cpp.
{ return m_parent; }
References m_parent.
setDirCount() [1/2]
void DirDefImpl::setDirCount (int count) [virtual]
Implements DirDef.
Definition at line 164 of file dirdef.cpp.
{
  m_dirCount=count;
}
References m_dirCount.
setDirCount() [2/2]
virtual void DirDefImpl::setDirCount (int count) [virtual]
Implements DirDef.
setDiskName() [1/2]
virtual void DirDefImpl::setDiskName (const QCString & name) [inline], [virtual]
Implements DirDef.
Definition at line 66 of file dirdef.cpp.
{ m_diskName = name; }
References m_diskName, and DefinitionMixin< DirDef >::name().
setDiskName() [2/2]
virtual void DirDefImpl::setDiskName (const QCString & name) [inline], [virtual]
Implements DirDef.
Definition at line 66 of file dirdef.cpp.
{ m_diskName = name; }
References m_diskName, and DefinitionMixin< DirDef >::name().
setLevel() [1/2]
void DirDefImpl::setLevel () [virtual]
Implements DirDef.
Definition at line 626 of file dirdef.cpp.
{
  if (m_level==-1) // level not set before
  {
    DirDef *p = parent();
    if (p)
    {
      p->setLevel();
      m_level = p->level()+1;
    }
    else
    {
      m_level = 0;
    }
  }
}
References m_level, p, and parent().
setLevel() [2/2]
virtual void DirDefImpl::setLevel () [virtual]
Implements DirDef.
setParent() [1/2]
void DirDefImpl::setParent (DirDef * parent) [virtual]
Implements DirDef.
Definition at line 159 of file dirdef.cpp.
{
   m_parent=p;
}
References m_parent, and p.
setParent() [2/2]
virtual void DirDefImpl::setParent (DirDef * parent) [virtual]
Implements DirDef.
shortName() [1/2]
virtual const QCString DirDefImpl::shortName () const [inline], [virtual]
Implements DirDef.
Definition at line 50 of file dirdef.cpp.
{ return m_shortName; }
References m_shortName.
Referenced by writeDirectoryGraph().
shortName() [2/2]
virtual const QCString DirDefImpl::shortName () const [inline], [virtual]
Implements DirDef.
Definition at line 50 of file dirdef.cpp.
{ return m_shortName; }
References m_shortName.
shortTitle() [1/2]
QCString DirDefImpl::shortTitle () const [virtual]
Implements DirDef.
Definition at line 460 of file dirdef.cpp.
{
  return theTranslator->trDirReference(m_shortName);
}
References m_shortName, theTranslator, and Translator::trDirReference().
Referenced by writeDocumentation().
shortTitle() [2/2]
virtual QCString DirDefImpl::shortTitle () const [virtual]
Implements DirDef.
sort() [1/2]
void DirDefImpl::sort () [virtual]
Implements DirDef.
Definition at line 175 of file dirdef.cpp.
{
  std::sort(m_subdirs.begin(), m_subdirs.end(), compareDirDefs);
  std::sort(m_fileList.begin(), m_fileList.end(), compareFileDefs);
}
References compareDirDefs(), compareFileDefs(), m_fileList, and m_subdirs.
Referenced by translator.TrManager::generateTranslatorReport().
sort() [2/2]
virtual void DirDefImpl::sort () [virtual]
Implements DirDef.
Referenced by translator.TrManager::generateTranslatorReport().
startMemberDeclarations() [1/2]
void DirDefImpl::startMemberDeclarations (OutputList & ol) [private]
Definition at line 450 of file dirdef.cpp.
{
  ol.startMemberSections();
}
References OutputList::startMemberSections().
Referenced by writeDocumentation().
startMemberDeclarations() [2/2]
void DirDefImpl::startMemberDeclarations (OutputList & ol) [private]
subDirs() [1/2]
virtual const DirList & DirDefImpl::subDirs () const [inline], [virtual]
Implements DirDef.
Definition at line 54 of file dirdef.cpp.
{ return m_subdirs; }
References m_subdirs.
subDirs() [2/2]
virtual const DirList & DirDefImpl::subDirs () const [inline], [virtual]
Implements DirDef.
Definition at line 54 of file dirdef.cpp.
{ return m_subdirs; }
References m_subdirs.
usedDirs() [1/2]
virtual const UsedDirLinkedMap & DirDefImpl::usedDirs () const [inline], [virtual]
Implements DirDef.
Definition at line 59 of file dirdef.cpp.
{ return m_usedDirs; }
References m_usedDirs.
usedDirs() [2/2]
virtual const UsedDirLinkedMap & DirDefImpl::usedDirs () const [inline], [virtual]
Implements DirDef.
Definition at line 59 of file dirdef.cpp.
{ return m_usedDirs; }
References m_usedDirs.
writeBriefDescription() [1/2]
void DirDefImpl::writeBriefDescription (OutputList & ol) [private]
Definition at line 267 of file dirdef.cpp.
{
  if (hasBriefDescription())
  {
    auto parser { createDocParser() };
    auto ast { validatingParseDoc(
         *parser.get(), briefFile(),briefLine(),this,0,briefDescription(),TRUE,FALSE,
         QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startParagraph();
      ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Man);
      ol.writeString(" - ");
      ol.popGeneratorState();
      ol.writeDoc(ast.get(),this,0);
      ol.pushGeneratorState();
      ol.disable(OutputGenerator::RTF);
      ol.writeString(" \n");
      ol.enable(OutputGenerator::RTF);
      if (Config_getBool(REPEAT_BRIEF) ||
          !documentation().isEmpty()
         )
      {
        ol.disableAllBut(OutputGenerator::Html);
        ol.startTextLink(QCString(),"details");
        ol.parseText(theTranslator->trMore());
        ol.endTextLink();
      }
      ol.popGeneratorState();
      ol.endParagraph();
    }
  }
  ol.writeSynopsis();
}
References DefinitionMixin< DirDef >::briefDescription(), DefinitionMixin< DirDef >::briefFile(), DefinitionMixin< DirDef >::briefLine(), Config_getBool, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< DirDef >::documentation(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), FALSE, DefinitionMixin< DirDef >::hasBriefDescription(), OutputGenerator::Html, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, Translator::trMore(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeBriefDescription() [2/2]
void DirDefImpl::writeBriefDescription (OutputList & ol) [private]
writeDetailedDescription() [1/2]
void DirDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) [private]
Definition at line 220 of file dirdef.cpp.
{
  if ((!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF)) ||
      !documentation().isEmpty())
  {
    ol.pushGeneratorState();
      ol.disable(OutputGenerator::Html);
      ol.writeRuler();
    ol.popGeneratorState();
    ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Html);
      ol.writeAnchor(QCString(),"details");
    ol.popGeneratorState();
    ol.startGroupHeader();
    ol.parseText(title);
    ol.endGroupHeader();
    // repeat brief description
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF))
    {
      ol.generateDoc(briefFile(),briefLine(),this,0,briefDescription(),FALSE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    // separator between brief and details
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF) &&
        !documentation().isEmpty())
    {
      ol.pushGeneratorState();
        ol.disable(OutputGenerator::Man);
        ol.disable(OutputGenerator::RTF);
        // ol.newParagraph(); // FIXME:PARA
        ol.enableAll();
        ol.disableAllBut(OutputGenerator::Man);
        ol.enable(OutputGenerator::Latex);
        ol.writeString("\n\n");
      ol.popGeneratorState();
    }
    // write documentation
    if (!documentation().isEmpty())
    {
      ol.generateDoc(docFile(),docLine(),this,0,documentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
  }
}
References DefinitionMixin< DirDef >::briefDescription(), DefinitionMixin< DirDef >::briefFile(), DefinitionMixin< DirDef >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< DirDef >::docFile(), DefinitionMixin< DirDef >::docLine(), DefinitionMixin< DirDef >::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endGroupHeader(), FALSE, OutputList::generateDoc(), OutputGenerator::Html, OutputGenerator::Latex, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startGroupHeader(), TRUE, OutputList::writeAnchor(), OutputList::writeRuler(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDetailedDescription() [2/2]
void DirDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) [private]
writeDirectoryGraph() [1/2]
void DirDefImpl::writeDirectoryGraph (OutputList & ol) [private]
Definition at line 305 of file dirdef.cpp.
{
  // write graph dependency graph
  if (Config_getBool(DIRECTORY_GRAPH) && Config_getBool(HAVE_DOT))
  {
    DotDirDeps dirDep(this);
    if (!dirDep.isTrivial())
    {
      msg("Generating dependency graph for directory %s\n",qPrint(displayName()));
      ol.disable(OutputGenerator::Man);
      //ol.startParagraph();
      ol.startDirDepGraph();
      ol.parseText(theTranslator->trDirDepGraph(shortName()));
      ol.endDirDepGraph(dirDep);
      //ol.endParagraph();
      ol.enableAll();
    }
  }
}
References Config_getBool, OutputList::disable(), displayName(), OutputList::enableAll(), OutputList::endDirDepGraph(), DotDirDeps::isTrivial(), OutputGenerator::Man, msg(), OutputList::parseText(), qPrint(), shortName(), OutputList::startDirDepGraph(), theTranslator, and Translator::trDirDepGraph().
Referenced by writeDocumentation().
writeDirectoryGraph() [2/2]
void DirDefImpl::writeDirectoryGraph (OutputList & ol) [private]
writeDocumentation() [1/2]
void DirDefImpl::writeDocumentation (OutputList & ol) [virtual]
Implements DirDef.
Definition at line 508 of file dirdef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  ol.pushGeneratorState();
  QCString title=theTranslator->trDirReference(m_dispName);
  startFile(ol,getOutputFileBase(),name(),title,HLI_Files,!generateTreeView);
  if (!generateTreeView)
  {
    // write navigation path
    writeNavigationPath(ol);
    ol.endQuickIndices();
  }
  startTitle(ol,getOutputFileBase());
  ol.pushGeneratorState();
    ol.disableAllBut(OutputGenerator::Html);
    ol.parseText(shortTitle());
    ol.enableAll();
    ol.disable(OutputGenerator::Html);
    ol.parseText(title);
  ol.popGeneratorState();
  endTitle(ol,getOutputFileBase(),title);
  ol.startContents();
  //---------------------------------------- start flexible part -------------------------------
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Directory))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol);
        break;
      case LayoutDocEntry::DirGraph:
        writeDirectoryGraph(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
        startMemberDeclarations(ol);
        break;
      case LayoutDocEntry::DirSubDirs:
        writeSubDirList(ol);
        break;
      case LayoutDocEntry::DirFiles:
        writeFileList(ol);
        break;
      case LayoutDocEntry::MemberDeclEnd:
        endMemberDeclarations(ol);
        break;
      case LayoutDocEntry::DetailedDesc:
        {
          const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
          if (ls)
          {
            writeDetailedDescription(ol,ls->title(lang));
          }
        }
        break;
      case LayoutDocEntry::ClassIncludes:
      case LayoutDocEntry::ClassInlineClasses:
      case LayoutDocEntry::ClassInheritanceGraph:
      case LayoutDocEntry::ClassNestedClasses:
      case LayoutDocEntry::ClassCollaborationGraph:
      case LayoutDocEntry::ClassAllMembersLink:
      case LayoutDocEntry::ClassUsedFiles:
      case LayoutDocEntry::NamespaceNestedNamespaces:
      case LayoutDocEntry::NamespaceNestedConstantGroups:
      case LayoutDocEntry::NamespaceClasses:
      case LayoutDocEntry::NamespaceConcepts:
      case LayoutDocEntry::NamespaceInterfaces:
      case LayoutDocEntry::NamespaceStructs:
      case LayoutDocEntry::NamespaceExceptions:
      case LayoutDocEntry::NamespaceInlineClasses:
      case LayoutDocEntry::ConceptDefinition:
      case LayoutDocEntry::FileClasses:
      case LayoutDocEntry::FileConcepts:
      case LayoutDocEntry::FileInterfaces:
      case LayoutDocEntry::FileStructs:
      case LayoutDocEntry::FileExceptions:
      case LayoutDocEntry::FileNamespaces:
      case LayoutDocEntry::FileConstantGroups:
      case LayoutDocEntry::FileIncludes:
      case LayoutDocEntry::FileIncludeGraph:
      case LayoutDocEntry::FileIncludedByGraph:
      case LayoutDocEntry::FileSourceLink:
      case LayoutDocEntry::FileInlineClasses:
      case LayoutDocEntry::GroupClasses:
      case LayoutDocEntry::GroupConcepts:
      case LayoutDocEntry::GroupInlineClasses:
      case LayoutDocEntry::GroupNamespaces:
      case LayoutDocEntry::GroupDirs:
      case LayoutDocEntry::GroupNestedGroups:
      case LayoutDocEntry::GroupFiles:
      case LayoutDocEntry::GroupGraph:
      case LayoutDocEntry::GroupPageDocs:
      case LayoutDocEntry::AuthorSection:
      case LayoutDocEntry::MemberGroups:
      case LayoutDocEntry::MemberDecl:
      case LayoutDocEntry::MemberDef:
      case LayoutDocEntry::MemberDefStart:
      case LayoutDocEntry::MemberDefEnd:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::Directory entry list\n",lde->kind());
        break;
    }
  }
  //---------------------------------------- end flexible part -------------------------------
  ol.endContents();
  endFileWithNavPath(this,ol);
  ol.popGeneratorState();
}
References LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, LayoutDocEntry::ConceptDefinition, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocManager::Directory, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, OutputList::disable(), OutputList::disableAllBut(), OutputList::enableAll(), OutputList::endContents(), endFileWithNavPath(), endMemberDeclarations(), OutputList::endQuickIndices(), endTitle(), err(), LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, LayoutDocEntry::FileStructs, DefinitionMixin< DirDef >::getLanguage(), getOutputFileBase(), LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, HLI_Files, OutputGenerator::Html, LayoutDocManager::instance(), m_dispName, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, DefinitionMixin< DirDef >::name(), LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, LayoutDocEntry::NamespaceStructs, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), shortTitle(), OutputList::startContents(), startFile(), startMemberDeclarations(), startTitle(), theTranslator, LayoutDocEntrySection::title(), Translator::trDirReference(), writeBriefDescription(), writeDetailedDescription(), writeDirectoryGraph(), writeFileList(), DefinitionMixin< DirDef >::writeNavigationPath(), and writeSubDirList().
writeDocumentation() [2/2]
virtual void DirDefImpl::writeDocumentation (OutputList & ol) [virtual]
Implements DirDef.
writeFileList() [1/2]
void DirDefImpl::writeFileList (OutputList & ol) [private]
Definition at line 374 of file dirdef.cpp.
{
  int numFiles = 0;
  for (const auto &fd : m_fileList)
  {
    bool genSourceFile;
    if (fileVisibleInIndex(fd,genSourceFile))
    {
      numFiles++;
    }
    else if (genSourceFile)
    {
      numFiles++;
    }
  }
  // write file list
  if (numFiles>0)
  {
    ol.startMemberHeader("files");
    ol.parseText(theTranslator->trFile(TRUE,FALSE));
    ol.endMemberHeader();
    ol.startMemberList();
    for (const auto &fd : m_fileList)
    {
      bool doc,src;
      doc = fileVisibleInIndex(fd,src);
      if (doc || src)
      {
        ol.startMemberDeclaration();
        ol.startMemberItem(fd->anchor(),0);
        ol.docify(theTranslator->trFile(FALSE,TRUE)+" ");
        ol.insertMemberAlign();
        if (fd->isLinkable())
        {
          ol.writeObjectLink(fd->getReference(),fd->getOutputFileBase(),QCString(),fd->name());
        }
        else
        {
          ol.startBold();
          ol.docify(fd->name());
          ol.endBold();
        }
        if (fd->generateSourceFile())
        {
          ol.pushGeneratorState();
          ol.disableAllBut(OutputGenerator::Html);
          ol.docify(" ");
          ol.startTextLink(fd->includeName(),QCString());
          ol.docify("[");
          ol.parseText(theTranslator->trCode());
          ol.docify("]");
          ol.endTextLink();
          ol.popGeneratorState();
        }
        ol.endMemberItem();
        if (!fd->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
        {
          ol.startMemberDescription(fd->getOutputFileBase());
          ol.generateDoc(briefFile(),briefLine(),fd,0,fd->briefDescription(),
              FALSE, // indexWords
              FALSE, // isExample
              QCString(), // exampleName
              TRUE, // single line
              TRUE, // link from index
              Config_getBool(MARKDOWN_SUPPORT)
              );
          ol.endMemberDescription();
        }
        ol.endMemberDeclaration(fd->anchor(),QCString());
      }
    }
    ol.endMemberList();
  }
}
References DefinitionMixin< DirDef >::briefFile(), DefinitionMixin< DirDef >::briefLine(), Config_getBool, OutputList::disableAllBut(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), OutputList::endTextLink(), FALSE, fileVisibleInIndex(), OutputList::generateDoc(), OutputGenerator::Html, OutputList::insertMemberAlign(), m_fileList, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), src, OutputList::startBold(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), OutputList::startTextLink(), theTranslator, Translator::trCode(), Translator::trFile(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeFileList() [2/2]
void DirDefImpl::writeFileList (OutputList & ol) [private]
writeSubDirList() [1/2]
void DirDefImpl::writeSubDirList (OutputList & ol) [private]
Definition at line 325 of file dirdef.cpp.
{
  int numSubdirs = 0;
  for(const auto dd : m_subdirs)
  {
    if (dd->hasDocumentation() || !dd->getFiles().empty())
    {
      numSubdirs++;
    }
  }
  // write subdir list
  if (numSubdirs>0)
  {
    ol.startMemberHeader("subdirs");
    ol.parseText(theTranslator->trDir(TRUE,FALSE));
    ol.endMemberHeader();
    ol.startMemberList();
    for(const auto dd : m_subdirs)
    {
      if (dd->hasDocumentation() || !dd->getFiles().empty())
      {
        ol.startMemberDeclaration();
        ol.startMemberItem(dd->anchor(),0);
        ol.parseText(theTranslator->trDir(FALSE,TRUE)+" ");
        ol.insertMemberAlign();
        ol.writeObjectLink(dd->getReference(),dd->getOutputFileBase(),QCString(),dd->shortName());
        ol.endMemberItem();
        if (!dd->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
        {
          ol.startMemberDescription(dd->getOutputFileBase());
          ol.generateDoc(briefFile(),briefLine(),dd,0,dd->briefDescription(),
              FALSE, // indexWords
              FALSE, // isExample
              QCString(), // exampleName
              TRUE, // single line
              TRUE, // link from index
              Config_getBool(MARKDOWN_SUPPORT)
              );
          ol.endMemberDescription();
        }
        ol.endMemberDeclaration(dd->anchor(),QCString());
      }
    }
    ol.endMemberList();
  }
}
References DefinitionMixin< DirDef >::briefFile(), DefinitionMixin< DirDef >::briefLine(), Config_getBool, OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), FALSE, OutputList::generateDoc(), OutputList::insertMemberAlign(), m_subdirs, OutputList::parseText(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trDir(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeSubDirList() [2/2]
void DirDefImpl::writeSubDirList (OutputList & ol) [private]
writeTagFile() [1/2]
void DirDefImpl::writeTagFile (TextStream & t) [virtual]
Implements DirDef.
Definition at line 471 of file dirdef.cpp.
{
  tagFile << " <compound kind=\"dir\">\n";
  tagFile << " <name>" << convertToXML(displayName()) << "</name>\n";
  tagFile << " <path>" << convertToXML(stripFromPath(name())) << "</path>\n";
  tagFile << " <filename>" << addHtmlExtensionIfMissing(getOutputFileBase()) << "</filename>\n";
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Directory))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::DirSubDirs:
        {
          if (m_subdirs.size()>0)
          {
            for(const auto dd : m_subdirs)
            {
              tagFile << " <dir>" << convertToXML(dd->displayName()) << "</dir>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::DirFiles:
        {
          for (const auto &fd : m_fileList)
          {
              tagFile << " <file>" << convertToXML(fd->name()) << "</file>\n";
          }
        }
        break;
      default:
        break;
    }
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << " </compound>\n";
}
References addHtmlExtensionIfMissing(), convertToXML(), LayoutDocManager::Directory, LayoutDocEntry::DirFiles, LayoutDocEntry::DirSubDirs, displayName(), getOutputFileBase(), LayoutDocManager::instance(), m_fileList, m_subdirs, DefinitionMixin< DirDef >::name(), stripFromPath(), and DefinitionMixin< DirDef >::writeDocAnchorsToTagFile().
writeTagFile() [2/2]
virtual void DirDefImpl::writeTagFile (TextStream & t) [virtual]
Implements DirDef.
Member Data Documentation
m_dirCount
int DirDefImpl::m_dirCount = -1 [private]
Definition at line 96 of file dirdef.cpp.
Referenced by dirCount(), and setDirCount().
m_diskName
QCString DirDefImpl::m_diskName [private]
Definition at line 94 of file dirdef.cpp.
Referenced by DirDefImpl(), getOutputFileBase(), and setDiskName().
m_dispName
QCString DirDefImpl::m_dispName [private]
Definition at line 92 of file dirdef.cpp.
Referenced by DirDefImpl(), displayName(), and writeDocumentation().
m_fileList
FileList DirDefImpl::m_fileList [private]
Definition at line 95 of file dirdef.cpp.
Referenced by addFile(), computeDependencies(), getFiles(), sort(), writeFileList(), and writeTagFile().
m_level
int DirDefImpl::m_level [private]
Definition at line 97 of file dirdef.cpp.
Referenced by DirDefImpl(), level(), and setLevel().
m_parent
DirDef * DirDefImpl::m_parent [private]
Definition at line 98 of file dirdef.cpp.
Referenced by depGraphIsTrivial(), DirDefImpl(), parent(), and setParent().
m_shortName
QCString DirDefImpl::m_shortName [private]
Definition at line 93 of file dirdef.cpp.
Referenced by DirDefImpl(), shortName(), and shortTitle().
m_subdirs
DirList DirDefImpl::m_subdirs [private]
Definition at line 91 of file dirdef.cpp.
Referenced by addSubDir(), hasSubdirs(), sort(), subDirs(), writeSubDirList(), and writeTagFile().
m_usedDirs
UsedDirLinkedMap DirDefImpl::m_usedDirs [private]
Definition at line 99 of file dirdef.cpp.
Referenced by addUsesDependency(), computeDependencies(), depGraphIsTrivial(), and usedDirs().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dirdef.cpp
doxygen/src/dirdef.cpp