DotFilePatcher Class Reference
#include <dotfilepatcher.h>
Classes
struct Map
Public Member Functions
DotFilePatcher (const QCString &patchFile)
int addMap (const QCString &mapFile, const QCString &relPath, bool urlOnly, const QCString &context, const QCString &label)
int addFigure (const QCString &baseName, const QCString &figureName, bool heightCheck)
int addSVGConversion (const QCString &relPath, bool urlOnly, const QCString &context, bool zoomable, int graphId)
int addSVGObject (const QCString &baseName, const QCString &figureName, const QCString &relPath)
bool run () const
bool isSVGFile () const
DotFilePatcher (const QCString &patchFile)
int addMap (const QCString &mapFile, const QCString &relPath, bool urlOnly, const QCString &context, const QCString &label)
int addFigure (const QCString &baseName, const QCString &figureName, bool heightCheck)
int addSVGConversion (const QCString &relPath, bool urlOnly, const QCString &context, bool zoomable, int graphId)
int addSVGObject (const QCString &baseName, const QCString &figureName, const QCString &relPath)
bool run () const
bool isSVGFile () const
Static Public Member Functions
static bool convertMapFile (TextStream &t, const QCString &mapName, const QCString &relPath, bool urlOnly=FALSE, const QCString &context=QCString())
static bool writeSVGFigureLink (TextStream &out, const QCString &relPath, const QCString &baseName, const QCString &absImgName)
static bool writeVecGfxFigure (TextStream &out, const QCString &baseName, const QCString &figureName)
static bool convertMapFile (TextStream &t, const QCString &mapName, const QCString &relPath, bool urlOnly=FALSE, const QCString &context=QCString())
static bool writeSVGFigureLink (TextStream &out, const QCString &relPath, const QCString &baseName, const QCString &absImgName)
static bool writeVecGfxFigure (TextStream &out, const QCString &baseName, const QCString &figureName)
Private Attributes
std::vector< Map > m_maps
QCString m_patchFile
Detailed Description
Helper class to insert a set of map file into an output file
Definition at line 26 of file dotfilepatcher.h.
Constructor & Destructor Documentation
DotFilePatcher() [1/2]
DotFilePatcher::DotFilePatcher (const QCString & patchFile)
Definition at line 251 of file dotfilepatcher.cpp.
  : m_patchFile(patchFile)
{
}
DotFilePatcher() [2/2]
DotFilePatcher::DotFilePatcher (const QCString & patchFile)
Member Function Documentation
addFigure() [1/2]
int DotFilePatcher::addFigure (const QCString & baseName, const QCString & figureName, bool heightCheck)
Definition at line 269 of file dotfilepatcher.cpp.
{
  size_t id = m_maps.size();
  m_maps.emplace_back(figureName,"",heightCheck,"",baseName);
  return static_cast<int>(id);
}
References id, and m_maps.
addFigure() [2/2]
int DotFilePatcher::addFigure (const QCString & baseName, const QCString & figureName, bool heightCheck)
addMap() [1/2]
int DotFilePatcher::addMap (const QCString & mapFile, const QCString & relPath, bool urlOnly, const QCString & context, const QCString & label)
Definition at line 261 of file dotfilepatcher.cpp.
{
  size_t id = m_maps.size();
  m_maps.emplace_back(mapFile,relPath,urlOnly,context,label);
  return static_cast<int>(id);
}
References id, and m_maps.
addMap() [2/2]
int DotFilePatcher::addMap (const QCString & mapFile, const QCString & relPath, bool urlOnly, const QCString & context, const QCString & label)
addSVGConversion() [1/2]
int DotFilePatcher::addSVGConversion (const QCString & relPath, bool urlOnly, const QCString & context, bool zoomable, int graphId)
Definition at line 277 of file dotfilepatcher.cpp.
{
  size_t id = m_maps.size();
  m_maps.emplace_back("",relPath,urlOnly,context,"",zoomable,graphId);
  return static_cast<int>(id);
}
References id, and m_maps.
Referenced by writeDotImageMapFromFile().
addSVGConversion() [2/2]
int DotFilePatcher::addSVGConversion (const QCString & relPath, bool urlOnly, const QCString & context, bool zoomable, int graphId)
addSVGObject() [1/2]
int DotFilePatcher::addSVGObject (const QCString & baseName, const QCString & figureName, const QCString & relPath)
Definition at line 286 of file dotfilepatcher.cpp.
{
  size_t id = m_maps.size();
  m_maps.emplace_back(absImgName,relPath,false,"",baseName);
  return static_cast<int>(id);
}
References id, and m_maps.
addSVGObject() [2/2]
int DotFilePatcher::addSVGObject (const QCString & baseName, const QCString & figureName, const QCString & relPath)
convertMapFile() [1/2]
bool DotFilePatcher::convertMapFile (TextStream & t, const QCString & mapName, const QCString & relPath, bool urlOnly = FALSE, const QCString & context = QCString()) [static]
converts the rectangles in a client site image map into a stream
Parameters
t the stream to which the result is written.
mapName the name of the map file.
relPath the relative path to the root of the output directory (used in case CREATE_SUBDIRS is enabled).
urlOnly if FALSE the url field in the map contains an external references followed by a $ and then the URL.
context the context (file, class, or namespace) in which the map file was found
Returns
TRUE if successful.
Definition at line 217 of file dotfilepatcher.cpp.
{
  std::ifstream f(mapName.str(),std::ifstream::in);
  if (!f.is_open())
  {
    err("problems opening map file %s for inclusion in the docs!\n"
      "If you installed Graphviz/dot after a previous failing run, \n"
      "try deleting the output directory and rerun doxygen.\n",qPrint(mapName));
    return FALSE;
  }
  std::string line;
  while (getline(f,line)) // foreach line
  {
    QCString buf = line+'\n';
    if (buf.startsWith("<area"))
    {
      QCString replBuf = replaceRef(buf,relPath,urlOnly,context);
      // strip id="..." from replBuf since the id's are not needed and not unique.
      int indexS = replBuf.find("id=\""), indexE;
      if (indexS>0 && (indexE=replBuf.find('"',indexS+4))!=-1)
      {
        t << replBuf.left(indexS-1) << replBuf.right(replBuf.length() - indexE - 1);
      }
      else
      {
        t << replBuf;
      }
    }
  }
  return TRUE;
}
References err(), f, FALSE, QCString::find(), QCString::left(), QCString::length(), qPrint(), replaceRef(), QCString::right(), QCString::startsWith(), QCString::str(), string, and TRUE.
Referenced by insertMapFile(), run(), and writeDotImageMapFromFile().
convertMapFile() [2/2]
static bool DotFilePatcher::convertMapFile (TextStream & t, const QCString & mapName, const QCString & relPath, bool urlOnly = FALSE, const QCString & context = QCString()) [static]
isSVGFile() [1/2]
bool DotFilePatcher::isSVGFile () const
Definition at line 256 of file dotfilepatcher.cpp.
{
  return m_patchFile.endsWith(".svg");
}
References QCString::endsWith(), and m_patchFile.
Referenced by run().
isSVGFile() [2/2]
bool DotFilePatcher::isSVGFile () const
run() [1/2]
bool DotFilePatcher::run () const
Definition at line 295 of file dotfilepatcher.cpp.
{
  //printf("DotFilePatcher::run(): %s\n",qPrint(m_patchFile));
  bool interactiveSVG_local = Config_getBool(INTERACTIVE_SVG);
  bool isSVGFile = m_patchFile.endsWith(".svg");
  int graphId = -1;
  QCString relPath;
  if (isSVGFile)
  {
    const Map &map = m_maps.front(); // there is only one 'map' for a SVG file
    interactiveSVG_local = interactiveSVG_local && map.zoomable;
    graphId = map.graphId;
    relPath = map.relPath;
    //printf("DotFilePatcher::addSVGConversion: file=%s zoomable=%d\n",
    // qPrint(m_patchFile),map->zoomable);
  }
  std::string tmpName = m_patchFile.str()+".tmp";
  std::string patchFile = m_patchFile.str();
  Dir thisDir;
  if (!thisDir.rename(patchFile,tmpName))
  {
    err("Failed to rename file %s to %s!\n",qPrint(m_patchFile),tmpName.c_str());
    return FALSE;
  }
  std::ifstream fi(tmpName, std::ifstream::in);
  std::ofstream fo(patchFile, std::ofstream::out | std::ofstream::binary);
  if (!fi.is_open())
  {
    err("problem opening file %s for patching!\n",tmpName.c_str());
    thisDir.rename(tmpName,patchFile);
    return FALSE;
  }
  if (!fo.is_open())
  {
    err("problem opening file %s for patching!\n",qPrint(m_patchFile));
    thisDir.rename(tmpName,patchFile);
    return FALSE;
  }
  TextStream t(&fo);
  int width=0,height=0;
  bool insideHeader=FALSE;
  bool replacedHeader=FALSE;
  bool foundSize=FALSE;
  std::string lineStr;
  static const reg::Ex reSVG(R"([\[<]!-- SVG [0-9]+)");
  static const reg::Ex reMAP(R"(<!-- MAP [0-9]+)");
  static const reg::Ex reFIG(R"(% FIG [0-9]+)");
  while (getline(fi,lineStr))
  {
    QCString line = lineStr+'\n';
    //printf("line=[%s]\n",qPrint(line.stripWhiteSpace()));
    int i;
    if (isSVGFile)
    {
      if (interactiveSVG_local)
      {
        if (line.find("<svg")!=-1 && !replacedHeader)
        {
          int count;
          count = sscanf(line.data(),"<svg width=\"%dpt\" height=\"%dpt\"",&width,&height);
          //printf("width=%d height=%d\n",width,height);
          foundSize = count==2 && (width>500 || height>450);
          if (foundSize) insideHeader=TRUE;
        }
        else if (insideHeader && !replacedHeader && line.find("<g id=\"graph")!=-1)
        {
          line="";
          if (foundSize)
          {
            // insert special replacement header for interactive SVGs
            t << "<!--zoomable " << height << " -->\n";
            t << svgZoomHeader;
            t << "var viewWidth = " << width << ";\n";
            t << "var viewHeight = " << height << ";\n";
            if (graphId>=0)
            {
              t << "var sectionId = 'dynsection-" << graphId << "';\n";
            }
            t << "</script>\n";
            t << "<script xlink:href=\"" << relPath << "svgpan.js\"/>\n";
            t << "<svg id=\"graph\" class=\"graph\">\n";
            t << "<g id=\"viewport\">\n";
          }
          insideHeader=FALSE;
          replacedHeader=TRUE;
        }
      }
      if (!insideHeader || !foundSize) // copy SVG and replace refs,
                                       // unless we are inside the header of the SVG.
                                       // Then we replace it with another header.
      {
        const Map &map = m_maps.front(); // there is only one 'map' for a SVG file
        t << replaceRef(line,map.relPath,map.urlOnly,map.context,"_top");
      }
    }
    else if ((i=findIndex(line.str(),reSVG))!=-1)
    {
      //printf("Found marker at %d\n",i);
      int mapId=-1;
      t << line.left(i);
      int n = sscanf(line.data()+i+1,"!-- SVG %d",&mapId);
      if (n==1 && mapId>=0 && mapId<static_cast<int>(m_maps.size()))
      {
        int e = std::max(line.find("--]"),line.find("-->"));
        const Map &map = m_maps.at(mapId);
        //printf("DotFilePatcher::writeSVGFigure: file=%s zoomable=%d\n",
        // qPrint(m_patchFile),map.zoomable);
        if (!writeSVGFigureLink(t,map.relPath,map.label,map.mapFile))
        {
          err("Problem extracting size from SVG file %s\n",qPrint(map.mapFile));
        }
        if (e!=-1) t << line.mid(e+3);
      }
      else // error invalid map id!
      {
        err("Found invalid SVG id in file %s!\n",qPrint(m_patchFile));
        t << line.mid(i);
      }
    }
    else if ((i=findIndex(line.str(),reMAP))!=-1)
    {
      int mapId=-1;
      t << line.left(i);
      int n = sscanf(line.data()+i,"<!-- MAP %d",&mapId);
      if (n==1 && mapId>=0 && mapId<static_cast<int>(m_maps.size()))
      {
        TextStream tt;
        const Map &map = m_maps.at(mapId);
        //printf("patching MAP %d in file %s with contents of %s\n",
        // mapId,qPrint(m_patchFile),qPrint(map.mapFile));
        convertMapFile(tt,map.mapFile,map.relPath,map.urlOnly,map.context);
        if (!tt.empty())
        {
          t << "<map name=\"" << correctId(map.label) << "\" id=\"" << correctId(map.label) << "\">\n";
          t << tt.str();
          t << "</map>\n";
        }
      }
      else // error invalid map id!
      {
        err("Found invalid MAP id in file %s!\n",qPrint(m_patchFile));
        t << line.mid(i);
      }
    }
    else if ((i=findIndex(line.str(),reFIG))!=-1)
    {
      int mapId=-1;
      int n = sscanf(line.data()+i+2,"FIG %d",&mapId);
      //printf("line='%s' n=%d\n",qPrint(line)+i,n);
      if (n==1 && mapId>=0 && mapId<static_cast<int>(m_maps.size()))
      {
        const Map &map = m_maps.at(mapId);
        //printf("patching FIG %d in file %s with contents of %s\n",
        // mapId,qPrint(m_patchFile),qPrint(map.mapFile));
        if (!writeVecGfxFigure(t,map.label,map.mapFile))
        {
          err("problem writing FIG %d figure!\n",mapId);
          return FALSE;
        }
      }
      else // error invalid map id!
      {
        err("Found invalid bounding FIG %d in file %s!\n",mapId,qPrint(m_patchFile));
        t << line;
      }
    }
    else
    {
      t << line;
    }
  }
  fi.close();
  if (isSVGFile && interactiveSVG_local && replacedHeader)
  {
    QCString orgName=m_patchFile.left(m_patchFile.length()-4)+"_org.svg";
    t << substitute(svgZoomFooter,"$orgname",stripPath(orgName));
    t.flush();
    fo.close();
    // keep original SVG file so we can refer to it, we do need to replace
    // dummy link by real ones
    fi.open(tmpName,std::ifstream::in);
    fo.open(orgName.str(),std::ofstream::out | std::ofstream::binary);
    if (!fi.is_open())
    {
      err("problem opening file %s for reading!\n",tmpName.c_str());
      return FALSE;
    }
    if (!fo.is_open())
    {
      err("problem opening file %s for writing!\n",qPrint(orgName));
      return FALSE;
    }
    t.setStream(&fo);
    while (getline(fi,lineStr)) // foreach line
    {
      std::string line = lineStr+'\n';
      const Map &map = m_maps.front(); // there is only one 'map' for a SVG file
      t << replaceRef(line.c_str(),map.relPath,map.urlOnly,map.context,"_top");
    }
    t.flush();
    fi.close();
    fo.close();
  }
  // remove temporary file
  thisDir.remove(tmpName);
  return TRUE;
}
References Config_getBool, DotFilePatcher::Map::context, convertMapFile(), correctId(), QCString::data(), e, TextStream::empty(), QCString::endsWith(), err(), FALSE, QCString::find(), findIndex(), TextStream::flush(), DotFilePatcher::Map::graphId, isSVGFile(), DotFilePatcher::Map::label, QCString::left(), QCString::length(), m_maps, m_patchFile, DotFilePatcher::Map::mapFile, QCString::mid(), n, out, qPrint(), DotFilePatcher::Map::relPath, Dir::remove(), Dir::rename(), replaceRef(), TextStream::setStream(), QCString::str(), TextStream::str(), string, stripPath(), substitute(), svgZoomFooter, svgZoomHeader, TRUE, DotFilePatcher::Map::urlOnly, writeSVGFigureLink(), writeVecGfxFigure(), and DotFilePatcher::Map::zoomable.
Referenced by writeDotImageMapFromFile().
run() [2/2]
bool DotFilePatcher::run () const
writeSVGFigureLink() [1/2]
bool DotFilePatcher::writeSVGFigureLink (TextStream & out, const QCString & relPath, const QCString & baseName, const QCString & absImgName) [static]
Check if a reference to a SVG figure can be written and do so if possible. Returns FALSE if not possible (for instance because the SVG file is not yet generated).
Definition at line 541 of file dotfilepatcher.cpp.
{
  int width=600,height=600;
  if (!readSVGSize(absImgName,&width,&height))
  {
    return FALSE;
  }
  if (width==-1)
  {
    if (height<=60) height=300; else height+=300; // add some extra space for zooming
    if (height>600) height=600; // clip to maximum height of 600 pixels
    out << "<div class=\"zoom\">";
    //out << "<object type=\"image/svg+xml\" data=\""
    //out << "<embed type=\"image/svg+xml\" src=\""
    out << "<iframe scrolling=\"no\" frameborder=\"0\" src=\""
        << relPath << baseName << ".svg\" width=\"100%\" height=\"" << height << "\">";
  }
  else
  {
    //out << "<object type=\"image/svg+xml\" data=\""
    //out << "<embed type=\"image/svg+xml\" src=\""
    out << "<iframe scrolling=\"no\" frameborder=\"0\" src=\""
        << relPath << baseName << ".svg\" width=\""
        << ((width*96+48)/72) << "\" height=\""
        << ((height*96+48)/72) << "\">";
  }
  writeSVGNotSupported(out);
  //out << "</object>";
  //out << "</embed>";
  out << "</iframe>";
  if (width==-1)
  {
    out << "</div>";
  }
  return TRUE;
}
References FALSE, out, readSVGSize(), TRUE, and writeSVGNotSupported().
Referenced by DotGraph::generateCode(), run(), and writeDotImageMapFromFile().
writeSVGFigureLink() [2/2]
static bool DotFilePatcher::writeSVGFigureLink (TextStream & out, const QCString & relPath, const QCString & baseName, const QCString & absImgName) [static]
writeVecGfxFigure() [1/2]
bool DotFilePatcher::writeVecGfxFigure (TextStream & out, const QCString & baseName, const QCString & figureName) [static]
Definition at line 580 of file dotfilepatcher.cpp.
{
  int width=400,height=550;
  if (Config_getBool(USE_PDFLATEX))
  {
    if (!DotRunner::readBoundingBox(figureName+".pdf",&width,&height,FALSE))
    {
      //printf("writeVecGfxFigure()=0\n");
      return FALSE;
    }
  }
  else
  {
    if (!DotRunner::readBoundingBox(figureName+".eps",&width,&height,TRUE))
    {
      //printf("writeVecGfxFigure()=0\n");
      return FALSE;
    }
  }
  //printf("Got PDF/EPS size %d,%d\n",width,height);
  int maxWidth = 350; /* approx. page width in points, excl. margins */
  int maxHeight = 550; /* approx. page height in points, excl. margins */
  out << "\\nopagebreak\n"
         "\\begin{figure}[H]\n"
         "\\begin{center}\n"
         "\\leavevmode\n";
  if (width>maxWidth || height>maxHeight) // figure too big for page
  {
    // c*width/maxWidth > c*height/maxHeight, where c=maxWidth*maxHeight>0
    if (width*maxHeight>height*maxWidth)
    {
      out << "\\includegraphics[width=" << maxWidth << "pt]";
    }
    else
    {
      out << "\\includegraphics[height=" << maxHeight << "pt]";
    }
  }
  else
  {
    out << "\\includegraphics[width=" << width << "pt]";
  }
  out << "{" << baseName << "}\n"
         "\\end{center}\n"
         "\\end{figure}\n";
  //printf("writeVecGfxFigure()=1\n");
  return TRUE;
}
References Config_getBool, FALSE, out, DotRunner::readBoundingBox(), and TRUE.
Referenced by DotGraph::generateCode(), and run().
writeVecGfxFigure() [2/2]
static bool DotFilePatcher::writeVecGfxFigure (TextStream & out, const QCString & baseName, const QCString & figureName) [static]
Member Data Documentation
m_maps
std::vector< Map > DotFilePatcher::m_maps [private]
Definition at line 69 of file dotfilepatcher.h.
Referenced by addFigure(), addMap(), addSVGConversion(), addSVGObject(), and run().
m_patchFile
QCString DotFilePatcher::m_patchFile [private]
Definition at line 70 of file dotfilepatcher.h.
Referenced by isSVGFile(), and run().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dotfilepatcher.h
doxygen/src/dotfilepatcher.h
doxygen/build/doxygen/src/dotfilepatcher.cpp
doxygen/src/dotfilepatcher.cpp