ClassDefMutable Class Reference
#include <classdef.h>
Public Member Functions
virtual void setIncludeFile (FileDef *fd, const QCString &incName, bool local, bool force)=0
virtual void setFileDef (FileDef *fd)=0
virtual void setSubGrouping (bool enabled)=0
virtual void setProtection (Protection p)=0
virtual void setGroupDefForAllMembers (GroupDef *g, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs)=0
virtual void setIsStatic (bool b)=0
virtual void setCompoundType (CompoundType t)=0
virtual void setClassName (const QCString &name)=0
virtual void setClassSpecifier (uint64 spec)=0
virtual void setTemplateArguments (const ArgumentList &al)=0
virtual void setTemplateBaseClassNames (const TemplateNameMap &templateNames)=0
virtual void setTemplateMaster (const ClassDef *tm)=0
virtual void setTypeConstraints (const ArgumentList &al)=0
virtual void setCategoryOf (ClassDef *cd)=0
virtual void setUsedOnly (bool b)=0
virtual void setTagLessReference (const ClassDef *cd)=0
virtual void setName (const QCString &name)=0
virtual void setMetaData (const QCString &md)=0
virtual void setRequiresClause (const QCString &req)=0
virtual void insertBaseClass (ClassDef *, const QCString &name, Protection p, Specifier s, const QCString &t=QCString())=0
virtual void insertSubClass (ClassDef *, Protection p, Specifier s, const QCString &t=QCString())=0
virtual void insertMember (MemberDef *)=0
virtual void insertUsedFile (const FileDef *)=0
virtual void addMembersToTemplateInstance (const ClassDef *cd, const ArgumentList &templateArguments, const QCString &templSpec)=0
virtual void addInnerCompound (const Definition *d)=0
virtual bool addExample (const QCString &anchor, const QCString &name, const QCString &file)=0
virtual void addUsedClass (ClassDef *cd, const QCString &accessName, Protection prot)=0
virtual void addUsedByClass (ClassDef *cd, const QCString &accessName, Protection prot)=0
virtual void makeTemplateArgument (bool b=TRUE)=0
virtual void mergeCategory (ClassDef *category)=0
virtual void findSectionsInDocumentation ()=0
virtual void addMembersToMemberGroup ()=0
virtual void addListReferences ()=0
virtual void addTypeConstraints ()=0
virtual void computeAnchors ()=0
virtual void mergeMembers ()=0
virtual void sortMemberLists ()=0
virtual void distributeMemberGroupDocumentation ()=0
virtual void reclassifyMember (MemberDefMutable *md, MemberType t)=0
virtual void removeMemberFromLists (MemberDef *md)=0
virtual void setAnonymousEnumType ()=0
virtual void countMembers ()=0
virtual void sortAllMembersList ()=0
virtual void writeDocumentation (OutputList &ol) const =0
virtual void writeDocumentationForInnerClasses (OutputList &ol) const =0
virtual void writeMemberPages (OutputList &ol) const =0
virtual void writeMemberList (OutputList &ol) const =0
virtual void writeDeclaration (OutputList &ol, const MemberDef *md, bool inGroup, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const =0
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const =0
virtual void writeSummaryLinks (OutputList &ol) const =0
virtual void writeInlineDocumentation (OutputList &ol) const =0
virtual void writeTagFile (TextStream &)=0
virtual void writeMemberDeclarations (OutputList &ol, ClassDefSet &visitedClasses, MemberListType lt, const QCString &title, const QCString &subTitle=QCString(), bool showInline=FALSE, const ClassDef *inheritedFrom=0, int lt2=-1, bool invert=FALSE, bool showAlways=FALSE) const =0
virtual void addGroupedInheritedMembers (OutputList &ol, MemberListType lt, const ClassDef *inheritedFrom, const QCString &inheritId) const =0
virtual void setIncludeFile (FileDef *fd, const QCString &incName, bool local, bool force)=0
virtual void setFileDef (FileDef *fd)=0
virtual void setSubGrouping (bool enabled)=0
virtual void setProtection (Protection p)=0
virtual void setGroupDefForAllMembers (GroupDef *g, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs)=0
virtual void setIsStatic (bool b)=0
virtual void setCompoundType (CompoundType t)=0
virtual void setClassName (const QCString &name)=0
virtual void setClassSpecifier (uint64 spec)=0
virtual void setTemplateArguments (const ArgumentList &al)=0
virtual void setTemplateBaseClassNames (const TemplateNameMap &templateNames)=0
virtual void setTemplateMaster (const ClassDef *tm)=0
virtual void setTypeConstraints (const ArgumentList &al)=0
virtual void setCategoryOf (ClassDef *cd)=0
virtual void setUsedOnly (bool b)=0
virtual void setTagLessReference (const ClassDef *cd)=0
virtual void setName (const QCString &name)=0
virtual void setMetaData (const QCString &md)=0
virtual void setRequiresClause (const QCString &req)=0
virtual void insertBaseClass (ClassDef *, const QCString &name, Protection p, Specifier s, const QCString &t=QCString())=0
virtual void insertSubClass (ClassDef *, Protection p, Specifier s, const QCString &t=QCString())=0
virtual void insertMember (MemberDef *)=0
virtual void insertUsedFile (const FileDef *)=0
virtual void addMembersToTemplateInstance (const ClassDef *cd, const ArgumentList &templateArguments, const QCString &templSpec)=0
virtual void addInnerCompound (const Definition *d)=0
virtual bool addExample (const QCString &anchor, const QCString &name, const QCString &file)=0
virtual void addUsedClass (ClassDef *cd, const QCString &accessName, Protection prot)=0
virtual void addUsedByClass (ClassDef *cd, const QCString &accessName, Protection prot)=0
virtual void makeTemplateArgument (bool b=TRUE)=0
virtual void mergeCategory (ClassDef *category)=0
virtual void findSectionsInDocumentation ()=0
virtual void addMembersToMemberGroup ()=0
virtual void addListReferences ()=0
virtual void addTypeConstraints ()=0
virtual void computeAnchors ()=0
virtual void mergeMembers ()=0
virtual void sortMemberLists ()=0
virtual void distributeMemberGroupDocumentation ()=0
virtual void reclassifyMember (MemberDefMutable *md, MemberType t)=0
virtual void removeMemberFromLists (MemberDef *md)=0
virtual void setAnonymousEnumType ()=0
virtual void countMembers ()=0
virtual void sortAllMembersList ()=0
virtual void writeDocumentation (OutputList &ol) const =0
virtual void writeDocumentationForInnerClasses (OutputList &ol) const =0
virtual void writeMemberPages (OutputList &ol) const =0
virtual void writeMemberList (OutputList &ol) const =0
virtual void writeDeclaration (OutputList &ol, const MemberDef *md, bool inGroup, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const =0
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const =0
virtual void writeSummaryLinks (OutputList &ol) const =0
virtual void writeInlineDocumentation (OutputList &ol) const =0
virtual void writeTagFile (TextStream &)=0
virtual void writeMemberDeclarations (OutputList &ol, ClassDefSet &visitedClasses, MemberListType lt, const QCString &title, const QCString &subTitle=QCString(), bool showInline=FALSE, const ClassDef *inheritedFrom=0, int lt2=-1, bool invert=FALSE, bool showAlways=FALSE) const =0
virtual void addGroupedInheritedMembers (OutputList &ol, MemberListType lt, const ClassDef *inheritedFrom, const QCString &inheritId) const =0
Additional Inherited Members
Detailed Description
Definition at line 380 of file classdef.h.
Member Function Documentation
addExample() [1/2]
virtual bool ClassDefMutable::addExample (const QCString & anchor, const QCString & name, const QCString & file) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by generateClassOrGlobalLink().
addExample() [2/2]
virtual bool ClassDefMutable::addExample (const QCString & anchor, const QCString & name, const QCString & file) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
addGroupedInheritedMembers() [1/2]
virtual void ClassDefMutable::addGroupedInheritedMembers (OutputList & ol, MemberListType lt, const ClassDef * inheritedFrom, const QCString & inheritId) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by MemberList::writeDeclarations().
addGroupedInheritedMembers() [2/2]
virtual void ClassDefMutable::addGroupedInheritedMembers (OutputList & ol, MemberListType lt, const ClassDef * inheritedFrom, const QCString & inheritId) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
addInnerCompound() [1/2]
virtual void ClassDefMutable::addInnerCompound (const Definition * d) [pure virtual]
Implements DefinitionMutable.
Implemented in ClassDefImpl, ClassDefImpl, DefinitionMixin< ClassDefMutable >, and DefinitionMixin< ClassDefMutable >.
Referenced by ClassDefImpl::insertTemplateInstance().
addInnerCompound() [2/2]
virtual void ClassDefMutable::addInnerCompound (const Definition * d) [pure virtual]
Implements DefinitionMutable.
Implemented in ClassDefImpl, ClassDefImpl, DefinitionMixin< ClassDefMutable >, and DefinitionMixin< ClassDefMutable >.
addListReferences() [1/2]
virtual void ClassDefMutable::addListReferences () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addListReferences().
addListReferences() [2/2]
virtual void ClassDefMutable::addListReferences () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
addMembersToMemberGroup() [1/2]
virtual void ClassDefMutable::addMembersToMemberGroup () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addMembersToMemberGroup().
addMembersToMemberGroup() [2/2]
virtual void ClassDefMutable::addMembersToMemberGroup () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
addMembersToTemplateInstance() [1/2]
virtual void ClassDefMutable::addMembersToTemplateInstance (const ClassDef * cd, const ArgumentList & templateArguments, const QCString & templSpec) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by ClassDefImpl::addMembersToTemplateInstance(), and createTemplateInstanceMembers().
addMembersToTemplateInstance() [2/2]
virtual void ClassDefMutable::addMembersToTemplateInstance (const ClassDef * cd, const ArgumentList & templateArguments, const QCString & templSpec) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
addTypeConstraints() [1/2]
virtual void ClassDefMutable::addTypeConstraints () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by findUsedTemplateInstances().
addTypeConstraints() [2/2]
virtual void ClassDefMutable::addTypeConstraints () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
addUsedByClass() [1/2]
virtual void ClassDefMutable::addUsedByClass (ClassDef * cd, const QCString & accessName, Protection prot) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by findUsedClassesForClass().
addUsedByClass() [2/2]
virtual void ClassDefMutable::addUsedByClass (ClassDef * cd, const QCString & accessName, Protection prot) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
addUsedClass() [1/2]
virtual void ClassDefMutable::addUsedClass (ClassDef * cd, const QCString & accessName, Protection prot) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by findUsedClassesForClass().
addUsedClass() [2/2]
virtual void ClassDefMutable::addUsedClass (ClassDef * cd, const QCString & accessName, Protection prot) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
computeAnchors() [1/2]
virtual void ClassDefMutable::computeAnchors () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by computeMemberReferences().
computeAnchors() [2/2]
virtual void ClassDefMutable::computeAnchors () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
countMembers() [1/2]
virtual void ClassDefMutable::countMembers () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by countMembers().
countMembers() [2/2]
virtual void ClassDefMutable::countMembers () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
distributeMemberGroupDocumentation() [1/2]
virtual void ClassDefMutable::distributeMemberGroupDocumentation () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by distributeMemberGroupDocumentation().
distributeMemberGroupDocumentation() [2/2]
virtual void ClassDefMutable::distributeMemberGroupDocumentation () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
findSectionsInDocumentation() [1/2]
virtual void ClassDefMutable::findSectionsInDocumentation () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by findSectionsInDocumentation().
findSectionsInDocumentation() [2/2]
virtual void ClassDefMutable::findSectionsInDocumentation () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
insertBaseClass() [1/2]
virtual void ClassDefMutable::insertBaseClass (ClassDef * , const QCString & name, Protection p, Specifier s, const QCString & t = QCString()) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addInstance(), and findClassRelation().
insertBaseClass() [2/2]
virtual void ClassDefMutable::insertBaseClass (ClassDef * , const QCString & name, Protection p, Specifier s, const QCString & t = QCString()) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
insertMember() [1/2]
virtual void ClassDefMutable::insertMember (MemberDef *) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addEnumValuesToEnums(), addInstance(), addLocalObjCMethod(), addMemberSpecialization(), addOverloaded(), addVariableToClass(), createTagLessInstance(), findEnums(), findMember(), and findUsingDeclImports().
insertMember() [2/2]
virtual void ClassDefMutable::insertMember (MemberDef *) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
insertSubClass() [1/2]
virtual void ClassDefMutable::insertSubClass (ClassDef * , Protection p, Specifier s, const QCString & t = QCString()) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addInstance(), and findClassRelation().
insertSubClass() [2/2]
virtual void ClassDefMutable::insertSubClass (ClassDef * , Protection p, Specifier s, const QCString & t = QCString()) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
insertUsedFile() [1/2]
virtual void ClassDefMutable::insertUsedFile (const FileDef *) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addClassToContext(), addLocalObjCMethod(), addMemberDocs(), addOverloaded(), addVariableToClass(), findClassRelation(), findEnums(), findMember(), and ClassDefImpl::insertUsedFile().
insertUsedFile() [2/2]
virtual void ClassDefMutable::insertUsedFile (const FileDef *) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
makeTemplateArgument() [1/2]
virtual void ClassDefMutable::makeTemplateArgument (bool b = TRUE) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by findUsedClassesForClass().
makeTemplateArgument() [2/2]
virtual void ClassDefMutable::makeTemplateArgument (bool b = TRUE) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
mergeCategory() [1/2]
virtual void ClassDefMutable::mergeCategory (ClassDef * category) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by mergeCategories().
mergeCategory() [2/2]
virtual void ClassDefMutable::mergeCategory (ClassDef * category) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
mergeMembers() [1/2]
virtual void ClassDefMutable::mergeMembers () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by buildCompleteMemberLists(), and ClassDefImpl::mergeMembers().
mergeMembers() [2/2]
virtual void ClassDefMutable::mergeMembers () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
reclassifyMember() [1/2]
virtual void ClassDefMutable::reclassifyMember (MemberDefMutable * md, MemberType t) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addVariableToClass().
reclassifyMember() [2/2]
virtual void ClassDefMutable::reclassifyMember (MemberDefMutable * md, MemberType t) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
removeMemberFromLists() [1/2]
virtual void ClassDefMutable::removeMemberFromLists (MemberDef * md) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
removeMemberFromLists() [2/2]
virtual void ClassDefMutable::removeMemberFromLists (MemberDef * md) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setAnonymousEnumType() [1/2]
virtual void ClassDefMutable::setAnonymousEnumType () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by setAnonymousEnumType().
setAnonymousEnumType() [2/2]
virtual void ClassDefMutable::setAnonymousEnumType () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setCategoryOf() [1/2]
virtual void ClassDefMutable::setCategoryOf (ClassDef * cd) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by ClassDefImpl::mergeCategory().
setCategoryOf() [2/2]
virtual void ClassDefMutable::setCategoryOf (ClassDef * cd) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setClassName() [1/2]
virtual void ClassDefMutable::setClassName (const QCString & name) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addVariableToFile(), and writeClassTree().
setClassName() [2/2]
virtual void ClassDefMutable::setClassName (const QCString & name) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setClassSpecifier() [1/2]
virtual void ClassDefMutable::setClassSpecifier (uint64 spec) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addClassToContext().
setClassSpecifier() [2/2]
virtual void ClassDefMutable::setClassSpecifier (uint64 spec) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setCompoundType() [1/2]
virtual void ClassDefMutable::setCompoundType (CompoundType t) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addClassToContext(), and findClassRelation().
setCompoundType() [2/2]
virtual void ClassDefMutable::setCompoundType (CompoundType t) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setFileDef() [1/2]
virtual void ClassDefMutable::setFileDef (FileDef * fd) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addClassToContext(), and createTagLessInstance().
setFileDef() [2/2]
virtual void ClassDefMutable::setFileDef (FileDef * fd) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setGroupDefForAllMembers() [1/2]
virtual void ClassDefMutable::setGroupDefForAllMembers (GroupDef * g, Grouping::GroupPri_t pri, const QCString & fileName, int startLine, bool hasDocs) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addMemberToGroups(), and ClassDefImpl::setGroupDefForAllMembers().
setGroupDefForAllMembers() [2/2]
virtual void ClassDefMutable::setGroupDefForAllMembers (GroupDef * g, Grouping::GroupPri_t pri, const QCString & fileName, int startLine, bool hasDocs) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setIncludeFile() [1/2]
virtual void ClassDefMutable::setIncludeFile (FileDef * fd, const QCString & incName, bool local, bool force) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setIncludeFile() [2/2]
virtual void ClassDefMutable::setIncludeFile (FileDef * fd, const QCString & incName, bool local, bool force) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setIsStatic() [1/2]
virtual void ClassDefMutable::setIsStatic (bool b) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addClassToContext().
setIsStatic() [2/2]
virtual void ClassDefMutable::setIsStatic (bool b) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setMetaData() [1/2]
virtual void ClassDefMutable::setMetaData (const QCString & md) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addClassToContext().
setMetaData() [2/2]
virtual void ClassDefMutable::setMetaData (const QCString & md) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setName() [1/2]
virtual void ClassDefMutable::setName (const QCString & name) [pure virtual]
Sets a new name for the definition
Implements DefinitionMutable.
Implemented in ClassDefImpl, DefinitionMixin< ClassDefMutable >, ClassDefImpl, and DefinitionMixin< ClassDefMutable >.
setName() [2/2]
virtual void ClassDefMutable::setName (const QCString & name) [pure virtual]
Sets a new name for the definition
Implements DefinitionMutable.
Implemented in ClassDefImpl, DefinitionMixin< ClassDefMutable >, ClassDefImpl, and DefinitionMixin< ClassDefMutable >.
setProtection() [1/2]
virtual void ClassDefMutable::setProtection (Protection p) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addClassToContext().
setProtection() [2/2]
virtual void ClassDefMutable::setProtection (Protection p) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setRequiresClause() [1/2]
virtual void ClassDefMutable::setRequiresClause (const QCString & req) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addClassToContext().
setRequiresClause() [2/2]
virtual void ClassDefMutable::setRequiresClause (const QCString & req) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setSubGrouping() [1/2]
virtual void ClassDefMutable::setSubGrouping (bool enabled) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addClassToContext().
setSubGrouping() [2/2]
virtual void ClassDefMutable::setSubGrouping (bool enabled) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setTagLessReference() [1/2]
virtual void ClassDefMutable::setTagLessReference (const ClassDef * cd) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by processTagLessClasses().
setTagLessReference() [2/2]
virtual void ClassDefMutable::setTagLessReference (const ClassDef * cd) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setTemplateArguments() [1/2]
virtual void ClassDefMutable::setTemplateArguments (const ArgumentList & al) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addClassToContext().
setTemplateArguments() [2/2]
virtual void ClassDefMutable::setTemplateArguments (const ArgumentList & al) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setTemplateBaseClassNames() [1/2]
virtual void ClassDefMutable::setTemplateBaseClassNames (const TemplateNameMap & templateNames) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by findTemplateInstanceRelation().
setTemplateBaseClassNames() [2/2]
virtual void ClassDefMutable::setTemplateBaseClassNames (const TemplateNameMap & templateNames) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setTemplateMaster() [1/2]
virtual void ClassDefMutable::setTemplateMaster (const ClassDef * tm) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by ClassDefImpl::insertTemplateInstance().
setTemplateMaster() [2/2]
virtual void ClassDefMutable::setTemplateMaster (const ClassDef * tm) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setTypeConstraints() [1/2]
virtual void ClassDefMutable::setTypeConstraints (const ArgumentList & al) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by addClassToContext().
setTypeConstraints() [2/2]
virtual void ClassDefMutable::setTypeConstraints (const ArgumentList & al) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
setUsedOnly() [1/2]
virtual void ClassDefMutable::setUsedOnly (bool b) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by ClassDefImpl::addTypeConstraint(), and findUsedClassesForClass().
setUsedOnly() [2/2]
virtual void ClassDefMutable::setUsedOnly (bool b) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
sortAllMembersList() [1/2]
virtual void ClassDefMutable::sortAllMembersList () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by buildCompleteMemberLists().
sortAllMembersList() [2/2]
virtual void ClassDefMutable::sortAllMembersList () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
sortMemberLists() [1/2]
virtual void ClassDefMutable::sortMemberLists () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by sortMemberLists().
sortMemberLists() [2/2]
virtual void ClassDefMutable::sortMemberLists () [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
writeDeclaration() [1/2]
virtual void ClassDefMutable::writeDeclaration (OutputList & ol, const MemberDef * md, bool inGroup, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by MemberDefImpl::writeDeclaration().
writeDeclaration() [2/2]
virtual void ClassDefMutable::writeDeclaration (OutputList & ol, const MemberDef * md, bool inGroup, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
writeDocumentation() [1/2]
virtual void ClassDefMutable::writeDocumentation (OutputList & ol) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by generateDocsForClassList(), generateNamespaceClassDocs(), and ClassDefImpl::writeDocumentationForInnerClasses().
writeDocumentation() [2/2]
virtual void ClassDefMutable::writeDocumentation (OutputList & ol) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
writeDocumentationForInnerClasses() [1/2]
virtual void ClassDefMutable::writeDocumentationForInnerClasses (OutputList & ol) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by generateDocsForClassList(), generateNamespaceClassDocs(), and ClassDefImpl::writeDocumentationForInnerClasses().
writeDocumentationForInnerClasses() [2/2]
virtual void ClassDefMutable::writeDocumentationForInnerClasses (OutputList & ol) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
writeInlineDocumentation() [1/2]
virtual void ClassDefMutable::writeInlineDocumentation (OutputList & ol) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by ClassLinkedRefMap::writeDocumentation().
writeInlineDocumentation() [2/2]
virtual void ClassDefMutable::writeInlineDocumentation (OutputList & ol) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
writeMemberDeclarations() [1/2]
virtual void ClassDefMutable::writeMemberDeclarations (OutputList & ol, ClassDefSet & visitedClasses, MemberListType lt, const QCString & title, const QCString & subTitle = QCString(), bool showInline = FALSE, const ClassDef * inheritedFrom = 0, int lt2 = -1, bool invert = FALSE, bool showAlways = FALSE) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by ClassDefImpl::writeInheritedMemberDeclarations().
writeMemberDeclarations() [2/2]
virtual void ClassDefMutable::writeMemberDeclarations (OutputList & ol, ClassDefSet & visitedClasses, MemberListType lt, const QCString & title, const QCString & subTitle = QCString(), bool showInline = FALSE, const ClassDef * inheritedFrom = 0, int lt2 = -1, bool invert = FALSE, bool showAlways = FALSE) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
writeMemberList() [1/2]
virtual void ClassDefMutable::writeMemberList (OutputList & ol) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by generateDocsForClassList(), generateNamespaceClassDocs(), and ClassDefImpl::writeDocumentationForInnerClasses().
writeMemberList() [2/2]
virtual void ClassDefMutable::writeMemberList (OutputList & ol) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
writeMemberPages() [1/2]
virtual void ClassDefMutable::writeMemberPages (OutputList & ol) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
writeMemberPages() [2/2]
virtual void ClassDefMutable::writeMemberPages (OutputList & ol) const [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
writeQuickMemberLinks() [1/2]
virtual void ClassDefMutable::writeQuickMemberLinks (OutputList & ol, const MemberDef * md) const [pure virtual]
Implements DefinitionMutable.
Implemented in ClassDefImpl, DefinitionMixin< ClassDefMutable >, ClassDefImpl, and DefinitionMixin< ClassDefMutable >.
writeQuickMemberLinks() [2/2]
virtual void ClassDefMutable::writeQuickMemberLinks (OutputList & ol, const MemberDef * md) const [pure virtual]
Implements DefinitionMutable.
Implemented in ClassDefImpl, DefinitionMixin< ClassDefMutable >, ClassDefImpl, and DefinitionMixin< ClassDefMutable >.
writeSummaryLinks() [1/2]
virtual void ClassDefMutable::writeSummaryLinks (OutputList & ol) const [pure virtual]
Implements DefinitionMutable.
Implemented in ClassDefImpl, DefinitionMixin< ClassDefMutable >, ClassDefImpl, and DefinitionMixin< ClassDefMutable >.
writeSummaryLinks() [2/2]
virtual void ClassDefMutable::writeSummaryLinks (OutputList & ol) const [pure virtual]
Implements DefinitionMutable.
Implemented in ClassDefImpl, DefinitionMixin< ClassDefMutable >, ClassDefImpl, and DefinitionMixin< ClassDefMutable >.
writeTagFile() [1/2]
virtual void ClassDefMutable::writeTagFile (TextStream &) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
Referenced by writeTagFile().
writeTagFile() [2/2]
virtual void ClassDefMutable::writeTagFile (TextStream &) [pure virtual]
Implemented in ClassDefImpl, and ClassDefImpl.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/classdef.h
doxygen/src/classdef.h