PerlModDocVisitor Class Reference
Concrete visitor implementation for PerlMod output.
Public Member Functions
PerlModDocVisitor (PerlModOutput &)
virtual ~PerlModDocVisitor ()
void finish ()
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &)
void operator() (const DocHtmlList &)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocHtmlCaption &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &)
void operator() (const DocRef &)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
PerlModDocVisitor (PerlModOutput &)
virtual ~PerlModDocVisitor ()
void finish ()
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &)
void operator() (const DocHtmlList &)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocHtmlCaption &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &)
void operator() (const DocRef &)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
Private Member Functions
template<class T >
void visitChildren (const T &t)
void addLink (const QCString &ref, const QCString &file, const QCString &anchor)
void enterText ()
void leaveText ()
void openItem (const QCString &)
void closeItem ()
void singleItem (const QCString &)
void openSubBlock (const QCString &=QCString())
void closeSubBlock ()
template<class T >
void visitChildren (const T &t)
void addLink (const QCString &ref, const QCString &file, const QCString &anchor)
void enterText ()
void leaveText ()
void openItem (const QCString &)
void closeItem ()
void singleItem (const QCString &)
void openSubBlock (const QCString &=QCString())
void closeSubBlock ()
Private Attributes
PerlModOutput & m_output
bool m_textmode
bool m_textblockstart
QCString m_other
Detailed Description
Concrete visitor implementation for PerlMod output.
Definition at line 284 of file perlmodgen.cpp.
Constructor & Destructor Documentation
PerlModDocVisitor() [1/2]
PerlModDocVisitor::PerlModDocVisitor (PerlModOutput & output)
Definition at line 395 of file perlmodgen.cpp.
  : m_output(output), m_textmode(false), m_textblockstart(FALSE)
{
  m_output.openList("doc");
}
References m_output, and PerlModOutput::openList().
 PerlModDocVisitor() [1/2]
virtual PerlModDocVisitor::~PerlModDocVisitor () [inline], [virtual]
Definition at line 288 of file perlmodgen.cpp.
{ }
PerlModDocVisitor() [2/2]
PerlModDocVisitor::PerlModDocVisitor (PerlModOutput &)
 PerlModDocVisitor() [2/2]
virtual PerlModDocVisitor::~PerlModDocVisitor () [inline], [virtual]
Definition at line 288 of file perlmodgen.cpp.
{ }
Member Function Documentation
addLink() [1/2]
void PerlModDocVisitor::addLink (const QCString & ref, const QCString & file, const QCString & anchor) [private]
Definition at line 408 of file perlmodgen.cpp.
{
  QCString link = file;
  if (!anchor.isEmpty())
    (link += "_1") += anchor;
  m_output.addFieldQuotedString("link", link);
}
References PerlModOutput::addFieldQuotedString(), caseconvert::file, QCString::isEmpty(), and m_output.
Referenced by operator()().
addLink() [2/2]
void PerlModDocVisitor::addLink (const QCString & ref, const QCString & file, const QCString & anchor) [private]
closeItem() [1/2]
void PerlModDocVisitor::closeItem () [private]
Definition at line 422 of file perlmodgen.cpp.
{
  leaveText();
  m_output.closeHash();
}
References PerlModOutput::closeHash(), leaveText(), and m_output.
Referenced by operator()(), and singleItem().
closeItem() [2/2]
void PerlModDocVisitor::closeItem () [private]
closeSubBlock() [1/2]
void PerlModDocVisitor::closeSubBlock () [private]
Definition at line 460 of file perlmodgen.cpp.
{
  leaveText();
  m_output.closeList();
}
References PerlModOutput::closeList(), leaveText(), and m_output.
Referenced by operator()().
closeSubBlock() [2/2]
void PerlModDocVisitor::closeSubBlock () [private]
enterText() [1/2]
void PerlModDocVisitor::enterText () [private]
Definition at line 428 of file perlmodgen.cpp.
{
  if (m_textmode)
    return;
  openItem("text");
  m_output.addField("content").add('\'');
  m_textmode = true;
}
References PerlModOutput::add(), PerlModOutput::addField(), m_output, m_textmode, and openItem().
Referenced by operator()().
enterText() [2/2]
void PerlModDocVisitor::enterText () [private]
finish() [1/2]
void PerlModDocVisitor::finish ()
Definition at line 401 of file perlmodgen.cpp.
{
  leaveText();
  m_output.closeList()
    .add(m_other);
}
References PerlModOutput::add(), PerlModOutput::closeList(), leaveText(), m_other, and m_output.
Referenced by addPerlModDocBlock().
finish() [2/2]
void PerlModDocVisitor::finish ()
leaveText() [1/2]
void PerlModDocVisitor::leaveText () [private]
Definition at line 437 of file perlmodgen.cpp.
{
  if (!m_textmode)
    return;
  m_textmode = false;
  m_output
    .add('\'')
    .closeHash();
}
References PerlModOutput::add(), PerlModOutput::closeHash(), m_output, and m_textmode.
Referenced by closeItem(), closeSubBlock(), finish(), openItem(), openSubBlock(), and operator()().
leaveText() [2/2]
void PerlModDocVisitor::leaveText () [private]
openItem() [1/2]
void PerlModDocVisitor::openItem (const QCString & name) [private]
Definition at line 416 of file perlmodgen.cpp.
{
  leaveText();
  m_output.openHash().addFieldQuotedString("type", name);
}
References PerlModOutput::addFieldQuotedString(), leaveText(), m_output, setup::name, and PerlModOutput::openHash().
Referenced by enterText(), operator()(), and singleItem().
openItem() [2/2]
void PerlModDocVisitor::openItem (const QCString &) [private]
openSubBlock() [1/2]
void PerlModDocVisitor::openSubBlock (const QCString & s = QCString()) [private]
Definition at line 453 of file perlmodgen.cpp.
{
  leaveText();
  m_output.openList(s);
  m_textblockstart = true;
}
References leaveText(), m_output, m_textblockstart, PerlModOutput::openList(), and s.
Referenced by operator()().
openSubBlock() [2/2]
void PerlModDocVisitor::openSubBlock (const QCString & = QCString()) [private]
operator()() [1/114]
void PerlModDocVisitor::operator() (const DocAnchor & anc)
Definition at line 673 of file perlmodgen.cpp.
{
  QCString anchor = anc.file() + "_1" + anc.anchor();
  openItem("anchor");
  m_output.addFieldQuotedString("id", anchor);
  closeItem();
}
References PerlModOutput::addFieldQuotedString(), DocAnchor::anchor(), closeItem(), DocAnchor::file(), m_output, and openItem().
operator()() [2/114]
void PerlModDocVisitor::operator() (const DocAnchor &)
operator()() [3/114]
void PerlModDocVisitor::operator() (const DocAutoList & l)
Definition at line 773 of file perlmodgen.cpp.
{
  openItem("list");
  m_output.addFieldQuotedString("style", l.isEnumList() ? "ordered" : "itemized");
  openSubBlock("content");
  visitChildren(l);
  closeSubBlock();
  closeItem();
}
References PerlModOutput::addFieldQuotedString(), closeItem(), closeSubBlock(), DocAutoList::isEnumList(), m_output, openItem(), openSubBlock(), and visitChildren().
operator()() [4/114]
void PerlModDocVisitor::operator() (const DocAutoList &)
operator()() [5/114]
void PerlModDocVisitor::operator() (const DocAutoListItem & li)
Definition at line 783 of file perlmodgen.cpp.
{
  openSubBlock();
  visitChildren(li);
  closeSubBlock();
}
References closeSubBlock(), openSubBlock(), and visitChildren().
operator()() [6/114]
void PerlModDocVisitor::operator() (const DocAutoListItem &)
operator()() [7/114]
void PerlModDocVisitor::operator() (const DocCite & cite)
Definition at line 761 of file perlmodgen.cpp.
{
  openItem("cite");
  m_output.addFieldQuotedString("text", cite.text());
  closeItem();
}
References PerlModOutput::addFieldQuotedString(), closeItem(), m_output, openItem(), and DocCite::text().
operator()() [8/114]
void PerlModDocVisitor::operator() (const DocCite &)
operator()() [9/114]
void PerlModDocVisitor::operator() (const DocDiaFile & df)
Definition at line 1125 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<diafile name=\""); m_output.add(df->file()); m_output.add("\">");
#endif
  visitChildren(df);
#if 0
  m_output.add("</diafile>");
#endif
}
References PerlModOutput::add(), DocDiagramFileBase::file(), m_output, and visitChildren().
operator()() [10/114]
void PerlModDocVisitor::operator() (const DocDiaFile &)
operator()() [11/114]
void PerlModDocVisitor::operator() (const DocDotFile & df)
Definition at line 1104 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<dotfile name=\""); m_output.add(df->file()); m_output.add("\">");
#endif
  visitChildren(df);
#if 0
  m_output.add("</dotfile>");
#endif
}
References PerlModOutput::add(), DocDiagramFileBase::file(), m_output, and visitChildren().
operator()() [12/114]
void PerlModDocVisitor::operator() (const DocDotFile &)
operator()() [13/114]
void PerlModDocVisitor::operator() (const DocEmoji & sy)
Definition at line 578 of file perlmodgen.cpp.
{
  enterText();
  const char *name = EmojiEntityMapper::instance()->name(sy.index());
  if (name)
  {
    m_output.add(name);
  }
  else
  {
    m_output.add(sy.name());
  }
}
References PerlModOutput::add(), enterText(), EmojiEntityMapper::instance(), m_output, setup::name, EmojiEntityMapper::name(), and sy.
operator()() [14/114]
void PerlModDocVisitor::operator() (const DocEmoji &)
operator()() [15/114]
void PerlModDocVisitor::operator() (const DocFormula & f)
Definition at line 736 of file perlmodgen.cpp.
{
  openItem("formula");
  QCString id;
  id += QCString().setNum(f.id());
  m_output.addFieldQuotedString("id", id).addFieldQuotedString("content", f.text());
  closeItem();
}
References PerlModOutput::addFieldQuotedString(), closeItem(), f, id, m_output, openItem(), and QCString::setNum().
operator()() [16/114]
void PerlModDocVisitor::operator() (const DocFormula &)
operator()() [17/114]
void PerlModDocVisitor::operator() (const DocHorRuler &)
Definition at line 604 of file perlmodgen.cpp.
{
  singleItem("hruler");
}
References singleItem().
operator()() [18/114]
void PerlModDocVisitor::operator() (const DocHorRuler &)
operator()() [19/114]
void PerlModDocVisitor::operator() (const DocHRef & href)
Definition at line 1020 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<ulink url=\""); m_output.add(href.url()); m_output.add("\">");
#endif
  visitChildren(href);
#if 0
  m_output.add("</ulink>");
#endif
}
References PerlModOutput::add(), m_output, DocHRef::url(), and visitChildren().
operator()() [20/114]
void PerlModDocVisitor::operator() (const DocHRef &)
operator()() [21/114]
void PerlModDocVisitor::operator() (const DocHtmlBlockQuote & q)
Definition at line 1298 of file perlmodgen.cpp.
{
  openItem("blockquote");
  openSubBlock("content");
  visitChildren(q);
  closeSubBlock();
  closeItem();
}
References closeItem(), closeSubBlock(), openItem(), openSubBlock(), and visitChildren().
operator()() [22/114]
void PerlModDocVisitor::operator() (const DocHtmlBlockQuote &)
operator()() [23/114]
void PerlModDocVisitor::operator() (const DocHtmlCaption & c)
Definition at line 998 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<caption>");
#endif
  visitChildren(c);
#if 0
  m_output.add("</caption>\n");
#endif
}
References PerlModOutput::add(), c, m_output, and visitChildren().
operator()() [24/114]
void PerlModDocVisitor::operator() (const DocHtmlCaption &)
operator()() [25/114]
void PerlModDocVisitor::operator() (const DocHtmlCell & c)
Definition at line 987 of file perlmodgen.cpp.
{
#if 0
  if (c.isHeading()) m_output.add("<entry thead=\"yes\">"); else m_output.add("<entry thead=\"no\">");
#endif
  visitChildren(c);
#if 0
  m_output.add("</entry>");
#endif
}
References PerlModOutput::add(), c, m_output, and visitChildren().
operator()() [26/114]
void PerlModDocVisitor::operator() (const DocHtmlCell &)
operator()() [27/114]
void PerlModDocVisitor::operator() (const DocHtmlDescData & dd)
Definition at line 949 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<listitem>");
#endif
  visitChildren(dd);
#if 0
  m_output.add("</listitem>\n");
#endif
}
References PerlModOutput::add(), m_output, and visitChildren().
operator()() [28/114]
void PerlModDocVisitor::operator() (const DocHtmlDescData &)
operator()() [29/114]
void PerlModDocVisitor::operator() (const DocHtmlDescList & dl)
Definition at line 927 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<variablelist>\n");
#endif
  visitChildren(dl);
#if 0
  m_output.add("</variablelist>\n");
#endif
}
References PerlModOutput::add(), m_output, and visitChildren().
operator()() [30/114]
void PerlModDocVisitor::operator() (const DocHtmlDescList &)
operator()() [31/114]
void PerlModDocVisitor::operator() (const DocHtmlDescTitle & dt)
Definition at line 938 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<varlistentry><term>");
#endif
  visitChildren(dt);
#if 0
  m_output.add("</term></varlistentry>\n");
#endif
}
References PerlModOutput::add(), m_output, and visitChildren().
operator()() [32/114]
void PerlModDocVisitor::operator() (const DocHtmlDescTitle &)
operator()() [33/114]
void PerlModDocVisitor::operator() (const DocHtmlDetails & details)
Definition at line 1040 of file perlmodgen.cpp.
{
  openItem("details");
  auto summary = details.summary();
  if (summary)
  {
    std::visit(*this,*summary);
  }
  openSubBlock("content");
  visitChildren(details);
  closeSubBlock();
  closeItem();
}
References closeItem(), closeSubBlock(), openItem(), openSubBlock(), and visitChildren().
operator()() [34/114]
void PerlModDocVisitor::operator() (const DocHtmlDetails &)
operator()() [35/114]
void PerlModDocVisitor::operator() (const DocHtmlHeader & header)
Definition at line 1054 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<sect"); m_output.add(header.level()); m_output.add(">");
#endif
  visitChildren(header);
#if 0
  m_output.add("</sect"); m_output.add(header.level()); m_output.add(">\n");
#endif
}
References PerlModOutput::add(), DocHtmlHeader::level(), m_output, and visitChildren().
operator()() [36/114]
void PerlModDocVisitor::operator() (const DocHtmlHeader &)
operator()() [37/114]
void PerlModDocVisitor::operator() (const DocHtmlList & l)
Definition at line 892 of file perlmodgen.cpp.
{
  openItem("list");
  m_output.addFieldQuotedString("style", (l.type() == DocHtmlList::Ordered) ? "ordered" : "itemized");
  for (const auto &opt : l.attribs())
  {
    if (opt.name=="type")
    {
      m_output.addFieldQuotedString("list_type", qPrint(opt.value));
    }
    if (opt.name=="start")
    {
      m_output.addFieldQuotedString("start", qPrint(opt.value));
    }
  }
  openSubBlock("content");
  visitChildren(l);
  closeSubBlock();
  closeItem();
}
References PerlModOutput::addFieldQuotedString(), DocHtmlList::attribs(), closeItem(), closeSubBlock(), m_output, openItem(), openSubBlock(), DocHtmlList::Ordered, qPrint(), DocHtmlList::type(), and visitChildren().
operator()() [38/114]
void PerlModDocVisitor::operator() (const DocHtmlList &)
operator()() [39/114]
void PerlModDocVisitor::operator() (const DocHtmlListItem & l)
Definition at line 913 of file perlmodgen.cpp.
{
  for (const auto &opt : l.attribs())
  {
    if (opt.name=="value")
    {
      m_output.addFieldQuotedString("item_value", qPrint(opt.value));
    }
  }
  openSubBlock();
  visitChildren(l);
  closeSubBlock();
}
References PerlModOutput::addFieldQuotedString(), DocHtmlListItem::attribs(), closeSubBlock(), m_output, openSubBlock(), qPrint(), and visitChildren().
operator()() [40/114]
void PerlModDocVisitor::operator() (const DocHtmlListItem &)
operator()() [41/114]
void PerlModDocVisitor::operator() (const DocHtmlRow & r)
Definition at line 976 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<row>\n");
#endif
  visitChildren(r);
#if 0
  m_output.add("</row>\n");
#endif
}
References PerlModOutput::add(), m_output, r, and visitChildren().
operator()() [42/114]
void PerlModDocVisitor::operator() (const DocHtmlRow &)
operator()() [43/114]
void PerlModDocVisitor::operator() (const DocHtmlSummary & summary)
Definition at line 1031 of file perlmodgen.cpp.
{
  openItem("summary");
  openSubBlock("content");
  visitChildren(summary);
  closeSubBlock();
  closeItem();
}
References closeItem(), closeSubBlock(), openItem(), openSubBlock(), and visitChildren().
operator()() [44/114]
void PerlModDocVisitor::operator() (const DocHtmlSummary &)
operator()() [45/114]
void PerlModDocVisitor::operator() (const DocHtmlTable & t)
Definition at line 960 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<table rows=\""); m_output.add(t.numRows());
  m_output.add("\" cols=\""); m_output.add(t.numCols()); m_output.add("\">");
#endif
  if (t.caption())
  {
    std::visit(*this,*t.caption());
  }
  visitChildren(t);
#if 0
  m_output.add("</table>\n");
#endif
}
References PerlModOutput::add(), DocHtmlTable::caption(), m_output, DocHtmlTable::numRows(), and visitChildren().
operator()() [46/114]
void PerlModDocVisitor::operator() (const DocHtmlTable &)
operator()() [47/114]
void PerlModDocVisitor::operator() (const DocImage & img)
Definition at line 1065 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<image type=\"");
  switch(img.type())
  {
  case DocImage::Html: m_output.add("html"); break;
  case DocImage::Latex: m_output.add("latex"); break;
  case DocImage::Rtf: m_output.add("rtf"); break;
  }
  m_output.add("\"");
  QCString baseName=img.name();
  int i;
  if ((i=baseName.findRev('/'))!=-1 || (i=baseName.findRev('\\'))!=-1)
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  m_output.add(" name=\""); m_output.add(baseName); m_output.add("\"");
  if (!img.width().isEmpty())
  {
    m_output.add(" width=\"");
    m_output.addQuoted(img.width());
    m_output.add("\"");
  }
  else if (!img.height().isEmpty())
  {
    m_output.add(" height=\"");
    m_output.addQuoted(img.height());
    m_output.add("\"");
  }
  m_output.add(">");
#endif
  visitChildren(img);
#if 0
  m_output.add("</image>");
#endif
}
References PerlModOutput::add(), PerlModOutput::addQuoted(), QCString::findRev(), DocImage::height(), DocImage::Html, QCString::isEmpty(), DocImage::Latex, QCString::length(), m_output, DocImage::name(), QCString::right(), DocImage::Rtf, DocImage::type(), visitChildren(), and DocImage::width().
operator()() [48/114]
void PerlModDocVisitor::operator() (const DocImage &)
operator()() [49/114]
void PerlModDocVisitor::operator() (const DocInclude & inc)
Definition at line 681 of file perlmodgen.cpp.
{
  const char *type = 0;
  switch (inc.type())
  {
    case DocInclude::IncWithLines:
      return;
    case DocInclude::Include:
      return;
    case DocInclude::DontInclude: return;
    case DocInclude::DontIncWithLines: return;
    case DocInclude::HtmlInclude: type = "htmlonly"; break;
    case DocInclude::LatexInclude: type = "latexonly"; break;
    case DocInclude::RtfInclude: type = "rtfonly"; break;
    case DocInclude::ManInclude: type = "manonly"; break;
    case DocInclude::XmlInclude: type = "xmlonly"; break;
    case DocInclude::DocbookInclude: type = "docbookonly"; break;
    case DocInclude::VerbInclude: type = "preformatted"; break;
    case DocInclude::Snippet: return;
    case DocInclude::SnipWithLines: return;
    case DocInclude::SnippetDoc:
    case DocInclude::IncludeDoc:
      err("Internal inconsistency: found switch SnippetDoc / IncludeDoc in file: %s"
          "Please create a bug report\n",__FILE__);
      break;
  }
  openItem(type);
  m_output.addFieldQuotedString("content", inc.text());
  closeItem();
}
References PerlModOutput::addFieldQuotedString(), closeItem(), DocInclude::DocbookInclude, DocInclude::DontInclude, DocInclude::DontIncWithLines, err(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::LatexInclude, m_output, DocInclude::ManInclude, openItem(), DocInclude::RtfInclude, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, DocInclude::text(), DocInclude::type(), DocInclude::VerbInclude, and DocInclude::XmlInclude.
operator()() [50/114]
void PerlModDocVisitor::operator() (const DocInclude &)
operator()() [51/114]
void PerlModDocVisitor::operator() (const DocIncOperator &)
Definition at line 712 of file perlmodgen.cpp.
{
#if 0
  //printf("DocIncOperator: type=%d first=%d, last=%d text='%s'\n",
  // op.type(),op.isFirst(),op.isLast(),op.text().data());
  if (op.isFirst())
  {
    m_output.add("<programlisting>");
  }
  if (op.type()!=DocIncOperator::Skip)
  {
    parseCode(m_ci,op.context(),op.text(),FALSE,0);
  }
  if (op.isLast())
  {
    m_output.add("</programlisting>");
  }
  else
  {
    m_output.add('\n');
  }
#endif
}
References PerlModOutput::add(), FALSE, m_output, parseCode(), and DocIncOperator::Skip.
operator()() [52/114]
void PerlModDocVisitor::operator() (const DocIncOperator &)
operator()() [53/114]
void PerlModDocVisitor::operator() (const DocIndexEntry &)
Definition at line 745 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<indexentry>"
           "<primaryie>");
  m_output.addQuoted(ie->entry());
  m_output.add("</primaryie>"
           "<secondaryie></secondaryie>"
           "</indexentry>");
#endif
}
References PerlModOutput::add(), PerlModOutput::addQuoted(), and m_output.
operator()() [54/114]
void PerlModDocVisitor::operator() (const DocIndexEntry &)
operator()() [55/114]
void PerlModDocVisitor::operator() (const DocInternal & i)
Definition at line 1009 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<internal>");
#endif
  visitChildren(i);
#if 0
  m_output.add("</internal>");
#endif
}
References PerlModOutput::add(), m_output, and visitChildren().
operator()() [56/114]
void PerlModDocVisitor::operator() (const DocInternal &)
operator()() [57/114]
void PerlModDocVisitor::operator() (const DocInternalRef & ref)
Definition at line 1283 of file perlmodgen.cpp.
{
  openItem("ref");
  addLink(QCString(),ref.file(),ref.anchor());
  openSubBlock("content");
  visitChildren(ref);
  closeSubBlock();
  closeItem();
}
References addLink(), DocInternalRef::anchor(), closeItem(), closeSubBlock(), DocInternalRef::file(), openItem(), openSubBlock(), and visitChildren().
operator()() [58/114]
void PerlModDocVisitor::operator() (const DocInternalRef &)
operator()() [59/114]
void PerlModDocVisitor::operator() (const DocLineBreak &)
Definition at line 599 of file perlmodgen.cpp.
{
  singleItem("linebreak");
}
References singleItem().
operator()() [60/114]
void PerlModDocVisitor::operator() (const DocLineBreak &)
operator()() [61/114]
void PerlModDocVisitor::operator() (const DocLink & lnk)
Definition at line 1137 of file perlmodgen.cpp.
{
  openItem("link");
  addLink(lnk.ref(), lnk.file(), lnk.anchor());
  visitChildren(lnk);
  closeItem();
}
References addLink(), DocLink::anchor(), closeItem(), DocLink::file(), openItem(), DocLink::ref(), and visitChildren().
operator()() [62/114]
void PerlModDocVisitor::operator() (const DocLink &)
operator()() [63/114]
void PerlModDocVisitor::operator() (const DocLinkedWord & w)
Definition at line 494 of file perlmodgen.cpp.
{
  openItem("url");
  addLink(w.ref(), w.file(), w.anchor());
  m_output.addFieldQuotedString("content", w.word());
  closeItem();
}
References PerlModOutput::addFieldQuotedString(), addLink(), closeItem(), m_output, openItem(), and w.
operator()() [64/114]
void PerlModDocVisitor::operator() (const DocLinkedWord &)
operator()() [65/114]
void PerlModDocVisitor::operator() (const DocMscFile & df)
Definition at line 1114 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<mscfile name=\""); m_output.add(df->file()); m_output.add("\">");
#endif
  visitChildren(df);
#if 0
  m_output.add("<mscfile>");
#endif
}
References PerlModOutput::add(), DocDiagramFileBase::file(), m_output, and visitChildren().
operator()() [66/114]
void PerlModDocVisitor::operator() (const DocMscFile &)
operator()() [67/114]
void PerlModDocVisitor::operator() (const DocPara & p)
Definition at line 790 of file perlmodgen.cpp.
{
  if (m_textblockstart)
    m_textblockstart = false;
  else
    singleItem("parbreak");
  /*
  openItem("para");
  openSubBlock("content");
  */
  visitChildren(p);
  /*
  closeSubBlock();
  closeItem();
  */
}
References m_textblockstart, p, singleItem(), and visitChildren().
operator()() [68/114]
void PerlModDocVisitor::operator() (const DocPara &)
operator()() [69/114]
void PerlModDocVisitor::operator() (const DocParamList & pl)
Definition at line 1205 of file perlmodgen.cpp.
{
  leaveText();
  m_output.openHash().openList("parameters");
  for (const auto &param : pl.parameters())
  {
    QCString name;
    const DocWord *word = std::get_if<DocWord>(&param);
    const DocLinkedWord *linkedWord = std::get_if<DocLinkedWord>(&param);
    if (word)
    {
      name = word->word();
    }
    else if (linkedWord)
    {
      name = linkedWord->word();
    }
    QCString dir = "";
    const DocParamSect *sect = std::get_if<DocParamSect>(pl.parent());
    if (sect && sect->hasInOutSpecifier())
    {
      if (pl.direction()!=DocParamSect::Unspecified)
      {
        if (pl.direction()==DocParamSect::In)
        {
          dir = "in";
        }
        else if (pl.direction()==DocParamSect::Out)
        {
          dir = "out";
        }
        else if (pl.direction()==DocParamSect::InOut)
        {
          dir = "in,out";
        }
      }
    }
    m_output.openHash()
      .addFieldQuotedString("name", name).addFieldQuotedString("dir", dir)
      .closeHash();
  }
  m_output.closeList()
    .openList("doc");
  for (const auto &par : pl.paragraphs())
  {
    std::visit(*this,par);
  }
  leaveText();
  m_output.closeList()
    .closeHash();
}
References PerlModOutput::addFieldQuotedString(), PerlModOutput::closeHash(), PerlModOutput::closeList(), DocParamList::direction(), DocParamSect::hasInOutSpecifier(), DocParamSect::In, DocParamSect::InOut, leaveText(), m_output, setup::name, PerlModOutput::openHash(), PerlModOutput::openList(), DocParamSect::Out, DocParamList::paragraphs(), DocParamList::parameters(), DocNode::parent(), DocParamSect::Unspecified, DocLinkedWord::word(), and word.
operator()() [70/114]
void PerlModDocVisitor::operator() (const DocParamList &)
operator()() [71/114]
void PerlModDocVisitor::operator() (const DocParamSect & s)
Definition at line 1178 of file perlmodgen.cpp.
{
  leaveText();
  const char *type = 0;
  switch(s.type())
  {
    case DocParamSect::Param: type = "params"; break;
    case DocParamSect::RetVal: type = "retvals"; break;
    case DocParamSect::Exception: type = "exceptions"; break;
    case DocParamSect::TemplateParam: type = "templateparam"; break;
    case DocParamSect::Unknown:
      err("unknown parameter section found\n");
      break;
  }
  m_output.openHash();
  //openOther();
  openSubBlock(type);
  visitChildren(s);
  closeSubBlock();
  //closeOther();
  m_output.closeHash();
}
References PerlModOutput::closeHash(), closeSubBlock(), err(), DocParamSect::Exception, leaveText(), m_output, PerlModOutput::openHash(), openSubBlock(), DocParamSect::Param, DocParamSect::RetVal, s, DocParamSect::TemplateParam, DocParamSect::Unknown, and visitChildren().
operator()() [72/114]
void PerlModDocVisitor::operator() (const DocParamSect &)
operator()() [73/114]
void PerlModDocVisitor::operator() (const DocParBlock & pb)
Definition at line 1311 of file perlmodgen.cpp.
{
  visitChildren(pb);
}
References visitChildren().
operator()() [74/114]
void PerlModDocVisitor::operator() (const DocParBlock &)
operator()() [75/114]
void PerlModDocVisitor::operator() (const DocRef & ref)
Definition at line 1145 of file perlmodgen.cpp.
{
  openItem("ref");
  if (!ref.hasLinkText())
    m_output.addFieldQuotedString("text", ref.targetTitle());
  openSubBlock("content");
  visitChildren(ref);
  closeSubBlock();
  closeItem();
}
References PerlModOutput::addFieldQuotedString(), closeItem(), closeSubBlock(), DocRef::hasLinkText(), m_output, openItem(), openSubBlock(), DocRef::targetTitle(), and visitChildren().
operator()() [76/114]
void PerlModDocVisitor::operator() (const DocRef &)
operator()() [77/114]
void PerlModDocVisitor::operator() (const DocRoot & r)
Definition at line 807 of file perlmodgen.cpp.
{
  visitChildren(r);
}
References r, and visitChildren().
operator()() [78/114]
void PerlModDocVisitor::operator() (const DocRoot &)
operator()() [79/114]
void PerlModDocVisitor::operator() (const DocSecRefItem & ref)
Definition at line 1156 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<tocitem id=\""); m_output.add(ref->file()); m_output.add("_1"); m_output.add(ref->anchor()); m_output.add("\">");
#endif
  visitChildren(ref);
#if 0
  m_output.add("</tocitem>");
#endif
}
References PerlModOutput::add(), DocSecRefItem::anchor(), DocSecRefItem::file(), m_output, and visitChildren().
operator()() [80/114]
void PerlModDocVisitor::operator() (const DocSecRefItem &)
operator()() [81/114]
void PerlModDocVisitor::operator() (const DocSecRefList & l)
Definition at line 1167 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<toclist>");
#endif
  visitChildren(l);
#if 0
  m_output.add("</toclist>");
#endif
}
References PerlModOutput::add(), m_output, and visitChildren().
operator()() [82/114]
void PerlModDocVisitor::operator() (const DocSecRefList &)
operator()() [83/114]
void PerlModDocVisitor::operator() (const DocSection & s)
Definition at line 881 of file perlmodgen.cpp.
{
  QCString sect = QCString().sprintf("sect%d",s.level());
  openItem(sect);
  m_output.addFieldQuotedString("title", s.title());
  openSubBlock("content");
  visitChildren(s);
  closeSubBlock();
  closeItem();
}
References PerlModOutput::addFieldQuotedString(), closeItem(), closeSubBlock(), m_output, openItem(), openSubBlock(), s, QCString::sprintf(), and visitChildren().
operator()() [84/114]
void PerlModDocVisitor::operator() (const DocSection &)
operator()() [85/114]
void PerlModDocVisitor::operator() (const DocSeparator &)
Definition at line 1201 of file perlmodgen.cpp.
{
}
operator()() [86/114]
void PerlModDocVisitor::operator() (const DocSeparator &)
operator()() [87/114]
void PerlModDocVisitor::operator() (const DocSimpleList & l)
Definition at line 861 of file perlmodgen.cpp.
{
  openItem("list");
  m_output.addFieldQuotedString("style", "itemized");
  openSubBlock("content");
  visitChildren(l);
  closeSubBlock();
  closeItem();
}
References PerlModOutput::addFieldQuotedString(), closeItem(), closeSubBlock(), m_output, openItem(), openSubBlock(), and visitChildren().
operator()() [88/114]
void PerlModDocVisitor::operator() (const DocSimpleList &)
operator()() [89/114]
void PerlModDocVisitor::operator() (const DocSimpleListItem & li)
Definition at line 871 of file perlmodgen.cpp.
{
  openSubBlock();
  if (li.paragraph())
  {
    std::visit(*this,*li.paragraph());
  }
  closeSubBlock();
}
References closeSubBlock(), openSubBlock(), and DocSimpleListItem::paragraph().
operator()() [90/114]
void PerlModDocVisitor::operator() (const DocSimpleListItem &)
operator()() [91/114]
void PerlModDocVisitor::operator() (const DocSimpleSect & s)
Definition at line 812 of file perlmodgen.cpp.
{
  const char *type = 0;
  switch (s.type())
  {
  case DocSimpleSect::See: type = "see"; break;
  case DocSimpleSect::Return: type = "return"; break;
  case DocSimpleSect::Author: type = "author"; break;
  case DocSimpleSect::Authors: type = "authors"; break;
  case DocSimpleSect::Version: type = "version"; break;
  case DocSimpleSect::Since: type = "since"; break;
  case DocSimpleSect::Date: type = "date"; break;
  case DocSimpleSect::Note: type = "note"; break;
  case DocSimpleSect::Warning: type = "warning"; break;
  case DocSimpleSect::Pre: type = "pre"; break;
  case DocSimpleSect::Post: type = "post"; break;
  case DocSimpleSect::Copyright: type = "copyright"; break;
  case DocSimpleSect::Invar: type = "invariant"; break;
  case DocSimpleSect::Remark: type = "remark"; break;
  case DocSimpleSect::Attention: type = "attention"; break;
  case DocSimpleSect::User: type = "par"; break;
  case DocSimpleSect::Rcs: type = "rcs"; break;
  case DocSimpleSect::Unknown:
    err("unknown simple section found\n");
    break;
  }
  leaveText();
  m_output.openHash();
  //openOther();
  openSubBlock(type);
  if (s.title())
  {
    std::visit(*this,*s.title());
  }
  visitChildren(s);
  closeSubBlock();
  //closeOther();
  m_output.closeHash();
}
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, PerlModOutput::closeHash(), closeSubBlock(), DocSimpleSect::Copyright, DocSimpleSect::Date, err(), DocSimpleSect::Invar, leaveText(), m_output, DocSimpleSect::Note, PerlModOutput::openHash(), openSubBlock(), DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, s, DocSimpleSect::See, DocSimpleSect::Since, DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, visitChildren(), and DocSimpleSect::Warning.
operator()() [92/114]
void PerlModDocVisitor::operator() (const DocSimpleSect &)
operator()() [93/114]
void PerlModDocVisitor::operator() (const DocSimpleSectSep &)
Definition at line 757 of file perlmodgen.cpp.
{
}
operator()() [94/114]
void PerlModDocVisitor::operator() (const DocSimpleSectSep &)
operator()() [95/114]
void PerlModDocVisitor::operator() (const DocStyleChange & s)
Definition at line 609 of file perlmodgen.cpp.
{
  const char *style = 0;
  switch (s.style())
  {
    case DocStyleChange::Bold: style = "bold"; break;
    case DocStyleChange::S: style = "s"; break;
    case DocStyleChange::Strike: style = "strike"; break;
    case DocStyleChange::Del: style = "del"; break;
    case DocStyleChange::Underline: style = "underline"; break;
    case DocStyleChange::Ins: style = "ins"; break;
    case DocStyleChange::Italic: style = "italic"; break;
    case DocStyleChange::Code: style = "code"; break;
    case DocStyleChange::Subscript: style = "subscript"; break;
    case DocStyleChange::Superscript: style = "superscript"; break;
    case DocStyleChange::Center: style = "center"; break;
    case DocStyleChange::Small: style = "small"; break;
    case DocStyleChange::Cite: style = "cite"; break;
    case DocStyleChange::Preformatted: style = "preformatted"; break;
    case DocStyleChange::Div: style = "div"; break;
    case DocStyleChange::Span: style = "span"; break;
  }
  openItem("style");
  m_output.addFieldQuotedString("style", style)
    .addFieldBoolean("enable", s.enable());
  closeItem();
}
References PerlModOutput::addFieldBoolean(), PerlModOutput::addFieldQuotedString(), DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Cite, closeItem(), DocStyleChange::Code, DocStyleChange::Del, DocStyleChange::Div, DocStyleChange::Ins, DocStyleChange::Italic, m_output, openItem(), DocStyleChange::Preformatted, s, DocStyleChange::S, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::Strike, style, DocStyleChange::Subscript, DocStyleChange::Superscript, and DocStyleChange::Underline.
operator()() [96/114]
void PerlModDocVisitor::operator() (const DocStyleChange &)
operator()() [97/114]
void PerlModDocVisitor::operator() (const DocSymbol & sy)
Definition at line 508 of file perlmodgen.cpp.
{
  const HtmlEntityMapper::PerlSymb *res = HtmlEntityMapper::instance()->perl(sy.symbol());
  const char *accent=0;
  if (res->symb)
  {
    switch (res->type)
    {
      case HtmlEntityMapper::Perl_string:
        enterText();
        m_output.add(res->symb);
        break;
      case HtmlEntityMapper::Perl_char:
        enterText();
        m_output.add(res->symb[0]);
        break;
      case HtmlEntityMapper::Perl_symbol:
        leaveText();
        openItem("symbol");
        m_output.addFieldQuotedString("symbol", res->symb);
        closeItem();
        break;
      default:
        switch(res->type)
        {
          case HtmlEntityMapper::Perl_umlaut:
            accent = "umlaut";
            break;
          case HtmlEntityMapper::Perl_acute:
            accent = "acute";
            break;
          case HtmlEntityMapper::Perl_grave:
            accent = "grave";
            break;
          case HtmlEntityMapper::Perl_circ:
            accent = "circ";
            break;
          case HtmlEntityMapper::Perl_slash:
            accent = "slash";
            break;
          case HtmlEntityMapper::Perl_tilde:
            accent = "tilde";
            break;
          case HtmlEntityMapper::Perl_cedilla:
            accent = "cedilla";
            break;
          case HtmlEntityMapper::Perl_ring:
            accent = "ring";
            break;
          default:
            break;
        }
        leaveText();
        if (accent)
        {
          openItem("accent");
          m_output
            .addFieldQuotedString("accent", accent)
            .addFieldQuotedChar("letter", res->symb[0]);
          closeItem();
        }
        break;
    }
  }
  else
  {
    err("perl: non supported HTML-entity found: %s\n",HtmlEntityMapper::instance()->html(sy.symbol(),TRUE));
  }
}
References PerlModOutput::add(), PerlModOutput::addFieldQuotedChar(), PerlModOutput::addFieldQuotedString(), closeItem(), enterText(), err(), HtmlEntityMapper::instance(), leaveText(), m_output, openItem(), HtmlEntityMapper::perl(), HtmlEntityMapper::Perl_acute, HtmlEntityMapper::Perl_cedilla, HtmlEntityMapper::Perl_char, HtmlEntityMapper::Perl_circ, HtmlEntityMapper::Perl_grave, HtmlEntityMapper::Perl_ring, HtmlEntityMapper::Perl_slash, HtmlEntityMapper::Perl_string, HtmlEntityMapper::Perl_symbol, HtmlEntityMapper::Perl_tilde, HtmlEntityMapper::Perl_umlaut, sy, HtmlEntityMapper::PerlSymb::symb, TRUE, and HtmlEntityMapper::PerlSymb::type.
operator()() [98/114]
void PerlModDocVisitor::operator() (const DocSymbol &)
operator()() [99/114]
void PerlModDocVisitor::operator() (const DocText & t)
Definition at line 1293 of file perlmodgen.cpp.
{
  visitChildren(t);
}
References visitChildren().
operator()() [100/114]
void PerlModDocVisitor::operator() (const DocText &)
operator()() [101/114]
void PerlModDocVisitor::operator() (const DocTitle & t)
Definition at line 852 of file perlmodgen.cpp.
{
  openItem("title");
  openSubBlock("content");
  visitChildren(t);
  closeSubBlock();
  closeItem();
}
References closeItem(), closeSubBlock(), openItem(), openSubBlock(), and visitChildren().
operator()() [102/114]
void PerlModDocVisitor::operator() (const DocTitle &)
operator()() [103/114]
void PerlModDocVisitor::operator() (const DocURL & u)
Definition at line 592 of file perlmodgen.cpp.
{
  openItem("url");
  m_output.addFieldQuotedString("content", u.url());
  closeItem();
}
References PerlModOutput::addFieldQuotedString(), closeItem(), m_output, openItem(), and DocURL::url().
operator()() [104/114]
void PerlModDocVisitor::operator() (const DocURL &)
operator()() [105/114]
void PerlModDocVisitor::operator() (const DocVerbatim & s)
Definition at line 637 of file perlmodgen.cpp.
{
  const char *type = 0;
  switch (s.type())
  {
    case DocVerbatim::Code:
#if 0
      m_output.add("<programlisting>");
      parseCode(m_ci,s->context(),s->text(),FALSE,0);
      m_output.add("</programlisting>");
      return;
#endif
    case DocVerbatim::JavaDocCode:
    case DocVerbatim::JavaDocLiteral:
    case DocVerbatim::Verbatim: type = "preformatted"; break;
    case DocVerbatim::HtmlOnly: type = "htmlonly"; break;
    case DocVerbatim::RtfOnly: type = "rtfonly"; break;
    case DocVerbatim::ManOnly: type = "manonly"; break;
    case DocVerbatim::LatexOnly: type = "latexonly"; break;
    case DocVerbatim::XmlOnly: type = "xmlonly"; break;
    case DocVerbatim::DocbookOnly: type = "docbookonly"; break;
    case DocVerbatim::Dot: type = "dot"; break;
    case DocVerbatim::Msc: type = "msc"; break;
    case DocVerbatim::PlantUML: type = "plantuml"; break;
  }
  openItem(type);
  if (s.hasCaption())
  {
     openSubBlock("caption");
     visitChildren(s);
     closeSubBlock();
  }
  m_output.addFieldQuotedString("content", s.text());
  closeItem();
}
References PerlModOutput::add(), PerlModOutput::addFieldQuotedString(), closeItem(), closeSubBlock(), DocVerbatim::Code, DocVerbatim::DocbookOnly, DocVerbatim::Dot, FALSE, DocVerbatim::HtmlOnly, DocVerbatim::JavaDocCode, DocVerbatim::JavaDocLiteral, DocVerbatim::LatexOnly, m_output, DocVerbatim::ManOnly, DocVerbatim::Msc, openItem(), openSubBlock(), parseCode(), DocVerbatim::PlantUML, DocVerbatim::RtfOnly, s, DocVerbatim::Verbatim, visitChildren(), and DocVerbatim::XmlOnly.
operator()() [106/114]
void PerlModDocVisitor::operator() (const DocVerbatim &)
operator()() [107/114]
void PerlModDocVisitor::operator() (const DocVhdlFlow &)
Definition at line 1307 of file perlmodgen.cpp.
{
}
operator()() [108/114]
void PerlModDocVisitor::operator() (const DocVhdlFlow &)
operator()() [109/114]
void PerlModDocVisitor::operator() (const DocWhiteSpace &)
Definition at line 502 of file perlmodgen.cpp.
{
  enterText();
  m_output.add(' ');
}
References PerlModOutput::add(), enterText(), and m_output.
operator()() [110/114]
void PerlModDocVisitor::operator() (const DocWhiteSpace &)
operator()() [111/114]
void PerlModDocVisitor::operator() (const DocWord & w)
Definition at line 488 of file perlmodgen.cpp.
{
  enterText();
  m_output.addQuoted(w.word());
}
References PerlModOutput::addQuoted(), enterText(), m_output, and w.
operator()() [112/114]
void PerlModDocVisitor::operator() (const DocWord &)
operator()() [113/114]
void PerlModDocVisitor::operator() (const DocXRefItem & x)
Definition at line 1259 of file perlmodgen.cpp.
{
#if 0
  m_output.add("<xrefsect id=\"");
  m_output.add(x->file()); m_output.add("_1"); m_output.add(x->anchor());
  m_output.add("\">");
  m_output.add("<xreftitle>");
  m_output.addQuoted(x->title());
  m_output.add("</xreftitle>");
  m_output.add("<xrefdescription>");
#endif
  if (x.title().isEmpty()) return;
  openItem("xrefitem");
  openSubBlock("content");
  visitChildren(x);
  if (x.title().isEmpty()) return;
  closeSubBlock();
  closeItem();
#if 0
  m_output.add("</xrefdescription>");
  m_output.add("</xrefsect>");
#endif
}
References PerlModOutput::add(), PerlModOutput::addQuoted(), closeItem(), closeSubBlock(), m_output, openItem(), openSubBlock(), visitChildren(), and x.
operator()() [114/114]
void PerlModDocVisitor::operator() (const DocXRefItem &)
singleItem() [1/2]
void PerlModDocVisitor::singleItem (const QCString & name) [private]
Definition at line 447 of file perlmodgen.cpp.
{
  openItem(name);
  closeItem();
}
References closeItem(), setup::name, and openItem().
Referenced by operator()().
singleItem() [2/2]
void PerlModDocVisitor::singleItem (const QCString &) [private]
visitChildren() [1/2]
template<class T >
void PerlModDocVisitor::visitChildren (const T & t) [inline], [private]
Definition at line 361 of file perlmodgen.cpp.
    {
      for (const auto &child : t.children())
      {
         std::visit(*this, child);
      }
    }
Referenced by operator()().
visitChildren() [2/2]
template<class T >
void PerlModDocVisitor::visitChildren (const T & t) [inline], [private]
Definition at line 361 of file perlmodgen.cpp.
    {
      for (const auto &child : t.children())
      {
         std::visit(*this, child);
      }
    }
Member Data Documentation
m_other
QCString PerlModDocVisitor::m_other [private]
Definition at line 392 of file perlmodgen.cpp.
Referenced by finish().
m_output
PerlModOutput & PerlModDocVisitor::m_output [private]
Definition at line 389 of file perlmodgen.cpp.
Referenced by addLink(), closeItem(), closeSubBlock(), enterText(), finish(), leaveText(), openItem(), openSubBlock(), operator()(), and PerlModDocVisitor().
m_textblockstart
bool PerlModDocVisitor::m_textblockstart [private]
Definition at line 391 of file perlmodgen.cpp.
Referenced by openSubBlock(), and operator()().
m_textmode
bool PerlModDocVisitor::m_textmode [private]
Definition at line 390 of file perlmodgen.cpp.
Referenced by enterText(), and leaveText().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/perlmodgen.cpp
doxygen/src/perlmodgen.cpp