TemplateNodeEncoding Class Reference
Class representing the 'encoding' tag in a template.
Public Member Functions
TemplateNodeEncoding (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
TemplateNodeEncoding (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
Private Attributes
ExprAstPtr m_encExpr
TemplateNodeList m_nodes
Additional Inherited Members
Detailed Description
Class representing the 'encoding' tag in a template.
Definition at line 4614 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeEncoding() [1/2]
TemplateNodeEncoding::TemplateNodeEncoding (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4617 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeEncoding>(parser,parent,line)
    {
      TRACE(("{TemplateNodeEncoding(%s)\n",qPrint(data)));
      ExpressionParser ep(parser,line);
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"encoding tag is missing encoding argument");
        m_encExpr.reset();
      }
      else
      {
        m_encExpr = ep.parse(data);
      }
      StringVector stopAt = { "endencoding" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endencoding
      TRACE(("}TemplateNodeEncoding(%s)\n",qPrint(data)));
    }
References data, m_encExpr, m_nodes, TemplateNodeCreator< TemplateNodeEncoding >::m_templateName, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), TRACE, and TemplateParser::warn().
TemplateNodeEncoding() [2/2]
TemplateNodeEncoding::TemplateNodeEncoding (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4617 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeEncoding>(parser,parent,line)
    {
      TRACE(("{TemplateNodeEncoding(%s)\n",qPrint(data)));
      ExpressionParser ep(parser,line);
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"encoding tag is missing encoding argument");
        m_encExpr.reset();
      }
      else
      {
        m_encExpr = ep.parse(data);
      }
      StringVector stopAt = { "endencoding" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endencoding
      TRACE(("}TemplateNodeEncoding(%s)\n",qPrint(data)));
    }
References data, m_encExpr, m_nodes, TemplateNodeCreator< TemplateNodeEncoding >::m_templateName, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), TRACE, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeEncoding::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4636 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      QCString encStr;
      if (m_encExpr)
      {
        encStr = m_encExpr->resolve(c).toString();
      }
      QCString oldEncStr = ci->encoding();
      if (!encStr.isEmpty())
      {
        ci->setEncoding(m_templateName,m_line,encStr);
      }
      m_nodes.render(ts,c);
      ci->setEncoding(m_templateName,m_line,oldEncStr);
    }
References c, TemplateContextImpl::encoding(), QCString::isEmpty(), m_encExpr, TemplateNodeCreator< TemplateNodeEncoding >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeEncoding >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::setEncoding(), and TemplateContextImpl::setLocation().
render() [2/2]
void TemplateNodeEncoding::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4636 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      QCString encStr;
      if (m_encExpr)
      {
        encStr = m_encExpr->resolve(c).toString();
      }
      QCString oldEncStr = ci->encoding();
      if (!encStr.isEmpty())
      {
        ci->setEncoding(m_templateName,m_line,encStr);
      }
      m_nodes.render(ts,c);
      ci->setEncoding(m_templateName,m_line,oldEncStr);
    }
References c, TemplateContextImpl::encoding(), QCString::isEmpty(), m_encExpr, TemplateNodeCreator< TemplateNodeEncoding >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeEncoding >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::setEncoding(), and TemplateContextImpl::setLocation().
Member Data Documentation
m_encExpr
ExprAstPtr TemplateNodeEncoding::m_encExpr [private]
Definition at line 4655 of file template.cpp.
Referenced by render(), and TemplateNodeEncoding().
m_nodes
TemplateNodeList TemplateNodeEncoding::m_nodes [private]
Definition at line 4656 of file template.cpp.
Referenced by render(), and TemplateNodeEncoding().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp