NamespaceListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
NamespaceListContext ()
virtual ~NamespaceListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
NamespaceListContext ()
virtual ~NamespaceListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc ()
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 607 of file context.h.
Constructor & Destructor Documentation
NamespaceListContext() [1/2]
NamespaceListContext::NamespaceListContext ()
Definition at line 6227 of file context.cpp.
                                           : p(std::make_unique<Private>())
{
  p->addNamespaces(*Doxygen::namespaceLinkedMap);
}
References Doxygen::namespaceLinkedMap, and p.
 NamespaceListContext() [1/2]
NamespaceListContext::~NamespaceListContext () [virtual]
Definition at line 6232 of file context.cpp.
{
}
NamespaceListContext() [2/2]
NamespaceListContext::NamespaceListContext ()
 NamespaceListContext() [2/2]
virtual NamespaceListContext::~NamespaceListContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr NamespaceListContext::alloc () [inline], [static]
Definition at line 610 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<NamespaceListContext>()); }
Referenced by generateOutputViaTemplate().
alloc() [2/2]
static TemplateListIntfPtr NamespaceListContext::alloc () [inline], [static]
Definition at line 610 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<NamespaceListContext>()); }
at() [1/2]
TemplateVariant NamespaceListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 6242 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant NamespaceListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t NamespaceListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 6237 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t NamespaceListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr NamespaceListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 6247 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr NamespaceListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > NamespaceListContext::p [private]
Definition at line 623 of file context.h.
Referenced by at(), count(), createIterator(), and NamespaceListContext().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp