FilterRelative Class Reference
The implementation of the `relative` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `relative` filter.
Definition at line 1219 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterRelative::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1222 of file template.cpp.
    {
      if (v.isValid() && v.isString() && v.toString().startsWith(".."))
      {
        return TRUE;
      }
      else
      {
        return FALSE;
      }
    }
References FALSE, TemplateVariant::isString(), TemplateVariant::isValid(), QCString::startsWith(), TemplateVariant::toString(), and TRUE.
apply() [2/2]
static TemplateVariant FilterRelative::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1222 of file template.cpp.
    {
      if (v.isValid() && v.isString() && v.toString().startsWith(".."))
      {
        return TRUE;
      }
      else
      {
        return FALSE;
      }
    }
References FALSE, TemplateVariant::isString(), TemplateVariant::isValid(), QCString::startsWith(), TemplateVariant::toString(), and TRUE.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp