ghc::filesystem::directory_entry Class Reference
#include <filesystem.hpp>
Public Member Functions
directory_entry () noexcept=default
directory_entry (const directory_entry &)=default
directory_entry (directory_entry &&) noexcept=default
directory_entry (const path &p, std::error_code &ec)
~directory_entry ()
directory_entry & operator= (const directory_entry &)=default
directory_entry & operator= (directory_entry &&) noexcept=default
void assign (const path &p, std::error_code &ec)
void replace_filename (const path &p, std::error_code &ec)
void refresh (std::error_code &ec) noexcept
const filesystem::path & path () const noexcept
operator const filesystem::path & () const noexcept
bool exists (std::error_code &ec) const noexcept
bool is_block_file (std::error_code &ec) const noexcept
bool is_character_file (std::error_code &ec) const noexcept
bool is_directory (std::error_code &ec) const noexcept
bool is_fifo (std::error_code &ec) const noexcept
bool is_other (std::error_code &ec) const noexcept
bool is_regular_file (std::error_code &ec) const noexcept
bool is_socket (std::error_code &ec) const noexcept
bool is_symlink (std::error_code &ec) const noexcept
uintmax_t file_size (std::error_code &ec) const noexcept
file_time_type last_write_time (std::error_code &ec) const noexcept
file_status status (std::error_code &ec) const noexcept
file_status symlink_status (std::error_code &ec) const noexcept
uintmax_t hard_link_count (std::error_code &ec) const noexcept
bool operator< (const directory_entry &rhs) const noexcept
bool operator== (const directory_entry &rhs) const noexcept
bool operator!= (const directory_entry &rhs) const noexcept
bool operator<= (const directory_entry &rhs) const noexcept
bool operator> (const directory_entry &rhs) const noexcept
bool operator>= (const directory_entry &rhs) const noexcept
directory_entry () noexcept=default
directory_entry (const directory_entry &)=default
directory_entry (directory_entry &&) noexcept=default
directory_entry (const path &p, std::error_code &ec)
~directory_entry ()
directory_entry & operator= (const directory_entry &)=default
directory_entry & operator= (directory_entry &&) noexcept=default
void assign (const path &p, std::error_code &ec)
void replace_filename (const path &p, std::error_code &ec)
void refresh (std::error_code &ec) noexcept
const filesystem::path & path () const noexcept
operator const filesystem::path & () const noexcept
bool exists (std::error_code &ec) const noexcept
bool is_block_file (std::error_code &ec) const noexcept
bool is_character_file (std::error_code &ec) const noexcept
bool is_directory (std::error_code &ec) const noexcept
bool is_fifo (std::error_code &ec) const noexcept
bool is_other (std::error_code &ec) const noexcept
bool is_regular_file (std::error_code &ec) const noexcept
bool is_socket (std::error_code &ec) const noexcept
bool is_symlink (std::error_code &ec) const noexcept
uintmax_t file_size (std::error_code &ec) const noexcept
file_time_type last_write_time (std::error_code &ec) const noexcept
file_status status (std::error_code &ec) const noexcept
file_status symlink_status (std::error_code &ec) const noexcept
uintmax_t hard_link_count (std::error_code &ec) const noexcept
bool operator< (const directory_entry &rhs) const noexcept
bool operator== (const directory_entry &rhs) const noexcept
bool operator!= (const directory_entry &rhs) const noexcept
bool operator<= (const directory_entry &rhs) const noexcept
bool operator> (const directory_entry &rhs) const noexcept
bool operator>= (const directory_entry &rhs) const noexcept
Private Member Functions
file_type status_file_type (std::error_code &ec) const noexcept
file_type status_file_type (std::error_code &ec) const noexcept
Private Attributes
filesystem::path _path
file_status _status
file_status _symlink_status
uintmax_t _file_size = static_cast<uintmax_t>(-1)
uintmax_t _hard_link_count = static_cast<uintmax_t>(-1)
time_t _last_write_time = 0
Friends
class directory_iterator
Detailed Description
Definition at line 813 of file filesystem.hpp.
Constructor & Destructor Documentation
directory_entry() [1/8]
ghc::filesystem::directory_entry::directory_entry () [default], [noexcept]
directory_entry() [2/8]
ghc::filesystem::directory_entry::directory_entry (const directory_entry &) [default]
directory_entry() [3/8]
ghc::filesystem::directory_entry::directory_entry (directory_entry &&) [default], [noexcept]
directory_entry() [4/8]
GHC_INLINE ghc::filesystem::directory_entry::directory_entry (const path & p, std::error_code & ec)
Definition at line 5093 of file filesystem.hpp.
    : _path(p)
    , _file_size(static_cast<uintmax_t>(-1))
#ifndef GHC_OS_WINDOWS
    , _hard_link_count(static_cast<uintmax_t>(-1))
#endif
    , _last_write_time(0)
{
    refresh(ec);
}
References refresh().
 directory_entry() [1/2]
GHC_INLINE ghc::filesystem::directory_entry::~directory_entry ()
Definition at line 5104 of file filesystem.hpp.
{}
directory_entry() [5/8]
ghc::filesystem::directory_entry::directory_entry () [default], [noexcept]
directory_entry() [6/8]
ghc::filesystem::directory_entry::directory_entry (const directory_entry &) [default]
directory_entry() [7/8]
ghc::filesystem::directory_entry::directory_entry (directory_entry &&) [default], [noexcept]
directory_entry() [8/8]
ghc::filesystem::directory_entry::directory_entry (const path & p, std::error_code & ec)
 directory_entry() [2/2]
ghc::filesystem::directory_entry::~directory_entry ()
Member Function Documentation
assign() [1/2]
GHC_INLINE void ghc::filesystem::directory_entry::assign (const path & p, std::error_code & ec)
Definition at line 5119 of file filesystem.hpp.
{
    _path = p;
    refresh(ec);
}
References _path, p, and refresh().
assign() [2/2]
void ghc::filesystem::directory_entry::assign (const path & p, std::error_code & ec)
exists() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::exists (std::error_code & ec) const [noexcept]
Definition at line 5193 of file filesystem.hpp.
{
    return status_file_type(ec) != file_type::not_found;
}
References ghc::filesystem::not_found.
exists() [2/2]
bool ghc::filesystem::directory_entry::exists (std::error_code & ec) const [noexcept]
file_size() [1/2]
GHC_INLINE uintmax_t ghc::filesystem::directory_entry::file_size (std::error_code & ec) const [noexcept]
Definition at line 5310 of file filesystem.hpp.
{
    if (_file_size != static_cast<uintmax_t>(-1)) {
        ec.clear();
        return _file_size;
    }
    return filesystem::file_size(path(), ec);
}
References ghc::filesystem::file_size().
file_size() [2/2]
uintmax_t ghc::filesystem::directory_entry::file_size (std::error_code & ec) const [noexcept]
hard_link_count() [1/2]
GHC_INLINE uintmax_t ghc::filesystem::directory_entry::hard_link_count (std::error_code & ec) const [noexcept]
Definition at line 5332 of file filesystem.hpp.
{
#ifndef GHC_OS_WINDOWS
    if (_hard_link_count != static_cast<uintmax_t>(-1)) {
        ec.clear();
        return _hard_link_count;
    }
#endif
    return filesystem::hard_link_count(path(), ec);
}
References ghc::filesystem::hard_link_count().
hard_link_count() [2/2]
uintmax_t ghc::filesystem::directory_entry::hard_link_count (std::error_code & ec) const [noexcept]
is_block_file() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::is_block_file (std::error_code & ec) const [noexcept]
Definition at line 5204 of file filesystem.hpp.
{
    return status_file_type(ec) == file_type::block;
}
References ghc::filesystem::block.
is_block_file() [2/2]
bool ghc::filesystem::directory_entry::is_block_file (std::error_code & ec) const [noexcept]
is_character_file() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::is_character_file (std::error_code & ec) const [noexcept]
Definition at line 5216 of file filesystem.hpp.
{
    return status_file_type(ec) == file_type::character;
}
References ghc::filesystem::character.
is_character_file() [2/2]
bool ghc::filesystem::directory_entry::is_character_file (std::error_code & ec) const [noexcept]
is_directory() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::is_directory (std::error_code & ec) const [noexcept]
Definition at line 5228 of file filesystem.hpp.
{
    return status_file_type(ec) == file_type::directory;
}
References ghc::filesystem::directory.
is_directory() [2/2]
bool ghc::filesystem::directory_entry::is_directory (std::error_code & ec) const [noexcept]
is_fifo() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::is_fifo (std::error_code & ec) const [noexcept]
Definition at line 5240 of file filesystem.hpp.
{
    return status_file_type(ec) == file_type::fifo;
}
References ghc::filesystem::fifo.
is_fifo() [2/2]
bool ghc::filesystem::directory_entry::is_fifo (std::error_code & ec) const [noexcept]
is_other() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::is_other (std::error_code & ec) const [noexcept]
Definition at line 5253 of file filesystem.hpp.
{
    auto ft = status_file_type(ec);
    bool other = ft != file_type::none && ft != file_type::not_found && ft != file_type::regular && ft != file_type::directory && !is_symlink(ec);
    return !ec && other;
}
References ghc::filesystem::directory, ghc::filesystem::is_symlink(), ghc::filesystem::none, ghc::filesystem::not_found, and ghc::filesystem::regular.
is_other() [2/2]
bool ghc::filesystem::directory_entry::is_other (std::error_code & ec) const [noexcept]
is_regular_file() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::is_regular_file (std::error_code & ec) const [noexcept]
Definition at line 5267 of file filesystem.hpp.
{
    return status_file_type(ec) == file_type::regular;
}
References ghc::filesystem::regular.
is_regular_file() [2/2]
bool ghc::filesystem::directory_entry::is_regular_file (std::error_code & ec) const [noexcept]
is_socket() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::is_socket (std::error_code & ec) const [noexcept]
Definition at line 5279 of file filesystem.hpp.
{
    return status_file_type(ec) == file_type::socket;
}
References ghc::filesystem::socket.
is_socket() [2/2]
bool ghc::filesystem::directory_entry::is_socket (std::error_code & ec) const [noexcept]
is_symlink() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::is_symlink (std::error_code & ec) const [noexcept]
Definition at line 5291 of file filesystem.hpp.
{
    if(_symlink_status.type() != file_type::none) {
        ec.clear();
        return _symlink_status.type() == file_type::symlink;
    }
    return filesystem::is_symlink(symlink_status(ec));
}
References ghc::filesystem::is_symlink(), ghc::filesystem::none, ghc::filesystem::symlink, and ghc::filesystem::symlink_status().
Referenced by ghc::filesystem::recursive_directory_iterator::increment().
is_symlink() [2/2]
bool ghc::filesystem::directory_entry::is_symlink (std::error_code & ec) const [noexcept]
last_write_time() [1/2]
GHC_INLINE file_time_type ghc::filesystem::directory_entry::last_write_time (std::error_code & ec) const [noexcept]
Definition at line 5354 of file filesystem.hpp.
{
    if (_last_write_time != 0) {
        ec.clear();
        return std::chrono::system_clock::from_time_t(_last_write_time);
    }
    return filesystem::last_write_time(path(), ec);
}
References ghc::filesystem::last_write_time().
last_write_time() [2/2]
file_time_type ghc::filesystem::directory_entry::last_write_time (std::error_code & ec) const [noexcept]
operator const filesystem::path &() [1/2]
GHC_INLINE ghc::filesystem::directory_entry::operator const filesystem::path & () const [noexcept]
Definition at line 5165 of file filesystem.hpp.
{
    return _path;
}
operator const filesystem::path &() [2/2]
ghc::filesystem::directory_entry::operator const filesystem::path & () const [noexcept]
operator!=() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::operator!= (const directory_entry & rhs) const [noexcept]
Definition at line 5418 of file filesystem.hpp.
{
    return _path != rhs._path;
}
operator!=() [2/2]
bool ghc::filesystem::directory_entry::operator!= (const directory_entry & rhs) const [noexcept]
operator<() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::operator< (const directory_entry & rhs) const [noexcept]
Definition at line 5408 of file filesystem.hpp.
{
    return _path < rhs._path;
}
operator<() [2/2]
bool ghc::filesystem::directory_entry::operator< (const directory_entry & rhs) const [noexcept]
operator<=() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::operator<= (const directory_entry & rhs) const [noexcept]
Definition at line 5423 of file filesystem.hpp.
{
    return _path <= rhs._path;
}
operator<=() [2/2]
bool ghc::filesystem::directory_entry::operator<= (const directory_entry & rhs) const [noexcept]
operator=() [1/4]
directory_entry & ghc::filesystem::directory_entry::operator= (const directory_entry &) [default]
operator=() [2/4]
directory_entry & ghc::filesystem::directory_entry::operator= (const directory_entry &) [default]
operator=() [3/4]
directory_entry & ghc::filesystem::directory_entry::operator= (directory_entry &&) [default], [noexcept]
operator=() [4/4]
directory_entry & ghc::filesystem::directory_entry::operator= (directory_entry &&) [default], [noexcept]
operator==() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::operator== (const directory_entry & rhs) const [noexcept]
Definition at line 5413 of file filesystem.hpp.
{
    return _path == rhs._path;
}
operator==() [2/2]
bool ghc::filesystem::directory_entry::operator== (const directory_entry & rhs) const [noexcept]
operator>() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::operator> (const directory_entry & rhs) const [noexcept]
Definition at line 5428 of file filesystem.hpp.
{
    return _path > rhs._path;
}
operator>() [2/2]
bool ghc::filesystem::directory_entry::operator> (const directory_entry & rhs) const [noexcept]
operator>=() [1/2]
GHC_INLINE bool ghc::filesystem::directory_entry::operator>= (const directory_entry & rhs) const [noexcept]
Definition at line 5433 of file filesystem.hpp.
{
    return _path >= rhs._path;
}
operator>=() [2/2]
bool ghc::filesystem::directory_entry::operator>= (const directory_entry & rhs) const [noexcept]
path() [1/2]
GHC_INLINE const filesystem::path & ghc::filesystem::directory_entry::path () const [noexcept]
Definition at line 5160 of file filesystem.hpp.
{
    return _path;
}
References _path.
path() [2/2]
const filesystem::path & ghc::filesystem::directory_entry::path () const [noexcept]
refresh() [1/2]
GHC_INLINE void ghc::filesystem::directory_entry::refresh (std::error_code & ec) [noexcept]
Definition at line 5150 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    _status = detail::status_ex(_path, ec, &_symlink_status, &_file_size, nullptr, &_last_write_time);
#else
    _status = detail::status_ex(_path, ec, &_symlink_status, &_file_size, &_hard_link_count, &_last_write_time);
#endif
}
References ghc::filesystem::detail::status_ex().
Referenced by assign(), directory_entry(), and replace_filename().
refresh() [2/2]
void ghc::filesystem::directory_entry::refresh (std::error_code & ec) [noexcept]
replace_filename() [1/2]
GHC_INLINE void ghc::filesystem::directory_entry::replace_filename (const path & p, std::error_code & ec)
Definition at line 5133 of file filesystem.hpp.
{
    _path.replace_filename(p);
    refresh(ec);
}
References _path, p, refresh(), and ghc::filesystem::path::replace_filename().
replace_filename() [2/2]
void ghc::filesystem::directory_entry::replace_filename (const path & p, std::error_code & ec)
status() [1/2]
GHC_INLINE file_status ghc::filesystem::directory_entry::status (std::error_code & ec) const [noexcept]
Definition at line 5373 of file filesystem.hpp.
{
    if (_status.type() != file_type::none && _status.permissions() != perms::unknown) {
        ec.clear();
        return _status;
    }
    return filesystem::status(path(), ec);
}
References ghc::filesystem::none, ghc::filesystem::status(), and ghc::filesystem::unknown.
Referenced by translator.Transl::__collectClassInfo(), translator.Transl::__init__(), translator.Transl::processing(), and translator.Transl::report().
status() [2/2]
file_status ghc::filesystem::directory_entry::status (std::error_code & ec) const [noexcept]
Referenced by translator.Transl::__collectClassInfo(), translator.Transl::__init__(), translator.Transl::processing(), and translator.Transl::report().
status_file_type() [1/2]
GHC_INLINE file_type ghc::filesystem::directory_entry::status_file_type (std::error_code & ec) const [private], [noexcept]
Definition at line 5177 of file filesystem.hpp.
{
    if(_status.type() != file_type::none) {
        ec.clear();
        return _status.type();
    }
    return filesystem::status(path(), ec).type();
}
References ghc::filesystem::none, ghc::filesystem::status(), and ghc::filesystem::file_status::type().
status_file_type() [2/2]
file_type ghc::filesystem::directory_entry::status_file_type (std::error_code & ec) const [private], [noexcept]
symlink_status() [1/2]
GHC_INLINE file_status ghc::filesystem::directory_entry::symlink_status (std::error_code & ec) const [noexcept]
Definition at line 5392 of file filesystem.hpp.
{
    if (_symlink_status.type() != file_type::none && _symlink_status.permissions() != perms::unknown) {
        ec.clear();
        return _symlink_status;
    }
    return filesystem::symlink_status(path(), ec);
}
References ghc::filesystem::none, ghc::filesystem::symlink_status(), and ghc::filesystem::unknown.
symlink_status() [2/2]
file_status ghc::filesystem::directory_entry::symlink_status (std::error_code & ec) const [noexcept]
Friends And Related Function Documentation
directory_iterator
directory_iterator [friend]
Definition at line 890 of file filesystem.hpp.
Member Data Documentation
_file_size
uintmax_t ghc::filesystem::directory_entry::_file_size = static_cast<uintmax_t>(-1) [private]
Definition at line 898 of file filesystem.hpp.
Referenced by ghc::filesystem::directory_iterator::impl::copyToDirEntry().
_hard_link_count
uintmax_t ghc::filesystem::directory_entry::_hard_link_count = static_cast<uintmax_t>(-1) [private]
Definition at line 900 of file filesystem.hpp.
Referenced by ghc::filesystem::directory_iterator::impl::copyToDirEntry().
_last_write_time
time_t ghc::filesystem::directory_entry::_last_write_time = 0 [private]
Definition at line 902 of file filesystem.hpp.
Referenced by ghc::filesystem::directory_iterator::impl::copyToDirEntry().
_path
filesystem::path ghc::filesystem::directory_entry::_path [private]
Definition at line 895 of file filesystem.hpp.
Referenced by assign(), ghc::filesystem::directory_iterator::impl::increment(), path(), and replace_filename().
_status
file_status ghc::filesystem::directory_entry::_status [private]
Definition at line 896 of file filesystem.hpp.
Referenced by ghc::filesystem::directory_iterator::impl::copyToDirEntry().
_symlink_status
file_status ghc::filesystem::directory_entry::_symlink_status [private]
Definition at line 897 of file filesystem.hpp.
Referenced by ghc::filesystem::directory_iterator::impl::copyToDirEntry().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/filesystem/filesystem.hpp
doxygen/filesystem/filesystem.hpp