TextGeneratorHtml Class Reference
Public Member Functions
TextGeneratorHtml (TextStream &ts, const QCString &relPath)
void writeString (const QCString &s, bool keepSpaces) const
void writeBreak (int indent) const
void writeLink (const QCString &ref, const QCString &f, const QCString &anchor, const QCString &name) const
TextGeneratorHtml (TextStream &ts, const QCString &relPath)
void writeString (const QCString &s, bool keepSpaces) const
void writeBreak (int indent) const
void writeLink (const QCString &ref, const QCString &f, const QCString &anchor, const QCString &name) const
Private Attributes
TextStream & m_ts
QCString m_relPath
Detailed Description
Definition at line 3391 of file context.cpp.
Constructor & Destructor Documentation
TextGeneratorHtml() [1/2]
TextGeneratorHtml::TextGeneratorHtml (TextStream & ts, const QCString & relPath) [inline]
Definition at line 3394 of file context.cpp.
       : m_ts(ts), m_relPath(relPath) {}
TextGeneratorHtml() [2/2]
TextGeneratorHtml::TextGeneratorHtml (TextStream & ts, const QCString & relPath) [inline]
Definition at line 3394 of file context.cpp.
       : m_ts(ts), m_relPath(relPath) {}
Member Function Documentation
writeBreak() [1/2]
void TextGeneratorHtml::writeBreak (int indent) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 3436 of file context.cpp.
    {
      m_ts << "<br />";
      for (int i=0;i<indent;i++)
      {
        m_ts << "&#160;";
      }
    }
References m_ts.
writeBreak() [2/2]
void TextGeneratorHtml::writeBreak (int indent) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 3436 of file context.cpp.
    {
      m_ts << "<br />";
      for (int i=0;i<indent;i++)
      {
        m_ts << "&#160;";
      }
    }
writeLink() [1/2]
void TextGeneratorHtml::writeLink (const QCString & ref, const QCString & f, const QCString & anchor, const QCString & name) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 3445 of file context.cpp.
    {
      if (!ref.isEmpty())
      {
        m_ts << "<a class=\"elRef\" ";
        m_ts << externalLinkTarget();
      }
      else
      {
        m_ts << "<a class=\"el\" ";
      }
      m_ts << "href=\"";
      m_ts << externalRef(m_relPath,ref,TRUE);
      if (!f.isEmpty()) m_ts << addHtmlExtensionIfMissing(f);
      if (!anchor.isEmpty()) m_ts << "#" << anchor;
      m_ts << "\">";
      m_ts << convertToHtml(name);
      m_ts << "</a>";
    }
References addHtmlExtensionIfMissing(), convertToHtml(), externalLinkTarget(), externalRef(), f, QCString::isEmpty(), m_relPath, m_ts, setup::name, and TRUE.
writeLink() [2/2]
void TextGeneratorHtml::writeLink (const QCString & ref, const QCString & f, const QCString & anchor, const QCString & name) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 3445 of file context.cpp.
    {
      if (!ref.isEmpty())
      {
        m_ts << "<a class=\"elRef\" ";
        m_ts << externalLinkTarget();
      }
      else
      {
        m_ts << "<a class=\"el\" ";
      }
      m_ts << "href=\"";
      m_ts << externalRef(m_relPath,ref,TRUE);
      if (!f.isEmpty()) m_ts << addHtmlExtensionIfMissing(f);
      if (!anchor.isEmpty()) m_ts << "#" << anchor;
      m_ts << "\">";
      m_ts << convertToHtml(name);
      m_ts << "</a>";
    }
References addHtmlExtensionIfMissing(), convertToHtml(), externalLinkTarget(), externalRef(), f, QCString::isEmpty(), setup::name, and TRUE.
writeString() [1/2]
void TextGeneratorHtml::writeString (const QCString & s, bool keepSpaces) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 3396 of file context.cpp.
    {
      static const char *hex="0123456789ABCDEF";
      if (s.isEmpty()) return;
      if (keepSpaces)
      {
        const char *p=s.data();
        char c;
        while ((c=*p++))
        {
          switch(c)
          {
            case '<': m_ts << "&lt;"; break;
            case '>': m_ts << "&gt;"; break;
            case '\'': m_ts << "&#39;"; break;
            case '"': m_ts << "&quot;"; break;
            case '&': m_ts << "&amp;"; break;
            case ' ': m_ts << "&#160;"; break;
            default:
              {
                uchar uc = static_cast<uchar>(c);
                if (uc<32 && !isspace(c)) // non-printable control characters
                {
                  m_ts << "&#x24" << hex[uc>>4] << hex[uc&0xF] << ";";
                }
                else
                {
                  m_ts << c;
                }
              }
              break;
          }
        }
      }
      else
      {
        m_ts << convertToHtml(s);
      }
    }
References c, convertToHtml(), gdFont::data, hex, reg::isspace(), m_ts, p, and s.
writeString() [2/2]
void TextGeneratorHtml::writeString (const QCString & s, bool keepSpaces) const [inline], [virtual]
Implements TextGeneratorIntf.
Definition at line 3396 of file context.cpp.
    {
      static const char *hex="0123456789ABCDEF";
      if (s.isEmpty()) return;
      if (keepSpaces)
      {
        const char *p=s.data();
        char c;
        while ((c=*p++))
        {
          switch(c)
          {
            case '<': m_ts << "&lt;"; break;
            case '>': m_ts << "&gt;"; break;
            case '\'': m_ts << "&#39;"; break;
            case '"': m_ts << "&quot;"; break;
            case '&': m_ts << "&amp;"; break;
            case ' ': m_ts << "&#160;"; break;
            default:
              {
                uchar uc = static_cast<uchar>(c);
                if (uc<32 && !isspace(c)) // non-printable control characters
                {
                  m_ts << "&#x24" << hex[uc>>4] << hex[uc&0xF] << ";";
                }
                else
                {
                  m_ts << c;
                }
              }
              break;
          }
        }
      }
      else
      {
        m_ts << convertToHtml(s);
      }
    }
References c, convertToHtml(), gdFont::data, hex, reg::isspace(), PageContext::p, and s.
Member Data Documentation
m_relPath
QCString TextGeneratorHtml::m_relPath [private]
Definition at line 3469 of file context.cpp.
Referenced by writeLink().
m_ts
TextStream & TextGeneratorHtml::m_ts [private]
Definition at line 3468 of file context.cpp.
Referenced by writeBreak(), writeLink(), and writeString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp