MemberContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (const MemberDef *md)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant isStatic () const
TemplateVariant isObjCMethod () const
TemplateVariant isObjCProperty () const
TemplateVariant isCSharpProperty () const
TemplateVariant isImplementation () const
TemplateVariant isSignal () const
TemplateVariant isSlot () const
TemplateVariant isTypedef () const
TemplateVariant isFunction () const
TemplateVariant isFunctionPtr () const
TemplateVariant isFriend () const
TemplateVariant isForeign () const
TemplateVariant isEvent () const
TemplateVariant isInline () const
TemplateVariant isExplicit () const
TemplateVariant isMutable () const
TemplateVariant isGettable () const
TemplateVariant isPrivateGettable () const
TemplateVariant isProtectedGettable () const
TemplateVariant isSettable () const
TemplateVariant isPrivateSettable () const
TemplateVariant isProtectedSettable () const
TemplateVariant isReadable () const
TemplateVariant isWritable () const
TemplateVariant isAddable () const
TemplateVariant isRemovable () const
TemplateVariant isRaisable () const
TemplateVariant isFinal () const
TemplateVariant isAbstract () const
TemplateVariant isOverride () const
TemplateVariant isInitonly () const
TemplateVariant isOptional () const
TemplateVariant isRequired () const
TemplateVariant isNonAtomic () const
TemplateVariant isCopy () const
TemplateVariant isAssign () const
TemplateVariant isRetain () const
TemplateVariant isWeak () const
TemplateVariant isStrong () const
TemplateVariant isEnumStruct () const
TemplateVariant isUnretained () const
TemplateVariant isNew () const
TemplateVariant isSealed () const
TemplateVariant isExternal () const
TemplateVariant isTypeAlias () const
TemplateVariant isDefault () const
TemplateVariant isDelete () const
TemplateVariant isNoExcept () const
TemplateVariant isAttribute () const
TemplateVariant isUNOProperty () const
TemplateVariant isReadonly () const
TemplateVariant isBound () const
TemplateVariant isConstrained () const
TemplateVariant isTransient () const
TemplateVariant isMaybeVoid () const
TemplateVariant isMaybeDefault () const
TemplateVariant isMaybeAmbiguous () const
TemplateVariant isPublished () const
TemplateVariant isTemplateSpecialization () const
TemplateVariant isProperty () const
TemplateVariant isEnumValue () const
TemplateVariant isVariable () const
TemplateVariant isEnumeration () const
TemplateVariant hasDetails () const
TemplateVariant isDefine () const
TemplateVariant isAnonymous () const
TemplateVariant isRelated () const
TemplateVariant enumBaseType () const
TemplateVariant hasOneLineInitializer () const
TemplateVariant hasMultiLineInitializer () const
TemplateVariant extraTypeChars () const
TemplateVariant type () const
TemplateVariant fieldType () const
TemplateVariant declType () const
TemplateVariant declArgs () const
TemplateVariant exception () const
TemplateVariant bitfields () const
TemplateVariant initializer () const
TemplateVariant initializerAsCode () const
TemplateVariant anonymousType () const
TemplateVariant anonymousMember () const
TemplateVariant enumValues () const
TemplateVariant templateArgs () const
TemplateVariant templateAlias () const
TemplateVariant propertyAttrs () const
TemplateVariant eventAttrs () const
TemplateVariant getClass () const
TemplateVariant category () const
TemplateVariant categoryRelation () const
TemplateVariant getFile () const
TemplateVariant getNamespace () const
TemplateVariant definition () const
TemplateVariant parameters () const
TemplateVariant hasParameters () const
TemplateVariant hasConstQualifier () const
TemplateVariant hasVolatileQualifier () const
TemplateVariant hasRefQualifierLValue () const
TemplateVariant hasRefQualifierRValue () const
TemplateVariant trailingReturnType () const
TemplateVariant templateDecls () const
TemplateVariant labels () const
TemplateVariant paramDocs () const
TemplateVariant implements () const
TemplateVariant reimplements () const
TemplateVariant implementedBy () const
TemplateVariant reimplementedBy () const
TemplateVariant examples () const
TemplateVariant typeConstraints () const
TemplateVariant sourceRefs () const
TemplateVariant sourceRefBys () const
TemplateVariant sourceCode () const
DotCallGraphPtr getCallGraph () const
DotCallGraphPtr getCallerGraph () const
TemplateVariant hasSources () const
TemplateVariant hasReferencedByRelation () const
TemplateVariant hasReferencesRelation () const
const ArgumentList & getDefArgList () const
TemplateVariant functionQualifier () const
TemplateVariant hasCallGraph () const
TemplateVariant callGraph () const
TemplateVariant referencedByRelation () const
TemplateVariant hasCallerGraph () const
TemplateVariant callerGraph () const
TemplateVariant referencesRelation () const
TemplateVariant handleDetailsVisibleFor (const TemplateVariantList &args) const
TemplateVariant detailsVisibleFor () const
TemplateVariant handleNameWithContextFor (const TemplateVariantList &args) const
TemplateVariant nameWithContextFor () const
Private (const MemberDef *md)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant isStatic () const
TemplateVariant isObjCMethod () const
TemplateVariant isObjCProperty () const
TemplateVariant isCSharpProperty () const
TemplateVariant isImplementation () const
TemplateVariant isSignal () const
TemplateVariant isSlot () const
TemplateVariant isTypedef () const
TemplateVariant isFunction () const
TemplateVariant isFunctionPtr () const
TemplateVariant isFriend () const
TemplateVariant isForeign () const
TemplateVariant isEvent () const
TemplateVariant isInline () const
TemplateVariant isExplicit () const
TemplateVariant isMutable () const
TemplateVariant isGettable () const
TemplateVariant isPrivateGettable () const
TemplateVariant isProtectedGettable () const
TemplateVariant isSettable () const
TemplateVariant isPrivateSettable () const
TemplateVariant isProtectedSettable () const
TemplateVariant isReadable () const
TemplateVariant isWritable () const
TemplateVariant isAddable () const
TemplateVariant isRemovable () const
TemplateVariant isRaisable () const
TemplateVariant isFinal () const
TemplateVariant isAbstract () const
TemplateVariant isOverride () const
TemplateVariant isInitonly () const
TemplateVariant isOptional () const
TemplateVariant isRequired () const
TemplateVariant isNonAtomic () const
TemplateVariant isCopy () const
TemplateVariant isAssign () const
TemplateVariant isRetain () const
TemplateVariant isWeak () const
TemplateVariant isStrong () const
TemplateVariant isEnumStruct () const
TemplateVariant isUnretained () const
TemplateVariant isNew () const
TemplateVariant isSealed () const
TemplateVariant isExternal () const
TemplateVariant isTypeAlias () const
TemplateVariant isDefault () const
TemplateVariant isDelete () const
TemplateVariant isNoExcept () const
TemplateVariant isAttribute () const
TemplateVariant isUNOProperty () const
TemplateVariant isReadonly () const
TemplateVariant isBound () const
TemplateVariant isConstrained () const
TemplateVariant isTransient () const
TemplateVariant isMaybeVoid () const
TemplateVariant isMaybeDefault () const
TemplateVariant isMaybeAmbiguous () const
TemplateVariant isPublished () const
TemplateVariant isTemplateSpecialization () const
TemplateVariant isProperty () const
TemplateVariant isEnumValue () const
TemplateVariant isVariable () const
TemplateVariant isEnumeration () const
TemplateVariant hasDetails () const
TemplateVariant isDefine () const
TemplateVariant isAnonymous () const
TemplateVariant isRelated () const
TemplateVariant enumBaseType () const
TemplateVariant hasOneLineInitializer () const
TemplateVariant hasMultiLineInitializer () const
TemplateVariant extraTypeChars () const
TemplateVariant type () const
TemplateVariant fieldType () const
TemplateVariant declType () const
TemplateVariant declArgs () const
TemplateVariant exception () const
TemplateVariant bitfields () const
TemplateVariant initializer () const
TemplateVariant initializerAsCode () const
TemplateVariant anonymousType () const
TemplateVariant anonymousMember () const
TemplateVariant enumValues () const
TemplateVariant templateArgs () const
TemplateVariant templateAlias () const
TemplateVariant propertyAttrs () const
TemplateVariant eventAttrs () const
TemplateVariant getClass () const
TemplateVariant category () const
TemplateVariant categoryRelation () const
TemplateVariant getFile () const
TemplateVariant getNamespace () const
TemplateVariant definition () const
TemplateVariant parameters () const
TemplateVariant hasParameters () const
TemplateVariant hasConstQualifier () const
TemplateVariant hasVolatileQualifier () const
TemplateVariant hasRefQualifierLValue () const
TemplateVariant hasRefQualifierRValue () const
TemplateVariant trailingReturnType () const
TemplateVariant templateDecls () const
TemplateVariant labels () const
TemplateVariant paramDocs () const
TemplateVariant implements () const
TemplateVariant reimplements () const
TemplateVariant implementedBy () const
TemplateVariant reimplementedBy () const
TemplateVariant examples () const
TemplateVariant typeConstraints () const
TemplateVariant sourceRefs () const
TemplateVariant sourceRefBys () const
TemplateVariant sourceCode () const
DotCallGraphPtr getCallGraph () const
DotCallGraphPtr getCallerGraph () const
TemplateVariant hasSources () const
TemplateVariant hasReferencedByRelation () const
TemplateVariant hasReferencesRelation () const
const ArgumentList & getDefArgList () const
TemplateVariant functionQualifier () const
TemplateVariant hasCallGraph () const
TemplateVariant callGraph () const
TemplateVariant referencedByRelation () const
TemplateVariant hasCallerGraph () const
TemplateVariant callerGraph () const
TemplateVariant referencesRelation () const
TemplateVariant handleDetailsVisibleFor (const TemplateVariantList &args) const
TemplateVariant detailsVisibleFor () const
TemplateVariant handleNameWithContextFor (const TemplateVariantList &args) const
TemplateVariant nameWithContextFor () const
Private Member Functions
TemplateVariant createTemplateArgs () const
TemplateVariant createTemplateAlias () const
TemplateVariant createPropertyAttrs () const
TemplateVariant createEventAttrs () const
TemplateVariant createParameters () const
TemplateVariant createEnumValues () const
TemplateVariant createFileDef () const
TemplateVariant createNamespaceDef () const
TemplateVariant createClassDef () const
TemplateVariant createCategory () const
TemplateVariant createCategoryRelation () const
TemplateVariant createDefinition () const
TemplateVariant createTrailingReturnType () const
TemplateVariant createTemplateDecls () const
TemplateVariant createAnonymousType () const
TemplateVariant createParamDocs () const
TemplateVariant createImplements () const
TemplateVariant createReimplements () const
TemplateVariant createImplementedBy () const
TemplateVariant createReimplementedBy () const
TemplateVariant createExamples () const
TemplateVariant createSourceRefs () const
TemplateVariant createSourceRefBys () const
DotCallGraphPtr createCallGraph () const
DotCallGraphPtr createCallerGraph () const
TemplateVariant createAnonymousMember () const
TemplateVariant createLabels () const
TemplateVariant createTypeConstraints () const
TemplateVariant createInitializerAsCode () const
TemplateVariant createInitializer () const
TemplateVariant createSourceCode () const
TemplateVariant createDeclType () const
TemplateVariant createDeclArgs () const
TemplateVariant createFieldType () const
TemplateVariant createException () const
TemplateVariant createBitfields () const
TemplateVariant createTemplateArgs () const
TemplateVariant createTemplateAlias () const
TemplateVariant createPropertyAttrs () const
TemplateVariant createEventAttrs () const
TemplateVariant createParameters () const
TemplateVariant createEnumValues () const
TemplateVariant createFileDef () const
TemplateVariant createNamespaceDef () const
TemplateVariant createClassDef () const
TemplateVariant createCategory () const
TemplateVariant createCategoryRelation () const
TemplateVariant createDefinition () const
TemplateVariant createTrailingReturnType () const
TemplateVariant createTemplateDecls () const
TemplateVariant createAnonymousType () const
TemplateVariant createParamDocs () const
TemplateVariant createImplements () const
TemplateVariant createReimplements () const
TemplateVariant createImplementedBy () const
TemplateVariant createReimplementedBy () const
TemplateVariant createExamples () const
TemplateVariant createSourceRefs () const
TemplateVariant createSourceRefBys () const
DotCallGraphPtr createCallGraph () const
DotCallGraphPtr createCallerGraph () const
TemplateVariant createAnonymousMember () const
TemplateVariant createLabels () const
TemplateVariant createTypeConstraints () const
TemplateVariant createInitializerAsCode () const
TemplateVariant createInitializer () const
TemplateVariant createSourceCode () const
TemplateVariant createDeclType () const
TemplateVariant createDeclArgs () const
TemplateVariant createFieldType () const
TemplateVariant createException () const
TemplateVariant createBitfields () const
Private Attributes
const MemberDef * m_memberDef
Cachable m_cachable
Static Private Attributes
static const PropertyMap< MemberContext::Private > s_inst
Additional Inherited Members
Detailed Description
Definition at line 3574 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
MemberContext::Private::Private (const MemberDef * md) [inline]
Definition at line 3577 of file context.cpp.
                                 : DefinitionContext<MemberContext::Private>(md) , m_memberDef(md)
    {
    }
Private() [2/2]
MemberContext::Private::Private (const MemberDef * md) [inline]
Definition at line 3577 of file context.cpp.
                                 : DefinitionContext<MemberContext::Private>(md) , m_memberDef(md)
    {
    }
Member Function Documentation
anonymousMember() [1/2]
TemplateVariant MemberContext::Private::anonymousMember () const [inline]
Definition at line 3666 of file context.cpp.
{ return m_cachable.anonymousMember.get(this); }
References MemberContext::Private::Cachable::anonymousMember, and m_cachable.
anonymousMember() [2/2]
TemplateVariant MemberContext::Private::anonymousMember () const [inline]
Definition at line 3666 of file context.cpp.
{ return m_cachable.anonymousMember.get(this); }
anonymousType() [1/2]
TemplateVariant MemberContext::Private::anonymousType () const [inline]
Definition at line 3665 of file context.cpp.
{ return m_cachable.anonymousType.get(this); }
References MemberContext::Private::Cachable::anonymousType, and m_cachable.
anonymousType() [2/2]
TemplateVariant MemberContext::Private::anonymousType () const [inline]
Definition at line 3665 of file context.cpp.
{ return m_cachable.anonymousType.get(this); }
bitfields() [1/2]
TemplateVariant MemberContext::Private::bitfields () const [inline]
Definition at line 3662 of file context.cpp.
{ return m_cachable.bitfields.get(this); }
References MemberContext::Private::Cachable::bitfields, and m_cachable.
bitfields() [2/2]
TemplateVariant MemberContext::Private::bitfields () const [inline]
Definition at line 3662 of file context.cpp.
{ return m_cachable.bitfields.get(this); }
callerGraph() [1/2]
TemplateVariant MemberContext::Private::callerGraph () const [inline]
Definition at line 3793 of file context.cpp.
    {
      if (hasCallerGraph().toBool())
      {
        DotCallGraphPtr cg = getCallerGraph();
        TextStream t;
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              cg->writeGraph(t,GOF_BITMAP,EOF_Html,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_memberDef->getOutputFileBase()),
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
          case ContextOutputFormat_Latex:
            {
              cg->writeGraph(t,GOF_EPS,EOF_LaTeX,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+m_memberDef->getOutputFileBase()+".tex",
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
        return TemplateVariant(t.str().c_str(),TRUE);
      }
      else
      {
        return TemplateVariant("");
      }
    }
References addHtmlExtensionIfMissing(), ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, getCallerGraph(), MemberDef::getOutputFileBase(), GOF_BITMAP, GOF_EPS, hasCallerGraph(), m_memberDef, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), DefinitionContext< MemberContext::Private >::relPathAsString(), TextStream::str(), and TRUE.
callerGraph() [2/2]
TemplateVariant MemberContext::Private::callerGraph () const [inline]
Definition at line 3793 of file context.cpp.
    {
      if (hasCallerGraph().toBool())
      {
        DotCallGraphPtr cg = getCallerGraph();
        TextStream t;
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              cg->writeGraph(t,GOF_BITMAP,EOF_Html,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_memberDef->getOutputFileBase()),
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
          case ContextOutputFormat_Latex:
            {
              cg->writeGraph(t,GOF_EPS,EOF_LaTeX,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+m_memberDef->getOutputFileBase()+".tex",
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
        return TemplateVariant(t.str().c_str(),TRUE);
      }
      else
      {
        return TemplateVariant("");
      }
    }
References addHtmlExtensionIfMissing(), ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, GOF_BITMAP, GOF_EPS, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), TextStream::str(), and TRUE.
callGraph() [1/2]
TemplateVariant MemberContext::Private::callGraph () const [inline]
Definition at line 3735 of file context.cpp.
    {
      if (hasCallGraph().toBool())
      {
        DotCallGraphPtr cg = getCallGraph();
        TextStream t;
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              cg->writeGraph(t,GOF_BITMAP,EOF_Html,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_memberDef->getOutputFileBase()),
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
          case ContextOutputFormat_Latex:
            {
              cg->writeGraph(t,GOF_EPS,EOF_LaTeX,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+m_memberDef->getOutputFileBase()+".tex",
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
        return TemplateVariant(t.str().c_str(),TRUE);
      }
      else
      {
        return TemplateVariant("");
      }
    }
References addHtmlExtensionIfMissing(), ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, getCallGraph(), MemberDef::getOutputFileBase(), GOF_BITMAP, GOF_EPS, hasCallGraph(), m_memberDef, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), DefinitionContext< MemberContext::Private >::relPathAsString(), TextStream::str(), and TRUE.
callGraph() [2/2]
TemplateVariant MemberContext::Private::callGraph () const [inline]
Definition at line 3735 of file context.cpp.
    {
      if (hasCallGraph().toBool())
      {
        DotCallGraphPtr cg = getCallGraph();
        TextStream t;
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              cg->writeGraph(t,GOF_BITMAP,EOF_Html,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_memberDef->getOutputFileBase()),
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
          case ContextOutputFormat_Latex:
            {
              cg->writeGraph(t,GOF_EPS,EOF_LaTeX,
                  g_globals.outputDir,
                  g_globals.outputDir+Portable::pathSeparator()+m_memberDef->getOutputFileBase()+".tex",
                  relPathAsString(),TRUE,g_globals.dynSectionId
                  );
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
        return TemplateVariant(t.str().c_str(),TRUE);
      }
      else
      {
        return TemplateVariant("");
      }
    }
References addHtmlExtensionIfMissing(), ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, GOF_BITMAP, GOF_EPS, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), TextStream::str(), and TRUE.
category() [1/2]
TemplateVariant MemberContext::Private::category () const [inline]
Definition at line 3673 of file context.cpp.
{ return m_cachable.category.get(this); }
References MemberContext::Private::Cachable::category, and m_cachable.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::getCategory(), doxmlparser.index.MixedContainer::getCategory(), doxmlparser.compound.MixedContainer::to_etree(), and doxmlparser.index.MixedContainer::to_etree().
category() [2/2]
TemplateVariant MemberContext::Private::category () const [inline]
Definition at line 3673 of file context.cpp.
{ return m_cachable.category.get(this); }
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::getCategory(), doxmlparser.index.MixedContainer::getCategory(), doxmlparser.compound.MixedContainer::to_etree(), and doxmlparser.index.MixedContainer::to_etree().
categoryRelation() [1/2]
TemplateVariant MemberContext::Private::categoryRelation () const [inline]
Definition at line 3674 of file context.cpp.
{ return m_cachable.categoryRelation.get(this); }
References MemberContext::Private::Cachable::categoryRelation, and m_cachable.
categoryRelation() [2/2]
TemplateVariant MemberContext::Private::categoryRelation () const [inline]
Definition at line 3674 of file context.cpp.
{ return m_cachable.categoryRelation.get(this); }
createAnonymousMember() [1/2]
TemplateVariant MemberContext::Private::createAnonymousMember () const [inline], [private]
Definition at line 4148 of file context.cpp.
    {
      return m_memberDef->fromAnonymousMember() ?
          TemplateVariant(MemberContext::alloc(m_memberDef)) :
          TemplateVariant(false);
    }
References MemberContext::alloc(), MemberDef::fromAnonymousMember(), and m_memberDef.
createAnonymousMember() [2/2]
TemplateVariant MemberContext::Private::createAnonymousMember () const [inline], [private]
Definition at line 4148 of file context.cpp.
    {
      return m_memberDef->fromAnonymousMember() ?
          TemplateVariant(MemberContext::alloc(m_memberDef)) :
          TemplateVariant(false);
    }
References MemberContext::alloc().
createAnonymousType() [1/2]
TemplateVariant MemberContext::Private::createAnonymousType () const [inline], [private]
Definition at line 4025 of file context.cpp.
    {
      const ClassDef *cd = m_memberDef->getClassDefOfAnonymousType();
      return cd ? TemplateVariant(ClassContext::alloc(cd)) : TemplateVariant(false);
    }
References ClassContext::alloc(), MemberDef::getClassDefOfAnonymousType(), and m_memberDef.
createAnonymousType() [2/2]
TemplateVariant MemberContext::Private::createAnonymousType () const [inline], [private]
Definition at line 4025 of file context.cpp.
    {
      const ClassDef *cd = m_memberDef->getClassDefOfAnonymousType();
      return cd ? TemplateVariant(ClassContext::alloc(cd)) : TemplateVariant(false);
    }
References ClassContext::alloc().
createBitfields() [1/2]
TemplateVariant MemberContext::Private::createBitfields () const [inline], [private]
Definition at line 4229 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),m_memberDef->bitfieldString());
    }
References MemberDef::bitfieldString(), createLinkedText(), m_memberDef, and DefinitionContext< MemberContext::Private >::relPathAsString().
createBitfields() [2/2]
TemplateVariant MemberContext::Private::createBitfields () const [inline], [private]
Definition at line 4229 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),m_memberDef->bitfieldString());
    }
References createLinkedText().
createCallerGraph() [1/2]
DotCallGraphPtr MemberContext::Private::createCallerGraph () const [inline], [private]
Definition at line 4144 of file context.cpp.
    {
      return std::make_shared<DotCallGraph>(m_memberDef,TRUE);
    }
References m_memberDef, and TRUE.
createCallerGraph() [2/2]
DotCallGraphPtr MemberContext::Private::createCallerGraph () const [inline], [private]
Definition at line 4144 of file context.cpp.
    {
      return std::make_shared<DotCallGraph>(m_memberDef,TRUE);
    }
References TRUE.
createCallGraph() [1/2]
DotCallGraphPtr MemberContext::Private::createCallGraph () const [inline], [private]
Definition at line 4140 of file context.cpp.
    {
      return std::make_shared<DotCallGraph>(m_memberDef,FALSE);
    }
References FALSE, and m_memberDef.
createCallGraph() [2/2]
DotCallGraphPtr MemberContext::Private::createCallGraph () const [inline], [private]
Definition at line 4140 of file context.cpp.
    {
      return std::make_shared<DotCallGraph>(m_memberDef,FALSE);
    }
References FALSE.
createCategory() [1/2]
TemplateVariant MemberContext::Private::createCategory () const [inline], [private]
Definition at line 3967 of file context.cpp.
    {
      return m_memberDef->category() ?
          TemplateVariant(ClassContext::alloc(m_memberDef->category())) :
          TemplateVariant(false);
    }
References ClassContext::alloc(), MemberDef::category(), and m_memberDef.
createCategory() [2/2]
TemplateVariant MemberContext::Private::createCategory () const [inline], [private]
Definition at line 3967 of file context.cpp.
    {
      return m_memberDef->category() ?
          TemplateVariant(ClassContext::alloc(m_memberDef->category())) :
          TemplateVariant(false);
    }
References ClassContext::alloc().
createCategoryRelation() [1/2]
TemplateVariant MemberContext::Private::createCategoryRelation () const [inline], [private]
Definition at line 3973 of file context.cpp.
    {
      return m_memberDef->categoryRelation() ?
          TemplateVariant(MemberContext::alloc(m_memberDef->categoryRelation())) :
          TemplateVariant(false);
    }
References MemberContext::alloc(), MemberDef::categoryRelation(), and m_memberDef.
createCategoryRelation() [2/2]
TemplateVariant MemberContext::Private::createCategoryRelation () const [inline], [private]
Definition at line 3973 of file context.cpp.
    {
      return m_memberDef->categoryRelation() ?
          TemplateVariant(MemberContext::alloc(m_memberDef->categoryRelation())) :
          TemplateVariant(false);
    }
References MemberContext::alloc().
createClassDef() [1/2]
TemplateVariant MemberContext::Private::createClassDef () const [inline], [private]
Definition at line 3961 of file context.cpp.
    {
      return m_memberDef->getClassDef() ?
          TemplateVariant(ClassContext::alloc(m_memberDef->getClassDef())) :
          TemplateVariant(false);
    }
References ClassContext::alloc(), MemberDef::getClassDef(), and m_memberDef.
createClassDef() [2/2]
TemplateVariant MemberContext::Private::createClassDef () const [inline], [private]
Definition at line 3961 of file context.cpp.
    {
      return m_memberDef->getClassDef() ?
          TemplateVariant(ClassContext::alloc(m_memberDef->getClassDef())) :
          TemplateVariant(false);
    }
References ClassContext::alloc().
createDeclArgs() [1/2]
TemplateVariant MemberContext::Private::createDeclArgs () const [inline], [private]
Definition at line 4217 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),m_memberDef->argsString());
    }
References MemberDef::argsString(), createLinkedText(), m_memberDef, and DefinitionContext< MemberContext::Private >::relPathAsString().
createDeclArgs() [2/2]
TemplateVariant MemberContext::Private::createDeclArgs () const [inline], [private]
Definition at line 4217 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),m_memberDef->argsString());
    }
References createLinkedText().
createDeclType() [1/2]
TemplateVariant MemberContext::Private::createDeclType () const [inline], [private]
Definition at line 4213 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),m_memberDef->getDeclType());
    }
References createLinkedText(), MemberDef::getDeclType(), m_memberDef, and DefinitionContext< MemberContext::Private >::relPathAsString().
createDeclType() [2/2]
TemplateVariant MemberContext::Private::createDeclType () const [inline], [private]
Definition at line 4213 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),m_memberDef->getDeclType());
    }
References createLinkedText().
createDefinition() [1/2]
TemplateVariant MemberContext::Private::createDefinition () const [inline], [private]
Definition at line 3979 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),
                              m_memberDef->displayDefinition());
    }
References createLinkedText(), MemberDef::displayDefinition(), m_memberDef, and DefinitionContext< MemberContext::Private >::relPathAsString().
createDefinition() [2/2]
TemplateVariant MemberContext::Private::createDefinition () const [inline], [private]
Definition at line 3979 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),
                              m_memberDef->displayDefinition());
    }
References createLinkedText().
createEnumValues() [1/2]
TemplateVariant MemberContext::Private::createEnumValues () const [inline], [private]
Definition at line 3943 of file context.cpp.
    {
      return m_memberDef->isEnumerate() ?
          TemplateVariant(MemberListContext::alloc(m_memberDef->enumFieldList())) :
          TemplateVariant(false);
    }
References MemberListContext::alloc(), MemberDef::enumFieldList(), MemberDef::isEnumerate(), and m_memberDef.
createEnumValues() [2/2]
TemplateVariant MemberContext::Private::createEnumValues () const [inline], [private]
Definition at line 3943 of file context.cpp.
    {
      return m_memberDef->isEnumerate() ?
          TemplateVariant(MemberListContext::alloc(m_memberDef->enumFieldList())) :
          TemplateVariant(false);
    }
References MemberListContext::alloc().
createEventAttrs() [1/2]
TemplateVariant MemberContext::Private::createEventAttrs () const [inline], [private]
Definition at line 3924 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(3);
      if (m_memberDef->isEvent())
      {
        if (m_memberDef->isAddable()) list.push_back("add");
        if (m_memberDef->isRemovable()) list.push_back("remove");
        if (m_memberDef->isRaisable()) list.push_back("raise");
      }
      return TemplateImmutableList::alloc(list);
    }
References TemplateImmutableList::alloc(), MemberDef::isAddable(), MemberDef::isEvent(), MemberDef::isRaisable(), MemberDef::isRemovable(), and m_memberDef.
createEventAttrs() [2/2]
TemplateVariant MemberContext::Private::createEventAttrs () const [inline], [private]
Definition at line 3924 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(3);
      if (m_memberDef->isEvent())
      {
        if (m_memberDef->isAddable()) list.push_back("add");
        if (m_memberDef->isRemovable()) list.push_back("remove");
        if (m_memberDef->isRaisable()) list.push_back("raise");
      }
      return TemplateImmutableList::alloc(list);
    }
References TemplateImmutableList::alloc().
createExamples() [1/2]
TemplateVariant MemberContext::Private::createExamples () const [inline], [private]
Definition at line 4110 of file context.cpp.
    {
      TemplateVariantList list;
      if (m_memberDef->hasExamples())
      {
        list.reserve(m_memberDef->getExamples().size());
        for (const auto &ex : m_memberDef->getExamples())
        {
          TemplateStructIntfPtr s = TemplateImmutableStruct::alloc(
          {
            { "text", TemplateVariant(ex.name) },
            { "isLinkable", TemplateVariant(TRUE) },
            { "anchor", TemplateVariant(ex.anchor) },
            { "fileName", TemplateVariant(ex.file) },
            { "isReference", TemplateVariant(FALSE) },
            { "externalReference",TemplateVariant("") }
          });
          list.push_back(s);
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References TemplateImmutableStruct::alloc(), TemplateImmutableList::alloc(), FALSE, MemberDef::getExamples(), MemberDef::hasExamples(), m_memberDef, s, and TRUE.
createExamples() [2/2]
TemplateVariant MemberContext::Private::createExamples () const [inline], [private]
Definition at line 4110 of file context.cpp.
    {
      TemplateVariantList list;
      if (m_memberDef->hasExamples())
      {
        list.reserve(m_memberDef->getExamples().size());
        for (const auto &ex : m_memberDef->getExamples())
        {
          TemplateStructIntfPtr s = TemplateImmutableStruct::alloc(
          {
            { "text", TemplateVariant(ex.name) },
            { "isLinkable", TemplateVariant(TRUE) },
            { "anchor", TemplateVariant(ex.anchor) },
            { "fileName", TemplateVariant(ex.file) },
            { "isReference", TemplateVariant(FALSE) },
            { "externalReference",TemplateVariant("") }
          });
          list.push_back(s);
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References TemplateImmutableStruct::alloc(), TemplateImmutableList::alloc(), FALSE, s, and TRUE.
createException() [1/2]
TemplateVariant MemberContext::Private::createException () const [inline], [private]
Definition at line 4225 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),m_memberDef->excpString());
    }
References createLinkedText(), MemberDef::excpString(), m_memberDef, and DefinitionContext< MemberContext::Private >::relPathAsString().
createException() [2/2]
TemplateVariant MemberContext::Private::createException () const [inline], [private]
Definition at line 4225 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),m_memberDef->excpString());
    }
References createLinkedText().
createFieldType() [1/2]
TemplateVariant MemberContext::Private::createFieldType () const [inline], [private]
Definition at line 4221 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),m_memberDef->fieldType());
    }
References createLinkedText(), MemberDef::fieldType(), m_memberDef, and DefinitionContext< MemberContext::Private >::relPathAsString().
createFieldType() [2/2]
TemplateVariant MemberContext::Private::createFieldType () const [inline], [private]
Definition at line 4221 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),m_memberDef->fieldType());
    }
References createLinkedText().
createFileDef() [1/2]
TemplateVariant MemberContext::Private::createFileDef () const [inline], [private]
Definition at line 3949 of file context.cpp.
    {
      return m_memberDef->getFileDef() ?
          TemplateVariant(FileContext::alloc(m_memberDef->getFileDef())) :
          TemplateVariant(false);
    }
References FileContext::alloc(), MemberDef::getFileDef(), and m_memberDef.
createFileDef() [2/2]
TemplateVariant MemberContext::Private::createFileDef () const [inline], [private]
Definition at line 3949 of file context.cpp.
    {
      return m_memberDef->getFileDef() ?
          TemplateVariant(FileContext::alloc(m_memberDef->getFileDef())) :
          TemplateVariant(false);
    }
References FileContext::alloc().
createImplementedBy() [1/2]
TemplateVariant MemberContext::Private::createImplementedBy () const [inline], [private]
Definition at line 4080 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_memberDef->reimplementedBy().size());
      for (const auto &md : m_memberDef->reimplementedBy())
      {
        const ClassDef *cd = md->getClassDef();
        // filter on pure virtual/interface methods
        if (cd && md->virtualness()==Pure && cd->compoundType()==ClassDef::Interface)
        {
          list.push_back(MemberContext::alloc(md));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), ClassDef::compoundType(), ClassDef::Interface, m_memberDef, Pure, MemberDef::reimplementedBy(), and MemberVector::size().
createImplementedBy() [2/2]
TemplateVariant MemberContext::Private::createImplementedBy () const [inline], [private]
Definition at line 4080 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_memberDef->reimplementedBy().size());
      for (const auto &md : m_memberDef->reimplementedBy())
      {
        const ClassDef *cd = md->getClassDef();
        // filter on pure virtual/interface methods
        if (cd && md->virtualness()==Pure && cd->compoundType()==ClassDef::Interface)
        {
          list.push_back(MemberContext::alloc(md));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), ClassDef::compoundType(), ClassDef::Interface, and Pure.
createImplements() [1/2]
TemplateVariant MemberContext::Private::createImplements () const [inline], [private]
Definition at line 4050 of file context.cpp.
    {
      const MemberDef *md = m_memberDef->reimplements();
      TemplateVariantList list;
      if (md)
      {
        const ClassDef *cd = md->getClassDef();
        // filter on pure virtual/interface methods
        if (cd && (md->virtualness()==Pure || cd->compoundType()==ClassDef::Interface))
        {
          list.push_back(MemberContext::alloc(md));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), ClassDef::compoundType(), MemberDef::getClassDef(), ClassDef::Interface, m_memberDef, Pure, MemberDef::reimplements(), and MemberDef::virtualness().
createImplements() [2/2]
TemplateVariant MemberContext::Private::createImplements () const [inline], [private]
Definition at line 4050 of file context.cpp.
    {
      const MemberDef *md = m_memberDef->reimplements();
      TemplateVariantList list;
      if (md)
      {
        const ClassDef *cd = md->getClassDef();
        // filter on pure virtual/interface methods
        if (cd && (md->virtualness()==Pure || cd->compoundType()==ClassDef::Interface))
        {
          list.push_back(MemberContext::alloc(md));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), ClassDef::compoundType(), MemberDef::getClassDef(), ClassDef::Interface, Pure, MemberDef::reimplements(), and MemberDef::virtualness().
createInitializer() [1/2]
TemplateVariant MemberContext::Private::createInitializer () const [inline], [private]
Definition at line 4186 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),m_memberDef->initializer());
    }
References createLinkedText(), MemberDef::initializer(), m_memberDef, and DefinitionContext< MemberContext::Private >::relPathAsString().
createInitializer() [2/2]
TemplateVariant MemberContext::Private::createInitializer () const [inline], [private]
Definition at line 4186 of file context.cpp.
    {
      return createLinkedText(m_memberDef,relPathAsString(),m_memberDef->initializer());
    }
References createLinkedText().
createInitializerAsCode() [1/2]
TemplateVariant MemberContext::Private::createInitializerAsCode () const [inline], [private]
Definition at line 4171 of file context.cpp.
    {
      QCString scopeName;
      if (m_memberDef->getClassDef())
      {
        scopeName = m_memberDef->getClassDef()->name();
      }
      else if (m_memberDef->getNamespaceDef())
      {
        scopeName = m_memberDef->getNamespaceDef()->name();
      }
      return TemplateVariant(parseCode(m_memberDef,
                                       scopeName,relPathAsString(),
                                       m_memberDef->initializer()));
    }
References MemberDef::getClassDef(), MemberDef::getNamespaceDef(), MemberDef::initializer(), m_memberDef, Definition::name(), parseCode(), and DefinitionContext< MemberContext::Private >::relPathAsString().
createInitializerAsCode() [2/2]
TemplateVariant MemberContext::Private::createInitializerAsCode () const [inline], [private]
Definition at line 4171 of file context.cpp.
    {
      QCString scopeName;
      if (m_memberDef->getClassDef())
      {
        scopeName = m_memberDef->getClassDef()->name();
      }
      else if (m_memberDef->getNamespaceDef())
      {
        scopeName = m_memberDef->getNamespaceDef()->name();
      }
      return TemplateVariant(parseCode(m_memberDef,
                                       scopeName,relPathAsString(),
                                       m_memberDef->initializer()));
    }
References parseCode().
createLabels() [1/2]
TemplateVariant MemberContext::Private::createLabels () const [inline], [private]
Definition at line 4154 of file context.cpp.
    {
      StringVector sl = m_memberDef->getLabels(m_memberDef->getOuterScope());
      TemplateVariantList list;
      list.reserve(sl.size());
      for (const auto &s : sl)
      {
        list.push_back(s.c_str());
      }
      return TemplateImmutableList::alloc(list);
    }
References TemplateImmutableList::alloc(), MemberDef::getLabels(), Definition::getOuterScope(), m_memberDef, s, and caseconvert::sl.
createLabels() [2/2]
TemplateVariant MemberContext::Private::createLabels () const [inline], [private]
Definition at line 4154 of file context.cpp.
    {
      StringVector sl = m_memberDef->getLabels(m_memberDef->getOuterScope());
      TemplateVariantList list;
      list.reserve(sl.size());
      for (const auto &s : sl)
      {
        list.push_back(s.c_str());
      }
      return TemplateImmutableList::alloc(list);
    }
References TemplateImmutableList::alloc(), s, and caseconvert::sl.
createNamespaceDef() [1/2]
TemplateVariant MemberContext::Private::createNamespaceDef () const [inline], [private]
Definition at line 3955 of file context.cpp.
    {
      return m_memberDef->getNamespaceDef() ?
          TemplateVariant(NamespaceContext::alloc(m_memberDef->getNamespaceDef())) :
          TemplateVariant(false);
    }
References NamespaceContext::alloc(), MemberDef::getNamespaceDef(), and m_memberDef.
createNamespaceDef() [2/2]
TemplateVariant MemberContext::Private::createNamespaceDef () const [inline], [private]
Definition at line 3955 of file context.cpp.
    {
      return m_memberDef->getNamespaceDef() ?
          TemplateVariant(NamespaceContext::alloc(m_memberDef->getNamespaceDef())) :
          TemplateVariant(false);
    }
References NamespaceContext::alloc().
createParamDocs() [1/2]
TemplateVariant MemberContext::Private::createParamDocs () const [inline], [private]
Definition at line 4030 of file context.cpp.
    {
      if (m_memberDef->argumentList().hasDocumentation())
      {
        QCString paramDocs;
        for (const Argument &a : m_memberDef->argumentList())
        {
          if (a.hasDocumentation())
          {
            QCString docs = a.docs;
            QCString direction = extractDirection(docs);
            paramDocs+="@param"+direction+" "+a.name+" "+docs;
          }
        }
        return TemplateVariant(parseDoc(m_memberDef,
                                        m_memberDef->docFile(),m_memberDef->docLine(),
                                        relPathAsString(),paramDocs,FALSE));
      }
      return TemplateVariant("");
    }
References a, MemberDef::argumentList(), Definition::docFile(), Definition::docLine(), extractDirection(), FALSE, ArgumentList::hasDocumentation(), m_memberDef, paramDocs(), parseDoc(), and DefinitionContext< MemberContext::Private >::relPathAsString().
createParamDocs() [2/2]
TemplateVariant MemberContext::Private::createParamDocs () const [inline], [private]
Definition at line 4030 of file context.cpp.
    {
      if (m_memberDef->argumentList().hasDocumentation())
      {
        QCString paramDocs;
        for (const Argument &a : m_memberDef->argumentList())
        {
          if (a.hasDocumentation())
          {
            QCString docs = a.docs;
            QCString direction = extractDirection(docs);
            paramDocs+="@param"+direction+" "+a.name+" "+docs;
          }
        }
        return TemplateVariant(parseDoc(m_memberDef,
                                        m_memberDef->docFile(),m_memberDef->docLine(),
                                        relPathAsString(),paramDocs,FALSE));
      }
      return TemplateVariant("");
    }
References a, extractDirection(), FALSE, and parseDoc().
createParameters() [1/2]
TemplateVariant MemberContext::Private::createParameters () const [inline], [private]
Definition at line 3936 of file context.cpp.
    {
      const ArgumentList &defArgList = getDefArgList();
      return !m_memberDef->isProperty() ?
          ArgumentListContext::alloc(defArgList,m_memberDef,relPathAsString()) :
          ArgumentListContext::alloc();
    }
References ArgumentListContext::alloc(), getDefArgList(), MemberDef::isProperty(), m_memberDef, and DefinitionContext< MemberContext::Private >::relPathAsString().
createParameters() [2/2]
TemplateVariant MemberContext::Private::createParameters () const [inline], [private]
Definition at line 3936 of file context.cpp.
    {
      const ArgumentList &defArgList = getDefArgList();
      return !m_memberDef->isProperty() ?
          ArgumentListContext::alloc(defArgList,m_memberDef,relPathAsString()) :
          ArgumentListContext::alloc();
    }
References ArgumentListContext::alloc().
createPropertyAttrs() [1/2]
TemplateVariant MemberContext::Private::createPropertyAttrs () const [inline], [private]
Definition at line 3909 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(6);
      if (m_memberDef->isProperty())
      {
        if (m_memberDef->isGettable()) list.push_back("get");
        if (m_memberDef->isPrivateGettable()) list.push_back("private get");
        if (m_memberDef->isProtectedGettable()) list.push_back("protected get");
        if (m_memberDef->isSettable()) list.push_back("set");
        if (m_memberDef->isPrivateSettable()) list.push_back("private set");
        if (m_memberDef->isProtectedSettable()) list.push_back("protected set");
      }
      return TemplateImmutableList::alloc(list);
    }
References TemplateImmutableList::alloc(), MemberDef::isGettable(), MemberDef::isPrivateGettable(), MemberDef::isPrivateSettable(), MemberDef::isProperty(), MemberDef::isProtectedGettable(), MemberDef::isProtectedSettable(), MemberDef::isSettable(), and m_memberDef.
createPropertyAttrs() [2/2]
TemplateVariant MemberContext::Private::createPropertyAttrs () const [inline], [private]
Definition at line 3909 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(6);
      if (m_memberDef->isProperty())
      {
        if (m_memberDef->isGettable()) list.push_back("get");
        if (m_memberDef->isPrivateGettable()) list.push_back("private get");
        if (m_memberDef->isProtectedGettable()) list.push_back("protected get");
        if (m_memberDef->isSettable()) list.push_back("set");
        if (m_memberDef->isPrivateSettable()) list.push_back("private set");
        if (m_memberDef->isProtectedSettable()) list.push_back("protected set");
      }
      return TemplateImmutableList::alloc(list);
    }
References TemplateImmutableList::alloc().
createReimplementedBy() [1/2]
TemplateVariant MemberContext::Private::createReimplementedBy () const [inline], [private]
Definition at line 4095 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_memberDef->reimplementedBy().size());
      for (const auto &md : m_memberDef->reimplementedBy())
      {
        const ClassDef *cd = md->getClassDef();
        // filter on non-pure virtual & non interface methods
        if (cd && md->virtualness()!=Pure && cd->compoundType()!=ClassDef::Interface)
        {
          list.push_back(MemberContext::alloc(md));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), ClassDef::compoundType(), ClassDef::Interface, m_memberDef, Pure, MemberDef::reimplementedBy(), and MemberVector::size().
createReimplementedBy() [2/2]
TemplateVariant MemberContext::Private::createReimplementedBy () const [inline], [private]
Definition at line 4095 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_memberDef->reimplementedBy().size());
      for (const auto &md : m_memberDef->reimplementedBy())
      {
        const ClassDef *cd = md->getClassDef();
        // filter on non-pure virtual & non interface methods
        if (cd && md->virtualness()!=Pure && cd->compoundType()!=ClassDef::Interface)
        {
          list.push_back(MemberContext::alloc(md));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), ClassDef::compoundType(), ClassDef::Interface, and Pure.
createReimplements() [1/2]
TemplateVariant MemberContext::Private::createReimplements () const [inline], [private]
Definition at line 4065 of file context.cpp.
    {
      const MemberDef *md = m_memberDef->reimplements();
      TemplateVariantList list;
      if (md)
      {
        const ClassDef *cd = md->getClassDef();
        // filter on non-pure virtual & non interface methods
        if (cd && md->virtualness()!=Pure && cd->compoundType()!=ClassDef::Interface)
        {
          list.push_back(MemberContext::alloc(md));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), ClassDef::compoundType(), MemberDef::getClassDef(), ClassDef::Interface, m_memberDef, Pure, MemberDef::reimplements(), and MemberDef::virtualness().
createReimplements() [2/2]
TemplateVariant MemberContext::Private::createReimplements () const [inline], [private]
Definition at line 4065 of file context.cpp.
    {
      const MemberDef *md = m_memberDef->reimplements();
      TemplateVariantList list;
      if (md)
      {
        const ClassDef *cd = md->getClassDef();
        // filter on non-pure virtual & non interface methods
        if (cd && md->virtualness()!=Pure && cd->compoundType()!=ClassDef::Interface)
        {
          list.push_back(MemberContext::alloc(md));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), ClassDef::compoundType(), MemberDef::getClassDef(), ClassDef::Interface, Pure, MemberDef::reimplements(), and MemberDef::virtualness().
createSourceCode() [1/2]
TemplateVariant MemberContext::Private::createSourceCode () const [inline], [private]
Definition at line 4190 of file context.cpp.
    {
      QCString codeFragment;
      const FileDef *fd = m_memberDef->getBodyDef();
      int startLine = m_memberDef->getStartBodyLine();
      int endLine = m_memberDef->getEndBodyLine();
      if (fd && readCodeFragment(fd->absFilePath(),startLine,endLine,codeFragment))
      {
        QCString scopeName;
        if (m_memberDef->getClassDef())
        {
          scopeName = m_memberDef->getClassDef()->name();
        }
        else if (m_memberDef->getNamespaceDef())
        {
          scopeName = m_memberDef->getNamespaceDef()->name();
        }
        return parseCode(m_memberDef,
                         scopeName,relPathAsString(),
                         codeFragment,startLine,endLine,TRUE);
      }
      return TemplateVariant("");
    }
References FileDef::absFilePath(), Definition::getBodyDef(), MemberDef::getClassDef(), Definition::getEndBodyLine(), MemberDef::getNamespaceDef(), Definition::getStartBodyLine(), m_memberDef, Definition::name(), parseCode(), readCodeFragment(), DefinitionContext< MemberContext::Private >::relPathAsString(), and TRUE.
createSourceCode() [2/2]
TemplateVariant MemberContext::Private::createSourceCode () const [inline], [private]
Definition at line 4190 of file context.cpp.
    {
      QCString codeFragment;
      const FileDef *fd = m_memberDef->getBodyDef();
      int startLine = m_memberDef->getStartBodyLine();
      int endLine = m_memberDef->getEndBodyLine();
      if (fd && readCodeFragment(fd->absFilePath(),startLine,endLine,codeFragment))
      {
        QCString scopeName;
        if (m_memberDef->getClassDef())
        {
          scopeName = m_memberDef->getClassDef()->name();
        }
        else if (m_memberDef->getNamespaceDef())
        {
          scopeName = m_memberDef->getNamespaceDef()->name();
        }
        return parseCode(m_memberDef,
                         scopeName,relPathAsString(),
                         codeFragment,startLine,endLine,TRUE);
      }
      return TemplateVariant("");
    }
References FileDef::absFilePath(), Definition::getBodyDef(), Definition::getStartBodyLine(), parseCode(), readCodeFragment(), and TRUE.
createSourceRefBys() [1/2]
TemplateVariant MemberContext::Private::createSourceRefBys () const [inline], [private]
Definition at line 4136 of file context.cpp.
    {
      return MemberListContext::alloc(m_memberDef->getReferencedByMembers());
    }
References MemberListContext::alloc(), Definition::getReferencedByMembers(), and m_memberDef.
createSourceRefBys() [2/2]
TemplateVariant MemberContext::Private::createSourceRefBys () const [inline], [private]
Definition at line 4136 of file context.cpp.
    {
      return MemberListContext::alloc(m_memberDef->getReferencedByMembers());
    }
References MemberListContext::alloc().
createSourceRefs() [1/2]
TemplateVariant MemberContext::Private::createSourceRefs () const [inline], [private]
Definition at line 4132 of file context.cpp.
    {
      return MemberListContext::alloc(m_memberDef->getReferencesMembers());
    }
References MemberListContext::alloc(), Definition::getReferencesMembers(), and m_memberDef.
createSourceRefs() [2/2]
TemplateVariant MemberContext::Private::createSourceRefs () const [inline], [private]
Definition at line 4132 of file context.cpp.
    {
      return MemberListContext::alloc(m_memberDef->getReferencesMembers());
    }
References MemberListContext::alloc().
createTemplateAlias() [1/2]
TemplateVariant MemberContext::Private::createTemplateAlias () const [inline], [private]
Definition at line 3902 of file context.cpp.
    {
      return m_memberDef->isTypeAlias() ?
         TemplateVariant(createLinkedText(m_memberDef,relPathAsString(),
                                QCString(" = ")+m_memberDef->typeString())) :
         TemplateVariant("");
    }
References createLinkedText(), MemberDef::isTypeAlias(), m_memberDef, DefinitionContext< MemberContext::Private >::relPathAsString(), and MemberDef::typeString().
createTemplateAlias() [2/2]
TemplateVariant MemberContext::Private::createTemplateAlias () const [inline], [private]
Definition at line 3902 of file context.cpp.
    {
      return m_memberDef->isTypeAlias() ?
         TemplateVariant(createLinkedText(m_memberDef,relPathAsString(),
                                QCString(" = ")+m_memberDef->typeString())) :
         TemplateVariant("");
    }
References createLinkedText().
createTemplateArgs() [1/2]
TemplateVariant MemberContext::Private::createTemplateArgs () const [inline], [private]
Definition at line 3896 of file context.cpp.
    {
      return !m_memberDef->templateArguments().empty() ?
         TemplateVariant(ArgumentListContext::alloc(m_memberDef->templateArguments(),m_memberDef,relPathAsString())) :
         TemplateVariant(false);
    }
References ArgumentListContext::alloc(), ArgumentList::empty(), m_memberDef, DefinitionContext< MemberContext::Private >::relPathAsString(), and MemberDef::templateArguments().
createTemplateArgs() [2/2]
TemplateVariant MemberContext::Private::createTemplateArgs () const [inline], [private]
Definition at line 3896 of file context.cpp.
    {
      return !m_memberDef->templateArguments().empty() ?
         TemplateVariant(ArgumentListContext::alloc(m_memberDef->templateArguments(),m_memberDef,relPathAsString())) :
         TemplateVariant(false);
    }
References ArgumentListContext::alloc().
createTemplateDecls() [1/2]
TemplateVariant MemberContext::Private::createTemplateDecls () const [inline], [private]
Definition at line 3991 of file context.cpp.
    {
      TemplateVariantList list;
      const ClassDef *cd=m_memberDef->getClassDef();
      if (!m_memberDef->definitionTemplateParameterLists().empty())
      {
        for (const ArgumentList &tal : m_memberDef->definitionTemplateParameterLists())
        {
          if (!tal.empty())
          {
            list.push_back(ArgumentListContext::alloc(tal,m_memberDef,relPathAsString()));
          }
        }
      }
      else
      {
        if (cd && !m_memberDef->isRelated() && !m_memberDef->isTemplateSpecialization())
        {
          for (const ArgumentList &tal : cd->getTemplateParameterLists())
          {
            if (!tal.empty())
            {
              list.push_back(ArgumentListContext::alloc(tal,m_memberDef,relPathAsString()));
            }
          }
        }
        if (!m_memberDef->templateArguments().empty()) // function template prefix
        {
          list.push_back(ArgumentListContext::alloc(
                       m_memberDef->templateArguments(),m_memberDef,relPathAsString()));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ArgumentListContext::alloc(), TemplateImmutableList::alloc(), MemberDef::definitionTemplateParameterLists(), ArgumentList::empty(), MemberDef::getClassDef(), ClassDef::getTemplateParameterLists(), MemberDef::isRelated(), MemberDef::isTemplateSpecialization(), m_memberDef, DefinitionContext< MemberContext::Private >::relPathAsString(), and MemberDef::templateArguments().
createTemplateDecls() [2/2]
TemplateVariant MemberContext::Private::createTemplateDecls () const [inline], [private]
Definition at line 3991 of file context.cpp.
    {
      TemplateVariantList list;
      const ClassDef *cd=m_memberDef->getClassDef();
      if (!m_memberDef->definitionTemplateParameterLists().empty())
      {
        for (const ArgumentList &tal : m_memberDef->definitionTemplateParameterLists())
        {
          if (!tal.empty())
          {
            list.push_back(ArgumentListContext::alloc(tal,m_memberDef,relPathAsString()));
          }
        }
      }
      else
      {
        if (cd && !m_memberDef->isRelated() && !m_memberDef->isTemplateSpecialization())
        {
          for (const ArgumentList &tal : cd->getTemplateParameterLists())
          {
            if (!tal.empty())
            {
              list.push_back(ArgumentListContext::alloc(tal,m_memberDef,relPathAsString()));
            }
          }
        }
        if (!m_memberDef->templateArguments().empty()) // function template prefix
        {
          list.push_back(ArgumentListContext::alloc(
                       m_memberDef->templateArguments(),m_memberDef,relPathAsString()));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ArgumentListContext::alloc(), TemplateImmutableList::alloc(), and ClassDef::getTemplateParameterLists().
createTrailingReturnType() [1/2]
TemplateVariant MemberContext::Private::createTrailingReturnType () const [inline], [private]
Definition at line 3984 of file context.cpp.
    {
      const ArgumentList &al = getDefArgList();
      return !al.trailingReturnType().isEmpty() ?
          TemplateVariant(createLinkedText(m_memberDef,relPathAsString(), al.trailingReturnType())) :
          TemplateVariant("");
    }
References createLinkedText(), getDefArgList(), QCString::isEmpty(), m_memberDef, DefinitionContext< MemberContext::Private >::relPathAsString(), and ArgumentList::trailingReturnType().
createTrailingReturnType() [2/2]
TemplateVariant MemberContext::Private::createTrailingReturnType () const [inline], [private]
Definition at line 3984 of file context.cpp.
    {
      const ArgumentList &al = getDefArgList();
      return !al.trailingReturnType().isEmpty() ?
          TemplateVariant(createLinkedText(m_memberDef,relPathAsString(), al.trailingReturnType())) :
          TemplateVariant("");
    }
References createLinkedText(), QCString::isEmpty(), and ArgumentList::trailingReturnType().
createTypeConstraints() [1/2]
TemplateVariant MemberContext::Private::createTypeConstraints () const [inline], [private]
Definition at line 4165 of file context.cpp.
    {
      return !m_memberDef->typeConstraints().empty() ?
          TemplateVariant(ArgumentListContext::alloc(m_memberDef->typeConstraints(),m_memberDef,relPathAsString())) :
          TemplateVariant(ArgumentListContext::alloc());
    }
References ArgumentListContext::alloc(), ArgumentList::empty(), m_memberDef, DefinitionContext< MemberContext::Private >::relPathAsString(), and MemberDef::typeConstraints().
createTypeConstraints() [2/2]
TemplateVariant MemberContext::Private::createTypeConstraints () const [inline], [private]
Definition at line 4165 of file context.cpp.
    {
      return !m_memberDef->typeConstraints().empty() ?
          TemplateVariant(ArgumentListContext::alloc(m_memberDef->typeConstraints(),m_memberDef,relPathAsString())) :
          TemplateVariant(ArgumentListContext::alloc());
    }
References ArgumentListContext::alloc().
declArgs() [1/2]
TemplateVariant MemberContext::Private::declArgs () const [inline]
Definition at line 3660 of file context.cpp.
{ return m_cachable.declArgs.get(this); }
References MemberContext::Private::Cachable::declArgs, and m_cachable.
declArgs() [2/2]
TemplateVariant MemberContext::Private::declArgs () const [inline]
Definition at line 3660 of file context.cpp.
{ return m_cachable.declArgs.get(this); }
declType() [1/2]
TemplateVariant MemberContext::Private::declType () const [inline]
Definition at line 3659 of file context.cpp.
{ return m_cachable.declType.get(this); }
References MemberContext::Private::Cachable::declType, and m_cachable.
declType() [2/2]
TemplateVariant MemberContext::Private::declType () const [inline]
Definition at line 3659 of file context.cpp.
{ return m_cachable.declType.get(this); }
definition() [1/2]
TemplateVariant MemberContext::Private::definition () const [inline]
Definition at line 3677 of file context.cpp.
{ return m_cachable.definition.get(this); }
References MemberContext::Private::Cachable::definition, and m_cachable.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_definition(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_definition().
definition() [2/2]
TemplateVariant MemberContext::Private::definition () const [inline]
Definition at line 3677 of file context.cpp.
{ return m_cachable.definition.get(this); }
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_definition(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_definition().
detailsVisibleFor() [1/2]
TemplateVariant MemberContext::Private::detailsVisibleFor () const [inline]
Definition at line 3857 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleDetailsVisibleFor,this,std::placeholders::_1));
    }
References handleDetailsVisibleFor().
detailsVisibleFor() [2/2]
TemplateVariant MemberContext::Private::detailsVisibleFor () const [inline]
Definition at line 3857 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleDetailsVisibleFor,this,std::placeholders::_1));
    }
enumBaseType() [1/2]
TemplateVariant MemberContext::Private::enumBaseType () const [inline]
Definition at line 3653 of file context.cpp.
{ return m_memberDef->enumBaseType(); }
References MemberDef::enumBaseType(), and m_memberDef.
enumBaseType() [2/2]
TemplateVariant MemberContext::Private::enumBaseType () const [inline]
Definition at line 3653 of file context.cpp.
{ return m_memberDef->enumBaseType(); }
enumValues() [1/2]
TemplateVariant MemberContext::Private::enumValues () const [inline]
Definition at line 3667 of file context.cpp.
{ return m_cachable.enumValues.get(this); }
References MemberContext::Private::Cachable::enumValues, and m_cachable.
enumValues() [2/2]
TemplateVariant MemberContext::Private::enumValues () const [inline]
Definition at line 3667 of file context.cpp.
{ return m_cachable.enumValues.get(this); }
eventAttrs() [1/2]
TemplateVariant MemberContext::Private::eventAttrs () const [inline]
Definition at line 3671 of file context.cpp.
{ return m_cachable.eventAttrs.get(this); }
References MemberContext::Private::Cachable::eventAttrs, and m_cachable.
eventAttrs() [2/2]
TemplateVariant MemberContext::Private::eventAttrs () const [inline]
Definition at line 3671 of file context.cpp.
{ return m_cachable.eventAttrs.get(this); }
examples() [1/2]
TemplateVariant MemberContext::Private::examples () const [inline]
Definition at line 3692 of file context.cpp.
{ return m_cachable.examples.get(this); }
References MemberContext::Private::Cachable::examples, and m_cachable.
examples() [2/2]
TemplateVariant MemberContext::Private::examples () const [inline]
Definition at line 3692 of file context.cpp.
{ return m_cachable.examples.get(this); }
exception() [1/2]
TemplateVariant MemberContext::Private::exception () const [inline]
Definition at line 3661 of file context.cpp.
{ return m_cachable.exception.get(this); }
References MemberContext::Private::Cachable::exception, and m_cachable.
exception() [2/2]
TemplateVariant MemberContext::Private::exception () const [inline]
Definition at line 3661 of file context.cpp.
{ return m_cachable.exception.get(this); }
extraTypeChars() [1/2]
TemplateVariant MemberContext::Private::extraTypeChars () const [inline]
Definition at line 3656 of file context.cpp.
{ return m_memberDef->extraTypeChars(); }
References MemberDef::extraTypeChars(), and m_memberDef.
extraTypeChars() [2/2]
TemplateVariant MemberContext::Private::extraTypeChars () const [inline]
Definition at line 3656 of file context.cpp.
{ return m_memberDef->extraTypeChars(); }
fields() [1/2]
StringVector MemberContext::Private::fields () const [inline]
Definition at line 3583 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector MemberContext::Private::fields () const [inline]
Definition at line 3583 of file context.cpp.
{ return s_inst.fields(); }
fieldType() [1/2]
TemplateVariant MemberContext::Private::fieldType () const [inline]
Definition at line 3658 of file context.cpp.
{ return m_cachable.fieldType.get(this); }
References MemberContext::Private::Cachable::fieldType, and m_cachable.
fieldType() [2/2]
TemplateVariant MemberContext::Private::fieldType () const [inline]
Definition at line 3658 of file context.cpp.
{ return m_cachable.fieldType.get(this); }
functionQualifier() [1/2]
TemplateVariant MemberContext::Private::functionQualifier () const [inline]
Definition at line 3709 of file context.cpp.
    {
      if (!m_memberDef->isObjCMethod() &&
          (m_memberDef->isFunction() || m_memberDef->isSlot() ||
           m_memberDef->isPrototype() || m_memberDef->isSignal()
          )
         )
      {
        return "()";
      }
      else
      {
        return "";
      }
    }
References MemberDef::isFunction(), MemberDef::isObjCMethod(), MemberDef::isPrototype(), MemberDef::isSignal(), MemberDef::isSlot(), and m_memberDef.
functionQualifier() [2/2]
TemplateVariant MemberContext::Private::functionQualifier () const [inline]
Definition at line 3709 of file context.cpp.
    {
      if (!m_memberDef->isObjCMethod() &&
          (m_memberDef->isFunction() || m_memberDef->isSlot() ||
           m_memberDef->isPrototype() || m_memberDef->isSignal()
          )
         )
      {
        return "()";
      }
      else
      {
        return "";
      }
    }
get() [1/2]
TemplateVariant MemberContext::Private::get (const QCString & n) const [inline]
Definition at line 3582 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant MemberContext::Private::get (const QCString & n) const [inline]
Definition at line 3582 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
getCallerGraph() [1/2]
DotCallGraphPtr MemberContext::Private::getCallerGraph () const [inline]
Definition at line 3698 of file context.cpp.
{ return m_cachable.callerGraph.get(this); }
References MemberContext::Private::Cachable::callerGraph, and m_cachable.
Referenced by callerGraph(), and hasCallerGraph().
getCallerGraph() [2/2]
DotCallGraphPtr MemberContext::Private::getCallerGraph () const [inline]
Definition at line 3698 of file context.cpp.
{ return m_cachable.callerGraph.get(this); }
getCallGraph() [1/2]
DotCallGraphPtr MemberContext::Private::getCallGraph () const [inline]
Definition at line 3697 of file context.cpp.
{ return m_cachable.callGraph.get(this); }
References MemberContext::Private::Cachable::callGraph, and m_cachable.
Referenced by callGraph(), and hasCallGraph().
getCallGraph() [2/2]
DotCallGraphPtr MemberContext::Private::getCallGraph () const [inline]
Definition at line 3697 of file context.cpp.
{ return m_cachable.callGraph.get(this); }
getClass() [1/2]
TemplateVariant MemberContext::Private::getClass () const [inline]
Definition at line 3672 of file context.cpp.
{ return m_cachable.classDef.get(this); }
References MemberContext::Private::Cachable::classDef, and m_cachable.
getClass() [2/2]
TemplateVariant MemberContext::Private::getClass () const [inline]
Definition at line 3672 of file context.cpp.
{ return m_cachable.classDef.get(this); }
getDefArgList() [1/2]
const ArgumentList & MemberContext::Private::getDefArgList () const [inline]
Definition at line 3703 of file context.cpp.
    {
      return (m_memberDef->isDocsForDefinition()) ?
              m_memberDef->argumentList() : m_memberDef->declArgumentList();
    }
References MemberDef::argumentList(), MemberDef::declArgumentList(), MemberDef::isDocsForDefinition(), and m_memberDef.
Referenced by createParameters(), createTrailingReturnType(), hasConstQualifier(), hasParameters(), hasRefQualifierLValue(), hasRefQualifierRValue(), and hasVolatileQualifier().
getDefArgList() [2/2]
const ArgumentList & MemberContext::Private::getDefArgList () const [inline]
Definition at line 3703 of file context.cpp.
    {
      return (m_memberDef->isDocsForDefinition()) ?
              m_memberDef->argumentList() : m_memberDef->declArgumentList();
    }
getFile() [1/2]
TemplateVariant MemberContext::Private::getFile () const [inline]
Definition at line 3675 of file context.cpp.
{ return m_cachable.fileDef.get(this); }
References MemberContext::Private::Cachable::fileDef, and m_cachable.
getFile() [2/2]
TemplateVariant MemberContext::Private::getFile () const [inline]
Definition at line 3675 of file context.cpp.
{ return m_cachable.fileDef.get(this); }
getNamespace() [1/2]
TemplateVariant MemberContext::Private::getNamespace () const [inline]
Definition at line 3676 of file context.cpp.
{ return m_cachable.namespaceDef.get(this); }
References m_cachable, and MemberContext::Private::Cachable::namespaceDef.
getNamespace() [2/2]
TemplateVariant MemberContext::Private::getNamespace () const [inline]
Definition at line 3676 of file context.cpp.
{ return m_cachable.namespaceDef.get(this); }
handleDetailsVisibleFor() [1/2]
TemplateVariant MemberContext::Private::handleDetailsVisibleFor (const TemplateVariantList & args) const [inline]
Definition at line 3840 of file context.cpp.
    {
      if (args.size()==1)
      {
        QCString containerStr = args[0].toString();
        MemberListContainer container = MemberListContainer::Class;
        if (containerStr=="module") container = MemberListContainer::Group;
        else if (containerStr=="file") container = MemberListContainer::File;
        else if (containerStr=="namespace") container = MemberListContainer::Namespace;
        return m_memberDef->isDetailedSectionVisible(container);
      }
      else
      {
        err(".detailsVisibleFor should take one string argument, got %zu\n",args.size());
      }
      return TemplateVariant();
    }
References Class, err(), File, Group, MemberDef::isDetailedSectionVisible(), m_memberDef, and Namespace.
Referenced by detailsVisibleFor().
handleDetailsVisibleFor() [2/2]
TemplateVariant MemberContext::Private::handleDetailsVisibleFor (const TemplateVariantList & args) const [inline]
Definition at line 3840 of file context.cpp.
    {
      if (args.size()==1)
      {
        QCString containerStr = args[0].toString();
        MemberListContainer container = MemberListContainer::Class;
        if (containerStr=="module") container = MemberListContainer::Group;
        else if (containerStr=="file") container = MemberListContainer::File;
        else if (containerStr=="namespace") container = MemberListContainer::Namespace;
        return m_memberDef->isDetailedSectionVisible(container);
      }
      else
      {
        err(".detailsVisibleFor should take one string argument, got %zu\n",args.size());
      }
      return TemplateVariant();
    }
References Class, err(), File, Group, and Namespace.
handleNameWithContextFor() [1/2]
TemplateVariant MemberContext::Private::handleNameWithContextFor (const TemplateVariantList & args) const [inline]
Definition at line 3861 of file context.cpp.
    {
      if (args.size()==1)
      {
        SrcLangExt lang = m_memberDef->getLanguage();
        QCString n = m_memberDef->name();
        QCString ctx = args[0].toString();
        QCString sep = getLanguageSpecificSeparator(lang,TRUE);
        if (m_memberDef->getEnumScope() && m_memberDef->livesInsideEnum())
        {
          n.prepend(m_memberDef->getEnumScope()->displayName()+sep);
        }
        if (ctx=="module" && m_memberDef->getClassDef() && !m_memberDef->isRelated())
        {
          n.prepend(m_memberDef->getClassDef()->displayName()+sep);
        }
        else if ((ctx=="module" || ctx=="file") && m_memberDef->getNamespaceDef())
        {
          n.prepend(m_memberDef->getNamespaceDef()->displayName()+sep);
        }
        return n;
      }
      else
      {
        err(".nameWithContextFor should take one string argument, got %zu\n",args.size());
      }
      return TemplateVariant();
    }
References ClassDef::displayName(), MemberDef::displayName(), NamespaceDef::displayName(), err(), MemberDef::getClassDef(), MemberDef::getEnumScope(), Definition::getLanguage(), getLanguageSpecificSeparator(), MemberDef::getNamespaceDef(), MemberDef::isRelated(), MemberDef::livesInsideEnum(), m_memberDef, n, Definition::name(), and TRUE.
Referenced by nameWithContextFor().
handleNameWithContextFor() [2/2]
TemplateVariant MemberContext::Private::handleNameWithContextFor (const TemplateVariantList & args) const [inline]
Definition at line 3861 of file context.cpp.
    {
      if (args.size()==1)
      {
        SrcLangExt lang = m_memberDef->getLanguage();
        QCString n = m_memberDef->name();
        QCString ctx = args[0].toString();
        QCString sep = getLanguageSpecificSeparator(lang,TRUE);
        if (m_memberDef->getEnumScope() && m_memberDef->livesInsideEnum())
        {
          n.prepend(m_memberDef->getEnumScope()->displayName()+sep);
        }
        if (ctx=="module" && m_memberDef->getClassDef() && !m_memberDef->isRelated())
        {
          n.prepend(m_memberDef->getClassDef()->displayName()+sep);
        }
        else if ((ctx=="module" || ctx=="file") && m_memberDef->getNamespaceDef())
        {
          n.prepend(m_memberDef->getNamespaceDef()->displayName()+sep);
        }
        return n;
      }
      else
      {
        err(".nameWithContextFor should take one string argument, got %zu\n",args.size());
      }
      return TemplateVariant();
    }
References err(), getLanguageSpecificSeparator(), n, and TRUE.
hasCallerGraph() [1/2]
TemplateVariant MemberContext::Private::hasCallerGraph () const [inline]
Definition at line 3782 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      if (m_memberDef->hasCallerGraph() && haveDot &&
          (m_memberDef->isFunction() || m_memberDef->isSlot() || m_memberDef->isSignal()))
      {
        DotCallGraphPtr cg = getCallerGraph();
        return !cg->isTooBig() && !cg->isTrivial();
      }
      return TemplateVariant(FALSE);
    }
References Config_getBool, FALSE, getCallerGraph(), MemberDef::hasCallerGraph(), MemberDef::isFunction(), MemberDef::isSignal(), MemberDef::isSlot(), and m_memberDef.
Referenced by callerGraph().
hasCallerGraph() [2/2]
TemplateVariant MemberContext::Private::hasCallerGraph () const [inline]
Definition at line 3782 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      if (m_memberDef->hasCallerGraph() && haveDot &&
          (m_memberDef->isFunction() || m_memberDef->isSlot() || m_memberDef->isSignal()))
      {
        DotCallGraphPtr cg = getCallerGraph();
        return !cg->isTooBig() && !cg->isTrivial();
      }
      return TemplateVariant(FALSE);
    }
References Config_getBool, and FALSE.
hasCallGraph() [1/2]
TemplateVariant MemberContext::Private::hasCallGraph () const [inline]
Definition at line 3724 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      if (m_memberDef->hasCallGraph() && haveDot &&
          (m_memberDef->isFunction() || m_memberDef->isSlot() || m_memberDef->isSignal()))
      {
        DotCallGraphPtr cg = getCallGraph();
        return !cg->isTooBig() && !cg->isTrivial();
      }
      return TemplateVariant(FALSE);
    }
References Config_getBool, FALSE, getCallGraph(), MemberDef::hasCallGraph(), MemberDef::isFunction(), MemberDef::isSignal(), MemberDef::isSlot(), and m_memberDef.
Referenced by callGraph().
hasCallGraph() [2/2]
TemplateVariant MemberContext::Private::hasCallGraph () const [inline]
Definition at line 3724 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      if (m_memberDef->hasCallGraph() && haveDot &&
          (m_memberDef->isFunction() || m_memberDef->isSlot() || m_memberDef->isSignal()))
      {
        DotCallGraphPtr cg = getCallGraph();
        return !cg->isTooBig() && !cg->isTrivial();
      }
      return TemplateVariant(FALSE);
    }
References Config_getBool, and FALSE.
hasConstQualifier() [1/2]
TemplateVariant MemberContext::Private::hasConstQualifier () const [inline]
Definition at line 3680 of file context.cpp.
{ return getDefArgList().constSpecifier(); }
References ArgumentList::constSpecifier(), and getDefArgList().
hasConstQualifier() [2/2]
TemplateVariant MemberContext::Private::hasConstQualifier () const [inline]
Definition at line 3680 of file context.cpp.
{ return getDefArgList().constSpecifier(); }
hasDetails() [1/2]
TemplateVariant MemberContext::Private::hasDetails () const [inline]
Definition at line 3649 of file context.cpp.
{ return m_memberDef->hasDetailedDescription(); }
References MemberDef::hasDetailedDescription(), and m_memberDef.
hasDetails() [2/2]
TemplateVariant MemberContext::Private::hasDetails () const [inline]
Definition at line 3649 of file context.cpp.
{ return m_memberDef->hasDetailedDescription(); }
hasMultiLineInitializer() [1/2]
TemplateVariant MemberContext::Private::hasMultiLineInitializer () const [inline]
Definition at line 3655 of file context.cpp.
{ return m_memberDef->hasMultiLineInitializer(); }
References MemberDef::hasMultiLineInitializer(), and m_memberDef.
hasMultiLineInitializer() [2/2]
TemplateVariant MemberContext::Private::hasMultiLineInitializer () const [inline]
Definition at line 3655 of file context.cpp.
{ return m_memberDef->hasMultiLineInitializer(); }
hasOneLineInitializer() [1/2]
TemplateVariant MemberContext::Private::hasOneLineInitializer () const [inline]
Definition at line 3654 of file context.cpp.
{ return m_memberDef->hasOneLineInitializer(); }
References MemberDef::hasOneLineInitializer(), and m_memberDef.
hasOneLineInitializer() [2/2]
TemplateVariant MemberContext::Private::hasOneLineInitializer () const [inline]
Definition at line 3654 of file context.cpp.
{ return m_memberDef->hasOneLineInitializer(); }
hasParameters() [1/2]
TemplateVariant MemberContext::Private::hasParameters () const [inline]
Definition at line 3679 of file context.cpp.
{ return !getDefArgList().empty(); }
References ArgumentList::empty(), and getDefArgList().
hasParameters() [2/2]
TemplateVariant MemberContext::Private::hasParameters () const [inline]
Definition at line 3679 of file context.cpp.
{ return !getDefArgList().empty(); }
hasReferencedByRelation() [1/2]
TemplateVariant MemberContext::Private::hasReferencedByRelation () const [inline]
Definition at line 3700 of file context.cpp.
{ return TemplateVariant(m_memberDef->hasReferencedByRelation()); }
References MemberDef::hasReferencedByRelation(), and m_memberDef.
Referenced by referencedByRelation().
hasReferencedByRelation() [2/2]
TemplateVariant MemberContext::Private::hasReferencedByRelation () const [inline]
Definition at line 3700 of file context.cpp.
{ return TemplateVariant(m_memberDef->hasReferencedByRelation()); }
hasReferencesRelation() [1/2]
TemplateVariant MemberContext::Private::hasReferencesRelation () const [inline]
Definition at line 3701 of file context.cpp.
{ return TemplateVariant(m_memberDef->hasReferencesRelation()); }
References MemberDef::hasReferencesRelation(), and m_memberDef.
Referenced by referencesRelation().
hasReferencesRelation() [2/2]
TemplateVariant MemberContext::Private::hasReferencesRelation () const [inline]
Definition at line 3701 of file context.cpp.
{ return TemplateVariant(m_memberDef->hasReferencesRelation()); }
hasRefQualifierLValue() [1/2]
TemplateVariant MemberContext::Private::hasRefQualifierLValue () const [inline]
Definition at line 3682 of file context.cpp.
{ return getDefArgList().refQualifier()==RefQualifierLValue; }
References getDefArgList(), ArgumentList::refQualifier(), and RefQualifierLValue.
hasRefQualifierLValue() [2/2]
TemplateVariant MemberContext::Private::hasRefQualifierLValue () const [inline]
Definition at line 3682 of file context.cpp.
{ return getDefArgList().refQualifier()==RefQualifierLValue; }
References RefQualifierLValue.
hasRefQualifierRValue() [1/2]
TemplateVariant MemberContext::Private::hasRefQualifierRValue () const [inline]
Definition at line 3683 of file context.cpp.
{ return getDefArgList().refQualifier()==RefQualifierRValue; }
References getDefArgList(), ArgumentList::refQualifier(), and RefQualifierRValue.
hasRefQualifierRValue() [2/2]
TemplateVariant MemberContext::Private::hasRefQualifierRValue () const [inline]
Definition at line 3683 of file context.cpp.
{ return getDefArgList().refQualifier()==RefQualifierRValue; }
References RefQualifierRValue.
hasSources() [1/2]
TemplateVariant MemberContext::Private::hasSources () const [inline]
Definition at line 3699 of file context.cpp.
{ return TemplateVariant(m_memberDef->hasSources()); }
References Definition::hasSources(), and m_memberDef.
hasSources() [2/2]
TemplateVariant MemberContext::Private::hasSources () const [inline]
Definition at line 3699 of file context.cpp.
{ return TemplateVariant(m_memberDef->hasSources()); }
hasVolatileQualifier() [1/2]
TemplateVariant MemberContext::Private::hasVolatileQualifier () const [inline]
Definition at line 3681 of file context.cpp.
{ return getDefArgList().volatileSpecifier(); }
References getDefArgList(), and ArgumentList::volatileSpecifier().
hasVolatileQualifier() [2/2]
TemplateVariant MemberContext::Private::hasVolatileQualifier () const [inline]
Definition at line 3681 of file context.cpp.
{ return getDefArgList().volatileSpecifier(); }
implementedBy() [1/2]
TemplateVariant MemberContext::Private::implementedBy () const [inline]
Definition at line 3690 of file context.cpp.
{ return m_cachable.implementedBy.get(this); }
References MemberContext::Private::Cachable::implementedBy, and m_cachable.
implementedBy() [2/2]
TemplateVariant MemberContext::Private::implementedBy () const [inline]
Definition at line 3690 of file context.cpp.
{ return m_cachable.implementedBy.get(this); }
implements() [1/2]
TemplateVariant MemberContext::Private::implements () const [inline]
Definition at line 3688 of file context.cpp.
{ return m_cachable.implements.get(this); }
References MemberContext::Private::Cachable::implements, and m_cachable.
implements() [2/2]
TemplateVariant MemberContext::Private::implements () const [inline]
Definition at line 3688 of file context.cpp.
{ return m_cachable.implements.get(this); }
initializer() [1/2]
TemplateVariant MemberContext::Private::initializer () const [inline]
Definition at line 3663 of file context.cpp.
{ return m_cachable.initializer.get(this); }
References MemberContext::Private::Cachable::initializer, and m_cachable.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
initializer() [2/2]
TemplateVariant MemberContext::Private::initializer () const [inline]
Definition at line 3663 of file context.cpp.
{ return m_cachable.initializer.get(this); }
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
initializerAsCode() [1/2]
TemplateVariant MemberContext::Private::initializerAsCode () const [inline]
Definition at line 3664 of file context.cpp.
{ return m_cachable.initializerAsCode.get(this); }
References MemberContext::Private::Cachable::initializerAsCode, and m_cachable.
initializerAsCode() [2/2]
TemplateVariant MemberContext::Private::initializerAsCode () const [inline]
Definition at line 3664 of file context.cpp.
{ return m_cachable.initializerAsCode.get(this); }
isAbstract() [1/2]
TemplateVariant MemberContext::Private::isAbstract () const [inline]
Definition at line 3614 of file context.cpp.
{ return m_memberDef->isAbstract(); }
References MemberDef::isAbstract(), and m_memberDef.
isAbstract() [2/2]
TemplateVariant MemberContext::Private::isAbstract () const [inline]
Definition at line 3614 of file context.cpp.
{ return m_memberDef->isAbstract(); }
isAddable() [1/2]
TemplateVariant MemberContext::Private::isAddable () const [inline]
Definition at line 3610 of file context.cpp.
{ return m_memberDef->isAddable(); }
References MemberDef::isAddable(), and m_memberDef.
isAddable() [2/2]
TemplateVariant MemberContext::Private::isAddable () const [inline]
Definition at line 3610 of file context.cpp.
{ return m_memberDef->isAddable(); }
isAnonymous() [1/2]
TemplateVariant MemberContext::Private::isAnonymous () const [inline]
Definition at line 3651 of file context.cpp.
{ return m_memberDef->isAnonymous(); }
References Definition::isAnonymous(), and m_memberDef.
isAnonymous() [2/2]
TemplateVariant MemberContext::Private::isAnonymous () const [inline]
Definition at line 3651 of file context.cpp.
{ return m_memberDef->isAnonymous(); }
isAssign() [1/2]
TemplateVariant MemberContext::Private::isAssign () const [inline]
Definition at line 3621 of file context.cpp.
{ return m_memberDef->isAssign(); }
References MemberDef::isAssign(), and m_memberDef.
isAssign() [2/2]
TemplateVariant MemberContext::Private::isAssign () const [inline]
Definition at line 3621 of file context.cpp.
{ return m_memberDef->isAssign(); }
isAttribute() [1/2]
TemplateVariant MemberContext::Private::isAttribute () const [inline]
Definition at line 3634 of file context.cpp.
{ return m_memberDef->isAttribute(); }
References MemberDef::isAttribute(), and m_memberDef.
isAttribute() [2/2]
TemplateVariant MemberContext::Private::isAttribute () const [inline]
Definition at line 3634 of file context.cpp.
{ return m_memberDef->isAttribute(); }
isBound() [1/2]
TemplateVariant MemberContext::Private::isBound () const [inline]
Definition at line 3637 of file context.cpp.
{ return m_memberDef->isBound(); }
References MemberDef::isBound(), and m_memberDef.
isBound() [2/2]
TemplateVariant MemberContext::Private::isBound () const [inline]
Definition at line 3637 of file context.cpp.
{ return m_memberDef->isBound(); }
isConstrained() [1/2]
TemplateVariant MemberContext::Private::isConstrained () const [inline]
Definition at line 3638 of file context.cpp.
{ return m_memberDef->isConstrained(); }
References MemberDef::isConstrained(), and m_memberDef.
isConstrained() [2/2]
TemplateVariant MemberContext::Private::isConstrained () const [inline]
Definition at line 3638 of file context.cpp.
{ return m_memberDef->isConstrained(); }
isCopy() [1/2]
TemplateVariant MemberContext::Private::isCopy () const [inline]
Definition at line 3620 of file context.cpp.
{ return m_memberDef->isCopy(); }
References MemberDef::isCopy(), and m_memberDef.
isCopy() [2/2]
TemplateVariant MemberContext::Private::isCopy () const [inline]
Definition at line 3620 of file context.cpp.
{ return m_memberDef->isCopy(); }
isCSharpProperty() [1/2]
TemplateVariant MemberContext::Private::isCSharpProperty () const [inline]
Definition at line 3589 of file context.cpp.
{ return m_memberDef->isCSharpProperty(); }
References MemberDef::isCSharpProperty(), and m_memberDef.
isCSharpProperty() [2/2]
TemplateVariant MemberContext::Private::isCSharpProperty () const [inline]
Definition at line 3589 of file context.cpp.
{ return m_memberDef->isCSharpProperty(); }
isDefault() [1/2]
TemplateVariant MemberContext::Private::isDefault () const [inline]
Definition at line 3631 of file context.cpp.
{ return m_memberDef->isDefault(); }
References MemberDef::isDefault(), and m_memberDef.
isDefault() [2/2]
TemplateVariant MemberContext::Private::isDefault () const [inline]
Definition at line 3631 of file context.cpp.
{ return m_memberDef->isDefault(); }
isDefine() [1/2]
TemplateVariant MemberContext::Private::isDefine () const [inline]
Definition at line 3650 of file context.cpp.
{ return m_memberDef->isDefine(); }
References MemberDef::isDefine(), and m_memberDef.
isDefine() [2/2]
TemplateVariant MemberContext::Private::isDefine () const [inline]
Definition at line 3650 of file context.cpp.
{ return m_memberDef->isDefine(); }
isDelete() [1/2]
TemplateVariant MemberContext::Private::isDelete () const [inline]
Definition at line 3632 of file context.cpp.
{ return m_memberDef->isDelete(); }
References MemberDef::isDelete(), and m_memberDef.
isDelete() [2/2]
TemplateVariant MemberContext::Private::isDelete () const [inline]
Definition at line 3632 of file context.cpp.
{ return m_memberDef->isDelete(); }
isEnumeration() [1/2]
TemplateVariant MemberContext::Private::isEnumeration () const [inline]
Definition at line 3648 of file context.cpp.
{ return m_memberDef->isEnumerate(); }
References MemberDef::isEnumerate(), and m_memberDef.
isEnumeration() [2/2]
TemplateVariant MemberContext::Private::isEnumeration () const [inline]
Definition at line 3648 of file context.cpp.
{ return m_memberDef->isEnumerate(); }
isEnumStruct() [1/2]
TemplateVariant MemberContext::Private::isEnumStruct () const [inline]
Definition at line 3625 of file context.cpp.
{ return m_memberDef->isEnumStruct(); }
References MemberDef::isEnumStruct(), and m_memberDef.
isEnumStruct() [2/2]
TemplateVariant MemberContext::Private::isEnumStruct () const [inline]
Definition at line 3625 of file context.cpp.
{ return m_memberDef->isEnumStruct(); }
isEnumValue() [1/2]
TemplateVariant MemberContext::Private::isEnumValue () const [inline]
Definition at line 3646 of file context.cpp.
{ return m_memberDef->isEnumValue(); }
References MemberDef::isEnumValue(), and m_memberDef.
isEnumValue() [2/2]
TemplateVariant MemberContext::Private::isEnumValue () const [inline]
Definition at line 3646 of file context.cpp.
{ return m_memberDef->isEnumValue(); }
isEvent() [1/2]
TemplateVariant MemberContext::Private::isEvent () const [inline]
Definition at line 3598 of file context.cpp.
{ return m_memberDef->isEvent(); }
References MemberDef::isEvent(), and m_memberDef.
isEvent() [2/2]
TemplateVariant MemberContext::Private::isEvent () const [inline]
Definition at line 3598 of file context.cpp.
{ return m_memberDef->isEvent(); }
isExplicit() [1/2]
TemplateVariant MemberContext::Private::isExplicit () const [inline]
Definition at line 3600 of file context.cpp.
{ return m_memberDef->isExplicit(); }
References MemberDef::isExplicit(), and m_memberDef.
isExplicit() [2/2]
TemplateVariant MemberContext::Private::isExplicit () const [inline]
Definition at line 3600 of file context.cpp.
{ return m_memberDef->isExplicit(); }
isExternal() [1/2]
TemplateVariant MemberContext::Private::isExternal () const [inline]
Definition at line 3629 of file context.cpp.
{ return m_memberDef->isExternal(); }
References MemberDef::isExternal(), and m_memberDef.
isExternal() [2/2]
TemplateVariant MemberContext::Private::isExternal () const [inline]
Definition at line 3629 of file context.cpp.
{ return m_memberDef->isExternal(); }
isFinal() [1/2]
TemplateVariant MemberContext::Private::isFinal () const [inline]
Definition at line 3613 of file context.cpp.
{ return m_memberDef->isFinal(); }
References MemberDef::isFinal(), and m_memberDef.
isFinal() [2/2]
TemplateVariant MemberContext::Private::isFinal () const [inline]
Definition at line 3613 of file context.cpp.
{ return m_memberDef->isFinal(); }
isForeign() [1/2]
TemplateVariant MemberContext::Private::isForeign () const [inline]
Definition at line 3597 of file context.cpp.
{ return m_memberDef->isForeign(); }
References MemberDef::isForeign(), and m_memberDef.
isForeign() [2/2]
TemplateVariant MemberContext::Private::isForeign () const [inline]
Definition at line 3597 of file context.cpp.
{ return m_memberDef->isForeign(); }
isFriend() [1/2]
TemplateVariant MemberContext::Private::isFriend () const [inline]
Definition at line 3596 of file context.cpp.
{ return m_memberDef->isFriend(); }
References MemberDef::isFriend(), and m_memberDef.
isFriend() [2/2]
TemplateVariant MemberContext::Private::isFriend () const [inline]
Definition at line 3596 of file context.cpp.
{ return m_memberDef->isFriend(); }
isFunction() [1/2]
TemplateVariant MemberContext::Private::isFunction () const [inline]
Definition at line 3594 of file context.cpp.
{ return m_memberDef->isFunction(); }
References MemberDef::isFunction(), and m_memberDef.
isFunction() [2/2]
TemplateVariant MemberContext::Private::isFunction () const [inline]
Definition at line 3594 of file context.cpp.
{ return m_memberDef->isFunction(); }
References TemplateVariant::isFunction().
isFunctionPtr() [1/2]
TemplateVariant MemberContext::Private::isFunctionPtr () const [inline]
Definition at line 3595 of file context.cpp.
{ return m_memberDef->isFunctionPtr(); }
References MemberDef::isFunctionPtr(), and m_memberDef.
isFunctionPtr() [2/2]
TemplateVariant MemberContext::Private::isFunctionPtr () const [inline]
Definition at line 3595 of file context.cpp.
{ return m_memberDef->isFunctionPtr(); }
isGettable() [1/2]
TemplateVariant MemberContext::Private::isGettable () const [inline]
Definition at line 3602 of file context.cpp.
{ return m_memberDef->isGettable(); }
References MemberDef::isGettable(), and m_memberDef.
isGettable() [2/2]
TemplateVariant MemberContext::Private::isGettable () const [inline]
Definition at line 3602 of file context.cpp.
{ return m_memberDef->isGettable(); }
isImplementation() [1/2]
TemplateVariant MemberContext::Private::isImplementation () const [inline]
Definition at line 3590 of file context.cpp.
{ return m_memberDef->isImplementation(); }
References MemberDef::isImplementation(), and m_memberDef.
isImplementation() [2/2]
TemplateVariant MemberContext::Private::isImplementation () const [inline]
Definition at line 3590 of file context.cpp.
{ return m_memberDef->isImplementation(); }
isInitonly() [1/2]
TemplateVariant MemberContext::Private::isInitonly () const [inline]
Definition at line 3616 of file context.cpp.
{ return m_memberDef->isInitonly(); }
References MemberDef::isInitonly(), and m_memberDef.
isInitonly() [2/2]
TemplateVariant MemberContext::Private::isInitonly () const [inline]
Definition at line 3616 of file context.cpp.
{ return m_memberDef->isInitonly(); }
isInline() [1/2]
TemplateVariant MemberContext::Private::isInline () const [inline]
Definition at line 3599 of file context.cpp.
{ return m_memberDef->isInline(); }
References MemberDef::isInline(), and m_memberDef.
isInline() [2/2]
TemplateVariant MemberContext::Private::isInline () const [inline]
Definition at line 3599 of file context.cpp.
{ return m_memberDef->isInline(); }
isMaybeAmbiguous() [1/2]
TemplateVariant MemberContext::Private::isMaybeAmbiguous () const [inline]
Definition at line 3642 of file context.cpp.
{ return m_memberDef->isMaybeAmbiguous(); }
References MemberDef::isMaybeAmbiguous(), and m_memberDef.
isMaybeAmbiguous() [2/2]
TemplateVariant MemberContext::Private::isMaybeAmbiguous () const [inline]
Definition at line 3642 of file context.cpp.
{ return m_memberDef->isMaybeAmbiguous(); }
isMaybeDefault() [1/2]
TemplateVariant MemberContext::Private::isMaybeDefault () const [inline]
Definition at line 3641 of file context.cpp.
{ return m_memberDef->isMaybeDefault(); }
References MemberDef::isMaybeDefault(), and m_memberDef.
isMaybeDefault() [2/2]
TemplateVariant MemberContext::Private::isMaybeDefault () const [inline]
Definition at line 3641 of file context.cpp.
{ return m_memberDef->isMaybeDefault(); }
isMaybeVoid() [1/2]
TemplateVariant MemberContext::Private::isMaybeVoid () const [inline]
Definition at line 3640 of file context.cpp.
{ return m_memberDef->isMaybeVoid(); }
References MemberDef::isMaybeVoid(), and m_memberDef.
isMaybeVoid() [2/2]
TemplateVariant MemberContext::Private::isMaybeVoid () const [inline]
Definition at line 3640 of file context.cpp.
{ return m_memberDef->isMaybeVoid(); }
isMutable() [1/2]
TemplateVariant MemberContext::Private::isMutable () const [inline]
Definition at line 3601 of file context.cpp.
{ return m_memberDef->isMutable(); }
References MemberDef::isMutable(), and m_memberDef.
isMutable() [2/2]
TemplateVariant MemberContext::Private::isMutable () const [inline]
Definition at line 3601 of file context.cpp.
{ return m_memberDef->isMutable(); }
isNew() [1/2]
TemplateVariant MemberContext::Private::isNew () const [inline]
Definition at line 3627 of file context.cpp.
{ return m_memberDef->isNew(); }
References MemberDef::isNew(), and m_memberDef.
isNew() [2/2]
TemplateVariant MemberContext::Private::isNew () const [inline]
Definition at line 3627 of file context.cpp.
{ return m_memberDef->isNew(); }
isNoExcept() [1/2]
TemplateVariant MemberContext::Private::isNoExcept () const [inline]
Definition at line 3633 of file context.cpp.
{ return m_memberDef->isNoExcept(); }
References MemberDef::isNoExcept(), and m_memberDef.
isNoExcept() [2/2]
TemplateVariant MemberContext::Private::isNoExcept () const [inline]
Definition at line 3633 of file context.cpp.
{ return m_memberDef->isNoExcept(); }
isNonAtomic() [1/2]
TemplateVariant MemberContext::Private::isNonAtomic () const [inline]
Definition at line 3619 of file context.cpp.
{ return m_memberDef->isNonAtomic(); }
References MemberDef::isNonAtomic(), and m_memberDef.
isNonAtomic() [2/2]
TemplateVariant MemberContext::Private::isNonAtomic () const [inline]
Definition at line 3619 of file context.cpp.
{ return m_memberDef->isNonAtomic(); }
isObjCMethod() [1/2]
TemplateVariant MemberContext::Private::isObjCMethod () const [inline]
Definition at line 3587 of file context.cpp.
{ return m_memberDef->isObjCMethod(); }
References MemberDef::isObjCMethod(), and m_memberDef.
isObjCMethod() [2/2]
TemplateVariant MemberContext::Private::isObjCMethod () const [inline]
Definition at line 3587 of file context.cpp.
{ return m_memberDef->isObjCMethod(); }
isObjCProperty() [1/2]
TemplateVariant MemberContext::Private::isObjCProperty () const [inline]
Definition at line 3588 of file context.cpp.
{ return m_memberDef->isObjCProperty(); }
References MemberDef::isObjCProperty(), and m_memberDef.
isObjCProperty() [2/2]
TemplateVariant MemberContext::Private::isObjCProperty () const [inline]
Definition at line 3588 of file context.cpp.
{ return m_memberDef->isObjCProperty(); }
isOptional() [1/2]
TemplateVariant MemberContext::Private::isOptional () const [inline]
Definition at line 3617 of file context.cpp.
{ return m_memberDef->isOptional(); }
References MemberDef::isOptional(), and m_memberDef.
isOptional() [2/2]
TemplateVariant MemberContext::Private::isOptional () const [inline]
Definition at line 3617 of file context.cpp.
{ return m_memberDef->isOptional(); }
isOverride() [1/2]
TemplateVariant MemberContext::Private::isOverride () const [inline]
Definition at line 3615 of file context.cpp.
{ return m_memberDef->isOverride(); }
References MemberDef::isOverride(), and m_memberDef.
isOverride() [2/2]
TemplateVariant MemberContext::Private::isOverride () const [inline]
Definition at line 3615 of file context.cpp.
{ return m_memberDef->isOverride(); }
isPrivateGettable() [1/2]
TemplateVariant MemberContext::Private::isPrivateGettable () const [inline]
Definition at line 3603 of file context.cpp.
{ return m_memberDef->isPrivateGettable(); }
References MemberDef::isPrivateGettable(), and m_memberDef.
isPrivateGettable() [2/2]
TemplateVariant MemberContext::Private::isPrivateGettable () const [inline]
Definition at line 3603 of file context.cpp.
{ return m_memberDef->isPrivateGettable(); }
isPrivateSettable() [1/2]
TemplateVariant MemberContext::Private::isPrivateSettable () const [inline]
Definition at line 3606 of file context.cpp.
{ return m_memberDef->isPrivateSettable(); }
References MemberDef::isPrivateSettable(), and m_memberDef.
isPrivateSettable() [2/2]
TemplateVariant MemberContext::Private::isPrivateSettable () const [inline]
Definition at line 3606 of file context.cpp.
{ return m_memberDef->isPrivateSettable(); }
isProperty() [1/2]
TemplateVariant MemberContext::Private::isProperty () const [inline]
Definition at line 3645 of file context.cpp.
{ return m_memberDef->isProperty(); }
References MemberDef::isProperty(), and m_memberDef.
isProperty() [2/2]
TemplateVariant MemberContext::Private::isProperty () const [inline]
Definition at line 3645 of file context.cpp.
{ return m_memberDef->isProperty(); }
isProtectedGettable() [1/2]
TemplateVariant MemberContext::Private::isProtectedGettable () const [inline]
Definition at line 3604 of file context.cpp.
{ return m_memberDef->isProtectedGettable(); }
References MemberDef::isProtectedGettable(), and m_memberDef.
isProtectedGettable() [2/2]
TemplateVariant MemberContext::Private::isProtectedGettable () const [inline]
Definition at line 3604 of file context.cpp.
{ return m_memberDef->isProtectedGettable(); }
isProtectedSettable() [1/2]
TemplateVariant MemberContext::Private::isProtectedSettable () const [inline]
Definition at line 3607 of file context.cpp.
{ return m_memberDef->isProtectedSettable(); }
References MemberDef::isProtectedSettable(), and m_memberDef.
isProtectedSettable() [2/2]
TemplateVariant MemberContext::Private::isProtectedSettable () const [inline]
Definition at line 3607 of file context.cpp.
{ return m_memberDef->isProtectedSettable(); }
isPublished() [1/2]
TemplateVariant MemberContext::Private::isPublished () const [inline]
Definition at line 3643 of file context.cpp.
{ return m_memberDef->isPublished(); }
References MemberDef::isPublished(), and m_memberDef.
isPublished() [2/2]
TemplateVariant MemberContext::Private::isPublished () const [inline]
Definition at line 3643 of file context.cpp.
{ return m_memberDef->isPublished(); }
isRaisable() [1/2]
TemplateVariant MemberContext::Private::isRaisable () const [inline]
Definition at line 3612 of file context.cpp.
{ return m_memberDef->isRaisable(); }
References MemberDef::isRaisable(), and m_memberDef.
isRaisable() [2/2]
TemplateVariant MemberContext::Private::isRaisable () const [inline]
Definition at line 3612 of file context.cpp.
{ return m_memberDef->isRaisable(); }
isReadable() [1/2]
TemplateVariant MemberContext::Private::isReadable () const [inline]
Definition at line 3608 of file context.cpp.
{ return m_memberDef->isReadable(); }
References MemberDef::isReadable(), and m_memberDef.
isReadable() [2/2]
TemplateVariant MemberContext::Private::isReadable () const [inline]
Definition at line 3608 of file context.cpp.
{ return m_memberDef->isReadable(); }
isReadonly() [1/2]
TemplateVariant MemberContext::Private::isReadonly () const [inline]
Definition at line 3636 of file context.cpp.
{ return m_memberDef->isReadonly(); }
References MemberDef::isReadonly(), and m_memberDef.
isReadonly() [2/2]
TemplateVariant MemberContext::Private::isReadonly () const [inline]
Definition at line 3636 of file context.cpp.
{ return m_memberDef->isReadonly(); }
isRelated() [1/2]
TemplateVariant MemberContext::Private::isRelated () const [inline]
Definition at line 3652 of file context.cpp.
{ return m_memberDef->isRelated(); }
References MemberDef::isRelated(), and m_memberDef.
isRelated() [2/2]
TemplateVariant MemberContext::Private::isRelated () const [inline]
Definition at line 3652 of file context.cpp.
{ return m_memberDef->isRelated(); }
isRemovable() [1/2]
TemplateVariant MemberContext::Private::isRemovable () const [inline]
Definition at line 3611 of file context.cpp.
{ return m_memberDef->isRemovable(); }
References MemberDef::isRemovable(), and m_memberDef.
isRemovable() [2/2]
TemplateVariant MemberContext::Private::isRemovable () const [inline]
Definition at line 3611 of file context.cpp.
{ return m_memberDef->isRemovable(); }
isRequired() [1/2]
TemplateVariant MemberContext::Private::isRequired () const [inline]
Definition at line 3618 of file context.cpp.
{ return m_memberDef->isRequired(); }
References MemberDef::isRequired(), and m_memberDef.
isRequired() [2/2]
TemplateVariant MemberContext::Private::isRequired () const [inline]
Definition at line 3618 of file context.cpp.
{ return m_memberDef->isRequired(); }
isRetain() [1/2]
TemplateVariant MemberContext::Private::isRetain () const [inline]
Definition at line 3622 of file context.cpp.
{ return m_memberDef->isRetain(); }
References MemberDef::isRetain(), and m_memberDef.
isRetain() [2/2]
TemplateVariant MemberContext::Private::isRetain () const [inline]
Definition at line 3622 of file context.cpp.
{ return m_memberDef->isRetain(); }
isSealed() [1/2]
TemplateVariant MemberContext::Private::isSealed () const [inline]
Definition at line 3628 of file context.cpp.
{ return m_memberDef->isSealed(); }
References MemberDef::isSealed(), and m_memberDef.
isSealed() [2/2]
TemplateVariant MemberContext::Private::isSealed () const [inline]
Definition at line 3628 of file context.cpp.
{ return m_memberDef->isSealed(); }
isSettable() [1/2]
TemplateVariant MemberContext::Private::isSettable () const [inline]
Definition at line 3605 of file context.cpp.
{ return m_memberDef->isSettable(); }
References MemberDef::isSettable(), and m_memberDef.
isSettable() [2/2]
TemplateVariant MemberContext::Private::isSettable () const [inline]
Definition at line 3605 of file context.cpp.
{ return m_memberDef->isSettable(); }
isSignal() [1/2]
TemplateVariant MemberContext::Private::isSignal () const [inline]
Definition at line 3591 of file context.cpp.
{ return m_memberDef->isSignal(); }
References MemberDef::isSignal(), and m_memberDef.
isSignal() [2/2]
TemplateVariant MemberContext::Private::isSignal () const [inline]
Definition at line 3591 of file context.cpp.
{ return m_memberDef->isSignal(); }
isSlot() [1/2]
TemplateVariant MemberContext::Private::isSlot () const [inline]
Definition at line 3592 of file context.cpp.
{ return m_memberDef->isSlot(); }
References MemberDef::isSlot(), and m_memberDef.
isSlot() [2/2]
TemplateVariant MemberContext::Private::isSlot () const [inline]
Definition at line 3592 of file context.cpp.
{ return m_memberDef->isSlot(); }
isStatic() [1/2]
TemplateVariant MemberContext::Private::isStatic () const [inline]
Definition at line 3586 of file context.cpp.
{ return m_memberDef->isStatic(); }
References MemberDef::isStatic(), and m_memberDef.
isStatic() [2/2]
TemplateVariant MemberContext::Private::isStatic () const [inline]
Definition at line 3586 of file context.cpp.
{ return m_memberDef->isStatic(); }
isStrong() [1/2]
TemplateVariant MemberContext::Private::isStrong () const [inline]
Definition at line 3624 of file context.cpp.
{ return m_memberDef->isStrong(); }
References MemberDef::isStrong(), and m_memberDef.
isStrong() [2/2]
TemplateVariant MemberContext::Private::isStrong () const [inline]
Definition at line 3624 of file context.cpp.
{ return m_memberDef->isStrong(); }
isTemplateSpecialization() [1/2]
TemplateVariant MemberContext::Private::isTemplateSpecialization () const [inline]
Definition at line 3644 of file context.cpp.
{ return m_memberDef->isTemplateSpecialization(); }
References MemberDef::isTemplateSpecialization(), and m_memberDef.
isTemplateSpecialization() [2/2]
TemplateVariant MemberContext::Private::isTemplateSpecialization () const [inline]
Definition at line 3644 of file context.cpp.
{ return m_memberDef->isTemplateSpecialization(); }
isTransient() [1/2]
TemplateVariant MemberContext::Private::isTransient () const [inline]
Definition at line 3639 of file context.cpp.
{ return m_memberDef->isTransient(); }
References MemberDef::isTransient(), and m_memberDef.
isTransient() [2/2]
TemplateVariant MemberContext::Private::isTransient () const [inline]
Definition at line 3639 of file context.cpp.
{ return m_memberDef->isTransient(); }
isTypeAlias() [1/2]
TemplateVariant MemberContext::Private::isTypeAlias () const [inline]
Definition at line 3630 of file context.cpp.
{ return m_memberDef->isTypeAlias(); }
References MemberDef::isTypeAlias(), and m_memberDef.
isTypeAlias() [2/2]
TemplateVariant MemberContext::Private::isTypeAlias () const [inline]
Definition at line 3630 of file context.cpp.
{ return m_memberDef->isTypeAlias(); }
isTypedef() [1/2]
TemplateVariant MemberContext::Private::isTypedef () const [inline]
Definition at line 3593 of file context.cpp.
{ return m_memberDef->isTypedef(); }
References MemberDef::isTypedef(), and m_memberDef.
isTypedef() [2/2]
TemplateVariant MemberContext::Private::isTypedef () const [inline]
Definition at line 3593 of file context.cpp.
{ return m_memberDef->isTypedef(); }
isUNOProperty() [1/2]
TemplateVariant MemberContext::Private::isUNOProperty () const [inline]
Definition at line 3635 of file context.cpp.
{ return m_memberDef->isUNOProperty(); }
References MemberDef::isUNOProperty(), and m_memberDef.
isUNOProperty() [2/2]
TemplateVariant MemberContext::Private::isUNOProperty () const [inline]
Definition at line 3635 of file context.cpp.
{ return m_memberDef->isUNOProperty(); }
isUnretained() [1/2]
TemplateVariant MemberContext::Private::isUnretained () const [inline]
Definition at line 3626 of file context.cpp.
{ return m_memberDef->isUnretained(); }
References MemberDef::isUnretained(), and m_memberDef.
isUnretained() [2/2]
TemplateVariant MemberContext::Private::isUnretained () const [inline]
Definition at line 3626 of file context.cpp.
{ return m_memberDef->isUnretained(); }
isVariable() [1/2]
TemplateVariant MemberContext::Private::isVariable () const [inline]
Definition at line 3647 of file context.cpp.
{ return m_memberDef->isVariable(); }
References MemberDef::isVariable(), and m_memberDef.
isVariable() [2/2]
TemplateVariant MemberContext::Private::isVariable () const [inline]
Definition at line 3647 of file context.cpp.
{ return m_memberDef->isVariable(); }
isWeak() [1/2]
TemplateVariant MemberContext::Private::isWeak () const [inline]
Definition at line 3623 of file context.cpp.
{ return m_memberDef->isWeak(); }
References MemberDef::isWeak(), and m_memberDef.
isWeak() [2/2]
TemplateVariant MemberContext::Private::isWeak () const [inline]
Definition at line 3623 of file context.cpp.
{ return m_memberDef->isWeak(); }
isWritable() [1/2]
TemplateVariant MemberContext::Private::isWritable () const [inline]
Definition at line 3609 of file context.cpp.
{ return m_memberDef->isWritable(); }
References MemberDef::isWritable(), and m_memberDef.
isWritable() [2/2]
TemplateVariant MemberContext::Private::isWritable () const [inline]
Definition at line 3609 of file context.cpp.
{ return m_memberDef->isWritable(); }
labels() [1/2]
TemplateVariant MemberContext::Private::labels () const [inline]
Definition at line 3686 of file context.cpp.
{ return m_cachable.labels.get(this); }
References MemberContext::Private::Cachable::labels, and m_cachable.
labels() [2/2]
TemplateVariant MemberContext::Private::labels () const [inline]
Definition at line 3686 of file context.cpp.
{ return m_cachable.labels.get(this); }
nameWithContextFor() [1/2]
TemplateVariant MemberContext::Private::nameWithContextFor () const [inline]
Definition at line 3889 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleNameWithContextFor,this,std::placeholders::_1));
    }
References handleNameWithContextFor().
nameWithContextFor() [2/2]
TemplateVariant MemberContext::Private::nameWithContextFor () const [inline]
Definition at line 3889 of file context.cpp.
    {
      return TemplateVariant(std::bind(&Private::handleNameWithContextFor,this,std::placeholders::_1));
    }
paramDocs() [1/2]
TemplateVariant MemberContext::Private::paramDocs () const [inline]
Definition at line 3687 of file context.cpp.
{ return m_cachable.paramDocs.get(this); }
References m_cachable, and MemberContext::Private::Cachable::paramDocs.
Referenced by createParamDocs().
paramDocs() [2/2]
TemplateVariant MemberContext::Private::paramDocs () const [inline]
Definition at line 3687 of file context.cpp.
{ return m_cachable.paramDocs.get(this); }
parameters() [1/2]
TemplateVariant MemberContext::Private::parameters () const [inline]
Definition at line 3678 of file context.cpp.
{ return m_cachable.parameters.get(this); }
References m_cachable, and MemberContext::Private::Cachable::parameters.
parameters() [2/2]
TemplateVariant MemberContext::Private::parameters () const [inline]
Definition at line 3678 of file context.cpp.
{ return m_cachable.parameters.get(this); }
propertyAttrs() [1/2]
TemplateVariant MemberContext::Private::propertyAttrs () const [inline]
Definition at line 3670 of file context.cpp.
{ return m_cachable.propertyAttrs.get(this); }
References m_cachable, and MemberContext::Private::Cachable::propertyAttrs.
propertyAttrs() [2/2]
TemplateVariant MemberContext::Private::propertyAttrs () const [inline]
Definition at line 3670 of file context.cpp.
{ return m_cachable.propertyAttrs.get(this); }
referencedByRelation() [1/2]
TemplateVariant MemberContext::Private::referencedByRelation () const [inline]
Definition at line 3774 of file context.cpp.
    {
      if (hasReferencedByRelation().toBool())
      {
        err("context.cpp: referencedByRelation not yet implemented\n");
      }
      return TemplateVariant("");
    }
References err(), and hasReferencedByRelation().
referencedByRelation() [2/2]
TemplateVariant MemberContext::Private::referencedByRelation () const [inline]
Definition at line 3774 of file context.cpp.
    {
      if (hasReferencedByRelation().toBool())
      {
        err("context.cpp: referencedByRelation not yet implemented\n");
      }
      return TemplateVariant("");
    }
References err().
referencesRelation() [1/2]
TemplateVariant MemberContext::Private::referencesRelation () const [inline]
Definition at line 3832 of file context.cpp.
    {
      if (hasReferencesRelation().toBool())
      {
         err("context.cpp: referencesRelation not yet implemented\n");
      }
      return TemplateVariant("");
    }
References err(), and hasReferencesRelation().
referencesRelation() [2/2]
TemplateVariant MemberContext::Private::referencesRelation () const [inline]
Definition at line 3832 of file context.cpp.
    {
      if (hasReferencesRelation().toBool())
      {
         err("context.cpp: referencesRelation not yet implemented\n");
      }
      return TemplateVariant("");
    }
References err().
reimplementedBy() [1/2]
TemplateVariant MemberContext::Private::reimplementedBy () const [inline]
Definition at line 3691 of file context.cpp.
{ return m_cachable.reimplementedBy.get(this); }
References m_cachable, and MemberContext::Private::Cachable::reimplementedBy.
reimplementedBy() [2/2]
TemplateVariant MemberContext::Private::reimplementedBy () const [inline]
Definition at line 3691 of file context.cpp.
{ return m_cachable.reimplementedBy.get(this); }
reimplements() [1/2]
TemplateVariant MemberContext::Private::reimplements () const [inline]
Definition at line 3689 of file context.cpp.
{ return m_cachable.reimplements.get(this); }
References m_cachable, and MemberContext::Private::Cachable::reimplements.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::add_reimplements(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_reimplements(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.memberdefType::insert_reimplements_at(), doxmlparser.compound.memberdefType::replace_reimplements_at(), and doxmlparser.compound.memberdefType::set_reimplements().
reimplements() [2/2]
TemplateVariant MemberContext::Private::reimplements () const [inline]
Definition at line 3689 of file context.cpp.
{ return m_cachable.reimplements.get(this); }
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::add_reimplements(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_reimplements(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.memberdefType::insert_reimplements_at(), doxmlparser.compound.memberdefType::replace_reimplements_at(), and doxmlparser.compound.memberdefType::set_reimplements().
sourceCode() [1/2]
TemplateVariant MemberContext::Private::sourceCode () const [inline]
Definition at line 3696 of file context.cpp.
{ return m_cachable.sourceCode.get(this); }
References m_cachable, and MemberContext::Private::Cachable::sourceCode.
sourceCode() [2/2]
TemplateVariant MemberContext::Private::sourceCode () const [inline]
Definition at line 3696 of file context.cpp.
{ return m_cachable.sourceCode.get(this); }
sourceRefBys() [1/2]
TemplateVariant MemberContext::Private::sourceRefBys () const [inline]
Definition at line 3695 of file context.cpp.
{ return m_cachable.sourceRefBys.get(this); }
References m_cachable, and MemberContext::Private::Cachable::sourceRefBys.
sourceRefBys() [2/2]
TemplateVariant MemberContext::Private::sourceRefBys () const [inline]
Definition at line 3695 of file context.cpp.
{ return m_cachable.sourceRefBys.get(this); }
sourceRefs() [1/2]
TemplateVariant MemberContext::Private::sourceRefs () const [inline]
Definition at line 3694 of file context.cpp.
{ return m_cachable.sourceRefs.get(this); }
References m_cachable, and MemberContext::Private::Cachable::sourceRefs.
sourceRefs() [2/2]
TemplateVariant MemberContext::Private::sourceRefs () const [inline]
Definition at line 3694 of file context.cpp.
{ return m_cachable.sourceRefs.get(this); }
templateAlias() [1/2]
TemplateVariant MemberContext::Private::templateAlias () const [inline]
Definition at line 3669 of file context.cpp.
{ return m_cachable.templateAlias.get(this); }
References m_cachable, and MemberContext::Private::Cachable::templateAlias.
templateAlias() [2/2]
TemplateVariant MemberContext::Private::templateAlias () const [inline]
Definition at line 3669 of file context.cpp.
{ return m_cachable.templateAlias.get(this); }
templateArgs() [1/2]
TemplateVariant MemberContext::Private::templateArgs () const [inline]
Definition at line 3668 of file context.cpp.
{ return m_cachable.templateArgs.get(this); }
References m_cachable, and MemberContext::Private::Cachable::templateArgs.
templateArgs() [2/2]
TemplateVariant MemberContext::Private::templateArgs () const [inline]
Definition at line 3668 of file context.cpp.
{ return m_cachable.templateArgs.get(this); }
templateDecls() [1/2]
TemplateVariant MemberContext::Private::templateDecls () const [inline]
Definition at line 3685 of file context.cpp.
{ return m_cachable.templateDecls.get(this); }
References m_cachable, and MemberContext::Private::Cachable::templateDecls.
templateDecls() [2/2]
TemplateVariant MemberContext::Private::templateDecls () const [inline]
Definition at line 3685 of file context.cpp.
{ return m_cachable.templateDecls.get(this); }
trailingReturnType() [1/2]
TemplateVariant MemberContext::Private::trailingReturnType () const [inline]
Definition at line 3684 of file context.cpp.
{ return m_cachable.trailingReturnType.get(this); }
References m_cachable, and MemberContext::Private::Cachable::trailingReturnType.
trailingReturnType() [2/2]
TemplateVariant MemberContext::Private::trailingReturnType () const [inline]
Definition at line 3684 of file context.cpp.
{ return m_cachable.trailingReturnType.get(this); }
type() [1/2]
TemplateVariant MemberContext::Private::type () const [inline]
Definition at line 3657 of file context.cpp.
{ return m_memberDef->typeString(); }
References m_memberDef, and MemberDef::typeString().
type() [2/2]
TemplateVariant MemberContext::Private::type () const [inline]
Definition at line 3657 of file context.cpp.
{ return m_memberDef->typeString(); }
typeConstraints() [1/2]
TemplateVariant MemberContext::Private::typeConstraints () const [inline]
Definition at line 3693 of file context.cpp.
{ return m_cachable.typeConstraints.get(this); }
References m_cachable, and MemberContext::Private::Cachable::typeConstraints.
typeConstraints() [2/2]
TemplateVariant MemberContext::Private::typeConstraints () const [inline]
Definition at line 3693 of file context.cpp.
{ return m_cachable.typeConstraints.get(this); }
Member Data Documentation
m_cachable
Cachable MemberContext::Private::m_cachable [private]
Definition at line 4274 of file context.cpp.
Referenced by anonymousMember(), anonymousType(), bitfields(), category(), categoryRelation(), declArgs(), declType(), definition(), enumValues(), eventAttrs(), examples(), exception(), fieldType(), getCallerGraph(), getCallGraph(), getClass(), getFile(), getNamespace(), implementedBy(), implements(), initializer(), initializerAsCode(), labels(), paramDocs(), parameters(), propertyAttrs(), reimplementedBy(), reimplements(), sourceCode(), sourceRefBys(), sourceRefs(), templateAlias(), templateArgs(), templateDecls(), trailingReturnType(), and typeConstraints().
m_memberDef
const MemberDef * MemberContext::Private::m_memberDef [private]
Definition at line 4234 of file context.cpp.
Referenced by callerGraph(), callGraph(), createAnonymousMember(), createAnonymousType(), createBitfields(), createCallerGraph(), createCallGraph(), createCategory(), createCategoryRelation(), createClassDef(), createDeclArgs(), createDeclType(), createDefinition(), createEnumValues(), createEventAttrs(), createExamples(), createException(), createFieldType(), createFileDef(), createImplementedBy(), createImplements(), createInitializer(), createInitializerAsCode(), createLabels(), createNamespaceDef(), createParamDocs(), createParameters(), createPropertyAttrs(), createReimplementedBy(), createReimplements(), createSourceCode(), createSourceRefBys(), createSourceRefs(), createTemplateAlias(), createTemplateArgs(), createTemplateDecls(), createTrailingReturnType(), createTypeConstraints(), enumBaseType(), extraTypeChars(), functionQualifier(), getDefArgList(), handleDetailsVisibleFor(), handleNameWithContextFor(), hasCallerGraph(), hasCallGraph(), hasDetails(), hasMultiLineInitializer(), hasOneLineInitializer(), hasReferencedByRelation(), hasReferencesRelation(), hasSources(), isAbstract(), isAddable(), isAnonymous(), isAssign(), isAttribute(), isBound(), isConstrained(), isCopy(), isCSharpProperty(), isDefault(), isDefine(), isDelete(), isEnumeration(), isEnumStruct(), isEnumValue(), isEvent(), isExplicit(), isExternal(), isFinal(), isForeign(), isFriend(), isFunction(), isFunctionPtr(), isGettable(), isImplementation(), isInitonly(), isInline(), isMaybeAmbiguous(), isMaybeDefault(), isMaybeVoid(), isMutable(), isNew(), isNoExcept(), isNonAtomic(), isObjCMethod(), isObjCProperty(), isOptional(), isOverride(), isPrivateGettable(), isPrivateSettable(), isProperty(), isProtectedGettable(), isProtectedSettable(), isPublished(), isRaisable(), isReadable(), isReadonly(), isRelated(), isRemovable(), isRequired(), isRetain(), isSealed(), isSettable(), isSignal(), isSlot(), isStatic(), isStrong(), isTemplateSpecialization(), isTransient(), isTypeAlias(), isTypedef(), isUNOProperty(), isUnretained(), isVariable(), isWeak(), isWritable(), and type().
s_inst
const PropertyMap< MemberContext::Private > MemberContext::Private::s_inst [static], [private]
Definition at line 4275 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp