AllMembersListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
AllMembersListContext (const MemberNameInfoLinkedMap &ml)
virtual ~AllMembersListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
AllMembersListContext (const MemberNameInfoLinkedMap &ml)
virtual ~AllMembersListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc (const MemberNameInfoLinkedMap &ml)
static TemplateListIntfPtr alloc (const MemberNameInfoLinkedMap &ml)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 1162 of file context.h.
Constructor & Destructor Documentation
AllMembersListContext() [1/2]
AllMembersListContext::AllMembersListContext (const MemberNameInfoLinkedMap & ml)
Definition at line 7747 of file context.cpp.
                                                                              : p(std::make_unique<Private>(ml))
{
}
 AllMembersListContext() [1/2]
AllMembersListContext::~AllMembersListContext () [virtual]
Definition at line 7751 of file context.cpp.
{
}
AllMembersListContext() [2/2]
AllMembersListContext::AllMembersListContext (const MemberNameInfoLinkedMap & ml)
 AllMembersListContext() [2/2]
virtual AllMembersListContext::~AllMembersListContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr AllMembersListContext::alloc (const MemberNameInfoLinkedMap & ml) [inline], [static]
Definition at line 1165 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<AllMembersListContext>(ml)); }
Referenced by ClassContext::Private::createAllMembersList().
alloc() [2/2]
static TemplateListIntfPtr AllMembersListContext::alloc (const MemberNameInfoLinkedMap & ml) [inline], [static]
Definition at line 1165 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<AllMembersListContext>(ml)); }
at() [1/2]
TemplateVariant AllMembersListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 7761 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant AllMembersListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t AllMembersListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 7756 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t AllMembersListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr AllMembersListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 7766 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr AllMembersListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > AllMembersListContext::p [private]
Definition at line 1178 of file context.h.
Referenced by at(), count(), and createIterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp