FilePair Class Reference
#include <dirdef.h>
Public Member Functions
FilePair (const FileDef *src, const FileDef *dst)
const FileDef * source () const
const FileDef * destination () const
FilePair (const FileDef *src, const FileDef *dst)
const FileDef * source () const
const FileDef * destination () const
Static Public Member Functions
static QCString key (const FileDef *srcFd, const FileDef *dstFd)
static QCString key (const FileDef *srcFd, const FileDef *dstFd)
Private Attributes
const FileDef * m_src
const FileDef * m_dst
Detailed Description
Class representing a pair of FileDef objects
Definition at line 41 of file dirdef.h.
Constructor & Destructor Documentation
FilePair() [1/2]
FilePair::FilePair (const FileDef * src, const FileDef * dst) [inline]
Definition at line 44 of file dirdef.h.
: m_src(src), m_dst(dst) {}
FilePair() [2/2]
FilePair::FilePair (const FileDef * src, const FileDef * dst) [inline]
Definition at line 44 of file dirdef.h.
: m_src(src), m_dst(dst) {}
Member Function Documentation
destination() [1/2]
const FileDef * FilePair::destination () const [inline]
Definition at line 46 of file dirdef.h.
{ return m_dst; }
References m_dst.
destination() [2/2]
const FileDef * FilePair::destination () const [inline]
Definition at line 46 of file dirdef.h.
{ return m_dst; }
References m_dst.
key() [1/2]
QCString FilePair::key (const FileDef * srcFd, const FileDef * dstFd) [static]
Definition at line 846 of file dirdef.cpp.
{
  return srcFd->getOutputFileBase()+";"+dstFd->getOutputFileBase();
}
References FileDef::getOutputFileBase().
Referenced by UsedDir::addFileDep(), and DirDefImpl::addUsesDependency().
key() [2/2]
static QCString FilePair::key (const FileDef * srcFd, const FileDef * dstFd) [static]
source() [1/2]
const FileDef * FilePair::source () const [inline]
Definition at line 45 of file dirdef.h.
{ return m_src; }
References m_src.
source() [2/2]
const FileDef * FilePair::source () const [inline]
Definition at line 45 of file dirdef.h.
{ return m_src; }
References m_src.
Member Data Documentation
m_dst
const FileDef * FilePair::m_dst [private]
Definition at line 50 of file dirdef.h.
Referenced by destination().
m_src
const FileDef * FilePair::m_src [private]
Definition at line 49 of file dirdef.h.
Referenced by source().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dirdef.h
doxygen/src/dirdef.h
doxygen/build/doxygen/src/dirdef.cpp
doxygen/src/dirdef.cpp