MemberGroup Class Reference
#include <membergroup.h>
Public Member Functions
MemberGroup (const Definition *container, int id, const QCString &header, const QCString &docs, const QCString &docFile, int docLine, MemberListContainer con)
~MemberGroup ()
QCString header () const
int groupId () const
void insertMember (const MemberDef *md)
void setAnchors ()
void writePlainDeclarations (OutputList &ol, bool inGroup, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const
void writeDeclarations (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool showInline=FALSE) const
void writeDocumentation (OutputList &ol, const QCString &scopeName, const Definition *container, bool showEnumValues, bool showInline) const
void writeDocumentationPage (OutputList &ol, const QCString &scopeName, const DefinitionMutable *container) const
void writeTagFile (TextStream &, bool qualifiedName=false)
void addGroupedInheritedMembers (OutputList &ol, const ClassDef *cd, MemberListType lt, const ClassDef *inheritedFrom, const QCString &inheritId) const
void setAnonymousEnumType ()
const QCString & documentation () const
bool allMembersInSameSection () const
void addToDeclarationSection ()
void countDecMembers ()
void countDocMembers ()
int countGroupedInheritedMembers (MemberListType lt)
void distributeMemberGroupDocumentation ()
void findSectionsInDocumentation (const Definition *d)
int numDecMembers () const
int numDecEnumValues () const
int numDocMembers () const
int numDocEnumValues () const
const Definition * container () const
const Definition * memberContainer () const
int countInheritableMembers (const ClassDef *inheritedFrom) const
void addListReferences (Definition *d)
void setRefItems (const RefItemVector &sli)
const MemberList & members () const
QCString docFile () const
int docLine () const
MemberGroup (const Definition *container, int id, const QCString &header, const QCString &docs, const QCString &docFile, int docLine, MemberListContainer con)
~MemberGroup ()
QCString header () const
int groupId () const
void insertMember (const MemberDef *md)
void setAnchors ()
void writePlainDeclarations (OutputList &ol, bool inGroup, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const
void writeDeclarations (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool showInline=FALSE) const
void writeDocumentation (OutputList &ol, const QCString &scopeName, const Definition *container, bool showEnumValues, bool showInline) const
void writeDocumentationPage (OutputList &ol, const QCString &scopeName, const DefinitionMutable *container) const
void writeTagFile (TextStream &, bool qualifiedName=false)
void addGroupedInheritedMembers (OutputList &ol, const ClassDef *cd, MemberListType lt, const ClassDef *inheritedFrom, const QCString &inheritId) const
void setAnonymousEnumType ()
const QCString & documentation () const
bool allMembersInSameSection () const
void addToDeclarationSection ()
void countDecMembers ()
void countDocMembers ()
int countGroupedInheritedMembers (MemberListType lt)
void distributeMemberGroupDocumentation ()
void findSectionsInDocumentation (const Definition *d)
int numDecMembers () const
int numDecEnumValues () const
int numDocMembers () const
int numDocEnumValues () const
const Definition * container () const
const Definition * memberContainer () const
int countInheritableMembers (const ClassDef *inheritedFrom) const
void addListReferences (Definition *d)
void setRefItems (const RefItemVector &sli)
const MemberList & members () const
QCString docFile () const
int docLine () const
Private Attributes
const Definition * m_container
std::unique_ptr< MemberList > memberList
MemberList * inDeclSection = 0
int grpId = 0
QCString grpHeader
QCString fileName
QCString doc
bool inSameSection = true
QCString m_docFile
int m_docLine
RefItemVector m_xrefListItems
Detailed Description
A class representing a group of members.
Definition at line 41 of file membergroup.h.
Constructor & Destructor Documentation
MemberGroup() [1/2]
MemberGroup::MemberGroup (const Definition * container, int id, const QCString & header, const QCString & docs, const QCString & docFile, int docLine, MemberListContainer con)
Definition at line 32 of file membergroup.cpp.
  : m_container(container),
    memberList(std::make_unique<MemberList>(MemberListType_memberGroup,con)),
    grpId(id), grpHeader(hdr), doc(d), m_docFile(docFile), m_docLine(docLine)
{
  //printf("New member group id=%d header=%s desc=%s\n",id,hdr,d);
  memberList->setNeedsSorting(Config_getBool(SORT_BRIEF_DOCS)); // detailed sections are already sorted elsewhere.
  //printf("Member group docs='%s'\n",qPrint(doc));
}
References Config_getBool, and memberList.
 MemberGroup() [1/2]
MemberGroup::~MemberGroup ()
Definition at line 44 of file membergroup.cpp.
{
}
MemberGroup() [2/2]
MemberGroup::MemberGroup (const Definition * container, int id, const QCString & header, const QCString & docs, const QCString & docFile, int docLine, MemberListContainer con)
 MemberGroup() [2/2]
MemberGroup::~MemberGroup ()
Member Function Documentation
addGroupedInheritedMembers() [1/2]
void MemberGroup::addGroupedInheritedMembers (OutputList & ol, const ClassDef * cd, MemberListType lt, const ClassDef * inheritedFrom, const QCString & inheritId) const
Definition at line 128 of file membergroup.cpp.
{
  //printf("** addGroupedInheritedMembers()\n");
  for (const auto &md : *memberList)
  {
    //printf("matching %d == %d\n",lt,md->getSectionList()->listType());
    const MemberList *ml = md->getSectionList(m_container);
    if (ml && lt==ml->listType())
    {
      MemberList mml(lt,MemberListContainer::Class);
      mml.push_back(md);
      mml.countDecMembers();
      mml.writePlainDeclarations(ol,false,cd,0,0,0,0,inheritedFrom,inheritId);
    }
  }
}
References Class, MemberList::countDecMembers(), MemberList::listType(), m_container, memberList, MemberVector::push_back(), and MemberList::writePlainDeclarations().
addGroupedInheritedMembers() [2/2]
void MemberGroup::addGroupedInheritedMembers (OutputList & ol, const ClassDef * cd, MemberListType lt, const ClassDef * inheritedFrom, const QCString & inheritId) const
addListReferences() [1/2]
void MemberGroup::addListReferences (Definition * d)
Definition at line 274 of file membergroup.cpp.
{
  memberList->addListReferences(def);
}
References memberList.
addListReferences() [2/2]
void MemberGroup::addListReferences (Definition * d)
addToDeclarationSection() [1/2]
void MemberGroup::addToDeclarationSection ()
Add this group as a subsection of the declaration section, instead of rendering it in its own section
Definition at line 167 of file membergroup.cpp.
{
  if (inDeclSection)
  {
    //printf("Adding group %p to list %p (type=%d) memberList=%p\n",this,
    // inDeclSection,inDeclSection->listType(),memberList);
    inDeclSection->addMemberGroup(this);
  }
}
References MemberList::addMemberGroup(), and inDeclSection.
addToDeclarationSection() [2/2]
void MemberGroup::addToDeclarationSection ()
allMembersInSameSection() [1/2]
bool MemberGroup::allMembersInSameSection () const [inline]
Definition at line 69 of file membergroup.h.
{ return inSameSection; }
References inSameSection.
allMembersInSameSection() [2/2]
bool MemberGroup::allMembersInSameSection () const [inline]
Definition at line 69 of file membergroup.h.
{ return inSameSection; }
References inSameSection.
container() [1/2]
const Definition * MemberGroup::container () const
Definition at line 187 of file membergroup.cpp.
{
  return m_container;
}
References m_container.
Referenced by doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), writeDocumentation(), and writeDocumentationPage().
container() [2/2]
const Definition * MemberGroup::container () const
Referenced by doxmlparser.compound.MemberSpec_::__init__(), and doxmlparser.index.MemberSpec_::__init__().
countDecMembers() [1/2]
void MemberGroup::countDecMembers ()
Definition at line 177 of file membergroup.cpp.
{
  memberList->countDecMembers();
}
References memberList.
countDecMembers() [2/2]
void MemberGroup::countDecMembers ()
countDocMembers() [1/2]
void MemberGroup::countDocMembers ()
Definition at line 182 of file membergroup.cpp.
{
  memberList->countDocMembers();
}
References memberList.
countDocMembers() [2/2]
void MemberGroup::countDocMembers ()
countGroupedInheritedMembers() [1/2]
int MemberGroup::countGroupedInheritedMembers (MemberListType lt)
Definition at line 147 of file membergroup.cpp.
{
  //printf("** countGroupedInheritedMembers()\n");
  int count=0;
  for (const auto &md : *memberList)
  {
    //printf("matching %d == %d\n",lt,md->getSectionList()->listType());
    const MemberList *ml = md->getSectionList(m_container);
    if (ml && lt==ml->listType())
    {
      count++;
    }
  }
  return count;
}
References MemberList::listType(), m_container, and memberList.
countGroupedInheritedMembers() [2/2]
int MemberGroup::countGroupedInheritedMembers (MemberListType lt)
countInheritableMembers() [1/2]
int MemberGroup::countInheritableMembers (const ClassDef * inheritedFrom) const
Definition at line 209 of file membergroup.cpp.
{
  return memberList->countInheritableMembers(inheritedFrom);
}
References memberList.
countInheritableMembers() [2/2]
int MemberGroup::countInheritableMembers (const ClassDef * inheritedFrom) const
distributeMemberGroupDocumentation() [1/2]
void MemberGroup::distributeMemberGroupDocumentation ()
Definition at line 215 of file membergroup.cpp.
{
  //printf("MemberGroup::distributeMemberGroupDocumentation() %s\n",qPrint(grpHeader));
  const MemberDef *md = 0;
  for (const auto &smd : *memberList)
  {
    //printf("checking md=%s\n",qPrint(md->name()));
    // find the first member of the group with documentation
    if (!smd->documentation().isEmpty() ||
        !smd->briefDescription().isEmpty() ||
        !smd->inbodyDocumentation().isEmpty()
       )
    {
      //printf("found it!\n");
      md = smd;
      break;
    }
  }
  if (md) // distribute docs of md to other members of the list
  {
    //printf("Member %s has documentation!\n",qPrint(md->name()));
    for (const auto &iomd : *memberList)
    {
      MemberDefMutable *omd = toMemberDefMutable(iomd);
      if (omd && md!=omd && omd->documentation().isEmpty() &&
                            omd->briefDescription().isEmpty() &&
                            omd->inbodyDocumentation().isEmpty()
         )
      {
        //printf("Copying documentation to member %s\n",qPrint(omd->name()));
        omd->setBriefDescription(md->briefDescription(),md->briefFile(),md->briefLine());
        omd->setDocumentation(md->documentation(),md->docFile(),md->docLine());
        omd->setInbodyDocumentation(md->inbodyDocumentation(),md->inbodyFile(),md->inbodyLine());
      }
    }
  }
}
References MemberDef::briefDescription(), Definition::briefFile(), Definition::briefLine(), Definition::docFile(), Definition::docLine(), MemberDef::documentation(), Definition::inbodyDocumentation(), Definition::inbodyFile(), Definition::inbodyLine(), QCString::isEmpty(), memberList, MemberDefMutable::setBriefDescription(), MemberDefMutable::setDocumentation(), MemberDefMutable::setInbodyDocumentation(), and toMemberDefMutable().
distributeMemberGroupDocumentation() [2/2]
void MemberGroup::distributeMemberGroupDocumentation ()
docFile() [1/2]
QCString MemberGroup::docFile () const [inline]
Definition at line 88 of file membergroup.h.
{ return m_docFile; }
References m_docFile.
docFile() [2/2]
QCString MemberGroup::docFile () const [inline]
Definition at line 88 of file membergroup.h.
{ return m_docFile; }
References m_docFile.
docLine() [1/2]
int MemberGroup::docLine () const [inline]
Definition at line 89 of file membergroup.h.
{ return m_docLine; }
References m_docLine.
docLine() [2/2]
int MemberGroup::docLine () const [inline]
Definition at line 89 of file membergroup.h.
{ return m_docLine; }
References m_docLine.
documentation() [1/2]
const QCString & MemberGroup::documentation () const [inline]
Definition at line 68 of file membergroup.h.
{ return doc; }
References doc.
Referenced by MemberGroupInfoContext::Private::createDocs().
documentation() [2/2]
const QCString & MemberGroup::documentation () const [inline]
Definition at line 68 of file membergroup.h.
{ return doc; }
References doc.
findSectionsInDocumentation() [1/2]
void MemberGroup::findSectionsInDocumentation (const Definition * d)
Definition at line 279 of file membergroup.cpp.
{
  docFindSections(doc,d,m_docFile);
  memberList->findSectionsInDocumentation(d);
}
References doc, docFindSections(), m_docFile, and memberList.
findSectionsInDocumentation() [2/2]
void MemberGroup::findSectionsInDocumentation (const Definition * d)
groupId() [1/2]
int MemberGroup::groupId () const [inline]
Definition at line 49 of file membergroup.h.
{ return grpId; }
References grpId.
groupId() [2/2]
int MemberGroup::groupId () const [inline]
Definition at line 49 of file membergroup.h.
{ return grpId; }
References grpId.
header() [1/2]
QCString MemberGroup::header () const [inline]
Definition at line 48 of file membergroup.h.
{ return grpHeader; }
References grpHeader.
Referenced by doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.sectiondefType::buildChildren(), doxmlparser.compound.sectiondefType::exportChildren(), doxmlparser.compound.sectiondefType::get_header(), MemberGroupInfoContext::Private::groupTitle(), doxmlparser.compound.sectiondefType::hasContent_(), and doxmlparser.compound.sectiondefType::set_header().
header() [2/2]
QCString MemberGroup::header () const [inline]
Definition at line 48 of file membergroup.h.
{ return grpHeader; }
References grpHeader.
Referenced by doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.sectiondefType::buildChildren(), doxmlparser.compound.sectiondefType::exportChildren(), doxmlparser.compound.sectiondefType::get_header(), doxmlparser.compound.sectiondefType::hasContent_(), and doxmlparser.compound.sectiondefType::set_header().
insertMember() [1/2]
void MemberGroup::insertMember (const MemberDef * md)
Definition at line 48 of file membergroup.cpp.
{
  //printf("MemberGroup::insertMember memberList=%p count=%d"
  // " member section list: %p: md=%p:%s\n",
  // memberList->first() ? memberList->first()->getSectionList() : 0,
  // memberList->count(),
  // md->getSectionList(),
  // md,qPrint(md->name()));
  const MemberDef *firstMd = memberList->empty() ? 0 : memberList->front();
  if (inSameSection && firstMd &&
      firstMd->getSectionList(m_container)!=md->getSectionList(m_container))
  {
    inSameSection=FALSE;
  }
  else if (inDeclSection==0)
  {
    inDeclSection = const_cast<MemberList*>(md->getSectionList(m_container));
    //printf("inDeclSection=%p type=%d\n",inDeclSection,inDeclSection->listType());
  }
  memberList->push_back(md);
  // copy the group of the first member in the memberGroup
  GroupDef *gd;
  if (firstMd && !firstMd->isAlias() && (gd=const_cast<GroupDef*>(firstMd->getGroupDef())))
  {
    MemberDefMutable *mdm = toMemberDefMutable(md);
    if (mdm)
    {
      mdm->setGroupDef(gd, firstMd->getGroupPri(),
                       firstMd->getGroupFileName(),
                       firstMd->getGroupStartLine(),
                       firstMd->getGroupHasDocs());
    }
    gd->insertMember(md);
  }
}
References FALSE, MemberDef::getGroupDef(), MemberDef::getGroupFileName(), MemberDef::getGroupHasDocs(), MemberDef::getGroupPri(), MemberDef::getGroupStartLine(), MemberDef::getSectionList(), inDeclSection, inSameSection, GroupDef::insertMember(), Definition::isAlias(), m_container, memberList, MemberDefMutable::setGroupDef(), and toMemberDefMutable().
Referenced by addMembersToMemberGroup().
insertMember() [2/2]
void MemberGroup::insertMember (const MemberDef * md)
memberContainer() [1/2]
const Definition * MemberGroup::memberContainer () const
Definition at line 192 of file membergroup.cpp.
{
  // return the container for the first member.
  // Note this can be different from container() in case
  // the member is rendered as part of a file but the members
  // are actually of a namespace.
  const Definition *ctx = 0;
  if (memberList && !memberList->empty())
  {
    const MemberDef *md = memberList->front();
    ctx = md->getClassDef();
    if (ctx==0) ctx = md->getNamespaceDef();
    if (ctx==0) ctx = md->getFileDef();
  }
  return ctx==0 ? m_container : ctx;
}
References MemberDef::getClassDef(), MemberDef::getFileDef(), MemberDef::getNamespaceDef(), m_container, and memberList.
memberContainer() [2/2]
const Definition * MemberGroup::memberContainer () const
members() [1/2]
const MemberList & MemberGroup::members () const [inline]
Definition at line 86 of file membergroup.h.
{ return *memberList.get(); }
References memberList.
Referenced by MemberGroupInfoContext::Private::createMembers().
members() [2/2]
const MemberList & MemberGroup::members () const [inline]
Definition at line 86 of file membergroup.h.
{ return *memberList.get(); }
References memberList.
numDecEnumValues() [1/2]
int MemberGroup::numDecEnumValues () const
Definition at line 259 of file membergroup.cpp.
{
  return memberList->numDecEnumValues();
}
References memberList.
numDecEnumValues() [2/2]
int MemberGroup::numDecEnumValues () const
numDecMembers() [1/2]
int MemberGroup::numDecMembers () const
Definition at line 254 of file membergroup.cpp.
{
  return memberList->numDecMembers();
}
References memberList.
numDecMembers() [2/2]
int MemberGroup::numDecMembers () const
numDocEnumValues() [1/2]
int MemberGroup::numDocEnumValues () const
Definition at line 269 of file membergroup.cpp.
{
  return memberList->numDocEnumValues();
}
References memberList.
numDocEnumValues() [2/2]
int MemberGroup::numDocEnumValues () const
numDocMembers() [1/2]
int MemberGroup::numDocMembers () const
Definition at line 264 of file membergroup.cpp.
{
  return memberList->numDocMembers();
}
References memberList.
numDocMembers() [2/2]
int MemberGroup::numDocMembers () const
setAnchors() [1/2]
void MemberGroup::setAnchors ()
Definition at line 87 of file membergroup.cpp.
{
  memberList->setAnchors();
}
References memberList.
setAnchors() [2/2]
void MemberGroup::setAnchors ()
setAnonymousEnumType() [1/2]
void MemberGroup::setAnonymousEnumType ()
Definition at line 123 of file membergroup.cpp.
{
  memberList->setAnonymousEnumType();
}
References memberList.
setAnonymousEnumType() [2/2]
void MemberGroup::setAnonymousEnumType ()
setRefItems() [1/2]
void MemberGroup::setRefItems (const RefItemVector & sli)
Definition at line 285 of file membergroup.cpp.
{
  m_xrefListItems.insert(m_xrefListItems.end(), sli.cbegin(), sli.cend());
}
References m_xrefListItems.
setRefItems() [2/2]
void MemberGroup::setRefItems (const RefItemVector & sli)
writeDeclarations() [1/2]
void MemberGroup::writeDeclarations (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool showInline = FALSE) const
Definition at line 92 of file membergroup.cpp.
{
  //printf("MemberGroup::writeDeclarations() %s\n",qPrint(grpHeader));
  QCString ldoc = doc;
  memberList->writeDeclarations(ol,cd,nd,fd,gd,grpHeader,ldoc,FALSE,showInline);
}
References doc, FALSE, grpHeader, and memberList.
writeDeclarations() [2/2]
void MemberGroup::writeDeclarations (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool showInline = FALSE) const
writeDocumentation() [1/2]
void MemberGroup::writeDocumentation (OutputList & ol, const QCString & scopeName, const Definition * container, bool showEnumValues, bool showInline) const
Definition at line 110 of file membergroup.cpp.
{
  //printf("MemberGroup::writeDocumentation() %s\n",qPrint(grpHeader));
  memberList->writeDocumentation(ol,scopeName,container,QCString(),showEnumValues,showInline);
}
References container(), and memberList.
writeDocumentation() [2/2]
void MemberGroup::writeDocumentation (OutputList & ol, const QCString & scopeName, const Definition * container, bool showEnumValues, bool showInline) const
writeDocumentationPage() [1/2]
void MemberGroup::writeDocumentationPage (OutputList & ol, const QCString & scopeName, const DefinitionMutable * container) const
Definition at line 117 of file membergroup.cpp.
{
  memberList->writeDocumentationPage(ol,scopeName,container);
}
References container(), and memberList.
writeDocumentationPage() [2/2]
void MemberGroup::writeDocumentationPage (OutputList & ol, const QCString & scopeName, const DefinitionMutable * container) const
writePlainDeclarations() [1/2]
void MemberGroup::writePlainDeclarations (OutputList & ol, bool inGroup, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const
Definition at line 101 of file membergroup.cpp.
{
  //printf("MemberGroup::writePlainDeclarations() memberList->count()=%d\n",memberList->count());
  memberList->writePlainDeclarations(ol,inGroup,cd,nd,fd,gd,indentLevel,inheritedFrom,inheritId);
}
References memberList.
writePlainDeclarations() [2/2]
void MemberGroup::writePlainDeclarations (OutputList & ol, bool inGroup, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const
writeTagFile() [1/2]
void MemberGroup::writeTagFile (TextStream & tagFile, bool qualifiedName = false)
Definition at line 290 of file membergroup.cpp.
{
  memberList->writeTagFile(tagFile,qualifiedName);
}
References memberList.
writeTagFile() [2/2]
void MemberGroup::writeTagFile (TextStream & , bool qualifiedName = false)
Member Data Documentation
doc
QCString MemberGroup::doc [private]
Definition at line 98 of file membergroup.h.
Referenced by documentation(), findSectionsInDocumentation(), and writeDeclarations().
fileName
QCString MemberGroup::fileName [private]
Definition at line 97 of file membergroup.h.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
grpHeader
QCString MemberGroup::grpHeader [private]
Definition at line 96 of file membergroup.h.
Referenced by header(), and writeDeclarations().
grpId
int MemberGroup::grpId = 0 [private]
Definition at line 95 of file membergroup.h.
Referenced by groupId().
inDeclSection
MemberList * MemberGroup::inDeclSection = 0 [private]
Definition at line 94 of file membergroup.h.
Referenced by addToDeclarationSection(), and insertMember().
inSameSection
bool MemberGroup::inSameSection = true [private]
Definition at line 99 of file membergroup.h.
Referenced by allMembersInSameSection(), and insertMember().
m_container
const Definition * MemberGroup::m_container [private]
Definition at line 92 of file membergroup.h.
Referenced by addGroupedInheritedMembers(), container(), countGroupedInheritedMembers(), insertMember(), and memberContainer().
m_docFile
QCString MemberGroup::m_docFile [private]
Definition at line 100 of file membergroup.h.
Referenced by docFile(), and findSectionsInDocumentation().
m_docLine
int MemberGroup::m_docLine [private]
Definition at line 101 of file membergroup.h.
Referenced by docLine().
m_xrefListItems
RefItemVector MemberGroup::m_xrefListItems [private]
Definition at line 102 of file membergroup.h.
Referenced by setRefItems().
memberList
std::unique_ptr< MemberList > MemberGroup::memberList [private]
Definition at line 93 of file membergroup.h.
Referenced by addGroupedInheritedMembers(), addListReferences(), countDecMembers(), countDocMembers(), countGroupedInheritedMembers(), countInheritableMembers(), distributeMemberGroupDocumentation(), findSectionsInDocumentation(), insertMember(), memberContainer(), MemberGroup(), members(), numDecEnumValues(), numDecMembers(), numDocEnumValues(), numDocMembers(), setAnchors(), setAnonymousEnumType(), writeDeclarations(), writeDocumentation(), writeDocumentationPage(), writePlainDeclarations(), and writeTagFile().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/membergroup.h
doxygen/src/membergroup.h
doxygen/build/doxygen/src/membergroup.cpp
doxygen/src/membergroup.cpp