ModuleContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (const GroupDef *gd)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (const GroupDef *gd)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant compoundType () const
TemplateVariant hasDetails () const
TemplateVariant modules () const
TemplateVariant examples () const
TemplateVariant pages () const
TemplateVariant dirs () const
TemplateVariant files () const
TemplateVariant classes () const
TemplateVariant namespaces () const
TemplateVariant constantgroups () const
TemplateVariant macros () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant enumValues () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant signals () const
TemplateVariant publicSlots () const
TemplateVariant protectedSlots () const
TemplateVariant privateSlots () const
TemplateVariant events () const
TemplateVariant properties () const
TemplateVariant friends () const
TemplateVariant memberGroups () const
TemplateVariant detailedMacros () const
TemplateVariant detailedTypedefs () const
TemplateVariant detailedEnums () const
TemplateVariant detailedEnumValues () const
TemplateVariant detailedFunctions () const
TemplateVariant detailedVariables () const
TemplateVariant detailedSignals () const
TemplateVariant detailedPublicSlots () const
TemplateVariant detailedProtectedSlots () const
TemplateVariant detailedPrivateSlots () const
TemplateVariant detailedEvents () const
TemplateVariant detailedProperties () const
TemplateVariant detailedFriends () const
TemplateVariant inlineClasses () const
DotGroupCollaborationPtr getGroupGraph () const
TemplateVariant hasGroupGraph () const
TemplateVariant groupGraph () const
TemplateVariant createModules () const
TemplateVariant createDirs () const
TemplateVariant createFiles () const
TemplateVariant createClasses () const
TemplateVariant createNamespaces () const
TemplateVariant createConstantgroups () const
TemplateVariant createExamples () const
TemplateVariant createPages () const
TemplateVariant createMemberList (MemberListType type, const QCString &title) const
TemplateVariant createMacros () const
TemplateVariant createTypedefs () const
TemplateVariant createEnums () const
TemplateVariant createEnumValues () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createSignals () const
TemplateVariant createPublicSlots () const
TemplateVariant createProtectedSlots () const
TemplateVariant createPrivateSlots () const
TemplateVariant createEvents () const
TemplateVariant createProperties () const
TemplateVariant createFriends () const
TemplateVariant createDetailedMacros () const
TemplateVariant createDetailedTypedefs () const
TemplateVariant createDetailedEnums () const
TemplateVariant createDetailedEnumValues () const
TemplateVariant createDetailedFunctions () const
TemplateVariant createDetailedVariables () const
TemplateVariant createDetailedSignals () const
TemplateVariant createDetailedPublicSlots () const
TemplateVariant createDetailedProtectedSlots () const
TemplateVariant createDetailedPrivateSlots () const
TemplateVariant createDetailedEvents () const
TemplateVariant createDetailedProperties () const
TemplateVariant createDetailedFriends () const
TemplateVariant createInlineClasses () const
TemplateVariant createMemberGroups () const
DotGroupCollaborationPtr createGroupGraph () const
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant compoundType () const
TemplateVariant hasDetails () const
TemplateVariant modules () const
TemplateVariant examples () const
TemplateVariant pages () const
TemplateVariant dirs () const
TemplateVariant files () const
TemplateVariant classes () const
TemplateVariant namespaces () const
TemplateVariant constantgroups () const
TemplateVariant macros () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant enumValues () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant signals () const
TemplateVariant publicSlots () const
TemplateVariant protectedSlots () const
TemplateVariant privateSlots () const
TemplateVariant events () const
TemplateVariant properties () const
TemplateVariant friends () const
TemplateVariant memberGroups () const
TemplateVariant detailedMacros () const
TemplateVariant detailedTypedefs () const
TemplateVariant detailedEnums () const
TemplateVariant detailedEnumValues () const
TemplateVariant detailedFunctions () const
TemplateVariant detailedVariables () const
TemplateVariant detailedSignals () const
TemplateVariant detailedPublicSlots () const
TemplateVariant detailedProtectedSlots () const
TemplateVariant detailedPrivateSlots () const
TemplateVariant detailedEvents () const
TemplateVariant detailedProperties () const
TemplateVariant detailedFriends () const
TemplateVariant inlineClasses () const
DotGroupCollaborationPtr getGroupGraph () const
TemplateVariant hasGroupGraph () const
TemplateVariant groupGraph () const
TemplateVariant createModules () const
TemplateVariant createDirs () const
TemplateVariant createFiles () const
TemplateVariant createClasses () const
TemplateVariant createNamespaces () const
TemplateVariant createConstantgroups () const
TemplateVariant createExamples () const
TemplateVariant createPages () const
TemplateVariant createMemberList (MemberListType type, const QCString &title) const
TemplateVariant createMacros () const
TemplateVariant createTypedefs () const
TemplateVariant createEnums () const
TemplateVariant createEnumValues () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createSignals () const
TemplateVariant createPublicSlots () const
TemplateVariant createProtectedSlots () const
TemplateVariant createPrivateSlots () const
TemplateVariant createEvents () const
TemplateVariant createProperties () const
TemplateVariant createFriends () const
TemplateVariant createDetailedMacros () const
TemplateVariant createDetailedTypedefs () const
TemplateVariant createDetailedEnums () const
TemplateVariant createDetailedEnumValues () const
TemplateVariant createDetailedFunctions () const
TemplateVariant createDetailedVariables () const
TemplateVariant createDetailedSignals () const
TemplateVariant createDetailedPublicSlots () const
TemplateVariant createDetailedProtectedSlots () const
TemplateVariant createDetailedPrivateSlots () const
TemplateVariant createDetailedEvents () const
TemplateVariant createDetailedProperties () const
TemplateVariant createDetailedFriends () const
TemplateVariant createInlineClasses () const
TemplateVariant createMemberGroups () const
DotGroupCollaborationPtr createGroupGraph () const
Private Attributes
const GroupDef * m_groupDef
Cachable m_cachable
Static Private Attributes
static const PropertyMap< ModuleContext::Private > s_inst
Additional Inherited Members
Detailed Description
Definition at line 4531 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
ModuleContext::Private::Private (const GroupDef * gd) [inline]
Definition at line 4534 of file context.cpp.
                                : DefinitionContext<ModuleContext::Private>(gd) , m_groupDef(gd)
    {
    }
Private() [2/2]
ModuleContext::Private::Private (const GroupDef * gd) [inline]
Definition at line 4534 of file context.cpp.
                                : DefinitionContext<ModuleContext::Private>(gd) , m_groupDef(gd)
    {
    }
Member Function Documentation
classes() [1/2]
TemplateVariant ModuleContext::Private::classes () const [inline], [private]
Definition at line 4554 of file context.cpp.
{ return m_cachable.classes.get(this); }
References ModuleContext::Private::Cachable::classes, and m_cachable.
classes() [2/2]
TemplateVariant ModuleContext::Private::classes () const [inline], [private]
Definition at line 4554 of file context.cpp.
{ return m_cachable.classes.get(this); }
compoundType() [1/2]
TemplateVariant ModuleContext::Private::compoundType () const [inline], [private]
Definition at line 4547 of file context.cpp.
{ return TemplateVariant("module"); }
compoundType() [2/2]
TemplateVariant ModuleContext::Private::compoundType () const [inline], [private]
Definition at line 4547 of file context.cpp.
{ return TemplateVariant("module"); }
constantgroups() [1/2]
TemplateVariant ModuleContext::Private::constantgroups () const [inline], [private]
Definition at line 4556 of file context.cpp.
{ return m_cachable.constantgroups.get(this); }
References ModuleContext::Private::Cachable::constantgroups, and m_cachable.
constantgroups() [2/2]
TemplateVariant ModuleContext::Private::constantgroups () const [inline], [private]
Definition at line 4556 of file context.cpp.
{ return m_cachable.constantgroups.get(this); }
createClasses() [1/2]
TemplateVariant ModuleContext::Private::createClasses () const [inline], [private]
Definition at line 4676 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getClasses().size());
      for (const auto &cd : m_groupDef->getClasses())
      {
        if (cd->visibleInParentsDeclList())
        {
          list.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ClassContext::alloc(), TemplateImmutableList::alloc(), GroupDef::getClasses(), m_groupDef, and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
createClasses() [2/2]
TemplateVariant ModuleContext::Private::createClasses () const [inline], [private]
Definition at line 4676 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getClasses().size());
      for (const auto &cd : m_groupDef->getClasses())
      {
        if (cd->visibleInParentsDeclList())
        {
          list.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ClassContext::alloc(), and TemplateImmutableList::alloc().
createConstantgroups() [1/2]
TemplateVariant ModuleContext::Private::createConstantgroups () const [inline], [private]
Definition at line 4702 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getNamespaces().size());
      for (const auto &nd : m_groupDef->getNamespaces())
      {
        if (nd->isLinkable() && nd->isConstantGroup())
        {
          list.push_back(NamespaceContext::alloc(nd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References NamespaceContext::alloc(), TemplateImmutableList::alloc(), GroupDef::getNamespaces(), m_groupDef, and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
createConstantgroups() [2/2]
TemplateVariant ModuleContext::Private::createConstantgroups () const [inline], [private]
Definition at line 4702 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getNamespaces().size());
      for (const auto &nd : m_groupDef->getNamespaces())
      {
        if (nd->isLinkable() && nd->isConstantGroup())
        {
          list.push_back(NamespaceContext::alloc(nd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References NamespaceContext::alloc(), and TemplateImmutableList::alloc().
createDetailedEnums() [1/2]
TemplateVariant ModuleContext::Private::createDetailedEnums () const [inline], [private]
Definition at line 4806 of file context.cpp.
    {
      return createMemberList(MemberListType_docEnumMembers,theTranslator->trEnumerationTypeDocumentation());
    }
References createMemberList(), MemberListType_docEnumMembers, theTranslator, and Translator::trEnumerationTypeDocumentation().
createDetailedEnums() [2/2]
TemplateVariant ModuleContext::Private::createDetailedEnums () const [inline], [private]
Definition at line 4806 of file context.cpp.
    {
      return createMemberList(MemberListType_docEnumMembers,theTranslator->trEnumerationTypeDocumentation());
    }
References MemberListType_docEnumMembers, theTranslator, and Translator::trEnumerationTypeDocumentation().
createDetailedEnumValues() [1/2]
TemplateVariant ModuleContext::Private::createDetailedEnumValues () const [inline], [private]
Definition at line 4810 of file context.cpp.
    {
      return createMemberList(MemberListType_docEnumValMembers,theTranslator->trEnumerationValueDocumentation());
    }
References createMemberList(), MemberListType_docEnumValMembers, theTranslator, and Translator::trEnumerationValueDocumentation().
createDetailedEnumValues() [2/2]
TemplateVariant ModuleContext::Private::createDetailedEnumValues () const [inline], [private]
Definition at line 4810 of file context.cpp.
    {
      return createMemberList(MemberListType_docEnumValMembers,theTranslator->trEnumerationValueDocumentation());
    }
References MemberListType_docEnumValMembers, theTranslator, and Translator::trEnumerationValueDocumentation().
createDetailedEvents() [1/2]
TemplateVariant ModuleContext::Private::createDetailedEvents () const [inline], [private]
Definition at line 4840 of file context.cpp.
    {
      return createMemberList(MemberListType_docEventMembers,theTranslator->trEventDocumentation());
    }
References createMemberList(), MemberListType_docEventMembers, theTranslator, and Translator::trEventDocumentation().
createDetailedEvents() [2/2]
TemplateVariant ModuleContext::Private::createDetailedEvents () const [inline], [private]
Definition at line 4840 of file context.cpp.
    {
      return createMemberList(MemberListType_docEventMembers,theTranslator->trEventDocumentation());
    }
References MemberListType_docEventMembers, theTranslator, and Translator::trEventDocumentation().
createDetailedFriends() [1/2]
TemplateVariant ModuleContext::Private::createDetailedFriends () const [inline], [private]
Definition at line 4848 of file context.cpp.
    {
      return createMemberList(MemberListType_docFriendMembers,theTranslator->trFriends());
    }
References createMemberList(), MemberListType_docFriendMembers, theTranslator, and Translator::trFriends().
createDetailedFriends() [2/2]
TemplateVariant ModuleContext::Private::createDetailedFriends () const [inline], [private]
Definition at line 4848 of file context.cpp.
    {
      return createMemberList(MemberListType_docFriendMembers,theTranslator->trFriends());
    }
References MemberListType_docFriendMembers, theTranslator, and Translator::trFriends().
createDetailedFunctions() [1/2]
TemplateVariant ModuleContext::Private::createDetailedFunctions () const [inline], [private]
Definition at line 4814 of file context.cpp.
    {
      SrcLangExt lang = m_groupDef->getLanguage();
      return createMemberList(MemberListType_docFuncMembers, lang==SrcLangExt_Fortran ? theTranslator->trSubprogramDocumentation() :
                                                                                        theTranslator->trFunctionDocumentation());
    }
References createMemberList(), Definition::getLanguage(), m_groupDef, MemberListType_docFuncMembers, SrcLangExt_Fortran, theTranslator, Translator::trFunctionDocumentation(), and Translator::trSubprogramDocumentation().
createDetailedFunctions() [2/2]
TemplateVariant ModuleContext::Private::createDetailedFunctions () const [inline], [private]
Definition at line 4814 of file context.cpp.
    {
      SrcLangExt lang = m_groupDef->getLanguage();
      return createMemberList(MemberListType_docFuncMembers, lang==SrcLangExt_Fortran ? theTranslator->trSubprogramDocumentation() :
                                                                                        theTranslator->trFunctionDocumentation());
    }
References MemberListType_docFuncMembers, SrcLangExt_Fortran, theTranslator, Translator::trFunctionDocumentation(), and Translator::trSubprogramDocumentation().
createDetailedMacros() [1/2]
TemplateVariant ModuleContext::Private::createDetailedMacros () const [inline], [private]
Definition at line 4798 of file context.cpp.
    {
      return createMemberList(MemberListType_docDefineMembers,theTranslator->trDefineDocumentation());
    }
References createMemberList(), MemberListType_docDefineMembers, theTranslator, and Translator::trDefineDocumentation().
createDetailedMacros() [2/2]
TemplateVariant ModuleContext::Private::createDetailedMacros () const [inline], [private]
Definition at line 4798 of file context.cpp.
    {
      return createMemberList(MemberListType_docDefineMembers,theTranslator->trDefineDocumentation());
    }
References MemberListType_docDefineMembers, theTranslator, and Translator::trDefineDocumentation().
createDetailedPrivateSlots() [1/2]
TemplateVariant ModuleContext::Private::createDetailedPrivateSlots () const [inline], [private]
Definition at line 4836 of file context.cpp.
    {
      return createMemberList(MemberListType_docPriSlotMembers,theTranslator->trPrivateSlots());
    }
References createMemberList(), MemberListType_docPriSlotMembers, theTranslator, and Translator::trPrivateSlots().
createDetailedPrivateSlots() [2/2]
TemplateVariant ModuleContext::Private::createDetailedPrivateSlots () const [inline], [private]
Definition at line 4836 of file context.cpp.
    {
      return createMemberList(MemberListType_docPriSlotMembers,theTranslator->trPrivateSlots());
    }
References MemberListType_docPriSlotMembers, theTranslator, and Translator::trPrivateSlots().
createDetailedProperties() [1/2]
TemplateVariant ModuleContext::Private::createDetailedProperties () const [inline], [private]
Definition at line 4844 of file context.cpp.
    {
      return createMemberList(MemberListType_docPropMembers,theTranslator->trPropertyDocumentation());
    }
References createMemberList(), MemberListType_docPropMembers, theTranslator, and Translator::trPropertyDocumentation().
createDetailedProperties() [2/2]
TemplateVariant ModuleContext::Private::createDetailedProperties () const [inline], [private]
Definition at line 4844 of file context.cpp.
    {
      return createMemberList(MemberListType_docPropMembers,theTranslator->trPropertyDocumentation());
    }
References MemberListType_docPropMembers, theTranslator, and Translator::trPropertyDocumentation().
createDetailedProtectedSlots() [1/2]
TemplateVariant ModuleContext::Private::createDetailedProtectedSlots () const [inline], [private]
Definition at line 4832 of file context.cpp.
    {
      return createMemberList(MemberListType_docProSlotMembers,theTranslator->trProtectedSlots());
    }
References createMemberList(), MemberListType_docProSlotMembers, theTranslator, and Translator::trProtectedSlots().
createDetailedProtectedSlots() [2/2]
TemplateVariant ModuleContext::Private::createDetailedProtectedSlots () const [inline], [private]
Definition at line 4832 of file context.cpp.
    {
      return createMemberList(MemberListType_docProSlotMembers,theTranslator->trProtectedSlots());
    }
References MemberListType_docProSlotMembers, theTranslator, and Translator::trProtectedSlots().
createDetailedPublicSlots() [1/2]
TemplateVariant ModuleContext::Private::createDetailedPublicSlots () const [inline], [private]
Definition at line 4828 of file context.cpp.
    {
      return createMemberList(MemberListType_docPubSlotMembers,theTranslator->trPublicSlots());
    }
References createMemberList(), MemberListType_docPubSlotMembers, theTranslator, and Translator::trPublicSlots().
createDetailedPublicSlots() [2/2]
TemplateVariant ModuleContext::Private::createDetailedPublicSlots () const [inline], [private]
Definition at line 4828 of file context.cpp.
    {
      return createMemberList(MemberListType_docPubSlotMembers,theTranslator->trPublicSlots());
    }
References MemberListType_docPubSlotMembers, theTranslator, and Translator::trPublicSlots().
createDetailedSignals() [1/2]
TemplateVariant ModuleContext::Private::createDetailedSignals () const [inline], [private]
Definition at line 4824 of file context.cpp.
    {
      return createMemberList(MemberListType_docSignalMembers,theTranslator->trSignals());
    }
References createMemberList(), MemberListType_docSignalMembers, theTranslator, and Translator::trSignals().
createDetailedSignals() [2/2]
TemplateVariant ModuleContext::Private::createDetailedSignals () const [inline], [private]
Definition at line 4824 of file context.cpp.
    {
      return createMemberList(MemberListType_docSignalMembers,theTranslator->trSignals());
    }
References MemberListType_docSignalMembers, theTranslator, and Translator::trSignals().
createDetailedTypedefs() [1/2]
TemplateVariant ModuleContext::Private::createDetailedTypedefs () const [inline], [private]
Definition at line 4802 of file context.cpp.
    {
      return createMemberList(MemberListType_docTypedefMembers,theTranslator->trTypedefDocumentation());
    }
References createMemberList(), MemberListType_docTypedefMembers, theTranslator, and Translator::trTypedefDocumentation().
createDetailedTypedefs() [2/2]
TemplateVariant ModuleContext::Private::createDetailedTypedefs () const [inline], [private]
Definition at line 4802 of file context.cpp.
    {
      return createMemberList(MemberListType_docTypedefMembers,theTranslator->trTypedefDocumentation());
    }
References MemberListType_docTypedefMembers, theTranslator, and Translator::trTypedefDocumentation().
createDetailedVariables() [1/2]
TemplateVariant ModuleContext::Private::createDetailedVariables () const [inline], [private]
Definition at line 4820 of file context.cpp.
    {
      return createMemberList(MemberListType_docVarMembers,theTranslator->trVariableDocumentation());
    }
References createMemberList(), MemberListType_docVarMembers, theTranslator, and Translator::trVariableDocumentation().
createDetailedVariables() [2/2]
TemplateVariant ModuleContext::Private::createDetailedVariables () const [inline], [private]
Definition at line 4820 of file context.cpp.
    {
      return createMemberList(MemberListType_docVarMembers,theTranslator->trVariableDocumentation());
    }
References MemberListType_docVarMembers, theTranslator, and Translator::trVariableDocumentation().
createDirs() [1/2]
TemplateVariant ModuleContext::Private::createDirs () const [inline], [private]
Definition at line 4656 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getDirs().size());
      for(const auto dd : m_groupDef->getDirs())
      {
        list.push_back(DirContext::alloc(dd));
      }
      return TemplateImmutableList::alloc(list);
    }
References DirContext::alloc(), TemplateImmutableList::alloc(), GroupDef::getDirs(), and m_groupDef.
createDirs() [2/2]
TemplateVariant ModuleContext::Private::createDirs () const [inline], [private]
Definition at line 4656 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getDirs().size());
      for(const auto dd : m_groupDef->getDirs())
      {
        list.push_back(DirContext::alloc(dd));
      }
      return TemplateImmutableList::alloc(list);
    }
References DirContext::alloc(), and TemplateImmutableList::alloc().
createEnums() [1/2]
TemplateVariant ModuleContext::Private::createEnums () const [inline], [private]
Definition at line 4749 of file context.cpp.
    {
      return createMemberList(MemberListType_decEnumMembers,theTranslator->trEnumerations());
    }
References createMemberList(), MemberListType_decEnumMembers, theTranslator, and Translator::trEnumerations().
createEnums() [2/2]
TemplateVariant ModuleContext::Private::createEnums () const [inline], [private]
Definition at line 4749 of file context.cpp.
    {
      return createMemberList(MemberListType_decEnumMembers,theTranslator->trEnumerations());
    }
References MemberListType_decEnumMembers, theTranslator, and Translator::trEnumerations().
createEnumValues() [1/2]
TemplateVariant ModuleContext::Private::createEnumValues () const [inline], [private]
Definition at line 4753 of file context.cpp.
    {
      return createMemberList(MemberListType_decEnumValMembers,theTranslator->trEnumerationValues());
    }
References createMemberList(), MemberListType_decEnumValMembers, theTranslator, and Translator::trEnumerationValues().
createEnumValues() [2/2]
TemplateVariant ModuleContext::Private::createEnumValues () const [inline], [private]
Definition at line 4753 of file context.cpp.
    {
      return createMemberList(MemberListType_decEnumValMembers,theTranslator->trEnumerationValues());
    }
References MemberListType_decEnumValMembers, theTranslator, and Translator::trEnumerationValues().
createEvents() [1/2]
TemplateVariant ModuleContext::Private::createEvents () const [inline], [private]
Definition at line 4786 of file context.cpp.
    {
      return createMemberList(MemberListType_events,theTranslator->trEvents());
    }
References createMemberList(), MemberListType_events, theTranslator, and Translator::trEvents().
createEvents() [2/2]
TemplateVariant ModuleContext::Private::createEvents () const [inline], [private]
Definition at line 4786 of file context.cpp.
    {
      return createMemberList(MemberListType_events,theTranslator->trEvents());
    }
References MemberListType_events, theTranslator, and Translator::trEvents().
createExamples() [1/2]
TemplateVariant ModuleContext::Private::createExamples () const [inline], [private]
Definition at line 4715 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getExamples().size());
      for (const auto &ex : m_groupDef->getExamples())
      {
        list.push_back(PageContext::alloc(ex,FALSE,TRUE));
      }
      return TemplateImmutableList::alloc(list);
    }
References PageContext::alloc(), TemplateImmutableList::alloc(), FALSE, GroupDef::getExamples(), m_groupDef, LinkedRefMap< T, Hash, KeyEqual, Map >::size(), and TRUE.
createExamples() [2/2]
TemplateVariant ModuleContext::Private::createExamples () const [inline], [private]
Definition at line 4715 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getExamples().size());
      for (const auto &ex : m_groupDef->getExamples())
      {
        list.push_back(PageContext::alloc(ex,FALSE,TRUE));
      }
      return TemplateImmutableList::alloc(list);
    }
References PageContext::alloc(), TemplateImmutableList::alloc(), FALSE, and TRUE.
createFiles() [1/2]
TemplateVariant ModuleContext::Private::createFiles () const [inline], [private]
Definition at line 4666 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getFiles().size());
      for (const auto &fd : m_groupDef->getFiles())
      {
        list.push_back(FileContext::alloc(fd));
      }
      return TemplateImmutableList::alloc(list);
    }
References FileContext::alloc(), TemplateImmutableList::alloc(), GroupDef::getFiles(), and m_groupDef.
createFiles() [2/2]
TemplateVariant ModuleContext::Private::createFiles () const [inline], [private]
Definition at line 4666 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getFiles().size());
      for (const auto &fd : m_groupDef->getFiles())
      {
        list.push_back(FileContext::alloc(fd));
      }
      return TemplateImmutableList::alloc(list);
    }
References FileContext::alloc(), and TemplateImmutableList::alloc().
createFriends() [1/2]
TemplateVariant ModuleContext::Private::createFriends () const [inline], [private]
Definition at line 4794 of file context.cpp.
    {
      return createMemberList(MemberListType_friends,theTranslator->trFriends());
    }
References createMemberList(), MemberListType_friends, theTranslator, and Translator::trFriends().
createFriends() [2/2]
TemplateVariant ModuleContext::Private::createFriends () const [inline], [private]
Definition at line 4794 of file context.cpp.
    {
      return createMemberList(MemberListType_friends,theTranslator->trFriends());
    }
References MemberListType_friends, theTranslator, and Translator::trFriends().
createFunctions() [1/2]
TemplateVariant ModuleContext::Private::createFunctions () const [inline], [private]
Definition at line 4757 of file context.cpp.
    {
      SrcLangExt lang = m_groupDef->getLanguage();
      return createMemberList(MemberListType_decFuncMembers, lang==SrcLangExt_Fortran ? theTranslator->trSubprograms() :
                                                             lang==SrcLangExt_VHDL ? theTranslator->trFunctionAndProc() :
                                                                                        theTranslator->trFunctions());
    }
References createMemberList(), Definition::getLanguage(), m_groupDef, MemberListType_decFuncMembers, SrcLangExt_Fortran, SrcLangExt_VHDL, theTranslator, Translator::trFunctionAndProc(), Translator::trFunctions(), and Translator::trSubprograms().
createFunctions() [2/2]
TemplateVariant ModuleContext::Private::createFunctions () const [inline], [private]
Definition at line 4757 of file context.cpp.
    {
      SrcLangExt lang = m_groupDef->getLanguage();
      return createMemberList(MemberListType_decFuncMembers, lang==SrcLangExt_Fortran ? theTranslator->trSubprograms() :
                                                             lang==SrcLangExt_VHDL ? theTranslator->trFunctionAndProc() :
                                                                                        theTranslator->trFunctions());
    }
References MemberListType_decFuncMembers, SrcLangExt_Fortran, SrcLangExt_VHDL, theTranslator, Translator::trFunctionAndProc(), Translator::trFunctions(), and Translator::trSubprograms().
createGroupGraph() [1/2]
DotGroupCollaborationPtr ModuleContext::Private::createGroupGraph () const [inline], [private]
Definition at line 4873 of file context.cpp.
    {
      return std::make_shared<DotGroupCollaboration>(m_groupDef);
    }
References m_groupDef.
createGroupGraph() [2/2]
DotGroupCollaborationPtr ModuleContext::Private::createGroupGraph () const [inline], [private]
Definition at line 4873 of file context.cpp.
    {
      return std::make_shared<DotGroupCollaboration>(m_groupDef);
    }
createInlineClasses() [1/2]
TemplateVariant ModuleContext::Private::createInlineClasses () const [inline], [private]
Definition at line 4852 of file context.cpp.
    {
      TemplateVariantList list;
      for (const auto &cd : m_groupDef->getClasses())
      {
        if (!cd->isAnonymous() &&
            cd->isLinkableInProject() &&
            cd->isEmbeddedInOuterScope() &&
            cd->partOfGroups().empty())
        {
          list.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ClassContext::alloc(), TemplateImmutableList::alloc(), GroupDef::getClasses(), and m_groupDef.
createInlineClasses() [2/2]
TemplateVariant ModuleContext::Private::createInlineClasses () const [inline], [private]
Definition at line 4852 of file context.cpp.
    {
      TemplateVariantList list;
      for (const auto &cd : m_groupDef->getClasses())
      {
        if (!cd->isAnonymous() &&
            cd->isLinkableInProject() &&
            cd->isEmbeddedInOuterScope() &&
            cd->partOfGroups().empty())
        {
          list.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ClassContext::alloc(), and TemplateImmutableList::alloc().
createMacros() [1/2]
TemplateVariant ModuleContext::Private::createMacros () const [inline], [private]
Definition at line 4741 of file context.cpp.
    {
      return createMemberList(MemberListType_decDefineMembers,theTranslator->trDefines());
    }
References createMemberList(), MemberListType_decDefineMembers, theTranslator, and Translator::trDefines().
createMacros() [2/2]
TemplateVariant ModuleContext::Private::createMacros () const [inline], [private]
Definition at line 4741 of file context.cpp.
    {
      return createMemberList(MemberListType_decDefineMembers,theTranslator->trDefines());
    }
References MemberListType_decDefineMembers, theTranslator, and Translator::trDefines().
createMemberGroups() [1/2]
TemplateVariant ModuleContext::Private::createMemberGroups () const [inline], [private]
Definition at line 4867 of file context.cpp.
    {
      return !m_groupDef->getMemberGroups().empty() ?
          MemberGroupListContext::alloc(m_groupDef,relPathAsString(),m_groupDef->getMemberGroups(),m_groupDef->subGrouping()) :
          MemberGroupListContext::alloc();
    }
References MemberGroupListContext::alloc(), GroupDef::getMemberGroups(), m_groupDef, DefinitionContext< ModuleContext::Private >::relPathAsString(), and GroupDef::subGrouping().
createMemberGroups() [2/2]
TemplateVariant ModuleContext::Private::createMemberGroups () const [inline], [private]
Definition at line 4867 of file context.cpp.
    {
      return !m_groupDef->getMemberGroups().empty() ?
          MemberGroupListContext::alloc(m_groupDef,relPathAsString(),m_groupDef->getMemberGroups(),m_groupDef->subGrouping()) :
          MemberGroupListContext::alloc();
    }
References MemberGroupListContext::alloc().
createMemberList() [1/2]
TemplateVariant ModuleContext::Private::createMemberList (MemberListType type, const QCString & title) const [inline], [private]
Definition at line 4735 of file context.cpp.
    {
      const MemberList *ml = m_groupDef->getMemberList(type);
      return ml ? TemplateVariant(MemberListInfoContext::alloc(m_groupDef,relPathAsString(),ml,title,""))
                : TemplateVariant(false);
    }
References MemberListInfoContext::alloc(), GroupDef::getMemberList(), m_groupDef, DefinitionContext< ModuleContext::Private >::relPathAsString(), and title().
Referenced by createDetailedEnums(), createDetailedEnumValues(), createDetailedEvents(), createDetailedFriends(), createDetailedFunctions(), createDetailedMacros(), createDetailedPrivateSlots(), createDetailedProperties(), createDetailedProtectedSlots(), createDetailedPublicSlots(), createDetailedSignals(), createDetailedTypedefs(), createDetailedVariables(), createEnums(), createEnumValues(), createEvents(), createFriends(), createFunctions(), createMacros(), createPrivateSlots(), createProperties(), createProtectedSlots(), createPublicSlots(), createSignals(), createTypedefs(), and createVariables().
createMemberList() [2/2]
TemplateVariant ModuleContext::Private::createMemberList (MemberListType type, const QCString & title) const [inline], [private]
Definition at line 4735 of file context.cpp.
    {
      const MemberList *ml = m_groupDef->getMemberList(type);
      return ml ? TemplateVariant(MemberListInfoContext::alloc(m_groupDef,relPathAsString(),ml,title,""))
                : TemplateVariant(false);
    }
References MemberListInfoContext::alloc().
createModules() [1/2]
TemplateVariant ModuleContext::Private::createModules () const [inline], [private]
Definition at line 4643 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getSubGroups().size());
      for (const auto &gd : m_groupDef->getSubGroups())
      {
        if (gd->isVisible())
        {
          list.push_back(ModuleContext::alloc(gd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ModuleContext::alloc(), TemplateImmutableList::alloc(), GroupDef::getSubGroups(), and m_groupDef.
createModules() [2/2]
TemplateVariant ModuleContext::Private::createModules () const [inline], [private]
Definition at line 4643 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getSubGroups().size());
      for (const auto &gd : m_groupDef->getSubGroups())
      {
        if (gd->isVisible())
        {
          list.push_back(ModuleContext::alloc(gd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References ModuleContext::alloc(), and TemplateImmutableList::alloc().
createNamespaces() [1/2]
TemplateVariant ModuleContext::Private::createNamespaces () const [inline], [private]
Definition at line 4689 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getNamespaces().size());
      for (const auto &nd : m_groupDef->getNamespaces())
      {
        if (nd->isLinkable() && !nd->isConstantGroup())
        {
          list.push_back(NamespaceContext::alloc(nd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References NamespaceContext::alloc(), TemplateImmutableList::alloc(), GroupDef::getNamespaces(), m_groupDef, and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
createNamespaces() [2/2]
TemplateVariant ModuleContext::Private::createNamespaces () const [inline], [private]
Definition at line 4689 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getNamespaces().size());
      for (const auto &nd : m_groupDef->getNamespaces())
      {
        if (nd->isLinkable() && !nd->isConstantGroup())
        {
          list.push_back(NamespaceContext::alloc(nd));
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References NamespaceContext::alloc(), and TemplateImmutableList::alloc().
createPages() [1/2]
TemplateVariant ModuleContext::Private::createPages () const [inline], [private]
Definition at line 4725 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getPages().size());
      for (const auto &ex : m_groupDef->getPages())
      {
        list.push_back(PageContext::alloc(ex,FALSE,TRUE));
      }
      return TemplateImmutableList::alloc(list);
    }
References PageContext::alloc(), TemplateImmutableList::alloc(), FALSE, GroupDef::getPages(), m_groupDef, LinkedRefMap< T, Hash, KeyEqual, Map >::size(), and TRUE.
createPages() [2/2]
TemplateVariant ModuleContext::Private::createPages () const [inline], [private]
Definition at line 4725 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_groupDef->getPages().size());
      for (const auto &ex : m_groupDef->getPages())
      {
        list.push_back(PageContext::alloc(ex,FALSE,TRUE));
      }
      return TemplateImmutableList::alloc(list);
    }
References PageContext::alloc(), TemplateImmutableList::alloc(), FALSE, and TRUE.
createPrivateSlots() [1/2]
TemplateVariant ModuleContext::Private::createPrivateSlots () const [inline], [private]
Definition at line 4782 of file context.cpp.
    {
      return createMemberList(MemberListType_priSlots,theTranslator->trPrivateSlots());
    }
References createMemberList(), MemberListType_priSlots, theTranslator, and Translator::trPrivateSlots().
createPrivateSlots() [2/2]
TemplateVariant ModuleContext::Private::createPrivateSlots () const [inline], [private]
Definition at line 4782 of file context.cpp.
    {
      return createMemberList(MemberListType_priSlots,theTranslator->trPrivateSlots());
    }
References MemberListType_priSlots, theTranslator, and Translator::trPrivateSlots().
createProperties() [1/2]
TemplateVariant ModuleContext::Private::createProperties () const [inline], [private]
Definition at line 4790 of file context.cpp.
    {
      return createMemberList(MemberListType_properties,theTranslator->trProperties());
    }
References createMemberList(), MemberListType_properties, theTranslator, and Translator::trProperties().
createProperties() [2/2]
TemplateVariant ModuleContext::Private::createProperties () const [inline], [private]
Definition at line 4790 of file context.cpp.
    {
      return createMemberList(MemberListType_properties,theTranslator->trProperties());
    }
References MemberListType_properties, theTranslator, and Translator::trProperties().
createProtectedSlots() [1/2]
TemplateVariant ModuleContext::Private::createProtectedSlots () const [inline], [private]
Definition at line 4778 of file context.cpp.
    {
      return createMemberList(MemberListType_proSlots,theTranslator->trProtectedSlots());
    }
References createMemberList(), MemberListType_proSlots, theTranslator, and Translator::trProtectedSlots().
createProtectedSlots() [2/2]
TemplateVariant ModuleContext::Private::createProtectedSlots () const [inline], [private]
Definition at line 4778 of file context.cpp.
    {
      return createMemberList(MemberListType_proSlots,theTranslator->trProtectedSlots());
    }
References MemberListType_proSlots, theTranslator, and Translator::trProtectedSlots().
createPublicSlots() [1/2]
TemplateVariant ModuleContext::Private::createPublicSlots () const [inline], [private]
Definition at line 4774 of file context.cpp.
    {
      return createMemberList(MemberListType_pubSlots,theTranslator->trPublicSlots());
    }
References createMemberList(), MemberListType_pubSlots, theTranslator, and Translator::trPublicSlots().
createPublicSlots() [2/2]
TemplateVariant ModuleContext::Private::createPublicSlots () const [inline], [private]
Definition at line 4774 of file context.cpp.
    {
      return createMemberList(MemberListType_pubSlots,theTranslator->trPublicSlots());
    }
References MemberListType_pubSlots, theTranslator, and Translator::trPublicSlots().
createSignals() [1/2]
TemplateVariant ModuleContext::Private::createSignals () const [inline], [private]
Definition at line 4770 of file context.cpp.
    {
      return createMemberList(MemberListType_signals,theTranslator->trSignals());
    }
References createMemberList(), MemberListType_signals, theTranslator, and Translator::trSignals().
createSignals() [2/2]
TemplateVariant ModuleContext::Private::createSignals () const [inline], [private]
Definition at line 4770 of file context.cpp.
    {
      return createMemberList(MemberListType_signals,theTranslator->trSignals());
    }
References MemberListType_signals, theTranslator, and Translator::trSignals().
createTypedefs() [1/2]
TemplateVariant ModuleContext::Private::createTypedefs () const [inline], [private]
Definition at line 4745 of file context.cpp.
    {
      return createMemberList(MemberListType_decTypedefMembers,theTranslator->trTypedefs());
    }
References createMemberList(), MemberListType_decTypedefMembers, theTranslator, and Translator::trTypedefs().
createTypedefs() [2/2]
TemplateVariant ModuleContext::Private::createTypedefs () const [inline], [private]
Definition at line 4745 of file context.cpp.
    {
      return createMemberList(MemberListType_decTypedefMembers,theTranslator->trTypedefs());
    }
References MemberListType_decTypedefMembers, theTranslator, and Translator::trTypedefs().
createVariables() [1/2]
TemplateVariant ModuleContext::Private::createVariables () const [inline], [private]
Definition at line 4764 of file context.cpp.
    {
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      return createMemberList(MemberListType_decVarMembers, sliceOpt ? theTranslator->trConstants() :
                                                                       theTranslator->trVariables());
    }
References Config_getBool, createMemberList(), MemberListType_decVarMembers, theTranslator, Translator::trConstants(), and Translator::trVariables().
createVariables() [2/2]
TemplateVariant ModuleContext::Private::createVariables () const [inline], [private]
Definition at line 4764 of file context.cpp.
    {
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      return createMemberList(MemberListType_decVarMembers, sliceOpt ? theTranslator->trConstants() :
                                                                       theTranslator->trVariables());
    }
References Config_getBool, MemberListType_decVarMembers, theTranslator, Translator::trConstants(), and Translator::trVariables().
detailedEnums() [1/2]
TemplateVariant ModuleContext::Private::detailedEnums () const [inline], [private]
Definition at line 4573 of file context.cpp.
{ return m_cachable.detailedEnums.get(this); }
References ModuleContext::Private::Cachable::detailedEnums, and m_cachable.
detailedEnums() [2/2]
TemplateVariant ModuleContext::Private::detailedEnums () const [inline], [private]
Definition at line 4573 of file context.cpp.
{ return m_cachable.detailedEnums.get(this); }
detailedEnumValues() [1/2]
TemplateVariant ModuleContext::Private::detailedEnumValues () const [inline], [private]
Definition at line 4574 of file context.cpp.
{ return m_cachable.detailedEnumValues.get(this); }
References ModuleContext::Private::Cachable::detailedEnumValues, and m_cachable.
detailedEnumValues() [2/2]
TemplateVariant ModuleContext::Private::detailedEnumValues () const [inline], [private]
Definition at line 4574 of file context.cpp.
{ return m_cachable.detailedEnumValues.get(this); }
detailedEvents() [1/2]
TemplateVariant ModuleContext::Private::detailedEvents () const [inline], [private]
Definition at line 4581 of file context.cpp.
{ return m_cachable.detailedEvents.get(this); }
References ModuleContext::Private::Cachable::detailedEvents, and m_cachable.
detailedEvents() [2/2]
TemplateVariant ModuleContext::Private::detailedEvents () const [inline], [private]
Definition at line 4581 of file context.cpp.
{ return m_cachable.detailedEvents.get(this); }
detailedFriends() [1/2]
TemplateVariant ModuleContext::Private::detailedFriends () const [inline], [private]
Definition at line 4583 of file context.cpp.
{ return m_cachable.detailedFriends.get(this); }
References ModuleContext::Private::Cachable::detailedFriends, and m_cachable.
detailedFriends() [2/2]
TemplateVariant ModuleContext::Private::detailedFriends () const [inline], [private]
Definition at line 4583 of file context.cpp.
{ return m_cachable.detailedFriends.get(this); }
detailedFunctions() [1/2]
TemplateVariant ModuleContext::Private::detailedFunctions () const [inline], [private]
Definition at line 4575 of file context.cpp.
{ return m_cachable.detailedFunctions.get(this); }
References ModuleContext::Private::Cachable::detailedFunctions, and m_cachable.
detailedFunctions() [2/2]
TemplateVariant ModuleContext::Private::detailedFunctions () const [inline], [private]
Definition at line 4575 of file context.cpp.
{ return m_cachable.detailedFunctions.get(this); }
detailedMacros() [1/2]
TemplateVariant ModuleContext::Private::detailedMacros () const [inline], [private]
Definition at line 4571 of file context.cpp.
{ return m_cachable.detailedMacros.get(this); }
References ModuleContext::Private::Cachable::detailedMacros, and m_cachable.
detailedMacros() [2/2]
TemplateVariant ModuleContext::Private::detailedMacros () const [inline], [private]
Definition at line 4571 of file context.cpp.
{ return m_cachable.detailedMacros.get(this); }
detailedPrivateSlots() [1/2]
TemplateVariant ModuleContext::Private::detailedPrivateSlots () const [inline], [private]
Definition at line 4580 of file context.cpp.
{ return m_cachable.detailedPrivateSlots.get(this); }
References ModuleContext::Private::Cachable::detailedPrivateSlots, and m_cachable.
detailedPrivateSlots() [2/2]
TemplateVariant ModuleContext::Private::detailedPrivateSlots () const [inline], [private]
Definition at line 4580 of file context.cpp.
{ return m_cachable.detailedPrivateSlots.get(this); }
detailedProperties() [1/2]
TemplateVariant ModuleContext::Private::detailedProperties () const [inline], [private]
Definition at line 4582 of file context.cpp.
{ return m_cachable.detailedProperties.get(this); }
References ModuleContext::Private::Cachable::detailedProperties, and m_cachable.
detailedProperties() [2/2]
TemplateVariant ModuleContext::Private::detailedProperties () const [inline], [private]
Definition at line 4582 of file context.cpp.
{ return m_cachable.detailedProperties.get(this); }
detailedProtectedSlots() [1/2]
TemplateVariant ModuleContext::Private::detailedProtectedSlots () const [inline], [private]
Definition at line 4579 of file context.cpp.
{ return m_cachable.detailedProtectedSlots.get(this); }
References ModuleContext::Private::Cachable::detailedProtectedSlots, and m_cachable.
detailedProtectedSlots() [2/2]
TemplateVariant ModuleContext::Private::detailedProtectedSlots () const [inline], [private]
Definition at line 4579 of file context.cpp.
{ return m_cachable.detailedProtectedSlots.get(this); }
detailedPublicSlots() [1/2]
TemplateVariant ModuleContext::Private::detailedPublicSlots () const [inline], [private]
Definition at line 4578 of file context.cpp.
{ return m_cachable.detailedPublicSlots.get(this); }
References ModuleContext::Private::Cachable::detailedPublicSlots, and m_cachable.
detailedPublicSlots() [2/2]
TemplateVariant ModuleContext::Private::detailedPublicSlots () const [inline], [private]
Definition at line 4578 of file context.cpp.
{ return m_cachable.detailedPublicSlots.get(this); }
detailedSignals() [1/2]
TemplateVariant ModuleContext::Private::detailedSignals () const [inline], [private]
Definition at line 4577 of file context.cpp.
{ return m_cachable.detailedSignals.get(this); }
References ModuleContext::Private::Cachable::detailedSignals, and m_cachable.
detailedSignals() [2/2]
TemplateVariant ModuleContext::Private::detailedSignals () const [inline], [private]
Definition at line 4577 of file context.cpp.
{ return m_cachable.detailedSignals.get(this); }
detailedTypedefs() [1/2]
TemplateVariant ModuleContext::Private::detailedTypedefs () const [inline], [private]
Definition at line 4572 of file context.cpp.
{ return m_cachable.detailedTypedefs.get(this); }
References ModuleContext::Private::Cachable::detailedTypedefs, and m_cachable.
detailedTypedefs() [2/2]
TemplateVariant ModuleContext::Private::detailedTypedefs () const [inline], [private]
Definition at line 4572 of file context.cpp.
{ return m_cachable.detailedTypedefs.get(this); }
detailedVariables() [1/2]
TemplateVariant ModuleContext::Private::detailedVariables () const [inline], [private]
Definition at line 4576 of file context.cpp.
{ return m_cachable.detailedVariables.get(this); }
References ModuleContext::Private::Cachable::detailedVariables, and m_cachable.
detailedVariables() [2/2]
TemplateVariant ModuleContext::Private::detailedVariables () const [inline], [private]
Definition at line 4576 of file context.cpp.
{ return m_cachable.detailedVariables.get(this); }
dirs() [1/2]
TemplateVariant ModuleContext::Private::dirs () const [inline], [private]
Definition at line 4552 of file context.cpp.
{ return m_cachable.dirs.get(this); }
References ModuleContext::Private::Cachable::dirs, and m_cachable.
dirs() [2/2]
TemplateVariant ModuleContext::Private::dirs () const [inline], [private]
Definition at line 4552 of file context.cpp.
{ return m_cachable.dirs.get(this); }
enums() [1/2]
TemplateVariant ModuleContext::Private::enums () const [inline], [private]
Definition at line 4559 of file context.cpp.
{ return m_cachable.enums.get(this); }
References ModuleContext::Private::Cachable::enums, and m_cachable.
enums() [2/2]
TemplateVariant ModuleContext::Private::enums () const [inline], [private]
Definition at line 4559 of file context.cpp.
{ return m_cachable.enums.get(this); }
enumValues() [1/2]
TemplateVariant ModuleContext::Private::enumValues () const [inline], [private]
Definition at line 4560 of file context.cpp.
{ return m_cachable.enums.get(this); }
References ModuleContext::Private::Cachable::enums, and m_cachable.
enumValues() [2/2]
TemplateVariant ModuleContext::Private::enumValues () const [inline], [private]
Definition at line 4560 of file context.cpp.
{ return m_cachable.enums.get(this); }
events() [1/2]
TemplateVariant ModuleContext::Private::events () const [inline], [private]
Definition at line 4567 of file context.cpp.
{ return m_cachable.events.get(this); }
References ModuleContext::Private::Cachable::events, and m_cachable.
events() [2/2]
TemplateVariant ModuleContext::Private::events () const [inline], [private]
Definition at line 4567 of file context.cpp.
{ return m_cachable.events.get(this); }
examples() [1/2]
TemplateVariant ModuleContext::Private::examples () const [inline], [private]
Definition at line 4550 of file context.cpp.
{ return m_cachable.examples.get(this); }
References ModuleContext::Private::Cachable::examples, and m_cachable.
examples() [2/2]
TemplateVariant ModuleContext::Private::examples () const [inline], [private]
Definition at line 4550 of file context.cpp.
{ return m_cachable.examples.get(this); }
fields() [1/2]
StringVector ModuleContext::Private::fields () const [inline]
Definition at line 4540 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector ModuleContext::Private::fields () const [inline]
Definition at line 4540 of file context.cpp.
{ return s_inst.fields(); }
files() [1/2]
TemplateVariant ModuleContext::Private::files () const [inline], [private]
Definition at line 4553 of file context.cpp.
{ return m_cachable.files.get(this); }
References ModuleContext::Private::Cachable::files, and m_cachable.
files() [2/2]
TemplateVariant ModuleContext::Private::files () const [inline], [private]
Definition at line 4553 of file context.cpp.
{ return m_cachable.files.get(this); }
friends() [1/2]
TemplateVariant ModuleContext::Private::friends () const [inline], [private]
Definition at line 4569 of file context.cpp.
{ return m_cachable.friends.get(this); }
References ModuleContext::Private::Cachable::friends, and m_cachable.
friends() [2/2]
TemplateVariant ModuleContext::Private::friends () const [inline], [private]
Definition at line 4569 of file context.cpp.
{ return m_cachable.friends.get(this); }
functions() [1/2]
TemplateVariant ModuleContext::Private::functions () const [inline], [private]
Definition at line 4561 of file context.cpp.
{ return m_cachable.functions.get(this); }
References ModuleContext::Private::Cachable::functions, and m_cachable.
functions() [2/2]
TemplateVariant ModuleContext::Private::functions () const [inline], [private]
Definition at line 4561 of file context.cpp.
{ return m_cachable.functions.get(this); }
get() [1/2]
TemplateVariant ModuleContext::Private::get (const QCString & n) const [inline]
Definition at line 4539 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant ModuleContext::Private::get (const QCString & n) const [inline]
Definition at line 4539 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
getGroupGraph() [1/2]
DotGroupCollaborationPtr ModuleContext::Private::getGroupGraph () const [inline], [private]
Definition at line 4585 of file context.cpp.
{ return m_cachable.groupGraph.get(this); }
References ModuleContext::Private::Cachable::groupGraph, and m_cachable.
Referenced by groupGraph(), and hasGroupGraph().
getGroupGraph() [2/2]
DotGroupCollaborationPtr ModuleContext::Private::getGroupGraph () const [inline], [private]
Definition at line 4585 of file context.cpp.
{ return m_cachable.groupGraph.get(this); }
groupGraph() [1/2]
TemplateVariant ModuleContext::Private::groupGraph () const [inline], [private]
Definition at line 4599 of file context.cpp.
    {
      TextStream t;
      bool haveDot = Config_getBool(HAVE_DOT);
      bool groupGraphs = Config_getBool(GROUP_GRAPHS);
      if (haveDot && groupGraphs)
      {
        DotGroupCollaborationPtr graph = getGroupGraph();
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              graph->writeGraph(t,GOF_BITMAP,
                                EOF_Html,
                                g_globals.outputDir,
                                g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_groupDef->getOutputFileBase()),
                                relPathAsString(),
                                TRUE,
                                g_globals.dynSectionId);
            }
            break;
          case ContextOutputFormat_Latex:
            {
              graph->writeGraph(t,GOF_EPS,
                                EOF_LaTeX,
                                g_globals.outputDir,
                                g_globals.outputDir+Portable::pathSeparator()+m_groupDef->getOutputFileBase()+".tex",
                                relPathAsString(),
                                TRUE,
                                g_globals.dynSectionId);
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References addHtmlExtensionIfMissing(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, getGroupGraph(), GroupDef::getOutputFileBase(), GOF_BITMAP, GOF_EPS, m_groupDef, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), DefinitionContext< ModuleContext::Private >::relPathAsString(), TextStream::str(), and TRUE.
groupGraph() [2/2]
TemplateVariant ModuleContext::Private::groupGraph () const [inline], [private]
Definition at line 4599 of file context.cpp.
    {
      TextStream t;
      bool haveDot = Config_getBool(HAVE_DOT);
      bool groupGraphs = Config_getBool(GROUP_GRAPHS);
      if (haveDot && groupGraphs)
      {
        DotGroupCollaborationPtr graph = getGroupGraph();
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              graph->writeGraph(t,GOF_BITMAP,
                                EOF_Html,
                                g_globals.outputDir,
                                g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_groupDef->getOutputFileBase()),
                                relPathAsString(),
                                TRUE,
                                g_globals.dynSectionId);
            }
            break;
          case ContextOutputFormat_Latex:
            {
              graph->writeGraph(t,GOF_EPS,
                                EOF_LaTeX,
                                g_globals.outputDir,
                                g_globals.outputDir+Portable::pathSeparator()+m_groupDef->getOutputFileBase()+".tex",
                                relPathAsString(),
                                TRUE,
                                g_globals.dynSectionId);
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References addHtmlExtensionIfMissing(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, GOF_BITMAP, GOF_EPS, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), TextStream::str(), and TRUE.
hasDetails() [1/2]
TemplateVariant ModuleContext::Private::hasDetails () const [inline], [private]
Definition at line 4548 of file context.cpp.
{ return m_groupDef->hasDetailedDescription(); }
References GroupDef::hasDetailedDescription(), and m_groupDef.
hasDetails() [2/2]
TemplateVariant ModuleContext::Private::hasDetails () const [inline], [private]
Definition at line 4548 of file context.cpp.
{ return m_groupDef->hasDetailedDescription(); }
hasGroupGraph() [1/2]
TemplateVariant ModuleContext::Private::hasGroupGraph () const [inline], [private]
Definition at line 4587 of file context.cpp.
    {
      bool result=FALSE;
      bool haveDot = Config_getBool(HAVE_DOT);
      bool groupGraphs = Config_getBool(GROUP_GRAPHS);
      if (haveDot && groupGraphs)
      {
        DotGroupCollaborationPtr graph = getGroupGraph();
        result = !graph->isTrivial();
      }
      return result;
    }
References Config_getBool, FALSE, and getGroupGraph().
hasGroupGraph() [2/2]
TemplateVariant ModuleContext::Private::hasGroupGraph () const [inline], [private]
Definition at line 4587 of file context.cpp.
    {
      bool result=FALSE;
      bool haveDot = Config_getBool(HAVE_DOT);
      bool groupGraphs = Config_getBool(GROUP_GRAPHS);
      if (haveDot && groupGraphs)
      {
        DotGroupCollaborationPtr graph = getGroupGraph();
        result = !graph->isTrivial();
      }
      return result;
    }
References Config_getBool, and FALSE.
highlight() [1/2]
TemplateVariant ModuleContext::Private::highlight () const [inline], [private]
Definition at line 4545 of file context.cpp.
{ return TemplateVariant("modules"); }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant ModuleContext::Private::highlight () const [inline], [private]
Definition at line 4545 of file context.cpp.
{ return TemplateVariant("modules"); }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
inlineClasses() [1/2]
TemplateVariant ModuleContext::Private::inlineClasses () const [inline], [private]
Definition at line 4584 of file context.cpp.
{ return m_cachable.inlineClasses.get(this); }
References ModuleContext::Private::Cachable::inlineClasses, and m_cachable.
inlineClasses() [2/2]
TemplateVariant ModuleContext::Private::inlineClasses () const [inline], [private]
Definition at line 4584 of file context.cpp.
{ return m_cachable.inlineClasses.get(this); }
macros() [1/2]
TemplateVariant ModuleContext::Private::macros () const [inline], [private]
Definition at line 4557 of file context.cpp.
{ return m_cachable.macros.get(this); }
References m_cachable, and ModuleContext::Private::Cachable::macros.
macros() [2/2]
TemplateVariant ModuleContext::Private::macros () const [inline], [private]
Definition at line 4557 of file context.cpp.
{ return m_cachable.macros.get(this); }
memberGroups() [1/2]
TemplateVariant ModuleContext::Private::memberGroups () const [inline], [private]
Definition at line 4570 of file context.cpp.
{ return m_cachable.memberGroups.get(this); }
References m_cachable, and ModuleContext::Private::Cachable::memberGroups.
memberGroups() [2/2]
TemplateVariant ModuleContext::Private::memberGroups () const [inline], [private]
Definition at line 4570 of file context.cpp.
{ return m_cachable.memberGroups.get(this); }
modules() [1/2]
TemplateVariant ModuleContext::Private::modules () const [inline], [private]
Definition at line 4549 of file context.cpp.
{ return m_cachable.modules.get(this); }
References m_cachable, and ModuleContext::Private::Cachable::modules.
modules() [2/2]
TemplateVariant ModuleContext::Private::modules () const [inline], [private]
Definition at line 4549 of file context.cpp.
{ return m_cachable.modules.get(this); }
namespaces() [1/2]
TemplateVariant ModuleContext::Private::namespaces () const [inline], [private]
Definition at line 4555 of file context.cpp.
{ return m_cachable.namespaces.get(this); }
References m_cachable, and ModuleContext::Private::Cachable::namespaces.
namespaces() [2/2]
TemplateVariant ModuleContext::Private::namespaces () const [inline], [private]
Definition at line 4555 of file context.cpp.
{ return m_cachable.namespaces.get(this); }
pages() [1/2]
TemplateVariant ModuleContext::Private::pages () const [inline], [private]
Definition at line 4551 of file context.cpp.
{ return m_cachable.pages.get(this); }
References m_cachable, and ModuleContext::Private::Cachable::pages.
pages() [2/2]
TemplateVariant ModuleContext::Private::pages () const [inline], [private]
Definition at line 4551 of file context.cpp.
{ return m_cachable.pages.get(this); }
privateSlots() [1/2]
TemplateVariant ModuleContext::Private::privateSlots () const [inline], [private]
Definition at line 4566 of file context.cpp.
{ return m_cachable.privateSlots.get(this); }
References m_cachable, and ModuleContext::Private::Cachable::privateSlots.
privateSlots() [2/2]
TemplateVariant ModuleContext::Private::privateSlots () const [inline], [private]
Definition at line 4566 of file context.cpp.
{ return m_cachable.privateSlots.get(this); }
properties() [1/2]
TemplateVariant ModuleContext::Private::properties () const [inline], [private]
Definition at line 4568 of file context.cpp.
{ return m_cachable.properties.get(this); }
References m_cachable, and ModuleContext::Private::Cachable::properties.
properties() [2/2]
TemplateVariant ModuleContext::Private::properties () const [inline], [private]
Definition at line 4568 of file context.cpp.
{ return m_cachable.properties.get(this); }
protectedSlots() [1/2]
TemplateVariant ModuleContext::Private::protectedSlots () const [inline], [private]
Definition at line 4565 of file context.cpp.
{ return m_cachable.protectedSlots.get(this); }
References m_cachable, and ModuleContext::Private::Cachable::protectedSlots.
protectedSlots() [2/2]
TemplateVariant ModuleContext::Private::protectedSlots () const [inline], [private]
Definition at line 4565 of file context.cpp.
{ return m_cachable.protectedSlots.get(this); }
publicSlots() [1/2]
TemplateVariant ModuleContext::Private::publicSlots () const [inline], [private]
Definition at line 4564 of file context.cpp.
{ return m_cachable.publicSlots.get(this); }
References m_cachable, and ModuleContext::Private::Cachable::publicSlots.
publicSlots() [2/2]
TemplateVariant ModuleContext::Private::publicSlots () const [inline], [private]
Definition at line 4564 of file context.cpp.
{ return m_cachable.publicSlots.get(this); }
signals() [1/2]
TemplateVariant ModuleContext::Private::signals () const [inline], [private]
Definition at line 4563 of file context.cpp.
{ return m_cachable.signals.get(this); }
References m_cachable, and ModuleContext::Private::Cachable::signals.
signals() [2/2]
TemplateVariant ModuleContext::Private::signals () const [inline], [private]
Definition at line 4563 of file context.cpp.
{ return m_cachable.signals.get(this); }
subHighlight() [1/2]
TemplateVariant ModuleContext::Private::subHighlight () const [inline], [private]
Definition at line 4546 of file context.cpp.
{ return TemplateVariant(""); }
subHighlight() [2/2]
TemplateVariant ModuleContext::Private::subHighlight () const [inline], [private]
Definition at line 4546 of file context.cpp.
{ return TemplateVariant(""); }
title() [1/2]
TemplateVariant ModuleContext::Private::title () const [inline], [private]
Definition at line 4544 of file context.cpp.
{ return TemplateVariant(m_groupDef->groupTitle()); }
References GroupDef::groupTitle(), and m_groupDef.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), createMemberList(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant ModuleContext::Private::title () const [inline], [private]
Definition at line 4544 of file context.cpp.
{ return TemplateVariant(m_groupDef->groupTitle()); }
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
typedefs() [1/2]
TemplateVariant ModuleContext::Private::typedefs () const [inline], [private]
Definition at line 4558 of file context.cpp.
{ return m_cachable.typedefs.get(this); }
References m_cachable, and ModuleContext::Private::Cachable::typedefs.
typedefs() [2/2]
TemplateVariant ModuleContext::Private::typedefs () const [inline], [private]
Definition at line 4558 of file context.cpp.
{ return m_cachable.typedefs.get(this); }
variables() [1/2]
TemplateVariant ModuleContext::Private::variables () const [inline], [private]
Definition at line 4562 of file context.cpp.
{ return m_cachable.variables.get(this); }
References m_cachable, and ModuleContext::Private::Cachable::variables.
variables() [2/2]
TemplateVariant ModuleContext::Private::variables () const [inline], [private]
Definition at line 4562 of file context.cpp.
{ return m_cachable.variables.get(this); }
Member Data Documentation
m_cachable
Cachable ModuleContext::Private::m_cachable [private]
Definition at line 4919 of file context.cpp.
Referenced by classes(), constantgroups(), detailedEnums(), detailedEnumValues(), detailedEvents(), detailedFriends(), detailedFunctions(), detailedMacros(), detailedPrivateSlots(), detailedProperties(), detailedProtectedSlots(), detailedPublicSlots(), detailedSignals(), detailedTypedefs(), detailedVariables(), dirs(), enums(), enumValues(), events(), examples(), files(), friends(), functions(), getGroupGraph(), inlineClasses(), macros(), memberGroups(), modules(), namespaces(), pages(), privateSlots(), properties(), protectedSlots(), publicSlots(), signals(), typedefs(), and variables().
m_groupDef
const GroupDef * ModuleContext::Private::m_groupDef [private]
Definition at line 4878 of file context.cpp.
Referenced by createClasses(), createConstantgroups(), createDetailedFunctions(), createDirs(), createExamples(), createFiles(), createFunctions(), createGroupGraph(), createInlineClasses(), createMemberGroups(), createMemberList(), createModules(), createNamespaces(), createPages(), groupGraph(), hasDetails(), and title().
s_inst
const PropertyMap< ModuleContext::Private > ModuleContext::Private::s_inst [static], [private]
Definition at line 4920 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp