TranslatorEnglish Class Reference
#include <translator_en.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString trPackageList ()
virtual QCString trFlowchart ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString trPackageList ()
virtual QCString trFlowchart ()
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include `translator.h` or `translator_adapter.h` here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 43 of file translator_en.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorEnglish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Reimplemented in TranslatorJapaneseEn, TranslatorKoreanEn, TranslatorJapaneseEn, and TranslatorKoreanEn.
Definition at line 82 of file translator_en.h.
    {
      return "0x409 English (United States)";
    }
getLanguageString() [2/2]
virtual QCString TranslatorEnglish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Reimplemented in TranslatorJapaneseEn, TranslatorKoreanEn, TranslatorJapaneseEn, and TranslatorKoreanEn.
Definition at line 82 of file translator_en.h.
    {
      return "0x409 English (United States)";
    }
idLanguage() [1/2]
virtual QCString TranslatorEnglish::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Reimplemented in TranslatorJapaneseEn, TranslatorKoreanEn, TranslatorJapaneseEn, and TranslatorKoreanEn.
Definition at line 55 of file translator_en.h.
    { return "english"; }
idLanguage() [2/2]
virtual QCString TranslatorEnglish::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Reimplemented in TranslatorJapaneseEn, TranslatorKoreanEn, TranslatorJapaneseEn, and TranslatorKoreanEn.
Definition at line 55 of file translator_en.h.
    { return "english"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorEnglish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Reimplemented in TranslatorJapaneseEn, TranslatorKoreanEn, TranslatorJapaneseEn, and TranslatorKoreanEn.
Definition at line 72 of file translator_en.h.
    {
      return "";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorEnglish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Reimplemented in TranslatorJapaneseEn, TranslatorKoreanEn, TranslatorJapaneseEn, and TranslatorKoreanEn.
Definition at line 72 of file translator_en.h.
    {
      return "";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorEnglish::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1906 of file translator_en.h.
    { return "Additional Inherited Members"; }
Referenced by TranslatorAdapter_1_8_0::trAdditionalInheritedMembers().
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorEnglish::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1906 of file translator_en.h.
    { return "Additional Inherited Members"; }
trAll() [1/2]
virtual QCString TranslatorEnglish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1420 of file translator_en.h.
    {
      return "All";
    }
trAll() [2/2]
virtual QCString TranslatorEnglish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1420 of file translator_en.h.
    {
      return "All";
    }
trAndMore() [1/2]
virtual QCString TranslatorEnglish::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1884 of file translator_en.h.
    { return "and "+number+" more..."; }
Referenced by TranslatorAdapter_1_8_0::trAndMore().
trAndMore() [2/2]
virtual QCString TranslatorEnglish::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1884 of file translator_en.h.
    { return "and "+number+" more..."; }
trAttention() [1/2]
virtual QCString TranslatorEnglish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 981 of file translator_en.h.
    {
      return "Attention";
    }
trAttention() [2/2]
virtual QCString TranslatorEnglish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 981 of file translator_en.h.
    {
      return "Attention";
    }
trAuthor() [1/2]
virtual QCString TranslatorEnglish::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1291 of file translator_en.h.
    {
      QCString result((first_capital ? "Author" : "author"));
      if (!singular) result+="s";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorEnglish::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1291 of file translator_en.h.
    {
      QCString result((first_capital ? "Author" : "author"));
      if (!singular) result+="s";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorEnglish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1149 of file translator_en.h.
    {
      return "Bug";
    }
trBug() [2/2]
virtual QCString TranslatorEnglish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1149 of file translator_en.h.
    {
      return "Bug";
    }
trBugList() [1/2]
virtual QCString TranslatorEnglish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1154 of file translator_en.h.
    {
      return "Bug List";
    }
trBugList() [2/2]
virtual QCString TranslatorEnglish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1154 of file translator_en.h.
    {
      return "Bug List";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorEnglish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1541 of file translator_en.h.
    {
      return "Here is the caller graph for this function:";
    }
Referenced by TranslatorAdapter_1_4_6::trCallerGraph().
trCallerGraph() [2/2]
virtual QCString TranslatorEnglish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1541 of file translator_en.h.
    {
      return "Here is the caller graph for this function:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorEnglish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1425 of file translator_en.h.
    {
      return "Here is the call graph for this function:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorEnglish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1425 of file translator_en.h.
    {
      return "Here is the call graph for this function:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorEnglish::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1860 of file translator_en.h.
    { return "Bibliography"; }
Referenced by TranslatorAdapter_1_7_5::trCiteReferences().
trCiteReferences() [2/2]
virtual QCString TranslatorEnglish::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1860 of file translator_en.h.
    { return "Bibliography"; }
trClass() [1/2]
virtual QCString TranslatorEnglish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1212 of file translator_en.h.
    {
      QCString result((first_capital ? "Class" : "class"));
      if (!singular) result+="es";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorEnglish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1212 of file translator_en.h.
    {
      QCString result((first_capital ? "Class" : "class"));
      if (!singular) result+="es";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorEnglish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 534 of file translator_en.h.
    {
      return "Inheritance diagram for "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorEnglish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 534 of file translator_en.h.
    {
      return "Inheritance diagram for "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorEnglish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 409 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structure Documentation";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Class Documentation";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorEnglish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 409 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structure Documentation";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Class Documentation";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorEnglish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1112 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structures";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorEnglish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1112 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structures";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorEnglish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 185 of file translator_en.h.
    { return "Class Hierarchy"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorEnglish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 185 of file translator_en.h.
    { return "Class Hierarchy"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorEnglish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 244 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Here is a hierarchical list of all entities:";
      }
      else
      {
        return "This inheritance list is sorted roughly, "
               "but not completely, alphabetically:";
      }
    }
References Config_getBool.
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorEnglish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 244 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Here is a hierarchical list of all entities:";
      }
      else
      {
        return "This inheritance list is sorted roughly, "
               "but not completely, alphabetically:";
      }
    }
References Config_getBool.
trClassMethods() [1/2]
virtual QCString TranslatorEnglish::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1944 of file translator_en.h.
    {
      return "Class Methods";
    }
Referenced by TranslatorAdapter_1_8_2::trClassMethods().
trClassMethods() [2/2]
virtual QCString TranslatorEnglish::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1944 of file translator_en.h.
    {
      return "Class Methods";
    }
trCode() [1/2]
virtual QCString TranslatorEnglish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 881 of file translator_en.h.
    {
      return "code";
    }
trCode() [2/2]
virtual QCString TranslatorEnglish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 881 of file translator_en.h.
    {
      return "code";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorEnglish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 836 of file translator_en.h.
    {
      return "Collaboration diagram for "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorEnglish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 836 of file translator_en.h.
    {
      return "Collaboration diagram for "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorEnglish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 382 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structure Index";
      }
      else
      {
        return "Class Index";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorEnglish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 382 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structure Index";
      }
      else
      {
        return "Class Index";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorEnglish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1596 of file translator_en.h.
    { return "Data Type Index"; }
Referenced by TranslatorAdapter_1_6_0::trCompoundIndexFortran().
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorEnglish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1596 of file translator_en.h.
    { return "Data Type Index"; }
trCompoundList() [1/2]
virtual QCString TranslatorEnglish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 189 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structures";
      }
      else
      {
        return "Class List";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorEnglish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 189 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structures";
      }
      else
      {
        return "Class List";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorEnglish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 267 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Here are the data structures with brief descriptions:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Here are the classes with brief descriptions:";
      }
      else
      {
        return "Here are the classes, structs, "
               "unions and interfaces with brief descriptions:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorEnglish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 267 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Here are the data structures with brief descriptions:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Here are the classes with brief descriptions:";
      }
      else
      {
        return "Here are the classes, structs, "
               "unions and interfaces with brief descriptions:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorEnglish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1569 of file translator_en.h.
    { return "Here are the data types with brief descriptions:"; }
Referenced by TranslatorAdapter_1_6_0::trCompoundListDescriptionFortran().
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorEnglish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1569 of file translator_en.h.
    { return "Here are the data types with brief descriptions:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorEnglish::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1561 of file translator_en.h.
    { return "Data Types List"; }
Referenced by TranslatorAdapter_1_6_0::trCompoundListFortran().
trCompoundListFortran() [2/2]
virtual QCString TranslatorEnglish::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1561 of file translator_en.h.
    { return "Data Types List"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorEnglish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 206 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Fields";
      }
      else
      {
        return "Class Members";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorEnglish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 206 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Fields";
      }
      else
      {
        return "Class Members";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorEnglish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 286 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll)
      {
        result+="documented ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct and union fields";
      }
      else
      {
        result+="class members";
      }
      result+=" with links to ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="the struct/union documentation for each field:";
        }
        else
        {
          result+="the class documentation for each member:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="the structures/unions they belong to:";
        }
        else
        {
          result+="the classes they belong to:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorEnglish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 286 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll)
      {
        result+="documented ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct and union fields";
      }
      else
      {
        result+="class members";
      }
      result+=" with links to ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="the struct/union documentation for each field:";
        }
        else
        {
          result+="the class documentation for each member:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="the structures/unions they belong to:";
        }
        else
        {
          result+="the classes they belong to:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorEnglish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1573 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll)
      {
        result+="documented ";
      }
      result+="data types members";
      result+=" with links to ";
      if (!extractAll)
      {
         result+="the data structure documentation for each member";
      }
      else
      {
         result+="the data types they belong to:";
      }
      return result;
    }
Referenced by TranslatorAdapter_1_6_0::trCompoundMembersDescriptionFortran().
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorEnglish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1573 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll)
      {
        result+="documented ";
      }
      result+="data types members";
      result+=" with links to ";
      if (!extractAll)
      {
         result+="the data structure documentation for each member";
      }
      else
      {
         result+="the data types they belong to:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorEnglish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1565 of file translator_en.h.
    { return "Data Fields"; }
Referenced by TranslatorAdapter_1_6_0::trCompoundMembersFortran().
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorEnglish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1565 of file translator_en.h.
    { return "Data Fields"; }
trCompoundReference() [1/2]
virtual QCString TranslatorEnglish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 609 of file translator_en.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorEnglish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 609 of file translator_en.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorEnglish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1637 of file translator_en.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Module"; break;
        case ClassDef::Struct: result+=" Type"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
Referenced by TranslatorAdapter_1_6_0::trCompoundReferenceFortran().
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorEnglish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1637 of file translator_en.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Module"; break;
        case ClassDef::Struct: result+=" Type"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorEnglish::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2234 of file translator_en.h.
    {
      QCString result=clName;
      if (isLocal) result+=" Local";
      switch(compType)
      {
        case ClassDef::Class: result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
Referenced by TranslatorAdapter_1_8_15::trCompoundReferenceSlice().
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorEnglish::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2234 of file translator_en.h.
    {
      QCString result=clName;
      if (isLocal) result+=" Local";
      switch(compType)
      {
        case ClassDef::Class: result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Interface"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Category"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorEnglish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 510 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structures";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorEnglish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 510 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structures";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trConcept() [1/2]
virtual QCString TranslatorEnglish::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2282 of file translator_en.h.
    {
      QCString result((first_capital ? "Concept" : "concept"));
      if (!singular) result+="s";
      return result;
    }
Referenced by TranslatorAdapter_1_9_2::trConcept().
trConcept() [2/2]
virtual QCString TranslatorEnglish::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2282 of file translator_en.h.
    {
      QCString result((first_capital ? "Concept" : "concept"));
      if (!singular) result+="s";
      return result;
    }
trConceptDefinition() [1/2]
virtual QCString TranslatorEnglish::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2318 of file translator_en.h.
    {
      return "Concept definition";
    }
Referenced by TranslatorAdapter_1_9_2::trConceptDefinition().
trConceptDefinition() [2/2]
virtual QCString TranslatorEnglish::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2318 of file translator_en.h.
    {
      return "Concept definition";
    }
trConceptDocumentation() [1/2]
virtual QCString TranslatorEnglish::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2305 of file translator_en.h.
    { return "Concept Documentation"; }
Referenced by TranslatorAdapter_1_9_2::trConceptDocumentation().
trConceptDocumentation() [2/2]
virtual QCString TranslatorEnglish::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2305 of file translator_en.h.
    { return "Concept Documentation"; }
trConceptIndex() [1/2]
virtual QCString TranslatorEnglish::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2301 of file translator_en.h.
    { return "Concept Index"; }
Referenced by TranslatorAdapter_1_9_2::trConceptIndex().
trConceptIndex() [2/2]
virtual QCString TranslatorEnglish::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2301 of file translator_en.h.
    { return "Concept Index"; }
trConceptList() [1/2]
virtual QCString TranslatorEnglish::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2297 of file translator_en.h.
    { return "Concept List"; }
Referenced by TranslatorAdapter_1_9_2::trConceptList().
trConceptList() [2/2]
virtual QCString TranslatorEnglish::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2297 of file translator_en.h.
    { return "Concept List"; }
trConceptListDescription() [1/2]
virtual QCString TranslatorEnglish::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2309 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="concepts with brief descriptions:";
      return result;
    }
Referenced by TranslatorAdapter_1_9_2::trConceptListDescription().
trConceptListDescription() [2/2]
virtual QCString TranslatorEnglish::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2309 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="concepts with brief descriptions:";
      return result;
    }
trConceptReference() [1/2]
virtual QCString TranslatorEnglish::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2289 of file translator_en.h.
    {
      QCString result=conceptName;
      result+=" Concept Reference";
      return result;
    }
Referenced by TranslatorAdapter_1_9_2::trConceptReference().
trConceptReference() [2/2]
virtual QCString TranslatorEnglish::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2289 of file translator_en.h.
    {
      QCString result=conceptName;
      result+=" Concept Reference";
      return result;
    }
trConstantDocumentation() [1/2]
virtual QCString TranslatorEnglish::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2142 of file translator_en.h.
    {
        return "Constant Documentation";
    }
Referenced by TranslatorAdapter_1_8_15::trConstantDocumentation().
trConstantDocumentation() [2/2]
virtual QCString TranslatorEnglish::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2142 of file translator_en.h.
    {
        return "Constant Documentation";
    }
trConstantGroupReference() [1/2]
virtual QCString TranslatorEnglish::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1981 of file translator_en.h.
    {
      QCString result=namespaceName;
      result+=" Constant Group Reference";
      return result;
    }
Referenced by TranslatorAdapter_1_8_4::trConstantGroupReference().
trConstantGroupReference() [2/2]
virtual QCString TranslatorEnglish::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1981 of file translator_en.h.
    {
      QCString result=namespaceName;
      result+=" Constant Group Reference";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorEnglish::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1977 of file translator_en.h.
    { return "Constant Groups"; }
Referenced by TranslatorAdapter_1_8_4::trConstantGroups().
trConstantGroups() [2/2]
virtual QCString TranslatorEnglish::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1977 of file translator_en.h.
    { return "Constant Groups"; }
trConstants() [1/2]
virtual QCString TranslatorEnglish::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2138 of file translator_en.h.
    {
        return "Constants";
    }
Referenced by TranslatorAdapter_1_8_15::trConstants().
trConstants() [2/2]
virtual QCString TranslatorEnglish::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2138 of file translator_en.h.
    {
        return "Constants";
    }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorEnglish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 846 of file translator_en.h.
    {
      return "Constructor & Destructor Documentation";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorEnglish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 846 of file translator_en.h.
    {
      return "Constructor & Destructor Documentation";
    }
trCopyright() [1/2]
virtual QCString TranslatorEnglish::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1864 of file translator_en.h.
    { return "Copyright"; }
Referenced by TranslatorAdapter_1_7_5::trCopyright().
trCopyright() [2/2]
virtual QCString TranslatorEnglish::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1864 of file translator_en.h.
    { return "Copyright"; }
trCustomReference() [1/2]
virtual QCString TranslatorEnglish::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2134 of file translator_en.h.
    { return name+" Reference"; }
References setup::name.
Referenced by TranslatorAdapter_1_8_15::trCustomReference().
trCustomReference() [2/2]
virtual QCString TranslatorEnglish::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2134 of file translator_en.h.
    { return name+" Reference"; }
References setup::name.
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorEnglish::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2264 of file translator_en.h.
    {
        return "Data Member Documentation";
    }
Referenced by TranslatorAdapter_1_8_15::trDataMemberDocumentation().
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorEnglish::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2264 of file translator_en.h.
    {
        return "Data Member Documentation";
    }
trDataMembers() [1/2]
virtual QCString TranslatorEnglish::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2260 of file translator_en.h.
    {
        return "Data Members";
    }
Referenced by TranslatorAdapter_1_8_15::trDataMembers().
trDataMembers() [2/2]
virtual QCString TranslatorEnglish::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2260 of file translator_en.h.
    {
        return "Data Members";
    }
trDataTypes() [1/2]
virtual QCString TranslatorEnglish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1620 of file translator_en.h.
    { return "Data Types"; }
Referenced by TranslatorAdapter_1_6_0::trDataTypes().
trDataTypes() [2/2]
virtual QCString TranslatorEnglish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1620 of file translator_en.h.
    { return "Data Types"; }
trDate() [1/2]
virtual QCString TranslatorEnglish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 548 of file translator_en.h.
    { return "Date"; }
trDate() [2/2]
virtual QCString TranslatorEnglish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 548 of file translator_en.h.
    { return "Date"; }
trDateTime() [1/2]
virtual QCString TranslatorEnglish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1821 of file translator_en.h.
    {
      static const char *days[] = { "Mon","Tue","Wed","Thu","Fri","Sat","Sun" };
      static const char *months[] = { "Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
Referenced by TranslatorAdapter_1_7_5::trDateTime().
trDateTime() [2/2]
virtual QCString TranslatorEnglish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1821 of file translator_en.h.
    {
      static const char *days[] = { "Mon","Tue","Wed","Thu","Fri","Sat","Sun" };
      static const char *months[] = { "Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorEnglish::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1837 of file translator_en.h.
    {
      static const char *days_short[] = { "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun" };
      static const char *days_full[] = { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorEnglish::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1837 of file translator_en.h.
    {
      static const char *days_short[] = { "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun" };
      static const char *days_full[] = { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayPeriod() [1/2]
virtual QCString TranslatorEnglish::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1849 of file translator_en.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
Referenced by TranslatorAdapter_1_7_5::trDayPeriod().
trDayPeriod() [2/2]
virtual QCString TranslatorEnglish::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1849 of file translator_en.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorEnglish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 813 of file translator_en.h.
    {
      return "Definition at line @0 of file @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorEnglish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 813 of file translator_en.h.
    {
      return "Definition at line @0 of file @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorEnglish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 173 of file translator_en.h.
    { return "defined in"; }
trDefinedIn() [2/2]
virtual QCString TranslatorEnglish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 173 of file translator_en.h.
    { return "defined in"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorEnglish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 817 of file translator_en.h.
    {
      return "Definition in file @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorEnglish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 817 of file translator_en.h.
    {
      return "Definition in file @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorEnglish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 480 of file translator_en.h.
    { return "Macro Definition Documentation"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorEnglish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 480 of file translator_en.h.
    { return "Macro Definition Documentation"; }
trDefines() [1/2]
virtual QCString TranslatorEnglish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 444 of file translator_en.h.
    { return "Macros"; }
trDefines() [2/2]
virtual QCString TranslatorEnglish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 444 of file translator_en.h.
    { return "Macros"; }
trDefineValue() [1/2]
virtual QCString TranslatorEnglish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1139 of file translator_en.h.
    {
      return "Value:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorEnglish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1139 of file translator_en.h.
    {
      return "Value:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorEnglish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 826 of file translator_en.h.
    {
      return "Deprecated";
    }
trDeprecated() [2/2]
virtual QCString TranslatorEnglish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 826 of file translator_en.h.
    {
      return "Deprecated";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorEnglish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1348 of file translator_en.h.
    {
      return "Deprecated List";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorEnglish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1348 of file translator_en.h.
    {
      return "Deprecated List";
    }
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorEnglish::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2274 of file translator_en.h.
    { return "Design Unit Documentation"; }
Referenced by trClassDocumentation(), and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorEnglish::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2274 of file translator_en.h.
    { return "Design Unit Documentation"; }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorEnglish::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2025 of file translator_en.h.
    { return "Design Unit Hierarchy"; }
Referenced by TranslatorAdapter_1_8_15::trDesignUnitHierarchy().
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorEnglish::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2025 of file translator_en.h.
    { return "Design Unit Hierarchy"; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorEnglish::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2040 of file translator_en.h.
    { return "Design Unit Index"; }
Referenced by TranslatorAdapter_1_8_15::trDesignUnitIndex().
trDesignUnitIndex() [2/2]
virtual QCString TranslatorEnglish::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2040 of file translator_en.h.
    { return "Design Unit Index"; }
trDesignUnitList() [1/2]
virtual QCString TranslatorEnglish::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2028 of file translator_en.h.
    { return "Design Unit List"; }
Referenced by TranslatorAdapter_1_8_15::trDesignUnitList().
trDesignUnitList() [2/2]
virtual QCString TranslatorEnglish::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2028 of file translator_en.h.
    { return "Design Unit List"; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorEnglish::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2034 of file translator_en.h.
    {
        return "Here is a list of all design unit members with links to "
            "the Entities they belong to:";
    }
Referenced by TranslatorAdapter_1_8_15::trDesignUnitListDescription().
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorEnglish::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2034 of file translator_en.h.
    {
        return "Here is a list of all design unit members with links to "
            "the Entities they belong to:";
    }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorEnglish::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2031 of file translator_en.h.
    { return "Design Unit Members"; }
Referenced by TranslatorAdapter_1_8_15::trDesignUnitMembers().
trDesignUnitMembers() [2/2]
virtual QCString TranslatorEnglish::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2031 of file translator_en.h.
    { return "Design Unit Members"; }
trDesignUnits() [1/2]
virtual QCString TranslatorEnglish::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2043 of file translator_en.h.
    { return "Design Units"; }
Referenced by TranslatorAdapter_1_8_15::trDesignUnits().
trDesignUnits() [2/2]
virtual QCString TranslatorEnglish::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2043 of file translator_en.h.
    { return "Design Units"; }
trDetailedDescription() [1/2]
virtual QCString TranslatorEnglish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 97 of file translator_en.h.
    { return "Detailed Description"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorEnglish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 97 of file translator_en.h.
    { return "Detailed Description"; }
trDetailLevel() [1/2]
virtual QCString TranslatorEnglish::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1876 of file translator_en.h.
    { return "detail level"; }
Referenced by TranslatorAdapter_1_8_0::trDetailLevel().
trDetailLevel() [2/2]
virtual QCString TranslatorEnglish::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1876 of file translator_en.h.
    { return "detail level"; }
trDictionaries() [1/2]
virtual QCString TranslatorEnglish::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2154 of file translator_en.h.
    {
        return "Dictionaries";
    }
Referenced by TranslatorAdapter_1_8_15::trDictionaries().
trDictionaries() [2/2]
virtual QCString TranslatorEnglish::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2154 of file translator_en.h.
    {
        return "Dictionaries";
    }
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorEnglish::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2158 of file translator_en.h.
    {
        return "Dictionary Documentation";
    }
Referenced by TranslatorAdapter_1_8_15::trDictionaryDocumentation().
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorEnglish::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2158 of file translator_en.h.
    {
        return "Dictionary Documentation";
    }
trDir() [1/2]
virtual QCString TranslatorEnglish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1515 of file translator_en.h.
    {
      QCString result((first_capital ? "Director" : "director"));
      if (singular) result+="y"; else result+="ies";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorEnglish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1515 of file translator_en.h.
    {
      QCString result((first_capital ? "Director" : "director"));
      if (singular) result+="y"; else result+="ies";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorEnglish::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1868 of file translator_en.h.
    { return "Directory dependency graph for "+name+":"; }
References setup::name.
Referenced by TranslatorAdapter_1_7_5::trDirDepGraph().
trDirDepGraph() [2/2]
virtual QCString TranslatorEnglish::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1868 of file translator_en.h.
    { return "Directory dependency graph for "+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorEnglish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1497 of file translator_en.h.
    { return "Directory Documentation"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorEnglish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1497 of file translator_en.h.
    { return "Directory Documentation"; }
trDirectories() [1/2]
virtual QCString TranslatorEnglish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1503 of file translator_en.h.
    { return "Directories"; }
trDirectories() [2/2]
virtual QCString TranslatorEnglish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1503 of file translator_en.h.
    { return "Directories"; }
trDirIndex() [1/2]
virtual QCString TranslatorEnglish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1491 of file translator_en.h.
    { return "Directory Hierarchy"; }
trDirIndex() [2/2]
virtual QCString TranslatorEnglish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1491 of file translator_en.h.
    { return "Directory Hierarchy"; }
trDirReference() [1/2]
virtual QCString TranslatorEnglish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1509 of file translator_en.h.
    { QCString result=dirName; result+=" Directory Reference"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorEnglish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1509 of file translator_en.h.
    { QCString result=dirName; result+=" Directory Reference"; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorEnglish::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1760 of file translator_en.h.
    {
      return name+" Relation";
    }
References setup::name.
Referenced by TranslatorAdapter_1_6_0::trDirRelation().
trDirRelation() [2/2]
virtual QCString TranslatorEnglish::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1760 of file translator_en.h.
    {
      return name+" Relation";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorEnglish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 364 of file translator_en.h.
    { return "Documentation"; }
trDocumentation() [2/2]
virtual QCString TranslatorEnglish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 364 of file translator_en.h.
    { return "Documentation"; }
trEnumerations() [1/2]
virtual QCString TranslatorEnglish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 456 of file translator_en.h.
    { return "Enumerations"; }
trEnumerations() [2/2]
virtual QCString TranslatorEnglish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 456 of file translator_en.h.
    { return "Enumerations"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorEnglish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 492 of file translator_en.h.
    { return "Enumeration Type Documentation"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorEnglish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 492 of file translator_en.h.
    { return "Enumeration Type Documentation"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorEnglish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1549 of file translator_en.h.
    { return "Enumerator Documentation"; }
Referenced by TranslatorAdapter_1_4_6::trEnumerationValueDocumentation().
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorEnglish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1549 of file translator_en.h.
    { return "Enumerator Documentation"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorEnglish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 474 of file translator_en.h.
    { return "Enumerator"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorEnglish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 474 of file translator_en.h.
    { return "Enumerator"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorEnglish::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1888 of file translator_en.h.
    { QCString result = "The documentation for this enum was generated from the following file";
      if (!single) result += "s";
      result+=":";
      return result;
    }
Referenced by TranslatorAdapter_1_8_0::trEnumGeneratedFromFiles().
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorEnglish::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1888 of file translator_en.h.
    { QCString result = "The documentation for this enum was generated from the following file";
      if (!single) result += "s";
      result+=":";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorEnglish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 165 of file translator_en.h.
    { return "enum name"; }
trEnumName() [2/2]
virtual QCString TranslatorEnglish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 165 of file translator_en.h.
    { return "enum name"; }
trEnumReference() [1/2]
virtual QCString TranslatorEnglish::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1896 of file translator_en.h.
    { return name+" Enum Reference"; }
References setup::name.
Referenced by TranslatorAdapter_1_8_0::trEnumReference().
trEnumReference() [2/2]
virtual QCString TranslatorEnglish::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1896 of file translator_en.h.
    { return name+" Enum Reference"; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorEnglish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 169 of file translator_en.h.
    { return "enum value"; }
trEnumValue() [2/2]
virtual QCString TranslatorEnglish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 169 of file translator_en.h.
    { return "enum value"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorEnglish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1365 of file translator_en.h.
    {
      return "Event Documentation";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorEnglish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1365 of file translator_en.h.
    {
      return "Event Documentation";
    }
trEvents() [1/2]
virtual QCString TranslatorEnglish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1360 of file translator_en.h.
    {
      return "Events";
    }
trEvents() [2/2]
virtual QCString TranslatorEnglish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1360 of file translator_en.h.
    {
      return "Events";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorEnglish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 434 of file translator_en.h.
    { return "Example Documentation"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorEnglish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 434 of file translator_en.h.
    { return "Example Documentation"; }
trExamples() [1/2]
virtual QCString TranslatorEnglish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 236 of file translator_en.h.
    { return "Examples"; }
trExamples() [2/2]
virtual QCString TranslatorEnglish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 236 of file translator_en.h.
    { return "Examples"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorEnglish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 350 of file translator_en.h.
    { return "Here is a list of all examples:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorEnglish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 350 of file translator_en.h.
    { return "Here is a list of all examples:"; }
trExceptionDocumentation() [1/2]
virtual QCString TranslatorEnglish::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2230 of file translator_en.h.
    {
        return "Exception Documentation";
    }
Referenced by TranslatorAdapter_1_8_15::trExceptionDocumentation().
trExceptionDocumentation() [2/2]
virtual QCString TranslatorEnglish::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2230 of file translator_en.h.
    {
        return "Exception Documentation";
    }
trExceptionHierarchy() [1/2]
virtual QCString TranslatorEnglish::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2222 of file translator_en.h.
    {
        return "Exception Hierarchy";
    }
Referenced by TranslatorAdapter_1_8_15::trExceptionHierarchy().
trExceptionHierarchy() [2/2]
virtual QCString TranslatorEnglish::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2222 of file translator_en.h.
    {
        return "Exception Hierarchy";
    }
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorEnglish::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2226 of file translator_en.h.
    {
        return "This inheritance list is sorted roughly, but not completely, alphabetically:";
    }
Referenced by TranslatorAdapter_1_8_15::trExceptionHierarchyDescription().
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorEnglish::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2226 of file translator_en.h.
    {
        return "This inheritance list is sorted roughly, but not completely, alphabetically:";
    }
trExceptionIndex() [1/2]
virtual QCString TranslatorEnglish::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2210 of file translator_en.h.
    {
        return "Exception Index";
    }
Referenced by TranslatorAdapter_1_8_15::trExceptionIndex().
trExceptionIndex() [2/2]
virtual QCString TranslatorEnglish::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2210 of file translator_en.h.
    {
        return "Exception Index";
    }
trExceptionList() [1/2]
virtual QCString TranslatorEnglish::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2214 of file translator_en.h.
    {
        return "Exception List";
    }
Referenced by TranslatorAdapter_1_8_15::trExceptionList().
trExceptionList() [2/2]
virtual QCString TranslatorEnglish::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2214 of file translator_en.h.
    {
        return "Exception List";
    }
trExceptionListDescription() [1/2]
virtual QCString TranslatorEnglish::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2218 of file translator_en.h.
    {
        return "Here are the exceptions with brief descriptions:";
    }
Referenced by TranslatorAdapter_1_8_15::trExceptionListDescription().
trExceptionListDescription() [2/2]
virtual QCString TranslatorEnglish::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2218 of file translator_en.h.
    {
        return "Here are the exceptions with brief descriptions:";
    }
trExceptions() [1/2]
virtual QCString TranslatorEnglish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 564 of file translator_en.h.
    { return "Exceptions"; }
trExceptions() [2/2]
virtual QCString TranslatorEnglish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 564 of file translator_en.h.
    { return "Exceptions"; }
trExtendsClass() [1/2]
virtual QCString TranslatorEnglish::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1936 of file translator_en.h.
    {
      return "Extends class @0.";
    }
Referenced by TranslatorAdapter_1_8_2::trExtendsClass().
trExtendsClass() [2/2]
virtual QCString TranslatorEnglish::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1936 of file translator_en.h.
    {
      return "Extends class @0.";
    }
trFile() [1/2]
virtual QCString TranslatorEnglish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1223 of file translator_en.h.
    {
      QCString result((first_capital ? "File" : "file"));
      if (!singular) result+="s";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorEnglish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1223 of file translator_en.h.
    {
      QCString result((first_capital ? "File" : "file"));
      if (!singular) result+="s";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorEnglish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 428 of file translator_en.h.
    { return "File Documentation"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorEnglish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 428 of file translator_en.h.
    { return "File Documentation"; }
trFileIn() [1/2]
virtual QCString TranslatorEnglish::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1797 of file translator_en.h.
    {
      return "File in "+name;
    }
References setup::name.
Referenced by TranslatorAdapter_1_7_5::trFileIn().
trFileIn() [2/2]
virtual QCString TranslatorEnglish::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1797 of file translator_en.h.
    {
      return "File in "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorEnglish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 397 of file translator_en.h.
    { return "File Index"; }
trFileIndex() [2/2]
virtual QCString TranslatorEnglish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 397 of file translator_en.h.
    { return "File Index"; }
trFileList() [1/2]
virtual QCString TranslatorEnglish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 202 of file translator_en.h.
    { return "File List"; }
trFileList() [2/2]
virtual QCString TranslatorEnglish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 202 of file translator_en.h.
    { return "File List"; }
trFileListDescription() [1/2]
virtual QCString TranslatorEnglish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 258 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="files with brief descriptions:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorEnglish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 258 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="files with brief descriptions:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorEnglish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 219 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals";
      }
      else
      {
        return "File Members";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorEnglish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 219 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals";
      }
      else
      {
        return "File Members";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorEnglish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 328 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="functions, variables, defines, enums, and typedefs";
      }
      else
      {
        result+="file members";
      }
      result+=" with links to ";
      if (extractAll)
        result+="the files they belong to:";
      else
        result+="the documentation:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorEnglish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 328 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="functions, variables, defines, enums, and typedefs";
      }
      else
      {
        result+="file members";
      }
      result+=" with links to ";
      if (extractAll)
        result+="the files they belong to:";
      else
        result+="the documentation:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorEnglish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 631 of file translator_en.h.
    {
      QCString result=fileName;
      result+=" File Reference";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorEnglish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 631 of file translator_en.h.
    {
      QCString result=fileName;
      result+=" File Reference";
      return result;
    }
trFlowchart() [1/2]
virtual QCString TranslatorEnglish::trFlowchart () [inline], [virtual]
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2337 of file translator_en.h.
    { return "Flowchart: "; }
Referenced by TranslatorAdapter_1_9_5::trFlowchart().
trFlowchart() [2/2]
virtual QCString TranslatorEnglish::trFlowchart () [inline], [virtual]
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2337 of file translator_en.h.
    { return "Flowchart: "; }
trFriends() [1/2]
virtual QCString TranslatorEnglish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 591 of file translator_en.h.
    { return "Friends"; }
trFriends() [2/2]
virtual QCString TranslatorEnglish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 591 of file translator_en.h.
    { return "Friends"; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorEnglish::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2046 of file translator_en.h.
    { return "Functions/Procedures/Processes"; }
Referenced by TranslatorAdapter_1_8_15::trFunctionAndProc().
trFunctionAndProc() [2/2]
virtual QCString TranslatorEnglish::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2046 of file translator_en.h.
    { return "Functions/Procedures/Processes"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorEnglish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 498 of file translator_en.h.
    { return "Function Documentation"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorEnglish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 498 of file translator_en.h.
    { return "Function Documentation"; }
trFunctions() [1/2]
virtual QCString TranslatorEnglish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 462 of file translator_en.h.
    { return "Functions"; }
trFunctions() [2/2]
virtual QCString TranslatorEnglish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 462 of file translator_en.h.
    { return "Functions"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorEnglish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 525 of file translator_en.h.
    {
      QCString result="Generated on "+date;
      if (!projName.isEmpty()) result+=" for "+projName;
      result+=" by";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorEnglish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 525 of file translator_en.h.
    {
      QCString result="Generated on "+date;
      if (!projName.isEmpty()) result+=" for "+projName;
      result+=" by";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorEnglish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 157 of file translator_en.h.
    { QCString result="Generated automatically by Doxygen";
      if (!s.isEmpty()) result+=" for "+s;
      result+=" from the source code.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorEnglish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 157 of file translator_en.h.
    { QCString result="Generated automatically by Doxygen";
      if (!s.isEmpty()) result+=" for "+s;
      result+=" from the source code.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorEnglish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 568 of file translator_en.h.
    { return "Generated by"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorEnglish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 568 of file translator_en.h.
    { return "Generated by"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorEnglish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 769 of file translator_en.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="The documentation for this ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?"design unit":"class"; break;
        case ClassDef::Struct: result+="struct"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" was generated from the following file";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorEnglish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 769 of file translator_en.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="The documentation for this ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?"design unit":"class"; break;
        case ClassDef::Struct: result+="struct"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" was generated from the following file";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorEnglish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1706 of file translator_en.h.
    {
      // single is true implies a single file
      QCString result="The documentation for this ";
      switch(compType)
      {
        case ClassDef::Class: result+="module"; break;
        case ClassDef::Struct: result+="type"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" was generated from the following file";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
Referenced by TranslatorAdapter_1_6_0::trGeneratedFromFilesFortran().
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorEnglish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1706 of file translator_en.h.
    {
      // single is true implies a single file
      QCString result="The documentation for this ";
      switch(compType)
      {
        case ClassDef::Class: result+="module"; break;
        case ClassDef::Struct: result+="type"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="interface"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="category"; break;
        case ClassDef::Exception: result+="exception"; break;
        default: break;
      }
      result+=" was generated from the following file";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorEnglish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1278 of file translator_en.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorEnglish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1278 of file translator_en.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorEnglish::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1772 of file translator_en.h.
    {
      return "Global Namespace";
    }
Referenced by TranslatorAdapter_1_6_0::trGlobalNamespace().
trGlobalNamespace() [2/2]
virtual QCString TranslatorEnglish::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1772 of file translator_en.h.
    {
      return "Global Namespace";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorEnglish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 856 of file translator_en.h.
    {
      return "Go to the documentation of this file.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorEnglish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 856 of file translator_en.h.
    {
      return "Go to the documentation of this file.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorEnglish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_en.h.
    {
      return "Go to the graphical class hierarchy";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorEnglish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_en.h.
    {
      return "Go to the graphical class hierarchy";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorEnglish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 851 of file translator_en.h.
    {
      return "Go to the source code of this file.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorEnglish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 851 of file translator_en.h.
    {
      return "Go to the source code of this file.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorEnglish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_en.h.
    {
      return "Go to the textual class hierarchy";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorEnglish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_en.h.
    {
      return "Go to the textual class hierarchy";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorEnglish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_en.h.
    {
      return "Graphical Class Hierarchy";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorEnglish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_en.h.
    {
      return "Graphical Class Hierarchy";
    }
trGroup() [1/2]
virtual QCString TranslatorEnglish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1245 of file translator_en.h.
    {
      QCString result((first_capital ? "Module" : "module"));
      if (!singular) result+="s";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorEnglish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1245 of file translator_en.h.
    {
      QCString result((first_capital ? "Module" : "module"));
      if (!singular) result+="s";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorEnglish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 376 of file translator_en.h.
    { return "Hierarchical Index"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorEnglish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 376 of file translator_en.h.
    { return "Hierarchical Index"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorEnglish::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1316 of file translator_en.h.
    {
      return "Implements "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorEnglish::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1316 of file translator_en.h.
    {
      return "Implements "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorEnglish::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1324 of file translator_en.h.
    {
      return "Implemented in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorEnglish::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1324 of file translator_en.h.
    {
      return "Implemented in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorEnglish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 985 of file translator_en.h.
    {
      return "This graph shows which files directly or "
             "indirectly include this file:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorEnglish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 985 of file translator_en.h.
    {
      return "This graph shows which files directly or "
             "indirectly include this file:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorEnglish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 841 of file translator_en.h.
    {
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorEnglish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 841 of file translator_en.h.
    {
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorEnglish::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1806 of file translator_en.h.
    {
      return "Includes file in "+name;
    }
References setup::name.
Referenced by TranslatorAdapter_1_7_5::trIncludesFileIn().
trIncludesFileIn() [2/2]
virtual QCString TranslatorEnglish::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1806 of file translator_en.h.
    {
      return "Includes file in "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorEnglish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 151 of file translator_en.h.
    { return ", including all inherited members."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorEnglish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 151 of file translator_en.h.
    { return ", including all inherited members."; }
trInheritedByList() [1/2]
virtual QCString TranslatorEnglish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 703 of file translator_en.h.
    {
      return "Inherited by "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorEnglish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 703 of file translator_en.h.
    {
      return "Inherited by "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorEnglish::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1900 of file translator_en.h.
    { return members+" inherited from "+what; }
Referenced by TranslatorAdapter_1_8_0::trInheritedFrom().
trInheritedFrom() [2/2]
virtual QCString TranslatorEnglish::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1900 of file translator_en.h.
    { return members+" inherited from "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorEnglish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 695 of file translator_en.h.
    {
      return "Inherits "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorEnglish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 695 of file translator_en.h.
    {
      return "Inherits "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorEnglish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 876 of file translator_en.h.
    {
      return "Initial value:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorEnglish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 876 of file translator_en.h.
    {
      return "Initial value:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorEnglish::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1952 of file translator_en.h.
    {
      return "Instance Methods";
    }
Referenced by TranslatorAdapter_1_8_2::trInstanceMethods().
trInstanceMethods() [2/2]
virtual QCString TranslatorEnglish::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1952 of file translator_en.h.
    {
      return "Instance Methods";
    }
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorEnglish::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2186 of file translator_en.h.
    {
        return "Interface Documentation";
    }
Referenced by TranslatorAdapter_1_8_15::trInterfaceDocumentation().
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorEnglish::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2186 of file translator_en.h.
    {
        return "Interface Documentation";
    }
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorEnglish::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2178 of file translator_en.h.
    {
        return "Interface Hierarchy";
    }
Referenced by TranslatorAdapter_1_8_15::trInterfaceHierarchy().
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorEnglish::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2178 of file translator_en.h.
    {
        return "Interface Hierarchy";
    }
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorEnglish::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2182 of file translator_en.h.
    {
        return "This inheritance list is sorted roughly, but not completely, alphabetically:";
    }
Referenced by TranslatorAdapter_1_8_15::trInterfaceHierarchyDescription().
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorEnglish::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2182 of file translator_en.h.
    {
        return "This inheritance list is sorted roughly, but not completely, alphabetically:";
    }
trInterfaceIndex() [1/2]
virtual QCString TranslatorEnglish::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2166 of file translator_en.h.
    {
        return "Interface Index";
    }
Referenced by TranslatorAdapter_1_8_15::trInterfaceIndex().
trInterfaceIndex() [2/2]
virtual QCString TranslatorEnglish::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2166 of file translator_en.h.
    {
        return "Interface Index";
    }
trInterfaceList() [1/2]
virtual QCString TranslatorEnglish::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2170 of file translator_en.h.
    {
        return "Interface List";
    }
Referenced by TranslatorAdapter_1_8_15::trInterfaceList().
trInterfaceList() [2/2]
virtual QCString TranslatorEnglish::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2170 of file translator_en.h.
    {
        return "Interface List";
    }
trInterfaceListDescription() [1/2]
virtual QCString TranslatorEnglish::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2174 of file translator_en.h.
    {
        return "Here are the interfaces with brief descriptions:";
    }
Referenced by TranslatorAdapter_1_8_15::trInterfaceListDescription().
trInterfaceListDescription() [2/2]
virtual QCString TranslatorEnglish::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2174 of file translator_en.h.
    {
        return "Here are the interfaces with brief descriptions:";
    }
trInterfaces() [1/2]
virtual QCString TranslatorEnglish::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1969 of file translator_en.h.
    { return "Exported Interfaces"; }
Referenced by TranslatorAdapter_1_8_4::trInterfaces().
trInterfaces() [2/2]
virtual QCString TranslatorEnglish::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1969 of file translator_en.h.
    { return "Exported Interfaces"; }
trInvariant() [1/2]
virtual QCString TranslatorEnglish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 871 of file translator_en.h.
    {
      return "Invariant";
    }
trInvariant() [2/2]
virtual QCString TranslatorEnglish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 871 of file translator_en.h.
    {
      return "Invariant";
    }
trISOLang() [1/2]
virtual QCString TranslatorEnglish::trISOLang () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorJapaneseEn, TranslatorKoreanEn, TranslatorJapaneseEn, and TranslatorKoreanEn.
Definition at line 77 of file translator_en.h.
    {
      return "en-US";
    }
trISOLang() [2/2]
virtual QCString TranslatorEnglish::trISOLang () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorJapaneseEn, TranslatorKoreanEn, TranslatorJapaneseEn, and TranslatorKoreanEn.
Definition at line 77 of file translator_en.h.
    {
      return "en-US";
    }
trLegend() [1/2]
virtual QCString TranslatorEnglish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1072 of file translator_en.h.
    {
      return "legend";
    }
trLegend() [2/2]
virtual QCString TranslatorEnglish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1072 of file translator_en.h.
    {
      return "legend";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorEnglish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1007 of file translator_en.h.
    {
      return
        "This page explains how to interpret the graphs that are generated "
        "by doxygen.<p>\n"
        "Consider the following example:\n"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "This will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A filled gray box represents the struct or class for which the "
        "graph is generated.</li>\n"
        "<li>%A box with a black border denotes a documented struct or class.</li>\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.</li>\n"
        "<li>%A box with a red border denotes a documented struct or class for"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries.</li>\n"
        "</ul>\n"
        "<p>\n"
        "The arrows have the following meaning:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A blue arrow is used to visualize a public inheritance "
        "relation between two classes.</li>\n"
        "<li>%A dark green arrow is used for protected inheritance.</li>\n"
        "<li>%A dark red arrow is used for private inheritance.</li>\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labelled with the variable(s) "
        "through which the pointed class or struct is accessible.</li>\n"
        "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "the template class it was instantiated from. The arrow is labelled with "
        "the template parameters of the instance.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorEnglish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1007 of file translator_en.h.
    {
      return
        "This page explains how to interpret the graphs that are generated "
        "by doxygen.<p>\n"
        "Consider the following example:\n"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "This will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A filled gray box represents the struct or class for which the "
        "graph is generated.</li>\n"
        "<li>%A box with a black border denotes a documented struct or class.</li>\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.</li>\n"
        "<li>%A box with a red border denotes a documented struct or class for"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries.</li>\n"
        "</ul>\n"
        "<p>\n"
        "The arrows have the following meaning:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A blue arrow is used to visualize a public inheritance "
        "relation between two classes.</li>\n"
        "<li>%A dark green arrow is used for protected inheritance.</li>\n"
        "<li>%A dark red arrow is used for private inheritance.</li>\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labelled with the variable(s) "
        "through which the pointed class or struct is accessible.</li>\n"
        "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "the template class it was instantiated from. The arrow is labelled with "
        "the template parameters of the instance.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorEnglish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1000 of file translator_en.h.
    {
      return "Graph Legend";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorEnglish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1000 of file translator_en.h.
    {
      return "Graph Legend";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorEnglish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 139 of file translator_en.h.
    { return "List of all members"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorEnglish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 139 of file translator_en.h.
    { return "List of all members"; }
trLoading() [1/2]
virtual QCString TranslatorEnglish::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1766 of file translator_en.h.
    {
      return "Loading...";
    }
Referenced by TranslatorAdapter_1_6_0::trLoading().
trLoading() [2/2]
virtual QCString TranslatorEnglish::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1766 of file translator_en.h.
    {
      return "Loading...";
    }
trMainPage() [1/2]
virtual QCString TranslatorEnglish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 800 of file translator_en.h.
    { return "Main Page"; }
trMainPage() [2/2]
virtual QCString TranslatorEnglish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 800 of file translator_en.h.
    { return "Main Page"; }
trMember() [1/2]
virtual QCString TranslatorEnglish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1267 of file translator_en.h.
    {
      QCString result((first_capital ? "Member" : "member"));
      if (!singular) result+="s";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorEnglish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1267 of file translator_en.h.
    {
      QCString result((first_capital ? "Member" : "member"));
      if (!singular) result+="s";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorEnglish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 122 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Field Documentation";
      }
      else
      {
        return "Member Data Documentation";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorEnglish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 122 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Field Documentation";
      }
      else
      {
        return "Member Data Documentation";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorEnglish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 105 of file translator_en.h.
    { return "Member Enumeration Documentation"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorEnglish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 105 of file translator_en.h.
    { return "Member Enumeration Documentation"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorEnglish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 109 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Member Function/Procedure/Process Documentation";
      }
      else
      {
        return "Member Function Documentation";
      }
    }
References Config_getBool.
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorEnglish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 109 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Member Function/Procedure/Process Documentation";
      }
      else
      {
        return "Member Function Documentation";
      }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorEnglish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1557 of file translator_en.h.
    { return "Member Function/Subroutine Documentation"; }
Referenced by TranslatorAdapter_1_6_0::trMemberFunctionDocumentationFortran().
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorEnglish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1557 of file translator_en.h.
    { return "Member Function/Subroutine Documentation"; }
trMemberList() [1/2]
virtual QCString TranslatorEnglish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 143 of file translator_en.h.
    { return "Member List"; }
trMemberList() [2/2]
virtual QCString TranslatorEnglish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 143 of file translator_en.h.
    { return "Member List"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorEnglish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 101 of file translator_en.h.
    { return "Member Typedef Documentation"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorEnglish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 101 of file translator_en.h.
    { return "Member Typedef Documentation"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorEnglish::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1959 of file translator_en.h.
    {
      return "Method Documentation";
    }
Referenced by TranslatorAdapter_1_8_2::trMethodDocumentation().
trMethodDocumentation() [2/2]
virtual QCString TranslatorEnglish::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1959 of file translator_en.h.
    {
      return "Method Documentation";
    }
trModule() [1/2]
virtual QCString TranslatorEnglish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1696 of file translator_en.h.
    {
      QCString result((first_capital ? "Module" : "module"));
      if (!singular) result+="s";
      return result;
    }
Referenced by TranslatorAdapter_1_6_0::trModule().
trModule() [2/2]
virtual QCString TranslatorEnglish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1696 of file translator_en.h.
    {
      QCString result((first_capital ? "Module" : "module"));
      if (!singular) result+="s";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorEnglish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 403 of file translator_en.h.
    { return "Module Documentation"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorEnglish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 403 of file translator_en.h.
    { return "Module Documentation"; }
trModuleIndex() [1/2]
virtual QCString TranslatorEnglish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 370 of file translator_en.h.
    { return "Module Index"; }
trModuleIndex() [2/2]
virtual QCString TranslatorEnglish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 370 of file translator_en.h.
    { return "Module Index"; }
trModuleReference() [1/2]
virtual QCString TranslatorEnglish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1658 of file translator_en.h.
    {
      QCString result=namespaceName;
      result+=" Module Reference";
      return result;
    }
Referenced by TranslatorAdapter_1_6_0::trModuleReference().
trModuleReference() [2/2]
virtual QCString TranslatorEnglish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1658 of file translator_en.h.
    {
      QCString result=namespaceName;
      result+=" Module Reference";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorEnglish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 181 of file translator_en.h.
    { return "Modules"; }
trModules() [2/2]
virtual QCString TranslatorEnglish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 181 of file translator_en.h.
    { return "Modules"; }
trModulesDescription() [1/2]
virtual QCString TranslatorEnglish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 358 of file translator_en.h.
    { return "Here is a list of all modules:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorEnglish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 358 of file translator_en.h.
    { return "Here is a list of all modules:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorEnglish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1689 of file translator_en.h.
    { return "Modules Index"; }
Referenced by TranslatorAdapter_1_6_0::trModulesIndex().
trModulesIndex() [2/2]
virtual QCString TranslatorEnglish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1689 of file translator_en.h.
    { return "Modules Index"; }
trModulesList() [1/2]
virtual QCString TranslatorEnglish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1624 of file translator_en.h.
    { return "Modules List"; }
Referenced by TranslatorAdapter_1_6_0::trModulesList().
trModulesList() [2/2]
virtual QCString TranslatorEnglish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1624 of file translator_en.h.
    { return "Modules List"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorEnglish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1628 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="modules with brief descriptions:";
      return result;
    }
Referenced by TranslatorAdapter_1_6_0::trModulesListDescription().
trModulesListDescription() [2/2]
virtual QCString TranslatorEnglish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1628 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="modules with brief descriptions:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorEnglish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1670 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="module members with links to ";
      if (extractAll)
      {
        result+="the module documentation for each member:";
      }
      else
      {
        result+="the modules they belong to:";
      }
      return result;
    }
Referenced by TranslatorAdapter_1_6_0::trModulesMemberDescription().
trModulesMemberDescription() [2/2]
virtual QCString TranslatorEnglish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1670 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="module members with links to ";
      if (extractAll)
      {
        result+="the module documentation for each member:";
      }
      else
      {
        result+="the modules they belong to:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorEnglish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1666 of file translator_en.h.
    { return "Module Members"; }
Referenced by TranslatorAdapter_1_6_0::trModulesMembers().
trModulesMembers() [2/2]
virtual QCString TranslatorEnglish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1666 of file translator_en.h.
    { return "Module Members"; }
trMonth() [1/2]
virtual QCString TranslatorEnglish::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1843 of file translator_en.h.
    {
      static const char *months_short[] = { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
      static const char *months_full[] = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMonth() [2/2]
virtual QCString TranslatorEnglish::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1843 of file translator_en.h.
    {
      static const char *months_short[] = { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
      static const char *months_full[] = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMore() [1/2]
virtual QCString TranslatorEnglish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 135 of file translator_en.h.
    { return "More..."; }
trMore() [2/2]
virtual QCString TranslatorEnglish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 135 of file translator_en.h.
    { return "More..."; }
trNamespace() [1/2]
virtual QCString TranslatorEnglish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1234 of file translator_en.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorEnglish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1234 of file translator_en.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorEnglish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 749 of file translator_en.h.
    { return "Namespace Documentation"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorEnglish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 749 of file translator_en.h.
    { return "Namespace Documentation"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorEnglish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 743 of file translator_en.h.
    { return "Namespace Index"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorEnglish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 743 of file translator_en.h.
    { return "Namespace Index"; }
trNamespaceList() [1/2]
virtual QCString TranslatorEnglish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 576 of file translator_en.h.
    { return "Namespace List"; }
trNamespaceList() [2/2]
virtual QCString TranslatorEnglish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 576 of file translator_en.h.
    { return "Namespace List"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorEnglish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 580 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="namespaces with brief descriptions:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorEnglish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 580 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="namespaces with brief descriptions:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorEnglish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 729 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="namespace members with links to ";
      if (extractAll)
        result+="the namespace documentation for each member:";
      else
        result+="the namespaces they belong to:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorEnglish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 729 of file translator_en.h.
    {
      QCString result="Here is a list of all ";
      if (!extractAll) result+="documented ";
      result+="namespace members with links to ";
      if (extractAll)
        result+="the namespace documentation for each member:";
      else
        result+="the namespaces they belong to:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorEnglish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 725 of file translator_en.h.
    { return "Namespace Members"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorEnglish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 725 of file translator_en.h.
    { return "Namespace Members"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorEnglish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 639 of file translator_en.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Reference";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorEnglish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 639 of file translator_en.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Reference";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorEnglish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 759 of file translator_en.h.
    { return "Namespaces"; }
trNamespaces() [2/2]
virtual QCString TranslatorEnglish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 759 of file translator_en.h.
    { return "Namespaces"; }
trNoMatches() [1/2]
virtual QCString TranslatorEnglish::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1784 of file translator_en.h.
    {
      return "No Matches";
    }
Referenced by TranslatorAdapter_1_6_0::trNoMatches().
trNoMatches() [2/2]
virtual QCString TranslatorEnglish::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1784 of file translator_en.h.
    {
      return "No Matches";
    }
trNote() [1/2]
virtual QCString TranslatorEnglish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 906 of file translator_en.h.
    {
      return "Note";
    }
trNote() [2/2]
virtual QCString TranslatorEnglish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 906 of file translator_en.h.
    {
      return "Note";
    }
trOperationDocumentation() [1/2]
virtual QCString TranslatorEnglish::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2256 of file translator_en.h.
    {
        return "Operation Documentation";
    }
Referenced by TranslatorAdapter_1_8_15::trOperationDocumentation().
trOperationDocumentation() [2/2]
virtual QCString TranslatorEnglish::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2256 of file translator_en.h.
    {
        return "Operation Documentation";
    }
trOperations() [1/2]
virtual QCString TranslatorEnglish::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2252 of file translator_en.h.
    {
        return "Operations";
    }
Referenced by TranslatorAdapter_1_8_15::trOperations().
trOperations() [2/2]
virtual QCString TranslatorEnglish::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2252 of file translator_en.h.
    {
        return "Operations";
    }
trOverloadText() [1/2]
virtual QCString TranslatorEnglish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1529 of file translator_en.h.
    {
       return "This is an overloaded member function, "
              "provided for convenience. It differs from the above "
              "function only in what argument(s) it accepts.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorEnglish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1529 of file translator_en.h.
    {
       return "This is an overloaded member function, "
              "provided for convenience. It differs from the above "
              "function only in what argument(s) it accepts.";
    }
trPackage() [1/2]
virtual QCString TranslatorEnglish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1124 of file translator_en.h.
    {
      return "Package "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorEnglish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1124 of file translator_en.h.
    {
      return "Package "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorEnglish::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1401 of file translator_en.h.
    {
      return "Package Attributes";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorEnglish::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1401 of file translator_en.h.
    {
      return "Package Attributes";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorEnglish::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1383 of file translator_en.h.
    {
      return "Package Functions";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorEnglish::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1383 of file translator_en.h.
    {
      return "Package Functions";
    }
trPackageList() [1/2]
virtual QCString TranslatorEnglish::trPackageList () [inline], [virtual]
Implements Translator.
Definition at line 2327 of file translator_en.h.
    { return "Package List"; }
Referenced by TranslatorAdapter_1_9_4::trPackageList().
trPackageList() [2/2]
virtual QCString TranslatorEnglish::trPackageList () [inline], [virtual]
Implements Translator.
Definition at line 2327 of file translator_en.h.
    { return "Package List"; }
trPackageListDescription() [1/2]
virtual QCString TranslatorEnglish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1129 of file translator_en.h.
    {
      return "Here are the packages with brief descriptions (if available):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorEnglish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1129 of file translator_en.h.
    {
      return "Here are the packages with brief descriptions (if available):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorEnglish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1387 of file translator_en.h.
    {
      return "Package Members";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorEnglish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1387 of file translator_en.h.
    {
      return "Package Members";
    }
trPackages() [1/2]
virtual QCString TranslatorEnglish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1134 of file translator_en.h.
    {
      return "Packages";
    }
trPackages() [2/2]
virtual QCString TranslatorEnglish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1134 of file translator_en.h.
    {
      return "Packages";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorEnglish::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1376 of file translator_en.h.
    {
      return "Package Types";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorEnglish::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1376 of file translator_en.h.
    {
      return "Package Types";
    }
trPage() [1/2]
virtual QCString TranslatorEnglish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1256 of file translator_en.h.
    {
      QCString result((first_capital ? "Page" : "page"));
      if (!singular) result+="s";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorEnglish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1256 of file translator_en.h.
    {
      QCString result((first_capital ? "Page" : "page"));
      if (!singular) result+="s";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorEnglish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 806 of file translator_en.h.
    { return "p."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorEnglish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 806 of file translator_en.h.
    { return "p."; }
trPageIndex() [1/2]
virtual QCString TranslatorEnglish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_en.h.
    {
      return "Page Index";
    }
trPageIndex() [2/2]
virtual QCString TranslatorEnglish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_en.h.
    {
      return "Page Index";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorEnglish::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1917 of file translator_en.h.
    {
      QCString opt = enable ? "enable" : "disable";
      return "click to "+opt+" panel synchronisation";
    }
Referenced by TranslatorAdapter_1_8_2::trPanelSynchronisationTooltip().
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorEnglish::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1917 of file translator_en.h.
    {
      QCString opt = enable ? "enable" : "disable";
      return "click to "+opt+" panel synchronisation";
    }
trParameters() [1/2]
virtual QCString TranslatorEnglish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 560 of file translator_en.h.
    { return "Parameters"; }
trParameters() [2/2]
virtual QCString TranslatorEnglish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 560 of file translator_en.h.
    { return "Parameters"; }
trPostcondition() [1/2]
virtual QCString TranslatorEnglish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 866 of file translator_en.h.
    {
      return "Postcondition";
    }
trPostcondition() [2/2]
virtual QCString TranslatorEnglish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 866 of file translator_en.h.
    {
      return "Postcondition";
    }
trPrecondition() [1/2]
virtual QCString TranslatorEnglish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 861 of file translator_en.h.
    {
      return "Precondition";
    }
trPrecondition() [2/2]
virtual QCString TranslatorEnglish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 861 of file translator_en.h.
    {
      return "Precondition";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorEnglish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 945 of file translator_en.h.
    {
      return "Private Attributes";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorEnglish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 945 of file translator_en.h.
    {
      return "Private Attributes";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorEnglish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 660 of file translator_en.h.
    { return "Private Member Functions"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorEnglish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 660 of file translator_en.h.
    { return "Private Member Functions"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorEnglish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 662 of file translator_en.h.
    { return "Private Slots"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorEnglish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 662 of file translator_en.h.
    { return "Private Slots"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorEnglish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 941 of file translator_en.h.
    {
      return "Private Types";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorEnglish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 941 of file translator_en.h.
    {
      return "Private Types";
    }
trProperties() [1/2]
virtual QCString TranslatorEnglish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1097 of file translator_en.h.
    {
      return "Properties";
    }
trProperties() [2/2]
virtual QCString TranslatorEnglish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1097 of file translator_en.h.
    {
      return "Properties";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorEnglish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1102 of file translator_en.h.
    {
      return "Property Documentation";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorEnglish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1102 of file translator_en.h.
    {
      return "Property Documentation";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorEnglish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 933 of file translator_en.h.
    {
      return "Protected Attributes";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorEnglish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 933 of file translator_en.h.
    {
      return "Protected Attributes";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorEnglish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 654 of file translator_en.h.
    { return "Protected Member Functions"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorEnglish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 654 of file translator_en.h.
    { return "Protected Member Functions"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorEnglish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 656 of file translator_en.h.
    { return "Protected Slots"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorEnglish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 656 of file translator_en.h.
    { return "Protected Slots"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorEnglish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 929 of file translator_en.h.
    {
      return "Protected Types";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorEnglish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 929 of file translator_en.h.
    {
      return "Protected Types";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorEnglish::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1927 of file translator_en.h.
    {
      return "Provided by category @0.";
    }
Referenced by TranslatorAdapter_1_8_2::trProvidedByCategory().
trProvidedByCategory() [2/2]
virtual QCString TranslatorEnglish::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1927 of file translator_en.h.
    {
      return "Provided by category @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorEnglish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 914 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Fields";
      }
      else
      {
        return "Public Attributes";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorEnglish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 914 of file translator_en.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Fields";
      }
      else
      {
        return "Public Attributes";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorEnglish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 646 of file translator_en.h.
    { return "Public Member Functions"; }
trPublicMembers() [2/2]
virtual QCString TranslatorEnglish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 646 of file translator_en.h.
    { return "Public Member Functions"; }
trPublicSlots() [1/2]
virtual QCString TranslatorEnglish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_en.h.
    { return "Public Slots"; }
trPublicSlots() [2/2]
virtual QCString TranslatorEnglish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_en.h.
    { return "Public Slots"; }
trPublicTypes() [1/2]
virtual QCString TranslatorEnglish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_en.h.
    {
      return "Public Types";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorEnglish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_en.h.
    {
      return "Public Types";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorEnglish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_en.h.
    {
      return "Referenced by";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorEnglish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_en.h.
    {
      return "Referenced by";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorEnglish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 438 of file translator_en.h.
    { return "Reference Manual"; }
trReferenceManual() [2/2]
virtual QCString TranslatorEnglish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 438 of file translator_en.h.
    { return "Reference Manual"; }
trReferences() [1/2]
virtual QCString TranslatorEnglish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1304 of file translator_en.h.
    {
      return "References";
    }
trReferences() [2/2]
virtual QCString TranslatorEnglish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1304 of file translator_en.h.
    {
      return "References";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorEnglish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 711 of file translator_en.h.
    {
      return "Reimplemented from "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorEnglish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 711 of file translator_en.h.
    {
      return "Reimplemented from "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorEnglish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 719 of file translator_en.h.
    {
      return "Reimplemented in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorEnglish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 719 of file translator_en.h.
    {
      return "Reimplemented in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorEnglish::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 601 of file translator_en.h.
    { return "Friends And Related Function Documentation"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorEnglish::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 601 of file translator_en.h.
    { return "Friends And Related Function Documentation"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorEnglish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 89 of file translator_en.h.
    { return "Related Functions"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorEnglish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 89 of file translator_en.h.
    { return "Related Functions"; }
trRelatedPages() [1/2]
virtual QCString TranslatorEnglish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 232 of file translator_en.h.
    { return "Related Pages"; }
trRelatedPages() [2/2]
virtual QCString TranslatorEnglish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 232 of file translator_en.h.
    { return "Related Pages"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorEnglish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 354 of file translator_en.h.
    { return "Here is a list of all related documentation pages:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorEnglish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 354 of file translator_en.h.
    { return "Here is a list of all related documentation pages:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorEnglish::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 93 of file translator_en.h.
    { return "(Note that these are not member functions.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorEnglish::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 93 of file translator_en.h.
    { return "(Note that these are not member functions.)"; }
trRemarks() [1/2]
virtual QCString TranslatorEnglish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 977 of file translator_en.h.
    {
      return "Remarks";
    }
trRemarks() [2/2]
virtual QCString TranslatorEnglish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 977 of file translator_en.h.
    {
      return "Remarks";
    }
trReturns() [1/2]
virtual QCString TranslatorEnglish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 552 of file translator_en.h.
    { return "Returns"; }
trReturns() [2/2]
virtual QCString TranslatorEnglish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 552 of file translator_en.h.
    { return "Returns"; }
trReturnValues() [1/2]
virtual QCString TranslatorEnglish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 795 of file translator_en.h.
    { return "Return values"; }
trReturnValues() [2/2]
virtual QCString TranslatorEnglish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 795 of file translator_en.h.
    { return "Return values"; }
trRTFansicp() [1/2]
virtual QCString TranslatorEnglish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Reimplemented in TranslatorJapaneseEn, TranslatorKoreanEn, TranslatorJapaneseEn, and TranslatorKoreanEn.
Definition at line 1188 of file translator_en.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorEnglish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Reimplemented in TranslatorJapaneseEn, TranslatorKoreanEn, TranslatorJapaneseEn, and TranslatorKoreanEn.
Definition at line 1188 of file translator_en.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorEnglish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Reimplemented in TranslatorJapaneseEn, TranslatorKoreanEn, TranslatorJapaneseEn, and TranslatorKoreanEn.
Definition at line 1197 of file translator_en.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorEnglish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Reimplemented in TranslatorJapaneseEn, TranslatorKoreanEn, TranslatorJapaneseEn, and TranslatorKoreanEn.
Definition at line 1197 of file translator_en.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorEnglish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1203 of file translator_en.h.
    {
      return "Index";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorEnglish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1203 of file translator_en.h.
    {
      return "Index";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorEnglish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1336 of file translator_en.h.
    {
      return "Table of Contents";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorEnglish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1336 of file translator_en.h.
    {
      return "Table of Contents";
    }
trSearch() [1/2]
virtual QCString TranslatorEnglish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 240 of file translator_en.h.
    { return "Search"; }
trSearch() [2/2]
virtual QCString TranslatorEnglish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 240 of file translator_en.h.
    { return "Search"; }
trSearching() [1/2]
virtual QCString TranslatorEnglish::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1778 of file translator_en.h.
    {
      return "Searching...";
    }
Referenced by TranslatorAdapter_1_6_0::trSearching().
trSearching() [2/2]
virtual QCString TranslatorEnglish::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1778 of file translator_en.h.
    {
      return "Searching...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorEnglish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1468 of file translator_en.h.
    {
      return "Matches:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorEnglish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1468 of file translator_en.h.
    {
      return "Matches:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorEnglish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1449 of file translator_en.h.
    {
      if (numDocuments==0)
      {
        return "Sorry, no documents matching your query.";
      }
      else if (numDocuments==1)
      {
        return "Found <b>1</b> document matching your query.";
      }
      else
      {
        return "Found <b>$num</b> documents matching your query. "
               "Showing best matches first.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorEnglish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1449 of file translator_en.h.
    {
      if (numDocuments==0)
      {
        return "Sorry, no documents matching your query.";
      }
      else if (numDocuments==1)
      {
        return "Found <b>1</b> document matching your query.";
      }
      else
      {
        return "Found <b>$num</b> documents matching your query. "
               "Showing best matches first.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorEnglish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1437 of file translator_en.h.
    {
      return "Search Results";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorEnglish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1437 of file translator_en.h.
    {
      return "Search Results";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorEnglish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 556 of file translator_en.h.
    { return "See also"; }
trSeeAlso() [2/2]
virtual QCString TranslatorEnglish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 556 of file translator_en.h.
    { return "See also"; }
trSequenceDocumentation() [1/2]
virtual QCString TranslatorEnglish::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2150 of file translator_en.h.
    {
        return "Sequence Documentation";
    }
Referenced by TranslatorAdapter_1_8_15::trSequenceDocumentation().
trSequenceDocumentation() [2/2]
virtual QCString TranslatorEnglish::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2150 of file translator_en.h.
    {
        return "Sequence Documentation";
    }
trSequences() [1/2]
virtual QCString TranslatorEnglish::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2146 of file translator_en.h.
    {
        return "Sequences";
    }
Referenced by TranslatorAdapter_1_8_15::trSequences().
trSequences() [2/2]
virtual QCString TranslatorEnglish::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2146 of file translator_en.h.
    {
        return "Sequences";
    }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorEnglish::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2002 of file translator_en.h.
    {
      // single is true implies a single file
      QCString result="The documentation for this service "
                      "was generated from the following file";
      if (single) result+=":"; else result+="s:";
      return result;
    }
Referenced by TranslatorAdapter_1_8_4::trServiceGeneratedFromFiles().
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorEnglish::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2002 of file translator_en.h.
    {
      // single is true implies a single file
      QCString result="The documentation for this service "
                      "was generated from the following file";
      if (single) result+=":"; else result+="s:";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorEnglish::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1988 of file translator_en.h.
    {
      QCString result=sName;
      result+=" Service Reference";
      return result;
    }
Referenced by TranslatorAdapter_1_8_4::trServiceReference().
trServiceReference() [2/2]
virtual QCString TranslatorEnglish::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1988 of file translator_en.h.
    {
      QCString result=sName;
      result+=" Service Reference";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorEnglish::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1973 of file translator_en.h.
    { return "Included Services"; }
Referenced by TranslatorAdapter_1_8_4::trServices().
trServices() [2/2]
virtual QCString TranslatorEnglish::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1973 of file translator_en.h.
    { return "Included Services"; }
trSignals() [1/2]
virtual QCString TranslatorEnglish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 650 of file translator_en.h.
    { return "Signals"; }
trSignals() [2/2]
virtual QCString TranslatorEnglish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 650 of file translator_en.h.
    { return "Signals"; }
trSince() [1/2]
virtual QCString TranslatorEnglish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 990 of file translator_en.h.
    {
      return "Since";
    }
trSince() [2/2]
virtual QCString TranslatorEnglish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 990 of file translator_en.h.
    {
      return "Since";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorEnglish::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2011 of file translator_en.h.
    {
      // single is true implies a single file
      QCString result="The documentation for this singleton "
                      "was generated from the following file";
      if (single) result+=":"; else result+="s:";
      return result;
    }
Referenced by TranslatorAdapter_1_8_4::trSingletonGeneratedFromFiles().
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorEnglish::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2011 of file translator_en.h.
    {
      // single is true implies a single file
      QCString result="The documentation for this singleton "
                      "was generated from the following file";
      if (single) result+=":"; else result+="s:";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorEnglish::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1995 of file translator_en.h.
    {
      QCString result=sName;
      result+=" Singleton Reference";
      return result;
    }
Referenced by TranslatorAdapter_1_8_4::trSingletonReference().
trSingletonReference() [2/2]
virtual QCString TranslatorEnglish::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1995 of file translator_en.h.
    {
      QCString result=sName;
      result+=" Singleton Reference";
      return result;
    }
trSliceInterfaces() [1/2]
virtual QCString TranslatorEnglish::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2162 of file translator_en.h.
    {
        return "Interfaces";
    }
Referenced by TranslatorAdapter_1_8_15::trSliceInterfaces().
trSliceInterfaces() [2/2]
virtual QCString TranslatorEnglish::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2162 of file translator_en.h.
    {
        return "Interfaces";
    }
trSourceFile() [1/2]
virtual QCString TranslatorEnglish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1479 of file translator_en.h.
    {
      return filename + " Source File";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorEnglish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1479 of file translator_en.h.
    {
      return filename + " Source File";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorEnglish::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1408 of file translator_en.h.
    {
      return "Static Package Attributes";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorEnglish::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1408 of file translator_en.h.
    {
      return "Static Package Attributes";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorEnglish::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1394 of file translator_en.h.
    {
      return "Static Package Functions";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorEnglish::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1394 of file translator_en.h.
    {
      return "Static Package Functions";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorEnglish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_en.h.
    {
      return "Static Private Attributes";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorEnglish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_en.h.
    {
      return "Static Private Attributes";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorEnglish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 664 of file translator_en.h.
    { return "Static Private Member Functions"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorEnglish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 664 of file translator_en.h.
    { return "Static Private Member Functions"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorEnglish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_en.h.
    {
      return "Static Protected Attributes";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorEnglish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_en.h.
    {
      return "Static Protected Attributes";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorEnglish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 658 of file translator_en.h.
    { return "Static Protected Member Functions"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorEnglish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 658 of file translator_en.h.
    { return "Static Protected Member Functions"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorEnglish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 925 of file translator_en.h.
    {
      return "Static Public Attributes";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorEnglish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 925 of file translator_en.h.
    {
      return "Static Public Attributes";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorEnglish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 652 of file translator_en.h.
    { return "Static Public Member Functions"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorEnglish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 652 of file translator_en.h.
    { return "Static Public Member Functions"; }
trStructDocumentation() [1/2]
virtual QCString TranslatorEnglish::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2206 of file translator_en.h.
    {
        return "Struct Documentation";
    }
Referenced by TranslatorAdapter_1_8_15::trStructDocumentation().
trStructDocumentation() [2/2]
virtual QCString TranslatorEnglish::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2206 of file translator_en.h.
    {
        return "Struct Documentation";
    }
trStructIndex() [1/2]
virtual QCString TranslatorEnglish::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2194 of file translator_en.h.
    {
        return "Struct Index";
    }
Referenced by TranslatorAdapter_1_8_15::trStructIndex().
trStructIndex() [2/2]
virtual QCString TranslatorEnglish::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2194 of file translator_en.h.
    {
        return "Struct Index";
    }
trStructList() [1/2]
virtual QCString TranslatorEnglish::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2198 of file translator_en.h.
    {
        return "Struct List";
    }
Referenced by TranslatorAdapter_1_8_15::trStructList().
trStructList() [2/2]
virtual QCString TranslatorEnglish::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2198 of file translator_en.h.
    {
        return "Struct List";
    }
trStructListDescription() [1/2]
virtual QCString TranslatorEnglish::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2202 of file translator_en.h.
    {
        return "Here are the structs with brief descriptions:";
    }
Referenced by TranslatorAdapter_1_8_15::trStructListDescription().
trStructListDescription() [2/2]
virtual QCString TranslatorEnglish::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2202 of file translator_en.h.
    {
        return "Here are the structs with brief descriptions:";
    }
trStructs() [1/2]
virtual QCString TranslatorEnglish::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2190 of file translator_en.h.
    {
        return "Structs";
    }
Referenced by TranslatorAdapter_1_8_15::trStructs().
trStructs() [2/2]
virtual QCString TranslatorEnglish::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2190 of file translator_en.h.
    {
        return "Structs";
    }
trSubprogram() [1/2]
virtual QCString TranslatorEnglish::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1742 of file translator_en.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram"));
      if (!singular) result+="s";
      return result;
    }
Referenced by TranslatorAdapter_1_6_0::trSubprogram().
trSubprogram() [2/2]
virtual QCString TranslatorEnglish::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1742 of file translator_en.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram"));
      if (!singular) result+="s";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorEnglish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1614 of file translator_en.h.
    { return "Function/Subroutine Documentation"; }
Referenced by TranslatorAdapter_1_6_0::trSubprogramDocumentation().
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorEnglish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1614 of file translator_en.h.
    { return "Function/Subroutine Documentation"; }
trSubprograms() [1/2]
virtual QCString TranslatorEnglish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1608 of file translator_en.h.
    { return "Functions/Subroutines"; }
Referenced by TranslatorAdapter_1_6_0::trSubprograms().
trSubprograms() [2/2]
virtual QCString TranslatorEnglish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1608 of file translator_en.h.
    { return "Functions/Subroutines"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorEnglish::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1880 of file translator_en.h.
    { return "Template Parameters"; }
Referenced by TranslatorAdapter_1_8_0::trTemplateParameters().
trTemplateParameters() [2/2]
virtual QCString TranslatorEnglish::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1880 of file translator_en.h.
    { return "Template Parameters"; }
trTest() [1/2]
virtual QCString TranslatorEnglish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1082 of file translator_en.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorEnglish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1082 of file translator_en.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorEnglish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1087 of file translator_en.h.
    {
      return "Test List";
    }
trTestList() [2/2]
virtual QCString TranslatorEnglish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1087 of file translator_en.h.
    {
      return "Test List";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorEnglish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 147 of file translator_en.h.
    { return "This is the complete list of members for "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorEnglish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 147 of file translator_en.h.
    { return "This is the complete list of members for "; }
trTodo() [1/2]
virtual QCString TranslatorEnglish::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 959 of file translator_en.h.
    {
      return "Todo";
    }
trTodo() [2/2]
virtual QCString TranslatorEnglish::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 959 of file translator_en.h.
    {
      return "Todo";
    }
trTodoList() [1/2]
virtual QCString TranslatorEnglish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 964 of file translator_en.h.
    {
      return "Todo List";
    }
trTodoList() [2/2]
virtual QCString TranslatorEnglish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 964 of file translator_en.h.
    {
      return "Todo List";
    }
trType() [1/2]
virtual QCString TranslatorEnglish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1731 of file translator_en.h.
    {
      QCString result((first_capital ? "Type" : "type"));
      if (!singular) result+="s";
      return result;
    }
Referenced by TranslatorAdapter_1_6_0::trType().
trType() [2/2]
virtual QCString TranslatorEnglish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1731 of file translator_en.h.
    {
      QCString result((first_capital ? "Type" : "type"));
      if (!singular) result+="s";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorEnglish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1750 of file translator_en.h.
    {
      return "Type Constraints";
    }
Referenced by TranslatorAdapter_1_6_0::trTypeConstraints().
trTypeConstraints() [2/2]
virtual QCString TranslatorEnglish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1750 of file translator_en.h.
    {
      return "Type Constraints";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorEnglish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 486 of file translator_en.h.
    { return "Typedef Documentation"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorEnglish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 486 of file translator_en.h.
    { return "Typedef Documentation"; }
trTypedefs() [1/2]
virtual QCString TranslatorEnglish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 450 of file translator_en.h.
    { return "Typedefs"; }
trTypedefs() [2/2]
virtual QCString TranslatorEnglish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 450 of file translator_en.h.
    { return "Typedefs"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorEnglish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1602 of file translator_en.h.
    { return "Data Type Documentation"; }
Referenced by TranslatorAdapter_1_6_0::trTypeDocumentation().
trTypeDocumentation() [2/2]
virtual QCString TranslatorEnglish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1602 of file translator_en.h.
    { return "Data Type Documentation"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorEnglish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 504 of file translator_en.h.
    { return "Variable Documentation"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorEnglish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 504 of file translator_en.h.
    { return "Variable Documentation"; }
trVariables() [1/2]
virtual QCString TranslatorEnglish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 468 of file translator_en.h.
    { return "Variables"; }
trVariables() [2/2]
virtual QCString TranslatorEnglish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 468 of file translator_en.h.
    { return "Variables"; }
trVersion() [1/2]
virtual QCString TranslatorEnglish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 544 of file translator_en.h.
    { return "Version"; }
trVersion() [2/2]
virtual QCString TranslatorEnglish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 544 of file translator_en.h.
    { return "Version"; }
trVhdlType() [1/2]
virtual QCString TranslatorEnglish::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2049 of file translator_en.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Library";
          else return "Libraries";
        case VhdlDocGen::PACKAGE:
          if (single) return "Package";
          else return "Packages";
        case VhdlDocGen::SIGNAL:
          if (single) return "Signal";
          else return "Signals";
        case VhdlDocGen::COMPONENT:
          if (single) return "Component";
          else return "Components";
        case VhdlDocGen::CONSTANT:
          if (single) return "Constant";
          else return "Constants";
        case VhdlDocGen::ENTITY:
          if (single) return "Entity";
          else return "Entities";
        case VhdlDocGen::TYPE:
          if (single) return "Type";
          else return "Types";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Subtype";
          else return "Subtypes";
        case VhdlDocGen::FUNCTION:
          if (single) return "Function";
          else return "Functions";
        case VhdlDocGen::RECORD:
          if (single) return "Record";
          else return "Records";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedure";
          else return "Procedures";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Architecture";
          else return "Architectures";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Attribute";
          else return "Attributes";
        case VhdlDocGen::PROCESS:
          if (single) return "Process";
          else return "Processes";
        case VhdlDocGen::PORT:
          if (single) return "Port";
          else return "Ports";
        case VhdlDocGen::USE:
          if (single) return "use clause";
          else return "Use Clauses";
        case VhdlDocGen::GENERIC:
          if (single) return "Generic";
          else return "Generics";
        case VhdlDocGen::PACKAGE_BODY:
          return "Package Body";
        case VhdlDocGen::UNITS:
          return "Units";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Shared Variable";
          else return "Shared Variables";
        case VhdlDocGen::VFILE:
          if (single) return "File";
          else return "Files";
        case VhdlDocGen::GROUP:
          if (single) return "Group";
          else return "Groups";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instantiation";
          else return "Instantiations";
        case VhdlDocGen::ALIAS:
          if (single) return "Alias";
          else return "Aliases";
        case VhdlDocGen::CONFIG:
          if (single) return "Configuration";
          else return "Configurations";
        case VhdlDocGen::MISCELLANEOUS:
          return "Miscellaneous";
        case VhdlDocGen::UCF_CONST:
          return "Constraints";
        default:
          return "Class";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
Referenced by TranslatorAdapter_1_8_15::trVhdlType().
trVhdlType() [2/2]
virtual QCString TranslatorEnglish::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2049 of file translator_en.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Library";
          else return "Libraries";
        case VhdlDocGen::PACKAGE:
          if (single) return "Package";
          else return "Packages";
        case VhdlDocGen::SIGNAL:
          if (single) return "Signal";
          else return "Signals";
        case VhdlDocGen::COMPONENT:
          if (single) return "Component";
          else return "Components";
        case VhdlDocGen::CONSTANT:
          if (single) return "Constant";
          else return "Constants";
        case VhdlDocGen::ENTITY:
          if (single) return "Entity";
          else return "Entities";
        case VhdlDocGen::TYPE:
          if (single) return "Type";
          else return "Types";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Subtype";
          else return "Subtypes";
        case VhdlDocGen::FUNCTION:
          if (single) return "Function";
          else return "Functions";
        case VhdlDocGen::RECORD:
          if (single) return "Record";
          else return "Records";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedure";
          else return "Procedures";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Architecture";
          else return "Architectures";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Attribute";
          else return "Attributes";
        case VhdlDocGen::PROCESS:
          if (single) return "Process";
          else return "Processes";
        case VhdlDocGen::PORT:
          if (single) return "Port";
          else return "Ports";
        case VhdlDocGen::USE:
          if (single) return "use clause";
          else return "Use Clauses";
        case VhdlDocGen::GENERIC:
          if (single) return "Generic";
          else return "Generics";
        case VhdlDocGen::PACKAGE_BODY:
          return "Package Body";
        case VhdlDocGen::UNITS:
          return "Units";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Shared Variable";
          else return "Shared Variables";
        case VhdlDocGen::VFILE:
          if (single) return "File";
          else return "Files";
        case VhdlDocGen::GROUP:
          if (single) return "Group";
          else return "Groups";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instantiation";
          else return "Instantiations";
        case VhdlDocGen::ALIAS:
          if (single) return "Alias";
          else return "Aliases";
        case VhdlDocGen::CONFIG:
          if (single) return "Configuration";
          else return "Configurations";
        case VhdlDocGen::MISCELLANEOUS:
          return "Miscellaneous";
        case VhdlDocGen::UCF_CONST:
          return "Constraints";
        default:
          return "Class";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
virtual QCString TranslatorEnglish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 540 of file translator_en.h.
    { return "Warning"; }
trWarning() [2/2]
virtual QCString TranslatorEnglish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 540 of file translator_en.h.
    { return "Warning"; }
trWriteList() [1/2]
virtual QCString TranslatorEnglish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 670 of file translator_en.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", and ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorEnglish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 670 of file translator_en.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", and ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_en.h
doxygen/src/translator_en.h