TemplateNodeResource Class Reference
Class representing an 'markers' tag in a template.
Public Member Functions
TemplateNodeResource (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &, TemplateContext *c)
TemplateNodeResource (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &, TemplateContext *c)
Private Attributes
ExprAstPtr m_resExpr
ExprAstPtr m_asExpr
bool m_append = false
Additional Inherited Members
Detailed Description
Class representing an 'markers' tag in a template.
Definition at line 4537 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeResource() [1/2]
TemplateNodeResource::TemplateNodeResource (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4540 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeResource>(parser,parent,line)
    {
      TRACE(("{TemplateNodeResource(%s)\n",qPrint(data)));
      ExpressionParser ep(parser,line);
      int i;
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"resource tag is missing resource file argument");
        m_resExpr.reset();
        m_asExpr.reset();
      }
      else if ((i=data.find(" as "))!=-1) // resource a as b
      {
        m_resExpr = ep.parse(data.left(i)); // part before as
        m_asExpr = ep.parse(data.mid(i+4)); // part after as
      }
      else if ((i=data.find(" append "))!=-1) // resource a appends to b
      {
        m_resExpr = ep.parse(data.left(i)); // part before append
        m_asExpr = ep.parse(data.mid(i+8)); // part after append
        m_append = true;
      }
      else // resource a
      {
        m_resExpr = ep.parse(data);
        m_asExpr.reset();
      }
      TRACE(("}TemplateNodeResource(%s)\n",qPrint(data)));
    }
References data, m_append, m_asExpr, m_resExpr, TemplateNodeCreator< TemplateNodeResource >::m_templateName, ExpressionParser::parse(), qPrint(), TRACE, and TemplateParser::warn().
TemplateNodeResource() [2/2]
TemplateNodeResource::TemplateNodeResource (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4540 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeResource>(parser,parent,line)
    {
      TRACE(("{TemplateNodeResource(%s)\n",qPrint(data)));
      ExpressionParser ep(parser,line);
      int i;
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"resource tag is missing resource file argument");
        m_resExpr.reset();
        m_asExpr.reset();
      }
      else if ((i=data.find(" as "))!=-1) // resource a as b
      {
        m_resExpr = ep.parse(data.left(i)); // part before as
        m_asExpr = ep.parse(data.mid(i+4)); // part after as
      }
      else if ((i=data.find(" append "))!=-1) // resource a appends to b
      {
        m_resExpr = ep.parse(data.left(i)); // part before append
        m_asExpr = ep.parse(data.mid(i+8)); // part after append
        m_append = true;
      }
      else // resource a
      {
        m_resExpr = ep.parse(data);
        m_asExpr.reset();
      }
      TRACE(("}TemplateNodeResource(%s)\n",qPrint(data)));
    }
References data, m_append, m_asExpr, m_resExpr, TemplateNodeCreator< TemplateNodeResource >::m_templateName, ExpressionParser::parse(), qPrint(), TRACE, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeResource::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4570 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_resExpr)
      {
        QCString resourceFile = m_resExpr->resolve(c).toString();
        if (resourceFile.isEmpty())
        {
          ci->warn(m_templateName,m_line,"invalid parameter for resource command\n");
        }
        else
        {
          QCString outputDirectory = ci->outputDirectory();
          if (m_asExpr)
          {
            QCString targetFile = m_asExpr->resolve(c).toString();
            mkpath(ci,targetFile.str());
            if (targetFile.isEmpty())
            {
              ci->warn(m_templateName,m_line,"invalid parameter at right side of '%s' for resource command\n", m_append ? "append" : "as");
            }
            else
            {
              ResourceMgr::instance().copyResourceAs(resourceFile,outputDirectory,targetFile,m_append);
            }
          }
          else
          {
            ResourceMgr::instance().copyResource(resourceFile,outputDirectory);
          }
        }
      }
    }
References c, ResourceMgr::copyResource(), ResourceMgr::copyResourceAs(), ResourceMgr::instance(), QCString::isEmpty(), m_append, m_asExpr, TemplateNodeCreator< TemplateNodeResource >::m_line, m_resExpr, TemplateNodeCreator< TemplateNodeResource >::m_templateName, TemplateNodeCreator< TemplateNodeResource >::mkpath(), TemplateContextImpl::outputDirectory(), TemplateContextImpl::setLocation(), QCString::str(), and TemplateContextImpl::warn().
render() [2/2]
void TemplateNodeResource::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4570 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_resExpr)
      {
        QCString resourceFile = m_resExpr->resolve(c).toString();
        if (resourceFile.isEmpty())
        {
          ci->warn(m_templateName,m_line,"invalid parameter for resource command\n");
        }
        else
        {
          QCString outputDirectory = ci->outputDirectory();
          if (m_asExpr)
          {
            QCString targetFile = m_asExpr->resolve(c).toString();
            mkpath(ci,targetFile.str());
            if (targetFile.isEmpty())
            {
              ci->warn(m_templateName,m_line,"invalid parameter at right side of '%s' for resource command\n", m_append ? "append" : "as");
            }
            else
            {
              ResourceMgr::instance().copyResourceAs(resourceFile,outputDirectory,targetFile,m_append);
            }
          }
          else
          {
            ResourceMgr::instance().copyResource(resourceFile,outputDirectory);
          }
        }
      }
    }
References c, ResourceMgr::copyResource(), ResourceMgr::copyResourceAs(), ResourceMgr::instance(), QCString::isEmpty(), m_append, m_asExpr, TemplateNodeCreator< TemplateNodeResource >::m_line, m_resExpr, TemplateNodeCreator< TemplateNodeResource >::m_templateName, TemplateNodeCreator< TemplateNodeResource >::mkpath(), TemplateContextImpl::outputDirectory(), TemplateContextImpl::setLocation(), QCString::str(), and TemplateContextImpl::warn().
Member Data Documentation
m_append
bool TemplateNodeResource::m_append = false [private]
Definition at line 4608 of file template.cpp.
Referenced by render(), and TemplateNodeResource().
m_asExpr
ExprAstPtr TemplateNodeResource::m_asExpr [private]
Definition at line 4607 of file template.cpp.
Referenced by render(), and TemplateNodeResource().
m_resExpr
ExprAstPtr TemplateNodeResource::m_resExpr [private]
Definition at line 4606 of file template.cpp.
Referenced by render(), and TemplateNodeResource().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp