FilterTexIndex Class Reference
The implementation of the `texindex` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `texindex` filter.
Definition at line 905 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterTexIndex::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 908 of file template.cpp.
    {
      if (v.isValid() && (v.isString()))
      {
        return TemplateVariant(latexEscapeIndexChars(v.toString()),TRUE);
      }
      else
      {
        return v;
      }
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), latexEscapeIndexChars(), TemplateVariant::toString(), and TRUE.
apply() [2/2]
static TemplateVariant FilterTexIndex::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 908 of file template.cpp.
    {
      if (v.isValid() && (v.isString()))
      {
        return TemplateVariant(latexEscapeIndexChars(v.toString()),TRUE);
      }
      else
      {
        return v;
      }
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), latexEscapeIndexChars(), TemplateVariant::toString(), and TRUE.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp