ModuleListContext::Private Class Reference
Public Member Functions
void addModules ()
void addModules ()
Additional Inherited Members
Detailed Description
Definition at line 6720 of file context.cpp.
Member Function Documentation
addModules() [1/2]
void ModuleListContext::Private::addModules () [inline]
Definition at line 6723 of file context.cpp.
    {
      for (const auto &gd : *Doxygen::groupLinkedMap)
      {
        if (!gd->isReference())
        {
          append(ModuleContext::alloc(gd.get()));
        }
      }
    }
References ModuleContext::alloc(), GenericNodeListContext::append(), and Doxygen::groupLinkedMap.
addModules() [2/2]
void ModuleListContext::Private::addModules () [inline]
Definition at line 6723 of file context.cpp.
    {
      for (const auto &gd : *Doxygen::groupLinkedMap)
      {
        if (!gd->isReference())
        {
          append(ModuleContext::alloc(gd.get()));
        }
      }
    }
References ModuleContext::alloc(), and Doxygen::groupLinkedMap.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp