GestaoHor Class Reference
#include <GestaoHor.h>
Classes
struct cmp
Public Member Functions
GestaoHor ()
void addStudent (Estudante s)
void getDataStudent (string filename1, string filename2)
void getDataAula (string filename)
const set< Estudante > & getStudents () const
const set< Estudante, cmp > & getStudentsByname () const
vector< pair< int, string > > ocupacaoTurmasUC (string uc)
void addPedidos (vector< pair< char, Pedido > > pedido)
void processPedidos ()
bool classConflict (Estudante estudante, UCTurma new_uct)
void removeStudentUCClass (Pedido pedido)
bool addStudentUCClass (Pedido pedido)
Private Attributes
set< UCTurma > aulas
set< Estudante > students
set< Estudante, cmp > students_byname
queue< vector< pair< char, Pedido > > > pedidos
list< vector< pair< char, Pedido > > > failed
Static Private Attributes
static const int cap = 30
Detailed Description
Definition at line 13 of file GestaoHor.h.
Constructor & Destructor Documentation
GestaoHor()
GestaoHor::GestaoHor ()
Definition at line 4 of file GestaoHor.cpp.
{}
Member Function Documentation
addPedidos()
void GestaoHor::addPedidos (vector< pair< char, Pedido > > pedido)
Definition at line 140 of file GestaoHor.cpp.
                                                            {
    pedidos.push(pedido);
}
References pedidos.
Referenced by Menu::alterarMenu().
addStudent()
void GestaoHor::addStudent (Estudante s)
Definition at line 6 of file GestaoHor.cpp.
                                      {
    students.insert(s);
}
References s, and students.
addStudentUCClass()
bool GestaoHor::addStudentUCClass (Pedido pedido)
Definition at line 233 of file GestaoHor.cpp.
                                               {
    int num = pedido.getCode();
    string turma = pedido.getCodTurma();
    string uc = pedido.getCodUc();
    Estudante temp = Estudante();
    temp.setCode(num);
    auto it1 = students.find(temp);
    temp = *it1;
    auto it2 = students_byname.find(temp);
    students.erase(it1);
    students_byname.erase(it2);
    UCTurma t = UCTurma(turma, uc);
    auto timetable = aulas.find(t);
    for(Aula a : timetable->getTimetable()){
        t.addAula(a);
    }
    if (classConflict(temp,t)){
        students.insert(temp);
        students_byname.insert(temp);
        failed.push_back(pedidos.front());
        return false;
    }
    temp.addTurma(t);
    students.insert(temp);
    students_byname.insert(temp);
    vector<pair<int,string>> ocupacao = ocupacaoTurmasUC(uc);
    string num_turma;
    num_turma.push_back(turma[5]);
    num_turma.push_back(turma[6]);
    int min = cap;
    for (pair<int,string> i : ocupacao){
        if (i.first != 0 && i.first < min)
            min = i.first;
    }
    if (ocupacao[stoi(num_turma) - 1].first > cap || abs(ocupacao[stoi(num_turma) - 1].first - min) >= 4){
        failed.push_back(pedidos.front());
        return false;
    }
    return true;
}
References a, UCTurma::addAula(), Estudante::addTurma(), aulas, cap, classConflict(), failed, Pedido::getCode(), Pedido::getCodTurma(), Pedido::getCodUc(), ocupacaoTurmasUC(), pedidos, Estudante::setCode(), students, and students_byname.
Referenced by processPedidos().
classConflict()
bool GestaoHor::classConflict (Estudante estudante, UCTurma new_uct)
Definition at line 192 of file GestaoHor.cpp.
                                                                  {
    vector<Aula> new_tppl;
    for (Aula a:new_uct.getTimetable()){
        if (a.getType() == "TP" || a.getType() == "PL") new_tppl.push_back(a);
    }
    for (UCTurma uct: estudante.getTurmas()){
        for (Aula a: uct.getTimetable()){
            if (a.getType() == "TP" || a.getType() == "PL"){
                for (Aula new_aula: new_tppl){
                    if (new_aula.getWeekday() == a.getWeekday()){
                        if (new_aula.getStartHour() >= a.getStartHour() && new_aula.getStartHour()<(a.getStartHour()+a.getDuration()))
                            return true;
                        if ((new_aula.getStartHour() + new_aula.getDuration()) >= a.getStartHour() && (new_aula.getStartHour() + new_aula.getDuration())<=(a.getStartHour()+a.getDuration()))
                            return true;
                    }
                }
            }
        }
    }
    return false;
}
References a, UCTurma::getTimetable(), and Estudante::getTurmas().
Referenced by addStudentUCClass().
getDataAula()
void GestaoHor::getDataAula (string filename)
Definition at line 10 of file GestaoHor.cpp.
                                          {
    ifstream in(filename);
    string line;
    getline(in, line);
    bool first = true;
    bool exists;
    UCTurma temp;
    string last_uccode;
    list<UCTurma> classes;
    while(getline(in, line)) {
        istringstream iss(line);
        string uccode, classcode;
        string weekDay, startH, duration, type;
        getline(iss, classcode, ',');
        getline(iss, uccode, ',');
        getline(iss, weekDay, ',');
        getline(iss, startH, ',');
        getline(iss, duration, ',');
        getline(iss, type,'\r');
        Aula aula = Aula(weekDay,stof(startH),stof(duration),type);
        if (first){
            temp = UCTurma(classcode, uccode);
            temp.addAula(aula);
            classes.push_back(temp);
            last_uccode = uccode;
            first = false;
            continue;
        }
        if (last_uccode.compare(uccode) == 0){
            exists = false;
            for (UCTurma& ucclass: classes){
                if(ucclass.getCodTurma().compare(classcode) == 0) {
                    ucclass.addAula(aula);
                    exists = true;
                    break;
                }
            }
            if(!exists){
                temp = UCTurma(classcode, uccode);
                temp.addAula(aula);
                classes.push_back(temp);
            }
        }
        else{
            last_uccode = uccode;
            for (UCTurma ucclass: classes){
                aulas.insert(ucclass);
            }
            classes.clear();
            temp = UCTurma(classcode, uccode);
            temp.addAula(aula);
            classes.push_back(temp);
        }
    }
    classes.push_back(temp);
    for (UCTurma ucclass: classes){
        aulas.insert(ucclass);
    }
}
References UCTurma::addAula(), aulas, ghc::filesystem::exists(), and filename.
Referenced by getDataStudent().
getDataStudent()
void GestaoHor::getDataStudent (string filename1, string filename2)
Definition at line 70 of file GestaoHor.cpp.
                                                                 {
    getDataAula(filename2);
    ifstream in(filename1);
    string line;
    getline(in, line);
    bool first = true;
    Estudante temp;
    while(getline(in, line)) {
        istringstream iss(line);
        string num, name;
        string uccode, classcode;
        getline(iss, num, ',');
        getline(iss, name, ',');
        getline(iss, uccode, ',');
        getline(iss, classcode, '\r');
        if (first){
            temp = Estudante(stoi(num), name);
            for (UCTurma ucturma: aulas){
                if ((ucturma.getCodTurma().compare(classcode) == 0) && (ucturma.getCodUc().compare(uccode) == 0))
                    temp.addTurma(ucturma);
            }
            first = false;
            continue;
        }
        if (temp.getName().compare(name) != 0){
            students.insert(temp);
            students_byname.insert(temp);
            temp = Estudante(stoi(num), name);
        }
        for (UCTurma ucturma: aulas){
            if ((ucturma.getCodTurma().compare(classcode) == 0) && (ucturma.getCodUc().compare(uccode) == 0)){
                temp.addTurma(ucturma);
            }
        }
    }
    students.insert(temp);
    students.insert(temp);
}
References Estudante::addTurma(), aulas, getDataAula(), Estudante::getName(), setup::name, students, and students_byname.
Referenced by main().
getStudents()
const set< Estudante > & GestaoHor::getStudents () const
Definition at line 182 of file GestaoHor.cpp.
                                                   {
    return students;
}
References students.
Referenced by Menu::estudantesAno(), Menu::estudantesMaisDeNUCs(), Menu::estudantesTurmaUC(), Menu::estudantesUC(), Menu::ocupacaoDeterminadaTurmaUC(), Menu::ocupacaoDeterminadaUC(), Menu::ocupacaoDeterminadoAno(), ocupacaoTurmasUC(), Menu::ocupacaoUCsAno(), Menu::searchHorarioByName(), and Menu::searchHorarioByNum().
getStudentsByname()
const set< Estudante, GestaoHor::cmp > & GestaoHor::getStudentsByname () const
Definition at line 186 of file GestaoHor.cpp.
                                                                       {
    return students_byname;
}
References students_byname.
Referenced by Menu::estudantesAno(), Menu::estudantesMaisDeNUCs(), Menu::estudantesTurmaUC(), Menu::estudantesUC(), and Menu::searchHorarioByName().
ocupacaoTurmasUC()
vector< pair< int, string > > GestaoHor::ocupacaoTurmasUC (string uc)
Definition at line 110 of file GestaoHor.cpp.
                                                             {
    string basis;
    basis.push_back(uc[6]);
    basis.push_back(uc[7]);
    int aux = stoi(basis);
    if (aux < 10) basis = "1LEIC";
    else if (aux < 20) basis = "2LEIC";
    else basis = "3LEIC";
    vector<pair<int, string>> ocupacao;
    for (int i = 1; i <= 16; i++){
        if (i < 10){
            ocupacao.push_back({0,basis + "0" + to_string(i)});
        } else ocupacao.push_back({0,basis + to_string(i)});
    }
    for (Estudante e: getStudents()){
        for (UCTurma t: e.getTurmas()){
            if (t.getCodUc() == uc){
                string turma;
                turma.push_back(t.getCodTurma()[5]);
                turma.push_back(t.getCodTurma()[6]);
                int num_turma = stoi(turma);
                ocupacao[num_turma - 1].first++;
                break;
            }
        }
    }
    return ocupacao;
}
References e, and getStudents().
Referenced by addStudentUCClass(), and Menu::ocupacaoTurmasMenu().
processPedidos()
void GestaoHor::processPedidos ()
Definition at line 144 of file GestaoHor.cpp.
                               {
    while (!pedidos.empty()){
        Pedido ready_pedido = pedidos.front()[0].second;
        int stuCode = ready_pedido.getCode();
        Estudante backup = Estudante();
        backup.setCode(stuCode);
        auto it1 = students.find(backup);
        backup = *it1;
        bool stopLoop = false;
        for (pair<char,Pedido> pedido : pedidos.front()){
            switch (pedido.first) {
                case 'r': {
                    removeStudentUCClass(pedido.second);
                    break;
                }
                case 'a':{
                    if (!addStudentUCClass(pedido.second)){
                        stopLoop = true;
                        Estudante del = Estudante();
                        del.setCode(stuCode);
                        auto it_del = students.find(del);
                        del = *it_del;
                        auto it_del_name = students_byname.find(del);
                        students.erase(it_del);
                        students_byname.erase(it_del_name);
                        students.insert(backup);
                        students_byname.insert(backup);
                    }
                    break;
                }
            }
            if (stopLoop) break;
        }
        pedidos.pop();
    }
}
References addStudentUCClass(), Pedido::getCode(), pedidos, removeStudentUCClass(), Estudante::setCode(), students, and students_byname.
Referenced by Menu::alterarMenu().
removeStudentUCClass()
void GestaoHor::removeStudentUCClass (Pedido pedido)
Definition at line 215 of file GestaoHor.cpp.
                                                  {
    int num = pedido.getCode();
    string turma = pedido.getCodTurma();
    string uc = pedido.getCodUc();
    Estudante temp = Estudante();
    temp.setCode(num);
    auto it1 = students.find(temp);
    temp = *it1;
    auto it2 = students_byname.find(temp);
    students.erase(it1);
    students_byname.erase(it2);
    UCTurma t = UCTurma(turma, uc);
    temp.removeTurma(t);
    students.insert(temp);
    students_byname.insert(temp);
}
References Pedido::getCode(), Pedido::getCodTurma(), Pedido::getCodUc(), Estudante::removeTurma(), Estudante::setCode(), students, and students_byname.
Referenced by processPedidos().
Member Data Documentation
aulas
set<UCTurma> GestaoHor::aulas [private]
Definition at line 38 of file GestaoHor.h.
Referenced by addStudentUCClass(), getDataAula(), and getDataStudent().
cap
const int GestaoHor::cap = 30 [static], [private]
Definition at line 43 of file GestaoHor.h.
Referenced by addStudentUCClass().
failed
list<vector<pair<char,Pedido> > > GestaoHor::failed [private]
Definition at line 42 of file GestaoHor.h.
Referenced by addStudentUCClass().
pedidos
queue<vector<pair<char,Pedido> > > GestaoHor::pedidos [private]
Definition at line 41 of file GestaoHor.h.
Referenced by addPedidos(), addStudentUCClass(), and processPedidos().
students
set<Estudante> GestaoHor::students [private]
Definition at line 39 of file GestaoHor.h.
Referenced by addStudent(), addStudentUCClass(), getDataStudent(), getStudents(), processPedidos(), and removeStudentUCClass().
students_byname
set<Estudante, cmp> GestaoHor::students_byname [private]
Definition at line 40 of file GestaoHor.h.
Referenced by addStudentUCClass(), getDataStudent(), getStudentsByname(), processPedidos(), and removeStudentUCClass().
The documentation for this class was generated from the following files:
GestaoHor.h
GestaoHor.cpp