XMLParser Class Reference
#include <xml.h>
Classes
struct Private
Public Member Functions
XMLParser (const XMLHandlers &handlers)
~XMLParser ()
void parse (const char *fileName, const char *inputString, bool debugEnabled)
XMLParser (const XMLHandlers &handlers)
~XMLParser ()
void parse (const char *fileName, const char *inputString, bool debugEnabled)
Private Member Functions
virtual int lineNr () const override
virtual std::string fileName () const override
virtual int lineNr () const override
virtual std::string fileName () const override
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Very basic SAX style parser to parse XML documents.
Definition at line 64 of file xml.h.
Constructor & Destructor Documentation
XMLParser() [1/2]
XMLParser::XMLParser (const XMLHandlers & handlers)
Creates an instance of the parser object. Different instances can run on different threads without interference.
Parameters
handlers The event handlers passed by the client.
Definition at line 418 of file xml.l.
                                                : p(new Private)
{
  xmlYYlex_init_extra(&p->xmlYY_extra,&p->yyscanner);
  p->xmlYY_extra.handlers = handlers;
}
References xmlYY_state::handlers, and p.
 XMLParser() [1/2]
XMLParser::~XMLParser ()
Destructor
Definition at line 424 of file xml.l.
{
  xmlYYlex_destroy(p->yyscanner);
}
References p.
XMLParser() [2/2]
XMLParser::XMLParser (const XMLHandlers & handlers)
Creates an instance of the parser object. Different instances can run on different threads without interference.
Parameters
handlers The event handlers passed by the client.
 XMLParser() [2/2]
XMLParser::~XMLParser ()
Destructor
Member Function Documentation
fileName() [1/2]
std::string XMLParser::fileName () const [override], [private], [virtual]
Implements XMLLocator.
Definition at line 489 of file xml.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  return yyextra->fileName;
}
References p.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), parse(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
virtual std::string XMLParser::fileName () const [override], [private], [virtual]
Implements XMLLocator.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
lineNr() [1/2]
int XMLParser::lineNr () const [override], [private], [virtual]
Implements XMLLocator.
Definition at line 483 of file xml.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  return yyextra->lineNr;
}
References p.
lineNr() [2/2]
virtual int XMLParser::lineNr () const [override], [private], [virtual]
Implements XMLLocator.
parse() [1/2]
void XMLParser::parse (const char * fileName, const char * inputString, bool debugEnabled)
Parses a file gives the contents of the file as a string.
Parameters
fileName the name of the file, used for error reporting.
inputString the contents of the file as a zero terminated UTF-8 string.
debugEnabled indicates if debugging via -d lex is enabled or not.
Definition at line 429 of file xml.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
#ifdef FLEX_DEBUG
  xmlYYset_debug(1,p->yyscanner);
#endif
  if (inputStr==nullptr || inputStr[0]=='\0') return; // empty input
  FILE *output = 0;
  const char *enter_txt = 0;
  const char *finished_txt = 0;
  const char *pre_txt = 0;
  if (yy_flex_debug) { output=stderr; pre_txt="--"; enter_txt="entering"; finished_txt="finished"; }
  else if (debugEnabled) { output=stdout; pre_txt=""; enter_txt="Entering"; finished_txt="Finished"; }
  if (output)
  {
    fprintf(output,"%s%s lexical analyzer: %s (for: %s)\n",pre_txt,enter_txt, __FILE__, fileName);
  }
  BEGIN(Initial);
  yyextra->fileName = fileName;
  yyextra->lineNr = 1;
  yyextra->inputString = inputStr;
  yyextra->inputPosition = 0;
  xmlYYrestart(0, yyscanner);
  if (yyextra->handlers.startDocument)
  {
    yyextra->handlers.startDocument();
  }
  xmlYYlex(yyscanner);
  if (yyextra->handlers.endDocument)
  {
    yyextra->handlers.endDocument();
  }
  if (!yyextra->xpath.empty())
  {
    std::string tagName = yyextra->xpath.back();
    std::string msg = "End of file reached while expecting closing tag '"+tagName+"'";
    reportError(yyscanner,msg);
  }
  if (output)
  {
    fprintf(output,"%s%s lexical analyzer: %s (for: %s)\n",pre_txt,finished_txt, __FILE__, fileName);
  }
}
References fileName(), msg(), p, reportError(), and string.
Referenced by LayoutDocManager::init(), main(), LayoutDocManager::parse(), and parseTagFile().
parse() [2/2]
void XMLParser::parse (const char * fileName, const char * inputString, bool debugEnabled)
Parses a file gives the contents of the file as a string.
Parameters
fileName the name of the file, used for error reporting.
inputString the contents of the file as a zero terminated UTF-8 string.
debugEnabled indicates if debugging via -d lex is enabled or not.
Member Data Documentation
p
std::unique_ptr< Private > XMLParser::p [private]
Definition at line 87 of file xml.h.
Referenced by fileName(), lineNr(), parse(), XMLParser(), and ~XMLParser().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/libxml/xml.h
doxygen/libxml/xml.h
doxygen/build/doxygen/libxml/xml.l
doxygen/libxml/xml.l