DotManager Class Reference
#include <dot.h>
Public Member Functions
DotRunner * createRunner (const QCString &absDotName, const QCString &md5Hash)
DotFilePatcher * createFilePatcher (const QCString &fileName)
bool run () const
DotRunner * createRunner (const QCString &absDotName, const QCString &md5Hash)
DotFilePatcher * createFilePatcher (const QCString &fileName)
bool run () const
Static Public Member Functions
static DotManager * instance ()
static DotManager * instance ()
Private Member Functions
DotManager ()
virtual ~DotManager ()
DotManager ()
virtual ~DotManager ()
Private Attributes
std::map< std::string, std::unique_ptr< DotRunner > > m_runners
std::map< std::string, DotFilePatcher > m_filePatchers
DotRunnerQueue * m_queue
std::vector< DotWorkerThreadPtr > m_workers
Detailed Description
Singleton that manages parallel dot invocations and patching files for embedding image maps
Definition at line 34 of file dot.h.
Constructor & Destructor Documentation
DotManager() [1/2]
DotManager::DotManager () [private]
Definition at line 84 of file dot.cpp.
                       : m_runners(), m_filePatchers()
{
  m_queue = new DotRunnerQueue;
  int i;
  int dotNumThreads = Config_getInt(DOT_NUM_THREADS);
  if (dotNumThreads!=1)
  {
    for (i=0;i<dotNumThreads;i++)
    {
      DotWorkerThreadPtr thread(new DotWorkerThread(m_queue));
      thread->start();
      if (thread->isRunning())
      {
        m_workers.push_back(std::move(thread));
      }
      else // no more threads available!
      {
      }
    }
    ASSERT(m_workers.size()>0);
  }
}
References ASSERT, Config_getInt, m_queue, and m_workers.
 DotManager() [1/2]
DotManager::~DotManager () [private], [virtual]
Definition at line 107 of file dot.cpp.
{
  if (!Doxygen::terminating) delete m_queue;
}
References m_queue, and Doxygen::terminating.
DotManager() [2/2]
DotManager::DotManager () [private]
 DotManager() [2/2]
virtual DotManager::~DotManager () [private], [virtual]
Member Function Documentation
createFilePatcher() [1/2]
DotFilePatcher * DotManager::createFilePatcher (const QCString & fileName)
Definition at line 136 of file dot.cpp.
{
  std::lock_guard<std::mutex> lock(g_dotManagerMutex);
  auto patcher = m_filePatchers.find(fileName.str());
  if (patcher != m_filePatchers.end()) return &(patcher->second);
  auto rv = m_filePatchers.emplace(std::make_pair(fileName.str(), fileName));
  assert(rv.second);
  return &(rv.first->second);
}
References g_dotManagerMutex, m_filePatchers, and QCString::str().
createFilePatcher() [2/2]
DotFilePatcher * DotManager::createFilePatcher (const QCString & fileName)
createRunner() [1/2]
DotRunner * DotManager::createRunner (const QCString & absDotName, const QCString & md5Hash)
Definition at line 112 of file dot.cpp.
{
  std::lock_guard<std::mutex> lock(g_dotManagerMutex);
  DotRunner* rv = nullptr;
  auto const runit = m_runners.find(absDotName.str());
  if (runit == m_runners.end())
  {
    auto insobj = std::make_unique<DotRunner>(absDotName, md5Hash);
    rv = insobj.get();
    m_runners.emplace(absDotName.str(), std::move(insobj));
  }
  else
  {
    // we have a match
    if (md5Hash != runit->second->getMd5Hash())
    {
      err("md5 hash does not match for two different runs of %s !\n", qPrint(absDotName));
    }
    rv = runit->second.get();
  }
  assert(rv);
  return rv;
}
References err(), g_dotManagerMutex, m_runners, qPrint(), and QCString::str().
Referenced by DotGraph::prepareDotFile().
createRunner() [2/2]
DotRunner * DotManager::createRunner (const QCString & absDotName, const QCString & md5Hash)
instance() [1/2]
DotManager * DotManager::instance () [static]
Definition at line 78 of file dot.cpp.
{
  static DotManager theInstance;
  return &theInstance;
}
Referenced by DotGraph::generateCode(), generateOutput(), DotGraph::prepareDotFile(), and DotLegendGraph::writeGraph().
instance() [2/2]
static DotManager * DotManager::instance () [static]
run() [1/2]
bool DotManager::run () const
Definition at line 148 of file dot.cpp.
{
  size_t numDotRuns = m_runners.size();
  size_t numFilePatchers = m_filePatchers.size();
  if (numDotRuns+numFilePatchers>1)
  {
    if (m_workers.size()==0)
    {
      msg("Generating dot graphs in single threaded mode...\n");
    }
    else
    {
      msg("Generating dot graphs using %zu parallel threads...\n",std::min(numDotRuns+numFilePatchers,m_workers.size()));
    }
  }
  size_t i=1;
  bool setPath=FALSE;
  if (Config_getBool(GENERATE_HTML))
  {
    setDotFontPath(Config_getString(HTML_OUTPUT));
    setPath=TRUE;
  }
  else if (Config_getBool(GENERATE_LATEX))
  {
    setDotFontPath(Config_getString(LATEX_OUTPUT));
    setPath=TRUE;
  }
  else if (Config_getBool(GENERATE_RTF))
  {
    setDotFontPath(Config_getString(RTF_OUTPUT));
    setPath=TRUE;
  }
  else if (Config_getBool(GENERATE_DOCBOOK))
  {
    setDotFontPath(Config_getString(DOCBOOK_OUTPUT));
    setPath=TRUE;
  }
  Portable::sysTimerStart();
  // fill work queue with dot operations
  size_t prev=1;
  if (m_workers.size()==0) // no threads to work with
  {
    for (auto & dr : m_runners)
    {
      msg("Running dot for graph %zu/%zu\n",prev,numDotRuns);
      dr.second->run();
      prev++;
    }
  }
  else // use multiple threads to run instances of dot in parallel
  {
    for (auto & dr: m_runners)
    {
      m_queue->enqueue(dr.second.get());
    }
    // wait for the queue to become empty
    while ((i=m_queue->size())>0)
    {
      i = numDotRuns - i;
      while (i>=prev)
      {
        msg("Running dot for graph %zu/%zu\n",prev,numDotRuns);
        prev++;
      }
      Portable::sleep(100);
    }
    while (numDotRuns>=prev)
    {
      msg("Running dot for graph %zu/%zu\n",prev,numDotRuns);
      prev++;
    }
    // signal the workers we are done
    for (i=0;i<m_workers.size();i++)
    {
      m_queue->enqueue(0); // add terminator for each worker
    }
    // wait for the workers to finish
    for (i=0;i<m_workers.size();i++)
    {
      m_workers.at(i)->wait();
    }
  }
  Portable::sysTimerStop();
  if (setPath)
  {
    unsetDotFontPath();
  }
  // patch the output file and insert the maps and figures
  i=1;
  // since patching the svg files may involve patching the header of the SVG
  // (for zoomable SVGs), and patching the .html files requires reading that
  // header after the SVG is patched, we first process the .svg files and
  // then the other files.
  for (auto & fp : m_filePatchers)
  {
    if (fp.second.isSVGFile())
    {
      msg("Patching output file %zu/%zu\n",i,numFilePatchers);
      if (!fp.second.run()) return FALSE;
      i++;
    }
  }
  for (auto& fp : m_filePatchers)
  {
    if (!fp.second.isSVGFile())
    {
      msg("Patching output file %zu/%zu\n",i,numFilePatchers);
      if (!fp.second.run()) return FALSE;
      i++;
    }
  }
  return TRUE;
}
References Config_getBool, Config_getString, DotRunnerQueue::enqueue(), FALSE, m_filePatchers, m_queue, m_runners, m_workers, msg(), setDotFontPath(), DotRunnerQueue::size(), Portable::sleep(), Portable::sysTimerStart(), Portable::sysTimerStop(), TRUE, and unsetDotFontPath().
Referenced by generateOutput().
run() [2/2]
bool DotManager::run () const
Member Data Documentation
m_filePatchers
std::map< std::string, DotFilePatcher > DotManager::m_filePatchers [private]
Definition at line 48 of file dot.h.
Referenced by createFilePatcher(), and run().
m_queue
DotRunnerQueue * DotManager::m_queue [private]
Definition at line 49 of file dot.h.
Referenced by DotManager(), run(), and ~DotManager().
m_runners
std::map< std::string, std::unique_ptr< DotRunner > > DotManager::m_runners [private]
Definition at line 47 of file dot.h.
Referenced by createRunner(), and run().
m_workers
std::vector< DotWorkerThreadPtr > DotManager::m_workers [private]
Definition at line 50 of file dot.h.
Referenced by DotManager(), and run().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dot.h
doxygen/src/dot.h
doxygen/build/doxygen/src/dot.cpp
doxygen/src/dot.cpp