TemplateParser Class Reference
Parser for templates.
Public Member Functions
TemplateParser (const TemplateEngine *engine, const QCString &templateName, TemplateTokenStream &tokens)
void parse (TemplateNode *parent, int line, const StringVector &stopAt, TemplateNodeList &nodes)
bool hasNextToken () const
TemplateTokenPtr takeNextToken ()
void removeNextToken ()
void prependToken (TemplateTokenPtr &&token)
const TemplateToken * currentToken () const
QCString templateName () const
void warn (const QCString &fileName, int line, const char *fmt,...) const
TemplateParser (const TemplateEngine *engine, const QCString &templateName, TemplateTokenStream &tokens)
void parse (TemplateNode *parent, int line, const StringVector &stopAt, TemplateNodeList &nodes)
bool hasNextToken () const
TemplateTokenPtr takeNextToken ()
void removeNextToken ()
void prependToken (TemplateTokenPtr &&token)
const TemplateToken * currentToken () const
QCString templateName () const
void warn (const QCString &fileName, int line, const char *fmt,...) const
Private Attributes
const TemplateEngine * m_engine = 0
QCString m_templateName
TemplateTokenStream & m_tokens
Detailed Description
Parser for templates.
Definition at line 1984 of file template.cpp.
Constructor & Destructor Documentation
TemplateParser() [1/2]
TemplateParser::TemplateParser (const TemplateEngine * engine, const QCString & templateName, TemplateTokenStream & tokens)
Definition at line 5049 of file template.cpp.
                                                            :
   m_engine(engine), m_templateName(templateName), m_tokens(tokens)
{
}
TemplateParser() [2/2]
TemplateParser::TemplateParser (const TemplateEngine * engine, const QCString & templateName, TemplateTokenStream & tokens)
Member Function Documentation
currentToken() [1/2]
const TemplateToken * TemplateParser::currentToken () const
Definition at line 5147 of file template.cpp.
{
  return m_tokens.front().get();
}
References m_tokens.
currentToken() [2/2]
const TemplateToken * TemplateParser::currentToken () const
hasNextToken() [1/2]
bool TemplateParser::hasNextToken () const
Definition at line 5134 of file template.cpp.
{
  return !m_tokens.empty();
}
References m_tokens.
Referenced by parse().
hasNextToken() [2/2]
bool TemplateParser::hasNextToken () const
parse() [1/2]
void TemplateParser::parse (TemplateNode * parent, int line, const StringVector & stopAt, TemplateNodeList & nodes)
Definition at line 5056 of file template.cpp.
{
  TRACE(("{TemplateParser::parse\n"));
  // process the tokens. Build node list
  while (hasNextToken())
  {
    auto tok = takeNextToken();
    TRACE(("%p:Token type=%d data='%s' line=%d\n",
           (void*)parent,tok->type,qPrint(tok->data),tok->line));
    switch(tok->type)
    {
      case TemplateToken::Text:
        nodes.push_back(std::make_unique<TemplateNodeText>(this,parent,tok->line,tok->data));
        break;
      case TemplateToken::Variable: // {{ var }}
        nodes.push_back(std::make_unique<TemplateNodeVariable>(this,parent,tok->line,tok->data));
        break;
      case TemplateToken::Block: // {% tag %}
        {
          QCString command = tok->data;
          int sep = command.find(' ');
          if (sep!=-1)
          {
            command=command.left(sep);
          }
          TemplateToken *tok_ptr = tok.get();
          if (std::find(stopAt.begin(),stopAt.end(),command.str())!=stopAt.end())
          {
            prependToken(std::move(tok));
            TRACE(("}TemplateParser::parse: stop\n"));
            return;
          }
          QCString arg;
          if (sep!=-1)
          {
            arg = tok_ptr->data.mid(sep+1);
          }
          TemplateNodePtr node = TemplateNodeFactory::instance().create(
                                 command,this,parent,tok_ptr->line,arg);
          if (node)
          {
            nodes.push_back(std::move(node));
          }
          else if (command=="empty" || command=="else" ||
                   command=="endif" || command=="endfor" ||
                   command=="endblock" || command=="endwith" ||
                   command=="endrecursetree" || command=="endspaceless" ||
                   command=="endmarkers" || command=="endmsg" ||
                   command=="endrepeat" || command=="elif" ||
                   command=="endrange" || command=="endtabbing" ||
                   command=="endencoding")
          {
            warn(m_templateName,tok_ptr->line,"Found tag '%s' without matching start tag",qPrint(command));
          }
          else
          {
            warn(m_templateName,tok_ptr->line,"Unknown tag '%s'",qPrint(command));
          }
        }
        break;
    }
  }
  if (!stopAt.empty())
  {
    QCString options;
    for (const auto &s : stopAt)
    {
      if (!options.isEmpty()) options+=", ";
      options+=s.c_str();
    }
    warn(m_templateName,line,"Unclosed tag in template, expected one of: %s",
        qPrint(options));
  }
  TRACE(("}TemplateParser::parse: last token\n"));
}
References TemplateToken::Block, TemplateNodeFactory::create(), QCString::data(), TemplateToken::data, QCString::find(), hasNextToken(), TemplateNodeFactory::instance(), QCString::isEmpty(), QCString::left(), TemplateToken::line, m_templateName, QCString::mid(), parent(), prependToken(), qPrint(), s, QCString::str(), takeNextToken(), TemplateToken::Text, TRACE, TemplateToken::Variable, and warn().
Referenced by TemplateImpl::TemplateImpl(), TemplateNodeBlock::TemplateNodeBlock(), TemplateNodeEncoding::TemplateNodeEncoding(), TemplateNodeExtend::TemplateNodeExtend(), TemplateNodeFor::TemplateNodeFor(), TemplateNodeIf::TemplateNodeIf(), TemplateNodeMarkers::TemplateNodeMarkers(), TemplateNodeMsg::TemplateNodeMsg(), TemplateNodeRange::TemplateNodeRange(), TemplateNodeRepeat::TemplateNodeRepeat(), TemplateNodeSpaceless::TemplateNodeSpaceless(), TemplateNodeTabbing::TemplateNodeTabbing(), TemplateNodeTree::TemplateNodeTree(), and TemplateNodeWith::TemplateNodeWith().
parse() [2/2]
void TemplateParser::parse (TemplateNode * parent, int line, const StringVector & stopAt, TemplateNodeList & nodes)
prependToken() [1/2]
void TemplateParser::prependToken (TemplateTokenPtr && token)
Definition at line 5157 of file template.cpp.
{
  m_tokens.push_front(std::move(token));
}
References m_tokens.
Referenced by parse().
prependToken() [2/2]
void TemplateParser::prependToken (TemplateTokenPtr && token)
removeNextToken() [1/2]
void TemplateParser::removeNextToken ()
Definition at line 5152 of file template.cpp.
{
  m_tokens.pop_front();
}
References m_tokens.
Referenced by TemplateNodeBlock::TemplateNodeBlock(), TemplateNodeEncoding::TemplateNodeEncoding(), TemplateNodeFor::TemplateNodeFor(), TemplateNodeIf::TemplateNodeIf(), TemplateNodeMarkers::TemplateNodeMarkers(), TemplateNodeMsg::TemplateNodeMsg(), TemplateNodeRange::TemplateNodeRange(), TemplateNodeRepeat::TemplateNodeRepeat(), TemplateNodeSpaceless::TemplateNodeSpaceless(), TemplateNodeTabbing::TemplateNodeTabbing(), TemplateNodeTree::TemplateNodeTree(), and TemplateNodeWith::TemplateNodeWith().
removeNextToken() [2/2]
void TemplateParser::removeNextToken ()
takeNextToken() [1/2]
TemplateTokenPtr TemplateParser::takeNextToken ()
Definition at line 5139 of file template.cpp.
{
  if (m_tokens.empty()) return TemplateTokenPtr();
  auto tok = std::move(m_tokens.front());
  m_tokens.pop_front();
  return tok;
}
References m_tokens.
Referenced by parse(), TemplateNodeFor::TemplateNodeFor(), and TemplateNodeIf::TemplateNodeIf().
takeNextToken() [2/2]
TemplateTokenPtr TemplateParser::takeNextToken ()
templateName() [1/2]
QCString TemplateParser::templateName () const [inline]
Definition at line 1997 of file template.cpp.
{ return m_templateName; }
References m_templateName.
Referenced by ExpressionParser::getNextToken(), ExpressionParser::parseNotExpression(), ExpressionParser::parsePrimaryExpression(), TemplateNodeBlock::TemplateNodeBlock(), TemplateNodeCloseSubIndex::TemplateNodeCloseSubIndex(), TemplateNodeCycle::TemplateNodeCycle(), TemplateNodeIndexEntry::TemplateNodeIndexEntry(), TemplateNodeOpenSubIndex::TemplateNodeOpenSubIndex(), and TemplateNodeWith::TemplateNodeWith().
templateName() [2/2]
QCString TemplateParser::templateName () const [inline]
Definition at line 1997 of file template.cpp.
{ return m_templateName; }
warn() [1/2]
void TemplateParser::warn (const QCString & fileName, int line, const char * fmt, ...) const
Definition at line 5162 of file template.cpp.
{
  va_list args;
  va_start(args,fmt);
  va_warn(fileName,line,fmt,args);
  va_end(args);
  m_engine->printIncludeContext(fileName,line);
}
References fmt, m_engine, TemplateEngine::printIncludeContext(), and va_warn().
Referenced by parse(), TemplateNodeBlock::TemplateNodeBlock(), TemplateNodeCloseSubIndex::TemplateNodeCloseSubIndex(), TemplateNodeCreate::TemplateNodeCreate(), TemplateNodeCycle::TemplateNodeCycle(), TemplateNodeEncoding::TemplateNodeEncoding(), TemplateNodeExtend::TemplateNodeExtend(), TemplateNodeFor::TemplateNodeFor(), TemplateNodeIf::TemplateNodeIf(), TemplateNodeInclude::TemplateNodeInclude(), TemplateNodeIndexEntry::TemplateNodeIndexEntry(), TemplateNodeMarkers::TemplateNodeMarkers(), TemplateNodeOpenSubIndex::TemplateNodeOpenSubIndex(), TemplateNodeRange::TemplateNodeRange(), TemplateNodeResource::TemplateNodeResource(), TemplateNodeTree::TemplateNodeTree(), TemplateNodeVariable::TemplateNodeVariable(), and TemplateNodeWith::TemplateNodeWith().
warn() [2/2]
void TemplateParser::warn (const QCString & fileName, int line, const char * fmt, ...) const
Member Data Documentation
m_engine
const TemplateEngine * TemplateParser::m_engine = 0 [private]
Definition at line 2000 of file template.cpp.
Referenced by warn().
m_templateName
QCString TemplateParser::m_templateName [private]
Definition at line 2001 of file template.cpp.
Referenced by parse(), and templateName().
m_tokens
TemplateTokenStream & TemplateParser::m_tokens [private]
Definition at line 2002 of file template.cpp.
Referenced by currentToken(), hasNextToken(), prependToken(), removeNextToken(), and takeNextToken().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp