HtmlHelpRecoder Class Reference
Public Member Functions
HtmlHelpRecoder ()
~HtmlHelpRecoder ()
HtmlHelpRecoder (const HtmlHelpRecoder &)=delete
HtmlHelpRecoder & operator= (const HtmlHelpRecoder &)=delete
void initialize ()
void finalize ()
QCString recode (const QCString &s)
HtmlHelpRecoder ()
~HtmlHelpRecoder ()
HtmlHelpRecoder (const HtmlHelpRecoder &)=delete
HtmlHelpRecoder & operator= (const HtmlHelpRecoder &)=delete
void initialize ()
void finalize ()
QCString recode (const QCString &s)
Private Attributes
void * m_iconv_null = reinterpret_cast<void*>(-1)
void * m_fromUtf8 = m_iconv_null
Detailed Description
Helper class to deal with recoding the UTF8 encoded text back to the native encoding specified by CHM_INDEX_ENCODING.
Definition at line 42 of file htmlhelp.cpp.
Constructor & Destructor Documentation
HtmlHelpRecoder() [1/4]
HtmlHelpRecoder::HtmlHelpRecoder () [inline]
Definition at line 45 of file htmlhelp.cpp.
{}
 HtmlHelpRecoder() [1/2]
HtmlHelpRecoder::~HtmlHelpRecoder () [inline]
Definition at line 46 of file htmlhelp.cpp.
{ finalize(); }
References finalize().
HtmlHelpRecoder() [2/4]
HtmlHelpRecoder::HtmlHelpRecoder (const HtmlHelpRecoder &) [delete]
HtmlHelpRecoder() [3/4]
HtmlHelpRecoder::HtmlHelpRecoder () [inline]
Definition at line 45 of file htmlhelp.cpp.
{}
 HtmlHelpRecoder() [2/2]
HtmlHelpRecoder::~HtmlHelpRecoder () [inline]
Definition at line 46 of file htmlhelp.cpp.
{ finalize(); }
References finalize().
HtmlHelpRecoder() [4/4]
HtmlHelpRecoder::HtmlHelpRecoder (const HtmlHelpRecoder &) [delete]
Member Function Documentation
finalize() [1/2]
void HtmlHelpRecoder::finalize () [inline]
Definition at line 60 of file htmlhelp.cpp.
    {
      if (m_fromUtf8!=m_iconv_null)
      {
        portable_iconv_close(m_fromUtf8);
        m_fromUtf8 = m_iconv_null;
      }
    }
References m_fromUtf8, m_iconv_null, and portable_iconv_close().
Referenced by ~HtmlHelpRecoder().
finalize() [2/2]
void HtmlHelpRecoder::finalize () [inline]
Definition at line 60 of file htmlhelp.cpp.
    {
      if (m_fromUtf8!=m_iconv_null)
      {
        portable_iconv_close(m_fromUtf8);
        m_fromUtf8 = m_iconv_null;
      }
    }
References m_fromUtf8, m_iconv_null, and portable_iconv_close().
initialize() [1/2]
void HtmlHelpRecoder::initialize () [inline]
Definition at line 50 of file htmlhelp.cpp.
    {
      QCString str = Config_getString(CHM_INDEX_ENCODING);
      if (str.isEmpty()) str = "CP1250"; // use safe and likely default
      m_fromUtf8 = portable_iconv_open(str.data(),"UTF-8");
      if (m_fromUtf8==m_iconv_null)
      {
        term("unsupported character conversion for CHM_INDEX_ENCODING: '%s'->'UTF-8'\n", qPrint(str));
      }
    }
References Config_getString, QCString::data(), QCString::isEmpty(), m_fromUtf8, m_iconv_null, portable_iconv_open(), qPrint(), and term().
initialize() [2/2]
void HtmlHelpRecoder::initialize () [inline]
Definition at line 50 of file htmlhelp.cpp.
    {
      QCString str = Config_getString(CHM_INDEX_ENCODING);
      if (str.isEmpty()) str = "CP1250"; // use safe and likely default
      m_fromUtf8 = portable_iconv_open(str.data(),"UTF-8");
      if (m_fromUtf8==m_iconv_null)
      {
        term("unsupported character conversion for CHM_INDEX_ENCODING: '%s'->'UTF-8'\n", qPrint(str));
      }
    }
References Config_getString, QCString::data(), QCString::isEmpty(), m_fromUtf8, m_iconv_null, portable_iconv_open(), qPrint(), and term().
operator=() [1/2]
HtmlHelpRecoder & HtmlHelpRecoder::operator= (const HtmlHelpRecoder &) [delete]
operator=() [2/2]
HtmlHelpRecoder & HtmlHelpRecoder::operator= (const HtmlHelpRecoder &) [delete]
recode() [1/2]
QCString HtmlHelpRecoder::recode (const QCString & s) [inline]
Definition at line 69 of file htmlhelp.cpp.
    {
      size_t iSize = s.length();
      size_t oSize = iSize*4+1;
      QCString output(oSize);
      size_t iLeft = iSize;
      size_t oLeft = oSize;
      const char *iPtr = s.data();
      char *oPtr = output.rawData();
      if (!portable_iconv(m_fromUtf8,&iPtr,&iLeft,&oPtr,&oLeft))
      {
        oSize -= oLeft;
        output.resize(oSize+1);
        output.at(oSize)='\0';
        return output;
      }
      else
      {
        return s;
      }
    }
References QCString::at(), gdFont::data, m_fromUtf8, portable_iconv(), QCString::rawData(), QCString::resize(), and s.
Referenced by HtmlHelp::Private::createProjectFile(), and HtmlHelpIndex::writeFields().
recode() [2/2]
QCString HtmlHelpRecoder::recode (const QCString & s) [inline]
Definition at line 69 of file htmlhelp.cpp.
    {
      size_t iSize = s.length();
      size_t oSize = iSize*4+1;
      QCString output(oSize);
      size_t iLeft = iSize;
      size_t oLeft = oSize;
      const char *iPtr = s.data();
      char *oPtr = output.rawData();
      if (!portable_iconv(m_fromUtf8,&iPtr,&iLeft,&oPtr,&oLeft))
      {
        oSize -= oLeft;
        output.resize(oSize+1);
        output.at(oSize)='\0';
        return output;
      }
      else
      {
        return s;
      }
    }
References QCString::at(), gdFont::data, m_fromUtf8, portable_iconv(), QCString::rawData(), QCString::resize(), and s.
Member Data Documentation
m_fromUtf8
void * HtmlHelpRecoder::m_fromUtf8 = m_iconv_null [private]
Definition at line 92 of file htmlhelp.cpp.
Referenced by finalize(), initialize(), and recode().
m_iconv_null
void * HtmlHelpRecoder::m_iconv_null = reinterpret_cast<void*>(-1) [private]
Definition at line 91 of file htmlhelp.cpp.
Referenced by finalize(), and initialize().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/htmlhelp.cpp
doxygen/src/htmlhelp.cpp