TemplateNodeWith Class Reference
Class representing an 'with' tag in a template.
Classes
struct Mapping
Public Member Functions
TemplateNodeWith (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeWith ()
void render (TextStream &ts, TemplateContext *c)
TemplateNodeWith (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeWith ()
void render (TextStream &ts, TemplateContext *c)
Private Attributes
TemplateNodeList m_nodes
std::vector< Mapping > m_args
Additional Inherited Members
Detailed Description
Class representing an 'with' tag in a template.
Definition at line 4181 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeWith() [1/2]
TemplateNodeWith::TemplateNodeWith (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4190 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeWith>(parser,parent,line)
    {
      TRACE(("{TemplateNodeWith(%s)\n",qPrint(data)));
      ExpressionParser expParser(parser,line);
      QCString filteredData = data;
      removeSpacesAroundEquals(filteredData);
      std::vector<QCString> args = split(filteredData," ");
      auto it = args.begin();
      while (it!=args.end())
      {
        QCString arg = *it;
        int j=arg.find('=');
        if (j>0)
        {
          ExprAstPtr expr = expParser.parse(arg.mid(j+1));
          if (expr)
          {
            m_args.emplace_back(arg.left(j),std::move(expr));
          }
        }
        else
        {
          parser->warn(parser->templateName(),line,"invalid argument '%s' for 'with' tag",qPrint(arg));
        }
        ++it;
      }
      StringVector stopAt = { "endwith" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endwith
      TRACE(("}TemplateNodeWith(%s)\n",qPrint(data)));
    }
References data, QCString::find(), QCString::left(), m_args, m_nodes, QCString::mid(), ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), removeSpacesAroundEquals(), split(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
 TemplateNodeWith() [1/2]
TemplateNodeWith::~TemplateNodeWith () [inline]
Definition at line 4222 of file template.cpp.
    {
    }
TemplateNodeWith() [2/2]
TemplateNodeWith::TemplateNodeWith (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4190 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeWith>(parser,parent,line)
    {
      TRACE(("{TemplateNodeWith(%s)\n",qPrint(data)));
      ExpressionParser expParser(parser,line);
      QCString filteredData = data;
      removeSpacesAroundEquals(filteredData);
      std::vector<QCString> args = split(filteredData," ");
      auto it = args.begin();
      while (it!=args.end())
      {
        QCString arg = *it;
        int j=arg.find('=');
        if (j>0)
        {
          ExprAstPtr expr = expParser.parse(arg.mid(j+1));
          if (expr)
          {
            m_args.emplace_back(arg.left(j),std::move(expr));
          }
        }
        else
        {
          parser->warn(parser->templateName(),line,"invalid argument '%s' for 'with' tag",qPrint(arg));
        }
        ++it;
      }
      StringVector stopAt = { "endwith" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endwith
      TRACE(("}TemplateNodeWith(%s)\n",qPrint(data)));
    }
References data, QCString::find(), QCString::left(), m_args, m_nodes, QCString::mid(), ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), removeSpacesAroundEquals(), split(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
 TemplateNodeWith() [2/2]
TemplateNodeWith::~TemplateNodeWith () [inline]
Definition at line 4222 of file template.cpp.
    {
    }
Member Function Documentation
render() [1/2]
void TemplateNodeWith::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4225 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      c->push();
      for (const auto &mapping : m_args)
      {
        TemplateVariant value = mapping.value->resolve(c);
        ci->set(mapping.name,value);
      }
      m_nodes.render(ts,c);
      c->pop();
    }
References c, m_args, TemplateNodeCreator< TemplateNodeWith >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeWith >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::set(), and TemplateContextImpl::setLocation().
render() [2/2]
void TemplateNodeWith::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4225 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      c->push();
      for (const auto &mapping : m_args)
      {
        TemplateVariant value = mapping.value->resolve(c);
        ci->set(mapping.name,value);
      }
      m_nodes.render(ts,c);
      c->pop();
    }
References c, m_args, TemplateNodeCreator< TemplateNodeWith >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeWith >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::set(), and TemplateContextImpl::setLocation().
Member Data Documentation
m_args
std::vector< Mapping > TemplateNodeWith::m_args [private]
Definition at line 4241 of file template.cpp.
Referenced by render(), and TemplateNodeWith().
m_nodes
TemplateNodeList TemplateNodeWith::m_nodes [private]
Definition at line 4240 of file template.cpp.
Referenced by render(), and TemplateNodeWith().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp