NamespaceMembersIndexContext::Private Class Reference
Public Member Functions
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Types
using MemberFilter = bool(MemberDef::*)() const
using MemberFilter = bool(MemberDef::*)() const
Private Member Functions
TemplateVariant all () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant enumValues () const
TemplateVariant macros () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant related () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
TemplateVariant createMembersFiltered (MemberFilter filter) const
TemplateVariant createAll () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createTypedefs () const
TemplateVariant createEnums () const
TemplateVariant createEnumValues () const
TemplateVariant all () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant enumValues () const
TemplateVariant macros () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant related () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
TemplateVariant createMembersFiltered (MemberFilter filter) const
TemplateVariant createAll () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createTypedefs () const
TemplateVariant createEnums () const
TemplateVariant createEnumValues () const
Private Attributes
CachedItem< TemplateVariant, Private, &Private::createAll > m_all
CachedItem< TemplateVariant, Private, &Private::createFunctions > m_functions
CachedItem< TemplateVariant, Private, &Private::createVariables > m_variables
CachedItem< TemplateVariant, Private, &Private::createTypedefs > m_typedefs
CachedItem< TemplateVariant, Private, &Private::createEnums > m_enums
CachedItem< TemplateVariant, Private, &Private::createEnumValues > m_enumValues
Static Private Attributes
static const PropertyMap< NamespaceMembersIndexContext::Private > s_inst
Detailed Description
Definition at line 7293 of file context.cpp.
Member Typedef Documentation
MemberFilter [1/2]
using NamespaceMembersIndexContext::Private::MemberFilter = bool (MemberDef::*)() const [private]
Definition at line 7319 of file context.cpp.
MemberFilter [2/2]
using NamespaceMembersIndexContext::Private::MemberFilter = bool (MemberDef::*)() const [private]
Definition at line 7319 of file context.cpp.
Member Function Documentation
all() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::all () const [inline], [private]
Definition at line 7302 of file context.cpp.
{ return m_all.get(this); }
References m_all.
all() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::all () const [inline], [private]
Definition at line 7302 of file context.cpp.
{ return m_all.get(this); }
createAll() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::createAll () const [inline], [private]
Definition at line 7341 of file context.cpp.
{ return createMembersFiltered(0); }
References createMembersFiltered().
createAll() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::createAll () const [inline], [private]
Definition at line 7341 of file context.cpp.
{ return createMembersFiltered(0); }
createEnums() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::createEnums () const [inline], [private]
Definition at line 7345 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumerate); }
References createMembersFiltered(), and MemberDef::isEnumerate().
createEnums() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::createEnums () const [inline], [private]
Definition at line 7345 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumerate); }
References MemberDef::isEnumerate().
createEnumValues() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::createEnumValues () const [inline], [private]
Definition at line 7346 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumValue); }
References createMembersFiltered(), and MemberDef::isEnumValue().
createEnumValues() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::createEnumValues () const [inline], [private]
Definition at line 7346 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumValue); }
References MemberDef::isEnumValue().
createFunctions() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::createFunctions () const [inline], [private]
Definition at line 7342 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isFunction); }
References createMembersFiltered(), and MemberDef::isFunction().
createFunctions() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::createFunctions () const [inline], [private]
Definition at line 7342 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isFunction); }
References MemberDef::isFunction().
createMembersFiltered() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::createMembersFiltered (MemberFilter filter) const [inline], [private]
Definition at line 7320 of file context.cpp.
    {
      TemplateVariantList list;
      for (const auto &mn : *Doxygen::functionNameLinkedMap)
      {
        for (const auto &md : *mn)
        {
          const NamespaceDef *nd=md->getNamespaceDef();
          if (nd && nd->isLinkableInProject() &&
              !md->name().isEmpty() && md->isLinkableInProject())
          {
            if (filter==0 || (md.get()->*filter)())
            {
              list.push_back(MemberContext::alloc(md.get()));
            }
          }
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), filter, Doxygen::functionNameLinkedMap, and NamespaceDef::isLinkableInProject().
Referenced by createAll(), createEnums(), createEnumValues(), createFunctions(), createTypedefs(), and createVariables().
createMembersFiltered() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::createMembersFiltered (MemberFilter filter) const [inline], [private]
Definition at line 7320 of file context.cpp.
    {
      TemplateVariantList list;
      for (const auto &mn : *Doxygen::functionNameLinkedMap)
      {
        for (const auto &md : *mn)
        {
          const NamespaceDef *nd=md->getNamespaceDef();
          if (nd && nd->isLinkableInProject() &&
              !md->name().isEmpty() && md->isLinkableInProject())
          {
            if (filter==0 || (md.get()->*filter)())
            {
              list.push_back(MemberContext::alloc(md.get()));
            }
          }
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), filter, Doxygen::functionNameLinkedMap, and NamespaceDef::isLinkableInProject().
createTypedefs() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::createTypedefs () const [inline], [private]
Definition at line 7344 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isTypedef); }
References createMembersFiltered(), and MemberDef::isTypedef().
createTypedefs() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::createTypedefs () const [inline], [private]
Definition at line 7344 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isTypedef); }
References MemberDef::isTypedef().
createVariables() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::createVariables () const [inline], [private]
Definition at line 7343 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isVariable); }
References createMembersFiltered(), and MemberDef::isVariable().
createVariables() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::createVariables () const [inline], [private]
Definition at line 7343 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isVariable); }
References MemberDef::isVariable().
enums() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::enums () const [inline], [private]
Definition at line 7306 of file context.cpp.
{ return m_enums.get(this); }
References m_enums.
enums() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::enums () const [inline], [private]
Definition at line 7306 of file context.cpp.
{ return m_enums.get(this); }
enumValues() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::enumValues () const [inline], [private]
Definition at line 7307 of file context.cpp.
{ return m_enumValues.get(this); }
References m_enumValues.
enumValues() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::enumValues () const [inline], [private]
Definition at line 7307 of file context.cpp.
{ return m_enumValues.get(this); }
events() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::events () const [inline], [private]
Definition at line 7310 of file context.cpp.
{ return FALSE; }
References FALSE.
events() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::events () const [inline], [private]
Definition at line 7310 of file context.cpp.
{ return FALSE; }
References FALSE.
fields() [1/2]
StringVector NamespaceMembersIndexContext::Private::fields () const [inline]
Definition at line 7298 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector NamespaceMembersIndexContext::Private::fields () const [inline]
Definition at line 7298 of file context.cpp.
{ return s_inst.fields(); }
fileName() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::fileName () const [inline], [private]
Definition at line 7312 of file context.cpp.
{ return "namespacemembers"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::fileName () const [inline], [private]
Definition at line 7312 of file context.cpp.
{ return "namespacemembers"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
functions() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::functions () const [inline], [private]
Definition at line 7303 of file context.cpp.
{ return m_functions.get(this); }
References m_functions.
functions() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::functions () const [inline], [private]
Definition at line 7303 of file context.cpp.
{ return m_functions.get(this); }
get() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::get (const QCString & n) const [inline]
Definition at line 7297 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::get (const QCString & n) const [inline]
Definition at line 7297 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
highlight() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::highlight () const [inline], [private]
Definition at line 7314 of file context.cpp.
{ return "namespaces"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::highlight () const [inline], [private]
Definition at line 7314 of file context.cpp.
{ return "namespaces"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
macros() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::macros () const [inline], [private]
Definition at line 7308 of file context.cpp.
{ return FALSE; }
References FALSE.
macros() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::macros () const [inline], [private]
Definition at line 7308 of file context.cpp.
{ return FALSE; }
References FALSE.
properties() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::properties () const [inline], [private]
Definition at line 7309 of file context.cpp.
{ return FALSE; }
References FALSE.
properties() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::properties () const [inline], [private]
Definition at line 7309 of file context.cpp.
{ return FALSE; }
References FALSE.
related() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::related () const [inline], [private]
Definition at line 7311 of file context.cpp.
{ return FALSE; }
References FALSE.
related() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::related () const [inline], [private]
Definition at line 7311 of file context.cpp.
{ return FALSE; }
References FALSE.
relPath() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::relPath () const [inline], [private]
Definition at line 7313 of file context.cpp.
{ return ""; }
relPath() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::relPath () const [inline], [private]
Definition at line 7313 of file context.cpp.
{ return ""; }
subhighlight() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::subhighlight () const [inline], [private]
Definition at line 7315 of file context.cpp.
{ return "namespacemembers"; }
subhighlight() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::subhighlight () const [inline], [private]
Definition at line 7315 of file context.cpp.
{ return "namespacemembers"; }
title() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::title () const [inline], [private]
Definition at line 7316 of file context.cpp.
{ return theTranslator->trNamespaceMembers(); }
References theTranslator, and Translator::trNamespaceMembers().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::title () const [inline], [private]
Definition at line 7316 of file context.cpp.
{ return theTranslator->trNamespaceMembers(); }
References theTranslator, and Translator::trNamespaceMembers().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
typedefs() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::typedefs () const [inline], [private]
Definition at line 7305 of file context.cpp.
{ return m_typedefs.get(this); }
References m_typedefs.
typedefs() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::typedefs () const [inline], [private]
Definition at line 7305 of file context.cpp.
{ return m_typedefs.get(this); }
variables() [1/2]
TemplateVariant NamespaceMembersIndexContext::Private::variables () const [inline], [private]
Definition at line 7304 of file context.cpp.
{ return m_variables.get(this); }
References m_variables.
variables() [2/2]
TemplateVariant NamespaceMembersIndexContext::Private::variables () const [inline], [private]
Definition at line 7304 of file context.cpp.
{ return m_variables.get(this); }
Member Data Documentation
m_all
CachedItem< TemplateVariant, Private, &Private::createAll > NamespaceMembersIndexContext::Private::m_all [private]
Definition at line 7348 of file context.cpp.
Referenced by all().
m_enums
CachedItem< TemplateVariant, Private, &Private::createEnums > NamespaceMembersIndexContext::Private::m_enums [private]
Definition at line 7352 of file context.cpp.
Referenced by enums().
m_enumValues
CachedItem< TemplateVariant, Private, &Private::createEnumValues > NamespaceMembersIndexContext::Private::m_enumValues [private]
Definition at line 7353 of file context.cpp.
Referenced by enumValues().
m_functions
CachedItem< TemplateVariant, Private, &Private::createFunctions > NamespaceMembersIndexContext::Private::m_functions [private]
Definition at line 7349 of file context.cpp.
Referenced by functions().
m_typedefs
CachedItem< TemplateVariant, Private, &Private::createTypedefs > NamespaceMembersIndexContext::Private::m_typedefs [private]
Definition at line 7351 of file context.cpp.
Referenced by typedefs().
m_variables
CachedItem< TemplateVariant, Private, &Private::createVariables > NamespaceMembersIndexContext::Private::m_variables [private]
Definition at line 7350 of file context.cpp.
Referenced by variables().
s_inst
const PropertyMap< NamespaceMembersIndexContext::Private > NamespaceMembersIndexContext::Private::s_inst [static], [private]
Initial value:
{
  { "all", &Private::all },
  { "functions", &Private::functions },
  { "variables", &Private::variables },
  { "typedefs", &Private::typedefs },
  { "enums", &Private::enums },
  { "enumValues", &Private::enumValues },
  { "macros", &Private::macros },
  { "properties", &Private::properties },
  { "events", &Private::events },
  { "related", &Private::related },
  { "fileName", &Private::fileName },
  { "relPath", &Private::relPath },
  { "highlight", &Private::highlight },
  { "subhighlight",&Private::subhighlight },
  { "title", &Private::title }
}
Definition at line 7354 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp