GrowBuf Class Reference
#include <growbuf.h>
Public Member Functions
GrowBuf ()
GrowBuf (size_t initialSize)
~GrowBuf ()
GrowBuf (const GrowBuf &other)
GrowBuf & operator= (const GrowBuf &other)
GrowBuf (GrowBuf &&other)
GrowBuf & operator= (GrowBuf &&other)
void reserve (size_t size)
void clear ()
void addChar (char c)
void addStr (const QCString &s)
void addStr (const std::string &s)
void addStr (const char *s)
void addStr (const char *s, size_t n)
void addInt (const char *fmt, int value)
char * get ()
const char * get () const
size_t getPos () const
void setPos (size_t newPos)
char at (size_t i) const
bool empty () const
GrowBuf ()
GrowBuf (size_t initialSize)
~GrowBuf ()
GrowBuf (const GrowBuf &other)
GrowBuf & operator= (const GrowBuf &other)
GrowBuf (GrowBuf &&other)
GrowBuf & operator= (GrowBuf &&other)
void reserve (size_t size)
void clear ()
void addChar (char c)
void addStr (const QCString &s)
void addStr (const std::string &s)
void addStr (const char *s)
void addStr (const char *s, size_t n)
void addInt (const char *fmt, int value)
char * get ()
const char * get () const
size_t getPos () const
void setPos (size_t newPos)
char at (size_t i) const
bool empty () const
Private Attributes
char * m_str
size_t m_pos
size_t m_len
Detailed Description
Class representing a string buffer optimised for growing.
Definition at line 27 of file growbuf.h.
Constructor & Destructor Documentation
GrowBuf() [1/8]
GrowBuf::GrowBuf () [inline]
Definition at line 30 of file growbuf.h.
: m_str(0), m_pos(0), m_len(0) {}
GrowBuf() [2/8]
GrowBuf::GrowBuf (size_t initialSize) [inline]
Definition at line 31 of file growbuf.h.
: m_pos(0), m_len(initialSize) { m_str=static_cast<char*>(malloc(m_len)); }
References m_len, and m_str.
 GrowBuf() [1/2]
GrowBuf::~GrowBuf () [inline]
Definition at line 32 of file growbuf.h.
{ free(m_str); }
References m_str.
GrowBuf() [3/8]
GrowBuf::GrowBuf (const GrowBuf & other) [inline]
Definition at line 33 of file growbuf.h.
    {
      m_len = other.m_len;
      m_pos = other.m_pos;
      m_str = static_cast<char*>(malloc(m_len));
      memcpy(m_str,other.m_str,m_len);
    }
References m_len, m_pos, and m_str.
GrowBuf() [4/8]
GrowBuf::GrowBuf (GrowBuf && other) [inline]
Definition at line 52 of file growbuf.h.
      : m_str(std::exchange(other.m_str,static_cast<char*>(0)))
      , m_pos(std::exchange(other.m_pos,0))
      , m_len(std::exchange(other.m_len,0))
    {
    }
GrowBuf() [5/8]
GrowBuf::GrowBuf () [inline]
Definition at line 30 of file growbuf.h.
: m_str(0), m_pos(0), m_len(0) {}
GrowBuf() [6/8]
GrowBuf::GrowBuf (size_t initialSize) [inline]
Definition at line 31 of file growbuf.h.
: m_pos(0), m_len(initialSize) { m_str=static_cast<char*>(malloc(m_len)); }
References m_len, and m_str.
 GrowBuf() [2/2]
GrowBuf::~GrowBuf () [inline]
Definition at line 32 of file growbuf.h.
{ free(m_str); }
References m_str.
GrowBuf() [7/8]
GrowBuf::GrowBuf (const GrowBuf & other) [inline]
Definition at line 33 of file growbuf.h.
    {
      m_len = other.m_len;
      m_pos = other.m_pos;
      m_str = static_cast<char*>(malloc(m_len));
      memcpy(m_str,other.m_str,m_len);
    }
References m_len, m_pos, and m_str.
GrowBuf() [8/8]
GrowBuf::GrowBuf (GrowBuf && other) [inline]
Definition at line 52 of file growbuf.h.
      : m_str(std::exchange(other.m_str,static_cast<char*>(0)))
      , m_pos(std::exchange(other.m_pos,0))
      , m_len(std::exchange(other.m_len,0))
    {
    }
Member Function Documentation
addChar() [1/2]
void GrowBuf::addChar (char c) [inline]
Definition at line 69 of file growbuf.h.
                          { if (m_pos>=m_len) { m_len+=GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                        m_str[m_pos++]=c;
                      }
References c, GROW_AMOUNT, m_len, m_pos, and m_str.
Referenced by SearchIndexExternal::addWord(), convertCharEntitiesToUTF8(), convertToDocBook(), convertToHtml(), convertToId(), convertToJSString(), convertToPSString(), convertToXML(), Markdown::detab(), escapeCharsInString(), escapeDoubleQuotes(), escapeSpecialChars(), filter2008VhdlComment(), filterId(), HtmlDocVisitor::filterQuotedCdataAttr(), formatDateTime(), Markdown::process(), Markdown::processBlocks(), DocParser::processCopyDoc(), Markdown::processQuotations(), Markdown::processSpecialCommand(), replaceVariables(), SearchIndexExternal::write(), Markdown::writeFencedCodeBlock(), and Markdown::writeOneLineHeaderOrRuler().
addChar() [2/2]
void GrowBuf::addChar (char c) [inline]
Definition at line 69 of file growbuf.h.
                          { if (m_pos>=m_len) { m_len+=GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                        m_str[m_pos++]=c;
                      }
References c, GROW_AMOUNT, m_len, m_pos, and m_str.
addInt() [1/2]
void GrowBuf::addInt (const char * fmt, int value) [inline]
Definition at line 109 of file growbuf.h.
                                           {
                      char tmp[50];
                      snprintf(tmp,50,fmt,value);
                      addStr(tmp);
    }
References addStr(), and fmt.
Referenced by formatDateTime().
addInt() [2/2]
void GrowBuf::addInt (const char * fmt, int value) [inline]
Definition at line 109 of file growbuf.h.
                                           {
                      char tmp[50];
                      snprintf(tmp,50,fmt,value);
                      addStr(tmp);
    }
References addStr(), and fmt.
addStr() [1/8]
void GrowBuf::addStr (const char * s) [inline]
Definition at line 90 of file growbuf.h.
                               {
                        if (s)
                        {
                          size_t l=strlen(s);
                          if (m_pos+l>=m_len) { m_len+=l+GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                          strcpy(&m_str[m_pos],s);
                          m_pos+=l;
                        }
                      }
References GROW_AMOUNT, m_len, m_pos, m_str, and s.
addStr() [2/8]
void GrowBuf::addStr (const char * s) [inline]
Definition at line 90 of file growbuf.h.
                               {
                        if (s)
                        {
                          size_t l=strlen(s);
                          if (m_pos+l>=m_len) { m_len+=l+GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                          strcpy(&m_str[m_pos],s);
                          m_pos+=l;
                        }
                      }
References GROW_AMOUNT, m_len, m_pos, m_str, and s.
addStr() [3/8]
void GrowBuf::addStr (const char * s, size_t n) [inline]
Definition at line 99 of file growbuf.h.
                                        {
                        if (s)
                        {
                          size_t l=strlen(s);
                          if (n<l) l=n;
                          if (m_pos+l>=m_len) { m_len+=l+GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                          strncpy(&m_str[m_pos],s,n);
                          m_pos+=l;
                        }
                      }
References GROW_AMOUNT, m_len, m_pos, m_str, n, and s.
addStr() [4/8]
void GrowBuf::addStr (const char * s, size_t n) [inline]
Definition at line 99 of file growbuf.h.
                                        {
                        if (s)
                        {
                          size_t l=strlen(s);
                          if (n<l) l=n;
                          if (m_pos+l>=m_len) { m_len+=l+GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                          strncpy(&m_str[m_pos],s,n);
                          m_pos+=l;
                        }
                      }
References GROW_AMOUNT, m_len, m_pos, m_str, n, and s.
addStr() [5/8]
void GrowBuf::addStr (const QCString & s) [inline]
Definition at line 72 of file growbuf.h.
                                   {
                        if (!s.isEmpty())
                        {
                          size_t l=s.length();
                          if (m_pos+l>=m_len) { m_len+=l+GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                          strcpy(&m_str[m_pos],s.data());
                          m_pos+=l;
                        }
                      }
References gdFont::data, GROW_AMOUNT, m_len, m_pos, m_str, and s.
Referenced by addInt(), Markdown::addStrEscapeUtf8Nbsp(), SearchIndexExternal::addWord(), convertCharEntitiesToUTF8(), convertToDocBook(), convertToHtml(), convertToId(), convertToJSString(), convertToPSString(), convertToXML(), Markdown::detab(), escapeCharsInString(), filterId(), HtmlDocVisitor::filterQuotedCdataAttr(), formatDateTime(), Markdown::processBlocks(), Markdown::processCodeSpan(), DocParser::processCopyDoc(), Markdown::processEmphasis1(), Markdown::processEmphasis2(), Markdown::processEmphasis3(), Markdown::processHtmlTagWrite(), Markdown::processInline(), Markdown::processLink(), Markdown::processNmdash(), Markdown::processQuotations(), Markdown::processQuoted(), Markdown::processSpecialCommand(), replaceVariables(), Markdown::writeBlockQuote(), Markdown::writeCodeBlock(), Markdown::writeFencedCodeBlock(), Markdown::writeMarkdownImage(), Markdown::writeOneLineHeaderOrRuler(), and Markdown::writeTableBlock().
addStr() [6/8]
void GrowBuf::addStr (const QCString & s) [inline]
Definition at line 72 of file growbuf.h.
                                   {
                        if (!s.isEmpty())
                        {
                          size_t l=s.length();
                          if (m_pos+l>=m_len) { m_len+=l+GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                          strcpy(&m_str[m_pos],s.data());
                          m_pos+=l;
                        }
                      }
References gdFont::data, GROW_AMOUNT, m_len, m_pos, m_str, and s.
addStr() [7/8]
void GrowBuf::addStr (const std::string & s) [inline]
Definition at line 81 of file growbuf.h.
                                    {
                        if (!s.empty())
                        {
                          size_t l=s.length();
                          if (m_pos+l>=m_len) { m_len+=l+GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                          strcpy(&m_str[m_pos],s.c_str());
                          m_pos+=l;
                        }
                      }
References GROW_AMOUNT, m_len, m_pos, m_str, and s.
addStr() [8/8]
void GrowBuf::addStr (const std::string & s) [inline]
Definition at line 81 of file growbuf.h.
                                    {
                        if (!s.empty())
                        {
                          size_t l=s.length();
                          if (m_pos+l>=m_len) { m_len+=l+GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                          strcpy(&m_str[m_pos],s.c_str());
                          m_pos+=l;
                        }
                      }
References GROW_AMOUNT, m_len, m_pos, m_str, and s.
at() [1/2]
char GrowBuf::at (size_t i) const [inline]
Definition at line 118 of file growbuf.h.
{ return m_str[i]; }
References m_str.
Referenced by filter2008VhdlComment().
at() [2/2]
char GrowBuf::at (size_t i) const [inline]
Definition at line 118 of file growbuf.h.
{ return m_str[i]; }
References m_str.
clear() [1/2]
void GrowBuf::clear () [inline]
Definition at line 68 of file growbuf.h.
{ m_pos=0; }
References m_pos.
Referenced by Markdown::detab(), filterId(), Markdown::process(), Markdown::processBlocks(), and Markdown::processQuotations().
clear() [2/2]
void GrowBuf::clear () [inline]
Definition at line 68 of file growbuf.h.
{ m_pos=0; }
References m_pos.
empty() [1/2]
bool GrowBuf::empty () const [inline]
Definition at line 119 of file growbuf.h.
{ return m_pos==0; }
References m_pos.
empty() [2/2]
bool GrowBuf::empty () const [inline]
Definition at line 119 of file growbuf.h.
{ return m_pos==0; }
References m_pos.
get() [1/4]
char * GrowBuf::get () [inline]
Definition at line 114 of file growbuf.h.
{ return m_str; }
References m_str.
Referenced by convertCharEntitiesToUTF8(), convertToDocBook(), convertToHtml(), convertToId(), convertToJSString(), convertToPSString(), convertToXML(), Markdown::detab(), escapeCharsInString(), escapeDoubleQuotes(), escapeSpecialChars(), filter2008VhdlComment(), filterId(), HtmlDocVisitor::filterQuotedCdataAttr(), formatDateTime(), Markdown::process(), Markdown::processBlocks(), DocParser::processCopyDoc(), Markdown::processQuotations(), replaceVariables(), and SearchIndexExternal::write().
get() [2/4]
char * GrowBuf::get () [inline]
Definition at line 114 of file growbuf.h.
{ return m_str; }
References m_str.
get() [3/4]
const char * GrowBuf::get () const [inline]
Definition at line 115 of file growbuf.h.
{ return m_str; }
References m_str.
get() [4/4]
const char * GrowBuf::get () const [inline]
Definition at line 115 of file growbuf.h.
{ return m_str; }
References m_str.
getPos() [1/2]
size_t GrowBuf::getPos () const [inline]
Definition at line 116 of file growbuf.h.
{ return m_pos; }
References m_pos.
Referenced by SearchIndexExternal::addWord(), filter2008VhdlComment(), and DocParser::processCopyDoc().
getPos() [2/2]
size_t GrowBuf::getPos () const [inline]
Definition at line 116 of file growbuf.h.
{ return m_pos; }
References m_pos.
operator=() [1/4]
GrowBuf & GrowBuf::operator= (const GrowBuf & other) [inline]
Definition at line 40 of file growbuf.h.
    {
      if (this!=&other)
      {
        free(m_str);
        m_len = other.m_len;
        m_pos = other.m_pos;
        m_str = static_cast<char*>(malloc(m_len));
        memcpy(m_str,other.m_str,m_len);
      }
      return *this;
    }
References m_len, m_pos, and m_str.
operator=() [2/4]
GrowBuf & GrowBuf::operator= (const GrowBuf & other) [inline]
Definition at line 40 of file growbuf.h.
    {
      if (this!=&other)
      {
        free(m_str);
        m_len = other.m_len;
        m_pos = other.m_pos;
        m_str = static_cast<char*>(malloc(m_len));
        memcpy(m_str,other.m_str,m_len);
      }
      return *this;
    }
References m_len, m_pos, and m_str.
operator=() [3/4]
GrowBuf & GrowBuf::operator= (GrowBuf && other) [inline]
Definition at line 58 of file growbuf.h.
    {
      if (this==&other)
        return *this;
      m_len = std::exchange(other.m_len,0);
      m_pos = std::exchange(other.m_pos,0);
      m_str = std::exchange(other.m_str,static_cast<char*>(0));
      return *this;
    }
References m_len, m_pos, and m_str.
operator=() [4/4]
GrowBuf & GrowBuf::operator= (GrowBuf && other) [inline]
Definition at line 58 of file growbuf.h.
    {
      if (this==&other)
        return *this;
      m_len = std::exchange(other.m_len,0);
      m_pos = std::exchange(other.m_pos,0);
      m_str = std::exchange(other.m_str,static_cast<char*>(0));
      return *this;
    }
References m_len, m_pos, and m_str.
reserve() [1/2]
void GrowBuf::reserve (size_t size) [inline]
Definition at line 67 of file growbuf.h.
{ if (m_len<size) { m_len = size; m_str = static_cast<char*>(realloc(m_str,m_len)); } }
References m_len, m_str, and size.
Referenced by Markdown::detab().
reserve() [2/2]
void GrowBuf::reserve (size_t size) [inline]
Definition at line 67 of file growbuf.h.
{ if (m_len<size) { m_len = size; m_str = static_cast<char*>(realloc(m_str,m_len)); } }
References m_len, m_str, and size.
setPos() [1/2]
void GrowBuf::setPos (size_t newPos) [inline]
Definition at line 117 of file growbuf.h.
{ m_pos = newPos; }
References m_pos.
Referenced by filter2008VhdlComment().
setPos() [2/2]
void GrowBuf::setPos (size_t newPos) [inline]
Definition at line 117 of file growbuf.h.
{ m_pos = newPos; }
References m_pos.
Member Data Documentation
m_len
size_t GrowBuf::m_len [private]
Definition at line 123 of file growbuf.h.
Referenced by addChar(), addStr(), GrowBuf(), operator=(), and reserve().
m_pos
size_t GrowBuf::m_pos [private]
Definition at line 122 of file growbuf.h.
Referenced by addChar(), addStr(), clear(), empty(), getPos(), GrowBuf(), operator=(), and setPos().
m_str
char * GrowBuf::m_str [private]
Definition at line 121 of file growbuf.h.
Referenced by addChar(), addStr(), at(), get(), GrowBuf(), operator=(), reserve(), and ~GrowBuf().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/growbuf.h
doxygen/src/growbuf.h