TemplateListIntf Class Reference
Abstract read-only interface for a context value of type list.
#include <template.h>
Classes
class ConstIterator
Abstract interface for a iterator of a list.
Public Types
using ConstIteratorPtr = std::unique_ptr< ConstIterator >
using ConstIteratorPtr = std::unique_ptr< ConstIterator >
Public Member Functions
virtual ~TemplateListIntf ()=default
virtual size_t count () const =0
virtual TemplateVariant at (size_t index) const =0
virtual TemplateListIntf::ConstIteratorPtr createIterator () const =0
virtual ~TemplateListIntf ()=default
virtual size_t count () const =0
virtual TemplateVariant at (size_t index) const =0
virtual TemplateListIntf::ConstIteratorPtr createIterator () const =0
Detailed Description
Abstract read-only interface for a context value of type list.
Note
The values of the list are TemplateVariants.
Definition at line 280 of file template.h.
Member Typedef Documentation
ConstIteratorPtr [1/2]
using TemplateListIntf::ConstIteratorPtr = std::unique_ptr<ConstIterator>
Definition at line 304 of file template.h.
ConstIteratorPtr [2/2]
using TemplateListIntf::ConstIteratorPtr = std::unique_ptr<ConstIterator>
Definition at line 304 of file template.h.
Constructor & Destructor Documentation
 TemplateListIntf() [1/2]
virtual TemplateListIntf::~TemplateListIntf () [virtual], [default]
Destroys the list
 TemplateListIntf() [2/2]
virtual TemplateListIntf::~TemplateListIntf () [virtual], [default]
Destroys the list
Member Function Documentation
at() [1/2]
virtual TemplateVariant TemplateListIntf::at (size_t index) const [pure virtual]
Returns the element at index position index.
Implemented in GenericNodeListContext, UsedFilesContext, IncludeInfoListContext, ClassListContext, ClassInheritanceContext, NestingContext, ConceptListContext, NamespaceListContext, DirListContext, FileListContext, PageListContext, ModuleListContext, ExampleListContext, InheritanceListContext, MemberListContext, MemberGroupListContext, InheritedMemberInfoListContext, AllMembersListContext, ArgumentListContext, SymbolListContext, SymbolGroupListContext, SymbolIndicesContext, SearchIndicesContext, TemplateList, TemplateImmutableList, GenericNodeListContext, UsedFilesContext, IncludeInfoListContext, ClassListContext, ClassInheritanceContext, NestingContext, ConceptListContext, NamespaceListContext, DirListContext, FileListContext, PageListContext, ModuleListContext, ExampleListContext, InheritanceListContext, MemberListContext, MemberGroupListContext, InheritedMemberInfoListContext, AllMembersListContext, ArgumentListContext, SymbolListContext, SymbolGroupListContext, SymbolIndicesContext, SearchIndicesContext, TemplateList, and TemplateImmutableList.
at() [2/2]
virtual TemplateVariant TemplateListIntf::at (size_t index) const [pure virtual]
Returns the element at index position index.
Implemented in GenericNodeListContext, UsedFilesContext, IncludeInfoListContext, ClassListContext, ClassInheritanceContext, NestingContext, ConceptListContext, NamespaceListContext, DirListContext, FileListContext, PageListContext, ModuleListContext, ExampleListContext, InheritanceListContext, MemberListContext, MemberGroupListContext, InheritedMemberInfoListContext, AllMembersListContext, ArgumentListContext, SymbolListContext, SymbolGroupListContext, SymbolIndicesContext, SearchIndicesContext, TemplateList, TemplateImmutableList, GenericNodeListContext, UsedFilesContext, IncludeInfoListContext, ClassListContext, ClassInheritanceContext, NestingContext, ConceptListContext, NamespaceListContext, DirListContext, FileListContext, PageListContext, ModuleListContext, ExampleListContext, InheritanceListContext, MemberListContext, MemberGroupListContext, InheritedMemberInfoListContext, AllMembersListContext, ArgumentListContext, SymbolListContext, SymbolGroupListContext, SymbolIndicesContext, SearchIndicesContext, TemplateList, and TemplateImmutableList.
count() [1/2]
virtual size_t TemplateListIntf::count () const [pure virtual]
Returns the number of elements in the list
Implemented in GenericNodeListContext, UsedFilesContext, IncludeInfoListContext, ClassListContext, ClassInheritanceContext, NestingContext, ConceptListContext, NamespaceListContext, DirListContext, FileListContext, PageListContext, ModuleListContext, ExampleListContext, InheritanceListContext, MemberListContext, MemberGroupListContext, InheritedMemberInfoListContext, AllMembersListContext, ArgumentListContext, SymbolListContext, SymbolGroupListContext, SymbolIndicesContext, SearchIndicesContext, TemplateList, TemplateImmutableList, GenericNodeListContext, UsedFilesContext, IncludeInfoListContext, ClassListContext, ClassInheritanceContext, NestingContext, ConceptListContext, NamespaceListContext, DirListContext, FileListContext, PageListContext, ModuleListContext, ExampleListContext, InheritanceListContext, MemberListContext, MemberGroupListContext, InheritedMemberInfoListContext, AllMembersListContext, ArgumentListContext, SymbolListContext, SymbolGroupListContext, SymbolIndicesContext, SearchIndicesContext, TemplateList, and TemplateImmutableList.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t TemplateListIntf::count () const [pure virtual]
Returns the number of elements in the list
Implemented in GenericNodeListContext, UsedFilesContext, IncludeInfoListContext, ClassListContext, ClassInheritanceContext, NestingContext, ConceptListContext, NamespaceListContext, DirListContext, FileListContext, PageListContext, ModuleListContext, ExampleListContext, InheritanceListContext, MemberListContext, MemberGroupListContext, InheritedMemberInfoListContext, AllMembersListContext, ArgumentListContext, SymbolListContext, SymbolGroupListContext, SymbolIndicesContext, SearchIndicesContext, TemplateList, TemplateImmutableList, GenericNodeListContext, UsedFilesContext, IncludeInfoListContext, ClassListContext, ClassInheritanceContext, NestingContext, ConceptListContext, NamespaceListContext, DirListContext, FileListContext, PageListContext, ModuleListContext, ExampleListContext, InheritanceListContext, MemberListContext, MemberGroupListContext, InheritedMemberInfoListContext, AllMembersListContext, ArgumentListContext, SymbolListContext, SymbolGroupListContext, SymbolIndicesContext, SearchIndicesContext, TemplateList, and TemplateImmutableList.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
virtual TemplateListIntf::ConstIteratorPtr TemplateListIntf::createIterator () const [pure virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implemented in GenericNodeListContext, UsedFilesContext, IncludeInfoListContext, ClassListContext, ClassInheritanceContext, NestingContext, ConceptListContext, NamespaceListContext, DirListContext, FileListContext, PageListContext, ModuleListContext, ExampleListContext, InheritanceListContext, MemberListContext, MemberGroupListContext, InheritedMemberInfoListContext, AllMembersListContext, ArgumentListContext, SymbolListContext, SymbolGroupListContext, SymbolIndicesContext, SearchIndicesContext, TemplateList, TemplateImmutableList, GenericNodeListContext, UsedFilesContext, IncludeInfoListContext, ClassListContext, ClassInheritanceContext, NestingContext, ConceptListContext, NamespaceListContext, DirListContext, FileListContext, PageListContext, ModuleListContext, ExampleListContext, InheritanceListContext, MemberListContext, MemberGroupListContext, InheritedMemberInfoListContext, AllMembersListContext, ArgumentListContext, SymbolListContext, SymbolGroupListContext, SymbolIndicesContext, SearchIndicesContext, TemplateList, and TemplateImmutableList.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr TemplateListIntf::createIterator () const [pure virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implemented in GenericNodeListContext, UsedFilesContext, IncludeInfoListContext, ClassListContext, ClassInheritanceContext, NestingContext, ConceptListContext, NamespaceListContext, DirListContext, FileListContext, PageListContext, ModuleListContext, ExampleListContext, InheritanceListContext, MemberListContext, MemberGroupListContext, InheritedMemberInfoListContext, AllMembersListContext, ArgumentListContext, SymbolListContext, SymbolGroupListContext, SymbolIndicesContext, SearchIndicesContext, TemplateList, TemplateImmutableList, GenericNodeListContext, UsedFilesContext, IncludeInfoListContext, ClassListContext, ClassInheritanceContext, NestingContext, ConceptListContext, NamespaceListContext, DirListContext, FileListContext, PageListContext, ModuleListContext, ExampleListContext, InheritanceListContext, MemberListContext, MemberGroupListContext, InheritedMemberInfoListContext, AllMembersListContext, ArgumentListContext, SymbolListContext, SymbolGroupListContext, SymbolIndicesContext, SearchIndicesContext, TemplateList, and TemplateImmutableList.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.h
doxygen/src/template.h