TranslatorArmenian Class Reference
#include <translator_am.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
Additional Inherited Members
Detailed Description
Definition at line 25 of file translator_am.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorArmenian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 40 of file translator_am.h.
    {
      return "0x42b Armenian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorArmenian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 40 of file translator_am.h.
    {
      return "0x42b Armenian";
    }
idLanguage() [1/2]
virtual QCString TranslatorArmenian::idLanguage () [inline], [virtual]
Used for identification of the language.
Implements Translator.
Definition at line 29 of file translator_am.h.
    { return "armenian"; }
idLanguage() [2/2]
virtual QCString TranslatorArmenian::idLanguage () [inline], [virtual]
Used for identification of the language.
Implements Translator.
Definition at line 29 of file translator_am.h.
    { return "armenian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorArmenian::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 33 of file translator_am.h.
    {
      return "\\usepackage[latin]{armtex}\n"
             "\\usepackage[armscii8]{inputenc}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorArmenian::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 33 of file translator_am.h.
    {
      return "\\usepackage[latin]{armtex}\n"
             "\\usepackage[armscii8]{inputenc}\n";
    }
trAll() [1/2]
virtual QCString TranslatorArmenian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1349 of file translator_am.h.
    {
      return "";
    }
trAll() [2/2]
virtual QCString TranslatorArmenian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1349 of file translator_am.h.
    {
      return "";
    }
trAttention() [1/2]
virtual QCString TranslatorArmenian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 936 of file translator_am.h.
    {
      return "";
    }
trAttention() [2/2]
virtual QCString TranslatorArmenian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 936 of file translator_am.h.
    {
      return "";
    }
trAuthor() [1/2]
virtual QCString TranslatorArmenian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1220 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorArmenian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1220 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorArmenian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1100 of file translator_am.h.
    {
      return "";
    }
trBug() [2/2]
virtual QCString TranslatorArmenian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1100 of file translator_am.h.
    {
      return "";
    }
trBugList() [1/2]
virtual QCString TranslatorArmenian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1105 of file translator_am.h.
    {
      return " ";
    }
trBugList() [2/2]
virtual QCString TranslatorArmenian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1105 of file translator_am.h.
    {
      return " ";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorArmenian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1469 of file translator_am.h.
    {
      return " .";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorArmenian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1469 of file translator_am.h.
    {
      return " .";
    }
trCallGraph() [1/2]
virtual QCString TranslatorArmenian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1354 of file translator_am.h.
    {
      return " .";
    }
trCallGraph() [2/2]
virtual QCString TranslatorArmenian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1354 of file translator_am.h.
    {
      return " .";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorArmenian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1799 of file translator_am.h.
    { return ""; }
trCiteReferences() [2/2]
virtual QCString TranslatorArmenian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1799 of file translator_am.h.
    { return ""; }
trClass() [1/2]
virtual QCString TranslatorArmenian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1133 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        QCString result((first_capital ? " " : " "));
        return result;
      }
      else
      {
        QCString result((first_capital ? "" : ""));
        if(!singular) result+="";
        return result;
      }
    }
References Config_getBool.
trClass() [2/2]
virtual QCString TranslatorArmenian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1133 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        QCString result((first_capital ? " " : " "));
        return result;
      }
      else
      {
        QCString result((first_capital ? "" : ""));
        if(!singular) result+="";
        return result;
      }
    }
References Config_getBool.
trClassDiagram() [1/2]
virtual QCString TranslatorArmenian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 471 of file translator_am.h.
    {
      return clName+QCString(" - .");
    }
trClassDiagram() [2/2]
virtual QCString TranslatorArmenian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 471 of file translator_am.h.
    {
      return clName+QCString(" - .");
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorArmenian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 343 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorArmenian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 343 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorArmenian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1063 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorArmenian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1063 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorArmenian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 142 of file translator_am.h.
    { return " "; }
trClassHierarchy() [2/2]
virtual QCString TranslatorArmenian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 142 of file translator_am.h.
    { return " "; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorArmenian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 202 of file translator_am.h.
    { return " , "
             " , .";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorArmenian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 202 of file translator_am.h.
    { return " , "
             " , .";
    }
trCode() [1/2]
virtual QCString TranslatorArmenian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 833 of file translator_am.h.
    {
      return " ";
    }
trCode() [2/2]
virtual QCString TranslatorArmenian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 833 of file translator_am.h.
    {
      return " ";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorArmenian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 788 of file translator_am.h.
    {
      return clName+"- .";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorArmenian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 788 of file translator_am.h.
    {
      return clName+"- .";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorArmenian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 316 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorArmenian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 316 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorArmenian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1523 of file translator_am.h.
    { return " "; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorArmenian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1523 of file translator_am.h.
    { return " "; }
trCompoundList() [1/2]
virtual QCString TranslatorArmenian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 146 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorArmenian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 146 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorArmenian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 217 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ` .";
      }
      else
      {
        return ", , "
                " ` .";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorArmenian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 217 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ` .";
      }
      else
      {
        return ", , "
                " ` .";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorArmenian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1497 of file translator_am.h.
    { return " ` ."; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorArmenian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1497 of file translator_am.h.
    { return " ` ."; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorArmenian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1489 of file translator_am.h.
    { return " "; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorArmenian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1489 of file translator_am.h.
    { return " "; }
trCompoundMembers() [1/2]
virtual QCString TranslatorArmenian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 163 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorArmenian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 163 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorArmenian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 231 of file translator_am.h.
    {
        QCString result=" ";
        if(!extractAll) result+=" ";
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result+=" ";
        else
          result+=" ";
        result+="`";
        result+=" ";
        if(!extractAll)
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result+="/ .";
          else
            result+=" .";
        }
        else
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result += "/, .";
          else
            result += ", .";
        }
        return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorArmenian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 231 of file translator_am.h.
    {
        QCString result=" ";
        if(!extractAll) result+=" ";
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result+=" ";
        else
          result+=" ";
        result+="`";
        result+=" ";
        if(!extractAll)
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result+="/ .";
          else
            result+=" .";
        }
        else
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result += "/, .";
          else
            result += ", .";
        }
        return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorArmenian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1501 of file translator_am.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ` ";
      if (!extractAll)
      {
        result+=" ";
      }
      else
      {
        result+=" , ";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorArmenian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1501 of file translator_am.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ` ";
      if (!extractAll)
      {
        result+=" ";
      }
      else
      {
        result+=" , ";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorArmenian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1493 of file translator_am.h.
    { return " "; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorArmenian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1493 of file translator_am.h.
    { return " "; }
trCompoundReference() [1/2]
virtual QCString TranslatorArmenian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 546 of file translator_am.h.
    {
      QCString result=clName;
      if (isTemplate)
      {
        switch(compType)
        {
          case ClassDef::Class: result+=" "; break;
          case ClassDef::Struct: result+=" "; break;
          case ClassDef::Union: result+=" "; break;
          case ClassDef::Interface: result+=" "; break;
          case ClassDef::Protocol: result+=" "; break;
          case ClassDef::Category: result+=" "; break;
          case ClassDef::Exception: result+=" "; break;
          default: break;
        }
        result+=" ";
      }
      else
      {
        switch(compType)
        {
          case ClassDef::Class: result+=" "; break;
          case ClassDef::Struct: result+=" "; break;
          case ClassDef::Union: result+=" "; break;
          case ClassDef::Interface: result+=" "; break;
          case ClassDef::Protocol: result+=" "; break;
          case ClassDef::Category: result+=" "; break;
          case ClassDef::Exception: result+=" "; break;
          default: break;
        }
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorArmenian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 546 of file translator_am.h.
    {
      QCString result=clName;
      if (isTemplate)
      {
        switch(compType)
        {
          case ClassDef::Class: result+=" "; break;
          case ClassDef::Struct: result+=" "; break;
          case ClassDef::Union: result+=" "; break;
          case ClassDef::Interface: result+=" "; break;
          case ClassDef::Protocol: result+=" "; break;
          case ClassDef::Category: result+=" "; break;
          case ClassDef::Exception: result+=" "; break;
          default: break;
        }
        result+=" ";
      }
      else
      {
        switch(compType)
        {
          case ClassDef::Class: result+=" "; break;
          case ClassDef::Struct: result+=" "; break;
          case ClassDef::Union: result+=" "; break;
          case ClassDef::Interface: result+=" "; break;
          case ClassDef::Protocol: result+=" "; break;
          case ClassDef::Category: result+=" "; break;
          case ClassDef::Exception: result+=" "; break;
          default: break;
        }
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorArmenian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1564 of file translator_am.h.
    {
      QCString result=clName;
      if (!isTemplate)
      {
        switch(compType)
        {
          case ClassDef::Class: result+=" "; break;
          case ClassDef::Struct: result+=" "; break;
          case ClassDef::Union: result+=" "; break;
          case ClassDef::Interface: result+=" "; break;
          case ClassDef::Protocol: result+=" "; break;
          case ClassDef::Category: result+=" "; break;
          case ClassDef::Exception: result+=" "; break;
          default: break;
        }
      }
      else
      {
        switch(compType)
        {
          case ClassDef::Class: result+=" "; break;
          case ClassDef::Struct: result+=" "; break;
          case ClassDef::Union: result+=" "; break;
          case ClassDef::Interface: result+=" "; break;
          case ClassDef::Protocol: result+=" "; break;
          case ClassDef::Category: result+=" "; break;
          case ClassDef::Exception: result+=" "; break;
          default: break;
        }
        result+=" ";
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorArmenian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1564 of file translator_am.h.
    {
      QCString result=clName;
      if (!isTemplate)
      {
        switch(compType)
        {
          case ClassDef::Class: result+=" "; break;
          case ClassDef::Struct: result+=" "; break;
          case ClassDef::Union: result+=" "; break;
          case ClassDef::Interface: result+=" "; break;
          case ClassDef::Protocol: result+=" "; break;
          case ClassDef::Category: result+=" "; break;
          case ClassDef::Exception: result+=" "; break;
          default: break;
        }
      }
      else
      {
        switch(compType)
        {
          case ClassDef::Class: result+=" "; break;
          case ClassDef::Struct: result+=" "; break;
          case ClassDef::Union: result+=" "; break;
          case ClassDef::Interface: result+=" "; break;
          case ClassDef::Protocol: result+=" "; break;
          case ClassDef::Category: result+=" "; break;
          case ClassDef::Exception: result+=" "; break;
          default: break;
        }
        result+=" ";
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorArmenian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 444 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorArmenian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 444 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorArmenian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 798 of file translator_am.h.
    {
      return "";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorArmenian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 798 of file translator_am.h.
    {
      return "";
    }
trCopyright() [1/2]
virtual QCString TranslatorArmenian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1803 of file translator_am.h.
    { return " "; }
trCopyright() [2/2]
virtual QCString TranslatorArmenian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1803 of file translator_am.h.
    { return " "; }
trDataTypes() [1/2]
virtual QCString TranslatorArmenian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1547 of file translator_am.h.
    { return " "; }
trDataTypes() [2/2]
virtual QCString TranslatorArmenian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1547 of file translator_am.h.
    { return " "; }
trDate() [1/2]
virtual QCString TranslatorArmenian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 485 of file translator_am.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorArmenian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 485 of file translator_am.h.
    { return ""; }
trDateTime() [1/2]
virtual QCString TranslatorArmenian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1758 of file translator_am.h.
    {
      static const char *days[] = { ",",",",",",",",
                                ",",",","," };
      static const char *months[] = { "","","","","","",
                                "","","","","","" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d ",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorArmenian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1758 of file translator_am.h.
    {
      static const char *days[] = { ",",",",",",",",
                                ",",",","," };
      static const char *months[] = { "","","","","","",
                                "","","","","","" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d ",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorArmenian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1776 of file translator_am.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorArmenian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1776 of file translator_am.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayPeriod() [1/2]
virtual QCString TranslatorArmenian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1788 of file translator_am.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorArmenian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1788 of file translator_am.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorArmenian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 765 of file translator_am.h.
    {
      return " @1 @0 :";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorArmenian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 765 of file translator_am.h.
    {
      return " @1 @0 :";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorArmenian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 130 of file translator_am.h.
    { return ""; }
trDefinedIn() [2/2]
virtual QCString TranslatorArmenian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 130 of file translator_am.h.
    { return ""; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorArmenian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 769 of file translator_am.h.
    {
      return " @0 :";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorArmenian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 769 of file translator_am.h.
    {
      return " @0 :";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorArmenian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 414 of file translator_am.h.
    { return ""; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorArmenian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 414 of file translator_am.h.
    { return ""; }
trDefines() [1/2]
virtual QCString TranslatorArmenian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 378 of file translator_am.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorArmenian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 378 of file translator_am.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorArmenian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1090 of file translator_am.h.
    {
      return "";
    }
trDefineValue() [2/2]
virtual QCString TranslatorArmenian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1090 of file translator_am.h.
    {
      return "";
    }
trDeprecated() [1/2]
virtual QCString TranslatorArmenian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 778 of file translator_am.h.
    {
      return " ";
    }
trDeprecated() [2/2]
virtual QCString TranslatorArmenian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 778 of file translator_am.h.
    {
      return " ";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorArmenian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1277 of file translator_am.h.
    {
      return " ";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorArmenian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1277 of file translator_am.h.
    {
      return " ";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorArmenian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 56 of file translator_am.h.
    { return " "; }
trDetailedDescription() [2/2]
virtual QCString TranslatorArmenian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 56 of file translator_am.h.
    { return " "; }
trDir() [1/2]
virtual QCString TranslatorArmenian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1444 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorArmenian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1444 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorArmenian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1807 of file translator_am.h.
    { return name + QCString("- :"); }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorArmenian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1807 of file translator_am.h.
    { return name + QCString("- :"); }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorArmenian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1426 of file translator_am.h.
    { return ""; }
trDirDocumentation() [2/2]
virtual QCString TranslatorArmenian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1426 of file translator_am.h.
    { return ""; }
trDirectories() [1/2]
virtual QCString TranslatorArmenian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1432 of file translator_am.h.
    { return ""; }
trDirectories() [2/2]
virtual QCString TranslatorArmenian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1432 of file translator_am.h.
    { return ""; }
trDirIndex() [1/2]
virtual QCString TranslatorArmenian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1420 of file translator_am.h.
    { return " "; }
trDirIndex() [2/2]
virtual QCString TranslatorArmenian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1420 of file translator_am.h.
    { return " "; }
trDirReference() [1/2]
virtual QCString TranslatorArmenian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1438 of file translator_am.h.
    { QCString result=dirName; result+=" "; return result; }
trDirReference() [2/2]
virtual QCString TranslatorArmenian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1438 of file translator_am.h.
    { QCString result=dirName; result+=" "; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorArmenian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1697 of file translator_am.h.
    {
      return QCString(name)+" ";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorArmenian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1697 of file translator_am.h.
    {
      return QCString(name)+" ";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorArmenian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 298 of file translator_am.h.
    { return " - "; }
trDocumentation() [2/2]
virtual QCString TranslatorArmenian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 298 of file translator_am.h.
    { return " - "; }
trEnumerations() [1/2]
virtual QCString TranslatorArmenian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 390 of file translator_am.h.
    { return ""; }
trEnumerations() [2/2]
virtual QCString TranslatorArmenian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 390 of file translator_am.h.
    { return ""; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorArmenian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 426 of file translator_am.h.
    { return " "; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorArmenian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 426 of file translator_am.h.
    { return " "; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorArmenian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1477 of file translator_am.h.
    { return ""; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorArmenian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1477 of file translator_am.h.
    { return ""; }
trEnumerationValues() [1/2]
virtual QCString TranslatorArmenian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 408 of file translator_am.h.
    { return ""; }
trEnumerationValues() [2/2]
virtual QCString TranslatorArmenian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 408 of file translator_am.h.
    { return ""; }
trEnumName() [1/2]
virtual QCString TranslatorArmenian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 122 of file translator_am.h.
    { return " "; }
trEnumName() [2/2]
virtual QCString TranslatorArmenian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 122 of file translator_am.h.
    { return " "; }
trEnumValue() [1/2]
virtual QCString TranslatorArmenian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 126 of file translator_am.h.
    { return " "; }
trEnumValue() [2/2]
virtual QCString TranslatorArmenian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 126 of file translator_am.h.
    { return " "; }
trEventDocumentation() [1/2]
virtual QCString TranslatorArmenian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1294 of file translator_am.h.
    {
      return " ";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorArmenian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1294 of file translator_am.h.
    {
      return " ";
    }
trEvents() [1/2]
virtual QCString TranslatorArmenian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1289 of file translator_am.h.
    {
      return "";
    }
trEvents() [2/2]
virtual QCString TranslatorArmenian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1289 of file translator_am.h.
    {
      return "";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorArmenian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 368 of file translator_am.h.
    { return ""; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorArmenian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 368 of file translator_am.h.
    { return ""; }
trExamples() [1/2]
virtual QCString TranslatorArmenian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 194 of file translator_am.h.
    { return ""; }
trExamples() [2/2]
virtual QCString TranslatorArmenian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 194 of file translator_am.h.
    { return ""; }
trExamplesDescription() [1/2]
virtual QCString TranslatorArmenian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 283 of file translator_am.h.
    { return " ."; }
trExamplesDescription() [2/2]
virtual QCString TranslatorArmenian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 283 of file translator_am.h.
    { return " ."; }
trExceptions() [1/2]
virtual QCString TranslatorArmenian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 501 of file translator_am.h.
    { return ""; }
trExceptions() [2/2]
virtual QCString TranslatorArmenian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 501 of file translator_am.h.
    { return ""; }
trFile() [1/2]
virtual QCString TranslatorArmenian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1152 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorArmenian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1152 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorArmenian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 362 of file translator_am.h.
    { return ""; }
trFileDocumentation() [2/2]
virtual QCString TranslatorArmenian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 362 of file translator_am.h.
    { return ""; }
trFileIn() [1/2]
virtual QCString TranslatorArmenian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1734 of file translator_am.h.
    {
      return " " + name + " ";
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorArmenian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1734 of file translator_am.h.
    {
      return " " + name + " ";
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorArmenian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 331 of file translator_am.h.
    { return ""; }
trFileIndex() [2/2]
virtual QCString TranslatorArmenian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 331 of file translator_am.h.
    { return ""; }
trFileList() [1/2]
virtual QCString TranslatorArmenian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 159 of file translator_am.h.
    { return " "; }
trFileList() [2/2]
virtual QCString TranslatorArmenian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 159 of file translator_am.h.
    { return " "; }
trFileListDescription() [1/2]
virtual QCString TranslatorArmenian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 208 of file translator_am.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ` :";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorArmenian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 208 of file translator_am.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ` :";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorArmenian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 177 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorArmenian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 177 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorArmenian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 259 of file translator_am.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , -, "
                " (typedef)";
      }
      else
      {
        result+=" ";
      }
      result+="`";
      result+=" ";
      if (extractAll)
        result+=", .";
      else
        result+=".";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorArmenian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 259 of file translator_am.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , -, "
                " (typedef)";
      }
      else
      {
        result+=" ";
      }
      result+="`";
      result+=" ";
      if (extractAll)
        result+=", .";
      else
        result+=".";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorArmenian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 584 of file translator_am.h.
    {
      return fileName+QCString(" ");
    }
trFileReference() [2/2]
virtual QCString TranslatorArmenian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 584 of file translator_am.h.
    {
      return fileName+QCString(" ");
    }
trFriends() [1/2]
virtual QCString TranslatorArmenian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 528 of file translator_am.h.
    { return ""; }
trFriends() [2/2]
virtual QCString TranslatorArmenian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 528 of file translator_am.h.
    { return ""; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorArmenian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 432 of file translator_am.h.
    { return ""; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorArmenian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 432 of file translator_am.h.
    { return ""; }
trFunctions() [1/2]
virtual QCString TranslatorArmenian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 396 of file translator_am.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorArmenian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 396 of file translator_am.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorArmenian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the documentation of a group before the list of links to documented files
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 462 of file translator_am.h.
    {
      QCString result=QCString(" ")+date;
      if (!projName.isEmpty()) result+=projName+" - ,";
      result+=" .";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorArmenian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the documentation of a group before the list of links to documented files
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 462 of file translator_am.h.
    {
      QCString result=QCString(" ")+date;
      if (!projName.isEmpty()) result+=projName+" - ,";
      result+=" .";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorArmenian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 115 of file translator_am.h.
    { QCString result=" , Doxygen- , ";
      if (!s.isEmpty()) result+=s+" :";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorArmenian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 115 of file translator_am.h.
    { QCString result=" , Doxygen- , ";
      if (!s.isEmpty()) result+=s+" :";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorArmenian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 505 of file translator_am.h.
    { return " "; }
trGeneratedBy() [2/2]
virtual QCString TranslatorArmenian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 505 of file translator_am.h.
    { return " "; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorArmenian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 722 of file translator_am.h.
    {
      QCString result = " ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" ";
      if (single) result+="."; else result+=".";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorArmenian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 722 of file translator_am.h.
    {
      QCString result = " ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" ";
      if (single) result+="."; else result+=".";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorArmenian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1646 of file translator_am.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" ";
      if (single) result+="."; else result+=".";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorArmenian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1646 of file translator_am.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" ";
      if (single) result+="."; else result+=".";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorArmenian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1207 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorArmenian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1207 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorArmenian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1709 of file translator_am.h.
    {
      return " ";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorArmenian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1709 of file translator_am.h.
    {
      return " ";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorArmenian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 808 of file translator_am.h.
    {
      return "' :";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorArmenian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 808 of file translator_am.h.
    {
      return "' :";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorArmenian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 841 of file translator_am.h.
    {
      return "' :";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorArmenian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 841 of file translator_am.h.
    {
      return "' :";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorArmenian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 803 of file translator_am.h.
    {
      return "' ";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorArmenian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 803 of file translator_am.h.
    {
      return "' ";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorArmenian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 845 of file translator_am.h.
    {
      return "' :";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorArmenian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 845 of file translator_am.h.
    {
      return "' :";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorArmenian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 837 of file translator_am.h.
    {
      return " :";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorArmenian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 837 of file translator_am.h.
    {
      return " :";
    }
trGroup() [1/2]
virtual QCString TranslatorArmenian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1174 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorArmenian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1174 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorArmenian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 310 of file translator_am.h.
    { return ""; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorArmenian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 310 of file translator_am.h.
    { return ""; }
trImplementedFromList() [1/2]
virtual QCString TranslatorArmenian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1245 of file translator_am.h.
    {
      return " () - "+trWriteList(numEntries)+":";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorArmenian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1245 of file translator_am.h.
    {
      return " () - "+trWriteList(numEntries)+":";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorArmenian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1253 of file translator_am.h.
    {
      return " - "+trWriteList(numEntries)+":";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorArmenian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1253 of file translator_am.h.
    {
      return " - "+trWriteList(numEntries)+":";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorArmenian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 940 of file translator_am.h.
    {
      return " , "
            " .";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorArmenian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 940 of file translator_am.h.
    {
      return " , "
            " .";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorArmenian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 793 of file translator_am.h.
    {
      return fName+"- .";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorArmenian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 793 of file translator_am.h.
    {
      return fName+"- .";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorArmenian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1743 of file translator_am.h.
    {
      return " " + name + " ";
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorArmenian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1743 of file translator_am.h.
    {
      return " " + name + " ";
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorArmenian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 109 of file translator_am.h.
    { return ", "; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorArmenian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 109 of file translator_am.h.
    { return ", "; }
trInheritedByList() [1/2]
virtual QCString TranslatorArmenian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 654 of file translator_am.h.
    {
      return " - "+trWriteList(numEntries)+":";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorArmenian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 654 of file translator_am.h.
    {
      return " - "+trWriteList(numEntries)+":";
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorArmenian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 646 of file translator_am.h.
    {
      return " - "+trWriteList(numEntries)+":";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorArmenian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 646 of file translator_am.h.
    {
      return " - "+trWriteList(numEntries)+":";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorArmenian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 828 of file translator_am.h.
    {
      return " ";
    }
trInitialValue() [2/2]
virtual QCString TranslatorArmenian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 828 of file translator_am.h.
    {
      return " ";
    }
trInvariant() [1/2]
virtual QCString TranslatorArmenian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 823 of file translator_am.h.
    {
      return "";
    }
trInvariant() [2/2]
virtual QCString TranslatorArmenian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 823 of file translator_am.h.
    {
      return "";
    }
trISOLang() [1/2]
virtual QCString TranslatorArmenian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 38 of file translator_am.h.
    { return "hy"; }
trISOLang() [2/2]
virtual QCString TranslatorArmenian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 38 of file translator_am.h.
    { return "hy"; }
trLegend() [1/2]
virtual QCString TranslatorArmenian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1023 of file translator_am.h.
    {
      return "";
    }
trLegend() [2/2]
virtual QCString TranslatorArmenian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1023 of file translator_am.h.
    {
      return "";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorArmenian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 963 of file translator_am.h.
    {
      return
        " , doxygen- :<p>\n"
        " .\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* */\n"
        "class Undocumented { };\n\n"
        "/*! */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ {};\n\n"
        "/*! */\n"
        "class ProtectedBase { };\n\n"
        "/*! */\n"
        "class PrivateBase { };\n\n"
        "/*! , Inherited */\n"
        "class Used { };\n\n"
        "/*! , */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " ."
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        " .\n"
        "<ul>\n"
        "<li>%A , "
        " :</li>\n"
        "<li>%A :</li>\n"
        "<li>%A :</li>\n"
        "<li>%A , \n"
        " / : , "
        " :</li>\n"
        "</ul>\n"
        " .\n"
        "<ul>\n"
        "<li>%A "
        " :</li>\n"
        "<li>%A :</li>\n"
        "<li>%A :</li>\n"
        "<li>%A , "
        " : "
        "(), :</li>\n"
        "<li> , "
        " . :</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorArmenian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 963 of file translator_am.h.
    {
      return
        " , doxygen- :<p>\n"
        " .\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* */\n"
        "class Undocumented { };\n\n"
        "/*! */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ {};\n\n"
        "/*! */\n"
        "class ProtectedBase { };\n\n"
        "/*! */\n"
        "class PrivateBase { };\n\n"
        "/*! , Inherited */\n"
        "class Used { };\n\n"
        "/*! , */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " ."
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        " .\n"
        "<ul>\n"
        "<li>%A , "
        " :</li>\n"
        "<li>%A :</li>\n"
        "<li>%A :</li>\n"
        "<li>%A , \n"
        " / : , "
        " :</li>\n"
        "</ul>\n"
        " .\n"
        "<ul>\n"
        "<li>%A "
        " :</li>\n"
        "<li>%A :</li>\n"
        "<li>%A :</li>\n"
        "<li>%A , "
        " : "
        "(), :</li>\n"
        "<li> , "
        " . :</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorArmenian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 956 of file translator_am.h.
    {
      return "";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorArmenian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 956 of file translator_am.h.
    {
      return "";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorArmenian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 90 of file translator_am.h.
    {
      return " ";
    }
trListOfAllMembers() [2/2]
virtual QCString TranslatorArmenian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 90 of file translator_am.h.
    {
      return " ";
    }
trLoading() [1/2]
virtual QCString TranslatorArmenian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1703 of file translator_am.h.
    {
      return "...";
    }
trLoading() [2/2]
virtual QCString TranslatorArmenian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1703 of file translator_am.h.
    {
      return "...";
    }
trMainPage() [1/2]
virtual QCString TranslatorArmenian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 752 of file translator_am.h.
    { return " "; }
trMainPage() [2/2]
virtual QCString TranslatorArmenian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 752 of file translator_am.h.
    { return " "; }
trMember() [1/2]
virtual QCString TranslatorArmenian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1196 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorArmenian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1196 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorArmenian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 72 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorArmenian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 72 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorArmenian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 64 of file translator_am.h.
    { return " h"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorArmenian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 64 of file translator_am.h.
    { return " h"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorArmenian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 68 of file translator_am.h.
    { return " "; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorArmenian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 68 of file translator_am.h.
    { return " "; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorArmenian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1485 of file translator_am.h.
    { return " /"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorArmenian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1485 of file translator_am.h.
    { return " /"; }
trMemberList() [1/2]
virtual QCString TranslatorArmenian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 97 of file translator_am.h.
    {
      return " ";
    }
trMemberList() [2/2]
virtual QCString TranslatorArmenian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 97 of file translator_am.h.
    {
      return " ";
    }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorArmenian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 60 of file translator_am.h.
    { return " (typedef)"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorArmenian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 60 of file translator_am.h.
    { return " (typedef)"; }
trModule() [1/2]
virtual QCString TranslatorArmenian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1637 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorArmenian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1637 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorArmenian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 337 of file translator_am.h.
    { return ""; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorArmenian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 337 of file translator_am.h.
    { return ""; }
trModuleIndex() [1/2]
virtual QCString TranslatorArmenian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 304 of file translator_am.h.
    { return ""; }
trModuleIndex() [2/2]
virtual QCString TranslatorArmenian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 304 of file translator_am.h.
    { return ""; }
trModuleReference() [1/2]
virtual QCString TranslatorArmenian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1601 of file translator_am.h.
    {
      return QCString(" ") + namespaceName;
    }
trModuleReference() [2/2]
virtual QCString TranslatorArmenian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1601 of file translator_am.h.
    {
      return QCString(" ") + namespaceName;
    }
trModules() [1/2]
virtual QCString TranslatorArmenian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 138 of file translator_am.h.
    { return ""; }
trModules() [2/2]
virtual QCString TranslatorArmenian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 138 of file translator_am.h.
    { return ""; }
trModulesDescription() [1/2]
virtual QCString TranslatorArmenian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 291 of file translator_am.h.
    { return " ."; }
trModulesDescription() [2/2]
virtual QCString TranslatorArmenian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 291 of file translator_am.h.
    { return " ."; }
trModulesIndex() [1/2]
virtual QCString TranslatorArmenian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1630 of file translator_am.h.
    { return ""; }
trModulesIndex() [2/2]
virtual QCString TranslatorArmenian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1630 of file translator_am.h.
    { return ""; }
trModulesList() [1/2]
virtual QCString TranslatorArmenian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1551 of file translator_am.h.
    { return " "; }
trModulesList() [2/2]
virtual QCString TranslatorArmenian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1551 of file translator_am.h.
    { return " "; }
trModulesListDescription() [1/2]
virtual QCString TranslatorArmenian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1555 of file translator_am.h.
    {
      QCString result="";
      if (!extractAll) result+=" ";
      result+=" ` .";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorArmenian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1555 of file translator_am.h.
    {
      QCString result="";
      if (!extractAll) result+=" ";
      result+=" ` .";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorArmenian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1611 of file translator_am.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ` ";
      if (extractAll)
      {
        result+=" .";
      }
      else
      {
        result+=", .";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorArmenian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1611 of file translator_am.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ` ";
      if (extractAll)
      {
        result+=" .";
      }
      else
      {
        result+=", .";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorArmenian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1607 of file translator_am.h.
    { return " "; }
trModulesMembers() [2/2]
virtual QCString TranslatorArmenian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1607 of file translator_am.h.
    { return " "; }
trMonth() [1/2]
virtual QCString TranslatorArmenian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1782 of file translator_am.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMonth() [2/2]
virtual QCString TranslatorArmenian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1782 of file translator_am.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMore() [1/2]
virtual QCString TranslatorArmenian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 85 of file translator_am.h.
    { return "..."; }
trMore() [2/2]
virtual QCString TranslatorArmenian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 85 of file translator_am.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorArmenian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1163 of file translator_am.h.
    {
      QCString result((first_capital ? " " : " "));
      if (!singular) result+="";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorArmenian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1163 of file translator_am.h.
    {
      QCString result((first_capital ? " " : " "));
      if (!singular) result+="";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorArmenian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 702 of file translator_am.h.
    { return " "; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorArmenian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 702 of file translator_am.h.
    { return " "; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorArmenian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 696 of file translator_am.h.
    { return " "; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorArmenian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 696 of file translator_am.h.
    { return " "; }
trNamespaceList() [1/2]
virtual QCString TranslatorArmenian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 513 of file translator_am.h.
    { return " "; }
trNamespaceList() [2/2]
virtual QCString TranslatorArmenian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 513 of file translator_am.h.
    { return " "; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorArmenian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 517 of file translator_am.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ` .";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorArmenian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 517 of file translator_am.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ` .";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorArmenian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 680 of file translator_am.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ` "
            " ";
      if (extractAll)
        result+=" .";
      else
        result+=" , .";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorArmenian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 680 of file translator_am.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ` "
            " ";
      if (extractAll)
        result+=" .";
      else
        result+=" , .";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorArmenian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 676 of file translator_am.h.
    { return " "; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorArmenian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 676 of file translator_am.h.
    { return " "; }
trNamespaceReference() [1/2]
virtual QCString TranslatorArmenian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 590 of file translator_am.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorArmenian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 590 of file translator_am.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorArmenian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 712 of file translator_am.h.
    { return " "; }
trNamespaces() [2/2]
virtual QCString TranslatorArmenian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 712 of file translator_am.h.
    { return " "; }
trNoMatches() [1/2]
virtual QCString TranslatorArmenian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1721 of file translator_am.h.
    {
      return "";
    }
trNoMatches() [2/2]
virtual QCString TranslatorArmenian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1721 of file translator_am.h.
    {
      return "";
    }
trNote() [1/2]
virtual QCString TranslatorArmenian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 858 of file translator_am.h.
    {
      return "";
    }
trNote() [2/2]
virtual QCString TranslatorArmenian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 858 of file translator_am.h.
    {
      return "";
    }
trOverloadText() [1/2]
virtual QCString TranslatorArmenian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1458 of file translator_am.h.
    {
       return " ` : "
              " :";
    }
trOverloadText() [2/2]
virtual QCString TranslatorArmenian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1458 of file translator_am.h.
    {
       return " ` : "
              " :";
    }
trPackage() [1/2]
virtual QCString TranslatorArmenian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1075 of file translator_am.h.
    {
      return " "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorArmenian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1075 of file translator_am.h.
    {
      return " "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorArmenian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1330 of file translator_am.h.
    {
      return " ";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorArmenian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1330 of file translator_am.h.
    {
      return " ";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorArmenian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1312 of file translator_am.h.
    {
      return " ";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorArmenian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1312 of file translator_am.h.
    {
      return " ";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorArmenian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1080 of file translator_am.h.
    {
      return " ` ().";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorArmenian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1080 of file translator_am.h.
    {
      return " ` ().";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorArmenian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1316 of file translator_am.h.
    {
      return " ";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorArmenian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1316 of file translator_am.h.
    {
      return " ";
    }
trPackages() [1/2]
virtual QCString TranslatorArmenian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1085 of file translator_am.h.
    {
      return "";
    }
trPackages() [2/2]
virtual QCString TranslatorArmenian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1085 of file translator_am.h.
    {
      return "";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorArmenian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1305 of file translator_am.h.
    {
      return " ";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorArmenian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1305 of file translator_am.h.
    {
      return " ";
    }
trPage() [1/2]
virtual QCString TranslatorArmenian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1185 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorArmenian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1185 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorArmenian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 758 of file translator_am.h.
    { return ":"; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorArmenian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 758 of file translator_am.h.
    { return ":"; }
trPageIndex() [1/2]
virtual QCString TranslatorArmenian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 849 of file translator_am.h.
    {
      return "";
    }
trPageIndex() [2/2]
virtual QCString TranslatorArmenian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 849 of file translator_am.h.
    {
      return "";
    }
trParameters() [1/2]
virtual QCString TranslatorArmenian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 497 of file translator_am.h.
    { return ""; }
trParameters() [2/2]
virtual QCString TranslatorArmenian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 497 of file translator_am.h.
    { return ""; }
trPostcondition() [1/2]
virtual QCString TranslatorArmenian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 818 of file translator_am.h.
    {
      return "";
    }
trPostcondition() [2/2]
virtual QCString TranslatorArmenian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 818 of file translator_am.h.
    {
      return "";
    }
trPrecondition() [1/2]
virtual QCString TranslatorArmenian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 813 of file translator_am.h.
    {
      return "";
    }
trPrecondition() [2/2]
virtual QCString TranslatorArmenian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 813 of file translator_am.h.
    {
      return "";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorArmenian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_am.h.
    {
      return " ";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorArmenian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_am.h.
    {
      return " ";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorArmenian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 611 of file translator_am.h.
    { return " "; }
trPrivateMembers() [2/2]
virtual QCString TranslatorArmenian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 611 of file translator_am.h.
    { return " "; }
trPrivateSlots() [1/2]
virtual QCString TranslatorArmenian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 613 of file translator_am.h.
    { return " "; }
trPrivateSlots() [2/2]
virtual QCString TranslatorArmenian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 613 of file translator_am.h.
    { return " "; }
trPrivateTypes() [1/2]
virtual QCString TranslatorArmenian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_am.h.
    {
      return " ";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorArmenian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_am.h.
    {
      return " ";
    }
trProperties() [1/2]
virtual QCString TranslatorArmenian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1048 of file translator_am.h.
    {
      return "";
    }
trProperties() [2/2]
virtual QCString TranslatorArmenian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1048 of file translator_am.h.
    {
      return "";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorArmenian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1053 of file translator_am.h.
    {
      return "";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorArmenian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1053 of file translator_am.h.
    {
      return "";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorArmenian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_am.h.
    {
      return " ";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorArmenian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_am.h.
    {
      return " ";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorArmenian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 605 of file translator_am.h.
    { return " "; }
trProtectedMembers() [2/2]
virtual QCString TranslatorArmenian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 605 of file translator_am.h.
    { return " "; }
trProtectedSlots() [1/2]
virtual QCString TranslatorArmenian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 607 of file translator_am.h.
    { return " "; }
trProtectedSlots() [2/2]
virtual QCString TranslatorArmenian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 607 of file translator_am.h.
    { return " "; }
trProtectedTypes() [1/2]
virtual QCString TranslatorArmenian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_am.h.
    {
      return " ";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorArmenian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_am.h.
    {
      return " ";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorArmenian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 866 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorArmenian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 866 of file translator_am.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorArmenian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 597 of file translator_am.h.
    { return " "; }
trPublicMembers() [2/2]
virtual QCString TranslatorArmenian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 597 of file translator_am.h.
    { return " "; }
trPublicSlots() [1/2]
virtual QCString TranslatorArmenian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 599 of file translator_am.h.
    { return " "; }
trPublicSlots() [2/2]
virtual QCString TranslatorArmenian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 599 of file translator_am.h.
    { return " "; }
trPublicTypes() [1/2]
virtual QCString TranslatorArmenian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 862 of file translator_am.h.
    {
      return " ";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorArmenian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 862 of file translator_am.h.
    {
      return " ";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorArmenian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_am.h.
    {
      return " - ";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorArmenian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_am.h.
    {
      return " - ";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorArmenian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 372 of file translator_am.h.
    { return " "; }
trReferenceManual() [2/2]
virtual QCString TranslatorArmenian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 372 of file translator_am.h.
    { return " "; }
trReferences() [1/2]
virtual QCString TranslatorArmenian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1233 of file translator_am.h.
    {
      return " - ";
    }
trReferences() [2/2]
virtual QCString TranslatorArmenian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1233 of file translator_am.h.
    {
      return " - ";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorArmenian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 662 of file translator_am.h.
    {
      return " - "+trWriteList(numEntries)+":";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorArmenian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 662 of file translator_am.h.
    {
      return " - "+trWriteList(numEntries)+":";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorArmenian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 670 of file translator_am.h.
    {
      return " "+trWriteList(numEntries)+" :";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorArmenian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 670 of file translator_am.h.
    {
      return " "+trWriteList(numEntries)+" :";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorArmenian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 538 of file translator_am.h.
    { return " "; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorArmenian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 538 of file translator_am.h.
    { return " "; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorArmenian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 48 of file translator_am.h.
    { return " "; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorArmenian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 48 of file translator_am.h.
    { return " "; }
trRelatedPages() [1/2]
virtual QCString TranslatorArmenian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 190 of file translator_am.h.
    { return " "; }
trRelatedPages() [2/2]
virtual QCString TranslatorArmenian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 190 of file translator_am.h.
    { return " "; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorArmenian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 287 of file translator_am.h.
    { return " ."; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorArmenian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 287 of file translator_am.h.
    { return " ."; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorArmenian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 52 of file translator_am.h.
    { return "(,)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorArmenian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 52 of file translator_am.h.
    { return "(,)"; }
trRemarks() [1/2]
virtual QCString TranslatorArmenian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 932 of file translator_am.h.
    {
      return "";
    }
trRemarks() [2/2]
virtual QCString TranslatorArmenian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 932 of file translator_am.h.
    {
      return "";
    }
trReturns() [1/2]
virtual QCString TranslatorArmenian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 489 of file translator_am.h.
    { return " "; }
trReturns() [2/2]
virtual QCString TranslatorArmenian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 489 of file translator_am.h.
    { return " "; }
trReturnValues() [1/2]
virtual QCString TranslatorArmenian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 747 of file translator_am.h.
    { return " "; }
trReturnValues() [2/2]
virtual QCString TranslatorArmenian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 747 of file translator_am.h.
    { return " "; }
trRTFansicp() [1/2]
virtual QCString TranslatorArmenian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1114 of file translator_am.h.
    {
      return "armscii-8";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorArmenian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1114 of file translator_am.h.
    {
      return "armscii-8";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorArmenian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1119 of file translator_am.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorArmenian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1119 of file translator_am.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorArmenian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1124 of file translator_am.h.
    {
      return "";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorArmenian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1124 of file translator_am.h.
    {
      return "";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorArmenian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1265 of file translator_am.h.
    {
      return "";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorArmenian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1265 of file translator_am.h.
    {
      return "";
    }
trSearch() [1/2]
virtual QCString TranslatorArmenian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 198 of file translator_am.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorArmenian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 198 of file translator_am.h.
    { return ""; }
trSearching() [1/2]
virtual QCString TranslatorArmenian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1715 of file translator_am.h.
    {
      return "...";
    }
trSearching() [2/2]
virtual QCString TranslatorArmenian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1715 of file translator_am.h.
    {
      return "...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorArmenian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1397 of file translator_am.h.
    {
      return " :";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorArmenian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1397 of file translator_am.h.
    {
      return " :";
    }
trSearchResults() [1/2]
virtual QCString TranslatorArmenian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1378 of file translator_am.h.
    {
      if (numDocuments==0)
      {
        return ", :";
      }
      else if(numDocuments == 1)
      {
        return " 1 :";
      }
      else
      {
        return " <b>$num</b> :"
          " ";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorArmenian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1378 of file translator_am.h.
    {
      if (numDocuments==0)
      {
        return ", :";
      }
      else if(numDocuments == 1)
      {
        return " 1 :";
      }
      else
      {
        return " <b>$num</b> :"
          " ";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorArmenian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1366 of file translator_am.h.
    {
      return " ";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorArmenian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1366 of file translator_am.h.
    {
      return " ";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorArmenian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 493 of file translator_am.h.
    { return " "; }
trSeeAlso() [2/2]
virtual QCString TranslatorArmenian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 493 of file translator_am.h.
    { return " "; }
trSignals() [1/2]
virtual QCString TranslatorArmenian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 601 of file translator_am.h.
    { return ""; }
trSignals() [2/2]
virtual QCString TranslatorArmenian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 601 of file translator_am.h.
    { return ""; }
trSince() [1/2]
virtual QCString TranslatorArmenian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 945 of file translator_am.h.
    {
      return "";
    }
trSince() [2/2]
virtual QCString TranslatorArmenian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 945 of file translator_am.h.
    {
      return "";
    }
trSourceFile() [1/2]
virtual QCString TranslatorArmenian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1408 of file translator_am.h.
    {
      return " " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorArmenian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1408 of file translator_am.h.
    {
      return " " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorArmenian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1337 of file translator_am.h.
    {
      return " ";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorArmenian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1337 of file translator_am.h.
    {
      return " ";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorArmenian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1323 of file translator_am.h.
    {
      return " ";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorArmenian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1323 of file translator_am.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorArmenian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 901 of file translator_am.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorArmenian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 901 of file translator_am.h.
    {
      return " ";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorArmenian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 615 of file translator_am.h.
    { return " "; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorArmenian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 615 of file translator_am.h.
    { return " "; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorArmenian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_am.h.
    {
      return " ";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorArmenian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_am.h.
    {
      return " ";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorArmenian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 609 of file translator_am.h.
    { return " "; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorArmenian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 609 of file translator_am.h.
    { return " "; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorArmenian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_am.h.
    {
      return " ";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorArmenian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_am.h.
    {
      return " ";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorArmenian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 603 of file translator_am.h.
    { return " "; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorArmenian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 603 of file translator_am.h.
    { return " "; }
trSubprogram() [1/2]
virtual QCString TranslatorArmenian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1680 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorArmenian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1680 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorArmenian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1541 of file translator_am.h.
    { return "/"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorArmenian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1541 of file translator_am.h.
    { return "/"; }
trSubprograms() [1/2]
virtual QCString TranslatorArmenian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1535 of file translator_am.h.
    { return "/"; }
trSubprograms() [2/2]
virtual QCString TranslatorArmenian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1535 of file translator_am.h.
    { return "/"; }
trTest() [1/2]
virtual QCString TranslatorArmenian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1033 of file translator_am.h.
    {
      return "";
    }
trTest() [2/2]
virtual QCString TranslatorArmenian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1033 of file translator_am.h.
    {
      return "";
    }
trTestList() [1/2]
virtual QCString TranslatorArmenian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1038 of file translator_am.h.
    {
      return " ";
    }
trTestList() [2/2]
virtual QCString TranslatorArmenian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1038 of file translator_am.h.
    {
      return " ";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorArmenian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 104 of file translator_am.h.
    { return " "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorArmenian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 104 of file translator_am.h.
    { return " "; }
trTodo() [1/2]
virtual QCString TranslatorArmenian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 912 of file translator_am.h.
    {
      return " ";
    }
trTodo() [2/2]
virtual QCString TranslatorArmenian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 912 of file translator_am.h.
    {
      return " ";
    }
trTodoList() [1/2]
virtual QCString TranslatorArmenian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 918 of file translator_am.h.
    {
      return " ";
    }
trTodoList() [2/2]
virtual QCString TranslatorArmenian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 918 of file translator_am.h.
    {
      return " ";
    }
trType() [1/2]
virtual QCString TranslatorArmenian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1670 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorArmenian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1670 of file translator_am.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorArmenian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1688 of file translator_am.h.
    {
      return " ";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorArmenian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1688 of file translator_am.h.
    {
      return " ";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorArmenian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 420 of file translator_am.h.
    { return " (typedef)"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorArmenian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 420 of file translator_am.h.
    { return " (typedef)"; }
trTypedefs() [1/2]
virtual QCString TranslatorArmenian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 384 of file translator_am.h.
    { return " (typedef)"; }
trTypedefs() [2/2]
virtual QCString TranslatorArmenian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 384 of file translator_am.h.
    { return " (typedef)"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorArmenian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1529 of file translator_am.h.
    { return " "; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorArmenian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1529 of file translator_am.h.
    { return " "; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorArmenian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 438 of file translator_am.h.
    { return ""; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorArmenian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 438 of file translator_am.h.
    { return ""; }
trVariables() [1/2]
virtual QCString TranslatorArmenian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 402 of file translator_am.h.
    { return ""; }
trVariables() [2/2]
virtual QCString TranslatorArmenian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 402 of file translator_am.h.
    { return ""; }
trVersion() [1/2]
virtual QCString TranslatorArmenian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 481 of file translator_am.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorArmenian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 481 of file translator_am.h.
    { return ""; }
trWarning() [1/2]
virtual QCString TranslatorArmenian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 477 of file translator_am.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorArmenian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 477 of file translator_am.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorArmenian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 621 of file translator_am.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorArmenian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 621 of file translator_am.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_am.h
doxygen/src/translator_am.h