TranslatorSerbianCyrillic Class Reference
#include <translator_sc.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString latexFontenc ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString latexFontenc ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
Additional Inherited Members
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include `translator.h` or `translator_adapter.h` here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 43 of file translator_sc.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorSerbianCyrillic::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 85 of file translator_sc.h.
    {
      return "0xC1A Serbian (Serbia, Cyrillic)";
    }
getLanguageString() [2/2]
virtual QCString TranslatorSerbianCyrillic::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 85 of file translator_sc.h.
    {
      return "0xC1A Serbian (Serbia, Cyrillic)";
    }
idLanguage() [1/2]
virtual QCString TranslatorSerbianCyrillic::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 55 of file translator_sc.h.
    { return "serbian-cyrillic"; }
idLanguage() [2/2]
virtual QCString TranslatorSerbianCyrillic::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 55 of file translator_sc.h.
    { return "serbian-cyrillic"; }
latexFontenc() [1/2]
virtual QCString TranslatorSerbianCyrillic::latexFontenc () [inline], [virtual]
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 77 of file translator_sc.h.
    {
      return "";
    }
latexFontenc() [2/2]
virtual QCString TranslatorSerbianCyrillic::latexFontenc () [inline], [virtual]
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 77 of file translator_sc.h.
    {
      return "";
    }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorSerbianCyrillic::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 72 of file translator_sc.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[serbianc]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorSerbianCyrillic::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 72 of file translator_sc.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[serbianc]{babel}\n";
    }
trAll() [1/2]
virtual QCString TranslatorSerbianCyrillic::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1422 of file translator_sc.h.
    {
      return "";
    }
trAll() [2/2]
virtual QCString TranslatorSerbianCyrillic::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1422 of file translator_sc.h.
    {
      return "";
    }
trAttention() [1/2]
virtual QCString TranslatorSerbianCyrillic::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 985 of file translator_sc.h.
    {
      return "";
    }
trAttention() [2/2]
virtual QCString TranslatorSerbianCyrillic::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 985 of file translator_sc.h.
    {
      return "";
    }
trAuthor() [1/2]
virtual QCString TranslatorSerbianCyrillic::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1293 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorSerbianCyrillic::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1293 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorSerbianCyrillic::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1151 of file translator_sc.h.
    {
      return "";
    }
trBug() [2/2]
virtual QCString TranslatorSerbianCyrillic::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1151 of file translator_sc.h.
    {
      return "";
    }
trBugList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1156 of file translator_sc.h.
    {
      return " ";
    }
trBugList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1156 of file translator_sc.h.
    {
      return " ";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1554 of file translator_sc.h.
    {
      return " :";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1554 of file translator_sc.h.
    {
      return " :";
    }
trCallGraph() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1427 of file translator_sc.h.
    {
      return " :";
    }
trCallGraph() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1427 of file translator_sc.h.
    {
      return " :";
    }
trClass() [1/2]
virtual QCString TranslatorSerbianCyrillic::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1214 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="e"; else result+="a";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorSerbianCyrillic::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1214 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="e"; else result+="a";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorSerbianCyrillic::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 521 of file translator_sc.h.
    {
      return " "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorSerbianCyrillic::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 521 of file translator_sc.h.
    {
      return " "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 396 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return " ";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 396 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return " ";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorSerbianCyrillic::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1114 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorSerbianCyrillic::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1114 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorSerbianCyrillic::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 180 of file translator_sc.h.
    { return " "; }
trClassHierarchy() [2/2]
virtual QCString TranslatorSerbianCyrillic::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 180 of file translator_sc.h.
    { return " "; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 239 of file translator_sc.h.
    { return " "
             " :";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 239 of file translator_sc.h.
    { return " "
             " :";
    }
trCode() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 885 of file translator_sc.h.
    {
      return "";
    }
trCode() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 885 of file translator_sc.h.
    {
      return "";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 840 of file translator_sc.h.
    {
      return " "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 840 of file translator_sc.h.
    {
      return " "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 369 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 369 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1609 of file translator_sc.h.
    { return " "; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1609 of file translator_sc.h.
    { return " "; }
trCompoundList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 184 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 184 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 254 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " :";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return " :";
      }
      else
      {
        return " , , "
               " :";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 254 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " :";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return " :";
      }
      else
      {
        return " , , "
               " :";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1582 of file translator_sc.h.
    { return " :"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1582 of file translator_sc.h.
    { return " :"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1574 of file translator_sc.h.
    { return " "; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1574 of file translator_sc.h.
    { return " "; }
trCompoundMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 201 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 201 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 273 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" / :";
        }
        else
        {
          result+=" :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="/ :";
        }
        else
        {
          result+=" :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 273 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" / :";
        }
        else
        {
          result+=" :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="/ :";
        }
        else
        {
          result+=" :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1586 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ";
      result+=" ";
      if (!extractAll)
      {
         result+=" ";
      }
      else
      {
         result+=" :";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1586 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ";
      result+=" ";
      if (!extractAll)
      {
         result+=" ";
      }
      else
      {
         result+=" :";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1578 of file translator_sc.h.
    { return ""; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1578 of file translator_sc.h.
    { return ""; }
trCompoundReference() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 596 of file translator_sc.h.
    {
      QCString result=clName;
      if (isTemplate)
      {
        result+=" ";
        switch(compType)
        {
          case ClassDef::Class: result+=" "; break;
          case ClassDef::Struct: result+=" "; break;
          case ClassDef::Union: result+=" "; break;
          case ClassDef::Interface: result+=" "; break;
          case ClassDef::Protocol: result+=" "; break;
          case ClassDef::Category: result+=" "; break;
          case ClassDef::Exception: result+=" "; break;
          default: break;
        }
      }
      else
      {
        result+=" ";
        switch(compType)
        {
          case ClassDef::Class: result+=" "; break;
          case ClassDef::Struct: result+=" "; break;
          case ClassDef::Union: result+=" "; break;
          case ClassDef::Interface: result+=" "; break;
          case ClassDef::Protocol: result+=" "; break;
          case ClassDef::Category: result+=" "; break;
          case ClassDef::Exception: result+=" "; break;
          default: break;
        }
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 596 of file translator_sc.h.
    {
      QCString result=clName;
      if (isTemplate)
      {
        result+=" ";
        switch(compType)
        {
          case ClassDef::Class: result+=" "; break;
          case ClassDef::Struct: result+=" "; break;
          case ClassDef::Union: result+=" "; break;
          case ClassDef::Interface: result+=" "; break;
          case ClassDef::Protocol: result+=" "; break;
          case ClassDef::Category: result+=" "; break;
          case ClassDef::Exception: result+=" "; break;
          default: break;
        }
      }
      else
      {
        result+=" ";
        switch(compType)
        {
          case ClassDef::Class: result+=" "; break;
          case ClassDef::Struct: result+=" "; break;
          case ClassDef::Union: result+=" "; break;
          case ClassDef::Interface: result+=" "; break;
          case ClassDef::Protocol: result+=" "; break;
          case ClassDef::Category: result+=" "; break;
          case ClassDef::Exception: result+=" "; break;
          default: break;
        }
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1650 of file translator_sc.h.
    {
      QCString result=clName;
      if (isTemplate) result+=" ";
      result+=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1650 of file translator_sc.h.
    {
      QCString result=clName;
      if (isTemplate) result+=" ";
      result+=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorSerbianCyrillic::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 497 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorSerbianCyrillic::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 497 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 850 of file translator_sc.h.
    {
      return " ";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 850 of file translator_sc.h.
    {
      return " ";
    }
trDataTypes() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1633 of file translator_sc.h.
    { return " "; }
trDataTypes() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1633 of file translator_sc.h.
    { return " "; }
trDate() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 535 of file translator_sc.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 535 of file translator_sc.h.
    { return ""; }
trDayOfWeek() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1765 of file translator_sc.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1765 of file translator_sc.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1779 of file translator_sc.h.
    {
      static const char *dayPeriod[] = { " ", " " };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1779 of file translator_sc.h.
    {
      static const char *dayPeriod[] = { " ", " " };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 817 of file translator_sc.h.
    {
      return " @0 @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 817 of file translator_sc.h.
    {
      return " @0 @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 168 of file translator_sc.h.
    { return " "; }
trDefinedIn() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 168 of file translator_sc.h.
    { return " "; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 821 of file translator_sc.h.
    {
      return " @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 821 of file translator_sc.h.
    {
      return " @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 467 of file translator_sc.h.
    { return " "; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 467 of file translator_sc.h.
    { return " "; }
trDefines() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 431 of file translator_sc.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 431 of file translator_sc.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1141 of file translator_sc.h.
    {
      return ":";
    }
trDefineValue() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1141 of file translator_sc.h.
    {
      return ":";
    }
trDeprecated() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 830 of file translator_sc.h.
    {
      return "";
    }
trDeprecated() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 830 of file translator_sc.h.
    {
      return "";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1350 of file translator_sc.h.
    {
      return " ";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1350 of file translator_sc.h.
    {
      return " ";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 101 of file translator_sc.h.
    { return ""; }
trDetailedDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 101 of file translator_sc.h.
    { return ""; }
trDir() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1529 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1529 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trDirDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1511 of file translator_sc.h.
    { return " "; }
trDirDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1511 of file translator_sc.h.
    { return " "; }
trDirectories() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1517 of file translator_sc.h.
    { return ""; }
trDirectories() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1517 of file translator_sc.h.
    { return ""; }
trDirIndex() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1505 of file translator_sc.h.
    { return " "; }
trDirIndex() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1505 of file translator_sc.h.
    { return " "; }
trDirReference() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1523 of file translator_sc.h.
    { QCString result=dirName; result+=" "; return result; }
trDirReference() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1523 of file translator_sc.h.
    { QCString result=dirName; result+=" "; return result; }
trDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 351 of file translator_sc.h.
    { return ""; }
trDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 351 of file translator_sc.h.
    { return ""; }
trEnumerations() [1/2]
virtual QCString TranslatorSerbianCyrillic::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 443 of file translator_sc.h.
    { return ""; }
trEnumerations() [2/2]
virtual QCString TranslatorSerbianCyrillic::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 443 of file translator_sc.h.
    { return ""; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 479 of file translator_sc.h.
    { return " "; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 479 of file translator_sc.h.
    { return " "; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1562 of file translator_sc.h.
    { return " "; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1562 of file translator_sc.h.
    { return " "; }
trEnumerationValues() [1/2]
virtual QCString TranslatorSerbianCyrillic::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 461 of file translator_sc.h.
    { return " "; }
trEnumerationValues() [2/2]
virtual QCString TranslatorSerbianCyrillic::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 461 of file translator_sc.h.
    { return " "; }
trEnumName() [1/2]
virtual QCString TranslatorSerbianCyrillic::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 160 of file translator_sc.h.
    { return " "; }
trEnumName() [2/2]
virtual QCString TranslatorSerbianCyrillic::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 160 of file translator_sc.h.
    { return " "; }
trEnumValue() [1/2]
virtual QCString TranslatorSerbianCyrillic::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 164 of file translator_sc.h.
    { return " "; }
trEnumValue() [2/2]
virtual QCString TranslatorSerbianCyrillic::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 164 of file translator_sc.h.
    { return " "; }
trEventDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1367 of file translator_sc.h.
    {
      return " ";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1367 of file translator_sc.h.
    {
      return " ";
    }
trEvents() [1/2]
virtual QCString TranslatorSerbianCyrillic::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1362 of file translator_sc.h.
    {
      return "";
    }
trEvents() [2/2]
virtual QCString TranslatorSerbianCyrillic::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1362 of file translator_sc.h.
    {
      return "";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 421 of file translator_sc.h.
    { return " "; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 421 of file translator_sc.h.
    { return " "; }
trExamples() [1/2]
virtual QCString TranslatorSerbianCyrillic::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 231 of file translator_sc.h.
    { return ""; }
trExamples() [2/2]
virtual QCString TranslatorSerbianCyrillic::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 231 of file translator_sc.h.
    { return ""; }
trExamplesDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 337 of file translator_sc.h.
    { return " :"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 337 of file translator_sc.h.
    { return " :"; }
trExceptions() [1/2]
virtual QCString TranslatorSerbianCyrillic::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 551 of file translator_sc.h.
    { return ""; }
trExceptions() [2/2]
virtual QCString TranslatorSerbianCyrillic::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 551 of file translator_sc.h.
    { return ""; }
trFile() [1/2]
virtual QCString TranslatorSerbianCyrillic::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1225 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="e"; else result+="a";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorSerbianCyrillic::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1225 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="e"; else result+="a";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 415 of file translator_sc.h.
    { return " "; }
trFileDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 415 of file translator_sc.h.
    { return " "; }
trFileIndex() [1/2]
virtual QCString TranslatorSerbianCyrillic::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 384 of file translator_sc.h.
    { return " "; }
trFileIndex() [2/2]
virtual QCString TranslatorSerbianCyrillic::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 384 of file translator_sc.h.
    { return " "; }
trFileList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 197 of file translator_sc.h.
    { return " "; }
trFileList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 197 of file translator_sc.h.
    { return " "; }
trFileListDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 245 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 245 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 214 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 214 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 315 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , , , ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (extractAll)
        result+=" :";
      else
        result+=":";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 315 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , , , ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (extractAll)
        result+=" :";
      else
        result+=":";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorSerbianCyrillic::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 635 of file translator_sc.h.
    {
      QCString result=fileName;
      result+=" ";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorSerbianCyrillic::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 635 of file translator_sc.h.
    {
      QCString result=fileName;
      result+=" ";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorSerbianCyrillic::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 578 of file translator_sc.h.
    { return ""; }
trFriends() [2/2]
virtual QCString TranslatorSerbianCyrillic::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 578 of file translator_sc.h.
    { return ""; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 485 of file translator_sc.h.
    { return " "; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 485 of file translator_sc.h.
    { return " "; }
trFunctions() [1/2]
virtual QCString TranslatorSerbianCyrillic::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 449 of file translator_sc.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorSerbianCyrillic::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 449 of file translator_sc.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorSerbianCyrillic::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 512 of file translator_sc.h.
    {
      QCString result=" "+date;
      if (!projName.isEmpty()) result+=" "+projName;
      result+=" ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorSerbianCyrillic::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 512 of file translator_sc.h.
    {
      QCString result=" "+date;
      if (!projName.isEmpty()) result+=" "+projName;
      result+=" ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorSerbianCyrillic::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 152 of file translator_sc.h.
    { QCString result=" Doxygen-";
      if (!s.isEmpty()) result+=" "+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorSerbianCyrillic::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 152 of file translator_sc.h.
    { QCString result=" Doxygen-";
      if (!s.isEmpty()) result+=" "+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorSerbianCyrillic::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 555 of file translator_sc.h.
    { return " "; }
trGeneratedBy() [2/2]
virtual QCString TranslatorSerbianCyrillic::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 555 of file translator_sc.h.
    { return " "; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorSerbianCyrillic::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 773 of file translator_sc.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorSerbianCyrillic::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 773 of file translator_sc.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorSerbianCyrillic::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1718 of file translator_sc.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorSerbianCyrillic::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1718 of file translator_sc.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorSerbianCyrillic::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1280 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorSerbianCyrillic::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1280 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="";
      return result;
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 860 of file translator_sc.h.
    {
      return " .";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 860 of file translator_sc.h.
    {
      return " .";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorSerbianCyrillic::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_sc.h.
    {
      return " ";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorSerbianCyrillic::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_sc.h.
    {
      return " ";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorSerbianCyrillic::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 855 of file translator_sc.h.
    {
      return " .";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorSerbianCyrillic::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 855 of file translator_sc.h.
    {
      return " .";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorSerbianCyrillic::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_sc.h.
    {
      return " ";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorSerbianCyrillic::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_sc.h.
    {
      return " ";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorSerbianCyrillic::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_sc.h.
    {
      return " ";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorSerbianCyrillic::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_sc.h.
    {
      return " ";
    }
trGroup() [1/2]
virtual QCString TranslatorSerbianCyrillic::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1247 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="a";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorSerbianCyrillic::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1247 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result+="a";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorSerbianCyrillic::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 363 of file translator_sc.h.
    { return " "; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorSerbianCyrillic::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 363 of file translator_sc.h.
    { return " "; }
trImplementedFromList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1318 of file translator_sc.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1318 of file translator_sc.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1326 of file translator_sc.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1326 of file translator_sc.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorSerbianCyrillic::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 989 of file translator_sc.h.
    {
      return " "
             " :";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorSerbianCyrillic::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 989 of file translator_sc.h.
    {
      return " "
             " :";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorSerbianCyrillic::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 845 of file translator_sc.h.
    {
      return " "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorSerbianCyrillic::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 845 of file translator_sc.h.
    {
      return " "+fName+":";
    }
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 146 of file translator_sc.h.
    { return ", ."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 146 of file translator_sc.h.
    { return ", ."; }
trInheritedByList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 707 of file translator_sc.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 707 of file translator_sc.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 699 of file translator_sc.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 699 of file translator_sc.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorSerbianCyrillic::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 880 of file translator_sc.h.
    {
      return " :";
    }
trInitialValue() [2/2]
virtual QCString TranslatorSerbianCyrillic::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 880 of file translator_sc.h.
    {
      return " :";
    }
trInvariant() [1/2]
virtual QCString TranslatorSerbianCyrillic::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 875 of file translator_sc.h.
    {
      return "";
    }
trInvariant() [2/2]
virtual QCString TranslatorSerbianCyrillic::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 875 of file translator_sc.h.
    {
      return "";
    }
trISOLang() [1/2]
virtual QCString TranslatorSerbianCyrillic::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 81 of file translator_sc.h.
    {
      return "sr-Cyrl";
    }
trISOLang() [2/2]
virtual QCString TranslatorSerbianCyrillic::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 81 of file translator_sc.h.
    {
      return "sr-Cyrl";
    }
trLegend() [1/2]
virtual QCString TranslatorSerbianCyrillic::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1074 of file translator_sc.h.
    {
      return "";
    }
trLegend() [2/2]
virtual QCString TranslatorSerbianCyrillic::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1074 of file translator_sc.h.
    {
      return "";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorSerbianCyrillic::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1011 of file translator_sc.h.
    {
      return
        " "
        "doxygen-.<p>\n"
        " :\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ { };\n\n"
        "/*! */\n"
        "class ProtectedBase { };\n\n"
        "/*! */\n"
        "class PrivateBase { };\n\n"
        "/*! */\n"
        "class Used { };\n\n"
        "/*! */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " \\c MAX_DOT_GRAPH_HEIGHT "
        " 240, :"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        " :\n"
        "<ul>\n"
        "<li>% "
        " .\n"
        "<li>% .\n"
        "<li>% .\n"
        "<li>% "
        " / . % "
        " .\n"
        "</ul>\n"
        " :\n"
        "<ul>\n"
        "<li>% "
        " .\n"
        "<li>% .\n"
        "<li>% .\n"
        "<li>% "
        " . / "
        " .\n"
        "<li>% "
        " . "
        " .\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorSerbianCyrillic::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1011 of file translator_sc.h.
    {
      return
        " "
        "doxygen-.<p>\n"
        " :\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ { };\n\n"
        "/*! */\n"
        "class ProtectedBase { };\n\n"
        "/*! */\n"
        "class PrivateBase { };\n\n"
        "/*! */\n"
        "class Used { };\n\n"
        "/*! */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " \\c MAX_DOT_GRAPH_HEIGHT "
        " 240, :"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        " :\n"
        "<ul>\n"
        "<li>% "
        " .\n"
        "<li>% .\n"
        "<li>% .\n"
        "<li>% "
        " / . % "
        " .\n"
        "</ul>\n"
        " :\n"
        "<ul>\n"
        "<li>% "
        " .\n"
        "<li>% .\n"
        "<li>% .\n"
        "<li>% "
        " . / "
        " .\n"
        "<li>% "
        " . "
        " .\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorSerbianCyrillic::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1004 of file translator_sc.h.
    {
      return " ";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorSerbianCyrillic::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1004 of file translator_sc.h.
    {
      return " ";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 134 of file translator_sc.h.
    { return " "; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 134 of file translator_sc.h.
    { return " "; }
trMainPage() [1/2]
virtual QCString TranslatorSerbianCyrillic::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 804 of file translator_sc.h.
    { return " "; }
trMainPage() [2/2]
virtual QCString TranslatorSerbianCyrillic::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 804 of file translator_sc.h.
    { return " "; }
trMember() [1/2]
virtual QCString TranslatorSerbianCyrillic::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1269 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorSerbianCyrillic::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1269 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 117 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 117 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 109 of file translator_sc.h.
    { return " "; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 109 of file translator_sc.h.
    { return " "; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 113 of file translator_sc.h.
    { return " "; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 113 of file translator_sc.h.
    { return " "; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorSerbianCyrillic::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1570 of file translator_sc.h.
    { return "r , "; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorSerbianCyrillic::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1570 of file translator_sc.h.
    { return "r , "; }
trMemberList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 138 of file translator_sc.h.
    { return " "; }
trMemberList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 138 of file translator_sc.h.
    { return " "; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 105 of file translator_sc.h.
    { return " "; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 105 of file translator_sc.h.
    { return " "; }
trModule() [1/2]
virtual QCString TranslatorSerbianCyrillic::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1709 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorSerbianCyrillic::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1709 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 390 of file translator_sc.h.
    { return " "; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 390 of file translator_sc.h.
    { return " "; }
trModuleIndex() [1/2]
virtual QCString TranslatorSerbianCyrillic::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 357 of file translator_sc.h.
    { return " "; }
trModuleIndex() [2/2]
virtual QCString TranslatorSerbianCyrillic::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 357 of file translator_sc.h.
    { return " "; }
trModuleReference() [1/2]
virtual QCString TranslatorSerbianCyrillic::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1671 of file translator_sc.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorSerbianCyrillic::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1671 of file translator_sc.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorSerbianCyrillic::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 176 of file translator_sc.h.
    { return ""; }
trModules() [2/2]
virtual QCString TranslatorSerbianCyrillic::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 176 of file translator_sc.h.
    { return ""; }
trModulesDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 345 of file translator_sc.h.
    { return " :"; }
trModulesDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 345 of file translator_sc.h.
    { return " :"; }
trModulesIndex() [1/2]
virtual QCString TranslatorSerbianCyrillic::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1702 of file translator_sc.h.
    { return " "; }
trModulesIndex() [2/2]
virtual QCString TranslatorSerbianCyrillic::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1702 of file translator_sc.h.
    { return " "; }
trModulesList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1637 of file translator_sc.h.
    { return " "; }
trModulesList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1637 of file translator_sc.h.
    { return " "; }
trModulesListDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1641 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1641 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1683 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
      {
        result+=" :";
      }
      else
      {
        result+=" :";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1683 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
      {
        result+=" :";
      }
      else
      {
        result+=" :";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1679 of file translator_sc.h.
    { return " "; }
trModulesMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1679 of file translator_sc.h.
    { return " "; }
trMonth() [1/2]
virtual QCString TranslatorSerbianCyrillic::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1772 of file translator_sc.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", " ", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", " " };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorSerbianCyrillic::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1772 of file translator_sc.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", " ", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", " " };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
virtual QCString TranslatorSerbianCyrillic::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 130 of file translator_sc.h.
    { return "..."; }
trMore() [2/2]
virtual QCString TranslatorSerbianCyrillic::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 130 of file translator_sc.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorSerbianCyrillic::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1236 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=" "; else result+=" ";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorSerbianCyrillic::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1236 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=" "; else result+=" ";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 753 of file translator_sc.h.
    { return " "; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 753 of file translator_sc.h.
    { return " "; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 747 of file translator_sc.h.
    { return " "; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 747 of file translator_sc.h.
    { return " "; }
trNamespaceList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 563 of file translator_sc.h.
    { return " "; }
trNamespaceList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 563 of file translator_sc.h.
    { return " "; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 567 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 567 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 733 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
        result+=" :";
      else
        result+=" :";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 733 of file translator_sc.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
        result+=" :";
      else
        result+=" :";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 729 of file translator_sc.h.
    { return " "; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 729 of file translator_sc.h.
    { return " "; }
trNamespaceReference() [1/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 643 of file translator_sc.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 643 of file translator_sc.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 763 of file translator_sc.h.
    { return " "; }
trNamespaces() [2/2]
virtual QCString TranslatorSerbianCyrillic::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 763 of file translator_sc.h.
    { return " "; }
trNote() [1/2]
virtual QCString TranslatorSerbianCyrillic::trNote () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_sc.h.
    {
      return "";
    }
trNote() [2/2]
virtual QCString TranslatorSerbianCyrillic::trNote () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_sc.h.
    {
      return "";
    }
trOverloadText() [1/2]
virtual QCString TranslatorSerbianCyrillic::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1543 of file translator_sc.h.
    {
       return " . "
              " ";
    }
trOverloadText() [2/2]
virtual QCString TranslatorSerbianCyrillic::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1543 of file translator_sc.h.
    {
       return " . "
              " ";
    }
trPackage() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1126 of file translator_sc.h.
    {
      return " "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1126 of file translator_sc.h.
    {
      return " "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1403 of file translator_sc.h.
    {
      return " ";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1403 of file translator_sc.h.
    {
      return " ";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1385 of file translator_sc.h.
    {
      return " ";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1385 of file translator_sc.h.
    {
      return " ";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1131 of file translator_sc.h.
    {
      return " ():";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1131 of file translator_sc.h.
    {
      return " ():";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1389 of file translator_sc.h.
    {
      return " ";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1389 of file translator_sc.h.
    {
      return " ";
    }
trPackages() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1136 of file translator_sc.h.
    {
      return "";
    }
trPackages() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1136 of file translator_sc.h.
    {
      return "";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1378 of file translator_sc.h.
    {
      return " ";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1378 of file translator_sc.h.
    {
      return " ";
    }
trPage() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1258 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result += "a";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1258 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+=""; else result += "a";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 810 of file translator_sc.h.
    { return "."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 810 of file translator_sc.h.
    { return "."; }
trPageIndex() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 901 of file translator_sc.h.
    {
      return " ";
    }
trPageIndex() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 901 of file translator_sc.h.
    {
      return " ";
    }
trParameters() [1/2]
virtual QCString TranslatorSerbianCyrillic::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 547 of file translator_sc.h.
    { return ""; }
trParameters() [2/2]
virtual QCString TranslatorSerbianCyrillic::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 547 of file translator_sc.h.
    { return ""; }
trPostcondition() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 870 of file translator_sc.h.
    {
      return " ";
    }
trPostcondition() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 870 of file translator_sc.h.
    {
      return " ";
    }
trPrecondition() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 865 of file translator_sc.h.
    {
      return " ";
    }
trPrecondition() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 865 of file translator_sc.h.
    {
      return " ";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_sc.h.
    {
      return " ";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_sc.h.
    {
      return " ";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 664 of file translator_sc.h.
    { return " "; }
trPrivateMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 664 of file translator_sc.h.
    { return " "; }
trPrivateSlots() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 666 of file translator_sc.h.
    { return " "; }
trPrivateSlots() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 666 of file translator_sc.h.
    { return " "; }
trPrivateTypes() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 945 of file translator_sc.h.
    {
      return " ";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 945 of file translator_sc.h.
    {
      return " ";
    }
trProperties() [1/2]
virtual QCString TranslatorSerbianCyrillic::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1099 of file translator_sc.h.
    {
      return "";
    }
trProperties() [2/2]
virtual QCString TranslatorSerbianCyrillic::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1099 of file translator_sc.h.
    {
      return "";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1104 of file translator_sc.h.
    {
      return " ";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1104 of file translator_sc.h.
    {
      return " ";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorSerbianCyrillic::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_sc.h.
    {
      return " ";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorSerbianCyrillic::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_sc.h.
    {
      return " ";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 658 of file translator_sc.h.
    { return " "; }
trProtectedMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 658 of file translator_sc.h.
    { return " "; }
trProtectedSlots() [1/2]
virtual QCString TranslatorSerbianCyrillic::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 660 of file translator_sc.h.
    { return " "; }
trProtectedSlots() [2/2]
virtual QCString TranslatorSerbianCyrillic::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 660 of file translator_sc.h.
    { return " "; }
trProtectedTypes() [1/2]
virtual QCString TranslatorSerbianCyrillic::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 933 of file translator_sc.h.
    {
      return " ";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorSerbianCyrillic::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 933 of file translator_sc.h.
    {
      return " ";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 918 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 918 of file translator_sc.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 650 of file translator_sc.h.
    { return " "; }
trPublicMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 650 of file translator_sc.h.
    { return " "; }
trPublicSlots() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 652 of file translator_sc.h.
    { return " "; }
trPublicSlots() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 652 of file translator_sc.h.
    { return " "; }
trPublicTypes() [1/2]
virtual QCString TranslatorSerbianCyrillic::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 914 of file translator_sc.h.
    {
      return " ";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorSerbianCyrillic::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 914 of file translator_sc.h.
    {
      return " ";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorSerbianCyrillic::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 977 of file translator_sc.h.
    {
      return " ";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorSerbianCyrillic::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 977 of file translator_sc.h.
    {
      return " ";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorSerbianCyrillic::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 425 of file translator_sc.h.
    { return ""; }
trReferenceManual() [2/2]
virtual QCString TranslatorSerbianCyrillic::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 425 of file translator_sc.h.
    { return ""; }
trReferences() [1/2]
virtual QCString TranslatorSerbianCyrillic::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1306 of file translator_sc.h.
    {
      return "";
    }
trReferences() [2/2]
virtual QCString TranslatorSerbianCyrillic::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1306 of file translator_sc.h.
    {
      return "";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 715 of file translator_sc.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 715 of file translator_sc.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 723 of file translator_sc.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 723 of file translator_sc.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 588 of file translator_sc.h.
    { return " "; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 588 of file translator_sc.h.
    { return " "; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorSerbianCyrillic::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 93 of file translator_sc.h.
    { return " "; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorSerbianCyrillic::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 93 of file translator_sc.h.
    { return " "; }
trRelatedPages() [1/2]
virtual QCString TranslatorSerbianCyrillic::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 227 of file translator_sc.h.
    { return " "; }
trRelatedPages() [2/2]
virtual QCString TranslatorSerbianCyrillic::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 227 of file translator_sc.h.
    { return " "; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorSerbianCyrillic::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 341 of file translator_sc.h.
    { return " :"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorSerbianCyrillic::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 341 of file translator_sc.h.
    { return " :"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorSerbianCyrillic::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 97 of file translator_sc.h.
    { return "(.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorSerbianCyrillic::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 97 of file translator_sc.h.
    { return "(.)"; }
trRemarks() [1/2]
virtual QCString TranslatorSerbianCyrillic::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 981 of file translator_sc.h.
    {
      return "";
    }
trRemarks() [2/2]
virtual QCString TranslatorSerbianCyrillic::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 981 of file translator_sc.h.
    {
      return "";
    }
trReturns() [1/2]
virtual QCString TranslatorSerbianCyrillic::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 539 of file translator_sc.h.
    { return ""; }
trReturns() [2/2]
virtual QCString TranslatorSerbianCyrillic::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 539 of file translator_sc.h.
    { return ""; }
trReturnValues() [1/2]
virtual QCString TranslatorSerbianCyrillic::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 799 of file translator_sc.h.
    { return " "; }
trReturnValues() [2/2]
virtual QCString TranslatorSerbianCyrillic::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 799 of file translator_sc.h.
    { return " "; }
trRTFansicp() [1/2]
virtual QCString TranslatorSerbianCyrillic::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1190 of file translator_sc.h.
    {
      return "1251";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorSerbianCyrillic::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1190 of file translator_sc.h.
    {
      return "1251";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorSerbianCyrillic::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1199 of file translator_sc.h.
    {
      return "204";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorSerbianCyrillic::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1199 of file translator_sc.h.
    {
      return "204";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorSerbianCyrillic::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1205 of file translator_sc.h.
    {
      return "";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorSerbianCyrillic::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1205 of file translator_sc.h.
    {
      return "";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorSerbianCyrillic::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1338 of file translator_sc.h.
    {
      return "";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorSerbianCyrillic::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1338 of file translator_sc.h.
    {
      return "";
    }
trSearch() [1/2]
virtual QCString TranslatorSerbianCyrillic::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 235 of file translator_sc.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorSerbianCyrillic::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 235 of file translator_sc.h.
    { return ""; }
trSearchMatches() [1/2]
virtual QCString TranslatorSerbianCyrillic::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1482 of file translator_sc.h.
    {
      return ":";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorSerbianCyrillic::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1482 of file translator_sc.h.
    {
      return ":";
    }
trSearchResults() [1/2]
virtual QCString TranslatorSerbianCyrillic::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1451 of file translator_sc.h.
    {
      if (numDocuments==0)
      {
        return " , .";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> .";
      }
      else if (numDocuments==2)
      {
        return " <b></b> .";
      }
      else if (numDocuments==3)
      {
        return " <b>3</b> .";
      }
      else if (numDocuments==4)
      {
        return " <b>4</b> .";
      }
      else
      {
        return " <b>$num</b> . "
               " .";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorSerbianCyrillic::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1451 of file translator_sc.h.
    {
      if (numDocuments==0)
      {
        return " , .";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> .";
      }
      else if (numDocuments==2)
      {
        return " <b></b> .";
      }
      else if (numDocuments==3)
      {
        return " <b>3</b> .";
      }
      else if (numDocuments==4)
      {
        return " <b>4</b> .";
      }
      else
      {
        return " <b>$num</b> . "
               " .";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorSerbianCyrillic::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1439 of file translator_sc.h.
    {
      return " ";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorSerbianCyrillic::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1439 of file translator_sc.h.
    {
      return " ";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorSerbianCyrillic::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 543 of file translator_sc.h.
    { return ""; }
trSeeAlso() [2/2]
virtual QCString TranslatorSerbianCyrillic::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 543 of file translator_sc.h.
    { return ""; }
trSignals() [1/2]
virtual QCString TranslatorSerbianCyrillic::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 654 of file translator_sc.h.
    { return ""; }
trSignals() [2/2]
virtual QCString TranslatorSerbianCyrillic::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 654 of file translator_sc.h.
    { return ""; }
trSince() [1/2]
virtual QCString TranslatorSerbianCyrillic::trSince () [inline], [virtual]
Implements Translator.
Definition at line 994 of file translator_sc.h.
    {
      return "";
    }
trSince() [2/2]
virtual QCString TranslatorSerbianCyrillic::trSince () [inline], [virtual]
Implements Translator.
Definition at line 994 of file translator_sc.h.
    {
      return "";
    }
trSourceFile() [1/2]
virtual QCString TranslatorSerbianCyrillic::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1493 of file translator_sc.h.
    {
      return filename + " ";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorSerbianCyrillic::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1493 of file translator_sc.h.
    {
      return filename + " ";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorSerbianCyrillic::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1410 of file translator_sc.h.
    {
      return " ";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorSerbianCyrillic::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1410 of file translator_sc.h.
    {
      return " ";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorSerbianCyrillic::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1396 of file translator_sc.h.
    {
      return " ";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorSerbianCyrillic::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1396 of file translator_sc.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorSerbianCyrillic::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 953 of file translator_sc.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorSerbianCyrillic::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 953 of file translator_sc.h.
    {
      return " ";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 668 of file translator_sc.h.
    { return " "; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 668 of file translator_sc.h.
    { return " "; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorSerbianCyrillic::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 941 of file translator_sc.h.
    {
      return " ";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorSerbianCyrillic::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 941 of file translator_sc.h.
    {
      return " ";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 662 of file translator_sc.h.
    { return " "; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 662 of file translator_sc.h.
    { return " "; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorSerbianCyrillic::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 929 of file translator_sc.h.
    {
      return " ";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorSerbianCyrillic::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 929 of file translator_sc.h.
    {
      return " ";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 656 of file translator_sc.h.
    { return " "; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 656 of file translator_sc.h.
    { return " "; }
trSubprogram() [1/2]
virtual QCString TranslatorSerbianCyrillic::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1752 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorSerbianCyrillic::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1752 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1627 of file translator_sc.h.
    { return " /"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1627 of file translator_sc.h.
    { return " /"; }
trSubprograms() [1/2]
virtual QCString TranslatorSerbianCyrillic::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1621 of file translator_sc.h.
    { return "/"; }
trSubprograms() [2/2]
virtual QCString TranslatorSerbianCyrillic::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1621 of file translator_sc.h.
    { return "/"; }
trTest() [1/2]
virtual QCString TranslatorSerbianCyrillic::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1084 of file translator_sc.h.
    {
      return "";
    }
trTest() [2/2]
virtual QCString TranslatorSerbianCyrillic::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1084 of file translator_sc.h.
    {
      return "";
    }
trTestList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1089 of file translator_sc.h.
    {
      return " ";
    }
trTestList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1089 of file translator_sc.h.
    {
      return " ";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorSerbianCyrillic::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 142 of file translator_sc.h.
    { return " "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorSerbianCyrillic::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 142 of file translator_sc.h.
    { return " "; }
trTodo() [1/2]
virtual QCString TranslatorSerbianCyrillic::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 963 of file translator_sc.h.
    {
      return "";
    }
trTodo() [2/2]
virtual QCString TranslatorSerbianCyrillic::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 963 of file translator_sc.h.
    {
      return "";
    }
trTodoList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 968 of file translator_sc.h.
    {
      return " ";
    }
trTodoList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 968 of file translator_sc.h.
    {
      return " ";
    }
trType() [1/2]
virtual QCString TranslatorSerbianCyrillic::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1742 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorSerbianCyrillic::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1742 of file translator_sc.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorSerbianCyrillic::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1760 of file translator_sc.h.
    {
      return " ";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorSerbianCyrillic::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1760 of file translator_sc.h.
    {
      return " ";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 473 of file translator_sc.h.
    { return " "; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 473 of file translator_sc.h.
    { return " "; }
trTypedefs() [1/2]
virtual QCString TranslatorSerbianCyrillic::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 437 of file translator_sc.h.
    { return " "; }
trTypedefs() [2/2]
virtual QCString TranslatorSerbianCyrillic::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 437 of file translator_sc.h.
    { return " "; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1615 of file translator_sc.h.
    { return " "; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1615 of file translator_sc.h.
    { return " "; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorSerbianCyrillic::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 491 of file translator_sc.h.
    { return " "; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorSerbianCyrillic::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 491 of file translator_sc.h.
    { return " "; }
trVariables() [1/2]
virtual QCString TranslatorSerbianCyrillic::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 455 of file translator_sc.h.
    { return ""; }
trVariables() [2/2]
virtual QCString TranslatorSerbianCyrillic::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 455 of file translator_sc.h.
    { return ""; }
trVersion() [1/2]
virtual QCString TranslatorSerbianCyrillic::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 531 of file translator_sc.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorSerbianCyrillic::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 531 of file translator_sc.h.
    { return ""; }
trWarning() [1/2]
virtual QCString TranslatorSerbianCyrillic::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 527 of file translator_sc.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorSerbianCyrillic::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 527 of file translator_sc.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorSerbianCyrillic::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 674 of file translator_sc.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorSerbianCyrillic::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 674 of file translator_sc.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_sc.h
doxygen/src/translator_sc.h