Pedido Class Reference
Classe Pedido.
#include <Pedido.h>
Public Member Functions
Pedido ()
Default constructor da classe `Pedido`.
void setCodUc (const string &codUc)
Modifier do atributo `codUC`.
void setCodTurma (const string &codTurma)
Modifier do atributo `codTurma`.
void setCode (int code)
Modifier do atributo `code`.
const string & getCodUc () const
Accessor do atributo `codUC`.
const string & getCodTurma () const
Accessor do atributo `codTurma`.
int getCode () const
Accessor do atributo `code`.
Private Attributes
int code
string codTurma
string codUC
Detailed Description
Classe Pedido.
Classe utilizada para criar um objeto `Pedido` que contém x parâmetros, de forma a organizar e armazenar a informação de forma mais elegante.
Definition at line 13 of file Pedido.h.
Constructor & Destructor Documentation
Pedido()
Pedido::Pedido ()
Default constructor da classe `Pedido`.
Complexidade O(1).
Definition at line 4 of file Pedido.cpp.
{}
Member Function Documentation
getCode()
int Pedido::getCode () const
Accessor do atributo `code`.
Complexidade O(1).
Returns
Código UP.
Definition at line 6 of file Pedido.cpp.
                          {
    return code;
}
References code.
Referenced by GestaoHor::addStudentUCClass(), GestaoHor::processPedidos(), and GestaoHor::removeStudentUCClass().
getCodTurma()
const string & Pedido::getCodTurma () const
Accessor do atributo `codTurma`.
Complexidade O(1).
Returns
Código da turma.
Definition at line 10 of file Pedido.cpp.
                                        {
    return codTurma;
}
References codTurma.
Referenced by GestaoHor::addStudentUCClass(), and GestaoHor::removeStudentUCClass().
getCodUc()
const string & Pedido::getCodUc () const
Accessor do atributo `codUC`.
Complexidade O(1)
Returns
Código UC.
Definition at line 14 of file Pedido.cpp.
                                     {
    return codUC;
}
References codUC.
Referenced by GestaoHor::addStudentUCClass(), and GestaoHor::removeStudentUCClass().
setCode()
void Pedido::setCode (int code)
Modifier do atributo `code`.
Complexidade O(1).
Parameters
code Código UP.
Definition at line 18 of file Pedido.cpp.
                             {
    Pedido::code = code;
}
References code.
Referenced by Menu::alterarMenu().
setCodTurma()
void Pedido::setCodTurma (const string & codTurma)
Modifier do atributo `codTurma`.
Complexidade O(1).
Parameters
codTurma Código da turma.
Definition at line 22 of file Pedido.cpp.
                                               {
    Pedido::codTurma = codTurma;
}
References codTurma.
Referenced by Menu::alterarMenu().
setCodUc()
void Pedido::setCodUc (const string & codUc)
Modifier do atributo `codUC`.
Complexidade O(1).
Parameters
codUc Código da UC.
Definition at line 26 of file Pedido.cpp.
                                         {
    codUC = codUc;
}
References codUC.
Referenced by Menu::alterarMenu().
Member Data Documentation
code
int Pedido::code [private]
Definition at line 15 of file Pedido.h.
Referenced by getCode(), and setCode().
codTurma
string Pedido::codTurma [private]
Definition at line 16 of file Pedido.h.
Referenced by getCodTurma(), and setCodTurma().
codUC
string Pedido::codUC [private]
Definition at line 17 of file Pedido.h.
Referenced by getCodUc(), and setCodUc().
The documentation for this class was generated from the following files:
Pedido.h
Pedido.cpp