LocalToc Class Reference
#include <types.h>
Public Types
enum Type {
None = 0
, Html = 0
, Latex = 1
, Xml = 2
,
Docbook = 3
, numTocTypes = 4
, None = 0
, Html = 0
,
Latex = 1
, Xml = 2
, Docbook = 3
, numTocTypes = 4
 }
enum Type {
None = 0
, Html = 0
, Latex = 1
, Xml = 2
,
Docbook = 3
, numTocTypes = 4
, None = 0
, Html = 0
,
Latex = 1
, Xml = 2
, Docbook = 3
, numTocTypes = 4
 }
Public Member Functions
LocalToc ()
void enableHtml (int level)
void enableLatex (int level)
void enableXml (int level)
void enableDocbook (int level)
bool isHtmlEnabled () const
bool isLatexEnabled () const
bool isXmlEnabled () const
bool isDocbookEnabled () const
bool nothingEnabled () const
int htmlLevel () const
int latexLevel () const
int xmlLevel () const
int docbookLevel () const
int mask () const
LocalToc ()
void enableHtml (int level)
void enableLatex (int level)
void enableXml (int level)
void enableDocbook (int level)
bool isHtmlEnabled () const
bool isLatexEnabled () const
bool isXmlEnabled () const
bool isDocbookEnabled () const
bool nothingEnabled () const
int htmlLevel () const
int latexLevel () const
int xmlLevel () const
int docbookLevel () const
int mask () const
Private Attributes
int m_mask
int m_level [numTocTypes]
Detailed Description
Definition at line 304 of file types.h.
Member Enumeration Documentation
Type [1/2]
enum LocalToc::Type
Enumerator
None
Html
Latex
Xml
Docbook
numTocTypes
None
Html
Latex
Xml
Docbook
numTocTypes
Definition at line 307 of file types.h.
              {
      None = 0, // initial value
      Html = 0, // index / also to be used as bit position in mask (1 << Html)
      Latex = 1, // ...
      Xml = 2, // ...
      Docbook = 3, // ...
      numTocTypes = 4 // number of enum values
    };
Type [2/2]
enum LocalToc::Type
Enumerator
None
Html
Latex
Xml
Docbook
numTocTypes
None
Html
Latex
Xml
Docbook
numTocTypes
Definition at line 307 of file types.h.
              {
      None = 0, // initial value
      Html = 0, // index / also to be used as bit position in mask (1 << Html)
      Latex = 1, // ...
      Xml = 2, // ...
      Docbook = 3, // ...
      numTocTypes = 4 // number of enum values
    };
Constructor & Destructor Documentation
LocalToc() [1/2]
LocalToc::LocalToc () [inline]
Definition at line 315 of file types.h.
: m_mask(None) { memset(m_level,0,sizeof(m_level)); }
References m_level.
LocalToc() [2/2]
LocalToc::LocalToc () [inline]
Definition at line 315 of file types.h.
: m_mask(None) { memset(m_level,0,sizeof(m_level)); }
References m_level.
Member Function Documentation
docbookLevel() [1/2]
int LocalToc::docbookLevel () const [inline]
Definition at line 348 of file types.h.
{ return m_level[Docbook]; }
References Docbook, and m_level.
Referenced by DefinitionImpl::writeToc().
docbookLevel() [2/2]
int LocalToc::docbookLevel () const [inline]
Definition at line 348 of file types.h.
{ return m_level[Docbook]; }
References Docbook, and m_level.
enableDocbook() [1/2]
void LocalToc::enableDocbook (int level) [inline]
Definition at line 333 of file types.h.
    {
      m_mask|=(1<<Docbook);
      m_level[Docbook]=level;
    }
References Docbook, level, m_level, and m_mask.
enableDocbook() [2/2]
void LocalToc::enableDocbook (int level) [inline]
Definition at line 333 of file types.h.
    {
      m_mask|=(1<<Docbook);
      m_level[Docbook]=level;
    }
References Docbook, level, m_level, and m_mask.
enableHtml() [1/2]
void LocalToc::enableHtml (int level) [inline]
Definition at line 318 of file types.h.
    {
      m_mask|=(1<<Html);
      m_level[Html]=level;
    }
References Html, level, m_level, and m_mask.
enableHtml() [2/2]
void LocalToc::enableHtml (int level) [inline]
Definition at line 318 of file types.h.
    {
      m_mask|=(1<<Html);
      m_level[Html]=level;
    }
References Html, level, m_level, and m_mask.
enableLatex() [1/2]
void LocalToc::enableLatex (int level) [inline]
Definition at line 323 of file types.h.
    {
      m_mask|=(1<<Latex);
      m_level[Latex]=level;
    }
References Latex, level, m_level, and m_mask.
enableLatex() [2/2]
void LocalToc::enableLatex (int level) [inline]
Definition at line 323 of file types.h.
    {
      m_mask|=(1<<Latex);
      m_level[Latex]=level;
    }
References Latex, level, m_level, and m_mask.
enableXml() [1/2]
void LocalToc::enableXml (int level) [inline]
Definition at line 328 of file types.h.
    {
      m_mask|=(1<<Xml);
      m_level[Xml]=level;
    }
References level, m_level, m_mask, and Xml.
enableXml() [2/2]
void LocalToc::enableXml (int level) [inline]
Definition at line 328 of file types.h.
    {
      m_mask|=(1<<Xml);
      m_level[Xml]=level;
    }
References level, m_level, m_mask, and Xml.
htmlLevel() [1/2]
int LocalToc::htmlLevel () const [inline]
Definition at line 345 of file types.h.
{ return m_level[Html]; }
References Html, and m_level.
Referenced by DefinitionImpl::writeToc().
htmlLevel() [2/2]
int LocalToc::htmlLevel () const [inline]
Definition at line 345 of file types.h.
{ return m_level[Html]; }
References Html, and m_level.
isDocbookEnabled() [1/2]
bool LocalToc::isDocbookEnabled () const [inline]
Definition at line 343 of file types.h.
{ return (m_mask & (1<<Docbook))!=0; }
References Docbook, and m_mask.
Referenced by PageDefImpl::writeDocumentation(), and DefinitionImpl::writeToc().
isDocbookEnabled() [2/2]
bool LocalToc::isDocbookEnabled () const [inline]
Definition at line 343 of file types.h.
{ return (m_mask & (1<<Docbook))!=0; }
References Docbook, and m_mask.
isHtmlEnabled() [1/2]
bool LocalToc::isHtmlEnabled () const [inline]
Definition at line 340 of file types.h.
{ return (m_mask & (1<<Html))!=0; }
References Html, and m_mask.
Referenced by PageDefImpl::writeDocumentation(), and DefinitionImpl::writeToc().
isHtmlEnabled() [2/2]
bool LocalToc::isHtmlEnabled () const [inline]
Definition at line 340 of file types.h.
{ return (m_mask & (1<<Html))!=0; }
References Html, and m_mask.
isLatexEnabled() [1/2]
bool LocalToc::isLatexEnabled () const [inline]
Definition at line 341 of file types.h.
{ return (m_mask & (1<<Latex))!=0; }
References Latex, and m_mask.
Referenced by PageDefImpl::writeDocumentation(), and DefinitionImpl::writeToc().
isLatexEnabled() [2/2]
bool LocalToc::isLatexEnabled () const [inline]
Definition at line 341 of file types.h.
{ return (m_mask & (1<<Latex))!=0; }
References Latex, and m_mask.
isXmlEnabled() [1/2]
bool LocalToc::isXmlEnabled () const [inline]
Definition at line 342 of file types.h.
{ return (m_mask & (1<<Xml))!=0; }
References m_mask, and Xml.
Referenced by generateXMLForPage().
isXmlEnabled() [2/2]
bool LocalToc::isXmlEnabled () const [inline]
Definition at line 342 of file types.h.
{ return (m_mask & (1<<Xml))!=0; }
References m_mask, and Xml.
latexLevel() [1/2]
int LocalToc::latexLevel () const [inline]
Definition at line 346 of file types.h.
{ return m_level[Latex]; }
References Latex, and m_level.
Referenced by DefinitionImpl::writeToc().
latexLevel() [2/2]
int LocalToc::latexLevel () const [inline]
Definition at line 346 of file types.h.
{ return m_level[Latex]; }
References Latex, and m_level.
mask() [1/2]
int LocalToc::mask () const [inline]
Definition at line 349 of file types.h.
{ return m_mask; }
References m_mask.
mask() [2/2]
int LocalToc::mask () const [inline]
Definition at line 349 of file types.h.
{ return m_mask; }
References m_mask.
nothingEnabled() [1/2]
bool LocalToc::nothingEnabled () const [inline]
Definition at line 344 of file types.h.
{ return m_mask == None; }
References m_mask, and None.
nothingEnabled() [2/2]
bool LocalToc::nothingEnabled () const [inline]
Definition at line 344 of file types.h.
{ return m_mask == None; }
References m_mask, and None.
xmlLevel() [1/2]
int LocalToc::xmlLevel () const [inline]
Definition at line 347 of file types.h.
{ return m_level[Xml]; }
References m_level, and Xml.
Referenced by generateXMLForPage().
xmlLevel() [2/2]
int LocalToc::xmlLevel () const [inline]
Definition at line 347 of file types.h.
{ return m_level[Xml]; }
References m_level, and Xml.
Member Data Documentation
m_level
int LocalToc::m_level [private]
Definition at line 353 of file types.h.
Referenced by docbookLevel(), enableDocbook(), enableHtml(), enableLatex(), enableXml(), htmlLevel(), latexLevel(), LocalToc(), and xmlLevel().
m_mask
int LocalToc::m_mask [private]
Definition at line 352 of file types.h.
Referenced by enableDocbook(), enableHtml(), enableLatex(), enableXml(), isDocbookEnabled(), isHtmlEnabled(), isLatexEnabled(), isXmlEnabled(), mask(), and nothingEnabled().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/types.h
doxygen/src/types.h