reg::PToken Class Reference
Public Types
enum class Kind : uint16_t {
End = 0x0000
, WhiteSpace = 0x1001
, Digit = 0x1002
, Alpha = 0x1003
,
AlphaNum = 0x1004
, CharClass = 0x2001
, NegCharClass = 0x2002
, BeginOfLine = 0x4001
,
EndOfLine = 0x4002
, BeginOfWord = 0x4003
, EndOfWord = 0x4004
, BeginCapture = 0x4005
,
EndCapture = 0x4006
, Any = 0x4007
, Star = 0x4008
, Optional = 0x4009
,
Character = 0x8000
, End = 0x0000
, WhiteSpace = 0x1001
, Digit = 0x1002
,
Alpha = 0x1003
, AlphaNum = 0x1004
, CharClass = 0x2001
, NegCharClass = 0x2002
,
BeginOfLine = 0x4001
, EndOfLine = 0x4002
, BeginOfWord = 0x4003
, EndOfWord = 0x4004
,
BeginCapture = 0x4005
, EndCapture = 0x4006
, Any = 0x4007
, Star = 0x4008
,
Optional = 0x4009
, Character = 0x8000
 }
enum class Kind : uint16_t {
End = 0x0000
, WhiteSpace = 0x1001
, Digit = 0x1002
, Alpha = 0x1003
,
AlphaNum = 0x1004
, CharClass = 0x2001
, NegCharClass = 0x2002
, BeginOfLine = 0x4001
,
EndOfLine = 0x4002
, BeginOfWord = 0x4003
, EndOfWord = 0x4004
, BeginCapture = 0x4005
,
EndCapture = 0x4006
, Any = 0x4007
, Star = 0x4008
, Optional = 0x4009
,
Character = 0x8000
, End = 0x0000
, WhiteSpace = 0x1001
, Digit = 0x1002
,
Alpha = 0x1003
, AlphaNum = 0x1004
, CharClass = 0x2001
, NegCharClass = 0x2002
,
BeginOfLine = 0x4001
, EndOfLine = 0x4002
, BeginOfWord = 0x4003
, EndOfWord = 0x4004
,
BeginCapture = 0x4005
, EndCapture = 0x4006
, Any = 0x4007
, Star = 0x4008
,
Optional = 0x4009
, Character = 0x8000
 }
Public Member Functions
const char * kindStr () const
PToken ()
PToken (Kind k)
PToken (char c)
PToken (uint16_t v)
PToken (uint16_t from, uint16_t to)
void setValue (uint16_t value)
Kind kind () const
uint16_t from () const
uint16_t to () const
uint16_t value () const
char asciiValue () const
bool isRange () const
bool isCharClass () const
const char * kindStr () const
PToken ()
PToken (Kind k)
PToken (char c)
PToken (uint16_t v)
PToken (uint16_t from, uint16_t to)
void setValue (uint16_t value)
Kind kind () const
uint16_t from () const
uint16_t to () const
uint16_t value () const
char asciiValue () const
bool isRange () const
bool isCharClass () const
Private Attributes
uint32_t m_rep
Detailed Description
Class representing a token in the compiled regular expression token stream. A token has a kind and an optional value whose meaning depends on the kind. It is also possible to store a (from,to) character range in a token.
Definition at line 58 of file regex.cpp.
Member Enumeration Documentation
Kind [1/2]
enum class reg::PToken::Kind : uint16_t [strong]
The kind of token.
Ranges per bit mask:
0x00FF from part of a range, except for 0x0000 which is the End marker
0x1FFF built-in ranges
0x2FFF user defined ranges
0x4FFF special operations
0x8000 literal character
Enumerator
End
WhiteSpace
Digit
Alpha
AlphaNum
CharClass
NegCharClass
BeginOfLine
EndOfLine
BeginOfWord
EndOfWord
BeginCapture
EndCapture
Any
Star
Optional
Character
End
WhiteSpace
Digit
Alpha
AlphaNum
CharClass
NegCharClass
BeginOfLine
EndOfLine
BeginOfWord
EndOfWord
BeginCapture
EndCapture
Any
Star
Optional
Character
Definition at line 70 of file regex.cpp.
    {
      End = 0x0000,
      WhiteSpace = 0x1001, // \s range [ \t\r\n]
      Digit = 0x1002, // \d range [0-9]
      Alpha = 0x1003, // \a range [a-z_A-Z\x80-\xFF]
      AlphaNum = 0x1004, // \w range [a-Z_A-Z0-9\x80-\xFF]
      CharClass = 0x2001, // []
      NegCharClass = 0x2002, // [^]
      BeginOfLine = 0x4001, // ^
      EndOfLine = 0x4002, // $
      BeginOfWord = 0x4003, // \<
      EndOfWord = 0x4004, // \>
      BeginCapture = 0x4005, // (
      EndCapture = 0x4006, //)
      Any = 0x4007, // .
      Star = 0x4008, // *
      Optional = 0x4009, // ?
      Character = 0x8000 // c
    };
Kind [2/2]
enum class reg::PToken::Kind : uint16_t [strong]
The kind of token.
Ranges per bit mask:
0x00FF from part of a range, except for 0x0000 which is the End marker
0x1FFF built-in ranges
0x2FFF user defined ranges
0x4FFF special operations
0x8000 literal character
Enumerator
End
WhiteSpace
Digit
Alpha
AlphaNum
CharClass
NegCharClass
BeginOfLine
EndOfLine
BeginOfWord
EndOfWord
BeginCapture
EndCapture
Any
Star
Optional
Character
End
WhiteSpace
Digit
Alpha
AlphaNum
CharClass
NegCharClass
BeginOfLine
EndOfLine
BeginOfWord
EndOfWord
BeginCapture
EndCapture
Any
Star
Optional
Character
Definition at line 70 of file regex.cpp.
    {
      End = 0x0000,
      WhiteSpace = 0x1001, // \s range [ \t\r\n]
      Digit = 0x1002, // \d range [0-9]
      Alpha = 0x1003, // \a range [a-z_A-Z\x80-\xFF]
      AlphaNum = 0x1004, // \w range [a-Z_A-Z0-9\x80-\xFF]
      CharClass = 0x2001, // []
      NegCharClass = 0x2002, // [^]
      BeginOfLine = 0x4001, // ^
      EndOfLine = 0x4002, // $
      BeginOfWord = 0x4003, // \<
      EndOfWord = 0x4004, // \>
      BeginCapture = 0x4005, // (
      EndCapture = 0x4006, //)
      Any = 0x4007, // .
      Star = 0x4008, // *
      Optional = 0x4009, // ?
      Character = 0x8000 // c
    };
Constructor & Destructor Documentation
PToken() [1/10]
reg::PToken::PToken () [inline]
Creates a token of kind 'End'
Definition at line 124 of file regex.cpp.
: m_rep(0) {}
PToken() [2/10]
reg::PToken::PToken (Kind k) [inline], [explicit]
Creates a token of the given kind k
Definition at line 127 of file regex.cpp.
: m_rep(static_cast<uint32_t>(k)<<16) {}
PToken() [3/10]
reg::PToken::PToken (char c) [inline]
Create a token for an ASCII character
Definition at line 130 of file regex.cpp.
                               : m_rep((static_cast<uint32_t>(Kind::Character)<<16) |
                                        static_cast<uint32_t>(c)) {}
PToken() [4/10]
reg::PToken::PToken (uint16_t v) [inline]
Create a token for a byte of an UTF-8 character
Definition at line 134 of file regex.cpp.
                               : m_rep((static_cast<uint32_t>(Kind::Character)<<16) |
                                        static_cast<uint32_t>(v)) {}
PToken() [5/10]
reg::PToken::PToken (uint16_t from, uint16_t to) [inline]
Create a token representing a range from one character from to another character to
Definition at line 138 of file regex.cpp.
: m_rep(static_cast<uint32_t>(from)<<16 | to) {}
PToken() [6/10]
reg::PToken::PToken () [inline]
Creates a token of kind 'End'
Definition at line 124 of file regex.cpp.
: m_rep(0) {}
PToken() [7/10]
reg::PToken::PToken (Kind k) [inline], [explicit]
Creates a token of the given kind k
Definition at line 127 of file regex.cpp.
: m_rep(static_cast<uint32_t>(k)<<16) {}
PToken() [8/10]
reg::PToken::PToken (char c) [inline]
Create a token for an ASCII character
Definition at line 130 of file regex.cpp.
                               : m_rep((static_cast<uint32_t>(Kind::Character)<<16) |
                                        static_cast<uint32_t>(c)) {}
PToken() [9/10]
reg::PToken::PToken (uint16_t v) [inline]
Create a token for a byte of an UTF-8 character
Definition at line 134 of file regex.cpp.
                               : m_rep((static_cast<uint32_t>(Kind::Character)<<16) |
                                        static_cast<uint32_t>(v)) {}
PToken() [10/10]
reg::PToken::PToken (uint16_t from, uint16_t to) [inline]
Create a token representing a range from one character from to another character to
Definition at line 138 of file regex.cpp.
: m_rep(static_cast<uint32_t>(from)<<16 | to) {}
Member Function Documentation
asciiValue() [1/2]
char reg::PToken::asciiValue () const [inline]
Returns the value for this token as a ASCII character
Definition at line 156 of file regex.cpp.
{ return static_cast<char>(m_rep); }
References m_rep.
Referenced by reg::Ex::Private::compile(), reg::Ex::match(), and reg::Ex::Private::matchAt().
asciiValue() [2/2]
char reg::PToken::asciiValue () const [inline]
Returns the value for this token as a ASCII character
Definition at line 156 of file regex.cpp.
{ return static_cast<char>(m_rep); }
References m_rep.
from() [1/2]
uint16_t reg::PToken::from () const [inline]
Returns the 'from' part of the character range. Only valid if this token represents a range
Definition at line 147 of file regex.cpp.
{ return m_rep>>16; }
References m_rep.
Referenced by isRange(), and reg::Ex::Private::matchAt().
from() [2/2]
uint16_t reg::PToken::from () const [inline]
Returns the 'from' part of the character range. Only valid if this token represents a range
Definition at line 147 of file regex.cpp.
{ return m_rep>>16; }
References m_rep.
isCharClass() [1/2]
bool reg::PToken::isCharClass () const [inline]
Returns true iff this token is a positive or negative character class
Definition at line 162 of file regex.cpp.
{ return kind()==Kind::CharClass || kind()==Kind::NegCharClass; }
References CharClass, kind(), and NegCharClass.
Referenced by reg::Ex::Private::matchAt().
isCharClass() [2/2]
bool reg::PToken::isCharClass () const [inline]
Returns true iff this token is a positive or negative character class
Definition at line 162 of file regex.cpp.
{ return kind()==Kind::CharClass || kind()==Kind::NegCharClass; }
References CharClass, kind(), and NegCharClass.
isRange() [1/2]
bool reg::PToken::isRange () const [inline]
Returns true iff this token represents a range of characters
Definition at line 159 of file regex.cpp.
{ return m_rep!=0 && from()<=to(); }
References from(), m_rep, and to().
isRange() [2/2]
bool reg::PToken::isRange () const [inline]
Returns true iff this token represents a range of characters
Definition at line 159 of file regex.cpp.
{ return m_rep!=0 && from()<=to(); }
References from(), m_rep, and to().
kind() [1/2]
Kind reg::PToken::kind () const [inline]
Returns the kind of the token
Definition at line 144 of file regex.cpp.
{ return static_cast<Kind>(m_rep>>16); }
References m_rep.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), reg::Ex::Private::compile(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), isCharClass(), reg::Ex::match(), reg::Ex::Private::matchAt(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
kind() [2/2]
Kind reg::PToken::kind () const [inline]
Returns the kind of the token
Definition at line 144 of file regex.cpp.
{ return static_cast<Kind>(m_rep>>16); }
References m_rep.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
kindStr() [1/2]
const char * reg::PToken::kindStr () const [inline]
returns a string representation of the tokens kind (useful for debugging).
Definition at line 92 of file regex.cpp.
    {
      if ((m_rep>>16)>=0x1000 || m_rep==0)
      {
        switch(static_cast<Kind>((m_rep>>16)))
        {
          case Kind::End: return "End";
          case Kind::Alpha: return "Alpha";
          case Kind::AlphaNum: return "AlphaNum";
          case Kind::WhiteSpace: return "WhiteSpace";
          case Kind::Digit: return "Digit";
          case Kind::CharClass: return "CharClass";
          case Kind::NegCharClass: return "NegCharClass";
          case Kind::Character: return "Character";
          case Kind::BeginOfLine: return "BeginOfLine";
          case Kind::EndOfLine: return "EndOfLine";
          case Kind::BeginOfWord: return "BeginOfWord";
          case Kind::EndOfWord: return "EndOfWord";
          case Kind::BeginCapture: return "BeginCapture";
          case Kind::EndCapture: return "EndCapture";
          case Kind::Any: return "Any";
          case Kind::Star: return "Star";
          case Kind::Optional: return "Optional";
        }
      }
      else
      {
        return "Range";
      }
    }
References Alpha, AlphaNum, Any, BeginCapture, BeginOfLine, BeginOfWord, Character, CharClass, Digit, End, EndCapture, EndOfLine, EndOfWord, m_rep, NegCharClass, Optional, Star, and WhiteSpace.
Referenced by reg::Ex::Private::matchAt().
kindStr() [2/2]
const char * reg::PToken::kindStr () const [inline]
returns a string representation of the tokens kind (useful for debugging).
Definition at line 92 of file regex.cpp.
    {
      if ((m_rep>>16)>=0x1000 || m_rep==0)
      {
        switch(static_cast<Kind>((m_rep>>16)))
        {
          case Kind::End: return "End";
          case Kind::Alpha: return "Alpha";
          case Kind::AlphaNum: return "AlphaNum";
          case Kind::WhiteSpace: return "WhiteSpace";
          case Kind::Digit: return "Digit";
          case Kind::CharClass: return "CharClass";
          case Kind::NegCharClass: return "NegCharClass";
          case Kind::Character: return "Character";
          case Kind::BeginOfLine: return "BeginOfLine";
          case Kind::EndOfLine: return "EndOfLine";
          case Kind::BeginOfWord: return "BeginOfWord";
          case Kind::EndOfWord: return "EndOfWord";
          case Kind::BeginCapture: return "BeginCapture";
          case Kind::EndCapture: return "EndCapture";
          case Kind::Any: return "Any";
          case Kind::Star: return "Star";
          case Kind::Optional: return "Optional";
        }
      }
      else
      {
        return "Range";
      }
    }
References Alpha, AlphaNum, Any, BeginCapture, BeginOfLine, BeginOfWord, Character, CharClass, Digit, End, EndCapture, EndOfLine, EndOfWord, m_rep, NegCharClass, Optional, Star, and WhiteSpace.
setValue() [1/2]
void reg::PToken::setValue (uint16_t value) [inline]
Sets the value for a token
Definition at line 141 of file regex.cpp.
{ m_rep = (m_rep & 0xFFFF0000) | value; }
References m_rep, and value().
setValue() [2/2]
void reg::PToken::setValue (uint16_t value) [inline]
Sets the value for a token
Definition at line 141 of file regex.cpp.
{ m_rep = (m_rep & 0xFFFF0000) | value; }
References m_rep, and value().
to() [1/2]
uint16_t reg::PToken::to () const [inline]
Returns the 'to' part of the character range. Only valid if this token represents a range
Definition at line 150 of file regex.cpp.
{ return m_rep & 0xFFFF; }
References m_rep.
Referenced by isRange(), and reg::Ex::Private::matchAt().
to() [2/2]
uint16_t reg::PToken::to () const [inline]
Returns the 'to' part of the character range. Only valid if this token represents a range
Definition at line 150 of file regex.cpp.
{ return m_rep & 0xFFFF; }
References m_rep.
value() [1/2]
uint16_t reg::PToken::value () const [inline]
Returns the value for this token
Definition at line 153 of file regex.cpp.
{ return m_rep & 0xFFFF; }
References m_rep.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), reg::Ex::Private::compile(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), reg::Ex::Private::matchAt(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), setValue(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), and doxmlparser.index.MixedContainer::to_etree_simple().
value() [2/2]
uint16_t reg::PToken::value () const [inline]
Returns the value for this token
Definition at line 153 of file regex.cpp.
{ return m_rep & 0xFFFF; }
References m_rep.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), and doxmlparser.index.MixedContainer::to_etree_simple().
Member Data Documentation
m_rep
uint32_t reg::PToken::m_rep [private]
Definition at line 165 of file regex.cpp.
Referenced by asciiValue(), from(), isRange(), kind(), kindStr(), setValue(), to(), and value().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/regex.cpp
doxygen/src/regex.cpp