SearchIndexExternal Class Reference
#include <searchindex.h>
Classes
struct SearchDocEntry
Public Member Functions
SearchIndexExternal ()
void setCurrentDoc (const Definition *ctx, const QCString &anchor, bool isSourceFile)
void addWord (const QCString &word, bool hiPriority)
void write (const QCString &file)
SearchIndexExternal ()
void setCurrentDoc (const Definition *ctx, const QCString &anchor, bool isSourceFile)
void addWord (const QCString &word, bool hiPriority)
void write (const QCString &file)
Private Attributes
std::map< std::string, SearchDocEntry > m_docEntries
SearchDocEntry * m_current = 0
Detailed Description
Writes search index that should be used with an externally provided search engine, e.g. doxyindexer and doxysearch.cgi.
Definition at line 136 of file searchindex.h.
Constructor & Destructor Documentation
SearchIndexExternal() [1/2]
SearchIndexExternal::SearchIndexExternal ()
Definition at line 404 of file searchindex.cpp.
{
}
SearchIndexExternal() [2/2]
SearchIndexExternal::SearchIndexExternal ()
Member Function Documentation
addWord() [1/2]
void SearchIndexExternal::addWord (const QCString & word, bool hiPriority)
Definition at line 491 of file searchindex.cpp.
{
  if (word.isEmpty() || !isId(word[0]) || m_current==0) return;
  GrowBuf *pText = hiPriority ? &m_current->importantText : &m_current->normalText;
  if (pText->getPos()>0) pText->addChar(' ');
  pText->addStr(word);
  //printf("addWord %s\n",word);
}
References GrowBuf::addChar(), GrowBuf::addStr(), GrowBuf::getPos(), isId(), and word.
addWord() [2/2]
void SearchIndexExternal::addWord (const QCString & word, bool hiPriority)
setCurrentDoc() [1/2]
void SearchIndexExternal::setCurrentDoc (const Definition * ctx, const QCString & anchor, bool isSourceFile)
Definition at line 465 of file searchindex.cpp.
{
  QCString extId = stripPath(Config_getString(EXTERNAL_SEARCH_ID));
  QCString baseName = isSourceFile ? (toFileDef(ctx))->getSourceFileBase() : ctx->getOutputFileBase();
  QCString url = addHtmlExtensionIfMissing(baseName);
  if (!anchor.isEmpty()) url+=QCString("#")+anchor;
  QCString key = extId+";"+url;
  auto it = m_docEntries.find(key.str());
  if (it == m_docEntries.end())
  {
    SearchDocEntry e;
    e.type = isSourceFile ? QCString("source") : definitionToName(ctx);
    e.name = ctx->qualifiedName();
    if (ctx->definitionType()==Definition::TypeMember)
    {
      e.args = (toMemberDef(ctx))->argsString();
    }
    e.extId = extId;
    e.url = url;
    it = m_docEntries.insert({key.str(),e}).first;
    //printf("searchIndexExt %s : %s\n",qPrint(e->name),qPrint(e->url));
  }
  m_current = &it->second;
}
References addHtmlExtensionIfMissing(), Config_getString, definitionToName(), Definition::definitionType(), e, Definition::getOutputFileBase(), QCString::isEmpty(), Definition::qualifiedName(), QCString::str(), stripPath(), toFileDef(), toMemberDef(), Definition::TypeMember, and setup::url.
setCurrentDoc() [2/2]
void SearchIndexExternal::setCurrentDoc (const Definition * ctx, const QCString & anchor, bool isSourceFile)
write() [1/2]
void SearchIndexExternal::write (const QCString & file)
Definition at line 500 of file searchindex.cpp.
{
  std::ofstream t(fileName.str(),std::ofstream::out | std::ofstream::binary);
  if (t.is_open())
  {
    t << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
    t << "<add>\n";
    for (auto &kv : m_docEntries)
    {
      SearchDocEntry &doc = kv.second;
      doc.normalText.addChar(0); // make sure buffer ends with a 0 terminator
      doc.importantText.addChar(0); // make sure buffer ends with a 0 terminator
      t << " <doc>\n";
      t << " <field name=\"type\">" << doc.type << "</field>\n";
      t << " <field name=\"name\">" << convertToXML(doc.name) << "</field>\n";
      if (!doc.args.isEmpty())
      {
        t << " <field name=\"args\">" << convertToXML(doc.args) << "</field>\n";
      }
      if (!doc.extId.isEmpty())
      {
        t << " <field name=\"tag\">" << convertToXML(doc.extId) << "</field>\n";
      }
      t << " <field name=\"url\">" << convertToXML(doc.url) << "</field>\n";
      t << " <field name=\"keywords\">" << convertToXML(doc.importantText.get()) << "</field>\n";
      t << " <field name=\"text\">" << convertToXML(doc.normalText.get()) << "</field>\n";
      t << " </doc>\n";
    }
    t << "</add>\n";
  }
  else
  {
    err("Failed to open file %s for writing!\n",qPrint(fileName));
  }
}
References GrowBuf::addChar(), SearchIndexExternal::SearchDocEntry::args, convertToXML(), err(), SearchIndexExternal::SearchDocEntry::extId, GrowBuf::get(), SearchIndexExternal::SearchDocEntry::importantText, QCString::isEmpty(), SearchIndexExternal::SearchDocEntry::name, SearchIndexExternal::SearchDocEntry::normalText, out, qPrint(), QCString::str(), SearchIndexExternal::SearchDocEntry::type, and SearchIndexExternal::SearchDocEntry::url.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_write(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_write().
write() [2/2]
void SearchIndexExternal::write (const QCString & file)
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_write(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_write().
Member Data Documentation
m_current
SearchDocEntry * SearchIndexExternal::m_current = 0 [private]
Definition at line 156 of file searchindex.h.
m_docEntries
std::map< std::string, SearchDocEntry > SearchIndexExternal::m_docEntries [private]
Definition at line 155 of file searchindex.h.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/searchindex.h
doxygen/src/searchindex.h
doxygen/build/doxygen/src/searchindex.cpp
doxygen/src/searchindex.cpp