DocTokenizer Class Reference
#include <doctokenizer.h>
Classes
struct Private
Public Member Functions
DocTokenizer ()
~DocTokenizer ()
TokenInfo * token ()
TokenInfo * newToken ()
void replaceToken (TokenInfo *newToken)
void setLineNr (int lineno)
int getLineNr (void)
void findSections (const QCString &input, const Definition *d, const QCString &fileName)
void init (const char *input, const QCString &fileName, bool markdownSupport)
void cleanup ()
void pushContext ()
bool popContext ()
int lex ()
void unputString (const QCString &tag)
void setStatePara ()
void setStateTitle ()
void setStateTitleAttrValue ()
void setStateCode ()
void setStateICode ()
void setStateXmlCode ()
void setStateHtmlOnly ()
void setStateManOnly ()
void setStateLatexOnly ()
void setStateXmlOnly ()
void setStateDbOnly ()
void setStateRtfOnly ()
void setStateVerbatim ()
void setStateIVerbatim ()
void setStateILiteral ()
void setStateILiteralOpt ()
void setStateDot ()
void setStateMsc ()
void setStateParam ()
void setStateXRefItem ()
void setStateFile ()
void setStatePattern ()
void setStateLink ()
void setStateCite ()
void setStateRef ()
void setStateInternalRef ()
void setStateText ()
void setStateSkipTitle ()
void setStateAnchor ()
void setInsidePre (bool b)
void pushBackHtmlTag (const QCString &tag)
void setStateSnippet ()
void startAutoList ()
void endAutoList ()
void setStatePlantUML ()
void setStateSetScope ()
void setStatePlantUMLOpt ()
void setStateOptions ()
void setStateBlock ()
void setStateEmoji ()
void setStateILine ()
void setStateQuotedString ()
void setStateShowDate ()
DocTokenizer ()
~DocTokenizer ()
TokenInfo * token ()
TokenInfo * newToken ()
void replaceToken (TokenInfo *newToken)
void setLineNr (int lineno)
int getLineNr (void)
void findSections (const QCString &input, const Definition *d, const QCString &fileName)
void init (const char *input, const QCString &fileName, bool markdownSupport)
void cleanup ()
void pushContext ()
bool popContext ()
int lex ()
void unputString (const QCString &tag)
void setStatePara ()
void setStateTitle ()
void setStateTitleAttrValue ()
void setStateCode ()
void setStateICode ()
void setStateXmlCode ()
void setStateHtmlOnly ()
void setStateManOnly ()
void setStateLatexOnly ()
void setStateXmlOnly ()
void setStateDbOnly ()
void setStateRtfOnly ()
void setStateVerbatim ()
void setStateIVerbatim ()
void setStateILiteral ()
void setStateILiteralOpt ()
void setStateDot ()
void setStateMsc ()
void setStateParam ()
void setStateXRefItem ()
void setStateFile ()
void setStatePattern ()
void setStateLink ()
void setStateCite ()
void setStateRef ()
void setStateInternalRef ()
void setStateText ()
void setStateSkipTitle ()
void setStateAnchor ()
void setInsidePre (bool b)
void pushBackHtmlTag (const QCString &tag)
void setStateSnippet ()
void startAutoList ()
void endAutoList ()
void setStatePlantUML ()
void setStateSetScope ()
void setStatePlantUMLOpt ()
void setStateOptions ()
void setStateBlock ()
void setStateEmoji ()
void setStateILine ()
void setStateQuotedString ()
void setStateShowDate ()
Static Public Member Functions
static const char * tokToString (int token)
static const char * retvalToString (int retval)
static const char * tokToString (int token)
static const char * retvalToString (int retval)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 120 of file doctokenizer.h.
Constructor & Destructor Documentation
DocTokenizer() [1/2]
DocTokenizer::DocTokenizer ()
Definition at line 1715 of file doctokenizer.l.
                           : p(std::make_unique<Private>())
{
  //printf("%p:DocTokenizer::DocTokenizer()\n",(void*)this);
  doctokenizerYYlex_init_extra(&p->extra,&p->yyscanner);
#ifdef FLEX_DEBUG
  doctokenizerYYset_debug(1,p->yyscanner);
#endif
}
References p.
 DocTokenizer() [1/2]
DocTokenizer::~DocTokenizer ()
Definition at line 1724 of file doctokenizer.l.
{
  //printf("%p:DocTokenizer::~DocTokenizer()\n",(void*)this);
  doctokenizerYYlex_destroy(p->yyscanner);
}
References p.
DocTokenizer() [2/2]
DocTokenizer::DocTokenizer ()
 DocTokenizer() [2/2]
DocTokenizer::~DocTokenizer ()
Member Function Documentation
cleanup() [1/2]
void DocTokenizer::cleanup ()
Definition at line 2089 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yy_delete_buffer(YY_CURRENT_BUFFER, yyscanner);
}
References p.
cleanup() [2/2]
void DocTokenizer::cleanup ()
endAutoList() [1/2]
void DocTokenizer::endAutoList ()
Definition at line 2124 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->autoListLevel--;
}
References p.
Referenced by DocAutoList::parse().
endAutoList() [2/2]
void DocTokenizer::endAutoList ()
findSections() [1/2]
void DocTokenizer::findSections (const QCString & input, const Definition * d, const QCString & fileName)
Definition at line 1742 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (input.isEmpty()) return;
  printlex(yy_flex_debug, TRUE, __FILE__, qPrint(fileName));
  yyextra->inputString = input.data();
  //printf("parsing --->'%s'<---\n",input);
  yyextra->inputPos = 0;
  yyextra->definition = d;
  yyextra->fileName = fileName;
  BEGIN(St_Sections);
  yyextra->yyLineNr = 1;
  doctokenizerYYlex(yyscanner);
  printlex(yy_flex_debug, FALSE, __FILE__, qPrint(fileName));
}
References QCString::data(), FALSE, QCString::isEmpty(), p, printlex(), qPrint(), and TRUE.
Referenced by docFindSections().
findSections() [2/2]
void DocTokenizer::findSections (const QCString & input, const Definition * d, const QCString & fileName)
getLineNr() [1/2]
int DocTokenizer::getLineNr (void)
Definition at line 2146 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  return yyextra->yyLineNr;
}
References p.
Referenced by DocParser::defaultHandleTitleAndSize(), DocParser::defaultHandleToken(), DocAnchor::DocAnchor(), DocCite::DocCite(), DocEmoji::DocEmoji(), DocFormula::DocFormula(), DocHtmlCaption::DocHtmlCaption(), DocLink::DocLink(), DocRef::DocRef(), DocParser::errorHandleDefaultToken(), DocParser::findAndCopyImage(), DocParser::handleAHref(), DocParser::handleAnchor(), DocPara::handleFile(), DocParser::handleImage(), DocParser::handleImg(), DocParser::handleInternalRef(), DocParser::handleLinkedWord(), DocParser::handleStyleArgument(), DocParser::handleStyleLeave(), DocParser::handleUnclosedStyleCommands(), DocParser::processCopyDoc(), DocParser::pushContext(), and DocParser::readTextFileByName().
getLineNr() [2/2]
int DocTokenizer::getLineNr (void)
init() [1/2]
void DocTokenizer::init (const char * input, const QCString & fileName, bool markdownSupport)
Definition at line 1761 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->autoListLevel = 0;
  yyextra->inputString = input;
  yyextra->inputPos = 0;
  yyextra->fileName = fileName;
  yyextra->insidePre = FALSE;
  yyextra->markdownSupport = markdownSupport;
  BEGIN(St_Para);
}
References FALSE, and p.
Referenced by DocParser::internalValidatingParseDoc(), validatingParseDoc(), and validatingParseText().
init() [2/2]
void DocTokenizer::init (const char * input, const QCString & fileName, bool markdownSupport)
lex() [1/2]
int DocTokenizer::lex ()
Definition at line 1730 of file doctokenizer.l.
{
  return doctokenizerYYlex(p->yyscanner);
}
References p.
Referenced by DocParser::defaultHandleTitleAndSize(), DocParser::defaultHandleToken(), DocParser::handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleEmoji(), DocPara::handleFile(), DocPara::handleIFile(), DocPara::handleILine(), DocParser::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocParser::handleInternalRef(), DocPara::handleLink(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleShowDate(), DocPara::handleStartCode(), DocParser::handleStyleArgument(), DocPara::handleXRefItem(), DocIndexEntry::parse(), DocVhdlFlow::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSecRefList::parse(), DocHtmlList::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocParamList::parse(), DocHtmlList::parseXml(), DocHtmlTable::parseXml(), and DocHtmlRow::parseXml().
lex() [2/2]
int DocTokenizer::lex ()
newToken() [1/2]
TokenInfo * DocTokenizer::newToken ()
Definition at line 1774 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  return yyextra->token = new TokenInfo;
}
References p.
Referenced by DocParser::pushContext(), and replaceToken().
newToken() [2/2]
TokenInfo * DocTokenizer::newToken ()
popContext() [1/2]
bool DocTokenizer::popContext ()
Definition at line 1695 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  //printf("DocTokenizer::popContext() stack=%zu\n",yyextra->lexerStack.size());
  if (yyextra->lexerStack.empty()) return FALSE;
  const auto &ctx = yyextra->lexerStack.top();
  yyextra->autoListLevel = ctx->autoListLevel;
  yyextra->inputPos = ctx->inputPos;
  yyextra->inputString = ctx->inputString;
  yy_delete_buffer(YY_CURRENT_BUFFER, yyscanner);
  yy_switch_to_buffer(ctx->state, yyscanner);
  BEGIN(ctx->rule);
  yyextra->lexerStack.pop();
  return TRUE;
}
References FALSE, p, and TRUE.
Referenced by DocParser::popContext().
popContext() [2/2]
bool DocTokenizer::popContext ()
pushBackHtmlTag() [1/2]
void DocTokenizer::pushBackHtmlTag (const QCString & tag)
Definition at line 2103 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  QCString tagName = tag;
  int i,l = tagName.length();
  unput('>');
  for (i=l-1;i>=0;i--)
  {
    unput(tag[i]);
  }
  unput('<');
}
References QCString::length(), and p.
Referenced by DocHtmlDescList::parse(), DocHtmlList::parse(), DocHtmlRow::parse(), DocHtmlList::parseXml(), and DocHtmlRow::parseXml().
pushBackHtmlTag() [2/2]
void DocTokenizer::pushBackHtmlTag (const QCString & tag)
pushContext() [1/2]
void DocTokenizer::pushContext ()
Definition at line 1680 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  //printf("DocTokenizer::pushContext() stack=%zu\n",yyextra->lexerStack.size());
  yyextra->lexerStack.push(
      std::make_unique<DocLexerContext>(
        yyextra->token,YY_START,
        yyextra->autoListLevel,
        yyextra->inputPos,
        yyextra->inputString,
        YY_CURRENT_BUFFER));
  yy_switch_to_buffer(yy_create_buffer(0, YY_BUF_SIZE, yyscanner), yyscanner);
}
References p.
Referenced by DocParser::pushContext().
pushContext() [2/2]
void DocTokenizer::pushContext ()
replaceToken() [1/2]
void DocTokenizer::replaceToken (TokenInfo * newToken)
Definition at line 1781 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  delete yyextra->token;
  yyextra->token = newToken;
}
References newToken(), and p.
Referenced by DocParser::popContext().
replaceToken() [2/2]
void DocTokenizer::replaceToken (TokenInfo * newToken)
retvalToString() [1/2]
const char * DocTokenizer::retvalToString (int retval) [static]
Definition at line 149 of file doctokenizer.l.
{
  switch (retval)
  {
    case RetVal_OK: return "RetVal_OK";
    case RetVal_SimpleSec: return "RetVal_SimpleSec";
    case RetVal_ListItem: return "RetVal_ListItem";
    case RetVal_Section: return "RetVal_Section";
    case RetVal_Subsection: return "RetVal_Subsection";
    case RetVal_Subsubsection: return "RetVal_Subsubsection";
    case RetVal_Paragraph: return "RetVal_Paragraph";
    case RetVal_SubParagraph: return "RetVal_SubParagraph";
    case RetVal_EndList: return "RetVal_EndList";
    case RetVal_EndPre: return "RetVal_EndPre";
    case RetVal_DescData: return "RetVal_DescData";
    case RetVal_DescTitle : return "RetVal_DescTitle";
    case RetVal_EndDesc: return "RetVal_EndDesc";
    case RetVal_TableRow: return "RetVal_TableRow";
    case RetVal_TableCell: return "RetVal_TableCell";
    case RetVal_TableHCell: return "RetVal_TableHCell";
    case RetVal_EndTable: return "RetVal_EndTable";
    case RetVal_Internal: return "RetVal_Internal";
  }
  return "ERROR";
}
References RetVal_DescData, RetVal_DescTitle, RetVal_EndDesc, RetVal_EndList, RetVal_EndPre, RetVal_EndTable, RetVal_Internal, RetVal_ListItem, RetVal_OK, RetVal_Paragraph, RetVal_Section, RetVal_SimpleSec, RetVal_SubParagraph, RetVal_Subsection, RetVal_Subsubsection, RetVal_TableCell, RetVal_TableHCell, and RetVal_TableRow.
Referenced by DocPara::handleCommand(), DocIndexEntry::parse(), DocHtmlDetails::parse(), DocSection::parse(), DocParBlock::parse(), DocHtmlList::parse(), DocPara::parse(), DocHtmlListItem::parse(), DocHtmlBlockQuote::parse(), DocInternal::parse(), DocHtmlList::parseXml(), and DocHtmlListItem::parseXml().
retvalToString() [2/2]
static const char * DocTokenizer::retvalToString (int retval) [static]
setInsidePre() [1/2]
void DocTokenizer::setInsidePre (bool b)
Definition at line 2096 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->insidePre = b;
}
References b, and p.
Referenced by DocPara::handleHtmlEndTag(), and DocPara::handleHtmlStartTag().
setInsidePre() [2/2]
void DocTokenizer::setInsidePre (bool b)
setLineNr() [1/2]
void DocTokenizer::setLineNr (int lineno)
Definition at line 2139 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->yyLineNr = lineno;
}
References p.
Referenced by DocPara::handleInclude(), DocParser::popContext(), validatingParseDoc(), and validatingParseText().
setLineNr() [2/2]
void DocTokenizer::setLineNr (int lineno)
setStateAnchor() [1/2]
void DocTokenizer::setStateAnchor ()
Definition at line 2022 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_Anchor);
}
References p.
Referenced by DocParser::handleAnchor().
setStateAnchor() [2/2]
void DocTokenizer::setStateAnchor ()
setStateBlock() [1/2]
void DocTokenizer::setStateBlock ()
Definition at line 2052 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->name="";
  BEGIN(St_Block);
}
References p.
Referenced by DocPara::handleInclude().
setStateBlock() [2/2]
void DocTokenizer::setStateBlock ()
setStateCite() [1/2]
void DocTokenizer::setStateCite ()
Definition at line 1987 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_Cite);
}
References p.
Referenced by DocPara::handleCite().
setStateCite() [2/2]
void DocTokenizer::setStateCite ()
setStateCode() [1/2]
void DocTokenizer::setStateCode ()
Definition at line 1810 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  yyextra->token->name="";
  BEGIN(St_CodeOpt);
}
References p.
Referenced by DocPara::handleCommand().
setStateCode() [2/2]
void DocTokenizer::setStateCode ()
setStateDbOnly() [1/2]
void DocTokenizer::setStateDbOnly ()
Definition at line 1870 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  BEGIN(St_DbOnly);
}
References p.
Referenced by DocParser::defaultHandleToken(), and DocPara::handleCommand().
setStateDbOnly() [2/2]
void DocTokenizer::setStateDbOnly ()
setStateDot() [1/2]
void DocTokenizer::setStateDot ()
Definition at line 1918 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  BEGIN(St_Dot);
}
References p.
Referenced by DocPara::handleCommand().
setStateDot() [2/2]
void DocTokenizer::setStateDot ()
setStateEmoji() [1/2]
void DocTokenizer::setStateEmoji ()
Definition at line 2060 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->name="";
  BEGIN(St_Emoji);
}
References p.
Referenced by DocPara::handleEmoji().
setStateEmoji() [2/2]
void DocTokenizer::setStateEmoji ()
setStateFile() [1/2]
void DocTokenizer::setStateFile ()
Definition at line 1965 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_File);
}
References p.
Referenced by DocPara::handleFile(), DocPara::handleIFile(), DocParser::handleImage(), and DocPara::handleInclude().
setStateFile() [2/2]
void DocTokenizer::setStateFile ()
setStateHtmlOnly() [1/2]
void DocTokenizer::setStateHtmlOnly ()
Definition at line 1837 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  yyextra->token->name="";
  BEGIN(St_HtmlOnlyOption);
}
References p.
Referenced by DocParser::defaultHandleToken(), and DocPara::handleCommand().
setStateHtmlOnly() [2/2]
void DocTokenizer::setStateHtmlOnly ()
setStateICode() [1/2]
void DocTokenizer::setStateICode ()
Definition at line 1819 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  yyextra->token->name="";
  BEGIN(St_iCodeOpt);
}
References p.
Referenced by DocPara::handleCommand().
setStateICode() [2/2]
void DocTokenizer::setStateICode ()
setStateILine() [1/2]
void DocTokenizer::setStateILine ()
Definition at line 2068 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_ILine);
}
References p.
Referenced by DocPara::handleILine().
setStateILine() [2/2]
void DocTokenizer::setStateILine ()
setStateILiteral() [1/2]
void DocTokenizer::setStateILiteral ()
Definition at line 1886 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  BEGIN(St_ILiteral);
}
References p.
Referenced by DocPara::handleCommand().
setStateILiteral() [2/2]
void DocTokenizer::setStateILiteral ()
setStateILiteralOpt() [1/2]
void DocTokenizer::setStateILiteralOpt ()
Definition at line 1894 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  BEGIN(St_ILiteralOpt);
}
References p.
Referenced by DocPara::handleCommand().
setStateILiteralOpt() [2/2]
void DocTokenizer::setStateILiteralOpt ()
setStateInternalRef() [1/2]
void DocTokenizer::setStateInternalRef ()
Definition at line 2001 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_IntRef);
}
References p.
Referenced by DocParser::handleInternalRef().
setStateInternalRef() [2/2]
void DocTokenizer::setStateInternalRef ()
setStateIVerbatim() [1/2]
void DocTokenizer::setStateIVerbatim ()
Definition at line 1910 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  BEGIN(St_iVerbatim);
}
References p.
Referenced by DocPara::handleCommand().
setStateIVerbatim() [2/2]
void DocTokenizer::setStateIVerbatim ()
setStateLatexOnly() [1/2]
void DocTokenizer::setStateLatexOnly ()
Definition at line 1878 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  BEGIN(St_LatexOnly);
}
References p.
Referenced by DocParser::defaultHandleToken(), and DocPara::handleCommand().
setStateLatexOnly() [2/2]
void DocTokenizer::setStateLatexOnly ()
setStateLink() [1/2]
void DocTokenizer::setStateLink ()
Definition at line 1980 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_Link);
}
References p.
Referenced by DocPara::handleLink(), and DocHtmlDescTitle::parse().
setStateLink() [2/2]
void DocTokenizer::setStateLink ()
setStateManOnly() [1/2]
void DocTokenizer::setStateManOnly ()
Definition at line 1846 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  BEGIN(St_ManOnly);
}
References p.
Referenced by DocParser::defaultHandleToken(), and DocPara::handleCommand().
setStateManOnly() [2/2]
void DocTokenizer::setStateManOnly ()
setStateMsc() [1/2]
void DocTokenizer::setStateMsc ()
Definition at line 1926 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  BEGIN(St_Msc);
}
References p.
Referenced by DocPara::handleCommand().
setStateMsc() [2/2]
void DocTokenizer::setStateMsc ()
setStateOptions() [1/2]
void DocTokenizer::setStateOptions ()
Definition at line 2044 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->name="";
  BEGIN(St_Options);
}
References p.
Referenced by DocParser::handleImage(), and DocPara::handleInclude().
setStateOptions() [2/2]
void DocTokenizer::setStateOptions ()
setStatePara() [1/2]
void DocTokenizer::setStatePara ()
Definition at line 1789 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_Para);
}
References p.
Referenced by DocParser::defaultHandleTitleAndSize(), DocParser::defaultHandleToken(), DocParser::handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleEmoji(), DocPara::handleFile(), DocPara::handleHtmlStartTag(), DocPara::handleIFile(), DocPara::handleILine(), DocParser::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocPara::handleLink(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleShowDate(), DocPara::handleStartCode(), DocPara::handleXRefItem(), DocIndexEntry::parse(), DocTitle::parse(), DocVhdlFlow::parse(), DocHtmlSummary::parse(), DocHtmlDescTitle::parse(), DocSecRefItem::parse(), DocRoot::parse(), and DocParamList::parse().
setStatePara() [2/2]
void DocTokenizer::setStatePara ()
setStateParam() [1/2]
void DocTokenizer::setStateParam ()
Definition at line 1951 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_Param);
}
References p.
Referenced by DocParamList::parse().
setStateParam() [2/2]
void DocTokenizer::setStateParam ()
setStatePattern() [1/2]
void DocTokenizer::setStatePattern ()
Definition at line 1972 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->name = "";
  BEGIN(St_Pattern);
}
References p.
Referenced by DocPara::handleIncludeOperator().
setStatePattern() [2/2]
void DocTokenizer::setStatePattern ()
setStatePlantUML() [1/2]
void DocTokenizer::setStatePlantUML ()
Definition at line 1943 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  BEGIN(St_PlantUML);
}
References p.
Referenced by DocPara::handleCommand().
setStatePlantUML() [2/2]
void DocTokenizer::setStatePlantUML ()
setStatePlantUMLOpt() [1/2]
void DocTokenizer::setStatePlantUMLOpt ()
Definition at line 1934 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  yyextra->token->sectionId="";
  BEGIN(St_PlantUMLOpt);
}
References p.
Referenced by DocPara::handleCommand().
setStatePlantUMLOpt() [2/2]
void DocTokenizer::setStatePlantUMLOpt ()
setStateQuotedString() [1/2]
void DocTokenizer::setStateQuotedString ()
Definition at line 2075 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_QuotedString);
}
References p.
Referenced by DocPara::handleShowDate().
setStateQuotedString() [2/2]
void DocTokenizer::setStateQuotedString ()
setStateRef() [1/2]
void DocTokenizer::setStateRef ()
Definition at line 1994 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_Ref);
}
References p.
Referenced by DocPara::handleRef(), and DocHtmlDescTitle::parse().
setStateRef() [2/2]
void DocTokenizer::setStateRef ()
setStateRtfOnly() [1/2]
void DocTokenizer::setStateRtfOnly ()
Definition at line 1854 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  BEGIN(St_RtfOnly);
}
References p.
Referenced by DocParser::defaultHandleToken(), and DocPara::handleCommand().
setStateRtfOnly() [2/2]
void DocTokenizer::setStateRtfOnly ()
setStateSetScope() [1/2]
void DocTokenizer::setStateSetScope ()
Definition at line 2037 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_SetScope);
}
References p.
Referenced by DocParser::defaultHandleToken().
setStateSetScope() [2/2]
void DocTokenizer::setStateSetScope ()
setStateShowDate() [1/2]
void DocTokenizer::setStateShowDate ()
Definition at line 2082 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_ShowDate);
}
References p.
Referenced by DocPara::handleShowDate().
setStateShowDate() [2/2]
void DocTokenizer::setStateShowDate ()
setStateSkipTitle() [1/2]
void DocTokenizer::setStateSkipTitle ()
Definition at line 2015 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_SkipTitle);
}
References p.
Referenced by DocPara::handleSection().
setStateSkipTitle() [2/2]
void DocTokenizer::setStateSkipTitle ()
setStateSnippet() [1/2]
void DocTokenizer::setStateSnippet ()
Definition at line 2029 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->name="";
  BEGIN(St_Snippet);
}
References p.
Referenced by DocPara::handleInclude().
setStateSnippet() [2/2]
void DocTokenizer::setStateSnippet ()
setStateText() [1/2]
void DocTokenizer::setStateText ()
Definition at line 2008 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_Text);
}
References p.
Referenced by DocText::parse().
setStateText() [2/2]
void DocTokenizer::setStateText ()
setStateTitle() [1/2]
void DocTokenizer::setStateTitle ()
Definition at line 1796 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_Title);
}
References p.
Referenced by DocParser::defaultHandleTitleAndSize(), DocIndexEntry::parse(), DocTitle::parse(), DocVhdlFlow::parse(), DocHtmlSummary::parse(), and DocSecRefItem::parse().
setStateTitle() [2/2]
void DocTokenizer::setStateTitle ()
setStateTitleAttrValue() [1/2]
void DocTokenizer::setStateTitleAttrValue ()
Definition at line 1803 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_TitleV);
}
References p.
Referenced by DocParser::defaultHandleTitleAndSize().
setStateTitleAttrValue() [2/2]
void DocTokenizer::setStateTitleAttrValue ()
setStateVerbatim() [1/2]
void DocTokenizer::setStateVerbatim ()
Definition at line 1902 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  BEGIN(St_Verbatim);
}
References p.
Referenced by DocPara::handleCommand().
setStateVerbatim() [2/2]
void DocTokenizer::setStateVerbatim ()
setStateXmlCode() [1/2]
void DocTokenizer::setStateXmlCode ()
Definition at line 1828 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  yyextra->token->name="";
  BEGIN(St_XmlCode);
}
References p.
Referenced by DocPara::handleHtmlStartTag().
setStateXmlCode() [2/2]
void DocTokenizer::setStateXmlCode ()
setStateXmlOnly() [1/2]
void DocTokenizer::setStateXmlOnly ()
Definition at line 1862 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->token->verb="";
  BEGIN(St_XmlOnly);
}
References p.
Referenced by DocParser::defaultHandleToken(), and DocPara::handleCommand().
setStateXmlOnly() [2/2]
void DocTokenizer::setStateXmlOnly ()
setStateXRefItem() [1/2]
void DocTokenizer::setStateXRefItem ()
Definition at line 1958 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(St_XRefItem);
}
References p.
Referenced by DocPara::handleXRefItem().
setStateXRefItem() [2/2]
void DocTokenizer::setStateXRefItem ()
startAutoList() [1/2]
void DocTokenizer::startAutoList ()
Definition at line 2117 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->autoListLevel++;
}
References p.
Referenced by DocAutoList::parse().
startAutoList() [2/2]
void DocTokenizer::startAutoList ()
token() [1/2]
TokenInfo * DocTokenizer::token ()
Referenced by tokToString().
token() [2/2]
TokenInfo * DocTokenizer::token ()
tokToString() [1/2]
const char * DocTokenizer::tokToString (int token) [static]
Definition at line 128 of file doctokenizer.l.
{
  switch (token)
  {
    case 0: return "TK_EOF";
    case TK_WORD: return "TK_WORD";
    case TK_LNKWORD: return "TK_LNKWORD";
    case TK_WHITESPACE: return "TK_WHITESPACE";
    case TK_LISTITEM: return "TK_LISTITEM";
    case TK_ENDLIST: return "TK_ENDLIST";
    case TK_COMMAND_AT: return "TK_COMMAND_AT";
    case TK_HTMLTAG: return "TK_HTMLTAG";
    case TK_SYMBOL: return "TK_SYMBOL";
    case TK_NEWPARA: return "TK_NEWPARA";
    case TK_RCSTAG: return "TK_RCSTAG";
    case TK_URL: return "TK_URL";
    case TK_COMMAND_BS: return "TK_COMMAND_BS";
  }
  return "ERROR";
}
References TK_COMMAND_AT, TK_COMMAND_BS, TK_ENDLIST, TK_HTMLTAG, TK_LISTITEM, TK_LNKWORD, TK_NEWPARA, TK_RCSTAG, TK_SYMBOL, TK_URL, TK_WHITESPACE, TK_WORD, and token().
Referenced by DocParser::defaultHandleToken(), DocParser::errorHandleDefaultToken(), DocParser::handleAnchor(), DocPara::handleCite(), DocPara::handleEmoji(), DocPara::handleFile(), DocPara::handleIFile(), DocParser::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocParser::handleInternalRef(), DocPara::handleLink(), DocPara::handleRef(), DocPara::handleSection(), DocParser::handleStyleArgument(), DocIndexEntry::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSecRefList::parse(), DocHtmlList::parse(), DocPara::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocText::parse(), DocLink::parse(), DocParamList::parse(), DocHtmlList::parseXml(), and DocHtmlRow::parseXml().
tokToString() [2/2]
static const char * DocTokenizer::tokToString (int token) [static]
unputString() [1/2]
void DocTokenizer::unputString (const QCString & tag)
Definition at line 1735 of file doctokenizer.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  unput_string(tag.data(),tag.length());
}
References QCString::data(), QCString::length(), p, and unput_string.
Referenced by DocParser::defaultHandleTitleAndSize().
unputString() [2/2]
void DocTokenizer::unputString (const QCString & tag)
Member Data Documentation
p
std::unique_ptr< Private > DocTokenizer::p [private]
Definition at line 192 of file doctokenizer.h.
Referenced by cleanup(), DocTokenizer(), endAutoList(), findSections(), getLineNr(), init(), lex(), newToken(), popContext(), pushBackHtmlTag(), pushContext(), replaceToken(), setInsidePre(), setLineNr(), setStateAnchor(), setStateBlock(), setStateCite(), setStateCode(), setStateDbOnly(), setStateDot(), setStateEmoji(), setStateFile(), setStateHtmlOnly(), setStateICode(), setStateILine(), setStateILiteral(), setStateILiteralOpt(), setStateInternalRef(), setStateIVerbatim(), setStateLatexOnly(), setStateLink(), setStateManOnly(), setStateMsc(), setStateOptions(), setStatePara(), setStateParam(), setStatePattern(), setStatePlantUML(), setStatePlantUMLOpt(), setStateQuotedString(), setStateRef(), setStateRtfOnly(), setStateSetScope(), setStateShowDate(), setStateSkipTitle(), setStateSnippet(), setStateText(), setStateTitle(), setStateTitleAttrValue(), setStateVerbatim(), setStateXmlCode(), setStateXmlOnly(), setStateXRefItem(), startAutoList(), unputString(), and ~DocTokenizer().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/doctokenizer.h
doxygen/src/doctokenizer.h
doxygen/build/doxygen/src/doctokenizer.l
doxygen/src/doctokenizer.l