TemplateNodeCreate Class Reference
Class representing an 'create' tag in a template.
Public Member Functions
TemplateNodeCreate (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &, TemplateContext *c)
TemplateNodeCreate (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &, TemplateContext *c)
Private Attributes
ExprAstPtr m_templateExpr
ExprAstPtr m_fileExpr
Additional Inherited Members
Detailed Description
Class representing an 'create' tag in a template.
Definition at line 3822 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeCreate() [1/2]
TemplateNodeCreate::TemplateNodeCreate (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3825 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeCreate>(parser,parent,line)
    {
      TRACE(("TemplateNodeCreate(%s)\n",qPrint(data)));
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"create tag is missing arguments");
      }
      int i = data.find(" from ");
      if (i==-1)
      {
        if (data.endsWith(" from"))
        {
          parser->warn(m_templateName,line,"create is missing template name after 'from' keyword");
        }
        else if (data=="from")
        {
          parser->warn(m_templateName,line,"create needs a file name and a template name");
        }
        else
        {
          parser->warn(m_templateName,line,"create is missing 'from' keyword");
        }
      }
      else
      {
        ExpressionParser ep(parser,line);
        m_fileExpr = ep.parse(data.left(i).stripWhiteSpace());
        m_templateExpr = ep.parse(data.mid(i+6).stripWhiteSpace());
      }
    }
References data, m_fileExpr, m_templateExpr, TemplateNodeCreator< TemplateNodeCreate >::m_templateName, ExpressionParser::parse(), qPrint(), TRACE, and TemplateParser::warn().
TemplateNodeCreate() [2/2]
TemplateNodeCreate::TemplateNodeCreate (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3825 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeCreate>(parser,parent,line)
    {
      TRACE(("TemplateNodeCreate(%s)\n",qPrint(data)));
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"create tag is missing arguments");
      }
      int i = data.find(" from ");
      if (i==-1)
      {
        if (data.endsWith(" from"))
        {
          parser->warn(m_templateName,line,"create is missing template name after 'from' keyword");
        }
        else if (data=="from")
        {
          parser->warn(m_templateName,line,"create needs a file name and a template name");
        }
        else
        {
          parser->warn(m_templateName,line,"create is missing 'from' keyword");
        }
      }
      else
      {
        ExpressionParser ep(parser,line);
        m_fileExpr = ep.parse(data.left(i).stripWhiteSpace());
        m_templateExpr = ep.parse(data.mid(i+6).stripWhiteSpace());
      }
    }
References data, m_fileExpr, m_templateExpr, TemplateNodeCreator< TemplateNodeCreate >::m_templateName, ExpressionParser::parse(), qPrint(), TRACE, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeCreate::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3856 of file template.cpp.
    {
      TRACE(("{TemplateNodeCreate::render\n"));
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_templateExpr && m_fileExpr)
      {
        QCString templateFile = m_templateExpr->resolve(c).toString();
        QCString outputFile = m_fileExpr->resolve(c).toString();
        if (templateFile.isEmpty())
        {
          ci->warn(m_templateName,m_line,"empty template name parameter for create command\n");
        }
        else if (outputFile.isEmpty())
        {
          ci->warn(m_templateName,m_line,"empty file name parameter for create command\n");
        }
        else
        {
          TemplateImpl *t = getTemplate();
          if (t)
          {
            QCString extension=outputFile;
            int i=extension.findRev('.');
            if (i!=-1)
            {
              extension=extension.right(extension.length()-i-1);
            }
            t->engine()->setOutputExtension(extension);
            Template *ct = t->engine()->loadByName(templateFile,m_line);
            TemplateImpl *createTemplate = ct ? dynamic_cast<TemplateImpl*>(ct) : 0;
            if (createTemplate)
            {
              mkpath(ci,outputFile.str());
              if (!ci->outputDirectory().isEmpty())
              {
                outputFile.prepend(ci->outputDirectory()+"/");
              }
              //printf("NoteCreate(%s)\n",qPrint(outputFile));
              std::ofstream f(outputFile.str(),std::ofstream::out | std::ofstream::binary);
              if (f.is_open())
              {
                TextStream ts(&f);
                TemplateEscapeIntf *escIntf = ci->escapeIntf();
                ci->selectEscapeIntf(extension);
                TextStream os;
                createTemplate->render(os,c);
                QCString out = os.str();
                stripLeadingWhiteSpace(out);
                ts << out;
                t->engine()->unload(t);
                ci->setActiveEscapeIntf(escIntf);
              }
              else
              {
                ci->warn(m_templateName,m_line,"failed to open output file '%s' for create command",qPrint(outputFile));
              }
            }
            else
            {
              ci->warn(m_templateName,m_line,"failed to load template '%s' for include",qPrint(templateFile));
            }
            t->engine()->setOutputExtension("");
          }
        }
      }
      TRACE(("}TemplateNodeCreate::render\n"));
    }
References c, TemplateImpl::engine(), TemplateContextImpl::escapeIntf(), f, QCString::findRev(), TemplateNodeCreator< TemplateNodeCreate >::getTemplate(), QCString::isEmpty(), QCString::length(), TemplateEngine::loadByName(), m_fileExpr, TemplateNodeCreator< TemplateNodeCreate >::m_line, m_templateExpr, TemplateNodeCreator< TemplateNodeCreate >::m_templateName, TemplateNodeCreator< TemplateNodeCreate >::mkpath(), out, TemplateContextImpl::outputDirectory(), QCString::prepend(), qPrint(), TemplateImpl::render(), QCString::right(), TemplateContextImpl::selectEscapeIntf(), TemplateContextImpl::setActiveEscapeIntf(), TemplateContextImpl::setLocation(), TemplateEngine::setOutputExtension(), QCString::str(), TextStream::str(), stripLeadingWhiteSpace(), TRACE, TemplateEngine::unload(), and TemplateContextImpl::warn().
render() [2/2]
void TemplateNodeCreate::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3856 of file template.cpp.
    {
      TRACE(("{TemplateNodeCreate::render\n"));
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_templateExpr && m_fileExpr)
      {
        QCString templateFile = m_templateExpr->resolve(c).toString();
        QCString outputFile = m_fileExpr->resolve(c).toString();
        if (templateFile.isEmpty())
        {
          ci->warn(m_templateName,m_line,"empty template name parameter for create command\n");
        }
        else if (outputFile.isEmpty())
        {
          ci->warn(m_templateName,m_line,"empty file name parameter for create command\n");
        }
        else
        {
          TemplateImpl *t = getTemplate();
          if (t)
          {
            QCString extension=outputFile;
            int i=extension.findRev('.');
            if (i!=-1)
            {
              extension=extension.right(extension.length()-i-1);
            }
            t->engine()->setOutputExtension(extension);
            Template *ct = t->engine()->loadByName(templateFile,m_line);
            TemplateImpl *createTemplate = ct ? dynamic_cast<TemplateImpl*>(ct) : 0;
            if (createTemplate)
            {
              mkpath(ci,outputFile.str());
              if (!ci->outputDirectory().isEmpty())
              {
                outputFile.prepend(ci->outputDirectory()+"/");
              }
              //printf("NoteCreate(%s)\n",qPrint(outputFile));
              std::ofstream f(outputFile.str(),std::ofstream::out | std::ofstream::binary);
              if (f.is_open())
              {
                TextStream ts(&f);
                TemplateEscapeIntf *escIntf = ci->escapeIntf();
                ci->selectEscapeIntf(extension);
                TextStream os;
                createTemplate->render(os,c);
                QCString out = os.str();
                stripLeadingWhiteSpace(out);
                ts << out;
                t->engine()->unload(t);
                ci->setActiveEscapeIntf(escIntf);
              }
              else
              {
                ci->warn(m_templateName,m_line,"failed to open output file '%s' for create command",qPrint(outputFile));
              }
            }
            else
            {
              ci->warn(m_templateName,m_line,"failed to load template '%s' for include",qPrint(templateFile));
            }
            t->engine()->setOutputExtension("");
          }
        }
      }
      TRACE(("}TemplateNodeCreate::render\n"));
    }
References c, TemplateImpl::engine(), TemplateContextImpl::escapeIntf(), f, QCString::findRev(), TemplateNodeCreator< TemplateNodeCreate >::getTemplate(), QCString::isEmpty(), QCString::length(), TemplateEngine::loadByName(), m_fileExpr, TemplateNodeCreator< TemplateNodeCreate >::m_line, m_templateExpr, TemplateNodeCreator< TemplateNodeCreate >::m_templateName, TemplateNodeCreator< TemplateNodeCreate >::mkpath(), out, TemplateContextImpl::outputDirectory(), QCString::prepend(), qPrint(), TemplateImpl::render(), QCString::right(), TemplateContextImpl::selectEscapeIntf(), TemplateContextImpl::setActiveEscapeIntf(), TemplateContextImpl::setLocation(), TemplateEngine::setOutputExtension(), QCString::str(), TextStream::str(), stripLeadingWhiteSpace(), TRACE, TemplateEngine::unload(), and TemplateContextImpl::warn().
Member Data Documentation
m_fileExpr
ExprAstPtr TemplateNodeCreate::m_fileExpr [private]
Definition at line 3928 of file template.cpp.
Referenced by render(), and TemplateNodeCreate().
m_templateExpr
ExprAstPtr TemplateNodeCreate::m_templateExpr [private]
Definition at line 3927 of file template.cpp.
Referenced by render(), and TemplateNodeCreate().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp