Step4 Class Reference
#include <wizard.h>
Public Member Functions
Step4 (Wizard *parent, const QHash< QString, Input * > &modelData)
void init ()
Step4 (Wizard *parent, const QHash< QString, Input * > &modelData)
void init ()
Private Slots
void diagramModeChanged (int)
void setClassGraphEnabled (int state)
void setCollaborationGraphEnabled (int state)
void setGraphicalHierarchyEnabled (int state)
void setIncludeGraphEnabled (int state)
void setIncludedByGraphEnabled (int state)
void setCallGraphEnabled (int state)
void setCallerGraphEnabled (int state)
void diagramModeChanged (int)
void setClassGraphEnabled (int state)
void setCollaborationGraphEnabled (int state)
void setGraphicalHierarchyEnabled (int state)
void setIncludeGraphEnabled (int state)
void setIncludedByGraphEnabled (int state)
void setCallGraphEnabled (int state)
void setCallerGraphEnabled (int state)
Private Attributes
QGroupBox * m_diagramMode = 0
QButtonGroup * m_diagramModeGroup = 0
QGroupBox * m_dotGroup = 0
QCheckBox * m_dotClass = 0
QCheckBox * m_dotCollaboration = 0
QCheckBox * m_dotInclude = 0
QCheckBox * m_dotIncludedBy = 0
QCheckBox * m_dotInheritance = 0
QCheckBox * m_dotCall = 0
QCheckBox * m_dotCaller = 0
Wizard * m_wizard = 0
const QHash< QString, Input * > & m_modelData
Detailed Description
Definition at line 188 of file wizard.h.
Constructor & Destructor Documentation
Step4() [1/2]
Step4::Step4 (Wizard * parent, const QHash< QString, Input * > & modelData)
Definition at line 1138 of file wizard.cpp.
  : m_wizard(wizard), m_modelData(modelData)
{
  m_diagramModeGroup = new QButtonGroup(this);
  QGridLayout *gbox = new QGridLayout(this);
  gbox->addWidget(new QLabel(tr("Diagrams to generate")),0,0);
  // CLASS_GRAPH = NO, HAVE_DOT = NO
  QRadioButton *rb = new QRadioButton(tr("No diagrams"));
  m_diagramModeGroup->addButton(rb, 0);
  gbox->addWidget(rb,1,0);
  rb->setChecked(true);
  // CLASS_GRAPH = TEXT, HAVE_DOT = NO
  rb = new QRadioButton(tr("Text only"));
  m_diagramModeGroup->addButton(rb, 1);
  gbox->addWidget(rb,2,0);
  // CLASS_GRAPH = YES/GRAPH, HAVE_DOT = NO
  rb = new QRadioButton(tr("Use built-in class diagram generator"));
  m_diagramModeGroup->addButton(rb, 2);
  gbox->addWidget(rb,3,0);
  // CLASS_GRAPH = YES/GRAPH, HAVE_DOT = YES
  rb = new QRadioButton(tr("Use dot tool from the GraphViz package"));
  m_diagramModeGroup->addButton(rb, 3);
  gbox->addWidget(rb,4,0);
  m_dotGroup = new QGroupBox(tr("Dot graphs to generate"));
    QVBoxLayout *vbox = new QVBoxLayout;
    m_dotClass=new QCheckBox(tr("Class graphs"));
    // CLASS_GRAPH
    m_dotCollaboration=new QCheckBox(tr("Collaboration diagrams"));
    // COLLABORATION_GRAPH
    m_dotInheritance=new QCheckBox(tr("Overall Class hierarchy"));
    // GRAPHICAL_HIERARCHY
    m_dotInclude=new QCheckBox(tr("Include dependency graphs"));
    // INCLUDE_GRAPH
    m_dotIncludedBy=new QCheckBox(tr("Included by dependency graphs"));
    // INCLUDED_BY_GRAPH
    m_dotCall=new QCheckBox(tr("Call graphs"));
    // CALL_GRAPH
    m_dotCaller=new QCheckBox(tr("Called by graphs"));
    // CALLER_GRAPH
    vbox->addWidget(m_dotClass);
    vbox->addWidget(m_dotCollaboration);
    vbox->addWidget(m_dotInheritance);
    vbox->addWidget(m_dotInclude);
    vbox->addWidget(m_dotIncludedBy);
    vbox->addWidget(m_dotCall);
    vbox->addWidget(m_dotCaller);
    vbox->addStretch(1);
    m_dotGroup->setLayout(vbox);
    m_dotClass->setChecked(true);
    m_dotGroup->setEnabled(false);
  gbox->addWidget(m_dotGroup,5,0);
  m_dotInclude->setChecked(true);
  m_dotCollaboration->setChecked(true);
  gbox->setRowStretch(6,1);
#if QT_VERSION < QT_VERSION_CHECK(5, 15, 0)
  connect(m_diagramModeGroup,SIGNAL(buttonClicked(int)),
          this,SLOT(diagramModeChanged(int)));
#else
  connect(m_diagramModeGroup,SIGNAL(idClicked(int)),
          this,SLOT(diagramModeChanged(int)));
#endif
  connect(m_dotClass,SIGNAL(stateChanged(int)),
          this,SLOT(setClassGraphEnabled(int)));
  connect(m_dotCollaboration,SIGNAL(stateChanged(int)),
          this,SLOT(setCollaborationGraphEnabled(int)));
  connect(m_dotInheritance,SIGNAL(stateChanged(int)),
          this,SLOT(setGraphicalHierarchyEnabled(int)));
  connect(m_dotInclude,SIGNAL(stateChanged(int)),
          this,SLOT(setIncludeGraphEnabled(int)));
  connect(m_dotIncludedBy,SIGNAL(stateChanged(int)),
          this,SLOT(setIncludedByGraphEnabled(int)));
  connect(m_dotCall,SIGNAL(stateChanged(int)),
          this,SLOT(setCallGraphEnabled(int)));
  connect(m_dotCaller,SIGNAL(stateChanged(int)),
          this,SLOT(setCallerGraphEnabled(int)));
}
References diagramModeChanged(), m_diagramModeGroup, m_dotCall, m_dotCaller, m_dotClass, m_dotCollaboration, m_dotGroup, m_dotInclude, m_dotIncludedBy, m_dotInheritance, setCallerGraphEnabled(), setCallGraphEnabled(), setClassGraphEnabled(), setCollaborationGraphEnabled(), setGraphicalHierarchyEnabled(), setIncludedByGraphEnabled(), and setIncludeGraphEnabled().
Step4() [2/2]
Step4::Step4 (Wizard * parent, const QHash< QString, Input * > & modelData)
Member Function Documentation
diagramModeChanged [1/2]
void Step4::diagramModeChanged (int id) [private], [slot]
Definition at line 1222 of file wizard.cpp.
{
  if (id==0) // no diagrams
  {
    updateBoolOption(m_modelData,STR_HAVE_DOT,false);
    updateStringOption(m_modelData,STR_CLASS_GRAPH, QString::fromLatin1("NO"));
  }
  else if (id==1) // text only
  {
    updateBoolOption(m_modelData,STR_HAVE_DOT,false);
    updateStringOption(m_modelData,STR_CLASS_GRAPH, QString::fromLatin1("TEXT"));
  }
  else if (id==2) // builtin diagrams
  {
    updateBoolOption(m_modelData,STR_HAVE_DOT,false);
    updateStringOption(m_modelData,STR_CLASS_GRAPH, QString::fromLatin1("YES"));
  }
  else if (id==3) // dot diagrams
  {
    updateBoolOption(m_modelData,STR_HAVE_DOT,true);
    updateStringOption(m_modelData,STR_CLASS_GRAPH, QString::fromLatin1("YES"));
  }
  m_dotGroup->setEnabled(id==3);
}
References m_dotGroup, m_modelData, STR_CLASS_GRAPH, STR_HAVE_DOT, updateBoolOption(), and updateStringOption().
Referenced by Step4().
diagramModeChanged [2/2]
void Step4::diagramModeChanged (int) [private], [slot]
init() [1/2]
void Step4::init ()
Definition at line 1290 of file wizard.cpp.
{
  int id = 0;
  QString classGraph = getStringOption(m_modelData,STR_CLASS_GRAPH).toLower();
  if (classGraph==QString::fromLatin1("yes") || classGraph==QString::fromLatin1("graph"))
  {
    id = getBoolOption(m_modelData,STR_HAVE_DOT) ? 3 : 2;
  }
  else if (classGraph==QString::fromLatin1("text"))
  {
    id = 1;
  }
  else
  {
    id = 0;
  }
  m_diagramModeGroup->button(id)->setChecked(true); // no diagrams
  m_dotGroup->setEnabled(id==3);
  m_dotClass->setChecked(getBoolOption(m_modelData,STR_CLASS_GRAPH));
  m_dotCollaboration->setChecked(getBoolOption(m_modelData,STR_COLLABORATION_GRAPH));
  m_dotInheritance->setChecked(getBoolOption(m_modelData,STR_GRAPHICAL_HIERARCHY));
  m_dotInclude->setChecked(getBoolOption(m_modelData,STR_INCLUDE_GRAPH));
  m_dotIncludedBy->setChecked(getBoolOption(m_modelData,STR_INCLUDED_BY_GRAPH));
  m_dotCall->setChecked(getBoolOption(m_modelData,STR_CALL_GRAPH));
  m_dotCaller->setChecked(getBoolOption(m_modelData,STR_CALLER_GRAPH));
}
References getBoolOption(), getStringOption(), m_diagramModeGroup, m_dotCall, m_dotCaller, m_dotClass, m_dotCollaboration, m_dotGroup, m_dotInclude, m_dotIncludedBy, m_dotInheritance, m_modelData, STR_CALL_GRAPH, STR_CALLER_GRAPH, STR_CLASS_GRAPH, STR_COLLABORATION_GRAPH, STR_GRAPHICAL_HIERARCHY, STR_HAVE_DOT, STR_INCLUDE_GRAPH, and STR_INCLUDED_BY_GRAPH.
Referenced by Wizard::refresh().
init() [2/2]
void Step4::init ()
setCallerGraphEnabled [1/2]
void Step4::setCallerGraphEnabled (int state) [private], [slot]
Definition at line 1285 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_CALLER_GRAPH,state==Qt::Checked);
}
References m_modelData, STR_CALLER_GRAPH, and updateBoolOption().
Referenced by Step4().
setCallerGraphEnabled [2/2]
void Step4::setCallerGraphEnabled (int state) [private], [slot]
setCallGraphEnabled [1/2]
void Step4::setCallGraphEnabled (int state) [private], [slot]
Definition at line 1280 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_CALL_GRAPH,state==Qt::Checked);
}
References m_modelData, STR_CALL_GRAPH, and updateBoolOption().
Referenced by Step4().
setCallGraphEnabled [2/2]
void Step4::setCallGraphEnabled (int state) [private], [slot]
setClassGraphEnabled [1/2]
void Step4::setClassGraphEnabled (int state) [private], [slot]
Definition at line 1247 of file wizard.cpp.
{
  QString classGraph = getStringOption(m_modelData,STR_CLASS_GRAPH);
  if (state==Qt::Checked)
  {
    updateStringOption(m_modelData,STR_CLASS_GRAPH,QString::fromLatin1("YES"));
  }
  else if (classGraph==QString::fromLatin1("YES") || classGraph==QString::fromLatin1("GRAPH"))
  {
    updateStringOption(m_modelData,STR_CLASS_GRAPH,QString::fromLatin1("NO"));
  }
}
References getStringOption(), m_modelData, STR_CLASS_GRAPH, and updateStringOption().
Referenced by Step4().
setClassGraphEnabled [2/2]
void Step4::setClassGraphEnabled (int state) [private], [slot]
setCollaborationGraphEnabled [1/2]
void Step4::setCollaborationGraphEnabled (int state) [private], [slot]
Definition at line 1260 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_COLLABORATION_GRAPH,state==Qt::Checked);
}
References m_modelData, STR_COLLABORATION_GRAPH, and updateBoolOption().
Referenced by Step4().
setCollaborationGraphEnabled [2/2]
void Step4::setCollaborationGraphEnabled (int state) [private], [slot]
setGraphicalHierarchyEnabled [1/2]
void Step4::setGraphicalHierarchyEnabled (int state) [private], [slot]
Definition at line 1265 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_GRAPHICAL_HIERARCHY,state==Qt::Checked);
}
References m_modelData, STR_GRAPHICAL_HIERARCHY, and updateBoolOption().
Referenced by Step4().
setGraphicalHierarchyEnabled [2/2]
void Step4::setGraphicalHierarchyEnabled (int state) [private], [slot]
setIncludedByGraphEnabled [1/2]
void Step4::setIncludedByGraphEnabled (int state) [private], [slot]
Definition at line 1275 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_INCLUDED_BY_GRAPH,state==Qt::Checked);
}
References m_modelData, STR_INCLUDED_BY_GRAPH, and updateBoolOption().
Referenced by Step4().
setIncludedByGraphEnabled [2/2]
void Step4::setIncludedByGraphEnabled (int state) [private], [slot]
setIncludeGraphEnabled [1/2]
void Step4::setIncludeGraphEnabled (int state) [private], [slot]
Definition at line 1270 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_INCLUDE_GRAPH,state==Qt::Checked);
}
References m_modelData, STR_INCLUDE_GRAPH, and updateBoolOption().
Referenced by Step4().
setIncludeGraphEnabled [2/2]
void Step4::setIncludeGraphEnabled (int state) [private], [slot]
Member Data Documentation
m_diagramMode
QGroupBox * Step4::m_diagramMode = 0 [private]
Definition at line 207 of file wizard.h.
m_diagramModeGroup
QButtonGroup * Step4::m_diagramModeGroup = 0 [private]
Definition at line 208 of file wizard.h.
Referenced by init(), and Step4().
m_dotCall
QCheckBox * Step4::m_dotCall = 0 [private]
Definition at line 215 of file wizard.h.
Referenced by init(), and Step4().
m_dotCaller
QCheckBox * Step4::m_dotCaller = 0 [private]
Definition at line 216 of file wizard.h.
Referenced by init(), and Step4().
m_dotClass
QCheckBox * Step4::m_dotClass = 0 [private]
Definition at line 210 of file wizard.h.
Referenced by init(), and Step4().
m_dotCollaboration
QCheckBox * Step4::m_dotCollaboration = 0 [private]
Definition at line 211 of file wizard.h.
Referenced by init(), and Step4().
m_dotGroup
QGroupBox * Step4::m_dotGroup = 0 [private]
Definition at line 209 of file wizard.h.
Referenced by diagramModeChanged(), init(), and Step4().
m_dotInclude
QCheckBox * Step4::m_dotInclude = 0 [private]
Definition at line 212 of file wizard.h.
Referenced by init(), and Step4().
m_dotIncludedBy
QCheckBox * Step4::m_dotIncludedBy = 0 [private]
Definition at line 213 of file wizard.h.
Referenced by init(), and Step4().
m_dotInheritance
QCheckBox * Step4::m_dotInheritance = 0 [private]
Definition at line 214 of file wizard.h.
Referenced by init(), and Step4().
m_modelData
const QHash< QString, Input * > & Step4::m_modelData [private]
Definition at line 218 of file wizard.h.
Referenced by diagramModeChanged(), init(), setCallerGraphEnabled(), setCallGraphEnabled(), setClassGraphEnabled(), setCollaborationGraphEnabled(), setGraphicalHierarchyEnabled(), setIncludedByGraphEnabled(), and setIncludeGraphEnabled().
m_wizard
Wizard * Step4::m_wizard = 0 [private]
Definition at line 217 of file wizard.h.
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/wizard.h
doxygen/build/doxygen/addon/doxywizard/wizard.h
doxygen/addon/doxywizard/wizard.cpp
doxygen/build/doxygen/addon/doxywizard/wizard.cpp