PerlModOutput Class Reference
Public Member Functions
PerlModOutput (bool pretty)
virtual ~PerlModOutput ()
void setPerlModOutputStream (PerlModOutputStream *os)
PerlModOutput & continueBlock ()
PerlModOutput & add (char c)
PerlModOutput & add (const QCString &s)
PerlModOutput & add (QCString &s)
PerlModOutput & add (int n)
PerlModOutput & add (unsigned int n)
PerlModOutput & addQuoted (const QCString &s)
PerlModOutput & indent ()
PerlModOutput & open (char c, const QCString &s=QCString())
PerlModOutput & close (char c=0)
PerlModOutput & addField (const QCString &s)
PerlModOutput & addFieldQuotedChar (const QCString &field, char content)
PerlModOutput & addFieldQuotedString (const QCString &field, const QCString &content)
PerlModOutput & addFieldBoolean (const QCString &field, bool content)
PerlModOutput & openList (const QCString &s=QCString())
PerlModOutput & closeList ()
PerlModOutput & openHash (const QCString &s=QCString())
PerlModOutput & closeHash ()
PerlModOutput (bool pretty)
virtual ~PerlModOutput ()
void setPerlModOutputStream (PerlModOutputStream *os)
PerlModOutput & continueBlock ()
PerlModOutput & add (char c)
PerlModOutput & add (const QCString &s)
PerlModOutput & add (QCString &s)
PerlModOutput & add (int n)
PerlModOutput & add (unsigned int n)
PerlModOutput & addQuoted (const QCString &s)
PerlModOutput & indent ()
PerlModOutput & open (char c, const QCString &s=QCString())
PerlModOutput & close (char c=0)
PerlModOutput & addField (const QCString &s)
PerlModOutput & addFieldQuotedChar (const QCString &field, char content)
PerlModOutput & addFieldQuotedString (const QCString &field, const QCString &content)
PerlModOutput & addFieldBoolean (const QCString &field, bool content)
PerlModOutput & openList (const QCString &s=QCString())
PerlModOutput & closeList ()
PerlModOutput & openHash (const QCString &s=QCString())
PerlModOutput & closeHash ()
Public Attributes
bool m_pretty
Protected Member Functions
void incIndent ()
void decIndent ()
void iaddQuoted (const QCString &)
void iaddFieldQuotedChar (const QCString &, char)
void iaddFieldQuotedString (const QCString &, const QCString &)
void iaddField (const QCString &)
void iopen (char, const QCString &)
void iclose (char)
void incIndent ()
void decIndent ()
void iaddQuoted (const QCString &)
void iaddFieldQuotedChar (const QCString &, char)
void iaddFieldQuotedString (const QCString &, const QCString &)
void iaddField (const QCString &)
void iopen (char, const QCString &)
void iclose (char)
Private Attributes
PerlModOutputStream * m_stream
int m_indentation
bool m_blockstart
char m_spaces [PERLOUTPUT_MAX_INDENTATION *2+2]
Detailed Description
Definition at line 97 of file perlmodgen.cpp.
Constructor & Destructor Documentation
PerlModOutput() [1/2]
PerlModOutput::PerlModOutput (bool pretty) [inline]
Definition at line 103 of file perlmodgen.cpp.
    : m_pretty(pretty), m_stream(0), m_indentation(false), m_blockstart(true)
  {
    m_spaces[0] = 0;
  }
References m_spaces.
 PerlModOutput() [1/2]
virtual PerlModOutput::~PerlModOutput () [inline], [virtual]
Definition at line 109 of file perlmodgen.cpp.
{ }
PerlModOutput() [2/2]
PerlModOutput::PerlModOutput (bool pretty) [inline]
Definition at line 103 of file perlmodgen.cpp.
    : m_pretty(pretty), m_stream(0), m_indentation(false), m_blockstart(true)
  {
    m_spaces[0] = 0;
  }
References m_spaces.
 PerlModOutput() [2/2]
virtual PerlModOutput::~PerlModOutput () [inline], [virtual]
Definition at line 109 of file perlmodgen.cpp.
{ }
Member Function Documentation
add() [1/10]
PerlModOutput & PerlModOutput::add (char c) [inline]
Definition at line 126 of file perlmodgen.cpp.
{ m_stream->add(c); return *this; }
References PerlModOutputStream::add(), c, and m_stream.
Referenced by doxmlparser.compound.memberdefType::__init__(), addPerlModDocBlock(), doxmlparser.compound.memberdefType::buildAttributes(), PerlModDocVisitor::enterText(), doxmlparser.compound.memberdefType::exportAttributes(), PerlModDocVisitor::finish(), PerlModGenerator::generatePerlModOutput(), doxmlparser.compound.memberdefType::get_add(), PerlModDocVisitor::leaveText(), PerlModDocVisitor::operator()(), and doxmlparser.compound.memberdefType::set_add().
add() [2/10]
PerlModOutput & PerlModOutput::add (char c) [inline]
Definition at line 126 of file perlmodgen.cpp.
{ m_stream->add(c); return *this; }
References PerlModOutputStream::add(), c, and m_stream.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [3/10]
PerlModOutput & PerlModOutput::add (const QCString & s) [inline]
Definition at line 127 of file perlmodgen.cpp.
{ m_stream->add(s); return *this; }
References PerlModOutputStream::add(), m_stream, and s.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [4/10]
PerlModOutput & PerlModOutput::add (const QCString & s) [inline]
Definition at line 127 of file perlmodgen.cpp.
{ m_stream->add(s); return *this; }
References PerlModOutputStream::add(), m_stream, and s.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [5/10]
PerlModOutput & PerlModOutput::add (int n) [inline]
Definition at line 129 of file perlmodgen.cpp.
{ m_stream->add(n); return *this; }
References PerlModOutputStream::add(), m_stream, and n.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [6/10]
PerlModOutput & PerlModOutput::add (int n) [inline]
Definition at line 129 of file perlmodgen.cpp.
{ m_stream->add(n); return *this; }
References PerlModOutputStream::add(), m_stream, and n.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [7/10]
PerlModOutput & PerlModOutput::add (QCString & s) [inline]
Definition at line 128 of file perlmodgen.cpp.
{ m_stream->add(s); return *this; }
References PerlModOutputStream::add(), m_stream, and s.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [8/10]
PerlModOutput & PerlModOutput::add (QCString & s) [inline]
Definition at line 128 of file perlmodgen.cpp.
{ m_stream->add(s); return *this; }
References PerlModOutputStream::add(), m_stream, and s.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [9/10]
PerlModOutput & PerlModOutput::add (unsigned int n) [inline]
Definition at line 130 of file perlmodgen.cpp.
{ m_stream->add(n); return *this; }
References PerlModOutputStream::add(), m_stream, and n.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [10/10]
PerlModOutput & PerlModOutput::add (unsigned int n) [inline]
Definition at line 130 of file perlmodgen.cpp.
{ m_stream->add(n); return *this; }
References PerlModOutputStream::add(), m_stream, and n.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
addField() [1/2]
PerlModOutput & PerlModOutput::addField (const QCString & s) [inline]
Definition at line 146 of file perlmodgen.cpp.
{ iaddField(s); return *this; }
References iaddField(), and s.
Referenced by addPerlModDocBlock(), and PerlModDocVisitor::enterText().
addField() [2/2]
PerlModOutput & PerlModOutput::addField (const QCString & s) [inline]
Definition at line 146 of file perlmodgen.cpp.
{ iaddField(s); return *this; }
References iaddField(), and s.
addFieldBoolean() [1/2]
PerlModOutput & PerlModOutput::addFieldBoolean (const QCString & field, bool content) [inline]
Definition at line 155 of file perlmodgen.cpp.
  {
    return addFieldQuotedString(field, content ? "yes" : "no");
  }
References addFieldQuotedString().
Referenced by PerlModGenerator::addIncludeInfo(), PerlModGenerator::generatePerlModForMember(), and PerlModDocVisitor::operator()().
addFieldBoolean() [2/2]
PerlModOutput & PerlModOutput::addFieldBoolean (const QCString & field, bool content) [inline]
Definition at line 155 of file perlmodgen.cpp.
  {
    return addFieldQuotedString(field, content ? "yes" : "no");
  }
References addFieldQuotedString().
addFieldQuotedChar() [1/2]
PerlModOutput & PerlModOutput::addFieldQuotedChar (const QCString & field, char content) [inline]
Definition at line 147 of file perlmodgen.cpp.
  {
    iaddFieldQuotedChar(field, content); return *this;
  }
References iaddFieldQuotedChar().
Referenced by PerlModDocVisitor::operator()().
addFieldQuotedChar() [2/2]
PerlModOutput & PerlModOutput::addFieldQuotedChar (const QCString & field, char content) [inline]
Definition at line 147 of file perlmodgen.cpp.
  {
    iaddFieldQuotedChar(field, content); return *this;
  }
References iaddFieldQuotedChar().
addFieldQuotedString() [1/2]
PerlModOutput & PerlModOutput::addFieldQuotedString (const QCString & field, const QCString & content) [inline]
Definition at line 151 of file perlmodgen.cpp.
  {
    iaddFieldQuotedString(field, content); return *this;
  }
References iaddFieldQuotedString().
Referenced by addFieldBoolean(), PerlModGenerator::addIncludeInfo(), PerlModDocVisitor::addLink(), PerlModGenerator::addListOfAllMembers(), addTemplateArgumentList(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForConcept(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModForPage(), PerlModGenerator::generatePerlModSection(), PerlModGenerator::generatePerlUserDefinedSection(), PerlModDocVisitor::openItem(), and PerlModDocVisitor::operator()().
addFieldQuotedString() [2/2]
PerlModOutput & PerlModOutput::addFieldQuotedString (const QCString & field, const QCString & content) [inline]
Definition at line 151 of file perlmodgen.cpp.
  {
    iaddFieldQuotedString(field, content); return *this;
  }
References iaddFieldQuotedString().
addQuoted() [1/2]
PerlModOutput & PerlModOutput::addQuoted (const QCString & s) [inline]
Definition at line 132 of file perlmodgen.cpp.
{ iaddQuoted(s); return *this; }
References iaddQuoted(), and s.
Referenced by PerlModDocVisitor::operator()().
addQuoted() [2/2]
PerlModOutput & PerlModOutput::addQuoted (const QCString & s) [inline]
Definition at line 132 of file perlmodgen.cpp.
{ iaddQuoted(s); return *this; }
References iaddQuoted(), and s.
close() [1/2]
PerlModOutput & PerlModOutput::close (char c = 0) [inline]
Definition at line 144 of file perlmodgen.cpp.
{ iclose(c); return *this; }
References c, and iclose().
Referenced by closeHash(), and closeList().
close() [2/2]
PerlModOutput & PerlModOutput::close (char c = 0) [inline]
Definition at line 144 of file perlmodgen.cpp.
{ iclose(c); return *this; }
References c, and iclose().
closeHash() [1/2]
PerlModOutput & PerlModOutput::closeHash () [inline]
Definition at line 162 of file perlmodgen.cpp.
{ close('}'); return *this; }
References close().
Referenced by PerlModGenerator::addIncludeInfo(), PerlModGenerator::addListOfAllMembers(), addPerlModDocBlock(), addTemplateArgumentList(), PerlModDocVisitor::closeItem(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForConcept(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModForPage(), PerlModGenerator::generatePerlModOutput(), PerlModGenerator::generatePerlModSection(), PerlModGenerator::generatePerlUserDefinedSection(), PerlModDocVisitor::leaveText(), and PerlModDocVisitor::operator()().
closeHash() [2/2]
PerlModOutput & PerlModOutput::closeHash () [inline]
Definition at line 162 of file perlmodgen.cpp.
{ close('}'); return *this; }
References close().
closeList() [1/2]
PerlModOutput & PerlModOutput::closeList () [inline]
Definition at line 160 of file perlmodgen.cpp.
{ close(']'); return *this; }
References close().
Referenced by PerlModGenerator::addListOfAllMembers(), addTemplateArgumentList(), PerlModDocVisitor::closeSubBlock(), PerlModDocVisitor::finish(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModOutput(), PerlModGenerator::generatePerlModSection(), PerlModGenerator::generatePerlUserDefinedSection(), and PerlModDocVisitor::operator()().
closeList() [2/2]
PerlModOutput & PerlModOutput::closeList () [inline]
Definition at line 160 of file perlmodgen.cpp.
{ close(']'); return *this; }
References close().
continueBlock() [1/2]
PerlModOutput & PerlModOutput::continueBlock () [inline]
Definition at line 116 of file perlmodgen.cpp.
  {
    if (m_blockstart)
      m_blockstart = false;
    else
      m_stream->add(',');
    indent();
    return *this;
  }
References PerlModOutputStream::add(), indent(), m_blockstart, and m_stream.
Referenced by iaddField(), and iopen().
continueBlock() [2/2]
PerlModOutput & PerlModOutput::continueBlock () [inline]
Definition at line 116 of file perlmodgen.cpp.
  {
    if (m_blockstart)
      m_blockstart = false;
    else
      m_stream->add(',');
    indent();
    return *this;
  }
References PerlModOutputStream::add(), indent(), m_blockstart, and m_stream.
decIndent() [1/2]
void PerlModOutput::decIndent () [protected]
Definition at line 214 of file perlmodgen.cpp.
{
  m_indentation--;
  if (m_indentation < PERLOUTPUT_MAX_INDENTATION)
    m_spaces[m_indentation * 2] = 0;
}
References m_indentation, m_spaces, and PERLOUTPUT_MAX_INDENTATION.
Referenced by iclose().
decIndent() [2/2]
void PerlModOutput::decIndent () [protected]
iaddField() [1/2]
void PerlModOutput::iaddField (const QCString & s) [protected]
Definition at line 236 of file perlmodgen.cpp.
{
  continueBlock();
  m_stream->add(s);
  m_stream->add(m_pretty ? " => " : "=>");
}
References PerlModOutputStream::add(), continueBlock(), m_pretty, m_stream, and s.
Referenced by addField(), iaddFieldQuotedChar(), iaddFieldQuotedString(), and iopen().
iaddField() [2/2]
void PerlModOutput::iaddField (const QCString &) [protected]
iaddFieldQuotedChar() [1/2]
void PerlModOutput::iaddFieldQuotedChar (const QCString & field, char content) [protected]
Definition at line 243 of file perlmodgen.cpp.
{
  iaddField(field);
  m_stream->add('\'');
  if ((content == '\'') || (content == '\\'))
    m_stream->add('\\');
  m_stream->add(content);
  m_stream->add('\'');
}
References PerlModOutputStream::add(), iaddField(), and m_stream.
Referenced by addFieldQuotedChar().
iaddFieldQuotedChar() [2/2]
void PerlModOutput::iaddFieldQuotedChar (const QCString & , char) [protected]
iaddFieldQuotedString() [1/2]
void PerlModOutput::iaddFieldQuotedString (const QCString & field, const QCString & content) [protected]
Definition at line 253 of file perlmodgen.cpp.
{
  if (content == 0)
    return;
  iaddField(field);
  m_stream->add('\'');
  iaddQuoted(content);
  m_stream->add('\'');
}
References PerlModOutputStream::add(), iaddField(), iaddQuoted(), and m_stream.
Referenced by addFieldQuotedString().
iaddFieldQuotedString() [2/2]
void PerlModOutput::iaddFieldQuotedString (const QCString & , const QCString &) [protected]
iaddQuoted() [1/2]
void PerlModOutput::iaddQuoted (const QCString & str) [protected]
Definition at line 221 of file perlmodgen.cpp.
{
  if (str.isEmpty()) return;
  const char *s = str.data();
  char c;
  while ((c = *s++) != 0)
  {
    if ((c == '\'') || (c == '\\'))
    {
      m_stream->add('\\');
    }
    m_stream->add(c);
  }
}
References PerlModOutputStream::add(), c, QCString::data(), QCString::isEmpty(), m_stream, and s.
Referenced by addQuoted(), and iaddFieldQuotedString().
iaddQuoted() [2/2]
void PerlModOutput::iaddQuoted (const QCString &) [protected]
iclose() [1/2]
void PerlModOutput::iclose (char c) [protected]
Definition at line 274 of file perlmodgen.cpp.
{
  decIndent();
  indent();
  if (c != 0)
    m_stream->add(c);
  m_blockstart = false;
}
References PerlModOutputStream::add(), c, decIndent(), indent(), m_blockstart, and m_stream.
Referenced by close().
iclose() [2/2]
void PerlModOutput::iclose (char) [protected]
incIndent() [1/2]
void PerlModOutput::incIndent () [protected]
Definition at line 204 of file perlmodgen.cpp.
{
  if (m_indentation < PERLOUTPUT_MAX_INDENTATION)
  {
    char *s = &m_spaces[m_indentation * 2];
    *s++ = ' '; *s++ = ' '; *s = 0;
  }
  m_indentation++;
}
References m_indentation, m_spaces, PERLOUTPUT_MAX_INDENTATION, and s.
Referenced by iopen().
incIndent() [2/2]
void PerlModOutput::incIndent () [protected]
indent() [1/2]
PerlModOutput & PerlModOutput::indent () [inline]
Definition at line 134 of file perlmodgen.cpp.
  {
    if (m_pretty) {
      m_stream->add('\n');
      m_stream->add(m_spaces);
    }
    return *this;
  }
References PerlModOutputStream::add(), m_pretty, m_spaces, and m_stream.
Referenced by continueBlock(), and iclose().
indent() [2/2]
PerlModOutput & PerlModOutput::indent () [inline]
Definition at line 134 of file perlmodgen.cpp.
  {
    if (m_pretty) {
      m_stream->add('\n');
      m_stream->add(m_spaces);
    }
    return *this;
  }
References PerlModOutputStream::add(), m_pretty, m_spaces, and m_stream.
iopen() [1/2]
void PerlModOutput::iopen (char c, const QCString & s) [protected]
Definition at line 263 of file perlmodgen.cpp.
{
  if (s != 0)
    iaddField(s);
  else
    continueBlock();
  m_stream->add(c);
  incIndent();
  m_blockstart = true;
}
References PerlModOutputStream::add(), c, continueBlock(), iaddField(), incIndent(), m_blockstart, m_stream, and s.
Referenced by open().
iopen() [2/2]
void PerlModOutput::iopen (char , const QCString &) [protected]
open() [1/2]
PerlModOutput & PerlModOutput::open (char c, const QCString & s = QCString()) [inline]
Definition at line 143 of file perlmodgen.cpp.
{ iopen(c, s); return *this; }
References c, iopen(), and s.
Referenced by openHash(), and openList().
open() [2/2]
PerlModOutput & PerlModOutput::open (char c, const QCString & s = QCString()) [inline]
Definition at line 143 of file perlmodgen.cpp.
{ iopen(c, s); return *this; }
References c, iopen(), and s.
openHash() [1/2]
PerlModOutput & PerlModOutput::openHash (const QCString & s = QCString()) [inline]
Definition at line 161 of file perlmodgen.cpp.
{ open('{', s); return *this; }
References open(), and s.
Referenced by PerlModGenerator::addIncludeInfo(), PerlModGenerator::addListOfAllMembers(), addPerlModDocBlock(), addTemplateArgumentList(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForConcept(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModForPage(), PerlModGenerator::generatePerlModOutput(), PerlModGenerator::generatePerlModSection(), PerlModGenerator::generatePerlUserDefinedSection(), PerlModDocVisitor::openItem(), and PerlModDocVisitor::operator()().
openHash() [2/2]
PerlModOutput & PerlModOutput::openHash (const QCString & s = QCString()) [inline]
Definition at line 161 of file perlmodgen.cpp.
{ open('{', s); return *this; }
References open(), and s.
openList() [1/2]
PerlModOutput & PerlModOutput::openList (const QCString & s = QCString()) [inline]
Definition at line 159 of file perlmodgen.cpp.
{ open('[', s); return *this; }
References open(), and s.
Referenced by PerlModGenerator::addListOfAllMembers(), addTemplateArgumentList(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModOutput(), PerlModGenerator::generatePerlModSection(), PerlModGenerator::generatePerlUserDefinedSection(), PerlModDocVisitor::openSubBlock(), PerlModDocVisitor::operator()(), and PerlModDocVisitor::PerlModDocVisitor().
openList() [2/2]
PerlModOutput & PerlModOutput::openList (const QCString & s = QCString()) [inline]
Definition at line 159 of file perlmodgen.cpp.
{ open('[', s); return *this; }
References open(), and s.
setPerlModOutputStream() [1/2]
void PerlModOutput::setPerlModOutputStream (PerlModOutputStream * os) [inline]
Definition at line 111 of file perlmodgen.cpp.
{ m_stream = os; }
References m_stream.
Referenced by PerlModGenerator::generatePerlModOutput().
setPerlModOutputStream() [2/2]
void PerlModOutput::setPerlModOutputStream (PerlModOutputStream * os) [inline]
Definition at line 111 of file perlmodgen.cpp.
{ m_stream = os; }
References m_stream.
Member Data Documentation
m_blockstart
bool PerlModOutput::m_blockstart [private]
Definition at line 184 of file perlmodgen.cpp.
Referenced by continueBlock(), iclose(), and iopen().
m_indentation
int PerlModOutput::m_indentation [private]
Definition at line 183 of file perlmodgen.cpp.
Referenced by decIndent(), and incIndent().
m_pretty
bool PerlModOutput::m_pretty
Definition at line 101 of file perlmodgen.cpp.
Referenced by iaddField(), and indent().
m_spaces
char PerlModOutput::m_spaces [private]
Definition at line 187 of file perlmodgen.cpp.
Referenced by decIndent(), incIndent(), indent(), and PerlModOutput().
m_stream
PerlModOutputStream * PerlModOutput::m_stream [private]
Definition at line 182 of file perlmodgen.cpp.
Referenced by add(), continueBlock(), iaddField(), iaddFieldQuotedChar(), iaddFieldQuotedString(), iaddQuoted(), iclose(), indent(), iopen(), and setPerlModOutputStream().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/perlmodgen.cpp
doxygen/src/perlmodgen.cpp