vhdl::parser::ErrorHandler Class Reference
#include <ErrorHandler.h>
Public Member Functions
virtual void handleUnexpectedToken (int expectedKind, const JJString &expectedToken, Token *actual, VhdlParser *parser)
virtual void handleParseError (Token *last, Token *unexpected, const JJSimpleString &production, VhdlParser *parser)
virtual int getErrorCount ()
virtual void handleOtherError (const JJString &message, VhdlParser *parser)
virtual ~ErrorHandler ()
ErrorHandler ()
virtual void handleUnexpectedToken (int expectedKind, const JJString &expectedToken, Token *actual, VhdlParser *parser)
virtual void handleParseError (Token *last, Token *unexpected, const JJSimpleString &production, VhdlParser *parser)
virtual int getErrorCount ()
virtual void handleOtherError (const JJString &message, VhdlParser *parser)
virtual ~ErrorHandler ()
ErrorHandler ()
Protected Attributes
int error_count
Friends
class VhdlParserTokenManager
class VhdlParser
Detailed Description
Definition at line 17 of file ErrorHandler.h.
Constructor & Destructor Documentation
 ErrorHandler() [1/2]
virtual vhdl::parser::ErrorHandler::~ErrorHandler () [inline], [virtual]
Definition at line 46 of file ErrorHandler.h.
{}
ErrorHandler() [1/2]
vhdl::parser::ErrorHandler::ErrorHandler () [inline]
Definition at line 47 of file ErrorHandler.h.
{ error_count = 0; }
References error_count.
 ErrorHandler() [2/2]
virtual vhdl::parser::ErrorHandler::~ErrorHandler () [inline], [virtual]
Definition at line 46 of file ErrorHandler.h.
{}
ErrorHandler() [2/2]
vhdl::parser::ErrorHandler::ErrorHandler () [inline]
Definition at line 47 of file ErrorHandler.h.
{ error_count = 0; }
References error_count.
Member Function Documentation
getErrorCount() [1/2]
virtual int vhdl::parser::ErrorHandler::getErrorCount () [inline], [virtual]
Definition at line 40 of file ErrorHandler.h.
                                  {
        return error_count;
      }
References error_count.
getErrorCount() [2/2]
virtual int vhdl::parser::ErrorHandler::getErrorCount () [inline], [virtual]
Definition at line 40 of file ErrorHandler.h.
                                  {
        return error_count;
      }
References error_count.
handleOtherError() [1/2]
virtual void vhdl::parser::ErrorHandler::handleOtherError (const JJString & message, VhdlParser * parser) [inline], [virtual]
Reimplemented in vhdl::parser::VhdlErrorHandler, and vhdl::parser::VhdlErrorHandler.
Definition at line 43 of file ErrorHandler.h.
                                                                                 {
        fprintf(stderr, "Error: %s\n", (char*)message.c_str());
      }
handleOtherError() [2/2]
virtual void vhdl::parser::ErrorHandler::handleOtherError (const JJString & message, VhdlParser * parser) [inline], [virtual]
Reimplemented in vhdl::parser::VhdlErrorHandler, and vhdl::parser::VhdlErrorHandler.
Definition at line 43 of file ErrorHandler.h.
                                                                                 {
        fprintf(stderr, "Error: %s\n", (char*)message.c_str());
      }
handleParseError() [1/2]
virtual void vhdl::parser::ErrorHandler::handleParseError (Token * last, Token * unexpected, const JJSimpleString & production, VhdlParser * parser) [inline], [virtual]
Reimplemented in vhdl::parser::VhdlErrorHandler, and vhdl::parser::VhdlErrorHandler.
Definition at line 36 of file ErrorHandler.h.
                                                                                                                          {
        error_count++;
        fprintf(stderr, "Encountered: %s at: %d:%d while parsing: %s\n", addUnicodeEscapes(unexpected->image).c_str(), unexpected->beginLine, unexpected->beginColumn, production.c_str());
      }
References vhdl::parser::addUnicodeEscapes(), vhdl::parser::Token::beginColumn, vhdl::parser::Token::beginLine, error_count, and vhdl::parser::Token::image.
Referenced by vhdl::parser::VhdlParser::absolute_pathname(), vhdl::parser::VhdlParser::abstract_literal(), vhdl::parser::VhdlParser::actual_designator(), vhdl::parser::VhdlParser::actual_part(), vhdl::parser::VhdlParser::adding_operator(), vhdl::parser::VhdlParser::alias_designator(), vhdl::parser::VhdlParser::allocator(), vhdl::parser::VhdlParser::array_type_definition(), vhdl::parser::VhdlParser::attribute_designator(), vhdl::parser::VhdlParser::attribute_name(), vhdl::parser::VhdlParser::block_declarative_item(), vhdl::parser::VhdlParser::choice(), vhdl::parser::VhdlParser::composite_type_definition(), vhdl::parser::VhdlParser::concurrent_signal_assignment_statement(), vhdl::parser::VhdlParser::concurrent_statement(), vhdl::parser::VhdlParser::conditional_signal_assignment_wave(), vhdl::parser::VhdlParser::configuration_declarative_item(), vhdl::parser::VhdlParser::configuration_item(), vhdl::parser::VhdlParser::constraint(), vhdl::parser::VhdlParser::context_item(), vhdl::parser::VhdlParser::delay_mechanism(), vhdl::parser::VhdlParser::design_file(), vhdl::parser::VhdlParser::designator(), vhdl::parser::VhdlParser::direction(), vhdl::parser::VhdlParser::discrete_range(), vhdl::parser::VhdlParser::entity_aspect(), vhdl::parser::VhdlParser::entity_class(), vhdl::parser::VhdlParser::entity_declarative_item(), vhdl::parser::VhdlParser::entity_name_list(), vhdl::parser::VhdlParser::entity_statement(), vhdl::parser::VhdlParser::entity_tag(), vhdl::parser::VhdlParser::enumeration_literal(), vhdl::parser::VhdlParser::external_pathname(), vhdl::parser::VhdlParser::factor(), vhdl::parser::VhdlParser::formal_designator(), vhdl::parser::VhdlParser::generate_scheme(), vhdl::parser::VhdlParser::group_constituent(), vhdl::parser::VhdlParser::identifier(), vhdl::parser::VhdlParser::ifunc(), vhdl::parser::VhdlParser::index_specification(), vhdl::parser::VhdlParser::inout_stat(), vhdl::parser::VhdlParser::instantiation_list(), vhdl::parser::VhdlParser::instantiation_unit(), vhdl::parser::VhdlParser::interface_declaration(), vhdl::parser::VhdlParser::interface_subprogram_declaration(), vhdl::parser::VhdlParser::interface_variable_declaration(), vhdl::parser::VhdlParser::iteration_scheme(), vhdl::parser::VhdlParser::library_unit(), vhdl::parser::VhdlParser::libustcont_stats(), vhdl::parser::VhdlParser::literal(), vhdl::parser::VhdlParser::logop(), vhdl::parser::VhdlParser::miscellaneous_operator(), vhdl::parser::VhdlParser::mode(), vhdl::parser::VhdlParser::multiplying_operation(), vhdl::parser::VhdlParser::name(), vhdl::parser::VhdlParser::name_ext(), vhdl::parser::VhdlParser::numeric_literal(), vhdl::parser::VhdlParser::object_class(), vhdl::parser::VhdlParser::package_body_declarative_item(), vhdl::parser::VhdlParser::package_declarative_item(), vhdl::parser::VhdlParser::parseInline(), vhdl::parser::VhdlParser::primary(), vhdl::parser::VhdlParser::primary_unit(), vhdl::parser::VhdlParser::process_declarative_item(), vhdl::parser::VhdlParser::protected_type_body_declarative_item(), vhdl::parser::VhdlParser::protected_type_declarative_item(), vhdl::parser::VhdlParser::qualified_expression(), vhdl::parser::VhdlParser::range(), vhdl::parser::VhdlParser::relation_operator(), vhdl::parser::VhdlParser::scalar_type_definition(), vhdl::parser::VhdlParser::secondary_unit(), vhdl::parser::VhdlParser::sel_var_list(), vhdl::parser::VhdlParser::select_name(), vhdl::parser::VhdlParser::selected_signal_assignment_wave(), vhdl::parser::VhdlParser::sensitivity_list(), vhdl::parser::VhdlParser::sequential_statement(), vhdl::parser::VhdlParser::shift_operator(), vhdl::parser::VhdlParser::sig_stat(), vhdl::parser::VhdlParser::sign(), vhdl::parser::VhdlParser::signal_assignment_statement(), vhdl::parser::VhdlParser::signal_kind(), vhdl::parser::VhdlParser::signal_list(), vhdl::parser::VhdlParser::subprogram_1(), vhdl::parser::VhdlParser::subprogram_declaration(), vhdl::parser::VhdlParser::subprogram_declarative_item(), vhdl::parser::VhdlParser::subprogram_kind(), vhdl::parser::VhdlParser::subprogram_specification(), vhdl::parser::VhdlParser::suffix(), vhdl::parser::VhdlParser::target(), vhdl::parser::VhdlParser::type_declaration(), vhdl::parser::VhdlParser::type_definition(), vhdl::parser::VhdlParser::variable_assignment_statement(), and vhdl::parser::VhdlParser::waveform().
handleParseError() [2/2]
virtual void vhdl::parser::ErrorHandler::handleParseError (Token * last, Token * unexpected, const JJSimpleString & production, VhdlParser * parser) [inline], [virtual]
Reimplemented in vhdl::parser::VhdlErrorHandler, and vhdl::parser::VhdlErrorHandler.
Definition at line 36 of file ErrorHandler.h.
                                                                                                                          {
        error_count++;
        fprintf(stderr, "Encountered: %s at: %d:%d while parsing: %s\n", addUnicodeEscapes(unexpected->image).c_str(), unexpected->beginLine, unexpected->beginColumn, production.c_str());
      }
References vhdl::parser::addUnicodeEscapes(), vhdl::parser::Token::beginColumn, vhdl::parser::Token::beginLine, error_count, and vhdl::parser::Token::image.
handleUnexpectedToken() [1/2]
virtual void vhdl::parser::ErrorHandler::handleUnexpectedToken (int expectedKind, const JJString & expectedToken, Token * actual, VhdlParser * parser) [inline], [virtual]
Reimplemented in vhdl::parser::VhdlErrorHandler, and vhdl::parser::VhdlErrorHandler.
Definition at line 28 of file ErrorHandler.h.
                                                                                                                             {
        error_count++;
        fprintf(stderr, "Expecting %s at: %d:%d but got %s\n", addUnicodeEscapes(expectedToken).c_str(), actual->beginLine, actual->beginColumn, addUnicodeEscapes(actual->image).c_str());
      }
References vhdl::parser::addUnicodeEscapes(), vhdl::parser::Token::beginColumn, vhdl::parser::Token::beginLine, error_count, and vhdl::parser::Token::image.
Referenced by vhdl::parser::VhdlParser::jj_consume_token().
handleUnexpectedToken() [2/2]
virtual void vhdl::parser::ErrorHandler::handleUnexpectedToken (int expectedKind, const JJString & expectedToken, Token * actual, VhdlParser * parser) [inline], [virtual]
Reimplemented in vhdl::parser::VhdlErrorHandler, and vhdl::parser::VhdlErrorHandler.
Definition at line 28 of file ErrorHandler.h.
                                                                                                                             {
        error_count++;
        fprintf(stderr, "Expecting %s at: %d:%d but got %s\n", addUnicodeEscapes(expectedToken).c_str(), actual->beginLine, actual->beginColumn, addUnicodeEscapes(actual->image).c_str());
      }
References vhdl::parser::addUnicodeEscapes(), vhdl::parser::Token::beginColumn, vhdl::parser::Token::beginLine, error_count, and vhdl::parser::Token::image.
Friends And Related Function Documentation
VhdlParser
VhdlParser [friend]
Definition at line 19 of file ErrorHandler.h.
VhdlParserTokenManager
VhdlParserTokenManager [friend]
Definition at line 18 of file ErrorHandler.h.
Member Data Documentation
error_count
int vhdl::parser::ErrorHandler::error_count [protected]
Definition at line 21 of file ErrorHandler.h.
Referenced by ErrorHandler(), getErrorCount(), vhdl::parser::VhdlErrorHandler::handleOtherError(), handleParseError(), vhdl::parser::VhdlErrorHandler::handleParseError(), handleUnexpectedToken(), and vhdl::parser::VhdlErrorHandler::handleUnexpectedToken().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/vhdlparser/ErrorHandler.h
doxygen/vhdlparser/ErrorHandler.h