DocHtmlDetails Class Reference
#include <docnode.h>
Public Member Functions
DocHtmlDetails (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs)
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
void parseSummary (DocNodeVariant *, HtmlAttribList &attribs)
const DocNodeVariant * summary () const
DocHtmlDetails (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs)
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
void parseSummary (DocNodeVariant *, HtmlAttribList &attribs)
const DocNodeVariant * summary () const
Private Attributes
HtmlAttribList m_attribs
std::unique_ptr< DocNodeVariant > m_summary
Additional Inherited Members
Detailed Description
Node Html details
Definition at line 809 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlDetails() [1/2]
DocHtmlDetails::DocHtmlDetails (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs) [inline]
Definition at line 812 of file docnode.h.
                                                                                           :
       DocCompoundNode(parser,parent), m_attribs(attribs) {}
DocHtmlDetails() [2/2]
DocHtmlDetails::DocHtmlDetails (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs) [inline]
Definition at line 812 of file docnode.h.
                                                                                           :
       DocCompoundNode(parser,parent), m_attribs(attribs) {}
Member Function Documentation
attribs() [1/2]
const HtmlAttribList & DocHtmlDetails::attribs () const [inline]
Definition at line 814 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by HtmlDocVisitor::operator()(), and parseSummary().
attribs() [2/2]
const HtmlAttribList & DocHtmlDetails::attribs () const [inline]
Definition at line 814 of file docnode.h.
{ return m_attribs; }
References m_attribs.
parse() [1/2]
int DocHtmlDetails::parse (DocNodeVariant * thisVariant)
Definition at line 1315 of file docnode.cpp.
{
  DBG(("DocHtmlDetails::parse() start\n"));
  int retval=0;
  auto ns = AutoNodeStack(parser(),thisVariant);
  // parse one or more paragraphs
  bool isFirst=TRUE;
  DocPara *par=0;
  do
  {
    auto vDocPara = children().append<DocPara>(parser(),thisVariant);
    par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse(vDocPara);
  }
  while (retval==TK_NEWPARA);
  if (par) par->markLast();
  DBG(("DocHtmlDetails::parse() end retval=%s\n",DocTokenizer::retvalToString(retval)));
  return (retval==RetVal_EndHtmlDetails) ? RetVal_OK : retval;
}
References DocNodeList::append(), DocCompoundNode::children(), DBG, FALSE, DocNodeList::get_last(), DocPara::markFirst(), DocPara::markLast(), DocPara::parse(), DocNode::parser(), RetVal_EndHtmlDetails, RetVal_OK, DocTokenizer::retvalToString(), TK_NEWPARA, and TRUE.
parse() [2/2]
int DocHtmlDetails::parse (DocNodeVariant *)
parseSummary() [1/2]
void DocHtmlDetails::parseSummary (DocNodeVariant * thisVariant, HtmlAttribList & attribs)
Definition at line 1338 of file docnode.cpp.
{
  DBG(("DocHtmlDetails::parseSummary() start\n"));
  m_summary = std::make_unique<DocNodeVariant>(DocHtmlSummary(parser(),thisVariant,attribs));
  DocHtmlSummary *summary = &std::get<DocHtmlSummary>(*m_summary);
  summary->parse(m_summary.get());
  DBG(("DocHtmlDetails::parseSummary() end\n"));
}
References attribs(), DBG, m_summary, DocNode::parser(), and summary().
Referenced by DocPara::handleHtmlStartTag().
parseSummary() [2/2]
void DocHtmlDetails::parseSummary (DocNodeVariant * , HtmlAttribList & attribs)
summary() [1/2]
const DocNodeVariant * DocHtmlDetails::summary () const [inline]
Definition at line 817 of file docnode.h.
{ return m_summary.get(); }
References m_summary.
Referenced by doxmlparser.compound.docDetailsType::__init__(), doxmlparser.compound.docDetailsType::get_summary(), DocPara::handleHtmlStartTag(), doxmlparser.compound.docDetailsType::hasContent_(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), parseSummary(), and doxmlparser.compound.docDetailsType::set_summary().
summary() [2/2]
const DocNodeVariant * DocHtmlDetails::summary () const [inline]
Definition at line 817 of file docnode.h.
{ return m_summary.get(); }
References m_summary.
Referenced by doxmlparser.compound.docDetailsType::__init__(), doxmlparser.compound.docDetailsType::get_summary(), doxmlparser.compound.docDetailsType::hasContent_(), and doxmlparser.compound.docDetailsType::set_summary().
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlDetails::m_attribs [private]
Definition at line 820 of file docnode.h.
Referenced by attribs().
m_summary
std::unique_ptr< DocNodeVariant > DocHtmlDetails::m_summary [private]
Definition at line 821 of file docnode.h.
Referenced by parseSummary(), and summary().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp