CallContext Class Reference
#include <scopedtypevariant.h>
Classes
struct Ctx
Public Member Functions
CallContext ()
void setScope (const ScopedTypeVariant &stv)
void pushScope (const QCString &name_, const QCString &type_)
void popScope (QCString &name_, QCString &type_)
void clear ()
const ScopedTypeVariant getScope () const
CallContext ()
void setScope (const ScopedTypeVariant &stv)
void pushScope (const QCString &name_, const QCString &type_)
void popScope (QCString &name_, QCString &type_)
void clear ()
const ScopedTypeVariant getScope () const
Private Attributes
std::vector< Ctx > m_stvList
Detailed Description
Represents the call context
Definition at line 244 of file scopedtypevariant.h.
Constructor & Destructor Documentation
CallContext() [1/2]
CallContext::CallContext () [inline]
Definition at line 255 of file scopedtypevariant.h.
    {
      clear();
    }
References clear().
CallContext() [2/2]
CallContext::CallContext () [inline]
Definition at line 255 of file scopedtypevariant.h.
    {
      clear();
    }
References clear().
Member Function Documentation
clear() [1/2]
void CallContext::clear () [inline]
Definition at line 278 of file scopedtypevariant.h.
    {
      m_stvList.clear();
      m_stvList.push_back(Ctx(QCString(),QCString()));
    }
References m_stvList.
Referenced by CallContext().
clear() [2/2]
void CallContext::clear () [inline]
Definition at line 278 of file scopedtypevariant.h.
    {
      m_stvList.clear();
      m_stvList.push_back(Ctx(QCString(),QCString()));
    }
References m_stvList.
getScope() [1/2]
const ScopedTypeVariant CallContext::getScope () const [inline]
Definition at line 283 of file scopedtypevariant.h.
    {
      return m_stvList.back().stv;
    }
References m_stvList.
getScope() [2/2]
const ScopedTypeVariant CallContext::getScope () const [inline]
Definition at line 283 of file scopedtypevariant.h.
    {
      return m_stvList.back().stv;
    }
References m_stvList.
popScope() [1/2]
void CallContext::popScope (QCString & name_, QCString & type_) [inline]
Definition at line 268 of file scopedtypevariant.h.
    {
      if (m_stvList.size()>1)
      {
        const Ctx &ctx = m_stvList.back();
        name_ = ctx.name;
        type_ = ctx.type;
        m_stvList.pop_back();
      }
    }
References m_stvList, CallContext::Ctx::name, and CallContext::Ctx::type.
popScope() [2/2]
void CallContext::popScope (QCString & name_, QCString & type_) [inline]
Definition at line 268 of file scopedtypevariant.h.
    {
      if (m_stvList.size()>1)
      {
        const Ctx &ctx = m_stvList.back();
        name_ = ctx.name;
        type_ = ctx.type;
        m_stvList.pop_back();
      }
    }
References m_stvList.
pushScope() [1/2]
void CallContext::pushScope (const QCString & name_, const QCString & type_) [inline]
Definition at line 264 of file scopedtypevariant.h.
    {
      m_stvList.push_back(Ctx(name_,type_));
    }
References m_stvList.
pushScope() [2/2]
void CallContext::pushScope (const QCString & name_, const QCString & type_) [inline]
Definition at line 264 of file scopedtypevariant.h.
    {
      m_stvList.push_back(Ctx(name_,type_));
    }
References m_stvList.
setScope() [1/2]
void CallContext::setScope (const ScopedTypeVariant & stv) [inline]
Definition at line 259 of file scopedtypevariant.h.
    {
      Ctx &ctx = m_stvList.back();
      ctx.stv=std::move(stv);
    }
References m_stvList, and CallContext::Ctx::stv.
setScope() [2/2]
void CallContext::setScope (const ScopedTypeVariant & stv) [inline]
Definition at line 259 of file scopedtypevariant.h.
    {
      Ctx &ctx = m_stvList.back();
      ctx.stv=std::move(stv);
    }
References m_stvList.
Member Data Documentation
m_stvList
std::vector< Ctx > CallContext::m_stvList [private]
Definition at line 289 of file scopedtypevariant.h.
Referenced by clear(), getScope(), popScope(), pushScope(), and setScope().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/scopedtypevariant.h
doxygen/src/scopedtypevariant.h