FilterFlatten Class Reference
The implementation of the `flatten` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Static Private Member Functions
static void flatten (const TemplateListIntfPtr tree, TemplateListPtr list)
static void flatten (const TemplateListIntfPtr tree, TemplateListPtr list)
Detailed Description
The implementation of the `flatten` filter.
Definition at line 1014 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterFlatten::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1017 of file template.cpp.
    {
      if (!v.isValid() || !v.isList())
      {
        return v;
      }
      else
      {
        TemplateListPtr list = TemplateList::alloc();
        TemplateListIntfPtr tree = v.toList();
        flatten(tree,list);
        return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(list));
      }
    }
References TemplateList::alloc(), flatten(), TemplateVariant::isList(), TemplateVariant::isValid(), and TemplateVariant::toList().
apply() [2/2]
static TemplateVariant FilterFlatten::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1017 of file template.cpp.
    {
      if (!v.isValid() || !v.isList())
      {
        return v;
      }
      else
      {
        TemplateListPtr list = TemplateList::alloc();
        TemplateListIntfPtr tree = v.toList();
        flatten(tree,list);
        return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(list));
      }
    }
References TemplateList::alloc(), TemplateVariant::isList(), TemplateVariant::isValid(), and TemplateVariant::toList().
flatten() [1/2]
static void FilterFlatten::flatten (const TemplateListIntfPtr tree, TemplateListPtr list) [inline], [static], [private]
Definition at line 1033 of file template.cpp.
    {
      if (tree)
      {
        TemplateListIntf::ConstIteratorPtr it = tree->createIterator();
        TemplateVariant item;
        for (it->toFirst();(it->current(item));it->toNext())
        {
          TemplateStructIntfPtr s = item.toStruct();
          if (s)
          {
            list->append(item);
            // if s has "children" then recurse into the children
            TemplateVariant children = s->get("children");
            if (children.isValid() && children.isList())
            {
              flatten(children.toList(),list);
            }
          }
          else
          {
            list->append(item);
          }
        }
      }
    }
References flatten(), TemplateVariant::isList(), TemplateVariant::isValid(), s, TemplateVariant::toList(), and TemplateVariant::toStruct().
Referenced by apply(), and flatten().
flatten() [2/2]
static void FilterFlatten::flatten (const TemplateListIntfPtr tree, TemplateListPtr list) [inline], [static], [private]
Definition at line 1033 of file template.cpp.
    {
      if (tree)
      {
        TemplateListIntf::ConstIteratorPtr it = tree->createIterator();
        TemplateVariant item;
        for (it->toFirst();(it->current(item));it->toNext())
        {
          TemplateStructIntfPtr s = item.toStruct();
          if (s)
          {
            list->append(item);
            // if s has "children" then recurse into the children
            TemplateVariant children = s->get("children");
            if (children.isValid() && children.isList())
            {
              flatten(children.toList(),list);
            }
          }
          else
          {
            list->append(item);
          }
        }
      }
    }
References TemplateVariant::isList(), TemplateVariant::isValid(), s, TemplateVariant::toList(), and TemplateVariant::toStruct().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp