BufStr Class Reference
Buffer used to store strings.
#include <bufstr.h>
Public Member Functions
BufStr (size_t size)
~BufStr ()
void addChar (char c)
void addArray (const char *a, size_t len)
void skip (size_t s)
void shrink (size_t newlen)
void resize (size_t newlen)
size_t size () const
char * data () const
char & at (size_t i) const
bool isEmpty () const
operator const char * () const
size_t curPos () const
void dropFromStart (size_t bytes)
void addTerminalCharIfMissing (char c)
BufStr (size_t size)
~BufStr ()
void addChar (char c)
void addArray (const char *a, size_t len)
void skip (size_t s)
void shrink (size_t newlen)
void resize (size_t newlen)
size_t size () const
char * data () const
char & at (size_t i) const
bool isEmpty () const
operator const char * () const
size_t curPos () const
void dropFromStart (size_t bytes)
void addTerminalCharIfMissing (char c)
Private Member Functions
void makeRoomFor (size_t size)
void makeRoomFor (size_t size)
Private Attributes
size_t m_size
size_t m_writeOffset
const size_t m_spareRoom
char * m_buf
Detailed Description
Buffer used to store strings.
This buffer is used append characters and strings. It will automatically resize itself, yet provide efficient random access to the content.
Definition at line 29 of file bufstr.h.
Constructor & Destructor Documentation
BufStr() [1/2]
BufStr::BufStr (size_t size) [inline]
Definition at line 32 of file bufstr.h.
      : m_size(size), m_writeOffset(0), m_spareRoom(10240), m_buf(0)
    {
      m_buf = static_cast<char *>(calloc(size,1));
    }
References m_buf, and size().
 BufStr() [1/2]
BufStr::~BufStr () [inline]
Definition at line 37 of file bufstr.h.
    {
      free(m_buf);
    }
References m_buf.
BufStr() [2/2]
BufStr::BufStr (size_t size) [inline]
Definition at line 32 of file bufstr.h.
      : m_size(size), m_writeOffset(0), m_spareRoom(10240), m_buf(0)
    {
      m_buf = static_cast<char *>(calloc(size,1));
    }
References m_buf, and size().
 BufStr() [2/2]
BufStr::~BufStr () [inline]
Definition at line 37 of file bufstr.h.
    {
      free(m_buf);
    }
References m_buf.
Member Function Documentation
addArray() [1/2]
void BufStr::addArray (const char * a, size_t len) [inline]
Definition at line 46 of file bufstr.h.
    {
      makeRoomFor(len);
      memcpy(m_buf+m_writeOffset,a,len);
      m_writeOffset+=len;
    }
References a, len, m_buf, m_writeOffset, and makeRoomFor().
Referenced by FilterCache::getFileContents(), and readInputFile().
addArray() [2/2]
void BufStr::addArray (const char * a, size_t len) [inline]
Definition at line 46 of file bufstr.h.
    {
      makeRoomFor(len);
      memcpy(m_buf+m_writeOffset,a,len);
      m_writeOffset+=len;
    }
References a, len, m_buf, m_writeOffset, and makeRoomFor().
addChar() [1/2]
void BufStr::addChar (char c) [inline]
Definition at line 41 of file bufstr.h.
    {
      makeRoomFor(1);
      m_buf[m_writeOffset++]=c;
    }
References c, m_buf, m_writeOffset, and makeRoomFor().
Referenced by addTerminalCharIfMissing(), fileToString(), FilterCache::getFileContents(), parseFile(), and readInputFile().
addChar() [2/2]
void BufStr::addChar (char c) [inline]
Definition at line 41 of file bufstr.h.
    {
      makeRoomFor(1);
      m_buf[m_writeOffset++]=c;
    }
References c, m_buf, m_writeOffset, and makeRoomFor().
addTerminalCharIfMissing() [1/2]
void BufStr::addTerminalCharIfMissing (char c) [inline]
Definition at line 107 of file bufstr.h.
    {
      if (m_buf && m_writeOffset>1 && m_buf[m_writeOffset-2]!=c && m_buf[m_writeOffset-1]=='\0')
      {
        // add missing terminal character and 0 terminator
        m_buf[m_writeOffset-1] = '\n';
        addChar('\0');
      }
      else if (m_buf && m_writeOffset>0 && m_buf[m_writeOffset-1]!='\0' && m_buf[m_writeOffset-1]!=c)
      {
        // add missing terminal character without 0 terminator
        addChar(c);
      }
    }
References addChar(), c, m_buf, and m_writeOffset.
Referenced by parseFile().
addTerminalCharIfMissing() [2/2]
void BufStr::addTerminalCharIfMissing (char c) [inline]
Definition at line 107 of file bufstr.h.
    {
      if (m_buf && m_writeOffset>1 && m_buf[m_writeOffset-2]!=c && m_buf[m_writeOffset-1]=='\0')
      {
        // add missing terminal character and 0 terminator
        m_buf[m_writeOffset-1] = '\n';
        addChar('\0');
      }
      else if (m_buf && m_writeOffset>0 && m_buf[m_writeOffset-1]!='\0' && m_buf[m_writeOffset-1]!=c)
      {
        // add missing terminal character without 0 terminator
        addChar(c);
      }
    }
References addChar(), c, m_buf, and m_writeOffset.
at() [1/2]
char & BufStr::at (size_t i) const [inline]
Definition at line 84 of file bufstr.h.
    {
      return m_buf[i];
    }
References m_buf.
Referenced by fileToString(), and readInputFile().
at() [2/2]
char & BufStr::at (size_t i) const [inline]
Definition at line 84 of file bufstr.h.
    {
      return m_buf[i];
    }
References m_buf.
curPos() [1/2]
size_t BufStr::curPos () const [inline]
Definition at line 96 of file bufstr.h.
    {
      return m_writeOffset;
    }
References m_writeOffset.
Referenced by parseFile(), Preprocessor::processFile(), and readInputFile().
curPos() [2/2]
size_t BufStr::curPos () const [inline]
Definition at line 96 of file bufstr.h.
    {
      return m_writeOffset;
    }
References m_writeOffset.
data() [1/2]
char * BufStr::data () const [inline]
Definition at line 80 of file bufstr.h.
    {
      return m_buf;
    }
References m_buf.
Referenced by convertCppComments(), fileToString(), FilterCache::getFileContents(), parseFile(), Preprocessor::processFile(), readCodeFragment(), readInputFile(), and transcodeCharacterBuffer().
data() [2/2]
char * BufStr::data () const [inline]
Definition at line 80 of file bufstr.h.
    {
      return m_buf;
    }
References m_buf.
dropFromStart() [1/2]
void BufStr::dropFromStart (size_t bytes) [inline]
Definition at line 100 of file bufstr.h.
    {
      if (bytes>m_size) bytes=m_size;
      if (bytes>0) qmemmove(m_buf,m_buf+bytes,m_size-bytes);
      m_size-=bytes;
      m_writeOffset-=bytes;
    }
References m_buf, m_size, m_writeOffset, and qmemmove().
Referenced by readInputFile().
dropFromStart() [2/2]
void BufStr::dropFromStart (size_t bytes) [inline]
Definition at line 100 of file bufstr.h.
    {
      if (bytes>m_size) bytes=m_size;
      if (bytes>0) qmemmove(m_buf,m_buf+bytes,m_size-bytes);
      m_size-=bytes;
      m_writeOffset-=bytes;
    }
References m_buf, m_size, m_writeOffset, and qmemmove().
isEmpty() [1/2]
bool BufStr::isEmpty () const [inline]
Definition at line 88 of file bufstr.h.
    {
      return m_writeOffset==0;
    }
References m_writeOffset.
isEmpty() [2/2]
bool BufStr::isEmpty () const [inline]
Definition at line 88 of file bufstr.h.
    {
      return m_writeOffset==0;
    }
References m_writeOffset.
makeRoomFor() [1/2]
void BufStr::makeRoomFor (size_t size) [inline], [private]
Definition at line 122 of file bufstr.h.
    {
      if (m_writeOffset+size>=m_size)
      {
        resize(m_size+size+m_spareRoom);
      }
    }
References m_size, m_spareRoom, m_writeOffset, resize(), and size().
Referenced by addArray(), addChar(), and skip().
makeRoomFor() [2/2]
void BufStr::makeRoomFor (size_t size) [inline], [private]
Definition at line 122 of file bufstr.h.
    {
      if (m_writeOffset+size>=m_size)
      {
        resize(m_size+size+m_spareRoom);
      }
    }
References m_size, m_spareRoom, m_writeOffset, resize(), and size().
operator const char *() [1/2]
BufStr::operator const char * () const [inline]
Definition at line 92 of file bufstr.h.
    {
      return m_buf;
    }
References m_buf.
operator const char *() [2/2]
BufStr::operator const char * () const [inline]
Definition at line 92 of file bufstr.h.
    {
      return m_buf;
    }
References m_buf.
resize() [1/2]
void BufStr::resize (size_t newlen) [inline]
Definition at line 62 of file bufstr.h.
    {
      size_t oldsize = m_size;
      m_size=newlen;
      if (m_writeOffset>=m_size) // offset out of range -> enlarge
      {
        m_size=m_writeOffset+m_spareRoom;
      }
      m_buf = static_cast<char *>(realloc(m_buf,m_size));
      if (m_size>oldsize)
      {
        memset(m_buf+oldsize,0,m_size-oldsize);
      }
    }
References m_buf, m_size, m_spareRoom, and m_writeOffset.
Referenced by FilterCache::getFileContents(), makeRoomFor(), and shrink().
resize() [2/2]
void BufStr::resize (size_t newlen) [inline]
Definition at line 62 of file bufstr.h.
    {
      size_t oldsize = m_size;
      m_size=newlen;
      if (m_writeOffset>=m_size) // offset out of range -> enlarge
      {
        m_size=m_writeOffset+m_spareRoom;
      }
      m_buf = static_cast<char *>(realloc(m_buf,m_size));
      if (m_size>oldsize)
      {
        memset(m_buf+oldsize,0,m_size-oldsize);
      }
    }
References m_buf, m_size, m_spareRoom, and m_writeOffset.
shrink() [1/2]
void BufStr::shrink (size_t newlen) [inline]
Definition at line 57 of file bufstr.h.
    {
      m_writeOffset=newlen;
      resize(newlen);
    }
References m_writeOffset, and resize().
Referenced by readInputFile(), and transcodeCharacterBuffer().
shrink() [2/2]
void BufStr::shrink (size_t newlen) [inline]
Definition at line 57 of file bufstr.h.
    {
      m_writeOffset=newlen;
      resize(newlen);
    }
References m_writeOffset, and resize().
size() [1/2]
size_t BufStr::size () const [inline]
Definition at line 76 of file bufstr.h.
    {
      return m_size;
    }
References m_size.
Referenced by BufStr(), fileToString(), and makeRoomFor().
size() [2/2]
size_t BufStr::size () const [inline]
Definition at line 76 of file bufstr.h.
    {
      return m_size;
    }
References m_size.
skip() [1/2]
void BufStr::skip (size_t s) [inline]
Definition at line 52 of file bufstr.h.
    {
      makeRoomFor(s);
      m_writeOffset+=s;
    }
References m_writeOffset, makeRoomFor(), and s.
Referenced by readInputFile().
skip() [2/2]
void BufStr::skip (size_t s) [inline]
Definition at line 52 of file bufstr.h.
    {
      makeRoomFor(s);
      m_writeOffset+=s;
    }
References m_writeOffset, makeRoomFor(), and s.
Member Data Documentation
m_buf
char * BufStr::m_buf [private]
Definition at line 132 of file bufstr.h.
Referenced by addArray(), addChar(), addTerminalCharIfMissing(), at(), BufStr(), data(), dropFromStart(), operator const char *(), resize(), and ~BufStr().
m_size
size_t BufStr::m_size [private]
Definition at line 129 of file bufstr.h.
Referenced by dropFromStart(), makeRoomFor(), resize(), and size().
m_spareRoom
const size_t BufStr::m_spareRoom [private]
Definition at line 131 of file bufstr.h.
Referenced by makeRoomFor(), and resize().
m_writeOffset
size_t BufStr::m_writeOffset [private]
Definition at line 130 of file bufstr.h.
Referenced by addArray(), addChar(), addTerminalCharIfMissing(), curPos(), dropFromStart(), isEmpty(), makeRoomFor(), resize(), shrink(), and skip().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/bufstr.h
doxygen/src/bufstr.h