DefinitionAliasMixin< Base > Class Template Reference
#include <definitionimpl.h>
Public Member Functions
DefinitionAliasMixin (const Definition *scope, const Definition *alias)
void init ()
void deinit ()
virtual ~DefinitionAliasMixin ()=default
virtual bool isAlias () const
virtual QCString name () const
virtual bool isAnonymous () const
virtual QCString localName () const
virtual QCString qualifiedName () const
virtual QCString symbolName () const
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
virtual int docLine () const
virtual QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
virtual QCString briefDescriptionAsTooltip () const
virtual int briefLine () const
virtual QCString inbodyDocumentation () const
virtual QCString inbodyFile () const
virtual int inbodyLine () const
virtual QCString briefFile () const
virtual QCString getDefFileName () const
virtual QCString getDefFileExtension () const
virtual int getDefLine () const
virtual int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
virtual bool isHidden () const
virtual bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
virtual QCString externalReference (const QCString &relPath) const
virtual int getStartDefLine () const
virtual int getStartBodyLine () const
virtual int getEndBodyLine () const
virtual const FileDef * getBodyDef () const
virtual SrcLangExt getLanguage () const
virtual const GroupList & partOfGroups () const
virtual bool isLinkableViaGroup () const
virtual const RefItemVector & xrefListItems () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual Definition * getOuterScope () const
virtual const MemberVector & getReferencesMembers () const
virtual const MemberVector & getReferencedByMembers () const
virtual bool hasSections () const
virtual bool hasSources () const
virtual bool hasBriefDescription () const
virtual QCString id () const
virtual const SectionRefs & getSectionRefs () const
virtual QCString navigationPathAsString () const
virtual QCString pathFragment () const
DefinitionAliasMixin (const Definition *scope, const Definition *alias)
void init ()
void deinit ()
virtual ~DefinitionAliasMixin ()=default
virtual bool isAlias () const
virtual QCString name () const
virtual bool isAnonymous () const
virtual QCString localName () const
virtual QCString qualifiedName () const
virtual QCString symbolName () const
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
virtual int docLine () const
virtual QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
virtual QCString briefDescriptionAsTooltip () const
virtual int briefLine () const
virtual QCString inbodyDocumentation () const
virtual QCString inbodyFile () const
virtual int inbodyLine () const
virtual QCString briefFile () const
virtual QCString getDefFileName () const
virtual QCString getDefFileExtension () const
virtual int getDefLine () const
virtual int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
virtual bool isHidden () const
virtual bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
virtual QCString externalReference (const QCString &relPath) const
virtual int getStartDefLine () const
virtual int getStartBodyLine () const
virtual int getEndBodyLine () const
virtual const FileDef * getBodyDef () const
virtual SrcLangExt getLanguage () const
virtual const GroupList & partOfGroups () const
virtual bool isLinkableViaGroup () const
virtual const RefItemVector & xrefListItems () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual Definition * getOuterScope () const
virtual const MemberVector & getReferencesMembers () const
virtual const MemberVector & getReferencedByMembers () const
virtual bool hasSections () const
virtual bool hasSources () const
virtual bool hasBriefDescription () const
virtual QCString id () const
virtual const SectionRefs & getSectionRefs () const
virtual QCString navigationPathAsString () const
virtual QCString pathFragment () const
Protected Member Functions
const Definition * getAlias () const
const Definition * getScope () const
const Definition * getAlias () const
const Definition * getScope () const
Private Member Functions
virtual Definition * toDefinition_ ()
virtual DefinitionMutable * toDefinitionMutable_ ()
virtual const DefinitionImpl * toDefinitionImpl_ () const
virtual void _setSymbolName (const QCString &name)
virtual QCString _symbolName () const
virtual Definition * toDefinition_ ()
virtual DefinitionMutable * toDefinitionMutable_ ()
virtual const DefinitionImpl * toDefinitionImpl_ () const
virtual void _setSymbolName (const QCString &name)
virtual QCString _symbolName () const
Private Attributes
DefinitionAliasImpl m_impl
const Definition * m_scope
const Definition * m_alias
QCString m_symbolName
Detailed Description
template<class Base>
class DefinitionAliasMixin< Base >
Definition at line 312 of file definitionimpl.h.
Constructor & Destructor Documentation
DefinitionAliasMixin() [1/2]
template<class Base >
DefinitionAliasMixin< Base >::DefinitionAliasMixin (const Definition * scope, const Definition * alias) [inline]
Definition at line 315 of file definitionimpl.h.
      : m_impl(this,scope,alias), m_scope(scope), m_alias(alias) {}
 DefinitionAliasMixin() [1/2]
template<class Base >
virtual DefinitionAliasMixin< Base >::~DefinitionAliasMixin () [virtual], [default]
DefinitionAliasMixin() [2/2]
template<class Base >
DefinitionAliasMixin< Base >::DefinitionAliasMixin (const Definition * scope, const Definition * alias) [inline]
Definition at line 315 of file definitionimpl.h.
      : m_impl(this,scope,alias), m_scope(scope), m_alias(alias) {}
 DefinitionAliasMixin() [2/2]
template<class Base >
virtual DefinitionAliasMixin< Base >::~DefinitionAliasMixin () [virtual], [default]
Member Function Documentation
_setSymbolName() [1/2]
template<class Base >
virtual void DefinitionAliasMixin< Base >::_setSymbolName (const QCString & name) [inline], [private], [virtual]
Definition at line 434 of file definitionimpl.h.
{ m_symbolName = name; }
References DefinitionAliasMixin< Base >::m_symbolName, and DefinitionAliasMixin< Base >::name().
_setSymbolName() [2/2]
template<class Base >
virtual void DefinitionAliasMixin< Base >::_setSymbolName (const QCString & name) [inline], [private], [virtual]
Definition at line 434 of file definitionimpl.h.
{ m_symbolName = name; }
References DefinitionAliasMixin< Base >::m_symbolName, and DefinitionAliasMixin< Base >::name().
_symbolName() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::_symbolName () const [inline], [private], [virtual]
Definition at line 435 of file definitionimpl.h.
{ return m_symbolName; }
References DefinitionAliasMixin< Base >::m_symbolName.
_symbolName() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::_symbolName () const [inline], [private], [virtual]
Definition at line 435 of file definitionimpl.h.
{ return m_symbolName; }
References DefinitionAliasMixin< Base >::m_symbolName.
briefDescription() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::briefDescription (bool abbreviate = FALSE) const [inline], [virtual]
Reimplemented in MemberDefAliasImpl, and MemberDefAliasImpl.
Definition at line 346 of file definitionimpl.h.
    { return m_alias->briefDescription(abbreviate); }
References abbreviate(), Definition::briefDescription(), and DefinitionAliasMixin< Base >::m_alias.
briefDescription() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::briefDescription (bool abbreviate = FALSE) const [inline], [virtual]
Reimplemented in MemberDefAliasImpl, and MemberDefAliasImpl.
Definition at line 346 of file definitionimpl.h.
    { return m_alias->briefDescription(abbreviate); }
References abbreviate(), Definition::briefDescription(), and DefinitionAliasMixin< Base >::m_alias.
briefDescriptionAsTooltip() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::briefDescriptionAsTooltip () const [inline], [virtual]
Definition at line 348 of file definitionimpl.h.
    { return m_alias->briefDescriptionAsTooltip(); }
References Definition::briefDescriptionAsTooltip(), and DefinitionAliasMixin< Base >::m_alias.
briefDescriptionAsTooltip() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::briefDescriptionAsTooltip () const [inline], [virtual]
Definition at line 348 of file definitionimpl.h.
    { return m_alias->briefDescriptionAsTooltip(); }
References Definition::briefDescriptionAsTooltip(), and DefinitionAliasMixin< Base >::m_alias.
briefFile() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::briefFile () const [inline], [virtual]
Definition at line 358 of file definitionimpl.h.
    { return m_alias->briefFile(); }
References Definition::briefFile(), and DefinitionAliasMixin< Base >::m_alias.
briefFile() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::briefFile () const [inline], [virtual]
Definition at line 358 of file definitionimpl.h.
    { return m_alias->briefFile(); }
References Definition::briefFile(), and DefinitionAliasMixin< Base >::m_alias.
briefLine() [1/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::briefLine () const [inline], [virtual]
Definition at line 350 of file definitionimpl.h.
    { return m_alias->briefLine(); }
References Definition::briefLine(), and DefinitionAliasMixin< Base >::m_alias.
briefLine() [2/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::briefLine () const [inline], [virtual]
Definition at line 350 of file definitionimpl.h.
    { return m_alias->briefLine(); }
References Definition::briefLine(), and DefinitionAliasMixin< Base >::m_alias.
deinit() [1/2]
template<class Base >
void DefinitionAliasMixin< Base >::deinit () [inline]
Definition at line 319 of file definitionimpl.h.
{ m_impl.deinit(); }
References DefinitionAliasImpl::deinit(), and DefinitionAliasMixin< Base >::m_impl.
deinit() [2/2]
template<class Base >
void DefinitionAliasMixin< Base >::deinit () [inline]
Definition at line 319 of file definitionimpl.h.
{ m_impl.deinit(); }
References DefinitionAliasImpl::deinit(), and DefinitionAliasMixin< Base >::m_impl.
docFile() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::docFile () const [inline], [virtual]
Definition at line 344 of file definitionimpl.h.
    { return m_alias->docFile(); }
References Definition::docFile(), and DefinitionAliasMixin< Base >::m_alias.
docFile() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::docFile () const [inline], [virtual]
Definition at line 344 of file definitionimpl.h.
    { return m_alias->docFile(); }
References Definition::docFile(), and DefinitionAliasMixin< Base >::m_alias.
docLine() [1/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::docLine () const [inline], [virtual]
Definition at line 342 of file definitionimpl.h.
    { return m_alias->docLine(); }
References Definition::docLine(), and DefinitionAliasMixin< Base >::m_alias.
docLine() [2/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::docLine () const [inline], [virtual]
Definition at line 342 of file definitionimpl.h.
    { return m_alias->docLine(); }
References Definition::docLine(), and DefinitionAliasMixin< Base >::m_alias.
documentation() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::documentation () const [inline], [virtual]
Reimplemented in MemberDefAliasImpl, and MemberDefAliasImpl.
Definition at line 340 of file definitionimpl.h.
    { return m_alias->documentation(); }
References Definition::documentation(), and DefinitionAliasMixin< Base >::m_alias.
documentation() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::documentation () const [inline], [virtual]
Reimplemented in MemberDefAliasImpl, and MemberDefAliasImpl.
Definition at line 340 of file definitionimpl.h.
    { return m_alias->documentation(); }
References Definition::documentation(), and DefinitionAliasMixin< Base >::m_alias.
externalReference() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::externalReference (const QCString & relPath) const [inline], [virtual]
Definition at line 384 of file definitionimpl.h.
    { return m_alias->externalReference(relPath); }
References Definition::externalReference(), and DefinitionAliasMixin< Base >::m_alias.
externalReference() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::externalReference (const QCString & relPath) const [inline], [virtual]
Definition at line 384 of file definitionimpl.h.
    { return m_alias->externalReference(relPath); }
References Definition::externalReference(), and DefinitionAliasMixin< Base >::m_alias.
findInnerCompound() [1/2]
template<class Base >
virtual const Definition * DefinitionAliasMixin< Base >::findInnerCompound (const QCString & name) const [inline], [virtual]
Reimplemented in ClassDefAliasImpl, NamespaceDefAliasImpl, ClassDefAliasImpl, and NamespaceDefAliasImpl.
Definition at line 402 of file definitionimpl.h.
    { return m_alias->findInnerCompound(name); }
References Definition::findInnerCompound(), DefinitionAliasMixin< Base >::m_alias, and DefinitionAliasMixin< Base >::name().
findInnerCompound() [2/2]
template<class Base >
virtual const Definition * DefinitionAliasMixin< Base >::findInnerCompound (const QCString & name) const [inline], [virtual]
Reimplemented in ClassDefAliasImpl, NamespaceDefAliasImpl, ClassDefAliasImpl, and NamespaceDefAliasImpl.
Definition at line 402 of file definitionimpl.h.
    { return m_alias->findInnerCompound(name); }
References Definition::findInnerCompound(), DefinitionAliasMixin< Base >::m_alias, and DefinitionAliasMixin< Base >::name().
getAlias() [1/2]
template<class Base >
const Definition * DefinitionAliasMixin< Base >::getAlias () const [inline], [protected]
Definition at line 426 of file definitionimpl.h.
{ return m_alias; }
References DefinitionAliasMixin< Base >::m_alias.
getAlias() [2/2]
template<class Base >
const Definition * DefinitionAliasMixin< Base >::getAlias () const [inline], [protected]
Definition at line 426 of file definitionimpl.h.
{ return m_alias; }
References DefinitionAliasMixin< Base >::m_alias.
getBodyDef() [1/2]
template<class Base >
virtual const FileDef * DefinitionAliasMixin< Base >::getBodyDef () const [inline], [virtual]
Definition at line 392 of file definitionimpl.h.
    { return m_alias->getBodyDef(); }
References Definition::getBodyDef(), and DefinitionAliasMixin< Base >::m_alias.
getBodyDef() [2/2]
template<class Base >
virtual const FileDef * DefinitionAliasMixin< Base >::getBodyDef () const [inline], [virtual]
Definition at line 392 of file definitionimpl.h.
    { return m_alias->getBodyDef(); }
References Definition::getBodyDef(), and DefinitionAliasMixin< Base >::m_alias.
getDefColumn() [1/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::getDefColumn () const [inline], [virtual]
Definition at line 366 of file definitionimpl.h.
    { return m_alias->getDefColumn(); }
References Definition::getDefColumn(), and DefinitionAliasMixin< Base >::m_alias.
getDefColumn() [2/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::getDefColumn () const [inline], [virtual]
Definition at line 366 of file definitionimpl.h.
    { return m_alias->getDefColumn(); }
References Definition::getDefColumn(), and DefinitionAliasMixin< Base >::m_alias.
getDefFileExtension() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::getDefFileExtension () const [inline], [virtual]
Definition at line 362 of file definitionimpl.h.
    { return m_alias->getDefFileExtension(); }
References Definition::getDefFileExtension(), and DefinitionAliasMixin< Base >::m_alias.
getDefFileExtension() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::getDefFileExtension () const [inline], [virtual]
Definition at line 362 of file definitionimpl.h.
    { return m_alias->getDefFileExtension(); }
References Definition::getDefFileExtension(), and DefinitionAliasMixin< Base >::m_alias.
getDefFileName() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::getDefFileName () const [inline], [virtual]
Definition at line 360 of file definitionimpl.h.
    { return m_alias->getDefFileName(); }
References Definition::getDefFileName(), and DefinitionAliasMixin< Base >::m_alias.
getDefFileName() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::getDefFileName () const [inline], [virtual]
Definition at line 360 of file definitionimpl.h.
    { return m_alias->getDefFileName(); }
References Definition::getDefFileName(), and DefinitionAliasMixin< Base >::m_alias.
getDefLine() [1/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::getDefLine () const [inline], [virtual]
Definition at line 364 of file definitionimpl.h.
    { return m_alias->getDefLine(); }
References Definition::getDefLine(), and DefinitionAliasMixin< Base >::m_alias.
getDefLine() [2/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::getDefLine () const [inline], [virtual]
Definition at line 364 of file definitionimpl.h.
    { return m_alias->getDefLine(); }
References Definition::getDefLine(), and DefinitionAliasMixin< Base >::m_alias.
getEndBodyLine() [1/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::getEndBodyLine () const [inline], [virtual]
Definition at line 390 of file definitionimpl.h.
    { return m_alias->getEndBodyLine(); }
References Definition::getEndBodyLine(), and DefinitionAliasMixin< Base >::m_alias.
getEndBodyLine() [2/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::getEndBodyLine () const [inline], [virtual]
Definition at line 390 of file definitionimpl.h.
    { return m_alias->getEndBodyLine(); }
References Definition::getEndBodyLine(), and DefinitionAliasMixin< Base >::m_alias.
getLanguage() [1/2]
template<class Base >
virtual SrcLangExt DefinitionAliasMixin< Base >::getLanguage () const [inline], [virtual]
Definition at line 394 of file definitionimpl.h.
    { return m_alias->getLanguage(); }
References Definition::getLanguage(), and DefinitionAliasMixin< Base >::m_alias.
getLanguage() [2/2]
template<class Base >
virtual SrcLangExt DefinitionAliasMixin< Base >::getLanguage () const [inline], [virtual]
Definition at line 394 of file definitionimpl.h.
    { return m_alias->getLanguage(); }
References Definition::getLanguage(), and DefinitionAliasMixin< Base >::m_alias.
getOuterScope() [1/2]
template<class Base >
virtual Definition * DefinitionAliasMixin< Base >::getOuterScope () const [inline], [virtual]
Definition at line 404 of file definitionimpl.h.
    { return const_cast<Definition*>(m_scope); }
References DefinitionAliasMixin< Base >::m_scope.
getOuterScope() [2/2]
template<class Base >
virtual Definition * DefinitionAliasMixin< Base >::getOuterScope () const [inline], [virtual]
Definition at line 404 of file definitionimpl.h.
    { return const_cast<Definition*>(m_scope); }
References DefinitionAliasMixin< Base >::m_scope.
getReference() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::getReference () const [inline], [virtual]
Reimplemented in ClassDefAliasImpl, ConceptDefAliasImpl, MemberDefAliasImpl, ClassDefAliasImpl, ConceptDefAliasImpl, and MemberDefAliasImpl.
Definition at line 380 of file definitionimpl.h.
    { return m_alias->getReference(); }
References Definition::getReference(), and DefinitionAliasMixin< Base >::m_alias.
getReference() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::getReference () const [inline], [virtual]
Reimplemented in ClassDefAliasImpl, ConceptDefAliasImpl, MemberDefAliasImpl, ClassDefAliasImpl, ConceptDefAliasImpl, and MemberDefAliasImpl.
Definition at line 380 of file definitionimpl.h.
    { return m_alias->getReference(); }
References Definition::getReference(), and DefinitionAliasMixin< Base >::m_alias.
getReferencedByMembers() [1/2]
template<class Base >
virtual const MemberVector & DefinitionAliasMixin< Base >::getReferencedByMembers () const [inline], [virtual]
Definition at line 408 of file definitionimpl.h.
    { return m_alias->getReferencedByMembers(); }
References Definition::getReferencedByMembers(), and DefinitionAliasMixin< Base >::m_alias.
getReferencedByMembers() [2/2]
template<class Base >
virtual const MemberVector & DefinitionAliasMixin< Base >::getReferencedByMembers () const [inline], [virtual]
Definition at line 408 of file definitionimpl.h.
    { return m_alias->getReferencedByMembers(); }
References Definition::getReferencedByMembers(), and DefinitionAliasMixin< Base >::m_alias.
getReferencesMembers() [1/2]
template<class Base >
virtual const MemberVector & DefinitionAliasMixin< Base >::getReferencesMembers () const [inline], [virtual]
Definition at line 406 of file definitionimpl.h.
    { return m_alias->getReferencesMembers(); }
References Definition::getReferencesMembers(), and DefinitionAliasMixin< Base >::m_alias.
getReferencesMembers() [2/2]
template<class Base >
virtual const MemberVector & DefinitionAliasMixin< Base >::getReferencesMembers () const [inline], [virtual]
Definition at line 406 of file definitionimpl.h.
    { return m_alias->getReferencesMembers(); }
References Definition::getReferencesMembers(), and DefinitionAliasMixin< Base >::m_alias.
getScope() [1/2]
template<class Base >
const Definition * DefinitionAliasMixin< Base >::getScope () const [inline], [protected]
Definition at line 427 of file definitionimpl.h.
{ return m_scope; }
References DefinitionAliasMixin< Base >::m_scope.
getScope() [2/2]
template<class Base >
const Definition * DefinitionAliasMixin< Base >::getScope () const [inline], [protected]
Definition at line 427 of file definitionimpl.h.
{ return m_scope; }
References DefinitionAliasMixin< Base >::m_scope.
getSectionRefs() [1/2]
template<class Base >
virtual const SectionRefs & DefinitionAliasMixin< Base >::getSectionRefs () const [inline], [virtual]
Definition at line 418 of file definitionimpl.h.
    { return m_alias->getSectionRefs(); }
References Definition::getSectionRefs(), and DefinitionAliasMixin< Base >::m_alias.
getSectionRefs() [2/2]
template<class Base >
virtual const SectionRefs & DefinitionAliasMixin< Base >::getSectionRefs () const [inline], [virtual]
Definition at line 418 of file definitionimpl.h.
    { return m_alias->getSectionRefs(); }
References Definition::getSectionRefs(), and DefinitionAliasMixin< Base >::m_alias.
getSourceAnchor() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::getSourceAnchor () const [inline], [virtual]
Definition at line 338 of file definitionimpl.h.
    { return m_alias->getSourceAnchor(); }
References Definition::getSourceAnchor(), and DefinitionAliasMixin< Base >::m_alias.
getSourceAnchor() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::getSourceAnchor () const [inline], [virtual]
Definition at line 338 of file definitionimpl.h.
    { return m_alias->getSourceAnchor(); }
References Definition::getSourceAnchor(), and DefinitionAliasMixin< Base >::m_alias.
getSourceFileBase() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::getSourceFileBase () const [inline], [virtual]
Reimplemented in ClassDefAliasImpl, and ClassDefAliasImpl.
Definition at line 336 of file definitionimpl.h.
    { return m_alias->getSourceFileBase(); }
References Definition::getSourceFileBase(), and DefinitionAliasMixin< Base >::m_alias.
getSourceFileBase() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::getSourceFileBase () const [inline], [virtual]
Reimplemented in ClassDefAliasImpl, and ClassDefAliasImpl.
Definition at line 336 of file definitionimpl.h.
    { return m_alias->getSourceFileBase(); }
References Definition::getSourceFileBase(), and DefinitionAliasMixin< Base >::m_alias.
getStartBodyLine() [1/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::getStartBodyLine () const [inline], [virtual]
Definition at line 388 of file definitionimpl.h.
    { return m_alias->getStartBodyLine(); }
References Definition::getStartBodyLine(), and DefinitionAliasMixin< Base >::m_alias.
getStartBodyLine() [2/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::getStartBodyLine () const [inline], [virtual]
Definition at line 388 of file definitionimpl.h.
    { return m_alias->getStartBodyLine(); }
References Definition::getStartBodyLine(), and DefinitionAliasMixin< Base >::m_alias.
getStartDefLine() [1/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::getStartDefLine () const [inline], [virtual]
Definition at line 386 of file definitionimpl.h.
    { return m_alias->getStartDefLine(); }
References Definition::getStartDefLine(), and DefinitionAliasMixin< Base >::m_alias.
getStartDefLine() [2/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::getStartDefLine () const [inline], [virtual]
Definition at line 386 of file definitionimpl.h.
    { return m_alias->getStartDefLine(); }
References Definition::getStartDefLine(), and DefinitionAliasMixin< Base >::m_alias.
hasBriefDescription() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::hasBriefDescription () const [inline], [virtual]
Definition at line 414 of file definitionimpl.h.
    { return m_alias->hasBriefDescription(); }
References Definition::hasBriefDescription(), and DefinitionAliasMixin< Base >::m_alias.
hasBriefDescription() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::hasBriefDescription () const [inline], [virtual]
Definition at line 414 of file definitionimpl.h.
    { return m_alias->hasBriefDescription(); }
References Definition::hasBriefDescription(), and DefinitionAliasMixin< Base >::m_alias.
hasDocumentation() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::hasDocumentation () const [inline], [virtual]
Reimplemented in ClassDefAliasImpl, MemberDefAliasImpl, ClassDefAliasImpl, and MemberDefAliasImpl.
Definition at line 368 of file definitionimpl.h.
    { return m_alias->hasDocumentation(); }
References Definition::hasDocumentation(), and DefinitionAliasMixin< Base >::m_alias.
hasDocumentation() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::hasDocumentation () const [inline], [virtual]
Reimplemented in ClassDefAliasImpl, MemberDefAliasImpl, ClassDefAliasImpl, and MemberDefAliasImpl.
Definition at line 368 of file definitionimpl.h.
    { return m_alias->hasDocumentation(); }
References Definition::hasDocumentation(), and DefinitionAliasMixin< Base >::m_alias.
hasSections() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::hasSections () const [inline], [virtual]
Definition at line 410 of file definitionimpl.h.
    { return m_alias->hasSections(); }
References Definition::hasSections(), and DefinitionAliasMixin< Base >::m_alias.
hasSections() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::hasSections () const [inline], [virtual]
Definition at line 410 of file definitionimpl.h.
    { return m_alias->hasSections(); }
References Definition::hasSections(), and DefinitionAliasMixin< Base >::m_alias.
hasSources() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::hasSources () const [inline], [virtual]
Definition at line 412 of file definitionimpl.h.
    { return m_alias->hasSources(); }
References Definition::hasSources(), and DefinitionAliasMixin< Base >::m_alias.
hasSources() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::hasSources () const [inline], [virtual]
Definition at line 412 of file definitionimpl.h.
    { return m_alias->hasSources(); }
References Definition::hasSources(), and DefinitionAliasMixin< Base >::m_alias.
hasUserDocumentation() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::hasUserDocumentation () const [inline], [virtual]
Definition at line 370 of file definitionimpl.h.
    { return m_alias->hasUserDocumentation(); }
References Definition::hasUserDocumentation(), and DefinitionAliasMixin< Base >::m_alias.
hasUserDocumentation() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::hasUserDocumentation () const [inline], [virtual]
Definition at line 370 of file definitionimpl.h.
    { return m_alias->hasUserDocumentation(); }
References Definition::hasUserDocumentation(), and DefinitionAliasMixin< Base >::m_alias.
id() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::id () const [inline], [virtual]
Definition at line 416 of file definitionimpl.h.
    { return m_alias->id(); }
References Definition::id(), and DefinitionAliasMixin< Base >::m_alias.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::id () const [inline], [virtual]
Definition at line 416 of file definitionimpl.h.
    { return m_alias->id(); }
References Definition::id(), and DefinitionAliasMixin< Base >::m_alias.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
inbodyDocumentation() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::inbodyDocumentation () const [inline], [virtual]
Definition at line 352 of file definitionimpl.h.
    { return m_alias->inbodyDocumentation(); }
References Definition::inbodyDocumentation(), and DefinitionAliasMixin< Base >::m_alias.
inbodyDocumentation() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::inbodyDocumentation () const [inline], [virtual]
Definition at line 352 of file definitionimpl.h.
    { return m_alias->inbodyDocumentation(); }
References Definition::inbodyDocumentation(), and DefinitionAliasMixin< Base >::m_alias.
inbodyFile() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::inbodyFile () const [inline], [virtual]
Definition at line 354 of file definitionimpl.h.
    { return m_alias->inbodyFile(); }
References Definition::inbodyFile(), and DefinitionAliasMixin< Base >::m_alias.
inbodyFile() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::inbodyFile () const [inline], [virtual]
Definition at line 354 of file definitionimpl.h.
    { return m_alias->inbodyFile(); }
References Definition::inbodyFile(), and DefinitionAliasMixin< Base >::m_alias.
inbodyLine() [1/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::inbodyLine () const [inline], [virtual]
Definition at line 356 of file definitionimpl.h.
    { return m_alias->inbodyLine(); }
References Definition::inbodyLine(), and DefinitionAliasMixin< Base >::m_alias.
inbodyLine() [2/2]
template<class Base >
virtual int DefinitionAliasMixin< Base >::inbodyLine () const [inline], [virtual]
Definition at line 356 of file definitionimpl.h.
    { return m_alias->inbodyLine(); }
References Definition::inbodyLine(), and DefinitionAliasMixin< Base >::m_alias.
init() [1/2]
template<class Base >
void DefinitionAliasMixin< Base >::init () [inline]
Definition at line 318 of file definitionimpl.h.
{ m_impl.init(); }
References DefinitionAliasImpl::init(), and DefinitionAliasMixin< Base >::m_impl.
init() [2/2]
template<class Base >
void DefinitionAliasMixin< Base >::init () [inline]
Definition at line 318 of file definitionimpl.h.
{ m_impl.init(); }
References DefinitionAliasImpl::init(), and DefinitionAliasMixin< Base >::m_impl.
isAlias() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isAlias () const [inline], [virtual]
Definition at line 323 of file definitionimpl.h.
{ return TRUE; }
References TRUE.
isAlias() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isAlias () const [inline], [virtual]
Definition at line 323 of file definitionimpl.h.
{ return TRUE; }
References TRUE.
isAnonymous() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isAnonymous () const [inline], [virtual]
Definition at line 328 of file definitionimpl.h.
    { return m_alias->isAnonymous(); }
References Definition::isAnonymous(), and DefinitionAliasMixin< Base >::m_alias.
isAnonymous() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isAnonymous () const [inline], [virtual]
Definition at line 328 of file definitionimpl.h.
    { return m_alias->isAnonymous(); }
References Definition::isAnonymous(), and DefinitionAliasMixin< Base >::m_alias.
isArtificial() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isArtificial () const [inline], [virtual]
Definition at line 378 of file definitionimpl.h.
    { return m_alias->isArtificial(); }
References Definition::isArtificial(), and DefinitionAliasMixin< Base >::m_alias.
isArtificial() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isArtificial () const [inline], [virtual]
Definition at line 378 of file definitionimpl.h.
    { return m_alias->isArtificial(); }
References Definition::isArtificial(), and DefinitionAliasMixin< Base >::m_alias.
isHidden() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isHidden () const [inline], [virtual]
Definition at line 376 of file definitionimpl.h.
    { return m_alias->isHidden(); }
References Definition::isHidden(), and DefinitionAliasMixin< Base >::m_alias.
isHidden() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isHidden () const [inline], [virtual]
Definition at line 376 of file definitionimpl.h.
    { return m_alias->isHidden(); }
References Definition::isHidden(), and DefinitionAliasMixin< Base >::m_alias.
isLinkableViaGroup() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isLinkableViaGroup () const [inline], [virtual]
Definition at line 398 of file definitionimpl.h.
    { return m_alias->isLinkableViaGroup(); }
References Definition::isLinkableViaGroup(), and DefinitionAliasMixin< Base >::m_alias.
isLinkableViaGroup() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isLinkableViaGroup () const [inline], [virtual]
Definition at line 398 of file definitionimpl.h.
    { return m_alias->isLinkableViaGroup(); }
References Definition::isLinkableViaGroup(), and DefinitionAliasMixin< Base >::m_alias.
isReference() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isReference () const [inline], [virtual]
Reimplemented in ClassDefAliasImpl, ConceptDefAliasImpl, MemberDefAliasImpl, ClassDefAliasImpl, ConceptDefAliasImpl, and MemberDefAliasImpl.
Definition at line 382 of file definitionimpl.h.
    { return m_alias->isReference(); }
References Definition::isReference(), and DefinitionAliasMixin< Base >::m_alias.
isReference() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isReference () const [inline], [virtual]
Reimplemented in ClassDefAliasImpl, ConceptDefAliasImpl, MemberDefAliasImpl, ClassDefAliasImpl, ConceptDefAliasImpl, and MemberDefAliasImpl.
Definition at line 382 of file definitionimpl.h.
    { return m_alias->isReference(); }
References Definition::isReference(), and DefinitionAliasMixin< Base >::m_alias.
isVisible() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isVisible () const [inline], [virtual]
Definition at line 374 of file definitionimpl.h.
    { return m_alias->isVisible(); }
References Definition::isVisible(), and DefinitionAliasMixin< Base >::m_alias.
isVisible() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isVisible () const [inline], [virtual]
Definition at line 374 of file definitionimpl.h.
    { return m_alias->isVisible(); }
References Definition::isVisible(), and DefinitionAliasMixin< Base >::m_alias.
isVisibleInProject() [1/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isVisibleInProject () const [inline], [virtual]
Definition at line 372 of file definitionimpl.h.
    { return m_alias->isVisibleInProject(); }
References Definition::isVisibleInProject(), and DefinitionAliasMixin< Base >::m_alias.
isVisibleInProject() [2/2]
template<class Base >
virtual bool DefinitionAliasMixin< Base >::isVisibleInProject () const [inline], [virtual]
Definition at line 372 of file definitionimpl.h.
    { return m_alias->isVisibleInProject(); }
References Definition::isVisibleInProject(), and DefinitionAliasMixin< Base >::m_alias.
localName() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::localName () const [inline], [virtual]
Reimplemented in NamespaceDefAliasImpl, and NamespaceDefAliasImpl.
Definition at line 330 of file definitionimpl.h.
    { return m_alias->localName(); }
References Definition::localName(), and DefinitionAliasMixin< Base >::m_alias.
localName() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::localName () const [inline], [virtual]
Reimplemented in NamespaceDefAliasImpl, and NamespaceDefAliasImpl.
Definition at line 330 of file definitionimpl.h.
    { return m_alias->localName(); }
References Definition::localName(), and DefinitionAliasMixin< Base >::m_alias.
name() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::name () const [inline], [virtual]
Reimplemented in MemberDefAliasImpl, and MemberDefAliasImpl.
Definition at line 326 of file definitionimpl.h.
    { return m_impl.name(); }
References DefinitionAliasMixin< Base >::m_impl, and DefinitionAliasImpl::name().
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), DefinitionAliasMixin< Base >::_setSymbolName(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), DefinitionAliasMixin< Base >::findInnerCompound(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::name () const [inline], [virtual]
Reimplemented in MemberDefAliasImpl, and MemberDefAliasImpl.
Definition at line 326 of file definitionimpl.h.
    { return m_impl.name(); }
References DefinitionAliasMixin< Base >::m_impl, and DefinitionAliasImpl::name().
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
navigationPathAsString() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::navigationPathAsString () const [inline], [virtual]
Definition at line 420 of file definitionimpl.h.
    { return m_alias->navigationPathAsString(); }
References DefinitionAliasMixin< Base >::m_alias, and Definition::navigationPathAsString().
navigationPathAsString() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::navigationPathAsString () const [inline], [virtual]
Definition at line 420 of file definitionimpl.h.
    { return m_alias->navigationPathAsString(); }
References DefinitionAliasMixin< Base >::m_alias, and Definition::navigationPathAsString().
partOfGroups() [1/2]
template<class Base >
virtual const GroupList & DefinitionAliasMixin< Base >::partOfGroups () const [inline], [virtual]
Definition at line 396 of file definitionimpl.h.
    { return m_alias->partOfGroups(); }
References DefinitionAliasMixin< Base >::m_alias, and Definition::partOfGroups().
partOfGroups() [2/2]
template<class Base >
virtual const GroupList & DefinitionAliasMixin< Base >::partOfGroups () const [inline], [virtual]
Definition at line 396 of file definitionimpl.h.
    { return m_alias->partOfGroups(); }
References DefinitionAliasMixin< Base >::m_alias, and Definition::partOfGroups().
pathFragment() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::pathFragment () const [inline], [virtual]
Definition at line 422 of file definitionimpl.h.
    { return m_alias->pathFragment(); }
References DefinitionAliasMixin< Base >::m_alias, and Definition::pathFragment().
pathFragment() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::pathFragment () const [inline], [virtual]
Definition at line 422 of file definitionimpl.h.
    { return m_alias->pathFragment(); }
References DefinitionAliasMixin< Base >::m_alias, and Definition::pathFragment().
qualifiedName() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::qualifiedName () const [inline], [virtual]
Reimplemented in MemberDefAliasImpl, and MemberDefAliasImpl.
Definition at line 332 of file definitionimpl.h.
    { return m_impl.qualifiedName(); }
References DefinitionAliasMixin< Base >::m_impl, and DefinitionAliasImpl::qualifiedName().
qualifiedName() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::qualifiedName () const [inline], [virtual]
Reimplemented in MemberDefAliasImpl, and MemberDefAliasImpl.
Definition at line 332 of file definitionimpl.h.
    { return m_impl.qualifiedName(); }
References DefinitionAliasMixin< Base >::m_impl, and DefinitionAliasImpl::qualifiedName().
symbolName() [1/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::symbolName () const [inline], [virtual]
Definition at line 334 of file definitionimpl.h.
    { return m_alias->symbolName(); }
References DefinitionAliasMixin< Base >::m_alias, and Definition::symbolName().
symbolName() [2/2]
template<class Base >
virtual QCString DefinitionAliasMixin< Base >::symbolName () const [inline], [virtual]
Definition at line 334 of file definitionimpl.h.
    { return m_alias->symbolName(); }
References DefinitionAliasMixin< Base >::m_alias, and Definition::symbolName().
toDefinition_() [1/2]
template<class Base >
virtual Definition * DefinitionAliasMixin< Base >::toDefinition_ () [inline], [private], [virtual]
Definition at line 430 of file definitionimpl.h.
{ return this; }
toDefinition_() [2/2]
template<class Base >
virtual Definition * DefinitionAliasMixin< Base >::toDefinition_ () [inline], [private], [virtual]
Definition at line 430 of file definitionimpl.h.
{ return this; }
toDefinitionImpl_() [1/2]
template<class Base >
virtual const DefinitionImpl * DefinitionAliasMixin< Base >::toDefinitionImpl_ () const [inline], [private], [virtual]
Definition at line 432 of file definitionimpl.h.
{ return 0; }
toDefinitionImpl_() [2/2]
template<class Base >
virtual const DefinitionImpl * DefinitionAliasMixin< Base >::toDefinitionImpl_ () const [inline], [private], [virtual]
Definition at line 432 of file definitionimpl.h.
{ return 0; }
toDefinitionMutable_() [1/2]
template<class Base >
virtual DefinitionMutable * DefinitionAliasMixin< Base >::toDefinitionMutable_ () [inline], [private], [virtual]
Definition at line 431 of file definitionimpl.h.
{ return 0; }
toDefinitionMutable_() [2/2]
template<class Base >
virtual DefinitionMutable * DefinitionAliasMixin< Base >::toDefinitionMutable_ () [inline], [private], [virtual]
Definition at line 431 of file definitionimpl.h.
{ return 0; }
xrefListItems() [1/2]
template<class Base >
virtual const RefItemVector & DefinitionAliasMixin< Base >::xrefListItems () const [inline], [virtual]
Definition at line 400 of file definitionimpl.h.
    { return m_alias->xrefListItems(); }
References DefinitionAliasMixin< Base >::m_alias, and Definition::xrefListItems().
xrefListItems() [2/2]
template<class Base >
virtual const RefItemVector & DefinitionAliasMixin< Base >::xrefListItems () const [inline], [virtual]
Definition at line 400 of file definitionimpl.h.
    { return m_alias->xrefListItems(); }
References DefinitionAliasMixin< Base >::m_alias, and Definition::xrefListItems().
Member Data Documentation
m_alias
template<class Base >
const Definition * DefinitionAliasMixin< Base >::m_alias [private]
Definition at line 438 of file definitionimpl.h.
Referenced by DefinitionAliasMixin< Base >::briefDescription(), DefinitionAliasMixin< Base >::briefDescriptionAsTooltip(), DefinitionAliasMixin< Base >::briefFile(), DefinitionAliasMixin< Base >::briefLine(), DefinitionAliasMixin< Base >::docFile(), DefinitionAliasMixin< Base >::docLine(), DefinitionAliasMixin< Base >::documentation(), DefinitionAliasMixin< Base >::externalReference(), DefinitionAliasMixin< Base >::findInnerCompound(), DefinitionAliasMixin< Base >::getAlias(), DefinitionAliasMixin< Base >::getBodyDef(), DefinitionAliasMixin< Base >::getDefColumn(), DefinitionAliasMixin< Base >::getDefFileExtension(), DefinitionAliasMixin< Base >::getDefFileName(), DefinitionAliasMixin< Base >::getDefLine(), DefinitionAliasMixin< Base >::getEndBodyLine(), DefinitionAliasMixin< Base >::getLanguage(), DefinitionAliasMixin< Base >::getReference(), DefinitionAliasMixin< Base >::getReferencedByMembers(), DefinitionAliasMixin< Base >::getReferencesMembers(), DefinitionAliasMixin< Base >::getSectionRefs(), DefinitionAliasMixin< Base >::getSourceAnchor(), DefinitionAliasMixin< Base >::getSourceFileBase(), DefinitionAliasMixin< Base >::getStartBodyLine(), DefinitionAliasMixin< Base >::getStartDefLine(), DefinitionAliasMixin< Base >::hasBriefDescription(), DefinitionAliasMixin< Base >::hasDocumentation(), DefinitionAliasMixin< Base >::hasSections(), DefinitionAliasMixin< Base >::hasSources(), DefinitionAliasMixin< Base >::hasUserDocumentation(), DefinitionAliasMixin< Base >::id(), DefinitionAliasMixin< Base >::inbodyDocumentation(), DefinitionAliasMixin< Base >::inbodyFile(), DefinitionAliasMixin< Base >::inbodyLine(), DefinitionAliasMixin< Base >::isAnonymous(), DefinitionAliasMixin< Base >::isArtificial(), DefinitionAliasMixin< Base >::isHidden(), DefinitionAliasMixin< Base >::isLinkableViaGroup(), DefinitionAliasMixin< Base >::isReference(), DefinitionAliasMixin< Base >::isVisible(), DefinitionAliasMixin< Base >::isVisibleInProject(), DefinitionAliasMixin< Base >::localName(), DefinitionAliasMixin< Base >::navigationPathAsString(), DefinitionAliasMixin< Base >::partOfGroups(), DefinitionAliasMixin< Base >::pathFragment(), DefinitionAliasMixin< Base >::symbolName(), and DefinitionAliasMixin< Base >::xrefListItems().
m_impl
template<class Base >
DefinitionAliasImpl DefinitionAliasMixin< Base >::m_impl [private]
Definition at line 436 of file definitionimpl.h.
Referenced by DefinitionAliasMixin< Base >::deinit(), DefinitionAliasMixin< Base >::init(), DefinitionAliasMixin< Base >::name(), and DefinitionAliasMixin< Base >::qualifiedName().
m_scope
template<class Base >
const Definition * DefinitionAliasMixin< Base >::m_scope [private]
Definition at line 437 of file definitionimpl.h.
Referenced by DefinitionAliasMixin< Base >::getOuterScope(), and DefinitionAliasMixin< Base >::getScope().
m_symbolName
template<class Base >
QCString DefinitionAliasMixin< Base >::m_symbolName [private]
Definition at line 439 of file definitionimpl.h.
Referenced by DefinitionAliasMixin< Base >::_setSymbolName(), and DefinitionAliasMixin< Base >::_symbolName().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/definitionimpl.h
doxygen/src/definitionimpl.h