MemberNameInfo Class Reference
#include <membername.h>
Public Types
using Ptr = std::unique_ptr< MemberInfo >
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
using Ptr = std::unique_ptr< MemberInfo >
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
Public Member Functions
MemberNameInfo (const QCString &name)
QCString memberName () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
size_t size () const
Ptr & back ()
const Ptr & back () const
Ptr & front ()
const Ptr & front () const
void push_back (Ptr &&p)
MemberNameInfo (const QCString &name)
QCString memberName () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
size_t size () const
Ptr & back ()
const Ptr & back () const
Ptr & front ()
const Ptr & front () const
void push_back (Ptr &&p)
Private Attributes
QCString m_name
Vec m_members
Detailed Description
Definition at line 98 of file membername.h.
Member Typedef Documentation
const_iterator [1/2]
using MemberNameInfo::const_iterator = typename Vec::const_iterator
Definition at line 104 of file membername.h.
const_iterator [2/2]
using MemberNameInfo::const_iterator = typename Vec::const_iterator
Definition at line 104 of file membername.h.
iterator [1/2]
using MemberNameInfo::iterator = typename Vec::iterator
Definition at line 103 of file membername.h.
iterator [2/2]
using MemberNameInfo::iterator = typename Vec::iterator
Definition at line 103 of file membername.h.
Ptr [1/2]
using MemberNameInfo::Ptr = std::unique_ptr<MemberInfo>
Definition at line 101 of file membername.h.
Ptr [2/2]
using MemberNameInfo::Ptr = std::unique_ptr<MemberInfo>
Definition at line 101 of file membername.h.
Vec [1/2]
using MemberNameInfo::Vec = std::vector<Ptr>
Definition at line 102 of file membername.h.
Vec [2/2]
using MemberNameInfo::Vec = std::vector<Ptr>
Definition at line 102 of file membername.h.
Constructor & Destructor Documentation
MemberNameInfo() [1/2]
MemberNameInfo::MemberNameInfo (const QCString & name) [inline]
Definition at line 106 of file membername.h.
: m_name(name) {}
MemberNameInfo() [2/2]
MemberNameInfo::MemberNameInfo (const QCString & name) [inline]
Definition at line 106 of file membername.h.
: m_name(name) {}
Member Function Documentation
back() [1/4]
Ptr & MemberNameInfo::back () [inline]
Definition at line 115 of file membername.h.
{ return m_members.back(); }
References m_members.
back() [2/4]
Ptr & MemberNameInfo::back () [inline]
Definition at line 115 of file membername.h.
{ return m_members.back(); }
References m_members.
back() [3/4]
const Ptr & MemberNameInfo::back () const [inline]
Definition at line 116 of file membername.h.
{ return m_members.back(); }
References m_members.
back() [4/4]
const Ptr & MemberNameInfo::back () const [inline]
Definition at line 116 of file membername.h.
{ return m_members.back(); }
References m_members.
begin() [1/4]
iterator MemberNameInfo::begin () [inline]
Definition at line 109 of file membername.h.
{ return m_members.begin(); }
References m_members.
begin() [2/4]
iterator MemberNameInfo::begin () [inline]
Definition at line 109 of file membername.h.
{ return m_members.begin(); }
References m_members.
begin() [3/4]
const_iterator MemberNameInfo::begin () const [inline]
Definition at line 111 of file membername.h.
{ return m_members.begin(); }
References m_members.
begin() [4/4]
const_iterator MemberNameInfo::begin () const [inline]
Definition at line 111 of file membername.h.
{ return m_members.begin(); }
References m_members.
empty() [1/2]
bool MemberNameInfo::empty () const [inline]
Definition at line 113 of file membername.h.
{ return m_members.empty(); }
References m_members.
empty() [2/2]
bool MemberNameInfo::empty () const [inline]
Definition at line 113 of file membername.h.
{ return m_members.empty(); }
References m_members.
end() [1/4]
iterator MemberNameInfo::end () [inline]
Definition at line 110 of file membername.h.
{ return m_members.end(); }
References m_members.
end() [2/4]
iterator MemberNameInfo::end () [inline]
Definition at line 110 of file membername.h.
{ return m_members.end(); }
References m_members.
end() [3/4]
const_iterator MemberNameInfo::end () const [inline]
Definition at line 112 of file membername.h.
{ return m_members.end(); }
References m_members.
end() [4/4]
const_iterator MemberNameInfo::end () const [inline]
Definition at line 112 of file membername.h.
{ return m_members.end(); }
References m_members.
front() [1/4]
Ptr & MemberNameInfo::front () [inline]
Definition at line 117 of file membername.h.
{ return m_members.front(); }
References m_members.
Referenced by ClassDefImpl::mergeCategory().
front() [2/4]
Ptr & MemberNameInfo::front () [inline]
Definition at line 117 of file membername.h.
{ return m_members.front(); }
References m_members.
front() [3/4]
const Ptr & MemberNameInfo::front () const [inline]
Definition at line 118 of file membername.h.
{ return m_members.front(); }
References m_members.
front() [4/4]
const Ptr & MemberNameInfo::front () const [inline]
Definition at line 118 of file membername.h.
{ return m_members.front(); }
References m_members.
memberName() [1/2]
QCString MemberNameInfo::memberName () const [inline]
Definition at line 107 of file membername.h.
{ return m_name; }
References m_name.
memberName() [2/2]
QCString MemberNameInfo::memberName () const [inline]
Definition at line 107 of file membername.h.
{ return m_name; }
References m_name.
push_back() [1/2]
void MemberNameInfo::push_back (Ptr && p) [inline]
Definition at line 119 of file membername.h.
{ m_members.push_back(std::move(p)); }
References m_members, and p.
Referenced by GroupDefImpl::insertMember(), ClassDefImpl::internalInsertMember(), ClassDefImpl::mergeCategory(), and ClassDefImpl::mergeMembers().
push_back() [2/2]
void MemberNameInfo::push_back (Ptr && p) [inline]
Definition at line 119 of file membername.h.
{ m_members.push_back(std::move(p)); }
References m_members, and p.
size() [1/2]
size_t MemberNameInfo::size () const [inline]
Definition at line 114 of file membername.h.
{ return m_members.size(); }
References m_members.
size() [2/2]
size_t MemberNameInfo::size () const [inline]
Definition at line 114 of file membername.h.
{ return m_members.size(); }
References m_members.
Member Data Documentation
m_members
Vec MemberNameInfo::m_members [private]
Definition at line 123 of file membername.h.
Referenced by back(), begin(), empty(), end(), front(), push_back(), and size().
m_name
QCString MemberNameInfo::m_name [private]
Definition at line 122 of file membername.h.
Referenced by memberName().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/membername.h
doxygen/src/membername.h