TemplateSpacelessIntf Class Reference
Interface used to remove redundant spaces inside a spaceless block.
#include <template.h>
Public Member Functions
virtual ~TemplateSpacelessIntf ()=default
virtual std::unique_ptr< TemplateSpacelessIntf > clone ()=0
virtual QCString remove (const QCString &input)=0
virtual void reset ()=0
virtual ~TemplateSpacelessIntf ()=default
virtual std::unique_ptr< TemplateSpacelessIntf > clone ()=0
virtual QCString remove (const QCString &input)=0
virtual void reset ()=0
Detailed Description
Interface used to remove redundant spaces inside a spaceless block.
Definition at line 411 of file template.h.
Constructor & Destructor Documentation
 TemplateSpacelessIntf() [1/2]
virtual TemplateSpacelessIntf::~TemplateSpacelessIntf () [virtual], [default]
 TemplateSpacelessIntf() [2/2]
virtual TemplateSpacelessIntf::~TemplateSpacelessIntf () [virtual], [default]
Member Function Documentation
clone() [1/2]
virtual std::unique_ptr< TemplateSpacelessIntf > TemplateSpacelessIntf::clone () [pure virtual]
Create a copy of the spaceless filter
Implemented in LatexSpaceless, HtmlSpaceless, LatexSpaceless, and HtmlSpaceless.
clone() [2/2]
virtual std::unique_ptr< TemplateSpacelessIntf > TemplateSpacelessIntf::clone () [pure virtual]
Create a copy of the spaceless filter
Implemented in LatexSpaceless, HtmlSpaceless, LatexSpaceless, and HtmlSpaceless.
remove() [1/2]
virtual QCString TemplateSpacelessIntf::remove (const QCString & input) [pure virtual]
Returns the input after removing redundant whitespace
Implemented in LatexSpaceless, HtmlSpaceless, LatexSpaceless, and HtmlSpaceless.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
remove() [2/2]
virtual QCString TemplateSpacelessIntf::remove (const QCString & input) [pure virtual]
Returns the input after removing redundant whitespace
Implemented in LatexSpaceless, HtmlSpaceless, LatexSpaceless, and HtmlSpaceless.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
reset() [1/2]
virtual void TemplateSpacelessIntf::reset () [pure virtual]
Reset filter state
Implemented in LatexSpaceless, HtmlSpaceless, LatexSpaceless, and HtmlSpaceless.
reset() [2/2]
virtual void TemplateSpacelessIntf::reset () [pure virtual]
Reset filter state
Implemented in LatexSpaceless, HtmlSpaceless, LatexSpaceless, and HtmlSpaceless.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.h
doxygen/src/template.h