NavPathElemContext::Private Class Reference
Public Member Functions
Private (const Definition *def)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (const Definition *def)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant isLinkable () const
TemplateVariant anchor () const
TemplateVariant fileName () const
TemplateVariant isReference () const
TemplateVariant externalReference () const
TemplateVariant text () const
QCString relPathAsString () const
TemplateVariant isLinkable () const
TemplateVariant anchor () const
TemplateVariant fileName () const
TemplateVariant isReference () const
TemplateVariant externalReference () const
TemplateVariant text () const
QCString relPathAsString () const
Private Attributes
const Definition * m_def
Static Private Attributes
static const PropertyMap< NavPathElemContext::Private > s_inst
Detailed Description
Definition at line 6995 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
NavPathElemContext::Private::Private (const Definition * def) [inline]
Definition at line 6998 of file context.cpp.
: m_def(def) {}
Private() [2/2]
NavPathElemContext::Private::Private (const Definition * def) [inline]
Definition at line 6998 of file context.cpp.
: m_def(def) {}
Member Function Documentation
anchor() [1/2]
TemplateVariant NavPathElemContext::Private::anchor () const [inline], [private]
Definition at line 7007 of file context.cpp.
{ return m_def->anchor(); }
References Definition::anchor(), and m_def.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
TemplateVariant NavPathElemContext::Private::anchor () const [inline], [private]
Definition at line 7007 of file context.cpp.
{ return m_def->anchor(); }
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
externalReference() [1/2]
TemplateVariant NavPathElemContext::Private::externalReference () const [inline], [private]
Definition at line 7010 of file context.cpp.
{ return m_def->externalReference(relPathAsString()); }
References Definition::externalReference(), m_def, and relPathAsString().
externalReference() [2/2]
TemplateVariant NavPathElemContext::Private::externalReference () const [inline], [private]
Definition at line 7010 of file context.cpp.
{ return m_def->externalReference(relPathAsString()); }
fields() [1/2]
StringVector NavPathElemContext::Private::fields () const [inline]
Definition at line 7002 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector NavPathElemContext::Private::fields () const [inline]
Definition at line 7002 of file context.cpp.
{ return s_inst.fields(); }
fileName() [1/2]
TemplateVariant NavPathElemContext::Private::fileName () const [inline], [private]
Definition at line 7008 of file context.cpp.
{ return m_def->getOutputFileBase(); }
References Definition::getOutputFileBase(), and m_def.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
TemplateVariant NavPathElemContext::Private::fileName () const [inline], [private]
Definition at line 7008 of file context.cpp.
{ return m_def->getOutputFileBase(); }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
get() [1/2]
TemplateVariant NavPathElemContext::Private::get (const QCString & n) const [inline]
Definition at line 7001 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant NavPathElemContext::Private::get (const QCString & n) const [inline]
Definition at line 7001 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
isLinkable() [1/2]
TemplateVariant NavPathElemContext::Private::isLinkable () const [inline], [private]
Definition at line 7006 of file context.cpp.
{ return m_def->isLinkable(); }
References Definition::isLinkable(), and m_def.
isLinkable() [2/2]
TemplateVariant NavPathElemContext::Private::isLinkable () const [inline], [private]
Definition at line 7006 of file context.cpp.
{ return m_def->isLinkable(); }
isReference() [1/2]
TemplateVariant NavPathElemContext::Private::isReference () const [inline], [private]
Definition at line 7009 of file context.cpp.
{ return m_def->isReference(); }
References Definition::isReference(), and m_def.
isReference() [2/2]
TemplateVariant NavPathElemContext::Private::isReference () const [inline], [private]
Definition at line 7009 of file context.cpp.
{ return m_def->isReference(); }
relPathAsString() [1/2]
QCString NavPathElemContext::Private::relPathAsString () const [inline], [private]
Definition at line 7032 of file context.cpp.
    {
      bool createSubdirs = Config_getBool(CREATE_SUBDIRS);
      return createSubdirs ? QCString("../../") : QCString("");
    }
References Config_getBool.
Referenced by externalReference().
relPathAsString() [2/2]
QCString NavPathElemContext::Private::relPathAsString () const [inline], [private]
Definition at line 7032 of file context.cpp.
    {
      bool createSubdirs = Config_getBool(CREATE_SUBDIRS);
      return createSubdirs ? QCString("../../") : QCString("");
    }
References Config_getBool.
text() [1/2]
TemplateVariant NavPathElemContext::Private::text () const [inline], [private]
Definition at line 7011 of file context.cpp.
    {
      Definition::DefType type = m_def->definitionType();
      QCString text = m_def->localName();
      if (type==Definition::TypeGroup)
      {
        text = (toGroupDef(m_def))->groupTitle();
      }
      else if (type==Definition::TypePage && ((toPageDef(m_def))->hasTitle()))
      {
        text = (toPageDef(m_def))->title();
      }
      else if (type==Definition::TypeClass)
      {
        if (text.endsWith("-p"))
        {
          text = text.left(text.length()-2);
        }
      }
      return text;
    }
References Definition::definitionType(), Definition::localName(), m_def, text(), toGroupDef(), toPageDef(), Definition::TypeClass, Definition::TypeGroup, and Definition::TypePage.
Referenced by text().
text() [2/2]
TemplateVariant NavPathElemContext::Private::text () const [inline], [private]
Definition at line 7011 of file context.cpp.
    {
      Definition::DefType type = m_def->definitionType();
      QCString text = m_def->localName();
      if (type==Definition::TypeGroup)
      {
        text = (toGroupDef(m_def))->groupTitle();
      }
      else if (type==Definition::TypePage && ((toPageDef(m_def))->hasTitle()))
      {
        text = (toPageDef(m_def))->title();
      }
      else if (type==Definition::TypeClass)
      {
        if (text.endsWith("-p"))
        {
          text = text.left(text.length()-2);
        }
      }
      return text;
    }
References QCString::endsWith(), QCString::left(), QCString::length(), toGroupDef(), toPageDef(), Definition::TypeClass, Definition::TypeGroup, and Definition::TypePage.
Member Data Documentation
m_def
const Definition * NavPathElemContext::Private::m_def [private]
Definition at line 7038 of file context.cpp.
Referenced by anchor(), externalReference(), fileName(), isLinkable(), isReference(), and text().
s_inst
const PropertyMap< NavPathElemContext::Private > NavPathElemContext::Private::s_inst [static], [private]
Initial value:
{
  { "isLinkable", &Private::isLinkable },
  { "fileName", &Private::fileName },
  { "anchor", &Private::anchor },
  { "text", &Private::text },
  { "isReference", &Private::isReference },
  { "externalReference",&Private::externalReference }
}
Definition at line 7039 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp