VHDLOutlineParser Class Reference
VHDL parser using state-based lexical scanning.
#include <vhdljjparser.h>
Classes
struct Private
Public Member Functions
VHDLOutlineParser ()
virtual ~VHDLOutlineParser ()
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)
bool needsPreprocessing (const QCString &) const
void parsePrototype (const QCString &text)
void setLineParsed (int tok)
int getLine (int tok)
int getLine ()
void lineCount (const char *)
void lineCount ()
void addProto (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6)
void createFunction (const char *impure, uint64 spec, const char *fname)
void addVhdlType (const char *n, int startLine, int section, uint64 spec, const char *args, const char *type, Protection prot)
void addCompInst (const char *n, const char *instName, const char *comp, int iLine)
void handleCommentBlock (const QCString &doc, bool brief)
void handleFlowComment (const char *)
void initEntry (Entry *e)
void newEntry ()
bool isFuncProcProced ()
void pushLabel (QCString &, QCString &)
QCString popLabel (QCString &q)
bool addLibUseClause (const QCString &type)
void mapLibPackage (Entry *root)
void createFlow ()
void error_skipto (int kind)
void oneLineComment (QCString qcs)
void setMultCommentLine ()
bool checkMultiComment (QCString &qcs, int line)
void insertEntryAtLine (std::shared_ptr< Entry > ce, int line)
QCString getNameID ()
int checkInlineCode (QCString &doc)
VHDLOutlineParser ()
virtual ~VHDLOutlineParser ()
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)
bool needsPreprocessing (const QCString &) const
void parsePrototype (const QCString &text)
void setLineParsed (int tok)
int getLine (int tok)
int getLine ()
void lineCount (const char *)
void lineCount ()
void addProto (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6)
void createFunction (const char *impure, uint64 spec, const char *fname)
void addVhdlType (const char *n, int startLine, int section, uint64 spec, const char *args, const char *type, Protection prot)
void addCompInst (const char *n, const char *instName, const char *comp, int iLine)
void handleCommentBlock (const QCString &doc, bool brief)
void handleFlowComment (const char *)
void initEntry (Entry *e)
void newEntry ()
bool isFuncProcProced ()
void pushLabel (QCString &, QCString &)
QCString popLabel (QCString &q)
bool addLibUseClause (const QCString &type)
void mapLibPackage (Entry *root)
void createFlow ()
void error_skipto (int kind)
void oneLineComment (QCString qcs)
void setMultCommentLine ()
bool checkMultiComment (QCString &qcs, int line)
void insertEntryAtLine (std::shared_ptr< Entry > ce, int line)
QCString getNameID ()
int checkInlineCode (QCString &doc)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
VHDL parser using state-based lexical scanning.
This is the VHDL language parser for doxygen.
Definition at line 27 of file vhdljjparser.h.
Constructor & Destructor Documentation
VHDLOutlineParser() [1/2]
VHDLOutlineParser::VHDLOutlineParser ()
Definition at line 123 of file vhdljjparser.cpp.
                                     : p(std::make_unique<Private>())
{
}
 VHDLOutlineParser() [1/2]
VHDLOutlineParser::~VHDLOutlineParser () [virtual]
Definition at line 127 of file vhdljjparser.cpp.
{
}
VHDLOutlineParser() [2/2]
VHDLOutlineParser::VHDLOutlineParser ()
 VHDLOutlineParser() [2/2]
virtual VHDLOutlineParser::~VHDLOutlineParser () [virtual]
Member Function Documentation
addCompInst() [1/2]
void VHDLOutlineParser::addCompInst (const char * n, const char * instName, const char * comp, int iLine)
Definition at line 470 of file vhdljjparser.cpp.
{
  VhdlParser::SharedState *s = &p->shared;
  s->current->spec=VhdlDocGen::INSTANTIATION;
  s->current->section=Entry::VARIABLE_SEC;
  s->current->startLine=iLine;
  s->current->bodyLine=iLine;
  s->current->type=instName; // foo:instname e.g proto or work. proto(ttt)
  s->current->exception=s->genLabels.lower(); // |arch|label1:label2...
  s->current->name=n; // foo
  if (s->lastCompound)
  {
    s->current->args=s->lastCompound->name; // architecture name
  }
  s->current->includeName=comp; // component/entity/configuration
  int u=s->genLabels.find("|",1);
  if (u>0)
  {
    s->current->write=s->genLabels.right(s->genLabels.length()-u);
    s->current->read=s->genLabels.left(u);
  }
  //printf (" \n genlabel: [%s] inst: [%s] name: [%s] %d\n",n,instName,comp,iLine);
  if (s->lastCompound)
  {
    s->current->args=s->lastCompound->name;
    if (true) // !findInstant(current->type))
    {
      initEntry(s->current.get());
      // TODO: protect with mutex
      g_instFiles.emplace_back(std::make_shared<Entry>(*s->current));
      // TODO: end protect with mutex
    }
    s->current=std::make_shared<Entry>();
  }
  else
  {
    newEntry();
  }
}
References g_instFiles, initEntry(), VhdlDocGen::INSTANTIATION, n, newEntry(), p, s, and Entry::VARIABLE_SEC.
Referenced by vhdl::parser::VhdlParser::component_instantiation_statement().
addCompInst() [2/2]
void VHDLOutlineParser::addCompInst (const char * n, const char * instName, const char * comp, int iLine)
addLibUseClause() [1/2]
bool VHDLOutlineParser::addLibUseClause (const QCString & type)
Definition at line 707 of file vhdljjparser.cpp.
{
  bool showIEEESTD=Config_getBool(FORCE_LOCAL_INCLUDES);
  if (showIEEESTD) // all standard packages and libraries will not be shown
  {
    if (type.lower().stripPrefix("ieee")) return FALSE;
    if (type.lower().stripPrefix("std")) return FALSE;
  }
  return TRUE;
}
References Config_getBool, FALSE, QCString::lower(), QCString::stripPrefix(), and TRUE.
Referenced by mapLibPackage().
addLibUseClause() [2/2]
bool VHDLOutlineParser::addLibUseClause (const QCString & type)
addProto() [1/2]
void VHDLOutlineParser::addProto (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6)
Definition at line 627 of file vhdljjparser.cpp.
{
  VhdlParser::SharedState *s = &p->shared;
  (void)s5; // avoid unused warning
  QCString name=s2;
  StringVector ql=split(name.str(),",");
  for (const auto &n : ql)
  {
    Argument arg;
    arg.name=n;
    if (s3)
    {
      arg.type=s3;
    }
    arg.type+=" ";
    arg.type+=s4;
    if (s6)
    {
      arg.type+=s6;
    }
    if (s->parse_sec==GEN_SEC && s->param_sec==0)
    {
      arg.defval="gen!";
    }
    if (s->parse_sec==PARAM_SEC)
    {
    // assert(false);
    }
    arg.defval+=s1;
    arg.attrib="";//s6;
    s->current->argList.push_back(arg);
    s->current->args+=s2;
    s->current->args+=",";
  }
}
References Argument::attrib, Argument::defval, GEN_SEC, n, setup::name, Argument::name, p, PARAM_SEC, s, split(), and Argument::type.
Referenced by vhdl::parser::VhdlParser::interface_variable_declaration().
addProto() [2/2]
void VHDLOutlineParser::addProto (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6)
addVhdlType() [1/2]
void VHDLOutlineParser::addVhdlType (const char * n, int startLine, int section, uint64 spec, const char * args, const char * type, Protection prot)
Definition at line 512 of file vhdljjparser.cpp.
{
  VhdlParser::SharedState *s = &p->shared;
  QCString name(n);
  if (isFuncProcProced() || VhdlDocGen::getFlowMember()) return;
  if (s->parse_sec==GEN_SEC)
  {
    spec= VhdlDocGen::GENERIC;
  }
  StringVector ql=split(name.str(),",");
  for (size_t u=0;u<ql.size();u++)
  {
    s->current->name=ql[u];
    s->current->startLine=startLine;
    s->current->bodyLine=startLine;
    s->current->section=section;
    s->current->spec=spec;
    s->current->fileName=p->yyFileName;
    if (s->current->args.isEmpty())
    {
      s->current->args=args;
    }
    s->current->type=type;
    s->current->protection=prot;
    if (!s->lastCompound && (section==Entry::VARIABLE_SEC) && (spec == VhdlDocGen::USE || spec == VhdlDocGen::LIBRARY))
    {
      p->libUse.emplace_back(std::make_shared<Entry>(*s->current));
      s->current->reset();
    }
    newEntry();
  }
}
References GEN_SEC, VhdlDocGen::GENERIC, VhdlDocGen::getFlowMember(), isFuncProcProced(), VhdlDocGen::LIBRARY, n, setup::name, newEntry(), p, s, split(), VhdlDocGen::USE, and Entry::VARIABLE_SEC.
Referenced by vhdl::parser::VhdlParser::alias_declaration(), vhdl::parser::VhdlParser::architecture_body(), vhdl::parser::VhdlParser::attribute_declaration(), vhdl::parser::VhdlParser::attribute_specification(), vhdl::parser::VhdlParser::component_declaration(), vhdl::parser::VhdlParser::configuration_declaration(), vhdl::parser::VhdlParser::constant_declaration(), vhdl::parser::VhdlParser::context_declaration(), vhdl::parser::VhdlParser::element_declaration(), vhdl::parser::VhdlParser::entity_declaration(), vhdl::parser::VhdlParser::file_declaration(), vhdl::parser::VhdlParser::full_type_declaration(), vhdl::parser::VhdlParser::ifunc(), vhdl::parser::VhdlParser::interface_declaration(), vhdl::parser::VhdlParser::interface_file_declaration(), vhdl::parser::VhdlParser::interface_variable_declaration(), vhdl::parser::VhdlParser::library_clause(), vhdl::parser::VhdlParser::package_body(), vhdl::parser::VhdlParser::package_declaration(), vhdl::parser::VhdlParser::package_instantiation_declaration(), vhdl::parser::VhdlParser::physical_type_definition(), vhdl::parser::VhdlParser::secondary_unit_declaration(), vhdl::parser::VhdlParser::signal_declaration(), vhdl::parser::VhdlParser::subprogram_instantiation_declaration(), vhdl::parser::VhdlParser::subtype_declaration(), vhdl::parser::VhdlParser::use_clause(), and vhdl::parser::VhdlParser::variable_declaration().
addVhdlType() [2/2]
void VHDLOutlineParser::addVhdlType (const char * n, int startLine, int section, uint64 spec, const char * args, const char * type, Protection prot)
checkInlineCode() [1/2]
int VHDLOutlineParser::checkInlineCode (QCString & doc)
Definition at line 272 of file vhdljjparser.cpp.
{
  static const reg::Ex csRe(R"([\\@]code)");
  static const reg::Ex cendRe(R"(\s*[\\@]endcode)");
  static const reg::Ex cbriefRe(R"([\\@]brief)");
  // helper to simulate behavior of QString.find(const QRegExp &re,int pos)
  auto findRe = [](const QCString &str,const reg::Ex &re,int pos=0) -> int
  {
    if ((int)str.length()<pos) return -1;
    reg::Match match;
    const std::string s = str.str();
    if (reg::search(s,match,re,pos)) // match found
    {
      return (int)match.position();
    }
    else // not found
    {
      return -1;
    }
  };
  auto replaceRe = [](const QCString &str,const reg::Ex &re,const QCString &replacement) -> QCString
  {
    return reg::replace(str.str(), re, replacement.str());
  };
  int index = findRe(doc,csRe);
  if (findRe(doc,cendRe)!=-1)
    return 1;
  if (index < 0)
    return index;
  VhdlParser::SharedState *s = &p->shared;
  p->strComment += doc;
  p->code = findRe(p->inputString,csRe, p->code + 1);
  int com = p->inputString.find(p->strComment.data());
  int ref = findRe(p->inputString,cendRe, p->code + 1);
  int len = p->strComment.size();
  int ll = com + len;
  int diff = ref - ll - 3;
  QCString code = p->inputString.mid(ll, diff);
  int iLine = 0;
  code = stripLeadingAndTrailingEmptyLines(code, iLine);
  int val = code.contains('\n');
  VhdlDocGen::prepareComment(p->strComment);
  StringVector ql = split(p->strComment.str(),"\n");
  QCString co;
  QCString na;
  for (const auto &qcs_ : ql)
  {
    QCString qcs(qcs_);
    qcs = qcs.simplifyWhiteSpace();
    if (findRe(qcs,csRe)!=-1)
    {
      int i = qcs.find('{');
      int j = qcs.find('}');
      if (i > 0 && j > 0 && j > i)
      {
        na = qcs.mid(i + 1, (j - i - 1));
      }
      continue;
    }
    qcs = replaceRe(qcs,cbriefRe, "");
    co += qcs;
    co += '\n';
  }
  VhdlDocGen::prepareComment(co);
  Entry gBlock;
  if (!na.isEmpty())
    gBlock.name = na;
  else
    gBlock.name = "misc" + VhdlDocGen::getRecordNumber();
  gBlock.startLine = p->yyLineNr+iLine-1;
  gBlock.bodyLine = p->yyLineNr+iLine-1 ;
  gBlock.doc = code;
  gBlock.inbodyDocs = code;
  gBlock.brief = co;
  gBlock.section = Entry::VARIABLE_SEC;
  gBlock.spec = VhdlDocGen::MISCELLANEOUS;
  gBlock.fileName = p->yyFileName;
  gBlock.endBodyLine = p->yyLineNr + val +iLine;
  gBlock.lang = SrcLangExt_VHDL;
  std::shared_ptr<Entry> compound;
  if (s->lastEntity)
    compound = s->lastEntity;
  else if (s->lastCompound)
    compound = s->lastCompound;
  else
    compound = 0;
  if (compound)
  {
    compound->copyToSubEntry(&gBlock);
  }
  else
  {
    gBlock.type = "misc"; // global code like library ieee...
    s->current_root->copyToSubEntry(&gBlock);
  }
  p->strComment.resize(0);
  return 1;
}
References Entry::bodyLine, Entry::brief, QCString::contains(), Entry::doc, Entry::endBodyLine, Entry::fileName, QCString::find(), VhdlDocGen::getRecordNumber(), Entry::inbodyDocs, QCString::isEmpty(), Entry::lang, len, QCString::length(), reg::match(), QCString::mid(), VhdlDocGen::MISCELLANEOUS, Entry::name, p, VhdlDocGen::prepareComment(), reg::replace(), s, reg::search(), Entry::section, QCString::simplifyWhiteSpace(), Entry::spec, split(), SrcLangExt_VHDL, Entry::startLine, QCString::str(), string, stripLeadingAndTrailingEmptyLines(), Entry::type, testsqlite3::val, and Entry::VARIABLE_SEC.
Referenced by handleCommentBlock().
checkInlineCode() [2/2]
int VHDLOutlineParser::checkInlineCode (QCString & doc)
checkMultiComment() [1/2]
bool VHDLOutlineParser::checkMultiComment (QCString & qcs, int line)
Definition at line 805 of file vhdljjparser.cpp.
{
  VhdlParser::SharedState *s = &p->shared;
  insertEntryAtLine(s->current_root,line);
  if (p->lineEntry.empty()) return false;
  VhdlDocGen::prepareComment(qcs);
  while (!p->lineEntry.empty())
  {
    std::shared_ptr<Entry> e=p->lineEntry.back();
    e->briefLine=line;
    e->brief+=qcs;
    p->lineEntry.pop_back();
  }
  return true;
}
References e, insertEntryAtLine(), p, VhdlDocGen::prepareComment(), and s.
Referenced by handleCommentBlock(), and oneLineComment().
checkMultiComment() [2/2]
bool VHDLOutlineParser::checkMultiComment (QCString & qcs, int line)
createFlow() [1/2]
void VHDLOutlineParser::createFlow ()
Definition at line 739 of file vhdljjparser.cpp.
{
  VhdlParser::SharedState *s = &p->shared;
  if (!VhdlDocGen::getFlowMember())
  {
    return;
  }
  QCString q,ret;
  if (s->currP==VhdlDocGen::FUNCTION)
  {
    q=":function(";
    FlowChart::alignFuncProc(q,s->tempEntry->argList,true);
    q+=")";
  }
  else if (s->currP==VhdlDocGen::PROCEDURE)
  {
    q=":procedure (";
    FlowChart::alignFuncProc(q,s->tempEntry->argList,false);
    q+=")";
  }
  else
  {
    q=":process("+s->tempEntry->args;
    q+=")";
  }
  q.prepend(VhdlDocGen::getFlowMember()->name());
  FlowChart::addFlowChart(FlowChart::START_NO,q,QCString());
  if (s->currP==VhdlDocGen::FUNCTION)
  {
    ret="end function ";
  }
  else if (s->currP==VhdlDocGen::PROCEDURE)
  {
    ret="end procedure";
  }
  else
  {
    ret="end process ";
  }
  FlowChart::addFlowChart(FlowChart::END_NO,ret,QCString());
  // FlowChart::printFlowList();
  FlowChart::writeFlowChart();
  s->currP=0;
}
References FlowChart::addFlowChart(), FlowChart::alignFuncProc(), FlowChart::END_NO, VhdlDocGen::FUNCTION, VhdlDocGen::getFlowMember(), setup::name, p, QCString::prepend(), VhdlDocGen::PROCEDURE, s, FlowChart::START_NO, and FlowChart::writeFlowChart().
Referenced by vhdl::parser::VhdlParser::process_statement(), and vhdl::parser::VhdlParser::subprogram_body().
createFlow() [2/2]
void VHDLOutlineParser::createFlow ()
createFunction() [1/2]
void VHDLOutlineParser::createFunction (const char * impure, uint64 spec, const char * fname)
Definition at line 550 of file vhdljjparser.cpp.
{
  VhdlParser::SharedState *s = &p->shared;
  QCString impure(imp);
  QCString fname(fn);
  s->current->spec=spec;
  s->current->section=Entry::FUNCTION_SEC;
  if (impure=="impure" || impure=="pure")
  {
    s->current->exception=impure;
  }
  if (s->parse_sec==GEN_SEC)
  {
    s->current->spec= VhdlDocGen::GENERIC;
    s->current->section=Entry::FUNCTION_SEC;
  }
  if (s->currP==VhdlDocGen::PROCEDURE)
  {
    s->current->name=impure;
    s->current->exception="";
  }
  else
  {
    s->current->name=fname;
  }
  if (spec==VhdlDocGen::PROCESS)
  {
    s->current->args=fname;
    s->current->name=impure;
    VhdlDocGen::deleteAllChars(s->current->args,' ');
    if (!fname.isEmpty())
    {
      StringVector q1=split(fname.str(),",");
      for (const auto &name : q1)
      {
        Argument arg;
        arg.name=name;
        s->current->argList.push_back(arg);
      }
    }
  }
}
References VhdlDocGen::deleteAllChars(), Entry::FUNCTION_SEC, GEN_SEC, VhdlDocGen::GENERIC, QCString::isEmpty(), setup::name, Argument::name, p, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, s, split(), and QCString::str().
Referenced by vhdl::parser::VhdlParser::process_statement(), and vhdl::parser::VhdlParser::subprogram_specification().
createFunction() [2/2]
void VHDLOutlineParser::createFunction (const char * impure, uint64 spec, const char * fname)
error_skipto() [1/2]
void VHDLOutlineParser::error_skipto (int kind)
Definition at line 843 of file vhdljjparser.cpp.
{
  Token *op;
  do
  {
    p->vhdlParser->getNextToken(); // step to next token
    op=p->vhdlParser->getToken(1); // get first token
    if (op==0) break;
    //fprintf(stderr,"\n %s",qPrint(t->image));
  } while (op->kind != kind);
  p->vhdlParser->clearError();
  // The above loop consumes tokens all the way up to a token of
  // "kind". We use a do-while loop rather than a while because the
  // current token is the one immediately before the erroneous token
  // (in our case the token immediately before what should have been
  // "if"/"while".
}
References vhdl::parser::Token::kind, and p.
Referenced by vhdl::parser::VhdlParser::architecture_body(), vhdl::parser::VhdlParser::generate_statement(), and vhdl::parser::VhdlParser::protected_type_declaration().
error_skipto() [2/2]
void VHDLOutlineParser::error_skipto (int kind)
getLine() [1/4]
int VHDLOutlineParser::getLine ()
Definition at line 719 of file vhdljjparser.cpp.
{
  return p->yyLineNr;
}
References p.
getLine() [2/4]
int VHDLOutlineParser::getLine ()
getLine() [3/4]
int VHDLOutlineParser::getLine (int tok)
Definition at line 730 of file vhdljjparser.cpp.
{
  int val=p->lineParse[tok];
  if (val<0) val=0;
  //assert(val>=0 && val<=yyLineNr);
  return val;
}
References p, and testsqlite3::val.
Referenced by vhdl::parser::VhdlParser::ifunc(), vhdl::parser::VhdlParser::package_declaration(), vhdl::parser::VhdlParser::process_statement(), vhdl::parser::VhdlParser::subprogram_body(), and vhdl::parser::VhdlParser::subprogram_specification().
getLine() [4/4]
int VHDLOutlineParser::getLine (int tok)
getNameID() [1/2]
QCString VHDLOutlineParser::getNameID ()
returns a unique id for each record member.
type first_rec is record RE: data_type; end;
type second_rec is record RE: data_type; end;
Definition at line 254 of file vhdljjparser.cpp.
{
  return QCString().setNum(idCounter++);
}
References idCounter, and QCString::setNum().
Referenced by vhdl::parser::VhdlParser::element_declaration().
getNameID() [2/2]
QCString VHDLOutlineParser::getNameID ()
handleCommentBlock() [1/2]
void VHDLOutlineParser::handleCommentBlock (const QCString & doc, bool brief)
Definition at line 382 of file vhdljjparser.cpp.
{
  int position = 0;
  bool needsEntry = FALSE;
  VhdlParser::SharedState *s = &p->shared;
  QCString doc = doc1;
  if (doc.isEmpty())
    return;
  if (checkMultiComment(doc, p->yyLineNr))
  {
    p->strComment.resize(0);
    return;
  }
  if (checkInlineCode(doc) > 0)
  {
    return;
  }
  Protection protection = Public;
  VhdlDocGen::prepareComment(doc);
  if (p->oldEntry == s->current.get())
  {
    p->str_doc.doc = doc;
    p->str_doc.iDocLine = p->iDocLine;
    p->str_doc.brief = brief;
    p->str_doc.pending = TRUE;
    return;
  }
  p->oldEntry = s->current.get();
  if (brief)
  {
    s->current->briefLine = p->yyLineNr;
  }
  else
  {
    s->current->docLine = p->yyLineNr;
  }
  Markdown markdown(p->yyFileName,p->iDocLine);
  int lineNr = p->iDocLine;
  QCString processedDoc = Config_getBool(MARKDOWN_SUPPORT) ? markdown.process(doc,lineNr) : doc;
   while (p->commentScanner.parseCommentBlock(
      p->thisParser,
      s->current.get(),
      processedDoc, // text
      p->yyFileName, // file
      lineNr, // line of block start
      brief,
      0,
      FALSE,
      protection,
      position,
      needsEntry,
      Config_getBool(MARKDOWN_SUPPORT)))
  {
    if (needsEntry)
      newEntry();
  }
  if (needsEntry)
  {
    if (p->varr)
    {
      p->varr = FALSE;
      s->current->name = p->varName;
      s->current->section = Entry::VARIABLEDOC_SEC;
      p->varName = "";
    }
    newEntry();
  }
  p->iDocLine = -1;
  p->strComment.resize(0);
}
References checkInlineCode(), checkMultiComment(), Config_getBool, FALSE, QCString::isEmpty(), newEntry(), p, VhdlDocGen::prepareComment(), Markdown::process(), Public, s, TRUE, and Entry::VARIABLEDOC_SEC.
Referenced by initEntry(), oneLineComment(), and vhdl::parser::VhdlParserTokenManager::SkipLexicalActions().
handleCommentBlock() [2/2]
void VHDLOutlineParser::handleCommentBlock (const QCString & doc, bool brief)
handleFlowComment() [1/2]
void VHDLOutlineParser::handleFlowComment (const char * doc)
Definition at line 259 of file vhdljjparser.cpp.
{
  lineCount(doc);
  if (VhdlDocGen::getFlowMember())
  {
    QCString qcs(doc);
    qcs=qcs.stripWhiteSpace();
    qcs.stripPrefix("--#");
    FlowChart::addFlowChart(FlowChart::COMMENT_NO,QCString(),QCString(),qcs);
  }
}
References FlowChart::addFlowChart(), FlowChart::COMMENT_NO, VhdlDocGen::getFlowMember(), lineCount(), QCString::stripPrefix(), and QCString::stripWhiteSpace().
Referenced by vhdl::parser::VhdlParserTokenManager::SkipLexicalActions().
handleFlowComment() [2/2]
void VHDLOutlineParser::handleFlowComment (const char *)
initEntry() [1/2]
void VHDLOutlineParser::initEntry (Entry * e)
Definition at line 194 of file vhdljjparser.cpp.
{
  e->fileName = p->yyFileName;
  e->lang = SrcLangExt_VHDL;
  if (p->str_doc.pending)
  {
    p->str_doc.pending=FALSE;
    p->oldEntry=0; // prevents endless recursion
    p->iDocLine=p->str_doc.iDocLine;
    handleCommentBlock(p->str_doc.doc,p->str_doc.brief);
    p->iDocLine=-1;
  }
  p->commentScanner.initGroupInfo(e);
}
References e, FALSE, handleCommentBlock(), p, and SrcLangExt_VHDL.
Referenced by addCompInst(), newEntry(), and parseInput().
initEntry() [2/2]
void VHDLOutlineParser::initEntry (Entry * e)
insertEntryAtLine() [1/2]
void VHDLOutlineParser::insertEntryAtLine (std::shared_ptr< Entry > ce, int line)
Definition at line 825 of file vhdljjparser.cpp.
{
  for (const auto &rt : ce->children())
  {
    if (rt->bodyLine==line)
    {
      p->lineEntry.push_back(rt);
    }
    insertEntryAtLine(rt,line);
  }
}
References insertEntryAtLine(), and p.
Referenced by checkMultiComment(), and insertEntryAtLine().
insertEntryAtLine() [2/2]
void VHDLOutlineParser::insertEntryAtLine (std::shared_ptr< Entry > ce, int line)
isFuncProcProced() [1/2]
bool VHDLOutlineParser::isFuncProcProced ()
Definition at line 598 of file vhdljjparser.cpp.
{
  VhdlParser::SharedState *s = &p->shared;
  if (s->currP==VhdlDocGen::FUNCTION ||
      s->currP==VhdlDocGen::PROCEDURE ||
      s->currP==VhdlDocGen::PROCESS
     )
  {
    return TRUE;
  }
  return FALSE;
}
References FALSE, VhdlDocGen::FUNCTION, p, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, s, and TRUE.
Referenced by addVhdlType().
isFuncProcProced() [2/2]
bool VHDLOutlineParser::isFuncProcProced ()
lineCount() [1/4]
void VHDLOutlineParser::lineCount ()
Definition at line 181 of file vhdljjparser.cpp.
{
  p->yyLineNr++;
}
References p.
Referenced by handleFlowComment().
lineCount() [2/4]
void VHDLOutlineParser::lineCount ()
lineCount() [3/4]
void VHDLOutlineParser::lineCount (const char * text)
Definition at line 186 of file vhdljjparser.cpp.
{
  for (const char* c=text ; *c ; ++c)
  {
    if (*c == '\n') p->yyLineNr++;
  }
}
References c, and p.
Referenced by vhdl::parser::VhdlParserTokenManager::SkipLexicalActions().
lineCount() [4/4]
void VHDLOutlineParser::lineCount (const char *)
mapLibPackage() [1/2]
void VHDLOutlineParser::mapLibPackage (Entry * root)
Definition at line 680 of file vhdljjparser.cpp.
{
  for (const auto &rt : p->libUse)
  {
    if (addLibUseClause(rt->name))
    {
      bool bFound=FALSE;
      for (const auto &current : root->children())
      {
        if (VhdlDocGen::isVhdlClass(current.get()))
        {
          if (current->startLine > rt->startLine)
          {
            bFound=TRUE;
            current->copyToSubEntry(rt);
            break;
          }
        }
      }//for
      if (!bFound)
      {
        root->copyToSubEntry(rt);
      }
    } //if
  }// for
}//MapLib
References addLibUseClause(), Entry::children(), Entry::copyToSubEntry(), FALSE, VhdlDocGen::isVhdlClass(), p, and TRUE.
Referenced by parseInput().
mapLibPackage() [2/2]
void VHDLOutlineParser::mapLibPackage (Entry * root)
needsPreprocessing() [1/2]
bool VHDLOutlineParser::needsPreprocessing (const QCString & extension) const [inline], [virtual]
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 37 of file vhdljjparser.h.
{ return TRUE; }
References TRUE.
needsPreprocessing() [2/2]
bool VHDLOutlineParser::needsPreprocessing (const QCString & extension) const [inline], [virtual]
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 37 of file vhdljjparser.h.
{ return TRUE; }
References TRUE.
newEntry() [1/2]
void VHDLOutlineParser::newEntry ()
Definition at line 209 of file vhdljjparser.cpp.
{
  VhdlParser::SharedState *s = &p->shared;
  p->previous = s->current.get();
  if (s->current->spec==VhdlDocGen::ENTITY ||
      s->current->spec==VhdlDocGen::PACKAGE ||
      s->current->spec==VhdlDocGen::ARCHITECTURE ||
      s->current->spec==VhdlDocGen::PACKAGE_BODY)
  {
    s->current_root->moveToSubEntryAndRefresh(s->current);
  }
  else
  {
    if (s->lastCompound)
    {
      s->lastCompound->moveToSubEntryAndRefresh(s->current);
    }
    else
    {
      if (s->lastEntity)
      {
    s->lastEntity->moveToSubEntryAndRefresh(s->current);
      }
      else
      {
    s->current_root->moveToSubEntryAndRefresh(s->current);
      }
    }
  }
  initEntry(s->current.get());
}
References VhdlDocGen::ARCHITECTURE, VhdlDocGen::ENTITY, initEntry(), p, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, and s.
Referenced by addCompInst(), addVhdlType(), handleCommentBlock(), vhdl::parser::VhdlParser::process_statement(), and vhdl::parser::VhdlParser::subprogram_specification().
newEntry() [2/2]
void VHDLOutlineParser::newEntry ()
oneLineComment() [1/2]
void VHDLOutlineParser::oneLineComment (QCString qcs)
Definition at line 794 of file vhdljjparser.cpp.
{
    int j=qcs.find("--!");
    qcs=qcs.right(qcs.length()-3-j);
    if (!checkMultiComment(qcs,p->iDocLine))
    {
      handleCommentBlock(qcs,TRUE);
    }
}
References checkMultiComment(), QCString::find(), handleCommentBlock(), QCString::length(), p, QCString::right(), and TRUE.
Referenced by vhdl::parser::VhdlParserTokenManager::SkipLexicalActions().
oneLineComment() [2/2]
void VHDLOutlineParser::oneLineComment (QCString qcs)
parseInput() [1/2]
void VHDLOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) [virtual]
Parses a single input file with the goal to build an Entry tree.
Parameters
 in fileName The full name of the file.
 in fileBuf The contents of the file (zero terminated).
 in,out root The root of the tree of Entry *nodes representing the information extracted from the file.
 in clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
Definition at line 131 of file vhdljjparser.cpp.
{
  VhdlParser::SharedState *s = &p->shared;
  p->thisParser=this;
  p->inputString=fileBuf;
 // fprintf(stderr,"\n ============= %s\n ==========\n",fileBuf);
  bool inLine = fileName.isEmpty();
  p->yyFileName=fileName;
  bool xilinx_ucf=isConstraintFile(p->yyFileName,".ucf");
  bool altera_qsf=isConstraintFile(p->yyFileName,".qsf");
  // support XILINX(ucf) and ALTERA (qsf) file
  if (xilinx_ucf)
  {
    VhdlDocGen::parseUCF(fileBuf,root.get(),p->yyFileName,FALSE);
    return;
  }
  if (altera_qsf)
  {
    VhdlDocGen::parseUCF(fileBuf,root.get(),p->yyFileName,TRUE);
    return;
  }
  p->yyLineNr=1;
  s->current_root=root;
  s->lastCompound=0;
  s->lastEntity=0;
  s->lastEntity=0;
  p->oldEntry = 0;
  s->current=std::make_shared<Entry>();
  initEntry(s->current.get());
  p->commentScanner.enterFile(fileName,p->yyLineNr);
  p->lineParse.reserve(200);
  p->parseVhdlfile(fileName,fileBuf,inLine);
  p->commentScanner.leaveFile(fileName,p->yyLineNr);
  s->current.reset();
  if (!inLine)
  mapLibPackage(root.get());
  p->yyFileName.resize(0);
  p->libUse.clear();
}
References FALSE, initEntry(), isConstraintFile(), QCString::isEmpty(), mapLibPackage(), p, VhdlDocGen::parseUCF(), s, and TRUE.
parseInput() [2/2]
void VHDLOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) [virtual]
Parses a single input file with the goal to build an Entry tree.
Parameters
 in fileName The full name of the file.
 in fileBuf The contents of the file (zero terminated).
 in,out root The root of the tree of Entry *nodes representing the information extracted from the file.
 in clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
parsePrototype() [1/2]
void VHDLOutlineParser::parsePrototype (const QCString & text) [virtual]
Callback function called by the comment block scanner. It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Definition at line 464 of file vhdljjparser.cpp.
{
  p->varName=text;
  p->varr=TRUE;
}
References p, and TRUE.
parsePrototype() [2/2]
void VHDLOutlineParser::parsePrototype (const QCString & text) [virtual]
Callback function called by the comment block scanner. It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
popLabel() [1/2]
QCString VHDLOutlineParser::popLabel (QCString & q)
Definition at line 617 of file vhdljjparser.cpp.
{
  int i=q.findRev("|");
  if (i<0) return QCString();
  q = q.left(i);
  return q;
}
References QCString::findRev(), and QCString::left().
Referenced by vhdl::parser::VhdlParser::block_statement(), and vhdl::parser::VhdlParser::generate_statement().
popLabel() [2/2]
QCString VHDLOutlineParser::popLabel (QCString & q)
pushLabel() [1/2]
void VHDLOutlineParser::pushLabel (QCString & label, QCString & val)
Definition at line 611 of file vhdljjparser.cpp.
{
  label+="|";
  label+=val;
}
References testsqlite3::val.
Referenced by vhdl::parser::VhdlParser::architecture_body(), vhdl::parser::VhdlParser::block_statement(), and vhdl::parser::VhdlParser::generate_statement().
pushLabel() [2/2]
void VHDLOutlineParser::pushLabel (QCString & , QCString &)
setLineParsed() [1/2]
void VHDLOutlineParser::setLineParsed (int tok)
Definition at line 724 of file vhdljjparser.cpp.
{
  if ((int)p->lineParse.size()<=tok) p->lineParse.resize(tok+1);
  p->lineParse[tok]=p->yyLineNr;
}
References p.
Referenced by vhdl::parser::VhdlParserTokenManager::TokenLexicalActions().
setLineParsed() [2/2]
void VHDLOutlineParser::setLineParsed (int tok)
setMultCommentLine() [1/2]
void VHDLOutlineParser::setMultCommentLine ()
Definition at line 789 of file vhdljjparser.cpp.
{
  p->iDocLine=p->yyLineNr;
}
References p.
Referenced by vhdl::parser::VhdlParserTokenManager::SkipLexicalActions().
setMultCommentLine() [2/2]
void VHDLOutlineParser::setMultCommentLine ()
Member Data Documentation
p
std::unique_ptr< Private > VHDLOutlineParser::p [private]
Definition at line 72 of file vhdljjparser.h.
Referenced by addCompInst(), addProto(), addVhdlType(), checkInlineCode(), checkMultiComment(), createFlow(), createFunction(), error_skipto(), filter2008VhdlComment(), getLine(), handleCommentBlock(), initEntry(), insertEntryAtLine(), isFuncProcProced(), lineCount(), mapLibPackage(), newEntry(), oneLineComment(), parseInput(), parsePrototype(), setLineParsed(), and setMultCommentLine().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/vhdljjparser.h
doxygen/src/vhdljjparser.h
doxygen/build/doxygen/src/vhdljjparser.cpp
doxygen/src/vhdljjparser.cpp