TuneColorDialog Class Reference
#include <wizard.h>
Public Member Functions
TuneColorDialog (int hue, int sat, int gamma, QWidget *parent=0)
int getHue () const
int getSaturation () const
int getGamma () const
TuneColorDialog (int hue, int sat, int gamma, QWidget *parent=0)
int getHue () const
int getSaturation () const
int getGamma () const
Private Slots
void updateImage (int hue, int sat, int val)
void updateImage (int hue, int sat, int val)
Private Attributes
QImage * m_image = 0
QLabel * m_imageLab = 0
int m_hue = 0
int m_sat = 0
int m_gam = 0
Detailed Description
Definition at line 34 of file wizard.h.
Constructor & Destructor Documentation
TuneColorDialog() [1/2]
TuneColorDialog::TuneColorDialog (int hue, int sat, int gamma, QWidget * parent = 0)
Definition at line 182 of file wizard.cpp.
                                                                          : QDialog(parent)
{
   setWindowTitle(tr("Tune the color of the HTML output"));
   QGridLayout *layout = new QGridLayout(this);
   m_image = new QImage(QString::fromLatin1(":/images/tunecolor.png"));
   m_imageLab = new QLabel;
   updateImage(hue,sat,gamma);
   layout->addWidget(new QLabel(tr("Example output: use the sliders on the right to adjust the color")),0,0);
   layout->addWidget(m_imageLab,1,0);
   QHBoxLayout *buttonsLayout = new QHBoxLayout;
   QPushButton *okButton = new QPushButton(tr("Ok"));
   connect(okButton,SIGNAL(clicked()),SLOT(accept()));
   okButton->setDefault(true);
   QPushButton *cancelButton = new QPushButton(tr("Cancel"));
   connect(cancelButton,SIGNAL(clicked()),SLOT(reject()));
   ColorPicker *huePicker = new ColorPicker(ColorPicker::Hue);
   huePicker->setCol(hue,sat,gamma);
   huePicker->setFixedWidth(20);
   layout->addWidget(huePicker,1,1);
   ColorPicker *satPicker = new ColorPicker(ColorPicker::Saturation);
   satPicker->setCol(hue,sat,gamma);
   satPicker->setFixedWidth(20);
   layout->addWidget(satPicker,1,2);
   ColorPicker *gamPicker = new ColorPicker(ColorPicker::Gamma);
   gamPicker->setCol(hue,sat,gamma);
   gamPicker->setFixedWidth(20);
   layout->addWidget(gamPicker,1,3);
   connect(huePicker,SIGNAL(newHsv(int,int,int)),satPicker,SLOT(setCol(int,int,int)));
   connect(satPicker,SIGNAL(newHsv(int,int,int)),huePicker,SLOT(setCol(int,int,int)));
   connect(huePicker,SIGNAL(newHsv(int,int,int)),gamPicker,SLOT(setCol(int,int,int)));
   connect(satPicker,SIGNAL(newHsv(int,int,int)),gamPicker,SLOT(setCol(int,int,int)));
   connect(gamPicker,SIGNAL(newHsv(int,int,int)),satPicker,SLOT(setCol(int,int,int)));
   connect(gamPicker,SIGNAL(newHsv(int,int,int)),huePicker,SLOT(setCol(int,int,int)));
   connect(huePicker,SIGNAL(newHsv(int,int,int)),this,SLOT(updateImage(int,int,int)));
   connect(satPicker,SIGNAL(newHsv(int,int,int)),this,SLOT(updateImage(int,int,int)));
   connect(gamPicker,SIGNAL(newHsv(int,int,int)),this,SLOT(updateImage(int,int,int)));
   buttonsLayout->addStretch();
   buttonsLayout->addWidget(okButton);
   buttonsLayout->addWidget(cancelButton);
   layout->addLayout(buttonsLayout,5,0,1,4);
}
References ColorPicker::Gamma, ColorPicker::Hue, m_image, m_imageLab, ColorPicker::Saturation, ColorPicker::setCol(), and updateImage().
TuneColorDialog() [2/2]
TuneColorDialog::TuneColorDialog (int hue, int sat, int gamma, QWidget * parent = 0)
Member Function Documentation
getGamma() [1/2]
int TuneColorDialog::getGamma () const
Definition at line 323 of file wizard.cpp.
{
  return m_gam;
}
References m_gam.
Referenced by Step3::tuneColorDialog().
getGamma() [2/2]
int TuneColorDialog::getGamma () const
getHue() [1/2]
int TuneColorDialog::getHue () const
Definition at line 313 of file wizard.cpp.
{
  return m_hue;
}
References m_hue.
Referenced by Step3::tuneColorDialog().
getHue() [2/2]
int TuneColorDialog::getHue () const
getSaturation() [1/2]
int TuneColorDialog::getSaturation () const
Definition at line 318 of file wizard.cpp.
{
  return m_sat;
}
References m_sat.
Referenced by Step3::tuneColorDialog().
getSaturation() [2/2]
int TuneColorDialog::getSaturation () const
updateImage [1/2]
void TuneColorDialog::updateImage (int hue, int sat, int val) [private], [slot]
Definition at line 294 of file wizard.cpp.
{
  QImage coloredImg(m_image->width(),m_image->height(),QImage::Format_RGB32);
  uint *srcPixel = (uint *)m_image->scanLine(0);
  uint *dstPixel = (uint *)coloredImg.scanLine(0);
  uint nrPixels = coloredImg.width()*coloredImg.height();
  for (uint i=0;i<nrPixels;i++,srcPixel++,dstPixel++)
  {
    QColor c = QColor::fromRgb(*srcPixel);
    double r,g,b;
    hsl2rgb(hue/359.0, sat/255.0, pow(c.green()/255.0,gam/100.0),&r,&g,&b);
    *dstPixel = qRgb((int)(r*255.0),(int)(g*255.0),(int)(b*255.0));
  }
  m_imageLab->setPixmap(QPixmap::fromImage(coloredImg));
  m_hue = hue;
  m_sat = sat;
  m_gam = gam;
}
References b, c, g, hsl2rgb(), m_gam, m_hue, m_image, m_imageLab, m_sat, and r.
Referenced by TuneColorDialog().
updateImage [2/2]
void TuneColorDialog::updateImage (int hue, int sat, int val) [private], [slot]
Member Data Documentation
m_gam
int TuneColorDialog::m_gam = 0 [private]
Definition at line 52 of file wizard.h.
Referenced by getGamma(), and updateImage().
m_hue
int TuneColorDialog::m_hue = 0 [private]
Definition at line 50 of file wizard.h.
Referenced by getHue(), and updateImage().
m_image
QImage * TuneColorDialog::m_image = 0 [private]
Definition at line 48 of file wizard.h.
Referenced by TuneColorDialog(), and updateImage().
m_imageLab
QLabel * TuneColorDialog::m_imageLab = 0 [private]
Definition at line 49 of file wizard.h.
Referenced by TuneColorDialog(), and updateImage().
m_sat
int TuneColorDialog::m_sat = 0 [private]
Definition at line 51 of file wizard.h.
Referenced by getSaturation(), and updateImage().
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/wizard.h
doxygen/build/doxygen/addon/doxywizard/wizard.h
doxygen/addon/doxywizard/wizard.cpp
doxygen/build/doxygen/addon/doxywizard/wizard.cpp