ScopedTypeVariant Class Reference
#include <scopedtypevariant.h>
Public Types
enum Variant {
Global
, Local
, Dummy
, Global
,
Local
, Dummy
 }
possible variant types
enum Variant {
Global
, Local
, Dummy
, Global
,
Local
, Dummy
 }
possible variant types
Public Member Functions
ScopedTypeVariant ()
default constructor for creating a variant of type Dummy
ScopedTypeVariant (const Definition *d)
constructor for creating a variant of type Global
ScopedTypeVariant (const QCString &name)
constructor for creating a variant of type Local
ScopedTypeVariant (const ScopedTypeVariant &stv)
copy constructor
ScopedTypeVariant (ScopedTypeVariant &&stv) noexcept
move constructor
ScopedTypeVariant & operator= (ScopedTypeVariant stv)
assignment operator
~ScopedTypeVariant ()
destructor
void setGlobal (const Definition *def)
Turn the variant into a Global type.
LocalDef * setLocal (const QCString &name)
Turn the variant into a Local type.
void setDummy ()
Turn the variant into a Dummy type.
Variant type () const
QCString name () const
LocalDef * localDef () const
const Definition * globalDef () const
ScopedTypeVariant ()
default constructor for creating a variant of type Dummy
ScopedTypeVariant (const Definition *d)
constructor for creating a variant of type Global
ScopedTypeVariant (const QCString &name)
constructor for creating a variant of type Local
ScopedTypeVariant (const ScopedTypeVariant &stv)
copy constructor
ScopedTypeVariant (ScopedTypeVariant &&stv) noexcept
move constructor
ScopedTypeVariant & operator= (ScopedTypeVariant stv)
assignment operator
~ScopedTypeVariant ()
destructor
void setGlobal (const Definition *def)
Turn the variant into a Global type.
LocalDef * setLocal (const QCString &name)
Turn the variant into a Local type.
void setDummy ()
Turn the variant into a Dummy type.
Variant type () const
QCString name () const
LocalDef * localDef () const
const Definition * globalDef () const
Private Attributes
Variant m_variant
QCString m_name
xx xx xx xx xx xx xx xx xx
union {
 const Definition * globalDef
 LocalDef * localDef
} m_u
xx xx xx xx xx xx xx xx xx
union {
 const Definition * globalDef
 LocalDef * localDef
} m_u
Friends
void swap (ScopedTypeVariant &first, ScopedTypeVariant &second)
swap function
void swap (ScopedTypeVariant &first, ScopedTypeVariant &second)
swap function
Detailed Description
Variant class for a scoped type.
Variants:
Dummy: a type used for hiding a global type.
Local: a locally defined type (e.g. found inside a function)
Global: a globally defined type (processed by doxygen in an earlier pass).
Definition at line 45 of file scopedtypevariant.h.
Member Enumeration Documentation
Variant [1/2]
enum ScopedTypeVariant::Variant
possible variant types
Enumerator
Global
Local
Dummy
Global
Local
Dummy
Definition at line 49 of file scopedtypevariant.h.
    {
      Global,
      Local,
      Dummy
    };
Variant [2/2]
enum ScopedTypeVariant::Variant
possible variant types
Enumerator
Global
Local
Dummy
Global
Local
Dummy
Definition at line 49 of file scopedtypevariant.h.
    {
      Global,
      Local,
      Dummy
    };
Constructor & Destructor Documentation
ScopedTypeVariant() [1/10]
ScopedTypeVariant::ScopedTypeVariant () [inline]
default constructor for creating a variant of type Dummy
Definition at line 56 of file scopedtypevariant.h.
                        : m_variant(Dummy)
    {
      m_u.globalDef = 0;
    }
References m_u.
ScopedTypeVariant() [2/10]
ScopedTypeVariant::ScopedTypeVariant (const Definition * d) [inline], [explicit]
constructor for creating a variant of type Global
Definition at line 61 of file scopedtypevariant.h.
    {
      if (d)
      {
        m_name = d->name();
        m_variant = Global;
        m_u.globalDef = d;
      }
      else
      {
        m_variant = Dummy;
        m_u.globalDef = 0;
      }
    }
References Dummy, Global, m_name, m_u, m_variant, and Definition::name().
ScopedTypeVariant() [3/10]
ScopedTypeVariant::ScopedTypeVariant (const QCString & name) [inline], [explicit]
constructor for creating a variant of type Local
Definition at line 76 of file scopedtypevariant.h.
    {
      m_name = name;
      m_variant = Local;
      m_u.localDef = new LocalDef;
    }
References Local, m_name, m_u, m_variant, and name().
ScopedTypeVariant() [4/10]
ScopedTypeVariant::ScopedTypeVariant (const ScopedTypeVariant & stv) [inline]
copy constructor
Definition at line 83 of file scopedtypevariant.h.
    {
      m_variant = stv.m_variant;
      m_name = stv.m_name;
      if (m_variant==Local)
      {
        m_u.localDef = new LocalDef(*stv.m_u.localDef);
      }
      else if (m_variant==Global)
      {
        m_u.globalDef = stv.m_u.globalDef;
      }
    }
References Global, globalDef, Local, localDef, m_name, m_u, and m_variant.
ScopedTypeVariant() [5/10]
ScopedTypeVariant::ScopedTypeVariant (ScopedTypeVariant && stv) [inline], [noexcept]
move constructor
Definition at line 97 of file scopedtypevariant.h.
                                                        : ScopedTypeVariant()
    {
      swap(*this,stv);
    }
References swap.
 ScopedTypeVariant() [1/2]
ScopedTypeVariant::~ScopedTypeVariant () [inline]
destructor
Definition at line 108 of file scopedtypevariant.h.
    {
      if (m_variant==Local)
      {
        delete m_u.localDef;
      }
    }
References Local, m_u, and m_variant.
ScopedTypeVariant() [6/10]
ScopedTypeVariant::ScopedTypeVariant () [inline]
default constructor for creating a variant of type Dummy
Definition at line 56 of file scopedtypevariant.h.
                        : m_variant(Dummy)
    {
      m_u.globalDef = 0;
    }
References m_u.
ScopedTypeVariant() [7/10]
ScopedTypeVariant::ScopedTypeVariant (const Definition * d) [inline], [explicit]
constructor for creating a variant of type Global
Definition at line 61 of file scopedtypevariant.h.
    {
      if (d)
      {
        m_name = d->name();
        m_variant = Global;
        m_u.globalDef = d;
      }
      else
      {
        m_variant = Dummy;
        m_u.globalDef = 0;
      }
    }
References Dummy, Global, m_name, m_u, m_variant, and Definition::name().
ScopedTypeVariant() [8/10]
ScopedTypeVariant::ScopedTypeVariant (const QCString & name) [inline], [explicit]
constructor for creating a variant of type Local
Definition at line 76 of file scopedtypevariant.h.
    {
      m_name = name;
      m_variant = Local;
      m_u.localDef = new LocalDef;
    }
References Local, m_name, m_u, m_variant, and name().
ScopedTypeVariant() [9/10]
ScopedTypeVariant::ScopedTypeVariant (const ScopedTypeVariant & stv) [inline]
copy constructor
Definition at line 83 of file scopedtypevariant.h.
    {
      m_variant = stv.m_variant;
      m_name = stv.m_name;
      if (m_variant==Local)
      {
        m_u.localDef = new LocalDef(*stv.m_u.localDef);
      }
      else if (m_variant==Global)
      {
        m_u.globalDef = stv.m_u.globalDef;
      }
    }
References Global, globalDef, Local, localDef, m_name, m_u, and m_variant.
ScopedTypeVariant() [10/10]
ScopedTypeVariant::ScopedTypeVariant (ScopedTypeVariant && stv) [inline], [noexcept]
move constructor
Definition at line 97 of file scopedtypevariant.h.
                                                        : ScopedTypeVariant()
    {
      swap(*this,stv);
    }
References swap.
 ScopedTypeVariant() [2/2]
ScopedTypeVariant::~ScopedTypeVariant () [inline]
destructor
Definition at line 108 of file scopedtypevariant.h.
    {
      if (m_variant==Local)
      {
        delete m_u.localDef;
      }
    }
References Local, m_u, and m_variant.
Member Function Documentation
globalDef() [1/2]
const Definition * ScopedTypeVariant::globalDef () const [inline]
Definition at line 160 of file scopedtypevariant.h.
{ return m_variant==Global ? m_u.globalDef : 0; }
References Global, m_u, and m_variant.
globalDef() [2/2]
const Definition * ScopedTypeVariant::globalDef () const [inline]
Definition at line 160 of file scopedtypevariant.h.
{ return m_variant==Global ? m_u.globalDef : 0; }
References Global, m_u, and m_variant.
localDef() [1/2]
LocalDef * ScopedTypeVariant::localDef () const [inline]
Definition at line 159 of file scopedtypevariant.h.
{ return m_variant==Local ? m_u.localDef : 0; }
References Local, m_u, and m_variant.
localDef() [2/2]
LocalDef * ScopedTypeVariant::localDef () const [inline]
Definition at line 159 of file scopedtypevariant.h.
{ return m_variant==Local ? m_u.localDef : 0; }
References Local, m_u, and m_variant.
name() [1/2]
QCString ScopedTypeVariant::name () const [inline]
Definition at line 158 of file scopedtypevariant.h.
{ return m_name; }
References m_name.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), generateClassOrGlobalLink(), generateMemberLink(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), ScopedTypeVariant(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), setCallContextForVar(), setLocal(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
QCString ScopedTypeVariant::name () const [inline]
Definition at line 158 of file scopedtypevariant.h.
{ return m_name; }
References m_name.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
operator=() [1/2]
ScopedTypeVariant & ScopedTypeVariant::operator= (ScopedTypeVariant stv) [inline]
assignment operator
Definition at line 102 of file scopedtypevariant.h.
    {
      swap(*this,stv);
      return *this;
    }
References swap.
operator=() [2/2]
ScopedTypeVariant & ScopedTypeVariant::operator= (ScopedTypeVariant stv) [inline]
assignment operator
Definition at line 102 of file scopedtypevariant.h.
    {
      swap(*this,stv);
      return *this;
    }
References swap.
setDummy() [1/2]
void ScopedTypeVariant::setDummy () [inline]
Turn the variant into a Dummy type.
Definition at line 147 of file scopedtypevariant.h.
    {
      if (m_variant==Local)
      {
        delete m_u.localDef;
      }
      m_variant = Dummy;
      m_name = "";
      m_u.localDef=0;
    }
References Dummy, Local, m_name, m_u, and m_variant.
setDummy() [2/2]
void ScopedTypeVariant::setDummy () [inline]
Turn the variant into a Dummy type.
Definition at line 147 of file scopedtypevariant.h.
    {
      if (m_variant==Local)
      {
        delete m_u.localDef;
      }
      m_variant = Dummy;
      m_name = "";
      m_u.localDef=0;
    }
References Dummy, Local, m_name, m_u, and m_variant.
setGlobal() [1/2]
void ScopedTypeVariant::setGlobal (const Definition * def) [inline]
Turn the variant into a Global type.
Definition at line 124 of file scopedtypevariant.h.
    {
      if (m_variant==Local)
      {
        delete m_u.localDef;
      }
      m_variant = Global;
      m_name = def->name();
      m_u.globalDef = def;
    }
References Global, Local, m_name, m_u, m_variant, and Definition::name().
setGlobal() [2/2]
void ScopedTypeVariant::setGlobal (const Definition * def) [inline]
Turn the variant into a Global type.
Definition at line 124 of file scopedtypevariant.h.
    {
      if (m_variant==Local)
      {
        delete m_u.localDef;
      }
      m_variant = Global;
      m_name = def->name();
      m_u.globalDef = def;
    }
References Global, Local, m_name, m_u, m_variant, and Definition::name().
setLocal() [1/2]
LocalDef * ScopedTypeVariant::setLocal (const QCString & name) [inline]
Turn the variant into a Local type.
Definition at line 135 of file scopedtypevariant.h.
    {
      if (m_variant==Local)
      {
        delete m_u.localDef;
      }
      m_variant = Local;
      m_name = name;
      m_u.localDef = new LocalDef;
      return m_u.localDef;
    }
References Local, m_name, m_u, m_variant, and name().
setLocal() [2/2]
LocalDef * ScopedTypeVariant::setLocal (const QCString & name) [inline]
Turn the variant into a Local type.
Definition at line 135 of file scopedtypevariant.h.
    {
      if (m_variant==Local)
      {
        delete m_u.localDef;
      }
      m_variant = Local;
      m_name = name;
      m_u.localDef = new LocalDef;
      return m_u.localDef;
    }
References Local, m_name, m_u, m_variant, and name().
type() [1/2]
Variant ScopedTypeVariant::type () const [inline]
Definition at line 157 of file scopedtypevariant.h.
{ return m_variant; }
References m_variant.
Referenced by generateClassOrGlobalLink(), generateMemberLink(), and setCallContextForVar().
type() [2/2]
Variant ScopedTypeVariant::type () const [inline]
Definition at line 157 of file scopedtypevariant.h.
{ return m_variant; }
References m_variant.
Friends And Related Function Documentation
swap [1/2]
void swap (ScopedTypeVariant & first, ScopedTypeVariant & second) [friend]
swap function
Definition at line 116 of file scopedtypevariant.h.
    {
      using std::swap; // enable ADL
      swap(first.m_variant,second.m_variant);
      swap(first.m_name,second.m_name);
      swap(first.m_u.globalDef,second.m_u.globalDef);
    }
Referenced by operator=(), and ScopedTypeVariant().
swap [2/2]
void swap (ScopedTypeVariant & first, ScopedTypeVariant & second) [friend]
swap function
Definition at line 116 of file scopedtypevariant.h.
    {
      using std::swap; // enable ADL
      swap(first.m_variant,second.m_variant);
      swap(first.m_name,second.m_name);
      swap(first.m_u.globalDef,second.m_u.globalDef);
    }
Member Data Documentation
globalDef
const Definition* ScopedTypeVariant::globalDef
Definition at line 167 of file scopedtypevariant.h.
Referenced by ScopedTypeVariant(), and writeObjCMethodCall().
localDef
LocalDef* ScopedTypeVariant::localDef
Definition at line 168 of file scopedtypevariant.h.
Referenced by generateFunctionLink(), generateMemberLink(), and ScopedTypeVariant().
m_name
QCString ScopedTypeVariant::m_name [private]
Definition at line 164 of file scopedtypevariant.h.
Referenced by name(), ScopedTypeVariant(), setDummy(), setGlobal(), and setLocal().
 [1/2]
union { ... } ScopedTypeVariant::m_u [private]
Referenced by globalDef(), localDef(), ScopedTypeVariant(), setDummy(), setGlobal(), setLocal(), and ~ScopedTypeVariant().
 [2/2]
union { ... } ScopedTypeVariant::m_u [private]
m_variant
Variant ScopedTypeVariant::m_variant [private]
Definition at line 163 of file scopedtypevariant.h.
Referenced by globalDef(), localDef(), ScopedTypeVariant(), setDummy(), setGlobal(), setLocal(), type(), and ~ScopedTypeVariant().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/scopedtypevariant.h
doxygen/src/scopedtypevariant.h