ArgumentList Class Reference
This class represents an function or template argument list.
#include <arguments.h>
Public Types
using Vec = std::vector< Argument >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
using Vec = std::vector< Argument >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
Public Member Functions
bool hasDocumentation () const
bool hasParameters () const
void reset ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
bool empty () const
size_t size () const
void clear ()
void push_back (const Argument &a)
Argument & back ()
const Argument & back () const
Argument & front ()
const Argument & front () const
Argument & at (size_t i)
const Argument & at (size_t i) const
bool constSpecifier () const
bool volatileSpecifier () const
bool pureSpecifier () const
QCString trailingReturnType () const
bool isDeleted () const
RefQualifierType refQualifier () const
bool noParameters () const
void setConstSpecifier (bool b)
void setVolatileSpecifier (bool b)
void setPureSpecifier (bool b)
void setTrailingReturnType (const QCString &s)
void setIsDeleted (bool b)
void setRefQualifier (RefQualifierType t)
void setNoParameters (bool b)
bool hasDocumentation () const
bool hasParameters () const
void reset ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
bool empty () const
size_t size () const
void clear ()
void push_back (const Argument &a)
Argument & back ()
const Argument & back () const
Argument & front ()
const Argument & front () const
Argument & at (size_t i)
const Argument & at (size_t i) const
bool constSpecifier () const
bool volatileSpecifier () const
bool pureSpecifier () const
QCString trailingReturnType () const
bool isDeleted () const
RefQualifierType refQualifier () const
bool noParameters () const
void setConstSpecifier (bool b)
void setVolatileSpecifier (bool b)
void setPureSpecifier (bool b)
void setTrailingReturnType (const QCString &s)
void setIsDeleted (bool b)
void setRefQualifier (RefQualifierType t)
void setNoParameters (bool b)
Private Attributes
std::vector< Argument > m_args
bool m_constSpecifier = FALSE
bool m_volatileSpecifier = FALSE
bool m_pureSpecifier = FALSE
QCString m_trailingReturnType
bool m_isDeleted = FALSE
RefQualifierType m_refQualifier = RefQualifierNone
bool m_noParameters = FALSE
Detailed Description
This class represents an function or template argument list.
This class also stores some information about member that is typically put after the argument list, such as whether the member is const, volatile or pure virtual.
Definition at line 59 of file arguments.h.
Member Typedef Documentation
const_iterator [1/2]
using ArgumentList::const_iterator = typename Vec::const_iterator
Definition at line 64 of file arguments.h.
const_iterator [2/2]
using ArgumentList::const_iterator = typename Vec::const_iterator
Definition at line 64 of file arguments.h.
iterator [1/2]
using ArgumentList::iterator = typename Vec::iterator
Definition at line 63 of file arguments.h.
iterator [2/2]
using ArgumentList::iterator = typename Vec::iterator
Definition at line 63 of file arguments.h.
Vec [1/2]
using ArgumentList::Vec = std::vector<Argument>
Definition at line 62 of file arguments.h.
Vec [2/2]
using ArgumentList::Vec = std::vector<Argument>
Definition at line 62 of file arguments.h.
Member Function Documentation
at() [1/4]
Argument & ArgumentList::at (size_t i) [inline]
Definition at line 100 of file arguments.h.
{ return m_args.at(i); }
References m_args.
Referenced by makeQualifiedNameWithTemplateParameters().
at() [2/4]
Argument & ArgumentList::at (size_t i) [inline]
Definition at line 100 of file arguments.h.
{ return m_args.at(i); }
References m_args.
at() [3/4]
const Argument & ArgumentList::at (size_t i) const [inline]
Definition at line 101 of file arguments.h.
{ return m_args.at(i); }
References m_args.
at() [4/4]
const Argument & ArgumentList::at (size_t i) const [inline]
Definition at line 101 of file arguments.h.
{ return m_args.at(i); }
References m_args.
back() [1/4]
Argument & ArgumentList::back () [inline]
Definition at line 96 of file arguments.h.
{ return m_args.back(); }
References m_args.
back() [2/4]
Argument & ArgumentList::back () [inline]
Definition at line 96 of file arguments.h.
{ return m_args.back(); }
References m_args.
back() [3/4]
const Argument & ArgumentList::back () const [inline]
Definition at line 97 of file arguments.h.
{ return m_args.back(); }
References m_args.
back() [4/4]
const Argument & ArgumentList::back () const [inline]
Definition at line 97 of file arguments.h.
{ return m_args.back(); }
References m_args.
begin() [1/4]
iterator ArgumentList::begin () [inline]
Definition at line 86 of file arguments.h.
{ return m_args.begin(); }
References m_args.
Referenced by MemberDefImpl::_writeTemplatePrefix(), argListToString(), MemberDefImpl::copyArgumentNames(), MemberDefImpl::detectUndocumentedParams(), functionSignature(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), hasDocumentation(), matchArguments2(), mergeArguments(), MemberDefImpl::resolveUnnamedParameters(), substituteTemplateArgumentsInString(), substituteTemplatesInString(), transferArgumentDocumentation(), and writeDefArgumentList().
begin() [2/4]
iterator ArgumentList::begin () [inline]
Definition at line 86 of file arguments.h.
{ return m_args.begin(); }
References m_args.
begin() [3/4]
const_iterator ArgumentList::begin () const [inline]
Definition at line 88 of file arguments.h.
{ return m_args.cbegin(); }
References m_args.
begin() [4/4]
const_iterator ArgumentList::begin () const [inline]
Definition at line 88 of file arguments.h.
{ return m_args.cbegin(); }
References m_args.
cbegin() [1/2]
const_iterator ArgumentList::cbegin () const [inline]
Definition at line 90 of file arguments.h.
{ return m_args.cbegin(); }
References m_args.
cbegin() [2/2]
const_iterator ArgumentList::cbegin () const [inline]
Definition at line 90 of file arguments.h.
{ return m_args.cbegin(); }
References m_args.
cend() [1/2]
const_iterator ArgumentList::cend () const [inline]
Definition at line 91 of file arguments.h.
{ return m_args.cend(); }
References m_args.
cend() [2/2]
const_iterator ArgumentList::cend () const [inline]
Definition at line 91 of file arguments.h.
{ return m_args.cend(); }
References m_args.
clear() [1/2]
void ArgumentList::clear () [inline]
Definition at line 94 of file arguments.h.
{ m_args.clear(); }
References m_args.
Referenced by reset().
clear() [2/2]
void ArgumentList::clear () [inline]
Definition at line 94 of file arguments.h.
{ m_args.clear(); }
References m_args.
constSpecifier() [1/2]
bool ArgumentList::constSpecifier () const [inline]
Definition at line 104 of file arguments.h.
{ return m_constSpecifier; }
References m_constSpecifier.
Referenced by argListToString(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), MemberContext::Private::hasConstQualifier(), matchArguments2(), and writeDefArgumentList().
constSpecifier() [2/2]
bool ArgumentList::constSpecifier () const [inline]
Definition at line 104 of file arguments.h.
{ return m_constSpecifier; }
References m_constSpecifier.
empty() [1/2]
bool ArgumentList::empty () const [inline]
Definition at line 92 of file arguments.h.
{ return m_args.empty(); }
References m_args.
Referenced by addClassToContext(), addMemberFunction(), ClassContext::Private::addTemplateDecls(), DocParser::checkArgumentName(), checkOverrideArg(), DocParser::checkUnOrMultipleDocumentedParams(), computeTemplateClassRelations(), MemberContext::Private::createTemplateArgs(), MemberContext::Private::createTemplateDecls(), ConceptContext::Private::createTemplateDecls(), MemberDefImpl::createTemplateInstanceMember(), ClassContext::Private::createTypeConstraints(), MemberContext::Private::createTypeConstraints(), MemberDefImpl::detectUndocumentedParams(), findGlobalMember(), functionInformation(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), getTemplateArgumentsFromName(), hasParameters(), MemberContext::Private::hasParameters(), insertTemplateSpecifierInScope(), MemberDefImpl::isBriefSectionVisible(), ClassDefImpl::isTemplate(), isVarWithConstructor(), makeQualifiedNameWithTemplateParameters(), matchArguments2(), searchTemplateSpecs(), substituteTemplateArgumentsInString(), tempArgListToString(), ClassDefImpl::title(), MemberDefImpl::writeDeclaration(), MemberDefImpl::writeDocumentation(), and writeTypeConstraints().
empty() [2/2]
bool ArgumentList::empty () const [inline]
Definition at line 92 of file arguments.h.
{ return m_args.empty(); }
References m_args.
end() [1/4]
iterator ArgumentList::end () [inline]
Definition at line 87 of file arguments.h.
{ return m_args.end(); }
References m_args.
Referenced by MemberDefImpl::_writeTemplatePrefix(), argListToString(), MemberDefImpl::copyArgumentNames(), MemberDefImpl::detectUndocumentedParams(), functionSignature(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), hasDocumentation(), matchArguments2(), mergeArguments(), MemberDefImpl::resolveUnnamedParameters(), substituteTemplateArgumentsInString(), substituteTemplatesInString(), transferArgumentDocumentation(), and writeDefArgumentList().
end() [2/4]
iterator ArgumentList::end () [inline]
Definition at line 87 of file arguments.h.
{ return m_args.end(); }
References m_args.
end() [3/4]
const_iterator ArgumentList::end () const [inline]
Definition at line 89 of file arguments.h.
{ return m_args.cend(); }
References m_args.
end() [4/4]
const_iterator ArgumentList::end () const [inline]
Definition at line 89 of file arguments.h.
{ return m_args.cend(); }
References m_args.
front() [1/4]
Argument & ArgumentList::front () [inline]
Definition at line 98 of file arguments.h.
{ return m_args.front(); }
References m_args.
Referenced by functionInformation(), MemberDefImpl::isBriefSectionVisible(), and matchArguments2().
front() [2/4]
Argument & ArgumentList::front () [inline]
Definition at line 98 of file arguments.h.
{ return m_args.front(); }
References m_args.
front() [3/4]
const Argument & ArgumentList::front () const [inline]
Definition at line 99 of file arguments.h.
{ return m_args.front(); }
References m_args.
front() [4/4]
const Argument & ArgumentList::front () const [inline]
Definition at line 99 of file arguments.h.
{ return m_args.front(); }
References m_args.
hasDocumentation() [1/2]
bool ArgumentList::hasDocumentation () const
Does any argument of this list have documentation?
the argument list is documented if one of its arguments is documented
Definition at line 21 of file arguments.cpp.
{
  return std::any_of(begin(),end(),[](const Argument &a){ return a.hasDocumentation(); });
}
References a, begin(), and end().
Referenced by MemberContext::Private::createParamDocs(), MemberDefImpl::hasDetailedDescription(), MemberDefImpl::hasDocumentation(), and MemberDefImpl::writeDocumentation().
hasDocumentation() [2/2]
bool ArgumentList::hasDocumentation () const
Does any argument of this list have documentation?
hasParameters() [1/2]
bool ArgumentList::hasParameters () const [inline]
Does this list have zero or more parameters
Definition at line 69 of file arguments.h.
    {
      return !empty() || m_noParameters;
    }
References empty(), and m_noParameters.
Referenced by MemberDefImpl::_writeTypeConstraints(), addMemberFunction(), addTemplateArgumentList(), argListToString(), combineDeclarationAndDefinition(), MemberDefImpl::detectUndocumentedParams(), generateXMLForMember(), MemberDefImpl::hasDetailedDescription(), MemberDefImpl::setAnchor(), MemberDefImpl::writeDeclaration(), writeDefArgumentList(), MemberDefImpl::writeDocumentation(), VhdlDocGen::writeFunctionProto(), VhdlDocGen::writeProcessProto(), writeTemplateArgumentList(), and VhdlDocGen::writeVHDLDeclaration().
hasParameters() [2/2]
bool ArgumentList::hasParameters () const [inline]
Does this list have zero or more parameters
Definition at line 69 of file arguments.h.
    {
      return !empty() || m_noParameters;
    }
References empty(), and m_noParameters.
isDeleted() [1/2]
bool ArgumentList::isDeleted () const [inline]
Definition at line 108 of file arguments.h.
{ return m_isDeleted; }
References m_isDeleted.
Referenced by MemberDefImpl::isDeleted().
isDeleted() [2/2]
bool ArgumentList::isDeleted () const [inline]
Definition at line 108 of file arguments.h.
{ return m_isDeleted; }
References m_isDeleted.
noParameters() [1/2]
bool ArgumentList::noParameters () const [inline]
Definition at line 110 of file arguments.h.
{ return m_noParameters; }
References m_noParameters.
noParameters() [2/2]
bool ArgumentList::noParameters () const [inline]
Definition at line 110 of file arguments.h.
{ return m_noParameters; }
References m_noParameters.
pureSpecifier() [1/2]
bool ArgumentList::pureSpecifier () const [inline]
Definition at line 106 of file arguments.h.
{ return m_pureSpecifier; }
References m_pureSpecifier.
Referenced by argListToString().
pureSpecifier() [2/2]
bool ArgumentList::pureSpecifier () const [inline]
Definition at line 106 of file arguments.h.
{ return m_pureSpecifier; }
References m_pureSpecifier.
push_back() [1/2]
void ArgumentList::push_back (const Argument & a) [inline]
Definition at line 95 of file arguments.h.
{ m_args.push_back(a); }
References a, and m_args.
Referenced by addMemberFunction(), addSTLClass(), and DocParser::checkUnOrMultipleDocumentedParams().
push_back() [2/2]
void ArgumentList::push_back (const Argument & a) [inline]
Definition at line 95 of file arguments.h.
{ m_args.push_back(a); }
References a, and m_args.
refQualifier() [1/2]
RefQualifierType ArgumentList::refQualifier () const [inline]
Definition at line 109 of file arguments.h.
{ return m_refQualifier; }
References m_refQualifier.
Referenced by argListToString(), generateXMLForMember(), MemberContext::Private::hasRefQualifierLValue(), MemberContext::Private::hasRefQualifierRValue(), matchArguments2(), and writeDefArgumentList().
refQualifier() [2/2]
RefQualifierType ArgumentList::refQualifier () const [inline]
Definition at line 109 of file arguments.h.
{ return m_refQualifier; }
References m_refQualifier.
reset() [1/2]
void ArgumentList::reset () [inline]
Definition at line 73 of file arguments.h.
    {
      clear();
      m_constSpecifier = FALSE;
      m_volatileSpecifier = FALSE;
      m_pureSpecifier = FALSE;
      m_trailingReturnType.resize(0);
      m_isDeleted = FALSE;
      m_refQualifier = RefQualifierNone;
      m_noParameters = FALSE;
    }
References clear(), FALSE, m_constSpecifier, m_isDeleted, m_noParameters, m_pureSpecifier, m_refQualifier, m_trailingReturnType, m_volatileSpecifier, RefQualifierNone, and QCString::resize().
Referenced by Entry::reset().
reset() [2/2]
void ArgumentList::reset () [inline]
Definition at line 73 of file arguments.h.
    {
      clear();
      m_constSpecifier = FALSE;
      m_volatileSpecifier = FALSE;
      m_pureSpecifier = FALSE;
      m_trailingReturnType.resize(0);
      m_isDeleted = FALSE;
      m_refQualifier = RefQualifierNone;
      m_noParameters = FALSE;
    }
References clear(), FALSE, m_constSpecifier, m_isDeleted, m_noParameters, m_pureSpecifier, m_refQualifier, m_trailingReturnType, m_volatileSpecifier, RefQualifierNone, and QCString::resize().
setConstSpecifier() [1/2]
void ArgumentList::setConstSpecifier (bool b) [inline]
Definition at line 112 of file arguments.h.
{ m_constSpecifier = b; }
References b, and m_constSpecifier.
setConstSpecifier() [2/2]
void ArgumentList::setConstSpecifier (bool b) [inline]
Definition at line 112 of file arguments.h.
{ m_constSpecifier = b; }
References b, and m_constSpecifier.
setIsDeleted() [1/2]
void ArgumentList::setIsDeleted (bool b) [inline]
Definition at line 116 of file arguments.h.
{ m_isDeleted = b; }
References b, and m_isDeleted.
setIsDeleted() [2/2]
void ArgumentList::setIsDeleted (bool b) [inline]
Definition at line 116 of file arguments.h.
{ m_isDeleted = b; }
References b, and m_isDeleted.
setNoParameters() [1/2]
void ArgumentList::setNoParameters (bool b) [inline]
Definition at line 118 of file arguments.h.
{ m_noParameters = b; }
References b, and m_noParameters.
setNoParameters() [2/2]
void ArgumentList::setNoParameters (bool b) [inline]
Definition at line 118 of file arguments.h.
{ m_noParameters = b; }
References b, and m_noParameters.
setPureSpecifier() [1/2]
void ArgumentList::setPureSpecifier (bool b) [inline]
Definition at line 114 of file arguments.h.
{ m_pureSpecifier = b; }
References b, and m_pureSpecifier.
setPureSpecifier() [2/2]
void ArgumentList::setPureSpecifier (bool b) [inline]
Definition at line 114 of file arguments.h.
{ m_pureSpecifier = b; }
References b, and m_pureSpecifier.
setRefQualifier() [1/2]
void ArgumentList::setRefQualifier (RefQualifierType t) [inline]
Definition at line 117 of file arguments.h.
{ m_refQualifier = t; }
References m_refQualifier.
setRefQualifier() [2/2]
void ArgumentList::setRefQualifier (RefQualifierType t) [inline]
Definition at line 117 of file arguments.h.
{ m_refQualifier = t; }
References m_refQualifier.
setTrailingReturnType() [1/2]
void ArgumentList::setTrailingReturnType (const QCString & s) [inline]
Definition at line 115 of file arguments.h.
{ m_trailingReturnType = s; }
References m_trailingReturnType, and s.
setTrailingReturnType() [2/2]
void ArgumentList::setTrailingReturnType (const QCString & s) [inline]
Definition at line 115 of file arguments.h.
{ m_trailingReturnType = s; }
References m_trailingReturnType, and s.
setVolatileSpecifier() [1/2]
void ArgumentList::setVolatileSpecifier (bool b) [inline]
Definition at line 113 of file arguments.h.
{ m_volatileSpecifier = b; }
References b, and m_volatileSpecifier.
setVolatileSpecifier() [2/2]
void ArgumentList::setVolatileSpecifier (bool b) [inline]
Definition at line 113 of file arguments.h.
{ m_volatileSpecifier = b; }
References b, and m_volatileSpecifier.
size() [1/2]
size_t ArgumentList::size () const [inline]
Definition at line 93 of file arguments.h.
{ return m_args.size(); }
References m_args.
Referenced by addMemberFunction(), FlowChart::alignFuncProc(), DocParser::checkUnOrMultipleDocumentedParams(), combineDeclarationAndDefinition(), findGlobalMember(), functionInformation(), GroupDefImpl::insertMember(), matchArguments2(), mergeArguments(), prototypeInformation(), MemberDefImpl::setAnchor(), writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), VhdlDocGen::writeFunctionProto(), and VhdlDocGen::writeProcedureProto().
size() [2/2]
size_t ArgumentList::size () const [inline]
Definition at line 93 of file arguments.h.
{ return m_args.size(); }
References m_args.
trailingReturnType() [1/2]
QCString ArgumentList::trailingReturnType () const [inline]
Definition at line 107 of file arguments.h.
{ return m_trailingReturnType; }
References m_trailingReturnType.
Referenced by argListToString(), MemberContext::Private::createTrailingReturnType(), MemberDefImpl::warnIfUndocumentedParams(), and writeDefArgumentList().
trailingReturnType() [2/2]
QCString ArgumentList::trailingReturnType () const [inline]
Definition at line 107 of file arguments.h.
{ return m_trailingReturnType; }
References m_trailingReturnType.
volatileSpecifier() [1/2]
bool ArgumentList::volatileSpecifier () const [inline]
Definition at line 105 of file arguments.h.
{ return m_volatileSpecifier; }
References m_volatileSpecifier.
Referenced by argListToString(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), MemberContext::Private::hasVolatileQualifier(), matchArguments2(), and writeDefArgumentList().
volatileSpecifier() [2/2]
bool ArgumentList::volatileSpecifier () const [inline]
Definition at line 105 of file arguments.h.
{ return m_volatileSpecifier; }
References m_volatileSpecifier.
Member Data Documentation
m_args
std::vector< Argument > ArgumentList::m_args [private]
Definition at line 121 of file arguments.h.
Referenced by at(), back(), begin(), cbegin(), cend(), clear(), empty(), end(), front(), push_back(), and size().
m_constSpecifier
bool ArgumentList::m_constSpecifier = FALSE [private]
Does the member modify the state of the class?
Definition at line 123 of file arguments.h.
Referenced by constSpecifier(), reset(), and setConstSpecifier().
m_isDeleted
bool ArgumentList::m_isDeleted = FALSE [private]
method with =delete
Definition at line 131 of file arguments.h.
Referenced by isDeleted(), reset(), and setIsDeleted().
m_noParameters
bool ArgumentList::m_noParameters = FALSE [private]
is it an explicit empty list
Definition at line 135 of file arguments.h.
Referenced by hasParameters(), noParameters(), reset(), and setNoParameters().
m_pureSpecifier
bool ArgumentList::m_pureSpecifier = FALSE [private]
Is this a pure virtual member?
Definition at line 127 of file arguments.h.
Referenced by pureSpecifier(), reset(), and setPureSpecifier().
m_refQualifier
RefQualifierType ArgumentList::m_refQualifier = RefQualifierNone [private]
C++11 ref qualifier
Definition at line 133 of file arguments.h.
Referenced by refQualifier(), reset(), and setRefQualifier().
m_trailingReturnType
QCString ArgumentList::m_trailingReturnType [private]
C++11 style Trailing return type?
Definition at line 129 of file arguments.h.
Referenced by reset(), setTrailingReturnType(), and trailingReturnType().
m_volatileSpecifier
bool ArgumentList::m_volatileSpecifier = FALSE [private]
Is the member volatile?
Definition at line 125 of file arguments.h.
Referenced by reset(), setVolatileSpecifier(), and volatileSpecifier().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/arguments.h
doxygen/src/arguments.h
doxygen/build/doxygen/src/arguments.cpp
doxygen/src/arguments.cpp