InputBool Class Reference
#include <inputbool.h>
Public Slots
void reset ()
void setValue (bool)
void reset ()
void setValue (bool)
Signals
void changed ()
void toggle (QString, bool)
void showHelp (Input *)
void changed ()
void toggle (QString, bool)
void showHelp (Input *)
Public Member Functions
InputBool (QGridLayout *layout, int &row, const QString &id, bool enabled, const QString &docs)
QVariant & value ()
void update ()
Kind kind () const
QString docs () const
QString id () const
QString templateDocs () const
void addDependency (Input *option)
void setEnabled (bool)
void updateDependencies ()
bool isDefault ()
void writeValue (QTextStream &t, TextCodecAdapter *codec)
void setTemplateDocs (const QString &docs)
InputBool (QGridLayout *layout, int &row, const QString &id, bool enabled, const QString &docs)
QVariant & value ()
void update ()
Kind kind () const
QString docs () const
QString id () const
QString templateDocs () const
void addDependency (Input *option)
void setEnabled (bool)
void updateDependencies ()
bool isDefault ()
void writeValue (QTextStream &t, TextCodecAdapter *codec)
void setTemplateDocs (const QString &docs)
Static Public Member Functions
static bool convertToBool (const QVariant &v, bool &isValid)
static bool convertToBool (const QVariant &v, bool &isValid)
Private Slots
void help ()
void help ()
Private Member Functions
void updateDefault ()
void updateDefault ()
Private Attributes
bool m_state
bool m_default
bool m_enabled
QVariant m_value
QCheckBox * m_cb
QString m_docs
QList< Input * > m_dependencies
QString m_id
QLabel * m_lab
QString m_tdocs
Additional Inherited Members
Detailed Description
Definition at line 23 of file inputbool.h.
Constructor & Destructor Documentation
InputBool() [1/2]
InputBool::InputBool (QGridLayout * layout, int & row, const QString & id, bool enabled, const QString & docs)
Definition at line 21 of file inputbool.cpp.
  : m_default(checked), m_docs(docs), m_id(id)
{
  m_lab = new HelpLabel(id);
  m_cb = new QCheckBox;
  layout->addWidget(m_lab,row, 0);
  layout->addWidget(m_cb,row, 1);
  m_enabled = true;
  m_state=!checked; // force update
  setValue(checked);
  connect(m_cb, SIGNAL(toggled(bool)), SLOT(setValue(bool)));
  connect(m_lab, SIGNAL(enter()), SLOT(help()));
  connect(m_lab, SIGNAL(reset()), SLOT(reset()));
  row++;
}
References help(), m_cb, m_enabled, m_lab, m_state, reset(), and setValue().
InputBool() [2/2]
InputBool::InputBool (QGridLayout * layout, int & row, const QString & id, bool enabled, const QString & docs)
Member Function Documentation
addDependency() [1/2]
void InputBool::addDependency (Input * option) [inline], [virtual]
Implements Input.
Definition at line 38 of file inputbool.h.
{ m_dependencies+=option; }
References m_dependencies.
addDependency() [2/2]
void InputBool::addDependency (Input * option) [inline], [virtual]
Implements Input.
Definition at line 38 of file inputbool.h.
{ m_dependencies+=option; }
References m_dependencies.
changed [1/2]
void InputBool::changed () [signal]
Referenced by setValue().
changed [2/2]
void InputBool::changed () [signal]
convertToBool() [1/2]
bool InputBool::convertToBool (const QVariant & v, bool & isValid) [static]
Definition at line 91 of file inputbool.cpp.
{
  QString v = value.toString().toLower();
  if (v==QString::fromLatin1("yes") || v==QString::fromLatin1("true") ||
      v==QString::fromLatin1("1") || v==QString::fromLatin1("all"))
  {
    isValid = true;
    return true;
  }
  else if (v==QString::fromLatin1("no") || v==QString::fromLatin1("false") ||
           v==QString::fromLatin1("0") || v==QString::fromLatin1("none"))
  {
    isValid = true;
    return false;
  }
  else
  {
    isValid = false;
    return false;
  }
}
References value().
Referenced by update(), and upgradeConfig().
convertToBool() [2/2]
static bool InputBool::convertToBool (const QVariant & v, bool & isValid) [static]
docs() [1/2]
QString InputBool::docs () const [inline], [virtual]
Implements Input.
Definition at line 35 of file inputbool.h.
{ return m_docs; }
References m_docs.
Referenced by setTemplateDocs().
docs() [2/2]
QString InputBool::docs () const [inline], [virtual]
Implements Input.
Definition at line 35 of file inputbool.h.
{ return m_docs; }
References m_docs.
help [1/2]
void InputBool::help () [private], [slot]
Definition at line 39 of file inputbool.cpp.
{
  showHelp(this);
}
References showHelp().
Referenced by InputBool().
help [2/2]
void InputBool::help () [private], [slot]
id() [1/2]
QString InputBool::id () const [inline], [virtual]
Implements Input.
Definition at line 36 of file inputbool.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
QString InputBool::id () const [inline], [virtual]
Implements Input.
Definition at line 36 of file inputbool.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
isDefault() [1/2]
bool InputBool::isDefault () [virtual]
Implements Input.
Definition at line 145 of file inputbool.cpp.
{
  return m_state == m_default;
}
References m_default, and m_state.
isDefault() [2/2]
bool InputBool::isDefault () [virtual]
Implements Input.
kind() [1/2]
Kind InputBool::kind () const [inline], [virtual]
Implements Input.
Definition at line 34 of file inputbool.h.
{ return Bool; }
References Input::Bool.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
kind() [2/2]
Kind InputBool::kind () const [inline], [virtual]
Implements Input.
Definition at line 34 of file inputbool.h.
{ return Bool; }
References Input::Bool.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
reset [1/2]
void InputBool::reset () [slot]
Definition at line 132 of file inputbool.cpp.
{
  setValue(m_default);
}
References m_default, and setValue().
Referenced by InputBool().
reset [2/2]
void InputBool::reset () [slot]
setEnabled() [1/2]
void InputBool::setEnabled (bool b) [virtual]
Implements Input.
Definition at line 44 of file inputbool.cpp.
{
  m_enabled = b;
  m_cb->setEnabled(b);
  m_lab->setEnabled(b);
  updateDefault();
  updateDependencies();
}
References b, m_cb, m_enabled, m_lab, updateDefault(), and updateDependencies().
setEnabled() [2/2]
void InputBool::setEnabled (bool) [virtual]
Implements Input.
setTemplateDocs() [1/2]
void InputBool::setTemplateDocs (const QString & docs) [inline], [virtual]
Implements Input.
Definition at line 43 of file inputbool.h.
{ m_tdocs = docs; }
References docs(), and m_tdocs.
setTemplateDocs() [2/2]
void InputBool::setTemplateDocs (const QString & docs) [inline], [virtual]
Implements Input.
Definition at line 43 of file inputbool.h.
{ m_tdocs = docs; }
References docs(), and m_tdocs.
setValue [1/2]
void InputBool::setValue (bool s) [slot]
Definition at line 61 of file inputbool.cpp.
{
  if (m_state!=s)
  {
    m_state=s;
    updateDefault();
    updateDependencies();
    m_cb->setChecked(s);
    m_value = m_state;
    emit changed();
  }
}
References changed(), m_cb, m_state, m_value, s, updateDefault(), and updateDependencies().
Referenced by InputBool(), and reset().
setValue [2/2]
void InputBool::setValue (bool) [slot]
showHelp [1/2]
void InputBool::showHelp (Input *) [signal]
Referenced by help().
showHelp [2/2]
void InputBool::showHelp (Input *) [signal]
templateDocs() [1/2]
QString InputBool::templateDocs () const [inline], [virtual]
Implements Input.
Definition at line 37 of file inputbool.h.
{ return m_tdocs; }
References m_tdocs.
templateDocs() [2/2]
QString InputBool::templateDocs () const [inline], [virtual]
Implements Input.
Definition at line 37 of file inputbool.h.
{ return m_tdocs; }
References m_tdocs.
toggle [1/2]
void InputBool::toggle (QString , bool) [signal]
toggle [2/2]
void InputBool::toggle (QString , bool) [signal]
update() [1/2]
void InputBool::update () [virtual]
Implements Input.
Definition at line 113 of file inputbool.cpp.
{
  bool isValid=false;
  bool b = convertToBool(m_value,isValid);
  if (isValid)
  {
    m_state = b;
  }
  else
  {
    config_warn("argument '%s' for option %s is not a valid boolean value."
                " Using the default: %s!",qPrintable(m_value.toString()),qPrintable(m_id),m_default?"YES":"NO");
    m_state = m_default;
  }
  m_cb->setChecked(m_state);
  updateDefault();
  updateDependencies();
}
References b, config_warn(), convertToBool(), m_cb, m_default, m_id, m_state, m_value, updateDefault(), and updateDependencies().
Referenced by runtests.Tester::__init__(), and runtests.Tester::run().
update() [2/2]
void InputBool::update () [virtual]
Implements Input.
Referenced by runtests.Tester::__init__(), and runtests.Tester::run().
updateDefault() [1/2]
void InputBool::updateDefault () [private]
Definition at line 74 of file inputbool.cpp.
{
  if (m_state==m_default || !m_lab->isEnabled())
  {
    m_lab->setText(QString::fromLatin1("<qt>")+m_id+QString::fromLatin1("</qt>"));
  }
  else
  {
    m_lab->setText(QString::fromLatin1("<qt><font color='red'>")+m_id+QString::fromLatin1("</font></qt>"));
  }
}
References m_default, m_id, m_lab, and m_state.
Referenced by setEnabled(), setValue(), and update().
updateDefault() [2/2]
void InputBool::updateDefault () [private]
updateDependencies() [1/2]
void InputBool::updateDependencies () [virtual]
Implements Input.
Definition at line 53 of file inputbool.cpp.
{
  for (int i=0;i<m_dependencies.count();i++)
  {
    m_dependencies[i]->setEnabled(m_enabled && m_state);
  }
}
References m_dependencies, m_enabled, and m_state.
Referenced by setEnabled(), setValue(), and update().
updateDependencies() [2/2]
void InputBool::updateDependencies () [virtual]
Implements Input.
value() [1/2]
QVariant & InputBool::value () [virtual]
Implements Input.
Definition at line 86 of file inputbool.cpp.
{
  return m_value;
}
References m_value.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), convertToBool(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), doxmlparser.index.MixedContainer::to_etree_simple(), and upgradeConfig().
value() [2/2]
QVariant & InputBool::value () [virtual]
Implements Input.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), and doxmlparser.index.MixedContainer::to_etree_simple().
writeValue() [1/2]
void InputBool::writeValue (QTextStream & t, TextCodecAdapter * codec) [virtual]
Implements Input.
Definition at line 137 of file inputbool.cpp.
{
  if (m_state)
    t << codec->encode(QString::fromLatin1("YES"));
  else
    t << codec->encode(QString::fromLatin1("NO"));
}
References TextCodecAdapter::encode(), and m_state.
writeValue() [2/2]
void InputBool::writeValue (QTextStream & t, TextCodecAdapter * codec) [virtual]
Implements Input.
Member Data Documentation
m_cb
QCheckBox * InputBool::m_cb [private]
Definition at line 64 of file inputbool.h.
Referenced by InputBool(), setEnabled(), setValue(), and update().
m_default
bool InputBool::m_default [private]
Definition at line 61 of file inputbool.h.
Referenced by isDefault(), reset(), update(), and updateDefault().
m_dependencies
QList< Input * > InputBool::m_dependencies [private]
Definition at line 66 of file inputbool.h.
Referenced by addDependency(), and updateDependencies().
m_docs
QString InputBool::m_docs [private]
Definition at line 65 of file inputbool.h.
Referenced by docs().
m_enabled
bool InputBool::m_enabled [private]
Definition at line 62 of file inputbool.h.
Referenced by InputBool(), setEnabled(), and updateDependencies().
m_id
QString InputBool::m_id [private]
Definition at line 67 of file inputbool.h.
Referenced by id(), update(), and updateDefault().
m_lab
QLabel * InputBool::m_lab [private]
Definition at line 68 of file inputbool.h.
Referenced by InputBool(), setEnabled(), and updateDefault().
m_state
bool InputBool::m_state [private]
Definition at line 60 of file inputbool.h.
Referenced by InputBool(), isDefault(), setValue(), update(), updateDefault(), updateDependencies(), and writeValue().
m_tdocs
QString InputBool::m_tdocs [private]
Definition at line 69 of file inputbool.h.
Referenced by setTemplateDocs(), and templateDocs().
m_value
QVariant InputBool::m_value [private]
Definition at line 63 of file inputbool.h.
Referenced by setValue(), update(), and value().
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/inputbool.h
doxygen/build/doxygen/addon/doxywizard/inputbool.h
doxygen/addon/doxywizard/inputbool.cpp
doxygen/build/doxygen/addon/doxywizard/inputbool.cpp