InputInt Class Reference
#include <inputint.h>
Public Slots
void reset ()
void setValue (int val)
void reset ()
void setValue (int val)
Signals
void changed ()
void showHelp (Input *)
void changed ()
void showHelp (Input *)
Public Member Functions
InputInt (QGridLayout *layout, int &row, const QString &id, int defVal, int minVal, int maxVal, const QString &docs)
~InputInt ()=default
QVariant & value ()
void update ()
Kind kind () const
QString docs () const
QString id () const
QString templateDocs () const
void addDependency (Input *)
void setEnabled (bool)
void updateDependencies ()
bool isDefault ()
void writeValue (QTextStream &t, TextCodecAdapter *codec)
void setTemplateDocs (const QString &docs)
InputInt (QGridLayout *layout, int &row, const QString &id, int defVal, int minVal, int maxVal, const QString &docs)
~InputInt ()=default
QVariant & value ()
void update ()
Kind kind () const
QString docs () const
QString id () const
QString templateDocs () const
void addDependency (Input *)
void setEnabled (bool)
void updateDependencies ()
bool isDefault ()
void writeValue (QTextStream &t, TextCodecAdapter *codec)
void setTemplateDocs (const QString &docs)
Private Slots
void help ()
void help ()
Private Member Functions
void updateDefault ()
void updateDefault ()
Private Attributes
QLabel * m_lab
QSpinBox * m_sp
int m_val
int m_default
int m_minVal
int m_maxVal
QVariant m_value
QString m_docs
QString m_id
QString m_tdocs
Additional Inherited Members
Detailed Description
Definition at line 23 of file inputint.h.
Constructor & Destructor Documentation
InputInt() [1/2]
InputInt::InputInt (QGridLayout * layout, int & row, const QString & id, int defVal, int minVal, int maxVal, const QString & docs)
Definition at line 31 of file inputint.cpp.
  : m_default(defVal), m_minVal(minVal), m_maxVal(maxVal), m_docs(docs), m_id(id)
{
  m_lab = new HelpLabel(id);
  m_sp = new NoWheelSpinBox;
  m_sp->setMinimum(minVal);
  m_sp->setMaximum(maxVal);
  m_sp->setSingleStep(1);
  m_val=defVal-1; // force update
  setValue(defVal);
  layout->addWidget(m_lab, row, 0);
  layout->addWidget(m_sp, row, 1);
  connect(m_sp, SIGNAL(valueChanged(int)),
          this, SLOT(setValue(int)));
  connect(m_lab, SIGNAL(enter()), SLOT(help()));
  connect(m_lab, SIGNAL(reset()), SLOT(reset()));
  row++;
}
References help(), m_lab, m_sp, m_val, reset(), and setValue().
 InputInt() [1/2]
InputInt::~InputInt () [default]
InputInt() [2/2]
InputInt::InputInt (QGridLayout * layout, int & row, const QString & id, int defVal, int minVal, int maxVal, const QString & docs)
 InputInt() [2/2]
InputInt::~InputInt () [default]
Member Function Documentation
addDependency() [1/2]
void InputInt::addDependency (Input *) [inline], [virtual]
Implements Input.
Definition at line 41 of file inputint.h.
{ Q_ASSERT(false); }
addDependency() [2/2]
void InputInt::addDependency (Input *) [inline], [virtual]
Implements Input.
Definition at line 41 of file inputint.h.
{ Q_ASSERT(false); }
changed [1/2]
void InputInt::changed () [signal]
Referenced by updateDefault().
changed [2/2]
void InputInt::changed () [signal]
docs() [1/2]
QString InputInt::docs () const [inline], [virtual]
Implements Input.
Definition at line 38 of file inputint.h.
{ return m_docs; }
References m_docs.
Referenced by setTemplateDocs().
docs() [2/2]
QString InputInt::docs () const [inline], [virtual]
Implements Input.
Definition at line 38 of file inputint.h.
{ return m_docs; }
References m_docs.
help [1/2]
void InputInt::help () [private], [slot]
Definition at line 55 of file inputint.cpp.
{
  showHelp(this);
}
References showHelp().
Referenced by InputInt().
help [2/2]
void InputInt::help () [private], [slot]
id() [1/2]
QString InputInt::id () const [inline], [virtual]
Implements Input.
Definition at line 39 of file inputint.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
QString InputInt::id () const [inline], [virtual]
Implements Input.
Definition at line 39 of file inputint.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
isDefault() [1/2]
bool InputInt::isDefault () [virtual]
Implements Input.
Definition at line 132 of file inputint.cpp.
{
  return m_val == m_default;
}
References m_default, and m_val.
isDefault() [2/2]
bool InputInt::isDefault () [virtual]
Implements Input.
kind() [1/2]
Kind InputInt::kind () const [inline], [virtual]
Implements Input.
Definition at line 37 of file inputint.h.
{ return Int; }
References Input::Int.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
kind() [2/2]
Kind InputInt::kind () const [inline], [virtual]
Implements Input.
Definition at line 37 of file inputint.h.
{ return Int; }
References Input::Int.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
reset [1/2]
void InputInt::reset () [slot]
Definition at line 121 of file inputint.cpp.
{
  setValue(m_default);
}
References m_default, and setValue().
Referenced by InputInt().
reset [2/2]
void InputInt::reset () [slot]
setEnabled() [1/2]
void InputInt::setEnabled (bool state) [virtual]
Implements Input.
Definition at line 96 of file inputint.cpp.
{
  m_lab->setEnabled(state);
  m_sp->setEnabled(state);
  updateDefault();
}
References m_lab, m_sp, and updateDefault().
setEnabled() [2/2]
void InputInt::setEnabled (bool) [virtual]
Implements Input.
setTemplateDocs() [1/2]
void InputInt::setTemplateDocs (const QString & docs) [inline], [virtual]
Implements Input.
Definition at line 46 of file inputint.h.
{ m_tdocs = docs; }
References docs(), and m_tdocs.
setTemplateDocs() [2/2]
void InputInt::setTemplateDocs (const QString & docs) [inline], [virtual]
Implements Input.
Definition at line 46 of file inputint.h.
{ m_tdocs = docs; }
References docs(), and m_tdocs.
setValue [1/2]
void InputInt::setValue (int val) [slot]
Definition at line 61 of file inputint.cpp.
{
  int newVal = val;
  newVal = qMax(m_minVal,newVal);
  newVal = qMin(m_maxVal,newVal);
  if (val != newVal)
  {
    config_warn("argument '%d' for option %s is not a valid number in the range [%d..%d]!"
                " Using the default: %d!\n",val,qPrintable(m_id),m_minVal,m_maxVal,m_default);
    newVal = m_default;
  }
  if (newVal!=m_val)
  {
    m_val = newVal;
    m_sp->setValue(newVal);
    m_value = m_val;
    updateDefault();
  }
}
References config_warn(), m_default, m_id, m_maxVal, m_minVal, m_sp, m_val, m_value, updateDefault(), and testsqlite3::val.
Referenced by InputInt(), reset(), and update().
setValue [2/2]
void InputInt::setValue (int val) [slot]
showHelp [1/2]
void InputInt::showHelp (Input *) [signal]
Referenced by help().
showHelp [2/2]
void InputInt::showHelp (Input *) [signal]
templateDocs() [1/2]
QString InputInt::templateDocs () const [inline], [virtual]
Implements Input.
Definition at line 40 of file inputint.h.
{ return m_tdocs; }
References m_tdocs.
templateDocs() [2/2]
QString InputInt::templateDocs () const [inline], [virtual]
Implements Input.
Definition at line 40 of file inputint.h.
{ return m_tdocs; }
References m_tdocs.
update() [1/2]
void InputInt::update () [virtual]
Implements Input.
Definition at line 108 of file inputint.cpp.
{
  bool ok;
  int newVal = m_value.toInt(&ok);
  if (!ok)
  {
    config_warn("argument '%s' for option %s is not a valid number in the range [%d..%d]!"
                " Using the default: %d!\n",qPrintable(m_value.toString()),qPrintable(m_id),m_minVal,m_maxVal,m_default);
    newVal = m_default;
  }
  setValue(newVal);
}
References config_warn(), m_default, m_id, m_maxVal, m_minVal, m_value, and setValue().
Referenced by runtests.Tester::__init__(), and runtests.Tester::run().
update() [2/2]
void InputInt::update () [virtual]
Implements Input.
Referenced by runtests.Tester::__init__(), and runtests.Tester::run().
updateDefault() [1/2]
void InputInt::updateDefault () [private]
Definition at line 81 of file inputint.cpp.
{
  {
    if (m_val==m_default || !m_lab->isEnabled())
    {
      m_lab->setText(QString::fromLatin1("<qt>")+m_id+QString::fromLatin1("</qt>"));
    }
    else
    {
      m_lab->setText(QString::fromLatin1("<qt><font color='red'>")+m_id+QString::fromLatin1("</font></qt>"));
    }
    emit changed();
  }
}
References changed(), m_default, m_id, m_lab, and m_val.
Referenced by setEnabled(), and setValue().
updateDefault() [2/2]
void InputInt::updateDefault () [private]
updateDependencies() [1/2]
void InputInt::updateDependencies () [inline], [virtual]
Implements Input.
Definition at line 43 of file inputint.h.
{}
updateDependencies() [2/2]
void InputInt::updateDependencies () [inline], [virtual]
Implements Input.
Definition at line 43 of file inputint.h.
{}
value() [1/2]
QVariant & InputInt::value () [virtual]
Implements Input.
Definition at line 103 of file inputint.cpp.
{
  return m_value;
}
References m_value.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), and doxmlparser.index.MixedContainer::to_etree_simple().
value() [2/2]
QVariant & InputInt::value () [virtual]
Implements Input.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), and doxmlparser.index.MixedContainer::to_etree_simple().
writeValue() [1/2]
void InputInt::writeValue (QTextStream & t, TextCodecAdapter * codec) [virtual]
Implements Input.
Definition at line 126 of file inputint.cpp.
{
  t << m_val;
}
References m_val.
writeValue() [2/2]
void InputInt::writeValue (QTextStream & t, TextCodecAdapter * codec) [virtual]
Implements Input.
Member Data Documentation
m_default
int InputInt::m_default [private]
Definition at line 64 of file inputint.h.
Referenced by isDefault(), reset(), setValue(), update(), and updateDefault().
m_docs
QString InputInt::m_docs [private]
Definition at line 68 of file inputint.h.
Referenced by docs().
m_id
QString InputInt::m_id [private]
Definition at line 69 of file inputint.h.
Referenced by id(), setValue(), update(), and updateDefault().
m_lab
QLabel * InputInt::m_lab [private]
Definition at line 61 of file inputint.h.
Referenced by InputInt(), setEnabled(), and updateDefault().
m_maxVal
int InputInt::m_maxVal [private]
Definition at line 66 of file inputint.h.
Referenced by setValue(), and update().
m_minVal
int InputInt::m_minVal [private]
Definition at line 65 of file inputint.h.
Referenced by setValue(), and update().
m_sp
QSpinBox * InputInt::m_sp [private]
Definition at line 62 of file inputint.h.
Referenced by InputInt(), setEnabled(), and setValue().
m_tdocs
QString InputInt::m_tdocs [private]
Definition at line 70 of file inputint.h.
Referenced by setTemplateDocs(), and templateDocs().
m_val
int InputInt::m_val [private]
Definition at line 63 of file inputint.h.
Referenced by InputInt(), isDefault(), setValue(), updateDefault(), and writeValue().
m_value
QVariant InputInt::m_value [private]
Definition at line 67 of file inputint.h.
Referenced by setValue(), update(), and value().
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/inputint.h
doxygen/build/doxygen/addon/doxywizard/inputint.h
doxygen/addon/doxywizard/inputint.cpp
doxygen/build/doxygen/addon/doxywizard/inputint.cpp