TranslatorLatvian Class Reference
#include <translator_lv.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
Additional Inherited Members
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include `translator.h` or `translator_adapter.h` here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 51 of file translator_lv.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorLatvian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 87 of file translator_lv.h.
    {
      return "0x426 Latvian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorLatvian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 87 of file translator_lv.h.
    {
      return "0x426 Latvian";
    }
idLanguage() [1/2]
virtual QCString TranslatorLatvian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 63 of file translator_lv.h.
    { return "latvian"; }
idLanguage() [2/2]
virtual QCString TranslatorLatvian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 63 of file translator_lv.h.
    { return "latvian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorLatvian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 77 of file translator_lv.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[latvian]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorLatvian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 77 of file translator_lv.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[latvian]{babel}\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorLatvian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1900 of file translator_lv.h.
    { return "Papildus mantotie elementi"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorLatvian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1900 of file translator_lv.h.
    { return "Papildus mantotie elementi"; }
trAll() [1/2]
virtual QCString TranslatorLatvian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1408 of file translator_lv.h.
    {
      return "Visi";
    }
trAll() [2/2]
virtual QCString TranslatorLatvian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1408 of file translator_lv.h.
    {
      return "Visi";
    }
trAndMore() [1/2]
virtual QCString TranslatorLatvian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1876 of file translator_lv.h.
    { return "un vl "+number+"..."; }
trAndMore() [2/2]
virtual QCString TranslatorLatvian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1876 of file translator_lv.h.
    { return "un vl "+number+"..."; }
trAttention() [1/2]
virtual QCString TranslatorLatvian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 969 of file translator_lv.h.
    {
      return "Uzmanbu";
    }
trAttention() [2/2]
virtual QCString TranslatorLatvian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 969 of file translator_lv.h.
    {
      return "Uzmanbu";
    }
trAuthor() [1/2]
virtual QCString TranslatorLatvian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1279 of file translator_lv.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      if (singular) result+="s"; else result+="i";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorLatvian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1279 of file translator_lv.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      if (singular) result+="s"; else result+="i";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorLatvian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1137 of file translator_lv.h.
    {
      return "Kda";
    }
trBug() [2/2]
virtual QCString TranslatorLatvian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1137 of file translator_lv.h.
    {
      return "Kda";
    }
trBugList() [1/2]
virtual QCString TranslatorLatvian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1142 of file translator_lv.h.
    {
      return "Kdu saraksts";
    }
trBugList() [2/2]
virtual QCString TranslatorLatvian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1142 of file translator_lv.h.
    {
      return "Kdu saraksts";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorLatvian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1529 of file translator_lv.h.
    {
      return "eit ir s funkcijas izsaukuma grafs:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorLatvian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1529 of file translator_lv.h.
    {
      return "eit ir s funkcijas izsaukuma grafs:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorLatvian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1413 of file translator_lv.h.
    {
      return "eit ir visu funkciju izsaugumu grafs:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorLatvian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1413 of file translator_lv.h.
    {
      return "eit ir visu funkciju izsaugumu grafs:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorLatvian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1852 of file translator_lv.h.
    { return "Bibliogrfisks atsauces"; }
trCiteReferences() [2/2]
virtual QCString TranslatorLatvian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1852 of file translator_lv.h.
    { return "Bibliogrfisks atsauces"; }
trClass() [1/2]
virtual QCString TranslatorLatvian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1200 of file translator_lv.h.
    {
      QCString result((first_capital ? "Klase" : "klase"));
      if (!singular) result+="s";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorLatvian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1200 of file translator_lv.h.
    {
      QCString result((first_capital ? "Klase" : "klase"));
      if (!singular) result+="s";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorLatvian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 523 of file translator_lv.h.
    {
      return "Mantojambas diagramma klasei "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorLatvian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 523 of file translator_lv.h.
    {
      return "Mantojambas diagramma klasei "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorLatvian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 398 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktras dokomentcija";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klases dokumentcija";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorLatvian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 398 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktras dokomentcija";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klases dokumentcija";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorLatvian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1100 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktras";
      }
      else
      {
        return "Klases";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorLatvian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1100 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktras";
      }
      else
      {
        return "Klases";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorLatvian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 182 of file translator_lv.h.
    { return "Klau hierarhija"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorLatvian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 182 of file translator_lv.h.
    { return "Klau hierarhija"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorLatvian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 241 of file translator_lv.h.
    { return "is mantojambas saraksts ir sakrtots aptuveni, "
             "bet ne pilnb, alfabta secb:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorLatvian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 241 of file translator_lv.h.
    { return "is mantojambas saraksts ir sakrtots aptuveni, "
             "bet ne pilnb, alfabta secb:";
    }
trClassMethods() [1/2]
virtual QCString TranslatorLatvian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1938 of file translator_lv.h.
    {
      return "Klases metodes";
    }
trClassMethods() [2/2]
virtual QCString TranslatorLatvian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1938 of file translator_lv.h.
    {
      return "Klases metodes";
    }
trCode() [1/2]
virtual QCString TranslatorLatvian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 869 of file translator_lv.h.
    {
      return "pirmkods";
    }
trCode() [2/2]
virtual QCString TranslatorLatvian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 869 of file translator_lv.h.
    {
      return "pirmkods";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorLatvian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 824 of file translator_lv.h.
    {
      return "Sadarbbas diagramma klasei "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorLatvian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 824 of file translator_lv.h.
    {
      return "Sadarbbas diagramma klasei "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorLatvian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 371 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktru indess";
      }
      else
      {
        return "Klau indekss";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorLatvian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 371 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktru indess";
      }
      else
      {
        return "Klau indekss";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorLatvian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1584 of file translator_lv.h.
    { return "Datu tipu indekss"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorLatvian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1584 of file translator_lv.h.
    { return "Datu tipu indekss"; }
trCompoundList() [1/2]
virtual QCString TranslatorLatvian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 186 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktras";
      }
      else
      {
        return "Klau saraksts";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorLatvian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 186 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktras";
      }
      else
      {
        return "Klau saraksts";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorLatvian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 256 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "eit ir visas datu struktras ar su aprakstu:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "eit ir visas klases ar su aprakstu:";
      }
      else
      {
        return "eit ir visas klases, struktras, "
               "apvienojumi un interfeisi ar su aprakstu:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorLatvian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 256 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "eit ir visas datu struktras ar su aprakstu:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "eit ir visas klases ar su aprakstu:";
      }
      else
      {
        return "eit ir visas klases, struktras, "
               "apvienojumi un interfeisi ar su aprakstu:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorLatvian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1557 of file translator_lv.h.
    { return "eit ir visu datu tipu saraksts ar su aprakstu:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorLatvian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1557 of file translator_lv.h.
    { return "eit ir visu datu tipu saraksts ar su aprakstu:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorLatvian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1549 of file translator_lv.h.
    { return "Datu tipu saraksts"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorLatvian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1549 of file translator_lv.h.
    { return "Datu tipu saraksts"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorLatvian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 203 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu lauki";
      }
      else
      {
        return "Klases elementi";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorLatvian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 203 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu lauki";
      }
      else
      {
        return "Klases elementi";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorLatvian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 275 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll)
      {
        result+="dokumentto ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struktru un apvienojumu lauku";
      }
      else
      {
        result+="klases elementu";
      }
      result+=" saraksts ar saitm uz ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktru/apvienojumu dokumentciju katram laukam:";
        }
        else
        {
          result+="klases dokumentciju katram elementam:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktrm/apvienojumiem, kam tie pieder:";
        }
        else
        {
          result+="klasm, kam tie pieder:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorLatvian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 275 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll)
      {
        result+="dokumentto ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struktru un apvienojumu lauku";
      }
      else
      {
        result+="klases elementu";
      }
      result+=" saraksts ar saitm uz ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktru/apvienojumu dokumentciju katram laukam:";
        }
        else
        {
          result+="klases dokumentciju katram elementam:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktrm/apvienojumiem, kam tie pieder:";
        }
        else
        {
          result+="klasm, kam tie pieder:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorLatvian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1561 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll)
      {
        result+="dokumentto ";
      }
      result+="datu tipu saraksts";
      result+=" ar saitm uz ";
      if (!extractAll)
      {
         result+="datu struktras dokumentciju katram elementam:";
      }
      else
      {
         result+="datu tipiem, kam tie pieder:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorLatvian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1561 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll)
      {
        result+="dokumentto ";
      }
      result+="datu tipu saraksts";
      result+=" ar saitm uz ";
      if (!extractAll)
      {
         result+="datu struktras dokumentciju katram elementam:";
      }
      else
      {
         result+="datu tipiem, kam tie pieder:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorLatvian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1553 of file translator_lv.h.
    { return "Datu lauki"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorLatvian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1553 of file translator_lv.h.
    { return "Datu lauki"; }
trCompoundReference() [1/2]
virtual QCString TranslatorLatvian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 598 of file translator_lv.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" klases"; break;
        case ClassDef::Struct: result+=" struktras"; break;
        case ClassDef::Union: result+=" apvienojuma"; break;
        case ClassDef::Interface: result+=" interfeisa"; break;
        case ClassDef::Protocol: result+=" protokola"; break;
        case ClassDef::Category: result+=" kategorijas"; break;
        case ClassDef::Exception: result+=" izmuma"; break;
        default: break;
      }
      if (isTemplate) result+=" veidnes";
      result+=" apraksts";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorLatvian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 598 of file translator_lv.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" klases"; break;
        case ClassDef::Struct: result+=" struktras"; break;
        case ClassDef::Union: result+=" apvienojuma"; break;
        case ClassDef::Interface: result+=" interfeisa"; break;
        case ClassDef::Protocol: result+=" protokola"; break;
        case ClassDef::Category: result+=" kategorijas"; break;
        case ClassDef::Exception: result+=" izmuma"; break;
        default: break;
      }
      if (isTemplate) result+=" veidnes";
      result+=" apraksts";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorLatvian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1625 of file translator_lv.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" modua"; break;
        case ClassDef::Struct: result+=" tipa"; break;
        case ClassDef::Union: result+=" apvienojuma"; break;
        case ClassDef::Interface: result+=" interfeisa"; break;
        case ClassDef::Protocol: result+=" protokola"; break;
        case ClassDef::Category: result+=" kategorijas"; break;
        case ClassDef::Exception: result+=" izmuma"; break;
        default: break;
      }
      if (isTemplate) result+=" sagataves";
      result+=" atsauce";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorLatvian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1625 of file translator_lv.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" modua"; break;
        case ClassDef::Struct: result+=" tipa"; break;
        case ClassDef::Union: result+=" apvienojuma"; break;
        case ClassDef::Interface: result+=" interfeisa"; break;
        case ClassDef::Protocol: result+=" protokola"; break;
        case ClassDef::Category: result+=" kategorijas"; break;
        case ClassDef::Exception: result+=" izmuma"; break;
        default: break;
      }
      if (isTemplate) result+=" sagataves";
      result+=" atsauce";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorLatvian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 499 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktras";
      }
      else
      {
        return "Klases";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorLatvian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 499 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktras";
      }
      else
      {
        return "Klases";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorLatvian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 834 of file translator_lv.h.
    {
      return "Konstruktora un destruktora dokumentcija";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorLatvian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 834 of file translator_lv.h.
    {
      return "Konstruktora un destruktora dokumentcija";
    }
trCopyright() [1/2]
virtual QCString TranslatorLatvian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1856 of file translator_lv.h.
    { return "Autortiesbas"; }
trCopyright() [2/2]
virtual QCString TranslatorLatvian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1856 of file translator_lv.h.
    { return "Autortiesbas"; }
trDataTypes() [1/2]
virtual QCString TranslatorLatvian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1608 of file translator_lv.h.
    { return "Datu tipi"; }
trDataTypes() [2/2]
virtual QCString TranslatorLatvian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1608 of file translator_lv.h.
    { return "Datu tipi"; }
trDate() [1/2]
virtual QCString TranslatorLatvian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 537 of file translator_lv.h.
    { return "Datums"; }
trDate() [2/2]
virtual QCString TranslatorLatvian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 537 of file translator_lv.h.
    { return "Datums"; }
trDateTime() [1/2]
virtual QCString TranslatorLatvian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1809 of file translator_lv.h.
    {
      static const char *days[] = { "Pirm","Otr","Tr","Cet","Piekt","Sest","Sv" };
      static const char *months[] = { "Jan","Feb","Mar","Apr","Mai","Jn","Jl","Aug","Sept","Okt","Nov","Dec" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorLatvian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1809 of file translator_lv.h.
    {
      static const char *days[] = { "Pirm","Otr","Tr","Cet","Piekt","Sest","Sv" };
      static const char *months[] = { "Jan","Feb","Mar","Apr","Mai","Jn","Jl","Aug","Sept","Okt","Nov","Dec" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorLatvian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1825 of file translator_lv.h.
    {
      static const char *days_short[] = { "pirmd.", "otrd.", "tred.", "ceturtd.", "piektd.", "sestd.", "svtd." };
      static const char *days_full[] = { "pirmdiena", "otrdiena", "trediena", "ceturtdiena", "piektdiena", "sestdiena", "svtdiena" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorLatvian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1825 of file translator_lv.h.
    {
      static const char *days_short[] = { "pirmd.", "otrd.", "tred.", "ceturtd.", "piektd.", "sestd.", "svtd." };
      static const char *days_full[] = { "pirmdiena", "otrdiena", "trediena", "ceturtdiena", "piektdiena", "sestdiena", "svtdiena" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorLatvian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1841 of file translator_lv.h.
    {
      static const char *dayPeriod[] = { "priekp.", "pcp." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorLatvian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1841 of file translator_lv.h.
    {
      static const char *dayPeriod[] = { "priekp.", "pcp." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorLatvian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 801 of file translator_lv.h.
    {
      return "Defints lnij @0 fail @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorLatvian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 801 of file translator_lv.h.
    {
      return "Defints lnij @0 fail @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorLatvian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 170 of file translator_lv.h.
    { return "defints"; }
trDefinedIn() [2/2]
virtual QCString TranslatorLatvian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 170 of file translator_lv.h.
    { return "defints"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorLatvian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 805 of file translator_lv.h.
    {
      return "Defints fail @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorLatvian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 805 of file translator_lv.h.
    {
      return "Defints fail @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorLatvian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 469 of file translator_lv.h.
    { return "Makro defincijas dokumentcija"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorLatvian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 469 of file translator_lv.h.
    { return "Makro defincijas dokumentcija"; }
trDefines() [1/2]
virtual QCString TranslatorLatvian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 433 of file translator_lv.h.
    { return "Makro"; }
trDefines() [2/2]
virtual QCString TranslatorLatvian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 433 of file translator_lv.h.
    { return "Makro"; }
trDefineValue() [1/2]
virtual QCString TranslatorLatvian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1127 of file translator_lv.h.
    {
      return "Vrtba:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorLatvian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1127 of file translator_lv.h.
    {
      return "Vrtba:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorLatvian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 814 of file translator_lv.h.
    {
      return "Novecojusi";
    }
trDeprecated() [2/2]
virtual QCString TranslatorLatvian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 814 of file translator_lv.h.
    {
      return "Novecojusi";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorLatvian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1336 of file translator_lv.h.
    {
      return "Novecojuo saraksts";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorLatvian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1336 of file translator_lv.h.
    {
      return "Novecojuo saraksts";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorLatvian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 103 of file translator_lv.h.
    { return "Detalizts apraksts"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorLatvian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 103 of file translator_lv.h.
    { return "Detalizts apraksts"; }
trDetailLevel() [1/2]
virtual QCString TranslatorLatvian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1868 of file translator_lv.h.
    { return "detalizcijas lmenis"; }
trDetailLevel() [2/2]
virtual QCString TranslatorLatvian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1868 of file translator_lv.h.
    { return "detalizcijas lmenis"; }
trDir() [1/2]
virtual QCString TranslatorLatvian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1503 of file translator_lv.h.
    {
      QCString result((first_capital ? "Direktorija" : "direktorija"));
      if (!singular) result+="s";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorLatvian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1503 of file translator_lv.h.
    {
      QCString result((first_capital ? "Direktorija" : "direktorija"));
      if (!singular) result+="s";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorLatvian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1860 of file translator_lv.h.
    { return QCString("Atkarbu grafs direktorijai ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorLatvian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1860 of file translator_lv.h.
    { return QCString("Atkarbu grafs direktorijai ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorLatvian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1485 of file translator_lv.h.
    { return "Direktorijas dokumentcija"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorLatvian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1485 of file translator_lv.h.
    { return "Direktorijas dokumentcija"; }
trDirectories() [1/2]
virtual QCString TranslatorLatvian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1491 of file translator_lv.h.
    { return "Direktorijas"; }
trDirectories() [2/2]
virtual QCString TranslatorLatvian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1491 of file translator_lv.h.
    { return "Direktorijas"; }
trDirIndex() [1/2]
virtual QCString TranslatorLatvian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1479 of file translator_lv.h.
    { return "Direktoriju struktra"; }
trDirIndex() [2/2]
virtual QCString TranslatorLatvian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1479 of file translator_lv.h.
    { return "Direktoriju struktra"; }
trDirReference() [1/2]
virtual QCString TranslatorLatvian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1497 of file translator_lv.h.
    { QCString result="Direktorijas "; result+=dirName; result+=" atsauce"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorLatvian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1497 of file translator_lv.h.
    { QCString result="Direktorijas "; result+=dirName; result+=" atsauce"; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorLatvian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1748 of file translator_lv.h.
    {
      return QCString(name)+" relcija";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorLatvian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1748 of file translator_lv.h.
    {
      return QCString(name)+" relcija";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorLatvian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 353 of file translator_lv.h.
    { return "Dokumentcija"; }
trDocumentation() [2/2]
virtual QCString TranslatorLatvian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 353 of file translator_lv.h.
    { return "Dokumentcija"; }
trEnumerations() [1/2]
virtual QCString TranslatorLatvian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 445 of file translator_lv.h.
    { return "Uzskaitjumi"; }
trEnumerations() [2/2]
virtual QCString TranslatorLatvian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 445 of file translator_lv.h.
    { return "Uzskaitjumi"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorLatvian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 481 of file translator_lv.h.
    { return "Uzskaitjumlitera tipa dokumentcija"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorLatvian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 481 of file translator_lv.h.
    { return "Uzskaitjumlitera tipa dokumentcija"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorLatvian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1537 of file translator_lv.h.
    { return "Uzskaitjumlitera dokumentcija"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorLatvian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1537 of file translator_lv.h.
    { return "Uzskaitjumlitera dokumentcija"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorLatvian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 463 of file translator_lv.h.
    { return "Uzskaitjumliteri"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorLatvian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 463 of file translator_lv.h.
    { return "Uzskaitjumliteri"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorLatvian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1880 of file translator_lv.h.
    { QCString result = "Dokumentcija im uzskaitjumliterlim tika enerta no sekojo";
      if (single) result+="a"; else result += "iem";
      result+=" fail";
      if (single) result+="a"; else result += "iem";
      result+=":";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorLatvian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1880 of file translator_lv.h.
    { QCString result = "Dokumentcija im uzskaitjumliterlim tika enerta no sekojo";
      if (single) result+="a"; else result += "iem";
      result+=" fail";
      if (single) result+="a"; else result += "iem";
      result+=":";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorLatvian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 162 of file translator_lv.h.
    { return "uzskaitjuma nosaukums"; }
trEnumName() [2/2]
virtual QCString TranslatorLatvian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 162 of file translator_lv.h.
    { return "uzskaitjuma nosaukums"; }
trEnumReference() [1/2]
virtual QCString TranslatorLatvian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1890 of file translator_lv.h.
    { return QCString(name)+" uzskaitjumlitera atsauce"; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorLatvian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1890 of file translator_lv.h.
    { return QCString(name)+" uzskaitjumlitera atsauce"; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorLatvian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 166 of file translator_lv.h.
    { return "uzskaitjuma vrtba"; }
trEnumValue() [2/2]
virtual QCString TranslatorLatvian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 166 of file translator_lv.h.
    { return "uzskaitjuma vrtba"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorLatvian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1353 of file translator_lv.h.
    {
      return "Notikumu dokumentcija";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorLatvian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1353 of file translator_lv.h.
    {
      return "Notikumu dokumentcija";
    }
trEvents() [1/2]
virtual QCString TranslatorLatvian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1348 of file translator_lv.h.
    {
      return "Notikumi";
    }
trEvents() [2/2]
virtual QCString TranslatorLatvian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1348 of file translator_lv.h.
    {
      return "Notikumi";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorLatvian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 423 of file translator_lv.h.
    { return "Piemri"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorLatvian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 423 of file translator_lv.h.
    { return "Piemri"; }
trExamples() [1/2]
virtual QCString TranslatorLatvian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 233 of file translator_lv.h.
    { return "Piemri"; }
trExamples() [2/2]
virtual QCString TranslatorLatvian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 233 of file translator_lv.h.
    { return "Piemri"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorLatvian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 339 of file translator_lv.h.
    { return "eit ir visu piemru saraksts:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorLatvian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 339 of file translator_lv.h.
    { return "eit ir visu piemru saraksts:"; }
trExceptions() [1/2]
virtual QCString TranslatorLatvian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 553 of file translator_lv.h.
    { return "Izmumi"; }
trExceptions() [2/2]
virtual QCString TranslatorLatvian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 553 of file translator_lv.h.
    { return "Izmumi"; }
trExtendsClass() [1/2]
virtual QCString TranslatorLatvian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1930 of file translator_lv.h.
    {
      return "Paplaina klasi @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorLatvian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1930 of file translator_lv.h.
    {
      return "Paplaina klasi @0.";
    }
trFile() [1/2]
virtual QCString TranslatorLatvian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1211 of file translator_lv.h.
    {
      QCString result((first_capital ? "Fail" : "fail"));
      if (singular) result+="s"; else result+="i";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorLatvian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1211 of file translator_lv.h.
    {
      QCString result((first_capital ? "Fail" : "fail"));
      if (singular) result+="s"; else result+="i";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorLatvian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 417 of file translator_lv.h.
    { return "Faila dokumentcija"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorLatvian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 417 of file translator_lv.h.
    { return "Faila dokumentcija"; }
trFileIn() [1/2]
virtual QCString TranslatorLatvian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1785 of file translator_lv.h.
    {
      return "File in "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorLatvian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1785 of file translator_lv.h.
    {
      return "File in "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorLatvian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 386 of file translator_lv.h.
    { return "Failu indekss"; }
trFileIndex() [2/2]
virtual QCString TranslatorLatvian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 386 of file translator_lv.h.
    { return "Failu indekss"; }
trFileList() [1/2]
virtual QCString TranslatorLatvian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 199 of file translator_lv.h.
    { return "Failu saraksts"; }
trFileList() [2/2]
virtual QCString TranslatorLatvian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 199 of file translator_lv.h.
    { return "Failu saraksts"; }
trFileListDescription() [1/2]
virtual QCString TranslatorLatvian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 247 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll) result+="dokumentto ";
      result+="failu saraksts ar su aprakstu:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorLatvian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 247 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll) result+="dokumentto ";
      result+="failu saraksts ar su aprakstu:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorLatvian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 216 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globlie";
      }
      else
      {
        return "Faila elementi";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorLatvian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 216 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globlie";
      }
      else
      {
        return "Faila elementi";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorLatvian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 317 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll) result+="dokumentto ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkciju, maingo, definciju, uzskaitjumliteru un typedefs";
      }
      else
      {
        result+="faila elementu";
      }
      result+=" saraksts ar saitm uz ";
      if (extractAll)
        result+="failiem, kam tie pieder:";
      else
        result+="dokumentciju:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorLatvian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 317 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll) result+="dokumentto ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkciju, maingo, definciju, uzskaitjumliteru un typedefs";
      }
      else
      {
        result+="faila elementu";
      }
      result+=" saraksts ar saitm uz ";
      if (extractAll)
        result+="failiem, kam tie pieder:";
      else
        result+="dokumentciju:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorLatvian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 620 of file translator_lv.h.
    {
      QCString result=fileName;
      result+=" faila apraksts";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorLatvian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 620 of file translator_lv.h.
    {
      QCString result=fileName;
      result+=" faila apraksts";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorLatvian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 580 of file translator_lv.h.
    { return "Draugi"; }
trFriends() [2/2]
virtual QCString TranslatorLatvian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 580 of file translator_lv.h.
    { return "Draugi"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorLatvian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 487 of file translator_lv.h.
    { return "Funkcijas dokumentcija"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorLatvian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 487 of file translator_lv.h.
    { return "Funkcijas dokumentcija"; }
trFunctions() [1/2]
virtual QCString TranslatorLatvian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 451 of file translator_lv.h.
    { return "Funkcijas"; }
trFunctions() [2/2]
virtual QCString TranslatorLatvian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 451 of file translator_lv.h.
    { return "Funkcijas"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorLatvian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 514 of file translator_lv.h.
    {
      QCString result="enerts "+date;
      if (!projName.isEmpty()) result+=" projektam "+projName;
      result+=" ar";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorLatvian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 514 of file translator_lv.h.
    {
      QCString result="enerts "+date;
      if (!projName.isEmpty()) result+=" projektam "+projName;
      result+=" ar";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorLatvian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 154 of file translator_lv.h.
    { QCString result="Automtiski enerts izmantojot Doxygen";
      if (!s.isEmpty()) result+=" priek "+s;
      result+=" no pirmkoda.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorLatvian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 154 of file translator_lv.h.
    { QCString result="Automtiski enerts izmantojot Doxygen";
      if (!s.isEmpty()) result+=" priek "+s;
      result+=" no pirmkoda.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorLatvian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 557 of file translator_lv.h.
    { return "enerts ar"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorLatvian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 557 of file translator_lv.h.
    { return "enerts ar"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorLatvian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 758 of file translator_lv.h.
    { // single is true implies a single file
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+="s klases"; break;
        case ClassDef::Struct: result+="s struktras"; break;
        case ClassDef::Union: result+=" apvienojuma"; break;
        case ClassDef::Interface: result+=" interfeisa"; break;
        case ClassDef::Protocol: result+=" protokola"; break;
        case ClassDef::Category: result+="s kategorijas"; break;
        case ClassDef::Exception: result+=" izmuma"; break;
        default: break;
      }
      result+=" dokumentcijas tika enerta no da fail";
      if (single) result+="a:"; else result+="iem:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorLatvian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 758 of file translator_lv.h.
    { // single is true implies a single file
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+="s klases"; break;
        case ClassDef::Struct: result+="s struktras"; break;
        case ClassDef::Union: result+=" apvienojuma"; break;
        case ClassDef::Interface: result+=" interfeisa"; break;
        case ClassDef::Protocol: result+=" protokola"; break;
        case ClassDef::Category: result+="s kategorijas"; break;
        case ClassDef::Exception: result+=" izmuma"; break;
        default: break;
      }
      result+=" dokumentcijas tika enerta no da fail";
      if (single) result+="a:"; else result+="iem:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorLatvian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1694 of file translator_lv.h.
    {
      // single is true implies a single file
      QCString result="Dokumentcija ";
      switch(compType)
      {
        case ClassDef::Class: result+="im modulim"; break;
        case ClassDef::Struct: result+="im tipam"; break;
        case ClassDef::Union: result+="im apvienojumam"; break;
        case ClassDef::Interface: result+="im interfeisam"; break;
        case ClassDef::Protocol: result+="im protokolam"; break;
        case ClassDef::Category: result+="ai kategorijai"; break;
        case ClassDef::Exception: result+="im izmumam"; break;
        default: break;
      }
      result+=" tika enerta no fail";
      if (single) result+="a:"; else result+="iem:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorLatvian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1694 of file translator_lv.h.
    {
      // single is true implies a single file
      QCString result="Dokumentcija ";
      switch(compType)
      {
        case ClassDef::Class: result+="im modulim"; break;
        case ClassDef::Struct: result+="im tipam"; break;
        case ClassDef::Union: result+="im apvienojumam"; break;
        case ClassDef::Interface: result+="im interfeisam"; break;
        case ClassDef::Protocol: result+="im protokolam"; break;
        case ClassDef::Category: result+="ai kategorijai"; break;
        case ClassDef::Exception: result+="im izmumam"; break;
        default: break;
      }
      result+=" tika enerta no fail";
      if (single) result+="a:"; else result+="iem:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorLatvian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1266 of file translator_lv.h.
    {
      QCString result((first_capital ? "Globl" : "globl"));
      if (singular) result+="ais"; else result+="ie";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorLatvian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1266 of file translator_lv.h.
    {
      QCString result((first_capital ? "Globl" : "globl"));
      if (singular) result+="ais"; else result+="ie";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorLatvian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1760 of file translator_lv.h.
    {
      return "Global Namespace";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorLatvian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1760 of file translator_lv.h.
    {
      return "Global Namespace";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorLatvian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 844 of file translator_lv.h.
    {
      return "Ietu uz faila dokumentciju.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorLatvian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 844 of file translator_lv.h.
    {
      return "Ietu uz faila dokumentciju.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorLatvian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_lv.h.
    {
      return "Iet uz grafisku klases hierarhiju";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorLatvian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_lv.h.
    {
      return "Iet uz grafisku klases hierarhiju";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorLatvian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 839 of file translator_lv.h.
    {
      return "Iet uz faila pirmkodu.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorLatvian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 839 of file translator_lv.h.
    {
      return "Iet uz faila pirmkodu.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorLatvian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_lv.h.
    {
      return "Iet uz tekstulu klases hierarhiju";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorLatvian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_lv.h.
    {
      return "Iet uz tekstulu klases hierarhiju";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorLatvian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 873 of file translator_lv.h.
    {
      return "Grafiska klases hierarhija";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorLatvian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 873 of file translator_lv.h.
    {
      return "Grafiska klases hierarhija";
    }
trGroup() [1/2]
virtual QCString TranslatorLatvian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1233 of file translator_lv.h.
    {
      QCString result((first_capital ? "Grupa" : "grupa"));
      if (!singular) result+="s";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorLatvian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1233 of file translator_lv.h.
    {
      QCString result((first_capital ? "Grupa" : "grupa"));
      if (!singular) result+="s";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorLatvian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 365 of file translator_lv.h.
    { return "Hierarhijas indekss"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorLatvian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 365 of file translator_lv.h.
    { return "Hierarhijas indekss"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorLatvian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1304 of file translator_lv.h.
    {
      return "steno "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorLatvian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1304 of file translator_lv.h.
    {
      return "steno "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorLatvian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1312 of file translator_lv.h.
    {
      return "stenots "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorLatvian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1312 of file translator_lv.h.
    {
      return "stenots "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorLatvian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_lv.h.
    {
      return "is grafs rda kuri faili tiei vai "
             "netiei iekauj o failu:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorLatvian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_lv.h.
    {
      return "is grafs rda kuri faili tiei vai "
             "netiei iekauj o failu:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorLatvian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 829 of file translator_lv.h.
    {
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorLatvian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 829 of file translator_lv.h.
    {
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorLatvian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1794 of file translator_lv.h.
    {
      return "Includes file in "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorLatvian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1794 of file translator_lv.h.
    {
      return "Includes file in "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorLatvian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 148 of file translator_lv.h.
    { return ", ieskaitot mantotos elementus."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorLatvian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 148 of file translator_lv.h.
    { return ", ieskaitot mantotos elementus."; }
trInheritedByList() [1/2]
virtual QCString TranslatorLatvian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 692 of file translator_lv.h.
    {
      return "Tiek mantots "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorLatvian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 692 of file translator_lv.h.
    {
      return "Tiek mantots "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorLatvian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1894 of file translator_lv.h.
    { return QCString(members)+" manto no "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorLatvian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1894 of file translator_lv.h.
    { return QCString(members)+" manto no "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorLatvian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 684 of file translator_lv.h.
    {
      return "Manto no "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorLatvian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 684 of file translator_lv.h.
    {
      return "Manto no "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorLatvian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 864 of file translator_lv.h.
    {
      return "Skotnj vrtba:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorLatvian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 864 of file translator_lv.h.
    {
      return "Skotnj vrtba:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorLatvian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1946 of file translator_lv.h.
    {
      return "Instances metodes";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorLatvian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1946 of file translator_lv.h.
    {
      return "Instances metodes";
    }
trInvariant() [1/2]
virtual QCString TranslatorLatvian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 859 of file translator_lv.h.
    {
      return "Invariants";
    }
trInvariant() [2/2]
virtual QCString TranslatorLatvian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 859 of file translator_lv.h.
    {
      return "Invariants";
    }
trISOLang() [1/2]
virtual QCString TranslatorLatvian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 83 of file translator_lv.h.
    {
      return "lv";
    }
trISOLang() [2/2]
virtual QCString TranslatorLatvian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 83 of file translator_lv.h.
    {
      return "lv";
    }
trLegend() [1/2]
virtual QCString TranslatorLatvian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1060 of file translator_lv.h.
    {
      return "leenda";
    }
trLegend() [2/2]
virtual QCString TranslatorLatvian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1060 of file translator_lv.h.
    {
      return "leenda";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorLatvian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 995 of file translator_lv.h.
    {
      return
        "This page explains how to interpret the graphs that are generated "
        "by doxygen.<p>\n"
        "Consider the following example:\n"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "This will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A filled gray box represents the struct or class for which the "
        "graph is generated.</li>\n"
        "<li>%A box with a black border denotes a documented struct or class.</li>\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.</li>\n"
        "<li>%A box with a red border denotes a documented struct or class for"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries.</li>\n"
        "</ul>\n"
        "<p>\n"
        "The arrows have the following meaning:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.</li>\n"
        "<li>%A dark green arrow is used for protected inheritance.</li>\n"
        "<li>%A dark red arrow is used for private inheritance.</li>\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible.</li>\n"
        "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "the template class it was instantiated from. The arrow is labeled with "
        "the template parameters of the instance.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorLatvian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 995 of file translator_lv.h.
    {
      return
        "This page explains how to interpret the graphs that are generated "
        "by doxygen.<p>\n"
        "Consider the following example:\n"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "This will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A filled gray box represents the struct or class for which the "
        "graph is generated.</li>\n"
        "<li>%A box with a black border denotes a documented struct or class.</li>\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.</li>\n"
        "<li>%A box with a red border denotes a documented struct or class for"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries.</li>\n"
        "</ul>\n"
        "<p>\n"
        "The arrows have the following meaning:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.</li>\n"
        "<li>%A dark green arrow is used for protected inheritance.</li>\n"
        "<li>%A dark red arrow is used for private inheritance.</li>\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible.</li>\n"
        "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "the template class it was instantiated from. The arrow is labeled with "
        "the template parameters of the instance.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorLatvian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 988 of file translator_lv.h.
    {
      return "Grafika leenda";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorLatvian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 988 of file translator_lv.h.
    {
      return "Grafika leenda";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorLatvian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 136 of file translator_lv.h.
    { return "Visu elementu saraksts"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorLatvian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 136 of file translator_lv.h.
    { return "Visu elementu saraksts"; }
trLoading() [1/2]
virtual QCString TranslatorLatvian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1754 of file translator_lv.h.
    {
      return "Tiek veikta ielde...";
    }
trLoading() [2/2]
virtual QCString TranslatorLatvian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1754 of file translator_lv.h.
    {
      return "Tiek veikta ielde...";
    }
trMainPage() [1/2]
virtual QCString TranslatorLatvian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 788 of file translator_lv.h.
    { return "Skumlapa"; }
trMainPage() [2/2]
virtual QCString TranslatorLatvian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 788 of file translator_lv.h.
    { return "Skumlapa"; }
trMember() [1/2]
virtual QCString TranslatorLatvian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1255 of file translator_lv.h.
    {
      QCString result((first_capital ? "Element" : "element"));
      if (singular) result+="s"; else result+="i";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorLatvian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1255 of file translator_lv.h.
    {
      QCString result((first_capital ? "Element" : "element"));
      if (singular) result+="s"; else result+="i";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorLatvian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 119 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lauka dokumentcija";
      }
      else
      {
        return "Elementa datu dokumentcija";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorLatvian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 119 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lauka dokumentcija";
      }
      else
      {
        return "Elementa datu dokumentcija";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorLatvian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 111 of file translator_lv.h.
    { return "Elementa uzskaitjumlitera dokumentcija"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorLatvian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 111 of file translator_lv.h.
    { return "Elementa uzskaitjumlitera dokumentcija"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorLatvian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 115 of file translator_lv.h.
    { return "Elementa funkcijas dokumentcija"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorLatvian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 115 of file translator_lv.h.
    { return "Elementa funkcijas dokumentcija"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorLatvian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1545 of file translator_lv.h.
    { return "Elementa funckijas/apakrutnas dokumentcija"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorLatvian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1545 of file translator_lv.h.
    { return "Elementa funckijas/apakrutnas dokumentcija"; }
trMemberList() [1/2]
virtual QCString TranslatorLatvian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 140 of file translator_lv.h.
    { return "Elementu saraksts"; }
trMemberList() [2/2]
virtual QCString TranslatorLatvian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 140 of file translator_lv.h.
    { return "Elementu saraksts"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorLatvian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 107 of file translator_lv.h.
    { return "Elementa Typedef dokumentcija"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorLatvian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 107 of file translator_lv.h.
    { return "Elementa Typedef dokumentcija"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorLatvian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1953 of file translator_lv.h.
    {
      return "Metou dokumentcija";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorLatvian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1953 of file translator_lv.h.
    {
      return "Metou dokumentcija";
    }
trModule() [1/2]
virtual QCString TranslatorLatvian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1684 of file translator_lv.h.
    {
      QCString result((first_capital ? "Modu" : "modu"));
      if (singular) result+="lis"; else result+="i";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorLatvian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1684 of file translator_lv.h.
    {
      QCString result((first_capital ? "Modu" : "modu"));
      if (singular) result+="lis"; else result+="i";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorLatvian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 392 of file translator_lv.h.
    { return "Modua dokumentcija"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorLatvian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 392 of file translator_lv.h.
    { return "Modua dokumentcija"; }
trModuleIndex() [1/2]
virtual QCString TranslatorLatvian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 359 of file translator_lv.h.
    { return "Moduu indekss"; }
trModuleIndex() [2/2]
virtual QCString TranslatorLatvian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 359 of file translator_lv.h.
    { return "Moduu indekss"; }
trModuleReference() [1/2]
virtual QCString TranslatorLatvian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1646 of file translator_lv.h.
    {
      QCString result=namespaceName;
      result+=" moduu atsauce";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorLatvian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1646 of file translator_lv.h.
    {
      QCString result=namespaceName;
      result+=" moduu atsauce";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorLatvian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 178 of file translator_lv.h.
    { return "Modui"; }
trModules() [2/2]
virtual QCString TranslatorLatvian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 178 of file translator_lv.h.
    { return "Modui"; }
trModulesDescription() [1/2]
virtual QCString TranslatorLatvian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 347 of file translator_lv.h.
    { return "eit ir visu moduu saraksts:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorLatvian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 347 of file translator_lv.h.
    { return "eit ir visu moduu saraksts:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorLatvian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1677 of file translator_lv.h.
    { return "Moduu indekss"; }
trModulesIndex() [2/2]
virtual QCString TranslatorLatvian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1677 of file translator_lv.h.
    { return "Moduu indekss"; }
trModulesList() [1/2]
virtual QCString TranslatorLatvian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1612 of file translator_lv.h.
    { return "Moduu saraksts"; }
trModulesList() [2/2]
virtual QCString TranslatorLatvian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1612 of file translator_lv.h.
    { return "Moduu saraksts"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorLatvian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1616 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll) result+="dokumentto ";
      result+="moduu saraksts ar su aprakstu:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorLatvian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1616 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll) result+="dokumentto ";
      result+="moduu saraksts ar su aprakstu:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorLatvian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1658 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll) result+="dokumentto ";
      result+="modua elementu saraksts ar saitm uz ";
      if (extractAll)
      {
        result+="modua dokumentciju katram elementam:";
      }
      else
      {
        result+="moduiem, kuriem tie pieder:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorLatvian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1658 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll) result+="dokumentto ";
      result+="modua elementu saraksts ar saitm uz ";
      if (extractAll)
      {
        result+="modua dokumentciju katram elementam:";
      }
      else
      {
        result+="moduiem, kuriem tie pieder:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorLatvian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1654 of file translator_lv.h.
    { return "Modua elementi"; }
trModulesMembers() [2/2]
virtual QCString TranslatorLatvian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1654 of file translator_lv.h.
    { return "Modua elementi"; }
trMonth() [1/2]
virtual QCString TranslatorLatvian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1833 of file translator_lv.h.
    {
      static const char *months_short[] = { "janv.", "febr.", "marts", "apr.", "maijs", "jn.", "jl.", "aug.", "sept.", "okt.", "nov.", "dec." };
      static const char *months_full[] = { "janvris", "februris", "marts", "aprlis", "maijs", "jnijs", "jlijs", "augusts", "septembris", "oktobris", "novembris", "decembris" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorLatvian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1833 of file translator_lv.h.
    {
      static const char *months_short[] = { "janv.", "febr.", "marts", "apr.", "maijs", "jn.", "jl.", "aug.", "sept.", "okt.", "nov.", "dec." };
      static const char *months_full[] = { "janvris", "februris", "marts", "aprlis", "maijs", "jnijs", "jlijs", "augusts", "septembris", "oktobris", "novembris", "decembris" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorLatvian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 132 of file translator_lv.h.
    { return "vairk..."; }
trMore() [2/2]
virtual QCString TranslatorLatvian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 132 of file translator_lv.h.
    { return "vairk..."; }
trNamespace() [1/2]
virtual QCString TranslatorLatvian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1222 of file translator_lv.h.
    {
      QCString result((first_capital ? "Nosaukumvieta" : "nosaukumvieta"));
      if (!singular) result+="s";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorLatvian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1222 of file translator_lv.h.
    {
      QCString result((first_capital ? "Nosaukumvieta" : "nosaukumvieta"));
      if (!singular) result+="s";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorLatvian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 738 of file translator_lv.h.
    { return "Nosaukumvietas dokumentcija"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorLatvian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 738 of file translator_lv.h.
    { return "Nosaukumvietas dokumentcija"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorLatvian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 732 of file translator_lv.h.
    { return "Nosaukumvietu indekss"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorLatvian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 732 of file translator_lv.h.
    { return "Nosaukumvietu indekss"; }
trNamespaceList() [1/2]
virtual QCString TranslatorLatvian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 565 of file translator_lv.h.
    { return "Nosaukumvietu saraksts"; }
trNamespaceList() [2/2]
virtual QCString TranslatorLatvian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 565 of file translator_lv.h.
    { return "Nosaukumvietu saraksts"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorLatvian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 569 of file translator_lv.h.
    {
      QCString result="eit ir visas ";
      if (!extractAll) result+="dokumentts ";
      result+="nosaukumvietas ar su aprakstu:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorLatvian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 569 of file translator_lv.h.
    {
      QCString result="eit ir visas ";
      if (!extractAll) result+="dokumentts ";
      result+="nosaukumvietas ar su aprakstu:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorLatvian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 718 of file translator_lv.h.
    {
      QCString result="eit ir visi ";
      if (!extractAll) result+="dokumenttie ";
      result+="nosaukumvietas elementi ar saitm uz ";
      if (extractAll)
        result+="nosaukumvieta dokumentciju katram elementam:";
      else
        result+="nosaukumvietu, kam tie pieder:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorLatvian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 718 of file translator_lv.h.
    {
      QCString result="eit ir visi ";
      if (!extractAll) result+="dokumenttie ";
      result+="nosaukumvietas elementi ar saitm uz ";
      if (extractAll)
        result+="nosaukumvieta dokumentciju katram elementam:";
      else
        result+="nosaukumvietu, kam tie pieder:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorLatvian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 714 of file translator_lv.h.
    { return "Nosaukumvietas elementi"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorLatvian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 714 of file translator_lv.h.
    { return "Nosaukumvietas elementi"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorLatvian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 628 of file translator_lv.h.
    {
      QCString result=namespaceName;
      result+=" nosaukumvietas apraksts";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorLatvian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 628 of file translator_lv.h.
    {
      QCString result=namespaceName;
      result+=" nosaukumvietas apraksts";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorLatvian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 748 of file translator_lv.h.
    { return "Nosaukumvietas"; }
trNamespaces() [2/2]
virtual QCString TranslatorLatvian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 748 of file translator_lv.h.
    { return "Nosaukumvietas"; }
trNoMatches() [1/2]
virtual QCString TranslatorLatvian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1772 of file translator_lv.h.
    {
      return "Nav atbilstbu";
    }
trNoMatches() [2/2]
virtual QCString TranslatorLatvian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1772 of file translator_lv.h.
    {
      return "Nav atbilstbu";
    }
trNote() [1/2]
virtual QCString TranslatorLatvian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 894 of file translator_lv.h.
    {
      return "Piezme";
    }
trNote() [2/2]
virtual QCString TranslatorLatvian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 894 of file translator_lv.h.
    {
      return "Piezme";
    }
trOverloadText() [1/2]
virtual QCString TranslatorLatvian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1517 of file translator_lv.h.
    {
       return " ir elementa prslogota funkcija, kas "
              "pardta tikai informtvo nolkos. T atiras no iepriekapraksts "
              "funkcijas tikai ar parametriem, ko t saem.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorLatvian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1517 of file translator_lv.h.
    {
       return " ir elementa prslogota funkcija, kas "
              "pardta tikai informtvo nolkos. T atiras no iepriekapraksts "
              "funkcijas tikai ar parametriem, ko t saem.";
    }
trPackage() [1/2]
virtual QCString TranslatorLatvian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1112 of file translator_lv.h.
    {
      return "Pakotne "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorLatvian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1112 of file translator_lv.h.
    {
      return "Pakotne "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorLatvian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1389 of file translator_lv.h.
    {
      return "Pakas atribti";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorLatvian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1389 of file translator_lv.h.
    {
      return "Pakas atribti";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorLatvian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1371 of file translator_lv.h.
    {
      return "Pakas funkcijas";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorLatvian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1371 of file translator_lv.h.
    {
      return "Pakas funkcijas";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorLatvian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1117 of file translator_lv.h.
    {
      return "Here are the packages with brief descriptions (if available):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorLatvian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1117 of file translator_lv.h.
    {
      return "Here are the packages with brief descriptions (if available):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorLatvian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1375 of file translator_lv.h.
    {
      return "Pakas elementi";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorLatvian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1375 of file translator_lv.h.
    {
      return "Pakas elementi";
    }
trPackages() [1/2]
virtual QCString TranslatorLatvian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1122 of file translator_lv.h.
    {
      return "Pakotnes";
    }
trPackages() [2/2]
virtual QCString TranslatorLatvian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1122 of file translator_lv.h.
    {
      return "Pakotnes";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorLatvian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1364 of file translator_lv.h.
    {
      return "Pakas tipi";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorLatvian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1364 of file translator_lv.h.
    {
      return "Pakas tipi";
    }
trPage() [1/2]
virtual QCString TranslatorLatvian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1244 of file translator_lv.h.
    {
      QCString result((first_capital ? "Lapa" : "lapa"));
      if (!singular) result+="s";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorLatvian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1244 of file translator_lv.h.
    {
      QCString result((first_capital ? "Lapa" : "lapa"));
      if (!singular) result+="s";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorLatvian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 794 of file translator_lv.h.
    { return "lpp."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorLatvian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 794 of file translator_lv.h.
    { return "lpp."; }
trPageIndex() [1/2]
virtual QCString TranslatorLatvian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_lv.h.
    {
      return "Lapas indekss";
    }
trPageIndex() [2/2]
virtual QCString TranslatorLatvian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_lv.h.
    {
      return "Lapas indekss";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorLatvian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1911 of file translator_lv.h.
    {
      QCString opt = enable ? "iespjotu" : "atspjotu";
      return "uzklikint, lai "+opt+" paneu sinhronizciju";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorLatvian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1911 of file translator_lv.h.
    {
      QCString opt = enable ? "iespjotu" : "atspjotu";
      return "uzklikint, lai "+opt+" paneu sinhronizciju";
    }
trParameters() [1/2]
virtual QCString TranslatorLatvian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 549 of file translator_lv.h.
    { return "Parametri"; }
trParameters() [2/2]
virtual QCString TranslatorLatvian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 549 of file translator_lv.h.
    { return "Parametri"; }
trPostcondition() [1/2]
virtual QCString TranslatorLatvian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 854 of file translator_lv.h.
    {
      return "Pcnosacjums";
    }
trPostcondition() [2/2]
virtual QCString TranslatorLatvian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 854 of file translator_lv.h.
    {
      return "Pcnosacjums";
    }
trPrecondition() [1/2]
virtual QCString TranslatorLatvian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 849 of file translator_lv.h.
    {
      return "Pirmsnosacjums";
    }
trPrecondition() [2/2]
virtual QCString TranslatorLatvian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 849 of file translator_lv.h.
    {
      return "Pirmsnosacjums";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorLatvian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 933 of file translator_lv.h.
    {
      return "Privtie atribti";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorLatvian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 933 of file translator_lv.h.
    {
      return "Privtie atribti";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorLatvian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 649 of file translator_lv.h.
    { return "Privts elementa funkcijas"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorLatvian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 649 of file translator_lv.h.
    { return "Privts elementa funkcijas"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorLatvian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 651 of file translator_lv.h.
    { return "Privts spraugas"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorLatvian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 651 of file translator_lv.h.
    { return "Privts spraugas"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorLatvian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 929 of file translator_lv.h.
    {
      return "Privtie tipi";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorLatvian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 929 of file translator_lv.h.
    {
      return "Privtie tipi";
    }
trProperties() [1/2]
virtual QCString TranslatorLatvian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1085 of file translator_lv.h.
    {
      return "Rekvizti";
    }
trProperties() [2/2]
virtual QCString TranslatorLatvian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1085 of file translator_lv.h.
    {
      return "Rekvizti";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorLatvian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1090 of file translator_lv.h.
    {
      return "Rekviztu dokumentcija";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorLatvian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1090 of file translator_lv.h.
    {
      return "Rekviztu dokumentcija";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorLatvian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 921 of file translator_lv.h.
    {
      return "Aizsargtie atribti";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorLatvian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 921 of file translator_lv.h.
    {
      return "Aizsargtie atribti";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorLatvian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 643 of file translator_lv.h.
    { return "Aizsargts elementa funkcijas"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorLatvian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 643 of file translator_lv.h.
    { return "Aizsargts elementa funkcijas"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorLatvian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_lv.h.
    { return "Aizsargts spraugas"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorLatvian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_lv.h.
    { return "Aizsargts spraugas"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorLatvian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 917 of file translator_lv.h.
    {
      return "Aizsargtie tipi";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorLatvian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 917 of file translator_lv.h.
    {
      return "Aizsargtie tipi";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorLatvian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1921 of file translator_lv.h.
    {
      return "Nodroina kategorija @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorLatvian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1921 of file translator_lv.h.
    {
      return "Nodroina kategorija @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorLatvian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu lauki";
      }
      else
      {
        return "Publiskie atribti";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorLatvian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu lauki";
      }
      else
      {
        return "Publiskie atribti";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorLatvian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 635 of file translator_lv.h.
    { return "Publisks elementa funkcijas"; }
trPublicMembers() [2/2]
virtual QCString TranslatorLatvian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 635 of file translator_lv.h.
    { return "Publisks elementa funkcijas"; }
trPublicSlots() [1/2]
virtual QCString TranslatorLatvian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 637 of file translator_lv.h.
    { return "Publisks spraugas"; }
trPublicSlots() [2/2]
virtual QCString TranslatorLatvian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 637 of file translator_lv.h.
    { return "Publisks spraugas"; }
trPublicTypes() [1/2]
virtual QCString TranslatorLatvian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 898 of file translator_lv.h.
    {
      return "Publiskie tipi";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorLatvian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 898 of file translator_lv.h.
    {
      return "Publiskie tipi";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorLatvian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 961 of file translator_lv.h.
    {
      return "Atsauces no";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorLatvian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 961 of file translator_lv.h.
    {
      return "Atsauces no";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorLatvian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 427 of file translator_lv.h.
    { return "Rokasgrmata"; }
trReferenceManual() [2/2]
virtual QCString TranslatorLatvian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 427 of file translator_lv.h.
    { return "Rokasgrmata"; }
trReferences() [1/2]
virtual QCString TranslatorLatvian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1292 of file translator_lv.h.
    {
      return "Atsauces";
    }
trReferences() [2/2]
virtual QCString TranslatorLatvian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1292 of file translator_lv.h.
    {
      return "Atsauces";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorLatvian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 700 of file translator_lv.h.
    {
      return "Primplementts no "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorLatvian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 700 of file translator_lv.h.
    {
      return "Primplementts no "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorLatvian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 708 of file translator_lv.h.
    {
      return "Primplementts "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorLatvian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 708 of file translator_lv.h.
    {
      return "Primplementts "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorLatvian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 590 of file translator_lv.h.
    { return "Draugu un saistto funkciju dokumentcija"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorLatvian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 590 of file translator_lv.h.
    { return "Draugu un saistto funkciju dokumentcija"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorLatvian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 95 of file translator_lv.h.
    { return "Saistts funkcijas"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorLatvian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 95 of file translator_lv.h.
    { return "Saistts funkcijas"; }
trRelatedPages() [1/2]
virtual QCString TranslatorLatvian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 229 of file translator_lv.h.
    { return "Saistts lapas"; }
trRelatedPages() [2/2]
virtual QCString TranslatorLatvian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 229 of file translator_lv.h.
    { return "Saistts lapas"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorLatvian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 343 of file translator_lv.h.
    { return "Here is a list of all related documentation pages:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorLatvian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 343 of file translator_lv.h.
    { return "Here is a list of all related documentation pages:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorLatvian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 99 of file translator_lv.h.
    { return "(s nav elementu funkcijas.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorLatvian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 99 of file translator_lv.h.
    { return "(s nav elementu funkcijas.)"; }
trRemarks() [1/2]
virtual QCString TranslatorLatvian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 965 of file translator_lv.h.
    {
      return "Piebildes";
    }
trRemarks() [2/2]
virtual QCString TranslatorLatvian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 965 of file translator_lv.h.
    {
      return "Piebildes";
    }
trReturns() [1/2]
virtual QCString TranslatorLatvian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 541 of file translator_lv.h.
    { return "Atgrie"; }
trReturns() [2/2]
virtual QCString TranslatorLatvian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 541 of file translator_lv.h.
    { return "Atgrie"; }
trReturnValues() [1/2]
virtual QCString TranslatorLatvian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 783 of file translator_lv.h.
    { return "Atgrieams vrtbas"; }
trReturnValues() [2/2]
virtual QCString TranslatorLatvian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 783 of file translator_lv.h.
    { return "Atgrieams vrtbas"; }
trRTFansicp() [1/2]
virtual QCString TranslatorLatvian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1176 of file translator_lv.h.
    {
      return "1257";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorLatvian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1176 of file translator_lv.h.
    {
      return "1257";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorLatvian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1185 of file translator_lv.h.
    {
      return "186";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorLatvian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1185 of file translator_lv.h.
    {
      return "186";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorLatvian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1191 of file translator_lv.h.
    {
      return "Indekss";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorLatvian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1191 of file translator_lv.h.
    {
      return "Indekss";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorLatvian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1324 of file translator_lv.h.
    {
      return "Satura rdtjs";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorLatvian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1324 of file translator_lv.h.
    {
      return "Satura rdtjs";
    }
trSearch() [1/2]
virtual QCString TranslatorLatvian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 237 of file translator_lv.h.
    { return "Meklt"; }
trSearch() [2/2]
virtual QCString TranslatorLatvian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 237 of file translator_lv.h.
    { return "Meklt"; }
trSearching() [1/2]
virtual QCString TranslatorLatvian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1766 of file translator_lv.h.
    {
      return "Mekl...";
    }
trSearching() [2/2]
virtual QCString TranslatorLatvian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1766 of file translator_lv.h.
    {
      return "Mekl...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorLatvian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1456 of file translator_lv.h.
    {
      return "Atbilst mekltajam:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorLatvian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1456 of file translator_lv.h.
    {
      return "Atbilst mekltajam:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorLatvian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1437 of file translator_lv.h.
    {
      if (numDocuments==0)
      {
        return "Netika atrasts neviens dokuments.";
      }
      else if (numDocuments==1)
      {
        return "Atrasts <b>1</b> dokuments.";
      }
      else
      {
        return "Atrasti <b>$num</b> Dokumenti. "
               "Skum attlo tos, kas atbilst vispreczk.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorLatvian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1437 of file translator_lv.h.
    {
      if (numDocuments==0)
      {
        return "Netika atrasts neviens dokuments.";
      }
      else if (numDocuments==1)
      {
        return "Atrasts <b>1</b> dokuments.";
      }
      else
      {
        return "Atrasti <b>$num</b> Dokumenti. "
               "Skum attlo tos, kas atbilst vispreczk.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorLatvian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1425 of file translator_lv.h.
    {
      return "Meklanas rezultti";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorLatvian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1425 of file translator_lv.h.
    {
      return "Meklanas rezultti";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorLatvian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 545 of file translator_lv.h.
    { return "Skatties ar"; }
trSeeAlso() [2/2]
virtual QCString TranslatorLatvian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 545 of file translator_lv.h.
    { return "Skatties ar"; }
trSignals() [1/2]
virtual QCString TranslatorLatvian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 639 of file translator_lv.h.
    { return "Signli"; }
trSignals() [2/2]
virtual QCString TranslatorLatvian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 639 of file translator_lv.h.
    { return "Signli"; }
trSince() [1/2]
virtual QCString TranslatorLatvian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 978 of file translator_lv.h.
    {
      return "Kop";
    }
trSince() [2/2]
virtual QCString TranslatorLatvian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 978 of file translator_lv.h.
    {
      return "Kop";
    }
trSourceFile() [1/2]
virtual QCString TranslatorLatvian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1467 of file translator_lv.h.
    {
      return filename + " pirmkoda fails";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorLatvian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1467 of file translator_lv.h.
    {
      return filename + " pirmkoda fails";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorLatvian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1396 of file translator_lv.h.
    {
      return "Statiskie pakas atribti";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorLatvian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1396 of file translator_lv.h.
    {
      return "Statiskie pakas atribti";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorLatvian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1382 of file translator_lv.h.
    {
      return "Statisks pakas funkcijas";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorLatvian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1382 of file translator_lv.h.
    {
      return "Statisks pakas funkcijas";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorLatvian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_lv.h.
    {
      return "Statiskie privtie atribti";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorLatvian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_lv.h.
    {
      return "Statiskie privtie atribti";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorLatvian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_lv.h.
    { return "Statisks privts elementa funkcijas"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorLatvian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_lv.h.
    { return "Statisks privts elementa funkcijas"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorLatvian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 925 of file translator_lv.h.
    {
      return "Statiskie aizsargtie atribti";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorLatvian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 925 of file translator_lv.h.
    {
      return "Statiskie aizsargtie atribti";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorLatvian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 647 of file translator_lv.h.
    { return "Statisks aizsargts elementa funkcijas"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorLatvian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 647 of file translator_lv.h.
    { return "Statisks aizsargts elementa funkcijas"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorLatvian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 913 of file translator_lv.h.
    {
      return "Statiskie publiskie atribti";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorLatvian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 913 of file translator_lv.h.
    {
      return "Statiskie publiskie atribti";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorLatvian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 641 of file translator_lv.h.
    { return "Statisks publisks elementa funkcijas"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorLatvian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 641 of file translator_lv.h.
    { return "Statisks publisks elementa funkcijas"; }
trSubprogram() [1/2]
virtual QCString TranslatorLatvian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1730 of file translator_lv.h.
    {
      QCString result((first_capital ? "Apakprogramma" : "apakprogramma"));
      if (!singular) result+="s";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorLatvian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1730 of file translator_lv.h.
    {
      QCString result((first_capital ? "Apakprogramma" : "apakprogramma"));
      if (!singular) result+="s";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorLatvian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1602 of file translator_lv.h.
    { return "Funkcijas/Apakrutnas dokumentcija"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorLatvian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1602 of file translator_lv.h.
    { return "Funkcijas/Apakrutnas dokumentcija"; }
trSubprograms() [1/2]
virtual QCString TranslatorLatvian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1596 of file translator_lv.h.
    { return "Funkcijas/Apakrutnas"; }
trSubprograms() [2/2]
virtual QCString TranslatorLatvian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1596 of file translator_lv.h.
    { return "Funkcijas/Apakrutnas"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorLatvian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1872 of file translator_lv.h.
    { return "Sagataves parametri"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorLatvian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1872 of file translator_lv.h.
    { return "Sagataves parametri"; }
trTest() [1/2]
virtual QCString TranslatorLatvian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1070 of file translator_lv.h.
    {
      return "Testi";
    }
trTest() [2/2]
virtual QCString TranslatorLatvian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1070 of file translator_lv.h.
    {
      return "Testi";
    }
trTestList() [1/2]
virtual QCString TranslatorLatvian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1075 of file translator_lv.h.
    {
      return "Testu saraksts";
    }
trTestList() [2/2]
virtual QCString TranslatorLatvian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1075 of file translator_lv.h.
    {
      return "Testu saraksts";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorLatvian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 144 of file translator_lv.h.
    { return "is ir pilns elementu saraksts klasei "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorLatvian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 144 of file translator_lv.h.
    { return "is ir pilns elementu saraksts klasei "; }
trTodo() [1/2]
virtual QCString TranslatorLatvian::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 947 of file translator_lv.h.
    {
      return "Jizdara";
    }
trTodo() [2/2]
virtual QCString TranslatorLatvian::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 947 of file translator_lv.h.
    {
      return "Jizdara";
    }
trTodoList() [1/2]
virtual QCString TranslatorLatvian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 952 of file translator_lv.h.
    {
      return "Darmo darbu saraksts";
    }
trTodoList() [2/2]
virtual QCString TranslatorLatvian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 952 of file translator_lv.h.
    {
      return "Darmo darbu saraksts";
    }
trType() [1/2]
virtual QCString TranslatorLatvian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1719 of file translator_lv.h.
    {
      QCString result((first_capital ? "Tip" : "tip"));
      if (singular) result+="s"; else result+="i";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorLatvian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1719 of file translator_lv.h.
    {
      QCString result((first_capital ? "Tip" : "tip"));
      if (singular) result+="s"; else result+="i";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorLatvian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1738 of file translator_lv.h.
    {
      return "Tipa ierobeojumi";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorLatvian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1738 of file translator_lv.h.
    {
      return "Tipa ierobeojumi";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorLatvian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 475 of file translator_lv.h.
    { return "Typedef dokumentcija"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorLatvian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 475 of file translator_lv.h.
    { return "Typedef dokumentcija"; }
trTypedefs() [1/2]
virtual QCString TranslatorLatvian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 439 of file translator_lv.h.
    { return "Typedefs"; }
trTypedefs() [2/2]
virtual QCString TranslatorLatvian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 439 of file translator_lv.h.
    { return "Typedefs"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorLatvian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1590 of file translator_lv.h.
    { return "Datu tipa dokumentcija"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorLatvian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1590 of file translator_lv.h.
    { return "Datu tipa dokumentcija"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorLatvian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 493 of file translator_lv.h.
    { return "Maingo dokumentcija"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorLatvian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 493 of file translator_lv.h.
    { return "Maingo dokumentcija"; }
trVariables() [1/2]
virtual QCString TranslatorLatvian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 457 of file translator_lv.h.
    { return "Maingie"; }
trVariables() [2/2]
virtual QCString TranslatorLatvian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 457 of file translator_lv.h.
    { return "Maingie"; }
trVersion() [1/2]
virtual QCString TranslatorLatvian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 533 of file translator_lv.h.
    { return "Versija"; }
trVersion() [2/2]
virtual QCString TranslatorLatvian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 533 of file translator_lv.h.
    { return "Versija"; }
trWarning() [1/2]
virtual QCString TranslatorLatvian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 529 of file translator_lv.h.
    { return "Brdinjums"; }
trWarning() [2/2]
virtual QCString TranslatorLatvian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 529 of file translator_lv.h.
    { return "Brdinjums"; }
trWriteList() [1/2]
virtual QCString TranslatorLatvian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 659 of file translator_lv.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", un ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorLatvian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 659 of file translator_lv.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", un ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_lv.h
doxygen/src/translator_lv.h