vhdl::parser::VhdlErrorHandler Class Reference
#include <VhdlParserErrorHandler.hpp>
Public Member Functions
VhdlErrorHandler (const char *fileName)
virtual void handleUnexpectedToken (int expectedKind, const JJString &expectedToken, Token *actual, VhdlParser *parser)
virtual void handleParseError (Token *last, Token *unexpected, const JJSimpleString &production, VhdlParser *parser)
virtual void handleOtherError (const JJString &message, VhdlParser *parser)
VhdlErrorHandler (const char *fileName)
virtual void handleUnexpectedToken (int expectedKind, const JJString &expectedToken, Token *actual, VhdlParser *parser)
virtual void handleParseError (Token *last, Token *unexpected, const JJSimpleString &production, VhdlParser *parser)
virtual void handleOtherError (const JJString &message, VhdlParser *parser)
Private Attributes
QCString m_fileName
Additional Inherited Members
Detailed Description
Definition at line 16 of file VhdlParserErrorHandler.hpp.
Constructor & Destructor Documentation
VhdlErrorHandler() [1/2]
vhdl::parser::VhdlErrorHandler::VhdlErrorHandler (const char * fileName) [inline]
Definition at line 19 of file VhdlParserErrorHandler.hpp.
: m_fileName(fileName) {}
VhdlErrorHandler() [2/2]
vhdl::parser::VhdlErrorHandler::VhdlErrorHandler (const char * fileName) [inline]
Definition at line 19 of file VhdlParserErrorHandler.hpp.
: m_fileName(fileName) {}
Member Function Documentation
handleOtherError() [1/2]
virtual void vhdl::parser::VhdlErrorHandler::handleOtherError (const JJString & message, VhdlParser * parser) [inline], [virtual]
Reimplemented from vhdl::parser::ErrorHandler.
Definition at line 35 of file VhdlParserErrorHandler.hpp.
    {
      warn(m_fileName, -1, "unexpected error: '%s'", (char*)message.c_str());
      error_count++;
      throw std::exception();
    }
References vhdl::parser::ErrorHandler::error_count, m_fileName, and warn().
handleOtherError() [2/2]
virtual void vhdl::parser::VhdlErrorHandler::handleOtherError (const JJString & message, VhdlParser * parser) [inline], [virtual]
Reimplemented from vhdl::parser::ErrorHandler.
Definition at line 35 of file VhdlParserErrorHandler.hpp.
    {
      warn(m_fileName, -1, "unexpected error: '%s'", (char*)message.c_str());
      error_count++;
      throw std::exception();
    }
References vhdl::parser::ErrorHandler::error_count, m_fileName, and warn().
handleParseError() [1/2]
virtual void vhdl::parser::VhdlErrorHandler::handleParseError (Token * last, Token * unexpected, const JJSimpleString & production, VhdlParser * parser) [inline], [virtual]
Reimplemented from vhdl::parser::ErrorHandler.
Definition at line 28 of file VhdlParserErrorHandler.hpp.
    {
      warn(m_fileName,last->beginLine,"unexpected token: '%s'", unexpected->image.data());
      error_count++;
      throw std::exception();
    }
References vhdl::parser::Token::beginLine, vhdl::parser::ErrorHandler::error_count, vhdl::parser::Token::image, m_fileName, and warn().
handleParseError() [2/2]
virtual void vhdl::parser::VhdlErrorHandler::handleParseError (Token * last, Token * unexpected, const JJSimpleString & production, VhdlParser * parser) [inline], [virtual]
Reimplemented from vhdl::parser::ErrorHandler.
Definition at line 28 of file VhdlParserErrorHandler.hpp.
    {
      warn(m_fileName,last->beginLine,"unexpected token: '%s'", unexpected->image.data());
      error_count++;
      throw std::exception();
    }
References vhdl::parser::Token::beginLine, vhdl::parser::ErrorHandler::error_count, vhdl::parser::Token::image, m_fileName, and warn().
handleUnexpectedToken() [1/2]
virtual void vhdl::parser::VhdlErrorHandler::handleUnexpectedToken (int expectedKind, const JJString & expectedToken, Token * actual, VhdlParser * parser) [inline], [virtual]
Reimplemented from vhdl::parser::ErrorHandler.
Definition at line 21 of file VhdlParserErrorHandler.hpp.
    {
      warn(m_fileName,actual->beginLine,"syntax error '%s'",actual->image.data());
      error_count++;
      throw std::exception();
    }
References vhdl::parser::Token::beginLine, vhdl::parser::ErrorHandler::error_count, vhdl::parser::Token::image, m_fileName, and warn().
handleUnexpectedToken() [2/2]
virtual void vhdl::parser::VhdlErrorHandler::handleUnexpectedToken (int expectedKind, const JJString & expectedToken, Token * actual, VhdlParser * parser) [inline], [virtual]
Reimplemented from vhdl::parser::ErrorHandler.
Definition at line 21 of file VhdlParserErrorHandler.hpp.
    {
      warn(m_fileName,actual->beginLine,"syntax error '%s'",actual->image.data());
      error_count++;
      throw std::exception();
    }
References vhdl::parser::Token::beginLine, vhdl::parser::ErrorHandler::error_count, vhdl::parser::Token::image, m_fileName, and warn().
Member Data Documentation
m_fileName
QCString vhdl::parser::VhdlErrorHandler::m_fileName [private]
Definition at line 43 of file VhdlParserErrorHandler.hpp.
Referenced by handleOtherError(), handleParseError(), and handleUnexpectedToken().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/vhdlparser/VhdlParserErrorHandler.hpp
doxygen/vhdlparser/VhdlParserErrorHandler.hpp