MemberName Class Reference
#include <membername.h>
Public Types
using Ptr = std::unique_ptr< MemberDef >
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
using reverse_iterator = typename Vec::reverse_iterator
using const_reverse_iterator = typename Vec::const_reverse_iterator
using Ptr = std::unique_ptr< MemberDef >
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
using reverse_iterator = typename Vec::reverse_iterator
using const_reverse_iterator = typename Vec::const_reverse_iterator
Public Member Functions
MemberName (const QCString &name)
QCString memberName () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
bool empty () const
size_t size () const
Ptr & back ()
const Ptr & back () const
Ptr & front ()
const Ptr & front () const
void push_back (Ptr &&p)
MemberName (const QCString &name)
QCString memberName () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
bool empty () const
size_t size () const
Ptr & back ()
const Ptr & back () const
Ptr & front ()
const Ptr & front () const
void push_back (Ptr &&p)
Private Attributes
QCString m_name
Vec m_members
Detailed Description
Definition at line 24 of file membername.h.
Member Typedef Documentation
const_iterator [1/2]
using MemberName::const_iterator = typename Vec::const_iterator
Definition at line 30 of file membername.h.
const_iterator [2/2]
using MemberName::const_iterator = typename Vec::const_iterator
Definition at line 30 of file membername.h.
const_reverse_iterator [1/2]
using MemberName::const_reverse_iterator = typename Vec::const_reverse_iterator
Definition at line 32 of file membername.h.
const_reverse_iterator [2/2]
using MemberName::const_reverse_iterator = typename Vec::const_reverse_iterator
Definition at line 32 of file membername.h.
iterator [1/2]
using MemberName::iterator = typename Vec::iterator
Definition at line 29 of file membername.h.
iterator [2/2]
using MemberName::iterator = typename Vec::iterator
Definition at line 29 of file membername.h.
Ptr [1/2]
using MemberName::Ptr = std::unique_ptr<MemberDef>
Definition at line 27 of file membername.h.
Ptr [2/2]
using MemberName::Ptr = std::unique_ptr<MemberDef>
Definition at line 27 of file membername.h.
reverse_iterator [1/2]
using MemberName::reverse_iterator = typename Vec::reverse_iterator
Definition at line 31 of file membername.h.
reverse_iterator [2/2]
using MemberName::reverse_iterator = typename Vec::reverse_iterator
Definition at line 31 of file membername.h.
Vec [1/2]
using MemberName::Vec = std::vector<Ptr>
Definition at line 28 of file membername.h.
Vec [2/2]
using MemberName::Vec = std::vector<Ptr>
Definition at line 28 of file membername.h.
Constructor & Destructor Documentation
MemberName() [1/2]
MemberName::MemberName (const QCString & name) [inline]
Definition at line 34 of file membername.h.
: m_name(name) {}
MemberName() [2/2]
MemberName::MemberName (const QCString & name) [inline]
Definition at line 34 of file membername.h.
: m_name(name) {}
Member Function Documentation
back() [1/4]
Ptr & MemberName::back () [inline]
Definition at line 49 of file membername.h.
{ return m_members.back(); }
References m_members.
back() [2/4]
Ptr & MemberName::back () [inline]
Definition at line 49 of file membername.h.
{ return m_members.back(); }
References m_members.
back() [3/4]
const Ptr & MemberName::back () const [inline]
Definition at line 50 of file membername.h.
{ return m_members.back(); }
References m_members.
back() [4/4]
const Ptr & MemberName::back () const [inline]
Definition at line 50 of file membername.h.
{ return m_members.back(); }
References m_members.
begin() [1/4]
iterator MemberName::begin () [inline]
Definition at line 37 of file membername.h.
{ return m_members.begin(); }
References m_members.
Referenced by addOverloaded().
begin() [2/4]
iterator MemberName::begin () [inline]
Definition at line 37 of file membername.h.
{ return m_members.begin(); }
References m_members.
begin() [3/4]
const_iterator MemberName::begin () const [inline]
Definition at line 39 of file membername.h.
{ return m_members.begin(); }
References m_members.
begin() [4/4]
const_iterator MemberName::begin () const [inline]
Definition at line 39 of file membername.h.
{ return m_members.begin(); }
References m_members.
cbegin() [1/2]
const_iterator MemberName::cbegin () const [inline]
Definition at line 41 of file membername.h.
{ return m_members.cbegin(); }
References m_members.
cbegin() [2/2]
const_iterator MemberName::cbegin () const [inline]
Definition at line 41 of file membername.h.
{ return m_members.cbegin(); }
References m_members.
cend() [1/2]
const_iterator MemberName::cend () const [inline]
Definition at line 42 of file membername.h.
{ return m_members.cend(); }
References m_members.
cend() [2/2]
const_iterator MemberName::cend () const [inline]
Definition at line 42 of file membername.h.
{ return m_members.cend(); }
References m_members.
crbegin() [1/2]
const_reverse_iterator MemberName::crbegin () const [inline]
Definition at line 45 of file membername.h.
{ return m_members.crbegin(); }
References m_members.
crbegin() [2/2]
const_reverse_iterator MemberName::crbegin () const [inline]
Definition at line 45 of file membername.h.
{ return m_members.crbegin(); }
References m_members.
crend() [1/2]
const_reverse_iterator MemberName::crend () const [inline]
Definition at line 46 of file membername.h.
{ return m_members.crend(); }
References m_members.
crend() [2/2]
const_reverse_iterator MemberName::crend () const [inline]
Definition at line 46 of file membername.h.
{ return m_members.crend(); }
References m_members.
empty() [1/2]
bool MemberName::empty () const [inline]
Definition at line 47 of file membername.h.
{ return m_members.empty(); }
References m_members.
empty() [2/2]
bool MemberName::empty () const [inline]
Definition at line 47 of file membername.h.
{ return m_members.empty(); }
References m_members.
end() [1/4]
iterator MemberName::end () [inline]
Definition at line 38 of file membername.h.
{ return m_members.end(); }
References m_members.
Referenced by addOverloaded().
end() [2/4]
iterator MemberName::end () [inline]
Definition at line 38 of file membername.h.
{ return m_members.end(); }
References m_members.
end() [3/4]
const_iterator MemberName::end () const [inline]
Definition at line 40 of file membername.h.
{ return m_members.end(); }
References m_members.
end() [4/4]
const_iterator MemberName::end () const [inline]
Definition at line 40 of file membername.h.
{ return m_members.end(); }
References m_members.
front() [1/4]
Ptr & MemberName::front () [inline]
Definition at line 51 of file membername.h.
{ return m_members.front(); }
References m_members.
Referenced by addOverloaded(), setCallContextForVar(), and writeObjCMethodCall().
front() [2/4]
Ptr & MemberName::front () [inline]
Definition at line 51 of file membername.h.
{ return m_members.front(); }
References m_members.
front() [3/4]
const Ptr & MemberName::front () const [inline]
Definition at line 52 of file membername.h.
{ return m_members.front(); }
References m_members.
front() [4/4]
const Ptr & MemberName::front () const [inline]
Definition at line 52 of file membername.h.
{ return m_members.front(); }
References m_members.
memberName() [1/2]
QCString MemberName::memberName () const [inline]
Definition at line 35 of file membername.h.
{ return m_name; }
References m_name.
memberName() [2/2]
QCString MemberName::memberName () const [inline]
Definition at line 35 of file membername.h.
{ return m_name; }
References m_name.
push_back() [1/2]
void MemberName::push_back (Ptr && p) [inline]
Definition at line 53 of file membername.h.
{ m_members.push_back(std::move(p)); }
References m_members, and p.
Referenced by addEnumValuesToEnums(), addInstance(), addLocalObjCMethod(), addMemberSpecialization(), ClassDefImpl::addMembersToTemplateInstance(), addOverloaded(), addVariableToClass(), addVariableToFile(), buildDefineList(), findDefineDocumentation(), findEnums(), findMember(), findUsingDeclImports(), NamespaceDefImpl::insertMember(), and ClassDefImpl::mergeCategory().
push_back() [2/2]
void MemberName::push_back (Ptr && p) [inline]
Definition at line 53 of file membername.h.
{ m_members.push_back(std::move(p)); }
References m_members, and p.
rbegin() [1/2]
reverse_iterator MemberName::rbegin () [inline]
Definition at line 43 of file membername.h.
{ return m_members.rbegin(); }
References m_members.
Referenced by getDefsOld().
rbegin() [2/2]
reverse_iterator MemberName::rbegin () [inline]
Definition at line 43 of file membername.h.
{ return m_members.rbegin(); }
References m_members.
rend() [1/2]
reverse_iterator MemberName::rend () [inline]
Definition at line 44 of file membername.h.
{ return m_members.rend(); }
References m_members.
Referenced by getDefsOld().
rend() [2/2]
reverse_iterator MemberName::rend () [inline]
Definition at line 44 of file membername.h.
{ return m_members.rend(); }
References m_members.
size() [1/2]
size_t MemberName::size () const [inline]
Definition at line 48 of file membername.h.
{ return m_members.size(); }
References m_members.
Referenced by addOverloaded(), findMember(), setCallContextForVar(), and writeObjCMethodCall().
size() [2/2]
size_t MemberName::size () const [inline]
Definition at line 48 of file membername.h.
{ return m_members.size(); }
References m_members.
Member Data Documentation
m_members
Vec MemberName::m_members [private]
Definition at line 57 of file membername.h.
Referenced by back(), begin(), cbegin(), cend(), crbegin(), crend(), empty(), end(), front(), push_back(), rbegin(), rend(), and size().
m_name
QCString MemberName::m_name [private]
Definition at line 56 of file membername.h.
Referenced by memberName().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/membername.h
doxygen/src/membername.h