FilterDefault Class Reference
The implementation of the `default` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &arg)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &arg)
Detailed Description
The implementation of the `default` filter.
Definition at line 991 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterDefault::apply (const TemplateVariant & v, const TemplateVariant & arg) [inline], [static]
Definition at line 994 of file template.cpp.
    {
      if (!v.isValid())
      {
        return arg;
      }
      else if (v.isString() && v.toString().isEmpty())
      {
        return arg;
      }
      else
      {
        return v;
      }
    }
References QCString::isEmpty(), TemplateVariant::isString(), TemplateVariant::isValid(), and TemplateVariant::toString().
apply() [2/2]
static TemplateVariant FilterDefault::apply (const TemplateVariant & v, const TemplateVariant & arg) [inline], [static]
Definition at line 994 of file template.cpp.
    {
      if (!v.isValid())
      {
        return arg;
      }
      else if (v.isString() && v.toString().isEmpty())
      {
        return arg;
      }
      else
      {
        return v;
      }
    }
References QCString::isEmpty(), TemplateVariant::isString(), TemplateVariant::isValid(), and TemplateVariant::toString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp