DotGraph Class Reference
#include <dotgraph.h>
Public Member Functions
DotGraph ()
virtual ~DotGraph ()=default
DotGraph ()
virtual ~DotGraph ()=default
Protected Member Functions
int getNextNodeNumber ()
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
virtual QCString getBaseName () const =0
virtual QCString absMapName () const
virtual QCString getMapLabel () const =0
virtual QCString getImgAltText () const
virtual void computeTheGraph ()=0
QCString absBaseName () const
QCString absDotName () const
QCString imgName () const
QCString absImgName () const
QCString relImgName () const
int getNextNodeNumber ()
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
virtual QCString getBaseName () const =0
virtual QCString absMapName () const
virtual QCString getMapLabel () const =0
virtual QCString getImgAltText () const
virtual void computeTheGraph ()=0
QCString absBaseName () const
QCString absDotName () const
QCString imgName () const
QCString absImgName () const
QCString relImgName () const
Static Protected Member Functions
static void writeGraphHeader (TextStream &t, const QCString &title=QCString())
static void writeGraphFooter (TextStream &t)
static void computeGraph (DotNode *root, GraphType gt, GraphOutputFormat format, const QCString &rank, bool renderParents, bool backArrows, const QCString &title, QCString &graphStr)
static void writeGraphHeader (TextStream &t, const QCString &title=QCString())
static void writeGraphFooter (TextStream &t)
static void computeGraph (DotNode *root, GraphType gt, GraphOutputFormat format, const QCString &rank, bool renderParents, bool backArrows, const QCString &title, QCString &graphStr)
Protected Attributes
GraphOutputFormat m_graphFormat = GOF_BITMAP
EmbeddedOutputFormat m_textFormat = EOF_Html
Dir m_dir
QCString m_fileName
QCString m_relPath
bool m_generateImageMap = false
int m_graphId = 0
QCString m_absPath
QCString m_baseName
QCString m_theGraph
bool m_regenerate = false
bool m_doNotAddImageToIndex = false
bool m_noDivTag = false
bool m_zoomable = true
bool m_urlOnly = false
Private Member Functions
DotGraph (const DotGraph &)
DotGraph & operator= (const DotGraph &)
bool prepareDotFile ()
void generateCode (TextStream &t)
DotGraph (const DotGraph &)
DotGraph & operator= (const DotGraph &)
bool prepareDotFile ()
void generateCode (TextStream &t)
Private Attributes
int m_curNodeNumber = 0
Detailed Description
A dot graph
Definition at line 33 of file dotgraph.h.
Constructor & Destructor Documentation
DotGraph() [1/4]
DotGraph::DotGraph () [inline]
Definition at line 36 of file dotgraph.h.
               : m_doNotAddImageToIndex(FALSE), m_noDivTag(FALSE),
                 m_zoomable(TRUE), m_urlOnly(FALSE) {}
 DotGraph() [1/2]
virtual DotGraph::~DotGraph () [virtual], [default]
DotGraph() [2/4]
DotGraph::DotGraph (const DotGraph &) [private]
DotGraph() [3/4]
DotGraph::DotGraph () [inline]
Definition at line 36 of file dotgraph.h.
               : m_doNotAddImageToIndex(FALSE), m_noDivTag(FALSE),
                 m_zoomable(TRUE), m_urlOnly(FALSE) {}
 DotGraph() [2/2]
virtual DotGraph::~DotGraph () [virtual], [default]
DotGraph() [4/4]
DotGraph::DotGraph (const DotGraph &) [private]
Member Function Documentation
absBaseName() [1/2]
QCString DotGraph::absBaseName () const [inline], [protected]
Definition at line 73 of file dotgraph.h.
{ return m_absPath + m_baseName; }
References m_absPath, and m_baseName.
Referenced by generateCode(), prepareDotFile(), and DotLegendGraph::writeGraph().
absBaseName() [2/2]
QCString DotGraph::absBaseName () const [inline], [protected]
Definition at line 73 of file dotgraph.h.
{ return m_absPath + m_baseName; }
References m_absPath, and m_baseName.
absDotName() [1/2]
QCString DotGraph::absDotName () const [inline], [protected]
Definition at line 74 of file dotgraph.h.
{ return m_absPath + m_baseName + ".dot"; }
References m_absPath, and m_baseName.
Referenced by prepareDotFile().
absDotName() [2/2]
QCString DotGraph::absDotName () const [inline], [protected]
Definition at line 74 of file dotgraph.h.
{ return m_absPath + m_baseName + ".dot"; }
References m_absPath, and m_baseName.
absImgName() [1/2]
QCString DotGraph::absImgName () const [inline], [protected]
Definition at line 76 of file dotgraph.h.
{ return m_absPath + imgName(); }
References imgName(), and m_absPath.
Referenced by generateCode(), prepareDotFile(), and DotLegendGraph::writeGraph().
absImgName() [2/2]
QCString DotGraph::absImgName () const [inline], [protected]
Definition at line 76 of file dotgraph.h.
{ return m_absPath + imgName(); }
References imgName(), and m_absPath.
absMapName() [1/2]
virtual QCString DotGraph::absMapName () const [inline], [protected], [virtual]
Definition at line 67 of file dotgraph.h.
{ return m_absPath + m_baseName + ".map"; }
References m_absPath, and m_baseName.
Referenced by generateCode(), and prepareDotFile().
absMapName() [2/2]
virtual QCString DotGraph::absMapName () const [inline], [protected], [virtual]
Definition at line 67 of file dotgraph.h.
{ return m_absPath + m_baseName + ".map"; }
References m_absPath, and m_baseName.
computeGraph() [1/2]
void DotGraph::computeGraph (DotNode * root, GraphType gt, GraphOutputFormat format, const QCString & rank, bool renderParents, bool backArrows, const QCString & title, QCString & graphStr) [static], [protected]
Definition at line 306 of file dotgraph.cpp.
{
  //printf("computeMd5Signature\n");
  TextStream md5stream;
  writeGraphHeader(md5stream,title);
  if (!rank.isEmpty())
  {
    md5stream << " rankdir=\"" << rank << "\";\n";
  }
  root->clearWriteFlag();
  root->write(md5stream, gt, format, gt!=CallGraph && gt!=Dependency, TRUE, backArrows);
  if (renderParents)
  {
    for (const auto &pn : root->parents())
    {
      if (pn->isVisible())
      {
        const auto &children = pn->children();
        auto child_it = std::find(children.begin(),children.end(),root);
        size_t index = child_it - children.begin();
        root->writeArrow(md5stream, // stream
            gt, // graph type
            format, // output format
            pn, // child node
            &pn->edgeInfo()[index], // edge info
            FALSE, // topDown?
            backArrows // point back?
          );
      }
      pn->write(md5stream, // stream
                gt, // graph type
                format, // output format
                TRUE, // topDown?
                FALSE, // toChildren?
                backArrows // backward pointing arrows?
      );
    }
  }
  writeGraphFooter(md5stream);
  graphStr=md5stream.str();
}
References CallGraph, DotNode::clearWriteFlag(), Dependency, FALSE, QCString::isEmpty(), DotNode::parents(), TextStream::str(), TRUE, DotNode::write(), DotNode::writeArrow(), writeGraphFooter(), and writeGraphHeader().
Referenced by DotCallGraph::computeTheGraph(), DotClassGraph::computeTheGraph(), and DotInclDepGraph::computeTheGraph().
computeGraph() [2/2]
static void DotGraph::computeGraph (DotNode * root, GraphType gt, GraphOutputFormat format, const QCString & rank, bool renderParents, bool backArrows, const QCString & title, QCString & graphStr) [static], [protected]
computeTheGraph() [1/2]
virtual void DotGraph::computeTheGraph () [protected], [pure virtual]
Implemented in DotCallGraph, DotClassGraph, DotDirDeps, DotGfxHierarchyTable, DotGroupCollaboration, DotInclDepGraph, DotLegendGraph, DotCallGraph, DotClassGraph, DotDirDeps, DotGfxHierarchyTable, DotGroupCollaboration, DotInclDepGraph, and DotLegendGraph.
Referenced by writeGraph().
computeTheGraph() [2/2]
virtual void DotGraph::computeTheGraph () [protected], [pure virtual]
Implemented in DotCallGraph, DotClassGraph, DotDirDeps, DotGfxHierarchyTable, DotGroupCollaboration, DotInclDepGraph, DotLegendGraph, DotCallGraph, DotClassGraph, DotDirDeps, DotGfxHierarchyTable, DotGroupCollaboration, DotInclDepGraph, and DotLegendGraph.
generateCode() [1/2]
void DotGraph::generateCode (TextStream & t) [private]
Definition at line 212 of file dotgraph.cpp.
{
  QCString imgExt = getDotImageExtension();
  if (m_graphFormat==GOF_BITMAP && m_textFormat==EOF_DocBook)
  {
    t << "<para>\n";
    t << " <informalfigure>\n";
    t << " <mediaobject>\n";
    t << " <imageobject>\n";
    t << " <imagedata";
    t << " width=\"50%\" align=\"center\" valign=\"middle\" scalefit=\"0\" fileref=\"" << m_relPath << m_baseName << "." << imgExt << "\">";
    t << "</imagedata>\n";
    t << " </imageobject>\n";
    t << " </mediaobject>\n";
    t << " </informalfigure>\n";
    t << "</para>\n";
  }
  else if (m_graphFormat==GOF_BITMAP && m_generateImageMap) // produce HTML to include the image
  {
    if (imgExt=="svg") // add link to SVG file without map file
    {
      if (!m_noDivTag) t << "<div class=\"center\">";
      if (m_regenerate || !DotFilePatcher::writeSVGFigureLink(t,m_relPath,m_baseName,absImgName())) // need to patch the links in the generated SVG file
      {
        if (m_regenerate)
        {
          DotManager::instance()->
               createFilePatcher(absImgName())->
               addSVGConversion(m_relPath,FALSE,QCString(),m_zoomable,m_graphId);
        }
        int mapId = DotManager::instance()->
               createFilePatcher(m_fileName)->
               addSVGObject(m_baseName,absImgName(),m_relPath);
        t << "<!-- SVG " << mapId << " -->\n";
      }
      if (!m_noDivTag) t << "</div>\n";
    }
    else // add link to bitmap file with image map
    {
      if (!m_noDivTag) t << "<div class=\"center\">";
      t << "<img src=\"" << relImgName() << "\" border=\"0\" usemap=\"#" << correctId(getMapLabel()) << "\" alt=\"" << getImgAltText() << "\"/>";
      if (!m_noDivTag) t << "</div>";
      t << "\n";
      if (m_regenerate || !insertMapFile(t, absMapName(), m_relPath, correctId(getMapLabel())))
      {
        int mapId = DotManager::instance()->
          createFilePatcher(m_fileName)->
          addMap(absMapName(), m_relPath, m_urlOnly, QCString(), getMapLabel());
        t << "<!-- MAP " << mapId << " -->\n";
      }
    }
  }
  else if (m_graphFormat==GOF_EPS) // produce tex to include the .eps image
  {
    if (m_regenerate || !DotFilePatcher::writeVecGfxFigure(t,m_baseName,absBaseName()))
    {
      int figId = DotManager::instance()->
                  createFilePatcher(m_fileName)->
                  addFigure(m_baseName,absBaseName(),FALSE /*TRUE*/);
      t << "\n% FIG " << figId << "\n";
    }
  }
}
References absBaseName(), absImgName(), absMapName(), correctId(), EOF_DocBook, FALSE, getDotImageExtension(), getImgAltText(), getMapLabel(), GOF_BITMAP, GOF_EPS, insertMapFile(), DotManager::instance(), m_baseName, m_fileName, m_generateImageMap, m_graphFormat, m_graphId, m_noDivTag, m_regenerate, m_relPath, m_textFormat, m_urlOnly, m_zoomable, relImgName(), DotFilePatcher::writeSVGFigureLink(), and DotFilePatcher::writeVecGfxFigure().
Referenced by writeGraph().
generateCode() [2/2]
void DotGraph::generateCode (TextStream & t) [private]
getBaseName() [1/2]
virtual QCString DotGraph::getBaseName () const [protected], [pure virtual]
Implemented in DotCallGraph, DotClassGraph, DotDirDeps, DotGfxHierarchyTable, DotGroupCollaboration, DotInclDepGraph, DotLegendGraph, DotCallGraph, DotClassGraph, DotDirDeps, DotGfxHierarchyTable, DotGroupCollaboration, DotInclDepGraph, and DotLegendGraph.
Referenced by writeGraph().
getBaseName() [2/2]
virtual QCString DotGraph::getBaseName () const [protected], [pure virtual]
Implemented in DotCallGraph, DotClassGraph, DotDirDeps, DotGfxHierarchyTable, DotGroupCollaboration, DotInclDepGraph, DotLegendGraph, DotCallGraph, DotClassGraph, DotDirDeps, DotGfxHierarchyTable, DotGroupCollaboration, DotInclDepGraph, and DotLegendGraph.
getImgAltText() [1/2]
virtual QCString DotGraph::getImgAltText () const [inline], [protected], [virtual]
Reimplemented in DotClassGraph, DotDirDeps, DotClassGraph, and DotDirDeps.
Definition at line 69 of file dotgraph.h.
{ return ""; }
Referenced by generateCode().
getImgAltText() [2/2]
virtual QCString DotGraph::getImgAltText () const [inline], [protected], [virtual]
Reimplemented in DotClassGraph, DotDirDeps, DotClassGraph, and DotDirDeps.
Definition at line 69 of file dotgraph.h.
{ return ""; }
getMapLabel() [1/2]
virtual QCString DotGraph::getMapLabel () const [protected], [pure virtual]
Implemented in DotCallGraph, DotClassGraph, DotDirDeps, DotGfxHierarchyTable, DotGroupCollaboration, DotInclDepGraph, DotLegendGraph, DotCallGraph, DotClassGraph, DotDirDeps, DotGfxHierarchyTable, DotGroupCollaboration, DotInclDepGraph, and DotLegendGraph.
Referenced by generateCode().
getMapLabel() [2/2]
virtual QCString DotGraph::getMapLabel () const [protected], [pure virtual]
Implemented in DotCallGraph, DotClassGraph, DotDirDeps, DotGfxHierarchyTable, DotGroupCollaboration, DotInclDepGraph, DotLegendGraph, DotCallGraph, DotClassGraph, DotDirDeps, DotGfxHierarchyTable, DotGroupCollaboration, DotInclDepGraph, and DotLegendGraph.
getNextNodeNumber() [1/2]
int DotGraph::getNextNodeNumber () [inline], [protected]
returns node numbers. The Counter is reset by the constructor
Definition at line 42 of file dotgraph.h.
{ return ++m_curNodeNumber; }
References m_curNodeNumber.
Referenced by DotClassGraph::addClass(), DotGfxHierarchyTable::addClassList(), DotGroupCollaboration::addCollaborationMember(), DotGfxHierarchyTable::addHierarchy(), DotGroupCollaboration::buildGraph(), DotInclDepGraph::buildGraph(), DotCallGraph::buildGraph(), DotCallGraph::DotCallGraph(), DotClassGraph::DotClassGraph(), DotGroupCollaboration::DotGroupCollaboration(), and DotInclDepGraph::DotInclDepGraph().
getNextNodeNumber() [2/2]
int DotGraph::getNextNodeNumber () [inline], [protected]
returns node numbers. The Counter is reset by the constructor
Definition at line 42 of file dotgraph.h.
{ return ++m_curNodeNumber; }
References m_curNodeNumber.
imgName() [1/2]
QCString DotGraph::imgName () const [protected]
Definition at line 107 of file dotgraph.cpp.
{
  return m_baseName + ((m_graphFormat == GOF_BITMAP) ?
                      ("." + getDotImageExtension()) : (Config_getBool(USE_PDFLATEX) ? ".pdf" : ".eps"));
}
References Config_getBool, getDotImageExtension(), GOF_BITMAP, m_baseName, and m_graphFormat.
Referenced by absImgName(), relImgName(), and writeGraph().
imgName() [2/2]
QCString DotGraph::imgName () const [protected]
operator=() [1/2]
DotGraph & DotGraph::operator= (const DotGraph &) [private]
operator=() [2/2]
DotGraph & DotGraph::operator= (const DotGraph &) [private]
prepareDotFile() [1/2]
bool DotGraph::prepareDotFile () [private]
Definition at line 151 of file dotgraph.cpp.
{
  if (!m_dir.exists())
  {
    term("Output dir %s does not exist!\n", m_dir.path().c_str());
  }
  char sigStr[33];
  uchar md5_sig[16];
  // calculate md5
  MD5Buffer(m_theGraph.data(), m_theGraph.length(), md5_sig);
  // convert result to a string
  MD5SigToString(md5_sig, sigStr);
  // already queued files are processed again in case the output format has changed
  if (sameMd5Signature(absBaseName(), sigStr) &&
      deliverablesPresent(absImgName(),
                          m_graphFormat == GOF_BITMAP && m_generateImageMap ? absMapName() : QCString()
                         )
     )
  {
    // all needed files are there
    return FALSE;
  }
  // need to rebuild the image
  // write .dot file because image was new or has changed
  std::ofstream f(absDotName().str(),std::ofstream::out | std::ofstream::binary);
  if (!f.is_open())
  {
    err("Could not open file %s for writing\n",qPrint(absDotName()));
    return TRUE;
  }
  f << m_theGraph;
  f.close();
  if (m_graphFormat == GOF_BITMAP)
  {
    // run dot to create a bitmap image
    DotRunner * dotRun = DotManager::instance()->createRunner(absDotName(), sigStr);
    dotRun->addJob(Config_getEnumAsString(DOT_IMAGE_FORMAT), absImgName(), absDotName(), 1);
    if (m_generateImageMap) dotRun->addJob(MAP_CMD, absMapName(), absDotName(), 1);
  }
  else if (m_graphFormat == GOF_EPS)
  {
    // run dot to create a .eps image
    DotRunner *dotRun = DotManager::instance()->createRunner(absDotName(), sigStr);
    if (Config_getBool(USE_PDFLATEX))
    {
      dotRun->addJob("pdf",absImgName(),absDotName(),1);
    }
    else
    {
      dotRun->addJob("ps",absImgName(),absDotName(),1);
    }
  }
  return TRUE;
}
References absBaseName(), absDotName(), absImgName(), absMapName(), DotRunner::addJob(), Config_getBool, Config_getEnumAsString, DotManager::createRunner(), QCString::data(), deliverablesPresent(), err(), Dir::exists(), f, FALSE, GOF_BITMAP, GOF_EPS, DotManager::instance(), QCString::length(), m_dir, m_generateImageMap, m_graphFormat, m_theGraph, MAP_CMD, MD5Buffer(), MD5SigToString(), out, Dir::path(), qPrint(), sameMd5Signature(), term(), and TRUE.
Referenced by writeGraph().
prepareDotFile() [2/2]
bool DotGraph::prepareDotFile () [private]
relImgName() [1/2]
QCString DotGraph::relImgName () const [inline], [protected]
Definition at line 77 of file dotgraph.h.
{ return m_relPath + imgName(); }
References imgName(), and m_relPath.
Referenced by generateCode().
relImgName() [2/2]
QCString DotGraph::relImgName () const [inline], [protected]
Definition at line 77 of file dotgraph.h.
{ return m_relPath + imgName(); }
References imgName(), and m_relPath.
writeGraph() [1/2]
QCString DotGraph::writeGraph (TextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1) [protected]
Definition at line 115 of file dotgraph.cpp.
{
  m_graphFormat = gf;
  m_textFormat = ef;
  m_dir = Dir(path.str());
  m_fileName = fileName;
  m_relPath = relPath;
  m_generateImageMap = generateImageMap;
  m_graphId = graphId;
  m_absPath = m_dir.absPath() + "/";
  m_baseName = getBaseName();
  computeTheGraph();
  m_regenerate = prepareDotFile();
  if (!m_doNotAddImageToIndex)
  {
    std::lock_guard<std::mutex> lock(g_dotIndexListMutex);
    Doxygen::indexList->addImageFile(imgName());
  }
  generateCode(t);
  return m_baseName;
}
References Dir::absPath(), IndexList::addImageFile(), computeTheGraph(), g_dotIndexListMutex, generateCode(), getBaseName(), imgName(), Doxygen::indexList, m_absPath, m_baseName, m_dir, m_doNotAddImageToIndex, m_fileName, m_generateImageMap, m_graphFormat, m_graphId, m_regenerate, m_relPath, m_textFormat, prepareDotFile(), and QCString::str().
Referenced by DotGfxHierarchyTable::createGraph(), DotLegendGraph::writeGraph(), DotDirDeps::writeGraph(), DotClassGraph::writeGraph(), DotCallGraph::writeGraph(), DotGroupCollaboration::writeGraph(), and DotInclDepGraph::writeGraph().
writeGraph() [2/2]
QCString DotGraph::writeGraph (TextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1) [protected]
writeGraphFooter() [1/2]
void DotGraph::writeGraphFooter (TextStream & t) [static], [protected]
Definition at line 301 of file dotgraph.cpp.
{
  t << "}\n";
}
Referenced by computeGraph(), DotDirDeps::computeTheGraph(), DotGfxHierarchyTable::computeTheGraph(), DotGroupCollaboration::computeTheGraph(), and DotLegendGraph::computeTheGraph().
writeGraphFooter() [2/2]
static void DotGraph::writeGraphFooter (TextStream & t) [static], [protected]
writeGraphHeader() [1/2]
void DotGraph::writeGraphHeader (TextStream & t, const QCString & title = QCString()) [static], [protected]
Definition at line 276 of file dotgraph.cpp.
{
  t << "digraph ";
  if (title.isEmpty())
  {
    t << "\"Dot Graph\"";
  }
  else
  {
    t << "\"" << convertToXML(title) << "\"";
  }
  t << "\n{\n";
  if (Config_getBool(INTERACTIVE_SVG)) // insert a comment to force regeneration when this
                       // option is toggled
  {
    t << " // INTERACTIVE_SVG=YES\n";
  }
  t << " // LATEX_PDF_SIZE\n"; // write placeholder for LaTeX PDF bounding box size replacement
  t << " bgcolor=\"transparent\";\n";
  QCString c = Config_getString(DOT_COMMON_ATTR);
  if (!c.isEmpty()) c += ",";
  t << " edge [" << c << Config_getString(DOT_EDGE_ATTR) << "];\n";
  t << " node [" << c << Config_getString(DOT_NODE_ATTR) << "];\n";
}
References c, Config_getBool, Config_getString, convertToXML(), and QCString::isEmpty().
Referenced by computeGraph(), DotDirDeps::computeTheGraph(), DotGfxHierarchyTable::computeTheGraph(), DotLegendGraph::computeTheGraph(), and DotGroupCollaboration::writeGraphHeader().
writeGraphHeader() [2/2]
static void DotGraph::writeGraphHeader (TextStream & t, const QCString & title = QCString()) [static], [protected]
Member Data Documentation
m_absPath
QCString DotGraph::m_absPath [protected]
Definition at line 88 of file dotgraph.h.
Referenced by absBaseName(), absDotName(), absImgName(), absMapName(), and writeGraph().
m_baseName
QCString DotGraph::m_baseName [protected]
Definition at line 89 of file dotgraph.h.
Referenced by absBaseName(), absDotName(), absMapName(), generateCode(), DotCallGraph::getMapLabel(), DotDirDeps::getMapLabel(), DotGroupCollaboration::getMapLabel(), imgName(), and writeGraph().
m_curNodeNumber
int DotGraph::m_curNodeNumber = 0 [private]
Definition at line 104 of file dotgraph.h.
Referenced by getNextNodeNumber().
m_dir
Dir DotGraph::m_dir [protected]
Definition at line 82 of file dotgraph.h.
Referenced by prepareDotFile(), and writeGraph().
m_doNotAddImageToIndex
bool DotGraph::m_doNotAddImageToIndex = false [protected]
Definition at line 92 of file dotgraph.h.
Referenced by DotCallGraph::writeGraph(), writeGraph(), and DotGroupCollaboration::writeGraph().
m_fileName
QCString DotGraph::m_fileName [protected]
Definition at line 83 of file dotgraph.h.
Referenced by generateCode(), and writeGraph().
m_generateImageMap
bool DotGraph::m_generateImageMap = false [protected]
Definition at line 85 of file dotgraph.h.
Referenced by generateCode(), prepareDotFile(), and writeGraph().
m_graphFormat
GraphOutputFormat DotGraph::m_graphFormat = GOF_BITMAP [protected]
Definition at line 80 of file dotgraph.h.
Referenced by DotCallGraph::computeTheGraph(), DotClassGraph::computeTheGraph(), DotGroupCollaboration::computeTheGraph(), DotInclDepGraph::computeTheGraph(), generateCode(), imgName(), prepareDotFile(), and writeGraph().
m_graphId
int DotGraph::m_graphId = 0 [protected]
Definition at line 86 of file dotgraph.h.
Referenced by generateCode(), and writeGraph().
m_noDivTag
bool DotGraph::m_noDivTag = false [protected]
Definition at line 93 of file dotgraph.h.
Referenced by DotGfxHierarchyTable::createGraph(), and generateCode().
m_regenerate
bool DotGraph::m_regenerate = false [protected]
Definition at line 91 of file dotgraph.h.
Referenced by generateCode(), and writeGraph().
m_relPath
QCString DotGraph::m_relPath [protected]
Definition at line 84 of file dotgraph.h.
Referenced by generateCode(), relImgName(), and writeGraph().
m_textFormat
EmbeddedOutputFormat DotGraph::m_textFormat = EOF_Html [protected]
Definition at line 81 of file dotgraph.h.
Referenced by generateCode(), and writeGraph().
m_theGraph
QCString DotGraph::m_theGraph [protected]
Definition at line 90 of file dotgraph.h.
Referenced by DotCallGraph::computeTheGraph(), DotClassGraph::computeTheGraph(), DotDirDeps::computeTheGraph(), DotGfxHierarchyTable::computeTheGraph(), DotGroupCollaboration::computeTheGraph(), DotInclDepGraph::computeTheGraph(), DotLegendGraph::computeTheGraph(), and prepareDotFile().
m_urlOnly
bool DotGraph::m_urlOnly = false [protected]
Definition at line 95 of file dotgraph.h.
Referenced by generateCode(), and DotDirDeps::writeGraph().
m_zoomable
bool DotGraph::m_zoomable = true [protected]
Definition at line 94 of file dotgraph.h.
Referenced by DotGfxHierarchyTable::createGraph(), and generateCode().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dotgraph.h
doxygen/src/dotgraph.h
doxygen/build/doxygen/src/dotgraph.cpp
doxygen/src/dotgraph.cpp