ArgumentContext::Private Class Reference
Public Member Functions
Private (const Argument &arg, const Definition *def, const QCString &relPath)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (const Argument &arg, const Definition *def, const QCString &relPath)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant type () const
TemplateVariant attrib () const
TemplateVariant name () const
TemplateVariant defVal () const
TemplateVariant array () const
TemplateVariant docs () const
TemplateVariant namePart () const
TemplateVariant createType () const
TemplateVariant createDefval () const
TemplateVariant createDocs () const
TemplateVariant type () const
TemplateVariant attrib () const
TemplateVariant name () const
TemplateVariant defVal () const
TemplateVariant array () const
TemplateVariant docs () const
TemplateVariant namePart () const
TemplateVariant createType () const
TemplateVariant createDefval () const
TemplateVariant createDocs () const
Private Attributes
Argument m_argument
const Definition * m_def
QCString m_relPath
CachedItem< TemplateVariant, Private, &Private::createType > m_type
CachedItem< TemplateVariant, Private, &Private::createDefval > m_defval
CachedItem< TemplateVariant, Private, &Private::createDocs > m_docs
Static Private Attributes
static const PropertyMap< ArgumentContext::Private > s_inst
Detailed Description
Definition at line 8207 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
ArgumentContext::Private::Private (const Argument & arg, const Definition * def, const QCString & relPath) [inline]
Definition at line 8210 of file context.cpp.
      : m_argument(arg), m_def(def), m_relPath(relPath) {}
Private() [2/2]
ArgumentContext::Private::Private (const Argument & arg, const Definition * def, const QCString & relPath) [inline]
Definition at line 8210 of file context.cpp.
      : m_argument(arg), m_def(def), m_relPath(relPath) {}
Member Function Documentation
array() [1/2]
TemplateVariant ArgumentContext::Private::array () const [inline], [private]
Definition at line 8223 of file context.cpp.
{ return m_argument.array; }
References Argument::array, and m_argument.
Referenced by doxmlparser.compound.paramType::__init__(), doxmlparser.compound.paramType::get_array(), doxmlparser.compound.paramType::hasContent_(), and doxmlparser.compound.paramType::set_array().
array() [2/2]
TemplateVariant ArgumentContext::Private::array () const [inline], [private]
Definition at line 8223 of file context.cpp.
{ return m_argument.array; }
Referenced by doxmlparser.compound.paramType::__init__(), doxmlparser.compound.paramType::get_array(), doxmlparser.compound.paramType::hasContent_(), and doxmlparser.compound.paramType::set_array().
attrib() [1/2]
TemplateVariant ArgumentContext::Private::attrib () const [inline], [private]
Definition at line 8220 of file context.cpp.
{ return m_argument.attrib; }
References Argument::attrib, and m_argument.
attrib() [2/2]
TemplateVariant ArgumentContext::Private::attrib () const [inline], [private]
Definition at line 8220 of file context.cpp.
{ return m_argument.attrib; }
createDefval() [1/2]
TemplateVariant ArgumentContext::Private::createDefval () const [inline], [private]
Definition at line 8242 of file context.cpp.
    {
      return createLinkedText(m_def,m_relPath,m_argument.defval);
    }
References createLinkedText(), Argument::defval, m_argument, m_def, and m_relPath.
createDefval() [2/2]
TemplateVariant ArgumentContext::Private::createDefval () const [inline], [private]
Definition at line 8242 of file context.cpp.
    {
      return createLinkedText(m_def,m_relPath,m_argument.defval);
    }
References createLinkedText().
createDocs() [1/2]
TemplateVariant ArgumentContext::Private::createDocs () const [inline], [private]
Definition at line 8246 of file context.cpp.
    {
      return !m_argument.docs.isEmpty() ?
          TemplateVariant(parseDoc(m_def,m_def->docFile(),m_def->docLine(),m_relPath,m_argument.docs,TRUE)) :
          TemplateVariant("");
    }
References Definition::docFile(), Definition::docLine(), Argument::docs, QCString::isEmpty(), m_argument, m_def, m_relPath, parseDoc(), and TRUE.
createDocs() [2/2]
TemplateVariant ArgumentContext::Private::createDocs () const [inline], [private]
Definition at line 8246 of file context.cpp.
    {
      return !m_argument.docs.isEmpty() ?
          TemplateVariant(parseDoc(m_def,m_def->docFile(),m_def->docLine(),m_relPath,m_argument.docs,TRUE)) :
          TemplateVariant("");
    }
References parseDoc(), and TRUE.
createType() [1/2]
TemplateVariant ArgumentContext::Private::createType () const [inline], [private]
Definition at line 8238 of file context.cpp.
    {
      return createLinkedText(m_def,m_relPath,m_argument.type);
    }
References createLinkedText(), m_argument, m_def, m_relPath, and Argument::type.
createType() [2/2]
TemplateVariant ArgumentContext::Private::createType () const [inline], [private]
Definition at line 8238 of file context.cpp.
    {
      return createLinkedText(m_def,m_relPath,m_argument.type);
    }
References createLinkedText().
defVal() [1/2]
TemplateVariant ArgumentContext::Private::defVal () const [inline], [private]
Definition at line 8222 of file context.cpp.
{ return m_defval.get(this); }
References m_defval.
defVal() [2/2]
TemplateVariant ArgumentContext::Private::defVal () const [inline], [private]
Definition at line 8222 of file context.cpp.
{ return m_defval.get(this); }
docs() [1/2]
TemplateVariant ArgumentContext::Private::docs () const [inline], [private]
Definition at line 8224 of file context.cpp.
{ return m_docs.get(this); }
References m_docs.
docs() [2/2]
TemplateVariant ArgumentContext::Private::docs () const [inline], [private]
Definition at line 8224 of file context.cpp.
{ return m_docs.get(this); }
fields() [1/2]
StringVector ArgumentContext::Private::fields () const [inline]
Definition at line 8215 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector ArgumentContext::Private::fields () const [inline]
Definition at line 8215 of file context.cpp.
{ return s_inst.fields(); }
get() [1/2]
TemplateVariant ArgumentContext::Private::get (const QCString & n) const [inline]
Definition at line 8214 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant ArgumentContext::Private::get (const QCString & n) const [inline]
Definition at line 8214 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
name() [1/2]
TemplateVariant ArgumentContext::Private::name () const [inline], [private]
Definition at line 8221 of file context.cpp.
{ return m_argument.name; }
References m_argument, and Argument::name.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
TemplateVariant ArgumentContext::Private::name () const [inline], [private]
Definition at line 8221 of file context.cpp.
{ return m_argument.name; }
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
namePart() [1/2]
TemplateVariant ArgumentContext::Private::namePart () const [inline], [private]
Definition at line 8225 of file context.cpp.
    {
      QCString result = m_argument.attrib;
      size_t l = result.length();
      if (l>2 && result.at(0)=='[' && result.at(l-1)==']')
      {
        result = result.mid(1,l-2);
        if (result!=",") result+=":"; // for normal keywords add colon
      }
      return result;
    }
References QCString::at(), Argument::attrib, QCString::length(), m_argument, and QCString::mid().
namePart() [2/2]
TemplateVariant ArgumentContext::Private::namePart () const [inline], [private]
Definition at line 8225 of file context.cpp.
    {
      QCString result = m_argument.attrib;
      size_t l = result.length();
      if (l>2 && result.at(0)=='[' && result.at(l-1)==']')
      {
        result = result.mid(1,l-2);
        if (result!=",") result+=":"; // for normal keywords add colon
      }
      return result;
    }
References QCString::at(), QCString::length(), and QCString::mid().
type() [1/2]
TemplateVariant ArgumentContext::Private::type () const [inline], [private]
Definition at line 8219 of file context.cpp.
{ return m_type.get(this); }
References m_type.
type() [2/2]
TemplateVariant ArgumentContext::Private::type () const [inline], [private]
Definition at line 8219 of file context.cpp.
{ return m_type.get(this); }
Member Data Documentation
m_argument
Argument ArgumentContext::Private::m_argument [private]
Definition at line 8252 of file context.cpp.
Referenced by array(), attrib(), createDefval(), createDocs(), createType(), name(), and namePart().
m_def
const Definition * ArgumentContext::Private::m_def [private]
Definition at line 8253 of file context.cpp.
Referenced by createDefval(), createDocs(), and createType().
m_defval
CachedItem< TemplateVariant, Private, &Private::createDefval > ArgumentContext::Private::m_defval [private]
Definition at line 8256 of file context.cpp.
Referenced by defVal().
m_docs
CachedItem< TemplateVariant, Private, &Private::createDocs > ArgumentContext::Private::m_docs [private]
Definition at line 8257 of file context.cpp.
Referenced by docs().
m_relPath
QCString ArgumentContext::Private::m_relPath [private]
Definition at line 8254 of file context.cpp.
Referenced by createDefval(), createDocs(), and createType().
m_type
CachedItem< TemplateVariant, Private, &Private::createType > ArgumentContext::Private::m_type [private]
Definition at line 8255 of file context.cpp.
Referenced by type().
s_inst
const PropertyMap< ArgumentContext::Private > ArgumentContext::Private::s_inst [static], [private]
Initial value:
{
  { "type", &Private::type },
  { "name", &Private::name },
  { "defVal", &Private::defVal },
  { "docs", &Private::docs },
  { "attrib", &Private::attrib },
  { "array", &Private::array },
  { "namePart", &Private::namePart }
}
Definition at line 8258 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp