TemplateNodeMarkers Class Reference
Class representing an 'markers' tag in a template.
Public Member Functions
TemplateNodeMarkers (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
TemplateNodeMarkers (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
Private Attributes
TemplateNodeList m_nodes
QCString m_var
ExprAstPtr m_listExpr
ExprAstPtr m_patternExpr
Additional Inherited Members
Detailed Description
Class representing an 'markers' tag in a template.
Definition at line 4394 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeMarkers() [1/2]
TemplateNodeMarkers::TemplateNodeMarkers (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4397 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeMarkers>(parser,parent,line)
    {
      TRACE(("{TemplateNodeMarkers(%s)\n",qPrint(data)));
      int i = data.find(" in ");
      int w = data.find(" with ");
      if (i==-1 || w==-1 || w<i)
      {
        parser->warn(m_templateName,line,"markers tag as wrong format. Expected: markers <var> in <list> with <string_with_markers>");
      }
      else
      {
        ExpressionParser expParser(parser,line);
        m_var = data.left(i);
        m_listExpr = expParser.parse(data.mid(i+4,w-i-4));
        m_patternExpr = expParser.parse(data.right(data.length()-w-6));
      }
      StringVector stopAt = { "endmarkers" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endmarkers
      TRACE(("}TemplateNodeMarkers(%s)\n",qPrint(data)));
    }
References data, m_listExpr, m_nodes, m_patternExpr, TemplateNodeCreator< TemplateNodeMarkers >::m_templateName, m_var, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), TRACE, w, and TemplateParser::warn().
TemplateNodeMarkers() [2/2]
TemplateNodeMarkers::TemplateNodeMarkers (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4397 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeMarkers>(parser,parent,line)
    {
      TRACE(("{TemplateNodeMarkers(%s)\n",qPrint(data)));
      int i = data.find(" in ");
      int w = data.find(" with ");
      if (i==-1 || w==-1 || w<i)
      {
        parser->warn(m_templateName,line,"markers tag as wrong format. Expected: markers <var> in <list> with <string_with_markers>");
      }
      else
      {
        ExpressionParser expParser(parser,line);
        m_var = data.left(i);
        m_listExpr = expParser.parse(data.mid(i+4,w-i-4));
        m_patternExpr = expParser.parse(data.right(data.length()-w-6));
      }
      StringVector stopAt = { "endmarkers" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endmarkers
      TRACE(("}TemplateNodeMarkers(%s)\n",qPrint(data)));
    }
References data, m_listExpr, m_nodes, m_patternExpr, TemplateNodeCreator< TemplateNodeMarkers >::m_templateName, m_var, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), TRACE, w, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeMarkers::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4419 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (!m_var.isEmpty() && m_listExpr && m_patternExpr)
      {
        TemplateVariant v = m_listExpr->resolve(c);
        const TemplateListIntfPtr list = v.toList();
        TemplateVariant patternStr = m_patternExpr->resolve(c);
        if (list)
        {
          if (patternStr.isString())
          {
            TemplateListIntf::ConstIteratorPtr it = list->createIterator();
            c->push();
            std::string str = patternStr.toString().str();
            static const reg::Ex marker(R"(@\d+)");
            reg::Iterator re_it(str,marker);
            reg::Iterator end;
            size_t index=0;
            for (; re_it!=end ; ++re_it)
            {
              const auto &match = *re_it;
              size_t newIndex = match.position();
              size_t matchLen = match.length();
              std::string part = str.substr(index,newIndex-index);
              if (ci->needsRecoding())
              {
                ts << ci->recode(QCString(part)); // write text before marker
              }
              else
              {
                ts << part; // write text before marker
              }
              unsigned long entryIndex = std::stoul(match.str().substr(1));
              TemplateVariant var;
              size_t i=0;
              // search for list element at position id
              for (it->toFirst(); (it->current(var)) && i<entryIndex; it->toNext(),i++) {}
              if (i==entryIndex) // found element
              {
                TemplateStructPtr s = TemplateStruct::alloc();
                s->set("id",i);
                c->set("markers",std::static_pointer_cast<TemplateStructIntf>(s));
                c->set(m_var,var); // define local variable to hold element of list type
                bool wasSpaceless = ci->spacelessEnabled();
                ci->enableSpaceless(TRUE);
                m_nodes.render(ts,c);
                ci->enableSpaceless(wasSpaceless);
              }
              else if (i<entryIndex)
              {
                ci->warn(m_templateName,m_line,"markers list does not an element for marker position %d",i);
              }
              index=newIndex+matchLen; // set index just after marker
            }
            if (ci->needsRecoding())
            {
              ts << ci->recode(str.substr(index)); // write text after last marker
            }
            else
            {
              ts << str.substr(index); // write text after last marker
            }
            c->pop();
          }
          else
          {
            ci->warn(m_templateName,m_line,"markers requires a parameter of string type after 'with'!");
          }
        }
        else
        {
          ci->warn(m_templateName,m_line,"markers requires a parameter of list type after 'in'!");
        }
      }
    }
References TemplateStruct::alloc(), c, TemplateContextImpl::enableSpaceless(), ghc::filesystem::end(), QCString::isEmpty(), TemplateVariant::isString(), TemplateNodeCreator< TemplateNodeMarkers >::m_line, m_listExpr, m_nodes, m_patternExpr, TemplateNodeCreator< TemplateNodeMarkers >::m_templateName, m_var, reg::match(), TemplateContextImpl::needsRecoding(), TemplateContextImpl::recode(), TemplateNodeList::render(), s, TemplateContextImpl::setLocation(), TemplateContextImpl::spacelessEnabled(), QCString::str(), string, TemplateVariant::toList(), TemplateVariant::toString(), TRUE, var, and TemplateContextImpl::warn().
render() [2/2]
void TemplateNodeMarkers::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4419 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (!m_var.isEmpty() && m_listExpr && m_patternExpr)
      {
        TemplateVariant v = m_listExpr->resolve(c);
        const TemplateListIntfPtr list = v.toList();
        TemplateVariant patternStr = m_patternExpr->resolve(c);
        if (list)
        {
          if (patternStr.isString())
          {
            TemplateListIntf::ConstIteratorPtr it = list->createIterator();
            c->push();
            std::string str = patternStr.toString().str();
            static const reg::Ex marker(R"(@\d+)");
            reg::Iterator re_it(str,marker);
            reg::Iterator end;
            size_t index=0;
            for (; re_it!=end ; ++re_it)
            {
              const auto &match = *re_it;
              size_t newIndex = match.position();
              size_t matchLen = match.length();
              std::string part = str.substr(index,newIndex-index);
              if (ci->needsRecoding())
              {
                ts << ci->recode(QCString(part)); // write text before marker
              }
              else
              {
                ts << part; // write text before marker
              }
              unsigned long entryIndex = std::stoul(match.str().substr(1));
              TemplateVariant var;
              size_t i=0;
              // search for list element at position id
              for (it->toFirst(); (it->current(var)) && i<entryIndex; it->toNext(),i++) {}
              if (i==entryIndex) // found element
              {
                TemplateStructPtr s = TemplateStruct::alloc();
                s->set("id",i);
                c->set("markers",std::static_pointer_cast<TemplateStructIntf>(s));
                c->set(m_var,var); // define local variable to hold element of list type
                bool wasSpaceless = ci->spacelessEnabled();
                ci->enableSpaceless(TRUE);
                m_nodes.render(ts,c);
                ci->enableSpaceless(wasSpaceless);
              }
              else if (i<entryIndex)
              {
                ci->warn(m_templateName,m_line,"markers list does not an element for marker position %d",i);
              }
              index=newIndex+matchLen; // set index just after marker
            }
            if (ci->needsRecoding())
            {
              ts << ci->recode(str.substr(index)); // write text after last marker
            }
            else
            {
              ts << str.substr(index); // write text after last marker
            }
            c->pop();
          }
          else
          {
            ci->warn(m_templateName,m_line,"markers requires a parameter of string type after 'with'!");
          }
        }
        else
        {
          ci->warn(m_templateName,m_line,"markers requires a parameter of list type after 'in'!");
        }
      }
    }
References TemplateStruct::alloc(), c, TemplateContextImpl::enableSpaceless(), ghc::filesystem::end(), QCString::isEmpty(), TemplateVariant::isString(), TemplateNodeCreator< TemplateNodeMarkers >::m_line, m_listExpr, m_nodes, m_patternExpr, TemplateNodeCreator< TemplateNodeMarkers >::m_templateName, m_var, reg::match(), TemplateContextImpl::needsRecoding(), TemplateContextImpl::recode(), TemplateNodeList::render(), s, TemplateContextImpl::setLocation(), TemplateContextImpl::spacelessEnabled(), QCString::str(), string, TemplateVariant::toList(), TemplateVariant::toString(), TRUE, var, and TemplateContextImpl::warn().
Member Data Documentation
m_listExpr
ExprAstPtr TemplateNodeMarkers::m_listExpr [private]
Definition at line 4501 of file template.cpp.
Referenced by render(), and TemplateNodeMarkers().
m_nodes
TemplateNodeList TemplateNodeMarkers::m_nodes [private]
Definition at line 4499 of file template.cpp.
Referenced by render(), and TemplateNodeMarkers().
m_patternExpr
ExprAstPtr TemplateNodeMarkers::m_patternExpr [private]
Definition at line 4502 of file template.cpp.
Referenced by render(), and TemplateNodeMarkers().
m_var
QCString TemplateNodeMarkers::m_var [private]
Definition at line 4500 of file template.cpp.
Referenced by render(), and TemplateNodeMarkers().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp