PlantumlManager Class Reference
#include <plantuml.h>
Public Types
enum OutputFormat {
PUML_BITMAP
, PUML_EPS
, PUML_SVG
, PUML_BITMAP
,
PUML_EPS
, PUML_SVG
 }
enum OutputFormat {
PUML_BITMAP
, PUML_EPS
, PUML_SVG
, PUML_BITMAP
,
PUML_EPS
, PUML_SVG
 }
using FilesMap = std::map< std::string, StringVector >
using ContentMap = std::map< std::string, PlantumlContent >
using FilesMap = std::map< std::string, StringVector >
using ContentMap = std::map< std::string, PlantumlContent >
Public Member Functions
void run ()
QCString writePlantUMLSource (const QCString &outDirArg, const QCString &fileName, const QCString &content, OutputFormat format, const QCString &engine, const QCString &srcFile, int srcLine)
void generatePlantUMLOutput (const QCString &baseName, const QCString &outDir, OutputFormat format)
void run ()
QCString writePlantUMLSource (const QCString &outDirArg, const QCString &fileName, const QCString &content, OutputFormat format, const QCString &engine, const QCString &srcFile, int srcLine)
void generatePlantUMLOutput (const QCString &baseName, const QCString &outDir, OutputFormat format)
Static Public Member Functions
static PlantumlManager & instance ()
static PlantumlManager & instance ()
Private Member Functions
PlantumlManager ()
void insert (const std::string &key, const std::string &value, const QCString &outDir, OutputFormat format, const QCString &puContent, const QCString &srcFile, int srcLine)
PlantumlManager ()
void insert (const std::string &key, const std::string &value, const QCString &outDir, OutputFormat format, const QCString &puContent, const QCString &srcFile, int srcLine)
Private Attributes
FilesMap m_pngPlantumlFiles
FilesMap m_svgPlantumlFiles
FilesMap m_epsPlantumlFiles
ContentMap m_pngPlantumlContent
ContentMap m_svgPlantumlContent
ContentMap m_epsPlantumlContent
Detailed Description
Singleton that manages plantuml relation actions
Definition at line 40 of file plantuml.h.
Member Typedef Documentation
ContentMap [1/2]
using PlantumlManager::ContentMap = std::map< std::string, PlantumlContent >
Definition at line 74 of file plantuml.h.
ContentMap [2/2]
using PlantumlManager::ContentMap = std::map< std::string, PlantumlContent >
Definition at line 74 of file plantuml.h.
FilesMap [1/2]
using PlantumlManager::FilesMap = std::map< std::string, StringVector >
Definition at line 73 of file plantuml.h.
FilesMap [2/2]
using PlantumlManager::FilesMap = std::map< std::string, StringVector >
Definition at line 73 of file plantuml.h.
Member Enumeration Documentation
OutputFormat [1/2]
enum PlantumlManager::OutputFormat
Plant UML output image formats
Enumerator
PUML_BITMAP
PUML_EPS
PUML_SVG
PUML_BITMAP
PUML_EPS
PUML_SVG
Definition at line 44 of file plantuml.h.
{ PUML_BITMAP, PUML_EPS, PUML_SVG };
OutputFormat [2/2]
enum PlantumlManager::OutputFormat
Plant UML output image formats
Enumerator
PUML_BITMAP
PUML_EPS
PUML_SVG
PUML_BITMAP
PUML_EPS
PUML_SVG
Definition at line 44 of file plantuml.h.
{ PUML_BITMAP, PUML_EPS, PUML_SVG };
Constructor & Destructor Documentation
PlantumlManager() [1/2]
PlantumlManager::PlantumlManager () [private]
Definition at line 127 of file plantuml.cpp.
{
}
PlantumlManager() [2/2]
PlantumlManager::PlantumlManager () [private]
Member Function Documentation
generatePlantUMLOutput() [1/2]
void PlantumlManager::generatePlantUMLOutput (const QCString & baseName, const QCString & outDir, OutputFormat format)
Convert a PlantUML file to an image.
Parameters
 in baseName the name of the generated file (as returned by writePlantUMLSource())
 in outDir the directory to write the resulting image into.
 in format the image format to generate.
Definition at line 92 of file plantuml.cpp.
{
  QCString imgName = baseName;
  // The basename contains path, we need to strip the path from the filename in order
  // to create the image file name which should be included in the index.qhp (Qt help index file).
  int i;
  if ((i=imgName.findRev('/'))!=-1) // strip path
  {
    imgName=imgName.right(imgName.length()-i-1);
  }
  switch (format)
  {
    case PUML_BITMAP:
      imgName+=".png";
      break;
    case PUML_EPS:
      imgName+=".eps";
      break;
    case PUML_SVG:
      imgName+=".svg";
      break;
  }
  Doxygen::indexList->addImageFile(imgName);
}
References IndexList::addImageFile(), QCString::findRev(), Doxygen::indexList, QCString::length(), PUML_BITMAP, PUML_EPS, PUML_SVG, and QCString::right().
Referenced by FlowChart::printUmlTree(), RTFDocVisitor::writePlantUMLFile(), DocbookDocVisitor::writePlantUMLFile(), LatexDocVisitor::writePlantUMLFile(), and HtmlDocVisitor::writePlantUMLFile().
generatePlantUMLOutput() [2/2]
void PlantumlManager::generatePlantUMLOutput (const QCString & baseName, const QCString & outDir, OutputFormat format)
Convert a PlantUML file to an image.
Parameters
 in baseName the name of the generated file (as returned by writePlantUMLSource())
 in outDir the directory to write the resulting image into.
 in format the image format to generate.
insert() [1/2]
void PlantumlManager::insert (const std::string & key, const std::string & value, const QCString & outDir, OutputFormat format, const QCString & puContent, const QCString & srcFile, int srcLine) [private]
Definition at line 338 of file plantuml.cpp.
{
  Debug::print(Debug::Plantuml,0,"*** %s key:%s ,value:%s\n","PlantumlManager::insert",qPrint(key),qPrint(value));
  switch (format)
  {
    case PUML_BITMAP:
      addPlantumlFiles(m_pngPlantumlFiles,key,value);
      print(m_pngPlantumlFiles);
      addPlantumlContent(m_pngPlantumlContent,key,outDir,puContent,srcFile,srcLine);
      print(m_pngPlantumlContent);
      break;
    case PUML_EPS:
      addPlantumlFiles(m_epsPlantumlFiles,key,value);
      print(m_epsPlantumlFiles);
      addPlantumlContent(m_epsPlantumlContent,key,outDir,puContent,srcFile,srcLine);
      print(m_epsPlantumlContent);
      break;
    case PUML_SVG:
      addPlantumlFiles(m_svgPlantumlFiles,key,value);
      print(m_svgPlantumlFiles);
      addPlantumlContent(m_svgPlantumlContent,key,outDir,puContent,srcFile,srcLine);
      print(m_svgPlantumlContent);
      break;
  }
}
References addPlantumlContent(), addPlantumlFiles(), m_epsPlantumlContent, m_epsPlantumlFiles, m_pngPlantumlContent, m_pngPlantumlFiles, m_svgPlantumlContent, m_svgPlantumlFiles, Debug::Plantuml, print(), Debug::print(), PUML_BITMAP, PUML_EPS, PUML_SVG, and qPrint().
Referenced by writePlantUMLSource().
insert() [2/2]
void PlantumlManager::insert (const std::string & key, const std::string & value, const QCString & outDir, OutputFormat format, const QCString & puContent, const QCString & srcFile, int srcLine) [private]
instance() [1/2]
PlantumlManager & PlantumlManager::instance () [static]
Definition at line 121 of file plantuml.cpp.
{
  static PlantumlManager theInstance;
  return theInstance;
}
Referenced by generateOutput(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), FlowChart::printUmlTree(), RTFDocVisitor::writePlantUMLFile(), DocbookDocVisitor::writePlantUMLFile(), LatexDocVisitor::writePlantUMLFile(), HtmlDocVisitor::writePlantUMLFile(), and writePlantUMLSource().
instance() [2/2]
static PlantumlManager & PlantumlManager::instance () [static]
run() [1/2]
void PlantumlManager::run ()
Run plant UML tool for all images
Definition at line 280 of file plantuml.cpp.
{
  Debug::print(Debug::Plantuml,0,"*** %s\n","PlantumlManager::run");
  runPlantumlContent(m_pngPlantumlFiles, m_pngPlantumlContent, PUML_BITMAP);
  runPlantumlContent(m_svgPlantumlFiles, m_svgPlantumlContent, PUML_SVG);
  runPlantumlContent(m_epsPlantumlFiles, m_epsPlantumlContent, PUML_EPS);
}
References m_epsPlantumlContent, m_epsPlantumlFiles, m_pngPlantumlContent, m_pngPlantumlFiles, m_svgPlantumlContent, m_svgPlantumlFiles, Debug::Plantuml, Debug::print(), PUML_BITMAP, PUML_EPS, PUML_SVG, and runPlantumlContent().
Referenced by generateOutput().
run() [2/2]
void PlantumlManager::run ()
Run plant UML tool for all images
writePlantUMLSource() [1/2]
QCString PlantumlManager::writePlantUMLSource (const QCString & outDirArg, const QCString & fileName, const QCString & content, OutputFormat format, const QCString & engine, const QCString & srcFile, int srcLine)
Write a PlantUML compatible file.
Parameters
 in outDirArg the output directory to write the file to.
 in fileName the name of the file. If empty a name will be chosen automatically.
 in content the contents of the PlantUML file.
 in format the image format to generate.
 in engine the plantuml engine to use.
 in srcFile the source file resulting in the write command.
 in srcLine the line number resulting in the write command.
Returns
The name of the generated file.
Definition at line 27 of file plantuml.cpp.
{
  QCString baseName;
  QCString puName;
  QCString imgName;
  QCString outDir(outDirArg);
  static int umlindex=1;
  Debug::print(Debug::Plantuml,0,"*** %s fileName: %s\n","writePlantUMLSource",qPrint(fileName));
  Debug::print(Debug::Plantuml,0,"*** %s outDir: %s\n","writePlantUMLSource",qPrint(outDir));
  // strip any trailing slashes and backslashes
  uint l;
  while ((l=outDir.length())>0 && (outDir.at(l-1)=='/' || outDir.at(l-1)=='\\'))
  {
    outDir = outDir.left(l-1);
  }
  if (fileName.isEmpty()) // generate name
  {
    puName = "inline_umlgraph_"+QCString().setNum(umlindex);
    baseName = outDir+"/inline_umlgraph_"+QCString().setNum(umlindex++);
  }
  else // user specified name
  {
    baseName = fileName;
    int i=baseName.findRev('.');
    if (i!=-1) baseName = baseName.left(i);
    puName = baseName;
    baseName.prepend(outDir+"/");
  }
  switch (format)
  {
    case PUML_BITMAP:
      imgName =puName+".png";
      break;
    case PUML_EPS:
      imgName =puName+".eps";
      break;
    case PUML_SVG:
      imgName =puName+".svg";
      break;
  }
  Debug::print(Debug::Plantuml,0,"*** %s baseName: %s\n","writePlantUMLSource",qPrint(baseName));
  Debug::print(Debug::Plantuml,0,"*** %s puName: %s\n","writePlantUMLSource",qPrint(puName));
  Debug::print(Debug::Plantuml,0,"*** %s imgName: %s\n","writePlantUMLSource",qPrint(imgName));
  QCString text = "@start"+engine+" "+imgName+"\n";
  text+=content;
  text+="\n@end"+engine+"\n";
  QCString qcOutDir(outDir);
  uint pos = qcOutDir.findRev("/");
  QCString generateType(qcOutDir.right(qcOutDir.length() - (pos + 1)));
  Debug::print(Debug::Plantuml,0,"*** %s generateType: %s\n","writePlantUMLSource",qPrint(generateType));
  PlantumlManager::instance().insert(generateType.str(),puName.str(),outDir,format,text,srcFile,srcLine);
  Debug::print(Debug::Plantuml,0,"*** %s generateType: %s\n","writePlantUMLSource",qPrint(generateType));
  return baseName;
}
References QCString::at(), QCString::findRev(), insert(), instance(), QCString::isEmpty(), QCString::left(), QCString::length(), Debug::Plantuml, QCString::prepend(), Debug::print(), PUML_BITMAP, PUML_EPS, PUML_SVG, qPrint(), QCString::right(), QCString::setNum(), and QCString::str().
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), and FlowChart::printUmlTree().
writePlantUMLSource() [2/2]
QCString PlantumlManager::writePlantUMLSource (const QCString & outDirArg, const QCString & fileName, const QCString & content, OutputFormat format, const QCString & engine, const QCString & srcFile, int srcLine)
Write a PlantUML compatible file.
Parameters
 in outDirArg the output directory to write the file to.
 in fileName the name of the file. If empty a name will be chosen automatically.
 in content the contents of the PlantUML file.
 in format the image format to generate.
 in engine the plantuml engine to use.
 in srcFile the source file resulting in the write command.
 in srcLine the line number resulting in the write command.
Returns
The name of the generated file.
Member Data Documentation
m_epsPlantumlContent
ContentMap PlantumlManager::m_epsPlantumlContent [private]
Definition at line 90 of file plantuml.h.
Referenced by insert(), and run().
m_epsPlantumlFiles
FilesMap PlantumlManager::m_epsPlantumlFiles [private]
Definition at line 87 of file plantuml.h.
Referenced by insert(), and run().
m_pngPlantumlContent
ContentMap PlantumlManager::m_pngPlantumlContent [private]
Definition at line 88 of file plantuml.h.
Referenced by insert(), and run().
m_pngPlantumlFiles
FilesMap PlantumlManager::m_pngPlantumlFiles [private]
Definition at line 85 of file plantuml.h.
Referenced by insert(), and run().
m_svgPlantumlContent
ContentMap PlantumlManager::m_svgPlantumlContent [private]
Definition at line 89 of file plantuml.h.
Referenced by insert(), and run().
m_svgPlantumlFiles
FilesMap PlantumlManager::m_svgPlantumlFiles [private]
Definition at line 86 of file plantuml.h.
Referenced by insert(), and run().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/plantuml.h
doxygen/src/plantuml.h
doxygen/build/doxygen/src/plantuml.cpp
doxygen/src/plantuml.cpp