XMLContentHandler Class Reference
Public Types
enum FieldNames {
UnknownField = 0
, TypeField = 1
, NameField = 2
, ArgsField = 3
,
TagField = 4
, UrlField = 5
, KeywordField = 6
, TextField = 7
,
UnknownField = 0
, TypeField = 1
, NameField = 2
, ArgsField = 3
,
TagField = 4
, UrlField = 5
, KeywordField = 6
, TextField = 7
 }
enum FieldNames {
UnknownField = 0
, TypeField = 1
, NameField = 2
, ArgsField = 3
,
TagField = 4
, UrlField = 5
, KeywordField = 6
, TextField = 7
,
UnknownField = 0
, TypeField = 1
, NameField = 2
, ArgsField = 3
,
TagField = 4
, UrlField = 5
, KeywordField = 6
, TextField = 7
 }
Public Member Functions
XMLContentHandler (const std::string &path)
~XMLContentHandler ()
void startElement (const std::string &name, const XMLHandlers::Attributes &attrib)
void endElement (const std::string &name)
void characters (const std::string &ch)
void error (const std::string &fileName, int lineNr, const std::string &msg)
XMLContentHandler (const std::string &path)
~XMLContentHandler ()
void startElement (const std::string &name, const XMLHandlers::Attributes &attrib)
void endElement (const std::string &name)
void characters (const std::string &ch)
void error (const std::string &fileName, int lineNr, const std::string &msg)
Private Attributes
Xapian::WritableDatabase m_db
Xapian::Document m_doc
Xapian::TermGenerator m_indexer
Xapian::Stem m_stemmer
std::string m_data
FieldNames m_curFieldName
Detailed Description
This class is a wrapper around SAX style XML parser, which parses the file without first building a DOM tree in memory.
Definition at line 146 of file doxyindexer.cpp.
Member Enumeration Documentation
FieldNames [1/2]
enum XMLContentHandler::FieldNames
Enumerator
UnknownField
TypeField
NameField
ArgsField
TagField
UrlField
KeywordField
TextField
UnknownField
TypeField
NameField
ArgsField
TagField
UrlField
KeywordField
TextField
Definition at line 165 of file doxyindexer.cpp.
    {
      UnknownField = 0,
      TypeField = 1,
      NameField = 2,
      ArgsField = 3,
      TagField = 4,
      UrlField = 5,
      KeywordField = 6,
      TextField = 7
    };
FieldNames [2/2]
enum XMLContentHandler::FieldNames
Enumerator
UnknownField
TypeField
NameField
ArgsField
TagField
UrlField
KeywordField
TextField
UnknownField
TypeField
NameField
ArgsField
TagField
UrlField
KeywordField
TextField
Definition at line 165 of file doxyindexer.cpp.
    {
      UnknownField = 0,
      TypeField = 1,
      NameField = 2,
      ArgsField = 3,
      TagField = 4,
      UrlField = 5,
      KeywordField = 6,
      TextField = 7
    };
Constructor & Destructor Documentation
XMLContentHandler() [1/2]
XMLContentHandler::XMLContentHandler (const std::string & path) [inline]
Handler for parsing XML data
Definition at line 150 of file doxyindexer.cpp.
      : m_db(path+"doxysearch.db",Xapian::DB_CREATE_OR_OVERWRITE),
        m_stemmer("english")
    {
      m_curFieldName = UnknownField;
      m_indexer.set_stemmer(m_stemmer);
      m_indexer.set_document(m_doc);
    }
References m_curFieldName, m_doc, m_indexer, m_stemmer, and UnknownField.
 XMLContentHandler() [1/2]
XMLContentHandler::~XMLContentHandler () [inline]
Free data handler
Definition at line 160 of file doxyindexer.cpp.
    {
      m_db.commit();
    }
References m_db.
XMLContentHandler() [2/2]
XMLContentHandler::XMLContentHandler (const std::string & path) [inline]
Handler for parsing XML data
Definition at line 150 of file doxyindexer.cpp.
      : m_db(path+"doxysearch.db",Xapian::DB_CREATE_OR_OVERWRITE),
        m_stemmer("english")
    {
      m_curFieldName = UnknownField;
      m_indexer.set_stemmer(m_stemmer);
      m_indexer.set_document(m_doc);
    }
References m_curFieldName, m_doc, m_indexer, m_stemmer, and UnknownField.
 XMLContentHandler() [2/2]
XMLContentHandler::~XMLContentHandler () [inline]
Free data handler
Definition at line 160 of file doxyindexer.cpp.
    {
      m_db.commit();
    }
References m_db.
Member Function Documentation
characters() [1/2]
void XMLContentHandler::characters (const std::string & ch) [inline]
Handler for inline text
Definition at line 264 of file doxyindexer.cpp.
    {
      m_data += ch;
    }
References m_data.
Referenced by main().
characters() [2/2]
void XMLContentHandler::characters (const std::string & ch) [inline]
Handler for inline text
Definition at line 264 of file doxyindexer.cpp.
    {
      m_data += ch;
    }
References m_data.
endElement() [1/2]
void XMLContentHandler::endElement (const std::string & name) [inline]
Handler for an end tag. Called for </doc> and </field> tags
Definition at line 196 of file doxyindexer.cpp.
    {
      if (name=="doc") // </doc>
      {
        std::string term = m_doc.get_value(NameField);
        std::string partTerm;
        size_t pos = term.rfind("::");
        if (pos!=std::string::npos)
        {
          partTerm = term.substr(pos+2);
        }
        if (m_doc.get_value(TypeField)=="class" ||
            m_doc.get_value(TypeField)=="file" ||
            m_doc.get_value(TypeField)=="namespace") // containers get highest prio
        {
          safeAddTerm(term,m_doc,1000);
          if (!partTerm.empty())
          {
            safeAddTerm(partTerm,m_doc,500);
          }
        }
        else // members and others get lower prio
        {
          safeAddTerm(m_doc.get_value(NameField),m_doc,100);
          if (!partTerm.empty())
          {
            safeAddTerm(partTerm,m_doc,50);
          }
        }
        m_db.add_document(m_doc);
        m_doc.clear_values();
        m_doc.clear_terms();
      }
      else if (name=="field" && m_curFieldName!=UnknownField) // </field>
      {
        // strip whitespace from m_data
        m_data = reduce(m_data);
        // replace XML entities
        m_data = unescapeXmlEntities(m_data);
        // add data to the document
        m_doc.add_value(m_curFieldName,m_data);
        switch (m_curFieldName)
        {
          case TypeField:
          case NameField:
          case TagField:
          case UrlField:
            // meta data that is not searchable
            break;
          case KeywordField:
            addWords(m_data,m_doc,50);
            break;
          case ArgsField:
            addIdentifiers(m_data,m_doc,10);
            break;
          case TextField:
            addWords(m_data,m_doc,2);
            break;
          default:
            break;
        }
        m_data="";
        m_curFieldName=UnknownField;
      }
      // reset m_data
    }
References addIdentifiers(), addWords(), ArgsField, KeywordField, m_curFieldName, m_data, m_db, m_doc, setup::name, NameField, reduce(), safeAddTerm(), string, TagField, term(), TextField, TypeField, unescapeXmlEntities(), UnknownField, and UrlField.
Referenced by main().
endElement() [2/2]
void XMLContentHandler::endElement (const std::string & name) [inline]
Handler for an end tag. Called for </doc> and </field> tags
Definition at line 196 of file doxyindexer.cpp.
    {
      if (name=="doc") // </doc>
      {
        std::string term = m_doc.get_value(NameField);
        std::string partTerm;
        size_t pos = term.rfind("::");
        if (pos!=std::string::npos)
        {
          partTerm = term.substr(pos+2);
        }
        if (m_doc.get_value(TypeField)=="class" ||
            m_doc.get_value(TypeField)=="file" ||
            m_doc.get_value(TypeField)=="namespace") // containers get highest prio
        {
          safeAddTerm(term,m_doc,1000);
          if (!partTerm.empty())
          {
            safeAddTerm(partTerm,m_doc,500);
          }
        }
        else // members and others get lower prio
        {
          safeAddTerm(m_doc.get_value(NameField),m_doc,100);
          if (!partTerm.empty())
          {
            safeAddTerm(partTerm,m_doc,50);
          }
        }
        m_db.add_document(m_doc);
        m_doc.clear_values();
        m_doc.clear_terms();
      }
      else if (name=="field" && m_curFieldName!=UnknownField) // </field>
      {
        // strip whitespace from m_data
        m_data = reduce(m_data);
        // replace XML entities
        m_data = unescapeXmlEntities(m_data);
        // add data to the document
        m_doc.add_value(m_curFieldName,m_data);
        switch (m_curFieldName)
        {
          case TypeField:
          case NameField:
          case TagField:
          case UrlField:
            // meta data that is not searchable
            break;
          case KeywordField:
            addWords(m_data,m_doc,50);
            break;
          case ArgsField:
            addIdentifiers(m_data,m_doc,10);
            break;
          case TextField:
            addWords(m_data,m_doc,2);
            break;
          default:
            break;
        }
        m_data="";
        m_curFieldName=UnknownField;
      }
      // reset m_data
    }
References addIdentifiers(), addWords(), ArgsField, KeywordField, m_curFieldName, m_data, m_db, m_doc, setup::name, NameField, reduce(), safeAddTerm(), string, TagField, term(), TextField, TypeField, unescapeXmlEntities(), UnknownField, and UrlField.
error() [1/2]
void XMLContentHandler::error (const std::string & fileName, int lineNr, const std::string & msg) [inline]
Definition at line 269 of file doxyindexer.cpp.
    {
      std::cerr << "Fatal error at " << fileName << ":" << lineNr << ": " << msg << std::endl;
    }
References msg().
Referenced by main().
error() [2/2]
void XMLContentHandler::error (const std::string & fileName, int lineNr, const std::string & msg) [inline]
Definition at line 269 of file doxyindexer.cpp.
    {
      std::cerr << "Fatal error at " << fileName << ":" << lineNr << ": " << msg << std::endl;
    }
References msg().
startElement() [1/2]
void XMLContentHandler::startElement (const std::string & name, const XMLHandlers::Attributes & attrib) [inline]
Handler for a start tag. Called for <doc> and <field> tags
Definition at line 178 of file doxyindexer.cpp.
    {
      m_data="";
      if (name=="field")
      {
        std::string fieldName = XMLHandlers::value(attrib,"name");
        if (fieldName=="type") m_curFieldName=TypeField;
        else if (fieldName=="name") m_curFieldName=NameField;
        else if (fieldName=="args") m_curFieldName=ArgsField;
        else if (fieldName=="tag") m_curFieldName=TagField;
        else if (fieldName=="url") m_curFieldName=UrlField;
        else if (fieldName=="keywords") m_curFieldName=KeywordField;
        else if (fieldName=="text") m_curFieldName=TextField;
        else m_curFieldName=UnknownField;
      }
    }
References ArgsField, KeywordField, m_curFieldName, m_data, setup::name, NameField, string, TagField, TextField, TypeField, UnknownField, UrlField, and XMLHandlers::value().
Referenced by main().
startElement() [2/2]
void XMLContentHandler::startElement (const std::string & name, const XMLHandlers::Attributes & attrib) [inline]
Handler for a start tag. Called for <doc> and <field> tags
Definition at line 178 of file doxyindexer.cpp.
    {
      m_data="";
      if (name=="field")
      {
        std::string fieldName = XMLHandlers::value(attrib,"name");
        if (fieldName=="type") m_curFieldName=TypeField;
        else if (fieldName=="name") m_curFieldName=NameField;
        else if (fieldName=="args") m_curFieldName=ArgsField;
        else if (fieldName=="tag") m_curFieldName=TagField;
        else if (fieldName=="url") m_curFieldName=UrlField;
        else if (fieldName=="keywords") m_curFieldName=KeywordField;
        else if (fieldName=="text") m_curFieldName=TextField;
        else m_curFieldName=UnknownField;
      }
    }
References ArgsField, KeywordField, m_curFieldName, m_data, setup::name, NameField, string, TagField, TextField, TypeField, UnknownField, UrlField, and XMLHandlers::value().
Member Data Documentation
m_curFieldName
FieldNames XMLContentHandler::m_curFieldName [private]
Definition at line 282 of file doxyindexer.cpp.
Referenced by endElement(), startElement(), and XMLContentHandler().
m_data
std::string XMLContentHandler::m_data [private]
Definition at line 281 of file doxyindexer.cpp.
Referenced by characters(), endElement(), and startElement().
m_db
Xapian::WritableDatabase XMLContentHandler::m_db [private]
Definition at line 277 of file doxyindexer.cpp.
Referenced by endElement(), and ~XMLContentHandler().
m_doc
Xapian::Document XMLContentHandler::m_doc [private]
Definition at line 278 of file doxyindexer.cpp.
Referenced by endElement(), and XMLContentHandler().
m_indexer
Xapian::TermGenerator XMLContentHandler::m_indexer [private]
Definition at line 279 of file doxyindexer.cpp.
Referenced by XMLContentHandler().
m_stemmer
Xapian::Stem XMLContentHandler::m_stemmer [private]
Definition at line 280 of file doxyindexer.cpp.
Referenced by XMLContentHandler().
The documentation for this class was generated from the following files:
doxygen/addon/doxysearch/doxyindexer.cpp
doxygen/build/doxygen/addon/doxysearch/doxyindexer.cpp