NamespaceListContext::Private Class Reference
Public Member Functions
void addNamespaces (const NamespaceLinkedMap &nsLinkedMap)
void addNamespaces (const NamespaceLinkedMap &nsLinkedMap)
Additional Inherited Members
Detailed Description
Definition at line 6212 of file context.cpp.
Member Function Documentation
addNamespaces() [1/2]
void NamespaceListContext::Private::addNamespaces (const NamespaceLinkedMap & nsLinkedMap) [inline]
Definition at line 6215 of file context.cpp.
    {
      for (const auto &nd : nsLinkedMap)
      {
        if (nd->isLinkableInProject())
        {
          append(NamespaceContext::alloc(nd.get()));
        }
      }
    }
References NamespaceContext::alloc(), and GenericNodeListContext::append().
addNamespaces() [2/2]
void NamespaceListContext::Private::addNamespaces (const NamespaceLinkedMap & nsLinkedMap) [inline]
Definition at line 6215 of file context.cpp.
    {
      for (const auto &nd : nsLinkedMap)
      {
        if (nd->isLinkableInProject())
        {
          append(NamespaceContext::alloc(nd.get()));
        }
      }
    }
References NamespaceContext::alloc().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp