ghc::filesystem::file_status Class Reference
#include <filesystem.hpp>
Public Member Functions
file_status () noexcept
file_status (file_type ft, perms prms=perms::unknown) noexcept
file_status (const file_status &) noexcept
file_status (file_status &&) noexcept
~file_status ()
file_status & operator= (const file_status &) noexcept
file_status & operator= (file_status &&) noexcept
void type (file_type ft) noexcept
void permissions (perms prms) noexcept
file_type type () const noexcept
perms permissions () const noexcept
file_status () noexcept
file_status (file_type ft, perms prms=perms::unknown) noexcept
file_status (const file_status &) noexcept
file_status (file_status &&) noexcept
~file_status ()
file_status & operator= (const file_status &) noexcept
file_status & operator= (file_status &&) noexcept
void type (file_type ft) noexcept
void permissions (perms prms) noexcept
file_type type () const noexcept
perms permissions () const noexcept
Private Attributes
file_type _type
perms _perms
Friends
bool operator== (const file_status &lhs, const file_status &rhs) noexcept
bool operator== (const file_status &lhs, const file_status &rhs) noexcept
Detailed Description
Definition at line 786 of file filesystem.hpp.
Constructor & Destructor Documentation
file_status() [1/8]
GHC_INLINE ghc::filesystem::file_status::file_status () [noexcept]
Definition at line 5012 of file filesystem.hpp.
    : file_status(file_type::none)
{
}
file_status() [2/8]
GHC_INLINE ghc::filesystem::file_status::file_status (file_type ft, perms prms = perms::unknown) [explicit], [noexcept]
Definition at line 5017 of file filesystem.hpp.
    : _type(ft)
    , _perms(prms)
{
}
file_status() [3/8]
GHC_INLINE ghc::filesystem::file_status::file_status (const file_status & other) [noexcept]
Definition at line 5023 of file filesystem.hpp.
    : _type(other._type)
    , _perms(other._perms)
{
}
file_status() [4/8]
GHC_INLINE ghc::filesystem::file_status::file_status (file_status && other) [noexcept]
Definition at line 5029 of file filesystem.hpp.
    : _type(other._type)
    , _perms(other._perms)
{
}
 file_status() [1/2]
GHC_INLINE ghc::filesystem::file_status::~file_status ()
Definition at line 5035 of file filesystem.hpp.
{}
file_status() [5/8]
ghc::filesystem::file_status::file_status () [noexcept]
file_status() [6/8]
ghc::filesystem::file_status::file_status (file_type ft, perms prms = perms::unknown) [explicit], [noexcept]
file_status() [7/8]
ghc::filesystem::file_status::file_status (const file_status &) [noexcept]
file_status() [8/8]
ghc::filesystem::file_status::file_status (file_status &&) [noexcept]
 file_status() [2/2]
ghc::filesystem::file_status::~file_status ()
Member Function Documentation
operator=() [1/4]
GHC_INLINE file_status & ghc::filesystem::file_status::operator= (const file_status & rhs) [noexcept]
Definition at line 5038 of file filesystem.hpp.
{
    _type = rhs._type;
    _perms = rhs._perms;
    return *this;
}
References _type.
operator=() [2/4]
file_status & ghc::filesystem::file_status::operator= (const file_status &) [noexcept]
operator=() [3/4]
GHC_INLINE file_status & ghc::filesystem::file_status::operator= (file_status && rhs) [noexcept]
Definition at line 5045 of file filesystem.hpp.
{
    _type = rhs._type;
    _perms = rhs._perms;
    return *this;
}
References _type.
operator=() [4/4]
file_status & ghc::filesystem::file_status::operator= (file_status &&) [noexcept]
permissions() [1/4]
GHC_INLINE perms ghc::filesystem::file_status::permissions () const [noexcept]
Definition at line 5069 of file filesystem.hpp.
{
    return _perms;
}
References _perms.
permissions() [2/4]
perms ghc::filesystem::file_status::permissions () const [noexcept]
permissions() [3/4]
GHC_INLINE void ghc::filesystem::file_status::permissions (perms prms) [noexcept]
Definition at line 5058 of file filesystem.hpp.
{
    _perms = prms;
}
Referenced by ghc::filesystem::directory_iterator::impl::copyToDirEntry(), FileInfo::isExecutable(), FileInfo::isReadable(), and FileInfo::isWritable().
permissions() [4/4]
void ghc::filesystem::file_status::permissions (perms prms) [noexcept]
type() [1/4]
GHC_INLINE file_type ghc::filesystem::file_status::type () const [noexcept]
Definition at line 5064 of file filesystem.hpp.
{
    return _type;
}
References _type.
type() [2/4]
file_type ghc::filesystem::file_status::type () const [noexcept]
type() [3/4]
GHC_INLINE void ghc::filesystem::file_status::type (file_type ft) [noexcept]
Definition at line 5053 of file filesystem.hpp.
{
    _type = ft;
}
Referenced by ghc::filesystem::directory_iterator::impl::copyToDirEntry(), and ghc::filesystem::directory_entry::status_file_type().
type() [4/4]
void ghc::filesystem::file_status::type (file_type ft) [noexcept]
Friends And Related Function Documentation
operator== [1/2]
bool operator== (const file_status & lhs, const file_status & rhs) [friend]
Definition at line 804 of file filesystem.hpp.
{ return lhs.type() == rhs.type() && lhs.permissions() == rhs.permissions(); }
operator== [2/2]
bool operator== (const file_status & lhs, const file_status & rhs) [friend]
Definition at line 804 of file filesystem.hpp.
{ return lhs.type() == rhs.type() && lhs.permissions() == rhs.permissions(); }
Member Data Documentation
_perms
perms ghc::filesystem::file_status::_perms [private]
Definition at line 807 of file filesystem.hpp.
Referenced by permissions().
_type
file_type ghc::filesystem::file_status::_type [private]
Definition at line 806 of file filesystem.hpp.
Referenced by operator=(), and type().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/filesystem/filesystem.hpp
doxygen/filesystem/filesystem.hpp