SearchIndexIntf Class Reference
#include <searchindex.h>
Public Types
enum Kind { Internal
, External
, Internal
, External
 }
enum Kind { Internal
, External
, Internal
, External
 }
using SearchIndexVariant = std::variant< SearchIndex, SearchIndexExternal >
using SearchIndexVariant = std::variant< SearchIndex, SearchIndexExternal >
Public Member Functions
SearchIndexIntf (Kind k)
void setCurrentDoc (const Definition *ctx, const QCString &anchor, bool isSourceFile)
void addWord (const QCString &word, bool hiPriority)
void write (const QCString &file)
Kind kind () const
SearchIndexIntf (Kind k)
void setCurrentDoc (const Definition *ctx, const QCString &anchor, bool isSourceFile)
void addWord (const QCString &word, bool hiPriority)
void write (const QCString &file)
Kind kind () const
Private Attributes
Kind m_kind
SearchIndexVariant m_variant
Detailed Description
Abstract proxy interface for non-javascript based search indices. It forwards calls to either SearchIndex or SearchIndexExternal depending on the Kind passed during construction.
Definition at line 170 of file searchindex.h.
Member Typedef Documentation
SearchIndexVariant [1/2]
using SearchIndexIntf::SearchIndexVariant = std::variant<SearchIndex,SearchIndexExternal>
Definition at line 173 of file searchindex.h.
SearchIndexVariant [2/2]
using SearchIndexIntf::SearchIndexVariant = std::variant<SearchIndex,SearchIndexExternal>
Definition at line 173 of file searchindex.h.
Member Enumeration Documentation
Kind [1/2]
enum SearchIndexIntf::Kind
Enumerator
Internal
External
Internal
External
Definition at line 174 of file searchindex.h.
{ Internal, External };
Kind [2/2]
enum SearchIndexIntf::Kind
Enumerator
Internal
External
Internal
External
Definition at line 174 of file searchindex.h.
{ Internal, External };
Constructor & Destructor Documentation
SearchIndexIntf() [1/2]
SearchIndexIntf::SearchIndexIntf (Kind k) [inline]
Definition at line 175 of file searchindex.h.
                            : m_kind(k),
        m_variant(k==Internal ? SearchIndexVariant(SearchIndex()) :
                                SearchIndexVariant(SearchIndexExternal())) { }
SearchIndexIntf() [2/2]
SearchIndexIntf::SearchIndexIntf (Kind k) [inline]
Definition at line 175 of file searchindex.h.
                            : m_kind(k),
        m_variant(k==Internal ? SearchIndexVariant(SearchIndex()) :
                                SearchIndexVariant(SearchIndexExternal())) { }
Member Function Documentation
addWord() [1/2]
void SearchIndexIntf::addWord (const QCString & word, bool hiPriority) [inline]
Definition at line 182 of file searchindex.h.
    {
      dispatch_call<SearchIndexMethods::addWord>(m_variant,word,hiPriority);
    }
References m_variant, and word.
Referenced by addToIndices(), SIDataCollection::transfer(), and VhdlDocGen::writeVHDLDeclaration().
addWord() [2/2]
void SearchIndexIntf::addWord (const QCString & word, bool hiPriority) [inline]
Definition at line 182 of file searchindex.h.
    {
      dispatch_call<SearchIndexMethods::addWord>(m_variant,word,hiPriority);
    }
References m_variant, and word.
kind() [1/2]
Kind SearchIndexIntf::kind () const [inline]
Definition at line 190 of file searchindex.h.
{ return m_kind; }
References m_kind.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
kind() [2/2]
Kind SearchIndexIntf::kind () const [inline]
Definition at line 190 of file searchindex.h.
{ return m_kind; }
References m_kind.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
setCurrentDoc() [1/2]
void SearchIndexIntf::setCurrentDoc (const Definition * ctx, const QCString & anchor, bool isSourceFile) [inline]
Definition at line 178 of file searchindex.h.
    {
      dispatch_call<SearchIndexMethods::setCurrentDoc>(m_variant,ctx,anchor,isSourceFile);
    }
References m_variant.
Referenced by addToIndices(), SIDataCollection::transfer(), and VhdlDocGen::writeVHDLDeclaration().
setCurrentDoc() [2/2]
void SearchIndexIntf::setCurrentDoc (const Definition * ctx, const QCString & anchor, bool isSourceFile) [inline]
Definition at line 178 of file searchindex.h.
    {
      dispatch_call<SearchIndexMethods::setCurrentDoc>(m_variant,ctx,anchor,isSourceFile);
    }
References m_variant.
write() [1/2]
void SearchIndexIntf::write (const QCString & file) [inline]
Definition at line 186 of file searchindex.h.
    {
      dispatch_call<SearchIndexMethods::write>(m_variant,file);
    }
References caseconvert::file, and m_variant.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), generateOutput(), doxmlparser.compound.memberdefType::get_write(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_write().
write() [2/2]
void SearchIndexIntf::write (const QCString & file) [inline]
Definition at line 186 of file searchindex.h.
    {
      dispatch_call<SearchIndexMethods::write>(m_variant,file);
    }
References caseconvert::file, and m_variant.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_write(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_write().
Member Data Documentation
m_kind
Kind SearchIndexIntf::m_kind [private]
Definition at line 192 of file searchindex.h.
Referenced by kind().
m_variant
SearchIndexVariant SearchIndexIntf::m_variant [private]
Definition at line 193 of file searchindex.h.
Referenced by addWord(), setCurrentDoc(), and write().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/searchindex.h
doxygen/src/searchindex.h