DotInclDepGraph Class Reference
#include <dotincldepgraph.h>
Public Member Functions
DotInclDepGraph (const FileDef *fd, bool inverse)
~DotInclDepGraph ()
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
bool isTrivial () const
bool isTooBig () const
int numNodes () const
void writeXML (TextStream &t)
void writeDocbook (TextStream &t)
DotInclDepGraph (const FileDef *fd, bool inverse)
~DotInclDepGraph ()
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
bool isTrivial () const
bool isTooBig () const
int numNodes () const
void writeXML (TextStream &t)
void writeDocbook (TextStream &t)
Protected Member Functions
virtual QCString getBaseName () const
virtual QCString getMapLabel () const
virtual void computeTheGraph ()
virtual QCString getBaseName () const
virtual QCString getMapLabel () const
virtual void computeTheGraph ()
Private Member Functions
QCString diskName () const
void buildGraph (DotNode *n, const FileDef *fd, int distance)
void determineVisibleNodes (DotNodeDeque &queue, int &maxNodes)
void determineTruncatedNodes (DotNodeDeque &queue)
QCString diskName () const
void buildGraph (DotNode *n, const FileDef *fd, int distance)
void determineVisibleNodes (DotNodeDeque &queue, int &maxNodes)
void determineTruncatedNodes (DotNodeDeque &queue)
Private Attributes
DotNode * m_startNode
DotNodeMap m_usedNodes
QCString m_inclDepFileName
QCString m_inclByDepFileName
bool m_inverse
Additional Inherited Members
Detailed Description
Representation of an include dependency graph
Definition at line 30 of file dotincldepgraph.h.
Constructor & Destructor Documentation
DotInclDepGraph() [1/2]
DotInclDepGraph::DotInclDepGraph (const FileDef * fd, bool inverse)
Definition at line 123 of file dotincldepgraph.cpp.
{
  m_inverse = inverse;
  ASSERT(fd!=0);
  m_inclDepFileName = fd->includeDependencyGraphFileName();
  m_inclByDepFileName = fd->includedByDependencyGraphFileName();
  QCString tmp_url=fd->getReference()+"$"+fd->getOutputFileBase();
  QCString tooltip = fd->briefDescriptionAsTooltip();
  m_startNode = new DotNode(getNextNodeNumber(),
                            fd->docName(),
                            tooltip,
                            tmp_url,
                            TRUE); // root node
  m_startNode->setDistance(0);
  m_usedNodes.insert(std::make_pair(fd->absFilePath().str(),m_startNode));
  buildGraph(m_startNode,fd,1);
  int maxNodes = Config_getInt(DOT_GRAPH_MAX_NODES);
  DotNodeDeque openNodeQueue;
  openNodeQueue.push_back(m_startNode);
  determineVisibleNodes(openNodeQueue,maxNodes);
  openNodeQueue.clear();
  openNodeQueue.push_back(m_startNode);
  determineTruncatedNodes(openNodeQueue);
}
References FileDef::absFilePath(), ASSERT, Definition::briefDescriptionAsTooltip(), buildGraph(), Config_getInt, determineTruncatedNodes(), determineVisibleNodes(), FileDef::docName(), DotGraph::getNextNodeNumber(), FileDef::getOutputFileBase(), Definition::getReference(), FileDef::includedByDependencyGraphFileName(), FileDef::includeDependencyGraphFileName(), m_inclByDepFileName, m_inclDepFileName, m_inverse, m_startNode, m_usedNodes, DotNode::setDistance(), QCString::str(), and TRUE.
 DotInclDepGraph() [1/2]
DotInclDepGraph::~DotInclDepGraph ()
Definition at line 149 of file dotincldepgraph.cpp.
{
  DotNode::deleteNodes(m_startNode);
}
References DotNode::deleteNodes(), and m_startNode.
DotInclDepGraph() [2/2]
DotInclDepGraph::DotInclDepGraph (const FileDef * fd, bool inverse)
 DotInclDepGraph() [2/2]
DotInclDepGraph::~DotInclDepGraph ()
Member Function Documentation
buildGraph() [1/2]
void DotInclDepGraph::buildGraph (DotNode * n, const FileDef * fd, int distance) [private]
Definition at line 22 of file dotincldepgraph.cpp.
{
  const IncludeInfoList &includeFiles = m_inverse ? fd->includedByFileList() : fd->includeFileList();
  for (const auto &ii : includeFiles)
  {
    const FileDef *bfd = ii.fileDef;
    QCString in = ii.includeName;
    //printf(">>>> in='%s' bfd=%p\n",qPrint(ii->includeName),bfd);
    bool doc=TRUE,src=FALSE;
    if (bfd)
    {
      in = bfd->absFilePath();
      doc = bfd->isLinkable() && !bfd->isHidden();
      src = bfd->generateSourceFile();
    }
    if (doc || src || !Config_getBool(HIDE_UNDOC_RELATIONS))
    {
      QCString url="";
      if (bfd) url=bfd->getOutputFileBase();
      if (!doc && src)
      {
        url=bfd->getSourceFileBase();
      }
      auto it = m_usedNodes.find(in.str());
      if (it!=m_usedNodes.end()) // file is already a node in the graph
      {
        DotNode *bn = it->second;
        n->addChild(bn,0,0);
        bn->addParent(n);
        bn->setDistance(distance);
      }
      else
      {
        QCString tmp_url;
        QCString tooltip;
        if (bfd)
        {
          tmp_url=doc || src ? bfd->getReference()+"$"+url : QCString();
          tooltip = bfd->briefDescriptionAsTooltip();
        }
        DotNode *bn = new DotNode(getNextNodeNumber(),// n
                         ii.includeName, // label
                         tooltip, // tip
                         tmp_url, // url
                         FALSE, // rootNode
                         0); // cd
        n->addChild(bn,0,0);
        bn->addParent(n);
        m_usedNodes.insert(std::make_pair(in.str(),bn));
        bn->setDistance(distance);
        if (bfd) buildGraph(bn,bfd,distance+1);
      }
    }
  }
}
References FileDef::absFilePath(), DotNode::addParent(), Definition::briefDescriptionAsTooltip(), buildGraph(), Config_getBool, FALSE, FileDef::generateSourceFile(), DotGraph::getNextNodeNumber(), FileDef::getOutputFileBase(), Definition::getReference(), FileDef::getSourceFileBase(), FileDef::includedByFileList(), FileDef::includeFileList(), Definition::isHidden(), FileDef::isLinkable(), m_inverse, m_usedNodes, n, DotNode::setDistance(), src, QCString::str(), TRUE, and setup::url.
Referenced by buildGraph(), and DotInclDepGraph().
buildGraph() [2/2]
void DotInclDepGraph::buildGraph (DotNode * n, const FileDef * fd, int distance) [private]
computeTheGraph() [1/2]
void DotInclDepGraph::computeTheGraph () [protected], [virtual]
Implements DotGraph.
Definition at line 166 of file dotincldepgraph.cpp.
{
  computeGraph(m_startNode, Dependency, m_graphFormat, "", FALSE,
               m_inverse, m_startNode->label(), m_theGraph);
}
References DotGraph::computeGraph(), Dependency, FALSE, DotNode::label(), DotGraph::m_graphFormat, m_inverse, m_startNode, and DotGraph::m_theGraph.
computeTheGraph() [2/2]
virtual void DotInclDepGraph::computeTheGraph () [protected], [virtual]
Implements DotGraph.
determineTruncatedNodes() [1/2]
void DotInclDepGraph::determineTruncatedNodes (DotNodeDeque & queue) [private]
Definition at line 98 of file dotincldepgraph.cpp.
{
  while (!queue.empty())
  {
    DotNode *n = queue.front();
    queue.pop_front();
    if (n->isVisible() && n->isTruncated()==DotNode::Unknown)
    {
      bool truncated = FALSE;
      for (const auto &dn : n->children())
      {
        if (!dn->isVisible())
        {
          truncated = TRUE;
        }
        else
        {
          queue.push_back(dn);
        }
      }
      n->markAsTruncated(truncated);
    }
  }
}
References FALSE, n, TRUE, and DotNode::Unknown.
Referenced by DotInclDepGraph().
determineTruncatedNodes() [2/2]
void DotInclDepGraph::determineTruncatedNodes (DotNodeDeque & queue) [private]
determineVisibleNodes() [1/2]
void DotInclDepGraph::determineVisibleNodes (DotNodeDeque & queue, int & maxNodes) [private]
Definition at line 79 of file dotincldepgraph.cpp.
{
  while (!queue.empty() && maxNodes>0)
  {
    DotNode *n = queue.front();
    queue.pop_front();
    if (!n->isVisible() && n->distance()<=Config_getInt(MAX_DOT_GRAPH_DEPTH)) // not yet processed
    {
      n->markAsVisible();
      maxNodes--;
      // add direct children
      for (const auto &dn : n->children())
      {
        queue.push_back(dn);
      }
    }
  }
}
References Config_getInt, and n.
Referenced by DotInclDepGraph().
determineVisibleNodes() [2/2]
void DotInclDepGraph::determineVisibleNodes (DotNodeDeque & queue, int & maxNodes) [private]
diskName() [1/2]
QCString DotInclDepGraph::diskName () const [private]
diskName() [2/2]
QCString DotInclDepGraph::diskName () const [private]
getBaseName() [1/2]
QCString DotInclDepGraph::getBaseName () const [protected], [virtual]
Implements DotGraph.
Definition at line 154 of file dotincldepgraph.cpp.
{
  if (m_inverse)
  {
    return m_inclByDepFileName;
  }
  else
  {
    return m_inclDepFileName;
  }
}
References m_inclByDepFileName, m_inclDepFileName, and m_inverse.
getBaseName() [2/2]
virtual QCString DotInclDepGraph::getBaseName () const [protected], [virtual]
Implements DotGraph.
getMapLabel() [1/2]
QCString DotInclDepGraph::getMapLabel () const [protected], [virtual]
Implements DotGraph.
Definition at line 172 of file dotincldepgraph.cpp.
{
  if (m_inverse)
  {
    return escapeCharsInString(m_startNode->label(),FALSE) + "dep";
  }
  else
  {
    return escapeCharsInString(m_startNode->label(),FALSE);
  }
}
References escapeCharsInString(), FALSE, DotNode::label(), m_inverse, and m_startNode.
getMapLabel() [2/2]
virtual QCString DotInclDepGraph::getMapLabel () const [protected], [virtual]
Implements DotGraph.
isTooBig() [1/2]
bool DotInclDepGraph::isTooBig () const
Definition at line 201 of file dotincldepgraph.cpp.
{
  return numNodes()>=Config_getInt(DOT_GRAPH_MAX_NODES);
}
References Config_getInt, and numNodes().
Referenced by FileDefImpl::writeIncludedByGraph(), and FileDefImpl::writeIncludeGraph().
isTooBig() [2/2]
bool DotInclDepGraph::isTooBig () const
isTrivial() [1/2]
bool DotInclDepGraph::isTrivial () const
Definition at line 196 of file dotincldepgraph.cpp.
{
  return m_startNode->children().empty();
}
References DotNode::children(), and m_startNode.
Referenced by generateXMLForFile(), FileDefImpl::writeIncludedByGraph(), and FileDefImpl::writeIncludeGraph().
isTrivial() [2/2]
bool DotInclDepGraph::isTrivial () const
numNodes() [1/2]
int DotInclDepGraph::numNodes () const
Definition at line 206 of file dotincldepgraph.cpp.
{
  return static_cast<int>(m_startNode->children().size());
}
References DotNode::children(), and m_startNode.
Referenced by isTooBig(), FileDefImpl::writeIncludedByGraph(), and FileDefImpl::writeIncludeGraph().
numNodes() [2/2]
int DotInclDepGraph::numNodes () const
writeDocbook() [1/2]
void DotInclDepGraph::writeDocbook (TextStream & t)
Definition at line 219 of file dotincldepgraph.cpp.
{
  for (const auto &kv : m_usedNodes)
  {
    kv.second->writeDocbook(t,FALSE);
  }
}
References FALSE, and m_usedNodes.
writeDocbook() [2/2]
void DotInclDepGraph::writeDocbook (TextStream & t)
writeGraph() [1/2]
QCString DotInclDepGraph::writeGraph (TextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1)
Definition at line 184 of file dotincldepgraph.cpp.
{
  return DotGraph::writeGraph(out, graphFormat, textFormat, path, fileName, relPath, generateImageMap, graphId);
}
References out, and DotGraph::writeGraph().
writeGraph() [2/2]
QCString DotInclDepGraph::writeGraph (TextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1)
writeXML() [1/2]
void DotInclDepGraph::writeXML (TextStream & t)
Definition at line 211 of file dotincldepgraph.cpp.
{
  for (const auto &kv : m_usedNodes)
  {
    kv.second->writeXML(t,FALSE);
  }
}
References FALSE, and m_usedNodes.
Referenced by generateXMLForFile().
writeXML() [2/2]
void DotInclDepGraph::writeXML (TextStream & t)
Member Data Documentation
m_inclByDepFileName
QCString DotInclDepGraph::m_inclByDepFileName [private]
Definition at line 58 of file dotincldepgraph.h.
Referenced by DotInclDepGraph(), and getBaseName().
m_inclDepFileName
QCString DotInclDepGraph::m_inclDepFileName [private]
Definition at line 57 of file dotincldepgraph.h.
Referenced by DotInclDepGraph(), and getBaseName().
m_inverse
bool DotInclDepGraph::m_inverse [private]
Definition at line 59 of file dotincldepgraph.h.
Referenced by buildGraph(), computeTheGraph(), DotInclDepGraph(), getBaseName(), and getMapLabel().
m_startNode
DotNode * DotInclDepGraph::m_startNode [private]
Definition at line 55 of file dotincldepgraph.h.
Referenced by computeTheGraph(), DotInclDepGraph(), getMapLabel(), isTrivial(), numNodes(), and ~DotInclDepGraph().
m_usedNodes
DotNodeMap DotInclDepGraph::m_usedNodes [private]
Definition at line 56 of file dotincldepgraph.h.
Referenced by buildGraph(), DotInclDepGraph(), writeDocbook(), and writeXML().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dotincldepgraph.h
doxygen/src/dotincldepgraph.h
doxygen/build/doxygen/src/dotincldepgraph.cpp
doxygen/src/dotincldepgraph.cpp