MemberVector Class Reference
#include <memberlist.h>
Public Types
using Ptr = const MemberDef *
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
using value_type = const MemberDef *
using const_reference = const value_type &
using Ptr = const MemberDef *
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
using value_type = const MemberDef *
using const_reference = const value_type &
Public Member Functions
void push_back (const MemberDef *md)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
size_t size () const
const_reference front () const
const_reference back () const
const_reference operator[] (int index) const
const_reference operator[] (size_t index) const
void sort ()
void inSort (const MemberDef *md)
void remove (const MemberDef *md)
bool contains (const MemberDef *md)
void push_back (const MemberDef *md)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
size_t size () const
const_reference front () const
const_reference back () const
const_reference operator[] (int index) const
const_reference operator[] (size_t index) const
void sort ()
void inSort (const MemberDef *md)
void remove (const MemberDef *md)
bool contains (const MemberDef *md)
Static Public Member Functions
static bool lessThan (const MemberDef *md1, const MemberDef *md2)
static bool lessThan (const MemberDef *md1, const MemberDef *md2)
Protected Attributes
Vec m_members
Detailed Description
A vector of MemberDef object
Definition at line 32 of file memberlist.h.
Member Typedef Documentation
const_iterator [1/2]
using MemberVector::const_iterator = typename Vec::const_iterator
Definition at line 39 of file memberlist.h.
const_iterator [2/2]
using MemberVector::const_iterator = typename Vec::const_iterator
Definition at line 39 of file memberlist.h.
const_reference [1/2]
using MemberVector::const_reference = const value_type&
Definition at line 41 of file memberlist.h.
const_reference [2/2]
using MemberVector::const_reference = const value_type&
Definition at line 41 of file memberlist.h.
iterator [1/2]
using MemberVector::iterator = typename Vec::iterator
Definition at line 38 of file memberlist.h.
iterator [2/2]
using MemberVector::iterator = typename Vec::iterator
Definition at line 38 of file memberlist.h.
Ptr [1/2]
using MemberVector::Ptr = const MemberDef *
Definition at line 36 of file memberlist.h.
Ptr [2/2]
using MemberVector::Ptr = const MemberDef *
Definition at line 36 of file memberlist.h.
value_type [1/2]
using MemberVector::value_type = const MemberDef *
Definition at line 40 of file memberlist.h.
value_type [2/2]
using MemberVector::value_type = const MemberDef *
Definition at line 40 of file memberlist.h.
Vec [1/2]
using MemberVector::Vec = std::vector<Ptr>
Definition at line 37 of file memberlist.h.
Vec [2/2]
using MemberVector::Vec = std::vector<Ptr>
Definition at line 37 of file memberlist.h.
Member Function Documentation
back() [1/2]
const_reference MemberVector::back () const [inline]
Definition at line 50 of file memberlist.h.
{ return m_members.back(); }
References m_members.
back() [2/2]
const_reference MemberVector::back () const [inline]
Definition at line 50 of file memberlist.h.
{ return m_members.back(); }
References m_members.
begin() [1/4]
iterator MemberVector::begin () [inline]
Definition at line 43 of file memberlist.h.
{ return m_members.begin(); }
References m_members.
Referenced by MemberDefImpl::_writeReimplementedBy(), refMapToVector(), and MemberDefImpl::writeEnumDeclaration().
begin() [2/4]
iterator MemberVector::begin () [inline]
Definition at line 43 of file memberlist.h.
{ return m_members.begin(); }
References m_members.
begin() [3/4]
const_iterator MemberVector::begin () const [inline]
Definition at line 45 of file memberlist.h.
{ return m_members.cbegin(); }
References m_members.
begin() [4/4]
const_iterator MemberVector::begin () const [inline]
Definition at line 45 of file memberlist.h.
{ return m_members.cbegin(); }
References m_members.
contains() [1/2]
bool MemberVector::contains (const MemberDef * md) [inline]
Definition at line 71 of file memberlist.h.
    {
      auto it = std::find(m_members.begin(),m_members.end(),md);
      return it!=m_members.end();
    }
References m_members.
Referenced by FileDefImpl::insertMember(), and MemberDefImpl::insertReimplementedBy().
contains() [2/2]
bool MemberVector::contains (const MemberDef * md) [inline]
Definition at line 71 of file memberlist.h.
    {
      auto it = std::find(m_members.begin(),m_members.end(),md);
      return it!=m_members.end();
    }
References m_members.
empty() [1/2]
bool MemberVector::empty () const [inline]
Definition at line 47 of file memberlist.h.
{ return m_members.empty(); }
References m_members.
Referenced by MemberList::addListReferences(), DotGroupCollaboration::addMemberList(), generateDEFClassSection(), generateDEFSection(), PerlModGenerator::generatePerlModForMember(), DefinitionImpl::getReferencedByMembers(), DefinitionImpl::getReferencesMembers(), writeGroupTreeNode(), and writeMemberToIndex().
empty() [2/2]
bool MemberVector::empty () const [inline]
Definition at line 47 of file memberlist.h.
{ return m_members.empty(); }
References m_members.
end() [1/4]
iterator MemberVector::end () [inline]
Definition at line 44 of file memberlist.h.
{ return m_members.end(); }
References m_members.
Referenced by MemberDefImpl::_writeReimplementedBy(), refMapToVector(), and MemberDefImpl::writeEnumDeclaration().
end() [2/4]
iterator MemberVector::end () [inline]
Definition at line 44 of file memberlist.h.
{ return m_members.end(); }
References m_members.
end() [3/4]
const_iterator MemberVector::end () const [inline]
Definition at line 46 of file memberlist.h.
{ return m_members.cend(); }
References m_members.
end() [4/4]
const_iterator MemberVector::end () const [inline]
Definition at line 46 of file memberlist.h.
{ return m_members.cend(); }
References m_members.
front() [1/2]
const_reference MemberVector::front () const [inline]
Definition at line 49 of file memberlist.h.
{ return m_members.front(); }
References m_members.
front() [2/2]
const_reference MemberVector::front () const [inline]
Definition at line 49 of file memberlist.h.
{ return m_members.front(); }
References m_members.
inSort() [1/2]
void MemberVector::inSort (const MemberDef * md) [inline]
Definition at line 62 of file memberlist.h.
    {
      m_members.insert(std::upper_bound(m_members.begin(), m_members.end(), md, lessThan), md);
    }
References lessThan(), and m_members.
Referenced by MemberDefImpl::insertReimplementedBy().
inSort() [2/2]
void MemberVector::inSort (const MemberDef * md) [inline]
Definition at line 62 of file memberlist.h.
    {
      m_members.insert(std::upper_bound(m_members.begin(), m_members.end(), md, lessThan), md);
    }
References lessThan(), and m_members.
lessThan() [1/2]
static bool MemberVector::lessThan (const MemberDef * md1, const MemberDef * md2) [inline], [static]
Definition at line 54 of file memberlist.h.
    {
      return genericCompareMembers(md1,md2)<0;
    }
References genericCompareMembers().
Referenced by inSort(), and sort().
lessThan() [2/2]
static bool MemberVector::lessThan (const MemberDef * md1, const MemberDef * md2) [inline], [static]
Definition at line 54 of file memberlist.h.
    {
      return genericCompareMembers(md1,md2)<0;
    }
References genericCompareMembers().
operator[]() [1/4]
const_reference MemberVector::operator[] (int index) const [inline]
Definition at line 51 of file memberlist.h.
{ return m_members[index]; }
References m_members.
operator[]() [2/4]
const_reference MemberVector::operator[] (int index) const [inline]
Definition at line 51 of file memberlist.h.
{ return m_members[index]; }
References m_members.
operator[]() [3/4]
const_reference MemberVector::operator[] (size_t index) const [inline]
Definition at line 52 of file memberlist.h.
{ return m_members[index]; }
References m_members.
operator[]() [4/4]
const_reference MemberVector::operator[] (size_t index) const [inline]
Definition at line 52 of file memberlist.h.
{ return m_members[index]; }
References m_members.
push_back() [1/2]
void MemberVector::push_back (const MemberDef * md) [inline]
Definition at line 42 of file memberlist.h.
{ m_members.push_back(md); }
References m_members.
Referenced by MemberGroup::addGroupedInheritedMembers(), InheritedMemberInfoListContext::Private::addMemberGroupsOfClass(), InheritedMemberInfoListContext::Private::addMemberList(), ClassContext::Private::addMembers(), getPorts(), MemberDefImpl::insertEnumField(), GroupDefImpl::insertMember(), FileDefImpl::insertMember(), and NamespaceDefImpl::insertMember().
push_back() [2/2]
void MemberVector::push_back (const MemberDef * md) [inline]
Definition at line 42 of file memberlist.h.
{ m_members.push_back(md); }
References m_members.
remove() [1/2]
void MemberVector::remove (const MemberDef * md) [inline]
Definition at line 66 of file memberlist.h.
    {
      auto it = std::find(m_members.begin(),m_members.end(),md);
      if (it!=m_members.end()) m_members.erase(it);
    }
References m_members.
Referenced by doxmlparser.compound.memberdefType::__init__(), addMembersToMemberGroup(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), GroupDefImpl::removeMemberFromList(), and doxmlparser.compound.memberdefType::set_remove().
remove() [2/2]
void MemberVector::remove (const MemberDef * md) [inline]
Definition at line 66 of file memberlist.h.
    {
      auto it = std::find(m_members.begin(),m_members.end(),md);
      if (it!=m_members.end()) m_members.erase(it);
    }
References m_members.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
size() [1/2]
size_t MemberVector::size () const [inline]
Definition at line 48 of file memberlist.h.
{ return m_members.size(); }
References m_members.
Referenced by cModule(), MemberContext::Private::createImplementedBy(), MemberContext::Private::createReimplementedBy(), listSymbols(), and GroupDefImpl::numDocMembers().
size() [2/2]
size_t MemberVector::size () const [inline]
Definition at line 48 of file memberlist.h.
{ return m_members.size(); }
References m_members.
sort() [1/2]
void MemberVector::sort () [inline]
Definition at line 58 of file memberlist.h.
    {
      std::sort(m_members.begin(),m_members.end(),lessThan);
    }
References lessThan(), and m_members.
Referenced by translator.TrManager::generateTranslatorReport(), FileDefImpl::sortMemberLists(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), and NamespaceDefImpl::writeDocumentation().
sort() [2/2]
void MemberVector::sort () [inline]
Definition at line 58 of file memberlist.h.
    {
      std::sort(m_members.begin(),m_members.end(),lessThan);
    }
References lessThan(), and m_members.
Referenced by translator.TrManager::generateTranslatorReport().
Member Data Documentation
m_members
Vec MemberVector::m_members [protected]
Definition at line 77 of file memberlist.h.
Referenced by MemberList::addListReferences(), back(), begin(), contains(), MemberList::countDecMembers(), MemberList::countDocMembers(), MemberList::countEnumValues(), MemberList::countInheritableMembers(), MemberList::declVisible(), empty(), end(), MemberList::findSectionsInDocumentation(), front(), inSort(), operator[](), push_back(), remove(), MemberList::setAnchors(), MemberList::setAnonymousEnumType(), size(), sort(), MemberList::writeDocumentation(), MemberList::writeDocumentationPage(), MemberList::writePlainDeclarations(), MemberList::writeSimpleDocumentation(), and MemberList::writeTagFile().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/memberlist.h
doxygen/src/memberlist.h