DocIndexEntry Class Reference
#include <docnode.h>
Public Member Functions
DocIndexEntry (DocParser *parser, DocNodeVariant *parent, const Definition *scope, const MemberDef *md)
int parse (DocNodeVariant *)
const Definition * scope () const
const MemberDef * member () const
QCString entry () const
DocIndexEntry (DocParser *parser, DocNodeVariant *parent, const Definition *scope, const MemberDef *md)
int parse (DocNodeVariant *)
const Definition * scope () const
const MemberDef * member () const
QCString entry () const
Private Attributes
QCString m_entry
const Definition * m_scope = 0
const MemberDef * m_member = 0
Additional Inherited Members
Detailed Description
Node representing an entry in the index.
Definition at line 522 of file docnode.h.
Constructor & Destructor Documentation
DocIndexEntry() [1/2]
DocIndexEntry::DocIndexEntry (DocParser * parser, DocNodeVariant * parent, const Definition * scope, const MemberDef * md) [inline]
Definition at line 525 of file docnode.h.
      : DocNode(parser,parent), m_scope(scope), m_member(md) {}
DocIndexEntry() [2/2]
DocIndexEntry::DocIndexEntry (DocParser * parser, DocNodeVariant * parent, const Definition * scope, const MemberDef * md) [inline]
Definition at line 525 of file docnode.h.
      : DocNode(parser,parent), m_scope(scope), m_member(md) {}
Member Function Documentation
entry() [1/2]
QCString DocIndexEntry::entry () const [inline]
Definition at line 530 of file docnode.h.
{ return m_entry; }
References m_entry.
Referenced by doxmlparser.compound.docRowType::__init__(), doxmlparser.compound.docRowType::add_entry(), doxmlparser.compound.docRowType::get_entry(), doxmlparser.compound.docRowType::hasContent_(), doxmlparser.compound.docRowType::insert_entry_at(), DocbookDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), doxmlparser.compound.docRowType::replace_entry_at(), and doxmlparser.compound.docRowType::set_entry().
entry() [2/2]
QCString DocIndexEntry::entry () const [inline]
Definition at line 530 of file docnode.h.
{ return m_entry; }
References m_entry.
Referenced by doxmlparser.compound.docRowType::__init__(), doxmlparser.compound.docRowType::add_entry(), doxmlparser.compound.docRowType::get_entry(), doxmlparser.compound.docRowType::hasContent_(), doxmlparser.compound.docRowType::insert_entry_at(), doxmlparser.compound.docRowType::replace_entry_at(), and doxmlparser.compound.docRowType::set_entry().
member() [1/2]
const MemberDef * DocIndexEntry::member () const [inline]
Definition at line 529 of file docnode.h.
{ return m_member; }
References m_member.
Referenced by doxmlparser.compound.listofallmembersType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.listofallmembersType::add_member(), doxmlparser.index.CompoundType::add_member(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.listofallmembersType::get_member(), doxmlparser.index.CompoundType::get_member(), doxmlparser.compound.listofallmembersType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.compound.listofallmembersType::insert_member_at(), doxmlparser.index.CompoundType::insert_member_at(), doxmlparser.compound.listofallmembersType::replace_member_at(), doxmlparser.index.CompoundType::replace_member_at(), doxmlparser.compound.listofallmembersType::set_member(), and doxmlparser.index.CompoundType::set_member().
member() [2/2]
const MemberDef * DocIndexEntry::member () const [inline]
Definition at line 529 of file docnode.h.
{ return m_member; }
References m_member.
Referenced by doxmlparser.compound.listofallmembersType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.listofallmembersType::add_member(), doxmlparser.index.CompoundType::add_member(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.listofallmembersType::get_member(), doxmlparser.index.CompoundType::get_member(), doxmlparser.compound.listofallmembersType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.compound.listofallmembersType::insert_member_at(), doxmlparser.index.CompoundType::insert_member_at(), doxmlparser.compound.listofallmembersType::replace_member_at(), doxmlparser.index.CompoundType::replace_member_at(), doxmlparser.compound.listofallmembersType::set_member(), and doxmlparser.index.CompoundType::set_member().
parse() [1/2]
int DocIndexEntry::parse (DocNodeVariant * thisVariant)
Definition at line 1460 of file docnode.cpp.
{
  int retval=RetVal_OK;
  auto ns = AutoNodeStack(parser(),thisVariant);
  DBG(("DocIndexEntry::parse() start\n"));
  int tok=parser()->tokenizer.lex();
  if (tok!=TK_WHITESPACE)
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected whitespace after \\addindex command");
    goto endindexentry;
  }
  parser()->tokenizer.setStateTitle();
  m_entry="";
  while ((tok=parser()->tokenizer.lex()))
  {
    switch (tok)
    {
      case TK_WHITESPACE:
        m_entry+=" ";
        break;
      case TK_WORD:
      case TK_LNKWORD:
        m_entry+=parser()->context.token->name;
        break;
      case TK_SYMBOL:
        {
          HtmlEntityMapper::SymType s = DocSymbol::decodeSymbol(parser()->context.token->name);
          switch (s)
          {
            case HtmlEntityMapper::Sym_BSlash: m_entry+='\\'; break;
            case HtmlEntityMapper::Sym_At: m_entry+='@'; break;
            case HtmlEntityMapper::Sym_Less: m_entry+='<'; break;
            case HtmlEntityMapper::Sym_Greater: m_entry+='>'; break;
            case HtmlEntityMapper::Sym_Amp: m_entry+='&'; break;
            case HtmlEntityMapper::Sym_Dollar: m_entry+='$'; break;
            case HtmlEntityMapper::Sym_Hash: m_entry+='#'; break;
            case HtmlEntityMapper::Sym_Percent: m_entry+='%'; break;
            case HtmlEntityMapper::Sym_apos: m_entry+='\''; break;
            case HtmlEntityMapper::Sym_Quot: m_entry+='"'; break;
            case HtmlEntityMapper::Sym_lsquo: m_entry+='`'; break;
            case HtmlEntityMapper::Sym_rsquo: m_entry+='\''; break;
            case HtmlEntityMapper::Sym_ldquo: m_entry+="``"; break;
            case HtmlEntityMapper::Sym_rdquo: m_entry+="''"; break;
            case HtmlEntityMapper::Sym_ndash: m_entry+="--"; break;
            case HtmlEntityMapper::Sym_mdash: m_entry+="---"; break;
            default:
              warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected symbol found as argument of \\addindex");
              break;
          }
        }
        break;
      case TK_COMMAND_AT:
        // fall through
      case TK_COMMAND_BS:
        switch (Mappers::cmdMapper->map(parser()->context.token->name))
        {
          case CMD_BSLASH: m_entry+='\\'; break;
          case CMD_AT: m_entry+='@'; break;
          case CMD_LESS: m_entry+='<'; break;
          case CMD_GREATER: m_entry+='>'; break;
          case CMD_AMP: m_entry+='&'; break;
          case CMD_DOLLAR: m_entry+='$'; break;
          case CMD_HASH: m_entry+='#'; break;
          case CMD_DCOLON: m_entry+="::"; break;
          case CMD_PERCENT: m_entry+='%'; break;
          case CMD_NDASH: m_entry+="--"; break;
          case CMD_MDASH: m_entry+="---"; break;
          case CMD_QUOTE: m_entry+='"'; break;
          case CMD_PUNT: m_entry+='.'; break;
          case CMD_PLUS: m_entry+='+'; break;
          case CMD_MINUS: m_entry+='-'; break;
          case CMD_EQUAL: m_entry+='='; break;
          default:
               warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected command %s found as argument of \\addindex",
                              qPrint(parser()->context.token->name));
               break;
        }
      break;
      default:
        warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected token %s",
            DocTokenizer::tokToString(tok));
        break;
    }
  }
  parser()->tokenizer.setStatePara();
  m_entry = m_entry.stripWhiteSpace();
endindexentry:
  DBG(("DocIndexEntry::parse() end retval=%s\n",DocTokenizer::retvalToString(retval)));
  return retval;
}
References CMD_AMP, CMD_AT, CMD_BSLASH, CMD_DCOLON, CMD_DOLLAR, CMD_EQUAL, CMD_GREATER, CMD_HASH, CMD_LESS, CMD_MDASH, CMD_MINUS, CMD_NDASH, CMD_PERCENT, CMD_PLUS, CMD_PUNT, CMD_QUOTE, Mappers::cmdMapper, DocParser::context, DBG, DocSymbol::decodeSymbol(), DocTokenizer::lex(), m_entry, TokenInfo::name, DocNode::parser(), qPrint(), RetVal_OK, DocTokenizer::retvalToString(), s, DocTokenizer::setStatePara(), DocTokenizer::setStateTitle(), QCString::stripWhiteSpace(), HtmlEntityMapper::Sym_Amp, HtmlEntityMapper::Sym_apos, HtmlEntityMapper::Sym_At, HtmlEntityMapper::Sym_BSlash, HtmlEntityMapper::Sym_Dollar, HtmlEntityMapper::Sym_Greater, HtmlEntityMapper::Sym_Hash, HtmlEntityMapper::Sym_ldquo, HtmlEntityMapper::Sym_Less, HtmlEntityMapper::Sym_lsquo, HtmlEntityMapper::Sym_mdash, HtmlEntityMapper::Sym_ndash, HtmlEntityMapper::Sym_Percent, HtmlEntityMapper::Sym_Quot, HtmlEntityMapper::Sym_rdquo, HtmlEntityMapper::Sym_rsquo, TK_COMMAND_AT, TK_COMMAND_BS, TK_LNKWORD, TK_SYMBOL, TK_WHITESPACE, TK_WORD, DocParserContext::token, DocParser::tokenizer, DocTokenizer::tokToString(), and warn_doc_error().
parse() [2/2]
int DocIndexEntry::parse (DocNodeVariant *)
scope() [1/2]
const Definition * DocIndexEntry::scope () const [inline]
Definition at line 528 of file docnode.h.
{ return m_scope; }
References m_scope.
Referenced by doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.compound.memberRefType::get_scope(), doxmlparser.compound.memberRefType::hasContent_(), and doxmlparser.compound.memberRefType::set_scope().
scope() [2/2]
const Definition * DocIndexEntry::scope () const [inline]
Definition at line 528 of file docnode.h.
{ return m_scope; }
References m_scope.
Referenced by doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.compound.memberRefType::get_scope(), doxmlparser.compound.memberRefType::hasContent_(), and doxmlparser.compound.memberRefType::set_scope().
Member Data Documentation
m_entry
QCString DocIndexEntry::m_entry [private]
Definition at line 533 of file docnode.h.
Referenced by entry(), and parse().
m_member
const MemberDef * DocIndexEntry::m_member = 0 [private]
Definition at line 535 of file docnode.h.
Referenced by member().
m_scope
const Definition * DocIndexEntry::m_scope = 0 [private]
Definition at line 534 of file docnode.h.
Referenced by scope().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp