DocVisitor Class Reference
Helper base class for functionality shared by all visitors.
#include <docvisitor.h>
Classes
struct Private
Public Member Functions
DocVisitor ()
virtual ~DocVisitor ()
CodeParserInterface & getCodeParser (const QCString &langExt)
void pushHidden (bool hide)
bool popHidden ()
DocVisitor ()
virtual ~DocVisitor ()
CodeParserInterface & getCodeParser (const QCString &langExt)
void pushHidden (bool hide)
bool popHidden ()
Private Attributes
std::unique_ptr< Private > m_p
Detailed Description
Helper base class for functionality shared by all visitors.
Definition at line 27 of file docvisitor.h.
Constructor & Destructor Documentation
DocVisitor() [1/2]
DocVisitor::DocVisitor ()
Definition at line 32 of file docvisitor.cpp.
                       : m_p(std::make_unique<Private>())
{
}
 DocVisitor() [1/2]
DocVisitor::~DocVisitor () [virtual]
Definition at line 36 of file docvisitor.cpp.
{
}
DocVisitor() [2/2]
DocVisitor::DocVisitor ()
 DocVisitor() [2/2]
virtual DocVisitor::~DocVisitor () [virtual]
Member Function Documentation
getCodeParser() [1/2]
CodeParserInterface & DocVisitor::getCodeParser (const QCString & langExt)
Definition at line 40 of file docvisitor.cpp.
{
  std::string ext = extension.str();
  // for each extension we create a code parser once per visitor, so that
  // the context of the same parser object is reused throughout multiple passes for instance
  // for code fragments shown via dontinclude.
  auto it = m_p->parserFactoryMap.find(ext);
  if (it==m_p->parserFactoryMap.end())
  {
    auto factory = Doxygen::parserManager->getCodeParserFactory(extension);
    auto result = m_p->parserFactoryMap.insert(std::make_pair(ext,factory()));
    it = result.first;
  }
  return *it->second.get();
}
References ParserManager::getCodeParserFactory(), m_p, Doxygen::parserManager, QCString::str(), and string.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
getCodeParser() [2/2]
CodeParserInterface & DocVisitor::getCodeParser (const QCString & langExt)
popHidden() [1/2]
bool DocVisitor::popHidden ()
Definition at line 61 of file docvisitor.cpp.
{
  if (m_p->hidden.empty()) return false;
  bool v = m_p->hidden.top();
  m_p->hidden.pop();
  return v;
}
References m_p.
Referenced by RTFDocVisitor::includePicturePostRTF(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
popHidden() [2/2]
bool DocVisitor::popHidden ()
pushHidden() [1/2]
void DocVisitor::pushHidden (bool hide)
Definition at line 56 of file docvisitor.cpp.
{
  m_p->hidden.push(hide);
}
References m_p.
Referenced by RTFDocVisitor::includePicturePreRTF(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
pushHidden() [2/2]
void DocVisitor::pushHidden (bool hide)
Member Data Documentation
m_p
std::unique_ptr< Private > DocVisitor::m_p [private]
Definition at line 30 of file docvisitor.h.
Referenced by getCodeParser(), popHidden(), and pushHidden().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docvisitor.h
doxygen/src/docvisitor.h
doxygen/build/doxygen/src/docvisitor.cpp
doxygen/src/docvisitor.cpp