NestingContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
void addNamespaces (const NamespaceLinkedMap &nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet &visitedClasses)
void addNamespaces (const NamespaceLinkedRefMap &nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet &visitedClasses)
void addClasses (const ClassLinkedMap &clLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addClasses (const ClassLinkedRefMap &clLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addConcepts (const ConceptLinkedMap &cnLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addConcepts (const ConceptLinkedRefMap &cnLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addDirs (const DirLinkedMap &, ClassDefSet &visitedClasses)
void addDirs (const DirList &, ClassDefSet &visitedClasses)
void addFiles (const FileNameLinkedMap &, ClassDefSet &visitedClasses)
void addFiles (const FileList &, ClassDefSet &visitedClasses)
void addPages (const PageLinkedMap &pages, bool rootOnly, ClassDefSet &visitedClasses)
void addPages (const PageLinkedRefMap &pages, bool rootOnly, ClassDefSet &visitedClasses)
void addModules (const GroupLinkedMap &modules, ClassDefSet &visitedClasses)
void addModules (const GroupList &modules, ClassDefSet &visitedClasses)
void addClassHierarchy (const ClassLinkedMap &clLinkedMap, ClassDefSet &visitedClasses)
void addDerivedClasses (const BaseClassList &bcl, bool hideSuper, ClassDefSet &visitedClasses)
void addMembers (const MemberVector &mv, ClassDefSet &visitedClasses)
NestingContext (const NestingNodeContext *parent, ContextTreeType type, int level)
virtual ~NestingContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
void addNamespaces (const NamespaceLinkedMap &nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet &visitedClasses)
void addNamespaces (const NamespaceLinkedRefMap &nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet &visitedClasses)
void addClasses (const ClassLinkedMap &clLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addClasses (const ClassLinkedRefMap &clLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addConcepts (const ConceptLinkedMap &cnLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addConcepts (const ConceptLinkedRefMap &cnLinkedMap, bool rootOnly, ClassDefSet &visitedClasses)
void addDirs (const DirLinkedMap &, ClassDefSet &visitedClasses)
void addDirs (const DirList &, ClassDefSet &visitedClasses)
void addFiles (const FileNameLinkedMap &, ClassDefSet &visitedClasses)
void addFiles (const FileList &, ClassDefSet &visitedClasses)
void addPages (const PageLinkedMap &pages, bool rootOnly, ClassDefSet &visitedClasses)
void addPages (const PageLinkedRefMap &pages, bool rootOnly, ClassDefSet &visitedClasses)
void addModules (const GroupLinkedMap &modules, ClassDefSet &visitedClasses)
void addModules (const GroupList &modules, ClassDefSet &visitedClasses)
void addClassHierarchy (const ClassLinkedMap &clLinkedMap, ClassDefSet &visitedClasses)
void addDerivedClasses (const BaseClassList &bcl, bool hideSuper, ClassDefSet &visitedClasses)
void addMembers (const MemberVector &mv, ClassDefSet &visitedClasses)
NestingContext (const NestingNodeContext *parent, ContextTreeType type, int level)
virtual ~NestingContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc (const NestingNodeContext *parent, ContextTreeType type, int level)
static TemplateListIntfPtr alloc (const NestingNodeContext *parent, ContextTreeType type, int level)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 526 of file context.h.
Constructor & Destructor Documentation
NestingContext() [1/2]
NestingContext::NestingContext (const NestingNodeContext * parent, ContextTreeType type, int level)
Definition at line 5975 of file context.cpp.
                                                                                              : p(std::make_unique<Private>(parent,type,level))
{
}
 NestingContext() [1/2]
NestingContext::~NestingContext () [virtual]
Definition at line 5979 of file context.cpp.
{
}
NestingContext() [2/2]
NestingContext::NestingContext (const NestingNodeContext * parent, ContextTreeType type, int level)
 NestingContext() [2/2]
virtual NestingContext::~NestingContext () [virtual]
Member Function Documentation
addClasses() [1/4]
void NestingContext::addClasses (const ClassLinkedMap & clLinkedMap, bool rootOnly, ClassDefSet & visitedClasses)
Definition at line 6004 of file context.cpp.
{
  p->addClasses(clLinkedMap,rootOnly,visitedClasses);
}
References p.
Referenced by addNamespaces().
addClasses() [2/4]
void NestingContext::addClasses (const ClassLinkedMap & clLinkedMap, bool rootOnly, ClassDefSet & visitedClasses)
addClasses() [3/4]
void NestingContext::addClasses (const ClassLinkedRefMap & clLinkedMap, bool rootOnly, ClassDefSet & visitedClasses)
Definition at line 5999 of file context.cpp.
{
  p->addClasses(clLinkedRefMap,rootOnly,visitedClasses);
}
References p.
addClasses() [4/4]
void NestingContext::addClasses (const ClassLinkedRefMap & clLinkedMap, bool rootOnly, ClassDefSet & visitedClasses)
addClassHierarchy() [1/2]
void NestingContext::addClassHierarchy (const ClassLinkedMap & clLinkedMap, ClassDefSet & visitedClasses)
Definition at line 6069 of file context.cpp.
{
  p->addClassHierarchy(classLinkedMap,visitedClasses);
}
References p.
addClassHierarchy() [2/2]
void NestingContext::addClassHierarchy (const ClassLinkedMap & clLinkedMap, ClassDefSet & visitedClasses)
addConcepts() [1/4]
void NestingContext::addConcepts (const ConceptLinkedMap & cnLinkedMap, bool rootOnly, ClassDefSet & visitedClasses)
Definition at line 6014 of file context.cpp.
{
  p->addConcepts(cpLinkedMap,rootOnly,visitedClasses);
}
References p.
Referenced by addNamespaces().
addConcepts() [2/4]
void NestingContext::addConcepts (const ConceptLinkedMap & cnLinkedMap, bool rootOnly, ClassDefSet & visitedClasses)
addConcepts() [3/4]
void NestingContext::addConcepts (const ConceptLinkedRefMap & cnLinkedMap, bool rootOnly, ClassDefSet & visitedClasses)
Definition at line 6009 of file context.cpp.
{
  p->addConcepts(cpLinkedRefMap,rootOnly,visitedClasses);
}
References p.
addConcepts() [4/4]
void NestingContext::addConcepts (const ConceptLinkedRefMap & cnLinkedMap, bool rootOnly, ClassDefSet & visitedClasses)
addDerivedClasses() [1/2]
void NestingContext::addDerivedClasses (const BaseClassList & bcl, bool hideSuper, ClassDefSet & visitedClasses)
Definition at line 6074 of file context.cpp.
{
  p->addDerivedClasses(bcl,hideSuper,visitedClasses);
}
References p.
addDerivedClasses() [2/2]
void NestingContext::addDerivedClasses (const BaseClassList & bcl, bool hideSuper, ClassDefSet & visitedClasses)
addDirs() [1/4]
void NestingContext::addDirs (const DirLinkedMap & dirs, ClassDefSet & visitedClasses)
Definition at line 6029 of file context.cpp.
{
  p->addDirs(dirs,visitedClasses);
}
References p.
addDirs() [2/4]
void NestingContext::addDirs (const DirLinkedMap & , ClassDefSet & visitedClasses)
addDirs() [3/4]
void NestingContext::addDirs (const DirList & dirs, ClassDefSet & visitedClasses)
Definition at line 6034 of file context.cpp.
{
  p->addDirs(dirs,visitedClasses);
}
References p.
addDirs() [4/4]
void NestingContext::addDirs (const DirList & , ClassDefSet & visitedClasses)
addFiles() [1/4]
void NestingContext::addFiles (const FileList & files, ClassDefSet & visitedClasses)
Definition at line 6044 of file context.cpp.
{
  p->addFiles(files,visitedClasses);
}
References p.
addFiles() [2/4]
void NestingContext::addFiles (const FileList & , ClassDefSet & visitedClasses)
addFiles() [3/4]
void NestingContext::addFiles (const FileNameLinkedMap & files, ClassDefSet & visitedClasses)
Definition at line 6039 of file context.cpp.
{
  p->addFiles(files,visitedClasses);
}
References p.
addFiles() [4/4]
void NestingContext::addFiles (const FileNameLinkedMap & , ClassDefSet & visitedClasses)
addMembers() [1/2]
void NestingContext::addMembers (const MemberVector & mv, ClassDefSet & visitedClasses)
Definition at line 6079 of file context.cpp.
{
  p->addMembers(mv,visitedClasses);
}
References p.
addMembers() [2/2]
void NestingContext::addMembers (const MemberVector & mv, ClassDefSet & visitedClasses)
addModules() [1/4]
void NestingContext::addModules (const GroupLinkedMap & modules, ClassDefSet & visitedClasses)
Definition at line 6059 of file context.cpp.
{
  p->addModules(modules,visitedClasses);
}
References p.
addModules() [2/4]
void NestingContext::addModules (const GroupLinkedMap & modules, ClassDefSet & visitedClasses)
addModules() [3/4]
void NestingContext::addModules (const GroupList & modules, ClassDefSet & visitedClasses)
Definition at line 6064 of file context.cpp.
{
  p->addModules(modules,visitedClasses);
}
References p.
addModules() [4/4]
void NestingContext::addModules (const GroupList & modules, ClassDefSet & visitedClasses)
addNamespaces() [1/4]
void NestingContext::addNamespaces (const NamespaceLinkedMap & nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet & visitedClasses)
Definition at line 6019 of file context.cpp.
{
  p->addNamespaces(nsLinkedMap,rootOnly,addClasses,addConcepts,visitedClasses);
}
References addClasses(), addConcepts(), and p.
addNamespaces() [2/4]
void NestingContext::addNamespaces (const NamespaceLinkedMap & nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet & visitedClasses)
addNamespaces() [3/4]
void NestingContext::addNamespaces (const NamespaceLinkedRefMap & nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet & visitedClasses)
Definition at line 6024 of file context.cpp.
{
  p->addNamespaces(nsLinkedRefMap,rootOnly,addClasses,addConcepts,visitedClasses);
}
References addClasses(), addConcepts(), and p.
addNamespaces() [4/4]
void NestingContext::addNamespaces (const NamespaceLinkedRefMap & nsLinkedMap, bool rootOnly, bool addClasses, bool addConcepts, ClassDefSet & visitedClasses)
addPages() [1/4]
void NestingContext::addPages (const PageLinkedMap & pages, bool rootOnly, ClassDefSet & visitedClasses)
Definition at line 6049 of file context.cpp.
{
  p->addPages(pages,rootOnly,visitedClasses);
}
References p.
addPages() [2/4]
void NestingContext::addPages (const PageLinkedMap & pages, bool rootOnly, ClassDefSet & visitedClasses)
addPages() [3/4]
void NestingContext::addPages (const PageLinkedRefMap & pages, bool rootOnly, ClassDefSet & visitedClasses)
Definition at line 6054 of file context.cpp.
{
  p->addPages(pages,rootOnly,visitedClasses);
}
References p.
addPages() [4/4]
void NestingContext::addPages (const PageLinkedRefMap & pages, bool rootOnly, ClassDefSet & visitedClasses)
alloc() [1/2]
static TemplateListIntfPtr NestingContext::alloc (const NestingNodeContext * parent, ContextTreeType type, int level) [inline], [static]
Definition at line 530 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<NestingContext>(parent,type,level)); }
References level, and parent().
Referenced by ClassHierarchyContext::Private::Private(), ClassTreeContext::Private::Private(), NamespaceTreeContext::Private::Private(), FileTreeContext::Private::Private(), ConceptTreeContext::Private::Private(), ModuleTreeContext::Private::Private(), ExampleTreeContext::Private::Private(), NestingNodeContext::Private::Private(), and PageTreeContext::Private::Private().
alloc() [2/2]
static TemplateListIntfPtr NestingContext::alloc (const NestingNodeContext * parent, ContextTreeType type, int level) [inline], [static]
Definition at line 530 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<NestingContext>(parent,type,level)); }
References level, and parent().
at() [1/2]
TemplateVariant NestingContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 5989 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant NestingContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t NestingContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 5984 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t NestingContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr NestingContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 5994 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr NestingContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > NestingContext::p [private]
Definition at line 561 of file context.h.
Referenced by addClasses(), addClassHierarchy(), addConcepts(), addDerivedClasses(), addDirs(), addFiles(), addMembers(), addModules(), addNamespaces(), addPages(), at(), count(), and createIterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp