Markdown Class Reference
Helper class to process markdown formatted text.
#include <markdown.h>
Classes
struct LinkRef
Public Member Functions
Markdown (const QCString &fileName, int lineNr, int indentLevel=0)
QCString process (const QCString &input, int &startNewlines, bool fromParseInput=false)
QCString extractPageTitle (QCString &docs, QCString &id, int &prepend)
void setIndentLevel (int level)
Markdown (const QCString &fileName, int lineNr, int indentLevel=0)
QCString process (const QCString &input, int &startNewlines, bool fromParseInput=false)
QCString extractPageTitle (QCString &docs, QCString &id, int &prepend)
void setIndentLevel (int level)
Private Types
using Action_t = std::function< int(const char *, int, int)>
using Action_t = std::function< int(const char *, int, int)>
Private Member Functions
QCString detab (const QCString &s, int &refIndent)
QCString processQuotations (const QCString &s, int refIndent)
QCString processBlocks (const QCString &s, int indent)
QCString isBlockCommand (const char *data, int offset, int size)
int isSpecialCommand (const char *data, int offset, int size)
void findEndOfLine (const char *data, int size, int &pi, int &i, int &end)
int processHtmlTagWrite (const char *data, int offset, int size, bool doWrite)
int processHtmlTag (const char *data, int offset, int size)
int processEmphasis (const char *data, int offset, int size)
int processEmphasis1 (const char *data, int size, char c)
int processEmphasis2 (const char *data, int size, char c)
int processEmphasis3 (const char *data, int size, char c)
int processNmdash (const char *data, int off, int size)
int processQuoted (const char *data, int, int size)
int processCodeSpan (const char *data, int, int size)
void addStrEscapeUtf8Nbsp (const char *s, int len)
int processSpecialCommand (const char *data, int offset, int size)
int processLink (const char *data, int, int size)
int findEmphasisChar (const char *data, int size, char c, int c_size)
void processInline (const char *data, int size)
void writeMarkdownImage (const char *fmt, bool inline_img, bool explicitTitle, const QCString &title, const QCString &content, const QCString &link, const QCString &attributes, const FileDef *fd)
int isHeaderline (const char *data, int size, bool allowAdjustLevel)
int isAtxHeader (const char *data, int size, QCString &header, QCString &id, bool allowAdjustLevel)
void writeOneLineHeaderOrRuler (const char *data, int size)
void writeFencedCodeBlock (const char *data, const char *lng, int blockStart, int blockEnd)
int writeBlockQuote (const char *data, int size)
int writeCodeBlock (const char *data, int size, int refIndent)
int writeTableBlock (const char *data, int size)
QCString detab (const QCString &s, int &refIndent)
QCString processQuotations (const QCString &s, int refIndent)
QCString processBlocks (const QCString &s, int indent)
QCString isBlockCommand (const char *data, int offset, int size)
int isSpecialCommand (const char *data, int offset, int size)
void findEndOfLine (const char *data, int size, int &pi, int &i, int &end)
int processHtmlTagWrite (const char *data, int offset, int size, bool doWrite)
int processHtmlTag (const char *data, int offset, int size)
int processEmphasis (const char *data, int offset, int size)
int processEmphasis1 (const char *data, int size, char c)
int processEmphasis2 (const char *data, int size, char c)
int processEmphasis3 (const char *data, int size, char c)
int processNmdash (const char *data, int off, int size)
int processQuoted (const char *data, int, int size)
int processCodeSpan (const char *data, int, int size)
void addStrEscapeUtf8Nbsp (const char *s, int len)
int processSpecialCommand (const char *data, int offset, int size)
int processLink (const char *data, int, int size)
int findEmphasisChar (const char *data, int size, char c, int c_size)
void processInline (const char *data, int size)
void writeMarkdownImage (const char *fmt, bool inline_img, bool explicitTitle, const QCString &title, const QCString &content, const QCString &link, const QCString &attributes, const FileDef *fd)
int isHeaderline (const char *data, int size, bool allowAdjustLevel)
int isAtxHeader (const char *data, int size, QCString &header, QCString &id, bool allowAdjustLevel)
void writeOneLineHeaderOrRuler (const char *data, int size)
void writeFencedCodeBlock (const char *data, const char *lng, int blockStart, int blockEnd)
int writeBlockQuote (const char *data, int size)
int writeCodeBlock (const char *data, int size, int refIndent)
int writeTableBlock (const char *data, int size)
Private Attributes
std::unordered_map< std::string, LinkRef > m_linkRefs
QCString m_fileName
int m_lineNr = 0
int m_indentLevel =0
GrowBuf m_out
Markdown::Action_t m_actions [256]
Detailed Description
Helper class to process markdown formatted text.
Definition at line 32 of file markdown.h.
Member Typedef Documentation
Action_t [1/2]
using Markdown::Action_t = std::function<int(const char *,int,int)> [private]
Definition at line 82 of file markdown.h.
Action_t [2/2]
using Markdown::Action_t = std::function<int(const char *,int,int)> [private]
Definition at line 82 of file markdown.h.
Constructor & Destructor Documentation
Markdown() [1/2]
Markdown::Markdown (const QCString & fileName, int lineNr, int indentLevel = 0)
Definition at line 218 of file markdown.cpp.
  : m_fileName(fileName), m_lineNr(lineNr), m_indentLevel(indentLevel)
{
  using namespace std::placeholders;
  // setup callback table for special characters
  m_actions[static_cast<unsigned int>('_')] = std::bind(&Markdown::processEmphasis, this,_1,_2,_3);
  m_actions[static_cast<unsigned int>('*')] = std::bind(&Markdown::processEmphasis, this,_1,_2,_3);
  m_actions[static_cast<unsigned int>('~')] = std::bind(&Markdown::processEmphasis, this,_1,_2,_3);
  m_actions[static_cast<unsigned int>('`')] = std::bind(&Markdown::processCodeSpan, this,_1,_2,_3);
  m_actions[static_cast<unsigned int>('\\')]= std::bind(&Markdown::processSpecialCommand,this,_1,_2,_3);
  m_actions[static_cast<unsigned int>('@')] = std::bind(&Markdown::processSpecialCommand,this,_1,_2,_3);
  m_actions[static_cast<unsigned int>('[')] = std::bind(&Markdown::processLink, this,_1,_2,_3);
  m_actions[static_cast<unsigned int>('!')] = std::bind(&Markdown::processLink, this,_1,_2,_3);
  m_actions[static_cast<unsigned int>('<')] = std::bind(&Markdown::processHtmlTag, this,_1,_2,_3);
  m_actions[static_cast<unsigned int>('-')] = std::bind(&Markdown::processNmdash, this,_1,_2,_3);
  m_actions[static_cast<unsigned int>('"')] = std::bind(&Markdown::processQuoted, this,_1,_2,_3);
  (void)m_lineNr; // not used yet
}
References m_actions, m_lineNr, processCodeSpan(), processEmphasis(), processHtmlTag(), processLink(), processNmdash(), processQuoted(), and processSpecialCommand().
Markdown() [2/2]
Markdown::Markdown (const QCString & fileName, int lineNr, int indentLevel = 0)
Member Function Documentation
addStrEscapeUtf8Nbsp() [1/2]
void Markdown::addStrEscapeUtf8Nbsp (const char * s, int len) [private]
Definition at line 1687 of file markdown.cpp.
{
  TRACE(s);
  if (Portable::strnstr(s,g_doxy_nbsp,len)==0) // no escape needed -> fast
  {
    m_out.addStr(s,len);
  }
  else // escape needed -> slow
  {
    m_out.addStr(substitute(QCString(s).left(len),g_doxy_nbsp,g_utf8_nbsp));
  }
}
References GrowBuf::addStr(), g_doxy_nbsp, g_utf8_nbsp, len, m_out, s, Portable::strnstr(), substitute(), and TRACE.
Referenced by processSpecialCommand(), and writeFencedCodeBlock().
addStrEscapeUtf8Nbsp() [2/2]
void Markdown::addStrEscapeUtf8Nbsp (const char * s, int len) [private]
detab() [1/2]
QCString Markdown::detab (const QCString & s, int & refIndent) [private]
Definition at line 3340 of file markdown.cpp.
{
  TRACE(s);
  int tabSize = Config_getInt(TAB_SIZE);
  int size = s.length();
  m_out.clear();
  m_out.reserve(size);
  const char *data = s.data();
  int i=0;
  int col=0;
  const int maxIndent=1000000; // value representing infinity
  int minIndent=maxIndent;
  while (i<size)
  {
    char c = data[i++];
    switch(c)
    {
      case '\t': // expand tab
        {
          int stop = tabSize - (col%tabSize);
          //printf("expand at %d stop=%d\n",col,stop);
          col+=stop;
          while (stop--) m_out.addChar(' ');
        }
        break;
      case '\n': // reset column counter
        m_out.addChar(c);
        col=0;
        break;
      case ' ': // increment column counter
        m_out.addChar(c);
        col++;
        break;
      default: // non-whitespace => update minIndent
        if (c<0 && i<size) // multibyte sequence
        {
          // special handling of the UTF-8 nbsp character 0xC2 0xA0
          int nb = isUTF8NonBreakableSpace(data);
          if (nb>0)
          {
            m_out.addStr(g_doxy_nbsp);
            i+=nb-1;
          }
          else
          {
            int bytes = getUTF8CharNumBytes(c);
            for (int j=0;j<bytes-1 && c;j++)
            {
              m_out.addChar(c);
              c = data[i++];
            }
            m_out.addChar(c);
          }
        }
        else
        {
          m_out.addChar(c);
        }
        if (col<minIndent) minIndent=col;
        col++;
    }
  }
  if (minIndent!=maxIndent) refIndent=minIndent; else refIndent=0;
  m_out.addChar(0);
  //printf("detab refIndent=%d\n",refIndent);
  return m_out.get();
}
References GrowBuf::addChar(), GrowBuf::addStr(), c, GrowBuf::clear(), Config_getInt, gdFont::data, data, g_doxy_nbsp, GrowBuf::get(), getUTF8CharNumBytes(), isUTF8NonBreakableSpace(), m_out, GrowBuf::reserve(), s, size, and TRACE.
Referenced by process().
detab() [2/2]
QCString Markdown::detab (const QCString & s, int & refIndent) [private]
extractPageTitle() [1/2]
QCString Markdown::extractPageTitle (QCString & docs, QCString & id, int & prepend)
Definition at line 3289 of file markdown.cpp.
{
  TRACE(docs);
  // first first non-empty line
  prepend = 0;
  QCString title;
  int i=0;
  int size=docs.size();
  QCString docs_org(docs);
  const char *data = docs_org.data();
  docs = "";
  while (i<size && (data[i]==' ' || data[i]=='\n'))
  {
    if (data[i]=='\n') prepend++;
    i++;
  }
  if (i>=size) { TRACE_RESULT(""); return ""; }
  int end1=i+1;
  while (end1<size && data[end1-1]!='\n') end1++;
  //printf("i=%d end1=%d size=%d line='%s'\n",i,end1,size,docs.mid(i,end1-i).data());
  // first line from i..end1
  if (end1<size)
  {
    // second line form end1..end2
    int end2=end1+1;
    while (end2<size && data[end2-1]!='\n') end2++;
    if (isHeaderline(data+end1,size-end1,FALSE))
    {
      convertStringFragment(title,data+i,end1-i-1);
      docs+="\n\n"+docs_org.mid(end2);
      id = extractTitleId(title, 0);
      //printf("extractPageTitle(title='%s' docs='%s' id='%s')\n",title.data(),docs.data(),id.data());
      TRACE_RESULT(title);
      return title;
    }
  }
  if (i<end1 && isAtxHeader(data+i,end1-i,title,id,FALSE)>0)
  {
    docs+="\n";
    docs+=docs_org.mid(end1);
  }
  else
  {
    docs=docs_org;
    id = extractTitleId(title, 0);
  }
  //printf("extractPageTitle(title='%s' docs='%s' id='%s')\n",qPrint(title),qPrint(docs),qPrint(id));
  TRACE_RESULT(title);
  return title;
}
References convertStringFragment(), data, QCString::data(), extractTitleId(), FALSE, isAtxHeader(), isHeaderline(), QCString::mid(), size, QCString::size(), TRACE, and TRACE_RESULT.
Referenced by MarkdownOutlineParser::parseInput().
extractPageTitle() [2/2]
QCString Markdown::extractPageTitle (QCString & docs, QCString & id, int & prepend)
findEmphasisChar() [1/2]
int Markdown::findEmphasisChar (const char * data, int size, char c, int c_size) [private]
looks for the next emph char, skipping other constructs, and stopping when either it is found, or we are at the end of a paragraph.
Definition at line 679 of file markdown.cpp.
{
  TRACE(data);
  int i = 1;
  while (i<size)
  {
    while (i<size && data[i]!=c && data[i]!='`' &&
                     data[i]!='\\' && data[i]!='@' &&
                     !(data[i]=='/' && data[i-1]=='<') && // html end tag also ends emphasis
                     data[i]!='\n') i++;
    //printf("findEmphasisChar: data=[%s] i=%d c=%c\n",data,i,data[i]);
    // not counting escaped chars or characters that are unlikely
    // to appear as the end of the emphasis char
    if (ignoreCloseEmphChar(i-1))
    {
      i++;
      continue;
    }
    else
    {
      // get length of emphasis token
      int len = 0;
      while (i+len<size && data[i+len]==c)
      {
        len++;
      }
      if (len>0)
      {
        if (len!=c_size || (i<size-len && isIdChar(i+len))) // to prevent touching some_underscore_identifier
        {
          i=i+len;
          continue;
        }
        TRACE_RESULT(i);
        return i; // found it
      }
    }
    // skipping a code span
    if (data[i]=='`')
    {
      int snb=0;
      while (i<size && data[i]=='`') snb++,i++;
      // find same pattern to end the span
      int enb=0;
      while (i<size && enb<snb)
      {
        if (data[i]=='`') enb++;
        if (snb==1 && data[i]=='\'') break; // ` ended by '
        i++;
      }
    }
    else if (data[i]=='@' || data[i]=='\\')
    { // skip over blocks that should not be processed
      QCString endBlockName = isBlockCommand(data+i,i,size-i);
      if (!endBlockName.isEmpty())
      {
        i++;
        int l = endBlockName.length();
        while (i<size-l)
        {
          if ((data[i]=='\\' || data[i]=='@') && // command
              data[i-1]!='\\' && data[i-1]!='@') // not escaped
          {
            if (qstrncmp(&data[i+1],endBlockName.data(),l)==0)
            {
              break;
            }
          }
          i++;
        }
      }
      else if (i<size-1 && isIdChar(i+1)) // @cmd, stop processing, see bug 690385
      {
        TRACE_RESULT(0);
        return 0;
      }
      else
      {
        i++;
      }
    }
    else if (data[i-1]=='<' && data[i]=='/') // html end tag invalidates emphasis
    {
      TRACE_RESULT(0);
      return 0;
    }
    else if (data[i]=='\n') // end * or _ at paragraph boundary
    {
      i++;
      while (i<size && data[i]==' ') i++;
      if (i>=size || data[i]=='\n') { TRACE_RESULT(0); return 0; } // empty line -> paragraph
    }
    else // should not get here!
    {
      i++;
    }
  }
  TRACE_RESULT(0);
  return 0;
}
References c, data, QCString::data(), ignoreCloseEmphChar, isBlockCommand(), QCString::isEmpty(), isIdChar, len, QCString::length(), qstrncmp(), size, TRACE, and TRACE_RESULT.
Referenced by processEmphasis1(), processEmphasis2(), and processEmphasis3().
findEmphasisChar() [2/2]
int Markdown::findEmphasisChar (const char * data, int size, char c, int c_size) [private]
findEndOfLine() [1/2]
void Markdown::findEndOfLine (const char * data, int size, int & pi, int & i, int & end) [private]
Definition at line 2822 of file markdown.cpp.
{
  TRACE(data);
  // find end of the line
  int nb=0;
  end=i+1;
  //while (end<=size && data[end-1]!='\n')
  int j=0;
  while (end<=size && (j=isNewline(data+end-1))==0)
  {
    // while looking for the end of the line we might encounter a block
    // that needs to be passed unprocessed.
    if ((data[end-1]=='\\' || data[end-1]=='@') && // command
        (end<=1 || (data[end-2]!='\\' && data[end-2]!='@')) // not escaped
       )
    {
      QCString endBlockName = isBlockCommand(data+end-1,end-1,size-(end-1));
      end++;
      if (!endBlockName.isEmpty())
      {
        int l = endBlockName.length();
        for (;end<size-l-1;end++) // search for end of block marker
        {
          if ((data[end]=='\\' || data[end]=='@') &&
              data[end-1]!='\\' && data[end-1]!='@'
             )
          {
            if (qstrncmp(&data[end+1],endBlockName.data(),l)==0)
            {
              // found end marker, skip over this block
              //printf("feol.block m_out={%s}\n",qPrint(QCString(data+i).left(end+l+1-i)));
              end = end + l + 2;
              break;
            }
          }
        }
      }
    }
    else if (nb==0 && data[end-1]=='<' && end<size-6 &&
             (end<=1 || (data[end-2]!='\\' && data[end-2]!='@'))
            )
    {
      if (tolower(data[end])=='p' && tolower(data[end+1])=='r' &&
          tolower(data[end+2])=='e' && (data[end+3]=='>' || data[end+3]==' ')) // <pre> tag
      {
        // skip part until including </pre>
        end = end + processHtmlTagWrite(data+end-1,end-1,size-end+1,false) + 2;
        break;
      }
      else
      {
        end++;
      }
    }
    else if (nb==0 && data[end-1]=='`')
    {
      while (end<=size && data[end-1]=='`') end++,nb++;
    }
    else if (nb>0 && data[end-1]=='`')
    {
      int enb=0;
      while (end<=size && data[end-1]=='`') end++,enb++;
      if (enb==nb) nb=0;
    }
    else
    {
      end++;
    }
  }
  if (j>0) end+=j-1;
  //printf("findEndOfLine pi=%d i=%d end=%d {%s}\n",pi,i,end,qPrint(QCString(data+i).left(end-i)));
}
References data, QCString::data(), ghc::filesystem::end(), isBlockCommand(), QCString::isEmpty(), isNewline(), QCString::length(), processHtmlTagWrite(), qstrncmp(), size, caseconvert::tolower, and TRACE.
Referenced by processBlocks(), and processQuotations().
findEndOfLine() [2/2]
void Markdown::findEndOfLine (const char * data, int size, int & pi, int & i, int & end) [private]
isAtxHeader() [1/2]
int Markdown::isAtxHeader (const char * data, int size, QCString & header, QCString & id, bool allowAdjustLevel) [private]
Definition at line 2002 of file markdown.cpp.
{
  TRACE(data);
  int i = 0, end;
  int level = 0, blanks=0;
  // find start of header text and determine heading level
  while (i<size && data[i]==' ') i++;
  if (i>=size || data[i]!='#')
  {
    TRACE_RESULT(0);
    return 0;
  }
  while (i<size && level<6 && data[i]=='#') i++,level++;
  while (i<size && data[i]==' ') i++,blanks++;
  if (level==1 && blanks==0)
  {
    TRACE_RESULT(0);
    return 0; // special case to prevent #someid seen as a header (see bug 671395)
  }
  // find end of header text
  end=i;
  while (end<size && data[end]!='\n') end++;
  while (end>i && (data[end-1]=='#' || data[end-1]==' ')) end--;
  // store result
  convertStringFragment(header,data+i,end-i);
  id = extractTitleId(header, level);
  if (!id.isEmpty()) // strip #'s between title and id
  {
    i=header.length()-1;
    while (i>=0 && (header.at(i)=='#' || header.at(i)==' ')) i--;
    header=header.left(i+1);
  }
  if (allowAdjustLevel && level==1 && m_indentLevel==-1)
  {
    // in case we find a `# Section` on a markdown page that started with the same level
    // header, we no longer need to artificially decrease the paragraph level.
    // So both
    // -------------------
    // # heading 1 <-- here we set g_indentLevel to -1
    // # heading 2 <-- here we set g_indentLevel back to 0 such that this will be a @section
    // -------------------
    // and
    // -------------------
    // # heading 1 <-- here we set g_indentLevel to -1
    // ## heading 2 <-- here we keep g_indentLevel at -1 such that @subsection will be @section
    // -------------------
    // will convert to
    // -------------------
    // @page md_page Heading 1
    // @section autotoc_md1 Heading 2
    // -------------------
    m_indentLevel=0;
  }
  int res = level+m_indentLevel;
  TRACE_RESULT(res);
  return res;
}
References QCString::at(), convertStringFragment(), data, ghc::filesystem::end(), extractTitleId(), QCString::left(), QCString::length(), level, m_indentLevel, size, TRACE, and TRACE_RESULT.
Referenced by extractPageTitle(), and writeOneLineHeaderOrRuler().
isAtxHeader() [2/2]
int Markdown::isAtxHeader (const char * data, int size, QCString & header, QCString & id, bool allowAdjustLevel) [private]
isBlockCommand() [1/2]
QCString Markdown::isBlockCommand (const char * data, int offset, int size) [private]
Definition at line 404 of file markdown.cpp.
{
  TRACE(data);
  using EndBlockFunc = QCString (*)(const std::string &,bool,char);
  static const auto getEndBlock = [](const std::string &blockName,bool,char) -> QCString
  {
    return "end"+blockName;
  };
  static const auto getEndCode = [](const std::string &blockName,bool openBracket,char) -> QCString
  {
    return openBracket ? QCString("}") : "end"+blockName;
  };
  static const auto getEndUml = [](const std::string &blockName,bool,char) -> QCString
  {
    return "enduml";
  };
  static const auto getEndFormula = [](const std::string &blockName,bool,char nextChar) -> QCString
  {
    switch (nextChar)
    {
      case '$': return "f$";
      case '(': return "f)";
      case '[': return "f]";
      case '{': return "f}";
    }
    return "";
  };
  // table mapping a block start command to a function that can return the matching end block string
  static const std::unordered_map<std::string,EndBlockFunc> blockNames =
  {
    { "dot", getEndBlock },
    { "code", getEndCode },
    { "icode", getEndBlock },
    { "msc", getEndBlock },
    { "verbatim", getEndBlock },
    { "iverbatim", getEndBlock },
    { "iliteral", getEndBlock },
    { "latexonly", getEndBlock },
    { "htmlonly", getEndBlock },
    { "xmlonly", getEndBlock },
    { "rtfonly", getEndBlock },
    { "manonly", getEndBlock },
    { "docbookonly", getEndBlock },
    { "startuml", getEndUml },
    { "f", getEndFormula }
  };
  bool openBracket = offset>0 && data[-1]=='{';
  bool isEscaped = offset>0 && (data[-1]=='\\' || data[-1]=='@');
  if (isEscaped) return QCString();
  int end=1;
  while (end<size && (data[end]>='a' && data[end]<='z')) end++;
  if (end==1) return QCString();
  std::string blockName(data+1,end-1);
  auto it = blockNames.find(blockName);
  QCString result;
  if (it!=blockNames.end()) // there is a function assigned
  {
    result = it->second(blockName, openBracket, end<size ? data[end] : 0);
  }
  TRACE_RESULT(result);
  return result;
}
References data, ghc::filesystem::end(), offset, size, string, TRACE, and TRACE_RESULT.
Referenced by findEmphasisChar(), findEndOfLine(), processBlocks(), and processSpecialCommand().
isBlockCommand() [2/2]
QCString Markdown::isBlockCommand (const char * data, int offset, int size) [private]
isHeaderline() [1/2]
int Markdown::isHeaderline (const char * data, int size, bool allowAdjustLevel) [private]
returns whether the line is a setext-style hdr underline
Definition at line 1785 of file markdown.cpp.
{
  TRACE(data);
  int i=0, c=0;
  while (i<size && data[i]==' ') i++;
  // test of level 1 header
  if (data[i]=='=')
  {
    while (i<size && data[i]=='=') i++,c++;
    while (i<size && data[i]==' ') i++;
    int level = (c>1 && (i>=size || data[i]=='\n')) ? 1 : 0;
    if (allowAdjustLevel && level==1 && m_indentLevel==-1)
    {
      // In case a page starts with a header line we use it as title, promoting it to @page.
      // We set g_indentLevel to -1 to promoting the other sections if they have a deeper
      // nesting level than the page header, i.e. @section..@subsection becomes @page..@section.
      // In case a section at the same level is found (@section..@section) however we need
      // to undo this (and the result will be @page..@section).
      m_indentLevel=0;
    }
    TRACE_RESULT(m_indentLevel+level);
    return m_indentLevel+level;
  }
  // test of level 2 header
  if (data[i]=='-')
  {
    while (i<size && data[i]=='-') i++,c++;
    while (i<size && data[i]==' ') i++;
    return (c>1 && (i>=size || data[i]=='\n')) ? m_indentLevel+2 : 0;
  }
  TRACE_RESULT(0);
  return 0;
}
References c, data, level, m_indentLevel, size, TRACE, and TRACE_RESULT.
Referenced by extractPageTitle(), and processBlocks().
isHeaderline() [2/2]
int Markdown::isHeaderline (const char * data, int size, bool allowAdjustLevel) [private]
isSpecialCommand() [1/2]
int Markdown::isSpecialCommand (const char * data, int offset, int size) [private]
Definition at line 472 of file markdown.cpp.
{
  TRACE(data);
  using EndCmdFunc = int (*)(const char *,int,int);
  static const auto endOfLine = [](const char *data_,int offset_,int size_) -> int
  {
    // skip until the end of line (allowing line continuation characters)
    char lc = 0;
    char c;
    while (offset_<size_ && ((c=data_[offset_])!='\n' || lc=='\\'))
    {
      if (c=='\\') lc='\\'; // last character was a line continuation
      else if (c!=' ') lc=0; // rest line continuation
      offset_++;
    }
    return offset_;
  };
  static const auto endOfLabel = [](const char *data_,int offset_,int size_) -> int
  {
    if (offset_<size_ && data_[offset_]==' ') // we expect a space before the label
    {
      char c;
      offset_++;
      // skip over spaces
      while (offset_<size_ && data_[offset_]==' ') offset_++;
      // skip over label
      while (offset_<size_ && (c=data_[offset_])!=' ' && c!='\\' && c!='@' && c!='\n') offset_++;
      return offset_;
    }
    return 0;
  };
  static const auto endOfParam = [](const char *data_,int offset_,int size_) -> int
  {
    int index=offset_;
    if (index<size_ && data_[index]==' ') // skip over optional spaces
    {
      index++;
      while (index<size_ && data_[index]==' ') index++;
    }
    if (index<size_ && data_[index]=='[') // find matching ']'
    {
      index++;
      char c;
      while (index<size_ && (c=data_[index])!=']' && c!='\n') index++;
      if (index==size_ || data_[index]!=']') return 0; // invalid parameter
      offset_=index+1; // part after [...] is the parameter name
    }
    return endOfLabel(data_,offset_,size_);
  };
  static const auto endOfFuncLike = [](const char *data_,int offset_,int size_,bool allowSpaces) -> int
  {
    if (offset_<size_ && data_[offset_]==' ') // we expect a space before the name
    {
      char c=0;
      offset_++;
      // skip over spaces
      while (offset_<size_ && data_[offset_]==' ')
      {
        offset_++;
      }
      // skip over name (and optionally type)
      while (offset_<size_ && (c=data_[offset_])!='\n' && (allowSpaces || c!=' ') && c!='(')
      {
        offset_++;
      }
      if (c=='(') // find the end of the function
      {
        int count=1;
        offset_++;
        while (offset_<size_ && (c=data_[offset_++]))
        {
          if (c=='(') count++;
          else if (c==')') count--;
          if (count==0) return offset_;
        }
      }
      return offset_;
    }
    return 0;
  };
  static const auto endOfFunc = [](const char *data_,int offset_,int size_) -> int
  {
    return endOfFuncLike(data_,offset_,size_,true);
  };
  static const auto endOfGuard = [](const char *data_,int offset_,int size_) -> int
  {
    return endOfFuncLike(data_,offset_,size_,false);
  };
  static const std::unordered_map<std::string,EndCmdFunc> cmdNames =
  {
    { "a", endOfLabel },
    { "addindex", endOfLine },
    { "addtogroup", endOfLabel },
    { "anchor", endOfLabel },
    { "b", endOfLabel },
    { "c", endOfLabel },
    { "category", endOfLine },
    { "cite", endOfLabel },
    { "class", endOfLine },
    { "concept", endOfLine },
    { "copybrief", endOfFunc },
    { "copydetails", endOfFunc },
    { "copydoc", endOfFunc },
    { "def", endOfFunc },
    { "defgroup", endOfLabel },
    { "diafile", endOfLine },
    { "dir", endOfLine },
    { "dockbookinclude",endOfLine },
    { "dontinclude", endOfLine },
    { "dotfile", endOfLine },
    { "dotfile", endOfLine },
    { "e", endOfLabel },
    { "elseif", endOfGuard },
    { "em", endOfLabel },
    { "emoji", endOfLabel },
    { "enum", endOfLabel },
    { "example", endOfLine },
    { "exception", endOfLine },
    { "extends", endOfLabel },
    { "file", endOfLine },
    { "fn", endOfFunc },
    { "headerfile", endOfLine },
    { "htmlinclude", endOfLine },
    { "idlexcept", endOfLine },
    { "if", endOfGuard },
    { "ifnot", endOfGuard },
    { "image", endOfLine },
    { "implements", endOfLine },
    { "include", endOfLine },
    { "includedoc", endOfLine },
    { "includelineno", endOfLine },
    { "ingroup", endOfLabel },
    { "interface", endOfLine },
    { "interface", endOfLine },
    { "latexinclude", endOfLine },
    { "maninclude", endOfLine },
    { "memberof", endOfLabel },
    { "mscfile", endOfLine },
    { "namespace", endOfLabel },
    { "noop", endOfLine },
    { "overload", endOfLine },
    { "p", endOfLabel },
    { "package", endOfLabel },
    { "page", endOfLabel },
    { "paragraph", endOfLabel },
    { "param", endOfParam },
    { "property", endOfLine },
    { "protocol", endOfLine },
    { "ref", endOfLabel },
    { "refitem", endOfLine },
    { "related", endOfLabel },
    { "relatedalso", endOfLabel },
    { "relates", endOfLabel },
    { "relatesalso", endOfLabel },
    { "retval", endOfLabel },
    { "rtfinclude", endOfLine },
    { "section", endOfLabel },
    { "skip", endOfLine },
    { "skipline", endOfLine },
    { "snippet", endOfLine },
    { "snippetdoc", endOfLine },
    { "snippetlineno", endOfLine },
    { "struct", endOfLine },
    { "subpage", endOfLabel },
    { "subsection", endOfLabel },
    { "subsubsection", endOfLabel },
    { "throw", endOfLabel },
    { "throws", endOfLabel },
    { "tparam", endOfLabel },
    { "typedef", endOfLine },
    { "union", endOfLine },
    { "until", endOfLine },
    { "var", endOfLine },
    { "verbinclude", endOfLine },
    { "weakgroup", endOfLabel },
    { "xmlinclude", endOfLine },
    { "xrefitem", endOfLabel }
  };
  bool isEscaped = offset>0 && (data[-1]=='\\' || data[-1]=='@');
  if (isEscaped) return 0;
  int end=1;
  while (end<size && (data[end]>='a' && data[end]<='z')) end++;
  if (end==1) return 0;
  std::string cmdName(data+1,end-1);
  int result=0;
  auto it = cmdNames.find(cmdName);
  if (it!=cmdNames.end()) // command with parameters that should be ignored by markdown
  {
    // find the end of the parameters
    result = it->second(data,end,size);
  }
  return result;
}
References c, data, ghc::filesystem::end(), offset, size, string, and TRACE.
Referenced by processSpecialCommand().
isSpecialCommand() [2/2]
int Markdown::isSpecialCommand (const char * data, int offset, int size) [private]
process() [1/2]
QCString Markdown::process (const QCString & input, int & startNewlines, bool fromParseInput = false)
Definition at line 3410 of file markdown.cpp.
{
  if (input.isEmpty()) return input;
  int refIndent;
  // for replace tabs by spaces
  QCString s = input;
  if (s.at(s.length()-1)!='\n') s += "\n"; // see PR #6766
  s = detab(s,refIndent);
  //printf("======== DeTab =========\n---- output -----\n%s\n---------\n",qPrint(s));
  // then process quotation blocks (as these may contain other blocks)
  s = processQuotations(s,refIndent);
  //printf("======== Quotations =========\n---- output -----\n%s\n---------\n",qPrint(s));
  // then process block items (headers, rules, and code blocks, references)
  s = processBlocks(s,refIndent);
  //printf("======== Blocks =========\n---- output -----\n%s\n---------\n",qPrint(s));
  // finally process the inline markup (links, emphasis and code spans)
  m_out.clear();
  processInline(s.data(),s.length());
  m_out.addChar(0);
  if (fromParseInput)
  {
    Debug::print(Debug::Markdown,0,"---- output -----\n%s\n=========\n",qPrint(m_out.get()));
  }
  else
  {
    Debug::print(Debug::Markdown,0,"======== Markdown =========\n---- input ------- \n%s\n---- output -----\n%s\n=========\n",qPrint(input),qPrint(m_out.get()));
  }
  // post processing
  QCString result = substitute(m_out.get(),g_doxy_nbsp,"&nbsp;");
  const char *p = result.data();
  if (p)
  {
    while (*p==' ') p++; // skip over spaces
    while (*p=='\n') {startNewlines++;p++;}; // skip over newlines
    if (qstrncmp(p,"<br>",4)==0) p+=4; // skip over <br>
  }
  if (p>result.data())
  {
    // strip part of the input
    result = result.mid(static_cast<int>(p-result.data()));
  }
  return result;
}
References GrowBuf::addChar(), GrowBuf::clear(), gdFont::data, QCString::data(), detab(), g_doxy_nbsp, GrowBuf::get(), QCString::isEmpty(), m_out, Debug::Markdown, QCString::mid(), p, Debug::print(), processBlocks(), processInline(), processQuotations(), qPrint(), qstrncmp(), s, and substitute().
Referenced by VHDLOutlineParser::handleCommentBlock(), handleCommentBlock(), DocPara::handleInclude(), handleParametersCommentBlocks(), and MarkdownOutlineParser::parseInput().
process() [2/2]
QCString Markdown::process (const QCString & input, int & startNewlines, bool fromParseInput = false)
processBlocks() [1/2]
QCString Markdown::processBlocks (const QCString & s, int indent) [private]
Definition at line 3049 of file markdown.cpp.
{
  TRACE(s);
  m_out.clear();
  const char *data = s.data();
  int size = s.length();
  int i=0,end=0,pi=-1,ref,level;
  QCString id,link,title;
#if 0 // commented m_out, since starting with a comment block is probably a usage error
      // see also http://stackoverflow.com/q/20478611/784672
  // special case when the documentation starts with a code block
  // since the first line is skipped when looking for a code block later on.
  if (end>codeBlockIndent && isCodeBlock(data,0,end,blockIndent))
  {
    i=writeCodeBlock(m_out,data,size,blockIndent);
    end=i+1;
    pi=-1;
  }
#endif
  int currentIndent = indent;
  int listIndent = indent;
  bool insideList = false;
  bool newBlock = false;
  // process each line
  while (i<size)
  {
    findEndOfLine(data,size,pi,i,end);
    // line is now found at [i..end)
    int lineIndent=0;
    while (lineIndent<end && data[i+lineIndent]==' ') lineIndent++;
    //printf("** lineIndent=%d line=(%s)\n",lineIndent,qPrint(QCString(data+i).left(end-i)));
    if (newBlock)
    {
      //printf("** end of block\n");
      if (insideList && lineIndent<currentIndent) // end of list
      {
        //printf("** end of list\n");
        currentIndent = indent;
        insideList = false;
      }
      newBlock = false;
    }
    if ((listIndent=isListMarker(data+i,end-i))) // see if we need to increase the indent level
    {
      if (listIndent<currentIndent+4)
      {
        //printf("** start of list\n");
        insideList = true;
        currentIndent = listIndent;
      }
    }
    else if (isEndOfList(data+i,end-i))
    {
      //printf("** end of list\n");
      insideList = false;
      currentIndent = listIndent;
    }
    else if (isEmptyLine(data+i,end-i))
    {
      //printf("** new block\n");
      newBlock = true;
    }
    //printf("indent=%d listIndent=%d blockIndent=%d\n",indent,listIndent,blockIndent);
    //printf("findEndOfLine: pi=%d i=%d end=%d\n",pi,i,end);
    if (pi!=-1)
    {
      int blockStart,blockEnd,blockOffset;
      QCString lang;
      int blockIndent = currentIndent;
      //printf("isHeaderLine(%s)=%d\n",QCString(data+i).left(size-i).data(),level);
      QCString endBlockName;
      if (data[i]=='@' || data[i]=='\\') endBlockName = isBlockCommand(data+i,i,size-i);
      if (!endBlockName.isEmpty())
      {
        // handle previous line
        if (isLinkRef(data+pi,i-pi,id,link,title))
        {
          m_linkRefs.insert({id.lower().str(),LinkRef(link,title)});
        }
        else
        {
          writeOneLineHeaderOrRuler(data+pi,i-pi);
        }
        m_out.addChar(data[i]);
        i++;
        int l = endBlockName.length();
        while (i<size-l)
        {
          if ((data[i]=='\\' || data[i]=='@') && // command
              data[i-1]!='\\' && data[i-1]!='@') // not escaped
          {
            if (qstrncmp(&data[i+1],endBlockName.data(),l)==0)
            {
              m_out.addChar(data[i]);
              m_out.addStr(endBlockName);
              i+=l+1;
              break;
            }
          }
          m_out.addChar(data[i]);
          i++;
        }
      }
      else if ((level=isHeaderline(data+i,size-i,TRUE))>0)
      {
        //printf("Found header at %d-%d\n",i,end);
        while (pi<size && data[pi]==' ') pi++;
        QCString header;
        convertStringFragment(header,data+pi,i-pi-1);
        id = extractTitleId(header, level);
        //printf("header='%s' is='%s'\n",qPrint(header),qPrint(id));
        if (!header.isEmpty())
        {
          if (!id.isEmpty())
          {
            m_out.addStr(level==1?"@section ":"@subsection ");
            m_out.addStr(id);
            m_out.addStr(" ");
            m_out.addStr(header);
            m_out.addStr("\n\n");
          }
          else
          {
            m_out.addStr(level==1?"<h1>":"<h2>");
            m_out.addStr(header);
            m_out.addStr(level==1?"\n</h1>\n":"\n</h2>\n");
          }
        }
        else
        {
          m_out.addStr("\n<hr>\n");
        }
        pi=-1;
        i=end;
        end=i+1;
        continue;
      }
      else if ((ref=isLinkRef(data+pi,size-pi,id,link,title)))
      {
        //printf("found link ref: id='%s' link='%s' title='%s'\n",
        // qPrint(id),qPrint(link),qPrint(title));
        m_linkRefs.insert({id.lower().str(),LinkRef(link,title)});
        i=ref+pi;
        end=i+1;
      }
      else if (isFencedCodeBlock(data+pi,size-pi,currentIndent,lang,blockStart,blockEnd,blockOffset))
      {
        //printf("Found FencedCodeBlock lang='%s' start=%d end=%d code={%s}\n",
        // qPrint(lang),blockStart,blockEnd,QCString(data+pi+blockStart).left(blockEnd-blockStart).data());
        writeFencedCodeBlock(data+pi,lang.data(),blockStart,blockEnd);
        i=pi+blockOffset;
        pi=-1;
        end=i+1;
        continue;
      }
      else if (isCodeBlock(data+i,i,end-i,blockIndent))
      {
        // skip previous line (it is empty anyway)
        i+=writeCodeBlock(data+i,size-i,blockIndent);
        pi=-1;
        end=i+1;
        continue;
      }
      else if (isTableBlock(data+pi,size-pi))
      {
        i=pi+writeTableBlock(data+pi,size-pi);
        pi=-1;
        end=i+1;
        continue;
      }
      else
      {
        writeOneLineHeaderOrRuler(data+pi,i-pi);
      }
    }
    pi=i;
    i=end;
  }
  //printf("last line %d size=%d\n",i,size);
  if (pi!=-1 && pi<size) // deal with the last line
  {
    if (isLinkRef(data+pi,size-pi,id,link,title))
    {
      //printf("found link ref: id='%s' link='%s' title='%s'\n",
      // qPrint(id),qPrint(link),qPrint(title));
      m_linkRefs.insert({id.lower().str(),LinkRef(link,title)});
    }
    else
    {
      writeOneLineHeaderOrRuler(data+pi,size-pi);
    }
  }
  m_out.addChar(0);
  return m_out.get();
}
References GrowBuf::addChar(), GrowBuf::addStr(), GrowBuf::clear(), codeBlockIndent, convertStringFragment(), gdFont::data, data, QCString::data(), ghc::filesystem::end(), extractTitleId(), findEndOfLine(), GrowBuf::get(), id, isBlockCommand(), isCodeBlock(), QCString::isEmpty(), isEmptyLine(), isEndOfList(), isFencedCodeBlock(), isHeaderline(), isLinkRef(), isListMarker(), isTableBlock(), QCString::length(), level, m_linkRefs, m_out, qstrncmp(), s, size, TRACE, TRUE, writeCodeBlock(), writeFencedCodeBlock(), writeOneLineHeaderOrRuler(), and writeTableBlock().
Referenced by process().
processBlocks() [2/2]
QCString Markdown::processBlocks (const QCString & s, int indent) [private]
processCodeSpan() [1/2]
int Markdown::processCodeSpan (const char * data, int , int size) [private]
'`' parsing a code span (assuming codespan != 0)
Definition at line 1609 of file markdown.cpp.
{
  TRACE(data);
  int end, nb = 0, i, f_begin, f_end;
  /* counting the number of backticks in the delimiter */
  while (nb<size && data[nb]=='`')
  {
    nb++;
  }
  /* finding the next delimiter */
  i = 0;
  int nl=0;
  for (end=nb; end<size && i<nb && nl<2; end++)
  {
    if (data[end]=='`')
    {
      i++;
    }
    else if (data[end]=='\n')
    {
      i=0;
      nl++;
    }
    else if (data[end]=='\'' && nb==1 && (end==size-1 || (end<size-1 && !isIdChar(end+1))))
    { // look for quoted strings like 'some word', but skip strings like `it's cool`
      QCString textFragment;
      convertStringFragment(textFragment,data+nb,end-nb);
      m_out.addStr("&lsquo;");
      m_out.addStr(textFragment);
      m_out.addStr("&rsquo;");
      return end+1;
    }
    else
    {
      i=0;
    }
  }
  if (i < nb && end >= size)
  {
    TRACE_RESULT(0);
    return 0; // no matching delimiter
  }
  if (nl==2) // too many newlines inside the span
  {
    TRACE_RESULT(0);
    return 0;
  }
  // trimming outside whitespaces
  f_begin = nb;
  while (f_begin < end && data[f_begin]==' ')
  {
    f_begin++;
  }
  f_end = end - nb;
  while (f_end > nb && data[f_end-1]==' ')
  {
    f_end--;
  }
  //printf("found code span '%s'\n",qPrint(QCString(data+f_begin).left(f_end-f_begin)));
  /* real code span */
  if (f_begin < f_end)
  {
    QCString codeFragment;
    convertStringFragment(codeFragment,data+f_begin,f_end-f_begin);
    m_out.addStr("<tt>");
    //m_out.addStr(convertToHtml(codeFragment,TRUE));
    m_out.addStr(escapeSpecialChars(codeFragment));
    m_out.addStr("</tt>");
  }
  TRACE_RESULT(end);
  return end;
}
References GrowBuf::addStr(), convertStringFragment(), data, ghc::filesystem::end(), escapeSpecialChars(), isIdChar, m_out, size, TRACE, and TRACE_RESULT.
Referenced by Markdown().
processCodeSpan() [2/2]
int Markdown::processCodeSpan (const char * data, int , int size) [private]
processEmphasis() [1/2]
int Markdown::processEmphasis (const char * data, int offset, int size) [private]
Definition at line 1081 of file markdown.cpp.
{
  TRACE(data);
  if ((offset>0 && !isOpenEmphChar(-1)) || // invalid char before * or _
      (size>1 && data[0]!=data[1] && !(isIdChar(1) || extraChar(1) || data[1]=='[')) || // invalid char after * or _
      (size>2 && data[0]==data[1] && !(isIdChar(2) || extraChar(2) || data[2]=='['))) // invalid char after ** or __
  {
    TRACE_RESULT(0);
    return 0;
  }
  char c = data[0];
  int ret;
  if (size>2 && c!='~' && data[1]!=c) // _bla or *bla
  {
    // whitespace cannot follow an opening emphasis
    if (data[1]==' ' || data[1]=='\n' ||
        (ret = processEmphasis1(data+1, size-1, c)) == 0)
    {
      TRACE_RESULT(0);
      return 0;
    }
    return ret+1;
  }
  if (size>3 && data[1]==c && data[2]!=c) // __bla or **bla
  {
    if (data[2]==' ' || data[2]=='\n' ||
        (ret = processEmphasis2(data+2, size-2, c)) == 0)
    {
      TRACE_RESULT(0);
      return 0;
    }
    return ret+2;
  }
  if (size>4 && c!='~' && data[1]==c && data[2]==c && data[3]!=c) // ___bla or ***bla
  {
    if (data[3]==' ' || data[3]=='\n' ||
        (ret = processEmphasis3(data+3, size-3, c)) == 0)
    {
      TRACE_RESULT(0);
      return 0;
    }
    TRACE_RESULT(ret+3);
    return ret+3;
  }
  TRACE_RESULT(0);
  return 0;
}
References c, data, extraChar, isIdChar, isOpenEmphChar, offset, processEmphasis1(), processEmphasis2(), processEmphasis3(), size, TRACE, and TRACE_RESULT.
Referenced by Markdown().
processEmphasis() [2/2]
int Markdown::processEmphasis (const char * data, int offset, int size) [private]
processEmphasis1() [1/2]
int Markdown::processEmphasis1 (const char * data, int size, char c) [private]
process single emphasis
Definition at line 787 of file markdown.cpp.
{
  TRACE(data);
  int i = 0, len;
  /* skipping one symbol if coming from emph3 */
  if (size>1 && data[0]==c && data[1]==c) { i=1; }
  while (i<size)
  {
    len = findEmphasisChar(data+i, size-i, c, 1);
    if (len==0) { TRACE_RESULT(0); return 0; }
    i+=len;
    if (i>=size) { TRACE_RESULT(0); return 0; }
    if (i+1<size && data[i+1]==c)
    {
      i++;
      continue;
    }
    if (data[i]==c && data[i-1]!=' ' && data[i-1]!='\n')
    {
      m_out.addStr("<em>");
      processInline(data,i);
      m_out.addStr("</em>");
      TRACE_RESULT(i+1);
      return i+1;
    }
  }
  TRACE_RESULT(0);
  return 0;
}
References GrowBuf::addStr(), c, data, findEmphasisChar(), len, m_out, processInline(), size, TRACE, and TRACE_RESULT.
Referenced by processEmphasis(), and processEmphasis3().
processEmphasis1() [2/2]
int Markdown::processEmphasis1 (const char * data, int size, char c) [private]
processEmphasis2() [1/2]
int Markdown::processEmphasis2 (const char * data, int size, char c) [private]
process double emphasis
Definition at line 821 of file markdown.cpp.
{
  TRACE(data);
  int i = 0, len;
  while (i<size)
  {
    len = findEmphasisChar(data+i, size-i, c, 2);
    if (len==0)
    {
      TRACE_RESULT(0);
      return 0;
    }
    i += len;
    if (i+1<size && data[i]==c && data[i+1]==c && i && data[i-1]!=' ' &&
        data[i-1]!='\n'
       )
    {
      if (c == '~') m_out.addStr("<strike>");
      else m_out.addStr("<strong>");
      processInline(data,i);
      if (c == '~') m_out.addStr("</strike>");
      else m_out.addStr("</strong>");
      TRACE_RESULT(i+2);
      return i + 2;
    }
    i++;
  }
  TRACE_RESULT(0);
  return 0;
}
References GrowBuf::addStr(), c, data, findEmphasisChar(), len, m_out, processInline(), size, TRACE, and TRACE_RESULT.
Referenced by processEmphasis(), and processEmphasis3().
processEmphasis2() [2/2]
int Markdown::processEmphasis2 (const char * data, int size, char c) [private]
processEmphasis3() [1/2]
int Markdown::processEmphasis3 (const char * data, int size, char c) [private]
Parsing triple emphasis. Finds the first closing tag, and delegates to the other emph
Definition at line 856 of file markdown.cpp.
{
  TRACE(data);
  int i = 0, len;
  while (i<size)
  {
    len = findEmphasisChar(data+i, size-i, c, 3);
    if (len==0)
    {
      TRACE_RESULT(0);
      return 0;
    }
    i+=len;
    /* skip whitespace preceded symbols */
    if (data[i]!=c || data[i-1]==' ' || data[i-1]=='\n')
    {
      continue;
    }
    if (i+2<size && data[i+1]==c && data[i+2]==c)
    {
      m_out.addStr("<em><strong>");
      processInline(data,i);
      m_out.addStr("</strong></em>");
      TRACE_RESULT(i+3);
      return i+3;
    }
    else if (i+1<size && data[i+1]==c)
    {
      // double symbol found, handing over to emph1
      len = processEmphasis1(data-2, size+2, c);
      if (len==0)
      {
        TRACE_RESULT(0);
        return 0;
      }
      else
      {
        TRACE_RESULT(len-2);
        return len - 2;
      }
    }
    else
    {
      // single symbol found, handing over to emph2
      len = processEmphasis2(data-1, size+1, c);
      if (len==0)
      {
        TRACE_RESULT(0);
        return 0;
      }
      else
      {
        TRACE_RESULT(len-1);
        return len - 1;
      }
    }
  }
  TRACE_RESULT(0);
  return 0;
}
References GrowBuf::addStr(), c, data, findEmphasisChar(), len, m_out, processEmphasis1(), processEmphasis2(), processInline(), size, TRACE, and TRACE_RESULT.
Referenced by processEmphasis().
processEmphasis3() [2/2]
int Markdown::processEmphasis3 (const char * data, int size, char c) [private]
processHtmlTag() [1/2]
int Markdown::processHtmlTag (const char * data, int offset, int size) [private]
Definition at line 1075 of file markdown.cpp.
{
  TRACE(data);
  return processHtmlTagWrite(data,offset,size,true);
}
References data, offset, processHtmlTagWrite(), size, and TRACE.
Referenced by Markdown().
processHtmlTag() [2/2]
int Markdown::processHtmlTag (const char * data, int offset, int size) [private]
processHtmlTagWrite() [1/2]
int Markdown::processHtmlTagWrite (const char * data, int offset, int size, bool doWrite) [private]
Process a HTML tag. Note that
..
 are treated specially, in the sense that all code inside is written unprocessed
Definition at line 985 of file markdown.cpp.
{
  TRACE(data);
  if (offset>0 && data[-1]=='\\') { TRACE_RESULT(0); return 0; } // escaped <
  // find the end of the html tag
  int i=1;
  int l=0;
  // compute length of the tag name
  while (i<size && isIdChar(i)) i++,l++;
  QCString tagName;
  convertStringFragment(tagName,data+1,i-1);
  if (tagName.lower()=="pre") // found <pre> tag
  {
    bool insideStr=FALSE;
    while (i<size-6)
    {
      char c=data[i];
      if (!insideStr && c=='<') // potential start of html tag
      {
        if (data[i+1]=='/' &&
            tolower(data[i+2])=='p' && tolower(data[i+3])=='r' &&
            tolower(data[i+4])=='e' && tolower(data[i+5])=='>')
        { // found </pre> tag, copy from start to end of tag
          if (doWrite) m_out.addStr(data,i+6);
          //printf("found <pre>..</pre> [%d..%d]\n",0,i+6);
          TRACE_RESULT(i+6);
          return i+6;
        }
      }
      else if (insideStr && c=='"')
      {
        if (data[i-1]!='\\') insideStr=FALSE;
      }
      else if (c=='"')
      {
        insideStr=TRUE;
      }
      i++;
    }
  }
  else // some other html tag
  {
    if (l>0 && i<size)
    {
      if (data[i]=='/' && i<size-1 && data[i+1]=='>') // <bla/>
      {
        //printf("Found htmlTag={%s}\n",qPrint(QCString(data).left(i+2)));
        if (doWrite) m_out.addStr(data,i+2);
        TRACE_RESULT(i+2);
        return i+2;
      }
      else if (data[i]=='>') // <bla>
      {
        //printf("Found htmlTag={%s}\n",qPrint(QCString(data).left(i+1)));
        if (doWrite) m_out.addStr(data,i+1);
        TRACE_RESULT(i+1);
        return i+1;
      }
      else if (data[i]==' ') // <bla attr=...
      {
        i++;
        bool insideAttr=FALSE;
        while (i<size)
        {
          if (!insideAttr && data[i]=='"')
          {
            insideAttr=TRUE;
          }
          else if (data[i]=='"' && data[i-1]!='\\')
          {
            insideAttr=FALSE;
          }
          else if (!insideAttr && data[i]=='>') // found end of tag
          {
            //printf("Found htmlTag={%s}\n",qPrint(QCString(data).left(i+1)));
            if (doWrite) m_out.addStr(data,i+1);
            TRACE_RESULT(i+1);
            return i+1;
          }
          i++;
        }
      }
    }
  }
  //printf("Not a valid html tag\n");
  TRACE_RESULT(0);
  return 0;
}
References GrowBuf::addStr(), c, convertStringFragment(), data, FALSE, isIdChar, QCString::lower(), m_out, offset, size, caseconvert::tolower, TRACE, TRACE_RESULT, and TRUE.
Referenced by findEndOfLine(), and processHtmlTag().
processHtmlTagWrite() [2/2]
int Markdown::processHtmlTagWrite (const char * data, int offset, int size, bool doWrite) [private]
processInline() [1/2]
void Markdown::processInline (const char * data, int size) [private]
Definition at line 1757 of file markdown.cpp.
{
  TRACE(data);
  int i=0, end=0;
  Action_t action;
  while (i<size)
  {
    // skip over character that do not trigger a specific action
    while (end<size && ((action=m_actions[static_cast<uchar>(data[end])])==0)) end++;
    // and add them to the output
    m_out.addStr(data+i,end-i);
    if (end>=size) break;
    i=end;
    // do the action matching a special character at i
    end = action(data+i,i,size-i);
    if (end<=0) // update end
    {
      end=i+1-end;
    }
    else // skip until end
    {
      i+=end;
      end=i;
    }
  }
}
References GrowBuf::addStr(), data, ghc::filesystem::end(), m_actions, m_out, size, and TRACE.
Referenced by process(), processEmphasis1(), processEmphasis2(), processEmphasis3(), and processLink().
processInline() [2/2]
void Markdown::processInline (const char * data, int size) [private]
processLink() [1/2]
int Markdown::processLink (const char * data, int offset, int size) [private]
Definition at line 1170 of file markdown.cpp.
{
  TRACE(data);
  QCString content;
  QCString link;
  QCString title;
  int contentStart,contentEnd,linkStart,titleStart,titleEnd;
  bool isImageLink = FALSE;
  bool isImageInline = FALSE;
  bool isToc = FALSE;
  int i=1;
  if (data[0]=='!')
  {
    isImageLink = TRUE;
    if (size<2 || data[1]!='[')
    {
      TRACE_RESULT(0);
      return 0;
    }
    // if there is non-whitespace before the ![ within the scope of two new lines, the image
    // is considered inlined, i.e. the image is not preceded by an empty line
    int numNLsNeeded=2;
    int pos = -1;
    while (pos>=-offset && numNLsNeeded>0)
    {
      if (data[pos]=='\n') numNLsNeeded--;
      else if (data[pos]!=' ') // found non-whitespace, stop searching
      {
        isImageInline=true;
        break;
      }
      pos--;
    }
    // skip '!['
    i++;
  }
  contentStart=i;
  int level=1;
  int nlTotal=0;
  int nl=0;
  // find the matching ]
  while (i<size)
  {
    if (data[i-1]=='\\') // skip escaped characters
    {
    }
    else if (data[i]=='[')
    {
      level++;
    }
    else if (data[i]==']')
    {
      level--;
      if (level<=0) break;
    }
    else if (data[i]=='\n')
    {
      nl++;
      if (nl>1) { TRACE_RESULT(0); return 0; } // only allow one newline in the content
    }
    i++;
  }
  nlTotal += nl;
  nl = 0;
  if (i>=size) return 0; // premature end of comment -> no link
  contentEnd=i;
  convertStringFragment(content,data+contentStart,contentEnd-contentStart);
  //printf("processLink: content={%s}\n",qPrint(content));
  if (!isImageLink && content.isEmpty()) { TRACE_RESULT(0); return 0; } // no link text
  i++; // skip over ]
  bool whiteSpace = false;
  // skip whitespace
  while (i<size && data[i]==' ') {whiteSpace = true; i++;}
  if (i<size && data[i]=='\n') // one newline allowed here
  {
    whiteSpace = true;
    i++;
    nl++;
    // skip more whitespace
    while (i<size && data[i]==' ') i++;
  }
  nlTotal += nl;
  nl = 0;
  if (whiteSpace && i<size && (data[i]=='(' || data[i]=='[')) return 0;
  bool explicitTitle=FALSE;
  if (i<size && data[i]=='(') // inline link
  {
    i++;
    while (i<size && data[i]==' ') i++;
    bool uriFormat=false;
    if (i<size && data[i]=='<') { i++; uriFormat=true; }
    linkStart=i;
    int braceCount=1;
    while (i<size && data[i]!='\'' && data[i]!='"' && braceCount>0)
    {
      if (data[i]=='\n') // unexpected EOL
      {
        nl++;
        if (nl>1) { TRACE_RESULT(0); return 0; }
      }
      else if (data[i]=='(')
      {
        braceCount++;
      }
      else if (data[i]==')')
      {
        braceCount--;
      }
      if (braceCount>0)
      {
        i++;
      }
    }
    nlTotal += nl;
    nl = 0;
    if (i>=size || data[i]=='\n') { TRACE_RESULT(0); return 0; }
    convertStringFragment(link,data+linkStart,i-linkStart);
    link = link.stripWhiteSpace();
    //printf("processLink: link={%s}\n",qPrint(link));
    if (link.isEmpty()) { TRACE_RESULT(0); return 0; }
    if (uriFormat && link.at(link.length()-1)=='>') link=link.left(link.length()-1);
    // optional title
    if (data[i]=='\'' || data[i]=='"')
    {
      char c = data[i];
      i++;
      titleStart=i;
      nl=0;
      while (i<size)
      {
        if (data[i]=='\n')
        {
          if (nl>1) { TRACE_RESULT(0); return 0; }
          nl++;
        }
        else if (data[i]=='\\') // escaped char in string
        {
          i++;
        }
        else if (data[i]==c)
        {
          i++;
          break;
        }
        i++;
      }
      if (i>=size)
      {
        TRACE_RESULT(0);
        return 0;
      }
      titleEnd = i-1;
      // search back for closing marker
      while (titleEnd>titleStart && data[titleEnd]==' ') titleEnd--;
      if (data[titleEnd]==c) // found it
      {
        convertStringFragment(title,data+titleStart,titleEnd-titleStart);
        explicitTitle=TRUE;
        while (i<size)
        {
          if (data[i]==' ')i++; // remove space after the closing quote and the closing bracket
          else if (data[i] == ')') break; // the end bracket
          else // illegal
          {
            TRACE_RESULT(0);
            return 0;
          }
        }
      }
      else
      {
        TRACE_RESULT(0);
        return 0;
      }
    }
    i++;
  }
  else if (i<size && data[i]=='[') // reference link
  {
    i++;
    linkStart=i;
    nl=0;
    // find matching ]
    while (i<size && data[i]!=']')
    {
      if (data[i]=='\n')
      {
        nl++;
        if (nl>1) { TRACE_RESULT(0); return 0; }
      }
      i++;
    }
    if (i>=size) { TRACE_RESULT(0); return 0; }
    // extract link
    convertStringFragment(link,data+linkStart,i-linkStart);
    //printf("processLink: link={%s}\n",qPrint(link));
    link = link.stripWhiteSpace();
    if (link.isEmpty()) // shortcut link
    {
      link=content;
    }
    // lookup reference
    QCString link_lower = link.lower();
    auto lr_it=m_linkRefs.find(link_lower.str());
    if (lr_it!=m_linkRefs.end()) // found it
    {
      link = lr_it->second.link;
      title = lr_it->second.title;
      //printf("processLink: ref: link={%s} title={%s}\n",qPrint(link),qPrint(title));
    }
    else // reference not found!
    {
      //printf("processLink: ref {%s} do not exist\n",link.qPrint(lower()));
      TRACE_RESULT(0);
      return 0;
    }
    i++;
  }
  else if (i<size && data[i]!=':' && !content.isEmpty()) // minimal link ref notation [some id]
  {
    QCString content_lower = content.lower();
    auto lr_it = m_linkRefs.find(content_lower.str());
    //printf("processLink: minimal link {%s} lr=%p",qPrint(content),lr);
    if (lr_it!=m_linkRefs.end()) // found it
    {
      link = lr_it->second.link;
      title = lr_it->second.title;
      explicitTitle=TRUE;
      i=contentEnd;
    }
    else if (content=="TOC")
    {
      isToc=TRUE;
      i=contentEnd;
    }
    else
    {
      TRACE_RESULT(0);
      return 0;
    }
    i++;
  }
  else
  {
    TRACE_RESULT(0);
    return 0;
  }
  nlTotal += nl;
  // search for optional image attributes
  QCString attributes;
  if (isImageLink)
  {
    int j = i;
    // skip over whitespace
    while (j<size && data[j]==' ') { j++; }
    if (j<size && data[j]=='{') // we have attributes
    {
      i = j;
      // skip over '{'
      i++;
      int attributesStart=i;
      nl=0;
      // find the matching '}'
      while (i<size)
      {
        if (data[i-1]=='\\') // skip escaped characters
        {
        }
        else if (data[i]=='{')
        {
          level++;
        }
        else if (data[i]=='}')
        {
          level--;
          if (level<=0) break;
        }
        else if (data[i]=='\n')
        {
          nl++;
          if (nl>1) { TRACE_RESULT(0); return 0; } // only allow one newline in the content
        }
        i++;
      }
      nlTotal += nl;
      if (i>=size) return 0; // premature end of comment -> no attributes
      int attributesEnd=i;
      convertStringFragment(attributes,data+attributesStart,attributesEnd-attributesStart);
      i++; // skip over '}'
    }
    if (!isImageInline)
    {
      // if there is non-whitespace after the image within the scope of two new lines, the image
      // is considered inlined, i.e. the image is not followed by an empty line
      int numNLsNeeded=2;
      int pos = i;
      while (pos<size && numNLsNeeded>0)
      {
        if (data[pos]=='\n') numNLsNeeded--;
        else if (data[pos]!=' ') // found non-whitespace, stop searching
        {
          isImageInline=true;
          break;
        }
        pos++;
      }
    }
  }
  if (isToc) // special case for [TOC]
  {
    int toc_level = Config_getInt(TOC_INCLUDE_HEADINGS);
    if (toc_level > 0 && toc_level <=5)
    {
      m_out.addStr("@tableofcontents{html:");
      m_out.addStr(QCString().setNum(toc_level));
      m_out.addStr("}");
    }
  }
  else if (isImageLink)
  {
    bool ambig;
    FileDef *fd=0;
    if (link.find("@ref ")!=-1 || link.find("\\ref ")!=-1 ||
        (fd=findFileDef(Doxygen::imageNameLinkedMap,link,ambig)))
        // assume doxygen symbol link or local image link
    {
      // check if different handling is needed per format
      writeMarkdownImage("html", isImageInline, explicitTitle, title, content, link, attributes, fd);
      writeMarkdownImage("latex", isImageInline, explicitTitle, title, content, link, attributes, fd);
      writeMarkdownImage("rtf", isImageInline, explicitTitle, title, content, link, attributes, fd);
      writeMarkdownImage("docbook", isImageInline, explicitTitle, title, content, link, attributes, fd);
      writeMarkdownImage("xml", isImageInline, explicitTitle, title, content, link, attributes, fd);
    }
    else
    {
      m_out.addStr("<img src=\"");
      m_out.addStr(link);
      m_out.addStr("\" alt=\"");
      m_out.addStr(content);
      m_out.addStr("\"");
      if (!title.isEmpty())
      {
        m_out.addStr(" title=\"");
        m_out.addStr(substitute(title.simplifyWhiteSpace(),"\"","&quot;"));
        m_out.addStr("\"");
      }
      m_out.addStr("/>");
    }
  }
  else
  {
    SrcLangExt lang = getLanguageFromFileName(link);
    int lp=-1;
    if ((lp=link.find("@ref "))!=-1 || (lp=link.find("\\ref "))!=-1 || (lang==SrcLangExt_Markdown && !isURL(link)))
        // assume doxygen symbol link
    {
      if (lp==-1) // link to markdown page
      {
        m_out.addStr("@ref ");
        if (!(Portable::isAbsolutePath(link) || isURL(link)))
        {
          FileInfo forg(link.str());
          if (forg.exists() && forg.isReadable())
          {
            link = forg.absFilePath();
          }
          else if (!(forg.exists() && forg.isReadable()))
          {
            FileInfo fi(m_fileName.str());
            QCString mdFile = m_fileName.left(m_fileName.length()-fi.fileName().length()) + link;
            FileInfo fmd(mdFile.str());
            if (fmd.exists() && fmd.isReadable())
            {
              link = fmd.absFilePath().data();
            }
          }
        }
      }
      m_out.addStr(link);
      m_out.addStr(" \"");
      if (explicitTitle && !title.isEmpty())
      {
        m_out.addStr(substitute(title,"\"","&quot;"));
      }
      else
      {
        m_out.addStr(substitute(content,"\"","&quot;"));
      }
      m_out.addStr("\"");
    }
    else if (link.find('/')!=-1 || link.find('.')!=-1 || link.find('#')!=-1)
    { // file/url link
      if (link.at(0) == '#')
      {
        m_out.addStr("@ref ");
        m_out.addStr(link.mid(1));
        m_out.addStr(" \"");
        m_out.addStr(substitute(content.simplifyWhiteSpace(),"\"","&quot;"));
        m_out.addStr("\"");
      }
      else
      {
        m_out.addStr("<a href=\"");
        m_out.addStr(link);
        m_out.addStr("\"");
        for (int ii = 0; ii < nlTotal; ii++) m_out.addStr("\n");
        if (!title.isEmpty())
        {
          m_out.addStr(" title=\"");
          m_out.addStr(substitute(title.simplifyWhiteSpace(),"\"","&quot;"));
          m_out.addStr("\"");
        }
        m_out.addStr(" ");
        m_out.addStr(externalLinkTarget());
        m_out.addStr(">");
        content = substitute(content.simplifyWhiteSpace(),"\"","\\\"");
        processInline(content.data(),content.length());
        m_out.addStr("</a>");
      }
    }
    else // avoid link to e.g. F[x](y)
    {
      //printf("no link for '%s'\n",qPrint(link));
      TRACE_RESULT(0);
      return 0;
    }
  }
  TRACE_RESULT(i);
  return i;
}
References FileInfo::absFilePath(), GrowBuf::addStr(), QCString::at(), c, Config_getInt, convertStringFragment(), data, QCString::data(), FileInfo::exists(), externalLinkTarget(), FALSE, FileInfo::fileName(), QCString::find(), findFileDef(), getLanguageFromFileName(), Doxygen::imageNameLinkedMap, Portable::isAbsolutePath(), QCString::isEmpty(), FileInfo::isReadable(), isURL(), QCString::left(), QCString::length(), level, QCString::lower(), m_fileName, m_linkRefs, m_out, QCString::mid(), offset, processInline(), QCString::simplifyWhiteSpace(), size, SrcLangExt_Markdown, QCString::str(), QCString::stripWhiteSpace(), substitute(), TRACE, TRACE_RESULT, TRUE, and writeMarkdownImage().
Referenced by Markdown().
processLink() [2/2]
int Markdown::processLink (const char * data, int , int size) [private]
processNmdash() [1/2]
int Markdown::processNmdash (const char * data, int off, int size) [private]
Process ndash and mdashes
Definition at line 921 of file markdown.cpp.
{
  TRACE(data);
  // precondition: data[0]=='-'
  int i=1;
  int count=1;
  if (i<size && data[i]=='-') // found --
  {
    count++,i++;
  }
  if (i<size && data[i]=='-') // found ---
  {
    count++,i++;
  }
  if (i<size && data[i]=='-') // found ----
  {
    count++;
  }
  if (count>=2 && off>=2 && qstrncmp(data-2,"<!",2)==0)
  { TRACE_RESULT(1-count); return 1-count; } // start HTML comment
  if (count==2 && (data[2]=='>'))
  { TRACE_RESULT(0); return 0; } // end HTML comment
  if (count==2 && (off<8 || qstrncmp(data-8,"operator",8)!=0)) // -- => ndash
  {
    m_out.addStr("&ndash;");
    TRACE_RESULT(2);
    return 2;
  }
  else if (count==3) // --- => ndash
  {
    m_out.addStr("&mdash;");
    TRACE_RESULT(3);
    return 3;
  }
  // not an ndash or mdash
  TRACE_RESULT(0);
  return 0;
}
References GrowBuf::addStr(), data, m_out, qstrncmp(), size, TRACE, and TRACE_RESULT.
Referenced by Markdown().
processNmdash() [2/2]
int Markdown::processNmdash (const char * data, int off, int size) [private]
processQuotations() [1/2]
QCString Markdown::processQuotations (const QCString & s, int refIndent) [private]
Definition at line 2917 of file markdown.cpp.
{
  TRACE(s);
  m_out.clear();
  const char *data = s.data();
  int size = s.length();
  int i=0,end=0,pi=-1;
  int blockStart,blockEnd,blockOffset;
  bool newBlock = false;
  bool insideList = false;
  int currentIndent = refIndent;
  int listIndent = refIndent;
  QCString lang;
  while (i<size)
  {
    findEndOfLine(data,size,pi,i,end);
    // line is now found at [i..end)
    int lineIndent=0;
    while (lineIndent<end && data[i+lineIndent]==' ') lineIndent++;
    //printf("** lineIndent=%d line=(%s)\n",lineIndent,qPrint(QCString(data+i).left(end-i)));
    if (newBlock)
    {
      //printf("** end of block\n");
      if (insideList && lineIndent<currentIndent) // end of list
      {
        //printf("** end of list\n");
        currentIndent = refIndent;
        insideList = false;
      }
      newBlock = false;
    }
    if ((listIndent=isListMarker(data+i,end-i))) // see if we need to increase the indent level
    {
      if (listIndent<currentIndent+4)
      {
        //printf("** start of list\n");
        insideList = true;
        currentIndent = listIndent;
      }
    }
    else if (isEndOfList(data+i,end-i))
    {
      //printf("** end of list\n");
      insideList = false;
      currentIndent = listIndent;
    }
    else if (isEmptyLine(data+i,end-i))
    {
      //printf("** new block\n");
      newBlock = true;
    }
    //printf("currentIndent=%d listIndent=%d refIndent=%d\n",currentIndent,listIndent,refIndent);
    if (pi!=-1)
    {
      if (isFencedCodeBlock(data+pi,size-pi,currentIndent,lang,blockStart,blockEnd,blockOffset))
      {
        auto addSpecialCommand = [&](const QCString &startCmd,const QCString &endCmd)
        {
          int cmdPos = pi+blockStart+1;
          QCString pl = QCString(data+cmdPos).left(blockEnd-blockStart-1);
          uint ii = 0;
          // check for absence of start command, either @start<cmd>, or \\start<cmd>
          while (ii<pl.length() && qisspace(pl[ii])) ii++; // skip leading whitespace
          if (ii+startCmd.length()>=pl.length() || // no room for start command
              (pl[ii]!='\\' && pl[ii]!='@') || // no @ or \ after whitespace
              qstrncmp(pl.data()+ii+1,startCmd.data(),startCmd.length())!=0) // no start command
          {
            pl = "@"+startCmd+"\\ilinebr " + pl + " @"+endCmd;
          }
          processSpecialCommand(pl.data(),0,pl.length());
        };
        if (!Config_getString(PLANTUML_JAR_PATH).isEmpty() && lang=="plantuml")
        {
          addSpecialCommand("startuml","enduml");
        }
        else if (Config_getBool(HAVE_DOT) && lang=="dot")
        {
          addSpecialCommand("dot","enddot");
        }
        else if (lang=="msc") // msc is built-in
        {
          addSpecialCommand("msc","endmsc");
        }
        else // normal code block
        {
          writeFencedCodeBlock(data+pi,lang.data(),blockStart,blockEnd);
        }
        i=pi+blockOffset;
        pi=-1;
        end=i+1;
        continue;
      }
      else if (isBlockQuote(data+pi,i-pi,currentIndent))
      {
        i = pi+writeBlockQuote(data+pi,size-pi);
        pi=-1;
        end=i+1;
        continue;
      }
      else
      {
        //printf("quote m_out={%s}\n",QCString(data+pi).left(i-pi).data());
        m_out.addStr(data+pi,i-pi);
      }
    }
    pi=i;
    i=end;
  }
  if (pi!=-1 && pi<size) // deal with the last line
  {
    if (isBlockQuote(data+pi,size-pi,currentIndent))
    {
      writeBlockQuote(data+pi,size-pi);
    }
    else
    {
      m_out.addStr(data+pi,size-pi);
    }
  }
  m_out.addChar(0);
  //printf("Process quotations\n---- input ----\n%s\n---- output ----\n%s\n------------\n",
  // qPrint(s),m_out.get());
  return m_out.get();
}
References GrowBuf::addChar(), GrowBuf::addStr(), GrowBuf::clear(), Config_getBool, Config_getString, gdFont::data, data, QCString::data(), ghc::filesystem::end(), findEndOfLine(), GrowBuf::get(), isBlockQuote(), isEmptyLine(), isEndOfList(), isFencedCodeBlock(), isListMarker(), QCString::left(), QCString::length(), m_out, processSpecialCommand(), qisspace(), qstrncmp(), s, size, TRACE, writeBlockQuote(), and writeFencedCodeBlock().
Referenced by process().
processQuotations() [2/2]
QCString Markdown::processQuotations (const QCString & s, int refIndent) [private]
processQuoted() [1/2]
int Markdown::processQuoted (const char * data, int , int size) [private]
Process quoted section `...`, can contain one embedded newline
Definition at line 961 of file markdown.cpp.
{
  TRACE(data);
  int i=1;
  int nl=0;
  while (i<size && data[i]!='"' && nl<2)
  {
    if (data[i]=='\n') nl++;
    i++;
  }
  if (i<size && data[i]=='"' && nl<2)
  {
    m_out.addStr(data,i+1);
    TRACE_RESULT(i+2);
    return i+1;
  }
  // not a quoted section
  TRACE_RESULT(0);
  return 0;
}
References GrowBuf::addStr(), data, m_out, size, TRACE, and TRACE_RESULT.
Referenced by Markdown().
processQuoted() [2/2]
int Markdown::processQuoted (const char * data, int , int size) [private]
processSpecialCommand() [1/2]
int Markdown::processSpecialCommand (const char * data, int offset, int size) [private]
Definition at line 1700 of file markdown.cpp.
{
  TRACE(data);
  int i=1;
  QCString endBlockName = isBlockCommand(data,offset,size);
  if (!endBlockName.isEmpty())
  {
    TRACE_MORE("endBlockName=%s\n",qPrint(endBlockName));
    int l = endBlockName.length();
    while (i<size-l)
    {
      if ((data[i]=='\\' || data[i]=='@') && // command
          data[i-1]!='\\' && data[i-1]!='@') // not escaped
      {
        if (qstrncmp(&data[i+1],endBlockName.data(),l)==0)
        {
          //printf("found end at %d\n",i);
          addStrEscapeUtf8Nbsp(data,i+1+l);
          TRACE_RESULT(i+1+l);
          return i+1+l;
        }
      }
      i++;
    }
  }
  int endPos = isSpecialCommand(data,offset,size);
  if (endPos>0)
  {
    m_out.addStr(data,endPos);
    return endPos;
  }
  if (size>1 && data[0]=='\\') // escaped characters
  {
    char c=data[1];
    if (c=='[' || c==']' || c=='*' || c=='!' || c=='(' || c==')' || c=='`' || c=='_')
    {
      m_out.addChar(data[1]);
      TRACE_RESULT(2);
      return 2;
    }
    else if (c=='-' && size>3 && data[2]=='-' && data[3]=='-') // \---
    {
      m_out.addStr(&data[1],3);
      TRACE_RESULT(2);
      return 4;
    }
    else if (c=='-' && size>2 && data[2]=='-') // \--
    {
      m_out.addStr(&data[1],2);
      TRACE_RESULT(3);
      return 3;
    }
  }
  TRACE_RESULT(0);
  return 0;
}
References GrowBuf::addChar(), GrowBuf::addStr(), addStrEscapeUtf8Nbsp(), c, data, QCString::data(), isBlockCommand(), QCString::isEmpty(), isSpecialCommand(), QCString::length(), m_out, offset, qPrint(), qstrncmp(), size, TRACE, TRACE_MORE, and TRACE_RESULT.
Referenced by Markdown(), and processQuotations().
processSpecialCommand() [2/2]
int Markdown::processSpecialCommand (const char * data, int offset, int size) [private]
setIndentLevel() [1/2]
void Markdown::setIndentLevel (int level) [inline]
Definition at line 38 of file markdown.h.
{ m_indentLevel = level; }
References level, and m_indentLevel.
Referenced by MarkdownOutlineParser::parseInput().
setIndentLevel() [2/2]
void Markdown::setIndentLevel (int level) [inline]
Definition at line 38 of file markdown.h.
{ m_indentLevel = level; }
References level, and m_indentLevel.
writeBlockQuote() [1/2]
int Markdown::writeBlockQuote (const char * data, int size) [private]
Definition at line 2707 of file markdown.cpp.
{
  TRACE(data);
  int l;
  int i=0;
  int curLevel=0;
  int end=0;
  while (i<size)
  {
    // find end of this line
    end=i+1;
    while (end<=size && data[end-1]!='\n') end++;
    int j=i;
    int level=0;
    int indent=i;
    // compute the quoting level
    while (j<end && (data[j]==' ' || data[j]=='>'))
    {
      if (data[j]=='>') { level++; indent=j+1; }
      else if (j>0 && data[j-1]=='>') indent=j+1;
      j++;
    }
    if (j>0 && data[j-1]=='>' &&
        !(j==size || data[j]=='\n')) // disqualify last > if not followed by space
    {
      indent--;
      level--;
      j--;
    }
    if (!level && data[j-1]!='\n') level=curLevel; // lazy
    if (level>curLevel) // quote level increased => add start markers
    {
      for (l=curLevel;l<level-1;l++)
      {
        m_out.addStr("<blockquote>");
      }
      m_out.addStr("<blockquote>&zwj;"); // empty blockquotes are also shown
    }
    else if (level<curLevel) // quote level decreased => add end markers
    {
      for (l=level;l<curLevel;l++)
      {
        m_out.addStr("</blockquote>");
      }
    }
    curLevel=level;
    if (level==0) break; // end of quote block
    // copy line without quotation marks
    m_out.addStr(data+indent,end-indent);
    // proceed with next line
    i=end;
  }
  // end of comment within blockquote => add end markers
  for (l=0;l<curLevel;l++)
  {
    m_out.addStr("</blockquote>");
  }
  TRACE_RESULT(i);
  return i;
}
References GrowBuf::addStr(), data, ghc::filesystem::end(), level, m_out, size, TRACE, and TRACE_RESULT.
Referenced by processQuotations().
writeBlockQuote() [2/2]
int Markdown::writeBlockQuote (const char * data, int size) [private]
writeCodeBlock() [1/2]
int Markdown::writeCodeBlock (const char * data, int size, int refIndent) [private]
Definition at line 2768 of file markdown.cpp.
{
  TRACE(data);
  int i=0,end;
  //printf("writeCodeBlock: data={%s}\n",qPrint(QCString(data).left(size)));
  // no need for \ilinebr here as the previous line was empty and was skipped
  m_out.addStr("@iverbatim\n");
  int emptyLines=0;
  while (i<size)
  {
    // find end of this line
    end=i+1;
    while (end<=size && data[end-1]!='\n') end++;
    int j=i;
    int indent=0;
    while (j<end && data[j]==' ') j++,indent++;
    //printf("j=%d end=%d indent=%d refIndent=%d tabSize=%d data={%s}\n",
    // j,end,indent,refIndent,Config_getInt(TAB_SIZE),qPrint(QCString(data+i).left(end-i-1)));
    if (j==end-1) // empty line
    {
      emptyLines++;
      i=end;
    }
    else if (indent>=refIndent+codeBlockIndent) // enough indent to continue the code block
    {
      while (emptyLines>0) // write skipped empty lines
      {
        // add empty line
        m_out.addStr("\n");
        emptyLines--;
      }
      // add code line minus the indent
      m_out.addStr(data+i+refIndent+codeBlockIndent,end-i-refIndent-codeBlockIndent);
      i=end;
    }
    else // end of code block
    {
      break;
    }
  }
  m_out.addStr("@endiverbatim\\ilinebr ");
  while (emptyLines>0) // write skipped empty lines
  {
    // add empty line
    m_out.addStr("\n");
    emptyLines--;
  }
  //printf("i=%d\n",i);
  TRACE_RESULT(i);
  return i;
}
References GrowBuf::addStr(), codeBlockIndent, data, ghc::filesystem::end(), m_out, size, TRACE, and TRACE_RESULT.
Referenced by processBlocks().
writeCodeBlock() [2/2]
int Markdown::writeCodeBlock (const char * data, int size, int refIndent) [private]
writeFencedCodeBlock() [1/2]
void Markdown::writeFencedCodeBlock (const char * data, const char * lng, int blockStart, int blockEnd) [private]
Definition at line 2896 of file markdown.cpp.
{
  TRACE(data);
  QCString lang = lng;
  if (!lang.isEmpty() && lang.at(0)=='.') lang=lang.mid(1);
  while (*data==' ' || *data=='\t')
  {
    m_out.addChar(*data++);
    blockStart--;
    blockEnd--;
  }
  m_out.addStr("@icode");
  if (!lang.isEmpty())
  {
    m_out.addStr("{"+lang+"}");
  }
  addStrEscapeUtf8Nbsp(data+blockStart,blockEnd-blockStart);
  m_out.addStr("@endicode");
}
References GrowBuf::addChar(), GrowBuf::addStr(), addStrEscapeUtf8Nbsp(), QCString::at(), data, QCString::isEmpty(), m_out, QCString::mid(), and TRACE.
Referenced by processBlocks(), and processQuotations().
writeFencedCodeBlock() [2/2]
void Markdown::writeFencedCodeBlock (const char * data, const char * lng, int blockStart, int blockEnd) [private]
writeMarkdownImage() [1/2]
void Markdown::writeMarkdownImage (const char * fmt, bool inline_img, bool explicitTitle, const QCString & title, const QCString & content, const QCString & link, const QCString & attributes, const FileDef * fd) [private]
Definition at line 1130 of file markdown.cpp.
{
  QCString attributes = getFilteredImageAttributes(fmt, attrs);
  m_out.addStr("@image");
  if (inline_img)
  {
    m_out.addStr("{inline}");
  }
  m_out.addStr(" ");
  m_out.addStr(fmt);
  m_out.addStr(" ");
  m_out.addStr(link.mid(fd ? 0 : 5));
  if (!explicitTitle && !content.isEmpty())
  {
    m_out.addStr(" \"");
    m_out.addStr(escapeDoubleQuotes(content));
    m_out.addStr("\"");
  }
  else if ((content.isEmpty() || explicitTitle) && !title.isEmpty())
  {
    m_out.addStr(" \"");
    m_out.addStr(escapeDoubleQuotes(title));
    m_out.addStr("\"");
  }
  else
  {
    m_out.addStr(" ");// so the line break will not be part of the image name
  }
  if (!attributes.isEmpty())
  {
    m_out.addStr(" ");
    m_out.addStr(attributes);
    m_out.addStr(" ");
  }
  m_out.addStr("\\ilinebr ");
}
References GrowBuf::addStr(), escapeDoubleQuotes(), fmt, getFilteredImageAttributes(), QCString::isEmpty(), m_out, and QCString::mid().
Referenced by processLink().
writeMarkdownImage() [2/2]
void Markdown::writeMarkdownImage (const char * fmt, bool inline_img, bool explicitTitle, const QCString & title, const QCString & content, const QCString & link, const QCString & attributes, const FileDef * fd) [private]
writeOneLineHeaderOrRuler() [1/2]
void Markdown::writeOneLineHeaderOrRuler (const char * data, int size) [private]
Definition at line 2650 of file markdown.cpp.
{
  TRACE(data);
  int level;
  QCString header;
  QCString id;
  if (isHRuler(data,size))
  {
    m_out.addStr("<hr>\n");
  }
  else if ((level=isAtxHeader(data,size,header,id,TRUE)))
  {
    QCString hTag;
    if (level<5 && !id.isEmpty())
    {
      switch(level)
      {
        case 1: m_out.addStr("@section ");
                 break;
        case 2: m_out.addStr("@subsection ");
                 break;
        case 3: m_out.addStr("@subsubsection ");
                 break;
        default: m_out.addStr("@paragraph ");
                 break;
      }
      m_out.addStr(id);
      m_out.addStr(" ");
      m_out.addStr(header);
      m_out.addStr("\n");
    }
    else
    {
      if (!id.isEmpty())
      {
        m_out.addStr("\\anchor "+id+"\\ilinebr ");
      }
      hTag.sprintf("h%d",level);
      m_out.addStr("<"+hTag+">");
      m_out.addStr(header);
      m_out.addStr("</"+hTag+">\n");
    }
  }
  else if (size>0) // nothing interesting -> just output the line
  {
    int tmpSize = size;
    if (data[size-1] == '\n') tmpSize--;
    m_out.addStr(data,tmpSize);
    if (hasLineBreak(data,size))
    {
      m_out.addStr("<br>");
    }
    if (tmpSize != size) m_out.addChar('\n');
  }
}
References GrowBuf::addChar(), GrowBuf::addStr(), data, hasLineBreak(), id, isAtxHeader(), isHRuler(), level, m_out, size, QCString::sprintf(), TRACE, and TRUE.
Referenced by processBlocks().
writeOneLineHeaderOrRuler() [2/2]
void Markdown::writeOneLineHeaderOrRuler (const char * data, int size) [private]
writeTableBlock() [1/2]
int Markdown::writeTableBlock (const char * data, int size) [private]
Definition at line 2430 of file markdown.cpp.
{
  TRACE(data);
  int i=0,j,k;
  int columns,start,end,cc;
  i = findTableColumns(data,size,start,end,columns);
  int headerStart = start;
  int headerEnd = end;
  // read cell alignments
  int ret = findTableColumns(data+i,size-i,start,end,cc);
  k=0;
  std::vector<int> columnAlignment(columns);
  bool leftMarker=FALSE,rightMarker=FALSE;
  bool startFound=FALSE;
  j=start+i;
  while (j<=end+i)
  {
    if (!startFound)
    {
      if (data[j]==':') { leftMarker=TRUE; startFound=TRUE; }
      if (data[j]=='-') startFound=TRUE;
      //printf(" data[%d]=%c startFound=%d\n",j,data[j],startFound);
    }
    if (data[j]=='-') rightMarker=FALSE;
    else if (data[j]==':') rightMarker=TRUE;
    if (j<=end+i && (data[j]=='|' && (j==0 || data[j-1]!='\\')))
    {
      if (k<columns)
      {
        columnAlignment[k] = markersToAlignment(leftMarker,rightMarker);
        //printf("column[%d] alignment=%d\n",k,columnAlignment[k]);
        leftMarker=FALSE;
        rightMarker=FALSE;
        startFound=FALSE;
      }
      k++;
    }
    j++;
  }
  if (k<columns)
  {
    columnAlignment[k] = markersToAlignment(leftMarker,rightMarker);
    //printf("column[%d] alignment=%d\n",k,columnAlignment[k]);
  }
  // proceed to next line
  i+=ret;
  // Store the table cell information by row then column. This
  // allows us to handle row spanning.
  std::vector<std::vector<TableCell> > tableContents;
  int m=headerStart;
  std::vector<TableCell> headerContents(columns);
  for (k=0;k<columns;k++)
  {
    while (m<=headerEnd && (data[m]!='|' || (m>0 && data[m-1]=='\\')))
    {
      headerContents[k].cellText += data[m++];
    }
    m++;
    // do the column span test before stripping white space
    // || is spanning columns, | | is not
    headerContents[k].colSpan = headerContents[k].cellText.isEmpty();
    headerContents[k].cellText = headerContents[k].cellText.stripWhiteSpace();
  }
  tableContents.push_back(headerContents);
  // write table cells
  while (i<size)
  {
    ret = findTableColumns(data+i,size-i,start,end,cc);
    if (cc!=columns) break; // end of table
    j=start+i;
    k=0;
    std::vector<TableCell> rowContents(columns);
    while (j<=end+i)
    {
      if (j<=end+i && (data[j]=='|' && (j==0 || data[j-1]!='\\')))
      {
        // do the column span test before stripping white space
        // || is spanning columns, | | is not
        rowContents[k].colSpan = rowContents[k].cellText.isEmpty();
        rowContents[k].cellText = rowContents[k].cellText.stripWhiteSpace();
        k++;
      } // if (j<=end+i && (data[j]=='|' && (j==0 || data[j-1]!='\\')))
      else
      {
        rowContents[k].cellText += data[j];
      } // else { if (j<=end+i && (data[j]=='|' && (j==0 || data[j-1]!='\\'))) }
      j++;
    } // while (j<=end+i)
    // do the column span test before stripping white space
    // || is spanning columns, | | is not
    rowContents[k].colSpan = rowContents[k].cellText.isEmpty();
    rowContents[k].cellText = rowContents[k].cellText.stripWhiteSpace();
    tableContents.push_back(rowContents);
    // proceed to next line
    i+=ret;
  }
  m_out.addStr("<table class=\"markdownTable\">");
  QCString cellTag("th"), cellClass("class=\"markdownTableHead");
  for (unsigned row = 0; row < tableContents.size(); row++)
  {
    if (row)
    {
      if (row % 2)
      {
        m_out.addStr("\n<tr class=\"markdownTableRowOdd\">");
      }
      else
      {
        m_out.addStr("\n<tr class=\"markdownTableRowEven\">");
      }
    }
    else
    {
      m_out.addStr("\n <tr class=\"markdownTableHead\">");
    }
    for (int c = 0; c < columns; c++)
    {
      // save the cell text for use after column span computation
      QCString cellText(tableContents[row][c].cellText);
      // Row span handling. Spanning rows will contain a caret ('^').
      // If the current cell contains just a caret, this is part of an
      // earlier row's span and the cell should not be added to the
      // output.
      if (tableContents[row][c].cellText == "^")
      {
        continue;
      }
      if (tableContents[row][c].colSpan)
      {
        int cr = c;
        while (cr >= 0 && tableContents[row][cr].colSpan)
        {
          cr--;
        };
        if (cr >= 0 && tableContents[row][cr].cellText == "^") continue;
      }
      unsigned rowSpan = 1, spanRow = row+1;
      while ((spanRow < tableContents.size()) &&
             (tableContents[spanRow][c].cellText == "^"))
      {
        spanRow++;
        rowSpan++;
      }
      m_out.addStr(" <" + cellTag + " " + cellClass);
      // use appropriate alignment style
      switch (columnAlignment[c])
      {
        case AlignLeft: m_out.addStr("Left\""); break;
        case AlignRight: m_out.addStr("Right\""); break;
        case AlignCenter: m_out.addStr("Center\""); break;
        case AlignNone: m_out.addStr("None\""); break;
      }
      if (rowSpan > 1)
      {
        QCString spanStr;
        spanStr.setNum(rowSpan);
        m_out.addStr(" rowspan=\"" + spanStr + "\"");
      }
      // Column span handling, assumes that column spans will have
      // empty strings, which would indicate the sequence "||", used
      // to signify spanning columns.
      unsigned colSpan = 1;
      while ((c < columns-1) && tableContents[row][c+1].colSpan)
      {
        c++;
        colSpan++;
      }
      if (colSpan > 1)
      {
        QCString spanStr;
        spanStr.setNum(colSpan);
        m_out.addStr(" colspan=\"" + spanStr + "\"");
      }
      // need at least one space on either side of the cell text in
      // order for doxygen to do other formatting
      m_out.addStr("> " + cellText + " \\ilinebr </" + cellTag + ">");
    }
    cellTag = "td";
    cellClass = "class=\"markdownTableBody";
    m_out.addStr(" </tr>");
  }
  m_out.addStr("</table>\n");
  TRACE_RESULT(i);
  return i;
}
References GrowBuf::addStr(), AlignCenter, AlignLeft, AlignNone, AlignRight, c, data, ghc::filesystem::end(), FALSE, findTableColumns(), m_out, markersToAlignment(), QCString::setNum(), size, TRACE, TRACE_RESULT, and TRUE.
Referenced by processBlocks().
writeTableBlock() [2/2]
int Markdown::writeTableBlock (const char * data, int size) [private]
Member Data Documentation
m_actions
Markdown::Action_t Markdown::m_actions [private]
Definition at line 89 of file markdown.h.
Referenced by Markdown(), and processInline().
m_fileName
QCString Markdown::m_fileName [private]
Definition at line 85 of file markdown.h.
Referenced by processLink().
m_indentLevel
int Markdown::m_indentLevel =0 [private]
Definition at line 87 of file markdown.h.
Referenced by isAtxHeader(), isHeaderline(), and setIndentLevel().
m_lineNr
int Markdown::m_lineNr = 0 [private]
Definition at line 86 of file markdown.h.
Referenced by Markdown().
m_linkRefs
std::unordered_map< std::string, LinkRef > Markdown::m_linkRefs [private]
Definition at line 84 of file markdown.h.
Referenced by processBlocks(), and processLink().
m_out
GrowBuf Markdown::m_out [private]
Definition at line 88 of file markdown.h.
Referenced by addStrEscapeUtf8Nbsp(), detab(), process(), processBlocks(), processCodeSpan(), processEmphasis1(), processEmphasis2(), processEmphasis3(), processHtmlTagWrite(), processInline(), processLink(), processNmdash(), processQuotations(), processQuoted(), processSpecialCommand(), writeBlockQuote(), writeCodeBlock(), writeFencedCodeBlock(), writeMarkdownImage(), writeOneLineHeaderOrRuler(), and writeTableBlock().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/markdown.h
doxygen/src/markdown.h
doxygen/build/doxygen/src/markdown.cpp
doxygen/src/markdown.cpp