vhdl::parser::TokenManager Class Reference
#include <TokenManager.h>
Public Member Functions
virtual ~TokenManager ()
virtual Token * getNextToken ()=0
virtual void setParser (void *parser)
virtual void lexicalError ()
virtual ~TokenManager ()
virtual Token * getNextToken ()=0
virtual void setParser (void *parser)
virtual void lexicalError ()
Detailed Description
An implementation for this interface is generated by JavaCCParser. The user is free to use any implementation of their choice.
Definition at line 18 of file TokenManager.h.
Constructor & Destructor Documentation
 TokenManager() [1/2]
virtual vhdl::parser::TokenManager::~TokenManager () [inline], [virtual]
Definition at line 20 of file TokenManager.h.
{ }
 TokenManager() [2/2]
virtual vhdl::parser::TokenManager::~TokenManager () [inline], [virtual]
Definition at line 20 of file TokenManager.h.
{ }
Member Function Documentation
getNextToken() [1/2]
virtual Token * vhdl::parser::TokenManager::getNextToken () [pure virtual]
This gets the next token from the input stream. A token of kind 0 (<EOF>) should be returned on EOF.
Implemented in vhdl::parser::VhdlParserTokenManager, and vhdl::parser::VhdlParserTokenManager.
Referenced by vhdl::parser::VhdlParser::getNextToken(), vhdl::parser::VhdlParser::getToken(), vhdl::parser::VhdlParser::jj_consume_token(), vhdl::parser::VhdlParser::jj_ntk_f(), and vhdl::parser::VhdlParser::jj_scan_token().
getNextToken() [2/2]
virtual Token * vhdl::parser::TokenManager::getNextToken () [pure virtual]
This gets the next token from the input stream. A token of kind 0 (<EOF>) should be returned on EOF.
Implemented in vhdl::parser::VhdlParserTokenManager, and vhdl::parser::VhdlParserTokenManager.
lexicalError() [1/2]
virtual void vhdl::parser::TokenManager::lexicalError () [inline], [virtual]
Definition at line 26 of file TokenManager.h.
                                {
    std::cerr << "Lexical error encountered." << std::endl;
  }
lexicalError() [2/2]
virtual void vhdl::parser::TokenManager::lexicalError () [inline], [virtual]
Definition at line 26 of file TokenManager.h.
                                {
    std::cerr << "Lexical error encountered." << std::endl;
  }
setParser() [1/2]
virtual void vhdl::parser::TokenManager::setParser (void * parser) [inline], [virtual]
Definition at line 25 of file TokenManager.h.
{};
setParser() [2/2]
virtual void vhdl::parser::TokenManager::setParser (void * parser) [inline], [virtual]
Definition at line 25 of file TokenManager.h.
{};
The documentation for this class was generated from the following files:
doxygen/build/doxygen/vhdlparser/TokenManager.h
doxygen/vhdlparser/TokenManager.h