MemberDefImpl Class Reference
Classes
class IMPL
Public Member Functions
MemberDefImpl (const QCString &defFileName, int defLine, int defColumn, const QCString &type, const QCString &name, const QCString &args, const QCString &excp, Protection prot, Specifier virt, bool stat, Relationship related, MemberType t, const ArgumentList &tal, const ArgumentList &al, const QCString &metaData)
virtual ~MemberDefImpl ()
virtual DefType definitionType () const
virtual MemberDef * resolveAlias ()
virtual const MemberDef * resolveAlias () const
virtual CodeSymbolType codeSymbolType () const
virtual MemberDef * deepCopy () const
virtual void moveTo (Definition *)
virtual QCString getOutputFileBase () const
virtual QCString getReference () const
virtual QCString anchor () const
virtual QCString declaration () const
virtual QCString definition () const
virtual QCString typeString () const
virtual QCString argsString () const
virtual QCString excpString () const
virtual QCString bitfieldString () const
virtual QCString extraTypeChars () const
virtual const QCString & initializer () const
virtual int initializerLines () const
virtual uint64 getMemberSpecifiers () const
virtual const MemberList * getSectionList (const Definition *) const
virtual QCString displayDefinition () const
virtual const ClassDef * getClassDef () const
virtual const FileDef * getFileDef () const
virtual const NamespaceDef * getNamespaceDef () const
virtual const GroupDef * getGroupDef () const
virtual ClassDef * accessorClass () const
virtual QCString getReadAccessor () const
virtual QCString getWriteAccessor () const
virtual Grouping::GroupPri_t getGroupPri () const
virtual QCString getGroupFileName () const
virtual int getGroupStartLine () const
virtual bool getGroupHasDocs () const
virtual QCString qualifiedName () const
virtual QCString objCMethodName (bool localLink, bool showStatic) const
virtual Protection protection () const
virtual Specifier virtualness (int count=0) const
virtual MemberType memberType () const
virtual QCString memberTypeName () const
virtual bool isSignal () const
virtual bool isSlot () const
virtual bool isVariable () const
virtual bool isEnumerate () const
virtual bool isEnumValue () const
virtual bool isTypedef () const
virtual bool isSequence () const
virtual bool isDictionary () const
virtual bool isFunction () const
virtual bool isFunctionPtr () const
virtual bool isDefine () const
virtual bool isFriend () const
virtual bool isDCOP () const
virtual bool isProperty () const
virtual bool isEvent () const
virtual bool isRelated () const
virtual bool isForeign () const
virtual bool isStatic () const
virtual bool isInline () const
virtual bool isExplicit () const
virtual bool isMutable () const
virtual bool isGettable () const
virtual bool isPrivateGettable () const
virtual bool isProtectedGettable () const
virtual bool isSettable () const
virtual bool isPrivateSettable () const
virtual bool isProtectedSettable () const
virtual bool isReadable () const
virtual bool isWritable () const
virtual bool isAddable () const
virtual bool isRemovable () const
virtual bool isRaisable () const
virtual bool isFinal () const
virtual bool isAbstract () const
virtual bool isOverride () const
virtual bool isInitonly () const
virtual bool isOptional () const
virtual bool isRequired () const
virtual bool isNonAtomic () const
virtual bool isCopy () const
virtual bool isAssign () const
virtual bool isRetain () const
virtual bool isWeak () const
virtual bool isStrong () const
virtual bool isEnumStruct () const
virtual bool isUnretained () const
virtual bool isNew () const
virtual bool isSealed () const
virtual bool isImplementation () const
virtual bool isExternal () const
virtual bool isTypeAlias () const
virtual bool isDefault () const
virtual bool isDelete () const
virtual bool isNoExcept () const
virtual bool isAttribute () const
virtual bool isUNOProperty () const
virtual bool isReadonly () const
virtual bool isBound () const
virtual bool isConstrained () const
virtual bool isTransient () const
virtual bool isMaybeVoid () const
virtual bool isMaybeDefault () const
virtual bool isMaybeAmbiguous () const
virtual bool isPublished () const
virtual bool isTemplateSpecialization () const
virtual bool isObjCMethod () const
virtual bool isObjCProperty () const
virtual bool isCSharpProperty () const
virtual bool isConstructor () const
virtual bool isDestructor () const
virtual bool hasOneLineInitializer () const
virtual bool hasMultiLineInitializer () const
virtual bool showInCallGraph () const
virtual bool isStrongEnumValue () const
virtual bool livesInsideEnum () const
virtual bool isSliceLocal () const
virtual bool isConstExpr () const
virtual int numberOfFlowKeyWords () const
virtual bool isFriendToHide () const
virtual bool isNotFriend () const
virtual bool isFunctionOrSignalSlot () const
virtual bool isRelatedOrFriend () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool hasDocumentation () const
virtual bool isDeleted () const
virtual bool isBriefSectionVisible () const
virtual bool isDetailedSectionVisible (MemberListContainer container) const
virtual bool hasDetailedDescription () const
virtual bool isFriendClass () const
virtual bool isDocumentedFriendClass () const
virtual const MemberDef * reimplements () const
virtual const MemberVector & reimplementedBy () const
virtual bool isReimplementedBy (const ClassDef *cd) const
virtual ClassDef * relatedAlso () const
virtual bool hasDocumentedEnumValues () const
virtual const MemberDef * getAnonymousEnumType () const
virtual bool isDocsForDefinition () const
virtual const MemberDef * getEnumScope () const
virtual const MemberVector & enumFieldList () const
virtual void setEnumBaseType (const QCString &type)
virtual QCString enumBaseType () const
virtual bool hasExamples () const
virtual const ExampleList & getExamples () const
virtual bool isPrototype () const
virtual const ArgumentList & argumentList () const
virtual ArgumentList & argumentList ()
virtual const ArgumentList & declArgumentList () const
virtual const ArgumentList & templateArguments () const
virtual const ArgumentLists & definitionTemplateParameterLists () const
virtual int getMemberGroupId () const
virtual MemberGroup * getMemberGroup () const
virtual bool fromAnonymousScope () const
virtual bool anonymousDeclShown () const
virtual MemberDef * fromAnonymousMember () const
virtual bool hasCallGraph () const
virtual bool hasCallerGraph () const
virtual bool hasReferencesRelation () const
virtual bool hasReferencedByRelation () const
virtual const MemberDef * templateMaster () const
virtual QCString getScopeString () const
virtual ClassDef * getClassDefOfAnonymousType () const
virtual bool isTypedefValCached () const
virtual const ClassDef * getCachedTypedefVal () const
virtual QCString getCachedTypedefTemplSpec () const
virtual QCString getCachedResolvedTypedef () const
virtual MemberDef * memberDefinition () const
virtual MemberDef * memberDeclaration () const
virtual const MemberDef * inheritsDocsFrom () const
virtual const MemberDef * getGroupAlias () const
virtual ClassDef * category () const
virtual const MemberDef * categoryRelation () const
virtual QCString displayName (bool=TRUE) const
virtual QCString getDeclType () const
virtual StringVector getLabels (const Definition *container) const
virtual const ArgumentList & typeConstraints () const
virtual QCString requiresClause () const
virtual QCString documentation () const
virtual QCString briefDescription (bool abbr=FALSE) const
virtual QCString fieldType () const
virtual bool isReference () const
virtual QCString getDeclFileName () const
virtual int getDeclLine () const
virtual int getDeclColumn () const
virtual void setMemberType (MemberType t)
virtual void setDefinition (const QCString &d)
virtual void setFileDef (const FileDef *fd)
virtual void setAnchor ()
virtual void setProtection (Protection p)
virtual void setMemberSpecifiers (uint64 s)
virtual void mergeMemberSpecifiers (uint64 s)
virtual void setInitializer (const QCString &i)
virtual void setBitfields (const QCString &s)
virtual void setMaxInitLines (int lines)
virtual void setMemberClass (const ClassDef *cd)
virtual void setSectionList (const Definition *container, const MemberList *sl)
virtual void setGroupDef (const GroupDef *gd, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs, MemberDef *member=0)
virtual void setReadAccessor (const QCString &r)
virtual void setWriteAccessor (const QCString &w)
virtual void setTemplateSpecialization (bool b)
virtual void makeRelated ()
virtual void makeForeign ()
virtual void setInheritsDocsFrom (const MemberDef *md)
virtual void setTagInfo (const TagInfo *i)
virtual void setArgsString (const QCString &as)
virtual void setReimplements (const MemberDef *md)
virtual void insertReimplementedBy (const MemberDef *md)
virtual void setRelatedAlso (ClassDef *cd)
virtual void insertEnumField (const MemberDef *md)
virtual void setEnumScope (const MemberDef *md, bool livesInsideEnum=FALSE)
virtual void setEnumClassScope (const ClassDef *cd)
virtual void setDocumentedEnumValues (bool value)
virtual void setAnonymousEnumType (const MemberDef *md)
virtual bool addExample (const QCString &anchor, const QCString &name, const QCString &file)
virtual void setPrototype (bool p, const QCString &df, int line, int column)
virtual void setExplicitExternal (bool b, const QCString &df, int line, int column)
virtual void setDeclFile (const QCString &df, int line, int column)
virtual void moveArgumentList (std::unique_ptr< ArgumentList > al)
virtual void moveDeclArgumentList (std::unique_ptr< ArgumentList > al)
virtual void setDefinitionTemplateParameterLists (const ArgumentLists &lists)
virtual void setTypeConstraints (const ArgumentList &al)
virtual void setType (const QCString &t)
virtual void setAccessorType (ClassDef *cd, const QCString &t)
virtual void setNamespace (const NamespaceDef *nd)
virtual void setMemberGroup (MemberGroup *grp)
virtual void setMemberGroupId (int id)
virtual void makeImplementationDetail ()
virtual void setFromAnonymousScope (bool b) const
virtual void setFromAnonymousMember (MemberDef *m)
virtual void enableCallGraph (bool e)
virtual void enableCallerGraph (bool e)
virtual void enableReferencedByRelation (bool e)
virtual void enableReferencesRelation (bool e)
virtual void setTemplateMaster (const MemberDef *mt)
virtual void addListReference (Definition *d)
virtual void setDocsForDefinition (bool b)
virtual void setGroupAlias (const MemberDef *md)
virtual void cacheTypedefVal (const ClassDef *val, const QCString &templSpec, const QCString &resolvedType)
virtual void invalidateTypedefValCache ()
virtual void invalidateCachedArgumentTypes ()
virtual void setMemberDefinition (MemberDef *md)
virtual void setMemberDeclaration (MemberDef *md)
virtual void setAnonymousUsed () const
virtual void copyArgumentNames (const MemberDef *bmd)
virtual void setCategory (ClassDef *)
virtual void setCategoryRelation (const MemberDef *)
virtual void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)
virtual void setInbodyDocumentation (const QCString &d, const QCString &inbodyFile, int inbodyLine)
virtual void setHidden (bool b)
virtual void setRequiresClause (const QCString &req)
virtual void incrementFlowKeyWordCount ()
virtual void writeDeclaration (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool inGroup, int indentLevel, const ClassDef *inheritFrom=0, const QCString &inheritId=QCString()) const
virtual void writeDocumentation (const MemberList *ml, int memCount, int memTotal, OutputList &ol, const QCString &scopeName, const Definition *container, bool inGroup, bool showEnumValues=FALSE, bool showInline=FALSE) const
virtual void writeMemberDocSimple (OutputList &ol, const Definition *container) const
virtual void writeEnumDeclaration (OutputList &typeDecl, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd) const
virtual void writeTagFile (TextStream &, bool useQualifiedName) const
virtual void warnIfUndocumented () const
virtual void warnIfUndocumentedParams () const
virtual bool visibleInIndex () const
virtual void detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const
virtual MemberDefMutable * createTemplateInstanceMember (const ArgumentList &formalArgs, const std::unique_ptr< ArgumentList > &actualArgs) const
virtual void findSectionsInDocumentation ()
virtual void writeLink (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool onlyText=FALSE) const
virtual void resolveUnnamedParameters (const MemberDef *md)
MemberDefImpl (const QCString &defFileName, int defLine, int defColumn, const QCString &type, const QCString &name, const QCString &args, const QCString &excp, Protection prot, Specifier virt, bool stat, Relationship related, MemberType t, const ArgumentList &tal, const ArgumentList &al, const QCString &metaData)
virtual ~MemberDefImpl ()
virtual DefType definitionType () const
virtual MemberDef * resolveAlias ()
virtual const MemberDef * resolveAlias () const
virtual CodeSymbolType codeSymbolType () const
virtual MemberDef * deepCopy () const
virtual void moveTo (Definition *)
virtual QCString getOutputFileBase () const
virtual QCString getReference () const
virtual QCString anchor () const
virtual QCString declaration () const
virtual QCString definition () const
virtual QCString typeString () const
virtual QCString argsString () const
virtual QCString excpString () const
virtual QCString bitfieldString () const
virtual QCString extraTypeChars () const
virtual const QCString & initializer () const
virtual int initializerLines () const
virtual uint64 getMemberSpecifiers () const
virtual const MemberList * getSectionList (const Definition *) const
virtual QCString displayDefinition () const
virtual const ClassDef * getClassDef () const
virtual const FileDef * getFileDef () const
virtual const NamespaceDef * getNamespaceDef () const
virtual const GroupDef * getGroupDef () const
virtual ClassDef * accessorClass () const
virtual QCString getReadAccessor () const
virtual QCString getWriteAccessor () const
virtual Grouping::GroupPri_t getGroupPri () const
virtual QCString getGroupFileName () const
virtual int getGroupStartLine () const
virtual bool getGroupHasDocs () const
virtual QCString qualifiedName () const
virtual QCString objCMethodName (bool localLink, bool showStatic) const
virtual Protection protection () const
virtual Specifier virtualness (int count=0) const
virtual MemberType memberType () const
virtual QCString memberTypeName () const
virtual bool isSignal () const
virtual bool isSlot () const
virtual bool isVariable () const
virtual bool isEnumerate () const
virtual bool isEnumValue () const
virtual bool isTypedef () const
virtual bool isSequence () const
virtual bool isDictionary () const
virtual bool isFunction () const
virtual bool isFunctionPtr () const
virtual bool isDefine () const
virtual bool isFriend () const
virtual bool isDCOP () const
virtual bool isProperty () const
virtual bool isEvent () const
virtual bool isRelated () const
virtual bool isForeign () const
virtual bool isStatic () const
virtual bool isInline () const
virtual bool isExplicit () const
virtual bool isMutable () const
virtual bool isGettable () const
virtual bool isPrivateGettable () const
virtual bool isProtectedGettable () const
virtual bool isSettable () const
virtual bool isPrivateSettable () const
virtual bool isProtectedSettable () const
virtual bool isReadable () const
virtual bool isWritable () const
virtual bool isAddable () const
virtual bool isRemovable () const
virtual bool isRaisable () const
virtual bool isFinal () const
virtual bool isAbstract () const
virtual bool isOverride () const
virtual bool isInitonly () const
virtual bool isOptional () const
virtual bool isRequired () const
virtual bool isNonAtomic () const
virtual bool isCopy () const
virtual bool isAssign () const
virtual bool isRetain () const
virtual bool isWeak () const
virtual bool isStrong () const
virtual bool isEnumStruct () const
virtual bool isUnretained () const
virtual bool isNew () const
virtual bool isSealed () const
virtual bool isImplementation () const
virtual bool isExternal () const
virtual bool isTypeAlias () const
virtual bool isDefault () const
virtual bool isDelete () const
virtual bool isNoExcept () const
virtual bool isAttribute () const
virtual bool isUNOProperty () const
virtual bool isReadonly () const
virtual bool isBound () const
virtual bool isConstrained () const
virtual bool isTransient () const
virtual bool isMaybeVoid () const
virtual bool isMaybeDefault () const
virtual bool isMaybeAmbiguous () const
virtual bool isPublished () const
virtual bool isTemplateSpecialization () const
virtual bool isObjCMethod () const
virtual bool isObjCProperty () const
virtual bool isCSharpProperty () const
virtual bool isConstructor () const
virtual bool isDestructor () const
virtual bool hasOneLineInitializer () const
virtual bool hasMultiLineInitializer () const
virtual bool showInCallGraph () const
virtual bool isStrongEnumValue () const
virtual bool livesInsideEnum () const
virtual bool isSliceLocal () const
virtual bool isConstExpr () const
virtual int numberOfFlowKeyWords () const
virtual bool isFriendToHide () const
virtual bool isNotFriend () const
virtual bool isFunctionOrSignalSlot () const
virtual bool isRelatedOrFriend () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool hasDocumentation () const
virtual bool isDeleted () const
virtual bool isBriefSectionVisible () const
virtual bool isDetailedSectionVisible (MemberListContainer container) const
virtual bool hasDetailedDescription () const
virtual bool isFriendClass () const
virtual bool isDocumentedFriendClass () const
virtual const MemberDef * reimplements () const
virtual const MemberVector & reimplementedBy () const
virtual bool isReimplementedBy (const ClassDef *cd) const
virtual ClassDef * relatedAlso () const
virtual bool hasDocumentedEnumValues () const
virtual const MemberDef * getAnonymousEnumType () const
virtual bool isDocsForDefinition () const
virtual const MemberDef * getEnumScope () const
virtual const MemberVector & enumFieldList () const
virtual void setEnumBaseType (const QCString &type)
virtual QCString enumBaseType () const
virtual bool hasExamples () const
virtual const ExampleList & getExamples () const
virtual bool isPrototype () const
virtual const ArgumentList & argumentList () const
virtual ArgumentList & argumentList ()
virtual const ArgumentList & declArgumentList () const
virtual const ArgumentList & templateArguments () const
virtual const ArgumentLists & definitionTemplateParameterLists () const
virtual int getMemberGroupId () const
virtual MemberGroup * getMemberGroup () const
virtual bool fromAnonymousScope () const
virtual bool anonymousDeclShown () const
virtual MemberDef * fromAnonymousMember () const
virtual bool hasCallGraph () const
virtual bool hasCallerGraph () const
virtual bool hasReferencesRelation () const
virtual bool hasReferencedByRelation () const
virtual const MemberDef * templateMaster () const
virtual QCString getScopeString () const
virtual ClassDef * getClassDefOfAnonymousType () const
virtual bool isTypedefValCached () const
virtual const ClassDef * getCachedTypedefVal () const
virtual QCString getCachedTypedefTemplSpec () const
virtual QCString getCachedResolvedTypedef () const
virtual MemberDef * memberDefinition () const
virtual MemberDef * memberDeclaration () const
virtual const MemberDef * inheritsDocsFrom () const
virtual const MemberDef * getGroupAlias () const
virtual ClassDef * category () const
virtual const MemberDef * categoryRelation () const
virtual QCString displayName (bool=TRUE) const
virtual QCString getDeclType () const
virtual StringVector getLabels (const Definition *container) const
virtual const ArgumentList & typeConstraints () const
virtual QCString requiresClause () const
virtual QCString documentation () const
virtual QCString briefDescription (bool abbr=FALSE) const
virtual QCString fieldType () const
virtual bool isReference () const
virtual QCString getDeclFileName () const
virtual int getDeclLine () const
virtual int getDeclColumn () const
virtual void setMemberType (MemberType t)
virtual void setDefinition (const QCString &d)
virtual void setFileDef (const FileDef *fd)
virtual void setAnchor ()
virtual void setProtection (Protection p)
virtual void setMemberSpecifiers (uint64 s)
virtual void mergeMemberSpecifiers (uint64 s)
virtual void setInitializer (const QCString &i)
virtual void setBitfields (const QCString &s)
virtual void setMaxInitLines (int lines)
virtual void setMemberClass (const ClassDef *cd)
virtual void setSectionList (const Definition *container, const MemberList *sl)
virtual void setGroupDef (const GroupDef *gd, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs, MemberDef *member=0)
virtual void setReadAccessor (const QCString &r)
virtual void setWriteAccessor (const QCString &w)
virtual void setTemplateSpecialization (bool b)
virtual void makeRelated ()
virtual void makeForeign ()
virtual void setInheritsDocsFrom (const MemberDef *md)
virtual void setTagInfo (const TagInfo *i)
virtual void setArgsString (const QCString &as)
virtual void setReimplements (const MemberDef *md)
virtual void insertReimplementedBy (const MemberDef *md)
virtual void setRelatedAlso (ClassDef *cd)
virtual void insertEnumField (const MemberDef *md)
virtual void setEnumScope (const MemberDef *md, bool livesInsideEnum=FALSE)
virtual void setEnumClassScope (const ClassDef *cd)
virtual void setDocumentedEnumValues (bool value)
virtual void setAnonymousEnumType (const MemberDef *md)
virtual bool addExample (const QCString &anchor, const QCString &name, const QCString &file)
virtual void setPrototype (bool p, const QCString &df, int line, int column)
virtual void setExplicitExternal (bool b, const QCString &df, int line, int column)
virtual void setDeclFile (const QCString &df, int line, int column)
virtual void moveArgumentList (std::unique_ptr< ArgumentList > al)
virtual void moveDeclArgumentList (std::unique_ptr< ArgumentList > al)
virtual void setDefinitionTemplateParameterLists (const ArgumentLists &lists)
virtual void setTypeConstraints (const ArgumentList &al)
virtual void setType (const QCString &t)
virtual void setAccessorType (ClassDef *cd, const QCString &t)
virtual void setNamespace (const NamespaceDef *nd)
virtual void setMemberGroup (MemberGroup *grp)
virtual void setMemberGroupId (int id)
virtual void makeImplementationDetail ()
virtual void setFromAnonymousScope (bool b) const
virtual void setFromAnonymousMember (MemberDef *m)
virtual void enableCallGraph (bool e)
virtual void enableCallerGraph (bool e)
virtual void enableReferencedByRelation (bool e)
virtual void enableReferencesRelation (bool e)
virtual void setTemplateMaster (const MemberDef *mt)
virtual void addListReference (Definition *d)
virtual void setDocsForDefinition (bool b)
virtual void setGroupAlias (const MemberDef *md)
virtual void cacheTypedefVal (const ClassDef *val, const QCString &templSpec, const QCString &resolvedType)
virtual void invalidateTypedefValCache ()
virtual void invalidateCachedArgumentTypes ()
virtual void setMemberDefinition (MemberDef *md)
virtual void setMemberDeclaration (MemberDef *md)
virtual void setAnonymousUsed () const
virtual void copyArgumentNames (const MemberDef *bmd)
virtual void setCategory (ClassDef *)
virtual void setCategoryRelation (const MemberDef *)
virtual void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)
virtual void setInbodyDocumentation (const QCString &d, const QCString &inbodyFile, int inbodyLine)
virtual void setHidden (bool b)
virtual void setRequiresClause (const QCString &req)
virtual void incrementFlowKeyWordCount ()
virtual void writeDeclaration (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool inGroup, int indentLevel, const ClassDef *inheritFrom=0, const QCString &inheritId=QCString()) const
virtual void writeDocumentation (const MemberList *ml, int memCount, int memTotal, OutputList &ol, const QCString &scopeName, const Definition *container, bool inGroup, bool showEnumValues=FALSE, bool showInline=FALSE) const
virtual void writeMemberDocSimple (OutputList &ol, const Definition *container) const
virtual void writeEnumDeclaration (OutputList &typeDecl, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd) const
virtual void writeTagFile (TextStream &, bool useQualifiedName) const
virtual void warnIfUndocumented () const
virtual void warnIfUndocumentedParams () const
virtual bool visibleInIndex () const
virtual void detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const
virtual MemberDefMutable * createTemplateInstanceMember (const ArgumentList &formalArgs, const std::unique_ptr< ArgumentList > &actualArgs) const
virtual void findSectionsInDocumentation ()
virtual void writeLink (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool onlyText=FALSE) const
virtual void resolveUnnamedParameters (const MemberDef *md)
Private Member Functions
void _computeLinkableInProject ()
void _computeIsConstructor ()
void _computeIsDestructor ()
void _writeGroupInclude (OutputList &ol, bool inGroup) const
void _writeMultiLineInitializer (OutputList &ol, const QCString &scopeName) const
void _writeCallGraph (OutputList &ol) const
void _writeCallerGraph (OutputList &ol) const
void _writeReimplements (OutputList &ol) const
bool _isReimplements () const
void _writeReimplementedBy (OutputList &ol) const
size_t _countReimplementedBy () const
void _writeExamples (OutputList &ol) const
void _writeTypeConstraints (OutputList &ol) const
void _writeEnumValues (OutputList &ol, const Definition *container, const QCString &cfname, const QCString &ciname, const QCString &cname) const
void _writeCategoryRelation (OutputList &ol) const
void _writeTagData (const DefType) const
void _writeTemplatePrefix (OutputList &ol, const Definition *def, const ArgumentList &al, bool writeReqClause=true) const
bool _hasVisibleCallGraph () const
bool _hasVisibleCallerGraph () const
MemberDefImpl (const MemberDefImpl &)
MemberDefImpl & operator= (const MemberDefImpl &)
void _computeLinkableInProject ()
void _computeIsConstructor ()
void _computeIsDestructor ()
void _writeGroupInclude (OutputList &ol, bool inGroup) const
void _writeMultiLineInitializer (OutputList &ol, const QCString &scopeName) const
void _writeCallGraph (OutputList &ol) const
void _writeCallerGraph (OutputList &ol) const
void _writeReimplements (OutputList &ol) const
bool _isReimplements () const
void _writeReimplementedBy (OutputList &ol) const
size_t _countReimplementedBy () const
void _writeExamples (OutputList &ol) const
void _writeTypeConstraints (OutputList &ol) const
void _writeEnumValues (OutputList &ol, const Definition *container, const QCString &cfname, const QCString &ciname, const QCString &cname) const
void _writeCategoryRelation (OutputList &ol) const
void _writeTagData (const DefType) const
void _writeTemplatePrefix (OutputList &ol, const Definition *def, const ArgumentList &al, bool writeReqClause=true) const
bool _hasVisibleCallGraph () const
bool _hasVisibleCallerGraph () const
MemberDefImpl (const MemberDefImpl &)
MemberDefImpl & operator= (const MemberDefImpl &)
Private Attributes
IMPL * m_impl
uchar m_isLinkableCached
uchar m_isConstructorCached
uchar m_isDestructorCached
Additional Inherited Members
Detailed Description
Definition at line 51 of file memberdef.cpp.
Constructor & Destructor Documentation
MemberDefImpl() [1/4]
MemberDefImpl::MemberDefImpl (const QCString & df, int dl, int dc, const QCString & t, const QCString & na, const QCString & a, const QCString & e, Protection p, Specifier v, bool s, Relationship r, MemberType mt, const ArgumentList & tal, const ArgumentList & al, const QCString & meta)
Creates a new member definition.
Parameters
df File containing the definition of this member.
dl Line at which the member definition was found.
dc Column at which the member definition was found.
t A string representing the type of the member.
na A string representing the name of the member.
a A string representing the arguments of the member.
e A string representing the throw clause of the members.
p The protection context of the member, possible values are: Public, Protected, Private.
v The degree of 'virtualness' of the member, possible values are: Normal, Virtual, Pure.
s A boolean that is true iff the member is static.
r The relationship between the class and the member.
mt The kind of member. See MemberType for a list of all types.
tal The template arguments of this member.
al The arguments of this member. This is a structured form of the string past as argument a.
meta Slice metadata.
Definition at line 1387 of file memberdef.cpp.
                      : DefinitionMixin(df,dl,dc,removeRedundantWhiteSpace(na))
{
  //printf("MemberDefImpl::MemberDef(%s)\n",na);
  m_impl = new MemberDefImpl::IMPL;
  m_impl->init(this,t,a,e,p,v,s,r,mt,tal,al,meta);
  m_isLinkableCached = 0;
  m_isConstructorCached = 0;
  m_isDestructorCached = 0;
}
References a, e, MemberDefImpl::IMPL::init(), m_impl, m_isConstructorCached, m_isDestructorCached, m_isLinkableCached, p, r, and s.
Referenced by deepCopy().
 MemberDefImpl() [1/2]
MemberDefImpl::~MemberDefImpl () [virtual]
Destroys the member definition.
Definition at line 1444 of file memberdef.cpp.
{
  delete m_impl;
  //printf("%p: ~MemberDef()\n",this);
  m_impl=0;
}
References m_impl.
MemberDefImpl() [2/4]
MemberDefImpl::MemberDefImpl (const MemberDefImpl & md) [private]
Definition at line 1401 of file memberdef.cpp.
                                                    : DefinitionMixin(md)
{
  m_impl = new MemberDefImpl::IMPL;
  m_isLinkableCached = 0;
  m_isConstructorCached = 0;
  m_isDestructorCached = 0;
}
References m_impl, m_isConstructorCached, m_isDestructorCached, and m_isLinkableCached.
MemberDefImpl() [3/4]
MemberDefImpl::MemberDefImpl (const QCString & defFileName, int defLine, int defColumn, const QCString & type, const QCString & name, const QCString & args, const QCString & excp, Protection prot, Specifier virt, bool stat, Relationship related, MemberType t, const ArgumentList & tal, const ArgumentList & al, const QCString & metaData)
 MemberDefImpl() [2/2]
virtual MemberDefImpl::~MemberDefImpl () [virtual]
MemberDefImpl() [4/4]
MemberDefImpl::MemberDefImpl (const MemberDefImpl &) [private]
Member Function Documentation
_computeIsConstructor() [1/2]
void MemberDefImpl::_computeIsConstructor () [private]
Definition at line 4411 of file memberdef.cpp.
{
  m_isConstructorCached=1; // FALSE
  if (getClassDef())
  {
    if (m_impl->isDMember) // for D
    {
      m_isConstructorCached = name()=="this" ? 2 : 1;
      return;
    }
    else if (getLanguage()==SrcLangExt_PHP) // for PHP
    {
      m_isConstructorCached = name()=="__construct" ? 2 : 1;
      return;
    }
    else if (name()=="__init__" &&
             getLanguage()==SrcLangExt_Python) // for Python
    {
      m_isConstructorCached = 2; // TRUE
      return;
    }
    else // for other languages
    {
      QCString locName = getClassDef()->localName();
      int i=locName.find('<');
      if (i==-1) // not a template class
      {
        m_isConstructorCached = name()==locName ? 2 : 1;
      }
      else
      {
        m_isConstructorCached = name()==locName.left(i) ? 2 : 1;
      }
      return;
    }
  }
}
References QCString::find(), getClassDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), MemberDefImpl::IMPL::isDMember, QCString::left(), Definition::localName(), m_impl, m_isConstructorCached, DefinitionMixin< MemberDefMutable >::name(), SrcLangExt_PHP, and SrcLangExt_Python.
Referenced by isConstructor().
_computeIsConstructor() [2/2]
void MemberDefImpl::_computeIsConstructor () [private]
_computeIsDestructor() [1/2]
void MemberDefImpl::_computeIsDestructor () [private]
Definition at line 4461 of file memberdef.cpp.
{
  bool isDestructor;
  if (m_impl->isDMember) // for D
  {
    isDestructor = name()=="~this";
  }
  else if (getLanguage()==SrcLangExt_PHP) // for PHP
  {
    isDestructor = name()=="__destruct";
  }
  else if (name()=="__del__" &&
           getLanguage()==SrcLangExt_Python) // for Python
  {
    isDestructor=TRUE;
  }
  else // other languages
  {
    isDestructor =
           (name().find('~')!=-1 || name().find('!')!=-1) // The ! is for C++/CLI
           && name().find("operator")==-1;
  }
  m_isDestructorCached = isDestructor ? 2 : 1;
}
References QCString::find(), DefinitionMixin< MemberDefMutable >::getLanguage(), isDestructor(), MemberDefImpl::IMPL::isDMember, m_impl, m_isDestructorCached, DefinitionMixin< MemberDefMutable >::name(), SrcLangExt_PHP, SrcLangExt_Python, and TRUE.
Referenced by isDestructor().
_computeIsDestructor() [2/2]
void MemberDefImpl::_computeIsDestructor () [private]
_computeLinkableInProject() [1/2]
void MemberDefImpl::_computeLinkableInProject () [private]
Definition at line 1638 of file memberdef.cpp.
{
  bool extractStatic = Config_getBool(EXTRACT_STATIC);
  bool extractPrivateVirtual = Config_getBool(EXTRACT_PRIV_VIRTUAL);
  m_isLinkableCached = 2; // linkable
  //printf("MemberDefImpl::isLinkableInProject(name=%s)\n",qPrint(name()));
  if (isHidden())
  {
    //printf("is hidden\n");
    m_isLinkableCached = 1;
    return;
  }
  if (templateMaster())
  {
    //printf("has template master\n");
    m_isLinkableCached = templateMaster()->isLinkableInProject() ? 2 : 1;
    return;
  }
  if (isAnonymous())
  {
    //printf("name invalid\n");
    m_isLinkableCached = 1; // not a valid or a dummy name
    return;
  }
  if (!hasDocumentation() || isReference())
  {
    //printf("no docs or reference\n");
    m_isLinkableCached = 1; // no documentation
    return;
  }
  const GroupDef *groupDef = getGroupDef();
  const ClassDef *classDef = getClassDef();
  if (groupDef && !groupDef->isLinkableInProject())
  {
    //printf("group but group not linkable!\n");
    m_isLinkableCached = 1; // group but group not linkable
    return;
  }
  if (!groupDef && classDef && !classDef->isLinkableInProject())
  {
    //printf("in a class but class not linkable!\n");
    m_isLinkableCached = 1; // in class but class not linkable
    return;
  }
  const NamespaceDef *nspace = getNamespaceDef();
  const FileDef *fileDef = getFileDef();
  if (!groupDef && nspace && !m_impl->related && !nspace->isLinkableInProject()
      && (fileDef==0 || !fileDef->isLinkableInProject()))
  {
    //printf("in a namespace but namespace not linkable!\n");
    m_isLinkableCached = 1; // in namespace but namespace not linkable
    return;
  }
  if (!groupDef && !nspace &&
      !m_impl->related && !classDef &&
      fileDef && !fileDef->isLinkableInProject())
  {
    //printf("in a file but file not linkable!\n");
    m_isLinkableCached = 1; // in file (and not in namespace) but file not linkable
    return;
  }
  if ((!protectionLevelVisible(m_impl->prot) && m_impl->mtype!=MemberType_Friend) &&
       !(m_impl->prot==Private && (m_impl->virt!=Normal || isOverride() || isFinal()) && extractPrivateVirtual))
  {
    //printf("private and invisible!\n");
    m_isLinkableCached = 1; // hidden due to protection
    return;
  }
  if (m_impl->stat && classDef==0 && !extractStatic)
  {
    //printf("static and invisible!\n");
    m_isLinkableCached = 1; // hidden due to staticness
    return;
  }
  //printf("linkable!\n");
  return; // linkable!
}
References Config_getBool, getClassDef(), getFileDef(), getGroupDef(), getNamespaceDef(), hasDocumentation(), DefinitionMixin< MemberDefMutable >::isAnonymous(), isFinal(), DefinitionMixin< MemberDefMutable >::isHidden(), ClassDef::isLinkableInProject(), FileDef::isLinkableInProject(), GroupDef::isLinkableInProject(), MemberDef::isLinkableInProject(), NamespaceDef::isLinkableInProject(), isOverride(), isReference(), m_impl, m_isLinkableCached, MemberType_Friend, MemberDefImpl::IMPL::mtype, Normal, Private, MemberDefImpl::IMPL::prot, protectionLevelVisible(), MemberDefImpl::IMPL::related, MemberDefImpl::IMPL::stat, templateMaster(), and MemberDefImpl::IMPL::virt.
Referenced by isLinkableInProject().
_computeLinkableInProject() [2/2]
void MemberDefImpl::_computeLinkableInProject () [private]
_countReimplementedBy() [1/2]
size_t MemberDefImpl::_countReimplementedBy () const [private]
Definition at line 2866 of file memberdef.cpp.
{
  const MemberVector &bml=reimplementedBy();
  size_t count=0;
  for (const auto &bmd : bml)
  {
    const ClassDef *bcd=bmd->getClassDef();
    // count the members that directly inherit from md and for
    // which the member and class are visible in the docs.
    if (bcd && bmd->isLinkable() && bcd->isLinkable())
    {
      count++;
    }
  }
  return count;
}
References ClassDef::isLinkable(), and reimplementedBy().
Referenced by _writeReimplementedBy(), and hasDetailedDescription().
_countReimplementedBy() [2/2]
size_t MemberDefImpl::_countReimplementedBy () const [private]
_hasVisibleCallerGraph() [1/2]
bool MemberDefImpl::_hasVisibleCallerGraph () const [private]
Definition at line 5403 of file memberdef.cpp.
{
  bool enabled = m_impl->hasCallerGraph &&
         (isFunction() || isSlot() || isSignal()) &&
         Config_getBool(HAVE_DOT);
  if (enabled)
  {
    bool trivial = DotCallGraph::isTrivial(this,TRUE);
    return !trivial;
  }
  return FALSE;
}
References Config_getBool, FALSE, MemberDefImpl::IMPL::hasCallerGraph, isFunction(), isSignal(), isSlot(), DotCallGraph::isTrivial(), m_impl, and TRUE.
Referenced by _writeCallerGraph(), and hasDetailedDescription().
_hasVisibleCallerGraph() [2/2]
bool MemberDefImpl::_hasVisibleCallerGraph () const [private]
_hasVisibleCallGraph() [1/2]
bool MemberDefImpl::_hasVisibleCallGraph () const [private]
Definition at line 5385 of file memberdef.cpp.
{
  bool enabled = m_impl->hasCallGraph &&
         (isFunction() || isSlot() || isSignal()) &&
         Config_getBool(HAVE_DOT);
  if (enabled)
  {
    bool trivial = DotCallGraph::isTrivial(this,FALSE);
    return !trivial;
  }
  return FALSE;
}
References Config_getBool, FALSE, MemberDefImpl::IMPL::hasCallGraph, isFunction(), isSignal(), isSlot(), DotCallGraph::isTrivial(), and m_impl.
Referenced by _writeCallGraph(), and hasDetailedDescription().
_hasVisibleCallGraph() [2/2]
bool MemberDefImpl::_hasVisibleCallGraph () const [private]
_isReimplements() [1/2]
bool MemberDefImpl::_isReimplements () const [private]
Definition at line 2793 of file memberdef.cpp.
{
  const MemberDef *bmd=reimplements();
  const ClassDef *bcd=0;
  if (bmd && (bcd=bmd->getClassDef()))
  {
    // write class that contains a member that is reimplemented by this one
    if (bcd->isLinkable())
    {
      return true;
    }
  }
  return false;
}
References MemberDef::getClassDef(), ClassDef::isLinkable(), and reimplements().
Referenced by hasDetailedDescription().
_isReimplements() [2/2]
bool MemberDefImpl::_isReimplements () const [private]
_writeCallerGraph() [1/2]
void MemberDefImpl::_writeCallerGraph (OutputList & ol) const [private]
Definition at line 2771 of file memberdef.cpp.
{
  if (_hasVisibleCallerGraph())
  {
    DotCallGraph callerGraph(this, TRUE);
    if (callerGraph.isTooBig())
    {
       warn_uncond("Caller graph for '%s' not generated, too many nodes (%d), threshold is %d. Consider increasing DOT_GRAPH_MAX_NODES.\n",
           qPrint(qualifiedName()), callerGraph.numNodes(), Config_getInt(DOT_GRAPH_MAX_NODES));
    }
    else if (!callerGraph.isTrivial())
    {
      msg("Generating caller graph for function %s\n",qPrint(qualifiedName()));
      ol.disable(OutputGenerator::Man);
      ol.startCallGraph();
      ol.parseText(theTranslator->trCallerGraph());
      ol.endCallGraph(callerGraph);
      ol.enableAll();
    }
  }
}
References _hasVisibleCallerGraph(), Config_getInt, OutputList::disable(), OutputList::enableAll(), OutputList::endCallGraph(), DotCallGraph::isTooBig(), DotCallGraph::isTrivial(), OutputGenerator::Man, msg(), DotCallGraph::numNodes(), OutputList::parseText(), qPrint(), qualifiedName(), OutputList::startCallGraph(), theTranslator, Translator::trCallerGraph(), TRUE, and warn_uncond().
Referenced by writeDocumentation().
_writeCallerGraph() [2/2]
void MemberDefImpl::_writeCallerGraph (OutputList & ol) const [private]
_writeCallGraph() [1/2]
void MemberDefImpl::_writeCallGraph (OutputList & ol) const [private]
Definition at line 2748 of file memberdef.cpp.
{
  // write call graph
  if (_hasVisibleCallGraph())
  {
    DotCallGraph callGraph(this,FALSE);
    if (callGraph.isTooBig())
    {
       warn_uncond("Call graph for '%s' not generated, too many nodes (%d), threshold is %d. Consider increasing DOT_GRAPH_MAX_NODES.\n",
           qPrint(qualifiedName()), callGraph.numNodes(), Config_getInt(DOT_GRAPH_MAX_NODES));
    }
    else if (!callGraph.isTrivial())
    {
      msg("Generating call graph for function %s\n",qPrint(qualifiedName()));
      ol.disable(OutputGenerator::Man);
      ol.startCallGraph();
      ol.parseText(theTranslator->trCallGraph());
      ol.endCallGraph(callGraph);
      ol.enableAll();
    }
  }
}
References _hasVisibleCallGraph(), Config_getInt, OutputList::disable(), OutputList::enableAll(), OutputList::endCallGraph(), FALSE, DotCallGraph::isTooBig(), DotCallGraph::isTrivial(), OutputGenerator::Man, msg(), DotCallGraph::numNodes(), OutputList::parseText(), qPrint(), qualifiedName(), OutputList::startCallGraph(), theTranslator, Translator::trCallGraph(), and warn_uncond().
Referenced by writeDocumentation().
_writeCallGraph() [2/2]
void MemberDefImpl::_writeCallGraph (OutputList & ol) const [private]
_writeCategoryRelation() [1/2]
void MemberDefImpl::_writeCategoryRelation (OutputList & ol) const [private]
Definition at line 2942 of file memberdef.cpp.
{
  if (getClassDef()) // this should be a member of a class/category
  {
    //printf("%s: category %s relation %s class=%s categoryOf=%s\n",
    // qPrint(name()),
    // m_impl->category ? qPrint(m_impl->category->name()) : "<none>",
    // m_impl->categoryRelation ? qPrint(m_impl->categoryRelation->name()) : "<none>",
    // qPrint(m_impl->classDef->name()),
    // m_impl->classDef->categoryOf() ? qPrint(m_impl->classDef->categoryOf()->name()) : "<none>"
    //);
    QCString text;
    QCString ref;
    QCString file;
    QCString anc;
    QCString name;
    int i=-1;
    if (m_impl->categoryRelation && m_impl->categoryRelation->isLinkable())
    {
      if (m_impl->category)
      {
        // this member is in a normal class and implements method categoryRelation from category
        // so link to method 'categoryRelation' with 'provided by category 'category' text.
        text = theTranslator->trProvidedByCategory();
        name = m_impl->category->displayName();
      }
      else if (getClassDef()->categoryOf())
      {
        // this member is part of a category so link to the corresponding class member of the class we extend
        // so link to method 'categoryRelation' with 'extends class 'classDef->categoryOf()'
        text = theTranslator->trExtendsClass();
        name = getClassDef()->categoryOf()->displayName();
      }
      i=text.find("@0");
      if (i!=-1)
      {
        const MemberDef *md = m_impl->categoryRelation;
        ref = md->getReference();
        file = md->getOutputFileBase();
        anc = md->anchor();
      }
    }
    if (i!=-1 && !name.isEmpty())
    {
      ol.startParagraph();
      ol.parseText(text.left(i));
      ol.writeObjectLink(ref,file,anc,name);
      ol.parseText(text.mid(i+2));
      ol.endParagraph();
    }
  }
}
References MemberDef::anchor(), MemberDefImpl::IMPL::category, ClassDef::categoryOf(), MemberDefImpl::IMPL::categoryRelation, ClassDef::displayName(), OutputList::endParagraph(), caseconvert::file, QCString::find(), getClassDef(), MemberDef::getOutputFileBase(), MemberDef::getReference(), QCString::isEmpty(), MemberDef::isLinkable(), QCString::left(), m_impl, QCString::mid(), DefinitionMixin< MemberDefMutable >::name(), OutputList::parseText(), OutputList::startParagraph(), theTranslator, Translator::trExtendsClass(), Translator::trProvidedByCategory(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
_writeCategoryRelation() [2/2]
void MemberDefImpl::_writeCategoryRelation (OutputList & ol) const [private]
_writeEnumValues() [1/2]
void MemberDefImpl::_writeEnumValues (OutputList & ol, const Definition * container, const QCString & cfname, const QCString & ciname, const QCString & cname) const [private]
Definition at line 3016 of file memberdef.cpp.
{
  // For enum, we also write the documented enum values
  if (isEnumerate())
  {
    bool first=TRUE;
    //printf("** %s: enum values=%zu\n",qPrint(name()),enumFieldList().size());
    for (const auto &fmd : enumFieldList())
    {
      //printf("Enum %p: isLinkable()=%d\n",fmd,fmd->isLinkable());
      if (fmd->isLinkable())
      {
        if (first)
        {
          ol.startDescTable(theTranslator->trEnumerationValues());
        }
        ol.startDescTableRow();
        ol.addIndexItem(fmd->name(),ciname);
        ol.addIndexItem(ciname,fmd->name());
        ol.startDescTableTitle();
        ol.startDoxyAnchor(cfname,cname,fmd->anchor(),fmd->name(),fmd->argsString());
        first=FALSE;
        ol.docify(fmd->name());
        ol.disableAllBut(OutputGenerator::Man);
        ol.writeString(" ");
        ol.enableAll();
        ol.endDoxyAnchor(cfname,fmd->anchor());
        ol.endDescTableTitle();
        ol.startDescTableData();
        bool hasBrief = !fmd->briefDescription().isEmpty();
        bool hasDetails = !fmd->documentation().isEmpty();
        if (hasBrief)
        {
          ol.generateDoc(fmd->briefFile(),fmd->briefLine(),
              getOuterScope()?getOuterScope():container,
              fmd,fmd->briefDescription(),TRUE,FALSE,
              QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
        }
        // FIXME:PARA
        //if (!fmd->briefDescription().isEmpty() &&
        // !fmd->documentation().isEmpty())
        //{
        // ol.newParagraph();
        //}
        if (hasDetails)
        {
          ol.generateDoc(fmd->docFile(),fmd->docLine(),
              getOuterScope()?getOuterScope():container,
              fmd,fmd->documentation()+"\n",TRUE,FALSE,
              QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
        }
        ol.endDescTableData();
        ol.endDescTableRow();
      }
    }
    if (!first)
    {
      ol.endDescTable();
    }
  }
}
References OutputList::addIndexItem(), Definition::briefDescription(), Config_getBool, OutputList::disableAllBut(), OutputList::docify(), Definition::documentation(), OutputList::enableAll(), OutputList::endDescTable(), OutputList::endDescTableData(), OutputList::endDescTableRow(), OutputList::endDescTableTitle(), OutputList::endDoxyAnchor(), enumFieldList(), FALSE, OutputList::generateDoc(), DefinitionMixin< MemberDefMutable >::getOuterScope(), isEnumerate(), OutputGenerator::Man, OutputList::startDescTable(), OutputList::startDescTableData(), OutputList::startDescTableRow(), OutputList::startDescTableTitle(), OutputList::startDoxyAnchor(), theTranslator, Translator::trEnumerationValues(), TRUE, and OutputList::writeString().
Referenced by writeDocumentation().
_writeEnumValues() [2/2]
void MemberDefImpl::_writeEnumValues (OutputList & ol, const Definition * container, const QCString & cfname, const QCString & ciname, const QCString & cname) const [private]
_writeExamples() [1/2]
void MemberDefImpl::_writeExamples (OutputList & ol) const [private]
Definition at line 2995 of file memberdef.cpp.
{
  // write the list of examples that use this member
  if (hasExamples())
  {
    ol.startExamples();
    ol.startDescForItem();
    writeExamples(ol,m_impl->examples);
    ol.endDescForItem();
    ol.endExamples();
  }
}
References OutputList::endDescForItem(), OutputList::endExamples(), MemberDefImpl::IMPL::examples, hasExamples(), m_impl, OutputList::startDescForItem(), OutputList::startExamples(), and writeExamples().
Referenced by writeDocumentation().
_writeExamples() [2/2]
void MemberDefImpl::_writeExamples (OutputList & ol) const [private]
_writeGroupInclude() [1/2]
void MemberDefImpl::_writeGroupInclude (OutputList & ol, bool inGroup) const [private]
Definition at line 3163 of file memberdef.cpp.
{
  // only write out the include file if this is not part of a class or file
  // definition
  bool showGroupedMembInc = Config_getBool(SHOW_GROUPED_MEMB_INC);
  const FileDef *fd = getFileDef();
  QCString nm;
  if (fd) nm = getFileDef()->docName();
  if (inGroup && fd && showGroupedMembInc && !nm.isEmpty())
  {
    ol.startParagraph();
    ol.startTypewriter();
    SrcLangExt lang = getLanguage();
    bool isIDLorJava = lang==SrcLangExt_IDL || lang==SrcLangExt_Java;
    if (isIDLorJava)
    {
      ol.docify("import ");
    }
    else
    {
      ol.docify("#include ");
    }
    if (isIDLorJava) ol.docify("\""); else ol.docify("<");
    if (fd->isLinkable())
    {
      ol.writeObjectLink(fd->getReference(),fd->getOutputFileBase(),fd->anchor(),nm);
    }
    else
    {
      ol.docify(nm);
    }
    if (isIDLorJava) ol.docify("\""); else ol.docify(">");
    ol.endTypewriter();
    ol.endParagraph();
  }
}
References FileDef::anchor(), Config_getBool, OutputList::docify(), FileDef::docName(), OutputList::endParagraph(), OutputList::endTypewriter(), getFileDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), FileDef::getOutputFileBase(), Definition::getReference(), QCString::isEmpty(), FileDef::isLinkable(), SrcLangExt_IDL, SrcLangExt_Java, OutputList::startParagraph(), OutputList::startTypewriter(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
_writeGroupInclude() [2/2]
void MemberDefImpl::_writeGroupInclude (OutputList & ol, bool inGroup) const [private]
_writeMultiLineInitializer() [1/2]
void MemberDefImpl::_writeMultiLineInitializer (OutputList & ol, const QCString & scopeName) const [private]
Definition at line 3204 of file memberdef.cpp.
{
    //printf("md=%s initLines=%d init='%s'\n",qPrint(name()),initLines,qPrint(init));
    ol.startBold();
    if (m_impl->mtype==MemberType_Define)
      ol.parseText(theTranslator->trDefineValue());
    else
      ol.parseText(theTranslator->trInitialValue());
    ol.endBold();
    QCString langCorrected = getDefFileExtension();
    SrcLangExt srcLangExt = getLanguageFromFileName(getDefFileExtension());
    if (srcLangExt == SrcLangExt_Lex)
    {
      langCorrected = ".doxygen_lex_c";
      srcLangExt = SrcLangExt_Cpp;
    }
    auto intf = Doxygen::parserManager->getCodeParser(langCorrected);
    intf->resetCodeParserState();
    ol.startCodeFragment("DoxyCode");
    intf->parseCode(ol,scopeName,m_impl->initializer,srcLangExt,FALSE,QCString(),const_cast<FileDef*>(getFileDef()),
                     -1,-1,TRUE,this,FALSE,this);
    ol.endCodeFragment("DoxyCode");
}
References OutputList::endBold(), OutputList::endCodeFragment(), FALSE, ParserManager::getCodeParser(), DefinitionMixin< MemberDefMutable >::getDefFileExtension(), getFileDef(), getLanguageFromFileName(), MemberDefImpl::IMPL::initializer, m_impl, MemberType_Define, MemberDefImpl::IMPL::mtype, Doxygen::parserManager, OutputList::parseText(), SrcLangExt_Cpp, SrcLangExt_Lex, OutputList::startBold(), OutputList::startCodeFragment(), theTranslator, Translator::trDefineValue(), Translator::trInitialValue(), and TRUE.
Referenced by writeDocumentation().
_writeMultiLineInitializer() [2/2]
void MemberDefImpl::_writeMultiLineInitializer (OutputList & ol, const QCString & scopeName) const [private]
_writeReimplementedBy() [1/2]
void MemberDefImpl::_writeReimplementedBy (OutputList & ol) const [private]
Definition at line 2883 of file memberdef.cpp.
{
  const MemberVector &bml=reimplementedBy();
  size_t count = _countReimplementedBy();
  if (count>0)
  {
    auto replaceFunc = [&bml,&ol](size_t entryIndex)
    {
      size_t cnt=0;
      auto it = bml.begin();
      // find the entryIndex-th documented entry in the inheritance list.
      const MemberDef *bmd = 0;
      const ClassDef *bcd = 0;
      while (it!=bml.end())
      {
        bmd = *it;
        bcd = bmd->getClassDef();
        if (bmd->isLinkable() && bcd->isLinkable())
        {
          if (cnt==entryIndex) break;
          cnt++;
        }
        ++it;
      }
      if (bcd && bmd) // write link for marker
      {
        //ol.writeObjectLink(bcd->getReference(),bcd->getOutputFileBase(),
        // bmd->anchor(),bcd->name());
        ol.writeObjectLink(bmd->getReference(),bmd->getOutputFileBase(),
            bmd->anchor(),bcd->displayName());
        if (bmd->isLinkableInProject())
        {
          writePageRef(ol,bmd->getOutputFileBase(),bmd->anchor());
        }
      }
    };
    QCString reimplInLine;
    if (m_impl->virt==Pure || (getClassDef() && getClassDef()->compoundType()==ClassDef::Interface))
    {
      reimplInLine = theTranslator->trImplementedInList(static_cast<int>(count));
    }
    else
    {
      reimplInLine = theTranslator->trReimplementedInList(static_cast<int>(count));
    }
    // write the list of classes that overwrite this member
    ol.startParagraph();
    writeMarkerList(ol,
                    reimplInLine.str(),
                    count,
                    replaceFunc);
    ol.endParagraph();
  }
}
References _countReimplementedBy(), MemberDef::anchor(), MemberVector::begin(), ClassDef::displayName(), MemberVector::end(), OutputList::endParagraph(), getClassDef(), MemberDef::getClassDef(), MemberDef::getOutputFileBase(), MemberDef::getReference(), ClassDef::Interface, ClassDef::isLinkable(), MemberDef::isLinkable(), MemberDef::isLinkableInProject(), m_impl, Pure, reimplementedBy(), OutputList::startParagraph(), QCString::str(), theTranslator, Translator::trImplementedInList(), Translator::trReimplementedInList(), MemberDefImpl::IMPL::virt, writeMarkerList(), OutputList::writeObjectLink(), and writePageRef().
Referenced by writeDocumentation().
_writeReimplementedBy() [2/2]
void MemberDefImpl::_writeReimplementedBy (OutputList & ol) const [private]
_writeReimplements() [1/2]
void MemberDefImpl::_writeReimplements (OutputList & ol) const [private]
Definition at line 2807 of file memberdef.cpp.
{
  const MemberDef *bmd=reimplements();
  const ClassDef *bcd=0;
  if (bmd && (bcd=bmd->getClassDef()))
  {
    // write class that contains a member that is reimplemented by this one
    if (bcd->isLinkable())
    {
      ol.startParagraph();
      QCString reimplFromLine;
      if (bmd->virtualness()!=Pure && bcd->compoundType()!=ClassDef::Interface)
      {
        reimplFromLine = theTranslator->trReimplementedFromList(1);
      }
      else
      {
        reimplFromLine = theTranslator->trImplementedFromList(1);
      }
      int markerPos = reimplFromLine.find("@0");
      if (markerPos!=-1) // should always pass this.
      {
        ol.parseText(reimplFromLine.left(markerPos)); //text left from marker
        if (bmd->isLinkable()) // replace marker with link
        {
          //Definition *bd=bmd->group;
          //if (bd==0) bd=bcd;
          ol.writeObjectLink(bmd->getReference(),bmd->getOutputFileBase(),
              bmd->anchor(),bcd->displayName());
          //ol.writeObjectLink(bcd->getReference(),bcd->getOutputFileBase(),
          // bmd->anchor(),bcd->name());
          if (bmd->isLinkableInProject())
          {
            writePageRef(ol,bmd->getOutputFileBase(),bmd->anchor());
          }
        }
        else
        {
          ol.writeObjectLink(bcd->getReference(),bcd->getOutputFileBase(),
              QCString(),bcd->displayName());
          if (bcd->isLinkableInProject()/* && !Config_getBool(PDF_HYPERLINKS)*/)
          {
            writePageRef(ol,bcd->getOutputFileBase(),bcd->anchor());
          }
        }
        ol.parseText(reimplFromLine.right(
              reimplFromLine.length()-markerPos-2)); // text right from marker
      }
      else
      {
        err("translation error: no marker in trReimplementsFromList()\n");
      }
      ol.endParagraph();
    }
  }
}
References ClassDef::anchor(), MemberDef::anchor(), ClassDef::compoundType(), ClassDef::displayName(), OutputList::endParagraph(), err(), QCString::find(), MemberDef::getClassDef(), ClassDef::getOutputFileBase(), MemberDef::getOutputFileBase(), ClassDef::getReference(), MemberDef::getReference(), ClassDef::Interface, ClassDef::isLinkable(), MemberDef::isLinkable(), ClassDef::isLinkableInProject(), MemberDef::isLinkableInProject(), QCString::left(), QCString::length(), OutputList::parseText(), Pure, reimplements(), QCString::right(), OutputList::startParagraph(), theTranslator, Translator::trImplementedFromList(), Translator::trReimplementedFromList(), MemberDef::virtualness(), OutputList::writeObjectLink(), and writePageRef().
Referenced by writeDocumentation().
_writeReimplements() [2/2]
void MemberDefImpl::_writeReimplements (OutputList & ol) const [private]
_writeTagData() [1/2]
void MemberDefImpl::_writeTagData (const DefType) const [private]
_writeTagData() [2/2]
void MemberDefImpl::_writeTagData (const DefType) const [private]
_writeTemplatePrefix() [1/2]
void MemberDefImpl::_writeTemplatePrefix (OutputList & ol, const Definition * def, const ArgumentList & al, bool writeReqClause = true) const [private]
Definition at line 2021 of file memberdef.cpp.
{
  ol.docify("template<");
  for (auto it = al.begin(); it!=al.end();)
  {
    Argument a = *it;
    linkifyText(TextGeneratorOLImpl(ol), // out
        def, // scope
        getFileDef(), // fileScope
        this, // self
        a.type, // text
        FALSE // autoBreak
        );
    ol.docify(" ");
    ol.docify(a.name);
    if (a.defval.length()!=0)
    {
      ol.docify(" = ");
      ol.docify(a.defval);
    }
    ++it;
    if (it!=al.end()) ol.docify(", ");
  }
  ol.docify("> ");
  if (writeReqClause && !m_impl->requiresClause.isEmpty())
  {
    ol.lineBreak();
    ol.docify("requires ");
    linkifyText(TextGeneratorOLImpl(ol), // out
        def, // scope
        getFileDef(), // fileScope
        this, // self
        m_impl->requiresClause, // text
        FALSE // autoBreak
        );
  }
}
References a, ArgumentList::begin(), OutputList::docify(), ArgumentList::end(), FALSE, getFileDef(), QCString::isEmpty(), OutputList::lineBreak(), linkifyText(), m_impl, and MemberDefImpl::IMPL::requiresClause.
Referenced by writeDeclaration(), and writeDocumentation().
_writeTemplatePrefix() [2/2]
void MemberDefImpl::_writeTemplatePrefix (OutputList & ol, const Definition * def, const ArgumentList & al, bool writeReqClause = true) const [private]
_writeTypeConstraints() [1/2]
void MemberDefImpl::_writeTypeConstraints (OutputList & ol) const [private]
Definition at line 3008 of file memberdef.cpp.
{
  if (m_impl->typeConstraints.hasParameters())
  {
    writeTypeConstraints(ol,this,m_impl->typeConstraints);
  }
}
References ArgumentList::hasParameters(), m_impl, MemberDefImpl::IMPL::typeConstraints, and writeTypeConstraints().
Referenced by writeDocumentation().
_writeTypeConstraints() [2/2]
void MemberDefImpl::_writeTypeConstraints (OutputList & ol) const [private]
accessorClass() [1/2]
ClassDef * MemberDefImpl::accessorClass () const [virtual]
Implements MemberDef.
Definition at line 4649 of file memberdef.cpp.
{
  return m_impl->accessorClass;
}
References MemberDefImpl::IMPL::accessorClass, and m_impl.
Referenced by MemberDefImpl::IMPL::init().
accessorClass() [2/2]
virtual ClassDef * MemberDefImpl::accessorClass () const [virtual]
Implements MemberDef.
addExample() [1/2]
bool MemberDefImpl::addExample (const QCString & anchor, const QCString & name, const QCString & file) [virtual]
Implements MemberDefMutable.
Definition at line 1506 of file memberdef.cpp.
{
  //printf("%s::addExample(%s,%s,%s)\n",qPrint(name()),anchor,nameStr,file);
  return m_impl->examples.inSort(Example(anchor,nameStr,file));
}
References anchor(), Example, MemberDefImpl::IMPL::examples, caseconvert::file, ExampleList::inSort(), and m_impl.
addExample() [2/2]
virtual bool MemberDefImpl::addExample (const QCString & anchor, const QCString & name, const QCString & file) [virtual]
Implements MemberDefMutable.
addListReference() [1/2]
void MemberDefImpl::addListReference (Definition * d) [virtual]
Implements MemberDefMutable.
Definition at line 4248 of file memberdef.cpp.
{
  bool optimizeOutputForC = Config_getBool(OPTIMIZE_OUTPUT_FOR_C);
  //bool hideScopeNames = Config_getBool(HIDE_SCOPE_NAMES);
  //bool optimizeOutputJava = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
  //bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  SrcLangExt lang = getLanguage();
  if (!isLinkableInProject()) return;
  QCString memLabel;
  if (optimizeOutputForC)
  {
    memLabel=theTranslator->trGlobal(TRUE,TRUE);
  }
  else if (lang==SrcLangExt_Fortran)
  {
    memLabel=theTranslator->trSubprogram(TRUE,TRUE);
  }
  else
  {
    memLabel=theTranslator->trMember(TRUE,TRUE);
  }
  QCString memName = name();
  Definition *pd=getOuterScope();
  QCString pdName = pd->definitionType()==Definition::TypeClass ?
                    (toClassDef(pd))->displayName() : pd->name();
  QCString sep = getLanguageSpecificSeparator(lang,TRUE);
  QCString memArgs;
  if (!isRelated()
      /* && commented out as a result of bug 597016
      (
       (!hideScopeNames && // there is a scope
        pd && pd!=Doxygen::globalScope) // and we can show it
       ||
       (pd=getClassDef()) // it's a class so we
                                              // show the scope anyway
      )
      */
     )
  {
    if (isObjCMethod())
    {
      memName = "[" + pd->name() + " " + name() + "]";
    }
    else
    {
      if (pd!=Doxygen::globalScope) memName.prepend(pdName+sep);
      memArgs = argsString();
    }
  }
  const RefItemVector &xrefItems = xrefListItems();
  addRefItem(xrefItems,
        qualifiedName()+argsString(), // argsString is needed for overloaded functions (see bug 609624)
        memLabel,
        getOutputFileBase()+"#"+anchor(),memName,memArgs,pd);
}
References addRefItem(), anchor(), argsString(), Config_getBool, Definition::definitionType(), displayName(), DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), DefinitionMixin< MemberDefMutable >::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, isLinkableInProject(), isObjCMethod(), isRelated(), DefinitionMixin< MemberDefMutable >::name(), Definition::name(), QCString::prepend(), qualifiedName(), SrcLangExt_Fortran, theTranslator, toClassDef(), Translator::trGlobal(), Translator::trMember(), Translator::trSubprogram(), TRUE, Definition::TypeClass, and DefinitionMixin< MemberDefMutable >::xrefListItems().
addListReference() [2/2]
virtual void MemberDefImpl::addListReference (Definition * d) [virtual]
Implements MemberDefMutable.
anchor() [1/2]
QCString MemberDefImpl::anchor () const [virtual]
Returns the anchor within a page where this item can be found
Implements MemberDef.
Definition at line 1615 of file memberdef.cpp.
{
  QCString result=m_impl->anc;
  if (m_impl->groupAlias) return m_impl->groupAlias->anchor();
  if (m_impl->templateMaster) return m_impl->templateMaster->anchor();
  if (m_impl->enumScope && m_impl->enumScope!=this) // avoid recursion for C#'s public enum E { E, F }
  {
    result.prepend(m_impl->enumScope->anchor());
  }
  if (getGroupDef())
  {
    if (m_impl->groupMember)
    {
      result=m_impl->groupMember->anchor();
    }
    else if (getReference().isEmpty())
    {
      result.prepend("g");
    }
  }
  return result;
}
References MemberDefImpl::IMPL::anc, MemberDef::anchor(), MemberDefImpl::IMPL::enumScope, getGroupDef(), getReference(), MemberDefImpl::IMPL::groupAlias, MemberDefImpl::IMPL::groupMember, m_impl, QCString::prepend(), and MemberDefImpl::IMPL::templateMaster.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), addExample(), addListReference(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), getOutputFileBase(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), doxmlparser.compound.docTocItemType::set_anchor(), writeDeclaration(), writeDocumentation(), writeLink(), writeMemberDocSimple(), and writeTagFile().
anchor() [2/2]
virtual QCString MemberDefImpl::anchor () const [virtual]
Returns the anchor within a page where this item can be found
Implements MemberDef.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anonymousDeclShown() [1/2]
bool MemberDefImpl::anonymousDeclShown () const [virtual]
Implements MemberDef.
Definition at line 5370 of file memberdef.cpp.
{
  return m_impl->annUsed;
}
References MemberDefImpl::IMPL::annUsed, and m_impl.
anonymousDeclShown() [2/2]
virtual bool MemberDefImpl::anonymousDeclShown () const [virtual]
Implements MemberDef.
argsString() [1/2]
QCString MemberDefImpl::argsString () const [virtual]
Implements MemberDef.
Definition at line 4795 of file memberdef.cpp.
{
  return m_impl->args;
}
References MemberDefImpl::IMPL::args, and m_impl.
Referenced by addListReference(), isFunctionPtr(), warnIfUndocumented(), writeDeclaration(), writeDocumentation(), writeMemberDocSimple(), and writeTagFile().
argsString() [2/2]
virtual QCString MemberDefImpl::argsString () const [virtual]
Implements MemberDef.
argumentList() [1/4]
ArgumentList & MemberDefImpl::argumentList () [virtual]
Definition at line 5287 of file memberdef.cpp.
{
  return m_impl->defArgList;
}
References MemberDefImpl::IMPL::defArgList, and m_impl.
argumentList() [2/4]
virtual ArgumentList & MemberDefImpl::argumentList () [virtual]
argumentList() [3/4]
const ArgumentList & MemberDefImpl::argumentList () const [virtual]
Implements MemberDef.
Definition at line 5282 of file memberdef.cpp.
{
  return m_impl->defArgList;
}
References MemberDefImpl::IMPL::defArgList, and m_impl.
Referenced by detectUndocumentedParams(), and warnIfUndocumentedParams().
argumentList() [4/4]
virtual const ArgumentList & MemberDefImpl::argumentList () const [virtual]
Implements MemberDef.
bitfieldString() [1/2]
QCString MemberDefImpl::bitfieldString () const [virtual]
Implements MemberDef.
Definition at line 4805 of file memberdef.cpp.
{
  return m_impl->bitfields;
}
References MemberDefImpl::IMPL::bitfields, and m_impl.
bitfieldString() [2/2]
virtual QCString MemberDefImpl::bitfieldString () const [virtual]
Implements MemberDef.
briefDescription() [1/2]
QCString MemberDefImpl::briefDescription (bool abbreviate = FALSE) const [virtual]
Returns the brief description of this definition. This can include commands.
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 5972 of file memberdef.cpp.
{
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->briefDescription(abbr);
  }
  else
  {
    return DefinitionMixin::briefDescription(abbr);
  }
}
References MemberDef::briefDescription(), DefinitionMixin< Base >::briefDescription(), m_impl, and MemberDefImpl::IMPL::templateMaster.
Referenced by findSectionsInDocumentation(), hasDetailedDescription(), writeDeclaration(), writeDocumentation(), and writeMemberDocSimple().
briefDescription() [2/2]
virtual QCString MemberDefImpl::briefDescription (bool abbreviate = FALSE) const [virtual]
Returns the brief description of this definition. This can include commands.
Reimplemented from DefinitionMixin< MemberDefMutable >.
cacheTypedefVal() [1/2]
void MemberDefImpl::cacheTypedefVal (const ClassDef * val, const QCString & templSpec, const QCString & resolvedType) [virtual]
Implements MemberDefMutable.
Definition at line 5727 of file memberdef.cpp.
{
  m_impl->isTypedefValCached=TRUE;
  m_impl->cachedTypedefValue=val;
  m_impl->cachedTypedefTemplSpec=templSpec;
  m_impl->cachedResolvedType=resolvedType;
  //printf("MemberDefImpl::cacheTypedefVal=%s m_impl=%p\n",qPrint(m_impl->cachedResolvedType),m_impl);
}
References MemberDefImpl::IMPL::cachedResolvedType, MemberDefImpl::IMPL::cachedTypedefTemplSpec, MemberDefImpl::IMPL::cachedTypedefValue, MemberDefImpl::IMPL::isTypedefValCached, m_impl, TRUE, and testsqlite3::val.
cacheTypedefVal() [2/2]
virtual void MemberDefImpl::cacheTypedefVal (const ClassDef * val, const QCString & templSpec, const QCString & resolvedType) [virtual]
Implements MemberDefMutable.
category() [1/2]
ClassDef * MemberDefImpl::category () const [virtual]
Implements MemberDef.
Definition at line 5687 of file memberdef.cpp.
{
  return m_impl->category;
}
References MemberDefImpl::IMPL::category, and m_impl.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::getCategory(), doxmlparser.index.MixedContainer::getCategory(), doxmlparser.compound.MixedContainer::to_etree(), and doxmlparser.index.MixedContainer::to_etree().
category() [2/2]
virtual ClassDef * MemberDefImpl::category () const [virtual]
Implements MemberDef.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::getCategory(), doxmlparser.index.MixedContainer::getCategory(), doxmlparser.compound.MixedContainer::to_etree(), and doxmlparser.index.MixedContainer::to_etree().
categoryRelation() [1/2]
const MemberDef * MemberDefImpl::categoryRelation () const [virtual]
Implements MemberDef.
Definition at line 5697 of file memberdef.cpp.
{
  return m_impl->categoryRelation;
}
References MemberDefImpl::IMPL::categoryRelation, and m_impl.
categoryRelation() [2/2]
virtual const MemberDef * MemberDefImpl::categoryRelation () const [virtual]
Implements MemberDef.
codeSymbolType() [1/2]
CodeSymbolType MemberDefImpl::codeSymbolType () const [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 6040 of file memberdef.cpp.
{
  switch (memberType())
  {
    case MemberType_Define: return CodeSymbolType::Define;
    case MemberType_Function: return CodeSymbolType::Function;
    case MemberType_Variable: return CodeSymbolType::Variable;
    case MemberType_Typedef: return CodeSymbolType::Typedef;
    case MemberType_Enumeration: return CodeSymbolType::Enumeration;
    case MemberType_EnumValue: return CodeSymbolType::EnumValue;
    case MemberType_Signal: return CodeSymbolType::Signal;
    case MemberType_Slot: return CodeSymbolType::Slot;
    case MemberType_Friend: return CodeSymbolType::Friend;
    case MemberType_DCOP: return CodeSymbolType::DCOP;
    case MemberType_Property: return CodeSymbolType::Property;
    case MemberType_Event: return CodeSymbolType::Event;
    case MemberType_Interface: return CodeSymbolType::Interface;
    case MemberType_Service: return CodeSymbolType::Service;
    case MemberType_Sequence: return CodeSymbolType::Sequence;
    case MemberType_Dictionary: return CodeSymbolType::Dictionary;
  }
  return CodeSymbolType::Default;
}
References DCOP, Default, Define, Dictionary, Enumeration, EnumValue, Event, Friend, Function, Interface, memberType(), MemberType_DCOP, MemberType_Define, MemberType_Dictionary, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Sequence, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, Property, Sequence, Service, Signal, Slot, Typedef, and Variable.
codeSymbolType() [2/2]
virtual CodeSymbolType MemberDefImpl::codeSymbolType () const [virtual]
Used for syntax highlighting symbol class
Implements Definition.
copyArgumentNames() [1/2]
void MemberDefImpl::copyArgumentNames (const MemberDef * bmd) [virtual]
Implements MemberDefMutable.
Definition at line 5736 of file memberdef.cpp.
{
  {
    const ArgumentList &srcAl = bmd->argumentList();
    ArgumentList &dstAl = m_impl->defArgList;
    auto srcIt = srcAl.begin();
    auto dstIt = dstAl.begin();
    while (srcIt!=srcAl.end() && dstIt!=dstAl.end())
    {
      Argument &argDst = *dstIt;
      const Argument &argSrc = *srcIt;
      argDst.name = argSrc.name;
      argDst.docs = argSrc.docs;
      ++srcIt;
      ++dstIt;
    }
  }
  {
    const ArgumentList &srcAl = bmd->declArgumentList();
    ArgumentList &dstAl = m_impl->declArgList;
    auto srcIt = srcAl.begin();
    auto dstIt = dstAl.begin();
    while (srcIt!=srcAl.end() && dstIt!=dstAl.end())
    {
      Argument &argDst = *dstIt;
      const Argument &argSrc = *srcIt;
      argDst.name = argSrc.name;
      argDst.docs = argSrc.docs;
      ++srcIt;
      ++dstIt;
    }
  }
}
References MemberDef::argumentList(), ArgumentList::begin(), MemberDefImpl::IMPL::declArgList, MemberDef::declArgumentList(), MemberDefImpl::IMPL::defArgList, Argument::docs, ArgumentList::end(), m_impl, and Argument::name.
copyArgumentNames() [2/2]
virtual void MemberDefImpl::copyArgumentNames (const MemberDef * bmd) [virtual]
Implements MemberDefMutable.
createTemplateInstanceMember() [1/2]
MemberDefMutable * MemberDefImpl::createTemplateInstanceMember (const ArgumentList & formalArgs, const std::unique_ptr< ArgumentList > & actualArgs) const [virtual]
Implements MemberDef.
Definition at line 4176 of file memberdef.cpp.
{
  //printf(" Member %s %s %s\n",typeString(),qPrint(name()),argsString());
  std::unique_ptr<ArgumentList> actualArgList = std::make_unique<ArgumentList>(m_impl->defArgList);
  if (!m_impl->defArgList.empty())
  {
    // replace formal arguments with actuals
    for (Argument &arg : *actualArgList)
    {
      arg.type = substituteTemplateArgumentsInString(arg.type,formalArgs,actualArgs);
    }
    actualArgList->setTrailingReturnType(
       substituteTemplateArgumentsInString(actualArgList->trailingReturnType(),formalArgs,actualArgs));
  }
  QCString methodName=name();
  if (methodName.startsWith("operator ")) // conversion operator
  {
    methodName=substituteTemplateArgumentsInString(methodName,formalArgs,actualArgs);
  }
  MemberDefMutable *imd = createMemberDef(
                       getDefFileName(),getDefLine(),getDefColumn(),
                       substituteTemplateArgumentsInString(m_impl->type,formalArgs,actualArgs),
                       methodName,
                       substituteTemplateArgumentsInString(m_impl->args,formalArgs,actualArgs),
                       m_impl->exception, m_impl->prot,
                       m_impl->virt, m_impl->stat, m_impl->related, m_impl->mtype,
                       ArgumentList(), ArgumentList(), ""
                   );
  imd->moveArgumentList(std::move(actualArgList));
  imd->setDefinition(substituteTemplateArgumentsInString(m_impl->def,formalArgs,actualArgs));
  imd->setBodyDef(getBodyDef());
  imd->setBodySegment(getDefLine(),getStartBodyLine(),getEndBodyLine());
  //imd->setBodyMember(this);
  // TODO: init other member variables (if needed).
  // TODO: reimplemented info
  return imd;
}
References MemberDefImpl::IMPL::args, createMemberDef(), MemberDefImpl::IMPL::def, MemberDefImpl::IMPL::defArgList, ArgumentList::empty(), MemberDefImpl::IMPL::exception, DefinitionMixin< MemberDefMutable >::getBodyDef(), DefinitionMixin< MemberDefMutable >::getDefColumn(), DefinitionMixin< MemberDefMutable >::getDefFileName(), DefinitionMixin< MemberDefMutable >::getDefLine(), DefinitionMixin< MemberDefMutable >::getEndBodyLine(), DefinitionMixin< MemberDefMutable >::getStartBodyLine(), m_impl, MemberDefMutable::moveArgumentList(), MemberDefImpl::IMPL::mtype, DefinitionMixin< MemberDefMutable >::name(), MemberDefImpl::IMPL::prot, MemberDefImpl::IMPL::related, DefinitionMutable::setBodyDef(), DefinitionMutable::setBodySegment(), MemberDefMutable::setDefinition(), QCString::startsWith(), MemberDefImpl::IMPL::stat, substituteTemplateArgumentsInString(), MemberDefImpl::IMPL::type, and MemberDefImpl::IMPL::virt.
createTemplateInstanceMember() [2/2]
virtual MemberDefMutable * MemberDefImpl::createTemplateInstanceMember (const ArgumentList & formalArgs, const std::unique_ptr< ArgumentList > & actualArgs) const [virtual]
Implements MemberDef.
declaration() [1/2]
QCString MemberDefImpl::declaration () const [virtual]
Implements MemberDef.
Definition at line 4775 of file memberdef.cpp.
{
  return m_impl->decl;
}
References MemberDefImpl::IMPL::decl, and m_impl.
declaration() [2/2]
virtual QCString MemberDefImpl::declaration () const [virtual]
Implements MemberDef.
declArgumentList() [1/2]
const ArgumentList & MemberDefImpl::declArgumentList () const [virtual]
Implements MemberDef.
Definition at line 5292 of file memberdef.cpp.
{
  return m_impl->declArgList;
}
References MemberDefImpl::IMPL::declArgList, and m_impl.
Referenced by detectUndocumentedParams(), and warnIfUndocumentedParams().
declArgumentList() [2/2]
virtual const ArgumentList & MemberDefImpl::declArgumentList () const [virtual]
Implements MemberDef.
deepCopy() [1/2]
MemberDef * MemberDefImpl::deepCopy () const [virtual]
Implements MemberDef.
Definition at line 1409 of file memberdef.cpp.
{
  //MemberDef *result = new MemberDef(getDefFileName(),getDefLine(),name());
  MemberDefImpl *result = new MemberDefImpl(*this);
  // first copy everything by reference
  *result->m_impl = *m_impl;
  result->m_impl->defArgList = m_impl->defArgList;
  result->m_impl->tArgList = m_impl->tArgList;
  result->m_impl->typeConstraints = m_impl->typeConstraints;
  result->setDefinitionTemplateParameterLists(m_impl->defTmpArgLists);
  result->m_impl->declArgList = m_impl->declArgList;
  return result;
}
References MemberDefImpl::IMPL::declArgList, MemberDefImpl::IMPL::defArgList, MemberDefImpl::IMPL::defTmpArgLists, m_impl, MemberDefImpl(), setDefinitionTemplateParameterLists(), MemberDefImpl::IMPL::tArgList, and MemberDefImpl::IMPL::typeConstraints.
deepCopy() [2/2]
virtual MemberDef * MemberDefImpl::deepCopy () const [virtual]
Implements MemberDef.
definition() [1/2]
QCString MemberDefImpl::definition () const [virtual]
Implements MemberDef.
Definition at line 4780 of file memberdef.cpp.
{
  return m_impl->def;
}
References MemberDefImpl::IMPL::def, and m_impl.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), displayDefinition(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_definition(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.memberdefType::set_definition(), setAnchor(), and writeDocumentation().
definition() [2/2]
virtual QCString MemberDefImpl::definition () const [virtual]
Implements MemberDef.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_definition(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_definition().
definitionTemplateParameterLists() [1/2]
const ArgumentLists & MemberDefImpl::definitionTemplateParameterLists () const [virtual]
Implements MemberDef.
Definition at line 5350 of file memberdef.cpp.
{
  return m_impl->defTmpArgLists;
}
References MemberDefImpl::IMPL::defTmpArgLists, and m_impl.
definitionTemplateParameterLists() [2/2]
virtual const ArgumentLists & MemberDefImpl::definitionTemplateParameterLists () const [virtual]
Implements MemberDef.
definitionType() [1/2]
virtual DefType MemberDefImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements MemberDef.
Definition at line 61 of file memberdef.cpp.
{ return TypeMember; }
References Definition::TypeMember.
definitionType() [2/2]
virtual DefType MemberDefImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements MemberDef.
Definition at line 61 of file memberdef.cpp.
{ return TypeMember; }
References Definition::TypeMember.
detectUndocumentedParams() [1/2]
void MemberDefImpl::detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const [virtual]
Implements MemberDef.
Definition at line 3941 of file memberdef.cpp.
{
  // this function is called while parsing the documentation. A member can have multiple
  // documentation blocks, which could be handled by multiple threads, hence this guard.
  std::lock_guard<std::mutex> lock(g_detectUndocumentedParamsMutex);
  bool isPython = getLanguage()==SrcLangExt_Python;
  if (!m_impl->hasDocumentedParams && hasParamCommand)
  {
    //printf("%s:hasDocumentedParams=TRUE;\n",qPrint(name()));
    m_impl->hasDocumentedParams = TRUE;
  }
  else if (!m_impl->hasDocumentedParams)
  {
    const ArgumentList &al = argumentList();
    const ArgumentList &declAl = declArgumentList();
    bool allDoc=TRUE; // no parameter => all parameters are documented
    if (// member has parameters
        al.hasParameters() // with at least one parameter (that is not void)
       )
    {
      // see if all parameters have documentation
      for (auto it = al.begin(); it!=al.end() && allDoc; ++it)
      {
        Argument a = *it;
        if (!a.name.isEmpty() && a.type!="void" &&
            !(isPython && (a.name=="self" || a.name=="cls"))
           )
        {
          allDoc = !a.docs.isEmpty();
        }
        //printf("a->type=%s a->name=%s doc=%s\n",
        // qPrint(a->type),qPrint(a->name),qPrint(a->docs));
      }
      if (!allDoc && declAl.empty()) // try declaration arguments as well
      {
        allDoc=TRUE;
        for (auto it = al.begin(); it!=al.end() && allDoc; ++it)
        {
          Argument a = *it;
          if (!a.name.isEmpty() && a.type!="void" &&
              !(isPython && (a.name=="self" || a.name=="cls"))
             )
          {
            allDoc = !a.docs.isEmpty();
          }
          //printf("a->name=%s doc=%s\n",qPrint(a->name),qPrint(a->docs));
        }
      }
    }
    if (allDoc)
    {
      //printf("%s:hasDocumentedParams=TRUE;\n",qPrint(name()));
      m_impl->hasDocumentedParams = TRUE;
    }
  }
  //printf("Member %s hasDocumentedReturnType=%d hasReturnCommand=%d\n",
  // qPrint(name()),m_impl->hasDocumentedReturnType,hasReturnCommand);
  if (!m_impl->hasDocumentedReturnType && // docs not yet found
      hasReturnCommand)
  {
    m_impl->hasDocumentedReturnType = TRUE;
  }
}
References a, argumentList(), ArgumentList::begin(), declArgumentList(), ArgumentList::empty(), ArgumentList::end(), g_detectUndocumentedParamsMutex, DefinitionMixin< MemberDefMutable >::getLanguage(), MemberDefImpl::IMPL::hasDocumentedParams, MemberDefImpl::IMPL::hasDocumentedReturnType, ArgumentList::hasParameters(), m_impl, SrcLangExt_Python, and TRUE.
detectUndocumentedParams() [2/2]
virtual void MemberDefImpl::detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const [virtual]
Implements MemberDef.
displayDefinition() [1/2]
QCString MemberDefImpl::displayDefinition () const [virtual]
Implements MemberDef.
Definition at line 3087 of file memberdef.cpp.
{
  QCString ldef = definition();
  QCString title = name();
  if (isEnumerate())
  {
    if (isAnonymous())
    {
      ldef = title = "anonymous enum";
      if (!m_impl->enumBaseType.isEmpty())
      {
        ldef+=" : "+m_impl->enumBaseType;
      }
    }
    else
    {
      ldef.prepend("enum ");
      if (isSliceLocal())
      {
        ldef.prepend("local ");
      }
    }
  }
  else if (isEnumValue())
  {
    if (isAnonymous())
    {
      ldef=ldef.mid(2);
    }
  }
  std::string sdef = ldef.str();
  reg::Match match;
  if (reg::search(sdef,match,reAnonymous))
  {
    ldef = match.prefix().str() + " { ... } " + match.suffix().str();
  }
  const ClassDef *cd=getClassDef();
  if (cd && cd->isObjectiveC())
  {
    // strip scope name
    int ep = ldef.find("::");
    if (ep!=-1)
    {
      int sp=ldef.findRev(' ',ep);
      if (sp!=-1)
      {
        ldef=ldef.left(sp+1)+ldef.mid(ep+2);
      }
    }
    // strip keywords
    int dp = ldef.find(':');
    if (dp!=-1)
    {
      ldef=ldef.left(dp+1);
    }
    int l=ldef.length();
    //printf("start >%s<\n",qPrint(ldef));
    int i=l-1;
    while (i>=0 && (isId(ldef.at(i)) || ldef.at(i)==':')) i--;
    while (i>=0 && isspace(static_cast<uchar>(ldef.at(i)))) i--;
    if (i>0)
    {
      // insert braches around the type
      QCString tmp("("+ldef.left(i+1)+")"+ldef.mid(i+1));
      ldef=tmp;
    }
    //printf("end >%s< i=%d\n",qPrint(ldef),i);
    if (isStatic()) ldef.prepend("+ "); else ldef.prepend("- ");
  }
  SrcLangExt lang = getLanguage();
  QCString sep = getLanguageSpecificSeparator(lang,TRUE);
  return substitute(ldef,"::",sep);
}
References QCString::at(), definition(), MemberDefImpl::IMPL::enumBaseType, QCString::find(), QCString::findRev(), getClassDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), DefinitionMixin< MemberDefMutable >::isAnonymous(), QCString::isEmpty(), isEnumerate(), isEnumValue(), isId(), ClassDef::isObjectiveC(), isSliceLocal(), reg::isspace(), isStatic(), QCString::left(), QCString::length(), m_impl, reg::match(), QCString::mid(), DefinitionMixin< MemberDefMutable >::name(), QCString::prepend(), reAnonymous, reg::search(), QCString::str(), string, substitute(), and TRUE.
displayDefinition() [2/2]
virtual QCString MemberDefImpl::displayDefinition () const [virtual]
Implements MemberDef.
displayName() [1/2]
QCString MemberDefImpl::displayName (bool includeScope = TRUE) const [virtual]
Returns the name of the definition as it appears in the output
Implements MemberDef.
Definition at line 5798 of file memberdef.cpp.
{
  return DefinitionMixin::name();
}
References DefinitionMixin< Base >::name().
Referenced by addListReference().
displayName() [2/2]
virtual QCString MemberDefImpl::displayName (bool includeScope = TRUE) const [virtual]
Returns the name of the definition as it appears in the output
Implements MemberDef.
documentation() [1/2]
QCString MemberDefImpl::documentation () const [virtual]
Returns the detailed description of this definition
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 5984 of file memberdef.cpp.
{
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->documentation();
  }
  else
  {
    return DefinitionMixin::documentation();
  }
}
References DefinitionMixin< Base >::documentation(), MemberDef::documentation(), m_impl, and MemberDefImpl::IMPL::templateMaster.
Referenced by findSectionsInDocumentation(), hasDetailedDescription(), isBriefSectionVisible(), writeDocumentation(), and writeMemberDocSimple().
documentation() [2/2]
virtual QCString MemberDefImpl::documentation () const [virtual]
Returns the detailed description of this definition
Reimplemented from DefinitionMixin< MemberDefMutable >.
enableCallerGraph() [1/2]
void MemberDefImpl::enableCallerGraph (bool e) [virtual]
Implements MemberDefMutable.
Definition at line 4666 of file memberdef.cpp.
{
  m_impl->hasCallerGraph=e;
  if (e) Doxygen::parseSourcesNeeded = TRUE;
}
References e, MemberDefImpl::IMPL::hasCallerGraph, m_impl, Doxygen::parseSourcesNeeded, and TRUE.
enableCallerGraph() [2/2]
virtual void MemberDefImpl::enableCallerGraph (bool e) [virtual]
Implements MemberDefMutable.
enableCallGraph() [1/2]
void MemberDefImpl::enableCallGraph (bool e) [virtual]
Implements MemberDefMutable.
Definition at line 4660 of file memberdef.cpp.
{
  m_impl->hasCallGraph=e;
  if (e) Doxygen::parseSourcesNeeded = TRUE;
}
References e, MemberDefImpl::IMPL::hasCallGraph, m_impl, Doxygen::parseSourcesNeeded, and TRUE.
enableCallGraph() [2/2]
virtual void MemberDefImpl::enableCallGraph (bool e) [virtual]
Implements MemberDefMutable.
enableReferencedByRelation() [1/2]
void MemberDefImpl::enableReferencedByRelation (bool e) [virtual]
Implements MemberDefMutable.
Definition at line 4672 of file memberdef.cpp.
{
  m_impl->hasReferencedByRelation=e;
  if (e) Doxygen::parseSourcesNeeded = TRUE;
}
References e, MemberDefImpl::IMPL::hasReferencedByRelation, m_impl, Doxygen::parseSourcesNeeded, and TRUE.
enableReferencedByRelation() [2/2]
virtual void MemberDefImpl::enableReferencedByRelation (bool e) [virtual]
Implements MemberDefMutable.
enableReferencesRelation() [1/2]
void MemberDefImpl::enableReferencesRelation (bool e) [virtual]
Implements MemberDefMutable.
Definition at line 4678 of file memberdef.cpp.
{
  m_impl->hasReferencesRelation=e;
  if (e) Doxygen::parseSourcesNeeded = TRUE;
}
References e, MemberDefImpl::IMPL::hasReferencesRelation, m_impl, Doxygen::parseSourcesNeeded, and TRUE.
enableReferencesRelation() [2/2]
virtual void MemberDefImpl::enableReferencesRelation (bool e) [virtual]
Implements MemberDefMutable.
enumBaseType() [1/2]
QCString MemberDefImpl::enumBaseType () const [virtual]
Implements MemberDef.
Definition at line 5712 of file memberdef.cpp.
{
  return m_impl->enumBaseType;
}
References MemberDefImpl::IMPL::enumBaseType, and m_impl.
enumBaseType() [2/2]
virtual QCString MemberDefImpl::enumBaseType () const [virtual]
Implements MemberDef.
enumFieldList() [1/2]
const MemberVector & MemberDefImpl::enumFieldList () const [virtual]
Implements MemberDef.
Definition at line 5267 of file memberdef.cpp.
{
  return m_impl->enumFields;
}
References MemberDefImpl::IMPL::enumFields, and m_impl.
Referenced by _writeEnumValues().
enumFieldList() [2/2]
virtual const MemberVector & MemberDefImpl::enumFieldList () const [virtual]
Implements MemberDef.
excpString() [1/2]
QCString MemberDefImpl::excpString () const [virtual]
Implements MemberDef.
Definition at line 4800 of file memberdef.cpp.
{
  return m_impl->exception;
}
References MemberDefImpl::IMPL::exception, and m_impl.
Referenced by writeDeclaration(), and writeDocumentation().
excpString() [2/2]
virtual QCString MemberDefImpl::excpString () const [virtual]
Implements MemberDef.
extraTypeChars() [1/2]
QCString MemberDefImpl::extraTypeChars () const [virtual]
Implements MemberDef.
Definition at line 4785 of file memberdef.cpp.
{
  return m_impl->extraTypeChars;
}
References MemberDefImpl::IMPL::extraTypeChars, and m_impl.
Referenced by MemberDefImpl::IMPL::init().
extraTypeChars() [2/2]
virtual QCString MemberDefImpl::extraTypeChars () const [virtual]
Implements MemberDef.
fieldType() [1/2]
QCString MemberDefImpl::fieldType () const [virtual]
Implements MemberDef.
Definition at line 3727 of file memberdef.cpp.
{
  QCString type = m_impl->accessorType;
  if (type.isEmpty())
  {
    type = m_impl->type;
  }
  if (isTypedef() && getLanguage() != SrcLangExt_Slice) type.prepend("typedef ");
  return simplifyTypeForTable(type);
}
References MemberDefImpl::IMPL::accessorType, DefinitionMixin< MemberDefMutable >::getLanguage(), QCString::isEmpty(), isTypedef(), m_impl, QCString::prepend(), simplifyTypeForTable(), SrcLangExt_Slice, and MemberDefImpl::IMPL::type.
Referenced by writeMemberDocSimple().
fieldType() [2/2]
virtual QCString MemberDefImpl::fieldType () const [virtual]
Implements MemberDef.
findSectionsInDocumentation() [1/2]
void MemberDefImpl::findSectionsInDocumentation () [virtual]
Implements MemberDefMutable.
Definition at line 4654 of file memberdef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
}
References briefDescription(), DefinitionMixin< MemberDefMutable >::docFile(), docFindSections(), and documentation().
findSectionsInDocumentation() [2/2]
virtual void MemberDefImpl::findSectionsInDocumentation () [virtual]
Implements MemberDefMutable.
fromAnonymousMember() [1/2]
MemberDef * MemberDefImpl::fromAnonymousMember () const [virtual]
Implements MemberDef.
Definition at line 5651 of file memberdef.cpp.
{
  return m_impl->annMemb;
}
References MemberDefImpl::IMPL::annMemb, and m_impl.
fromAnonymousMember() [2/2]
virtual MemberDef * MemberDefImpl::fromAnonymousMember () const [virtual]
Implements MemberDef.
fromAnonymousScope() [1/2]
bool MemberDefImpl::fromAnonymousScope () const [virtual]
Implements MemberDef.
Definition at line 5365 of file memberdef.cpp.
{
  return m_impl->annScope;
}
References MemberDefImpl::IMPL::annScope, and m_impl.
fromAnonymousScope() [2/2]
virtual bool MemberDefImpl::fromAnonymousScope () const [virtual]
Implements MemberDef.
getAnonymousEnumType() [1/2]
const MemberDef * MemberDefImpl::getAnonymousEnumType () const [virtual]
Implements MemberDef.
Definition at line 5237 of file memberdef.cpp.
{
  return m_impl->annEnumType;
}
References MemberDefImpl::IMPL::annEnumType, and m_impl.
Referenced by writeDeclaration().
getAnonymousEnumType() [2/2]
virtual const MemberDef * MemberDefImpl::getAnonymousEnumType () const [virtual]
Implements MemberDef.
getCachedResolvedTypedef() [1/2]
QCString MemberDefImpl::getCachedResolvedTypedef () const [virtual]
Implements MemberDef.
Definition at line 5446 of file memberdef.cpp.
{
  //printf("MemberDefImpl::getCachedResolvedTypedef()=%s m_impl=%p\n",qPrint(m_impl->cachedResolvedType),m_impl);
  return m_impl->cachedResolvedType;
}
References MemberDefImpl::IMPL::cachedResolvedType, and m_impl.
getCachedResolvedTypedef() [2/2]
virtual QCString MemberDefImpl::getCachedResolvedTypedef () const [virtual]
Implements MemberDef.
getCachedTypedefTemplSpec() [1/2]
QCString MemberDefImpl::getCachedTypedefTemplSpec () const [virtual]
Implements MemberDef.
Definition at line 5441 of file memberdef.cpp.
{
  return m_impl->cachedTypedefTemplSpec;
}
References MemberDefImpl::IMPL::cachedTypedefTemplSpec, and m_impl.
getCachedTypedefTemplSpec() [2/2]
virtual QCString MemberDefImpl::getCachedTypedefTemplSpec () const [virtual]
Implements MemberDef.
getCachedTypedefVal() [1/2]
const ClassDef * MemberDefImpl::getCachedTypedefVal () const [virtual]
Implements MemberDef.
Definition at line 5436 of file memberdef.cpp.
{
  return m_impl->cachedTypedefValue;
}
References MemberDefImpl::IMPL::cachedTypedefValue, and m_impl.
getCachedTypedefVal() [2/2]
virtual const ClassDef * MemberDefImpl::getCachedTypedefVal () const [virtual]
Implements MemberDef.
getClassDef() [1/2]
const ClassDef * MemberDefImpl::getClassDef () const [virtual]
Implements MemberDef.
Definition at line 4825 of file memberdef.cpp.
{
  return m_impl->classDef;
}
References MemberDefImpl::IMPL::classDef, and m_impl.
Referenced by _computeIsConstructor(), _computeLinkableInProject(), _writeCategoryRelation(), _writeReimplementedBy(), displayDefinition(), getClassDefOfAnonymousType(), getLabels(), getOutputFileBase(), getReference(), getScopeString(), hasDetailedDescription(), isBriefSectionVisible(), isCSharpProperty(), isDetailedSectionVisible(), isObjCMethod(), isObjCProperty(), objCMethodName(), qualifiedName(), warnIfUndocumented(), writeDeclaration(), writeDocumentation(), and writeLink().
getClassDef() [2/2]
virtual const ClassDef * MemberDefImpl::getClassDef () const [virtual]
Implements MemberDef.
getClassDefOfAnonymousType() [1/2]
ClassDef * MemberDefImpl::getClassDefOfAnonymousType () const [virtual]
If this member has an anonymous class/struct/union as its type, then this method will return the ClassDef that describes this return type.
Implements MemberDef.
Definition at line 1827 of file memberdef.cpp.
{
  std::lock_guard<std::mutex> lock(g_cachedAnonymousTypeMutex);
  //printf("%s:getClassDefOfAnonymousType() cache=%s\n",qPrint(name()),
  // m_impl->cachedAnonymousType?qPrint(m_impl->cachedAnonymousType->name()):"<empty>");
  if (m_impl->cachedAnonymousType) return m_impl->cachedAnonymousType;
  QCString cname;
  if (getClassDef()!=0)
  {
    cname=getClassDef()->name();
  }
  else if (getNamespaceDef()!=0)
  {
    cname=getNamespaceDef()->name();
  }
  QCString ltype(m_impl->type);
  // strip 'friend' keyword from ltype
  ltype.stripPrefix("friend ");
  // search for the last anonymous scope in the member type
  ClassDef *annoClassDef=0;
  // match expression if it contains at least one @1 marker, e.g.
  // 'struct A::@1::@2::B' matches 'A::@1::@2::B' but 'struct A::B' does not match.
  std::string stype = ltype.str();
  static const reg::Ex r(R"([\w@:]*@\d+[\w@:]*)");
  reg::Match match;
  if (reg::search(stype,match,r)) // found anonymous scope in type
  {
    QCString annName = match.str();
    // if inside a class or namespace try to prepend the scope name
    if (!cname.isEmpty() && annName.left(cname.length()+2)!=cname+"::")
    {
      QCString ts=stripAnonymousNamespaceScope(cname+"::"+annName);
      annoClassDef=getClass(ts);
    }
    // if not found yet, try without scope name
    if (annoClassDef==0)
    {
      QCString ts=stripAnonymousNamespaceScope(annName);
      annoClassDef=getClass(ts);
    }
  }
  m_impl->cachedAnonymousType = annoClassDef;
  return annoClassDef;
}
References MemberDefImpl::IMPL::cachedAnonymousType, g_cachedAnonymousTypeMutex, getClass(), getClassDef(), getNamespaceDef(), QCString::isEmpty(), QCString::left(), QCString::length(), m_impl, reg::match(), Definition::name(), r, reg::search(), QCString::str(), string, stripAnonymousNamespaceScope(), QCString::stripPrefix(), and MemberDefImpl::IMPL::type.
Referenced by writeDeclaration().
getClassDefOfAnonymousType() [2/2]
virtual ClassDef * MemberDefImpl::getClassDefOfAnonymousType () const [virtual]
Implements MemberDef.
getDeclColumn() [1/2]
int MemberDefImpl::getDeclColumn () const [virtual]
Implements MemberDef.
Definition at line 5482 of file memberdef.cpp.
{
  return m_impl->declColumn;
}
References MemberDefImpl::IMPL::declColumn, and m_impl.
getDeclColumn() [2/2]
virtual int MemberDefImpl::getDeclColumn () const [virtual]
Implements MemberDef.
getDeclFileName() [1/2]
QCString MemberDefImpl::getDeclFileName () const [virtual]
Implements MemberDef.
Definition at line 5472 of file memberdef.cpp.
{
  return m_impl->declFileName;
}
References MemberDefImpl::IMPL::declFileName, and m_impl.
getDeclFileName() [2/2]
virtual QCString MemberDefImpl::getDeclFileName () const [virtual]
Implements MemberDef.
getDeclLine() [1/2]
int MemberDefImpl::getDeclLine () const [virtual]
Implements MemberDef.
Definition at line 5477 of file memberdef.cpp.
{
  return m_impl->declLine;
}
References MemberDefImpl::IMPL::declLine, and m_impl.
getDeclLine() [2/2]
virtual int MemberDefImpl::getDeclLine () const [virtual]
Implements MemberDef.
getDeclType() [1/2]
QCString MemberDefImpl::getDeclType () const [virtual]
Implements MemberDef.
Definition at line 1981 of file memberdef.cpp.
{
  SrcLangExt lang = getLanguage();
  QCString ltype(m_impl->type);
  if (lang==SrcLangExt_Cpp && isEnumerate() && isStrong())
  {
    if (isEnumStruct())
    {
      ltype+=" struct";
    }
    else
    {
      ltype+=" class";
    }
  }
  if (isTypedef() && getLanguage() != SrcLangExt_Slice)
  {
    ltype.prepend("typedef ");
  }
  if (isTypeAlias())
  {
    ltype="using";
  }
  // strip 'friend' keyword from ltype
  ltype.stripPrefix("friend ");
  if (ltype=="@") // rename type from enum values
  {
    ltype="";
  }
  else
  {
    if (isObjCMethod())
    {
      ltype.prepend("(");
      ltype.append(")");
    }
  }
  return ltype;
}
References QCString::append(), DefinitionMixin< MemberDefMutable >::getLanguage(), isEnumerate(), isEnumStruct(), isObjCMethod(), isStrong(), isTypeAlias(), isTypedef(), m_impl, QCString::prepend(), SrcLangExt_Cpp, SrcLangExt_Slice, QCString::stripPrefix(), and MemberDefImpl::IMPL::type.
getDeclType() [2/2]
virtual QCString MemberDefImpl::getDeclType () const [virtual]
Implements MemberDef.
getEnumScope() [1/2]
const MemberDef * MemberDefImpl::getEnumScope () const [virtual]
Implements MemberDef.
Definition at line 5247 of file memberdef.cpp.
{
  return m_impl->enumScope;
}
References MemberDefImpl::IMPL::enumScope, and m_impl.
Referenced by getOutputFileBase(), and writeLink().
getEnumScope() [2/2]
virtual const MemberDef * MemberDefImpl::getEnumScope () const [virtual]
Implements MemberDef.
getExamples() [1/2]
const ExampleList & MemberDefImpl::getExamples () const [virtual]
Implements MemberDef.
Definition at line 5272 of file memberdef.cpp.
{
  return m_impl->examples;
}
References MemberDefImpl::IMPL::examples, and m_impl.
getExamples() [2/2]
virtual const ExampleList & MemberDefImpl::getExamples () const [virtual]
Implements MemberDef.
getFileDef() [1/2]
const FileDef * MemberDefImpl::getFileDef () const [virtual]
Implements MemberDef.
Definition at line 4830 of file memberdef.cpp.
{
  return m_impl->fileDef;
}
References MemberDefImpl::IMPL::fileDef, and m_impl.
Referenced by _computeLinkableInProject(), _writeGroupInclude(), _writeMultiLineInitializer(), _writeTemplatePrefix(), getOutputFileBase(), getReference(), warnIfUndocumented(), writeDeclaration(), and writeDocumentation().
getFileDef() [2/2]
virtual const FileDef * MemberDefImpl::getFileDef () const [virtual]
Implements MemberDef.
getGroupAlias() [1/2]
const MemberDef * MemberDefImpl::getGroupAlias () const [virtual]
Implements MemberDef.
Definition at line 5467 of file memberdef.cpp.
{
  return m_impl->groupAlias;
}
References MemberDefImpl::IMPL::groupAlias, and m_impl.
getGroupAlias() [2/2]
virtual const MemberDef * MemberDefImpl::getGroupAlias () const [virtual]
Implements MemberDef.
getGroupDef() [1/2]
const GroupDef * MemberDefImpl::getGroupDef () const [virtual]
Implements MemberDef.
Definition at line 4850 of file memberdef.cpp.
{
  return m_impl->group;
}
References MemberDefImpl::IMPL::group, and m_impl.
Referenced by _computeLinkableInProject(), anchor(), getOutputFileBase(), getReference(), isDetailedSectionVisible(), warnIfUndocumented(), writeDeclaration(), writeDocumentation(), and writeLink().
getGroupDef() [2/2]
virtual const GroupDef * MemberDefImpl::getGroupDef () const [virtual]
Implements MemberDef.
getGroupFileName() [1/2]
QCString MemberDefImpl::getGroupFileName () const [virtual]
Implements MemberDef.
Definition at line 4860 of file memberdef.cpp.
{
  return m_impl->groupFileName;
}
References MemberDefImpl::IMPL::groupFileName, and m_impl.
getGroupFileName() [2/2]
virtual QCString MemberDefImpl::getGroupFileName () const [virtual]
Implements MemberDef.
getGroupHasDocs() [1/2]
bool MemberDefImpl::getGroupHasDocs () const [virtual]
Implements MemberDef.
Definition at line 4870 of file memberdef.cpp.
{
  return m_impl->groupHasDocs;
}
References MemberDefImpl::IMPL::groupHasDocs, and m_impl.
getGroupHasDocs() [2/2]
virtual bool MemberDefImpl::getGroupHasDocs () const [virtual]
Implements MemberDef.
getGroupPri() [1/2]
Grouping::GroupPri_t MemberDefImpl::getGroupPri () const [virtual]
Implements MemberDef.
Definition at line 4855 of file memberdef.cpp.
{
  return m_impl->grouppri;
}
References MemberDefImpl::IMPL::grouppri, and m_impl.
getGroupPri() [2/2]
virtual Grouping::GroupPri_t MemberDefImpl::getGroupPri () const [virtual]
Implements MemberDef.
getGroupStartLine() [1/2]
int MemberDefImpl::getGroupStartLine () const [virtual]
Implements MemberDef.
Definition at line 4865 of file memberdef.cpp.
{
  return m_impl->groupStartLine;
}
References MemberDefImpl::IMPL::groupStartLine, and m_impl.
getGroupStartLine() [2/2]
virtual int MemberDefImpl::getGroupStartLine () const [virtual]
Implements MemberDef.
getLabels() [1/2]
StringVector MemberDefImpl::getLabels (const Definition * container) const [virtual]
Implements MemberDef.
Definition at line 2627 of file memberdef.cpp.
{
  StringVector sl;
  bool inlineInfo = Config_getBool(INLINE_INFO);
  Specifier lvirt=virtualness();
  if ((!isObjCMethod() || isOptional() || isRequired()) &&
      (protection()!=Public || lvirt!=Normal ||
       isFriend() || isRelated() ||
       (isInline() && inlineInfo) ||
       isSignal() || isSlot() ||
       isStatic() || isExternal() ||
       (getClassDef() && getClassDef()!=container && container->definitionType()==TypeClass) ||
       (m_impl->memSpec & ~Entry::Inline)!=0
      )
     )
  {
    // write the member specifier list
    //ol.writeLatexSpacing();
    //ol.startTypewriter();
    //ol.docify(" [");
    SrcLangExt lang = getLanguage();
    bool optVhdl = lang==SrcLangExt_VHDL;
    bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
    if (optVhdl)
    {
      sl.push_back(theTranslator->trVhdlType(getMemberSpecifiers(),TRUE).str());
    }
    else
    {
      if (isFriend()) sl.push_back("friend");
      else if (isRelated()) sl.push_back("related");
      else
      {
        if (isExternal()) sl.push_back("extern");
        if (inlineInfo && isInline()) sl.push_back("inline");
        if (isExplicit()) sl.push_back("explicit");
        if (isMutable()) sl.push_back("mutable");
        if (isStatic()) sl.push_back("static");
        if (isGettable()) sl.push_back("get");
        if (isProtectedGettable()) sl.push_back("protected get");
        if (isSettable()) sl.push_back("set");
        if (isProtectedSettable()) sl.push_back("protected set");
        if (extractPrivate)
        {
          if (isPrivateGettable()) sl.push_back("private get");
          if (isPrivateSettable()) sl.push_back("private set");
        }
        if (isConstExpr()) sl.push_back("constexpr");
        if (isAddable()) sl.push_back("add");
        if (!isUNOProperty() && isRemovable()) sl.push_back("remove");
        if (isRaisable()) sl.push_back("raise");
        if (isReadable()) sl.push_back("read");
        if (isWritable()) sl.push_back("write");
        if (isFinal()) sl.push_back("final");
        if (isAbstract()) sl.push_back("abstract");
        if (isOverride()) sl.push_back("override");
        if (isInitonly()) sl.push_back("initonly");
        if (isSealed()) sl.push_back("sealed");
        if (isNew()) sl.push_back("new");
        if (isOptional()) sl.push_back("optional");
        if (isRequired()) sl.push_back("required");
        if (isNonAtomic()) sl.push_back("nonatomic");
        else if (isObjCProperty()) sl.push_back("atomic");
        // mutual exclusive Objective 2.0 property attributes
        if (isAssign()) sl.push_back("assign");
        else if (isCopy()) sl.push_back("copy");
        else if (isRetain()) sl.push_back("retain");
        else if (isWeak()) sl.push_back("weak");
        else if (lang!=SrcLangExt_CSharp && isStrong()) sl.push_back("strong");
        else if (isUnretained()) sl.push_back("unsafe_unretained");
        if (!isObjCMethod())
        {
          if (protection()==Protected) sl.push_back("protected");
          else if (protection()==Private) sl.push_back("private");
          else if (protection()==Package) sl.push_back("package");
          if (lvirt==Virtual) sl.push_back("virtual");
          else if (lvirt==Pure) sl.push_back("pure virtual");
          if (isSignal()) sl.push_back("signal");
          if (isSlot()) sl.push_back("slot");
          if (isDefault()) sl.push_back("default");
          if (isDelete()) sl.push_back("delete");
          if (isNoExcept()) sl.push_back("noexcept");
          if (isAttribute()) sl.push_back("attribute");
          if (isUNOProperty()) sl.push_back("property");
          if (isReadonly()) sl.push_back("readonly");
          if (isBound()) sl.push_back("bound");
          if (isUNOProperty() && isRemovable()) sl.push_back("removable");
          if (isConstrained()) sl.push_back("constrained");
          if (isTransient()) sl.push_back("transient");
          if (isMaybeVoid()) sl.push_back("maybevoid");
          if (isMaybeDefault()) sl.push_back("maybedefault");
          if (isMaybeAmbiguous()) sl.push_back("maybeambiguous");
          if (isPublished()) sl.push_back("published"); // enum
        }
        if (isObjCProperty() && isImplementation())
        {
          sl.push_back("implementation");
        }
      }
      if (getClassDef() &&
          container->definitionType()==TypeClass &&
          getClassDef()!=container &&
          !isRelated()
         )
      {
        sl.push_back("inherited");
      }
    }
  }
  else if (isObjCMethod() && isImplementation())
  {
    sl.push_back("implementation");
  }
  return sl;
}
References Config_getBool, Definition::definitionType(), getClassDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), getMemberSpecifiers(), Entry::Inline, isAbstract(), isAddable(), isAssign(), isAttribute(), isBound(), isConstExpr(), isConstrained(), isCopy(), isDefault(), isDelete(), isExplicit(), isExternal(), isFinal(), isFriend(), isGettable(), isImplementation(), isInitonly(), isInline(), isMaybeAmbiguous(), isMaybeDefault(), isMaybeVoid(), isMutable(), isNew(), isNoExcept(), isNonAtomic(), isObjCMethod(), isObjCProperty(), isOptional(), isOverride(), isPrivateGettable(), isPrivateSettable(), isProtectedGettable(), isProtectedSettable(), isPublished(), isRaisable(), isReadable(), isReadonly(), isRelated(), isRemovable(), isRequired(), isRetain(), isSealed(), isSettable(), isSignal(), isSlot(), isStatic(), isStrong(), isTransient(), isUNOProperty(), isUnretained(), isWeak(), isWritable(), m_impl, MemberDefImpl::IMPL::memSpec, Normal, Package, Private, Protected, protection(), Public, Pure, caseconvert::sl, SrcLangExt_CSharp, SrcLangExt_VHDL, theTranslator, TRUE, Translator::trVhdlType(), Definition::TypeClass, Virtual, and virtualness().
Referenced by writeDocumentation().
getLabels() [2/2]
virtual StringVector MemberDefImpl::getLabels (const Definition * container) const [virtual]
Implements MemberDef.
getMemberGroup() [1/2]
MemberGroup * MemberDefImpl::getMemberGroup () const [virtual]
Implements MemberDef.
Definition at line 5360 of file memberdef.cpp.
{
  return m_impl->memberGroup;
}
References m_impl, and MemberDefImpl::IMPL::memberGroup.
getMemberGroup() [2/2]
virtual MemberGroup * MemberDefImpl::getMemberGroup () const [virtual]
Implements MemberDef.
getMemberGroupId() [1/2]
int MemberDefImpl::getMemberGroupId () const [virtual]
Implements MemberDef.
Definition at line 5355 of file memberdef.cpp.
{
  return m_impl->grpId;
}
References MemberDefImpl::IMPL::grpId, and m_impl.
getMemberGroupId() [2/2]
virtual int MemberDefImpl::getMemberGroupId () const [virtual]
Implements MemberDef.
getMemberSpecifiers() [1/2]
uint64 MemberDefImpl::getMemberSpecifiers () const [virtual]
Implements MemberDef.
Definition at line 4820 of file memberdef.cpp.
{
  return m_impl->memSpec;
}
References m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
getMemberSpecifiers() [2/2]
virtual uint64 MemberDefImpl::getMemberSpecifiers () const [virtual]
Implements MemberDef.
getNamespaceDef() [1/2]
const NamespaceDef * MemberDefImpl::getNamespaceDef () const [virtual]
Implements MemberDef.
Definition at line 4835 of file memberdef.cpp.
{
  return m_impl->nspace;
}
References m_impl, and MemberDefImpl::IMPL::nspace.
Referenced by _computeLinkableInProject(), getClassDefOfAnonymousType(), getOutputFileBase(), getReference(), getScopeString(), isDetailedSectionVisible(), warnIfUndocumented(), writeDeclaration(), writeDocumentation(), and writeLink().
getNamespaceDef() [2/2]
virtual const NamespaceDef * MemberDefImpl::getNamespaceDef () const [virtual]
Implements MemberDef.
getOutputFileBase() [1/2]
QCString MemberDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements MemberDef.
Definition at line 1517 of file memberdef.cpp.
{
  bool separateMemberPages = Config_getBool(SEPARATE_MEMBER_PAGES);
  bool inlineSimpleClasses = Config_getBool(INLINE_SIMPLE_STRUCTS);
  QCString baseName;
  //printf("Member: %s: templateMaster=%p group=%p classDef=%p nspace=%p fileDef=%p\n",
  // qPrint(name()),m_impl->templateMaster,m_impl->group,m_impl->classDef,
  // m_impl->nspace,m_impl->fileDef);
  const NamespaceDef *nspace = getNamespaceDef();
  const FileDef *fileDef = getFileDef();
  const ClassDef *classDef = getClassDef();
  const GroupDef *groupDef = getGroupDef();
  if (!m_impl->explicitOutputFileBase.isEmpty())
  {
    return m_impl->explicitOutputFileBase;
  }
  else if (templateMaster())
  {
    return templateMaster()->getOutputFileBase();
  }
  else if (groupDef)
  {
    baseName=groupDef->getOutputFileBase();
  }
  else if (classDef)
  {
    baseName=classDef->getOutputFileBase();
    if (inlineSimpleClasses && classDef->isSimple())
    {
      return baseName;
    }
  }
  else if (nspace && (nspace->isLinkable() || nspace->isAnonymous()))
  {
    baseName=nspace->getOutputFileBase();
  }
  else if (fileDef)
  {
    baseName=fileDef->getOutputFileBase();
  }
  if (baseName.isEmpty())
  {
    warn(getDefFileName(),getDefLine(),
       "Internal inconsistency: member %s does not belong to any"
       " container!",qPrint(name())
      );
    return "dummy";
  }
  else if (separateMemberPages && hasDetailedDescription())
  {
    if (getEnumScope()) // enum value, which is part of enum's documentation
    {
      baseName+="_"+getEnumScope()->anchor();
    }
    else
    {
      baseName+="_"+anchor();
    }
  }
  return baseName;
}
References anchor(), MemberDef::anchor(), Config_getBool, MemberDefImpl::IMPL::explicitOutputFileBase, getClassDef(), DefinitionMixin< MemberDefMutable >::getDefFileName(), DefinitionMixin< MemberDefMutable >::getDefLine(), getEnumScope(), getFileDef(), getGroupDef(), getNamespaceDef(), ClassDef::getOutputFileBase(), FileDef::getOutputFileBase(), GroupDef::getOutputFileBase(), MemberDef::getOutputFileBase(), NamespaceDef::getOutputFileBase(), hasDetailedDescription(), Definition::isAnonymous(), QCString::isEmpty(), NamespaceDef::isLinkable(), ClassDef::isSimple(), m_impl, DefinitionMixin< MemberDefMutable >::name(), qPrint(), templateMaster(), and warn().
Referenced by addListReference(), writeDeclaration(), writeDocumentation(), writeLink(), writeMemberDocSimple(), and writeTagFile().
getOutputFileBase() [2/2]
virtual QCString MemberDefImpl::getOutputFileBase () const [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements MemberDef.
getReadAccessor() [1/2]
QCString MemberDefImpl::getReadAccessor () const [virtual]
Implements MemberDef.
Definition at line 4840 of file memberdef.cpp.
{
  return m_impl->read;
}
References m_impl, and MemberDefImpl::IMPL::read.
getReadAccessor() [2/2]
virtual QCString MemberDefImpl::getReadAccessor () const [virtual]
Implements MemberDef.
getReference() [1/2]
QCString MemberDefImpl::getReference () const [virtual]
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 1581 of file memberdef.cpp.
{
  QCString ref = DefinitionMixin::getReference();
  if (!ref.isEmpty())
  {
    return ref;
  }
  const NamespaceDef *nspace = getNamespaceDef();
  const FileDef *fileDef = getFileDef();
  const ClassDef *classDef = getClassDef();
  const GroupDef *groupDef = getGroupDef();
  if (templateMaster())
  {
    return templateMaster()->getReference();
  }
  else if (groupDef)
  {
    return groupDef->getReference();
  }
  else if (classDef)
  {
    return classDef->getReference();
  }
  else if (nspace)
  {
    return nspace->getReference();
  }
  else if (fileDef)
  {
    return fileDef->getReference();
  }
  return "";
}
References getClassDef(), getFileDef(), getGroupDef(), getNamespaceDef(), DefinitionMixin< Base >::getReference(), ClassDef::getReference(), Definition::getReference(), MemberDef::getReference(), QCString::isEmpty(), and templateMaster().
Referenced by anchor(), and writeLink().
getReference() [2/2]
virtual QCString MemberDefImpl::getReference () const [virtual]
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Reimplemented from DefinitionMixin< MemberDefMutable >.
getScopeString() [1/2]
QCString MemberDefImpl::getScopeString () const [virtual]
Implements MemberDef.
Definition at line 4093 of file memberdef.cpp.
{
  QCString result;
  if (getClassDef()) result=getClassDef()->displayName();
  else if (getNamespaceDef()) result=getNamespaceDef()->displayName();
  return result;
}
References ClassDef::displayName(), NamespaceDef::displayName(), getClassDef(), and getNamespaceDef().
getScopeString() [2/2]
virtual QCString MemberDefImpl::getScopeString () const [virtual]
Implements MemberDef.
getSectionList() [1/2]
const MemberList * MemberDefImpl::getSectionList (const Definition * container) const [virtual]
Implements MemberDef.
Definition at line 4304 of file memberdef.cpp.
{
  auto it = m_impl->sectionMap.find(container);
  return it!=m_impl->sectionMap.end() ? it->second : 0;
}
References m_impl, and MemberDefImpl::IMPL::sectionMap.
getSectionList() [2/2]
virtual const MemberList * MemberDefImpl::getSectionList (const Definition *) const [virtual]
Implements MemberDef.
getWriteAccessor() [1/2]
QCString MemberDefImpl::getWriteAccessor () const [virtual]
Implements MemberDef.
Definition at line 4845 of file memberdef.cpp.
{
  return m_impl->write;
}
References m_impl, and MemberDefImpl::IMPL::write.
getWriteAccessor() [2/2]
virtual QCString MemberDefImpl::getWriteAccessor () const [virtual]
Implements MemberDef.
hasCallerGraph() [1/2]
bool MemberDefImpl::hasCallerGraph () const [virtual]
Implements MemberDef.
Definition at line 5398 of file memberdef.cpp.
{
  return m_impl->hasCallerGraph;
}
References MemberDefImpl::IMPL::hasCallerGraph, and m_impl.
Referenced by MemberDefImpl::IMPL::init().
hasCallerGraph() [2/2]
virtual bool MemberDefImpl::hasCallerGraph () const [virtual]
Implements MemberDef.
hasCallGraph() [1/2]
bool MemberDefImpl::hasCallGraph () const [virtual]
Implements MemberDef.
Definition at line 5380 of file memberdef.cpp.
{
  return m_impl->hasCallGraph;
}
References MemberDefImpl::IMPL::hasCallGraph, and m_impl.
Referenced by MemberDefImpl::IMPL::init().
hasCallGraph() [2/2]
virtual bool MemberDefImpl::hasCallGraph () const [virtual]
Implements MemberDef.
hasDetailedDescription() [1/2]
bool MemberDefImpl::hasDetailedDescription () const [virtual]
Implements MemberDef.
Definition at line 2505 of file memberdef.cpp.
{
  //printf(">hasDetailedDescription(cached=%d)\n",m_impl->hasDetailedDescriptionCached);
  if (!m_impl->hasDetailedDescriptionCached)
  {
    bool extractAll = Config_getBool(EXTRACT_ALL);
    bool alwaysDetailedSec = Config_getBool(ALWAYS_DETAILED_SEC);
    bool repeatBrief = Config_getBool(REPEAT_BRIEF);
    bool briefMemberDesc = Config_getBool(BRIEF_MEMBER_DESC);
    bool hideUndocMembers = Config_getBool(HIDE_UNDOC_MEMBERS);
    bool extractStatic = Config_getBool(EXTRACT_STATIC);
    bool extractPrivateVirtual = Config_getBool(EXTRACT_PRIV_VIRTUAL);
    bool inlineSources = Config_getBool(INLINE_SOURCES);
    // the member has detailed documentation because the user added some comments
    bool docFilter =
           // extract all is enabled
           extractAll ||
           // has detailed docs
           !documentation().isEmpty() ||
           // has inbody docs
           !inbodyDocumentation().isEmpty() ||
           // is an enum with values that are documented
           (isEnumerate() && hasDocumentedEnumValues()) ||
           // is documented enum value
           (m_impl->mtype==MemberType_EnumValue && !briefDescription().isEmpty()) ||
           // has brief description that is part of the detailed description
           (!briefDescription().isEmpty() && // has brief docs
            (alwaysDetailedSec && // they are visible in
             (repeatBrief || // detailed section or
              !briefMemberDesc // they are explicitly not
             ) // shown in brief section
            )
           ) ||
           // has one or more documented arguments
           (m_impl->templateMaster ?
            m_impl->templateMaster->argumentList().hasDocumentation() :
            m_impl->defArgList.hasDocumentation());
    // generate function guard
    // ================== =======
    // _writeGroupInclude -> ignored in calculation
    // multiLineInitializer() -> hasMultiLineInitializer()
    // _writeReimplements -> _isReimplements()
    // _writeReimplementedBy -> _countReimplementedBy()>0
    // _writeExamples -> hasExamples()
    // _writeTypeConstraints -> m_impl->typeConstraints.hasParameters()
    // writeSourceDef -> !getSourceFileBase().isEmpty();
    // writeInlineCode -> INLINE_SOURCES && hasSources()
    // writeSourceRefs -> hasReferencesRelation() && hasSourceRefs()
    // writeSourceReffedBy -> hasReferencedByRelation() && hasSourceReffedBy()
    // _writeCallGraph -> _hasVisibleCallGraph()
    // _writeCallerGraph -> _hasVisibleCallerGraph()
    // the member has detailed documentation because there is some generated info
    bool docInfo =
           // has a multi-line initialization block
           (hasMultiLineInitializer()) ||
           // reimplements / reimplemented by
           _isReimplements() || (_countReimplementedBy() > 0) ||
           // examples
           hasExamples() ||
           // type constraints
           m_impl->typeConstraints.hasParameters() ||
           // has source definition
           !getSourceFileBase().isEmpty() ||
           // has inline sources
           (inlineSources && hasSources()) ||
           // has references
           (hasReferencesRelation() && hasSourceRefs()) ||
           (hasReferencedByRelation() && hasSourceReffedBy()) ||
           // call graph
           _hasVisibleCallGraph() ||
           // caller graph
           _hasVisibleCallerGraph();
    if (!hideUndocMembers) // if HIDE_UNDOC_MEMBERS is NO we also show the detailed section
                           // if there is only some generated info
    {
      docFilter = docFilter || docInfo;
    }
    // this is not a global static or global statics should be extracted
    bool staticFilter = getClassDef()!=0 || !isStatic() || extractStatic;
    // only include members that are non-private unless EXTRACT_PRIVATE is
    // set to YES or the member is part of a group
    bool privateFilter = protectionLevelVisible(protection()) || m_impl->mtype==MemberType_Friend ||
                         (m_impl->prot==Private && (m_impl->virt!=Normal || isOverride() || isFinal()) && extractPrivateVirtual);
    // hide friend (class|struct|union) member if HIDE_FRIEND_COMPOUNDS
    // is true
    bool friendCompoundFilter = !(Config_getBool(HIDE_FRIEND_COMPOUNDS) && isFriend());
    m_impl->detailedDescriptionCachedValue =
        (docFilter && staticFilter && privateFilter && friendCompoundFilter && !isHidden());
    //printf("docFilter=%d docInfo=%d staticFilter=%d privateFilter=%d friendCompoundFilter=%d !isHidden()=%d",
    // docFilter,docInfo,staticFilter,privateFilter,friendCompoundFilter,!isHidden());
    m_impl->hasDetailedDescriptionCached = true;
  }
  //printf("<hasDetailedDescription(cached=%d)\n",m_impl->hasDetailedDescriptionCached);
  return m_impl->detailedDescriptionCachedValue;
}
References _countReimplementedBy(), _hasVisibleCallerGraph(), _hasVisibleCallGraph(), _isReimplements(), MemberDef::argumentList(), briefDescription(), Config_getBool, MemberDefImpl::IMPL::defArgList, MemberDefImpl::IMPL::detailedDescriptionCachedValue, documentation(), getClassDef(), DefinitionMixin< MemberDefMutable >::getSourceFileBase(), MemberDefImpl::IMPL::hasDetailedDescriptionCached, ArgumentList::hasDocumentation(), hasDocumentedEnumValues(), hasExamples(), hasMultiLineInitializer(), ArgumentList::hasParameters(), hasReferencedByRelation(), hasReferencesRelation(), DefinitionMixin< MemberDefMutable >::hasSourceReffedBy(), DefinitionMixin< MemberDefMutable >::hasSourceRefs(), DefinitionMixin< MemberDefMutable >::hasSources(), DefinitionMixin< MemberDefMutable >::inbodyDocumentation(), QCString::isEmpty(), isEnumerate(), isFinal(), isFriend(), DefinitionMixin< MemberDefMutable >::isHidden(), isOverride(), isStatic(), m_impl, MemberType_EnumValue, MemberType_Friend, MemberDefImpl::IMPL::mtype, Normal, Private, MemberDefImpl::IMPL::prot, protection(), protectionLevelVisible(), MemberDefImpl::IMPL::templateMaster, MemberDefImpl::IMPL::typeConstraints, and MemberDefImpl::IMPL::virt.
Referenced by getOutputFileBase(), isDetailedSectionVisible(), warnIfUndocumented(), writeDeclaration(), and writeLink().
hasDetailedDescription() [2/2]
virtual bool MemberDefImpl::hasDetailedDescription () const [virtual]
Implements MemberDef.
hasDocumentation() [1/2]
bool MemberDefImpl::hasDocumentation () const [virtual]
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 4080 of file memberdef.cpp.
{
  return DefinitionMixin::hasDocumentation() ||
         (m_impl->mtype==MemberType_Enumeration && m_impl->docEnumValues) || // has enum values
         (m_impl->defArgList.hasDocumentation()); // has doc arguments
}
References MemberDefImpl::IMPL::defArgList, MemberDefImpl::IMPL::docEnumValues, ArgumentList::hasDocumentation(), DefinitionMixin< Base >::hasDocumentation(), m_impl, MemberType_Enumeration, and MemberDefImpl::IMPL::mtype.
Referenced by _computeLinkableInProject(), isBriefSectionVisible(), visibleInIndex(), warnIfUndocumentedParams(), and writeDeclaration().
hasDocumentation() [2/2]
virtual bool MemberDefImpl::hasDocumentation () const [virtual]
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Reimplemented from DefinitionMixin< MemberDefMutable >.
hasDocumentedEnumValues() [1/2]
bool MemberDefImpl::hasDocumentedEnumValues () const [virtual]
Implements MemberDef.
Definition at line 5232 of file memberdef.cpp.
{
  return m_impl->docEnumValues;
}
References MemberDefImpl::IMPL::docEnumValues, and m_impl.
Referenced by hasDetailedDescription(), and writeEnumDeclaration().
hasDocumentedEnumValues() [2/2]
virtual bool MemberDefImpl::hasDocumentedEnumValues () const [virtual]
Implements MemberDef.
hasExamples() [1/2]
bool MemberDefImpl::hasExamples () const [virtual]
Implements MemberDef.
Definition at line 1512 of file memberdef.cpp.
{
  return !m_impl->examples.empty();
}
References MemberDefImpl::IMPL::examples, and m_impl.
Referenced by _writeExamples(), and hasDetailedDescription().
hasExamples() [2/2]
virtual bool MemberDefImpl::hasExamples () const [virtual]
Implements MemberDef.
hasMultiLineInitializer() [1/2]
bool MemberDefImpl::hasMultiLineInitializer () const [virtual]
Implements MemberDef.
Definition at line 4227 of file memberdef.cpp.
{
  //printf("initLines=%d userInitLines=%d maxInitLines=%d\n",
  // initLines,userInitLines,maxInitLines);
  return m_impl->initLines>0 &&
         ((m_impl->initLines<m_impl->maxInitLines && m_impl->userInitLines==-1) // implicitly enabled
          || m_impl->initLines<m_impl->userInitLines // explicitly enabled
         );
}
References MemberDefImpl::IMPL::initLines, m_impl, MemberDefImpl::IMPL::maxInitLines, and MemberDefImpl::IMPL::userInitLines.
Referenced by hasDetailedDescription(), and writeDocumentation().
hasMultiLineInitializer() [2/2]
virtual bool MemberDefImpl::hasMultiLineInitializer () const [virtual]
Implements MemberDef.
hasOneLineInitializer() [1/2]
bool MemberDefImpl::hasOneLineInitializer () const [virtual]
Implements MemberDef.
Definition at line 4218 of file memberdef.cpp.
{
  //printf("%s: init=%s, initLines=%d maxInitLines=%d userInitLines=%d\n",
  // qPrint(name()),qPrint(m_impl->initializer),m_impl->initLines,
  // m_impl->maxInitLines,m_impl->userInitLines);
  return !m_impl->initializer.isEmpty() && m_impl->initLines==0 && // one line initializer
         ((m_impl->maxInitLines>0 && m_impl->userInitLines==-1) || m_impl->userInitLines>0); // enabled by default or explicitly
}
References MemberDefImpl::IMPL::initializer, MemberDefImpl::IMPL::initLines, QCString::isEmpty(), m_impl, MemberDefImpl::IMPL::maxInitLines, and MemberDefImpl::IMPL::userInitLines.
Referenced by writeDeclaration(), writeDocumentation(), and writeMemberDocSimple().
hasOneLineInitializer() [2/2]
virtual bool MemberDefImpl::hasOneLineInitializer () const [virtual]
Implements MemberDef.
hasReferencedByRelation() [1/2]
bool MemberDefImpl::hasReferencedByRelation () const [virtual]
Implements MemberDef.
Definition at line 5416 of file memberdef.cpp.
{
  return m_impl->hasReferencedByRelation;
}
References MemberDefImpl::IMPL::hasReferencedByRelation, and m_impl.
Referenced by hasDetailedDescription(), MemberDefImpl::IMPL::init(), and writeDocumentation().
hasReferencedByRelation() [2/2]
virtual bool MemberDefImpl::hasReferencedByRelation () const [virtual]
Implements MemberDef.
hasReferencesRelation() [1/2]
bool MemberDefImpl::hasReferencesRelation () const [virtual]
Implements MemberDef.
Definition at line 5421 of file memberdef.cpp.
{
  return m_impl->hasReferencesRelation;
}
References MemberDefImpl::IMPL::hasReferencesRelation, and m_impl.
Referenced by hasDetailedDescription(), MemberDefImpl::IMPL::init(), and writeDocumentation().
hasReferencesRelation() [2/2]
virtual bool MemberDefImpl::hasReferencesRelation () const [virtual]
Implements MemberDef.
incrementFlowKeyWordCount() [1/2]
void MemberDefImpl::incrementFlowKeyWordCount () [virtual]
Implements MemberDefMutable.
Definition at line 5786 of file memberdef.cpp.
{
  m_impl->numberOfFlowKW++;
}
References m_impl, and MemberDefImpl::IMPL::numberOfFlowKW.
incrementFlowKeyWordCount() [2/2]
virtual void MemberDefImpl::incrementFlowKeyWordCount () [virtual]
Implements MemberDefMutable.
inheritsDocsFrom() [1/2]
const MemberDef * MemberDefImpl::inheritsDocsFrom () const [virtual]
Implements MemberDef.
Definition at line 5462 of file memberdef.cpp.
{
  return m_impl->docProvider;
}
References MemberDefImpl::IMPL::docProvider, and m_impl.
inheritsDocsFrom() [2/2]
virtual const MemberDef * MemberDefImpl::inheritsDocsFrom () const [virtual]
Implements MemberDef.
initializer() [1/2]
const QCString & MemberDefImpl::initializer () const [virtual]
Implements MemberDef.
Definition at line 4810 of file memberdef.cpp.
{
  return m_impl->initializer;
}
References MemberDefImpl::IMPL::initializer, and m_impl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), doxmlparser.compound.enumvalueType::set_initializer(), and setInitializer().
initializer() [2/2]
virtual const QCString & MemberDefImpl::initializer () const [virtual]
Implements MemberDef.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
initializerLines() [1/2]
int MemberDefImpl::initializerLines () const [virtual]
Implements MemberDef.
Definition at line 4815 of file memberdef.cpp.
{
  return m_impl->initLines;
}
References MemberDefImpl::IMPL::initLines, and m_impl.
initializerLines() [2/2]
virtual int MemberDefImpl::initializerLines () const [virtual]
Implements MemberDef.
insertEnumField() [1/2]
void MemberDefImpl::insertEnumField (const MemberDef * md) [virtual]
Implements MemberDefMutable.
Definition at line 1501 of file memberdef.cpp.
{
  m_impl->enumFields.push_back(md);
}
References MemberDefImpl::IMPL::enumFields, m_impl, and MemberVector::push_back().
insertEnumField() [2/2]
virtual void MemberDefImpl::insertEnumField (const MemberDef * md) [virtual]
Implements MemberDefMutable.
insertReimplementedBy() [1/2]
void MemberDefImpl::insertReimplementedBy (const MemberDef * md) [virtual]
Implements MemberDefMutable.
Definition at line 1456 of file memberdef.cpp.
{
  if (m_impl->templateMaster)
  {
    MemberDefMutable *mdm = toMemberDefMutable(m_impl->templateMaster);
    if (mdm)
    {
      mdm->insertReimplementedBy(md);
    }
  }
  if (!m_impl->redefinedBy.contains(md))
  {
    m_impl->redefinedBy.inSort(md);
  }
}
References MemberVector::contains(), MemberDefMutable::insertReimplementedBy(), MemberVector::inSort(), m_impl, MemberDefImpl::IMPL::redefinedBy, MemberDefImpl::IMPL::templateMaster, and toMemberDefMutable().
insertReimplementedBy() [2/2]
virtual void MemberDefImpl::insertReimplementedBy (const MemberDef * md) [virtual]
Implements MemberDefMutable.
invalidateCachedArgumentTypes() [1/2]
void MemberDefImpl::invalidateCachedArgumentTypes () [virtual]
Implements MemberDefMutable.
Definition at line 5780 of file memberdef.cpp.
{
  invalidateCachedTypesInArgumentList(m_impl->defArgList);
  invalidateCachedTypesInArgumentList(m_impl->declArgList);
}
References MemberDefImpl::IMPL::declArgList, MemberDefImpl::IMPL::defArgList, invalidateCachedTypesInArgumentList(), and m_impl.
invalidateCachedArgumentTypes() [2/2]
virtual void MemberDefImpl::invalidateCachedArgumentTypes () [virtual]
Implements MemberDefMutable.
invalidateTypedefValCache() [1/2]
void MemberDefImpl::invalidateTypedefValCache () [virtual]
Implements MemberDefMutable.
Definition at line 5672 of file memberdef.cpp.
{
  m_impl->isTypedefValCached=FALSE;
}
References FALSE, MemberDefImpl::IMPL::isTypedefValCached, and m_impl.
invalidateTypedefValCache() [2/2]
virtual void MemberDefImpl::invalidateTypedefValCache () [virtual]
Implements MemberDefMutable.
isAbstract() [1/2]
bool MemberDefImpl::isAbstract () const [virtual]
Implements MemberDef.
Definition at line 5070 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Abstract)!=0;
}
References Entry::Abstract, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isAbstract() [2/2]
virtual bool MemberDefImpl::isAbstract () const [virtual]
Implements MemberDef.
isAddable() [1/2]
bool MemberDefImpl::isAddable () const [virtual]
Implements MemberDef.
Definition at line 5020 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Addable)!=0;
}
References Entry::Addable, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels(), and writeDeclaration().
isAddable() [2/2]
virtual bool MemberDefImpl::isAddable () const [virtual]
Implements MemberDef.
isAssign() [1/2]
bool MemberDefImpl::isAssign () const [virtual]
Implements MemberDef.
Definition at line 5095 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Assign)!=0;
}
References Entry::Assign, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isAssign() [2/2]
virtual bool MemberDefImpl::isAssign () const [virtual]
Implements MemberDef.
isAttribute() [1/2]
bool MemberDefImpl::isAttribute () const [virtual]
Implements MemberDef.
Definition at line 5152 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Attribute)!=0;
}
References Entry::Attribute, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isAttribute() [2/2]
virtual bool MemberDefImpl::isAttribute () const [virtual]
Implements MemberDef.
isBound() [1/2]
bool MemberDefImpl::isBound () const [virtual]
Implements MemberDef.
Definition at line 5167 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Bound)!=0;
}
References Entry::Bound, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isBound() [2/2]
virtual bool MemberDefImpl::isBound () const [virtual]
Implements MemberDef.
isBriefSectionVisible() [1/2]
bool MemberDefImpl::isBriefSectionVisible () const [virtual]
This methods returns TRUE iff the brief section (also known as declaration section) is visible in the documentation.
Implements MemberDef.
Definition at line 1879 of file memberdef.cpp.
{
  bool extractStatic = Config_getBool(EXTRACT_STATIC);
  bool extractPrivateVirtual = Config_getBool(EXTRACT_PRIV_VIRTUAL);
  bool hideUndocMembers = Config_getBool(HIDE_UNDOC_MEMBERS);
  bool briefMemberDesc = Config_getBool(BRIEF_MEMBER_DESC);
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  bool hideFriendCompounds = Config_getBool(HIDE_FRIEND_COMPOUNDS);
  //printf("Member %s grpId=%d docs=%s file=%s args=%s\n",
  // qPrint(name()),
  // 0,"", //grpId,grpId==-1?"<none>":Doxygen::memberDocDict[grpId]->data(),
  // "", //qPrint(getFileDef()->name()),
  // argsString());
  auto it = Doxygen::memberGroupInfoMap.find(m_impl->grpId);
  bool hasDocs = hasDocumentation();
  if (it!=Doxygen::memberGroupInfoMap.end())
  {
    auto &info = it->second;
    //printf("name=%s m_impl->grpId=%d info=%p\n",qPrint(name()),m_impl->grpId,info);
    //QCString *pMemGrp = Doxygen::memberDocDict[grpId];
    hasDocs = hasDocs ||
                  // part of a documented member group
                 (m_impl->grpId!=-1 && !(info->doc.isEmpty() && info->header.isEmpty()));
  }
  // only include static members with file/namespace scope if
  // explicitly enabled in the config file
  bool visibleIfStatic = !(getClassDef()==0 &&
                           isStatic() &&
                           !extractStatic
                          );
  // only include members is the are documented or
  // HIDE_UNDOC_MEMBERS is NO in the config file
  bool visibleIfDocumented = (!hideUndocMembers ||
                              hasDocs ||
                              isDocumentedFriendClass()
                             );
  // hide members with no detailed description and brief descriptions
  // explicitly disabled.
  bool visibleIfEnabled = !(hideUndocMembers &&
                            documentation().isEmpty() &&
                            !briefMemberDesc &&
                            !repeatBrief
                           );
  // Hide friend (class|struct|union) declarations if HIDE_FRIEND_COMPOUNDS is true
  bool visibleIfFriendCompound = !(hideFriendCompounds &&
                                   isFriend() /*&&
                                   (m_impl->type=="friend class" ||
                                    m_impl->type=="friend struct" ||
                                    m_impl->type=="friend union"
                                   )*/
                                  );
  // only include members that are non-private unless EXTRACT_PRIVATE is
  // set to YES or the member is part of a group. And as a special case,
  // private *documented* virtual members are shown if EXTRACT_PRIV_VIRTUAL
  // is set to YES
  bool visibleIfPrivate = (protectionLevelVisible(protection()) ||
                           m_impl->mtype==MemberType_Friend ||
                           (m_impl->prot==Private && (m_impl->virt!=Normal || isOverride() || isFinal()) && extractPrivateVirtual && hasDocs)
                          );
  // hide member if it overrides a member in a superclass and has no
  // documentation of its own
  //bool visibleIfDocVirtual = !reimplements() ||
  // !Config_getBool(INHERIT_DOCS) ||
  // hasDocs;
  // true if this member is a constructor or destructor
  bool cOrDTor = isConstructor() || isDestructor();
  // hide default constructors or destructors (no args) without
  // documentation
  bool visibleIfNotDefaultCDTor = !(cOrDTor &&
                                   (m_impl->defArgList.empty() ||
                                    m_impl->defArgList.front().type == "void"
                                   ) &&
                                   !hasDocs
                                  );
  //printf("visibleIfStatic=%d visibleIfDocumented=%d visibleIfEnabled=%d "
  // "visibleIfPrivate=%d visibleIfNotDefaultCDTor=%d "
  // "visibleIfFriendCompound=%d !annScope=%d\n",
  // visibleIfStatic,visibleIfDocumented,
  // visibleIfEnabled,visibleIfPrivate,visibleIfNotDefaultCDTor,
  // visibleIfFriendCompound,!m_impl->annScope);
  bool visible = visibleIfStatic && visibleIfDocumented &&
                 visibleIfEnabled && visibleIfPrivate &&
                 /*visibleIfDocVirtual &&*/ visibleIfNotDefaultCDTor &&
                 visibleIfFriendCompound &&
                 !m_impl->annScope && !isHidden();
  //printf("MemberDefImpl::isBriefSectionVisible() %d\n",visible);
  return visible;
}
References MemberDefImpl::IMPL::annScope, Config_getBool, MemberDefImpl::IMPL::defArgList, documentation(), ArgumentList::empty(), ghc::filesystem::end(), ArgumentList::front(), getClassDef(), MemberDefImpl::IMPL::grpId, hasDocumentation(), isConstructor(), isDestructor(), isDocumentedFriendClass(), QCString::isEmpty(), isFinal(), isFriend(), DefinitionMixin< MemberDefMutable >::isHidden(), isOverride(), isStatic(), m_impl, Doxygen::memberGroupInfoMap, MemberType_Friend, MemberDefImpl::IMPL::mtype, Normal, Private, MemberDefImpl::IMPL::prot, protection(), protectionLevelVisible(), Argument::type, and MemberDefImpl::IMPL::virt.
Referenced by writeEnumDeclaration().
isBriefSectionVisible() [2/2]
virtual bool MemberDefImpl::isBriefSectionVisible () const [virtual]
Implements MemberDef.
isConstExpr() [1/2]
bool MemberDefImpl::isConstExpr () const [virtual]
Implements MemberDef.
Definition at line 5262 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::ConstExpr)!=0;
}
References Entry::ConstExpr, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isConstExpr() [2/2]
virtual bool MemberDefImpl::isConstExpr () const [virtual]
Implements MemberDef.
isConstrained() [1/2]
bool MemberDefImpl::isConstrained () const [virtual]
Implements MemberDef.
Definition at line 5172 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Constrained)!=0;
}
References Entry::Constrained, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isConstrained() [2/2]
virtual bool MemberDefImpl::isConstrained () const [virtual]
Implements MemberDef.
isConstructor() [1/2]
bool MemberDefImpl::isConstructor () const [virtual]
Implements MemberDef.
Definition at line 4449 of file memberdef.cpp.
{
  if (m_isConstructorCached==0)
  {
    MemberDefImpl *that = const_cast<MemberDefImpl*>(this);
    that->_computeIsConstructor();
  }
  ASSERT(m_isConstructorCached>0);
  return m_isConstructorCached==2;
}
References _computeIsConstructor(), ASSERT, and m_isConstructorCached.
Referenced by isBriefSectionVisible(), showInCallGraph(), and warnIfUndocumentedParams().
isConstructor() [2/2]
virtual bool MemberDefImpl::isConstructor () const [virtual]
Implements MemberDef.
isCopy() [1/2]
bool MemberDefImpl::isCopy () const [virtual]
Implements MemberDef.
Definition at line 5090 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Copy)!=0;
}
References Entry::Copy, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isCopy() [2/2]
virtual bool MemberDefImpl::isCopy () const [virtual]
Implements MemberDef.
isCSharpProperty() [1/2]
bool MemberDefImpl::isCSharpProperty () const [virtual]
Implements MemberDef.
Definition at line 4717 of file memberdef.cpp.
{
  if (getClassDef() && getClassDef()->isCSharp() && isProperty()) return TRUE;
  return FALSE;
}
References FALSE, getClassDef(), isProperty(), and TRUE.
isCSharpProperty() [2/2]
virtual bool MemberDefImpl::isCSharpProperty () const [virtual]
Implements MemberDef.
isDCOP() [1/2]
bool MemberDefImpl::isDCOP () const [virtual]
Implements MemberDef.
Definition at line 4945 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_DCOP;
}
References m_impl, MemberType_DCOP, and MemberDefImpl::IMPL::mtype.
isDCOP() [2/2]
virtual bool MemberDefImpl::isDCOP () const [virtual]
Implements MemberDef.
isDefault() [1/2]
bool MemberDefImpl::isDefault () const [virtual]
Implements MemberDef.
Definition at line 5137 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Default)!=0;
}
References Entry::Default, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isDefault() [2/2]
virtual bool MemberDefImpl::isDefault () const [virtual]
Implements MemberDef.
isDefine() [1/2]
bool MemberDefImpl::isDefine () const [virtual]
Implements MemberDef.
Definition at line 4935 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Define;
}
References m_impl, MemberType_Define, and MemberDefImpl::IMPL::mtype.
Referenced by writeDeclaration(), writeDocumentation(), and writeMemberDocSimple().
isDefine() [2/2]
virtual bool MemberDefImpl::isDefine () const [virtual]
Implements MemberDef.
isDelete() [1/2]
bool MemberDefImpl::isDelete () const [virtual]
Implements MemberDef.
Definition at line 5142 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Delete)!=0;
}
References Entry::Delete, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isDelete() [2/2]
virtual bool MemberDefImpl::isDelete () const [virtual]
Implements MemberDef.
isDeleted() [1/2]
bool MemberDefImpl::isDeleted () const [virtual]
Implements MemberDef.
Definition at line 4075 of file memberdef.cpp.
{
  return m_impl->defArgList.isDeleted();
}
References MemberDefImpl::IMPL::defArgList, ArgumentList::isDeleted(), and m_impl.
Referenced by warnIfUndocumented(), and warnIfUndocumentedParams().
isDeleted() [2/2]
virtual bool MemberDefImpl::isDeleted () const [virtual]
Implements MemberDef.
isDestructor() [1/2]
bool MemberDefImpl::isDestructor () const [virtual]
Implements MemberDef.
Definition at line 4486 of file memberdef.cpp.
{
  if (m_isDestructorCached==0)
  {
    MemberDefImpl *that=const_cast<MemberDefImpl*>(this);
    that->_computeIsDestructor();
  }
  ASSERT(m_isDestructorCached>0);
  return m_isDestructorCached==2;
}
References _computeIsDestructor(), ASSERT, and m_isDestructorCached.
Referenced by _computeIsDestructor(), isBriefSectionVisible(), showInCallGraph(), and warnIfUndocumentedParams().
isDestructor() [2/2]
virtual bool MemberDefImpl::isDestructor () const [virtual]
Implements MemberDef.
isDetailedSectionVisible() [1/2]
bool MemberDefImpl::isDetailedSectionVisible (MemberListContainer container) const [virtual]
Implements MemberDef.
Definition at line 2609 of file memberdef.cpp.
{
  bool separateMemPages = Config_getBool(SEPARATE_MEMBER_PAGES);
  bool inlineSimpleStructs = Config_getBool(INLINE_SIMPLE_STRUCTS);
  bool hideUndocMembers = Config_getBool(HIDE_UNDOC_MEMBERS);
  bool groupFilter = getGroupDef()==0 || container==MemberListContainer::Group || separateMemPages;
  bool fileFilter = getNamespaceDef()==0 || !getNamespaceDef()->isLinkable() || container!=MemberListContainer::File;
  bool simpleFilter = (hasBriefDescription() || !hideUndocMembers) && inlineSimpleStructs &&
                      getClassDef()!=0 && getClassDef()->isSimple();
  bool visible = hasDetailedDescription() && groupFilter && fileFilter &&
                 !isReference();
  bool result = visible || simpleFilter;
  //printf("%s::isDetailedSectionVisible: %d groupFilter=%d fileFilter=%d\n",
  // qPrint(name()),result,groupFilter,fileFilter);
  return result;
}
References Config_getBool, File, getClassDef(), getGroupDef(), getNamespaceDef(), Group, DefinitionMixin< MemberDefMutable >::hasBriefDescription(), hasDetailedDescription(), NamespaceDef::isLinkable(), isReference(), and ClassDef::isSimple().
isDetailedSectionVisible() [2/2]
virtual bool MemberDefImpl::isDetailedSectionVisible (MemberListContainer container) const [virtual]
Implements MemberDef.
isDictionary() [1/2]
bool MemberDefImpl::isDictionary () const [virtual]
Implements MemberDef.
Definition at line 4920 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Dictionary;
}
References m_impl, MemberType_Dictionary, and MemberDefImpl::IMPL::mtype.
isDictionary() [2/2]
virtual bool MemberDefImpl::isDictionary () const [virtual]
Implements MemberDef.
isDocsForDefinition() [1/2]
bool MemberDefImpl::isDocsForDefinition () const [virtual]
Implements MemberDef.
Definition at line 5242 of file memberdef.cpp.
{
  return m_impl->docsForDefinition;
}
References MemberDefImpl::IMPL::docsForDefinition, and m_impl.
Referenced by warnIfUndocumentedParams().
isDocsForDefinition() [2/2]
virtual bool MemberDefImpl::isDocsForDefinition () const [virtual]
Implements MemberDef.
isDocumentedFriendClass() [1/2]
bool MemberDefImpl::isDocumentedFriendClass () const [virtual]
Implements MemberDef.
Definition at line 4065 of file memberdef.cpp.
{
  ClassDef *fcd=0;
  QCString baseName=name();
  int i=baseName.find('<');
  if (i!=-1) baseName=baseName.left(i);
  return (isFriendClass() &&
         (fcd=getClass(baseName)) && fcd->isLinkable());
}
References QCString::find(), getClass(), isFriendClass(), ClassDef::isLinkable(), QCString::left(), and DefinitionMixin< MemberDefMutable >::name().
Referenced by isBriefSectionVisible(), and writeDeclaration().
isDocumentedFriendClass() [2/2]
virtual bool MemberDefImpl::isDocumentedFriendClass () const [virtual]
Implements MemberDef.
isEnumerate() [1/2]
bool MemberDefImpl::isEnumerate () const [virtual]
Implements MemberDef.
Definition at line 4900 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Enumeration;
}
References m_impl, MemberType_Enumeration, and MemberDefImpl::IMPL::mtype.
Referenced by _writeEnumValues(), displayDefinition(), getDeclType(), hasDetailedDescription(), and writeDocumentation().
isEnumerate() [2/2]
virtual bool MemberDefImpl::isEnumerate () const [virtual]
Implements MemberDef.
isEnumStruct() [1/2]
bool MemberDefImpl::isEnumStruct () const [virtual]
Implements MemberDef.
Definition at line 5115 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::EnumStruct)!=0;
}
References Entry::EnumStruct, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getDeclType(), and writeDocumentation().
isEnumStruct() [2/2]
virtual bool MemberDefImpl::isEnumStruct () const [virtual]
Implements MemberDef.
isEnumValue() [1/2]
bool MemberDefImpl::isEnumValue () const [virtual]
Implements MemberDef.
Definition at line 4905 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_EnumValue;
}
References m_impl, MemberType_EnumValue, and MemberDefImpl::IMPL::mtype.
Referenced by displayDefinition(), and writeDocumentation().
isEnumValue() [2/2]
virtual bool MemberDefImpl::isEnumValue () const [virtual]
Implements MemberDef.
isEvent() [1/2]
bool MemberDefImpl::isEvent () const [virtual]
Implements MemberDef.
Definition at line 4955 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Event;
}
References m_impl, MemberType_Event, and MemberDefImpl::IMPL::mtype.
Referenced by writeDeclaration().
isEvent() [2/2]
virtual bool MemberDefImpl::isEvent () const [virtual]
Implements MemberDef.
isExplicit() [1/2]
bool MemberDefImpl::isExplicit () const [virtual]
Implements MemberDef.
Definition at line 4980 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Explicit)!=0;
}
References Entry::Explicit, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isExplicit() [2/2]
virtual bool MemberDefImpl::isExplicit () const [virtual]
Implements MemberDef.
isExternal() [1/2]
bool MemberDefImpl::isExternal () const [virtual]
Implements MemberDef.
Definition at line 5208 of file memberdef.cpp.
{
  return m_impl->explExt;
}
References MemberDefImpl::IMPL::explExt, and m_impl.
Referenced by getLabels().
isExternal() [2/2]
virtual bool MemberDefImpl::isExternal () const [virtual]
Implements MemberDef.
isFinal() [1/2]
bool MemberDefImpl::isFinal () const [virtual]
Implements MemberDef.
Definition at line 5045 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Final)!=0;
}
References Entry::Final, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by _computeLinkableInProject(), getLabels(), hasDetailedDescription(), isBriefSectionVisible(), and writeDeclaration().
isFinal() [2/2]
virtual bool MemberDefImpl::isFinal () const [virtual]
Implements MemberDef.
isForeign() [1/2]
bool MemberDefImpl::isForeign () const [virtual]
Implements MemberDef.
Definition at line 4965 of file memberdef.cpp.
{
  return m_impl->related == Foreign;
}
References Foreign, m_impl, and MemberDefImpl::IMPL::related.
Referenced by isRelatedOrFriend().
isForeign() [2/2]
virtual bool MemberDefImpl::isForeign () const [virtual]
Implements MemberDef.
isFriend() [1/2]
bool MemberDefImpl::isFriend () const [virtual]
Implements MemberDef.
Definition at line 4940 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Friend;
}
References m_impl, MemberType_Friend, and MemberDefImpl::IMPL::mtype.
Referenced by getLabels(), hasDetailedDescription(), isBriefSectionVisible(), isFriendClass(), isNotFriend(), and isRelatedOrFriend().
isFriend() [2/2]
virtual bool MemberDefImpl::isFriend () const [virtual]
Implements MemberDef.
isFriendClass() [1/2]
bool MemberDefImpl::isFriendClass () const [virtual]
Implements MemberDef.
Definition at line 6011 of file memberdef.cpp.
{
  return (isFriend() &&
         (m_impl->type=="friend class" || m_impl->type=="friend struct" ||
          m_impl->type=="friend union"));
}
References isFriend(), m_impl, and MemberDefImpl::IMPL::type.
Referenced by isDocumentedFriendClass(), and warnIfUndocumented().
isFriendClass() [2/2]
virtual bool MemberDefImpl::isFriendClass () const [virtual]
Implements MemberDef.
isFriendToHide() [1/2]
bool MemberDefImpl::isFriendToHide () const [virtual]
Implements MemberDef.
Definition at line 6001 of file memberdef.cpp.
{
  bool hideFriendCompounds = Config_getBool(HIDE_FRIEND_COMPOUNDS);
  bool isFriendToHide = hideFriendCompounds &&
     (m_impl->type=="friend class" ||
      m_impl->type=="friend struct" ||
      m_impl->type=="friend union");
  return isFriendToHide;
}
References Config_getBool, isFriendToHide(), m_impl, and MemberDefImpl::IMPL::type.
Referenced by isFriendToHide(), isNotFriend(), and isRelatedOrFriend().
isFriendToHide() [2/2]
virtual bool MemberDefImpl::isFriendToHide () const [virtual]
Implements MemberDef.
isFunction() [1/2]
bool MemberDefImpl::isFunction () const [virtual]
Implements MemberDef.
Definition at line 4925 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Function;
}
References m_impl, MemberType_Function, and MemberDefImpl::IMPL::mtype.
Referenced by _hasVisibleCallerGraph(), _hasVisibleCallGraph(), isFunctionOrSignalSlot(), isObjCMethod(), showInCallGraph(), warnIfUndocumentedParams(), and writeDocumentation().
isFunction() [2/2]
virtual bool MemberDefImpl::isFunction () const [virtual]
Implements MemberDef.
isFunctionOrSignalSlot() [1/2]
bool MemberDefImpl::isFunctionOrSignalSlot () const [virtual]
Implements MemberDef.
Definition at line 6024 of file memberdef.cpp.
{
  return isFunction() || isSlot() || isSignal();
}
References isFunction(), isSignal(), and isSlot().
isFunctionOrSignalSlot() [2/2]
virtual bool MemberDefImpl::isFunctionOrSignalSlot () const [virtual]
Implements MemberDef.
isFunctionPtr() [1/2]
bool MemberDefImpl::isFunctionPtr () const [virtual]
Implements MemberDef.
Definition at line 4930 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Variable && QCString(argsString()).find(")(")!=-1;
}
References argsString(), QCString::find(), m_impl, MemberType_Variable, and MemberDefImpl::IMPL::mtype.
isFunctionPtr() [2/2]
virtual bool MemberDefImpl::isFunctionPtr () const [virtual]
Implements MemberDef.
isGettable() [1/2]
bool MemberDefImpl::isGettable () const [virtual]
Implements MemberDef.
Definition at line 4990 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Gettable)!=0;
}
References Entry::Gettable, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels(), and writeDeclaration().
isGettable() [2/2]
virtual bool MemberDefImpl::isGettable () const [virtual]
Implements MemberDef.
isImplementation() [1/2]
bool MemberDefImpl::isImplementation () const [virtual]
Implements MemberDef.
Definition at line 5203 of file memberdef.cpp.
{
  return m_impl->implOnly;
}
References MemberDefImpl::IMPL::implOnly, and m_impl.
Referenced by getLabels(), and writeDeclaration().
isImplementation() [2/2]
virtual bool MemberDefImpl::isImplementation () const [virtual]
Implements MemberDef.
isInitonly() [1/2]
bool MemberDefImpl::isInitonly () const [virtual]
Implements MemberDef.
Definition at line 5065 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Initonly)!=0;
}
References Entry::Initonly, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isInitonly() [2/2]
virtual bool MemberDefImpl::isInitonly () const [virtual]
Implements MemberDef.
isInline() [1/2]
bool MemberDefImpl::isInline () const [virtual]
Implements MemberDef.
Definition at line 4975 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Inline)!=0;
}
References Entry::Inline, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isInline() [2/2]
virtual bool MemberDefImpl::isInline () const [virtual]
Implements MemberDef.
isLinkable() [1/2]
bool MemberDefImpl::isLinkable () const [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements MemberDef.
Definition at line 1751 of file memberdef.cpp.
{
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->isLinkable();
  }
  else
  {
    return isLinkableInProject() || isReference();
  }
}
References MemberDef::isLinkable(), isLinkableInProject(), isReference(), m_impl, and MemberDefImpl::IMPL::templateMaster.
Referenced by visibleInIndex(), and writeLink().
isLinkable() [2/2]
virtual bool MemberDefImpl::isLinkable () const [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements MemberDef.
isLinkableInProject() [1/2]
bool MemberDefImpl::isLinkableInProject () const [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements MemberDef.
Definition at line 1740 of file memberdef.cpp.
{
  if (m_isLinkableCached==0)
  {
    MemberDefImpl *that = const_cast<MemberDefImpl*>(this);
    that->_computeLinkableInProject();
  }
  ASSERT(m_isLinkableCached>0);
  return m_isLinkableCached==2;
}
References _computeLinkableInProject(), ASSERT, and m_isLinkableCached.
Referenced by addListReference(), isLinkable(), writeEnumDeclaration(), and writeTagFile().
isLinkableInProject() [2/2]
virtual bool MemberDefImpl::isLinkableInProject () const [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements MemberDef.
isMaybeAmbiguous() [1/2]
bool MemberDefImpl::isMaybeAmbiguous () const [virtual]
Implements MemberDef.
Definition at line 5192 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::MaybeAmbiguous)!=0;
}
References m_impl, Entry::MaybeAmbiguous, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isMaybeAmbiguous() [2/2]
virtual bool MemberDefImpl::isMaybeAmbiguous () const [virtual]
Implements MemberDef.
isMaybeDefault() [1/2]
bool MemberDefImpl::isMaybeDefault () const [virtual]
Implements MemberDef.
Definition at line 5187 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::MaybeDefault)!=0;
}
References m_impl, Entry::MaybeDefault, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isMaybeDefault() [2/2]
virtual bool MemberDefImpl::isMaybeDefault () const [virtual]
Implements MemberDef.
isMaybeVoid() [1/2]
bool MemberDefImpl::isMaybeVoid () const [virtual]
Implements MemberDef.
Definition at line 5182 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::MaybeVoid)!=0;
}
References m_impl, Entry::MaybeVoid, and MemberDefImpl::IMPL::memSpec.
Referenced by getLabels().
isMaybeVoid() [2/2]
virtual bool MemberDefImpl::isMaybeVoid () const [virtual]
Implements MemberDef.
isMutable() [1/2]
bool MemberDefImpl::isMutable () const [virtual]
Implements MemberDef.
Definition at line 4985 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Mutable)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Mutable.
Referenced by getLabels().
isMutable() [2/2]
virtual bool MemberDefImpl::isMutable () const [virtual]
Implements MemberDef.
isNew() [1/2]
bool MemberDefImpl::isNew () const [virtual]
Implements MemberDef.
Definition at line 5050 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::New)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::New.
Referenced by getLabels().
isNew() [2/2]
virtual bool MemberDefImpl::isNew () const [virtual]
Implements MemberDef.
isNoExcept() [1/2]
bool MemberDefImpl::isNoExcept () const [virtual]
Implements MemberDef.
Definition at line 5147 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::NoExcept)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::NoExcept.
Referenced by getLabels().
isNoExcept() [2/2]
virtual bool MemberDefImpl::isNoExcept () const [virtual]
Implements MemberDef.
isNonAtomic() [1/2]
bool MemberDefImpl::isNonAtomic () const [virtual]
Implements MemberDef.
Definition at line 5085 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::NonAtomic)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::NonAtomic.
Referenced by getLabels().
isNonAtomic() [2/2]
virtual bool MemberDefImpl::isNonAtomic () const [virtual]
Implements MemberDef.
isNotFriend() [1/2]
bool MemberDefImpl::isNotFriend () const [virtual]
Implements MemberDef.
Definition at line 6019 of file memberdef.cpp.
{
  return !(isFriend() && isFriendToHide());
}
References isFriend(), and isFriendToHide().
isNotFriend() [2/2]
virtual bool MemberDefImpl::isNotFriend () const [virtual]
Implements MemberDef.
isObjCMethod() [1/2]
bool MemberDefImpl::isObjCMethod () const [virtual]
Implements MemberDef.
Definition at line 4705 of file memberdef.cpp.
{
  if (getClassDef() && getClassDef()->isObjectiveC() && isFunction()) return TRUE;
  return FALSE;
}
References FALSE, getClassDef(), isFunction(), and TRUE.
Referenced by addListReference(), getDeclType(), getLabels(), qualifiedName(), showInCallGraph(), writeDeclaration(), writeDocumentation(), writeLink(), and writeMemberDocSimple().
isObjCMethod() [2/2]
virtual bool MemberDefImpl::isObjCMethod () const [virtual]
Implements MemberDef.
isObjCProperty() [1/2]
bool MemberDefImpl::isObjCProperty () const [virtual]
Implements MemberDef.
Definition at line 4711 of file memberdef.cpp.
{
  if (getClassDef() && getClassDef()->isObjectiveC() && isProperty()) return TRUE;
  return FALSE;
}
References FALSE, getClassDef(), isProperty(), and TRUE.
Referenced by getLabels(), and writeDeclaration().
isObjCProperty() [2/2]
virtual bool MemberDefImpl::isObjCProperty () const [virtual]
Implements MemberDef.
isOptional() [1/2]
bool MemberDefImpl::isOptional () const [virtual]
Implements MemberDef.
Definition at line 5075 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Optional)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Optional.
Referenced by getLabels().
isOptional() [2/2]
virtual bool MemberDefImpl::isOptional () const [virtual]
Implements MemberDef.
isOverride() [1/2]
bool MemberDefImpl::isOverride () const [virtual]
Implements MemberDef.
Definition at line 5060 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Override)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Override.
Referenced by _computeLinkableInProject(), getLabels(), hasDetailedDescription(), isBriefSectionVisible(), and writeDeclaration().
isOverride() [2/2]
virtual bool MemberDefImpl::isOverride () const [virtual]
Implements MemberDef.
isPrivateGettable() [1/2]
bool MemberDefImpl::isPrivateGettable () const [virtual]
Implements MemberDef.
Definition at line 4995 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::PrivateGettable)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::PrivateGettable.
Referenced by getLabels(), and writeDeclaration().
isPrivateGettable() [2/2]
virtual bool MemberDefImpl::isPrivateGettable () const [virtual]
Implements MemberDef.
isPrivateSettable() [1/2]
bool MemberDefImpl::isPrivateSettable () const [virtual]
Implements MemberDef.
Definition at line 5010 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::PrivateSettable)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::PrivateSettable.
Referenced by getLabels(), and writeDeclaration().
isPrivateSettable() [2/2]
virtual bool MemberDefImpl::isPrivateSettable () const [virtual]
Implements MemberDef.
isProperty() [1/2]
bool MemberDefImpl::isProperty () const [virtual]
Implements MemberDef.
Definition at line 4950 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Property;
}
References m_impl, MemberType_Property, and MemberDefImpl::IMPL::mtype.
Referenced by isCSharpProperty(), isObjCProperty(), and writeDeclaration().
isProperty() [2/2]
virtual bool MemberDefImpl::isProperty () const [virtual]
Implements MemberDef.
isProtectedGettable() [1/2]
bool MemberDefImpl::isProtectedGettable () const [virtual]
Implements MemberDef.
Definition at line 5000 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::ProtectedGettable)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::ProtectedGettable.
Referenced by getLabels(), and writeDeclaration().
isProtectedGettable() [2/2]
virtual bool MemberDefImpl::isProtectedGettable () const [virtual]
Implements MemberDef.
isProtectedSettable() [1/2]
bool MemberDefImpl::isProtectedSettable () const [virtual]
Implements MemberDef.
Definition at line 5015 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::ProtectedSettable)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::ProtectedSettable.
Referenced by getLabels(), and writeDeclaration().
isProtectedSettable() [2/2]
virtual bool MemberDefImpl::isProtectedSettable () const [virtual]
Implements MemberDef.
isPrototype() [1/2]
bool MemberDefImpl::isPrototype () const [virtual]
Implements MemberDef.
Definition at line 5277 of file memberdef.cpp.
{
  return m_impl->proto;
}
References m_impl, and MemberDefImpl::IMPL::proto.
isPrototype() [2/2]
virtual bool MemberDefImpl::isPrototype () const [virtual]
Implements MemberDef.
isPublished() [1/2]
bool MemberDefImpl::isPublished () const [virtual]
Implements MemberDef.
Definition at line 5197 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Published)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Published.
Referenced by getLabels().
isPublished() [2/2]
virtual bool MemberDefImpl::isPublished () const [virtual]
Implements MemberDef.
isRaisable() [1/2]
bool MemberDefImpl::isRaisable () const [virtual]
Implements MemberDef.
Definition at line 5030 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Raisable)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Raisable.
Referenced by getLabels(), and writeDeclaration().
isRaisable() [2/2]
virtual bool MemberDefImpl::isRaisable () const [virtual]
Implements MemberDef.
isReadable() [1/2]
bool MemberDefImpl::isReadable () const [virtual]
Implements MemberDef.
Definition at line 5035 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Readable)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Readable.
Referenced by getLabels().
isReadable() [2/2]
virtual bool MemberDefImpl::isReadable () const [virtual]
Implements MemberDef.
isReadonly() [1/2]
bool MemberDefImpl::isReadonly () const [virtual]
Implements MemberDef.
Definition at line 5162 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Readonly)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Readonly.
Referenced by getLabels().
isReadonly() [2/2]
virtual bool MemberDefImpl::isReadonly () const [virtual]
Implements MemberDef.
isReference() [1/2]
bool MemberDefImpl::isReference () const [virtual]
Returns TRUE if this definition is imported via a tag file.
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 6034 of file memberdef.cpp.
{
  return DefinitionMixin::isReference() ||
         (m_impl->templateMaster && m_impl->templateMaster->isReference());
}
References DefinitionMixin< Base >::isReference(), MemberDef::isReference(), m_impl, and MemberDefImpl::IMPL::templateMaster.
Referenced by _computeLinkableInProject(), isDetailedSectionVisible(), isLinkable(), warnIfUndocumented(), warnIfUndocumentedParams(), and writeDeclaration().
isReference() [2/2]
virtual bool MemberDefImpl::isReference () const [virtual]
Returns TRUE if this definition is imported via a tag file.
Reimplemented from DefinitionMixin< MemberDefMutable >.
isReimplementedBy() [1/2]
bool MemberDefImpl::isReimplementedBy (const ClassDef * cd) const [virtual]
Implements MemberDef.
Definition at line 1482 of file memberdef.cpp.
{
  if (cd)
  {
    for (const auto &md : m_impl->redefinedBy)
    {
      const ClassDef *mcd = md->getClassDef();
      if (mcd)
      {
        if (cd==mcd || cd->isBaseClass(mcd,TRUE))
        {
          return TRUE;
        }
      }
    }
  }
  return FALSE;
}
References FALSE, ClassDef::isBaseClass(), m_impl, MemberDefImpl::IMPL::redefinedBy, and TRUE.
isReimplementedBy() [2/2]
virtual bool MemberDefImpl::isReimplementedBy (const ClassDef * cd) const [virtual]
Implements MemberDef.
isRelated() [1/2]
bool MemberDefImpl::isRelated () const [virtual]
Implements MemberDef.
Definition at line 4960 of file memberdef.cpp.
{
  return m_impl->related == Related;
}
References m_impl, MemberDefImpl::IMPL::related, and Related.
Referenced by addListReference(), getLabels(), isRelatedOrFriend(), and writeLink().
isRelated() [2/2]
virtual bool MemberDefImpl::isRelated () const [virtual]
Implements MemberDef.
isRelatedOrFriend() [1/2]
bool MemberDefImpl::isRelatedOrFriend () const [virtual]
Implements MemberDef.
Definition at line 6029 of file memberdef.cpp.
{
  return isRelated() || isForeign() || (isFriend() && !isFriendToHide());
}
References isForeign(), isFriend(), isFriendToHide(), and isRelated().
isRelatedOrFriend() [2/2]
virtual bool MemberDefImpl::isRelatedOrFriend () const [virtual]
Implements MemberDef.
isRemovable() [1/2]
bool MemberDefImpl::isRemovable () const [virtual]
Implements MemberDef.
Definition at line 5025 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Removable)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Removable.
Referenced by getLabels(), and writeDeclaration().
isRemovable() [2/2]
virtual bool MemberDefImpl::isRemovable () const [virtual]
Implements MemberDef.
isRequired() [1/2]
bool MemberDefImpl::isRequired () const [virtual]
Implements MemberDef.
Definition at line 5080 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Required)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Required.
Referenced by getLabels().
isRequired() [2/2]
virtual bool MemberDefImpl::isRequired () const [virtual]
Implements MemberDef.
isRetain() [1/2]
bool MemberDefImpl::isRetain () const [virtual]
Implements MemberDef.
Definition at line 5100 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Retain)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Retain.
Referenced by getLabels().
isRetain() [2/2]
virtual bool MemberDefImpl::isRetain () const [virtual]
Implements MemberDef.
isSealed() [1/2]
bool MemberDefImpl::isSealed () const [virtual]
Implements MemberDef.
Definition at line 5055 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Sealed)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Sealed.
Referenced by getLabels().
isSealed() [2/2]
virtual bool MemberDefImpl::isSealed () const [virtual]
Implements MemberDef.
isSequence() [1/2]
bool MemberDefImpl::isSequence () const [virtual]
Implements MemberDef.
Definition at line 4915 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Sequence;
}
References m_impl, MemberType_Sequence, and MemberDefImpl::IMPL::mtype.
isSequence() [2/2]
virtual bool MemberDefImpl::isSequence () const [virtual]
Implements MemberDef.
isSettable() [1/2]
bool MemberDefImpl::isSettable () const [virtual]
Implements MemberDef.
Definition at line 5005 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Settable)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Settable.
Referenced by getLabels(), and writeDeclaration().
isSettable() [2/2]
virtual bool MemberDefImpl::isSettable () const [virtual]
Implements MemberDef.
isSignal() [1/2]
bool MemberDefImpl::isSignal () const [virtual]
Implements MemberDef.
Definition at line 4885 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Signal;
}
References m_impl, MemberType_Signal, and MemberDefImpl::IMPL::mtype.
Referenced by _hasVisibleCallerGraph(), _hasVisibleCallGraph(), getLabels(), and isFunctionOrSignalSlot().
isSignal() [2/2]
virtual bool MemberDefImpl::isSignal () const [virtual]
Implements MemberDef.
isSliceLocal() [1/2]
bool MemberDefImpl::isSliceLocal () const [virtual]
Implements MemberDef.
Definition at line 5257 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Local)!=0;
}
References Entry::Local, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by displayDefinition(), and writeDocumentation().
isSliceLocal() [2/2]
virtual bool MemberDefImpl::isSliceLocal () const [virtual]
Implements MemberDef.
isSlot() [1/2]
bool MemberDefImpl::isSlot () const [virtual]
Implements MemberDef.
Definition at line 4890 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Slot;
}
References m_impl, MemberType_Slot, and MemberDefImpl::IMPL::mtype.
Referenced by _hasVisibleCallerGraph(), _hasVisibleCallGraph(), getLabels(), isFunctionOrSignalSlot(), and showInCallGraph().
isSlot() [2/2]
virtual bool MemberDefImpl::isSlot () const [virtual]
Implements MemberDef.
isStatic() [1/2]
bool MemberDefImpl::isStatic () const [virtual]
Implements MemberDef.
Definition at line 4970 of file memberdef.cpp.
{
  return m_impl->stat;
}
References m_impl, and MemberDefImpl::IMPL::stat.
Referenced by displayDefinition(), getLabels(), hasDetailedDescription(), isBriefSectionVisible(), objCMethodName(), qualifiedName(), visibleInIndex(), writeDeclaration(), writeDocumentation(), writeLink(), and writeTagFile().
isStatic() [2/2]
virtual bool MemberDefImpl::isStatic () const [virtual]
Implements MemberDef.
isStrong() [1/2]
bool MemberDefImpl::isStrong () const [virtual]
Implements MemberDef.
Definition at line 5110 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Strong)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Strong.
Referenced by getDeclType(), getLabels(), writeDocumentation(), and writeTagFile().
isStrong() [2/2]
virtual bool MemberDefImpl::isStrong () const [virtual]
Implements MemberDef.
isStrongEnumValue() [1/2]
bool MemberDefImpl::isStrongEnumValue () const [virtual]
Implements MemberDef.
Definition at line 5120 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_EnumValue &&
         m_impl->enumScope &&
         m_impl->enumScope->isStrong();
}
References MemberDefImpl::IMPL::enumScope, MemberDef::isStrong(), m_impl, MemberType_EnumValue, and MemberDefImpl::IMPL::mtype.
isStrongEnumValue() [2/2]
virtual bool MemberDefImpl::isStrongEnumValue () const [virtual]
Implements MemberDef.
isTemplateSpecialization() [1/2]
bool MemberDefImpl::isTemplateSpecialization () const [virtual]
Implements MemberDef.
Definition at line 5213 of file memberdef.cpp.
{
  return m_impl->tspec;
}
References m_impl, and MemberDefImpl::IMPL::tspec.
Referenced by writeDocumentation().
isTemplateSpecialization() [2/2]
virtual bool MemberDefImpl::isTemplateSpecialization () const [virtual]
Implements MemberDef.
isTransient() [1/2]
bool MemberDefImpl::isTransient () const [virtual]
Implements MemberDef.
Definition at line 5177 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Transient)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Transient.
Referenced by getLabels().
isTransient() [2/2]
virtual bool MemberDefImpl::isTransient () const [virtual]
Implements MemberDef.
isTypeAlias() [1/2]
bool MemberDefImpl::isTypeAlias () const [virtual]
Implements MemberDef.
Definition at line 5132 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Alias)!=0;
}
References Entry::Alias, m_impl, and MemberDefImpl::IMPL::memSpec.
Referenced by getDeclType(), and writeDeclaration().
isTypeAlias() [2/2]
virtual bool MemberDefImpl::isTypeAlias () const [virtual]
Implements MemberDef.
isTypedef() [1/2]
bool MemberDefImpl::isTypedef () const [virtual]
Implements MemberDef.
Definition at line 4910 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Typedef;
}
References m_impl, MemberType_Typedef, and MemberDefImpl::IMPL::mtype.
Referenced by fieldType(), getDeclType(), writeDeclaration(), and writeDocumentation().
isTypedef() [2/2]
virtual bool MemberDefImpl::isTypedef () const [virtual]
Implements MemberDef.
isTypedefValCached() [1/2]
bool MemberDefImpl::isTypedefValCached () const [virtual]
Implements MemberDef.
Definition at line 5431 of file memberdef.cpp.
{
  return m_impl->isTypedefValCached;
}
References MemberDefImpl::IMPL::isTypedefValCached, and m_impl.
Referenced by MemberDefImpl::IMPL::init().
isTypedefValCached() [2/2]
virtual bool MemberDefImpl::isTypedefValCached () const [virtual]
Implements MemberDef.
isUNOProperty() [1/2]
bool MemberDefImpl::isUNOProperty () const [virtual]
Implements MemberDef.
Definition at line 5157 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Property)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Property.
Referenced by getLabels().
isUNOProperty() [2/2]
virtual bool MemberDefImpl::isUNOProperty () const [virtual]
Implements MemberDef.
isUnretained() [1/2]
bool MemberDefImpl::isUnretained () const [virtual]
Implements MemberDef.
Definition at line 5127 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Unretained)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Unretained.
Referenced by getLabels().
isUnretained() [2/2]
virtual bool MemberDefImpl::isUnretained () const [virtual]
Implements MemberDef.
isVariable() [1/2]
bool MemberDefImpl::isVariable () const [virtual]
Implements MemberDef.
Definition at line 4895 of file memberdef.cpp.
{
  return m_impl->mtype==MemberType_Variable;
}
References m_impl, MemberType_Variable, and MemberDefImpl::IMPL::mtype.
Referenced by writeDocumentation(), and writeMemberDocSimple().
isVariable() [2/2]
virtual bool MemberDefImpl::isVariable () const [virtual]
Implements MemberDef.
isWeak() [1/2]
bool MemberDefImpl::isWeak () const [virtual]
Implements MemberDef.
Definition at line 5105 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Weak)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Weak.
Referenced by getLabels().
isWeak() [2/2]
virtual bool MemberDefImpl::isWeak () const [virtual]
Implements MemberDef.
isWritable() [1/2]
bool MemberDefImpl::isWritable () const [virtual]
Implements MemberDef.
Definition at line 5040 of file memberdef.cpp.
{
  return (m_impl->memSpec&Entry::Writable)!=0;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and Entry::Writable.
Referenced by getLabels().
isWritable() [2/2]
virtual bool MemberDefImpl::isWritable () const [virtual]
Implements MemberDef.
livesInsideEnum() [1/2]
bool MemberDefImpl::livesInsideEnum () const [virtual]
Implements MemberDef.
Definition at line 5252 of file memberdef.cpp.
{
  return m_impl->livesInsideEnum;
}
References MemberDefImpl::IMPL::livesInsideEnum, and m_impl.
Referenced by MemberDefImpl::IMPL::init(), and setEnumScope().
livesInsideEnum() [2/2]
virtual bool MemberDefImpl::livesInsideEnum () const [virtual]
Implements MemberDef.
makeForeign() [1/2]
void MemberDefImpl::makeForeign () [virtual]
Implements MemberDefMutable.
Definition at line 5559 of file memberdef.cpp.
{
  m_impl->related = Foreign;
  m_isLinkableCached = 0;
}
References Foreign, m_impl, m_isLinkableCached, and MemberDefImpl::IMPL::related.
makeForeign() [2/2]
virtual void MemberDefImpl::makeForeign () [virtual]
Implements MemberDefMutable.
makeImplementationDetail() [1/2]
void MemberDefImpl::makeImplementationDetail () [virtual]
Implements MemberDefMutable.
Definition at line 5636 of file memberdef.cpp.
{
  m_impl->implOnly=TRUE;
}
References MemberDefImpl::IMPL::implOnly, m_impl, and TRUE.
makeImplementationDetail() [2/2]
virtual void MemberDefImpl::makeImplementationDetail () [virtual]
Implements MemberDefMutable.
makeRelated() [1/2]
void MemberDefImpl::makeRelated () [virtual]
Implements MemberDefMutable.
Definition at line 5553 of file memberdef.cpp.
{
  m_impl->related = Related;
  m_isLinkableCached = 0;
}
References m_impl, m_isLinkableCached, MemberDefImpl::IMPL::related, and Related.
makeRelated() [2/2]
virtual void MemberDefImpl::makeRelated () [virtual]
Implements MemberDefMutable.
memberDeclaration() [1/2]
MemberDef * MemberDefImpl::memberDeclaration () const [virtual]
Implements MemberDef.
Definition at line 5457 of file memberdef.cpp.
{
  return m_impl->memDec;
}
References m_impl, and MemberDefImpl::IMPL::memDec.
memberDeclaration() [2/2]
virtual MemberDef * MemberDefImpl::memberDeclaration () const [virtual]
Implements MemberDef.
memberDefinition() [1/2]
MemberDef * MemberDefImpl::memberDefinition () const [virtual]
Implements MemberDef.
Definition at line 5452 of file memberdef.cpp.
{
  return m_impl->memDef;
}
References m_impl, and MemberDefImpl::IMPL::memDef.
memberDefinition() [2/2]
virtual MemberDef * MemberDefImpl::memberDefinition () const [virtual]
Implements MemberDef.
memberType() [1/2]
MemberType MemberDefImpl::memberType () const [virtual]
Implements MemberDef.
Definition at line 4880 of file memberdef.cpp.
{
  return m_impl->mtype;
}
References m_impl, and MemberDefImpl::IMPL::mtype.
Referenced by codeSymbolType().
memberType() [2/2]
virtual MemberType MemberDefImpl::memberType () const [virtual]
Implements MemberDef.
memberTypeName() [1/2]
QCString MemberDefImpl::memberTypeName () const [virtual]
Implements MemberDef.
Definition at line 3847 of file memberdef.cpp.
{
  switch (m_impl->mtype)
  {
    case MemberType_Define: return "macro definition";
    case MemberType_Function: return "function";
    case MemberType_Variable: return "variable";
    case MemberType_Typedef: return "typedef";
    case MemberType_Enumeration: return "enumeration";
    case MemberType_EnumValue: return "enumvalue";
    case MemberType_Signal: return "signal";
    case MemberType_Slot: return "slot";
    case MemberType_Friend: return "friend";
    case MemberType_DCOP: return "dcop";
    case MemberType_Property: return "property";
    case MemberType_Event: return "event";
    case MemberType_Interface: return "interface";
    case MemberType_Service: return "service";
    case MemberType_Sequence: return "sequence";
    case MemberType_Dictionary: return "dictionary";
    default: return "unknown";
  }
}
References m_impl, MemberType_DCOP, MemberType_Define, MemberType_Dictionary, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Sequence, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, and MemberDefImpl::IMPL::mtype.
Referenced by warnIfUndocumented().
memberTypeName() [2/2]
virtual QCString MemberDefImpl::memberTypeName () const [virtual]
Implements MemberDef.
mergeMemberSpecifiers() [1/2]
void MemberDefImpl::mergeMemberSpecifiers (uint64 s) [virtual]
Implements MemberDefMutable.
Definition at line 5520 of file memberdef.cpp.
{
  m_impl->memSpec|=s;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and s.
mergeMemberSpecifiers() [2/2]
virtual void MemberDefImpl::mergeMemberSpecifiers (uint64 s) [virtual]
Implements MemberDefMutable.
moveArgumentList() [1/2]
void MemberDefImpl::moveArgumentList (std::unique_ptr< ArgumentList > al) [virtual]
Implements MemberDefMutable.
Definition at line 4623 of file memberdef.cpp.
{
  m_impl->defArgList = *al;
}
References MemberDefImpl::IMPL::defArgList, and m_impl.
moveArgumentList() [2/2]
virtual void MemberDefImpl::moveArgumentList (std::unique_ptr< ArgumentList > al) [virtual]
Implements MemberDefMutable.
moveDeclArgumentList() [1/2]
void MemberDefImpl::moveDeclArgumentList (std::unique_ptr< ArgumentList > al) [virtual]
Implements MemberDefMutable.
Definition at line 4628 of file memberdef.cpp.
{
  m_impl->declArgList = *al;
}
References MemberDefImpl::IMPL::declArgList, and m_impl.
moveDeclArgumentList() [2/2]
virtual void MemberDefImpl::moveDeclArgumentList (std::unique_ptr< ArgumentList > al) [virtual]
Implements MemberDefMutable.
moveTo() [1/2]
void MemberDefImpl::moveTo (Definition * scope) [virtual]
Implements MemberDef.
Definition at line 1423 of file memberdef.cpp.
{
   setOuterScope(scope);
   if (scope->definitionType()==Definition::TypeClass)
   {
     m_impl->classDef = toClassDef(scope);
   }
   else if (scope->definitionType()==Definition::TypeFile)
   {
     m_impl->fileDef = toFileDef(scope);
   }
   else if (scope->definitionType()==Definition::TypeNamespace)
   {
     m_impl->nspace = toNamespaceDef(scope);
   }
   m_isLinkableCached = 0;
   m_isConstructorCached = 0;
}
References MemberDefImpl::IMPL::classDef, Definition::definitionType(), MemberDefImpl::IMPL::fileDef, m_impl, m_isConstructorCached, m_isLinkableCached, MemberDefImpl::IMPL::nspace, DefinitionMixin< MemberDefMutable >::setOuterScope(), toClassDef(), toFileDef(), toNamespaceDef(), Definition::TypeClass, Definition::TypeFile, and Definition::TypeNamespace.
moveTo() [2/2]
virtual void MemberDefImpl::moveTo (Definition *) [virtual]
Implements MemberDef.
numberOfFlowKeyWords() [1/2]
int MemberDefImpl::numberOfFlowKeyWords () const [virtual]
Implements MemberDef.
Definition at line 5791 of file memberdef.cpp.
{
  return m_impl->numberOfFlowKW;
}
References m_impl, and MemberDefImpl::IMPL::numberOfFlowKW.
numberOfFlowKeyWords() [2/2]
virtual int MemberDefImpl::numberOfFlowKeyWords () const [virtual]
Implements MemberDef.
objCMethodName() [1/2]
QCString MemberDefImpl::objCMethodName (bool localLink, bool showStatic) const [virtual]
Implements MemberDef.
Definition at line 4758 of file memberdef.cpp.
{
  QCString qm;
  if (showStatic)
  {
    if (isStatic()) qm="+ "; else qm="- ";
  }
  qm+=name();
  if (!localLink) // link to method of same class
  {
    qm+=" (";
    qm+=getClassDef()->name();
    qm+=")";
  }
  return qm;
}
References getClassDef(), isStatic(), DefinitionMixin< MemberDefMutable >::name(), and Definition::name().
objCMethodName() [2/2]
virtual QCString MemberDefImpl::objCMethodName (bool localLink, bool showStatic) const [virtual]
Implements MemberDef.
operator=() [1/2]
MemberDefImpl & MemberDefImpl::operator= (const MemberDefImpl &) [private]
operator=() [2/2]
MemberDefImpl & MemberDefImpl::operator= (const MemberDefImpl &) [private]
protection() [1/2]
Protection MemberDefImpl::protection () const [virtual]
Implements MemberDef.
Definition at line 4875 of file memberdef.cpp.
{
  return m_impl->prot;
}
References m_impl, and MemberDefImpl::IMPL::prot.
Referenced by getLabels(), hasDetailedDescription(), isBriefSectionVisible(), and writeDeclaration().
protection() [2/2]
virtual Protection MemberDefImpl::protection () const [virtual]
Implements MemberDef.
qualifiedName() [1/2]
QCString MemberDefImpl::qualifiedName () const [virtual]
Returns the fully qualified name of this definition
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 4723 of file memberdef.cpp.
{
  if (isObjCMethod())
  {
    QCString qm;
    if (isStatic()) qm="+"; else qm="-";
    qm+="[";
    qm+=getClassDef()->name()+" ";
    qm+=name();
    qm+="]";
    return qm;
  }
  else if (m_impl->enumScope && m_impl->enumScope->isStrong())
  {
    return m_impl->enumScope->qualifiedName()+
           getLanguageSpecificSeparator(getLanguage())+
           localName();
  }
  else
  {
    return DefinitionMixin::qualifiedName();
  }
}
References MemberDefImpl::IMPL::enumScope, getClassDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), isObjCMethod(), isStatic(), MemberDef::isStrong(), DefinitionMixin< MemberDefMutable >::localName(), m_impl, DefinitionMixin< MemberDefMutable >::name(), Definition::name(), DefinitionMixin< Base >::qualifiedName(), and MemberDef::qualifiedName().
Referenced by _writeCallerGraph(), _writeCallGraph(), addListReference(), warnIfUndocumentedParams(), and writeTagFile().
qualifiedName() [2/2]
virtual QCString MemberDefImpl::qualifiedName () const [virtual]
Returns the fully qualified name of this definition
Reimplemented from DefinitionMixin< MemberDefMutable >.
reimplementedBy() [1/2]
const MemberVector & MemberDefImpl::reimplementedBy () const [virtual]
Implements MemberDef.
Definition at line 1477 of file memberdef.cpp.
{
  return m_impl->redefinedBy;
}
References m_impl, and MemberDefImpl::IMPL::redefinedBy.
Referenced by _countReimplementedBy(), and _writeReimplementedBy().
reimplementedBy() [2/2]
virtual const MemberVector & MemberDefImpl::reimplementedBy () const [virtual]
Implements MemberDef.
reimplements() [1/2]
const MemberDef * MemberDefImpl::reimplements () const [virtual]
Implements MemberDef.
Definition at line 1472 of file memberdef.cpp.
{
  return m_impl->redefines;
}
References m_impl, and MemberDefImpl::IMPL::redefines.
Referenced by doxmlparser.compound.memberdefType::__init__(), _isReimplements(), _writeReimplements(), doxmlparser.compound.memberdefType::add_reimplements(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_reimplements(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.memberdefType::insert_reimplements_at(), doxmlparser.compound.memberdefType::replace_reimplements_at(), doxmlparser.compound.memberdefType::set_reimplements(), and virtualness().
reimplements() [2/2]
virtual const MemberDef * MemberDefImpl::reimplements () const [virtual]
Implements MemberDef.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::add_reimplements(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_reimplements(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.memberdefType::insert_reimplements_at(), doxmlparser.compound.memberdefType::replace_reimplements_at(), and doxmlparser.compound.memberdefType::set_reimplements().
relatedAlso() [1/2]
ClassDef * MemberDefImpl::relatedAlso () const [virtual]
Implements MemberDef.
Definition at line 5227 of file memberdef.cpp.
{
  return m_impl->relatedAlso;
}
References m_impl, and MemberDefImpl::IMPL::relatedAlso.
Referenced by MemberDefImpl::IMPL::init().
relatedAlso() [2/2]
virtual ClassDef * MemberDefImpl::relatedAlso () const [virtual]
Implements MemberDef.
requiresClause() [1/2]
QCString MemberDefImpl::requiresClause () const [virtual]
Implements MemberDef.
Definition at line 5722 of file memberdef.cpp.
{
  return m_impl->requiresClause;
}
References m_impl, and MemberDefImpl::IMPL::requiresClause.
requiresClause() [2/2]
virtual QCString MemberDefImpl::requiresClause () const [virtual]
Implements MemberDef.
resolveAlias() [1/4]
virtual MemberDef * MemberDefImpl::resolveAlias () [inline], [virtual]
Implements MemberDef.
Definition at line 62 of file memberdef.cpp.
{ return this; }
resolveAlias() [2/4]
virtual MemberDef * MemberDefImpl::resolveAlias () [inline], [virtual]
Implements MemberDef.
Definition at line 62 of file memberdef.cpp.
{ return this; }
resolveAlias() [3/4]
virtual const MemberDef * MemberDefImpl::resolveAlias () const [inline], [virtual]
Implements MemberDef.
Definition at line 63 of file memberdef.cpp.
{ return this; }
resolveAlias() [4/4]
virtual const MemberDef * MemberDefImpl::resolveAlias () const [inline], [virtual]
Implements MemberDef.
Definition at line 63 of file memberdef.cpp.
{ return this; }
resolveUnnamedParameters() [1/2]
void MemberDefImpl::resolveUnnamedParameters (const MemberDef * md) [virtual]
Implements MemberDefMutable.
Definition at line 5297 of file memberdef.cpp.
{
  ArgumentList &decAl = m_impl->declArgList;
  ArgumentList &defAl = m_impl->defArgList;
  const ArgumentList &decAlSrc = md->declArgumentList();
  const ArgumentList &defAlSrc = md->argumentList();
  auto decSrc = decAlSrc.begin(), defSrc = defAlSrc.begin();
  for (auto decIt = decAl.begin(), defIt = defAl.begin();
       decIt != decAl.end() && defIt != defAl.end() && decSrc != decAlSrc.end() && defSrc != defAlSrc.end();
       ++decIt, ++defIt, ++decSrc, ++defSrc++)
  {
    Argument &decA = *decIt;
    Argument &defA = *defIt;
    const Argument &decAS = *decSrc;
    const Argument &defAS = *defSrc;
    if (decA.name.isEmpty())
    {
      if (!defA.name.isEmpty())
      {
        decA.name = defA.name;
      }
      else if (!decAS.name.isEmpty())
      {
        decA.name = decAS.name;
      }
      else if (!defAS.name.isEmpty())
      {
        decA.name = defAS.name;
      }
    }
    if (defA.name.isEmpty())
    {
      if (!decA.name.isEmpty())
      {
        defA.name = decA.name;
      }
      else if (!decAS.name.isEmpty())
      {
        defA.name = decAS.name;
      }
      else if (!defAS.name.isEmpty())
      {
        defA.name = defAS.name;
      }
    }
  }
}
References MemberDef::argumentList(), ArgumentList::begin(), MemberDefImpl::IMPL::declArgList, MemberDef::declArgumentList(), MemberDefImpl::IMPL::defArgList, ArgumentList::end(), QCString::isEmpty(), m_impl, and Argument::name.
resolveUnnamedParameters() [2/2]
virtual void MemberDefImpl::resolveUnnamedParameters (const MemberDef * md) [virtual]
Implements MemberDefMutable.
setAccessorType() [1/2]
void MemberDefImpl::setAccessorType (ClassDef * cd, const QCString & t) [virtual]
Implements MemberDefMutable.
Definition at line 4643 of file memberdef.cpp.
{
  m_impl->accessorClass = cd;
  m_impl->accessorType = t;
}
References MemberDefImpl::IMPL::accessorClass, MemberDefImpl::IMPL::accessorType, and m_impl.
setAccessorType() [2/2]
virtual void MemberDefImpl::setAccessorType (ClassDef * cd, const QCString & t) [virtual]
Implements MemberDefMutable.
setAnchor() [1/2]
void MemberDefImpl::setAnchor () [virtual]
Implements MemberDefMutable.
Definition at line 4101 of file memberdef.cpp.
{
  QCString memAnchor = name();
  if (!m_impl->args.isEmpty()) memAnchor+=m_impl->args;
  memAnchor.prepend(definition()); // actually the method name is now included
            // twice, which is silly, but we keep it this way for backward
            // compatibility.
  // include number of template arguments as well,
  // to distinguish between two template
  // specializations that only differ in the template parameters.
  if (m_impl->tArgList.hasParameters())
  {
    char buf[20];
    qsnprintf(buf,20,"%d:",static_cast<int>(m_impl->tArgList.size()));
    buf[19]='\0';
    memAnchor.prepend(buf);
  }
  if (!m_impl->requiresClause.isEmpty())
  {
    memAnchor+=" "+m_impl->requiresClause;
  }
  // convert to md5 hash
  uchar md5_sig[16];
  char sigStr[33];
  MD5Buffer(memAnchor.data(),memAnchor.length(),md5_sig);
  MD5SigToString(md5_sig,sigStr);
  m_impl->anc = QCString("a")+sigStr;
}
References MemberDefImpl::IMPL::anc, MemberDefImpl::IMPL::args, QCString::data(), definition(), ArgumentList::hasParameters(), QCString::isEmpty(), QCString::length(), m_impl, MD5Buffer(), MD5SigToString(), DefinitionMixin< MemberDefMutable >::name(), QCString::prepend(), qsnprintf, MemberDefImpl::IMPL::requiresClause, ArgumentList::size(), and MemberDefImpl::IMPL::tArgList.
setAnchor() [2/2]
virtual void MemberDefImpl::setAnchor () [virtual]
Implements MemberDefMutable.
setAnonymousEnumType() [1/2]
void MemberDefImpl::setAnonymousEnumType (const MemberDef * md) [virtual]
Implements MemberDefMutable.
Definition at line 5592 of file memberdef.cpp.
{
  m_impl->annEnumType = md;
}
References MemberDefImpl::IMPL::annEnumType, and m_impl.
setAnonymousEnumType() [2/2]
virtual void MemberDefImpl::setAnonymousEnumType (const MemberDef * md) [virtual]
Implements MemberDefMutable.
setAnonymousUsed() [1/2]
void MemberDefImpl::setAnonymousUsed () const [virtual]
Implements MemberDefMutable.
Definition at line 5375 of file memberdef.cpp.
{
  m_impl->annUsed = TRUE;
}
References MemberDefImpl::IMPL::annUsed, m_impl, and TRUE.
Referenced by writeDeclaration().
setAnonymousUsed() [2/2]
virtual void MemberDefImpl::setAnonymousUsed () const [virtual]
Implements MemberDefMutable.
setArgsString() [1/2]
void MemberDefImpl::setArgsString (const QCString & as) [virtual]
Implements MemberDefMutable.
Definition at line 5570 of file memberdef.cpp.
{
  m_impl->args = as;
}
References MemberDefImpl::IMPL::args, and m_impl.
setArgsString() [2/2]
virtual void MemberDefImpl::setArgsString (const QCString & as) [virtual]
Implements MemberDefMutable.
setBitfields() [1/2]
void MemberDefImpl::setBitfields (const QCString & s) [virtual]
Implements MemberDefMutable.
Definition at line 5525 of file memberdef.cpp.
{
  m_impl->bitfields = QCString(s).simplifyWhiteSpace();
}
References MemberDefImpl::IMPL::bitfields, m_impl, s, and QCString::simplifyWhiteSpace().
setBitfields() [2/2]
virtual void MemberDefImpl::setBitfields (const QCString & s) [virtual]
Implements MemberDefMutable.
setBriefDescription() [1/2]
void MemberDefImpl::setBriefDescription (const QCString & b, const QCString & briefFile, int briefLine) [virtual]
Sets the brief description of this definition to b. A dot is added to the sentence if not available.
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 1722 of file memberdef.cpp.
{
  DefinitionMixin::setBriefDescription(b,briefFile,briefLine);
  m_isLinkableCached = 0;
}
References b, DefinitionMixin< MemberDefMutable >::briefFile(), DefinitionMixin< MemberDefMutable >::briefLine(), m_isLinkableCached, and DefinitionMixin< Base >::setBriefDescription().
setBriefDescription() [2/2]
virtual void MemberDefImpl::setBriefDescription (const QCString & b, const QCString & briefFile, int briefLine) [virtual]
Sets the brief description of this definition to b. A dot is added to the sentence if not available.
Reimplemented from DefinitionMixin< MemberDefMutable >.
setCategory() [1/2]
void MemberDefImpl::setCategory (ClassDef * def) [virtual]
Implements MemberDefMutable.
Definition at line 5692 of file memberdef.cpp.
{
  m_impl->category = def;
}
References MemberDefImpl::IMPL::category, and m_impl.
setCategory() [2/2]
virtual void MemberDefImpl::setCategory (ClassDef *) [virtual]
Implements MemberDefMutable.
setCategoryRelation() [1/2]
void MemberDefImpl::setCategoryRelation (const MemberDef * md) [virtual]
Implements MemberDefMutable.
Definition at line 5702 of file memberdef.cpp.
{
  m_impl->categoryRelation = md;
}
References MemberDefImpl::IMPL::categoryRelation, and m_impl.
setCategoryRelation() [2/2]
virtual void MemberDefImpl::setCategoryRelation (const MemberDef *) [virtual]
Implements MemberDefMutable.
setDeclFile() [1/2]
void MemberDefImpl::setDeclFile (const QCString & df, int line, int column) [virtual]
Implements MemberDefMutable.
Definition at line 5624 of file memberdef.cpp.
{
  m_impl->declFileName = df;
  m_impl->declLine = line;
  m_impl->declColumn = column;
}
References MemberDefImpl::IMPL::declColumn, MemberDefImpl::IMPL::declFileName, MemberDefImpl::IMPL::declLine, and m_impl.
Referenced by setExplicitExternal(), and setPrototype().
setDeclFile() [2/2]
virtual void MemberDefImpl::setDeclFile (const QCString & df, int line, int column) [virtual]
Implements MemberDefMutable.
setDefinition() [1/2]
void MemberDefImpl::setDefinition (const QCString & d) [virtual]
Implements MemberDefMutable.
Definition at line 5496 of file memberdef.cpp.
{
  m_impl->def=d;
}
References MemberDefImpl::IMPL::def, and m_impl.
setDefinition() [2/2]
virtual void MemberDefImpl::setDefinition (const QCString & d) [virtual]
Implements MemberDefMutable.
setDefinitionTemplateParameterLists() [1/2]
void MemberDefImpl::setDefinitionTemplateParameterLists (const ArgumentLists & lists) [virtual]
Implements MemberDefMutable.
Definition at line 1764 of file memberdef.cpp.
{
  m_impl->defTmpArgLists = lists;
}
References MemberDefImpl::IMPL::defTmpArgLists, and m_impl.
Referenced by deepCopy().
setDefinitionTemplateParameterLists() [2/2]
virtual void MemberDefImpl::setDefinitionTemplateParameterLists (const ArgumentLists & lists) [virtual]
Implements MemberDefMutable.
setDocsForDefinition() [1/2]
void MemberDefImpl::setDocsForDefinition (bool b) [virtual]
Implements MemberDefMutable.
Definition at line 5662 of file memberdef.cpp.
{
  m_impl->docsForDefinition = b;
}
References b, MemberDefImpl::IMPL::docsForDefinition, and m_impl.
setDocsForDefinition() [2/2]
virtual void MemberDefImpl::setDocsForDefinition (bool b) [virtual]
Implements MemberDefMutable.
setDocumentation() [1/2]
void MemberDefImpl::setDocumentation (const QCString & d, const QCString & docFile, int docLine, bool stripWhiteSpace = TRUE) [virtual]
Sets the documentation of this definition to d.
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 1716 of file memberdef.cpp.
{
  DefinitionMixin::setDocumentation(d,docFile,docLine,stripWhiteSpace);
  m_isLinkableCached = 0;
}
References DefinitionMixin< MemberDefMutable >::docFile(), DefinitionMixin< MemberDefMutable >::docLine(), m_isLinkableCached, and DefinitionMixin< Base >::setDocumentation().
setDocumentation() [2/2]
virtual void MemberDefImpl::setDocumentation (const QCString & d, const QCString & docFile, int docLine, bool stripWhiteSpace = TRUE) [virtual]
Sets the documentation of this definition to d.
Reimplemented from DefinitionMixin< MemberDefMutable >.
setDocumentedEnumValues() [1/2]
void MemberDefImpl::setDocumentedEnumValues (bool value) [virtual]
Implements MemberDefMutable.
Definition at line 5587 of file memberdef.cpp.
{
  m_impl->docEnumValues=value;
}
References MemberDefImpl::IMPL::docEnumValues, and m_impl.
setDocumentedEnumValues() [2/2]
virtual void MemberDefImpl::setDocumentedEnumValues (bool value) [virtual]
Implements MemberDefMutable.
setEnumBaseType() [1/2]
void MemberDefImpl::setEnumBaseType (const QCString & type) [virtual]
Implements MemberDefMutable.
Definition at line 5707 of file memberdef.cpp.
{
  m_impl->enumBaseType = type;
}
References MemberDefImpl::IMPL::enumBaseType, and m_impl.
setEnumBaseType() [2/2]
virtual void MemberDefImpl::setEnumBaseType (const QCString & type) [virtual]
Implements MemberDefMutable.
setEnumClassScope() [1/2]
void MemberDefImpl::setEnumClassScope (const ClassDef * cd) [virtual]
Implements MemberDefMutable.
Definition at line 5580 of file memberdef.cpp.
{
  m_impl->classDef = cd;
  m_isLinkableCached = 0;
  m_isConstructorCached = 0;
}
References MemberDefImpl::IMPL::classDef, m_impl, m_isConstructorCached, and m_isLinkableCached.
setEnumClassScope() [2/2]
virtual void MemberDefImpl::setEnumClassScope (const ClassDef * cd) [virtual]
Implements MemberDefMutable.
setEnumScope() [1/2]
void MemberDefImpl::setEnumScope (const MemberDef * md, bool livesInsideEnum = FALSE) [virtual]
Implements MemberDefMutable.
Definition at line 4147 of file memberdef.cpp.
{
  m_impl->enumScope=md;
  m_impl->livesInsideEnum=livesInsideEnum;
  if (md->getGroupDef())
  {
    m_impl->group = const_cast<GroupDef*>(md->getGroupDef());
    m_impl->grouppri = md->getGroupPri();
    m_impl->groupFileName = md->getGroupFileName();
    m_impl->groupStartLine = md->getGroupStartLine();
    m_impl->groupHasDocs = md->getGroupHasDocs();
    m_isLinkableCached = 0;
  }
}
References MemberDefImpl::IMPL::enumScope, MemberDef::getGroupDef(), MemberDef::getGroupFileName(), MemberDef::getGroupHasDocs(), MemberDef::getGroupPri(), MemberDef::getGroupStartLine(), MemberDefImpl::IMPL::group, MemberDefImpl::IMPL::groupFileName, MemberDefImpl::IMPL::groupHasDocs, MemberDefImpl::IMPL::grouppri, MemberDefImpl::IMPL::groupStartLine, livesInsideEnum(), MemberDefImpl::IMPL::livesInsideEnum, m_impl, and m_isLinkableCached.
setEnumScope() [2/2]
virtual void MemberDefImpl::setEnumScope (const MemberDef * md, bool livesInsideEnum = FALSE) [virtual]
Implements MemberDefMutable.
setExplicitExternal() [1/2]
void MemberDefImpl::setExplicitExternal (bool b, const QCString & df, int line, int column) [virtual]
Implements MemberDefMutable.
Definition at line 5610 of file memberdef.cpp.
{
  m_impl->explExt=b;
  if (b)
  {
    setDeclFile(df,line,column);
  }
  else
  {
    setDefFile(df,line,column);
  }
}
References b, MemberDefImpl::IMPL::explExt, m_impl, setDeclFile(), and DefinitionMixin< MemberDefMutable >::setDefFile().
setExplicitExternal() [2/2]
virtual void MemberDefImpl::setExplicitExternal (bool b, const QCString & df, int line, int column) [virtual]
Implements MemberDefMutable.
setFileDef() [1/2]
void MemberDefImpl::setFileDef (const FileDef * fd) [virtual]
Implements MemberDefMutable.
Definition at line 5501 of file memberdef.cpp.
{
  m_impl->fileDef=fd;
  m_isLinkableCached = 0;
  m_isConstructorCached = 0;
  m_isDestructorCached = 0;
}
References MemberDefImpl::IMPL::fileDef, m_impl, m_isConstructorCached, m_isDestructorCached, and m_isLinkableCached.
setFileDef() [2/2]
virtual void MemberDefImpl::setFileDef (const FileDef * fd) [virtual]
Implements MemberDefMutable.
setFromAnonymousMember() [1/2]
void MemberDefImpl::setFromAnonymousMember (MemberDef * m) [virtual]
Implements MemberDefMutable.
Definition at line 5646 of file memberdef.cpp.
{
  m_impl->annMemb=m;
}
References MemberDefImpl::IMPL::annMemb, and m_impl.
setFromAnonymousMember() [2/2]
virtual void MemberDefImpl::setFromAnonymousMember (MemberDef * m) [virtual]
Implements MemberDefMutable.
setFromAnonymousScope() [1/2]
void MemberDefImpl::setFromAnonymousScope (bool b) const [virtual]
Implements MemberDefMutable.
Definition at line 5641 of file memberdef.cpp.
{
  m_impl->annScope=b;
}
References MemberDefImpl::IMPL::annScope, b, and m_impl.
setFromAnonymousScope() [2/2]
virtual void MemberDefImpl::setFromAnonymousScope (bool b) const [virtual]
Implements MemberDefMutable.
setGroupAlias() [1/2]
void MemberDefImpl::setGroupAlias (const MemberDef * md) [virtual]
Implements MemberDefMutable.
Definition at line 5667 of file memberdef.cpp.
{
  m_impl->groupAlias = md;
}
References MemberDefImpl::IMPL::groupAlias, and m_impl.
setGroupAlias() [2/2]
virtual void MemberDefImpl::setGroupAlias (const MemberDef * md) [virtual]
Implements MemberDefMutable.
setGroupDef() [1/2]
void MemberDefImpl::setGroupDef (const GroupDef * gd, Grouping::GroupPri_t pri, const QCString & fileName, int startLine, bool hasDocs, MemberDef * member = 0) [virtual]
Implements MemberDefMutable.
Definition at line 4133 of file memberdef.cpp.
{
  //printf("%s MemberDefImpl::setGroupDef(%s)\n",qPrint(name()),qPrint(gd->name()));
  m_impl->group=gd;
  m_impl->grouppri=pri;
  m_impl->groupFileName=fileName;
  m_impl->groupStartLine=startLine;
  m_impl->groupHasDocs=hasDocs;
  m_impl->groupMember=member;
  m_isLinkableCached = 0;
}
References MemberDefImpl::IMPL::group, MemberDefImpl::IMPL::groupFileName, MemberDefImpl::IMPL::groupHasDocs, MemberDefImpl::IMPL::groupMember, MemberDefImpl::IMPL::grouppri, MemberDefImpl::IMPL::groupStartLine, m_impl, and m_isLinkableCached.
setGroupDef() [2/2]
virtual void MemberDefImpl::setGroupDef (const GroupDef * gd, Grouping::GroupPri_t pri, const QCString & fileName, int startLine, bool hasDocs, MemberDef * member = 0) [virtual]
Implements MemberDefMutable.
setHidden() [1/2]
void MemberDefImpl::setHidden (bool b) [virtual]
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 1734 of file memberdef.cpp.
{
  DefinitionMixin::setHidden(b);
  m_isLinkableCached = 0;
}
References b, m_isLinkableCached, and DefinitionMixin< Base >::setHidden().
setHidden() [2/2]
virtual void MemberDefImpl::setHidden (bool b) [virtual]
Reimplemented from DefinitionMixin< MemberDefMutable >.
setInbodyDocumentation() [1/2]
void MemberDefImpl::setInbodyDocumentation (const QCString & d, const QCString & docFile, int docLine) [virtual]
Set the documentation that was found inside the body of an item. If there was already some documentation set, the new documentation will be appended.
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 1728 of file memberdef.cpp.
{
  DefinitionMixin::setInbodyDocumentation(d,inbodyFile,inbodyLine);
  m_isLinkableCached = 0;
}
References DefinitionMixin< MemberDefMutable >::inbodyFile(), DefinitionMixin< MemberDefMutable >::inbodyLine(), m_isLinkableCached, and DefinitionMixin< Base >::setInbodyDocumentation().
setInbodyDocumentation() [2/2]
virtual void MemberDefImpl::setInbodyDocumentation (const QCString & d, const QCString & docFile, int docLine) [virtual]
Set the documentation that was found inside the body of an item. If there was already some documentation set, the new documentation will be appended.
Reimplemented from DefinitionMixin< MemberDefMutable >.
setInheritsDocsFrom() [1/2]
void MemberDefImpl::setInheritsDocsFrom (const MemberDef * md) [virtual]
Implements MemberDefMutable.
Definition at line 5565 of file memberdef.cpp.
{
  m_impl->docProvider = md;
}
References MemberDefImpl::IMPL::docProvider, and m_impl.
setInheritsDocsFrom() [2/2]
virtual void MemberDefImpl::setInheritsDocsFrom (const MemberDef * md) [virtual]
Implements MemberDefMutable.
setInitializer() [1/2]
void MemberDefImpl::setInitializer (const QCString & i) [virtual]
Implements MemberDefMutable.
Definition at line 4237 of file memberdef.cpp.
{
  m_impl->initializer=initializer;
  int l=m_impl->initializer.length();
  int p=l-1;
  while (p>=0 && isspace(static_cast<uchar>(m_impl->initializer.at(p)))) p--;
  m_impl->initializer=m_impl->initializer.left(p+1);
  m_impl->initLines=m_impl->initializer.contains('\n');
  //printf("%s::setInitializer(%s)\n",qPrint(name()),qPrint(m_impl->initializer));
}
References QCString::at(), QCString::contains(), initializer(), MemberDefImpl::IMPL::initializer, MemberDefImpl::IMPL::initLines, reg::isspace(), QCString::left(), QCString::length(), m_impl, and p.
setInitializer() [2/2]
virtual void MemberDefImpl::setInitializer (const QCString & i) [virtual]
Implements MemberDefMutable.
setMaxInitLines() [1/2]
void MemberDefImpl::setMaxInitLines (int lines) [virtual]
Implements MemberDefMutable.
Definition at line 5530 of file memberdef.cpp.
{
  if (lines!=-1)
  {
    m_impl->userInitLines=lines;
  }
}
References m_impl, and MemberDefImpl::IMPL::userInitLines.
setMaxInitLines() [2/2]
virtual void MemberDefImpl::setMaxInitLines (int lines) [virtual]
Implements MemberDefMutable.
setMemberClass() [1/2]
void MemberDefImpl::setMemberClass (const ClassDef * cd) [virtual]
Implements MemberDefMutable.
Definition at line 4162 of file memberdef.cpp.
{
  m_impl->classDef=cd;
  m_isLinkableCached = 0;
  m_isConstructorCached = 0;
  setOuterScope(const_cast<ClassDef*>(cd));
}
References MemberDefImpl::IMPL::classDef, m_impl, m_isConstructorCached, m_isLinkableCached, and DefinitionMixin< MemberDefMutable >::setOuterScope().
setMemberClass() [2/2]
virtual void MemberDefImpl::setMemberClass (const ClassDef * cd) [virtual]
Implements MemberDefMutable.
setMemberDeclaration() [1/2]
void MemberDefImpl::setMemberDeclaration (MemberDef * md) [virtual]
Implements MemberDefMutable.
Definition at line 5682 of file memberdef.cpp.
{
  m_impl->memDec=md;
}
References m_impl, and MemberDefImpl::IMPL::memDec.
setMemberDeclaration() [2/2]
virtual void MemberDefImpl::setMemberDeclaration (MemberDef * md) [virtual]
Implements MemberDefMutable.
setMemberDefinition() [1/2]
void MemberDefImpl::setMemberDefinition (MemberDef * md) [virtual]
Implements MemberDefMutable.
Definition at line 5677 of file memberdef.cpp.
{
  m_impl->memDef=md;
}
References m_impl, and MemberDefImpl::IMPL::memDef.
setMemberDefinition() [2/2]
virtual void MemberDefImpl::setMemberDefinition (MemberDef * md) [virtual]
Implements MemberDefMutable.
setMemberGroup() [1/2]
void MemberDefImpl::setMemberGroup (MemberGroup * grp) [virtual]
Implements MemberDef.
Definition at line 4088 of file memberdef.cpp.
{
  m_impl->memberGroup = grp;
}
References m_impl, and MemberDefImpl::IMPL::memberGroup.
setMemberGroup() [2/2]
virtual void MemberDefImpl::setMemberGroup (MemberGroup * grp) [virtual]
Implements MemberDef.
setMemberGroupId() [1/2]
void MemberDefImpl::setMemberGroupId (int id) [virtual]
Implements MemberDefMutable.
Definition at line 5631 of file memberdef.cpp.
{
  m_impl->grpId=id;
}
References MemberDefImpl::IMPL::grpId, DefinitionMixin< MemberDefMutable >::id(), and m_impl.
setMemberGroupId() [2/2]
virtual void MemberDefImpl::setMemberGroupId (int id) [virtual]
Implements MemberDefMutable.
setMemberSpecifiers() [1/2]
void MemberDefImpl::setMemberSpecifiers (uint64 s) [virtual]
Implements MemberDefMutable.
Definition at line 5515 of file memberdef.cpp.
{
  m_impl->memSpec=s;
}
References m_impl, MemberDefImpl::IMPL::memSpec, and s.
setMemberSpecifiers() [2/2]
virtual void MemberDefImpl::setMemberSpecifiers (uint64 s) [virtual]
Implements MemberDefMutable.
setMemberType() [1/2]
void MemberDefImpl::setMemberType (MemberType t) [virtual]
Implements MemberDefMutable.
Definition at line 5490 of file memberdef.cpp.
{
  m_impl->mtype=t;
  m_isLinkableCached = 0;
}
References m_impl, m_isLinkableCached, and MemberDefImpl::IMPL::mtype.
setMemberType() [2/2]
virtual void MemberDefImpl::setMemberType (MemberType t) [virtual]
Implements MemberDefMutable.
setNamespace() [1/2]
void MemberDefImpl::setNamespace (const NamespaceDef * nd) [virtual]
Implements MemberDefMutable.
Definition at line 4170 of file memberdef.cpp.
{
  m_impl->nspace=nd;
  setOuterScope(const_cast<NamespaceDef*>(nd));
}
References m_impl, MemberDefImpl::IMPL::nspace, and DefinitionMixin< MemberDefMutable >::setOuterScope().
setNamespace() [2/2]
virtual void MemberDefImpl::setNamespace (const NamespaceDef * nd) [virtual]
Implements MemberDefMutable.
setProtection() [1/2]
void MemberDefImpl::setProtection (Protection p) [virtual]
Implements MemberDefMutable.
Definition at line 5509 of file memberdef.cpp.
{
  m_impl->prot=p;
  m_isLinkableCached = 0;
}
References m_impl, m_isLinkableCached, p, and MemberDefImpl::IMPL::prot.
setProtection() [2/2]
virtual void MemberDefImpl::setProtection (Protection p) [virtual]
Implements MemberDefMutable.
setPrototype() [1/2]
void MemberDefImpl::setPrototype (bool p, const QCString & df, int line, int column) [virtual]
Implements MemberDefMutable.
Definition at line 5597 of file memberdef.cpp.
{
  m_impl->proto=p;
  if (p)
  {
    setDeclFile(df,line,column);
  }
  else
  {
    setDefFile(df,line,column);
  }
}
References m_impl, p, MemberDefImpl::IMPL::proto, setDeclFile(), and DefinitionMixin< MemberDefMutable >::setDefFile().
setPrototype() [2/2]
virtual void MemberDefImpl::setPrototype (bool p, const QCString & df, int line, int column) [virtual]
Implements MemberDefMutable.
setReadAccessor() [1/2]
void MemberDefImpl::setReadAccessor (const QCString & r) [virtual]
Implements MemberDefMutable.
Definition at line 5538 of file memberdef.cpp.
{
  m_impl->read=r;
}
References m_impl, r, and MemberDefImpl::IMPL::read.
setReadAccessor() [2/2]
virtual void MemberDefImpl::setReadAccessor (const QCString & r) [virtual]
Implements MemberDefMutable.
setReimplements() [1/2]
void MemberDefImpl::setReimplements (const MemberDef * md) [virtual]
Implements MemberDefMutable.
Definition at line 1451 of file memberdef.cpp.
{
  m_impl->redefines = md;
}
References m_impl, and MemberDefImpl::IMPL::redefines.
setReimplements() [2/2]
virtual void MemberDefImpl::setReimplements (const MemberDef * md) [virtual]
Implements MemberDefMutable.
setRelatedAlso() [1/2]
void MemberDefImpl::setRelatedAlso (ClassDef * cd) [virtual]
Implements MemberDefMutable.
Definition at line 5575 of file memberdef.cpp.
{
  m_impl->relatedAlso=cd;
}
References m_impl, and MemberDefImpl::IMPL::relatedAlso.
setRelatedAlso() [2/2]
virtual void MemberDefImpl::setRelatedAlso (ClassDef * cd) [virtual]
Implements MemberDefMutable.
setRequiresClause() [1/2]
void MemberDefImpl::setRequiresClause (const QCString & req) [virtual]
Implements MemberDefMutable.
Definition at line 5717 of file memberdef.cpp.
{
  m_impl->requiresClause = req;
}
References m_impl, and MemberDefImpl::IMPL::requiresClause.
setRequiresClause() [2/2]
virtual void MemberDefImpl::setRequiresClause (const QCString & req) [virtual]
Implements MemberDefMutable.
setSectionList() [1/2]
void MemberDefImpl::setSectionList (const Definition * container, const MemberList * sl) [virtual]
Implements MemberDefMutable.
Definition at line 4310 of file memberdef.cpp.
{
  //printf("MemberDefImpl::setSectionList(%s,%p) name=%s\n",qPrint(d->name()),sl,qPrint(name()));
  m_impl->sectionMap.insert(std::make_pair(container,sl));
}
References m_impl, MemberDefImpl::IMPL::sectionMap, and caseconvert::sl.
setSectionList() [2/2]
virtual void MemberDefImpl::setSectionList (const Definition * container, const MemberList * sl) [virtual]
Implements MemberDefMutable.
setTagInfo() [1/2]
void MemberDefImpl::setTagInfo (const TagInfo * i) [virtual]
Implements MemberDefMutable.
Definition at line 4747 of file memberdef.cpp.
{
  if (ti)
  {
    //printf("%s: Setting tag name=%s anchor=%s\n",qPrint(name()),qPrint(ti->tagName),qPrint(ti->anchor));
    m_impl->anc=ti->anchor;
    setReference(ti->tagName);
    m_impl->explicitOutputFileBase = stripExtension(ti->fileName);
  }
}
References MemberDefImpl::IMPL::anc, TagInfo::anchor, MemberDefImpl::IMPL::explicitOutputFileBase, TagInfo::fileName, m_impl, DefinitionMixin< MemberDefMutable >::setReference(), stripExtension(), and TagInfo::tagName.
setTagInfo() [2/2]
virtual void MemberDefImpl::setTagInfo (const TagInfo * i) [virtual]
Implements MemberDefMutable.
setTemplateMaster() [1/2]
void MemberDefImpl::setTemplateMaster (const MemberDef * mt) [virtual]
Implements MemberDefMutable.
Definition at line 5656 of file memberdef.cpp.
{
  m_impl->templateMaster=mt;
  m_isLinkableCached = 0;
}
References m_impl, m_isLinkableCached, and MemberDefImpl::IMPL::templateMaster.
setTemplateMaster() [2/2]
virtual void MemberDefImpl::setTemplateMaster (const MemberDef * mt) [virtual]
Implements MemberDefMutable.
setTemplateSpecialization() [1/2]
void MemberDefImpl::setTemplateSpecialization (bool b) [virtual]
Implements MemberDefMutable.
Definition at line 5548 of file memberdef.cpp.
{
  m_impl->tspec=b;
}
References b, m_impl, and MemberDefImpl::IMPL::tspec.
setTemplateSpecialization() [2/2]
virtual void MemberDefImpl::setTemplateSpecialization (bool b) [virtual]
Implements MemberDefMutable.
setType() [1/2]
void MemberDefImpl::setType (const QCString & t) [virtual]
Implements MemberDefMutable.
Definition at line 4638 of file memberdef.cpp.
{
  m_impl->type = t;
}
References m_impl, and MemberDefImpl::IMPL::type.
setType() [2/2]
virtual void MemberDefImpl::setType (const QCString & t) [virtual]
Implements MemberDefMutable.
setTypeConstraints() [1/2]
void MemberDefImpl::setTypeConstraints (const ArgumentList & al) [virtual]
Implements MemberDefMutable.
Definition at line 4633 of file memberdef.cpp.
{
  m_impl->typeConstraints = al;
}
References m_impl, and MemberDefImpl::IMPL::typeConstraints.
setTypeConstraints() [2/2]
virtual void MemberDefImpl::setTypeConstraints (const ArgumentList & al) [virtual]
Implements MemberDefMutable.
setWriteAccessor() [1/2]
void MemberDefImpl::setWriteAccessor (const QCString & w) [virtual]
Implements MemberDefMutable.
Definition at line 5543 of file memberdef.cpp.
{
  m_impl->write=w;
}
References m_impl, w, and MemberDefImpl::IMPL::write.
setWriteAccessor() [2/2]
virtual void MemberDefImpl::setWriteAccessor (const QCString & w) [virtual]
Implements MemberDefMutable.
showInCallGraph() [1/2]
bool MemberDefImpl::showInCallGraph () const [virtual]
Implements MemberDef.
Definition at line 5218 of file memberdef.cpp.
{
  return isFunction() ||
         isSlot() ||
         isConstructor() ||
         isDestructor() ||
         isObjCMethod();
}
References isConstructor(), isDestructor(), isFunction(), isObjCMethod(), and isSlot().
showInCallGraph() [2/2]
virtual bool MemberDefImpl::showInCallGraph () const [virtual]
Implements MemberDef.
templateArguments() [1/2]
const ArgumentList & MemberDefImpl::templateArguments () const [virtual]
Implements MemberDef.
Definition at line 5345 of file memberdef.cpp.
{
  return m_impl->tArgList;
}
References m_impl, and MemberDefImpl::IMPL::tArgList.
templateArguments() [2/2]
virtual const ArgumentList & MemberDefImpl::templateArguments () const [virtual]
Implements MemberDef.
templateMaster() [1/2]
const MemberDef * MemberDefImpl::templateMaster () const [virtual]
Implements MemberDef.
Definition at line 5426 of file memberdef.cpp.
{
  return m_impl->templateMaster;
}
References m_impl, and MemberDefImpl::IMPL::templateMaster.
Referenced by _computeLinkableInProject(), getOutputFileBase(), getReference(), and MemberDefImpl::IMPL::init().
templateMaster() [2/2]
virtual const MemberDef * MemberDefImpl::templateMaster () const [virtual]
Implements MemberDef.
typeConstraints() [1/2]
const ArgumentList & MemberDefImpl::typeConstraints () const [virtual]
Implements MemberDef.
Definition at line 5996 of file memberdef.cpp.
{
  return m_impl->typeConstraints;
}
References m_impl, and MemberDefImpl::IMPL::typeConstraints.
typeConstraints() [2/2]
virtual const ArgumentList & MemberDefImpl::typeConstraints () const [virtual]
Implements MemberDef.
typeString() [1/2]
QCString MemberDefImpl::typeString () const [virtual]
Implements MemberDef.
Definition at line 4790 of file memberdef.cpp.
{
  return m_impl->type;
}
References m_impl, and MemberDefImpl::IMPL::type.
Referenced by warnIfUndocumentedParams(), and writeTagFile().
typeString() [2/2]
virtual QCString MemberDefImpl::typeString () const [virtual]
Implements MemberDef.
virtualness() [1/2]
Specifier MemberDefImpl::virtualness (int count = 0) const [virtual]
Implements MemberDef.
Definition at line 4316 of file memberdef.cpp.
{
  if (count>25)
  {
     warn(getDefFileName(),getDefLine(),
       "Internal inconsistency: recursion detected in overload relation for member %s!"
       ,qPrint(name())
      );
     return Normal;
  }
  Specifier v = m_impl->virt;
  const MemberDef *rmd = reimplements();
  while (rmd && v==Normal)
  {
    v = rmd->virtualness(count+1)==Normal ? Normal : Virtual;
    rmd = rmd->reimplements();
  }
  return v;
}
References DefinitionMixin< MemberDefMutable >::getDefFileName(), DefinitionMixin< MemberDefMutable >::getDefLine(), m_impl, DefinitionMixin< MemberDefMutable >::name(), Normal, qPrint(), reimplements(), MemberDef::reimplements(), MemberDefImpl::IMPL::virt, Virtual, MemberDef::virtualness(), and warn().
Referenced by getLabels().
virtualness() [2/2]
virtual Specifier MemberDefImpl::virtualness (int count = 0) const [virtual]
Implements MemberDef.
visibleInIndex() [1/2]
bool MemberDefImpl::visibleInIndex () const [virtual]
Implements MemberDef.
Definition at line 3915 of file memberdef.cpp.
{
  bool hideUndocMembers = Config_getBool(HIDE_UNDOC_MEMBERS);
  bool extractStatic = Config_getBool(EXTRACT_STATIC);
  return (!isAnonymous() &&
      (!hideUndocMembers || hasDocumentation()) &&
      (!isStatic() || extractStatic) &&
      isLinkable()
     );
}
References Config_getBool, hasDocumentation(), DefinitionMixin< MemberDefMutable >::isAnonymous(), isLinkable(), and isStatic().
visibleInIndex() [2/2]
virtual bool MemberDefImpl::visibleInIndex () const [virtual]
Implements MemberDef.
warnIfUndocumented() [1/2]
void MemberDefImpl::warnIfUndocumented () const [virtual]
Implements MemberDef.
Definition at line 3871 of file memberdef.cpp.
{
  /*
   * Removed bug_303020:
   * if (m_impl->memberGroup) return;
   */
  const ClassDef *cd = getClassDef();
  const NamespaceDef *nd = getNamespaceDef();
  const FileDef *fd = getFileDef();
  const GroupDef *gd = getGroupDef();
  const Definition *d=0;
  QCString t;
  if (cd)
    t=cd->compoundTypeString(), d=cd;
  else if (nd)
  {
    d=nd;
    t=nd->compoundTypeString();
  }
  else if (gd)
    t="group", d=gd;
  else
    t="file", d=fd;
  bool extractAll = Config_getBool(EXTRACT_ALL);
  //printf("%s:warnIfUndoc: hasUserDocs=%d isFriendClass=%d protection=%d isRef=%d isDel=%d\n",
  // qPrint(name()),
  // hasUserDocumentation(),isFriendClass(),protectionLevelVisible(m_impl->prot),isReference(),isDeleted());
  if ((!hasUserDocumentation() && !extractAll) &&
      !isFriendClass() &&
      name().find('@')==-1 && d && d->name().find('@')==-1 &&
      protectionLevelVisible(m_impl->prot) &&
      !isReference() && !isDeleted()
     )
  {
    warn_undoc(getDefFileName(),getDefLine(),"Member %s%s (%s) of %s %s is not documented.",
         qPrint(name()),qPrint(argsString()),qPrint(memberTypeName()),qPrint(t),qPrint(d->name()));
  }
  else if (!hasDetailedDescription())
  {
    warnIfUndocumentedParams();
  }
}
References argsString(), ClassDef::compoundTypeString(), NamespaceDef::compoundTypeString(), Config_getBool, QCString::find(), getClassDef(), DefinitionMixin< MemberDefMutable >::getDefFileName(), DefinitionMixin< MemberDefMutable >::getDefLine(), getFileDef(), getGroupDef(), getNamespaceDef(), hasDetailedDescription(), DefinitionMixin< MemberDefMutable >::hasUserDocumentation(), isDeleted(), isFriendClass(), isReference(), m_impl, memberTypeName(), DefinitionMixin< MemberDefMutable >::name(), Definition::name(), MemberDefImpl::IMPL::prot, protectionLevelVisible(), qPrint(), warn_undoc(), and warnIfUndocumentedParams().
Referenced by writeDeclaration().
warnIfUndocumented() [2/2]
virtual void MemberDefImpl::warnIfUndocumented () const [virtual]
Implements MemberDef.
warnIfUndocumentedParams() [1/2]
void MemberDefImpl::warnIfUndocumentedParams () const [virtual]
Implements MemberDef.
Definition at line 4008 of file memberdef.cpp.
{
  QCString returnType = typeString();
  bool isFortran = getLanguage()==SrcLangExt_Fortran;
  bool isFortranSubroutine = isFortran && returnType.find("subroutine")!=-1;
  bool isVoidReturn = (returnType=="void") || (returnType.endsWith(" void"));
  if (!isVoidReturn && returnType == "auto")
  {
    const ArgumentList &defArgList=isDocsForDefinition() ? argumentList() : declArgumentList();
    if (!defArgList.trailingReturnType().isEmpty())
    {
      QCString strippedTrailingReturn = stripTrailingReturn(defArgList.trailingReturnType());
      isVoidReturn = (strippedTrailingReturn=="void") || (strippedTrailingReturn.endsWith(" void"));
    }
  }
  if (!Config_getBool(EXTRACT_ALL) &&
      Config_getBool(WARN_IF_UNDOCUMENTED) &&
      Config_getBool(WARN_NO_PARAMDOC) &&
      isFunction() &&
      !isDeleted() &&
      !isReference() &&
      !Doxygen::suppressDocWarnings)
  {
    if (!m_impl->hasDocumentedParams)
    {
      warn_doc_error(docFile(),docLine(),
          "parameters of member %s are not documented",
          qPrint(qualifiedName()));
    }
    if (!m_impl->hasDocumentedReturnType &&
        hasDocumentation() && !returnType.isEmpty() &&
        !(// not one of the cases where nothing is returned
          isVoidReturn || // void return type
          isFortranSubroutine || // fortran subroutine
          isConstructor() || // a constructor
          isDestructor() // or destructor
         )
       )
    {
      warn_doc_error(docFile(),docLine(),
          "return type of member %s is not documented",
          qPrint(qualifiedName()));
    }
  }
  if (Config_getBool(WARN_IF_DOC_ERROR) &&
            m_impl->hasDocumentedReturnType &&
            (isVoidReturn || // void return type
             isFortranSubroutine || // fortran subroutine
             isConstructor() || // a constructor
             isDestructor())) // or destructor
  {
    warn_doc_error(docFile(),docLine(),"found documented return type for %s that does not return anything",
                   qPrint(qualifiedName()));
  }
}
References argumentList(), Config_getBool, declArgumentList(), DefinitionMixin< MemberDefMutable >::docFile(), DefinitionMixin< MemberDefMutable >::docLine(), QCString::endsWith(), QCString::find(), DefinitionMixin< MemberDefMutable >::getLanguage(), hasDocumentation(), MemberDefImpl::IMPL::hasDocumentedParams, MemberDefImpl::IMPL::hasDocumentedReturnType, isConstructor(), isDeleted(), isDestructor(), isDocsForDefinition(), QCString::isEmpty(), isFunction(), isReference(), m_impl, qPrint(), qualifiedName(), SrcLangExt_Fortran, stripTrailingReturn(), Doxygen::suppressDocWarnings, ArgumentList::trailingReturnType(), typeString(), and warn_doc_error().
Referenced by warnIfUndocumented(), and writeDocumentation().
warnIfUndocumentedParams() [2/2]
virtual void MemberDefImpl::warnIfUndocumentedParams () const [virtual]
Implements MemberDef.
writeDeclaration() [1/2]
void MemberDefImpl::writeDeclaration (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool inGroup, int indentLevel, const ClassDef * inheritFrom = 0, const QCString & inheritId = QCString()) const [virtual]
init.isEmpty() && initLines==0 && // one line initializer
Implements MemberDef.
Definition at line 2061 of file memberdef.cpp.
{
  //printf("> %s MemberDefImpl::writeDeclaration() inGroup=%d\n",qPrint(qualifiedName()),inGroup);
  // hide enum value, since they appear already as part of the enum, unless they
  // are explicitly grouped.
  if (!inGroup && m_impl->mtype==MemberType_EnumValue) return;
  const Definition *d=0;
  ASSERT (cd!=0 || nd!=0 || fd!=0 || gd!=0); // member should belong to something
  if (cd) d=cd; else if (nd) d=nd; else if (fd) d=fd; else d=gd;
  if (d==gd) // see bug 753608
  {
    if (getClassDef()) d = getClassDef();
    else if (getNamespaceDef()) d = getNamespaceDef();
    else if (getFileDef()) d = getFileDef();
  }
  QCString cname = d->name();
  QCString cdname = d->displayName();
  QCString cfname = getOutputFileBase();
  // search for the last anonymous scope in the member type
  ClassDefMutable *annoClassDef=toClassDefMutable(getClassDefOfAnonymousType());
  ol.startMemberDeclaration();
  // start a new member declaration
  bool isAnonType = annoClassDef || m_impl->annMemb || m_impl->annEnumType;
  ol.startMemberItem(anchor(),
                     isAnonType ? 1 : !m_impl->tArgList.empty() ? 3 : 0,
                     inheritId
                    );
  // If there is no detailed description we need to write the anchor here.
  bool detailsVisible = hasDetailedDescription();
  bool writeAnchor = (inGroup || getGroupDef()==0) && // only write anchors for member that have no details and are
                     !detailsVisible && !m_impl->annMemb; // rendered inside the group page or are not grouped at all
  if (writeAnchor)
  {
    QCString doxyArgs=argsString();
    QCString doxyName=name();
    if (!cname.isEmpty())
    {
      doxyName.prepend(cdname+getLanguageSpecificSeparator(getLanguage()));
    }
    ol.startDoxyAnchor(cfname,cname,anchor(),doxyName,doxyArgs);
  }
  if (!detailsVisible)
  {
    ol.pushGeneratorState();
    ol.disable(OutputGenerator::Man);
    ol.disable(OutputGenerator::Latex);
    ol.disable(OutputGenerator::Docbook);
    ol.docify("\n");
    ol.popGeneratorState();
  }
  if (annoClassDef || m_impl->annMemb)
  {
    int j;
    for (j=0;j<indentLevel;j++)
    {
      ol.writeNonBreakableSpace(3);
    }
  }
  // *** write template lists
  if (m_impl->tArgList.hasParameters() && getLanguage()==SrcLangExt_Cpp)
  {
    if (!isAnonType) ol.startMemberTemplateParams();
    _writeTemplatePrefix(ol,d,m_impl->tArgList);
    if (!isAnonType) ol.endMemberTemplateParams(anchor(),inheritId);
  }
  // *** write type
  QCString ltype(m_impl->type);
  if (isTypedef() && getLanguage() != SrcLangExt_Slice)
  {
    ltype.prepend("typedef ");
  }
  if (isTypeAlias())
  {
    ltype="using";
  }
  // strip 'friend' keyword from ltype
  ltype.stripPrefix("friend ");
  static const reg::Ex r(R"(@\d+)");
  reg::Match match;
  std::string stype = ltype.str();
  bool endAnonScopeNeeded=FALSE;
  if (reg::search(stype,match,r)) // member has an anonymous type
  {
    int i = static_cast<int>(match.position());
    int l = static_cast<int>(match.length());
    //printf("annoClassDef=%p annMemb=%p scopeName='%s' anonymous='%s'\n",
    // annoClassDef,annMemb,qPrint(cname),qPrint(ltype.mid(i,l)));
    if (annoClassDef) // type is an anonymous compound
    {
      int ir=i+l;
      //printf("<<<<<<<<<<<<<<\n");
      ol.startAnonTypeScope(indentLevel);
      annoClassDef->writeDeclaration(ol,m_impl->annMemb,inGroup,indentLevel+1,inheritedFrom,inheritId);
      //printf(">>>>>>>>>>>>>> startMemberItem(2)\n");
      ol.startMemberItem(anchor(),2,inheritId);
      int j;
      for (j=0;j< indentLevel;j++)
      {
        ol.writeNonBreakableSpace(3);
      }
      QCString varName=ltype.right(ltype.length()-ir).stripWhiteSpace();
      //printf(">>>>>> ltype='%s' varName='%s'\n",qPrint(ltype),qPrint(varName));
      ol.docify("}");
      if (varName.isEmpty() && isAnonymous())
      {
        ol.docify(";");
      }
      else if (!varName.isEmpty() && (varName.at(0)=='*' || varName.at(0)=='&'))
      {
        ol.docify(" ");
        ol.docify(varName);
      }
      endAnonScopeNeeded=TRUE;
    }
    else
    {
      if (getAnonymousEnumType()) // type is an anonymous enum
      {
        linkifyText(TextGeneratorOLImpl(ol), // out
                    d, // scope
                    getBodyDef(), // fileScope
                    this, // self
                    ltype.left(i), // text
                    FALSE // autoBreak
                   );
        getAnonymousEnumType()->writeEnumDeclaration(ol,cd,nd,fd,gd);
        //ol+=*getAnonymousEnumType()->enumDecl();
        linkifyText(TextGeneratorOLImpl(ol),d,getFileDef(),this,ltype.right(ltype.length()-i-l),TRUE);
      }
      else
      {
        ltype = ltype.left(i) + " { ... } " + removeAnonymousScopes(ltype.right(ltype.length()-i-l));
        linkifyText(TextGeneratorOLImpl(ol), // out
                    d, // scope
                    getBodyDef(), // fileScope
                    this, // self
                    ltype, // text
                    FALSE // autoBreak
                   );
      }
    }
  }
  else if (ltype=="@") // rename type from enum values
  {
    ltype="";
  }
  else
  {
    if (isObjCMethod())
    {
      ltype.prepend("(");
      ltype.append(")");
    }
    linkifyText(TextGeneratorOLImpl(ol), // out
                d, // scope
                getBodyDef(), // fileScope
                this, // self
                ltype, // text
                FALSE // autoBreak
               );
  }
  bool htmlOn = ol.isEnabled(OutputGenerator::Html);
  if (htmlOn && !ltype.isEmpty())
  {
    ol.disable(OutputGenerator::Html);
  }
  if (!ltype.isEmpty()) ol.docify(" ");
  if (htmlOn)
  {
    ol.enable(OutputGenerator::Html);
  }
  if (m_impl->annMemb)
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputGenerator::Html);
    ol.writeNonBreakableSpace(3);
    ol.popGeneratorState();
  }
  else
  {
    ol.insertMemberAlign(m_impl->tArgList.hasParameters());
  }
  // *** write name
  if (!isAnonymous()) // hide anonymous stuff
  {
    bool extractPrivateVirtual = Config_getBool(EXTRACT_PRIV_VIRTUAL);
    bool extractStatic = Config_getBool(EXTRACT_STATIC);
    MemberDefMutable *annMemb = toMemberDefMutable(m_impl->annMemb);
    bool visibleIfPrivate = (protectionLevelVisible(protection()) ||
                             m_impl->mtype==MemberType_Friend ||
                             (m_impl->prot==Private &&
                                (m_impl->virt!=Normal || isOverride() || isFinal()) &&
                                extractPrivateVirtual && hasDocumentation()
                             ));
    //printf("Member name=`%s gd=%p md->groupDef=%p inGroup=%d isLinkable()=%d hasDocumentation=%d\n",qPrint(name()),gd,getGroupDef(),inGroup,isLinkable(),hasDocumentation());
    if (!name().isEmpty() && // name valid
        (hasDetailedDescription() || isReference()) && // has docs
        visibleIfPrivate &&
        !(isStatic() && getClassDef()==0 && !extractStatic) // hidden due to static-ness
       )
    {
      if (annMemb)
      {
        //printf("anchor=%s ann_anchor=%s\n",anchor(),annMemb->anchor());
        annMemb->writeLink(ol,
            annMemb->getClassDef(),
            annMemb->getNamespaceDef(),
            annMemb->getFileDef(),
            annMemb->getGroupDef());
        annMemb->setAnonymousUsed();
        setAnonymousUsed();
      }
      else
      {
        //printf("writeLink %s->%d\n",qPrint(name),hasDocumentation());
        const ClassDef *rcd = cd;
        if (isReference() && getClassDef()) rcd = getClassDef();
        writeLink(ol,rcd,nd,fd,gd);
      }
    }
    else if (isDocumentedFriendClass())
      // if the member is an undocumented friend declaration for some class,
      // then maybe we can link to the class
    {
      writeLink(ol,getClass(name()),0,0,0);
    }
    else
      // there is a brief member description and brief member
      // descriptions are enabled or there is no detailed description.
    {
      if (annMemb)
      {
        annMemb->setAnonymousUsed();
        setAnonymousUsed();
      }
      const ClassDef *rcd = cd;
      if (isReference() && getClassDef()) rcd = getClassDef();
      writeLink(ol,rcd,nd,fd,gd,TRUE);
    }
  }
  // *** write arguments
  if (!argsString().isEmpty() && !isObjCMethod())
  {
    if (!isDefine() && !isTypedef()) ol.writeString(" ");
    linkifyText(TextGeneratorOLImpl(ol), // out
                d, // scope
                getBodyDef(), // fileScope
                this, // self
                isDefine() ?
                   substitute(argsString(),",",", ") :
                isTypedef() ?
                   substitute(argsString(),")(",") (") :
                   argsString(), // text
                m_impl->annMemb, // autoBreak
                TRUE, // external
                FALSE, // keepSpaces
                indentLevel
               );
  }
  // *** write exceptions
  if (!excpString().isEmpty())
  {
    ol.writeString(" ");
    ol.docify(excpString());
  }
  // *** write bitfields
  if (!m_impl->bitfields.isEmpty()) // add bitfields
  {
    linkifyText(TextGeneratorOLImpl(ol),d,getBodyDef(),this,m_impl->bitfields);
  }
  else if (hasOneLineInitializer()
      //((maxInitLines>0 && userInitLines==-1) || userInitLines>0) // enabled by default or explicitly
          ) // add initializer
  {
    if (!isDefine())
    {
      //ol.writeString(" = ");
      ol.writeString(" ");
      linkifyText(TextGeneratorOLImpl(ol),d,getBodyDef(),this,m_impl->initializer.simplifyWhiteSpace());
    }
    else
    {
      ol.writeNonBreakableSpace(3);
      linkifyText(TextGeneratorOLImpl(ol),d,getBodyDef(),this,m_impl->initializer);
    }
  }
  else if (isTypeAlias()) // using template alias
  {
    ol.writeString(" = ");
    linkifyText(TextGeneratorOLImpl(ol),d,getBodyDef(),this,m_impl->type);
  }
  if ((isObjCMethod() || isObjCProperty()) && isImplementation())
  {
    ol.startTypewriter();
    ol.docify(" [implementation]");
    ol.endTypewriter();
  }
  bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
  if (isProperty() && (isSettable() || isGettable() ||
      isPrivateSettable() || isPrivateGettable() ||
      isProtectedSettable() || isProtectedGettable()))
  {
      ol.writeLatexSpacing();
      ol.startTypewriter();
      ol.docify(" [");
      StringVector sl;
      if (isGettable()) sl.push_back("get");
      if (isProtectedGettable()) sl.push_back("protected get");
      if (isSettable()) sl.push_back("set");
      if (isProtectedSettable()) sl.push_back("protected set");
      if (extractPrivate)
      {
        if (isPrivateGettable()) sl.push_back("private get");
        if (isPrivateSettable()) sl.push_back("private set");
      }
      bool first=true;
      for (const auto &s : sl)
      {
         if (!first)
         {
           ol.docify(", ");
         }
         first=false;
         ol.docify(s.c_str());
      }
      ol.docify("]");
      ol.endTypewriter();
  }
  if (isEvent() && (isAddable() || isRemovable() || isRaisable()))
  {
      ol.writeLatexSpacing();
      ol.startTypewriter();
      ol.docify(" [");
      StringVector sl;
      if (isAddable()) sl.push_back("add");
      if (isRemovable()) sl.push_back("remove");
      if (isRaisable()) sl.push_back("raise");
      bool first=true;
      for (const auto &s : sl)
      {
        if (!first)
        {
          ol.docify(", ");
        }
        first=false;
        ol.docify(s.c_str());
      }
      ol.docify("]");
      ol.endTypewriter();
  }
  if (writeAnchor)
  {
    ol.endDoxyAnchor(cfname,anchor());
  }
  //printf("endMember %s annoClassDef=%p annEnumType=%p\n",
  // qPrint(name()),annoClassDef,annEnumType);
  ol.endMemberItem();
  if (endAnonScopeNeeded)
  {
    ol.endAnonTypeScope(indentLevel);
  }
  // write brief description
  if (!briefDescription().isEmpty() &&
      Config_getBool(BRIEF_MEMBER_DESC)
     )
  {
    auto parser { createDocParser() };
    auto ast { validatingParseDoc(*parser.get(),
                                     briefFile(),briefLine(),
                                     getOuterScope()?getOuterScope():d,
                                     this,briefDescription(),TRUE,FALSE,
                                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startMemberDescription(anchor(),inheritId);
      ol.writeDoc(ast.get(),getOuterScope()?getOuterScope():d,this);
      if (detailsVisible) // add More.. link only when both brief and details are visible
      {
        ol.pushGeneratorState();
        ol.disableAllBut(OutputGenerator::Html);
        ol.docify(" ");
        MemberDefMutable *annMemb = NULL;
        if (!isAnonymous()) // hide anonymous stuff
        {
          annMemb = toMemberDefMutable(m_impl->annMemb);
        }
        if (annMemb)
        {
          ol.startTextLink(annMemb->getOutputFileBase(),annMemb->anchor());
        }
        else
        {
          ol.startTextLink(getOutputFileBase(),anchor());
        }
        ol.parseText(theTranslator->trMore());
        ol.endTextLink();
        ol.popGeneratorState();
      }
      // for RTF we need to add an extra empty paragraph
      ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::RTF);
      ol.startParagraph();
      ol.endParagraph();
      ol.popGeneratorState();
      ol.endMemberDescription();
    }
  }
  ol.endMemberDeclaration(anchor(),inheritId);
  warnIfUndocumented();
  //printf("< %s MemberDefImpl::writeDeclaration() inGroup=%d\n",qPrint(qualifiedName()),inGroup);
}
References _writeTemplatePrefix(), anchor(), MemberDef::anchor(), MemberDefImpl::IMPL::annEnumType, MemberDefImpl::IMPL::annMemb, QCString::append(), argsString(), ASSERT, QCString::at(), MemberDefImpl::IMPL::bitfields, briefDescription(), DefinitionMixin< MemberDefMutable >::briefFile(), DefinitionMixin< MemberDefMutable >::briefLine(), Config_getBool, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), Definition::displayName(), OutputGenerator::Docbook, OutputList::docify(), ArgumentList::empty(), OutputList::enable(), OutputList::endAnonTypeScope(), OutputList::endDoxyAnchor(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberItem(), OutputList::endMemberTemplateParams(), OutputList::endParagraph(), OutputList::endTextLink(), OutputList::endTypewriter(), excpString(), FALSE, getAnonymousEnumType(), DefinitionMixin< MemberDefMutable >::getBodyDef(), getClass(), getClassDef(), MemberDef::getClassDef(), getClassDefOfAnonymousType(), getFileDef(), MemberDef::getFileDef(), getGroupDef(), MemberDef::getGroupDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), getNamespaceDef(), MemberDef::getNamespaceDef(), DefinitionMixin< MemberDefMutable >::getOuterScope(), getOutputFileBase(), MemberDef::getOutputFileBase(), hasDetailedDescription(), hasDocumentation(), hasOneLineInitializer(), ArgumentList::hasParameters(), OutputGenerator::Html, if(), MemberDefImpl::IMPL::initializer, OutputList::insertMemberAlign(), isAddable(), DefinitionMixin< MemberDefMutable >::isAnonymous(), isDefine(), isDocumentedFriendClass(), QCString::isEmpty(), OutputList::isEnabled(), isEvent(), isFinal(), isGettable(), isImplementation(), isObjCMethod(), isObjCProperty(), isOverride(), isPrivateGettable(), isPrivateSettable(), isProperty(), isProtectedGettable(), isProtectedSettable(), isRaisable(), isReference(), isRemovable(), isSettable(), isStatic(), isTypeAlias(), isTypedef(), OutputGenerator::Latex, QCString::left(), QCString::length(), linkifyText(), m_impl, OutputGenerator::Man, reg::match(), MemberType_EnumValue, MemberType_Friend, MemberDefImpl::IMPL::mtype, DefinitionMixin< MemberDefMutable >::name(), Definition::name(), Normal, OutputList::parseText(), OutputList::popGeneratorState(), QCString::prepend(), Private, MemberDefImpl::IMPL::prot, protection(), protectionLevelVisible(), OutputList::pushGeneratorState(), r, removeAnonymousScopes(), QCString::right(), OutputGenerator::RTF, s, reg::search(), setAnonymousUsed(), MemberDefMutable::setAnonymousUsed(), QCString::simplifyWhiteSpace(), caseconvert::sl, SrcLangExt_Cpp, SrcLangExt_Slice, OutputList::startAnonTypeScope(), OutputList::startDoxyAnchor(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberItem(), OutputList::startMemberTemplateParams(), OutputList::startParagraph(), OutputList::startTextLink(), OutputList::startTypewriter(), QCString::str(), string, QCString::stripPrefix(), substitute(), MemberDefImpl::IMPL::tArgList, theTranslator, toClassDefMutable(), toMemberDefMutable(), Translator::trMore(), TRUE, MemberDefImpl::IMPL::type, validatingParseDoc(), MemberDefImpl::IMPL::virt, warnIfUndocumented(), ClassDefMutable::writeDeclaration(), OutputList::writeDoc(), MemberDef::writeEnumDeclaration(), OutputList::writeLatexSpacing(), writeLink(), MemberDefMutable::writeLink(), OutputList::writeNonBreakableSpace(), and OutputList::writeString().
writeDeclaration() [2/2]
virtual void MemberDefImpl::writeDeclaration (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool inGroup, int indentLevel, const ClassDef * inheritFrom = 0, const QCString & inheritId = QCString()) const [virtual]
Implements MemberDef.
writeDocumentation() [1/2]
void MemberDefImpl::writeDocumentation (const MemberList * ml, int memCount, int memTotal, OutputList & ol, const QCString & scName, const Definition * container, bool inGroup, bool showEnumValues = FALSE, bool showInline = FALSE) const [virtual]
Writes the `detailed documentation` section of this member to all active output formats.
Implements MemberDefMutable.
Definition at line 3231 of file memberdef.cpp.
{
  // if this member is in a group find the real scope name.
  bool hasParameterList = FALSE;
  //printf("MemberDefImpl::writeDocumentation(): name='%s' hasDocs='%d' containerType=%d inGroup=%d sectionLinkable=%d\n",
  // qPrint(name()),hasDocs,container->definitionType(),inGroup,hasDetailedDescription());
  //if (!hasDocs) return;
  //if (isEnumValue() && !showEnumValues) return;
  SrcLangExt lang = getLanguage();
  //printf("member=%s lang=%d\n",qPrint(name()),lang);
  bool optVhdl = lang==SrcLangExt_VHDL;
  QCString sep = getLanguageSpecificSeparator(lang,TRUE);
  QCString scopeName = scName;
  QCString memAnchor = anchor();
  QCString ciname = container->displayName();
  const Definition *scopedContainer = container; // see bug 753608
  if (container->definitionType()==TypeGroup)
  {
    if (getClassDef()) { scopeName=getClassDef()->displayName(); scopedContainer=getClassDef(); }
    else if (getNamespaceDef()) { scopeName=getNamespaceDef()->displayName(); scopedContainer=getNamespaceDef(); }
    else if (getFileDef()) { scopeName=getFileDef()->displayName(); scopedContainer=getFileDef(); }
    ciname = (toGroupDef(container))->groupTitle();
  }
  else if (container->definitionType()==TypeFile && getNamespaceDef() && getNamespaceDef()->isLinkable())
  { // member is in a namespace, but is written as part of the file documentation
    // as well, so we need to make sure its anchor is unique (it is not really used).
    memAnchor.prepend("file_");
  }
  QCString cname = container->name();
  QCString cfname = getOutputFileBase();
  // get member name
  QCString doxyName=name();
  // prepend scope if there is any. TODO: make this optional for C only docs
  if (!scopeName.isEmpty())
  {
    doxyName.prepend(scopeName+sep);
  }
  QCString doxyArgs=argsString();
  QCString ldef = definition();
  QCString title = name();
  //printf("member '%s' def='%s'\n",qPrint(name()),qPrint(ldef));
  if (isEnumerate())
  {
    if (title.at(0)=='@')
    {
      ldef = title = "anonymous enum";
      if (!m_impl->enumBaseType.isEmpty())
      {
        ldef+=" : "+m_impl->enumBaseType;
      }
    }
    else
    {
      if (lang==SrcLangExt_Cpp)
      {
        if (isEnumStruct()) ldef.prepend("struct ");
        else if (isStrong()) ldef.prepend("class ");
      }
      ldef.prepend("enum ");
      if (isSliceLocal())
      {
        ldef.prepend("local ");
      }
    }
  }
  else if (isEnumValue())
  {
    if (ldef.at(0)=='@')
    {
      ldef=ldef.mid(2);
    }
  }
  else if (isFunction() && !isObjCMethod())
  {
    title += "()";
  }
  if (lang == SrcLangExt_Slice)
  {
    // Remove the container scope from the member name.
    QCString prefix = scName + sep;
    int pos = ldef.findRev(prefix.data());
    if(pos != -1)
    {
      ldef.remove(pos, prefix.length());
    }
  }
  //----------------------------------------
  ol.pushGeneratorState();
  bool htmlEndLabelTable=FALSE;
  StringVector sl = getLabels(scopedContainer);
  static const reg::Ex r(R"(@\d+)");
  reg::Match match;
  std::string sdef = ldef.str();
  if ((isVariable() || isTypedef()) && reg::search(sdef,match,r))
  {
    // find enum type and insert it in the definition
    bool found=false;
    for (const auto &vmd : *ml)
    {
      if (vmd->isEnumerate() && match.str()==vmd->name())
      {
        ol.startDoxyAnchor(cfname,cname,memAnchor,doxyName,doxyArgs);
        ol.startMemberDoc(ciname,name(),memAnchor,name(),memCount,memTotal,showInline);
        std::string prefix = match.prefix().str();
        std::string suffix = match.suffix().str();
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,prefix.c_str());
        vmd->writeEnumDeclaration(ol,getClassDef(),getNamespaceDef(),getFileDef(),getGroupDef());
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,suffix.c_str());
        found=true;
        break;
      }
    }
    if (!found) // anonymous compound
    {
      //printf("Anonymous compound '%s'\n",qPrint(cname));
      ol.startDoxyAnchor(cfname,cname,memAnchor,doxyName,doxyArgs);
      ol.startMemberDoc(ciname,name(),memAnchor,"",memCount,memTotal,showInline);
      // search for the last anonymous compound name in the definition
      ol.startMemberDocName(isObjCMethod());
      if (reg::search(sdef,match,reAnonymous))
      {
        std::string prefix = match.prefix().str();
        std::string suffix = match.suffix().str();
        ol.docify(prefix.c_str());
        ol.docify(" { ... } ");
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,suffix.c_str());
      }
      else
      {
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,ldef);
      }
    }
  }
  else // not an enum value or anonymous compound
  {
    ol.startDoxyAnchor(cfname,cname,memAnchor,doxyName,doxyArgs);
    ol.startMemberDoc(ciname,name(),memAnchor,title,memCount,memTotal,showInline);
    if (!m_impl->metaData.isEmpty() && getLanguage()==SrcLangExt_Slice)
    {
      ol.startMemberDocPrefixItem();
      ol.docify(m_impl->metaData);
      ol.endMemberDocPrefixItem();
    }
    const ClassDef *cd=getClassDef();
    const NamespaceDef *nd=getNamespaceDef();
    if (!Config_getBool(HIDE_SCOPE_NAMES))
    {
      bool first=TRUE;
      if (!m_impl->defTmpArgLists.empty() && lang==SrcLangExt_Cpp)
        // definition has explicit template parameter declarations
      {
        for (const ArgumentList &tal : m_impl->defTmpArgLists)
        {
          if (!tal.empty())
          {
            if (!first) ol.docify(" ");
            ol.startMemberDocPrefixItem();
            _writeTemplatePrefix(ol,scopedContainer,tal);
            ol.endMemberDocPrefixItem();
          }
        }
      }
      else // definition gets it template parameters from its class
        // (since no definition was found)
      {
        if (cd && lang==SrcLangExt_Cpp && !isTemplateSpecialization())
        {
          for (const ArgumentList &tal : cd->getTemplateParameterLists())
          {
            if (!tal.empty())
            {
              if (!first) ol.docify(" ");
              ol.startMemberDocPrefixItem();
              _writeTemplatePrefix(ol,scopedContainer,tal,false);
              ol.endMemberDocPrefixItem();
            }
          }
        }
        if (m_impl->tArgList.hasParameters() && lang==SrcLangExt_Cpp) // function template prefix
        {
          ol.startMemberDocPrefixItem();
          _writeTemplatePrefix(ol,scopedContainer,m_impl->tArgList);
          ol.endMemberDocPrefixItem();
        }
      }
    }
    if (!sl.empty())
    {
      ol.pushGeneratorState();
      ol.disableAll();
      ol.enable(OutputGenerator::Html);
      ol.writeString("<table class=\"mlabels\">\n");
      ol.writeString(" <tr>\n");
      ol.writeString(" <td class=\"mlabels-left\">\n");
      ol.popGeneratorState();
      htmlEndLabelTable=TRUE;
    }
    ol.startMemberDocName(isObjCMethod());
    if (cd && cd->isObjectiveC())
    {
      // strip scope name
      int ep = ldef.find("::");
      if (ep!=-1)
      {
        int sp=ldef.findRev(' ',ep);
        if (sp!=-1)
        {
          ldef=ldef.left(sp+1)+ldef.mid(ep+2);
        } else {
          ldef=ldef.mid(ep+2);
        }
      }
      // strip keywords
      int dp = ldef.find(':');
      if (dp!=-1)
      {
        ldef=ldef.left(dp+1);
      }
      int dl=ldef.length();
      //printf("start >%s<\n",qPrint(ldef));
      int i=dl-1;
      while (i>=0 && (isId(ldef.at(i)) || ldef.at(i)==':')) i--;
      while (i>=0 && isspace(static_cast<uchar>(ldef.at(i)))) i--;
      if (i>0)
      {
        // insert braches around the type
        QCString tmp("("+ldef.left(i+1)+")"+ldef.mid(i+1));
        ldef=tmp;
      }
      //printf("end >%s< i=%d\n",qPrint(ldef),i);
      if (isStatic()) ldef.prepend("+ "); else ldef.prepend("- ");
    }
    if (optVhdl)
    {
      hasParameterList=VhdlDocGen::writeVHDLTypeDocumentation(this,scopedContainer,ol);
    }
    else if (lang==SrcLangExt_Slice)
    {
      // Eliminate the self-reference.
      int pos = ldef.findRev(' ');
      if (pos<0) pos=0;
      if (pos>0)
      {
        linkifyText(TextGeneratorOLImpl(ol),
                    scopedContainer,
                    getBodyDef(),
                    this,
                    ldef.left(pos)
                   );
      }
      ol.docify(ldef.mid(pos));
      const Definition *scope = cd;
      if (scope==0) scope = nd;
      hasParameterList=writeDefArgumentList(ol,scope,this);
    }
    else
    {
      linkifyText(TextGeneratorOLImpl(ol),
                  scopedContainer,
                  getBodyDef(),
                  this,
                  substitute(ldef,"::",sep)
                 );
      const Definition *scope = cd;
      if (scope==0) scope = nd;
      hasParameterList=writeDefArgumentList(ol,scope,this);
    }
    if (hasOneLineInitializer()) // add initializer
    {
      if (!isDefine())
      {
        //ol.docify(" = ");
        ol.docify(" ");
        QCString init = m_impl->initializer.simplifyWhiteSpace();
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,init);
      }
      else
      {
        ol.writeNonBreakableSpace(3);
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,m_impl->initializer);
      }
    }
    if (!excpString().isEmpty()) // add exception list
    {
      writeExceptionList(ol,cd,this);
      hasParameterList=true; // call endParameterList below
    }
  }
  ol.pushGeneratorState();
  ol.disable(OutputGenerator::Html);
  if (!sl.empty())
  {
    ol.startLabels();
    size_t count=0;
    for (const auto &s : sl)
    {
      count++;
      ol.writeLabel(s.c_str(),count==sl.size());
    }
    ol.endLabels();
  }
  ol.popGeneratorState();
  if (hasParameterList)
  {
    ol.endParameterList();
    ol.endMemberDoc(TRUE);
  }
  else
  {
    ol.endMemberDocName();
    ol.endMemberDoc(FALSE);
  }
  // for HTML write the labels here
  ol.pushGeneratorState();
  ol.disableAll();
  ol.enable(OutputGenerator::Html);
  if (htmlEndLabelTable)
  {
    ol.writeString(" </td>\n");
    ol.writeString(" <td class=\"mlabels-right\">\n");
    ol.startLabels();
    size_t count=0;
    for (const auto &s : sl)
    {
      count++;
      ol.writeLabel(s.c_str(),count==sl.size());
    }
    ol.endLabels();
    ol.writeString(" </td>\n");
    ol.writeString(" </tr>\n");
    ol.writeString("</table>\n");
  }
  ol.writeString("</div>");
  ol.popGeneratorState();
  ol.endDoxyAnchor(cfname,memAnchor);
  ol.startIndent();
  _writeGroupInclude(ol,inGroup);
  /* write multi-line initializer (if any) */
  if (hasMultiLineInitializer()) _writeMultiLineInitializer(ol,scopeName);
  /* write brief description */
  QCString brief = briefDescription();
  if (!brief.isEmpty() &&
      (Config_getBool(REPEAT_BRIEF) ||
       !Config_getBool(BRIEF_MEMBER_DESC)
      )
     )
  {
    ol.startParagraph();
    ol.generateDoc(briefFile(),briefLine(),
                scopedContainer,this,
                brief,FALSE,FALSE,
                QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    ol.endParagraph();
  }
  /* write detailed description */
  QCString detailed = documentation();
  if (!detailed.isEmpty() ||
      !inbodyDocumentation().isEmpty())
  {
    // write vhdl inline code with or without option INLINE_SOURCE
    if (optVhdl && VhdlDocGen::isMisc(this))
    {
      VhdlDocGen::writeSource(this,ol,cname);
      return;
    }
    else
    {
      ol.generateDoc(docFile(),docLine(),scopedContainer,this,detailed+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    if (!inbodyDocumentation().isEmpty())
    {
      ol.generateDoc(inbodyFile(),inbodyLine(),
                     scopedContainer,this,
                     inbodyDocumentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
  }
  else if (!brief.isEmpty() && (Config_getBool(REPEAT_BRIEF) || !Config_getBool(BRIEF_MEMBER_DESC)))
  {
    if (!inbodyDocumentation().isEmpty())
    {
      ol.generateDoc(inbodyFile(),inbodyLine(),scopedContainer,this,inbodyDocumentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
  }
  //printf("***** defArgList=%p name=%s docs=%s hasDocs=%d\n",
  // defArgList,
  // defArgList?defArgList->hasDocumentation():-1);
  const ArgumentList &docArgList = m_impl->templateMaster ?
                                   m_impl->templateMaster->argumentList() :
                                   m_impl->defArgList;
  if (docArgList.hasDocumentation())
  {
    QCString paramDocs;
    for (const Argument &a : docArgList)
    {
      if (a.hasDocumentation())
      {
        QCString docsWithoutDir = a.docs;
        QCString direction = extractDirection(docsWithoutDir);
        paramDocs+="@param"+direction+" "+a.name+" "+docsWithoutDir;
      }
    }
    // feed the result to the documentation parser
    ol.generateDoc(
        docFile(),docLine(),
        scopedContainer,
        this, // memberDef
        paramDocs, // docStr
        TRUE, // indexWords
        FALSE, // isExample
        QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT)
        );
  }
  _writeEnumValues(ol,scopedContainer,cfname,ciname,cname);
  _writeReimplements(ol);
  _writeReimplementedBy(ol);
  _writeCategoryRelation(ol);
  _writeExamples(ol);
  _writeTypeConstraints(ol);
  writeSourceDef(ol,cname);
  writeInlineCode(ol,cname);
  if (hasReferencesRelation()) writeSourceRefs(ol,cname);
  if (hasReferencedByRelation()) writeSourceReffedBy(ol,cname);
  _writeCallGraph(ol);
  _writeCallerGraph(ol);
  ol.endIndent();
  // enable LaTeX again
  //if (Config_getBool(EXTRACT_ALL) && !hasDocs) ol.enable(OutputGenerator::Latex);
  ol.popGeneratorState();
  warnIfUndocumentedParams();
}
References _writeCallerGraph(), _writeCallGraph(), _writeCategoryRelation(), _writeEnumValues(), _writeExamples(), _writeGroupInclude(), _writeMultiLineInitializer(), _writeReimplementedBy(), _writeReimplements(), _writeTemplatePrefix(), _writeTypeConstraints(), a, anchor(), argsString(), MemberDef::argumentList(), QCString::at(), briefDescription(), DefinitionMixin< MemberDefMutable >::briefFile(), DefinitionMixin< MemberDefMutable >::briefLine(), Config_getBool, QCString::data(), MemberDefImpl::IMPL::defArgList, definition(), Definition::definitionType(), MemberDefImpl::IMPL::defTmpArgLists, OutputList::disable(), OutputList::disableAll(), ClassDef::displayName(), Definition::displayName(), FileDef::displayName(), NamespaceDef::displayName(), DefinitionMixin< MemberDefMutable >::docFile(), OutputList::docify(), DefinitionMixin< MemberDefMutable >::docLine(), documentation(), ArgumentList::empty(), OutputList::enable(), OutputList::endDoxyAnchor(), OutputList::endIndent(), OutputList::endLabels(), OutputList::endMemberDoc(), OutputList::endMemberDocName(), OutputList::endMemberDocPrefixItem(), OutputList::endParagraph(), OutputList::endParameterList(), MemberDefImpl::IMPL::enumBaseType, excpString(), extractDirection(), FALSE, QCString::find(), QCString::findRev(), found, OutputList::generateDoc(), DefinitionMixin< MemberDefMutable >::getBodyDef(), getClassDef(), getFileDef(), getGroupDef(), getLabels(), DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), getNamespaceDef(), getOutputFileBase(), ClassDef::getTemplateParameterLists(), ArgumentList::hasDocumentation(), hasMultiLineInitializer(), hasOneLineInitializer(), ArgumentList::hasParameters(), hasReferencedByRelation(), hasReferencesRelation(), OutputGenerator::Html, DefinitionMixin< MemberDefMutable >::inbodyDocumentation(), DefinitionMixin< MemberDefMutable >::inbodyFile(), DefinitionMixin< MemberDefMutable >::inbodyLine(), Config::init(), MemberDefImpl::IMPL::initializer, isDefine(), QCString::isEmpty(), isEnumerate(), isEnumStruct(), isEnumValue(), isFunction(), isId(), NamespaceDef::isLinkable(), VhdlDocGen::isMisc(), isObjCMethod(), ClassDef::isObjectiveC(), isSliceLocal(), reg::isspace(), isStatic(), isStrong(), isTemplateSpecialization(), isTypedef(), isVariable(), QCString::left(), QCString::length(), linkifyText(), m_impl, reg::match(), MemberDefImpl::IMPL::metaData, QCString::mid(), DefinitionMixin< MemberDefMutable >::name(), Definition::name(), OutputList::popGeneratorState(), QCString::prepend(), OutputList::pushGeneratorState(), r, reAnonymous, QCString::remove(), s, reg::search(), QCString::simplifyWhiteSpace(), caseconvert::sl, SrcLangExt_Cpp, SrcLangExt_Slice, SrcLangExt_VHDL, OutputList::startDoxyAnchor(), OutputList::startIndent(), OutputList::startLabels(), OutputList::startMemberDoc(), OutputList::startMemberDocName(), OutputList::startMemberDocPrefixItem(), OutputList::startParagraph(), QCString::str(), string, substitute(), MemberDefImpl::IMPL::tArgList, MemberDefImpl::IMPL::templateMaster, toGroupDef(), TRUE, Definition::TypeFile, Definition::TypeGroup, warnIfUndocumentedParams(), writeDefArgumentList(), writeExceptionList(), DefinitionMixin< MemberDefMutable >::writeInlineCode(), OutputList::writeLabel(), OutputList::writeNonBreakableSpace(), VhdlDocGen::writeSource(), DefinitionMixin< MemberDefMutable >::writeSourceDef(), DefinitionMixin< MemberDefMutable >::writeSourceReffedBy(), DefinitionMixin< MemberDefMutable >::writeSourceRefs(), OutputList::writeString(), and VhdlDocGen::writeVHDLTypeDocumentation().
writeDocumentation() [2/2]
virtual void MemberDefImpl::writeDocumentation (const MemberList * ml, int memCount, int memTotal, OutputList & ol, const QCString & scopeName, const Definition * container, bool inGroup, bool showEnumValues = FALSE, bool showInline = FALSE) const [virtual]
Implements MemberDefMutable.
writeEnumDeclaration() [1/2]
void MemberDefImpl::writeEnumDeclaration (OutputList & typeDecl, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd) const [virtual]
Implements MemberDef.
Definition at line 4497 of file memberdef.cpp.
{
  int enumMemCount=0;
  uint numVisibleEnumValues=0;
  for (const auto &fmd : m_impl->enumFields)
  {
    if (fmd->isBriefSectionVisible()) numVisibleEnumValues++;
  }
  if (numVisibleEnumValues==0 && !isBriefSectionVisible())
  {
    return;
  }
  QCString n = name();
  int i=n.findRev("::");
  if (i!=-1) n=n.right(n.length()-i-2); // strip scope (TODO: is this needed?)
  if (n[0]!='@') // not an anonymous enum
  {
    if (isLinkableInProject() || hasDocumentedEnumValues())
    {
      //_writeTagData(compoundType);
      writeLink(typeDecl,cd,nd,fd,gd);
    }
    else
    {
      typeDecl.startBold();
      typeDecl.docify(n);
      typeDecl.endBold();
    }
    typeDecl.writeChar(' ');
  }
  if (!m_impl->enumBaseType.isEmpty())
  {
    typeDecl.writeChar(':');
    typeDecl.writeChar(' ');
    typeDecl.docify(m_impl->enumBaseType);
    typeDecl.writeChar(' ');
  }
  uint enumValuesPerLine = static_cast<uint>(Config_getInt(ENUM_VALUES_PER_LINE));
  if (numVisibleEnumValues>0 && enumValuesPerLine>0)
  {
    typeDecl.docify("{ ");
    auto it = m_impl->enumFields.begin();
    if (it!=m_impl->enumFields.end())
    {
      const MemberDef *fmd=*it;
      bool fmdVisible = fmd->isBriefSectionVisible();
      bool first=true;
      while (fmd)
      {
        if (fmdVisible)
        {
          if (!first)
          {
            typeDecl.writeString(", ");
          }
          /* in html we start a new line after a number of items */
          if (numVisibleEnumValues>enumValuesPerLine
              && (enumMemCount%enumValuesPerLine)==0
             )
          {
            typeDecl.pushGeneratorState();
            typeDecl.disableAllBut(OutputGenerator::Html);
            typeDecl.enable(OutputGenerator::Latex);
            typeDecl.enable(OutputGenerator::Docbook);
            typeDecl.lineBreak();
            typeDecl.disable(OutputGenerator::Latex);
            typeDecl.disable(OutputGenerator::Docbook);
            typeDecl.writeString("&#160;&#160;");
            typeDecl.popGeneratorState();
          }
          MemberDefMutable *fmdm = toMemberDefMutable(fmd);
          if (fmdm && fmd->hasDocumentation()) // enum value has docs
          {
            fmdm->writeLink(typeDecl,cd,nd,fd,gd);
          }
          else // no docs for this enum value
          {
            typeDecl.startBold();
            typeDecl.docify(fmd->name());
            typeDecl.endBold();
          }
          if (fmd->hasOneLineInitializer()) // enum value has initializer
          {
            //typeDecl.writeString(" = ");
            typeDecl.writeString(" ");
            typeDecl.parseText(fmd->initializer());
          }
          first=false;
        }
        bool prevVisible = fmdVisible;
        ++it;
        if (it!=m_impl->enumFields.end())
        {
          fmd=*it;
        }
        else
        {
          fmd=0;
        }
        if (prevVisible)
        {
          typeDecl.disable(OutputGenerator::Man);
          typeDecl.writeString("\n"); // to prevent too long lines in LaTeX
          typeDecl.enable(OutputGenerator::Man);
          enumMemCount++;
        }
      }
      if (numVisibleEnumValues>enumValuesPerLine)
      {
        typeDecl.pushGeneratorState();
        typeDecl.disableAllBut(OutputGenerator::Html);
        typeDecl.lineBreak();
        typeDecl.popGeneratorState();
      }
    }
    typeDecl.docify(" }");
  }
}
References MemberVector::begin(), Config_getInt, OutputList::disable(), OutputList::disableAllBut(), OutputGenerator::Docbook, OutputList::docify(), OutputList::enable(), MemberVector::end(), OutputList::endBold(), MemberDefImpl::IMPL::enumBaseType, MemberDefImpl::IMPL::enumFields, MemberDef::hasDocumentation(), hasDocumentedEnumValues(), MemberDef::hasOneLineInitializer(), OutputGenerator::Html, MemberDef::initializer(), isBriefSectionVisible(), MemberDef::isBriefSectionVisible(), QCString::isEmpty(), isLinkableInProject(), OutputGenerator::Latex, OutputList::lineBreak(), m_impl, OutputGenerator::Man, n, DefinitionMixin< MemberDefMutable >::name(), Definition::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startBold(), toMemberDefMutable(), OutputList::writeChar(), writeLink(), MemberDefMutable::writeLink(), and OutputList::writeString().
writeEnumDeclaration() [2/2]
virtual void MemberDefImpl::writeEnumDeclaration (OutputList & typeDecl, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd) const [virtual]
Implements MemberDef.
writeLink() [1/2]
void MemberDefImpl::writeLink (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool onlyText = FALSE) const [virtual]
Implements MemberDefMutable.
Definition at line 1769 of file memberdef.cpp.
{
  SrcLangExt lang = getLanguage();
  bool hideScopeNames = Config_getBool(HIDE_SCOPE_NAMES);
  QCString sep = getLanguageSpecificSeparator(lang,TRUE);
  QCString n = name();
  const ClassDef *classDef = getClassDef();
  const NamespaceDef *nspace = getNamespaceDef();
  if (!hideScopeNames)
  {
    if (m_impl->enumScope && m_impl->livesInsideEnum && getGroupDef()!=0)
    {
      n.prepend(m_impl->enumScope->displayName()+sep);
    }
    if (classDef && gd && !isRelated())
    {
      n.prepend(classDef->displayName()+sep);
    }
    else if (nspace && (gd || fd))
    {
      n.prepend(nspace->displayName()+sep);
    }
  }
  if (isObjCMethod())
  {
    if (isStatic()) ol.docify("+ "); else ol.docify("- ");
  }
  if (!onlyText && (isLinkable() || hasDetailedDescription())) // write link
  {
    if (m_impl->mtype==MemberType_EnumValue && getGroupDef()==0 && // enum value is not grouped
        getEnumScope() && getEnumScope()->getGroupDef()) // but its container is
    {
      const GroupDef *enumValGroup = getEnumScope()->getGroupDef();
      ol.writeObjectLink(enumValGroup->getReference(),
                         enumValGroup->getOutputFileBase(),
                         anchor(),n);
    }
    else
    {
      ol.writeObjectLink(getReference(),getOutputFileBase(),anchor(),n);
    }
  }
  else // write only text
  {
    ol.startBold();
    ol.docify(n);
    ol.endBold();
  }
}
References anchor(), Config_getBool, ClassDef::displayName(), MemberDef::displayName(), NamespaceDef::displayName(), OutputList::docify(), OutputList::endBold(), MemberDefImpl::IMPL::enumScope, getClassDef(), getEnumScope(), getGroupDef(), MemberDef::getGroupDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), getNamespaceDef(), getOutputFileBase(), GroupDef::getOutputFileBase(), getReference(), Definition::getReference(), hasDetailedDescription(), isLinkable(), isObjCMethod(), isRelated(), isStatic(), MemberDefImpl::IMPL::livesInsideEnum, m_impl, MemberType_EnumValue, MemberDefImpl::IMPL::mtype, n, DefinitionMixin< MemberDefMutable >::name(), OutputList::startBold(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDeclaration(), and writeEnumDeclaration().
writeLink() [2/2]
virtual void MemberDefImpl::writeLink (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool onlyText = FALSE) const [virtual]
Implements MemberDefMutable.
writeMemberDocSimple() [1/2]
void MemberDefImpl::writeMemberDocSimple (OutputList & ol, const Definition * container) const [virtual]
Implements MemberDefMutable.
Definition at line 3739 of file memberdef.cpp.
{
  Definition *scope = getOuterScope();
  QCString doxyName = name();
  QCString doxyArgs = argsString();
  QCString memAnchor = anchor();
  QCString cfname = getOutputFileBase();
  QCString cname;
  if (scope) cname = scope->name();
  if (doxyName.at(0)=='@')
  {
    doxyName="__unnamed__";
  }
  ClassDef *cd = m_impl->accessorClass;
  //printf("===> %s::anonymous: %s\n",qPrint(name()),cd?qPrint(cd->name()):"<none>");
  if (container && container->definitionType()==Definition::TypeClass &&
      !(toClassDef(container))->isJavaEnum())
  {
    ol.startInlineMemberType();
    ol.startDoxyAnchor(cfname,cname,memAnchor,doxyName,doxyArgs);
    QCString ts = fieldType();
    if (cd) // cd points to an anonymous struct pointed to by this member
      // so we add a link to it from the type column.
    {
      int i=0;
      const char *prefixes[] = { "struct ","union ","class ", 0 };
      const char **p = prefixes;
      while (*p)
      {
        int l=qstrlen(*p);
        if (ts.left(l)==*p)
        {
          ol.writeString(*p);
          i=l;
        }
        p++;
      }
      ol.writeObjectLink(cd->getReference(),
          cd->getOutputFileBase(),
          cd->anchor(),ts.mid(i));
    }
    else // use standard auto linking
    {
      linkifyText(TextGeneratorOLImpl(ol), // out
          scope, // scope
          getBodyDef(), // fileScope
          this, // self
          ts // text
          );
    }
    ol.endDoxyAnchor(cfname,memAnchor);
    ol.endInlineMemberType();
  }
  ol.startInlineMemberName();
  ol.docify(doxyName);
  if (isVariable() && !argsString().isEmpty() && !isObjCMethod())
  {
    linkifyText(TextGeneratorOLImpl(ol),getOuterScope(),getBodyDef(),this,argsString());
  }
  if (!m_impl->bitfields.isEmpty()) // add bitfields
  {
    linkifyText(TextGeneratorOLImpl(ol),getOuterScope(),getBodyDef(),this,m_impl->bitfields);
  }
  if (hasOneLineInitializer() && !isDefine())
  {
    ol.writeString(" ");
    linkifyText(TextGeneratorOLImpl(ol),getOuterScope(),getBodyDef(),this,m_impl->initializer.simplifyWhiteSpace());
  }
  ol.endInlineMemberName();
  ol.startInlineMemberDoc();
  QCString brief = briefDescription();
  QCString detailed = documentation();
  /* write brief description */
  if (!brief.isEmpty())
  {
    ol.generateDoc(briefFile(),briefLine(),
                getOuterScope()?getOuterScope():container,this,
                brief,FALSE,FALSE,
                QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
  }
  /* write detailed description */
  if (!detailed.isEmpty())
  {
    if (!brief.isEmpty())
    {
      ol.disable(OutputGenerator::Html);
      ol.lineBreak();
      ol.enable(OutputGenerator::Html);
    }
    ol.generateDoc(docFile(),docLine(),
                getOuterScope()?getOuterScope():container,this,
                detailed+"\n",FALSE,FALSE,
                QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
  }
  ol.endInlineMemberDoc();
}
References MemberDefImpl::IMPL::accessorClass, anchor(), ClassDef::anchor(), argsString(), QCString::at(), MemberDefImpl::IMPL::bitfields, briefDescription(), DefinitionMixin< MemberDefMutable >::briefFile(), DefinitionMixin< MemberDefMutable >::briefLine(), Config_getBool, Definition::definitionType(), OutputList::disable(), DefinitionMixin< MemberDefMutable >::docFile(), OutputList::docify(), DefinitionMixin< MemberDefMutable >::docLine(), documentation(), OutputList::enable(), OutputList::endDoxyAnchor(), OutputList::endInlineMemberDoc(), OutputList::endInlineMemberName(), OutputList::endInlineMemberType(), FALSE, fieldType(), OutputList::generateDoc(), DefinitionMixin< MemberDefMutable >::getBodyDef(), DefinitionMixin< MemberDefMutable >::getOuterScope(), getOutputFileBase(), ClassDef::getOutputFileBase(), ClassDef::getReference(), hasOneLineInitializer(), OutputGenerator::Html, MemberDefImpl::IMPL::initializer, isDefine(), QCString::isEmpty(), isObjCMethod(), isVariable(), QCString::left(), OutputList::lineBreak(), linkifyText(), m_impl, QCString::mid(), DefinitionMixin< MemberDefMutable >::name(), Definition::name(), p, qstrlen(), QCString::simplifyWhiteSpace(), OutputList::startDoxyAnchor(), OutputList::startInlineMemberDoc(), OutputList::startInlineMemberName(), OutputList::startInlineMemberType(), toClassDef(), TRUE, Definition::TypeClass, OutputList::writeObjectLink(), and OutputList::writeString().
writeMemberDocSimple() [2/2]
virtual void MemberDefImpl::writeMemberDocSimple (OutputList & ol, const Definition * container) const [virtual]
Implements MemberDefMutable.
writeTagFile() [1/2]
void MemberDefImpl::writeTagFile (TextStream & tagFile, bool useQualifiedName) const [virtual]
Implements MemberDefMutable.
Definition at line 4336 of file memberdef.cpp.
{
  if (!isLinkableInProject()) return;
  tagFile << " <member kind=\"";
  switch (m_impl->mtype)
  {
    case MemberType_Define: tagFile << "define"; break;
    case MemberType_EnumValue: tagFile << "enumvalue"; break;
    case MemberType_Property: tagFile << "property"; break;
    case MemberType_Event: tagFile << "event"; break;
    case MemberType_Variable: tagFile << "variable"; break;
    case MemberType_Typedef: tagFile << "typedef"; break;
    case MemberType_Enumeration: tagFile << "enumeration"; break;
    case MemberType_Function: tagFile << "function"; break;
    case MemberType_Signal: tagFile << "signal"; break;
    case MemberType_Friend: tagFile << "friend"; break;
    case MemberType_DCOP: tagFile << "dcop"; break;
    case MemberType_Slot: tagFile << "slot"; break;
    case MemberType_Interface: tagFile << "interface"; break;
    case MemberType_Service: tagFile << "service"; break;
    case MemberType_Sequence: tagFile << "sequence"; break;
    case MemberType_Dictionary: tagFile << "dictionary"; break;
  }
  if (m_impl->prot!=Public)
  {
    tagFile << "\" protection=\"";
    if (m_impl->prot==Protected) tagFile << "protected";
    else if (m_impl->prot==Package) tagFile << "package";
    else /* Private */ tagFile << "private";
  }
  if (m_impl->virt!=Normal)
  {
    tagFile << "\" virtualness=\"";
    if (m_impl->virt==Virtual) tagFile << "virtual";
    else /* Pure */ tagFile << "pure";
  }
  if (isStatic())
  {
    tagFile << "\" static=\"yes";
  }
  tagFile << "\">\n";
  if (typeString()!=QCString("@"))
  {
    tagFile << " <type>" << convertToXML(typeString()) << "</type>\n";
  }
  tagFile << " <name>" << convertToXML(useQualifiedName ? qualifiedName() : name()) << "</name>\n";
  tagFile << " <anchorfile>" << addHtmlExtensionIfMissing(getOutputFileBase()) << "</anchorfile>\n";
  tagFile << " <anchor>" << convertToXML(anchor()) << "</anchor>\n";
  QCString idStr = id();
  if (!idStr.isEmpty())
  {
    tagFile << " <clangid>" << convertToXML(idStr) << "</clangid>\n";
  }
  tagFile << " <arglist>" << convertToXML(argsString()) << "</arglist>\n";
  if (isStrong())
  {
    for (const auto &fmd : m_impl->enumFields)
    {
      if (!fmd->isReference())
      {
        tagFile << " <enumvalue file=\"" << convertToXML(addHtmlExtensionIfMissing(getOutputFileBase()));
        tagFile << "\" anchor=\"" << convertToXML(fmd->anchor());
        idStr = fmd->id();
        if (!idStr.isEmpty())
        {
          tagFile << "\" clangid=\"" << convertToXML(idStr);
        }
        tagFile << "\">" << convertToXML(fmd->name()) << "</enumvalue>\n";
      }
    }
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << " </member>\n";
}
References addHtmlExtensionIfMissing(), anchor(), argsString(), convertToXML(), MemberDefImpl::IMPL::enumFields, getOutputFileBase(), DefinitionMixin< MemberDefMutable >::id(), QCString::isEmpty(), isLinkableInProject(), isStatic(), isStrong(), m_impl, MemberType_DCOP, MemberType_Define, MemberType_Dictionary, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Sequence, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, MemberDefImpl::IMPL::mtype, DefinitionMixin< MemberDefMutable >::name(), Normal, Package, MemberDefImpl::IMPL::prot, Protected, Public, qualifiedName(), typeString(), MemberDefImpl::IMPL::virt, Virtual, and DefinitionMixin< MemberDefMutable >::writeDocAnchorsToTagFile().
writeTagFile() [2/2]
virtual void MemberDefImpl::writeTagFile (TextStream & , bool useQualifiedName) const [virtual]
Implements MemberDefMutable.
Member Data Documentation
m_impl
IMPL * MemberDefImpl::m_impl [private]
Definition at line 367 of file memberdef.cpp.
Referenced by _computeIsConstructor(), _computeIsDestructor(), _computeLinkableInProject(), _hasVisibleCallerGraph(), _hasVisibleCallGraph(), _writeCategoryRelation(), _writeExamples(), _writeMultiLineInitializer(), _writeReimplementedBy(), _writeTemplatePrefix(), _writeTypeConstraints(), accessorClass(), addExample(), anchor(), anonymousDeclShown(), argsString(), argumentList(), bitfieldString(), briefDescription(), cacheTypedefVal(), category(), categoryRelation(), copyArgumentNames(), createTemplateInstanceMember(), declaration(), declArgumentList(), deepCopy(), definition(), definitionTemplateParameterLists(), detectUndocumentedParams(), displayDefinition(), documentation(), enableCallerGraph(), enableCallGraph(), enableReferencedByRelation(), enableReferencesRelation(), enumBaseType(), enumFieldList(), excpString(), extraTypeChars(), fieldType(), fromAnonymousMember(), fromAnonymousScope(), getAnonymousEnumType(), getCachedResolvedTypedef(), getCachedTypedefTemplSpec(), getCachedTypedefVal(), getClassDef(), getClassDefOfAnonymousType(), getDeclColumn(), getDeclFileName(), getDeclLine(), getDeclType(), getEnumScope(), getExamples(), getFileDef(), getGroupAlias(), getGroupDef(), getGroupFileName(), getGroupHasDocs(), getGroupPri(), getGroupStartLine(), getLabels(), getMemberGroup(), getMemberGroupId(), getMemberSpecifiers(), getNamespaceDef(), getOutputFileBase(), getReadAccessor(), getSectionList(), getWriteAccessor(), hasCallerGraph(), hasCallGraph(), hasDetailedDescription(), hasDocumentation(), hasDocumentedEnumValues(), hasExamples(), hasMultiLineInitializer(), hasOneLineInitializer(), hasReferencedByRelation(), hasReferencesRelation(), incrementFlowKeyWordCount(), inheritsDocsFrom(), initializer(), initializerLines(), insertEnumField(), insertReimplementedBy(), invalidateCachedArgumentTypes(), invalidateTypedefValCache(), isAbstract(), isAddable(), isAssign(), isAttribute(), isBound(), isBriefSectionVisible(), isConstExpr(), isConstrained(), isCopy(), isDCOP(), isDefault(), isDefine(), isDelete(), isDeleted(), isDictionary(), isDocsForDefinition(), isEnumerate(), isEnumStruct(), isEnumValue(), isEvent(), isExplicit(), isExternal(), isFinal(), isForeign(), isFriend(), isFriendClass(), isFriendToHide(), isFunction(), isFunctionPtr(), isGettable(), isImplementation(), isInitonly(), isInline(), isLinkable(), isMaybeAmbiguous(), isMaybeDefault(), isMaybeVoid(), isMutable(), isNew(), isNoExcept(), isNonAtomic(), isOptional(), isOverride(), isPrivateGettable(), isPrivateSettable(), isProperty(), isProtectedGettable(), isProtectedSettable(), isPrototype(), isPublished(), isRaisable(), isReadable(), isReadonly(), isReference(), isReimplementedBy(), isRelated(), isRemovable(), isRequired(), isRetain(), isSealed(), isSequence(), isSettable(), isSignal(), isSliceLocal(), isSlot(), isStatic(), isStrong(), isStrongEnumValue(), isTemplateSpecialization(), isTransient(), isTypeAlias(), isTypedef(), isTypedefValCached(), isUNOProperty(), isUnretained(), isVariable(), isWeak(), isWritable(), livesInsideEnum(), makeForeign(), makeImplementationDetail(), makeRelated(), memberDeclaration(), MemberDefImpl(), memberDefinition(), memberType(), memberTypeName(), mergeMemberSpecifiers(), moveArgumentList(), moveDeclArgumentList(), moveTo(), numberOfFlowKeyWords(), protection(), qualifiedName(), reimplementedBy(), reimplements(), relatedAlso(), requiresClause(), resolveUnnamedParameters(), setAccessorType(), setAnchor(), setAnonymousEnumType(), setAnonymousUsed(), setArgsString(), setBitfields(), setCategory(), setCategoryRelation(), setDeclFile(), setDefinition(), setDefinitionTemplateParameterLists(), setDocsForDefinition(), setDocumentedEnumValues(), setEnumBaseType(), setEnumClassScope(), setEnumScope(), setExplicitExternal(), setFileDef(), setFromAnonymousMember(), setFromAnonymousScope(), setGroupAlias(), setGroupDef(), setInheritsDocsFrom(), setInitializer(), setMaxInitLines(), setMemberClass(), setMemberDeclaration(), setMemberDefinition(), setMemberGroup(), setMemberGroupId(), setMemberSpecifiers(), setMemberType(), setNamespace(), setProtection(), setPrototype(), setReadAccessor(), setReimplements(), setRelatedAlso(), setRequiresClause(), setSectionList(), setTagInfo(), setTemplateMaster(), setTemplateSpecialization(), setType(), setTypeConstraints(), setWriteAccessor(), templateArguments(), templateMaster(), typeConstraints(), typeString(), virtualness(), warnIfUndocumented(), warnIfUndocumentedParams(), writeDeclaration(), writeDocumentation(), writeEnumDeclaration(), writeLink(), writeMemberDocSimple(), writeTagFile(), and ~MemberDefImpl().
m_isConstructorCached
uchar MemberDefImpl::m_isConstructorCached [private]
Definition at line 369 of file memberdef.cpp.
Referenced by _computeIsConstructor(), isConstructor(), MemberDefImpl(), moveTo(), setEnumClassScope(), setFileDef(), and setMemberClass().
m_isDestructorCached
uchar MemberDefImpl::m_isDestructorCached [private]
Definition at line 370 of file memberdef.cpp.
Referenced by _computeIsDestructor(), isDestructor(), MemberDefImpl(), and setFileDef().
m_isLinkableCached
uchar MemberDefImpl::m_isLinkableCached [private]
Definition at line 368 of file memberdef.cpp.
Referenced by _computeLinkableInProject(), isLinkableInProject(), makeForeign(), makeRelated(), MemberDefImpl(), moveTo(), setBriefDescription(), setDocumentation(), setEnumClassScope(), setEnumScope(), setFileDef(), setGroupDef(), setHidden(), setInbodyDocumentation(), setMemberClass(), setMemberType(), setProtection(), and setTemplateMaster().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/memberdef.cpp
doxygen/src/memberdef.cpp