IncludeInfoListContext::Private Class Reference
Public Member Functions
Private (const IncludeInfoList &list, SrcLangExt lang)
Private (const IncludeInfoList &list, SrcLangExt lang)
Additional Inherited Members
Detailed Description
Definition at line 1676 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
IncludeInfoListContext::Private::Private (const IncludeInfoList & list, SrcLangExt lang) [inline]
Definition at line 1679 of file context.cpp.
    {
      for (const auto &ii : list)
      {
        append(IncludeInfoContext::alloc(&ii,lang));
      }
    }
References IncludeInfoContext::alloc(), and GenericNodeListContext::append().
Private() [2/2]
IncludeInfoListContext::Private::Private (const IncludeInfoList & list, SrcLangExt lang) [inline]
Definition at line 1679 of file context.cpp.
    {
      for (const auto &ii : list)
      {
        append(IncludeInfoContext::alloc(&ii,lang));
      }
    }
References IncludeInfoContext::alloc().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp