ClassDefAliasImpl Class Reference
Public Member Functions
ClassDefAliasImpl (const Definition *newScope, const ClassDef *cd)
virtual ~ClassDefAliasImpl ()
virtual DefType definitionType () const
const ClassDef * getCdAlias () const
virtual ClassDef * resolveAlias ()
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString getInstanceOutputFileBase () const
virtual QCString getSourceFileBase () const
virtual QCString getReference () const
virtual bool isReference () const
virtual bool isLocal () const
virtual ClassLinkedRefMap getClasses () const
virtual bool hasDocumentation () const
virtual bool hasDetailedDescription () const
virtual QCString collaborationGraphFileName () const
virtual QCString inheritanceGraphFileName () const
virtual QCString displayName (bool includeScope=TRUE) const
virtual CompoundType compoundType () const
virtual QCString compoundTypeString () const
virtual const BaseClassList & baseClasses () const
virtual const BaseClassList & subClasses () const
virtual const MemberNameInfoLinkedMap & memberNameInfoLinkedMap () const
virtual Protection protection () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool isVisibleInHierarchy () const
virtual bool visibleInParentsDeclList () const
virtual const ArgumentList & templateArguments () const
virtual FileDef * getFileDef () const
virtual const MemberDef * getMemberByName (const QCString &s) const
virtual int isBaseClass (const ClassDef *bcd, bool followInstances) const
virtual bool isSubClass (ClassDef *bcd, int level=0) const
virtual bool isAccessibleMember (const MemberDef *md) const
virtual const TemplateInstanceList & getTemplateInstances () const
virtual const ClassDef * templateMaster () const
virtual bool isTemplate () const
virtual const IncludeInfo * includeInfo () const
virtual const UsesClassList & usedImplementationClasses () const
virtual const UsesClassList & usedByImplementationClasses () const
virtual const ConstraintClassList & templateTypeConstraints () const
virtual bool isTemplateArgument () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual ArgumentLists getTemplateParameterLists () const
virtual QCString qualifiedNameWithTemplateParameters (const ArgumentLists *actualParams=0, uint *actualParamIndex=0) const
virtual bool isAbstract () const
virtual bool isObjectiveC () const
virtual bool isFortran () const
virtual bool isCSharp () const
virtual bool isFinal () const
virtual bool isSealed () const
virtual bool isPublished () const
virtual bool isExtension () const
virtual bool isForwardDeclared () const
virtual bool isInterface () const
virtual ClassDef * categoryOf () const
virtual QCString className () const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberGroupList & getMemberGroups () const
virtual const TemplateNameMap & getTemplateBaseClassNames () const
virtual bool isUsedOnly () const
virtual QCString anchor () const
virtual bool isEmbeddedInOuterScope () const
virtual bool isSimple () const
virtual const ClassDef * tagLessReference () const
virtual const MemberDef * isSmartPointer () const
virtual bool isJavaEnum () const
virtual QCString title () const
virtual QCString generatedFromFiles () const
virtual const FileList & usedFiles () const
virtual const ArgumentList & typeConstraints () const
virtual const ExampleList & getExamples () const
virtual bool hasExamples () const
virtual QCString getMemberListFileName () const
virtual bool subGrouping () const
virtual bool isSliceLocal () const
virtual bool hasNonReferenceSuperClass () const
virtual QCString requiresClause () const
virtual int countMembersIncludingGrouped (MemberListType lt, const ClassDef *inheritedFrom, bool additional) const
virtual int countInheritanceNodes () const
virtual int countMemberDeclarations (MemberListType lt, const ClassDef *inheritedFrom, int lt2, bool invert, bool showAlways, ClassDefSet &visitedClasses) const
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const
virtual ClassDef * insertTemplateInstance (const QCString &fileName, int startLine, int startColumn, const QCString &templSpec, bool &freshInstance) const
virtual void updateBaseClasses (const BaseClassList &)
virtual void updateSubClasses (const BaseClassList &)
ClassDefAliasImpl (const Definition *newScope, const ClassDef *cd)
virtual ~ClassDefAliasImpl ()
virtual DefType definitionType () const
const ClassDef * getCdAlias () const
virtual ClassDef * resolveAlias ()
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString getInstanceOutputFileBase () const
virtual QCString getSourceFileBase () const
virtual QCString getReference () const
virtual bool isReference () const
virtual bool isLocal () const
virtual ClassLinkedRefMap getClasses () const
virtual bool hasDocumentation () const
virtual bool hasDetailedDescription () const
virtual QCString collaborationGraphFileName () const
virtual QCString inheritanceGraphFileName () const
virtual QCString displayName (bool includeScope=TRUE) const
virtual CompoundType compoundType () const
virtual QCString compoundTypeString () const
virtual const BaseClassList & baseClasses () const
virtual const BaseClassList & subClasses () const
virtual const MemberNameInfoLinkedMap & memberNameInfoLinkedMap () const
virtual Protection protection () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool isVisibleInHierarchy () const
virtual bool visibleInParentsDeclList () const
virtual const ArgumentList & templateArguments () const
virtual FileDef * getFileDef () const
virtual const MemberDef * getMemberByName (const QCString &s) const
virtual int isBaseClass (const ClassDef *bcd, bool followInstances) const
virtual bool isSubClass (ClassDef *bcd, int level=0) const
virtual bool isAccessibleMember (const MemberDef *md) const
virtual const TemplateInstanceList & getTemplateInstances () const
virtual const ClassDef * templateMaster () const
virtual bool isTemplate () const
virtual const IncludeInfo * includeInfo () const
virtual const UsesClassList & usedImplementationClasses () const
virtual const UsesClassList & usedByImplementationClasses () const
virtual const ConstraintClassList & templateTypeConstraints () const
virtual bool isTemplateArgument () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual ArgumentLists getTemplateParameterLists () const
virtual QCString qualifiedNameWithTemplateParameters (const ArgumentLists *actualParams=0, uint *actualParamIndex=0) const
virtual bool isAbstract () const
virtual bool isObjectiveC () const
virtual bool isFortran () const
virtual bool isCSharp () const
virtual bool isFinal () const
virtual bool isSealed () const
virtual bool isPublished () const
virtual bool isExtension () const
virtual bool isForwardDeclared () const
virtual bool isInterface () const
virtual ClassDef * categoryOf () const
virtual QCString className () const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberGroupList & getMemberGroups () const
virtual const TemplateNameMap & getTemplateBaseClassNames () const
virtual bool isUsedOnly () const
virtual QCString anchor () const
virtual bool isEmbeddedInOuterScope () const
virtual bool isSimple () const
virtual const ClassDef * tagLessReference () const
virtual const MemberDef * isSmartPointer () const
virtual bool isJavaEnum () const
virtual QCString title () const
virtual QCString generatedFromFiles () const
virtual const FileList & usedFiles () const
virtual const ArgumentList & typeConstraints () const
virtual const ExampleList & getExamples () const
virtual bool hasExamples () const
virtual QCString getMemberListFileName () const
virtual bool subGrouping () const
virtual bool isSliceLocal () const
virtual bool hasNonReferenceSuperClass () const
virtual QCString requiresClause () const
virtual int countMembersIncludingGrouped (MemberListType lt, const ClassDef *inheritedFrom, bool additional) const
virtual int countInheritanceNodes () const
virtual int countMemberDeclarations (MemberListType lt, const ClassDef *inheritedFrom, int lt2, bool invert, bool showAlways, ClassDefSet &visitedClasses) const
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const
virtual ClassDef * insertTemplateInstance (const QCString &fileName, int startLine, int startColumn, const QCString &templSpec, bool &freshInstance) const
virtual void updateBaseClasses (const BaseClassList &)
virtual void updateSubClasses (const BaseClassList &)
Additional Inherited Members
Detailed Description
Definition at line 373 of file classdef.cpp.
Constructor & Destructor Documentation
ClassDefAliasImpl() [1/2]
ClassDefAliasImpl::ClassDefAliasImpl (const Definition * newScope, const ClassDef * cd) [inline]
Definition at line 376 of file classdef.cpp.
      : DefinitionAliasMixin(newScope,cd) { init(); }
References DefinitionAliasMixin< ClassDef >::init().
 ClassDefAliasImpl() [1/2]
virtual ClassDefAliasImpl::~ClassDefAliasImpl () [inline], [virtual]
Definition at line 378 of file classdef.cpp.
{ deinit(); }
References DefinitionAliasMixin< ClassDef >::deinit().
ClassDefAliasImpl() [2/2]
ClassDefAliasImpl::ClassDefAliasImpl (const Definition * newScope, const ClassDef * cd) [inline]
Definition at line 376 of file classdef.cpp.
      : DefinitionAliasMixin(newScope,cd) { init(); }
References DefinitionAliasMixin< ClassDef >::init().
 ClassDefAliasImpl() [2/2]
virtual ClassDefAliasImpl::~ClassDefAliasImpl () [inline], [virtual]
Definition at line 378 of file classdef.cpp.
{ deinit(); }
References DefinitionAliasMixin< ClassDef >::deinit().
Member Function Documentation
anchor() [1/2]
virtual QCString ClassDefAliasImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements ClassDef.
Definition at line 501 of file classdef.cpp.
    { return getCdAlias()->anchor(); }
References ClassDef::anchor(), and getCdAlias().
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString ClassDefAliasImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements ClassDef.
Definition at line 501 of file classdef.cpp.
    { return getCdAlias()->anchor(); }
References ClassDef::anchor(), and getCdAlias().
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
baseClasses() [1/2]
virtual const BaseClassList & ClassDefAliasImpl::baseClasses () const [inline], [virtual]
Returns the list of base classes from which this class directly inherits.
Implements ClassDef.
Definition at line 414 of file classdef.cpp.
    { return getCdAlias()->baseClasses(); }
References ClassDef::baseClasses(), and getCdAlias().
baseClasses() [2/2]
virtual const BaseClassList & ClassDefAliasImpl::baseClasses () const [inline], [virtual]
Returns the list of base classes from which this class directly inherits.
Implements ClassDef.
Definition at line 414 of file classdef.cpp.
    { return getCdAlias()->baseClasses(); }
References ClassDef::baseClasses(), and getCdAlias().
categoryOf() [1/2]
virtual ClassDef * ClassDefAliasImpl::categoryOf () const [inline], [virtual]
Returns the class of which this is a category (Objective-C only)
Implements ClassDef.
Definition at line 487 of file classdef.cpp.
    { return getCdAlias()->categoryOf(); }
References ClassDef::categoryOf(), and getCdAlias().
categoryOf() [2/2]
virtual ClassDef * ClassDefAliasImpl::categoryOf () const [inline], [virtual]
Returns the class of which this is a category (Objective-C only)
Implements ClassDef.
Definition at line 487 of file classdef.cpp.
    { return getCdAlias()->categoryOf(); }
References ClassDef::categoryOf(), and getCdAlias().
className() [1/2]
virtual QCString ClassDefAliasImpl::className () const [inline], [virtual]
Returns the name of the class including outer classes, but not including namespaces.
Implements ClassDef.
Definition at line 489 of file classdef.cpp.
    { return getCdAlias()->className(); }
References ClassDef::className(), and getCdAlias().
className() [2/2]
virtual QCString ClassDefAliasImpl::className () const [inline], [virtual]
Returns the name of the class including outer classes, but not including namespaces.
Implements ClassDef.
Definition at line 489 of file classdef.cpp.
    { return getCdAlias()->className(); }
References ClassDef::className(), and getCdAlias().
codeSymbolType() [1/2]
virtual CodeSymbolType ClassDefAliasImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 384 of file classdef.cpp.
    { return getCdAlias()->codeSymbolType(); }
References Definition::codeSymbolType(), and getCdAlias().
codeSymbolType() [2/2]
virtual CodeSymbolType ClassDefAliasImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 384 of file classdef.cpp.
    { return getCdAlias()->codeSymbolType(); }
References Definition::codeSymbolType(), and getCdAlias().
collaborationGraphFileName() [1/2]
virtual QCString ClassDefAliasImpl::collaborationGraphFileName () const [inline], [virtual]
returns the file name to use for the collaboration graph
Implements ClassDef.
Definition at line 404 of file classdef.cpp.
    { return getCdAlias()->collaborationGraphFileName(); }
References ClassDef::collaborationGraphFileName(), and getCdAlias().
collaborationGraphFileName() [2/2]
virtual QCString ClassDefAliasImpl::collaborationGraphFileName () const [inline], [virtual]
returns the file name to use for the collaboration graph
Implements ClassDef.
Definition at line 404 of file classdef.cpp.
    { return getCdAlias()->collaborationGraphFileName(); }
References ClassDef::collaborationGraphFileName(), and getCdAlias().
compoundType() [1/2]
virtual CompoundType ClassDefAliasImpl::compoundType () const [inline], [virtual]
Returns the type of compound this is, i.e. class/struct/union/..
Implements ClassDef.
Definition at line 410 of file classdef.cpp.
    { return getCdAlias()->compoundType(); }
References ClassDef::compoundType(), and getCdAlias().
compoundType() [2/2]
virtual CompoundType ClassDefAliasImpl::compoundType () const [inline], [virtual]
Returns the type of compound this is, i.e. class/struct/union/..
Implements ClassDef.
Definition at line 410 of file classdef.cpp.
    { return getCdAlias()->compoundType(); }
References ClassDef::compoundType(), and getCdAlias().
compoundTypeString() [1/2]
virtual QCString ClassDefAliasImpl::compoundTypeString () const [inline], [virtual]
Returns the type of compound as a string
Implements ClassDef.
Definition at line 412 of file classdef.cpp.
    { return getCdAlias()->compoundTypeString(); }
References ClassDef::compoundTypeString(), and getCdAlias().
compoundTypeString() [2/2]
virtual QCString ClassDefAliasImpl::compoundTypeString () const [inline], [virtual]
Returns the type of compound as a string
Implements ClassDef.
Definition at line 412 of file classdef.cpp.
    { return getCdAlias()->compoundTypeString(); }
References ClassDef::compoundTypeString(), and getCdAlias().
countInheritanceNodes() [1/2]
virtual int ClassDefAliasImpl::countInheritanceNodes () const [inline], [virtual]
Implements ClassDef.
Definition at line 538 of file classdef.cpp.
    { return getCdAlias()->countInheritanceNodes(); }
References ClassDef::countInheritanceNodes(), and getCdAlias().
countInheritanceNodes() [2/2]
virtual int ClassDefAliasImpl::countInheritanceNodes () const [inline], [virtual]
Implements ClassDef.
Definition at line 538 of file classdef.cpp.
    { return getCdAlias()->countInheritanceNodes(); }
References ClassDef::countInheritanceNodes(), and getCdAlias().
countMemberDeclarations() [1/2]
virtual int ClassDefAliasImpl::countMemberDeclarations (MemberListType lt, const ClassDef * inheritedFrom, int lt2, bool invert, bool showAlways, ClassDefSet & visitedClasses) const [inline], [virtual]
Implements ClassDef.
Definition at line 540 of file classdef.cpp.
    { return getCdAlias()->countMemberDeclarations(lt,inheritedFrom,lt2,invert,showAlways,visitedClasses); }
References ClassDef::countMemberDeclarations(), and getCdAlias().
countMemberDeclarations() [2/2]
virtual int ClassDefAliasImpl::countMemberDeclarations (MemberListType lt, const ClassDef * inheritedFrom, int lt2, bool invert, bool showAlways, ClassDefSet & visitedClasses) const [inline], [virtual]
Implements ClassDef.
Definition at line 540 of file classdef.cpp.
    { return getCdAlias()->countMemberDeclarations(lt,inheritedFrom,lt2,invert,showAlways,visitedClasses); }
References ClassDef::countMemberDeclarations(), and getCdAlias().
countMembersIncludingGrouped() [1/2]
virtual int ClassDefAliasImpl::countMembersIncludingGrouped (MemberListType lt, const ClassDef * inheritedFrom, bool additional) const [inline], [virtual]
Implements ClassDef.
Definition at line 536 of file classdef.cpp.
    { return getCdAlias()->countMembersIncludingGrouped(lt,inheritedFrom,additional); }
References ClassDef::countMembersIncludingGrouped(), and getCdAlias().
countMembersIncludingGrouped() [2/2]
virtual int ClassDefAliasImpl::countMembersIncludingGrouped (MemberListType lt, const ClassDef * inheritedFrom, bool additional) const [inline], [virtual]
Implements ClassDef.
Definition at line 536 of file classdef.cpp.
    { return getCdAlias()->countMembersIncludingGrouped(lt,inheritedFrom,additional); }
References ClassDef::countMembersIncludingGrouped(), and getCdAlias().
definitionType() [1/2]
virtual DefType ClassDefAliasImpl::definitionType () const [inline], [virtual]
Used for RTTI, this is a class
Implements ClassDef.
Definition at line 379 of file classdef.cpp.
{ return TypeClass; }
References Definition::TypeClass.
definitionType() [2/2]
virtual DefType ClassDefAliasImpl::definitionType () const [inline], [virtual]
Used for RTTI, this is a class
Implements ClassDef.
Definition at line 379 of file classdef.cpp.
{ return TypeClass; }
References Definition::TypeClass.
displayName() [1/2]
virtual QCString ClassDefAliasImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name as it is appears in the documentation
Implements ClassDef.
Definition at line 408 of file classdef.cpp.
    { return makeDisplayName(this,includeScope); }
References makeDisplayName().
displayName() [2/2]
virtual QCString ClassDefAliasImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name as it is appears in the documentation
Implements ClassDef.
Definition at line 408 of file classdef.cpp.
    { return makeDisplayName(this,includeScope); }
References makeDisplayName().
findInnerCompound() [1/2]
virtual const Definition * ClassDefAliasImpl::findInnerCompound (const QCString & name) const [inline], [virtual]
Returns the definition of a nested compound if available, or 0 otherwise.
Parameters
name The name of the nested compound
Reimplemented from DefinitionAliasMixin< ClassDef >.
Definition at line 460 of file classdef.cpp.
    { return getCdAlias()->findInnerCompound(name); }
References ClassDef::findInnerCompound(), getCdAlias(), and DefinitionAliasMixin< ClassDef >::name().
findInnerCompound() [2/2]
virtual const Definition * ClassDefAliasImpl::findInnerCompound (const QCString & name) const [inline], [virtual]
Returns the definition of a nested compound if available, or 0 otherwise.
Parameters
name The name of the nested compound
Reimplemented from DefinitionAliasMixin< ClassDef >.
Definition at line 460 of file classdef.cpp.
    { return getCdAlias()->findInnerCompound(name); }
References ClassDef::findInnerCompound(), getCdAlias(), and DefinitionAliasMixin< ClassDef >::name().
generatedFromFiles() [1/2]
virtual QCString ClassDefAliasImpl::generatedFromFiles () const [inline], [virtual]
Implements ClassDef.
Definition at line 515 of file classdef.cpp.
    { return getCdAlias()->generatedFromFiles(); }
References ClassDef::generatedFromFiles(), and getCdAlias().
generatedFromFiles() [2/2]
virtual QCString ClassDefAliasImpl::generatedFromFiles () const [inline], [virtual]
Implements ClassDef.
Definition at line 515 of file classdef.cpp.
    { return getCdAlias()->generatedFromFiles(); }
References ClassDef::generatedFromFiles(), and getCdAlias().
getCdAlias() [1/2]
const ClassDef * ClassDefAliasImpl::getCdAlias () const [inline]
Definition at line 381 of file classdef.cpp.
{ return toClassDef(getAlias()); }
References DefinitionAliasMixin< ClassDef >::getAlias(), and toClassDef().
Referenced by anchor(), baseClasses(), categoryOf(), className(), codeSymbolType(), collaborationGraphFileName(), compoundType(), compoundTypeString(), countInheritanceNodes(), countMemberDeclarations(), countMembersIncludingGrouped(), findInnerCompound(), generatedFromFiles(), getClasses(), getExamples(), getFileDef(), getInstanceOutputFileBase(), getMemberByName(), getMemberGroups(), getMemberList(), getMemberListFileName(), getMemberLists(), getOutputFileBase(), getReference(), getSourceFileBase(), getTemplateBaseClassNames(), getTemplateInstances(), getTemplateParameterLists(), hasDetailedDescription(), hasDocumentation(), hasExamples(), hasNonReferenceSuperClass(), includeInfo(), inheritanceGraphFileName(), insertTemplateInstance(), isAbstract(), isAccessibleMember(), isBaseClass(), isCSharp(), isEmbeddedInOuterScope(), isExtension(), isFinal(), isFortran(), isForwardDeclared(), isInterface(), isJavaEnum(), isLinkable(), isLinkableInProject(), isLocal(), isObjectiveC(), isPublished(), isReference(), isSealed(), isSimple(), isSliceLocal(), isSmartPointer(), isSubClass(), isTemplate(), isTemplateArgument(), isUsedOnly(), isVisibleInHierarchy(), memberNameInfoLinkedMap(), protection(), requiresClause(), resolveAlias(), subClasses(), subGrouping(), tagLessReference(), templateArguments(), templateMaster(), templateTypeConstraints(), title(), typeConstraints(), usedByImplementationClasses(), usedFiles(), usedImplementationClasses(), visibleInParentsDeclList(), and writeDeclarationLink().
getCdAlias() [2/2]
const ClassDef * ClassDefAliasImpl::getCdAlias () const [inline]
Definition at line 381 of file classdef.cpp.
{ return toClassDef(getAlias()); }
References DefinitionAliasMixin< ClassDef >::getAlias(), and toClassDef().
getClasses() [1/2]
virtual ClassLinkedRefMap ClassDefAliasImpl::getClasses () const [inline], [virtual]
returns the classes nested into this class
Implements ClassDef.
Definition at line 398 of file classdef.cpp.
    { return getCdAlias()->getClasses(); }
References getCdAlias(), and ClassDef::getClasses().
getClasses() [2/2]
virtual ClassLinkedRefMap ClassDefAliasImpl::getClasses () const [inline], [virtual]
returns the classes nested into this class
Implements ClassDef.
Definition at line 398 of file classdef.cpp.
    { return getCdAlias()->getClasses(); }
References getCdAlias(), and ClassDef::getClasses().
getExamples() [1/2]
virtual const ExampleList & ClassDefAliasImpl::getExamples () const [inline], [virtual]
Implements ClassDef.
Definition at line 521 of file classdef.cpp.
    { return getCdAlias()->getExamples(); }
References getCdAlias(), and ClassDef::getExamples().
getExamples() [2/2]
virtual const ExampleList & ClassDefAliasImpl::getExamples () const [inline], [virtual]
Implements ClassDef.
Definition at line 521 of file classdef.cpp.
    { return getCdAlias()->getExamples(); }
References getCdAlias(), and ClassDef::getExamples().
getFileDef() [1/2]
virtual FileDef * ClassDefAliasImpl::getFileDef () const [inline], [virtual]
Returns the namespace this compound is in, or 0 if it has a global scope. Returns the file in which this compound's definition can be found. Should not return 0 (but it might be a good idea to check anyway).
Implements ClassDef.
Definition at line 434 of file classdef.cpp.
    { return getCdAlias()->getFileDef(); }
References getCdAlias(), and ClassDef::getFileDef().
getFileDef() [2/2]
virtual FileDef * ClassDefAliasImpl::getFileDef () const [inline], [virtual]
Returns the namespace this compound is in, or 0 if it has a global scope. Returns the file in which this compound's definition can be found. Should not return 0 (but it might be a good idea to check anyway).
Implements ClassDef.
Definition at line 434 of file classdef.cpp.
    { return getCdAlias()->getFileDef(); }
References getCdAlias(), and ClassDef::getFileDef().
getInstanceOutputFileBase() [1/2]
virtual QCString ClassDefAliasImpl::getInstanceOutputFileBase () const [inline], [virtual]
Implements ClassDef.
Definition at line 388 of file classdef.cpp.
    { return getCdAlias()->getInstanceOutputFileBase(); }
References getCdAlias(), and ClassDef::getInstanceOutputFileBase().
getInstanceOutputFileBase() [2/2]
virtual QCString ClassDefAliasImpl::getInstanceOutputFileBase () const [inline], [virtual]
Implements ClassDef.
Definition at line 388 of file classdef.cpp.
    { return getCdAlias()->getInstanceOutputFileBase(); }
References getCdAlias(), and ClassDef::getInstanceOutputFileBase().
getMemberByName() [1/2]
virtual const MemberDef * ClassDefAliasImpl::getMemberByName (const QCString &) const [inline], [virtual]
Returns the member with the given name
Implements ClassDef.
Definition at line 436 of file classdef.cpp.
    { return getCdAlias()->getMemberByName(s); }
References getCdAlias(), ClassDef::getMemberByName(), and s.
getMemberByName() [2/2]
virtual const MemberDef * ClassDefAliasImpl::getMemberByName (const QCString &) const [inline], [virtual]
Returns the member with the given name
Implements ClassDef.
Definition at line 436 of file classdef.cpp.
    { return getCdAlias()->getMemberByName(s); }
References getCdAlias(), ClassDef::getMemberByName(), and s.
getMemberGroups() [1/2]
virtual const MemberGroupList & ClassDefAliasImpl::getMemberGroups () const [inline], [virtual]
Returns the member groups defined for this class
Implements ClassDef.
Definition at line 495 of file classdef.cpp.
    { return getCdAlias()->getMemberGroups(); }
References getCdAlias(), and ClassDef::getMemberGroups().
getMemberGroups() [2/2]
virtual const MemberGroupList & ClassDefAliasImpl::getMemberGroups () const [inline], [virtual]
Returns the member groups defined for this class
Implements ClassDef.
Definition at line 495 of file classdef.cpp.
    { return getCdAlias()->getMemberGroups(); }
References getCdAlias(), and ClassDef::getMemberGroups().
getMemberList() [1/2]
virtual MemberList * ClassDefAliasImpl::getMemberList (MemberListType lt) const [inline], [virtual]
Returns the members in the list identified by lt
Implements ClassDef.
Definition at line 491 of file classdef.cpp.
    { return getCdAlias()->getMemberList(lt); }
References getCdAlias(), and ClassDef::getMemberList().
getMemberList() [2/2]
virtual MemberList * ClassDefAliasImpl::getMemberList (MemberListType lt) const [inline], [virtual]
Returns the members in the list identified by lt
Implements ClassDef.
Definition at line 491 of file classdef.cpp.
    { return getCdAlias()->getMemberList(lt); }
References getCdAlias(), and ClassDef::getMemberList().
getMemberListFileName() [1/2]
virtual QCString ClassDefAliasImpl::getMemberListFileName () const [inline], [virtual]
Implements ClassDef.
Definition at line 525 of file classdef.cpp.
    { return getCdAlias()->getMemberListFileName(); }
References getCdAlias(), and ClassDef::getMemberListFileName().
getMemberListFileName() [2/2]
virtual QCString ClassDefAliasImpl::getMemberListFileName () const [inline], [virtual]
Implements ClassDef.
Definition at line 525 of file classdef.cpp.
    { return getCdAlias()->getMemberListFileName(); }
References getCdAlias(), and ClassDef::getMemberListFileName().
getMemberLists() [1/2]
virtual const MemberLists & ClassDefAliasImpl::getMemberLists () const [inline], [virtual]
Returns the list containing the list of members sorted per type
Implements ClassDef.
Definition at line 493 of file classdef.cpp.
    { return getCdAlias()->getMemberLists(); }
References getCdAlias(), and ClassDef::getMemberLists().
getMemberLists() [2/2]
virtual const MemberLists & ClassDefAliasImpl::getMemberLists () const [inline], [virtual]
Returns the list containing the list of members sorted per type
Implements ClassDef.
Definition at line 493 of file classdef.cpp.
    { return getCdAlias()->getMemberLists(); }
References getCdAlias(), and ClassDef::getMemberLists().
getOutputFileBase() [1/2]
virtual QCString ClassDefAliasImpl::getOutputFileBase () const [inline], [virtual]
Returns the unique base name (without extension) of the class's file on disk
Implements ClassDef.
Definition at line 386 of file classdef.cpp.
    { return getCdAlias()->getOutputFileBase(); }
References getCdAlias(), and ClassDef::getOutputFileBase().
getOutputFileBase() [2/2]
virtual QCString ClassDefAliasImpl::getOutputFileBase () const [inline], [virtual]
Returns the unique base name (without extension) of the class's file on disk
Implements ClassDef.
Definition at line 386 of file classdef.cpp.
    { return getCdAlias()->getOutputFileBase(); }
References getCdAlias(), and ClassDef::getOutputFileBase().
getReference() [1/2]
virtual QCString ClassDefAliasImpl::getReference () const [inline], [virtual]
If this class originated from a tagfile, this will return the tag file reference
Reimplemented from DefinitionAliasMixin< ClassDef >.
Definition at line 392 of file classdef.cpp.
    { return getCdAlias()->getReference(); }
References getCdAlias(), and ClassDef::getReference().
getReference() [2/2]
virtual QCString ClassDefAliasImpl::getReference () const [inline], [virtual]
If this class originated from a tagfile, this will return the tag file reference
Reimplemented from DefinitionAliasMixin< ClassDef >.
Definition at line 392 of file classdef.cpp.
    { return getCdAlias()->getReference(); }
References getCdAlias(), and ClassDef::getReference().
getSourceFileBase() [1/2]
virtual QCString ClassDefAliasImpl::getSourceFileBase () const [inline], [virtual]
Returns the base name for the source code file
Reimplemented from DefinitionAliasMixin< ClassDef >.
Definition at line 390 of file classdef.cpp.
    { return getCdAlias()->getSourceFileBase(); }
References getCdAlias(), and ClassDef::getSourceFileBase().
getSourceFileBase() [2/2]
virtual QCString ClassDefAliasImpl::getSourceFileBase () const [inline], [virtual]
Returns the base name for the source code file
Reimplemented from DefinitionAliasMixin< ClassDef >.
Definition at line 390 of file classdef.cpp.
    { return getCdAlias()->getSourceFileBase(); }
References getCdAlias(), and ClassDef::getSourceFileBase().
getTemplateBaseClassNames() [1/2]
virtual const TemplateNameMap & ClassDefAliasImpl::getTemplateBaseClassNames () const [inline], [virtual]
Implements ClassDef.
Definition at line 497 of file classdef.cpp.
    { return getCdAlias()->getTemplateBaseClassNames(); }
References getCdAlias(), and ClassDef::getTemplateBaseClassNames().
getTemplateBaseClassNames() [2/2]
virtual const TemplateNameMap & ClassDefAliasImpl::getTemplateBaseClassNames () const [inline], [virtual]
Implements ClassDef.
Definition at line 497 of file classdef.cpp.
    { return getCdAlias()->getTemplateBaseClassNames(); }
References getCdAlias(), and ClassDef::getTemplateBaseClassNames().
getTemplateInstances() [1/2]
virtual const TemplateInstanceList & ClassDefAliasImpl::getTemplateInstances () const [inline], [virtual]
Returns a sorted dictionary with all template instances found for this template class. Returns 0 if not a template or no instances.
Implements ClassDef.
Definition at line 444 of file classdef.cpp.
    { return getCdAlias()->getTemplateInstances(); }
References getCdAlias(), and ClassDef::getTemplateInstances().
getTemplateInstances() [2/2]
virtual const TemplateInstanceList & ClassDefAliasImpl::getTemplateInstances () const [inline], [virtual]
Returns a sorted dictionary with all template instances found for this template class. Returns 0 if not a template or no instances.
Implements ClassDef.
Definition at line 444 of file classdef.cpp.
    { return getCdAlias()->getTemplateInstances(); }
References getCdAlias(), and ClassDef::getTemplateInstances().
getTemplateParameterLists() [1/2]
virtual ArgumentLists ClassDefAliasImpl::getTemplateParameterLists () const [inline], [virtual]
Returns the template parameter lists that form the template declaration of this class.
Example: template<class T> class TC {} = 0; will return a list with one ArgumentList containing one argument with type=`class` and name=`T`.
Implements ClassDef.
Definition at line 462 of file classdef.cpp.
    { return getCdAlias()->getTemplateParameterLists(); }
References getCdAlias(), and ClassDef::getTemplateParameterLists().
getTemplateParameterLists() [2/2]
virtual ArgumentLists ClassDefAliasImpl::getTemplateParameterLists () const [inline], [virtual]
Returns the template parameter lists that form the template declaration of this class.
Example: template<class T> class TC {} = 0; will return a list with one ArgumentList containing one argument with type=`class` and name=`T`.
Implements ClassDef.
Definition at line 462 of file classdef.cpp.
    { return getCdAlias()->getTemplateParameterLists(); }
References getCdAlias(), and ClassDef::getTemplateParameterLists().
hasDetailedDescription() [1/2]
virtual bool ClassDefAliasImpl::hasDetailedDescription () const [inline], [virtual]
returns TRUE if this class has a non-empty detailed description
Implements ClassDef.
Definition at line 402 of file classdef.cpp.
    { return getCdAlias()->hasDetailedDescription(); }
References getCdAlias(), and ClassDef::hasDetailedDescription().
hasDetailedDescription() [2/2]
virtual bool ClassDefAliasImpl::hasDetailedDescription () const [inline], [virtual]
returns TRUE if this class has a non-empty detailed description
Implements ClassDef.
Definition at line 402 of file classdef.cpp.
    { return getCdAlias()->hasDetailedDescription(); }
References getCdAlias(), and ClassDef::hasDetailedDescription().
hasDocumentation() [1/2]
virtual bool ClassDefAliasImpl::hasDocumentation () const [inline], [virtual]
returns TRUE if this class has documentation
Reimplemented from DefinitionAliasMixin< ClassDef >.
Definition at line 400 of file classdef.cpp.
    { return getCdAlias()->hasDocumentation(); }
References getCdAlias(), and ClassDef::hasDocumentation().
hasDocumentation() [2/2]
virtual bool ClassDefAliasImpl::hasDocumentation () const [inline], [virtual]
returns TRUE if this class has documentation
Reimplemented from DefinitionAliasMixin< ClassDef >.
Definition at line 400 of file classdef.cpp.
    { return getCdAlias()->hasDocumentation(); }
References getCdAlias(), and ClassDef::hasDocumentation().
hasExamples() [1/2]
virtual bool ClassDefAliasImpl::hasExamples () const [inline], [virtual]
Implements ClassDef.
Definition at line 523 of file classdef.cpp.
    { return getCdAlias()->hasExamples(); }
References getCdAlias(), and ClassDef::hasExamples().
hasExamples() [2/2]
virtual bool ClassDefAliasImpl::hasExamples () const [inline], [virtual]
Implements ClassDef.
Definition at line 523 of file classdef.cpp.
    { return getCdAlias()->hasExamples(); }
References getCdAlias(), and ClassDef::hasExamples().
hasNonReferenceSuperClass() [1/2]
virtual bool ClassDefAliasImpl::hasNonReferenceSuperClass () const [inline], [virtual]
Implements ClassDef.
Definition at line 531 of file classdef.cpp.
    { return getCdAlias()->hasNonReferenceSuperClass(); }
References getCdAlias(), and ClassDef::hasNonReferenceSuperClass().
hasNonReferenceSuperClass() [2/2]
virtual bool ClassDefAliasImpl::hasNonReferenceSuperClass () const [inline], [virtual]
Implements ClassDef.
Definition at line 531 of file classdef.cpp.
    { return getCdAlias()->hasNonReferenceSuperClass(); }
References getCdAlias(), and ClassDef::hasNonReferenceSuperClass().
includeInfo() [1/2]
virtual const IncludeInfo * ClassDefAliasImpl::includeInfo () const [inline], [virtual]
Implements ClassDef.
Definition at line 450 of file classdef.cpp.
    { return getCdAlias()->includeInfo(); }
References getCdAlias(), and ClassDef::includeInfo().
includeInfo() [2/2]
virtual const IncludeInfo * ClassDefAliasImpl::includeInfo () const [inline], [virtual]
Implements ClassDef.
Definition at line 450 of file classdef.cpp.
    { return getCdAlias()->includeInfo(); }
References getCdAlias(), and ClassDef::includeInfo().
inheritanceGraphFileName() [1/2]
virtual QCString ClassDefAliasImpl::inheritanceGraphFileName () const [inline], [virtual]
returns the file name to use for the inheritance graph
Implements ClassDef.
Definition at line 406 of file classdef.cpp.
    { return getCdAlias()->inheritanceGraphFileName(); }
References getCdAlias(), and ClassDef::inheritanceGraphFileName().
inheritanceGraphFileName() [2/2]
virtual QCString ClassDefAliasImpl::inheritanceGraphFileName () const [inline], [virtual]
returns the file name to use for the inheritance graph
Implements ClassDef.
Definition at line 406 of file classdef.cpp.
    { return getCdAlias()->inheritanceGraphFileName(); }
References getCdAlias(), and ClassDef::inheritanceGraphFileName().
insertTemplateInstance() [1/2]
virtual ClassDef * ClassDefAliasImpl::insertTemplateInstance (const QCString & fileName, int startLine, int startColumn, const QCString & templSpec, bool & freshInstance) const [inline], [virtual]
Implements ClassDef.
Definition at line 547 of file classdef.cpp.
    { return getCdAlias()->insertTemplateInstance(fileName,startLine,startColumn,templSpec,freshInstance); }
References getCdAlias(), and ClassDef::insertTemplateInstance().
insertTemplateInstance() [2/2]
virtual ClassDef * ClassDefAliasImpl::insertTemplateInstance (const QCString & fileName, int startLine, int startColumn, const QCString & templSpec, bool & freshInstance) const [inline], [virtual]
Implements ClassDef.
Definition at line 547 of file classdef.cpp.
    { return getCdAlias()->insertTemplateInstance(fileName,startLine,startColumn,templSpec,freshInstance); }
References getCdAlias(), and ClassDef::insertTemplateInstance().
isAbstract() [1/2]
virtual bool ClassDefAliasImpl::isAbstract () const [inline], [virtual]
Returns TRUE if there is at least one pure virtual member in this class.
Implements ClassDef.
Definition at line 467 of file classdef.cpp.
    { return getCdAlias()->isAbstract(); }
References getCdAlias(), and ClassDef::isAbstract().
isAbstract() [2/2]
virtual bool ClassDefAliasImpl::isAbstract () const [inline], [virtual]
Returns TRUE if there is at least one pure virtual member in this class.
Implements ClassDef.
Definition at line 467 of file classdef.cpp.
    { return getCdAlias()->isAbstract(); }
References getCdAlias(), and ClassDef::isAbstract().
isAccessibleMember() [1/2]
virtual bool ClassDefAliasImpl::isAccessibleMember (const MemberDef * md) const [inline], [virtual]
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
Implements ClassDef.
Definition at line 442 of file classdef.cpp.
    { return getCdAlias()->isAccessibleMember(md); }
References getCdAlias(), and ClassDef::isAccessibleMember().
isAccessibleMember() [2/2]
virtual bool ClassDefAliasImpl::isAccessibleMember (const MemberDef * md) const [inline], [virtual]
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
Implements ClassDef.
Definition at line 442 of file classdef.cpp.
    { return getCdAlias()->isAccessibleMember(md); }
References getCdAlias(), and ClassDef::isAccessibleMember().
isBaseClass() [1/2]
virtual int ClassDefAliasImpl::isBaseClass (const ClassDef * bcd, bool followInstances) const [inline], [virtual]
Returns TRUE iff bcd is a direct or indirect base class of this class. This function will recursively traverse all branches of the inheritance tree.
Implements ClassDef.
Definition at line 438 of file classdef.cpp.
    { return getCdAlias()->isBaseClass(bcd,followInstances); }
References getCdAlias(), and ClassDef::isBaseClass().
isBaseClass() [2/2]
virtual int ClassDefAliasImpl::isBaseClass (const ClassDef * bcd, bool followInstances) const [inline], [virtual]
Returns TRUE iff bcd is a direct or indirect base class of this class. This function will recursively traverse all branches of the inheritance tree.
Implements ClassDef.
Definition at line 438 of file classdef.cpp.
    { return getCdAlias()->isBaseClass(bcd,followInstances); }
References getCdAlias(), and ClassDef::isBaseClass().
isCSharp() [1/2]
virtual bool ClassDefAliasImpl::isCSharp () const [inline], [virtual]
Returns TRUE if this class is implemented in C#
Implements ClassDef.
Definition at line 473 of file classdef.cpp.
    { return getCdAlias()->isCSharp(); }
References getCdAlias(), and ClassDef::isCSharp().
isCSharp() [2/2]
virtual bool ClassDefAliasImpl::isCSharp () const [inline], [virtual]
Returns TRUE if this class is implemented in C#
Implements ClassDef.
Definition at line 473 of file classdef.cpp.
    { return getCdAlias()->isCSharp(); }
References getCdAlias(), and ClassDef::isCSharp().
isEmbeddedInOuterScope() [1/2]
virtual bool ClassDefAliasImpl::isEmbeddedInOuterScope () const [inline], [virtual]
Implements ClassDef.
Definition at line 503 of file classdef.cpp.
    { return getCdAlias()->isEmbeddedInOuterScope(); }
References getCdAlias(), and ClassDef::isEmbeddedInOuterScope().
isEmbeddedInOuterScope() [2/2]
virtual bool ClassDefAliasImpl::isEmbeddedInOuterScope () const [inline], [virtual]
Implements ClassDef.
Definition at line 503 of file classdef.cpp.
    { return getCdAlias()->isEmbeddedInOuterScope(); }
References getCdAlias(), and ClassDef::isEmbeddedInOuterScope().
isExtension() [1/2]
virtual bool ClassDefAliasImpl::isExtension () const [inline], [virtual]
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
Implements ClassDef.
Definition at line 481 of file classdef.cpp.
    { return getCdAlias()->isExtension(); }
References getCdAlias(), and ClassDef::isExtension().
isExtension() [2/2]
virtual bool ClassDefAliasImpl::isExtension () const [inline], [virtual]
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
Implements ClassDef.
Definition at line 481 of file classdef.cpp.
    { return getCdAlias()->isExtension(); }
References getCdAlias(), and ClassDef::isExtension().
isFinal() [1/2]
virtual bool ClassDefAliasImpl::isFinal () const [inline], [virtual]
Returns TRUE if this class is marked as final
Implements ClassDef.
Definition at line 475 of file classdef.cpp.
    { return getCdAlias()->isFinal(); }
References getCdAlias(), and ClassDef::isFinal().
isFinal() [2/2]
virtual bool ClassDefAliasImpl::isFinal () const [inline], [virtual]
Returns TRUE if this class is marked as final
Implements ClassDef.
Definition at line 475 of file classdef.cpp.
    { return getCdAlias()->isFinal(); }
References getCdAlias(), and ClassDef::isFinal().
isFortran() [1/2]
virtual bool ClassDefAliasImpl::isFortran () const [inline], [virtual]
Returns TRUE if this class is implemented in Fortran
Implements ClassDef.
Definition at line 471 of file classdef.cpp.
    { return getCdAlias()->isFortran(); }
References getCdAlias(), and ClassDef::isFortran().
isFortran() [2/2]
virtual bool ClassDefAliasImpl::isFortran () const [inline], [virtual]
Returns TRUE if this class is implemented in Fortran
Implements ClassDef.
Definition at line 471 of file classdef.cpp.
    { return getCdAlias()->isFortran(); }
References getCdAlias(), and ClassDef::isFortran().
isForwardDeclared() [1/2]
virtual bool ClassDefAliasImpl::isForwardDeclared () const [inline], [virtual]
Returns TRUE if this class represents a forward declaration of a template class
Implements ClassDef.
Definition at line 483 of file classdef.cpp.
    { return getCdAlias()->isForwardDeclared(); }
References getCdAlias(), and ClassDef::isForwardDeclared().
isForwardDeclared() [2/2]
virtual bool ClassDefAliasImpl::isForwardDeclared () const [inline], [virtual]
Returns TRUE if this class represents a forward declaration of a template class
Implements ClassDef.
Definition at line 483 of file classdef.cpp.
    { return getCdAlias()->isForwardDeclared(); }
References getCdAlias(), and ClassDef::isForwardDeclared().
isInterface() [1/2]
virtual bool ClassDefAliasImpl::isInterface () const [inline], [virtual]
Returns TRUE if this class represents an interface
Implements ClassDef.
Definition at line 485 of file classdef.cpp.
    { return getCdAlias()->isInterface(); }
References getCdAlias(), and ClassDef::isInterface().
isInterface() [2/2]
virtual bool ClassDefAliasImpl::isInterface () const [inline], [virtual]
Returns TRUE if this class represents an interface
Implements ClassDef.
Definition at line 485 of file classdef.cpp.
    { return getCdAlias()->isInterface(); }
References getCdAlias(), and ClassDef::isInterface().
isJavaEnum() [1/2]
virtual bool ClassDefAliasImpl::isJavaEnum () const [inline], [virtual]
Implements ClassDef.
Definition at line 511 of file classdef.cpp.
    { return getCdAlias()->isJavaEnum(); }
References getCdAlias(), and ClassDef::isJavaEnum().
isJavaEnum() [2/2]
virtual bool ClassDefAliasImpl::isJavaEnum () const [inline], [virtual]
Implements ClassDef.
Definition at line 511 of file classdef.cpp.
    { return getCdAlias()->isJavaEnum(); }
References getCdAlias(), and ClassDef::isJavaEnum().
isLinkable() [1/2]
virtual bool ClassDefAliasImpl::isLinkable () const [inline], [virtual]
return TRUE iff a link to this class is possible (either within this project, or as a cross-reference to another project).
Implements ClassDef.
Definition at line 424 of file classdef.cpp.
    { return getCdAlias()->isLinkable(); }
References getCdAlias(), and ClassDef::isLinkable().
isLinkable() [2/2]
virtual bool ClassDefAliasImpl::isLinkable () const [inline], [virtual]
return TRUE iff a link to this class is possible (either within this project, or as a cross-reference to another project).
Implements ClassDef.
Definition at line 424 of file classdef.cpp.
    { return getCdAlias()->isLinkable(); }
References getCdAlias(), and ClassDef::isLinkable().
isLinkableInProject() [1/2]
virtual bool ClassDefAliasImpl::isLinkableInProject () const [inline], [virtual]
returns TRUE iff a link is possible to this item within this project.
Implements ClassDef.
Definition at line 422 of file classdef.cpp.
    { return getCdAlias()->isLinkableInProject(); }
References getCdAlias(), and ClassDef::isLinkableInProject().
isLinkableInProject() [2/2]
virtual bool ClassDefAliasImpl::isLinkableInProject () const [inline], [virtual]
returns TRUE iff a link is possible to this item within this project.
Implements ClassDef.
Definition at line 422 of file classdef.cpp.
    { return getCdAlias()->isLinkableInProject(); }
References getCdAlias(), and ClassDef::isLinkableInProject().
isLocal() [1/2]
virtual bool ClassDefAliasImpl::isLocal () const [inline], [virtual]
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES
Implements ClassDef.
Definition at line 396 of file classdef.cpp.
    { return getCdAlias()->isLocal(); }
References getCdAlias(), and ClassDef::isLocal().
isLocal() [2/2]
virtual bool ClassDefAliasImpl::isLocal () const [inline], [virtual]
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES
Implements ClassDef.
Definition at line 396 of file classdef.cpp.
    { return getCdAlias()->isLocal(); }
References getCdAlias(), and ClassDef::isLocal().
isObjectiveC() [1/2]
virtual bool ClassDefAliasImpl::isObjectiveC () const [inline], [virtual]
Returns TRUE if this class is implemented in Objective-C
Implements ClassDef.
Definition at line 469 of file classdef.cpp.
    { return getCdAlias()->isObjectiveC(); }
References getCdAlias(), and ClassDef::isObjectiveC().
isObjectiveC() [2/2]
virtual bool ClassDefAliasImpl::isObjectiveC () const [inline], [virtual]
Returns TRUE if this class is implemented in Objective-C
Implements ClassDef.
Definition at line 469 of file classdef.cpp.
    { return getCdAlias()->isObjectiveC(); }
References getCdAlias(), and ClassDef::isObjectiveC().
isPublished() [1/2]
virtual bool ClassDefAliasImpl::isPublished () const [inline], [virtual]
Returns TRUE if this class is marked as published
Implements ClassDef.
Definition at line 479 of file classdef.cpp.
    { return getCdAlias()->isPublished(); }
References getCdAlias(), and ClassDef::isPublished().
isPublished() [2/2]
virtual bool ClassDefAliasImpl::isPublished () const [inline], [virtual]
Returns TRUE if this class is marked as published
Implements ClassDef.
Definition at line 479 of file classdef.cpp.
    { return getCdAlias()->isPublished(); }
References getCdAlias(), and ClassDef::isPublished().
isReference() [1/2]
virtual bool ClassDefAliasImpl::isReference () const [inline], [virtual]
Returns TRUE if this class is imported via a tag file
Reimplemented from DefinitionAliasMixin< ClassDef >.
Definition at line 394 of file classdef.cpp.
    { return getCdAlias()->isReference(); }
References getCdAlias(), and ClassDef::isReference().
isReference() [2/2]
virtual bool ClassDefAliasImpl::isReference () const [inline], [virtual]
Returns TRUE if this class is imported via a tag file
Reimplemented from DefinitionAliasMixin< ClassDef >.
Definition at line 394 of file classdef.cpp.
    { return getCdAlias()->isReference(); }
References getCdAlias(), and ClassDef::isReference().
isSealed() [1/2]
virtual bool ClassDefAliasImpl::isSealed () const [inline], [virtual]
Returns TRUE if this class is marked as sealed
Implements ClassDef.
Definition at line 477 of file classdef.cpp.
    { return getCdAlias()->isSealed(); }
References getCdAlias(), and ClassDef::isSealed().
isSealed() [2/2]
virtual bool ClassDefAliasImpl::isSealed () const [inline], [virtual]
Returns TRUE if this class is marked as sealed
Implements ClassDef.
Definition at line 477 of file classdef.cpp.
    { return getCdAlias()->isSealed(); }
References getCdAlias(), and ClassDef::isSealed().
isSimple() [1/2]
virtual bool ClassDefAliasImpl::isSimple () const [inline], [virtual]
Implements ClassDef.
Definition at line 505 of file classdef.cpp.
    { return getCdAlias()->isSimple(); }
References getCdAlias(), and ClassDef::isSimple().
isSimple() [2/2]
virtual bool ClassDefAliasImpl::isSimple () const [inline], [virtual]
Implements ClassDef.
Definition at line 505 of file classdef.cpp.
    { return getCdAlias()->isSimple(); }
References getCdAlias(), and ClassDef::isSimple().
isSliceLocal() [1/2]
virtual bool ClassDefAliasImpl::isSliceLocal () const [inline], [virtual]
Implements ClassDef.
Definition at line 529 of file classdef.cpp.
    { return getCdAlias()->isSliceLocal(); }
References getCdAlias(), and ClassDef::isSliceLocal().
isSliceLocal() [2/2]
virtual bool ClassDefAliasImpl::isSliceLocal () const [inline], [virtual]
Implements ClassDef.
Definition at line 529 of file classdef.cpp.
    { return getCdAlias()->isSliceLocal(); }
References getCdAlias(), and ClassDef::isSliceLocal().
isSmartPointer() [1/2]
virtual const MemberDef * ClassDefAliasImpl::isSmartPointer () const [inline], [virtual]
Implements ClassDef.
Definition at line 509 of file classdef.cpp.
    { return getCdAlias()->isSmartPointer(); }
References getCdAlias(), and ClassDef::isSmartPointer().
isSmartPointer() [2/2]
virtual const MemberDef * ClassDefAliasImpl::isSmartPointer () const [inline], [virtual]
Implements ClassDef.
Definition at line 509 of file classdef.cpp.
    { return getCdAlias()->isSmartPointer(); }
References getCdAlias(), and ClassDef::isSmartPointer().
isSubClass() [1/2]
virtual bool ClassDefAliasImpl::isSubClass (ClassDef * bcd, int level = 0) const [inline], [virtual]
Returns TRUE iff bcd is a direct or indirect sub class of this class.
Implements ClassDef.
Definition at line 440 of file classdef.cpp.
    { return getCdAlias()->isSubClass(bcd,level); }
References getCdAlias(), ClassDef::isSubClass(), and level.
isSubClass() [2/2]
virtual bool ClassDefAliasImpl::isSubClass (ClassDef * bcd, int level = 0) const [inline], [virtual]
Returns TRUE iff bcd is a direct or indirect sub class of this class.
Implements ClassDef.
Definition at line 440 of file classdef.cpp.
    { return getCdAlias()->isSubClass(bcd,level); }
References getCdAlias(), ClassDef::isSubClass(), and level.
isTemplate() [1/2]
virtual bool ClassDefAliasImpl::isTemplate () const [inline], [virtual]
Returns TRUE if this class is a template
Implements ClassDef.
Definition at line 448 of file classdef.cpp.
    { return getCdAlias()->isTemplate(); }
References getCdAlias(), and ClassDef::isTemplate().
isTemplate() [2/2]
virtual bool ClassDefAliasImpl::isTemplate () const [inline], [virtual]
Returns TRUE if this class is a template
Implements ClassDef.
Definition at line 448 of file classdef.cpp.
    { return getCdAlias()->isTemplate(); }
References getCdAlias(), and ClassDef::isTemplate().
isTemplateArgument() [1/2]
virtual bool ClassDefAliasImpl::isTemplateArgument () const [inline], [virtual]
Implements ClassDef.
Definition at line 458 of file classdef.cpp.
    { return getCdAlias()->isTemplateArgument(); }
References getCdAlias(), and ClassDef::isTemplateArgument().
isTemplateArgument() [2/2]
virtual bool ClassDefAliasImpl::isTemplateArgument () const [inline], [virtual]
Implements ClassDef.
Definition at line 458 of file classdef.cpp.
    { return getCdAlias()->isTemplateArgument(); }
References getCdAlias(), and ClassDef::isTemplateArgument().
isUsedOnly() [1/2]
virtual bool ClassDefAliasImpl::isUsedOnly () const [inline], [virtual]
Implements ClassDef.
Definition at line 499 of file classdef.cpp.
    { return getCdAlias()->isUsedOnly(); }
References getCdAlias(), and ClassDef::isUsedOnly().
isUsedOnly() [2/2]
virtual bool ClassDefAliasImpl::isUsedOnly () const [inline], [virtual]
Implements ClassDef.
Definition at line 499 of file classdef.cpp.
    { return getCdAlias()->isUsedOnly(); }
References getCdAlias(), and ClassDef::isUsedOnly().
isVisibleInHierarchy() [1/2]
virtual bool ClassDefAliasImpl::isVisibleInHierarchy () const [inline], [virtual]
the class is visible in a class diagram, or class hierarchy
Implements ClassDef.
Definition at line 426 of file classdef.cpp.
    { return getCdAlias()->isVisibleInHierarchy(); }
References getCdAlias(), and ClassDef::isVisibleInHierarchy().
isVisibleInHierarchy() [2/2]
virtual bool ClassDefAliasImpl::isVisibleInHierarchy () const [inline], [virtual]
the class is visible in a class diagram, or class hierarchy
Implements ClassDef.
Definition at line 426 of file classdef.cpp.
    { return getCdAlias()->isVisibleInHierarchy(); }
References getCdAlias(), and ClassDef::isVisibleInHierarchy().
memberNameInfoLinkedMap() [1/2]
virtual const MemberNameInfoLinkedMap & ClassDefAliasImpl::memberNameInfoLinkedMap () const [inline], [virtual]
Returns a dictionary of all members. This includes any inherited members. Members are sorted alphabetically.
Implements ClassDef.
Definition at line 418 of file classdef.cpp.
    { return getCdAlias()->memberNameInfoLinkedMap(); }
References getCdAlias(), and ClassDef::memberNameInfoLinkedMap().
memberNameInfoLinkedMap() [2/2]
virtual const MemberNameInfoLinkedMap & ClassDefAliasImpl::memberNameInfoLinkedMap () const [inline], [virtual]
Returns a dictionary of all members. This includes any inherited members. Members are sorted alphabetically.
Implements ClassDef.
Definition at line 418 of file classdef.cpp.
    { return getCdAlias()->memberNameInfoLinkedMap(); }
References getCdAlias(), and ClassDef::memberNameInfoLinkedMap().
protection() [1/2]
virtual Protection ClassDefAliasImpl::protection () const [inline], [virtual]
Return the protection level (Public,Protected,Private) in which this compound was found.
Implements ClassDef.
Definition at line 420 of file classdef.cpp.
    { return getCdAlias()->protection(); }
References getCdAlias(), and ClassDef::protection().
protection() [2/2]
virtual Protection ClassDefAliasImpl::protection () const [inline], [virtual]
Return the protection level (Public,Protected,Private) in which this compound was found.
Implements ClassDef.
Definition at line 420 of file classdef.cpp.
    { return getCdAlias()->protection(); }
References getCdAlias(), and ClassDef::protection().
qualifiedNameWithTemplateParameters() [1/2]
virtual QCString ClassDefAliasImpl::qualifiedNameWithTemplateParameters (const ArgumentLists * actualParams = 0, uint * actualParamIndex = 0) const [inline], [virtual]
Implements ClassDef.
Definition at line 464 of file classdef.cpp.
    { return makeQualifiedNameWithTemplateParameters(this,actualParams,actualParamIndex); }
References makeQualifiedNameWithTemplateParameters().
qualifiedNameWithTemplateParameters() [2/2]
virtual QCString ClassDefAliasImpl::qualifiedNameWithTemplateParameters (const ArgumentLists * actualParams = 0, uint * actualParamIndex = 0) const [inline], [virtual]
Implements ClassDef.
Definition at line 464 of file classdef.cpp.
    { return makeQualifiedNameWithTemplateParameters(this,actualParams,actualParamIndex); }
References makeQualifiedNameWithTemplateParameters().
requiresClause() [1/2]
virtual QCString ClassDefAliasImpl::requiresClause () const [inline], [virtual]
Implements ClassDef.
Definition at line 533 of file classdef.cpp.
    { return getCdAlias()->requiresClause(); }
References getCdAlias(), and ClassDef::requiresClause().
requiresClause() [2/2]
virtual QCString ClassDefAliasImpl::requiresClause () const [inline], [virtual]
Implements ClassDef.
Definition at line 533 of file classdef.cpp.
    { return getCdAlias()->requiresClause(); }
References getCdAlias(), and ClassDef::requiresClause().
resolveAlias() [1/2]
virtual ClassDef * ClassDefAliasImpl::resolveAlias () [inline], [virtual]
Definition at line 382 of file classdef.cpp.
{ return const_cast<ClassDef*>(getCdAlias()); }
References getCdAlias().
resolveAlias() [2/2]
virtual ClassDef * ClassDefAliasImpl::resolveAlias () [inline], [virtual]
Definition at line 382 of file classdef.cpp.
{ return const_cast<ClassDef*>(getCdAlias()); }
References getCdAlias().
subClasses() [1/2]
virtual const BaseClassList & ClassDefAliasImpl::subClasses () const [inline], [virtual]
Returns the list of sub classes that directly derive from this class
Implements ClassDef.
Definition at line 416 of file classdef.cpp.
    { return getCdAlias()->subClasses(); }
References getCdAlias(), and ClassDef::subClasses().
subClasses() [2/2]
virtual const BaseClassList & ClassDefAliasImpl::subClasses () const [inline], [virtual]
Returns the list of sub classes that directly derive from this class
Implements ClassDef.
Definition at line 416 of file classdef.cpp.
    { return getCdAlias()->subClasses(); }
References getCdAlias(), and ClassDef::subClasses().
subGrouping() [1/2]
virtual bool ClassDefAliasImpl::subGrouping () const [inline], [virtual]
Implements ClassDef.
Definition at line 527 of file classdef.cpp.
    { return getCdAlias()->subGrouping(); }
References getCdAlias(), and ClassDef::subGrouping().
subGrouping() [2/2]
virtual bool ClassDefAliasImpl::subGrouping () const [inline], [virtual]
Implements ClassDef.
Definition at line 527 of file classdef.cpp.
    { return getCdAlias()->subGrouping(); }
References getCdAlias(), and ClassDef::subGrouping().
tagLessReference() [1/2]
virtual const ClassDef * ClassDefAliasImpl::tagLessReference () const [inline], [virtual]
Implements ClassDef.
Definition at line 507 of file classdef.cpp.
    { return getCdAlias()->tagLessReference(); }
References getCdAlias(), and ClassDef::tagLessReference().
tagLessReference() [2/2]
virtual const ClassDef * ClassDefAliasImpl::tagLessReference () const [inline], [virtual]
Implements ClassDef.
Definition at line 507 of file classdef.cpp.
    { return getCdAlias()->tagLessReference(); }
References getCdAlias(), and ClassDef::tagLessReference().
templateArguments() [1/2]
virtual const ArgumentList & ClassDefAliasImpl::templateArguments () const [inline], [virtual]
Returns the template arguments of this class
Implements ClassDef.
Definition at line 430 of file classdef.cpp.
    { return getCdAlias()->templateArguments(); }
References getCdAlias(), and ClassDef::templateArguments().
templateArguments() [2/2]
virtual const ArgumentList & ClassDefAliasImpl::templateArguments () const [inline], [virtual]
Returns the template arguments of this class
Implements ClassDef.
Definition at line 430 of file classdef.cpp.
    { return getCdAlias()->templateArguments(); }
References getCdAlias(), and ClassDef::templateArguments().
templateMaster() [1/2]
virtual const ClassDef * ClassDefAliasImpl::templateMaster () const [inline], [virtual]
Returns the template master of which this class is an instance. Returns 0 if not applicable.
Implements ClassDef.
Definition at line 446 of file classdef.cpp.
    { return getCdAlias()->templateMaster(); }
References getCdAlias(), and ClassDef::templateMaster().
templateMaster() [2/2]
virtual const ClassDef * ClassDefAliasImpl::templateMaster () const [inline], [virtual]
Returns the template master of which this class is an instance. Returns 0 if not applicable.
Implements ClassDef.
Definition at line 446 of file classdef.cpp.
    { return getCdAlias()->templateMaster(); }
References getCdAlias(), and ClassDef::templateMaster().
templateTypeConstraints() [1/2]
virtual const ConstraintClassList & ClassDefAliasImpl::templateTypeConstraints () const [inline], [virtual]
Implements ClassDef.
Definition at line 456 of file classdef.cpp.
    { return getCdAlias()->templateTypeConstraints(); }
References getCdAlias(), and ClassDef::templateTypeConstraints().
templateTypeConstraints() [2/2]
virtual const ConstraintClassList & ClassDefAliasImpl::templateTypeConstraints () const [inline], [virtual]
Implements ClassDef.
Definition at line 456 of file classdef.cpp.
    { return getCdAlias()->templateTypeConstraints(); }
References getCdAlias(), and ClassDef::templateTypeConstraints().
title() [1/2]
virtual QCString ClassDefAliasImpl::title () const [inline], [virtual]
Implements ClassDef.
Definition at line 513 of file classdef.cpp.
    { return getCdAlias()->title(); }
References getCdAlias(), and ClassDef::title().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
virtual QCString ClassDefAliasImpl::title () const [inline], [virtual]
Implements ClassDef.
Definition at line 513 of file classdef.cpp.
    { return getCdAlias()->title(); }
References getCdAlias(), and ClassDef::title().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
typeConstraints() [1/2]
virtual const ArgumentList & ClassDefAliasImpl::typeConstraints () const [inline], [virtual]
Implements ClassDef.
Definition at line 519 of file classdef.cpp.
    { return getCdAlias()->typeConstraints(); }
References getCdAlias(), and ClassDef::typeConstraints().
typeConstraints() [2/2]
virtual const ArgumentList & ClassDefAliasImpl::typeConstraints () const [inline], [virtual]
Implements ClassDef.
Definition at line 519 of file classdef.cpp.
    { return getCdAlias()->typeConstraints(); }
References getCdAlias(), and ClassDef::typeConstraints().
updateBaseClasses() [1/2]
virtual void ClassDefAliasImpl::updateBaseClasses (const BaseClassList & bcd) [inline], [virtual]
Update the list of base classes to the one passed
Implements ClassDef.
Definition at line 551 of file classdef.cpp.
{}
updateBaseClasses() [2/2]
virtual void ClassDefAliasImpl::updateBaseClasses (const BaseClassList & bcd) [inline], [virtual]
Update the list of base classes to the one passed
Implements ClassDef.
Definition at line 551 of file classdef.cpp.
{}
updateSubClasses() [1/2]
virtual void ClassDefAliasImpl::updateSubClasses (const BaseClassList & bcd) [inline], [virtual]
Update the list of sub classes to the one passed
Implements ClassDef.
Definition at line 552 of file classdef.cpp.
{}
updateSubClasses() [2/2]
virtual void ClassDefAliasImpl::updateSubClasses (const BaseClassList & bcd) [inline], [virtual]
Update the list of sub classes to the one passed
Implements ClassDef.
Definition at line 552 of file classdef.cpp.
{}
usedByImplementationClasses() [1/2]
virtual const UsesClassList & ClassDefAliasImpl::usedByImplementationClasses () const [inline], [virtual]
Implements ClassDef.
Definition at line 454 of file classdef.cpp.
    { return getCdAlias()->usedByImplementationClasses(); }
References getCdAlias(), and ClassDef::usedByImplementationClasses().
usedByImplementationClasses() [2/2]
virtual const UsesClassList & ClassDefAliasImpl::usedByImplementationClasses () const [inline], [virtual]
Implements ClassDef.
Definition at line 454 of file classdef.cpp.
    { return getCdAlias()->usedByImplementationClasses(); }
References getCdAlias(), and ClassDef::usedByImplementationClasses().
usedFiles() [1/2]
virtual const FileList & ClassDefAliasImpl::usedFiles () const [inline], [virtual]
Implements ClassDef.
Definition at line 517 of file classdef.cpp.
    { return getCdAlias()->usedFiles(); }
References getCdAlias(), and ClassDef::usedFiles().
usedFiles() [2/2]
virtual const FileList & ClassDefAliasImpl::usedFiles () const [inline], [virtual]
Implements ClassDef.
Definition at line 517 of file classdef.cpp.
    { return getCdAlias()->usedFiles(); }
References getCdAlias(), and ClassDef::usedFiles().
usedImplementationClasses() [1/2]
virtual const UsesClassList & ClassDefAliasImpl::usedImplementationClasses () const [inline], [virtual]
Implements ClassDef.
Definition at line 452 of file classdef.cpp.
    { return getCdAlias()->usedImplementationClasses(); }
References getCdAlias(), and ClassDef::usedImplementationClasses().
usedImplementationClasses() [2/2]
virtual const UsesClassList & ClassDefAliasImpl::usedImplementationClasses () const [inline], [virtual]
Implements ClassDef.
Definition at line 452 of file classdef.cpp.
    { return getCdAlias()->usedImplementationClasses(); }
References getCdAlias(), and ClassDef::usedImplementationClasses().
visibleInParentsDeclList() [1/2]
virtual bool ClassDefAliasImpl::visibleInParentsDeclList () const [inline], [virtual]
show this class in the declaration section of its parent?
Implements ClassDef.
Definition at line 428 of file classdef.cpp.
    { return getCdAlias()->visibleInParentsDeclList(); }
References getCdAlias(), and ClassDef::visibleInParentsDeclList().
visibleInParentsDeclList() [2/2]
virtual bool ClassDefAliasImpl::visibleInParentsDeclList () const [inline], [virtual]
show this class in the declaration section of its parent?
Implements ClassDef.
Definition at line 428 of file classdef.cpp.
    { return getCdAlias()->visibleInParentsDeclList(); }
References getCdAlias(), and ClassDef::visibleInParentsDeclList().
writeDeclarationLink() [1/2]
virtual void ClassDefAliasImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const [inline], [virtual]
Implements ClassDef.
Definition at line 544 of file classdef.cpp.
    { getCdAlias()->writeDeclarationLink(ol,found,header,localNames); }
References found, getCdAlias(), and ClassDef::writeDeclarationLink().
writeDeclarationLink() [2/2]
virtual void ClassDefAliasImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const [inline], [virtual]
Implements ClassDef.
Definition at line 544 of file classdef.cpp.
    { getCdAlias()->writeDeclarationLink(ol,found,header,localNames); }
References found, getCdAlias(), and ClassDef::writeDeclarationLink().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/classdef.cpp
doxygen/src/classdef.cpp