TranslatorBulgarian Class Reference
#include <translator_bg.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
Additional Inherited Members
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include `translator.h` or `translator_adapter.h` here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 48 of file translator_bg.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorBulgarian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 86 of file translator_bg.h.
    {
      return "0x402 bulgarian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorBulgarian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 86 of file translator_bg.h.
    {
      return "0x402 bulgarian";
    }
idLanguage() [1/2]
virtual QCString TranslatorBulgarian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 60 of file translator_bg.h.
    { return "bulgarian"; }
idLanguage() [2/2]
virtual QCString TranslatorBulgarian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 60 of file translator_bg.h.
    { return "bulgarian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorBulgarian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 77 of file translator_bg.h.
    {
    { return "\\usepackage[T2A]{fontenc}\n\\usepackage[bulgarian]{babel}\n"; }
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorBulgarian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 77 of file translator_bg.h.
    {
    { return "\\usepackage[T2A]{fontenc}\n\\usepackage[bulgarian]{babel}\n"; }
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorBulgarian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1903 of file translator_bg.h.
    { return " "; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorBulgarian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1903 of file translator_bg.h.
    { return " "; }
trAll() [1/2]
virtual QCString TranslatorBulgarian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1417 of file translator_bg.h.
    {
      return " ";
    }
trAll() [2/2]
virtual QCString TranslatorBulgarian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1417 of file translator_bg.h.
    {
      return " ";
    }
trAndMore() [1/2]
virtual QCString TranslatorBulgarian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1881 of file translator_bg.h.
    { return " "+number+" ..."; }
trAndMore() [2/2]
virtual QCString TranslatorBulgarian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1881 of file translator_bg.h.
    { return " "+number+" ..."; }
trAttention() [1/2]
virtual QCString TranslatorBulgarian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 978 of file translator_bg.h.
    {
      return "";
    }
trAttention() [2/2]
virtual QCString TranslatorBulgarian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 978 of file translator_bg.h.
    {
      return "";
    }
trAuthor() [1/2]
virtual QCString TranslatorBulgarian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1288 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorBulgarian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1288 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorBulgarian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1146 of file translator_bg.h.
    {
      return "";
    }
trBug() [2/2]
virtual QCString TranslatorBulgarian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1146 of file translator_bg.h.
    {
      return "";
    }
trBugList() [1/2]
virtual QCString TranslatorBulgarian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1151 of file translator_bg.h.
    {
      return " ";
    }
trBugList() [2/2]
virtual QCString TranslatorBulgarian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1151 of file translator_bg.h.
    {
      return " ";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorBulgarian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1538 of file translator_bg.h.
    {
      return " :";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorBulgarian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1538 of file translator_bg.h.
    {
      return " :";
    }
trCallGraph() [1/2]
virtual QCString TranslatorBulgarian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1422 of file translator_bg.h.
    {
      return " :";
    }
trCallGraph() [2/2]
virtual QCString TranslatorBulgarian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1422 of file translator_bg.h.
    {
      return " :";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorBulgarian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1857 of file translator_bg.h.
    { return ""; }
trCiteReferences() [2/2]
virtual QCString TranslatorBulgarian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1857 of file translator_bg.h.
    { return ""; }
trClass() [1/2]
virtual QCString TranslatorBulgarian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1209 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorBulgarian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1209 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorBulgarian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 530 of file translator_bg.h.
    {
      return (QCString)" "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorBulgarian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 530 of file translator_bg.h.
    {
      return (QCString)" "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 405 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return " ";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 405 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return " ";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorBulgarian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1109 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorBulgarian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1109 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorBulgarian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 181 of file translator_bg.h.
    { return " "; }
trClassHierarchy() [2/2]
virtual QCString TranslatorBulgarian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 181 of file translator_bg.h.
    { return " "; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorBulgarian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 240 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return " :";
      }
      else
      {
        return " , "
               " :";
      }
    }
References Config_getBool.
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorBulgarian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 240 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return " :";
      }
      else
      {
        return " , "
               " :";
      }
    }
References Config_getBool.
trClassMethods() [1/2]
virtual QCString TranslatorBulgarian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1941 of file translator_bg.h.
    {
      return " ";
    }
trClassMethods() [2/2]
virtual QCString TranslatorBulgarian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1941 of file translator_bg.h.
    {
      return " ";
    }
trCode() [1/2]
virtual QCString TranslatorBulgarian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 878 of file translator_bg.h.
    {
      return " ";
    }
trCode() [2/2]
virtual QCString TranslatorBulgarian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 878 of file translator_bg.h.
    {
      return " ";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorBulgarian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 833 of file translator_bg.h.
    {
      return (QCString)" "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorBulgarian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 833 of file translator_bg.h.
    {
      return (QCString)" "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorBulgarian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 378 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorBulgarian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 378 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorBulgarian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1593 of file translator_bg.h.
    { return " "; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorBulgarian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1593 of file translator_bg.h.
    { return " "; }
trCompoundList() [1/2]
virtual QCString TranslatorBulgarian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 185 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorBulgarian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 185 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorBulgarian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 263 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " :";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return " :";
      }
      else
      {
        return ", , "
               " :";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorBulgarian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 263 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " :";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return " :";
      }
      else
      {
        return ", , "
               " :";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorBulgarian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1566 of file translator_bg.h.
    { return " :"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorBulgarian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1566 of file translator_bg.h.
    { return " :"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorBulgarian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1558 of file translator_bg.h.
    { return " "; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorBulgarian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1558 of file translator_bg.h.
    { return " "; }
trCompoundMembers() [1/2]
virtual QCString TranslatorBulgarian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 202 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorBulgarian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 202 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorBulgarian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 282 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" , ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" / :";
        }
        else
        {
          result+=" :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="/, :";
        }
        else
        {
          result+=", :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorBulgarian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 282 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" , ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" / :";
        }
        else
        {
          result+=" :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="/, :";
        }
        else
        {
          result+=", :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorBulgarian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1570 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ";
      result+=" ";
      if (!extractAll)
      {
         result+=" ";
      }
      else
      {
         result+=" , :";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorBulgarian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1570 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ";
      result+=" ";
      if (!extractAll)
      {
         result+=" ";
      }
      else
      {
         result+=" , :";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorBulgarian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1562 of file translator_bg.h.
    { return " "; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorBulgarian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1562 of file translator_bg.h.
    { return " "; }
trCompoundReference() [1/2]
virtual QCString TranslatorBulgarian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 605 of file translator_bg.h.
    {
      QCString result=(QCString)clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorBulgarian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 605 of file translator_bg.h.
    {
      QCString result=(QCString)clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorBulgarian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1634 of file translator_bg.h.
    {
      QCString result=(QCString)clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorBulgarian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1634 of file translator_bg.h.
    {
      QCString result=(QCString)clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorBulgarian::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2231 of file translator_bg.h.
    {
      QCString result=(QCString)clName;
      if (isLocal) result+=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorBulgarian::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2231 of file translator_bg.h.
    {
      QCString result=(QCString)clName;
      if (isLocal) result+=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorBulgarian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 506 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorBulgarian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 506 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trConcept() [1/2]
virtual QCString TranslatorBulgarian::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2279 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trConcept() [2/2]
virtual QCString TranslatorBulgarian::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2279 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trConceptDefinition() [1/2]
virtual QCString TranslatorBulgarian::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2315 of file translator_bg.h.
    {
      return " ";
    }
trConceptDefinition() [2/2]
virtual QCString TranslatorBulgarian::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2315 of file translator_bg.h.
    {
      return " ";
    }
trConceptDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2302 of file translator_bg.h.
    { return " "; }
trConceptDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2302 of file translator_bg.h.
    { return " "; }
trConceptIndex() [1/2]
virtual QCString TranslatorBulgarian::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2298 of file translator_bg.h.
    { return " "; }
trConceptIndex() [2/2]
virtual QCString TranslatorBulgarian::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2298 of file translator_bg.h.
    { return " "; }
trConceptList() [1/2]
virtual QCString TranslatorBulgarian::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2294 of file translator_bg.h.
    { return " "; }
trConceptList() [2/2]
virtual QCString TranslatorBulgarian::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2294 of file translator_bg.h.
    { return " "; }
trConceptListDescription() [1/2]
virtual QCString TranslatorBulgarian::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2306 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trConceptListDescription() [2/2]
virtual QCString TranslatorBulgarian::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2306 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trConceptReference() [1/2]
virtual QCString TranslatorBulgarian::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2286 of file translator_bg.h.
    {
      QCString result=conceptName;
      result+=" ";
      return result;
    }
trConceptReference() [2/2]
virtual QCString TranslatorBulgarian::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2286 of file translator_bg.h.
    {
      QCString result=conceptName;
      result+=" ";
      return result;
    }
trConstantDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2139 of file translator_bg.h.
    {
        return " ";
    }
trConstantDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2139 of file translator_bg.h.
    {
        return " ";
    }
trConstantGroupReference() [1/2]
virtual QCString TranslatorBulgarian::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1978 of file translator_bg.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorBulgarian::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1978 of file translator_bg.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorBulgarian::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1974 of file translator_bg.h.
    { return " "; }
trConstantGroups() [2/2]
virtual QCString TranslatorBulgarian::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1974 of file translator_bg.h.
    { return " "; }
trConstants() [1/2]
virtual QCString TranslatorBulgarian::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2135 of file translator_bg.h.
    {
        return "";
    }
trConstants() [2/2]
virtual QCString TranslatorBulgarian::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2135 of file translator_bg.h.
    {
        return "";
    }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 843 of file translator_bg.h.
    {
      return " & ";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 843 of file translator_bg.h.
    {
      return " & ";
    }
trCopyright() [1/2]
virtual QCString TranslatorBulgarian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1861 of file translator_bg.h.
    { return " "; }
trCopyright() [2/2]
virtual QCString TranslatorBulgarian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1861 of file translator_bg.h.
    { return " "; }
trCustomReference() [1/2]
virtual QCString TranslatorBulgarian::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2131 of file translator_bg.h.
    { return QCString(name)+" "; }
References setup::name.
trCustomReference() [2/2]
virtual QCString TranslatorBulgarian::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2131 of file translator_bg.h.
    { return QCString(name)+" "; }
References setup::name.
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2261 of file translator_bg.h.
    {
        return " ";
    }
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2261 of file translator_bg.h.
    {
        return " ";
    }
trDataMembers() [1/2]
virtual QCString TranslatorBulgarian::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2257 of file translator_bg.h.
    {
        return " ";
    }
trDataMembers() [2/2]
virtual QCString TranslatorBulgarian::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2257 of file translator_bg.h.
    {
        return " ";
    }
trDataTypes() [1/2]
virtual QCString TranslatorBulgarian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1617 of file translator_bg.h.
    { return " "; }
trDataTypes() [2/2]
virtual QCString TranslatorBulgarian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1617 of file translator_bg.h.
    { return " "; }
trDate() [1/2]
virtual QCString TranslatorBulgarian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 544 of file translator_bg.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorBulgarian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 544 of file translator_bg.h.
    { return ""; }
trDateTime() [1/2]
virtual QCString TranslatorBulgarian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1818 of file translator_bg.h.
    {
      static const char *days[] = { "","","","","","","" };
      static const char *months[] = { "","","","","","","","","","","","" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorBulgarian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1818 of file translator_bg.h.
    {
      static const char *days[] = { "","","","","","","" };
      static const char *months[] = { "","","","","","","","","","","","" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorBulgarian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1834 of file translator_bg.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorBulgarian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1834 of file translator_bg.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayPeriod() [1/2]
virtual QCString TranslatorBulgarian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1846 of file translator_bg.h.
    {
      static const char *dayPeriod[] = { "..", ".." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorBulgarian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1846 of file translator_bg.h.
    {
      static const char *dayPeriod[] = { "..", ".." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorBulgarian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 810 of file translator_bg.h.
    {
      return " @1 @0.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorBulgarian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 810 of file translator_bg.h.
    {
      return " @1 @0.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorBulgarian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 169 of file translator_bg.h.
    { return " "; }
trDefinedIn() [2/2]
virtual QCString TranslatorBulgarian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 169 of file translator_bg.h.
    { return " "; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorBulgarian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 814 of file translator_bg.h.
    {
      return " @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorBulgarian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 814 of file translator_bg.h.
    {
      return " @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 476 of file translator_bg.h.
    { return " "; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 476 of file translator_bg.h.
    { return " "; }
trDefines() [1/2]
virtual QCString TranslatorBulgarian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 440 of file translator_bg.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorBulgarian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 440 of file translator_bg.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorBulgarian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1136 of file translator_bg.h.
    {
      return ":";
    }
trDefineValue() [2/2]
virtual QCString TranslatorBulgarian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1136 of file translator_bg.h.
    {
      return ":";
    }
trDeprecated() [1/2]
virtual QCString TranslatorBulgarian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 823 of file translator_bg.h.
    {
      return "";
    }
trDeprecated() [2/2]
virtual QCString TranslatorBulgarian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 823 of file translator_bg.h.
    {
      return "";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorBulgarian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1345 of file translator_bg.h.
    {
      return " ";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorBulgarian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1345 of file translator_bg.h.
    {
      return " ";
    }
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2271 of file translator_bg.h.
    { return " "; }
Referenced by trClassDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2271 of file translator_bg.h.
    { return " "; }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorBulgarian::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2022 of file translator_bg.h.
    { return " "; }
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorBulgarian::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2022 of file translator_bg.h.
    { return " "; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorBulgarian::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2037 of file translator_bg.h.
    { return " "; }
trDesignUnitIndex() [2/2]
virtual QCString TranslatorBulgarian::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2037 of file translator_bg.h.
    { return " "; }
trDesignUnitList() [1/2]
virtual QCString TranslatorBulgarian::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2025 of file translator_bg.h.
    { return " "; }
trDesignUnitList() [2/2]
virtual QCString TranslatorBulgarian::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2025 of file translator_bg.h.
    { return " "; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorBulgarian::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2031 of file translator_bg.h.
    {
        return "Here is a list of all design unit members with links to "
            "the Entities they belong to:";
    }
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorBulgarian::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2031 of file translator_bg.h.
    {
        return "Here is a list of all design unit members with links to "
            "the Entities they belong to:";
    }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorBulgarian::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2028 of file translator_bg.h.
    { return " "; }
trDesignUnitMembers() [2/2]
virtual QCString TranslatorBulgarian::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2028 of file translator_bg.h.
    { return " "; }
trDesignUnits() [1/2]
virtual QCString TranslatorBulgarian::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2040 of file translator_bg.h.
    { return " "; }
trDesignUnits() [2/2]
virtual QCString TranslatorBulgarian::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2040 of file translator_bg.h.
    { return " "; }
trDetailedDescription() [1/2]
virtual QCString TranslatorBulgarian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 102 of file translator_bg.h.
    { return " "; }
trDetailedDescription() [2/2]
virtual QCString TranslatorBulgarian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 102 of file translator_bg.h.
    { return " "; }
trDetailLevel() [1/2]
virtual QCString TranslatorBulgarian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1873 of file translator_bg.h.
    { return " "; }
trDetailLevel() [2/2]
virtual QCString TranslatorBulgarian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1873 of file translator_bg.h.
    { return " "; }
trDictionaries() [1/2]
virtual QCString TranslatorBulgarian::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2151 of file translator_bg.h.
    {
        return "";
    }
trDictionaries() [2/2]
virtual QCString TranslatorBulgarian::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2151 of file translator_bg.h.
    {
        return "";
    }
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2155 of file translator_bg.h.
    {
        return " ";
    }
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2155 of file translator_bg.h.
    {
        return " ";
    }
trDir() [1/2]
virtual QCString TranslatorBulgarian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1512 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorBulgarian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1512 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=""; else result+="";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorBulgarian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1865 of file translator_bg.h.
    { return QCString(" ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorBulgarian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1865 of file translator_bg.h.
    { return QCString(" ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1494 of file translator_bg.h.
    { return " "; }
trDirDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1494 of file translator_bg.h.
    { return " "; }
trDirectories() [1/2]
virtual QCString TranslatorBulgarian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1500 of file translator_bg.h.
    { return ""; }
trDirectories() [2/2]
virtual QCString TranslatorBulgarian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1500 of file translator_bg.h.
    { return ""; }
trDirIndex() [1/2]
virtual QCString TranslatorBulgarian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1488 of file translator_bg.h.
    { return " "; }
trDirIndex() [2/2]
virtual QCString TranslatorBulgarian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1488 of file translator_bg.h.
    { return " "; }
trDirReference() [1/2]
virtual QCString TranslatorBulgarian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1506 of file translator_bg.h.
    { QCString result=dirName; result+=" "; return result; }
trDirReference() [2/2]
virtual QCString TranslatorBulgarian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1506 of file translator_bg.h.
    { QCString result=dirName; result+=" "; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorBulgarian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1757 of file translator_bg.h.
    {
      return QCString(name)+" ";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorBulgarian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1757 of file translator_bg.h.
    {
      return QCString(name)+" ";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 360 of file translator_bg.h.
    { return ""; }
trDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 360 of file translator_bg.h.
    { return ""; }
trEnumerations() [1/2]
virtual QCString TranslatorBulgarian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 452 of file translator_bg.h.
    { return ""; }
trEnumerations() [2/2]
virtual QCString TranslatorBulgarian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 452 of file translator_bg.h.
    { return ""; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 488 of file translator_bg.h.
    { return " "; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 488 of file translator_bg.h.
    { return " "; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1546 of file translator_bg.h.
    { return " "; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1546 of file translator_bg.h.
    { return " "; }
trEnumerationValues() [1/2]
virtual QCString TranslatorBulgarian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 470 of file translator_bg.h.
    { return " "; }
trEnumerationValues() [2/2]
virtual QCString TranslatorBulgarian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 470 of file translator_bg.h.
    { return " "; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorBulgarian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1885 of file translator_bg.h.
    { QCString result = " ";
      if (single) result+=" :"; else result+=" :";
      result+=":";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorBulgarian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1885 of file translator_bg.h.
    { QCString result = " ";
      if (single) result+=" :"; else result+=" :";
      result+=":";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorBulgarian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 161 of file translator_bg.h.
    { return ""; }
trEnumName() [2/2]
virtual QCString TranslatorBulgarian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 161 of file translator_bg.h.
    { return ""; }
trEnumReference() [1/2]
virtual QCString TranslatorBulgarian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1893 of file translator_bg.h.
    { return QCString(name)+" "; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorBulgarian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1893 of file translator_bg.h.
    { return QCString(name)+" "; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorBulgarian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 165 of file translator_bg.h.
    { return " "; }
trEnumValue() [2/2]
virtual QCString TranslatorBulgarian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 165 of file translator_bg.h.
    { return " "; }
trEventDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1362 of file translator_bg.h.
    {
      return " ";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1362 of file translator_bg.h.
    {
      return " ";
    }
trEvents() [1/2]
virtual QCString TranslatorBulgarian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1357 of file translator_bg.h.
    {
      return "";
    }
trEvents() [2/2]
virtual QCString TranslatorBulgarian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1357 of file translator_bg.h.
    {
      return "";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 430 of file translator_bg.h.
    { return " "; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 430 of file translator_bg.h.
    { return " "; }
trExamples() [1/2]
virtual QCString TranslatorBulgarian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 232 of file translator_bg.h.
    { return ""; }
trExamples() [2/2]
virtual QCString TranslatorBulgarian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 232 of file translator_bg.h.
    { return ""; }
trExamplesDescription() [1/2]
virtual QCString TranslatorBulgarian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 346 of file translator_bg.h.
    { return " :"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorBulgarian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 346 of file translator_bg.h.
    { return " :"; }
trExceptionDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2227 of file translator_bg.h.
    {
        return " ";
    }
trExceptionDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2227 of file translator_bg.h.
    {
        return " ";
    }
trExceptionHierarchy() [1/2]
virtual QCString TranslatorBulgarian::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2219 of file translator_bg.h.
    {
        return " ";
    }
trExceptionHierarchy() [2/2]
virtual QCString TranslatorBulgarian::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2219 of file translator_bg.h.
    {
        return " ";
    }
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorBulgarian::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2223 of file translator_bg.h.
    {
        return " , , :";
    }
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorBulgarian::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2223 of file translator_bg.h.
    {
        return " , , :";
    }
trExceptionIndex() [1/2]
virtual QCString TranslatorBulgarian::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2207 of file translator_bg.h.
    {
        return " ";
    }
trExceptionIndex() [2/2]
virtual QCString TranslatorBulgarian::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2207 of file translator_bg.h.
    {
        return " ";
    }
trExceptionList() [1/2]
virtual QCString TranslatorBulgarian::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2211 of file translator_bg.h.
    {
        return " ";
    }
trExceptionList() [2/2]
virtual QCString TranslatorBulgarian::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2211 of file translator_bg.h.
    {
        return " ";
    }
trExceptionListDescription() [1/2]
virtual QCString TranslatorBulgarian::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2215 of file translator_bg.h.
    {
        return " :";
    }
trExceptionListDescription() [2/2]
virtual QCString TranslatorBulgarian::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2215 of file translator_bg.h.
    {
        return " :";
    }
trExceptions() [1/2]
virtual QCString TranslatorBulgarian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 560 of file translator_bg.h.
    { return ""; }
trExceptions() [2/2]
virtual QCString TranslatorBulgarian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 560 of file translator_bg.h.
    { return ""; }
trExtendsClass() [1/2]
virtual QCString TranslatorBulgarian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1933 of file translator_bg.h.
    {
      return " @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorBulgarian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1933 of file translator_bg.h.
    {
      return " @0.";
    }
trFile() [1/2]
virtual QCString TranslatorBulgarian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1220 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorBulgarian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1220 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 424 of file translator_bg.h.
    { return " "; }
trFileDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 424 of file translator_bg.h.
    { return " "; }
trFileIn() [1/2]
virtual QCString TranslatorBulgarian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1794 of file translator_bg.h.
    {
      return (QCString)" "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorBulgarian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1794 of file translator_bg.h.
    {
      return (QCString)" "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorBulgarian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 393 of file translator_bg.h.
    { return " "; }
trFileIndex() [2/2]
virtual QCString TranslatorBulgarian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 393 of file translator_bg.h.
    { return " "; }
trFileList() [1/2]
virtual QCString TranslatorBulgarian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 198 of file translator_bg.h.
    { return " "; }
trFileList() [2/2]
virtual QCString TranslatorBulgarian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 198 of file translator_bg.h.
    { return " "; }
trFileListDescription() [1/2]
virtual QCString TranslatorBulgarian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 254 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorBulgarian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 254 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorBulgarian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 215 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorBulgarian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 215 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorBulgarian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 324 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , , ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (extractAll)
        result+=", :";
      else
        result+=":";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorBulgarian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 324 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , , ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (extractAll)
        result+=", :";
      else
        result+=":";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorBulgarian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 627 of file translator_bg.h.
    {
      QCString result=fileName;
      result+=" ";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorBulgarian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 627 of file translator_bg.h.
    {
      QCString result=fileName;
      result+=" ";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorBulgarian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 587 of file translator_bg.h.
    { return ""; }
trFriends() [2/2]
virtual QCString TranslatorBulgarian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 587 of file translator_bg.h.
    { return ""; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorBulgarian::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2043 of file translator_bg.h.
    { return "//"; }
trFunctionAndProc() [2/2]
virtual QCString TranslatorBulgarian::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2043 of file translator_bg.h.
    { return "//"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 494 of file translator_bg.h.
    { return " "; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 494 of file translator_bg.h.
    { return " "; }
trFunctions() [1/2]
virtual QCString TranslatorBulgarian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 458 of file translator_bg.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorBulgarian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 458 of file translator_bg.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorBulgarian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 521 of file translator_bg.h.
    {
      QCString result=(QCString)" "+date;
      if (!projName.isEmpty()) result+=(QCString)" "+projName;
      result+=(QCString)" ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorBulgarian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 521 of file translator_bg.h.
    {
      QCString result=(QCString)" "+date;
      if (!projName.isEmpty()) result+=(QCString)" "+projName;
      result+=(QCString)" ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorBulgarian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 153 of file translator_bg.h.
    { QCString result=" Doxygen";
      if (!s.isEmpty()) result+=(QCString)" "+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorBulgarian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 153 of file translator_bg.h.
    { QCString result=" Doxygen";
      if (!s.isEmpty()) result+=(QCString)" "+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorBulgarian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 564 of file translator_bg.h.
    { return " "; }
trGeneratedBy() [2/2]
virtual QCString TranslatorBulgarian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 564 of file translator_bg.h.
    { return " "; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorBulgarian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 766 of file translator_bg.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result=(QCString)" ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?" ":""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorBulgarian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 766 of file translator_bg.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result=(QCString)" ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?" ":""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorBulgarian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1703 of file translator_bg.h.
    {
      // single is true implies a single file
      QCString result=(QCString)" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorBulgarian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1703 of file translator_bg.h.
    {
      // single is true implies a single file
      QCString result=(QCString)" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorBulgarian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1275 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorBulgarian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1275 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorBulgarian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1769 of file translator_bg.h.
    {
      return " ";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorBulgarian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1769 of file translator_bg.h.
    {
      return " ";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 853 of file translator_bg.h.
    {
      return " .";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 853 of file translator_bg.h.
    {
      return " .";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorBulgarian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 886 of file translator_bg.h.
    {
      return " ";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorBulgarian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 886 of file translator_bg.h.
    {
      return " ";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorBulgarian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 848 of file translator_bg.h.
    {
      return " .";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorBulgarian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 848 of file translator_bg.h.
    {
      return " .";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorBulgarian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 890 of file translator_bg.h.
    {
      return " ";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorBulgarian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 890 of file translator_bg.h.
    {
      return " ";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorBulgarian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 882 of file translator_bg.h.
    {
      return " ";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorBulgarian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 882 of file translator_bg.h.
    {
      return " ";
    }
trGroup() [1/2]
virtual QCString TranslatorBulgarian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1242 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorBulgarian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1242 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorBulgarian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 372 of file translator_bg.h.
    { return " "; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorBulgarian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 372 of file translator_bg.h.
    { return " "; }
trImplementedFromList() [1/2]
virtual QCString TranslatorBulgarian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1313 of file translator_bg.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorBulgarian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1313 of file translator_bg.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorBulgarian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1321 of file translator_bg.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorBulgarian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1321 of file translator_bg.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorBulgarian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 982 of file translator_bg.h.
    {
      return " , "
             " :";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorBulgarian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 982 of file translator_bg.h.
    {
      return " , "
             " :";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorBulgarian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 838 of file translator_bg.h.
    {
      return (QCString)" "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorBulgarian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 838 of file translator_bg.h.
    {
      return (QCString)" "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorBulgarian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1803 of file translator_bg.h.
    {
      return (QCString)" "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorBulgarian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1803 of file translator_bg.h.
    {
      return (QCString)" "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorBulgarian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 147 of file translator_bg.h.
    { return ", ."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorBulgarian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 147 of file translator_bg.h.
    { return ", ."; }
trInheritedByList() [1/2]
virtual QCString TranslatorBulgarian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 699 of file translator_bg.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorBulgarian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 699 of file translator_bg.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorBulgarian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1897 of file translator_bg.h.
    { return QCString(members)+" "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorBulgarian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1897 of file translator_bg.h.
    { return QCString(members)+" "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorBulgarian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 691 of file translator_bg.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorBulgarian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 691 of file translator_bg.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorBulgarian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 873 of file translator_bg.h.
    {
      return " :";
    }
trInitialValue() [2/2]
virtual QCString TranslatorBulgarian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 873 of file translator_bg.h.
    {
      return " :";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorBulgarian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1949 of file translator_bg.h.
    {
      return " ";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorBulgarian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1949 of file translator_bg.h.
    {
      return " ";
    }
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2183 of file translator_bg.h.
    {
        return " ";
    }
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2183 of file translator_bg.h.
    {
        return " ";
    }
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorBulgarian::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2175 of file translator_bg.h.
    {
        return " ";
    }
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorBulgarian::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2175 of file translator_bg.h.
    {
        return " ";
    }
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorBulgarian::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2179 of file translator_bg.h.
    {
        return " , , :";
    }
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorBulgarian::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2179 of file translator_bg.h.
    {
        return " , , :";
    }
trInterfaceIndex() [1/2]
virtual QCString TranslatorBulgarian::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2163 of file translator_bg.h.
    {
        return " ";
    }
trInterfaceIndex() [2/2]
virtual QCString TranslatorBulgarian::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2163 of file translator_bg.h.
    {
        return " ";
    }
trInterfaceList() [1/2]
virtual QCString TranslatorBulgarian::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2167 of file translator_bg.h.
    {
        return " ";
    }
trInterfaceList() [2/2]
virtual QCString TranslatorBulgarian::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2167 of file translator_bg.h.
    {
        return " ";
    }
trInterfaceListDescription() [1/2]
virtual QCString TranslatorBulgarian::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2171 of file translator_bg.h.
    {
        return " :";
    }
trInterfaceListDescription() [2/2]
virtual QCString TranslatorBulgarian::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2171 of file translator_bg.h.
    {
        return " :";
    }
trInterfaces() [1/2]
virtual QCString TranslatorBulgarian::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1966 of file translator_bg.h.
    { return " "; }
trInterfaces() [2/2]
virtual QCString TranslatorBulgarian::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1966 of file translator_bg.h.
    { return " "; }
trInvariant() [1/2]
virtual QCString TranslatorBulgarian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 868 of file translator_bg.h.
    {
      return "";
    }
trInvariant() [2/2]
virtual QCString TranslatorBulgarian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 868 of file translator_bg.h.
    {
      return "";
    }
trISOLang() [1/2]
virtual QCString TranslatorBulgarian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 82 of file translator_bg.h.
    {
      return "bg";
    }
trISOLang() [2/2]
virtual QCString TranslatorBulgarian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 82 of file translator_bg.h.
    {
      return "bg";
    }
trLegend() [1/2]
virtual QCString TranslatorBulgarian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1069 of file translator_bg.h.
    {
      return "";
    }
trLegend() [2/2]
virtual QCString TranslatorBulgarian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1069 of file translator_bg.h.
    {
      return "";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorBulgarian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1004 of file translator_bg.h.
    {
      return
        " , "
        " doxygen.<p>\n"
        " :\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! , */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ { };\n\n"
        "/*! , */\n"
        "class ProtectedBase { };\n\n"
        "/*! , */\n"
        "class PrivateBase { };\n\n"
        "/*! , */\n"
        "class Used { };\n\n"
        "/*! , */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " :"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        " :\n"
        "</p>\n"
        "<ul>\n"
        "<li>% , "
        " .</li>\n"
        "<li>% .</li>\n"
        "<li>% .</li>\n"
        "<li>% "
        " /. %A a e"
        ", .</li>\n"
        "</ul>\n"
        "<p>\n"
        " :\n"
        "</p>\n"
        "<ul>\n"
        "<li>% "
        " .</li>\n"
        "<li>% .</li>\n"
        "<li>% .</li>\n"
        "<li>% , "
        " . () "
        " .</li>\n"
        "<li>% "
        " , . "
        " .</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorBulgarian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1004 of file translator_bg.h.
    {
      return
        " , "
        " doxygen.<p>\n"
        " :\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! , */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ { };\n\n"
        "/*! , */\n"
        "class ProtectedBase { };\n\n"
        "/*! , */\n"
        "class PrivateBase { };\n\n"
        "/*! , */\n"
        "class Used { };\n\n"
        "/*! , */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " :"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        " :\n"
        "</p>\n"
        "<ul>\n"
        "<li>% , "
        " .</li>\n"
        "<li>% .</li>\n"
        "<li>% .</li>\n"
        "<li>% "
        " /. %A a e"
        ", .</li>\n"
        "</ul>\n"
        "<p>\n"
        " :\n"
        "</p>\n"
        "<ul>\n"
        "<li>% "
        " .</li>\n"
        "<li>% .</li>\n"
        "<li>% .</li>\n"
        "<li>% , "
        " . () "
        " .</li>\n"
        "<li>% "
        " , . "
        " .</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorBulgarian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 997 of file translator_bg.h.
    {
      return " ";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorBulgarian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 997 of file translator_bg.h.
    {
      return " ";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorBulgarian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 135 of file translator_bg.h.
    { return " "; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorBulgarian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 135 of file translator_bg.h.
    { return " "; }
trLoading() [1/2]
virtual QCString TranslatorBulgarian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1763 of file translator_bg.h.
    {
      return "...";
    }
trLoading() [2/2]
virtual QCString TranslatorBulgarian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1763 of file translator_bg.h.
    {
      return "...";
    }
trMainPage() [1/2]
virtual QCString TranslatorBulgarian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 797 of file translator_bg.h.
    { return " "; }
trMainPage() [2/2]
virtual QCString TranslatorBulgarian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 797 of file translator_bg.h.
    { return " "; }
trMember() [1/2]
virtual QCString TranslatorBulgarian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1264 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorBulgarian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1264 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 118 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 118 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 110 of file translator_bg.h.
    { return " "; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 110 of file translator_bg.h.
    { return " "; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 114 of file translator_bg.h.
    { return " () "; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 114 of file translator_bg.h.
    { return " () "; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorBulgarian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1554 of file translator_bg.h.
    { return "/ "; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorBulgarian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1554 of file translator_bg.h.
    { return "/ "; }
trMemberList() [1/2]
virtual QCString TranslatorBulgarian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 139 of file translator_bg.h.
    { return " "; }
trMemberList() [2/2]
virtual QCString TranslatorBulgarian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 139 of file translator_bg.h.
    { return " "; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 106 of file translator_bg.h.
    { return " "; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 106 of file translator_bg.h.
    { return " "; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1956 of file translator_bg.h.
    {
      return " ";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1956 of file translator_bg.h.
    {
      return " ";
    }
trModule() [1/2]
virtual QCString TranslatorBulgarian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1693 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorBulgarian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1693 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 399 of file translator_bg.h.
    { return " "; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 399 of file translator_bg.h.
    { return " "; }
trModuleIndex() [1/2]
virtual QCString TranslatorBulgarian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 366 of file translator_bg.h.
    { return " "; }
trModuleIndex() [2/2]
virtual QCString TranslatorBulgarian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 366 of file translator_bg.h.
    { return " "; }
trModuleReference() [1/2]
virtual QCString TranslatorBulgarian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1655 of file translator_bg.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorBulgarian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1655 of file translator_bg.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorBulgarian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 177 of file translator_bg.h.
    { return ""; }
trModules() [2/2]
virtual QCString TranslatorBulgarian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 177 of file translator_bg.h.
    { return ""; }
trModulesDescription() [1/2]
virtual QCString TranslatorBulgarian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 354 of file translator_bg.h.
    { return " :"; }
trModulesDescription() [2/2]
virtual QCString TranslatorBulgarian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 354 of file translator_bg.h.
    { return " :"; }
trModulesIndex() [1/2]
virtual QCString TranslatorBulgarian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1686 of file translator_bg.h.
    { return " "; }
trModulesIndex() [2/2]
virtual QCString TranslatorBulgarian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1686 of file translator_bg.h.
    { return " "; }
trModulesList() [1/2]
virtual QCString TranslatorBulgarian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1621 of file translator_bg.h.
    { return " "; }
trModulesList() [2/2]
virtual QCString TranslatorBulgarian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1621 of file translator_bg.h.
    { return " "; }
trModulesListDescription() [1/2]
virtual QCString TranslatorBulgarian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1625 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorBulgarian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1625 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorBulgarian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1667 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
      {
        result+=" :";
      }
      else
      {
        result+=", :";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorBulgarian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1667 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
      {
        result+=" :";
      }
      else
      {
        result+=", :";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorBulgarian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1663 of file translator_bg.h.
    { return " "; }
trModulesMembers() [2/2]
virtual QCString TranslatorBulgarian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1663 of file translator_bg.h.
    { return " "; }
trMonth() [1/2]
virtual QCString TranslatorBulgarian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1840 of file translator_bg.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMonth() [2/2]
virtual QCString TranslatorBulgarian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1840 of file translator_bg.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMore() [1/2]
virtual QCString TranslatorBulgarian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 131 of file translator_bg.h.
    { return "..."; }
trMore() [2/2]
virtual QCString TranslatorBulgarian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 131 of file translator_bg.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorBulgarian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1231 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? " " : " ");
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorBulgarian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1231 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? " " : " ");
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 746 of file translator_bg.h.
    { return " "; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 746 of file translator_bg.h.
    { return " "; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorBulgarian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 740 of file translator_bg.h.
    { return " "; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorBulgarian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 740 of file translator_bg.h.
    { return " "; }
trNamespaceList() [1/2]
virtual QCString TranslatorBulgarian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 572 of file translator_bg.h.
    { return " "; }
trNamespaceList() [2/2]
virtual QCString TranslatorBulgarian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 572 of file translator_bg.h.
    { return " "; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorBulgarian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 576 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorBulgarian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 576 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorBulgarian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 726 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
        result+=" :";
      else
        result+=" :";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorBulgarian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 726 of file translator_bg.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
        result+=" :";
      else
        result+=" :";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorBulgarian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 721 of file translator_bg.h.
    { return " ";
    }
trNamespaceMembers() [2/2]
virtual QCString TranslatorBulgarian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 721 of file translator_bg.h.
    { return " ";
    }
trNamespaceReference() [1/2]
virtual QCString TranslatorBulgarian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 635 of file translator_bg.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorBulgarian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 635 of file translator_bg.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorBulgarian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 756 of file translator_bg.h.
    { return " "; }
trNamespaces() [2/2]
virtual QCString TranslatorBulgarian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 756 of file translator_bg.h.
    { return " "; }
trNoMatches() [1/2]
virtual QCString TranslatorBulgarian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1781 of file translator_bg.h.
    {
      return " ";
    }
trNoMatches() [2/2]
virtual QCString TranslatorBulgarian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1781 of file translator_bg.h.
    {
      return " ";
    }
trNote() [1/2]
virtual QCString TranslatorBulgarian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 903 of file translator_bg.h.
    {
      return "";
    }
trNote() [2/2]
virtual QCString TranslatorBulgarian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 903 of file translator_bg.h.
    {
      return "";
    }
trOperationDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2253 of file translator_bg.h.
    {
        return " ";
    }
trOperationDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2253 of file translator_bg.h.
    {
        return " ";
    }
trOperations() [1/2]
virtual QCString TranslatorBulgarian::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2249 of file translator_bg.h.
    {
        return "";
    }
trOperations() [2/2]
virtual QCString TranslatorBulgarian::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2249 of file translator_bg.h.
    {
        return "";
    }
trOverloadText() [1/2]
virtual QCString TranslatorBulgarian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1526 of file translator_bg.h.
    {
       return " , "
              " . "
              " .";
    }
trOverloadText() [2/2]
virtual QCString TranslatorBulgarian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1526 of file translator_bg.h.
    {
       return " , "
              " . "
              " .";
    }
trPackage() [1/2]
virtual QCString TranslatorBulgarian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1121 of file translator_bg.h.
    {
      return (QCString)" "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorBulgarian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1121 of file translator_bg.h.
    {
      return (QCString)" "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorBulgarian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1398 of file translator_bg.h.
    {
      return " ";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorBulgarian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1398 of file translator_bg.h.
    {
      return " ";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorBulgarian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1380 of file translator_bg.h.
    {
      return " ";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorBulgarian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1380 of file translator_bg.h.
    {
      return " ";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorBulgarian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1126 of file translator_bg.h.
    {
      return " ():";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorBulgarian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1126 of file translator_bg.h.
    {
      return " ():";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorBulgarian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1384 of file translator_bg.h.
    {
      return " ";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorBulgarian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1384 of file translator_bg.h.
    {
      return " ";
    }
trPackages() [1/2]
virtual QCString TranslatorBulgarian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1131 of file translator_bg.h.
    {
      return "";
    }
trPackages() [2/2]
virtual QCString TranslatorBulgarian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1131 of file translator_bg.h.
    {
      return "";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorBulgarian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1373 of file translator_bg.h.
    {
      return " ";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorBulgarian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1373 of file translator_bg.h.
    {
      return " ";
    }
trPage() [1/2]
virtual QCString TranslatorBulgarian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1253 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorBulgarian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1253 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorBulgarian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 803 of file translator_bg.h.
    { return "."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorBulgarian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 803 of file translator_bg.h.
    { return "."; }
trPageIndex() [1/2]
virtual QCString TranslatorBulgarian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 894 of file translator_bg.h.
    {
      return " ";
    }
trPageIndex() [2/2]
virtual QCString TranslatorBulgarian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 894 of file translator_bg.h.
    {
      return " ";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorBulgarian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1914 of file translator_bg.h.
    {
      QCString opt = enable ? "" : "";
      return " "+opt+" ";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorBulgarian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1914 of file translator_bg.h.
    {
      QCString opt = enable ? "" : "";
      return " "+opt+" ";
    }
trParameters() [1/2]
virtual QCString TranslatorBulgarian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 556 of file translator_bg.h.
    { return ""; }
trParameters() [2/2]
virtual QCString TranslatorBulgarian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 556 of file translator_bg.h.
    { return ""; }
trPostcondition() [1/2]
virtual QCString TranslatorBulgarian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 863 of file translator_bg.h.
    {
      return "";
    }
trPostcondition() [2/2]
virtual QCString TranslatorBulgarian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 863 of file translator_bg.h.
    {
      return "";
    }
trPrecondition() [1/2]
virtual QCString TranslatorBulgarian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 858 of file translator_bg.h.
    {
      return "";
    }
trPrecondition() [2/2]
virtual QCString TranslatorBulgarian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 858 of file translator_bg.h.
    {
      return "";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorBulgarian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 942 of file translator_bg.h.
    {
      return " ";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorBulgarian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 942 of file translator_bg.h.
    {
      return " ";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorBulgarian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 656 of file translator_bg.h.
    { return " "; }
trPrivateMembers() [2/2]
virtual QCString TranslatorBulgarian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 656 of file translator_bg.h.
    { return " "; }
trPrivateSlots() [1/2]
virtual QCString TranslatorBulgarian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 658 of file translator_bg.h.
    { return " "; }
trPrivateSlots() [2/2]
virtual QCString TranslatorBulgarian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 658 of file translator_bg.h.
    { return " "; }
trPrivateTypes() [1/2]
virtual QCString TranslatorBulgarian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 938 of file translator_bg.h.
    {
      return " ";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorBulgarian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 938 of file translator_bg.h.
    {
      return " ";
    }
trProperties() [1/2]
virtual QCString TranslatorBulgarian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1094 of file translator_bg.h.
    {
      return "";
    }
trProperties() [2/2]
virtual QCString TranslatorBulgarian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1094 of file translator_bg.h.
    {
      return "";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1099 of file translator_bg.h.
    {
      return " ";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1099 of file translator_bg.h.
    {
      return " ";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorBulgarian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 930 of file translator_bg.h.
    {
      return " ";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorBulgarian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 930 of file translator_bg.h.
    {
      return " ";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorBulgarian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 650 of file translator_bg.h.
    { return " "; }
trProtectedMembers() [2/2]
virtual QCString TranslatorBulgarian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 650 of file translator_bg.h.
    { return " "; }
trProtectedSlots() [1/2]
virtual QCString TranslatorBulgarian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 652 of file translator_bg.h.
    { return " "; }
trProtectedSlots() [2/2]
virtual QCString TranslatorBulgarian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 652 of file translator_bg.h.
    { return " "; }
trProtectedTypes() [1/2]
virtual QCString TranslatorBulgarian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 926 of file translator_bg.h.
    {
      return " ";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorBulgarian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 926 of file translator_bg.h.
    {
      return " ";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorBulgarian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1924 of file translator_bg.h.
    {
      return " @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorBulgarian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1924 of file translator_bg.h.
    {
      return " @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorBulgarian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 911 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorBulgarian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 911 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorBulgarian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_bg.h.
    { return " "; }
trPublicMembers() [2/2]
virtual QCString TranslatorBulgarian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_bg.h.
    { return " "; }
trPublicSlots() [1/2]
virtual QCString TranslatorBulgarian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_bg.h.
    { return " "; }
trPublicSlots() [2/2]
virtual QCString TranslatorBulgarian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_bg.h.
    { return " "; }
trPublicTypes() [1/2]
virtual QCString TranslatorBulgarian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 907 of file translator_bg.h.
    {
      return " ";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorBulgarian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 907 of file translator_bg.h.
    {
      return " ";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorBulgarian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 970 of file translator_bg.h.
    {
      return " ";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorBulgarian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 970 of file translator_bg.h.
    {
      return " ";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorBulgarian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 434 of file translator_bg.h.
    { return " "; }
trReferenceManual() [2/2]
virtual QCString TranslatorBulgarian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 434 of file translator_bg.h.
    { return " "; }
trReferences() [1/2]
virtual QCString TranslatorBulgarian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1301 of file translator_bg.h.
    {
      return " ";
    }
trReferences() [2/2]
virtual QCString TranslatorBulgarian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1301 of file translator_bg.h.
    {
      return " ";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorBulgarian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 707 of file translator_bg.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorBulgarian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 707 of file translator_bg.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorBulgarian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 715 of file translator_bg.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorBulgarian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 715 of file translator_bg.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 597 of file translator_bg.h.
    { return " "; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 597 of file translator_bg.h.
    { return " "; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorBulgarian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 94 of file translator_bg.h.
    { return ", "; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorBulgarian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 94 of file translator_bg.h.
    { return ", "; }
trRelatedPages() [1/2]
virtual QCString TranslatorBulgarian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 228 of file translator_bg.h.
    { return " "; }
trRelatedPages() [2/2]
virtual QCString TranslatorBulgarian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 228 of file translator_bg.h.
    { return " "; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorBulgarian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 350 of file translator_bg.h.
    { return " :"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorBulgarian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 350 of file translator_bg.h.
    { return " :"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorBulgarian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 98 of file translator_bg.h.
    { return "(, .)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorBulgarian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 98 of file translator_bg.h.
    { return "(, .)"; }
trRemarks() [1/2]
virtual QCString TranslatorBulgarian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 974 of file translator_bg.h.
    {
      return "";
    }
trRemarks() [2/2]
virtual QCString TranslatorBulgarian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 974 of file translator_bg.h.
    {
      return "";
    }
trReturns() [1/2]
virtual QCString TranslatorBulgarian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 548 of file translator_bg.h.
    { return ""; }
trReturns() [2/2]
virtual QCString TranslatorBulgarian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 548 of file translator_bg.h.
    { return ""; }
trReturnValues() [1/2]
virtual QCString TranslatorBulgarian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 792 of file translator_bg.h.
    { return " "; }
trReturnValues() [2/2]
virtual QCString TranslatorBulgarian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 792 of file translator_bg.h.
    { return " "; }
trRTFansicp() [1/2]
virtual QCString TranslatorBulgarian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1185 of file translator_bg.h.
    {
      return "1251";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorBulgarian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1185 of file translator_bg.h.
    {
      return "1251";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorBulgarian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1194 of file translator_bg.h.
    {
      return "204";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorBulgarian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1194 of file translator_bg.h.
    {
      return "204";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorBulgarian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1200 of file translator_bg.h.
    {
      return " ";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorBulgarian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1200 of file translator_bg.h.
    {
      return " ";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorBulgarian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1333 of file translator_bg.h.
    {
      return "";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorBulgarian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1333 of file translator_bg.h.
    {
      return "";
    }
trSearch() [1/2]
virtual QCString TranslatorBulgarian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 236 of file translator_bg.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorBulgarian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 236 of file translator_bg.h.
    { return ""; }
trSearching() [1/2]
virtual QCString TranslatorBulgarian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1775 of file translator_bg.h.
    {
      return "...";
    }
trSearching() [2/2]
virtual QCString TranslatorBulgarian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1775 of file translator_bg.h.
    {
      return "...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorBulgarian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1465 of file translator_bg.h.
    {
      return ":";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorBulgarian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1465 of file translator_bg.h.
    {
      return ":";
    }
trSearchResults() [1/2]
virtual QCString TranslatorBulgarian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1446 of file translator_bg.h.
    {
      if (numDocuments==0)
      {
        return " , .";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> , .";
      }
      else
      {
        return " <b>$num</b> , . "
               " - .";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorBulgarian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1446 of file translator_bg.h.
    {
      if (numDocuments==0)
      {
        return " , .";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> , .";
      }
      else
      {
        return " <b>$num</b> , . "
               " - .";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorBulgarian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1434 of file translator_bg.h.
    {
      return " ";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorBulgarian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1434 of file translator_bg.h.
    {
      return " ";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorBulgarian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 552 of file translator_bg.h.
    { return " "; }
trSeeAlso() [2/2]
virtual QCString TranslatorBulgarian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 552 of file translator_bg.h.
    { return " "; }
trSequenceDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2147 of file translator_bg.h.
    {
        return " ";
    }
trSequenceDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2147 of file translator_bg.h.
    {
        return " ";
    }
trSequences() [1/2]
virtual QCString TranslatorBulgarian::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2143 of file translator_bg.h.
    {
        return "";
    }
trSequences() [2/2]
virtual QCString TranslatorBulgarian::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2143 of file translator_bg.h.
    {
        return "";
    }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorBulgarian::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1999 of file translator_bg.h.
    {
      // single is true implies a single file
      QCString result=(QCString)" "
                                " ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorBulgarian::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1999 of file translator_bg.h.
    {
      // single is true implies a single file
      QCString result=(QCString)" "
                                " ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorBulgarian::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1985 of file translator_bg.h.
    {
      QCString result=(QCString)sName;
      result+=" ";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorBulgarian::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1985 of file translator_bg.h.
    {
      QCString result=(QCString)sName;
      result+=" ";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorBulgarian::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1970 of file translator_bg.h.
    { return " "; }
trServices() [2/2]
virtual QCString TranslatorBulgarian::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1970 of file translator_bg.h.
    { return " "; }
trSignals() [1/2]
virtual QCString TranslatorBulgarian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 646 of file translator_bg.h.
    { return ""; }
trSignals() [2/2]
virtual QCString TranslatorBulgarian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 646 of file translator_bg.h.
    { return ""; }
trSince() [1/2]
virtual QCString TranslatorBulgarian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 987 of file translator_bg.h.
    {
      return "";
    }
trSince() [2/2]
virtual QCString TranslatorBulgarian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 987 of file translator_bg.h.
    {
      return "";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorBulgarian::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2008 of file translator_bg.h.
    {
      // single is true implies a single file
      QCString result=(QCString)" "
                                " ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorBulgarian::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2008 of file translator_bg.h.
    {
      // single is true implies a single file
      QCString result=(QCString)" "
                                " ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorBulgarian::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1992 of file translator_bg.h.
    {
      QCString result=(QCString)sName;
      result+=" ";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorBulgarian::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1992 of file translator_bg.h.
    {
      QCString result=(QCString)sName;
      result+=" ";
      return result;
    }
trSliceInterfaces() [1/2]
virtual QCString TranslatorBulgarian::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2159 of file translator_bg.h.
    {
        return "";
    }
trSliceInterfaces() [2/2]
virtual QCString TranslatorBulgarian::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2159 of file translator_bg.h.
    {
        return "";
    }
trSourceFile() [1/2]
virtual QCString TranslatorBulgarian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1476 of file translator_bg.h.
    {
      return filename + " ";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorBulgarian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1476 of file translator_bg.h.
    {
      return filename + " ";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorBulgarian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1405 of file translator_bg.h.
    {
      return " ";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorBulgarian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1405 of file translator_bg.h.
    {
      return " ";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorBulgarian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1391 of file translator_bg.h.
    {
      return " ";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorBulgarian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1391 of file translator_bg.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorBulgarian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 946 of file translator_bg.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorBulgarian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 946 of file translator_bg.h.
    {
      return " ";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorBulgarian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 660 of file translator_bg.h.
    { return " "; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorBulgarian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 660 of file translator_bg.h.
    { return " "; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorBulgarian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 934 of file translator_bg.h.
    {
      return " ";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorBulgarian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 934 of file translator_bg.h.
    {
      return " ";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorBulgarian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 654 of file translator_bg.h.
    { return " "; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorBulgarian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 654 of file translator_bg.h.
    { return " "; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorBulgarian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 922 of file translator_bg.h.
    {
      return " ";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorBulgarian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 922 of file translator_bg.h.
    {
      return " ";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorBulgarian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_bg.h.
    { return " "; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorBulgarian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_bg.h.
    { return " "; }
trStructDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2203 of file translator_bg.h.
    {
        return " ";
    }
trStructDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2203 of file translator_bg.h.
    {
        return " ";
    }
trStructIndex() [1/2]
virtual QCString TranslatorBulgarian::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2191 of file translator_bg.h.
    {
        return " ";
    }
trStructIndex() [2/2]
virtual QCString TranslatorBulgarian::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2191 of file translator_bg.h.
    {
        return " ";
    }
trStructList() [1/2]
virtual QCString TranslatorBulgarian::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2195 of file translator_bg.h.
    {
        return " ";
    }
trStructList() [2/2]
virtual QCString TranslatorBulgarian::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2195 of file translator_bg.h.
    {
        return " ";
    }
trStructListDescription() [1/2]
virtual QCString TranslatorBulgarian::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2199 of file translator_bg.h.
    {
        return " :";
    }
trStructListDescription() [2/2]
virtual QCString TranslatorBulgarian::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2199 of file translator_bg.h.
    {
        return " :";
    }
trStructs() [1/2]
virtual QCString TranslatorBulgarian::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2187 of file translator_bg.h.
    {
        return "";
    }
trStructs() [2/2]
virtual QCString TranslatorBulgarian::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2187 of file translator_bg.h.
    {
        return "";
    }
trSubprogram() [1/2]
virtual QCString TranslatorBulgarian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1739 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=":"; else result+=":";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorBulgarian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1739 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (singular) result+=":"; else result+=":";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1611 of file translator_bg.h.
    { return "/ "; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1611 of file translator_bg.h.
    { return "/ "; }
trSubprograms() [1/2]
virtual QCString TranslatorBulgarian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1605 of file translator_bg.h.
    { return "/"; }
trSubprograms() [2/2]
virtual QCString TranslatorBulgarian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1605 of file translator_bg.h.
    { return "/"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorBulgarian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1877 of file translator_bg.h.
    { return " "; }
trTemplateParameters() [2/2]
virtual QCString TranslatorBulgarian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1877 of file translator_bg.h.
    { return " "; }
trTest() [1/2]
virtual QCString TranslatorBulgarian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1079 of file translator_bg.h.
    {
      return "";
    }
trTest() [2/2]
virtual QCString TranslatorBulgarian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1079 of file translator_bg.h.
    {
      return "";
    }
trTestList() [1/2]
virtual QCString TranslatorBulgarian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1084 of file translator_bg.h.
    {
      return " ";
    }
trTestList() [2/2]
virtual QCString TranslatorBulgarian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1084 of file translator_bg.h.
    {
      return " ";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorBulgarian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 143 of file translator_bg.h.
    { return " "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorBulgarian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 143 of file translator_bg.h.
    { return " "; }
trTodo() [1/2]
virtual QCString TranslatorBulgarian::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 956 of file translator_bg.h.
    {
      return " ";
    }
trTodo() [2/2]
virtual QCString TranslatorBulgarian::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 956 of file translator_bg.h.
    {
      return " ";
    }
trTodoList() [1/2]
virtual QCString TranslatorBulgarian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 961 of file translator_bg.h.
    {
      return " ";
    }
trTodoList() [2/2]
virtual QCString TranslatorBulgarian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 961 of file translator_bg.h.
    {
      return " ";
    }
trType() [1/2]
virtual QCString TranslatorBulgarian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1728 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorBulgarian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1728 of file translator_bg.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorBulgarian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1747 of file translator_bg.h.
    {
      return " ";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorBulgarian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1747 of file translator_bg.h.
    {
      return " ";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 482 of file translator_bg.h.
    { return " "; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 482 of file translator_bg.h.
    { return " "; }
trTypedefs() [1/2]
virtual QCString TranslatorBulgarian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 446 of file translator_bg.h.
    { return " "; }
trTypedefs() [2/2]
virtual QCString TranslatorBulgarian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 446 of file translator_bg.h.
    { return " "; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1599 of file translator_bg.h.
    { return " "; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1599 of file translator_bg.h.
    { return " "; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorBulgarian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 500 of file translator_bg.h.
    { return " "; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorBulgarian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 500 of file translator_bg.h.
    { return " "; }
trVariables() [1/2]
virtual QCString TranslatorBulgarian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 464 of file translator_bg.h.
    { return ""; }
trVariables() [2/2]
virtual QCString TranslatorBulgarian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 464 of file translator_bg.h.
    { return ""; }
trVersion() [1/2]
virtual QCString TranslatorBulgarian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 540 of file translator_bg.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorBulgarian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 540 of file translator_bg.h.
    { return ""; }
trVhdlType() [1/2]
virtual QCString TranslatorBulgarian::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2046 of file translator_bg.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "";
          else return "";
        case VhdlDocGen::PACKAGE:
          if (single) return "";
          else return "";
        case VhdlDocGen::SIGNAL:
          if (single) return "";
          else return "";
        case VhdlDocGen::COMPONENT:
          if (single) return "";
          else return "";
        case VhdlDocGen::CONSTANT:
          if (single) return "";
          else return "";
        case VhdlDocGen::ENTITY:
          if (single) return "";
          else return "";
        case VhdlDocGen::TYPE:
          if (single) return "";
          else return "";
        case VhdlDocGen::SUBTYPE:
          if (single) return "";
          else return "";
        case VhdlDocGen::FUNCTION:
          if (single) return "";
          else return "";
        case VhdlDocGen::RECORD:
          if (single) return "";
          else return "";
        case VhdlDocGen::PROCEDURE:
          if (single) return "";
          else return "";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "";
          else return "";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "";
          else return "";
        case VhdlDocGen::PROCESS:
          if (single) return "";
          else return "";
        case VhdlDocGen::PORT:
          if (single) return "";
          else return "";
        case VhdlDocGen::USE:
          if (single) return "use ";
          else return "Use ";
        case VhdlDocGen::GENERIC:
          if (single) return "";
          else return "";
        case VhdlDocGen::PACKAGE_BODY:
          return " ";
        case VhdlDocGen::UNITS:
          return "";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return " ";
          else return " ";
        case VhdlDocGen::VFILE:
          if (single) return "";
          else return "";
        case VhdlDocGen::GROUP:
          if (single) return "";
          else return "";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "";
          else return "";
        case VhdlDocGen::ALIAS:
          if (single) return "";
          else return "";
        case VhdlDocGen::CONFIG:
          if (single) return "";
          else return "";
        case VhdlDocGen::MISCELLANEOUS:
          return "";
        case VhdlDocGen::UCF_CONST:
          return "";
        default:
          return "";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trVhdlType() [2/2]
virtual QCString TranslatorBulgarian::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2046 of file translator_bg.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "";
          else return "";
        case VhdlDocGen::PACKAGE:
          if (single) return "";
          else return "";
        case VhdlDocGen::SIGNAL:
          if (single) return "";
          else return "";
        case VhdlDocGen::COMPONENT:
          if (single) return "";
          else return "";
        case VhdlDocGen::CONSTANT:
          if (single) return "";
          else return "";
        case VhdlDocGen::ENTITY:
          if (single) return "";
          else return "";
        case VhdlDocGen::TYPE:
          if (single) return "";
          else return "";
        case VhdlDocGen::SUBTYPE:
          if (single) return "";
          else return "";
        case VhdlDocGen::FUNCTION:
          if (single) return "";
          else return "";
        case VhdlDocGen::RECORD:
          if (single) return "";
          else return "";
        case VhdlDocGen::PROCEDURE:
          if (single) return "";
          else return "";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "";
          else return "";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "";
          else return "";
        case VhdlDocGen::PROCESS:
          if (single) return "";
          else return "";
        case VhdlDocGen::PORT:
          if (single) return "";
          else return "";
        case VhdlDocGen::USE:
          if (single) return "use ";
          else return "Use ";
        case VhdlDocGen::GENERIC:
          if (single) return "";
          else return "";
        case VhdlDocGen::PACKAGE_BODY:
          return " ";
        case VhdlDocGen::UNITS:
          return "";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return " ";
          else return " ";
        case VhdlDocGen::VFILE:
          if (single) return "";
          else return "";
        case VhdlDocGen::GROUP:
          if (single) return "";
          else return "";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "";
          else return "";
        case VhdlDocGen::ALIAS:
          if (single) return "";
          else return "";
        case VhdlDocGen::CONFIG:
          if (single) return "";
          else return "";
        case VhdlDocGen::MISCELLANEOUS:
          return "";
        case VhdlDocGen::UCF_CONST:
          return "";
        default:
          return "";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
virtual QCString TranslatorBulgarian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 536 of file translator_bg.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorBulgarian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 536 of file translator_bg.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorBulgarian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 666 of file translator_bg.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorBulgarian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 666 of file translator_bg.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_bg.h
doxygen/src/translator_bg.h